### PR TITLE
mediatek: switch to fitblk for JDCloud RE-CP-03

### PR DESCRIPTION
**Pull request by 1715173329**
Use the new fitblk driver.

### CODE REVIEW

**Comment by ptpt52** [comment]
upgrade from old version supported?

**Comment by 1715173329** [comment]
> upgrade from old version supported?

Yes.

**Comment by cyyself** [comment]
> upgrade from old version supported?

I confirmed and tested that it is supported using sysupgrade. We can also roll back to old versions using sysupgrade if we didn't write a new u-boot to use fitblk in bootargs.

**Comment by 1715173329** [comment]
Need to run `fw_setenv bootargs root=/dev/mmcblk0p65` in initramfs.

**Comment by cyyself** [comment]
> Need to run `fw_setenv bootargs root=/dev/mmcblk0p65` in initramfs.

Please don't forget to add `rootwait`.

**Comment by cyyself** [comment]
> > > Need to run `fw_setenv bootargs root=/dev/mmcblk0p65` in initramfs.
> > 
> > 
> > Please don't forget to add `rootwait`.
> 
> `fw_setenv bootargs root=/dev/mmcblk0p65 rootwait` ?

Yes. I currently use these bootargs on my JDCloud RE-CP-03. I don't see any boot failures on reboot. But without rootwait, it might be 70% of the boot that fails to find rootfs on Kernel v6.1.

```console
root@MisakaPortal:~# ubus call system board
{
	"kernel": "6.1.82",
	"hostname": "MisakaPortal",
	"system": "ARMv8 Processor rev 4",
	"model": "JDCloud RE-CP-03",
	"board_name": "jdcloud,re-cp-03",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "OpenWrt",
		"version": "SNAPSHOT",
		"revision": "r25773-766ec55966",
		"target": "mediatek/filogic",
		"description": "OpenWrt SNAPSHOT r25773-766ec55966"
	}
}
root@MisakaPortal:~# fw_printenv bootargs
bootargs=root=/dev/mmcblk0p65 rootwait
```

**Comment by itq5** [comment]
UBOOT需要在哪里下载？

**Pull request merged**
