### PR TITLE
wifi-scripts: fix FILS AKM selection with EAP-192

### PR DESCRIPTION
**Pull request by cotequeiroz**
Fix netifd hostapd.sh selection of FILS-SHA384 algorithm with eap-192.

This should be trivial.

### CODE REVIEW

**Comment by Ansuel** [comment]
@cotequeiroz should we also backport this?

**Comment by cotequeiroz** [comment]
I wouldn't rush a release because of this, but it should be fixed--just a typo.

**Comment by Ansuel** [comment]
@cotequeiroz yep wasn't talking about a release but only if the same problem is present on some stable branch

**Comment by cotequeiroz** [comment]
My bad, sorry.  It should be picked to 23.05.

**Comment by cotequeiroz** [comment]
But it is not a straight cherry pick, as this script was moved from hostapd to wifi-scripts in main, but not in 23.05.  I'll open a new PR for it.

**Comment by cotequeiroz** [comment]
Here it is: #14659

**Pull request merged**
