### PR TITLE
mvebu: update WRT3200ACM (Rango) dts

### PR DESCRIPTION
**Pull request by nitroshift**
Include definition for future implementation of Parser and Classifier, define Marvell CESA and modify Power LED and SATA LED addresses.

Signed-off-by: Sebastian Careba <nitroshift@yahoo.com>

### CODE REVIEW

**Review by seragh — COMMENTED** [review]
You are opening braces in the first hunk without closing them later, so this very likely won't compile. Some whitespace errors also made it into that hunk.

**Comment by nitroshift** [comment]
Fixed.

**Comment by nitroshift** [comment]
@wongsyrone 

Those properties are defined in the armada-38x.dtsi.

**Comment by nitroshift** [comment]
Fixed.

**Comment by wongsyrone** [comment]
Hi, I tested this change on my router, it will cause infinite rebooting. Can you check it?

**Comment by nitroshift** [comment]
I will reopen this when I will have an unit to test on.

**Pull request closed without merging**
