### PR TITLE
realtek: default to 6.6

### PR DESCRIPTION
**Pull request by robimarko**
Now that there is 6.6 support for realtek, lets encourage testing it by making it default so 5.15 can be dropped ASAP.

### CODE REVIEW

**Comment by namiltd** [comment]
Also add a commit removing the 5.15 kernel for realtek.
Additionally another removing this kernel in target/inux/generic and the main/include/kernel-5.15 file.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by Neustradamus** [comment]
@robimarko: Top, thanks!

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/openwrt/openwrt/pull/16204
- https://github.com/openwrt/openwrt/pull/16391
- https://github.com/openwrt/openwrt/pull/16408

**Pull request merged**
