### PR TITLE
wireguard: permit storing private & preshared keys in files

### PR DESCRIPTION
**Pull request by LukaszDargiewicz**
Add support for storing private keys and preshared keys in files, hiding secrets from uci configuration

This is rebased pull request #1391 

Signed-off-by: Lukasz Dargiewicz <lukasz.dargiewicz@gmail.com>

### CODE REVIEW

**Comment by ynezz** [comment]
> This is rebased pull request #1391

What has changed since then https://github.com/openwrt/openwrt/pull/1391#issuecomment-475919754 ?

**Comment by LukaszDargiewicz** [comment]
> > This is rebased pull request #1391
> 
> What has changed since then [#1391 (comment)](https://github.com/openwrt/openwrt/pull/1391#issuecomment-475919754) ?

Code formatting and clean single commit here.
Luci part updated and ported to js since https://github.com/openwrt/luci/pull/2207#issuecomment-512146429

**Review by CodeFetch — APPROVED** [review]
Looks good to me

**Review by ynezz — CHANGES_REQUESTED** [review]
* missing commit description
* partially answered question https://github.com/openwrt/openwrt/pull/2416#issuecomment-533237352

I've closed the previous PR, because it didn't made sense to me and still doesn't make much sense to me, I'm missing proper use case for this.  Are we going to store other secrets now stored in the UCI like for example PSKs into the separate files as well?

**Comment by adrianschmutzler** [comment]
As for the last PR, this has received no feedback despite the already known opinion of ynezz, so I'm closing this now for effectively the same reason why #1391 was closed.

**Pull request closed without merging**
