### PR TITLE
prereq-build: allow symlinks to update

### LINKED ISSUE #12610: Incorrect links in staging_dir
### Describe the bug

I am compiling the latest snapshot and get an error. It seems that the `python3` link in my `staging_dir`  points to `python3.10`, but my system switched to `python3.11` already. How do I fix the links in staging_dir?

```
:~/openwrt> uname -a
Linux blaq 6.3.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:42 +0000 x86_64 GNU/Linux
:~/openwrt> ls -la /usr/bin/python3*
lrwxrwxrwx 1 root root    10 Apr  5 16:52 /usr/bin/python3 -> python3.11
-rwxr-xr-x 1 root root 14280 Apr  5 16:52 /usr/bin/python3.11
-rwxr-xr-x 1 root root  3248 Apr  5 16:52 /usr/bin/python3.11-config
lrwxrwxrwx 1 root root    17 Apr  5 16:52 /usr/bin/python3-config -> python3.11-config

```

I proceed to update OpenWrt as follows:

```
:~/openwrt> git pull
Already up to date.
:~/openwrt> make menuconfig
:~/openwrt> ./scripts/feeds update -a && ./scripts/feeds install -a && make -j1 V=sc
[... some lines skipped ...]
make[3]: Entering directory '/home/draug/openwrt/tools/pkgconf'
/home/draug/openwrt/staging_dir/host/bin/sed -e "s|@CC@|'gcc',|" -e "s|@CXX@|'g++',|" -e "s|@PKGCONFIG@|/home/draug/openwrt/staging_dir/host/bin/pkg-config|" -e "s|@CMAKE@|/home/draug/openwrt/staging_dir/host/bin/cmake|" -e "s|@PYTHON@|/home/draug/openwrt/staging_dir/host/bin/python3|" -e "s|@CFLAGS@|'-O2', '-I/home/draug/openwrt/staging_dir/host/include', '-I/home/draug/openwrt/staging_dir/host/include',|" -e "s|@CXXFLAGS@|'-I/home/draug/openwrt/staging_dir/host/include',|" -e "s|@LDFLAGS@|'-L/home/draug/openwrt/staging_dir/host/lib',|" -e "s|@PREFIX@|/home/draug/openwrt/staging_dir/host|" < /home/draug/openwrt/staging_dir/host/lib/meson/openwrt-native.txt.in > /home/draug/openwrt/build_dir/host/pkgconf-1.9.5/openwrt-native.txt
/home/draug/openwrt/staging_dir/host/bin/python3 /home/draug/openwrt/staging_dir/host/bin/meson.py  --native-file /home/draug/openwrt/build_dir/host/pkgconf-1.9.5/openwrt-native.txt -Ddefault_library=static -Dtests=disabled /home/draug/openwrt/build_dir/host/pkgconf-1.9.5/openwrt-build /home/draug/openwrt/build_dir/host/pkgconf-1.9.5/openwrt-build/..
bash: line 1: /home/draug/openwrt/staging_dir/host/bin/python3: No such file or directory
make[3]: *** [Makefile:42: /home/draug/openwrt/build_dir/host/pkgconf-1.9.5/.configured] Error 127
make[3]: Leaving directory '/home/draug/openwrt/tools/pkgconf'
time: tools/pkgconf/compile#0.06#0.01#0.06
    ERROR: tools/pkgconf failed to build.
make[2]: *** [tools/Makefile:226: tools/pkgconf/compile] Error 1
make[2]: Leaving directory '/home/draug/openwrt'
make[1]: *** [tools/Makefile:222: /home/draug/openwrt/staging_dir/host/stamp/.tools_compile_nyyynyynnnyyynynyyyyyyynyyynnynyynnynnyyyyyyyyyyyyyyyyynynnyyyyyyy] Error 2
make[1]: Leaving directory '/home/draug/openwrt'
make: *** [/home/draug/openwrt/include/toplevel.mk:231: world] Error 2
```

I look at the cause of the error:
```
:~/openwrt> ls -la /home/draug/openwrt/staging_dir/host/bin/python3
lrwxrwxrwx 1 draug users 19 Mar  8  2022 /home/draug/openwrt/staging_dir/host/bin/python3 -> /usr/bin/python3.10
:~/openwrt> ls -la /usr/bin/python3*
lrwxrwxrwx 1 root root    10 Apr  5 16:52 /usr/bin/python3 -> python3.11
-rwxr-xr-x 1 root root 14280 Apr  5 16:52 /usr/bin/python3.11
-rwxr-xr-x 1 root root  3248 Apr  5 16:52 /usr/bin/python3.11-config
lrwxrwxrwx 1 root root    17 Apr  5 16:52 /usr/bin/python3-config -> python3.11-config
```

### OpenWrt version

draug@blaq:~/openwrt> git log | head -1 commit 7ad1fa12efd99dd2a4e4ffa01365280f63e99e55

### OpenWrt target/subtarget

lantiq / xrx200

### Device

BT Home Hub 5A

### Image kind

Self-built image

### Steps to reproduce

_No response_

### Actual behaviour

_No response_

### Expected behaviour

_No response_

### Additional info

_No response_

### Diffconfig

```text
#!/bin/sh
make ./scripts/config/conf >/dev/null || { make ./scripts/config/conf; exit 1; }
grep \^CONFIG_TARGET_ .config | head -n3 > tmp/.diffconfig.head
grep \^CONFIG_TARGET_DEVICE_ .config >> tmp/.diffconfig.head
grep '^CONFIG_ALL=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_ALL_KMODS=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_ALL_NONSHARED=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_DEVEL=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_TOOLCHAINOPTS=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_BUSYBOX_CUSTOM=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_TARGET_PER_DEVICE_ROOTFS=y' .config >> tmp/.diffconfig.head
./scripts/config/conf --defconfig=tmp/.diffconfig.head -w tmp/.diffconfig.stage1 Config.in >/dev/null
./scripts/kconfig.pl '>+' tmp/.diffconfig.stage1 .config >> tmp/.diffconfig.head
./scripts/config/conf --defconfig=tmp/.diffconfig.head -w tmp/.diffconfig.stage2 Config.in >/dev/null
./scripts/kconfig.pl '>' tmp/.diffconfig.stage2 .config >> tmp/.diffconfig.head
cat tmp/.diffconfig.head
rm -f tmp/.diffconfig tmp/.diffconfig.head
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by mcprat**
Fixes #12610 

to test:
replace a symlink in staging_dir/host/bin with a bad path
`rm -f staging_dir/host/.prereq-build`
`make prereq`
new symlink!

### CODE REVIEW

**Comment by mpratt14** [comment]
ping @Ansuel @dhewg 

thoughts?

**Comment by mpratt14** [comment]
@Ansuel @ynezz it would be nice to have this before branch

if you don't like that this relies on the format of `ls` I have a Perl script alternative

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by mpratt14** [comment]
yeah that's strange...

@guidosarducci does your system have both `install` and `ginstall` matching the check, or is it possible you have one of them in multiple paths?

workaround is ok I guess, but maybe we should split it so macos looks only for `ginstall`?

**Comment by guidosarducci** [comment]
@mpratt14 No, I'm not using MacOS but build locally on Ubuntu without issue. The problem happens on the buildbots during CI of my PR. The workaround above isn't an option, as I'd need to PR the change I believe. Instead, I rebased onto master, dropping your commits, and force-pushed my PR again. The problem didn't reoccur during CI (but I found an NLS issue instead... 😞 )

**Comment by mpratt14** [comment]
ah ok I see

is it just CI or someone can reproduce on a local system?

I happened in my fork's CI too
https://github.com/mpratt14/openwrt/actions/runs/4989579405/jobs/8933682006#step:5:56

going to use this branch to diagnose

**Comment by mpratt14** [comment]
it almost seems like the CI has 3 different `install` or `ginstall`, one failing the check and the other two working

check for `install` fails the first time but succeeds the second time...weird...

```
Checking 'install'... 
install (GNU coreutils) 9.3
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
lrwxr-xr-x  1 runner  staff  23 May 22 21:04 /Volumes/OpenWrt/openwrt/staging_dir/host/bin/install -> /usr/local/bin/ginstall
install (GNU coreutils) 9.3
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
lrwxr-xr-x  1 runner  staff  16 May 22 21:04 /Volumes/OpenWrt/openwrt/staging_dir/host/bin/install -> /usr/bin/install
failed.]
```

**Comment by mpratt14** [comment]
https://github.com/mpratt14/openwrt/actions/runs/5051252297/jobs/9062888672
starting line 1943 in Make prereq

1. there is duplicate paths
2. line 1962 should have output after, command is `/usr/bin/install --version`
3. later at line 2027, it tries `/usr/bin/install --version` again and there is output

It's not even a matter of that the CI has a version of install that is not from GNU, but that the CI is misbehaving.
We ought to tell github about this...

for now, switching the order of checking `ginstall` then `install` seems like the most appropriate fix
@ynezz do you want to do it? also your thoughts?

this is what I added to make prereq to get this output

```
                        echo ------ path ------; \
                        echo $(subst $(space),:,$(filter-out $(STAGING_DIR_HOST)/%,$(subst :,$(space),$(PATH)))); \
                        echo ------ begin which install ------; \
                        which -a install; \
                        echo ------ end which install ------; \
                        echo ------ begin which ginstall ------; \
                        which -a ginstall; \
                        echo ------ end which ginstall ------; \
                        echo ------ show bin ------; \
                        echo "$$$$$$$$bin"; \
                        echo ------ ls bin ------; \
                        ls -lsa "$$$$$$$$bin"; \
                        echo ------ show cmd ------; \
                        echo "$$$$$$$$cmd"; \
                        echo ------ do cmd ------; \
                        $$$$$$$$cmd; \
                        echo ------ do bin version ------; \
                        $$$$$$$$bin --version; \
```

**Comment by mpratt14** [comment]
PR for this is up #12700

**Comment by ynezz** [comment]
> It's not even a matter of that the CI has a version of install that is not from GNU, but that the CI is misbehaving.

BTW all macOS users seems to be affected, it's not only about CI. Its clearly regression caused by this PR, reverting it fixes the problem. 

> 2. line 1962 should have output after, command is /usr/bin/install --version

Ok, but then it should be happy with `ginstall`, right? Why is that not working?

> 3. later at line 2027, it tries /usr/bin/install --version again and there is output

So what it fails then? It should go with that, right?

IMO the clue is probably here:

```
------ do bin version ------
install (GNU coreutils) 9.3
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
lrwxr-xr-x  1 runner  staff  16 May 22 23:12 /Volumes/OpenWrt/openwrt/staging_dir/host/bin/install -> /usr/bin/install
failed.
```

I interpret this in the following way, we've found a suitable binary, created a symlink, but still ended with `failed` result? This leads us to the [following part](https://github.com/mpratt14/openwrt/blob/73e853191c1a4359d991edd8a080e1f6ec898e4c/include/prereq.mk#L131-L133):

```make
ln -sf "$$$$$$$$bin" "$(STAGING_DIR_HOST)/bin/$(strip $(1))"; \
ls -dl -- $(STAGING_DIR_HOST)/bin/$(strip $(1)); \
exit 1; \
```

That `exit 1` seems bogus to me, its clearly a working case, so should be `exit 0` ?

**Comment by ynezz** [comment]
> That exit 1 seems bogus to me, its clearly a working case, so should be exit 0 ?

Seems to be the culprit https://github.com/ynezz/openwrt/actions/runs/5057059440/jobs/9075343176?pr=4#step:5:1020

**Comment by mpratt14** [comment]
just be to clear, I changed the prereq check so that it will make sure that the target of the link is the same if it is checked again, and if not it gets updated and checked again to be the same, and if not, something is wrong with the either the *program* or the *machine*, would you agree?

**Comment by mpratt14** [comment]
also by the way, another solution would just be to remove a check/symlink for install. if you read the commit that added it on GitHub (and Rosen's comment on it), we likely don't even need it anymore

**Comment by guidosarducci** [comment]
> I have yet to see what's happening to anyone's macos, is evidence only being posted in IRC or are some just saying it without providing verbose output like I did with the CI?

What are you looking for exactly? When I reported this, since no macos all I could provide on IRC was a CI link as you did: https://github.com/guidosarducci/openwrt/actions/runs/5042532195/jobs/9043268333.

I'll admit to being a little lost on the current state of understanding the problem/fix...

**Comment by mpratt14** [comment]
if I understand the reply from @ynezz correctly, he is claiming that this is also happening to someone's personal macos host, but I haven't seen anyone say that, so it must have been only mentioned on IRC without proof?

**Comment by ynezz** [comment]
@ldir-EDB0 I might have misinterpreted your message on IRC, could you make it clear whether you've hit this issue on your Mac or on the GitHub CI? It would help us track down the root of the problem and fix that properly. I've simply assumed, that you've hit that issue on your Mac as it was the case always before.

**Comment by ldir-EDB0** [comment]
It was native mac OS/hardware.  No CI involved.

The current master/main ;-) has resolved the issue... this is the 'exit 0' change.

**Comment by mpratt14** [comment]
OK understood, however, the `exit 1` is intentional, so something else is still not quite right...

@ldir-EDB0  does looking for "ginstall" first also resolve it for you (that is, while returning the `exit 1`)?

**Comment by ldir-EDB0** [comment]
Checking for ginstall first in prereq.mk resolves the missing install dependency check and allows a build to go through, however subsequent build attempts fail very early trying to applying kernel patches... the prereq check has flipped 4 or so binaries to something else, very bizarre.

**Comment by mpratt14** [comment]
> subsequent build attempts fail very early trying to applying kernel patches... the prereq check has flipped 4 or so binaries to something else

.....can we really blame prereq for that?

my commit is not that complicated, it pretty much just runs the checks twice at most, instead of just "once and if-and-only-if" the symlink doesn't exist already

**Comment by ldir-EDB0** [comment]
> > subsequent build attempts fail very early trying to applying kernel patches... the prereq check has flipped 4 or so binaries to something else
> 
> .....can we really blame prereq for that?
> 
> my commit is not that complicated, it pretty much just runs the checks twice at most, instead of just "once and if-and-only-if" the symlink doesn't exist already

I offered that as additional information that might help locate the problem.  This behaviour was not seen before the prereq update and disappears if the update is reverted...so yes I can 'blame' prereq for that change in behaviour.  Let's see what the behaviour is with the latest commits.

**Comment by mpratt14** [comment]
I meant specifically the kernel patches issue sounded like it would have nothing to do with prereq. I imagined that passing prereq checks means the symlinks are good and no other change. Perhaps I just misunderstood what you meant by "flipped".

Either way, we need more info, I don't think I can reproduce whatever you're currently seeing at this point.

**Pull request closed without merging**
