### PR TITLE
at91: kernel update to the level of support provided by linux4microchip-2022.10 kernel release

### PR DESCRIPTION
**Pull request by claudiubeznea**
Hi,

This pull request updates the kernel for AT91 device to the level of support
provided by linux4microchip-2022.10. The exception (at the moment) is
QSPI and WILC (the intention is to have these 2 also in subsequent pull
requests). Some of the patches included in this series are already in
upstream kernel, some or not (most notably here are the sound patches and
the new SAM9X7 SoC support).

Thank you,
Claudiu Beznea

### CODE REVIEW

**Comment by claudiubeznea** [comment]
Hi,

I know this is a huge pull request that may need more time for review.
Just want to know if it is left behind or doesn't comply with OpenWrt community rules
or anything else...

Thank  you,
Claudiu Beznea

**Comment by hauke** [comment]
If we add all these patches we also have to maintain them. This was already annoying for the layerscape target when it shipped with over 100 patches.

I would prefer to stay closer to the upstream kernel. If you really need some of these patches for some features or to support some new boards I am fine with adding them, but I would like to avoid to add all the patches from your BSP.

@claudiubeznea  Could you please have a look at #12058 too.

**Comment by claudiubeznea** [comment]
@hauke : I truly understand this has to be maintained. This is the reason I haven't introduced in this commit (as specified) QSPI patches from linux4microchip tree as it touches also core part of the subsystem. The patches in this PR touches only AT91 specific drivers (exception being audio part, I can get rid of it if you prefer).

It is first time I push kernel patches not yet upstreamed to OpenWrt so it wasn't clear to me how it will work. Not that it might count, on my side I periodically monitor the buildbot for at91 targets. If this PR will be accepted you can mention me every time there are issues so that I can look at it ASAP. 

With regards to the content of this PR, It contains upstreamed kernel patches but also not yet upstreamed one. From the 2nd category there are mostly patches for SAM9X7 SoC and it's evaluation board (which will end up at some point in upstream kernel) and these are distributed across different kernel subsystems. Audio patches not in kernel upstream are also there and some of these might not end in upstream kernel, thus, if you want I can get rid of them from this PR.

With regards to https://github.com/openwrt/openwrt/pull/12058, I just reviewed it. I tested v5.15 on all targets I have access to previously, when updating OpenWrt kernel for v5.15 and when preparing this PR.

If it happens to have patches that need my attention please mention me on github (I monitor the the mailing list but not the github).

Thank you,
Claudiu Beznea

**Comment by ynezz** [comment]
5.15 is over, we're now focusing on [6.1](https://github.com/openwrt/openwrt/issues/14546) so Claudiu, it would be really appreciated if you could prepare 6.1 kernel support for at91 target, thanks!

**Comment by robimarko** [comment]
@claudiubeznea Can you please take care of bumping to 6.1?

**Comment by robimarko** [comment]
Thanks for include devs that can possibly help

**Comment by robimarko** [comment]
@noglitch That was the OpenWrt project asking for help from Microchip in order to bump the at91 target to kernel 6.1 as we are moving away from kernel 5.15 and only few targets remain.

**Pull request closed without merging**
