### PR TITLE
build: add CycloneDX SBOM JSON support

### PR DESCRIPTION
**Pull request by ynezz**
CycloneDX is an open source standard developed by the OWASP foundation.
It supports a wide range of development ecosystems, a comprehensive set
of use cases, and focuses on automation, ease of adoption, and
progressive enhancement of SBOMs (Software Bill Of Materials) throughout
build pipelines.

So lets add support for CycloneDX SBOM for packages and images
manifests.

Uploading following SBOM files from local qualcommax/ipq807x Snapshot build (without external feeds):

[base/Packages.sbom-cyclonedx.json](https://github.com/openwrt/openwrt/files/13182709/Packages.sbom-cyclonedx.json)
[target/packages/Packages.sbom-cyclonedx.json](https://github.com/openwrt/openwrt/files/13182710/Packages.sbom-cyclonedx.json)
[target/openwrt-qualcommax-ipq807x.sbom-cyclonedx.json](https://github.com/openwrt/openwrt/files/13182713/openwrt-qualcommax-ipq807x.sbom-cyclonedx.json)

Provides following results in the Dependency-Track v4.9.0 

image

Setup of Dependency-Track is [relatively easy](https://docs.dependencytrack.org/getting-started/deploy-docker/#quickstart-docker-compose):

```
curl -LO https://dependencytrack.org/docker-compose.yml
docker-compose up -d
```

then wait a bit for init and head to http://localhost:8080/

### CODE REVIEW

**Comment by ynezz** [comment]
Importing SBOMs from qualcommax/ipq807x build:

[openwrt-qualcommax-ipq807x.sbom-cyclonedx.json](https://github.com/openwrt/openwrt/files/13181474/openwrt-qualcommax-ipq807x.sbom-cyclonedx.json)
[packages/Packages.sbom-cyclonedx.json](https://github.com/openwrt/openwrt/files/13181479/Packages.sbom-cyclonedx.json)
[base/Packages.sbom-cyclonedx.json](https://github.com/openwrt/openwrt/files/13181482/Packages.sbom-cyclonedx.json)

produced following overview in https://dependencytrack.org/

Screenshot from 2023-10-26 20-42-43

**Comment by lynxis** [comment]
I've also used the Dependency-Track image with OpenWrt but generated the stuff with https://github.com/ads-tec/sbom-openwrt.

Thanks for adding it to the build system!

**Comment by hauke** [comment]
The `PKG_CVE_FIXES` field was already proposed in #13646

**Comment by jow-** [comment]
LGTM

**Pull request merged**
