### PR TITLE
ipq40xx/mikrotik: adds wlan/WiFi lz77 decompress

### PR DESCRIPTION
**Pull request by MichaelUray**
ipq40xx/mikrotik: adds wlan/WiFi lz77 decompress

Fixes the no wireless issue for the MikroTik RouterBOARD hAP ac3 with lz77 compression

https://forum.openwrt.org/t/no-wireless-mikrotik-rbd53ig-5hacd2hnd/157763
https://forum.openwrt.org/t/lz77-in-mikrotik/91696

Applies the patch from [john-tho](https://github.com/john-tho/openwrt/pull/5) to which works fine on my hAP ac3 (RBD53iG-5HacD2HnD).

 ```
generic: platform/mikrotik: add wlan lz77 decompress

A number of new (or newly factory flashed) Mikrotik devices are using
LZ77 magic for wlan tag hard_config data.
New devices include the Chateau LTE12 [1], and ax devices [2]
Newly factory flashed devices may include the hap ac3 [3]

This can be seen in decoded OEM supout [4] dmesg:
"radio data lz77 decompressed from"…

Investigating an arm RouterOS flash.ko module, and supplied example
hard_config dumps, the format was determined via [5].

debug prints can be enabled in a DYNAMIC_DEBUG kernel build via the
kernel cmdline:

        chosen {
-               bootargs = "console=ttyS0,115200";
+               bootargs = "console=ttyS0,115200 dyndbg=\"file: drivers/platform/mikrotik/* +p\"";
        };

[1]: https://forum.openwrt.org/t/no-wireless-mikrotik-rbd53ig-5hacd2hnd/157763/4
[2]: https://forum.openwrt.org/t/mikrotik-routeros-v7-x-and-openwrt-sysupgrade/148072/17
[3]: https://forum.openwrt.org/t/adding-support-for-mikrotik-hap-ax2/133715/47
[4]: https://github.com/farseeker/go-mikrotik-rif
[5]: https://github.com/john-tho/routeros-wlan-lz77-decode

Signed-off-by: John Thomson <git@johnthomson.fastmail.com.au>
```

Signed-off-by: Michael Uray <mu@spamfence.net>

### CODE REVIEW

**Comment by robimarko** [comment]
Commit has formal issues, the title is not correct and SoB is missing, also this is not your code and the original author is not credited at all.

**Comment by MichaelUray** [comment]
This is my first pull-request and I have tried to follow [submitting patches](https://openwrt.org/submitting-patches), it looks not very successfully.
Could you please advise me how to correct that?

> the title is not correct 

Why is that? What needs to get changed?
I just looked up for the authors original title which is "generic: platform/mikrotik: add wlan lz77 decompress"
Would that fit better?

> SoB is missing

Not sure what this means.

> the original author is not credited at all

So far as I have seen is he mentioned in the source code like "Copyright (C) 2023 John Thomson".
I also have mention him in the signoff as well as in the git comment.
Where do I have to add his name as well?

**Comment by robimarko** [comment]
> the title is not correct
> 
> Why is that? What needs to get changed?
> I just looked up for the authors original title which is "generic: platform/mikrotik: add wlan lz77 decompress"
> Would that fit better?

Look at the actual commit title, its:
```
Signed-off-by: Michael Uray <mu@spamfence.net>
 ipq40xx/mikrotik: adds wlan/WiFi lz77 decompress
```
I am sure you just meant to use `ipq40xx/mikrotik: adds wlan/WiFi lz77 decompress`

> SoB is missing
> 
> Not sure what this means.

Signed-off-by in the commit, it's actually part of the title which is not correct as it goes at the bottom of the commit.

> the original author is not credited at all
> 
> So far as I have seen is he mentioned in the source code like "Copyright (C) 2023 John Thomson".
> I also have mention him in the signoff as well as in the git comment.
> Where do I have to add his name as well?

Considering that you just applied his patch [1], you should have kept it untouched or modified to apply but kept the original author as the commit author and just added your SoB in the commit.

[1] https://github.com/john-tho/openwrt/pull/5/commits/0100a75f06f142633a6b06c5418d8c253c17941

Also, the commit description doesn't really explain what is being done, but rather only what is being fixed.
This doesn't belong in the description at all:
```
modified:   target/linux/generic/files/drivers/platform/mikrotik/Makefile
modified:   target/linux/generic/files/drivers/platform/mikrotik/rb_hardconfig.c
new file:   target/linux/generic/files/drivers/platform/mikrotik/rb_hardconfig_lz77.c
new file:   target/linux/generic/files/drivers/platform/mikrotik/rb_hardconfig_lz77.h
modified:   target/linux/generic/files/drivers/platform/mikrotik/routerboot.h
```

@john-tho Considering you are the original author, is this code ready to be included?

**Comment by john-tho** [comment]
> is this code ready to be included?

My to do list for this:
- move variable declarations out of loop declarations to start of function for [picky compiler](https://github.com/aredn/aredn/pull/920/commits/de86ad528835860bd41f5a9d8523db157a3601ee)
- remove the LE build test (possibly introduce kernel Kconfig like `CONFIG_MIKROTIK_RB_SYSFS_WLAN_LZ77`—assuming not needed for the ramips Mikrotik devices). [This was reportedly required and functional on an ath79 device](https://github.com/john-tho/openwrt/pull/5#issuecomment-1702140515).
- technical review

I have just not found the time to get around to making and build testing them, then committing the time for the review process…

**Comment by robimarko** [comment]
@john-tho Any chance you had some time to work on this?

**Comment by MichaelUray** [comment]
@john-tho since I am not able to provide the required code quality, do you see a chance to provide a proper commit?
How should I go ahead here, should I close this commit and you take over there?

**Pull request closed without merging**
