### PR TITLE
arm-trusted-firmware-mvebu: general updates

### PR DESCRIPTION
**Pull request by robimarko**
We are currently using outdated components for the `mvebu` ATF, and ATF itself is outdated.

So, this patch series updates the individual components first including the CM3 toolchain and
then the ATF itself to the current v2.9 stable.

I have tested the image on Methode eDPU (Armada 3720)

### CODE REVIEW

**Comment by robimarko** [comment]
@dhewg You are probably interested

**Comment by dhewg** [comment]
I'm currently running this one:  [0001-arm-trusted-firmware-mvebu-update-stuff.patch.txt](https://github.com/openwrt/openwrt/files/12379464/0001-arm-trusted-firmware-mvebu-update-stuff.patch.txt)
I didn't bother with cryptopp nor the toolchain, but I did update mox-boot-builder. Feel free to add that hunk here.
But I guess that's a 98% Tested-By ;)

**Comment by robimarko** [comment]
@dhewg Great, I have added the Mox builder update as well.

**Comment by hauke** [comment]
Thank you for the pull request, I merge it into main in ebbcfd095d5c77bc67087854a696e887dec99769, ff671d318cfbec0d7c920f70e4b8565955e2994e, ef82e26d353fca8116d9dd0b49a6a0df811ab951, 84e9d49452b119b9b1ba61d1ae919d58f9632059, f6ca36df84da2476acc6c76b8c7438fc18984c5f and 67dacdd652538f2cf7e43a24c4b54694b96be284

**Pull request closed without merging**
