### PR TITLE
ramips: fix i2s clock unit from KHz to MHz

### PR DESCRIPTION
**Pull request by Vonger**
Signed-off-by: Qin Wei support@vocore.io

### CODE REVIEW

**Comment by ynezz** [comment]
@Vonger  Can you please add this missing bits so I can merge it? Thanks.

From https://openwrt.org/submitting-patches
>  * all commits must contain Signed-off-by: My Name <my@email.address> where you write your real name and real email address, in accordance with Section 11 of the Linux Kernel patches guide.

> * it will be committed to the source changelog, so it should explain to a competent reader why you made this commit. It will be useful for people searching the commit logs looking for a fix for their issue.

**Comment by Vonger** [comment]
Thank you for the information, I have updated it, if anything wrong, please let me know :)

**Comment by 981213** [comment]
You should add sign-off to your commit message instead of GitHub PR description :)

**Comment by Vonger** [comment]
> You should add sign-off to your commit message instead of GitHub PR description :)

how ....

**Comment by ynezz** [comment]
I don't want to waste more time on this so I've merged it into my staging tree https://git.openwrt.org/?p=openwrt/staging/ynezz.git;a=shortlog;h=refs/heads/staging, thanks!

**Pull request closed without merging**
