### PR TITLE
rockchip: add driver for hardware RNG

### PR DESCRIPTION
**Pull request by dangowrt**
Rockchip SoCs used to have a random number generator as part of their crypto device, and support for it has to be added to the corresponding driver.

Newer Rockchip SoCs like the RK3568 have an independent True Random Number Generator device. Import pending patchset which adds a driver for it, include it in Kconfig and enable it in the device tree.

Doing so significantly reduces the time needed to boot devices based on those SoCs, from about 27 seconds until Ethernet is up and running to less than 13 seconds with a minimal snapshot image.

### CODE REVIEW

**Comment by dangowrt** [comment]
@1715173329 I'd appreciate a review and testing on other newer RockChip devices. I only got R5C here for testing.

**Comment by dick902** [comment]
Tested with NanoPi R5S, the boot time is significant reduced with this!
No problem found for me so far.

**Review by 1715173329 — APPROVED** [review]
Looks lovely.

**Review by dick902 — APPROVED** [review]

**Comment by namiltd** [comment]
Please also prepare this patch for kernel 6.6.

**Comment by 1715173329** [comment]
This can be easily rebased. #15212 is not merged yet.

**Comment by namiltd** [comment]
Parallel corrections to the code are always a problem :/

**Comment by 1715173329** [comment]
> the time needed to boot devices based on those SoCs

https://lore.kernel.org/u-boot/20241016100203.629713-1-alexthreed@gmail.com/

I guess this is the root cause.

**Pull request merged**
