### PR TITLE
toolchain: Use GCC 8 by default

### PR DESCRIPTION
**Pull request by diizzyy**
Switch to GCC 8 for all targets

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile and run tests on multiple platforms
https://github.com/openwrt/openwrt/pull/1846#issuecomment-466625657

**Comment by neheb** [comment]
This should be ready. I also pushed fixes for most compilation problems (ARC platform currently uses GCC8).

**Comment by neheb** [comment]
Probably the only package with any problems is libsocks: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/base/dante/compile.txt

I can't figure out how to fix it.

**Comment by adrianschmutzler** [comment]
This has been done in d509463816bf593de841398914f0d9d68bf76458.
Thanks for working on this and testing anyway.

**Pull request closed without merging**
