### PR TITLE
zip: make reproducible archive

### PR DESCRIPTION
**Pull request by mans0n**
build: image: properly deal with zip timestamp

Zip uses DOS timestamp to record last modification time of packed files,
and it is stored in local time. To make image builds reproducible, adjust
file mtime and set timezone to UTC. This can replace the hackish "--mtime"
option introduced in commit 18c9faa03211 ("tools: zip: add option for
reproducible archives").

Ref: https://wiki.debian.org/ReproducibleBuilds/TimestampsInZip

---

tools: zip: make encrypted archives reproducible

zip always try to generate new encryption header depending on execution
time and process id, which is far from being reproducible. This commit
changes the zip srand() seed to a fixed value to generate reproducible
random bytes for the encryption header. Our purpose is far from secure
archive encryption, so this would not be a big problem.

---

The goal of this patchset is to make [humax,e10 factory image](https://github.com/openwrt/openwrt/blob/0e32c6baf37688e8cefed5718afe13ec18f75233/target/linux/ramips/image/mt7621.mk#L656) reproducible.

I did not added the following options because:
* `-o`: This does not change the file content itself.
* `-Z store`: We are not concerned with reproducibility across different versions of zip.

Ref: https://stackoverflow.com/questions/62524167/zip-non-deterministic-result-in-linux

cc: @aparcar @mkresin

### CODE REVIEW

**Comment by aparcar** [comment]
Sounds good but can't we make Zip understand SOUCE DATE EPOCH and thereby have a predictable seed? That patch could even go upstream I'd hope

**Comment by mans0n** [comment]
I've also thought about it, but I concluded that would make the patch more hackish...
I've heard info-zip is not in very actively maintained state, but anyway your comment led me to this [reproducible patch](https://sourceforge.net/p/infozip/patches/25/). It seems much nicer, I might be able to extend it for the predictable seed in more decent way than I expected.

**Comment by aparcar** [comment]
I was able to get `busybox` upstream to merge a [similar patch](https://github.com/mirror/busybox/commit/947a22b33262c93e5c50286b723b9086a33a4c1f), we should try the same with `zip` :)

**Comment by mkresin** [comment]
I'm kind of confused, as I don't see how your change fixes the issue I've addressed with the now dropped patch.

Within ZIP archives the creation/modification date of each file is stored. To have a predictable creation/modification date I've added the mtime option. Otherwise the creation/modification date  of the to be compressed file is used, which is different each time time file is created.

I'm not entirely sure, but I recall to wrote patch to get the netgear_r6120 image reproducible. I suspect the image will not be reproducible as soon as I apply this patch.

**Comment by mkresin** [comment]
Nevermind, I spotted the relevant change. You are changing the file date with `touch -hcd` instead. Not sure which approach is more hackish.

Have you confirmed the touch magic is portable? MacOS comes in mind. The only reference to the MacOS touch suggests that [-d isn't available](https://ss64.com/osx/touch.html).

I still favour the mtime patch in compare to the touch workaround.

**Comment by aparcar** [comment]
@mkresin did you suggest your patches to upstream?

**Comment by svlobanov** [comment]
@mkresin 
Apple touch is BSD touch and '-d' is not available (I've checked it on my mac (big sur 11.6))

If we need '-d' option, we can use the same trick as it's done for bash (https://github.com/openwrt/openwrt/commit/3869ccbcc891a7185550a2a422e2db01fd994b7d ). We can just compile gnu coreutils touch if HOST_OS is Darwin (add as tools/touch)

**Comment by mkresin** [comment]
> @mkresin did you suggest your patches to upstream?

No. The mailinglist of the project is disabled and only a contact form left. There is some kind of bugtracker at the sourceforge page, but patches piling up without reaction since years. Seem to me a waste of time to suggest the patch there.

The project looks pretty dead.

**Comment by mkresin** [comment]
> @mkresin Apple touch is BSD touch and '-d' is not available (I've checked it on my mac (big sur 11.6))
> 
> If we need '-d' option, we can use the same trick as it's done for bash ([3869ccb](https://github.com/openwrt/openwrt/commit/3869ccbcc891a7185550a2a422e2db01fd994b7d) ). We can just compile gnu coreutils touch if HOST_OS is Darwin (add as tools/touch)
> 
> moreover, if you build openwrt on macos and follow wiki page (https://openwrt.org/docs/guide-developer/toolchain/buildroot.exigence.macosx ), then you will use GNU touch that supports '-d'
> 
> ```
> % echo $PATH
> /opt/homebrew/opt/findutils/libexec/gnubin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/opt/gettext/bin:/opt/homebrew/opt/gnu-getopt/bin:/opt/homebrew/opt/make/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/sergey/.nexustools:/Users/sergey/.nexustools
> 
> % which touch
> /opt/homebrew/opt/coreutils/libexec/gnubin/touch
> ```

Thanks for the testing!

@mans0n Do you agree that the we should keep the mtime option, considering the portability issue of the touch command? I tend to say, if it ain't broken don't fix it.

**Comment by aparcar** [comment]
We already maintain squashfs-kit which was dead for some time, I'd prefer using a different zip implementation instead of maintaining this one. @neheb or anyone else, ideas for alternatives?

**Comment by svlobanov** [comment]
> We already maintain squashfs-kit which was dead for some time, I'd prefer using a different zip implementation instead of maintaining this one. @neheb or anyone else, ideas for alternatives?

we can evaluate this one https://sourceforge.net/projects/sevenzip/ . p7zip is dead, but sevenzip is from 7-zip author. License looks good.

**Comment by mans0n** [comment]
> Have you confirmed the touch call is portable? MacOS comes in mind. The only reference to the MacOS touch I found, suggests that [-d isn't available](https://ss64.com/osx/touch.html).

Good point. The [reproducible-builds](https://reproducible-builds.org/docs/archives/) doc suggests to use `touch` for the purpose so I thought it would be safe to use, but it seems it is not always true.

> Do you agree that the we should keep the mtime option, considering the portability issue of the touch command? I tend to say, if it ain't broken don't fix it.

Agreed, but my goal is reproducible encryption, and I'm currently thinking of rewriting my srand() seed patch on top of this [patch](https://sourceforge.net/p/infozip/patches/25/) which utilizes `SOURCE_DATE_EPOCH ` env directly. That way we can also skip the extra `touch` command.

> we can evaluate this one https://sourceforge.net/projects/sevenzip/ . p7zip is dead, but sevenzip is from 7-zip author. License looks good.

I've also thought about replacing the info-zip with a well-maintained alternative, but I didn't know that 7-zip also supports the zip compression method, thanks. Still need to look whether it supports reproducible encryption, though.

**Comment by svlobanov** [comment]
>I've also thought about replacing the info-zip with a well-maintained alternative, but I didn't know that 7-zip also supports the zip compression method, thanks. Still need to look whether it supports reproducible encryption, though.

if you want just to check if it supports reproducible encryption, you can download precompiled binaries (form sf) for linux/mac/windows and just check. no need to compile it yourself

**Comment by mkresin** [comment]
> Agreed, but my goal is reproducible encryption, and I'm currently thinking of rewriting my predictable seed patch on top of this [patch](https://sourceforge.net/p/infozip/patches/25/) which utilizes `SOURCE_DATE_EPOCH` env directly. That way we can also skip the extra `touch` command.

That patch should work as well.

I can not remember why I opted for replacing the timestamp with SOURCE_DATE_EPOCH only via extra parameter instead of doing it by default in case the SOURCE_DATE_EPOCH env variable is present.

I don't understand the reason why the patch only replaces mtimes newer than SOURCE_DATE_EPOCH. Wouldn't it cause non reproducible build in worse case?

**Comment by mans0n** [comment]
> I don't understand the reason why the patch only replaces mtimes newer than SOURCE_DATE_EPOCH. Wouldn't it cause non reproducible build in worse case?

AFAIK it's an intended behavior: [ref](https://reproducible-builds.org/docs/archives/)

```
In some cases, it is preferable to keep the original times for files
that have not been created or modified during the build process.
```

We're applying the zip build recipe to (newly generated) device images, so that would not the case here.

**Comment by mans0n** [comment]
* Dropped the touch command.
* Added the SOURCE_DATE_EPOCH patch.
* The srand() seed now depends on SOURCE_DATE_EPOCH.

Still hackish than I expected... But I think this will do the job for us. I don't think info-zip will accept new patches given the situation, so these are likely to remain as downstream patches anyway. 

I've also checked 7-zip implementation and it fetches random bytes directly from /dev/urandom. I'm thinking of asking 7-zip devs for opinions on reproducible encryption.

**Comment by mans0n** [comment]
I'll merge this after a build test by CI.

**Comment by mans0n** [comment]
Merged as e42764cc5f, 39d06472eb, 4f3a565f5d.

**Comment by aparcar** [comment]
Are those patches already sent to upstream?

**Comment by mans0n** [comment]
Nope, as I don't expect a response there.
But I'll try opening a ticket upstream, it would not hurt anyway.

**Comment by aparcar** [comment]
Thanks

**Pull request closed without merging**
