### PR TITLE
toolchain/binutils: switch to version 2.39 by default

### PR DESCRIPTION
**Pull request by hauke**
This was build tested with all core packages successfully.

I am currently testing this.

I started now a build on all targets in github CI. 
https://github.com/hauke/openwrt/actions?query=branch%3Aupdate-binutils-test

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

Please report if you are aware of any problem related to a binutils 2.39 in OpenWrt.

Known problems:
- [x] build problem in layerscape/armv8_64b, tfa-layerscape
- [x] build problem in sunxi/cortexa53, arm-trusted-firmware-sunxi

### CODE REVIEW

**Comment by diizzyy** [comment]
Works fine on ipq40xx, mvebu and mediatek (mt7622) for me (tm) but I haven't tried every single package available

**Comment by hauke** [comment]
I see the following errors which are probably related to the binutils update:
layerscape/armv8_64b:
````
cc1: note: someone does not honour COPTS correctly, passed 0 times
  CC      lib/libc/strnlen.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
  CC      lib/libc/strrchr.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
  AS      lib/libc/aarch64/setjmp.S
  AR      /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_generic_musl/tfa-layerscape-ls1012a-frdm/tfa-layerscape-21.08/build/ls1012afrdm/release/lib/libc.a
  LD      /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_generic_musl/tfa-layerscape-ls1012a-frdm/tfa-layerscape-21.08/build/ls1012afrdm/release/bl31/bl31.elf
cc1: note: someone does not honour COPTS correctly, passed 0 times
aarch64-openwrt-linux-musl-ld.bfd: warning: /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_generic_musl/tfa-layerscape-ls1012a-frdm/tfa-layerscape-21.08/build/ls1012afrdm/release/bl31/bl31.elf has a LOAD segment with RWX permissions
make[4]: *** [Makefile:1101: /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_generic_musl/tfa-layerscape-ls1012a-frdm/tfa-layerscape-21.08/build/ls1012afrdm/release/bl31/bl31.elf] Error 1
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_generic_musl/tfa-layerscape-ls1012a-frdm/tfa-layerscape-21.08'
make[3]: *** [Makefile:185: /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_generic_musl/tfa-layerscape-ls1012a-frdm/tfa-layerscape-21.08/.built] Error 2
time: package/boot/tfa-layerscape/ls1012a-frdm/compile#3.49#0.86#4.56
Error: Process completed with exit code 2.
````

sunxi/cortexa53
````
====== Make errors from logs/package/boot/arm-trusted-firmware-sunxi/sun50i_a64/compile.txt ======
  CC      lib/libc/strlcpy.c
  CC      lib/libc/strlen.c
  CC      lib/libc/strncmp.c
  CC      lib/libc/strnlen.c
  CC      lib/libc/strrchr.c
  AS      lib/libc/aarch64/setjmp.S
  AR      /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/arm-trusted-firmware-sunxi-sun50i_a64/arm-trusted-firmware-sunxi-2020-11-17-e2c509a3/build/sun50i_a64/release/lib/libfdt.a
  AR      /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/arm-trusted-firmware-sunxi-sun50i_a64/arm-trusted-firmware-sunxi-2020-11-17-e2c509a3/build/sun50i_a64/release/lib/libc.a
  LD      /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/arm-trusted-firmware-sunxi-sun50i_a64/arm-trusted-firmware-sunxi-2020-11-17-e2c509a3/build/sun50i_a64/release/bl31/bl31.elf
aarch64-openwrt-linux-musl-ld: warning: /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/arm-trusted-firmware-sunxi-sun50i_a64/arm-trusted-firmware-sunxi-2020-11-17-e2c509a3/build/sun50i_a64/release/bl31/bl31.elf has a LOAD segment with RWX permissions
make[4]: *** [Makefile:1105: /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/arm-trusted-firmware-sunxi-sun50i_a64/arm-trusted-firmware-sunxi-2020-11-17-e2c509a3/build/sun50i_a64/release/bl31/bl31.elf] Error 1
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/arm-trusted-firmware-sunxi-sun50i_a64/arm-trusted-firmware-sunxi-2020-11-17-e2c509a3'
make[3]: *** [Makefile:67: /__w/openwrt/openwrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/arm-trusted-firmware-sunxi-sun50i_a64/arm-trusted-firmware-sunxi-2020-11-17-e2c509a3/.built] Error 2
time: package/boot/arm-trusted-firmware-sunxi/sun50i_a64/compile#4.92#1.47#7.33
Error: Process completed with exit code 2.
````

**Comment by hauke** [comment]
All core packages are compiling.
I created separate pull requests for the trusted firmware arm changes:
https://github.com/openwrt/openwrt/pull/11637
https://github.com/openwrt/openwrt/pull/11639
https://github.com/openwrt/openwrt/pull/11640

**Comment by hauke** [comment]
All problems I know of are fixed now. I plan to merge this in the next few days.

We still have some general problem with building some packages with glibc, but this is related to 5db4fbad4f55acf1a1bcc8b9685e2581789226a5.

**Pull request merged**
