### PR TITLE
kernel: Backport more MGLRU patches

### PR DESCRIPTION
**Pull request by Kaz205**
Fixes a regression in MGLRU, where the reclaim path could occasionally
have long tail latency.

### CODE REVIEW

**Comment by robimarko** [comment]
Both description in PR and more importanly, commit description is missing as to why this is needed

**Comment by Kaz205** [comment]
Done.

**Comment by Ansuel** [comment]
Also 6.1 needs to be handled

**Comment by Kaz205** [comment]
Done.

**Pull request merged**
