### PR TITLE
treewide: use uniform vendor for british telecom

### PR DESCRIPTION
**Pull request by mwarning**
British Telecom is mostly known as BT.

Signed-off-by: Moritz Warning <moritzwarning@web.de>

### CODE REVIEW

**Comment by mans0n** [comment]
I would use "treewide: ..." prefix.
And I see two more BT devices in bcm63xx, are they also from British Telecom?

**Comment by mwarning** [comment]
@mans0n good point, thnak you.

**Comment by aparcar** [comment]
Looks good

**Comment by hauke** [comment]
Thank your for the patch, I applied it to master.

**Pull request closed without merging**
