### PR TITLE
mediatek mt7622

### PR DESCRIPTION
**Pull request by selanf**
ce907a1dd8 mediatek mt7622: use ondemand governor as default
b517a4954c mediatek mt7622: use at least 1.0 volt in dts
8ef1bce38b mediatek mt7622: add 125mhz in dts
4b6c14f116 mediatek mt7622: fix 300mhz typo in dts

### CODE REVIEW

**Comment by selanf** [comment]
ping @dangowrt 
https://github.com/openwrt/openwrt/pull/4440 is related

**Comment by dangowrt** [comment]
I believe the proper solution would be to reset cpufreq and voltage to defined values some where around https://github.com/mtk-openwrt/arm-trusted-firmware/blob/mtksoc/plat/mediatek/mt7622/bl2_plat_setup.c#L268
In that way we wouldn't loose 0.9V modes (which are working fine). As the minimum frequency also isn't clear at this point (30MHz or 300Mhz? Or 125MHz?), I suggest to simply comment-out the currently lowest (30 MHz) operation point, so that the lowest available then becomes 437.5 Mhz @ 1.0V which is known to work well, is actually mentioned in the DTS and not just a guess or observation. We can hope that MediaTek will get back to use at some point about this issue.

Regarding change of default governor:
I believe it'd be better to have that handled in UCI, `/etc/config/system` would be the right place to store cpufreq defaults and have them applied by to-be-implemented `/etc/init.d/cpufreq` at boot.

**Comment by selanf** [comment]
This is all i can do, im not a c developer.

Resetting voltage correctly is up to somone else. If that ever happens, the min-1V patch could be deleted again.
Worst case on to low voltage? It crashes. What happens on to high volt (current limit 1,31v@1,35ghz)? It burns

My device works well since weeks with above changes.

For someone who knows what a cpu governor is, it is easy to change it in the kernel-config or by an echo in rc.local. Im not sure if the other should change the default by web interface.
But running the device by git-default at full speed causes 5°C more what reduced the lifespan for sure, so something should be changed.

So change it as you like.

**Comment by hnyman** [comment]
> As the minimum frequency also isn't clear at this point (30MHz or 300Mhz? Or 125MHz?),

I think that it is 300 MHz, as that is the label assigned to the OPP, while there is one missing zero in the actual value.

I actually noticed that in June and sent mail to the author of that line (and dangowrt), but the author from Mediatek never answered to me. :-(


Culprit commit:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/arch/arm64/boot/dts/mediatek/mt7622.dtsi?id=a5a80f78657f7d7b9b73bc67d0a18d5997c91168


I noticed that by looking at the cpufreq data in a live router running OpenWrt with kernel 5.10. 
The first "30000" looks abnormally small.
 
> root@E8450:~# cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_frequencies
> 30000 437500 600000 812500 1025000 1137500 1262500 1350000

**Comment by selanf** [comment]
I have currently set "scaling_min_freq" to 300mhz, as in this way the transition go lim(1), as visible on screenshot in #16315.
Removing 125mhz completely the devices transits betwen the then 2 lowest frequencies 300+437

**Pull request closed without merging**
