### PR TITLE
libs/popt: Remove rpm5.org as source URL

### PR DESCRIPTION
**Pull request by diizzyy**
rpm5.org is once again dead/down, remove it permanently
Change URL to archive.org snapshot

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by ynezz** [comment]
Well, can't we just remove this package? I don't see anything depending explicitly on `libpopt`

**Comment by diizzyy** [comment]
Uhm...no? Quite a few packages does such as rsync and Samba
https://downloads.openwrt.org/snapshots/packages/mips64_octeonplus/packages/Packages
Grep libpopt0

**Comment by ynezz** [comment]
> Uhm...no? Quite a few packages does such as rsync and Samba
> https://downloads.openwrt.org/snapshots/packages/mips64_octeonplus/packages/Packages
> Grep libpopt0

That's what I'm saying, nothing seems to be using libpopt in the main tree, just in the packages feeds, so popt should be probably removed from the main tree and moved to packages repository.

**Comment by diizzyy** [comment]
In that case we should probably move like half the package tree?

**Comment by ynezz** [comment]
> In that case we should probably move like half the package tree?

That's the plan, yes. Quoting [from the email](http://lists.infradead.org/pipermail/openwrt-devel/2019-June/017658.html):

```
During the meetup in Hamburg we discussed about  having only the required and
actually "basic" packages inside the master  tree and move everything else to
packages feed (after reviewing what's there). I believe this will be also included in
the official summary from the meetup and discussed further afterwards.
```

**Comment by EXSERENS** [comment]
or use this instead?
http://ftp.rpm.org/mirror/popt/

**Comment by diizzyy** [comment]
@EXSERENS 
We already have two mirrors added :-)

**Comment by diizzyy** [comment]
@ynezz 
When is this going to happen, any timeline at all?

**Comment by diizzyy** [comment]
Ping

**Comment by adrianschmutzler** [comment]
@diizzyy Since it is planned to move the package to packages repo, do we still need the patch?

**Comment by diizzyy** [comment]
@adrianschmutzler 
I find it somewhat amusing that you're asking after ~5 months but I guess its better late than never. There's no roadmap or any clear directions of anything except what a one (?) induvidual wants so I'm just as clueless as everyone else outside the "team". ...and rpm5.org is still down/not working so one would expect the package tree to provide working mirrors?

**Comment by diizzyy** [comment]
Still broken, upstream doesn't seem to care so....

**Pull request closed without merging**
