### PR TITLE
[21.02] Backport formalities check for OpenWrt 21.02

### PR DESCRIPTION
**Pull request by BKPepe**
Reference: https://github.com/openwrt/openwrt/pull/11348

Fixes partially: https://github.com/openwrt/openwrt/issues/10980

cc: @Ansuel

### CODE REVIEW

**Comment by Ansuel** [comment]
@BKPepe thanks in the mean time i'm thinking of a correct way to have tools container for branch

**Comment by BKPepe** [comment]
I would say we can merge this as it is, right? The check is working as it should, and it will help the referenced pull request as it will contain fewer commits to review. Also, there will be at least something for OpenWrt 21.02 branch.

**Comment by Ansuel** [comment]
@BKPepe can you rebase this on top of openwrt-21.02 ?

**Comment by BKPepe** [comment]
Done.

**Pull request merged**
