### PR TITLE
[22.03] ramips: add support for ASUS RT-AX53U

### PR DESCRIPTION
**Pull request by robje**
apply commit 8c00fd9b4519bf0ef8fb3470a6df421b9f38c03c to openwrt-22.03

commit 8c00fd9b4519bf0ef8fb3470a6df421b9f38c03c by Chuncheng Chen <ccchen1984@gmail.com>

> Specifications:
> - Device: ASUS RT-AX53U
> - SoC: MT7621AT
> - Flash: 128MB
> - RAM: 256MB
> - Switch: 1 WAN, 3 LAN (10/100/1000 Mbps)
> - WiFi: MT7905 2x2 2.4G + MT7975 2x2 5G
> - Ports: USB 3.0
> - LEDs: 1x POWER (blue, configurable)
>         3x LAN (blue, configurable)
>         1x WAN (blue, configurable)
>         1x USB (blue, not configurable)
> 1x 2.4G (blue, not configurable)
> 1x 5G (blue, not configurable)
> 
> Flash by U-Boot TFTP method:
> - Configure your PC with IP 192.168.1.2
> - Set up TFTP server and put the factory.bin image on your PC
> - Connect serial port(rate:115200) and turn on AP, then interrupt "U-Boot Boot Menu" by hitting any key
>    Select "2. Upgrade firmware"
>    Press enter when show "Run firmware after upgrading? (Y/n):"
>    Select 0 for TFTP method
>    Input U-Boot's IP address: 192.168.1.1
>    Input TFTP server's IP address: 192.168.1.2
>    Input IP netmask: 255.255.255.0
>    Input file name: openwrt-ramips-mt7621-asus_rt-ax53u-squashfs-factory.bin
> - Restart AP aftre see the log "Firmware upgrade completed!"

Maybe MR #10400 should be included as well, dunno

Signed-off-by: Rob J. Epping <epping@renf.us>

### CODE REVIEW

**Comment by castiel652** [comment]
add "[22.03]" to the PR title

**Comment by DragonBluep** [comment]
#10056 Already a PR for 22.03 branch here.

**Comment by robje** [comment]
> add "[22.03]" to the PR title

[x] done

**Comment by robje** [comment]
> #10056 Already a PR for 22.03 branch here.

which seems stalled.

**Pull request closed without merging**
