### PR TITLE
realtek: rework hardware-assisted indirect mdio access v2

### PR DESCRIPTION
**Pull request by plappermaul**
With commit https://github.com/openwrt/openwrt/commit/b53202a8c3f728c348c5376e5b5fb36af7c37744 the phy access logic was
enhanced. A quite big kernel patch was introduced that allowed to make use of
hardware-assisted page access like we have in the realtek target. Basically it
works the following way

- The enhanced bus intercepts page write accesses
- Currently selected pages are stored in internal vars.
- Finally only all-in-one-consistent bus/register accesses are issued
- It intercepted page changes and ensured that only a complete bus call

For the details see https://github.com/openwrt/openwrt/pull/16172

Switching over to newer kernels this patch is really hard to maintain. Its heavy
modifcations exist only in the realtek target. So it does not matter if we keep
it as an kernel modification or directly include it in our driver. To make it the
future brighter we drop this patch and take over its logic. Thus the kernel will
stay totally modification-free. What do we do?

1. Up to now the bus->priv structure directly pointed to ethernet->priv. Create an
explicit private structure rtl838x_bus_priv that not only holds the ethernet->priv
pointer but also space for some bus status tracking vars as well.

2. Wherever we use a reference to ethernet->priv directly replace that by an
additional indirection over the new rtl838x_bus_priv structure.

3. Up to now the phy flag PHY_HAS_REALTEK_PAGES identified that we can use the
alternative paged access from the patch. As this will be no longer available
remove it and provide read_page/write_page functions for each possible PHY.
These functions will be pretty standard as for other Realtek PHYs.

4. The existing mdio bus read/write function rely on the classic MII_ADDR_C45
flag - one interface for two access types. This mixup will be removed on the way
to kernel 6.6. In the future there will be two pairs of access functions. One for
classic access one for c45 style access. Rewrite our functions into 3 parts:

- a classic read/write function: ready for kernel 6.6
- a new c45 read/write function: ready for kernel 6.6
- a legacy read/write wrapper: for current 5.15 for the time being

When we switch to 6.6 we only need to remove the legacy wrappers and link the
new functions. Life can be so easy.

5. The classic read/write functions will incorporate the interception logic that
was originally in the patch.

6. The package convenience functions that were embedded in the patch get lost as
well. Rewrite them inside our phy driver.

Signed-off-by: Markus Stockhausen <markus.stockhausen@gmx.de>

### CODE REVIEW

**Review by dangowrt — COMMENTED** [review]
Thank you for taking your time to work on this.
The general direction should be to get rid of the rtl838x-specific PHY drivers in favor of merging the missing PHYs into the existing upstream `realtek.c` PHY driver -- many of the ICs covered in the rtl838x-specific driver are already also covered in `realtek.c`.

I agree with page_read being a private property of the bus, trying to add it to generic PHY infrastructure in Linux probably wasn't a good idea. However, it be even better if the `bus_write_page`, `bus_read_page`, `bus_write`, `bus_read` as well as related macros could hence go into the MDIO bus driver instead of being moved to the PHY driver (which we should try to rid from platform-specific code not related to the PHY itself, so it would be reusable and share as much code as possible). Accelerated page access is *not* a property of the PHY, as you correctly stated it is a property of the bus. The same PHY would require using MII register 0x1f for setting the page on non-RealTek host platforms, **and that's exactly what the RealTek SoC's page access abstraction also does**. Sadly it is not only about acceleration of paged access, but also about it not interfering with (hardware-driven) PHY polling which conflicts with non-abstracted paged access (ie. speed has never been the justification for this).

**Comment by bmork** [comment]
Tkanks for this.  Works for me on Netgear GS108Tv3

**Comment by mikevd97** [comment]
Thanks. Works on D-Link DGS-1210-20.

**Comment by plappermaul** [comment]
@dangowrt with only 5 days into mdio & phy stuff I feel stupid. But to summerize what I have understood:

try to reduce the phy code in best case down to:

```
static int rtl821x_read_page(struct phy_device *phydev)
{
	return __phy_read(phydev, RTL8XXX_PAGE_SELECT);
}

static int rtl821x_write_page(struct phy_device *phydev, int page)
{
	return __phy_write(phydev, RTL8XXX_PAGE_SELECT, page);
}
```

and try to do some magic inside the bus?

**Comment by dangowrt** [comment]
The problem is that it won't work in this way because the MDIO controller (which does automated polling of link status of all PHYs **in hardware**) *expects* you to use the paged access abstractions. You *must* use them on this hardware, otherwise the internal logic of the MDIO controller doesn't know what page you are currently on and will poll random registers in case you are not on the default page.

**Comment by plappermaul** [comment]
Stil top stupid. I understand that we somehow Need to store the page for our two step register Access. And having a separate page per PHY - seems ok but I do not 100% understand.

can you give an example of the interference?

**Comment by dangowrt** [comment]
On all RealTek switch platforms the hardware periodically reads the link status of each PHYs. This is to some degree programmable, so that you can tell the hardware to read specific C22 registers from specific pages, or C45 registers, to determine the current link speed, duplex, flow-control, ...
This happens without any need for the driver to do *anything* at runtime, completely invisible and in a parallel *hardware* thread, independent of the CPU running Linux. All you need to do is to set it up once. Having the MAC link settings automatically follow the PHY link status also happens to be the only way to control MAC port status in a meaningful way, or at least it's the only way we fully understand, as this is what every vendor firmware is doing.

The hardware PHY polling unit doesn't care about bus locking, it just assumes that all paged PHY operations are also done via the same hardware unit offering this (and other not very helpful, more on that later) PHY access abstractions.

Assume the following code flow when doing what you suggested above:
```
Linux PHY driver                 |     Hardware PHY polling
---------------------------------+---------------------------------
Write x to register 0x1f         |
                                 | Read status register 0
                                 | (assuming currently on page 0) !!
Read register y                  |
Write n to register y            |
Write 0 to register 0x1f         |
                                ...
                                 | Read status register 0
                                 | (assuming currently on page 0)
```

As you can see the first reading of register 0 by the hardware PHY polling unit would be on page *x* rather than on page 0 because the hardware is unaware of *non-atomic nature* of paged access when done manually.

The same operation looks a bit different when using the paged access hardware abstraction:
```
Linux PHY driver                 |     Hardware PHY polling
---------------------------------+---------------------------------
Read register y on page x        |
                                 | Read status register 0 on page 0 
                                 | (assuming currently on page x)
Write n to register y            |
Write n to register y on page x  |
                                ...
                                 | Read status register 0 on page 0
                                 | (assuming currently on page x)
```

In other words: The MDIO controller has quite a bit of hidden internal state and does things in background.

We are not actually dealing with classic simple MDIO bus controllers here, but rather with an abstract mapping of bus + PHY address to switch ports and lots of programmable logic to allow polling 48 PHYs on up to 4 different busses in hardware without the CPU doing anything for that. This allows to create cheap designs without designated PHY interrupt lines (as we all know pincount heavily influences silicon production cost, and that's 48 pins less needed on a 48-port switch).

MDIO has 5-bit addresses from 0 to 31, the RealTek Ethernet hardware has *hardware registers* to define which of the MAC ports are connected to which PHYs (bus 0...3, addr 0...31), and it got registers to define which PHY registers and bits should be polled *by the hardware* for various link properties. PHY indirect access happens via the MAC port, which results in absurd things like "PHY address 62" which in reality is that *MAC port number* and obviously **not** the PHY address on an actual MDIO bus.

Now, of course, we could try to disable hardware PHY polling while accessing the PHY in software and make sure to always return it to page 0 before enabling hardware PHY polling again. But do we really want that?

More importantly, we should try to define the actual MDIO busses in DT, and from the phy-handles of the MAC ports define the MAC port <-> MDIO bus + PHY address mapping and program the relevant registers accordingly instead of relying on the bootloader to do that and then keep using the already setup abstractions with bogus PHY addresses which are port addresses in reality.

**Comment by plappermaul** [comment]
So much info for my little brain. To achieve the MDIO magic I understood we need to

- intercept all page 1f calls
- handle raw bus writes (page fff on RTL838x and page 1fff on RTL839x)

My proposal:

static int rtl838x_mdio_read(struct mii_bus *bus, int addr, int regnum)
{
	int err, val;
	struct rtl838x_bus_priv *bus_priv = bus->priv;
	struct rtl838x_eth_priv *eth_priv = bus_priv->eth_priv;

	if (addr >= 24 && addr <= 27 && eth_priv->id == 0x8380)
		return rtl838x_read_sds_phy(addr, regnum);
	
	if (regnum == RTL8XXX_PAGE_SELECT && bus_priv->page != RTL838X_PAGE_RAW) {
		printk("  rtl838x_mdio_read: return internal page %d\n", bus_priv->page);
		return bus_priv->page;	
	}

	err = rtl838x_read_phy(addr, bus_priv->page, regnum, &val);
	printk("  rtl838x_mdio_write: issued bus read addr=%d, page=%d, reg=%d, val=%d, err=%d\n", addr, bus_priv->page, regnum, val, err);
	bus_priv->raw = (bus_priv->page == RTL838X_PAGE_RAW);
	return err ? err : val;
}

static int rtl838x_mdio_write(struct mii_bus *bus, int addr, int regnum, u16 val)
{
	struct rtl838x_bus_priv *bus_priv = bus->priv;
	struct rtl838x_eth_priv *eth_priv = bus_priv->eth_priv;
	int err = 0, page = bus_priv->page, offset = 0;
	
	if (addr >= 24 && addr <= 27 && eth_priv->id == 0x8380) {
		if (addr == 26)
			offset = 0x100;
		sw_w32(val, RTL838X_SDS4_FIB_REG0 + offset + (regnum << 2));
		return 0;
	}
	
	if (regnum == RTL8XXX_PAGE_SELECT) {
		printk("  rtl838x_mdio_write: set internal page %d\n", val);
		bus_priv->page = val;
	}	

	if (!bus_priv->raw && (regnum != RTL8XXX_PAGE_SELECT || page == RTL838X_PAGE_RAW)) {
		err = rtl838x_write_phy(addr, page, regnum, val);
		printk("  rtl838x_mdio_write: issued bus write addr=%d, page=%d, reg=%d, val=%d, err=%d\n", addr, page, regnum, val, err);
		bus_priv->raw = (page == RTL838X_PAGE_RAW);
	} else {
		bus_priv->raw = false;
	}

	return err;
}

A simple test program for that is

```
printk("**TEST 1*********************\n");
printk("phy_write(phydev, RTL8XXX_PAGE_SELECT, 12)\n");
val = phy_write(phydev, RTL8XXX_PAGE_SELECT, 12);
printk("phy_write()=%d\n", val);
printk("phy_read(phydev, RTL8XXX_PAGE_SELECT)\n");
val = phy_read(phydev, RTL8XXX_PAGE_SELECT);
printk("phy_read()=%d\n", val);

printk("**TEST 2*********************\n");
printk("phy_write(phydev, 7, 33)\n");
val = phy_write(phydev, 7, 33);
printk("phy_write()%d\n", val);
printk("phy_read(phydev, 7)\n");
val = phy_read(phydev, 7);
printk("result is %d\n", val);

printk("**TEST 3*********************\n");
printk("phy_write_paged(phydev, RTL83XX_PAGE_RAW, RTL8XXX_PAGE_SELECT, 13)\n");
val = phy_write_paged(phydev, RTL83XX_PAGE_RAW, RTL8XXX_PAGE_SELECT, 13);
printk("phy_write_paged()=%d\n", val);
printk("phy_read_paged(phydev, RTL83XX_PAGE_RAW, RTL8XXX_PAGE_SELECT)\n");
val = phy_read_paged(phydev, RTL83XX_PAGE_RAW, RTL8XXX_PAGE_SELECT);
printk("phy_read_paged()=%d\n", val);
	
printk("**TEST 4*********************\n");
printk("phy_write_paged(phydev, RTL83XX_PAGE_RAW, 7, 44)\n");
val = phy_write_paged(phydev, RTL83XX_PAGE_RAW, 7, 44);
printk("phy_write_paged()=%d\n", val);
printk("phy_read_paged(phydev, RTL83XX_PAGE_RAW, 7)\n");
val = phy_read_paged(phydev, RTL83XX_PAGE_RAW, 7);
printk("phy_read_paged()=%d\n", val);
```

and output is

```
[    1.625963] **TEST 1*********************
[    1.630464] phy_write(phydev, RTL8XXX_PAGE_SELECT, 12)
[    1.636288]   rtl838x_mdio_write: set internal page 12
[    1.642056] phy_write()=0
[    1.644984] phy_read(phydev, RTL8XXX_PAGE_SELECT)
[    1.650325]   rtl838x_mdio_read: return internal page 12
[    1.656370] phy_read()=12
[    1.659328] **TEST 2*********************
[    1.663806] phy_write(phydev, 7, 33)
[    1.678020]   rtl838x_mdio_write: issued bus write addr=8, page=12, reg=7, val=33, err=0
[    1.687180] phy_write()0
[    1.690040] phy_read(phydev, 7)
[    1.693641]   rtl838x_mdio_write: issued bus read addr=8, page=12, reg=7, val=2081, err=0
[    1.702897] result is 2081
[    1.706034] **TEST 3*********************
[    1.710535] phy_write_paged(phydev, RTL83XX_PAGE_RAW, RTL8XXX_PAGE_SELECT, 13)
[    1.718683]   rtl838x_mdio_read: return internal page 12
[    1.724645]   rtl838x_mdio_write: set internal page 4095
[    1.730661]   rtl838x_mdio_write: set internal page 13
[    1.746618]   rtl838x_mdio_write: issued bus write addr=8, page=4095, reg=31, val=13, err=0
[    1.756076]   rtl838x_mdio_write: set internal page 12 (REMARK!)
[    1.761841] phy_write_paged()=0
[    1.765435] phy_read_paged(phydev, RTL83XX_PAGE_RAW, RTL8XXX_PAGE_SELECT)
[    1.773045]   rtl838x_mdio_read: return internal page 12
[    1.779078]   rtl838x_mdio_write: set internal page 4095
[    1.785147]   rtl838x_mdio_write: issued bus read addr=8, page=4095, reg=31, val=13, err=0
[    1.794498]   rtl838x_mdio_write: set internal page 12
[    1.800382] phy_read_paged()=13
[    1.803929] **TEST 4*********************
[    1.808495] phy_write_paged(phydev, RTL83XX_PAGE_RAW, 7, 44)
[    1.814844]   rtl838x_mdio_read: return internal page 12
[    1.820863]   rtl838x_mdio_write: set internal page 4095
[    1.837066]   rtl838x_mdio_write: issued bus write addr=8, page=4095, reg=7, val=44, err=0
[    1.846430]   rtl838x_mdio_write: set internal page 12
[    1.852200] phy_write_paged()=0
[    1.855794] phy_read_paged(phydev, RTL83XX_PAGE_RAW, 7)
[    1.861660]   rtl838x_mdio_read: return internal page 12
[    1.867676]   rtl838x_mdio_write: set internal page 4095
[    1.873735]   rtl838x_mdio_write: issued bus read addr=8, page=4095, reg=7, val=2092, err=0
[    1.883183]   rtl838x_mdio_write: set internal page 12
[    1.889051] phy_read_paged()=2092
```

This seems ok for me with one (maybe neglectable) detail. Changing SELECT_PAGE in RAW mode will keep the MDIO internal set page (see REMARK)

Happy with that?

**Comment by dangowrt** [comment]
I like the concept, and I see that this would work perfectly, keeps all properties of the MDIO controller inside the controller driver (== Ethernet driver on that platform) and thereby allow sharing PHY drivers with non-RealTek platforms. It is also non-intrusive and doesn't require any upstream kernel changes.

The next step would be to describe the actual hardware in DT, ie. have 4 `mdio` nodes under the Ethernet controller instead of dealing with bogus 6-bit "PHY addresses" (which are post addresses with hardware-mapped PHYs in reality).

**Comment by plappermaul** [comment]
Thanks for the positive review. I already posted the new v2 version for testing.

One open point that I did not cover yet: Do I have to take care about bus logic for the mmd (C45) accesses? Until now all I did was:

- Create the ..._c45() functions
- Remove the bus_capabilities=C22 assignment stuff and ignoring any possible side effects

**Comment by plappermaul** [comment]
@musashino205 found a bug this will need a v3

**Comment by plappermaul** [comment]
included into https://github.com/openwrt/openwrt/pull/16204

**Pull request closed without merging**
