### PR TITLE
dropbear: refresh package

### PR DESCRIPTION
**Pull request by rockdrilla**
- enable back DROPBEAR_USE_PASSWORD_ENV
- sequential rework of configuration recipe:
  * reorder options in Configure recipe
  * rework recipes that configure build
  * roll up recipes into mapping lists
- add ssh-askpass support in configuration
- bump package version

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by rockdrilla** [comment]
I've updated commits with bin/ipk size changes (forgot to do this before sending pull request).

**Comment by rockdrilla** [comment]
@dedeckeh friendly ping :blush:

**Review by rockdrilla — COMMENTED** [review]
Seems legit, builds and runs fine.

**Comment by Borromini** [comment]
Has been working fine here for a few weeks.

**Comment by ynezz** [comment]
> Has been working fine here for a few weeks.

@Borromini is that your `Tested-by`? :)

**Comment by Borromini** [comment]
Yes it is! Sorry :-)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Op donderdag 10 december 2020 om 12:37 schreef Petr Štetiar <notifications@github.com>:

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
