### PR TITLE
libevent: update to release 2.1.8

### PR DESCRIPTION
**Pull request by yogo1212**

### CODE REVIEW

**Comment by diizzyy** [comment]
This release is broken in several ways and was determined in the past not to be imported.
https://github.com/lede-project/source/pull/1080
https://github.com/lede-project/source/pull/848

**Comment by yogo1212** [comment]
sorry. i hadn't occured to look at closed PRs.
how about updating to the libevent-patch that fixes the dependency issue?
i suppose you prefer using the release with the patch sitting on top

**Comment by diizzyy** [comment]
For now, I think we'll wait for a new release of the 2.1-branch or jump on 2.2
https://github.com/libevent/libevent/commit/efcfa046aeab0ce9e783d648d10db3b69dcf7066

**Comment by yogo1212** [comment]
well, the last update was three years ago. waiting another year probably won't make much of a difference :-D
there are some nifty new features, though..
so just in case, here's a version with the patch.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
