### PR TITLE
mediatek: cleanup and fix for mt7623

### PR DESCRIPTION
**Pull request by mans0n**
- mediatek: tidy up image subtarget Makefiles
- mediatek: mt7623: enforce image metadata check
- mediatek: remove unnecessary uci-defaults script
- mediatek: mt7623: refresh kernel 5.4 config
- mediatek: re-add u3phy2 phy-switch patch

### CODE REVIEW

**Comment by mans0n** [comment]
All patches (except patch 1) are run-tested on an unofficial NAND-based MT7623A device.

For patch 2, UniElec U7623-02 does not use uImage, so the current image check logic seems to be wrong anyway.

I didn't touch 4.19 here, I'll add 4.19 patch if it's prefered.

Could you please have a look? @blogic

**Comment by adrianschmutzler** [comment]
I will merge patch 1 today.

@blogic The rest might be interesting for you.

**Comment by adrianschmutzler** [comment]
@mans0n 

Just rerun make kernel_oldconfig and it wants the following:
```
--- a/target/linux/mediatek/mt7623/config-5.4
+++ b/target/linux/mediatek/mt7623/config-5.4
@@ -216,6 +216,7 @@ CONFIG_GENERIC_STRNCPY_FROM_USER=y
 CONFIG_GENERIC_STRNLEN_USER=y
 CONFIG_GPIOLIB=y
 CONFIG_GPIO_SYSFS=y
+CONFIG_GRO_CELLS=y
 CONFIG_HANDLE_DOMAIN_IRQ=y
 CONFIG_HARDEN_BRANCH_PREDICTOR=y
 CONFIG_HARDIRQS_SW_RESEND=y
@@ -409,7 +410,6 @@ CONFIG_PINCTRL_MT6397=y
 CONFIG_PINCTRL_MT7623=y
 CONFIG_PINCTRL_MTK=y
 CONFIG_PINCTRL_MTK_MOORE=y
-CONFIG_PLUGIN_HOSTCC="g++"
 CONFIG_PM=y
 CONFIG_PM_CLK=y
 CONFIG_PM_GENERIC_DOMAINS=y
```

I wouldn't care about the CONFIG_GRO_CELLS and just include it, but I wonder why you add the CONFIG_PLUGIN_HOSTCC which is removed for me again.

**Comment by mans0n** [comment]
> I wonder why you add the CONFIG_PLUGIN_HOSTCC which is removed for me again.

I don't understand either. I even do not know what CONFIG_PLUGIN_HOSTCC actually does.
Perhaps `make kernel_oldconfig` results different configs on different setups. (For example #3101 added `# CONFIG_SND_SOC_MT6797 is not set` but it did not occured to me.)

**Comment by adrianschmutzler** [comment]
@mans0n 

Okay, then I would merge your refresh patch, but remove CONFIG_PLUGIN_HOSTCC from it (and also won't add CONFIG_GRO_CELLS). Okay?

**Comment by mans0n** [comment]
Rebased due to f72a2b004c35 and 636b62e8e232.
And removed CONFIG_PLUGIN_HOSTCC manually.

**Comment by adrianschmutzler** [comment]
Thanks, pushed.

**Comment by dwmw2** [comment]
The image metadata check in 359b91d3b9e conflicts with the BPi R2 support in #3101 where I've made `platform_check_image()` check for the partition layout changing.

**Comment by mans0n** [comment]
Yeah, one should be changed accordingly after the other get merged first.

**Comment by EXSERENS** [comment]
@diizzyy How you think about ```HZ100``` in this pull request?

**Comment by adrianschmutzler** [comment]
> How you think about HZ100 in this pull request?

@EXSERENS That patch has been merged already. Since no HZ settings are done in generic config anymore, those symbols get added per target if you refresh config ...

**Comment by dwmw2** [comment]
The "re-add u3phy2 phy-switch patch" patch makes my Unielec U7623 board boot again, fixing https://bugs.openwrt.org/index.php?do=details&task_id=3217

It still doesn't have Ethernet connectivity; just an eth0 which receives no packets.

**Comment by mans0n** [comment]
Rebased due to af9932c9b7b9.
platform_check_image() is not trivial anymore so I dropped the metadata patch for now.

**Comment by ynezz** [comment]
@dwmw2 Thanks for testing, so I can add your tested-by ?

**Comment by dwmw2** [comment]
> @dwmw2 Thanks for testing, so I can add your tested-by ?

Sure, thanks.

I had also resolved the metadata check but haven't tested sysupgrade since doing so; we can do that later.

@mans0n do you have the SP flash tool working to do USB recovery on MT7623? I'm hoping I can fix the installation process for U7623 that way... if I can get it working.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by mans0n** [comment]
@dwmw2 
Actually I haven't tried it as I failed to enable the micro USB port on the board. If you manage to get it working, please let me know. That would be quite interesting.

As for the ethernet, I guess it can also be fixed by adjusting the dts (expecially the position of mt7530 node), but I'm not sure about its exact form. Perhaps [this](https://github.com/mans0n/openwrt/commit/b99605b0bc18bbea670265c5f9deefa6314b2f82#diff-31f9dc26461d3406ab27c3a4408e6fdcR170) might give you a clue.

**Comment by dwmw2** [comment]
I got the flash tool working, and I have a functional U-Boot for the U7632. Working on establishing why the kernel doesn't boot when I change from uImage to FIT.

Yeah, making the eth setup look a lot more like the BPI-R2 will probably fix that. I have similar problems in U-Boot too with the Ethernet.

At some point I need to work out how to cope with sysupgrade from 19.07 to newer images that "own" the whole device and not just the space after block 0xA00.

**Comment by dwmw2** [comment]
Also, U-Boot knows the real RAM size from the preloaded so doesn't need *different* DT for the different memory sizes. It really ought to be able to pass the appropriate DT memory node to the kernel too, and then I won't need a new board type for my 1GiB board.

Really, if we own the bootloader then it ought to give the correct DT to the kernel and we should never need to use the awful hack of building DT into the kernel image anyway. All the mt7623 boards can use precisely the same kernel.

**Pull request closed without merging**
