### PR TITLE
kernel: bump 5.10 to 5.10.165

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: ramips/tplink_archer-a6-v3
Run-tested: ramips/tplink_archer-a6-v3

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by graysky2** [comment]
@Ansuel - any thoughts why this is failing?

**Comment by hauke** [comment]
It looks like some patches need a refresh. The build fails like this:
````
Kernel patches for oxnas/ox820 require refresh. (run 'make target/linux/refresh' and force push this pr)
````

**Comment by graysky2** [comment]
@hauke - I see those lines but the source was successfully refreshed by `update_kernel.sh`

**Comment by hauke** [comment]
It is complaining about kernel linux-5.15.88.tar.xz.
Please rebase to trigger a new run on a more recent master.

**Pull request merged**
