### PR TITLE
Fix ip-tiny libcap compile fail

### PR DESCRIPTION
**Pull request by stgnet**
Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by lucize** [comment]
mabe ip-tiny not to be built with libcap support ? libcap I think is not in the base repo and a package from base should not depend from other repo

**Comment by adrianschmutzler** [comment]
@stgnet Hi, your PR has formal issues (commit message, missing Signed-off, otc.)

Have a look at https://openwrt.org/submitting-patches

**Comment by hauke** [comment]
ip-tiny should not depend on libcap, can we somehow get rid of this dependency for ip-tiny and only add it for ip-full

**Comment by ynezz** [comment]
>  Fix ip-tiny libcap compile fail 

Would be nice to know where/how it fails.

**Comment by adrianschmutzler** [comment]
@stgnet Please address/respond on the comments, or we will close the PR.

**Comment by stgnet** [comment]
My apologies - this was meant to track a temporary workaround for an
internal project and not meant to be a public pr to the origin project.

------------------------------
     Scott Griepentrog   +1-256-580-6090 http://theB.life

**Comment by adrianschmutzler** [comment]
@stgnet So, it can be closed?

**Comment by stgnet** [comment]
Yes, since it was not my intention to create an issue on the main project,
only on my own fork.


------------------------------
     Scott Griepentrog   +1-256-580-6090 http://theB.life

**Pull request closed without merging**
