### PR TITLE
wireguard-tools: bump to 20210914

### PR DESCRIPTION
**Pull request by graysky2**
https://github.com/WireGuard/wireguard-tools/compare/v1.0.20210424...v1.0.20210914

Build system: x86_64
Build-tested: bcm2711/RPi4B
Run-tested: bcm2711/RPi4B

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by adschm** [comment]
Commit message is missing. For bumps typically: What/where are the changes?

**Comment by adschm** [comment]
> WireGuard/wireguard-tools@v1.0.20210424...v1.0.20210914

And there is absolutely no chance you could convert that into a "git log --oneline" that can actually be read (even without GitHub or a browser) ...? ;-)

**Comment by aparcar** [comment]
Looking at the changes, what actually affects OpenWrt?

**Comment by graysky2** [comment]
@aparcar - This is a fair point, changes are unrelated to Linux.  Only advantage of bumping is to retain sync with upstream versioning.

**Comment by aparcar** [comment]
Let's safe some users some precious flash cycles and skip this until a change relevant for linux appears?

**Comment by graysky2** [comment]
Your call.

**Comment by aparcar** [comment]
I guess if we want to [feel fancy](https://repology.org/project/wireguard-tools/versions) we should do it, if not we should close this. @adschm thoughts?

**Comment by kofec** [comment]
I was not able to compile wireguard on 19.07 and update version to 
`Generating index for package ./kmod-wireguard_4.14.245+1.0.20210424-1_mips_24kc.ipk`
Maybe branch 19,07 can also be updated ?
I think that needed fix is:
compat: icmp_ndo_send functions were backported extensively
and also patch is no longer needed as:
compat: skb_mark_not_on_list was backported to 4.14

**Comment by Borromini** [comment]
> I was not able to compile wireguard on 19.07 so update version to `Generating index for package ./kmod-wireguard_4.14.245+1.0.20210424-1_mips_24kc.ipk` Maybe branch 19,07 can also be updated ? I think that needed fix is: compat: icmp_ndo_send functions were backported extensively and also patch is no longer needed as: compat: skb_mark_not_on_list was backported to 4.14

That's unrelated to this PR.

@aparcar @graysky2 I had the same feeling looking at the changelog: no changes that would affect WireGuard on Linux/OpenWrt. Makes more sense to me to bump when there's actual improvements for Linux involved.

**Comment by aparcar** [comment]
Agree

**Comment by PolynomialDivision** [comment]
Can we bump wireguard-tools? I accidentally made now a second commit bumping the version. For me it looks better that we ship the recent versions and don't ship outdated software. We also bump each kernel release and so on to stay in sync with everything. I don't see that we will break the flash of someone except people are using `opkg` to upgrade wireguard-tools. However, that is not common?

**Pull request closed without merging**
