### PR TITLE
WIP mac80211: fix use of local variable

### PR DESCRIPTION
**Pull request by yogo1212**
this looks a lot like a bug to me.
not entirely sure it is.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
This was introduced in 2014: https://github.com/openwrt/openwrt/commit/4d99db168cf7b7068aae540b405f90065e305302

From what it looks to me, it should be either 
`head -n $idx /sys/class/ieee80211/${phy}/addresses | tail -n1`

or one could keep the macidx and remove the second parameter and idx assignment from the function.

The first should be sligthly preferable, as mac80211_generate_mac will assign a fallback value to the id then.

That's just from quickly looking at the code, we should wait for an expert in any case.

Note that your commit has formal issues: There is no commit message and you lack Signed-off-by.

**Comment by yogo1212** [comment]
hello adrian :-)

i'm usually hesitant to add a signed-off before knowing that it's good but i'm running into trouble with maintainers all over the place - maybe i should just change my strategy.

the second parameter is `id="${macidx:-0}"` which suggests macidx might be undefined; so i agree that just using idx is the better option.

**Comment by adrianschmutzler** [comment]
> i'm usually hesitant to add a signed-off before knowing that it's good but i'm running into trouble with maintainers all over the place - maybe i should just change my strategy.

If it's not marked specifically, it should be ready for submission.
Otherwise, you should use something like work-in-progress (WIP), ready-for-comment (RFC) or similar to prefix your PR (not commit) title, indicating that it's not finished. Despite, there is the draft mode in GitHub.

However, most probably I would still comment about missing Signed-off then, but at least you would more clearly indicate the state of what you present here.

Despite, I'd still add a description to the commit message. In your case, it would state that the function uses macidx from global context, althought idx is set up in local context and unused.
One could also mention the additional aid of id="${macidx:-0}" ...

**Comment by yogo1212** [comment]
ok. i hope this addresses your comments.
i didn't know about draft mode

**Comment by yogo1212** [comment]
@nbd168 could you have a quick look over this?

**Comment by adrianschmutzler** [comment]
@yogo1212 You should add a
`Fixes: 4d99db168cf7 ("mac80211: try to get interface addresses from wiphy sysfs 'addresses' if no mask is set")`
to the commit message (before Signed-off)

@dangowrt Can you have a quick look, I think this is a valid fix.

**Comment by yogo1212** [comment]
@adrianschmutzler done :-)

**Comment by adrianschmutzler** [comment]
It looks valid and correct to me, so I will merge it.

**Pull request closed without merging**
