### PR TITLE
kernel: split kernel version to dedicated files

### PR DESCRIPTION
**Pull request by Ansuel**
Move the kernel versions and hash to dedicated files.
This makes kernel bump quicker and fix some annoying
problem with rebasing when multiple kernel bump are proposed.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

@nbd168 @aparcar What do you think? I'm also reworking the old script to change these files directly.

### CODE REVIEW

**Comment by Ansuel** [comment]
I also added the additional script. This should make kernel bump less annoying

**Comment by aparcar** [comment]
First commit seems fine to me. @rsalvaterra @graysky2 since both of you do plenty of kernel bumps, could you please test and review this?

**Comment by rsalvaterra** [comment]
I'm not entirely convinced. On one hand, having the kernel versions/hashes in separate files makes concurrent bumps easier, since there won't be conflicts to resolve manually. On the other hand, why would one want to simply bump the kernel version without rebasing the whole patch set? Feels like a recipe for disaster to me. @graysky2?

**Comment by Ansuel** [comment]
@rsalvaterra mhh don't know many time minor kernel bump require only a change of the version/hash and a target/linux/refresh.
If your concern is that user would simply update the version/hash with the script without refreshing/compile/testing the new version than we can simply ignore the kernel bump or ask for testing.
I understand that this would make things simple but IMHO it seems wrong from the start that we had to modify an include file to bump the kernel version.
But yhea this branch started with a big security risk so I understand if this is very wrong ahahhah (again it all started by me getting annoyed by 5.15 that needs to be rebased on every kernel bump, it has to be done when we will have to merge it but it's problematic if users wants to test it now)

**Comment by rsalvaterra** [comment]
> @rsalvaterra mhh don't know many time minor kernel bump require only a change of the version/hash and a target/linux/refresh.

In my experience, I estimate about 5 % of the time. 😉 (I should probably start keeping a statistic.)

> If your concern is that user would simply update the version/hash with the script without refreshing/compile/testing the new version than we can simply ignore the kernel bump or ask for testing. I understand that this would make things simple but IMHO it seems wrong from the start that we had to modify an include file to bump the kernel version.

Most likely the build would break, and quite spectacularly. Refreshing/reabasing patches is pretty much mandatory. We write them, put them in pending-\*, send them upstream, move them to backports-\* when accepted, delete them on kernel bumps when they're backported to stable. It's a delicate dance.

> But yhea this branch started with a big security risk so I understand if this is very wrong ahahhah (again it all started by me getting annoyed by 5.15 that needs to be rebased on every kernel bump, it has to be done when we will have to merge it but it's problematic if users wants to test it now)

Yeah, I'd avoid providing each and every (power-)user with loaded footguns. They're called "maintainer tools" and kept in a separate repository for a reason. 😉.

**Comment by rsalvaterra** [comment]
@Ansuel, if the issue is having to rebase your pull request when 5.15 is updated (quite understandable), I'd suggest not doing it all the time. 5.15 is a new kernel, we could merge a certain release and do the updates afterwards. Would that be feasible?

**Comment by graysky2** [comment]
I see both sides of this.  I don't have a strong opinion either way.  I agree with @rsalvaterra re: 5.15 rebasing frequency for what my opinion is worth :smile:

**Comment by Ansuel** [comment]
> Yeah, I'd avoid providing each and every (power-)user with loaded footguns. They're called "maintainer tools" and kept in a separate repository for a reason. 😉.

Mhh I still think the first commit is a positive change. It's cleaner to have kernel version separate from include files.
We can consider dropping the second commit also if we notice a kernel bump that only change the kernel file we would instantly notice that something is wrong and that the patch is invalid.

Don't know, I really hate the idea that kernel-version.mk have multiple revision that are actually just kernel bump and not related to the version parsing logic. I assume it was correct back in the old days when openwrt supported 3.18 kernel version and kernel bumps were not that common as we had multiple patches and hack by broadcom/other stuff but now? It looks like we are starting to have a bump every week and be on par of kernel.org (probably related to the fact that we are finally reducing the number of patch that needs to be refreshed)

**Comment by rsalvaterra** [comment]
@luaraneda, agreed. @Ansuel, mind just splitting the kernel versions into separate makefiles and update the `update_kernel.sh` script accordingly? I'm just not sure how the merge will be done, since it has to occur in sync and we're talking about separate repositories.

**Comment by Ansuel** [comment]
Wait I think I didn't understand. Isn't the first commit what you are
suggesting? (Splitting the kernel to separate makefiles?)

I'm also confused about the second part.

Il Gio 13 Gen 2022, 14:15 Rui Salvaterra ***@***.***> ha
scritto:

**Comment by luaraneda** [comment]
I think he is saying to apply the first commit to this repository (OpenWrt), and the second to the "maintainer tools" repository that is used to automate/help on kernel bumps.

**Comment by Ansuel** [comment]
Oh ok. Yes I also agree on that. So I have to remove the second commit and
propose the script to the other repo. Can someone link me that?

Il Gio 13 Gen 2022, 19:57 Rui Salvaterra ***@***.***> ha
scritto:

**Comment by aparcar** [comment]
@rsalvaterra if you tested it, please merge the first commit.

@Ansuel https://git.openwrt.org/?p=maintainer-tools.git;a=summary

**Comment by rsalvaterra** [comment]
> @rsalvaterra if you tested it, please merge the first commit.

 I haven't yet, but will do.

**Comment by Ansuel** [comment]
The only concer I have is if we should handle when patchver is not defined
but that should be mandatory for a correct target definition.

Il Gio 13 Gen 2022, 21:28 Rui Salvaterra ***@***.***> ha
scritto:

**Comment by rsalvaterra** [comment]
> The only concer I have is if we should handle when patchver is not defined but that should be mandatory for a correct target definition.

I don't think that would be a problem. Like you said, a target that doesn't define `KERNEL_PATCHVER` has more immediate issues to solve.

**Comment by rsalvaterra** [comment]
@Ansuel, I merged your first commit, but I had to rebase it on top of current master (@graysky2, you'll need to update your 5.4 bump pull accordingly). As for fixing `update_kernel.sh` in maintainer tools, it's probably better to send the patch to the mailing list.

**Comment by graysky2** [comment]
@Ansuel - You might wan to take some suggestions from [shellcheck](https://www.shellcheck.net/) on your 2nd commit.  Most involve quoting.

```
Line 98:
$CMD make target/linux/download KERNEL_PATCHVER=${KERNEL} LINUX_VERSION=${PATCHVER} LINUX_KERNEL_HASH=skip || exit 1
                                                ^-- SC2086 (info): Double quote to prevent globbing and word splitting.
>>                                                                      ^-- SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
$CMD make target/linux/download KERNEL_PATCHVER="${KERNEL}" LINUX_VERSION="${PATCHVER}" LINUX_KERNEL_HASH=skip || exit 1
 
Line 101:
        NEWVER=${PATCHVER#$KERNEL}
                          ^-- SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: (apply this, apply all SC2295)
        NEWVER=${PATCHVER#"$KERNEL"}
 
Line 103:
                echo ./staging_dir/host/bin/mkhash sha256 dl/linux-$PATCHVER.tar.xz
>>                                                                 ^-- SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
                echo ./staging_dir/host/bin/mkhash sha256 dl/linux-"$PATCHVER".tar.xz
 
Line 106:
        if [ -f dl/linux-$PATCHVER.tar.xz ]; then
                         ^-- SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
        if [ -f dl/linux-"$PATCHVER".tar.xz ]; then
 
Line 107:
                CHECKSUM=$(./staging_dir/host/bin/mkhash sha256 dl/linux-$PATCHVER.tar.xz)
>>                                                                       ^-- SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
                CHECKSUM=$(./staging_dir/host/bin/mkhash sha256 dl/linux-"$PATCHVER".tar.xz)
 
Line 110:
        $CMD ./staging_dir/host/bin/sed -i include/kernel-${KERNEL} \
                                                          ^-- SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
        $CMD ./staging_dir/host/bin/sed -i include/kernel-"${KERNEL}" \
```

**Review by graysky2 — COMMENTED** [review]
Line 50 calls $kernel but that is not defined... needs to be $KERNEL

**Comment by graysky2** [comment]
@Ansuel - When I made that change, your script worked as expected updating `include/kernel-5.4` with the hash.  Ultimately, shouldn't the existing `update_kernel.sh` get modified to do this?

**Comment by rsalvaterra** [comment]
> Ultimately, shouldn't the existing `update_kernel.sh` get modified to do this?

It must be modified, as we won't be able to update the kernels until then. @Ansuel?

**Comment by Ansuel** [comment]
@rsalvaterra can i add an option to the update_kernel script to just update the version and skipping the build? I notice the script is a little too much aggressive with config and stuff and can be problematic.

**Comment by rsalvaterra** [comment]
Wait… The fix seems trivial enough, even for my weak shell-fu. Let me take a stab at it here…

**Comment by rsalvaterra** [comment]
@graysky2, does this look sane to you (untested)?

```
diff --git a/update_kernel.sh b/update_kernel.sh
index 0cbdb1d..2c4bb09 100755
--- a/update_kernel.sh
+++ b/update_kernel.sh
@@ -155,7 +155,7 @@ if [ "$UPDATE" -eq 1 ]; then
                CHECKSUM=$(./staging_dir/host/bin/mkhash sha256 dl/linux-$PATCHVER.tar.xz)
        fi
 
-       $CMD ./staging_dir/host/bin/sed -i include/kernel-version.mk \
+       $CMD ./staging_dir/host/bin/sed -i include/kernel-$KERNEL \
                -e "s|LINUX_VERSION-${KERNEL} =.*|LINUX_VERSION-${KERNEL} = ${NEWVER}|" \
                -e "s|LINUX_KERNEL_HASH-${KERNEL}.*|LINUX_KERNEL_HASH-${PATCHVER} = ${CHECKSUM}|"
 fi
```

**Comment by rsalvaterra** [comment]
> @rsalvaterra can i add an option to the update_kernel script to just update the version and skipping the build? I notice the script is a little too much aggressive with config and stuff and can be problematic. (also didn't notice the script was already part of the maintainers tool)

We already agreed that bumping kernel versions without rebasing the patches would be a bad idea. So, what would be the use case for such an option? If it ever goes in, it needs a big, fat warning, at least.

**Comment by Ansuel** [comment]
okok will only push a fix for the script to the mailing list

**Comment by rsalvaterra** [comment]
> okok will only push a fix for the script to the mailing list

Thanks! See my diff above, I believe that one-liner is the correct fix, but I'll wait for your patch. :wink:

**Comment by graysky2** [comment]
@rsalvaterra 
> does this look sane to you (untested)?

Yep, looks right/tested on 5.4.171-->5.4.172 and works as expected.

**Comment by rsalvaterra** [comment]
> Yep, looks right/tested on 5.4.171-->5.4.172 and works as expected.

Nice! I'm bumping 5.10 to .92 as we speak, good to know it works.

**Comment by Ansuel** [comment]
Closing this. Pushed the script fix to the mailing list.

**Comment by Ansuel** [comment]
@aparcar @rsalvaterra just for reference I want to alert you that the split broke the bpf-headers package when a testing kernel version is used on the target. I already pushed a fix to the mailing list. Tagging you here in case you missed the patch

**Pull request closed without merging**
