### PR TITLE
buildroot: per-subtarget patches

### PR DESCRIPTION
**Pull request by LuKePicci**
I recently implemented this into an old chaos calmer buildroot to support a specific scenario. I would like to share this for proper review from openwrt community. I don't know if this could be of any general interest or if this is already implemented in current master in different ways.
Assuming each subtarget's kernel builds to a different build_dir subdirectory (ie. linux-*target*_*subtarget*), this patchset allows each subtarget to bring specific kernel patches into regular target's patches directories as symlinks. Then everything gets copied into quilt's platform as usual when kernel patching stage is reached.

Subtargets families sharing the same kernel patches have their patches-* folder symlinked to that one of their main family member.

I had to patch CC's buildroot and define `$(SUBTARGET)` in `rules.mk` to also get bin outputs to go into different subdirectories, but it looks like current master can do this already since that var is there already.

This could eventually be extended to files-* as well. Also, a proper make clean target is missing..

This was my first valid idea to easily manage subtargets of different cpu arch (eg. mips and arm brcm63xx). Having multiple clones of the same target for each board equiring different kernel patches was not convenient to me, and I preferred to have them all under a single target.

Please, take this as a concept. Of course, I will squash everything to a well-done single commit with proper commit message once reviewed in case.

### CODE REVIEW

**Comment by hauke** [comment]
I would like to avoid to split the patches even further.
If the arm brcm63xx needs different patches I think we can also put it into a separate target and move the common stuff between the mips and arm version into the generic part.

**Comment by LuKePicci** [comment]
Yeah, that would somehow work for the arm vs. mips brcm63xx case. However, the openwrt buildroot I had to work with was linked to an external sdk in such a way that every subtarget matched a different profile selecting different set of patches to enable slightly different hardware features like dect, pon and fxs phone ports. In that case having a different target for each board family was a bit tricky to maintain since they still shared most stuff between them. What I called a board family was a group of boards sharing the same set of kernel patches, then every board had a different Kconfig. Without my approach in this PR I would have been required to have a different target for each board family each with many subtargets for each board. Per-subtarget patches allowed to keep them all under the same target (they ware all brcm63xx after all) and symlink every subtarget to its family representative. member, usually that one with all features enabled. I found this approach to better match the current concept of targets in openwrt where each of them relates to a platform rather then a cpu arch or a different hardware variant of the same platform. Of course, refactoring that third-party kernel sources into a unified tree/patch series supporting all board families was out of my scope.

**Comment by LuKePicci** [comment]
> in such a way that every subtarget matched a different profile selecting different set of patches

Before my patches, this was basically achieved by branching the whole buildroot once for each board family, thus having multiple instances of the same target.

**Comment by ynezz** [comment]
I second https://github.com/openwrt/openwrt/pull/2851#issuecomment-604080268

**Pull request closed without merging**
