### PR TITLE
x86: switch to Linux 6.6

### PR DESCRIPTION
**Pull request by namiltd**
Switch to Linux kernel version 6.6 and drop configs, files and patches for Linux 6.1.

Issues found that still need to be resolved:
- ~~[Framebuffer broken with kernel 6.6](https://github.com/openwrt/openwrt/issues/15222)~~
- ~~[x86_64: 6.6 kernel: Intel i915 graphics card driver loading error](https://github.com/openwrt/openwrt/issues/15380)~~

### CODE REVIEW

**Comment by namiltd** [comment]
@PolynomialDivision Please read this PR and approve it.

**Comment by hauke** [comment]
I created a PR to activate CONFIG_FB_DEVICE, see #15559

**Comment by namiltd** [comment]
I think it's time to merge.

**Comment by hauke** [comment]
Could you split this into two patches please, one updating to kernel 6.6 and one removing 6.1 support please.

**Comment by namiltd** [comment]
@hauke Done.

**Pull request merged**
