### PR TITLE
[21.02] ipq40xx: backport devices

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Our wireless community needs the SXTsq 5 AC SoC. In particular, the device is ideal to be mounted on the balcony to supply public areas with internet access (we provide free internet access). This may become very important for the summer and the ongoing corona pandemic. I know the merge window is already completed, but I think it would be good to merge this. Otherwise, Gluon builds will not include this SoC.

(compile testing ...)

### CODE REVIEW

**Comment by aparcar** [comment]
@rogerpueyo @adschm thoughts?

**Comment by rogerpueyo** [comment]
We'd probably need to backport support for hAP ac2 (faea7becafc634dc882f0ad8f9388862ccd5bd0d), which can be directly cherry-picked. I'll give it a try with the device, although PolynomialDivision seems to have done it already.

**Comment by aparcar** [comment]
> We'd probably need to backport support for hAP ac2 (faea7becafc634dc882f0ad8f9388862ccd5bd0d), which can be directly cherry-picked. I'll give it a try with the device, although PolynomialDivision seems to have done it already.

Looking at the two commits the former seems to do so, or am I understanding it wrong?

**Comment by rogerpueyo** [comment]
Yes, but I'd say it's on @PolynomialDivision 's repo, not upstream.

**Comment by PolynomialDivision** [comment]
I cherry-picked from trunk? (at least I think I did it xD)

**Comment by rogerpueyo** [comment]
Sorry for the confusion. To add support for the SXTsq, we needed the support for hAP ac2 commit before. This is exactly what the PR does. I just meant to say that they had different hashes than master because they were cherry-picked to your openwrt-21.02 branch.

I gave it a try on the device. So far, so good. :smiley:

**Comment by PolynomialDivision** [comment]
BTW thanks a lot @rogerpueyo and @robimarko. Our "island-firmware" is now available. :) Let's see how many balcony we can equip with it.

image

**Comment by PolynomialDivision** [comment]
> I gave it a try on the device. So far, so good. smiley

I can also give it a try in our freifunk network. But currently, I do not have internet access except my mobile hotspot, that is why I'm blocked. But maybe later today...

**Comment by zorun** [comment]
Please update your commits to add the original commit hash (using `git cherry-pick -x`)

I am testing the hap-ac2 patch and will merge it if no issue pops up. For the SXTsq, it has just been merged to master, so I think it's best to wait a bit more for this one (but I agree it should be in 21.02).

In any case, good job for the long-running effort to support these boards :+1:

**Comment by PolynomialDivision** [comment]
> Please update your commits to add the original commit hash (using `git cherry-pick -x`)

Isn't the commit hash changed since I amended the commit message?

**Comment by aparcar** [comment]
@zorun thanks for taking over

**Comment by zorun** [comment]
So, while testing this I found an issue where the wifi interfaces just don't appear and `/sys/firmware/mikrotik/hard_config/wlan_data/` is empty. I have the same problem on master, see http://lists.openwrt.org/pipermail/openwrt-devel/2021-April/034911.html for details.

If you have this device, I'm interested to see if the hard_config partition can always be set to 0x2000, so that we can put that in the DTS: https://forum.openwrt.org/t/support-for-mikrotik-hap-ac2/23333/324

Other than that, it seems to be working nicely, but I would like to fix this issue before merging.

**Comment by PolynomialDivision** [comment]
@zorun Your descript issue is not affecting the sxtsqac? So maybe I can change the PR so we can already merge the sxtsq?

**Comment by rogerpueyo** [comment]
> @zorun Your descript issue is not affecting the sxtsqac? So maybe I can change the PR so we can already merge the sxtsq?

By reading the mailing list I understand that Thibaut, the author of the MikroTik sysfs driver, is working on it. Maybe he can provide a fix for these hap ac versions with two radios that can be backported to 21.02 with both devices, so that you can merge both devices together?

**Comment by john-tho** [comment]
Can we submit, test, and merge a quick fix for the long hard_config hap ac2 to master using a forced size for the [routerboot parser](https://github.com/openwrt/openwrt/blob/master/target/linux/generic/files/drivers/mtd/parsers/routerbootpart.c).
That way we only modify one device, and it is simpler to justify including in 21.02.
```
--- a/target/linux/ipq40xx/files/arch/arm/boot/dts/qcom-ipq4018-hap-ac2.dts
+++ b/target/linux/ipq40xx/files/arch/arm/boot/dts/qcom-ipq4018-hap-ac2.dts
@@ -189,6 +189,7 @@
                                reg = <0x80000 0x80000>;
 
                                hard_config {
+                                       size = <0x2000>;
                                        read-only;
                                };
```
Needs @zorun's device details (maybe the factory booter version is telling?) & testing.


I did not read @f00b4r0's [email](https://lists.openwrt.org/pipermail/openwrt-devel/2021-May/034915.html) as if they were going to submit a fix, but a driver change would require extra testing.

Cheers

**Comment by zorun** [comment]
Yes this is basically the patch I just sent, it's the most reasonable fix IMHO.

Since it apparently affects very few devices (actually, 1 so far), I'm merging this as it is now, including the SXTsq since @rogerpueyo run-tested it. I'll backport the hard_config patch later.

**Pull request closed without merging**
