### PR TITLE
ramips: tl-wr840n-v5 tftp image

### PR DESCRIPTION
**Pull request by alex-eri**
Missed extra images

  IMAGES += tftp-recovery.bin
  IMAGE/factory.bin := tplink-v2-image -e
  IMAGE/tftp-recovery.bin := pad-extra 128k | $$(IMAGE/factory.bin)

Common tplink tftp image is tested to be installed with "hold-button tftp"

### CODE REVIEW

**Comment by ynezz** [comment]
To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

**Comment by ynezz** [comment]
Ping.

**Comment by rotanid** [comment]
@alex-eri you have to change your commit message's title and add a sign-off, this can be done using "amend" and afterwards a force push to your "patch-1" branch.

**Comment by adrianschmutzler** [comment]
There has been a reorganization in ramips target today. Please:
- rebase/update/check your changes in mt76x8.mk

Thank you!

**Comment by adrianschmutzler** [comment]
Please have a look at the commit message here:
https://github.com/openwrt/openwrt/commit/d0ef27594a8d9156e6748e890229d2daa32465fd
It sounds as if there are two versions of TFTP bootloaders around, of which one bricks the device when TFTP is used.
So I would hesitate to provide official TFTP support for this device.
Despite, instead of inheriting Device/tplink as in your patch, one would have to explicitly add the tftp image to the 840n-v5 definition. Otherwise, we would inherit other stuff from the parent definition that we do not want in 840n-v5.

**Comment by adrianschmutzler** [comment]
@robimarko Do you have an updated opinion on this one (as initial support and commit for wr840n-v5 was from you)?

**Comment by robimarko** [comment]
Well, I am fine with TFTP images as they can be really usefull.
But the reason I intentionally did not include them is because my device came with the same U-boot as for the v4 version which had double the flash and it would completely brick the device since it would delete the U-boot.
After manually compiling the v5 U-boot TFTP worked fine, but there is no way of knowing which version is on there without serial.

**Comment by adrianschmutzler** [comment]
@robimarko 
So, if we provide a TFTP version here, there will most probably be users bricking there device with it?
Because that sounds like a NAK to me (although I do not bear any authority)

**Comment by robimarko** [comment]
Possibly, if they have one of the early units that probably by mistake shipped with U-boot for WR840N v4 and were configured for twice the flash size.

**Comment by alex-eri** [comment]
@robimarko v5 has 4M flash. how tftp can break router?

When there is no support for v5 i used v4 image (made without luci) on that router.

**Comment by robimarko** [comment]
@alex-eri Easily, it will overwrite the U-boot with junk and it hard bricked then

**Comment by alex-eri** [comment]
u-boot is on front of firmware. how it can be overwritten?

**Comment by robimarko** [comment]
Well, its not really rewritten as much since U-boot expects 8MB of flash instead of 4MB it will try to erase all of that except for 128K or something like that for U-boot, but since it wont be able to address any further than 4MB it will simply skip to the beginning of the flash and erase U-boot.

**Comment by adrianschmutzler** [comment]
I will close this PR:
Based on the information given by @robimarko (https://github.com/openwrt/openwrt/commit/d0ef27594a8d9156e6748e890229d2daa32465fd and discussion above), early versions of this device were shipped with wrong uboot. This can result in bricking the device when using the tftp image on those. As the user cannot determine the uboot version from the outside, I prefer not having the risk of a bricked device over the convenience of having a tftp image.

@alex-eri Nevertheless, thanks for putting efforts into compiling that patch.

**Pull request closed without merging**
