### PR TITLE
Eht 11be

### PR DESCRIPTION
**Pull request by januszdziedzic**
Add option to enable hostapd 11BE.
Add UCI option to configure EHT (and EHT320).
Mark mt7996e as 11BE capable.

### CODE REVIEW

**Comment by wlshdjj** [comment]
The mac80211.sh is missing ";;" at the end of line 311:

**Comment by januszdziedzic** [comment]
yes, seems wasn't there before :)
```
                case "$htmode" in
-                       HE20) op_class=131;;
-                       HE*) op_class=$((132 + $vht_oper_chwidth))
```
Will fix it:

**Review by danpawlik — APPROVED** [review]

**Review by danpawlik — APPROVED** [review]
LGTM.

`Tested-by: Daniel Pawlik <pawlik.dan@gmail.com>`

**Review by frebergguru — APPROVED** [review]
Looks good

**Comment by januszdziedzic** [comment]
board.json and config/wireless generation to work correctly need
https://github.com/jow-/ucode/pull/222

Without it will generate HExx

**Comment by januszdziedzic** [comment]
BTW, who should kick package/utils/ucode?

For mt7996 I see 233 firmware will be also soon in linux-firmware.git
https://patchwork.kernel.org/project/linux-wireless/patch/20240926034802.28294-1-shayne.chen@mediatek.com/

**Comment by danpawlik** [comment]
Could we go with that patch? It is working for a while on my BPI-R4 and so far I don't see any issue.

**Comment by blogic** [comment]
I just pulled this into my staging tree and will push it to the main branch shortly incl iwinfo and ucode updates

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
