### PR TITLE
Bring WireGuard in-tree for 21.02

### PR DESCRIPTION
**Pull request by lipnitsk**
Cherry pick the work done in #3885 and WireGuard fixes from master. Benefits:
- Performance improvements
- Maintainability (@zx2c4 offered to support the backport patch series, but will not support wireguard-linux-compat). This specific backport is in widespread use, being part of SUSE's enterprise kernel, Oracle's enterprise kernel, Google's Android kernel, Gentoo's distro kernel, and probably more. These patches are from the backport tree which is maintained in the open here: https://git.zx2c4.com/wireguard-linux/log/?h=backport-5.4.y
- Gets rid of hacky wireguard-linux-compat

### CODE REVIEW

**Comment by zx2c4** [comment]
How would you feel about squashing a lot of the wireguard commits together? So the series would look like:

- zynq
- kernel-5.4: add wireguard patches [my patches]
- kernel: migrate wireguard into kernel tree [your packaging work]
- wireguard-tools: bump [my simple version bump]

**Comment by lipnitsk** [comment]
I'm completely fine with that. Just don't know if it's customary to squash cherry-picks here. I think if the message inside the squashed commit mentions the SHAs we should be good.

**Comment by zx2c4** [comment]
Oh. If you're supposed to reference master-branch patches, then feel free to ignore my suggestion.

**Comment by lipnitsk** [comment]
Let me just squash for now. Can always revert back if somebody objects..

**Comment by lipnitsk** [comment]
@zx2c4 looks better?

**Comment by zx2c4** [comment]
Perfecto.

**Comment by adschm** [comment]
At the risk of being shouted at again:
Policy is to cherry-pick patches from master individually with proper reference (i.e. git cherry-pick -x).
If somebody managed to mess it up in master and needed many patches, just using the same patches in stable branch has the benefit that you can easily identify what's been backported and what's not, without having to read lots of text in commit message etc.

**Comment by zx2c4** [comment]
> Oh. If you're supposed to reference master-branch patches, then feel free to ignore my suggestion.

Ahh looks like I was very wrong after all. Sorry about that!

**Comment by adschm** [comment]
It won't really be nicer that way, but I've ended up comparing folder history too often to not appreciate this approach ...

**Comment by lipnitsk** [comment]
@adschm np - just reverted it back to the un-squashed set.

**Comment by Borromini** [comment]
@lipnitsk Correct me if I'm wrong, but I'm seeing these added statically into the kernel:

```
+CONFIG_PACKAGE_kmod-crypto-kpp=y
+CONFIG_PACKAGE_kmod-crypto-lib-blake2s=y
+CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y
+CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y
+CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y
+CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y
```

I can find the menuconfig entries for kmod-crypto-kpp, but not for those crypto libs. The search does show them but they don't seem to be selectable anywhere. Is that intentional? Is there a technical reason to not have them selectable (and selectable as modules [m])?

If someone includes WireGuard ([*]), then the dependencies will be included in the final images anyway. 

I'll be giving the PR a test spin on some platforms soon regardless. Thank you both for the work.

**Comment by lipnitsk** [comment]
Correct me if I'm wrong, but `PACKAGE_` selections in top-level .config add nothing static to the kernel. They define .ipks that get built, `y` means it gets auto installed into your image and `m` is built for your package repo so that the device can install it at a later date. In either case, kernel modules from .ipk are loaded dynamically. The reason you are seeing `y` there is probably because wireguard-tools or luci-app-wireguard is set to `y` in your config and these hidden libraries are dependencies for those.

**Comment by Borromini** [comment]
No, my bad, you're right, all those packages still show their kernel modules in /lib/modules/$(uname -r). Sorry for the noise.

I just tested this on an EdgeRouter 4 (octeon target). Compile-tested on mt7621 as well.

Tested-by: Stijn Segers <foss@volatilesystems.org>

**Comment by zx2c4** [comment]
FYI https://github.com/openwrt/openwrt/commit/196f3d586f11d96ba4ab60068cfb12420bcd20fd

**Comment by lipnitsk** [comment]
Yeah, I saw that. What's the policy on kernel updates on release branches? I'd like to bring it in, but kernel has not been updated here since 21.02 branched. I guess I can just cherry-pick all the updates and see what the core folks say.

**Comment by lipnitsk** [comment]
Actually, one update did happen, so may be it is okay. 76d1168d0d4b9d76e2ad78c0fc6b255561deb284

**Comment by Borromini** [comment]
It's okay, but someone has to merge it. I've tested this PR like this since that mimics master:

1. 21.02 HEAD
2. Pulled master .100 and .101 bumps
3. Applied this PR
4. Pulled Jason's master .102 bump

**Comment by lipnitsk** [comment]
ok, done. Will still need to grab https://patchwork.ozlabs.org/project/openwrt/patch/20210305035321.1097894-1-ilya.lipnitskiy@gmail.com/ whenever it is merged to master to fix mt7621.

**Comment by hauke** [comment]
When 196f3d586f11d96ba4ab60068cfb12420bcd20fd is added as a separate commit the kernel is not compiling between the commit adding the initial patches and 196f3d586f11d96ba4ab60068cfb12420bcd20fd. 
I think it is more important that every version compiles, otherwise using git bisect will not work any more. 
I would squash 196f3d586f11d96ba4ab60068cfb12420bcd20fd into 3888fa78802354ab7bbd19b7d061fd80a16ce06b and probably 23b801d3ba57e34cc609ea40982c7fbed08164e9 too. 

Is this needed too 0c0cb97da7f5cc06919449131dd57ed805f8f78d ? I ran into this some time ago, but I do not know exactly what configuration I used.

**Comment by lipnitsk** [comment]
464451d9ab824c2ed62f7da33f0a965f562714c8 and 2a27f6f90a430342cdbe84806e8b10acff446a2d fix certain target builds too.

**Comment by lipnitsk** [comment]
@hauke took a stab at it...

Take a look at 12585261e38c82149b385ac16df1180e6f88a6fd, all squashes are in there, I preserved the first cherry-pick message and all the cherry pick SHAs.

**Comment by lipnitsk** [comment]
I think there is still an argument for squashing 464451d9ab824c2ed62f7da33f0a965f562714c8 into 06351f1bd0455abacb700db5098bb798f66948fc, otherwise bisect may not be happy on commits in between for bcm47xx, bcm63xx, lantiq/ase, ath25 builds

**Comment by hauke** [comment]
Thank you for the pull request, I merged it into openwrt 21.02 branch.

**Pull request closed without merging**
