### PR TITLE
ipq806x: add support for GL.iNet GL-B1300

### PR DESCRIPTION
**Pull request by handongming**
This patch adds support for GL.iNet GL-B1300

Specification:
- SOC:        IPQ4028 / QCA Dakota
- RAM:        256 MiB
- FLASH:      32 MiB
- ETH:        Qualcomm Atheros QCA8075 Gigabit Switch (2 x LAN, 1 x WAN)
- USB:        1 x 3.0 (via Synopsys DesignWare DWC3 controller in the SoC)
- WLAN1:      Qualcomm Atheros QCA4028 2.4GHz 802.11bgn 2:2x2
- WLAN2:      Qualcomm Atheros QCA4028 5GHz 802.11a/n/ac 2:2x2
- INPUT:      one reset and one WPS button
- LEDS:       3 leds: Power, WIFI(only for 2.4G currently), and one reserved
- UART:       1 x UART on PCB (3.3V, TX, RX, GND) - 115200 8N1

Installation:
Method 1:
- use serial port to stop uboot
- uboot command: run lf
Method 2:
- push down reset button and power on
- wait until three leds constantly on then release
- upgrade by uboot web at http://192.168.1.1
Note:
- the sysupgrade image need to be renamed to lede-gl-b1300.bin in both method.
- the sysupgrade image can be automatically downloaded if tftp server at
  192.168.1.2 have that file.
- the wifi led will be flashing when writing image.

Signed-off-by: handongming <handongming@gl-inet.com>

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @handongming,

Please, read our [submitting patches rules](https://lede-project.org/submitting-patches), and make sure your pull request follows them. Your SoB line (`Signed-off-by: handongming <handongming@gl-inet.com>`) must contain real name.

Cheers,
Piotr

**Comment by handongming** [comment]
Thanks. I've changed.

**Comment by blogic** [comment]
merged, Thanks !

i had to manually rebase package/firmware/ipq-wifi/Makefile, please verify that it still works on device. I have only compile tested it

**Comment by ecsv** [comment]
To the author @handongming  of the patch: There is an official process to upstream the BDFs to ath10k-firmware. See https://github.com/openwrt/openwrt/pull/713#issuecomment-369511149 for more info about that.

The ipq-wifi is a little bit problematic and I already accidentally broke images by not checking enough what I had enabled during the build. And I think Ben Greear also has problems with it when he wants to provide his alternative firmware (but maybe I remember this incorrectly).

**Comment by handongming** [comment]
@ecsv Thank you for your guidance. I just followed your way to write a letter to ath10k maillist.

**Pull request closed without merging**
