### PR TITLE
[RFT] toolchain/binutils: switch to version 2.37 by default

### PR DESCRIPTION
**Pull request by aparcar**
Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by neheb** [comment]
```
Tested-by: Rosen Penev <rosenp@gmail.com>
```

**Comment by LGA1150** [comment]
Nodejs failed to build with binutils 2.37.
https://www.mail-archive.com/bug-binutils@gnu.org/msg38662.html

**Comment by dhewg** [comment]
Which seems to be fixed by
https://sourceware.org/git/?p=binutils-gdb.git;a=patch;h=1c611b40e6bfc8029bff7696814330b5bc0ee5c0

**Comment by dhewg** [comment]
Works fine on my devices:
```
Tested-by: Andre Heider <a.heider@gmail.com> # lantiq/xrx200
Tested-by: Andre Heider <a.heider@gmail.com> # ramips/mt7621
```

**Comment by Ansuel** [comment]
Tested-by: Ansuel Smith <ansuelsmth@gmail.com>

I use this from a long time without a problem on my r7800

**Comment by aparcar** [comment]
Merged, thanks evyerone for testing.

**Comment by LGA1150** [comment]
> Which seems to be fixed by
> https://sourceware.org/git/?p=binutils-gdb.git;a=patch;h=1c611b40e6bfc8029bff7696814330b5bc0ee5c0

Is this fix included in 2.37 release?

**Comment by dhewg** [comment]
Nope, but it's in the 2.37 branch, so should be in the next point release:
https://sourceware.org/git/?p=binutils-gdb.git;a=shortlog;h=refs/heads/binutils-2_37-branch

**Pull request closed without merging**
