### PR TITLE
[21.02] Backport mvebu updates for U-boot and add support for Turris Omnia

### PR DESCRIPTION
**Pull request by BKPepe**
Since ``tools/libressl`` was updated in OpenWrt 21.02 in this PR https://github.com/openwrt/openwrt/pull/9326, which was required to compile recent U-boot versions. This allowed backporting newer U-boot versions from the master branch to have up-to-date U-boot and added U-boot for Turris Omnia router with additional patches related to it, which will be included in the upcoming U-boot release 2022.04.

This compiles successfully on Ubuntu 21.10 and compiled U-boot was tested on the Turris Omnia router.

@dhewg Can you check it on your end that it works for you? Since I don't backport https://github.com/openwrt/openwrt/pull/4709.

____

If my proposal gets accepted, it would allow me to drop separate package [omnia-uboot](https://gitlab.nic.cz/turris/os/packages/-/blob/e337d2994b9d35b72ad4dd2503eef10bba39c740/hardware/omnia/omnia-uboot/Makefile) within the Turris OS and use and test U-boot versions provided by OpenWrt.

### CODE REVIEW

**Comment by ynezz** [comment]
I'm not sure if bumping U-Boot from 2021.01 to 2022.01 in the release being out for one year is ok.

**Comment by BKPepe** [comment]
I understand why you might be against doing that, but from my point of view, it has so many benefits to manufacturers (in my case) or users as well.

In both cases, you don't need to wait until there is a new version of OpenWrt, which happens approx. once per year. You can enjoy more features and bug fixes with a new version during that time in the stable branch.

For me, it helps that we (at least in Turris) can unify the U-boot version across all Turris Omnia revisions with the stable branch already, and we don't need to wait until a new OpenWrt release. In the meantime, we can have it on our playground and fiddle around it, but I know that some users don't use Turris OS and already use OpenWrt.

On the other hand, I can see that you are against bumping the U-boot version as updating U-boot can be very dangerous. You could argue that there is possible to use the older version of U-boot and add Turris Omnia straight away. That could also be possible, but it will require to backport so many patches. The DDR training mostly gets into the upcoming version ``2022.04``, but we should not forget about the rest.

Features enabled for Turris Omnia:
**since v2021.10:**
- [NVMe support](https://source.denx.de/u-boot/u-boot/-/commit/1b713f15501723efd4731ea2985f6fd81d309158)
- [GPT partition support](https://source.denx.de/u-boot/u-boot/-/commit/f4ce28ab740d8728f3f580febbc3598a1498df18)

It means that you can boot from PCIe-USB, PCIe-SATA controllers, and even from NVME disks, including GPT partitions. It could be helpful in cases for users who wear out their eMMC.

In general, I'm talking about improvements for A38x, where there is now an RTC driver, fixed and improvement things related to SPL and PCIe. That could help for the existing U-boot images for ``SolidRun ClearFog A1`` and ``Kobol Helios 4``.

It is going to help ``Marvell ESPRESSObin`` as well. There were multiple improvements for the A3720 PCIe driver in U-boot. In U-boot versions ``2021.07``, ``2021.01``, ``2022.04``. And also higher speed while using UART.

So, it is improvements for all U-boot mvebu targets.

**Comment by ynezz** [comment]
> adding a new U-boot package for a new

I fail to see, how can this cause regressions.

> Who knows, right?

We now know for sure a70383080694f26d13db8341a83261f6b1c45f12.

**Comment by dhewg** [comment]
Yeah, sorry, I didn't have any free time for stuff like this at all.
But anyway, I'm using a firmware build from master with a non-master userland. That works just fine - at least on espressobin - since you need to flash it to NOR. With that I mind I really care about the branches but don't have an opinion on what should be backported either for other boards

**Pull request closed without merging**
