### PR TITLE
Add kmod-crypto-echainiv as a dependency of kmod-ipsec.

### LINKED ISSUE #222: ipsec broken in master
As of commit 8ad3f44dcefb72e850091ef857f1d0236ef66c4b, the kmod-ipsec package's dependency list is incomplete. That commit split the crypto/chainiv.ko kernel module out from kmod-crypto-iv in favor of providing it via the kmod-crypto-echainiv package. The crypto-echainiv package should get automatically enabled when kmod-ipsec is enabled.

### PR DESCRIPTION
**Pull request by nmeyerhans**
Fixes #222

### CODE REVIEW

**Review by seragh — COMMENTED** [review]
kmod-crypto-iv gets dropped in Linux 4.8, possibly you don't need it anymore when you add kmod-crypto-echainiv to ipsec instead.

Anyway sorry for the inconvenience

**Comment by wigyori** [comment]
Build-tested on ar71xx and rb532 (4.4 and 4.1 respectively), so Ack. Before merging, please update the commit message to "packages: kmod-ipsec: Add kmod-crypto-echainiv as a dependency of kmod-ipsec".

Thx,
-w-

**Comment by nmeyerhans** [comment]
I've updated the commit message. I don't have permission to merge this PR myself, so if somebody with the necessary access could do that for me, I'd appreciate it.

**Comment by wigyori** [comment]
There we go - thanks!

**Pull request merged**
