### PR TITLE
ar71xx: switch TP-LINK RE450 v1 to dynamic partitioning 

### PR DESCRIPTION
**Pull request by dasty**
**Version 2**

As mentioned in commit 5f24933 recent changes on ar71xx (switch to 4.14,
memory compaction, ...) cause an increase in kernel size, making it too
big for RE450.

RE450 images were not build due to the following error message:
os-image partition too big (more than 1572864 bytes): Success

Tested on RE450, device boots and was used to send this patch.

NOTE: switch to dynamic partitioning instead of switching RE450 to target
      tiny was suggested by David Bauer <mail@david-bauer.net>

Reported-by: Enrico Mioso mrkiko.rs@gmail.com
Signed-off-by: Radek Dostál rd@radekdostal.com

---
**Version 1**

As mentioned in commit 5f249333090741ecba190855b13c87fd93ca2520 recent
changes on ar71xx (switch to 4.14, memory compaction, ...) cause
an increase in kernel size, making it too big for RE450.

Its images are not build due to the following error message:
os-image partition too big (more than 1572864 bytes): Success

Tested on RE450, device boots and was used to send this patch.

Reported-by: Enrico Mioso <mrkiko.rs@gmail.com>
Signed-off-by: Radek Dostál <rd@radekdostal.com>

----
**NOTE: It may be worth to check other devices. Unfortunately I am only in possession of RE450.**

### CODE REVIEW

**Comment by blocktrron** [comment]
I think a better aproach would be to switch the device to dynamic partitioning introduced in this commit: https://github.com/openwrt/openwrt/commit/408c54b02f6a6dd2c0ae30a7885a37c9ac4c1b53

**Comment by dasty** [comment]
@blocktrron - thank you for your suggestion. I just pushed a new version of the patch where instead of switching to tiny I am using dynamic partitioning.

**Comment by rotanid** [comment]
@dasty please update the title of your PR accordingly, too ;)

**Comment by dasty** [comment]
@rotanid done, thank you for your suggestion.

**Pull request closed without merging**
