### PR TITLE
px5g: Fix certificate signature using wolfSSL

### PR DESCRIPTION
**Pull request by elms**
Signed-off-by: Elms <jeff@wolfssl.com>

### CODE REVIEW

**Comment by aparcar** [comment]
Commit message missing.

**Comment by dgarske** [comment]
Tied to this wolfSSL issue report: https://github.com/wolfSSL/wolfssl/issues/3691
Fix looks good. Thanks @elms

**Comment by PolynomialDivision** [comment]
Compile and runtested on OpenWrt 4300 (Trunk).

```
openssl x509 -text -noout -in uhttpd.crt 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0f:46:d5:aa:81:ae:a5:a4:be:79:20:4f:e9:ca:fa:e9
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = ZZ, ST = Somewhere, L = Unknown, O = OpenWrt3a812b84, CN = OpenWrt
        Validity
            Not Before: Jan 25 23:04:22 2021 GMT
            Not After : Jan 26 23:04:22 2023 GMT
        Subject: C = ZZ, ST = Somewhere, L = Unknown, O = OpenWrt3a812b84, CN = OpenWrt
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:43:fd:b3:1c:48:4f:53:99:86:62:d7:e6:f4:f3:
                    e8:42:ac:9b:4f:95:ef:ea:8c:0c:85:37:f8:a8:39:
                    78:70:85:41:7c:71:60:54:b0:33:bf:c8:d8:d5:ea:
                    70:3e:75:eb:46:7d:10:eb:95:17:20:db:25:0a:f1:
                    06:6a:0b:04:7c
                ASN1 OID: prime256v1
                NIST CURVE: P-256
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:f3:16:c7:63:b7:fd:57:3e:94:70:0a:e4:05:
         8c:40:a5:b8:d4:9f:52:fb:78:05:cd:ce:63:84:70:5b:5b:12:
         dc:02:21:00:cd:37:74:aa:8a:67:30:ff:5e:a0:ff:1e:94:cb:
         16:12:d5:b2:8f:6d:c8:78:f1:db:b8:8c:fa:92:d0:d2:e2:7e
```

Thanks a lot @dgarske and @elms

**Comment by aparcar** [comment]
@elms Is Elms your real and full name? We somewhat need it for the Signed-of-by line.

**Comment by elms** [comment]
@aparcar yes, Jeff Elms. Let me know if I  need to amend and push

**Comment by aparcar** [comment]
Please fix the signed off, I can then push the package. Thank you very much for the quick response and fix!

**Review by dangowrt — APPROVED** [review]
Makes sense and looks good. Thank you!

**Comment by aparcar** [comment]
Merged, that k you very much!

**Pull request closed without merging**
