### PR TITLE
ipq40xx: switch to Kernel 5.10

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Devices I tested:
- Fritz!Box 7530 (running for a week without any issues)
- SXTsq 5 AC (running for a week without any issues)

### CODE REVIEW

**Comment by adschm** [comment]
Note that all of these "switch to" commits will need commit messages eventually. These drafts are only helpful to have something to discuss and build images against.

**Comment by aparcar** [comment]
There seem to be issues with the mikrotik subtarget: https://github.com/aparcar/openwrt/actions/runs/1296535398

**Comment by john-tho** [comment]
I have been using ipq40xx 5.10 with out-of-tree mikrotik devices without any issues, but mine are not buildbot config.

In your CI pipeline, I can only see one ipq40xx/generic device—cellc_rtl30vw [failing for image size](https://github.com/aparcar/openwrt/runs/3771745179?check_suite_focus=true#step:15:11960):

https://github.com/openwrt/openwrt/blob/21c7a8593d86175c0764d23e77bb019fd9617f53/target/linux/ipq40xx/image/generic.mk#L268

```
mv /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb.new /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb
4235264 bytes (4.2 MB, 4.0 MiB) copied, 0.00838848 s, 505 MB/s
WARNING: Image file /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb is too big: 4235264 > 4194304
cp /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb /home/runner/work/openwrt/openwrt/openwrt/bin/targets/ipq40xx/generic/openwrt-ipq40xx-generic-cellc_rtl30vw-fit-uImage.itb
cp: cannot stat '/home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb': No such file or directory
make[4]: *** [Makefile:17: /home/runner/work/openwrt/openwrt/openwrt/bin/targets/ipq40xx/generic/openwrt-ipq40xx-generic-cellc_rtl30vw-fit-uImage.itb] Error 1
```

**Comment by aparcar** [comment]
Anything we can do about that!

**Comment by PolynomialDivision** [comment]
> There seem to be issues with the mikrotik subtarget: https://github.com/aparcar/openwrt/actions/runs/1296535398

It looks like generic has issues?

btw: I updatet the PR and removed the part where I deleted all 5.4 stuff.

**Comment by PolynomialDivision** [comment]
I don't have any issues building generic device with my normal buildroot.

**Comment by xabolcs** [comment]
> Anything we can do about that?

@CHKDSK88 (@obsy ) do you have that device? Do you know anything  about that `4096 K` kernel size limit?
Tips for workaround? Does that device support lzma compression? Or zImage kernel type?

**Comment by obsy** [comment]
No, I don't have device anymore.

**Comment by adschm** [comment]
There was a whole bunch of devices that failed during full build, just look at my commit message here:
https://github.com/openwrt/openwrt/commit/7b1fa276f5a220782f702b099fc68a079c2a0fd5

There is probably at least one more of them ...

**Comment by adschm** [comment]
Apart from that, testing support has been out for 7 days. I think we should give this one or two _months_ before we switch.

**Comment by aparcar** [comment]
> Apart from that, testing support has been out for 7 days. I think we should give this one or two months before we switch.

Fine with me, this PR is mostly to collect feedback and create an overview.

**Comment by adschm** [comment]
> > Apart from that, testing support has been out for 7 days. I think we should give this one or two months before we switch.
> 
> Fine with me, this PR is mostly to collect feedback and create an overview.

I was a bit afraid of too much PR pollution initially, but I think this kind of tracking is a good idea to make this process more systematic and kind of collect the discussion somewhere. :-)

So yes, just keep it open.

**Comment by xabolcs** [comment]
> There was a whole bunch of devices that failed during full build, just look at my commit message here:
> 7b1fa276f5a220782f702b099fc68a079c2a0fd5

GL-iNet GL-B1300 is on the list.

And it looks like with it's first version of U-Boot (`U-Boot 2012.07 [Chaos Calmer 15.05.1,r35193] (Apr 13 2018 - 13:54:46)`) it does have boot problems indeed: it's unable to start OpenWrt, just restarts. (No serial access for now)

[Debrick via U-Boot](https://docs.gl-inet.com/en/3/troubleshooting/debrick/) works.

When I got serial access, then I will test newer [vendor U-Boot releases](https://github.com/gl-inet/uboot-ipq40xx).

(For the record, I already [notified / asked the vendor](https://forum.gl-inet.com/t/ipq40xx-kernel-size-and-u-boot-v5-10-is-too-big-for-4-mb/17619) about this `KERNEL_SIZE:=` problem)

**Comment by adschm** [comment]
@john-tho Will we face the 4k sector problems here with 5.10?

**Comment by john-tho** [comment]
Not 4k sector problems for the ipq40xx_mikrotik subtarget.
`CONFIG_MTD_SPI_NOR_USE_4K_SECTORS=y` was not used there.
Cheers

**Comment by adschm** [comment]
Hmm, unless there are queued changes I am not aware about, it looks best to me to switch fast now.
This will have the relevant devices disabled and thus hopefully create enough attention to have them fixed (if possible) before we branch ...

Does anybody have an idea whether there are devices out there which are not shielded by KERNEL_SIZE, i.e. will not fail to build but fail to boot instead?

**Comment by xabolcs** [comment]
>     * 
> 
> 
> Until the [proper fix arrives](https://forum.gl-inet.com/t/ipq40xx-kernel-size-and-u-boot-v5-10-is-too-big-for-4-mb/17619/3) for those devices, it would be nice to limit them to 4 MB kernel, IMHO.

GL.iNet's [`uboot-ipq40xx` repository](https://github.com/gl-inet/uboot-ipq40xx) got the fix and a new U-Boot binary: the `KERNEL_SIZE` can be updated to 8192k (and should be enabled for GL-AP1300 and GL-B2200 too)!

It would be nice to 
* update the Wiki pages about this U-Boot version, and 
* switch to `Device/FitzImage` for the remaining / upcoming `glinet-ipq40xx` devices

**Comment by adschm** [comment]
> My CI builds fine as well using the Buildbot settings (nevermind the MacOS failure): https://github.com/aparcar/openwrt/actions/runs/1387549572

Then it's probably just a build problem on my side.

**Comment by xabolcs** [comment]
@aparcar 
> My [CI](https://github.com/aparcar/openwrt/actions/runs/1387549572) builds fine as well using the Buildbot settings ...

I don't see 5.10 kmods in the downloadable artifact. The diff does not have the change from this PR, and the "Set configuration" step doesn't list related config.

How does that CI build relates to this PR?

**Comment by PolynomialDivision** [comment]
I'm already building ipq40xx images with DSA support (that needs 5.10) kernel. Whats blocking this PR?

**Comment by aparcar** [comment]
> How does that CI build relates to this PR?

@xabolcs Good catch, you're right! It wasn't in my staging tree and therefore build the Kernel 5.4 - thanks! Building with 5.10 results in breakage: https://github.com/aparcar/openwrt/runs/4085044480?check_suite_focus=true

```
mv /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb.new /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb
WARNING: Image file /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb is too big: 4237312 > 4194304
cp /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb /home/runner/work/openwrt/openwrt/openwrt/bin/targets/ipq40xx/generic/openwrt-ipq40xx-generic-cellc_rtl30vw-fit-uImage.itb
cp: cannot stat '/home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb': No such file or directory
make[4]: *** [Makefile:17: /home/runner/work/openwrt/openwrt/openwrt/bin/targets/ipq40xx/generic/openwrt-ipq40xx-generic-cellc_rtl30vw-fit-uImage.itb] Error 1
make[4]: Leaving directory '/home/runner/work/openwrt/openwrt/openwrt/target/linux/ipq40xx/image'
make[3]: *** [Makefile:24: install] Error 2
make[3]: Leaving directory '/home/runner/work/openwrt/openwrt/openwrt/target/linux/ipq40xx'
make[2]: *** [Makefile:11: install] Error 2
make[2]: Leaving directory '/home/runner/work/openwrt/openwrt/openwrt/target/linux'
time: target/linux/install#342.14#37.42#357.94
    ERROR: target/linux failed to build.
make[1]: *** [target/Makefile:25: target/linux/install] Error 1
make[1]: Leaving directory '/home/runner/work/openwrt/openwrt/openwrt'
make: *** [/home/runner/work/openwrt/openwrt/openwrt/include/toplevel.mk:230: target/install] Error 2
Error: Process completed with exit code 2.
```

**Comment by adschm** [comment]
> > How does that CI build relates to this PR?
> 
> @xabolcs Good catch, you're right! It wasn't in my staging tree and therefore build the Kernel 5.4 - thanks! Building with 5.10 results in breakage: https://github.com/aparcar/openwrt/runs/4085044480?check_suite_focus=true
> 
> ```
> mv /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb.new /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb
> WARNING: Image file /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cellc_rtl30vw-fit-uImage.itb is too big: 4237312 > 4194304

So, is there a comfortable way to identify all devices not building without having to individually disable and rebuild until it works?

**Comment by robimarko** [comment]
I still don't understand why it builds locally for me just fine with the buildbot config, I dont get a single too large error.

**Comment by adschm** [comment]
> I still don't understand why it builds locally for me just fine with the buildbot config, I dont get a single too large error.

Size difference is 43 kB. If you have feeds installed and build-settings as you stated, maybe there is one or two additional options that reduze size again below this threshold?

**Comment by robimarko** [comment]
Yeah, I cleaned everything up in my env today.
And just enabled the CONFIG_TESTING_KERNEL and CONFIG_BUILDBOT and I hit the size issue now, so it was the dirty env and config kind of issue.

I don't know where can we save the additional 43kB, even if it squeeze it now it's gonna pop up back in a couple of months.
Cellc rtl30vw already uses LZMA so we can't really compress the kernel further.

**Comment by adschm** [comment]
> Yeah, I cleaned everything up in my env today. And just enabled the CONFIG_TESTING_KERNEL and CONFIG_BUILDBOT and I hit the size issue now, so it was the dirty env and config kind of issue.
> 
> I don't know where can we save the additional 43kB, even if it squeeze it now it's gonna pop up back in a couple of months. Cellc rtl30vw already uses LZMA so we can't really compress the kernel further.

My plan actually is to bump ASAP, disable all affected devices, and then wait for people to make them work again.

But this requires quite some time, so I haven't done it yet. If somebody likes to identify all affected devices, please do so.

**Comment by robimarko** [comment]
@adschm I manually went and disabled the devices that were falling.
Here is the patch that disables them:
https://github.com/sartura/openwrt/commit/09a201b21cc227fbf2924e34de75886a7b769fae

**Comment by adschm** [comment]
@robimarko Thanks. Can I use (=merge) that patch as-is if the target builds with that and 5.10?

**Comment by robimarko** [comment]
Sure, that is why I shared it.

**Comment by xabolcs** [comment]
@adschm , but please don't disable those `glinet` devices!

**Comment by adschm** [comment]
Merged.

Thanks for helping me out here ...

**Comment by CHKDSK88** [comment]
I prepared switch to zImage for Cell-C:
https://github.com/openwrt/openwrt/pull/4751

**Pull request closed without merging**
