### PR TITLE
[18.06] ramips: remove RB750GR3 support

### PR DESCRIPTION
**Pull request by f00b4r0**
faf94d926e2810f895f2a98d4a49ee2fe8f673e8 added support for a hacked
device where the original boot loader (routerboot) has been replaced
by u-boot.

Support for this device with stock bootloader is possible (as evidenced
by support for the RBM33G), and conflicts with this code.

Remove conflicting support before release.

Signed-off-by: Thibaut VARÈNE <hacks@slashdirt.org>

### CODE REVIEW

**Comment by psyborg55** [comment]
i'm sure the author is waiting your support for this device with stock bootloader since you say is possible. also what exactly is conflicting here?

**Comment by f00b4r0** [comment]
https://github.com/f00b4r0/openwrt/commits/rb750gr3routerboot

**Comment by mkresin** [comment]
I totally agree that we should use the stock bootloader wherever possible.

> Remove conflicting support before release.

Well, support for the RB750GR3 is already included in the LEDE 17.04 release.

I'm fine to **replace** the current rb750gr3 image with a version that works with stock bootloader (and is incompatible with already installed images due to different boardname in the image metadata).

It doesn't happen that often but I have to agree with @psyborg55. I neither see the conflict nor the need to drop working code without a proper replacement.

**Comment by f00b4r0** [comment]
Of course.

It makes all the more sense to burden ourselves with supporting code that should never have been supported in the first place for yet another major release cycle.
And, assuming that there is more than a single user for that code, I look forward to the bug reports when 19.x releases and people running their u-boot'ed device on 18.06 will try to upgrade to the routerboot-compatible (but not u-boot) 19.x images and complain that sysupgrade refuses them.

Meanwhile, @jow seemed to have a different opinion on device removal?

**Comment by psyborg55** [comment]
that's why u should use universal u-boot version from @pepe2k and easily support 1806 19xx routerboot or whatever other firmware you want to load

**Comment by f00b4r0** [comment]
@psyborg55 feel free to submit a patch to that effect.

**Comment by mkresin** [comment]
> I look forward to the bug reports when 19.x releases and people running their u-boot'ed device on 18.06 will try to upgrade to the routerboot-compatible (but not u-boot) 19.x images and complain that sysupgrade refuses them.

Excuse me if i have an obvious brainfart, but the very same applies to users using the LEDE 17.04 image. In worst case they file reports because of the missing image. Assuming you wip changes will make it into a future release, they might file bugs due to the metadata mismatch.

**Comment by f00b4r0** [comment]
I'll try to make it simple:

- This code should never have been accepted: it should certainly not be part of a release and if it accidentally was part of one that should absolutely not be reason to continue what is IMO a mistake.
- This code does not support the stock hardware
- This code is a maintenance burden (it's a custom hack, in essence)
- This code will induce confusion with end user when the new code is introduced
- There will be no upgrade path between this code and the new support

Each and every one of these facts is reason enough on its own to warrant the removal of this code (unless you suggest that once bad code goes in it can't go out unless a replacement is provided).

Emphasising again, _there will be no upgrade path_ from the current RB750Gr3 support to the new one. The supplementary rationale from my point of view is thus precisely to break the support chain and make it perfectly clear that current support stops in 18.06 without what could be taken as a sign of a transition ("oh, image has changed name but it should still be the right one"): old support in 17, nothing in 18, new support in 19: clean break.

By the way, in that regard any request to offer an immediate replacement _before_ removal seems to be totally missing that "no upgrade path" point.

Thus 18.06 should not claim to support this hardware as is and I think that for users (again, assuming there's more than one, something I have my doubts about) that stick to releases, having the support dropped for 18 and possibly reinstated for the stock hardware in 19 sends the correct signal.

Finally, if there ever is a bugreport claiming the image file is missing, it's a lot easier to deal with ("support has been dropped, close bug") than having to explain why the new image cannot be flashed over the old one.

I will now rest my case.

**Comment by mkresin** [comment]
Got your point.

> there will be no upgrade path

Got it and I'm fine with it as I share your opinion that there is most likely only one users.

Yes the current support for the board is ugly but it seems to work at least and I'm not going to remove something working without replacement.

> old support in 17, nothing in 18, new support in 19: clean break.

I refuse to believe that it would stop anyone from creating a bug report.

**Comment by f00b4r0** [comment]
> Yes the current support for the board is ugly but it seems to work at least and I'm not going to remove something working without replacement.

What replacement are you talking about? New support code is new: it didn't exist before. It has no difference with a new device being added to OpenWRT.

Old support code is wrong code and there is no replacement for it as it requested hacking the device in possibly unrecoverable ways.

**Comment by blogic** [comment]
this boils down to the question do we tell those fine with replacing bootloaders that it is not ok or tell the other crowd that dont like doing so it not ok. either way one group will be pissed and threaten to throw the towel.

as for reaching consensus, i must say its your own fault for choosing to post such a fundamental question patch on a walled microsoft garden where hardly any of those people who will end up making such decisions look.

I understand both sides of the discussion and would suggest that you post the patch on the ML, where people will actually see it.

**Comment by f00b4r0** [comment]
@blogic ok will post, though [last time](https://lists.openwrt.org/pipermail/openwrt-devel/2017-November/009879.html) I asked the m-l for feedback I can't say I've been overwhelmed with answers 😛
Also didn't expect that prioritizing support for stock bootloader was a topic of debate.

**Pull request closed without merging**
