### PR TITLE
bcm47xx: switch to Linux 6.6

### PR DESCRIPTION
**Pull request by namiltd**
Switch to Linux kernel version 6.6 and drop configs, files and patches for Linux 6.1.

Requires testing on real hardware before approval.

### CODE REVIEW

**Comment by namiltd** [comment]
@kylehendrydev Can you check the operation of kernel 6.6 on Linksys EA6500 v1?

**Comment by namiltd** [comment]
No response, so all we have to switch and wait for error reports.

**Comment by kylehendrydev** [comment]
Tested 6.6 kernel image with a Linksys EA6500 v1 (bcm4706) and Netgear WNR3500L v1 NA (bcm4718). Both had the same crash at boot:

[    2.285668] init: Console is alive
[    2.289996] init: - watchdog -
[    2.295738] Got mcheck at 8001022c
[    2.299262] CPU: 0 PID: 196 Comm: init Not tainted 6.6.34 #0
[    2.305038] $ 0   : 00000000 00000001 fffd7000 00000001
[    2.310407] $ 4   : 00000004 00000003 00026e9f 77e86003
[    2.315771] $ 8   : 00000000 81c82000 00000002 00000008
[    2.321133] $12   : 00000002 0000308b 00000000 ffffff00
[    2.326497] $16   : 80802e28 7fffffeb 806e9280 7fffffeb
[    2.331860] $20   : 81c8eaf8 00000001 000007fc 00000000
[    2.337223] $24   : 00000000 ffffffff                  
[    2.342586] $28   : 81b2e000 81b2fd88 00000000 8000f614
[    2.347949] Hi    : 00000000
[    2.350882] Lo    : 80808081
[    2.353814] epc   : 8001022c __kmap_pgprot+0xdc/0x108
[    2.358984] ra    : 8000f614 __flush_anon_page+0xc4/0xec
[    2.364409] Status: 11208402	KERNEL EXL 
[    2.368424] Cause : 00800060 (ExcCode 18)
[    2.372511] PrId  : 00019740 (MIPS 74Kc)
[    2.376512] CPU: 0 PID: 196 Comm: init Not tainted 6.6.34 #0
[    2.382288] Stack : 00000000 00000001 000007fc 800622c8 00000000 00000004 00000000 00000000
[    2.390871]         81b2fc4c 807a0000 80780000 8064a254 8197e448 00000001 81b2fbf0 212d90d1
[    2.399449]         00000000 00000000 8064a254 81b2fb30 ffffefff 00000000 00000000 ffffffea
[    2.408027]         00000000 81b2fb3c 00000098 806f1a88 00000000 8064a254 806e9280 7fffffeb
[    2.416605]         81c8eaf8 00000001 000007fc 00000000 00000018 803238a4 89042010 00000060
[    2.425182]         ...
[    2.427693] Call Trace:
[    2.430185] [<80006fd0>] show_stack+0x28/0xf0
[    2.434675] [<8057d908>] dump_stack_lvl+0x38/0x60
[    2.439523] [<80008108>] do_mcheck+0x2c/0xa0
[    2.443899] [<80003d34>] handle_mcheck_int+0x3c/0x48
[    2.448975] 
[    2.450502] Index    : 3
[    2.453082] PageMask : 0
[    2.455661] EntryHi  : fffd6000
[    2.458857] EntryLo0 : 00026e9f
[    2.462055] EntryLo1 : 00026e9f
[    2.465251] Wired    : 4
[    2.467833] 
[    2.469359] Index:  0 pgmask=4kb va=fffd6000 asid=00
[    2.469359] 	[pa=0079f000 c=3 d=1 v=1 g=1] [pa=0079f000 c=3 d=1 v=1 g=1]
[    2.481262] Index:  1 pgmask=4kb va=fffd2000 asid=00
[    2.481262] 	[pa=01057000 c=3 d=1 v=1 g=1] [pa=01057000 c=3 d=1 v=1 g=1]
[    2.493159] Index:  2 pgmask=4kb va=fffd0000 asid=00
[    2.493159] 	[pa=008b4000 c=3 d=1 v=1 g=1] [pa=008b4000 c=3 d=1 v=1 g=1]
[    2.505057] Index:  3 pgmask=4kb va=fffd6000 asid=00
[    2.505057] 	[pa=009ba000 c=3 d=1 v=1 g=1] [pa=009ba000 c=3 d=1 v=1 g=1]
[    2.516957] Index: 24 pgmask=4kb va=80030000 asid=00
[    2.516957] 	[pa=00000000 c=0 d=0 v=0 g=0] [pa=00000000 c=0 d=0 v=0 g=0]
[    2.528863] Index: 39 pgmask=4kb va=8004e000 asid=00
[    2.528863] 	[pa=00000000 c=0 d=0 v=0 g=0] [pa=00000000 c=0 d=0 v=0 g=0]
[    2.540768] Index: 46 pgmask=4kb va=8005c000 asid=00
[    2.540768] 	[pa=00000000 c=0 d=0 v=0 g=0] [pa=00000000 c=0 d=0 v=0 g=0]
[    2.552667] 
[    2.554190] Code: 40843000  40850000  000000c0 <42000002> 000000c0  40875000  10600002  41606000  41606020 
[    2.564207] Kernel panic - not syncing: Caught Machine Check exception - caused by multiple matching entries in the TLB.
[    2.575261] Rebooting in 1 seconds..
[    3.577238] bcm47xx: Please stand by while rebooting the system...

**Comment by namiltd** [comment]
Similar problem: https://patchwork.kernel.org/project/linux-arm-kernel/patch/addfcb3-b5f4-976e-e050-a2508e589cfe@google.com/#25387898

**Comment by namiltd** [comment]
@kylehendrydev Please check if anything has changed with kernel 6.6.35.

**Comment by kylehendrydev** [comment]
Tried 6.6.35 and I'm getting the same crash

**Comment by namiltd** [comment]
Can you check the patch works: https://github.com/torvalds/linux/commit/d18419cd66835c29ac732624324b99b43f4cff1c

**Comment by namiltd** [comment]
Please attach the entire log.

**Comment by kylehendrydev** [comment]
[bcm4718-6.6.35-mcheck-crash.txt](https://github.com/user-attachments/files/15962893/bcm4718-6.6.35-mcheck-crash.txt)
[bcm4706-6.6.35-mcheck-crash.txt](https://github.com/user-attachments/files/15962894/bcm4706-6.6.35-mcheck-crash.txt)

Same crash with early_tlb_init() patch.

Full logs are attached.

This is what I've found out so far:
- This crash isn't happening on 6.1
- The code path that triggers this is slightly different on .35 (r4k_flush_cache_page instead of __flush_anon_page)
- I tried a 6.6 bmips build on a bcm63168 device and didn't get this crash, so it's specific to this CPU
- CONFIG_DEBUG_PAGEALLOC and CONFIG_DEBUG_VM_* do not generate any extra debugging output (the exception happens first?)
- The crash doesn't happen until init starts, so it could be a problem mapping memory for userspace

**Comment by namiltd** [comment]
@yuzhaogoogle @nathanchance Can you help?

**Comment by yuzhaogoogle** [comment]
FWIW, I don't think we ever fixed that crash on v6.6 or later kernel versions.

The kernel CI that tests MIPS/MIPS64 is QEMU-based, which doesn't support detecting conflicting TLBs.

I'll check with one of our experts in this area. Meanwhile, if you could bisection would help find the culprit?

Thanks.

**Comment by yuzhaogoogle** [comment]
Thanks, @namiltd 

I took a look at the call paths that caused the MCEs and didn't find any new clues.

I think we might get more help by reporting this to the MIPS kernel mailing list?

**Comment by namiltd** [comment]
It will be difficult because I have no previous experience with the kernel mailing list and I do not have a router with this system for testing.

**Comment by yuzhaogoogle** [comment]
I'll post this bug to the mailing list. Meanwhile, would it possible for you to bisect? Thanks.

**Comment by namiltd** [comment]
@kylehendrydev Can you check the oldest code with 6.6 kernel support (git reset --hard 65f34e99284f33be96518ac48de7d0beb972633e)?

**Comment by yuzhaogoogle** [comment]
I forwarded this bug to the MIPS mailing list [here](https://lore.kernel.org/linux-mips/CAOUHufac==iT7BD9_eWERNcpazV6KEaR3qupR9v5SrzC4GXYcg@mail.gmail.com/).

**Comment by kylehendrydev** [comment]
[bcm4718-6.6.32-mcheck-crash.txt](https://github.com/user-attachments/files/16038340/bcm4718-6.6.32-mcheck-crash.txt)

Tried a build from that commit, same crash

**Comment by FlyGoat** [comment]
Hi, can you try to remove call to `bcm47xx_prom_highmem_init()`?

This is the root cause, and it doesn't make any sense to me at all.

**Comment by FlyGoat** [comment]
Sorry I 

> Hi, can you try to remove call to `bcm47xx_prom_highmem_init()`?
> 
> This is the root cause, and it doesn't make any sense to me at all.

Sorry I made a wrong diagnosis, the actual problem is in our cache alias code, will try to make a patch.

**Comment by FlyGoat** [comment]
I'm unable to reproduce it on my 74K evaluation system, but I was able to source a EA6500 v1 locally.
@kylehendrydev, do you mind sharing your EA6500 v1 6.6 openwrt tree?

Thanks

**Comment by kylehendrydev** [comment]
@FlyGoat Try [this branch](https://github.com/kylehendrydev/openwrt/tree/bcm47xx-linksys-ea6500v1-6.6)

**Comment by FlyGoat** [comment]
Hi @kylehendrydev,

I found this issue is caused by OpenWRT's patch.

Please drop following patches:

```
160-kmap_coherent.patch
300-fork_cacheflush.patch
310-no_highpage.patch
```

I believe they are all related to some ancient cache aliasing bugs that have been fixed in upstream, and no longer relevant for us.

**Comment by namiltd** [comment]
@kylehendrydev Try new version

**Comment by kylehendrydev** [comment]
@namiltd Tested new branch on Netgear WNR3500L v1 NA: LEDs, buttons, ethernet and wifi works. 

On Linksys EA6500 v1 LEDs, buttons, and ethernet work. Couldn't get wifi AP to work, but neither radio is fully supported and didn't work on 5.15.

**Comment by namiltd** [comment]
@kylehendrydev  Can you attach logs from EA6500 v1? I wonder why WiFi doesn't work on this router. Maybe it can be run for kernel 6.6.

**Comment by namiltd** [comment]
I found out: broadcom wifi

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
