### PR TITLE
gettext-full: fix compilation under macOS

### PR DESCRIPTION
**Pull request by neheb**
static linking under macOS doesn't work correctly for some reason.
Switch to shared linking for the host build.

Also start using libiconv/host for the host build. shared linking
seems to fail without libiconv.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

ping @httpstorm Try testing with gmake package/rpcsvc-proto/host

### CODE REVIEW

**Comment by neheb** [comment]
Hmm this is failing under linux. Setting to draft.

**Comment by httpstorm** [comment]
@neheb Hello Rosen!
My last build on macOS from an empty directory is based on ed7769aa405fe246b89c9c97b7fb552dfb0b4995, which is 2 commits before this patch. Everything compiled correctly. Are these changes needed and what errors do they fix?

**Comment by httpstorm** [comment]
@neheb Hi Rosen!
The patch doesn't seem to make a difference on macOS. The build fails either way with the same missing symbols. Luckily my last build from an empty directory is just two commits behind your patch and was successful, because `package/rpcsvc-proto` was not compiled during my build. `/usr/local/bin/make` is GNU Make 4.3, Built for x86_64-apple-darwin20.1.0.

Before patch
```
Undefined symbols for architecture x86_64:
  "_libintl_gettext", referenced from:
      _main in rpc_main.o
      _usage in rpc_main.o
      _checkfiles in rpc_main.o
      _c_output in rpc_main.o
      _h_output in rpc_main.o
      _l_output in rpc_main.o
      _s_output in rpc_main.o
      ...
  "_libintl_setlocale", referenced from:
      _main in rpc_main.o
  "_libintl_textdomain", referenced from:
      _main in rpc_main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

After patch
```
Undefined symbols for architecture x86_64:
  "_libintl_gettext", referenced from:
      _main in rpc_main.o
      _usage in rpc_main.o
      _checkfiles in rpc_main.o
      _c_output in rpc_main.o
      _h_output in rpc_main.o
      _l_output in rpc_main.o
      _s_output in rpc_main.o
      ...
  "_libintl_setlocale", referenced from:
      _main in rpc_main.o
  "_libintl_textdomain", referenced from:
      _main in rpc_main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Build log: https://pastebin.com/JnwTeuss

**Comment by neheb** [comment]
@httpstorm yeah so my change to gettext-full/host replaces libintl.a with .so. that log shows libintl.a to be still present.

**Comment by neheb** [comment]
I maybe figured out why static linking is totally broken. libiconv is a stub, not an actual libiconv. It should not be used for host packages.

**Comment by httpstorm** [comment]
@rasa Ross, can you please have a look:
In short `samba4` depends on `rpcsvc-proto/host`, which depends on `gettext-full` `libiconv/host`. `rpcsvc-proto/host` fails to build on macOS. On Linux it builds fine. @neheb found that _libiconv is a stub_.

**Comment by neheb** [comment]
I'll just mark this as ready.

Currently, this PR fixes several packages such that they compile on macOS. Others are still broken. Nevertheless, this is already an improvement. No change on Linux. No idea about FreeBSD (I don't use it).

**Comment by httpstorm** [comment]
@neheb Hi Rosen! I'm happy to read you made some progress! 😎 I'll give it a test build right now for target x64 on macOS with samba4 selected. Let know know about any additional items or tests you want me to run.
About FreeBSD, I do happen to have a new VM which I use to build my web server `httpstorm.com` and some other tools. I'm not sure if it is set for OpenWRT, but I can at least give it a try.

**Comment by httpstorm** [comment]
@neheb Can you please rebase your patch on the current master? I think the current base is not buildable.

**Comment by neheb** [comment]
Done.

**Comment by httpstorm** [comment]
@neheb FreeBSD required some packages to be installed, then a patch to `scripts/mkhash.c`. With that I was able to start the build, but `tools/dosfstools` failed due to missing type. Further research might take long since we don't know how make packages are broken, and I'm not sure it is worth investing time now. The only thing that we can do is a pull request for `scripts/mkhash.c`.
```
108 - #endif
134 + #endif
```
I'm still building on macOS…

**Comment by neheb** [comment]
I assume close to no one builds on FreeBSD honestly. Although some patches reference FreeBSD...

**Comment by httpstorm** [comment]
macOS:
`make package/rpcsvc-proto/host/compile V=sc`: success.

Meanwhile `samba4` still fails. This line seems suspicious `-n Linux`.
```
make package/feeds/packages/samba4/compile V=sc
…
Setting top to                           : /Volumes/test2/5/openwrt/build_dir/target-x86_64_musl/samba-4.14.7 
Setting out to                           : /Volumes/test2/5/openwrt/build_dir/target-x86_64_musl/samba-4.14.7/bin 
Checking for 'clang' (C compiler)        : not found 
Checking for 'gcc' (C compiler)          : x86_64-openwrt-linux-musl-gcc 
Checking for program 'git'               : /Volumes/test2/5/openwrt/staging_dir/host/bin/git 
Checking for c flags '-MMD'              : yes 
Checking for program 'gdb'               : not found 
Checking for header sys/utsname.h        : yes 
Checking uname sysname type              : -n Linux
 
Checking uname machine type              : not found 
Checking uname release type              : not found 
Checking uname version type              : not found 
Checking for header stdio.h              : no 
Checking simple C program                : not found 
The configuration failed
(complete log in /Volumes/test2/5/openwrt/build_dir/target-x86_64_musl/samba-4.14.7/bin/config.log)
```
make log: https://pastebin.com/aT32vUNQ
config.log: https://pastebin.com/zwkB3im4

**Comment by neheb** [comment]
Ah yes now I remember. I think there's something wrong with the build script. It's not related to this PR. That uname is weird, yes.

**Comment by httpstorm** [comment]
@neheb I will try building the rest of the image without `samba4`, to make sure we don't break anything. Rosen, can you please join me on screen sharing and help with `samba4`?

**Review by httpstorm — APPROVED** [review]
Corrects the build errors in package/rpcsvc-proto/host. Tested on macOS 11.6.1.

**Comment by neheb** [comment]
ping @hauke

**Comment by regae** [comment]
i am able to pass samba4 error, it is caused by
buildtools/wafsamba/wscript
`args = ['/bin/sh', '-c', "echo -n '%s'; exit %d" % (retstring, retcode)]`
either use bash or /bin/echo or doubeEscape c "\\c"

is there a better solution?

**Comment by neheb** [comment]
That looks like a good solution.

**Comment by regae** [comment]
new problem rises, configure can not find popt.h
staging_dir/target*/usr/include is not defined

**Comment by neheb** [comment]
@svlobanov you might find this interesting.

**Comment by svlobanov** [comment]
@neheb thank you for mentioning me

My variant to fix package/rpcsvc-proto issue: https://github.com/openwrt/packages/pull/17430

**Comment by httpstorm** [comment]
@neheb @svlobanov  I ran a test build for target x64 on macOS 11.6.2 x64, and I can confirm that Sergey's patch resolves the build errors. Thank you!

`make package/rpcsvc-proto/host/{clean,compile} V=sc`

**Comment by neheb** [comment]
Going to close this. While this fixes certain things on macOS, it's not enough to fix glib2. I also have no real macOS hardware or any desire to use VMs. Maybe @svlobanov can pick this up if needed at some point.

**Pull request closed without merging**
