### PR TITLE
Add support for BananaPi BPi-R2, second take

### PR DESCRIPTION
**Pull request by abbradar**
This is a retake on https://github.com/openwrt/openwrt/pull/1135 without WiFi support, which is too messy to upstream.

Several unresolved concerns from @blogic remain which I'm not sure how to handle:
* https://github.com/openwrt/openwrt/pull/1135#discussion_r207863955
* https://github.com/openwrt/openwrt/pull/1135#pullrequestreview-143558706
* https://github.com/openwrt/openwrt/pull/1135#pullrequestreview-143558950

Another problem is that built SD image fails to create jffs2 partition when booted citing "no jffs2 nodes". One needs to run `jffs2reset` to fix that; can I do that to the image itself instead somehow?

### CODE REVIEW

**Comment by abbradar** [comment]
I cleaned up these patches a little more. What else I tried for fun:

1. Using upstream u-boot 2017.07 - requires swig, I avoided changing common u-boot package for now and just continued using vendor package;
2. Backporting upstream kernel patches for .dts instead of applying my own ones - didn't work, the kernel doesn't boot at all with UART radio silence. It seems to me that's because we also need to backport non-.dts changes; I have no idea what else to port and this would require too much patches overall. For now let's stick to my patches instead which are minimum amount of changes required for board to boot.

We use the same partitioning method as `sunxi` now (hardcoded offsets) but possible future work is to use some kind of partition table instead. Image building script is also inspired by `sunxi`.

Thanks to all the wonderful people from IRC for help!

**Comment by frank-w** [comment]
Maybe should drop 0027-fix-dql-support

it's reported by lexa2 as bring instability

http://forum.banana-pi.org/t/bpi-r2-slow-ethernet-speed/4031/69

**Comment by lexa2** [comment]
Yep, `0027-net-next-mediatek-fix-DQL-support.patch` causes huge network instabilities under any substantial load on any of three R2 boards I've got on hand and tried testing on. Thus for my situation openwrt image with this patch in kernel was essentially useless. Thus I dropped this patch in my variant of BPi-R2 specific OpenWRT fork.

**Comment by abbradar** [comment]
Let's leave this for another PR then, as this would affect more than just R2. Still, now I know what's the cause of these instabilities!

**Comment by adrianschmutzler** [comment]
What's the status here? When I read the initial messages, this looks like RFC/WIP to me?

**Comment by abbradar** [comment]
@adrianschmutzler Yeah, I'm waiting for answers on https://github.com/openwrt/openwrt/pull/1135#discussion_r207863955 and https://github.com/openwrt/openwrt/pull/1135#pullrequestreview-143558706 . For https://github.com/openwrt/openwrt/pull/1135#pullrequestreview-143558950 I want to try using upstream .dts again and determine what's wrong but that's a lot of work so first I'd like some general comments on this PR.

**Comment by adrianschmutzler** [comment]
I've added the RFC label. I might be a good idea to mark your PR (! not the commit) correspondingly, it will make life easier for reviewers:
Prefix with target, e.g. "mediatek:" in your case.
When RFC/WIP/RFT etc., prefix with [RFC] or similar.
You can change your PR title at any time, and remove the RFC when you think you are ready.

**Comment by cioby23** [comment]
@abbradar do you plan to update the pull request to be merged into openwrt trunk ?

**Comment by adrianschmutzler** [comment]
Hi, since this adding device support is effectively a feature, and none of the committer seems to be interested in reviewing it (or even in commenting on your RFC), I will close it now (i.e. "Won't implement").

I'm sorry, but better crush your remaining hopes now than waiting another year where supposedly nothing different will happen.

**Pull request closed without merging**
