### PR TITLE
ath79: allow symmetrical ring buffer

### PR DESCRIPTION
**Pull request by SheepWillPrevail**
This allows the user to specify a larger tx ring buffer size via ethtool. Having symmetrical ring buffer sizes increases throughput on high bandwidth (1 gbps tested) network connections.

Signed-off-by: Robert Meijer <robert.s.meijer@gmail.com>

### CODE REVIEW

**Comment by SheepWillPrevail** [comment]
A bit of background; in the past gains could be had with ADSL connections if one prioritzed TCP ACK over regular traffic, so the downstream could be saturated. I did this in the past with OpenBSD pf.

When I connected my WDR-3600 to my gigabit fibre I noticed the speed of the downstream to be somewhat unstable.

Applying this patch and using 'ethtool -G eth0 tx 256' fixes this.

I have been running with a default tx ring size of 256 for longer than a year now without any issues. The memory use of the kernel is increased by 128*1540 bytes after this configuration of course.

A long time ago I did some digging through the mailing list and they mentioned a larger size, like this, wouldn't be needed because of the generally smaller upstream.

Maybe the 256 for tx ring size could be the default, but I thought that would be too much for this patch. I could amend it of course.

**Comment by xback** [comment]
Iirc, there was an actual reason to keep this tx size small.
This driver is mainly used on single core socs with only a small L1 cache.
Keeping the size smaller improved cache hotness.

I fully agree that it could improve txrate during peek rate, but I think the total performance of the full system will be lower by putting more pressure on RAM transactions as a result of reduced caching effectiveness.

Ill check the driver on Monday to see if it actually requires a pow2 size.
Maybe other values besides simply doubling it could be better.

**Comment by CodeFetch** [comment]
Changing the MAX ring size is okay as the default is untouched. There are scenarios where increasing the ring buffer size makes sense. Routers that forward traffic profit from symmetrical ring buffers. Furthermore the issue he described is clearly bufferbloat and if it is solved by increasing the ring buffer size, then it was likely too small. And I'm pretty sure it was too small for gigabit.

```
In an attempt to increase our cache warmth, we are decreasing NAPI.
This increases the warmth of the reused SKBs.
```

This is not about the L1 cache, but about SKB memory handling. This is an attempt to force NAPI to poll or be forcefully interrupted by a full ring or something.

So I don't see any problem in merging this if it only gives the user access to an additional configuration option...

**Comment by CodeFetch** [comment]
From what I remember the NAPI weight defines when to start switching from interrupt-driven to polled mode. When in polled mode the ring buffers need to be able to keep the packet in the ring or we will see excessive packet loss. Actually I think all these values need to be rethinked. They should be different for different devices... Another thing is that the NAPI polling behavior depends on the HZ value. All these values need to fit well for a device to perform best. Thus I guess making it configurable is a good idea.

**Comment by adschm** [comment]
While I cannot contribute anything useful regarding the content, note that the commit message needs to be wrapped properly.

**Review by CodeFetch — COMMENTED** [review]
Please wrap commit message as adschm suggested!

**Comment by CodeFetch** [comment]
@SheepWillPrevail Ping

**Comment by SheepWillPrevail** [comment]
> @SheepWillPrevail Ping

I would like to, but due to circumstance I don't have access to a computer to make this happen.

So it's the wrapping of the commit message?

**Comment by SheepWillPrevail** [comment]
> From what I remember the NAPI weight defines when to start switching from interrupt-driven to polled mode. When in polled mode the ring buffers need to be able to keep the packet in the ring or we will see excessive packet loss. Actually I think all these values need to be rethinked. They should be different for different devices... Another thing is that the NAPI polling behavior depends on the HZ value. All these values need to fit well for a device to perform best. Thus I guess making it configurable is a good idea.

It is, ethtool does this.

**Pull request merged**
