### PR TITLE
[RFC] ath79: disable unused switches on tiny targets

### PR DESCRIPTION
**Pull request by lucize**
get more space by moving unused switches from tiny target
searched for used switches in ar71xx match files

we could also disable flow offloading because most of targets are able to do 100mb/s traffic
with this I could squash wireguard and luci into the image (ipv6 disabled)

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by mkresin** [comment]
Please do it the other way round. Drop them from target/linux/ath79/config-4.14 and enable them in the subtarget target configs where required.

After checking board.d/02_network, I suspect the following boards are using realtek switches:

- tplink,tl-wr1043nd-v2
- tplink,tl-wr1043nd-v3
- tplink,tl-wr2543-v1
- netgear,wndr3800

How much does the tiny kernel/images shrink if the realtek drivers aren't included?

**Comment by lucize** [comment]
I needed at least 16k for the image to be build and with this I could make it work, I'll compare them, maybe if we would have something like this in CONFIG_AR8216_PHY to disable the gigabit support if the target is tiny. I don't expect gigabit switches on 4MB flash, but I  could be proved wrong

**Comment by diizzyy** [comment]
...not sure if we need IDE, KVM and USB_SUPPORT?

**Comment by lucize** [comment]
on 4.14.52

```
ls -la
-rw-r--r--  1 build build  1379809 iun 28 01:26 tl-wr841-v9-kernel.bin

```
without

`-rw-r--r--  1 build build  1368215 iun 28 01:33 tl-wr841-v9-kernel.bin`

usb we need, at least for tl-mr3020

**Comment by diizzyy** [comment]
@lucize 
Sorry, I was under the impression that it used https://github.com/openwrt/openwrt/blob/master/target/linux/ath79/config-4.14 as base.

**Comment by lucize** [comment]
yes it is used, but I didn't see any `o` being built, I'll disable them and see the diff

**Comment by juppin** [comment]
I didn´t saw that you disabled flow offloading for the tiny target, but i´m against this!

For example i have some wr841 as cheap vpn clients running for home office and i always use nat here...
With flow offloading i have more cpu resources for en-/decryption...

**Comment by diizzyy** [comment]
You have a point however I think you'll see little to no difference in actual performance since the SoCs are quite slow to begin with. I know it sounds backwards but I think you get the idea.

**Comment by bobafetthotmail** [comment]
> With flow offloading i have more cpu resources for en-/decryption...

I think this should be tested to see if it really matters before deciding if it can be dropped or not.

**Comment by lucize** [comment]
@juppin I disabled it in my build, maybe now it fits with LUCI, a wireguard test showed 35mb/s on non pppoe vpn, I'll try a test with offloading, it was on my todo

**Comment by juppin** [comment]
I will do some test with flow offloading and openvpn on my wr841v8 in the next time...

What would also be a good option for the tiny target:
```
# CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE is not set
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
```

The size optimization was the default on 4.9, but on 4.14 the default is performance...
This will save probably about 200k or more.

**Comment by diizzyy** [comment]
@juppin 
I played around with OpenVPN a few months ago and I can with ~95% confidence say that it'll be very little difference if any at all. http://projects.pyret.net/dump/lede/openvpn-benchmarks.txt
It's not with offloading but the userland design kills performance so you're not really missing out on anything. The above is with compiler and library settings but as you can see it barely pushes 15mbit, even using a beefer SoC (MT7621) makes little difference.

**Comment by juppin** [comment]
> a few months ago

With flow offload or are you using sfe for your tests?

Probably it´s a placebo, but i noticed a performance gain on samba file transfer over a openvpn connection with aes256/sha256... Probably with only aes128/sha1 there will be no real difference.

**Comment by lucize** [comment]
so using wireguard vpn with flow offload I have max 53mb upload 35mb download and without offload I have 47mb upload and  35mb download, I think it should be the same for up and down, but don't know why they are not in sync
previous test was done by wifi and I didn't realize it

**Comment by lucize** [comment]
I've also added #1125

**Comment by juppin** [comment]
What about the kernel optimization for size instead of the default for performance that i mentioned above?

**Comment by lucize** [comment]
the latest + #1125 
`-rw-r--r-- 1 build build 1359579 iun 28 15:13 tl-wr841-v9-kernel.bin
`
with added

```
# CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE is not set
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
```

`-rw-r--r--  1 build build  1276911 iun 28 15:18 tl-wr841-v9-kernel.bin`

**Comment by lucize** [comment]
wireguard slowed down by ~1-2 megabit so I think is safe to add this too

**Comment by mkresin** [comment]
After all the offtopic, I had a look at the PR again.

As of know, the AT803X_PHY doesn't need to be added to the NAND subtarget. The only supported board has the QCA9531, which doesn't support external xMII.

The ar2740 and ar9331 used for the tiny boards doesn't support external xMII. either.

I havn't checked the generic subtarget. Might be that some of the phy drivers are not (yet) required.

**Comment by lucize** [comment]
I've just checked the ar71xx match files and config-default. there are phy drivers that are not used yet, should I remove them until someone has need of them ?

**Comment by mkresin** [comment]
Checking mach files doesn't work. Ethernet  phy drivers are loaded based on the phy id reported on the mdio bus. There is no need to specific if an ethernet phy and which ethernet phy is used. All that is needed is a  ethernet phy driver with a matching phy id defined.

Please add my explanation about SoCs not supporting external xMII to the commit message! It will show why it is safe to do what you have done so far.

> should I remove them until someone has need of them

For the NAND config yes. For the generic kernel config it depends on whether you can say for sure that no board has such an ethernet phy (either by checking if the SoC supports external xMII, the bootlog or pictures of the PCB).

**Comment by lucize** [comment]
>  ar2740 

typo ?

@mkresin verified the dmesg on wiki and images found on google and wikidevi and for the existing targets only realtek and AT803X seems to be preset

**Comment by mkresin** [comment]
> typo ?

Obviously it is. ar7240 makes more sense.

**Comment by mkresin** [comment]
> verified the dmesg on wiki and images found on google and wikidevi and for the existing targets only realtek and AT803X seems to be preset

Add it to the commit message. Be careful with wikidevi, ethernet phys are usually not mentioned there.

**Comment by lucize** [comment]
> careful with wikidevi, ethernet phys are usually not mentioned there.

I was referring to pictures

**Comment by lucize** [comment]
@mkresin updated

**Comment by mkresin** [comment]
I've enabled all ethernet phy and switch drivers for the generic target again. I felt it was to risky to disable them for the generic subtarget as well. On top, there isn't much (or any?) size pressure for the generic subtarget.

**Comment by lucize** [comment]
yes, it's perfectly fine !

**Pull request closed without merging**
