### PR TITLE
 ramips: fix GELAN port in D-Link DWR-118-A2

### PR DESCRIPTION
**Pull request by CHKDSK88**
This patch fix and enable GELAN port in D-LINK DWR-118-A2.

This changes allow to use PHY with mdio address different than
port number.

Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>

### CODE REVIEW

**Comment by CHKDSK88** [comment]
@mkresin 

Could You look at this PR?

**Comment by CHKDSK88** [comment]
Bump.

I rebased to current master.

**Comment by dangowrt** [comment]
@mkresin can we merge this?

**Comment by trtk** [comment]
Hi, @mkresin , @dangowrt, @CHKDSK88   I can confirm to this patch fix the only one gigabit port on DWR118 A2 device. Please merge it go the base code.

**Comment by CHKDSK88** [comment]
19.07 was branched. Can we merge it now?

**Comment by ynezz** [comment]
> 19.07 was branched. Can we merge it now?

I've just merged it into my staging tree, will test it on my mt7620 device and if it's ok, then I'm going to push it.

**Comment by ynezz** [comment]
@trtk can I have your `Tested-by: Your Real Name <your@email.com>` please?

**Comment by ynezz** [comment]
@trtk For details please see https://www.kernel.org/doc/html/latest/process/submitting-patches.html#using-reported-by-tested-by-reviewed-by-suggested-by-and-fixes

**Comment by trtk** [comment]
@ynezz  sure, Tested-by: Richard Toth <trtk1992@gmail.com>

**Comment by ynezz** [comment]
Pushed to master, thanks!

**Pull request closed without merging**
