### PR TITLE
add python 3.12 support

### PR DESCRIPTION
**Pull request by neheb**
Repost of https://github.com/openwrt/openwrt/pull/16190

I don't remember the details, but that PR didn't work quite right on Ubuntu 18.04.

### CODE REVIEW

**Comment by robimarko** [comment]
Why a repost when the linked PR is basically identical?

**Comment by neheb** [comment]
Hrm looks like that’s true. This one passes CI

**Comment by robimarko** [comment]
Well, only format tests fail there which is weird since the commits match

**Comment by neheb** [comment]
Nope. The first commit is reworded to pass CI.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
