### PR TITLE
Update mktplinkfw2.c

### PR DESCRIPTION
**Pull request by psyborg55**
update tp-link v2 header addresses and informations

### CODE REVIEW

**Comment by mkresin** [comment]
Not sure what you are trying to do here but it looks completely wrong.

The changed vendor string doesn't make any sense at all to me. Furthermore, the TP-Link v2 header uses v1.0 as version number. Version number v2.0 is used for the v3 header. Your change would break working images.

Finally, the changed offsets in the header comments are wrong. I mean, fw_version starts at 0x04 and has a length of decimal 48 which is 0x30 in hex. Therefore, hw_id has to be at 0x34.

**Comment by psyborg55** [comment]
i got device here that is using v2.0 as a version number but the header contents match v1 addresses for example hwid starts at 0x40. found another device with the same firmware structure: it is tp-link wdr3320 v2. you can check original fw image.

**Comment by mkresin** [comment]
I guess everything you need was added to mktplinkfw.c with https://github.com/openwrt/openwrt/commit/b15a58e61ef621bf602194d53d5035161828de52 more than a year ago.

**Comment by psyborg55** [comment]
then i should not make any modifications except indicate v2 header in device profile. but the generated image was not accepted by tplink webupdate tool.

and i found similar complaints here: https://forum.openwrt.org/viewtopic.php?id=45894

**Comment by mkresin** [comment]
According to you changes, you need to use

-N <vendor>     set image vendor to <vendor>
-m <version>    set header version to <version>

My point was that you should not blindly change files and break existing images this way.

**Comment by psyborg55** [comment]
i don't think it will make sense since the router did not accept even original fw with stripped down u-boot. i've not tried yet to flash full image.

why not separate v2 header creation tool from v1 completely? this way it creates confusion only...

**Comment by mkresin** [comment]
> i don't think it will make sense since the router did not accept even original fw with stripped down u-boot. i've not tried yet to flash full image.
> 
> why not separate v2 header creation tool from v1 completely? this way it creates confusion only...
> 
Because we have two different v2 header. One that is close to the v1 one and a complete new one.

I've still no idea what you are really trying to do, how the header you are trying to create should look like and if you ever was able to create an image that is accepted by the tp-link webinterface.

What you are doing looks wierd. I mean you are changing field sizes in the comments without changing the code. You add a sig field to the header but no function to fill these field.

And finally, your changes to the version and vendor name break the header of images already using mktplinkfw2.

**Comment by psyborg55** [comment]
does the v2 header which is close to v1 has any signatures? can you tell me which devices use that kind of header so i can check?

field sizes in comment correspond to v3 header, v2 header has field sizes identical to v1 except for sign key

v1 image has kernel_ofs 20000 in both headers. v2 has 200 in first header and 20000 in second.

<a href='http://postimg.org/image/sxf7ce78r/' target='_blank'>Screenshot</a><br/><br/>
<a href='http://postimg.org/image/by68x4w17/' target='_blank'>Screenshot-1</a><br/><br/>

**Comment by mkresin** [comment]
Now I got what you are trying to do. You want to create a v3 header.

Please write a mktplinkfw3.c for this or alter mktplinkfw2.c to create a v3 header (only) if some optional parameter is present.

But it wont work anyway, since the private RSA key from tp-link is required to create a signature which will be accepted by the stock firmware update routine. And this private key is still unknown.

**Comment by psyborg55** [comment]
no i dont.

**Pull request closed without merging**
