### PR TITLE
ar71xx: remove target

### PR DESCRIPTION
**Pull request by aparcar**
The target is replaced by the device tree based target ath79.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
Anything missing to remove?

**Comment by dangowrt** [comment]
Now that we got the openwrt-19.07 branch I think we are fine. The default target has already been changed to ath79 afaik.

**Comment by 981213** [comment]
Ther raw nand driver isn't ported to ath79 yet. I think we can still leave this target there for a while until everything are ported to ath79..

**Comment by hqvv** [comment]
Please kindly help to port QIHOO C301 and Netgear R6100 from ar71xx to ath79 before remove the target.
Thanks

**Comment by mrkiko** [comment]
Hello guys!
Am I missing something - or plenty of hardware will be obsoleted right away when removing this target, like e.g.: TP-LINK MR6400 ?
Or the TP-LINK RE450 V1.
Yeah, I am mentioni hardware I have, and of course I am not telling someoen should port this hardware if they don't want to, but I wonder how many of the 227 of the
target/linux/ar71xx/files/arch/mips/ath79/mach*.c files have been ported. This is an honest question - maybe most of them...
I saw many ports after all - and I thanks all of you working on OpenWRt in general.
but... isn't too soon?

thanks to all of you guys,
Enrico

**Comment by diizzyy** [comment]
This is a bad idea since far from all platforms have migrated and there are still issues with migrated ones.

**Comment by rogerpueyo** [comment]
> The target is replaced by the device tree based target ath79.
Only partially; there are a number of devices (e.g., all the Mikrotik subtarget) which have not been ported yet.

We could, anyway, define a number of requirements to be achieved before deleting ar71xx. For instance, the NAND driver, having a certain percentage of ar71xx devices ported into ath79, etc.

**Comment by diizzyy** [comment]
ar71xx is probably the one most "popular" (used) target so I don't see the need to rush especially since 4.14 isn't going to be removed for quite some time.

**Comment by lynxis** [comment]
@aparcar can you please state why you want to remove. And why this might be not a problem for it. Please also mark this PR as RFC

**Comment by jeffsf** [comment]
> Ther raw nand driver isn't ported to ath79 yet

Are you talking about `rawnand` or `spinand`?

If SPI NAND, I have already done the work to _enable its use with Linux 4.19 on a `ath79/nand` target,_ developed, tested, and had accepted upstream driver for the current-generation GigaDevice SPI NAND, offered backport patches to OpenWrt for the SPI NAND, and have _fully working GL.iNet GL-AR300M and GL-AR750S code ready for submission._ (Waiting on confirmation on a new driver for some older flash used in early production GL-AR300M for upstream submission). This was available earlier on Patchwork for the GL-AR750S alone, but I since have unified and simplified support.

I'm not sure why _developers_ are so up in arms about this. How hard is `git checkout openwrt-19.06` to get back to the old sources? End users will have release 19.06. This shouldn't be a surprise. If your favorite device isn't on ath79 already, after all the time that this has been coming, _fix it._

All that keeping ar71xx around will do, in my opinion, is delay the _next_ release as everyone scrambles with

> Nooooo, you can't release! My ImportPOS 3600 isn't on ath79 yet, I'll port it now, just wait for me.

**Comment by dangowrt** [comment]
I argee with @jeffsf and think there has been a misunderstanding: the upcoming 19.06 release *will* include ar71xx. *Future* releases will not. And, of course, just like for any deprecated targets, we will move the code into the [targets feed](https://github.com/openwrt/targets), so as long as the kernel version is still supported in the buildroot, users can still build that target.
Removing the ar71xx target from the buildroot will make it crystal clear that there are no resources allocated into keeping it maintained nor new patches are accepted -- and focus all our efforts into ath79 instead.
Of course, this will be painful for some users. However, this pain will make them port-over their boards to ath79 and add and/or fix whatever needed to do so.

**Comment by psyborg55** [comment]
denied

**Comment by pepe2k** [comment]
@dangowrt 

> I argee with @jeffsf and think there has been a misunderstanding: the upcoming 19.06 release [...]

19.0**7** :)

**Comment by adrianschmutzler** [comment]
Just thought about a situation where removing ar71xx would be helpful:
When we introduced TP-Link CPE210 v2 to ath79, I previously had to convert the ar71xx device to dynamic partitioning as the tplink-safeloader.c is shared between both targets. So just adding ath79 with dynamic partitioning would have broken the device on ar71xx.
While this would be also possible for another device in source-only mode, I would hesitate to do that as it taints the existing (working) device config.
Thus, I would prefer removing ar71xx target if it not actually required anymore.

**Comment by ynezz** [comment]
We will keep the ar71xx in the tree, but won't build images anymore, it will be [source only target](https://git.openwrt.org/?p=openwrt/staging/ynezz.git;a=commit;h=11d3da6afd06f27de691ee92c92032b4738ea4f9). Removing it would simply make it harder for downstream projects like Gluon for example.

**Comment by ldir-EDB0** [comment]
By not dropping the target we're just kicking the pain point can of conversion to ath79 further down the road.  Stuff tends get get fixed more quickly when it's broke, without it breaking I question what incentive is there for device conversion to ath79.  I switched my Archer C7 to ath79 as soon as it became available on that target, unfortunately I was unable to help the actual conversion process but I was able to help test.

I'd argue that pain now reduces the pain later.

**Pull request closed without merging**
