### PR TITLE
zynq: switch to Linux 6.6

### PR DESCRIPTION
**Pull request by namiltd**
Switch to Linux kernel version 6.6 and drop config for Linux 6.1.

### CODE REVIEW

**Comment by namiltd** [comment]
Ping @PolynomialDivision

@luaraneda Can you runtest?

**Comment by luaraneda** [comment]
> Ping @PolynomialDivision
> 
> @luaraneda Can you runtest?

Sure, give me a couple of days to compile and find a device

**Comment by luaraneda** [comment]
Run tested on Zybo Z7-20.

You can add:
`Tested-by: Luis Araneda <luaraneda@gmail.com> # Zybo Z7-20`

**Comment by PolynomialDivision** [comment]
this is not merged?

**Comment by namiltd** [comment]
@PolynomialDivision I closed it due to confusion, I have already reopened it.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
