### PR TITLE
Netgear EX6150: Mark the toggle switch as EV_SW

### PR DESCRIPTION
**Pull request by kroeckx**
Fixes: FS#3590

I would like to fix this in 19.07 too, should I create an additional pull request for that?

Tested on 19.07

### CODE REVIEW

**Comment by adschm** [comment]
Hi, while the content seems reasonable, please fix the formal errors (commit title, missing Signed-off-by ...)
https://openwrt.org/submitting-patches

No need to backport, I would cherry-pick it myself after merged to master if it appears suitable (which appears to be the case here).

**Comment by kroeckx** [comment]
The commit has a sign off.

I'm not sure what I should do with the commit title, I couldn't find
anything related to it in the documentation, but I might just not be
looking at the right place.

**Comment by kroeckx** [comment]
I guess I should look at the URL ...

**Comment by adschm** [comment]
Indeed, apparently it has (sorry if I got this wrong in the first place).
Still, this needs a proper title and commit message.

**Comment by kroeckx** [comment]
I've forced pushed a new commit

**Comment by adschm** [comment]
Merged for master and 19.07, thanks!

**Pull request closed without merging**
