### PR TITLE
CI: remove various tools from macOS CI

### PR DESCRIPTION
**Pull request by neheb**
This was needed when tools/zstd was not in the tree. Now that it is, remove it.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

ping @aparcar @Ansuel

### CODE REVIEW

**Comment by neheb** [comment]
readline might not be needed as well. For example, in the packages feed, softethervpn(5) has readline/host as a dependency as Debian CI does not provide it.

**Comment by neheb** [comment]
Seems these others aren't needed either.

**Comment by aparcar** [comment]
Fine with me, I think some of them are required for package builds right? If not we should remove them from the wiki, too

**Comment by neheb** [comment]
I don’t think so. Yes they should be removed from wiki.

**Comment by Ansuel** [comment]
@neheb can i merge this? did we update the wiki?

**Review by hauke — APPROVED** [review]

**Review by aparcar — APPROVED** [review]

**Comment by neheb** [comment]
Looking more at the macOS runner image, a lot of the packages are already preinstalled:

```
2023-01-06T20:18:39.0647600Z [33mWarning:[0m autoconf 2.71 is already installed and up-to-date.
2023-01-06T20:18:39.0648160Z To reinstall 2.71, run:
2023-01-06T20:18:39.0648460Z   brew reinstall autoconf
2023-01-06T20:18:39.0768130Z [33mWarning:[0m gettext 0.21.1 is already installed and up-to-date.
2023-01-06T20:18:39.0768510Z To reinstall 0.21.1, run:
2023-01-06T20:18:39.0769000Z   brew reinstall gettext
2023-01-06T20:18:39.0877140Z [33mWarning:[0m gmp 6.2.1_1 is already installed and up-to-date.
2023-01-06T20:18:39.0878510Z To reinstall 6.2.1_1, run:
2023-01-06T20:18:39.0878950Z   brew reinstall gmp
2023-01-06T20:18:39.0921670Z [33mWarning:[0m gnu-getopt 2.38.1 is already installed and up-to-date.
2023-01-06T20:18:39.0922000Z To reinstall 2.38.1, run:
2023-01-06T20:18:39.0922530Z   brew reinstall gnu-getopt
2023-01-06T20:18:39.0977740Z [33mWarning:[0m gnu-tar 1.34_1 is already installed and up-to-date.
2023-01-06T20:18:39.0978090Z To reinstall 1.34_1, run:
2023-01-06T20:18:39.0978500Z   brew reinstall gnu-tar
2023-01-06T20:18:39.1034850Z [33mWarning:[0m libidn2 2.3.4 is already installed and up-to-date.
2023-01-06T20:18:39.1035700Z To reinstall 2.3.4, run:
2023-01-06T20:18:39.1037060Z   brew reinstall libidn2
2023-01-06T20:18:39.1130610Z [33mWarning:[0m libunistring 1.0 is already installed and up-to-date.
2023-01-06T20:18:39.1130990Z To reinstall 1.0, run:
2023-01-06T20:18:39.1131790Z   brew reinstall libunistring
2023-01-06T20:18:39.1200820Z [33mWarning:[0m m4 1.4.19 is already installed and up-to-date.
2023-01-06T20:18:39.1201210Z To reinstall 1.4.19, run:
2023-01-06T20:18:39.1201480Z   brew reinstall m4
2023-01-06T20:18:39.1345000Z [33mWarning:[0m mpfr 4.1.0-p13 is already installed and up-to-date.
2023-01-06T20:18:39.1345910Z To reinstall 4.1.0-p13, run:
2023-01-06T20:18:39.1346690Z   brew reinstall mpfr
2023-01-06T20:18:39.1429320Z [33mWarning:[0m ncurses 6.3 is already installed and up-to-date.
2023-01-06T20:18:39.1429680Z To reinstall 6.3, run:
2023-01-06T20:18:39.1430130Z   brew reinstall ncurses
2023-01-06T20:18:39.1486370Z [33mWarning:[0m openssl@1.1 1.1.1s is already installed and up-to-date.
2023-01-06T20:18:39.1486770Z To reinstall 1.1.1s, run:
2023-01-06T20:18:39.1487030Z   brew reinstall openssl@1.1
2023-01-06T20:18:39.1506350Z [33mWarning:[0m pkg-config 0.29.2_3 is already installed and up-to-date.
2023-01-06T20:18:39.1506740Z To reinstall 0.29.2_3, run:
2023-01-06T20:18:39.1507250Z   brew reinstall pkg-config
2023-01-06T20:18:39.1649020Z [33mWarning:[0m readline 8.2.1 is already installed and up-to-date.
2023-01-06T20:18:39.1649380Z To reinstall 8.2.1, run:
2023-01-06T20:18:39.1649620Z   brew reinstall readline
2023-01-06T20:18:39.1728480Z [33mWarning:[0m wget 1.21.3 is already installed and up-to-date.
2023-01-06T20:18:39.1729300Z To reinstall 1.21.3, run:
2023-01-06T20:18:39.1729780Z   brew reinstall wget
2023-01-06T20:18:39.1783170Z [33mWarning:[0m zstd 1.5.2 is already installed and up-to-date.
2023-01-06T20:18:39.1783590Z To reinstall 1.5.2, run:
2023-01-06T20:18:39.1783870Z   brew reinstall zstd
```

which means more of these can be removed.

**Comment by neheb** [comment]
@Ansuel might as well merge.

**Pull request merged**
