### PR TITLE
mediatek: filogic: switch to fitblk for Xiaomi Redmi AX6000

### PR DESCRIPTION
**Pull request by HZFrodo**
Use the new fitblk driver.

Run-tested: filogic/mt7986a-xiaomi-redmi-router-ax6000-ubootmod

### CODE REVIEW

**Comment by HZFrodo** [comment]
Full boot log:

```
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 6.1.80 (xxx@xxx-xxx) (aarch64-openwrt-linux-musl-gcc (OpenWrt GCC 12.3.0 r25392-13cdc8955c) 12.3.0, GNU ld (GNU Binutils) 2.40.0) #0 SMP Mon Mar  4 23:23:59 2024
[    0.000000] Machine model: Xiaomi Redmi Router AX6000 (OpenWrt U-Boot layout)
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x0000000042ffffff]
[    0.000000]   node   0: [mem 0x0000000043000000-0x000000004302ffff]
[    0.000000]   node   0: [mem 0x0000000043030000-0x000000004fbfffff]
[    0.000000]   node   0: [mem 0x000000004fc00000-0x000000004ffbffff]
[    0.000000]   node   0: [mem 0x000000004ffc0000-0x000000005fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.4
[    0.000000] percpu: Embedded 18 pages/cpu s33384 r8192 d32152 u73728
[    0.000000] pcpu-alloc: s33384 r8192 d32152 u73728 alloc=18*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: GIC system register CPU interface
[    0.000000] CPU features: kernel page table isolation disabled by kernel configuration
[    0.000000] alternatives: applying boot alternatives
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129024
[    0.000000] Kernel command line: console=ttyS0,115200n8 console_msg_format=syslog
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 497300K/524288K available (8320K kernel code, 886K rwdata, 2412K rodata, 448K init, 289K bss, 26988K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GICv3: GIC: Using split EOI/Deactivate mode
[    0.000000] GICv3: 640 SPIs implemented
[    0.000000] GICv3: 0 Extended SPIs implemented
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GICv3: GICv3 features: 16 PPIs
[    0.000000] GICv3: CPU0: found redistributor 0 region 0:0x000000000c080000
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 timer(s) running at 13.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x2ff89eacb, max_idle_ns: 440795202429 ns
[    0.000000] sched_clock: 56 bits at 13MHz, resolution 76ns, wraps every 4398046511101ns
[    0.000120] Calibrating delay loop (skipped), value calculated using timer frequency.. 26.00 BogoMIPS (lpj=130000)
[    0.000126] pid_max: default: 32768 minimum: 301
[    0.000335] Mount-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.000342] Mountpoint-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.000999] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.001305] cblist_init_generic: Setting adjustable number of callback queues.
[    0.001308] cblist_init_generic: Setting shift to 2 and lim to 1.
[    0.001397] rcu: Hierarchical SRCU implementation.
[    0.001398] rcu:     Max phase no-delay instances is 1000.
[    0.001682] smp: Bringing up secondary CPUs ...
[    0.001946] Detected VIPT I-cache on CPU1
[    0.001988] cacheinfo: Unable to detect cache hierarchy for CPU 1
[    0.001994] GICv3: CPU1: found redistributor 1 region 0:0x000000000c0a0000
[    0.002019] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.002280] Detected VIPT I-cache on CPU2
[    0.002309] cacheinfo: Unable to detect cache hierarchy for CPU 2
[    0.002313] GICv3: CPU2: found redistributor 2 region 0:0x000000000c0c0000
[    0.002323] CPU2: Booted secondary processor 0x0000000002 [0x410fd034]
[    0.002574] Detected VIPT I-cache on CPU3
[    0.002601] cacheinfo: Unable to detect cache hierarchy for CPU 3
[    0.002605] GICv3: CPU3: found redistributor 3 region 0:0x000000000c0e0000
[    0.002615] CPU3: Booted secondary processor 0x0000000003 [0x410fd034]
[    0.002640] smp: Brought up 1 node, 4 CPUs
[    0.002644] SMP: Total of 4 processors activated.
[    0.002646] CPU features: detected: 32-bit EL0 Support
[    0.002648] CPU features: detected: CRC32 instructions
[    0.002671] CPU features: emulated: Privileged Access Never (PAN) using TTBR0_EL1 switching
[    0.002674] CPU: All CPU(s) started at EL2
[    0.002675] alternatives: applying system-wide alternatives
[    0.005137] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.005153] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.005287] pinctrl core: initialized pinctrl subsystem
[    0.005795] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.006053] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[    0.006074] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.006089] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.006423] thermal_sys: Registered thermal governor 'fair_share'
[    0.006425] thermal_sys: Registered thermal governor 'bang_bang'
[    0.006427] thermal_sys: Registered thermal governor 'step_wise'
[    0.006428] thermal_sys: Registered thermal governor 'user_space'
[    0.006469] ASID allocator initialised with 65536 entries
[    0.006787] pstore: Registered ramoops as persistent store backend
[    0.006789] ramoops: using 0x10000@0x42ff0000, ecc: 0
[    0.013901] cryptd: max_cpu_qlen set to 1000
[    0.014551] SCSI subsystem initialized
[    0.014622] libata version 3.00 loaded.
[    0.015514] clocksource: Switched to clocksource arch_sys_counter
[    0.016063] NET: Registered PF_INET protocol family
[    0.016141] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.016532] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.016542] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.016548] TCP established hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.016569] TCP bind hash table entries: 4096 (order: 5, 131072 bytes, linear)
[    0.016662] TCP: Hash tables configured (established 4096 bind 4096)
[    0.016722] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.016737] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.016826] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.016846] PCI: CLS 0 bytes, default 64
[    0.017691] workingset: timestamp_bits=46 max_order=17 bucket_order=0
[    0.020526] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.020535] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.046198] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
[    0.046868] printk: console [ttyS0] disabled
[    0.067017] 11002000.serial: ttyS0 at MMIO 0x11002000 (irq = 116, base_baud = 2500000) is a ST16650V2
[    0.785009] printk: console [ttyS0] enabled
[    0.790041] mtk_rng 1020f000.rng: registered RNG driver
[    0.795743] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.804396] loop: module loaded
[    0.809044] spi spi0.0: setup: ignoring unsupported mode bits a00
[    0.815679] spi-nand spi0.0: ESMT SPI NAND was found.
[    0.820979] spi-nand spi0.0: 128 MiB, block size: 128 KiB, page size: 2048, OOB size: 64
[    0.829513] 6 fixed-partitions partitions found on MTD device spi0.0
[    0.836304] Creating 6 MTD partitions on "spi0.0":
[    0.841341] 0x000000000000-0x000000100000 : "BL2"
[    0.847510] 0x000000100000-0x000000140000 : "Nvram"
[    0.853126] 0x000000140000-0x000000180000 : "Bdata"
[    0.858792] 0x000000180000-0x000000380000 : "Factory"
[    0.866247] 0x000000380000-0x000000580000 : "FIP"
[    0.873131] 0x000000580000-0x000008000000 : "ubi"
[    0.979367] ubi0: default fastmap pool size: 45
[    0.984152] ubi0: default fastmap WL pool size: 22
[    0.989194] ubi0: attaching mtd5
[    3.106101] ubi0: scanning is finished
[    3.134655] ubi0: attached mtd5 (name "ubi", size 122 MiB)
[    3.140407] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    3.147526] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    3.154551] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    3.161754] ubi0: good PEBs: 980, bad PEBs: 0, corrupted PEBs: 0
[    3.168005] ubi0: user volume: 4, internal volumes: 1, max. volumes count: 128
[    3.175464] ubi0: max/mean erase counter: 7/3, WL threshold: 4096, image sequence number: 1157858698
[    3.184833] ubi0: available PEBs: 0, total reserved PEBs: 980, PEBs reserved for bad PEB handling: 20
[    3.194293] ubi0: background thread "ubi_bgt0d" started, PID 182
[    3.195789] block ubiblock0_2: created from ubi0:2(fit)
[    3.339772] mtk_soc_eth 15100000.ethernet eth0: mediatek frame engine at 0xffffffc009480000, irq 121
[    3.349587] i2c_dev: i2c /dev entries driver
[    3.355301] mtk-wdt 1001c000.watchdog: Watchdog enabled (timeout=31 sec, nowayout=0)
[    3.363966] NET: Registered PF_INET6 protocol family
[    3.369813] Segment Routing with IPv6
[    3.373738] In-situ OAM (IOAM) with IPv6
[    3.377963] NET: Registered PF_PACKET protocol family
[    3.383342] 8021q: 802.1Q VLAN Support v1.8
[    3.388784] pstore: Using crash dump compression: deflate
[    3.403360] FIT: Detected U-Boot 2024.01-OpenWrt-r25383-fbb924abff
[    3.409868] FIT: Selected configuration: "config-1" (OpenWrt xiaomi_redmi-router-ax6000-ubootmod)
[    3.418990] FIT:           kernel sub-image 0x00001000..0x0053d318 "kernel-1" (ARM64 OpenWrt Linux-6.1.80) 
[    3.428976] FIT:          flat_dt sub-image 0x0053e000..0x0054305d "fdt-1" (ARM64 OpenWrt xiaomi_redmi-router-ax6000-ubootmod device tree blob) 
[    3.442166] FIT:       filesystem sub-image 0x00544000..0x009fdfff "rootfs-1" (ARM64 OpenWrt xiaomi_redmi-router-ax6000-ubootmod rootfs) 
[    3.455110] block ubiblock0_2: mapped 1 uImage.FIT filesystem sub-image as /dev/fit0
[    3.502606] mt7530-mdio mdio-bus:1f: configuring for fixed/2500base-x link mode
[    3.511831] mt7530-mdio mdio-bus:1f: Link is Up - 2.5Gbps/Full - flow control rx/tx
[    3.521276] mt7530-mdio mdio-bus:1f lan4 (uninitialized): PHY [mt7530-0:01] driver [MediaTek MT7531 PHY] (irq=125)
[    3.541859] mt7530-mdio mdio-bus:1f lan3 (uninitialized): PHY [mt7530-0:02] driver [MediaTek MT7531 PHY] (irq=126)
[    3.562156] mt7530-mdio mdio-bus:1f lan2 (uninitialized): PHY [mt7530-0:03] driver [MediaTek MT7531 PHY] (irq=127)
[    3.582443] mt7530-mdio mdio-bus:1f wan (uninitialized): PHY [mt7530-0:04] driver [MediaTek MT7531 PHY] (irq=128)
[    3.593784] device eth0 entered promiscuous mode
[    3.598681] DSA: tree 0 setup
[    3.603195] UBI: auto-attach mtd5
[    3.606784] ubi: mtd5 is already attached to ubi0
[    3.611730] UBI error: cannot attach mtd5
[    3.629055] VFS: Mounted root (squashfs filesystem) readonly on device 259:0.
[    3.636604] Freeing unused kernel memory: 448K
[    3.705548] Run /sbin/init as init process
[    3.709890]   with arguments:
[    3.713101]     /sbin/init
[    3.716063]   with environment:
[    3.719448]     HOME=/
[    3.722052]     TERM=linux
[    4.005523] random: crng init done
[    4.087008] init: Console is alive
[    4.090853] init: - watchdog -
[    4.731122] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    4.774857] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    4.792654] init: - preinit -
[    5.348570] mtk_soc_eth 15100000.ethernet eth0: configuring for fixed/2500base-x link mode
[    5.357374] mtk_soc_eth 15100000.ethernet eth0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[    5.366625] mt7530-mdio mdio-bus:1f lan4: configuring for phy/gmii link mode
[    5.374447] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    6.523084] mt7530-mdio mdio-bus:1f lan4: Link is Up - 1Gbps/Full - flow control rx/tx
[    6.531288] IPv6: ADDRCONF(NETDEV_CHANGE): lan4: link becomes ready
[    7.505750] UBIFS (ubi0:3): Mounting in unauthenticated mode
[    7.511730] UBIFS (ubi0:3): background thread "ubifs_bgt0_3" started, PID 541
[    7.855634] UBIFS (ubi0:3): UBIFS: mounted UBI device 0, volume 3, name "rootfs_data"
[    7.863710] UBIFS (ubi0:3): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[    7.873865] UBIFS (ubi0:3): FS size: 108691456 bytes (103 MiB, 856 LEBs), max 867 LEBs, journal size 5459968 bytes (5 MiB, 43 LEBs)
[    7.885924] UBIFS (ubi0:3): reserved for root: 4952683 bytes (4836 KiB)
[    7.892778] UBIFS (ubi0:3): media format: w5/r0 (latest is w5/r0), UUID AF148FD7-9024-455E-86E9-ED1F055B221B, small LPT model
[    7.906886] mount_root: overlay filesystem has not been fully initialized yet
[    7.916741] mount_root: switching to ubifs overlay
[    7.930170] overlayfs: null uuid detected in lower fs '/', falling back to xino=off,index=off,nfs_export=off.
[    8.237197] urandom-seed: Seed file not found (/etc/urandom.seed)
[    8.298834] mt7530-mdio mdio-bus:1f lan4: Link is Down
[    8.310328] procd: - early -
[    8.313608] procd: - watchdog -
[    8.866774] procd: - watchdog -
[    8.870413] procd: - ubus -
[    8.957827] procd: - init -
[    9.253365] kmodloader: loading kernel modules from /etc/modules.d/*
[    9.299046] crypto-safexcel 10320000.crypto: EIP97:230(0,1,4,4)-HIA:270(0,5,5),PE:150/433(alg:7fcdfc00)/0/0/0
[    9.315488] Loading modules backported from Linux version v6.6.15-0-g51f354b815c4
[    9.323256] Backport generated by backports.git 193becf2
[    9.406557] urngd: v1.0.2 started.
[    9.776282] mt798x-wmac 18000000.wifi: HW/SW Version: 0x8a108a10, Build Time: 20221012174648a
[    9.776282] 
[   10.109381] mt798x-wmac 18000000.wifi: WM Firmware Version: ____000000, Build Time: 20221012174725
[   10.261355] mt798x-wmac 18000000.wifi: WA Firmware Version: DEV_000000, Build Time: 20221012174937
[   10.369280] mt798x-wmac 18000000.wifi: registering led 'mt76-phy0'
[   10.377068] mt798x-wmac 18000000.wifi: registering led 'mt76-phy1'
[   14.196431] PPP generic driver version 2.4.2
[   14.201588] NET: Registered PF_PPPOX protocol family
[   14.208649] kmodloader: done loading kernel modules from /etc/modules.d/*
[   14.375442] mtdblock: MTD device 'Bdata' is NAND, please consider using UBI block devices instead.
[   18.662075] mtk_soc_eth 15100000.ethernet eth0: Link is Down
[   18.675322] mtk_soc_eth 15100000.ethernet eth0: configuring for fixed/2500base-x link mode
[   18.684129] mtk_soc_eth 15100000.ethernet eth0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[   18.688765] mt7530-mdio mdio-bus:1f lan2: configuring for phy/gmii link mode
[   18.700899] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   18.707686] br-lan: port 1(lan2) entered blocking state
[   18.713204] br-lan: port 1(lan2) entered disabled state
[   18.721718] device lan2 entered promiscuous mode
[   18.737173] mt7530-mdio mdio-bus:1f lan3: configuring for phy/gmii link mode
[   18.747347] br-lan: port 2(lan3) entered blocking state
[   18.752848] br-lan: port 2(lan3) entered disabled state
[   18.760145] device lan3 entered promiscuous mode
[   18.771978] mt7530-mdio mdio-bus:1f lan4: configuring for phy/gmii link mode
[   18.782265] br-lan: port 3(lan4) entered blocking state
[   18.787811] br-lan: port 3(lan4) entered disabled state
[   18.795323] device lan4 entered promiscuous mode
[   18.809374] mt7530-mdio mdio-bus:1f wan: configuring for phy/gmii link mode
```

**Comment by graysky2** [comment]
Are any changes needed for users building their own images should this PR get merged or will it just work?

**Comment by HZFrodo** [comment]
> Are any changes needed for users building their own images should this PR get merged or will it just work?

No, it just work after user upgrade to new firmware, user configurations will retain.

**Comment by 981213** [comment]
Merged. Thanks!

**Comment by everything411** [comment]
It seems that this change breaks the installation method in [openwrt wiki for redmi ax6000 ubootmod](https://openwrt.org/toh/xiaomi/redmi_ax6000).
`sysupgrade -n /tmp/ax6000-ubootmod-squashfs-sysupgrade.itb` fails in initramfs-recovery mode.
`fitblk_get_bootdev` (code link [here](https://github.com/openwrt/openwrt/blob/22f24f91076d858775fb7ebb0693508c1df421d0/target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh#L89C14-L89C32)) returns `""` (nothing) in initramfs-recovery mode and then the script writes nothing to the flash.

**Pull request closed without merging**
