### PR TITLE
omap: add kernel 6.6

### PR DESCRIPTION
**Pull request by dhewg**
Just as with #14582, simple and fast change.
Lightly tested on boneblack.

/cc @janh wrt cpsw driver, I didn't check if the patch is still required for 6.6, so I kept it.

### CODE REVIEW

**Comment by namiltd** [comment]
I think you should rename the patches folder to patches-6.6 to make it easier to update to the next kernel versions.

**Comment by dhewg** [comment]
I initially decided against it, but done now.
I checked and omap was the only target which didn't have the version 
suffix, so this brings it in line.

**Comment by namiltd** [comment]
You set:
```
# CONFIG_CRYPTO_MANAGER_DISABLE_TESTS is not set
# CONFIG_CRYPTO_MANAGER_EXTRA_TESTS is not set
```
Or maybe it would be better?:
```
CONFIG_ASYMMETRIC_KEY_TYPE=y
CONFIG_ASYMMETRIC_PUBLIC_KEY_SUBTYPE=y
CONFIG_CRYPTO_CURVE25519=y
CONFIG_CRYPTO_LIB_CURVE25519_GENERIC=y
CONFIG_CRYPTO_SIG=y
# CONFIG_PKCS8_PRIVATE_KEY_PARSER is not set
```
Link: https://github.com/openwrt/openwrt/compare/1f55fd3f652c088d2333a3c550eec0247229968a..7424b41fc813c0e3fb0a3d85750e1fded322e99d

**Comment by dhewg** [comment]
That looks like bloat to me, as long as nothing depends on those knobs 
we shouldn't have a reason to enable them

**Pull request merged**
