### PR TITLE
target: add standard arm64 target

### PR DESCRIPTION
**Pull request by mcbridematt**
This port is for arm64 systems that implement Arm's Boot Base specifications, also known as [Arm SystemReady](https://github.com/ARM-software/arm-systemready).

These systems behave a lot like existing x86 machines, e.g using EFI+GRUB to boot. This target does use some of the same code and scripts as x86 (especially around the GRUB EFI setup).

Versions of this target have been submitted in the past but didn't get any traction. Now that such machines are now more abundant I think now is a good time. We have been "shipping" this as the OpenWrt port for our Ten64 product for a while, though some Ten64-specific bits are not in this set.

The initial version has been tested with:
* Traverse Ten64 (NXP LS1088A)
* QEMU virt with EDKII firmware
* Amazon EC2 Graviton instances
* VMware Fusion for Apple Silicon (tech preview version).

On prior versions of this patchset there has been suggestions that this should belong under the `armvirt` target. I'm open to the idea. Note that there is no 32-bit support under the arm64 target.

### CODE REVIEW

**Comment by dangowrt** [comment]
I also think that merging this with armvirt (and renaming it to genericarm or something like that) would be the way to go.

FYI: U-Boot supports starting GRUB EFI as well, so even targets now supported by using U-Boot directly may also boot via EFI (`mediatek/mt7622` BananaPi BPi-R64, for example, see https://forum.banana-pi.org/t/having-fun-with-passmark-memtest86-9-0-free-on-the-bpi-r64/12017 ).

**Comment by mcbridematt** [comment]
Our board (Ten64) uses U-Boot so yes this target does work with U-Boot's EFI support :)

Pretty much any modern ARM64 board that uses mass storage (eMMC,SD,USB,NVMe) can use this, though it gets slightly more complicated for boards where the mass storage is also the SoC boot mechanism (e.g Raspberry Pi)

**Comment by aparcar** [comment]
Tested and works great on my Apple Silicon with UTM.

I guess it should become part of armvirt rather being it's own target.

**Comment by mcbridematt** [comment]
> I also think that merging this with armvirt
> I guess it should become part of armvirt rather being it's own target.

Alright, I'll make it so.

> (and renaming it to genericarm or something like that)

Would be a good idea I think. Maybe the existing '32'/'64' in armvirt should move under 'qemu' as well, but that doesn't have to happen right away.

**Comment by svlobanov** [comment]
Tested-by: Sergey V. Lobanov <sergey@lobanov>

VMDK image tested on macos big sur (arm64) with VMWare Fusion Professional Version e.x.p (18656771), e1000e and vmxnet3 network interfaces

**Comment by dangowrt** [comment]
> Would be a good idea I think. Maybe the existing '32'/'64' in armvirt should move under 'qemu' as well, but that doesn't have to happen right away.

I reckon the very same kernel suitable for UEFI boot on ARM64 can also be used with QEMU if we just add the needed config symbols for both use-cases into a common kernel configuration, so we won't need an additional 'qemu' target.

**Comment by varoudis** [comment]
Works great on pimox7 or Proxmox on arm64 (rPi4).
Very useful thank you.

**Comment by mcbridematt** [comment]
As suggested, I have restructured this into the armvirt target - see pull #4996.

**Pull request closed without merging**
