### PR TITLE
kernel: bump 6.1 to 6.1.37

### PR DESCRIPTION
**Pull request by graysky2**
kernel: bump 6.1 to 6.1.37

Manually rebased:
	generic/hack-6.1/220-arm-gc_sections.patch
	armsr/patches-6.1/221-armsr-disable_gc_sections_armv7.patch

All other patches automatically rebased.

### CODE REVIEW

**Comment by graysky2** [comment]
Not sure what needs to happen to fix these errors

**Comment by ajayramaswamy** [comment]
the path of the modules have changed see
https://github.com/gregkh/linux/commit/29429a1f5871dbe54ee0da81bb12db8567f15379

**Comment by john-tho** [comment]
> Not sure what needs to happen to fix these errors

> the path of the modules have changed see [gregkh/linux@29429a1](https://github.com/gregkh/linux/commit/29429a1f5871dbe54ee0da81bb12db8567f15379)

Ouch. Changing a path in a stable kernel is noticable.

There are [kernel version test modifiers](https://github.com/openwrt/openwrt/blob/01885bc6a33dbfa6f3c9e97778fd8f4f60e2514f/include/kernel.mk#L299) we can use for the module `FILES`. Example being when kernel version greater or equal to 6.1: `@ge6.1`, and the opposite, less than 6.1: `@lt6.1`.
Try something like (untested):
```patch
diff --git a/package/kernel/linux/modules/fs.mk b/package/kernel/linux/modules/fs.mk
index 5fb9a2b7d64f..dd50ef5e311a 100644
--- a/package/kernel/linux/modules/fs.mk
+++ b/package/kernel/linux/modules/fs.mk
@@ -89,8 +89,10 @@ define KernelPackage/fs-smbfs-common
   HIDDEN:=1
   KCONFIG:=CONFIG_SMBFS_COMMON
   FILES:= \
-	$(LINUX_DIR)/fs/smbfs_common/cifs_arc4.ko \
-	$(LINUX_DIR)/fs/smbfs_common/cifs_md4.ko
+	$(LINUX_DIR)/fs/smbfs_common/cifs_arc4.ko@lt6.1 \
+	$(LINUX_DIR)/fs/smbfs_common/cifs_md4.ko@lt6.1 \
+	$(LINUX_DIR)/fs/smb/common/cifs_arc4.ko@ge6.1 \
+	$(LINUX_DIR)/fs/smb/common/cifs_md4.ko@ge6.1
 endef
 
 define KernelPackage/fs-smbfs-common/description
@@ -108,7 +110,8 @@ define KernelPackage/fs-cifs
 	CONFIG_CIFS_DFS_UPCALL=n \
 	CONFIG_CIFS_UPCALL=n
   FILES:= \
-	$(LINUX_DIR)/fs/cifs/cifs.ko
+	$(LINUX_DIR)/fs/cifs/cifs.ko@lt6.1 \
+	$(LINUX_DIR)/fs/smb/client/cifs.ko@ge6.1
   AUTOLOAD:=$(call AutoLoad,30,cifs)
   $(call AddDepends/nls)
   DEPENDS+= \
@@ -373,7 +376,9 @@ define KernelPackage/fs-ksmbd
 	CONFIG_SMB_SERVER_SMBDIRECT=n \
 	CONFIG_SMB_SERVER_CHECK_CAP_NET_ADMIN=n \
 	CONFIG_SMB_SERVER_KERBEROS5=n
-  FILES:=$(LINUX_DIR)/fs/ksmbd/ksmbd.ko
+  FILES:= \
+	 $(LINUX_DIR)/fs/ksmbd/ksmbd.ko@lt6.1 \
+	 $(LINUX_DIR)/fs/smb/server/ksmbd.ko@ge6.1
   AUTOLOAD:=$(call AutoLoad,41,ksmbd)
 endef
 

```

**Comment by john-tho** [comment]
I see CI spat out an error for the common modules:
```
Package kmod-fs-cifs is missing dependencies for the following libraries:
cifs_arc4.ko
cifs_md4.ko
```
Not enough CI log to see if these are packaged by fs-smbfs-common, or I typo'ed my paths somewhere.

I did miss that the kconfig `SMBFS_COMMON` got changed to `CONFIG_SMBFS`, so we will need to fix that as well, with something like:
```
  KCONFIG:=\
           CONFIG_SMBFS_COMMON@lt6.1 \
           CONFIG_SMBFS@ge6.1
```

Maybe wait to hear what a committer has to say, but I would prefer these cifs module folder rename changes squashed into the kernel bump commit, otherwise we would have a commit with a broken build.
Fine by me if you take authorship of these changes, they were only suggestions, but if you do tag me as (co-)author, you would need to include my Signed-off-by tag as well. I didn't do that (and format a proper patch) because I had not tested the changes.

Cheers,
Thanks for handling these kernel bumps

**Comment by graysky2** [comment]
I applied your changes and squashed per your suggestion.  Thanks!

**Comment by john-tho** [comment]
I had to go digging to work out why CI was failing, and think I came up with a bug and fix via https://github.com/openwrt/openwrt/pull/13021. It allowed me to build a bcm2711 rpi4 image with kmod-fs-ksmbd atop your last push (https://github.com/openwrt/openwrt/commit/bdb9178de2e319d28bc5beef204c89931f0a710b).
Alternatively, leave the version switches off the KCONFIG symbols. Just list both the new, and the old symbols, and let kconfig deal with them.

**Comment by graysky2** [comment]
I accidentally deleted by 6.1 branch ... I recreated it but am unable reopen this PR.

**Comment by graysky2** [comment]
I accidentally deleted by 6.1 branch ... I recreated it but am unable reopen this PR.

**Comment by graysky2** [comment]
I accidentally deleted by 6.1 branch ... I recreated and reopen this PR.

**Comment by graysky2** [comment]
Reopened

**Comment by graysky2** [comment]
I cannot get the PR to reopen. Should I create a new one?

**Comment by john-tho** [comment]
> I cannot get the PR to reopen. Should I create a new one?

I think, you need to restore the branch to state when PR was closed.
See if you can `reset --hard` your 6.1 branch back to https://github.com/openwrt/openwrt/commit/bdb9178de2e319d28bc5beef204c89931f0a710b, then push it, then reopen.
Also, might need to reset to https://github.com/openwrt/openwrt/commit/01885bc6a33dbfa6f3c9e97778fd8f4f60e2514f (I see that was referenced in a compare where, so guessing that was your previous base at close) before applying `bdb`.

**Comment by graysky2** [comment]
Trying with https://github.com/openwrt/openwrt/commit/bdb9178de2e319d28bc5beef204c89931f0a710b

**Comment by graysky2** [comment]
now the reopen and comment button is available

**Comment by graysky2** [comment]
No luck it seems

**Comment by graysky2** [comment]
That did it (hard reset).  Thanks.

**Comment by graysky2** [comment]
I think `CONFIG_LOCK_MM_AND_FIND_VMA=y` should be set but in which file?

**Comment by john-tho** [comment]
> I think `CONFIG_LOCK_MM_AND_FIND_VMA=y` should be set but in which file?

When we search for it, it is quite widely used (from 6.1.37): https://elixir.bootlin.com/linux/v6.1.37/A/ident/CONFIG_LOCK_MM_AND_FIND_VMA, https://github.com/gregkh/linux/commits/linux-6.1.y
From a quick look, it looks like it is selected on all the OpenWrt arch: arm, arm64, mips, powerpc, riscv, x86. If that is the case, set it in `target/linux/generic`, I guess.

**Comment by hauke** [comment]
Yes please fold the changes needed for a kernel bump just into the commit which bumps the kernel.

**Comment by graysky2** [comment]
> Yes please fold the changes needed for a kernel bump just into the commit which bumps the kernel.

In the future, do you want all changes in a single commit?  Ie, patch rebased + config changes if needed?  In the past, I believe guidance was to have them separated into their own commits.

**Pull request merged**
