### PR TITLE
uClibc-ng: update package from 1.0.31 to 1.0.34

### PR DESCRIPTION
**Pull request by Grommish**
Signed-off-by: Donald Hoskins <grommish@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Tested on malta. Works fine.

**Comment by ynezz** [comment]
Add commit description, change the commit subject to `uclibc: update package from 1.0.31 to 1.0.34` as in https://openwrt.org/submitting-patches

**Comment by Grommish** [comment]
Is there anything else that needs to be correctect?

**Comment by hauke** [comment]
This was applied in c182caeec275b0ca11614cb3d8db7bba57845032

**Pull request closed without merging**
