### PR TITLE
dropbear: bump to 2018.76

### PR DESCRIPTION
**Pull request by rockdrilla**
- cherry-pick upstream fixes
- strip down supplemental code for fuzzing
- refresh patches
- move OpenWrt configuration from patch to Build/Configure recipe

NB: this PR recommends (#786) to be merged upstream.

compile- and run-tested on ar71xx/generic (TP-Link Archer C7 v2).
compare 'build metrics' for dropbear versions (2017.75 vs 2018.76):

  'make defconfig' scenario:
  - binary size has grown by 14% (168kb vs 192kb),
  - package (ipk) has grown by 14% (85kb vs 97kb).

  This is more reliable result compared with (#789).

  same with CONFIG_DROPBEAR_ECC=y:
  - binary size has grown by 10% (193kb vs 212kb),
  - package (ipk) has grown by 11% (96kb vs 107kb).

dropbear 2018.76 changelog:

  Configuration/compatibility changes:
  - "configure --enable-static" should now be used instead of "make STATIC=1".
    This will avoid 'hardened build' flags that conflict with static binaries.
  - Set 'hardened build' flags by default if supported by the compiler.
    These can be disabled with configure --disable-harden if needed.
  - Spectre patch from Loganaden Velvindron.
  - "dropbear -r" option for hostkeys no longer attempts to load the default
    hostkey paths as well. If desired these can be specified manually.
    Patch from CamVan Nguyen.
  - group1-sha1 key exchange is disabled in the server by default since the
    fixed 1024-bit group may be susceptible to attacks.
  - twofish ciphers are now disabled in the default configuration.
  - Default generated ECDSA key size is now 256 (rather than 521) for better
    interoperability.
  - Minimum RSA key length has been increased to 1024 bits.

  Other features and fixes:
  - Add runtime -T max_auth_tries option from Kevin Darbyshire-Bryant.
  - Add 'dbclient -J &fd' to allow dbclient to connect over an existing socket.
    See dbclient manpage for a socat example. Patch from Harald Becker.
  - Add "-c forced_command" option. Patch from Jeremy Kerr.
  - Restricted group -G option added with patch from stellarpower.
  - Support server-chosen TCP forwarding ports, patch from houseofkodai.
  - Allow choosing outgoing address for dbclient with
    -b [bind_address][:bind_port]. Patch from houseofkodai.
  - Makefile will now rebuild object files when header files are modified.
  - Add group14-256 and group16 key exchange options.
  - curve25519-sha256 also supported without @libssh.org suffix.
  - Update bundled libtomcrypt to 1.18.1, libtommath to 1.0.1.
    This fixes building with some recent versions of clang.
  - Set PAM_RHOST which is needed by modules such as pam_abl.
  - Improvements to DSS and RSA public key validation.
    Found by OSS-Fuzz.
  - Don't exit when an authorized_keys file has malformed entries.
    Found by OSS-Fuzz.
  - Fix null-pointer crash with malformed ECDSA or DSS keys.
    Found by OSS-Fuzz
  - Numerous code cleanups and small issues fixed by Francois Perrad.
  - Test for pkt_sched.h rather than SO_PRIORITY which was problematic with
    some musl platforms. Reported by Oliver Schneider and Andrew Bainbridge.
  - Fix some platform portability problems, from Ben Gardner.
  - Add EXEEXT filename suffix for building dropbearmulti, from William Foster.
  - Support --enable-<option> properly for configure, from Stefan Hauser.
  - configure have_openpty result can be cached, from Eric BУЉnard.
  - handle platforms that return close() < -1 on failure, from Marco Wenzel.
  - Build and configuration cleanups from Michael Witten.
  - Fix libtomcrypt/libtommath linking order, from Andre McCurdy.
  - Fix old Linux platforms that have SYS_clock_gettime but not CLOCK_MONOTONIC.
  - Update curve25519-donna implementation to current version.

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
Instead of adding a "ton" of upstream patches just use git and use a specific commit instead?

**Comment by neheb** [comment]
NAK on all the upstream patches. They should only be in OpenWrt if they fix something.

**Comment by rockdrilla** [comment]
@diizzyy upstream has a lot of code for fuzzing, so using git trunk isn't applicable. Are we planning to do fuzzing on low/mid-end soho routers? Well, no.

@neheb Just take a look at patches first prior to commenting PR, and only then we may talk about them.

**Comment by dedeckeh** [comment]
@rockdrilla Your latest patches are missing a SoB and in several cases a clear commit description explaining what the patch changes

**Comment by rockdrilla** [comment]
@dedeckeh, please point out which commits don't have descriptive message, i'll fix this ASAP.

**Comment by dedeckeh** [comment]
Commits having no SoB:

- https://github.com/openwrt/openwrt/pull/876/commits/00099ce7986739092c777a6d1343cc2d30eaf930

- https://github.com/openwrt/openwrt/pull/876/commits/a471c5d34855d03fb0818607a35cdab4063b76f4

- https://github.com/openwrt/openwrt/pull/876/commits/1e87128734363514662fa8371c9d5abfac20fa43

- https://github.com/openwrt/openwrt/pull/876/commits/5c7094b0bb391604d16e5119cf529d990508ef29

- https://github.com/openwrt/openwrt/pull/876/commits/970768c3a8da71e6045a4ea13260f39e4b587d43


Patch https://github.com/openwrt/openwrt/pull/876/commits/a471c5d34855d03fb0818607a35cdab4063b76f4 should not be a seperate commit but rather squashed into https://github.com/openwrt/openwrt/pull/876/commits/00099ce7986739092c777a6d1343cc2d30eaf930

As already mentioned by @neheb those extra patches on top of version 2018.76 is awkward unless they fix critical issues; discussion needs to be hold with other developers if we want this

**Comment by dedeckeh** [comment]
I fail to understand why these extra patches are required; if they're critical I would expect a new dropbear version to be released in the near future

**Comment by nbd168** [comment]
Also, could you please investigate why the package binary size grows so much by the bump? What's the source of that extra bloat?

**Comment by rockdrilla** [comment]
@dedeckeh, ok, i'm going to rework extra patches.
@nbd168, i'll try to investigate where are these extra bytes reside.

**Comment by diizzyy** [comment]
Has anyone considered tinyssh as a viable alternative and/or compared sizes?

**Comment by diizzyy** [comment]
also, http://lists.infradead.org/pipermail/lede-dev/2018-April/011998.html

**Pull request closed without merging**
