### PR TITLE
binutils: Use 2.31.1 by default

### PR DESCRIPTION
**Pull request by diizzyy**
Set binutils 2.23.1 as default

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile/Runtime tested on: 
octeonplus, EdgeRouter Lite, OpenWrt master
kirkwood, iOmega iConnect, OpenWrt master
mvebu, Linksys WRT3200ACM, OpenWrt master
ramips, MQMaker WiTi board, OpenWrt master

**Comment by diizzyy** [comment]
@dedeckeh 
Technically that would be toolchain?

**Comment by diizzyy** [comment]
Compile/Runtime tested on:
ath79, TP-Link TL-WDR3600, OpenWrt master

**Comment by hauke** [comment]
Could you please post this to the mailling list, I think this needs some more discussion.

**Comment by diizzyy** [comment]
@hauke 
I'll close this then and let someone else do the work.

**Comment by diizzyy** [comment]
Longer tests with https://lists.openwrt.org/pipermail/openwrt-devel/2018-July/013394.html included

**Comment by diizzyy** [comment]
@hauke 
For whatever reason the mailinglist blocks the mail

**Comment by blogic** [comment]
it bounces as you are not subscribed.

**Comment by diizzyy** [comment]
@blogic 
Other mails works just fine which seems inconsistent?
```
The reason it is being held:

    Message has a suspicious header
```
Sounds like a configuration issue?

**Comment by diizzyy** [comment]
My bad, I'm using the wrong terminology apparently.
I'm subscribed but I don't receive any emails from the list itself (intentionally).
Sorry for the confusion

**Comment by hauke** [comment]
@diizzyy can you send the mail just to me then I can have a look at the headers.

**Comment by diizzyy** [comment]
@hauke 
I tried sending it again as I don't have the original mail left which the list accepted, weird.

Can you please reopen this?

**Pull request closed without merging**
