### PR TITLE
kernel: 5.10: backport mac06 explicit disable patch

### PR DESCRIPTION
**Pull request by clayface**
This commit adds Ansuel Smith's explicit mac06 disable.

Signed-off-by: Matthew Hagan <mnhagan88@gmail.com>

### CODE REVIEW

**Comment by clayface** [comment]
@neheb can you check please?
@ansuel I added your signed-off-by as well if that's okay

Let me know if there's any issue.

**Comment by Ansuel** [comment]
LGTM

**Comment by adschm** [comment]
The following are used twice: 730, 731, 732.

**Comment by clayface** [comment]
Fixed 730. 731 and 732 are formerly 781 and 782. 781 has two separate mt7530 related patches and 782 is a series of two patches.

**Comment by adschm** [comment]
Will merge the first patch after another rename.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master.

**Pull request closed without merging**
