### PR TITLE
comgt: add new script to send ussd request and get the answer

### PR DESCRIPTION
**Pull request by klukonin**
Maintainer: Felix Fietkau <nbd@nbd.name>

Signed-off-by: Kirill Lukonin klukonin@gmail.com

Run tested on: Mikrotik wAP LTE KIT

Description: New script for comgt. Should help to fetch balance or any additional information with USSD.
This script use the standard AT command which should be supported by all modems.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Hi, please adjust the order of stuff in your commit message. It should be like:
```
comgt: add new script to send ussd request and get the answer

New script for comgt. Should help to fetch balance or any additional information with USSD.
This script use the standard AT command which should be supported by all modems.

Run tested on: Mikrotik wAP LTE KIT

Signed-off-by: Kirill Lukonin klukonin@gmail.com
```

Maintainer is not required/useful there.

**Comment by klukonin** [comment]
@adrianschmutzler Done.

**Comment by klukonin** [comment]
Looks like everything is OK now.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
