### PR TITLE
Dnsmasq: update to 2.87

### PR DESCRIPTION
**Pull request by ldir-EDB0**
Another attempt, hopefully have more time this week.  Improved commit descriptions since last time.

### CODE REVIEW

**Comment by stangri** [comment]
First of all, thank you for tackling this again. The nft set support in dnsmasq is big and great news and I can't wait until this is merged and backported to 22.03.

> dnsmasq: nftset: serve from ipset config

I strongly believe we should leave existing ipset configs alone (and populate ipsets from dnsmasq if iptables/ipset are installed on systems with fw4 or throw the warning if iptables/ipset are not present) and use the new nftset configs to let dnsmasq populate nft sets and here's why:

1. If this were to get backported to 22.03 (which it should), it would break things for early adopters who are using 22.03 now with dnsmasq-full which only supports ipset. As the fw4 no longer creates/targets ipsets, they are using dnsmasq ipset support together with the iptables scripts and force-transitioning to nftsets would break things for them. Even before fw4, there were mentions/threads on the forum where people would use dhcp config for ipsets (to let dnsmasq populate ipsets) but would manually create ipsets and iptables rules to target/handle them, even tho fw3 supported the same functionality.
2. If this is designed to help people using ipset configs in `firewall` and `dhcp` who held off from upgrading to 22.03 due to dnsmasq not currently supporting nft sets, first of all they might still have to update their configs due to nft sets needing a family, second, they would most likely be savy enough to rename ipset to nftset in their configs anyways.
3. If this is designed for the future, to help people who have never used ipset before and coming to this feature after this PR is merged, they will be confused by having to use ipset config to create nft sets.
4. While ipset could be independent from any table and family-agnostic, the nft sets must belong to a table and require a table name, a table family and the nft set family to be defined, so we will need 3 additional options for the new nftset configurations compared to ipsets. Yes, the logic to derive the family name from the ipset is smart, but to fully support the capabilities of dnsmasq to populate nft sets, we'll need to allow users to indicate those 3 additional options.
5. What's the long-term thinking here? Let's say in 4-5 years when everyone has forgotten about iptables/ipset, the option would still be called ipset even tho it creates nft set?

Sorry, I can't contribute the code right now, but I believe that as long as the upstream package supports creating ipsets, whatever version of firewall is, the OpenWrt dnsmasq package should create an ipset if iptables/ipset are installed and throw a warning for ipset configs when iptables/ipset are not installed.

As per items 1-3 above, I don't see a user scenario where serving nft sets from ipset config is helpful and I see it being a burden in a future.

We need a new nftset config to let dnsmasq populate nft sets and it should support 3 new options: `table`, `table_family`, `family`. If family is omitted, it's a great idea to use the exiting code to derive the family from the set name, if the `table_family` is omitted it should be assumed `inet` and if `table` is omitted, it should be `fw4` (with `table_family`=`inet` of course).

PS. Because of the above, I also believe that the fw4 code should be updated to also allow the use of nftset config option to be consistent with dhcp config, however the fw4-created nft sets should be created within inet fw4 table of course and the only extra option allowed there would be the set family.

PPS.  Since the transition uci-defaults script is there already, we might use it to copy the ipset entries to nftset ones and then dnsmasq should try to populate both (and silently fail for ipset if the iptables/ipset are not present).

Tagging @jow- @mkresin .

**Comment by stangri** [comment]
> This could be solved by attempting to emit both nftset and ipset directives from the same ipset uci config, then disable either of them depending on the availability of installed tools.

That should solve the problem of people who have upgraded to 22.03 already and are already using dnsmasq ipset support, if implemented in the way to prioritizes ipset if iptables/ipset are installed.

> As far as I understand, the code is designed to handle that in a smart manner, it should produce working results without manual intervention.
Well, where they could have used a family-agnostic ipset before, they may need to create two family-specific nft sets now. So some manual adjustments may be needed.

What about adding options for table and table family, as well as the family for the nft set itself?

**Comment by lvqier** [comment]
Can we build nftset feature into package dnsmasq instead of dnsmasq-full?
It is strange that ipset/nftset option presents on DHCP and DNS page while people have to install the dnsmasq-full package to make it work.

**Comment by anomeome** [comment]
dnsmasq bump on master is borked due to previous [commit](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=002a99eccd75fb653163bae0a1132bd4f494e7ad)

**Comment by hauke** [comment]
@jow- @ldir-EDB0  Do you plan to backport this to 22.03?

**Comment by hauke** [comment]
> dnsmasq bump on master is borked due to previous [commit](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=002a99eccd75fb653163bae0a1132bd4f494e7ad)

This was fixed in 41691ce9ac10b3aaaf7c05e6e5b55b626f66949b

**Comment by ldir-EDB0** [comment]
I don't think there's a technical reason not to backport to 22.03 - I don't have the time to do it.

**Pull request closed without merging**
