### PR TITLE
ath79: add empty squashfs-lzma filesystem

### PR DESCRIPTION
**Pull request by aparcar**
The filesystem is currently created on every build to trick the boot loader of some FRITZ! devices into accepting the image. Sadly the resulting squashfs-lzma filesystem is not reproducible. To fix this, create a squashfs filesystem once and include it into the repository.

Creation happend as shown below

    rm -rf empty_dir
    mkdir empty_dir
    ./staging_dir/host/bin/mksquashfs-lzma \
    	empty_dir/ include/empty-squashfs-lzma \
    	-noappend -root-owned -be -nopad -b 65536 -fixed-time 0

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by dhewg** [comment]
If that works and is acceptable you can move the file and function to `target/linux/ath79/image/`.
This isn't the first of its kind too: `target/linux/lantiq/image/eva.dummy.squashfs`. Burried in 0f6a9d5c7c938f40657ca30f588479893606781e

**Comment by aparcar** [comment]
I'll move it over there then

**Comment by dangowrt** [comment]
Can't we generate that empty squashfs *once* and/or fix the reason why it is not reproducible?
Including binaries in the tree should be avoided imho

**Comment by mpratt14** [comment]
im curious in what ways it's not reproducible, is it a timestamp?

**Comment by aparcar** [comment]
@lynxis ideas?

**Pull request closed without merging**
