### PR TITLE
ath10k: update QCA4019 firmware

### PR DESCRIPTION
**Pull request by vort7u**
Update firmware for QCA4019 also for 18.06 branch.
https://github.com/openwrt/openwrt/pull/1138

Signed-off-by: Massimo T. masnia@tiscali.it

### CODE REVIEW

**Comment by hauke** [comment]
master currently uses the version 10.4-3.5.3-00053, but I think it should be save to upgrade to this version even in 18.06.

**Comment by robimarko** [comment]
This one should be stable,even linux-firmware distributes this version

**Comment by mastum** [comment]
@robimarko yes is stable, I've been using it for two months with AVM 4040.

**Comment by chunkeey** [comment]
see #1138 . Merged. Thanks.

**Pull request closed without merging**
