### PR TITLE
lantiq: mark only xrx200 subtarget as source-only

### PR DESCRIPTION
**Pull request by abajk**
The current problems blocking the switch to the kernel 5.15 are related to the GSWIP driver. This driver is only used by the xrx200 subtarget. The other subtargets are unaffected by this problem.

Signed-off-by: Aleksander Jan Bajkowski <olek2@wp.pl>

### CODE REVIEW

**Comment by Ansuel** [comment]
@abajk I have read also another device have a problem with the switch on lantiq? Also can you revert the commit and apply this?

**Comment by abajk** [comment]
> @abajk I have read also another device have a problem with the switch on lantiq?

This problem is not related to the 5.15 kernel. AVM 7320/7330 have had problems since the beginning when they were added to OpenWRT.

> Also can you revert the commit and apply this?

Done.

**Comment by abajk** [comment]
A brief clarification. Currently supported SoCs:
* amazon - does not have a built-in switch. It uses external swconfig switches,
* danube - as above,
* falcon - lacks a driver for ethernet and GPON, disabled for a long time,
* arx100 - integrated 3-port switch (embedded tantos). The driver for DSA is missing. Currently only the first port works, only if the cable is connected during the boot process. This problem affects the AVM7320/7330 and has existed forever. Other devices use external swconfig switches.
* xrx200 - integrated 7-port switch (embedded gswip). There are problems with adding entries to the FDB table.

Translated with www.DeepL.com/Translator (free version)

**Comment by Ansuel** [comment]
> * arx100 - integrated 3-port switch (embedded tantos). The driver for DSA is missing. Currently only the first port works, only if the cable is connected during the boot process. This problem affects the AVM7320/7330 and has existed forever. Other devices use external swconfig switches and are not affected by this problem.

mhhh is the device disabled from creating images? also i bet is the bootloader init stuff if it does detect cable attached...

**Comment by abajk** [comment]
> mhhh is the device disabled from creating images?

The device is not disabled. I think everyone who uses it is aware of the problems that exist.

> also i bet is the bootloader init stuff if it does detect cable attached...

Indeed. The link only works because the bootloader programs the speed and duplex at the boot. I did not debug this problem in the current driver, instead I started writing a [simple DSA driver ](https://github.com/abajk/linux/commit/b7d2ee8cc0438e53e3a48cf92e422a1cbff45dd6#diff-9a20d0e6fbe2403582a3136379cdcb0cb4ebea4a4f79c45a6ce7f61c7fc971f3)for the built-in switch. A lot of things work, but there are still problems with the second lan port hanging during iperf.

**Pull request merged**
