### PR TITLE
kernel: add missing symbol

### PR DESCRIPTION
**Pull request by flyn-org**
See also http://lists.infradead.org/pipermail/openwrt-devel/2020-February/021764.html

Reported by Buildbot:

x86 instruction decoder selftest (X86_DECODER_SELFTEST) [N/y/?] (NEW) aborted!

Fixes: eca8a2ee0d44 ("kernel: bump 4.14 to 4.14.169")
Signed-off-by: Koen Vandeputte <koen.vandeputte@ncentric.com>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Hmm, why do you propose someone else's patch here? (@xback)

**Comment by flyn-org** [comment]
@adrianschmutzler, I believe OpenWrt applied his patch to openwrt-19.07, but not master. I git cherry-picked his work into master.

**Comment by adrianschmutzler** [comment]
Ah, now I see it. It wasn't applied to master since master is on 4.19 already.
Anyway, @xback should decide on this one.

**Comment by hauke** [comment]
This pull request was superseded by this change:
https://patchwork.ozlabs.org/patch/1236420/

**Pull request closed without merging**
