### PR TITLE
kernel: bump 5.15 to 5.15.157

### PR DESCRIPTION
**Pull request by hauke**
* kernel: bump 5.15 to 5.15.156
    
    No manual changes needed.
    
 * kernel: bump 5.15 to 5.15.157
    
    Removed because they are upstream:
       generic/backport-5.15/741-v6.9-01-netfilter-flowtable-validate-pppoe-header.patch
       https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.15.y&id=d06977b9a4109f8738bb276125eb6a0b772bc433
    
    Removed because they are upstream:
       generic/backport-5.15/741-v6.9-02-netfilter-flowtable-incorrect-pppoe-tuple.patch
       https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.15.y&id=e719b52d0c56989b0f3475a03a6d64f182c85b56
    
    Manual adapted the following patches:
       generic/pending-5.15/700-netfilter-nft_flow_offload-handle-netdevice-events-f.patch
       generic/pending-5.15/723-net-mt7531-ensure-all-MACs-are-powered-down-before-r.patch

### CODE REVIEW

**Comment by namiltd** [comment]
missing: NF_FLOW_TABLE_PROCFS

**Comment by Borromini** [comment]
Seeing the following error, looks like those patches were already removed earlier?

```
error: target/linux/generic/backport-5.15/741-v6.9-01-netfilter-flowtable-validate-pppoe-header.patch: does not exist in index
error: target/linux/generic/backport-5.15/741-v6.9-02-netfilter-flowtable-incorrect-pppoe-tuple.patch: does not exist in index
```

**Comment by hauke** [comment]
> `MITIGATION_SPECTRE_BHI`



> Edit: I see a `MITIGATION_SPECTRE_BHI` missing symbol as well on x86/64? Not just `NF_FLOW_TABLE_PROCFS`.

There is no support for x86 with kernel 5.15 in the OpenWrt main branch.

**Comment by Borromini** [comment]
@hauke My bad, sleep deprived. I was testing this on 23.05  already 🤦.

**Pull request merged**
