### PR TITLE
ppp: update to version 2.4.7.git-2018-06-23

### PR DESCRIPTION
**Pull request by sch-m**
This bumps ppp to latest git version.

There is one upstream commit, which changes DES encryption calls from
libcrypt / glibc to openssl.

As long as we don't use glibc-2.28, revert this commit.

Signed-off-by: Martin Schiller <ms@dev.tdt.de>

-------------
Old message about the backport of some commits:

This backports 4 commits from the latest pppd.

The major target of this patches is to make discovery timeouts
and attempts configurable and return immediatly if PADO received
in new quiet mode.

Signed-off-by: Martin Schiller <ms@dev.tdt.de>

### CODE REVIEW

**Comment by jow-** [comment]
Are these backports not part of any pppd release yet?

**Comment by dedeckeh** [comment]
@jow- No they're not; therefore I'm wondering if it does not make sense to switch to the latest version in the pppd git repo (https://github.com/paulusmack/ppp)

**Comment by wongsyrone** [comment]
I would recommend update to its latest git HEAD as it contains various fixes.

I did it in my tree and looks working as expected.

https://github.com/wongsyrone/lede-1/commit/a14fc4e20abcae83904b7ab21ce7302f5df2fcf7
https://github.com/wongsyrone/lede-1/commit/f32eeadfe9d0d9fcc370f709214ed7d9f839c5ed
https://github.com/wongsyrone/lede-1/commit/8753443a30f6213e27f763f0f5bd67318dc20585
https://github.com/wongsyrone/lede-1/commit/44bf31cd0a2e29d7821b1ee989ee8347cb7d6c41

current tree: https://github.com/wongsyrone/lede-1/tree/master/package/network/services/ppp

Feel free to take what you like.

**Comment by sch-m** [comment]
@jow- @dedeckeh Would it be ok, when I create a new PR which will switch pppd from release (tar.gz) PKG_SOURCE to latest git PKG_SOURCE? Doing this may obsolete some of the existing patches as well.

**Comment by dedeckeh** [comment]
@sch-m I discussed this briefly with @jow- ; switching to https://github.com/paulusmack/ppp is fine for us. However there's commit https://github.com/paulusmack/ppp/commit/3c7b86229f7bd2600d74db14b1fe5b3896be3875 which probably will cause some troubles

**Comment by wongsyrone** [comment]
I choose to static link to openssl due to https://github.com/paulusmack/ppp/commit/3c7b86229f7bd2600d74db14b1fe5b3896be3875 .

**Comment by dedeckeh** [comment]
@wongsyrone Static linking to OpenSSL is not really an option for space limited devices. For musl and glibc2.27 we can keep linking to crypt; however if we switch to glibc 2.28 we will have to link to one of the SSL libraries

**Comment by wongsyrone** [comment]
I tested linking to static and shared OpenSSL, the static one can fit in a 4MB flash device, the shared one cannot. It only needs to take DES functions.

**Comment by sch-m** [comment]
Well the DES encryption is used/needed for MS-CHAP and EAP SRP-SHA1.
Is this really used nowadays? I mean, we talk about DES.
Maybe disabling MS-CHAP and EAP SRP-SHA1 support would be also a solution?

**Comment by wongsyrone** [comment]
It changes the functionality and most user doesn't check commit history, it might not work as they expected.

**Comment by sch-m** [comment]
You are right, but sometimes you have to drop some old stuff even if there maybe could be someone who is still using it. We also dropped e.g. old and weak cipher suites in dropbear which maybe were used by someone.

Please understand me right: I don't want to force the removal of this features, but I want to think about it if these are still required.

**Comment by sch-m** [comment]
@dedeckeh I've just found out that we already have some problems/warnings related to this crypto stuff with musl, because <stdlib.h> is not included in pppcrypt.c:

`pppcrypt.c: In function 'DesSetkey':
pppcrypt.c:122:2: warning: implicit declaration of function 'setkey'; did you mean 'DesSetkey'? [-Wimplicit-function-declaration]
  setkey((const char *)crypt_key);
  ^~~~~~
  DesSetkey
pppcrypt.c: In function 'DesEncrypt':
pppcrypt.c:137:2: warning: implicit declaration of function 'encrypt'; did you mean 'crypt'? [-Wimplicit-function-declaration]
  encrypt((char *)des_input, 0);
  ^~~~~~~
  crypt`

**Comment by wongsyrone** [comment]
I asked @dedeckeh several days before, he said planned to [upgrade to glibc 2.28](https://github.com/openwrt/openwrt/commit/1dcaef841017d805501fef19ec57e5a723cf76cd) . The revert openssl patch becomes the glibc upgrade blocker, as long as you stick to 2.27 forever.

**Comment by wongsyrone** [comment]
@sch-m 
BTW, I have a patch to fix implicit function declaration warnings, you can take what you like.

The `999-` prefix means added by me.

https://github.com/wongsyrone/lede-1/blob/master/package/network/services/ppp/patches/999-03-fix-implicit-function-declaration.patch

**Comment by dedeckeh** [comment]
Patch pushed to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=eaaee181d194f8908a70833b3298392622bc5c86); thx

**Pull request closed without merging**
