### PR TITLE
fix totolink x5000r wrong wi-fi 5GHZ mac address

### PR DESCRIPTION
**Pull request by p055877632**
totolink x5000r wi-fi 5GHZ MAC addresses map:

factory 0x8004 : wlan5g MAC addresses

### CODE REVIEW

**Comment by adschm** [comment]
Formal issues:
https://openwrt.org/submitting-patches
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes

Regarding the content, I would like to have an overview of the correct (=desired) assignment in the commit message, like we do for new devices: https://openwrt.org/docs/guide-developer/device-support-policies#mac_addresses

**Comment by neheb** [comment]
Shouldn't this be handled in DTS?

**Comment by adschm** [comment]
> Shouldn't this be handled in DTS?

Depends on whether we actually need to flip the local bit.

**Comment by ptpt52** [comment]
I prefer fix it by change in mt76
https://github.com/openwrt/mt76/pull/476

**Pull request closed without merging**
