### PR TITLE
kernel: use skb_list_del_init in NF_HOOK_LIST

### PR DESCRIPTION
**Pull request by ptpt52**
list_del is invalid use for skb
it cannot make sure skb->next=NULL

### CODE REVIEW

**Comment by ynezz** [comment]
Please [upstream](https://www.kernel.org/doc/html/latest/process/submitting-patches.html) that change first, then backport it to the this tree, thanks.

**Comment by ptpt52** [comment]
@ynezz  hi, I think it is already in upstream, please see new kernel.
and u may go backport it.

**Comment by ynezz** [comment]
>  and u may go backport it.

Rule of thumb in almost every FOSS project: If you want something to happen, you should do it yourself.

**Comment by ptpt52** [comment]
https://github.com/openwrt/openwrt/pull/3200
@ptpt52  backported. In this way?

**Pull request closed without merging**
