### PR TITLE
mbedtls: Update to version 2.28.3

### PR DESCRIPTION
**Pull request by hauke**
This only fixes minor problems.
Changelog: https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.3

The 100-fix-compile.patch patch was merged upstream, see: https://github.com/Mbed-TLS/mbedtls/issues/6243

The code style of all files in mbedtls 2.28.3 was changed. I took a new version of the 100-x509-crt-verify-SAN-iPAddress.patch patch from this pull request: https://github.com/Mbed-TLS/mbedtls/pull/6475

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
ping @gstrauss

**Comment by gstrauss** [comment]
As @hauke noted, the mbedtls team applied a new coding style to mbedtls 3.x and reformatted everything.  They also applied the new coding style and reformatted the 2.28.3 branch.

If @hauke used the mebedtls-team-provided tools to reformat the patch for SAN iPAddress, that is fine.

Since the patch snapshot committed to openwrt, the subsequent incremental changes made to the patch in https://github.com/Mbed-TLS/mbedtls/pull/6475 are for portability to (embedded) systems environments without `inet_pton()`.  Linux has `inet_pton()`.  Once the patch is merged to mbedtls 3.x, I plan to sync up the patch to openwrt for consistency.  The mbedtls team is unfortunately unable to make any progress without 1000+ interrupts.  They may eventually commit the patch, and then they plan to rewrite it with longer variable names and slightly adjusted syntax, but no substantive changes to functionality have currently been communicated.  tl;dr patch works as advertised; mbedtls team continues to be unable to make progress further than navel gazing.

**Comment by gstrauss** [comment]
@hauke when did you last pull the patch from https://github.com/Mbed-TLS/mbedtls/pull/6475 ?

**Comment by hauke** [comment]
I took the recent patches from https://github.com/Mbed-TLS/mbedtls/pull/6475. I did not rebase the the old one. Adapting the existing patch was more work, but I can try to  adapt the "old" patch to the new style.

**Comment by hauke** [comment]
I took this patch: https://github.com/Mbed-TLS/mbedtls/pull/6475/commits/88a795b8dad40a59987175cf349b58813c1e7f94
it is more or less the same as the old one we currently have in OpenWrt. This also adds the ifdefs for windows.

**Comment by gstrauss** [comment]
Thanks, @hauke.  That looks good to me.  https://github.com/Mbed-TLS/mbedtls/commit/88a795b8dad40a59987175cf349b58813c1e7f94 is the latest patch in the series.

FYI: Instead of allowing commits to be edited during review, the mbedtls team generally prefers separate commits for changes requested in review comments  and then makes a mess of the history by not squashing commits.  That's why there are so many commits for what was originally intended to be a tightly scoped PR.

**Comment by gstrauss** [comment]
I manually compared the differences between the patch in this PR and the patchset in https://github.com/Mbed-TLS/mbedtls/pull/6475 .  The patch here contains the important functional additions needed for openwrt.  The patch here does not include the local `inet_pton()` implementation -- which is not needed since Linux has provided inet_pton() for a very long time -- and the patch here does not include the changes added to the mbedtls test framework.

**Comment by hauke** [comment]
@gstrauss Thanks for looking into the patch and explaining the mbedtls process. 
I hope your changes get merged at some point in time into upstream mbedtls.

**Pull request merged**
