### PR TITLE
kernel: add kmod-i2c-designware-pci

### PR DESCRIPTION
**Pull request by ruantu**
add Synopsys DesignWare I2C adapter for PCI driver support.

Signen-off-by: ruantu <625480598@qq.com>

### CODE REVIEW

**Comment by ruantu** [comment]
support Intel Bay Trail platform i2c interface.

**Comment by hauke** [comment]
The i2c-designware-pci.ko module will depend on the i2c-designware-core.ko model, I think that should also be packaged.

**Comment by mkresin** [comment]
> support Intel Bay Trail platform i2c interface.

Please add this information to the commit message. The first question I had while seeing the PR was which target/boards are using the Synopsys DesignWare PCI I2C adapter.

**Comment by ruantu** [comment]
So I decided to put this driver in the target config, because this module and another CONFIG_I2C_DESIGNWARE_PLATFORM are related to the bios settings and depend on ACPI.

**Comment by ruantu** [comment]
The driver depends on the LPSS Mode in the BIOS setting. If it is PCI Mode, it is driven by i2c-designware-pci. If it is ACPI Mode, it is driven by i2c-designware-platform.

**Pull request closed without merging**
