### PR TITLE
kernel: generic backport 6.1: rename mistyped .patch file

### PR DESCRIPTION
**Pull request by antnyfls**
Fixes mistyped patch file **patc** https://github.com/openwrt/openwrt/blob/main/target/linux/generic/backport-6.1/790-49-v6.10-net-dsa-mt7530-provide-own-phylink-MAC-operations.patc

### CODE REVIEW

**Comment by rany2** [comment]
Ping @dangowrt, could this be why it the WAN port is failing on mt7621?

**Comment by ptpt52** [comment]
mark

**Comment by Ansuel** [comment]
@rany2 in theory the extension should not matter everything in the patches directory is assumed and treated as a patch

**Comment by rany2** [comment]
@Ansuel I see, I falsely assumed that the way these patches got applied was roughly `for x in *.patch; do.... `. That's good to know, it would have been painful if this bug was that silly 😅

**Pull request merged**
