### PR TITLE
realtek: adapt patch description to it's current use

### PR DESCRIPTION
**Pull request by PolynomialDivision**
The patch is not doing anymore what the descriptions says. Update it.
@musashino205

### CODE REVIEW

**Comment by musashino205** [comment]
Note: The message in the patch was copied from https://github.com/openwrt/openwrt/commit/9bac1c20b8f39f2e0e342b087add5093b94feaed by https://github.com/openwrt/openwrt/commit/f1f97db627b2f82989a0f97a74bc7a3debd67ecd .

**Comment by PolynomialDivision** [comment]
Is this an ACK? ;)

**Comment by musashino205** [comment]
Yes.

**Comment by PolynomialDivision** [comment]
Ready to be merged @Ansuel ^^

**Pull request merged**
