### PR TITLE
bpftools: update to 5.10.10

### PR DESCRIPTION
**Pull request by guidosarducci**
Use the latest stable kernel since the previous 5.8.x series is EOL.

Also drop the following patches recently accepted upstream:

  * 001-libbpf-ensure-no-local-symbols-counted-in-ABI-check.patch
  * 002-libbpf-fix-build-failure-from-uninitialized-variable.patch
  * 003-bpftool-allow-passing-BPFTOOL_VERSION-to-make.patch
  * 004-v5.9-bpftool-use-only-ftw-for-file-tree-parsing.patch

Signed-off-by: Tony Ambardar <itugrok@yahoo.com>

This has been tested against current master branch using the following architectures, tools, etc: 
- Compile and run-tested using gcc 8.4 on qemu/arm64, qemu/mips32be and EA6350v3/ipq40xx
- Compile-tested using gcc 10.2 on ppc8540

### CODE REVIEW

**Comment by neheb** [comment]
fails with musl 1.2.2:

https://gist.github.com/neheb/51cb36d3d17707303b611ac7d2b2df21

**Comment by guidosarducci** [comment]
Pinging @dangowrt who reviewed a previous update. Appreciate if you could take a look!

**Comment by neheb** [comment]
After adding the patch:

```
make[4]: Leaving directory '/home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/tools/lib/bpf'
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/btf.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/btf_dumper.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/cfg.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/cgroup.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/common.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/feature.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/gen.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/iter.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/json_writer.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/link.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/main.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/map.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/map_perf_ring.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/net.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/netlink_dumper.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  CC       /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/perf.o
cc1: note: someone does not honour COPTS correctly, passed 2 times
  LINK     /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/bpftool-bootstrap
  GEN      /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/vmlinux.h
/bin/sh: /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/bpftools-full/bpftools-5.10.9/bpftool-bootstrap: cannot execute binary file: Exec format error
```

**Comment by guidosarducci** [comment]
@neheb Hi Rosen, given you have PR https://github.com/openwrt/openwrt/pull/3004 for your WIP on a future musl-1.2.x, let's keep related notes and patches there to avoid confusion. I've already commented in that thread on needing to understand root causes, how best to upstream any fixes, and making some time to reproduce. But none of that affects OpenWRT master branch.

> fails with musl 1.2.2:
> 
> https://gist.github.com/neheb/51cb36d3d17707303b611ac7d2b2df21

And that's fine isn't it, since this PR targets OpenWRT master and currently supported archs/tools i.e. musl-1.1.x?

**Comment by neheb** [comment]
Sure

**Comment by guidosarducci** [comment]
Updated kernel to 5.10.10 just released. Note that `libbpf` and `bpftool` sources haven't changed.

Recently learned @blogic is also experimenting with eBPF, so pinging as interested party/possible reviewer.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
