### PR TITLE
mpc85xx: switch default kernel to 5.15

### PR DESCRIPTION
**Pull request by PolynomialDivision**
The default kernel should be switched to 5.15 in order to enable testing by a broader audience.

Tested on TP-Link TL-WDR4900 v1.

### CODE REVIEW

**Review by BKPepe — APPROVED** [review]
Let's do this even though we could remove the kernel files for 5.10 to force it even more as kernel 6.1 was marked as LTS release.

**Comment by PolynomialDivision** [comment]
> Let's do this even though we could remove the kernel files for 5.10 to force it even more as kernel 6.1 was marked as LTS release.

Some people prefer to remove the legacy files in a separate commit some days/weeks after the default kernel was switched. That's why I did not remove the old files.

**Comment by PolynomialDivision** [comment]
ping @Ansuel

**Comment by aparcar** [comment]
Merged, thanks!

**Pull request closed without merging**
