### PR TITLE
build/json: generate json file for initramfs

### PR DESCRIPTION
**Pull request by aparcar**
The initramfs images are missing from the profiles.json files.

Signed-off-by: Moritz Warning <moritzwarning@web.de>
[fix code by exporting device variables]
Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
@mwarning please test this asap and I'll backport it to 21.02

**Comment by dangowrt** [comment]
Would be nice to not duplicate the list of exported device variables. Can't this be abstracted into some way it can be reused for both, normal filesystem images as well as initramfs images?

**Comment by aparcar** [comment]
I don't understand how how the creation of initramfs and regular images is different, just that they use different levels of `make`. I couldn't find a better solution and @nbd168 suggested to add the export. I'm sure there is a better way but I'm lost.

**Comment by dangowrt** [comment]
> I don't understand how how the creation of initramfs and regular images is different, just that they use different levels of `make`. I couldn't find a better solution and @nbd168 suggested to add the export. I'm sure there is a better way but I'm lost.

Maybe something like
```
define device-export-json-vars 
	DEVICE_ID="$$(1)" \
	BIN_DIR="$$(BIN_DIR)" \
	SOURCE_DATE_EPOCH=$$(SOURCE_DATE_EPOCH) \
	IMAGE_NAME="$$$$(notdir $$$$^)" \
	IMAGE_PREFIX="$$(IMAGE_PREFIX)" \
	DEVICE_VENDOR="$$$$(DEVICE_VENDOR)" \
...
endef
```
and then call this in both places?

**Comment by mwarning** [comment]
> @mwarning please test this asap and I'll backport it to 21.02

The patch works for me so far (OpenWrt master, ipq40xx/generic AVM FritzBox 4040).

**Comment by aparcar** [comment]
As discussed with @mwarning and @dangowrt this is merged and backported now, future iteration beautify the code but this should be part of 21.02.

**Comment by adschm** [comment]
I hope you still have overview over all this json creation stuff which gets bigger and bigger every time. I've lost track completely already a while ago.

**Comment by aparcar** [comment]
I hope you keep track of all those DTS file changes, i lost track a while ago ;)

But sure, I'll write a document describing the files.

**Comment by mwarning** [comment]
Afaik, all changes are two chunks in the makefiles (for initramfs and the other images) and two python scripts (one create json files, the other to merge them into one).

**Comment by dangowrt** [comment]
This was merged.

**Pull request closed without merging**
