### PR TITLE
[RFC] ath79: add read support using spi-mem

### PR DESCRIPTION
**Pull request by luizluca**
kernel 4.18 dropped fast flash interface (torvalds/linux@cfd12db4f12383506ca81fddd0f20921f166afd0) in favor to a new generic [spi-mem](https://bootlin.com/blog/spi-mem-bringing-some-consistency-to-the-spi-memory-ecosystem/) interface. During upgrade from 4.14 and 4.19, the [fast_flash patch](https://github.com/openwrt/openwrt/blob/3771176c9ef9b5d231e9019bc0c872dbe3617209/target/linux/ath79/patches-4.14/461-spi-ath79-add-fast-flash-read.patch) was dropped from openwrt (3771176c9ef9b5d231e9019bc0c872dbe3617209). This resulted in slower read speed for some devices while it also uncovered a possible hardware bug with tplink,tl-wr2543-v1.

This patch was tested with tplink,tl-wr2543-v1, with 3x speed up and tplink,archer-c7-v2 with no speed up (after adding m25p,fast-read).

### CODE REVIEW

**Comment by olek210** [comment]
1. Ath79 has [now](53ab9865c2b91bc6a239b2adee800dc52875b6bc) support for kernel 5.4. Maybe add this patch also to patches-5.4.
2. Does this patch reduce CPU load on Archer C7 when reading spi memory?

**Comment by 981213** [comment]
> 2. Does this patch reduce CPU load on Archer C7 when reading spi memory?

No. ar933x and later SoCs use a different driver since:

ebf0d8dade ath79: add new ar934x spi driver

**Comment by neheb** [comment]
```
git grep fast-read
dts/ar7161_buffalo_wzr-hp-ag300h.dts:           m25p,fast-read;
dts/ar7161_buffalo_wzr-hp-ag300h.dts:           m25p,fast-read;
```

```
It accelerate only fast-read op reading flash directly from
memory mapped region. 'm25p,fast-read' must be set in order
to use the new spi-mem.
```

hmmmm....

**Comment by luizluca** [comment]
> No. ar933x and later SoCs use a different driver since:

@981213 , I was suspicious that was happening as it never printed any debug log I added. I was going to check that hypothesis. You just save me some precious time. 

> hmmmm....

@neheb , this was suggested by @981213 because the memory mapped access is doing a fast-read. I would "accelerate" normal read ops if the code also intercepted normal read op reaching the same performance even without 'm25p,fast-read'.

The good side is that only those devices with 'm25p,fast-read' might have a regression.

I'll update soon this PR to add the patch also to patches-5.4. I will not conflict as I wrote it based on linux-next.

**Comment by neheb** [comment]
*digs*

Looks like I have a WR1043ND that probably applies to this. Will test.

**Comment by neheb** [comment]
Hmm the compatible field for ar9132 has qca,ar9132-spi in it. I can't see any reference to that anywhere.

**Comment by neheb** [comment]
Before:

```
root@OpenWrt:~# time cat /dev/mtdblock1 > /dev/null
real    0m 10.03s
```

After:

```
root@OpenWrt:~# time cat /dev/mtdblock1 > /dev/null
real    0m 3.16s
```

Throw in the tl_wr1032ndv1 as well.

**Comment by ynezz** [comment]
> Maybe add this patch also to patches-5.4.

Yep, I would focus only on 5.4 as well, there (probably) wont be any release with 4.19.

**Comment by luizluca** [comment]
I did some testing with 5.4. Using a serial interface, I could test tl-wt2543nd and it worked nicely. 

For 5.4, I needed to replace (based on linux-next previous commits):

```
if (mem->spi->chip_select || gpio_is_valid(mem->spi->cs_gpio))
```

with

```
if (mem->spi->chip_select || mem->spi->cs_gpiod)
```

I'm not sure it is correct.

I also tested a tl-wr1043nd-v1 but only for 4.19 as I don't have a serial interface ready for it. I added a new commit enabling fast-read.

Ethernet for linux-5.4 does not seem to be still in a very good shape for target ath79. For tl-wr2543nd, It got no ethernet interface (even without my patch):

``` 
[    2.847887] ag71xx: probe of 19000000.eth failed with error -2
```

tl-wrd4300, which does not use the driver touched by this patch, had very unstable network too, with a lot of packet loss. I could barely run uname. I'm doing a clean build to test if it was something from a previous kernel. However, this is off-topic for this PR.

**Comment by luizluca** [comment]
> I'm doing a clean build to test

Same for a clean built. Anyway, the patch is good for both 4.19 and 5.4.

**Comment by 981213** [comment]
Merged into my staging tree at: https://git.openwrt.org/?p=openwrt/staging/981213.git
Thanks!

**Pull request closed without merging**
