### PR TITLE
base-files: add option to set LED brightness

### PR DESCRIPTION
**Pull request by testuser7**
Add option to set LED brightness via uci:

```
config led 'led_blue'
        option name 'blue'
        option default '1'
        option sysfs 'blue:status'
        option brightness '1'
```

### CODE REVIEW

**Comment by raenye** [comment]
Which devices benefit from this, BTW?

**Comment by testuser7** [comment]
> Which devices benefit from this, BTW?

Devices based on NXP PCA9633 LED controller (e.g. Linksys Velop routers).

**Comment by blogic** [comment]
merged, Thanks !

**Comment by testuser7** [comment]
@blogic Did you accidentally close a PR without merging commits?

**Comment by blogic** [comment]
its still in my local staging, will push during the day

**Comment by blogic** [comment]
https://github.com/openwrt/openwrt/issues/17269
https://github.com/openwrt/openwrt/commit/3c7134fa320b823ab7c5f91dd1ad948491d97478

**Pull request closed without merging**
