### PR TITLE
bcm27xx: add CPU_FREQ_GOV_SCHEDUTIL

### PR DESCRIPTION
**Pull request by graysky2**
I am not sure why schedutil was excluded from the default kernel config as it is included many ARM distros so build schedutil governor for this platform.

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Review by rsalvaterra — APPROVED** [review]
I wonder if `CPU_FREQ_GOV_SCHEDUTIL` should just be moved to the generic kconfig. It should be the default, nowadays, for targets which have CPU frequency scaling. Are the removed ksyms result from a `make kernel_oldconfig`? Anyway, the changes are fine.

**Comment by graysky2** [comment]
@rsalvaterra - I do not disagree with you regarding a global default.  I found it interesting though that `bcm2708` did not offer an option for it when I refreshed it.  I guess that if unsupported, a global change would simply not show up in unaffected targets?

**Comment by Noltari** [comment]
@graysky2 you're right, this was missed when support for bcm2709, bcm2710 and bcm2711 targets was added in the past.
Upstream RPi configs have this enabled:
- https://github.com/Noltari/rpi-linux/blob/dff79e31c3b05a50f725442c1fc19a6194491523/arch/arm/configs/bcm2709_defconfig#L51
- https://github.com/Noltari/rpi-linux/blob/dff79e31c3b05a50f725442c1fc19a6194491523/arch/arm/configs/bcm2711_defconfig#L51

RPi configs don't have this enabled:
- https://github.com/Noltari/rpi-linux/blob/dff79e31c3b05a50f725442c1fc19a6194491523/arch/arm/configs/bcm2835_defconfig#L43
- https://github.com/Noltari/rpi-linux/blob/dff79e31c3b05a50f725442c1fc19a6194491523/arch/arm/configs/bcmrpi_defconfig#L46

**Comment by Noltari** [comment]
Merged in 0ffb6deaaaf01a3c79e0e9540770b74fad55695d.
Thanks!

**Pull request closed without merging**
