### PR TITLE
build: fixup 9534357 v2

### PR DESCRIPTION
**Pull request by mayli**
Cherry Picked from
https://git.openwrt.org/?p=openwrt/staging/nbd.git;a=commit;h=921d4500825f837335f998656f0bb88ef0920d55

Related discussion
https://github.com/openwrt/openwrt/pull/3520
https://github.com/openwrt/openwrt/pull/3520#issuecomment-712410237

### CODE REVIEW

**Comment by aparcar** [comment]
:popcorn:

**Comment by adschm** [comment]
Have you asked @nbd168 whether you are allowed to submit those here?

**Comment by mayli** [comment]
@nbd168 ping?

**Comment by aparcar** [comment]
I thinks this is now already applied? https://github.com/openwrt/openwrt/commit/a4c1c169c391ac0b11e4c3e895b282f07585347c

**Pull request closed without merging**
