### PR TITLE
armvirt: rename to 'armsr'

### PR DESCRIPTION
**Pull request by mcbridematt**
As discussed in https://github.com/openwrt/openwrt/pull/12817#issuecomment-1578358211

The story so far:
* armvirt now runs on real hardware, not just QEMU, thanks to EFI support.
Including Ten64, Synquacer, i.MX8+ boards, AWS Graviton instances (VM and bare-metal)
The next generation of SoC's like STM32MP2 and i.MX9 will likely land here rather than on individual targets.

* It has been suggested that the name should be changed before 23.05 release, otherwise there will be confusion later on

* The easiest way to do this is to rename the whole armvirt target (32+64 bit).
Moving arm64 into it's own target is a possibility, but then we would end up unwinding some of the changes made for EFI
To be honest, having the 32-bit subtarget is not a big burden.

* I proposed `armsr` (Arm SystemReady) as the new target name
I am open to other suggestions.

Also open to suggestions on:
```
BOARDNAME:=Arm SystemReady compatible (EFI)
```

### CODE REVIEW

**Comment by ynezz** [comment]
Thanks for pushing it forward.

> If a future CPU specification justifies it's own profile, it could be named armv9 or similar.

We currently can't rule out `armv9` specific subtarget, so I'm really in favor of yours/@dangowrt proposals, thus would probably go with:

> git mv target/linux/armsr/32 target/linux/armsr/armv7 # other options: arm32, aarch32
> git mv target/linux/armsr/64 target/linux/armsr/armv8 # other options: generic, arm64, aarch64 

Considering all the options and `armv9` we would end up with following subtargets:

* 32, 64, armv9
* arm32, arm64, armv9
* aarch32, aarch64, armv9
* armv7, armv8, armv9

So IMO we've a clear winner in `armv7, armv8, armv9` as its more consistent (we've already `layerscape/armv7` and `rockchip/armv8` subtargets).

**Comment by mcbridematt** [comment]
Pull request updated.
As discussed, subtarget names changed:
```
32 => armv7
64 => armv8
```
BOARDNAME is now `Arm SystemReady (EFI) compliant`

**Comment by mcbridematt** [comment]
Fixed two remaining `armvirt` references:
- scripts/qemustart
- GitHub CI autolabeller

There are a small number of references (like `DEPENDS:=@TARGET_armvirt`) in the OpenWrt package feeds. I will open a pull request for those once the name change is merged.

**Comment by ynezz** [comment]
Merged in 3df01b1aa40a8e783dbbebdbe6088a49aed186f8, thanks!

**Pull request closed without merging**
