### PR TITLE
bcm27xx: add Raspberry Pi 5 support

### PR DESCRIPTION
**Pull request by Noltari**
Adds new bcm2712 subtarget for Raspberry Pi 5.

### CODE REVIEW

**Comment by PocketMiner82** [comment]
Hi @Noltari, I tried out this new subtarget and it seems like this only works on a microSD card. I tried to flash OpenWRT to a USB stick and changed the cmdline.txt to `console=serial0,115200 console=tty1 root=/dev/sda2 rootfstype=squashfs,ext4 rootwait`. I then tried to boot the Raspberry PI 5 but it is stuck at `Waiting for root device /dev/sda2...`. It seems like that the USB kernel driver doesn't get loaded, because if i connect or disconnect e. g. a keyboard or another USB stick, no messages pop up on the screen. Also, if I boot from a microSD card, I can see that USB host controllers get discovered and if I connect a keyboard then, i see the usual USB connected messages, but only AFTER the root partition is mounted...
I used the default configuration to compile openwrt, only changed the target to bcm2712.

**Comment by Noltari** [comment]
> Hi @Noltari, I tried out this new subtarget and it seems like this only works when booting from a microSD card.
> 
> I tried to flash OpenWRT to a USB stick and changed the cmdline.txt to `console=serial0,115200 console=tty1 root=/dev/sda2 rootfstype=squashfs,ext4 rootwait`. I then tried to boot the Raspberry PI 5 but it is stuck at `Waiting for root device /dev/sda2...`.
> It seems like that the USB kernel driver doesn't get loaded, because if i connect or disconnect e. g. a keyboard or another USB stick, no messages pop up on the screen.
> Also, if I boot from a microSD card, I can see that USB host controllers get discovered and if I connect a keyboard, i see the usual USB connected messages, but only AFTER the root partition is mounted...
> 
> I used the default configuration to compile openwrt, only changed the target to bcm2712.

Thanks for reporting that @PocketMiner82, I will take a look into it.
TBH I didn't test booting from USB since, sorry for that :(

**Comment by Noltari** [comment]
@PocketMiner82 can you test if this branch fixes the issue?
https://github.com/Noltari/openwrt/commits/bcm2712-usb-config
(I don't know when I'll have time to test it myself, it might take me a couple of days or more)

**Comment by PocketMiner82** [comment]
@Noltari It is working now. Thank you for the fast responding.

**Comment by Noltari** [comment]
> @Noltari That branch is working. Thank you for the fast response.

Thanks! I will merge it later today :)

**Pull request merged**
