### PR TITLE
target: add ARM server (EFI) target 

### PR DESCRIPTION
**Pull request by mcbridematt**
Revised version of lede-project/source#1609
Changes:
- Fix make complaining about qemu dependencies being overwritten
- Add sysinfo support (via DMI, as with x86)
- Add missing CONFIG_CRYPTO_DEV_CAVIUM_ZIP symbol that was introduced in the mean time

-----------------------------
This patch series adds an 'armserver' target, for ARM machines that use EFI to boot.

These machines are generally server machines (Centriq, ThunderX, X-Gene etc.) that comply with the ARM Server Base System requirements (using ACPI).

There is also a newer ARM Embedded Boot Spec which mandates a small set of EFI services with ACPI or DT, i.e u-boot's bootefi

GRUB2 is used as the bootloader, similar to x86, but with GPT as the disk label format.

These binaries will also work under QEMU and KVM with an EDK2 BIOS file, see https://gist.github.com/mcbridematt/2e45073a0a2a489d379c7b33c6019d91 for a boot log.

Tested:
- qemu-system-aarch64 on x86, -cpu cortex-a57 -M virt
- qemu-system-aarch64 on aarch64, -cpu host -M virt (NXP LS1043)
- Traverse LS1043V board with u-boot 2018.01-rc2 (GRUB test only, this machine requires a slightly different configuration - out of scope for this patch)

I based this target on armvirt but I think having a distinct armserver target is better as the ARM server/EFI target needs to support all possible hardware in the kernel for aarch64.

Two points of note:
- The boot partition for EFI must be FAT32, which has a minimum size of 32MB (for 512b sector disks), I have set the kernel partition size to 48MB on TARGET_armserver to ensure this requirement is met (mkfs.fat may not generate FAT32 if the specified size is on or around 32MB)
- This patch also introduces QCOW2 image generation, for convenience. x86 generates vdi and vmdk images but qcow2 is the prevalent aarch64 image type among other distributions (Fedora, Ubuntu)
- This target uses 4.14

### CODE REVIEW

**Comment by alive4ever** [comment]
You may drop my name from the sign-off line, so that the DCO passes. I just modify it a little and sent it to lede-dev to get some attention.

The gptfdisk makefile is based on @sduponch [work](https://github.com/openwrt/openwrt/blob/ab84c90e329cc95cf51ffd838af5dc43b3d539de/tools/gptfdisk/Makefile).

**Comment by mcbridematt** [comment]
Pull commits have been refreshed, no changes apart from the Signed-off-by change mentioned above.
Precompiled binaries here: https://gitlab.com/traversetech/openwrt-armvm-uefi/-/jobs/51025405/artifacts/browse/bin/targets/armserver/64/

**Comment by alive4ever** [comment]
The combined-ext4.img boots.
I suggest adding ``efi_gop`` module to grub, so that grub menu can be displayed on the efi framebuffer device.

**Comment by alive4ever** [comment]
Shouldn't armvirt toolchain works for this purpose, i.e. compiling grub?

I think adding uefi bootable image support to armvirt via image configuration is better for the build-system instead of adding a new armserver target, which only duplicates the armvirt toolchain.

For grub, there should be a grub-efi sub-package which add ``--with-platform=efi`` during ``./configure``, so it would be portable to other platform, i.e. x86

**Comment by mcbridematt** [comment]
I thought about that, my first attempts were layering the grub setup onto armvirt.
There is no difference in toolchain between armserver/64 and other aarch64 targets.
(I've left 32-bit ARM out of this target, as there are no 32-bit ARM server/EFI machines on the market, the non-ARM server cores don't even implement Aarch32 backwards compatibility.)

Once possible reason not to put it in armvirt is if EFI or related (SMBIOS, DMI etc.) services are demanded by the armserver target, for example the sysinfo support in this changeset uses DMI to get the machine name, other ARM targets would do this by looking for the device tree.

**Comment by alive4ever** [comment]
There is grub-efi packaged on [Jow staging repository](https://git.openwrt.org/?p=openwrt/staging/jow.git;a=summary).

You might want to wait for Jow staging repository to get merged into master before making changes, either new armserver target or modify armvirt target to spit openwrt-*uefi-gpt.img

**Comment by blogic** [comment]
looks like the PR stalled with very little interest. if you still think that it should be merged, please give it another shot. Sorry ...

**Pull request closed without merging**
