### PR TITLE
libbsd: fix libpath not to use host path

### PR DESCRIPTION
**Pull request by xuefer**
fix perl build issue posted at openwrt/packages/issues/19390
"ld: cannot find /usr/lib/libbsd.so.0.11.6: No such file or directory"

Signed-off-by: Xuefer <xuefer@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
ping @Ansuel

**Comment by hauke** [comment]
Please add a comment on top of package/libs/libbsd/patches/001-fix-libpath.patch
did you send this patch to the upstream libbsd project too?  We prefer if the patches are getting send upstream so OpenWrt can remove the later when we update to a more recent version of the library again.

Please add this tag to the commit message:
`Fixes: #19390`

**Comment by hauke** [comment]
Please use your full name as author and in the Signed-off-by line.

**Comment by Ansuel** [comment]
@xuefer also pls follow the pattern

```
commit title

commit description

Fixes
Sob
```

**Comment by hauke** [comment]
Thank you for the patch, I merged it into master in ab31547df06430798e6adb853a7faab13eb1754c. I do not know why github did not automatically close this pull request.

**Comment by xuefer** [comment]
Thanks, let's close this

**Pull request closed without merging**
