### PR TITLE
kernel: improve config handling of IO_URING and DYNAMIC_DEBUG

### PR DESCRIPTION
**Pull request by guidosarducci**
This includes changes in handling two kernel config settings with notable impact to kernel sizes:

1. Kernel setting CONFIG_IO_URING supports high-performance I/O for file access and servers, generally for more performant platforms, and adds ~45 KB to kernel sizes. The need for this on less "beefy" devices is questionable, as is the size cost considering many platforms have kernel size limits which require tricky repartitioning if outgrown. The size cost is also large relative to the ~180 KB bump expected between major OpenWRT kernel releases. 

   No OpenWrt packages have hard dependencies on this; samba4 and mariadb can take advantage if available (+KERNEL_IO_URING:liburing) but otherwise build and work fine.

   Since CONFIG_IO_URING is already managed via the KERNEL_IO_URING setting in Config-kernel.in (default Y), remove it from those target configs which unconditionally enable it, and update the defaults to enable it conditionally only on more powerful 64-bit x86 and arm devices. It may still be manually enabled as needed for high-performance custom builds.

2. Since CONFIG_DYNAMIC_DEBUG is already managed via the KERNEL_DYNAMIC_DEBUG setting in Config-kernel.in (default N), remove or disable it in target configs which unconditionally enable it, along with the related setting CONFIG_DYNAMIC_DEBUG_CORE. This saves several KB in the kernels for ipq40xx, ipq806x, filogic, mt7622, qoriq, and sunxi.

These changes were investigated and [mentioned](https://github.com/openwrt/openwrt/pull/11405#issuecomment-1336569959) during development of #11405 , and [requested](https://github.com/openwrt/openwrt/pull/11405#issuecomment-1361496681) as a follow-up PR. They have been build- and run-tested on malta/be32, including the mariadb and samba4 packages. These commits together reduced LZMA kernel size by ~50 KB.

(Note: while working on #11405 , these changes alone would have avoided the need to repartition the ipq40xx device, and there are a number of related changes e.g. see the WIP at https://github.com/guidosarducci/openwrt/commits/master-clean-configs)

Please have a look and comment @hauke and @Ansuel .

### CODE REVIEW

**Comment by Ansuel** [comment]
@guidosarducci i like this change. Maybe for rockchip we can also enable by default, should not be a small flash target and afaik many board are used for file sharing in mind

**Comment by guidosarducci** [comment]
> @guidosarducci i like this change. Maybe for rockchip we can also enable by default, should not be a small flash target and afaik many board are used for file sharing in mind

@Ansuel Hi Christian, since rockchip has `ARCH:=aarch64` it will be enabled by default. Are you OK with this otherwise?

The rationale for `default y if (x86_64 || aarch64)` is that these are likely "desktop-class" systems, lacking kernel-size limitations, and with OK memory, CPU, and HW I/O specs... i.e. not really the HPC platforms pumping 2GB/s I/O where `IO_URING` shines, but likely still the best performing OWRT devices.

**Comment by Ansuel** [comment]
@guidosarducci oh ok! Yep I already got your logic before by looking at the change and it totally correct!

LGTM. If no one have anything against this in a few days i will merge this!

**Comment by guidosarducci** [comment]
Thanks! For reference, these would be the targets enabled by default:
```
$ git grep -E "ARCH:=aarch64|ARCH:=x86_64" target/linux
target/linux/armvirt/64/target.mk:ARCH:=aarch64
target/linux/bcm27xx/bcm2710/target.mk:ARCH:=aarch64
target/linux/bcm27xx/bcm2711/target.mk:ARCH:=aarch64
target/linux/bcm4908/Makefile:ARCH:=aarch64
target/linux/ipq807x/Makefile:ARCH:=aarch64
target/linux/layerscape/armv8_64b/target.mk:ARCH:=aarch64
target/linux/mediatek/filogic/target.mk:ARCH:=aarch64
target/linux/mediatek/mt7622/target.mk:ARCH:=aarch64
target/linux/mvebu/cortexa53/target.mk:ARCH:=aarch64
target/linux/mvebu/cortexa72/target.mk:ARCH:=aarch64
target/linux/octeontx/Makefile:ARCH:=aarch64
target/linux/rockchip/armv8/target.mk:ARCH:=aarch64
target/linux/sunxi/cortexa53/target.mk:ARCH:=aarch64
target/linux/uml/Makefile:ARCH:=x86_64
target/linux/x86/64/target.mk:ARCH:=x86_64
```

**Comment by Ansuel** [comment]
I'm not really sure for the bcm targets... no idea they were aarch64 honestly... Anyway I would wait what @hauke think about this and then i will merge... We have also the other cleanup to merge so lots of fun stuff to change

**Comment by guidosarducci** [comment]
Sure, it was @hauke who requested the PR when I suggested this change, so would like to hear from him too. BTW, those BCM targets cover things like Raspberry Pi and Netgear R8000p, which seem appropriate. 

> We have also the other cleanup to merge so lots of fun stuff to change

Oooh, what cleanup is that? Good cleanups don't get the attention they deserve in my experience...

**Comment by guidosarducci** [comment]
Ping @Ansuel . Any success with feedback from @hauke ? I haven't run into him on IRC myself. And the cleanup you mentioned?

**Comment by Ansuel** [comment]
@guidosarducci i'm ok with merging this, but i can rebase for you. Can you rebase on top of master?

**Comment by guidosarducci** [comment]
@Ansuel Thanks! I've rebased on master... Repeating the checks will take some time however.

**Pull request merged**
