### PR TITLE
ramips: fix 2.4GHz WLAN issue for TL-WR902AC v4

### PR DESCRIPTION
**Pull request by DragonBluep**
Please backport it to the branch v24.

### CODE REVIEW

**Comment by 981213** [comment]
The commit title can be more descriptive: ramips: fix 2.4G wifi eeprom offset for TL-WR902AC v4

**Comment by DragonBluep** [comment]
> The commit title can be more descriptive: ramips: fix 2.4G wmac eeprom offset for TL-WR902AC v4

Updated. Thanks.

**Comment by namiltd** [comment]
According to https://github.com/openwrt/openwrt/issues/13969 the fix should also be backported to branch 23.05.

**Comment by DragonBluep** [comment]
> According to #13969 this patch should also be backported to branch 23.05.

This device (TL-WR902AC v4) was not backported to the v23 branch. ref:
https://git.openwrt.org/?p=openwrt%2Fopenwrt.git&a=search&h=refs%2Fheads%2Fopenwrt-23.05&st=grep&s=TL-WR902AC+v4

**Pull request merged**
