### PR TITLE
Backport GitHub Actions for OpenWrt 21.02

### PR DESCRIPTION
**Pull request by BKPepe**
I backported all relevant commits regarding CI from OpenWrt master branch to OpenWrt 21.02

Fixes: https://github.com/openwrt/openwrt/issues/10980

### CODE REVIEW

**Comment by Ansuel** [comment]
@BKPepe wait can we split this and limit it to formalities? we need extra care for the tools container, a run from the the 21.02 branch would result in overwriting the container tools... since it was experimental we still have to add support to build it to per branch

**Comment by Ansuel** [comment]
btw @BKPepe we also need some additional commits that CI depends on
https://github.com/Ansuel/openwrt/commits/openwrt-21.02
everything after CI per branch.... commit needs to be backported as well...

Also we should decide if we should use stable external toolchains instead of using snapshot for everything.

**Comment by Ansuel** [comment]
Ok this is fun... i think we have some broken target on 21.02?

https://github.com/Ansuel/openwrt/actions/runs/3559941425
https://github.com/Ansuel/openwrt/actions/runs/3559941427

fun stuff

**Comment by Ansuel** [comment]
Ok in theory i should have added support for creating a tools container specific to the branch and using release toolchain instead of snapshot. Currently testing... but we need a few commit to backport to make everything working. they are only related to CONFIG_AUTORELEASE and EXTERNAL_TOOLCHAIN so they should not be problematic.

**Comment by Ansuel** [comment]
@BKPepe i still have to test some small thing and tweak others anyway many commits are missing from this...
Tell me how we want to proceed. If you want i can like what is needed
https://github.com/openwrt/openwrt/pull/11391

**Comment by neheb** [comment]
As far as backporting CI stuff to 21.02 and 22.03, ACK.

It has already found problems before even being merged.

**Comment by hauke** [comment]
I had to fix multiple problems in master to get the " Build all core packages" to pass. I think I ported all fixes back to openwrt-22.03. I fixed the problems in #10396, but this also contains more fixes.

**Comment by Ansuel** [comment]
@BKPepe i posted all the required changes here https://github.com/openwrt/openwrt/pull/11414 think you can rebase this and limit it to CI commits.

**Comment by Ansuel** [comment]
@BKPepe last thing to rebase this...

But you need to add some extra commit.

You can check here the missing one. 
https://github.com/Ansuel/openwrt/pull/5/commits

**Pull request merged**
