### PR TITLE
ipq806x: compile in schedutil governor

### PR DESCRIPTION
**Pull request by graysky2**
Add schedutil for CPU freq scaling but leave ondemand enabled by default

Gives users a third option to augment ondemand and performance.  Kernel
docs[1] explain differences and this PR empowers users w/ the choice to
select between the older ondemand and newer and more simplistic schedutil
should they wish to use one that is not the performance governor.

1. Documentation/admin-guide/pm/cpufreq.rst

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by ynezz** [comment]
Missing commit description.

**Comment by graysky2** [comment]
@ynezz - Edited.  Let me know if more is needed.

**Comment by ynezz** [comment]
No, you're editing PR description, not commit description https://github.com/openwrt/openwrt/pull/3183/commits/4b0996b2249728cd012cceda2a35798d1ae69dae

**Comment by graysky2** [comment]
> No, you're editing PR description, not commit description 4b0996b

Got it, my mistaken.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
