### PR TITLE
Layerscape: update kernel/packages to NXP LSDK 19.03

### PR DESCRIPTION
**Pull request by yangbolu1991**
NXP had announced Layerscape OpenWrt 19.04 release, whose code base was below 3/27/2019 commit of OpenWrt mainline. The release was all using NXP LSDK 19.03 release kernel and components.

2892033 wireguard: introduce 'nohostroute' option

The patches of this pull request were all from Layerscape OpenWrt 19.04, with cleaning up and dropping some patches non-upstreamble I think.

NXP LSDK site:
https://www.nxp.com/support/developer-resources/run-time-software/linux-software-and-development-tools/layerscape-software-development-kit-v19.03:LAYERSCAPE-SDK
NXP source code:
https://lsdk.github.io/components.html
NXP OpenWrt source code:
https://source.codeaurora.org/external/qoriq/qoriq-components/openwrt/

BTW, I'd like to introduce NXP Edgescale client for edge computing, although I had dropped related patches in the pull request. I'd like to know whether such client for edge computing is welcomed for OpenWrt/packages.
Here is more detail about Edgescale.
https://www.nxp.com/support/developer-resources/run-time-software/linux-software-and-development-tools/edgescale-for-secure-edge-computing:EDGESCALE?lang=en&lang_cd=en&
Edgescale user guide for NXP OpenWrt-19.04
https://source.codeaurora.org/external/qoriq/qoriq-components/openwrt/tree/package/network/services/eds/README?h=integration

Thanks a lot.

### CODE REVIEW

**Comment by yangbolu1991** [comment]
Rebased patches, since below openwrt commit just caused conflicts several minutes ago.
07720c392f kernel: bump 4.14 to 4.14.115

**Comment by yangbolu1991** [comment]
Rebased patch-set to resolve conflicts.

**Comment by yangbolu1991** [comment]
Any comments?
Thanks!

**Comment by yangbolu1991** [comment]
@hauke @blogic 
Hi Hauke and John, hope for your comments on this.
I have to always rebased these patches before reviewing and merging.
Thanks a lot.

**Comment by yangbolu1991** [comment]
Rebased to resolve conflicts.

**Comment by ynezz** [comment]
@mcbridematt could you please check this? I've noticed, that it touches some traverse stuff, thanks.

**Comment by mcbridematt** [comment]
Apologies for the wait, it looks like it breaks USB/XHCI on our (LS1043) board:
```
[    5.624294] xhci-hcd xhci-hcd.2.auto: new USB bus registered, assigned bus number 5
[    5.632200] xhci-hcd xhci-hcd.2.auto: hcc params 0x0220f66d hci version 0x100 quirks 0x0000002002010810
[    5.641605] xhci-hcd xhci-hcd.2.auto: irq 51, io mem 0x03100000
[    5.655575] xhci-hcd xhci-hcd.2.auto: xHCI Host Controller
[    5.661100] xhci-hcd xhci-hcd.2.auto: new USB bus registered, assigned bus number 6
[    5.668759] xhci-hcd xhci-hcd.2.auto: Host supports USB 3.0  SuperSpeed
[   12.839614] xhci-hcd xhci-hcd.1.auto: Error while assigning device slot ID
[   12.846493] xhci-hcd xhci-hcd.1.auto: Max number of devices this xHCI host supports is 127.
[   17.959611] xhci-hcd xhci-hcd.0.auto: Error while assigning device slot ID
[   17.966489] xhci-hcd xhci-hcd.0.auto: Max number of devices this xHCI host supports is 127.
...
usb usb2-port1: couldn't allocate usb_device
usb usb3-port1: couldn't allocate usb_device
```
I'll try and bisect it.

**Comment by yangbolu1991** [comment]
Hi Mathew,
USB worked on LS1043ARDB board. I discussed with our USB owner. The issue should be related to dma-coherent. I think you can try to remove dma-coherent under soc/ in your board dts to have a try.
Please refer to the patch below.
https://source.codeaurora.org/external/qoriq/qoriq-components/linux/commit/?h=linux-4.14&id=89bffbe5494ebcd1fbed34899060b04face3952b

If it works, could you generate a patch for your board dts and send pull request after this pull request is merged?
Thanks a lot.

**Comment by yangbolu1991** [comment]
Rebased.

**Comment by mcbridematt** [comment]
Thanks @yangbolu1991 , it is indeed the smmu changes. 
I will submit a pull after this one is merged to add a similar dts layer for our boards.

**Comment by ynezz** [comment]
@mcbridematt thanks for testing!

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
