### PR TITLE
kernel: add exFAT driver for Linux 5.4

### PR DESCRIPTION
**Pull request by dengqf6**
Add exFAT driver for Linux 5.4
To avoid conflict with exfat-nofuse in feeds/packages, name it exfat-staging

### CODE REVIEW

**Comment by hnyman** [comment]
+1 for pointing out the renaming pointer.

I tried to use the 5.4 in-tree module a few days ago and did stumble upon the same name clash. 

In the long-run it might be better to rename the out-of-tree module in the feed and keep this in-tree 5.4+ module as kmod-fs-exfat

**Comment by hnyman** [comment]
I tested PR combined to settings a kernel version limit to the packages feed exfat-nofuse package, as  suggested in 
http://lists.infradead.org/pipermail/openwrt-devel/2020-March/022088.html

The exfat driver mounts a drive nicely with my kernel 5.4 ipq806x/R7800:

```
root@router1:~# mount | grep exfat
/dev/sda1 on /mnt/sda1 type exfat (rw,relatime,fmask=0000,dmask=0000,allow_utime=0022,iocharset=utf8,namecase=0,errors=remount-ro)
```

I think that the packages feed package should be renamed to kmod-fs-exfat-nofuse to allow this in-tree package to be the proper kmod-fs-exfat

**Comment by hnyman** [comment]
@yousong 
ccing you, as you are the maintainer of exfat-nofuse and have also commit access to the main openWrt repo. You could take care of the changes to both packages.

**Comment by yousong** [comment]
Merged in b255260 .  Thank you!

**Pull request closed without merging**
