### PR TITLE
kernel: bump 5.10 to 5.10.107

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by rsalvaterra** [comment]
Run-tested:
ath79/generic (TL-WDR3600)

**Comment by rockdrilla** [comment]
@graysky2 friendly ping, 5.10.105 has been released :]

**Comment by anomeome** [comment]
Stop for query of:
`Harden Spectre style attacks against branch history (HARDEN_BRANCH_HISTORY) [Y/n/?] (NEW)`
On target _mvebu_

**Comment by graysky2** [comment]
Not sure how general that is since both bmc1711 and mt7622 built find without it.  @rsalvaterra do you have an opinion?  If that symbol is in fact needed for mvebu but not for others, I am thinking it's better to put it in the mvebu config rather than the 5.10 general config.

**Comment by graysky2** [comment]
@anomeome - I grabbed the [mvebu config](https://www.pornhub.com/view_video.php?viewkey=ph61d4726464f6d) and built with this without an error.

**Comment by graysky2** [comment]
@anomeome - I grabbed the [buildbot mvebu config](https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa53/config.buildinfo) and built this PR without an error.

**Comment by anomeome** [comment]
As resolution I did:

```
diff --git a/target/linux/generic/config-5.10 b/target/linux/generic/config-5.10
index ca93b5f269..030099bca3 100644
--- a/target/linux/generic/config-5.10
+++ b/target/linux/generic/config-5.10
@@ -2161,6 +2161,7 @@ CONFIG_GPIO_SYSFS=y
 CONFIG_HARDENED_USERCOPY=y
 # CONFIG_HARDENED_USERCOPY_FALLBACK is not set
 # CONFIG_HARDENED_USERCOPY_PAGESPAN is not set
+# CONFIG_HARDEN_BRANCH_HISTORY is not set
 CONFIG_HARDEN_EL2_VECTORS=y
 # CONFIG_HARDLOCKUP_DETECTOR is not set
 # CONFIG_HAVE_ARM_ARCH_TIMER is not set
@@ -3381,6 +3382,7 @@ CONFIG_MESSAGE_LOGLEVEL_DEFAULT=4
 # CONFIG_MICROCHIP_T1_PHY is not set
 # CONFIG_MICROSEMI_PHY is not set
 # CONFIG_MIGRATION is not set
+CONFIG_MITIGATE_SPECTRE_BRANCH_HISTORY=y
 CONFIG_MII=y
 # CONFIG_MIKROTIK is not set
 # CONFIG_MIKROTIK_RB532 is not set
```

I'm certainly hitting it not being set and would have expected the bot build to be the same. perhaps some other _hardening_ config is forcing things. Have not looked to check if it should default to on or not.

**Comment by Borromini** [comment]
I built on mvebu/cortexa72 as well and didn't run into the spectre symbol.

Compile-tested: mvebu/cortexa72, ramips/mt7621, realtek/rtl838x
Run-tested: mvebu/cortexa72, ramips/mt7621, realtek/rtl838x

**Comment by anomeome** [comment]
Started from a _dirclean_, _git reset --hard_, on an up to date pull. Applied 3 patches, one being this PR and the other two having nothing to do with the issue at hand. Copied in [configdiff](https://termbin.com/238x) and generated a .config to the same result.

**Comment by graysky2** [comment]
Building with your config does trigger an error due to a missing symbol:
```
make V=s
...
Disable branch prediction (CPU_BPREDICT_DISABLE) [N/y/?] n
Harden the branch predictor against aliasing attacks (HARDEN_BRANCH_PREDICTOR) [Y/n/?] y
Harden Spectre style attacks against branch history (HARDEN_BRANCH_HISTORY) [Y/n/?] (NEW) 
```

The buildbot config works without error as mentioned above.  Not sure how to proceed.  @rsalvaterra any thoughts?

**Comment by anomeome** [comment]
As above, define it as not set in the generic config-5.10 file. The question is whether it should be enabled by default on some targets. I did compile with it enabled in the target config to be sure it built, but I do not use the radios on this device so did not test.

**Comment by rsalvaterra** [comment]
> Building with your config does trigger an error due to a missing symbol:
> 
> ```
> make V=s
> ...
> Disable branch prediction (CPU_BPREDICT_DISABLE) [N/y/?] n
> Harden the branch predictor against aliasing attacks (HARDEN_BRANCH_PREDICTOR) [Y/n/?] y
> Harden Spectre style attacks against branch history (HARDEN_BRANCH_HISTORY) [Y/n/?] (NEW) 
> ```
> 
> The buildbot config works without error as mentioned above. Not sure how to proceed. @rsalvaterra any thoughts?

That's a Spectre-related mitigation, so it should be enabled by default in the generic kconfig.

**Comment by graysky2** [comment]
I added the option, but when I test built using the .config provided by @anomeome above, I got an error relating to no LLVM/clang on my system.  Can you try building with the new commit?  I can verify that the new commit does not break the building of bcm2711.

**Comment by anomeome** [comment]
Not added in alphabetical order

**Comment by graysky2** [comment]
> Not added in alphabetical order 

Fixed.... is it a best practice to run the entire file through `sort`?

**Comment by anomeome** [comment]
alphabetical in the whole config file as I did above. A wholesale change via sort best relegated to a cosmetic change  IMO.

**Comment by hauke** [comment]
Thank you for your patch, I applied the first one to master in 3f5b2d25eef9a252c54adcad18ba65a0d19d69b2.

**Comment by openwrtfirmwarecostum** [comment]
I tried kernel 5.10.104 very stable

**Comment by hauke** [comment]
Thank you for your patches, I applied the first 2 to master in 048f0b170296c6fc2e2076bbe7c07b4c840d31f6 and b04d38a2eaa5604aa7216e0c02846d96dc2d317f.

**Comment by hauke** [comment]
Thank you for your patch, I also applied the last remaining on to master in 1eb5d50fd3dff15a2e316fcfa3c25597be429526.

**Pull request closed without merging**
