### PR TITLE
tools/expat: update to 2.4.1

### PR DESCRIPTION
**Pull request by neheb**
Switched to CMake for faster compilation and greater parallel
friendliness.

Added CMake options from the packages feed.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
...but CMake depends on expat?

**Comment by neheb** [comment]
Hmm? Where does it say that?

**Comment by diizzyy** [comment]
https://github.com/Kitware/CMake/blob/master/CMakeLists.txt#L191
Unless we want to use included libraries

**Comment by neheb** [comment]
Interesting...

Wonder what's currently used.

**Comment by neheb** [comment]
I looked into this. I think this should be kept as is.

I have no idea how to enable CMAKE_USE_SYSTEM_EXPAT.

**Comment by neheb** [comment]
Closing since it seems this will never be merged.

**Pull request closed without merging**
