### PR TITLE
gdb: update to 15.1

### PR DESCRIPTION
**Pull request by jen1-sys**
gdb: update to 15.1

### CODE REVIEW

**Comment by hnyman** [comment]
@jen1-sys 
I find it hard to believe that none of your dozen version update PRs for tools or toolchain components require any refreshes for the OpenWrt patches for those tools, especially in cases where there is a major version change.

You need to ensure that all patches apply cleanly, and if needed, refresh them so that they apply cleanly.

**Comment by jen1-sys** [comment]
@hnyman  tested successfully with my Asus RT-AC88U (arm_cortex-a9) using GCC 14.2.0 and binutils 2.43.1, yet I don't know about other architectures!

Sometimes newer versions will not work, so I update to the latest working version, here is an example https://github.com/openwrt/packages/pull/25022 and here is another example https://github.com/openwrt/packages/pull/25026 (closed thiugh)

**Comment by hnyman** [comment]
> > You need to ensure that all patches apply cleanly, and if needed, refresh them so that they apply cleanly.

> tested successfully with my Asus RT-AC88U (arm_cortex-a9)

You apparently did not understand my message.
It is not about just "compiling succesfully", but about making sure that all the local patches for each tool apply cleanly.
Just using this gdb as example, the existing patches do NOT apply cleanly to your 15.1: 
`"Hunk #1 succeeded at 2698 (offset 24 lines)."`

You need to refresh the patches.  
(That will get visible also in the PR itself once some OpenWrt dev triggers the automatic CI builds for your PRs...) 

```
perus@ub2404:/OpenWrt/aarch64$ make toolchain/gdb/prepare V=s
make[2]: Entering directory '/OpenWrt/aarch64/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/OpenWrt/aarch64/scripts/config'
make[1]: Entering directory '/OpenWrt/aarch64'
make[2]: Entering directory '/OpenWrt/aarch64/toolchain/gdb'
. /OpenWrt/aarch64/include/shell.sh; xzcat /OpenWrt/aarch64/dl/gdb-15.1.tar.xz | tar -C /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/* /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1

Applying /OpenWrt/aarch64/toolchain/gdb/patches/120-fix-compile-flag-mismatch.patch using plaintext: 
patching file gdbserver/configure
Hunk #1 succeeded at 2698 (offset 24 lines).
touch /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/.prepared
make[2]: Leaving directory '/OpenWrt/aarch64/toolchain/gdb'
time: toolchain/gdb/prepare#1.68#1.10#2.16
make[1]: Leaving directory '/OpenWrt/aarch64'
```

Hint:
you should do `make toolchain/gdb/refresh`  to refresh.
And for each PR where local patches exist.
Example:

```
perus@ub2404:/OpenWrt/aarch64$ make toolchain/gdb/clean
make[2]: Entering directory '/OpenWrt/aarch64/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/OpenWrt/aarch64/scripts/config'
 make[1] toolchain/gdb/clean
 make[2] -C toolchain/gdb clean
perus@ub2404:/OpenWrt/aarch64$ make toolchain/gdb/refresh V=s
make[2]: Entering directory '/OpenWrt/aarch64/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/OpenWrt/aarch64/scripts/config'
make[1]: Entering directory '/OpenWrt/aarch64'
make[2]: Entering directory '/OpenWrt/aarch64/toolchain/gdb'
. /OpenWrt/aarch64/include/shell.sh; xzcat /OpenWrt/aarch64/dl/gdb-15.1.tar.xz | tar -C /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/* /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1
rm -rf /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/patches; mkdir -p /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/patches
touch /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/.quilt_used
touch /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/.prepared
if [ -s "/OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/patches/series" ]; then (cd "/OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1"; if quilt --quiltrc=- next >/dev/null 2>&1; then quilt --quiltrc=- push -a; else quilt --quiltrc=- top >/dev/null 2>&1; fi ); fi
Applying patch 120-fix-compile-flag-mismatch.patch
patching file gdbserver/configure
Hunk #1 succeeded at 2698 (offset 24 lines).

Now at patch 120-fix-compile-flag-mismatch.patch
touch "/OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/.quilt_checked"
Applying patch 120-fix-compile-flag-mismatch.patch
patching file gdbserver/configure
Hunk #1 succeeded at 2698 (offset 24 lines).

Now at patch 120-fix-compile-flag-mismatch.patch
Refreshed patch 120-fix-compile-flag-mismatch.patch
rm -rf /OpenWrt/aarch64/toolchain/gdb/patches 2>/dev/null >/dev/null
[ -f /OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/.quilt_no_patch ] || mkdir -p /OpenWrt/aarch64/toolchain/gdb/patches
'/OpenWrt/aarch64/build_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/gdb-15.1/patches/120-fix-compile-flag-mismatch.patch' -> '/OpenWrt/aarch64/toolchain/gdb/patches/120-fix-compile-flag-mismatch.patch'
make[2]: Leaving directory '/OpenWrt/aarch64/toolchain/gdb'
time: toolchain/gdb/refresh#1.59#0.92#1.96
make[1]: Leaving directory '/OpenWrt/aarch64'
```

Refreshed patch visible in git diff:

```
perus@ub2404:/OpenWrt/aarch64$ git diff
diff --git a/toolchain/gdb/Makefile b/toolchain/gdb/Makefile
index ecb31398e6..c41a7b67c8 100644
--- a/toolchain/gdb/Makefile
+++ b/toolchain/gdb/Makefile
@@ -7,12 +7,12 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=gdb
-PKG_VERSION:=14.1
+PKG_VERSION:=15.1
 PKG_RELEASE:=1
 
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
 PKG_SOURCE_URL:=@GNU/gdb
-PKG_HASH:=d66df51276143451fcbff464cc8723d68f1e9df45a6a2d5635a54e71643edb80
+PKG_HASH:=38254eacd4572134bca9c5a5aa4d4ca564cbbd30c369d881f733fb6b903354f2
 PKG_CPE_ID:=cpe:/a:gnu:gdb
 GDB_DIR:=$(PKG_NAME)-$(PKG_VERSION)
 
diff --git a/toolchain/gdb/patches/120-fix-compile-flag-mismatch.patch b/toolchain/gdb/patches/120-fix-compile-flag-mismatch.patch
index 9430509278..f9c5670094 100644
--- a/toolchain/gdb/patches/120-fix-compile-flag-mismatch.patch
+++ b/toolchain/gdb/patches/120-fix-compile-flag-mismatch.patch
@@ -1,6 +1,6 @@
 --- a/gdbserver/configure
 +++ b/gdbserver/configure
-@@ -2674,7 +2674,7 @@ $as_echo "$as_me: error: \`$ac_var' was
+@@ -2698,7 +2698,7 @@ $as_echo "$as_me: error: \`$ac_var' was
        ac_cache_corrupted=: ;;
      ,);;
      *)
```

And then update each PR if there were changed patches.

**Comment by krant** [comment]
@jen1-sys first of all - thanks a lot for putting an effort to update update the stuff! But you've missed `make <something>/refresh`, please re-read @hnyman comment. Also, it would be much easier for you to get a single PR merged first - after that GitHub would allow your next PRs to run without approve.

**Comment by jen1-sys** [comment]
@krant The reason I build from scratch is meson package. Somehow some packages are dependence on other packages, if if build successful changes other packages will fail them later. That the reason I build from scratch.

Here is how I do it: 
Download the main branch as zip, extract, 
Run ./scripts/feeds update -a
Update the files https://www.mediafire.com/file/gpg41cio97ktl63/OpenWrt_updates.tar.xz/file
Run ./scripts/feeds install -a
Run make menuconfig and choose my options
make

Just now I built with all the updates with no issues, anyhow from some reason not all the packages that usually compiled are compiled some are missing, like 7z and bash?

Here are the list of the downloaded packages built from scratch with no issues.



```
.                                      firmware-utils-2024.06.20~6ac44974.tar.zst              libselinux-3.7.tar.gz                        patchelf-0.18.0.tar.bz2
..                                     firmware-utils-2024.09.22~ed9c97fa.tar.zst              libsepol-3.7.tar.gz                          pcre2-10.42.tar.bz2
acl-2.3.2.tar.xz                       flex-2.6.4.tar.gz                                       libssh2-1.11.0.tar.gz                        pkgconf-2.2.0.tar.gz
argp-standalone-1.3.tar.gz             flit_core-3.9.0.tar.gz                                  libtool-2.4.7.tar.gz                         ppp-2.4.9_git20210104.tar.zst
attr-2.5.2.tar.xz                      fortify-headers-1.1.tar.zst                             libubox-2024.03.29~eb9bcb64.tar.zst          procd-2024.07.07~f230c117.tar.zst
autoconf-2.71.tar.gz                   fstools-2024.07.14~408c2cc4.tar.zst                     linux-6.6.52.tar.xz                          pyproject_hooks-1.0.0.tar.gz
autoconf-archive-2023.02.20.tar.xz     fwtool-2019.11.12~8f7fe925.tar.zst                      linux-atm-2.5.2.tar.gz                       Python-3.11.7.tar.xz
automake-1.16.5.tar.gz                 gawk-5.3.1.tar.xz                                       linux-firmware-20240909.tar.xz               quilt-0.68.tar.gz
backports-6.11.tar.xz                  gcc-14.2.0.tar.xz                                       lua-5.1.5.tar.gz                             readline-8.2.tar.gz
bc-1.07.1.tar.gz                       gdb-15.1.tar.xz                                         lua-5.4.6.tar.gz                             rpcd-2024.09.17~9f4b86e7.tar.zst
binutils-2.43.1.tar.xz                 gdbm-1.24.tar.gz                                        lucihttp-2023.03.15~9b5b683f.tar.zst         sed-4.9.tar.gz
bison-3.8.2.tar.gz                     gengetopt-2.23.tar.xz                                   lzma-4.65.tar.bz2                            sqlite-autoconf-3460100.tar.gz
bluez-5.72.tar.xz                      glib-2.82.1.tar.xz                                      m4-1.4.19.tar.gz                             squashfs4-4.6.1.tar.zst
broadcom-wl-4.150.10.5.tar.bz2         gmp-6.3.0.tar.gz                                        make-ext4fs-2020.01.05~5c201be7.tar.zst      tar-1.35.tar.gz
broadcom-wl-5.100.138.tar.bz2          gmp-6.3.0.tar.xz                                        mbedtls-3.6.1.tar.bz2                        u-boot-2024.07.tar.bz2
build-1.0.3.tar.gz                     gnulib-c99c8d491850dc3a6e0b8604a2729d8bc5c0eff1.tar.gz  meson-1.5.2.tar.gz                           ubox-2024.04.26~85f10530.tar.zst
busybox-1.36.1.tar.bz2                 hostapd-2024.09.15~5ace39b0.tar.zst                     mklibs_0.1.45.tar.xz                         ubus-2023.11.28~f84eb599.tar.zst
bzip2-1.0.8.tar.gz                     installer-0.7.0.tar.gz                                  mpc-1.3.1.tar.gz                             ucert-2020.05.24~00b921d8.tar.zst
ca-certificates_20240203.tar.xz        iproute2-6.9.0.tar.xz                                   mpfr-4.2.1.tar.gz                            uci-2023.08.10~5781664d.tar.zst
cgi-io-2022.08.10~901b0f04.tar.zst     iptables-1.8.8.tar.bz2                                  mtd-utils-2.2.0.tar.bz2                      uclient-2024.04.19~e8780fa7.tar.zst
cmake-3.30.3.tar.gz                    iw-6.9.tar.xz                                           mtools-4.0.44.tar.bz2                        ucode-2024.07.11~1a8a0bcf.tar.zst
coreutils-9.3.tar.xz                   jansson-2.14.tar.gz                                     musl-1.2.5.tar.gz                            udebug-2023.12.06~6d3f51f9.tar.zst
cpio-2.15.tar.bz2                      json-c-0.17-nodoc.tar.gz                                musl-fts-1.2.7.tar.xz                        uhttpd-2023.06.25~34a8a74d.tar.zst
csstidy-2021.06.13~707feaec.tar.zst    jsonfilter-2024.01.23~594cfa86.tar.zst                  ncurses-6.4.tar.gz                           urngd-2023.11.01~44365eb1.tar.zst
dbus-1.14.10.tar.xz                    libbpf-1.4.5.tar.zst                                    netifd-2024.09.21~24f9a93a.tar.zst           usign-2020.05.23~f1f65026.tar.zst
dnsmasq-2.90.tar.xz                    libcap-2.69.tar.xz                                      nftables-1.0.9.tar.xz                        ustream-ssl-2024.07.28~99bd3d2b.tar.zst
dosfstools-4.2.tar.gz                  libdeflate-1.20.tar.gz                                  ninja-1.11.1.tar.gz                          util-linux-2.40.2.tar.xz
dropbear-2024.85.tar.bz2               libffi-3.4.6.tar.gz                                     nmap-7.95.tar.bz2                            wheel-0.42.0.tar.gz
e2fsprogs-1.47.1.tar.gz                libical-3.0.11.tar.gz                                   odhcp6c-2023.05.12~bcd28363.tar.zst          wireguard-tools-1.0.20210914.tar.xz
ELFkickers-3.2.tar.gz                  libiwinfo-2024.09.17~268a6624.tar.zst                   odhcpd-2024.05.08~a2988231.tar.zst           wireless-regdb-2024.07.04.tar.xz
elfutils-0.191.tar.bz2                 libmnl-1.0.5.tar.bz2                                    openssl-3.0.15.tar.gz                        xz-5.6.2.tar.bz2
expat-2.6.3.tar.gz                     libnftnl-1.2.7.tar.xz                                   openwrt-keyring-2022.03.25~62471e69.tar.zst  zip30.tar.gz
fakeroot_1.33.orig.tar.gz              libnl-tiny-2023.12.05~965c4bf4.tar.zst                  opkg-2022.02.24~d038e5b6.tar.zst             zlib-1.3.1.tar.gz
findutils-4.10.0.tar.xz                libpcap-1.10.5.tar.gz                                   packaging-23.2.tar.gz                        zlib-1.3.1.tar.xz
firewall4-2024.05.21~4c01d1eb.tar.zst  libressl-3.7.3.tar.gz                                   patch-2.7.6.tar.gz                           zstd-1.5.6.tar.gz

```

I just flash the build and running my Asus RT-AC88U (arm_cortex-a9) !

Here are the packages mentioned in these pulls that are safe to update as of today:

https://github.com/openwrt/openwrt/pull/16529 libselinux 3.7 
https://github.com/openwrt/openwrt/pull/16527 libsepol 3.7
https://github.com/openwrt/openwrt/pull/16499 meson 1.5.2
https://github.com/openwrt/openwrt/pull/16498 binutils 2.43.1
https://github.com/openwrt/openwrt/pull/16496 e2fsprogs 1.47.1
https://github.com/openwrt/openwrt/pull/16495 nettle 3.10 
https://github.com/openwrt/openwrt/pull/16494 gdb 15.1
https://github.com/openwrt/openwrt/pull/16493 gdb 15.1
https://github.com/openwrt/openwrt/pull/16492 xz 5.6.2
https://github.com/openwrt/openwrt/pull/16489 mtools 4.0.44
https://github.com/openwrt/openwrt/pull/16485 e2fsprogs 1.47.1
https://github.com/openwrt/packages/pull/25028 mtools 4.0.44
https://github.com/openwrt/packages/pull/25027 gawk 5.3.1
https://github.com/openwrt/packages/pull/25022 libical 3.0.11
https://github.com/openwrt/packages/pull/25021 glib2 2.82.1
https://github.com/openwrt/packages/pull/25020 gdbm 1.24

Now for some reason, I am 100% sure that other packages used to be downloaded and compiled, didn't compiled today.

The packages in the links above are 100% safe to compile.

**Comment by krant** [comment]
CI has additional step which checks that patches are properly refreshed. Not all your PRs need this, but some of them do and will fail because of that.

**Comment by jen1-sys** [comment]
@krant  I get it if there are additional checks, as there are other CPU architectures, not mention the instruction sets (arm, x86,x64).

I am just trying to be helpful :)

**Comment by jen1-sys** [comment]
@curtdept  read my comment 2 posts ago how I do it, it is already cleaned and refreshed for all packages!

```
└─$ make toolchain/gdb/refresh V=s
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist
make[2]: Entering directory '/mnt/ramdisk/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/mnt/ramdisk/openwrt/scripts/config'
time: target/linux/prereq#0.09#0.01#0.10
make[1]: Entering directory '/mnt/ramdisk/openwrt'
make[2]: Entering directory '/mnt/ramdisk/openwrt/toolchain/gdb'
Applying patch 120-fix-compile-flag-mismatch.patch
patching file gdbserver/configure

Now at patch 120-fix-compile-flag-mismatch.patch
Patch 120-fix-compile-flag-mismatch.patch is unchanged
rm -rf /mnt/ramdisk/openwrt/toolchain/gdb/patches 2>/dev/null >/dev/null
[ -f /mnt/ramdisk/openwrt/build_dir/toolchain-arm_cortex-a9_gcc-14.2.0_musl_eabi/gdb-15.1/.quilt_no_patch ] || mkdir -p /mnt/ramdisk/openwrt/toolchain/gdb/patches
'/mnt/ramdisk/openwrt/build_dir/toolchain-arm_cortex-a9_gcc-14.2.0_musl_eabi/gdb-15.1/patches/120-fix-compile-flag-mismatch.patch' -> '/mnt/ramdisk/openwrt/toolchain/gdb/patches/120-fix-compile-flag-mismatch.patch'
make[2]: Leaving directory '/mnt/ramdisk/openwrt/toolchain/gdb'
time: toolchain/gdb/refresh#0.14#0.04#0.17
make[1]: Leaving directory '/mnt/ramdisk/openwrt'
```

**Comment by hauke** [comment]
Replaced by 1cd7708eb3f2569ff0c005c568ed9bbd2391a06b from https://github.com/openwrt/openwrt/pull/16665

**Pull request closed without merging**
