### PR TITLE
kernel: bump 6.6 to 6.6.22

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.22
    
Affected patch automatically rebased.

Build system: x86/64
Build-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, flogic/glinet_gl-mt6000, ramips/tplink_archer-a6-v3, flogic/glinet_gl-mt6000
Run-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, flogic/glinet_gl-mt6000, ramips/tplink_archer-a6-v3, flogic/glinet_gl-mt6000

### CODE REVIEW

**Comment by robimarko** [comment]
`target/linux/generic/pending-6.6/670-ipv6-allow-rejecting-with-source-address-failed-policy.patch` requires refresh, so CI will fail

**Comment by graysky2** [comment]
@robimarko - that is odd, the initial run of the script did not make that modification.

**Review by pesa1234 — APPROVED** [review]
gl.inet MT6000 ok. thanks

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
