### PR TITLE
bcm27xx: add 6.6 testing kernel

### PR DESCRIPTION
**Pull request by Noltari**
Tested on the following subtargets:
- [ ] bcm2708
- [ ] bcm2709
- [ ] bcm2710
- [x] bcm2711
- [ ] bcm2712

### CODE REVIEW

**Comment by DragonBluep** [comment]
I suggest moving kernel symbols which are only available on the `bcm27xx` target from `generic` to the sub-target. They are coming from local patches. ref: https://github.com/openwrt/openwrt/pull/15324

**Comment by Noltari** [comment]
> I suggest moving kernel symbols which are only available on the `bcm27xx` target from `generic` to the sub-target. They are coming from local patches. ref: #15324

Doing that usually results on symbols appearing and disappearing whenever the config is refreshed with or without all the kmod packages enabled. Did you try that?

**Comment by DragonBluep** [comment]
> > I suggest moving kernel symbols which are only available on the `bcm27xx` target from `generic` to the sub-target. They are coming from local patches. ref: #15324
> 
> Doing that usually results on symbols appearing and disappearing whenever the config is refreshed with or without all the kmod packages enabled. Did you try that?

Yes. That's for sure those `is not set` symbols will be automatically removed. But I noticed `bcm27xx` is the only target which pollutes the generic config files with the target specific symbols. Anyway, they are harmless, I just found that these symbols would make it difficult to clean up generic config files.

**Review by schuettecarsten — APPROVED** [review]
Works in my device (bcm2711)

**Comment by schuettecarsten** [comment]
bcm27xx patches fail on kernel 6.6.32, see https://github.com/openwrt/openwrt/pull/15513

```
Applying /home/cschuette/openwrt/snapshot/openwrt/target/linux/bcm27xx/patches-6.6/950-0245-net-bcmgenet-Reset-RBUF-on-first-open.patch using plaintext:
patching file drivers/net/ethernet/broadcom/genet/bcmgenet.c
Hunk #1 FAILED at 3307.
Hunk #2 succeeded at 3346 with fuzz 2 (offset 14 lines).
Hunk #3 FAILED at 3403.
Hunk #4 FAILED at 4278.
```

**Comment by schuettecarsten** [comment]
Any news on this?
Also fails with kernel 6.6.33 (https://github.com/openwrt/openwrt/pull/15696)

**Comment by Noltari** [comment]
> Any news on this? Also fails with kernel 6.6.33 (#15696)

Rebased on latest main, with latest patches from https://github.com/raspberrypi/linux/commits/rpi-6.6.y/ and refreshed kernel configs.

**Comment by Noltari** [comment]
@hauke @DragonBluep https://github.com/openwrt/openwrt/commit/2d00ed7caae4ad3f1706d414780acedf9371ba06

Even though I added as most symbols as I could to the bcm27xx configs, I had to restore the following specific bcm27xx symbols on the generic config, as these symbols only show up when all kmods are selected in the build config:
```
CONFIG_BACKLIGHT_RPI
CONFIG_DRM_PANEL_ILITEK_ILI9806E
CONFIG_DRM_PANEL_TPO_Y17P
CONFIG_DRM_PANEL_WAVESHARE_TOUCHSCREEN
CONFIG_DRM_RP1_DPI
CONFIG_DRM_RP1_DSI
CONFIG_DRM_RP1_VEC
CONFIG_REGULATOR_RASPBERRYPI_TOUCHSCREEN_V2
```

The following symbol is new from the updated patches:
```
CONFIG_MEDIA_PCI_HAILO
```

I also restored the following symbol that was removed from the generic config and it's not bcm27xx specific:
```
CONFIG_ARCH_BCM_63XX
```

**Comment by leobsky** [comment]
> I also restored the following symbol that was removed from the generic config and it's not bcm27xx specific:

@Noltari Other option is to create a new config with all the removed symbol in
`target/linux/bcm27xx/config-6.6`  I tested on the pi5 on the weekend
https://github.com/leobsky/openwrt/commit/8d039434e258f716db18dfb952bf2e0aaa94a28a

**Comment by Noltari** [comment]
> > I also restored the following symbol that was removed from the generic config and it's not bcm27xx specific:
> 
> @Noltari Other option is to create a new config with all the removed symbol in `target/linux/bcm27xx/config-6.6` I tested on the pi5 on the weekend [leobsky@8d03943](https://github.com/leobsky/openwrt/commit/8d039434e258f716db18dfb952bf2e0aaa94a28a)

I will try t

> > I also restored the following symbol that was removed from the generic config and it's not bcm27xx specific:
> 
> @Noltari Other option is to create a new config with all the removed symbol in `target/linux/bcm27xx/config-6.6` I tested on the pi5 on the weekend [leobsky@8d03943](https://github.com/leobsky/openwrt/commit/8d039434e258f716db18dfb952bf2e0aaa94a28a)

@leobsky thanks for the suggestion, I will check that.
What happens if you run `make kernel_menuconfig CONFIG_TARGET=subtarget` instead of `make kernel_menuconfig` with that new config?
Does it update the symbols from the subtarget?

**Comment by leobsky** [comment]
> What happens if you run make kernel_menuconfig CONFIG_TARGET=subtarget instead of make kernel_menuconfig with that new config?
Does it update the symbols from the subtarget?

@Noltari yes did it tat way `make kernel_menuconfig CONFIG_TARGET=subtarget` to keep the target config untouched

**Pull request merged**
