### PR TITLE
toolchain/binutils: Remove 2.30

### PR DESCRIPTION
**Pull request by diizzyy**
Remove binutils 2.30

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile/Runtime tested on: mvebu, Linksys WRT3200ACM, OpenWrt master

**Comment by diizzyy** [comment]
@hauke 
Don't see any reason to keep this...

**Comment by diizzyy** [comment]
@nbd168 
Ping

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
