### PR TITLE
f2fs-tools: update to fix resize.f2fs error

### PR DESCRIPTION
**Pull request by metercai**
update the last version of f2fs-tools to avoid to fails at expanding the filesystem for squashfs image.

Signed-off-by: metercai <cai.mingjun@gmail.com>

### CODE REVIEW

**Comment by mans0n** [comment]
Hi, this has some formal issues, especially:

* Please add a prefix "package:" to the commit title.
* Please add a proper commit message more than just an error message.
* Please add a Signed-off-by tag with your real name.

https://openwrt.org/docs/guide-developer/frequent-pr-mistakes

**Comment by mans0n** [comment]
PR description != commit message.
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes#know_the_difference_between_the_pr_pull_request_and_the_commit
And you should use your **real** name for the Signed-off-by tag. I would recommend to run `git commit --amend --signoff --reset-author` to refresh the author line as well.

**Comment by mans0n** [comment]
Please do not create merge commit, this PR should contain only commits by yourself.
https://openwrt.org/docs/guide-developer/working-with-github-pr#squashing_commits

**Comment by hauke** [comment]
I would prefer if you just backport the patch you need instead of going to a random git commit.

**Comment by hauke** [comment]
The resize problem was fixed in 1aac1b36d3cf44c8bfa8d4a6d8df6e815fc06529 by applying #9803. This fixes #9800.

**Pull request closed without merging**
