### PR TITLE
kernel: add new option KERNEL_CC_OPTIMIZE_FOR_DEBUGGING

### PR DESCRIPTION
**Pull request by jmarcet**
Signed-off-by: Javier Marcet <javier@marcet.info>

The topic says it all.

### CODE REVIEW

**Comment by jmarcet** [comment]
When debugging the kernel, there are some values which are not optimized out on gdb (kgdb) thanks to this.

**Comment by hauke** [comment]
How are these patches of getting into mainline Linux kernel? Currently I do not see then in linux-next.

**Comment by jmarcet** [comment]
I don't think they will be merged upstream. There was a [post](https://lwn.net/Articles/753201/) about it on lwn.net a while ago.

**Comment by jmarcet** [comment]
I din't think it will be merged upstream.

There was a post about it on [lwn.net](https://lwn.net/Articles/756616/) a while ago.

**Comment by adrianschmutzler** [comment]
Well, if kernel doesn't want these changes, and you want us to take them, you should not only add a justification to your commit message as requested already, but an extensive and compelling one.

**Comment by jmarcet** [comment]
Well, I am afraid I do not have a good enough reason.

I enabled all that debugging while tracing a race condition in the kernel but it didn't help much after all, so I'll drop it.

Thanks for the feedback anyway.

**Pull request closed without merging**
