### PR TITLE
mvebu: add linux 5.10 support

### PR DESCRIPTION
**Pull request by nitroshift**
This adds support for Linux 5.10 on the mvebu target.

Signed-off-by: Sebastian Careba <nitroshift@yahoo.com>

### CODE REVIEW

**Comment by SkewedZeppelin** [comment]
Tested working on caiman and mamba.
My kernel size is at 3.1MB, https://github.com/openwrt/openwrt/pull/3852 is necessary for mamba and venom.

Tested-by: Tad <tad@spotco.us>

**Comment by adschm** [comment]
Reviewing (and reading) kernel bumps is typically much easier when they are provided in the following steps:
1. Stupidly copy files-5.4, patches-5.4, config-5.4 over to files-5.10, patches-5.10, config-5.10 without touching them otherwise.
2. Refresh 5.10 patches (so this commit shows the actual changes)
3. Refresh 5.10 config (make kernel_oldconfig), so this commit shows the actual changes)
4. ... Update other stuff grouped into logical steps

**Comment by diizzyy** [comment]
Is that a suggestion or a requirement as the project members doesn't seem to use it?
https://github.com/openwrt/openwrt/commits/master/target/linux/bcm63xx

**Comment by adschm** [comment]
> Is that a suggestion or a requirement as the project members doesn't seem to use it?
> https://github.com/openwrt/openwrt/commits/master/target/linux/bcm63xx

That is a suggestion. However, as it makes reading and reviewing much easier, it probably will speed things up.

**Comment by rsalvaterra** [comment]
@adschm, @nitroshift told me on IRC he doesn't have a lot of time to do this, so I'm taking a stab at it. Will smoke-test on my Turris Omnia.

**Comment by rsalvaterra** [comment]
FYI, patch series [here](https://patchwork.ozlabs.org/project/openwrt/list/?series=230213). Let me know if you'd prefer a pull request.

**Comment by 1Jeff1** [comment]
> FYI, patch series [here](https://patchwork.ozlabs.org/project/openwrt/list/?series=230213). Let me know if you'd prefer a pull request.

@rsalvaterra Github is more friendly with the normal users a PR would be great.

**Comment by rsalvaterra** [comment]
> @rsalvaterra Github is more friendly with the normal users a PR would be great.

It isn't to me, I'm much more confortable with email patches. But if the core developers prefer the pull request, I'll do it.

**Comment by njhsi** [comment]
> FYI, patch series [here](https://patchwork.ozlabs.org/project/openwrt/list/?series=230213). Let me know if you'd prefer a pull request.

thanks! there are 3 config paras out of control, should them be taken care of?

CONFIG_HAVE_ARM_ARCH_TIMER, CONFIG_ARM_ARCH_TIMER_EVTSTREAM, CONFIG_ARM_ATAG_DTB_COMPAT_CMDLINE_MANGLE

fyi, I made it as below
buildman@debian:~/target/linux/mvebu$ diff config-5.10 config-5.10.new
30c30,32
< CONFIG_ARM_ATAG_DTB_COMPAT_CMDLINE_FROM_BOOTLOADER=y
---
> # CONFIG_ARM_ATAG_DTB_COMPAT_CMDLINE_FROM_BOOTLOADER is not set
> CONFIG_ARM_ATAG_DTB_COMPAT_CMDLINE_MANGLE=y
> CONFIG_ARM_ARCH_TIMER_EVTSTREAM=y
206a209
> CONFIG_HAVE_ARM_ARCH_TIMER=y

**Comment by rsalvaterra** [comment]
> thanks! there are 3 config paras out of control, should them be taken care of?
> 
> CONFIG_HAVE_ARM_ARCH_TIMER,
> CONFIG_ARM_ARCH_TIMER_EVTSTREAM,
> CONFIG_ARM_ATAG_DTB_COMPAT_CMDLINE_MANGLE

Possibly, if those kconfig symbols are introduced by patches. If that's the case, I have to `make kernel_oldconfig` _after_ refreshing all the patches. Let me double check, I'll respin if necessary.

**Comment by rsalvaterra** [comment]
@njhsi, you were right about `ARM_ATAG_DTB_COMPAT_CMDLINE_MANGLE`. I just respun the series [here](https://patchwork.ozlabs.org/project/openwrt/list/?series=230289).

All the `HAVE_*` kconfig symbols are selected by the architecture itself, we have no control over them (as a side note, the ARM Architected Timer is a per-core high resolution timer present in ARMv7+ CPUs, so it's definitely a nice-to-have feature).

`ARM_ARCH_TIMER_EVTSTREAM` defaults to `y`, so it's probably a good idea to keep it enabled. 😉

**Comment by rmandrad** [comment]
pretty straightforward ... apart from if one has wireguard ... it is now included on the kernel

What is holding getting this approved ?!

**Comment by rsalvaterra** [comment]
Whoa, there! I just posted this, give the core developers some time, they
have a lot on their hands.

A sábado, 20/02/2021, 13:13, Miguel Andrade <notifications@github.com>
escreveu:

**Comment by anomeome** [comment]
@rmandrad , see [PR3885](https://github.com/openwrt/openwrt/pull/3885)

**Comment by rsalvaterra** [comment]
V3 of the series [here](https://patchwork.ozlabs.org/project/openwrt/list/?series=230421).

**Comment by rsalvaterra** [comment]
V4 and final [here](https://patchwork.ozlabs.org/project/openwrt/list/?series=230516). The [first patch](https://patchwork.ozlabs.org/project/openwrt/patch/20210222173714.220839-2-rsalvaterra@gmail.com/) of the series is out of thread, for some reason.

**Comment by SkewedZeppelin** [comment]
@rsalvaterra
I've been running v3 on mamba/caiman for 6+ hours, no issues.
Is v4 any functional changes? or just cosmetic?

**Comment by rsalvaterra** [comment]
> @rsalvaterra I've been running v3 on mamba/caiman for 6+ hours, no issues. Is v4 any functional changes? or just cosmetic?

There's only a functional change in the 4th patch, restoring the device tree for the ESPRESSObin Ultra (cortexa53 target), which was inadvertently removed. Both cortexa9 and cortexa72 are unchanged.

**Comment by adschm** [comment]
This is superseded by the version in patchwork.

**Comment by dominick-han** [comment]
Hello everyone! Thank you for your work here :)

Quick question, I went in `make menuconfig` to enable testing kernel, and `make clean && make -j1`
It's asking for `Architected timer support (HAVE_ARM_ARCH_TIMER) [N/y/?] (NEW)`, not sure what to choose (probably N?)

**Comment by pali** [comment]
Hello! Why you are including the patch `target/linux/mvebu/patches-5.10/314-arm64-dts-marvell-armada37xx-Add-eth0-alias.patch`? I do not see this patch/change in mainline linux.

**Comment by pali** [comment]
PING! what is above custom patch suppose to do?

**Comment by rsalvaterra** [comment]
> PING! what is above custom patch suppose to do?

You probably need to ask the original author. I merely forward-ported it.

**Comment by pali** [comment]
> I merely forward-ported it.

Which seems to be incorrect.

**Comment by pali** [comment]
Same question what why is there patch `target/linux/mvebu/patches-5.10/700-mvneta-tx-queue-workaround.patch` and what is suppose to do? It is also not in mainline kernel 5.10 neither in new version. In description of the patch is some bug (?) in 5.10 kernel. Can you post a link to this 5.10 kernel bug? Where it was reported and so? Because I have not found anything related to this kind of issue for 5.10 kernel.

**Comment by tmn505** [comment]
Hi, @pali, I intended do send patch to drop `target/linux/mvebu/patches-5.10/314-arm64-dts-marvell-armada37xx-Add-eth0-alias.patch`, will do that in upcoming days.
As for `target/linux/mvebu/patches-5.10/700-mvneta-tx-queue-workaround.patch`, this patch was on the tree since I remember and can't say much about it more than it was carried from one major bump to another. There was "recent" conversation about this patch on IRC: https://freenode.irclog.whitequark.org/openwrt-devel/2020-12-18#28633662;. There @nbd168 explains bit more on the topic. Looking at https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cf9bf871280d9e0a8869d98c2602d29caf69dfa3 maybe this bug was present on some earlier Armada SoCs as well?

**Comment by pali** [comment]
Ok!

About 700-mvneta-tx-queue-workaround.patch in OpenWRT kernel, I got more pings that this OpenWRT patch is causing performance regressions and because it is not in mainline kernel I was not able to find any reason why it is here.

64bit A3720 can receive mvneta interrupts only on first CPU, but there are already hooks for this SoC in mainline kernel (with backports to stable kernels) for a long time. Yea, some fixups were sent recently but they are also included in stable kernels.

So either this patch is copying from old version to new without testing or understanding why it is there (like alias patch, which does nothing). Or nobody cared to report this bug with description what is the issue and how it can be reproduced.

**Comment by tmn505** [comment]
Thanks for explanation. Felix wrote in that IRC conversation: "<nbd> mangix: i could easily reproduce it with iperf (not iperf3) and -P 4". Maybe You can try it out on Omnia? I don't have any other board except A3720.

The alias patch was added with the initial support for ESPRESSObin. Now it does nothing for ESPRESSObin, but it could for other boards, like uDPU or GL-MV1000. I'll send the patch to remove it anyway, if any board is relying on it then we'll add alias nodes to them.

**Pull request closed without merging**
