### PR TITLE
[23.05]: lldpd: cherry picks from main

### PR DESCRIPTION
**Pull request by systemcrash**
Each commit here is from main and has been well tested on 23.05 series.

A few commits on main individually contained errors, but cumulatively they are now resolved.

### CODE REVIEW

**Comment by systemcrash** [comment]
ping

**Comment by tapper82** [comment]
Any one fancy fleshing out the wiki for lldpd: ? https://openwrt.org/docs/techref/lldpd After reading that I still don't get what lldpd is and what it's for.

**Comment by systemcrash** [comment]
Will this make the cut for next 23.05 build coming soon?

**Comment by systemcrash** [comment]
@Ansuel @robimarko to integrate patches from master to 23.

ping also @stintel

**Comment by robimarko** [comment]
Thanks! Rebased on top of openwrt-23.05 and merged!

**Comment by systemcrash** [comment]
Thanks dude!

**Pull request merged**
