### PR TITLE
[RFC]add clang-format kernel style

### PR DESCRIPTION
**Pull request by aparcar**
copied from the official kernel style:

https://github.com/torvalds/linux/blob/master/.clang-format

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
@ynezz so you'd be in favor to have a style "fitting" most of the current style? If so I'd work a bit on that issue to have eventually something all OpenWrt tools *could* stick to.

**Comment by ynezz** [comment]
> so you'd be in favor to have a style "fitting" most of the current style? 

I've made [a summary](https://github.com/openwrt/openwrt/pull/2052#issuecomment-495176931) already. As @KanjiMonster said:

> > it would make more sense to tweak the .clang-format so it matches the existing code style, not some arbitrary different one (and then use clang-format to find/fix inconsistencies)

So this would need several coding styles, as there's no common coding style between the projects, because they were started by different people.

> eventually something all OpenWrt tools _could_ stick to

Well, currently it's "please try to adhere to the coding style already present in this particular project" advice. I can't even imagine, that we're going to convert all projects to one coding style enforced by one .clang-format and one particular clang-format version.

**Comment by neheb** [comment]
Could GNU Indent be an alternative?

**Comment by ynezz** [comment]
> Could GNU Indent be an alternative?

I really don't know how to explain it better, sorry :-) It's not about the tool, it's about the divergence of coding styles between the projects, there are simply plenty of them, because they were not developed by the single person. We would probably either need to unify the coding style across the projects or provide separate formatting rules for every project to match its specific coding style.

I'll try to bring this topic on the developer meeting next week.

**Comment by ynezz** [comment]
Closing it as it has very low chances to be accepted as it is, for details see for example https://github.com/openwrt/openwrt/pull/2052#issuecomment-495169932

**Pull request closed without merging**
