### PR TITLE
tools/e2fsprogs: Update to 1.45.2

### PR DESCRIPTION
**Pull request by diizzyy**
Update e2fsprogs to 1.45.2
Remove OpenBSD patch

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master
Run tested: mvebu, Linksys WRT3200ACM, OpenWrt master

**Comment by dedeckeh** [comment]
This fails for me with the following error 
make[4]: Entering directory '/home/dedeckeh/arm-virt-staging/build_dir/host/e2fsprogs-1.45.2/scrub'
	MKDIR_P /etc/cron.d
	MKDIR_P /home/dedeckeh/arm-virt-staging/staging_dir/host/lib/e2fsprogs
	MKDIR_P /home/dedeckeh/arm-virt-staging/staging_dir/host/bin /home/dedeckeh/arm-virt-staging/staging_dir/host/share/man/man8 /home/dedeckeh/arm-virt-staging/staging_dir/host/etc
	INSTALL /etc/cron.d/e2scrub_all
/usr/bin/install: cannot create regular file '/etc/cron.d/e2scrub_all': Permission denied

**Comment by diizzyy** [comment]
Looks like it picks up crond on your system for some reason

**Comment by diizzyy** [comment]
Compile tested: ipq40xx, Linksys EA6350v3, OpenWrt master
Run tested: ipq40xx, Linksys EA6350v3, OpenWrt master

**Comment by EXSERENS** [comment]
I have same problem with dedeckeh.

**Comment by diizzyy** [comment]
Works just fine on Alpine which is the only Linux distro I run these days, if someone wants to debug Debian/Ubuntu feel free to do so.

**Comment by jow-** [comment]
Failing for me as well on Debian. Closing this as there does not seem to be interest to fix/test the PR.

**Pull request closed without merging**
