### PR TITLE
ar71xx: Add support for Ubiquiti LiteBeam ac

### PR DESCRIPTION
**Pull request by rogerpueyo**
This pull request adds support for ar71xx Ubiquiti LiteBeam ac devices. It builds on top of https://github.com/openwrt/openwrt/pull/1110 and https://github.com/openwrt/openwrt/pull/689 .

### CODE REVIEW

**Comment by TobleMiner** [comment]
@rogerpueyo Nice work. I think the PR description and the commit text need to include some information on the hardware and an install instruction (guess you could just reference the support commit for the NanoStation AC loco there) though.

**Comment by rogerpueyo** [comment]
@TobleMiner , yes, I totally agree.

I have the feeling that the ar71xx target is to be deprecated and everything moved to the newer ath79. How do you feel about porting the WA board (and the devices) there?

**Comment by robimarko** [comment]
I ported Nanobeam 5AC WA to ath79 but PCI perfomance was terrible while on ar71xx its normal.
Su I doubt we will see a big progress until big bugs are not fixed

**Comment by psyborg55** [comment]
what benefits are there if including it in ath79 tree? if more performance problems then i don't see what some of you guys are trying to accomplish. just keep up with ar71xx.

**Comment by TobleMiner** [comment]
@psyborg55 There are quite a few advantages ath79 has over the old ar71xx target:

 - ath79is device tree  based. It will remove need for machine files which afaik are not accepted upstream in the linux kernel. Thus moving to device tree targets will make openwrts linux kernel more compatible with linux.

- The machine files are quite a mess. Just look through the code used to support all the different boards in openwrt. They contain a lot of duplicate code. It would be nice to replace them by device tree files.

- Device trees make runtime configuration changes and debugging easier. Pretty much all device tree configuration is accessible at runtime and can also be modified.

I think all of theese are excellent reasons to prefer device tree targets over legacy targets where possible.

**Comment by psyborg55** [comment]
so the idea is to upstream whole project to linux kernel? like it's impossible to manage it the way it is?

duplicate code is not really an issue, and sometimes it can help for easier device porting to the unexperienced ones or people just starting to explore openwrt.

keep in mind that not everyone wish to enable possibility of many runtime configuration changes.

**Comment by bobafetthotmail** [comment]
> so the idea is to upstream whole project to linux kernel? like it's impossible to manage it the way it is?

The idea is to drop as much downstream patches as possible, as it lowers the maintenance burden.

Note that the decision was already taken by core developers involved and the ball is already rolling. There is nothing to discuss, way too late for that.
https://github.com/openwrt/openwrt/commit/53c474abbdfef8eb3499e2d10c9ad491788b8a72
https://github.com/openwrt/openwrt/commit/bc04cf780e95aa292695f064dfaeea08df8c9b84
https://github.com/openwrt/openwrt/commit/db34cdf6c537304f41a097d9b9b085efa31d1146

**Comment by robimarko** [comment]
No, I don't plan to upstream ath79 one since it makes no sense to do it until PCI issues are resolved.
I will however make a PR tommorow for ar71xx target

**Comment by TobleMiner** [comment]
I'll try recompiling NanoStation AC loco ath79 Support based on current master. Fingers crossed

**Comment by robimarko** [comment]
Awesome, I gotta rebase my Nanobeam AC branch then.
But I am sure that we are missing TX/RX delay that is applied in ar71xx PR

**Comment by robimarko** [comment]
I dont think that driver is able to poll that from DT.

**Comment by TobleMiner** [comment]
I'm not entirely sure but this looks a lot like what we are looking for, doesn't it?

```
static void ag71xx_setup_gmac_934x(struct device_node *np, void __iomem *base)
{
  u32 val = __raw_readl(base + AR934X_GMAC_REG_ETH_CFG);

  ag71xx_of_bit(np, "rgmii-gmac0", &val, AR934X_ETH_CFG_RGMII_GMAC0);
  ag71xx_of_bit(np, "mii-gmac0", &val, AR934X_ETH_CFG_MII_GMAC0);
  ag71xx_of_bit(np, "gmii-gmac0", &val, AR934X_ETH_CFG_GMII_GMAC0);
  ag71xx_of_bit(np, "switch-phy-swap", &val, AR934X_ETH_CFG_SW_PHY_SWAP);
  ag71xx_of_bit(np, "switch-only-mode", &val,
    AR934X_ETH_CFG_SW_ONLY_MODE);
  ag71xx_of_set(np, "rxdv-delay", &val,
          AR934X_ETH_CFG_RDV_DELAY_SHIFT, 0x3);
  ag71xx_of_set(np, "rxd-delay", &val,
          AR934X_ETH_CFG_RXD_DELAY_SHIFT, 0x3);
  ag71xx_of_set(np, "txd-delay", &val,
          AR934X_ETH_CFG_TXD_DELAY_SHIFT, 0x3);
  ag71xx_of_set(np, "txen-delay", &val,
          AR934X_ETH_CFG_TXE_DELAY_SHIFT, 0x3);

  __raw_writel(val, base + AR934X_GMAC_REG_ETH_CFG);
}
```

**Comment by robimarko** [comment]
It looks like it

**Comment by TobleMiner** [comment]
Yep, this looks really promising. I'm now getting Gbit ethernet speeds and 350 Mbit/s up/down on the wireless radio. Patch seems to have solved our problems

**Comment by TobleMiner** [comment]
I'm not able to get the ar9342 onboard wmac to work though.

**Comment by robimarko** [comment]
For the first gen of AirMax AC gear internal wmac is disabled so you cant
use it.
Its only in the second gen gear that its usable as a management radio

**Comment by TobleMiner** [comment]
Well, it's working on my ar71xx tree so I'm pretty confident it should be working here, too. I'll take a look at the legacy ar71xx init code and try to figure out what's missing.

**Comment by robimarko** [comment]
Are you sure its working on ar71xx?
I dont remember it working on my LBE23AC in ar71xx

**Comment by TobleMiner** [comment]
Well it was not working on 5 GHz because the 5 GHz frontend does not exists but has been replaced by a directional coupler that allows it to receive signals on the big main antenna.
It was working fine on 2.4 GHz though.

**Comment by Leo-PL** [comment]
This is great news! I hope that ironing out the kinks will be easy, and the patches get accepted soon.

**Comment by TobleMiner** [comment]
Yeah there is still some rather strange stuff like
```
root@OpenWrt:/# ethtool eth0
Settings for eth0:
Cannot get device settings: Bad address
        Current message level: 0x000000ff (255)
                               drv probe link timer ifdown ifup rx_err tx_err
        Link detected: no
```

but it does not seem to affect operation

**Comment by robimarko** [comment]
I have had that same behaviour on other ath79 devices.
It looks like ag71xx driver does not expose the things needed for ethtool.

Its weird that not even a basic info is available though

**Comment by rogerpueyo** [comment]
Since the depending PR have been closed, it makes no sense to keep this one open.

**Comment by rotanid** [comment]
@rogerpueyo what about #1346 / #1347 - is this not your new base?

**Comment by rogerpueyo** [comment]
Hi @rotanid,

No, these PR are for the new ath79 port, which will eventually supersede this ar71xx one. Therefore, don't expect this device being supported in ar71xx.

I could add support for it on the ath79 port, based on #1346 and #1347, maybe later today, but I don't have the device to test it anymore. If I generated the .bin firmware image, could you try and report it?

Regards,

**Pull request closed without merging**
