### PR TITLE
can.mk: sort modules

### PR DESCRIPTION
**Pull request by lucize**
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
not to offend or anything :)
but this patch [ and related PR series ] does not offer much added value for the noise it creates 

while there is value in sorting the kmods, I would do it slowly/gradually as things progress over-time, as modules get added/removed

**Comment by blogic** [comment]
@commodo @lucize I tend to agree. they are also really hard to review.

**Comment by lucize** [comment]
@blogic should not be so hard to review, just run a `make menuconfig` on parallel sdk and visually compare that all options are present

**Comment by blogic** [comment]
@lucize i am doing cat old.mk | sort > old ; cat new.mk | sort > new ; diff -urN old new and verify that the result is empty

**Comment by blogic** [comment]
merged, Thanks !

**Comment by lucize** [comment]
ok, so I'll sort all of them, there is a general mess in there..

**Pull request closed without merging**
