### PR TITLE
sunxi: fix wifi connection for Banana Pi M2 Berry

### PR DESCRIPTION
**Pull request by LizenzFass78851**
sunxi: fix for wifi connection not working for Banana Pi M2 Berry

- fixes the problem that the banana pi m2 berry cannot connect to wifi and cannot be used as an access point

### CODE REVIEW

**Comment by Ansuel** [comment]
@LizenzFass78851 sure this fix something but why and how? We need more details....

**Comment by LizenzFass78851** [comment]
this change changes the wlan firmware used in the build of the bananpi m2 berry from "target/linux/sunxi/image/cortexa7.mk" from brcmfmac-firmware-43430-sdio to cypress-firmware-43430-sdio because the brcmfmac wlan firmware on the m2 berry does not work, i.e. as mentioned above, no connection to the wifi. with the cypress wlan firmware the wlan connection works as a client and as an access point.

to clarify, I tested this with my existing bananpi m2 berry.
I use the ultra image in the example, but both chipsets are almost the same except for the wifi firmware mentioned
Screenshot (53)


situation before installing the "cypress-firmware-43430-sdio" on bananapi m2 berry:
```
root@OpenWrt-BananaPi:~# opkg list-installed | grep "cypress-firmware-43430-sdio"
root@OpenWrt-BananaPi:~# 
root@OpenWrt-BananaPi:~# dmesg | grep "sdio"
[    8.187169] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    8.196876] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.bin failed with error -2
[    8.206626] brcmfmac mmc1:0001:1: Falling back to sysfs fallback for: brcm/brcmfmac43430-sdio.bin
[   14.231645] brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50

```
Screenshot (51)
Screenshot (52)

situation during the installation of the "cypress-firmware-43430-sdio" and the subsequent reboot:
```
root@OpenWrt-BananaPi:~# opkg install cypress-firmware-43430-sdio
Installing cypress-firmware-43430-sdio (5.4.18-2021_0812-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.5/packages/arm_cortex-a7_neon-vfpv4/base/cypress-firmware-43430-sdio_5.4.18-2021_0812-1_arm_cortex-a7_neon-vfpv4.ipk
Configuring cypress-firmware-43430-sdio.
```

situation after installing the "cypress-firmware-43430-sdio" on the bananapi m2 berry:
```
root@OpenWrt-BananaPi:~# opkg list-installed | grep "cypress-firmware-43430-sdio"
cypress-firmware-43430-sdio - 5.4.18-2021_0812-1
root@OpenWrt-BananaPi:~# dmesg | grep "sdio"
[    8.193013] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    8.223521] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.sinovoip,bpi-m2-ultra.txt failed with error -2
[    8.235218] brcmfmac mmc1:0001:1: Falling back to sysfs fallback for: brcm/brcmfmac43430-sdio.sinovoip,bpi-m2-ultra.txt
[    8.392252] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
```

Screenshot (56)
Screenshot (57)

as can be seen on the banana pi m2 berry, the wlan works with the cypress firmware 43430 sdio used. hence the pull request with the appropriate adjustment when building the image for the m2 berry

**Comment by LizenzFass78851** [comment]
This change, which contains this pull request, has already been made in the master branch and also in the openwrt-22.03 branch (from commit ff2bb16730f629d54bde8ba85c75d8614741e3fd only in relation to the file [target/linux/sunxi/image/cortexa7.mk](https://github.com/openwrt/openwrt/blob/ff2bb16730f629d54bde8ba85c75d8614741e3fd/target/linux/sunxi/image/cortexa7.mk)), so the backport to openwrt-  21.02 to fix the mentioned problem with the wifi on the m2 berry

**Comment by Ansuel** [comment]
Ok then you should use cherry-pick -x 

Also title is wrong should be [21.02]

**Comment by hauke** [comment]
It looks like the backports were done wrong. 
First this one was backported: d0b0ebf966a412ddc2b25dffb5eff7effbcd0220 with this change `(removed sinovoip_bananapi-m2-berry)`
Then this one was backported: 052ff08aa7ec8d39677fcaccaa74fe2d13ef0384 `sunxi: add support for Banana Pi M2 Berry`

**Comment by LizenzFass78851** [comment]
I have adopted the said change from pull request #11992 in the pull request here

**Comment by LizenzFass78851** [comment]
> It looks like the backports were done wrong. First this one was backported: [d0b0ebf](https://github.com/openwrt/openwrt/commit/d0b0ebf966a412ddc2b25dffb5eff7effbcd0220) with this change `(removed sinovoip_bananapi-m2-berry)` Then this one was backported: [052ff08](https://github.com/openwrt/openwrt/commit/052ff08aa7ec8d39677fcaccaa74fe2d13ef0384) `sunxi: add support for Banana Pi M2 Berry`
> 
> I do not think this is really a backport this is a fix of both these backports.
> 
> Please mention both commits it in two Fixes tags.

I force-pushed it again. This time with the correct name of the commit, a signoff and with the mention of the two commits (see quote) in the description of the commit because yesterday I force-pushed the commit with the wrong name.
Sorry for the inconvenience.

**Comment by BKPepe** [comment]
I wonder how this could pass the formality check. :shrug: Because there is noreply email address and also there is no real name as it is required here: https://openwrt.org/submitting-patches

**Comment by Ansuel** [comment]
@BKPepe eh.... my theory is that the check stopped at the first entry?

**Pull request merged**
