### PR TITLE
oxnas: add 6.1 testing support

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
ping @dangowrt

**Comment by PolynomialDivision** [comment]
So we drop it?

**Comment by dangowrt** [comment]
I think it's the only good option to drop it. Reverting the upstream drop is not trivial and even when re-adding all the drivers as downstream patches it will still only be possible to use it as single core. So users are really better off just staying with OpenWrt 23.05 and Linux 5.15 (and then maybe ImmortalWrt or other projects which may still provide builds based on Linux 5.15 once official OpenWrt stops doing that in 2025...). It's remarkable anyway how long this hardware survived, and OpenWrt has been the only option for an up-to-date OS for a long time already... The Shuttle KD-20 I used when developing the port shows visible signs of corrosion on the steel parts by now and even some components on the board don't look exactly fresh any more -- but it still boots and seems to work just fine.

**Comment by robimarko** [comment]
In this case, I have to agree with @dangowrt and drop it.

**Pull request closed without merging**
