### PR TITLE
wireguard: permit storing private & preshared keys in files

### PR DESCRIPTION
**Pull request by LukaszDargiewicz**
Add support for storing private keys and preshared keys in files, hiding secrets from uci configuration

### CODE REVIEW

**Review by ldir-EDB0 — COMMENTED** [review]
Hi Lukasz,

Thanks for your patch.  Unfortunately it cannot be accepted in its present form.  Please update the commit title to something like 'wireguard: permit storing private & preshared keys in files'

Also you need to sign off your commit with the proper 'Signed-off-by' tag.

I understand why you done this change but have you considered the case of 'sysupgrade' which at present would not preserve your key files across an upgrade?

**Comment by LukaszDargiewicz** [comment]
Hi Kevin,

Thanks for your review. I am beginner contributor to openwrt. I will update this commit.

I know of this limitation. These file paths need to be added to /etc/sysupgrade.conf for it to persist over upgrade.
There is another potential issue with luci-proto-wireguard which should be updated to support this new configuration options. I will try to address this.

**Comment by bobafetthotmail** [comment]
>These file paths need to be added to /etc/sysupgrade.conf for it to persist over upgrade.

/etc/sysupgrade.conf is mostly for user stuff.

Packages provide their own text file in  **/lib/upgrade/keep.d/** that contains the paths of the files to save.
All files in that folder will be parsed together with /etc/sysupgrade.conf and follow the same "syntax" (one path per line, full path to the file).

**Comment by LukaszDargiewicz** [comment]
> > These file paths need to be added to /etc/sysupgrade.conf for it to persist over upgrade.
> 
> /etc/sysupgrade.conf is mostly for user stuff.
> 
> Packages provide their own text file in **/lib/upgrade/keep.d/** that contains the paths of the files to save.
> All files in that folder will be parsed together with /etc/sysupgrade.conf and follow the same "syntax" (one path per line, full path to the file).

Files should now be stored in **/etc/wireguard/** directory, and that directory will be saved over upgrade.
Values of _private_key_file_ and _preshared_key_file_ options should now be filenames of files in **/etc/wireguard/** directory.

**Comment by ynezz** [comment]
@LukaszDargiewicz I'm wondering why do you need this change, and can't find answer in you commit either, so you should probably add it as well. What's wrong with having private key contents in UCI files, why can't you use it today, why do you need to store it in separate files?

**Comment by ynezz** [comment]
Closing as nobody seems to be interested in this feature. If you really think, that it should be included, please try to send this patch to mailing list, where it probably might get wider audience. Thanks!

**Pull request closed without merging**
