### PR TITLE
ath79: merge D-Link DAP-2695 with dtsi

### PR DESCRIPTION
**Pull request by s-2**
Further devices from the series have been added in the meantime,
introducing `qca955x_dlink_dap-2xxx.dtsi`.

Thus, merge support for DAP-2695 with the existing dtsi.
SPI frequency will be increased to 50 MHz.

This implies factory images can now be flashed via the regular
OEM Web UI, as well as the bootloader recovery.

Signed-off-by: Sebastian Schaper <openwrt@sebastianschaper.net>

### CODE REVIEW

**Comment by s-2** [comment]
@stintel Thanks for testing, I've split this up to have the spi frequency increase in a separate commit.

Should I add your `Testted-By:` to the commit message? (Feel free to do so if you consider to merge this)

**Comment by stintel** [comment]
Ahh wait. I only tested 1 commit. I'll retest with both, and I'll merge if my AP is still working then ;-)

**Comment by s-2** [comment]
> Ahh wait. I only tested 1 commit. I'll retest with both, and I'll merge if my AP is still working then ;-)

It was indeed only one commit in the previous branch, I've split this up to explicitly declare the increase of spi frequency; i.e. the frequency will be deleted anyways by the second commit, since it comes from dtsi :slightly_smiling_face:

**Comment by stintel** [comment]
OK. Can you maybe explain why the SPI frequency has to be increased in the commit message of the first commit? It's not really clear from the current message.

**Comment by s-2** [comment]
I've noticed with previous pull requests, that changes to the spi frequency are usually placed into a seperate commit, as not to "hide" the change behind an unconspicuous commit message like "merge with dtsi".

Any suggestion on how to reword the first commit message? It basically means "it will be increased anyways by the next commit, and it works fine"

**Comment by stintel** [comment]
Something like "Once we merge this DTS with the DTSI, the SPI frequency will be increased. Increase the speed before merging with the DTSI to make this change more visible." ?

**Comment by s-2** [comment]
splitted device model spelling into separate commit

restored previously improved commit message (spi frequency increase) after rebase

**Comment by adschm** [comment]
Strange, for some reason it appears as if I commented in your local repository. I will put the relevant stuff here again.

**Comment by adschm** [comment]
> There seem to be two competing ways of declaring the position of wifi calibration data, the extraction script 10-ath9k-eeprom and the declaration via devicetree.
> I recall asking in openwrt#3471 whether any of these methods would be preferred; using the devicetree has the disadvantage of requiring an entry in 10_fix_wifi_mac (since the ascii hex format is currently unsupported by nvmem-cells), however the solution is at least partly upstream-compatible, thus it was chosen for the DAP-2660/2230/3320/2680/3662 series.
> Reusing the existing dtsi involves adapting DAP-2695 to this method as well.

My understanding is that 10-ath9k-eeprom and mtd-cal-data are not the same. But I'm no expert with this. Maybe @blocktrron can help?

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 3d896850885d3d721018aa742b1c7471155b78f0, be88f416db0a7ba7064c1b8bcb9556452d0729d3 and 25df32708606a364322cb721492241bb6e5c66f4.

**Pull request closed without merging**
