### PR TITLE
qualcommax: use PHY regulator for USB GPIO

### PR DESCRIPTION
**Pull request by neheb**
The PHY can handle turning off the GPIOs when turning off all USB ports.

ping @robimarko

### CODE REVIEW

**Comment by neheb** [comment]
Maybe this should be vdda-phy-provider based on phy-qcom-qmp-usb.c

@robimarko what do you think?

**Comment by neheb** [comment]
Yeah, definitely.

**Comment by neheb** [comment]
Upstream IPQ8074-HK01 uses ss_phy instead. Hrm.

**Comment by aiamadeus** [comment]
> Upstream IPQ8074-HK01 uses ss_phy instead. Hrm.

I think we should use vdd-supply for usb3.0 5v:
https://github.com/torvalds/linux/blob/adc218676eef25575469234709c2d87185ca223a/arch/arm64/boot/dts/qcom/ipq5332-rdp468.dts#L101

**Comment by neheb** [comment]
I can't see where vdd is specified as the name in the drivers:

```
$ git grep \"vdd\" drivers/phy/
drivers/phy/qualcomm/phy-qcom-m31.c:    qphy->vreg = devm_regulator_get(dev, "vdd");
drivers/phy/qualcomm/phy-qcom-qusb2.c:  "vdd", "vdda-pll", "vdda-phy-dpdm",
drivers/phy/qualcomm/phy-qcom-snps-eusb2.c:     "vdd", "vdda12",
drivers/phy/qualcomm/phy-qcom-usb-hs-28nm.c:    priv->vregs[VDD].supply = "vdd";
drivers/phy/qualcomm/phy-qcom-usb-ss.c: priv->regs[0].supply = "vdd";
$ git grep qcom,ipq8074-qusb2-phy drivers/
drivers/phy/qualcomm/phy-qcom-qusb2.c:          .compatible     = "qcom,ipq8074-qusb2-phy",
$ git grep qcom,ipq8074-qmp-usb3-phy drivers/
drivers/phy/qualcomm/phy-qcom-qmp-usb.c
```

**Comment by robimarko** [comment]
Any chance you can include ipq60xx as well?

It would be nice to get rid of custom regulators if this works

**Comment by robimarko** [comment]
Works on MR7350, so I assume it will just work on others as well :)

**Comment by aiamadeus** [comment]
I didn't notice that the dts change of ax89x had errors until merged.
```
phy-qcom-qusb2.c -> qusb_phy
drivers/phy/qualcomm/phy-qcom-qusb2.c:  "vdd", "vdda-pll", "vdda-phy-dpdm",
phy-qcom-qmp-usbc.c -> ssphy
drivers/phy/qualcomm/phy-qcom-qmp-usbc.c:    "vdda-phy", "vdda-pll",
```
So it should be vdd-supply for qusb_phy_0/1.

**Pull request merged**
