### PR TITLE
rockchip: add more Radxa boards

### PR DESCRIPTION
**Pull request by RadxaNaoki**
~~it depends on https://github.com/openwrt/openwrt/pull/15815 and https://github.com/openwrt/openwrt/pull/15861~~

### CODE REVIEW

**Comment by RadxaNaoki** [comment]
this add support for

- Radxa ROCK Pi E v3.0
- Radxa ROCK 3A/3B/3C
- Radxa ZERO 3E/3W

**Comment by maurerr** [comment]
I believe we don't merge off-tree kernel patches for rockchip - considering some of the boards (like zero3 e/w + rock3a/c) are due for 6.11 and rock3b is under review - l likely to land also in 6.11 and 6.12.
Also u-boot patches should come from upstream.
cc @1715173329

**Comment by RadxaNaoki** [comment]
since 2016, I sent some patches to add new devices (ath79 and ramips). at that time, all of them were not from upstream.

https://openwrt.org/docs/guide-developer/toolchain/use-patches-with-buildsystem#naming_patches

only 0xx patch is backport (from upstream) patch.

**Comment by 1715173329** [comment]
ath79/mediatek/ramips are the exceptions. However, for rockchip, these board patches (not including openwrt-specific ones) should be sent upstream and accepted.

**Comment by 1715173329** [comment]
And please write hardware specification & installation instruction in commit message for each board like #14740.

**Comment by RadxaNaoki** [comment]
> And please write hardware specification & installation instruction in commit message for each board like #14740.

I was thinking to do it (I thought it will be mentioned by review). but, this PR will not be merged, is there any reason to continue my work???

**Pull request closed without merging**
