### PR TITLE
ath10k-ct bump

### PR DESCRIPTION
**Pull request by xback**
This first updates ath10k-ct to the latest version,
and then we switch from 6.2 to 6.4.

Both commits have been running on hundreds of devices in the field
covering both wave 1 and wave 2 chipsets, and both PCI and AHB sources.

### CODE REVIEW

**Comment by raenye** [comment]
Still no 802.11s in CT drivers, right?

**Comment by filippz** [comment]
Sorry to be late to report  but for me on C2600 this one seems to break WiFi leds as there are no in `ath10k-phy0` and `ath10k-phy1` in `/sys/class/leds`.
Can anyone confirm that the WiFi leds are working for them with this PR as I might be barking at the wrong tree?

**Comment by hnyman** [comment]
> Sorry to be late to report but for me on C2600 this one seems to break WiFi leds 

I noticed the same, and authored the PR #13949 to fix the LEDs (and other issues).

(This PR overlooked all our local patches that contained explicit references to "ath10k-6.2" path.)

**Comment by filippz** [comment]
Off topic - while debugging this one I noticed that after switching to DSA that `white:lan` is always on even if no cable is plugged in any of `lanX `ports. Changing netdev from `br-lan` to `eth1` doesn't help - only manually selecting any of `lanX `makes that led to go to off. I'll try to investigate it further...

**Comment by castillofrancodamian** [comment]
The device directly runs out of memory for me and restarts.

**Pull request merged**
