### PR TITLE
ar71xx: add support for UniFi-AC-Mesh-Pro

### PR DESCRIPTION
**Pull request by achterin**
This adds the build option for UniFi AC Mesh Pro as well as model detection for it.
The device is a hardware clone of the AC Pro.

- SoC: QCA9563-AL3A (775Mhz)
- RAM: 128MiB
- Flash: 16MiB - dual firmware partitions!
- LAN: 2x 1000M - POE+
- Wireless:
        2.4G: QCA9563
          5G: UniFi Chip, QCA988X compatible

### CODE REVIEW

**Comment by lucize** [comment]
did you tried this https://github.com/openwrt/openwrt/pull/1090 ? is not working for you ?

**Comment by achterin** [comment]
no i did not because it isnt upstream yet and i wanted to use that code in gluon which is based on lede-17.01. but i can try it next week when i dont need the devices in production anymore.

**Comment by mkresin** [comment]
May I've missed something, but the only change I'm able to spot in compare to the current image is that the model is reported as "Ubiquiti UniFi-AC-MESH-PRO" instead of "Ubiquiti UniFi-AC-PRO" and an identical image to the ubnt-unifiac-mesh-pro one is created. I mean, even the userspace boardname is the same for both boards.

I've to admit, I don't see much gain in merging this, especially considering that the ath79 image already reports the model as "Ubiquiti UniFi-AC-PRO/MESH PRO".

**Comment by achterin** [comment]
@mkresin: understandable. the reason i applied the changes is, that i want to use this code in the gluon project. gluon comes with several settings preconfigured for certain devices. as you might know some 5ghz channels are prohibited to use outdoors in the eu. therefore one needs to know if its an AP AC Pro (indoor device) or an AC Mesh Pro (outdoor).
As the next gluon version will be based on OpenWrt 18.06, which does not contain ath79 yet, i need the ar71xx variant.
It would be nice if you could reconsider your opinion on this because the gluon project does not allow openwrt changes that aren't upstream which means that this model detection will not be present while AP AC Lite/AC Mesh detection is.

**Comment by mkresin** [comment]
Support for the UniFi-AC-Mesh-Pro was merged to the ath79 subtarget. I see more no than a little chance that this PR will be ever merged. Hence I'll close the PR.

If you disagree with the my decision, please start a discussion on the OpenWrt development mailinglist.

**Pull request closed without merging**
