### PR TITLE
ramips: add support for TP-Link Deco M4R v4 

### PR DESCRIPTION
**Pull request by shizmob**
This adds support for the V4 hardware revision of the Deco M4R.
It is a complete overhaul compared to the V1 and V2, and is much more similar to the Archer C6 V3 and C6U V1.

Specifications:

SoC: MediaTek MT7621AT (2 cores at 880 MHz, 4 threads)
RAM: Kingston D1216ECMDXGJD (256 MB)
Wireless 2.4 GHz: MediaTek MT7603EN
Wireless 5 GHz: MediaTek MT7613BEN
Flash: 16 MB SPI NOR

Installation:

Flash the *-factory.bin image in the U-Boot recovery webserver.
You can trigger this webserver by holding the reset button until the LED flashes yellow,
or by hooking up to serial pads on the board (clearly labeled GND, RX and TX) and pressing `x` early in boot.

Once the factory image has been flashed, you can use the regular upgrade procedure with sysupgrade images for subsequent flashes.

This change depends on commit 3657cf56708 ("tplink-safeloader: Add support for Deco M4R V4") in firmware-utils;
this PR bumps it, but since said repo is not on GitHub, it would require cherry-picking https://github.com/Shizmob/openwrt-firmware-utils/commit/3657cf567082a7b57b56b551c833f8ec64ccae4c and possibly adjusting 3c4b4e7362d3c6ceff93f62e5a92787df638f790 before merging.

### CODE REVIEW

**Comment by Shizmob** [comment]
Force-pushed to fix formalities, apologies.

**Comment by Shizmob** [comment]
It seems failing checks are due to the dependency on https://github.com/Shizmob/openwrt-firmware-utils/commit/3657cf567082a7b57b56b551c833f8ec64ccae4c to be merged upstream.

**Comment by Shizmob** [comment]
Formalities, round two.

**Comment by Shizmob** [comment]
Pushed https://github.com/Shizmob/openwrt-firmware-utils/commit/c8810120985839c919307a7be9dec99d086da8d0 which also takes care of the formalities there, and updated this PR to match. Should I send out a patch for that separately to the mailing list, or can you merge it @hauke?

**Comment by Shizmob** [comment]
Friendly ping :)

**Comment by Shizmob** [comment]
Ping!

**Comment by hauke** [comment]
Please send https://github.com/Shizmob/openwrt-firmware-utils/commit/c8810120985839c919307a7be9dec99d086da8d0 as a patch if you haven't done yet.

**Comment by Shizmob** [comment]
Thanks, it's available at https://patchwork.ozlabs.org/project/openwrt/patch/mailman.6856.1674388248.3064139.openwrt-devel@lists.openwrt.org/ now.

**Comment by Shizmob** [comment]
The `firmware-utils` patch has been merged, this PR is now ready.

**Pull request merged**
