### PR TITLE
ar71xx: add support for Hak5 WiFi Pineapple MK5

### PR DESCRIPTION
**Pull request by K0HAX**
This adds support for an AR9331 based Hak5 penetration testing tool:

- WiFi Pineapple MK5

WiFi Pineapple MK5 specifications:

- SoC: Atheros AR9331
- RAM: 64 MB (DDR2)
- FLASH: 16 MB
- WiFi: Realtek RTL8187L
- Ethernet: 1x Fast Ethernet
- Ports: 2x RP-SMA for antennas, 1x USB 2.0 (host), 1x micro SD
- Power: 5-12 volts, 1A, 5.5mmx2.1mm (Type M Barrel) connector
- Other: Status LEDs

Flash instructions:

Original firmware is based on OpenWRT.
Use sysupgrade via SSH to flash.

Signed-off-by: Michael Englehorn <michael@englehorn.com>

### CODE REVIEW

**Comment by K0HAX** [comment]
Just a note, most of the code originated from Hak5's old OpenWRT sources that I got here: http://wifipineapple.com/mk5/source.tar.gz and ported to `master`

I tested with my own Pineapple MK5.

**Comment by bobafetthotmail** [comment]
the devices in ar71xx are being migrated to device tree and more modern base scripts in the ath79 target, the ar71xx target will eventually be dropped.

You might want to make a PR for the ath79 target too.

**Comment by ynezz** [comment]
@K0HAX As already suggested by @bobafetthotmail, it's pretty hard to get anything included in ar71xx these days, new development should simply happen in ath79 (DTS based ar71xx successor). Thanks!

**Comment by K0HAX** [comment]
Is there a guide to building an ath79 target that automatically detects the partition table like ar71xx does? I don't know how to build an ath79 target.

**Pull request closed without merging**
