### PR TITLE
fritz-tools: fritz_tffs_nand: cache already read sector ids

### PR DESCRIPTION
**Pull request by dhewg**
This speeds up the tool significantly, especially when using the "-a" argument.
Including two preparatory cleanup patches.

/cc past committers as potential reviewers @kestrel1974 @blocktrron @AndyX90

### CODE REVIEW

**Comment by dhewg** [comment]
Anyone? This PR is close to it's first birthday :)

Based on its commit history, maybe @kestrel1974  or @blocktrron?

**Comment by blocktrron** [comment]
I just now saw this by accident. Looks good to me.

**Comment by dhewg** [comment]
Did you mean to push this? :D

**Comment by blocktrron** [comment]
It is in my staging tree, I will push it to master with the next iteration. I'm currently busy, but I'll try to make it this weekend.

**Pull request closed without merging**
