### PR TITLE
mediatek: add support for TP-Link TL-XDR4288/608x

### PR DESCRIPTION
**Pull request by aiamadeus**
```
Hardware specification:
  SoC: MediaTek MT7986A 4x A53
  Flash: ESMT F50L1G41LB 128MB
  RAM: ESMT M15T4G16256A 512MB
  Ethernet (Max Speed):
    XDR6086: 1x 2.5G Wan, 1x 2.5G Lan, 1x 1G Lan
    XDR6088: 1x 2.5G Wan, 1x 2.5G Lan, 4x 1G Lan
  WiFi1: MT7976GN 2.4GHz ax 4x4
  WiFi2: MT7976AN 5GHz ax 4x4
  Button: Reset, Wps, Turbo
  Power: DC 12V 4A
```

### CODE REVIEW

**Comment by aiamadeus** [comment]
@boretom You can retest wax206 with my patch.

**Comment by boretom** [comment]
> @boretom You can retest wax206 with my patch.

Hey @aiamadeus thanks a lot for pointing me to your patch. I'll give it a go this weekend and report back.

**Comment by boretom** [comment]
@aiamadeus I have your patch "generic: 5.15: update rtl8221 phy driver"/commit 64c6128 a go and it works well, amazing and thanks.

There is one caveat: I can't change the speed to 2500 using ethtool.

```
# set it to 1G/Full Duplex
ethtool -s wan speed 1000 duplex full
# dmesg
[ 1104.981491] mt7530 mdio-bus:00 wan: Link is Down
[ 1108.127859] mt7530 mdio-bus:00 wan: Link is Up - 1Gbps/Full - flow control rx/tx

# set it to 2.5G/Full Duplex
ethtool -s wan speed 2500 duplex full
# dmesg 
[ 1215.394041] mt7530 mdio-bus:00 wan: Link is Down

# what works is use auto-neg
ethtool -s wan autoneg on
# dmesg
[ 1320.207383] mt7530 mdio-bus:00 wan: Link is Up - 2.5Gbps/Full - flow control rx/tx
```

The switch used for testing is a QNAP QSW-M1204-4C.

**Comment by ptpt52** [comment]
mark

**Comment by nasbdh9** [comment]
phy driver there are still pending fixes related to submission to upstream, have you read from https://forum.openwrt.org/t/adding-support-for-tp-link-xdr-6086/140637/ from 97 to 116

**Comment by aiamadeus** [comment]
> phy driver there are still pending fixes related to submission to upstream

That is more related to mt7531, I just patch the rtl8221 phy to work like the gpy211 phy in kernel.

**Comment by Borromini** [comment]
Can you add flashing & recovery instructions to the commit message itself please, as requested for commits adding device support? The links in your commit message will die at some point, and become useless.

Thanks!

**Comment by hauke** [comment]
Please send the Realtek driver patch also to the Linux netdev mailing list to get it integrated into upstream Linux kernel.

**Comment by boretom** [comment]
An addition to me earlier remark about not being able to set speed to 2.5G using `ethtool`:
Using the `ethtool-full` package instead of `ethtool` I'm able to manually set the speed to 2.5G too. Not an issue with the driver!

**Comment by cyyself** [comment]
I have the TL-XDR6088 and tested your patch with mainline OpenWRT commit `1d82a47b497e11e2474703ab8e3ef6994d33809d`. 

The LAN-5 Port (which is RTL8221B PHY connected to the MT7531 switch) works fine. But the WAN port which is directly connected to gmac1 is still having trouble with 1G speed although the 2.5G speed works. 

Furthermore, the LED of the 2.5G Ports didn't light, but it can be simply fixed by setting MDIO registers which I have done before [here](https://github.com/cyyself/openwrt/blob/99e434c513987a2a3aeeaad01ee582b9e725f148/target/linux/mediatek/patches-5.15/932-rtk822x-xdr6088.patch#L211).

**Comment by aiamadeus** [comment]
> Please send the Realtek driver patch also to the Linux netdev mailing list to get it integrated into upstream Linux kernel.

This patch depends on the rtl8221b_config_init patch from @lynxis, and I don't find the status of his patch.
> But the WAN port which is directly connected to gmac1 is still having trouble with 1G speed although the 2.5G speed works.

Reading through the mtk_eth driver in the mtk sdk, they made a change to fix this, and @lynxis has done this before: https://github.com/lynxis/openwrt/commit/9ff250f52a29329f0963702bbc8abe56b99f6d68 . I know @dangowrt currently working on improving this, maybe can offer advice.

**Comment by cyyself** [comment]
I did some debugging and find out the WAN port only advertises 2500BaseT/Full speed, so a 1G speed link partner will not work. You can take [this patch](https://github.com/cyyself/openwrt/commit/3db00b16acc3ff49859339b87d534d05aad5c24f) then WAN at 1G speed will work.

However, I've tested the WAN port with 100Mbps and 10Mbps, there is a bug that if we run iperf between WAN and LAN, we will get mtk_soc_eth transmit queue timed out.

Here is dmesg log:

```
[  218.932170] mtk_soc_eth 15100000.ethernet eth1: Link is Up - 100Mbps/Half - flow control off
[  236.577240] mtk_soc_eth 15100000.ethernet eth0: Link is Down
[  236.582915] mtk_soc_eth 15100000.ethernet eth1: Link is Down
[  236.835704] mtk_soc_eth 15100000.ethernet: warm reset failed
[  236.855130] mtk_soc_eth 15100000.ethernet eth0: configuring for fixed/2500base-x link mode
[  236.863516] mtk_soc_eth 15100000.ethernet eth0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[  237.014621] mtk_soc_eth 15100000.ethernet eth1: PHY [mdio-bus:07] driver [RTL8221B-VB-CG 2.5Gbps PHY] (irq=POLL)
[  237.024777] mtk_soc_eth 15100000.ethernet eth1: configuring for phy/sgmii link mode
[  240.204178] mtk_soc_eth 15100000.ethernet eth1: Link is Up - 100Mbps/Half - flow control off
[  241.883063] ------------[ cut here ]------------
[  241.887684] NETDEV WATCHDOG: eth0 (mtk_soc_eth): transmit queue 3 timed out
[  241.894648] WARNING: CPU: 2 PID: 0 at dev_watchdog+0x330/0x33c
[  241.900469] Modules linked in: qcserial pppoe ppp_async option cdc_mbim wireguard usb_wwan sierra_net sierra rndis_host qmi_wwan pppox ppp_generig
[  241.900633]  nf_flow_table nf_conncount libcurve25519_generic libchacha iptable_raw iptable_nat iptable_mangle iptable_filter ipt_ECN ip_tables hd
[  241.987700]  xhci_pci xhci_mtk_hcd xhci_hcd gpio_button_hotplug xfs vfat fat exfat btrfs xor xor_neon raid6_pq libcrc32c usbcore usb_common mii
[  242.087219] CPU: 2 PID: 0 Comm: swapper/2 Not tainted 5.15.94 #0
[  242.093206] Hardware name: TP-Link TL-XDR6088 (DT)
[  242.097977] pstate: 60000005 (nZCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[  242.104917] pc : dev_watchdog+0x330/0x33c
[  242.108911] lr : dev_watchdog+0x330/0x33c
[  242.112905] sp : ffffffc008babdb0
[  242.116203] x29: ffffffc008babdb0 x28: 0000000000000140 x27: 00000000ffffffff
[  242.123319] x26: 0000000000000000 x25: 0000000000000002 x24: ffffff80057b9478
[  242.130434] x23: 0000000000000000 x22: 0000000000000001 x21: ffffffc008a76000
[  242.137552] x20: ffffff80057b9000 x19: 0000000000000003 x18: ffffffc008a8a260
[  242.144668] x17: ffffffc017453000 x16: ffffffc008bac000 x15: 0000000000000399
[  242.151783] x14: 0000000000000133 x13: ffffffc008babad8 x12: ffffffc008ae2260
[  242.158898] x11: 712074696d736e61 x10: ffffffc008ae2260 x9 : 0000000000000000
[  242.166014] x8 : ffffffc008a8a210 x7 : ffffffc008a8a260 x6 : 0000000000000001
[  242.173130] x5 : 0000000000000000 x4 : 0000000000000000 x3 : 0000000000000000
[  242.180244] x2 : 0000000000000040 x1 : 0000000000000004 x0 : 000000000000003f
[  242.187361] Call trace:
[  242.189794]  dev_watchdog+0x330/0x33c
[  242.193442]  call_timer_fn.constprop.0+0x20/0x80
[  242.198043]  __run_timers.part.0+0x208/0x284
[  242.202296]  run_timer_softirq+0x38/0x70
[  242.206202]  _stext+0x10c/0x28c
[  242.209329]  __irq_exit_rcu+0xdc/0xfc
[  242.212978]  irq_exit+0xc/0x1c
[  242.216018]  handle_domain_irq+0x60/0x8c
[  242.219928]  gic_handle_irq+0x50/0x120
[  242.223662]  call_on_irq_stack+0x28/0x44
[  242.227570]  do_interrupt_handler+0x4c/0x54
[  242.231735]  el1_interrupt+0x2c/0x4c
[  242.235298]  el1h_64_irq_handler+0x14/0x20
[  242.239379]  el1h_64_irq+0x74/0x78
[  242.242764]  arch_cpu_idle+0x14/0x20
[  242.246325]  do_idle+0xc0/0x150
[  242.249455]  cpu_startup_entry+0x20/0x60
[  242.253362]  secondary_start_kernel+0x130/0x140
[  242.257876]  __secondary_switched+0x50/0x54
[  242.262044] ---[ end trace ea3d8373391c8919 ]---
```

**Comment by dangowrt** [comment]
Please do `make target/linux/refresh` and add changed patches to their respective commits. Otherwise looks good to go.

**Comment by dangowrt** [comment]
The 2.5G PHYs should work as expected with https://github.com/openwrt/openwrt/pull/12317 . Please test and report.

**Comment by geberl** [comment]
Apologies for my ignorance, I don't know if this is even the correct thread.

Today's snapshot release killed the WAN port on my Netgear WAC206 (lan ports still working fine). I can't say that it worked yesterday, but my previous version from around 2 weeks ago worked nicely with that port. I only tried connecting it to gigabit ethernet though, not 2.5G (no equipment). ifconfig shows some bytes in TX, but 0 bytes in RX.

**Comment by dangowrt** [comment]
@geberl This should be [fixed now](https://forum.openwrt.org/t/netgear-wax206-issue-wan-last-snapshot-r22459/156195/11?u=daniel) by #12317 which [has been merged today](https://github.com/openwrt/openwrt/commit/d98c8fc06ddd36f4b47c0eef8094e68257b92f87). Tomorrow's snapshot should hence work again on the WAX206.

**Comment by cyyself** [comment]
I've tested this patch. I came across 3 issues:

1. The WAN port only works at 2.5G and 1G speeds. I think it could be simply fixed since we have SGMII and HSGMII switch works.

2. The ethtool on the router side didn't show the proper advertised link mode on the WAN port (which PHY directly connects to SoC eth1). The Router will advertise 2.5G and 1G to the link partner, but the ethtool didn't show the 1G speed advertised.

    Here is the ethtool output on the router side.

    ```bash
    root@OpenWrt:/# ethtool eth1
    Settings for eth1:
            Supported ports: [ TP    MII ]
            Supported link modes:   2500baseT/Full
            Supported pause frame use: Symmetric Receive-only
            Supports auto-negotiation: Yes
            Supported FEC modes: Not reported
            Advertised link modes:  2500baseT/Full
            Advertised pause frame use: Symmetric Receive-only
            Advertised auto-negotiation: Yes
            Advertised FEC modes: Not reported
            Link partner advertised link modes:  1000baseT/Full
            Link partner advertised pause frame use: Symmetric Receive-only
            Link partner advertised auto-negotiation: Yes
            Link partner advertised FEC modes: Not reported
            Speed: 1000Mb/s
            Duplex: Unknown! (255)
            Auto-negotiation: on
            master-slave cfg: preferred slave
            master-slave status: master
            Port: Twisted Pair
            PHYAD: 7
            Transceiver: external
            MDI-X: Unknown
            Current message level: 0x000000ff (255)
                                drv probe link timer ifdown ifup rx_err tx_err
            Link detected: yes
    ```

    Here is the ethtool output on the link partner side:

    ```bash
    ➜  ~ sudo ethtool enp7s0
    Settings for enp7s0:
        Supported ports: [ TP	 MII ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
                                2500baseT/Full
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  1000baseT/Full
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Link partner advertised link modes:  1000baseT/Full
                                            2500baseT/Full
        Link partner advertised pause frame use: Symmetric Receive-only
        Link partner advertised auto-negotiation: Yes
        Link partner advertised FEC modes: Not reported
        Speed: 1000Mb/s
        Duplex: Full
        Auto-negotiation: on
        master-slave cfg: preferred slave
        master-slave status: slave
        Port: Twisted Pair
        PHYAD: 0
        Transceiver: external
        MDI-X: Unknown
        Supports Wake-on: pumbg
        Wake-on: d
        Link detected: yes
    ```


3. The LED of 2.5G PHY didn't light. But it can be simply fixed by adding some MDIO write in the PHY initialization code.

**Comment by dangowrt** [comment]
Thank you for testing all this. Looks like the RealTek PHY driver is as broken as it could possibly get.
https://github.com/torvalds/linux/commit/74d155be2677a6e0df0a41487d3ca217bd756604 obviously wasn't tested at all...

**Comment by cyyself** [comment]
> Thank you for testing all this. Looks like the RealTek PHY driver is as broken as it could possibly get. [torvalds/linux@74d155b](https://github.com/torvalds/linux/commit/74d155be2677a6e0df0a41487d3ca217bd756604) obviously wasn't tested at all...

I want to add some information. I tried to reboot my TP-Link XDR6088 and connect to the different switch and NIC on eth1, I found that this issue only happens when the eth1 connects to a 2.5G capable device for the first time after reboot. If the first eth1 connects to a 1G link partner for the first time after reboot, everything works fine. I will try to debug the kernel.

**Comment by cyyself** [comment]
@dangowrt I found the issues about speed advertised in an on eth1 of xdr6088 can be simply fixed by [this hack](https://github.com/cyyself/linux/commit/9046727d3fb108ef9727d4e3c382cefe2a76cda7). 

And I found that the kernel without this hack only works when we have ethernet plugged into eth1 without 2.5G capability on the link partner side.

**Comment by dangowrt** [comment]
The hack is obsolete and also not needed for other PHY drivers. If the PHY driver correctly announces it's capabilities, generic phylink validate should just do the job, there is no need for hacks like that. With GPY211 it also works without such hacks. If you want to help, please try implementing `.read_status` and `.config_aneg` for RTL822x which actually works. That will fix it. I will also have the XDR-6068 hardware in a couple of days (or weeks, depends on postal service and customs) and can do it then.

**Comment by ptpt52** [comment]
Forgive me if this is off-topic, but I have a question about gpio-i2c. It seems that i2c-gpio doesn't function on the mt7981 system-on-chip, as the hardware is unable to detect a signal on pins 22 and 23. Is there anything specific that needs to be done to resolve this issue?
@dangowrt 
```
        i2c_0: i2c@0 {
                compatible = "i2c-gpio";
                #address-cells = <1>;
                #size-cells = <0>;
                sda-gpios = <&pio 22 (GPIO_ACTIVE_HIGH | GPIO_OPEN_DRAIN)>;
                scl-gpios = <&pio 23 (GPIO_ACTIVE_HIGH | GPIO_OPEN_DRAIN)>;
                i2c-gpio,delay-us = <2>;
        };
```
boot log:
```
[    8.648006] i2c-gpio i2c@0: using lines 477 (SDA) and 478 (SCL)
```
cat /sys/kernel/debug/gpio
```
root@X-WRT:~# cat /sys/kernel/debug/gpio 
gpiochip0: GPIOs 455-511, parent: platform/11d00000.pinctrl, pinctrl_moore:
 gpio-456 (                    |reset               ) in  hi IRQ ACTIVE LOW
 gpio-459 (                    |reset               ) out hi 
 gpio-460 (                    |PHY reset           ) out hi 
 gpio-467 (                    |mdio                ) out lo 
 gpio-468 (                    |mdio                ) in  hi 
 gpio-469 (                    |PHY reset           ) out hi ACTIVE LOW
 gpio-477 (                    |sda                 ) out lo 
 gpio-478 (                    |scl                 ) out lo 
 gpio-479 (                    |sda                 ) out lo 
 gpio-480 (                    |scl                 ) out hi 
 gpio-489 (                    |green:system        ) out hi ACTIVE LOW
 gpio-490 (                    |red:run             ) out lo ACTIVE LOW
 gpio-494 (                    |reset               ) out hi 
```

**Comment by dangowrt** [comment]
@ptpt52 You may need to use pinconf to setup the pins' `conf-pu` and `conf-pd` drive-strength and bias.

**Comment by ptpt52** [comment]
> @ptpt52 You may need to use pinconf to setup the pins' `conf-pu` and `conf-pd` drive-strength and bias.

it looks like that it is not related to pinconf.

It was discovered through testing that GPIO 6 and 7 can be used to simulate I2C, and GPIO 30 and 31 can be used to simulate I2C as well.

for other gpios they cannot work well on 7981.

**Comment by cyyself** [comment]
@dangowrt I found an issue that if connect to non 2.5G link partner and then `ip link set eth1 down` and then set back to up will destroy 2.5G AN. 

Procedure:
1. Connect 1G/100M/10M link partner to eth1
2. `ip link set eth1 down` and then `ip link set eth1 up`
3. We will get `mtk_soc_eth 15100000.ethernet eth1: configuring for phy/sgmii link mode` in dmesg, but we expect `phy/2500base-x link mode`, and then 2500M/Full speed will not advertise anymore.

I tried switching back to 2500BASEX mode in the PHY driver in `link_change_notify` and `rtl822x_read_status`, but it doesn't work due to the kernel will not pass the newly updated `phydev->interface` value to `pl->link_config.interface` to validate. And it's hard to fix due to [this is a feature for Clause 45 PHYs](https://github.com/torvalds/linux/commit/e45d1f5288b81e77eb87288ae2d0a0d00e0989d3).

**Comment by ptpt52** [comment]
> @ptpt52 You may need to use pinconf to setup the pins' `conf-pu` and `conf-pd` drive-strength and bias.

great thanks. this it the point to the issue. but I have to backport the pinconf changes from your linux code: https://github.com/dangowrt/linux.git to make it works.

the bias or drive-strength do not work with the linux code in openwrt now.

**Comment by dangowrt** [comment]
@ptpt52 Yes, true, we need to sync pinctrl-mt7981.c and backport some pinconf features for that. I've prepared https://github.com/openwrt/openwrt/pull/12384 for that, please give it a shot and let me know if it improves I2C (and possibly also GPIO-driven MDIO)

**Comment by dangowrt** [comment]
* RealTek PHYs fixed
 * U-Boot now has correct MAC address and Linux eth0 inherits it
 * make sure U-Boot environment can be created and (re-)format UBI otherwise
 
Merged via https://github.com/openwrt/openwrt/commit/21be2c26d555b33e9faf85be3e980876810b29d3

**Comment by dangowrt** [comment]
@cyyself
> And it's hard to fix due to [this is a feature for Clause 45 PHYs](https://github.com/torvalds/linux/commit/e45d1f5288b81e77eb87288ae2d0a0d00e0989d3).

As the PHY does identify correctly also when using C45 bus access, the easy fix is to set `compatible = "ethernet-phy-ieee802.3-c45";` for both PHYs ;)

**Comment by v4lkyr** [comment]
I have a router with the same 2.5G chip and it's not working in latest openwrt build.

**Comment by dangowrt** [comment]
@v4lkyr Please share informaton about the exact model and device tree you are using as well as a complete boot log -- without that it will be impossible to analyze the problem, as TL-XDR device added in this PR are all working fine.
Note that there have been various internal revisions of those RealTek 2.5G PHYs and also some vendor bootloaders at times do weird things with them before lauching OpenWrt/Linux...

**Pull request closed without merging**
