### PR TITLE
build: Allow specifying uImage time

### PR DESCRIPTION
**Pull request by yangfl**
Some U-Boot checks for a specified uImage time and refuses to boot if mismatched. This patch fixes it by recognizing UIMAGE_TIME parameter.

Signed-off-by: David Yang <mmyangfl@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@yangfl I wonder if an alternative would be to set the env before? Or this may be problematic for other tool part of the image build?

**Comment by yangfl** [comment]
@Ansuel no one use UIMAGE_TIME before. Setting SOURCE_DATE_EPOCH golbally would be too destructive for other parts other than uimage build.

**Comment by robimarko** [comment]
This is going to make images unreproducible

**Comment by robimarko** [comment]
Indeed, I though you would just use the build time in the device recipe instead, that would make it unreproducible.

**Comment by yangfl** [comment]
If (if I'm correct) UIMAGE_TIME is not set in device recipe, how could this affect SOURCE_DATE_EPOCH?

**Comment by Ansuel** [comment]
> @Ansuel no one use UIMAGE_TIME before. Setting SOURCE_DATE_EPOCH golbally would be too destructive for other parts other than uimage build.

it was just an idea if we could find a way to find a workaround instead of adding an additional option

**Comment by yangfl** [comment]
nah... we could create another build command say 'uImage-fix-time', but that would require dirty hack on header crc and is not desirable I think.

**Comment by mpratt14** [comment]
`SOURCE_DATE_EPOCH` is a global variable, you either need to use the mkimage flags to manipulate the timestamp, or temporarily store the original value and then put it back after thia recipe

**Comment by yangfl** [comment]
Hey this is makefile... variable assignments won't last to other commands

**Comment by mpratt14** [comment]
they do if you export them

openwrt build system uses it as a global variable

from include/toplevel.mk

```
ifeq ($(SDK),1)
  include $(TOPDIR)/include/version.mk
else
  REVISION:=$(shell $(TOPDIR)/scripts/getver.sh)
  SOURCE_DATE_EPOCH:=$(shell $(TOPDIR)/scripts/get_source_date_epoch.sh)
endif

export REVISION
export SOURCE_DATE_EPOCH
```

**Comment by yangfl** [comment]
So you've seen it... Is there any `export` in this patch?

**Comment by mpratt14** [comment]
AFAIK you only need to export a variable once for a change to the value to apply to all subsequent calls to it, but I could be wrong... better to be safe than sorry

you can either set a temporary variable to store value of SOURCE_DATE_EPOCH

or we can patch mkimage to allow setting a custom time, similar to the patch to set a custom magic number

`tools/mkimage/patches/030-allow-to-use-different-magic.patch`

**Comment by mpratt14** [comment]
in fact: we can make a patch that uses your new variable `UIMAGE_TIME` first, and if `UIMAGE_TIME` is null, then it would try `SOURCE_DATE_EPOCH`

**Comment by yangfl** [comment]
Hmm. Please, make a tiny experiment:

```make
A:=1
export A

all:
  echo $(A)
  echo $$A
  A=2 echo $(A)
  A=2 echo $$A
  A=2
  echo $(A)
  echo $$A
```

**Comment by mpratt14** [comment]
that's a nice way to demonstrate, I also tested by applying the actual change to the build system

I also overlooked the backslash that makes it in the same line as the mkimage command, so you were right

however, the new variable `UIMAGE_TIME` needs to be added to the list of device vars, in my opinion this should be done in the commit here, not when a device that uses it is added

in `include/image.mk`

for `DEFAULT_DEVICE_VARS` add the variable to the list

for `Device/Init` define it as null

just like `UIMAGE_NAME`

I agree that this is the appropriate solution

**Comment by yangfl** [comment]
Let the maintainer judge this.

**Comment by mpratt14** [comment]
I think that if you update this commit the way I described it would be more acceptable (because of the new variable that you're introducing)

**Comment by yangfl** [comment]
Since you are misleading in makefile workflows I would like to wait others' reviews.

**Comment by aparcar** [comment]
I think this patch is fine, from my understanding you're just temporarily setting SOURCE_DATE_EPOCH for that single mkimage run. 

> however, the new variable UIMAGE_TIME needs to be added to the list of device vars, in my opinion this should be done in the commit here, not when a device that uses it is added

I agree, if not done a single device setting this value would affect all others.

**Comment by yangfl** [comment]
@aparcar ok, fixed

**Pull request merged**
