### PR TITLE
kernel: rtl8367b: fix and improve support

### PR DESCRIPTION
**Pull request by musashino205**
These commit fixes some issues and improve support for Realtek RTL8367B driver.

Tested on: I-O DATA WN-AC733GR3 (RTL8367RB)

### CODE REVIEW

**Comment by 981213** [comment]
Hi!
I'm not sure what to do with the line removed in 4th commit after changed in 3rd commit so I've just picked the first two commits in this PR as fixes first.

**Comment by musashino205** [comment]
Thank you for your review.

With the intent of making changes one by one, I've splitted those changes into two commits. If they can be merged into single commit, I'll do.

**Comment by musashino205** [comment]
I merged the last two commits into single commit.

**Comment by 981213** [comment]
Merged into my staging tree at: https://git.openwrt.org/?p=openwrt/staging/981213.git
Thanks!

**Pull request closed without merging**
