### PR TITLE
tools/mm-macros: remove

### PR DESCRIPTION
**Pull request by neheb**
ccaaab1c048159611e93a181dde740f49fa12483 says that this is in the
codebase because of libsigc++, which is not in the codebase anymore.
Neither in base nor in packages. It doesn't seem to be needed by
anything else either. GNOME packages have transitioned to using meson,
which does not use m4 files.

Tested local compile with CONFIG_ALL. No problems seen.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by aparcar** [comment]
Remove from tools/Makefile needed

**Comment by neheb** [comment]
Oh wow. I did this locally but didn't add it to git.

**Comment by neheb** [comment]
Removed.

**Comment by aparcar** [comment]
Happens to the best

**Comment by adschm** [comment]
OT: Sorry for commenting inline at the wrong repo, but GitHub's behavior change still does not match my behavior ;-)

**Review by aparcar — APPROVED** [review]

**Comment by neheb** [comment]
> OT: Sorry for commenting inline at the wrong repo, but GitHub's behavior change still does not match my behavior ;-)

They somewhat recently changed it. I hate it too.

**Comment by aparcar** [comment]
Merged, thanks

**Pull request closed without merging**
