### PR TITLE
QCA6390 (ath11k_pci) support

### PR DESCRIPTION
**Pull request by FlyGoat**
Tested on generic x86_64 machine with FN-Link QCAi6390 M.2 module.

### CODE REVIEW

**Comment by robimarko** [comment]
Are you sure that this works without MHI which is a hard dependency of ath11k PCI?
Like, it will fail to build without it, and the MHI is not really in the best shape in 5.10 which is why I chose not to make a PR for ath11k PCI support, its way to flaky in 5.10

Also, I don't like tying of ath11k PCI and the core module together.
And, are you sure that it works without further backports, cause just backports were not enough for me and QCA6390.

Did you package the QMI yourself or used the RFC that somebody already sent, cause it looks suspiciously similar to me

**Comment by FlyGoat** [comment]
> Are you sure that this works without MHI which is a hard dependency of ath11k PCI? Like, it will fail to build without it, and the MHI is not really in the best shape in 5.10 which is why I chose not to make a PR for ath11k PCI support, its way to flaky in 5.10

Hmm it only depends on qmi-helpers which is a part of this PR.

> 
> Also, I don't like tying of ath11k PCI and the core module together. And, are you sure that it works without further backports, cause just backports were not enough for me and QCA6390.

Probably it's a good idea to sepreate them, I'm just not sure how will IPQ guys handle ath10h_ahb. I'm just bindly copy the package of ath10k so...
Anything went wrong at your side?

> 
> Did you package the QMI yourself or used the RFC that somebody already sent, cause it looks suspiciously similar to me

Yes I packaged qmi-helper in first commit.

**Comment by FlyGoat** [comment]
Though I didn't do any intensive test, just tried to connect to a hotspot with it.

**Comment by FlyGoat** [comment]
Ahh, MHI is mandatory, I accidentally enabled it in my local kernel menuconfig...
So I have to package it as well.
Is it worthy to do sort of backport for 5.10?

**Comment by robimarko** [comment]
I actually did most of the work back in November, MHI needs some more love and ath11k needs patches to be updated.
https://github.com/sartura/openwrt/commits/ipq40xx-dsa-bit-qca6391

FW is also completely outdated in the linux-firmware, so using the ath11k-firmware repo would be better.

Now, since there is interest in PCI ath11k it looks to be worth the trouble.
I have updated the ath11k for IPQ807x anyway, but QRTR and MHI need more love.

I have time tomorrow, are you OK with me updating my old branch and making a PR out of that?

**Comment by FlyGoat** [comment]
Yep I'm in UTC. Will try to do it tommrrow, thanks for the pointing :-)

For MHI I guess bindly backport every commits from 5.10 to now will just work, the same for QRTR?

**Comment by robimarko** [comment]
No, that's the issue, you can't just backport MHI and QRTR to for example 5.15+, it wont work.
ath11k as well is not usable without further patches, that's why I asked if its OK that I update my work and make a PR

**Comment by FlyGoat** [comment]
> No, that's the issue, you can't just backport MHI and QRTR to for example 5.15+, it wont work. ath11k as well is not usable without further patches, that's why I asked if its OK that I update my work and make a PR

Ok, let me check tomorrow, thanks.

**Comment by FlyGoat** [comment]
After thinking over night, I think we'd better put our effort of backporting QRTR and MHI into -backport upstream. Cuz srivers in -backport tree is supposed to work without further backporting in main kernel tree.

**Comment by robimarko** [comment]
I dont really get your last comment, MHI and QRTR are not part of the backports at all

**Comment by FlyGoat** [comment]
> I dont really get your last comment, MHI and QRTR are not part of the backports at all

I meant we should add it to backport, not only in OpenWRT tree.

**Comment by robimarko** [comment]
Well not, they are not part of the wireless drivers at all

**Comment by FlyGoat** [comment]
ok, I'm now messing with QRTR stuff, thanks.

**Comment by FlyGoat** [comment]
I tried to work based backport tree and submited it to the upstream.
It seems like backport upstream is not against accepting them.

https://lore.kernel.org/backports/12bcca34-90ec-ca85-a95b-c067b35a47ae@hauke-m.de/T/#t

**Comment by FlyGoat** [comment]
@robimarko I'm starting work on your tree. I saw you mentioned `ATH11K_THERMAL` when packaging ATH11K but I can't find this Kconfig in upstream.

Is this intentional?

**Comment by FlyGoat** [comment]
Also I'm likely to leave ipq40xx stuff in that tree untouched since I'm know nothing about those SoCs :-(

**Comment by robimarko** [comment]
It's local to the mac80211 package, so that like on ath10k you can enable/disable it and it will pull in hwmon and thermal kmods.
Upstream just builds the thermal support if hwmon and thermal symbols are enabled in the kernel config.

Ignore the IPQ40xx changes, it was needed for the board I was testing with.

**Comment by hauke** [comment]
I think it makes sense to have these drivers in backports in general.
If these drivers are in backports they can only be used by drivers which are also in backports. The situation could be similar to ssb/bcma Broadcom bus abstraction, this was shipped by backports, but in OpenWrt we maintained our own in kernel backport which allowed OpenWrt to compile these drivers into the kernel.

If having the QRTR and mhi driver in backports will only break the QCom WWAN driver in OpenWrt I am fine with it.

**Comment by robimarko** [comment]
Yes, it should only potentially break the modem support though these modes are quite rare.
Other than that they are only used by ath11k so far, so if you are fine with keeping them in backports so they are synced to the driver even better.

ath11k is really being developed hard, so I have like 170 or so backported commits on top of the current 5.15 that we are using in the IPQ807x, most of them actually target PCI cards like QCA6390 and the WCN series.
Whats your opinion on keeping ath11k synced up with ath-next in OpenWrt on regular bases, because just cherry-picking here and there doesn't really work(Trust me I tried)?

**Comment by FlyGoat** [comment]
If it's necessary I may try to add those WWAN device to backport as well.
I do have a SDX55 on my laptop to test :-)

**Comment by FlyGoat** [comment]
@robimarko Are there any notable change for QRTR and MHI in ath-next? If not we may handle it in ath10k-ct way?

**Comment by robimarko** [comment]
No, 5.15 based MHI and QRTR looks to be working fine even with the ath-next head

**Comment by FlyGoat** [comment]
Hmm, just a quick galance on how desktop platform is handling SDX55, it seems like only `MHI_BUS_PCI_GENERIC` is used to support this modem in kernel. Others are all handled by user space programs (ModemManager).

As `MHI_BUS_PCI_GENERIC` is backported as well, I guess it won't break anything?

**Comment by robimarko** [comment]
Yeah, MHI is just the control bus that exposes means to talk to the modem/load FW etc and then userspace takes over.

**Comment by FlyGoat** [comment]
@hauke Any chance to get backport tree updated?

**Comment by hauke** [comment]
I updated mac80211 in master, it now contains your patches. Please try commit 3aa96efa24c13c6e0aafa5ad826f3f95a3bd74f9.

**Comment by robimarko** [comment]
@hauke Are we going to have conflicts with for example QRTR MHI from the backports with the QRTR SMD from the kernel?
Because, AHB ath11k requires QRTR SMD which requires RPMSG, which requires QCA SMD driver, and so on.

**Comment by hauke** [comment]
Currently QRTR MHI are not build from backports, but if we want to use it from backports we should not pack the version from the kernel in OpenWrt. I do not have the overview which version of the drivers we should use. I plan to use backports from the next LTS kernel (~5.20) for the next OpenWrt release based on kernel 5.15.

**Comment by robimarko** [comment]
I don't know if that's gonna be flexible enough, for PCI support it will probably be fine, but not AHB for SoC-s as there are way more dependencies, and for example shipping, QRTR MHI means that you cant then simply package QRTR SMD outside of backports because of QRTR core.

Shipping all of the dependencies in backports doesn't really seem viable, not to mention patches for those as not everything is upstream, then tracking the point release fixes again the backports version, etc.
Just for an example, a big one is Q6v5 WCSS remoteproc.

**Comment by robimarko** [comment]
BTW, this does not appear to work:
```
Package kmod-ath11k-pci is missing dependencies for the following libraries:
mhi.ko
```

**Comment by Ansuel** [comment]
Mhhh stalled? Should we close and reopen when we have REAL ath11k support?

**Comment by Ansuel** [comment]
@robimarko @FlyGoat any news with this?

**Comment by robimarko** [comment]
ath11k PCI support was already merged in:
https://github.com/openwrt/openwrt/commit/93ae4353cdf651ef0b5d8a4d40a6c29d8d3f655b

**Comment by Ansuel** [comment]
Suppressed by 93ae4353cdf651ef0b5d8a4d40a6c29d8d3f655b

**Comment by Ansuel** [comment]
@robimarko think I should cherry-pick the last commit for the board-2 ?

**Comment by robimarko** [comment]
Which one?

**Comment by robimarko** [comment]
If you are talking about the linux-firmware one, the no.
Everything required for QCA6390 and like consumer cards was added as part of the ath11k PCI series, its all packaged and existing already.

**Pull request closed without merging**
