### PR TITLE
Omap uboot updates

### PR DESCRIPTION
**Pull request by mrnuke-adaptrum**

### CODE REVIEW

**Comment by kaloz** [comment]
The reason why uboot-omap is hidden is simple: pretty much all boards we support in this target either need or at least benefit from having a new bootloader compiled.

**Comment by mrnuke-adaptrum** [comment]
> either need 

Could you elaborate on that please? More specifically, how does hiding the package benefit things?

> benefit from having a new bootloader compiled

That does not seem like a valid reason to keep behavior that's inconsistent with all other supported platforms.

My motivation for writing this patch is twofold. First, it saves a significant amount of time (1 min out of 5) when building openwrt repeatedly (and we do that a lot!). Second, It's very confusing to see no options under the <Bootloaders...> section in menuconfig. I hope that leaving things on by default, but keeping them visible is an acceptable resolution.

**Comment by wigyori** [comment]
I'd be more happy if instead of a commit/revert series, a "clean" commit would be re-submitted in a PR.

**Comment by mrnuke-adaptrum** [comment]
> I'd be more happy if instead of a commit/revert series, a "clean" commit would be re-submitted in a PR.

Thank you for the suggestion. PR updated.

**Comment by mrnuke-adaptrum** [comment]
PING

**Comment by wigyori** [comment]
Ping @kaloz

**Pull request closed without merging**
