### PR TITLE
generic: replace netfilter patch with upstream version

### PR DESCRIPTION
**Pull request by namiltd**
Replace netfilter patch with upstream version.

### CODE REVIEW

**Comment by KanjiMonster** [comment]
The patch is already queued for 6.6 (https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/queue-6.6/netfilter-xtables-fix-typo-causing-some-targets-not-.patch?id=fb48f952d4b59f14aa61b63d9c98249281055132), so not sure if it's worth it if the next 6.6 update will already include it.

**Comment by namiltd** [comment]
@KanjiMonster But it's not there yet in version 6.6.58.

**Comment by KanjiMonster** [comment]
It's in 6.6.59-rc1 https://lore.kernel.org/lkml/20241028080619.589960-1-ojeda@kernel.org/T/#r14cf40e2ca4fdc7c53d3c29228a6ce940b3632e5, which will likely release tomorrow or so.

**Comment by namiltd** [comment]
quote: "Very similar to Ilya Katsnelson's patch including a missing chunk in the TRACE extension"
So I leave it to the administrators to decide whether to approve it or not.

**Comment by namiltd** [comment]
Kernel 6.6.59 has been released, so this PR will be outdated.

**Pull request closed without merging**
