### PR TITLE
generic: enable CONFIG_ARM_CRYPTO for 32bit arm targets

### PR DESCRIPTION
**Pull request by msdos03**
After [following PR](https://github.com/openwrt/openwrt/pull/12349), 
some arm platforms including kirkwood meet error like this
```
ERROR: module '/home/user/openwrt/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood_generic/linux-5.15.109/arch/arm/crypto/sha512-arm.ko' is missing.
```
when building with kmod-crypto-sha512. 
Fix it by adding `CONFIG_ARM_CRYPTO=y` to kirkwood specific kernel config.

### CODE REVIEW

**Comment by robimarko** [comment]
@Ansuel `ipq806x` for example also is hitting this.
It may be better to add a hidden arm-crypto kmod that just turns this symbol on as a dependency

**Comment by msdos03** [comment]
> @Ansuel `ipq806x` for example also is hitting this. It may be better to add a hidden arm-crypto kmod that just turns this symbol on as a dependency

Some arm platforms already have this symbol enabled, and this config have been removed in 6.1 kernel. 
So I think add it to every arm platforms is a better choice.

**Comment by Ansuel** [comment]
@ynezz @msdos03 btw from this https://github.com/Ansuel/openwrt/actions/runs/4925703032/jobs/8800685976

multiple targets require this config

Can't we just backport the commit that dropped the config?

**Comment by robimarko** [comment]
@Ansuel Here is the commit:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.27&id=4a329fecc9aaebb27a53fa7abfa53bbc2ee42f3f

Its completely refactoring the ARM and AMR64 crypto config, so its quite broad, better just enable the symbol for ARM targets for now.

**Comment by Ansuel** [comment]
@robimarko mhhh is not that big i bet it would apply directly but i agree better enable the config for the related target.

Enabling the config should not increase the kernel right? Just make the kmod compile. Am I wrong?

**Comment by robimarko** [comment]
Kernel size shouldnt increase AFAIK since this just means that instead of the generic algo implementation the architecture optimized version will be used.

**Comment by Ansuel** [comment]
Well we have a clear view of the target required for this. I would merge this but I need the other target correctly changed.

**Comment by msdos03** [comment]
@Ansuel got it

**Comment by Ansuel** [comment]
@msdos03 Hi very nice work!!

Just can you by chance split this in 2 commit? One refreshing config and the other adding the arm one?

**Comment by msdos03** [comment]
@Ansuel Done, I put all the changes in one commit.

**Comment by msdos03** [comment]
@Ansuel Done

**Comment by Ansuel** [comment]
@msdos03 Thanks a lot. I will wait for CI to finish and I will merge tomorrow!

**Comment by msdos03** [comment]
@Ansuel Wait a moment, I found that there are more arm32 targets build OK in https://github.com/Ansuel/openwrt/actions/runs/4925703032/jobs/8800685976
But they didn't contain CONFIG_ARM_CRYPTO=y either.
These targets need fix too, I thought I should update the PR again

**Pull request merged**
