### PR TITLE
[23.05] firmware-utils: bump to git HEAD (2023-11-03)

### PR DESCRIPTION
**Pull request by maurerle**
Bump firmware-utils to support D-Link COVR-X1860 in v23.05
    
    a170683c0e11 firmware-utils: fix use of NULL string progname
    89875fc18b57 tplink-safeloader: CPE510: add Canadian support
    9e211d2980fe mktplinkfw2: add support to extract bootloader images
    c18f662f3c74 mktplinkfw2: add support to pack bootloader
    3dc133915f87 mktplinkfw2: show exact exceed bytes when the image is to big
    d16ff798d58a tplink-safeloader: WPA8631: add v4 AU, US
    0fa1cc51013f zytrx: add LTE5398-M904
    635466123429 firmware-utils: ptgen: add SiFive GPT partition support
    ba5bc4e1ae9d add dlink-sge-image for D-Link devices by SGE

The removed patch was applied upstream.

### CODE REVIEW

**Comment by blocktrron** [comment]
This introduces a lot of changes unrelated with your intention. I would prefer to cherry-pick them to a release-specific branch.

**Comment by maurerle** [comment]
Sure, I just thought thats the way we did it around here too:
https://github.com/openwrt/openwrt/commit/2cece6e2b078e6acb97f3ed99ffc58f0f8fa2365

**Comment by maurerle** [comment]
I reduced the amount of changes and used cherry-picks from existing commits on main to go there.

Though I think you meant to create a release-branch on the firmware-utils repository..?
If it is needed sure, but I would prefer it this way.

**Comment by Borromini** [comment]
@blocktrron Was there ever the intention to have a release branch for firmware-utils? Because as it stands there's just a single repo that moves at the pace of the OpenWrt main repository.

E.g. the recent EAP615-Wall commit would be handy in 23.05 too. @maurerle Would you mind adding that too?

https://github.com/openwrt/firmware-utils/commit/d87b6c4b6423201e595459840f51d0dced04a4eb

**Comment by maurerle** [comment]
@blocktrron created a release branch on the firmware-utils repo which can be used without adding unrelated commits.
if @Borromini wants to backport other changes too, you can backport these onto that branch independently:
https://github.com/openwrt/firmware-utils/tree/openwrt-23.05

This PR is therefore not needed anymore.

**Pull request closed without merging**
