### PR TITLE
ath79: add support for TP-Link CPE510 V3.20

### PR DESCRIPTION
**Pull request by Parabol1337**
TP-Link CPE510-v3.20 is an outdoor wireless CPE for 5 GHz with
one Ethernet port based on Atheros AR9344

Specifications:

    Based on the same underlying hardware as the TP-Link CPE510
    Power, LAN, and 4 green LEDs
    1 10/100Mbps Shielded Ethernet Port (Passive PoE in)
    Built-in 13dBi 2x2 dual-polarized directional MIMO antenna
    Adjustable transmission power from 0 to 23dBm/200mw

Flashing instructions:
Flash factory image through stock firmware WEB UI
or through TFTP
To get to TFTP recovery just hold reset button while powering on for
around 4-5 seconds and release.
Rename factory image to recovery.bin
Stock TFTP server IP:192.168.0.100
Stock device TFTP adress:192.168.0.254

Signed-off-by: Ulf Cramme <<ulf@cramme.org>>

### CODE REVIEW

**Comment by adschm** [comment]
This has formal issues. Please check https://openwrt.org/submitting-patches

**Comment by Parabol1337** [comment]
Please help me, I have no idea what to do differently.
I'm brand new here. I've always made my changes for myself in the past
Thank you very much

**Comment by adschm** [comment]
From submitting-patches:

* commit subject
  * must have a prefix that depends from what you are doing in the commit
    * kernel: for kernel and kmod (kernel module) packages
    * package name: for packages
    * device architecture: for devices (for example, mvebu: or ramips: add support to example_eval board )
    * tool name: for tools
    * build: for general buildsystem changes that are not targeted at something in /toolchain
  * must be less than 50 characters long
  * must describe what the commit changes and why the commit is necessary. (It is challenging to be both succinct and descriptive, but that is what a well-written summary should do)
  * don't capitalize first word after the prefix
  * don't write a full stop at the end of the subject line
* commit description
  * must have less than 75 characters per line
  * it will be committed to the source changelog, so it should explain to a competent reader why you made this commit.
    Include symptoms of the failure you are fixing (log messages, error messages, etc.), it will be useful for
    people searching the commit logs looking for a fix for their issue.
    If a patch fixes a compile failure, include only the most relevant part of the failure log
  * If you add support for new hardware: Include in your commit message a short description of the hardware and how to install OpenWrt on it. Have a look at the recent additions for some examples.
* all commits must contain Signed-off-by: My Name <my@email.address> where you write your real name and real email address, in accordance with Section 11 of the Linux Kernel patches guide
  * GitHub web interface or GUI application for git: you must append the the Signed-off-by: line manually in the commit description

**Comment by adschm** [comment]
Ping.

**Comment by adschm** [comment]
Merged proper patch in #3685 instead.

**Pull request closed without merging**
