### PR TITLE
kernel-5.4: combine all wireguard patches into one updater script patch

### PR DESCRIPTION
**Pull request by zx2c4**
This is either an amazing idea or the worst idea ever. Rather than
shipping a huge series of these, we can combine all the patches into one
minimal patch, with a single diff per file, merged from all prior
changes. We can then stick the result below a bash script that updates
itself. The net result is a single patch file that can be run to update
itself to the newest series.

CC @lipnitsk @blocktrron

### CODE REVIEW

**Comment by zx2c4** [comment]
Pros:
- One file instead of many.
- Updates from the backport tree are made trivial.
- Cool hack.

Cons:
- By combining the upstream-matched patches into a single file, it becomes harder to see which patch doesn't agree, if something goes wrong.
- Insane.

**Comment by lipnitsk** [comment]
@adschm thoughts on merging this in? This way could make it more maintainable for 21.02 as well.

**Comment by adschm** [comment]
> @adschm thoughts on merging this in? This way could make it more maintainable for 21.02 as well.

No, because I think it will make it _less_ maintainable. zx2c4 has made a good job in showing both sides of the subject, and why this is essentially a matter of taste.

**Comment by lipnitsk** [comment]
> this is essentially a matter of taste.

That, but one (maybe minor) advantage of a single patch is faster quilt refresh. Although that's really a quilt issue and we are hacking around it by reducing the number of patches.

**Comment by adschm** [comment]
> > this is essentially a matter of taste.
> 
> That, but one (maybe minor) advantage of a single patch is faster quilt refresh. Although that's really a quilt issue and we are hacking around it by reducing the number of patches.

Well, I don't see a benefit when my car drives faster into the wrong direction.

**Comment by zx2c4** [comment]
> > > this is essentially a matter of taste.
> > 
> > That, but one (maybe minor) advantage of a single patch is faster quilt refresh. Although that's really a quilt issue and we are hacking around it by reducing the number of patches.
> 
> Well, I don't see a benefit when my car drives faster into the wrong direction.

Haha, funny analogy. I don't have any issue abandoning this. We can continue doing things normally rather than the, "Jason's weird ideas" approach. :)

**Comment by adschm** [comment]
Note that my point on taste implied that other people might see this differently, and I merely expressed that _I_ won't merge it. So please don't close it because of my verdict (although, of course, changes are not really high that somebody will pick it up now suddenly after 21 days ...).

**Comment by zx2c4** [comment]
Oh, okay! Will reopen in case somebody else feels differently.

**Comment by CodeFetch** [comment]
I agree with adschm... This increases frustration in case something goes wrong. As nobody felt different, yet it will likely not change.

**Comment by adschm** [comment]
Since there has been no interest or positive feedback by maintainers for almost three months, I'm finally closing this now.
But thanks for being interested in keeping things organized, even if it didn't work out this way.

**Pull request closed without merging**
