### PR TITLE
build: normalize imagebuilder/sdk naming

### PR DESCRIPTION
**Pull request by aparcar**
We use a specific file prefix dependent on target and release except for
imagebuilder and sdk. While everything goes `openwrt-<release>-<target>`
the two go `openwrt-<sdk/imagebuilder>-<release>-<target>`.

This commit normalizes the naming:

    openwrt-x86-64-generic-squashfs-combined.img
    openwrt-x86-64-generic-squashfs-rootfs.img.gz
    openwrt-x86-64-imagebuilder.Linux-x86_64.tar.xz
    openwrt-x86-64-sdk_gcc-11.2.0_musl.Linux-x86_64.tar.xz

Previously the naming would be as following:

    openwrt-x86-64-generic-squashfs-combined.img
    openwrt-x86-64-generic-squashfs-rootfs.img.gz
    openwrt-imagebuilder-x86-64.Linux-x86_64.tar.xz
    openwrt-sdk-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
This may break some downstream, however a regex to catch files isn't really complicated. 

```perl
    qr/[Oo]pen[Ww]rt-.*?[Ii]mage[Bb]uilder/,
    qr/[Oo]pen[Ww]rt-.*?[Ss][Dd][Kk]/,
```

**Comment by aparcar** [comment]
@jow- do you have an opinion on that?

**Comment by adschm** [comment]
I don't understand this change. Won't it remove information?

Maybe it would help if you gave examples for "before" AND "after" in your commit message ...

**Comment by aparcar** [comment]
Updated.

**Comment by jow-** [comment]
I don't like it. Take https://downloads.openwrt.org/snapshots/targets/ath79/generic/ as example. The imagebuilder would end up somewhere between hak5 and iodata devices while the SDK would land between samsung and siemens devices in an ordinary sorted file listing.

It would look like just another firmware image file. A NAK from me due to that.

**Comment by aparcar** [comment]
by adopting the [metafiles](https://github.com/jow-/LEDE_Download_Index_Page/blob/master/dir-index.cgi#L245) regex this should still end up at the bottom. It would allow to cut of the *prefix* (openwrt-21.02.0-apm821xx-sata-) like done for images and make the whole entry more readable, allowing additionally somewhat more equally sized tables.
image

**Comment by adschm** [comment]
Ah, thanks, now I understand the change. I don't have a particular preference here.

**Comment by aparcar** [comment]
A better approach is likely to add SDK and image builder to the JSON files. Closing this.

**Pull request closed without merging**
