### PR TITLE
Add watchdog max6370 support via GPIO

### PR DESCRIPTION
**Pull request by BKPepe**
This backports the third version [1], which is awaiting upstream merge. It
adds support for watchdog max6370, which is connected via GPIO. It
is useful primarily for P2020 RDB and Turris 1.x routers, which are
not yet supported.

[1] https://www.spinics.net/lists/linux-watchdog/msg23299.html

cc: @CHKDSK88

### CODE REVIEW

**Comment by musashino205** [comment]
Please use target name for suffix in the commit title of the second commit, ```mpc85xx:```. ```mpc85xx: p2020:``` can also be used.

**Comment by BKPepe** [comment]
Added, thanks!

**Comment by hauke** [comment]
Why do you add `CONFIG_MAX63XX_WATCHDOG` into the kernel configuration and do not add it as a loadable kernel module?

**Comment by BKPepe** [comment]
That's a good question, and thanks for pointing it out. I checked it how it is done for other platforms like

- https://github.com/openwrt/openwrt/blob/8010d3da0376f68dd3724c30db0c4c9c513e5376/target/linux/at91/sam9x/config-default#L26
- https://github.com/openwrt/openwrt/blob/8010d3da0376f68dd3724c30db0c4c9c513e5376/target/linux/mvebu/cortexa53/config-5.15#L22
- https://github.com/openwrt/openwrt/blob/8010d3da0376f68dd3724c30db0c4c9c513e5376/target/linux/omap/config-5.15#L630

So, I tried to keep the consistency across targets, but I can do it as a loadable kernel module if requested.

**Comment by BKPepe** [comment]
Anything else to address this pull request and have it merged?

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in 620bc37c2a6ab54bbb094be57bff1eeb2acb0933 and f8cd27891fbd0d7cd992b6ed4da958bd37f8c6ea.

**Pull request closed without merging**
