### PR TITLE
scripts: use std library for jam crc32 calculation

### PR DESCRIPTION
**Pull request by dek3rr**
CRC32 is available in a standard library. It seems reasonable
to defer to that rather than run a custom implementation.

Signed-off-by: Doug Kerr <dek3rr@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
seems sane. is this dependent on a version of python?

**Comment by dekerr** [comment]
it's python 3. As I understand, python 3.6 is the minimum version for openwrt now
https://docs.python.org/3.9/library/binascii.html#binascii.crc32

**Comment by hauke** [comment]
Please split this into two commits, one changing the formatting and one doing the code change. It is very hard for me to review your changes.

**Comment by dekerr** [comment]
Sorry, I'm doing my best to learn how the ecosystem works here. Thanks for your patience : )

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 0642a2166b9526ec01fe47b6aed1fd57a29e35f9 and 6f692c9c497e5e60eb51da741b07ef1c10096355.

**Pull request closed without merging**
