### PR TITLE
Openwrt 19.07 cudy WR1300 support

### PR DESCRIPTION
**Pull request by fermat2a**
Adding support for AC1200 Dual Band Wi-Fi Router WR1300 into Openwrt 19.07 (http://www.cudytech.com/productinfo/90088.html).

Integration into master is in progress.

### CODE REVIEW

**Comment by musashino205** [comment]
"*Thus, device support typically is not backported.*"
https://openwrt.org/docs/guide-developer/device-support-policies#device_support_backports

**Comment by fermat2a** [comment]
_"While feature backports still should be an exception, they typically are done for changes that are easy and well isolated. In contrast, requiring new drivers or patches to kernel subsystems etc. will drive your chances close to zero."_
https://openwrt.org/docs/guide-developer/device-support-policies#device_support_backports

I hoped that this is the case here...

**Comment by adschm** [comment]
This has several formal issues, and adding a full DTS file is not simple/trivial in the original idea of that text. Apart from that, 19.07 has become quite old now, so your chances are virtually zero, particularly since you cannot present a strong argument to support your case. I won't merge it, and I don't think anybody else will.

**Comment by fermat2a** [comment]
o.k., understood.

Anyway I will go on with my work for the master Branch. Is there any idea about when the version 20 is planned? Is it enough to bring my changes into master to make it into the nexht version? Or is there already some stabi Branch against which I should also test?

Do you see anything I did wrong with this PR, that I should do better for the PR on master?

27.12.2020 13:55:55 Adrian Schmutzler <notifications@github.com>:

**Comment by rotanid** [comment]
@fermat2a i'm not sure if it's written down, but having support in the master branch is crucial, otherwise it won't ever be acceptable for stable branches. so you (or the guys working on the patches) did it in the wrong order.
The release branch for the 20 release will happen very soon, so it's not even guaranteed anymore you get this device into the next release or at least getting it there will also be a backport from master branch to 20.x release branch then.
maybe sad news, but reality is better than false hopes.

**Comment by fermat2a** [comment]
Good to know. Is there already a way to test my changes against the ongoing work for release 20? I did not see a branch on github up to now.

27.12.2020 23:38:46 Andreas Ziegler <notifications@github.com>:

**Comment by rotanid** [comment]
no, as long as there is no branch, the work happens in master branch

**Pull request closed without merging**
