### PR TITLE
octeon: switch to Kernel 5.15 by default

### PR DESCRIPTION
**Pull request by aparcar**
This PR to have an overview of testing.

### CODE REVIEW

**Comment by Borromini** [comment]
Light testing here on an EdgeRouter Lite a few weeks ago showed no issues.

**Comment by Borromini** [comment]
Can't swap this in to be my main router, sorry. @flygarn12 Do you still have you EdgeRouter 4? Could you help out?

@damex You ported the ER-4 AFAIK, could you help out?

**Comment by flygarn12** [comment]
I can maybe try installing it this weekend. But I have only one and it is the operational router so I can't test it on any other setup than the setup specific to the rest of the network.

**Comment by aparcar** [comment]
To git.openwrt.org:openwrt/openwrt.git
   596059266a..c8934099bf  master -> master

Merged to get further testing.

**Pull request closed without merging**
