### PR TITLE
wolfssl: fix Config.in typo

### PR DESCRIPTION
**Pull request by Spudz76**
Found a typo in an item description, simple repair, no effect other than cosmetic.

### CODE REVIEW

**Comment by Ansuel** [comment]
@Spudz76 hi you need to fix some formal problems for this to be merged. Feel free to ask help about it

**Comment by Spudz76** [comment]
Repaired the commit message, and since I was force-pushing anyway, also rebased on current `master`

**Comment by Ansuel** [comment]
Hi, i would use something like wolfssl: fix Config.in typo.
Also you need to set a commit description.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in 3d205eb216c21fc94a0e088b0b67ed61b0c992df.

**Pull request closed without merging**
