### PR TITLE
kernel: bump 5.10 to 5.10.134

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by aparcar** [comment]
Please rebase to see if the new kernel CI is happy

**Comment by aparcar** [comment]
Excellent, thank you!

@Ansuel looks like we should include those tools in the containers

**Comment by Ansuel** [comment]
> Excellent, thank you!
> 
> @Ansuel looks like we should include those tools in the containers

Mh what tools?

**Comment by aparcar** [comment]
> > Excellent, thank you!
> > 
> > @Ansuel looks like we should include those tools in the containers
> 
> Mh what tools?

make tools/compile

**Comment by Ansuel** [comment]
@aparcar mhhh so your idea is to cache the tools dir and make it part of the container?

**Comment by aparcar** [comment]
If the CI passes it seems save to merge or do you have an idea for basic runtime tests?

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 7d3c0928de191b203dd5b27ddf208698d08639e3, 913f160ac6c4dcf69ec0eb805c8a1cee809ace45, 56760c0b1316a0e379ff141b895c2929f0dace8d and 7be62b1187bb7e21bcdaadfc3d47713a91f05898.

**Pull request closed without merging**
