### PR TITLE
kernel: qca-ssdk: update to 12.5 for kernel 6.6

### PR DESCRIPTION
**Pull request by qosmio**
Qualcomm recently committed a new branch (12.5.r2) targeting kernel 6.6. This lets us clean up a few patches particularly the one for "C22/C45" mdio.

A quick way to see what changed for IPQ807x/6018 was to list the files produced during build `(**/*.o)`, replace the extension with "`.c`", and doing a `git log`.

Filtering from those commits, ones of particular interest are listed below:

```
2024-04-16 - 0d8f30aa - fix compile issue on hk with linux style build
2024-01-29 - 636464f7 - update the check for port link notify
2024-01-24 - 30c10e7f - enable and disable loopback for xgmac to fix qm stuck issue
2024-01-15 - b6ea10aa - update the the APIs to access switch
2024-01-08 - a1687502 - Disable Tx bridge mac before power off the PHY
2024-01-07 - 3eafb613 - support led configure for malibu phy
2024-01-07 - 5c1af60d - remove phy type check from mac reset when mode switch
2023-12-17 - 79d0b1e8 - remove the PHY access APIs in ssdk_plat.c
2023-12-16 - b2953740 - Update mii read/write functions
2023-12-11 - 37f2eac3 - add port id check for fdb entry
2023-12-11 - d040ca4d - support mdio clause45 on kernel6.6
2023-12-07 - 11494fbc - use barrier mw() during access fdb entry table
2023-12-03 - 8e40a284 - fix build warnings on kernel6.6
2023-11-10 - 10aa0a02 - change speed value when call ssdk_port_link_notify
2023-11-06 - ee4c4a60 - Update mac bitmap value of L3 table on MAC delete
2023-11-03 - 7cd27d39 - support 10G phy common feature
2023-10-30 - 383cc0d2 - fix mactype and mux select issue
2023-10-24 - decf534a - support autoneg status query on force port
2023-10-11 - 111d574e - move ssdk_led_init to regi_init
2023-10-08 - 6b14c142 - the combo port also need to parse SFP pins
2023-10-03 - fb2e0401 - fix port5 interface mode switch issue in erp case
```

A lot of the build warnings have been fixed upstream too.

Included a patch to also address remaining build warnings for `fal_eg_trans_filter_bypass_en_get` and `fal_eg_trans_filter_bypass_en_set`.

Verified with users on QNAP 301W, NBG7815, and myself on Dynalink DL-WRX36 that everything is functional, including LEDS.

### CODE REVIEW

**Comment by skramstad** [comment]
Thanks @qosmio . Should we also create a new PR for nss-dp 12.5.r2 branch?
https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-dp/-/tree/NHSS.QSDK.12.5.r2?ref_type=heads

**Comment by robimarko** [comment]
Thanks for doing this, I started but then ran out of time.

**Comment by skramstad** [comment]
Maybe it's a good time to update qca-nss-dp too, so new PR for qca-nss-dp https://github.com/openwrt/openwrt/pull/15383

**Comment by jmv2009** [comment]
Runs OK on fritz-repeater (ipq40xx+qca8035 single ethernet)
Queues are (since recently I think) not equally filled, generating unequal interrupt loads on cores (each redirected to a different core)
```
 33:    4961021          0          0          0 GIC-0  97 Edge      c080000.ethernet:txq0
 37:       1370      20547          0          0 GIC-0 101 Edge      c080000.ethernet:txq4
 41:       1309          0      12785          0 GIC-0 105 Edge      c080000.ethernet:txq8
 45:       1123          0          0     843040 GIC-0 109 Edge      c080000.ethernet:txq12
 49:    8932428          0          0          0 GIC-0 272 Edge      c080000.ethernet:rxq0
 51:       5608     765405          0          0 GIC-0 274 Edge      c080000.ethernet:rxq2
 53:       6100          0     723258          0 GIC-0 276 Edge      c080000.ethernet:rxq4
 55:       5270          0          0    1283617 GIC-0 278 Edge      c080000.ethernet:rxq6
```

**Comment by robimarko** [comment]
> Runs OK on fritz-repeater (ipq4019+qca8035 single ethernet) Queues are (since recently I think) not equally filled, generating unequal interrupt loads on cores (each redirected to a different core)
> 
> ```
>  33:    4961021          0          0          0 GIC-0  97 Edge      c080000.ethernet:txq0
>  37:       1370      20547          0          0 GIC-0 101 Edge      c080000.ethernet:txq4
>  41:       1309          0      12785          0 GIC-0 105 Edge      c080000.ethernet:txq8
>  45:       1123          0          0     843040 GIC-0 109 Edge      c080000.ethernet:txq12
>  49:    8932428          0          0          0 GIC-0 272 Edge      c080000.ethernet:rxq0
>  51:       5608     765405          0          0 GIC-0 274 Edge      c080000.ethernet:rxq2
>  53:       6100          0     723258          0 GIC-0 276 Edge      c080000.ethernet:rxq4
>  55:       5270          0          0    1283617 GIC-0 278 Edge      c080000.ethernet:rxq6
> ```

SSDK is not used on IPQ4019 at all

**Comment by sppmasterspp** [comment]
Run tested on QNAP along with https://github.com/openwrt/openwrt/pull/15383
Screenshot 2024-05-07 011742

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
