### PR TITLE
bcm4908: switch to Kernel 5.15 by default

### PR DESCRIPTION
**Pull request by aparcar**
This PR to have an overview of testing.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
A rebase on latest master would be good. New patches arrived for the target.

**Comment by aparcar** [comment]
@PolynomialDivision can you test this?

**Comment by aparcar** [comment]
@Rafostar can you please have a look?

**Comment by rmilecki** [comment]
I did some testing on GT-AC5300. There is some bug affecting `sysupgrade`. At first I believed it's related to the kernel 5.15 as I didn't notice that with 5.10. Now I noticed `sysupgrade` actually works but **partially** only. It upgrades kernel but does not userspace (rootfs). I've to perform more debugging when I'm back after this long weekend.

**Comment by rmilecki** [comment]
`sysupgrade` issue wan't related to the kernel bump at all. I was confused by kernel being updated while userspace not. Sorry for that.

This is OK.

`sysupgrade` fix is pending (`[PATCH] base-files: fix nand_upgrade_ubinized()`).

**Pull request closed without merging**
