### PR TITLE
mac80211: ath12k: allow country set for WCN7850

### PR DESCRIPTION
**Pull request by januszdziedzic**
Update channels when country set.

### CODE REVIEW

**Comment by robimarko** [comment]
Dont you need the remaining 3 patches as well?
Especially `wifi: ath12k: avoid firmware crash when reg set for WCN7850`

**Comment by januszdziedzic** [comment]
so far didn't hit any crash and after country set can setup AP:
```
root@bpi-r64-42acb69cd7af:~# iw phy2 reg get
phy#2
country GB: DFS-ETSI
        (2402 - 2482 @ 40), (N/A, 20), (N/A)
        (5170 - 5250 @ 80), (N/A, 23), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (N/A, 23), (0 ms), NO-OUTDOOR, DFS, AUTO-BW
        (5490 - 5590 @ 80), (N/A, 30), (0 ms), DFS, AUTO-BW
        (5590 - 5650 @ 40), (N/A, 30), (600000 ms), DFS, AUTO-BW
        (5650 - 5730 @ 80), (N/A, 30), (0 ms), DFS, AUTO-BW
        (5735 - 5875 @ 80), (N/A, 14), (N/A), AUTO-BW
        (5855 - 5875 @ 20), (N/A, 14), (N/A), AUTO-BW
        (5945 - 6425 @ 320), (N/A, 24), (N/A), NO-OUTDOOR, AUTO-BW

root@bpi-r64-42acb69cd7af:~# iw wlan2 info
Interface wlan2
        ifindex 10
        wdev 0x200000001
        addr 00:03:7f:58:28:37
        ssid OpenWrt
        type AP
        wiphy 2
        channel 1 (5955 MHz), width: 320 MHz, center1: 6105 MHz
        txpower 24.00 dBm
        multicast TXQ:
                qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                0       0       0       0       0       0       0       0               0
root@bpi-r64-42acb69cd7af:~#
```

This one is series 1/4 - 4/4 - in one patch.
```
From: Kang Yang <[kangyang@qti-qualcomm.corp-partner.google.com](mailto:kangyang@qti-qualcomm.corp-partner.google.com)>

This patch-set is mainly does four things:
1. Add handler to send WMI_SET_CURRENT_COUNTRY_CMDID to firmware.
2. Implement 11d scan offload, and report country code to firmware by
WMI command WMI_SET_CURRENT_COUNTRY_CMDID.
3. Use WMI_SET_CURRENT_COUNTRY_CMDID to set country code for WCN7850.
4. Store country code, and update it to firmware after device recovery.

With this patch-set, WCN7850 can do 11d offload scan and update country
code to firmware successfully.

Note: This patch-set is an old patch-set in public review written by
Wen Gong. Just continue sending it for him.
Link: https://patchwork.kernel.org/project/linux-wireless/cover/20230914090746.23560-1-quic_wgong@quicinc.com/

v3:
    1. use wiphy::mtx lock instead of adding a new lock(patch#2).
    2. rename struct according to wmi naming convention(patch#1, #2).
    3. update copyright in reg.h
    4. modifiy patch#3, #4 due to struct name change.
v2: change per Jeff.
    1. change alpha2 length from 3 to 2.
    2. change wmi_11d_new_cc_ev to wmi_11d_new_cc_event.

Wen Gong (4):
  wifi: ath12k: add configure country code for WCN7850
  wifi: ath12k: add 11d scan offload support
  wifi: ath12k: use correct WMI command to set country code for WCN7850
  wifi: ath12k: store and send country code to firmware after recovery
```

Cold be I miss smth - but AP works much better when country set and channels unlocked :)

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by fs30000** [comment]
Will these patches be merged to mainline? I cannot set country for the QCNCM865 and hostapd fails to start. I'm using 6.13.

**Comment by robimarko** [comment]
> Will these patches be merged to mainline? I cannot set country for the QCNCM865 and hostapd fails to start. I'm using 6.13.

I dont see how is this question for OpenWrt, v10 of this was sent couple of days ago:
https://patchwork.kernel.org/project/linux-wireless/patch/20250212063200.1631-2-quic_kangyang@quicinc.com/

**Comment by fs30000** [comment]
> > Will these patches be merged to mainline? I cannot set country for the QCNCM865 and hostapd fails to start. I'm using 6.13.
> 
> I dont see how is this question for OpenWrt, v10 of this was sent couple of days ago: https://patchwork.kernel.org/project/linux-wireless/patch/20250212063200.1631-2-quic_kangyang@quicinc.com/

I tried the card with mainline 6.13 and 6.14-rc from Frank's repo. It crashed, the patch here fixed it. Still, country code not possible to set even on 6.14-rc. So i came here asking you guys for help.

Compiling with the second patch (001-wifi-ath12k-add-11d-scan-offload-support-and-handle-country-code-for-WCN7850.patch)  applied fails with this:

```
Build Kernel
building with 4 threads
Cleanup Kernel Build
needed: make u-boot-tools bc gcc libc6-dev libncurses-dev ccache libssl-dev
generate branch vars...
getting git branch:
* 6.13-main
kernbranch:6.13-main,gitbranch:-main
make[1]: Entering directory '/root/build'
  GEN     Makefile
  CALL    /root/BPI-Router-Linux/scripts/checksyscalls.sh
  CC [M]  drivers/net/wireless/ath/ath12k/mac.o
  CC      init/main.o
  CC      io_uring/io_uring.o
  CC      init/do_mounts.o
  CC      io_uring/notif.o
  CC      init/init_task.o
  CC      io_uring/net.o
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c: In function 'ath12k_bss_assoc':
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:3007:18: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_type'
 3007 |             arvif->vdev_type == WMI_VDEV_TYPE_STA &&
      |                  ^~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:3008:18: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_subtype'
 3008 |             arvif->vdev_subtype == WMI_VDEV_SUBTYPE_NONE)
      |                  ^~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c: In function 'ath12k_mac_op_hw_scan':
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:4069:18: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_type'
 4069 |             arvif->vdev_type == WMI_VDEV_TYPE_STA &&
      |                  ^~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:4070:18: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_subtype'
 4070 |             arvif->vdev_subtype == WMI_VDEV_SUBTYPE_NONE)
      |                  ^~
In file included from /root/BPI-Router-Linux/include/linux/init.h:5,
                 from /root/BPI-Router-Linux/include/linux/printk.h:6,
                 from /root/BPI-Router-Linux/include/asm-generic/bug.h:22,
                 from /root/BPI-Router-Linux/arch/arm64/include/asm/bug.h:26,
                 from /root/BPI-Router-Linux/include/linux/bug.h:5,
                 from /root/BPI-Router-Linux/include/net/mac80211.h:16,
                 from /root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:7:
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c: In function 'ath12k_mac_vif_ap_active_any':
/root/BPI-Router-Linux/include/linux/container_of.h:20:54: error: 'struct ath12k_vif' has no member named 'list'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                                                      ^~
/root/BPI-Router-Linux/include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:9: note: in expansion of macro 'static_assert'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:23: note: in expansion of macro '__same_type'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:601:9: note: in expansion of macro 'container_of'
  601 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:612:9: note: in expansion of macro 'list_entry'
  612 |         list_entry((ptr)->next, type, member)
      |         ^~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:770:20: note: in expansion of macro 'list_first_entry'
  770 |         for (pos = list_first_entry(head, typeof(*pos), member);        \
      |                    ^~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/compiler_types.h:483:27: error: expression in static assertion is not an integer
  483 | #define __same_type(a, b) __builtin_types_compatible_p(typeof(a), typeof(b))
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:9: note: in expansion of macro 'static_assert'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:23: note: in expansion of macro '__same_type'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:601:9: note: in expansion of macro 'container_of'
  601 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:612:9: note: in expansion of macro 'list_entry'
  612 |         list_entry((ptr)->next, type, member)
      |         ^~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:770:20: note: in expansion of macro 'list_first_entry'
  770 |         for (pos = list_first_entry(head, typeof(*pos), member);        \
      |                    ^~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
In file included from /root/BPI-Router-Linux/include/uapi/linux/posix_types.h:5,
                 from /root/BPI-Router-Linux/include/uapi/linux/types.h:14,
                 from /root/BPI-Router-Linux/include/linux/types.h:6,
                 from /root/BPI-Router-Linux/include/linux/kasan-checks.h:5,
                 from /root/BPI-Router-Linux/include/asm-generic/rwonce.h:26,
                 from /root/BPI-Router-Linux/arch/arm64/include/asm/rwonce.h:71,
                 from /root/BPI-Router-Linux/include/linux/compiler.h:339,
                 from /root/BPI-Router-Linux/include/asm-generic/bug.h:5:
/root/BPI-Router-Linux/include/linux/stddef.h:16:33: error: 'struct ath12k_vif' has no member named 'list'
   16 | #define offsetof(TYPE, MEMBER)  __builtin_offsetof(TYPE, MEMBER)
      |                                 ^~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/container_of.h:23:28: note: in expansion of macro 'offsetof'
   23 |         ((type *)(__mptr - offsetof(type, member))); })
      |                            ^~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:601:9: note: in expansion of macro 'container_of'
  601 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:612:9: note: in expansion of macro 'list_entry'
  612 |         list_entry((ptr)->next, type, member)
      |         ^~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:770:20: note: in expansion of macro 'list_first_entry'
  770 |         for (pos = list_first_entry(head, typeof(*pos), member);        \
      |                    ^~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
In file included from /root/BPI-Router-Linux/include/linux/smp.h:12,
                 from /root/BPI-Router-Linux/include/linux/alloc_tag.h:14,
                 from /root/BPI-Router-Linux/include/linux/percpu.h:5,
                 from /root/BPI-Router-Linux/arch/arm64/include/asm/arch_timer.h:18,
                 from /root/BPI-Router-Linux/arch/arm64/include/asm/timex.h:8,
                 from /root/BPI-Router-Linux/include/linux/timex.h:67,
                 from /root/BPI-Router-Linux/include/linux/time32.h:13,
                 from /root/BPI-Router-Linux/include/linux/time.h:60,
                 from /root/BPI-Router-Linux/include/linux/skbuff.h:15,
                 from /root/BPI-Router-Linux/include/linux/if_ether.h:19,
                 from /root/BPI-Router-Linux/include/net/mac80211.h:18:
/root/BPI-Router-Linux/include/linux/list.h:761:26: error: 'struct ath12k_vif' has no member named 'list'
  761 |         list_is_head(&pos->member, (head))
      |                          ^~
/root/BPI-Router-Linux/include/linux/list.h:771:15: note: in expansion of macro 'list_entry_is_head'
  771 |              !list_entry_is_head(pos, head, member);                    \
      |               ^~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
In file included from /root/BPI-Router-Linux/include/linux/kernel.h:22,
                 from /root/BPI-Router-Linux/include/net/mac80211.h:17:
/root/BPI-Router-Linux/include/linux/list.h:645:25: error: 'struct ath12k_vif' has no member named 'list'
  645 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |                         ^~
/root/BPI-Router-Linux/include/linux/container_of.h:19:33: note: in definition of macro 'container_of'
   19 |         void *__mptr = (void *)(ptr);                                   \
      |                                 ^~~
/root/BPI-Router-Linux/include/linux/list.h:645:9: note: in expansion of macro 'list_entry'
  645 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:772:20: note: in expansion of macro 'list_next_entry'
  772 |              pos = list_next_entry(pos, member))
      |                    ^~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:645:25: error: 'struct ath12k_vif' has no member named 'list'
  645 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |                         ^~
/root/BPI-Router-Linux/include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:9: note: in expansion of macro 'static_assert'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:23: note: in expansion of macro '__same_type'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:601:9: note: in expansion of macro 'container_of'
  601 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:645:9: note: in expansion of macro 'list_entry'
  645 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:772:20: note: in expansion of macro 'list_next_entry'
  772 |              pos = list_next_entry(pos, member))
      |                    ^~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:54: error: 'struct ath12k_vif' has no member named 'list'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                                                      ^~
/root/BPI-Router-Linux/include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:9: note: in expansion of macro 'static_assert'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:23: note: in expansion of macro '__same_type'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:601:9: note: in expansion of macro 'container_of'
  601 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:645:9: note: in expansion of macro 'list_entry'
  645 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:772:20: note: in expansion of macro 'list_next_entry'
  772 |              pos = list_next_entry(pos, member))
      |                    ^~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:645:25: error: 'struct ath12k_vif' has no member named 'list'
  645 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |                         ^~
/root/BPI-Router-Linux/include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:9: note: in expansion of macro 'static_assert'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/container_of.h:21:23: note: in expansion of macro '__same_type'
   21 |                       __same_type(*(ptr), void),                        \
      |                       ^~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:601:9: note: in expansion of macro 'container_of'
  601 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:645:9: note: in expansion of macro 'list_entry'
  645 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:772:20: note: in expansion of macro 'list_next_entry'
  772 |              pos = list_next_entry(pos, member))
      |                    ^~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/compiler_types.h:483:27: error: expression in static assertion is not an integer
  483 | #define __same_type(a, b) __builtin_types_compatible_p(typeof(a), typeof(b))
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/build_bug.h:78:56: note: in definition of macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:9: note: in expansion of macro 'static_assert'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/container_of.h:20:23: note: in expansion of macro '__same_type'
   20 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:601:9: note: in expansion of macro 'container_of'
  601 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:645:9: note: in expansion of macro 'list_entry'
  645 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:772:20: note: in expansion of macro 'list_next_entry'
  772 |              pos = list_next_entry(pos, member))
      |                    ^~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/stddef.h:16:33: error: 'struct ath12k_vif' has no member named 'list'
   16 | #define offsetof(TYPE, MEMBER)  __builtin_offsetof(TYPE, MEMBER)
      |                                 ^~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/container_of.h:23:28: note: in expansion of macro 'offsetof'
   23 |         ((type *)(__mptr - offsetof(type, member))); })
      |                            ^~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:601:9: note: in expansion of macro 'container_of'
  601 |         container_of(ptr, type, member)
      |         ^~~~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:645:9: note: in expansion of macro 'list_entry'
  645 |         list_entry((pos)->member.next, typeof(*(pos)), member)
      |         ^~~~~~~~~~
/root/BPI-Router-Linux/include/linux/list.h:772:20: note: in expansion of macro 'list_next_entry'
  772 |              pos = list_next_entry(pos, member))
      |                    ^~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6836:17: note: in expansion of macro 'list_for_each_entry'
 6836 |                 list_for_each_entry(arvif, &ar->arvifs, list) {
      |                 ^~~~~~~~~~~~~~~~~~~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:6837:34: error: 'struct ath12k_vif' has no member named 'is_u                                                           p'
 6837 |                         if (arvif->is_up && arvif->vdev_type == WMI_VDEV_TYPE_AP)
      |                                  ^~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c: In function 'ath12k_mac_vdev_create':
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:7129:26: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_type'
 7129 |                     arvif->vdev_type == WMI_VDEV_TYPE_STA &&
      |                          ^~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:7130:26: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_subtype'
 7130 |                     arvif->vdev_subtype == WMI_VDEV_SUBTYPE_NONE) {
      |                          ^~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c: In function 'ath12k_mac_vdev_delete':
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:7475:18: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_type'
 7475 |             arvif->vdev_type == WMI_VDEV_TYPE_STA &&
      |                  ^~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:7476:18: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_subtype'
 7476 |             arvif->vdev_subtype == WMI_VDEV_SUBTYPE_NONE)
      |                  ^~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c: In function 'ath12k_mac_op_unassign_vif_chanctx':
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:8320:18: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_type'
 8320 |             arvif->vdev_type == WMI_VDEV_TYPE_STA &&
      |                  ^~
/root/BPI-Router-Linux/drivers/net/wireless/ath/ath12k/mac.c:8321:18: error: 'struct ath12k_link_vif' has no member named                                                            'vdev_subtype'
 8321 |             arvif->vdev_subtype == WMI_VDEV_SUBTYPE_NONE &&
      |                  ^~
make[8]: *** [/root/BPI-Router-Linux/scripts/Makefile.build:194: drivers/net/wireless/ath/ath12k/mac.o] Error 1
make[7]: *** [/root/BPI-Router-Linux/scripts/Makefile.build:440: drivers/net/wireless/ath/ath12k] Error 2
make[6]: *** [/root/BPI-Router-Linux/scripts/Makefile.build:440: drivers/net/wireless/ath] Error 2
make[5]: *** [/root/BPI-Router-Linux/scripts/Makefile.build:440: drivers/net/wireless] Error 2
make[4]: *** [/root/BPI-Router-Linux/scripts/Makefile.build:440: drivers/net] Error 2
make[3]: *** [/root/BPI-Router-Linux/scripts/Makefile.build:440: drivers] Error 2
make[3]: *** Waiting for unfinished jobs....
  CC      io_uring/poll.o
  CC      io_uring/uring_cmd.o
  AR      init/built-in.a
  CC      io_uring/sqpoll.o
  CC      io_uring/register.o
  CC      io_uring/napi.o
  AR      io_uring/built-in.a
make[2]: *** [/root/BPI-Router-Linux/Makefile:1989: .] Error 2
make[1]: Leaving directory '/root/build'
make[1]: *** [/root/BPI-Router-Linux/Makefile:251: __sub-make] Error 2
make: *** [Makefile:251: __sub-make] Error 2
```

**Pull request merged**
