### PR TITLE
ramips: mt7621: disable build 64 MiB RAM devices

### PR DESCRIPTION
**Pull request by DragonBluep**

### CODE REVIEW

**Comment by dangowrt** [comment]
I got several devices with 64 MiB of RAM and they all boot fine, even with Linux 6.6.
In order to run asterisk (!) on some of them I use `zram-swap`. But LuCI and working as a simple AP works also without that.
Instead of disabling them, we should consider adding `zram-swap` to the selection of default packages and let users previously reporting Oom test that.

**Comment by DragonBluep** [comment]
> I got several devices with 64 MiB of RAM and they all boot fine, even with Linux 6.6. In order to run asterisk (!) on some of them I use `zram-swap`. But LuCI and working as a simple AP works also without that. Instead of disabling them, we should consider adding `zram-swap` to the selection of default packages and let users previously reporting Oom test that.

It seems that the MT7621 multi-core CPU takes up more RAM. In the current main branch, I can get about 60 MiB of available RAM on 128 MiB RAM MT7620/AR9344 devices. But for the 128 MiB RAM MT7621 device, I only get about 20 MiB of available space left.

**Comment by MalikuMane** [comment]
> I got several devices with 64 MiB of RAM and they all boot fine, even with Linux 6.6. In order to run asterisk (!) on some of them I use `zram-swap`. But LuCI and working as a simple AP works also without that. Instead of disabling them, we should consider adding `zram-swap` to the selection of default packages and let users previously reporting Oom test that.



> I got several devices with 64 MiB of RAM and they all boot fine, even with Linux 6.6. In order to run asterisk (!) on some of them I use `zram-swap`. But LuCI and working as a simple AP works also without that. Instead of disabling them, we should consider adding `zram-swap` to the selection of default packages and let users previously reporting Oom test that.

Just adding zram-swap wasn't enough, i had to remove several packages and disable some of the init scripts to make it usable.

**Comment by MalikuMane** [comment]
> @MalikuMane You can enable `low_mem` and `small_flash` features to free up more memory. They willl trim some debug informations.
> 
> ```
> --- a/target/linux/ramips/mt7621/target.mk
> +++ b/target/linux/ramips/mt7621/target.mk
> @@ -4,7 +4,7 @@
>  
>  SUBTARGET:=mt7621
>  BOARDNAME:=MT7621 based boards
> -FEATURES+=nand ramdisk rtc usb minor
> +FEATURES+=nand ramdisk rtc usb minor low_mem small_flash
>  CPU_TYPE:=24kc
>  KERNELNAME:=vmlinux vmlinuz
>  # make Kernel/CopyImage use $LINUX_DIR/vmlinuz
> ```
> 

So far i tried building an image with just these changes and it did boot up without OOM. Ill play around with the kernel config later but this is a good start.

              total        used        free      shared  buff/cache   available
Mem:          57736       40672       12468          84        4596        2420

**Comment by Linaro1985** [comment]
> nbd patch with rx.dma_size = 512 for mt7621

MT7986 works unstable with this patches backported to OpenWrt-23.05. fq dma fix also included.

**Comment by MalikuMane** [comment]
> nbd patch with rx.dma_size = 512 for mt7621
> 
> https://lore.kernel.org/all/20241015110940.63702-3-nbd@nbd.name/

Forgot to report, yes it works 
```
              total        used        free      shared  buff/cache   available
Mem:          55572       36820       10696          56        8056        2368
```

**Comment by Neustradamus** [comment]
@nbd168, @brada4: What do you think?

**Comment by brada4** [comment]
I completely agree with dangowrt's first comment - i.e add zram-swap to 64MB devices.
For example devices without wifi can do away with 64MB for more time ahead.

**Comment by MalikuMane** [comment]
> @MalikuMane Which version are you testing? Master branch SNAPSHOT or openwrt v23? Is zram helpful for your device? I guess the sysupgrade function is no longer work on your device due to limited free ram.

v23, i tested the patch without the zram. Which configuration should i test?

**Comment by brada4** [comment]
just add zram-swap package.

**Comment by MalikuMane** [comment]
> just add zram-swap package.

```
              total        used        free      shared  buff/cache   available
Mem:          55572       35448       15520           8        4604        5532
Swap:         27644        1792       25852
```
Got some swap now

**Comment by blogic** [comment]
looks like this is resolved hence closing. if this is still a problem please re-open.

**Comment by MalikuMane** [comment]
AFAIK the fix is still under review upstream so it's not actually fixed in a currently available release or snapshot.

**Comment by DragonBluep** [comment]
The test of @MalikuMane is based on kernel 5.15 and there is only 5 MiB free RAM available, so I don't think 64 MiB MT7621 can boot the kernel 6.6.

**Pull request closed without merging**
