### PR TITLE
uboot-mediatek: fixes the defconfig typo

### PR DESCRIPTION
**Pull request by aiamadeus**
CONFIG_CMD_MTDPART does not exist, fix it.

### CODE REVIEW

**Comment by Ansuel** [comment]
@aiamadeus can you split this to 2 commit one for each changed patch and add the relevant Fixes tag to them?

A quick git blame 
https://github.com/openwrt/openwrt/commit/e9ad412049c3d4d2e5bbd6993e4cc9922a8a27a9
https://github.com/openwrt/openwrt/commit/ed5000431940c0c8ae2b5704faa0ceb68a299102

Feel free to ask for help

**Comment by aiamadeus** [comment]
> can you split this to 2 commit one for each changed patch and add the relevant Fixes tag to them?

Thanks, I have changed it.

**Comment by Ansuel** [comment]
@aiamadeus if you can't i will fix it for you but fixes tag needs to stay in the same line, no wrapping :D 
Just tell me what do you prefer (me fixing or you fix)

**Comment by aiamadeus** [comment]
> but fixes tag needs to stay in the same line, no wrapping

Fixed it.

**Pull request merged**
