### PR TITLE
libnetfilter-queue: fix package title, description

### PR DESCRIPTION
**Pull request by cpatulea**

### CODE REVIEW

**Comment by hauke** [comment]
Hi, your PR has formal issues, please have a look at https://openwrt.org/submitting-patches

**Comment by cpatulea** [comment]
I've updated the commit message, could you please take another look?

**Comment by adrianschmutzler** [comment]
You have not updated the commit message, as there is no commit message. The commit message is meant to explain what you change and why.

**Comment by cpatulea** [comment]
> You have not updated the commit message, as there is no commit message. The commit message is meant to explain what you change and why.

I am not really sure what more you would like. The commit diff is 4 lines, some minor updates to pcakage title and description. The commit message is (and yes, I *did* update it after the original PR, after I was asked to read the contributing guidelines and did so):

>   libnetfilter-queue: fix package title, description
>
>  Signed-off-by: Catalin Patulea <catalinp@google.com>

This seems to me sufficient to explain the change. Can you give me an example of what more you are expecting in the commit message?

Are you a project member or just commenting here?

**Comment by adrianschmutzler** [comment]
> This seems to me sufficient to explain the change. Can you give me an example of what more you are expecting in the commit message?

Well, you say that you fix title/description. That implies that there is something "wrong" with current description. So, you could provide some details what this would be, e.g. (unrelated to your changes):
"This fixes wrong grammar in the package title."
"The original text was copy/pasted from some other package. This puts the correct description there."
"The text is updated to resembled the changes of this package after commit xxx."
"The text implies the package has functionality X, but actually it does Y."
...

The reason to implement such a description is to inform anyone looking at the patch about what he has to expect from it. Otherwise, you would have to deduce the intention from the changes, making it harder to find errors. Despite, it's a service to the reviewer/readers.

It might seem like pestering for a simple commit like this, still it improves quality of the repository and due to the same reasons it shouldn't be too hard for you to create a description. :-)

**Comment by mkresin** [comment]
> Are you a project member or just commenting here?

Does it make any difference?

**Comment by cpatulea** [comment]
Okay, how about this?

**Comment by cpatulea** [comment]
@hauke would you mind taking another look?

**Comment by adrianschmutzler** [comment]
Thanks, pulled this (with slight adjustments) to my staging tree.

**Pull request closed without merging**
