### PR TITLE
generic: mtd: spinand: winbond: more serial NAND flash types

### PR DESCRIPTION
**Pull request by namiltd**
Add support for W25N01JW, W25N02JWZEIF, W25N512GW, W25N02KWZEIR and W25N01GWZEIG.
Add support for W25N04KV.

### CODE REVIEW

**Comment by hauke** [comment]
Have you seen these chips on some boards?

**Comment by namiltd** [comment]
No, but on https://github.com/openwrt/openwrt/issues/16259 there is a request to add W25N04KV
I think it is worth adding them for new constructions.

**Comment by namiltd** [comment]
@hauke Is there a chance to approve this PR or is it better to close it and wait until routers that need these chips are found? Then this fix will be necessary.

**Comment by hauke** [comment]
Thanks, I applied the patches. We will probably see such devices soon.

**Pull request merged**
