### PR TITLE
ipq806x: ecw5410: multiple fixes

### PR DESCRIPTION
**Pull request by robimarko**
This PR introduces multiple fixes to the ECW5410 support.

GPIO bit-banging an MDIO interface is dropped as there is no reason for that since the SoC has an MDIO controller and there is a driver for it.

PCI1 QCA9984 radio was unable to load the BDF as it couldn't detect the BMI ID due to no pre-cal data being provided to the driver.

And lastly, overriding the MAC-s via userspace helper is dropped as there is no reason to do so.
All that was needed is to correct the ethernet aliases to the proper order so that MAC-s matched the stock FW.

Signed-off-by: Robert Marko <robert.marko@sartura.hr>

### CODE REVIEW

**Comment by robimarko** [comment]
@adschm This should resolve your question about MAC-s and some other things I found while looking into MAC-s.
I would like to point out that the original commit for ECW5410 was signed by me as I did that work, but it was done for TIP based on the now ancient 4.14 kernel and OpenWrt 18.06 they were using at that time and I had to hack it a lot to make it work.
They didn't want upstreaming it into OpenWrt at that time and somehow later it got pushed into OpenWrt without actually being ready for that.

**Comment by adschm** [comment]
> I would like to point out that the original commit for ECW5410 was signed by me as I did that work, but it was done for TIP based on the now ancient 4.14 kernel and OpenWrt 18.06 they were using at that time and I had to hack it a lot to make it work. They didn't want upstreaming it into OpenWrt at that time and somehow later it got pushed into OpenWrt without actually being ready for that.

Unfortunately, it happens from time to time that some committers just pick unfinished or broken stuff. We have to make the best out of it...

**Comment by robimarko** [comment]
I understand that, but that just wastes more time for reviewing new code, I am just look at the IPQ related backlog

**Comment by adschm** [comment]
Thanks, I will merge it this weekend.

About the other issue, there is not much I can change about it.

**Comment by robimarko** [comment]
Thanks, I am well aware of a general lack of reviewers in most projects.

**Pull request closed without merging**
