### PR TITLE
iperf: move iperf3 and iperf to package feed

### PR DESCRIPTION
**Pull request by feckert**
@aparcar @pprindeville As discussed.
This is my P/R to move iperf to pachage feed

### CODE REVIEW

**Comment by pprindeville** [comment]
Where's the other half?

**Comment by aparcar** [comment]
I sent those patches to the ML a while ago...

**Comment by pprindeville** [comment]
> I sent those patches to the ML a while ago...

Is there a PR on GitHub?

**Comment by aparcar** [comment]
http://patchwork.ozlabs.org/project/openwrt/patch/20210115200337.1500054-1-mail@aparcar.org/ but I'm fine using @feckert patches. @nbd168 aggreed via IRC.

**Comment by aparcar** [comment]
Merged, thank you.

**Pull request closed without merging**
