### PR TITLE
ramips: add support for ELECOM WRC-1900GST

### PR DESCRIPTION
**Pull request by drvlabo**
ELECOM WRC-1900GST is a wireless router, based on Mediatek MT7621A.
This is almost same as WRC-2533GST except wireless specs.

Specifications:

  - SoC : MT7621A (four logical CPU cores)
  - RAM : 128MiB
  - ROM : 16MiB of SPI NOR-FLASH
  - wireless :
          5GHz : 3T3R up to 1300Mbps/11ac with MT7615
          2.4GHz : 3T3R up to 600Mbps/11n with MT7615
  - Ethernet : 5 ports, all ports is capable of 1000base-T
  - Ether switch : MT7530 (MT7621A built-in)
  - LEDs : 4 LEDs
  - buttons : 2 buttons and 1 slide-switch
  - UART : header is on PCB, 57600bps

Flash instruction using factory image:
    
 1. Connect the computer to the LAN port of WRC-1900GST
 2. Connect power cable to WRC-1900GST and turn on it
 3. Access to "https://192.168.2.1/" and open firmware update
    page ("ファームウェア更新")
 4. Select the OpenWrt factory image and click apply ("適用")
    button
 5. Wait ~150 seconds to complete flashing
    
Signed-off-by: NOGUCHI Hiroshi <drvlabo@gmail.com>

### CODE REVIEW

**Comment by mkresin** [comment]
@drvlabo your Signed-off-by is missing and there is no installation instruction in the commit message. Both is mentioned in https://openwrt.org/submitting-patches.

@musashino205 may I ask you to do the review. You are way more familiar with these boards.

**Comment by musashino205** [comment]
@mkresin OK.

**Comment by drvlabo** [comment]
@mkresin Thanks for pointing-outs about my missings.
Now fixed them.

**Comment by mkresin** [comment]
@drvlabo you have updated the github description but not the commit message. The github PR description is more like an envelope und will not make it into the repository.

So, please update the commit description. try ```git commit --amend``` to do so.

**Comment by drvlabo** [comment]
@mkresin Sorry again. I modified comment on my repository's commit with 'git commit --amend'

**Comment by musashino205** [comment]
LGTM.

**Comment by mkresin** [comment]
@drvlabo please fix your git/github settings. The [author of your commit](https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/1300.patch) is set to "drvlabo <drvlabo@gmail.com>" but has to match the name + e-mail address used in the Signed-off-by. This time I fixed it for you.

**Comment by mkresin** [comment]
Merged, thanks.

**Pull request closed without merging**
