### PR TITLE
build: fix ldconfig executable error in python

### PR DESCRIPTION
**Pull request by dmascord**
The empty executable is causing problems with meson builds, due to the
error: OSError: [Errno 8] Exec format error: 'ldconfig'

This patch changes the empty ldconfig stub to symlink to /bin/true to
work around this issue.

Signed-off-by: Damien Mascord <tusker@tusker.org>

---

Credits go to dhewg on IRC for the idea.

The following txt file shows the full build error

[ldconfig-full-error.txt](https://github.com/openwrt/openwrt/files/7452029/ldconfig-full-error.txt)

### CODE REVIEW

**Comment by bittorf** [comment]
This fixes the error for me on Debian 11.1

**Comment by abajk** [comment]
`Tested-by: Aleksander Jan Bajkowski <olek2@wp.pl> # Tested on Debian 11`

**Review by abajk — APPROVED** [review]

**Comment by abajk** [comment]
You can also add this tag in the commit description: 
`Fixes: FS#4117`

**Review by ahao99 — COMMENTED** [review]
that helps!

**Comment by lucize** [comment]
Fix on Debian 10
Tested-By: Lucian Cristian <lucian.cristian@gmail.com>

**Comment by zorun** [comment]
Merged, thanks.

**Comment by aparcar** [comment]
Nice, this was the missing bit to get meson running for 21.02!

**Pull request closed without merging**
