### PR TITLE
toolchain: Use GCC 8.3.0 by default and remove 7.1 for ARC

### PR DESCRIPTION
**Pull request by diizzyy**
Discussed here: https://github.com/openwrt/openwrt/pull/1803
ARC support is finally upstream so drop branched versions
@abrodkin @EvgeniiDidin

### CODE REVIEW

**Comment by diizzyy** [comment]
@abrodkin @EvgeniiDidin 
Ping

**Comment by EvgeniiDidin** [comment]
Hi Daniel,
Could you please add these changes to one of the patches:
```
diff --git a/toolchain/gcc/Config.version b/toolchain/gcc/Config.version
index 6534ef593e..74d96a7a66 100644
--- a/toolchain/gcc/Config.version
+++ b/toolchain/gcc/Config.version
@@ -4,6 +4,7 @@ config GCC_VERSION_5
 
 config GCC_VERSION_8
        default y if GCC_USE_VERSION_8
+       default y if arc
        bool
 
 config GCC_USE_EMBEDDED_PATH_REMAP
```
This will set GCC_VERSION  to 8.3.0, otherwise the version is 7.4.0 and build fails.

**Comment by diizzyy** [comment]
@EvgeniiDidin 
Existing config? Starting fresh defaults to 8

**Comment by EvgeniiDidin** [comment]
GCC_USE_VERSION_8 option is enabled for ARC only if DEVEL and TOOLCHAINOPTS options are enabled. But by default these options are disabled. With my changes simply running "make menuconfig" and choosing ARC target system will set GCC_VERSION to 8.3.0.

**Comment by diizzyy** [comment]
@EvgeniiDidin 
Ahh, now I see. Added :-)

**Comment by EvgeniiDidin** [comment]
Using GCC 8.3.0 image builds and runs well. I think we can apply these patches.

**Comment by diizzyy** [comment]
@hauke @chunkeey

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.
Is it possible to switch also gdb to the upstream version?

**Comment by EvgeniiDidin** [comment]
Unfortunately not all ARC changes are upstreamed (especially GDB for Linux, bare-metal support is all in upstream) and so upstream release won't even configure. Still the plan is to upstream missing pieces of ARC GDB port through the course of this year.
That said for now we need to keep ARC fork as it is.

**Pull request closed without merging**
