### PR TITLE
CC: ar71xx: Added missing support for Linksys E2100L

### PR DESCRIPTION
**Pull request by gadkrumholz**
It's based on the WRT160NL according to https://wiki.openwrt.org/toh/linksys/e2100l

Based on research done here: https://forum.openwrt.org/viewtopic.php?id=24244 and here: https://forum.openwrt.org/viewtopic.php?pid=120791#p120791 this patch was conceived.

### CODE REVIEW

**Comment by wigyori** [comment]
Hi,

Looks good at first - would you mind to do a patch against trunk? Please add a "CC: ar71xx: " prefix to the CC commit, and an "ar71xx: " prefix to the trunk commit, thanks.

**Comment by gadkrumholz** [comment]
I changed the PR message and added the specified prefix. Did I do it correctly?

Also, am I correct in assuming you mean "master" and not "trunk"? I didn't do a patch for master/trunk yet... but I can if you'd like me to.

**Comment by wigyori** [comment]
Not the PR message, the commit message should be amended, please. :)  (Same goes for #250).

Yes, it's master (called trunk in the SVN days). Have to change the mindset for myself as well yet. Thanks.

**Comment by wigyori** [comment]
Oh, and Signed-off-by please to all commits.

**Comment by gadkrumholz** [comment]
Ok, I updated the commit messages for both PR's to include their prefixes and the Signed-off-by. Does this look better now? Thanks!

**Comment by wigyori** [comment]
Both patches look good, thanks!

**Pull request merged**
