### PR TITLE
WIP tools/ninja: add ninja build system to tools

### PR DESCRIPTION
**Pull request by ja-pa**
This PR adds support for Ninja build system https://ninja-build.org. 

Ninja is a dependency for Meson builds system https://mesonbuild.com. See [list of some projects](https://mesonbuild.com/Users.html )  which use Meson. 
In near future, I would like to add Meson to packages feed (since it depends on python3).

It's also possible to use Ninja alone or with another generator (see [List of possible generators](https://github.com/ninja-build/ninja/wiki/List-of-generators-producing-ninja-build-files)

### CODE REVIEW

**Comment by lucize** [comment]
cool, gtk already needs meson, how would be this available, like cmake.mk ?

**Comment by diizzyy** [comment]
The SDK should be self-contained meaning that we need to pull in Python as it's both a build and run-time requirement for Ninja. Once that's done we should make it an option for CMake (can generate  build.ninja files) to prefer Ninja over (GNU)make so it can be tested "in the wild". This should also help making compilation more reliable when doing parallel builds which would be a nice "side-effect". Once confirmed reliable Ninja should be made the default option and then we can import Meson. I might be wrong but that seems like the most logical path to go.

**Comment by ja-pa** [comment]
@diizzyy Thanks, that approach sounds reasonable.

**Comment by ja-pa** [comment]
After discussion in packages repo, I think that the best solution will be to integrate ninja to packages/devel. So I'm closing this PR. Thanks

**Pull request closed without merging**
