### PR TITLE
hostapd: mark accepted patches

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Upstreamed patches:
- 170-DPP-fix-memleak-of-intro.peer_key.patch
- 461-driver_nl80211-use-new-parameters-during-ibss-join.patch
- 800-acs-don-t-select-indoor-channel-on-outdoor-operation.patch
- 992-openssl-include-rsa.patch

### CODE REVIEW

**Comment by Ansuel** [comment]
If we follow patch index numbering.... in theory 000 should be backport patches might be better than ACCEPTED or can't we add the next release version like we do with the linux kernel?

**Comment by hauke** [comment]
Only very few packages follow this patches numbering. If you want to mark the upstream patches I would prefer if you move them to 0 and move the patches currently starting with 0 to some other number.

**Comment by Ansuel** [comment]
(ideally the patch rename in a different commit)

@hauke (sorry for ot did you by chance notice my private email?

**Comment by PolynomialDivision** [comment]
Thanks for your comments. :)

However, I think I will close this in favor of:
https://github.com/openwrt/openwrt/pull/12178

**Pull request closed without merging**
