### PR TITLE
toolchain: gdb: update to 12.1

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gdb/NEWS;hb=gdb-12.1-release

Refreshed patch:
- 120-fix-compile-flag-mismatch.patch

### CODE REVIEW

**Comment by neheb** [comment]
I'd maybe port the patches from: https://git.alpinelinux.org/aports/tree/main/gdb or https://git.openembedded.org/openembedded-core/tree/meta/recipes-devtools/gdb/gdb

**Comment by PolynomialDivision** [comment]
@neheb But not for the toolchain?

**Comment by neheb** [comment]
Ah yeah good point.

**Comment by hauke** [comment]
I would prefer to not add extra patches which are not needed.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in 728740fe7818ebd3264fcd98b78a0e12239e73aa.

**Pull request closed without merging**
