### PR TITLE
bcm53xx: bump compat version for DSA migration

### PR DESCRIPTION
**Pull request by mans0n**
During the DSA conversion in commit e9672b1a8fa4 ("bcm53xx: switch to
the upstream DSA-based b53 driver"), it also added a simple migration
script for the default network config. But it cannot handle complex
config and thus it is not complete enough to be used for stable releases.
This commit drops the migration script and instead bumps the compat
version to 1.1 for all bcm53xx devices like we did in 1eac573b5304
("ramips: mt7621: implement compatibility version for DSA migration").

Since DSA support on bcm53xx is out for a while already, this applies
the same uci-defaults workaround for early adopters as we did for mt7621
in the past.

---

Ref:
https://github.com/openwrt/openwrt/issues/9248#issuecomment-1080813017
https://github.com/openwrt/openwrt/commit/e9672b1a8fa4714cbc35d5964caf704b2e571f35#commitcomment-58577826

We should also backport this to 22.03 branch before a release, but without the uci-defaults workaround.

### CODE REVIEW

**Comment by mans0n** [comment]
Cc: @rmilecki

**Comment by mans0n** [comment]
I did a build test successfully but did not tested the actual run-time sysupgrade. (No testable device at the moment)

**Comment by aparcar** [comment]
Do you think it's possible to implement an upgrade path in case the default configuration was used? For default home routers it would be nice to upgrade them without resetting them

**Comment by mans0n** [comment]
> Do you think it's possible to implement an upgrade path in case the default configuration was used? For default home routers it would be nice to upgrade them without resetting them

I think it's hard to figure out whether the config is in the default state or not. If we touch it incautiously, it might blow out some micro-configured stuff.

For the early DSA adopters, I might add a comment that they can simply force sysupgrade keeping existing config as we did in e81e625ca375.

**Comment by mans0n** [comment]
Added a sysupgrade comment for early DSA-adopters.
For 22.03 branch, only the first patch should be backported.

**Comment by mans0n** [comment]
@rmilecki Could you please consider testing this? I'd love to do it myself but it will take some times to bring up my dead devices...

**Comment by mans0n** [comment]
Finally tried this on RT-AC88U and now I've realized that bcm53xx target does not inspect the image metadata (no `REQUIRE_IMAGE_METADATA=1`) thus the whole compat_version scheme does not work with this target at all. Oops. Sorry for the fuss.
Maybe we can convert the target [platform.sh](https://github.com/openwrt/openwrt/blob/c0a6fefd9b74af03a30810be20f0ce5504447b3e/target/linux/bcm53xx/base-files/lib/upgrade/platform.sh) to the "standard" way at this time, but I guess there must be a reason why we did not switch to it earlier, and I'm not that familiar with this target (I do not understand most of the target platform.sh), so I resign.

I still do not feel [03_dsa_migrate](https://github.com/openwrt/openwrt/blob/c0a6fefd9b74af03a30810be20f0ce5504447b3e/target/linux/bcm53xx/base-files/etc/uci-defaults/03_dsa_migrate) is sufficient for stable release, I hope there would be a way to warn users for the DSA migration, during sysupgrade or via release announcement.

**Pull request closed without merging**
