### PR TITLE
rockchip: fix some ipv4 connectivity issues on NanoPi R2S

### PR DESCRIPTION
**Pull request by mj22226**
When the NanoPi R2S boot with the lan cable disconected will not get ipv4 address after boot, e.j. when is used as a travelrouter.
Fixed by moving rtl8152 driver to within the kernel.

### CODE REVIEW

**Comment by lucize** [comment]
sure is not some usb3 driver or dts problem ?
on my rock64 board I don't have this problem
a network restart doesn't solve the problem ?

**Comment by mj22226** [comment]
> sure is not some usb3 driver or dts problem ?
> on my rock64 board I don't have this problem
> a network restart doesn't solve the problem ?

On the rock64 board is different, you maybe are using the rtl8152 as a WAN ( eth1), on the nanopi r2s is used as LAN (eth1) if I set the rtl8152 as a WAN on the nanopi r2s works without issues.

**Comment by lucize** [comment]
I'll try also that scenario

**Comment by 1715173329** [comment]
However, the change just belongs to R2S, but not the whole target.
Personally, I don't consider it's a good idea to add the device related
configuration to the target.

> if I set the rtl8152 as a WAN on the nanopi r2s works without issues

Unfortunately, someone reports them has same issue with ports swapped.
(See coolsnowwolf/lede#5248)

Another possible reason is there's a latency between two Ethernet ports
when device booting as rtl8152 is transferred from USB, which we must wait
for usb_core start up first.
That delay the native Ethernet port start up may be a solution, but it just a guess.

**Comment by blocktrron** [comment]
@mj22226 Can you be more concise on your issue here? From my understanding is you issue on the WAN side, which is not related to the Realtek USB NIC. So this "fix" feels more like a way to workaround the unknown underlying bug.

**Comment by mj22226** [comment]
@blocktrron The issue is on the LAN side (rtl8152) , it is not a workaround, having the driver loaded as a module seems to be the problem, when the driver is loaded within kernel works perfectly.

**Comment by 1715173329** [comment]
@mj22226 
> having the driver loaded as a module seems to be the problem

Yup, when loaded as a module, it must wait for another module named "usb_core" starts up first.
And this produces a latency, which causes the problem.
When it was built-in with kernel, it will be loaded directly, so the problem will disappear.

But I still say, delaying the native Ethernet port starts up may be a better idea, as others boards 
in this target doesn't need this module.

**Comment by rodman80** [comment]
Tested the patch on my nanopi r2s and can confirm it does indeed fix the issue.

**Comment by blocktrron** [comment]
I've tried to reproduce an IPv4 issue on my board today and all i got was dnsmasq failing to restart when netifd brought up the eth1 interface.

So if this is the problem you are seeing here, the dnsmasq package should be fixed to handle these cases.

**Comment by mj22226** [comment]
> I've tried to reproduce an IPv4 issue on my board today and all i got was dnsmasq failing to restart when netifd brought up the eth1 interface.

Did you try with my fix applied?

**Comment by blocktrron** [comment]
Yes, dnsmasq does not have to reload in this case, as both interfaces are present prior to the start of netifd.

However, this is just a workaround for the underlying issue outlined above and should be fixed in dnsmasq / netifd.

**Comment by blocktrron** [comment]
@mj22226 @rodman80 

Please try the following patch. It should fix the incorrect assumption in dnsmasqs initscript.

```
From 8739da9e892778c138f283bb322de46c80e46371 Mon Sep 17 00:00:00 2001
From: David Bauer <mail@david-bauer.net>
Date: Tue, 18 Aug 2020 15:09:22 +0200
Subject: [PATCH] dnsmasq: abort dhcp_check on interface state

Abort the link-check based on the interface instead of the carrier
state. In cases where the interface is up but the carrier is down,
netifd won't case a dnsmasq reload, thus dhcp won't be active on thsi
interface.

Signed-off-by: David Bauer <mail@david-bauer.net>
---
 package/network/services/dnsmasq/files/dnsmasq.init | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/package/network/services/dnsmasq/files/dnsmasq.init b/package/network/services/dnsmasq/files/dnsmasq.init
index 932103d8b5..2d72bc6a28 100644
--- a/package/network/services/dnsmasq/files/dnsmasq.init
+++ b/package/network/services/dnsmasq/files/dnsmasq.init
@@ -106,9 +106,9 @@ dhcp_check() {
 
 	[ -s "$stamp" ] && return $(cat "$stamp")
 
-	# If there's no carrier yet, skip this interface.
+	# If interface is down, skip it.
 	# The init script will be called again once the link is up
-	case "$(devstatus "$ifname" | jsonfilter -e @.carrier)" in
+	case "$(devstatus "$ifname" | jsonfilter -e @.up)" in
 		false) return 1;;
 	esac
 
-- 
2.28.0

```

**Comment by mj22226** [comment]
> Please try the following patch. It should fix the incorrect assumption in dnsmasqs initscript.

@blocktrron  I tried the patch and it is working nicely now, since this is been fixed  I will close it.Thanks for taken the time to look on this.

**Comment by rodman80** [comment]
Confirmed it works, @blocktrron . Nice job!
I think it should be commited by someone before closing, nop?

**Pull request closed without merging**
