### PR TITLE
build: fix typo in cmake patch

### PR DESCRIPTION
**Pull request by pstef**

### CODE REVIEW

**Comment by neheb** [comment]
So this patch has always been broken?

**Comment by adrianschmutzler** [comment]
Actually, that's quite interesting. The case would always be entered, so the patch was essentially without any effect, as it would have produced

```
  cmake_make_flags="${cmake_make_flags} -j ${cmake_parallel_make}"
```

effectively in any case. We should ask ourselves whether we need it at all, if it went good four years without it.

**Comment by adrianschmutzler** [comment]
So, if I understand this correctly, we would just have added a plain number as argument to cmake_make_flags so far.
And parallel build was never working for cmake ...?

**Comment by pstef** [comment]
> But [0-9]* here doesn't match an empty string, and we were actually removing the -j
`-j` is not set in the line below the case statement, but it is added inside the case statement.

> And parallel build was never working for cmake ...?
cmake's `configure` step can be parallelized with `--parallel=4`

**Comment by adrianschmutzler** [comment]
I wonder whether we can just remove the patch entirely.

**Comment by pstef** [comment]
In my opinion, if `$cmake_parallel_make` is guaranteed to be either empty or a number, the patch can be abandoned.

**Comment by adrianschmutzler** [comment]
@pstef I will investigate this a little more, but that's also my belief. And emptiness would be checked in original bootstrap beforehand anyway.

**Comment by adrianschmutzler** [comment]
I just used the following patch:
```
--- a/bootstrap
+++ b/bootstrap
@@ -1284,6 +1284,7 @@ int main(){ printf("1%c", (char)0x0a); r
 cmake_original_make_flags="${cmake_make_flags}"
 if [ "x${cmake_parallel_make}" != "x" ]; then
   cmake_make_flags="${cmake_make_flags} -j ${cmake_parallel_make}"
+  echo "§${cmake_parallel_make}§${cmake_make_flags}§\n" >> /data/maketest.txt
 fi
 for a in ${cmake_make_processors}; do
   if [ -z "${cmake_make_processor}" ] && cmake_try_make "${a}" "${cmake_make_flags}" >> ../cmake_bootstrap.log 2>&1; then
```

It gave me, in the file:
`§--jobserver-auth=3,4§ -j --jobserver-auth=3,4§`

So, it doesn't appear to be as easy as we thought after all.

**Comment by pstef** [comment]
With the patch file entirely deleted, top-level `make -j4` ends up running paralell cmake `bash ./configure --paralell`, that is, it appears to be runinng the configure script many times simultaneusly, each of which in turn tries to bootstrap in parallel.

With the patch file as it is now (before my change), top-level `make -j4` doesn't blow up like in the above and it is also able to bootstrap cmake in paralell. However, `./configure --parallel=4` from `openwrt/build_dir/host/cmake-3.17.4` doesn't result in parallel bootstrap.

With the patch file as in this PR, none of the above problems appear.

**Comment by adrianschmutzler** [comment]
I will merge the proposed version.

**Pull request closed without merging**
