### PR TITLE
realtek: Enable R4K FPU

### PR DESCRIPTION
**Pull request by oliv3r**
Our hardware supports the R4K FPU, so lets enable it. Without this option, we are getting 'illegal instruction' errors. Enabling this allows us to compile software with hardware-float enabled (-mhard-float) and yields the following results from tst-ieee754 [0]:

```
root@OpenWrt:/# ./tst-ieee754
$Id: tst-ieee754.c 144615 2022-01-06 15:10:31Z vinc17/zira $

FLT_RADIX = 2
FLT_MANT_DIG = 24
DBL_MANT_DIG = 53
LDBL_MANT_DIG = 53

FLT_MIN_EXP = -125
DBL_MIN_EXP = -1021
LDBL_MIN_EXP = -1021

FLT_MAX_EXP = 128
DBL_MAX_EXP = 1024
LDBL_MAX_EXP = 1024

FLT_EPSILON = 1.19209e-07 = 0x1p-23
DBL_EPSILON = 2.22045e-16 = 0x1p-52
LDBL_EPSILON = 2.22045e-16 = 0x1p-52

FLT_MIN = 1.17549e-38 = 0x1p-126
DBL_MIN = 2.22507e-308 = 0x1p-1022
LDBL_MIN = 2.22507e-308 = 0x1p-1022

FLT_MAX = 3.40282e+38 = 0x1.fffffep+127
DBL_MAX = 1.79769e+308 = 0x1.fffffffffffffp+1023
LDBL_MAX = 1.79769e+308 = 0x1.fffffffffffffp+1023

sizeof(float) = 4
sizeof(double) = 8
sizeof(long double) = 8

__STDC_IEC_559__ defined:
The implementation shall conform to the IEEE-754 standard.
FLT_EVAL_METHOD is 0 (see ISO/IEC 9899, 5.2.4.2.2#8).

x + y, with x = 9007199254740994.0 and y = 1.0 - 1/65536.0 (type double).
The IEEE-754 result is 9007199254740994 with double precision.
The IEEE-754 result is 9007199254740996 with extended precision.
The obtained result is 9007199254740994.

NAN != NAN --> 1 (should be 1)
isnan(NAN) --> 1 (should be 1)
NAN >= 0.0 --> 0 (should be 0)
NAN <= 0.0 --> 0 (should be 0)
  #3||#4   --> 0 (should be 0)
!(#3||#4)  --> 1 (should be 1)
  #3 + #4  --> 0 (should be 0)
!(#3 + #4) --> 1 (should be 1)
The FE_INVALID flag is not set for NAN >= 0.
The FE_INVALID flag is not set for NAN <= 0.
The FE_INVALID flag is not set for NAN > 0.
The FE_INVALID flag is not set for NAN < 0.

x * y + z with FP_CONTRACT OFF is not fused.

Error in cast of double to unsigned: incorrect value

Rounding to nearest
-------> to nearest (to nearest / to nearest)
(double) 0 = 0
Signed zero tests (x is 0.0 and y is -0.0):
  Test 1.0 / x != 1.0 / y  returns 1 (should be 1).
  Test 1.0 / x == 1.0 / +x returns 1 (should be 1).
  Test 1.0 / x != 1.0 / +y returns 1 (should be 1).
  Test 1.0 / x != 1.0 / -x returns 1 (should be 1).
  Test 1.0 / x == 1.0 / -y returns 1 (should be 1).
0 + 0 = 0
0 - 0 = 0
0 + -0 = 0
0 - -0 = 0
-0 + 0 = 0
-0 - 0 = -0
-0 + -0 = -0
-0 - -0 = 0
1 + 1 = 2
1 - 1 = 0
1 + -1 = 0
1 - -1 = 2
0 * 0 = 0
0 * -0 = -0
-0 * 0 = -0
-0 * -0 = 0
Constant expression 1 + DBL_MIN = 1
Variable expression 1 + DBL_MIN = 1
Constant expression 1 - DBL_MIN = 1
Variable expression 1 - DBL_MIN = 1
1/3 in float       : 0x1.555556p-2
1/3 in double      : 0x1.5555555555555p-2
1/3 in long double : 0x1.5555555555555p-2
Dec 1.1  = 0x1.199999999999ap+0
FLT_MAX  = 0x1.fffffep+127
DBL_MAX  = 0x1.fffffffffffffp+1023
LDBL_MAX = 0x1.fffffffffffffp+1023
FLT_EPSILON  = 0x1p-23
DBL_EPSILON  = 0x1p-52
LDBL_EPSILON = 0x1p-52
pow(nan, nan) = -inf
pow(nan, inf) = -inf
pow(nan, -inf) = -inf
pow(nan, 0) = -inf
pow(nan, -0) = -inf
pow(nan, 0.5) = -inf
pow(nan, -0.5) = -inf
pow(nan, 1) = -inf
pow(nan, -1) = -inf
pow(nan, 2) = -inf
pow(nan, -2) = -inf
pow(inf, nan) = -inf
pow(inf, inf) = -inf
pow(inf, -inf) = -inf
pow(inf, 0) = -inf
pow(inf, -0) = -inf
pow(inf, 0.5) = -inf
pow(inf, -0.5) = -inf
pow(inf, 1) = -inf
pow(inf, -1) = -inf
pow(inf, 2) = -inf
pow(inf, -2) = -inf
pow(-inf, nan) = -inf
pow(-inf, inf) = -inf
pow(-inf, -inf) = -inf
pow(-inf, 0) = -inf
pow(-inf, -0) = -inf
pow(-inf, 0.5) = -inf
pow(-inf, -0.5) = -inf
pow(-inf, 1) = -inf
pow(-inf, -1) = -inf
pow(-inf, 2) = -inf
pow(-inf, -2) = -inf
pow(0, nan) = -inf
pow(0, inf) = -inf
pow(0, -inf) = -inf
pow(0, 0) = -inf
pow(0, -0) = -inf
pow(0, 0.5) = -inf
pow(0, -0.5) = -inf
pow(0, 1) = -inf
pow(0, -1) = -inf
pow(0, 2) = -inf
pow(0, -2) = -inf
pow(-0, nan) = -inf
pow(-0, inf) = -inf
pow(-0, -inf) = -inf
pow(-0, 0) = -inf
pow(-0, -0) = -inf
pow(-0, 0.5) = -inf
pow(-0, -0.5) = -inf
pow(-0, 1) = -inf
pow(-0, -1) = -inf
pow(-0, 2) = -inf
pow(-0, -2) = -inf
pow(0.5, nan) = -inf
pow(0.5, inf) = -inf
pow(0.5, -inf) = -inf
pow(0.5, 0) = -inf
pow(0.5, -0) = -inf
pow(0.5, 0.5) = -inf
pow(0.5, -0.5) = -inf
pow(0.5, 1) = -inf
pow(0.5, -1) = -inf
pow(0.5, 2) = -inf
pow(0.5, -2) = -inf
pow(-0.5, nan) = -inf
pow(-0.5, inf) = -inf
pow(-0.5, -inf) = -inf
pow(-0.5, 0) = -inf
pow(-0.5, -0) = -inf
pow(-0.5, 0.5) = -inf
pow(-0.5, -0.5) = -inf
pow(-0.5, 1) = -inf
pow(-0.5, -1) = -inf
pow(-0.5, 2) = -inf
pow(-0.5, -2) = -inf
pow(1, nan) = -inf
pow(1, inf) = -inf
pow(1, -inf) = -inf
pow(1, 0) = -inf
pow(1, -0) = -inf
pow(1, 0.5) = -inf
pow(1, -0.5) = -inf
pow(1, 1) = -inf
pow(1, -1) = -inf
pow(1, 2) = -inf
pow(1, -2) = -inf
pow(-1, nan) = -inf
pow(-1, inf) = -inf
pow(-1, -inf) = -inf
pow(-1, 0) = -inf
pow(-1, -0) = -inf
pow(-1, 0.5) = -inf
pow(-1, -0.5) = -inf
pow(-1, 1) = -inf
pow(-1, -1) = -inf
pow(-1, 2) = -inf
pow(-1, -2) = -inf
pow(2, nan) = -inf
pow(2, inf) = -inf
pow(2, -inf) = -inf
pow(2, 0) = -inf
pow(2, -0) = -inf
pow(2, 0.5) = -inf
pow(2, -0.5) = -inf
pow(2, 1) = -inf
pow(2, -1) = -inf
pow(2, 2) = -inf
pow(2, -2) = -inf
pow(-2, nan) = -inf
pow(-2, inf) = -inf
pow(-2, -inf) = -inf
pow(-2, 0) = -inf
pow(-2, -0) = -inf
pow(-2, 0.5) = -inf
pow(-2, -0.5) = -inf
pow(-2, 1) = -inf
pow(-2, -1) = -inf
pow(-2, 2) = -inf
pow(-2, -2) = -inf

Rounding toward 0
Error

Rounding to -oo
Error

Rounding to +oo
Error
```

Not everything is perfectly supported, but most stuff seems to be covered.

[0]: https://www.vinc17.net/research/fptest.en.html

### CODE REVIEW

**Comment by 981213** [comment]
Are you sure the hardware actually have FPU support? It sounds strange that a chip for routers come with the optional FPU because it's useless for networking.
Enabling the FPU support will make hard-float userspace program run on MIPS chips without FPU but that's just kernel trapping the illegal instructions and simulating one. Hard-float apps on simulated FPU will be slower than its soft-float equivalent.

**Comment by oliv3r** [comment]
> Are you sure the hardware actually have FPU support? It sounds strange that a chip for routers come with the optional FPU because it's useless for networking. Enabling the FPU support will make hard-float userspace program run on MIPS chips without FPU but that's just kernel trapping the illegal instructions and simulating one. Hard-float apps on simulated FPU will be slower than its soft-float equivalent.

If I enable the R4K_FPU module, and the chip has no hardware float, will the kernel do software float emulation? My understanding was, that by enabling hardfloat, compiling with --hard-float, and running the code, would only work if we have an actually floating point unit?

**Comment by 981213** [comment]
> If I enable the R4K_FPU module, and the chip has no hardware float, will the kernel do software float emulation?

It will. By enabling CONFIG_MIPS_FP_SUPPORT the linux kernel is built with FPU emulation enabled.

> Anyway, do we have any way to test this?

According to arch/mips/kernel/proc.c (Line 61 in current linux-next):
```c
	sprintf(fmt, "cpu model\t\t: %%s V%%d.%%d%s\n",
		      cpu_data[n].options & MIPS_CPU_FPU ? "  FPU V%d.%d" : "");
```
You'll get an explicit FPU version in /proc/cpuinfo if your CPU comes with an FPU and you have FPU support enabled.

**Comment by 981213** [comment]
> As for the strangeness, not sure it is so strange at all.

All the QCA/Ralink/MTK/Broadcom MIPS chips don't include a FPU. That's why I think it's strange :D

**Comment by oliv3r** [comment]
I'm not seeing this string 'FPU V:' so I see the error of my ways :) I apologize for the noise! I suppose a explicit Kconfig flag would be nice to have under 'enable FP' "emulate FP' that allows you to disable FP emulation, in that case, if hardware has FP, it gets used, otherwise, you get the `SIGILL` as before. But that's a different discussion elsewhere.

Thank you for checking @981213 !

**Comment by 981213** [comment]
> I suppose a explicit Kconfig flag would be nice to have under 'enable FP' "emulate FP' that allows you to disable FP emulation

A quote from https://www.linux-mips.org/wiki/Floating_point:

> MIPS floating point units do not support all operations in hardware. A MIPS implementation is free to not implement certain cases in hardware. For example denormalized numbers - that's numbers very close to zero - are not handled in hardware. In such a case MIPS FPU will throw an unimplemented exception and expects the exception handler to do deal with the issue. The software in the Linux kernel handles all this and more, it's capable of fully emulating a hardware floating point unit. That is code built for hardware floating point will always run correctly, even on systems without an FPU.
> 
> Note that since Linux 2.4.4 there is no kernel configuration option for the floating point assist / floating point emulator anymore. All kernels contain it as too many people got that choice wrong - any system having an FPU in the hardware must have the FPU emulator to guarantee correct operation.

**Pull request closed without merging**
