### PR TITLE
libbsd: update to 0.11.6 and add libmd

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Update libbsd to 0.11.6 and add libmd.

### CODE REVIEW

**Comment by neheb** [comment]
nah. I'd rather replace it with libobsd.

**Comment by neheb** [comment]
https://github.com/openwrt/openwrt/pull/9714 is the PR.

**Comment by PolynomialDivision** [comment]
What about updating and than replacing?

**Comment by hauke** [comment]
How much bigger is the libbsd getting and how big is libmd

**Comment by PolynomialDivision** [comment]
Update:
```
32392	libbsd0_0.11.6-1_aarch64_cortex-a53.ipk
19010	libmd0_1.0.4-1_aarch64_cortex-a53.ipk
```

Before:
```
37615	libbsd0_0.10.0-1_aarch64_cortex-a53.ipk
```

So the library shrinked by `37615-32392=5223 bytes`, so around 5KiB.
With the libmd dependency `((32392+37615)-37615)/1024=31KiB`.
I will have a look again if I can shrink the size.

**Comment by PolynomialDivision** [comment]
@hauke I thought I can link statically against libmd, however it fails with
```
Package libbsd is missing dependencies for the following libraries:
libmd.so.0
```
Am I doing something wrong?

**Comment by neheb** [comment]
Yeah you're installing both versions to InstallDev and libbsd is linking against the shared one.

**Comment by PolynomialDivision** [comment]
> Yeah you're installing both versions to InstallDev and libbsd is linking against the shared one.

But I'm doing:
```
TARGET_LDFLAGS := -Wl,-Bstatic -lmd -Wl,-Bdynamic
```
So that is just ignored?

**Comment by PolynomialDivision** [comment]
Okay, I made libmd now static only. So
```
38514	libbsd0_0.11.6-1_aarch64_cortex-a53.ipk
```
So we have `38514-37615=899` so not even 1 KiB. I think that is good?

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 89a39876072d95fb0016acb989f6e2bc236a48ec and f42e24f19df765b9da05c7bbcafa9428e1f8ef13.

**Comment by neheb** [comment]
So there's actually a hillarious issue here. libbsd.so is actually a text file with the contents:

```
 /* GNU ld script
  * The
OUTPUT_FORMAT(elf64-tradbigmips)
GROUP(/usr/lib/libbsd.so.0.11.6 AS_NEEDED(-lmd))
```

Amazing.

**Pull request closed without merging**
