### PR TITLE
mpc85xx: drop empty patch as it backported to LTS kernel 5.15.70

### PR DESCRIPTION
**Pull request by BKPepe**
This patch is part of Linux kernel 5.15.70, the content was removed, but the empty file is still being carried over the repository, so remove it once for all

Fixes: e1b009c ("kernel: bump 5.15 to 5.15.70")

### CODE REVIEW

**Comment by Ansuel** [comment]
How that even happen wth?

**Comment by BKPepe** [comment]
Well, you should ask @graysky2, I can see the mistake even in web ui. See https://github.com/openwrt/openwrt/pull/10797/files

**Comment by graysky2** [comment]
I do my best to review the diffs between version bumps.  Thanks for catching this, @BKPepe

**Comment by Ansuel** [comment]
@graysky2 you do always great work on refreshing... was just curious if this is the output of an automated tool

**Comment by robimarko** [comment]
LGTM, so:
`Reviewed-by: Robert Marko <robimarko@gmail.com>`

**Comment by graysky2** [comment]
@Ansuel - my SOP is to let the script throw an error about a reverse applied patch, then look up in the changelog to find it to confirm it was upstreamed before I delete it.  If the script did not flag this one as reverse applied, that would explain why I carried it.

**Comment by robimarko** [comment]
Quilt sometimes misses already applied patches, no idea why but I have experienced that before.

BTW, thanks for all of your hard work updating to latest kernel point releases.

**Comment by Ansuel** [comment]
@BKPepe can you rebase so i can flag this as merged?

**Comment by BKPepe** [comment]
Done.

**Pull request merged**
