### PR TITLE
airoha: default to 6.6 and drop 6.1

### PR DESCRIPTION
**Pull request by robimarko**
6.6 has been in testing for a while, so move to it as default and drop 6.1 kernel for airoha.

### CODE REVIEW

**Comment by robimarko** [comment]
@merbanan Any chance you can give it a go?

**Comment by merbanan** [comment]
```
## Loading kernel from FIT Image at 81800000 ...
   Using 'config-1' configuration
   Trying 'kernel-1' kernel subimage
     Description:  ARM OpenWrt Linux-6.6.32
     Type:         Kernel Image
     Compression:  lzma compressed
     Data Start:   0x818000e4
     Data Size:    5234771 Bytes = 5 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: 0x80208000
     Entry Point:  0x80208000
     Hash algo:    crc32
     Hash value:   d3f17eaf
     Hash algo:    sha1
     Hash value:   033d75691de99839e3bed9a8d79fafd9ea484089
   Verifying Hash Integrity ... crc32+ sha1+ OK
## Loading fdt from FIT Image at 81800000 ...
   Using 'config-1' configuration
   Trying 'fdt-1' fdt subimage
     Description:  ARM OpenWrt airoha_en7523-evb device tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x81cfe274
     Data Size:    4555 Bytes = 4.4 KiB
     Architecture: ARM
     Hash algo:    crc32
     Hash value:   55c140b8
     Hash algo:    sha1
     Hash value:   c7b9511fceeed6a6b3268becd261e797e1aaae47
   Verifying Hash Integrity ... crc32+ sha1+ OK
   Booting using the fdt blob at 0x81cfe274
   Uncompressing Kernel Image ... OK
   reserving fdt memory region: addr=80000000 size=200000
   Loading Device Tree to 9cdf6000, end 9cdfa1ca ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 6.6.32 (benjamin@benjamin-12C) (arm-openwrt-linux-muslgnueabi-gcc (OpenWrt GCC 13.3.0 r26515-6e51b363e9) 13
.3.0, GNU ld (GNU Binutils) 2.42) #0 SMP Tue Jun  4 08:19:41 2024
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Airoha EN7523 Evaluation Board
[    0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80200000
[    0.000000] earlycon: ns16550 at MMIO32 0x1fbf0000 (options '115200n8')
[    0.000000] printk: bootconsole [ns16550] enabled
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] OF: reserved mem: 0x84000000..0x849fffff (10240 KiB) nomap non-reusable npu_binary@84000000
[    0.000000] OF: reserved mem: 0x84b00000..0x84bfffff (1024 KiB) nomap non-reusable npu_flag@84B0000
[    0.000000] OF: reserved mem: 0x85000000..0x869fffff (26624 KiB) nomap non-reusable npu_pkt@85000000
[    0.000000] OF: reserved mem: 0x86b00000..0x86bfffff (1024 KiB) nomap non-reusable npu_phyaddr@86B00000
[    0.000000] OF: reserved mem: 0x86d00000..0x86dfffff (1024 KiB) nomap non-reusable npu_rxdesc@86D00000
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000080200000-0x000000009fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080200000-0x0000000083ffffff]
[    0.000000]   node   0: [mem 0x0000000084000000-0x00000000849fffff]
[    0.000000]   node   0: [mem 0x0000000084a00000-0x0000000084afffff]
[    0.000000]   node   0: [mem 0x0000000084b00000-0x0000000084bfffff]
[    0.000000]   node   0: [mem 0x0000000084c00000-0x0000000084ffffff]
[    0.000000]   node   0: [mem 0x0000000085000000-0x00000000869fffff]
[    0.000000]   node   0: [mem 0x0000000086a00000-0x0000000086afffff]
[    0.000000]   node   0: [mem 0x0000000086b00000-0x0000000086bfffff]
[    0.000000]   node   0: [mem 0x0000000086c00000-0x0000000086cfffff]
[    0.000000]   node   0: [mem 0x0000000086d00000-0x0000000086dfffff]
[    0.000000]   node   0: [mem 0x0000000086e00000-0x000000009fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x000000009fffffff]
[    0.000000] On node 0, zone Normal: 512 pages in unavailable ranges
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.1
[    0.000000] percpu: Embedded 13 pages/cpu s20756 r8192 d24300 u53248
[    0.000000] Kernel command line: console=ttyS0,115200 earlycon
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129412
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 459976K/522240K available (6600K kernel code, 575K rwdata, 1652K rodata, 7168K init, 207K bss, 62264K reserved, 0
K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] GICv3: 256 SPIs implemented
[    0.000000] GICv3: 0 Extended SPIs implemented
[    0.000000] GICv3: GICv3 features: 16 PPIs
[    0.000000] GICv3: CPU0: found redistributor 0 region 0:0x09080000
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 timer(s) running at 25.00MHz (virt).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x5c40939b5, max_idle_ns: 440795202646 ns
[    0.000001] sched_clock: 56 bits at 25MHz, resolution 40ns, wraps every 4398046511100ns
[    0.008791] Switching to timer-based delay loop, resolution 40ns
[    0.015482] Calibrating delay loop (skipped), value calculated using timer frequency.. 50.00 BogoMIPS (lpj=250000)
[    0.026861] CPU: Testing write buffer coherency: ok
[    0.032245] pid_max: default: 32768 minimum: 301
[    0.043231] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.051277] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.065024] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.072057] RCU Tasks Trace: Setting shift to 1 and lim to 1 rcu_task_cb_adjust=1.
[    0.080500] Setting up static identity map for 0x80300000 - 0x80300060
[    0.087836] rcu: Hierarchical SRCU implementation.
[    0.093095] rcu:     Max phase no-delay instances is 1000.
[    0.099240] smp: Bringing up secondary CPUs ...
[    0.104738] GICv3: CPU1: found redistributor 1 region 0:0x090a0000
[    0.104789] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.104908] smp: Brought up 1 node, 2 CPUs
[    0.122445] SMP: Total of 2 processors activated (100.00 BogoMIPS).
[    0.129328] CPU: All CPU(s) started in SVC mode.
[    0.136565] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.147449] futex hash table entries: 512 (order: 3, 32768 bytes, linear)
[    0.157952] pinctrl core: initialized pinctrl subsystem
[    0.164973] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.171819] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.180192] cpuidle: using governor menu
[    0.191863] SCSI subsystem initialized
[    0.196205] usbcore: registered new interface driver usbfs
[    0.202272] usbcore: registered new interface driver hub
[    0.208190] usbcore: registered new device driver usb
[    0.214847] clocksource: Switched to clocksource arch_sys_counter
[    0.228370] NET: Registered PF_INET protocol family
[    0.233908] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.242806] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.252050] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.260576] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.269128] TCP bind hash table entries: 4096 (order: 4, 65536 bytes, linear)
[    0.277074] TCP: Hash tables configured (established 4096 bind 4096)
[    0.284152] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.291371] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.299555] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.305851] PCI: CLS 0 bytes, default 64
[    0.311556] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.320182] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.326744] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.341583] mtk-pcie 1fa91000.pcie: host bridge /pcie@1fa91000 ranges:
[    0.348943] mtk-pcie 1fa91000.pcie:      MEM 0x0020000000..0x0021ffffff -> 0x0020000000
[    0.903359] mtk-pcie 1fa91000.pcie: PCI host bridge to bus 0000:00
[    0.910205] pci_bus 0000:00: root bus resource [bus 00-ff]
[    0.916263] pci_bus 0000:00: root bus resource [mem 0x20000000-0x21ffffff]
[    0.924006] pci 0000:00:00.0: [14c3:0810] type 01 class 0x060400
[    0.930789] pci 0000:00:00.0: reg 0x10: can't handle BAR larger than 4GB (size 0x200000000)
[    0.939987] pci 0000:00:00.0: reg 0x10: [mem size 0x00000001 64bit pref disabled]
[    0.949773] PCI: bus0: Fast back to back transfers disabled
[    0.955956] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    0.965424] pci 0000:01:00.0: [14c3:7915] type 00 class 0x000280
[    0.972199] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit pref]
[    0.980260] pci 0000:01:00.0: reg 0x18: [mem 0x00000000-0x00003fff 64bit pref]
[    0.988331] pci 0000:01:00.0: reg 0x20: [mem 0x00000000-0x00000fff 64bit pref]
[    0.996929] pci 0000:01:00.0: supports D1 D2
[    1.001620] pci 0000:01:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[    1.009252] pci 0000:01:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s PCIe x1 link at 0000:00:00.0 (capable of 4.000
 Gb/s with 5.0 GT/s PCIe x1 link)
[    1.026193] PCI: bus1: Fast back to back transfers disabled
[    1.032318] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    1.039674] pci 0000:00:00.0: BAR 8: assigned [mem 0x20000000-0x201fffff]
[    1.047156] pci 0000:00:00.0: BAR 0: assigned [mem 0x20200000 64bit pref disabled]
[    1.055537] pci 0000:00:00.0: BAR 0: error updating (0x2020000c != 0x0000000c)
[    1.063541] pci 0000:01:00.0: BAR 0: assigned [mem 0x20000000-0x200fffff 64bit pref]
[    1.072136] pci 0000:01:00.0: BAR 2: assigned [mem 0x20100000-0x20103fff 64bit pref]
[    1.080736] pci 0000:01:00.0: BAR 4: assigned [mem 0x20104000-0x20104fff 64bit pref]
[    1.089331] pci 0000:00:00.0: PCI bridge to [bus 01]
[    1.094814] pci 0000:00:00.0:   bridge window [mem 0x20000000-0x201fffff]
[    1.102555] pcieport 0000:00:00.0: enabling device (0140 -> 0142)
[    1.109997] pcieport 0000:00:00.0: PME: Signaling with IRQ 29
[    1.117220] mtk-pcie 1fa92000.pcie: host bridge /pcie@1fa92000 ranges:
[    1.124420] mtk-pcie 1fa92000.pcie:      MEM 0x0022000000..0x0023ffffff -> 0x0022000000
[    1.273350] mtk-pcie 1fa92000.pcie: PCI host bridge to bus 0001:00
[    1.280193] pci_bus 0001:00: root bus resource [bus 00-ff]
[    1.286246] pci_bus 0001:00: root bus resource [mem 0x22000000-0x23ffffff]
[    1.294007] pci 0001:00:01.0: [14c3:0811] type 01 class 0x060400
[    1.300788] pci 0001:00:01.0: reg 0x10: can't handle BAR larger than 4GB (size 0x200000000)
[    1.309971] pci 0001:00:01.0: reg 0x10: [mem size 0x00000001 64bit pref disabled]
[    1.319746] PCI: bus0: Fast back to back transfers disabled
[    1.325943] pci 0001:00:01.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    1.335385] pci 0001:01:00.0: [14c3:7915] type 00 class 0x000280
[    1.342164] pci 0001:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit pref]
[    1.350223] pci 0001:01:00.0: reg 0x18: [mem 0x00000000-0x00003fff 64bit pref]
[    1.358287] pci 0001:01:00.0: reg 0x20: [mem 0x00000000-0x00000fff 64bit pref]
[    1.366878] pci 0001:01:00.0: supports D1 D2
[    1.371567] pci 0001:01:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[    1.379199] pci 0001:01:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s PCIe x1 link at 0001:00:01.0 (capable of 4.000
 Gb/s with 5.0 GT/s PCIe x1 link)
[    1.396149] PCI: bus1: Fast back to back transfers disabled
[    1.402275] pci_bus 0001:01: busn_res: [bus 01-ff] end is updated to 01
[    1.409630] pci 0001:00:01.0: BAR 8: assigned [mem 0x22000000-0x221fffff]
[    1.417110] pci 0001:00:01.0: BAR 0: assigned [mem 0x22200000 64bit pref disabled]
[    1.425487] pci 0001:00:01.0: BAR 0: error updating (0x2220000c != 0x0000000c)
[    1.433455] pci 0001:01:00.0: BAR 0: assigned [mem 0x22000000-0x220fffff 64bit pref]
[    1.442056] pci 0001:01:00.0: BAR 2: assigned [mem 0x22100000-0x22103fff 64bit pref]
[    1.450649] pci 0001:01:00.0: BAR 4: assigned [mem 0x22104000-0x22104fff 64bit pref]
[    1.459250] pci 0001:00:01.0: PCI bridge to [bus 01]
[    1.464735] pci 0001:00:01.0:   bridge window [mem 0x22000000-0x221fffff]
[    1.472500] pcieport 0001:00:01.0: enabling device (0140 -> 0142)
[    1.480019] pcieport 0001:00:01.0: PME: Signaling with IRQ 31
[    1.487392] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    1.495447] printk: console [ttyS0] disabled
[    1.500549] 1fbf0000.serial: ttyS0 at MMIO 0x1fbf0000 (irq = 32, base_baud = 115200) is a 16550
[    1.510205] printk: console [ttyS0] enabled
[    1.510205] printk: console [ttyS0] enabled
[    1.518999] printk: bootconsole [ns16550] disabled
[    1.518999] printk: bootconsole [ns16550] disabled
[    1.532135] spi-nand spi0.0: Micron SPI NAND was found.
[    1.537441] spi-nand spi0.0: 256 MiB, block size: 128 KiB, page size: 2048, OOB size: 128
[    1.550919] 4 fixed-partitions partitions found on MTD device spi0.0
[    1.557329] Creating 4 MTD partitions on "spi0.0":
[    1.562127] 0x000000000000-0x00000007c000 : "u-boot"
[    1.568572] 0x00000007c000-0x000000080000 : "u-boot-env"
[    1.573905] mtd: partition "u-boot-env" doesn't start on an erase/write block boundary -- force read-only
[    1.584373] 0x000000080000-0x0000000c0000 : "art"
[    1.590244] 0x0000000c0000-0x00000e000000 : "firmware"
[    3.706647] no rootfs found after FIT image in "firmware"
[    3.715345] NET: Registered PF_INET6 protocol family
[    3.721558] Segment Routing with IPv6
[    3.725348] In-situ OAM (IOAM) with IPv6
[    3.729360] NET: Registered PF_PACKET protocol family
[    3.734435] 8021q: 802.1Q VLAN Support v1.8
[    3.738695] Registering SWP/SWPB emulation handler
[    3.765236] clk: Disabling unused clocks
[    3.776462] Freeing unused kernel image (initmem) memory: 7168K
[    3.782655] Run /init as init process
[    3.962329] init: Console is alive
[    3.971220] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    3.979541] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    3.996884] init: - preinit -
[    7.014855] random: crng init done
script "minicomscript.txt": global timeout
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[    9.110015] procd: - early -
[    9.635371] procd: - ubus -
[    9.691333] procd: - init -
Please press Enter to activate this console.
[    9.910057] kmodloader: loading kernel modules from /etc/modules.d/*
[    9.966951] PPP generic driver version 2.4.2
[    9.973173] NET: Registered PF_PPPOX protocol family
[    9.988280] kmodloader: done loading kernel modules from /etc/modules.d/*
[   10.516015] urngd: v1.0.2 started.



BusyBox v1.36.1 (2024-05-18 13:05:55 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r26515-6e51b363e9
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@OpenWrt:/# 

```

**Comment by merbanan** [comment]
> @merbanan Any chance you can give it a go?

```
diff --git a/target/linux/airoha/Makefile b/target/linux/airoha/Makefile
index 50c871edaa..99ce7443ec 100644
--- a/target/linux/airoha/Makefile
+++ b/target/linux/airoha/Makefile
@@ -6,8 +6,7 @@ BOARDNAME:=Airoha ARM
 CPU_TYPE:=cortex-a7
 FEATURES:=dt squashfs nand ramdisk gpio source-only
 
-KERNEL_PATCHVER:=6.1
-KERNEL_TESTING_PATCHVER:=6.6
+KERNEL_PATCHVER:=6.6
 
 include $(INCLUDE_DIR)/target.mk
```

I recreated the diff, reconfigured, rebuilt and booted the image. Looks like it worked fine.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
