### PR TITLE
CC: ar71xx: backport LED fix for TL-WR841N-v11

### PR DESCRIPTION
**Pull request by shalzz**

### CODE REVIEW

**Comment by wigyori** [comment]
Nitpicking only - please update the commit message to have "CC: ar71xx: " prefix, as per https://lists.openwrt.org/pipermail/openwrt-devel/2016-September/042235.html

**Comment by Shalzz** [comment]
Updated.

**Comment by wigyori** [comment]
Thanks, can you please add a Signed-off-by to the commit as well.

**Comment by Shalzz** [comment]
done

**Pull request merged**
