### PR TITLE
kernel: bump 5.15 to 5.15.148

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.148

Removed upstreamed:
	generic/hack-5.15/321-powerpc_crtsavres_prereq.patch[1]

Manually rebased:
        target/linux/octeontx/patches-5.15/0004-PCI-add-quirk-for-Gateworks-PLX-PEX860x-switch-with-.patch[2]

All other patches automatically rebased.

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.148&id=0b11a145eb00d51f7ef18cfcae587b93f9adb1e9
2. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit?h=v5.15.148&id=b67064bd372300a75293efbbc70624996dccffd4

Build system: x86_64
Build-tested: ramips/tplink_archer-a6-v3
Run-tested: ramips/tplink_archer-a6-v3

### CODE REVIEW

**Comment by graysky2** [comment]
I refreshed this a 2nd time but found no changes.  I do not know why octeontx/generic is failing.

**Comment by DragonBluep** [comment]
Perhaps you can try adding 4 lines offset to the patch.

https://github.com/openwrt/openwrt/blob/0c45d2cfc6a0ca036af036771d0f1b36a3836bcc/target/linux/octeontx/patches-5.15/0004-PCI-add-quirk-for-Gateworks-PLX-PEX860x-switch-with-.patch#L25
Change this line to
` @@ -5883,3 +5884,34 @@ static void nvidia_ion_ahci_fixup(struct `

Ref:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit?h=v5.15.148&id=b67064bd372300a75293efbbc70624996dccffd4

**Comment by graysky2** [comment]
Thanks for the suggestion @DragonBluep, let's see it passes.

**Comment by MoetaYuko** [comment]
> Removed upstreamed: generic/hack-5.15/321-powerpc_crtsavres_prereq.patch[1]

something wrong with this, ppc targets failed to build https://downloads.openwrt.org/snapshots/faillogs/powerpc_464fp/base/cryptodev-linux/compile.txt

**Pull request merged**
