### PR TITLE
fix url for kernel

### PR DESCRIPTION
**Pull request by mikysal78**

### CODE REVIEW

**Comment by riblo** [comment]
I also need this 👍

**Comment by nemesisdesign** [comment]
Just [sent an email on openwrt-devel](https://lists.openwrt.org/pipermail/openwrt-devel/2017-March/042842.html), I hope somebody will take care of this.

**Comment by wigyori** [comment]
Hi,

Thanks for the PR - there are a few issues with the PR, f.e. no Signed-off-by, and the title is incorrect. To make things quick, I've backported Hauke's change from trunk into 9a1fd3e, which is the same chang e- thanks for the fix anyway.

Regards,
-w-

**Comment by nemesisdesign** [comment]
ok, thx

**Comment by mikysal78** [comment]
grazie! :)

**Pull request closed without merging**
