### PR TITLE
ipq40xx: add kernel 5.10 testing kernel support

### PR DESCRIPTION
**Pull request by blocktrron**
Add Kernel 5.10 support as testing kernel for ipq40xx.

Tested-on: Aruba AP-303

Signed-off-by: David Bauer <mail@david-bauer.net>

### CODE REVIEW

**Comment by SirDMZ** [comment]
appears to break ethernet on gl-inet b1300. investigation ongoing.

**Comment by robimarko** [comment]
This will break networking due to MDIO drivers being separated out to their folder.
This will in turn cause the AR40xx to probe first and then fails on the MDIO bus as it is not yet registered.
Deferring the probe won't help also as it will succeed in finding the MDIO bus but there will be no traffic.
The only workaround is to move the AR40xx into the MDIO folder as well.

**Comment by chunkeey** [comment]
@robimarko didn't you have a 5.10+ tree with the ipqess / dsa as well? Or has this sadly folded because of the pesky hardware behavior with DSA?

**Comment by robimarko** [comment]
At work, we have a public 5.9-RC6 branch with DSA, however, note that after X amount of traffic it locks up.
https://github.com/sartura/linux/tree/ipq40xx/linux-v5.9-rc6-ipqess

I can't share much, but we are working on it, gotta check with management whether WIP stuff can be published as well to have wider testing of it.
Let's just say that IPQ40xx and sadly IPQ807x as well as IPQ50xx which have just copy/pasted the switch + PSGMII stuff is not really the best HW and is really hard to do properly with DSA.

**Comment by chunkeey** [comment]
> I can't share much, but we are working on it, gotta check with management whether WIP stuff can be published as well to have wider testing of it.
Let's just say that IPQ40xx and sadly IPQ807x as well as IPQ50xx which have just copy/pasted the switch + PSGMII stuff is not really the best HW and is really hard to do properly with DSA.

Hm, glitchy stuff and I wasted so much time on these. But without a "hint" where to look this is for now a dead-end.
Ok, so 5.10 keeps the hacked google swconfig driver, but it moves to a different location.

**Comment by robimarko** [comment]
> Hm, glitchy stuff and I wasted so much time on these. But without a "hint" where to look this is for now a dead-end.
> Ok, so 5.10 keeps the hacked google swconfig driver, but it moves to a different location.

Yeah, really finicky HW.
It looks like "AR40xx" is gonna live with another few kernel versions(BTW I have it running even on 5.12)

**Comment by Boos4721** [comment]
humm, isnt boot

**Comment by PolynomialDivision** [comment]
@blocktrron The 100-GPIO patch is already accepted treewide, so the image does not build. ;) Just wanted to test the 5.10 on a 7530.
https://github.com/openwrt/openwrt/blob/master/target/linux/generic/hack-5.10/800-GPIO-add-named-gpio-exports.patch

**Comment by PolynomialDivision** [comment]
>  The only workaround is to move the AR40xx into the MDIO folder as well.

Let's do it, so we can go to new kernel? Just testing.

**Comment by robimarko** [comment]
I started working on 5.10 for ipq40xx as I need it, so I should have something soon.

**Comment by PolynomialDivision** [comment]
> I started working on 5.10 for ipq40xx as I need it, so I should have something soon.

Nice to hear, then I will just wait. :) With DSA support?

**Comment by robimarko** [comment]
Nope, DSA is still in the works, a low priority though.
I will see at work whether it can be shared so that it gets some outside testing.

**Comment by PolynomialDivision** [comment]
>  I will see at work whether it can be shared so that it gets some outside testing.

Great. Always willing to test new stuff. We still have some issues with crashing/freezing switches. We wrote a watchdog that restarts devices if something like that happens. Also wrote with @blocktrron in a private email chat about it.

As you can see here, the uptime is very bad:
uptimeemma

http://monitor.berlin.freifunk.net/detail.php?p=uptime&t=uptime&h=emma-core&s=31536000

**Comment by PolynomialDivision** [comment]
We can close this PR (but I can't).

**Pull request closed without merging**
