### PR TITLE
ramips: add kmod-mt71615e to Netgear R6350 image for 5Ghz support

### PR DESCRIPTION
**Pull request by nicefile**
This cover all  FCC ID PY317300390  Netgear devices:
R6350
R6260
R6850
WAC124 
Tested ok on my R6260 with Intel AC8260

### CODE REVIEW

**Comment by nicefile** [comment]
Yes increment is not needed there as 0x8004  factory have needed address . Also I can confirm it match stock firmware

**Comment by pepe2k** [comment]
Hello @nicefile,

Please, read our [submitting patches rules](https://openwrt.org/submitting-patches), and make sure your pull request follows them - at the moment, your commits have formal issues, like missing SoB lines.

Cheers,
Piotr

**Comment by achterin** [comment]
As stated in my PR #2358 these devices seem to be hardware identical, but while writing support for R6260 i discovered that the firmware1 partition defined in the dts for R6350 is larger than it is in the original firmware for R6260. This means either that the original author made a small mistake or the flash layout is slightly different.
If it's a mistake, i think the best approach would be to use a shared dtsi. If not, then i would not test images for R6350 on a R6250, even if the images work properly.

**Comment by nicefile** [comment]
> As stated in my PR #2358 these devices seem to be hardware identical, but while writing support for R6260 i discovered that the firmware1 partition defined in the dts for R6350 is larger than it is in the original firmware for R6260. This means either that the original author made a small mistake or the flash layout is slightly different.
> If it's a mistake, i think the best approach would be to use a shared dtsi. If not, then i would not test images for R6350 on a R6250, even if the images work properly.

I have R6250 and I can confirm the dts for R6350 is ok  (apart mt7615 declaration missing). As I've build 
Missing 1MB is on the end of the NAND And it's not even declared in oem firmware .I'm sure users can live with wasted 1MB .
oem mtd definition cover  first 127MB  NAND
openwrt mtd definitrion cover all 128MB NAND

**Comment by nicefile** [comment]
> No address being loaded with eeprom from 0x8000?

Yes You are right . I was wrong . I did change to use  0x8004 mac addres for 5Ghz

**Comment by achterin** [comment]
> I have R6250 and I can confirm the dts for R6350 is ok (apart mt7615 declaration missing). As I've build firmware from sources.

Sorry, i've mistyped the device name, as there is no R6250. What I meant to say is that if both devices have a slightly different flash-layout with oem-firmware it is a bad idea to cross-test changes. All you have done is testing 5GHz support for R6260, not R6350.
We need to be sure that both devices use the same (shorter) layout and therefore need someone with a R6350 who could check the oem-firmware.

**Comment by nicefile** [comment]
> Sorry, i've mistyped the device name, as there is no R6250. What I meant to say is that if both devices have a slightly different flash-layout with oem-firmware it is a bad idea to cross-test changes. All you have done is testing 5GHz support for R6260, not R6350.
> We need to be sure that both devices use the same (shorter) layout and therefore need someone with a R6350 who could check the oem-firmware.

Sure I meant R6260 not R6250 . I've done successful R6260 recovery using nmrpflash and R6260/R6350/R6850 firmware. Unless proved wrong we are good to leave this as it is. No harm done as OpenWrt use that bits in read-only

**Comment by achterin** [comment]
> I've done successful R6260 recovery using nmrpflash and R6260/R6350/R6850 firmware.

There is no universal firmware for all 3 devices, each one has its own. So to be clear: have you tried all 3 firmwares on your device?

**Comment by achterin** [comment]
@adrianschmutzler no need to test, both lines are obsolete as can be seen in my r6260 pr. both macs get setup just fine.

**Comment by nicefile** [comment]
> > I've done successful R6260 recovery using nmrpflash and R6260/R6350/R6850 firmware.
> 
> AFAIK There is no universal firmware for all 3 devices, each one has its own. So to be clear: have you tried all 3 firmwares on your device?
Don't have too as they share same hash
c411b683eab7c4b3d27b8dafdcd88627 *R6350-V1.1.0.52.img
c411b683eab7c4b3d27b8dafdcd88627 *R6260-V1.1.0.52.img
c411b683eab7c4b3d27b8dafdcd88627 *R6850-V1.1.0.52.img

**Comment by achterin** [comment]
> Don't have too as they share same hash
> c411b683eab7c4b3d27b8dafdcd88627 *R6350-V1.1.0.52.img
> c411b683eab7c4b3d27b8dafdcd88627 *R6260-V1.1.0.52.img
> c411b683eab7c4b3d27b8dafdcd88627 *R6850-V1.1.0.52.img

nice catch! i will adjust my commit and merge the dts files. thanks!

**Comment by nicefile** [comment]
#2358 Cover this change` so this pull  is closed now.

**Pull request closed without merging**
