### PR TITLE
x86: geode: 6.6: add missing kernel options

### PR DESCRIPTION
**Pull request by namiltd**
Add options removed by `make kernel_oldconfig CONFIG_TARGET=subtarget', missing which causes compilation to stop and cause an error.

### CODE REVIEW

**Comment by namiltd** [comment]
@robimarko Please take a look at this PR

**Comment by robimarko** [comment]
How can I reproduce this?

I tried building locally for Geode generic and 6.6 and kernel builds just fine

**Comment by namiltd** [comment]
During build and checking on Github e.g. https://github.com/openwrt/openwrt/actions/runs/8576644772/job/23508986751

**Comment by namiltd** [comment]
This is not a bug. Please post your questions at https://forum.openwrt.org/c/devel/8

**Comment by robimarko** [comment]
Well, I find it rather weird it doesn't happen localy

**Comment by namiltd** [comment]
I experienced the same thing, but decided that adding these options wouldn't break anything but fix the build on Github.

**Comment by namiltd** [comment]
@robimarko The problem occurs locally if we set:
```
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_geode=y
CONFIG_TARGET_x86_geode_DEVICE_generic=y
CONFIG_ALL_KMODS=y
CONFIG_DEVEL=y
CONFIG_AUTOREMOVE=y
CONFIG_BUILD_NLS=y
CONFIG_CCACHE=y
CONFIG_KERNEL_WERROR=y
CONFIG_LINUX_6_6=y
CONFIG_TESTING_KERNEL=y
```
I copied these settings from the Github test machine.

**Comment by robimarko** [comment]
Ok, can you add a Fixes tag to the commit?

**Comment by namiltd** [comment]
@robimarko Is that enough or o you have any other suggestions?

**Comment by robimarko** [comment]
Look at:
https://github.com/openwrt/openwrt/commit/076e86041862ff7962c395706238c69fc8b83594

Fixes that is short hash (12 long) and the commit name you are fixing/blaming

**Comment by namiltd** [comment]
@robimarko Done

**Comment by robimarko** [comment]
@namiltd No, it's not supposed to be a GH link to the commit.
Put `2a86425de107` instead

**Comment by namiltd** [comment]
I shortened the number.

**Comment by robimarko** [comment]
Well, no idea what is going on but GH is expanding the hash into its own link.
I assume you are editing this locally?

**Comment by namiltd** [comment]
Now it should be OK. Sorry for the confusion.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
