### PR TITLE
kernel: bump 5.4 to 5.4.64

### PR DESCRIPTION
**Pull request by graysky2**
Remove upstreamed patches:
 generic-backport
  `701-v5.5-net-core-use-listified-Rx-for-GRO_NORMAL-in-napi_gro.patch`

Manually merged:
 mediatek/patches-5.4
  `0603-net-dsa-mt7530-Extend-device-data-ready-for-adding-a.patch`

All other modifications made by `update_kernel.sh`

Build system: x86_64
Run-tested: ipq806x (R7800)

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by zuzia-dev** [comment]
Lantiq xrx200 - everything works fine.

**Comment by curtdept** [comment]
Build test ok : Curtis Deptuck <curtdept@me.com>

Wont get to run test until EOD.

**Comment by adschm** [comment]
Looks good, will merge with another run test.

@zuzia-dev Please specify whether run-test or build-test. For run-test, name the device.

**Comment by anomeome** [comment]
compile / test : mvebu / mamba, rango

**Comment by graysky2** [comment]
In addition to the mvebu/mamba,rango result from @anomeome, @ldir-EDB0 has independently arrived at the same commit.  I do not know what hardware he is using or if he tested.

**Comment by zuzia-dev** [comment]
> @zuzia-dev Please specify whether run-test or build-test. For run-test, name the device.

Build system: x86_64
Run-tested: xrx200 (Easybox 904 xDSL).

**Comment by adschm** [comment]
Thanks, merged.

**Pull request closed without merging**
