### PR TITLE
mvebu: Armada 37xx PCIe controller backports

### PR DESCRIPTION
**Pull request by elkablo**
The first patch ports back Armada 3720's PCIe controller driver [fixes staged for Linux 5.17](https://lore.kernel.org/linux-pci/20211130172913.9727-1-kabel@kernel.org/).

The second patch ports back [pending fixes for this PCIe controller driver](https://lore.kernel.org/linux-pci/20220110015018.26359-1-kabel@kernel.org/).

With these patches ported back, the controller now correctly supports MSI and MSI-X interrupts, which, among other things, makes it possible to use NVMe drives on this platform (for example on ESPRESSObin, @tmn505).

NVMe support for mvebu is being enabled by pull request #4919.

### CODE REVIEW

**Comment by BKPepe** [comment]
There's is already my PR to enable NVMe - https://github.com/openwrt/openwrt/pull/4919 . :(

**Comment by elkablo** [comment]
@tmn505 @v-vid @adschm @rsalvaterra @dhewg could some of you find time to review this?

**Comment by elkablo** [comment]
> There's is already my PR to enable NVMe - #4919 . :(

Ok, removed the last patch enabling NVMe, let's do that with your PR.

**Review by rsalvaterra — APPROVED** [review]
I'm not really qualified for reviewing the patches' contents. Being backports, however, means they had to be reviewed/acked by the upstream maintainers. With that in mind, the pull looks good to me.

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
