### PR TITLE
toolchain: Use binutils 2.32 by default

### PR DESCRIPTION
**Pull request by diizzyy**
Switch to binutils 2.32 for all targets

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile and run tests on multiple platforms
https://github.com/openwrt/openwrt/pull/1803#issuecomment-461979479

**Comment by neheb** [comment]
Last time I tried this on MIPS, the toolchain did not compile. Works fine on ARC, ARM, and PPC.

**Comment by diizzyy** [comment]
....and that was?

**Comment by neheb** [comment]
I tried again. I can't seem to reproduce. Never mind :).

**Comment by diizzyy** [comment]
Compile tested: ipq40xx, Linksys EA6350v3, OpenWrt master
Run tested: ipq40xx, Linksys EA6350v3, OpenWrt master

**Comment by mx2345** [comment]
Have been using binutils 2.32 for my builds since February and haven't noticed any problems so far.

Compile and run tested: DIR-645 (ramips), UAP-AC-LR (ath79), FRITZ3370 (lantiq) - OpenWrt master

**Comment by diizzyy** [comment]
2.33.1 is even out at this time ;-)

**Comment by nasbdh9** [comment]
Tested on multiple targets without problems...
( apm821xx ramips ath79 ipq40xx mvebu x86_64 )

**Pull request closed without merging**
