### PR TITLE
meson: add support for Thunder OneCloud

### PR DESCRIPTION
**Pull request by shiyu1314**
Specifications:

SoC: Amlogic S805 ARM Cortex-A53 1.5 GHz
RAM: 1 GB RAM
Flash: 8 GB eMMC
LAN: 1x RTL8211F Gigabit Ethernet/at support
LEDs: 1x blue and 1x red
USB：Two USB 2.0
Buttons: 1x reset button

Flashing instructions:
Standard onecloud SD card installation procedure - copy image to SD card, insert into SD card slot on the device and boot.

u-boot
https://github.com/shiyu1314/u-boot-onecloud/releases

### CODE REVIEW

**Comment by motolav** [comment]
You're adding a new target so your title should be something like
`meson: add target for Amlogic Meson SOCs`
and maybe use a separate commit for adding support for the device `Thunder OneCloud`
`meson: add support for Thunder OneCloud`

**Comment by Ansuel** [comment]
@shiyu1314 

image

quick guide on how to better handle this
```
git add .
git commit 
git push --force
```

And pr gets magically updated... Please don't open any new pr also we lose track of the history and any intermediate review.
It's just a friendly warning to help you in getting this merged, please follow what we ask!

**Comment by Ansuel** [comment]
@shiyu1314 thanks a lot for following the advice!

**Comment by Ansuel** [comment]
Run a make target/linux/clean 
There are currently some additional config option that has to be disabled in your config-6.1 file

**Comment by shiyu1314** [comment]
> Run a make target/linux/clean There are currently some additional config option that has to be disabled in your config-6.1 file

Thank you for your patience. You can compile now

**Pull request closed without merging**
