### PR TITLE
ipq806x: setup DSA port conduit in board.d

### PR DESCRIPTION
**Pull request by Ansuel**
Now that netifd and uci-defaults.sh supports a way to setup DSA port
conduit without using iproute2 tool, set DSA port conduit directly in
board.d, that will fill board.d and will instruct netifd to setup the
port.

Drop special init.d qca8k_set_port script and ip-tiny from target dep as
they are not required anymore.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by e9hack** [comment]
It looks like netifd does compile with kernel 6.1 only. With kernel 5.15, definition of IFLA_DSA_MASTER is missing.

**Comment by Ansuel** [comment]
@e9hack indeed i didn't think about that!

**Comment by Ansuel** [comment]
@e9hack thanks for the report fixed!

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
good solution for gro.

**Comment by e9hack** [comment]
@Ansuel 
If I do the same setup in 02_network for the Archer C7 v2, there is no traffic over lanX/wan possible. Do I missing something?

**Comment by Ansuel** [comment]
You should check IP link also did you test with latest commit?

Il Dom 12 Nov 2023, 18:16 e9hack ***@***.***> ha scritto:

**Comment by neheb** [comment]
@elkablo may be able to help. He has a big endian device with two CPU ports connected to the switch.

**Comment by e9hack** [comment]
I didn't use the latest netifd. I did use one version before. Now it works initially. 

I see other strange things. 

If I set lan3 (or lan1 or lan2) to eth0, traffic on all three ports stops. Lan1-3 is part of a bridge. Lan4 is used as a single interface. If I set all three ports to eth0, traffic is running again. If I toggle some ports, but let one port at eth0, traffic is continuously running. If I set all ports back to eth1 and now a single port again to eth0, the game starts again. Traffic is continuously pinging via a connected PC. 

If I transfer data over a port which is set to eth0, it looks like that the traffic is running over eth1. ifconfig shows the traffic for eth1 and not for eth0. Traffic is a file transfer via scp.

**Comment by e9hack** [comment]
> I see other strange things.

They are an issue of qca8k_setup(). It does initialize everything related to the first found cpu port only. If it does initialize everything related to both cpu ports, both issues are gone.

**Comment by e9hack** [comment]
To get eth0 property working for the TP Link Archer C7 v2, I need the following additional patch:
```--- a/drivers/net/dsa/qca/qca8k-8xxx.c	2023-11-14 16:43:02.000000000 +0100
+++ b/drivers/net/dsa/qca/qca8k-8xxx.c	2023-11-14 17:25:20.000000000 +0100
@@ -898,13 +898,14 @@ static int
 qca8k_internal_mdio_write(struct mii_bus *slave_bus, int phy, int regnum, u16 data)
 {
 	struct qca8k_priv *priv = slave_bus->priv;
+#if 0
 	int ret;
 
 	/* Use mdio Ethernet when available, fallback to legacy one on error */
 	ret = qca8k_phy_eth_command(priv, false, phy, regnum, data);
 	if (!ret)
 		return 0;
-
+#endif
 	return qca8k_mdio_write(priv, phy, regnum, data);
 }
 
@@ -913,12 +914,12 @@ qca8k_internal_mdio_read(struct mii_bus
 {
 	struct qca8k_priv *priv = slave_bus->priv;
 	int ret;
-
+#if 0
 	/* Use mdio Ethernet when available, fallback to legacy one on error */
 	ret = qca8k_phy_eth_command(priv, true, phy, regnum, 0);
 	if (ret >= 0)
 		return ret;
-
+#endif
 	ret = qca8k_mdio_read(priv, phy, regnum);
 
 	if (ret < 0)
@@ -1075,20 +1076,19 @@ qca8k_setup_mac_pwr_sel(struct qca8k_pri
 	return ret;
 }
 
-static int qca8k_find_cpu_port(struct dsa_switch *ds)
+static u8 qca8k_find_cpu_ports(struct dsa_switch *ds)
 {
 	struct qca8k_priv *priv = ds->priv;
+	u8 res = 0;
 
 	/* Find the connected cpu port. Valid port are 0 or 6 */
 	if (dsa_is_cpu_port(ds, 0))
-		return 0;
-
-	dev_dbg(priv->dev, "port 0 is not the CPU port. Checking port 6");
+		res |= BIT(0);
 
 	if (dsa_is_cpu_port(ds, 6))
-		return 6;
+		res |= BIT(6);
 
-	return -EINVAL;
+	return res;
 }
 
 static int
@@ -1934,13 +1934,14 @@ qca8k_setup(struct dsa_switch *ds)
 {
 	struct qca8k_priv *priv = (struct qca8k_priv *)ds->priv;
 	struct dsa_port *dp;
-	int cpu_port, ret;
+	int ret;
 	u32 mask;
+	u8 cpu_ports;
 
-	cpu_port = qca8k_find_cpu_port(ds);
-	if (cpu_port < 0) {
+	cpu_ports = qca8k_find_cpu_ports(ds);
+	if (!cpu_ports) {
 		dev_err(priv->dev, "No cpu port configured in both cpu port0 and port6");
-		return cpu_port;
+		return -EINVAL;
 	}
 
 	/* Parse CPU port config to be later used in phy_link mac_config */
@@ -2028,10 +2029,13 @@ qca8k_setup(struct dsa_switch *ds)
 		return ret;
 
 	/* CPU port gets connected to all user ports of the switch */
-	ret = qca8k_rmw(priv, QCA8K_PORT_LOOKUP_CTRL(cpu_port),
-			QCA8K_PORT_LOOKUP_MEMBER, dsa_user_ports(ds));
-	if (ret)
-		return ret;
+	dsa_switch_for_each_cpu_port(dp, ds) {
+		ret = qca8k_rmw(priv, QCA8K_PORT_LOOKUP_CTRL(dp->index),
+				QCA8K_PORT_LOOKUP_MEMBER, dsa_user_ports(ds));
+		if (ret < 0)
+			return ret;
+	}
+
 
 	/* Setup connection between CPU port & user ports
 	 * Individual user ports get connected to CPU port only
@@ -2041,7 +2045,7 @@ qca8k_setup(struct dsa_switch *ds)
 
 		ret = qca8k_rmw(priv, QCA8K_PORT_LOOKUP_CTRL(port),
 				QCA8K_PORT_LOOKUP_MEMBER,
-				BIT(cpu_port));
+				cpu_ports);
 		if (ret)
 			return ret;
 
```

**Comment by neheb** [comment]
@Ansuel I see

```
target/linux/ipq806x/config-6.1:CONFIG_ETHERNET_PACKET_MANGLE=y
```

is this needed anymore?

**Pull request merged**
