### PR TITLE
kernel: bump 6.1 to 6.1.54

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.54

Removed upstreamed:
        generic/backport-6.1/020-v6.3-02-UPSTREAM-mm-multi-gen-LRU-rename-lrugen-lists-to-lru.patch[1]
        ipq806x/patches-6.1/140-v6.5-hwspinlock-qcom-add-missing-regmap-config-for-SFPB-M.patch[2]

All other patches automatically rebased.

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.54&id=a73d04c460521e45f257d28d73df096e41ece324
2. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.54&id=e93bc372dbc0bde133c854c03502a95617041972

Build system: x86/64
Build-tested: x86/64/AMD Cezanne
Run-tested: x86/64/AMD Cezanne

### CODE REVIEW

**Comment by graysky2** [comment]
In which file/files should I add the new symbol `CONFIG_VIDEO_CAMERA_SENSOR=y`?

Failing builds include:
```
target-arm-openwrt-linux-muslgnueabi_musl/linux-armsr_armv7
target-arm-openwrt-linux-muslgnueabi_musl/linux-bcm27xx_bcm2708
target-arm-openwrt-linux-muslgnueabi_musl/linux-ipq806x_chromium
target-aarch64-openwrt-linux-musl_musl/linux-qualcommax_ipq807x
```

**Comment by robimarko** [comment]
`CONFIG_VIDEO_CAMERA_SENSOR` should just be disabled in the generic config.
Definitively not needed on ipq806x and ipq807x, if required targets can later override the generic config.

**Comment by graysky2** [comment]
Thanks @robimarko - I did this.  For bcm27xx targets I have it enabled though.

**Comment by graysky2** [comment]
@robimarko - any insight into the failure of that module for bcm27xx?

**Comment by hauke** [comment]
Are the packages depending on `kmod-video-core` still including their .ko files?

Maybe we should activate `CONFIG_VIDEO_CAMERA_SENSOR` in the generic configuration because this is not activating any compile units it just hides many options.

**Comment by graysky2** [comment]
I just force-pushed it, @hauke

**Comment by graysky2** [comment]
@hauke - any other ideas to try?  6.1.54-rc1 was released overnight.

**Comment by robimarko** [comment]
Well, it's basically asking for `MEDIA_SUPPORT` and `MEDIA_CONTROLLER` but I still need to figure out what is now trying to include them.

**Comment by robimarko** [comment]
@Ansuel Can we get this merged?

**Pull request merged**
