### PR TITLE
nftables: update to 1.1.1

### PR DESCRIPTION
**Pull request by hauke**
* libnftnl: update to 1.2.8
    
    Release Announcement:
    https://www.spinics.net/lists/netfilter-devel/msg87287.html
    https://www.spinics.net/lists/netfilter-devel/msg88520.html

 * nftables: update to 1.1.1

    Release Announcement:
    https://lwn.net/Articles/982283/
    https://lwn.net/Articles/992760/

### CODE REVIEW

**Comment by xiaobaishu1** [comment]
expr/fullcone.c:161:10: error: 'struct expr_ops' has no member named 'max_attr'
  161 |         .max_attr       = NFTA_FULLCONE_MAX,
      |          ^~~~~~~~

**Comment by hauke** [comment]
I have to test it more before merging. If someone is testing this please report your results in a comment.

**Comment by rmandrad** [comment]
tested-by: Rudy Andram <rmandrad@gmail.com>

mediatek bananapi4

`nftables v1.1.1 (Commodore Bullmoose #2)`

the only thing I noticed is I don't see nft offload while doing an iperf in spite of having nft_flow_offload loaded and hw offload settings enabled on the firewall 

fw4 print | grep offload shows
`                flags offload;
                meta l4proto { tcp, udp } flow offload @ft`

**Comment by Neustradamus** [comment]
@hauke: Thanks!

**Pull request merged**
