### PR TITLE
ramips: tl-wr840n-v5: increase firmware partition for 4Mmtk layot

### PR DESCRIPTION
**Pull request by xssa**
According to console log during TP-Link TL-WR840N v5 OEM firmware update
procedure 0x3e0000-0x3f0000 64kB "config" partition, which is used to store
router's configuration settings, is erased and recreated again during every
OEM firmware update procedure, thus does not contain any valuable factory data.
So it is convinient to use this extra 64kB erase block for jffs overlay due
limited flash size on this device like it used on TP-Link's ar71xx boards.

Signed-off-by: Serg Studzinskii <serguzhg@gmail.com>

### CODE REVIEW

**Comment by robimarko** [comment]
Have you tested this and looked at config partition content?

**Comment by xssa** [comment]
Yes, it is tested by reverting back from lede/openwrt to OEM factory firmware both way many times without any issues. In OEM firmware flash dumps content is unencrypted xml config file.

**Comment by robimarko** [comment]
Awesome, great catch.

**Comment by mkresin** [comment]
@xssa sorry for being offtopic, but have you ever tried to use tftp recovery or doing an upgrade from the stock firmware using a factory image. Changing the code to

```
define Device/tl-wr840n-v5
  $(Device/tplink)
  DTS := TL-WR840NV5
  IMAGE_SIZE := 3840k
  DEVICE_TITLE := TP-Link TL-WR840N v5
  TPLINK_FLASHLAYOUT := 4Mmtk
  TPLINK_HWID := 0x08400005
  TPLINK_HWREV := 0x1
  TPLINK_HWREVADD := 0x5
  TPLINK_HVERSION := 3
endef
TARGET_DEVICES += tl-wr840n-v5
```

should build such images and would reduce some code duplication.

**Comment by xssa** [comment]
@mkresin Sorry, but i don't clearly got idea of your question. Sysupgrade image is the only image that is build by lede/openwrt for TP-Link TL-wr840n v5 and it can be used both for tftp recovery and also for ordinary OEM web ui update for EU (only!) devices. For other region localized OEM versions TPLINK_HWREV := 0x1 will not match thus tftp recovery is only usefull. There is some talks [here](https://forum.lede-project.org/t/support-for-tl-wr840n-es-ver-5-0-eu/6281/144?u=xssa) about localized images. This is a subject for another PR.

**Comment by mkresin** [comment]
> Sysupgrade image is the only image that is build by lede/openwrt for TP-Link TL-wr840n v5 and it can be used both for tftp recovery and also for ordinary OEM web ui update for EU (only!) devices.

Okay, I wasn't aware that the sysupgrade image can be used for everything.

The rational behind my question is that all other tplink boards in target/linux/ramips/image/mt76x8.mk require a special factory.bin and a special made tftp-recovery.bin. I was the opinion that a flash from OEM web ui or flash via tftp wasn't support for the tl-wr840n-v5.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
