### PR TITLE
kernel: bump 6.6 to 6.6.23

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.23

Removed upstreamed:
```
  pending-6.6/735-net-mediatek-mtk_eth_soc-release-MAC_MCR_FORCE_LINK-.patch[1]
  pending-6.6/736-net-ethernet-mtk_eth_soc-fix-PPE-hanging-issue.patch[2]
  mediatek/patches-6.6/232-clk-mediatek-mt7981-topckgen-flag-SGM_REG_SEL-as-cri.patch[3]
```
Manually rebased:
```
  mediatek/patches-6.6/100-dts-update-mt7622-rfb1.patch
```

Added:
```
  generic/backports-6.6/981-mtd-spinand-Add-support-for-5-byte-IDs.patch[4]
```
All other patches automatically rebased.

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.6.23&id=1f32abb474c1c9bdb21d9eda74c325a0b3a162e5
2. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.6.23&id=943c14ece95eb1cf98d477462aebcbfdfd714633
3. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.6.23&id=6ff01b314149d1cf59caebc29384f0beed21cba4
4. See comments in https://github.com/openwrt/openwrt/pull/14992 regarding broken flogic/xiaomi_redmi-router-ax6000-ubootmod

Build system: x86/64
Build-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, flogic/glinet_gl-mt6000
Run-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, flogic/glinet_gl-mt6000

### CODE REVIEW

**Comment by graysky2** [comment]
I built this and installed `openwrt-mediatek-filogic-xiaomi_redmi-router-ax6000-ubootmod-squashfs-sysupgrade.itb` on my Redmi AX6000 but found that I bricked it.  No LEDs or indication that the system is booting at all.

**Comment by vincejv** [comment]
compiles and boots fine on x86

**Comment by DragonBluep** [comment]
[[PATCH 1/2] mtd: spinand: Add support for 5-byte IDs](https://lore.kernel.org/linux-mtd/20240125200108.24374-2-ezra@easyb.ch/) is missing.

**Comment by graysky2** [comment]
Thanks @DragonBluep - I won't have a chance to test this, but I added the patch you called out.  Is the location I chose correct?

**Comment by DragonBluep** [comment]
Hi! Moving it to backport would be better. If you have time please report this issue upstream.

**Comment by graysky2** [comment]
Verified good boot on ` flogic/xiaomi_redmi-router-ax6000-ubootmod`

**Comment by graysky2** [comment]
Any insights into the build failure?  Seems to be a missing built file.

**Comment by dangowrt** [comment]
> <3>[    0.885607] spi-nand spi0.0: unknown raw ID c8017f7f

I see a missing SPI-NAND identification which leads to missing rootfs. Will investigate now.

**Comment by dangowrt** [comment]
> Any insights into the build failure? Seems to be a missing built file.

Missing symbol should be added to `target/linux/generic/config-6.6`:
```
# CONFIG_SSIF_IPMI_BMC is not set
```

**Comment by graysky2** [comment]
> Edit: I understand this has been resolved already by adding back patch [mtd: spinand: Add support for 5-byte IDs](https://lore.kernel.org/linux-mtd/20240125200108.24374-2-ezra@easyb.ch/), right?

@dangowrt - Yes, acknowledgment to @DragonBluep for calling it out.  Once added, my `flogic/xiaomi_redmi-router-ax6000-ubootmod` boots and runs fine.

**Comment by hauke** [comment]
I send a mail to stable@vger.kernel.org, the missing patch will probably get backported to 6.6.24. Thanks detecting and fixing the issue.

**Comment by hauke** [comment]
The bcm53xx_generic build is still failing:
````
  HDRINST usr/include/asm/unistd-eabi.h
  INSTALL /__w/openwrt/openwrt/openwrt/build_dir/target-arm-openwrt-linux-muslgnueabi_musl/linux-bcm53xx_generic/linux-6.6.23/user_headers/include
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-arm-openwrt-linux-muslgnueabi_musl/linux-bcm53xx_generic/linux-6.6.23'
arm-openwrt-linux-muslgnueabi-ld.bin: error: unplaced orphan section `.init.text' from `arch/arm/boot/compressed/cache-v7-min.o'
make[7]: *** [arch/arm/boot/compressed/Makefile:164: arch/arm/boot/compressed/vmlinux] Error 1
make[6]: *** [arch/arm/boot/Makefile:58: arch/arm/boot/compressed/vmlinux] Error 2
````
@rmilecki Do you have an idea?

**Comment by hauke** [comment]
> The bcm53xx_generic build is still failing:
> 
> ```
>   HDRINST usr/include/asm/unistd-eabi.h
>   INSTALL /__w/openwrt/openwrt/openwrt/build_dir/target-arm-openwrt-linux-muslgnueabi_musl/linux-bcm53xx_generic/linux-6.6.23/user_headers/include
> make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-arm-openwrt-linux-muslgnueabi_musl/linux-bcm53xx_generic/linux-6.6.23'
> arm-openwrt-linux-muslgnueabi-ld.bin: error: unplaced orphan section `.init.text' from `arch/arm/boot/compressed/cache-v7-min.o'
> make[7]: *** [arch/arm/boot/compressed/Makefile:164: arch/arm/boot/compressed/vmlinux] Error 1
> make[6]: *** [arch/arm/boot/Makefile:58: arch/arm/boot/compressed/vmlinux] Error 2
> ```
> 
> @rmilecki Do you have an idea?

I see the same problem also in other PRs. This is a problem in main branch and not this PR.

**Comment by robimarko** [comment]
@hauke OK, so CI is failing because we enable `Werror` on it if I am not mistaken so the warning turns into an error.
Still scratching my head on the root cause though

**Pull request merged**
