### PR TITLE
Preinit x86 improvements

### PR DESCRIPTION
**Pull request by pprindeville**
We're using the Supermicro 5018D-FN8T and -FN4T with great success, and for a
$900 bundle it's hard to beat the performance of the Xeon D-15xx SoC's. So let's
upstream our changes so others may use them.

### CODE REVIEW

**Comment by pprindeville** [comment]
@jow- @hauke @stintel Any other questions/suggestions about this PR or are we good to merge?

**Comment by pprindeville** [comment]
Per @jow-'s catch, we need to test for a non-empty pair of vendor/product AFTER checking for the broken Supermicro strings...

**Comment by jow-** [comment]
Picked with minor changes (added `x86: ` prefix to subject) to my staging tree at https://git.openwrt.org/openwrt/staging/jow.git

**Comment by pprindeville** [comment]
Thanks!

**Pull request closed without merging**
