### PR TITLE
ath11k-firmware: update to stable WLAN.HK.2.9.0.1-01837-QCAHKSWPL_SILICONZ-1

### PR DESCRIPTION
**Pull request by kwiateusz**
Tested on Xiaomi AX3600 and it works well. It’s good to check on other devices because it’s supposedly a stable version so it should work well on any.

cc @robimarko

### CODE REVIEW

**Comment by dick902** [comment]
Test with xiaomi AX9000. xiaomi AX3600, and Dynalink DL-WRX36
All work without issue for now!
BTW, xiaomi AX9000 DO NOT need the patched board-2.bin anymore for the PCI wifi card with this firmware.

**Comment by dchard** [comment]
@robimarko I tested this on AX6. It does work correctly (of course a couple days of testing is a good idea based on what we have seen before). They definitely improved something as even with the previous minor version my phone never reached more than 600Mbits DL with Speedtest and now it maxes out at 930Mbits (line rate of my GPON). Never seen a result like this before on this phone.

**Review by ghost — COMMENTED** [review]
Tested on Xiaomi AX3600. All working ok. Better memory consumption and stability I would say

**Comment by kwiateusz** [comment]
When I posted that pr and package was downloaded from github everything works fine. Even in pr for 23.05 it's ok.

@Ansuel any clue what goes wrong?

**Comment by Ansuel** [comment]
What I'm missing is if the hash is correct or not from generating it on a local system

**Comment by hnyman** [comment]
hash is ok, when downloaded locally from git.
Apparently hash is right, but CDN has a failed copy of it ???

```
Download failed.
No more mirrors to try - giving up.
make[2]: Leaving directory '/Openwrt/DL-WRX36/package/firmware/ath11k-firmware'
time: package/firmware/ath11k-firmware/download#228.07#7.99#263.40
make[1]: Leaving directory '/Openwrt/DL-WRX36'

perus@ub2304:/Openwrt/DL-WRX36$ sha256sum dl/ath11k-firmware-2023-07-06-69f6b734.tar.xz 
0f0203f755cb6713f6a1f41397dcd0f1a24e5cdbe75258af961343b927ebb3e9  dl/ath11k-firmware-023-07-06-69f6b734.tar.xz
```

Note that the git download takes really long, as it apparently first downloads the whole 360 MB of firmware binaries, and only then xz's it. tmp/ in the middle of the xz process

```
perus@ub2304:/Openwrt/DL-WRX36/tmp$ ls -l dl
total 383596
-rw-r--r-- 1 perus perus 360546130 Jul 18 15:56 ath11k-firmware-2023-07-06-69f6b734.tar.gz.dl
-rw-r--r-- 1 perus perus  32243712 Jul 18 15:59 ath11k-firmware-2023-07-06-69f6b734.tar.xz
drwxr-xr-x 3 perus perus      4096 Jul 18 15:57 ath11k-firmware-2023-07-06-69f6b734.untar
-rwxr-xr-x 1 perus perus       104 Jul 18 15:13 github.commit.ts.cache
```

But it is somewhat confusing, as first the download from mirrors fails with "giving up" and it seems to freeze, as the download script has no indication that a git download is tried next, but it is progressing in the background, and then it finally suddenly succeeds...

The silent xz step took over 4 minutes, as the downloaded ath11-firmware binary repo is so huge.

**Comment by Quentin-M** [comment]
Unfortunately, while AP @ 160MHz Ch36 works, 802.11s @ 160MHz Ch36 still does not work on the AX9000. Nothing going on in the logs, no DFS going on either.

**Comment by kwiateusz** [comment]
It's a regression or on previous fw it doesn't work either?

**Comment by Quentin-M** [comment]
I should've been clearer - it did not work previously either. I am not sure where to start troubleshooting, as there's nothing in the logs (besides radio/interface/mesh up messages), nothing from hostapd (not a line - so no mention of HT_SCAN either). `iw dev` shows the wrong channel.

```
$ iw dev
phy#3
        Interface phy3-mesh0
                ifindex 36
                wdev 0x300000006
                addr c8:bf:4c:bb:ec:b0
                type mesh point
                channel 149 (5745 MHz), width: 160 MHz, center1: 5815 MHz
                txpower 30.00 dBm
                multicast TXQ:
                        qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                        0       0       19      0       0       0       0       1648            19
```

**Pull request merged**
