### PR TITLE
[WIP] binutils: update to 2.35.2

### PR DESCRIPTION
**Pull request by rockdrilla**
Refreshed patches, no changes are made (merely rename directory).

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by anomeome** [comment]
Submitted yesterday to [patchwork](https://patchwork.ozlabs.org/project/openwrt/list/?series=240722)

**Comment by hauke** [comment]
The patches from the mailing list were applied.

**Comment by rockdrilla** [comment]
@hauke, regular package is still `2.35.1`. May I ask you to cherry-pick that commit too?

**Comment by hauke** [comment]
ok, sorry I missed that could you please rebase your pull request.

**Comment by aparcar** [comment]
The toolchain uses 3.36.1 right? Should we update straight to that?

**Comment by rockdrilla** [comment]
@aparcar, no, toolchain is using 2.34 by default.

**Comment by rockdrilla** [comment]
@hauke done.

**Comment by hauke** [comment]
Thank you for the patch, I applied the remaining patch to master.

**Pull request closed without merging**
