### PR TITLE
[19.07] kernel: bump 4.14 to 4.14.327

### PR DESCRIPTION
**Pull request by T-X**
The following four new config symbols were added due to the update and were set to their default values:

* CONFIG_GDS_FORCE_MITIGATION=n
* CONFIG_INET_TABLE_PERTURB_ORDER=16
* CONFIG_RANDOM_TRUST_CPU=y
* CONFIG_RANDOM_TRUST_BOOTLOADER=y

The following patches were initially rejected and needed manual, but small and straightforward adjustments:

* .../generic/.../289-v4.16-netfilter-add-defines-for-arp-decnet-max-hooks.patch
* .../generic/.../303-v4.16-netfilter-nf_tables-remove-multihook-chains-and-fami.patch
* .../generic/.../344-v4.16-netfilter-nf_tables-allocate-handle-and-delete-objec.patch
* .../ath79/.../403-mtd_fix_cfi_cmdset_0002_status_check.patch
* .../ar71xx/.../403-mtd_fix_cfi_cmdset_0002_status_check.patch
* .../ar71xx/.../930-chipidea-pullup.patch
* .../oxnas/.../100-oxnas-clk-plla-pllb.patch
* .../lantiq/.../0028-NET-lantiq-various-etop-fixes.patch
* .../layerscape/.../202-core-linux-support-layerscape.patch
* .../layerscape/.../707-dpaa-ethernet-support-layerscape.patch
* .../layerscape/.../807-usb-support-layerscape.patch

All other patches were updated automatically via
"make target/linux/refresh".

Runtime tested on an x86 VM and ath79 UniFi AP. All other targets were build tested only.

### CODE REVIEW

**Comment by robimarko** [comment]
19.07 branch is EOL, so its not supported in any way.

**Comment by T-X** [comment]
I know, I don't expect another 19.07 release tag. But I thought it might be useful for some people who nevertheless need to work with 19.07 for a little while longer for devices with small RAM/flash.

For Freifunk with Gluon we have some NSM2 XM devices  for instance which are actively meshing, which we can't replace that easily / quickly / cheaply right now, nor update to a newer OpenWrt release.

**Comment by robimarko** [comment]
I dont have anything against, its up to the maintainers

**Comment by T-X** [comment]
Thanks for the feedback!

@ynezz For the Gluon project we only use and supported a limited number of userspace packages. To keep things small and easy to use. While giving up flexibility/configurablity (for instance there is no LuCI support). So keeping these up-to-date downstream seems doable for us. For Gluon, it's the kernel part that kind of worries me more, actually. There it would be helpful to have it in OpenWrt, to get a slightly more wide-spread usage+testing coverage. And maybe even get a bit of help/feedback from other, experienced devs (if available).

@kofec thanks, that looks interesting. And like quite some work and effort. What makes me a bit hesitant, though: It seems to update more than just the kernel, contains more changes? So I'm wondering I'm unsure if it could be used as an OpenWrt 19.07 drop-in replacement for Gluon's legacy branches. Also, with no offense ment, haven't heard of that user who is working on this before. So I'm again unsure if I would want to switch to that from a trust point-of-view? (but yeah, could/might check what exactly s/he has modified in the OpenWrt kernel part and compare it with my changes)

Btw. 4.14 now officially became end-of-life, no more releases/updates after 4.14.336: https://lore.kernel.org/r/2024011046-ecology-tiptoeing-ce50@gregkh/. So, yeah, that is definitely an official dead-end now. Just wondering / unsure if we should then bump the Linux kernel downstream in our Gluon legacy / End-of-Life branches. As realistically, these devices that are unable to update to a newer OpenWrt will still be around for a little longer.

**Pull request closed without merging**
