### PR TITLE
kernel: bump 5.4 to 5.4.66

### PR DESCRIPTION
**Pull request by graysky2**
All modifications made by update_kernel.sh/no manual intervention needed

Build-tested: x86_64
Run-tested: ipq806x (R7800), ath79 (Archer C7v5)

No dmesg regressions, everything appears functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by curtdept** [comment]
Build tested: Curtis Deptuck <curtdept@me.com> (x86/64)

Will run test when possible.

**Comment by graysky2** [comment]
Anyone else w/ another arch care to weigh in?

**Comment by adschm** [comment]
For a bump like this with no manual interference I'd say it generally would be enough to run-test one and build on two to three targets. Since you have build-tested x86/64 and ipq806x, maybe just add another target (e.g. a mips one or other different architecture) to your build-test routine and we can speed this up a lot. (And it case there are patches to merge manually, one could add a build-test for the affected target instead ...)

Btw which config do you use for build-testing?

**Comment by graysky2** [comment]
@adschm - I have a config customized to my use case, see below.  I will build for mips and report back, was thinking it needed to be run tested as well.

```
% ./scripts/diffconfig.sh        
CONFIG_TARGET_ipq806x=y
CONFIG_TARGET_ipq806x_generic=y
CONFIG_TARGET_ipq806x_generic_DEVICE_netgear_r7800=y
CONFIG_ATH10K_LEDS=y
# CONFIG_DROPBEAR_ED25519 is not set
# CONFIG_KERNEL_BLK_DEV_THROTTLING is not set
# CONFIG_KERNEL_CFS_BANDWIDTH is not set
CONFIG_PACKAGE_ath10k-firmware-qca9984=y
CONFIG_PACKAGE_ath10k-firmware-qca9984-ct=m
CONFIG_PACKAGE_block-mount=y
# CONFIG_PACKAGE_ca-bundle is not set
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
CONFIG_PACKAGE_iptables-mod-ipopt=y
CONFIG_PACKAGE_irqbalance=y
CONFIG_PACKAGE_kmod-ath10k=y
CONFIG_PACKAGE_kmod-ath10k-ct=m
CONFIG_PACKAGE_kmod-crypto-crc32=y
CONFIG_PACKAGE_kmod-crypto-hash=y
CONFIG_PACKAGE_kmod-fs-f2fs=y
CONFIG_PACKAGE_kmod-ifb=y
CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
CONFIG_PACKAGE_kmod-ipt-ipopt=y
CONFIG_PACKAGE_kmod-ipt-raw=y
CONFIG_PACKAGE_kmod-ledtrig-default-on=y
CONFIG_PACKAGE_kmod-ledtrig-heartbeat=y
CONFIG_PACKAGE_kmod-ledtrig-netdev=y
CONFIG_PACKAGE_kmod-ledtrig-timer=y
CONFIG_PACKAGE_kmod-sched-cake=y
CONFIG_PACKAGE_kmod-sched-core=y
CONFIG_PACKAGE_kmod-usb-storage=y
CONFIG_PACKAGE_libelf=y
CONFIG_PACKAGE_libf2fs=y
CONFIG_PACKAGE_libiwinfo-lua=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libpopt=y
CONFIG_PACKAGE_librt=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libuuid=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-app-sqm=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_netperf=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-rrdns=y
CONFIG_PACKAGE_rsync=y
CONFIG_PACKAGE_rsyncd=y
CONFIG_PACKAGE_sqm-scripts=y
CONFIG_PACKAGE_tc=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_PACKAGE_zlib=y
CONFIG_RSYNC_zlib=y
CONFIG_PACKAGE_kmod-hwmon-core=y
```

**Comment by adschm** [comment]
Run-test is always better, testing with buildbot config is always better.

However, it's not practical do run-tests on several targets for each minor bump. After all, it depends on what has changed ...
Whether you will find a regression is luck or bad luck anyway.

To get an idea, you may just go through the commit messages of the kernel bump history:
https://github.com/openwrt/openwrt/commits/master/include/kernel-version.mk

**Comment by graysky2** [comment]
Where can I get the buildbot config?

**Comment by adschm** [comment]
> Where can I get the buildbot config?

CONFIG_BUILDBOT=y
or select accordingly in the Global Build Settings (after you've chosen the correct target/subtarget).
I typically de-select imagebuilder and sdk manually afterwards to save a little build time.

To do it properly, you would also update and install all packages from feeds (beforehand):
```
./scripts/feeds update
./scripts/feeds install -a
```

**Comment by adschm** [comment]
Or you may just look at what's in config.buildinfo for the downloads, e.g. at the bottom of
https://downloads.openwrt.org/snapshots/targets/ath79/generic/

**Comment by graysky2** [comment]
Updated commit for ath79 build

**Comment by adschm** [comment]
Thanks, merged.

BTW: For targets with subtargets, you should mention the subtarget, like ath79/generic. Though the kernel patches are same for all subtargets, config is different, and it also helps with debugging if something goes wrong.

**Pull request closed without merging**
