### PR TITLE
ar71xx: Add support for W25Q128JVSIM Flash

### PR DESCRIPTION
**Pull request by krux2222**
Add support for Winbond W25Q128JVSIM Flash

### CODE REVIEW

**Comment by krux2222** [comment]
first pull request- sorry for wrong subject, should be: 
ar71xx: Add support for Winbond W25Q128JVSIM Flash

**Comment by tapper82** [comment]
Hi sorry I am not able to review this, but thanks for your time and efert. I am not a dev just a nozy user. It's always good to se a new face around here! :-)

**Comment by mkresin** [comment]
AS John said, please send the patch to the linux-mtd maintainer to get it included in the linux kernel. If it was accepted it can be backported to OpenWrt.

Have a look at the "[linux-mtd patch submission guide](http://www.linux-mtd.infradead.org/source.html)" and https://kernelnewbies.org/FirstKernelPatch.

**Comment by robimarko** [comment]
I hit the same issue with wAP R.
Pushed my patch upstream.
https://patchwork.ozlabs.org/patch/934181/

This PR is not really correct as not all features that IC has have been listed and name was wrong.
JVSIM is just he code for SOIC package.

JV is the actual series.
Will open a PR after the patch is merged

**Comment by robimarko** [comment]
Awesome, hopefully it will be merged soon so I can submit backports to 4.9 and 4.14

**Comment by TobleMiner** [comment]
There seem to be Versions of the rbm33g with this flash chip, too. Nice job sending patch upstream.

**Comment by robimarko** [comment]
It will take a while until someone upstreams takes a look at it.

It looks like all Mikrotik product made recently use the JV revision

**Comment by robimarko** [comment]
No, I said that the board it was tested on does not support dual or quad
spi.
Flash does,and datasheet confirms that

**Comment by TobleMiner** [comment]
@robimarko Ah, ok. Just sounded a little confusing reading it for the first time. So you are actually referring to the board there. Thanks for clearing that up.

**Comment by mkresin** [comment]
Closing the PR awaiting a new one from @robimarko as soon as his patch is merged. As outlined, the PR doesn't add all supported flags and I'm in favour of merging something accepted upstream.

**Comment by wigyori** [comment]
A similar patch landed in 4.18 for W25Q32JV, which also states that support for dual or quad SPI wasn't tested. @robimarko , has your patch been sent to mainline?

https://github.com/torvalds/linux/commit/7fccf56ea4faef3f1e704acc18b8576b2eb9989d

**Comment by robimarko** [comment]
I sent the patch on June 25th, there has been no activity on it nor was it picked for 4.19

**Pull request closed without merging**
