### PR TITLE
ramips: mt76x8: fix ephy led always blinking

### PR DESCRIPTION
**Pull request by mans0n**
Many MT7628 devices are using software control for their Ethernet LEDs,
but there have been reports of devices using hardware control that when
the Ethernet port is connected, the corresponding LED starts blinking
even if there is no traffic. By comparing the esw driver with the
ethernet driver from MTK SDK, it was found that disabling EEE fixes the
issue. Add a device tree property "mediatek,eee-disable" to apply the
fix only to selected boards.

Reported-at: https://github.com/openwrt/openwrt/pull/911
Reported-at: https://github.com/openwrt/openwrt/pull/5044

### CODE REVIEW

**Comment by mans0n** [comment]
I chose to not use `eee-broken-100tx` here as the property was meant for ethernet phy, not ethernet switch, and AFAIU the kernel uses it to prohibit EEE mode advertisement, not to disable EEE mode in physical device. So I added another custom property in the driver.

**Comment by mans0n** [comment]
Cc: @ysc3839 @mkresin

**Comment by mkresin** [comment]
> ... as the property was meant for ethernet phy, not ethernet switch,

As a note: Looking at your changes, it looks like EEE is disabled for all switch embedded phys. The difference here is, that the individual switch ports/phys are not exposed via device tree as they would by using DSA.

Disabling EEE because the led blinking is going mad, doesn't look like the correct solution. Different story if there would be interop issues like regular link loss or negotiation of a wrong link speed.

Can the issue mitigated by handling the blinking in software/user space?

**Comment by mans0n** [comment]
> Disabling EEE because the led blinking is going mad, doesn't look like the correct solution. Different story if there would be interop issues like regular link loss or negotiation of a wrong link speed.

Looking at the MTK driver, it seems it also needs a separate snippet to enable EEE, which is not in our esw driver.
https://gist.github.com/ysc3839/d88242927c48f792fe2ac6dd8f1023a4#file-raether-c-L4000
FWIW, I've tried importing the EEE-enable snippet into the esw driver, but it did not solved the blinking issue.
I don't know how to check whether EEE feature is working correctly or not, I would happily test it if I could.

> Can the issue mitigated by handling the blinking in software/user space?

Sure, it can be mitigated by using software trigger. But that's what I want to avoid if possible.

**Comment by mkresin** [comment]
I got lost.

In your commit message you say "disabling EEE fixes the issue". In your last comment "needs a separate snippet to enable EEE".

What is the deal here?

Disabling something in the driver - for all boards - to only fix a LED blinking issue of some(?) boards, which can be mitigated by switching to software controlled led, isn't a proper way to address the issue.

**Comment by AuthorReflex** [comment]
Tested on Asus RT-AC1200. It's working better than PR https://github.com/openwrt/openwrt/pull/5044

**Comment by mans0n** [comment]
My point is that the current driver might not even enable EEE anyway.
I think we don't really understand what the MTK driver actually does, it says "EEE setting"/"disable EEE" but I failed to find a documentation on those switch registers accessible through `rt305x_mii_write()`. It might be possible that either or both are doing just LED setup for EEE mode or something (and the actual EEE mode setup is done elsewhere).

> Disabling something in the driver - for all boards - to only fix a LED blinking issue of some(?) boards, which can be mitigated by switching to software controlled led, isn't a proper way to address the issue.

You may be right. What do you think of #5044, which mitigates the issue by setting alternative LED mode?

> Tested on Asus RT-AC1200. It's working better than PR #5044

Thanks for the test! Can I get your Tested-by?

**Comment by mans0n** [comment]
FYR this is the code I used to test EEE enable.

<details>

```diff
--- a/target/linux/ramips/files/drivers/net/ethernet/ralink/esw_rt3050.c
+++ b/target/linux/ramips/files/drivers/net/ethernet/ralink/esw_rt3050.c
@@ -86,9 +86,12 @@
 #define RT305X_ESW_SPD_S		0
 
 #define RT305X_ESW_PCR0_WT_NWAY_DATA_S	16
+#define RT305X_ESW_PCR0_RD_PHY_CMD	BIT(14)
 #define RT305X_ESW_PCR0_WT_PHY_CMD	BIT(13)
 #define RT305X_ESW_PCR0_CPU_PHY_REG_S	8
 
+#define RT305X_ESW_PCR1_RD_DATA_S	16
+#define RT305X_ESW_PCR1_RD_RDY		BIT(1)
 #define RT305X_ESW_PCR1_WT_DONE		BIT(0)
 
 #define RT305X_ESW_ATS_TIMEOUT		(5 * HZ)
@@ -292,6 +295,47 @@ static void esw_rmw(struct rt305x_esw *esw, unsigned reg,
 	spin_unlock_irqrestore(&esw->reg_rw_lock, flags);
 }
 
+static u32 rt305x_mii_read(struct rt305x_esw *esw, u32 phy_addr,
+			   u32 phy_register, u32 *read_data)
+{
+	unsigned long t_start = jiffies;
+	int ret = 0;
+	u32 status = 0;
+
+	*read_data = 0xffff;
+	while (1) {
+		if (!(esw_r32(esw, RT305X_ESW_REG_PCR1) &
+		      RT305X_ESW_PCR1_RD_RDY))
+			break;
+		if (time_after(jiffies, t_start + RT305X_ESW_PHY_TIMEOUT)) {
+			ret = 1;
+			goto out;
+		}
+	}
+
+	esw_w32(esw, (phy_register << RT305X_ESW_PCR0_CPU_PHY_REG_S) |
+		     (phy_addr) | RT305X_ESW_PCR0_RD_PHY_CMD,
+		RT305X_ESW_REG_PCR0);
+
+	t_start = jiffies;
+	while (1) {
+		if (esw_r32(esw, RT305X_ESW_REG_PCR1) &
+			    RT305X_ESW_PCR1_RD_RDY)
+			break;
+		if (time_after(jiffies, t_start + RT305X_ESW_PHY_TIMEOUT)) {
+			ret = 1;
+			goto out;
+		}
+	}
+
+	status = esw_r32(esw, RT305X_ESW_REG_PCR1);
+	*read_data = (status >> RT305X_ESW_PCR1_RD_DATA_S) & 0xffff;
+out:
+	if (ret)
+		dev_err(esw->dev, "ramips_eth: MDIO timeout\n");
+	return ret;
+}
+
 static u32 rt305x_mii_write(struct rt305x_esw *esw, u32 phy_addr,
 			    u32 phy_register, u32 write_data)
 {
@@ -654,6 +698,22 @@ static void esw_hw_init(struct rt305x_esw *esw)
 		for (i = 0; i < 5; i++) {
 			rt305x_mii_write(esw, i, 31, 0x8000);
 			rt305x_mii_write(esw, i,  0, 0x3100);
+
+			/* disable EEE */
+			if (of_property_read_bool(esw->swdev->of_node, "eee-broken-100tx")) {
+				rt305x_mii_write(esw, i, 13, 0x7);
+				rt305x_mii_write(esw, i, 14, 0x3c);
+				rt305x_mii_write(esw, i, 13, 0x4007);
+				rt305x_mii_write(esw, i, 14, 0x0);
+			}
+			else {
+				/* EEE setting */
+				u32 phy_val;
+				rt305x_mii_read(esw, i, 26, &phy_val);
+				phy_val |= (1 << 5);
+				rt305x_mii_write(esw, i, 26, phy_val);
+			}
+
 			rt305x_mii_write(esw, i, 30, 0xa000);
 			rt305x_mii_write(esw, i, 31, 0xa000);
 			rt305x_mii_write(esw, i, 16, 0x0606);
```

</details>

**Comment by w43322** [comment]
In the case of Asus RT-AC1200, I don't think the issue could be resolved by switching to swconfig. It shows no TX/RX activity. 
This is also mentioned in PR #5044 , where the author is working on a similar device - Asus RT-AC1200 v2.

**Comment by w43322** [comment]
Tested this PR and the LEDs do work as intended. Frequency of blinking is better than the other solution #5044 (the other solution yielded ~2Hz).

**Comment by AuthorReflex** [comment]
> > Tested on Asus RT-AC1200. It's working better than PR #5044
> 
> Thanks for the test! Can I get your Tested-by?
Yes

**Comment by AuthorReflex** [comment]
Since #5028 is merged in master, changes need to be taken also in their dts (mt7628an_asus_rt-ac1200.dts).

**Comment by mans0n** [comment]
Thanks for the notice.

I should investigate the EEE feature to go forward but I'm running out of time...

**Comment by mans0n** [comment]
I got to know that ethtool can check EEE status. So I did some tests:

```
# ethtool on OpenWrt
root@OpenWrt:/# ethtool --show-eee eth0
Cannot get EEE settings: Not supported
# ethtool-full on OpenWrt
root@OpenWrt:/# ethtool --show-eee eth0
netlink error: Not supported

# ethtool on host connected to mt7628, EEE not disabled in esw driver
$ ethtool --show-eee eth1
EEE settings for eth1:
        EEE status: enabled - active
        Tx LPI: disabled
        Supported EEE link modes:  100baseT/Full
                                   1000baseT/Full
        Advertised EEE link modes:  Not reported
        Link partner advertised EEE link modes:  100baseT/Full

# ethtool on host connected to mt7628, EEE disabled in esw driver
$ ethtool --show-eee eth1
EEE settings for eth1:
        EEE status: enabled - inactive
        Tx LPI: disabled
        Supported EEE link modes:  100baseT/Full
                                   1000baseT/Full
        Advertised EEE link modes:  Not reported
        Link partner advertised EEE link modes:  Not reported
```

So it seems `eee_disable` code does disable EEE.
I'll try to find a way to not disable EEE but still fix the LED issue.
If I fail to find a nice alternative, I'll close this PR. (then we might turn to #5044 or SW trigger)

**Comment by mans0n** [comment]
Nope, I feel this is the dead end. :( Let me know if you find any breakthrough.

**Pull request closed without merging**
