### PR TITLE
kirkwood: use three temperature sensors instead of one

### PR DESCRIPTION
**Pull request by ThBexx**
temp1 -> main board temp1
temp2 -> main board temp2
temp3 -> processor temperature
All three temperatures give valid input for the PWM of the fan on NSA310. 
Change tested on two NSA310
Signed-off-by: ThBexx <thomas.beckler@hotmail.com>

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
looks OK. 

As I wrote in the comment in the script, I did not see the other temperatures changing, so I put only Temp 1 in it. Did you notice the other two changing?

Either way it's better to have all three temps monitored.

**Comment by ThBexx** [comment]
yes i noticed the other two temperatures changing. Thank you for the fast comment

**Comment by mans0n** [comment]
Okay, now that the contents of the patch got confirmed, it's time to address the formal aspects.

> this is my first pull request:

Please remove this from the commit message, and add a Signed-off-by line.

Those temperature numbers still seem quite arbitrary to me. Please add some comments explaining about the numbers as @bobafetthotmail did.

**Comment by ThBexx** [comment]
@mans0n modifications done as requested

**Comment by bobafetthotmail** [comment]
you closed this PR?

**Comment by ThBexx** [comment]
I closed it by accident...

**Comment by adrianschmutzler** [comment]
Your commit has formal issues (missing Signed-off, no real description what you do and why it's required/needed).

Despite, please squash all your changes into a single commit.

After that, some Tested-by by other people or reviews would increase your chances of this being merged.

**Comment by ThBexx** [comment]
Merged into one commit. Added signed-off.

**Comment by adrianschmutzler** [comment]
Now the commit title is missing.

**Comment by ThBexx** [comment]
Thank you for your patience. Updated the commit message with a titel.

In a private message of the OpenWRT forum I was in contact with _eerozeteen_. He did a test of the script:

_I saw that when i do "sensors" one by one, PWM flow from 1k to 3,4k. Looks like very unstable:_

```
root@nsa310:~# sensors
lm85-i2c-0-2e
Adapter: mv64xxx_i2c adapter
[..]
fan1:        1130 RPM  (min =    0 RPM)
[..]
temp1:        +28.0°C  (low  = -127.0°C, high = +127.0°C)
temp2:        +34.0°C  (low  = -127.0°C, high = +127.0°C)
temp3:        +34.0°C  (low  = -127.0°C, high = +127.0°C)
sensors
lm85-i2c-0-2e
Adapter: mv64xxx_i2c adapter
[..]
fan1:        3385 RPM  (min =    0 RPM)
[..]
temp1:        +28.0°C  (low  = -127.0°C, high = +127.0°C)
temp2:        +34.0°C  (low  = -127.0°C, high = +127.0°C)
temp3:        +34.0°C  (low  = -127.0°C, high = +127.0°C)
```
_I'm looking for way to use fan when temp goes above 46*C and off in below. Of course I can test for you any other options with fan.

Regards
eerozeteen_

@bobafetthotmail: Regarding eerozeteen last statement, I would like to get your opinion on increasing the min. temperature for the cooling fan. I would not increase the default temperatures. 
Running a HDD with up to 50°C is a safe way (not reducing the life time significantly). With a higher default temperature inside the NAS I think the 50°C inside the HDD are exceeded.

**Comment by adrianschmutzler** [comment]
Now the commit title is too long, maybe use "kirkwood: use three temperature sensors instead of one"

Despite, note that somebody else will have to review the content.

**Comment by bobafetthotmail** [comment]
> @bobafetthotmail: Regarding eerozeteen last statement, I would like to get your opinion on increasing the min. temperature for the cooling fan. I would not increase the default temperatures.
> Running a HDD with up to 50°C is a safe way (not reducing the life time significantly). With a higher default temperature inside the NAS I think the 50°C inside the HDD are exceeded.

In my experience, temp read by these sensors is not close to drive temperature. They will be 10-15 degrees off or more, so what he is doing is not secure imho.

The drive temp was (is) more or less stable and safe in my testing and with my drives but YMMV as temperatures of air and type of drive make a big difference. I had some drives that were HOT and even NSA325 fan could not keep them cool enough if actively writing, and I retired them because of that. Too hot for the performance, I can accept that from SAS drives that have 10k or 15k RPM, not from Sata drives at 7.2k RPM.

But apart from some special cases temp will be ok as long as the fan is working at all. For NAS drives (WD Red and Seagate Ironwolf) this may not be needed as the drives have slower RPM and are cooler.

Only 100% safe and foolproof way to deal with drive temp and minimze fan use is to keep the fan control manual and run a script that makes an infinite loop and every 5 seconds or so it reads HDD temp and limits with
`sudo smartctl -A /dev/sda | grep Temperature`

This will answer with 
`194 Temperature_Celsius     0x0002   150   150   000    Old_age   Always       -       40 (Min/Max 13/68)`
that will tell you both current temp (last number, the "40") and the safe temp range (13 to 68 Celsius for the drive I used for this example) so you can parse that with Awk into variables for the script logic to decide if fan must be activated or not.

AFAIk there is a file in `/sys/devices/platform/ocp@f1000000/f1011000.i2c/i2c-0/0-002e/hwmon/hwmon0` that lets you write fan speed directly if you did not enable automatic fan control with 
`echo 123 > "$path_to_hwmon/pwm1_auto_channels" `

**Comment by mans0n** [comment]
FYI there's an in-kernel way to get drivetemp (and control fan automatically). 9f14216

**Comment by ThBexx** [comment]
thank you for the valuable input. Unfortunately I don't find the time to implement any of your suggestions (smartmontools for additional temperature input / use kernel to do fan control). 
@bobafetthotmail: Would you kindly review my modification, so the change can be either accepted or rejected?

**Comment by bobafetthotmail** [comment]
looks good to me, also run tested on my nsa310

You can add a 

**Reviewed-by: Alberto Bursi <bobafetthotmail@gmail.com>**

in the commit message

Since I'm just a contributor that added a few Kirkwood devices, we will still have to wait for a project member to merge this.

**Comment by adschm** [comment]
Please use your real name for Signed-off-by and make sure both commit message and code has max. 74 characters (i.e. put the comment into a separate line if needed at all)

**Comment by ThBexx** [comment]
Trying to do the requested changes I am totally messed up the local branches. With my limited knowledge of git i am not able to resolve it (tried in a reasonable time). So feel free to perform the requested changes or just close the thread...

**Comment by bobafetthotmail** [comment]
the branches on your github clone https://github.com/ThBexx/openwrt/tree/patch-1 seem to be ok, so just go in a clean folder and
git clone https://github.com/ThBexx/openwrt.git
git checkout patch-1

then install "nano" text editor (apt-get install nano, yum install nano, or whatever), this is actually usable by modern people, unlike Vi/Vim that is a meme

set it as default git text eitor with
git config --global core.editor nano

Then you should be able to edit the commit message with 
git commit --amend

and send the changes to github
git push -f

**Comment by adschm** [comment]
So, since this is reviewed and tested, but in unmergeable state, we have to go on somehow.

I think the quickest way will be if I wrap myself. But in any case I need a proper Signed-off-by

@ThBexx Maybe just post a proper SoB here?
@bobafetthotmail I assume you still agree with merging this, as I base my decision mainly on your review?

**Comment by bobafetthotmail** [comment]
Yes I agree with merging this. I tested it and it worked correctly.

Thanks for taking over this.

I would assume that his name is Thomas Beckler, as that's both in the Github profile and in the email, although I don't know about the legality of going through and just craft the signed-off by for him.

**Comment by ThBexx** [comment]
Thank you for taking over. I know this is a simple task but I am not so familiar with GitHub. So for me it is an invest of time, which I at the moment don't want to spend. Thank you for your support and keep openwrt improving/developing.

**Comment by adschm** [comment]
@ThBexx Still, I need a proper "valid" Signed-off-by line somewhere, at least just posted here as a comment.

**Comment by bobafetthotmail** [comment]
> Thank you for taking over. I know this is a simple task but I am not so familiar with GitHub. So for me it is an invest of time, which I at the moment don't want to spend. Thank you for your support and keep openwrt improving/developing.

Can you please at least post 
**Signed-off-by: <my name> thomas.beckler@hotmail.com**
with your true name as a message here? That's what Adrian asked with "Maybe just post a proper SoB here?" and it would be good enough for him at this point.

**Comment by ThBexx** [comment]
Signed-off-by: Thomas Beckler <thomas.beckler@hotmail.com>

**Comment by adschm** [comment]
Okay.

**Pull request closed without merging**
