### PR TITLE
mediatek, ramips: switch to Linux 6.6

### PR DESCRIPTION
**Pull request by dangowrt**
Maintaining support for both, Linux 6.1 and Linux 6.6 is an unneeded burden as we are not going to build a release based on Linux 6.1 anyway.
Now that reliability and performance on Linux 6.6 look good on both MediaTek (MIPS, ARM) targets, lets switch to Linux kernel version 6.6 and drop configs, files and patches intended for Linux 6.1.

Multiple users have confirmed that Linux 6.6 works fine and with long uptimes on MediaTek ARM-based devices:
https://github.com/openwrt/openwrt/pull/14772#issuecomment-2091184474

Issues with WAN port (phy-muxing) on MIPS-based MT7621 have recently been resolved as well:
https://github.com/openwrt/openwrt/issues/14942#issuecomment-2088700577

### CODE REVIEW

**Comment by musashino205** [comment]
Since the `blkdevparts` support in Linux Kernel is broken, the support for Unielec U7623-02 eMMC may be broken on Linux Kernel 6.6.
https://patchwork.kernel.org/project/linux-block/patch/20240421074005.565-1-musashino.open@gmail.com/

**Comment by AuthorReflex** [comment]
With  kernel 6.6 does not work autodetection speed on two-pairs cable: https://github.com/openwrt/openwrt/issues/15348

**Review by namiltd — APPROVED** [review]

**Comment by Spudz76** [comment]
Everything feels right on ramips/mt7621_linksys_ea7300-v1

Even the `ovpn_dco_v2` module works again (didn't for a while) which I was hoping might increase throughput and reduce CPU usage in combination with supported algorithms in `crypto_hw_eip93` but I haven't tested that yet.  Previously it would only build successfully on 6.1 for reasons I never investigated (could have been dirty tree from switching back and forth between 6.1/6.6).

**Review by PolynomialDivision — APPROVED** [review]

**Comment by Borromini** [comment]
Been working fine on WAX202 / EAP235-Wall v1 (with the PHY mux issue fixed now) / EAP615-Wall v1. So drop 6.1 I say :slightly_smiling_face:.

Thanks!

**Comment by Spudz76** [comment]
> Since the `blkdevparts` support in Linux Kernel 6.6~ is broken, the support for Unielec U7623-02 eMMC may be broken on Linux Kernel 6.6. https://patchwork.kernel.org/project/linux-block/patch/20240421074005.565-1-musashino.open@gmail.com/

Dropped that patch into my tree as `target/linux/generic/pending-6.6/195-block-fix-and-simplify-blkdevparts-cmdline-parsing.patch` and it built fine, although my platform doesn't use that feature (is nand) so I don't know if it fixes the problem beyond the patch and build success.

**Review by pesa1234 — APPROVED** [review]
mediatek/filogic MT6000 ok

**Comment by namiltd** [comment]
I added an additional fix to remove unnecessary if: https://github.com/dangowrt/openwrt/pull/3

**Comment by tbsky** [comment]
> Everything feels right on ramips/mt7621_linksys_ea7300-v1
> 
> Even the `ovpn_dco_v2` module works again (didn't for a while) which I was hoping might increase throughput and reduce CPU usage in combination with supported algorithms in `crypto_hw_eip93` but I haven't tested that yet. Previously it would only build successfully on 6.1 for reasons I never investigated (could have been dirty tree from switching back and forth between 6.1/6.6).

I have tried ovpn_dco_v2 at mt7621 under 23.05. I wonder if anyone really test it?  it seems never compiled correctly and it is not usable by openvpn.  https://github.com/openwrt/packages/issues/24050

**Comment by Spudz76** [comment]
For whatever reason it builds fine if you add kmod-wireguard even if you aren't going to use kmod-wireguard.  No idea why it's like that.  It does not build otherwise and it's a very odd problem.  Beyond building and loading the opvn_dco_v2 I have not checked if OpenVPN actually finds and uses it, or if it then works with the hardware crypto (I am using wolfssl).

**Comment by rx78gp01** [comment]
> 
> I have tried ovpn_dco_v2 at mt7621 under 23.05. I wonder if anyone really test it? it seems never compiled correctly and it is not usable by openvpn. [openwrt/packages#24050](https://github.com/openwrt/packages/issues/24050)

I have tried ovpn_dco_v2 in 23.05.3, it is usable.

```
 OpenWrt 23.05.3, r23809-234f1a2efa
 -----------------------------------------------------
root@OpenWrt:~# opkg list-installed | grep -i dco
kmod-ovpn-dco-v2 - 5.15.158+0.2.20240320-1

daemon.notice openvpn(sample_server)[2509]: OpenVPN 2.6.10 mipsel-openwrt-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] [DCO]
daemon.notice openvpn(sample_server)[2509]: library versions: OpenSSL 3.0.13 30 Jan 2024, LZO 2.10
daemon.notice openvpn(sample_server)[2509]: DCO version: N/A
daemon.notice openvpn(sample_server)[2509]: net_route_v4_best_gw query: dst 0.0.0.0
daemon.notice openvpn(sample_server)[2509]: net_route_v4_best_gw result: via 192.168.1.1 dev br-lan
daemon.notice openvpn(sample_server)[2509]: Diffie-Hellman initialized with 2048 bit key
daemon.notice openvpn(sample_server)[2509]: net_iface_new: add tun0 type ovpn-dco
daemon.notice openvpn(sample_server)[2509]: DCO device tun0 opened

```

**Comment by tbsky** [comment]
> I have tried ovpn_dco_v2 in 23.05.3, it is usable.
> 
> ```
>  OpenWrt 23.05.3, r23809-234f1a2efa
>  -----------------------------------------------------
> root@OpenWrt:~# opkg list-installed | grep -i dco
> kmod-ovpn-dco-v2 - 5.15.158+0.2.20240320-1
> 
> daemon.notice openvpn(sample_server)[2509]: OpenVPN 2.6.10 mipsel-openwrt-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] [DCO]
> daemon.notice openvpn(sample_server)[2509]: library versions: OpenSSL 3.0.13 30 Jan 2024, LZO 2.10
> daemon.notice openvpn(sample_server)[2509]: DCO version: N/A
> daemon.notice openvpn(sample_server)[2509]: net_route_v4_best_gw query: dst 0.0.0.0
> daemon.notice openvpn(sample_server)[2509]: net_route_v4_best_gw result: via 192.168.1.1 dev br-lan
> daemon.notice openvpn(sample_server)[2509]: Diffie-Hellman initialized with 2048 bit key
> daemon.notice openvpn(sample_server)[2509]: net_iface_new: add tun0 type ovpn-dco
> daemon.notice openvpn(sample_server)[2509]: DCO device tun0 opened

thanks for the info. last time I try if openvpn can not find dco version(eg: "DCO version: N/A"), then dco tunnel can not create correctly. maybe there was something wrong on my side. I will try again with current snapshot to see if it is working now.

**Comment by Spudz76** [comment]
Note you must also enable the feature inside OpenVPN package, in addition to the kmod, such as for mine:
`CONFIG_OPENVPN_wolfssl_ENABLE_DCO=y`

**Comment by romanovj** [comment]
enabling threaded backlog leads to kernel panic, no logs, sorry

sysctl -w net.core.backlog_threaded=1

**Comment by Spudz76** [comment]
> kernel panic
Not really, but it does break networking such as freezing existing ssh sessions and not responding to ICMP or anything else afterward until reboot from serial console, or power cycle.  Also does not recover after setting it back to "0".

Log from serial console where it definitely doesn't panic. (mt7621 / Linksys EA7300-v1)
```
BusyBox v1.36.1 (2024-04-29 03:09:55 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r26329+8-cffd3ad8d7
 -----------------------------------------------------
root@wonky2:/# uname -a
Linux wonky2.lan 6.6.30 #0 SMP Thu May 16 05:31:56 2024 mips GNU/Linux
root@wonky2:/# sysctl net.core.backlog_threaded
net.core.backlog_threaded = 0
root@wonky2:/# sysctl -w net.core.backlog_threaded=1
net.core.backlog_threaded = 1
root@wonky2:/# sysctl net.core.backlog_threaded
net.core.backlog_threaded = 1
root@wonky2:/#
```

**Comment by csharper2005** [comment]
> Even the `ovpn_dco_v2` module works again (didn't for a while)

Have you tested it? I had no success with 6.6 & mediatek/filogic & ramips/mt7621. OpenVPN client (tun, dco) connects, some resources are available via the tunnel, but some aren't.

The errors on a server side:
```
Sun May 19 07:16:40 2024 daemon.err openvpn(server)[11019]: TLS Error: could not determine wrapping from [AF_INET6]::ffff:xx.xx.xx.xx:21218 (via ::ffff:xx.xx.xx.xx%eth1)
Sun May 19 07:16:42 2024 daemon.err openvpn(server)[11019]: TLS Error: could not determine wrapping from [AF_INET6]::ffff:xx.xx.xx.xx:21218 (via ::ffff:xx.xx.xx.xx%eth1)
Sun May 19 07:16:46 2024 daemon.err openvpn(server)[11019]: TLS Error: could not determine wrapping from [AF_INET6]::ffff:xx.xx.xx.xx:21218 (via ::ffff:xx.xx.xx.xx%eth1)
Sun May 19 07:16:54 2024 daemon.err openvpn(server)[11019]: TLS Error: could not determine wrapping from [AF_INET6]::ffff:xx.xx.xx.xx:21218 (via ::ffff:xx.xx.xx.xx%eth1)
Sun May 19 07:17:10 2024 daemon.err openvpn(server)[11019]: TLS Error: could not determine wrapping from [AF_INET6]::ffff:xx.xx.xx.xx:21218 (via ::ffff:xx.xx.xx.xx%eth1)
Sun May 19 07:17:42 2024 daemon.err openvpn(server)[11019]: TLS Error: could not determine wrapping from [AF_INET6]::ffff:xx.xx.xx.xx:21218 (via ::ffff:xx.xx.xx.xx%eth1)
```
There is no any errors without dco. It looks like packets corruption.

**Comment by namiltd** [comment]
@csharper2005 Check this out: https://github.com/openwrt/openwrt/issues/15491#issuecomment-2119136327

**Comment by Spudz76** [comment]
I should have said, "compiles again"

No I have never actually tried using it (yet)

**Comment by csharper2005** [comment]
OpenVPN stops work after installing `libopenssl-devcrypto`. Any ideas?
```
Sun May 19 14:05:56 2024 daemon.err openvpn(client)[5112]: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network                                           connectivity)
Sun May 19 14:05:56 2024 daemon.err openvpn(client)[5112]: TLS Error: TLS handshake failed
Sun May 19 14:05:56 2024 daemon.notice openvpn(client)[5112]: SIGUSR1[soft,tls-error] received, process restarting
Sun May 19 14:05:57 2024 daemon.warn openvpn(client)[5112]: NOTE: the current --script-security setting may allow this configuration to call us                                          er-defined scripts
Sun May 19 14:05:57 2024 daemon.notice openvpn(client)[5112]: TCP/UDP: Preserving recently used remote address: [AF_INET]xx.xx.xx.xx:xxxx
Sun May 19 14:05:57 2024 daemon.notice openvpn(client)[5112]: UDPv4 link local: (not bound)
Sun May 19 14:05:57 2024 daemon.notice openvpn(client)[5112]: UDPv4 link remote: [AF_INET]xx.xx.xx.xx:xxxx
Sun May 19 14:06:57 2024 daemon.err openvpn(client)[5112]: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network                                           connectivity)
Sun May 19 14:06:57 2024 daemon.err openvpn(client)[5112]: TLS Error: TLS handshake failed
Sun May 19 14:06:57 2024 daemon.notice openvpn(client)[5112]: SIGUSR1[soft,tls-error] received, process restarting
Sun May 19 14:06:58 2024 daemon.warn openvpn(client)[5112]: NOTE: the current --script-security setting may allow this configuration to call us                                          er-defined scripts
Sun May 19 14:06:58 2024 daemon.notice openvpn(client)[5112]: TCP/UDP: Preserving recently used remote address: [AF_INET]xx.xx.xx.xx:xxxx
Sun May 19 14:06:58 2024 daemon.notice openvpn(client)[5112]: UDPv4 link local: (not bound)
Sun May 19 14:06:58 2024 daemon.notice openvpn(client)[5112]: UDPv4 link remote: [AF_INET]xx.xx.xx.xx:xxxx
```

`devcrypto.cnf` (default, without the changes):
```
[devcrypto_sect]
default_algorithms = ALL
#USE_SOFTDRIVERS = 2
CIPHERS=DES-CBC, DES-EDE3-CBC, AES-128-CBC, AES-192-CBC, AES-256-CBC, \
	AES-128-CTR, AES-192-CTR, AES-256-CTR
DIGESTS = NONE
```

```
~# openssl engine -t -c -vv -pre DUMP_INFO devcrypto
(devcrypto) /dev/crypto engine
Information about ciphers supported by the /dev/crypto engine:
Cipher DES-CBC, NID=31, /dev/crypto info: id=1, driver=cbc(des-eip93) (hw accelerated)
Cipher DES-EDE3-CBC, NID=44, /dev/crypto info: id=2, driver=cbc(des3_ede-eip93) (hw accelerated)
Cipher BF-CBC, NID=91, /dev/crypto info: id=3, CIOCGSESSION (session open call) failed
Cipher CAST5-CBC, NID=108, /dev/crypto info: id=4, CIOCGSESSION (session open call) failed
Cipher AES-128-CBC, NID=419, /dev/crypto info: id=11, CIOCGSESSION (session open call) failed
Cipher AES-192-CBC, NID=423, /dev/crypto info: id=11, CIOCGSESSION (session open call) failed
Cipher AES-256-CBC, NID=427, /dev/crypto info: id=11, CIOCGSESSION (session open call) failed
Cipher RC4, NID=5, /dev/crypto info: id=12, CIOCGSESSION (session open call) failed
Cipher AES-128-CTR, NID=904, /dev/crypto info: id=21, driver=ctr(aes-eip93) (hw accelerated)
Cipher AES-192-CTR, NID=905, /dev/crypto info: id=21, driver=ctr(aes-eip93) (hw accelerated)
Cipher AES-256-CTR, NID=906, /dev/crypto info: id=21, driver=ctr(aes-eip93) (hw accelerated)
Cipher AES-128-ECB, NID=418, /dev/crypto info: id=23, CIOCGSESSION (session open call) failed
Cipher AES-192-ECB, NID=422, /dev/crypto info: id=23, CIOCGSESSION (session open call) failed
Cipher AES-256-ECB, NID=426, /dev/crypto info: id=23, CIOCGSESSION (session open call) failed

Information about digests supported by the /dev/crypto engine:
Digest MD5, NID=4, /dev/crypto info: id=13, driver=md5-generic (software), CIOCCPHASH capable
Digest SHA1, NID=64, /dev/crypto info: id=14, driver=sha1-generic (software), CIOCCPHASH capable
Digest RIPEMD160, NID=117, /dev/crypto info: id=102, driver=unknown. CIOCGSESSION (session open) failed
Digest SHA224, NID=675, /dev/crypto info: id=103, driver=sha224-generic (software), CIOCCPHASH capable
Digest SHA256, NID=672, /dev/crypto info: id=104, driver=sha256-generic (software), CIOCCPHASH capable
Digest SHA384, NID=673, /dev/crypto info: id=105, driver=sha384-generic (software), CIOCCPHASH capable
Digest SHA512, NID=674, /dev/crypto info: id=106, driver=sha512-generic (software), CIOCCPHASH capable

[Success]: DUMP_INFO
 [DES-CBC, DES-EDE3-CBC, AES-128-CTR, AES-192-CTR, AES-256-CTR]
     [ available ]
     USE_SOFTDRIVERS: specifies whether to use software (not accelerated) drivers (0=use only accelerated drivers, 1=allow all drivers, 2=use if acceleration can't be determined) [default=2]
     CIPHERS: either ALL, NONE, or a comma-separated list of ciphers to enable [default=ALL]
     DIGESTS: either ALL, NONE, or a comma-separated list of digests to enable [default=NONE]
     DUMP_INFO: dump info about each algorithm to stderr; use 'openssl engine -pre DUMP_INFO devcrypto'

```

**Comment by Spudz76** [comment]
Something wrong with your eip93 driver or devcrypto, mine says:
```
root@wonky2:~# openssl engine -t -c -vv -pre DUMP_INFO devcrypto
(devcrypto) /dev/crypto engine
Information about ciphers supported by the /dev/crypto engine:
Cipher DES-CBC, NID=31, /dev/crypto info: id=1, driver=cbc(des-eip93) (hw accelerated)
Cipher DES-EDE3-CBC, NID=44, /dev/crypto info: id=2, driver=cbc(des3_ede-eip93) (hw accelerated)
Cipher BF-CBC, NID=91, /dev/crypto info: id=3, CIOCGSESSION (session open call) failed
Cipher CAST5-CBC, NID=108, /dev/crypto info: id=4, CIOCGSESSION (session open call) failed
Cipher AES-128-CBC, NID=419, /dev/crypto info: id=11, driver=cbc(aes-eip93) (hw accelerated)
Cipher AES-192-CBC, NID=423, /dev/crypto info: id=11, driver=cbc(aes-eip93) (hw accelerated)
Cipher AES-256-CBC, NID=427, /dev/crypto info: id=11, driver=cbc(aes-eip93) (hw accelerated)
Cipher RC4, NID=5, /dev/crypto info: id=12, CIOCGSESSION (session open call) failed
Cipher AES-128-CTR, NID=904, /dev/crypto info: id=21, driver=ctr(aes-eip93) (hw accelerated)
Cipher AES-192-CTR, NID=905, /dev/crypto info: id=21, driver=ctr(aes-eip93) (hw accelerated)
Cipher AES-256-CTR, NID=906, /dev/crypto info: id=21, driver=ctr(aes-eip93) (hw accelerated)
Cipher AES-128-ECB, NID=418, /dev/crypto info: id=23, driver=ecb(aes-eip93) (hw accelerated)
Cipher AES-192-ECB, NID=422, /dev/crypto info: id=23, driver=ecb(aes-eip93) (hw accelerated)
Cipher AES-256-ECB, NID=426, /dev/crypto info: id=23, driver=ecb(aes-eip93) (hw accelerated)
Cipher CAMELLIA-128-CBC, NID=751, /dev/crypto info: id=101, CIOCGSESSION (session open call) failed
Cipher CAMELLIA-192-CBC, NID=752, /dev/crypto info: id=101, CIOCGSESSION (session open call) failed
Cipher CAMELLIA-256-CBC, NID=753, /dev/crypto info: id=101, CIOCGSESSION (session open call) failed

Information about digests supported by the /dev/crypto engine:
Digest MD5, NID=4, /dev/crypto info: id=13, driver=md5-generic (software), CIOCCPHASH capable
Digest SHA1, NID=64, /dev/crypto info: id=14, driver=sha1-generic (software), CIOCCPHASH capable
Digest RIPEMD160, NID=117, /dev/crypto info: id=102, driver=unknown. CIOCGSESSION (session open) failed
Digest SHA224, NID=675, /dev/crypto info: id=103, driver=sha224-generic (software), CIOCCPHASH capable
Digest SHA256, NID=672, /dev/crypto info: id=104, driver=sha256-generic (software), CIOCCPHASH capable
Digest SHA384, NID=673, /dev/crypto info: id=105, driver=sha384-generic (software), CIOCCPHASH capable
Digest SHA512, NID=674, /dev/crypto info: id=106, driver=sha512-generic (software), CIOCCPHASH capable

[Success]: DUMP_INFO
 [DES-CBC, DES-EDE3-CBC, AES-128-CBC, AES-192-CBC, AES-256-CBC, AES-128-CTR, AES-192-CTR, AES-256-CTR]
```
Which is the full list from the conf (looks same as yours)

**Comment by romanovj** [comment]
> Any ideas?

you didn't install kernal modules for CBC

```
Cipher AES-128-CBC, NID=419, /dev/crypto info: id=11, CIOCGSESSION (session open call) failed
Cipher AES-192-CBC, NID=423, /dev/crypto info: id=11, CIOCGSESSION (session open call) failed
Cipher AES-256-CBC, NID=427, /dev/crypto info: id=11, CIOCGSESSION (session open call) failed
```

**Comment by csharper2005** [comment]
@Spudz76, @romanovj thanks. Will check. @Spudz76 does your result was obtained on mt7621 and kernel 6.6?

And one more finding. Noticed that `CHACHA20-POLY1305` doesn't work with dco. There is a difference with wireguard, dco doesn't load libchacha20poly1305 module.
```
root@ts:~# lsmod | grep ovpn_dco_v2
ip6_udp_tunnel         12288  2 wireguard,ovpn_dco_v2
ovpn_dco_v2            53248  0
udp_tunnel             20480  2 wireguard,ovpn_dco_v2

root@ts:~# lsmod | grep wireguard
ip6_udp_tunnel         12288  2 wireguard,ovpn_dco_v2
**libchacha20poly1305**    12288  1 wireguard
**libcurve25519_generic**   20480  1 wireguard
udp_tunnel             20480  2 wireguard,ovpn_dco_v2
wireguard              69632  0

```

**Comment by Spudz76** [comment]
Yeah, from the [ovpn-dco repo](https://github.com/OpenVPN/ovpn-dco/):
```
This is a list of current limitations which are planned to be removed as we move forward:
* Only AEAD mode and 'none' (with no auth) supported
* Only AES-GCM and CHACHA20POLY1305 ciphers supported
```
However eip93 (mt7621) hardware doesn't do chacha anyway.  OpenVPN may be using internal non-engine OpenSSL chacha code (not the sw implementation in kernel) since the engine doesn't accel it?

But then also `mssfix` is still unsupported and generally you have to [turn MTUs down](https://github.com/OpenVPN/ovpn-dco/issues/31#issuecomment-2014250436) (`tun-mtu` < 1420) because if it fragments then your throughput gets chopped due to extra handoffs overhead/delays which is usually slower than just not using accel at all (in general the topic of that whole upstream thread).  Also eip93 is horrible at small data chunks below ~512KB even with the fallback/bypass-by-size feature which doesn't seem to actually work (or it just falls back to the kernel sw implementation which is way slower than not using the engine).  Seems like for optimal speeds OpenSSL would need to decide to not use the engine for smaller chunks, the eip93 module can only defer to the sw version in the kernel.

There are no significant changes between the upstream `master` and the tag currently built in OpenWRT `main`.

**Comment by romanovj** [comment]
I replaced 760-net-core-add-optional-threading-for-backlog-processi.patch with net-provide-smp-threads-for-backlog-napi https://github.com/mina/linux/commit/1a3e4d6a75c6301ff08d1cc5ef081d2213c87fd1

It's just works)

```
 693     2 root     SW       0   0%  11% [napi/phy0-7]
  698     2 root     SW       0   0%   4% [mt76-tx phy0]
 5014  4980 root     R     1416   1%   2% top -n1
  274     2 root     SW       0   0%   2% [napi/mtk_eth-6]
  273     2 root     SW       0   0%   2% [napi/mtk_eth-5]
   45     2 root     SW       0   0%   2% [backlog_napi/1]
   47     2 root     SW       0   0%   2% [backlog_napi/3]
   44     2 root     SW       0   0%   2% [backlog_napi/0]
```

**Comment by csharper2005** [comment]
> ovpn-dco-v2 needs depends: +kmod-crypto-chacha20poly1305 +kmod-crypto-lib-chacha20 +kmod-crypto-lib-poly1305

Yeah, you're right. Now CHACHA20-POLY1305 is working. I got DL 48 / UP 57 mbit/s (mt7621, tun-mtu 1320).

Should we fix the dependencies for ovpn_dco_v2 kmod packages?

**Comment by tbsky** [comment]
> > ovpn-dco-v2 needs depends: +kmod-crypto-chacha20poly1305 +kmod-crypto-lib-chacha20 +kmod-crypto-lib-poly1305
> 
> Yeah, you're right. Now CHACHA20-POLY1305 is working. I got DL 48 / UP 57 mbit/s (mt7621, tun-mtu 1320).

   I got similar result under 23.05.  AES is much worse.  without DCO it can do 15-20 mbit/s.  wireguard got 300mib/s DL speed at the same device.

**Comment by Spudz76** [comment]
`+kmod-crypto-chacha20poly1305` by itself already pulls in `+kmod-crypto-lib-chacha20 +kmod-crypto-lib-poly1305` (and `+kmod-crypto-aead` which can thus be removed)

Working on those dep fixes, currently testing a build with adjustments.  Thing is kernel modules build keeps crashing on missing `chacha-mips.ko` but the deps are now the same as `kmod-wireguard` which builds everything fine (confusing).  Everything in the makefiles should be pulling that module in.  I have done just about every clean other than distclean.

**Comment by sweroam-mibr** [comment]
#14318  Any possibility that this bug is resolved in 6.6?

**Pull request merged**
