### PR TITLE
wwan: update proto to serve more than one interface

### PR DESCRIPTION
**Pull request by feckert**
- Add ec25 to database
- Add mc7304 to database
- check ifname on proto event -> updates proto to use more then one interface with this proto
- fix shellcheck warnings

This is a updated pullrequest from 
https://github.com/lede-project/source/pull/1310

### CODE REVIEW

**Comment by feckert** [comment]
@dedeckeh any progress on my PR?

**Comment by blogic** [comment]
@feckert patch 3 has a grammar error then/than. the description does not explain what the patch does. at first glance it also looks like we are now using hardcoded ifnames which we wanted to avoid
patch 4 and 5 have no description that is acceptable.

**Comment by blogic** [comment]
and patch 4 looks wrong we want to pass all args singletons and not all crammed into a single arg

**Comment by feckert** [comment]
@blogic thanks for coment

> at first glance it also looks like we are now using hardcoded ifnames which we wanted to avoid

I unterstand your concern but how could I pin the wwan proto handler to use on special interface if i have more then 1 modem in the system.

My suggestion would be:
We could make this configurable? If a ifname is set then use this **ifname** and  if no **ifname** is set use the first one which the proto handler could find.

We could also use the usb bus id for example "1-1" or "2-1.3" to pin the proto  handler and use the network interface on this usb device?

**Comment by blogic** [comment]
feel free to propose a patch on the ML, closing this for now as its rotting.

**Comment by feckert** [comment]
@blogic 
We could at least add the following commits to the database:
https://github.com/openwrt/openwrt/pull/686/commits/d3e243cec2b843996700be75a440f78cdcf856ea
https://github.com/openwrt/openwrt/pull/686/commits/79c07c79ee7d369bc8d69271a9ac96785a52f8ff

**Pull request closed without merging**
