### PR TITLE
musl: bump to 1.1.16

### PR DESCRIPTION
**Pull request by seragh**
Tested on mvebu, improves compatibility with Linux-4.8 and later, details in the commit message

### CODE REVIEW

**Comment by wigyori** [comment]
Thanks, I'll do a test-run on ar71xx.

**Comment by wigyori** [comment]
BTW @seragh , would you mind to take a look at these please?

https://github.com/lede-project/source/commit/b97c933ffb5aae338351a1db12a3f7cf5234f5c7
https://github.com/lede-project/source/commit/2912f9f2a2e5997df069d38e20d85ff4cc51acef
https://github.com/lede-project/source/commit/4c4047ec19edcaf39ec83728904d1081bf848894

Thx,
-w-

**Comment by seragh** [comment]
On Mon, 09 Jan 2017 00:47:58 -0800
Zoltan Herpai <notifications@github.com> wrote:

> BTW @seragh , would you mind to take a look at these please?
> 
> https://github.com/lede-project/source/commit/b97c933ffb5aae338351a1db12a3f7cf5234f5c7

Is a no-op commit, also 0xx- is a lie, it's not a backport, 1xx- would
be more appropriate me thinks if we already move it.

> https://github.com/lede-project/source/commit/2912f9f2a2e5997df069d38e20d85ff4cc51acef

already in 1.1.16

> https://github.com/lede-project/source/commit/4c4047ec19edcaf39ec83728904d1081bf848894

This is just a refresh, basically another no-op commit. A refresh is
done as part of this PR as well.

Ralph

**Comment by wigyori** [comment]
Ack, thanks.
And runtime-tested on ar71xx.

**Pull request merged**
