### PR TITLE
ccache improvements

### PR DESCRIPTION
**Pull request by nihilus**

### CODE REVIEW

**Review by schuettecarsten — APPROVED** [review]

**Comment by Neustradamus** [comment]
@hauke, @hnyman: What do you think?

**Comment by hnyman** [comment]
Sorry, no deeper ccache knowledge.

**Comment by blogic** [comment]
merged, Thanks !

**Comment by Neustradamus** [comment]
Merged commits:
- https://github.com/openwrt/openwrt/commit/1f11912138ce8a77cc0e2faa26942133d393b010
- https://github.com/openwrt/openwrt/commit/3859e8eeb82950d8594f60d40e5ee23fd02207c9

**Comment by stefanct** [comment]
Overriding the user's compression settings via `CCACHE_NOCOMPRESS:=true` is a regression for those who rely on the space savings AFAICT.
How about something like this (untested):

    CCACHE_NOCOMPRESS?=true
    export CCACHE_NOCOMPRESS

PS: I ended up here because something else is broken with compressions (w/o these patches on the openwrt-24.10 branch), namely with negative compression levels, but I haven't figured it out yet.

**Comment by nihilus** [comment]
> Overriding the user's compression settings via `CCACHE_NOCOMPRESS:=true` is a regression for those who rely on the space savings AFAICT. How about something like this (untested):
> 
> ```
> CCACHE_NOCOMPRESS?=true
> export CCACHE_NOCOMPRESS
> ```
> 
> PS: I ended up here because something else is broken with compressions (w/o these patches on the openwrt-24.10 branch), namely with negative compression levels, but I haven't figured it out yet.

Please make PR with this fix... My rationale is to make it easy for the users to have things faster.

**Pull request closed without merging**
