### PR TITLE
treewide: fix some cosmetic glitches in dts files

### PR DESCRIPTION
**Pull request by p-wassi**
- remove single spaces hidden by a tab
- replace indentation with spaces by tabs
- make empty lines empty

### CODE REVIEW

**Comment by jow-** [comment]
Please use `treewide: ` as prefix instead of `general: `

**Comment by p-wassi** [comment]
Renamed (also in the commit message)

**Comment by mkresin** [comment]
May I ask to cleanup some more dts(i) files.

The following should fix some more issue:

```
# drop trailing whitespace
find -iname *.dtsi -o -iname *.dts -exec perl -p -i -e 's/(.*?)\s+\n/$1\n/' {} \;

# drop more unnecessary blank lines
find -iname *.dtsi -o -iname *.dts -exec perl -p -i -e 'undef $/; s/(}?;\n)\s*\n(\s*};)/$1$2/g' {} \;
```

Beside of that the following files still have spaces vs. tabs issues:

- target/linux/at91/files/arch/arm/boot/dts/wb50n.dts
- target/linux/samsung/dts/TQ210.dts

**Comment by mkresin** [comment]
> where you're added as Signed-off-by, is this ok?

Fine with me with. As it was something trivial, I don't really care about my SoB.

Anyway, thanks a lot for the cleanup. I've merged the changes.

**Pull request closed without merging**
