### PR TITLE
kernel: bump 5.10 to 5.10.125

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: ipq806x/R7800

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by AuthorReflex** [comment]
due to commit 6950ee32c1879818de03f13a9a5de1be41ad2782 "lsm,selinux: pass flowi_common instead of flowi to the LSM hooks" xtables-addons need to be updated
```
--- a/extensions/xt_ECHO.c
+++ b/extensions/xt_ECHO.c
@@ -101,7 +101,7 @@
        memcpy(&fl.daddr, &newip->daddr, sizeof(fl.daddr));
        fl.fl6_sport = newudp->source;
        fl.fl6_dport = newudp->dest;
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 11, 0)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 10, 121)
        security_skb_classify_flow((struct sk_buff *)oldskb, flowi6_to_flowi_common(&fl));
 #else
        security_skb_classify_flow((struct sk_buff *)oldskb, flowi6_to_flowi(&fl));
```

**Comment by graysky2** [comment]
I did not see that file in the kernel source nor in the git repo.

**Comment by graysky2** [comment]
@AuthorReflex - see above, thanks

**Comment by jospezial** [comment]
5.10.122 released

**Comment by jospezial** [comment]
5.10.123 released

**Comment by hauke** [comment]
Thank you for your patches, I added them to the master branch in 706a4ec40cce108f484b40805bfa48619a0a7f09, 9edc514e3dafcc36db69046a37daab818cfc1a07, 5202a511cc4557303d4b77bf77ebb66e524dcddf, 9e5d743422edc4036cda7d96b96ba62705f382de and 53d99fedc7afd96adfb6f38fc939c9ee9981c2ed.

**Comment by dave14305** [comment]
https://github.com/openwrt/openwrt/blob/openwrt-22.03/target/linux/bcm27xx/patches-5.10/950-0005-Revert-mailbox-avoid-timer-start-from-callback.patch

This patch needs attention after the kernel update in 22.03.

**Pull request closed without merging**
