### PR TITLE
libpcap: add optional netfilter support

### PR DESCRIPTION
**Pull request by InkblotAdmirer**
Adds configuration option for libpcap to enable listening on netfilter_queue.
Enables nflog interface in tcpdump and NFLOG target with associated options in iptables.
    
Default is disabled -- no changes to build unless configured therefore package version is left unchanged.

Tested on mvebu, Shelby.

EDIT:  updated notes based on latest PR.

Signed-off-by: InkblotAdmirer <github@inkblotadmirer.me>

### CODE REVIEW

**Review by seragh — COMMENTED** [review]
The HAS_NF is odd. It's not a property of libpcap but something you intent to make configurable. Maybe PCAP_NFQ_SUPPORT works for you as well.

Also you could use PKG_CONFIG_DEPENDS with ifdefs, see openssl for an example.

The commit message says required for 3506. Without external references this can't be understood. I'd mention fwknop and the requirement with a sentence or two.

Looking at fwknop pull request you don't have a config dependency on PCAP_HAS_NF but in fact seem to drop the dependency on libpcap all together. So where does this requirement come from?

**Comment by InkblotAdmirer** [comment]
I am ambivalent toward naming and will change based on whatever convention is desired -- I was following the style in the existing config file however:  the two existing configs are PCAP_HAS_USB and PCAP_HAS_BT.  Without the HAS_NF set, support won't even be compiled in so the convention made sense to me.

As to the fwknop dependency, I was misremembering.  When fwknop is configured to listen on netfilter it disables libpcap support altogether (thus the dependency is removed).  I can amend the commit message to remove this and add the true reason for this, in that it allows tcpdump to use the nflog interface and iptables to use the NFLOG target and associated options.

Please let me know if the configuration variable should be updated as well.

**Comment by seragh** [comment]
On Sat, 26 Nov 2016 06:09:17 -0800
InkblotAdmirer <notifications@github.com> wrote:

> I am ambivalent toward naming and will change based on whatever
> convention is desired -- I was following the style in the existing
> config file however:  the two existing configs are PCAP_HAS_USB and
> PCAP_HAS_BT.  Without the HAS_NF set, support won't even be compiled
> in so the convention made sense to me.
> 

In that case leave it as it is.

> As to the fwknop dependency, I was misremembering.  When fwknop is
> configured to listen on netfilter it disables libpcap support
> altogether (thus the dependency is removed).  I can amend the commit
> message to remove this and add the true reason for this, in that it
> allows tcpdump to use the nflog interface and iptables to use the
> NFLOG target and associated options.

Yes, please update the commit message to the real reason. Then Author
and Signed-of-by need a real name and need to match. As for the Subject
it's to long, what do you think about "libpcap: add optional netfilter
support" instead?

**Review by seragh — COMMENTED** [review]
The pull request is just a cover letter for a series and gets thrown away, just that your series consists of only one commit. Only the commits in the series need the Signed-off-by. The commit subject is the first line of the commit message followed by a blank line and should be no longer than 50 characters if avoidable. It's the part github prints in bold for commits.

**Comment by seragh** [comment]
The config variable and not using PKG_CONFIG_DEPENDS isn't pretty but the same as currently done. So at this point I'd add my Reviewed-by, tho no clue if github provides such somehow.

**Comment by InkblotAdmirer** [comment]
Thanks for the review and input!

**Comment by InkblotAdmirer** [comment]
http://lists.infradead.org/pipermail/lede-dev/2017-February/006019.html

**Pull request closed without merging**
