### PR TITLE
octeontx: add 6.1 testing kernel

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@Gateworks can you runtest?

**Comment by Gateworks** [comment]
> @Gateworks can you runtest?

I've tested this but it fails to boot on Gateworks Newport due to a dt issue exposed by commit [2b2cd74a06c3 ("irqchip/gic-v3: Claim iomem resources")](https://github.com/torvalds/linux/commit/2b2cd74a06c3) in 5.19.

The fix would be to revert that patch (not obvious/trivial) or look into fixing the the dt issue (also not obvious/trivial) which has to do with the [ecam node claiming memory regions which overlap with its peripherals](https://lore.kernel.org/lkml/410c8561-a7e3-6a3f-b634-08adaa806111@arm.com/). Note the dt for these boards is not in the linux tree but instead in the boot firmware.

The OcteonTX processors (CN80xx/CN81xx) have gone end of life and are no longer supported by Cavium (which was bought by Marvell shortly before they dumped support for the processor)

Are there any other boards other than the Gateworks Newport product family using octeontx?

If not I would be for just dropping support for it

**Comment by PolynomialDivision** [comment]
@dangowrt @robimarko Same discussion here.

**Comment by robimarko** [comment]
I dont really have anything smart to comment here, its either somebody fixes it or we drop it.

**Comment by PolynomialDivision** [comment]
Okay, I will do a PR for dropping this target. Let's see.

**Pull request closed without merging**
