### PR TITLE
ramips: mt7620: add kernel size for Jboot devices

### PR DESCRIPTION
**Pull request by CHKDSK88**
Since few months multiple users reported problems with various JBoot
devices. [0][1][2][3] All of them was bricked.

On my Lava LR-25G001 it freezes with current snapshot:

```
CDW57CAM_003 Jboot B695
Giga Switch AR8327 init
AR8327/AR8337 id   ==> 0x1302
JRecovery Version R1.2 2014/04/01 18:25
SPI FLASH: MX25l12805d 16M
.
.
(freeze)
```

The kernel size is >2048k.

I built current master with minimal config and it boots well:

```
CDW57CAM_003 Jboot B695
Giga Switch AR8327 init
AR8327/AR8337 id   ==> 0x1302
JRecovery Version R1.2 2014/04/01 18:25
SPI FLASH: MX25l12805d 16M
.
...........................
Starting kernel @80000000...
[    0.000000] Linux version 5.4.124
```

Kernel size is <2048k.

Jboot bootloader isn't open source, so it's impossible to find
solution in code. It looks, that some buffer for kernel have 2MB size.

To avoid bricked devices, this commit introduces 2048k limit kernel
size for all jboot routers.

Fixes: FS#3539

[0] https://bugs.openwrt.org/index.php?do=details&task_id=3539
[1] https://eko.one.pl/forum/viewtopic.php?pid=254344
[2] https://eko.one.pl/forum/viewtopic.php?id=20930
[3] https://eko.one.pl/forum/viewtopic.php?pid=241376#p241376

Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>

### CODE REVIEW

**Comment by mpratt14** [comment]
Hi Pawel,

are you sure there is no solution?

what type of image is Jboot expecting? LZMA compressed or uncompressed or....?

To me, it sounds like a classic problem of the bootloader not able to decompress an image that is too large
in that case, it may be possible to use the lzma-loader somehow

**Comment by CHKDSK88** [comment]
> Hi Pawel,
> 

Hi Michael,

> are you sure there is no solution?
> 

Nope, but at this moment I don't know how to make it work.

> what type of image is Jboot expecting? LZMA compressed or uncompressed or....?
> 

Jboot uses LZMA by default.

> To me, it sounds like a classic problem of the bootloader not able to decompress an image that is too large
> in that case, it may be possible to use the lzma-loader somehow

The mayor problem is, that jboot freezes if kernel is too big, and in most cases, only way is reprogram nor with external programmer.  LZMA is used already,  Jboot isn't FOSS, so I'm afraid, that only way is second stage bootloader. But I never run SSBL on any architecture.

**Comment by CHKDSK88** [comment]
> Ohh!
> 
> I have to find my DWR-116!
> 
> @mpratt14, the kernel is the default `$(KERNEL_DTB)`, which is `kernel-bin | append-dtb | lzma`.
> 
> So the lzma-loader could help. At least one of it's modes.

@xabolcs 
Can lzma-loader read kernel image from spi-nor?

**Comment by xabolcs** [comment]
>  Can lzma-loader read kernel image from spi-nor?

Yep!
It has two modes:
* LZMA wrapper (aka [`Device/uimage-lzma-loader`](https://github.com/openwrt/openwrt/blob/7f946a880a61816e338e99b79ece6fb206fc6f9c/target/linux/ramips/image/Makefile#L199)), where it offloads the decompresson work from bootloader. It's very famous in the [`ramips/mt7621`](https://github.com/openwrt/openwrt/blob/master/target/linux/ramips/image/mt7621.mk) subtarget.
* OKLI loader (receipts with `LOADER_FLASH_OFFS :=`, `COMPILE/loader-$(1).bin :=`, ...): this mode helps where the bootloader has hard size limit. E.g. it only loads 1536k / 2048k data from flash. It's common in `ath79`, but it was introduced to `ramips` with [HooToo HT-TM05](https://github.com/openwrt/openwrt/blob/7f946a880a61816e338e99b79ece6fb206fc6f9c/target/linux/ramips/image/mt7620.mk#L494).

**Comment by xabolcs** [comment]
One should find out is there a hard limit for size in JBOOT with excercising the lzma-loader!

It would be nice if JBOOT would accept firmware images with uImage header. Then we could use `$(Device/uimage-lzma-loader)` instead `KERNEL := ...`.
```
define Device/amit_jboot
  DLINK_IMAGE_OFFSET := 0x10000
  $(Device/uimage-lzma-loader)
  IMAGES += factory.bin
  IMAGE/sysupgrade.bin := mkdlinkfw | pad-rootfs | append-metadata
  IMAGE/factory.bin := mkdlinkfw | pad-rootfs | mkdlinkfw-factory
  DEVICE_PACKAGES := jboot-tools kmod-usb2 kmod-usb-ohci
endef
```

If JBOOT doesn't like uImage headers, then we should mimic the `Device/uimage-lzma-loader` recipe:
```
define Device/amit_jboot
  DLINK_IMAGE_OFFSET := 0x10000
  LOADER_TYPE := bin
  KERNEL := $(KERNEL_DTB) | loader-kernel
  IMAGES += factory.bin
  IMAGE/sysupgrade.bin := mkdlinkfw | pad-rootfs | append-metadata
  IMAGE/factory.bin := mkdlinkfw | pad-rootfs | mkdlinkfw-factory
  DEVICE_PACKAGES := jboot-tools kmod-usb2 kmod-usb-ohci
endef
```

If it boots then we are ready! :+1: 
It it starts the second stage loader, but it has crc problems, then the JBOOT may have hard limits on kernel size.

In this case we should try the OKLI loader. It's a bit complex to set up, but you have an example in `ramips/mt7620` already.

**Comment by adschm** [comment]
I'm taking this quickly in order to hopefully prevent some bricks. I've removed the "Fixes:", since this is no "fix".

Please continue discussion, so we are able to replace this temporary solution quickly, if possible.

**Comment by adschm** [comment]
... and, of course, thanks!

**Comment by adschm** [comment]
I will also backport this in a few days unless somebody complains or Hauke beats me ...

**Comment by xabolcs** [comment]
> I will also backport this ...

```
$ ls -Gg openwrt-imagebuilder-21.02.0-rc2-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/dlink_dwr-*1.02.0-rc2-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linu
-rw-r--r-- 1 1979480 May 28 16:04 openwrt-imagebuilder-21.02.0-rc2-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/dlink_dwr-116-a1-kernel.bin
-rw-r--r-- 1 1980104 May 28 16:04 openwrt-imagebuilder-21.02.0-rc2-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/dlink_dwr-118-a1-kernel.bin
-rw-r--r-- 1 1980126 May 28 16:04 openwrt-imagebuilder-21.02.0-rc2-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/dlink_dwr-118-a2-kernel.bin
-rw-r--r-- 1 1979554 May 28 16:04 openwrt-imagebuilder-21.02.0-rc2-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/dlink_dwr-921-c1-kernel.bin
-rw-r--r-- 1 1979554 May 28 16:04 openwrt-imagebuilder-21.02.0-rc2-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/dlink_dwr-921-c3-kernel.bin
-rw-r--r-- 1 1979561 May 28 16:04 openwrt-imagebuilder-21.02.0-rc2-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/dlink_dwr-922-e2-kernel.bin
-rw-r--r-- 1 1980114 May 28 16:04 openwrt-imagebuilder-21.02.0-rc2-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/dlink_dwr-960-kernel.bin
```
Interestingly the 21.02 kernels are smaller than the snapshot kernels.

The `ramips: mt7620: add kernel size for Jboot devices` commit should make it way to 21.02, but I think it's better to skip making them source only.

**Comment by adschm** [comment]
Ah, okay. Looks like we are close, though. Anyway, you are right, the KERNEL_SIZE patch is the proper measure for this, and if they fall out we can still disable them.

**Comment by mpratt14** [comment]
a possible idea to start

I don't know about the flash layout, so this example makes 2 assumptions
basically, I need to know where the headers are and how long they are
so assume that LOADER_FLASH_OFFS and `pad-to 64k` are both wrong numbers

 - there is no data appended to the end after `mkdlinkfw`
 - the true flash offset of kernel would be DLINK_IMAGE_OFFSET + loader and pad to 4k ( + length of header?)

in ramips/image/Makefile:

```
define Build/mkdlinkfw-lzma-loader
	-$(STAGING_DIR_HOST)/bin/mkdlinkfw \
		-k $(KDIR)/loader-$(DEVICE_NAME).lzma \
		-r $(IMAGE_KERNEL) \
		-o $@ \
		$(if $(DLINK_IMAGE_OFFSET), -O $(DLINK_IMAGE_OFFSET)) \
		-s $(DLINK_FIRMWARE_SIZE)
endef
```

then in the subtarget makefile

```
define Device/amit_jboot
  KERNEL := $(KERNEL_DTB) | uImage lzma -M 0x4f4b4c49
  DLINK_IMAGE_OFFSET := 0x10000
  LOADER_FLASH_OFFS := 0x230000
  LOADER_TYPE := bin
  COMPILE := loader-$(1).bin loader-$(1).lzma
  COMPILE/loader-$(1).bin := loader-okli-compile
  COMPILE/loader-$(1).lzma := append-loader-okli $(1) | pad-to 64k | lzma | pad-to 64k
  IMAGES += factory.bin
  IMAGE/factory.bin := mkdlinkfw-lzma-loader | append-rootfs | pad-rootfs | mkdlinkfw-factory
  IMAGE/sysupgrade.bin := mkdlinkfw-lzma-loader | append-rootfs | pad-rootfs | append-metadata
  DEVICE_PACKAGES := jboot-tools kmod-usb2 kmod-usb-ohci
endef
```

and DTS would have

```
partition@210000 {
	compatible = "openwrt,uimage", "denx,uimage";
	openwrt,ih-magic = <IH_MAGIC_OKLI>;
	label = "firmware";
	reg = <0x210000 0xde0000>;
};
```

**Comment by CHKDSK88** [comment]
@mpratt14 @xabolcs 

It works! Thank You guys. I will prepare changes for all jboot mt7620 devices.

```
CDW57CAM_003 Jboot B695
Giga Switch AR8327 init
AR8327/AR8337 id   ==> 0x1302
JRecovery Version R1.2 2014/04/01 18:25
SPI FLASH: MX25l12805d 16M
.
...
Starting kernel @80000000...


OpenWrt kernel loader for MIPS based SoC
Copyright (C) 2011 Gabor Juhos <juhosg@openwrt.org>
Looking for OpenWrt image... found at 0xbc020038
Decompressing kernel... done!
Starting kernel at 80000000...

[    0.000000] Linux version 5.4.124 (XXX@YYY) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r15433+1492-f34f4a6665)) #0 Thu Jun 10 10:51:13 2021
[    0.000000] Board has DDR2
[    0.000000] Analog PMU set to hw control
[    0.000000] Digital PMU set to hw control
[    0.000000] SoC Type: MediaTek MT7620A ver:2 eco:6
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019650 (MIPS 24KEc)
[    0.000000] MIPS: machine is LAVA LR-25G001
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 16240
[    0.000000] Kernel command line: console=ttyS0,57600 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.000000] Writing ErrCtl register=000566e0
[    0.000000] Readback ErrCtl register=000566e0
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 57436K/65536K available (4732K kernel code, 198K rwdata, 1044K rodata, 1184K init, 205K bss, 8100K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 256
[    0.000000] random: get_random_bytes called from start_kernel+0x358/0x54c with crng_init=0
[    0.000000] CPU Clock: 580MHz
[    0.000000] clocksource: systick: mask: 0xffff max_cycles: 0xffff, max_idle_ns: 583261500 ns
[    0.000000] systick: enable autosleep mode
[    0.000000] systick: running - mult: 214748, shift: 32
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6590553264 ns
[    0.000009] sched_clock: 32 bits at 290MHz, resolution 3ns, wraps every 7405115902ns
[    0.015485] Calibrating delay loop... 385.84 BogoMIPS (lpj=1929216)
[    0.087713] pid_max: default: 32768 minimum: 301
[    0.097063] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.111468] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.133102] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.152584] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.166181] pinctrl core: initialized pinctrl subsystem
[    0.177064] NET: Registered protocol family 16
[    0.670645] PCI host bridge /pcie@10140000 ranges:
[    0.680047]  MEM 0x0000000020000000..0x000000002fffffff
[    0.690417]   IO 0x0000000010160000..0x000000001016ffff
[    0.722929] rt2880_gpio 10000600.gpio: registering 24 gpios
[    0.733985] rt2880_gpio 10000600.gpio: registering 24 irq handlers
[    0.747033] PCI host bridge to bus 0000:00
[    0.755026] pci_bus 0000:00: root bus resource [mem 0x20000000-0x2fffffff]
[    0.768749] pci_bus 0000:00: root bus resource [io  0x10160000-0x1016ffff]
[    0.782378] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    0.795874] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    0.811668] pci 0000:00:00.0: [1814:0801] type 01 class 0x060400
[    0.823603] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    0.836036] pci 0000:00:00.0: reg 0x14: [mem 0x00000000-0x0000ffff]
[    0.848570] pci 0000:00:00.0: supports D1
[    0.856438] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    0.869870] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    0.885888] pci 0000:01:00.0: [14c3:7650] type 00 class 0x028000
[    0.897760] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff]
[    0.910297] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    0.922563] pci 0000:01:00.1: [14c3:8650] type 00 class 0x0d1100
[    0.934431] pci 0000:01:00.1: reg 0x10: [mem 0x00000000-0x000fffff]
[    0.946960] pci 0000:01:00.1: supports D1
[    0.954774] pci 0000:01:00.1: PME# supported from D0 D1 D3hot D3cold
[    0.969401] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    0.982448] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 01
[    0.995604] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    1.008725] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    1.022571] pci 0000:00:00.0: BAR 8: assigned [mem 0x20000000-0x201fffff]
[    1.036071] pci 0000:00:00.0: BAR 1: assigned [mem 0x20200000-0x2020ffff]
[    1.049579] pci 0000:01:00.0: BAR 0: assigned [mem 0x20000000-0x200fffff]
[    1.063077] pci 0000:01:00.1: BAR 0: assigned [mem 0x20100000-0x201fffff]
[    1.076574] pci 0000:00:00.0: PCI bridge to [bus 01]
[    1.086422] pci 0000:00:00.0:   bridge window [mem 0x20000000-0x201fffff]
[    1.100057] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    1.124191] clocksource: Switched to clocksource systick
[    1.136009] NET: Registered protocol family 2
[    1.144796] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    1.159731] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    1.176295] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    1.191468] TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    1.205479] TCP: Hash tables configured (established 1024 bind 1024)
[    1.218259] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    1.231169] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    1.245315] NET: Registered protocol family 1
[    1.253893] PCI: CLS 0 bytes, default 32
[    1.264634] rt-timer 10000100.timer: maximum frequency is 1220Hz
[    1.278626] workingset: timestamp_bits=14 max_order=14 bucket_order=0
[    1.299489] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    1.310997] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    1.347220] gpio-export gpio_export: 1 gpio(s) exported
[    1.357836] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    1.371464] printk: console [ttyS0] disabled
[    1.379934] 10000c00.uartlite: ttyS0 at MMIO 0x10000c00 (irq = 20, base_baud = 2500000) is a Palmchip BK-3103
[    1.399580] printk: console [ttyS0] enabled
[    1.399580] printk: console [ttyS0] enabled
[    1.416158] printk: bootconsole [early0] disabled
[    1.416158] printk: bootconsole [early0] disabled
[    1.441251] spi spi0.0: force spi mode3
[    1.449850] spi-nor spi0.0: mx25l12805d (16384 Kbytes)
[    1.460210] 3 fixed-partitions partitions found on MTD device spi0.0
[    1.472879] Creating 3 MTD partitions on "spi0.0":
[    1.482438] 0x000000000000-0x000000010000 : "jboot"
[    1.493171] 0x000000010000-0x000000ff0000 : "firmware"
[    1.628923] 2 uimage-fw partitions found on MTD device firmware
[    1.640748] Creating 2 MTD partitions on "firmware":
[    1.650658] 0x000000000000-0x0000001f732f : "kernel"
[    1.661569] 0x0000001f732f-0x000000fe0000 : "rootfs"
[    1.672396] mtd: device 3 (rootfs) set to be root filesystem
[    1.685513] 1 squashfs-split partitions found on MTD device rootfs
[    1.697918] 0x0000004b0000-0x000000fe0000 : "rootfs_data"
[    1.709728] 0x000000ff0000-0x000001000000 : "config"
[    1.721491] libphy: Fixed MDIO Bus: probed
[    1.739547] gsw: setting port4 to ephy mode
[    1.748041] mtk_soc_eth 10100000.ethernet: generated random MAC address 36:b4:c0:07:97:19
[    1.764558] libphy: mdio: probed
[    1.773330] switch0: Atheros AR8337 rev. 2 switch registered on mdio-bus
[    2.013339] ar8327: qca,phy-rgmii-en is not specified
[    2.025131] ar8327: qca,phy-rgmii-en is not specified
[    2.035390] mtk_soc_eth 10100000.ethernet: using fixed link parameters
[    2.049578] mtk_soc_eth 10100000.ethernet: loaded mt7620 driver
[    2.062091] mtk_soc_eth 10100000.ethernet eth0: mediatek frame engine at 0xb0100000, irq 5
[    2.079128] rt2880_wdt 10000120.watchdog: Initialized
[    2.090593] NET: Registered protocol family 10
[    2.104301] Segment Routing with IPv6
[    2.111715] NET: Registered protocol family 17
[    2.120703] 8021q: 802.1Q VLAN Support v1.8
[    2.143730] VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
[    2.164443] Freeing unused kernel memory: 1184K
[    2.173459] This architecture does not have kernel memory protection.
[    2.186313] Run /sbin/init as init process
[    2.513607] random: fast init done
[    3.799218] init: Console is alive
[    3.806409] init: - watchdog -
[    6.057282] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    6.325706] usbcore: registered new interface driver usbfs
[    6.336816] usbcore: registered new interface driver hub
[    6.347552] usbcore: registered new device driver usb
[    6.364724] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    6.379598] ehci-fsl: Freescale EHCI Host controller driver
[    6.392371] ehci-platform: EHCI generic platform driver
[    6.413194] phy phy-usbphy.0: remote usb device wakeup disabled
[    6.425011] phy phy-usbphy.0: UTMI 16bit 30MHz
[    6.433871] ehci-platform 101c0000.ehci: EHCI Host Controller
[    6.445358] ehci-platform 101c0000.ehci: new USB bus registered, assigned bus number 1
[    6.461273] ehci-platform 101c0000.ehci: irq 26, io mem 0x101c0000
[    6.483979] ehci-platform 101c0000.ehci: USB 2.0 started, EHCI 1.00
[    6.497525] hub 1-0:1.0: USB hub found
[    6.505507] hub 1-0:1.0: 1 port detected
[    6.518947] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    6.532666] ohci-platform: OHCI generic platform driver
[    6.543440] ohci-platform 101c1000.ohci: Generic Platform OHCI controller
[    6.557035] ohci-platform 101c1000.ohci: new USB bus registered, assigned bus number 2
[    6.572941] ohci-platform 101c1000.ohci: irq 26, io mem 0x101c1000
[    6.613607] hub 2-0:1.0: USB hub found
[    6.621592] hub 2-0:1.0: 1 port detected
[    6.634263] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    6.652989] init: - preinit -
[    8.358816] random: jshn: uninitialized urandom read (4 bytes read)
[    8.458699] random: jshn: uninitialized urandom read (4 bytes read)
[    8.819159] random: jshn: uninitialized urandom read (4 bytes read)
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[   10.349614] mount_root: jffs2 not ready yet, using temporary tmpfs overlay
[   10.367749] urandom-seed: Seed file not found (/etc/urandom.seed)
[   10.479201] procd: - early -
[   10.485048] procd: - watchdog -
[   10.886589] procd: - watchdog -
[   10.893551] procd: - ubus -
[   11.001758] urandom_read: 5 callbacks suppressed
[   11.001767] random: ubusd: uninitialized urandom read (4 bytes read)
[   11.042567] random: ubusd: uninitialized urandom read (4 bytes read)
[   11.059027] procd: - init -
Please press Enter to activate this console.
[   12.106500] kmodloader: loading kernel modules from /etc/modules.d/*
[   12.162171] Loading modules backported from Linux version v5.10.42-0-g65859eca4dff
[   12.177356] Backport generated by backports.git v5.10.42-1-0-gbee5c545
[   12.272657] xt_time: kernel timezone is -0000
[   12.458110] PPP generic driver version 2.4.2
[   12.476544] NET: Registered protocol family 24
[   12.532016] urngd: jent-rng init failed, err: 2
[   12.546836] mt76x0e 0000:01:00.0: card - bus=0x1, slot = 0x0 irq=4
[   12.559479] mt76x0e 0000:01:00.0: ASIC revision: 76100002
[   12.573493] mt76x0e 0000:01:00.0: Firmware Version: 0.1.00
[   12.670021] mt76x0e 0000:01:00.0: EEPROM ver:01 fae:00
[   12.728064] ieee80211 phy1: rt2x00lib_request_eeprom_file: Info - Loading EEPROM data from 'soc_wmac.eeprom'.
[   12.748067] rt2800_wmac 10180000.wmac: Direct firmware load for soc_wmac.eeprom failed with error -2
[   12.766297] rt2800_wmac 10180000.wmac: Falling back to sysfs fallback for: soc_wmac.eeprom
[   14.266224] ieee80211 phy1: rt2x00_set_rt: Info - RT chipset 6352, rev 0500 detected
[   14.281764] ieee80211 phy1: rt2x00_set_rf: Info - RF chipset 7620 detected
[   14.332581] kmodloader: done loading kernel modules from /etc/modules.d/*
```

**Comment by xabolcs** [comment]
So the easy way didn't work? 😕
This OKLI stuff is more complex and more fragile.

**Comment by mpratt14** [comment]
> So the easy way didn't work? 😕

I think the "easy way" requires uimage header that tells the bootloader that the image is uncompressed, but with JBoot that is not an option as far as we know

**Comment by mpratt14** [comment]
> Looking for OpenWrt image... found at 0xbc020038

try to adjust padding so that kernel is found exactly on the eraseblock 0xbc020000

**Comment by CHKDSK88** [comment]
> I think the "easy way" requires uimage header that tells the bootloader that the image is uncompressed, but with JBoot that is not an option as far as we know

Exactly. OKLI was easier.



> try to adjust padding so that kernel is found exactly on the eraseblock 0xbc020000

I'll try. 0x38 are sum of two JBOOT headers. Pad to 65480 instead 64k should align it.

**Comment by xabolcs** [comment]
> Exactly. OKLI was easier.

🙈

**Comment by CHKDSK88** [comment]
Please look #4255

**Comment by xabolcs** [comment]
> ... and in most cases, only way is reprogram nor with external programmer.

For the record, **I confirm** that anything over 2048 K (like an oversized kernel packed into lzma-loader) **bricks the device** (e.g my DWR-116) into a paper weight.

It doesn't recoverable with reset button method, the only way is to reprogram the flash chip.

**Comment by xabolcs** [comment]
> Exactly. OKLI was easier.

It's not easier! IT'S THE ONLY WAY! :grinning:

**Pull request closed without merging**
