### PR TITLE
kernel: bump 5.15 to 5.15.45

### PR DESCRIPTION
**Pull request by rsalvaterra**
For 5.15.44 (and also 5.10.119, heads up, @graysky2):
Delete the crypto-lib-blake2s kmod package, as BLAKE2s is now built-in.

Deleted (upstreamed):
generic/backport-5.15/890-v5.19-net-sfp-Add-tx-fault-workaround-for-Huawei-MA5671A-SFP-ON.patch [1]
generic/backport-5.15/610-v5.18-netfilter-flowtable-move-dst_check-to-packet-path.patch [2]
generic/pending-5.15/704-00-netfilter-flowtable-fix-excessive-hw-offload-attempt.patch [3]
generic/pending-5.15/704-01-netfilter-nft_flow_offload-skip-dst-neigh-lookup-for.patch [4]
generic/pending-5.15/704-02-net-fix-dev_fill_forward_path-with-pppoe-bridge.patch [5]
generic/pending-5.15/704-03-netfilter-nft_flow_offload-fix-offload-with-pppoe-vl.patch [6]

Manually rebased:
generic/hack-5.15/650-netfilter-add-xt_FLOWOFFLOAD-target.patch

Other patches automatically rebased.

Run-tested:
mvebu/cortexa9 (Turris Omnia)
mediatek/mt7622 (Belkin RT3200)
ramips/mt7621 (Redmi AC2100, after reverting 0bc794a66845738eef7eeb7e13877ffb8aec17f7)

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.41&id=99858114a3b2c8f5f8707d9bbd46c50f547c87c0
[2] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.42&id=88b937673b3552d54da20f648e61a123f4c1fa67
[3] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.42&id=5f4197a020c049a59ea7907c31f9ab037dcefefe
[4] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.42&id=7613dcaceee281973145588f4244f2f78ef85b7f
[5] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.42&id=f96b2e06721249ebf8da3254cfef29dcb6583948
[6] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.42&id=b329889974aed47e1167c85653c07097013e01a7

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by graysky2** [comment]
```
Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200
```

**Comment by rsalvaterra** [comment]
**WARNING: 5.15.42 is broken**. I just pushed so @nbd168 can take a look at the fload offloading patch.

**Comment by jospezial** [comment]
5.15.42 released

**Comment by rsalvaterra** [comment]
> 5.15.42 released

I know, but It's a non-trivial bump.

**Comment by ldir-EDB0** [comment]
and now 5.15.43 released a few hours later - what fun!

**Comment by rsalvaterra** [comment]
> and now 5.15.43 released a few hours later - what fun!

Aw, WTF…! I was just about getting .42 fixed! Oh, well… 🙄

**Comment by graysky2** [comment]
```
Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200
```

**Comment by rsalvaterra** [comment]
Has anyone tested this pull request on MT7621 devices? My Redmi AC2100 is having a bad time with .42+, doesn't boot at all (and I still haven't soldered a serial header on it)…

**Comment by castiel652** [comment]
> Has anyone tested this pull request on MT7621 devices? My Redmi AC2100 is having a bad time with .42+, doesn't boot at all (and I still haven't soldered a serial header on it)…

You might have run into this? 
#9905

**Comment by rsalvaterra** [comment]
> You might have run into this? #9905

It does seem to be the case, thanks for the heads up. If the 22.03 branch is also affected, it means some -stable backported patch broke it, since I've been running master builds with Linux 5.15, and 22.03 is based on 5.10.

**Comment by jospezial** [comment]
5.15.43 Built before todays rebase.
```
Build system: linux x86_64
Build tested for and run tested on: Arcadyan VGV7510KW22 (o2 Box 6431)
```

**Comment by DragonBluep** [comment]
I have tested the MT7621 devices, ZTE E8820 V2 (SPI Flash, FIT image) and RAISECOM MSG1500 (NAND Flash, without lzma-loader) both work normally.

**Comment by t-8ch** [comment]
```
Build system: linux x86_64
Build tested for and run tested on: Linksys EA6350v3
```

**Comment by Boos4721** [comment]
5.15.44 released
iShot_2022-05-30_18 07 53

**Comment by graysky2** [comment]
```
Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200
```

**Comment by graysky2** [comment]
@rsalvaterra - Thanks for the heads-up.  https://github.com/openwrt/openwrt/commit/f0bcccc4a54e7512a2901a3f030925e45434ec9c

**Comment by rsalvaterra** [comment]
> I'm a bit hampered in my debugging at the moment, but as-is, this PR on its own (without the corresponding 5.10.x pull) breaks building targets using kernel v5.10 (seen on ath79 and x86_64).
> 
> ```
> Package kmod-wireguard is missing dependencies for the following libraries:
> libblake2s.ko
> ```
It's expected. The removal of the kernel module affects both kernels, so this and the 5.10 pull request should be merged at the same time.

**Comment by graysky2** [comment]
```
Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200
```

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in ed1536e0b6b7f2aeea6881632b89b269d27ff7ce, 2454342e068335ec0a52b2304e83f5f62f6b6b2d, 1f20e70a5cd26a41dbccea9401e2704632953ffe, 79e7a2552e89d762a1a2a9bcf327427738f5d238 and fbf6992f2b8960cbca36cd652bcdc71d69931076.

**Pull request closed without merging**
