### PR TITLE
tools: fix compilation with older glibc

### PR DESCRIPTION
**Pull request by neheb**
Alternative to https://github.com/openwrt/openwrt/pull/16449

ping @robimarko @zxlhhyccc

### CODE REVIEW

**Comment by neheb** [comment]
more autoreconf trash.

ping @mcprat

**Comment by zxlhhyccc** [comment]
@neheb 
````
bootstrap: running: /__w/openwrt/openwrt/openwrt/staging_dir/host/share/gnulib/gnulib-tool --no-changelog --avoid=dummy --libtool --macro-prefix=GL --with-tests --tests-base=gnulib-tests --aux-dir=build-aux --m4-base=m4 --local-dir=gl --local-dir=gl-mod/bootstrap --import announce-gen bootstrap...
gnulib-tool: warning: module bootstrap doesn't exist
gnulib-tool: warning: module extract-trace doesn't exist
gnulib-tool: warning: module inline-source doesn't exist
====== Make errors from logs/tools/e2fsprogs/compile.txt ======
  : ; \
fi
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/host/e2fsprogs-1.47.0/po'
making install in scrub
make[4]: Entering directory '/__w/openwrt/openwrt/openwrt/build_dir/host/e2fsprogs-1.47.0/scrub'
	MKDIR_P /etc/cron.d
	MKDIR_P /__w/openwrt/openwrt/openwrt/staging_dir/host/lib/e2fsprogs
	INSTALL /etc/cron.d/e2scrub_all
	MKDIR_P /__w/openwrt/openwrt/openwrt/staging_dir/host/bin /__w/openwrt/openwrt/openwrt/staging_dir/host/share/man/man8 /__w/openwrt/openwrt/openwrt/staging_dir/host/etc
/__w/openwrt/openwrt/openwrt/staging_dir/host/bin/install: cannot remove '/etc/cron.d/e2scrub_all': Permission denied
make[4]: *** [Makefile:451: install-crond] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/host/e2fsprogs-1.47.0/scrub'
make[3]: *** [Makefile:444: install-progs-recursive] Error 1
make[3]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/host/e2fsprogs-1.47.0'
make[2]: *** [Makefile:51: /__w/openwrt/openwrt/openwrt/staging_dir/host/stamp/.e2fsprogs_installed] Error 2
````

**Comment by robimarko** [comment]
Well, it makes the detection issue go away but:
```
making all in lib/et
make[5]: Entering directory '/openwrt/openwrt/build_dir/host/e2fsprogs-1.47.0/lib/et'
	CC error_message.c
make[5]: I.: Command not found
Makefile:380: recipe for target 'error_message.o' failed
make[5]: [error_message.o] Error 127 (ignored)
	CC et_name.c
make[5]: I.: Command not found
Makefile:380: recipe for target 'et_name.o' failed
make[5]: [et_name.o] Error 127 (ignored)
	CC init_et.c
make[5]: I.: Command not found
Makefile:380: recipe for target 'init_et.o' failed
make[5]: [init_et.o] Error 127 (ignored)
	CC com_err.c
make[5]: I.: Command not found
Makefile:380: recipe for target 'com_err.o' failed
make[5]: [com_err.o] Error 127 (ignored)
	CC com_right.c
make[5]: I.: Command not found
Makefile:380: recipe for target 'com_right.o' failed
make[5]: [com_right.o] Error 127 (ignored)
	GEN_LIB libcom_err.a
ar: error_message.o: No such file or directory
Makefile:406: recipe for target 'libcom_err.a' failed
make[5]: *** [libcom_err.a] Error 1
```

Though its likely completely unrelated.

BTW, I am not sure that your change is fully valid as it changes the desired e2fsprogs behaviour of actually trying to link with the library to test for the symbol and instead just finds the library.

**Comment by mcprat** [comment]
would `UUID_LIBS` just be undefined?

**Comment by mcprat** [comment]
`configure` is patched in-place (not good practice, we should get rid of this...)

see `tools/e2fsprogs/patches/003-no-crond.patch`

a possible alternative would be a configure arg, but I didn't try it yet
`--with-crond-dir=no`

**Comment by zxlhhyccc** [comment]
@robimarko How do I use the compile configuration to bring glibc into the build environment?

**Comment by neheb** [comment]
Applied https://github.com/openwrt/openwrt/pull/16500 . Let's see if this will work.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
