### PR TITLE
ipq40xx: add DSL support for 6.1 kernel

### PR DESCRIPTION
**Pull request by dhewg**
This was only compile time tested in combination with #13294

I'm not sure if I get around to actually runtime test that soonish, does anyone have a spare fritzbox 75x0 to see if the DSL line is working on 6.1?

### CODE REVIEW

**Comment by Djfe** [comment]
Thanks for the patch, I'm currently building.

**Comment by dhewg** [comment]
DSL works on 6.1, but there's a runtime  warning:
`memcpy: detected field-spanning write (size 4) of single field "pDestPtr" at build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dsl_cpe_mei-ugw_8.5.2.10/src/drv_mei_cpe_msg_process.c:3570 (size 2)`

Which is correct, it writes to `unsigned short index;`. It looks like the extra 2 bytes of the memcpy would just write to the struct's padding? cc @janh before I do something stupid ;)

**Comment by janh** [comment]
@dhewg: A few lines above, there is this comment:
```
   /*
      modem message
      - index and length fields are part of the appl. payload
   */
```

I assume this means that `pUserMsg->pPayload` contains the index and length, followed by the actual payload. This matches the order of the fields in `CMV_STD_MESSAGE_HEADER_T`, which is also followed by a `CMV_STD_MESSAGE_PAYLOAD_T` in `CMV_STD_MESSAGE_T`.

So it looks like it this code assumes that the compiler doesn't add any padding to `CMV_STD_MESSAGE_HEADER_T` and `CMV_STD_MESSAGE_T`. But it should work as long as that is actually the case.

**Comment by dhewg** [comment]
I read it the same way, but I'm not convinced yet that this is what is actually happening.

Correct me if I'm wrong, but:
I don't see the relevant struct's marked as packed. Without it there'd be padding between each of the struct's `short`'s. In which case it'd be memcpying 2 byte of `index` and 2 bytes of padding on a 32bit host, so excluding `length` as indented?

**Comment by dhewg** [comment]
For the record, this is the struct:
```
typedef struct cmv_std_message_header_s
{
   /** Mailbox Code */
   unsigned short mbxCode;
   /** Function/Direction Opcode */
   unsigned short fctCode;
   /** payload control fields: size, msg index */
   unsigned short paylCntrl;
   /** IFX msgId / CMV address, group */
   unsigned short MessageID;
   /** CMV index */
   unsigned short index;
   /** CMV length */
   unsigned short length;
} CMV_STD_MESSAGE_HEADER_T;
```

**Pull request merged**
