### PR TITLE
kernel: 5.10: fix kmod- package builds

### PR DESCRIPTION
**Pull request by lipnitsk**
By popular demand, breaking this change out of https://github.com/openwrt/openwrt/pull/3885

### CODE REVIEW

**Comment by anomeome** [comment]
I made a _diiffconfig_ from your above config, removed a few extraneous lines resulting in [configdiff](https://termbin.com/bamm), generated a config, make dirclean, and successfully built an image. So far, so good.

Took an existing 5.10 [configdiff](https://termbin.com/pomq) which I use, the only thing missing is WG, make dirclean (although I do not believe the toolchain should play a part here), successfully built an image. Go into make menuconfig and turn on _luci-app-wireguard_ and it fails with the above error.

Yesterday I played around with removing possible cyrpto bits that I thought might conflict in my _real config_, afalg, devcrpto, openssl, ... Never got to anyting that would allow things to build

**Comment by blocktrron** [comment]
Looks good. However I'd propose to add a commit which adds a dependency on 5.4 for the wireguard package, so all kmods are built successfully. What do you think?

**Comment by lipnitsk** [comment]
@blocktrron is that what you had in mind? Take a look.

**Comment by adschm** [comment]
> wireguard-compat: don't build on Linux 5.10

Prefix should just be "wireguard:"

I suggest to rephrase the commit message to explain why the package is not used for 5.10 ...

**Comment by lipnitsk** [comment]
@adschm done

**Comment by blocktrron** [comment]
Merged to my staging tree. I'll do some build-tests and merge afterwards.

Ping me via E-Mail in case i don't get back to this within the next 1-2 days.

**Comment by blocktrron** [comment]
Merged, thanks!

**Pull request closed without merging**
