### PR TITLE
kernel: bump 5.4 to 5.4.57

### PR DESCRIPTION
**Pull request by graysky2**
This PR is a blend of several kernel bumps authored by ldir taken from his
staging tree. In total, 5 patches deleted, several others merged, and the
rest adjusted by `update_kernel.sh`

Summary, deleted:
```
 022-v5.8-mtd-rawnand-brcmnand-correctly-verify-erased-pages.patch
 024-v5.8-mtd-rawnand-brcmnand-fix-CS0-layout.patch
 742-v5.5-net-sfp-add-support-for-module-quirks.patch
 743-v5.5-net-sfp-add-some-quirks-for-GPON-modules.patch
 641-sch_cake-fix-IP-protocol-handling-in-the-presence-of.patch
```
Build system: x86_64
Run-tested: Netgear R7800 (ipq806x)

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by anomeome** [comment]
Does not build for me with target _mvebu_, [error](https://termbin.com/r3pk). The same issue occurred with the .53 submission to the ML.

**Comment by 1Jeff1** [comment]
> Does not build for me with target _mvebu_, [error](https://termbin.com/r3pk). The same issue occurred with the .53 submission to the ML.

It fail in mvebu because this 2 patches are already upstream 
`target/linux/generic/backport-5.4/742-v5.5-net-sfp-add-support-for-module-quirks.patch
 target/linux/generic/backport-5.4/743-v5.5-net-sfp-add-some-quirks-for-GPON-modules.patch`
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/phy/sfp-bus.c?h=linux-5.4.y&id=17918c99abc1b499ba146b5a36ad02bc64ca6a7d
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/phy/sfp-bus.c?h=linux-5.4.y&id=370cc95c00aefdcdfb5b63ccc904e2aaaf12f90e

**Comment by graysky2** [comment]
@1Jeff1 - How peculiar, for me, it passed the `update_kernel.sh -v -u 5.4` test.  Thank you for sharing the two links.  Let me verify again and I will rebase if as needed.

**Comment by anomeome** [comment]
Yes, it is those two patches, when the ML .53 failed on me, I tried a move to .54 with:
`update_kernel.sh --update --verbose 5.4 5.4.54`
which failed and I reconciled back to the kernel changelog.
I was attempting to make the point that something that is as _carte blanche_ such as this, really should undergo a buildbot style of test, and also that since you piggy backed off the previous attempt, the oversight was not on you.

**Comment by graysky2** [comment]
@anomeome - I don't want to point fingers, I just want to get this right.  I am re-running the script now.  It is currently iterating through the uarches and is currently on ipq40xx so it passed mvebu.  Stay tuned :D

**Comment by anomeome** [comment]
I was not trying to point fingers, in fact I was attempting to do the exact opposite, while indicating where / how things went wrong. Ain't no big.

**Comment by graysky2** [comment]
No problem, community effort!

**Comment by graysky2** [comment]
@anomeome - Please try to compile now that I rebased incorporating @1Jeff1 's suggestion and re-re-running `update_kernel.sh`.

* Minimal config built fine.
* My personal config built fine and I am booted into it now for over an hours without any issues.

**Comment by anomeome** [comment]
compile / test - mvebu / mamba

```
OpenWrt SNAPSHOT, r14017-c90db26e05
root@mamba:/# uname -a
Linux mamba 5.4.55 #0 SMP Sun Aug 2 16:10:06 2020 armv7l GNU/Linux
```

**Comment by guidosarducci** [comment]
> I was attempting to make the point that something that is as _carte blanche_ such as this, really should undergo a buildbot style of test, and also that since you piggy backed off the previous attempt, the oversight was not on you.
>
Yes, 100% this.  Moreover, there should be some variety in run time testing as with the build testing. Currently we have several virtual targets available to do this: x64_64/32, arm 64/32, and mips 64/32 be/le.

**Comment by graysky2** [comment]
Updated for 5.4.56

**Pull request closed without merging**
