### PR TITLE
build,wpa-cli: fix for wpa-cli package not being built

### PR DESCRIPTION
**Pull request by cotequeiroz**
[It was brought to my attention](https://github.com/openwrt/openwrt/commit/67f9245ee57eaf47093275670b227c7911f485d4#commitcomment-59339612) that the wpa-cli package was not getting built after #4728.

19aae94 made it so that all packages without a defined `VARIANT` built in the same Makefile as packages with a defined `VARIANT` get built only with the first `VARIANT` in the list of menuconfig-selected package variants.  If all variants are selected, the first one defined is used.

Hostapd only builds wpa-cli if the variant has supplicant support (variants that are not hostapd*):
https://github.com/openwrt/openwrt/blob/67f9245ee57eaf47093275670b227c7911f485d4/package/network/services/hostapd/Makefile#L652-L653

The first variant that gets built with CONFIG_ALL is hostapd-full-internal, so wpa-cli will not have its install section:
```
Makefile:710: WARNING: skipping wpa-cli -- package has no install section
```
If we just changed the order of the packages, then we would hit a problem with hostapd-utils, which not built for supplicant-only packages.

To circumvent this, the fist commit restores the original behavior of building a package for every defined variant if they have 
```
VARIANT:=*
````
The second commit then changes wpa-cli and hostapd-utils packages to have `VARIANT:=*`.

I've done a quick search through the packages to spot any other package that uses that logic, but found none that defined packages without a defined `VARIANT` that had sections guarded by `BUILD_VARIANT` conditionals.

### CODE REVIEW

**Comment by cotequeiroz** [comment]
ping @nbd168

**Comment by neheb** [comment]
That prepare txt file looks accidentally committed?

**Comment by cotequeiroz** [comment]
Sure was.  Thanks for pointing it out.  I have fixed it.

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master.

**Pull request closed without merging**
