### PR TITLE
[RFT] realtek: crypto driver (v6)

### PR DESCRIPTION
**Pull request by plappermaul**
Realtek devices like the RTL838X and RTL930X series hava a crypto engine built in. It supports AES/3DES/DES/SHA1/MD5. Let's try to unleash it's powers. This commit is in alpha state with the following restrictions:

- only SHA1 & MD5 implemented
- only works on RTL838X (coherency issues on other devices)
- IRQ handling takes too long
- debugging messages all over the code

### CODE REVIEW

**Comment by z-e-r-o** [comment]
At patch 122-04 at all 3 "if (!of_machine_is_compatible("qcom,ipq8064")" the closing ")" is missing. This will crash too.

**Comment by plappermaul** [comment]
v2 posted. Changes since version 1:

- IRQ data handling split into tasklet
- reduced scope of ring buffer lock
- preparation for 32 byte line caches (RTL9302)
- use DMA kernel functions for writeback

**Comment by plappermaul** [comment]
v3

- initial support for ECB(AES) 
- works on RTL9302

party in the phone booth ...

**Comment by plappermaul** [comment]
v4

- CBC(AES) and CTR(AES) support
- no more size limits for AES

**Comment by plappermaul** [comment]
v5 Bugfixes and code cleanup.

**Comment by plappermaul** [comment]
v6 posted

- further code cleanup
- removed all debugging messages

**Comment by plappermaul** [comment]
@svanheule @oliv3r This PR ist getting into a stage where I must decide how to mainline it. Be it OpenWrt or upstream kernel. Sander already mentioned that he might not be the right one. Nevertheless I invite you to participate in the process. Feel free to make a review of the current version. Drop a note too in case you have no time or no interest

**Comment by svanheule** [comment]
Continued upstream: https://lore.kernel.org/linux-crypto/20221013184026.63826-1-markus.stockhausen@gmx.de/

**Pull request closed without merging**
