### PR TITLE
octeon: ubnt-edgerouter: fix sysupgrade config backup/restore

### PR DESCRIPTION
**Pull request by sur5r**
er is missing from platform_copy_config() and octeon_move_config(), so config is lost on every sysupgrade.

Tested using local patching combined with image generator.

To fix this in production, `base-files` would need to contain a fixed version of `platform.sh` before doing a sysupgrade to a fixed version. Is this possible with the way OpenWRT does releases and package updates?

### CODE REVIEW

**Comment by robimarko** [comment]
I am a bit confused, isnt the device compatible used for the model identifier?

Cause, otherwise ER Lite and USG are probably broke as well

**Comment by sur5r** [comment]
I'm not sure I understand your confusion. `$(board_name)` resolves to `cat /tmp/sysinfo/board_name` (see https://github.com/openwrt/openwrt/blob/main/package/base-files/files/lib/functions.sh#L522).

`/tmp/sysinfo/board_name` gets filled by `do_sysinfo_octeon()` from https://github.com/openwrt/openwrt/blob/main/target/linux/octeon/base-files/lib/preinit/01_sysinfo which results in `er` for this board.
It explicitely overrides what `do_sysinfo_generic()` from https://github.com/openwrt/openwrt/blob/main/package/base-files/files/lib/preinit/02_sysinfo

The comments hint that the whole platform is not really clean regarding names so we have to live with what we have.

**Comment by sur5r** [comment]
Digging deeper:

- `ubnt,usg` gets handled by `02_sysinfo` and has an OpenWRT supplied DTS. So that checks out.
- `erlite` gets overridden as well, not sure whether it uses a passed DT or the one present in Linux upstream

**Comment by robimarko** [comment]
That is what is confusing me as well, ERLite probably has the same issue, USG since it has its own DTS then it will pick up the model name from it.

**Comment by sur5r** [comment]
erlite booted with `openwrt-23.05.4-octeon-generic-ubnt_edgerouter-lite-initramfs-kernel.bin`:

```
# cat /proc/cpuinfo 
system type		: UBNT_E100 (CN5020p1.1-500-SCP)
machine			: Unknown
processor		: 0
cpu model		: Cavium Octeon+ V0.1
BogoMIPS		: 1000.00
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 64
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa			: mips1 mips2 mips3 mips4 mips5 mips32r1 mips32r2 mips64r1 mips64r2
ASEs implemented	:
Options implemented	: tlb 4kex octeon_cache 32fpr prefetch mcheck ejtag llsc rixi lpa vtag_icache perf_cntr_intr_bit nan_legacy nan_2008 perf
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

processor		: 1
cpu model		: Cavium Octeon+ V0.1
BogoMIPS		: 1000.00
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 64
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa			: mips1 mips2 mips3 mips4 mips5 mips32r1 mips32r2 mips64r1 mips64r2
ASEs implemented	:
Options implemented	: tlb 4kex octeon_cache 32fpr prefetch mcheck ejtag llsc rixi lpa vtag_icache perf_cntr_intr_bit nan_legacy nan_2008 perf
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 1
VCED exceptions		: not available
VCEI exceptions		: not available
```

Also, dmesg reports:

```
[    0.000000] Using internal Device Tree.
```

I guess this is necessary since `/proc/device-tree/compatible` contains just `cavium,octeon-3860` which is too broad.

I also tested sysupgrade and the config gets restored as expected. So `erlite` is fine as is.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
