### PR TITLE
ramips: fixed wifi support on Unielec U7621-06

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Nicholas Smith <nicholas.smith@telcoantennas.com.au>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://lede-project.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by nickberry17** [comment]
This commit has the wrong values.  It should actually be this commit: 00e875ace84666c4409dcd3f64621be4a9565d0c

**Comment by bobafetthotmail** [comment]
the PR won't be accepted in this state, see this paragraph of the wiki to remove wrong commits from it https://openwrt.org/submitting-patches#squashing_commits

**Comment by nickberry17** [comment]
Thank you, I will take care of it

**Comment by nickberry17** [comment]
I believe I have squashed the commits

**Comment by neheb** [comment]
Why does it go from mt76@1 to @2?

**Comment by pepe2k** [comment]
@nickberry17 please have a read [original commit with support for this board](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=46ab81e405d238e95071d7d56a0f07bb51fc8cb3), especially this part:

"2. The manufacturer offers five different wireless cards with MediaTek chipsets, based on MT76x2, MT7603 and MT7615. Images of the board all show that the miniPCIe slots are dedicated to specific Wi-Fi cards. **However, the slots are generic.**"

I'm using this board with mt76 and ath9k cards.

Cheers,
Piotr

**Comment by nickberry17** [comment]
Thanks Piotr,

So what I have done is actually hard coding the slots to expect to have mt76xx wifi chips?

**Comment by CHKDSK88** [comment]
mt76 mpcie cards work without any info in dtc.

**Comment by mkresin** [comment]
> So what I have done is actually hard coding the slots to expect to have mt76xx wifi chips?

More or less. And you added a frequency limit which might not apply to the used miniPCIe cards.

I'm going to close the PR, as the used wireless cards are not a fixed configuration.

**Pull request closed without merging**
