### PR TITLE
nftables/libnftnl: update

### PR DESCRIPTION
**Pull request by PolynomialDivision**
see commit

Runtested: Belkin RT3200 (OpenWrt Master)

@jow-

### CODE REVIEW

**Comment by aparcar** [comment]
I'd call it "clean up" not "fix" since there is not technical issue

**Comment by PolynomialDivision** [comment]
> I'd call it "clean up" not "fix" since there is not technical issue

Updatet :)

**Comment by PolynomialDivision** [comment]
I also updatet libnftl ( @sbyx ) because I now bumped nftables to 1.0.4.

Run-tested on Belkin RT3200 OpenWrt Master.

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
