### PR TITLE
ustream-ssl:  openssl 1.1 compatibility

### PR DESCRIPTION
**Pull request by cotequeiroz**
Patch to compile ustream-ssl with openssl-1.1.0.

### CODE REVIEW

**Comment by neheb** [comment]
Please send these patches to the mailing list instead of here. Higher chance of being accepted.

Please avoid TLS_server_method as TLS versions 1.0 and 1.1 are useless for server operation. 1.0 and 1.1 are for older clients, XP, iOS < 6, Android < 4.4, etc...

Do you have a use case for this?

**Comment by neheb** [comment]
Ah OK. Make sure the patches apply directly to ustream-ssl and not OpenWrt as patch files.

**Comment by neheb** [comment]
I just tested this. I get these errors: 

/home/mangix/devstuff/openwrt/build_dir/target-mipsel_24kc_musl/ustream-ssl-openssl/ustream-ssl-2018-04-30-527e7002/ustream-openssl.c: In function '__ustream_ssl_context_new':
/home/mangix/devstuff/openwrt/build_dir/target-mipsel_24kc_musl/ustream-ssl-openssl/ustream-ssl-2018-04-30-527e7002/ustream-openssl.c:33:3: error: implicit declaration of function 'SSL_load_error_strings'; did you mean 'ERR_lib_error_string'? [-Werror=implicit-function-declaration]
   SSL_load_error_strings();
   ^~~~~~~~~~~~~~~~~~~~~~
   ERR_lib_error_string
/home/mangix/devstuff/openwrt/build_dir/target-mipsel_24kc_musl/ustream-ssl-openssl/ustream-ssl-2018-04-30-527e7002/ustream-openssl.c:34:3: error: implicit declaration of function 'SSL_library_init'; did you mean 'SSL_in_init'? [-Werror=implicit-function-declaration]
   SSL_library_init();
   ^~~~~~~~~~~~~~~~
   SSL_in_init
/home/mangix/devstuff/openwrt/build_dir/target-mipsel_24kc_musl/ustream-ssl-openssl/ustream-ssl-2018-04-30-527e7002/ustream-openssl.c:59:2: error: implicit declaration of function 'SSL_CTX_set_ecdh_auto'; did you mean 'SSL_CTX_set_dh_auto'? [-Werror=implicit-function-declaration]
  SSL_CTX_set_ecdh_auto(c, 1);
  ^~~~~~~~~~~~~~~~~~~~~
  SSL_CTX_set_dh_auto
cc1: all warnings being treated as errors

Note that my OpenSSL build has deprecated functions disabled.

**Comment by cotequeiroz** [comment]
I did not go that far to make the changes. My thought was to minimize the differences.

**Comment by dissent1** [comment]
Not applicable anymore

**Comment by neheb** [comment]
I like the mbedTLS changes. Please get rid of 3DES though. XP is EOL.

I would post the mbedTLS changes on the mailing list for faster merging.

**Comment by cotequeiroz** [comment]
I've made some changes to the security options used in the library, and made them more uniform across all supported libraries (mbedtls, wolfssl, openssl 1.0.2 & openssl 1.1.0).
The biggest, and probably most controversial change is in the ciphersuite ordering.  Here's my reasoning:
The first priority was key exchange, to provide forward-security.
Then comes encryption algorithm.  AEAD ciphers are chosen first.  They are chacha20-poly1305 (256 bits), and aes-gcm (128 & 256 bits variants). Among the three, I've selected chacha20-poly1305 because of higher performance and strength.  Here's a table generated by `openssl speed` on ramips:
```
((openssl speed -evp chacha20-poly1305 | egrep "^(type|chacha)") && (openssl speed -evp aes-128-gcm && openssl speed -evp aes-256-gcm) | egrep "^aes") 2>/dev/null
type                 16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
chacha20-poly1305     6873.30k    10734.22k    12217.75k    12613.07k    12769.39k    12665.00k
aes-128-gcm           3759.88k     4280.96k     4415.66k     4437.79k     4456.12k     4436.88k
aes-256-gcm           3408.83k     3738.10k     3838.52k     3841.90k     3864.31k     3882.17k
```
I'm assuming most routers running openwrt are not going to have AES-capable chips.  If we were to run the benchmark in a newer server, I'd bump AES-256 to the top.  This is what it looks like in my x86_64:
```
type                 16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
chacha20-poly1305   206412.13k   400740.77k   788942.85k   869130.38k   899400.83k   893596.97k
aes-128-gcm         283449.15k   730408.60k  1074886.58k  1176372.95k  1232831.03k  1245781.87k
aes-256-gcm         238760.79k   660843.45k   967903.44k  1071756.62k  1089887.49k  1089552.89k
```
This could be added as an option, or selected automatically depending on architecture.  The difference is more dramatic for the lesser capable chips anyway.
You can check your "grade" at https://www.ssllabs.com/ssltest/.  You'll get an A on openssl and mbedtls, and an A- with wolfssl--the minus is due to lack of secure renegotiation.  There's an option to enable it, but wolfssl does not recommend using it.

**Comment by cotequeiroz** [comment]
I forgot to mention 3DES.  I thought about taking it out completely, but if you leave it at the bottom of the chain in client-mode only, it won't be selected unless it is the only option.  Here's an example of a necessary site that uses 3DES only (it's the Brazilian Federal Revenue Agency, by the way):
https://www.ssllabs.com/ssltest/analyze.html?d=www.receita.fazenda.gov.br

**Comment by neheb** [comment]
That link bring more questions than answers. I overlooked that it was client mode only.

As far as hardware acceleration is concerned, most targets do not have it. The ones that do are powerful hardware anyway. It would be nice to have chacha20 by default. I don't know which libraries do and don't support it.

**Comment by shawnchain** [comment]
Got same error while building my own packages with latest lede-17.01-branch-built sdk.
Any hints? Thanks!

```
17.01/lede-sdk-ramips-mt7620_gcc-5.4.0_musl-1.1.16.Linux-x86_64/build_dir/target-mipsel_24kc_musl-1.1.16/ustream-ssl-cyassl/ustream-ssl-2018-05-22-5322f9db/ustream-openssl.c:53:2: error: implicit declaration of function 'SSL_CTX_set_ecdh_auto' [-Werror=implicit-function-declaration]
  SSL_CTX_set_ecdh_auto(c, 1);
  ^
cc1: all warnings being treated as errors
CMakeFiles/ustream-ssl.dir/build.make:110: recipe for target 'CMakeFiles/ustream-ssl.dir/ustream-openssl.c.o' failed
make[5]: *** [CMakeFiles/ustream-ssl.dir/ustream-openssl.c.o] Error 1
```

**Comment by cotequeiroz** [comment]
I think it can be fixed by changing the #if just above it.  Since `SSL_CTX_set_ecdh_auto` is a macro, and has been deprecated in 1.1.0, we can assume it will always be a macro.  So we can check for it directly, instead of using `CYASSL_OPENSSL_H_`, which may not be defined for you.  I'll try it here with current master, and repost the commit if it works.  I'll try with lede 17.01 next, but if you want to help me out, or if you're anxious ;-), just change line 196 of the patch to: 
```
#if defined(SSL_CTX_set_ecdh_auto) && OPENSSL_VERSION_NUMBER < 0x10100000L
```
Let me know if it works.
Cheers,
Eneas

**Comment by cotequeiroz** [comment]
I had this out of sync with my repo.  Sorry.  Now you have the correct version, with the fix above.

**Comment by shawnchain** [comment]
@cotequeiroz it works. But there is no patches under 17.01 branch for ustream-ssl indeed abd I tried your latest changes from your fork and commented out the libustream-wolfssl package to make the compile success.

Currently my solution will be skip the ustream-openssl package before the issue is fixed on 17.01 branch.

**Comment by cotequeiroz** [comment]
This has been merged upstream.

**Pull request closed without merging**
