### PR TITLE
[RFT] bcm63xx: use generic diag.sh

### PR DESCRIPTION
**Pull request by adschm**
This commit removes the target-specific diag.sh script. This way, the
generic one is used for the target, which uses DT-aliases to specify the
LEDs used.

Though generic diag.sh allows to use different LEDs to indicate different
states, this just moves the old assignment and does not try to "improve"
the assignment by using additional colors.

For the few cases where status_led2 was used in old diag.sh, only the
primary LED was migrated.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
@Noltari FYI. Could you run-test this on any of the affected devices?

**Comment by Noltari** [comment]
> @Noltari FYI. Could you run-test this on any of the affected devices?

Run-tested on Comtrend AR-5387un and it works as expected :).
BTW, can we also remove the default-state from the power led nodes?
https://github.com/openwrt/openwrt/blob/master/target/linux/bcm63xx/dts/bcm6328-comtrend-ar-5387un.dts#L48

Thanks!

**Comment by adrianschmutzler** [comment]
> BTW, can we also remove the default-state from the power led nodes?
> https://github.com/openwrt/openwrt/blob/master/target/linux/bcm63xx/dts/bcm6328-comtrend-ar-5387un.dts#L48

I personally like that default-on, because it will be an early indication that something "is going on" during boot very early. However, people expressed a different opinion when changing this for kirkwood: https://github.com/openwrt/openwrt/pull/2764#issuecomment-590411608

So, I'd be interested in your reasoning why to remove it as well.

**Comment by Noltari** [comment]
> > BTW, can we also remove the default-state from the power led nodes?
> > https://github.com/openwrt/openwrt/blob/master/target/linux/bcm63xx/dts/bcm6328-comtrend-ar-5387un.dts#L48
> 
> I personally like that default-on, because it will be an indication that something "is going on" during boot very early. However, people expressed a different opinion when changing this for kirkwood: [#2764 (comment)](https://github.com/openwrt/openwrt/pull/2764#issuecomment-590411608)
> 
> So, I'd be interested in your reasoning why to remove it as well.

Actually I didn't think about not having the led on before preinit, so let's keep the default-on values.

**Comment by adrianschmutzler** [comment]
Okay, thanks for quick feedback, then I will just merge this PR relatively soon.

**Comment by adrianschmutzler** [comment]
Merged. If somebody spots an error or wants to improve the support of a device by using different LEDs now, feel free to propose a new PR/patch for that.

**Pull request closed without merging**
