### PR TITLE
[RFT] ath79/mikrotik: minor cleanup

### PR DESCRIPTION
**Pull request by adschm**
This does minor cleanup to the mikrotik subtarget:
- Fix the network setup on qca953x
- Introduce a function for setting ath9k caldata

@rogerpueyo @f00b4r0 @SvenRoederer

### CODE REVIEW

**Comment by f00b4r0** [comment]
Looks good to me

**Comment by adschm** [comment]
Merged the ath9k patch, the ethernet patch should see some actual testing.

**Comment by rogerpueyo** [comment]
Hi @adschm ,

I tested the patch on the MikroTik LHG 2: it works correctly.

Thanks for your cleanup.

**Comment by adschm** [comment]
Thanks, merged.

**Pull request closed without merging**
