### PR TITLE
uhttpd: drop relevant options if ipv6 is not supported

### PR DESCRIPTION
**Pull request by rosysong**
Signed-off-by: Rosy Song <rosysong@rosinson.com>

### CODE REVIEW

**Comment by jow-** [comment]
Why is this needed?

**Comment by rosysong** [comment]
This may result in daemon.err in 'logread'.

**Comment by jow-** [comment]
Does it prevent uhttpd from starting up? If not I tend to NAK this PR. Personally I consider CONFIG_IPv6=n to be an unsupported configuration nowadays.

**Comment by rosysong** [comment]
@jow- Currently, this PR does not prevent uhttpd from starting up, but I may lead to misunderstandings and leave a hidden dangers in the future or the environment only support ipv4.

**Comment by rosysong** [comment]
@jow-  Another issue found which may lead to crash on uhttpd, logread output :

**daemon.err uhttpd[1042]: luci: accepted login on / for root from 192.168.1.184**

**Comment by rosysong** [comment]
@jow- @dedeckeh  I updated my commit, please check it again, it seems safer than before ?? :-)

**Comment by ynezz** [comment]
>  I updated my commit, please check it again, it seems safer than before

Nope, your IPV6 address detection logic is still flawed (handling of fdf8:f53b:82e4::53 for example), so if there's issue with uhttpd, please fix it there instead as suggested already, instead of this hacky workarounds in init scripts.

**Pull request closed without merging**
