### PR TITLE
tools: add ninja and use for CMake

### PR DESCRIPTION
**Pull request by neheb**
Ninja is an alternative to GNU Make that does native parallelization, resulting in typically 5-10% faster compiles.

CMake has native support for it.

While Ninja is typically paired with meson, CMake can also take advantage of it.

First two patches were from @ja-pa 's submission to get meson in here.

Tested this with host and target builds.  Feedback is appreciated.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Hi, first two commit don't have a description. I'm aware that this is mostly done in commit 3, but still it would be good to also have some explanation about the package before.
Maybe even just copy the relevant parts of commit 3 there ...

**Comment by neheb** [comment]
Those patches were just applied with curl | git am. But sure. I'll update that eventually.

**Comment by ynezz** [comment]
BTW just wanted to actually check how faster Ninja is and how does it look like, but this PR doesn't build https://gitlab.com/ynezz/openwrt/-/jobs/493640055

> native parallelization

What does this mean exactly? If I read it correctly, main advantage of Ninja are incremental builds of large codebases of C++ projects. OpenWrt is about a lot of small C projects, where you usually rebuild from scratch, no incremental compilation (putting development and debugging aside).

> resulting in typically 5-10% faster compiles.

Ok, how was that measured? What host, what did you build test actually?

If those 5-10% numbers are true, is this relatively small speedup worth it? I mean, you're introducing new tool which always means increased maintenance and support efforts, very likely sucking away already scarce human resources which could be used for better in other parts of the project.

We're all used to parsing of (C)Make output, errors and quirks. We're using (C)Make in our personal/professional projects as well, being pragmatic in order to maintain and sometime improve are (C)Make skills. Now with Ninja, we would get different build system, with different behavior, output, quirks and we would probably use it only solely inside of OpenWrt. Sorry, but it doesn't make much sense to me.

BTW it seems like Ninja has increased RAM [usage](https://github.com/valhalla/valhalla/pull/2084#issuecomment-560759196) as well.

**Comment by neheb** [comment]
Weird. ninja should be built before cmake in tools. It works locally.

Ninja will get introduced to the tree anyway.; It's a dependency of meson. It's a question of when, not if. util-linux for example is transitioning to meson.

The speedup is definitely worth it since not every cmake package defines BUILD_PARALLEL.

**Comment by ynezz** [comment]
> Ninja will get introduced to the tree anyway.; It's a dependency of meson. It's a question of when, not if

Ok, it's certainly possible, it might as well be another build system by that time as well. But lets leave that aside until then.

> util-linux for example is transitioning to meson.

Interesting, have some links? Are they going to drop support for other build tools?

**Comment by ynezz** [comment]
> Ninja will get introduced to the tree anyway

And does it mean also, that it should be used instead of Make in CMake based projects?

> The speedup is definitely worth it since not every cmake package defines BUILD_PARALLEL

How is that related? BTW I see only `PKG_BUILD_PARALLEL:=0` set in 4 packages, where only `uci` is using CMake.

**Comment by ynezz** [comment]
> not every cmake package defines BUILD_PARALLEL

Ok, read it wrong. So what about making the PKG_BUILD_PARALLEL:=1 default for CMake packages?

**Comment by ynezz** [comment]
For example in case of `uci`, the current build PKG_BUILD_PARALLEL:=0 is 9s, parallel build PKG_BUILD_PARALLEL:=1 is 7.5s with `time make package/system/uci/{clean,compile} -j9` on `i7-6700HQ`

**Comment by neheb** [comment]
https://github.com/karelzak/util-linux/pull/968

Not every package is as small as uci. Some takes several minutes.

PKG_BUILD_PARALLEL defaults to 0 currently. I've seen some CMake packages that don't benefit from it (crtmpserver in particular which I got rid of in the packages feed). Ninja should solve those issues as well.

**Comment by ynezz** [comment]
> karelzak/util-linux#968

I see `meson: add second build system` nothing about removal of the current build system

**Comment by ynezz** [comment]
So I made an experiment:

* x86/64 [build](https://gitlab.com/ynezz/openwrt/-/jobs/494158223) took *34 minutes 15 seconds* with [`treewide: make CMake build parallel by default`](https://gitlab.com/ynezz/openwrt/-/commit/b0616d99fa91726c6167403ffc02fed2bf2439a1)
* x86/64 [build](https://gitlab.com/ynezz/openwrt/-/jobs/494165833) took *33 minutes 47 seconds* with [`Revert "treewide: make CMake build parallel by default"`](https://gitlab.com/ynezz/openwrt/-/commit/5284825f2f45253aeb76b51bfc720d2f227f2b06)

I simply assume, that the difference is some rounding error caused by the GitLab machinery/infra.

**Comment by neheb** [comment]
Hrm I'm getting similar results:

```
time make -j 12
```

Before:

```
2816.69user 298.91system 7:21.65elapsed 705%CPU (0avgtext+0avgdata 1213060maxresident)k
198192inputs+15278784outputs (117major+140764437minor)pagefaults 0swaps
```

After:

```
2866.29user 291.80system 7:20.02elapsed 717%CPU (0avgtext+0avgdata 1212348maxresident)k
1168504inputs+15228576outputs (1328major+139630044minor)pagefaults 0swaps
```

I'll try to figure out what's going on. My feeling is some weird interaction with make -j X.

**Comment by ynezz** [comment]
I don't see much difference even with https://github.com/ynezz/openwrt/commit/b601599741435a8887dae7ef9c9c19825e3718c2

**Comment by neheb** [comment]
defaulting to it is somewhat dangerous. Some packages do not build.

**Comment by ynezz** [comment]
> defaulting to it is somewhat dangerous. Some packages do not build.

Then I think, that those broken packages should be marked properly as broken with `PKG_BUILD_PARALLEL:=0`.

**Comment by neheb** [comment]
Closing since there seems to be no interest.

I will note that libfuse, which is currently in master uses meson in newer versions. No idea why the version used here is so out of date.

**Comment by neheb** [comment]
@ynezz note that even though PKG_BUILD_PARALLEL is broken with CMake + GNU Make for some packages, CMake + Ninja always works.

**Pull request closed without merging**
