### PR TITLE
kernel: bump 6.1 to 6.1.77

### PR DESCRIPTION
**Pull request by graysky2**
kernel: bump 6.1 to 6.1.77

Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.77

Removed upstreamed:
	generic/backport-6.1/707-v6.8-01-net-phy-at803x-fix-passing-the-wrong-reference-for-c.patch[1]
	generic/backport-6.1/796-v6.8-ipmr-fix-kernel-panic-when-forwarding-mcast-packets.patch[2]

All other patches automatically rebased.

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.77&id=7dc0fefd37dd5fb03fdac6e3e01b1c2291148ccb
2. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.77&id=d2f1b7fe74afd66298dbb3c7b39e7b62e4df1724

Build system: x86/64
Build-tested: x86/64/AMD Cezanne
Run-tested: x86/64/AMD Cezanne

### CODE REVIEW

**Comment by graysky2** [comment]
Not yet compile nor run tested

**Comment by schuettecarsten** [comment]
Compile-tested for bcm2711 - unfortunately, device reboots some seconds after PPPoE connection is established, this happens with kernel 6.1.75 also but not on 6.1.74. The only thing I can see in the centralized syslod receiver is:

```
Unable to handle kernel access to user memory outside uaccess routines at virtual address 000000000000007a
Mem abort info:
ESR = 0x0000000096000005
EC = 0x25: DABT (current EL), IL = 32 bits
SET = 0, FnV = 0
EA = 0, S1PTW = 0
FSC = 0x05: level 1 translation fault
Data abort info:
ISV = 0, ISS = 0x00000005
CM = 0, WnR = 0
user pgtable: 4k pages, 39-bit VAs, pgdp=000000005d660000
[000000000000007a] pgd=080000005b178003, p4d=080000005b178003, pud=080000005b178003, pmd=0[...]
```

**Comment by vincejv** [comment]
Compiled successfully on x86 and booted without issues.
PPPoE works on x86 with both 6.1.75 and 6.1.76, no issues so far.

**Comment by schuettecarsten** [comment]
https://github.com/openwrt/openwrt/issues/14554

**Comment by schuettecarsten** [comment]
6.1.77 tested on bcm27xx/bcm2711 (rpi-4), mediatek/mt7622( linksys_e8450) and ath79/generic (tplink_archer-c7-v5), works.

**Pull request merged**
