### PR TITLE
[WiP] ar71xx: add support for TP-Link Archer D7 v1

### PR DESCRIPTION
**Pull request by DavideFioravanti**
This is an unusual modem-router. I managed to get almost everything
working few weeks ago when I created this patch, but due to the limited
spare time available I postopone the PR untill now.

I based my work on the Archer C7 files so there are still some 
references to that router in the mach-archer-d7-v1.c file. But I'll fix them
in the final PR

**==== WIP PART ====**
The BCM6318 is connected to the QCA9558 via lan, so also the DSL part
could work in the future. 
I started a [thread ](https://forum.lede-project.org/t/archer-d7-support/15790) for these problems some weeks ago but I didn't get any advice.
I'll write a small summary for the main problems, but I advice to read the
thread anyway to have more details.

**1) Switch configuration**
The BCM chip is connected to the QCA through the 6th port of the switch.
But we can't currently control the BCM chip so we will have
an alwas connected, but not working, port to deal with.

Because of this, I didn't add the switch configuration for the DSL PORT,
so I configured the LAN4 as WAN port.

**2) Network LED always ON**
Because of the internal connection to the BCM CPU, the switch has
always a connected port. So the only LAN led of this router is always on.

**3) WIFI2G-WIFI5G and USB1-USB2 with one LED**
There is just a led for both wifi interfaces and both USB ports.

**4) TPLINK_FLASHLAYOUT := 16Mltq**
Apparently this is the only ar71xx device to require the Tp-Link header v3,
while other ar71xx needs the safeloader or the the v1. I got OpenWrt
working using the 16Mltq layout but this is not formally correct

**==== STANDARD OPENWRT COMMIT MESSAGE ====**

TP-Link Archer D7 v1 is a dual-band AC1750 router + modem.
The router section is based on Qualcomm/Atheros QCA9558 + QCA9880.
The "DSL" section is based on BCM6318 but it's currently not supported.

I tested only the initramfs image because I am still trying to
solve these problems.

Router section - Specification:

- 775/650/258 MHz (CPU/DDR/AHB)
- 128 MB of RAM (DDR2)
- 16 MB of FLASH (SPI NOR)
- 3T3R 2.4 GHz
- 3T3R 5 GHz
- 4x 10/100/1000 Mbps Ethernet
- 7x LED, 2x button
- UART header on PCB

Everything is working except:
 - Lan LED (always on)
 - Broadband LED (missing GPIO - probably driven by the BCM6318)
 - Internet LED (missing GPIO - probably driven by the BCM6318)
 - WIFI LED (working only for one interface at time, while in the
		OEM firmware works for both wifi interfaces)
 - Communication with BCM6318.

Initramfs instruction under U-Boot, using UART:
tftpboot 0x80800000 openwrt-ar71xx-generic-archer-d7-v1-initramfs-kernel.bin
bootm

(**NOT TESTED**) Flash instruction under U-Boot, using UART:
tftp 0x81000000 openwrt-ar71xx-...-sysupgrade.bin
erase 0x9f020000 +$filesize
cp.b $fileaddr 0x9f020000 $filesize
reset

Signed-off-by: Davide Fioravanti <pantanastyle@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
fails to apply ontop of the latest tree, please rebase

**Comment by pleasantone** [comment]
Consider switching to ath79

**Comment by DavideFioravanti** [comment]
Conflicts solved.
@pleasantone When [this commit](https://github.com/openwrt/openwrt/pull/1222) will be merged I'll create an ath79 version of this patch.

However, while I am still semi-actively working on problem **(1)**, I don't know what to do for problem **(2)**, **(3)** and **(4)**

**Comment by ynezz** [comment]
@DavideFioravanti I've asked other developers about ar71xx/ath79 preference on IRC at #openwrt-devel and the outcome was, that although adding ath79 support is not mandatory, you would probably get your contribution reviewed and merged faster.

BTW if you're still hoping to get it merged as it is, then you need to rebase this PR, remove the merge commits, and probably add proper subject to `Fix for network led` -> `ar71xx: Fix for network led`.

**Comment by DavideFioravanti** [comment]
@ynezz I started working on this commit before ath79 was very stable... I can create an ath79 version of this patch and cancel this PR without problems :)

However I would like to have at least an opinion about problem about  **(4)** TPLINK_FLASHLAYOUT also because it's the same problem that I have with this patch: https://github.com/openwrt/openwrt/pull/1504

And possibily a solution for problem **(2)** and **(3)**, but they are not so important

**Comment by ynezz** [comment]
@DavideFioravanti Sorry, I don't have those answers to you as I don't know much about this platform.

**Comment by halfonf** [comment]
Hey any news on this PR ?
I have a D7 which I'm not really happy with.
Would love to be able to use this firmware.
Is there a guide on how to apply it ?

thx

**Comment by DavideFioravanti** [comment]
I will create a new PR using the ath79 target

**Pull request closed without merging**
