### PR TITLE
[RFC]Revert "mwlwifi: update to version 10.3.4.0-2018-03-30"

### PR DESCRIPTION
**Pull request by dissent1**
This reverts commit a6f24c9a78dd9f557c25b0e7c3add6bc7c74a07c
'mwlwifi: update to version 10.3.4.0-2018-03-30'

2018-03-30 version causes an issue when some clients stop
communicating with the AP until reconnected manually.

The problem seem to lie within the firmware blob itself, because
using the newer firmware blob with previous driver causes the same
issue while using the previous driver with previous blob does not).

Revert the bump for now until the issue is tracked down and fixed.

@yuhhaurlin

### CODE REVIEW

**Comment by tapper82** [comment]
Hi I have same findings on wrt3200acm. OpenWrt SNAPSHOT r7020-43d70a7a9d / LuCI Master (git-18.143.28733-7acacf2)

**Comment by dissent1** [comment]
Yes, forgot to mention that the issue is observed on wrt3200acm.

**Comment by anomeome** [comment]
I'm not seeing this with the clients(limited) that I utilise. Is there an issue open at the _mwlwifi github_ about this problem that I am not seeing?

**Comment by diizzyy** [comment]
This (the current) driver/firmware is by far the most stable one and I haven't seen any regressions either using various devices (laptops, cell phones etc). What devices are troublesome and on what band?

**Comment by AjkayAlan** [comment]
I'll chip in my thoughts - WRT3200ACM - I have not seen this issue, and honestly this current driver/firmware has worked quite well for me.

My setup:
Separate SSID's for 2.4ghz vs 5ghz
WPA2 AES Encryption
2.4GHz: Channel 6
5GHz: Channel 149
IPv6: DHCPv6

I would reiterate what others have asked - Have you submitted an issue on the mwlwifi github and is it acknowledged?

**Comment by dissent1** [comment]
I encounter it on 5ghz ch36 (I don't use 2.4 band). Devices are iPhone 6s plus and iPad air.
AFAIK @tapper82 tried to push the issue to the mwlwifi repo but it was not accepted by the maintainer.
Doesn't matter if it is accepted or not we have 2 persons who encounter the issue.

**Comment by tapper82** [comment]
wrt3200acm French 5 GHZ chan 44 80 mhz wide 2 android phones drop from the net a moto c4 and a GS 8

**Comment by tapper82** [comment]
I am going to reset my config and retest.

**Comment by diizzyy** [comment]
Motorola Razr (XT910) (TI chipset), Moto G4 (QCA), Moto X Play (QCA), Sony Xperia Z3+(QCA), Asus Zenphone 3 (QCA), Atheros AR9380, Intel AC 7620, Sony Playstation 4 (slim, Marvell chipset), Panasonic ALL multiroom speaker series (QCA) all work great on 5Ghz.

**Comment by tapper82** [comment]
Aftre a reset of my configs I cant make the same bug trigger. I had had the same configs through about 20 sysupgrades.

**Comment by lucize** [comment]
@tapper82 did you removed the sdio wifi adapter ? and don't change the region, but I think that you should know this by now

**Comment by dissent1** [comment]
My issue is config independent because it starts happening when I switch to the latest (current) firmware blob.

Let’s just wait then if someone else pops in confirming the issue.

**Comment by lucize** [comment]
I have an xperia x that is not working well but I think is related to low phone performance on ac (signal related) and set it only on 2.4, I'll try your revert and see if it behaves better

**Comment by tapper82** [comment]
I don't know any thing about the sdio wifi adapter. You meen radio 2? If so I leve it disabled. Plus my 3200acm was sent to me from france so the wi-fi defults to fr.

**Comment by lucize** [comment]
if you changed the country then remove your wifi file reboot and setup it again but this time don't touch/change country, and also uninstall de sdio driver (it is installed by default)

**Comment by tapper82** [comment]
OK I will try but why do I want to remove the sdio driver? What afect does it have?

**Comment by lucize** [comment]
just try it ;)

**Comment by lucize** [comment]
@dissent1 I can't confirm or infirm that this helped me with xperia x, but for sure the device is the worst ac client I ever seen regarding to signal strength.

**Comment by diizzyy** [comment]
@lucize 
Xperia X shouldn't be that bad. In my experience Xperia phones (QCA based ones at least) are good in general but they're inferior to laptops, routers etc which is to be expected. Can't really say that other phones I have are better in that regard.

**Comment by lucize** [comment]
@diizzyy the blackberry priv in the same spot has 866mb link, the X has ~54mb or so, with dropouts so I think that this revert can't help it

**Comment by dissent1** [comment]
Good that you guys have your issues sorted out, but I can definitely confirm that reverting the driver bump solves WiFi stalls on Apple devices I own.

Let this PR float around maybe there are more ones like me.

**Comment by dissent1** [comment]
Ppl seem to experience issues with new firmware update 
https://github.com/kaloz/mwlwifi/commit/11896425a9fe6d576b52864d8d0945656db3d551#comments
https://github.com/kaloz/mwlwifi/commit/fcaea79ad33d6ae3c381d9e96bf77d6870ca8e79#comments
Taking into account that there are no major changes between these 2 versions that common user may notice, I believe it won’t cause any degradation for everyone but fixes things for some of us.

**Comment by diizzyy** [comment]
@dissent1 @tapper82 
Does the new driver work better?

**Comment by dissent1** [comment]
Don't know now, I've switched to a different device.
This one does not apply anymore.

**Pull request closed without merging**
