### PR TITLE
base-files: fix luci TZ default show zonename

### PR DESCRIPTION
**Pull request by licsber**
when use uci set `timezone` to, example 'CST-8'

config file `/etc/config/system` set `option timezone 'CST-8'` correctly

but in luci web[System - System], it still show Timezone: 'UTC'

because luci show `zonename` instead of `timezone` param

hope to add default `zonename` param to 'UTC' for easily modify in compile.

### CODE REVIEW

**Comment by 981213** [comment]
> easily modify in compile.

If you are modifying it anyway, what's the difference between adding the line in your local branch and adding it here & changing it in your local branch afterwards?

> but in luci web[System - System], it still show Timezone: 'UTC'

I think this is an less-than-ideal behavior of LuCI and should be fixed there instead.

**Comment by licsber** [comment]
> If you are modifying it anyway, what's the difference between adding the line in your local branch and adding it here & changing it in your local branch afterwards?

just don't want maintain my repo with so small difference, now i compile firmware with some bash scripts base on upstream.

> I think this is an less-than-ideal behavior of LuCI and should be fixed there instead.

sounds great, maybe i should check how LuCI handle this param.

**Comment by jow-** [comment]
Why can't your bash script just set both params?

**Comment by licsber** [comment]
fix failed actions https://github.com/openwrt/openwrt/actions/runs/8663430026
change commit message username to my real name.

**Comment by licsber** [comment]
fix failed actions again https://github.com/openwrt/openwrt/actions/runs/8670213230/job/23778264950
change both git author name and commit name to my real name

**Comment by licsber** [comment]
fix upstream libbpf error: https://github.com/openwrt/openwrt/actions/runs/8680512941/job/23803472501
by rebase my repo to openwrt:main

**Pull request closed without merging**
