### PR TITLE
CC: brcm2708: Fix Kernel Panic: DM9601 Fast Ethernet Adapter

### PR DESCRIPTION
**Pull request by mauron85**
The dm9601 driver expects to receive a single encapsulated ethernet frame from the device in one URB transfer, and it provides an URB buffer of length 1,522 to receive it. This is not a round multiple of USB transfer packets.

The device in question [1] provides a stream of such frames and it does not conveniently slice them up as the dm9601 driver expects. We can end up with 1,536 (0x600) bytes returned by the device in response to the URB request. This may include several encapsulated ethernet frames, and/or fragments thereof.

It seems to me that the kernel 'Oops' arises because the dwc_otg driver does not notice that the destination buffer is too small to receive the full 1,536 bytes. Comparing dwc_otg's update_urb_state_xfer_comp with dwc2's dwc2_update_urb_state is suggestive.

More details: raspberrypi/linux#1045
All Credits to: https://github.com/mw9

### CODE REVIEW

**Comment by wigyori** [comment]
Thanks for the fix - please update the commit msg to have a "CC: brcm2708: " prefix as it's a backport, and add a SoB, otherwise it looks OK.

Thx,
-w-

**Comment by mauron85** [comment]
Hopefully done right.

**Comment by mauron85** [comment]
Oh not. Pushed extra file.

**Comment by mauron85** [comment]
Ok, I believe I don't have to create new PR as you can squash those commits anyway. If not, I'll close and publish new PR.

**Comment by wigyori** [comment]
Hi @mauron85 - if you don't mind, please make a new PR. :)

Thx,
-w-

**Comment by wigyori** [comment]
@mauron85 ping

**Pull request closed without merging**
