### PR TITLE
target: consolidate targets with missing generic subtarget

### PR DESCRIPTION
**Pull request by Ansuel**
It was found that many target follow an image naming style which is different from other all othe targets
This series allign every target to a common naming style by appending a generic subtarget.

Same game as for 853e4dd3062df7cb5704b15d6af6730e3194b571. Add generic
to the filenames.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

---

@hauke @hnyman Any problem with this? Notice this as i'm testing the container CI idea and i notice discrepancy on the external toolchain naming.

### CODE REVIEW

**Review by hauke — APPROVED** [review]

**Comment by aparcar** [comment]
I suggested that a lifetime ago but people were reluctant since it adds "bloat", something I'd consider consistency in this case. Could you please briefly check the mailing list/patchwork for the discussion long ago? I don't remember if there were technical reasons against it.

**Review by aparcar — APPROVED** [review]

**Comment by aparcar** [comment]
See https://patchwork.ozlabs.org/project/openwrt/patch/20190823090237.9471-1-mail@aparcar.org/

**Comment by Ansuel** [comment]
@aparcar from the discussion i can't see any problem... there were only complain for the additional ""empty"" file... Should we consider adding that variable to the include .mk? Seems a nice idea but it can be confusing honestly. 
IMHO for targets it would be better to just enforce a template that everyone should follow...

**Comment by robimarko** [comment]
Personally, I like the idea of uniformity as it really makes no sense that only these targets dont have generic subtarget.

**Pull request merged**
