### PR TITLE
feeds: use git-src-full to allow Git versioning

### PR DESCRIPTION
**Pull request by aparcar**
Both $(AUTORELEASE) and $(PKG_SRC_VERSION) (from luci.git) use the Git
log to determine releases and package timestamps.

Feeds are shallow cloned by default, resulting in an incomplete Git log
and therefore different local package versions than offered upstream.

This commits sets the default feeds to use `src-git-full` to solve that.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by hnyman** [comment]
Please also fix the `git pull --ff-only` usage (in three places in src-git-full).

I only fixed the traditional src-git with #3610 / commit  https://github.com/openwrt/openwrt/commit/2b1d92f134e9b6c5744a3cc2d0e22273a7a5fe03
but the src-git-full remained unfixed.

**Comment by hnyman** [comment]
@aparcar 
Are you proceeding with this?

**Comment by aparcar** [comment]
Thanks for the reminder, I'll do that later today!

**Comment by aparcar** [comment]
I'm somewhat against "forcing" that behavior onto users, I'd just proceed with the change suggested and future setup start using it. Especially CI would get "fixed" by this.

**Comment by hnyman** [comment]
Your original approach is just fine. ;-)

**Pull request closed without merging**
