### PR TITLE
realtek: add ZyXEL GS1900-24HPv2 support

### PR DESCRIPTION
**Pull request by zambelly**
This patch adds support for the RTL8382 based GS1900-24HPv2 from ZyXEL.

Signed-off-by: Soma Zambelly <zambelly.soma@gmail.com>

### CODE REVIEW

**Comment by pkgadd** [comment]
The commit message should contain information about the device and how to install OpenWrt on it, feel free to borrow from https://github.com/openwrt/openwrt/pull/3860.

**Comment by pkgadd** [comment]
I'm pretty sure https://github.com/openwrt/openwrt/pull/3860#issuecomment-777105467 applies to this device as well, to set up uboot-envtools.

**Comment by zambelly** [comment]
> I'm pretty sure [#3860 (comment)](https://github.com/openwrt/openwrt/pull/3860#issuecomment-777105467) applies to this device as well, to set up uboot-envtools.

I'm not sure I understand. My commit contains the `package/boot/uboot-envtools/files/realtek` modification.
All uboot-envtools commands work correctly

**Comment by zambelly** [comment]
I updated the commit message per your request

**Comment by pkgadd** [comment]
> I'm not sure I understand. My commit contains the `package/boot/uboot-envtools/files/realtek` modification.

Sorry, I somehow missed that part.

**Comment by zambelly** [comment]
Based on the stock firmware's configuration, and other people's experience with the GS1900-24HP (v1), I originally configured the memory as only 64 MiB in the device tree.
Only while writing the full commit message for this commit did I realize that this switch actually has 128 MiB.
I adjusted the device tree according to this.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master.

**Comment by Neustradamus** [comment]
Merged commit is:
- https://github.com/openwrt/openwrt/commit/c5b44af2fc5ffe620405ccb743b6f4acc461d4de

@hauke: Not possible into 21.02.x branch?

**Pull request closed without merging**
