### PR TITLE
Fix bug introduced by APuP

### PR DESCRIPTION
**Pull request by G10h4ck**
Include hotfix suggested by Sebastian Gottschall

@see https://github.com/openwrt/openwrt/pull/15442#issuecomment-2322787285

### CODE REVIEW

**Comment by hauke** [comment]
This PR has formal issues:
> === Checking commit '8802c72bb45fec047805867339e36aacef429fda'
> Author name (Gioacchino Mazzurco) seems ok
> Commit subject line MUST start with '<area>: ' (Fix bug introduced by APuP)
> Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Gioacchino Mazzurco <gio@polymathes.cc>')
> Include hotfix suggested by Sebastian Gottschall
> A commit message exists
> Error: Process completed with exit code 1.

**Comment by BrainSlayer** [comment]
@hauke & @G10h4ck you are permitted todo any change as required regarding my own patch ownership. but do not delay it since it does fix a critical stability issue. due the nature of the original apup patch hostapd will crash on wds station disconnect also if apup support is not compiled in.

**Comment by mwarning** [comment]
Is there something missing? Imho, this MR looks good.

**Comment by hauke** [comment]
I increased `PKG_RELEASE` too, opkg will install this as an update now.

**Pull request merged**
