### PR TITLE
ath79: switch to Kernel 5.10

### PR DESCRIPTION
**Pull request by aparcar**
CI build with artifacts: https://github.com/aparcar/openwrt/actions/runs/1290291243

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by mrkiko** [comment]
Netgear R6100 works on 5.10 so far.

**Comment by neheb** [comment]
Plenty of testing done with Archer C7v2. Stable.

**Comment by pkgadd** [comment]
`Tested-by: Stefan Lippers-Hollmann <s.l-h@gmx.de> [ath79/tl-wdr3600; ath79/tl-wdr4300]`

**Comment by john-tho** [comment]
I suspect that some RedBoot devices, where the `FIS directory` (an SPI-NOR partition which stores SPI-NOR partition table) partition boundaries are unaligned to the kernel SPI-NOR erasesize (`0x10000`) will not be able to update the `FIS directory` under 5.10. This happens in sysupgrade, and will be noticeable with an upgrade to an image with a different kernel length.
I do not have one of these devices. This was mentioned last year and detailed the reason: The OpenWRT pending 411 & 412 NOR partial erase patches do not work and are not present in 5.10: https://github.com/openwrt/openwrt/pull/3271#issuecomment-696936166, https://lists.openwrt.org/pipermail/openwrt-devel/2020-September/031500.html

**Comment by PolynomialDivision** [comment]
Why don't you delete all the 5.4 related configs, patches and files?

**Comment by aparcar** [comment]
This is to collect feedback and missing changes. Once this get merged I'll remove 5.4, for now it saves me continuous rebasing.

**Comment by rodsmar** [comment]
Archer C6 v2 (US) with 5.10 and qca8k. Stable.

**Comment by aparcar** [comment]
How can we continue here? Do we need more testing? @john-tho do you need help with the issue you mentioned?

**Comment by john-tho** [comment]
> How can we continue here? Do we need more testing? @john-tho do you need help with the issue you mentioned?

I don't have a RedBoot device to test. I would disable the Redboot device sysupgrade or images 760952ad022561931846b02ddfe69c21afead0fe, and proceed with the kernel bump:
- adtran,bsap1800-v2
- adtran,bsap1840
- jjplus,ja76pf2
- ubnt,routerstation
- ubnt,routerstation-pro

Previous bug:
https://bugs.openwrt.org/index.php?do=details&task_id=2428 At least the bootloader config won't be wiped like that.

If anyone uses one, they can work out a fix to use or fake 4K_SECTORS. I reached out to a number of people who had authored to OpenWrt's FIS directory update implementation in December 2020, so they have been aware long enough.

**Comment by john-tho** [comment]
Regarding the FIS directory updates:

The adtran bsap18xx devices look like they don't need sysupgrade disabled:
From [forum console output: FIS directory is a 10K partition: `0x00fd0000-0x00fe0000 : "FIS directory"`](https://forum.openwrt.org/t/support-for-adtran-bluesocket-bsap-1800v2/10660)

jjPlus JA76PF2 [yes: `mtd4: 0000f000 0000f000 "FIS directory"`](https://bugs.openwrt.org/index.php?do=details&task_id=2428)
RouterStation [yes: `[    0.757099] 0x000000ff0000-0x000000fff000 : "FIS directory"`](https://forum.openwrt.org/t/porting-guide-ar71xx-to-ath79/13013/211)

So revert of this looks okay to me: https://github.com/openwrt/openwrt/commit/760952ad022561931846b02ddfe69c21afead0fe

**Comment by john-tho** [comment]
Hi @tmn505,
If you have a jjPlus JA76PF2 or RouterStation available to test, I suspect sysupgrade from kernel 5.10 will not work (when kernel size changes, FIS directory mtd partition is too small to be writeable, so cannot be updated). I suggested their sysupgrade images be disabled again.
Would be great if you could make any comments or do testing?
Cheers

**Comment by xback** [comment]
Purely fyi
I've been running ath79 - 5.10 on following devices in the field for months now:

- Mikrotik rb922 (custom configured with -march=74kc)
--> ~120 devices
- Mikrotik rb912 (custom configured with -march=74kc)
--> ~ 60 devices
- gl-inet gl-mifi
--> ~10 devices
- gl-inet e750
--> 2 devices
- mikrotik wapac
--> 2 devices
- mikrotik wapr
--> 2 devices

**Comment by ac7v4** [comment]
With the following upstream commits, is the PR still relevant?

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=7f5c823da2b4906771bf3ea849aa27f8b12d02f5

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=d58eec88b5c6192c14187f2576dab6dda51f4f8f

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=0aa1316218c4204b73f9df413478ee49dd2159bd

I could be wrong. Please advise.

**Comment by aparcar** [comment]
This PR is for ath79 not omap

**Comment by ac7v4** [comment]
> This PR is for ath79 not omap

Ok thanks.

**Comment by ac7v4** [comment]
Hi, I’m trying to build OpenWrt using github actions.
Here is my workflow run. [Workflow](https://github.com/ac7v4/OpenWrt-Archer_C7_v4/runs/4324471626?check_suite_focus=true) 

It fails here.

From https://github.com/openwrt/openwrt
 * [new ref]               refs/pull/4619/head -> k510-ath79
 CONFLICT (modify/delete): target/linux/ath79/patches-5.4/0032-MIPS-ath79-sanitize-symbols.patch deleted in k510-ath79 and modified in HEAD.  Version HEAD of target/linux/ath79/patches-5.4/0032-MIPS-ath79-sanitize-symbols.patch left in tree.
 Automatic merge failed; fix conflicts and then commit the result.
Error: Process completed with exit code 1.

Can someone help me to fix this please?

**Comment by castillofrancodamian** [comment]
> Hi, I’m trying to build OpenWrt for an Archer C7 v4 using github actions. Here is my workflow run. [Workflow](https://github.com/ac7v4/OpenWrt-Archer_C7_v4/runs/4324471626?check_suite_focus=true)
> 
> It fails here.
> 
> From https://github.com/openwrt/openwrt
> 
> * [new ref]               refs/pull/4619/head -> k510-ath79
>   CONFLICT (modify/delete): target/linux/ath79/patches-5.4/0032-MIPS-ath79-sanitize-symbols.patch deleted in k510-ath79 and modified in HEAD.  Version HEAD of target/linux/ath79/patches-5.4/0032-MIPS-ath79-sanitize-symbols.patch left in tree.
>   Automatic merge failed; fix conflicts and then commit the result.
>   Error: Process completed with exit code 1.
> 
> Can someone help me to fix this please?

Can an image be compiled with GitHub?

**Comment by ac7v4** [comment]
> > Hi, I’m trying to build OpenWrt for an Archer C7 v4 using github actions. Here is my workflow run. [Workflow](https://github.com/ac7v4/OpenWrt-Archer_C7_v4/runs/4324471626?check_suite_focus=true)
> > It fails here.
> > From https://github.com/openwrt/openwrt
> > 
> > * [new ref]               refs/pull/4619/head -> k510-ath79
> >   CONFLICT (modify/delete): target/linux/ath79/patches-5.4/0032-MIPS-ath79-sanitize-symbols.patch deleted in k510-ath79 and modified in HEAD.  Version HEAD of target/linux/ath79/patches-5.4/0032-MIPS-ath79-sanitize-symbols.patch left in tree.
> >   Automatic merge failed; fix conflicts and then commit the result.
> >   Error: Process completed with exit code 1.
> > 
> > Can someone help me to fix this please?
> 
> Can an image be compiled with GitHub?

Yes it can be, i have built with PR#4528 and PR#4562. But when I try to include PR#4519 it fails.

**Comment by castillofrancodamian** [comment]
> > > Hi, I’m trying to build OpenWrt for an Archer C7 v4 using github actions. Here is my workflow run. [Workflow](https://github.com/ac7v4/OpenWrt-Archer_C7_v4/runs/4324471626?check_suite_focus=true)
> > > It fails here.
> > > From https://github.com/openwrt/openwrt
> > > 
> > > * [new ref]               refs/pull/4619/head -> k510-ath79
> > >   CONFLICT (modify/delete): target/linux/ath79/patches-5.4/0032-MIPS-ath79-sanitize-symbols.patch deleted in k510-ath79 and modified in HEAD.  Version HEAD of target/linux/ath79/patches-5.4/0032-MIPS-ath79-sanitize-symbols.patch left in tree.
> > >   Automatic merge failed; fix conflicts and then commit the result.
> > >   Error: Process completed with exit code 1.
> > > 
> > > Can someone help me to fix this please?
> > 
> > 
> > Can an image be compiled with GitHub?
> 
> Yes it can be, i have built with PR#4528 and PR#4562. But when I try to include PR#4519 it fails.

Is there any guide I can follow to do that?

**Comment by ac7v4** [comment]
> Is there any guide I can follow to do that?

I don’t know of any guide, but if you search PETERX on github you will find it.

**Comment by castillofrancodamian** [comment]
Works perfectly on an Archer C60 v1.

**Comment by abajk** [comment]
`Tested-by: Aleksander Jan Bajkowski <olek2@wp.pl> # Tested on TP-Link TL-WDR4300`

**Comment by aparcar** [comment]
@adschm can we merge this and fix remaining issues later on?

**Comment by rsalvaterra** [comment]
@aparcar, @adschm, `ath79` is a huge target. If we wait until all possible devices are tested at 5.10, we will never make progress. I suggest merging this and deal with any possible fallout, just like we did for `ramips`.

**Comment by blocktrron** [comment]
WIll remove kernel 5.4 after the builds have passed.

**Comment by aparcar** [comment]
@blocktrron thanks for taking over!

**Comment by PolynomialDivision** [comment]
Works on following devices:
- [x] Rocket 5 AC Lite
- ...

**Comment by tapper82** [comment]
All good on C7-V2 running as a Dumb AP.

**Comment by tmn505** [comment]
@john-tho thanks for the mention. When @nbd168 introduced 5.10, he left out the partial erase block patches and given that the lowest erase block which upstream would consider is 4K, let's not delve on this and move forward. No reason to keep that hacks around. The sysupgrade images for Routerstations and JA76PF2, as You mentioned, should be disabled for now (or for ever if no solution will be found).

I'm considering similar approach to assemble FIS partition as in #4897, using kmod-mtd-rw but that would be hackish. Another would be replacing bootloader, which sources are available and needs only one configuration option flip to fix it. The downside for Routerstations is that bootloader recovery using reset button would not work any more, since I don't have the sources for this utility. Cheers.

**Pull request closed without merging**
