### PR TITLE
kernel: bump 5.15 to 5.15.60

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by graysky2** [comment]
I believe the zynq/generic build error is a false positive due to a bad tarball download.

**Comment by ynezz** [comment]
> I believe the zynq/generic build error is a false positive due to a bad tarball download.

Indeed, seems like some CDN hiccup as I'm able to download it here, but it's using different host. BTW I'm just wondering, are you able to trigger failed job re-run as a normal user? I've fired the rebuild of that failed job just now.

**Comment by graysky2** [comment]
@ynezz - I do not know how to trigger the checks without force pushing a commit.  I will try if you advise how.

**Comment by ynezz** [comment]
image

**Comment by graysky2** [comment]
My user does not have those options:
no

**Comment by ynezz** [comment]
Thanks, I've just runtime tested it on turris-omnia and glinet-b1300, no regressions to .59 so I've merged it in 5238a87c20bc1.

**Pull request closed without merging**
