### PR TITLE
ath79: fix USB speed issues on ar934x devices like TP-Link WDR3600/WDR4300

### PR DESCRIPTION
**Pull request by jneuhauser**
The new of driver for the ath79 target is missing a reset definition that has a dramastic performance decrease on at least the TP-Link WDR3600/WDR4300 and similar devices.

This performance decrease on ath79 over ar71xx was reported on:
- OpenWRT Forum [#46794](https://forum.openwrt.org/t/usb-wdr4300-low-speed-on-external-storage/46794)
- GitHub PR https://github.com/openwrt/openwrt/pull/964
- Flyspray [#2567](https://bugs.openwrt.org/index.php?do=details&task_id=2567)

The kernel log prints `not running at top speed; connect to a high speed hub` for all connected usb device without this pr.

After comparing the old mach-driver **arch/mips/ath79/dev-usb.c** with the new of-driver **drivers/phy/phy-ar7200-usb.c** it turns out that there is some different behavior and a missing reset for the analog part of the usb unit on ar934x.

This commits add the missing reset signal, reorders the assertion of the reset bits and removed the logic that puts the phy into reset if deasserting the phy reset or asserting the suspend_override bits failed.

### Without this PR
**internal 4-port usb hub and usb-stick is detected like:**
```
[    5.918324] usb 1-1: new full-speed USB device number 2 using ehci-platform
[    6.182793] usb 1-1: not running at top speed; connect to a high speed hub
[    6.206210] hub 1-1:1.0: USB hub found
[    6.212253] hub 1-1:1.0: 4 ports detected
[    6.539842] usb 1-1.1: new full-speed USB device number 3 using ehci-platform
[    6.942394] usb 1-1.1: not running at top speed; connect to a high speed hub
[    7.032767] usb-storage 1-1.1:1.0: USB Mass Storage device detected
```
```
root@OpenWrt:~# lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 12M
        |__ Port 1: Dev 3, If 0, Class=Mass Storage, Driver=usb-storage, 12M
```
**raw write test:**
```
root@OpenWrt:~# time dd if=/dev/zero of=/dev/sda1 bs=10M count=100 conv=fsync
100+0 records in
100+0 records out
real	16m 11.47s
user	0m 0.00s
sys	0m 17.72s
1000M / 971s = 1.0299 M/s
```

### With this PR
**internal 4-port usb hub and usb-stick is detected like:**
```
[    5.918948] usb 1-1: new high-speed USB device number 2 using ehci-platform
[    6.192680] hub 1-1:1.0: USB hub found
[    6.198768] hub 1-1:1.0: 4 ports detected
[    6.530023] usb 1-1.1: new high-speed USB device number 3 using ehci-platform
[    7.002807] usb-storage 1-1.1:1.0: USB Mass Storage device detected
```
```
root@OpenWrt_Second:~# lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 1: Dev 3, If 0, Class=Mass Storage, Driver=usb-storage, 480M
```
**raw write test:**
```
root@OpenWrt:~# time dd if=/dev/zero of=/dev/sda1 bs=10M count=100 conv=fsync
100+0 records in
100+0 records out
real	1m 33.13s
user	0m 0.00s
sys	0m 16.75s
1000M / 93s = 10,75 M/s
```

## Test on other devices that uses the **ar7200-usb-phy** driver

**For now, this PR should only change the behavior on devices with ar934x based devices.**

If you think you are affected by this, then check your kernel log with `dmesg` if you are seeing `not running at top speed; connect to a high speed hub` after you connected a usb device.

The following device trees include files uses this driver:
```
ar7240.dtsi
ar7241.dtsi
ar7242.dtsi
ar9132.dtsi
ar9330.dtsi
ar934x.dtsi
qca953x.dtsi
qca9557.dtsi
qca956x.dtsi
```

## Backporting to 19.07 (kernel 4.14)
If this should be also applied to 19.07, then i will create a second PR for the 19.07 branch.

### CODE REVIEW

**Comment by jneuhauser** [comment]
i have added better commit messages which better describe the changes.

I also changed the title of the PR to make more people aware of it.

**Comment by gwlim** [comment]
Ok did some quick testing for affected platforms
MR3420v1 AR7242 - Hi Speed
MR3420v2 AR9341 - Full Speed
TL-WR1043NDv1 AR9132 - Hi Speed
TL-WDR4300v1 AR9344 - Full Speed
Archer C7v4 QCA956X - Hi Speed
Don't see a pattern here could be a USB quirk or uboot initialization thing.
IMO if it doesn't brick anything must as well apply to all

**Comment by jneuhauser** [comment]
@gwlim Are your tests with this patches or without it?
As i see only the ar934x devices are on Full Speed (12 Mbps), so i suggest you have done your testing without this patches, right?

According to the old driver **arch/mips/ath79/dev-usb.c**, only ar934x has this missing reset for the analog part of the usb phy.

@blogic Do you have any comments or thoughts?

**Comment by gwlim** [comment]
@jneuhauser 
I did the quick test without the patch.
If that is the case we should just apply the patch to 934x.dtsi

**Comment by gwlim** [comment]
I can confirm AR934x goes to Hi Speed with the patch, but this message appears in dmesg
```
[    0.077579] io scheduler deadline registered (default)
[    0.078292] ar7200-usb-phy usb-phy: phy reset is missing
[    0.079876] pinctrl-single 1804002c.pinmux: 544 pins, size 68
```

**Comment by jneuhauser** [comment]
> ```
> [    0.078292] ar7200-usb-phy usb-phy: phy reset is missing
> ```

This message is also in the kernel log without my patches...
I think the driver initialization is deferred at this point because the gpio driver is not yet available.
This should be fixed in a separate PR, as this is more or less just a cosmetic bug.

**Comment by gwlim** [comment]
Tested works with AR9341 (MR3420v2) and AR9344 (WDR4300v1).

**Comment by gpu8500aiw** [comment]
Tested on WDR4300v1.
USB2 speed works. Around 11MB/s with SMB file sharing on USB drive

**Comment by jneuhauser** [comment]
Run tested by me on:
tl-wr1043v2
tl-wr1043v4

**Comment by phizev** [comment]
I'm running with this on a WDR3600, it's pretty much critical if one is using a USB tethered mobile device as a backup connection. 30Mbps down, 18Mbps up on a quick speedtest with a flash drive connected.

**Comment by blogic** [comment]
merged, thanks !

**Comment by jneuhauser** [comment]
@gwlim https://github.com/openwrt/openwrt/pull/2700 should address the reported error message on a defered init of the ar7200-usb-phy driver.

**Pull request closed without merging**
