### PR TITLE
update bison from 3.2.2 to 3.2.4

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: protonesso <nagakamira@gmail.com>

### CODE REVIEW

**Comment by protonesso** [comment]
set "tools" label

**Comment by diizzyy** [comment]
Compile/Runtime tested?

**Comment by protonesso** [comment]
I will test soon!

**Comment by protonesso** [comment]
image
Compiled

**Comment by protonesso** [comment]
on debian 9

**Comment by dedeckeh** [comment]
@protonesso The patch must be signed off with your real name; see https://openwrt.org/submitting-patches#submitting_patches

**Comment by protonesso** [comment]
How to edit my commit?

**Comment by dedeckeh** [comment]
@protonesso Make the changes in the git commit message via git commit --amend; than do a forced update by doing git push -f

**Comment by protonesso** [comment]
@dedeckeh job done! My real name and surname are Egor Mikhaylov

**Comment by dedeckeh** [comment]
I manually fixed the git commit author as it did not align with the signed off name.
Patch pushed to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=ff62e83211c8ed306f6c7e5996d1bc7199dc9f00); thx

**Pull request closed without merging**
