### PR TITLE
Add support for DIR-853-R1

### PR DESCRIPTION
**Pull request by fiduchi**
ramips: Add support for Dlink DIR-853-R1

This PR adds suppotr for router Dlink DIR-853-R1

Specifications:

    SoC: MT7621AT
    RAM: 128MB
    Flash: 16MB SPI
    WiFi: MT7615DN (2.4GHz+5Ghz) with DBDC (This mode allows
    this single chip act as an 2x2 11n radio and an 2x2 11ac radio at the
    same time)
    LAN: 5x1000M
    LEDs Power Blue+Orange,Wan Blue+Orange,WPS Blue,"2.4G"Blue, "5G" Blue,
    USB Blue
    Buttons Reset,WPS, Wifi

lan factory 0xe000 CD(label)
wan factory 0xe006 D0
2.4 GHz factory 0xe000+1 ECCE
5.0 GHz factory 0xe000+2 6ECE

Flashing instruction:

The Dlink "Emergency Room"

Connect your client computer to LAN1 of the device
Set your client IP address manually to 192.168.0.101 / 255.255.255.0.
Then, power down the router, press and hold the reset button, then
re-plug it. Keep the reset button pressed until the internet LED stops
flashing
Call the recovery page or tftp for the device at http://192.168.0.1
Use the provided emergency web GUI to upload and flash a new firmware to
the device.

Signed-off-by: Stas Fiduchi fiduchi@protonmail.com

### CODE REVIEW

**Comment by mpratt14** [comment]
@adschm let's just keep this one, otherwise, there are going to be endless dead PRs from this person. All 3 past PRs have the same problem now

it seems that recovering a deleted branch is possible, but a deleted fork is gone forever (unless maybe contacting GitHub support and then who knows)

**Comment by adschm** [comment]
@mpratt14 The submitter opened a new PR twice against my explicit request. How should I trust him on anything else?

**Comment by adschm** [comment]
And like with all multi-post PRs, it got worse than it was before ...

**Comment by fiduchi** [comment]
not. Sorry, I'm just trying to restore pr 4086, but nothing works for me.

Отправлено из мобильного клиента ProtonMail

-------- Исходное сообщение --------
В 11 июн. 2021 г., 19:45, Adrian Schmutzler написано:

**Comment by mpratt14** [comment]
@fiduchi to return to your new commit

```
git reset --hard HEAD^
git cherry-pick 1e72a7bc39da457b99fb9ff3371df91cafb1e5be
git pull --rebase https://github.com/openwrt/openwrt.git master
git push --force https://github.com/fiduchi/openwrt.git master
```

**Comment by fiduchi** [comment]
> @fiduchi to return to your new commit
> 
> ```
> git reset --hard HEAD^
> git cherry-pick 1e72a7bc39da457b99fb9ff3371df91cafb1e5be
> git pull --rebase https://github.com/openwrt/openwrt.git master
> git push --force https://github.com/fiduchi/openwrt.git master
> ```
is it to open 4086 ???

**Comment by mpratt14** [comment]
> is it to open 4086 ???

no

it is for putting the new commit in this one

**Comment by fiduchi** [comment]
> > это чтобы открыть 4086 ???
> 
> НЕТ
> 
> это для того, чтобы поместить новый коммит в этот

ah the new pull request is blocked as a duplicate 4086. I can't open 4086 back. I don’t know what to do anymore.

**Pull request closed without merging**
