### PR TITLE
ipq40xx: add switch led blink support

### PR DESCRIPTION
**Pull request by dengqf6**
Implement `get_port_stats()` function for ar40xx phy

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
You could be chattier in your commit message...

**Comment by CodeFetch** [comment]
@dengqf6 Can you please explain how/where the switch LEDs are being turned on and off?
It's OT, but I'm also interested in QCA9531, because the datasheet says it's possible to set a GPIO function to let the switch directly control the GPIOs and configure the blink pattern using MDIO registers. Is it similar with QCA40xx? Is it implemented this way in OpenWrt or does OpenWrt use something like the netdev LED trigger? If yes, wouldn't it save some CPU cylces to let the switch chip's directly control the GPIOs?

**Comment by dengqf6** [comment]
@CodeFetch 
In some cases the LEDs are connected to the SoC and not the switch/phy (QCA807x in this case), so they cannot be controlled by the switch/phy directly.
IPQ40xx has an LED controller which can be used to control LAN/WAN/WiFi LEDs, but driver is not available in mainline linux.

**Comment by dengqf6** [comment]
@chunkeey ping

**Comment by adrianschmutzler** [comment]
@dengqf6 This requires an update to include 5.4. After that, either try to ping blogic and chunkeey again or send it to the openwrt-devel list (I'd do the latter).

**Comment by adschm** [comment]
The relevant file has been moved from kernel patches to files/
Please update.

**Comment by dengqf6** [comment]
Updated

**Review by CodeFetch — CHANGES_REQUESTED** [review]
Your commit name is a bit misleading. Please change it to something like:
ipq40xx: ar40xx: implement get_port_stats()

And then state in the commit message that this allows the switch LED driver to work... The commit name should state what the commit does instead of what it intends to achieve. This makes searching through the history easier.

**Comment by CodeFetch** [comment]
@dengqf6 Ping!

**Comment by PolynomialDivision** [comment]
Ping.

**Comment by PolynomialDivision** [comment]
Please also add the DSA conversion:
https://github.com/openwrt/openwrt/pull/4721

**Comment by 981213** [comment]
IPQ40xx is using DSA now. This PR can be closed.

**Pull request closed without merging**
