### PR TITLE
ramips: improve pinctrl for Youku YK-L1

### PR DESCRIPTION
**Pull request by DragonBluep**
1. rename led pin "air" to a more common name "wlan" and use "phy0tpt" to trigger it.
2. led "wan" can be triggered by ethernet pinctrl by default so just drop it.

### CODE REVIEW

**Comment by adschm** [comment]
> 1. rename led pin "air" to a more common name "wlan" and use "phy0tpt" to trigger it.

Well, what would be the "correct" name based on the vendor?

**Comment by DragonBluep** [comment]
> > 1. rename led pin "air" to a more common name "wlan" and use "phy0tpt" to trigger it.
> 
> Well, what would be the "correct" name based on the vendor?

085944ltt22ddd2znngdjf~2
There are only some icons on the router and I think "wlan" is more suitable.

**Comment by adschm** [comment]
> > > 1. rename led pin "air" to a more common name "wlan" and use "phy0tpt" to trigger it.
> > 
> > 
> > Well, what would be the "correct" name based on the vendor?
> 
> 085944ltt22ddd2znngdjf~2
> There are only some icons on the router and I think "wlan" is more suitable.

Okay, so if you refer to the center one, this is perfectly fine.

**Comment by adschm** [comment]
Thanks, will be merged soon.

**Pull request closed without merging**
