### PR TITLE
brcm2708: kernel config cleanup & pre-work before adding 4.14 support

### PR DESCRIPTION
**Pull request by commodo**
Related to PR https://github.com/openwrt/openwrt/pull/589

There are a few elements in that PR that I'm not sure that are acceptable, so instead of holding up these changes with that PR, I decided to submit them separately.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
@stintel @Noltari

**Comment by commodo** [comment]
rebased on a newer master

**Comment by stintel** [comment]
Unable to test this as for some reason my generated image is only a few KB.

**Comment by commodo** [comment]
Curios: do you get the same result without this patchset ?

For me this produces an 8 Mb gz sdcard image

**Comment by stintel** [comment]
Sorry I should have written that it even happens on master, with a clean, default config.

**Comment by commodo** [comment]
I’d be interested in fixing this if I can.

Can you share your config ?
Maybe I have a chance of reproducing it.

It sounds like a host specific bug.
But who knows

**Comment by commodo** [comment]
@stintel  ping :)

**Comment by stintel** [comment]
clean default config -> `"echo "CONFIG_TARGET_brcm2708=y" > .config; echo "CONFIG_TARGET_brcm2708_bcm2708=y" >> .config; make defconfig"`

**Comment by commodo** [comment]
hey

so for me, this also works ; 
i think this is probably a host-specific issue ;

in my case, i'm on an XUbuntu 17.10 x86_64;

**Comment by commodo** [comment]
Changelog v1 -> v2:
* reformatted comments to 75 col width
* rebased on top of a newer master
* adjusted kernel version for pi kmods : 
  * `snd-bcm2835.ko@ge4.12` was `snd-bcm2835.ko@ge4.14` before
  * `bcm2835-v4l2.ko@ge4.12` was `bcm2835-v4l2.ko@ge4.14` before

**Comment by commodo** [comment]
@stintel 
would it be too much trouble to ask for a build log ?

just curios, if i can figure it out if i can

no hurry from my side

**Comment by stintel** [comment]
@commodo https://www.linux-ipv6.be/LEDE/brcm2708.log

**Comment by stintel** [comment]
If I remove the gzip step from IMAGE/sdcard.img.gz in Device/Default in target/linux/brcm2708/image/Makefile the problem goes away. I think the problem is that the image is called .gz before it's being gzipped, and then gzip doesn't want to compress it due to it already having the .gz extension.

**Comment by commodo** [comment]
ack ;
thanks for checking
i also found this
```
gzip: skipping: /home/stijn/Development/LEDE/source/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-brcm2708_bcm2708/tmp/openwrt-brcm2708-bcm2708-rpi-ext4-sdcard.img.gz ends with .gz
```

**Comment by commodo** [comment]
Changelog v2 -> v3:
* rebased on top of newer master (16245a5d8e77c165344666c9520aeb5ca3b18c31) ; this should include fix to address the `gzip` problem

**Comment by commodo** [comment]
@stintel 
ping

**Comment by commodo** [comment]
@stintel 
ping

**Comment by commodo** [comment]
hmm ; on 2nd thought: maybe i'll close the PR :)
and re-spin this later;
or maybe drop it altogether; it's been a bit too long since i created this, and i'd need to re-test it;

**Comment by stintel** [comment]
@commodo sorry for not looking into this. I might have a go at it myself, I would really like to see brcm2708 use 4.14 in the next release.

**Comment by commodo** [comment]
no worries;
i don't have a board atm, so i can't test much;
i'll have 1 in a week or so;
so, i could probably also help with the upgrade later;

the only note-worthy commit from here for upgrading to 4.14 is https://github.com/openwrt/openwrt/pull/606/commits/e3c7e3899d9a05b23ad610aa8c66c43e40b08476
that is: if you are still keeping 4.9 around

you could probably take a look at this commit series and pick stuff out:
https://github.com/commodo/openwrt/commits/master
(that's just stuff that's quickly done to work for me)

FWIW: I picked the patches from the RPi github repo; but that does not really seem like a good idea as they backport plenty of stuff in the rpi-4.14.y branch; also some patches are complete drivers, so the total amount of patch-files is ~4-5 MB
I have not identified what the best approach is.

**Pull request closed without merging**
