### PR TITLE
CI: build all host tools

### PR DESCRIPTION
**Pull request by Ansuel**
Now that we build also core packages, we need more host tools. Compile
all of them to reduce compile time on other actions.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@hauke what do you think? on push it will take 2h+ to compile the container with all the tools compiled... This is to reduce the core packages workflow

**Comment by hauke** [comment]
There is a bug in the packages workflow, I fixed it here: https://github.com/hauke/openwrt/commit/e2a97404c34f5245bd6fafb0626c99fed9517ad1

I am working on building all subtargets for all targets with changes: https://github.com/hauke/openwrt/tree/github-target-build2

**Comment by hauke** [comment]
I think it is good to build all host tools to ind there more potential bugs.

I pushed the fix to prevent the tools getting rebuild in the packages workflow, see 6645a019f88e2e6930fe63d1a51046a8e72445a0.

I am not sure how well ccache actually works in the CI, the caches uploaded are often less then 1MB which looks pretty small for me. 
Please also check if we have to select BUILD_ALL_HOST_TOOLS in the package.yml now too.

**Comment by Ansuel** [comment]
I notice some targets for some reason doesn't use ccache for kernel
compilation... Some limitation of the arch???

The option is just to compile and is not required on any user

Il Sab 12 Nov 2022, 16:24 Hauke Mehrtens ***@***.***> ha
scritto:

**Pull request merged**
