### PR TITLE
bcm63xx: add BQL and xmit_more support

### PR DESCRIPTION
**Pull request by spliew89**
This patch series add Byte Queue Limits and subsequently xmit_more support to the bcm63xx target. BQL aims to reduce/remove bufferbloat while xmit_more relies on BQL to allow bulking of hardware TX queue.

### CODE REVIEW

**Comment by adschm** [comment]
Please add commit descriptions for the commits and add a patch header for the actual patches inside the commits.

**Comment by spliew89** [comment]
> 
> 
> Please add commit descriptions for the commits and add a patch header for the actual patches inside the commits.

Changed as requested.

**Comment by adschm** [comment]
You have somehow duplicated your commits?

**Comment by spliew89** [comment]
> You have somehow duplicated your commits?

Sorry, I'm not familiar with git. Fixed with git reset.

**Comment by Noltari** [comment]
@spliew89 I've already merged https://github.com/openwrt/openwrt/pull/3502 and https://github.com/openwrt/openwrt/pull/3558. However, as I already said on https://github.com/openwrt/openwrt/pull/3502, I'm not merging this PR because [the xmit_more patch is causing issues on my Huawei HG253s v2](https://github.com/openwrt/openwrt/pull/3502#issuecomment-735936314)

Do you want me to do some more tests with the xmit_more patch?
Shall I merge the BQL support patch in the meantime?

**Comment by spliew89** [comment]
> Do you want me to do some more tests with the xmit_more patch?

Sure, if you want to. Meanwhile I will work on the issue.

> Shall I merge the BQL support patch in the meantime?

Please proceed. It doesn't depend on xmit_more and still provide benefits of its own.

**Comment by spliew89** [comment]
Unfortunately I can't recreate the issue on my BCM6328 and BCM6333 + BCM5325 devices.
And that's by duplicating your test setup, running iperf3 in the routers.

**Comment by Noltari** [comment]
> Unfortunately I can't recreate the issue on my BCM6328 and BCM6333 + BCM5325 devices.
> And that's by duplicating your test setup, running iperf3 in the routers.

Are all of your devices fast ethernet?
I'm thinking that maybe it's only reproducible on gigabit ethernet devices. I will do more tests today and see if I can reproduce it on my Comtrend VG-8050 (gigabit) and on my Sercomm AD1018 (fast ethernet).

**Comment by Noltari** [comment]
@spliew89 incrementing the number of TX descriptors seems to fix the issue (no more _bcm63xx_enetsw bcm63xx_enetsw.0: xmit called with no tx desc available?_ exceptions):
```
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.10   sec  9.90 MBytes  75.6 Mbits/sec    0    163 KBytes
[  5]   1.10-2.03   sec  8.75 MBytes  79.0 Mbits/sec    0    163 KBytes
[  5]   2.03-3.09   sec  10.0 MBytes  78.6 Mbits/sec    0    163 KBytes
[  5]   3.09-4.03   sec  8.75 MBytes  78.8 Mbits/sec    0    163 KBytes
[  5]   4.03-5.11   sec  10.0 MBytes  77.2 Mbits/sec    0    163 KBytes
[  5]   5.11-6.04   sec  8.75 MBytes  78.9 Mbits/sec    0    163 KBytes
[  5]   6.04-7.11   sec  10.0 MBytes  79.0 Mbits/sec    0    172 KBytes
[  5]   7.11-8.03   sec  8.75 MBytes  79.6 Mbits/sec    0    172 KBytes
[  5]   8.03-9.09   sec  10.0 MBytes  79.1 Mbits/sec    0    172 KBytes
[  5]   9.09-10.01  sec  8.75 MBytes  79.6 Mbits/sec    0    172 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.01  sec  93.6 MBytes  78.5 Mbits/sec    0             sender
[  5]   0.00-10.03  sec  93.6 MBytes  78.3 Mbits/sec                  receiver
```

I've pushed the change to my branch: https://github.com/Noltari/openwrt/commits/bcm63xx-net

However, I have to test this on some of my other devices to see if there are any regressions.

**Comment by spliew89** [comment]
> Are all of your devices fast ethernet?
> I'm thinking that maybe it's only reproducible on gigabit ethernet devices. I will do more tests today and see if I can reproduce it on my Comtrend VG-8050 (BCM63268 - gigabit) and on my Sercomm AD1018 (BCM6328 - fast ethernet).

Yes.

> 
> 
> @spliew89 incrementing the number of TX descriptors seems to fix the issue (no more _bcm63xx_enetsw bcm63xx_enetsw.0: xmit called with no tx desc available?_ exceptions):
> 
> ```
> [ ID] Interval           Transfer     Bitrate         Retr  Cwnd
> [  5]   0.00-1.10   sec  9.90 MBytes  75.6 Mbits/sec    0    163 KBytes
> [  5]   1.10-2.03   sec  8.75 MBytes  79.0 Mbits/sec    0    163 KBytes
> [  5]   2.03-3.09   sec  10.0 MBytes  78.6 Mbits/sec    0    163 KBytes
> [  5]   3.09-4.03   sec  8.75 MBytes  78.8 Mbits/sec    0    163 KBytes
> [  5]   4.03-5.11   sec  10.0 MBytes  77.2 Mbits/sec    0    163 KBytes
> [  5]   5.11-6.04   sec  8.75 MBytes  78.9 Mbits/sec    0    163 KBytes
> [  5]   6.04-7.11   sec  10.0 MBytes  79.0 Mbits/sec    0    172 KBytes
> [  5]   7.11-8.03   sec  8.75 MBytes  79.6 Mbits/sec    0    172 KBytes
> [  5]   8.03-9.09   sec  10.0 MBytes  79.1 Mbits/sec    0    172 KBytes
> [  5]   9.09-10.01  sec  8.75 MBytes  79.6 Mbits/sec    0    172 KBytes
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bitrate         Retr
> [  5]   0.00-10.01  sec  93.6 MBytes  78.5 Mbits/sec    0             sender
> [  5]   0.00-10.03  sec  93.6 MBytes  78.3 Mbits/sec                  receiver
> ```
> 
> I've pushed the change to my branch: https://github.com/Noltari/openwrt/commits/bcm63xx-net
> 
> ```
> --- a/drivers/net/ethernet/broadcom/bcm63xx_enet.h
> +++ b/drivers/net/ethernet/broadcom/bcm63xx_enet.h
> @@ -14,7 +14,7 @@
> 
>  /* default number of descriptor */
>  #define BCMENET_DEF_RX_DESC	64
> -#define BCMENET_DEF_TX_DESC	32
> +#define BCMENET_DEF_TX_DESC	48
> 
>  /* maximum burst len for dma (4 bytes unit) */
>  #define BCMENET_DMA_MAXBURST	16
> ```
> 
> However, I have to test this on some of my other devices to see if there are any regressions.

In fact, Jesper Dangaard Brouer mentioned about it.
[http://netoptimizer.blogspot.com/2014/06/pktgen-for-network-overload-testing.html](url)

**Comment by Noltari** [comment]
Merged, thanks!
https://github.com/openwrt/openwrt/commit/342524895c1636734f79f4901ac8a4c3f5f9849a
https://github.com/openwrt/openwrt/commit/36334b2d4b41527e9d0c682441a77aba6449228d

**Pull request closed without merging**
