### PR TITLE
U-boot mvebu: update & add support for Turris Omnia

### PR DESCRIPTION
**Pull request by BKPepe**
My pull requests updates mvebu U-boot to version 2022.01, and while at it, I added U-boot for Turris Omnia. It is necessary to backport two patches for Marvell A38x, which solves DDR training as explained in the commit message. Otherwise, after flashing, you can experience that it requires a reboot of the router and hope that it will boot successfully on the next run.

Updating U-boot can be very dangerous, and that's why I did not include flash instructions in the commit message. While updating U-boot you should have the serial cable, but for experienced users, I was able to proceed with mtd. 

I need to mention that I tried updating U-boot version from the newer version (2019.07). I did not try it on the unit with an older version like 2015.10-rc2, yet.

Having this as it is should not harm and do anything as support in U-boot for Turris Omnia in upstream was improved over the years. 

In the future, I want to add support in ``target/linux/mvebu/image/cortexa9.mk``.

### CODE REVIEW

**Comment by BKPepe** [comment]
If anything goes wrong, there is a possibility to still use this article in Turris documentation https://docs.turris.cz/hw/omnia/serial-boot/ to get running the router.

**Comment by neheb** [comment]
To clarify, this is only for the newer Omnia units, right?

**Comment by BKPepe** [comment]
I would say that it can work on all Turris Omnia units. I tested it on an older revision, but I had already updated U-boot to version 2019.07 and as well with the new fwEnv. So, updating to 2022.01 was smooth.

If you are going to try to update from u-boot 2015.10-rc2, you will also need to update the rescue and update the location of the U-boot environment.

Anyway, there is a U-boot upgrade procedure, which I found on OpenWrt documentation from someone. I did not test it, but it seems like a way to update U-boot to 2019.07 or even replace some U-boot images with newer ones.

**Comment by hauke** [comment]
This looks good to me
@dhewg  Could you have a look please.

**Review by dangowrt — APPROVED** [review]

**Review by dhewg — APPROVED** [review]
Runtime tested on espressobin, everything looks good, thanks!

`Tested-by: Andre Heider <a.heider@gmail.com> # espressobin`

**Comment by BKPepe** [comment]
Changes v1 → v2:

- added @dhewg Tested-by into commit with update U-boot

**Comment by BKPepe** [comment]
Changes v2 → v3:

- rebased on the latest changes on the master branch to fix Githun Actions failure:
```
/home/runner/work/_temp/66f8abcb-e3a0-4f52-87c5-0776d7f1bc13.sh: line 1: .github/workflows/ci_helpers.sh: No such file or directory
```

**Comment by BKPepe** [comment]
> To clarify, this is only for the newer Omnia units, right?

I got a never-used 1 GB Turris Omnia CZ11NIC13 with the version of Turris OS 3.2.1, which we have lying around if anything goes wrong. It has following U-boot versions:
- ``U-Boot SPL 2015.10-rc2 (Aug 18 2016 - 16:22:54)``, 
- ``U-Boot 2015.10-rc2 (Aug 18 2016 - 16:22:54 +0200), Build: jenkins-omnia-test-301``

I followed the documentation on how to flash OpenWrt 21.02.1, and I am sure that I made one small mistake here. I booted it to ramdisk and didn't flash OpenWrt image to eMMC, and I tried to update the U-boot. It worked for me when I replaced the file in ``/usr/share/nor-update/boot`` with a ``u-boot-spl.kwb`` from this pull request and continued with that. It started to boot from TFTP, but followed up with ``Installation with U-Boot 2019.07 or later``, Turris Omnia boots, and it works with a newer version of U-boot. :-)

```
U-Boot SPL 2022.01 (Jan 28 2022 - 12:40:49 +0000)
High speed PHY - Version: 2.0
MiniPCIe/mSATA card detection... MiniPCIe
Detected Device ID 6820
board SerDes lanes topology details:
 | Lane # | Speed |  Type       |
 --------------------------------
 |   0    |   5   | PCIe0       |
 |   1    |   5   | USB3 HOST0  |
 |   2    |   5   | PCIe1       |
 |   3    |   5   | USB3 HOST1  |
 |   4    |   5   | PCIe2       |
 |   5    |   0   | SGMII2      |
 --------------------------------
High speed PHY - Ended Successfully
mv_ddr: 14.0.0 
DDR3 Training Sequence - Switching XBAR Window to FastPath Window
mv_ddr: completed successfully
Trying to boot from SPI


U-Boot 2022.01 (Jan 28 2022 - 12:40:49 +0000)
```

Yeah, maybe the instructions on OpenWrt documentation are incorrect, or I made a small hiccup. Anyway, it is still doable with the UART cable, but still, it is something that I want to look at it and improve the process to be smoother, and it still works with newer revisions of Turris Omnia, so it can be improved over time. Not great, not terrible. This means that it should not be blocked just because of this. I'm reporting what I observed on the first attempt.

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 782d4c8306c89fc8b7e98601acc5b6da0bd596bb, 5c804bc199e43e7d41af3242cba950f88bb29807 and d16bd89c71da6bad5f4d37008217ced3bac4e5d6

**Comment by neheb** [comment]
I'll note I updated my Omnia with its original 2015.10 bootloader. While it worked, TurrisOS no longer booted. But restoring with a flash drive made it boot again. So not painless but not too bad.

**Comment by BKPepe** [comment]
Thanks for the feedback! I think I know what could be a culprit while using Turris OS. Were you using Turris OS 5.x version? There was added a new U-boot env partition ``u-boot-env`` and thus the U-boot environment was not migrated. That's what is going to be addresed within https://gitlab.nic.cz/turris/os/packages/-/merge_requests/894. I will provide instructions for Turris OS soon once this is merged.

Anyway, what is necessary for OpenWrt 21.02 is this pull request: 
https://github.com/openwrt/openwrt/pull/9299 (backported to Turris OS 6.0)

**Comment by neheb** [comment]
Yeah I was using 5. I have backups so nothing was lost.

**Pull request closed without merging**
