### PR TITLE
ipq806x: support L2 cache and rpm clocks scaling

### PR DESCRIPTION
**Pull request by dissent1**
Add support for L2 cache and rpm fabric clocks (APPS and DDR) scaling according to CPU frequency.
Tested on k4.9 and k4.14.

### CODE REVIEW

**Comment by bouwew** [comment]
Just FYI, I tested these patches on an R7800-build with kernel 4.9.76 and they (patch 3) failed when patching the file cpufreq-dt.c

**Comment by dissent1** [comment]
@bouwew maybe there's a leftover in your tree or you didn't pull all these commits (you should apply all)? I've refreshed these patches before committing, so it applies cleanly.

**Comment by pkgadd** [comment]
I've given this a short test on ipq8065/ nbg6817, no regressions, seems to be fine.

**Comment by Ansuel** [comment]
why also this no merge?

**Comment by huaracheguarache** [comment]
Everything seems to be running fine for me, but BogoMIPS values seem low:

```
root@lulu:~# cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 6.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 
CPU implementer	: 0x51
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0x04d
CPU revision	: 0

processor	: 1
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 12.50
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 
CPU implementer	: 0x51
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0x04d
CPU revision	: 0

Hardware	: Generic DT based system
Revision	: 0000
Serial		: 0000000000000000
```

Anything to be worried about?

**Comment by pkgadd** [comment]
@huaracheguarache 
> BogoMIPS values seem low

Ignore bogomips completely, they aren't a benchmark and contain no intrinsic information at all - as the name implies, the value is totally bogus. See [Revert 9fc2105aeaaf56b0cf75296a84702d0f9e64437b to fix pyaudio (and probably more)](https://patchwork.kernel.org/patch/5564851/) for some details.

In short, in contrast to old systems without timers (those showed a rough relation between clock rate (not performance!) and bogomips), contemporary ones which do actually use hardware timers instead of deriving the time base from the clock frequency (which is fluctuation on most modern platforms to save power or reduce hear). In practice this means that the bogomips value is generally very low on any modern SOCs (rather than related to the clock frequency). Consequently in 2015 it was attempted to remove the BogoMIPS entry from cpuinfo completely, unfortunately by that time multiple userspace programs had started to read this value and started misbehaving on existing systems in its absense. Following Linus' rule of "no-regressions!", this change had to be reverted - but that doesn't make the value itself less bogus. During the discussions around this bug, it was suggest to report a fixed value of "BogoMIPS: 1" (to avoid crashed because of missing this entry and to avoid division by zero - which could have happened in case of "BogoMIPS: 0") - unfortunately it became obvious that some applications tried to be smart and varied their behaviour based on this value, "no regressions" struck again, so the original calculation had to be reinstated. Again, this doesn't make the value itself less bogus, it just makes systems that had been working before (especially those without hardware timers) keep working now and in the future - the values on modern SOCs (with hardware timers and variable frequencies) remain useless (very) low (usually 1-2 figure range), but those SOCs never worked before (no regression possible) --> it's the application (userspace) developers to fix their stuff.

Just to put it into perspective:

- the venerable Linksys WRT-54GL (BCM5352, 200 MHz, mips32, 2005 vintage, but based on older SOCs) reports
  BogoMIPS: 199.06
- TP-Link TL-WDR4300 (AR9344, 560 MHz, mips 74Kc, 2012 vintage) reports
  BogoMIPS: 274.02
- ZyXEL NBG6817 (IPQ8065, 2*1.7 GHz, ARMv7/ ~cortex A15, 2016 vintage) reports
  BogoMIPS: 21.87

...now try to correlate the BogoMIPS value with the actual SOC performance (indeed, that doesn't work).

**Comment by fantom-x** [comment]
I have been running this for a while and saw no regressions.

**Comment by gnufsh** [comment]
I am testing this on the ipq8065/R7800 and it seems to work fine.

**Comment by nbd168** [comment]
Sorry that I didn't have time to review this earlier. I'll take a look at the patches now.

**Comment by nbd168** [comment]
I noticed that you're hacking a lot of ipq806x specific code into the generic cpufreq-dt driver. I think it would be a lot less messy if you just fork that driver and create an ipq806x specific one instead.

**Pull request closed without merging**
