### PR TITLE
base-files: informative service command in /etc/shinit

### PR DESCRIPTION
**Pull request by stangri**
This patch ~brings back the service command to /etc/profile. In addition, when listing services it~ shows services enabled/disabled and running status, when the `service` command is invoked with no/invalid arguments, like this:

```
Usage: service <service> [command]
The following services are available:
/etc/init.d/acme                   enabled         stopped
/etc/init.d/boot                   enabled         stopped
/etc/init.d/cron                   enabled         running
/etc/init.d/dnsmasq                enabled         running
...
```

I was helped a lot in the mailing list trying to put this together in one nice command. Thank you to everyone who replied and sorry it took me a while to submit.

Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by aparcar** [comment]
Tested and works, however I had to manually source `/etc/profile`. Is that intended?

**Comment by stangri** [comment]
> Tested and works, however I had to manually source `/etc/profile`. Is that intended?

No, my understanding was that the `/etc/profile` is sourced during shell login. Is it not anymore? What would be the proper file to place this code in then? Was that the reason the `service` function was moved out of the `/etc/profile`?

**Comment by aparcar** [comment]
I think the easiest is you track it down via `git log etc/profile`.

**Comment by stangri** [comment]
Thank you, found the change, updated PR.

**Comment by stangri** [comment]
@aparcar @adschm any additional comments? Please merge if accepted.

**Comment by aparcar** [comment]
I'm okay with this change, I don't think anyone would parse the output of the `service` command directly.

**Review by aparcar — APPROVED** [review]

**Comment by stangri** [comment]
Please merge.

**Comment by aparcar** [comment]
This patch introduces a trailing white space and lacks a commit message. Please add an example output to the commit message.

**Review by aparcar — CHANGES_REQUESTED** [review]
Missing commit message and trailing white space error.

**Review by aparcar — APPROVED** [review]

**Comment by stangri** [comment]
@aparcar Paul, can you invite someone else to be a second reviewer for this, so it can be merged? This is my first PR outside of packages/luci, I don't know what to do.

**Comment by aparcar** [comment]
Just wait till I'm back on my Laptop :)

**Comment by adschm** [comment]
PKG_RELEASE needs to be bumped.

**Comment by stangri** [comment]
> PKG_RELEASE needs to be bumped.

Done!

**Comment by aparcar** [comment]
Merged. Next time please limit commit msg length to 72

**Comment by adschm** [comment]
You broke the commit title during picking ...

**Comment by aparcar** [comment]
All right I'm sorry, wonder how that happened

**Comment by adschm** [comment]
The separating empty line between the title and the message sometimes gets eaten by something (might also depend on how you picked the commit). One should always check with `git log` before pushing ...

**Comment by stangri** [comment]
> Please add an example output to the commit message.

> Merged. Next time please limit commit msg length to 72

@aparcar Paul, I'm not sure if I understood your first message correctly, please advise so I'll know what to do next time.

**Comment by adschm** [comment]
@stangri Each line in the commit message should have a maximum of 74 characters.

But apparently, your commit message (at least for the first commit) was correct, maybe it got mangled at aparcar's repo.

**Comment by adschm** [comment]
And talking about next time: no merge commit...

**Pull request closed without merging**
