### PR TITLE
toolchain/gdb: update to 14.1

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
https://lists.gnu.org/archive/html/info-gnu/2023-12/msg00001.html

Refresh patch:
- 120-fix-compile-flag-mismatch.patch

### CODE REVIEW

**Comment by Ansuel** [comment]
Btw this broke the CI... For some reason the toolchain doesn't compile anymore with gdb selected.

**Comment by PolynomialDivision** [comment]
Are you sure that this is not caused by https://github.com/openwrt/openwrt/commit/66dfbca262f4e6ebc1b4f94fb1c4482894c26d0c ?

**Comment by Ansuel** [comment]
@PolynomialDivision possible looking at the previous run CI run. Thing is that searching online gives error on zstd while this is more generic.

**Comment by nbd168** [comment]
I did some digging, and I believe it should be fixed by 2872ff7be19cfd20c95c4cbc880c0af38f82ea15

**Pull request closed without merging**
