### PR TITLE
bpf-headers: fix llvm invocation

### PR DESCRIPTION
**Pull request by rockdrilla**
- specify CC target explicitly
- define KBUILD_SYM32=n to select "native" build format (if building with 64-bit arch)
- rewrap lines (for good)

### CODE REVIEW

**Comment by rockdrilla** [comment]
Compile-tested: mediatek/filogic (GL.iNet GL-MT6000).

**Comment by Ansuel** [comment]
> * define KBUILD_SYM32=n to select "native" build format (if building with 64-bit arch)

we were targeting 32bit to support both... isn't that wrong for bpf stuff?

**Comment by rockdrilla** [comment]
@Ansuel `llvm-bpf` doesn't understand `-msym32` which arrives from [`arch/mips/Makefile`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/mips/Makefile?h=v5.15.158#n283).

Hovewer, these files are using `KBUILD_64BIT_SYM32`:
- `arch/mips/Makefile`
- `arch/mips/dec/int-handler.S`
- `arch/mips/include/asm/pgtable-64.h`
- `arch/mips/include/asm/stackframe.h`
- `arch/mips/kernel/genex.S`

**Comment by robimarko** [comment]
Yeah:
`clang: error: unknown argument: '-msym32'`

Clang does not support `-msym32`, that seems to be a GCC only thing.

**Comment by rockdrilla** [comment]
@robimarko friendly ping!

**Comment by robimarko** [comment]
I am going to need and explanation of what this does exactly and why its needed as BPF isn't really my thing

**Comment by rockdrilla** [comment]
This MR ensures that correct target type is used - as with [#15703](https://github.com/openwrt/openwrt/pull/15703).

**Comment by robimarko** [comment]
I get what you are trying to achieve, but why `KBUILD_SYM32=n` ?

**Comment by rockdrilla** [comment]
I've encountered FTBFS while building for mediatek/filogic at the same time as #15704.

As with #15703, this MR is not really essential for LLVM-BPF toolchain built by OpenWrt (after #15704 was merged) but is required to present if using "host toolchain" (which is not necessary was built by/with OpenWrt).

Ref: [arch/mips/Makefile:294](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/mips/Makefile?h=v6.6.50#n294)

**Comment by robimarko** [comment]
Wait, now I am lost, if you were targeting filogic, how is this even impacting you?

Cause, as far as I can tell it should only impact 64 bit MIPS builds

**Comment by robimarko** [comment]
@nbd168 Thanks, now this change makes sense

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
