### PR TITLE
dnsmasq: allow building without tftp server support

### PR DESCRIPTION
**Pull request by rosysong**
Signed-off-by: Rosy Song <rosysong@rosinson.com>

### CODE REVIEW

**Comment by rosysong** [comment]
saving 100+ KBytes memory if I remember correctly

**Comment by dedeckeh** [comment]
@rosysong Can you make the commit message more verbose stating how much the size decreases ?

**Comment by rosysong** [comment]
@dedeckeh OK, here is the newer commit.

**Comment by rosysong** [comment]
@dedeckeh  It's done, please check it again, thanks!

**Comment by dedeckeh** [comment]
Patch pushed to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=27be78ef461af31015a6c9cfc334b3c5c69b3953); thx

**Pull request closed without merging**
