### PR TITLE
kernel: bump 5.15 to 5.15.123

### PR DESCRIPTION
**Pull request by graysky2**
Manually rebased:
	bcm4908/patches-5.15/071-v6.1-0001-net-broadcom-bcm4908_enet-handle-EPROBE_DEFER-when-g.patch
	bcm53xx/patches-5.15/180-usb-xhci-add-support-for-performing-fake-doorbell.patch

Removed upstreamed:
	backport-5.15/735-v6.5-net-bgmac-postpone-turning-IRQs-off-to-avoid-SoC-han.patch[1]
	backport-5.15/817-v6.5-01-leds-trigger-netdev-Recheck-NETDEV_LED_MODE_LINKUP-o.patch[2]
	pending-5.15/143-jffs2-reduce-stack-usage-in-jffs2_build_xattr_subsys.patch[3]
	pending-5.15/160-workqueue-fix-enum-type-for-gcc-13.patch[4]
	bcm53xx/patches-5.15/036-v6.5-0003-ARM-dts-BCM5301X-Drop-clock-names-from-the-SPI-node.patch[5]
	bcm53xx/patches-5.15/036-v6.5-0015-ARM-dts-BCM5301X-fix-duplex-full-full-duplex.patch[6]

Don't know how to handle, should it be removed or rebased:
	ipq40xx/patches-5.15/902-dts-ipq4019-ap-dk04.1.patch*

All other patches automatically rebased.

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.123&id=02474292a44205c1eb5a03634ead155a3c9134f4
2. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.123&id=86b93cbfe104e99fd3d25a49748b99fb88101573
3. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.123&id=79b9ab357b6f5675007f4c02ff8765cbd8dc06a2
4. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.123&id=d528faa9e828b9fc46dfb684a2a9fd8c2e860ed8
5. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.123&id=5899bc4058e89d5110a23797ff94439c53b77c25
6. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.123&id=95afd2c7c7d26087730dc938709e025a303e5499
* When I inspected arch/arm/boot/dts/qcom-ipq4019-ap.dk04.1.dtsi.rej generated by quilt, they seemed out of context for the file entirely. I just removed the patch in order to get this PR out there for review. Someone with more knowledge about this will need to comment and potentially add the patch back and fix it as needed if it needs to stay.

Build system: x86/64
Build-tested: ramips/tplink_archer-a6-v3
Run-tested: ramips/tplink_archer-a6-v3

### CODE REVIEW

**Comment by hauke** [comment]
The nand node was moved, see https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/arch/arm/boot/dts/qcom-ipq4019-ap.dk04.1.dtsi?id=v5.15.123&id2=v5.15.120

**Comment by Gingernut1978** [comment]
ping @robimarko

**Comment by john-tho** [comment]
> I am still not sure what needs to happen. I took a stab at it [here](https://github.com/openwrt/openwrt/pull/13172/commits/b9bf0239f6cb124c1b0cd9f2d652f8f26f4f56c5) but I don't think it's right.

Too much changing.

Downstream patch:
https://github.com/openwrt/openwrt/blob/master/target/linux/ipq40xx/patches-5.15/902-dts-ipq4019-ap-dk04.1.patch

Upstream change:
> The nand node was moved, see https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/arch/arm/boot/dts/qcom-ipq4019-ap.dk04.1.dtsi?id=v5.15.123&id2=v5.15.120

Need a little more understanding of what the downstream patch wants to achieve. The chunk that fails adds nodes to the [`soc` DTS node](https://elixir.bootlin.com/linux/v5.15.123/source/arch/arm/boot/dts/qcom-ipq4019-ap.dk04.1.dtsi#L25), after the [`pci` node](https://elixir.bootlin.com/linux/v5.15.123/source/arch/arm/boot/dts/qcom-ipq4019-ap.dk04.1.dtsi#L103).
The only thing that should change in the downstream _patch_ here is the [patch context (`qpic-nand` node should disappear, given it was removed upstream)](https://github.com/openwrt/openwrt/blob/dcdcfc15115a1038e90f21f5aa41726d9c7e2fe5/target/linux/ipq40xx/patches-5.15/902-dts-ipq4019-ap-dk04.1.patch#L130). Context being the parts of the file which are not being changed by the patch.

**Comment by robimarko** [comment]
We should probably finally get rid of QCA reference board support as other than causing pain every time something changes I doubt anybody is actually using those.

Most of the changes in those DK board patches are suspicious to put it mildly and basically need to be redone.

**Comment by hauke** [comment]
This should make the ipq40xx target build: 7107a6163e2af3350461003a6a6b08e3aacd1104 I think I pushed it into your branch. 
It failed before like this:
````
  HDRINST usr/include/asm/sockios.h
  INSTALL /__w/openwrt/openwrt/openwrt/build_dir/target-arm-openwrt-linux-muslgnueabi_musl/linux-ipq40xx_chromium/linux-5.15.123/user_headers/include
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-arm-openwrt-linux-muslgnueabi_musl/linux-ipq40xx_chromium/linux-5.15.123'
arch/arm/boot/dts/qcom-ipq4019-ap.dk04.1.dtsi:158.25-160.4: ERROR (duplicate_label): /soc/nand-controller@79b0000/dma@8e04000: Duplicate label 'cryptobam' on /soc/nand-controller@79b0000/dma@8e04000 and /soc/dma@8e04000
arch/arm/boot/dts/qcom-ipq4019.dtsi:765.28-773.5: ERROR (duplicate_label): /soc/ssphy@9a000: Duplicate label 'usb3_ss_phy' on /soc/ssphy@9a000 and /soc/nand-controller@79b0000/ssphy@9a000
arch/arm/boot/dts/qcom-ipq4019.dtsi:775.28-783.5: ERROR (duplicate_label): /soc/hsphy@a6000: Duplicate label 'usb3_hs_phy' on /soc/hsphy@a6000 and /soc/nand-controller@79b0000/hsphy@a6000
arch/arm/boot/dts/qcom-ipq4019.dtsi:785.22-805.5: ERROR (duplicate_label): /soc/usb3@8af8800: Duplicate label 'usb3' on /soc/usb3@8af8800 and /soc/nand-controller@79b0000/usb3@8af8800
arch/arm/boot/dts/qcom-ipq4019.dtsi:807.28-815.5: ERROR (duplicate_label): /soc/hsphy@a8000: Duplicate label 'usb2_hs_phy' on /soc/hsphy@a8000 and /soc/nand-controller@79b0000/hsphy@a8000
arch/arm/boot/dts/qcom-ipq4019.dtsi:817.22-837.5: ERROR (duplicate_label): /soc/usb2@60f8800: Duplicate label 'usb2' on /soc/usb2@60f8800 and /soc/nand-controller@79b0000/usb2@60f8800
ERROR: Input tree has errors, aborting (use -f to force output)
make[5]: *** [scripts/Makefile.lib:347: arch/arm/boot/dts/qcom-ipq4019-ap.dk04.1-c1.dtb] Error 2
make[4]: *** [Makefile:1451: dtbs] Error 2
make[4]: *** Waiting for unfinished jobs....
````

**Comment by hauke** [comment]
hmm It looks like I confused github with my push into your branch. ;-)
I assumed changes from this branch should show up in this pull request: https://github.com/graysky2/openwrt/commits/5.15

**Comment by graysky2** [comment]
I got it, @hauke.  If it builds fine, I will squash all into a single commit.

**Pull request merged**
