### PR TITLE
tools/mklibs: update to 0.1.45

### PR DESCRIPTION
**Pull request by neheb**
Remove 2to3 patch. Upstream already did this.

Remove uClibc patches as only musl is present now.

Refresh others.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by rsalvaterra** [comment]
Have you build/run-tested this? It's failing here. Doing a dirclean build now, hopefully it's only something on my side…

**Comment by rsalvaterra** [comment]
It's not entirely upstream's fault. Some of our patches also need to be converted to Python 3.

**Comment by neheb** [comment]
That is strange…

**Comment by neheb** [comment]
This looks premature:

https://salsa.debian.org/installer-team/mklibs/-/commit/1570a770410db780cf526603b6b54af6e3f840df
https://salsa.debian.org/installer-team/mklibs/-/commit/2e3e0a8705e6b0f2abe310a81d3cfe52c205e22e

Next version I guess...

**Comment by neheb** [comment]
Oh it's just the second commit that needs to be backported...

**Comment by neheb** [comment]
The problem was local patches. Please retest.

**Comment by rsalvaterra** [comment]
> Alright this should be fine now. I ran through pylint. It's reporting no real errors.

I tested this last update and it does seem to do the trick here (ath79/generic), thanks!

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in c8b7065f61b75cab17b3b39c5091aa8de14f0aa8.

**Pull request closed without merging**
