### PR TITLE
tools/ccache: find libzstd using rpath

### PR DESCRIPTION
**Pull request by tomjnixon**
Previously, ccache would end up using the system libzstd, which is not supposed to be a build requirement.

I found this when building on nixos (where zstd wasn't available because it wasn't specified as a dependency), but I believe this kind of issue should be fixed for the sake of reproducibility and general cleanliness.

The same thing happens on ubuntu (though doesn't cause a problem); I've tested this on both.

You can see the results of this with `ldd staging_dir/host/bin/ccache`:

before:

        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f3e2ad51000)

after:

        libzstd.so.1 => /openwrt/staging_dir/host/lib/libzstd.so.1 (0x00007f71bf072000)

### CODE REVIEW

**Comment by neheb** [comment]
Seems legit. On Fedora 33, I can't uninstall host libzstd so I can't really test:

```
Error: 
 Problem: The operation would result in removing the following protected packages: systemd
(try to add '--skip-broken' to skip uninstallable packages)

libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f7011b2e000)
```

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
Yeah this is needed. I just tested this on my CentOS 7 VM:

```
	libzstd.so.1 => not found
```

**Comment by aparcar** [comment]
Thanks!

**Comment by tomjnixon** [comment]
Thanks for merging!

**Pull request closed without merging**
