### PR TITLE
tools/fakeroot: update to 1.27

### PR DESCRIPTION
**Pull request by neheb**
Remove macOS stuff. Upstream has fixed it in the same way.

Refreshed patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by aparcar** [comment]
Doesn't work on my system:

```
communicate.c:485:27: error: use of undeclared identifier 'SOL_TCP'
  if (setsockopt(comm_sd, SOL_TCP, TCP_NODELAY, &val, sizeof (val)) < 0)
 ```

**Comment by neheb** [comment]
What an interesting error…

**Comment by neheb** [comment]
Oh that's great. Changes for 1.27 are not public in any git repo.

**Comment by aparcar** [comment]
Your PR mentions 1.37?

**Comment by neheb** [comment]
Fixed.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in 40f91f6a2f633d2fbca13aa7ad6e5be1e79f5aa6.

**Pull request closed without merging**
