### PR TITLE
busybox: nslookup: ensure unique transaction IDs for the DNS queries

### PR DESCRIPTION
**Pull request by ukleinek**
On machines with a coarse monotonic clock (here: TP-Link RE200 powered by a MediaTek MT7620A) it can happen that the two DNS requests (for A and AAAA) share the same transaction ID. If this happens the second reply is wrongly dropped and nslookup reports "No answer".

Fix this by ensuring that the transaction IDs are unique.

An earlier attempt to fix that was discussed at
http://lists.openwrt.org/pipermail/openwrt-devel/2022-October/039545.html which ensured (somewhat) that res_mkquery doesn't create duplicate ids when called twice in the same clock tick. But it was agreed that this needs fixing in the caller of res_mkquery. I already sent a patch to the busybox mailing list, but no response so far.

This is https://github.com/openwrt/openwrt/pull/10957 rebased to master.

### CODE REVIEW

**Comment by ukleinek** [comment]
A backport into 22.03.x would be great, it actively hurts me there.

**Review by jow- — APPROVED** [review]

**Comment by Ansuel** [comment]
@ukleinek it's bad that they still didn't answer to the patch...
But anyway I will merge this and backport to 22.03

**Comment by Ansuel** [comment]
Just notice you disabled push by maintainers... Can you rebase this on top of master so i can flag this pr as merged?
If you can't np but this pr won't be flagged as merged by github but just closed.

**Comment by ukleinek** [comment]
@Ansuel Rebased to current master.
(I don't understand the requirement, but it seems quite a popular concept *shrug*)

**Comment by Ansuel** [comment]
Backported to openwrt-22.03 with bc8e24c654050d7fcafd8d6f179bf1ffdf6045fa

**Comment by Ansuel** [comment]
> @Ansuel Rebased to current master. (I don't understand the requirement, but it seems quite a popular concept _shrug_)

The rebase is needed or pr can't be applied with `git merge --ff-only` and this is the only way to make github happy and flag pr as merged.

**Comment by ukleinek** [comment]
> > @Ansuel Rebased to current master. (I don't understand the requirement, but it seems quite a popular concept _shrug_)
> 
> The rebase is needed or pr can't be applied with `git merge --ff-only` and this is the only way to make github happy and flag pr as merged.

If you drop `--ff-only` it should work just fine. Of course you get a more complicate git history then, but in my eyes that is the lesser evil.

In the devel bubble I usually live in (i.e. the linux kernel world), rebasing isn't welcome as it annoys people that based their work on the rebased commit (not a big issue for this patch I guess) and it throws away testing the committer might have done.

So if you want, keeping my commit as is (i.e. unrebased) plus an added merge commit better documents the development process. And if really something should break, bisecting can differentiate between "broken on the submitter's tree" and "broken on integration (only)". I didn't pay attention to that, but if I based my change on a commit that is contained in the fork point of the 22.03.x release branch you could even merge the commit in both branches (master and 22.03.x) without the need for cherry-picking which in my eyes also has some charm.

(I don't wanna be a PITA, if the discussion annoys you, please ignore.)

**Comment by ukleinek** [comment]
Oh, and I forgot: Thanks for acting on my PR. Very nice that these wifi issues were found which made my change contained in a released version quite a bit faster I guess :-)

**Pull request merged**
