### PR TITLE
libbsd: update to 0.11.7

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Changes:
084911c Release libbsd 0.11.7
3538d38 man: Discourage using the library in non-overlay mode 03fccd1 include: Adjust reallocarray() per glibc adoption 6b6e686 include: Adjust arc4random() per glibc adoption da1f45a include: explicit_bzero() requires _DEFAULT_SOURCE 2f9eddc include: Simplify glibc version dependent macro handling 28298ac doc: Switch references from pkg-config to pkgconf ef981f9 doc: Add missing empty line to separate README sections 6928d78 doc: Refer to the main git repository as primary d586575 test: Fix explicit_bzero() test on the Hurd be327c6 fgetwln: Add comment about lack of getwline(3) for recommendation a14612d setmode: Dot not use saveset after free
f4baceb man: Rewrite gerprogname(3bsd) from scratch f35c545 man: Lowercase man page title
b466b14 man: Document that some arc4random(3) functions are now in glibc 2.36 1f6a48b Sync arc4random(3) implementation from OpenBSD 873639e Fix ELF support for big endian SH
c9c78fd man: Use -compact also for alternative functions in libbsd(7) 5f21307 getentropy: Fix function cast for getauxval()

### CODE REVIEW

**Comment by neheb** [comment]
```
3538d38 man: Discourage using the library in non-overlay mode
```

Sounds about right. Should probably fix all packages that don't.

**Comment by neheb** [comment]
Yeah https://github.com/openwrt/packages/pull/19615

libbsd-overlay.pc needs to be fixed to not use host paths.

**Comment by xuefer** [comment]
> ```
> 3538d38 man: Discourage using the library in non-overlay mode
> ```
> 
> Sounds about right. Should probably fix all packages that don't.

#11008

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in 8ad82d31a0b4f8e658680b683e7e63ba2333ba30.

**Pull request closed without merging**
