### PR TITLE
prereq-build: increase GCC requirement to 8

### PR DESCRIPTION
**Pull request by neheb**
The current minimum OS requirement for OpenWrt is Ubuntu 18.04, which includes 7 and 8. 8 is necessary for ccache.

gcc and g+++ are now symlinked to staging_dir, similar to Python.

ping @jow- @Ansuel

### CODE REVIEW

**Comment by hauke** [comment]
The default compiler in Ubuntu 18.04 is GCC 7. You can manually install a more modern one, but the gcc command uses gcc 7 by default.

I would like to wait with this change till after the next OpenWrt version was branched off.

**Comment by neheb** [comment]
Note that ccache does not work because of this right now.

**Comment by hauke** [comment]
It is fine for me if you need GCC 8 for ccache.

**Comment by neheb** [comment]
I guess I'll try patching it. I prefer this PR though.

**Comment by mpratt14** [comment]
this is much better than a patch to ccache IMO

branching should happen soon anyway right?

**Comment by hauke** [comment]
I would just ignore that ccache does not work when someone uses gcc 7. People who are still using GCC 7 then can not use ccache and will run into errors. that is fine with me.
I would not invest time in making ccache work with gcc 7.

**Comment by dfateyev** [comment]
I think it should be closed. Current master state doesn't imply specific handling of older GCC versions.

**Comment by neheb** [comment]
@hauke 23.05 was branched

**Comment by neheb** [comment]
ping

**Review by KanjiMonster — APPROVED** [review]
LGTM, especially in light of #13102, i.e. patchelf 0.18 not building with GCC 7 or lower. So we currently have an effective minimum of 8 anyway.

**Pull request merged**
