### PR TITLE
treewide: nuke DRIVER_11W_SUPPORT

### PR DESCRIPTION
**Pull request by dobo90**
treewide: nuke DRIVER_11W_SUPPORT

As of hostapd upstream commit 7d2ed8ba "Remove CONFIG_IEEE80211W build parameter"
https://w1.fi/cgit/hostap/commit?id=7d2ed8bae86a31dd2df45c24b3f7281d55315482
802.11w feature is always enabled in the build time.

It doesn't make sense to opt-in 802.11w per driver as hostapd will always
be compiled with this feature enabled.

As suggested by Hauke Mehrtens, for now keep 11w enabled in build_features.h
for compatibility reasons. This option will be dropped when LuCI is adjusted.

Signed-off-by: Dobroslaw Kijowski <dobo90@gmail.com>

### CODE REVIEW

**Comment by dobo90** [comment]
Another option would be to nuke DRIVER_11W_SUPPORT. But I'm not sure whether all wireless drivers have 802.11w support. That's why I've restored the original hostapd behavior before CONFIG_IEEE80211W build parameter removal.

This commit brings back ability to configure 802.11w in LuCI.

**Comment by dobo90** [comment]
I've prepared also code changes for nuking DRIVER_11W_SUPPORT. They are more intrusive but I think it's a better way to solve the problem (as hostapd will always be compiled with 802.11w enabled). Changes are available at:

https://github.com/dobo90/openwrt/commits/nuke_driver_11w_support
https://github.com/dobo90/luci/commits/nuke_driver_11w_support

**Comment by hauke** [comment]
I would prefer if we remove the DRIVER_11W_SUPPORT option. 
Most drivers support ieee80211w by now, OpenWrt activates this option if any driver which was build supports it. It is always activated in our release builds. 
We could keep support for 11w in build_features.h and activate it unconditionally for some time for backwards compatibility.

**Comment by dobo90** [comment]
I've pushed the commit implementing changes suggested by @hauke into the same branch as before.

**Comment by dobo90** [comment]
It's been hanging for a long while. Can someone of you review this? @hauke, @adschm, @jow- 
A friendly remainder: without those changes LuCI doesn't show 802.11w settings at all.

**Comment by adschm** [comment]
Please bump PKG_RELEASE for all _packages_ you touch.

**Comment by ynezz** [comment]
Please rebase.

**Comment by dobo90** [comment]
@ynezz rebased.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
