### PR TITLE
libnftnl: update to 1.2.7

### PR DESCRIPTION
**Pull request by jen1-sys**
libnftnl: update to 1.2.7

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Can you remove the "libs/"? See other commits done to packages.

**Comment by PolynomialDivision** [comment]
Further, we add a link to the Releas Notes or Changelog,... to the commit message.

**Comment by hauke** [comment]
How did you test this?

**Comment by jen1-sys** [comment]
@hauke  Please read my comment here how I build my imagehttps://github.com/openwrt/openwrt/pull/16493

Here are some pics and link to the image builder https://www.mediafire.com/file/aigqtqnzyfth9d3/openwrt-imagebuilder-bcm53xx-generic.Linux-x86_64.tar.zst/file

Screenshot 2024-09-29 081424
Screenshot 2024-09-29 081449
Screenshot 2024-09-29 081527


Sorry I am busy, can't explain in details now,

**Comment by rockdrilla** [comment]
Compile/run-tested: mediatek/filogic (GL.iNet GL-MT6000).
NB: `OPENWRT_TAINTS="no-all glibc"`

**Comment by rockdrilla** [comment]
Heads up: libnftnl 1.2.8 is released: https://lwn.net/Articles/992761/
* incorrect validation of dynset netlink attribute from the kernel.
* don't append a newline when printing a rule.

**Comment by Neustradamus** [comment]
To follow this PR :)

**Comment by Rondom** [comment]
@jen1-sys Nitpick: As a general guideline it is a good idea to look at the commit message of previous updates.
https://github.com/openwrt/openwrt/commits/7ab7cf464f737270abc53a635fbc9253a63b5583/package/libs/libnftnl/Makefile Often, we also add a link to the changelog(s) to the commit message.

**Comment by hauke** [comment]
superseded by d9ed0d438b0ec7d813764d629be7a753dc3fbac5 from #16769.

**Pull request closed without merging**
