### PR TITLE
Add STAGING_DIR_HOSTPKG variable

### PR DESCRIPTION
**Pull request by neocturne**
At the moment, many packages in https://github.com/openwrt/packages hardcode the prefix `$(STAGING_DIR)/host` for host packages (as `$(STAGING_DIR_HOST)` is mostly used by tools only now). We're thinking about changing the prefix in LEDE, and after some changes that caused issues (see openwrt/packages#3297, openwrt/packages#3423, openwrt/packages#3433) we've come to the conclusion that introducing a new variable STAGING_DIR_HOSTPKG for this directory is the cleanest solution.

This adds the variable to OpenWrt in the same way it was done in LEDE, so community packages can start using it.

### CODE REVIEW

**Comment by NeoRaider** [comment]
Ping - is there an issue with this PR?

**Comment by NeoRaider** [comment]
Any chance we can get this merged soon? This is currently blocking some refactoring I'd like to do...

**Comment by wigyori** [comment]
I'll check this today.

**Comment by flokli** [comment]
@wigyori Did you already took a look at this?

**Comment by NeoRaider** [comment]
I don't mean to nag, but... ping?

**Comment by NeoRaider** [comment]
Ping. This is a trivial 2-line change.

**Comment by lemoer** [comment]
I also want to bump this issue, because me and a lot of other people want to see the gluon project ported to lede. This would be a lot easier, if you could merge this PR in openwrt.

**Comment by AiyionPrime** [comment]
I'd like to bump this as well.

**Comment by lemoer** [comment]
@wigyori Please review and merge this PR. It's quite simple! And the CI test have not failed really. It seems as the CI itself has some issues.

**Comment by AiyionPrime** [comment]
thanks @wigyori

**Pull request merged**
