### PR TITLE
ar71xx:add support for E1700AC E558 E600G/GAC E750A/G

### PR DESCRIPTION
**Pull request by zhangsd20**
Qxwlan E1700AC v2 is based on Qualcomm QCA9563 + QCA9880 + QCA8334.

Specification:

- 750/400/250 MHz (CPU/DDR/AHB)
- 128 MB of RAM (DDR2)
- 8/16 MB of FLASH (SPI NOR)
- 3T3R 2.4 GHz (QCA9563) with external FEM (SKY85309-11)
- 3T3R 5 GHz (QCA9880) with external FEM (SKY85728-11)
- 2x 10/100/1000 Mbps Ethernet (one port with PoE support)
- 1x miniPCIe slot (USB 2.0 bus only)
- 1x microSIM slot
- 1x USB 2.0
- 5x LED (4 driven by GPIO)
- 1x button (reset)
- 1x 2-pos switch
- 1x DC jack for main power input (9-48 V)
- UART (J5) and LEDs (J13) headers on PCB

Qxwlan E558 v2 is based on Qualcomm QCA9558 + AR8327.

Specification:

- 720/600/200 MHz (CPU/DDR/AHB)
- 128 MB of RAM (DDR2)
- 8/16 MB of FLASH (SPI NOR)
- 2T3R 2.4 GHz (QCA9558)
- 3x 10/100/1000 Mbps Ethernet (one port with PoE support)
- 4x miniPCIe slot (USB 2.0 bus only)
- 1x microSIM slot
- 5x LED (4 driven by GPIO)
- 1x button (reset)
- 1x 3-pos switch
- 1x DC jack for main power input (9-48 V)
- UART (JP5) and LEDs (J8) headers on PCB

Qxwlan E750A v4 is based on Qualcomm QCA9344.

Specification:

- 560/450/225 MHz (CPU/DDR/AHB)
- 128 MB of RAM (DDR2)
- 8/16 MB of FLASH (SPI NOR)
- 2T3R 5G GHz (AR9344)
- 2x 10/100 Mbps Ethernet (one port with PoE support)
- 1x miniPCIe slot (USB 2.0 bus only)
- 7x LED (6 driven by GPIO)
- 1x button (reset)
- 1x DC jack for main power input (9-48 V)
- UART (J23) and LEDs (J2) headers on PCB

Qxwlan E750G v8 is based on Qualcomm QCA9344.

Specification:

- 560/450/225 MHz (CPU/DDR/AHB)
- 128 MB of RAM (DDR2)
- 8/16 MB of FLASH (SPI NOR)
- 2T3R 2.4G GHz (AR9344)
- 2x 10/100 Mbps Ethernet (PoE support)
- 2x 10/100/1000 Mbps Ethernet
- 7x LED (6 driven by GPIO)
- 1x button (reset)
- 1x DC jack for main power input (9-48 V)
- UART (J23) and LEDs (J2) headers on PCB

Qxwlan E600G is based on Qualcomm/Atheros QCA9531.

Specification:

- 650/391/216 MHz (CPU/DDR/AHB)
- 64/128 MB of RAM (DDR2)
- 8/16 MB of FLASH (SPI NOR)
- 2T2R 2.4 GHz (QCA9531) with external PA (LXK-6601)
- 2x 10/100 Mbps Ethernet (one port with PoE support)
- 1x miniPCIe slot (with PCIe and USB 2.0 buses)
- 1x microSIM slot
- 5x LED (4 driven by GPIO)
- 1x button (reset)
- 1x DC jack for main power input (9-48 V)
- UART (J100), SIM (J34), JTAG (J5) and LEDs (J7) headers on PCB

Qxwlan E600GAC is based on Qualcomm/Atheros QCA9531 + QCA9887.

Specification:

- 650/391/216 MHz (CPU/DDR/AHB)
- 64/128 MB of RAM (DDR2)
- 8/16 MB of FLASH (SPI NOR)
- 2T2R 2.4 GHz (QCA9531)
- 1T1R 5 GHz (QCA9887) with external FEM (SKY85703-11)
- 2x 10/100 Mbps Ethernet
- 6x LED (1x RGB, 5 driven by GPIO)
- 1x button (reset)
- 1x DC jack for main power input (9-12 V)
- UART (J100), USB (J102), JTAG (J5) and LEDs (J7) header on PCB

Flash instruction (using U-Boot CLI and tftp server):

1. Configure PC with static IP 192.168.1.10 and tftp server.
2. Rename "sysupgrade" filename to "firmware.bin" and place it in tftp
   server directory.
3. Connect PC with one of RJ45 ports, power up the board and press
   "enter" key to access U-Boot CLI.
4. Use the following command to update the device to OpenWrt: "run lfw".

Flash instruction (using U-Boot web-based recovery):

1. Configure PC with static IP 192.168.1.xxx(2-254)/24.
2. Connect PC with one of RJ45 ports, press the reset button, power up
   the board and keep button pressed for around 6-7 seconds, until LEDs
   start flashing.
3. Open your browser and enter 192.168.1.1, select "sysupgrade" image
   and click the upgrade button.

Signed-off-by: Peng Zhang <sd20@qxwlan.com>

### CODE REVIEW

**Comment by mkresin** [comment]
> Add more commits by pushing to the lede-17.01 branch on zhangsd20/openwrt.

Please rebase your changes  on top of the master branch.

> Qxwlan E1700AC v2 is based on Qualcomm QCA9563 + QCA9880 + QCA8334
> Qxwlan E558 v2 is based on Qualcomm QCA9558 + AR8327
> Qxwlan E750A v4 is based on Qualcomm QCA9344
> Qxwlan E750G v8 is based on Qualcomm QCA9344
> WHQX E600G is based on Qualcomm/Atheros QCA9531
> WHQX E600GAC is based on Qualcomm/Atheros QCA9531 + QCA9887

One commit per board please

It might make more sense to port these board right to the new ath79 target.

**Comment by zhangsd20** [comment]
what do you means?what should i do ?

**Comment by zhangsd20** [comment]
Every board I need to submit separately， you means ?

**Comment by Neustradamus** [comment]
Not merged in 17.01 but good one merged in master:
- https://github.com/openwrt/openwrt/pull/1191

E558 v2
- https://github.com/openwrt/openwrt/commit/b74f63f81d6121b5eace3f0c0c87399f7e0fde92

E750A v4
- https://github.com/openwrt/openwrt/commit/ac03d51a3f4daa2f6a2a83f041dcd71674a9f724

E750G v8
- https://github.com/openwrt/openwrt/commit/53a45020135b504cb4bee0fa8d98c8eaf6391066

Linked to:
- https://github.com/openwrt/openwrt/pull/1190
- https://github.com/openwrt/openwrt/pull/1183
- https://github.com/openwrt/openwrt/pull/1124
- https://github.com/openwrt/openwrt/pull/1123
- https://github.com/openwrt/openwrt/pull/1105

**Pull request closed without merging**
