### PR TITLE
hostapd: add 802.11 elems in probe req

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Add 802.11 elems in the hostapd_ubus_request.
Signed-off-by: Nick Hainke vincent@systemli.org

### CODE REVIEW

**Comment by blogic** [comment]
@PolynomialDivision why do we need this ? do you possibly have a different patch making use of this new element ?

**Comment by PolynomialDivision** [comment]
@blogic 
I would like to see that patch merged in the 600-ubus patch or as new 601-ubus patch. For me it is just easier to patch the ubus stuff without the need to patch a patch. ^^ If the ubus stuff is changing I have to update my patch again... I find this information useful and maybe other developers will continue.
The ieee802_11_elems struct contains information like the capabilities and ht and vht stuff..
For example #726 ...

What are the reasons to not include the ieee802_11_elems?

**Comment by blogic** [comment]
ah ok, #726 uses this and has it included. next time please close the preparation patch when posting the patch inside a 2nd PR.

duplicate, part of #726

**Comment by blogic** [comment]
this is what happens when duplicates are posted. #648 should be closed and #726 stays open

**Pull request closed without merging**
