### PR TITLE
tools/7z: update to 24.05

### PR DESCRIPTION
**Pull request by mcprat**
ping @PolynomialDivision @robimarko @Ansuel 

build failed on my armhf machine due to a "fix" for Alpine OS
upstream has both cases handled

 - add a variable to the build system
 - implement it during cleanup of the 7z Makefile
 - update 7z to 24.05 in order to drop problematic parts of a patch

### CODE REVIEW

**Comment by neheb** [comment]
from tools/Makefile, this seems to be used only for REALTEK. Anything preventing using xz instead?

**Comment by mpratt14** [comment]
from 5fcc6f0f19422c952db8bc4d72f324ead21232c6

"7z is one of the two compression formats supported in H3C firmware
images (the alternative would be ARJ)."

it's not a problem at all to build this, it's very quick to build, it's just that the Makefile and patches were not written well...

**Comment by neheb** [comment]
xz's --long-help says

```
  -F, --format=FMT    file format to encode or decode; possible values are
                      `auto' (default), `xz', `lzma', `lzip', and `raw'
```

So I guess it can't be used.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
