### PR TITLE
Ipq60xxipq60xx: add initial support for GL.iNet GL-AX1800 GL-AXT1800

### PR DESCRIPTION
**Pull request by IslamAlam**
This adds initial support for the GL.iNet GL-AX1800 GL-AXT1800, an IPQ6010 based.

# GL.iNet GL-AX1800 
<h2 class="font-weight-bold text-left" style="box-sizing: border-box; outline: none; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 700 !important; line-height: 1.2; font-size: 2rem; text-align: left; color: rgb(50, 52, 54); font-family: -apple-system, &quot;system-ui&quot;, &quot;segoe ui&quot;, Roboto, &quot;helvetica neue&quot;, Arial, &quot;noto sans&quot;, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;, &quot;noto color emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Specification</h2>

Interface | 1 x WAN Ethernet port4 x LAN Ethernet ports1 x USB 3.0 (Type-A)1 x LED1 x Sync Button1 x Reset Button1 x 12V/1.5A DC Input
-- | --
CPU | IPQ6000 Quad-core Arm Processor @1.2GHz
NPU (Networking Processing Unit) | 1.5GHz
Memory / Storage | DDR3L 512MB / NAND Flash 128MB
Antennas | 4 x External Antennas
Protocol | IEEE 802.11 a/b/g/n/ac/ax
Wi-Fi Speed | 600Mbps (2.4GHz), 1200Mbps(5GHz)
Ethernet Speed | 10/100/1000Mbps
LED | Power and Internet

# GL.iNet GL-AXT1800
<h2 class="font-weight-bold text-left" style="box-sizing: border-box; outline: none; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 700 !important; line-height: 1.2; font-size: 2rem; text-align: left; color: rgb(50, 52, 54); font-family: -apple-system, &quot;system-ui&quot;, &quot;segoe ui&quot;, Roboto, &quot;helvetica neue&quot;, Arial, &quot;noto sans&quot;, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;, &quot;noto color emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Specification</h2>

Interface | 1 x WAN Ethernet port2 x LAN Ethernet ports1 x USB 3.0 port1 x Type-C power port1 x MicroSD card slot (Max.512GB)1 x Reset button1 x Toggle button
-- | --
CPU | IPQ6000 1.2GHz Quad-core Processor
Memory / Storage | DDR3L 512MB / NAND Flash 128MB
Protocol | IEEE 802.11a/b/g/n/ac/ax
Wi-Fi Speed | 600Mbps (2.4GHz), 1200Mbps (5GHz)
Ethernet Speed | 10/100/1000Mbps

### CODE REVIEW

**Comment by IslamAlam** [comment]
Just pushed it to openwrt upstream @1715173329

**Comment by robimarko** [comment]
Does this even apply against master?

I have to be honest, and say that there is still number of open questions in regards to IPQ60xx that are waiting upstream feedback or are broken, that is the reason why I haven't made a PR for it yet.

**Comment by JiaY-shi** [comment]
It is recommended to close this pr, it is not fully ready yet, as @robimarko said, there are still many problems that need to be solved, and it is still in the testing stage.

**Comment by IslamAlam** [comment]
> Does this even apply against master?
> 
> I have to be honest, and say that there is still number of open questions in regards to IPQ60xx that are waiting upstream feedback or are broken, that is the reason why I haven't made a PR for it yet.

What do you purpose for us to proceed with the integration of the IPQ60xx upstream?

**Comment by robimarko** [comment]
> > Does this even apply against master?
> > I have to be honest, and say that there is still number of open questions in regards to IPQ60xx that are waiting upstream feedback or are broken, that is the reason why I haven't made a PR for it yet.
> 
> What do you purpose for us to proceed with the integration of the IPQ60xx upstream?

It's quite simple, start contributing code to the upstream kernel, fixing USB2.0, etc.

**Comment by Ansuel** [comment]
@IslamAlamthanks a lot for the PR and I hope i don't make someone sad. We are handling this ""internally"" with making this in a workable state upstream first. This is to prevent having to send and touch 100 commit as soon as upstream ask us to make a change. I would like to wait a bit for a formal pr and support to be proposed by us and then expand with new device support. Hope these reason are understandable.

(just for reference we are close and we are actually preparing qualcommax for the introduction of this subtarget... just a few patch are still missing... it's merge window upstream so things are currently stopped now for 1 more week)

**Comment by IslamAlam** [comment]
@Ansuel @robimarko I will then close this PR, thanks for informing us. Do you have a timeline when the PR for qualcommax will be ready?

**Comment by soshial** [comment]
I've got an impression that @solidus1983 has already fully implemented the support of these 2 routers [in his repo](https://github.com/solidus1983/openwrt/tree/ipq60xx-devel) and solved the issues with USB as well.

Is this a parallel attempt to support this router, @IslamAlam?

**Comment by Vladdrako** [comment]
> solved the issues with USB as well

What do you mean? How's? If I'm not mistaken USB is buggy in ipq60xx for now.

**Comment by solidus1983** [comment]
@soshial My repo is just the same as JiaY-shi's repo as i have forked from it.

I think Ansuel means the Linux Kernel repo which is normally called upstream.

As for USB yes it detects some USB items and can show in LUCI but i haven't fully tested past that.

**Pull request closed without merging**
