### PR TITLE
octeon: split up remaining DEVICE_TITLE

### PR DESCRIPTION
**Pull request by mwarning**
DEVICE_TITLE is split up into DEVICE_VENDOR and DEVICE_MODEL

### CODE REVIEW

**Comment by mwarning** [comment]
@adrianschmutzler we had this target already. But this one was left/forgotten?

**Comment by adrianschmutzler** [comment]
@aparcar 

I think we agreed on staying with DEVICE_TITLE for devices just named "Generic", but I'm not sure anymore. Do you remember?

**Comment by mwarning** [comment]
I do not remember. This just looks for consistent.

**Comment by mwarning** [comment]
ok, closing this then.

**Comment by aparcar** [comment]
Hi, sorry for the late response. I'd be in favor to find a naming that is unique for the target and still uses the new MODEL/VENDOR variables, like I proposed [here](https://github.com/openwrt/openwrt/pull/2291). Maybe `DEVICE_VENDOR=Generic` and `DEVICE_MODEL=Octeon Architecture` would make sense?

**Comment by mwarning** [comment]
@adrianschmutzler what do you think?

**Comment by adrianschmutzler** [comment]
I can live with both, aparcar's suggestion and just keeping Generic as DEVICE_TITLE.
However, I am not really satisfied with both solutions, too.
I might have to think about it a little longer ...

**Comment by mwarning** [comment]
ok, reopen ticket until we have made a decision

**Comment by mwarning** [comment]
My personal opinion is that we should try to remove DEVICE_TITLE from ./target. Otherwise we have a special variable other people will scratch their heads about.

**Comment by adrianschmutzler** [comment]
Well, we most probably won't remove the variable, but we might remove all cases where it is set manually.

My current tendency goes towards @aparcar's suggestion:
DEVICE_VENDOR:=Generic
DEVICE_MODEL:=Octeon

This would create a device name "Generic Octeon" which is relatively logical.

Despite, it matches our earlier agreement for brcm63xx:
  DEVICE_VENDOR := Generic
  DEVICE_MODEL := 96328avng

**Comment by adrianschmutzler** [comment]
Addition:
For those devices just called "Generic", I would prefer having one commit renaming all of them together (across targets). This will show that we have a concise approach, will make reviewing easier and might help to stay consistent.

**Comment by mwarning** [comment]
@adrianschmutzler If we want to handle Generic vendors in one commit. Then I need to remove that change from this and other PRs..

**Comment by adrianschmutzler** [comment]
@mwarning I only talk about plain "Generic".
I would _not_ move the "Generic 96328avng" or similar cases.

For this subset, I do not think there is much to remove from other PRs. Despite, if you forget to remove one of those, it will just be a rebase then ...

**Comment by adrianschmutzler** [comment]
@mwarning Just grepped for that:
```
adsc@buildfff:/data/openwrt$ grep -rni "DEVICE_.*generic" target/
target/linux/ath25/image/Makefile:64:  DEVICE_TITLE := Generic Images
target/linux/ar71xx/patches-4.14/920-usb-chipidea-AR933x-platform-support.patch:66:+    platform_device_register_simple("usb_phy_generic",
target/linux/octeon/image/Makefile:27:  DEVICE_TITLE := Generic
target/linux/brcm63xx/image/bcm63xx.mk:60:  DEVICE_TITLE := Generic 963281TAN
target/linux/brcm63xx/image/bcm63xx.mk:70:  DEVICE_TITLE := Generic 96328avng
target/linux/brcm63xx/image/bcm63xx.mk:79:  DEVICE_TITLE := Generic 96338GW
target/linux/brcm63xx/image/bcm63xx.mk:88:  DEVICE_TITLE := Generic 96338W
target/linux/brcm63xx/image/bcm63xx.mk:98:  DEVICE_TITLE := Generic 96345GW2
target/linux/brcm63xx/image/bcm63xx.mk:109:  DEVICE_TITLE := Generic 96348GW
target/linux/brcm63xx/image/bcm63xx.mk:118:  DEVICE_TITLE := Generic 96348GW-10
target/linux/brcm63xx/image/bcm63xx.mk:127:  DEVICE_TITLE := Generic 96348GW-11
target/linux/brcm63xx/image/bcm63xx.mk:136:  DEVICE_TITLE := Generic 96348R
target/linux/brcm63xx/image/bcm63xx.mk:145:  DEVICE_TITLE := Generic 96358VW
target/linux/brcm63xx/image/bcm63xx.mk:154:  DEVICE_TITLE := Generic 96358VW2
target/linux/brcm63xx/image/bcm63xx.mk:163:  DEVICE_TITLE := Generic 96368MVNgr
target/linux/brcm63xx/image/bcm63xx.mk:172:  DEVICE_TITLE := Generic 96368MVWG
```

Looks like ath25 and octeon are the only two targets to have plain "Generic" devices. I expected more than that. In this case, I'm fine with keeping the PRs as they are now ...

**Review by adschm — APPROVED** [review]

**Review by aparcar — APPROVED** [review]

**Comment by mwarning** [comment]
@blogic please review - thanks!

**Comment by hauke** [comment]
Thank you for your patch, it was applied to master.

**Pull request closed without merging**
