### PR TITLE
mediatek: filogic: wax220: cleanup device tree

### PR DESCRIPTION
**Pull request by agners**
Fix compatible string to match what is supported upstream, fix alignment and order MTD partitions according to offset.

### CODE REVIEW

**Comment by musashino205** [comment]
Please use the target name instead of the subtarget name for prefix of the commit title. (```mediatek: ```)

**Comment by agners** [comment]
Meanwhile I've tested this on actual hardware: Things looking good here :+1:

**Comment by blocktrron** [comment]
Merged to my staging tree - thanks!

**Pull request closed without merging**
