### PR TITLE
toolchain/gcc: Add GCC 10.1.0

### PR DESCRIPTION
**Pull request by wongsyrone**
**IMPORTANT**: I send this pull request because I can't see my patch listed on patchwork. This pull request is the same as the one sent to the mailing list.

Compared to GCC 9:

881-no_tm_section.patch modified based on upstream change

See https://gcc.gnu.org/gcc-10/porting_to.html for more info

Compiled and run tested on x86_64

Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

### CODE REVIEW

**Comment by wongsyrone** [comment]
Cc @neheb @hauke @nbd168 @xback @yousong

**Comment by neheb** [comment]
A bunch of packages should break with this :). I'll test when I can.

**Comment by yousong** [comment]
For the patches dir part, please consider doing this in at least two separate commits, first a verbatim copy of the ones from 9.3.0, then changes in this addition, for ease of tracking and review.

**Comment by wongsyrone** [comment]
Commits I made to fix GCC 10 compilation:

main repo:

https://github.com/wongsyrone/lede-1/commit/ebfa84b45cb5bcaacdaac56c653a191f759bfbe4

Luci:

https://github.com/wongsyrone/luci-1/commit/0cdbe35d69c7cffa99a6bc870f21ad7c95e2e7ba

packages feed:

https://github.com/wongsyrone/packages-1/commit/56d9bc75b4b7f4006c28417d066f46900016eb9a
https://github.com/wongsyrone/packages-1/commit/17ac8ab0bb7b77d87f9090d29860756477647764
https://github.com/wongsyrone/packages-1/commit/7ca6c73ae575e27081a128718b92596531030f90
https://github.com/wongsyrone/packages-1/commit/3a1683eb140d06379924a10d0cc0a9b1a855acab

**Comment by neheb** [comment]
Locally libupnp is failing as well. GCC8 > 9 had less breakage.

**Comment by wongsyrone** [comment]
Sorry, I cannot fix the packages I didn't use. You can apply the porting guide GCC guys provided.

I quote it here:
```
As a workaround, legacy C code where all tentative definitions should be placed into a common block can be compiled with -fcommon.
```

I think we should blame the package maintainer instead of a new compiler version enforcing C standard.

**Comment by neheb** [comment]
Another casualty: https://github.com/openwrt/luci/pull/4196

Those extern commits look weird to me. Should probably use static.

**Comment by wongsyrone** [comment]
extern means the real definition locates in the corresponding source file instead of the header file.

**Comment by wongsyrone** [comment]
I found [my patch](https://patchwork.ozlabs.org/project/openwrt/patch/20200621090251.1093279-1-wong.syrone@gmail.com/) listed on patchwork.

**Comment by neheb** [comment]
Running this on an Archer C7v2. Works fine. malta works fine as well.

**Comment by wongsyrone** [comment]
Any update on this PR?

**Comment by ynezz** [comment]
> For the patches dir part, please consider doing this in at least two separate commits, first a verbatim copy of the ones from 9.3.0, then changes in this addition, for ease of tracking and review.

I second that [request](https://github.com/openwrt/openwrt/pull/3126#issuecomment-647222939) which you've probably missed. It's hard to review (needs additional time) otherwise.

**Comment by wongsyrone** [comment]
@ynezz @yousong Already split into three commits.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by wongsyrone** [comment]
@ynezz Sorry. I cannot find my commits in your staging tree.

**Pull request closed without merging**
