### PR TITLE
scripts/feeds: silence git warning by selecting pull style

### PR DESCRIPTION
**Pull request by hnyman**
Silence the warning in git 2.27 about undefined fast-forward style in git pull. 
Define "ff-only" as the style in the script.

---
Since git 2.27 git gives a warning at each `git pull` in case you have not defined a default pull rebase/ff style:

```
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.

...
```
That warning is triggered with each feed at each `scripts/feeds` run.

The reason why I titled this PR as RFC at this point, is that although "ff-only" suits me, as I mainly keep my own source code changes uncommitted in my local repo. But I wonder if "git pull --rebase" (without merge) might be a better option for those who use commits to store their changes.

### CODE REVIEW

**Comment by ynezz** [comment]
AFAIU `ff-only` should keep current behavior so it should be ok

**Comment by hnyman** [comment]
@ynezz @dedeckeh 
No objections so far.
Please merge, if you think that this is ok.

**Comment by neheb** [comment]
Locally I've fixed this by configuring it with git confg --global, but this is better.

**Comment by aparcar** [comment]
Merged, thanks!

**Pull request closed without merging**
