### PR TITLE
wireguard-tools: update to v1.0.20210914

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Update to latest version.

### CODE REVIEW

**Comment by graysky2** [comment]
https://github.com/openwrt/openwrt/pull/4558

**Comment by PolynomialDivision** [comment]
Feels weird not updating and shipping an outdated release.

**Comment by graysky2** [comment]
I thought so too :grin:

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in e74b79ed56b09bb94f3e8890a1f9d61b77a8176c.

**Pull request closed without merging**
