### PR TITLE
apm821xx: add NVMEM-on-UBI support + config cleanups.

### PR DESCRIPTION
**Pull request by neheb**
ping @robimarko @hauke @chunkeey 

The last commit especially is needed to fix https://github.com/openwrt/openwrt/commit/8d302f5ebc6e2787d01d6c6a8ef6bcc403949705

### CODE REVIEW

**Comment by neheb** [comment]
Some of these crypto additions are due to CONFIG_UBIFS_FS_ZSTD in target/generic.

I'm guessing that's a different PR.

**Comment by RussellSenior** [comment]
@neheb I tried the four patches on top of 3a168e359587 and I'm still getting the u-boot-env MAC address and not the board-config ubi volume MAC address. I confirmed that the kernel .config included CONFIG_MTD_UBI_NVMEM=y.

**Comment by neheb** [comment]
oh that's an embarrassing typo.

**Comment by neheb** [comment]
@RussellSenior try again.

**Comment by RussellSenior** [comment]
@neheb i just added your "fix volume/volname" patch to the previous 4, and problem with MAC addr persists.

**Comment by RussellSenior** [comment]
Fwiw: I dropped some printk's into drivers/mtd/ubi/vmt.c in the find_volume_fwnode() function and I'm seeming them match board-config in dmesg:

```
[    1.273654] nand: device found, Manufacturer ID: 0xad, Chip ID: 0x75
[    1.280028] nand: Hynix NAND 32MiB 3,3V 8-bit
[    1.284369] nand: 32 MiB, SLC, erase size: 16 KiB, page size: 512, OOB size: 16
[    1.291681] Scanning device for bad blocks
[    1.403690] 5 fixed-partitions partitions found on MTD device 4e4000000.ndfc.nand
[    1.411617] Creating 5 MTD partitions on "4e4000000.ndfc.nand":
[    1.417543] 0x000000000000-0x000000150000 : "u-boot"
[    1.424704] 0x000000150000-0x000000160000 : "u-boot-env"
[    1.431036] 0x000000160000-0x000000170000 : "u-boot-env-redundant"
[    1.438516] 0x000000170000-0x000000180000 : "oops"
[    1.444591] 0x000000180000-0x000002000000 : "ubi"
[    1.454129] ubi0: attaching mtd4
[    1.626781] ubi0: scanning is finished
[    1.638474] VOLNAME: board-config
[    1.641804] VOLID: 0
[    1.645983] ubi0: attached mtd4 (name "ubi", size 30 MiB)
[    1.651435] ubi0: PEB size: 16384 bytes (16 KiB), LEB size: 15872 bytes
[    1.658028] ubi0: min./max. I/O unit sizes: 512/512, sub-page size 256
[    1.664530] ubi0: VID header offset: 256 (aligned 256), data offset: 512
[    1.671214] ubi0: good PEBs: 1952, bad PEBs: 0, corrupted PEBs: 0
[    1.677287] ubi0: user volume: 5, internal volumes: 1, max. volumes count: 92
[    1.684393] ubi0: max/mean erase counter: 1032/726, WL threshold: 4096, image sequence number: 1992864020
[    1.693927] ubi0: available PEBs: 0, total reserved PEBs: 1952, PEBs reserved for bad PEB handling: 40
[    1.703238] ubi0: background thread "ubi_bgt0d" started, PID 127
[    1.710164] block ubiblock0_3: created from ubi0:3(rootfs)
[    1.715647] ubiblock: device ubiblock0_3 (rootfs) set to be root filesystem
```

**Comment by neheb** [comment]
at this point I'm wondering if UBI-on-NVMEM supports big endian. ping @dangowrt

FWIW, I tested MAC address with u-boot,env and that worked fine.

**Comment by dangowrt** [comment]
Afaik endianess doesn't matter in UBI world, just like with any other NVMEM provider we just receive things in on-disk byte order.
As a first step you should investigate if `/sys/class/ubi/ubi0_0/of_node` exists, because that would hint to the DT node being matched correctly. Next step would be checking if all the necessary NVMEM kernel options are enabled, and if you can see the ubi volume with cells on it in  `/sys/bus/nvmem/devices`.
If both is the case, the NVMEM part is working correctly.
Now, in order to avoid Linux from receiving the U-Boot assigned `ethaddr` all you need to do is remove the `ethernet0` alias in DT.

**Comment by neheb** [comment]
@RussellSenior try again. Because locally I wiped my UBI partition, this resulted in the ethernet interface not coming up.

Also because the driver errors on not being able to find a mac address instead of generating a random one.

**Comment by RussellSenior** [comment]
> Afaik endianess doesn't matter in UBI world, just like with any other NVMEM provider we just receive things in on-disk byte order. As a first step you should investigate if `/sys/class/ubi/ubi0_0/of_node` exists, because that would hint to the DT node being matched correctly. Next step would be checking if all the necessary NVMEM kernel options are enabled, and if you can see the ubi volume with cells on it in `/sys/bus/nvmem/devices`. If both is the case, the NVMEM part is working correctly. Now, in order to avoid Linux from receiving the U-Boot assigned `ethaddr` all you need to do is remove the `ethernet0` alias in DT.

```
root@cat:/sys/class/ubi/ubi0_0/of_node# ls -al
drwxr-xr-x    3 root     root             0 Oct  5 22:06 .
drwxr-xr-x    3 root     root             0 Oct  5 22:06 ..
-r--r--r--    1 root     root            24 Oct  5 22:06 name
drwxr-xr-x    3 root     root             0 Oct  5 22:06 nvmem-layout
-r--r--r--    1 root     root            13 Oct  5 22:06 volname
root@cat:/sys/class/ubi/ubi0_0/of_node# echo $(cat volname)
board-config
```

```
root@cat:~# hexdump -C /sys/bus/nvmem/devices/ubi0_0/cells/macaddr@66 
00000000  00 18 0a xx yy zz                                 |......|
00000006
```

Which all looks seemingly correct, but, still, the macaddr assigned to the interface is the one found in u-boot-env, not 00:18:0a:xx:yy:zz.

**Comment by RussellSenior** [comment]
> Which all looks seemingly correct, but, still, the macaddr assigned to the interface is the one found in u-boot-env, not 00:18:0a:xx:yy:zz.
> 
> I haven't tried the last patch yet...

With the last patch ("/delete-property/ ethernet0;"), I get the correct MAC address! yay!

**Comment by chunkeey** [comment]
I'm waiting for https://github.com/openwrt/openwrt/pull/14729 to hit first.

As for preliminary findings:

  - CONFIG_CC_IMPLICIT_FALLTHROUGH, CONFIG_CC_NO_ARRAY_BOUNDS, CONFIG_GCC10_NO_ARRAY_BOUNDS  
    these are compiler related options, can't we filter those?
 
  - CONFIG_DEBUG_INFO, CONFIG_SERIAL_8250_FSL any particular reason these are selected? We don't need them, right?

 - can you please document (i.e comment in the dts or at least a note in the git commit) that the MR24+MX60 uboot supplies a dogdy ethernet mac. And that this breaks the normal way of the drivers to get the ethernet-mac since the assumption is that what u-boot provides in the DTB is correct.

**Comment by neheb** [comment]
> I'm waiting for #14729 to hit first.
> 
> As for preliminary findings:
> 
> * CONFIG_CC_IMPLICIT_FALLTHROUGH, CONFIG_CC_NO_ARRAY_BOUNDS, CONFIG_GCC10_NO_ARRAY_BOUNDS
>   these are compiler related options, can't we filter those?
> * CONFIG_DEBUG_INFO, CONFIG_SERIAL_8250_FSL any particular reason these are selected? We don't need them, right?
> * can you please document (i.e comment in the dts or at least a note in the git commit) that the MR24+MX60 uboot supplies a dogdy ethernet mac. And that this breaks the normal way of the drivers to get the ethernet-mac since the assumption is that what u-boot provides in the DTB is correct.

What does that PR have to do with this one?

Those compiler options are present in most other targets.

These are probably selected anyway.

Will do.

**Comment by neheb** [comment]
@RussellSenior does dmesg show probe errors with u-boot,env?

**Comment by RussellSenior** [comment]
> @RussellSenior does dmesg show probe errors with u-boot,env?

Like this?

```
[    2.096376] u_boot_env 4e4000000.ndfc:nand:partitions:partition@150000: Invalid calculated CRC32: 0xb085ae88 (expected: 0xe08c81ed)
[    2.108201] u_boot_env: probe of 4e4000000.ndfc:nand:partitions:partition@150000 failed with error -22
```

**Comment by neheb** [comment]
Yep. That gets fixed with https://github.com/openwrt/openwrt/pull/16618

**Comment by chunkeey** [comment]
> > I'm waiting for #14729 to hit first.
> > As for preliminary findings:
> > 
> > * CONFIG_CC_IMPLICIT_FALLTHROUGH, CONFIG_CC_NO_ARRAY_BOUNDS, CONFIG_GCC10_NO_ARRAY_BOUNDS
> >   these are compiler related options, can't we filter those?
> > * CONFIG_DEBUG_INFO, CONFIG_SERIAL_8250_FSL any particular reason these are selected? We don't need them, right?
> > * can you please document (i.e comment in the dts or at least a note in the git commit) that the MR24+MX60 uboot supplies a dogdy ethernet mac. And that this breaks the normal way of the drivers to get the ethernet-mac since the assumption is that what u-boot provides in the DTB is correct.
> 
> What does that PR have to do with this one?

Easy, the "NVMEM-on-UBI" in the commit subject reminded me of this. From what I know @dangowrt  wrote the kernel's ubi/nvmem.c . So, he has probably a good overview how good the support is... And apparently, the series is on hold?! 

> Those compiler options are present in most other targets.
> 
> These are probably selected anyway.

Question here then: is there anything particular wrong with apm821xx config then?
I was told that one should avoid making Changes for Change's Sake. Is this still true?

> 
> Will do.
> 
> edit: I looked into these new config options. Even without them in the config file, they're present in the actual .config for the kernel.

+1 for testing. Though that SERIAL_8250_FSL is kinda odd.

**Comment by neheb** [comment]
> > > I'm waiting for #14729 to hit first.
> > > As for preliminary findings:
> > > 
> > > * CONFIG_CC_IMPLICIT_FALLTHROUGH, CONFIG_CC_NO_ARRAY_BOUNDS, CONFIG_GCC10_NO_ARRAY_BOUNDS
> > >   these are compiler related options, can't we filter those?
> > > * CONFIG_DEBUG_INFO, CONFIG_SERIAL_8250_FSL any particular reason these are selected? We don't need them, right?
> > > * can you please document (i.e comment in the dts or at least a note in the git commit) that the MR24+MX60 uboot supplies a dogdy ethernet mac. And that this breaks the normal way of the drivers to get the ethernet-mac since the assumption is that what u-boot provides in the DTB is correct.
> > 
> > 
> > What does that PR have to do with this one?
> 
> Easy, the "NVMEM-on-UBI" in the commit subject reminded me of this. From what I know @dangowrt wrote the kernel's ubi/nvmem.c . So, he has probably a good overview how good the support is... And apparently, the series is on hold?!

```
target/linux/ipq40xx/generic/config-default:CONFIG_MTD_UBI_NVMEM=y
target/linux/ipq40xx/mikrotik/config-default:CONFIG_MTD_UBI_NVMEM=y
target/linux/mediatek/filogic/config-6.6:CONFIG_MTD_UBI_NVMEM=y
target/linux/mediatek/mt7622/config-6.6:CONFIG_MTD_UBI_NVMEM=y
target/linux/ramips/mt7621/config-6.6:CONFIG_MTD_UBI_NVMEM=y
```

This is already in use. That PR is for an unrelated device.

> 
> > Those compiler options are present in most other targets.
> > These are probably selected anyway.
> 
> Question here then: is there anything particular wrong with apm821xx config then? I was told that one should avoid making Changes for Change's Sake. Is this still true?

This came from me trying and failing to see why NVMEM on UBI wasn't working or where the other CONFIG_MTD_UBI symbols even where. Once I figured it out, it turns out nand/config-default was extremely old and contained symbols no longer present (CONFIG_IKAREM=y ???)

> 
> > Will do.
> > edit: I looked into these new config options. Even without them in the config file, they're present in the actual .config for the kernel.
> 
> +1 for testing. Though that SERIAL_8250_FSL is kinda odd.
I agree. I don't know what enables it.

**Comment by RussellSenior** [comment]
> edit: I should point out MAC addresses on MX60 and MR24 are currently wrong as the bootloader address is applied (same default address everywhere).

In master, since 8d302f5ebc6e2787d01d6c6a8ef6bcc403949705, the MAC address is wrong.

**Comment by RussellSenior** [comment]
> > +1 for testing. Though that SERIAL_8250_FSL is kinda odd.
> 
> I agree. I don't know what enables it.

From the kernel's drivers/tty/serial/8250/Kconfig:

```
config SERIAL_8250_FSL
        tristate "Freescale 16550 UART support" if COMPILE_TEST && !(PPC || ARM || ARM64)
        depends on SERIAL_8250
        default SERIAL_8250 if PPC || ARM || ARM64
        help
          Selecting this option enables a workaround for a break-detection
          erratum for Freescale 16550 UARTs in the 8250 driver. It also
          enables support for ACPI enumeration.
```

**Comment by neheb** [comment]
Sure but it’ll come back on a refresh. Anyway it’s a moot point. It makes sense to have everything refreshed. We’ve been doing this for patches for quite a while now.

**Comment by neheb** [comment]
I don't see a problem with the kernel config changes (they aren't really).

They're a prelude for the last commit which is needed to fix the UBI issue.

**Review by dangowrt — APPROVED** [review]

**Comment by RussellSenior** [comment]
I rebased this pull request on current master (caf5caae44f54855b6630d90e99a3e861cf77995), and on my MR24, I am no longer passing traffic on the eth0 interface.

**Comment by neheb** [comment]
so without this PR it works?

**Comment by RussellSenior** [comment]
> so without this PR it works?

Okay, this is bizarre, and I think I've seen it before. I flashed a bunch of recent versions I have tested and none of them had working eth0. I tried replacing the ethernet cable, no difference. I tried powering it off for a few minutes and the powering on again, no difference. Then I booted into a recovery partition, with a version 5.x something kernel, and it worked, proving (i think) that the hardware was okay. Then I booted into this pull request rebased (as described above) and (WHUT?) eth0 is working (gets DHCP and passes traffic). I also booted into master branch with the single revert of 8d302f5ebc6e2787d01d6c6a8ef6bcc403949705, and that works too (i.e. eth0 gets DHCP and passes traffic). It feels like something isn't getting initiallized or something so it depends on some lingering register or something whether it works or not. Or, <insert theory here>.

**Comment by hauke** [comment]
I haven't read everything.

This commit 5815884c3a2a6d56d4fb0d1019276caea4bba9ba removed `CONFIG_AT803X_PHY` from the kernel configuration. This is the driver for the AR8035. 
@RussellSenior  Could you please activate `CONFIG_AT803X_PHY` in `target/linux/apm821xx/nand/config-default` again.

**Comment by chunkeey** [comment]
@hauke, please also check out https://github.com/openwrt/openwrt/pull/16618
for some reason @neheb thinks I'm wrong about u-boot,env-redundant-count (for the WNDR4700). He also thinks that he's right with u-boot,env-redundant-bool on the MX60, and so far he won't check to see if this is true or not.

It's like https://github.com/openwrt/openwrt/pull/4679 all over again. So please tell me, what's the issue here?!

**Comment by robimarko** [comment]
I am not sure what #4679 has to do with this?

**Comment by neheb** [comment]
This PR does not handle uboot

**Comment by neheb** [comment]
> I haven't read everything.
> 
> This commit [5815884](https://github.com/openwrt/openwrt/commit/5815884c3a2a6d56d4fb0d1019276caea4bba9ba) removed `CONFIG_AT803X_PHY` from the kernel configuration. This is the driver for the AR8035. @RussellSenior Could you please activate `CONFIG_AT803X_PHY` in `target/linux/apm821xx/nand/config-default` again.

interestingly, the ethernet driver has a phy.c with this little section:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/net/ethernet/ibm/emac/phy.c?h=v6.6.57#n492

I have no idea why.

**Comment by RussellSenior** [comment]
> I haven't read everything.
> 
> This commit [5815884](https://github.com/openwrt/openwrt/commit/5815884c3a2a6d56d4fb0d1019276caea4bba9ba) removed `CONFIG_AT803X_PHY` from the kernel configuration. This is the driver for the AR8035. @RussellSenior Could you please activate `CONFIG_AT803X_PHY` in `target/linux/apm821xx/nand/config-default` again.

@hauke I used make kernel_menuconfig to add it, and that fixed my cold-boot-no-ethernet-traffic problem. THANK YOU!

**Comment by neheb** [comment]
Rebased.

**Comment by RussellSenior** [comment]
> Rebased.

Seems ripe for some squashing too.

**Comment by neheb** [comment]
Hmm? Seems fine to me.

Anyway, I'll need to rebase again after https://github.com/openwrt/openwrt/pull/16743 gets merged.

**Comment by neheb** [comment]
No idea what you mean. I squashing commits 2 and 3 makes sense but the others seem standalone.

**Comment by robimarko** [comment]
I mean, to me the kernel config changes are weird (First 3 commits), but I get what they are achieving

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
