### PR TITLE
tools/libressl: update to 3.2.1

### PR DESCRIPTION
**Pull request by wevsty**
libressl update to 3.2.1
Delete 001-dont-build-tests-man.patch
Add configure args :
--enable-static
--disable-tests

The patch (001-dont-build-tests-man.patch) no longer works with the current version.
Follow the patch notes:
Adding the --enable-static and --disable-tests parameters should replace the patch.

Test passed on ubuntu.
But I don't have a MacOS to test.
Maybe need someone using MacOS to test.

Signed-off-by: Yuan Tao <ty@wevs.org>

### CODE REVIEW

**Comment by wevsty** [comment]
By the way, I prefer to use cmake to compile libressl.

The openwrt/tools/Makefile requires that cmake compiles with libressl.
But my test results show, compiling cmake does not depend on libressl.

**Comment by hauke** [comment]
cmake uses some openssl functions and links against it.
If we would build it against the system openssl, it would use the openssl 1.0 or 1.1 API depending on the build host. This could cause problems in the SDK builder.

**Comment by wevsty** [comment]
> 
> 
> cmake uses some openssl functions and links against it.
> If we would build it against the system openssl, it would use the openssl 1.0 or 1.1 API depending on the build host. This could cause problems in the SDK builder.

OK, Got it.

**Comment by hauke** [comment]
Thank you for the pull request, it was applied to master.

**Pull request closed without merging**
