### PR TITLE
ag71xx: fix wrong register definition issue

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by Ansuel** [comment]
mh?

**Comment by neheb** [comment]
This is just a documentation change, getting rid of unknowns. Nothing more.

**Comment by Ansuel** [comment]
@neheb considering the quality of the commit description and sob tag... I would just add everything from scratch and add a tag like Ref: LINK_TO_THE_REAL_COMMIT

That sob tag is not that acceptable honestly...

**Comment by neheb** [comment]
Don't quite remember where I found it.

**Pull request merged**
