### PR TITLE
kernel: bump 5.15 to 5.15.33

### PR DESCRIPTION
**Pull request by rsalvaterra**
Deleted (upstreamed):
generic/backport-5.15/350-v5.18-MIPS-pgalloc-fix-memory-leak-caused-by-pgd_free.patch [1]
generic/backport-5.15/730-v5.16-hv-utils-add-PTP_1588_CLOCK-to-Kconfig-to-fix-build.patch [2]
generic/pending-5.15/850-0014-PCI-aardvark-Fix-reading-PCI_EXP_RTSTA_PME-bit-on-em.patch [3]

Manually rebased:
generic/pending-5.15/850-0002-PCI-aardvark-Fix-reading-MSI-interrupt-number.patch
ramips/patches-5.15/710-at803x.patch

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.33&id=d29cda15cab086d82d692de016f7249545d4b6b4
[2] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.33&id=d5aad7d63b1b5c1f3c4b69e12c05e7c7d196fae8
[3] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.33&id=ed750e22e44366e264bcdf7b1cf0713f08f7980a

Run-tested (.32 only):
ramips/mt7621 (Redmi AC2100)

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by rsalvaterra** [comment]
This should probably stay on hold until all the 5.15 issues are resolved, but I'll keep it updated with newer bumps as they come along.

**Comment by alexeys85** [comment]
I'm running 5.15.31 on omap with no problems too.

**Comment by ynezz** [comment]
> should we create a mega issue and link/track every 5.15 progress

Probably there should be a separate ticket for each issue having some appropriate label, like for example `kernel-v5.15` ?

**Comment by Ansuel** [comment]
The main goal is keep things organized and have a quick way to check the status of things. Mega issue requires to be updated every time. Project instead can autoupdate by just adding the correct tag. Wonder if project would be the correct way to handle this.

**Comment by rsalvaterra** [comment]
> > This should probably stay on hold until all the 5.15 issues are resolved
> 
> I'm running 5.15.31 on x86/64, sunxi a7/a53 and imx/a9 just fine.

That's because your hardware doesn't have an Aardvark PCIe controller. 😉

**Comment by ynezz** [comment]
> That's because your hardware doesn't have an Aardvark PCIe controller. wink

Sorry, but I fail to see, why this is so special and should block kernel version bumps. It's just for developers, AFAIK 5.10 is still default so we don't provide any official images with 5.15 yet.

**Comment by Ansuel** [comment]
@ynezz think his idea is to first stabilize the patch in generic and then start upgrading the version.

**Comment by rsalvaterra** [comment]
> @ynezz think his idea is to first stabilize the patch in generic and then start upgrading the version.

Yes, that was my idea. Sure, we can still rebase broken patches on top of new kernels (the result will still be a broken system, pretty much the status quo)… I don't have a strong opinion either way, though, it's fine if it's merged as-is.

**Review by ynezz — APPROVED** [review]
LGTM

**Comment by ynezz** [comment]
Just run tested this on `imx6ull-colibri-aster`.

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 5a09eb17c2ca3a8fea09509b09edb30c54e9316e and be381a7ac70d94c088145e520b8045bd6b5a7957.

**Pull request closed without merging**
