### PR TITLE
util-linux: added unshare, nsenter executable

### PR DESCRIPTION
**Pull request by utoni**

### CODE REVIEW

**Comment by hauke** [comment]
The blocks are alphabetical ordered please add the new packages to the correct position.
Please update the title to "util-linux: added unshare and nsenter executables"

**Comment by hauke** [comment]
Looks better now, can you please squash this together into one commit with a Signed-off-by: line

**Comment by lnslbrty** [comment]
done

**Comment by hauke** [comment]
Thank you for the patch it was applied to master.

**Pull request closed without merging**
