### PR TITLE
wolfssl: Do not activate HW acceleration on armvirt

### PR DESCRIPTION
**Pull request by hauke**
The armvirt target is also used to run OpenWrt in lxc on other targets
like a raspberry pi. If we set CONFIG_WOLFSSL_ASM_CAPABLE wolfssl is
only working when the CPU supports the hardware extension.

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

### CODE REVIEW

**Comment by neheb** [comment]
ping @cotequeiroz

**Comment by champtar** [comment]
@hauke are you sure you meant to ask me for review ?

**Comment by cotequeiroz** [comment]
I think this makes sense. Since it only changes the default, if there’s a need to use hw crypto, one can build locally with it enabled.

**Comment by Ansuel** [comment]
@hauke guess we have to backport this to 22.03 right?

**Comment by hauke** [comment]
@champtar sorry I wanted to add @cotequeiroz  as reviewer.
We should backport this to 22.03. Someone on the forum was complaining about this. 

Would be nice wolfssl would be able to detect this CPU crypto extension  automatically.

**Comment by hauke** [comment]
`WOLFSSL_HAS_CPU_CRYPTO` depends on this option. This with change setting WOLFSSL_HAS_CPU_CRYPTO is not possible on armvirt an more.

**Comment by cotequeiroz** [comment]
I misread it, sorry.

I don't know anything about qemu with aarch64.  If it is not usable with armvirt at all, this PR is fine as is.  There's no point in building it.

_Optional:_ If it works on some implementations, but not others, then perhaps you can just change the default, and allow people to build their own if they can run it:
``` diff
--- a/package/libs/wolfssl/Config.in
+++ b/package/libs/wolfssl/Config.in

 choice
        prompt "Hardware Acceleration"
-       default WOLFSSL_HAS_CPU_CRYPTO if WOLFSSL_ASM_CAPABLE
+       default WOLFSSL_HAS_CPU_CRYPTO if WOLFSSL_ASM_CAPABLE && !TARGET_armvirt
        default WOLFSSL_HAS_NO_HW

        config WOLFSSL_HAS_NO_HW
```

**Comment by hauke** [comment]
Thanks @cotequeiroz <our change looks better and allows to change the activate CPU crypto if needed. 

The armvirt target can be used on arbitrary aarch64 CPUs. For example inside of qemu or inside a container like lxc.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in d1b5d17d03c844ad578bb53b90ea17377bdc5eee.

**Review by cotequeiroz — COMMENTED** [review]
```
Reviewed-by: Eneas U de Queiroz <cotequeiroz@gmail.com>
```

**Pull request closed without merging**
