### PR TITLE
libnetfilter_queue: bump to git HEAD

### PR DESCRIPTION
**Pull request by Zxilly**
Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Note that there's also http://patchwork.ozlabs.org/project/openwrt/patch/20201109071714.30206-1-rosenp@gmail.com/

**Comment by Zxilly** [comment]
> Note that there's also http://patchwork.ozlabs.org/project/openwrt/patch/20201109071714.30206-1-rosenp@gmail.com/

But I noticed the Makefile at `https://github.com/openwrt/openwrt/blob/7e67d144868b716fc1d9b256e57d9f83b8acd9cd/package/libs/libnetfilter-queue/Makefile` is still outdated.That's why I make this PR.

**Comment by neheb** [comment]
Alternative to this PR: https://github.com/openwrt/packages/pull/14047

**Comment by Zxilly** [comment]
> Alternative to this PR: [openwrt/packages#14047](https://github.com/openwrt/packages/pull/14047)

Tks for your work.

**Pull request closed without merging**
