### PR TITLE
[RFC] kernel: drop kmod-ledtrig-{default-on,heartbeat,netdev,timer} packages

### PR DESCRIPTION
**Pull request by mans0n**
The goal of this PR is to remove kmod dependency of the luci collection package.

When we run `opkg install luci` on self-built snapshot image, the installation failes
due to unmet kernel version dependency:
```
root@OpenWrt:/# opkg install luci
Installing luci (git-20.074.84698-ead5e81) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_xscale/luci/luci_git-20.074.84698-ead5e81_all.ipk
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ledtrig-default-on found, but incompatible with the architectures configured
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ledtrig-heartbeat found, but incompatible with the architectures configured
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ledtrig-netdev found, but incompatible with the architectures configured
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ledtrig-timer found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 *      kernel (= 5.4.86-1-f9bcc5911da3ac3e6475f95070b6e091)
 * opkg_install_cmd: Cannot install package luci.
```
Of course, it can be easily resolved by adding luci or kmod-ledtrig-* packages at build time, but I admit it becomes a bit cumbersome sometimes.
Fortunately, the three of the four kernel modules are already built-in on most targets, and the last one, heartbeat, does not increase kernel size that much, so we can make all of them built-in and remove the kmod packages.

I also made a patch for the luci part. I'll open another PR for it, if this gets positive feedbacks.
EDIT: openwrt/luci#4719

### CODE REVIEW

**Comment by adschm** [comment]
This looks like a good idea to me. The targets that disabled triggers before are only a few (and mostly legacy), and the size requirement for heartbeat is obviously negligible.

The only remaining possible reason to disable the symbols on certain targets would be if the functionality is broken there. If we can exclude that to a fair level, I think we should merge this.

However, I'm no kernel expert, so better wait for an additional opinion before you go on with additional work :-)

**Comment by adschm** [comment]
And I'm not really sure whether the third patch should be a "kernel:" or a "treewide:". But that's really the least of our problems ...

**Comment by mans0n** [comment]
I had a run-test on oxnas with built-in netdev trigger and it worked well. And I don't think default-on or timer trigger would break on any platform.

**Review by jow- — APPROVED** [review]
ACK from the LuCI side.

**Comment by adschm** [comment]
I decided to merge this, it's well-justified and I don't see any obvious issue with it.
Thanks!

**Comment by mans0n** [comment]
Thank you for review and merge, as always. :)

**Pull request closed without merging**
