### PR TITLE
[23.05] layerscape: fix support of LS1088A-RDB in 5.15

### PR DESCRIPTION
**Pull request by CHKDSK88**
This PR contains two commits extracted from #12440, which are required for proper work LS1088A-RDB board in 23.05 stable release.

### CODE REVIEW

**Comment by cowgirlalexa** [comment]
> @cowgirlalexa Please test this branch: https://github.com/CHKDSK88/openwrt-1/tree/layerscape-23.05
> 
> Now everything should be ok.

@CHKDSK88 I can confirm it id working

**Review by cowgirlalexa — COMMENTED** [review]
Compiled and it is booting on my LS1088ARDB

**Review by cowgirlalexa — COMMENTED** [review]
Verified - working

**Review by cowgirlalexa — COMMENTED** [review]
Verified - working - recommended for final approval

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
