### PR TITLE
comgt: fix hotplug event handling

### PR DESCRIPTION
**Pull request by andres-h**
https://bugs.openwrt.org/index.php?do=details&task_id=2439

### CODE REVIEW

**Comment by obsy** [comment]
See https://github.com/openwrt/openwrt/pull/2351

**Comment by adrianschmutzler** [comment]
@andres-h Please add a description of the "what and why" to your commit.

**Comment by andres-h** [comment]
Is it correct now?

**Comment by adrianschmutzler** [comment]
Hi, please team up with @rozhuk-im from #2351 , so we can save work and don't have to discuss twice.

**Comment by adrianschmutzler** [comment]
This is very close to #2351, which was earlier. I will close this one as it's a duplicate, please proceed with discussion in #2351.

**Pull request closed without merging**
