### PR TITLE
[22.03] tools/ccache: update to 4.6.3

### PR DESCRIPTION
**Pull request by mchehab**
Full changelog: https://ccache.dev/releasenotes.html#_ccache_4_6_3

This also reverts changeset 3de4572ed308 ("tools/ccache: fix build with musl and gcc 12"), as ccache 4.6.3 already contains a fix for the issue.

Fixes: https://github.com/openwrt/openwrt/issues/12462

### CODE REVIEW

**Comment by Ansuel** [comment]
@mchehab can you include the fixes tag in the commit? (right before the sob tag, no new line)

**Comment by PolynomialDivision** [comment]
Please change title to [22.03]. Further, you would use `git cherry-pick -x 83ea2e11b4b7872642bc7ac587361ccd783308f2` to backport from master the commit: https://github.com/openwrt/openwrt/commit/83ea2e11b4b7872642bc7ac587361ccd783308f2

**Comment by mchehab** [comment]
> @mchehab can you include the fixes tag in the commit? (right before the sob tag, no new line)

Done.

> Please change github title to [22.03]. 

Done.

> Further, you would use `git cherry-pick -x 83ea2e11b4b7872642bc7ac587361ccd783308f2` to backport from master the commit: [83ea2e1](https://github.com/openwrt/openwrt/commit/83ea2e11b4b7872642bc7ac587361ccd783308f2) However, not sure if that is needed here.

Not sure if it it is need - or if it makes sense - as changeset 83ea2e1 doesn't revert changeset 3de4572ed308. 

Perhaps I can add something like: 

```
Backports 83ea2e11b4b7 ("ccache: update to 4.6.3")
```

To its description.

**Comment by hauke** [comment]
I cherry-picked the individual patches in eeff8b3be101b639dd4d99e50bb0de0a3ae63f7c, 80653f0c07aeef1c0e37c1aad828158f6e47eaee and c1ccae54ceb6d5b5d8572e061f1159293dc25917.

**Pull request closed without merging**
