### PR TITLE
Add support for ZyXEL Keenetic series

### PR DESCRIPTION
**Pull request by tolkonepiu**
This pull request based on svn diff 47 from S-Trace (S-trace@list.ru). Added support for models:
- ZyXEL Keenetic
- ZyXEL Keenetic 4G rev.A
- ZyXEL Keenetic 4G rev.B/NBG4114
- ZyXEL Keenetic Lite rev.A
- ZyXEL Keenetic Lite rev.B/NBG4104

### CODE REVIEW

**Comment by wigyori** [comment]
@tolkonepiu - thanks for the fixup, can you please make sure the docs for the devices are created/filled on the wiki? We'd also need the SoB on the commits and a bit more detail on the devices.

Thanks,
-w-

**Comment by tolkonepiu** [comment]
Ok:smile:

**Comment by wigyori** [comment]
Ping @tolkonepiu ? :)

-w-

**Comment by KOLANICH** [comment]
Btw, how about reusing dir620 page? It is known to be nearly identical to keenetic and often was flashed with keenetic firmware. BTW, how about hwnat?

**Comment by lgp698asd** [comment]
Hi openwrt!
@wigyori 
wiki? https://wiki.openwrt.org/toh/zyxel/keenetic
"We'd also need the SoB?" what is it SoB?

**Comment by wigyori** [comment]
@lgp698asd - well, for the wiki that's a bit too short, refer to f.e. this [1] page. :)  SoB is the Signed-off-by signature, pls refer to [2].

[1] https://wiki.openwrt.org/toh/tp-link/tl-wr741nd
[2] https://ltsi.linuxfoundation.org/developers/signed-process

**Comment by wigyori** [comment]
Ping @lgp698asd

**Comment by mxl** [comment]
What's the state of this PR?

**Comment by blogic** [comment]
already part of the LEDE tree which will replace the OWRT tree shortly

**Comment by nerijus** [comment]
Could you please show the changes in LEDE tree? I don't see them.

**Comment by nerijus** [comment]
Why is it closed without any comment?

**Comment by robototechnic** [comment]
Also interested. There is no information about ZyXEL Keenetic 4G rev.B / NBG4114 in the source.

**Comment by nos1609** [comment]
@blogic @jow- Any obstacles to merging this pr? Because I've checked both openwrt and lede repos, and they're only 4 models present in ramips board configs, while with those listed here they already should be 8 in total. Please check commits once again. Thanks

**Comment by mkresin** [comment]
It can't be merged as it is. The whole PR is based on outdated code and contains more than 250 (unintended) commits. Someone need to re-spin the PR based on the current development code.

**Comment by tolkonepiu** [comment]
@mkresin, i can do it.

**Pull request closed without merging**
