### PR TITLE
scripts: feeds: fix version detection for Make >= 3.8.1

### PR DESCRIPTION
**Pull request by imShara**
Simillar with issue #24 and patch f51dd01ca6df8e773424f37cfe2b136cb0d37c10

### CODE REVIEW

**Comment by nbd168** [comment]
When you copy code from elsewhere, you should leave proper attribution in place

**Comment by imShara** [comment]
@nbd168, how it can be done in this case? I made links to parent commit in master branch.

**Comment by nbd168** [comment]
Import the commit that you want to backport, then edit the commit message, instead of just committing the change yourself

**Comment by wigyori** [comment]
git commit --author='John Doe' , then copy-paste the commit message from the original place - if you're using the standard linux git toolset.

**Pull request closed without merging**
