### PR TITLE
kernel: remove duplicated disabled entries from 5.4 kconfig

### PR DESCRIPTION
**Pull request by abajk**
I wrote script. It deletes disabled entries from subtargets if they exist in generic kconfig.

For example kernel_oldconfig for imx6 show that we can delete 159 disabled config entries:
~~~
$ kernel_oldconfig CONFIG_TARGET=subtarget_platform
$ git diff | grep ^-# | wc -l
159
~~~
and this script do part of this work for all subtargets.

Check if script work well. Diff between work done on imx6 by oldconfig and this script:
~~~
$ git diff origin/duplicated-disabled target/linux/imx6/ | grep "#" | grep -v ^" #"
-# CONFIG_FSL_IMX8_DDR_PMU is not set
+# CONFIG_SENSORS_DRIVETEMP is not set
~~~

* CONFIG_SENSORS_DRIVETEMP:
 is new symbol and oldconfig want add this.
* CONFIG_SENSORS_DRIVETEMP:
 is definied nowhere and oldconfig want delete this additionaly.

It look like that it work well.

### CODE REVIEW

**Comment by mkresin** [comment]
Something is wrong with your script. Looking at the lantiq target

```
target/linux/lantiq/config-4.19:CONFIG_PSB6970_PHY=y
target/linux/lantiq/config-5.4:CONFIG_PSB6970_PHY=y
target/linux/lantiq/ase/config-4.19:# CONFIG_PSB6970_PHY is not set
target/linux/lantiq/ase/config-5.4:# CONFIG_PSB6970_PHY is not set
target/linux/lantiq/falcon/config-4.19:# CONFIG_PSB6970_PHY is not set
target/linux/lantiq/falcon/config-5.4:# CONFIG_PSB6970_PHY is not set
```

it isn't expected that `CONFIG_PSB6970_PHY` gets removed from `ase/config-5.4` and `falcon/config-5.4`.

**Comment by olek210** [comment]
You're right. it doesn't work when:
- generic config disables symbols,
- target config enables,
- subtarget again disables.

Script works well only for target configs, so subtarget kconfig were removed from this PR. Mediatek is included because it don't have target config and in this situation script schould work.

PR is now fixed :)

**Comment by peterwillcn** [comment]
Mark

**Comment by adrianschmutzler** [comment]
Thanks for your effort. However, I don't think this method is very effective:
It is quite hard to review, it will be outdated if only one of the targets change their config, and it detaches the reviewing process from the targets affected.

I'd personally prefer to have the config refreshed per target/subtarget and committed for the individual targets as well. This will also help with review, as the number of changes per commit is reduced.

In the meantime, the PR is quite outdated anyway. I'm not going to review/merge it in this fashion, and based on the history I don't think anybody else will. So, I recommend to close this and provide per-target refreshes were necessary. Still, thanks for bringing up the discussion.

**Pull request closed without merging**
