### PR TITLE
Introduce `findrev` from `luci.mk`

### PR DESCRIPTION
**Pull request by aparcar**
To avoid manual increasing of PKG_RELEASE for every change the
$(AUTORELEASE) and $(COMMITCOUNT) functions were previously added. While
those perfectly automated the previous release schema, they required a
full Git history to work. With ever increasing popularity of OpenWrt,
this brings server infrastructure to stall and wastes bandwidth.

An alternative is the automatic revision finding used in luci.git, where
the function `findrev` automatically generates a PKG_RELEASE based on
the last commit.

A modified `findrev` version is added to the rules.mk file to represent
custom needs. Most prominently the `base-files` package requires the
revision of openwrt.git and not of the package specific sub-folder.

The function `findrev` works also without using a Git repository by
falling back to the last file modification time.

### CODE REVIEW

**Comment by ynezz** [comment]
> To avoid manual increasing of PKG_RELEASE for every change

I really fail to see what is wrong with that, rather the opposite, fixed numbers are well, good old fixed numbers. And if the human factor is the problem, then lets fix this with CI instead.

Anyway, if you really want to proceed, then please at least consider doing it after branching of '23 release.

**Comment by aparcar** [comment]
Sure we can do that with CI, too. I just thought that luci uses this anyway and at least for base-files no CI can really fix it.

**Comment by Ansuel** [comment]
why rules.mk and not version.mk?

**Comment by aparcar** [comment]
This should be handled via CI

**Pull request closed without merging**
