### PR TITLE
mac80211: Fix wifi throughput

### PR DESCRIPTION
**Pull request by hauke**
Backport 2 patches from upstream Linux to fix a Wifi throughput problem.

### CODE REVIEW

**Comment by lorand-horvath** [comment]
@hauke Are these patches needed for kernel 6.6 as well?

**Comment by AgustinLorenzo** [comment]
Hi @hauke 

Yep, these patches seem to be required for 6.6.

I am seeing in the log this

```
[21638.517648] Ignoring NSS change in VHT Operating Mode Notification from 5a:8f:b0:2d:10:c0 with invalid nss 2
[29083.401386] Ignoring NSS change in VHT Operating Mode Notification from 5a:8f:b0:2d:10:c0 with invalid nss 2
[30627.499654] Ignoring NSS change in VHT Operating Mode Notification from 5a:8f:b0:2d:10:c0 with invalid nss 2
```
Regards, Agustin

**Review by ricsc — APPROVED** [review]
I applied the patches to my 23.05.4 build and can confirm, that they fix the wifi throughput issue seen in 2.4G using a R7800 + Pixel 6a.

**Review by egc112 — APPROVED** [review]
I just compiled with these two patches using Kongs Repo and can confirm that the 2.4 GHz speed is 106 Mb/s up from 52 Mb/s without any patches. 
MCS indicating it is now using both streams, MCS up from 7 without patches to 15 with patches
Thank you all!

**Comment by WildByDesign** [comment]
Can anyone please confirm if this fixes throughout on 5GHz as well?

I assume yes, but I cannot test right now. Thanks.

**Comment by egc112** [comment]
I have no before testing done this time but I currently  have 640 Mb/s from my Samsung S20, 80 MHz
afbeelding

**Comment by rany2** [comment]
> Can anyone please confirm if this fixes throughout on 5GHz as well?
> 
> I assume yes, but I cannot test right now. Thanks.

Yes for me, on Pixel 7 my up speed went from 600Mb/s to 850Mb/s. This on 802.11ax mt7915. Note that when testing you need to run the test for a minute or more to get it out of the power save mode.

**Review by rany2 — APPROVED** [review]

**Comment by rpodric** [comment]
Does this problem pertain to the recent 22.03.7 too, as it also saw an update for mac80211, though not the one mentioning "backport" that v23 did.

**Comment by hauke** [comment]
This is not a problem in master, because it uses mac80211 from kernel 6.9 which fixed the problem.
Maybe this is a problem in 22.03, but this version is now unsupported. 

I am working on getting these patches into Linux stable 6.1 and 6.6 tree.

**Pull request merged**
