### PR TITLE
ath79: Consistent labels for Unifi AC devices and addition of AC Mesh

### PR DESCRIPTION
**Pull request by adschm**
1. Label Unifi AC Lite consistent with other Ubiquiti devices
=> Just follow the naming scheme of all other ubnt devices in ath79 target.
2. Add definitions for Unifi AC Mesh
=>  The Unifi AC Mesh is equivalent to the Unifi AC Lite. However,
    for setting certain parameters with the flashed device it is
    helpful that the devices know their variant (e.g. automatically
    setting antenna gain for the different antennas in Lite and Mesh).

### CODE REVIEW

**Comment by lucize** [comment]
please be aware that this https://github.com/openwrt/openwrt/pull/1090 will be merged soon and maybe rebase on that

**Comment by adrianschmutzler** [comment]
Will do that, #1090 seems quite helpful.

**Comment by mkresin** [comment]
I rebased and cherry picked only your "ath79: Label Unifi AC devices consistent with other Ubnt devices" commit to [my staging tree](https://git.openwrt.org/?p=openwrt/staging/mkresin.git;a=summary) for now.

@lucize I've applied the same changes to your Unifi commit in my staging tree.

I'm not yet sure about the "ath79: Add definitions for Unifi AC Mesh" commit. Beside the userspace boardname, the dts/image is identical to the unifiac-lite. Even the model name in the device tree mentions the mesh already.

I'm rather thinking about adding the `ubnt-unifiac-mesh` to the `SUPPORTED_DEVICES` of the unifiac-lite image and using this image instead. We might rename the ubnt_unifiac-lite image to something like ubnt_unifiac-lite-mesh.

Let me hear what you are thinking about it.

**Comment by adrianschmutzler** [comment]
@mkresin Thanks so far.
Let me explain my problem: I use an OpenWRT-based firmware.
OpenWRT does not consider the antenna gain when setting tx power for ubnt devices, so default tx power is illegal. I do take care of that by setting the antenna gain based on board/device name automatically in my firmware. With ar71xx, there was a function setting the model string based on some magic (https://github.com/openwrt/openwrt/blob/master/target/linux/ar71xx/base-files/lib/ar71xx.sh#L105). With ath79, this function is not present anymore and I cannot distinguish between AC Lite and AC Mesh, which bear different antennas (by default). So I would like to have at least different model strings for Mesh and Lite so I can set legal tx power by default. The easiest way to achieve this was adding a dts for the AC Mesh.

**Comment by mkresin** [comment]
Gotcha. I merged a slightly modified version to [my staging tree](https://git.openwrt.org/?p=openwrt/staging/mkresin.git;a=summary). Please build and test an image from my staging tree to ensure everything is still working.

**Comment by lucize** [comment]
does it means that mesh pro should be the same ?

**Comment by adrianschmutzler** [comment]
That's a general question: The same question arises for Bullet M vs. Loco M vs. Picostation M, which have been identified before in ar71xx, but are not (so far) in ath79. So far, I do not know whether one should really split all of them or whether it would be better to just have an identification script within the same image as for ar71xx ...

**Comment by mkresin** [comment]
>  or whether it would be better to just have an identification script within the same image as for ar71xx ...

No please not. The ar71xx scripts turned into a near to unmaintainable shell script hell over time. I'm really glad that we got rid of them.

I guess at the time the scripts were added, it was the same discussion. Wasting build resources vs. a small shell script (which it isn't any more). I'm for wasting build resources now days.

> does it means that mesh pro should be the same ?
> The same question arises for Bullet M vs. Loco M vs. Picostation M

I would like to regret from adding dedicated images, till there is a real need as with AC mesh. I've no idea if the antenna gain can be fixed with a few lines of code, hence I'm fine to add a dedicated image (albeit I would like to see this issues fix for all AC Mesh users by including $something).

**Comment by adrianschmutzler** [comment]
I also like the conciseness of the ath79 approach. Forgive me, but I take the opportunity to share some thoughts in this context:

Same background on the antenna topic:
With other devices, the antenna gain is somehow read automatically from the driver (at least as I understand it). This is not working for the ubnt devices.
I thus solved this problem with a simple script adding something like
uci set wireless.radio0.antenna_gain=4
in an uci-default script. The decision for which value is used is done by the model string. The values were entered individually based on research.
Note that Bullet M has no antenna by default, Loco M has one and Picostation M has a different one plus a preamplifier which is also not dealt with automatically.
I am not capable of implementing a good solution for OpenWRT myself, as I have no expertise with driver stuff etc. However, setting values for the devices supported manually is okay for me, as long as I can distinguish them.

Regarding adding dedicated images:
I do like the idea of devices being identified unambiguously. Especially with the Ubnt M devices, there is also always the problem of finding the right image for your device: Do I need nano-m or bullet-m for the picostation? If my loco M has xw hardware, I need the loco-m-xw, but if its xm, I need the bullet-m image although the name is different... This has room for improvement.
Providing dedicated images would solve this problem and the problem of the device identification at rumtime (maybe other people require this for reasons different from just setting antenna gain).
I tend towards this way, especially since the dts structure makes implementations clearer than they were before. Still, I wait for an ultimate optimal solution to rise at the horizon ...

Maybe I should just start a PR for Bullet-M (which would be a 5-minute-task) and wait for the feedback ...?

**Comment by adrianschmutzler** [comment]
@mkresin !! Found an error in my AC Mesh patch which went into your staging tree: 
generic-ubnt.mk in line 104 (at the bottom of the patch diff) should say
TARGET_DEVICES += ubnt_unifiac-mesh
instead of
TARGET_DEVICES += ubnt_unifiac-lite

**Comment by mkresin** [comment]
Excelent catch!

Applied to following patch:

```diff
diff --git a/target/linux/ath79/image/generic-ubnt.mk b/target/linux/ath79/image/generic-ubnt.mk
index 3c98d39..540277d 100644
--- a/target/linux/ath79/image/generic-ubnt.mk
+++ b/target/linux/ath79/image/generic-ubnt.mk
@@ -99,9 +99,9 @@ TARGET_DEVICES += ubnt_unifiac-lite
 define Device/ubnt_unifiac-mesh
   $(Device/ubnt_unifiac)
   DEVICE_TITLE := Ubiquiti UniFi AC-Mesh
-  SUPPORTED_DEVICES := ubnt,unifiac-mesh ubnt-unifiac-mesh
+  SUPPORTED_DEVICES += ubnt-unifiac-mesh
 endef
-TARGET_DEVICES += ubnt_unifiac-lite
+TARGET_DEVICES += ubnt_unifiac-mesh
 
 define Device/ubnt_unifiac-pro
   $(Device/ubnt_unifiac)
```

**Comment by adrianschmutzler** [comment]
@mkresin Quickly test-flashed a device today and everything looked okayish ...

**Pull request closed without merging**
