### PR TITLE
ramips: backport mt7621-spi from linux-next-20190329

### PR DESCRIPTION
**Pull request by 981213**
Upstream driver has gone through a series of cleanup and was moved
from drivers/staging into drivers/spi. Backport it to replace our
messy driver.

Signed-off-by: Chuanhong Guo <gch981213@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Note that it's quite a speedup.

time dd if=/dev/mtdblock3 of=/dev/null bs=64k

Before:
14.09s.

After:
6.16s

**Comment by peterwillcn** [comment]
ramips test pass
```
[    2.497430] MediaTek Nand driver init, version v2.1 Fix AHB virt2phys error
[    2.504736] spi-mt7621 1e000b00.spi: sys_freq: 220000000
[    2.520188] m25p80 spi0.0: w25q256 (32768 Kbytes)
[    2.524934] 4 fixed-partitions partitions found on MTD device spi0.0
[    2.531277] Creating 4 MTD partitions on "spi0.0":
[    2.536057] 0x000000000000-0x000000030000 : "u-boot"
[    2.542035] 0x000000030000-0x000000040000 : "u-boot-env"
[    2.548278] 0x000000040000-0x000000050000 : "factory"
[    2.554185] 0x000000050000-0x000002000000 : "firmware"
[    2.560456] 2 uimage-fw partitions found on MTD device firmware
```

**Comment by joerg555** [comment]
Hi,
i have checked the patch on an MT7688 "AI7688" modul, ist working fine, very good speedup.
time dd if=/dev/mtdblock3 of=/dev/null bs=64k
before:
507+0 records in
507+0 records out
real    0m 31.17s
user    0m 0.00s
sys     0m 0.37s
after:
507+0 records in
507+0 records out
real    0m 13.04s
user    0m 0.00s
sys     0m 0.35s

**Comment by ynezz** [comment]
@peterwillcn @joerg555 Thanks for testing, it's very helpful. Could you please as well provide your `Tested-by: Real Name <real@email.com> [device tested on]`?

**Comment by joerg555** [comment]
Hi,
i have checked the patch on an MT7688 "AI7688" modul, ist working fine, very good speedup.
time dd if=/dev/mtdblock3 of=/dev/null bs=64k
before:
507+0 records in
507+0 records out
real 0m 31.17s
user 0m 0.00s
sys 0m 0.37s
after:
507+0 records in
507+0 records out
real 0m 13.04s
user 0m 0.00s
sys 0m 0.35s
Tested-by: Jörg Schüler-Maroldt <joerg-linux@arcor.de> [LinkIt Smart 7688, AcSIP AI7688H Wi-Fi module]

**Comment by neheb** [comment]
Tested-by: Rosen Penev <rosenp@gmail.com>

**Comment by peterwillcn** [comment]
Tested-by: Tian Xiao bo peterwillcn@gmail.com [Newifi-D2 MediaTek MT7621 ver:1 eco:3]

**Comment by chunkeey** [comment]
Merged. Thanks.

**Pull request closed without merging**
