### PR TITLE
ath79: add support for TP-Link Archer C5 v1

### PR DESCRIPTION
**Pull request by terual**
I have tested the functionality on the device.

TP-Link Archer C5 v1 is a dual band router
based on Qualcomm/Atheros QCA9558 + QCA9880.

Specification:

 - 720 MHz CPU
 - 128 MB of RAM (Various chips)
 - 16 MB of FLASH (Various chips)
 - SoC QCA9558 integrated 3T3R 2.4 GHz Wi-Fi
 - minipcie slot with 3T3R 5 GHz QCA9880-BR4A
 - 5x 10/100/1000 Mbps Ethernet (AR8327N Switch)
 - 10x LEDs, 2x software buttons

For further informwation on the device, visit the wiki:
<https://openwrt.org/toh/tp-link/archer-c5-c7-wdr7500>

Signed-off-by: Bart Lauret <bblauret@gmail.com>

### CODE REVIEW

**Comment by chunkeey** [comment]
Merged. Thanks.

**Comment by adrianschmutzler** [comment]
Although this PR has been has been closed already, I would be interested in some additional data about the device(s) in case you still have access to it:

I'm currently working on a PR to store the label-mac-address in the DTS (https://github.com/openwrt/openwrt/pull/2159).

I would appreciate if you could provide information about your device:
Please run
`find /proc/device-tree/ -name "*mac-address*"`
on your device (just with the current firmware, no need to update anything; just has to be ath79, no ar71xx).
For each of the returned paths (if there are any), retrieve the mac-address with `cat`, e.g.
`cat /proc/device-tree/ahb/eth@19000000/mac-address`

Now check which of those returned MAC addresses matches the one on the label/sticker/case of your device and tell me the device-tree path leading to it. Note that you do not have to post your MAC addresses here, but just a statement about which match, e.g. like
```
/proc/device-tree/ahb/eth@1a000000/mac-address
/proc/device-tree/ahb/eth@1a000000/mtd-mac-address-increment
/proc/device-tree/ahb/eth@1a000000/mtd-mac-address
/proc/device-tree/ahb/eth@19000000/mac-address <== this one
/proc/device-tree/ahb/eth@19000000/mtd-mac-address
/proc/device-tree/ahb/apb/wmac@18100000/mac-address
/proc/device-tree/ahb/apb/wmac@18100000/mtd-mac-address
```

There may be one, two or no paths giving the correct address. It may also happen that the `find` command returns nothing. Thanks.

**Comment by terual** [comment]
These paths return binary information on this device, but using hexdump on these paths I get MAC-addresses. Right now I do not have physical access to the device, so I cannot check these MACs to the sticker. Is it still valuable to check knowing it returns the MAC in binary?

By the way
`find /proc/device-tree/ -name "*mac-address*"`
returns
```
/proc/device-tree/ahb/eth@1a000000/mac-address
/proc/device-tree/ahb/eth@1a000000/mtd-mac-address
/proc/device-tree/ahb/eth@19000000/mac-address
/proc/device-tree/ahb/eth@19000000/mtd-mac-address-increment
/proc/device-tree/ahb/eth@19000000/mtd-mac-address
/proc/device-tree/ahb/apb/wmac@18100000/mac-address
/proc/device-tree/ahb/apb/wmac@18100000/mtd-mac-address
```

**Comment by adrianschmutzler** [comment]
Ah, sorry, I went too fast writing that...
Data is expected to be binary, and you can read the addresses simply by
```
. /lib/functions/system.sh
get_mac_binary "$yourpath" 0
```

However, for your device I would only require the data for confirmation, so I only need it if it's accessible with minimum effort.

Thanks again for reporting the `cat` mistake.

**Comment by terual** [comment]
The MAC address from the sticker on the back of the router was visibile in two locations:

```
/proc/device-tree/ahb/eth@1a000000/mac-address <== this one
/proc/device-tree/ahb/eth@1a000000/mtd-mac-address
/proc/device-tree/ahb/eth@19000000/mac-address
/proc/device-tree/ahb/eth@19000000/mtd-mac-address-increment
/proc/device-tree/ahb/eth@19000000/mtd-mac-address
/proc/device-tree/ahb/apb/wmac@18100000/mac-address <== and this one
/proc/device-tree/ahb/apb/wmac@18100000/mtd-mac-address
```

**Comment by adrianschmutzler** [comment]
Thanks, so I use `label-mac-device = &eth1;`.

**Pull request closed without merging**
