### PR TITLE
toolchain: mold: Update to 2.33.0

### PR DESCRIPTION
**Pull request by schuettecarsten**
https://github.com/rui314/mold/releases/tag/v2.33.0

### CODE REVIEW

**Comment by schuettecarsten** [comment]
@PolynomialDivision @robimarko
Can you please review an maybe merge this? :-)

**Comment by robimarko** [comment]
Did it compile on macOS before?

**Comment by schuettecarsten** [comment]
> Did it compile on macOS before?

I cannot answer this as I do my builds on an Ubuntu machine.
Does it fail on macOS now?

**Comment by robimarko** [comment]
Yes, you can see its failling to build in CI for macOS

**Comment by Rondom** [comment]
It is a bit hard to solve MacOS specific issues if one does not have the hardware. @robimarko  Do you know anyone who can help?

@schuettecarsten  mold 2.33.0 has been released

**Comment by schuettecarsten** [comment]
Updated to mold 2.33.0

**Comment by robimarko** [comment]
I asked about macOS cause I dont remember whether it compiled before this update, if it did not then fixing it is not something that needs to be done in this PR.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
