### PR TITLE
Add Orange Pi PC2 support and Sunxi: ths dvfs support

### PR DESCRIPTION
**Pull request by Menion2k**
This pull request is made by two patch

patch #1 
    sunxi: Added support for Orange Pi PC2 
    Changed default role of Orange Pi PC2 MSUB port to host (in dts)
    Changed default function of Orange Pi PC2 power button to PWR_BTN

patch #2
    sunxi: add THS and DVFS support for selected H3/H5 boards
              (merge from megous/linux branch ths-4-14)
    Compile in kernel support for the voltage regulators SY8106A
    Add kernel support for SUN8I_THS

### CODE REVIEW

**Comment by wigyori** [comment]
Looks better, can you please:

 - Add a more reasonable commit title for the first patch ("sunxi: add support for Orange Pi PC 2"),
 - I'd be more happy to see the USB OTG in a separate commit to make it easier to discover. It can stay in the same commit, but please be verbose about the USB OTG state in the board description above,
 - Add some info about the board (you can use 70130268a85ea2373c6787414a20caa31ab05df7 as an example),
 - The config changes in the second commit are definitely wrong, please only add the required regulator changes,
 - You're also enabling CONFIG_REGULATOR_TPS51632, is it necessary, or only the SY8106 ?

Thanks,
-w-

**Comment by Menion2k** [comment]
Hi Zoltan, please check inline

2018-03-26 17:47 GMT+02:00 Zoltan Herpai <notifications@github.com>:

> Looks better, can you please:
>
>    - Add a more reasonable commit title for the first patch ("sunxi: add
>    support for Orange Pi PC 2"),
>
> How can I change the commit title now?

>
>    - I'd be more happy to see the USB OTG in a separate commit to make it
>    easier to discover. It can stay in the same commit, but please be verbose
>    about the USB OTG state in the board description above,
>
> Again, shall I blame and revert the commit? Or send a third patch? Please
consider that the OTG to HOST modification is dedicated to Pi PC2 and only
for that and can be changed in /sys/ anytime, I have made it as default
since I don't see point to have a router with a port in OTG

>
>    - Add some info about the board (you can use 7013026
>    <https://github.com/openwrt/openwrt/commit/70130268a85ea2373c6787414a20caa31ab05df7>
>    as an example),
>
> Ok, again, how/where can I add these info?

>
>    - The config changes in the second commit are definitely wrong, please
>    only add the required regulator changes,
>
> Well, this is the config-4.14 update that "make kernel_menuconfig" itself
copy back. Shall I selectively merge the mod manually? Again I have made no
modification except of the three mentioned

>
>    - You're also enabling CONFIG_REGULATOR_TPS51632, is it necessary, or
>    only the SY8106 ?
>
> yes, because some board where I have merged the THS use this regulator for
core voltages control. See the patch itself

**Comment by Menion2k** [comment]
Hi again
I have force pushed the update commit #1 message according to your suggestion
For the config-4-14: yes I made a mistake, I forgot that I have enabled also the CONFIG_IKCONFIG_PROC. I will try to amend this later on, I am not very familiar with pull request flow, shall I modify the commit, or add a new one with the new config-4.14?

**Comment by Menion2k** [comment]
Zoltan I have just realized that I was wrong saying that also the TPS51632 is required, I made a mistake in following the (long) patchset for THS/DVFS. I will remove it in config-4.14 once you give me indication if it is enough that I manually add two entries (CONFIG_REGULATOR_SY8106A=y and CONFIG_SUN8I_THS=y) and if you want a new commit to fix it or I have to overwrite the commit #2

**Comment by Menion2k** [comment]
Hi again
I have verified that if is enough to add the two CONFIG only to get a consistent kernel config
I have reset and recommit the changes, automatic build has been triggered
Let me know if everything is ok now
It is also worth mentioning that I do have an Orange Pi PC2 running LEDE snapshot with working THS/DVFS
Bye

**Comment by hauke** [comment]
Hi, you can modify your existing commits with "git rebase origin/master  --interactive" and then force push the updated patches to your existing branch and the new versions will show up in this pull request.

Is the DVFS code similar to this version which is currently proposed for upstream Linux: https://lkml.org/lkml/2018/2/5/900 ?

There is also a similar pull request here: #830

**Comment by Menion2k** [comment]
Hi. I have rewritten the comments and fixed th config-4.14 some days ago.
Yes my patch are identical to the ones being proposed, in the comments I have specified where I have taken them (mogous branch is the reference branch that collects all the sunxi contributions). My patch includes also Orange Pi Pc (proposed in #830) but there is also DVFS

**Comment by Menion2k** [comment]
Hello
Is there anything that is preventing to add at least patch 1 that would add a new, good, board to the supported devices?

**Comment by wigyori** [comment]
As discussed on IRC, I'll try to take a look this weekend.

**Comment by wigyori** [comment]
Hi,
 - Pushed a very minimal board support to https://github.com/wigyori/openwrt/tree/master-opipc2 to get it up and running - let me know if you're fine with that, will merge after that,
 - As for the OTG change, I've moved that to a separate patch, included in the tree,
 - The DVFS change should be separated - please re-submit that part of this PR separately.
Apologies for the delay.

Regards,
-w-

**Comment by Menion2k** [comment]
Hi Zoltan
I will check your branch asap. the THS DVFS is already in a separated patch, which has no connection to the OpiPC2 patch. Is really necessary to fill a dedicated PR for it?

**Comment by Menion2k** [comment]
THS DVFS dedicated PR #1236 issued

**Comment by Menion2k** [comment]
Hello
I see that the patch 1 of this PR has been merged, and as agreed I filled another PR for patch 2. So I think this PR can be closed (the confilct comes from the merge of patch 1 without having tagged this as merged).

**Pull request closed without merging**
