### PR TITLE
busybox: update to 1.36.0

### PR DESCRIPTION
**Pull request by hnyman**
Update busybox to the new version 1.36.0 released today.

* refresh patches (remove the backported upstream fix)
* refresh config

I did not enable new applets (tree, tsort, seedrng)

Regarding new options, I did not set a default value to udhcpc6 script name, as we do not use the udhcpc6 applet. (Note that netifd provides the IPv4 script for udhcpc that we use.) 

Compiled & run-tested with ipq806x/R7800. 
(I also re-sysupgraded from the new version to see that sysupgrading works).

-----

Config refresh details:

Refresh commands, run after busybox is first built once:

```
cd package/utils/busybox/config/
../convert_menuconfig.pl ../../../../build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/busybox-default/busybox-1.36.0
cd ..
./convert_defaults.pl ../../../build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/busybox-default/busybox-1.36.0/.config > Config-defaults.in
```

Manual edits needed after config refresh, as the script removes some values/logic:

* Config-defaults.in: OpenWrt config symbol IPV6 logic applied to BUSYBOX_DEFAULT_FEATURE_IPV6

* Config-defaults.in: OpenWrt config TARGET_bcm53xx logic applied to BUSYBOX_DEFAULT_TRUNCATE (commit 547f1ec)

* Config-defaults.in: OpenWrt logic applied to BUSYBOX_DEFAULT_LOGIN_SESSION_AS_CHILD (commit dc92917)

* Config-defaults.in: correct the default ports that get reset
  BUSYBOX_DEFAULT_FEATURE_HTTPD_PORT_DEFAULT    80
  BUSYBOX_DEFAULT_FEATURE_TELNETD_PORT_DEFAULT  23

* config/editors/Config.in: Add USE_GLIBC dependency to BUSYBOX_CONFIG_FEATURE_VI_REGEX_SEARCH (commit f141090)

* config/shell/Config.in: change at "Options common to all shells" the conditional symbol SHELL_ASH --> BUSYBOX_CONFIG_SHELL_ASH (discussion in http://lists.openwrt.org/pipermail/openwrt-devel/2021-January/033140.html Apparently our script does not see the hidden option while prepending config options with "BUSYBOX_CONFIG_" which leads to a missed dependency when the options are later evaluated.)

* Edit a few Config.in files by adding quotes to sourced items in config/Config.in, config/networking/Config.in and config/util-linux/Config.in (commit 1da014f)

### CODE REVIEW

**Comment by hardfalcon** [comment]
It might make sense to include this commit from upstream which fixes one occurrence of undefined behaviour:
https://git.busybox.net/busybox/commit/?id=ca96022d6edaaf619324db5a481698231d74d1df

**Comment by hnyman** [comment]
Yeah,  I noticed the new upstream commit and I might include it into the PR.
But I do not see that commit very crucial to us, as it only concerns the probably rarely used "ed" editor.

**Comment by hardfalcon** [comment]
> Yeah, I noticed the new upstream commit and I might include it into the PR. But I do not see that commit very crucial to us, as it only concerns the probably rarely used "ed" editor.

My personal preference would be to include that patch as a separate commit in order to allow for easier bisecting just in case it turns out to cause issues after all (which I still consider pretty unlikely).

**Comment by neheb** [comment]
```
qemu-mips-static: Could not open '/lib/ld-musl-mips-sf.so.1': No such file or directory
```

Can't install

**Pull request merged**
