### PR TITLE
ar71xx: add support for Zsun WiFi SD Card Reader

### PR DESCRIPTION
**Pull request by gdm85**
I have cherry-picked all the new commits from https://github.com/Emeryth/openwrt-zsun to attempt adding upstream support for this tiny device.

I am building & testing this branch as of writing; should the commit about the signing key be dropped?

### CODE REVIEW

**Comment by wigyori** [comment]
Thanks for trying to upstream the board support, but this'll require some more effort. :)  

Some thoughts:
 - there is no reason to re-add the 3.18 support, so please re-base it on the current 4.4 kernel
 - the mach file looks OK
 - please re-base the 415- patch onto 4.4 (if support for this chip is not already available in that kernel)
 - add only the ATH79_MACH_ZSUN_SDREADER into machtypes.h
 - same goes for Kconfig.openwrt and Makefile
 - the uci-defaults/99_zsun-enable-wifi file is OK there

Let me know how it goes, I'm happy to help.

Thx,
-w-

**Comment by gdm85** [comment]
@wigyori thanks for your feedback, I was hoping on some help like this. Unfortunately - although I am familiar with kernel/modules building - I am new to openwrt so I am having some issues to understand this part:

> add only the ATH79_MACH_ZSUN_SDREADER into machtypes.h
> same goes for Kconfig.openwrt and Makefile
> 

As you can see I made an attempt in 6f8ae6e, although I have not yet figured out how to change the `Makefile` - or whether it's needed. Can you please elaborate a bit further?

**Comment by wigyori** [comment]
Hi @gdm85 ,

So:
 - 80482b8 - please drop this commit completely,
 - config-3.18 - drop this completely please. CC release was based on 3.18, but trunk is currently on 4.4, so any diffs to the config should be patched into config-4.4 .
 - In the initial PR I saw a new machtypes.h file added. There is no need to add it, rather the existing machtypes.h should be patched. Same goes for Kconfig.openwrt. This is exactly what You're doing in c0906d0.
 - While You're working on support for this device, would you mind to update the wiki? :)  https://wiki.openwrt.org/toh/zsun/wifi-card-reader

Thanks!

-w-
 - 415-mtd-m25p80-add-w25q128fw.patch - this should be rebased to apply onto 4.4 kernel.
 -

**Comment by gdm85** [comment]
@wigyori it took me a while to realize that one of the patches was modifying the local files! Wasn't expecting that. I think I got it right now: please review 460d1803cf8cf880d1ed710490ac4c10638fdb36 vs the original patch https://github.com/Emeryth/openwrt-zsun/blob/zsun/target/linux/ar71xx/patches-3.18/610-MIPS-ath79-openwrt-machines.patch

I think that patch contained a lot of stuff that was unrelated to the Zsun itself.

Only thing left for me now is to rebase `415-mtd-m25p80-add-w25q128fw.patch`, update the wiki and then of course test this :)

**Comment by gdm85** [comment]
I have rebased the Linux kernel patch and found out that `w25q128fw` has already been added to `spi-nor.c`; by reading the disclaimer in `m25p80.c` it seems like that it would not be needed to add `m25q128fw` there, but regardless I did to preserve the intent of original PR and this is the resulting small patch left: https://github.com/gdm85/openwrt/blob/fa24e0bc6ff27bd0f4d0a4431b36b8103a241350/target/linux/ar71xx/patches-4.4/415-mtd-m25p80-add-w25q128fw.patch

**Comment by wigyori** [comment]
I think you're getting close, can you do a cleaned up PR and rebase the patches onto a current trunk? I just spotted that ar71xx has dropped 3.18 support some time ago, so You seem to be using some old tree - sorry for not spotting that earlier.

**Comment by gdm85** [comment]
@wigyori I think I messed up first time by letting git attach the commits to the original parents with automerge; a careful conflict resolution has led to the current commits which seem much cleaner. It is also rebased.

I will now verify if this builds (and meanwhile openwrt's PR builder should too).

**Comment by gdm85** [comment]
It builds successfully, however I do not see the sysupgrade image being generated.

I think it's due to the u-boot uImage being larger, 1.3M (this branch) vs 1.2M (original chaos calmer branch), for reference https://owncloud.hackerspace.pl/index.php/s/7s5c5RDS7Njgwpv?path=%2F2016-01-12

The maximum allowed for that mtd partition would be 1245184 bytes. Since flashing a partial uBoot image will brick the device, how do we prevent this scenario?

I will now try removing something from the .config to generate a smaller image.

**Comment by gdm85** [comment]
@wigyori sorry to bother you, any other suggestion?

**Comment by zoobab** [comment]
Good to see that someone was working on taking the patches back to trunk.

Could we get the commits in LEDE as well?

**Comment by GilDev** [comment]
Any news on this?

**Comment by ShapeShifter499** [comment]
I'd like to know about this too.

@zoobab  Also Lede support sounds nice

**Comment by hellyberry** [comment]
LEDE support would be great

**Comment by gdm85** [comment]
Oh, sorry, lost track of the comments here. @zoobab I asked also on mailing list, no reply. I still have the issue mentioned in [comment](https://github.com/openwrt/openwrt/pull/312?_pjax=%23js-repo-pjax-container#issuecomment-272302178):
> It builds successfully, however I do not see the sysupgrade image being generated.
> 

Perhaps somebody with more OpenWRT experience can help/explain?

**Comment by opnwrt4lede** [comment]
As openwrt is abandoned it would be very nice to contribute this one to LEDE. There is a open and vital community around. There is also custom builds around and a Thread @ https://forum.lede-project.org/t/supporting-zsun-wifi-card-reader-16mb-flash-64mb-ram-ar9331/2142

Would be very nice if this one could get mainlined!

---
the king is dead - long live the king!

**Comment by gdm85** [comment]
@opnwrt4lede can you please clarify how you know OpenWRT is dead? Any official announcement/acknowledgement? The [wikipedia page](https://en.wikipedia.org/wiki/OpenWrt) doesn't say it's abandoned (not that I consider it authoritative for OpenWRT, but couldn't find anything official...)

**Comment by wigyori** [comment]
Ah, the good old FUD...

**Comment by opnwrt4lede** [comment]
@gdm85 just read the most recent issue #578 where a contributor says:

> None. Furthermore, **openwrt is a dead project** until they remerge with LEDE.

Another signal are also the missing security updates for openwrt and the fact that most active developers jumped on LEDE.

Anyway, would be nice to see this get's upstreamed!

---
the king is dead - long live the king!

**Comment by zoobab** [comment]
I gave a Zsun to Zoltan at last OpenWRT Summit in Prague to add support for it.

It has not been merged, either in LEDE or OpenWRT, because of special kernel partition I was told.

Apparently this device is not alone in the list of affected devices by this problem.

**Comment by opnwrt4lede** [comment]
@zoobab 

Thank's for your participation. Could you clarify the problem with the special kernel partition?
I thought the last remaining issue (beside getting the existing code into mainline) was the fact that LEDE ships the device with wifi off after flashing. For this device it would mean that it get's soft bricked through the act of flashing LEDE...

**Comment by zoobab** [comment]
There is a need to make an exception to that "wifi disabled" by default config.

The only easy way to configure the device is through wifi in this case, you don't want to implement a config system through USB files. Nor you want people to open the case and solder a serial console on those tiny test points.

**Comment by GilDev** [comment]
I flashed two Zsun with OpenWRT via WiFi and it worked beautifully, that's definitely a great feature!

**Comment by opnwrt4lede** [comment]
Looks like someone has most recent LEDE up and running including the imagebuilder =)

https://forum.lede-project.org/t/supporting-zsun-wifi-card-reader-16mb-flash-64mb-ram-ar9331/2142/71?u=dirlede

---
openwrt is dead - long live openwrt!

**Comment by gdm85** [comment]
@opnwrt4lede where is the source code there? I can only see compiled/binary images...

**Comment by ShapeShifter499** [comment]
@opnwrt4lede I thought LEDE and OpenWRT were supposed to be merged and the name was going back to OpenWRT.

**Comment by zoobab** [comment]
Closed 8 hours ago, but no explanation on whether support was added or not, either in OpenWRT or LEDE repo.

Had a quick check, it seems it has not been merged in any repo.

**Comment by gdm85** [comment]
Something worse must have happened. Seems like the master of OpenWRT was force-pushed or replaced, I have really never opened a PR with 10000+ commits to merge. My PR contained 5 commits.

I will rebase with the new master but really would be nice to have an explanation from @jow- at this point.

**Comment by gdm85** [comment]
I have rebased the PR on top of current master; Github will not update the PR stats unless it's reopened.

You can see it contains 5 commits (ahead of openwrt:master) here: https://github.com/gdm85/openwrt

**Comment by zoobab** [comment]
I think all the PRs were closed due to the LEDE/OpenWRT remerge.

But that's only a supposition, it would have been better to give an explanation.

Anyway one year for a Pull Request is totally insane.

They should adopt C4 process, like the Monero project:

https://rfc.zeromq.org/spec:22/C4/

"Maintainers SHALL merge correct patches from other Contributors rapidly."

**Comment by gdm85** [comment]
@zoobab I feel like now one should open a new PR and make some noise to get attention. Not my cup of tea. Feel free to re-open the PR with the commits I left there on my fork, I am unsubscribing this PR.

**Comment by rvs** [comment]
Seems like https://forum.lede-project.org/t/announcing-the-openwrt-lede-merge/10217 indicates that all PRs need to be resubmitted. Any chance @gdm85 could be interested in re-sending it?

**Comment by gdm85** [comment]
@rvs it would have been enough to re-open this one. Sure, I have created #678.

**Pull request closed without merging**
