### PR TITLE
ramips: drop gmac label patch, rename at preinit

### PR DESCRIPTION
**Pull request by lipnitsk**
Ubiquity ER-X and ER-X-SFP devices are the only ones that have a port
labeled 'eth0', which also is the default device name for the
mtk_soc_eth driver. The current solution for that involves labeling the
gmac as 'dsa' and patching mtk_soc_eth to use the label as the device
name, if available.

To avoid patching the driver, we can use 'eth00' or another temporary
name for the DSA slave in device tree, then rename the gmac/phy device
at preinit to free up 'eth0', then finally rename port0 to 'eth0' to
match the label on the router package.

Here are the relevant boot messages with this change applied on an ER-X
device:
[    5.095343] mtk_soc_eth 1e100000.ethernet eth0: mediatek frame engine at 0xbe100000, irq 20
[    5.212708] mt7530 mdio-bus:1f eth00 (uninitialized): PHY [dsa-0.0:00] driver [Generic PHY] (irq=POLL)
[   10.222691] mtk_soc_eth 1e100000.ethernet dsa: renamed from eth0
[   10.278705] mt7530 mdio-bus:1f eth0: renamed from eth00

Signed-off-by: Ilya Lipnitskiy <ilya.lipnitskiy@gmail.com>

erx

@adschm @981213 @dengqf6 @vDorst thoughts on this? Was the `net-ethernet-mediatek-support-net-labels.patch` meant to be upstreamed? If so, I can drop this change. It seems a little overkill to change the driver for just two devices though.

### CODE REVIEW

**Comment by vDorst** [comment]
For me dropping the label patch is fine. It was never intended to get in OpenWrt.

I think just rename the port to "lanX" so it is the same with the other devices.
I know that there were some discussion about this topic in the past.

**Comment by lipnitsk** [comment]
> I think just rename the port to "lanX" so it is the same with the other devices.

Do you mean temporarily rename to `lan0` instead of `eth00` then back to `eth0` at preinit? Or do you mean - don't use "ethX" for lan ports on er-x{,-sfp}? It is nice to match the label on the box with the port names, but not strictly necessary.

**Comment by ptpt52** [comment]
all ports use name `lan1 lan2 lan3 lan4 wan`
drop the `eth0~eth4`

**Comment by vDorst** [comment]
It is great to have same name in OpenWrt as it is printed on the device.
The extra effort to maintain it and that it is different from the other devices may not be worth it.

**Comment by adschm** [comment]
Stuff like this is the reason why I've been against labelling ports with ethX all the time.

Now we are exchanging one workaround for another, with the choice only being where it's hidden from the developers' eyes...

**Comment by adschm** [comment]
> > The extra effort to maintain it and that it is different from the other devices may not be worth it.
> 
> I don't think it's much to maintain, especially if we do the rename in userspace and drop the extra patch. I can name the conflicting port `wan` in device tree, then rename it to eth0 to match the label, in userspace.

Don't start with these renaming cascades. This is only making everything more complicated.

**Comment by lipnitsk** [comment]
So should we just do away with ethX and be done? lan1-4 and wan could be the names instead..

**Comment by adschm** [comment]
> So should we just do away with ethX and be done? lan1-4 and wan could be the names instead..

Well, then the question would be which is "wan" again. What if somebody prefers to have "wan" on eth4? He would really have a messed up config then.

I've been wondering whether something completely different like port1-port5 or similar would be the superior solution here ...

**Comment by lipnitsk** [comment]
> I've been wondering whether something completely different like port1-port5 or similar would be the superior solution here ...

So a brand new port naming scheme that doesn't match other devices, nor the label on the box? Maybe we should just work to upstream the label patch and call it good - no reason the driver must use `eth0`, is there?

**Pull request closed without merging**
