### PR TITLE
ramips: replace AR8033 fiber hack with 5.18 patches

### PR DESCRIPTION
**Pull request by kestrel1974**
A patch was added in kernel 5.4 to support the fiber operation of AR8033 with ramips devices. In kernel 5.18 similar enhancements were added to the kernel. Those patches are required for other fiber based devices but when added, build fails for ramips targets. This commit removes the ramips patch and adds the kernel 5.18 ones.

The kernel patches are needed for another device that have fiber based on AR8033. Can someone please check, if the Edgerouter X fiber devices still work, when the existing 710-at803x.patch is removed and the kernel 5.18 implementation is used instead?

Many thanks.

### CODE REVIEW

**Comment by the2masters** [comment]
Why is the patch "746-v5.18-01-net-phy-at803x-move-page-selection-fix-to-config_init.patch" only applied against kernel-5.10 and not against 5.15?

**Comment by kestrel1974** [comment]
> Why is the patch "746-v5.18-01-net-phy-at803x-move-page-selection-fix-to-config_init.patch" only applied against kernel-5.10 and not against 5.15?

@the2masters It was already there in kernel 5.15, but from the github.com/torvalds/linux it looks like the 3 patches belong together:

Commits on Jan 27, 2022
net: phy: at803x: Support downstream SFP cage  …
@robhancocksed
@davem330
robhancocksed authored and davem330 committed on Jan 27, 2022
 dc4d5fc  
net: phy: at803x: add fiber support  …
@robhancocksed
@davem330
robhancocksed authored and davem330 committed on Jan 27, 2022
 3265f42  
net: phy: at803x: move page selection fix to config_init  …
@robhancocksed
@davem330
robhancocksed authored and davem330 committed on Jan 27, 2022
 4f3a00c

**Comment by kestrel1974** [comment]
@the2masters I just checked, it was applied with kernel 5.15, should I rename this single patch to replace 5.18 to 5.15 for the 5.10 directory?
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/drivers/net/phy/at803x.c?h=v5.15.103

**Comment by the2masters** [comment]
I don't know about the naming rules for backported patches. It first appeared in 5.18, for me the name is ok.
I will test the patch later today on an edgerouter X SFP, I have a direct attach and a single mode fiber link to test it on.

**Comment by kestrel1974** [comment]
Thank you so much.

**Comment by the2masters** [comment]
It is working fine with my fiber link and also with direct attach SFP Module. I diffed dmesg output (after sorting it to get stable output), the following messages are missing now (without any other effect):
```
-at803x_config_aneg: fiber
-Qualcomm Atheros AR8031/AR8033 mdio-bus:07: SFP interface 1000base-x
```

I only tested kernel 5.15, as ramips switched to kernel 5.15 by default. I could revert 77d061167cf8a7edb3ea7cbc9926f25c8ac8fe1e and test 5.10, but I don't think this is needed.

Tested-by: Stefan Hellermann <stefan@the2masters.de>

**Comment by kestrel1974** [comment]
I saw that two when I look at the existing patch that it produces the fiber output, which is not in the official kernel drivers. I don't think that testing 5.10 is needed if the ramips target has already switched to 5.15.
Thanks.

**Comment by john-tho** [comment]
When you backport changes like this, you will also need to backport Fixes to them. Sometimes also Fixes for the Fixes…
https://github.com/torvalds/linux/commit/9926de7315be3d606cc011a305ad9adb9e8e14c9
https://github.com/torvalds/linux/commit/1f0dd412e34e177621769866bef347f0b22364df
```
# in the upstream Linux tree
git log --grep='3265f42188' --grep='dc4d5fcc5d36' --grep='4f3a00c7f5b2' 3265f42188.. --pretty=oneline
# search for the commit id in the commit log (as it appears in Fixes tags)
1f0dd412e34e177621769866bef347f0b22364df net: phy: at803x: fix error return code in at803x_probe()
9926de7315be3d606cc011a305ad9adb9e8e14c9 net: phy: at803x: fix NULL pointer dereference on AR9331 PHY
```

**Comment by Ansuel** [comment]
Why one in pending and the other in backport? they are both backport. Am I missing something?

**Comment by kestrel1974** [comment]
@Ansuel Pending 5.10 contains another patch [730-net-phy-at803x-fix-feature-detection.patch](https://github.com/openwrt/openwrt/blob/master/target/linux/generic/pending-5.10/730-net-phy-at803x-fix-feature-detection.patch) which is required or preceeding the patches I would like to add.
Or should the 730 patch be moved to the backport directory (which would need renumbering given the other at803x patches already there - added after 746-v5.16-04-net-phy...)?

**Comment by Ansuel** [comment]
@kestrel1974 730 is not present upstream? Or probably the same change was introduced by another patch?

We should first sort out this to understand what to do. Renumber and moving are O.K. if the final target is to cleanup patches and move them to backports.

**Comment by john-tho** [comment]
> @kestrel1974 730 is not present upstream?

From blame on at803x:
https://github.com/torvalds/linux/commit/b856150c8098f12996ee81c3ab2a65adbaeeb3ec
Looks like that went into 5.14; can rename the patch and move to backports.

**Comment by Ansuel** [comment]
@john-tho @kestrel1974 yep that should be the best solution.

If we really can... I would suggest to split this in 3 commits
- first to move the 730 to backport and add the correct patch (please don't move it but actually generate the patch from the merged commit)
- second 5.10 drop pending patch and add backport patch
- third 5.15 drop pending patch and add backport patch

name should be something like

ramips: 5.10: .....
ramips: 5.15: .....

**Comment by Ansuel** [comment]
@kestrel1974 any news with this?

**Comment by Ansuel** [comment]
@john-tho can you check it?

(hoping i won't have to refresh a 5.10 kernel...)

**Comment by john-tho** [comment]
> @john-tho can you check it?
> 
> (hoping they will apply correctly and i won't have to refresh a 5.10 kernel...)

@Ansuel From a very quick look at your pending730->back729 (https://github.com/openwrt/openwrt/compare/66d1526c3e70ab20cb1197fe5089f7c2f3a55d9f..c7cc412dad5bbf7bf2ab067afc7f98ac3b4c7999, it looks like only the patch header and context are different between our downstream, and the backported upstream patches. Maybe just replace the header? There is context in the backported patch we do not have in 5.10: https://github.com/torvalds/linux/commit/390b4cad81484124db2b676ed20a265adc032bae

**Comment by Ansuel** [comment]
@john-tho the backport comes from git format-patch -1 HASH so it's expected that the header change 

I missed the second commit you linked?

**Comment by john-tho** [comment]
> @john-tho the backport comes from git format-patch -1 HASH so it's expected that the header change

Yes, hash change to backported patch good.
Sorry, I called the whole patch commit text & headers _header_.
 
> I missed the second commit you linked?

No, the backported patch has patch context `at803x_smarteee_config` with the commit I linked.
Old OpenWrt pending patch did not.
Probably won't apply…?

Maybe if we copy the commit headers & text from the backport to the pending patch it should work, given they look the same except for commit headers, text & patch context?

**Comment by Ansuel** [comment]
@john-tho get what you mean... Testing it somewhere and then I will refresh this... Had an opportunity to introduce a new useful feature for CI

**Comment by Ansuel** [comment]
@the2masters sorry totally missed you tag :( my bad!

**Comment by kestrel1974** [comment]
@Ansuel Sorry for the delay, I did not have the time to make the changes and test it, I had planned it for next weekend.

**Pull request merged**
