### PR TITLE
ramips: add support for Lava LR-25G001

### PR DESCRIPTION
**Pull request by CHKDSK88**
The Lava LR-25G001 Wireless Router is based on the MT7620A SoC.

    Specification:

    - MediaTek MT7620A (580 Mhz)
    - 64 MB of RAM
    - 16 MB of FLASH
    - 1x 802.11bgn radio
    - 1x 802.11ac radio (MT7610EN)
    - 5x 10/100/1000 Mbps AR8337 Switch (1 WAN AND 4 LAN)
    - 2x external, detachable antennas
    - 1x USB 2.0
    - UART (J3) header on PCB (57600 8n1)
    - 8x LED (3x GPIO-controlled), 2x button
    - JBOOT bootloader

    Known issues:
    - Work only three Gigabit ports (3/5, 1 WAN and 2LAN)

    Installation:
    Apply factory image via http web-gui or JBOOT recovery page

    How to revert to OEM firmware:
    - push the reset button and turn on the power. Wait until LED start
      blinking (~10sec.)
    - upload original factory image via JBOOT http (IP: 192.168.123.254)

    Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
merged, Thanks !

**Comment by nbriggs** [comment]
You noted that only 3/5 of Ethernet ports work -- I see the same problem on an ESR600.  Turns out that it's picking the wrong PHY driver for the other two ports ("Generic PHY" instead of "Atheros AR8216!AR8236!AR8316").  You might check /sys/bus/mdio_bus/drivers/* to see what it's getting in your case.  I don't know what's going on, yet.

**Comment by CHKDSK88** [comment]
@nbriggs 

I have the same issue:

````
root@OpenWrt:/# ls /sys/bus/mdio_bus/drivers/Atheros\ AR8216!AR8236!AR8316/
bind         mdio-bus:00  mdio-bus:03  mdio-bus:04  uevent       unbind
root@OpenWrt:/# ls /sys/bus/mdio_bus/drivers/Generic\ PHY/
bind         mdio-bus:01  mdio-bus:02  uevent       unbind
````

Did You find solution?

**Comment by nbriggs** [comment]
No, no solution yet. Still working on it though. I also revised my opinion about the wrong PHY driver -- I think that the way things currently work the switch should only look like a single PHY, so only ethernet-phy0 should be declared, which will give you just the mdio-bus:00 entry, and it works just as well (or just as badly) as with all the individual PHYs exposed in the DTS definition.   I'm trying to get the U-Boot code from EnGenius that might give some clues.  The old firmware sources they sent weren't what they *actually* used, and besides they distribute the ar8327 driver as a loadable module blob so no useful information is present.

**Pull request closed without merging**
