### PR TITLE
realtek: switch to Kernel 5.10

### PR DESCRIPTION
**Pull request by aparcar**
CI build with artifacts: https://github.com/aparcar/openwrt/actions/runs/1292205319

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
@blogic do you have a comment on this?

**Comment by adschm** [comment]
realtek support for kernel 5.10 is quite new and has seen big changes recently. I think we should give it some time to mature.

**Comment by aparcar** [comment]
Fine with me, I'm mostly interested to know if @blogic already uses 5.10 and got some test results.

**Comment by dangowrt** [comment]
Imho this is good to go
```
root@zyxel-gs1900hp:~# uptime
 22:56:45 up 17 days,  9:43,  load average: 0.02, 0.02, 0.02
root@zyxel-gs1900hp:~# uname -a
Linux zyxel-gs1900hp 5.10.60 #0 Thu Aug 26 23:24:38 2021 mips GNU/Linux
```

**Comment by adschm** [comment]
Okay, I will merge it.

**Comment by bkobl** [comment]
Thanks a lot!

**Pull request closed without merging**
