### PR TITLE
arm-trusted-firmware-sunxi: Update to 2.10

### PR DESCRIPTION
**Pull request by 1715173329**
Runtime tested on NanoPi R1S H5 and Orange Pi Zero3.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Can you add or link to a change log?

**Comment by 1715173329** [comment]
> Can you add or link to a change log?

Sure, will do it tomorrow ;)

**Comment by 1715173329** [comment]
added the link to changelog.

**Comment by PolynomialDivision** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
