### PR TITLE
ramips: add Xiaomi Mi Router 3 support

### PR DESCRIPTION
**Pull request by shibajee**
Specification:
 - CPU: 580 MHz
 - Flash size: 128 MB NAND
 - RAM size: 128 MB DDR2
 - Wireless No1: SoC-integrated: MT7620A 2x2 MIMO 802.11b/g/n (2.4 GHz)
 - Wireless No2: On-board chip: MT7612E 2x2 MIMO 802.11a/n/ac (5.0 GHz)
 - Switch: MT7620 built-in 10/100 switch w/ vlan support
 - USB: 2.0 x1

Flash instructions:
 1. access ssh via https://wiki.openwrt.org/toh/xiaomi/mir3
 2. insert a usb stick (FAT/FAT32) with copied two firmware files (.bin)
      lede-ramips-mt7620-miwifi-3-squashfs-kernel1.bin
      lede-ramips-mt7620-miwifi-3-squashfs-rootfs0.bin
 3. in ssh:
      nvram set flag_last_success=1
      nvram set boot_wait=on
      nvram set uart_en=1
      nvram commit
      cd /extdisks/sda1
      mtd write lede-ramips-mt7620-miwifi-3-squashfs-kernel1.bin kernel1
      mtd write lede-ramips-mt7620-miwifi-3-squashfs-rootfs0.bin rootfs0
      reboot
 4. login to the router http://192.168.1.1/

How to revert back to stock from LEDE/Openwrt:
 1. insert usb stick (FAT/FAT32) with stock firmware renamed to miwifi.bin
 2. in ssh:
      fw_setenv flag_try_sys2_failed 1
      reboot
 3. shortly after rebooting it will start blinking "red"
 4. then just press the reset button for 1-2 sec until the "blue" blinking turns into "yellow"
 5. now wait 5-6 min to finish the stock flash (until the led turns into static "blue")
 6. login to the router http://192.168.31.1/

Change/s:
	add "writebufsize" on mt7620 nand driver

Signed-off-by: Shibajee Roy <ador250@protonmail.com>

### CODE REVIEW

**Comment by mkresin** [comment]
Isn't it a duplicate of  #597?

**Comment by shibajee** [comment]
not exactly, that one is based on a new subtarget "mt7620nand" whereas mine is mt7620..moreover my one is compatible for kernel 4.4 in lede-17.01 branch..I'm still sorting things out for kernel 4.14 on master.

**Comment by mkresin** [comment]
But isn't it the very same board?

Nevertheless, support for new boards need to be added to master first. You patch clear targets the 17.01 branch only.

**Comment by shibajee** [comment]
same device as advertise, yes.
same board, not sure because I didn't face those kernel size issues as he described in his pulls.

**Comment by shibajee** [comment]
Do I have to make a new PR for master ?
can u remove this pull ?

**Comment by 9000000** [comment]
Can you please download link fw mir3 to test yourself, thanks

**Comment by ysc3839** [comment]
@9000000 You need a firmware binary to test?

**Comment by 9000000** [comment]
Yes firmware .......sysupgrade.tar

**Comment by ysc3839** [comment]
@9000000 
[lede-ramips-mt7620-miwifi-3-squashfs-sysupgrade.tar.gz](https://github.com/openwrt/openwrt/files/1814246/lede-ramips-mt7620-miwifi-3-squashfs-sysupgrade.tar.gz)

**Comment by 9000000** [comment]
You give more instructions on the first install, and for more fw ... xxx.bin

I'm afraid the update will be broken

**Comment by ysc3839** [comment]
@9000000
You can flash a third-party bootloader. If it breaks just push reset button and plug on power, it will boot into recovery mode. Open 192.168.1.1 and you can upload a firmware.

There's one problem that this bootloader can only flash a "bundled" firmware, which means you have to manually construct a firmware.

**Comment by 9000000** [comment]
Thank you so much that you will wait to use more complete. I'm currently using fw of ptpt52

**Comment by ysc3839** [comment]
@9000000 What's your meaning? Do you need the bootloader?

**Comment by shibajee** [comment]
@ysc3839 is the third party bootloader from Prometheus script/padavan ??

**Comment by 9000000** [comment]
@ysc3839 yes i need a bootloader

**Comment by 9000000** [comment]
I need 2 files this 
mtd write lede-ramips-mt7620-miwifi-3-squashfs-kernel1.bin kernel1
mtd write lede-ramips-mt7620-miwifi-3-squashfs-rootfs0.bin rootfs0 

to try can you please let me

**Comment by ysc3839** [comment]
@shibajee No. It's from a Chinese team.
In fact, the one in Prometheus is modified from official bootloader, enables TTL UART by default. And do not have a web recovery UI.

**Comment by shibajee** [comment]
@ysc3839 can u share/link that chinese ( is that breed ?) bootloader ?

**Comment by ysc3839** [comment]
@shibajee It's not breed. It's pb-boot.
Since the official [website](http://downloads.pandorabox.com.cn/) is down. I upload it here.
Unzip to get the .img file. Then mtd write to Bootloader.
[pb-boot-xiaomi3-20170907-1a831a3.zip](https://github.com/openwrt/openwrt/files/1822357/pb-boot-xiaomi3-20170907-1a831a3.zip)

**Comment by Neustradamus** [comment]
Any news about the support of Xiaomi Mi Router 3?

There were 2 PRs:
- https://github.com/openwrt/openwrt/pull/597
- https://github.com/openwrt/openwrt/pull/764

**Pull request closed without merging**
