### PR TITLE
kconfig: double up dollar signs in strings

### PR DESCRIPTION
**Pull request by pprindeville**
Since kconfig reads and writes makefiles, reflect that dollars need
to be doubled up in make syntax so that they're not interpolated.

Example: if we have a `CONFIG_VAR` of type string that we want to have
the value of `"abc$def"` then it must be written to the file `.config`
file as:

`CONFIG_VAR="abc$$def"`

to avoid the `$d` from being interpolated as the` $(d)`.

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by pprindeville** [comment]
Note: This patch was submitted earlier today to <linux-kbuild@vger.kernel.org>

**Comment by pprindeville** [comment]
Required by PR #622.  As an example, if I generate a password manually using openssl:

```
% openssl passwd -1 -salt xyz  yourpass
$1$xyz$X5pC0RUqKE5mOgXcDDgFk0
% 
```

I can't paste `$1$xyz$X5pC0RUqKE5mOgXcDDgFk0` directly into `CONFIG_TARGET_ROOT_PASSWORD`... I have to double the dollar signs to be syntactically correct.

But I shouldn't expect the casual user of `make menuconfig` to know this.  Therefore, if he enters a string variable that includes dollar signs, they will get doubled up by this patch.

If those variables are then used in macro expansions elsewhere, they will need to be re-escaped via `$(subst $,$$,...)` but that's a separate issue.

**Comment by pprindeville** [comment]
@hauke Can you please assign a reviewer or tags?  I'm not sure why GitHub prevents the submitter from setting these...

**Comment by pprindeville** [comment]
This is not exhaustive, but it's not meant to be.  There may be other places where `CONFIG_*` variables are interpolated where they might also need protection.

**Comment by pprindeville** [comment]
@NeoRaider @KanjiMonster Since you both commented on https://github.com/lede-project/source/pull/1586 I was hoping you might have some feedback on this PR.  Thanks.

**Comment by pprindeville** [comment]
@pepe2k Hi Piotr, can you please label this PR?  Thanks

**Comment by ynezz** [comment]
@pprindeville Can you please update it to latest master, I would like to test it. Thanks.

**Comment by ynezz** [comment]
> Required by PR #622. As an example, if I generate a password manually using openssl:

That PR #622 was rejected long time ago.

> Note: This patch was submitted earlier today to linux-kbuild@vger.kernel.org as [PATCH v1 1/1] kconfig: double up dollar signs in strings

And it seems like it wasn't accepted there as well.

This PR seems pretty much dead to me, thus closing.

**Pull request closed without merging**
