### PR TITLE
ipq8074: update to 2.9.0.1 ath11k firmware

### PR DESCRIPTION
**Pull request by robimarko**
Current WLAN.HK.2.5.0.1 FW is quite old and buggy, but we had to hold off
from updating to 2.6.0.1 and 2.7.0.1 as they had compatibility regressions,
but now QCA finally released 2.9.0.1 FW which is working on all of the
boards.

So finally update IPQ8074 and QCN9074 FW to the latest
WLAN.HK.2.9.0.1-01385-QCAHKSWPL_SILICONZ-1 firmware.

Tested on Dynalink DL-WRX36 and Qnap 301W

### CODE REVIEW

**Comment by dick902** [comment]
Tested with Xiaomi AX9000 / Xiaomi AX3600 / Dynalink DL-WRX36. All working.
However, the "workaround board2.bin" still required for the Xiaomi AX9000's QCN9074 lower 5G to work.

**Review by dick902 — APPROVED** [review]

**Comment by sbarj** [comment]
Tested on Xiaomi AX3600. Working so far so good. Better memory consumption and quite stable.

**Review by ghost — COMMENTED** [review]
Tested on Xiaomi AX3600. Working so far so good. Better memory consumption and quite stable.

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Tested-by: Mireia Fernández Casals [meirin.f@gmail.com](mailto:meirin.f@gmail.com) # Xiaomi AX3600

**Comment by dimfishr** [comment]
ax3600 and ax6 - all is working and speed increased:
wifi-lan iperf3:
```
[SUM]   0.00-10.00  sec  1.18 GBytes  1.02 Gbits/sec                  sender
[SUM]   0.00-10.00  sec  1012 MBytes   849 Mbits/sec                  receiver
```

**Comment by Fil010** [comment]
`Tested-by: Francisco G Luna <frangonlun@gmail.com>` #Netgear WAX218

**Comment by AlexeiGHub** [comment]
On Redmi AX6 iw list :
`HE RX MCS and NSS set 160 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: MCS 0-11
                                4 streams: MCS 0-11
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE TX MCS and NSS set 160 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: MCS 0-11
                                4 streams: MCS 0-11
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported`
Does that mean it now supports 4 threads at 160MHz?  Was there 2 before?

**Comment by webzit** [comment]
Thanks robimarko for your hard work in getting IPQ8074 functioning.

Today remoteproc crashed on WLAN.HK.2.9.0.1, but to be fair it also crashed with WLAN.HK.2.5.0.1 from time to time.

AX3600 @ OpenWrt SNAPSHOT r22570-8ecf160c47 / LuCI Master git-23.093.56957-2145121

Is this FW related (or merge related)?

`Tue Apr 18 12:46:24 2023 kern.warn kernel: [119639.840518] ath11k c000000.wifi: failed to flush transmit queue, data pkts pending 2
Tue Apr 18 12:46:31 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff IEEE 802.11: associated (aid 1)
Tue Apr 18 12:46:31 2023 daemon.notice hostapd: phy1-ap0: AP-STA-CONNECTED aa:bb:cc:dd:ee:ff auth_alg=sae
Tue Apr 18 12:46:31 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff RADIUS: starting accounting session 7700911BF9B197BD
Tue Apr 18 12:46:31 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff WPA: pairwise key handshake completed (RSN)
Tue Apr 18 12:46:31 2023 daemon.notice hostapd: EAPOL-4WAY-HS-COMPLETED aa:bb:cc:dd:ee:ff
Tue Apr 18 12:46:47 2023 daemon.notice hostapd: phy1-ap0: AP-STA-DISCONNECTED aa:bb:cc:dd:ee:ff
Tue Apr 18 12:46:48 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff IEEE 802.11: authenticated
Tue Apr 18 12:46:48 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff IEEE 802.11: associated (aid 1)
Tue Apr 18 12:46:48 2023 daemon.notice hostapd: phy1-ap0: AP-STA-CONNECTED aa:bb:cc:dd:ee:ff auth_alg=open
Tue Apr 18 12:46:48 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff RADIUS: starting accounting session 3D9AA5617FF969E3
Tue Apr 18 12:46:48 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff WPA: pairwise key handshake completed (RSN)
Tue Apr 18 12:46:48 2023 daemon.notice hostapd: EAPOL-4WAY-HS-COMPLETED aa:bb:cc:dd:ee:ff
Tue Apr 18 12:46:55 2023 daemon.info hostapd: phy1-ap0: STA bb:bb:cc:dd:ee:ff IEEE 802.11: associated (aid 2)
Tue Apr 18 12:46:55 2023 daemon.notice hostapd: phy1-ap0: AP-STA-CONNECTED bb:bb:cc:dd:ee:ff auth_alg=sae
Tue Apr 18 12:46:55 2023 daemon.info hostapd: phy1-ap0: STA bb:bb:cc:dd:ee:ff RADIUS: starting accounting session C592A119A78B880C
Tue Apr 18 12:46:55 2023 daemon.info hostapd: phy1-ap0: STA bb:bb:cc:dd:ee:ff WPA: pairwise key handshake completed (RSN)
Tue Apr 18 12:46:55 2023 daemon.notice hostapd: EAPOL-4WAY-HS-COMPLETED bb:bb:cc:dd:ee:ff
Tue Apr 18 12:47:04 2023 daemon.info hostapd: phy1-ap0: STA cc:bb:cc:dd:ee:ff IEEE 802.11: associated (aid 3)
Tue Apr 18 12:47:04 2023 daemon.notice hostapd: phy1-ap0: AP-STA-CONNECTED cc:bb:cc:dd:ee:ff auth_alg=sae
Tue Apr 18 12:47:04 2023 daemon.info hostapd: phy1-ap0: STA cc:bb:cc:dd:ee:ff RADIUS: starting accounting session E4E71D46E3B05883
Tue Apr 18 12:47:04 2023 daemon.info hostapd: phy1-ap0: STA cc:bb:cc:dd:ee:ff WPA: pairwise key handshake completed (RSN)
Tue Apr 18 12:47:04 2023 daemon.notice hostapd: EAPOL-4WAY-HS-COMPLETED cc:bb:cc:dd:ee:ff
Tue Apr 18 12:51:33 2023 daemon.notice hostapd: phy1-ap0: AP-STA-DISCONNECTED cc:bb:cc:dd:ee:ff
Tue Apr 18 12:51:33 2023 daemon.info hostapd: phy1-ap0: STA cc:bb:cc:dd:ee:ff IEEE 802.11: disassociated due to inactivity
Tue Apr 18 12:51:34 2023 daemon.info hostapd: phy1-ap0: STA cc:bb:cc:dd:ee:ff IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Tue Apr 18 12:51:36 2023 daemon.notice hostapd: phy1-ap0: AP-STA-DISCONNECTED bb:bb:cc:dd:ee:ff
Tue Apr 18 12:51:36 2023 daemon.info hostapd: phy1-ap0: STA bb:bb:cc:dd:ee:ff IEEE 802.11: disassociated due to inactivity
Tue Apr 18 12:51:37 2023 daemon.info hostapd: phy1-ap0: STA bb:bb:cc:dd:ee:ff IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Tue Apr 18 13:01:00 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff IEEE 802.11: authenticated
Tue Apr 18 13:01:01 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff IEEE 802.11: associated (aid 1)
Tue Apr 18 13:01:01 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff RADIUS: starting accounting session 3D9AA5617FF969E3
Tue Apr 18 13:01:01 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff WPA: pairwise key handshake completed (RSN)
Tue Apr 18 13:01:01 2023 daemon.notice hostapd: EAPOL-4WAY-HS-COMPLETED aa:bb:cc:dd:ee:ff
Tue Apr 18 13:10:20 2023 daemon.notice hostapd: phy1-ap0: AP-STA-DISCONNECTED aa:bb:cc:dd:ee:ff
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] qcom-q6v5-wcss-pil cd00000.q6v5_wcss: fatal error received:
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] QC Image Version: QC_IMAGE_VERSION_STRING=WLAN.HK.2.9.0.1-01385-QCAHKSWPL_SILICONZ-1
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] Image Variant : IMAGE_VARIANT_STRING=8074.wlanfw.eval_v2Q
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316]
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] wal_peer_control.c:2870 Assertion is_graceful_to_handle failedparam0 :zero, param1 :zero, param2 :zero.
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] Thread ID      : 0x00000069  Thread name    : WLAN RT0  Process ID     : 0
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] Register:
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] SP : 0x4bfb9230
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] FP : 0x4bfb9238
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] PC : 0x4b1080c4
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] SSR : 0x00000008
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] BADVA : 0x00020000
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] LR : 0x4b107860
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316]
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] Stack Dump
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] from : 0x4bfb9230
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316] to   : 0x4bfb9aa8
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.692316]
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.743027] remoteproc remoteproc0: crash detected in cd00000.q6v5_wcss: type fatal error
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.765272] remoteproc remoteproc0: handling crash #1 in cd00000.q6v5_wcss
Tue Apr 18 13:10:20 2023 kern.err kernel: [121075.773331] remoteproc remoteproc0: recovering cd00000.q6v5_wcss
Tue Apr 18 13:10:20 2023 kern.info kernel: [121075.806158] remoteproc remoteproc0: stopped remote processor cd00000.q6v5_wcss
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.099652] ath11k c000000.wifi: failed to find peer aa:bb:cc:dd:ee:ff on vdev 1 after creation
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.099709] ath11k c000000.wifi: failed to find peer vdev_id 1 addr aa:bb:cc:dd:ee:ff in delete
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.107522] ath11k c000000.wifi: failed peer aa:bb:cc:dd:ee:ff delete vdev_id 1 fallback ret -22
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.116312] ath11k c000000.wifi: Failed to add peer: aa:bb:cc:dd:ee:ff for VDEV: 1
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.125065] ath11k c000000.wifi: Failed to add station: aa:bb:cc:dd:ee:ff for VDEV: 1
Tue Apr 18 13:10:21 2023 daemon.notice hostapd: phy1-ap1: STA aa:bb:cc:dd:ee:ff IEEE 802.11: Could not add STA to kernel driver
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.169966] ath11k c000000.wifi: failed to update rx tid queue, tid 0 (-108)
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.170001] ath11k c000000.wifi: failed to update reo for rx tid 0: -108
Tue Apr 18 13:10:21 2023 kern.info kernel: [121076.176081] phy1-ap0: HW problem - can not stop rx aggregation for aa:bb:cc:dd:ee:ff tid 0
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.209670] ath11k c000000.wifi: failed to send WMI_PEER_DELETE cmd
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.209699] ath11k c000000.wifi: failed to delete peer vdev_id 0 addr aa:bb:cc:dd:ee:ff ret -108
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.215091] ath11k c000000.wifi: Failed to delete peer: aa:bb:cc:dd:ee:ff for VDEV: 0
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.223934] ------------[ cut here ]------------
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.231661] WARNING: CPU: 0 PID: 1577 at sta_set_sinfo+0xbec/0xc44 [mac80211]
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.236440] Modules linked in: pppoe ppp_async nft_fib_inet nf_flow_table_ipv6 nf_flow_table_ipv4 nf_flow_table_inet ath11k_ahb ath11k ath10k_pci ath10k_core ath wireguard pppox ppp_generic nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject nft_redir nft_quota nft_objref nft_numgen nft_nat nft_masq nft_log nft_limit nft_hash nft_flow_offload nft_fib_ipv6 nft_fib_ipv4 nft_fib nft_ct nft_counter nft_chain_nat nf_tables nf_nat nf_flow_table nf_conntrack mac80211 libchacha20poly1305 iptable_mangle iptable_filter ipt_REJECT ipt_ECN ip_tables chacha_neon cfg80211 xt_time xt_tcpudp xt_tcpmss xt_statistic xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_ecn xt_dscp xt_comment xt_TCPMSS xt_LOG xt_HL xt_DSCP xt_CLASSIFY x_tables slhc sch_cake qrtr_smd qrtr qmi_helpers poly1305_neon ns nfnetlink nf_reject_ipv6 nf_reject_ipv4 nf_log_syslog nf_defrag_ipv6 nf_defrag_ipv4 libcurve25519_generic libcrc32c libchacha crc_ccitt compat sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.236701]  cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred act_gact ifb ip6_udp_tunnel udp_tunnel seqiv jitterentropy_rng drbg michael_mic kpp hmac cmac leds_gpio xhci_plat_hcd xhci_pci xhci_hcd dwc3 dwc3_qcom qca_nss_dp qca_ssdk gpio_button_hotplug aquantia hwmon crc32c_generic
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.335209] CPU: 0 PID: 1577 Comm: hostapd Not tainted 5.15.106 #0
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.357445] Hardware name: Xiaomi AX3600 (DT)
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.363605] pstate: 60400005 (nZCv daif +PAN -UAO -TCO -DIT -SSBS BTYPE=--)
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.368123] pc : sta_set_sinfo+0xbec/0xc44 [mac80211]
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.375324] lr : sta_set_sinfo+0xbe8/0xc44 [mac80211]
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.380271] sp : ffffffc00bdab840
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.385389] x29: ffffffc00bdab840 x28: ffffff8003f3e9c0 x27: ffffffc00bdabdd0
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.388783] x26: ffffff800206e880 x25: ffffffc008c260c0 x24: ffffffc000c0d000
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.395987] x23: ffffffc00bdaba38 x22: ffffff80060e4900 x21: ffffff800f665aa8
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.403194] x20: ffffff8005eb0880 x19: ffffff800f665000 x18: ffffffc008b27bc8
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.410398] x17: 6f662063653a3565 x16: 3a30353a38343a62 x15: 00000000000004f8
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.417602] x14: 00000000000001a8 x13: ffffffc00bdab378 x12: 0000000000000006
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.424807] x11: ffffffc008a395e0 x10: 0000000000000000 x9 : ffffffc017466000
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.432012] x8 : fffffffe003d1a08 x7 : fffffffe003d1a00 x6 : 0000000000000004
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.439216] x5 : ffffff801fe9f580 x4 : 0000000000000000 x3 : ffffff8003f3e9c0
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.446422] x2 : 0000000000000000 x1 : ffffff8003f3e9c0 x0 : 00000000ffffff94
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.453628] Call trace:
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.460824]  sta_set_sinfo+0xbec/0xc44 [mac80211]
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.463518]  sta_info_destroy_addr_bss+0x50/0x7c [mac80211]
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.468121]  ieee80211_color_change_finish+0x1d88/0x2040 [mac80211]
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.473938]  cfg80211_check_station_change+0x1408/0x4970 [cfg80211]
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.480275]  genl_family_rcv_msg_doit+0xb8/0x11c
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.486609]  genl_rcv_msg+0xd4/0x1cc
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.491207]  netlink_rcv_skb+0x5c/0x130
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.494852]  genl_rcv+0x38/0x50
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.498845]  netlink_unicast+0x1f8/0x2f4
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.502057]  netlink_sendmsg+0x1a0/0x3dc
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.505965]  ____sys_sendmsg+0x288/0x2c0
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.509957]  ___sys_sendmsg+0x84/0xf0
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.513949]  __sys_sendmsg+0x48/0xb0
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.517596]  __arm64_sys_sendmsg+0x24/0x30
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.521328]  invoke_syscall.constprop.0+0x5c/0x104
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.525322]  do_el0_svc+0x6c/0x15c
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.530181]  el0_svc+0x18/0x54
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.533653]  el0t_64_sync_handler+0xe8/0x114
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.536782]  el0t_64_sync+0x184/0x188
Tue Apr 18 13:10:21 2023 kern.warn kernel: [121076.541294] ---[ end trace dcbb648112ca5d2c ]---
Tue Apr 18 13:10:25 2023 daemon.info hostapd: phy1-ap0: STA aa:bb:cc:dd:ee:ff IEEE 802.11: deauthenticated due to local deauth request
Tue Apr 18 13:10:26 2023 kern.err kernel: [121081.119758] qcom-q6v5-wcss-pil cd00000.q6v5_wcss: start timed out
Tue Apr 18 13:10:26 2023 kern.err kernel: [121081.119803] remoteproc remoteproc0: can't start rproc cd00000.q6v5_wcss: -110`

**Review by ghost — COMMENTED** [review]
Ups, wrong PR xd

**Comment by sppmasterspp** [comment]
I have found issues with version 2.9.0.1.
All is described on the [forum here](https://forum.openwrt.org/t/ath11k-possible-firmware-bug-traffic-interruptions-when-a-client-disconnects-from-wlan/167400).

**Comment by sppmasterspp** [comment]
> Current WLAN.HK.2.5.0.1 FW is quite old and buggy, but we had to hold off from updating to 2.6.0.1 and 2.7.0.1 as they had compatibility regressions, but now QCA finally released 2.9.0.1 FW which is working on all of the boards.
> 
> So finally update IPQ8074 and QCN9074 FW to the latest WLAN.HK.2.9.0.1-01385-QCAHKSWPL_SILICONZ-1 firmware.
> 
> Tested on Dynalink DL-WRX36 and Qnap 301W

Is it possible to check for the issues mentioned in the above post. Just to confirm them if they are present.

**Pull request merged**
