### PR TITLE
archs38: enable 5.15 testing kernel

### PR DESCRIPTION
**Pull request by PolynomialDivision**
**Only compile tested.**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@EvgeniiDidin @abrodkin, could you test?

**Comment by Ansuel** [comment]
@EvgeniiDidin can you provide tested-by tag? it would be good as it seems a not so common target so it would be good to keep you as a source for testing changes

**Comment by EvgeniiDidin** [comment]
@PolynomialDivision, could you please add this line to the commit message:
``` Tested-by: Evgeniy Didin <didin@synopsys.com> ``` ?
Thanks in advance!

**Comment by PolynomialDivision** [comment]
Thanks! @Ansuel this is ready to be merged! :)

**Pull request merged**
