### PR TITLE
cmake: include/cmake.mk needs modifying to allow out of source tree builds

### PR DESCRIPTION
**Pull request by hojuruku**
Some packages need out of source tree building with cmake, for example
when building kernel modules.
See an example here:
https://sourceforge.net/p/accel-ppp/code/ci/master/tree/README

This adds a new variable that can be used in Makefiles $(CMAKE_BINARY_DIR)

Signed-off-by: Luke McKee hojuruku@gmail.com

@nbd168 agrees, patching the include is the only way to go.

### CODE REVIEW

**Comment by nbd168** [comment]
should be CMAKE_BINARY_SUBDIR instead, relative to PKG_BUILD_DIR

**Comment by hojuruku** [comment]
<hojuruku> nbd let the package maintainers decide how to invoke cmake. the patch I sent is good? everything behaves the same if the package maintainers doesn't use the new variable. 
<nbd> hojuruku: i would like the patch to be changed to define a subdir instead of overriding the main dir
<nbd> because regardless of what some package maintainers are going to think, a configuration where you move the build dir outside of PKG_BUILD_DIR is not going to be supported
<nbd> so the patch shouldn't make it look like this is a thing
<hojuruku> don't some other packages already do it? with differences between PKG_SOURCE_DIR and PKG_BUILD_DIR
<nbd> if you move the source and build stuff outside of PKG_BUILD_DIR, it breaks proper cleaning of source trees and probably has some other negative consequences as well
<nbd> i'm not aware of any packages that do it
<hojuruku> so you want it to cd $PKG_BUILD_DIR/$CMAKE_BINARY_DIR
<hojuruku> well you have QA on all your package Makefiles so it's a bit of a misnomer.  Just leave it all up to the package maintainer, they want to build a few different times in a few different directories for different dependencies or something.
<nbd> QA is often not very strict, so it's important to me that the system encourages consistency
<hojuruku> Build files have been written to: /usr/src/openwrt/build_dir/target-mips_74kc+dsp2_musl-1.1.14/accel-ppp-1.11.0/build YAY!
<hojuruku> Entering directory '/usr/src/openwrt/build_dir/target-mips_74kc+dsp2_musl-1.1.14/accel-ppp-1.11.0' make[3]: *** No targets specified and no makefile found.  Stop. DOH!
<hojuruku> so you want to REMOVE the existing variable CMAKE_SOURCE_DIR - hard code it to .. (which confuses idiots reading build logs) and make the new variable I put in RELATIVE? I hear what your saying and why but couldn't that break existing packages, - that's why I went against that approach
<hojuruku> nbd put your comments on github - cut and paste :P it's a valid point, but I chose to do it the way I did because it gels more with the way it's currently set up.
<hojuruku> how do I fix my DOH! Create a dummy makefile in the root directory including the subdir OR overide with a define?

I don't disagree with nbd, but his suggestion requires implies removing $(CMAKE_SOURCE_DIR) from include/cmake.mk and replacing it with ".." as well as his suggested change.
I don't know who named that variable, it should have been called $(CMAKE_HOME_DIRECTORY) to be the same as CMAKE uses internally. 

Is that variable being used in any other packages?

Also before trying this patch, I didn't have any luck with this:
>[CMake] Invoking CMakle outside of the build/source dir.
>
>Bill Hoffman bill.hoffman at kitware.com 
>Mon Jun 6 11:44:35 EDT 2011
>Previous message: [CMake] Invoking CMakle outside of the build/source dir.
>Next message: [CMake] Invoking CMakle outside of the build/source dir.
>Messages sorted by: [ date ] [ thread ] [ subject ] [ author ]
>On 6/6/2011 11:33 AM, Yuri Timenkov wrote:
>> I guess there are cases when you can't do this.
>> For example, on Windows you can't simply call "cd -" or you may have
>> other kind of script than sh one (for example ant).
>>
>> Also both source dir and binary dir may be relative to current
>> directory, therefore you don't know neither absolute nor relative to
>> bindir source path. And determining it may be quite cumbersome (again,
>> in ant this can be done using property and property names are global and
>> they're evaluated only once per script, so you can't easily wrap cmake
>> call into macro).
>
>There is sort of a backdoor...
>
>You can use -H and -B on the command line like this:
>cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

This is what cmake does inside makefiles.  It has been this way but 
un-documented for some time.  I suppose we could just document it.  I 
don't see a reason to stop support for it some day...

-Bill

**Comment by hojuruku** [comment]
I didn't check all the package feeds but I found this.  The Makefile suggests it doesn't do any out of source tree building. 
```
lmc@hojuruku /usr/src/openwrt/feeds/packages $ grep -r CMAKE_SOURCE_DIR *
libs/libftdi/patches/101-fix-cmake-version-packagekit.patch:-SET(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}")
libs/libftdi/patches/101-fix-cmake-version-packagekit.patch:+set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}")
libs/libftdi/patches/101-fix-cmake-version-packagekit.patch:+set(top_srcdir ${CMAKE_SOURCE_DIR})
libs/libftdi/patches/101-fix-cmake-version-packagekit.patch:-   set(top_srcdir ${CMAKE_SOURCE_DIR})
libs/libftdi/patches/101-fix-cmake-version-packagekit.patch:    set(DOXY_DIR "${CMAKE_SOURCE_DIR}/doc")
```

**Comment by hojuruku** [comment]
@nbd168 You like the compromise?

**Comment by hojuruku** [comment]
@nbd168 I'll need this ETA 3-7 days for a new package I want to do a PR on. CC @KanjiMonster 

The new package will use the "compromise" of invoking CMAKE, however sometimes package maintainers will need to call cake for a specific directory, for example when compiling a kernel module or plugin etc and stuff like that.

**Comment by hojuruku** [comment]
New pull request procedure!
Lede re-works the pull request off github and send's it back to openwrt via @wigyori merges. Who knew!

<hojuruku> nbd: without defining anything how did it pass openwrt continuous integration eh if you had to define that variable in order to use cmake.mk? All those other cmake.mk using packages in openwrt had no problem. If what you are saying is true the patch would have failed CI.
<hojuruku> you guys are just dialing a tech argument for fun. We are talking about setting 2 variables in god damn make file. nbd's suggestion only breaks cmake.mk again for the same reason it was broken in the first place
<hojuruku> KanjiMonster: i've merged stuff before. There is nothing wrong wtih that commit-log except the SPACING you say.
<hojuruku> <hojuruku> nbd: make your suggestion , and give me an alternative patch, that allows the package maintainer to invoke cmake in ANY subdirectory reading ANY source location that is under $(PKG_BUILD_ROOT) - good luck because if you don't that as far as i'm concerned cmake.mk is still broken

<nbd> funny how you claim that my stuff breaks cmake.mk again without actually having seen it
<hojuruku> sorry that's the repost i wanted to say ^^^^ so nbd you are saying those who are using CMAKE must not be able to invoke cmake in any directory under PKG_BUILD_ROOT - that package maintainers can only run cmake in ither PKG_BUILD_DIR root or a single subdir one time only. 
<hojuruku> look you can fix it your way and then i'll add a pull request against that saying how it's broken. It's just being argumentive over gay rights not being able to separate your tech stuff from gay sex with young boys politics. 
(i.e. being banned from #lede-dev for talking about my father's human rights abuse and legal persecution for the crime of criticizing published gay marriage activists (http://web.csulb.edu/~d49er/spring99/v6n88-samesex.html http://archive.org/details/TwoDadsAreBetterThanOne) raping Russian infant drake newton. JOW / Lede-dev instant bans because they are gay and say it's wrong to oppose pedophilia.
It's literally a crime to link to this youtube video under case law
https://www.youtube.com/watch?v=UHrR9MY6GdM
(search abcplugspedos in austlii.edu.au case law database)
http://www.truthnews.com.au/web/radio/story/cultural_marxism_101 (2nd hour)
http://www.renegadebroadcasting.com/twos-company-threes-allowed-luke-mckee-4-7-16/
https://www.caselaw.nsw.gov.au/decision/55b9a3efe4b0f1d031deb3b1
http://bernardgaynor.com.au/ncat-deputy-president-has-questions-to-answer/
<nbd> https://git.lede-project.org/?p=lede/nbd/staging.git;a=commit;h=554b99c803f30bc7a86c9b6284f50d4a26c59d9c - with squashed commits and a trimmed down commit log
* hoijui has quit (Ping timeout: 276 seconds)
<hojuruku> so you make a new pull request and i'll close mine.
<nbd> nah, i'll just push my stuff to lede after some testing. openwrt merges from there anyway
<nbd> i don't have a github fork of openwrt and i find creating github pull requests somewhat cumbersome
<hojuruku> i'll just cut and paste into git hub thanks

**Comment by hojuruku** [comment]
Meanwhile I don't care as long as it gets done. I'll have my accel-ppp package that needs this ready in a few days.
Draft here: http://pastebin.ca/3668350

<hojuruku> i don't care as long as something that allows a basic build binary dir works, when another package maintainer thinks it's broken you can go deal with them.

**Pull request closed without merging**
