### PR TITLE
base-files: add sleep wait after sysupgrade

### PR DESCRIPTION
**Pull request by ptpt52**
for some unknown reason sysupgrade with nand_upgrade_ubinized is likely lost config, this workaroud just to resolve it.

### CODE REVIEW

**Comment by mpratt14** [comment]
is the problem `reboot -f` ?

maybe just `reboot` ?

**Comment by Ansuel** [comment]
@ptpt52 mhhh NACK in the current state. 30s IS A LOT OF TIMES.

Does sync fix this?

**Comment by Ansuel** [comment]
Or trying to ubi detach the partition?

**Comment by mpratt14** [comment]
> Does sync fix this?

sounds like it would, there are many examples of sync before umount

one of them:

https://github.com/openwrt/openwrt/blob/master/target/linux/ipq806x/base-files/lib/upgrade/zyxel.sh#L77

**Comment by Ansuel** [comment]
@mpratt14 yep as I feared... umount doesn't sync before doing umount... this cause the lost of the sysupgrade tar and on next boot the config gets reset...  terrifying bug

**Comment by Ansuel** [comment]
@ptpt52 the reason you config are getting lost is because the tar is not getting saved... adding sleep just gives time to the data to be actually written.

you need to put sync before umount -a

**Comment by ptpt52** [comment]
I try every possible but no help:
```
diff --git a/package/base-files/files/lib/upgrade/nand.sh b/package/base-files/files/lib/upgrade/nand.sh
index 5e8fb93e87..570417e92d 100644
--- a/package/base-files/files/lib/upgrade/nand.sh
+++ b/package/base-files/files/lib/upgrade/nand.sh
@@ -237,8 +237,9 @@ nand_do_upgrade_success() {
        if { [ ! -f "$conf_tar" ] || nand_restore_config "$conf_tar"; } && sync; then
                echo "sysupgrade successful"
        fi
+       sync
        umount -a
-       reboot -f
+       reboot
 }
 
 # Flash the UBI image to MTD partition
```

only add sleep wait help.

any idea?
@mpratt14  @Ansuel

**Comment by Ansuel** [comment]
https://github.com/openwrt/openwrt/blob/14764950670f9ad8fb8835fa3b4bd8713dda767d/package/base-files/files/lib/upgrade/nand.sh#L258 

Try add 
```
local mtdnum="$(find_mtd_index "$CI_UBIPART")"
ubidetach -p "${mtddev}" 
```
after ubiattach

**Comment by ptpt52** [comment]
> https://github.com/openwrt/openwrt/blob/14764950670f9ad8fb8835fa3b4bd8713dda767d/package/base-files/files/lib/upgrade/nand.sh#L258
> 
> Try add
> 
> ```
> local mtdnum="$(find_mtd_index "$CI_UBIPART")"
> ubidetach -p "${mtddev}" 
> ```
> 
> after ubiattach

what?
you mean this?
```diff
diff --git a/package/base-files/files/lib/upgrade/nand.sh b/package/base-files/files/lib/upgrade/nand.sh
index 56a1478b99..472a00aa03 100644
--- a/package/base-files/files/lib/upgrade/nand.sh
+++ b/package/base-files/files/lib/upgrade/nand.sh
@@ -238,7 +238,9 @@ nand_do_upgrade_success() {
                echo "sysupgrade successful"
        fi
        umount -a
-       echo "wait 30s to reboot" && sleep 30
+       local mtdnum="$(find_mtd_index "$CI_UBIPART")"
+       local mtddev="/dev/mtd${mtdnum}"
+       ubidetach -p "${mtddev}"
        reboot -f
 }
 
```
I try this above but no help.

OR

you mean this?
```diff
@@ -258,6 +260,12 @@ nand_upgrade_ubinized() {
        ubiformat "${mtddev}" -y -f "${ubi_file}"
        ubiattach -p "${mtddev}"
 
+       mtdnum="$(find_mtd_index "$CI_UBIPART")"
+       local mtddev="/dev/mtd${mtdnum}"
+       ubidetach -p "${mtddev}"
+
+       ubiattach -p "${mtddev}"
+
        nand_do_upgrade_success
 }
```

**Comment by Ansuel** [comment]
> you mean this?
> 
> ```diff
> diff --git a/package/base-files/files/lib/upgrade/nand.sh b/package/base-files/files/lib/upgrade/nand.sh
> index 56a1478b99..472a00aa03 100644
> --- a/package/base-files/files/lib/upgrade/nand.sh
> +++ b/package/base-files/files/lib/upgrade/nand.sh
> @@ -238,7 +238,9 @@ nand_do_upgrade_success() {
>                 echo "sysupgrade successful"
>         fi
>         umount -a
> -       echo "wait 30s to reboot" && sleep 30
> +       local mtdnum="$(find_mtd_index "$CI_UBIPART")"
> +       local mtddev="/dev/mtd${mtdnum}"
> +       ubidetach -p "${mtddev}"
>         reboot -f
>  }
>  
> ```
> 
> I try this above but no help.

this is the correct one but everything BEFORE umount -a

**Comment by ptpt52** [comment]
> > you mean this?
> > ```diff
> > diff --git a/package/base-files/files/lib/upgrade/nand.sh b/package/base-files/files/lib/upgrade/nand.sh
> > index 56a1478b99..472a00aa03 100644
> > --- a/package/base-files/files/lib/upgrade/nand.sh
> > +++ b/package/base-files/files/lib/upgrade/nand.sh
> > @@ -238,7 +238,9 @@ nand_do_upgrade_success() {
> >                 echo "sysupgrade successful"
> >         fi
> >         umount -a
> > -       echo "wait 30s to reboot" && sleep 30
> > +       local mtdnum="$(find_mtd_index "$CI_UBIPART")"
> > +       local mtddev="/dev/mtd${mtdnum}"
> > +       ubidetach -p "${mtddev}"
> >         reboot -f
> >  }
> >  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I try this above but no help.
> 
> this is the correct one but everything BEFORE umount -a

try it out. but still not work.

**Comment by ptpt52** [comment]
```
--- a/package/base-files/files/lib/upgrade/nand.sh
+++ b/package/base-files/files/lib/upgrade/nand.sh
@@ -237,8 +237,11 @@ nand_do_upgrade_success() {
        if { [ ! -f "$conf_tar" ] || nand_restore_config "$conf_tar"; } && sync; then
                echo "sysupgrade successful"
        fi
+       local mtdnum="$(find_mtd_index "$CI_UBIPART")"
+       local mtddev="/dev/mtd${mtdnum}"
+       ubidetach -p "${mtddev}"
+       sync
        umount -a
-       echo "wait 30s to reboot" && sleep 30
        reboot -f
 }
```
nothing help.

**Comment by ptpt52** [comment]
maybe something related to kernel or sync system call API?

**Comment by Ansuel** [comment]
Can't be that you are the only one affected by this problem. Are we aware of other user of such function? Other device?

**Comment by ptpt52** [comment]
I'm just doing targeted testing, in fact I don't need this nand_upgrade_ubinized upgrade method at the moment

for any device with `ubi` mtd part as ubi device, contain kernel + rootfs + rootfs_data volumes
could do that test.

just use the factory.bin = append-ubi file to do sysupgrade -F

**Comment by DragonBluep** [comment]
Related to this? #9828

**Comment by mpratt14** [comment]
just to be clear, you are doing sysupgrade to the same version or a different kernel?

**Comment by ptpt52** [comment]
> just to be clear, you are doing sysupgrade to the same version or a different kernel?

the same version, the same kernel.

**Comment by 981213** [comment]
NACK. 30s is too long for a workaround applied unconditionally to all devices.
BTW, I believe the use of nand_upgrade_ubinized is discouraged because it always write to the blocks at the begining without considering wear-leveling.

**Pull request closed without merging**
