### PR TITLE
prereq: SetupHostCommand: fix wrong check result

### PR DESCRIPTION
**Pull request by mcprat**
something discovered while testing with CI

and

handling side effects of #12617

### CODE REVIEW

**Comment by mpratt14** [comment]
ping @Ansuel @ynezz @ldir-EDB0 @neheb

**Review by neheb — APPROVED** [review]

**Review by ynezz — CHANGES_REQUESTED** [review]
Thank you for looking into this, but lets [fix it properly](https://github.com/openwrt/openwrt/pull/12617#issuecomment-1559145440).

**Comment by mpratt14** [comment]
none of this is my work

I would appreciate it if you simply closed my PR if you didn't like it, instead of hijacking it to more easily push your own commits...

**Comment by mpratt14** [comment]
I don't have a problem with your workaround so that other PRs are not affected right now, except that it's not labeled as a workaround

please restore my branch and we can take our time with a final solution:

a. remove the check for install completely 

or

b. check for ginstall first

or

c. delete /usr/bin/install on the CI as it maybe conflicts with newly installed GNU install (keep in mind we use command -v)

or

d. rewrite the order of paths in PATH so that
/usr/local/opt/coreutils/bin
is first

then we can safely put back the `exit 1`

**Comment by ynezz** [comment]
> I would appreciate it if you simply closed my PR if you didn't like it, instead of hijacking it to more easily push your own commits...

image

Ok, noted. This GH feature is probably misleading.

> please restore my branch and we can take our time with a final solution:

I've tried, not allowed now:

```
$ git push -f mpratt14 HEAD:ci-path-install 
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:mpratt14/openwrt
 ! [remote rejected]           HEAD -> ci-path-install (permission denied)
error: failed to push some refs to 'github.com:mpratt14/openwrt'
```

**Comment by mpratt14** [comment]
I understand your powers, I just think it was unnecessary...

if it turns out that the PR is bad, replacing it removes the history. IMO bad examples are just as useful as good examples

**Comment by mpratt14** [comment]
does it have to be reopened before you can push? or just totally stuck...

**Comment by ynezz** [comment]
> I understand your powers, I just think it was unnecessary...

BTW it's you who decides https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

> if it turns out that the PR is bad, replacing it removes the history.

image

The history is still there https://github.com/openwrt/openwrt/compare/4047f7b4f725c3f2bd4e90a1eb0af97f7c6cd93a..40d07372415239691cd3681ee6d6051b21fc3075

> does it have to be reopened before you can push? or just totally stuck...

image

I'm not able to re-open, I assume, that once the changes are merged, then GH locks the PR somehow.

**Comment by mpratt14** [comment]
I used to uncheck the box because I feared when I run `git push --mirror` that could mess something up if I somehow do it at the same time a member does something to my branch, or right after, but then when a member wants to merge my PR using the fancy script they have to ask me to check it. 

So I'd rather be nice and leave it checked and trust you all to handle it appropriately so my PR says "merged" instead of "closed" and we don't have to communicate about that option, and I'd like to keep trusting that it will be appropriate edits and keep the box checked to make it easier for you...

sure, I have my commits, but when someone opens this PR they won't see what I wanted to do right away, they would have to hunt for it...

anyway, tell me which option as a final solution we like better and I will work on it

**Comment by ynezz** [comment]
> anyway, tell me which option as a final solution we like better and I will work on it

Its chicken egg problem, without knowing the root of the problem, I'm not able to decide, sorry.

**Pull request closed without merging**
