### PR TITLE
add support for witi board nand version

### PR DESCRIPTION
**Pull request by fkpwolf**
WiTi is a MT7621 SOC board. It support SPI(default) and NAND flash. This patch add support for nand version.

### CODE REVIEW

**Comment by mkresin** [comment]
Instead of duplicating the WITI.dts, make a device tree include file (WITI.dtsi) from the existing  WITI.dts. This file should included all shared parts.

Include the WITI.dtsi in WITI-SPI.dts/WITI-NAND.dts and add the differences. Have a look at target/linux/ramips/dts/VOCORE* for examples.

**Comment by fkpwolf** [comment]
@mkresin code updated by your comments.

**Comment by mkresin** [comment]
I recommend to not merge this PR.

The WiTi does not have a NAND chip by default. It has empty solder pads to which a NAND chip can be soldered. Depending on which NAND chip is chosen, the partition sizes and Blocksize/Pagesize might be different. Basically everything regarding the NAND chip is custom.

I don't see a benefit of adding a configuration for one specific NAND chip (in regards of size).

**Comment by fkpwolf** [comment]
The patch didn't have any code for a **specific** NAND chip.

MTK's uboot support several NAND chips in it's code. It's boot configuration is to solder different PIN in board.

mt7621-boot

**Comment by mkresin** [comment]
Seriously?

Your partition layout requires a NAND chip of at least 128MB. If the NAND chip has a capacity of more than 128MB the additional space is unused. If the NAND chip is smaller, it doesn't work.

>```
>define Device/witi-nand
>     DTS := WITI-NAND
>     BLOCKSIZE := 128KiB
>     PAGESIZE := 2048
>```

vs.

- boot from ROM (NAND page 2k ...)
- boot from ROM (NAND page 4k ...)

from the datasheet screenshot.

**Comment by fkpwolf** [comment]
Sorry. I copy that part from another dts. I removed it and device still work. So BLOCKSIZE  and PAGESIZE are unused for MT7621? I guess when flash firmware, MTK uboot will identify nand chip and use a specific layout.

**Pull request closed without merging**
