### PR TITLE
package/utils/util-linux: Update to 2.35.1

### PR DESCRIPTION
**Pull request by diizzyy**
Update util-linux to 2.35.1

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested: ramips, mvebu
Runtime tested: mvebu Linksys WRT3200ACM

**Comment by neheb** [comment]
I am curious if 100-use_urandom.patch is needed since urngd was added. ping @ynezz

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by ynezz** [comment]
> I am curious if 100-use_urandom.patch is needed 

Unfortunately, this code is being called early during init to create the overlay filesystem, on some devices leaving little chance for a successful random pool init. True randomness is not that important here...

**Pull request closed without merging**
