### PR TITLE
nand sysupgrade improvements

### PR DESCRIPTION
**Pull request by Lanchon**
@dangowrt
hi Dan, as promised here is the expected fix for ubinized sysupgrade and other fixes.
i think at this point i can start working on safer upgrades.

please excuse the delay, i've been up to the neck with other stuff.

i got a new device (a much more common Askey RT4230W REV6 / RAC2V1K) to test stuff on because it doesn't look like my RAC2V1A port will be merging anytime soon.

regarding the PR, both commits are tested.

the first commit was tested in kernel-in-UBI mode, but the changes are simple enough so as to not need further testing IMHO. it basically deals with error handling.

i wanted to change the code to `set -euo pipefail`, but it calls library functions expecting the current environment, and touching those could cause side effects elsewhere, requiring an unacceptable explosion of testing. so many errors still won't be caught, which is not the end of the world since we are not doing any effort to recover (say, by at least starting dropbear).

the second commit was also tested (with an ubinized image i got from my device) and it works. but... it also worked on my device before the fix (me thinks). this code might fix some issues for some devices but possibly not all issues for all devices. you may want to test it in your failing device... or not. after all you don't care much for ubinized.

but i like ubinized sysupgrade. though it can't be made safe, it provides a way to restore a complete backup of everything (system, installed packages, and extra user files included) for kernel-in-ubi devices. (you have to NOT check the restore config checkbox for this to work.) and the UI for taking backups is already there: "save mtdblock contents" for ubi partition.

### CODE REVIEW

**Comment by Lanchon** [comment]
i added a 3rd commit that enables support for gzipped versions of all previously supported files.

back when firmware was compressed kernel + squashfs, tar was good enough. now we have ubifs images, ubinized images, and possibly uncompressed images inside the tar. a ubinized backup of my router is 400+ MB, but when compressed is <10 MB.

this also enables cases where uncompressed backup images may not fit in ram.

i tested tar, tar.gz, ubinized and ubinized.gz. it might be worth it to test ubifs or FIT before merging this one, although code is simple enough.

note that gzipping a regular squashfs sysupgrade image will hide its metadata and signature from the UI, but despite the warning, upgrades still work.

i need to write commit message for this but i dont have time now.

**Comment by Lanchon** [comment]
the 4th commit adds integrity checking where possible.

i've tested tar/tar.gz unbinized/ubinized.gz upgrades.

not tested: ubifs and fit upgrades,

**Comment by Lanchon** [comment]
@dangowrt you can test fit or ubifs if you want
but next comes safe upgrades at last, so you could deffer testing
...as long as no one else is modifying these files :)

**Comment by Ansuel** [comment]
@Lanchon just notice this! Didn't checked this in a good way but I notice you use -a and -o shell condition. Pls replace them with [] && [] and [] || [] to mute some shellcheck warning. (ideally we should not have shellcheck warning)

**Comment by ptpt52** [comment]
@Lanchon  @Ansuel 
thanks for your PR, but I test this PR 
`nand_upgrade_ubinized` upgrade cannot even success. it fails on sysupgrade the `ubi` file

but I cannot see what is the error log, I now cannot access to the TTL.

**Comment by Lanchon** [comment]
@Ansuel
hi! this is soooooo old! lol

let me provide context. i wanted to make sysupgrades safe on devices with kernel and rootfs in ubi. this would mean that interrupting the upgrade at any point in any way would not brick the device. this would be done without reserving any flash as long as (the sizes of) overlay > kernel+rootfs. sysupgrades would still not be atomic as configuration would be lost on interruption. (this could be fixed too, but would require reserving half the flash for upgrades, A/B style.)

so when i got to it  i found the nand code so dirty that i needed to clean up everything before starting. current code is a collage of bits of code by different authors and is not really maintainable.

so i was cleaning up and rewriting sensitive stuff but this requires testing on a bunch of devices and no one did the testing. and so this PR just hangs there.

> replace them with [] && [] and [] || [] 

i believe these idioms unnecessarily spawn sub sheslls.

**Comment by Lanchon** [comment]
so in the end i never got to safe sysupgrades which is what i wanted to do.

ubinized upgrades did not work before this patch (dont remember why now) but were fixed by these commits, at least on my device and others.

so question: is anybody willing to test what i couldnt test and then merge?

only if so i can go through the commits of the last 5 months and update this as needed.

**Comment by Lanchon** [comment]
merged by @dangowrt

**Pull request closed without merging**
