### PR TITLE
ath79: support ZTE MF286R built-in modem

### PR DESCRIPTION
**Pull request by Leo-PL**
This series completes the support of ZTE MF286R router added in commit 7ac8da00609f42b8aba74b7efc6b0d055b7cef3e.

First patch contains required kernel fixes to rndis_host driver, which is the primary network interface of the modem, without which the modem would set wrong MAC on outgoing traffic towards the router over RNDIS interface. The patches were just sent to LKML for upstreaming

Second patch allows NCM protocol handler to use explicitly configure network interface name - which is useful if a modem exposes multilple network interfaces, as is the case with some (not all) variants of MF286R's modem, which expose ECM and RNDIS at the same time.

Third patch fixes error in NCM protocol handler in modems exposing >1 interface, by selecting the network interface bound to the lowest USB interface of the device. 

Fourth patch allows to detect network ports on modems exposing ttyACM ports, which have a minor diffference in their sysfs semantics.

Finally, fifth patch adds the requisite AT commands to configure the MF286R internal modem and establish the connection. 

With that series, the support for MF286R is on par with other devices of MF286 series, and thus it probably deserves to be cherry-picked to 22.03 release. 

CC @obsy @chunkeey @bmork @kristrev

### CODE REVIEW

**Comment by obsy** [comment]
Tested by: Cezary Jackiewicz <cezary@eko.one.pl>

**Comment by Leo-PL** [comment]
Thread at LKML: https://marc.info/?l=linux-netdev&m=164929082624623&w=2

**Comment by Leo-PL** [comment]
Set as draft for now, until I send V2 patchset to LKML - it needs fixing.

**Review by hauke — APPROVED** [review]
Looks good to me. 
Please add the patches also for kernel 5.15.
When the patches are accepted by the Linux maintainers you can move them to the backports directory.

**Comment by Leo-PL** [comment]
Sent V2 (and had to send V3 immediately) - this should be now good to go, hopefully. In the meantime, another modem flavour was discovered, which uses the same commands, but identifies manufacturer as `"marvell"` instead of ZTE - this is also included.

**Comment by Leo-PL** [comment]
Patches landed in net-next: https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=caf968b483351d8825e68b06d77de5eb618aeb64

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in c99013e242682a71051619806f9cc4f4e51a58fa, a67629bbe25ef3d0e159db1e0c6ca81affd06898, b2940bb8b2878ce193f2edaee3e7d4c44f4a2065, ed7957810c0aee04943559be9b0ed23431ee0654 and e02fb42c53bad5dd36726c6ef5a46bfe31d2e400.

**Comment by Leo-PL** [comment]
@hauke I'd like to backport these patches to 22.03 as well, to ensure support for MF286R is complete in that release as well. Should I provide the patches, or is it easier for you to just cherry-pick them from master?

**Comment by hauke** [comment]
cherry-pick is preferred, please end a mail to the mailing list with the commit hashes you would like to get from master  into 22.03.

**Comment by braveheartleo** [comment]
Hi @Leo-PL,

Great work on bringing this device into the OpenWRT mainline. I have been following your progress closely, and now I have a ZTE MF286RA rebranded by an ISP. I have successfully flashed ``https://downloads.openwrt.org/snapshots/targets/ath79/nand/openwrt-ath79-nand-zte_mf286r-squashfs-sysupgrade.bin`` and its been running great on this model variant, except for the LTE modem.

There is no ``/dev/cdc-wdm0`` device upon boot. I can't figure out what is wrong, so I hope you could help me get the modem working with this device, and in the process bring complete support to this model variant if there may be subtle changes from the MF286R one.

Here is the ``dmesg``:
>[    0.000000] Linux version 5.10.120 (builder@buildhost) (mips-openwrt-linux-musl-gcc (OpenWrt GCC 11.3.0 r19839-6153c530cc) 11.3.0, GNU ld (GNU Binutils) 2.37) #0 Sun Jun 19 06:36:21 2022
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019750 (MIPS 74Kc)
[    0.000000] MIPS: machine is ZTE MF286R
[    0.000000] SoC: Qualcomm Atheros QCA956X ver 1 rev 0
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] On node 0 totalpages: 32768
[    0.000000]   Normal zone: 288 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 32768 pages, LIFO batch:7
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32480
[    0.000000] Kernel command line: console=ttyS0,115200n8 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 119996K/131072K available (6354K kernel code, 593K rwdata, 1332K rodata, 1248K init, 215K bss, 11076K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] CPU clock: 775.000 MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 4932285024 ns
[    0.000007] sched_clock: 32 bits at 387MHz, resolution 2ns, wraps every 5541893118ns
[    0.008281] Calibrating delay loop... 385.84 BogoMIPS (lpj=1929216)
[    0.074809] pid_max: default: 32768 minimum: 301
[    0.079809] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.087519] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.097643] dyndbg: Ignore empty _ddebug table in a CONFIG_DYNAMIC_DEBUG_CORE build
[    0.108337] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.118743] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.126015] pinctrl core: initialized pinctrl subsystem
[    0.135477] NET: Registered protocol family 16
[    0.140794] thermal_sys: Registered thermal governor 'step_wise'
[    0.195075] clocksource: Switched to clocksource MIPS
[    0.207873] NET: Registered protocol family 2
[    0.212684] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.221069] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.229976] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.238071] TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.245518] TCP: Hash tables configured (established 1024 bind 1024)
[    0.252348] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.259289] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.266926] NET: Registered protocol family 1
[    0.271541] PCI: CLS 0 bytes, default 32
[    0.281458] workingset: timestamp_bits=14 max_order=15 bucket_order=1
[    0.291872] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.298072] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.310090] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    0.320419] pinctrl-single 1804002c.pinmux: 544 pins, size 68
[    0.327536] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.336318] printk: console [ttyS0] disabled
[    0.340889] 18020000.uart: ttyS0 at MMIO 0x18020000 (irq = 9, base_baud = 1562500) is a 16550A
[    0.350031] printk: console [ttyS0] enabled
[    0.359095] printk: bootconsole [early0] disabled
[    0.385590] spi-nand spi0.1: GigaDevice SPI NAND was found.
[    0.391363] spi-nand spi0.1: 128 MiB, block size: 128 KiB, page size: 2048, OOB size: 128
[    0.402218] 6 fixed-partitions partitions found on MTD device (null)
[    0.408827] Creating 6 MTD partitions on "(null)":
[    0.413784] 0x000000000000-0x0000000a0000 : "fota-flag"
[    0.421017] 0x0000000a0000-0x000000120000 : "art"
[    0.428322] 0x000000120000-0x0000001a0000 : "mac"
[    0.435673] 0x0000001a0000-0x000001800000 : "ubiconcat0"
[    0.473064] 0x000001800000-0x000001c00000 : "kernel"
[    0.485328] 0x000001c00000-0x000008000000 : "ubiconcat1"
[    0.634821] spi-nor spi0.0: gd25q16 (2048 Kbytes)
[    0.639771] 3 fixed-partitions partitions found on MTD device spi0.0
[    0.646364] Creating 3 MTD partitions on "spi0.0":
[    0.651321] 0x000000000000-0x0000000a0000 : "u-boot"
[    0.658364] 0x0000000a0000-0x0000000c0000 : "u-boot-env"
[    0.664768] 0x0000000c0000-0x000000200000 : "reserved1"
[    0.673767] Concatenating MTD devices:
[    0.677710] (0): "ubiconcat0"
[    0.680772] (1): "ubiconcat1"
[    0.683827] into device "ubi-concat"
[    0.687555] 1 fixed-partitions partitions found on MTD device ubi-concat
[    0.694473] Creating 1 MTD partitions on "ubi-concat":
[    0.699807] 0x000000000000-0x000007a60000 : "ubi"
[    1.399312] switch0: Atheros AR8337 rev. 2 switch registered on mdio.0
[    2.056632] ag71xx 19000000.eth: connected to PHY at mdio.0:00 [uid=004dd036, driver=Atheros AR8216/AR8236/AR8316]
[    2.067902] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode: sgmii
[    2.076460] NET: Registered protocol family 10
[    2.087946] Segment Routing with IPv6
[    2.091832] NET: Registered protocol family 17
[    2.096569] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    2.109966] 8021q: 802.1Q VLAN Support v1.8
[    2.118361] PCI host bridge /ahb/pcie-controller@18250000 ranges:
[    2.124686]  MEM 0x0000000012000000..0x0000000013ffffff
[    2.130133]   IO 0x0000000000000000..0x0000000000000000
[    2.135719] PCI host bridge to bus 0000:00
[    2.139965] pci_bus 0000:00: root bus resource [mem 0x12000000-0x13ffffff]
[    2.147096] pci_bus 0000:00: root bus resource [io  0x0000]
[    2.152851] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    2.159869] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    2.168119] pci 0000:00:00.0: [168c:0056] type 00 class 0x028000
[    2.174360] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x001fffff 64bit]
[    2.181511] pci 0000:00:00.0: PME# supported from D0 D3hot
[    2.188391] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
[    2.195289] pci 0000:00:00.0: BAR 0: assigned [mem 0x12000000-0x121fffff 64bit]
[    2.206507] UBI: auto-attach mtd9
[    2.209966] ubi0: attaching mtd9
[    4.908043] ubi0: scanning is finished
[    4.946025] ubi0: attached mtd9 (name "ubi", size 122 MiB)
[    4.951705] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    4.958840] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    4.965872] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    4.973062] ubi0: good PEBs: 977, bad PEBs: 2, corrupted PEBs: 0
[    4.979274] ubi0: user volume: 2, internal volumes: 1, max. volumes count: 128
[    4.986738] ubi0: max/mean erase counter: 1/0, WL threshold: 4096, image sequence number: 1192403122
[    4.996169] ubi0: available PEBs: 0, total reserved PEBs: 977, PEBs reserved for bad PEB handling: 18
[    5.005794] ubi0: background thread "ubi_bgt0d" started, PID 331
[    5.014863] block ubiblock0_0: created from ubi0:0(rootfs)
[    5.020586] ubiblock: device ubiblock0_0 (rootfs) set to be root filesystem
[    5.051398] VFS: Mounted root (squashfs filesystem) readonly on device 254:0.
[    5.065645] Freeing unused kernel memory: 1248K
[    5.070322] This architecture does not have kernel memory protection.
[    5.077006] Run /sbin/init as init process
[    5.081233]   with arguments:
[    5.081236]     /sbin/init
[    5.081240]   with environment:
[    5.081243]     HOME=/
[    5.081247]     TERM=linux
[    5.837702] init: Console is alive
[    5.841648] init: - watchdog -
[    7.528357] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    7.668307] usbcore: registered new interface driver usbfs
[    7.674043] usbcore: registered new interface driver hub
[    7.679671] usbcore: registered new device driver usb
[    7.693855] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    7.703490] ehci-fsl: Freescale EHCI Host controller driver
[    7.710939] ehci-platform: EHCI generic platform driver
[    7.716728] ehci-platform 1b000000.usb: EHCI Host Controller
[    7.722604] ehci-platform 1b000000.usb: new USB bus registered, assigned bus number 1
[    7.730852] ehci-platform 1b000000.usb: irq 13, io mem 0x1b000000
[    7.765100] ehci-platform 1b000000.usb: USB 2.0 started, EHCI 1.00
[    7.772318] hub 1-0:1.0: USB hub found
[    7.776978] hub 1-0:1.0: 1 port detected
[    7.781841] ehci-platform 1b400000.usb: EHCI Host Controller
[    7.787758] ehci-platform 1b400000.usb: new USB bus registered, assigned bus number 2
[    7.796006] ehci-platform 1b400000.usb: irq 14, io mem 0x1b400000
[    7.825098] ehci-platform 1b400000.usb: USB 2.0 started, EHCI 1.00
[    7.832281] hub 2-0:1.0: USB hub found
[    7.836973] hub 2-0:1.0: 1 port detected
[    7.844189] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    7.862125] init: - preinit -
[    9.036305] usb 1-1: new high-speed USB device number 2 using ehci-platform
[    9.226433] random: jshn: uninitialized urandom read (4 bytes read)
[    9.301199] random: procd: uninitialized urandom read (4 bytes read)
[    9.339436] random: jshn: uninitialized urandom read (4 bytes read)
[   10.817959] Atheros AR8216/AR8236/AR8316 mdio.0:00: Port 2 is up
[   10.826165] eth0: link up (1000Mbps/Full duplex)
[   10.842968] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   10.858782] IPv6: ADDRCONF(NETDEV_CHANGE): eth0.1: link becomes ready
[   15.159665] UBIFS (ubi0:1): Mounting in unauthenticated mode
[   15.175423] UBIFS (ubi0:1): background thread "ubifs_bgt0_1" started, PID 476
[   15.347347] UBIFS (ubi0:1): recovery needed
[   15.740584] UBIFS (ubi0:1): recovery completed
[   15.745309] UBIFS (ubi0:1): UBIFS: mounted UBI device 0, volume 1, name "rootfs_data"
[   15.753397] UBIFS (ubi0:1): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[   15.763653] UBIFS (ubi0:1): FS size: 115675136 bytes (110 MiB, 911 LEBs), journal size 5840896 bytes (5 MiB, 46 LEBs)
[   15.774613] UBIFS (ubi0:1): reserved for root: 4952683 bytes (4836 KiB)
[   15.781453] UBIFS (ubi0:1): media format: w5/r0 (latest is w5/r0), UUID E87BAADD-3BAA-4D0C-ABE3-4462226194C9, small LPT model
[   15.828060] mount_root: switching to ubifs overlay
[   15.873235] urandom-seed: Seeding with /etc/urandom.seed
[   16.092082] eth0: link down
[   16.126201] procd: - early -
[   16.129505] procd: - watchdog -
[   16.929404] procd: - watchdog -
[   16.946153] procd: - ubus -
[   17.125263] urandom_read_iter: 5 callbacks suppressed
[   17.125270] random: ubusd: uninitialized urandom read (4 bytes read)
[   17.147073] random: ubusd: uninitialized urandom read (4 bytes read)
[   17.154389] random: ubusd: uninitialized urandom read (4 bytes read)
[   17.396019] procd: - init -
[   18.451849] urandom_read_iter: 21 callbacks suppressed
[   18.451857] random: jshn: uninitialized urandom read (4 bytes read)
[   18.511886] random: ubusd: uninitialized urandom read (4 bytes read)
[   18.535666] random: ubus: uninitialized urandom read (4 bytes read)
[   19.272076] kmodloader: loading kernel modules from /etc/modules.d/*
[   19.809327] urngd: v1.0.2 started.
[   19.884006] cdc_acm 1-1:1.2: ttyACM0: USB ACM device
[   19.905460] usbcore: registered new interface driver cdc_acm
[   19.911328] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[   19.955512] usbcore: registered new interface driver cdc_wdm
[   19.980180] Loading modules backported from Linux version v5.15.33-0-g06f50ca83ace
[   19.988059] Backport generated by backports.git v5.15.33-1-0-g183c4ab2
[   20.078683] usbcore: registered new interface driver usbserial_generic
[   20.085553] usbserial: USB Serial support registered for generic
[   20.125999] random: crng init done
[   20.129522] random: 4 urandom warning(s) missed due to ratelimiting
[   20.142972] cdc_ether 1-1:1.6 usb0: register 'cdc_ether' at usb-1b000000.usb-1, ZTE CDC Ethernet Device, 92:df:b0:3d:c8:73
[   20.154645] usbcore: registered new interface driver cdc_ether
[   20.184695] usbcore: registered new interface driver cdc_ncm
[   20.247127] usbcore: registered new interface driver huawei_cdc_ncm
[   20.754400] PPP generic driver version 2.4.2
[   20.763003] NET: Registered protocol family 24
[   20.777175] usbcore: registered new interface driver qmi_wwan
[   20.789260] rndis_host 1-1:1.0 usb1: register 'rndis_host' at usb-1b000000.usb-1, ZTE RNDIS device, f2:8a:48:9f:69:70
[   20.800478] usbcore: registered new interface driver rndis_host
[   20.912701] ath10k 5.15 driver, optimized for CT firmware, probing pci device: 0x56.
[   20.936277] ath10k_pci 0000:00:00.0: enabling device (0000 -> 0002)
[   20.943063] ath10k_pci 0000:00:00.0: pci irq legacy oper_irq_mode 1 irq_mode 0 reset_mode 0
[   23.538016] ath10k_pci 0000:00:00.0: qca9888 hw2.0 target 0x01000000 chip_id 0x00000000 sub 0000:0000
[   23.547590] ath10k_pci 0000:00:00.0: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 0
[   23.566776] ath10k_pci 0000:00:00.0: firmware ver 10.4b-ct-9888-fW-13-5ae337bb1 api 5 features mfp,peer-flow-ctrl,txstatus-noack,wmi-10.x-CT,ratemask-CT,regdump-CT,txrate-CT,flush-all-CT,pingpong-CT,ch-regs-CT,nop-CT,set-special-CT,tx-rc-CT,cust-stats-CT,txrate2-CT,beacon-cb-CT,wmi-block-ack-CT,wmi-bcn-rc-CT crc32 59e741e7
[   23.908555] ath10k_pci 0000:00:00.0: Loading BDF type 0
[   23.919305] ath10k_pci 0000:00:00.0: board_file api 2 bmi_id 0:16 crc32 465094d5
[   25.689981] ath10k_pci 0000:00:00.0: 10.4 wmi init: vdevs: 16  peers: 48  tid: 96
[   25.697765] ath10k_pci 0000:00:00.0: msdu-desc: 2500  skid: 32
[   25.747670] ath10k_pci 0000:00:00.0: wmi print 'P 48/48 V 16 K 144 PH 176 T 186  msdu-desc: 2500  sw-crypt: 0 ct-sta: 0'
[   25.758991] ath10k_pci 0000:00:00.0: wmi print 'free: 114572 iram: 12644 sram: 29508'
[   25.994862] ath10k_pci 0000:00:00.0: htt-ver 2.2 wmi-op 6 htt-op 4 cal pre-cal-nvmem max-sta 32 raw 0 hwcrypto 1
[   26.098329] ath: EEPROM regdomain: 0x0
[   26.098340] ath: EEPROM indicates default country code should be used
[   26.098345] ath: doing EEPROM country->regdmn map search
[   26.098358] ath: country maps to regdmn code: 0x3a
[   26.098364] ath: Country alpha2 being used: US
[   26.098368] ath: Regpair used: 0x3a
[   26.154686] usbcore: registered new interface driver option
[   26.160582] usbserial: USB Serial support registered for GSM modem (1-port)
[   26.225792] ath: EEPROM regdomain: 0x0
[   26.225804] ath: EEPROM indicates default country code should be used
[   26.225809] ath: doing EEPROM country->regdmn map search
[   26.225823] ath: country maps to regdmn code: 0x3a
[   26.225828] ath: Country alpha2 being used: US
[   26.225833] ath: Regpair used: 0x3a
[   26.236997] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
[   26.238874] ieee80211 phy1: Atheros AR9561 Rev:0 mem=0xb8100000, irq=2
[   26.285508] kmodloader: done loading kernel modules from /etc/modules.d/*
[   40.907180] eth0: link up (1000Mbps/Full duplex)
[   40.911988] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   40.935624] br-lan: port 1(eth0.1) entered blocking state
[   40.941211] br-lan: port 1(eth0.1) entered disabled state
[   40.947225] device eth0.1 entered promiscuous mode
[   40.952184] device eth0 entered promiscuous mode
[   40.979443] br-lan: port 1(eth0.1) entered blocking state
[   40.985036] br-lan: port 1(eth0.1) entered forwarding state
[   41.935394] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready

And here is ``/sys/kernel/debug/usb/devices``:
>T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480  MxCh= 1
B:  Alloc=  0/800 us ( 0%), #Int=  0, #Iso=  0
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev= 5.10
S:  Manufacturer=Linux 5.10.120 ehci_hcd
S:  Product=EHCI Host Controller
S:  SerialNumber=1b000000.usb
C:* #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=  0mA
I:* If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub
E:  Ad=81(I) Atr=03(Int.) MxPS=   4 Ivl=256ms
>
>T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480  MxCh= 0
D:  Ver= 2.00 Cls=ef(misc ) Sub=02 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=19d2 ProdID=1489 Rev=ff.ff
S:  Manufacturer=ZTE
S:  Product=ZTE
S:  SerialNumber=123456789ABCD
C:* #Ifs= 8 Cfg#= 1 Atr=e0 MxPwr=  2mA
A:  FirstIf#= 0 IfCount= 2 Cls=e0(wlcon) Sub=01 Prot=03
A:  FirstIf#= 2 IfCount= 2 Cls=02(comm.) Sub=02 Prot=01
A:  FirstIf#= 6 IfCount= 2 Cls=02(comm.) Sub=06 Prot=00
I:* If#= 0 Alt= 0 #EPs= 1 Cls=e0(wlcon) Sub=01 Prot=03 Driver=rndis_host
E:  Ad=82(I) Atr=03(Int.) MxPS=   8 Ivl=1ms
I:* If#= 1 Alt= 0 #EPs= 2 Cls=0a(data ) Sub=00 Prot=00 Driver=rndis_host
E:  Ad=81(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=01(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
I:* If#= 2 Alt= 0 #EPs= 1 Cls=02(comm.) Sub=02 Prot=01 Driver=cdc_acm
E:  Ad=84(I) Atr=03(Int.) MxPS=  10 Ivl=32ms
I:* If#= 3 Alt= 0 #EPs= 2 Cls=0a(data ) Sub=00 Prot=00 Driver=cdc_acm
E:  Ad=83(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=02(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
I:* If#= 4 Alt= 0 #EPs= 2 Cls=0a(data ) Sub=00 Prot=ff Driver=(none)
E:  Ad=85(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=03(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
I:* If#= 5 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=42 Prot=01 Driver=(none)
E:  Ad=86(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=04(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
I:* If#= 6 Alt= 0 #EPs= 1 Cls=02(comm.) Sub=06 Prot=00 Driver=cdc_ether
E:  Ad=88(I) Atr=03(Int.) MxPS=  16 Ivl=32ms
I:  If#= 7 Alt= 0 #EPs= 0 Cls=0a(data ) Sub=00 Prot=00 Driver=cdc_ether
I:* If#= 7 Alt= 1 #EPs= 2 Cls=0a(data ) Sub=00 Prot=00 Driver=cdc_ether
E:  Ad=87(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=05(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
>
>T:  Bus=02 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480  MxCh= 1
B:  Alloc=  0/800 us ( 0%), #Int=  0, #Iso=  0
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev= 5.10
S:  Manufacturer=Linux 5.10.120 ehci_hcd
S:  Product=EHCI Host Controller
S:  SerialNumber=1b400000.usb
C:* #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=  0mA
I:* If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub
E:  Ad=81(I) Atr=03(Int.) MxPS=   4 Ivl=256ms

Please let me know how else I could help. Thank you.

**Comment by obsy** [comment]
In MF286R there is no modem supported by qmi only by ncm. Install comgt-ncm package.

**Comment by braveheartleo** [comment]
> In MF286R there is no modem supported by qmi only by ncm. Install comgt-ncm package.

Hi, thank you for the reply. Yes the image has ``comgt-ncm``, it is part of the default packages for zte-mf286r. I only tried adding qmi but it didn't help with having the modem working.

**Comment by obsy** [comment]
Qmi is useless on the MF286R. Dont install it on MF286R.

**Comment by braveheartleo** [comment]
> Qmi is useless on the MF286R. Dont install it on MF286R.

Yes I have uninstalled the qmi kernel and userspace packages.

**Comment by gkourachanis** [comment]
> > Qmi is useless on the MF286R. Dont install it on MF286R.
> 
> Yes I have uninstalled the qmi kernel and userspace packages.

So, did you get it working? Are you having trouble with the LTE connection?

**Comment by obsy** [comment]
Modem works on ncm without any problem.

**Comment by braveheartleo** [comment]
> > > Qmi is useless on the MF286R. Dont install it on MF286R.
> > 
> > 
> > Yes I have uninstalled the qmi kernel and userspace packages.
> 
> So, did you get it working? Are you having trouble with the LTE connection?

No, I have no connection to the LTE modem still. There is no /dev/cdc-wdm0 and /dev/ttyUSB0. There is only /dev/ttyACM0. How can I configure the modem in Openwrt this way? Also, can we move this discussion to the support ticket I have referenced above? I don't want to clog this pull request meant for code reviews with my issue reports, my apologies for this.

**Comment by obsy** [comment]
```
config 'interface' 'wan'
        option 'proto' 'ncm'
        option 'device' '/dev/ttyACM0'
        option 'pincode' '1234'
        option 'apn' 'internet'
```

Forget about qmi. /dev/cdc-wdm0 etc.

**Comment by braveheartleo** [comment]
> Modem works on ncm without any problem.

Would be kind to guide me through the process on getting this working with mine? I may be missing something, but I can't see it at the moment. I'm using ``https://openwrt.org/docs/guide-user/network/wan/wwan/ethernetoverusb_ncm`` for reference. How can I setup the modem in Openwrt if I'm missing the NCM interface for it, typically /dev/cdc-wdm0 or /dev/ttyUSB0 as stated in that guide?

**Comment by obsy** [comment]
See above.

**Comment by braveheartleo** [comment]
> See above.

Thank you so much for clearing that up! 🥰 I got stuck referring to the guide, but the answer is right there all along. Now it's working in my device and I have full internet access. Cheers 😊

**Comment by obsy** [comment]
> > There is no `/dev/cdc-wdm0` device upon boot. I can't figure out what is wrong, so I hope you could help me get the modem working with this device, and in the process bring complete support to this model variant if there may be subtle changes from the MF286R one.

Read: https://github.com/openwrt/openwrt/pull/9670#issuecomment-1159757163

**Comment by eingrossfilou** [comment]
For those that have a MF286R, do you have the ["My modem doesn't reconnect after it loses the connection" problem](https://openwrt.org/docs/guide-user/network/wan/wwan/ethernetoverusb_ncm#my_modem_doesn_t_reconnect_after_it_loses_the_connection)?

**Pull request closed without merging**
