### PR TITLE
build: ar71xx remove packages from archer-c7-v1

### PR DESCRIPTION
**Pull request by a-mcintosh**
stop boot-loop
      kmod-ath10k ath10k-firmware-qca988x
      5 GHz radio decommissioned, but router works.

----

made in branch off of openwrt-18.06, tested on my hardware.

### CODE REVIEW

**Comment by a-mcintosh** [comment]
Will you explain why?

**Comment by Leo-PL** [comment]
It might be the right place, since 5GHz radio from this model is unsupported by ath10k anyway.

**Comment by bobafetthotmail** [comment]
If that's the case, then it should be added to the commit.
"removed ath10k because the 5Ghz hardware is unsupported and causes bootloop"

Otherwise, if this hardware was supposed to be supported by ath10 it's a bug.

**Comment by a-mcintosh** [comment]
There is a lot of backstory on the web.  The failed chipset choice on the -v1 is the QCA9880-AR1A and the good chip on the -v2 is the QCA9880-BR4A.  Common practice is to buy a new PCI card and modify the hardware.  The consensus seems to be that the driver will never be fixed.

I'll try to edit this down, then update the comment.

**Comment by bobafetthotmail** [comment]
**git commit --amend**

lets you edit the commit message of the last commit

**git push -f** 

to send the changes to github (and in this PR)

**Pull request closed without merging**
