### PR TITLE
uboot-mvebu: backport patch to fix nvme detail crash

### PR DESCRIPTION
**Pull request by BKPepe**
Steps to reproduce:
1. Insert NVMe disk with a reduction to Turris Omnia
2. Go to U-boot
3. Run following these commands:
a) ``nvme scan``
b) ``nvme detail``
4. Wait for crash

This is backported from U-boot upstream repository.
It should be included in the upcoming release - 2022.04 [1].

It was tested on Turris Omnia, mvebu, cortex-a9, OpenWrt master.

[1] https://patchwork.ozlabs.org/project/uboot/patch/20211209100639.21530-1-pali@kernel.org/

### CODE REVIEW

**Comment by neheb** [comment]
Omnia supports NVME drives. Cool.

**Comment by BKPepe** [comment]
Yes, but only up to 60mm.

**Comment by neheb** [comment]
I assume this involves an m.2 to movie adapter.

**Comment by BKPepe** [comment]
That's true. In theory, any m.2 cards could be connected up to 60mm, but it would be connected with card slope and not tested, not recommended. Anything up to 42mm should be just fine.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in 0f432fa3a926bf07f2c6c70ee9a64cbaa95e5d16.

**Pull request closed without merging**
