### PR TITLE
23.05: Multiple backports to OpenWrt 23.05

### PR DESCRIPTION
**Pull request by hauke**
This contains multiple backports to OpenWrt 23.05

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
What about backporting the CI changes?

**Comment by hauke** [comment]
I did not look at the CI changes, @Ansuel  can backport them.

**Comment by guidosarducci** [comment]
@hauke @PolynomialDivision A request, gentlemen? I have two PR's with BPF-related changes I've used since kernel 5.15 and which I hoped to see in 23.05, but having trouble securing reviews for merge. I'd appreciate if you had some time to look.

**Comment by Ansuel** [comment]
@hauke I have to check them but afaik they can totally come later since they are part of CI and won't cause any change to the images

**Pull request merged**
