### PR TITLE
realtek: Replace CEVT_RTL9300 with rtl930x hardware timer

### PR DESCRIPTION
**Pull request by oliv3r**
Currently, the CEVT patch is split between two patches, the platform support patch and the CEVT patch. This is weird and undesired. Lets move some stuff around so that each patch does what it is supposed to do.

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>

### CODE REVIEW

**Comment by oliv3r** [comment]
@svanheule While we'll remove this later anyway, it still makes it cleaner to have this together.

**Comment by oliv3r** [comment]
@svanheule since your on a roll; any thoughts?

**Comment by svanheule** [comment]
Now that we've got the more generic realtek timer, what needs to be done in order to just remove CEVT_9300?

**Comment by oliv3r** [comment]
@svanheule we will, but we need other things before we can _reliably_ use the timer on rtl930x. Since the removal patch may take a year to get merged, with our current churn rate :) Yes, lets clean this up now, and deal with it later in a clean way.

**Comment by oliv3r** [comment]
@svanheule anything technical that you are worrying about for not merging this? Anything you want me to?

**Comment by svanheule** [comment]
Can you be more precise on those "other things"? Do you have other patches already somewhere? If there are any unresolved issues, I'm willing to take this patch, but otherwise it feels a bit like pointless churn...

**Comment by oliv3r** [comment]
@svanheule As you know, I have 170 patches that need to be merged in some form. The 'timer removal' patcches are much later in the queue, due to issues and dependencies and 'not always working'. They depend on the clock patches, which still need to be cleaned up.

I have at the minimal 25 patches that need to go in before the timer removal. At our current rate of about 1 patch per week, we're talking 2 years before we remove the timer.

This is a _trivial_ patch that just moves some stuff around, and reduces the impact and churn/diff of the files affected. So it's not that pointless I'd think :)

**Comment by oliv3r** [comment]
@Ansuel can you also mark this as 'trival' please?

**Comment by oliv3r** [comment]
@svanheule since we've spent more time "bikkering" :p about this, since it's been a week or so, maybe just merge it :) even if we remove this in 2 weeks time ...

**Comment by svanheule** [comment]
There were actually only 3 patches in your realtek-dev tree with relevant changes in order to remove CEVT_9300:
- realtek: Move KConfig CEVT support for 9300
- realtek: Make mach header more generic [only renamed header]
- realtek: Replace CEVT_RTL9300 with hardware timer [replaced clock property to fix image build]

Which allowed applying:
- realtek: timer driver: activate for RTL930x devices

Built and booted on my XGS1250-12 as a test:
```
[    0.000000] CPU0 revision is: 00019555 (MIPS 34Kc)
[    0.000000] MIPS: machine is Zyxel XGS1250-12 Switch
...
[    0.000000] clocksource: realtek_otto_timer: mask: 0xfffffff max_cycles: 0xfffffff, max_idle_ns: 38225208801 ns
```
```
root@OpenWrt:/# cat /proc/interrupts 
           CPU0       
  8:      12423  realtek-rtl-intc   7  timer@3200
```

**Comment by oliv3r** [comment]
Sadly, that's only on the surface, the switch becomes unstable without 'some' of the other patches. Sometimes it doesn't boot properly, sometimes it just stalls. So only those three I found, are not enough, which is why I was cleaning all the others.

**Comment by svanheule** [comment]
> Sadly, that's only on the surface, the switch becomes unstable without 'some' of the other patches.

That something that would've been useful to have mentioned when you referred to 25 seemingly unrelated patches.
I can't see how adding a driver to allow clock speed modification would affect this (bulk of the in-between changes), so I'm quite sure it must be one of the other patches, which probably means the instability is elsewhere.

Can I test this? What does the device do when it becomes unstable? How long does it typically take for it to happen? Does it need to have traffic passing through?

**Comment by svanheule** [comment]
Normally I shouldn't care about out-of-tree patches. Since you provided them as the reason to not go ahead with removing the old timer, I had to go check them out of course :)

Of course the clock driver and timer are closely related, but I assume you are aware that what a clock driver does is to provide a means to determine and (optionally) modify the clock signal driving the timer. If that driver isn't there, the exact same hardware is still there, driving the timer hardware. So I currently don't see how not having that driver should cause any instabilities.

It's possible that one of the interim fixes has already improved the situation. I'll let my device run (idle) overnight with these patches, and let you know tomorrow if it's still alive.

**Comment by oliv3r** [comment]
> Normally I shouldn't care about out-of-tree patches. Since you provided them as the reason to not go ahead with removing the old timer, I had to go check them out of course :)

Hahah, do care! 75% of these patches come of 'out-of-tree' patches from birger, marcus and others probably too. I even look at your tree :) we can learn a lot from each other :p

But I obviously don't offer you (185 now :p) patches in one go, because not everything is ready, and fully tested in an isolated fashion. And yeah, maybe I could have dedicated some time to figure out why and what is needed to isolate the timer stuff, but with early failure, I quickly gave up on that. I can only spend my time once, and I need to generate more patches first :p (tbh I really don't like that bit, but the code-base is in such a dire state I can't help myself :p)

> 
> Of course the clock driver and timer are closely related, but I assume you are aware that what a clock driver does is to provide a means to determine and (optionally) modify the clock signal driving the timer. If that driver isn't there, the exact same hardware is still there, driving the timer hardware. So I currently don't see how not having that driver should cause any instabilities.

I don't know, as I said, I didn't deeply dive into it, which is also why i haven't offered you these patches as a whole, they are lower on my 'todo pile'. But again, could be it was that stupid IRQ patch we had linked in this MR, could be something unrelated. I just haven't looked into that.

> 
> It's possible that one of the interim fixes has already improved the situation. I'll let my device run (idle) overnight with these patches, and let you know tomorrow if it's still alive.

The only testing I've done, is booting (which causes the most failures, see the forum post I wrote a couple of weeks back) dhcp setup and iperf. I use `iperf3 -P4 -t 2000 -c <ip>` over a gbit (usb) link, which granted, is diminished by USB2 speeds :) The iperf3 tests actually never failed. IDLE also never caused an issue, it was really during boot/network init.

My (far fetched) theory at the time, was that the realtek code is causing a lot of busy-waiting and things like that, that just cause things to hang, which seems to have made worse by the timer changes.

As for 'the timer is just the timer', before we where using a (software) MIPS timer, where we not? And now a hardware timer (that's driven by the clocks) 'big' difference imo :)

But again, if you feel confident to merge these changes, I'm okay with that, I'm not against it :)

**Comment by oliv3r** [comment]
I just rebased and will test this some more too; I snook in https://github.com/openwrt/openwrt/pull/11636/commits/89de89a62c365b69112ee42ad1955a8f432466fc if you don't mind ;) you can drop it if you don't want right now ...

**Comment by svanheule** [comment]
> As for 'the timer is just the timer', before we where using a (software) MIPS timer, where we not? And now a hardware timer (that's driven by the clocks) 'big' difference imo :)

The CEVT_RTL9300 timer and the otto timer are same, just different driver implementations. The MIPS timer is also a hardware timer, but a different piece of hardware. Although the otto timer replaced the use of the MIPS timer, they could in theory be used at the same time.


> So my first boot actually immediately failed
 
:(

My three boots worked fine, but this probably needs more statistics. I'll try running some iperf tests too later this evening.

**Comment by oliv3r** [comment]
> > As for 'the timer is just the timer', before we where using a (software) MIPS timer, where we not? And now a hardware timer (that's driven by the clocks) 'big' difference imo :)
> 
> The CEVT_RTL9300 timer and the otto timer are same, just different driver implementations. The MIPS timer is also a hardware timer, but a different piece of hardware. Although the otto timer replaced the use of the MIPS timer, they could in theory be used at the same time.
> 
> > So my first boot actually immediately failed
> 
> :(
> 
> My three boots worked fine, but this probably needs more statistics. I'll try running some iperf tests too later this evening.

Booting seems to be the biggest issue, since restart of the network doesn't reliably work (that I know off) reboot is the only tool to validate. Could be difference of hardware? (network components are different) but idk :shrug: 

So i'll go back to my initial proposition, merge the cleanup; and deal with the bootup when we have more breath for that :)

**Comment by svanheule** [comment]
After flashing OpenWrt and cold-booting I was able to reproduce the watchdog time-outs. I also noticed very odd jumps in the timestamps of the kernel's boot log.

Dug a bit deeper and realised the scheduler clock was being registered before being enabled. Enabling only happened a bit later, when that timer was started as a clocksource.

Seems to be stable now for me. Can you give it another spin?

**Comment by oliv3r** [comment]
> After flashing OpenWrt and cold-booting I was able to reproduce the watchdog time-outs. I also noticed very odd jumps in the timestamps of the kernel's boot log.
> 
> Dug a bit deeper and realised the scheduler clock was being registered before being enabled. Enabling only happened a bit later, when that timer was started as a clocksource.
> 
> Seems to be stable now for me. Can you give it another spin?

I love how you are super-hesitant to avoid doing the cleanup patch :D but look where it got us :D super excited about trying this one out!!

**Comment by svanheule** [comment]
Merged with:

38cba61bff52 realtek: timer: Register enabled scheduler clock
68e28cdc47ac realtek: timer: Activate for RTL930x devices
f6ba61b9298f realtek: timer: Remove CEVT_RTL9300 completely
afb5d9e9d5a5 realtek: timer: Fix cosmetic whitespace in comments

I've added the `MIPS_EXTERNAL_TIMER` option to RTL930X too, and refreshed the 5.15 kernel config afterwards.

**Comment by oliv3r** [comment]
> Merged with:
> 
> [38cba61](https://github.com/openwrt/openwrt/commit/38cba61bff52f22affa66cc764dab2ac158ab7d3) realtek: timer: Register enabled scheduler clock [68e28cd](https://github.com/openwrt/openwrt/commit/68e28cdc47ac805faf2dda58127e848f8ef6efca) realtek: timer: Activate for RTL930x devices [f6ba61b](https://github.com/openwrt/openwrt/commit/f6ba61b9298f12dbf116556edc879d047e5145e9) realtek: timer: Remove CEVT_RTL9300 completely [afb5d9e](https://github.com/openwrt/openwrt/commit/afb5d9e9d5a5ecafceb0e3d4ffe1210077f8a40b) realtek: timer: Fix cosmetic whitespace in comments
> 
> I've added the `MIPS_EXTERNAL_TIMER` option to RTL930X too, and refreshed the 5.15 kernel config afterwards.

yeah sure, no worries, this will all go away in the upcoming patches anyway :)

**Pull request closed without merging**
