### PR TITLE
iptables: update to 1.8.9

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Changelog:
https://www.netfilter.org/projects/iptables/files/changes-iptables-1.8.9.txt

Mirror switched to "tar.xz".

Remove upstreamed:
- 020-treewide-use-uint-instead-of-u_int.patch
- 030-revert-fix-build-for-missing-ETH_ALEN-definition.patch
- 040-xshared-Fix-build-for-Werror-format-security.patch
- 050-build-fix-error-during-out-of-tree-build.patch
- 060-libxtables-unexport-init_extensions-declarations.patch

Refresh patches:
- 010-add-set-dscpmark-support.patch
- 101-remove-check-already.patch
- 102-iptables-disable-modprobe.patch
- 103-optional-xml.patch
- 200-configurable_builtin.patch
- 600-shared-libext.patch
- 700-disable-legacy-revisions.patch

Import patches:
- 020-extensions-NAT-Fix-for-Werror-format-security.patch

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Please have a look at `[600-shared-libext.patch](https://github.com/openwrt/openwrt/pull/12106/files#diff-2d75a2d24653dc99916a048bea57586e91549212bd80acd9529846ad5b9fb360)`.

**Comment by G-M0N3Y-2503** [comment]
I seem to be getting the following
```
root@OpenWrt:/# iptables -t nat -A POSTROUTING -p TCP -j MASQUERADE
iptables v1.8.9 (nf_tables): Chain 'MASQUERADE' does not exist
Try `iptables -h' or 'iptables --help' for more information.
```
or 
```
root@OpenWrt:/# iptables -t nat -A POSTROUTING -p TCP -j MASQUERADE
iptables v1.8.9 (legacy): Couldn't load target `MASQUERADE':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
```
With this version of iptables.

I was wondering if you have any insight as to why it doesn't work anymore.
I came across [this commit](https://git.netfilter.org/iptables/commit/?id=f30c5edce0413b2b2346c7f58e801f10f6e9bc5a) which at a glance changes some shared objects into symlinks, Is it perhaps some issue to do with that?

**Comment by zxlhhyccc** [comment]
@G-M0N3Y-2503 Castrated `libipt-masquerade.c`！

**Comment by AuthorReflex** [comment]
Update to 1.8.10 is ready
https://github.com/openwrt/openwrt/pull/16641

**Pull request closed without merging**
