### PR TITLE
kirkwood: switch to Kernel 5.15 by default

### PR DESCRIPTION
**Pull request by aparcar**
This PR to have an overview of testing.

### CODE REVIEW

**Comment by ascendbeing** [comment]
@aparcar gotta semi hijack: please can you implement my fix for preserve config for ea3500/ea4500 kirkwood? My comments in #11692 do this. 2 liner replacing a 1 liner in linksys.sh. it's been broken on ea3500/ea4500 Kirkwood for at least a few months. I've tested my change on ea3500. without it you can't preserve config for ea3500/ea4500. kernel upgrade seems as good a reason as any to do this.

**Comment by aparcar** [comment]
To git.openwrt.org:openwrt/openwrt.git
   16565bc1ce..596059266a  master -> master

Merged as discussed in meeting.

**Comment by jaheilman** [comment]
Tested Apr9 snapshot on EA3500:
squashfs-factory.bin -> no LuCI after update.  SSH works fine.
squashfs-sysupgrade.bin via ssh/command line (sysupgradev -v ...); still no LuCI.

Seems like the luci redirect page flashes for the briefest of seconds before getting a "network connection refused" error.  

I will do some testing using iperf and look into the webpage situation.  Anything I can pull for you lovely devs?

**Comment by aparcar** [comment]
Are you'd sure LuCI is even installed? Usually not part of snapshots

**Comment by jaheilman** [comment]
Yeah - that's on me!  First time snapshot user.  Installed LuCI from opkg fine - one of these days I'll get better with UCI.

I can confirm both 2.4GHz and 5GHz radios are detected.  Routed speeds are 350MBps (which is standard for this unit in my experience).  Everything looks good, I'll continue to benchmark and report.

**Pull request closed without merging**
