### PR TITLE
tools/cmake: fix compilation with host libzstd-dev

### PR DESCRIPTION
**Pull request by neheb**
cmake's find_package looks at host paths first for some reason. Switch to using pkgconfig for the search, matching other modules.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

ping @Ansuel

### CODE REVIEW

**Comment by neheb** [comment]
Meh decided to upstream this: https://github.com/libarchive/libarchive/pull/1781

**Comment by Ansuel** [comment]
@neheb should we add a fixes tag?

**Comment by neheb** [comment]
Added Fixes

**Comment by Ansuel** [comment]
@neheb can you remove extra space between fixes and soc? (pls don't hate me ahahha)

**Pull request merged**
