### PR TITLE
[19.07] ar71xx/mikrotik: backport fixes from master

### PR DESCRIPTION
**Pull request by f00b4r0**
Following the merge of #2943, this PR backports the necessary bits to get new revisions of already supported hardware to properly load WLAN caldata. This PR is meant to supersede/replace #2729.

Only the last two commits bring 19.07-specific code that isn't backported from master. If necessary/desirable, that code can be committed to master first and backported: the touched files are identical in master and 19.07 (ar71xx is a source-only target no longer updated in master).

It should be possible to backport this all the way back to 18.06 if needed.

Successfully tested on my (old rev) mAP Lite.

### CODE REVIEW

**Comment by f00b4r0** [comment]
@xback @adrianschmutzler backport PR for your review :)

**Comment by xback** [comment]
Great!
Will test this on Monday.

**Comment by adrianschmutzler** [comment]
Hmm, to be tidy, we actually should merge the last two patches to master first, so this PR really is a partial backport, and won't make parts of 19.07 "newer" than master. Any deviation between master and 19.07 is actually quite a pain if you want to fix anything later (I suffered from that just a while ago).

(Or we just delete ar71xx in master now, and decide to only update it in stable branches from now on.)

**Comment by f00b4r0** [comment]
@adrianschmutzler yes I fully agree that it's cleaner to do a true backport, that's why I mentioned it's actually possible and easy since the affected files have been untouched since 19.07.

IMHO we shouldn't delete ar71xx from master during 19.07 lifetime for that exact same reason.

**Comment by ae6xe** [comment]
I successfully tested this PR on top of 19.07.2 ar71xx target build within http://www.arednmesh.org images.  The device was a basebox 2  RB912UAG-2HPnD-OUT r2.

**Comment by f00b4r0** [comment]
merged; so closing

**Pull request closed without merging**
