### PR TITLE
treewide: Power LED color and function

### PR DESCRIPTION
**Pull request by namiltd**
Power LED color and function for all platforms

### CODE REVIEW

**Comment by raenye** [comment]
I think it makes sense to split this to several commits, one per target, and also deal with the other common LED function: status.

Also, perhaps rename the LED node itself (`s/power-red/led-power-red/g`).

**Comment by Ansuel** [comment]
@namiltd This was done with an automated script right?

**Comment by namiltd** [comment]
Few sed scripts + manual changes

**Comment by Ansuel** [comment]
> manual changes

ehhhhh what kind? I hoped it was all sed

**Comment by namiltd** [comment]
Manually only when, for example, there are comments that make it difficult to find or a different order of lines. There are only a few manually patched files, it didn't make sense to write a script for them.

**Comment by Ansuel** [comment]
@namiltd just trying to find reason not to check 500+ files ahahahah

**Comment by Ansuel** [comment]
Anyway I agree with what was asked... I know it's a lot to ask but can you split this in more commits one per target? 
Also the email in the SoB tag is wrong (use real email and not the no replay one from github)

**Comment by namiltd** [comment]
Of course I can split it, but this way I did it once, not eleven times.

**Comment by csharper2005** [comment]
> I think it makes sense to split this to several commits, one per target, and also deal with the other common LED function: status.
> 
> Also, perhaps rename the LED node itself (`s/power-red/led-power-red/g`).

The `led-power-red` doesn't match regex `(^led-[0-9a-f]$|led) `.  https://www.kernel.org/doc/Documentation/devicetree/bindings/leds/leds-gpio.yaml

**Comment by csharper2005** [comment]
@namiltd what is your plan? One type of led for all devices, then second type of led for all devices, etc?

As @raenye noted above node names (both leds and buttons) have to be updated too. I started per-device work here:
https://github.com/openwrt/openwrt/pull/14125
https://github.com/openwrt/openwrt/pull/13821

Additionally, in some cases `base-files/etc/board.d/01_leds` update is required.

**Comment by namiltd** [comment]
> @namiltd what is your plan? One type of led for all devices, then second type of led for all devices, etc?

That's exactly what I planned.

**Comment by csharper2005** [comment]
> > @namiltd what is your plan? One type of led for all devices, then second type of led for all devices, etc?
> 
> That's exactly what I planned.

I see. Some devices requires manual analyze. In the following example the led label doesn't match the function. Such conflicts should be resolved not by the sed, but by human. 😉
image
 
Therefore, the following plan seems more appropriate to me:
1. Take a group of devices or even whole target;
2. Change leds and buttons node names according to the kernel doc naming convention ;
3. Sort the nodes by gpio;
4. After the individual analyze add/update functions, enumerators, 02_leds.

**Comment by namiltd** [comment]
Currently, the project contains over 1,500 dts files. Correcting them one by one will take a lot of time. This needs to be done faster, so using scripts (e.g. sed) multiple files at once.

**Comment by Ansuel** [comment]
@csharper2005 @namiltd I would first split this per target (makes it easier to review)
For the simple case I would use sed... dropping the label to writing split color and function should be easy. The 01_leds scripts are not affected since the final name should be the same.

THEN we address all the special case and eventually add additional patch for the kernel for the missing status... For these conversion a gradual approach is a MUST, asking to change everything in one go is a recipe for regression.

**Comment by namiltd** [comment]
You're right, in this situation I'm closing this request. I tried to speed it up, unsuccessfully. I sparked a discussion, so I partially achieved my goal.

**Comment by Ansuel** [comment]
I would have preferred this to be just the simple case with the commit split... :(

**Comment by csharper2005** [comment]
> @csharper2005 @namiltd I would first split this per target (makes it easier to review) 
I agree with you. Additionally my suggestion is to update all leds (not by function) at once so as not to check one device several times. 

> For the simple case I would use sed... dropping the label to writing split color and function should be easy. The 01_leds scripts are not affected since the final name should be the same.

Not always. Currently lan leds usually looks like `green:lan1`. When we use enumerator we get `green:lan-1`.

> THEN we address all the special case and eventually add additional patch for the kernel for the missing status... For these conversion a gradual approach is a MUST, asking to change everything in one go is a recipe for regression.

Should this patch be upstreamed to the mainline kernel?

**Comment by Ansuel** [comment]
> green:lan1

those are special case that will be handled later... (another case of simple sed tho)

**Comment by csharper2005** [comment]
> You're right, in this situation I'm closing this request. I tried to speed it up, unsuccessfully. I sparked a discussion, so I partially achieved my goal.

Thanks for bringing up this topic. In any case, it was useful. I'm sorry you made decision to close this PR.

**Comment by namiltd** [comment]
Dividing into separate targets requires separate requests, so it was necessary.

**Comment by Ansuel** [comment]
@namiltd was ok to have all the different commits here

**Comment by chunkeey** [comment]
Please also make sure a look at the dts/dtsi files. Some of them look like they are missing the ```#include <dt-bindings/leds/common.h>``` (This is where the LED_COLOR_ID_ + LED_FUNCTION_ are defined in)

**Pull request closed without merging**
