### PR TITLE
mvebu: revert DSA

### PR DESCRIPTION
**Pull request by ghost**
Without a proper migration script DSA is not ready for mvebu, reverting bring back the nice swconfig to our mvebu devices.

### CODE REVIEW

**Comment by thagabe** [comment]
What do you mean?

**Comment by lucize** [comment]
MT7621 was also switched to DSA without a migration script

**Comment by anomeome** [comment]
This fire was fought and a decision made in the [mvebu:5.4 kernel update thread](https://github.com/openwrt/openwrt/pull/2804#issuecomment-612428266). A migration script is an _unobtanium_.If it wasn't, it would have materialised already; there certainly has been enough successfully attempted failures.

**Comment by bobafetthotmail** [comment]
sorry but it's years that devs wait for someone to make a script that can port switch configuration to DSA, it is not going to happen.

We will have to put strong warnings in next OpenWrt release so people know they will need to deal with this, but there is really no point in stopping this in master.

**Pull request closed without merging**
