### PR TITLE
ipq40xx: add support for Mikrotik wAP R ac

### PR DESCRIPTION
**Pull request by lynxis**
The Mikrotik wAP R AC is an outdoor, dual band, dual radio (802.11ac) AP with a miniPCIe slot for a LTE modem.
The wAP R AC is similar to the wAP AC but with the miniPCIe slot.

See https://mikrotik.com/product/wap_r_ac for more info.

Specifications:
- SoC: Qualcomm Atheros IPQ4018
- CPU: 4x ARM Cortex A7
- RAM: 128MB
- Storage: 16MB NOR flash
- Wireless:
   - Built-in IPQ4018 (SoC) 802.11b/g/n 2x2:2, internal antenna
   - Built-in IPQ4018 (SoC) 802.11a/n/ac 2x2:2, internal antenna
- Ethernet: Built-in IPQ4018 (SoC, QCA8075) , 2x 1000/100/10 ports one with 802.3af/at PoE in
- 1x Mini PCI-E port (USB2)

Installation:
Boot the initramfs image via TFTP, then flash the sysupgrade image using sysupgrade. Details at https://openwrt.org/toh/mikrotik/common.

Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

### CODE REVIEW

**Comment by lynxis** [comment]
Hi @robimarko,

I'm wondering how we should handle the other wAP based devices with LTE.
There are 3 devices:
- wAP R ac (comes with an empty lte slot)
- wAP ac LTE (lte modem)
- wAP ac LTE6 (cat6 lte modem)
they contain all the same board, but with a different modem.
In theory we could have different profiles to save some flash memory because the LTE/LTE6 seems to use a non-qmi modem. I only have the wAP R ac around. I don't know which driver the original mikrotik modem uses but from hap-ac3-lte6-kit it uses kmod-usb-acm kmod-usb-net-rndis.

I would go for 2 profiles. wAP R ac including most common lte drivers and wAP ac LTE for both LTE and LTE6.

Any thoughts?

**Comment by robimarko** [comment]
From my point of view, we should have profiles for each one of them even if the DTS will be mostly shared as that allows not shipping packages that are not needed.

**Comment by f00b4r0** [comment]
> I would go for 2 additional profiles. wAP R ac including most common lte drivers and wAP ac LTE for both LTE and LTE6 with only matching lte drivers.
> 
> Any thoughts?

We're already shipping profiles for otherwise identical devices (with the DTS being slimmed down to includes and setting device names), so I'd agree with @robimarko: it also makes it easier for users to find the correct image (though multiplying such cases certainly has an impact on our build infrastructure).

**Comment by robimarko** [comment]
For that one I am fine with having unique profiles or a shared one as the packages are gonna be the same, it just needs to be clearly communicated that it supports both boards

**Comment by lynxis** [comment]
Ok. Thank you! I'll take care of change and merging the remaining things.

**Comment by cTurtle98** [comment]
I see the wAP R AC in the snapshot builds but I don't see a techdata page for it nor a device page for it...

is there not one or am I failing to find it?

**Comment by Djfe** [comment]
This was merged in November 2022
https://github.com/openwrt/openwrt/commit/d4c460648dc28a7e8f2082101159971f6858c743

There is no wiki article for it, yet.
https://openwrt.org/toh/mikrotik/rbwapr-2nd_wap_r?do=search&sf=1&q=wap%20%40toh%3Amikrotik

**Pull request closed without merging**
