### PR TITLE
ath25: add 5.15 testing kernel

### PR DESCRIPTION
**Pull request by PolynomialDivision**
**Only compile tested!**

Add 5.15 as testing kernel.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@Leo-PL Can you test?

**Comment by Leo-PL** [comment]
Unlikely, I didn't resolve issues with bootloaders on my devices yet, so best I can do is to try booting initramfs.

**Comment by PolynomialDivision** [comment]
I think booting initramfs is totally fine. :)

**Comment by Leo-PL** [comment]
If someone could help me figure out a bootloader for D-Link DWL-3200AP B2 and TP-Link TL-WR340G v3, that would make things easier - the stuff I need seems to have evaporated from the Internet. @rsa9000 perhaps?

**Comment by Leo-PL** [comment]
@PolynomialDivision do you have some prebuilt images? This would save me a ton of time when testing.

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision do you have some prebuilt images? This would save me a ton of time when testing.

What device?

**Comment by Leo-PL** [comment]
The generic one should do (in ELF format) - I managed to somewhat boot it on DWL-3200AP.

**Comment by rsa9000** [comment]
@Leo-PL, sorry for the late reaction. I can not help with this issue: I have no idea what could be wrong with the bootloader and have no equipment access to run-test the code. Sorry.

**Comment by ynezz** [comment]
@dangowrt maybe you could check this along with @robimarko 's [ath25: mark as source-only](https://patchwork.ozlabs.org/project/openwrt/patch/20230116121856.59740-1-robimarko@gmail.com) ? IMO we should remove this target if its not usable with 5.15, there is no point of keeping it in the tree.

**Comment by Ansuel** [comment]
@hauke how should we handle this. Since it's source-only think it's ok to merge?

**Pull request closed without merging**
