### PR TITLE
treewide: Use DHCP by default on single port devices

### PR DESCRIPTION
**Pull request by diizzyy**
Use dhcp by default if the device only has one port.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Tested on OrangePi PC

**Comment by diizzyy** [comment]
@hauke

**Comment by wigyori** [comment]
There are a bunch of other targets with devices having one interface only (raspberrypi and mxs to say the least, including a bunch of APs from the "router" targets). Are those to be migrated as well? If this is a "project-wide" initiative to move to dhcp for such devices, so be it, otherwise I'm a bit reluctant to have the default behaviour (192.168.1.1 as a start) changed.

**Comment by diizzyy** [comment]
I think it makes more sense to have boards/devices that aren't "intended" as routers/APs to use DHCP as these are mainly used as generic network devices rather than a static IP.

**Comment by diizzyy** [comment]
Ok, how about
One port --> DHCP
More than one --> 192.168.1.1 ?

**Comment by diizzyy** [comment]
Having a look at the tree...

```
apm821xx		Change
arc770			Uses DHCP
archs38			Uses DHCP
at91			Change
ath25			Change (1)
brcm2708		Change
gemini			Change (2)
imx6			Change
ipq40xx			Change
ixp4xx			Change (3)
kirkwood		Uses DHCP
layerscape		Change? (3)
malta			Change
mcs814x			Change
mvebu			Change
mxs			Change
omap			Change? (3)
omap24xx		Uses DHCP
orion			Change
oxnas			Uses DHCP
pistachio		Uses DHCP
sunxi			Change
xburst			Change
zynq			Change
```

1. https://github.com/openwrt/openwrt/blob/master/target/linux/ath25/base-files/etc/board.d/02_network#L23
2. Not sure how to fix https://github.com/openwrt/openwrt/blob/master/target/linux/gemini/image/ImageInfo-ib4220 or DNS-313
3. No idea how the setup works...

If there's interest I can make a pull request for most of these targets (the ones I understand how they work) and we can work on the rest separately including the fast changing targets like ar71xx, ath79, mediatek, ramips .

**Comment by diizzyy** [comment]
```
Current status

gemini:			Need help

imx6:			Style help, gw51xx and gw52xx are single port.
			Alphabetical order or can I move these to Wandboard?

ixp4xx:			Need help

layerscape:		All supported boards seems to have multiple ports

malta:			Emulated device/environment, leave it alone?

mvebu:			Can't find any supported single port device

omap:			Need help

xburst:			Need help
```

I'd like to do ar71xx, ath79, mediatek, ramips separately as these are fast moving targets meaning
that it would need rebasing quite frequently. Malta and mvebu should be left untouched? 

As for the rest mentioned above, I'd like some help and do those targets separately.

**Comment by wigyori** [comment]
- mxs - ack.
 - ixp4xx - you'll need to make a distinction between the router devices (i.e. gw7001, tonze, etc) and the NAS devices (i.e. fsg3). I'm struggling with getting the target on 4.14 (some fsckery around initializing PCI devices and the kernel barfing as a result), if no one else volunteers, I'll add this to the queue.
 - ath25 - umm. So a distinction is also necessary for differences between a fonera, a fonera $foo, a meraki, and the other devices. :)

Regards,
-w-

**Comment by diizzyy** [comment]
@wigyori 
Thanks for having a look, missed the Fonera(2) box :-/

Regarding ath25 it looks like there are a few devices that potentially(?) still works

EnGenius ECB3500 (single port)
https://wiki.openwrt.org/toh/engenius/ecb3500
Works?

Fonera FON2202 (2 ports, switch)
https://wiki.openwrt.org/toh/fon/fonera2
Confirmed working
https://lists.openwrt.org/pipermail/openwrt-devel/2018-May/012398.html

Freedom CPE (Single port)
https://wiki.openwrt.org/toh/abicom/freedom_cpe
Confirmed working
https://lists.openwrt.org/pipermail/openwrt-devel/2018-May/012398.html

Meraki Mini (Single port)
https://openwrt.org/toh/meraki/mini
Works?

Accton MR3201a (Single port)
https://wiki.openwrt.org/toh/hwdata/accton/accton_mr3201a
Works? Can't find any information on how to install OpenWrt on this device

https://lists.openwrt.org/pipermail/openwrt-devel/2018-May/012398.html
D-Link DWL-2100AP (Single port) and D-Link DIR-300 (rev A1) (switch 5 ports) are 16Mbyte RAM devices which the Fonera(1) wiki page (https://wiki.openwrt.org/toh/fon/fonera#step_1downloading_the_openwrt_images) claims are dropped. Does 16Mbyte devices actually work more than booting?

I have no idea how you'd identify these devices however as they're using a generic platform image nor do I have the hardware myself.

@rsa9000
Can you assist with the mentioned above?

@linusw 
You seem quite active regarding the gemini platform, can you have a look at this?

@lynxis 
Can you assist with omap?

**Comment by rsa9000** [comment]
@diizzyy 
If I correctly understand your question to me, then you would like to know how ath25 detects a board model. Unfortunely, there are no mechanism in ath25 to detect a particular board model. All we have is a small piece of code (you already mentioned it above), which checks the number of ethernet interfaces and possible presence of a Switch chip and then configure LAN/WAN interface(s).

And by the way,  your initial comment answer to the question *what* should changed, but it do not describe *why* these changes should be made. You plan to change the default behavior in the such sensitive part as the device access after the initial reflashing, so could you rationale this change, please?

**Comment by diizzyy** [comment]
@rsa9000 
You're correct, sorry for being unclear. So the change above would be correct for ath25 unless I'm misunderstanding?

As for changing default behavior, in general I think we can assume that devices with one port are going to be connected to an existing network. In general the majority of "common" embedded distributions for single port computers/boards/devices (*ELEC, Lakka(.tv), Armbian, OpenEmbedded based distros etc) defaults to DHCP which makes it more consistent and convenient.

**Comment by rsa9000** [comment]
> So the change above would be correct for ath25 unless I'm misunderstanding?

Technically your change is correct for ath25. I can not acknowledge the change of the default behavior in such way (see below), but anyway you can feel free to add Reviewed-by: Sergey Ryazanov <ryazanov.s.a@gmail.com> to ath25 patch.

> In general the majority of "common" embedded distributions for single port computers/boards/devices (*ELEC, Lakka(.tv), Armbian, OpenEmbedded based distros etc) defaults to DHCP which makes it more consistent and convenient.

I would like to say that the OpenWRT is "uncommon" distro in such way that it used for wireless equipment, so you have at least two interfaces: wired and wireless. May be switching to using the DHCP for LAN interfaces of Access Point devices is suitable change. But there are a lot of Wireless Bridges like a Ubiquiti NS2/NS5 too and I assumes that users of such devices preffer to keep them statically configured. So I doubting, should we so radically change the default behaviour of all devices or may be it would be more suitable to add buildtime configuration option and allow users to choose static or dynamic configuration use by default?

I would like to say that the having a single port only is not sufficient condition to toggle this port to dynamic configuration mode.

May be you could describe a some real use case, when switching to dynamic configuration would benefit the developers and users, except making OpenWRT similar to other distros?

**Comment by diizzyy** [comment]
I actually asked about that earlier and so far it seems to be all or nothing mainly for support reasons. I didn't want to touch devices that aren't "generic" boards (sunxi etc), storage devices (D-Link DNS-3..) etc however I do see the benefit of having a unified configuration to reduce time spending on explaining why device X doesn't work like Y. Seeing that we have some platforms using DHCP instead of 192.168.1.1  I'd guess that developers used bootp, tftpboot for instance and/or considered 192.168.1.1 a hassle. In the end it will boil down to use case, personal preference and experience. I personally prefer when you just can connect a device and it works rather than changing network configuration on whatever device you use. This kinda works the other way on routers, as most already use DHCP they can just plug in a device into one of the LAN ports and dnsmasq/unbound will set up the rest. Having that in mind, I would guess that most end-users expects boards, NAS boxes etc to use DHCP by default because that's more common which kinda goes into the making it similar to other distros argument however.

**Comment by rsa9000** [comment]
Funny, I personally prefer static configuration for development to reduce uncertainty and dynamic configuration in production network to reduce manual work.

But your position definitely make sense.

**Comment by bobafetthotmail** [comment]
I think that for most usecases mentioned the device isn't set-and-forget anyway, so setting it to DHCP is more a hindrance than a benefit.

I mean, a NAS is completely worthless until someone connects to it and sets up the storage drives and the shared folder for the very least.

Other devices like raspberry Pi or similar devboards are even more "must be configured on first power up".

Most network devices are also worthless until someone connects to them and sets them up.

Placing anything on DHCP makes first connection annoying and less user-friendly, as now we would have to write in the wiki how to figure out the IP assigned by a DHCP server (assuming that there is one at all) before connecting to the device.

Afaik most stock router firmwares use something like **mdns** or **avahi** so that users can write a website name and be directed to the the router's webpage. I don't think this is a viable option (to have mdns installed by default).

So I think we should unify the configurations by placing all devices on static IP by default, then I can just write in the wiki " set your PC to static IP 192.168.1.2 and connect to the device at 192.168.1.1" which will always work, is easy to explain and allows the user to connect to the device to configure it.

**Comment by bobafetthotmail** [comment]
>I think you're exaggerating a bit, pretty much all firmwares/distros/* need some kind configuration and if this is such a hurdle how come it works fine for very common ones?

No. I said that all devices you want to place on DHCP would need to be configured anyway, because OpenWrt does not ship default NAS configuration with a drive and a shared folder, nor it ships whatever special configuration is needed by someone using a Raspberry Pi or similar devboards.

I also said that if you place them on DHCP it's annoying to connect to them because you need to figure out their IP first.

Since the device needs to be configured anyway, changing from static IP to dynamic or whatever else can be easily done during the configuration phase.

>many Yocto images are now using DHCP by default 

The ones with dhcp are also shipping Avahi by default, https://www.toradex.com/community/questions/5524/how-to-disable-avahi-from-yocto-build.html which is a zeroconf protocol server, like some commercial products.

So the user only writes a website name like **`http://www.routerlogin.net/`** for netgear routers https://kb.netgear.com/980/How-do-I-log-in-to-my-NETGEAR-home-router  and they land in the router web interface.
This does not require internet access, it's actually pretty neat.

OpenWrt has **mdns** that is small and last time I tried it could do that for a few services (webinterface, ssh and ftp I think, need to look up packages), but is not installed by default.

>If we look commercially,

The link you posted is an example where the user needs to download an application that connects to the device to read the IP

_**2.** Go to the mydlink support page and **download the setup wizard specific to your model and operating system**. Unzip it to your desktop or a folder on your PC._

This tool is required to proceed with step 3 (writing the IP of the device in the browser and then connecting).

Afaik OpenWrt does not have such tools so the user would have to figure out the IP on his own. I don't see how this would be an improvement over the static IP where you always know what it is.

-----
**conclusions:**

It seems to me that switching to DHCP "just because others do it" is cargo culting. We need to know why they are doing it so we can decide if OpenWrt would actually benefit or not from the change.

From what I saw, they are using DHCP because they integrate a very easy and convenient way to connect to the device (zeroconf protocol or an application that figures out the IP), if OpenWrt does not provide mdns in the default image then I think we should not switch to DHCP IP, as it only makes connecting the first time to the device more annoying.

I hope I have cleared up my view of this.

**Comment by diizzyy** [comment]
They're doing it because it's convenient, you plug in your device and it's accessible without changing anything in most cases except when there's no DHCP server, leases locked my MAC address etc. I think your average user would be much happier in that regard to retain network access while accessing their device to configure it.

I think the whole "it's hard" argument can be debunked by looking at pretty much everything else and far from everything uses avahi or mdns. If you read further regarding that D-Link link they even mention that can you also log into your router.
https://docs.armbian.com/User-Guide_Getting-Started/#how-to-set-fixed-ip - It doesn't really need to be much more advanced than that as far as information goes, possibly mention that hostname is going to be xxx.

**Comment by neheb** [comment]
ACK.

**Comment by diizzyy** [comment]
I just find the whole argument a bit strange as OpenWrt is primarily aimed as a networking oriented distribution...

**Comment by bobafetthotmail** [comment]
> I just find the whole argument a bit strange as OpenWrt is primarily aimed as a networking oriented distribution...

Might as well remove LuCi then, why use a limited web interface when you can ssh in and change all possible configuration text files or scripts with vi? Many advanced users don't even bother to include it in their builds.

It should be in everyone's best interest to keep the barrier to entry as low as possible, and I should not need to explain why.

**Comment by diizzyy** [comment]
Let's just leave it at that because this is getting out of hand...

**Comment by diizzyy** [comment]
What's the general stance on this? Will it ever be considered or will it just be a waste of time?

**Comment by jow-** [comment]
I could imagine that a middle way could be less controversial:

- Keep static ip
- Disable DHCP server
- Preconfigure DHCP client in addition to static IP

**Comment by arvati** [comment]
@diizzyy what I prefer would be:
* dhcp for one ethernet port device
* static for 'none' or 'two or more' ethernet port device

And another change off topic:  devices with none ethernet ports should have wifi enabled by default

**Comment by diizzyy** [comment]
@jow- 
You mean like having prewritten line in the config?

**Comment by cshoredaniel** [comment]
I have to say that in ar71xx I regret having originally configured the board support to use DHCP on a single device, for the simple reason that unlike commercial offerings OpenWrt does not broadcast wifi so that unlike what they are aiming for (zeroconf) you don't get some kind of AP with a Wifi on the LAN 'for free' AND it's a PITA for actually going in and configuring the device after flashing it (because you have to find the bloody address of the device; and if you don't control; can't query, the DHCP server it's even worse than just having to go through the extra hoops of looking on the DHCP server for the address that the device got.

@blogic did merge my ath79 port of the 'PowerCloud Systems CAP324' with static IP rather than DHCP, and also merge my ar71xx 'errata' for CAP324 including the individual commit in which I moved it back to static IP, so I'm curious what his and @nbd168 votes would be.

I personally think that people who want non-static behaviour are probably using non-stock OpenWrt anyway and therefore ought to be fully capable of provisioning to their preference.

**Comment by cshoredaniel** [comment]
@bobafetthotmail for experienced users the Netgear thing actually sucks because you *have* to connect on the router's lan as DHCP client for it work.  I have a nice little bench setup where I plug in the DUT/DTC (Device-Under-Test/Device-To-Configure) into a subnet that is masq'd going 'into' the network (so all devices connection from the lan and forwarding to bench appear to bench as the bench subnet, e.g. 192.168.1.x for OpenWrt standard stuff).  I can use LuCI or SSH to my heart's content to a device addressed as e.g. 192.168.1.1 without having to mess with my PC or laptop configuration.  Admittedly that's an advanced usage, but even for more ordinary users, in the absence of a correctly configured device (and NO PASSWORD by default), I think making sure users actually configure their device is actually a good idea.  Again if you are dealing with devices where there is a default password and/or Wifi you're not using a stock OpenWrt image.

As for @jow- suggestion for both static and DHCP, I'm not sure what I think of that.  I'm not sure of the consequences (or benefits). 

I'm really not clear on what the *benefit* of DHCP on single port devices is on *unmodified* OpenWrt.

**Comment by cshoredaniel** [comment]
I was going to just ping @mkresin  on this, but really this discussion should move to the openwrt-devel mailing list so the voting members have more visibility on the it.

**Comment by bobafetthotmail** [comment]
> for experienced users the Netgear thing actually sucks because you have to connect on the router's lan as DHCP client for it work.

I can't speak for Netgear's own thing as I never really tested that in a multi-router environment, but I'm pretty sure that Zeroconf servers available in OpenWrt (and Linux for that matter) like Avahi or mDNS work fine as long as you are both in the same subnet, it's not necessary to be a dhcp client or for the zeroconf server to be installed on the router/gateway.

**Comment by diizzyy** [comment]
@hauke @jow- @blogic 
How should we proceed?

**Comment by jow-** [comment]
Still not convinced that switching solely to DHCP is a good idea. How are users supposed to discover their device?

**Comment by jow-** [comment]
Well if we play the tech savvy card then there is no need to switch to DHCP in the first place, as the tech savvy will always be able to configure DHCP themselves.

Regarding the complaints; I doubt hardly anyone even notices this PR here. It should be probably discussed on the development mailing list and/or the forum.

**Comment by diizzyy** [comment]
As far as complaints goes, I meant that at least I can't find any about using DHCP instead of a static IP either on the lists or the forum(s)? It's not like they switched to DHCP recently...

Attaching a device with 192.168.1.1 as static IP is more intrusive than using DHCP in most cases...
Anyhow, if I import one of the above would that be satisfactory?

**Comment by cshoredaniel** [comment]
I'm with @jow- ; this needs discussed on ML.  I know @diizzyy has thing against the ML but this is for bleeding 'core' stuff already.  No excuse for not discussing on list.

**Comment by cshoredaniel** [comment]
@diizzyy Apologies on the assuming about your opinion of the ML (and I know I've been guilty of making guesses about other's opinions; will work on rectifying that).  Although I do wonder, why exactly do protest using the ML?  It seems odd to me, particularly where wider communication is needed.

**Comment by diizzyy** [comment]
I've packaged a tiny mdns daemon to help users find their device
https://github.com/openwrt/openwrt/pull/1339

**Comment by cshoredaniel** [comment]
I appreciate the effort you're putting into making this work, and I hate to rain on the parade, but does this do anything useful for Windows users?  Last I checked Windows wants WSD and avahi-style stuff doesn't do anything useful (this is one of those 'why I hate MS' deals).  I don't even know of any *useful* third party support, although that could simply not having looked terribly hard (I rarely use Windows these days, but for a lot of users the opposite is true).

**Comment by diizzyy** [comment]
Windows 10 comes with mDNS support, I have to admit that I haven't tried it myself yet but Windows 7 and Bonjour is confirmed working :-)

**Comment by diizzyy** [comment]
@mhei 
Good input, Windows 7 is however sadly dying and footprint is quite large which probably is a showstopper.
Perhaps we can utilize wssd2 (LLMNR) instead to cover "all" bases? 16kbyte (ipk) without any deps

**Comment by cshoredaniel** [comment]
@diizzyy Maybe I'm overly cynical, but my suspicion is that when it comes time to try and actually get this committed. it'll get NAK'd in part because the lack of meaningful argumentation and discussion on the ML.  Maybe OpenWrt core has changed that way, but if this gets committed anytime in the near future I'd owe you a beverage of your choice, if I could get it to you.

I haven't made up my mind whether I now for or against the proposal, but then I'm not who you have to convince, and from what I've seen most of the actual committers are not very communicative, most of the time.  Days jobs and all that I guess, but be prepared for frustration if this is über important to you.

**Comment by diizzyy** [comment]
@cshoredaniel 
I hear you, I just wanted to do something consistent but I wont waste my time if nobody cares at all in the end. Sadly that seems to be the case :-/

**Pull request closed without merging**
