### PR TITLE
add support for GL-AR300M Nand dual flash support

### PR DESCRIPTION
**Pull request by hanetzer**
Currently working on porting/rebasing/sanitizing/etc the vendor support for the
nand side of the gl-ar300m, based on domino-team/lede-ar300m@333ccb0 and
onward. I've rebased it and cleaned it up as much as possible without messing
with its code too much yet, but the ath79_spinand.c driver will require some
work in porting it from 4.4 to 4.9's kernel mtd/nand api.

Mostly opening this as a place of discussion, visibility and q&a.

Original PR: https://github.com/lede-project/source/pull/1570

### CODE REVIEW

**Comment by YakBizzarro** [comment]
What's missing exactly to get this pull-request merged?

**Comment by rotanid** [comment]
@YakBizzarro probably someone with more free time to check it.

**Comment by hanetzer** [comment]
@YakBizzarro @rotanid yeah, that's what it generally amounts to. I think perhaps my ubi params
are not quite right, but they 'work' (nand is a tricky beast). Also should contact the company and
see if I can get a proper name for the 'FW Device' chip, as I think that was just a generic placeholder
name they used in order to get it running.

**Comment by Cjcr** [comment]
No progress still with the NAND thing? :-( Very dissapointed

Meanwhile, how we can use the last Openwrt version (trunk) in this AR300M? I tried to update from LuCi (using the GL-Inet original firmware) with no results. It shows an error on the firmware file ... I also tried from uBoot, but It does nothing. What I should do to update it even without using NAND?

**Comment by rotanid** [comment]
@Cjcr i guess you have to put the nand-switch in the "correct" position.
for me that meant either removing the case or making the hole bigger to allow the switch to use the "correct" position

**Comment by hanetzer** [comment]
@rotanid @YakBizzarro @Cjcr I believe I've located a proper datasheet for the
nand chip in question, appears to be from Paragon, which seems to have been
absorbed by XTX Technology. Doing a bit of research to hopefully get this done
in a more accurate manner.

**Comment by Cjcr** [comment]
@hanetzer yes, that seems: https://github.com/gl-inet/lede-17.01/commit/5ea720b7da15d832417eb9351ac0f4ca7805d14e

We hope that we can have this merge in master trunk soon 👍

**Comment by hanetzer** [comment]
There is also the probability that the ar71xx targets are kinda frozen
until ath79 is usable. This would basically entail a conversion of every `target/linux/ar71xx/files/arch/mips/ath79/mach-$board.c` file into a `target/linux/ath79/dts/$BOARD.dts`, Would make things a tad bit
easier and the kernel image a tad bit smaller, which may make some
otherwise unsupportable devices supportable.

**Comment by blogic** [comment]
already part of ath79

**Pull request closed without merging**
