### PR TITLE
fakeroot: revert to 1.29 (debian "testing" release)

### PR DESCRIPTION
**Pull request by mcprat**
ping @PolynomialDivision @dangowrt 

I've been dealing with this for a while and getting sick of it, and I can't even find the fix.
I recommend that fakeroot (maybe some others too) stick with the "testing" releases from debian.

Fakeroot 1.30.1 broke building on certain hosts (32-bit archs).

As of 2023-01-10, this was apparently fixed in source code, however, the version is still 1.30.1 (patch release), so the old binaries are removed from the repository and replaced, but the source provided by the repository remains the same.

Furthermore, there are some complicated issues blocking the "testing" release from being bumped to a 1.30.x version.

Considering all of this, it would likely be better for this package to follow the "testing" release instead of the "unstable" release, which is still 1.29-1, so revert to that.

Link: https://bugs.debian.org/1023286
Link: https://tracker.debian.org/news/1407613/accepted-fakeroot-1301-11-source-into-unstable/
Link: https://qa.debian.org/excuses.php?package=fakeroot
Link: https://bugs.debian.org/1027803
Signed-off-by: Michael Pratt <mcpratt@pm.me>

### CODE REVIEW

**Comment by mpratt14** [comment]
seems like the problem is the fix actually, because the "fix" had to be fixed

but when I look at the commit history, the difference between the versions seems unrelated

```
fakeroot (1.30.1-1) unstable; urgency=medium

  * New upstream version.
    - fixes and extends time64 support to fstatat64.
      closes: #1023286.

 -- Clint Adams <clint@debian.org>  Thu, 03 Nov 2022 15:04:55 -0400

fakeroot (1.30-1) unstable; urgency=medium

  * New upstream version.
    - tries to cope with time64 on 32-bit architectures.
      closes: #1023286.
  * Drop kludge for glibc 2.33.

 -- Clint Adams <clint@debian.org>  Wed, 02 Nov 2022 20:17:56 -0400
```

**Comment by neheb** [comment]
The fix is to revert the most recent "fix":

```
Subject: [PATCH] Revert "Wrap time64 functions"

This reverts commit 3ff3bab429efbfc0e5b4a7941ae6beb8e17684b7.
```

**Comment by mpratt14** [comment]
@PolynomialDivision is there a specific reason we need version 1.30+ ? do you need to see the build error?

**Comment by hauke** [comment]
I do not fully get the problem.
Was the fakeroot_1.30.1.orig.tar.gz file changed or removed from the debian mirror?
The file is still there: http://deb.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.30.1.orig.tar.gz 
Do you have problems using fakeroot on 32 bit build systems?
I think the fix for 32 bit build systems is only included in fakeroot 1.30.1. 
It include these changes: 
https://salsa.debian.org/clint/fakeroot/-/commit/4a946cdc5cba202f888deb4ad831b4a305df7978
https://salsa.debian.org/clint/fakeroot/-/commit/3ff3bab429efbfc0e5b4a7941ae6beb8e17684b7

**Comment by neheb** [comment]
The last needs to be reverted.

**Comment by mpratt14** [comment]
> Was the fakeroot_1.30.1.orig.tar.gz file changed or removed from the debian mirror?

the problem actually, is that it was not changed or removed, yet there is a new binary release (with the same version base)

as far as I can tell, the current source code on salsa.debian.org does not even reflect this new hotfix version so I cannot even tell what change they made to "fix" the fix which broke building on my system (armhf 32-bit)

there used to be binaries for version `1.30.1-1` and those where removed and replaced by `1.30.1-1.1` because of this problem, but the source code tarball remains the same

because of the other issues they are citing that blocks moving unstable release to testing release in my opinion we should just revert until they figure out the mess they made in source

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision is there a specific reason we need version 1.30+ ? do you need to see the build error?

No there is no specific reason.

**Comment by mpratt14** [comment]
> replaced by `1.30.1-1.1` because of this problem

ok I was wrong about this detail, I found the changelog and diff (which is still not in the maintainer's repo)

https://metadata.ftp-master.debian.org/changelogs/main/f/fakeroot/fakeroot_1.30.1-1.1_changelog
https://sources.debian.org/patches/fakeroot/1.30.1-1.1/

**Comment by lovehackintosh** [comment]
Does PR #11986 fix this issue?

**Comment by mpratt14** [comment]
> Does PR #11986 fix this issue?

ah it's good to hear they did a new release

bumping to 1.31 should fix the problem, I will test after dinner

**Comment by neheb** [comment]
it does not.

I've already mentioned the solution.

**Comment by mpratt14** [comment]
like Rosen said, the problem is still there

also there are more issues even if building was resolved
see https://bugs.debian.org/1030638


this is the actual build error
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/media/SDStorage/builds/github-openwrt/openwrt/staging_dir/host/include -O2 -I/media/SDStorage/builds/github-openwrt/openwrt/staging_dir/host/include -MT libfakeroot.lo -MD -MP -MF .deps/libfakeroot.Tpo -c libfakeroot.c  -fPIC -DPIC -o .libs/libfakeroot.o
In file included from libfakeroot.c:274:
wrapped.h:236:40: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'LSTAT64_TIME64_ARG'
  236 | extern int (*NEXT_LSTAT64_TIME64_NOARG)LSTAT64_TIME64_ARG(int ver, const char *file_name, struct stat64 *buf);
      |                                        ^~~~~~~~~~~~~~~~~~
wrapped.h:237:39: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'STAT64_TIME64_ARG'
  237 | extern int (*NEXT_STAT64_TIME64_NOARG)STAT64_TIME64_ARG(int ver, const char *file_name, struct stat64 *buf);
      |                                       ^~~~~~~~~~~~~~~~~
wrapped.h:238:40: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'FSTAT64_TIME64_ARG'
  238 | extern int (*NEXT_FSTAT64_TIME64_NOARG)FSTAT64_TIME64_ARG(int ver, int fd, struct stat64 *buf);
      |                                        ^~~~~~~~~~~~~~~~~~
wrapped.h:239:42: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'FSTATAT64_TIME64_ARG'
  239 | extern int (*NEXT_FSTATAT64_TIME64_NOARG)FSTATAT64_TIME64_ARG(int ver, int dir_fd, const char *path, struct stat64 *buf, int flags);
      |                                          ^~~~~~~~~~~~~~~~~~~~
In file included from libfakeroot.c:275:
wraptmpf.h:636:24: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'LSTAT64_TIME64_ARG'
  636 | int TMP_LSTAT64_TIME64 LSTAT64_TIME64_ARG(int ver, const char *file_name, struct stat64 *buf){
      |                        ^~~~~~~~~~~~~~~~~~
wraptmpf.h:641:23: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'STAT64_TIME64_ARG'
  641 | int TMP_STAT64_TIME64 STAT64_TIME64_ARG(int ver, const char *file_name, struct stat64 *buf){
      |                       ^~~~~~~~~~~~~~~~~
wraptmpf.h:646:24: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'FSTAT64_TIME64_ARG'
  646 | int TMP_FSTAT64_TIME64 FSTAT64_TIME64_ARG(int ver, int fd, struct stat64 *buf){
      |                        ^~~~~~~~~~~~~~~~~~
wraptmpf.h:651:26: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'FSTATAT64_TIME64_ARG'
  651 | int TMP_FSTATAT64_TIME64 FSTATAT64_TIME64_ARG(int ver, int dir_fd, const char *path, struct stat64 *buf, int flags){
      |                          ^~~~~~~~~~~~~~~~~~~~
In file included from libfakeroot.c:276:
wrapdef.h:236:33: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'LSTAT64_TIME64_ARG'
  236 | int (*NEXT_LSTAT64_TIME64_NOARG)LSTAT64_TIME64_ARG(int ver, const char *file_name, struct stat64 *buf)=TMP_LSTAT64_TIME64;
      |                                 ^~~~~~~~~~~~~~~~~~
wrapdef.h:237:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'STAT64_TIME64_ARG'
  237 | int (*NEXT_STAT64_TIME64_NOARG)STAT64_TIME64_ARG(int ver, const char *file_name, struct stat64 *buf)=TMP_STAT64_TIME64;
      |                                ^~~~~~~~~~~~~~~~~
wrapdef.h:238:33: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'FSTAT64_TIME64_ARG'
  238 | int (*NEXT_FSTAT64_TIME64_NOARG)FSTAT64_TIME64_ARG(int ver, int fd, struct stat64 *buf)=TMP_FSTAT64_TIME64;
      |                                 ^~~~~~~~~~~~~~~~~~
wrapdef.h:239:35: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'FSTATAT64_TIME64_ARG'
  239 | int (*NEXT_FSTATAT64_TIME64_NOARG)FSTATAT64_TIME64_ARG(int ver, int dir_fd, const char *path, struct stat64 *buf, int flags)=TMP_FSTATAT64_TIME64;
      |                                   ^~~~~~~~~~~~~~~~~~~~
In file included from communicate.h:19,
                 from libfakeroot.c:65:
config.h:370:36: error: 'next___astat64_time64' undeclared here (not in a function)
  370 | #define NEXT_LSTAT64_TIME64_NOARG  next___astat64_time64
      |                                    ^~~~~~~~~~~~~~~~~~~~~
wrapstruct.h:237:14: note: in expansion of macro 'NEXT_LSTAT64_TIME64_NOARG'
  237 |   {(void(*))&NEXT_LSTAT64_TIME64_NOARG, WRAP_LSTAT64_TIME64_QUOTE},
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~
config.h:366:36: error: '__astat64_time64' undeclared here (not in a function)
  366 | #define WRAP_LSTAT64_TIME64_QUOTE  __astat64_time64
      |                                    ^~~~~~~~~~~~~~~~
wrapstruct.h:237:41: note: in expansion of macro 'WRAP_LSTAT64_TIME64_QUOTE'
  237 |   {(void(*))&NEXT_LSTAT64_TIME64_NOARG, WRAP_LSTAT64_TIME64_QUOTE},
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
config.h:378:38: error: '__astatat64_time64' undeclared here (not in a function)
  378 | #define WRAP_FSTATAT64_TIME64_QUOTE  __astatat64_time64
      |                                      ^~~~~~~~~~~~~~~~~~
wrapstruct.h:240:43: note: in expansion of macro 'WRAP_FSTATAT64_TIME64_QUOTE'
  240 |   {(void(*))&NEXT_FSTATAT64_TIME64_NOARG, WRAP_FSTATAT64_TIME64_QUOTE},
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
libfakeroot.c:2639:25: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'LSTAT64_TIME64_ARG'
 2639 | int WRAP_LSTAT64_TIME64 LSTAT64_TIME64_ARG(int ver,
      |                         ^~~~~~~~~~~~~~~~~~
libfakeroot.c:2658:24: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'STAT64_TIME64_ARG'
 2658 | int WRAP_STAT64_TIME64 STAT64_TIME64_ARG(int ver,
      |                        ^~~~~~~~~~~~~~~~~
libfakeroot.c:2676:25: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'FSTAT64_TIME64_ARG'
 2676 | int WRAP_FSTAT64_TIME64 FSTAT64_TIME64_ARG(int ver,
      |                         ^~~~~~~~~~~~~~~~~~
libfakeroot.c:2694:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'FSTATAT64_TIME64_ARG'
 2694 | int WRAP_FSTATAT64_TIME64 FSTATAT64_TIME64_ARG(int ver,
      |                           ^~~~~~~~~~~~~~~~~~~~
make[5]: *** [Makefile:669: libfakeroot.lo] Error 1
make[5]: Leaving directory '/media/SDStorage/builds/github-openwrt/openwrt/build_dir/host/fakeroot-1.31'
make[4]: *** [Makefile:691: all-recursive] Error 1
make[4]: Leaving directory '/media/SDStorage/builds/github-openwrt/openwrt/build_dir/host/fakeroot-1.31'
make[3]: *** [Makefile:460: all] Error 2
make[3]: Leaving directory '/media/SDStorage/builds/github-openwrt/openwrt/build_dir/host/fakeroot-1.31'
make[2]: *** [Makefile:33: /media/SDStorage/builds/github-openwrt/openwrt/build_dir/host/fakeroot-1.31/.built] Error 2
make[2]: Leaving directory '/media/SDStorage/builds/github-openwrt/openwrt/tools/fakeroot'
time: tools/fakeroot/compile#24.46#11.76#53.62
    ERROR: tools/fakeroot failed to build.
make[1]: *** [tools/Makefile:219: tools/fakeroot/compile] Error 1
make[1]: Leaving directory '/media/SDStorage/builds/github-openwrt/openwrt'
make: *** [/media/SDStorage/builds/github-openwrt/openwrt/include/toplevel.mk:231: tools/fakeroot/compile] Error 2

```

**Pull request merged**
