### PR TITLE
x86: update kernel 5.4 config

### PR DESCRIPTION
**Pull request by bobafetthotmail**
the last kernel update done with commit
500a02bc29b93907921fee727400d5f208e1fb85
placed most of the updated config only
in the x86_64 target.

Move the options needed by the other
targets too in the x86 base config,
and add an additional option needed
by those targets.

Signed-off-by: Alberto Bursi <bobafetthotmail@gmail.com>

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
@hauke @xback 

most of the config options in the commit I mentioned are needed by other x86 targets as well.

**Comment by bobafetthotmail** [comment]
ping @hauke this is annoying for people compiling for non-64bit x86 targets as it stops build to ask for new kernel options.

Can anyone please merge this?

Or at the very least tell me how the buildbots can just not care and build snapshots for these targets anyway?

**Comment by adrianschmutzler** [comment]
> Or at the very least tell me how the buildbots can just not care and build snapshots for these targets anyway?

Have tried building with the config.buildinfo from there: https://downloads.openwrt.org/snapshots/targets/x86/generic/ ?

**Comment by bobafetthotmail** [comment]
Yeah, I enabled CONFIG_BUILDBOT, CONFIG_TARGET_MULTI_PROFILE, CONFIG_TARGET_ALL_PROFILES and CONFIG_TARGET_PER_DEVICE_ROOTFS and CONFIG_DEVEL but didn't make much difference.

Other options in there are (should be) irrelevant, I'm not building with all kmods or all packages or whatever.

**Comment by adrianschmutzler** [comment]
So, most probably something selected by one of the additional kmods or packages will make it work on build-bots. That doesn't mean that your fix is wrong, but would answer your question why buildbots don't fail :-)

**Comment by bobafetthotmail** [comment]
I really don't think it's the case, I did have a look at the kernel options back when I made the PR and no other package or kmod requires or adds these things, all their dependencies are set in the kernel config as most basic stuff for X86.

A quick example, what package or additional config option in OpenWrt could possibly be causing the selection of
**Intel HDCP2.2 services of ME Interface (INTEL_MEI_HDCP)** ?
That's something completely esoteric about supporting HDCP2.2 anti-piracy video protocol on HDMI port on Intel systems that have the ME aka Management Engine.

At the moment I'm suspecting the buildbots are just doing tricks to give infinite " " response to any such interactive question from kernel config.

Like this
```
make << EOF




EOF
```
this trick will respond with "newline" for 4 times, I can make this hundreds of newlines long, and this will catch and respond to a reasonably large amount of interactive kernel config options.

But quite frankly it's disgraceful that I need to hack around like this.

@jow do you know if buildbots are doing something like I said? If so, can that be removed so it's easier to get someone to merge kernel config fixes like this?

**Comment by ynezz** [comment]
Here you can see the steps https://git.openwrt.org/?p=buildbot.git;a=blob;f=phase1/master.cfg#l834 run by buildbots, [here](http://buildbot.openwrt.org/master/images/builders/x86%2Flegacy/builds/319/steps/kmods/logs/stdio) you can study the output of kernel .config generation, so you can check and confirm, that there is no such workaround for x86/legacy, the build would simply fail on all targets without difference if the configs would be wrong.

**Comment by ynezz** [comment]
I've just started x86/legacy build on [GitLab CI](https://gitlab.com/ynezz/openwrt/-/jobs/552958861) which is [using almost](https://gitlab.com/ynezz/openwrt-ci/-/blob/master/openwrt-ci/target-build.mk#L33) the same build steps as on buildbots so let's see how this finishes.

**Comment by ynezz** [comment]
So perhaps it's now your turn to provide your .config and Git hash combination which fails for you.

**Comment by bobafetthotmail** [comment]
oh look at that buildbot log. It says "**Error in reading or end of file.**" after each of the options that are missing from the kernel config, and then it keeps going on.
It's effectively doing a "workaround" of its own will (due to a bug I guess).

I would not say that is normal, but I don't know enough of buildbot code to know why it's doing it.

```
*
* Restart config...
*
*
* Misc devices
*
Analog Devices Digital Potentiometers (AD525X_DPOT) [N/m/y/?] n
Dummy IRQ handler (DUMMY_IRQ) [N/m/y/?] n
Device driver for IBM RSA service processor (IBM_ASM) [N/m/y/?] n
Sensable PHANToM (PCI) (PHANTOM) [N/m/y/?] n
TI Flash Media interface support (TIFM_CORE) [N/m/y/?] n
Integrated Circuits ICS932S401 (ICS932S401) [N/m/y/?] n
Enclosure Services (ENCLOSURE_SERVICES) [N/m/y/?] n
Channel interface driver for the HP iLO processor (HP_ILO) [N/m/y/?] n
Medfield Avago APDS9802 ALS Sensor module (APDS9802ALS) [N/m/y/?] n
Intersil ISL29003 ambient light sensor (ISL29003) [N/m/y/?] n
Intersil ISL29020 ambient light sensor (ISL29020) [N/m/y/?] n
Taos TSL2550 ambient light sensor (SENSORS_TSL2550) [N/m/y/?] n
BH1770GLC / SFH7770 combined ALS - Proximity sensor (SENSORS_BH1770) [N/m/y/?] n
APDS990X combined als and proximity sensors (SENSORS_APDS990X) [N/m/y/?] n
Honeywell HMC6352 compass (HMC6352) [N/m/y/?] n
Dallas DS1682 Total Elapsed Time Recorder with Alarm (DS1682) [N/m/y/?] n
Intel EG20T PCH/LAPIS Semicon IOH(ML7213/ML7223/ML7831) PHUB (PCH_PHUB) [N/m/y/?] n
Lattice ECP3 FPGA bitstream configuration via SPI (LATTICE_ECP3_CONFIG) [N/m/y/?] n
Generic on-chip SRAM driver (SRAM) [N/y/?] n
PCI Endpoint Test driver (PCI_ENDPOINT_TEST) [N/m/y/?] n
Xilinx SDFEC 16 (XILINX_SDFEC) [N/m/y/?] n
pvpanic device support (PVPANIC) [N/m/y/?] n
ENE CB710/720 Flash memory card reader support (CB710_CORE) [N/m/y/?] n
STMicroeletronics LIS3LV02Dx three-axis digital accelerometer (I2C) (SENSORS_LIS3_I2C) [N/m/y/?] n
Altera FPGA firmware download module (ALTERA_STAPL) [N/m/y/?] n
Intel Management Engine Interface (INTEL_MEI) [N/m/y/?] n
ME Enabled Intel Chipsets (INTEL_MEI_ME) [N/m/y/?] n
Intel Trusted Execution Environment with ME Interface (INTEL_MEI_TXE) [N/m/y/?] n
Intel HDCP2.2 services of ME Interface (INTEL_MEI_HDCP) [N/m/y/?] (NEW) 
Error in reading or end of file.

VMware VMCI Driver (VMWARE_VMCI) [N/m/y/?] n
Line Echo Canceller support (ECHO) [M/n/y/?] m
Alcor Micro/Alcor Link PCI-E card reader (MISC_ALCOR_PCI) [N/m/y/?] n
Realtek PCI-E card reader (MISC_RTSX_PCI) [N/m/y/?] n
Realtek USB card reader (MISC_RTSX_USB) [N/m/y/?] n
HabanaAI accelerators (habanalabs) (HABANA_AI) [N/m/y/?] n
*
* SCSI low-level drivers
*
SCSI low-level drivers (SCSI_LOWLEVEL) [Y/n/?] y
  iSCSI Initiator over TCP/IP (ISCSI_TCP) [N/m/y/?] n
  iSCSI Boot Sysfs Interface (ISCSI_BOOT_SYSFS) [N/m/y/?] n
  Chelsio T3 iSCSI support (SCSI_CXGB3_ISCSI) [N/m/y/?] n
  Chelsio T4 iSCSI support (SCSI_CXGB4_ISCSI) [N/m/y/?] n
  QLogic NetXtreme II iSCSI support (SCSI_BNX2_ISCSI) [N/m/y/?] n
  Emulex 10Gbps iSCSI - BladeEngine 2 (BE2ISCSI) [N/m/y/?] n
  3ware 5/6/7/8xxx ATA-RAID support (BLK_DEV_3W_XXXX_RAID) [N/m/y/?] n
  HP Smart Array SCSI driver (SCSI_HPSA) [N/m/y/?] n
  3ware 9xxx SATA-RAID support (SCSI_3W_9XXX) [N/m/y/?] n
  3ware 97xx SAS/SATA-RAID support (SCSI_3W_SAS) [N/m/y/?] n
  ACARD SCSI support (SCSI_ACARD) [N/m/y/?] n
  Adaptec AHA152X/2825 support (SCSI_AHA152X) [N/m/y/?] n
  Adaptec AHA1542 support (SCSI_AHA1542) [N/m/y/?] n
  Adaptec AACRAID support (SCSI_AACRAID) [N/m/y/?] n
  Adaptec AIC7xxx Fast -> U160 support (SCSI_AIC7XXX) [N/m/y/?] n
  Adaptec AIC79xx U320 support (SCSI_AIC79XX) [N/m/y/?] n
  Adaptec AIC94xx SAS/SATA support (SCSI_AIC94XX) [N/m/y/?] n
  Marvell 88SE64XX/88SE94XX SAS/SATA support (SCSI_MVSAS) [M/n/y/?] m
    Compile in debug mode (SCSI_MVSAS_DEBUG) [N/y/?] n
    Support for interrupt tasklet (SCSI_MVSAS_TASKLET) [N/y/?] n
  Marvell UMI driver (SCSI_MVUMI) [N/m/y/?] n
  Adaptec I2O RAID support  (SCSI_DPT_I2O) [N/m/y/?] n
  AdvanSys SCSI support (SCSI_ADVANSYS) [N/m/y/?] n
  ARECA (ARC11xx/12xx/13xx/16xx) SATA/SAS RAID Host Adapter (SCSI_ARCMSR) [N/m/y/?] n
  ATTO Technology's ExpressSAS RAID adapter driver (SCSI_ESAS2R) [N/m/y/?] n
  LSI Logic New Generation RAID Device Drivers (MEGARAID_NEWGEN) [N/y/?] n
  LSI Logic Legacy MegaRAID Driver (MEGARAID_LEGACY) [N/m/y/?] n
  LSI Logic MegaRAID SAS RAID Module (MEGARAID_SAS) [N/m/y/?] n
  LSI MPT Fusion SAS 3.0 & SAS 2.0 Device Driver (SCSI_MPT3SAS) [N/m/y/?] n
  Legacy MPT2SAS config option (SCSI_MPT2SAS) [N/m/y/?] n
  Microsemi PQI Driver (SCSI_SMARTPQI) [N/m/y/?] n
  Universal Flash Storage Controller Driver Core (SCSI_UFSHCD) [N/m/y/?] n
  HighPoint RocketRAID 3xxx/4xxx Controller support (SCSI_HPTIOP) [N/m/y/?] n
  BusLogic SCSI support (SCSI_BUSLOGIC) [N/m/y/?] n
  Mylex DAC960/DAC1100 PCI RAID Controller (Block Interface) (SCSI_MYRB) [N/m/y/?] n
  Mylex DAC960/DAC1100 PCI RAID Controller (SCSI Interface) (SCSI_MYRS) [N/m/y/?] n
  VMware PVSCSI driver support (VMWARE_PVSCSI) [N/m/y/?] n
  Cisco SNIC Driver (SCSI_SNIC) [N/m/y/?] n
  DMX3191D SCSI support (SCSI_DMX3191D) [N/m/y/?] n
  Future Domain TMC-3260/AHA-2920A PCI SCSI support (SCSI_FDOMAIN_PCI) [N/m/y/?] n
  Future Domain 16xx ISA SCSI support (SCSI_FDOMAIN_ISA) [N/m/y/?] (NEW) 
Error in reading or end of file.

  Intel/ICP (former GDT SCSI Disk Array) RAID Controller support (SCSI_GDTH) [N/m/y/?] n
  Intel(R) C600 Series Chipset SAS Controller (SCSI_ISCI) [N/m/y/?] n
  Generic NCR5380/53c400 SCSI ISA card support (SCSI_GENERIC_NCR5380) [N/m/y/?] n
  IBM ServeRAID support (SCSI_IPS) [N/m/y/?] n
  Initio 9100U(W) support (SCSI_INITIO) [N/m/y/?] n
  Initio INI-A100U2W support (SCSI_INIA100) [N/m/y/?] n
  IOMEGA parallel port (ppa - older drives) (SCSI_PPA) [N/m/?] n
  IOMEGA parallel port (imm - newer drives) (SCSI_IMM) [N/m/?] n
  Promise SuperTrak EX Series support (SCSI_STEX) [N/m/y/?] n
  SYM53C8XX Version 2 SCSI support (SCSI_SYM53C8XX_2) [N/m/y/?] n
  IBM Power Linux RAID adapter support (SCSI_IPR) [N/m/y/?] n
  Qlogic FAS SCSI support (SCSI_QLOGIC_FAS) [N/m/y/?] n
  Qlogic QLA 1240/1x80/1x160 SCSI support (SCSI_QLOGIC_1280) [N/m/y/?] n
  QLogic ISP4XXX and ISP82XX host adapter family support (SCSI_QLA_ISCSI) [N/m/y/?] n
  Tekram DC395(U/UW/F) and DC315(U) SCSI support (SCSI_DC395x) [N/m/y/?] n
  Tekram DC390(T) and Am53/79C974 SCSI support (new driver) (SCSI_AM53C974) [N/m/y/?] n
  Workbit NinjaSCSI-32Bi/UDE support (SCSI_NSP32) [N/m/y/?] n
  Western Digital WD7193/7197/7296 support (SCSI_WD719X) [N/m/y/?] n
  SCSI debugging host and device simulator (SCSI_DEBUG) [N/m/y/?] n
  PMC SIERRA Linux MaxRAID adapter support (SCSI_PMCRAID) [N/m/y/?] n
  PMC-Sierra SPC 8001 SAS/SATA Based Host Adapter driver (SCSI_PM8001) [N/m/y/?] n
*
* I2C Hardware Bus support
*
*
* PC SMBus host controller drivers
*
ALI 1535 (I2C_ALI1535) [N/m/y/?] n
ALI 1563 (I2C_ALI1563) [N/m/y/?] n
ALI 15x3 (I2C_ALI15X3) [N/m/y/?] n
AMD 756/766/768/8111 and nVidia nForce (I2C_AMD756) [N/m/y/?] n
AMD 8111 (I2C_AMD8111) [N/m/y/?] n
AMD MP2 PCIe (I2C_AMD_MP2) [N/m/y/?] (NEW) 
Error in reading or end of file.

Intel 82801 (ICH/PCH) (I2C_I801) [M/n/y/?] m
Intel SCH SMBus 1.0 (I2C_ISCH) [N/m/y/?] n
Intel iSMT SMBus Controller (I2C_ISMT) [N/m/y/?] n
Intel PIIX4 and compatible (ATI/AMD/Serverworks/Broadcom/SMSC) (I2C_PIIX4) [M/n/y/?] m
Nvidia nForce2, nForce3 and nForce4 (I2C_NFORCE2) [N/m/y/?] n
NVIDIA GPU I2C controller (I2C_NVIDIA_GPU) [N/m/y/?] n
SiS 5595 (I2C_SIS5595) [N/m/y/?] n
SiS 630/730/964 (I2C_SIS630) [N/m/y/?] n
SiS 96x (I2C_SIS96X) [N/m/y/?] n
VIA VT82C586B (I2C_VIA) [N/m/y/?] n
VIA VT82C596/82C686/82xx and CX700/VX8xx/VX900 (I2C_VIAPRO) [N/m/y/?] n
*
* ACPI drivers
*
SMBus Control Method Interface (I2C_SCMI) [N/m/y/?] n
*
* I2C system bus drivers (mostly embedded / system-on-chip)
*
Synopsys DesignWare Platform (I2C_DESIGNWARE_PLATFORM) [N/m/y/?] n
Synopsys DesignWare PCI (I2C_DESIGNWARE_PCI) [N/m/y/?] n
Intel EG20T PCH/LAPIS Semicon IOH(ML7213/ML7223/ML7831) I2C (I2C_EG20T) [N/m/y/?] n
EMMA Mobile series I2C adapter (I2C_EMEV2) [N/m/y/?] n
OpenCores I2C Controller (I2C_OCORES) [N/m/y/?] n
PCA9564/PCA9665 as platform device (I2C_PCA_PLATFORM) [N/m/y/?] n
Simtec Generic I2C interface (I2C_SIMTEC) [N/m/y/?] n
Xilinx I2C Controller (I2C_XILINX) [N/m/y/?] n
*
* External I2C/SMBus adapter drivers
*
Diolan U2C-12 USB adapter (I2C_DIOLAN_U2C) [N/m/y/?] n
Parallel port adapter (I2C_PARPORT) [N/m/?] n
Parallel port adapter (light) (I2C_PARPORT_LIGHT) [N/m/y/?] n
RobotFuzz Open Source InterFace USB adapter (I2C_ROBOTFUZZ_OSIF) [N/m/y/?] n
TAOS evaluation module (I2C_TAOS_EVM) [N/m/y/?] n
Tiny-USB adapter (I2C_TINY_USB) [M/n/y/?] m
*
* Other I2C/SMBus bus drivers
*
Elektor ISA card (I2C_ELEKTOR) [N/m/y/?] n
PCA9564/PCA9665 on an ISA bus (I2C_PCA_ISA) [N/m/y/?] n
Geode ACCESS.bus support (SCx200_ACB) [N/m/y/?] n
*
* Graphics support
*
VGA Arbitration (VGA_ARB) [N/y/?] n
Laptop Hybrid Graphics - GPU switching support (VGA_SWITCHEROO) [N/y/?] n
Enable DisplayPort CEC-Tunneling-over-AUX HDMI support (DRM_DP_CEC) [N/y/?] n
ATI Radeon (DRM_RADEON) [Y/n/m/?] y
  Always enable userptr support (DRM_RADEON_USERPTR) [N/y/?] n
AMD GPU (DRM_AMDGPU) [Y/n/m/?] y
  Enable amdgpu support for SI parts (DRM_AMDGPU_SI) [Y/n/?] y
  Enable amdgpu support for CIK parts (DRM_AMDGPU_CIK) [Y/n/?] y
  Always enable userptr write support (DRM_AMDGPU_USERPTR) [N/y/?] n
  Allow GART access through debugfs (DRM_AMDGPU_GART_DEBUGFS) [N/y/?] n
Nouveau (NVIDIA) cards (DRM_NOUVEAU) [N/m/y/?] n
Intel 8xx/9xx/G3x/G4x/HD Graphics (DRM_I915) [Y/n/m/?] y
  Enable alpha quality support for new Intel hardware by default (DRM_I915_ALPHA_SUPPORT) [N/y/?] n
  Force probe driver for selected new Intel hardware (DRM_I915_FORCE_PROBE) [] (NEW) 
Error in reading or end of file.

  Enable capturing GPU state following a hang (DRM_I915_CAPTURE_ERROR) [Y/n/?] y
    Compress GPU error state (DRM_I915_COMPRESS_ERROR) [Y/n/?] y
  Always enable userptr support (DRM_I915_USERPTR) [Y/n/?] y
  *
  * drm/i915 Debugging
  *
  Force GCC to throw an error instead of a warning when compiling (DRM_I915_WERROR) [N/y/?] n
  Enable additional driver debugging (DRM_I915_DEBUG) [N/y/?] n
  Always insert extra checks around mmio access by default (DRM_I915_DEBUG_MMIO) [N/y/?] (NEW) 
Error in reading or end of file.

  Enable additional driver debugging for fence objects (DRM_I915_SW_FENCE_DEBUG_OBJECTS) [N/y/?] n
  Enable additional driver debugging for detecting dependency cycles (DRM_I915_SW_FENCE_CHECK_DAG) [N/y/?] n
  Enable additional driver debugging for GuC (DRM_I915_DEBUG_GUC) [N/y/?] n
  Enable selftests upon driver load (DRM_I915_SELFTEST) [N/y/?] n
  Enable low level request tracing events (DRM_I915_LOW_LEVEL_TRACEPOINTS) [N/y/?] n
  Enable extra debug warnings for vblank evasion (DRM_I915_DEBUG_VBLANK_EVADE) [N/y/?] n
  Enable extra state checking for runtime PM (DRM_I915_DEBUG_RUNTIME_PM) [N/y/?] (NEW) 
Error in reading or end of file.

  *
  * drm/i915 Profile Guided Optimisation
  *
  Runtime autosuspend delay for userspace GGTT mmaps (ms) (DRM_I915_USERFAULT_AUTOSUSPEND) [250] (NEW) 
Error in reading or end of file.

  Busywait for request completion (us) (DRM_I915_SPIN_REQUEST) [5] (NEW) 
Error in reading or end of file.
```

**Comment by bobafetthotmail** [comment]
> So perhaps it's now your turn to provide your .config and Git hash combination which fails for you.

there is no need for that, just do a default build from a clean git pull and you will encounter the issue

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by ynezz** [comment]
> thanks for that, please look at that buildbot log. It says "Error in reading or end of file." after each of the options that are missing from the kernel config, and then it keeps going on.

Yeah, you was right, this needs to be fixed, patches welcome! :)

**Pull request closed without merging**
