### PR TITLE
kernel: ksmbd: only v2 leases handle the directory

### PR DESCRIPTION
**Pull request by ptpt52**
This backport a fix for ksmbd.

Refer: https://github.com/namjaejeon/ksmbd/issues/469

### CODE REVIEW

**Review by pesa1234 — APPROVED** [review]
Tested with kernel 6.1 on latest snapshot, all is ok!

**Comment by sppmasterspp** [comment]
Compiled with this PR and everything is OK for now with kernel 6.1.71.

**Review by sppmasterspp — CHANGES_REQUESTED** [review]
Compiled with this PR and everything is OK for now with kernel 6.1.71.

**Review by sppmasterspp — APPROVED** [review]

**Comment by hauke** [comment]
Thank you for the PR, I applied it to main in 038b0cb4f1ac08803d601cea695c659c10629196.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/openwrt/openwrt/pull/14406
- https://github.com/openwrt/openwrt/pull/14408
- https://github.com/openwrt/openwrt/pull/14409 (merged)

Merged commit:
- https://github.com/openwrt/openwrt/commit/038b0cb4f1ac08803d601cea695c659c10629196

cc: @pesa1234, @ptpt52.

**Pull request closed without merging**
