### PR TITLE
download: introduce subdirectories for raw files

### PR DESCRIPTION
**Pull request by mcprat**
Some packages download a single raw file or set of raw files
instead of an archive.

The filenames of these download files have names and version numbers
that do not directly correspond to the name and version of the package
as it is defined in its Makefile.

To better organize downloaded files, this adds the option of
creating a subdirectory in the download directory for these files
that can be named with package specific variables.

Signed-off-by: Michael Pratt <mcpratt@pm.me>

### CODE REVIEW

**Comment by Ansuel** [comment]
@mpratt14 I wonder... to not change the rules.mk location wonder if we can add the DL_SUBDIR later? (in the dl defines?)

Also think we should also fix/add support to the dl_cleanup script for handling directory in download

**Comment by Ansuel** [comment]
@mpratt14 my (stupid) idea is to find a ""clean"" way to use this DL_SUBDIR without moving the rules.mk include. But I'm checking the include file and it looks to be a mess to accomplish this task. Tell me if i'm wrong.

My idea was to include the check in the generic download function so that the check was done there (and the option correctly parsed)... Considering this is specific to package wonder if we can add this check in download.mk instead of rules.mk.

What do you think?

**Comment by mpratt14** [comment]
thats a good point

I have a habit of working with rules.mk first since it is like a universal include file, but sometimes it's not necessary

however taking a look, there is so much usage of DL_DIR, even in package/

an alternative that should work is making DL_DIR a recursive variable

**Comment by Ansuel** [comment]
problem of tweaking DL_DIR is if some package overwrite that variable

Wonder if a simple fix would be add in download.mk a simple check that parse the DL_SUBDIR option and append the value to DL_DIR... This was we should keep the usual DL_DIR use and add this extra feature.

**Comment by mpratt14** [comment]
a package that overwrites DL_DIR would not be defining DL_SUBDIR, so no problem I think?

**Comment by Ansuel** [comment]
@mpratt14 yep that's exactly why a solution of appending things in download.mk in the presence of DL_SUBDIR would work and should not cause regression/problems

**Comment by mpratt14** [comment]
no i mean, the variable is not exported, so on the next package DL_SUBDIR never gets defined

**Comment by Ansuel** [comment]
@mpratt14 seems to work correctly :D can you update the dl cleanup script or you are not handy with python?

**Comment by mpratt14** [comment]
> problem of tweaking DL_DIR is if some package overwrite that variable

just to be clear, this is not a problem because DL_DIR has to be redefined after rules.mk is included, otherwise rules.mk will override whatever that package Makefile does. The order of include and definition decides what the value is, and rules.mk is included everywhere so it always gets redefined (which is why we don't clear the value of DL_DIR by setting it null)

by making it a recursive variable I don't need to reorder things, so much cleaner now 👍🏼

**Comment by mpratt14** [comment]
> can you update the dl cleanup script

I'm *ok* with python i guess, but that particular script looks messy to me, I'll try...

I never used it before so I would first have to judge expected behavior

**Comment by Ansuel** [comment]
> > can you update the dl cleanup script
> 
> I'm _ok_ with python i guess, but that particular script looks messy to me, I'll try...
> 
> I never used it before so I would first have to judge expected behavior

there is a dry run option to see what actually removes...

**Comment by mpratt14** [comment]
It might not need changes, since archives and the directories are named similarly, but I will test to be sure by making folders that have higher version / release numbers and dry-run

**Comment by Ansuel** [comment]
`ath10k-ct-firmware-2020-11-08 has an unknown file-extension` nope

**Comment by Ansuel** [comment]
@mpratt14 if you want i can give you the patch :D it's an easy fix

**Comment by mpratt14** [comment]
I caught a mistake

defining PKG_VERSION in acx-mac80211 causes it to be handled differently

**Comment by mpratt14** [comment]
I fixed the script but I found a bug in the process of testing

this PR doesn't add PKG_RELEASE there but it should be noted that having `$(NAME)-$(DATE)-$(RELEASE)` is broken

```
$ scripts/dl_cleanup.py -d dl | grep b43 | grep -v tar
dl/b43legacy-firmware-3.130.20.0 is a directory
dl/b43legacy-firmware-3.130.20.0-1 is a directory
Deleting dl/b43legacy-firmware-3.130.20.0
Keeping dl/b43legacy-firmware-3.130.20.0-1

$ scripts/dl_cleanup.py -d dl | grep acx | grep -v tar
dl/acx-mac80211-2014-02-16-1 is a directory
dl/acx-mac80211-2014-02-16 is a directory
Deleting dl/acx-mac80211-2014-02-16-1
Deleting dl/acx-mac80211-2014-02-16
```

**Comment by mpratt14** [comment]
another example of the bug

```
$ scripts/dl_cleanup.py -d dl | grep acx | grep -v tar
Deleting dl/acx-mac80211-2014-02-16-1
Deleting dl/acx-mac80211-2014-02-16
Deleting dl/acx-mac80211-2014-02-11
```

**Comment by mpratt14** [comment]
sorry full disclosure.... there is a tarball leftover thats why

```
$ scripts/dl_cleanup.py -d dl | grep acx
Deleting dl/acx-mac80211-2014-02-16-1
Deleting dl/acx-mac80211-2014-02-16
Deleting dl/acx-mac80211-2014-02-11
Keeping dl/acx-mac80211-2014-02-16-b6fc3149.tar.xz
```

**Comment by mpratt14** [comment]
acx-mac80211 is a unique case where there is a tarball inside the directory
need to figure out how to prefer the tarball inside the directory and delete the one outside the directory

**Comment by mpratt14** [comment]
looks ready to me

@Ansuel how is the python edit?

**Comment by Ansuel** [comment]
what weird issue?

**Comment by mpratt14** [comment]
I rebased

the weird issue is

```
Updating feed 'packages' from 'https://git.openwrt.org/feed/packages.git' ...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
failed.
```

**Comment by Ansuel** [comment]
@mpratt14 mhhh i wonder if we should ignore the corner case bug. Also in your commit is missing the required code to delete the directory if it's old.

I have some concern that the workaround may pose more harm than good.

**Comment by mpratt14** [comment]
nice catch. I'm reading about those functions now

the workaround simply prefers a directory over *not* a directory
if that is too simple, we can check whether the file is in the directory

**Comment by mpratt14** [comment]
I read through the whole script and I don't see anything else related now

**Comment by mpratt14** [comment]
@Ansuel can you cancel the old github CI actions from last push

**Comment by mpratt14** [comment]
@Ansuel so does the python change look ok?

**Comment by Ansuel** [comment]
@mpratt14 yep they looks ok. Still some concern about the workaround/hack but it's ok. If you can pls rebase on top of master so I can flag this as merged or if you can't I will just use the manual way :D

**Pull request merged**
