### PR TITLE
kernel: Add support for Gigadevice GD5F1GQ5UExxG SPI NAND

### PR DESCRIPTION
**Pull request by handongming**
kernel: Add support for Gigadevice GD5F1GQ5UExxG SPI NAND

### CODE REVIEW

**Comment by robimarko** [comment]
This has formal issues, and also please submit this upstream first.

**Comment by hauke** [comment]
Please send this patch to the linux mtd mailing list for Upstream Linux integration. 
Please add this patch also for kernel 5.15 in OpenWrt.

**Comment by 981213** [comment]
Your patch uses incorrect instruction template and get_ecc_status function.

There's already support for this chip in upstream kernel. That should be backported instead.
https://github.com/torvalds/linux/commit/469b992489852b500d39048aa0013639dfe9f2e6
The instruction template used in this upstream commit is also incorrect and needs a fix:
https://patchwork.ozlabs.org/project/linux-mtd/patch/20220320100001.247905-2-gch981213@gmail.com/

**Comment by handongming** [comment]
Thanks for review. I found kernel 5.15 already support GD5F1GQ5UExxG. Is it possible to merge patch only to openwrt 22.03(kernel 5.10)?

**Comment by 981213** [comment]
> Thanks for review. I found kernel 5.15 already support GD5F1GQ5UExxG. And I think get_ecc_status in kernel 5.10 only "gd5fxgq4_variant2_ooblayout" is available, and I test it okay.

No it's not. incorrectly reported bitflips will cause some problems in other part of linux e.g. unnecessary block replacement in UBI.

> Is it possible to merge patch only to openwrt 22.03(kernel 5.10)?

The chip support can be added but you should replace your patch with the correct commit from upstream instead.

**Comment by 981213** [comment]
Backported to master with https://github.com/openwrt/openwrt/commit/55be011a71a4499311e1b64a6c8797d32c949b9e

**Pull request closed without merging**
