### PR TITLE
lantiq:dts: Set correct gphy pins for ethernetports  (solves bug #3188)

### PR DESCRIPTION
**Pull request by wvdakker**
Signed-off-by: W. van den Akker <wvdakker@wilsoft.nl>

See bug: #3188 
Fix fix_gphy_pins.patch  supplied by: Mathias Kresin dev@kresin.me

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Please move the description to the commit message. Despite, please create a more meaningful commit title and use "lantiq: dts: " prefix with first word after that in lower case.

**Comment by wvdakker** [comment]
Problem description.

Device: Zyxel P2812-F1
Software version: Trunk r13335-586661018e

Steps to reproduce:

1: use a working .config from 19.07 (also tried a diffconfig and make defconfig)
2: compile the trunk version
3: upload to the router
4: no ports are available, dmesg reports 

[    0.658577] pinctrl-xway 1e100b10.pinmux: pin io5 already requested by 1e100bb0.stp; cannot claim for 1e108000.eth
[    0.667566] pinctrl-xway 1e100b10.pinmux: pin-5 (1e108000.eth) status -22
[    0.685238] lantiq,xrx200-net 1e108000.eth: Error applying setting, reverse things back
[    0.693270] lantiq,xrx200-net: probe of 1e108000.eth failed with error -22

**Comment by wvdakker** [comment]
> Please move the description to the commit message. Despite, please create a more meaningful commit title and use "lantiq: dts: " prefix with first word after that in lower case.

Done.

**Comment by adrianschmutzler** [comment]
No, the commit is still untouched (you edited the PR ...).

**Comment by adrianschmutzler** [comment]
Okay, that's better. Now also change the _commit_ title as suggested:
"lantiq: set correct gphy pins for Zyxel P-2812"
or similar.

For your signed-off-by, please use full first name.

The bug report should be mentioned with the following line immediately before the Signed-off-by:

"Fixes: FS#3188"

**Comment by wvdakker** [comment]
> Okay, that's better. Now also change the _commit_ title as suggested:
> "lantiq: set correct gphy pins for Zyxel P-2812"
> or similar.
> 
> For your signed-off-by, please use full first name.
> 
> The bug report should be mentioned with the following line immediately before the Signed-off-by:
> 
> "Fixes: FS#3188"

Done

**Comment by adrianschmutzler** [comment]
Thanks, will merge this to master later tonight.

**Comment by wvdakker** [comment]
Thanks.

**Pull request closed without merging**
