### PR TITLE
support for Zyxel WSM20 ( Multi M1 )

### PR DESCRIPTION
**Pull request by annick96**
Product is similar to Haier HAR-20S2U1 Huasifei WR1800K-AX-NAND
Subtarget:mt 7621
Bootloader: U-Boot
CPU:MediaTek MT7621AT
Flash MB:128
RAM MB:256
Ethernet 1Gbit 3*Lan 1 * Wan
MT7530
MT7905DAN + MT7975D 
WLAN 2.4GHz:b/g/n/axWLAN 5.0GHz:a/n/ac/ax
Serial connection parameters:115200 / 8N1
3 Button 
Led count : 2 * 5 with bicolor ( white green red ) 
Supply:12V 1.5A

### CODE REVIEW

**Comment by Spudz76** [comment]
What the actual what?  I don't even know how to mess up a PR this bad.

**Comment by Djfe** [comment]
I bought one of these two weeks ago and was going to add support for them.
I'm still waiting for Zyxel to reply to my GPL Request and send me the source code.

Looking at the OEM dts above: @annick96 I first thought: hey maybe he has already access to the code and I was going to suggest working together but nvm, it's copy&pasted from here it seems: https://forum.openwrt.org/t/802-11ax-routers/10484/224?u=djfe
A Zyxel Router is not the same as a Linksys Router just because they use similar chips. 🙄

This isn't even his first attempt at "adding" a device (#12127)
I don't think this PR even includes a commit of him. He somehow managed to merge release into master but his profile doesn't even have a fork of openwrt to begin with.
@annick96 Without a fork you can't add any code that adds device support. And simply copy&pasting dts files from the manufacturer won't magically add device support. We can't just use these, we have to create new files from them, build the ROM and then test it on the device. You submit a PR after you have done all of that. It probably doesn't help you, but this is part of that process: https://openwrt.org/submitting-patches

This "PR" readded 911 commits instead of adding 1 and thereby notified 71 people. Doing this wastes peoples time for nothing :/
Rethink this and maybe stay on the Forum unless you feel capable of using GItHub.

**Comment by SirLouen** [comment]
> I'm still waiting for Zyxel to reply to my GPL Request and send me the source code.

Create a repo when you have it [and post in the forum to alert everyone behind](https://forum.openwrt.org/t/openwrt-for-zyxel-wsm20-multy-m1/154379).

. I may also send a request to increase pressure. I have 6 units of this product, I feel that if we can hack it with good support from OpenWRT is going to be, by far, the best AX1800 router price-wise, under $40.

Anyway, I think that there are many commonalities between routers that @annick96 have been trying to find in the past few days in the form.

**Comment by Ansuel** [comment]
@annick96 closing this to stop the commit spam. Feel free to open a new one when you have enough info on correct device submission.

**Comment by annick96** [comment]
to date I have not found a sufficient solution, especially on the side of U-bbot
to make the box work I had to replace the u-boot (it is a great danger but good) by that of x-wrt for HUASIFEI HUASIFEI-AX-1800-NAND or even xwrt,wr1800k-ax-nand
x-wrt starts like this without any problem

**Pull request closed without merging**
