### PR TITLE
ar71xx: Change led trigger from usbdev to usbport

### PR DESCRIPTION
**Pull request by howl**
Changed all the usb leds triggers to the actual usbport.

Signed-off-by: David Santamaría Rogado <howl.nsp at gmail.com>

### CODE REVIEW

**Comment by chunkeey** [comment]
Good news!

https://github.com/openwrt/openwrt/commit/0658527e1ebe666cabde9267b6afbe543314160c

thanks to @rmilecki work, there's no need to convert the devices manually.

**Comment by howl** [comment]
@chunkeey the problem is that the triggers get applied in sysfs but luci is not able to show the configuration with usbdev, only with usbport.

**Comment by chunkeey** [comment]
@howl 
So this is a luci problem then (or as well)?!

Oh well, there's also the issue of the current users. Because they will need to wipe their existing configuration first before the entry shows up, right?. I think it would be nice to have a migration script for this as well.

Now, there's already a /etc/uci-defaults/04_led_migration script that could be extended to convert the existing usbdev triggers. But this requires automation. Thankfully, 0658527 has already a working version for the "hardest" part:

		# Translate port of root hub, e.g. 4-1 -> usb4-port1
		ports=$(echo "$dev" | sed -n 's/^\([0-9]*\)-\([0-9]*\)$/usb\1-port\2/p')
		# Translate port of extra hub, e.g. 2-2.4 -> 2-2-port4
		[ -z "$ports" ] && ports=$(echo "$dev" | sed -n 's/\./-port/p')

This converts the usbdev "1-1" to usb1-port1. So the migration script would only need to look for a usbdev led definition and either replace it, or swap out the trigger to usbport and the ports list. DONE.

---

as for converting target/linux/ar71xx/base-files/etc/board.d/01_leds 
Maybe this would work too? 

```
diff --git a/package/base-files/files/lib/functions/uci-defaults.sh b/package/base-files/files/lib/functions/uci-defaults.sh
index 315df7b708..fd10457bd8 100755
--- a/package/base-files/files/lib/functions/uci-defaults.sh
+++ b/package/base-files/files/lib/functions/uci-defaults.sh
@@ -489,13 +489,11 @@ _ucidef_set_led_trigger() {
 ucidef_set_led_usbdev() {
 	local dev="$4"
 
-	_ucidef_set_led_common "$1" "$2" "$3"
+	# see /etc/init.d/led
+	ports=$(echo "$dev" | sed -n 's/^\([0-9]*\)-\([0-9]*\)$/usb\1-port\2/p')
+	[ -z "$ports" ] && ports=$(echo "$dev" | sed -n 's/\./-port/p')
 
-	json_add_string type usb
-	json_add_string device "$dev"
-	json_select ..
-
-	json_select ..
+	ucidef_set_led_usbport "$1" "$2" "$3" "$ports"
 }
 
 ucidef_set_led_usbhost() {
```

this would also help with all other targets.

**Comment by howl** [comment]
@chunkeey could be or not, if I can remember well the @rmilecki work was done to not broke the usbdev trigger definitions when the new usbport trigger replaced usbdev but the idea behind was to let time to replace the trigger definitions from the old to the newer trigger.

LuCI reads the configuration expecting a usbport trigger options so it does display empty trigger combobox, but you can set it up correctly from LuCI. So I don't think that could be consider a LuCI bug.

I think the cleaner way to handle this could be, change usbdev to usbport in target/linux/*/base-files/etc/board.d/01_leds and also autoconvert the configuration from usbdev to usbport for existing configurations. If I'm not in a mistake your approach will only serve for new installations and also non configuration preserving updates.

What do you think?

**Comment by chunkeey** [comment]
> if I can remember well the @rmilecki work was done to not broke the usbdev trigger definitions when the new usbport trigger replaced usbdev but the idea behind was to let time to replace the trigger definitions from the old to the newer trigger.

"the idea behind was to let time to replace the trigger definitions from the old to the newer trigger.". Do you have a link to where this idea was discussed/declared? I can't find much about this in the commits or via google? I need your help there, Thanks.

The most recent development I know of: "put new LED definitions into the device-tree". (Though, this is not relevant for this PR since ar71xx does not support it). 

> LuCI reads the configuration expecting a usbport trigger options so it does display empty trigger combobox, but you can set it up correctly from LuCI. So I don't think that could be consider a LuCI bug.

Empty trigger combobox? Isn't this undefined behavior? Because it's showing up in my LuCi (git-19.038.66435-4e5111e) with Firefox 60.5.1esr as "Always off (none)" here (not on a AR71xx device, but I checked that /etc/init.d/led did setup the trigger ) which is why this seems very so odd. This is maybe why we see things differently, because we both really see different things.

screenshot_20190217_000022

and here are the available triggers in the combobox:

screenshot_20190217_000318

```
config led 'led_usb'
        option name 'USB'
        option sysfs 'rt-ac58u:blue:usb'
        option trigger 'usbdev'
        option dev '1-1'
```

> I think the cleaner way to handle this could be, change usbdev to usbport in target/linux/*/base-files/etc/board.d/01_leds and also autoconvert the configuration from usbdev to usbport for existing configurations. If I'm not in a mistake your approach will only serve for new installations and also non configuration preserving updates.

Yes, that's why I had the spacer, since it was about the mass-patching of target/linux/ar71xx/base-files/etc/board.d/01_leds by done hand. But I'm glad that you are coming around on the "autoconvert the configuration from usbdev to usbport". Because the script also handles the aforementioned: 
"1-1.1 usb port combinations." problem from your initial message.

**Comment by howl** [comment]
Thought there was discussed but can't find it so perhaps that was left as in idea on my mind https://github.com/openwrt/luci/issues/971, anyways the usbdev trigger is deprecated and it doesn't make sense maintaining remanents.

The Always off option could be nowadays but I can remember showing empty combobox when non installed trigger was specified in the configuration file, anyways the mismatch between config and luci display is there.

I can also apply the way 1-1.1 is converted to the patch and apply the changes for the 3 left boards, but at least for me can't tell if that is the real way usbport handle that situations.

To apply the idea about tweaking existing system config files from usbdev to usbport, where it could be the code, in /etc/init.d/leds?

**Comment by chunkeey** [comment]
> Thought there was discussed but can't find it so perhaps that was left as in idea on my mind openwrt/luci#971, anyways the usbdev trigger is deprecated and it doesn't make sense maintaining remanents.

K, then let's leave it at that.

> The Always off option could be nowadays but I can remember showing empty combobox when non installed trigger was specified in the configuration file, anyways the mismatch between config and luci display is there.

It seems LuCI pulls the available triggers from /sys/class/leds . So this is why it doesn't show any "usbdev" triggers on the combobox there. So, if one adds a usbdev trigger entry to list this should work. Maybe a more robust approach could be found, but heh' why not try:

```
--- /usr/lib/lua/luci/model/cbi/admin_system/leds.lua
+++ /usr/lib/lua/luci/model/cbi/admin_system/leds.lua
@@ -72,6 +72,9 @@ for t in triggers:gmatch("[%w-]+") do
 		trigger:value(t, translatef("Wi-Fi on (%s)", t))
 	elseif t:match("phy[0-9]tpt") then
 		trigger:value(t, translatef("Wi-Fi activity (%s)", t))
+	elseif t:match("usbport") then
+		trigger:value(t, translate(t, t))
+		trigger:value("usbdev", "usbdev")	
 	else
 		trigger:value(t, translate(t:gsub("-", "")))
 	end
```

screenshot_20190217_010927

> I can also apply the way 1-1.1 is converted to the patch and apply the changes for the 3 left boards, but at least for me can't tell if that is the real way usbport handle that situations

Truth be told: There's an underlying issue with the uci-definition for usbport with "what port/hub is where exactly".  This is because the usb bus, hub and device topology and enumeration can be a bit "random". (You can find gems like https://www.embeddedrelated.com/showthread/comp.arch.embedded/107341-1.php that go a bit into the detail for a specific use-case, but in the end it's down to some RNG. ). The Device-Tree supported LEDTrigger solution is a bit better, because it can guarantee that you probably got the right usb controller / port (in most embedded systems). 

"but at least for me can't tell if that is the real way usbport handle that situations"
I don't think that you necessarily need to do that, as long as you add/attach a easily reproducible way of you got there. So something like a script that for a given "01_leds" file could convert all legacy usbdev uci definitions to usbport uci definition would be good (for that one part).  

> To apply the idea about tweaking existing system config files from usbdev to usbport, where it could be the code, in /etc/init.d/leds?

Oh, yes, (the second part). I mentioned it in https://github.com/openwrt/openwrt/pull/1819#issuecomment-464385847 already, but I guess there was no context.
A good place (because there are already other renames/fixes in there is):
/etc/uci-defaults/04_led_migration (though, this is ar71xx specific. ). 
But It's probably for the best to just do it for one single target at a time.

**Comment by howl** [comment]
> > To apply the idea about tweaking existing system config files from usbdev to usbport, where it could be the code, in /etc/init.d/leds?
> 
> Oh, yes, (the second part). I mentioned it in [#1819 (comment)](https://github.com/openwrt/openwrt/pull/1819#issuecomment-464385847) already, but I guess there was no context.
> A good place (because there are already other renames/fixes in there is):
> /etc/uci-defaults/04_led_migration (though, this is ar71xx specific. ).
> But It's probably for the best to just do it for one single target at a time.

Sorry @chunkeey for asking already replied.

If I don't misunderstood, within led migration it can be simple done by adding a new function called for example migrate_usbdev_to_usbport called from all the boards, no matter even if it has usbs or not, where we just take with uci the usbdev values and set it up as usbport values, deleting the "option dev" only meaningful for usbdev.

About LuCI I don't know if it worth changing it. Let me explain, if the port from usbdev to usbport, could be done for all the families where usbdev is used in time before the next stable release, then won't be necessary to worry about luci.

**Comment by howl** [comment]
Commit amended matching author with SoB and tl-wdr4300, tl-wr942n-v1 and arduino-yun boards are now also converted.

**Comment by chunkeey** [comment]
I tried my hand at writing a converting script via `sed` 

https://gist.github.com/chunkeey/b0e3f5e698e41e8a62ecbf4fbeaa5df3

and it produces the same output. :+1: 

I'm probably going to also add the:
"the problem is that the triggers get applied in sysfs but luci is not able to show the configuration with usbdev, only with usbport." sentence from your https://github.com/openwrt/openwrt/pull/1819#issuecomment-463827438 because it answers why this change was necessary.

**Comment by chunkeey** [comment]
Merged. Thanks.

**Pull request closed without merging**
