### PR TITLE
kernel: bump 5.10 to 5.10.82

### PR DESCRIPTION
**Pull request by graysky2**
Removed upstreamed:
    `bcm53xx/patches-5.10/033-v5.16-0014-ARM-dts-NSP-Fix-mpcore-mmc-node-names.patch`

Manually rebased:
    `ipq806x/patches-5.10/086-ipq8064-fix-duplicate-node.patch`

All other patches automatically rebased.
```
Build system: x86_64
Build-tested: bcm2711/RPi4B, ipq806x/R7800
Run-tested: bcm2711/RPi4B, ipq806x/R7800
```
Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by graysky2** [comment]
@rsalvaterra - I cannot get my toolchain to build.  This is not build tested nor run tested.  Any help until I can fix the toolchain on my side?

**Review by rsalvaterra — APPROVED** [review]
Looks good to me, thanks!

Run-tested:
ramips/mt7621 (Redmi AC2100)

**Comment by anomeome** [comment]
`[   17.520642] *** NOT YET: opcode 3f ***`
This seems new, an unknown opcode?

**Comment by rsalvaterra** [comment]
Run-tested (.82):
ramips/mt7621 (Redmi AC2100)

Looks good, matches my local bump, thanks!

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in be077f48124b8bcedd7cdb552c050ce73a42e509 and 894f483d203a34618a3c725c808b8811d69c4430

**Pull request closed without merging**
