### PR TITLE
glibc: switch from git to https

### PR DESCRIPTION
**Pull request by juppin**
This is needed for working behind a http proxy.

Signed-off-by: Johann Neuhauser <jneuhauser@dh-electronics.de>

### CODE REVIEW

**Comment by diizzyy** [comment]
In general I think we should use git over https and github codeload if possible.

**Comment by yousong** [comment]
Apart from the git default port being blocked in many network environment, we really should not proto git repos such as glibc in the first place.  The repo is just too big for many users with small, "fragile" internet connections which is really bad since git has no "resume clone" feature.  It's really frustrating.

In the case of glibc, we are currently at the tip of glibc 2.26/master branch.  It's 146 commits away from the `glibc-2.26` tag.  We can surely work with that amount of patches.  Actually it's the largest number of "maintenance patches" since glibc release of 2.20.  Thus I suggest we switch back to the release tarball using `@GNU/libc`

```
➜  ~/git-repo/glibc git:(master) for i in `seq 20 27`; do echo -n "2.$i "; g log --pretty=oneline  glibc-2.$i..remotes/origin/release/2.$i/master | wc -l; done
2.20 41
2.21 31
2.22 110
2.23 108
2.24 88
2.25 127
2.26 146
2.27 37
```

**Comment by diizzyy** [comment]
fwiw, musl also uses git
https://github.com/openwrt/openwrt/commit/a8a5cb9595cd64a48c1cea6a1478c11e022474a9

**Comment by juppin** [comment]
Almost everything is downloaded / cloned over http(s) instead of git, so i thought why not for glibc...

On work i don´t have internet connection over a squid proxy and the admin won´t allow other destination ports than 80 and 443. :-(

But a tar.xz download would also be good solution.
Build system tried to download archive files from source.openwrt.org and so on, but there are no packed source codes...

**Comment by yousong** [comment]
It's good if it provides a better experience, regardless of how other existing packages are doing.  But we know such things are more subjective with all kinds of trade off.

Anyway, glibc-2.27 was out for a while and we are going to need it for RISC-V ISA support (@xfguo is working on it).  I will later try posting a RFC patch to the mailing list to see how it will go

And, LGTM for the change here ;)

**Comment by dedeckeh** [comment]
I find it quite cumbersome to maintain a list of 146 patches; it only increases the workload to maintain it. But if switching to https improves the user experience I've no objection

**Comment by diizzyy** [comment]
In this case I think it's fine to just switch to https/http but if only a few patches are needed it's probably better to patch a release tarball rather than using git/svn etc

**Comment by hauke** [comment]
I also prefer a http / https downloads because of strict company proxies which block everything else for security reasons.
If we would use the the same version as used to create the tar I would prefer the tar file, but here it looks good to clone with git over https.
@yousong and @xfguo: @wigyori is also working on RISC-V support, he has an FPGA.

**Comment by xfguo** [comment]
Great! Pls check my porting on https://github.com/xfguo/riscv-openwrt-port , I have a hifive-u board and also VC707 fpga.

@wigyori @hauke

**Comment by dedeckeh** [comment]
Patch has been applied to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=0370293cf3148b5bb6ffe1f94a4477bace23e21c); thanks

**Pull request closed without merging**
