### PR TITLE
build: make sure asm gets built with -DPIC

### PR DESCRIPTION
**Pull request by pprindeville**
Fixes issue #14921.

### CODE REVIEW

**Comment by pprindeville** [comment]
Requesting reviews by @aparcar and @nbd168.

**Comment by adschm** [comment]
Please comply to formal requirements: https://openwrt.org/submitting-patches

**Comment by pprindeville** [comment]
> Please comply to formal requirements: https://openwrt.org/submitting-patches

So... you want it submitted via email to the list?

**Comment by aparcar** [comment]
@pprindeville no, please prefix your commit with the package/area you're touching.

**Comment by pprindeville** [comment]
> @pprindeville no, please prefix your commit with the package/area you're touching.

Split into two commits, as one touched the build system (`rules.mk`) and another touched `libnfnetlink` but both need to go in at the same time.

**Comment by pprindeville** [comment]
Per @aparcar, ordering the commits such that nothing leaves the repo broken in any intermediate states.

**Comment by pprindeville** [comment]
`feeds/packages` has been fixed, so this PR will not break it.

**Comment by adschm** [comment]
> > Please comply to formal requirements: https://openwrt.org/submitting-patches
> 
> So... you want it submitted via email to the list?

As Paul said, I was referring to commit title and missing commit message, this appears to be fixed now.

**Comment by pprindeville** [comment]
Can we get a merge?

**Comment by pprindeville** [comment]
@cotequeiroz Can you please test this PR?

**Review by cotequeiroz — CHANGES_REQUESTED** [review]
I've done some basic testing, already; I was about to resend my [previous patch](https://patchwork.ozlabs.org/project/openwrt/patch/20210311214633.2727-1-cotequeiroz@gmail.com/) to do what you're doing here, but you beat me to it 😃.  I marked it as superseded in favor of this one instead.

One nitpick:  I suggest you edit the commit message to point the issue to packages feed: `#14921` -> `openwrt/packages#14921`.

I will perform a full build of 21.02 with this for x86_64 tonight, but feel free to merge it as is any time.

This, and openwrt/packages#15169 before it, should be cherry-picked to openwrt-21.02, since the strongswan linking failure happens there as well.

**Comment by pprindeville** [comment]
> I've done some basic testing, already; I was about to resend my [previous patch](https://patchwork.ozlabs.org/project/openwrt/patch/20210311214633.2727-1-cotequeiroz@gmail.com/) to do what you're doing here, but you beat me to it 😃. I marked it as superseded in favor of this one instead.
> 
> One nitpick: I suggest you edit the commit message to point the issue to packages feed: `#14921` -> `openwrt/packages#14921`.
> 
> I will perform a full build of 21.02 with this for x86_64 tonight, but feel free to merge it as is any time.
> 
> This, and [openwrt/packages#15169](https://github.com/openwrt/packages/pull/15169) before it, should be cherry-picked to openwrt-21.02, since the strongswan linking failure happens there as well.

Not following: the first line of the commit states:

```
Fixes issue #14921, whereby inline ASM wasn't getting built as PIC;
```

That's not enough of a reference to the problem?

**Comment by cotequeiroz** [comment]
I meant you show prepend the packages repo reference, since you're crossing repos:
```
Fixes issue openwrt/packages#14921, whereby ASM wasn't getting built as PIC;
```

I've finished my run, and found out package nss still needs a fix.  I'm opening a PR for it.

**Comment by pprindeville** [comment]
> I meant you should prepend the packages repo reference, since you're crossing repos [...]

Done.

**Review by cotequeiroz — APPROVED** [review]
My review won't count for the merge restriction.  Nonetheless,

Reviewed-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

**Comment by cotequeiroz** [comment]
There should be no hurdles to apply this to 21.02, if desired.  openwrt/packages#15227 took care of $(FPIC) quoting in the openwrt-21.02 branch of the packages feed.

**Comment by pprindeville** [comment]
Anyone?

**Comment by aparcar** [comment]
Isn't it possible to enable this just for the specific packages? I'm not familiar enough with the topic to enable it everywhere by default.

**Comment by pprindeville** [comment]
> Isn't it possible to enable this just for the specific packages? I'm not familiar enough with the topic to enable it everywhere by default.

It's pretty simple, really.  It's not enough to pass `-fPIC` into the compiler and loader flags.  There are certain bits of code that need to be aware that they're being built position-independent (especially assembly code which does it's only handling of addresses), and hence need `-DPIC` as well to be self-aware.

**Comment by ldir-EDB0** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ldir.git

**Comment by pprindeville** [comment]
Thanks!

**Pull request closed without merging**
