### PR TITLE
Enable userspace code profiling with perf

### PR DESCRIPTION
**Pull request by mgorbachyov**
Signed-off-by: Maxim Gorbachyov <maxim.gorbachyov@gmail.com>

### CODE REVIEW

**Comment by LipkeGu** [comment]
Please add the "Signed of by line"

**Comment by mgorbachyov** [comment]
@LipkeGu Done

**Comment by hauke** [comment]
Please provide this for the master branch. All new features should go into master first.

**Comment by mgorbachyov** [comment]
@hauke Done: https://github.com/openwrt/openwrt/pull/676

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
