### PR TITLE
bcm47xx: add kernels 6.1 and 6.6

### PR DESCRIPTION
**Pull request by namiltd**
Adding kernel 6.1 as main and 6.6 as test kernel for bcm47xx.

### CODE REVIEW

**Comment by ehem** [comment]
Not having such a device, so merely commenting as an on-looker.

Is it really worthwhile to add 6.1 _and_ 6.6?  Might it make more sense to add 6.6 and completely skip 6.1?

**Comment by namiltd** [comment]
Kernel 6.1 looks like a kernel for a future release. Most platforms already support it.

**Comment by ehem** [comment]
Seemed like there was hope the next release would use 6.6, in which case skipping 6.1 might be better.  Enough commentary from the peanut gallery on this though.

**Comment by namiltd** [comment]
I'm also in favor of 6.6. I've implemented both, so there's a choice.

**Comment by Mile-Lile** [comment]
I upgraded this morning my r8000 and all I can say it is rock solid... Thank you...

**Comment by namiltd** [comment]
Due to other commits adding support for the 6.1 kernel, a new PR was created with only the addition of support for the 6.6 kernel PR https://github.com/openwrt/openwrt/pull/15010

**Pull request closed without merging**
