### PR TITLE
[22.03] toolchain: bump GCC 11 to 11.3.0

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Remove an upstreamed patch and rebase all remaining patches.

Signed-off-by: Rui Salvaterra <rsalvaterra@gmail.com>
(cherry picked from commit f4cdef2191e1d8df6c37806ce5161135629e87de)

### CODE REVIEW

**Comment by hauke** [comment]
Normally we do not update the GCC minor version in a stable release, I agree with this policy. Do you need a special fix from this GCC version?

**Comment by PolynomialDivision** [comment]
Yes. This is fixing the issue with libmbedtls I describe here:
https://github.com/openwrt/packages/pull/19609#issuecomment-1281961389

Ping @neheb

**Comment by BKPepe** [comment]
From the referenced pull request, it is not clear that it helps, though.

**Comment by neheb** [comment]
sounds like it. The alternative is to def out the ppc code.

**Comment by ynezz** [comment]
>  I agree with this policy

+1

> Yes. This is fixing the issue with libmbedtls I describe here:

IMO patching libmbedtls is the right place and proper way forward.

**Pull request closed without merging**
