### PR TITLE
kernel: bump 5.15 to 5.15.38

### PR DESCRIPTION
**Pull request by rsalvaterra**
Deleted (upstreamed):
mediatek/patches-5.15/120-10-v5.18-mtd-nand-fix-ecc-parameters-for-mt7622.patch [1]

Other patches automatically rebased.

Run-tested:
mediatek/mt7622 (Belkin RT3200)

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.38&id=3ec920d755ae69c201b358e8d8e96c32f51145d8

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by lucize** [comment]
starting from 3.15.35 dell wyse cx0, Via CPU lockup if ethernet adapter is connected (even usb), with this version terminal is printing
```
SQUASHFS error: Unable to read metadata cache entry [...]
SQUASHFS error: Unable to read directory block [...]
```
it has an ide flash, I'll try to boot from an usb stick and see if it's the same, tried on multiple same devices

**Comment by rsalvaterra** [comment]
> starting from 3.15.35 dell wyse cx0, Via CPU lockup if ethernet adapter is connected (even usb), with this version terminal is printing (until freezes)
> 
> ```
> SQUASHFS error: Unable to read metadata cache entry [...]
> SQUASHFS error: Unable to read directory block [...]
> ```
> 
> it has an ide flash, I'll try to boot from an usb stick and see if it's the same, tried on multiple same devices LE: booting from usb didn't help, but no more squashfs errors printed on terminal

In order to rule out any possible squashfs issues, can you please build/boot an ext4 image and see if there are any errors with it?

**Comment by lucize** [comment]
yes, I'll try, but I guess it's just something that locks the system, when network traffic starts, and squashfs was just a collateral "damage", with .35 freezes instantly, with .36, ping is working a few seconds, I'll try also as an AP

**Comment by hauke** [comment]
If you think something is broken with locking you can activate these debug options and check if they find anything:
````
CONFIG_KERNEL_DETECT_HUNG_TASK=y
CONFIG_KERNEL_PROVE_LOCKING=y
CONFIG_KERNEL_SOFTLOCKUP_DETECTOR=y
CONFIG_KERNEL_WQ_WATCHDOG=y
````

**Comment by lucize** [comment]
oddly enough, with those kernel options, the device doesn't freeze anymore at boot if the cable is connected, but if I disconnect and reconnect it freezes again but in different way, the keyboard is not working anymore (caps/num lock seems to work, but no text) and the network cable status is displayed (every time I disconnect and reconnect), also acpi power button doesn't work

**Comment by jospezial** [comment]
5.15.37 released

**Comment by lucize** [comment]
I guess the only way is to do a git bisect, at least 5.10 is still working

**Comment by graysky2** [comment]
Build-system: x86_64
Build-tested: mt7622/RT3200
Run-tested: mt7622/RT3200

**Comment by lucize** [comment]
seems that the regression was fixed!
Tested x86

**Pull request merged**
