### PR TITLE
x86: add more-uarches patch and update config-6.6

### PR DESCRIPTION
**Pull request by graysky2**
Commit adds additional optimization/tuning for kernel builds via more micro-architectures options for x86 which are selected under:
   Processor type and features  --->
   Processor family --->

Upstream github[1] has some benchmarks showing small but real increases building a kernel with a tailored -march=foo option.  The patch is over 12 years old and well tested.

1. https://github.com/graysky2/kernel_compiler_patch?tab=readme-ov-file#benchmarks

Build system: x86/64
Build-tested: x86/64/AMD Cezanne
Run-tested: x86/64/AMD Cezanne

### CODE REVIEW

**Comment by graysky2** [comment]
Yes, the kernel uses its own set of CFLAGS, KCFLAGS. For example, see:

[arch/x86/Makefile](https://github.com/torvalds/linux/blob/master/arch/x86/Makefile)
[arch/x86/Makefile_32.cpu](https://github.com/torvalds/linux/blob/master/arch/x86/Makefile_32.cpu)
[arch/x86/Kconfig.cpu](https://github.com/torvalds/linux/blob/master/arch/x86/Kconfig.cpu)

**Comment by robimarko** [comment]
Is there a reason this cannot be upstreamed?

**Comment by graysky2** [comment]
> Is there a reason this cannot be upstreamed?

Lack of interest last time I tried, see: https://lkml.org/lkml/2012/12/5/421

**Comment by robimarko** [comment]
Well, its been over a decade since then.

My issue is that we are going to have to keep this basically forever if its not upstream

**Comment by curtdept** [comment]
I use this in all my builds and have for a very long time :) It would be nice to somehow project this into menuconfig so its not restrained to kernel config though.

**Comment by robimarko** [comment]
I am doing some more research, and it seems somebody submitted your patch in 2021 and there was a nice discussion, but it boils down to this:
https://lore.kernel.org/lkml/1708009975.124311.1629299321026@office.mailbox.org/

I have also looked at your benchmarks, and I dont think that carrying this around forever for a sub 1% (If any) performance improvement is worth it.

That is my opinion, I hope somebody else also chimes in.

**Comment by graysky2** [comment]
Thanks for the review.

> I have also looked at your benchmarks, and I dont think that carrying this around forever for a sub 1% (If any) performance improvement is worth it.

The irony is that the kernel already ships a number of antiquated options (pentium-mmx, K6, etc.) which likely also only import that particular end point by a fraction of a percent, but as I point out in the text, the make end point is just easily measured and convenient to run.  I think it's widely accepted that microarch specific optimizations are value-added, this is just modernizing choices.

**Comment by rany2** [comment]
> I have also looked at your benchmarks, and I dont think that carrying this around forever for a sub 1% (If any) performance improvement is worth it.

Yeah, I figured that someone from Intel/AMD would have done this a long time ago if they thought it was worth it. 

Anyway, I guess the only downside with this change is keeping the patch up-to-date. 

I'm willing to test out this patch on a Celeron J4005 (x86-64-v2) but I'm not sure how to properly benchmark. I wonder whether this patch would improve performance on these weaker CPUs.

**Comment by graysky2** [comment]
@rany2 - yes, I do not know what the best measure is for benchmarking the kernel.  The weakest CPU I have access to is the Intel N100 from my benchmark linked above.  All of the three I tested benefit by <1% based the make benchmark.  Really the principal to me is the compilers offer these, many x86 OpenWrt users build their own kernels, why NOT toggle these on?

**Comment by t-8ch** [comment]
Similar current discussion on LKML:
https://lore.kernel.org/lkml/7760553a-6410-4017-be7b-feda4109c0d5@intel.com/

Upstreams enthusiasm seems very limited.

**Comment by robimarko** [comment]
@graysky2 Because it means carrying this thing forever in OpenWrt as you can see from the upstream reply (Today):
https://lore.kernel.org/lkml/4d172613-481b-4b45-aa59-165ef1c7dc9b@intel.com/

Instead of patching the kernel, can't we just pass the required `-march` or whatever as a parameter while building, I am sure we are already passing stuff to the kernel.
That way we can add these optimisations in OpenWrt menuconfig behind some advanced symbol or whatever.

**Comment by graysky2** [comment]
> That way we can add these optimisations in OpenWrt menuconfig behind some advanced symbol or whatever.

I would be happy with that option.  Basically you can run this before you compile to circumvent any kernel hacking:
```
export KCFLAGS=' -march=x86-64-v3'
export KCPPFLAGS=' -march=x86-64-v3'
```

I do not know how to go about modifying the build system to allow an entry like this.

**Comment by robimarko** [comment]
Well, it seems that there is no need for any build system modifications as in:
`Advanced configuration options (for developers) -> Kernel extra CFLAGS`

You can pass whatever additional `KCFLAGS` you want to the kernel and thus pass your desired optimisations

**Comment by graysky2** [comment]
I think you're right @robimarko - I thought the internals of the kernel would override that but inspecting the output of `ps aux | grep march` while build the kernel does not show any entries for `-march=x86-64` it only shows the custom line I defined `-march=x86-64-v3`

**Pull request closed without merging**
