### PR TITLE
x86: enable CONFIG_MMC_SDHCI_ACPI for x86_64

### PR DESCRIPTION
**Pull request by mayli**
Some x86_64 single board computer (including Atomic Pi)
has onboard emmc, but requires CONFIG_MMC_SDHCI_ACPI driver
to use or boot from it.

Here is boot message for the mmc device

```
[    2.838008] mmc0: SDHCI controller on ACPI [80860F14:00] using ADMA
[    2.857536] mmc1: SDHCI controller on ACPI [80860F14:01] using ADMA
[    2.950019] mmc0: new HS200 MMC card at address 0001
[    3.158271] mmcblk0: mmc0:0001 M52516 14.6 GiB
[    3.170290] mmcblk0boot0: mmc0:0001 M52516 partition 1 4.00 MiB
[    3.177191] mmcblk0boot1: mmc0:0001 M52516 partition 2 4.00 MiB
[    3.183963] mmcblk0rpmb: mmc0:0001 M52516 partition 3 4.00 MiB, chardev (248:0)
```

Other lines changed in this config file are introduced by menuconfig.

### CODE REVIEW

**Comment by adschm** [comment]
Please use "x86:" instead of "kernel:" as prefix in the commit title, since your changes are target-specific.

**Comment by mayli** [comment]
> Please use "x86:" instead of "kernel:" as prefix in the commit title, since your changes are target-specific.

done

**Review by dangowrt — CHANGES_REQUESTED** [review]
Many of those changes are unrelated.:
```
CONFIG_HZ=250
CONFIG_HZ_250=y
```

I'm generally not against cleaning up config stuff, but it should be in a separate commit and also consider that some of those changes may need to into generic config rather than just for x86.
For starters, please only add the relevant config symbols really needed to bring up SDHCI.

**Comment by mayli** [comment]
@dangowrt Done :)

**Review by dangowrt — CHANGES_REQUESTED** [review]
Sorry, there are still tons of unrealted changes. Can you really just add the 2 or 3 lines needed for SDHCI and skip everything else for now?
Especially stuff like 
```
CONFIG_VGACON_SOFT_SCROLLBACK=y
# CONFIG_VGACON_SOFT_SCROLLBACK_PERSISTENT_ENABLE_BY_DEFAULT is not set
CONFIG_VGACON_SOFT_SCROLLBACK_SIZE=64
```
which actually changes behaviour and is clearly entirely unrealted.
We can't include your change like that.

**Comment by mayli** [comment]
@dangowrt the [diff ](https://github.com/openwrt/openwrt/pull/3533/files) shows +2 −0 , did i miss something?

**Comment by dangowrt** [comment]
> @dangowrt the diff shows +2 −0 , did i miss something?
@mayli Apparently yes :/
Maybe you forgot to `git add`? `git commit -a --amend` can also be a good solution here...

**Comment by aparcar** [comment]
I only see two lines changed, please recheck @dangowrt

**Comment by dangowrt** [comment]
```
[daniel@box lede]$ wget -q -O- https://github.com/openwrt/openwrt/pull/3533.patch
From 61bb5a59d2ef7bd1902afe47f90f5435cf7d2bcc Mon Sep 17 00:00:00 2001
From: Mengyang Li <mayli.he@gmail.com>
Date: Fri, 23 Oct 2020 17:07:18 -0700
Subject: [PATCH 1/2] x86: enable CONFIG_MMC_SDHCI_ACPI for x86_64

Some x86_64 single board computer (including Atomic Pi)
has onboard emmc, but requires CONFIG_MMC_SDHCI_ACPI driver
to use or boot from it.

Here is boot message for the mmc device

[    2.838008] mmc0: SDHCI controller on ACPI [80860F14:00] using ADMA
[    2.857536] mmc1: SDHCI controller on ACPI [80860F14:01] using ADMA
[    2.950019] mmc0: new HS200 MMC card at address 0001
[    3.158271] mmcblk0: mmc0:0001 M52516 14.6 GiB
[    3.170290] mmcblk0boot0: mmc0:0001 M52516 partition 1 4.00 MiB
[    3.177191] mmcblk0boot1: mmc0:0001 M52516 partition 2 4.00 MiB
[    3.183963] mmcblk0rpmb: mmc0:0001 M52516 partition 3 4.00 MiB, \
chardev (248:0)

Other lines changed in this config file are introduced by menuconfig.

Signed-off-by: Mengyang Li <mayli.he@gmail.com>
---
 target/linux/x86/64/config-5.4 | 27 ++++++++-------------------
 1 file changed, 8 insertions(+), 19 deletions(-)

diff --git a/target/linux/x86/64/config-5.4 b/target/linux/x86/64/config-5.4
index 3954abfd4fbc..dc8482d44cb3 100644
--- a/target/linux/x86/64/config-5.4
+++ b/target/linux/x86/64/config-5.4
@@ -64,19 +64,16 @@ CONFIG_AUDIT_ARCH=y
 CONFIG_BACKLIGHT_CLASS_DEVICE=y
 CONFIG_BACKLIGHT_GENERIC=y
 CONFIG_BALLOON_COMPACTION=y
-CONFIG_BLK_DEV_SR=y
-# CONFIG_BLK_DEV_SR_VENDOR is not set
 CONFIG_BLK_DEV_INTEGRITY=y
 CONFIG_BLK_DEV_NVME=y
+CONFIG_BLK_DEV_SR=y
 CONFIG_BLK_MQ_VIRTIO=y
 CONFIG_BLK_PM=y
 # CONFIG_BOOTPARAM_HOTPLUG_CPU0 is not set
 CONFIG_BTT=y
-CONFIG_CDROM=y
 # CONFIG_CALGARY_IOMMU is not set
-# CONFIG_CALGARY_IOMMU_ENABLED_BY_DEFAULT is not set
+CONFIG_CDROM=y
 CONFIG_CONNECTOR=y
-# CONFIG_CPU_HOTPLUG_STATE_CONTROL is not set
 CONFIG_CPU_RMAP=y
 CONFIG_CRC_T10DIF=y
 CONFIG_CRYPTO_AEAD=y
@@ -115,6 +112,7 @@ CONFIG_CRYPTO_SIMD=y
 # CONFIG_CRYPTO_TWOFISH_X86_64_3WAY is not set
 CONFIG_CRYPTO_XTS=y
 # CONFIG_DEBUG_HOTPLUG_CPU0 is not set
+CONFIG_DMA_ACPI=y
 CONFIG_DMA_SHARED_BUFFER=y
 # CONFIG_DPTF_POWER is not set
 CONFIG_DRM=y
@@ -122,7 +120,6 @@ CONFIG_DRM_BOCHS=y
 CONFIG_DRM_BRIDGE=y
 CONFIG_DRM_FBDEV_EMULATION=y
 CONFIG_DRM_FBDEV_OVERALLOC=100
-# CONFIG_DRM_GM12U320 is not set
 CONFIG_DRM_I915=y
 # CONFIG_DRM_I915_ALPHA_SUPPORT is not set
 CONFIG_DRM_I915_CAPTURE_ERROR=y
@@ -158,7 +155,6 @@ CONFIG_EFI_RUNTIME_WRAPPERS=y
 CONFIG_EFI_STUB=y
 # CONFIG_EFI_TEST is not set
 # CONFIG_EFI_VARS is not set
-# CONFIG_ENERGY_MODEL is not set
 CONFIG_FAILOVER=y
 CONFIG_FB=y
 CONFIG_FB_CFB_COPYAREA=y
@@ -176,7 +172,6 @@ CONFIG_FB_SYS_FOPS=y
 CONFIG_FB_SYS_IMAGEBLIT=y
 CONFIG_FB_TILEBLITTING=y
 # CONFIG_FB_VESA is not set
-# CONFIG_FONTS is not set
 CONFIG_FONT_8x8=y
 CONFIG_FRAMEBUFFER_CONSOLE=y
 CONFIG_FRAMEBUFFER_CONSOLE_DETECT_PRIMARY=y
@@ -192,7 +187,6 @@ CONFIG_GPIOLIB=y
 CONFIG_GPIOLIB_IRQCHIP=y
 CONFIG_GPIO_ACPI=y
 CONFIG_GPIO_ICH=y
-# CONFIG_GPIO_IT87 is not set
 CONFIG_GPIO_LYNXPOINT=y
 CONFIG_GPIO_SCH=y
 CONFIG_HARDLOCKUP_CHECK_TIMESTAMP=y
@@ -226,6 +220,7 @@ CONFIG_HOTPLUG_PCI_ACPI=y
 # CONFIG_HOTPLUG_PCI_SHPC is not set
 CONFIG_HOTPLUG_SMT=y
 CONFIG_HPET=y
+CONFIG_HPET_EMULATE_RTC=y
 CONFIG_HPET_MMAP=y
 # CONFIG_HP_ACCEL is not set
 CONFIG_HVC_DRIVER=y
@@ -246,6 +241,8 @@ CONFIG_HYPERV_STORAGE=y
 CONFIG_HYPERV_TIMER=y
 CONFIG_HYPERV_UTILS=y
 # CONFIG_HYPERV_VSOCKETS is not set
+CONFIG_HZ=250
+CONFIG_HZ_250=y
 CONFIG_I2C=y
 CONFIG_I2C_ALGOBIT=y
 CONFIG_I2C_BOARDINFO=y
@@ -286,7 +283,6 @@ CONFIG_LPC_SCH=y
 CONFIG_MAILBOX=y
 # CONFIG_MAXSMP is not set
 CONFIG_MEMORY_BALLOON=y
-# CONFIG_MEMORY_HOTPLUG is not set
 CONFIG_MFD_CORE=y
 # CONFIG_MFD_INTEL_LPSS_ACPI is not set
 CONFIG_MMC=y
@@ -294,6 +290,7 @@ CONFIG_MMC_BLOCK=y
 CONFIG_MMC_CQHCI=y
 CONFIG_MMC_RICOH_MMC=y
 CONFIG_MMC_SDHCI=y
+CONFIG_MMC_SDHCI_ACPI=y
 CONFIG_MMC_SDHCI_IO_ACCESSORS=y
 CONFIG_MMC_SDHCI_PCI=y
 # CONFIG_MMC_SDHCI_PLTFM is not set
@@ -313,7 +310,6 @@ CONFIG_NR_CPUS=8
 CONFIG_NR_CPUS_DEFAULT=64
 CONFIG_NR_CPUS_RANGE_BEGIN=2
 CONFIG_NR_CPUS_RANGE_END=512
-# CONFIG_NUMA is not set
 CONFIG_NVME_CORE=y
 CONFIG_NVME_MULTIPATH=y
 # CONFIG_NVME_TCP is not set
@@ -354,23 +350,18 @@ CONFIG_PINCTRL=y
 CONFIG_PM=y
 # CONFIG_PMIC_OPREGION is not set
 CONFIG_PM_CLK=y
-# CONFIG_PM_DEBUG is not set
 CONFIG_PM_SLEEP=y
 CONFIG_PM_SLEEP_SMP=y
 CONFIG_PNP=y
 CONFIG_PNPACPI=y
 CONFIG_PNP_DEBUG_MESSAGES=y
-# CONFIG_POWER_SUPPLY_HWMON is not set
 CONFIG_PROC_EVENTS=y
 CONFIG_PVH=y
 CONFIG_QUEUED_RWLOCKS=y
 CONFIG_QUEUED_SPINLOCKS=y
-# CONFIG_RANDOMIZE_BASE is not set
 CONFIG_RAS=y
 CONFIG_RCU_NEED_SEGCBLIST=y
 CONFIG_RCU_STALL_COMMON=y
-CONFIG_REGMAP=y
-CONFIG_REGMAP_I2C=y
 CONFIG_RELAY=y
 CONFIG_RELOCATABLE=y
 CONFIG_RESET_ATTACK_MITIGATION=y
@@ -386,6 +377,7 @@ CONFIG_SCHED_SMT=y
 # CONFIG_SCIF_BUS is not set
 CONFIG_SCSI_VIRTIO=y
 CONFIG_SENSORS_CORETEMP=y
+# CONFIG_SENSORS_DRIVETEMP is not set
 CONFIG_SENSORS_FAM15H_POWER=y
 CONFIG_SENSORS_I5500=y
 CONFIG_SENSORS_K10TEMP=y
@@ -414,9 +406,6 @@ CONFIG_TREE_SRCU=y
 CONFIG_UCS2_STRING=y
 # CONFIG_UNWINDER_ORC is not set
 CONFIG_USB_STORAGE=y
-CONFIG_VGACON_SOFT_SCROLLBACK=y
-# CONFIG_VGACON_SOFT_SCROLLBACK_PERSISTENT_ENABLE_BY_DEFAULT is not set
-CONFIG_VGACON_SOFT_SCROLLBACK_SIZE=64
 CONFIG_VIRTIO=y
 CONFIG_VIRTIO_BALLOON=y
 CONFIG_VIRTIO_BLK=y

From f37a70a53ddb1b97bcf6c90bcebfafbe5f062ec3 Mon Sep 17 00:00:00 2001
From: Mengyang Li <mengyan.li@nutanix.com>
Date: Mon, 9 Nov 2020 11:25:28 -0800
Subject: [PATCH 2/2] Update config-5.4

---
 target/linux/x86/64/config-5.4 | 27 ++++++++++++++++++++-------
 1 file changed, 20 insertions(+), 7 deletions(-)

diff --git a/target/linux/x86/64/config-5.4 b/target/linux/x86/64/config-5.4
index dc8482d44cb3..f09deca5b08b 100644
--- a/target/linux/x86/64/config-5.4
+++ b/target/linux/x86/64/config-5.4
@@ -64,16 +64,19 @@ CONFIG_AUDIT_ARCH=y
 CONFIG_BACKLIGHT_CLASS_DEVICE=y
 CONFIG_BACKLIGHT_GENERIC=y
 CONFIG_BALLOON_COMPACTION=y
+CONFIG_BLK_DEV_SR=y
+# CONFIG_BLK_DEV_SR_VENDOR is not set
 CONFIG_BLK_DEV_INTEGRITY=y
 CONFIG_BLK_DEV_NVME=y
-CONFIG_BLK_DEV_SR=y
 CONFIG_BLK_MQ_VIRTIO=y
 CONFIG_BLK_PM=y
 # CONFIG_BOOTPARAM_HOTPLUG_CPU0 is not set
 CONFIG_BTT=y
-# CONFIG_CALGARY_IOMMU is not set
 CONFIG_CDROM=y
+# CONFIG_CALGARY_IOMMU is not set
+# CONFIG_CALGARY_IOMMU_ENABLED_BY_DEFAULT is not set
 CONFIG_CONNECTOR=y
+# CONFIG_CPU_HOTPLUG_STATE_CONTROL is not set
 CONFIG_CPU_RMAP=y
 CONFIG_CRC_T10DIF=y
 CONFIG_CRYPTO_AEAD=y
@@ -120,6 +123,7 @@ CONFIG_DRM_BOCHS=y
 CONFIG_DRM_BRIDGE=y
 CONFIG_DRM_FBDEV_EMULATION=y
 CONFIG_DRM_FBDEV_OVERALLOC=100
+# CONFIG_DRM_GM12U320 is not set
 CONFIG_DRM_I915=y
 # CONFIG_DRM_I915_ALPHA_SUPPORT is not set
 CONFIG_DRM_I915_CAPTURE_ERROR=y
@@ -155,6 +159,7 @@ CONFIG_EFI_RUNTIME_WRAPPERS=y
 CONFIG_EFI_STUB=y
 # CONFIG_EFI_TEST is not set
 # CONFIG_EFI_VARS is not set
+# CONFIG_ENERGY_MODEL is not set
 CONFIG_FAILOVER=y
 CONFIG_FB=y
 CONFIG_FB_CFB_COPYAREA=y
@@ -172,6 +177,7 @@ CONFIG_FB_SYS_FOPS=y
 CONFIG_FB_SYS_IMAGEBLIT=y
 CONFIG_FB_TILEBLITTING=y
 # CONFIG_FB_VESA is not set
+# CONFIG_FONTS is not set
 CONFIG_FONT_8x8=y
 CONFIG_FRAMEBUFFER_CONSOLE=y
 CONFIG_FRAMEBUFFER_CONSOLE_DETECT_PRIMARY=y
@@ -187,6 +193,7 @@ CONFIG_GPIOLIB=y
 CONFIG_GPIOLIB_IRQCHIP=y
 CONFIG_GPIO_ACPI=y
 CONFIG_GPIO_ICH=y
+# CONFIG_GPIO_IT87 is not set
 CONFIG_GPIO_LYNXPOINT=y
 CONFIG_GPIO_SCH=y
 CONFIG_HARDLOCKUP_CHECK_TIMESTAMP=y
@@ -220,7 +227,6 @@ CONFIG_HOTPLUG_PCI_ACPI=y
 # CONFIG_HOTPLUG_PCI_SHPC is not set
 CONFIG_HOTPLUG_SMT=y
 CONFIG_HPET=y
-CONFIG_HPET_EMULATE_RTC=y
 CONFIG_HPET_MMAP=y
 # CONFIG_HP_ACCEL is not set
 CONFIG_HVC_DRIVER=y
@@ -241,8 +247,6 @@ CONFIG_HYPERV_STORAGE=y
 CONFIG_HYPERV_TIMER=y
 CONFIG_HYPERV_UTILS=y
 # CONFIG_HYPERV_VSOCKETS is not set
-CONFIG_HZ=250
-CONFIG_HZ_250=y
 CONFIG_I2C=y
 CONFIG_I2C_ALGOBIT=y
 CONFIG_I2C_BOARDINFO=y
@@ -283,6 +287,7 @@ CONFIG_LPC_SCH=y
 CONFIG_MAILBOX=y
 # CONFIG_MAXSMP is not set
 CONFIG_MEMORY_BALLOON=y
+# CONFIG_MEMORY_HOTPLUG is not set
 CONFIG_MFD_CORE=y
 # CONFIG_MFD_INTEL_LPSS_ACPI is not set
 CONFIG_MMC=y
@@ -290,8 +295,8 @@ CONFIG_MMC_BLOCK=y
 CONFIG_MMC_CQHCI=y
 CONFIG_MMC_RICOH_MMC=y
 CONFIG_MMC_SDHCI=y
-CONFIG_MMC_SDHCI_ACPI=y
 CONFIG_MMC_SDHCI_IO_ACCESSORS=y
+CONFIG_MMC_SDHCI_ACPI=y
 CONFIG_MMC_SDHCI_PCI=y
 # CONFIG_MMC_SDHCI_PLTFM is not set
 # CONFIG_MMC_TIFM_SD is not set
@@ -310,6 +315,7 @@ CONFIG_NR_CPUS=8
 CONFIG_NR_CPUS_DEFAULT=64
 CONFIG_NR_CPUS_RANGE_BEGIN=2
 CONFIG_NR_CPUS_RANGE_END=512
+# CONFIG_NUMA is not set
 CONFIG_NVME_CORE=y
 CONFIG_NVME_MULTIPATH=y
 # CONFIG_NVME_TCP is not set
@@ -350,18 +356,23 @@ CONFIG_PINCTRL=y
 CONFIG_PM=y
 # CONFIG_PMIC_OPREGION is not set
 CONFIG_PM_CLK=y
+# CONFIG_PM_DEBUG is not set
 CONFIG_PM_SLEEP=y
 CONFIG_PM_SLEEP_SMP=y
 CONFIG_PNP=y
 CONFIG_PNPACPI=y
 CONFIG_PNP_DEBUG_MESSAGES=y
+# CONFIG_POWER_SUPPLY_HWMON is not set
 CONFIG_PROC_EVENTS=y
 CONFIG_PVH=y
 CONFIG_QUEUED_RWLOCKS=y
 CONFIG_QUEUED_SPINLOCKS=y
+# CONFIG_RANDOMIZE_BASE is not set
 CONFIG_RAS=y
 CONFIG_RCU_NEED_SEGCBLIST=y
 CONFIG_RCU_STALL_COMMON=y
+CONFIG_REGMAP=y
+CONFIG_REGMAP_I2C=y
 CONFIG_RELAY=y
 CONFIG_RELOCATABLE=y
 CONFIG_RESET_ATTACK_MITIGATION=y
@@ -377,7 +388,6 @@ CONFIG_SCHED_SMT=y
 # CONFIG_SCIF_BUS is not set
 CONFIG_SCSI_VIRTIO=y
 CONFIG_SENSORS_CORETEMP=y
-# CONFIG_SENSORS_DRIVETEMP is not set
 CONFIG_SENSORS_FAM15H_POWER=y
 CONFIG_SENSORS_I5500=y
 CONFIG_SENSORS_K10TEMP=y
@@ -406,6 +416,9 @@ CONFIG_TREE_SRCU=y
 CONFIG_UCS2_STRING=y
 # CONFIG_UNWINDER_ORC is not set
 CONFIG_USB_STORAGE=y
+CONFIG_VGACON_SOFT_SCROLLBACK=y
+# CONFIG_VGACON_SOFT_SCROLLBACK_PERSISTENT_ENABLE_BY_DEFAULT is not set
+CONFIG_VGACON_SOFT_SCROLLBACK_SIZE=64
 CONFIG_VIRTIO=y
 CONFIG_VIRTIO_BALLOON=y
 CONFIG_VIRTIO_BLK=y
[daniel@box lede]$ 
```

**Comment by aparcar** [comment]
In cooperation with @dangowrt, merged, thank you.

**Pull request closed without merging**
