### PR TITLE
[23.05] ipq807x: prpl-haze: enable LED driver on device tree

### PR DESCRIPTION
**Pull request by CheWei-Chien**
Enable prpl-haze LED driver LP5562 on device tree.

You also need to set:
CONFIG_LEDS_LP5562=y
CONFIG_LEDS_LP55XX_COMMON=y
in kernel config

Signed-off-by: CheWei Chien <chewei.chien@wnc.com.tw>

### CODE REVIEW

**Comment by robimarko** [comment]
Why did you open a new PR?

**Comment by CheWei-Chien** [comment]
Sorry, I thought 23.05 and main branches need different PR ...........
How can I put main PR to 23.05 ?

**Comment by ynezz** [comment]
> How can I put main PR to 23.05 ?

I've just added the missing information to the documentation [Patch backports](https://openwrt.org/submitting-patches#patch_backports)

> 1. Changes needs to be first applied into the **main** branch
> 2. Afterwards those changes can be proposed to be applied into the stable (release) branch

**Comment by robimarko** [comment]
Can you rebase this based on the merged master commit?

**Comment by ynezz** [comment]
@CheWei-Chien can you please re-read https://github.com/openwrt/openwrt/pull/14319#issuecomment-1874956745 and mainly https://openwrt.org/submitting-patches#patch_backports, you should use `git cherry-pick -x <main branch commit` to backport/cherry-pick changes from stable into release branches, like for example in this case:

```
git reset --hard origin/openwrt-23.05
git cherry-pick -x b33fa6ac9065 fb45194305
git push -f
```

**Comment by CheWei-Chien** [comment]
> @CheWei-Chien can you please re-read [#14319 (comment)](https://github.com/openwrt/openwrt/pull/14319#issuecomment-1874956745) and mainly https://openwrt.org/submitting-patches#patch_backports, you should use `git cherry-pick -x <main branch commit` to backport/cherry-pick changes from stable into release branches, like for example in this case:
> 
> ```
> git reset --hard origin/openwrt-23.05
> git cherry-pick -x b33fa6ac9065 fb45194305
> git push -f
> ```
> 
> If you look at the Git commit history of [openwrt-23.05](https://github.com/openwrt/openwrt/commits/openwrt-23.05/) branch, you'll find out, that most of the commits are done this way.

It seems only kmod (b33fa6ac9065) can use cherry-pick. DTS is on a different path.

**Comment by ynezz** [comment]
> It seems only kmod ([b33fa6a](https://github.com/openwrt/openwrt/commit/b33fa6ac9065028046016ea631f6be0926d7abd0)) can use cherry-pick. DTS is on a different path.

That (sub)target renames are indeed PITA, but we can't avoid them, so just adjust the cherry-pick and commit OR simply keep it as it is and add `(cherry picked from commit <hash>)` to the bottom of the commit description. Everyone knows, that it would be never straight cherry-pick, but at least the origin of the changes is known = means, its backported from the main branch.

**Comment by robimarko** [comment]
Please fix the DTS compile errors

**Comment by robimarko** [comment]
Any reason this is still a draft?

**Comment by CheWei-Chien** [comment]
> Any reason this is still a draft?

I think no. I just no change it.

**Comment by robimarko** [comment]
@ynezz I will leave this to you since you have the board

**Review by ynezz — APPROVED** [review]
Just tested, thanks @CheWei-Chien for the LED fix, it works nice.

**Comment by ynezz** [comment]
Merged in 26e882f06f732784b2fbb224044ba7add93a34d8

**Pull request closed without merging**
