### PR TITLE
tools/cmake: Update to 3.14.0

### PR DESCRIPTION
**Pull request by diizzyy**
Update CMake to 3.14.0
Refresh patches
Remove inofficial fossies.org and replace with GitHub (link on official site)
Remove 150-C-feature-checks-Match-warnings-more-strictly.patch as it's
a no longer needed backport from upstream.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile and runtime tested: ar71xx, TP-Link TL-WDR3600, OpenWrt master

**Comment by dedeckeh** [comment]
Patch pushed to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=a3446257a8737bfc2899c5911791873561feecc7); thx

**Comment by diizzyy** [comment]
@dedeckeh 
This fails because buildsbots runs/enforces ancient version of GCC
I have no idea about the policy, but I guess they run Jessie? https://wiki.debian.org/DebianJessie

```
...
  CCC=/usr/bin/gcc-4.9
  CCXX=/usr/bin/g++-4.9
....
```

Compiles fine on Alpine 3.9.0 (GCC 8.2.0) and Debian 9.8 (GCC 6.3.0)

**Comment by dedeckeh** [comment]
@diizzyy we need to keep cmake at 3.13.2 for the moment; maybe the issue should be reported to the upstream cmake project ?

**Comment by diizzyy** [comment]
Since I can't comment on https://github.com/openwrt/openwrt/commit/d4540354303949c93b20ea0148afd90ce5e40ea6 (I assume this is intentional by committer)

Summary:
Ubuntu 18.10 (GCC 8.2) - OK
Ubuntu 14.04.2 (GCC 4.8.5(?)) - OK
Centos 7 (GCC 4.8.X(?)) - OK
Alpine 3.9.0 (GCC 8.2.0) - OK
Debian 9.8 (GCC 6.3.0) - OK
Buildbots, GCC 4.9(?)) (Debian 7?) - Fails

I did actually assume that it was due to ancient version of GCC but that doesn't seem the case?

**Comment by ynezz** [comment]
>  This fails because buildsbots runs/enforces ancient version of GCC

ancient from your POV, rock solid and battle tested for others :-)

> Since I can't comment on d454035 (I assume this is intentional by committer)

AFAIK I'm not aware about such GitHub feature, which would allow selectively blocking certain user's comments :-)

>  Ubuntu 14.04.2 (GCC 4.8.5(?)) - OK

FYI I've just installed gcc-4.9 and g++-4.9 (`g++ (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4`) and I'm able to compile cmake 3.14.0 just fine. Yes, strange, probably ccache hiccup.

**Comment by diizzyy** [comment]
https://help.github.com/en/articles/blocking-a-user-from-your-personal-account
@ynezz 
It's ancient enough that it's not recieving any updates from upstream in about 2y as far as I can tell https://gcc.gnu.org/git/?p=gcc.git;a=shortlog;h=refs/heads/gcc-4_9-branch and dropped from pretty much all other distros a long time ago or will (indirectly) very soon if you're looking at LTS branches except Debian?

https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Extended_Update_Support_(EUS)_/_Z_Tree
RHEL 7.6 seems to have ~2 months left for public users
Debian 8 seems to have some time left, https://wiki.debian.org/LTS
Ubuntu 14.04.X seems to be very close to EoL: https://www.ubuntu.com/about/release-cycle
I think those are the major ones still supported.
FreeBSD switched about 2 years ago and dropped it completely 4 months ago (I can't find any traces of it being enforced for a long time).
https://svnweb.freebsd.org/ports?view=revision&revision=437437
https://svnweb.freebsd.org/ports?view=revision&revision=482488

Oh well, it seem like it's not an issue in the end.

**Comment by jow-** [comment]
> Oh well, it seem like it's not an issue in the end.

Apart from the fact that it causes widespread breakage on the buildbots ;) What was the reason to bump it in the first place?

**Comment by diizzyy** [comment]
@jow- 
I was referring to my assumption that it was due to "old" versions of GCC as it compiled fine on 6.X and newer when I tested it but as other have managed to compile it on older versions seems like its an issue with the buildbot setup.

As for the bump itself it's mostly the commands and modules part of the release note (https://cmake.org/cmake/help/v3.14/release/3.14.html) as the package repo in general tries to track upstream closely and it's just a matter of time before there's unnecessary breakage because we're running old versions of tools. This also seems the reason why @chunkeey is looking at bumping libtool https://git.openwrt.org/?p=openwrt/staging/chunkeey.git;a=commit;h=9b649c6a3c227fc5960f0bc37ecc8a5281aa735d

**Comment by jow-** [comment]
The issue is triggered by g++ in combination with ccache (alternatively by `g++-4.9 -save-temps`) on *subsequent cached rebuilds*. A simple build test using `CXX=g++-4.9 ./configure && make` will not trigger it.

**Comment by diizzyy** [comment]
If I knew that https://open.cdash.org/index.php?project=CMake existed earlier (didn't find it when I looked last time) I'd would have ruled out my guess that GCC 4.9 being the issue.

**Comment by ynezz** [comment]
Just for the record, I'm adding more details about the ccache/g++-4.9 issue and how to reproduce it reliably:

```
< jow> the bug is indeed ccache related
< jow> can also be triggered with g++-4.9 -save-temps
< jow> it boils down to the fact that g++, under circumstances, produces preprocessed source which it is unable to read
< jow> or to compile, rather, this bug is exposed by ccache
< jow> its not simple to reproduce because a naive CXX="ccache g++" ./configure in cmake will strip the ccache ivoncation
< jow> you need to use a wrapper script, like the buildroot does
< jow> e.g.  echo -e "#!/bin/sh\nexec ccache /usr/bin/g++-4.9 \"\$@\"" > /tmp/g++.sh && chmod +x /tmp/g++.sh && CXX=/tmp/g++.sh ./configure && make
< jow> but that alone is not enough to trigger the error
< jow> you'll also need to build once, then build *another* time with ccache, only then you see the error
< jow> a similar bug report in debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784681
< jow> was not able to find a matching bug report in upstream gcc/g++
< jow> currently testing whether g++6 is affected as well
< jow> seems fine on g++6
```

**Comment by diizzyy** [comment]
Can't reproduce it either with GCC 8.2.0

So... perhaps add a workaround for GCC sub 6 by exporting ```export CCACHE_DISABLE=1``` ?

**Comment by diizzyy** [comment]
```
GCC_DMPVER_GREPCMD := grep -E '^(4\.[8-9]|[5]\.?)'
GCC_DMPVER_STRING := $(shell $(CC) -dumpversion | $(GCC_DMPVER_GREPCMD))
ifeq ($(GCC_DMPVER_STRING),)
  $(info GCC version > 6.0 detected, no workaround set for CCACHE)
  else
  $(info GCC version < 6.0 detected, disabling CCACHE)
  export CCACHE_DISABLE=1
endif
```

Perhaps something like that would be temporary fix?

**Comment by diizzyy** [comment]
@jow- 
Ping

**Comment by diizzyy** [comment]
@ynezz 
Might this be a suitable workaround?

**Pull request closed without merging**
