### PR TITLE
Add CAKE qdisc

### PR DESCRIPTION
**Pull request by ldir-EDB0**
Cake is an FQ-CoDel-derived traffic shaper and queue management
algorithm with some advanced features. It is supported by sqm-scripts
and can outperform HTB+FQ-CoDel in some cases, as well as offer features
such as host isolation that are not available otherwise.

This patches 'tc' in iproute2 to include support for Cake, and adds
kmod-sched-cake for the shaper itself. Patches copied over from LEDE
HEAD.

### CODE REVIEW

**Comment by hnyman** [comment]
Note that the sqm-scripts package was already bumped up to 1.1.1 by https://github.com/openwrt/packages/commit/a84d421b18ff3811a97a2eec33075cb04e2bdd34 and that 1.1.1 adds dependency on the cake qdisc. So this PR is needed for enabling sqm-scripts to be compiled in Openwrt.

**Comment by kdarbyshirebryant** [comment]
Ahh! I didn't know the sqm scripts bump had already occurred. Yes this pr really does need to go into openwrt :-)

**Comment by hnyman** [comment]
@wigyori 
Please commit this in to re-enable installing SQM for Openwrt.

**Comment by hnyman** [comment]
@wigyori 
can you also please pick the kernel patch that @tohojo sent to the mailing list:
https://patchwork.ozlabs.org/patch/721219/

That is related to the SQM 1.1.2 changes and is needed for the current SQM.

PS. and the buildbot is pretty broken. Buildslave wyrding misbehaves.

**Comment by wigyori** [comment]
Yep, already pulling the patch in, thanks for the heads-up.

I didn't have time yet to look into wyrding, as in why the hell is e2fsprogs broken there.

**Comment by wigyori** [comment]
wyrding should be fixed now, for the record.

**Comment by hnyman** [comment]
> Yep, already pulling the patch in, thanks for the heads-up.

Note that the patch from Toke does not apply, as Openwrt still has sch_esfq that has been removed from LEDE (and the patch is based on LEDE). After editing one context line, the patch will apply (with some line number offsets):

```
<  SCHED_MODULES_FILTER = $(SCHED_MODULES_CORE) act_connmark sch_netem
---
>  SCHED_MODULES_FILTER = $(SCHED_MODULES_CORE) act_connmark sch_esfq sch_netem
```

**Pull request merged**
