### PR TITLE
kernel: skip hpower setting for the module which has no revs

### PR DESCRIPTION
**Pull request by sprteruyama**
Signed-off-by: S.Teruyama <teruyama@springboard-inc.jp>

This commit adds support for NTT-Small-OCU
which has the sfp module with no compliance information.

### CODE REVIEW

**Comment by hauke** [comment]
did you send this patch also to upstream? If you did so please post the link to the mailing list post or patchwork.

**Comment by sprteruyama** [comment]
I'm sorry. I didn't post to the mailing list, I'll let you know when it shows up on patchwork.

**Comment by sprteruyama** [comment]
https://patchwork.ozlabs.org/project/openwrt/patch/1638108130-24432-1-git-send-email-teruyama@springboard-inc.jp/

**Comment by chunkeey** [comment]
This went on the netdev ML:

https://lore.kernel.org/netdev/20211202175843.0210476e@kicinski-fedora-pc1c0hjn.dhcp.thefacebook.com/t/#mf0448aa8641c6862a5d7b76f754a0cd7a89e68ec

likely this will get also fixed through linux-stable. @sprteruyama just needs to report back whenever
the latest suggestion worked.

**Comment by sprteruyama** [comment]
Hi,

Sorry for the late reply.
It worked perfectly on the actual device.

The attached file is the startup log.

Thanks.

**Comment by chunkeey** [comment]
@sprteruyama, do you mean that the fix in the thread by [Russell King](https://lore.kernel.org/netdev/20211202175843.0210476e@kicinski-fedora-pc1c0hjn.dhcp.thefacebook.com/t/#m4fa99abee803f98558803a95d1f46177d52953e5) worked? Then please report to the upstream
mail. My guess is, Russell and Bjorn are both waiting and sadly won't see that you wrote it here. Thanks!

**Comment by chunkeey** [comment]
@sprteruyama any update?

**Comment by sprteruyama** [comment]
Yes, Russell
***@***.***/t/#m4fa99abee803f98558803a95d1f46177d52953e5>'s
work is perfect.
Where should I post the report?

2021年12月17日(金) 4:09 Christian Lamparter ***@***.***>:

**Comment by hauke** [comment]
The change was applied to upstream Linux in https://github.com/torvalds/linux/commit/5765cee119bf5a36c94d20eceb37c445508934be This change was backported to kernel 5.10 in https://github.com/torvalds/linux/commit/ee64479c9ce62eedd1a2d5ab26d93aff58d68c19 which was released as v5.10.94. This version is used since OpenWrt 1343acc8cd9e5c4206c2f65f1897c7be5660f046

**Pull request closed without merging**
