### PR TITLE
archs38: add 6.1 testing kernel

### PR DESCRIPTION
**Pull request by robimarko**
Add kernel 6.1 as the testing kernel for `archs38`.

Do note that this is only compile tested, I dont have any boards.

### CODE REVIEW

**Comment by robimarko** [comment]
@EvgeniiDidin Any chance you have some of the boards?

**Comment by abrodkin** [comment]
> @EvgeniiDidin Any chance you have some of the boards?

@robimarko luckily we now have QEMU port for ARC and so the same image which used to work in nSIM is now meant to work in QEMU. Unfortunately ARC changes not yet upstreamed, so it's required to build it from sources here: https://github.com/foss-for-synopsys-dwc-arc-processors/qemu

If of any interest, below are instructions which might help with building and running QEMU:
* QEMU build instructions: https://foss-for-synopsys-dwc-arc-processors.github.io/experimental-documentation/2023.09/simulators/qemu/
* Running Linux for ARC cores in QEMU: https://foss-for-synopsys-dwc-arc-processors.github.io/experimental-documentation/2023.09/linux/simulators/qemu/

In the meantime I'll try to build OpenWrt image for nSIM/QEMU from this PR and see how it works.
If there're already built images, it will be even simpler and I may try them immediately.

**Comment by robimarko** [comment]
Those are some nice news, it would be awesome to know if this bump still works.
There are no prebuilt images unfortunately.

**Comment by abrodkin** [comment]
@robimarko sorry for the delay, but it works with the Linux kernel v6.1, see below:
```
nsimdrv -prop=nsim_isa_family=av2hs -prop=nsim_isa_core=3 -prop=chipid=0xffff -prop=nsim_isa_atomic_option=1 -prop=nsim_isa_ll64_option=1 -prop=nsim_mmu=4 -prop=mmu_pagesize=8192 -prop=mmu_super_pagesize=2097152 -prop=mmu_stlb_entries=16 -prop=mmu_ntlb_ways=4 -prop=mmu_ntlb_sets=128 -prop=icache=32768,64,4,0 -prop=dcache=16384,64,2,0 -prop=nsim_isa_shift_option=2 -prop=nsim_isa_swap_option=1 -prop=nsim_isa_bitscan_option=1 -prop=nsim_isa_sat=1 -prop=nsim_isa_div_rem_option=1 -prop=nsim_isa_mpy_option=9 -prop=nsim_isa_enable_timer_0=1 -prop=nsim_isa_enable_timer_1=1 -prop=nsim_isa_number_of_interrupts=32 -prop=nsim_isa_number_of_external_interrupts=32 -prop=isa_counters=1 -prop=nsim_isa_pct_counters=8 -prop=nsim_isa_pct_size=48 -prop=nsim_isa_pct_interrupt=1 -prop=nsim_mem-dev=uart0,kind=dwuart,base=0xf0000000,irq=24 -prop=nsim_isa_aps_feature=1 -prop=nsim_isa_num_actionpoints=4 -prop=nsim_isa_rtc_option=1 -prop=nsim_isa_fpud_option=1 bin/targets/archs38/generic-glibc/openwrt-archs38-generic-nsim_hs-initramfs.elf
Console now belongs to UART, hit CRTL-] to return to simulator.
[    0.000000] Linux version 6.1.80 (abrodkin@SNPS-Ecl1TeCeXg) (arc-openwrt-linux-gnu-gcc (OpenWrt GCC 12.3.0 r25567-0dfc0495fc) 12.3.0, GNU ld (GNU Binutils) 2.40.0) #0 SMP PREEMPT Thu Mar  7 11:17:13 2024
[    0.000000] Memory @ 80000000 [1024M]
[    0.000000] Memory @ 100000000 [1024M] Not used
[    0.000000] OF: fdt: Machine model: snps,zebu_hs
[    0.000000] earlycon: uart8250 at MMIO32 0xf0000000 (options '115200n8')
[    0.000000] printk: bootconsole [uart8250] enabled
[    0.000000] Failed to get possible-cpus from dtb, pretending all 4 cpus exist
[    0.000000] archs-intc       : 15 priority levels (default 1)
[    0.000000]
[    0.000000] IDENTITY : ARCVER [0x53] ARCNUM [0x0] CHIPID [0xffff]
[    0.000000] processor [0]    : HS38 R3.0 (ARCv2 ISA)
[    0.000000] Timers           : Timer0 Timer1 RTC [UP 64-bit]
[    0.000000] ISA Extn : atomic ll64 unalign mpy[opt 9] div_rem
[    0.000000] BPU              : partial match, cache:2048, Predict Table:16384 Return stk: 8
[    0.000000] MMU [v4] : 8k PAGE, 2M Super Page (not used) , swalk 2 lvl, JTLB 512 (128x4), uDTLB 8, uITLB 4
[    0.000000] I-Cache          : 32K, 4way/set, 64B Line, VIPT
[    0.000000] D-Cache          : 16K, 2way/set, 64B Line, PIPT
[    0.000000] Peripherals      : 0xc0000000
[    0.000000] Vector Table     : 0x90006000
[    0.000000] FPU              : SP DP
[    0.000000] DEBUG            : ActionPoint 4/full
[    0.000000] Extn [SMP]       : ARConnect (v0): 0 cores with
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000080000000-0x00000000bfffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080000000-0x00000000bfffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080000000-0x00000000bfffffff]
[    0.000000] percpu: Embedded 6 pages/cpu s17792 r8192 d23168 u49152
[    0.000000] pcpu-alloc: s17792 r8192 d23168 u49152 alloc=6*8192
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 130432
[    0.000000] Kernel command line: earlycon=uart8250,mmio32,0xf0000000,115200n8 console=ttyS0,115200n8 debug print-fatal-signals=1
[    0.000000] Dentry cache hash table entries: 131072 (order: 6, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 5, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 1025768K/1048576K available (5079K kernel code, 654K rwdata, 1648K rodata, 7504K init, 267K bss, 22808K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=128, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000]  Trampoline variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 512
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] Local-64-bit-Ctr not usable in SMP
[    0.000000] Failed to initialize '/rtc': -22
[    0.000000] Failed to initialize '/timer1': -22
[    0.000000] sched_clock: 32 bits at 100 Hz, resolution 10000000ns, wraps every 21474836475000000ns
[    0.000000] Calibrating delay loop... 99.22 BogoMIPS (lpj=496128)
[    0.090000] pid_max: default: 32768 minimum: 301
[    0.090000] Mount-cache hash table entries: 2048 (order: 0, 8192 bytes, linear)
[    0.090000] Mountpoint-cache hash table entries: 2048 (order: 0, 8192 bytes, linear)
[    0.110000] cblist_init_generic: Setting adjustable number of callback queues.
[    0.110000] cblist_init_generic: Setting shift to 2 and lim to 1.
[    0.110000] cblist_init_generic: Setting adjustable number of callback queues.
[    0.110000] cblist_init_generic: Setting shift to 2 and lim to 1.
[    0.110000] rcu: Hierarchical SRCU implementation.
[    0.110000] rcu:     Max phase no-delay instances is 1000.
[    0.120000] smp: Bringing up secondary CPUs ...
[    0.120000] Idle Task [1] (ptrval)
[    0.120000] Trying to bring up CPU1 ...
[    1.120000] Timeout: CPU1 FAILED to come up !!!
[    1.120000] Idle Task [2] (ptrval)
[    1.120000] Trying to bring up CPU2 ...
[    2.120000] Timeout: CPU2 FAILED to come up !!!
[    2.120000] Idle Task [3] (ptrval)
[    2.120000] Trying to bring up CPU3 ...
[    3.120000] Timeout: CPU3 FAILED to come up !!!
[    3.120000] smp: Brought up 1 node, 1 CPU
[    3.130000] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    3.130000] futex hash table entries: 1024 (order: 4, 131072 bytes, linear)
[    3.140000] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    3.140000] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[    3.230000] SCSI subsystem initialized
[    3.230000] pps_core: LinuxPPS API ver. 1 registered
[    3.230000] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    3.230000] PTP clock support registered
[    3.250000] NET: Registered PF_INET protocol family
[    3.250000] IP idents hash table entries: 16384 (order: 4, 131072 bytes, linear)
[    3.280000] tcp_listen_portaddr_hash hash table entries: 1024 (order: 0, 8192 bytes, linear)
[    3.280000] Table-perturb hash table entries: 65536 (order: 5, 262144 bytes, linear)
[    3.280000] TCP established hash table entries: 8192 (order: 2, 32768 bytes, linear)
[    3.280000] TCP bind hash table entries: 8192 (order: 4, 131072 bytes, linear)
[    3.280000] TCP: Hash tables configured (established 8192 bind 8192)
[    3.290000] UDP hash table entries: 512 (order: 1, 16384 bytes, linear)
[    3.290000] UDP-Lite hash table entries: 512 (order: 1, 16384 bytes, linear)
[    3.290000] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    3.290000] RPC: Registered named UNIX socket transport module.
[    3.290000] RPC: Registered udp transport module.
[    3.290000] RPC: Registered tcp transport module.
[    3.290000] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    3.320000] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    3.440000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    3.460000] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    3.480000] jitterentropy: Initialization failed with host not compliant with requirements: 2
[    3.480000] simple-pm-bus fpga: use noncoherent DMA ops
[    3.490000] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    3.510000] of_serial f0000000.serial: use noncoherent DMA ops
[    3.510000] printk: console [ttyS0] disabled
[    3.510000] f0000000.serial: ttyS0 at MMIO 0xf0000000 (irq = 24, base_baud = 3125000) is a 16550A
[    3.510000] printk: console [ttyS0] enabled
[    3.510000] printk: console [ttyS0] enabled
[    3.510000] printk: bootconsole [uart8250] disabled
[    3.510000] printk: bootconsole [uart8250] disabled
[    3.660000] brd: module loaded
[    3.680000] sdhci: Secure Digital Host Controller Interface driver
[    3.680000] sdhci: Copyright(c) Pierre Ossman
[    3.680000] Synopsys Designware Multimedia Card Interface Driver
[    3.680000] sdhci-pltfm: SDHCI platform and OF driver helper
[    3.700000] NET: Registered PF_INET6 protocol family
[    3.720000] Segment Routing with IPv6
[    3.720000] In-situ OAM (IOAM) with IPv6
[    3.720000] NET: Registered PF_PACKET protocol family
[    3.720000] 8021q: 802.1Q VLAN Support v1.8
[    4.190000] Freeing unused kernel image (initmem) memory: 7504K
[    4.190000] This architecture does not have kernel memory protection.
[    4.190000] Run /init as init process
[    4.190000]   with arguments:
[    4.190000]     /init
[    4.190000]   with environment:
[    4.190000]     HOME=/
[    4.190000]     TERM=linux
[    5.440000] init: Console is alive
[    5.470000] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    5.510000] usbcore: registered new interface driver usbfs
[    5.510000] usbcore: registered new interface driver hub
[    5.510000] usbcore: registered new device driver usb
[    5.530000] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    5.550000] init: - preinit -
[  255.050000] random: crng init done
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[  258.410000] procd: - early -
[  259.200000] procd: - ubus -
[  259.360000] procd: - init -
Please press Enter to activate this console.



BusyBox v1.36.1 (2024-03-16 23:19:22 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r25408-b717db86e5
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@(none):/# uname -a
Linux (none) 6.1.80 #0 SMP PREEMPT Thu Mar  7 11:17:13 2024 arc GNU/Linux
root@(none):/#
```

**Comment by robimarko** [comment]
Great, thank you

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
