### PR TITLE
[22.03] mbedtls: import patch to fix illegal instruction on mpc85xx

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Import patch as workaround for gcc-11.2.0.

### CODE REVIEW

**Comment by ynezz** [comment]
> Import patch as workaround for gcc-11.2.0

BTW import from where exactly? I can't find it upstream. IMO if it fixes upstream issue https://github.com/Mbed-TLS/mbedtls/issues/6430 then it should be sent upstream.

It would help to include more context in the commit message, for example reference related https://github.com/openwrt/openwrt/pull/11003, https://github.com/openwrt/packages/pull/19609 and https://github.com/Mbed-TLS/mbedtls/issues/6430 issues for more context.

**Comment by hauke** [comment]
Why is this tarted at OpenWrt 22.03 and not against master?
Does this problem not exists on master?

**Comment by hauke** [comment]
should we add this workaround or should we backport the fix for the toolchain?

**Comment by hauke** [comment]
Thank you for the patch, I applied it to the openwrt-22.03 branch in commit de6c3cca4d2b523937403ae2959597a1e48c7351.

**Comment by PolynomialDivision** [comment]
Sorry, that was a bit to quick. I was still working on that. :S Just tested it and it did not change anything. But maybe I also did a mistake while compiling it. So let me test again when buildbot builded everything. Next time I mark it again as [WIP]. Sorry.

**Pull request closed without merging**
