### PR TITLE
qualcommax: add ramoops memory region

### PR DESCRIPTION
**Pull request by qosmio**
This patch adds support for allocating reserved memory for ramoops. This is required to get PSTORE option working.

Tested with the following options:

```
CONFIG_PACKAGE_kmod-pstore=y
CONFIG_PACKAGE_kmod-ramoops=y
CONFIG_PACKAGE_kmod-reed-solomon=y
```

dmesg output
```console
➤ dmesg | grep -Ei "psto|ramo"

[Sun Jun  9 23:22:01 2024] OF: reserved mem: 0x0000000051200000..0x00000000512fffff (1024 KiB) map non-reusable ramoops@51200000
[Sun Jun  9 23:22:05 2024] pstore: Using crash dump compression: deflate
[Sun Jun  9 23:22:05 2024] pstore: Registered ramoops as persistent store backend
[Sun Jun  9 23:22:05 2024] ramoops: using 0x100000@0x51200000, ecc: 0
```

Triggering kernel panic

```bash
sh -c 'echo 10 > /proc/sys/kernel/panic; echo c > /proc/sysrq-trigger'
```

After rebooting

```bash
mkdir -p /tmp/ramoops
mount -t pstore pstore /tmp/ramoops
```

```bash
➤ l /tmp/ramoops
drwxr-x---    2 root     root           0 Jun  9 23:02 .
drwxr-xr-x    8 root     root        4.0K Jun  9 23:23 ..
-r--r--r--    1 root     root        6.6K Jun  9 23:21 dmesg-ramoops-0
```

Truncated output
```console
Panic#1 Part1
<6>[   21.656119] remoteproc remoteproc0: remote processor cd00000.q6v5_wcss is now up
<14>[   21.657910] kmodloader: done loading kernel modules from /etc/modules.d/*
<6>[   21.710545] ath11k c000000.wifi: chip_id 0x0 chip_family 0x0 board_id 0xff soc_id 0xffffffff
<6>[   21.710594] ath11k c000000.wifi: fw_version 0x270204a5 fw_build_timestamp 2022-08-04 13:05 fw_build_id WLAN.HK.2.7.0.1-01744-QCAHKSWPL_SILICONZ-1
<6>[   91.416867] br-lan: topology change detected, sending tcn bpdu
<6>[ 1256.023874] sysrq: Trigger a crash
<0>[ 1256.023911] Kernel panic - not syncing: sysrq triggered crash
<4>[ 1256.026176] CPU: 2 PID: 2842 Comm: sh Tainted: G           O       6.6.32 #0
<4>[ 1256.031993] Hardware name: Linksys MX5300 (DT)
<4>[ 1256.039106] Call trace:
<4>[ 1256.043354]  dump_backtrace+0xb0/0x10c
<4>[ 1256.045701]  show_stack+0x18/0x24
<4>[ 1256.049519]  dump_stack_lvl+0x48/0x60
<4>[ 1256.052906]  dump_stack+0x18/0x24
<4>[ 1256.056550]  panic+0x2d0/0x31c
<4>[ 1256.059848]  sysrq_handle_moom+0x0/0x30
<4>[ 1256.062800]  __handle_sysrq+0xe4/0x1e0
<4>[ 1256.066534]  write_sysrq_trigger+0xbc/0xfc
<4>[ 1256.070354]  proc_reg_write+0xb0/0xf8
<4>[ 1256.074434]  vfs_write+0xa4/0x298
<4>[ 1256.078165]  ksys_write+0x5c/0xe0
<4>[ 1256.081464]  __arm64_sys_write+0x1c/0x28
<4>[ 1256.084763]  invoke_syscall.constprop.0+0x5c/0x100
<4>[ 1256.088758]  do_el0_svc+0x40/0xc8
<4>[ 1256.093355]  el0_svc+0x30/0xb8
<4>[ 1256.096740]  el0t_64_sync_handler+0x120/0x12c
<4>[ 1256.099694]  el0t_64_sync+0x178/0x17c
<2>[ 1256.104122] SMP: stopping secondary CPUs
<0>[ 1256.107773] Kernel Offset: disabled
<0>[ 1256.111759] CPU features: 0x0,00000000,00000000,0000400b
<0>[ 1256.114975] Memory Limit: none
```

The only verified board where this patch doesn't seem to work is `dl-wrx36`. Shows error -28 (AKA `No space left on device`).

```console
[  200.982390] SMP: stopping secondary CPUs
[  200.986039] Kernel Offset: disabled
[  200.990026] CPU features: 0x0,00000000,00000000,0000400b
[  200.993242] Memory Limit: none
[  202.003031] pstore: backend (ramoops) writing error (-28)
[  202.003054] Rebooting in 10 seconds..
```

I tried changing the offset to be further down, as the DTS for DL-WRX36 shows `wifi_dump` and `wigig_dump` reserved where ramoops would be.

```dts
  wifi_dump@51100000 {
	  no-map;
	  reg = <0x00 0x51100000 0x00 0x600000>;
  };
  
  wigig_dump@51300000 {
	  no-map;
	  reg = <0x00 0x51300000 0x00 0x400000>;
  };

  ramoops_region: ramoops@51800000 {
	  compatible = "ramoops";
	  reg = <0x0 0x51800000 0x0 0x100000>;
	  no-map;
	  record-size = <0x1000>;
  };
```

Figured even though we're not specifically reserving that region, it was somehow "off limits". Not sure if it's U-boot related that is blocking from writing to any region.

The current boards tested:

**IPQ807x**
|Model|Size|Working|
|--- | --- | :---: |
AX3600 Xiaomi|512M|**Y**
Dynalink DL-WRX36|1G|**N**
Linksys MX5300|1G|**Y**
QNAP 301w|1G|**Y**
Xiaomi AX9000|1G|?
Zyxel NBG7815|1G|**Y**

**IPQ6018**
|Model|Size|Working|
|--- | --- | :---: |
GLiNet AXT1800|512M|**Y**

Untested
**IPQ807x**
|Model|Size|Working|
|--- | --- | :---: |
8devices Mango-DVK|1G|?
Arcadyan AW1000|1G|?
Buffalo WXR-5950AX12|1G|?
CMCC RM2-6|512M|?
Compex WPQ873|1G|?
Edgecore EAP102|1G|?
Edimax CAX1800|512M|?
Linksys MX4200v1|512M|?
Linksys MX4200v2|1G|?
Linksys MX8500|1G|?
Netgear RAX120v2|1G|?
Netgear SXR80|1G|?
Netgear SXS80|1G|?
Netgear WAX218|512M|?
Netgear WAX620|1G|?
Netgear WAX630|1G|?
prpl Foundation Haze|1G|?
Spectrum SAX1V1K|1G|?
Yuncore AX880|1G|?
Yuncore FAP650|512M|?
Zbtlink ZBT-Z800AX|1G|?
ZTE MF269|512M|?

EDIT: Removed incorrect model "Arcadyan MF269"

### CODE REVIEW

**Comment by rmandrad** [comment]
I've tested this both on the qnap and ax9000

**Comment by aiamadeus** [comment]
> Arcadyan MF269
> ZTE MF269

It should be 'ZTE MF269'.

**Comment by qosmio** [comment]
@aiamadeus , thanks, I've updated the PR.

**Comment by Neustradamus** [comment]
@legale: Have you seen this PR?

Can you check:
- Yuncore AX880
- Yuncore FAP650

Thanks in advance.

**Comment by innovara** [comment]
I've been investigating recently pstore and ramoops and I have some comments for your consideration.

Since there are only a few devices confirmed to be working, would it not make more sense to add the allocation of reserved memory to each confirmed device's dts file and drop the 'blanket' patches that affect to all the devices?

For example, adding the following to `target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq8071-ax3600.dts` without the patches would effectively do the same, but it would be self contained and maybe more likely to be merged.

```
/ { 
	reserved-memory {
		ramoops_region: ramoops@4e900000 {
			compatible = "ramoops";
			reg = <0x0 0x4e900000 0x0 0x100000>;
			no-map;
			record-size = <0x1000>;
		};
	};
};
```
Each device might need different regions and this approach gives you more granular control over the region reserved for ramoops.

Another aspect that needs some consideration according to what I've seen is how `ramoops_region` is modified in `target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq6018-512m.dtsi` and `target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq8074-512m.dtsi`.

For example, `ipq8074-512m.dtsi` is like this:
```
&ramoops_region {
	reg = <0x0 0x4e900000 0x0 0x100000>;
};
```
That leaves you with a node with a node-name@unit-address from `ipq8074.dtsi` which is `ramoops@51200000` but at `0x4e900000` which breaks the convention. I believe in such case you have to delete the node and create it again. It would be something like this following the previous example:

```
/delete-node/ &ramoops_region;

/ { 
	reserved-memory {
		ramoops_region: ramoops@4e900000 {
			compatible = "ramoops";
			reg = <0x0 0x4e900000 0x0 0x100000>;
			no-map;
			record-size = <0x1000>;
		};
	};
};
```
 Which kind of takes you back to avoid the patch to `ipq8074.dtsi` in the first place.

Either way, I think the per-device approach is less intrusive and can gain more traction and benefit those who have the device and have tested that ramoops works on their devices at the region reserved on the corresponding dts file.

**Comment by innovara** [comment]
I tested this patch on a recent build and it works on my (2) MX4200v2.

**Comment by Neustradamus** [comment]
@qosmio: Why have you closed your PR?

**Pull request closed without merging**
