### PR TITLE
[22.03] ramips: add support for MTS WG430223

### PR DESCRIPTION
**Pull request by csharper2005**
This is a backport of https://github.com/openwrt/openwrt/pull/9805.

- ramips: allow custom trx magic for Arcadyan (fixed merging conflict in mt7621.mk) - https://github.com/openwrt/openwrt/commit/109c503bee9aed34ffb485a29af1e2ec6f3bb6b1
- ramips: create new dtsi for Arcadyan routers (clean cherry-pick) - https://github.com/openwrt/openwrt/commit/5b59137a162c07738abbe9fd37125193b3107cb7
- ramips: add support for MTS WG430223 (clean cherry-pick) https://github.com/openwrt/openwrt/commit/498c15376bae109bfe130cc5581f83e4cc52c0f9

[Device page on WiKi](https://openwrt.org/toh/mts/wg430223)
--------------------

MTS WG430223 is a wireless AC1300 (WiFi 5) router manufactured by Arcadyan company. It's very similar to Beeline Smartbox Flash (Arcadyan WG443223).

Device specification
--------------------
SoC Type: MediaTek MT7621AT
RAM: 128 MiB
Flash: 128 MiB (Winbond W29N01HV)
Wireless 2.4 GHz (MT7615DN): b/g/n, 2x2
Wireless 5 GHz (MT7615DN): a/n/ac, 2x2
Ethernet: 3xGbE (WAN, LAN1, LAN2)
USB ports: No
Button: 1 (Reset/WPS)
LEDs: 2 (Red, Green)
Power: 12 VDC, 1 A
Connector type: Barrel
Bootloader: U-Boot (Ralink UBoot Version: 5.0.0.2)
OEM: Arcadyan WG430223

Installation
------------
1. Login to the router web interface (superadmin:serial number)
2. Navigate to Administration -> Miscellaneous -> Access control lists & enable telnet & enable "Remote control from any IP address"
3. Connect to the router using telnet (default admin:admin)
4. Place *factory.trx on any web server (192.168.1.2 in this example)
5. Connect to the router using telnet shell (no password required)
6. Save MAC adresses to U-Boot environment:
```
   uboot_env --set --name eth2macaddr --value $(ifconfig | grep eth2 | \
    awk '{print $5}')
   uboot_env --set --name eth3macaddr --value $(ifconfig | grep eth3 | \
    awk '{print $5}')
   uboot_env --set --name ra0macaddr --value $(ifconfig | grep ra0 | \
    awk '{print $5}')
   uboot_env --set --name rax0macaddr --value $(ifconfig | grep rax0 | \
    awk '{print $5}')
```
7. Ensure that MACs were saved correctly:
```   
   uboot_env --get --name eth2macaddr
   uboot_env --get --name eth3macaddr
   uboot_env --get --name ra0macaddr
   uboot_env --get --name rax0macaddr
```
8. Download and write the OpenWrt images:
```
   cd /tmp
   wget http://192.168.1.2/factory.trx
   mtd_write erase /dev/mtd4
   mtd_write write factory.trx /dev/mtd4
```
10. Set 1st boot partition and reboot:
```
   uboot_env --set --name bootpartition --value 0
```
Back to Stock
-------------
1. Run in the OpenWrt shell:
```
   fw_setenv bootpartition 1
   reboot
```
2. Optional step. Upgrade the stock firmware with any version to overwrite the OpenWrt in Slot 1.

MAC addresses
-------------
```
+-----------+-------------------+----------------+
| Interface | MAC               | Source         |
+-----------+-------------------+----------------+
| label     | A4:xx:xx:51:xx:F4 | No MACs was    |
| LAN       | A4:xx:xx:51:xx:F6 | found on Flash |
| WAN       | A4:xx:xx:51:xx:F4 | [1]            |
| WLAN_2g   | A4:xx:xx:51:xx:F5 |                |
| WLAN_5g   | A6:xx:xx:21:xx:F5 |                |
+-----------+-------------------+----------------+
```
[1]:
a. Label wasb't found neither in factory nor in other places.
b. MAC addresses are stored in encrypted partition "glbcfg". Encryption key hasn't known yet. To ensure the correct MACs in OpenWrt, a hack with saving of the MACs to u-boot-env during the installation was applied.
c. Default Ralink ethernet MAC address (00:0C:43:28:80:A0) was found in "Factory" 0xfff0. It's the same for all MTS WG430223 devices. OEM firmware also uses this MAC when initialazes ethernet driver. In OpenWrt we use it only as internal GMAC (eth0), all other MACs are unique. Therefore, there is no any barriers to the operation of several MTS WG430223 devices even within the same broadcast domain.

Stock firmware image format
---------------------------
The same as Beeline Smartbox Flash but with another trx magic
```
+--------------+---------------+----------------------------------------+
| Offset       |               | Description                            |
+==============+===============+========================================+
| 0x0          | 31 52 48 53   | TRX magic "1RHS"                       |
+--------------+---------------+----------------------------------------+
```

### CODE REVIEW

**Comment by MaxS0niX** [comment]
@Ansuel Are there any other changes required in the Pull Request?) Or just wait for a free maintainer for now?)

**Comment by csharper2005** [comment]
> Are there any other changes required in the Pull Request?) Or just wait for a free maintainer for now?)

@MaxS0niX Hope they were just waiting for me to find and fix the funny mistake. Cherry-pick was supposed to be from the OpenWrt repository, not mine own.

@Ansuel isn't it?

**Comment by Ansuel** [comment]
@adschm @rsalvaterra Should we backport this considering the problem with mac address

**Comment by csharper2005** [comment]
@Ansuel the [almost similar device](https://github.com/openwrt/openwrt/commit/f8b02130d2cd3b919c1292bc8ee8870f66794536) is already merged in 22.03. The workaround is known and reliable. So, nothing bad even if we keep everything as it is. If we found a clean solution here https://github.com/openwrt/openwrt/issues/10062 then we will apply it to both devices in one commit. Furthermore, that commit will be cherry-pickable from master to 22.03 branch.

**Comment by csharper2005** [comment]
> @adschm @rsalvaterra Should we backport this considering the problem with mac address

@Ansuel, the problem with mac address?
- The [almost similar device](https://github.com/openwrt/openwrt/commit/f8b02130d2cd3b919c1292bc8ee8870f66794536) is already merged in 22.03
- The workaround is known and reliable: We store the 100% **real** MACs in u-boot-env and don't use flipped byte like in other cases

Thus, could you explain, please, risks and impact you expect? Let's try to describe a "problem" together.

P.S. If we found a clean solution here https://github.com/openwrt/openwrt/issues/10062 then we will apply it to both devices in one commit. Furthermore, in this case the commit can be cherry-picked from master to 22.03 branch untouched (or with minimal correction).
P.P.S. Unfortunately, @adschm is a rare visitor here at the time.

**Comment by ynezz** [comment]
Thanks, merged in 464f349fadb

**Pull request closed without merging**
