### PR TITLE
dante: update to 1.4.3

### PR DESCRIPTION
**Pull request by yangfl**
Maintainer: @jow- 
<s>Test required, I don't have a suitable openwrt device for testing :(</s>Tested: ath79 19.07.2

### CODE REVIEW

**Comment by ynezz** [comment]
You're missing commit description

**Comment by yangfl** [comment]
hm, what description?

**Comment by ynezz** [comment]
> hm, what description?

```
Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.
```

so quoting from https://openwrt.org/submitting-patches

```
 commit description

    must have less than 75 characters per line
    it will be committed to the source changelog, so it should explain to a competent reader why you made this commit.
    Include symptoms of the failure you are fixing (log messages, error messages, etc.), it will be useful for
    people searching the commit logs looking for a fix for their issue.
    If a patch fixes a compile failure, include only the most relevant part of the failure log
```

**Comment by yangfl** [comment]
I thought the commit title should have explained itself, but nah

Compiled & tested 18.06.1 ar71xx

**Comment by adrianschmutzler** [comment]
@yangfl This should be updated and tested with recent master.

Please update or close if you don't want to continue with this matter.

**Comment by yangfl** [comment]
updated

**Comment by adrianschmutzler** [comment]
@jow- Maybe you can check this?

**Comment by yangfl** [comment]
?

**Comment by aparcar** [comment]
Could we move this to `packages.git`?

**Comment by bobafetthotmail** [comment]
why are you updating this if you "don't have a suitable OpenWrt device for testing"?

Even using a virtual machine or a normal PC is enough.

**Comment by yangfl** [comment]
OK I should have mentioned that I've tested it on my router long before.

**Comment by yangfl** [comment]
any progress?

**Comment by aparcar** [comment]
Sorry do you mind updating to 1.4.3?

**Comment by yangfl** [comment]
@aparcar updated

**Comment by aparcar** [comment]
@yangfl Since the openwrt.git developers are chronically overloaded, would you be okay with moving this to packages? @neheb do you have an opinion on that?

**Comment by yangfl** [comment]
@aparcar yes, would be happy to adopt this package!

**Comment by aparcar** [comment]
@yangfl amazing! Please create a PR over at packages.git and ping me once it's done. I'll remove `dante` from `openwrt.git` once it's migrated over. Closing this

**Pull request closed without merging**
