### PR TITLE
kernel: r8125/r8126: add CONFLICT to rss variant

### PR DESCRIPTION
**Pull request by aiamadeus**
The rss variant should conflict with the default.

### CODE REVIEW

**Review by Noltari — APPROVED** [review]
LGTM, but we should probably bump PKG_RELEASE

**Comment by aiamadeus** [comment]
> LGTM, but we should probably bump PKG_RELEASE

The package content has not changed, so I think it might not be needed?

**Comment by Noltari** [comment]
> The package content has not changed, so I think it might not be needed?

I'm not completely sure about this one, TBH...

**Comment by Noltari** [comment]
Merged, thanks!

**Pull request closed without merging**
