### PR TITLE
valgrind: update to 3.14.0

### PR DESCRIPTION
**Pull request by wongsyrone**
Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
Runtime/Compiled tested on?

**Comment by wongsyrone** [comment]
Compile and run tested on x64

**Comment by dedeckeh** [comment]
Superseded by commit https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=7e173b43314d064e7e8a6837b7767a731a092537

**Comment by wongsyrone** [comment]
That commit has the wrong title(4.14? you are drunk), didn't refresh the patch, didn't enable the new LTO option. I cannot see why it's better.

**Comment by diizzyy** [comment]
@wongsyrone 
Unfortunately there seems to be a "race condition" when it comes to Github, vs patchwork and non reviewed commits. We all can do typos but your patch does seem a bit more polished in this case.

**Comment by wongsyrone** [comment]
I should send it via gmail, but gmail is really annoying to enable 'Allow Insecure Apps' every time before using `git send-email`.

**Comment by wongsyrone** [comment]
Just kidding. It would be better if someone takes care of other changes.

**Comment by xback** [comment]
@wongsyrone 
@dedeckeh 
@diizzyy 

Syrone,
I did indeed missed your PR as I'm not getting notifications currently of new PR's being submitted.

I was using valgrind during a debug session and noticed the available upgrade.

tbh, I accidentally pushed my very rough patch to Master iso my Staging tree ..
I've added an extra (script) check locally which warns me now that I'm about to push to master
to avoid this in the future.

Please feel free to send a subsequent patch which refreshes the patches and adds the LTO.

Ps. I can also officially confirm I was not drunk ..

**Comment by wongsyrone** [comment]
Thanks for the feedback. If you compiled the source, you might noticed there are lots of unrecognizable configure options, I'm wondering if I should remove those options.

**Pull request closed without merging**
