### PR TITLE
ath79: fix missing DEVICE_VENDOR for some devices

### PR DESCRIPTION
**Pull request by ptpt52**

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
NAND target is reworked completely here: https://github.com/openwrt/openwrt/pull/2184
Therefore, I would just leave the single device in it as it is for now, since it will be removed and readded anyway.

**Comment by ptpt52** [comment]
there is some more fixes
and if leave the nand we should leave `DEVICE_TITLE`
if we change we should change all to new variables
so it is OK to merge I think.

**Review by adschm — APPROVED** [review]
I think you are right. Merge this.

**Comment by dangowrt** [comment]
Cherry-picked, thanks!

**Pull request closed without merging**
