### PR TITLE
x86:Fix Model shows "Default String" issue in Luci overview page.

### PR DESCRIPTION
**Pull request by pr0zel**
Before:
56c4cae5-adce-4400-b016-690f2f8de76e

After:
03df3117-5867-46dc-a9fd-6be689265f2a

### CODE REVIEW

**Comment by edrikk** [comment]
I would love for the text to be correct, but as a data point, on my N100, all 4 of the files the 01_sysinfo file looks at (sys_vendor, board_vendor, product_name, and board_name) all contain "Default String" as the BIOS clearly hasn't been updated by the vendor.

bios_vendor is the only file that contains information --> "American Megatrends International, LLC."

Can in addition to looking for/at "Default String",  bios_vendor should be add to the vendor block?

**Comment by namiltd** [comment]
```
=== Checking commit '95c7f55ef2efe2644546b3fbe3ccfc6b90e3a373'
Author name (pr0zel) need to be your real name 'firstname lastname'
Commit subject line MUST start with '<area>: ' (x86:Fix Model shows "Default String" issue in Luci overview page.)
Signed-off-by match author
Missing commit message. Please describe your changes
Error: Process completed with exit code 1.
```

**Comment by pr0zel** [comment]
> I would love for the text to be correct, but as a data point, on my N100, all 4 of the files the 01_sysinfo file looks at (sys_vendor, board_vendor, product_name, and board_name) all contain "Default String" as the BIOS clearly hasn't been updated by the vendor.
> 
> bios_vendor is the only file that contains information --> "American Megatrends International, LLC."
> 
> Can in addition to looking for/at "Default String", bios_vendor should be add to the vendor block?

If you're the only user and want to customize, you can modify this file. Replace the string "echo "$vendor $product" > /tmp/sysinfo/model" with "echo "American Megatrends International, LLC." > /tmp/sysinfo/model". This should resolve your issue.

**Comment by edrikk** [comment]
Yes understand.  I was more eluding that given you’ve already created this PR for the purposes of a fix, to augment your PC to make it cover more cases.

Otherwise, the entire PR could be replaced by similar echo to file commands by users.

**Comment by pr0zel** [comment]
> Yes understand. I was more eluding that given you’ve already created this PR for the purposes of a fix, to augment your PC to make it cover more cases.
> 
> Otherwise, the entire PR could be replaced by similar echo to file commands by users. :)

Thank you for your information and suggestions. I will search for more details and see if there are any further modifications needed to the code. Thank you for your feedback. I will close this PR.
BTW: As I'm new to GitHub, please bear with me if I've made any mistakes. :)

**Comment by namiltd** [comment]
You closed the commit unnecessarily, removing the "Default String" made sense.

**Pull request closed without merging**
