### PR TITLE
tools/fakeroot: update to 1.31 and fix 32-bit compilation

### PR DESCRIPTION
**Pull request by misaka36**
Release Note:
https://tracker.debian.org/media/packages/f/fakeroot/changelog-1.31-1

Add a patch to revert upstream commit
3ff3bab429efbfc0e5b4a7941ae6beb8e17684b7 ("Wrap time64 functions") to fix 32-bit compilation.

Signed-off-by: Linhui Liu <liulinhui36@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
revert upstream commit

```
3ff3bab429efbfc0e5b4a7941ae6beb8e17684b7.
```

and add as a patch here to fix 32-bit compilation.

**Comment by lovehackintosh** [comment]
@neheb Done, thanks.

**Comment by lovehackintosh** [comment]
@mpratt14 Can you test this again?

**Comment by mpratt14** [comment]
yes it works with that revert patch

but I'm strongly against the idea of bumping to the new version, I don't see why we need it, and to make it work we are removing one of the only changes. You can count the changes between 1.29 and 1.31 with one hand....and this is a critical build tool, without critical changes in that time

**Comment by lovehackintosh** [comment]
@mpratt14 I agree with you. Let’s close this.

**Pull request closed without merging**
