### PR TITLE
kernel: config: add symbol introduced with 6.2

### PR DESCRIPTION
**Pull request by CharlesMengCA**
CONFIG_DEBUG_INFO_COMPRESSED_ZSTD, required by  GCC 13.0+

Compress the debug information using zstd. This may provide better compression than zlib, for about the same time costs, but requires newer toolchain support. Requires GCC 13.0+ or Clang 16.0+, binutils 2.40+, and zstd.

### CODE REVIEW

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by 981213** [comment]
This commit is missing a valid e-mail address, the commit description lines aren't wrapped, and a name in `first_name last_name` format (e.g. `Charles Meng`) will be better.

**Comment by robimarko** [comment]
Yeah, gotta watch out more for formal issues.

**Comment by robimarko** [comment]
I have reverted the commit as it doesn't comply with formal requirements and will investigate why our formal CI check was not run against this PR.

So, please reopen this PR or open a new one that complies with formal requirements, namely the email, commit description line length etc

**Pull request merged**
