### PR TITLE
ar71xx: Update TP-LINK CPE510 V2.0 to have its own profile

### PR DESCRIPTION
**Pull request by apcameron**
This updates the TP-LINK CPE510 V2.0 to have its own profile
	instead of sharing the CPE510 V1.0 profile

Installation:
 	Flash factory image through stock firmware WEB UI
	or through TFTP
	To get to TFTP recovery just hold reset button while powering on for
	around 4-5 seconds and release.
	Rename factory image to recovery.bin
	Stock TFTP server IP:192.168.0.100
	Stock device TFTP adress:192.168.0.254

Signed-off-by: Andrew Cameron <apcameron@softhome.net>

### CODE REVIEW

**Comment by ynezz** [comment]
@apcameron Hi, it will depend on the maintainer decission, but I'm afraid, that `ar71xx` [is being slowly turned into maintenance mode](http://lists.infradead.org/pipermail/openwrt-adm/2018-December/000933.html), so you'll increase your chances for merge, if you could instead provide support for `TP-LINK CPE510 V2.0` to `ath79` platform (ar71xx successor), which is based on DTS. Thanks!

Other than that, your submission has some formal issues, please take a look at https://openwrt.org/submitting-patches and read it carefully, namely `Include in your commit message a short description of the hardware` is missing, then the commit subject should rather be `ar71xx: Add support for TP-LINK CPE510 V2.0`.

**Comment by apcameron** [comment]
@ynezz Openwrt already supports this device and so this is an Update not adding a new device. The goal is to get it to have its own binary instead of sharing the binary for the CPE510v1.0.

As far as porting to the ath79 platform  what documentation is out there on how to port a device from ar71xx to ath79? Currently this is not an option as the software I am using it with currently only supports the ar71xx branch.

**Comment by ynezz** [comment]
> so this is an update not adding a new device.

That's your view, from my point of view which is based on the content of this PR you're adding new device :-)

> documentation is out there on how to port a device from ar71xx to ath79

I don't think, that there's anything official, but I've stumbled upon https://forum.openwrt.org/t/porting-guide-ar71xx-to-ath79/13013/55

> Currently this is not an option as the software I am using it with currently only supports the ar71xx branch

Interesting, I'm wondering what kind of software would work only with ar71xx and not with the ath79. Anyway, I think, that this is not a valid reason for not migrating to ath79 platform.

**Comment by apcameron** [comment]
@ynezz The Ham Radio software I have has only got patches that will apply against the ar71xx branch. A future version will be based on ath79.
The Hardware Specs are the same as the [TP-LINK CPE510 V1.0](https://oldwiki.archive.openwrt.org/toh/tp-link/tl-cpe510) 
The difference is there is only 1 ethernet port.

**Comment by apcameron** [comment]
Closing this request and will attempt to create a version for the ath79 platform

**Pull request closed without merging**
