### PR TITLE
kernel: bump 5.15 to 5.15.84

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B
Run-tested: bcm2711/RPi4B

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by AQPSal** [comment]
RPI4B - bcmgenet does not seem to load since 5.15.83 - maybe a kernel configuration issue? Not technical enough to figure it out.

There seems to have been a pull request with some changes to the kconfig file for broadcom for that release.

**Comment by graysky2** [comment]
@AQPSal - not sure what you mean:
```
# dmesg|grep -i bcmg
[    0.257525] bcmgenet fd580000.ethernet: GENET 5.0 EPHY: 0x0000
[    1.943055] bcmgenet fd580000.ethernet: configuring instance for external RGMII (RX delay)
[    1.951979] bcmgenet fd580000.ethernet eth0: Link is Down
[    6.946351] bcmgenet fd580000.ethernet: configuring instance for external RGMII (RX delay)
[    6.955589] bcmgenet fd580000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
```

**Comment by AQPSal** [comment]
@graysky2 

Interesting - I tried snapshot with 5.15.83 in two different RPI4s and in both cases dmesg showed no bcmgenet (and therefore no interface). I even used a factory image to make sure it was not related to my configuration. Using an older snapshot with 5.15.80 worked properly (I do not have 5.15.82 but I recall that being the last one that loaded bcmgenet properly). Is there anything i could provide? Is this the right location to discuss this issue?

**Comment by graysky2** [comment]
@AQPSal - maybe the forums are a better place

**Review by BKPepe — APPROVED** [review]
- Run tested: mvebu/cortexa9, Turris Omnia.

**Pull request merged**
