### PR TITLE
mwlwifi: downgrade the 88W8964's firmware to 9.3.2.6

### PR DESCRIPTION
**Pull request by arinc9**
I've mailed a patch to openwrt-devel instead.
https://patchwork.ozlabs.org/project/openwrt/patch/20210722165406.1708-1-arinc.unal@gmail.com/

---
Avoid 88W8964 firmware 9.3.2.12 for Wi-Fi instabilities it causes on Linksys WRT3200ACM & WRT32X until fixes on master branch are backported to openwrt-21.02

A lot of users, me included, with Linksys WRT32X & WRT3200ACM devices experience often Wi-Fi cutouts on OpenWrt 21.02.0-rc3.
Here are people who had issues with 9.3.2.12 on WRT3200ACM. They no longer have the issue after installing OpenWrt 19.07 (which uses 9.3.2.6 firmware).

https://forum.openwrt.org/t/pre-compiled-updated-mwlwifi-drivers-for-stable-releases/3262/682

https://forum.openwrt.org/t/pre-compiled-updated-mwlwifi-drivers-for-stable-releases/3262/688

https://forum.openwrt.org/t/connectivity-issues-with-wifi/79003

https://forum.openwrt.org/t/users-needed-to-test-wi-fi-stability-on-linksys-wrt3200acm-wrt32x-on-openwrt-21-02-0-rc3/101700/2

https://forum.openwrt.org/t/users-needed-to-test-wi-fi-stability-on-linksys-wrt3200acm-wrt32x-on-openwrt-21-02-0-rc3/101700/14

https://forum.openwrt.org/t/users-needed-to-test-wi-fi-stability-on-linksys-wrt3200acm-wrt32x-on-openwrt-21-02-0-rc3/101700/16

I can confirm downgrading to 9.3.2.6 fixed the Wi-Fi cut-outs on my WRT32X.

https://forum.openwrt.org/t/users-needed-to-test-wi-fi-stability-on-linksys-wrt3200acm-wrt32x-on-openwrt-21-02-0-rc3/101700

---

This pull request uses the previous commit of mwlwifi repository used on OpenWrt 21.02 trunk, which 9.3.2.6 is used and the firmware works on Linux Kernel 5.3+.

Signed-off-by: Arınç ÜNAL <arinc.unal@gmail.com>

### CODE REVIEW

**Comment by rmandrad** [comment]
@arinc9 I have a WRT3200ACM running the master codebase & 5.10.50 & don't have any issues. It feels to me to be more an issue with the entire wifi stack and changes that were being made at that time of 21.02 ... do you have an open issue with the github mwlwifi ? maybe this way you could gather more feedback

**Comment by arinc9** [comment]
> WRT3200ACM running the master codebase & 5.10.50 & don't have any issues.

Looks like 5.10 was introduced recently to mvebu architecture. I'm going to try the trunk on my WRT32X, see if Wi-Fi is stable.

> do you have an open issue with the github mwlwifi ? maybe this way you could gather more feedback

No but good idea. If latest firmware works fine on the trunk, I see no reason to open an issue there, so this will wait for a while.

**Comment by arinc9** [comment]
@rmandrad I tried master branch with 5.4.132 & 5.10.51 kernels on latest firmware. The issue seems to be gone.

However, we don't have much time for the stable release of OpenWrt 21.02.0. Until whatever those changes on master are backported to openwrt-21.02 branch, this is a working fix that should be delivered with OpenWrt 21.02.0.

**Comment by arinc9** [comment]
Closing this PR, I've mailed a patch to the openwrt-devel instead.

https://patchwork.ozlabs.org/project/openwrt/patch/20210722165406.1708-1-arinc.unal@gmail.com/

**Comment by anomeome** [comment]
@rmandrad ,have you ever experienced the issue being addressed on any image. I see your moniker in the original [issue378](https://github.com/kaloz/mwlwifi/issues/378) when the BLOB was first extracted from the OEM FW to be tested. Some people started reporting this issue at that point, where many more never experienced any connectivity issues, I know I never did when I still used the radios on my rango. I suspect that the conclusion reached by BS at the end of that thread is correct.

**Comment by rmandrad** [comment]
Hi @anomeome yes I had some bad behaviour with one  client running an old intel wifi card ... changed it to a more recent card ax201 and things got ok ... the unstability on also got better with a few other fixes that came through, kernel upgrade ... I am unsure what has fixed the problem definetely the old intel wifi card didn't liked the mwlwifi upgrade but in the other hand I now get ax speeds !

**Comment by anomeome** [comment]
By way of another data point see [thread](https://forum.openwrt.org/t/21-02-rc3-on-wrt3200acm-wireless-5ghz-not-working/102173) opened today. No resolution from master image, both BLOBs work on 19.x, both fail on 21.x.

**Comment by rmandrad** [comment]
I am definetely not having this issue ... as I said I run snapshot with a new release everytime there is a kernel version (5.10) upgrade.... wondering if this is the problem .. 5.10 is not available on 21.x right?

**Comment by arinc9** [comment]
> 5.10 is not available on 21.x right?

No, however, wireless works fine on 5.4.x on trunk for me too.

**Pull request closed without merging**
