### PR TITLE
uhttpd: start when interface to listen becomes available

### PR DESCRIPTION
**Pull request by dangowrt**
Currently uhttpd won't start with a listening interface configured if the interface isn't already up at the time uhttpd starts. Make sure we attempt to start uhttpd when it comes up.

### CODE REVIEW

**Comment by aparcar** [comment]
Looks good

**Comment by jow-** [comment]
I would drop the elaborate IP->interface resolve logic and simply register an unconditional reload trigger for ifup events in case any non-`0.0.0.0` and non-`[::]` listen address is configured.

The reload will incur a bit of runtime overhead for running the init script but since the final command line won't change. uhttpd itself should see no unintended restarts unless it wasn't previously running due to an absent listen interface.

**Comment by dangowrt** [comment]
@jow- As uhttpd currently doesn't implement any dedicated reload logic (no SIGHUP handler or anything like that), a reload right now means kill and restart, and that is worth avoiding. Also, resolving the logical interface is done by relatively short functions `get_interface_by_ip` and `resolve_iface`, where as the ugly part of compiling a list of all listening IP addresses (by stripping the port and removing the brackets around IPv6 addresses) would still be needed even if we were to not care about the actual interface for addresses other than `0.0.0.0` and `[::]`...

**Comment by dangowrt** [comment]
Merged as 7b1c3068b74273af2370e433b3f476b65ddd123c

**Pull request closed without merging**
