### PR TITLE
kernel: bump 5.4 to 5.4.121

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: ipq806x/R7800
Run-tested: ipq806x/R7800

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by zuzia-dev** [comment]
Build system: x86_64
Build-tested: lantiq/xrx200/Easybox 904 xDSL (VGV952CJW33-E-IR)
Run-tested: lantiq/xrx200/Easybox 904 xDSL (VGV952CJW33-E-IR)

OK.

**Comment by rockdrilla** [comment]
Build system: x86_64
Build-tested: ath79/generic/TP-Link Archer C7 v2
Run-tested: ath79/generic/TP-Link Archer C7 v2

Works fine.

**Comment by Noltari** [comment]
@graysky2 bcm63xx/patches-5.4/434-nand-brcmnand-fix-OOB-R-W-with-Hamming-ECC.patch has been applied upstream and is no longer needed.

**Comment by graysky2** [comment]
@Noltari - Ah, I see it [listed for 5.4.119](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.4.119&id=e5b3e69eb36ac1178a7a2392616fd29afd288c4e) but the update script didn't catch it.

**Comment by graysky2** [comment]
I made a copy of my next branch [here](https://github.com/graysky2/openwrt/tree/next-copy).  Then went back to my next branch and removed the aforementioned patch updating the 5.4.119 commit.  Finally, I applied the 5.4.120 bump.  Both commit message were amended.  I am test building 5.4.120 now and will force push if successful.

Not sure if there is a cleaner way.

**Comment by graysky2** [comment]
@hauke - Thoughts on this?

**Comment by hauke** [comment]
Thank you for the patches, applied them to master.

**Pull request closed without merging**
