### PR TITLE
base-files: revert ipcalc exit with error and reenable server address inside DHCP range

### PR DESCRIPTION
**Pull request by yogo1212**
Analogous to two commits in https://github.com/openwrt/openwrt/pull/12925.

Comment for context: https://github.com/openwrt/openwrt/pull/12925#issuecomment-1649830184

### CODE REVIEW

**Comment by mpratt14** [comment]
maybe it's just me, but I feel like ipcalc.sh would be more robust and less error prone if it were not written in AWK

(besides the fact that I can barely understand AWK myself...)

**Comment by mpratt14** [comment]
i mean, even the shell can do this type of bitwise math, right? was AWK chosen for performance? I don't know much about the differences between the three, shell vs awk vs ucode

**Comment by yogo1212** [comment]
I have no idea why awk was chosen and I don't know ucode :sweat_smile: 
Probably, this PR (into the release branch) should only fix the bug.
Maybe add a comment on [the other PR](https://github.com/openwrt/openwrt/pull/12925)?

**Comment by mpratt14** [comment]
I'm just spitting ideas, and I think better readability of the source helps prevent issues like this.

**Comment by yogo1212** [comment]
@mpratt14 It does most definitely!
In [my first PR concerning ipcalc](https://github.com/openwrt/openwrt/pull/9857), I reduced nesting, split long lines of code - this time around it's a lot easier to work with.

**Comment by yogo1212** [comment]
Rebased + removed the previously present commits changing all the logic.
Instead, there's now a warning (rather than the error).

This should be merged to restore the configurations of those who have this kind of setup and rely on dnsmasq to not hand out the local address as a lease.
The proper, long-term fix should be discussed on the PR for the main branch (https://github.com/openwrt/openwrt/pull/12925).

**Comment by Ansuel** [comment]
@yogo1212 sorry for the delay. Hope you can still work on this.

2 question:
- Is it possible to first merge this in main and then backport? (or it wouldn't make sense?)
- please change the title to something more clear like `base-files: revert ipcal error and exit change to warning`

**Comment by yogo1212** [comment]
@Ansuel Hi :-)

The purpose of this PR was to have something that was easy to merge in order to restore the functionality in the release.
I guess that was a bit optimistic :smile: 

Before there's something to backport, we need to work out what change will be merged into main on the other PR.

**Comment by Ansuel** [comment]
@yogo1212 do you think changes on main will be good for backports or will be too much change?

Asking this, main will receive new feature or also additional fixup?

If they will be just new feature then I think it's ok with just this revert since no backport will happen.

(it's really just to finish working on 23.05 and focus on main about ipcal.sh)

**Comment by Ansuel** [comment]
@yogo1212 ok then I would merge this. Thanks for the clarification.

**Comment by yogo1212** [comment]
@ynezz is there a way to read program arguments in ucode?

the conversion of the functions was easy enough:
```
function bitcount(c) {
	c = ((c >> 0x01) & 0x55555555) + (c & 0x55555555);
	c = ((c >> 0x02) & 0x33333333) + (c & 0x33333333);
	c = ((c >> 0x04) & 0x0f0f0f0f) + (c & 0x0f0f0f0f);
	c = ((c >> 0x08) & 0x00ff00ff) + (c & 0x00ff00ff);
	c = ((c >> 0x10) & 0x0000ffff) + (c & 0x0000ffff);

	return c;
}

function ip2int(ip) {
	// iptoarr?
	let bytes = map(split(ip, "."), int);

	let ret = 0;
	for (x in bytes)
		ret = (ret << 8) | x;

	return ret;
}

function int2ip(ip) {
	let bytes = [
		ip >> 24 & 0xff,
		ip >> 16 & 0xff,
		ip >> 08 & 0xff,
		ip       & 0xff,
	];

	// arrtoip?
	return join(".", bytes);
}

function compl32(v) {
	return v ^ 0xffffffff;
}
```
(dumping here so anyone can pick it up)

**Comment by ynezz** [comment]
> @ynezz is there a way to read program arguments in ucode?

https://ucode.mein.io/tutorial-01-usage.html

> -D [name=]value: Define a global variable in the ucode program. If the name parameter is omitted, a JSON dictionary is  expected as the value, where each property becomes a global variable with its corresponding value. If name is specified, it defines a global variable with the provided value, parsed as JSON or as a literal string if JSON parsing fails.

Other options is to use [getenv](https://ucode.mein.io/module-core.html#getenv).

> the conversion of the functions was easy enough:

Ok, but my point was, that one can use [iptoarr](https://ucode.mein.io/module-core.html#iptoarr) core `ucode` functions already (IPv6 aware) and quite a lot of other helpers from [fw4.uc](https://github.com/openwrt/firewall4/blob/master/root/usr/share/ucode/fw4.uc).

**Pull request merged**
