### PR TITLE
[19.07] Cherry pick some fixes from the master branch

### PR DESCRIPTION
**Pull request by jerome-benoit**

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
@nbd Please check whether this is eligible for backport to 19.07.

**Comment by adrianschmutzler** [comment]
@nbd168 Please check whether this is eligible for backport to 19.07.

**Comment by jerome-benoit** [comment]
I know that I'm not a trusted OpenWRT contributor, but trust me, it's stable material :)

The kernel patch make frames not requiring ack on IEEE 80211 protocols to just not be counted as lost. 

The second allow to have the hostap CLI compiled with all the features required for debugging, whatever hostapd build type you are using.

**Comment by CodeFetch** [comment]
> I know that I'm not a trusted OpenWRT contributor, but trust me, it's stable material :)

Trust me, I'm an engineer

Sorry, I just couldn't miss the opportunity... What is the reason why you want this to be backported? This does not look critical and 20.x is on its way...

**Comment by jerome-benoit** [comment]
Because when I need to debug a Wifi AP running OpenWRT stable, I would like to not have:

* valid IEEE 8021 protocol frames marked as lost that mislead the diagnosis into the wrong direction and make you lost hours to find out that the frames was in fact not lost and that the pb is elsewhere;
* to rebuild wpa-cli because of missing features that I need to do proper debugging.

But maybe that's just me that thinks that the tools shipped on a stable firmware targeting Wifi router hardware should have a proper Wifi debugging tools suite that just works out of the box :)

**Comment by CodeFetch** [comment]
> But maybe that's just me that thinks that the tools shipped on a stable firmware targeting Wifi router hardware should have a proper Wifi debugging tools suite that just works out of the box :)

No, but I don't think this needs a maintenance release. As I said 20.x is on its way and efforts should be focused on the master branch.

**Comment by jerome-benoit** [comment]
You are just arguing that annoying bugs that encounter OpenWRT wifi router administrator in a stable release branch that just demands at least 1 min to be fixed by merging a PR backporting the relevant commits should not be fixed because that one minute time is too much time not focusing on the next stable release. Given the fact that a maintenance release on the 19.07 is anyhow on its way, welcome in pure nonsense. 

Take a deep breathe and restore your logical thinking instead of losing time arguing against merging genuine bug fixes in a stable release and make lose mine to argue against your faulty reasoning.

**Comment by CodeFetch** [comment]
@jerome-benoit Yes, minor issues that nobody except you cares about demanding adding and reviewing a kernel patch take too much time for backporting. It's not 1 minute we lost here. Not counted the nerves of your grumpy reply to: "Please be patient.". Patience is a virtue...

**Comment by ynezz** [comment]
Thanks! @nbd just acked it on IRC, I've merged it into the tree

**Pull request closed without merging**
