### PR TITLE
kirkwood: fix and tidy up

### PR DESCRIPTION
**Pull request by mans0n**
- fix boardname of ix2-200
- fix DEVICE_PACKAGES
- tidy up image Makefile
- tidy up hwmon_fancontrol

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Is patch 2 tested on device?

**Comment by mans0n** [comment]
Added a patch to convert DTS patches to plain files.

**Comment by mans0n** [comment]
@adrianschmutzler No, it's just build-tested.

**Comment by mans0n** [comment]
BTW, `ucidef_set_led_usbhost` and `ucidef_set_led_ataport` can also be replaced with `linux,default-trigger`.

**Comment by adrianschmutzler** [comment]
I will merge patches 1 and 3 in a minute. For patch 2, I'd like to have a device test (one would be enough).

Concerning patch 5 (the DTS stuff):
This is handled differently on different target and I have the impression that this is mostly taste. However, I would not want to change this (= merge it) without some additional opinion, so I would be happy if you could send patch 5 to the list. If there is a discussion, I would welcome it, if not, we can still merge it then.

**Comment by adrianschmutzler** [comment]
> BTW, ucidef_set_led_usbhost and ucidef_set_led_ataport can also be replaced with linux,default-trigger.

In principle, yes. However, this will again remove this configuration from direct access by the user. I personally feel that in these particular cases there is no sense in having this option exposed to the user by default, as the LEDs have a predefined purpose and will be properly set up. But in the past, I have felt some resistance when reducing direct user access.
So, as for the DTS changes, I'd like to have this through the mailing list for a bigger audience to complain (and preferably with device tests).

**Comment by mans0n** [comment]
> For patch 2, I'd like to have a device test (one would be enough).

What do you mean by a device test? Would you like to check if the hardware really needs the packages? Or if the packages are really broken?

> so I would be happy if you could send patch 5 to the mailing list.

Okay, I will.

As for the DTS trigger, I can live with the current board.d script, so I don't feel an urgent need to write a patch myself (for now).

**Comment by adrianschmutzler** [comment]
> What do you mean by a device test? Would you like to check if the hardware really needs the packages? Or if the packages are really broken?

I was targetting at this change:

"enabled I2C_MV64XXX in the kernel config, so we do not need kmod-i2c-mv64xxx in
DEVICE_PACKAGES."

Of course, we won't need device-testing for addition of kmod-hwmon-core.

**Comment by adrianschmutzler** [comment]
I've cut the kmod-hwmon-core changes out of your patch 2 and applied them, so the kmod-i2c-mv64xxx change will be left as a separate patch (rebase should solve that automatically).

**Comment by adrianschmutzler** [comment]
Just merged hwmon_fancontrol patch, too.

**Comment by mans0n** [comment]
> I was targetting at this change:
> "enabled I2C_MV64XXX in the kernel config, so we do not need kmod-i2c-mv64xxx in
DEVICE_PACKAGES."

Ah, I see. I'll explain more about it.
kmod-i2c-mv64xxx package was once there, and it was removed in 0d5ba94088ef.
https://github.com/openwrt/openwrt/commit/0d5ba94088efab1701c07c9ab65cdee38e16fcd3#diff-408ef098c7bef52dfaa7a4a8323d422eL137-L153
The only Kconfig which the package enabled was CONFIG_I2C_MV64XXX, so I thought it's obvious that I2C_MV64XXX superseded kmod-i2c-mv64xxx.
Anyway, kmod-i2c-mv64xxx does not exist anymore, so it's no use leaving it in DEVICE_PACKAGES.
on100 and ix2-200, which have kmod-i2c-mv64xxx in DEVICE_PACKAGES, were added after the package removal commit. Maybe the authors forgot to clean up...
I feel kirkwood is a bit dying target, and I don't expect somebody who can test it on on100 or ix2-200 will come out soon. The package is for i2c interface of kirkwood SoC, so it might be tested on other devices. What do you think?

**Comment by adrianschmutzler** [comment]
> Anyway, kmod-i2c-mv64xxx does not exist anymore, so it's no use leaving it in DEVICE_PACKAGES.
>on100 and ix2-200, which have kmod-i2c-mv64xxx in DEVICE_PACKAGES, were added after the package removal commit. Maybe the authors forgot to clean up...

I see your point, but what startles me is that having kmod-i2c-mv64xxx in DEVICE_PACKAGES still works without any warning or error, although is indeed has been removed.

**Comment by mans0n** [comment]
Umm, maybe that's because DEVICE_PACKAGES is a "default" list, not actual package list. For example, kmod-hwmon-lm* was in DEVICE_PACKAGES, but the package was not really included in the package list (due to the missing kmod-hwmon-core). I also tried adding "hello-im-here" in DEVICE_PACKAGES but I could not see any error during build. It would be much better if we have a mechanism to check if DEVICE_PACKAGES is indeed correct, though.

**Comment by adrianschmutzler** [comment]
> Umm, maybe that's because DEVICE_PACKAGES is a "default" list, not actual package list. For example, kmod-hwmon-lm* was in DEVICE_PACKAGES, but the package was not really included in the package list (due to the missing kmod-hwmon-core). I also tried adding "hello-im-here" in DEVICE_PACKAGES but I could not see any error during build.

That's a quite interesting insight. Based on that, I do not think I need to require testing anymore.
I would be helpful if you could also include a reference to https://github.com/openwrt/openwrt/commit/0d5ba94088efab1701c07c9ab65cdee38e16fcd3 in your commit message then, as in this commit (directly subsequent to the one you linked) the package i2c-mv64xxx was actually removed (making the inclusion in device_packages a "dead link").

**Comment by adrianschmutzler** [comment]
> It would be much better if we have a mechanism to check if DEVICE_PACKAGES is indeed correct, though.

Indeed. However, I'm not familiar enough with that part of the build process to do this myself soonish.

**Comment by mans0n** [comment]
Okay, done.

**Comment by adrianschmutzler** [comment]
Thanks, will merge the mv64xxx patch later today (when my ISP stops driving me mad ...)

**Comment by adrianschmutzler** [comment]
And merged. You can either keep this open for nicer view of the DTS patch or close it as you wish.

**Comment by mans0n** [comment]
I'll just keep this open for now.

**Comment by adrianschmutzler** [comment]
I will merge the DTS patch during the next hour, so we can close this already.

**Comment by mans0n** [comment]
Thank you for reviewing and merging, as always. :)

**Comment by adrianschmutzler** [comment]
Looking at this again, I have to remind myself to address the i2c-core selection issue at some point...

**Pull request closed without merging**
