### PR TITLE
[lede/17.01] sunxi: disable LPAE to allow kernel to run on A13

### PR DESCRIPTION
**Pull request by matteoscordino**
Fixes issue FS#1355.
LPAE extensions are enabled, but the A13 does not support them.
The result is the boot process stopping at "Starting kernel ..."

Signed-off-by: Matteo Scordino <matteo.scordino@gmail.com>

### CODE REVIEW

**Comment by ffainelli** [comment]
By disabling LPAE, are not you possibly causing one of the boards supported by this target to lose the extra memory that would be accessible with LPAE? Maybe you need to create a separate subtarget that has LPAE disabled?

**Comment by hauke** [comment]
LPAE was activated in this commit to get kvm support: 468735c3a2f75f4ae6592608c789d8753f418a84 
In master we already have different subtargets for the old A1X and the more recent Allwinner SoCs.

I think this pull request is ok.

**Comment by hauke** [comment]
@yousong and @wigyori  Can you comment on this

**Comment by matteoscordino** [comment]
@ffainelli I understand your concern; I think the problem does not apply to master at all as @hauke pointed out, and the intent of the patch is to be applied just to the lede-17.01 branch.

**Comment by yousong** [comment]
The change looks good to me as I think providing a working firmware out-of-the-box is a nice thing to have.  The LPAE was enabled previously to have KVM support and going through git log history sunxi/image/ I find no new board with RAM bigger than 4GB.

@matteoscordino , as the change is intended to be a bugfix, please also propose a pull request of the same kind against master branch, preferably only on `cortexa7/config-default`.

**Comment by hauke** [comment]
This is already fixed in master when I did the split into the multiple subtargets. @wigyori found it at that time because his board was not booting any more.
I will add this to the lede 17.01 branch soon.

**Comment by hauke** [comment]
Thank you for the patch it was applied to the lede-17.01 branch

**Pull request closed without merging**
