### PR TITLE
treewide: switch the timer frequency to 100 Hz

### PR DESCRIPTION
**Pull request by rsalvaterra**
Some targets select HZ=100, others HZ=250. There's no reason to select a higher
timer frequency (and 100 Hz are available in every architecture), so change all
targets to 100 Hz.

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by ldir-EDB0** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ldir.git

**Comment by rsalvaterra** [comment]
Have you noticed any regressions? The fact upstream has defaults doesn't mean they're sane defaults. Why on Earth would a router/gateway workload need such high frequency scheduling (250 or even 1000 Hz)? We're not exacly running DAWs on OpenWrt, are we? Lower frequencies are better for throughput (as in doing actual useful work and not wasting time scheduling unnecessarily).

**Comment by nbd168** [comment]
I'm not convinved that lower HZ settings are any better for throughput. Scheduling latency matters for routers as well, given that we have threaded NAPI and even softirq work is frequently bounced to ksoftirqd.

**Comment by nbd168** [comment]
I'm not 100% sure yet what an appropriate test case would be. I guess it might be interesting to use a lower performance platform (e.g. ath79) and compare throughput of 1-2 TCP flows while also putting some user space CPU load on the system.
I guess 4ms vs 10ms latency might make a difference.

**Comment by rsalvaterra** [comment]
> I'm not 100% sure yet what an appropriate test case would be. I guess it might be interesting to use a lower performance platform (e.g. ath79) and compare throughput of 1-2 TCP flows while also putting some user space CPU load on the system.
> I guess 4ms vs 10ms latency might make a difference.

I have a TL-WDR3600 with the CPU at 680 MHz (overclocked) and 100 Hz, also without noticeable differences. As for user space load, I can use Tor, the crypto is quite intensive. Would that be a useful test?

**Pull request closed without merging**
