### PR TITLE
kernel: bump 5.4 to 5.4.113

### PR DESCRIPTION
**Pull request by graysky2**
Ran update_kernel.sh in a fresh clone without any existing toolchains.  No manual intervention needed.

Build system: x86_64
Build-tested: ipq806x/R7800
Run-tested: ipq806x/R7800

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by rockdrilla** [comment]
Build system: x86_64
Build-tested: ath79/generic (TP-Link Archer C7 v2)
Run-tested: ath79/generic (TP-Link Archer C7 v2)

**Comment by adschm** [comment]
Thanks, will pick the .110 commit for now.

**Comment by rockdrilla** [comment]
5.4.112 works for me too. Good job! :+1:

**Comment by hauke** [comment]
Thank you for the patches. I applied them to master.

**Pull request closed without merging**
