### PR TITLE
wireguard: Bump to 0.0.20190913

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by dedeckeh** [comment]
The PR has several formal issues :

-  it has no no SoB

- the commit title should start with wireguard:

- the commit description should contain a short description what has changed in this version

Please have a look at https://openwrt.org/submitting-patches

**Comment by remedieriez** [comment]
Changes since 0.0.20190702:

define conversion constants for ancient kernels
android: refactor and add incoming allow rules 
enforce that unused bits of flags are zero 
immediately rekey all peers after changing device private key
support running in OpenVZ environments
do not run bc on clean target
skip peers with invalid keys
account for upstream configuration maze changes
openbsd: fix alternate routing table syntax
account for android-4.9 backport of addr_gen_mode
don't fail down when using systemd-resolved 
allow specifying kernel release 
enforce named pipe ownership and use protected prefix
work around ubuntu breakage 
support newer PaX 
don't rewrite siphash when it's from compat
squelch warnings for stack limit on broken kernel configs
support rhel/centos 7.7

And what do you mean with no SoB?

Signed-off-by: Brandy Krueger krueger.brandy24@gmail.com

**Comment by lucize** [comment]
@remedieriez yes, but you should use git --amend to add the descriptions there and then force push the commit
github comments are irrelevant to git history

**Comment by dedeckeh** [comment]
Patch pushed to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=1fe1a200d9bbe83437b018757ad75364a6d89b37); thx
Make sure for future PRs the github author matches the SoB; I've fixed this manually now

**Pull request closed without merging**
