### PR TITLE
tools/gengetopt: Update to 2.23

### PR DESCRIPTION
**Pull request by diizzyy**
Update gengetopt to 2.23
Remove 100-dependency_fix.patch, fixed upstream
Rework no tests and docs patch
Fix typo in copyright section

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master
Run tested: mvebu, Linksys WRT3200ACM, OpenWrt master

**Comment by EXSERENS** [comment]
```
openwrt/build_dir/host/gengetopt-2.23/build-aux/missing: line 81: automake-1.16: command not found
WARNING: 'automake-1.16' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
Makefile:704: recipe for target 'Makefile.in' failed
```

**Comment by diizzyy** [comment]
Interesting, does adding back ```HOST_FIXUP := autoreconf``` fix it?

**Comment by EXSERENS** [comment]
> Interesting, does adding back `HOST_FIXUP := autoreconf` fix it?

after add it back, build and run without problem.

**Comment by diizzyy** [comment]
@EXSERENS 
Thanks, I'll add that back later tonight

**Comment by diizzyy** [comment]
Compile tested: ipq40xx, Linksys EA6350v3, OpenWrt master
Run tested: ipq40xx, Linksys EA6350v3, OpenWrt master

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
