### PR TITLE
global: config-6.6: cosmetic clean-up

### PR DESCRIPTION
**Pull request by graysky2**
Strictly a cosmetic clean-up by alphabetizing all config-6.6 files using the following script:
```
mapfile -t targets < <(find . -name 'config-6.6')

for i in "${targets[@]}"; do
  awk -F'# ' '
    {
        if ($1) {
            key = $1
        } else {
            key = $2
        }
        print key "\t" $0
    }
' "$i" | sort | cut -f2- > /tmp/sorted
mv /tmp/sorted "$i"
done
```

### CODE REVIEW

**Comment by namiltd** [comment]
If you run menuconfig and save for this configuration, will it stay in this order? Check it out because if so then this change makes no sense.

**Comment by namiltd** [comment]
If you run kernel_menuconfig and save for this configuration, will it stay in this order? Check it out because if so then this change makes no sense.

**Comment by graysky2** [comment]
No change to the commit using the modified sort call

**Comment by neheb** [comment]
I assume this is a repeat of https://github.com/openwrt/openwrt/pull/16743

I don't think this PR is right.

**Comment by graysky2** [comment]
I did not see that PR.  Looks like my code gave a slightly different answer than the one in that PR.  Closing this.  Thanks for that link.

**Pull request closed without merging**
