### PR TITLE
generic: 6.1: backport QCA807x PHY patches

### PR DESCRIPTION
**Pull request by Ansuel**
Backport QCA807x PHY patches merged upstream that introduce the new concept of PHY package.

All affected patch automatically refreshed with make target/linux/refresh.

### CODE REVIEW

**Comment by Ansuel** [comment]
@robimarko can you check if this is O.K. 

Also would be good to have some tester for ipq40xx if this works correctly

**Comment by robimarko** [comment]
It looks OK to me, though I haven't runtime tested this on ipq40xx which would probably be a good idea.

**Comment by xabolcs** [comment]
> Also would be good to have some tester for ipq40xx if this works correctly

I have a GL-B1300, used as wired AP.
Will it make sense to test as is? Or should I test it as a main router too?

I could build and test later tonight.

**Comment by Ansuel** [comment]
@xabolcs it's enough to test this on a router that has the malibu PHY and the ipq4019 dsa switch

**Comment by xabolcs** [comment]
> on a router that has the malibu PHY and the ipq4019 dsa switch

GL-B1300 isn't like that.

**Comment by robimarko** [comment]
> > on a router that has the malibu PHY and the ipq4019 dsa switch
> 
> GL-B1300 isn't like that.

It is, it doesnt disable QCA807x PHY and it uses the built-in switch.

**Comment by xabolcs** [comment]
> > GL-B1300 isn't like that.
> 
> It is, it doesnt disable QCA807x PHY and it uses the built-in switch.

:confused:

But it doesn't have that malibu PHY.
Anyway, I happily do the testing. :+1:

**Comment by Ansuel** [comment]
I tested this on my Fritz 7530 and works correctly! Lets see how it goes if anyone reports regression...

**Comment by motolav** [comment]
My dynalink is back with another issue, this driver on my router doesn't allow any network traffic through the lan ports but the dmesg log still reports when there's a wired connection just no IPs are assigned to devices downstream of the port.
The same config works with 23.05 and snapshot until now

**Comment by yyyzz123** [comment]
> My dynalink is back with another issue, this driver on my router doesn't allow any network traffic through the lan ports but the dmesg log still reports when there's a wired connection just no IPs are assigned to devices downstream of the port. The same config works with 23.05 and snapshot until now

same on ax9000

**Comment by robimarko** [comment]
I have found the issue, now looking at the root cause

**Comment by robimarko** [comment]
This should be fixed via:
https://github.com/openwrt/openwrt/commit/6497cdba09d6faa04a4f74465ed95ae21e2ff1ff

**Comment by xabolcs** [comment]
For the record: it works nicely on a GL-B1300 used as AP - built from r25136-[6497cdba09](https://github.com/openwrt/openwrt/commit/6497cdba09).

```
root@GL-B1300-078 ~ # dmesg | grep -i phy
[    0.000000] Booting Linux on physical CPU 0x0
[    0.198069] tcsr 194b000.tcsr: setting usb hs phy mode select = e700e7
[    1.269563] qca8k-ipq4019 c000000.switch lan2 (uninitialized): PHY [90000.mdio-1:02] driver [Qualcomm QCA8075] (irq=POLL)
[    1.348500] qca8k-ipq4019 c000000.switch lan1 (uninitialized): PHY [90000.mdio-1:03] driver [Qualcomm QCA8075] (irq=POLL)
[    1.428499] qca8k-ipq4019 c000000.switch wan (uninitialized): PHY [90000.mdio-1:04] driver [Qualcomm QCA8075] (irq=POLL)
[    7.381960] qca8k-ipq4019 c000000.switch lan1: configuring for phy/psgmii link mode
[  120.115095] qca8k-ipq4019 c000000.switch lan1: configuring for phy/psgmii link mode
[  120.163348] qca8k-ipq4019 c000000.switch lan2: configuring for phy/psgmii link mode
[  120.195876] qca8k-ipq4019 c000000.switch wan: configuring for phy/psgmii link mode
```

```
root@GL-B1300-078 ~ # dmesg | head
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 6.1.77 (xabolcs@ut2004) (arm-openwrt-linux-muslgnueabi-gcc (OpenWrt GCC 12.3.0 r25122-2253645411) 12.3.0, GNU ld (GNU Binutils) 2.40.0) #0 SMP Mon Feb 12 12:25:45 2024
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: GL.iNet GL-B1300
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000080000000-0x000000008fffffff]
[    0.000000]   HighMem  empty
```

**Pull request merged**
