### PR TITLE
kernel: bump 5.10 to 5.10.50

### PR DESCRIPTION
**Pull request by rsalvaterra**
No deleted or manually refreshed patches.

Run-tested:
ath79/generic (TL-WDR3600) - @rsalvaterra (up to .49)
mvebu/cortexa9 (Turris Omnia) - @rsalvaterra (up to .50)
x86/64 (APU2) - @ldir-EDB0 (.47 only)

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by anomeome** [comment]
compile / test : mvebu / mamba, rango

_thumb_ working again

**Comment by rsalvaterra** [comment]
@aparcar, shall I squash, or leave them separate?

**Comment by aparcar** [comment]
> @aparcar, shall I squash, or leave them separate?

Separate for bisecting i guess

**Comment by SkewedZeppelin** [comment]
.49 tested on shelby/caiman

**Comment by rockdrilla** [comment]
Compile/run-tested (.50): ath79/generic (Archer C7 v2).

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master.

**Pull request closed without merging**
