### PR TITLE
scripts: support the $ORIGIN only without back slash to specify rpath

### PR DESCRIPTION
**Pull request by yorkie**
2efe776 introduces the bad rpaths check with the following description:

> Remove all rpath entries which do not point to a location below /lib or
> /usr/lib and which do not begin with '$ORIGIN'.

However the implementation are "begin with '$ORIGIN/'", somehow we need
to support `$ORIGIN` without back slash, too.

/cc @jow-

### CODE REVIEW

**Comment by jow-** [comment]
This change would also match `$ORIGINFOO`, please use `/lib/[^/]*|/usr/lib/[^/]*|\$ORIGIN/*|\$ORIGIN)` as match pattern instead.

**Comment by yorkie** [comment]
Good point @jow-, I will apply :)

**Comment by yorkie** [comment]
@jow- I have updated :)

**Comment by yorkie** [comment]
Thanks @jow- :)

**Pull request closed without merging**
