### PR TITLE
[WIP,RFT,RFC] layerscape: Add support for 6.1 kernel version

### PR DESCRIPTION
**Pull request by CHKDSK88**
This PR is based on @Ansuel PR #11011.

It contains @wodu patches with layerscape packages bumped to lf-6.1 and initial support for 6.1 kernel. All testers and commenters are welcome. 

Compile tested: all
Run tested: LS1046A-RDB (NOR and SD card version)

Known regressions:
- ~nobody cared irq: https://github.com/openwrt/openwrt/pull/12440#issuecomment-1517843470~
- none

### CODE REVIEW

**Comment by CHKDSK88** [comment]
First issue:

```
[  235.114377] irq 63: nobody cared (try booting with the "irqpoll" option)
[  235.121085] CPU: 0 PID: 2561 Comm: irq/63-1-0051 Tainted: G         C         6.1 #0
[  235.128829] Hardware name: LS1046A RDB Board (DT)
[  235.133524] Call trace:
[  235.135961]  dump_backtrace.part.0+0xbc/0xcc
[  235.140230]  show_stack+0x18/0x40
[  235.143538]  dump_stack_lvl+0x68/0x84
[  235.147194]  dump_stack+0x18/0x34
[  235.150500]  __report_bad_irq+0x4c/0xdc
[  235.154328]  note_interrupt+0x2f4/0x350
[  235.158159]  handle_irq_event+0x9c/0xc0
[  235.161987]  handle_fasteoi_irq+0xa4/0x1f4
[  235.166075]  generic_handle_domain_irq+0x2c/0x44
[  235.170685]  gic_handle_irq+0x48/0xc4
[  235.174338]  call_on_irq_stack+0x2c/0x58
[  235.178252]  do_interrupt_handler+0x80/0x8c
[  235.182428]  el1_interrupt+0x34/0x6c
[  235.185996]  el1h_64_irq_handler+0x18/0x2c
[  235.190084]  el1h_64_irq+0x68/0x6c
[  235.193477]  _raw_spin_unlock_irq+0x40/0x50
[  235.197652]  irq_thread_fn+0x78/0x90
[  235.201221]  irq_thread+0x124/0x1f0
[  235.204703]  kthread+0x108/0x10c
[  235.207922]  ret_from_fork+0x10/0x20
[  235.211490] handlers:
[  235.213752] [<000000001f3c5e36>] irq_default_primary_handler threaded [<000000001a9e7d13>] pcf2127_rtc_irq
[  235.223410] Disabling IRQ #63
```

**Comment by Ansuel** [comment]
@CHKDSK88 btw i plan to refresh the 6.1 pr when we branch for the new release that way we will be able to drop all these additional commits

**Comment by Ansuel** [comment]
@CHKDSK88 added you commit

**Comment by aparcar** [comment]
Blocked until branch

**Comment by wodu** [comment]
I couldn't reproduce irq not handled bug mentioned above for ls1046ardb but amount of i2c interrupts is a bit scary so there is something wrong there.
I have got the warning for aquantia. I have rebased on latest openwrt master and kernel 6.1.25 and still there. Need to look at NXP branch for changes.
```
[  139.228742] ------------[ cut here ]------------
[  139.233386] Your devicetree is out of date, please update it. The AQR107 family doesn't support XGMII, maybe you mean USXGMII.
[  139.244841] WARNING: CPU: 2 PID: 5400 at drivers/net/phy/aquantia_main.c:700 aqr107_config_init+0x94/0xa4
[  139.254423] Modules linked in: pppoe ppp_async nft_fib_inet nf_flow_table_inet wireguard pppox ppp_generic nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject nft_redir nft_quota nft_objref nft_numgen nft_nat nft_masq nft_log nn
[  139.312780] CPU: 2 PID: 5400 Comm: ifconfig Not tainted 6.1.25 #0
[  139.318875] Hardware name: LS1046A RDB Board (DT)
[  139.323575] pstate: 40400005 (nZcv daif +PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[  139.330538] pc : aqr107_config_init+0x94/0xa4
[  139.334892] lr : aqr107_config_init+0x94/0xa4
```

I have also tested on ls1028ardb and I haven't seen any issues, yet. I will try to merge ls1028 before 6.1 as it works fine with 5.15.

**Comment by CHKDSK88** [comment]
@wodu 

> I couldn't reproduce irq not handled bug mentioned above for ls1046ardb but amount of i2c interrupts is a bit scary so there is something wrong there. I have got the warning for aquantia. I have rebased on latest openwrt master and kernel 6.1.25 and still there. Need to look at NXP branch for changes.
> 

Yeah, it generate dozen of IRQ. In my case it fail at the end.

>I have got the warning for aquantia. I have rebased on latest openwrt master and kernel 6.1.25 and still there. Need to look at NXP branch for changes.
> ```
> [  139.228742] ------------[ cut here ]------------
> [  139.233386] Your devicetree is out of date, please update it. The AQR107 family doesn't support XGMII, maybe you mean USXGMII.
> [  139.244841] WARNING: CPU: 2 PID: 5400 at drivers/net/phy/aquantia_main.c:700 aqr107_config_init+0x94/0xa4
> [  139.254423] Modules linked in: pppoe ppp_async nft_fib_inet nf_flow_table_inet wireguard pppox ppp_generic nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject nft_redir nft_quota nft_objref nft_numgen nft_nat nft_masq nft_log nn
> [  139.312780] CPU: 2 PID: 5400 Comm: ifconfig Not tainted 6.1.25 #0
> [  139.318875] Hardware name: LS1046A RDB Board (DT)
> [  139.323575] pstate: 40400005 (nZcv daif +PAN -UAO -TCO -DIT -SSBS BTYPE=--)
> [  139.330538] pc : aqr107_config_init+0x94/0xa4
> [  139.334892] lr : aqr107_config_init+0x94/0xa4
> ```
> 

IMO it isn't fixed in official NXP tree:
https://github.com/nxp-qoriq/linux/blob/29549c7073bf72cfb2c4614d37de45ec36b60475/drivers/net/phy/aquantia_main.c#L660
https://github.com/nxp-qoriq/linux/blob/29549c7073bf72cfb2c4614d37de45ec36b60475/arch/arm64/boot/dts/freescale/fsl-ls1046a-rdb.dts#L152

> I have also tested on ls1028ardb and I haven't seen any issues, yet. I will try to merge ls1028 before 6.1 as it works fine with 5.15.

Maybe one of coredevs will merge it before 23.X.

**Comment by CHKDSK88** [comment]
@HarmlessWarlock @cowgirlalexa

Please check how LS1088A work with 6.1 and MC complex enabled.

**Comment by cowgirlalexa** [comment]
@CHKDSK88 I can confirm 6.1 and MC complex are working! Nice work!

**Comment by wodu** [comment]
I have tried it on boards I have.
LS1046ARDB: When I rebase kernel to 6.1.25 I don't see IRQ problems on i2c anymore. What's left is 10G link with Aquantia which doesn't work. I see some changes in later kernel which might address this issue. I will try to backport them.
LS1043ARDB: No issues so far.
LS1028ARDB: No issues so far.
LS1012A FRWY: No issues so far.

**Comment by cowgirlalexa** [comment]
@aparcar @CHKDSK88 can this be unblocked and added to the master repo

**Comment by CHKDSK88** [comment]
After update to 6.1.29 "nobody cared irq" issue was gone. 

IMO it could go for wider testing.

**Comment by Ansuel** [comment]
@CHKDSK88 what is the state of this?

**Comment by wodu** [comment]
I have just got some time to look at it. I have rebased over latest master, synced patches and configs. I haven't seen any issues while testing on ls1012 Frwy and ls1028a-rdb board. Only what I have added is fixed uboot entry load address for ls1028 as it has sneaked in before you commits for 6.1 support. 
I have compiled it for all platforms without issues. I can test it on ls1043/ls1046 if you think it's needed.

**Comment by CHKDSK88** [comment]
> @CHKDSK88 what is the state of this?

@Ansuel Couple months ago it was ready. I will rebase and recheck it and let you know.

**Comment by CHKDSK88** [comment]
@Ansuel 
It need to be refreshed. I will do it next week.

**Comment by CHKDSK88** [comment]
@Ansuel 

It ran compile tests. Tomorrow I will put it on devices again.
Does CI do work with `KERNEL_TESTING_PATCHVER`?

**Comment by wodu** [comment]
I have just checked out, compiled and tested it on following devices:
* ls1012-frwy - no issues
* ls1028a-rdb - no issues and felix switch is working - I need to send one small change for uboot but I will do it in another PR
* ls1046a-rdb - no issues, ethernet tested on sgmii and rgmii with aquantia 10g support still missing (known issue mentioned in the thread)

@CHKDSK88
I have also ls1043a somewhere so I could test it tomorrow if you don't have the board.

**Comment by Ansuel** [comment]
@CHKDSK88 patch to refresh!

**Comment by Ansuel** [comment]
Also new config

**Comment by CHKDSK88** [comment]
I forgot to clean before the final check. Now should be ok.

**Comment by Ansuel** [comment]
@CHKDSK88 still an error... but i remember fixing that???? in theory uintptr_t should be used there

**Comment by Ansuel** [comment]
(buildbot and CI compile with WERROR so this is why)
warning are ok for develop but not ok when we merge code in openwrt. We started enforcing this following kernel change.

**Comment by CHKDSK88** [comment]
@Ansuel 
Ok, I was to hurry. Now Werror is ok.

I extracted your changes to separate commit for easier changes tracking. Maybe you can send PR to NXP tree (https://github.com/nxp-qoriq/linux)? The PPFE driver was  permanently rejected upstream and vendor tree is only source of it.

**Comment by Ansuel** [comment]
@CHKDSK88 aside from the single change, I will merge this once the thing si fixed!

**Pull request merged**
