### PR TITLE
Disable LTO on some packages

### PR DESCRIPTION
**Pull request by timocapa**
Just some packages I've ran into errors with LTO enabled

### CODE REVIEW

**Comment by timocapa** [comment]
Apology for the current bad title, I didn't have time to properly think of a good one.

**Comment by mpratt14** [comment]
are you using ccache at all when building?

**Comment by timocapa** [comment]
> are you using ccache at all when building?

```
# CONFIG_CCACHE is not set
CONFIG_CCACHE_DIR=""
```

Nope

**Comment by dhewg** [comment]
At least iwinfo and lua build fine here on ipq40xx with CONFIG_USE_LTO last I checked.
That arch are you building and what's the exact problem?

**Comment by timocapa** [comment]
> That arch are you building and what's the exact problem?

I'm building ramips/mt7621

I just recloned OpenWrt, HEAD `0eebc6f0ddb0791406d30530e3fc25d39428bd5a`, didn't add any feeds, basic config created and just built OpenWrt
```
    ERROR: package/utils/lua failed to build.
    ERROR: package/libs/libsepol failed to build.
```

This is the error log of lua: https://pastebin.com/raw/ByEhLLZw

Dead Code Elimination is off

**Comment by dhewg** [comment]
This seems to be MIPS specific, so I don't think disabling LTO for all targets is a nice solution.

lua already has `TARGET_CFLAGS += $(FPIC)`. So either that's not working for all compilation units or mips16 interfers with LTO on this platform?

Does it work with LTO and `PKG_BUILD_FLAGS:=no-mips16` added to the lua Makefile?

**Comment by timocapa** [comment]
> Does it work with LTO and `PKG_BUILD_FLAGS:=no-mips16` added to the lua Makefile?

Building dirty (so, without wiping build_dir) still errors
image

I'll double check in a sec with build_dir removed

**Comment by dhewg** [comment]
lua builds just fine here with LTO on CONFIG_TARGET_ramips_mt7621_DEVICE_netgear_wac124=y

**Comment by dhewg** [comment]
Are you using the SDK for building everything on your own? If using the SDK, it needs to be of a specific version for these build flags to work at all

**Comment by timocapa** [comment]
> Are you using the SDK for building everything on your own?

I'm assuming no? I just cloned the OpenWrt repo, made the config and run `make -jX`

**Comment by dhewg** [comment]
Yeah, that should work, no SDK in play.

To double check, this is what fails for you? `make V=cs -j7 package/lua/{clean,compile}|tee /tmp/out.log`
Attach that log here, let's see if there're hints in there

**Comment by dhewg** [comment]
There's no `-DPIC -fpic` in those gcc cmdlines. I do see them for my mt7621 build. Looking at rules.mk, I don't see how that could happen, but that seems to be the culprint

**Comment by dhewg** [comment]
I forgot to mention `2>&1`, so `make V=cs -j7 package/lua/{clean,compile} 2>&1|tee /tmp/out.log`

**Comment by timocapa** [comment]
> Please remove all your changes and test with that

Clean HEAD 🤷

**Comment by dhewg** [comment]
No clue, maybe it's the make version or make doing stupid things on wsl or just something silly because that is wsl's nature.
Try a real linux, this is derailing into a support forum, which this issue tracker is not about

**Comment by mpratt14** [comment]
AFAIK we don't support WSL as host (although I suppose it *should* work)

I would talk to Microsoft people

**Comment by mpratt14** [comment]
possibly related

https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

**Comment by timocapa** [comment]
It seems to compile file on Ubuntu WSL2 - my Arch VM is noticeably weaker than my PC, so that's still going, but seems to point at an Arch specific failure right now

**Comment by dhewg** [comment]
Well, arch should work, there're alot of users using it to build OpenWrt images on.

**Comment by dhewg** [comment]
It works for me because I have CONFIG_PKG_ASLR_PIE_ALL set, which automatically adds PIC flags to LDFLAGS.
It doesn't work when CONFIG_PKG_ASLR_PIE_REGULAR is set.

It's still MIPS specific though.

This should fix it for CONFIG_PKG_ASLR_PIE_REGULAR too:
```
diff --git a/package/utils/lua/Makefile b/package/utils/lua/Makefile
--- a/package/utils/lua/Makefile
+++ b/package/utils/lua/Makefile
@@ -91,6 +91,7 @@ define Build/Configure
 endef
 
 TARGET_CFLAGS += -DLUA_USE_LINUX $(FPIC) -std=gnu99
+TARGET_LDFLAGS += $(FPIC)
 
 define Build/Compile
    $(MAKE) $(PKG_JOBS) -C $(PKG_BUILD_DIR) \
```

But the nice solution would be to add a `pic` flag to PKG_BUILD_FLAGS, which then adds the flags to CFLAGS *and* LDFLAGS, just like hardening.mk does, and refactor the ports (like lua) to use PKG_BUILD_FLAGS:=pic then

**Comment by dhewg** [comment]
It works for me because I have CONFIG_PKG_ASLR_PIE_ALL set, which automatically adds PIC flags to LDFLAGS.
It doesn't work when CONFIG_PKG_ASLR_PIE_REGULAR is set.

It's still MIPS specific though.

This should fix it for CONFIG_PKG_ASLR_PIE_REGULAR too:
```
diff --git a/package/utils/lua/Makefile b/package/utils/lua/Makefile
--- a/package/utils/lua/Makefile
+++ b/package/utils/lua/Makefile
@@ -91,6 +91,7 @@ define Build/Configure
 endef
 
 TARGET_CFLAGS += -DLUA_USE_LINUX $(FPIC) -std=gnu99
+TARGET_LDFLAGS += $(FPIC)
 
 define Build/Compile
    $(MAKE) $(PKG_JOBS) -C $(PKG_BUILD_DIR) \
```

But the nice solution would be to add a `pic` flag to PKG_BUILD_FLAGS, which then adds the flags to CFLAGS *and* LDFLAGS, just like hardening.mk does, and refactor the ports (like lua) to use PKG_BUILD_FLAGS:=pic then

**Comment by timocapa** [comment]
> CONFIG_PKG_ASLR_PIE_ALL 
I did this to check as well, but this seems to open a whole new can of issues specific to MIPS with `-mabicalls`, so I've just closed the PR. I can reopen this, or create an issue for this, if you'd prefer.

**Comment by timocapa** [comment]
@dhewg Turning on `CONFIG_PKG_ASLR_PIE_ALL` seems to work!

An alternative would be making LTO depend on `CONFIG_PKG_ASLR_PIE_ALL`, that said I don't know if that's a good solution..

**Pull request closed without merging**
