### PR TITLE
treewide: rename POWER_ON_STRIP register

### PR DESCRIPTION
**Pull request by mans0n**
AR8327 datasheet[1] calls the register at address 0x0010
"Power-on Strapping Register". As it has nothing to do with "strip",
let's rename it to "POWER_ON_STRAP" to make it easier to grasp.

[1] https://lafibre.info/images/doc/201106_spec_AR8327.pdf

### CODE REVIEW

**Comment by mans0n** [comment]
The DS also calls the register "POWER ON STRIPT REGISTER", I think it is just a typo.

**Comment by adrianschmutzler** [comment]
I won't merge this, but from reading the docs it seems to me that if you touch this, you should go the entire way and name it "POWER_ON_STRAPPING".

**Comment by mans0n** [comment]
> you should go the entire way and name it "POWER_ON_STRAPPING".

I agree that it's more coherent, but I feel POWER_ON_STRAPPING is too long (especially for bit macros in ar8327.h).

**Comment by adrianschmutzler** [comment]
Just added a device that would need rename, too:
https://github.com/openwrt/openwrt/commit/a0bb356612fddf747893fffbfa216dcb3c05f069

**Comment by mans0n** [comment]
Thanks for letting me know.
Rebased due to a0bb356.

**Comment by brianonn** [comment]
note that some of the dts files refer to it as `PWS_REG` too 
If you are doing a global rename here, you might as well make it consistent everywhere. 

```
[ ~/src/openwrt-1 ]
[514] $ rg -g \* PWS_REG
target/linux/ath79/dts/ar1022_sitecom_wlr-7100.dts
82:                     0x10 0x80000000 /* PWS_REG_VALUE */

target/linux/ath79/dts/ar9344_dlink_dir-8x5.dtsi
45:                     0x10 0xc1000000 /* PWS_REG_VALUE */

target/linux/ipq806x/files-5.4/arch/arm/boot/dts/qcom-ipq8064-ea8500.dts
282:                    0x00010 0x2613a0    /* PWS_REG */

target/linux/ipq806x/files-5.4/arch/arm/boot/dts/qcom-ipq8064-ea7500-v1.dts
266:                    0x00010 0x2613a0    /* PWS_REG */
```

**Comment by brianonn** [comment]
https://github.com/openwrt/openwrt/pull/3185

**Comment by mans0n** [comment]
I'm aware of it, but this PR is not for unifying all references of that register, it's only "fixing a typo" in the name. (I'll touch PWS_REG as well if core devs also want that.)

**Comment by adrianschmutzler** [comment]
Will merge this later tonight. Thanks for tidying up!

**Pull request closed without merging**
