### PR TITLE
ath79: improve DTS for TP-Link Archer D50 v1

### PR DESCRIPTION
**Pull request by adschm**
This addresses several issues in the DTS file:
- add diag LED support
- remove unused node names
- fix whitespace issues

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
@DavideFioravanti Stumbled across these when looking at your response in #2031
Can you have this PR tested?

**Comment by adrianschmutzler** [comment]
@suppenkasper0815 Still have a device to do a quick test?

**Comment by suppenkasper0815** [comment]
Hi, yes sure. Which test on which device? - Unfortunately for D50 I will not have access atm... I try to, but could help with D7...

**Comment by adrianschmutzler** [comment]
This patch here should add diag LED support (blinking during boot, failsafe etc.) to the D50V1, in addition to some code style changes. So, if you get access to the device, it should be very quick to test.

D7 is currently waiting for core-developer review.

**Comment by suppenkasper0815** [comment]
Ok, I'll test asap, but unfortunately I think I need to wait until next week. The device is in my second flat...

**Comment by adrianschmutzler** [comment]
@suppenkasper0815 Take your time, this is not a critical change ;-)

**Comment by adrianschmutzler** [comment]
Rebased.

**Comment by DavideFioravanti** [comment]
I got my Archer D50 back. I am going to test this patch soon! :)

**Review by DavideFioravanti — APPROVED** [review]
Tested. Working fine! ;)

**Comment by suppenkasper0815** [comment]
I'm sorry I haven't had time to test, but I'm glad you keep the development going! BTW... At the moment there are good and cheap offers for this device on eBay.

If we can use the device as Client and AP at the same time in 5 GHz wifi I think this is a very good and cheap solution for a lot of interested users for openwrt! Also the power consumption is way less than D7! So maybe it's a really interesting device now

**Comment by adrianschmutzler** [comment]
@blocktrron This should be ready and is quite simple.

**Comment by blocktrron** [comment]
merged, thanks.

**Pull request closed without merging**
