### PR TITLE
kernel: mtk_ppe setup flow entry keep alive

### PR DESCRIPTION
**Pull request by ptpt52**
It seems that the mtk offload keepalive not work

### CODE REVIEW

**Comment by ptpt52** [comment]
@nbd168  ping

**Comment by ptpt52** [comment]
aha
It seems a typo error in my code, I will test it again

**Comment by ptpt52** [comment]
now this is a fixed

**Comment by ptpt52** [comment]
now I found still bug in UDP stream

UDP stream keepalive callback not work.

**Comment by adschm** [comment]
Missing commit message.

**Comment by ptpt52** [comment]
updated

**Comment by adschm** [comment]
> mediatek/ramips: add flow offload keep alive
> This add back the code for flow offload keep alive setup
> this code is missing since b59d5c8
> ("mediatek: rewrite flow offload code")

This is changing generic patches, so the prefix should be "kernel:". Maybe use "kernel: add flow offload keepalive for mediatek/ramips" or similar (e.g. mt762x instead of mediatek/ramips etc.) for commit title.

If this actually _fixes_ the referenced commit and it's not just an improvement, consider adding a proper "Fixes:" line to the commit message referencing that commit.

**Comment by ptpt52** [comment]
hi, it seems hnat in kernel 5.10 is another quite different implementation
this fix maybe out of date as soon as we switch to kernel 5.10

so I perfer close this PR.

**Pull request closed without merging**
