### PR TITLE
gettext: remove

### PR DESCRIPTION
**Pull request by neheb**
This package was necessary when uClibc was in the tree. Now that uClibc
is gone, this can go too.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

@ldir-EDB0 is this an issue with macOS?

### CODE REVIEW

**Comment by neheb** [comment]
Hmm I think this can be completely removed. Nothing depends on gettext/host. gettext-full/host has a header and packages already depend on it.

**Comment by neheb** [comment]
Updated PR to remove this package.

**Comment by aparcar** [comment]
This should be tested by someone running MacOS X.

**Comment by neheb** [comment]
Not really.

macOS is only impacted in the host case. But for that there's already gettext-full/host, which is what is used everywhere.

interestingly nls.mk is only for target, not host.

**Comment by aparcar** [comment]
Anything blocking this?

**Comment by neheb** [comment]
No.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in e6f569406ffe1d9e35b9b9ea36f38cdd5837728d.

**Pull request closed without merging**
