### PR TITLE
kernel: remove NO_ARRAY_BOUNDS settings

### PR DESCRIPTION
**Pull request by namiltd**
Remove CONFIG_CC_NO_ARRAY_BOUNDS, CONFIG_GCC10_NO_ARRAY_BOUNDS and CONFIG_GCC11_NO_ARRAY_BOUNDS settings because they are dynamically added by the kernel based on GCC version. Filter these settings.

### CODE REVIEW

**Comment by robimarko** [comment]
They also need to go into:
https://github.com/openwrt/openwrt/blob/main/target/linux/generic/config-filter

To avoid being added back after a kernel refresh

**Comment by namiltd** [comment]
@robimarko Filtering added.

**Comment by Ansuel** [comment]
What is this 5th PR of .config cleanup? I feel we should first merge https://github.com/openwrt/openwrt/pull/16770 and then reevaluate each commit cleaning configs... And also improve 16770 to filter all

**Comment by namiltd** [comment]
Yes, I agree with You.

**Comment by hauke** [comment]
I merged https://github.com/openwrt/openwrt/pull/16770, pleases rebase on top of current main branch.

**Comment by namiltd** [comment]
Closed due of duplication of PR https://github.com/openwrt/openwrt/pull/16770

**Pull request closed without merging**
