### PR TITLE
tools/fakeroot: update to 1.28

### PR DESCRIPTION
**Pull request by neheb**
Refreshed patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
400-alpine-libc.musl-fix.patch breaks FreeBSD. Although FreeBSD has problems with many more tools.

**Comment by aparcar** [comment]
Do they have a changelog?

**Comment by neheb** [comment]
If you look at the top of https://tracker.debian.org/pkg/fakeroot , it says the git repo must be updated.

Reading the debian changelog I see:

```
* New upstream version
     - includes patch from Samuel Thibault to handle _STAT_VER on
       GNU/Hurd.  closes: [#1006151](https://bugs.debian.org/1006151).
```

**Comment by hauke** [comment]
We do not support building on FreeBSD, I used it some time ago to build test the U-Boot tools because I do not have MAC OS and FreeBSD is free.

**Comment by neheb** [comment]
Added comment about changes.

**Comment by neheb** [comment]
@hauke it seems historically people were using FreeBSD. I see 74 commits with FreeBSD here.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in 9a44bc78b4413673f15a425e066d5c771b8054c6.

**Pull request closed without merging**
