### PR TITLE
build: shuffle mirror list

### PR DESCRIPTION
**Pull request by IguanaBob**
Shuffle the mirror list to spread load on the mirrors.

Signed-off-by: Jonathan Hull <bright.lamp6045@fastmail.com>

### CODE REVIEW

**Comment by IguanaBob** [comment]
I created this because I noticed download.pl was always trying to download from the same mirror when building tools and that mirror was very slow.

**Review by neheb — APPROVED** [review]

**Comment by Ansuel** [comment]
@IguanaBob and how this solve the problem? looks to be an hack more than a fix btw if you want you can use aria2c as download manager that checks all the mirrors and autoselect the best one on the fly

**Comment by 981213** [comment]
I also don't like this approach. Random shuffle sometimes makes the experience even worse because the upstream URL is usually covered by a CDN while the speed of those mirror sites are only good for a specific region.

**Comment by Ansuel** [comment]
@IguanaBob did you tried aria2c download tool to test this?

**Comment by Ansuel** [comment]
Sorry closing this as we don't see a correct solution for the problem. We already have support for aria2c that should autoselect the best mirror.

**Pull request closed without merging**
