### PR TITLE
metadata: fixup "board"

### PR DESCRIPTION
**Pull request by aparcar**
currently the "board" parameter contains $(BOARD) which actually results
to `<target>` (like ramips, ar71xx) without subtarget. However, one
actually excepts (not?) to contain BOARD_NAME or DEVICE_NAME.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
@jow- @nbd168 @lynxis

**Comment by aparcar** [comment]
@pepe2k done

**Comment by pepe2k** [comment]
@aparcar 

I suppose the misuse of the `board` field value comes from the fact that variable `BOARD` is actually used for target name in `target/linux/*/Makefile` (at the same time, subtarget uses `SUBTARGET`).

This looks like some old mistake, overlook or maybe a backward compatibility thing... and it makes me thinking that changing it could break some existing users/down stream projects but personally I'm fine with it - it's not critical. Eventually, I would keep it and add separate `device` field with `DEVICE_NAME` or maybe `DEVICE_TITLE`? Lets wait for others opinion on this.

Cheers,
Piotr

**Comment by lynxis** [comment]
If we really care about downstream projects which use this, we should introduce a version field into the metadata.
I'm fine with this "board" commit. As board = $TARGET is IMHO completely wrong.
I agree DEVICE_TITLE might be interesting as well.

**Comment by aparcar** [comment]
@lynxis shoud I add a version field as well?
Also, DEVICE_TITLE != DEVICE_NAME? If so, is TITLE = the *model*?

**Comment by aparcar** [comment]
@lynxis I tried to add `DEVICE_TITLE`but it seem to be somewhat randomized. See the following output:
```
aparcar@chef:~/openwrt/bin/targets/ath79/generic$ ~/fwtool -i meta openwrt-ath79-generic-tplink_tl-wdr4300-squashfs-sysupgrade.bin 
aparcar@chef:~/openwrt/bin/targets/ath79/generic$ cat meta | python3 -m json.tool
{
    "metadata_version": "1.0",
    "supported_devices": [
        "tplink,tl-wdr4300",
        "tl-wdr4300"
    ],
    "version": {
        "dist": "OpenWrt",
        "version": "SNAPSHOT",
        "revision": "r9440+4-0f89c17b57",
        "target": "ath79/generic",
        "board": "tplink_tl-wdr4300",
        "model": "Ubiquiti RouterStation Pro"
    }
}
```

The `model` property is clearly broken, same happened for at least one other device. Am I missing something?

**Comment by dangowrt** [comment]
closed by commits
26c16aec670d9206bef1065d0de4c423a6cbdcbe
208f287908e4143170417ce6cda9ca6c287ccc90
7fa9794c4ce5988c8ef483d6f402033bf08eabb3

**Pull request closed without merging**
