### PR TITLE
Vrx518 support rebase master

### PR DESCRIPTION
**Pull request by PhoenixKopf**
updates for FB7520/30

### CODE REVIEW

**Comment by Ansuel** [comment]
@PhoenixKopf can you give use more details about this pr? also you should fix it to a correct tag... check other pr on a correct title format.

**Comment by DavideFioravanti** [comment]
@Ansuel I think that he created this PR by mistake (it's an old branch of mine). However some developers are really working hard on VDSL support in the forum and I think that there will be soon a real PR! :)

**Comment by Ansuel** [comment]
@DavideFioravanti well think i have to close this... hope to get the real pr soon :D

**Comment by DavideFioravanti** [comment]
[ OT ]
@Ansuel I didn't know you became a member of the Openwrt team! Congratulations! :D
[ /OT ]

**Comment by PhoenixKopf** [comment]
yep was a mistake sorry

**Pull request closed without merging**
