### PR TITLE
samba36: Remove

### PR DESCRIPTION
**Pull request by neheb**
Samba 3.6 is completely unsupported, in addition to having tons of patches

It also causes kernel panics on some platforms when sendfile is enabled.
Example:

https://github.com/gnubee-git/GnuBee_Docs/issues/45

I have reproduced on ramips as well as mvebu in the past.

Samba 4 is an alternative available in the packages repo.

cifsd is a lightweight alternative available in the packages repo. It is
also a faster alternative to both Samba versions (lower CPU usage).

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by aparcar** [comment]
@ynezz −32,006 lines, this looks like a nice cleanup

**Comment by neheb** [comment]
Posted here as the mailing list has size limits.

**Comment by stintel** [comment]
Nice that there is an alternative nowadays. However, I would not remove samba36 until we have luci-app-cifsd that is on par with luci-app-samba36.

**Comment by neheb** [comment]
I received an email from one of the cifsd authors. They are considering removing CIFS1 support in addition to renaming cifsd. Guess we'll have to wait and see what they do.

**Comment by neheb** [comment]
I've no issue with that.

That being said, it doesn't make too much sense to move something that is to be removed.

cifsd already has UCI support. LuCI support should not be that hard to do. ping @Andy2244

**Comment by Andy2244** [comment]
Yeah luci is planed for cifsd, did not had much time lately. Mostly trying to figure out if i can get a stable samba-4.11 package ready, the cross-compile bugs are still there, so are some other annoying build bugs. Not sure how long it may actually take the samba team to fix those, we reported the main bug 7 months ago.

I would also keep samba36 around for a bit longer, until we feel cifsd/samba4 works as a replacement and have been actually backported to 19.07.

PS: I will try update cifsd next week, they had some big changes lately and than add the luci stuff.

**Comment by alexsmartens** [comment]
Hi all,
I'm running running into some problems with samba36 (including [#10069](https://github.com/openwrt/packages/issues/10069)). I would like to try samba-4 or CIFS1 but cannot find any OpenWRT specific documentation/manuals/posts. 
Could you please share some helpful links and recommendations?

**Comment by neheb** [comment]
cifsd has mostly the same config format as samba3.

it's cifsdadmin instead of smbpasswd for the command (although it will change soon...).

**Comment by adrianschmutzler** [comment]
Labelled this "work in progress" as it looks to me that this is "blocked" by waiting/testing of replacements at the moment.

**Comment by neheb** [comment]
It's blocked on luci-app-cifsd being created. cifsd works perfectly fine, even on big endian devices (I did a lot of testing with upstream to make sure it worked).

**Comment by neheb** [comment]
@Andy2244 any news?

**Comment by Andy2244** [comment]
Need to test some of the latest changes and if it works will create the luci stuff next week, so i can get it ready for snapshots + 19.07.

**Comment by neheb** [comment]
luci-app-cifsd has landed. I think it’s time to proceed with this.

**Comment by Andy2244** [comment]
> 
> 
> luci-app-cifsd has landed. I think it’s time to proceed with this.

Keep those cases in mind :P
https://forum.openwrt.org/t/openwrt-snapshot-cifsd-issue/48912

**Comment by ynezz** [comment]
>  luci-app-cifsd has landed. I think it’s time to proceed with this.

Thanks! `Acked-by: Petr Štetiar <ynezz@true.cz>`.

**Comment by ynezz** [comment]
> Keep those cases in mind :P

https://github.com/cifsd-team/cifsd/issues/248

**Comment by neheb** [comment]
> > Keep those cases in mind :P
> 
> [cifsd-team/smbd#248](https://github.com/cifsd-team/smbd/issues/248)

Seems BrainSlayer found the issue: https://github.com/cifsd-team/smbd/issues/290

**Comment by neheb** [comment]
Rebased. Endian issues have been fixed. It works with garbage Android clients now.

This is ready to go.

**Comment by adrianschmutzler** [comment]
@ynezz @stintel What's the status with this?

**Comment by stintel** [comment]
> @ynezz @stintel What's the status with this?

I'll take this.

**Comment by stintel** [comment]
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=73fa1aba94f5cf566007ac18cee3ef08b3ae64bc

**Pull request closed without merging**
