### PR TITLE
qualcommax: dts: add reset delay to qca8081 phy

### PR DESCRIPTION
**Pull request by aiamadeus**
The qca8081 phy needs to set the reset delay time, otherwise it will not be detected by the mdio bus.

Fixes: 75ad5c2 ("qualcommax: switch to qca8081 upstream PHY driver")

### CODE REVIEW

**Comment by motolav** [comment]
The wan port on my Dynalink is also unusable with the new phy driver

**Comment by aiamadeus** [comment]
> The wan port on my Dynalink is also unusable with the new phy driver

Can you test this patch? Also I suspect that the phy led configuration did not work.
```
--- a/target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq8072-dl-wrx36.dts
+++ b/target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq8072-dl-wrx36.dts
@@ -162,6 +162,8 @@
 	qca8081: ethernet-phy@28 {
 		compatible = "ethernet-phy-id004d.d101";
 		reg = <28>;
+		reset-assert-us = <100000>;
+		reset-deassert-us = <100000>;
 		reset-gpios = <&tlmm 44 GPIO_ACTIVE_LOW>;
 
 		leds {
```

**Comment by motolav** [comment]
My wan port works now with the delay and the led does light up

**Comment by aiamadeus** [comment]
> My wan port works now with the delay and the led does light up

Can you try this? `ls /sys/class/leds/`

**Comment by motolav** [comment]
Yea the configuration is wrong, `/sys/class/leds/` doesn't show the phy leds. I spoke too soon when I saw the green led lit constantly

**Comment by robimarko** [comment]
We should add 10ms as the `reset-deassert-us` on all QCA8081 PHY-s, datasheet indicates that is the required time

**Comment by yyyzz123** [comment]
For qca8081's led. it work in previously versions, but upstream versions can't shut down, also qca8075 driver work

**Comment by Ansuel** [comment]
@robimarko do we need both assert and deassert?

**Comment by robimarko** [comment]
I don't think we need to assert, these PHY-s have no FW and I have not seen a minimal length of the reset pulse, they just take some time after deasserting to fully initialize.

**Comment by Ansuel** [comment]
@yyyzz123 what do you mean it doesn't shut down?

**Comment by yyyzz123** [comment]
> @yyyzz123 what do you mean it doesn't shut down?

QCA8081 upstream version can't turn off the led light, but i find in your repo https://github.com/Ansuel/openwrt/commit/57afcfb9213f29a838c28f79e8fec78c542e6bb5
This patch can turn off the led light.

**Comment by yyyzz123** [comment]
> > @yyyzz123 what do you mean it doesn't shut down?
> 
> QCA8081 upstream led patch can't turn off the led light, but i find in your repo [Ansuel@57afcfb](https://github.com/Ansuel/openwrt/commit/57afcfb9213f29a838c28f79e8fec78c542e6bb5) This patch can turn off the led light.

**Comment by Ansuel** [comment]
@aiamadeus can you remove the assert part from this?

**Comment by Ansuel** [comment]
@yyyzz123 I also bisect the problem with the LED, I will submit upstream and then backport... Hope it's not a problem some days with an additional LED turned on!

**Comment by aiamadeus** [comment]
> @aiamadeus can you remove the assert part from this?

Okay, I did a quick test and this works. But the AT803X_PHY driver doesn’t seem to work?

**Comment by yyyzz123** [comment]
> @yyyzz123 I also bisect the problem with the LED, I will submit upstream and then backport... Hope it's not a problem some days with an additional LED turned on!




> @yyyzz123 I also bisect the problem with the LED, I will submit upstream and then backport... Hope it's not a problem some days with an additional LED turned on!

Tanks for your works！I will test it.

**Comment by yyyzz123** [comment]
> @yyyzz123 I also bisect the problem with the LED, I will submit upstream and then backport... Hope it's not a problem some days with an additional LED turned on!
Tanks for your works！I will test it.

**Comment by yyyzz123** [comment]
> @yyyzz123 I also bisect the problem with the LED, I will submit upstream and then backport... Hope it's not a problem some days with an additional LED turned on!

Tanks for your works！I will test it.

**Comment by Ansuel** [comment]
> But the AT803X_PHY driver doesn’t seem to work?

what do you mean?

**Comment by aiamadeus** [comment]
> what do you mean?

Disable `CONFIG_AT803X_PHY`, just add reset delay, and wan port (qca8081) works.

**Comment by Ansuel** [comment]
@aiamadeus mhhh on my nbg the port works correctly with CONFIG_AT803X_PHY=y. What is your device?

**Comment by aiamadeus** [comment]
> on my nbg the port works correctly with CONFIG_AT803X_PHY=y. What is your device?

Arcadyan AW1000. Does the uboot of your device initialize network when it boot?

**Comment by Ansuel** [comment]
@aiamadeus no and the thing is reset anyway so everything is wiped. Either some regs are missing upstream or some custom tweaks by the oem... I need to check ssdk if we are missing something but it's strange

**Comment by aiamadeus** [comment]
> Do we have GPL of that device?

No, I think it may be a quirk of ssdk.

**Comment by Ansuel** [comment]
@aiamadeus I hope it's that. Let me clean some stuff and I will check if we are missing something

**Comment by Ansuel** [comment]
@aiamadeus also you are using 1g or 2.5g speed?

**Comment by Ansuel** [comment]
@aiamadeus can you do one thing? keep the config enabled and also enable the ssdk config for qca8081. Does the port work?

**Comment by Ansuel** [comment]
@robimarko do you know if the PHY is reset anyway even if the PHY driver is not compiled in?

**Comment by robimarko** [comment]
Yes, it will be reset regardless as we have set the ID via compatible.

**Comment by Ansuel** [comment]
@robimarko so in theory we should still reset the PHY and ssdk should step in to setup it?

**Comment by robimarko** [comment]
Yes, SSDK registers a normal PHY driver for QCA8081 so it will configure it

**Comment by Ansuel** [comment]
ok so in @aiamadeus case ... the PHY is getting reset and what QCA8081 upstream driver is doing is causing the port to malfunction? Is this theory correct?

**Comment by robimarko** [comment]
I would find it rather weird that the upstream driver is doing anything weird, it has like only 2 fixups for the PHY and that is it.

I will drag out a board with QCA8081 and see whats going on as well, I remember it working just fine at 1G on AX9000

**Comment by Ansuel** [comment]
Same for me on my nbg at 1g speed... his device have 2 port so i wonder if the problem is there?

**Comment by robimarko** [comment]
I only have EAP101(IPQ6018) with dual QCA8081 but that should make no difference.

**Comment by motolav** [comment]
Without the assert delay the QCA9081 doesn't work on my dynalink, I'm using the latest snapshot

**Comment by Ansuel** [comment]
@aiamadeus Any news from this? I would really hope to bisect this with your help!

**Comment by aiamadeus** [comment]
> Any news from this? I would really hope to bisect this with your help!

@Ansuel Sorry for the delay, I was sick during this time.
> keep the config enabled and also enable the ssdk config for qca8081. Does the port work?

Yes. Latest code without changes: qca8081 upstream driver work, phy leds work.
Enable qca8081 of both kernel and ssdk: Port work, phy leds not work (driven by ssdk).

**Comment by Ansuel** [comment]
> Sorry for the delay, I was sick during this time.

Hope you are doing well now!

> Yes. Latest code without changes: qca8081 upstream driver work, phy leds work.

Wait this is confusing. Just to make sure
- Latest code = Openwrt SNAPSHOT? (latest main commit?)
- qca8081 upstream driver work = So It does correctly work now?
- phy leds work = Yes we fixed this

> Enable qca8081 of both kernel and ssdk: Port work, phy leds not work (driven by ssdk).

Same question here. The broken phy leds is expected.

**Comment by aiamadeus** [comment]
> Latest code = Openwrt SNAPSHOT? (latest main commit?)

Yes, I did a `git pull` today and rebuilt the kernel.
> qca8081 upstream driver work = So It does correctly work now?

Yes, bootm is no problem either (uboot initializes the network).
> Same question here. The broken phy leds is expected.

At this time qca8081 is driven by ssdk, so maybe it's not a problem?

**Comment by Ansuel** [comment]
@aiamadeus No currently qca8081 is not driver by ssdk. (it's not compiled in) Can you by chance test with an official image? Just to remove any kind of unintended modification on self built image?

**Comment by Ansuel** [comment]
> Maybe there is a misunderstanding, I removed 'IN_QCA808X_PHY=FALSE' from ssdk for testing:

AAAnd now i'm confused...
- qca8081 upstream driver + IN_QCA808X_PHY=FALSE = doesn't work?
- qca8081 upstream driver + IN_QCA808X_PHY=TRUE = work?
- NO qca8081 upstream driver + IN_QCA808X_PHY=TRUE = work?

**Comment by aiamadeus** [comment]
> * qca8081 upstream driver + IN_QCA808X_PHY=FALSE = doesn't work?

Works well, includes phy leds (need to be configured in dts).
> * qca8081 upstream driver + IN_QCA808X_PHY=TRUE = work?

Works well, phy leds don't work (although the sys led node exists).
> * NO qca8081 upstream driver + IN_QCA808X_PHY=TRUE = work?

Work as before. There is a more extreme case:
* No qca8081 upstream driver + IN_QCA808X_PHY=FALSE

Works fine at 1G speed, not working at 2.5G.

**Comment by Ansuel** [comment]
Ok so a current SNAPSHOT image WITH NO MODIFICATION have the port correctly working (aside from missing LED configuration)? Cause you reported some days ago that the port was broken on SNAPSHOT for your device.

**Comment by aiamadeus** [comment]
> Without the assert delay the QCA9081 doesn't work on my dynalink, I'm using the latest snapshot The issue might just be the snapshot build not the code

@motolav Is it working properly now? My test here is working normally.

**Comment by Ansuel** [comment]
@robimarko should have the device and I remember him saying the pr was working correctly.

**Comment by motolav** [comment]
@aiamadeus my dynalink is fine, it was some odd glitch with the image builder that caused my issue

**Comment by aiamadeus** [comment]
@Ansuel Sorry but it looks like the lan port is broken now.
It seems that aw1000 was forgotten to be changed, but it still doesn’t work after changing it.
```
--- a/target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq8072-aw1000.dts
+++ b/target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq8072-aw1000.dts
@@ -246,24 +246,33 @@
 	pinctrl-names = "default";
 	reset-gpios = <&tlmm 37 GPIO_ACTIVE_LOW>;
 
-	qca8075_0: ethernet-phy@0 {
-		compatible = "ethernet-phy-ieee802.3-c22";
+	ethernet-phy-package@0 {
+		compatible = "qcom,qca8075-package";
+		#address-cells = <1>;
+		#size-cells = <0>;
 		reg = <0>;
-	};
 
-	qca8075_1: ethernet-phy@1 {
-		compatible = "ethernet-phy-ieee802.3-c22";
-		reg = <1>;
-	};
+		qcom,package-mode = "qsgmii";
 
-	qca8075_2: ethernet-phy@2 {
-		compatible = "ethernet-phy-ieee802.3-c22";
-		reg = <2>;
-	};
+		qca8075_0: ethernet-phy@0 {
+			compatible = "ethernet-phy-ieee802.3-c22";
+			reg = <0>;
+		};
+
+		qca8075_1: ethernet-phy@1 {
+			compatible = "ethernet-phy-ieee802.3-c22";
+			reg = <1>;
+		};
 
-	qca8075_3: ethernet-phy@3 {
-		compatible = "ethernet-phy-ieee802.3-c22";
-		reg = <3>;
+		qca8075_2: ethernet-phy@2 {
+			compatible = "ethernet-phy-ieee802.3-c22";
+			reg = <2>;
+		};
+
+		qca8075_3: ethernet-phy@3 {
+			compatible = "ethernet-phy-ieee802.3-c22";
+			reg = <3>;
+		};
 	};
 
 	qca8081: ethernet-phy@28 {
@@ -313,24 +322,28 @@
 
 &dp1 {
 	status = "okay";
+	phy-mode = "qsgmii";
 	phy-handle = <&qca8075_0>;
 	label = "lan1";
 };
 
 &dp2 {
 	status = "okay";
+	phy-mode = "qsgmii";
 	phy-handle = <&qca8075_1>;
 	label = "lan2";
 };
 
 &dp3 {
 	status = "okay";
+	phy-mode = "qsgmii";
 	phy-handle = <&qca8075_2>;
 	label = "lan3";
 };
 
 &dp4 {
 	status = "okay";
+	phy-mode = "qsgmii";
 	phy-handle = <&qca8075_3>;
 	label = "lan4";
 };
```

**Comment by sppmasterspp** [comment]
@Ansuel  
Compiling this morning with latest commits QNAP QHora-301W cannot connect to the upstream network.
My current configuration is LAN port 1 being WAN port.

**Pull request merged**
