### PR TITLE
sunxi: Add Xunlong Orangepi PC support

### PR DESCRIPTION
**Pull request by uzer00**
CPU: H3 Quad-core Cortex-A7 H.265/HEVC 4K @ 1.3 Ghz
GPU: Mali400MP2 GPU @ 600MHz (supports OpenGL ES 2.0)
Memory: 1GB DDR3 (shared with GPU)
Onboard: Storage TF card (Max. 64GB) / MMC card slot
Onboard: Network 10/100M Ethernet RJ45
Onboard header pinout: SPI, I2C, 1-WIRE
USB 2.0: Three USB 2.0 HOST, one USB 2.0 OTG
Buttons: Power Button(SW4)
Debug TTL UART: ..DC-IN.. >[GND][RX][TX] ..HDMI..

Signed-off-by: Vitalij Alshevsky <v_alshevsky@tut.by>

### CODE REVIEW

**Comment by ahmadrasyidsalim** [comment]
I think this commit just basic support of OpenWrt. How about the Ethernet? https://wiki.openwrt.org/toh/xunlong/orangepiplus

**Comment by uzer00** [comment]
OPi PC has internal ethernet interface 10/100M not like OPi PC Plus with external RTL8211E connection through mii_bus. There is kernel 4.14 builtin basic support for OPi PC. You need patching sun8i-h3-orangepi-pc.dts somethin like this https://github.com/armbian/build/blob/master/patch/kernel/sunxi-next/sunxi-add-orangepi-zero-plus.patch and enable some modules in kernel I think. I haven't OPi PC Plus board for tests.

**Comment by hauke** [comment]
In general this pull request looks good.
Please add a Signed-off-by line with your real name and also use your real name as author in your commits, see this for details:
https://openwrt.org/submitting-patches#working_with_github

**Comment by hauke** [comment]
Thank you for the patch, it was merged into master.

**Pull request closed without merging**
