### PR TITLE
mpc85xx: fix missing kernel config symbol

### PR DESCRIPTION
**Pull request by BKPepe**
While compiling OpenWrt master for Turris 1.x routers (p2020), it reported following error:

    Gianfar Ethernet (GIANFAR) [Y/n/m/?] y
    Freescale DPAA2 Ethernet Switch (FSL_DPAA2_SWITCH) [N/m/y/?] (NEW)
Error in reading or end of file.

Let's fix it by disabling it.

### CODE REVIEW

**Comment by Ansuel** [comment]
> Error in reading or end of file.

what is this error? Isn't it just a missing config?

**Comment by BKPepe** [comment]
That error happens if you are missing a config, so the full build can not finish and end like this. 

Here is the log, which I received by an email from Jenkins:
```
[...truncated 6011 lines...]
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 96 parallel jobs (remaining retries before decrease: 0)
FORCE-MAKE: Decreasing jobs count to: 48
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 48 parallel jobs (remaining retries before decrease: 1)
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 48 parallel jobs (remaining retries before decrease: 0)
FORCE-MAKE: Decreasing jobs count to: 24
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 24 parallel jobs (remaining retries before decrease: 1)
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 24 parallel jobs (remaining retries before decrease: 0)
FORCE-MAKE: Decreasing jobs count to: 12
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 12 parallel jobs (remaining retries before decrease: 1)
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 12 parallel jobs (remaining retries before decrease: 0)
FORCE-MAKE: Decreasing jobs count to: 6
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 6 parallel jobs (remaining retries before decrease: 1)
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 6 parallel jobs (remaining retries before decrease: 0)
FORCE-MAKE: Decreasing jobs count to: 3
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 3 parallel jobs (remaining retries before decrease: 1)
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 1
FORCE-MAKE: Build failed for 3 parallel jobs (remaining retries before decrease: 0)
FORCE-MAKE: Running single job fallback
WARNING: Makefile 'package/feeds/luci/luci-app-unbound/Makefile' has a dependency on 'unbound-daemon', which does not exist
make[2]: Entering directory '</turris1x/ws/build/scripts/config'>
make[2]: 'conf' is up to date.
make[2]: Leaving directory '</turris1x/ws/build/scripts/config'>
make[1]: Entering directory '</turris1x/ws/build'>
make[2]: Entering directory '</turris1x/ws/build/target/linux'>
make[3]: Entering directory '</turris1x/ws/build/target/linux/mpc85xx'>
rm -f </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/localversion>
</turris1x/ws/build/scripts/kconfig.pl>  + + </turris1x/ws/build/target/linux/generic/config-5.15> </turris1x/ws/build/target/linux/mpc85xx/config-5.15> </turris1x/ws/build/target/linux/mpc85xx/p2020/config-default> > </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.target>
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' </turris1x/ws/build/.config> >> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.target>
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.target>
echo "# CONFIG_KALLSYMS_ALL is not set" >> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.target>
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.target>
</turris1x/ws/build/scripts/package-metadata.pl> kconfig </turris1x/ws/build/tmp/.packageinfo> </turris1x/ws/build/.config> 5.15 > </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.override>
</turris1x/ws/build/scripts/kconfig.pl> 'm+' '+' </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.target> /dev/null </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.override> > </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.set>
WARNING: can't parse line: ==m
mv </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.set> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.old>
grep -v INITRAMFS </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.old> > </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.set>
echo 'CONFIG_INITRAMFS_SOURCE=""' >> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.set>
echo '# CONFIG_INITRAMFS_FORCE is not set' >> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.set>
rm -rf </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/modules>
cmp -s </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.set> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.prev> || { cp </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.set> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config;> cp </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.set> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.prev;> }
export MAKEFLAGS= ; [ -d </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/user_headers> ] || make -C </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72> KCFLAGS="-fmacro-prefix-map=</turris1x/ws/build/build_dir/target-powerpc_8548_musl=target-powerpc_8548_musl> -fno-caller-saves " HOSTCFLAGS="-O2 -I</turris1x/ws/build/staging_dir/host/include>  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="powerpc-openwrt-linux-muslspe-" ARCH="powerpc" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="packaging" KBUILD_BUILD_HOST="turris.cz" KBUILD_BUILD_TIMESTAMP="Sat Oct 15 13:37:03 2022" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L</turris1x/ws/build/staging_dir/host/lib"> CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.15.72 CC="ccache_cc"  INSTALL_HDR_PATH=</turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/user_headers> headers_install
grep '=[ym]' </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config.set> | LC_ALL=C sort | </turris1x/ws/build/staging_dir/host/bin/mkhash> md5 > </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.vermagic>
sed -i '/^CONFIG_LOCALVERSION=.*/ d' </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config>
echo CONFIG_LOCALVERSION=\""-`cat </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.vermagic`"\">  >> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.config;>
touch </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.configured>
rm -f </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/vmlinux> </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/System.map>
make -C </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72> KCFLAGS="-fmacro-prefix-map=</turris1x/ws/build/build_dir/target-powerpc_8548_musl=target-powerpc_8548_musl> -fno-caller-saves " HOSTCFLAGS="-O2 -I</turris1x/ws/build/staging_dir/host/include>  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="powerpc-openwrt-linux-muslspe-" ARCH="powerpc" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="packaging" KBUILD_BUILD_HOST="turris.cz" KBUILD_BUILD_TIMESTAMP="Sat Oct 15 13:37:03 2022" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L</turris1x/ws/build/staging_dir/host/lib"> CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.15.72 CC="ccache_cc" zImage modules
make[4]: Entering directory '</turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72'>
  SYNC    include/config/auto.conf.cmd
.config:1158:warning: override: CPU_LITTLE_ENDIAN changes choice state
.config:2433:warning: override: GENERIC_CPU changes choice state
*
* Restart config...
*
*
* Ethernet driver support
*
Ethernet driver support (ETHERNET) [Y/n/?] y
  3Com devices (NET_VENDOR_3COM) [Y/n/?] y
    3c590/3c900 series (592/595/597) "Vortex/Boomerang" support (VORTEX) [M/n/y/?] m
    3cr990 series "Typhoon" support (TYPHOON) [N/m/y/?] n
  Adaptec devices (NET_VENDOR_ADAPTEC) [Y/n/?] y
    Adaptec Starfire/DuraLAN support (ADAPTEC_STARFIRE) [N/m/y/?] n
  Agere devices (NET_VENDOR_AGERE) [Y/n/?] y
    Agere ET-1310 Gigabit Ethernet support (ET131X) [M/n/y/?] m
  Alacritech devices (NET_VENDOR_ALACRITECH) [Y/n/?] y
    Alacritech Slicoss support (SLICOSS) [N/m/y/?] n
  Alteon devices (NET_VENDOR_ALTEON) [Y/n/?] y
    Alteon AceNIC/3Com 3C985/NetGear GA620 Gigabit support (ACENIC) [N/m/y/?] n
  Altera Triple-Speed Ethernet MAC support (ALTERA_TSE) [N/m/y/?] n
  Amazon Devices (NET_VENDOR_AMAZON) [Y/n/?] y
  AMD devices (NET_VENDOR_AMD) [Y/n/?] y
    AMD 8111 (new PCI LANCE) support (AMD8111_ETH) [N/m/y/?] n
    AMD PCnet32 PCI support (PCNET32) [M/n/y/?] m
  aQuantia devices (NET_VENDOR_AQUANTIA) [Y/n/?] y
    aQuantia AQtion(tm) Support (AQTION) [M/n/?] m
  ARC devices (NET_VENDOR_ARC) [Y/n/?] y
  Atheros devices (NET_VENDOR_ATHEROS) [Y/n/?] y
    Atheros L2 Fast Ethernet support (ATL2) [M/n/y/?] m
    Atheros/Attansic L1 Gigabit Ethernet support (ATL1) [M/n/y/?] m
    Atheros L1E Gigabit Ethernet support (ATL1E) [M/n/y/?] m
    Atheros L1C Gigabit Ethernet support (ATL1C) [M/n/y/?] m
    Qualcomm Atheros AR816x/AR817x support (ALX) [M/n/y/?] m
  Broadcom devices (NET_VENDOR_BROADCOM) [Y/n/?] y
    Broadcom 440x/47xx ethernet support (B44) [M/n/y/?] m
    Broadcom GENET internal MAC support (BCMGENET) [N/m/y/?] n
    QLogic bnx2 support (BNX2) [M/n/y/?] m
    QLogic CNIC support (CNIC) [N/m/y/?] n
    Broadcom Tigon3 support (TIGON3) [M/n/?] m
      Broadcom Tigon3 HWMON support (TIGON3_HWMON) [N/y/?] n
    Broadcom NetXtremeII 10Gb support (BNX2X) [M/n/?] m
    Broadcom SYSTEMPORT internal MAC support (SYSTEMPORT) [N/m/y/?] n
    Broadcom NetXtreme-C/E support (BNXT) [N/m/?] n
  Cadence devices (NET_VENDOR_CADENCE) [Y/n/?] y
  Cavium ethernet drivers (NET_VENDOR_CAVIUM) [Y/n/?] y
  Chelsio devices (NET_VENDOR_CHELSIO) [Y/n/?] y
    Chelsio 10Gb Ethernet support (CHELSIO_T1) [N/m/y/?] n
    Chelsio Communications T3 10Gb Ethernet support (CHELSIO_T3) [N/m/y/?] n
    Chelsio Communications T4/T5/T6 Ethernet support (CHELSIO_T4) [N/m/?] n
    Chelsio Communications T4/T5/T6 Virtual Function Ethernet support (CHELSIO_T4VF) [N/m/y/?] n
  Cisco devices (NET_VENDOR_CISCO) [Y/n/?] y
    Cisco VIC Ethernet NIC Support (ENIC) [N/m/y/?] n
  Cortina Gemini devices (NET_VENDOR_CORTINA) [Y/n/?] y
    Gemini Gigabit Ethernet support (GEMINI_ETHERNET) [N/m/y/?] n
  Dave ethernet support (DNET) (DNET) [N/m/y/?] n
  Digital Equipment devices (NET_VENDOR_DEC) [Y/n/?] y
    DEC - Tulip devices (NET_TULIP) [Y/n/?] y
      Early DECchip Tulip (dc2104x) PCI support (DE2104X) [M/n/y/?] m
        Descriptor Skip Length in 32 bit longwords (DE2104X_DSL) [0] 0
      DECchip Tulip (dc2114x) PCI support (TULIP) [M/n/y/?] m
        New bus configuration (TULIP_MWI) [Y/n/?] y
        Use PCI shared mem for NIC registers (TULIP_MMIO) [Y/n/?] y
        Use RX polling (NAPI) (TULIP_NAPI) [Y/n/?] y
          Use Interrupt Mitigation (TULIP_NAPI_HW_MITIGATION) [Y/n/?] y
      Generic DECchip & DIGITAL EtherWORKS PCI/EISA (DE4X5) [N/m/y/?] n
      Winbond W89c840 Ethernet support (WINBOND_840) [M/n/y/?] m
      Davicom DM910x/DM980x support (DM9102) [M/n/y/?] m
      ULi M526x controller support (ULI526X) [M/n/y/?] m
  D-Link devices (NET_VENDOR_DLINK) [Y/n/?] y
    DL2000/TC902x/IP1000A-based Gigabit Ethernet support (DL2K) [N/m/y/?] n
    Sundance Alta support (SUNDANCE) [N/m/y/?] n
  Emulex devices (NET_VENDOR_EMULEX) [Y/n/?] y
    ServerEngines' 10Gbps NIC - BladeEngine (BE2NET) [M/n/y/?] m
      HWMON support for be2net driver (BE2NET_HWMON) [Y/n/?] y
      Support for BE2 chipsets (BE2NET_BE2) [Y/n/?] y
      Support for BE3 chipsets (BE2NET_BE3) [Y/n/?] y
      Support for Lancer chipsets (BE2NET_LANCER) [Y/n/?] y
      Support for Skyhawk chipsets (BE2NET_SKYHAWK) [Y/n/?] y
  EZchip devices (NET_VENDOR_EZCHIP) [Y/n/?] y
    EZchip NPS management enet support (EZCHIP_NPS_MANAGEMENT_ENET) [N/m/y/?] n
  Freescale devices (NET_VENDOR_FREESCALE) [Y/n/?] y
    FMan support (FSL_FMAN) [N/m/y/?] n
    Freescale PQ MDIO (FSL_PQ_MDIO) [Y/?] y
    Freescale XGMAC MDIO (FSL_XGMAC_MDIO) [N/m/y/?] n
    Freescale QE Gigabit Ethernet (UCC_GETH) [Y/n/m/?] y
      Transmit on Demand support (UGETH_TX_ON_DEMAND) [N/y/?] n
    Gianfar Ethernet (GIANFAR) [Y/n/m/?] y
    Freescale DPAA2 Ethernet Switch (FSL_DPAA2_SWITCH) [N/m/y/?] (NEW) 
Error in reading or end of file.

make[6]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[5]: *** [Makefile:620: syncconfig] Error 2
Makefile:717: include/config/auto.conf.cmd: No such file or directory
make[4]: *** [Makefile:740: include/config/auto.conf.cmd] Error 2
make[4]: Leaving directory '</turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72'>
make[3]: *** [Makefile:27: </turris1x/ws/build/build_dir/target-powerpc_8548_musl/linux-mpc85xx_p2020/linux-5.15.72/.modules]> Error 2
make[3]: Leaving directory '</turris1x/ws/build/target/linux/mpc85xx'>
make[2]: *** [Makefile:11: compile] Error 2
make[2]: Leaving directory '</turris1x/ws/build/target/linux'>
time: target/linux/compile#2.51#1.67#4.01
    ERROR: target/linux failed to build.
make[1]: *** [target/Makefile:30: target/linux/compile] Error 1
make[1]: Leaving directory '</turris1x/ws/build'>
make: *** [</turris1x/ws/build/include/toplevel.mk>:231: target/compile] Error 2
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```

After adding my proposed change, it works, meaning target/linux can be compiled and no errors are shown.

**Comment by BKPepe** [comment]
Ok, I will move it. Thanks.

**Comment by BKPepe** [comment]
I checked it and this option is only relevant to Freescale SoCs based on https://www.kernel.org/doc/html/latest/networking/device_drivers/ethernet/freescale/dpaa2/switch-driver.html .

In OpenWrt, there are already two targets (imx and qoriq), which has this option as not set:

- imx:
https://github.com/openwrt/openwrt/blob/689cfaeb7c37d7199f6e552bf32b0f996ea3040a/target/linux/imx/config-5.15#L166

- qoriq:
https://github.com/openwrt/openwrt/blob/689cfaeb7c37d7199f6e552bf32b0f996ea3040a/target/linux/qoriq/config-5.15#L119

So, it is a question, if I should move it to generic or not.

**Comment by CHKDSK88** [comment]
All "is not set" entries should be placed in generic.  It make target config more clear.

**Comment by hauke** [comment]
If it is not removed with `make kernel_oldconfig` and not needed by multiple targets (more than ~2), it should go into the target configuration.

**Comment by Ansuel** [comment]
Think this should stay in the target config.

**Comment by BKPepe** [comment]
What's the conclusion on this one? Should I move it to a generic config or not? This is required by three targets (imx, qoriq, mpc85xx)

**Comment by hauke** [comment]
If it gets removed when you refresh the mpc85xx configuration(`make kernel_oldconfig`) it should go to the generic kernel configuration, otherwise into the target configuration.

**Comment by BKPepe** [comment]
It was not removed during ``make kernel_oldconfig``.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in 941132cb3c6777e007a33eb47fa4517b4796b7ce.

**Comment by Hurricos** [comment]
BTW, DPAA is used on P2041 boards as opposed to eTSEC. We'd need a separate subtarget for those if so; see https://github.com/openwrt/openwrt/pull/3731

**Pull request closed without merging**
