### PR TITLE
[19.07] ath79: fix USB speed issues on ar934x devices like TP-Link WDR3600/WDR4300

### PR DESCRIPTION
**Pull request by jneuhauser**
See https://github.com/openwrt/openwrt/pull/2630

### CODE REVIEW

**Comment by jneuhauser** [comment]
Rebased on latest 19.07 changes.

Since https://github.com/openwrt/openwrt/pull/2630 is now merged, I suggest we some time, but at most until the 19.07.1 release.

**Comment by Leo-PL** [comment]
I had a chance to test this on my TL-WDR4300.
You can add my Tested-by tag if you'd like.
#2700 also works when backported.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by ynezz** [comment]
@jneuhauser FYI it's preferred to use `git cherry-pick -x` for backports if possible, I used that approach for backporting of bda6b6144dbe3e12d128b500821799ef472de4cb.

**Comment by jneuhauser** [comment]
Thanks, i know that...
But how about https://github.com/openwrt/openwrt/commit/6cca6fffa06b1996f9bcc280f766e8ba4fa97d45?
How should i cherry-pick a commit that modifies a different file?

**Pull request closed without merging**
