### PR TITLE
kernel: import wireguard backport for 5.4     

### PR DESCRIPTION
**Pull request by zx2c4**
Rather than using the clunky, old, slower wireguard-linux-compat out of tree module, this commit does a patch-by-patch backport of upstream's wireguard to 5.4. This specific backport is in widespread use, being part of SUSE's enterprise kernel, Oracle's enterprise kernel, Google's Android kernel, Gentoo's distro kernel, and probably more I've forgotten about. It's definately the "more proper" way of adding wireguard to a kernel than the ugly compat.h hell of the wireguard-linux-compat repo. And most importantly for OpenWRT, it allows using the same module configuration code for 5.10 as for 5.4, with no need for bifurcation.
    
These patches are from the backport tree which is maintained in the open here: https://git.zx2c4.com/wireguard-linux/log/?h=backport-5.4.y . I rebase this on Greg's tree from time to time.

I'll be sending PRs to update this as needed.

This will simplify the work being done on https://github.com/openwrt/openwrt/pull/3885

### CODE REVIEW

**Comment by zx2c4** [comment]
CC @lipnitsk

**Comment by adschm** [comment]
Formal nitpick: Commit title prefix should be "scripts/patch-kernel.sh" for first commit.

Thanks for providing this for a more well-founded discussion so quickly.

However, the relevant question from our side IMO is what we gain here:
The 21.02 release is based on the "compat-version" anyway. Unless we change that, we will have to maintain it.

So, for master, the question is just whether we throw in these patches now and remove them half a year later, without really doing much with 5.4-wireguard in the long run, or whether we want to have wireguard-compat there for testing/comparison with the 5.10 version.

So, unless we change wireguard in 21.02, the discussion is not about which 5.4-wireguard is better or worse, or easier/worse to maintain, but which would be more useful for (intermediate) development. From that angle, I personally think having proper-5.10 and compat-5.4 version in parallel seems to be the better choice for _us_ here.

**Comment by zx2c4** [comment]
> Formal nitpick: Commit title prefix should be "scripts/patch-kernel.sh" for first commit.

Done.

> However, the relevant question from our side IMO is what we gain here:
> The 21.02 release is based on the "compat-version" anyway. Unless we change that, we will have to maintain it.

We should update 21.02 to use these patches then.

Just take a look at https://git.zx2c4.com/wireguard-linux-compat/tree/src/compat/compat.h . As thrilling as this all was to write, compat code is plain scary. Moving to upstream commits makes everything a lot cleaner.

**Comment by zx2c4** [comment]
This has now been folded into https://github.com/openwrt/openwrt/pull/3885 so I'm closing this PR.

**Pull request closed without merging**
