### PR TITLE
mvebu: default to kernel 6.1

### PR DESCRIPTION
**Pull request by anomeome**
Change default kernel on mvebu target to 6.1. Remove 5.15 kernel support.

Signed-off-by: Kabuli Chana <newtownBuild@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@anomeome think it's better to do a single commit to change the makefile and then drop all the 5.15 patches

**Comment by stklcode** [comment]
+1 for making 6.1 default. testing for about 7 months now without notable issues.

Looks like the first commit incorporates some unrelated changes from mbetTLS bump with incorrect authorship. A clean rebase should fix this.

(ping #13213)

**Comment by Borromini** [comment]
@anomeome Could you find the time to remove the stray mbedTLS patch?

**Comment by anomeome** [comment]
DIW

**Pull request closed without merging**
