### PR TITLE
x86: geode: drm build fix

### PR DESCRIPTION
**Pull request by lucize**
added geode missing amd/radeon drm modules dependencies

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by Leo-PL** [comment]
While on x86 we usually have plenty of space, I wonder how much the kernel grows from that change, after all quite a few built-ins were added. Could you please compare that?

Good thing is, while building my own images I can always drop those modules ;)
@ynezz

**Comment by bobafetthotmail** [comment]
as mentioned in the mailing list, I don't see why we should build amdgpu and radeon drm modules for Geode systems.

amdgpu is for modern PCIe cards, and Geodes have AT MOST a PCI slot, more commonly a mini-PCI.

while it's indeed possible to mount an ancient PCI card supported by Radeon in the PCI slot, OpenWrt does not really do much with a screen beyond console display, and Geode boards have their own integrated graphics with a VGA port already.

**Comment by lucize** [comment]
I agree the drm should be disabled for geode, but anyway I made this

**Comment by tmn505** [comment]
Hi Lucian,
Unfortunately this is no-go. While storage space is non issue on Geode systems, RAM is. Some old WRAP boards have only 64MB and this is slowly becoming an issue. Instead of adding symbols to kernel config, add missing dependencies to modules, example: `+@TARGET_x86_geode:kmod-missing-module`.

**Comment by ynezz** [comment]
Latest successful Geode snapshot build seems to be the one on February 17th, so already some time ago. I don't see any bug report about that anywhere, so this makes me wonder if there are any interested users/developers.

Anyway, I still don't get what are you all trying to achieve here, what breakage are you fixing? I miss that real reason in the commit message of this PR and also in the patch proposed by @tmn505. According to the buildbots the [kernel modules have no issues](http://phase1.builds.openwrt.org/builders/x86%2Fgeode/builds/1334/steps/kmods/logs/stdio) but the [builds are failing](http://phase1.builds.openwrt.org/builders/x86%2Fgeode/builds/1334/steps/pkgbuild/logs/stdio) due to some issues in the packages.

BTW I've already tried to unbreak the geode just a few weeks ago, and if I still remember it correctly, it wasn't that easy as it looked at the first sight.

**Comment by ynezz** [comment]
> I miss that real reason in the commit message of this PR and also in the patch

In other words, what do I need to do to in order to reproduce the problem you're seeing, so one can actually verify, that the patch actually does what's written in the commit/patch description.

**Comment by lucize** [comment]
Select the drm-radeon or drm-amdgpu kernel package, and it will fail with some missing modules

**Comment by tmn505** [comment]
Here is the offending output in the buildlog You linked:
````
Package kmod-drm-amdgpu is missing dependencies for the following libraries:
backlight.ko
drm_kms_helper.ko
fb.ko
ttm.ko
````
That is the *real reason* why the build fails. OpenWrt has a sanity check (which is perfect for such problems) when packaging modules, applications or libraries. It prompts packager that his package is missing some particular dependencies.
On average distro You can check for module dependencies with:
`modinfo amdgpu | grep depends`
which will be exactly the same as here or slightly different depending on which kernel symbols were enabled.

The reason for my not adding missing dependencies is as stated in ML.

> I don't see any bug report about that anywhere, so this makes me wonder if there are any interested users/developers.
I am, not everyone runs snapshots on everything, even tough I use Arch Linux.

**Comment by ynezz** [comment]
Ok, I've tried to built Geode again and I'm now seeing the issue as you describe:

```
Package kmod-drm-amdgpu is missing dependencies for the following libraries:
backlight.ko
drm_kms_helper.ko
fb.ko
ttm.ko
```

So I still interpret this as a problem of `kmod-drm-amdgpu` dependencies, which needs to get fixed, not as a problem of the Geode platform, even it happens during build under Geode platform.

> > Yes, adding those modules to dependencies would solve the issue, but for how long?

Aren't we solving those with almost every kernel version bump (even during the patch level bumps) in bunch of other places? So I don't think, that this is a valid point.

> > If AMD people would decide to add another module to dependencies, we would need to fix it again 

Yes, until there's some automagic kernel module packager.

> and fix something not one would ever use on this target, only for the sake of it?

No, you should fix it in proper place, because other targets could benefit from this proper fix as well.

**Comment by lucize** [comment]
yes, but I think that intel is also using ttm, and it has the driver selected into kernel, so if I package the radeon with ttm as module then intel will fail and even if it can be built without that maybe it will fail loading the module, the right direction would be to have all drm video drivers as module, not built in the kernel so anyone could chose what  they want to use

**Comment by tmn505** [comment]
> yes, but I think that intel is also using ttm, and it has the driver selected into kernel, so if I package the radeon with ttm as module then intel will fail and even if it can be built without that maybe it will fail loading the module, the right direction would be to have all drm video drivers as module, not built in the kernel so anyone could chose what they want to use

No, it won't fail, all other subtargets have corresponding drivers enabled in kernel config, that is why geode is failing. You'll need to create package for drm_kms_helper.ko, ttm.ko and add them as dependencies to drm-radeon and drm-amdgpu (of course also fb and backlight). You can guard the them with dependency to `TARGET_x86_geode`, but that shouldn't be necessary, buildroot will create empty packages for other subtargets. 

> So I still interpret this as a problem of kmod-drm-amdgpu dependencies, which needs to get fixed, not as a problem of the Geode platform, even it happens during build under Geode platform.

Yes, this is problem with dependencies, but who will use those modules on this platform?

> Aren't we solving those with almost every kernel version bump (even during the patch level bumps) in bunch of other places? So I don't think, that this is a valid point.

But why wasting Your or others times, which could be spent on improvements?

> No, you should fix it in proper place, because other targets could benefit from this proper fix as well.

No other targets will benefit from it in foreseeable future, the offending drm modules are depending on x86 target and all corresponding drivers are built in kernel, not as modules and they will be refreshed for every kernel bump (which will solve missing symbols), except for geode. Did You have other target in mind?

**Comment by lucize** [comment]
@ynezz @tmn505 I think this the needed solution, I've tested the amd/radeon part, I'll see if the other video cards are working

**Comment by tmn505** [comment]
Thanks, this LGTM at first glance. I will test it tomorrow or Monday. Cheers.

**Comment by ynezz** [comment]
> @ynezz @tmn505 I think this the needed solution, I've tested the amd/radeon part, I'll see if the other video cards are working

I've just finished build testing of the following combinations `x86/64 x86/generic x86/geode x86/legacy ipq40xx/generic mvebu/cortexa72 brcm2708/brcm2708 brcm2708/brcm2710 imx6/generic` and `x86/geode` fails with following error:

```
Package kmod-drm-amdgpu is missing dependencies for the following libraries:
fb.ko
modules/video.mk:294: recipe for target '/openwrt/bin/targets/x86/geode/packages/kmod-drm-amdgpu_4.14.111-1_i386_pentium.ipk' failed
```

and build of `imx6/generic` fails with following error:

```
Package kmod-drm-kms-helper is missing dependencies for the following libraries:
cfbcopyarea.ko
cfbfillrect.ko
cfbimgblt.ko
fb.ko
fb_sys_fops.ko
syscopyarea.ko
sysfillrect.ko
sysimgblt.ko
modules/video.mk:273: recipe for target '/openwrt/bin/targets/imx6/generic/packages/kmod-drm-kms-helper_4.14.111-1_arm_cortex-a9_neon.ipk' failed
```

**Comment by lucize** [comment]
I'll add the kmod-fb, didn't saw that on my test

**Comment by lucize** [comment]
@ynezz So I moved all the dependencies on drm-kms-helper and removed from the rest

**Comment by ynezz** [comment]
> @ynezz So I moved all the dependencies on drm-kms-helper and removed from the rest

Ok, it builds now. Could you please also fix the commit subject to something like `kernel: Fix kmod-drm-amdgpu dependencies` and commit message should have some details as well:

```
Currently the Geode builds fails on following kernel module missing dependencies:

 Package kmod-drm-amdgpu is missing dependencies for the following libraries: 
 backlight.ko
 drm_kms_helper.ko
 fb.ko
 ttm.ko

So this patch tries to fix the kmod-drm-amdgpu module dependecies.

Fixes: 2f239c0 ("x86: video: add amdgpu DRM kernel package")
Fixes: 2f6918e ("x86: video: add radeon DRM module support")
```

So let's wait for @tmn505 feedback.

**Comment by tmn505** [comment]
All is good now, I'll mark my patch in patchwork as superseded. Thanks.

**Comment by ynezz** [comment]
> All is good now, I'll mark my patch in patchwork as superseded. Thanks.

So can I take this as your `Tested-by` ?

**Comment by tmn505** [comment]
> So can I take this as your Tested-by ?

Yes.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by ynezz** [comment]
@lucize So far the score is, one fixed platform (geode), one broken platform (layerscape_armv8_64b) :-)

layerscape seems to fail due to the [following](http://phase1.builds.lede-project.org/builders/layerscape%2Farmv8_64b/builds/890/steps/kmods/logs/stdio
):

```
*
* Restart config...
*
*
* Graphics support
*
VGA Arbitration (VGA_ARB) [Y/n/?] y
  Maximum number of GPUs (VGA_ARB_MAX_GPUS) [16] 16
ARM HDLCD (DRM_HDLCD) [N/m/?] n
ARM Mali Display Processor (DRM_MALI_DISPLAY) [N/m/?] n
ATI Radeon (DRM_RADEON) [N/m/?] n
AMD GPU (DRM_AMDGPU) [N/m/?] n
Nouveau (NVIDIA) cards (DRM_NOUVEAU) [N/m/?] n
Virtual GEM provider (DRM_VGEM) [N/m/?] n
DisplayLink (DRM_UDL) [N/m/?] n
AST server chips (DRM_AST) [N/m/?] n
Kernel modesetting driver for MGA G200 server engines (DRM_MGAG200) [N/m/?] n
Cirrus driver for QEMU emulated device (DRM_CIRRUS_QEMU) [N/m/?] n
R-Car DU Gen3 HDMI Encoder Support (DRM_RCAR_DW_HDMI) [N/m/?] n
QXL virtual GPU (DRM_QXL) [N/m/?] n
DRM Support for bochs dispi vga interface (qemu stdvga) (DRM_BOCHS) [N/m/?] n
Virtio GPU driver (DRM_VIRTIO_GPU) [N/m/?] (NEW) aborted!
```

**Comment by ynezz** [comment]
armvirt/64 is [failing](http://phase1.builds.openwrt.org/builders/armvirt%2F64/builds/1099/steps/kmods/logs/stdio) with the same error.

**Comment by lucize** [comment]
@DISPLAY_SUPPORT is defined on those targets ? Maybe only adding the missing symbols will fix it

**Comment by ynezz** [comment]
> Maybe only adding the missing symbols will fix it

I didn't looked at it yet as I've thought, that you maybe interested in fixing this remaining issue as well. If you're not interested, it's fine with me and I'll fix it myself, just let me know.

**Comment by lucize** [comment]
I'll do it, I also have to start drm on some intel atom devices that are not starting now

**Pull request closed without merging**
