### PR TITLE
ar71xx:add support for E558 v2/E750A v4/E750G v8

### PR DESCRIPTION
**Pull request by zhangsd20**
Qxwlan E558 v2 is based on Qualcomm QCA9558 + AR8327.

Specification:

720/600/200 MHz (CPU/DDR/AHB)
128 MB of RAM (DDR2)
8/16 MB of FLASH (SPI NOR)
2T2R 2.4 GHz (QCA9558)
3x 10/100/1000 Mbps Ethernet (one port with PoE support)
4x miniPCIe slot (USB 2.0 bus only)
1x microSIM slot
5x LED (4 driven by GPIO)
1x button (reset)
1x 3-pos switch
1x DC jack for main power input (9-48 V)
UART (JP5) and LEDs (J8) headers on PCB

Qxwlan E750A v4 is based on Qualcomm QCA9344.

Specification:

560/450/225 MHz (CPU/DDR/AHB)
128 MB of RAM (DDR2)
8/16 MB of FLASH (SPI NOR)
2T2R 5G GHz (AR9344)
2x 10/100 Mbps Ethernet (one port with PoE support)
1x miniPCIe slot (USB 2.0 bus only)
7x LED (6 driven by GPIO)
1x button (reset)
1x DC jack for main power input (9-48 V)
UART (J23) and LEDs (J2) headers on PCB

Qxwlan E750G v8 is based on Qualcomm QCA9344.

Specification:

560/450/225 MHz (CPU/DDR/AHB)
128 MB of RAM (DDR2)
8/16 MB of FLASH (SPI NOR)
2T2R 2.4G GHz (AR9344)
2x 10/100 Mbps Ethernet (PoE support)
2x 10/100/1000 Mbps Ethernet
7x LED (6 driven by GPIO)
1x button (reset)
1x DC jack for main power input (9-48 V)
UART (J23) and LEDs (J2) headers on PCB

Flash instruction (using U-Boot CLI and tftp server):

Configure PC with static IP 192.168.1.10 and tftp server.
Rename "sysupgrade" filename to "firmware.bin" and place it in tftp
server directory.
Connect PC with one of RJ45 ports, power up the board and press
"enter" key to access U-Boot CLI.
Use the following command to update the device to OpenWrt: "run lfw".

Flash instruction (using U-Boot web-based recovery):

Configure PC with static IP 192.168.1.xxx(2-254)/24.
Connect PC with one of RJ45 ports, press the reset button, power up
the board and keep button pressed for around 6-7 seconds, until LEDs
start flashing.
Open your browser and enter 192.168.1.1, select "sysupgrade" image
and click the upgrade button.

Signed-off-by: Peng Zhang <sd20@qxwlan.com>

### CODE REVIEW

**Comment by mkresin** [comment]
Please split the PR into multiple commits. One board, one commit.

**Comment by zhangsd20** [comment]
please see my pr （https://github.com/openwrt/openwrt/pull/1183）
How to submit multiple pr, after I submit a pr, I can't submit the second pr, what should I do?

**Comment by zhangsd20** [comment]
please see my pr （https://github.com/openwrt/openwrt/pull/1183 ）
How to submit multiple pr, after I submit a pr, I can't submit the second pr, what should I do?

**Comment by zhangsd20** [comment]
please see my pr （https://github.com/openwrt/openwrt/pull/1183 ）
How to submit multiple pr, after I submit a pr, I can't submit the second pr, what should I do?

**Comment by bobafetthotmail** [comment]
> How to submit multiple pr, after I submit a pr, I can't submit the second pr, what should I do?

make a git branch for each PR.

But Mkresin only asked to split the commits, you don't need to send one PR for each commit.

**Comment by zhangsd20** [comment]
Hi,
     Thank you very much! how to split the commit, split the commits?













在2018年07月16 22时12分，"Alberto Bursi"<notifications@github.com>写道：

How to submit multiple pr, after I submit a pr, I can't submit the second pr, what should I do?
make a git branch for each PR.
But Mkresin only asked to split the commits, you don't need to send one PR for each commit.

**Comment by bobafetthotmail** [comment]
> Thank you very much! how to split the commit, what should I do ?

start from clean OpenWrt source, add one device like you did in PR here https://github.com/openwrt/openwrt/pull/1183 then commit, then add another device, then commit, then add another device and commit. Open the PR with the first commit and it will carry the others too.

They ask you to do this because it is easier to review what you changed to add each device to OpenWrt.

**Comment by zhangsd20** [comment]
pelase see my PR ( https://github.com/openwrt/openwrt/pull/1191 )
I don't know if I am doing this right.

**Comment by juppin** [comment]
Why open always new PR's for the same devices...?

Do "git reset HEAD~1" to remove the first commit and then create single commits for your devices...

If you have created single commits for your devices use "git push -f" to force update your branch for this PR.
No need to create always a new PR.

**Comment by zhangsd20** [comment]
i will delete this PR,please see my new PR (  https://github.com/openwrt/openwrt/pull/1191 )

**Comment by Neustradamus** [comment]
Replaced by:
- https://github.com/openwrt/openwrt/pull/1191

E558 v2
- https://github.com/openwrt/openwrt/commit/b74f63f81d6121b5eace3f0c0c87399f7e0fde92

E750A v4
- https://github.com/openwrt/openwrt/commit/ac03d51a3f4daa2f6a2a83f041dcd71674a9f724

E750G v8
- https://github.com/openwrt/openwrt/commit/53a45020135b504cb4bee0fa8d98c8eaf6391066

Linked to:
- https://github.com/openwrt/openwrt/pull/1190
- https://github.com/openwrt/openwrt/pull/1183
- https://github.com/openwrt/openwrt/pull/1124
- https://github.com/openwrt/openwrt/pull/1123
- https://github.com/openwrt/openwrt/pull/1105

**Pull request closed without merging**
