### PR TITLE
rtl838x: cleanup/improvements

### PR DESCRIPTION
**Pull request by adschm**
This removes some leftover debug output and refreshs the config.

@bkobl

### CODE REVIEW

**Comment by bkobl** [comment]
Tested and it works. While you are at it, could you also directly fix the following messup in serial.c I made in the PR.
it needs to be
`		err = kstrtoul(s, 10, &baud);
		if (err)
			baud = 0;
`
not baud = kstrtoul...

**Comment by adschm** [comment]
> Tested and it works. While you are at it, could you also directly fix the following messup in serial.c I made in the PR.
> it needs to be
> ` err = kstrtoul(s, 10, &baud); if (err) baud = 0; `
> not baud = kstrtoul...

If you paste a commit title and message here for me, so I don't have to think ...

Apart from that, are parts of the files-5.4 contents expected to be upstream with a recent kernel? Because otherwise, I'd rename it to just "files"

**Comment by bkobl** [comment]
Commit title: Fix incorrect function call to kstrtoul

Message: Assign return value of kstrtoul to error variable instead of conversion value.
------------
blogic, biot and I are working hard to get arch/mips/rtl838x into an upsteam kernel quickly.

**Comment by Neustradamus** [comment]
Merged commits:
- https://github.com/openwrt/openwrt/commit/0da0aab6f2edc59e00c3c50a3c8f8d7e6f27c0b1
- https://github.com/openwrt/openwrt/commit/5c0cecb6c6bef941b803c7494b087ac08c473f87

**Pull request closed without merging**
