### PR TITLE
tools/elfutils: simplify and split patch

### PR DESCRIPTION
**Pull request by mcprat**
ping @robimarko @httpstorm 

Here is part 2 of preventative maintenance for tools/elfutils
(refer to part 1 here #15368)

I have also extended some of the changes already present into the debuginfod and tests directories.
Of course we do not intend to enable building the debuginfo server or tests,
but at least it is easily possible now, at least for testing purposes.

While I was doing that I discovered a small regression that causes the binaries built to seg fault
because of the fcntl() function provided by gnulib to infinitely call itself, fixed with the first commit of this series.

```
 lines of the portability patch before:  943
  lines of the portability patch moved:  160
lines of the portability patch removed:  515
  lines of the portability patch after:  268
                            total diff:  675
```

### CODE REVIEW

**Comment by mpratt14** [comment]
seems like macOS uses

```
#include <sys/param.h>
#include <sys/mount.h>
```

instead of 

```
#include <sys/statfs.h>
```

@httpstorm can you find which header has statfs() ???

**Comment by httpstorm** [comment]
@mpratt14 
Hey Michael, for macOS we need `#include <sys/mount.h>`.

``` C
make tools/elfutils/{clean,compile} -j 1 V=s
…
posix_fallocate.c:26:10: fatal error: 'sys/statfs.h' file not found
#include <sys/statfs.h>
         ^~~~~~~~~~~~~~

cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
grep -r 'statfs(' . |grep '\.h' |grep statfs
./usr/include/sys/mount.h:int     statfs(const char *, struct statfs *) __DARWIN_INODE64(statfs);
```
[x64.2024-06-12.01-elfutils.txt](https://httpstorm.com/share/.openwrt/test/2024-03-12_xcode-15.3/x64.2024-06-12.01-elfutils.txt)

This should fix the include:
``` diff
--- a/tools/gnulib/patches/320-modules-fallocate-posix.patch
+++ b/tools/gnulib/patches/320-modules-fallocate-posix.patch
@@ -163,7 +163,7 @@
  
 --- /dev/null
 +++ b/lib/posix_fallocate.c
-@@ -0,0 +1,144 @@
+@@ -0,0 +1,149 @@
 +/* posix_fallocate function that is glibc compatible.
 +
 +   Copyright (C) 2024 Free Software Foundation, Inc.
@@ -189,7 +189,12 @@
 +#include <stdint.h>
 +#include <sys/fcntl.h>
 +#include <sys/stat.h>
++
++#ifdef __APPLE__
++#include <sys/mount.h>
++#else
 +#include <sys/statfs.h>
++#endif
 +
 +/* Reserve storage for the data of the file associated with FD.  This
 +   emulation is far from perfect, but the kernel cannot do not much
```

Then there is another error
``` C
elf_update.c:96:18: error: call to undeclared function 'posix_fallocate'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          if (unlikely (posix_fallocate (elf->fildes, 0, size) != 0))
                        ^
```
[x64.2024-06-12.02-elfutils.txt](https://httpstorm.com/share/.openwrt/test/2024-03-12_xcode-15.3/x64.2024-06-12.02-elfutils.txt)

Sorry for the delay, I started some freelancing. If you know anyone who needs work with embedded or OpenWRT, please refer me to them. Good luck!

**Comment by mpratt14** [comment]
@httpstorm thanks for the test

I think I have the variable names reversed for substitutions... probably it should be GNULIB_FALLOCATE_POSIX instead of GNULIB_POSIX_FALLOCATE

I'll update tonight...

**Comment by mpratt14** [comment]
so it turns out that using `ar` like this isn't portable after all...
(honestly they should be embarrassed by using `ar` in any part of a build to compile `ar`)

```
libdwfl_objects = $(shell $(AR) t ../libdwfl/libdwfl.a)
libdw_a_LIBADD = $(addprefix ../libdwfl/,$(libdwfl_objects))
```

**Comment by httpstorm** [comment]
@mpratt14 

```
make[6]: *** No rule to make target '../libdwfl/__.SYMDEF', needed by 'libdw.a'.  Stop.
```
https://httpstorm.com/share/.openwrt/test/2024-03-12_xcode-15.3/x64.2024-06-13.01-elfutils.txt

**Comment by mpratt14** [comment]
rebasing in response to f97da2c61ad06a83c2fa23001459809005f8a721 ....

**Comment by httpstorm** [comment]
@mpratt14 

`elfutils` compiled successfully [x64.2024-06-14.01-elfutils.txt](https://httpstorm.com/share/.openwrt/test/2024-03-12_xcode-15.3/x64.2024-06-14.01-elfutils.txt)

However, this macro in `coreutils` seems familiar `#if @GNULIB_FALLOCATE_POSIX@`. Maybe some replacement failed to take place during configure?
``` C
make tools/coreutils/{clean,compile} -j 1 V=s
…
/Volumes/test/m/openwrt/staging_dir/host/bin/gcc  -I. -I./lib  -Ilib -I./lib -Isrc -I./src -I/Volumes/test/m/openwrt/staging_dir/host/include   -Wno-format-extra-args -Wno-implicit-const-int-float-conversion -Wno-tautological-constant-out-of-range-compare -O2 -I/Volumes/test/m/openwrt/staging_dir/host/include  -c -o src/date.o src/date.c
In file included from src/date.c:27:
In file included from src/system.h:104:
./lib/fcntl.h:754:5: error: invalid token at start of a preprocessor expression
#if @GNULIB_FALLOCATE_POSIX@
    ^
```
[x64.2024-06-14.02-coreutils.txt](https://httpstorm.com/share/.openwrt/test/2024-03-12_xcode-15.3/x64.2024-06-14.02-coreutils.txt)

**Comment by vortexilation** [comment]
Could it be libelf cannot be found libintl.so.8 related to elfutils ?, 
I am having problem rustc (rust-lang) finding libintl.so.8 in [here](https://github.com/openwrt/packages/issues/24375).

```
root@buildsystem:/home/user/works/openwrt# ldd /home/user/works/openwrt/staging_dir/target-x86_64_glibc_custom/usr/lib/libelf.so
        linux-vdso.so.1 (0x00007ffd965f1000)
        libintl.so.8 => not found
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f146c828000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f146c7fb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f146c616000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f146c872000)
```

**Comment by httpstorm** [comment]
@vortexilation 
The changes you see in this PR are not merged yet, and have no effect on your build yet. Unless you are intentionally building the PR branch.
I couldn't resist going off-topic to mention that building anything as `root` is generally a very bad idea. Consider an install command with destination `$(DST)/bin` where `DST` is undefined due to a bug. Or a malicious build script.

**Comment by vortexilation** [comment]
@httpstorm 

Just incase leftover from Part 1 i've meant, I will try this PR.

**Comment by httpstorm** [comment]
@vortexilation part 1 is merged, let's see @mpratt14 opinion.

**Comment by vortexilation** [comment]
The offending package is not yet on OpenWrt official packages tree, incase you wanted to [try](https://github.com/muink/openwrt-einat-ebpf). Need to be build with CONFIG_BUILD_NLS , it has left many people speechless regarding the bug (cannot found libintl.so.8).

**Comment by mpratt14** [comment]
@vortexilation

Thanks for bringing this issue to our attention, however, this PR is specifically for the host build of libelf, in which we have disabled shared objects, and you are experiencing this runtime link problem for the target build of libelf. For the host build, there has been a lot of adjustments through patches and incorporating gnulib modules and other Makefile overrides in order to get it to build on macOS. The target build doesn't suffer from the same problems because it uses the target's musl C library which we have full control over as well as linux headers instead of BSD/Mac headers which is the environment it is expected to build on. This means that the target build for libelf is mostly untouched and only has small adjustments. Once we have the host build more organized we can possibly pass on some of the fixes to the target build like the ability to disable shared objects. However to me, it looks like it may have something to do with either the rpath value which is not something we modify for the host build, or that libintl is not being built yet, possibly because it's not properly listed as a dependency.

The Makefiles that control the two builds are:

host:
`tools/elfutils/Makefile`

target:
`package/libs/elfutils/Makefile`

Also, I spotted a patch related to libintl, which is probably a good place to start figuring out what's wrong.
`package/libs/elfutils/patches/003-libintl-compatibility.patch`

For now, you're welcome to start a github issue for your specific problem
https://bugs.openwrt.org

**Comment by mpratt14** [comment]
has the linux build problem already been there as well? I can't see how it would be related to this...

**Comment by mpratt14** [comment]
@httpstorm could you try ath79 with kernel 6.1?

**Comment by httpstorm** [comment]
@mpratt14 
> has the linux build problem already been there as well? I can't see how it would be related to this...

I thought about it. The last build I made for my routers was about 2-3 weeks ago. I will have to test again.

> could you try ath79 with kernel 6.1?

ATH79, TL-WR1043N/ND v4, using the main kernel 6.1 compiled successfully. Then I enabled `frr` and `frr/host` failed. It compiled successfully a few days ago when my `frr` PR was accepted.

``` C
ld: warning: object file (/Volumes/test/m/ath79/openwrt/staging_dir/hostpkg/lib/libpython3.11.a[147](frozen.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      ___libelf_compress in libelf.a[116](elf_compress.o)
  "_deflateEnd", referenced from:
      ___libelf_compress in libelf.a[116](elf_compress.o)
      ___libelf_compress in libelf.a[116](elf_compress.o)
      ___libelf_compress in libelf.a[116](elf_compress.o)
      ___libelf_compress in libelf.a[116](elf_compress.o)
      ___libelf_compress in libelf.a[116](elf_compress.o)
      ___libelf_compress in libelf.a[116](elf_compress.o)
  "_deflateInit_", referenced from:
      ___libelf_compress in libelf.a[116](elf_compress.o)
  "_inflate", referenced from:
      ___libelf_decompress_zlib in libelf.a[116](elf_compress.o)
  "_inflateEnd", referenced from:
      ___libelf_decompress_zlib in libelf.a[116](elf_compress.o)
  "_inflateInit_", referenced from:
      ___libelf_decompress_zlib in libelf.a[116](elf_compress.o)
  "_inflateReset", referenced from:
      ___libelf_decompress_zlib in libelf.a[116](elf_compress.o)
  "_tdestroy", referenced from:
      _elf_end in libelf.a[9](elf_end.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
[x64.2024-06-14.05-frr-host.txt](https://httpstorm.com/share/.openwrt/test/2024-03-12_xcode-15.3/x64.2024-06-14.05-frr-host.txt)

**Comment by mpratt14** [comment]
@httpstorm

After a lot of rearranging and adding the LIBS variable to LIBADD variables, the lack of `tdestroy` should be gone from the error. However, the rest of it might still be missing. This is because libtool uses `gcc` to link objects and includes the `-lz` linker option among others, while without libtool, automake uses `ar` where you cannot use linker options. So if you see a similar situation, we need to add an `-lz` linker option to the LDFLAGS in `frr`. (this is really how static linking is supposed to work, honestly)

**Comment by mpratt14** [comment]
ok hold up...

another drawback from having `ar` create the library instead of `ld` from `gcc` is that I can't put a library in the list of library members, so I have to extend what I did for replacing `ar` for creating a list of objects in a library...

**Comment by httpstorm** [comment]
@mpratt14 
Hi Michael, I haven't had the opportunity to test your latest changes yet, I did however compile main 05aec66d5326974a636afe9fbf678a86c7f4e5c8, and found that `target/linux` fails for target x64, since the switch to 6.6 in 06d5d7b7bf2452c318f7ccc0a7248cf2491c9134. It builds successfully for TL-WR1043ND (atd79), and WRT3200ACM. Currently all three platforms are on linux-6.6. So as you suspected the `'linux/stddef.h' file not found` error is not related to your changes.

**Comment by mpratt14** [comment]
just wait, I'm about to push again 

you would have the same error as the CI at the moment

**Comment by mpratt14** [comment]
@httpstorm 

ok it's ready to test again

**Comment by httpstorm** [comment]
@mpratt14 
Tools and toolchain compile successfully. Any idea how to fix the unrelated `target/linux` error on x64 so I can confirm that the entire build process works and also test some packages? Meanwhile I will try building WRT3200ACM.

**Comment by vortexilation** [comment]
@httpstorm 

Try this [PR ](https://github.com/openwrt/openwrt/pull/15390)for fixing somekind of missing header.

**Comment by Ansuel** [comment]
mhhh linux/stddef.h is more of an include problem of the package... unrelated to my pr

**Comment by mpratt14** [comment]
I have not looked into the missing header issue, not even sure if it can be reproduced on my system.

**Comment by mpratt14** [comment]
> mhhh linux/stddef.h is more of an include problem of the package...

@Ansuel we are referring to a problem that's actually on main branch right now, when building kernel 6.6 only (and possibly when building on Macs only)

**Comment by robimarko** [comment]
@mpratt14 When did the header issue happen?

Because, I have compiled on macOS 14.5 for qualcommax just fine to test this PR.

**Comment by httpstorm** [comment]
@vortexilation 
Thanks, but the PR you mentioned affects the BPF package, while the error I have with the same header is about linux kernel.

@robimarko 
It happened since x64 switched from 6.1 to 6.6. ATH79 and WRT3200ACM are not affected and build fine on 6.6, only x64 is known to be broken so far.

**Comment by mpratt14** [comment]
@robimarko 

this is probably my last update, this should be ready now
the missing linux header, while it is still important to fix, has nothing to do with this PR

 - extended changes to more subdirectories to be consistent
 - updated commit messages

I posted a PR to fix frr host build which will now require the zlib linker flag to build
because the libelf functions depend on zlib, but the static libelf will no longer contain zlib functions.

https://github.com/openwrt/packages/pull/24412

**Comment by mpratt14** [comment]
I think the CI failed randomly, but I'm going to double check...

**Comment by Ansuel** [comment]
@mpratt14 refresh patch

**Comment by mpratt14** [comment]
> @mpratt14 refresh patch

yep, that was it, thanks 👍🏼

**Comment by httpstorm** [comment]
@mpratt14 Build successful with your `frr` PR for WRT3200ACM.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
