### PR TITLE
package/utils/f2fs-tools: Update to 1.11.0

### PR DESCRIPTION
**Pull request by diizzyy**
Update f2fs-tools to 1.11.0

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile and Runtime tested on: mt7621, WiTi Board, OpenWrt master

**Comment by blogic** [comment]
merged, Thanks !

**Comment by tofurky** [comment]
fwiw, the fsck.f2fs in 1.11 is completely broken for me on ath79. i had to downgrade to 1.10.

**Comment by diizzyy** [comment]
@tofurky 
Can you provide a log or something?

**Comment by tofurky** [comment]
seems to at least hit this which was added recently: https://git.kernel.org/pub/scm/linux/kernel/git/jaegeuk/f2fs-tools.git/tree/fsck/fsck.c#n350

```
Info: Force to fix corruption
Info: [/dev/sda1] Disk Model: STORAGE DEVICE  9451�#GENE
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 3334144 (1628 MB)
Info: MKFS version
  "Linux version 4.14.67 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Tue Aug 28 21:05:39 2018"
Info: FSCK version
  from "Linux version 4.14.67 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Tue Aug 28 21:05:39 2018"
    to "Linux version 4.14.67 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Tue Aug 28 21:05:39 2018"
Info: superblock features = 0 : 
Info: superblock encrypt level = 0, salt = 00000000000000000000000000000000
Info: total FS sectors = 3334144 (1628 MB)
Info: CKPT version = 6bb1f686
Info: Corrupted valid nat_bits in checkpoint
Info: Write valid nat_bits in checkpoint
Info: checkpoint state = c4 :  nat_bits crc compacted_summary sudden-power-off
[ASSERT] (__check_inode_mode: 351)  --> inode [0x3] unknown file type i_mode [0x41ed0000]

NID[0x3] is unreachable
NID[0x4] is unreachable
NID[0x5] is unreachable
NID[0x6] is unreachable
NID[0x7] is unreachable
NID[0x8] is unreachable
NID[0xa] is unreachable
NID[0xb] is unreachable
NID[0xf] is unreachable
NID[0x10] is unreachable
NID[0x13] is unreachable
NID[0x14] is unreachable
NID[0x15] is unreachable
NID[0x16] is unreachable
NID[0x17] is unreachable
NID[0x18] is unreachable
NID[0x19] is unreachable
NID[0x1a] is unreachable
NID[0x1b] is unreachable
NID[0x1c] is unreachable
NID[0x1d] is unreachable
NID[0x1e] is unreachable
NID[0x1f] is unreachable
NID[0x20] is unreachable
NID[0x21] is unreachable
NID[0x23] is unreachable
[FSCK] Unreachable nat entries                        [Fail] [0x1a]
[FSCK] SIT valid block bitmap checking                [Fail]
[FSCK] Hard link checking for regular file            [Ok..] [0x0]
[FSCK] valid_block_count matching with CP             [Fail] [0x0]
[FSCK] valid_node_count matcing with CP (de lookup)   [Fail] [0x0]
[FSCK] valid_node_count matcing with CP (nat lookup)  [Ok..] [0x1a]
[FSCK] valid_inode_count matched with CP              [Fail] [0x0]
[FSCK] free segment_count matched with CP             [Ok..] [0x31d]
[FSCK] next block offset is free                      [Ok..]
[FSCK] fixing SIT types
[FSCK] other corrupted bugs                           [Fail]
```

**Comment by diizzyy** [comment]
@tofurky
While I don't have an ath71 device available right now the mt7621 board I have is very similar however I can't reproduce what you're seeing.
It should be mentioned that this box using using -O2 default instead of -Os and GCC 7.3.0 + binutils 2.31.1 .

I'd suggest that you try GCC 7.3.0 first


```
root@OpenWrt:~# mkfs.f2fs /dev/sdb1

        F2FS-tools: mkfs.f2fs Ver: 1.11.0 (2018-07-10)

Info: Disable heap-based policy
Info: Debug level = 0
Info: Label =
Info: Trim is enabled
Info: [/dev/sdb1] Disk Model: USB FLASH DRIVE▒
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 60618719 (29598 MB)
Info: zone aligned segment0 blkaddr: 512
Info: format version with
  "Linux version 4.14.62 (diizzy@debian-buildbox-v3) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r7848+4-405cae4c54)) #0 SMP Fri Aug 17 07:31:14 2018"
Info: [/dev/sdb1] Discarding device
Info: This device doesn't support BLKSECDISCARD
Info: This device doesn't support BLKDISCARD
Info: Overprovision ratio = 1.170%
Info: Overprovision segments = 347 (GC reserved = 178)
Info: format successful

root@OpenWrt:~# mount /dev/sdb1 /mnt
root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                12.5M     12.5M         0 100% /rom
tmpfs                   124.0M     10.1M    114.0M   8% /tmp
/dev/mtdblock6            1.4M    272.0K      1.2M  18% /overlay
overlayfs:/overlay        1.4M    272.0K      1.2M  18% /
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/sdb1                28.9G    199.0M     28.0G   1% /mnt

root@OpenWrt:~# dd if=/dev/urandom of=/mnt/dummy.file bs=1M count=4096
4096+0 records in
4096+0 records out

root@OpenWrt:~# sha256sum /mnt/dummy.file
30b4a338cf3aaa63a6d558f2bf208378f28a51a3cd5a996ad42fc4941a3d4366  /mnt/dummy.file

root@OpenWrt:~# umount /mnt

root@OpenWrt:~# mount /dev/sdb1 /mnt

root@OpenWrt:~# sha256sum /mnt/dummy.file
30b4a338cf3aaa63a6d558f2bf208378f28a51a3cd5a996ad42fc4941a3d4366  /mnt/dummy.file

```

**Comment by tofurky** [comment]
yeah i used -02 as well. i was thinking it might be related to gcc-8. i'd need to rebuild and reflash the router to test so it will have to wait a bit. i checked to see where S_ISLNK et al. were defined and it's musl.

**Comment by diizzyy** [comment]
@tofurky 
You might want to give this a try although I doubt it's related/helps
https://lists.openwrt.org/pipermail/openwrt-devel/2018-July/013394.html

**Comment by cshoredaniel** [comment]
On 2018-08-30 05:45 AM, Daniel Engberg wrote:
>
> @tofurky <https://github.com/tofurky>
> While I don't have an ath71 device available right now the mt7621
> board I have is very similar however I can't reproduce what you're seeing.
>

For the record on ar934x boards I see the same thing.  I'm not sure if
it's a ar71xx/ar9xxx funkiness with the USB that is real culprit or an
something else (errata in the MIPS implementation?), or what.

Regards,

Daniel

**Comment by hauke** [comment]
Do you see this problem also with the default settings OpenWrt uses or only when using gcc 8 or other changes from the default?

**Comment by cshoredaniel** [comment]
On 2018-08-30 06:28 AM, Hauke Mehrtens wrote:
> Do you see this problem also with the default settings OpenWrt uses or
> only when using gcc 8 or other changes from the default?

Well the only difference for the kernel is I'm not building all kernel
modules but just the ones I want.  No toolchain changes.

I will do a test build, probably over the holiday weekend, to gather
more details.  It's always just been bad timing for debugging for me,
but now I can and have a free device and USB stick.

Regards,

Daniel

**Comment by cshoredaniel** [comment]
forgot about this...will try to get to in next few days

**Comment by tofurky** [comment]
my rspro isn't showing the "not running at top speed". the reader is hard-wired:
```
[    0.602932] ar7100-usb-phy 18030000.usb-phy: phy reset is missing
[    3.339372] usbcore: registered new interface driver usbfs
[    3.345011] usbcore: registered new interface driver hub
[    3.350421] usbcore: registered new device driver usb
[    3.372353] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    3.998388] ehci-platform 1b000000.usb: EHCI Host Controller
[    4.004117] ehci-platform 1b000000.usb: new USB bus registered, assigned bus number 1
[    4.012105] ehci-platform 1b000000.usb: irq 3, io mem 0x1b000000
[    4.042107] ehci-platform 1b000000.usb: USB 2.0 started, EHCI 1.00
[    4.049050] hub 1-0:1.0: USB hub found
[    4.059643] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    4.072755] ohci-platform 1c000000.usb: Generic Platform OHCI controller
[    4.079530] ohci-platform 1c000000.usb: new USB bus registered, assigned bus number 2
[    4.087509] ohci-platform 1c000000.usb: irq 12, io mem 0x1c000000
[    4.166841] hub 2-0:1.0: USB hub found
[    4.178758] usbcore: registered new interface driver usb-storage
[    4.616597] usb 1-2: new high-speed USB device number 2 using ehci-platform
[    4.877916] usb-storage 1-2:1.0: USB Mass Storage device detected
[    4.884666] usb-storage 1-2:1.0: Quirks match for vid 05e3 pid 0723: 8000
[    4.891615] scsi host0: usb-storage 1-2:1.0
[    6.037946] scsi 0:0:0:0: Direct-Access     Generic  STORAGE DEVICE   9451 PQ: 0 ANSI: 0
[    6.328204] sd 0:0:0:0: [sda] 3862528 512-byte logical blocks: (1.98 GB/1.84 GiB)
[    6.337070] sd 0:0:0:0: [sda] Write Protect is off
[    6.341890] sd 0:0:0:0: [sda] Mode Sense: 03 00 00 00
[    6.343204] sd 0:0:0:0: [sda] No Caching mode page found
[    6.348546] sd 0:0:0:0: [sda] Assuming drive cache: write through
[    6.362802]  sda: sda1 sda2
[    6.370207] sd 0:0:0:0: [sda] Attached SCSI removable disk
```

**Comment by diizzyy** [comment]
I'll try to test 4.9 next week to see if it makes any difference (both  USB speed and the general fsck failure) unless someone else beats me to it. :-)

**Pull request closed without merging**
