### PR TITLE
ar71xx: add support for EnGenius EMR3000

### PR DESCRIPTION
**Pull request by bk138**
EnGenius EMR3000 is a dual-band AC1200 router based on QCA9558.

Specifications:

- 720/600/240 MHz (CPU/DDR/AHB)
- 128 MB of RAM
- 32 MB of FLASH (SPI NOR)
- 2x 10/100/1000 Mbps Ethernet
- 2T2R 2.4 GHz (QCA9558), 802.11b/g/n, output power (max): 158 mW (22 dBm)
- 2T2R 5 GHz (QCA988X), 802.11ac/n/a, output power (max): 199 mW (23 dBm)
- 1x USB 2.0
- 4x LED, driven by GPIO
- 1x button (reset)
- DC jack for main power input
- UART header on PCB

Flash instructions:

As the vendor firmware is based on OpenWrt, you can flash the sysupgrade
image via the vendor GUI. There is no "Keep settings" checkbox, so make
sure to factory-reset after flashing by holding down reset for 5s to get
rid of the vendor config and be able to login.

Alternatively, you can flash via TFTP, the UART pins are wired as follows:

+---+-+
|RX |.|
|TX |.|
|GND|.|
|.  |.|◀
+---+-+
 ▲

Signed-off-by: Christian Beier <dontmind@freeshell.org>

### CODE REVIEW

**Comment by bk138** [comment]
Hello @dedeckeh, I'd like to kindly ask if there is anything missing from my part here. Shall I rather resend this on the mailing list or is there a schedule I do not know of?

**Comment by dedeckeh** [comment]
@bk138 No need to re-send the patch on the mailing list; review needs to be done by someone familiar with the ar71xx target. As most people do this in their free time some patience is required

**Comment by bk138** [comment]
OK, I understand.

**Comment by hanetzer** [comment]
@bk138 do you not have a factory image build? Or are they closer to 'good' openwrt than
the engenius devices I've dealt with?

**Comment by bk138** [comment]
I updated this PR to resolve conflicts with master that occured due to master development progress in the hope this might get merge some day.

**Comment by bk138** [comment]
@matejkupljen you're right, my refresh from 8d ago had gone wrong. Now 5911c1bbae15abc8d5271e62b2cdef8d7e9cc9d4 includes mach-emr3000.c again and has config-4.4 not included anymore. Sry for the fuckup.

**Comment by matejkupljen** [comment]
Thanks for the updated patch. I tried it on mine EMR3000 and after some initial basic testing it works, but with some changes to /etc/config/network. Although the target/linux/ar71xx/base-files/etc/board.d/02_network looks O.K., my configuration for the network isn't O.K. the eth0 and eth1 are reversed so the network does not work. This is how it looks after the flashing:

`config interface 'loopback'`
`        option ifname 'lo'`
`        option proto 'static'`
`        option ipaddr '127.0.0.1'`
`        option netmask '255.0.0.0'`

`config globals 'globals'`

`config interface 'lan'`
 `       option type 'bridge'`
`        option ifname 'eth0'`
`        option proto 'static'`
`        option ipaddr '192.168.1.1'`
`        option netmask '255.255.255.0'`
`        option ip6assign '60'`
`        option macaddr '88:DC:96:61:75:70'`

`config interface 'wan'`
`        option ifname 'eth1'`
`        option proto 'dhcp'`
`        option macaddr '88:DC:96:61:75:70`

When I change eth0 and eth1, everything works.

**Comment by bk138** [comment]
@matejkupljen Thanks for testing. It looks like you have settings from the OEM firmware (which is based on OpenWrt). Please see flashing instructions above, you need to factory reset after flashing as there's no "keep settings" checkbox to untick in OEM firmware.

**Comment by matejkupljen** [comment]
I don't think this is the case, since I followed the instructions for the first time and I also flashed the device several times using serial port and doing `sysupgrade -n image.bin`, to delete the configuration. Still checking why this would happen.

**Comment by bk138** [comment]
Updated the PR again...

**Comment by hanetzer** [comment]
@bk138 you may want to go ahead and target the ath79 target. Its the same hardware but
uses a dts file instead of a mach.c file to describe the hardware.

**Comment by bk138** [comment]
@hanetzer OK. Is there any porting guide available regarding mach file to dts?

**Comment by bk138** [comment]
So is it the porting over to ath79 that's holding this PR off? I see that there were additions to ar71xx just recently (4caab808300ad75575d778bae6e184caa26aeabc).

**Comment by ynezz** [comment]
@bk138 I've asked other developers about ar71xx/ath79 preference on IRC at #openwrt-devel and the outcome was, that although adding ath79 support is not mandatory, you would probably get your contribution reviewed and merged faster.

I think, that main blocking issue is, that missing ath79 support for this router would mean, that someone else would need to convert it to DTS once the ar71xx is going to be deprecated. Providing working DTS without the actual hardware for testing is quite hard. And you're adding relatively a lot of code, which someone would need to maintain. And some of that code is probably already generic in ath79.

**Comment by ynezz** [comment]
@bk138 Thank you for this contribution, but unfortunately it seems like it's not going to be merged since nobody has touched this PR for ages. Please could you try to submit support for this board in ath79?

**Comment by bk138** [comment]
Yeah it's a pity but we don't need this device anymore. Maybe someone else will pick up from here and port to ath79.

**Pull request closed without merging**
