### PR TITLE
octeon: Generate writable images for ERL

### PR DESCRIPTION
**Pull request by diizzyy**
Generate writable images for EdgeRouter Lite

Based on:
https://github.com/openwrt/openwrt/tree/master/target/linux/apm821xx/image
https://github.com/openwrt/openwrt/tree/master/target/linux/sunxi/image

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
As far as I can tell it works fine on my ERL so hopefully it seems that I haven't broken anything.
Can you please have a look @nbd168 @pkgadd ?
I couldn't figure out how toset  ext4 as overlayfs instead of f2fs however...

**Comment by chunkeey** [comment]
> I couldn't figure out how toset ext4 as overlayfs instead of f2fs however...

It's this check: https://lxr.openwrt.org/source/fstools/libfstools/rootdisk.c#L118

the CONFIG_TARGET_ROOTFS_PARTSIZE needs to be set to less than 100 (MiB) in order to have a ext4 rootfs.

**Comment by diizzyy** [comment]
@chunkeey 
Many thanks for looking into my overlayfs question!
I know it does use a HDD however the code is clean (easy enough for me to understand at least somewhat what it does) and it's one of the targets I know which uses ext4 as rootfs.

**Comment by diizzyy** [comment]
Ping

**Comment by diizzyy** [comment]
Anything that needs to be done to get this in?

**Comment by chunkeey** [comment]
Is there anything wrong with the squashfs files? From what I know squashfs + overlay would be preferred since the filesystem located on a flash-based USB-Stick.

**Comment by diizzyy** [comment]
I added those as loop+f2fs is broken on multiple platforms including this one throwing I/O errors (https://github.com/openwrt/openwrt/pull/1800) and I don't think anyone wants to risk their data at this point? 

I've seen this claim several times but never really seen any evidence of being an actual issue unless in some extreme conditions. see https://www.redhat.com/archives/ext3-users/2013-August/msg00001.html etc for more information. OpenWrt by default writes very little to flash so it's most likely not an issue in 2019. 

Side note: Running FreeBSD off a Sandisk USB stick for years (UFS) without any kind of excessive efforts to lower amount of writes worked flawless on this device.

**Comment by chunkeey** [comment]
> I added those as loop+f2fs is broken on multiple platforms including this one throwing I/O errors (#1800) and I don't think anyone wants to risk their data at this point?

I don't understand why you would not tackle this issue at the "root" and fix that broken f2fs+loop directly. Because from what I do understand, this is the solution you are looking for, right?

I think a good place to start would be write a proper bug report (ideally you would perform a bisection with git since this was working "before") and sent it off to the LKML (like linux-fsdevel, linux-block). If you looking for a good introduction for this process, I suggest following along the reporting-bugs guide: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/reporting-bugs.rst .

**Comment by diizzyy** [comment]
So in the meantime you suggest that having a potential unreliable filesystem for storage is a good idea?

**Comment by chunkeey** [comment]
> So in the meantime you suggest that having a potential unreliable filesystem for storage is a good idea?

Now you are putting words in my mouth. I guess this goes nowhere in a hurry.

**Comment by nbd168** [comment]
Another intermediate solution would be to change fstools to avoid using f2fs as overlay if it isn't enabled in the kernel. Still better than building pure ext4 images.

**Comment by diizzyy** [comment]
@chunkeey 
I'm not a filesystem developer and since I don't run OpenWrt on many different systems I'm unable to verify but I think the sources can be considered reliable. I'm just a bit surprised that you don't find these issues concerning. It wasn't my intention to "putting words in my mouth" so I apologize if it sounded that way. That said, I have very little trust in f2fs compared to ext4 despite being on flash memory.

@nbd168 
That would effectively mean that even if you'd want to use / test f2fs you'd be forced to use it as overlayfs? Perhaps making it a menu option would be a better idea?

**Comment by diizzyy** [comment]
@nbd168 
I can ofc drop the ext4 only images if that's required

**Comment by ynezz** [comment]
We really should fix this problem at it's origin and use workarounds as the last resort. It really seems like a problem with loop block device, no matter what filesystem is mounted over it, I've already started hunting that down, but got distracted by other tasks, anyway FWIW here are some stack traces produced with following patch (maybe someone could spot some issue already):

```diff
diff --git a/block/blk-core.c b/block/blk-core.c
index 0b14aeb..0ac24e7 100644
--- a/block/blk-core.c
+++ b/block/blk-core.c
@@ -182,7 +182,8 @@ static void print_req_error(struct request *req, blk_status_t status)
 	if (WARN_ON_ONCE(idx >= ARRAY_SIZE(blk_errors)))
 		return;
 
-	printk_ratelimited(KERN_ERR "%s: %s error, dev %s, sector %llu\n",
+	dump_stack();
+	printk(KERN_ERR "%s: %s error, dev %s, sector %llu\n",
 			   __func__, blk_errors[idx].name, req->rq_disk ?
 			   req->rq_disk->disk_name : "?",
 			   (unsigned long long)blk_rq_pos(req));

```

```
[    4.020854] mount_root: rootdisk overlay filesystem has not been formatted yet
[    4.070230] random: mkfs.f2fs: uninitialized urandom read (16 bytes read)
[    4.071513] CPU: 0 PID: 891 Comm: loop0 Not tainted 4.14.105 #0
[    4.073976] Call Trace:
[    4.074517]  dump_stack+0x63/0x83
[    4.075268]  blk_update_request+0x58/0x230
[    4.076038]  blk_mq_end_request+0x19/0x60
[    4.076767]  lo_complete_rq+0x65/0x70
[    4.077443]  __blk_mq_complete_request+0x121/0x130
[    4.078265]  blk_mq_complete_request+0x11/0x20
[    4.079043]  loop_queue_work+0x920/0x9a0
[    4.079753]  ? __switch_to+0x292/0x2e0
[    4.080449]  ? __schedule+0x3ca/0x410
[    4.081120]  ? __switch_to+0x292/0x2e0
[    4.081865]  kthread_worker_fn+0xe2/0x170
[    4.082922]  loop_kthread_worker_fn+0x19/0x20
[    4.084059]  kthread+0x112/0x120
[    4.084985]  ? figure_loop_size+0xa0/0xa0
[    4.086057]  ? kthread_create_on_node+0x40/0x40
[    4.087229]  ret_from_fork+0x35/0x40
[    4.088248] print_req_error: I/O error, dev loop0, sector 0
[    4.190481] F2FS-fs (loop0): Found nat_bits in checkpoint
[    4.193435] F2FS-fs (loop0): Mounted with checkpoint version = 500f0ae9
[    4.194586] mount_root: overlay filesystem has not been fully initialized yet
[    4.195790] mount_root: switching to f2fs overlay
```

```
[    3.964936] mount_root: rootdisk overlay filesystem has not been formatted yet
[    4.305716] CPU: 0 PID: 924 Comm: loop0 Not tainted 4.19.25 #0
[    4.313292] Call Trace:
[    4.315071]  dump_stack+0x63/0x85
[    4.317065]  blk_update_request+0x58/0x220
[    4.319454]  blk_mq_end_request+0x1b/0xa0
[    4.321759]  lo_complete_rq+0x99/0xb0
[    4.324013]  blk_mq_complete_request+0x101/0x110
[    4.326546]  loop_queue_work+0x8f2/0x980
[    4.328999]  ? __switch_to_asm+0x34/0x70
[    4.331452]  ? __switch_to_asm+0x34/0x70
[    4.333730]  ? __switch_to_asm+0x40/0x70
[    4.336176]  ? __switch_to_asm+0x40/0x70
[    4.338389]  ? __schedule+0x3cd/0x410
[    4.340589]  kthread_worker_fn+0xe2/0x170
[    4.342146]  loop_kthread_worker_fn+0x19/0x20
[    4.343802]  kthread+0x10b/0x120
[    4.345140]  ? figure_loop_size+0xa0/0xa0
[    4.346464]  ? kthread_park+0x80/0x80
[    4.347588]  ret_from_fork+0x35/0x40
[    4.348706] print_req_error: I/O error, dev loop0, sector 0
[    4.350726] random: mkfs.ext4: uninitialized urandom read (16 bytes read)
[    4.467962] EXT4-fs (loop0): mounted filesystem with ordered data mode. Opts: (null)
[    4.472746] mount_root: overlay filesystem has not been fully initialized yet
[    4.474476] mount_root: switching to ext4 overlay
[    4.498215] EXT4-fs (sda1): mounted filesystem without journal. Opts: (null)
```

**Comment by diizzyy** [comment]
More reports...
https://forum.openwrt.org/t/i-o-error-on-kernel-4-19-xx/36522

If I remove the ext4 only images, it's good to go?

**Comment by diizzyy** [comment]
@ynezz 
Can you perhaps have a look at the rest of the code? I'm not sure if it's done correctly as I can't really find any documentation at all about this.

**Comment by diizzyy** [comment]
@hauke 
Can you please have a look at this?

**Comment by diizzyy** [comment]
Ping

**Comment by chunkeey** [comment]
@diizzyy 

pong

https://github.com/openwrt/openwrt/commit/82f3a2b81e72f5d672f599d3dcb2959055f52418

**Comment by ynezz** [comment]
So what about this PR?

**Comment by diizzyy** [comment]
What about it?

**Comment by diizzyy** [comment]
Ping again...

**Comment by ynezz** [comment]
> Ping again...

For example I still miss the answer to the `Why do you need this changes?` question in your commit message. So far it seems to me like some workaround to an "issue" which was probably fixed via 82f3a2b81e72f5d672f599d3dcb2959055f52418.

**Comment by diizzyy** [comment]
"Generate writable images for ERL" is self-explanatory although it should be changed to singularis as the ext4 only image is dropped. Right now there are no images at all generated. https://downloads.openwrt.org/snapshots/targets/octeon/generic/

**Comment by diizzyy** [comment]
@hauke 
Can you have a look at this? It's been sitting here for months now...

**Comment by diizzyy** [comment]
Is anyone going to do anything about this or is it simply going to bitrot?

**Comment by diizzyy** [comment]
Superseded by https://github.com/openwrt/openwrt/pull/2900

**Pull request closed without merging**
