### PR TITLE
ksmbd: update to 3.4.4

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by neheb** [comment]
Thanks for handling this. I was reluctant to update it as @pesa1234 reported issues with 3.4.4 and thunar, but it seems this update is needed anyways.

**Review by abelian424 — APPROVED** [review]

**Comment by ptpt52** [comment]
something wrong with ksmbd? guest access never work
config:
```
config globals
	option workgroup 'WORKGROUP'
	option description 'Ksmbd on OpenWrt'

config share
	option name 'mnt'
	option path '/mnt'
	option read_only 'no'
	option guest_ok 'yes'
	option create_mask '0666'
	option dir_mask '0777'
	option force_root '1'
```

```
% mount_smbfs //guest@192.168.16.1/mnt mnt
mount_smbfs: server rejected the connection: Authentication error
```

**Comment by jaharon** [comment]
@neheb 
There's something amiss with 3.4.4
When trying to browse or map/mount
for some clients, debug mode shows, before the client failing (with `mount_smbfs: server connection failed: Invalid argument` for users with password, or with `mount_smbfs: server rejected the connection: Authentication error` for guest )
```
ksmbd: RFC1002 header 162 bytes
ksmbd: got SMB2 command
ksmbd: SMB2 data length 74 offset 88
ksmbd: SMB2 len 162
ksmbd: Limits exceeding the maximum allowable outstanding requests, given : 1, pending : 4294967295
```
Currently I only see this in MacOS 12.2.1

Works ok:
Kodi 19.3 (Nvidia Shield tv)
Windows 10 21H2
Ubuntu 22.04.3

I checked with 3.4.3 tools and 3.4.3 kernel module and all the clients work ok (with my initial test of trying to map/mount and browse)

If the tools are on 3.4.4 and the kernel module is on 3.4.3 (the current state of openwrt), this patch is required https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=41dbda16a090

I started tracing the issue to this commit https://github.com/cifsd-team/ksmbd/commit/1b6e50b7e8473c63081cead0db7a022714272c0f, but I'm not sure if it's a symptom or the issue yet.

**I would not recommend merging this at this time, I would consider downgrading ksmbd-tools to 3.4.3.**

@ptpt52 
The issue described above might be the same issue as you are seeing, although you might just be missing `map to guest = Bad User` in your globals config.

Use debug mode, if you can, to get more info
```
echo all > /sys/class/ksmbd-control/debug
```

**Comment by ptpt52** [comment]
@jaharon  thanks 
I just use the debug mode 
log:
```
[423888.546270] ksmbd: connect success: accepted new connection
[423888.655722] ksmbd: connect success: accepted new connection
[423888.657044] ksmbd: RFC1002 header 69 bytes
[423888.661112] ksmbd: got SMB
[423888.664502] ksmbd: SMB2 byte count 34, struct size : 0
[423888.669464] ksmbd: SMB1 len 69
[423888.672480] ksmbd: client requested dialect NT LM 0.12
[423888.676005] ksmbd: client requested dialect SMB 2.002
[423888.681306] ksmbd: client requested dialect SMB 2.???
[423888.686297] ksmbd: selected SMB 2.??? dialect
[423888.691217] ksmbd: conn->dialect 0x2ff
[423888.696014] ksmbd: conn->dialect 0x2ff
[423888.699549] ksmbd: Upgrade to SMB2 negotiation
[423888.703368] ksmbd: credits: requested[1] granted[1] total_granted[1]
[423888.715957] ksmbd: RFC1002 header 240 bytes
[423888.716295] ksmbd: got SMB2 command
[423888.719385] ksmbd: no length check for command
[423888.722952] ksmbd: SMB2 data length 0 offset 0
[423888.727542] ksmbd: SMB2 len 100
[423888.735156] ksmbd: cli req padded more than expected. Length 240 not 100 for cmd:0 mid:1
[423888.735732] ksmbd: client requested dialect 0x311
[423888.743173] ksmbd: selected SMB 3.1.1 dialect
[423888.747879] ksmbd: conn->dialect 0x311
[423888.752281] ksmbd: Received negotiate request
[423888.756371] ksmbd: decoding 4 negotiate contexts
[423888.760618] ksmbd: deassemble SMB2_PREAUTH_INTEGRITY_CAPABILITIES context
[423888.765394] ksmbd: deassemble SMB2_ENCRYPTION_CAPABILITIES context
[423888.772187] ksmbd: deassemble SMB2_COMPRESSION_CAPABILITIES context
[423888.778351] ksmbd: deassemble SMB2_NETNAME_NEGOTIATE_CONTEXT_ID context
[423888.784995] ksmbd: assemble SMB2_PREAUTH_INTEGRITY_CAPABILITIES context
[423888.791857] ksmbd: negotiate context offset 208, count 1
[423888.798323] ksmbd: credits: requested[1] granted[1] total_granted[1]
[423888.940789] ksmbd: RFC1002 header 162 bytes
[423888.942914] ksmbd: got SMB2 command
[423888.944379] ksmbd: SMB2 data length 74 offset 88
[423888.951483] ksmbd: SMB2 len 162
[423888.954756] ksmbd: Limits exceeding the maximum allowable outstanding requests, given : 1, pending : 4294967295
```

so it is the same issue..

**Comment by jaharon** [comment]
I think it got fixed in https://github.com/cifsd-team/ksmbd/commit/3bedd0eee4059d34de081eeb1d38722f78d20bfd
But I haven't tested it yet.

**Comment by ptpt52** [comment]
> I think it got fixed in [cifsd-team/ksmbd@3bedd0e](https://github.com/cifsd-team/ksmbd/commit/3bedd0eee4059d34de081eeb1d38722f78d20bfd) But I haven't tested it yet.
> 
> EDIT: That's not it.

great! just build and test it. it works!

**Comment by jaharon** [comment]
The issue I describe above is fixed in https://github.com/cifsd-team/ksmbd/commit/8f155815d9b87663278f6449325e9a5733ed6659

I just built it and tested and it fixed the issue.

It seems that 3.4.4 should be skipped for now.

**Comment by jaharon** [comment]
> > I think it got fixed in [cifsd-team/ksmbd@3bedd0e](https://github.com/cifsd-team/ksmbd/commit/3bedd0eee4059d34de081eeb1d38722f78d20bfd) But I haven't tested it yet.
> > EDIT: That's not it.
> 
> great! just build and test it. it works!

@ptpt52 

Thanks for your assistance with this.

You might have built from master so you got both commits (I used only the patch that I was testing), or maybe your issue was similar but different and was solved by the first commit.

**Comment by neheb** [comment]
So ksmbd-tools downgrade is needed?

**Comment by jaharon** [comment]
> So ksmbd-tools downgrade is needed?

That is my opinion, we can push ksmbd to 3.4.4, but we will need to maintain patches from the master branch.

On the other hand, we might want to have 3.4.4 (with patches) on openwrt master as it will help test 3.4.4, this is after all master and not stable.

I guess it depends on the changes from 3.4.3 to 3.4.4 and are they worth it.

I have a really simple use case for ksmbd and I've only been using it for 5 days, so I can't really decide.

**Comment by neheb** [comment]
@jaharon as I mentioned previously, @namjaejeon needs to cut a new release. Who knows when that will happen. IIRC the commit you linked to was a result of @pesa1234 's testing with Thunar.

**Comment by jaharon** [comment]
> @jaharon as I mentioned previously, @namjaejeon needs to cut a new release. Who knows when that will happen. IIRC the commit you linked to was a result of @pesa1234 's testing with Thunar.

@neheb 
I missed the conversation about the need to cut a new release, but I agree :)

Great job by @pesa1234 on tracking the issue!

**Comment by 4IceG** [comment]
Hi,
@neheb can you downgrade ksmbd-tools to 3.4.2? on 3.4.4 the network shares do not work (not only me).
Tested on Master openwrt-21.02 and on openwrt-22.03 and on Win7/10/11.

**Pull request closed without merging**
