### PR TITLE
kernel: add kmod-hwmon-sht3x support

### PR DESCRIPTION
**Pull request by ukleinek**
The driver supports the temperature and humidity sensors chips SHT3x and STS3x by Sensirion.

### CODE REVIEW

**Comment by ukleinek** [comment]
(rebased in the hope that the failing checks just go away, I didn't check them all, but the first few were problems that existed already before.)

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in cec9cbef449daea6529fbda64777ff1b7ae4e499.

**Comment by ukleinek** [comment]
@hauke: Thanks a lot. I wonder if this is eligible for a backport to `openwrt-22.03`?

**Comment by hauke** [comment]
backported to 22.03 in a907c203405b186d2436f24d0ac0bc19b6700852

**Pull request closed without merging**
