### PR TITLE
firewall: add rules to access from WAN

### PR DESCRIPTION
**Pull request by stokito**
Maintainer: @jow-
The rules are disabled, but a user will see them in config or GUI and easily enable if needed.

The whole idea is to make a Luci GUI wizard to enable WAN access https://github.com/openwrt/luci/issues/7137

Similarly, I think we should add a guest zone and a network, so that users can just enable it if needed. Will you accept a PR for this?

### CODE REVIEW

**Comment by mrkiko** [comment]
I would promote a more conscious path towards enabling remote access.

**Comment by mrkiko** [comment]
Well, I don't have a very strong opinion on this. But I would prefer the user to have to get their knowledge from the wiki and think about what they may need and want in the process.
Feel free to share it in the issue you pointed out if you think this point of view has somevalues. Thanks.

**Comment by Neustradamus** [comment]
Several weeks ago, I have done a comment here:
- https://github.com/openwrt/luci/pull/7138#issuecomment-2292812607

**Comment by blogic** [comment]
@stokito NAK on no longer using comments. the advantage of the comments is that a uci commit will remove them.
having them set to disabled would make the examples show up in luci.

**Pull request closed without merging**
