### PR TITLE
Add RSS variants to Realtek PCI ethernet drivers

### PR DESCRIPTION
**Pull request by Noltari**
Instead of enabling RSS support, let's introduce build variants and let users choose between them since RSS support can cause network issues.

### CODE REVIEW

**Comment by aiamadeus** [comment]
Most r8168 (rtl8111) chips do not support rss. Perhaps some newly produced variants support it.
But I've tried r8168 with rss enabled causing a big performance degradation.

**Comment by Noltari** [comment]
> Most r8168 (rtl8111) chips do not support rss. Perhaps some newly produced variants support it. But I've tried r8168 with rss enabled causing a big performance degradation.

Thanks for the report. I've dropped the r8168-rss variant.

**Comment by aiamadeus** [comment]
Thanks, but can we ignore this rss log? This log is noisy and useless.
```
--- a/src/r8125_rss.c
+++ b/src/r8125_rss.c
@@ -91,7 +91,7 @@ int rtl8125_get_rxnfc(struct net_device
         struct rtl8125_private *tp = netdev_priv(dev);
         int ret = -EOPNOTSUPP;
 
-        netif_info(tp, drv, tp->dev, "rss get rxnfc\n");
+        netif_dbg(tp, drv, tp->dev, "rss get rxnfc\n");
 
         if (!(dev->features & NETIF_F_RXHASH))
                 return ret;
```

**Comment by Noltari** [comment]
> Thanks, but can we ignore this rss log? This log is noisy and useless.

I haven't tested it yet with RSS enabled so I haven't seen how often that log appears.
But yeah, if it's too much we can ignore it.
Do you want to create a PR with that?

**Comment by aiamadeus** [comment]
> Do you want to create a PR with that?

I'll do it tomorrow or the day after.

**Pull request merged**
