### PR TITLE
ath79: move D-Link DIR-859 series to tiny sub-target

### PR DESCRIPTION
**Pull request by DragonBluep**
Some popular D-Link devices only have 64 MiB RAM. However, the ath10k wireless driver will consume a lot of memory. Let's move them to the `tiny` sub-target to get extra 7 MiB of free space. In this way, we can extend their lifetime to receive support for the next OpenWrt LTS (kernel 6.6) version.

On the other hand, the buildbot has not successfully built usable images for `ath79/tiny` sub-target for a long time due
to small Flash size. This PR can help us keep track of this sub-target.

### CODE REVIEW

**Comment by rx78gp01** [comment]
D-Link DIR-842 C series have 128 MiB RAM.
https://openwrt.org/toh/d-link/dir-842

**Comment by namiltd** [comment]
Many OpenWRT supported devices have 8MB flash and 64MB memory and are enabled by default. So the "DEFAULT := n" setting is incorrect in my opinion.

**Comment by raenye** [comment]
FWIW, D-Link DAP-1720 is 8/64 too.

**Comment by hauke** [comment]
> Many OpenWRT supported devices have 8MB flash and 64MB memory and are enabled by default. So the "DEFAULT := n" setting is incorrect in my opinion.

Currently it fails like this in buildbots:
````
    WARNING: Image file /builder/shared-workdir/build/build_dir/target-mips_24kc_musl/linux-ath79_tiny/tmp/openwrt-ath79-tiny-engenius_enh202-v1-squashfs-sysupgrade.bin is too big: 5505028 > 5046272
    WARNING: Image file /builder/shared-workdir/build/build_dir/target-mips_24kc_musl/linux-ath79_tiny/tmp/openwrt-ath79-tiny-engenius_enh202-v1-squashfs-factory.bin is too big: 5505028 > 5046272
````

These devices can not use the full 8MB flash, but only about 5MB, but we need 5.5MB.

**Pull request merged**
