### PR TITLE
ipq806x: fix MAC address on Meraki MR52 and MR42 after nvmem-layout

### PR DESCRIPTION
**Pull request by rkboni**
Based on similar fixes in https://github.com/openwrt/openwrt/pull/16624

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
So upstream, https://github.com/openwrt/openwrt/commit/d264d3a60ecc1 is what fixes it. Not sure if that should be backported instead.

**Comment by rkboni** [comment]
> So upstream, [d264d3a60ecc1](https://github.com/openwrt/openwrt/commit/d264d3a60ecc1) is what fixes it. Not sure if that should be backported instead.

Oh, didn't realize it had been fixed in https://github.com/openwrt/openwrt/pull/13952, and agree that it should probably be backported instead rather than fixing this piecemeal.  Is there a specific process for backporting changes from `main`?

**Comment by neheb** [comment]
git cherry-pick -x

**Comment by rkboni** [comment]
Thanks, meant more in terms of coordinating with the devs, but I'll close
this and cherry-pick the relevant change at the very least.

**Pull request closed without merging**
