### PR TITLE
tools/squashfs: rename to squashfs3-lzma

### PR DESCRIPTION
**Pull request by Ansuel**
The name of squashfs is confusing since in reality it's a really old version using an old lzma library. This tools is used for old ath79 netgear target and to produde a fake squasfs3 image needed for some specific bootloader from some OEM (AVM for example)

Rename squashfs tool to squasfs3-lzma to better describe it. Rename the installed bin from mksquashfs-lzma to mksquashfs3-lzma Also update any user of this tool.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@aparcar @hauke ok for you? Think it's a better name for this old tool

**Comment by Spudz76** [comment]
@Ansuel this uses `SRC_NAME` to fix the build 404 error, and makes the resulting host build dir as `squashfs3-lzma-3.0` using tar options to rename it during extraction.  The rest of everything follows as normal with `PKG_NAME`

https://github.com/Ansuel/openwrt/pull/9/files

**Comment by dhewg** [comment]
Isn't that what PKG_SOURCE_URL_FILE is for?

**Comment by Spudz76** [comment]
Not as far as I can tell, that seems to only change the name of the `dl/` file if it needs to be different than the `PKG_SOURCE` name.

The `TAR_OPTIONS` transform is needed to unpack into the correct build directory rather than the old name which remains in the source file.  Even if setting `PKG_SOURCE_URL_FILE`, which also seemed to have no effect.

**Comment by dhewg** [comment]
Alright.

But why not simply use `PKG_SOURCE:=squash$(PKG_VERSION).tar.gz` then? That's an official release, why muck around with it? Having 3.0 and 4.2 in the dl folder is pretty clear. Is there another reason except the cosmetic pgkname=dlname?

**Comment by aparcar** [comment]
Looks good, haven't yet checked why those tests fail

**Comment by Spudz76** [comment]
Because when the tarfile unpacks into `build_dir/host/` it creates the contained and statically named folder `build_dir/host/squashfs3.0/` and then tries to cd into `build_dir/host/squashfs3-lzma-3.0/` which doesn't exist.

**Comment by Ansuel** [comment]
@Spudz76 the difference is still there the package in build-dir is squashfs3.0 pretty clear. This change is to really rename the package name. Should we really add that tar transform option?

**Comment by Spudz76** [comment]
I prefer when I can locate the build_dir based directly from the package name rather than some other not-matching (even if fairly obvious) name.  But apparently nobody else cares so maybe I'm wrong that dir-names should directly map to the default location where one would expect to find them.  Least astonishment etc etc.  IMO the original file should have used tar-transform to correct the contained path to standards with the `-` in it, and not used `HOST_BUILD_DIR` at all.

**Comment by robimarko** [comment]
Can we just generate a static SquashFS3 blob and include it in the device builds instead of keeping SquashFS3 tooling around?

**Comment by dhewg** [comment]
That was my first idea, but then there's netgear: https://github.com/openwrt/openwrt/pull/10967#issuecomment-1419327294

**Comment by robimarko** [comment]
Ugh, so we need to keep old stuff around.
At least we can move to upstream SquashFS tools instead of our fork.

**Review by hauke — APPROVED** [review]

**Comment by hauke** [comment]
Renaming this to indicate that this is for squasfs3 only is good. This should reduce confusion. 
Does it build in a clean build? I think `HOST_BUILD_DIR` has to match the name of the folder in the tar.gz.

**Comment by Ansuel** [comment]
@hauke on second tought I think it's better to use tar transform... 

Can you check this new version?

---

@Spudz76 at the end i preferred your idea... seems nice and compact than adding bloat with a custom prepare thing...

**Comment by Spudz76** [comment]
If the folder in the tar has to match, then someone repack the tar since it's hosted at openwrt.org. :)

**Comment by Ansuel** [comment]
@Spudz76 that would change hash and the tar is hosted on sourceforce we just mirror it

**Comment by hauke** [comment]
looks good to me.

**Comment by Spudz76** [comment]
`produde a fake squasfs3`

`to squasfs3-lzma`

I guess nobody proofed the commit message, haha.  At least it's correct a few other times so keyword searches will still find it.

**Pull request merged**
