### PR TITLE
base-files: functions.sh: Add prepend() homologue to append()

### PR DESCRIPTION
**Pull request by pprindeville**
Add `prepend()` function to `functions.sh` to prepend a value (and optional separator) to a variable.  Useful for building strings right-to-left, such as domain names, etc.

### CODE REVIEW

**Comment by pprindeville** [comment]
See also: PR #12925

**Comment by Ansuel** [comment]
@pprindeville what about this? Also can you please add commit description?

**Comment by pprindeville** [comment]
> @pprindeville what about this? Also can you please add commit description?

Done

**Review by aparcar — APPROVED** [review]

**Comment by pprindeville** [comment]
@Ansuel Are we good to merge?

**Comment by pprindeville** [comment]
@kaloz @hauke @rsalvaterra @dangowrt Anyone else want to review and/or merge this please?

**Comment by pprindeville** [comment]
Urgently needed functionality for a rewrite of ISC-DHCP to Kea configuration files.

**Comment by aparcar** [comment]
Thanks!

**Pull request closed without merging**
