### PR TITLE
ramips: add TP-LINK TL-WR902AC v4

### PR DESCRIPTION
**Pull request by kjonca**
Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by Edmondena** [comment]
To Support the PR for the new TL-WR902AC v4 the following changes are suggested based on
OpenWrt 23.05.0 for ramips/mt76x8:

Please note that I have this recipe only working together with extroot as I do not know how to strip the manually added firmware files down to fit in the 8MB mtdblock4 device together with kmod-usb-storage and kmod-fs-ext4 or kmod-fs-btrfs which should be possible at least one or the other. Instead the simple "easy" solution could be to **not** provide any mt7615 5G Wifi support into the base image an have only the old common mt7603 2G4 wifi provided and plenty of space instead for v3 **and** v4 hardware. 

1. Install Openwrt image for v3 hardware revision
2. Suggested remove
    a) kmod-ppp  b) kmod-pppoe and c) kmod-pppox to maybe gain enough space for mt7615 Wifi drivers e.g # "opkg remove kmod-ppp"
3. # "opkg remove kmod-mt76x0e" and its dependencies kmod-mt76x0-common, kmod-mt76x02-common
4. Not know howto fit into base image (maybe first better remove the 5G support from base image?)
    a) # "opkg install kmod-mt7615e" and # "opkg install kmod-mt7663-firmware-ap"
    b) Not know howto include the manually added firmware binaries as required by dmesg boot failures (no idea howto strip unneeded content)
  - /lib/firmware/mediatek/mt7663_n9_v3.bin
  - /lib/firmware/mediatek/mt7663pr2h.bin
    c) Remove old 5G wireless interfaces: #rm -f /etc/config/wireless
    d) run # wifi config
5. Disconnect misconfigured hardware watchdog to prevent router freezing:
 - e.g. by 1st workaround in /etc/rc.local -> add: 
       # ubus call system watchdog "{ 'magicclose':true }"
       # ubus call system watchdog "{ 'stop':true }"
6. Decrease wasted memory in rc.local: # "sysctl -w vm.min_free_kbytes=1024"

Hope this helps as a 1st starting point to support Owrt on on this actually distributed low cost, low power travel router. Thanks in advance and BR

**Comment by giggid1** [comment]
Hi, I need to update my TL-WR902ac v4 with openwrt firmware, could you send me the commands to delete the v3 kmods and insert the v4 kmods? Thank you

**Comment by Edmondena** [comment]
Hello All!
Finally my WR902ACv4 has a likely OpenWrt Release based on this WR902ACv3 self created snapshot image referenced by: openwrt-23.05 branch (git-24.086.45142-09d5a38)
 /[ OpenWrt 23.05.3 (r23809-234f1a2efa)](https://openwrt.org/)

Maybe please someone wants to confirm this by the following Guideline and commit a pull request from it for the actual available Ramips based TL-WR902ACv4 Travel Router?

User & Developer Guide for compiling a stable Release Candidate for WR902ACv4:

**Step A:** Open the Firmware Selector for WR902AC
https://firmware-selector.openwrt.org/?version=23.05.3&target=ramips%2Fmt76x8&id=tplink_tl-wr902ac-v3

**Step B:** Adapt the minimal packages as suggested:
base-files busybox ca-bundle dnsmasq dropbear firewall4 fstools kmod-gpio-button-hotplug kmod-leds-gpio kmod-mt7603 kmod-nft-offload kmod-usb-ledtrig-usbport kmod-usb-ohci kmod-usb2 libc libgcc libustream-mbedtls logd luci mtd netifd nftables opkg procd procd-seccomp procd-ujail swconfig uci uclient-fetch urandom-seed urngd wpad-basic-mbedtls kmod-mt7615e kmod-mt7663-firmware-ap

-> Add these extra packages if required:
 _kmod-fs-ext4 e2fsprogs block-mount kmod-usb-storage luci-app-travelmate tune2fs badblocks htop_

**Please Note** To free urgently needed Flash space, I removed some packages that I have never seen to be required for a travel router in any hotel I was so far. Feel free to re-add them if you find enough space for it! The italic marked packages could be adapted according to your needs and require modifications of the following script.

**StepC:**
Load the first start boot script and adapt it as follows right before this last line:
>>echo "All done!"<<, insert the following code (Notes below):

##### >>Start Code Block
### # stop unstable watchdog
ubus call system watchdog "{ 'magicclose':true }"
ubus call system watchdog "{ 'stop':true }"
 
### # Decrease wasted memory
FREEMEMRV=$((`free | sed -e'/Mem/!d' -e's/^Mem: *\([1-9][0-9]*\) .*/\1/'`/28000*1024))
sysctl -w vm.swappiness=1                 #Moderates Swappen damit adguardghom stabil laeuft!
sysctl -w vm.vfs_cache_pressure=1         #Wert von max. 200 stresst die SD carte mit Swap uebermaessig!
sysctl -w vm.min_free_kbytes=$FREEMEMRV   #256M->8M Minimum, bei 64M->2M Minimale Speicherreserve
 
### # Patch nice level of init processes for improved stability
sed -i '32i \\t\tprocd_set_param nice \"-3\"' /etc/init.d/cron
sed -i '22i \\t\tprocd_set_param nice \"-5\"' /etc/init.d/dbus
sed -i '1198i \\t\tprocd_set_param nice \"13\"' /etc/init.d/dnsmasq
sed -i '166i \\t\tprocd_set_param nice \"2\"' /etc/init.d/dropbear
sed -i '39i \\t\tprocd_set_param nice \"16\"' /etc/init.d/log
sed -i '20i \\t\tprocd_set_param nice \"3\"' /etc/init.d/network
sed -i '15i \\t\tprocd_set_param nice \"-5\"' /etc/init.d/rpcd
sed -i '57i \\t\tprocd_set_param nice \"3\"' /etc/init.d/sysntpd
sed -i '123i \\t\tprocd_set_param nice \"10\"' /etc/init.d/uhttpd
sed -i '12i \\t\tprocd_set_param nice \"18\"' /etc/init.d/urngd
sed -i '15i \\t\tprocd_set_param nice \"10\"' /etc/init.d/wpad
sed -i '33i \\t\tprocd_set_param nice \"10\"' /etc/init.d/wpad
 
uci set travelmate.global.trm_nice="15"
##### << End Coode Block

**Please Note:** This device has low performance, low memory and low flash size!
Thus it will run repeatedly into watchdog kills with the standar v3 release configuration and even when you only try to update the firmware.
One experienced reason for this seems to be, that the nice priority of openwrt's system deamons rpc and ubus deamons are to weak. Thus the watchdog refresh is prevented from doing its job by even a simple user process that kicks it out of priority. Additionally this  hard watchdog reboot kills your sd storage removing its power during reboot if you try to extend you storag using Openwrt's extroot support.
Additionally in my experience it is not a good idea to let memory eating processes like dnscrypt or adguardhome have nice levels at below +15 where otherwise they could this gread small system completely unstable. 

**Step D:**
Build your own new snapshot (Sysupgrade) image from 100% released sources

**Step E:**
Use your Openwrt flash update mechanism to update your snapshot image.
**Please Note:**
- Caused by above noted watchdog problem you mayby have to skip a first error message, try again or load the image by hand according to Openwrt's commandline update procedure. Updates from this point (with above disabled watchdog) do not show up again.
- If you need the watchdog, it seems to be stable if you increase the watchdog timeout to its maximum as documented in the Openwrt Wiki

Hope this may help someone, enjoy!

**Comment by Edmondena** [comment]
After disabling the watchdog in the WR902ACv4 as documented above, some one may want to test and do experiments with it?

Here you maybe find a good starting point for it:
the following script goes into "/etc/rc.local" and is started at every boot and re-enabling the above disabled watchdog behavior.
**Please Note:**
- The "normal" behavior of the WR902ACv3 firmware freezes the device, so take care and don't wonder if this happens to you?
### #rc.local code starts here 
#*********************************************************************************************************
#*      Watchdog Timer
#*********************************************************************************************************
WNICE=-5
WDGTO=60                        # Max. possible Delay Timeout before device hangup
WDDCY=9                         # Vierfache Sicherheit des Triggers

# increase watchdog robustness by higher frequency and lnger reset timeout
watchlong(){
        ubus call system watchdog "{ 'timeout':$WDGTO }"
        ubus call system watchdog "{ 'frequency':$WDDCY }"
}

watchoff(){
        ubus call system watchdog "{ 'magicclose':true }"
        ubus call system watchdog "{ 'stop':true }"
}

watchself(){
        nice -n -3
        while true; do sleep $WDDCY && echo 1>/dev/watchdog; done
}

watchlong       #per default the same safest common setting 60s/9s for all devices
#watchoff       #disable device specific for WR902ACv4 devices only?
#watchself &    #Causes hardware freeze instead of reboot on WR902ACv4 only?
### #rc.local code end

**Pull request closed without merging**
