### PR TITLE
toolchain: gcc: add support for GCC 14

### PR DESCRIPTION
**Pull request by rsalvaterra**
Deleted (upstreamed):
- 020-Include-safe-ctype.h-after-C-standard-headers-to-avo.patch [1]
- 021-libcc1-fix-vector-include.patch [2]

All other patches automatically rebased.

[1] https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=9970b576b7e4ae337af1268395ff221348c4b34a
[2] https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=5213047b1d50af63dfabb5e5649821a6cb157e33

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by rsalvaterra** [comment]
Marked as WIP, as I still have to build it.

**Review by hauke — APPROVED** [review]

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
```
> make package/mbedtls/compile V=s
make[2]: Entering directory '/home/mangix/devstuff/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/mangix/devstuff/openwrt/scripts/config'
make[1]: Entering directory '/home/mangix/devstuff/openwrt'
+ mkdir -p /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_generic_musl
+ cd /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_generic_musl
+ mkdir -p bin lib stamp usr/include usr/lib
mkdir -p /home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/stamp
touch /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_generic_musl/.prepared
make[2]: Entering directory '/home/mangix/devstuff/openwrt/package/libs/toolchain'
Makefile:748: WARNING: skipping libgomp -- package has no install section
echo "libc" >> /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libatomic" >> /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libstdcpp" >> /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
echo "librt" >> /home/mangix/devstuff/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/toolchain.default.install
make[2]: Leaving directory '/home/mangix/devstuff/openwrt/package/libs/toolchain'
time: package/libs/toolchain/compile#0.13#0.10#0.22
make[2]: Entering directory '/home/mangix/devstuff/openwrt/package/libs/mbedtls'
rm -f /home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0/.built
touch /home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0/.built_check
MAKEFLAGS="" /home/mangix/devstuff/openwrt/staging_dir/host/bin/ninja  -j1 -C /home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0 
ninja: Entering directory `/home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0'
[1/277] Building C object library/CMakeFiles/mbedcrypto_static.dir/ctr_drbg.c.o
FAILED: library/CMakeFiles/mbedcrypto_static.dir/ctr_drbg.c.o 
/home/mangix/devstuff/openwrt/staging_dir/host/bin/ccache /home/mangix/devstuff/openwrt/staging_dir/toolchain-aarch64_generic_gcc-14.1.0_musl/bin/aarch64-openwrt-linux-musl-gcc  -I/home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0/include -I/home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0/library -I/home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0/3rdparty/everest/include -I/home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0/3rdparty/p256-m -I/home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0/3rdparty/p256-m/p256-m -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0=mbedtls-3.6.0 -ffunction-sections -fdata-sections -Wformat -Werror=format-security -DPIC -fPIC -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro -Wall -Wextra -Wwrite-strings -Wformat=2 -Wno-format-nonliteral -Wvla -Wlogical-op -Wshadow -Wformat-signedness -Wformat-overflow=2 -Wformat-truncation -Werror -Wmissing-declarations -Wmissing-prototypes -O2 -std=c99 -fPIC -MD -MT library/CMakeFiles/mbedcrypto_static.dir/ctr_drbg.c.o -MF library/CMakeFiles/mbedcrypto_static.dir/ctr_drbg.c.o.d -o library/CMakeFiles/mbedcrypto_static.dir/ctr_drbg.c.o -c /home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0/library/ctr_drbg.c
In file included from library/ctr_drbg.c:13:
In function 'mbedtls_xor',
    inlined from 'ctr_drbg_update_internal' at library/ctr_drbg.c:372:5:
library/common.h:235:17: error: array subscript 48 is outside array bounds of 'unsigned char[48]' [-Werror=array-bounds=]
  235 |         r[i] = a[i] ^ b[i];
      |                ~^~~
library/ctr_drbg.c: In function 'ctr_drbg_update_internal':
library/ctr_drbg.c:335:19: note: at offset 48 into object 'tmp' of size 48
  335 |     unsigned char tmp[MBEDTLS_CTR_DRBG_SEEDLEN];
      |                   ^~~
In function 'mbedtls_xor',
    inlined from 'ctr_drbg_update_internal' at library/ctr_drbg.c:372:5:
library/common.h:235:24: error: array subscript 48 is outside array bounds of 'const unsigned char[48]' [-Werror=array-bounds=]
  235 |         r[i] = a[i] ^ b[i];
      |                       ~^~~
library/ctr_drbg.c: In function 'ctr_drbg_update_internal':
library/ctr_drbg.c:333:57: note: at offset 48 into object 'data' of size [0, 48]
  333 |                                     const unsigned char data[MBEDTLS_CTR_DRBG_SEEDLEN])
      |                                     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'mbedtls_xor',
    inlined from 'ctr_drbg_update_internal' at library/ctr_drbg.c:372:5:
library/common.h:235:14: error: array subscript 48 is outside array bounds of 'unsigned char[48]' [-Werror=array-bounds=]
  235 |         r[i] = a[i] ^ b[i];
      |         ~~~~~^~~~~~~~~~~~~
library/ctr_drbg.c: In function 'ctr_drbg_update_internal':
library/ctr_drbg.c:335:19: note: at offset 48 into object 'tmp' of size 48
  335 |     unsigned char tmp[MBEDTLS_CTR_DRBG_SEEDLEN];
      |                   ^~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make[2]: *** [Makefile:182: /home/mangix/devstuff/openwrt/build_dir/target-aarch64_generic_musl/mbedtls-3.6.0/.built] Error 1
make[2]: Leaving directory '/home/mangix/devstuff/openwrt/package/libs/mbedtls'
time: package/libs/mbedtls/compile#0.46#0.14#0.58
    ERROR: package/libs/mbedtls failed to build.
```

**Comment by trippleflux** [comment]
gcc 14 failed to compiling net/frr : 
```
checking for gelf_getnote in -lelf... yes
checking python interpreter python3... /home/user/works/openwrt/staging_dir/hostpkg/bin/python3 (python3)
checking whether /home/user/works/openwrt/staging_dir/hostpkg/bin/python3.11-config is available... yes
checking whether /home/user/works/openwrt/staging_dir/hostpkg/bin/python3.11-config provides a working build environment... no
checking whether pkg-config python-3.11 is available... yes
checking whether pkg-config python-3.11 provides a working build environment... no
checking whether /home/user/works/openwrt/staging_dir/hostpkg/bin/python3.11-config is available... yes
checking whether /home/user/works/openwrt/staging_dir/hostpkg/bin/python3.11-config provides a working build environment... no
checking whether pkg-config python-3.11 is available... yes
checking whether pkg-config python-3.11 provides a working build environment... no
checking python interpreter python3.10... not working
checking python interpreter python3.9... not working
checking python interpreter python3.8... not working
checking python interpreter python3.7... not working
checking python interpreter python3.6... not working
checking python interpreter python3.5... not working
checking python interpreter python3.4... not working
checking python interpreter python3.3... not working
checking python interpreter python3.2... not working
checking python interpreter python... /home/user/works/openwrt/staging_dir/host/bin/python (python3)
checking whether /usr/bin/python3.11-config is available... no
checking whether pkg-config python-3.11 is available... yes
checking whether pkg-config python-3.11 provides a working build environment... no
checking whether /usr/bin/python3.11-config is available... no
checking whether pkg-config python-3.11 is available... yes
checking whether pkg-config python-3.11 provides a working build environment... no
checking python interpreter python2... not working
checking python interpreter python2.7... not working
configure: error: no working python version found
make[2]: *** [Makefile:227: /home/user/works/openwrt/build_dir/hostpkg/frr-10.1/.configured] Error 1
make[2]: Leaving directory '/home/user/works/openwrt/feeds/packages/net/frr'
time: package/feeds/packages/frr/host-compile#29.99#9.95#40.26
    ERROR: package/feeds/packages/frr [host] failed to build.
make[1]: *** [package/Makefile:127: package/feeds/packages/frr/host/compile] Error 1
make[1]: Leaving directory '/home/user/works/openwrt'
make: *** [/home/user/works/openwrt/include/toplevel.mk:233: package/frr/compile] Error 2
```

excerpt from frr config.log : 
```
configure:26004: ccache /home/user/works/openwrt/staging_dir/host/bin/gcc -o conftest -O2 -I/home/user/works/openwrt/staging_dir/host/include -I/home/user/works/openwrt/staging_dir/hostpkg/include -I/home/user/works/openwrt/staging_dir/target-x86_64_glibc_custom/host/include -I/home/user/works/openwrt/staging_dir/hostpkg/include/python3.11 -I/home/user/works/openwrt/staging_dir/host/include -I/home/user/works/openwrt/staging_dir/hostpkg/include -I/home/user/works/openwrt/staging_dir/target-x86_64_glibc_custom/host/include -I/home/user/works/openwrt/staging_dir/host/include/libelf -L/home/user/works/openwrt/staging_dir/host/lib -L/home/user/works/openwrt/staging_dir/hostpkg/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_glibc_custom/host/lib -g conftest.c -lpthread  -L/home/user/works/openwrt/staging_dir/hostpkg/lib -lpython3.11 -lz >&5
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(complexobject.o): in function `_Py_c_abs':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/complexobject.c:208:(.text+0xa01): undefined reference to `hypot'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(complexobject.o): in function `complex_pow':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/complexobject.c:522:(.text+0xb90): undefined reference to `floor'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(complexobject.o): in function `_Py_c_pow':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/complexobject.c:144:(.text+0xe11): undefined reference to `hypot'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/complexobject.c:145:(.text+0xe20): undefined reference to `pow'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/complexobject.c:146:(.text+0xe3e): undefined reference to `atan2'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/complexobject.c:148:(.text+0xe6c): undefined reference to `sincos'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/complexobject.c:149:(.text+0xea1): undefined reference to `exp'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/complexobject.c:150:(.text+0xeb9): undefined reference to `log'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(floatobject.o): in function `float_rem':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:655:(.text+0x7d8): undefined reference to `fmod'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(floatobject.o): in function `_float_div_mod':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:675:(.text+0x978): undefined reference to `fmod'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:698:(.text+0x9d8): undefined reference to `floor'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(floatobject.o): in function `float___ceil___impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:949:(.text+0xa17): undefined reference to `ceil'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(floatobject.o): in function `float___floor___impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:935:(.text+0xa37): undefined reference to `floor'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(floatobject.o): in function `float___round___impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:1090:(.text.unlikely+0x893): undefined reference to `round'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(floatobject.o): in function `float_is_integer_impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:901:(.text.unlikely+0xe86): undefined reference to `floor'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(floatobject.o): in function `float_pow':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:847:(.text.hot+0xddb): undefined reference to `pow'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:847:(.text.hot+0xf61): undefined reference to `pow'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:798:(.text.hot+0x110c): undefined reference to `fmod'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:824:(.text.hot+0x1175): undefined reference to `fmod'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:847:(.text.hot+0x11c5): undefined reference to `pow'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:788:(.text.hot+0x126b): undefined reference to `fmod'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(floatobject.o): in function `float___round___impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:1090:(.text.hot+0x14b6): undefined reference to `round'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/floatobject.c:1093:(.text.hot+0x16e0): undefined reference to `round'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(longobject.o): in function `PyLong_FromString':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Objects/longobject.c:2441:(.text.hot+0x7444): undefined reference to `log'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(pytime.o): in function `pytime_round':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Python/pytime.c:271:(.text+0x3d3): undefined reference to `floor'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(pytime.o): in function `pytime_round_half_even':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Python/pytime.c:248:(.text+0x3f9): undefined reference to `round'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(pytime.o): in function `pytime_round':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Python/pytime.c:275:(.text+0x442): undefined reference to `ceil'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(pytime.o): in function `pytime_round_half_even':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Python/pytime.c:251:(.text+0x45b): undefined reference to `round'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(pytime.o): in function `pytime_round':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Python/pytime.c:268:(.text.unlikely+0x219): undefined reference to `ceil'
/usr/bin/ld: /home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/Python/pytime.c:275:(.text.unlikely+0x229): undefined reference to `floor'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(_threadmodule.o): in function `thread_module_exec':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/./Modules/_threadmodule.c:1684:(.text+0x140): undefined reference to `floor'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(_localemodule.o): in function `_locale_bindtextdomain_impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/./Modules/_localemodule.c:736:(.text.unlikely+0x767): undefined reference to `g_libintl_bindtextdomain'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(_localemodule.o): in function `_locale_bind_textdomain_codeset_impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/./Modules/_localemodule.c:764:(.text.unlikely+0x8b5): undefined reference to `g_libintl_bind_textdomain_codeset'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(_localemodule.o): in function `_locale_textdomain_impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/./Modules/_localemodule.c:697:(.text.unlikely+0x95b): undefined reference to `g_libintl_textdomain'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(_localemodule.o): in function `_locale_dcgettext_impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/./Modules/_localemodule.c:681:(.text.unlikely+0xaa9): undefined reference to `g_libintl_dcgettext'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(_localemodule.o): in function `_locale_dgettext_impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/./Modules/_localemodule.c:662:(.text.unlikely+0xbd6): undefined reference to `g_libintl_dgettext'
/usr/bin/ld: /home/user/works/openwrt/staging_dir/hostpkg/lib/libpython3.11.a(_localemodule.o): in function `_locale_gettext_impl':
/home/user/works/openwrt/build_dir/hostpkg/Python-3.11.7/./Modules/_localemodule.c:643:(.text.unlikely+0xc5d): undefined reference to `g_libintl_gettext'
collect2: error: ld returned 1 exit status
```

**Comment by neheb** [comment]
@trippleflux can you make a PR for linux-atm?

**Comment by trippleflux** [comment]
@neheb 
I haven't got the experiences with git & github, i will try but i welcome for anybody to take first on my finding (patch).

**Comment by rsalvaterra** [comment]
Fallout from updating to a newer GCC major version is undesirable, but unavoidable. In an ideal world, all packages would have already been fixed to compile without issues. In reality, it's unreasonable to expect a developer to go all over the tree, fixing each and every package that fails to build, for one reson or another (I personally don't have the time nor the storage space to do so, I can only vouch for my personal configs).
Fixing broken packages is, and always will be, a best effort task. Whoever wants to play with GCC 14 knows the drill: if it breaks, you get to keep the pieces. That's why GCC 13.x is, and will keep being the default for the forseeable future. :wink:

**Comment by trippleflux** [comment]
@rsalvaterra 

Yup 3 days ago, I have finally finished my OpenWrt compilation (714 packages for x86_64) using gcc 14, experiencing some quirks on installed image but working fine so far for not heavy usage. Great job on this PR !.

**Comment by hauke** [comment]
I think this looks fine and you can merge it if you want. We can fix the broken packages afterwards.

**Comment by robimarko** [comment]
LGTM, so feel free to merge

**Comment by rsalvaterra** [comment]
Thanks for the feedback, everyone. I'll merge with a note stating that broken packages will be fixed as they're found.

**Comment by rsalvaterra** [comment]
Merged, thanks once again!

**Pull request closed without merging**
