### PR TITLE
ipq806x: Initial TP-Link and ASUS OnHub support

### PR DESCRIPTION
**Pull request by Ansuel**
Series submitted on patchwork and accepted. Opening a pr on github to have this tracked also here and to give it a final ci test.

### CODE REVIEW

**Comment by neheb** [comment]
this has a sound device? weird,

**Comment by Ansuel** [comment]
Yep the buzze to warn that you are in dev mode AHAHAHHAHA
Fix a problem with a bazoka

**Comment by neheb** [comment]
> 

that's it? LOL

**Comment by Ansuel** [comment]
Yes it just beep if you are in development mode... It's really just for that... Wonder if they use it also for other special feature like pair with sound or other strange stuff but No idea...

**Comment by neheb** [comment]
how does it show up under Linux? I'm guessing you can't use it with mpd...

**Comment by computersforpeace** [comment]
I recall there being some parts of initial setup that used the speaker, to alert you of certain phases, and even to identify itself (see https://youtube.com/watch?v=CX0ZplyQqvE&feature=shares&t=131). But it goes silent after that. Yeah, a real waste of hardware 😉 But hey, it has an unused Zigbee radio and even a Bluetooth controller!

The speaker supports standard Linux audio. I had it playing through my music library already, just as a test. It's not the best speaker I've ever heard, but it works...

**Comment by computersforpeace** [comment]
```
# cat /proc/asound/cards 
 0 [ipq806xstorm   ]: ipq806x-storm - ipq806x-storm
                      ipq806x-storm
```

**Comment by neheb** [comment]
ha reminds me of my old android phone with broken wifi but working bluetooth. I never looked into getting it working with OpenWrt.

**Pull request merged**
