### PR TITLE
sunxi: Enable SD block devices

### PR DESCRIPTION
**Pull request by diizzyy**
USB storage support is however SCSI Disk block device support isn't
meaning that connected devices wont enumerate. 
Enable CONFIG_BLK_DEV_SD by default to fix it.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile and runtime tested on: sunxi, Orange Pi PC, OpenWrt Master

**Comment by diizzyy** [comment]
@hauke

**Comment by diizzyy** [comment]
Same fix as for mvebu
https://github.com/openwrt/openwrt/commit/22ac4bd555218d292de576fb574c3b88b63097f8

**Comment by diizzyy** [comment]
@blogic 
Can you have a look?

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
