### PR TITLE
[RFT] qca8k: add support for multiple additional experimental feature

### PR DESCRIPTION
**Pull request by Ansuel**
ALERT
--
It seems kernel 5.10 lacks any support for lag. This was later added to kernel 5.13+ so RIP. We will have to wait for 5.16.
I'm keeping the patch here just to track all the difference and version for anyone that wants to test these new feature.

The main idea is to **resurrect bloogic** patch and add all these missing feature and **the golden patch of hnat feature** :D 

THIS IS ONLY COMPILE TESTED.
--
I would REALLY appreciate anyone that can put some time testing fast aging and the mirror mode feature. They were present in the original driver and it can be useful for someone. Fast aging should be included to better handle bridge registration and change.

**Also this depends on the qca8k backport pr to correctly work. #4528**

Feature to implement:
---

- [x] aging setting
- [x] fast age
- [x] mirror port
- [x] multicast db (TO BE REWORKED... currently doesn't remove rule)
- [x] lag
- [x] alert DSA for global mtu
- [ ] hnat 

3 main feature here are actually NOT TESTED and also NO IDEA IF THEY WORK.

- Mirror port should be work but again NOT TESTED. But the implementation is not that strange.
- MDB function. From Documentation we should use ARL table but no idea if it does actually work.
- lag support is a big LOL. In Documentation it's defined as Trunk. The implementation looks to be correct but who know if it does actually work. i don't have a device to test it so i need to wait some good guy to test it.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by e9hack** [comment]
#include <linux/bitfield.h> is missing.

**Comment by Ansuel** [comment]
Result of writing patch at 4am...

Il Sab 9 Ott 2021, 08:18 e9hack ***@***.***> ha scritto:

**Comment by Ansuel** [comment]
This changed to Ansuel's super secret (not that secret) PR where he adds missing feature to qca8k looking at the Documentation and trying to make that work without any guide from it.
Expect no connection LOL.

**Comment by Ansuel** [comment]
@robimarko also don't know if you have any device to test lag

**Comment by Ansuel** [comment]
Superseded by #4858

**Comment by tiagogaspar8** [comment]
Hi @Ansuel , will hwnat/hw offload be added as feature in #4858 or in the future in another pull request since this one is now closed?

Thank you for your work.

**Comment by Ansuel** [comment]
@tiagogaspar8 I currently have stopped work on hw offload. I'm trying to fix multicpu first. Yes offload will come in another separate pr. I have some changes ready but I still have to test them. qca8337 doesn't support them and i have to use a ipq40xx SoC

**Comment by tiagogaspar8** [comment]
@Ansuel I see, if you need help in testing I have a archer c7 v4 that has an qca8337n so if you need help in testing let me know.

Also, now that you mention the multi cpu patch, I see that your design makes it so that you can choose to which port each interface is bound to, yet that can make things a bit unoptimized, so I wanted to ask you if there is a way to create a lag interface with the round-robin algorithm with both eth0 and eth1 as it's team members and make the switch diver use the bond0 interface instead of eth0 or eth1, since the switch has the ASIC to support the lag interfaces it should remove the need to use the multi cpu patch because it makes it so that the CPU port has double the bandwidth.

If that doesn't make sense sorry, I'm just giving ideas to improve the situation 😁

**Comment by Ansuel** [comment]
I never tested bonding with the CPU port. No idea if it can work. robi said that it wouldn't work it would be worth to test.

**Comment by tiagogaspar8** [comment]
I believe it's a great feature!
I know you're more of a ipqxxxx guy but I have a Linksys wrt3200acm so if you'd like for me to test it I can give it a go!

**Pull request closed without merging**
