### PR TITLE
[23.05] cherry-pick commits from main branch

### PR DESCRIPTION
**Pull request by dangowrt**
Cherry-pick a bunch of by now tested commits from main branch to openwrt-23.05

### CODE REVIEW

**Comment by 0xFelix** [comment]
Can you include 5ae3b195a17d3c8a7b25e826928cd73117fbbe57 too? I'm seeing this issue on 23.05-rc3.,

**Comment by dangowrt** [comment]
@nbd168 will backport major changes how we configure hostapd/wpa_supplicant and replace a lots of Shell code with much more clean ucode implementation. I suppose he is going to take care of that and we won't need to backport https://github.com/openwrt/openwrt/commit/5ae3b195a17d3c8a7b25e826928cd73117fbbe57 individually before that.

**Comment by dangowrt** [comment]
@Ansuel are you ok with picking https://github.com/openwrt/openwrt/pull/13392/commits/cbc5da88fed7d58d2cdea4399515cd86e028d642 or think it's a good idea? I do it mostly so that patches again apply cleanly and we won't have to do a `make target/linux/refresh` on the openwrt-23.05 branch which will complicate future picks from the main branch.

**Comment by Ansuel** [comment]
Ok for me, it's a pretty safe change. (Only pppoe is affected but also
there, we have a fix)

I would also backport the phy led part if we really want

Il Lun 4 Set 2023, 22:05 Daniel Golle ***@***.***> ha scritto:

**Pull request merged**
