### PR TITLE
Update mt7621 to support xiaomi,mir-3g board name

### PR DESCRIPTION
**Pull request by idoo**
Some board name has `xiaomi,mir-3g` for xiaomi router 3G

### CODE REVIEW

**Comment by adschm** [comment]
> Some board name has `xiaomi,mir-3g` for xiaomi router 3G

Which?

**Comment by idoo** [comment]
for example in one of our routers:
```
{
        "model": {
                "id": "xiaomi,mir-3g",
                "name": "Xiaomi Mi Router 3G"
        },
```

**Comment by adschm** [comment]
Where does this snippet come from? Is it possible that you use some OpenWrt-derived firmware and not OpenWrt itself?

**Comment by idoo** [comment]
it is /etc/board.json

hmm, could be, however, board_detect returns the same result

**Comment by adschm** [comment]
Okay, and which version of OpenWrt are you running? And where did you get it from?

**Comment by idoo** [comment]
```
cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.2'
DISTRIB_REVISION='r10947-65030d81f3'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 19.07.2 r10947-65030d81f3'
DISTRIB_TAINTS='no-all'
```
it was already on this device — trying to update it to the latest version

**Comment by adschm** [comment]
Just checked it and don't see that string used anywhere. 19.07.2 used "xiaomi,mir3g"
No idea where you got this other one from.

**Comment by idoo** [comment]
hm, weird, looks that you're right
do you know, how I could change it on the device to be able to update openwrt?

**Comment by adschm** [comment]
Typically, if you are really sure it's the right image for the correct devices, you would just update with _force_ (i.e. sysupgrade -F ... in command line).

**Pull request closed without merging**
