### PR TITLE
kirkwood: switch to Kernel 5.10

### PR DESCRIPTION
**Pull request by aparcar**
CI build with artifacts: https://github.com/aparcar/openwrt/actions/runs/1289785931

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by CHKDSK88** [comment]
Please consider merge https://github.com/openwrt/openwrt/pull/4292 first.

**Comment by mans0n** [comment]
#4292 has been merged now, so we are good to go?

**Comment by CHKDSK88** [comment]
`Acked-by: Pawel Dembicki <paweldembicki@gmail.com>`

**Comment by adschm** [comment]
I will take care, but it might take until next weekend.

**Pull request closed without merging**
