### PR TITLE
kernel: 6.1: Add missing config option DEVTMPFS_SAFE

### PR DESCRIPTION
**Pull request by ghost**
Fixes build error when enabling CONFIG_KERNEL_DEVTMPFS in OpenWrt menuconfig.

### CODE REVIEW

**Comment by M95D** [comment]
I don't understand this Test Formalities error:
Commit subject line MUST start with '<area>: ' (Kernel 6.1: Add missing config option DEVTMPFS_SAFE)
Is "Kernel 6.1" not allowed for <area>?

**Comment by xabolcs** [comment]
The relevant check is:
```
grep -q -e '^[0-9A-Za-z,+/_\.-]\+: ' -e '^Revert '
```

No spaces are allowed before `:`. See file history to get a hint.

**Comment by M95D** [comment]
Closing, because it's already added here: https://github.com/openwrt/openwrt/commit/e26e088203303d79eb87056f8ca74b1a5f585206

**Comment by M95D** [comment]
> Closing, because it's already added here: [e26e088](https://github.com/openwrt/openwrt/commit/e26e088203303d79eb87056f8ca74b1a5f585206)

Reopening, because the commit above only adds it to x86, ignoring the rest of 6.1 affected kernels.

**Pull request merged**
