### PR TITLE
realtek: drop target

### PR DESCRIPTION
**Pull request by robimarko**
Sadly, the realtek target is the only target still using kernel 5.15,
and the next OpenWrt release will be using kernel 6.6.

Considering that the efforts to move realtek to kernel 6.1 have been
stalled for over a year [1] and the most active (Only?) has given up
we have no other choice that to drop the target.

In case there is new development activity and it is updated to 6.6
it can be readded.

[1] https://github.com/openwrt/openwrt/pull/12726

### CODE REVIEW

**Comment by robimarko** [comment]
I hope this can draw some developers that care about the target, otherwise we really have no choice.

@oliv3r @svanheule

**Comment by neheb** [comment]
those are...a lot of devices.

**Comment by oliv3r** [comment]
They are, but to be fair, this code shouldn't have been merged in the first place. It's of extremely poor quality.

I once offered to put the code into a separate module, and after days, couldn't get it to work (dependencies not starting in the correct order really). For me, that's still the best way forward, put all the networking code out-of-tree in a separate module.

But even then, it'll require a lot of effort to clean up; and even that which is merged upstream is off questionable quality and needs to be refactored.

So if anybody can help (with a little bit more then just testing things), that'd be needed at the least.

**Comment by Borromini** [comment]
Just going by the issues we are bumping into with 6.1 - which laid bare the amount of 'custom code' (for lack of a better word from a non-programmer) and magic numbers the present realtek codebase relies on, I don't think 6.6 is a walk in the park. It might be once we fixed what we are seeing on 6.1, but so fare noone has been able to. So...

**Comment by svanheule** [comment]
I could try to have a look tomorrow at getting the target to compile with 6.6, so we could mark it as source-only instead of dropping it entirely. Although I wouldn't mind a clean-slate approach either...

**Comment by bmork** [comment]
> it'll require a lot of effort to clean up;

No one disagrees about that. But to be fair: This target has been and is very valuable, and it would never had happened if strict quality code was required.  Personally I am very happy about the pragmatic approach taken and am hoping we can keep doing that for yet another release.  Proper clean code is definitely not an option if we want to make the deadline this time either.  Let's be realistic and just try to make it .... maybe not fly, but at least not crash and burn.

I'm not sure if I confused more than I helped with my 6.1 testing.  The code isn't exactly perfect in 5.15 either, as you point out.  Maybe I just pointed out existing issues.  FWIW, the end result was usable for me on 6.1.  No real show stoppers. Basic switch functionality with tagged and untagged vlans works fine. And that should be the priority. 

Let's just see if we can achieve something similar on 6.6.  IMHO anything with functional switching is better than dropping the target.  We can live with some known cpu port/ethernet driver issues if necessary.

(as for the dsa/ethernet rewrite: that's probably better done in mainline, where shortcuts won't be allowed. But it will be a hell of a lot of work, and I don't see the required resources being available. Unfortunately.  I'll be very happy if proven wrong)

**Comment by robimarko** [comment]
@bmork With the current code level of the target, it's only going to become more and more difficult to keep it afloat, hence why it's on 5.15, and the effort to get it to 6.1 has been stalled for over a year.

It has a lot of users, but it's essentially down to one or two developers and to me, this is another reminder of why too much downstream code is a rather big issue.

If somebody can get it to work on 6.6, that is great and keeps it around for one more release

**Comment by bmork** [comment]
> With the current code level of the target, it's only going to become more and more difficult to keep it afloat,

Yes, I know.  And many of us warned about that problem even before the code was initially accepted. But without the abilities to follow up with cleaner code matching the efforts Birger put into this project, it ended up looking more like a flood of negativity. And look where that brought us.

(not forgetting all the great work by @svanheule and others moving most of the non-networking code into mainline - it does make this much easier than it could have been)

So I am now trying very hard to learn from that and look at our possibilites here. I believe they are: 

1. repeat for one more cycle, or
2. drop the target

Personally I am in favour of anything which avoids option 2, because I don't think this target will ever come back if we do that.

**Comment by plappermaul** [comment]
Hi,

im willing to add support here. For this to happen, lengthy patch discussions with endless nitpicks and tons of iterations are a NOGO for me. To check if this will be possible this time I added support for the new device LGS310C via https://github.com/openwrt/openwrt/pull/16068

Lets see if teamwork is possible this time...

**Comment by svanheule** [comment]
Currently stopped at refreshing 800-net-mdio-support-hardware-assisted-indirect-access.patch for 6.6, will continue tomorrow.

**Comment by bmork** [comment]
> Currently stopped at refreshing 800-net-mdio-support-hardware-assisted-indirect-access.patch

Yes, that one will need love from someone understanding all the smi/mdio stuff.

Another major issue is the dsa driver. phylink_validate and phylink_mac_link_state is gone in v6.6.  So that code has to be rewritten.  Looks like phylink_validate can be mapped to phylink_get_caps quite easily (AI work maybe?).  Don't know about phylink_mac_link_state

**Comment by namiltd** [comment]
My suggestion is not to delete it but:
- Bring it to a correct compilation state
- set temporarily: FEATURES:=source-only

**Comment by svanheule** [comment]
> > Currently stopped at refreshing 800-net-mdio-support-hardware-assisted-indirect-access.patch
> 
> Yes, that one will need love from someone understanding all the smi/mdio stuff.

I started rebasing the patch, but there's just so much code modifying the kernel...

@howels has done some work here though. Mind if I take the changes from your tree? I would gladly add a line (Signed-off-by if you like, else a Suggested-by) to attribute your work.

**Comment by howels** [comment]
> > > Currently stopped at refreshing 800-net-mdio-support-hardware-assisted-indirect-access.patch
> > 
> > Yes, that one will need love from someone understanding all the smi/mdio stuff.
> 
> I started rebasing the patch, but there's just so much code modifying the kernel...
> 
> @howels has done some work here though. Mind if I take the changes from your tree? I would gladly add a line (Signed-off-by if you like, else a Suggested-by) to attribute your work.

Unfortunately my tree compiles but hangs during boot looks like it's happening when bringing up the 2nd core.
Feel free to have a look at https://github.com/howels/openwrt/tree/realtek-6.6-test I hope that something helps. I was fighting to get it compiling for a couple of days then needed to put it aside.

**Comment by namiltd** [comment]
@howels Could you organize your code so that we can create a PR, e.g. by dividing it into such commits?:
- kernel/realtek: Create kernel files for v6.6 (from v6.1)
- kernel/realtek: Restore kernel files for v6.1
- realtek: refresh config-6.6
- realtek: refresh patches
- ...
- ...
- realtek: enable 6.6 testing

**Comment by howels** [comment]
> @howels Could you organize your code so that we can create a PR, e.g. by dividing it into such commits?:
> 
>     * kernel/realtek: Create kernel files for v6.6 (from v6.1)
> 
>     * kernel/realtek: Restore kernel files for v6.1
> 
>     * realtek: refresh config-6.6
> 
>     * realtek: 6.6: refresh patches
> 
>     * ...
> 
>     * ...
> 
>     * realtek: enable 6.6 testing
> 
> 
> Target realtek is the last one that is not ported (or in the process of being) to 6.6.

Pleasantly surprised that it's working as well as it is, I thought I'd messed up after not completing the early stages of boot with RTL839x. I will have to locate an RTL838x device to validate functioning of the work on that uniprocessor platform as I know it's not booting on RTL839x from my testing with the HPE 1920-48G.
So, I'll line up test hardware and try to tidy this tomorrow or worst case over the weekend.

**Comment by bmork** [comment]
Just want to note that @howels v6.6 branch works really well for me on rtl838x (Netgear GS108Tv3) , with a couple of extra patches on top: https://github.com/bmork/openwrt/tree/realtek-6.6-test

The big big problem with my "fixes" is this: https://github.com/bmork/openwrt/commit/f858f8e78963693097256ca7498f46d35217db6a , which I assume breaks rtl839x and rtl93xx. I have no idea how to fix that. Or any device to test the assumption on.  Hoping @howels , @svanheule , @musashino205 or someone else who knows their way around the irq-realtek-rtl.c driver will chime in and restore the VPE/SMP functionality on top of the current mainline driver.

But failing that, we do have a slightly less painful option than disabling the whole target:  We can at least keep rtl838x support.

**Comment by howels** [comment]
> Just want to note that @howels v6.6 branch works really well for me on rtl838x (Netgear GS108Tv3) , with a couple of extra patches on top: https://github.com/bmork/openwrt/tree/realtek-6.6-test
> 
> The big big problem with my "fixes" is this: https://github.com/bmork/openwrt/commit/f858f8e78963693097256ca7498f46d35217db6a , which I assume breaks rtl839x and rtl93xx. I have no idea how to fix that. Or any device to test the assumption on.  Hoping @howels , @svanheule , @musashino205 or someone else who knows their way around the irq-realtek-rtl.c driver will chime in and restore the VPE/SMP functionality on top of the current mainline driver.
> 
> But failing that, we do have a slightly less painful option than disabling the whole target:  We can at least keep rtl838x support.

Glad that you are having success, I'm getting a Netgear GS308T fitted up for serial console currently and hope to do more work in the coming days.
I do think we need to be highly critical when we rework these patches, I threw up that branch after a burst of late night hacking but if we want to maintain realtek going forward the code needs to be clear, with focused and well documented commits. I'm to blame here so I'll try to clean up my work first. During the first pass I noticed that the same few files are patched over and over. With the large updates being made I would prefer to reconcile the patches and avoid overlapping patches for future maintainability.

**Comment by jonasjelonek** [comment]
@bmork I have a Zyxel XGS1250-12 on my desk, which has a RTL9302B SoC. I compiled and tested your tree on my device, primarily to test your assumption and to see how far I come. Without you patches on top of @howels tree I get the same issues that you described and fixed with your patches, i.e. the boot hang with the IRQ patches, and the crash in port_bridge_join.

After that I'm running into another kernel panic. Should I just share my crash log here or should this troubleshooting be continued somewhere else?
I'm happy to help wherever I can with my device :)

**Comment by simonwunderlich** [comment]
We actually want to use the Realtek OpenWRT target for switches in the future, add contribute features to it until the end of the year. The switches are designed to come with OpenWRT pre-installed and to be open and re-flashable. They will be based on RTL93xx, we don't have RTL8xxx switches in our lab.

Now, dropping the Realtek target would be rather bad for this plan. So we would like to help with efforts to keep this target alive. On the short term, we can probably help with testing/fixing on our 93xx switch samples which we already have.

@0xharshal

**Comment by oliv3r** [comment]
Thats great, however the struggle is mostly maintainer and developer capacity. The hole RE angle without docs doesnt help either

**Comment by oliv3r** [comment]
That's interesting. Any sources on this? a quick google didn't help me

**Comment by jwh** [comment]
I can't add much in the way of fixing up the code (I got most of the way to 6.6 but I just didn't understand the platform or the drivers enough to finish) - but I do have a stockpile of Zyxel devices as I'm using them in production so I'd be more than willing to help test/debug, 838x/839x atm, there are a couple of outstanding issues like SFPs on the 839x boards that don't work, so if I can offer any help let me know (on IRC also)

**Comment by bmork** [comment]
> That's interesting. Any sources on this? a quick google didn't help me

Unsure what you're referring to since github has broken threading, like most of these fancy web boards.  But if this was about the rtl9302 mainline support, then that's here:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/arch/mips/boot/dts/realtek/cameo-rtl9302c-2x-rtl8224-2xge.dts?id=74beefb5935a67f9fa60f8103e3f69d42d6a08d7

Do note the comment

> Add in full DSA switch support is still a work in progress.

which indicates that Allied Telesis are working on an unstreamable DSA driver!  That's extremely good news for us,  believe

**Comment by 0xharshal** [comment]
We have couple of unreleased devices, one very similar to rtl9302 with 2xrtl8224 and another with rtl9312 with 4x rtl8224 phys. 
While working with rlt9312 based device, I have made significant changes to rtl931x_* functions with 5.15 kernel, I also managed to get SFPs working. as @simonwunderlich said, I want to contribute to testing and further development on this. 

I see @bmork has a branch with 6.6, I can start testing my patches in this week

**Comment by plappermaul** [comment]
So lets get things rolling... 

I took care of the phy driver and reworked essential parts to be able to drop [800-net-mdio-support-hardware-assisted-indirect-access.patch](https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob_plain;f=target/linux/realtek/patches-5.15/800-net-mdio-support-hardware-assisted-indirect-access.patch;hb=refs/heads/main) This patch is intended to be applied on 5.15 to make migration to 6.6 much easier.

Please check and test https://github.com/openwrt/openwrt/pull/16172 on as many devices as possible and add your confirmations.

Thanks for your help in advance

**Comment by oliv3r** [comment]
hey plapper, you back?

**Comment by Neustradamus** [comment]
Please do not drop Realtek based devices... A lot of exist...

**Comment by oliv3r** [comment]
> * kernel/realtek: Create kernel files for v6.6 (from v6.1)
> * kernel/realtek: Restore kernel files for v6.1

I'd rather suggest not to do this, but use the kernel bump script for this purpose part of the repo :)

**Comment by plappermaul** [comment]
I am offering to collect a good patch series here https://github.com/plappermaul/openwrt/tree/realtek66ff

Until now it contains a running 6.6 platform including mdio rework and VPE. No eth no dsa no phy. See post in forum

**Comment by plappermaul** [comment]
For a brighter future: https://github.com/openwrt/openwrt/pull/16204

**Comment by basmevissen** [comment]
On 19/08/2024 19:06, plappermaul wrote:
> For a brighter future: #16204 
> <https://github.com/openwrt/openwrt/pull/16204>
> 


System application is starting...[    0.000000] Linux version 6.6.43 
***@***.***) (mips-openwrt-linux-musl-gcc (OpenWrt GCC 13.3.0 
r27114-26ad5c3abd) 13.3.0, GNU ld (GNU Binutils) 2.42) #0 Tue Aug 20 
07:08:34 2024
[    0.000000] RTL838X model is 83826800
[    0.000000] SoC Type: RTL8382
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019070 (MIPS 4KEc)
[    0.000000] MIPS: machine is HPE 1920-24G (JG924A)
[    0.000000] earlycon: ns16550a0 at MMIO 0x18002000 (options '38400n8')
[    0.000000] printk: bootconsole [ns16550a0] enabled
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Using appended Device Tree.
[    0.000000] Primary instruction cache 16kB, VIPT, 4-way, linesize 16 
bytes.
[    0.000000] Primary data cache 16kB, 2-way, VIPT, cache aliases, 
linesize 16 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 
0x0000000000000000-0x0000000007ffffff]

Same result as with the other Realtek 6.6 branches I tried. Looks like 
something broke...

Guess this is not a trivial thing to get working.

(still the same HP 24-ports switch)

Bas.

**Comment by howels** [comment]
> On 19/08/2024 19:06, plappermaul wrote: For a brighter future: #16204 <#16204>
> System application is starting...[ 0.000000] Linux version 6.6.43 ***@***.***) (mips-openwrt-linux-musl-gcc (OpenWrt GCC 13.3.0 r27114-26ad5c3abd) 13.3.0, GNU ld (GNU Binutils) 2.42) #0 Tue Aug 20 07:08:34 2024 [ 0.000000] RTL838X model is 83826800 [ 0.000000] SoC Type: RTL8382 [ 0.000000] printk: bootconsole [early0] enabled [ 0.000000] CPU0 revision is: 00019070 (MIPS 4KEc) [ 0.000000] MIPS: machine is HPE 1920-24G (JG924A) [ 0.000000] earlycon: ns16550a0 at MMIO 0x18002000 (options '38400n8') [ 0.000000] printk: bootconsole [ns16550a0] enabled [ 0.000000] Initrd not found or empty - disabling initrd [ 0.000000] Using appended Device Tree. [ 0.000000] Primary instruction cache 16kB, VIPT, 4-way, linesize 16 bytes. [ 0.000000] Primary data cache 16kB, 2-way, VIPT, cache aliases, linesize 16 bytes [ 0.000000] Zone ranges: [ 0.000000] Normal [mem 0x0000000000000000-0x0000000007ffffff] [ 0.000000] Movable zone start for each node [ 0.000000] Early memory node ranges [ 0.000000] node 0: [mem 0x0000000000000000-0x0000000007ffffff] [ 0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff] Same result as with the other Realtek 6.6 branches I tried. Looks like something broke... Guess this is not a trivial thing to get working. (still the same HP 24-ports switch) Bas.

Over on the PR this is discussed and an issue with the fw_getenv function in conjunction with the unusual HP bootloader is suspected.

**Comment by 0xharshal** [comment]
I have a repository with my patches for rtl931x on openwrt/master -> https://github.com/0xharshal/openwrt66ff-rtl931x/tree/master-rtl931x

and a branch that has patches ported on realtek66ff branch, https://github.com/0xharshal/openwrt66ff-rtl931x/tree/realtek66ff-9312

rtl931x twentyeight port switch, boots just fine on kernel 5.15 on master but crashes on kernel 6.6

Note that it is faking rtl8224 support, it does not actually work, once I can get the device to boot with mdio fixes, I can investigate upstream rtl8224 support which was added to backports-6.6

**Comment by plappermaul** [comment]
@robimarko @svanheule @hauke with total silence from the project side about this **realtek drop PR** how should we proceed?

**Comment by namiltd** [comment]
Can be closed, https://github.com/openwrt/openwrt/pull/16204 is merged.

**Comment by robimarko** [comment]
Indeed, great to see it merged

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/openwrt/openwrt/pull/12726
- https://github.com/openwrt/openwrt/pull/16204
- https://github.com/openwrt/openwrt/pull/16391
- https://github.com/openwrt/openwrt/pull/16408

**Comment by plappermaul** [comment]
Just to remember everyone what was initiated 555 days ago. We have come a long way since then.

**Comment by Borromini** [comment]
Thanks for the much needed TLC.

**Pull request closed without merging**
