### PR TITLE
libjson-c: update to 0.16

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Fix:
- 001-dont-build-docs.patch

Remove upstreamed patch:
- 010-clang.patch

### CODE REVIEW

**Comment by BKPepe** [comment]
I am not sure what are you doing is correct. Your commit is referenced to multiple pull requests, which are not relevant. After your commit is going to be merged, then it will be referenced once again.  :-(

I would propose to include [release notes](https://github.com/json-c/json-c/blob/d28ac67dde77566f53a97f22b4ea7cb36afe6582/ChangeLog#L2) in the commit message and that's it.

**Comment by PolynomialDivision** [comment]
> I am not sure what are you doing is correct. Your commit is referenced to multiple pull requests, which are not relevant. After your commit is going to be merged, then it will be referenced once again. :-(

You complain about how I generate the gitlog? I can also do it differently. If you have any suggestion feel free to tell me.

**Comment by BKPepe** [comment]
> You complain about how I generate the gitlog? 

I see that you removed it from the pull request, but the same applies to the commit message. If you extend the commit subject, you will see that there are referenced OpenWrt pull requests in the commit message, which are not relevant to ``libjson-c`` anyhow. Simple putting URL, which leads to the project's homepage's release notes, is, in my case, sufficient.

**Comment by PolynomialDivision** [comment]
> Simple putting URL, which leads to the project's homepage's release notes, is, in my case, sufficient.

I already added the changelog. Is that fine? I like to have more information in the commit message than just a link.

**Comment by BKPepe** [comment]
It is better than the previou, but you could add the reference (URL) for the changelog, but I don't think that it is necessary to have more information in the commit message than link if it is a simple bump. Anyway, LGTM now.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in f3a198697f6015ee47780841f0418d0d27f1c9c4.

**Pull request closed without merging**
