### PR TITLE
qosify-defaults add more default ports

### PR DESCRIPTION
**Pull request by francisuk1989**
qosify-defaults add more default ports

### CODE REVIEW

**Comment by anomeome** [comment]
Maybe SIP TLS 5061 as well

**Comment by francisuk1989** [comment]
> Maybe SIP TLS 5061 as well

Agreed also! :+1:

**Comment by robho** [comment]
Port 5061 for SIP/TLS is over TCP

**Comment by mans0n** [comment]
Hi, your PR has formal issues, please refer to the guidelines.
https://openwrt.org/submitting-patches
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes
Especially, your commit needs a proper commit message and a Signed-off-by tag.

**Comment by mans0n** [comment]
Ping. @francisuk1989

**Pull request closed without merging**
