### PR TITLE
ramips: Add SD Card support for HC5661A.

### PR DESCRIPTION
**Pull request by yujincheng08**
Now HC5661A has a SD Card driver while every network interfaces working well.

Thanks a lot to @gigibox 
Signed-off-by: LoveSy <shana@zju.edu.cn>

### CODE REVIEW

**Comment by yujincheng08** [comment]
@mkresin Sorry for my late reply. Now I add the `ramips:` prefix for my commits and split it to two commits.
I don't have MT7621 devices so I decided to change the condition into `ralink_soc == MT762X_SOC_MT7628AN`

**Comment by neheb** [comment]
does this compile? msdc0_hw.data_pins is not present in the struct.

**Comment by yujincheng08** [comment]
@neheb I format the file and use  void __iomem * instead of volatile u32.
I have no idea how to remove the else condition so I kept it.

**Comment by neheb** [comment]
ACK

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
