### PR TITLE
bcm27xx: update defconfig files

### PR DESCRIPTION
**Pull request by graysky2**
PR refreshes kernel defconfig files for all tree subtargets under `bcm27xx`.  Enabled CONFIG_ALL_KMODS and ran make kernel_menuconfig against `bcm27[08-11]`. Some of the removed symbols are present in `target/linux/generic/config-5.10` while others were added/removed by the make target.

### CODE REVIEW

**Comment by mans0n** [comment]
Could you add "bcm27xx: " prefix to each commit title? (So the title would be like "bcm27xx: bcm2708: ...")

**Comment by graysky2** [comment]
@mans0n - done

**Comment by chunkeey** [comment]
Merged. Thanks!

**Comment by dave14305** [comment]
bcm27xx is broken after this was merged.

**Comment by graysky2** [comment]
@dave14305 - https://github.com/openwrt/openwrt/commit/a478202d74b66c3da17d57442649eb4f131fc7b2#commitcomment-67096592

**Pull request closed without merging**
