### PR TITLE
imx6: Add support for kernel 4.19

### PR DESCRIPTION
**Pull request by ynezz**
This PR adds support for 4.19 kernel to i.MX6 target.

I had to drop `200-disable-msi.patch` as it seems, that it's not possible to compile kernel with it anymore:

```
drivers/pci/controller/dwc/pcie-designware-host.c:71:15: error: variable 'dw_pcie_msi_domain_info' has initializer but incomplete type
 static struct msi_domain_info dw_pcie_msi_domain_info = {
               ^~~~~~~~~~~~~~~ 
```

and if MSI is still causing problems we probably need to disable it with kernel cmdline option `nomsi`. Here's rebased patch `200-disable-msi.patch` which didn't worked for me:

```diff
--- a/drivers/pci/controller/dwc/Kconfig
+++ b/drivers/pci/controller/dwc/Kconfig
@@ -8,7 +8,6 @@ config PCIE_DW
 
 config PCIE_DW_HOST
         bool
-	depends on PCI_MSI_IRQ_DOMAIN
         select PCIE_DW
 
 config PCIE_DW_EP
@@ -91,7 +90,6 @@ config PCI_EXYNOS
 config PCI_IMX6
 	bool "Freescale i.MX6 PCIe controller"
 	depends on SOC_IMX6Q || (ARM && COMPILE_TEST)
-	depends on PCI_MSI_IRQ_DOMAIN
 	select PCIE_DW_HOST
 
 config PCIE_SPEAR13XX
```

I've build tested it with following config:

```
CONFIG_TARGET_imx6=y
CONFIG_TARGET_MULTI_PROFILE=y
CONFIG_TARGET_ALL_PROFILES=y
CONFIG_TARGET_DEVICE_imx6_DEVICE_ventana-large=y
CONFIG_TARGET_DEVICE_imx6_DEVICE_ventana=y
CONFIG_TARGET_DEVICE_imx6_DEVICE_cubox-i=y
CONFIG_TARGET_DEVICE_imx6_DEVICE_apalis=y
CONFIG_TARGET_DEVICE_imx6_DEVICE_wandboard=y
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
```

I've run tested it on Toradex Apalis iMX6 Quad 2GB IT V1.1A (pending PR #1595), I've attached complete [bootlog](https://github.com/openwrt/openwrt/files/2725491/apalis-boot-4.19.log).

So far I've noticed just following error messages related to f2fs with 4.19 which were not present in 4.14 (I'll look into it later as it happens only sometimes after sysupgrade):

```
[  442.672732] F2FS-fs (loop0): Issue discard(4116, 4116, 2) failed, ret: -5
[  442.679539] print_req_error: I/O error, dev loop0, sector 32896
[  442.679555] print_req_error: I/O error, dev loop0, sector 37112
[  442.691454] F2FS-fs (loop0): Issue discard(4638, 4638, 1) failed, ret: -5
[  442.698273] F2FS-fs (loop0): Issue discard(4112, 4112, 1) failed, ret: -5
[  442.705071] F2FS-fs (loop0): Issue discard(4639, 4639, 1) failed, ret: -5
[  503.141304] print_req_error: I/O error, dev loop0, sector 32960
[  503.147283] F2FS-fs (loop0): Issue discard(4120, 4120, 1) failed, ret: -5
```

FYI @nbd168 @Gateworks @xback @lperkov @v-vid

### CODE REVIEW

**Comment by xback** [comment]
Hi,

I already added 4.19 support for this target some time ago in my staging tree.

I'll probably finish it early next week.

**Comment by ynezz** [comment]
@xback Can you please try to build 4.19 kernel with following OpenWrt config?

```
CONFIG_TARGET_imx6=y
CONFIG_TARGET_MULTI_PROFILE=y
CONFIG_TARGET_ALL_PROFILES=y
CONFIG_TARGET_DEVICE_imx6_DEVICE_ventana-large=y
CONFIG_TARGET_DEVICE_imx6_DEVICE_ventana=y
CONFIG_TARGET_DEVICE_imx6_DEVICE_cubox-i=y
CONFIG_TARGET_DEVICE_imx6_DEVICE_wandboard=y
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
```

I'm not able to build it due to [missing symbols](https://github.com/openwrt/openwrt/pull/1714/commits/596e83d397d97aa63a0330e0b8a71a599ac37669) and then there's [broken kmod-drm](https://github.com/openwrt/openwrt/pull/1714/commits/a109f673e23604ca0f1f0f3a6c86c2d8f8d8dc74).

**Comment by ynezz** [comment]
Here is the missing symbol issue http://paste.ubuntu.com/p/tpnK6b479z/

**Comment by xback** [comment]
@ynezz 
Ack on the drm patch:  merged to master.

I'm not seeing the symbol issue here (ubuntu 18.04)

**Comment by xback** [comment]
All handled in commits:

- ca1b93f038a556912e66a54b0ccc57948a312bc2
- 3b401215308e042253f61a00e7e2047169c38863
- ab18540d114385c9b3ffa230ba406723fd3af27b

**Comment by Gateworks** [comment]
On Fri, Feb 8, 2019 at 1:44 AM Koen Vandeputte <notifications@github.com> wrote:
>
> All handled in commits:
>
> ca1b93f
> 3b40121
> ab18540
>

Koen,

I think MSI should continue to be disabled for IMX6. There's a patch
for this for 4.14 and I think we should apply it to 4.19 as well. IMX6
has an issue where if MSI is enabled legacy interrupts refuse to fire.
If you recall this was a big issue for ath9k as it only supported
legacy interrupts until 4.16. Even now though ath9k doesn't use MSI
unless you set the module param use_msi=1. Even with ath9k having MSI
supported now however there are still other devices and/or drivers
that don't have MSI support. For that reason and for the fact that MSI
can actually hurt performance as one can't have multiple MSI's with
separate hw vectors I saw we disable it. What do you think?

Tim

**Comment by xback** [comment]
@Gateworks 

Hi Tim,

The patch was currently removed due to:
- It didn't apply properly and needs to be remade
- re-evaluate the current functioning (if any) and optional performance testing before doing so. (both ath9k and ath10k)

But my gut feeling also thinks that in the end, MSI will be disabled once again ..

I've scheduled to perform the testing early next week, so there's a good chance you will see a patch come along to disable it once again.

Regards,

Koen

**Comment by Gateworks** [comment]
On Thu, Feb 14, 2019 at 7:11 AM Koen Vandeputte
<notifications@github.com> wrote:
>
> @Gateworks
>
> Hi Tim,
>
> The patch was currently removed due to:
>
> It didn't apply properly and needs to be remade
> re-evaluate the current functioning (if any) and optional performance testing before doing so. (both ath9k and ath10k)
>
> But my gut feeling also thinks that in the end, MSI will be disabled once again ..
>
> I've scheduled to perform the testing early next week, so there's a good chance you will see a patch come along to disable it once again.
>

Koen,

Your right... simply allowing it to be disabled in Kconfig ends up
with compile errors in the host controller now.

I did some testing on 4.20 and found that using 'use_msi=1' for ath9k
kernel params will get it functioning but also simply using pci=nomsi
seems to work fine. I seem to recall this wasn't possible at some
point in the past leading me to just disable it at compile time but
maybe things are different now.

So perhaps we want to force 'pci=nomsi' right now for IMX6 to deal with this.

I think you'll find performance testing to be tricky. There are 4
legacy IRQs which each have their own hardware interrupt vector making
it possible to steer them to different cores and perhaps increase
performance but the sharing of these depends on the ID of each socket
so its not always easy to isolate one card from another (or from PCIe
Gbe devices on-board as on the GW53xx/GW54xx/GW552x). MSI IRQ's have a
single shared hardware vector making that steering not possible so
theoretically legacy IRQ's should allow you to boost performance
slightly if you are not overlapping IRQ's.

Honestly the only other PCIe driver I've needed on ventana is the
tw6869 capture card and I've noticed that fails its irq request even
with MSI disabled and I haven't tracked that down yet.

Tim

**Pull request closed without merging**
