### PR TITLE
[22.03] bcm4908: Refresh kernel patches

### PR DESCRIPTION
**Pull request by Ansuel**
Refresh the kernel patches for this target. No manual changes.

Fixes: https://github.com/openwrt/openwrt/commit/45ac906c6415cebd12281088da6b06668c057f0a ("bcm4908: update DTS files with the latest changes")
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>
(cherry picked from commit https://github.com/openwrt/openwrt/commit/b97e5ac785960c13199239dd4821dd53f3801da3)
[ dropped 5.15 change not present in 22.03 ]
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
NACK.

This is an unfortunate limitation of Quilt where it cannot handle renames.

**Comment by Ansuel** [comment]
@neheb well we need to find a way currently CI test fails for this only patch not refreshed :(

**Comment by Ansuel** [comment]
@hauke any suggestion for this? @BKPepe

**Comment by BKPepe** [comment]
> NACK.

I'm afraid that your NACK is too late.

> @hauke any suggestion for this?

Well, since I am not @hauke, I can see that he did the same change as you did 24 days ago to the master branch.
Reference: https://github.com/openwrt/openwrt/commit/b97e5ac785960c13199239dd4821dd53f3801da3

In that case, I think cherry-picking that commit would be preferred.

**Comment by Ansuel** [comment]
Well I think I will cherry pick... Again sorry for ignoring the double NACK but I really need some working condition for CI on stable release so I can start implementing new stuff on snapshot...

**Review by BKPepe — APPROVED** [review]
lgtm

**Comment by hauke** [comment]
The patches with renames in it are easier to read and review, but sadly quilt does not support them. I want to be able to refresh the kernel tree always, otherwise I will overlook some changes when we do an update like a stable kernel update. 

It would be nice if we could teach quilt renames in patches.

**Comment by neheb** [comment]
I think @cotequeiroz looked into it at one point as determined it was non trivial.

**Pull request merged**
