### PR TITLE
toolchain: bump GCC 11 to 11.3.0

### PR DESCRIPTION
**Pull request by rsalvaterra**
Remove an upstreamed patch and rebase all remaining patches.

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by jospezial** [comment]
Next step ahead:

"May 6, 2022
The GCC developers are pleased to announce the release of GCC 12.1."

**Comment by rockdrilla** [comment]
Build/run-tested with ath79/generic (Archer C7 v2), no FTBFS so far, even with `-O3` for kernel build (with patch allowing CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3 for all arches).

**Comment by rsalvaterra** [comment]
Anything else needed here? @aparcar?

**Comment by jospezial** [comment]
```
Build system: linux x86_64
Build-tested for and run-tested: Arcadyan VGV7510KW22 (o2 Box 6431)
```
Please merge.

**Pull request closed without merging**
