### PR TITLE
ar71xx: add support for the Hak5 WiFi Pineapple NANO

### PR DESCRIPTION
**Pull request by sebkinne**
This patch adds support for the Hak5 WiFi Pineapple NANO, a
wireless penetration testing tool.

Specifications:
  * SoC: Atheros AR9331 (400MHz)
  * RAM: 64MB (DDR2)
  * Storage: 16MB
  * Wireless: AR9331 (built-in) and AR9271 (built-in via USB bus)
  * Ports: (2) RP-SMA Antenna, Ethernet over USB (ASIX AX88772A),
    USB 2.0 Host, and Micro SD
  * Power: USB 5V 1.5A
  * Other: Status LED and reset button

Flash instructions:
  Original firmware is based on OpenWrt.
  Use sysupgrade via SSH to flash.

Signed-off-by: Sebastian Kinne <contact@sebkinne.com>

### CODE REVIEW

**Comment by neheb** [comment]
Out of curiosity, why does this use Ethernet over USB as opposed to the built-in Ethernet port?

**Comment by sebkinne** [comment]
@neheb We wanted to create a "dongle" type device.

The ASIX connects to eth0 on the AR9331. We did not expose an ethernet port like we did on the WiFi Pineapple TETRA.

**Review by pepe2k — CHANGES_REQUESTED** [review]
Hi @sebkinne!

Thank you for your PR, please see my comments inline, below.

I had a brief look at your two other PRs (#719 and #720) and most of my comments here apply also there.

Also, as all of these devices are very similar and based on the same platform, would you please consider keeping support for all of them in a single shared mach-*.c file? For an example, please have a look at https://github.com/openwrt/openwrt/blob/master/target/linux/ar71xx/files/arch/mips/ath79/mach-archer-c7.c

It would be also easier for a review and merge/rebase if you combined all 3 PRs into single one (with 1 or 3 separate commits).

Cheers,
Piotr

**Comment by sebkinne** [comment]
Closed in favor of a single PR (#736).

**Pull request closed without merging**
