### PR TITLE
[23.05] MacOS improvements related to U-boot and its hacky patches

### PR DESCRIPTION
**Pull request by BKPepe**
Hi,

based on discussion here: https://github.com/openwrt/openwrt/commit/4a8961f1dfba33b1e9a38dd0ecb3a8b03c46edbb#commitcomment-140901426

I cherry-picked three commits from the main branch to be able to compile U-boot while using MacOS as host.

### CODE REVIEW

**Comment by BKPepe** [comment]
Hmm, I think the failing CI is not related to my issue, though.

While looking at log, I see that Docker image ``macos-latest`` was updated and now it is downloading ``make--4.4.1.arm64_sonoma.bottle.tar.gz`` and in the past, it was downloading ``make--4.4.1.monterey.bottle.tar.gz``

**Comment by BKPepe** [comment]
CI should be fixed by this https://github.com/openwrt/actions-shared-workflows/commit/cdc2a2569f2675cd60c38ebd3b925f6ce8ef1b6a. Could we re-run the CI instead of force pushing it, please? :)

**Comment by robimarko** [comment]
I think that force-pushing will be required as re-running the macOS CI is still not checking out the latest shared-workflow commit

**Comment by robimarko** [comment]
Yeah, force-pushing or any change was required in order to pick the current HEAD of actions-shared-workflow

**Comment by ynezz** [comment]
Would it be fine with you if I do this cherry-picks myself, thus signing them again, avoiding the `Unverified` label?

image

**Comment by BKPepe** [comment]
Sure, that's not a problem at all. :) I should again use my GPG to sign my commits as well.

**Comment by ynezz** [comment]
> I should again use my GPG to sign my commits as well.

Yep, that would be great and would work for me as well in this case as it would be `Partially verified` which should be fine. More details in the [other pull request](https://github.com/openwrt/openwrt/pull/15195#issuecomment-2063599444).

**Comment by ynezz** [comment]
Merged in 8695bc34426, thanks!

**Pull request closed without merging**
