### PR TITLE
[RFC/WIP]: armsr: add 6.6 as testing kernel

### PR DESCRIPTION
**Pull request by mcbridematt**
This patch set adds kernel 6.6 as the testing version for the armsr target.

Notes:
* ~kmod-drm is broken, while `CONFIG_DRM_EXEC` and `CONFIG_DRM_SUBALLOC_HELPER` are specified, the kernel doesn't build them (due to lack of modules depending on them?)~
* The GPIO numbers shifted as a result of changes in kernel 6.2, I think there will need to be an OpenWrt-wide approach to handle this
* armsr_armv8 requires virto_virqfd to be flagged as for 6.2 and earlier (same as x86, see https://github.com/openwrt/openwrt/pull/14868#issuecomment-1998260124) 
* Only tested so far in QEMU (armv7 and armv8) and Traverse Technologies Ten64. I will try some other hosts (e.g AWS Graviton) next week for armv8

### CODE REVIEW

**Comment by namiltd** [comment]
https://github.com/openwrt/openwrt/pull/14896/commits/4a2138c325f6bbae6a7cf51f87f0b8cb64de4419 Missing commit message. Please describe your changes

**Comment by hackpascal** [comment]
> * kmod-drm is broken, while `CONFIG_DRM_EXEC` and `CONFIG_DRM_SUBALLOC_HELPER` are specified, the kernel doesn't build them (due to lack of modules depending on them?)

This has been fixed by https://github.com/openwrt/openwrt/pull/14899

**Review by ehem — CHANGES_REQUESTED** [review]
There is a script for this which preserves history, that should be used instead.

(note to committers, the results of that script **cannot** be directly rebased)

**Comment by john-tho** [comment]
> * The GPIO numbers shifted as a result of changes in kernel 6.2, I think there will need to be an OpenWrt-wide approach to handle this

Maybe worth taking this to the mailing list, or pinging some maintainers to get the discussion going.

A quick and (very) dirty hack could be to modify the [`gpio_switch`](https://github.com/openwrt/openwrt/blob/main/package/base-files/files/etc/init.d/gpio_switch) script (and [config setter](https://github.com/openwrt/openwrt/blob/dea42f67ab06a8f2c1e6338f9829d31a28642317/package/base-files/files/lib/functions/uci-defaults.sh#L631)) to accept strings, which then could be `grep`ed against `gpio-line-names` or DTS labels in `cat /sys/kernel/debug/gpio`.
Maybe better is a gpiolib based solution?

You would also need a migration script to update these details in stored config if a sysupgrade takes a device from 6.1 to 6.6?

**Comment by mcbridematt** [comment]
> There is a script for this which preserves history, that should be used instead.
> 
> (note to committers, the results of that script **cannot** be directly rebased)

Done, the new commits are based on that

> Maybe worth taking this to the mailing list, or pinging some maintainers to get the discussion going.

I'll post to the ML. I can find some discussion about it back in 2022 but it appears further movement was waiting on libgpiod v2 to come out (which it did, last August).

I have tried to detect the kernel version and choose the correct GPIO base numbers that way, but I don't like this 100% either.

I would prefer using sysfs paths (like `/sys/devices/platform/soc/2000000.i2c/i2c-0/0-0076/gpio/`) but the problem is that board.d is run before modules, so it may not always find GPIOs from drivers that are not built into the kernel.

gpio-line-names from DT could be an option, but for a "universal" target like armsr, we can't depend on every board having a DTB that is setup correctly for us.

**Comment by mcbridematt** [comment]
Rebased and tested working on various AWS Graviton instances (a1.metal,c6g.metal,t4.nano)
It doesn't look like there will be a change in the GPIO system just yet, so a uci-defaults script will update existing gpio_switch references where needed.

**Pull request merged**
