### PR TITLE
kernel: fonfxc uImage parser checks partition DT node compatibility

### PR DESCRIPTION
**Pull request by drvlabo**
We cannot distinct between fonfxc uImage and generic uImage
because fonfxc uImage header is almost same as generic uImage,
except padding length after image name.

The fonfxc uImage parser is available
when specifying directly with DT compatible property.
So, added checking partition DT node is compatible with the parser.

Signed-off-by: NOGUCHI Hiroshi <drvlabo@gmail.com>

### CODE REVIEW

**Comment by ynezz** [comment]
Thanks, pushed in https://github.com/openwrt/openwrt/commit/e92a14709d37f64dcba8c81fa51e61e5f10f439a

**Comment by ynezz** [comment]
It seems like this fonfxc needs more work. @rmilecki has kindly reviewed this commit in the morning and told me, that this is not a proper fix and just a hack as this change is basically the same as removing `.type = MTD_PARSER_TYPE_FIRMWARE`, but this is not probably what would be desirable anyway.

By reading the source code again, I now think, that it would be better to try other approach instead, if the bootloader allows it. Can't you simply add some magic like `FONFXC-UIMAGE` into that 32 bytes (`FONFXC_PAD_LEN`) of padding and simply try check for that? Simply something as it's being currently done in `uimage_find_edimax`. This would of course involve some small change in `uimage_padhdr.c` as well.

**Comment by drvlabo** [comment]
I think an idea of checking whether 32 bytes padding area are all '0's.
In generic uImage 32 bytes '0's do not apear followed by uImage header.

How's that ?

**Comment by ynezz** [comment]
> I think an idea of checking whether 32 bytes padding area are all '0's.

I don't think, that checking for 32 zeroes is going to work in long term and thus is not a good idea. We should really check for some unique magic, which is not likely to be available in other uImage (even future ones) headers.

**Comment by drvlabo** [comment]
>  Can't you simply add some magic like FONFXC-UIMAGE into that 32 bytes (FONFXC_PAD_LEN) of padding
This means that  injecting unique value into padding area ?
For example, like this...
  0x46 0x66 0x78 0x63 0x00 ... (28bytes '0')

**Comment by ynezz** [comment]
> > Can't you simply add some magic like FONFXC-UIMAGE into that 32 bytes (FONFXC_PAD_LEN) of padding
> > This means that  injecting unique value into padding area ?
> > For example, like this...
> > 0x46 0x66 0x78 0x63 0x00 ... (28bytes '0')

Correct, choose something which is not likely to be included in any other image in order to avoid future clash, in other words, it would be better to make it longer then 4 bytes as in your example, so `FONFXC` or `FONFXC-UIMAGE` should be probably ok.

**Comment by rmilecki** [comment]
I did a quick research on that and it seems that Fon(Foxconn) parser it needed my `ramips` supported Fon FON2601 only (unless more targets start using it since the time it was added).

We're lucky for Fon FON2601 & `ramips` to use DT, so I believe we can limit that new parser to DT cases only. That sounds like a good idea since it's matching patter is so (too) generic.

**Comment by rmilecki** [comment]
Please try this alternative fix:
```
[PATCH] kernel: drop Fon(Foxconn) parser matching for the "firmware" partition
```
https://patchwork.ozlabs.org/patch/1142652/

I tried to compose a commit message that explains the original problem & why the proposed fix should be safe.

**Comment by drvlabo** [comment]
@rmilecki Thanks for the review and suggesting an idea to fix problem.

**Comment by rmilecki** [comment]
I've received testing success report & pushed the patch. See c4492dd70e93 ("kernel: drop Fon(Foxconn) parser matching for the "firmware" partition").

**Comment by drvlabo** [comment]
@rmilecki I checked the commit. I think that it's fine.

**Pull request closed without merging**
