### PR TITLE
openssl: add infrastructure for providers, build legacy provider

### PR DESCRIPTION
**Pull request by cotequeiroz**
This adapts the engine build infrastructure to allow building providers, and packages the legacy provider.  Providers are the successors of engines, which have been deprecated.

The legacy provider supplies OpenSSL implementations of algorithms that have been deemed legacy, including DES, IDEA, MDC2, SEED, and Whirlpool.

Since these algorithms are built in a separate package, it does not make sense to keep the individual options cluttering menuconfig.  The provider is always built with all of the openssl-default algorithms.

The engine build and configuration structure was changed to accommodate providers, adapt to the new style of openssl.cnf in version 3.0.  The engine and provider configuration files are saved in the same directory, renamed from "engines" to "modules".  The generated lists of installed engines and providers are kept separate.

Temporary breakage of engine packages is expected, but are trivial to be resolved.  There is not a clean upgrade path for configuration files, but this is already happening because of the added options in OpenSSL 3.0.

It is recommended to rename or remove the old config files when using sysupgrade with new libopenssl-conf engine packages.  Then apply the changes manually.

If upgrading with opkg, and the old config files have been changed, the new ones will be saved with -opgk extenstion, and are an alternative way of updating the configurations if not running sysupgrade.

While investigating some engine performance stuff, I found out `OPENSSL_SMALL_FOOTPRINT` cripples performance on aarch64 with only a 1% size decrease.  I consider this broken on aarch64.  While the performance penalty was not so severe with all targets, the benefit was minimal, so I turned it off unless `SMALL_FLASH` is used (poor souls).  This happens with openssl 1.1.1, so that commit should be backported.

----

I have only briefly tested this, so I'm marking it as draft for now.

Ping @e9hack, @brvphoenix

### CODE REVIEW

**Comment by zxlhhyccc** [comment]
What is the updated algorithm command?

**Comment by cotequeiroz** [comment]
I'm not sure I understand your question. This PR is adding a legacy provider, for unsafe, or rarely used algorithms.

OpenSSL lists these legacy algorithms even if the provider is not available.  If the provider is not enabled--the application can request it-- OpenSSL just fails when you try to use them. 

If you install the package, the provider will be enabled by default.

**Comment by zxlhhyccc** [comment]
@cotequeiroz The command to check the acceleration engine before updating is `openssl engine -t -c`，What is this updated command?

**Comment by cotequeiroz** [comment]
The "provider" API is the replacement of the deprecated "engine" API.  I haven't even started to look into porting afalg_engine to it.  To be honest, if I'm not coerced into doing it, I probably won't.

**Comment by cotequeiroz** [comment]
> @cotequeiroz The command to check the acceleration engine before updating is `openssl engine -t -c`，What is this updated command?

This does not change any of the engines there.  I haven't played that much with the new CLI util.  There appears to be no `openssl provider` command.  However, `openssl list` will show you interesting information.:
 -  `openssl list -providers -verbose` is the closest thing to `openssl engine -t -c`, but it will not list you the algorithms.
 -  `openssl list -cipher-algorithms` and `openssl list -digest-algorithms` will tell you what providers supply each algorithm.

**Comment by zxlhhyccc** [comment]
@cotequeiroz Very strange issue, AX6 will not start wireless if it does not compile the engine.

**Comment by e9hack** [comment]
I've partly success to get hostapd running with openssl. The necessary library legacy.so is build but not installed. I copy it manually to the router. I need somewhere in the openssl config files two sections:
```
[provider_sect]
legacy = legacy_sect
[legacy_sect]
activate = 1
```
I add this to /etc/ssl/openssl.conf

/etc/config/openssl contains an entry
```
config engine 'devcrypto'
	option enabled '1'
```
This looks incomplete or wrong. /etc/init.d/openssl reload shows the following error message:
```
Generating engines.cnf
Skipping devcrypto: /usr/lib/engines-3/devcrypto.so not found.
```
If I add something for the legacy provider to /etc/config/openssl:
```
config provider 'legacy'
	option enabled '1'
```
I get an error message too:
```
Generating providers.cnf
Skipping legacy: Could not find section legacy_sect in config files.
```
providers.cnf and engines.cnf are empty files (containing only a comment line).

**Comment by e9hack** [comment]
> I've partly success to get hostapd running with openssl. The necessary library legacy.so is build but not installed. I copy it manually to the router. I need somewhere in the openssl config files two sections:

For unknown reason was the legacy provider option not visible at the first try to configure openssl via 'make menuconfig'. Anything for the legacy provider is now created properly. For devcrypto something is missing.

**Comment by cotequeiroz** [comment]
> For unknown reason was the legacy provider option not visible at the first try to configure openssl via 'make menuconfig'. Anything for the legacy provider is now created properly. For devcrypto something is missing.

If you use an SDK, then you may need to update `include/openssl-module.mk` from this PR, but in that case it would fail to build.
It may have been stale `tmp/.package*` data.  BTW, does the legacy provider fix your problem?


> @cotequeiroz Very strange issue, AX6 will not start wireless if it does not compile the engine.

Do you use DES (not 3DES) anywhere? @xabolcs problem was due to its absence from openssl 3.0 default provider.  The devcrypto engine would have supplied that algorithm.  This is from the top of your run:
```
# openssl engine -t -c -v -pre DUMP_INFO devcrypto
(devcrypto) /dev/crypto engine
Information about ciphers supported by the /dev/crypto engine:
Cipher DES-CBC, NID=31, /dev/crypto info: id=1, driver=cbc-des-qce (hw accelerated)
```

**Comment by neheb** [comment]
> The "provider" API is the replacement of the deprecated "engine" API. I haven't even started to look into porting afalg_engine to it. To be honest, if I'm not coerced into doing it, I probably won't.

OK. I personally use it on Armbian. Works great.

**Comment by cotequeiroz** [comment]
I'll consider this a nice kind of coercion.

**Comment by e9hack** [comment]
> > For unknown reason was the legacy provider option not visible at the first try to configure openssl via 'make menuconfig'. Anything for the legacy provider is now created properly. For devcrypto something is missing.
> 
> If you use an SDK, then you may need to update `include/openssl-module.mk` from this PR, but in that case it would fail to build. It may have been stale `tmp/.package*` data. BTW, does the legacy provider fix your problem?

I had to delete anything under ./tmp to see the legacy provider in the configuration. With the legacy provider, hostapd is now running in wpa enterprise mode. If I reload the setting, I got the following output:
```
root@my-router:~# /etc/init.d/openssl reload
Generating engines.cnf
Skipping devcrypto: /usr/lib/engines-3/devcrypto.so not found.
Generating providers.cnf
Enabling legacy
```

**Comment by cotequeiroz** [comment]
Does `/usr/lib/engines-3/devcrypto.so` exist?  Was the devcrypto engine built into the main libopenssl library?  If so, you will need to set `force '1'` to the engine's config in `/etc/config/openssl`, to skip the check:
```
config engine 'devcrypto'
        option enabled '1'
        option force `1`
```
I will see about adding a specific option for it, and perhaps configure it properly when built into the library.

**Comment by zxlhhyccc** [comment]
openssl已更新到3.1.0版本了。。。。

**Comment by cotequeiroz** [comment]
> openssl has been updated to version 3.1.0...

The decision is not mine.  I'm not sure we should switch to 3.1, because its support will end on 2025-03-14, before 3.0, which is a LTS: 2026-09-07.  I could add a 3.1 package in the packages feed, and it can be used as a drop-in replacement, perhaps.

**Comment by cotequeiroz** [comment]
I think this can be merged now.  It would be good to iron out any problems before we fork the next release.
@Ansuel , can you help?

**Comment by Ansuel** [comment]
@cotequeiroz can you rebase?

**Pull request merged**
