### PR TITLE
[23.05] ramips: add support for D-Link COVR-X1860 A1

### PR DESCRIPTION
**Pull request by maurerle**
This is a PR to backport the D-Link COVR-X1860 A1 to openwrt 23.05.

It includes a bump the new firmware-utils release branch, which includes the needed signed image.
It also backports the dlink-sge-image utility function, which is cherry-picked from https://github.com/openwrt/openwrt/commit/4c0dc68f466588bb2ef60b29a4d8052b34112ca6
And cherry-picks the commit which adds support to the d-link covr-x1860 a1 from https://github.com/openwrt/openwrt/commit/0a18259e4aa361cd9e5848c038be4b9f4e3bfcc6

This has been tested using openwrt and gluon on a COVR-X1860

### CODE REVIEW

**Comment by maurerle** [comment]
The Test formalities should now be happy too.

A build from this is fine and produces following outputs:
openwrt-ramips-mt7621-dlink_covr-x1860-a1-squashfs-factory.bin
openwrt-ramips-mt7621-dlink_covr-x1860-a1-squashfs-recovery.bin
openwrt-ramips-mt7621-dlink_covr-x1860-a1-initramfs-kernel.bin  
openwrt-ramips-mt7621-dlink_covr-x1860-a1-squashfs-sysupgrade.bin

A device test is awaited.

After creating a branch on the official firmware-utils repository, I will force push the change back to the upstream firmware-utils repo.
This PR is then ready

**Comment by maurerle** [comment]
@hauke @blocktrron 
It is needed to push this branch/commit https://github.com/maurerle/firmware-utils/tree/openwrt-23.05 on the official firmware-utils openwrt repository :)
Can one of you do this?

**Comment by maurerle** [comment]
This is ready to merge from my side.
It is tested with openwrt and gluon.

**Comment by aparcar** [comment]
It doesn't seem right to change filenames within a release or am I misunderstanding the commit?

**Comment by aparcar** [comment]
Isn't this a duplicate of https://github.com/openwrt/openwrt/pull/14251 or the other way around?

**Comment by maurerle** [comment]
@aparcar you mean that `factory.bin` is now the signed `recovery.bin` for dlink_dir-8xx-a1 and dlink_dir-8xx-r1?
I don't know, I cherry picked the commit, but if this is too much, I can remove it too and only add the dlink-sge-image for the newly added covr-x1860.

Yes the other approach thought to fully bump the firmware-utils repo - I closed them.

**Comment by maurerle** [comment]
I changed the second commit to not contain the changes to other devices factory/recovery image.
I do not know if this should still be an adjusted cherry-pick or a totally independent commit.
I kept the reference of the cherrypick.

@blocktrron is it fine like that?

**Comment by blocktrron** [comment]
Merged, thanks!

**Pull request closed without merging**
