### PR TITLE
update to 3.3 and enable fat build

### PR DESCRIPTION
**Pull request by nmav**
This allows to include optimizations such as AESNI and ARM neon which
are detected on run-time.

Signed-off-by: Nikos Mavrogiannopoulos <nmav@gnutls.org>

### CODE REVIEW

**Comment by wigyori** [comment]
Please prefix the commit with"packages: nettle: ", otherwise it's fine.

Thx,
-w-

**Comment by nmav** [comment]
@wigyori done

**Comment by nmav** [comment]
@wigyori is there anything else needed?

**Comment by wigyori** [comment]
Let it be, thanks!

**Pull request merged**
