### PR TITLE
ath79: Add support of D-Link DIR-825 B1

### PR DESCRIPTION
**Pull request by hanipouspilot**
Signed-off-by: Dmitry Tunin <hanipouspilot@gmail.com>

### CODE REVIEW

**Comment by hanipouspilot** [comment]
So here we go. Configuration and scripting part looks to be finished.
Thanks a lot to all who helped.
If I forgot something, welcome to review.

The problem that is not solved is the eth1 crash. But it doesn't seem to be configuration related, but a bug in ag71xx that should be fixed somehow.

**Comment by hanipouspilot** [comment]
For completeness sake, here is dmesg
`
[    0.000000] Linux version 4.14.61 (pilot6@Pilot6) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r7764-733fddc)) #0 Thu Aug 9 18:08:01 2018
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019374 (MIPS 24Kc)
[    0.000000] MIPS: machine is D-Link DIR825B1
[    0.000000] SoC: Atheros AR7161 rev 2
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 04000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] On node 0 totalpages: 16384
[    0.000000] free_area_init_node: node 0, pgdat 80503460, node_mem_map 81007680
[    0.000000]   Normal zone: 128 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 16384 pages, LIFO batch:3
[    0.000000] random: get_random_bytes called from start_kernel+0x8c/0x474 with crng_init=0
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 16256
[    0.000000] Kernel command line: console=ttyS0,115200 rootfstype=squashfs,jffs2
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 58332K/65536K available (3704K kernel code, 151K rwdata, 896K rodata, 1192K init, 212K bss, 7204K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] CPU clock: 680.000 MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 5621354254 ns
[    0.000008] sched_clock: 32 bits at 340MHz, resolution 2ns, wraps every 6316128254ns
[    0.007797] Calibrating delay loop... 452.19 BogoMIPS (lpj=2260992)
[    0.074072] pid_max: default: 32768 minimum: 301
[    0.078880] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.085485] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.096078] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.105942] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.112088] pinctrl core: initialized pinctrl subsystem
[    0.118070] NET: Registered protocol family 16
[    0.427077] PCI host bridge /ahb/apb/pcie-controller@180c0000 ranges:
[    0.433531]  MEM 0x0000000010000000..0x0000000016ffffff
[    0.438743]   IO 0x0000000000000000..0x0000000000000000
[    0.457187] PCI host bridge to bus 0000:00
[    0.461290] pci_bus 0000:00: root bus resource [mem 0x10000000-0x16ffffff]
[    0.468195] pci_bus 0000:00: root bus resource [io  0x0000]
[    0.473761] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    0.480540] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    0.488496] pci 0000:00:11.0: [168c:ff1d] type 00 class 0x020000
[    0.488530] pci 0000:00:11.0: reg 0x10: [mem 0x00000000-0x0000ffff]
[    0.488767] pci 0000:00:12.0: [168c:ff1d] type 00 class 0x020000
[    0.488794] pci 0000:00:12.0: reg 0x10: [mem 0x00000000-0x0000ffff]
[    0.489010] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
[    0.489036] pci 0000:00:11.0: BAR 0: assigned [mem 0x10000000-0x1000ffff]
[    0.495850] pci 0000:00:12.0: BAR 0: assigned [mem 0x10010000-0x1001ffff]
[    0.503144] clocksource: Switched to clocksource MIPS
[    0.509044] NET: Registered protocol family 2
[    0.514081] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.521043] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.527440] TCP: Hash tables configured (established 1024 bind 1024)
[    0.533932] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.539766] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.546278] NET: Registered protocol family 1
[    0.550665] PCI: CLS 0 bytes, default 32
[    0.554210] Crashlog allocated RAM at address 0x3f00000
[    0.560416] workingset: timestamp_bits=30 max_order=14 bucket_order=0
[    0.570890] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.576748] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.593250] io scheduler noop registered
[    0.597170] io scheduler deadline registered (default)
[    0.602454] ar7100-usb-phy 18030000.usb-phy: phy reset is missing
[    0.609387] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.616353] console [ttyS0] disabled
[    0.619962] 18020000.uart: ttyS0 at MMIO 0x18020000 (irq = 8, base_baud = 10625000) is a 16550A
[    0.628705] console [ttyS0] enabled
[    0.635669] bootconsole [early0] disabled
[    0.648324] m25p80 spi0.0: m25p64 (8192 Kbytes)
[    0.652894] 5 fixed-partitions partitions found on MTD device spi0.0
[    0.659280] Creating 5 MTD partitions on "spi0.0":
[    0.664078] 0x000000000000-0x000000040000 : "u-boot"
[    0.669740] 0x000000040000-0x000000050000 : "config"
[    0.675374] 0x000000050000-0x000000660000 : "firmware"
[    0.691885] 2 uimage-fw partitions found on MTD device firmware
[    0.697832] 0x000000050000-0x0000001d3cc6 : "kernel"
[    0.703518] 0x0000001d3cc6-0x000000660000 : "rootfs"
[    0.709057] mtd: device 4 (rootfs) set to be root filesystem
[    0.714782] 1 squashfs-split partitions found on MTD device rootfs
[    0.720954] 0x000000450000-0x000000660000 : "rootfs_data"
[    0.726987] 0x000000660000-0x000000670000 : "caldata"
[    0.732637] 0x000000670000-0x000000800000 : "unknown"
[    0.738701] Realtek RTL8366S ethernet switch driver version 0.2.2
[    0.744876] rtl8366s rtl8366s: cannot find mdio node phandle
[    0.750534] rtl8366s rtl8366s: using GPIO pins 5 (SDA) and 7 (SCK)
[    0.756820] rtl8366s rtl8366s: RTL8366 ver. 1 chip found
[    0.809158] libphy: rtl8366s: probed
[    0.814152] libphy: Fixed MDIO Bus: probed
[    0.820134] ag71xx 19000000.eth: invalid MAC address, using random address
[    1.164761] ag71xx 19000000.eth: connected to PHY at fixed-0:00 [uid=00000000, driver=Generic PHY]
[    1.174291] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode:RGMII
[    1.180595] ag71xx 1a000000.eth: invalid MAC address, using random address
[    1.525014] ag71xx 1a000000.eth: connected to PHY at rtl8366s:04 [uid=001cc960, driver=Generic PHY]
[    1.534621] eth1: Atheros AG71xx at 0xba000000, irq 5, mode:RGMII
[    1.542681] NET: Registered protocol family 10
[    1.550984] Segment Routing with IPv6
[    1.554785] NET: Registered protocol family 17
[    1.559259] 8021q: 802.1Q VLAN Support v1.8
[    1.570625] VFS: Mounted root (squashfs filesystem) readonly on device 31:4.
[    1.581229] Freeing unused kernel memory: 1192K
[    1.585774] This architecture does not have kernel memory protection.
[    2.305465] init: Console is alive
[    2.309056] init: - watchdog -
[    2.543181] random: fast init done
[    3.394390] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    3.518424] usbcore: registered new interface driver usbfs
[    3.524000] usbcore: registered new interface driver hub
[    3.529389] usbcore: registered new device driver usb
[    3.539303] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    3.547351] ehci-platform: EHCI generic platform driver
[    4.151764] ehci-platform 1b000000.usb: EHCI Host Controller
[    4.157467] ehci-platform 1b000000.usb: new USB bus registered, assigned bus number 1
[    4.165404] ehci-platform 1b000000.usb: irq 3, io mem 0x1b000000
[    4.193176] ehci-platform 1b000000.usb: USB 2.0 started, EHCI 1.00
[    4.200083] hub 1-0:1.0: USB hub found
[    4.204217] hub 1-0:1.0: 2 ports detected
[    4.210993] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    4.218601] ohci-platform: OHCI generic platform driver
[    4.224060] ohci-platform 1c000000.usb: Generic Platform OHCI controller
[    4.230790] ohci-platform 1c000000.usb: new USB bus registered, assigned bus number 2
[    4.238691] ohci-platform 1c000000.usb: irq 11, io mem 0x1c000000
[    4.317969] hub 2-0:1.0: USB hub found
[    4.321999] hub 2-0:1.0: 2 ports detected
[    4.327452] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    4.337737] init: - preinit -
[    5.080472] random: jshn: uninitialized urandom read (4 bytes read)
[    5.209418] random: jshn: uninitialized urandom read (4 bytes read)
[    5.413276] random: jshn: uninitialized urandom read (4 bytes read)
[    5.917672] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    5.923619] IPv6: ADDRCONF(NETDEV_UP): eth0.1: link is not ready
[    6.993538] eth0: link up (1000Mbps/Full duplex)
[    6.998175] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    7.004833] IPv6: ADDRCONF(NETDEV_CHANGE): eth0.1: link becomes ready
[    9.157639] mount_root: jffs2 not ready yet, using temporary tmpfs overlay
[    9.192729] urandom-seed: Seed file not found (/etc/urandom.seed)
[    9.297892] procd: - early -
[    9.300859] procd: - watchdog -
[    9.671847] urandom_read: 3 callbacks suppressed
[    9.671855] random: jshn: uninitialized urandom read (4 bytes read)
[    9.846954] random: jshn: uninitialized urandom read (4 bytes read)
[    9.913034] procd: - watchdog -
[    9.919002] procd: - ubus -
[   10.183753] eth0: link down
[   10.186740] random: ubusd: uninitialized urandom read (4 bytes read)
[   10.256287] procd: - init -
[   10.500854] kmodloader: loading kernel modules from /etc/modules.d/*
[   10.512759] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[   10.536573] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   10.562285] usbcore: registered new interface driver cdc_wdm
[   10.630821] Loading modules backported from Linux version wt-2017-11-01-0-gfe248fc2c180
[   10.638869] Backport generated by backports.git v4.14-rc2-1-31-g86cf0e5d
[   10.651455] ip_tables: (C) 2000-2006 Netfilter Core Team
[   10.664538] nf_conntrack version 0.5.0 (1024 buckets, 4096 max)
[   10.747947] PCI: Enabling device 0000:00:11.0 (0000 -> 0002)
[   10.753831] PCI: Enabling device 0000:00:12.0 (0000 -> 0002)
[   10.760577] owl-loader 0000:00:11.0: Direct firmware load for ath9k-eeprom-pci-0000:00:11.0.bin failed with error -2
[   10.771132] owl-loader 0000:00:11.0: Falling back to user helper
[   10.778549] owl-loader 0000:00:12.0: Direct firmware load for ath9k-eeprom-pci-0000:00:12.0.bin failed with error -2
[   10.789105] owl-loader 0000:00:12.0: Falling back to user helper
[   10.809521] usbcore: registered new interface driver usbserial
[   10.815473] usbcore: registered new interface driver usbserial_generic
[   10.822042] usbserial: USB Serial support registered for generic
[   10.876813] xt_time: kernel timezone is -0000
[   10.885128] usbcore: registered new interface driver cdc_ncm
[   10.934454] usbcore: registered new interface driver huawei_cdc_ncm
[   11.003663] PPP generic driver version 2.4.2
[   11.012695] NET: Registered protocol family 24
[   11.070487] usbcore: registered new interface driver option
[   11.076193] usbserial: USB Serial support registered for GSM modem (1-port)
[   11.133542] kmodloader: done loading kernel modules from /etc/modules.d/*
[   11.148972] owl-loader 0000:00:11.0: fixup device configuration
[   11.156461] pci 0000:00:11.0: [168c:0029] type 00 class 0x028000
[   11.156496] pci 0000:00:11.0: reg 0x10: [mem 0x10000000-0x1000ffff]
[   11.156562] pci 0000:00:11.0: PME# supported from D0 D3hot
[   11.156781] pci 0000:00:11.0: BAR 0: assigned [mem 0x10000000-0x1000ffff]
[   11.163732] PCI: Enabling device 0000:00:11.0 (0000 -> 0002)
[   11.192380] ath: phy0: Ignoring endianness difference in EEPROM magic bytes.
[   11.201239] ath: EEPROM regdomain: 0x0
[   11.201243] ath: EEPROM indicates default country code should be used
[   11.201246] ath: doing EEPROM country->regdmn map search
[   11.201257] ath: country maps to regdmn code: 0x3a
[   11.201262] ath: Country alpha2 being used: US
[   11.201265] ath: Regpair used: 0x3a
[   11.215086] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   11.218019] ieee80211 phy0: Atheros AR9280 Rev:2 mem=0xb0000000, irq=12
[   11.389040] owl-loader 0000:00:12.0: fixup device configuration
[   11.396552] pci 0000:00:12.0: [168c:0029] type 00 class 0x028000
[   11.396589] pci 0000:00:12.0: reg 0x10: [mem 0xffff0000-0xffffffff]
[   11.396654] pci 0000:00:12.0: PME# supported from D0 D3hot
[   11.396876] pci 0000:00:12.0: BAR 0: assigned [mem 0x10010000-0x1001ffff]
[   11.403820] PCI: Enabling device 0000:00:12.0 (0000 -> 0002)
[   11.432476] ath: phy1: Ignoring endianness difference in EEPROM magic bytes.
[   11.441288] ath: EEPROM regdomain: 0x0
[   11.441293] ath: EEPROM indicates default country code should be used
[   11.441296] ath: doing EEPROM country->regdmn map search
[   11.441306] ath: country maps to regdmn code: 0x3a
[   11.441311] ath: Country alpha2 being used: US
[   11.441314] ath: Regpair used: 0x3a
[   11.457339] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
[   11.460294] ieee80211 phy1: Atheros AR9280 Rev:2 mem=0xb0010000, irq=12
[   23.889475] jffs2_scan_eraseblock(): End of filesystem marker found at 0x0
[   23.923208] jffs2_build_filesystem(): unlocking the mtd device... 
[   23.923267] done.
[   23.931357] jffs2_build_filesystem(): erasing all blocks after the end marker... 
[   25.184914] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   25.198616] eth0: link up (1000Mbps/Full duplex)
[   25.214262] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   25.265480] device eth0 entered promiscuous mode
[   25.288934] br-lan: port 1(eth0.1) entered blocking state
[   25.294383] br-lan: port 1(eth0.1) entered disabled state
[   25.300066] device eth0.1 entered promiscuous mode
[   25.393415] br-lan: port 1(eth0.1) entered blocking state
[   25.398817] br-lan: port 1(eth0.1) entered forwarding state
[   25.404564] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   25.515095] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
[   26.193320] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   27.634477] eth1: link up (100Mbps/Full duplex)
[   27.639379] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[   43.153156] ------------[ cut here ]------------
[   43.157803] WARNING: CPU: 0 PID: 1612 at net/sched/sch_generic.c:320 dev_watchdog+0x164/0x274
[   43.166323] NETDEV WATCHDOG: eth1 (ag71xx): transmit queue 0 timed out
[   43.172828] Modules linked in: ath9k ath9k_common pppoe ppp_async option ath9k_hw ath usb_wwan pppox ppp_generic nf_conntrack_ipv6 mac80211 iptable_nat ipt_REJECT ipt_MASQUERADE huawei_cdc_ncm cfg80211 cdc_ncm xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_FLOWOFFLOAD usbserial usbnet slhc owl_loader nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc_ccitt compat cdc_wdm ledtrig_usbport ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables sit tunnel4 ip_tunnel ohci_platform ohci_hcd
[   43.243600]  ehci_platform ehci_hcd gpio_button_hotplug usbcore nls_base usb_common mii
[   43.251604] CPU: 0 PID: 1612 Comm: luci Not tainted 4.14.61 #0
[   43.257428] Stack : 00000000 00000000 80637522 00000032 838dc2d4 804e78e7 804907f4 0000064c
[   43.265781]         80633670 00000140 804f2cf4 804f2cb4 804f2ca0 00000001 83809db8 735f66fe
[   43.274135]         00000000 00000000 80630000 00004990 00000000 00000000 00000007 00000000
[   43.282482]         000000ed 9f13a6c0 000000ec 00000000 80000000 00000000 804b7830 8030e0ac
[   43.290837]         00000009 00000140 804f2cf4 804f2cb4 00000001 8025d8e4 00000000 80630000
[   43.299194]         ...
[   43.301636] Call Trace:
[   43.304100] [<8006a90c>] show_stack+0x58/0x100
[   43.308549] [<80080900>] __warn+0xe4/0x118
[   43.312641] [<80080964>] warn_slowpath_fmt+0x30/0x3c
[   43.317611] [<8030e0ac>] dev_watchdog+0x164/0x274
[   43.322316] [<800b99e0>] call_timer_fn.isra.4+0x24/0x84
[   43.327559] [<800b9bb0>] run_timer_softirq+0x170/0x1e8
[   43.332696] [<803fd168>] __do_softirq+0xe8/0x2bc
[   43.337328] [<8020da40>] plat_irq_dispatch+0xc0/0x120
[   43.342367] [<800658f8>] handle_int+0x138/0x144
[   43.346900] [<8020268c>] lzma_main+0xd0/0xb1c
[   43.351249] [<80203690>] xz_dec_lzma2_run+0x5b8/0x898
[   43.356302] [<80201a9c>] xz_dec_run+0x398/0xb20
[   43.360828] [<8019985c>] squashfs_xz_uncompress+0x11c/0x200
[   43.366398] [<801996f4>] squashfs_decompress+0x48/0x80
[   43.371541] [<801950f4>] squashfs_read_data+0x4e4/0x6f0
[   43.376775] [<80195648>] squashfs_cache_get+0x198/0x2bc
[   43.381987] [<80196cb8>] squashfs_readpage+0x55c/0x704
[   43.387136] [<800f885c>] __do_page_cache_readahead+0x1cc/0x270
[   43.392959] [<800f8f28>] page_cache_sync_readahead+0x60/0x6c
[   43.398634] [<800ed36c>] generic_file_read_iter+0x2b0/0xab0
[   43.404219] [<8012e748>] do_iter_readv_writev+0x13c/0x184
[   43.409610] [<801301c8>] do_iter_read+0xd0/0x220
[   43.414235] [<801316a8>] vfs_readv+0x5c/0x94
[   43.418494] [<80131744>] do_readv+0x64/0xd4
[   43.422670] [<8006fa6c>] syscall_common+0x34/0x58
[   43.427373] ---[ end trace adf40a121e187ade ]---
[   43.431980] eth1: tx timeout
[   50.733243] done.
[   50.735205] jffs2: notice: (1431) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
[   51.271405] overlayfs: upper fs does not support tmpfile.
[   74.113257] eth1: tx timeout
[  117.273206] random: crng init done
[  117.276611] random: 1 urandom warning(s) missed due to ratelimiting
`

**Comment by mkresin** [comment]
Due to merge conflicts, I had to rework parts of your PR. Would you please build and runtime test an image build from [my staging tree](https://git.openwrt.org/?p=openwrt/staging/mkresin.git;a=summary) to ensure I didn't broke anything.

**Comment by hanipouspilot** [comment]
@mkresin I built from your tree. I see no problems. Mac addresses are assigned correctly.

**Comment by hanipouspilot** [comment]
But I need to check if initvals for the switch are needed. Without them the switch doesn't come up fast enough.
But I looked into the switch specs, and I can't get what <0x06 0x0108> may mean.

**Comment by mkresin** [comment]
Closing the PR now and will push my staging tree soon.

**Comment by hanipouspilot** [comment]
Please don't forget to add the mysterious initvals
@mkresin

**Comment by chunkeey** [comment]
>[   43.153156] ------------[ cut here ]------------
[   43.157803] WARNING: CPU: 0 PID: 1612 at net/sched/sch_generic.c:320 dev_watchdog+0x164/0x274
[   43.166323] NETDEV WATCHDOG: eth1 (ag71xx): transmit queue 0 timed out
[   43.172828] Modules linked in: ath9k [..]
[   43.243600]  ehci_platform ehci_hcd gpio_button_hotplug usbcore nls_base usb_common mii
[   43.251604] CPU: 0 PID: 1612 Comm: luci Not tainted 4.14.61 #0
[   43.257428] Stack : 00000000 00000000 80637522 00000032 838dc2d4 804e78e7 804907f4 0000064c
[   43.265781]         80633670 00000140 804f2cf4 804f2cb4 804f2ca0 00000001 83809db8 735f66fe
[   43.274135]         00000000 00000000 80630000 00004990 00000000 00000000 00000007 00000000
[   43.282482]         000000ed 9f13a6c0 000000ec 00000000 80000000 00000000 804b7830 8030e0ac
[   43.290837]         00000009 00000140 804f2cf4 804f2cb4 00000001 8025d8e4 00000000 80630000
[   43.299194]         ...
[   43.301636] Call Trace:
[   43.431980] eth1: tx timeout


You could check out https://patchwork.ozlabs.org/patch/958091/ .

**Comment by hanipouspilot** [comment]
@chunkeey Build the latest master. Another patch is needed to fix this crash.

**Pull request closed without merging**
