### PR TITLE
Add and Upgrade upx to 3.95 version

### PR DESCRIPTION
**Pull request by lrinQVQ**
openwrt remove upx, because it hasn't been used for a very long time.
But now, openwrt supports programs generated by golang compilation.
The binary files generated by golang are usually larger,This is very 
unfriendly for small Flash, such as devices that use 16M Nor-flash.
Take obfs4proxy as an example, in the case of the arm cortex-a7 architecture:
Before using upx compression:
stat obfs4proxy 
  File: obfs4proxy
  Size: 4601396   	Blocks: 8992       IO Block: 4096   regular file
Device: 812h/2066d	Inode: 57541039    Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/    lrin)   Gid: ( 1000/    lrin)
Access: 2019-01-20 10:22:54.374115460 +0800
Modify: 2019-01-20 10:22:54.282118787 +0800
Change: 2019-01-20 10:22:54.286118642 +0800
 Birth: -

After using upx compression:
stat obfs4proxy 
  File: obfs4proxy
  Size: 2964736   	Blocks: 5792       IO Block: 4096   regular file
Device: 812h/2066d	Inode: 55968904    Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/    lrin)   Gid: ( 1000/    lrin)
Access: 2019-01-20 14:34:31.960947706 +0800
Modify: 2019-01-20 14:34:25.000000000 +0800
Change: 2019-01-20 14:34:31.888954625 +0800
 Birth: -

### CODE REVIEW

**Comment by dengqf6** [comment]
> The binary files generated by golang are usually larger

Because golang binaries use static linking instead of dynamic linking
If golang programs on OpenWrt can be built with dynamic linking, they will be much smaller

**Comment by lrinQVQ** [comment]
> > The binary files generated by golang are usually larger
> 
> Because golang binaries use static linking instead of dynamic linking
> If golang programs on OpenWrt can be built with dynamic linking, they will be much smaller

Yep, maybe we should consider implementing dynamic linking, but before that, I think using upx for compression might be a better solution.

**Comment by diizzyy** [comment]
Both ubifs and squashfs already uses compression so the gain isn't probably all that great if any at all.

**Comment by lrinQVQ** [comment]
upx compressed file affects the compression of squashfs
It seems that using upx is not as good as using ubifs or squashfs.
Using upx does not make much sense

Not compression obfs4proxy with upx:
df -h
Filesystem Size Used Available Use% Mounted on
/dev/root 7.8M 7.8M 0 100% /rom
tmpfs 59.1M 2.2M 56.9M 4% /tmp
/dev/ubi0_5 99.3M 3.1M 91.5M 3% /overlay
overlayfs:/overlay 99.3M 3.1M 91.5M 3% /
tmpfs 512.0K 0 512.0K 0% /dev

compression obfs4proxy with upx:
df -h
Filesystem Size Used Available Use% Mounted on
/dev/root 7.8M 7.8M 0 100% /rom
tmpfs 59.1M 2.2M 56.9M 4% /tmp
/dev/ubi0_5 99.3M 5.3M 89.3M 6% /overlay
overlayfs:/overlay 99.3M 5.3M 89.3M 6% /
tmpfs 512.0K 0 512.0K 0% /dev

**Comment by jefferyto** [comment]
I know I missed this whole conversation, but I wanted to add a note about dynamic linking. It wouldn’t necessarily save space for the first Go executable (since the staticly-linked library code would be replaced with a shared library that would also need to be installed), but subsequent Go executables can use the same shared library.

I’m not really sure how “supported” this use case would be, but it appears that [Go binaries built by Yocto / OpenEmbedded are dynamically linked](
https://itnext.io/getting-go-onto-internet-things-582396ff2760) to a runtime library by default. It may be possible to adapt how Yocto does it.

Unless there is a pressing need for dynamic linking though, I don’t have the time right now to investigate this 🙇

**Comment by dengqf6** [comment]
> but subsequent Go executables can use the same shared library.

That's what I mean :smiley:

**Pull request closed without merging**
