### PR TITLE
sysfixtime: always store/retrieve RTC as UTC normal value

### PR DESCRIPTION
**Pull request by pprindeville**
Cherry-picking 9e8e8b7253e9b91c365a990009febec16fd99f0b from LEDE.

### CODE REVIEW

**Comment by pprindeville** [comment]
@blogic, @nbd168, @jow-

**Comment by pprindeville** [comment]
Quoting hwclock(8):

```
   LOCAL vs UTC
       Keeping  the  Hardware  Clock  in a local timescale causes inconsistent
       daylight saving time results:

       · If Linux is running during a daylight saving time  change,  the  time
         written to the Hardware Clock will be adjusted for the change.

       · If  Linux  is  NOT  running during a daylight saving time change, the
         time read from the Hardware  Clock  will  NOT  be  adjusted  for  the
         change.

       The  Hardware  Clock  on an ISA compatible system keeps only a date and
       time, it has no concept of timezone  nor  daylight  saving.  Therefore,
       when  hwclock is told that it is in local time, it assumes it is in the
       'correct' local time and makes no adjustments to the time read from it.

       Linux handles daylight saving time changes transparently only when  the
       Hardware  Clock is kept in the UTC timescale. Doing so is made easy for
       system administrators as hwclock uses local time for its output and  as
       the argument to the --date option.

       POSIX  systems, like Linux, are designed to have the System Clock oper‐
       ate in the UTC timescale. The Hardware Clock's purpose is to initialize
       the System Clock, so also keeping it in UTC makes sense.

       Linux does, however, attempt to accommodate the Hardware Clock being in
       the local timescale. This is primarily for dual-booting with older ver‐
       sions  of  MS  Windows. From Windows 7 on, the RealTimeIsUniversal reg‐
       istry key is supposed to be working properly so that its Hardware Clock
       can be kept in UTC.
```

in particular, "_The Hardware Clock's purpose is to initialize the System Clock, so also keeping it in UTC makes sense._"

**Comment by pprindeville** [comment]
For what it's worth, LEDE does this already with commit [9e8e8b7253e](https://github.com/lede-project/source/commit/9e8e8b7253e9b91c365a990009febec16fd99f0b)

**Comment by ptpt52** [comment]
good job, this patch fix the problem

**Comment by pprindeville** [comment]
> good job, this patch fix the problem

Hopefully it will get merged soon!

**Comment by pprindeville** [comment]
@hnyman @wigyori

**Comment by blogic** [comment]
fix is already part of the LEDE tree which will replace the OWRT tree shortly

**Pull request closed without merging**
