### PR TITLE
kernel: mtd: backport upstream MX25L25635[E|F] fix to 4.19

### PR DESCRIPTION
**Pull request by dengqf6**
@chunkeey 
This patch removes the previous hack that was necessary
for the ZyXEL NBG6617:
303-spi-nor-enable-4B-opcodes-for-mx25l25635f.patch

And replaces it with the 5.0-rc1 solution. This will
likely also enable Compex WPJ428's that still use the
original SPL1/u-boot will now sucessfully reboot.

Move the fix to generic and refresh other patches

### CODE REVIEW

**Comment by neheb** [comment]
This requires dts changes, no?

In particular, broken-flash-reset.

**Comment by dengqf6** [comment]
No

**Comment by chunkeey** [comment]
Is nobody saying anything about the hackisch

 target/linux/generic/backport-4.19/043-v4.21-mtd-spi-nor-fix-fixup-npe-panic.patch 

because I wrote it? This was the main reason why I keep it in the staging repo.

**Comment by dengqf6** [comment]
@chunkeey 
So I should move the patch to hack-4.19 right?

**Comment by chunkeey** [comment]
Thing is, as @neheb pointed out 4.19 has bb276262e88dae52cc717bb636b7468f66bb234e so, for affected devices we could just add the "broken-flash-reset;" property and report the splat it causes to greg as well as the backport patches to "fix" it. It's kinda cheesy though.

**Comment by adrianschmutzler** [comment]
@dengqf6 Do you plan to proceed with this?

**Comment by dengqf6** [comment]
@adrianschmutzler
It was from @chunkeey 's staging tree. Since 4.19 has broken-flash-reset I don't think we need this now.

**Pull request closed without merging**
