### PR TITLE
mediatek: filogic: convert boards to use fitblk driver

### PR DESCRIPTION
**Pull request by dangowrt**
Instead of using the deprecated uImage.FIT partition parser, use the newly introduced fitblk driver instead.
- [x] MediaTek MT79861 RFB (requires U-Boot patch)
- [x] Zyxel EX5601-T0
- [x] Netcore N60
- [x] Xiaomi WR30U
- [x] Xiaomi AX3000T
- [x] Qihoo 360T7
- [x] JCG Q30 PRO
- [x] H3C Magic NX30 Pro

Did I miss any other board still using the partition parser?

### CODE REVIEW

**Comment by Gingernut1978** [comment]
Asus tuf-ax4200?

**Comment by dangowrt** [comment]
> Was the Asus tuf-ax4200 already converted?

It's not using uImage.FIT partition magic, but separate rootfs and kernel image with the stock loader, and `sysupgrade.tar` as sysupgrade format. In `target/linux/mediatek/image/filogic.mk` you can see that it misses the `with-rootfs` keyword.

**Comment by dangowrt** [comment]
@aiamadeus @981213 @dimfishr @ftp21 @ptpt52 @hank9999 Please review (and ideally also test) the boards you got.

**Comment by hank9999** [comment]
> @aiamadeus @981213 @dimfishr @ftp21 @ptpt52 @hank9999 Please review (and ideally also test) the boards you got.

I will test it recenetly asap.

**Comment by hank9999** [comment]
@dangowrt Hi, I have built a firmware based on your latest commit, it boot and work well, but when I upgrade firmware, it does not work as expected.
This is uart output 
image
may be I need to update `platform.sh` file

**Comment by hank9999** [comment]
It can be fixed by this commit https://github.com/hank9999/openwrt/commit/f46d31aa4614d4248db73ada88d2b682b1f8579f
image
Now, it works fine.

**Comment by dangowrt** [comment]
@hank9999 Thanks for pointing this out, I've fixed that for all devices now.

**Review by hank9999 — APPROVED** [review]

**Comment by hank9999** [comment]
> @hank9999 Thanks for pointing this out, I've fixed that for all devices now.

Thanks for your working, Xiaomi WR30U and AX3000T works well.

**Pull request merged**
