### PR TITLE
[22.03] firewall3: bump to latest git HEAD (backport)

### PR DESCRIPTION
**Pull request by looi**
Suggested backport for firewall3. Removes some hacks from firewall3 and improves compatibility with running openwrt in a container.

### CODE REVIEW

**Comment by Ansuel** [comment]
@looi can you add your Sob tag? 

Also can you move the cherry pick info thing at the top of the commit description?

**Comment by looi** [comment]
Done. I've tried to follow 52a64755fc39ea1ac03e255dbb48b325de8914cc for the commit description formatting.

**Comment by zorun** [comment]
Does this fix an actual bug in 22.03? Especially since we are using firewall4 by default in 22.03?

**Comment by hauke** [comment]
Thank you for the patch I applied it to openwrt 22.03 in cb9a69807ec20cdbd11648532432b7874d0d46d4.

**Pull request closed without merging**
