### PR TITLE
dropbear: update to 2024-86, more options with detailed help

### PR DESCRIPTION
**Pull request by ghost**
Changes:
- update to 2024-86
- new menuconfig structure
- added in menuconfig almost all available configuration options
- added dependencies for options (some are unavailable on musl)
- added warning messages for invalid config selections
- all options have detailed help descriptions
- removed or replaced all options that required editing sysoptions.h
- set the default OpenWrt RecvWindowSize option to 0, so that the value selected at build time in menuconfig will be used

Tested on mvebu / Turris Omnia
Tested on mvebu / WRT1900ACv1.
Tested various combinations of options.
Tested with musl in combination with this patch: https://github.com/openwrt/openwrt/pull/15417
Not tested with glibc, but shouldn't be any problems.

Notes:
- The menuconfig defaults are mostly what upstream defaults are. Notable exception:
**DROPBEAR_DH_GROUP14_SHA1 and RSA-SHA1 disabled, which may disable some old client keys!**
Please suggest new defaults if these seem inappropriate to you.

- The `Build/Configure/dropbear_headers` section looks really unreadable to me. I removed all need to edit sysoptions.h, but I didn't touch the functions that do that. They should be removed after this PR is merged.

Thanks.

### CODE REVIEW

**Comment by rockdrilla** [comment]
@M95D `Build/Configure/dropbear_headers` was an eligible choice to avoid repetitions in `Makefile` (ref: 79d5c247, e1bd9645 and f2b22936). :slightly_smiling_face:

**Comment by M95D** [comment]
Yes, I certainly understand the motivation - it's so much easier to add config options in those lists - it's just so difficult (at least for me) to understand the code that does the conversion.

**Comment by rockdrilla** [comment]
@M95D here's notes about your merge request.

`Makefile`
- bump `PKG_RELEASE` (to `2`)

`Config.in`
- remove pure `default n` lines - this is excessive
- set default `DROPBEAR_DEFAULT_RECV_WINDOW` to `262144` (ref commit f95eecfb)

misc:
- consider returning split ECC support (`CONFIG_DROPBEAR_ECC_FULL`)

**Comment by M95D** [comment]
`PKG_RELEASE` - OK, I forgot about that.
`default n` - I like things explicit. But if you insist, I'll remove them.
`DROPBEAR_DEFAULT_RECV_WINDOW` - OK
`CONFIG_DROPBEAR_ECC_FULL` - I'm not sure. Discussion:
1. The author didn't intend to make Dropbear configurable in that much detail. Quote: `You shouldn't edit this file unless you know you need to.`
2. As I understand it, the big increase in size when ECDSA is selected comes from the curve, not key size. I'll do some tests to see how big is the difference on arm.
3. Removing that and future removal of the ident mangling will simplify that conversion function I was complaining about.

I would like to read your arguments for keeping it.

**Comment by M95D** [comment]
When compiled for armv7a+vfpv3-d16
ChachaPoli1307 + SHA256HMAC + Ed25519 + Curve25519 = 143'699 B
+ ECDSA + ECDH "half" = 184'727 B (+41'028 B)
+ ECDSA + ECDH "full" = 188'947 B (+4'220 B)
ChachaPoli + SHA256HMAC + ECDSA + ECDH "full" (without *25519) = 180695 B (-8252 B)

If squashfs'ed, the difference between "half" and "full" is probably less than 2K. I don't think it's significant enough to keep it.

**Comment by M95D** [comment]
I made the changes:
- PKG_RELEASE 
- DROPBEAR_DEFAULT_RECV_WINDOW 
- DROPBEAR_VERSION instead of LOCAL_IDENT = didn't test this one yet.

**Comment by rockdrilla** [comment]
@M95D one more thought: `CONFIG_DROPBEAR_DEFAULT_RECV_WINDOW` value may differ from the one hardcoded in init script ([here](https://github.com/openwrt/openwrt/blob/4f87a4d84f3d6d1625962413ea56cca1ce83db7c/package/network/services/dropbear/files/dropbear.init#L181)) which leads to running custom Dropbear package with undesired setting.

My suggestion:

```diff
--- a/package/network/services/dropbear/Makefile
+++ b/package/network/services/dropbear/Makefile
@@ -224,6 +224,7 @@ define Package/dropbear/install
 	$(INSTALL_CONF) ./files/dropbear.config $(1)/etc/config/dropbear
 	$(INSTALL_DIR) $(1)/etc/init.d
 	$(INSTALL_BIN) ./files/dropbear.init $(1)/etc/init.d/dropbear
+	$(ESED) 's/^(DROPBEAR_DEFAULT_RECV_WINDOW=).$$/\1=$(CONFIG_DROPBEAR_DEFAULT_RECV_WINDOW)/' -n $(1)/etc/init.d/dropbear
 	$(INSTALL_DIR) $(1)/usr/lib/opkg/info
 	$(INSTALL_DIR) $(1)/etc/dropbear
 	$(INSTALL_DIR) $(1)/lib/preinit
--- a/package/network/services/dropbear/files/dropbear.init
+++ b/package/network/services/dropbear/files/dropbear.init
@@ -9,6 +9,7 @@ USE_PROCD=1
 PROG=/usr/sbin/dropbear
 NAME=dropbear
 PIDCOUNT=0
+DROPBEAR_DEFAULT_RECV_WINDOW=262144
 
 extra_command "killclients" "Kill ${NAME} processes except servers and yourself"
 
@@ -178,7 +179,7 @@ validate_section_dropbear()
 		'SSHKeepAlive:uinteger:300' \
 		'IdleTimeout:uinteger:0' \
 		'MaxAuthTries:uinteger:3' \
-		'RecvWindowSize:uinteger:262144' \
+		"RecvWindowSize:uinteger:${DROPBEAR_DEFAULT_RECV_WINDOW}" \
 		'mdns:bool:1'
 }
 
@@ -336,10 +337,14 @@ dropbear_instance()
 	[ "${IdleTimeout}" -ne 0 ] && procd_append_param command -I "${IdleTimeout}"
 	[ "${SSHKeepAlive}" -ne 0 ] && procd_append_param command -K "${SSHKeepAlive}"
 	[ "${MaxAuthTries}" -ne 0 ] && procd_append_param command -T "${MaxAuthTries}"
-	[ "${RecvWindowSize}" -gt 0 ] && {
+	# only apply receive window size if it differs from default value
+	while [ "${RecvWindowSize}" != "${DROPBEAR_DEFAULT_RECV_WINDOW}" ] ; do
+		[ "${RecvWindowSize}" -gt 0 ] || break
+
 		# NB: OpenWrt increases receive window size to increase throughput on high latency links
-		# ref: validate_section_dropbear()
-		# default receive window size is 24576 (DEFAULT_RECV_WINDOW in default_options.h)
+		# ref: DROPBEAR_DEFAULT_RECV_WINDOW and validate_section_dropbear()
+		# Dropbear default receive window size is 24576 (DEFAULT_RECV_WINDOW in default_options.h)
+		# OpenWrt default receive window size is 262144 (package/network/services/dropbear/Config.in)
 
 		# src/sysoptions.h
 		local MAX_RECV_WINDOW=10485760
@@ -352,7 +357,9 @@ dropbear_instance()
 			RecvWindowSize=${MAX_RECV_WINDOW}
 		fi
 		procd_append_param command -W "${RecvWindowSize}"
-	}
+
+		break
+	done
 	[ "${mdns}" -ne 0 ] && procd_add_mdns "ssh" "tcp" "$Port" "daemon=dropbear"
 	procd_set_param respawn
 	procd_close_instance
```

**Comment by M95D** [comment]
That looks very complicated. How about this:

Some selections from dropbear init:
```
uci_load_validate dropbear dropbear "$1" "$2" \
    'RecvWindowSize:uinteger:262144' \

[ "${RecvWindowSize}" -gt 0 ] && {
    <some checks>
    procd_append_param command -W "${RecvWindowSize}"
}
```
As I understand it, if the RecvWindowSize is set to 0, then the -W argument won't be set and the build-default will apply. We could only change `'RecvWindowSize:uinteger:262144' \` to `'RecvWindowSize:uinteger:0' \` to have the same effect when RecvWindowSize is not set in config? Am I correct?

**Comment by rockdrilla** [comment]
I could assume more "easier" version:

```sh
[ "${RecvWindowSize}" -gt 0 ] && [ "${RecvWindowSize}" != "${DROPBEAR_DEFAULT_RECV_WINDOW}" ] && {
    # code here
}
```

Nevertheless, I'd suggest setting `-W` only if it differs from default value.

PS: passing `-W 0` to Dropbear resets receive window size to default value.

**Comment by M95D** [comment]
I did some tests.
1) Changing just `'RecvWindowSize:uinteger:262144' \` to `'RecvWindowSize:uinteger:0' \` leads to init running Dropbear like this:
```
root@GRAPHRT:~# top -bn 1 | grep dropbear
28713 28663 root     S     1512   0%   0% grep dropbear
28662  1225 root     S     1132   0%   0% /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 10022 -s -a -g -K 300 -T 3
 1225     1 root     S     1112   0%   0% /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 10022 -s -a -g -K 300 -T 3
```
Note that there's no `-W`.

2) Setting `DROPBEAR_VERSION,""` in `DB_OPT_COMMON`, and removing `!!LOCAL_IDENT,"SSH-2.0-dropbear" \` leads to this ident:
```
TRACE1 (2869) 0.146639: remoteident: SSH-2.0-dropbear_
```
...which has an extra `_` compared to the old string, but it works, and there's no more need to do replacements in `sysoptions.h`.

I'm going to leave it like this.

**Comment by M95D** [comment]
I made the changes. Ready to merge.

**Comment by M95D** [comment]
> Nevertheless, I'd suggest setting `-W` only if it differs from default value.

I did consider it, but I stll don't like it.
If the user sets the window size in the config to the default value, then he/she will probably start top/htop to see if it was applied. With your proposed change, he/she will be confused why it wasn't applied. We are avoiding a bug report.

Just test this PR as it is. You'll see that it works as intended.

**Comment by rockdrilla** [comment]
@M95D please revert setting `DROPBEAR_VERSION` to empty string (`""`) and restore `LOCAL_IDENT` override.
Reason: `DROPBEAR_VERSION` is used not only in `LOCAL_IDENT` but in various messages too.

**Comment by M95D** [comment]
> `DROPBEAR_VERSION` is used not only in `LOCAL_IDENT` but in various messages too (e.g. `dropbear -V`).

Thanks for noticing that!
I added that as patch to `sysoptions.h` instead.

**Comment by rockdrilla** [comment]
@M95D there's no need to produce patches - `Build/Configure/dropbear_headers` will do the job.

```Makefile
DB_OPT_COMMON = \
  !!LOCAL_IDENT,"SSH-2.0-dropbear" \
```

**Comment by M95D** [comment]
You really love sed, don't you? :-)

Just wait a moment. Upstream will support defining ident version in localoptions.h. https://github.com/mkj/dropbear/pull/303

**Comment by rockdrilla** [comment]
@M95D I actually hate `sed`-ing especially multiline matches. xD

**Comment by M95D** [comment]
OK, the ident feature is upstream and temporarily added here as a patch until a new release is done.
There's no more need to edit sysoptions.h, but I left the editing functions untouched in `Build/Configure/dropbear_headers` because I really don't understand them.
@rockdrilla: Please edit / simplify those functions after this PR is merged. Thanks!

**Comment by M95D** [comment]
Updated to the new release from last week and rebased.
Patches removed; they are now included in upstream sources. No other changes.

**Comment by hauke** [comment]
Please split this into multiple commits.

**Comment by M95D** [comment]
Added some more binary size info for various options.

**Comment by rockdrilla** [comment]
personal config before this PR:
```sh
CONFIG_LIBC="glibc"
# CONFIG_LIBC_USE_MUSL is not set
CONFIG_USE_GLIBC=y
# CONFIG_USE_APK is not set

# CONFIG_DROPBEAR_AGENTFORWARD is not set
CONFIG_DROPBEAR_ASKPASS=y
# CONFIG_DROPBEAR_DBCLIENT_AGENTFORWARD is not set
CONFIG_DROPBEAR_MODERN_ONLY=y
# CONFIG_DROPBEAR_U2F is not set
```
personal config with this PR included:
```sh
CONFIG_LIBC="glibc"
# CONFIG_LIBC_USE_MUSL is not set
CONFIG_USE_GLIBC=y
# CONFIG_USE_APK is not set

# CONFIG_DROPBEAR_AES128 is not set
# CONFIG_DROPBEAR_AES256 is not set
CONFIG_DROPBEAR_CLI_ASKPASS_HELPER=y
# CONFIG_DROPBEAR_DH_GROUP14_SHA256 is not set
# CONFIG_DROPBEAR_ECDH is not set
# CONFIG_DROPBEAR_ECDSA is not set
# CONFIG_DROPBEAR_RSA is not set
# CONFIG_DROPBEAR_SK_KEYS is not set
```
Compile/run-tested: GL.iNet GL-MT6000 (mediatek/filogic).
```sh
# opkg list-installed | grep dropbear
dropbear - 2024.86-r1
# dropbear -V
Dropbear v2024.86
```
Verifying dropbear's SSH version:
```sh
$ ssh -vvv krdwrt
OpenSSH_9.9p1 Debian-3, OpenSSL 3.3.2 3 Sep 2024
...
debug1: Connection established.
debug1: Local version string SSH-2.0-OpenSSH_9.9p1 Debian-3
debug1: Remote protocol version 2.0, remote software version dropbear
debug1: compat_banner: no match: dropbear
...
```

@M95D it looks like MR is fine enough, thanks! :muscle:

**Comment by hauke** [comment]
> > Please split this into multiple commits to make it easier to review.
> 
> I really can't. It's basically a complete rewrite of Makefile and Config.in. Better review the new files, not the diff. For the Config.in, it's best if you look at it in the menuconfig.

You already list the different changes in the commit description, this could be individual commits:
> Changes:
- update to 2024-86
- new menuconfig structure
- added in menuconfig almost all available configuration options
- added dependencies for options (some are unavailable on musl)
- added warning messages for invalid config selections
- all options have detailed help descriptions
- removed or replaced all options that required editing sysoptions.h

especially the restructure of the menuconfig structure should be a separate commit not added new features or removing old ones.

**Comment by M95D** [comment]
It's too much work to rewrite all that again, and the reason you gave (ease of review) doesn't make any sense. It would be even harder to review it separate commits.

Like I said, just review the final result as if it was a new package, not the diff. I kept very little from the original Makefile and the Config.in is completely new - nothing was kept from the old one.

@rockdrilla:
All option names are taken from dropbear `default_options.h` file. I only added `DROPBEAR_` prefix if they didn't already had it, to avoid confusion. I didn't check if the new names match the old config or not.

**Comment by rockdrilla** [comment]
@M95D, just to be clear: I had to run `make nconfig` just to ensure that my personal OpenWrt/dropbear build behaves exactly like I want to. Hovewer, `make oldconfig` or `make olddefconfig` is good choice.

**Comment by rockdrilla** [comment]
@M95D please rebase MR against current git head.

**Comment by rockdrilla** [comment]
@M95D I don't mean to close MR but rather bump package version (1 -> 2).

**Comment by M95D** [comment]
Well, if hauke made the update himself instead of picking this PR, that means he rejected it.

It appears that there are not enough devs that can merge PRs and those few won't read PRs more than 3 lines long. I had many PRs, most trivial ones merged, most important ones completely ignored for years.

I'm going to act very immature now, pick up my toys and go home.

**Comment by ynezz** [comment]
@M95D https://google.github.io/eng-practices/review/developer/handling-comments.html

**Pull request closed without merging**
