### PR TITLE
[23.05] armsr: backport Renesas + Framebuffer dev from main

### PR DESCRIPTION
**Pull request by mcbridematt**
This set backports recent changes to armsr from the main branch

1. virtio-gpu fix from #15586 
2. Add SMSC + Realtek PHYs to default image packages from #15586
3. Renesas Ethernet module addition from #15539 
4. Enable Renesas serial driver from #14896

### CODE REVIEW

**Comment by mcbridematt** [comment]
@JohnXVincent Could you try this on your (Renesas) boards? It has the serial + Ethernet driver backported from the main branch

I have some pre-built images binaries here, if that helps: https://archive.traverse.com.au/pub/traverse/ls1088firmware/openwrt/branches/openwrt-23-05/1346474806/image/

**Comment by hauke** [comment]
It would be nice if someone could test this on a Renesas board. If none finds the time I would merge it even when you only tested it on some other armsr boards.

**Comment by mcbridematt** [comment]
Thanks for testing, @johnv. I do see a few new options in the 6.6 kernel being used on the main branch, 
5.15.x:
```
CONFIG_CLK_RENESAS=y
CONFIG_CLK_R8A774A1=y
CONFIG_CLK_R8A774B1=y
CONFIG_CLK_R8A774C0=y
CONFIG_CLK_R8A774E1=y
CONFIG_CLK_R9A07G044=y
CONFIG_CLK_RCAR_CPG_LIB=y
CONFIG_CLK_RCAR_GEN3_CPG=y
CONFIG_CLK_RCAR_USB2_CLOCK_SEL=y
CONFIG_CLK_RZG2L=y
CONFIG_CLK_RENESAS_CPG_MSSR=y
CONFIG_CLK_RENESAS_DIV6=y
```

6.6.x:
```
CONFIG_CLK_RENESAS=y
CONFIG_CLK_R8A774A1=y
CONFIG_CLK_R8A774B1=y
CONFIG_CLK_R8A774C0=y
CONFIG_CLK_R8A774E1=y
CONFIG_CLK_R9A07G043=y
CONFIG_CLK_R9A07G044=y
CONFIG_CLK_R9A07G054=y
CONFIG_CLK_R9A09G011=y
CONFIG_CLK_RCAR_CPG_LIB=y
CONFIG_CLK_RCAR_GEN3_CPG=y
CONFIG_CLK_RCAR_USB2_CLOCK_SEL=y
CONFIG_CLK_RZG2L=y
CONFIG_CLK_RENESAS_CPG_MSSR=y
CONFIG_CLK_RENESAS_DIV6=y
```

**Comment by JohnXVincent** [comment]
Hi @mcbridematt 

Yes, Additional Renesas boards added in newer kernel version 6.6.x

Best Regards
John

**Comment by JohnXVincent** [comment]
Hi @mcbridematt 

Yes, Additional Renesas boards added in newer kernel version 6.6.x

Best Regards
John

**Pull request merged**
