### PR TITLE
ath79: initial RB91x support

### PR DESCRIPTION
**Pull request by silverchris**
Some very rough work on getting the RB91x platform ported to Ath79/Device Tree
Currently, it is bootable, NAND access works, USB, and Ethernet works.
WLAN is not working, as I haven't been able to fully unwind how ATH79_IP2_IRQ works, as well as the reset controller for it.
Need to figure out how to get the mac addresses set correctly as well, but I haven't really look at that yet. 

I made a brief attempt at getting the mpcie slot working, but haven't got that figured out yet.

Probably a lot of cleanup needed as well, as it's been a few years since I did any work like this.

### CODE REVIEW

**Comment by juppin** [comment]
There is already support for ahb wifi...

https://github.com/openwrt/openwrt/commit/83fb9ec5e0d175f99286dacda2f68c776c203f88

**Comment by silverchris** [comment]
I missed the ath9k device tree patches, didn't realize the kernel modules were built separately from the kernel.

The RB911/RB912 do use NAND, and are based on the ar9342, the NAND is connected to the GPIO pins.

I had to add an option to the ath9k device tree configuration to allow loading the cal data from a file on the filesystem. 

I need to package up the little program I adapted from https://github.com/openwrt/openwrt/blob/master/target/linux/ar71xx/files/arch/mips/ath79/routerboot.c that extracts the ath9k cal data from the routerboot hard config partition. This might be useful for other Mikrotik router boards as well, I just don't have any other ones to test with.

As it is right now, I have wifi working. I need to look at the interrupt cascade drivers still. 
I also need to look into gpio-export, I played with that a bit, but due to the exports being on the 74x164 attached to the SPI bus, I was running into some ordering issues

**Comment by 981213** [comment]
@juppin I'd tried the irq cascade driver from @blogic for ar9344 (I added ath79_ddr_wb_flush for it) but it's not working. The device stuck when I try to enable wifi. After adding printk to the IRQ handler of the cascade driver it seemed that the handler keeps executing again and again and I have no idea why this happened.
The original cascade driver was also tested on qca9563 and the device also stuck when enabling wifi.

**Comment by juppin** [comment]
Yeah, that is the same behavior that others and i had with this cascade driver...
Oddly enough, others had success with that driver for the IP3 interrups of usb and pcie on qca95xx.

**Comment by silverchris** [comment]
@juppin @981213 
I have been doing some playing with the IRQ cascade driver from https://github.com/openwrt/openwrt/blob/master/target/linux/ath79/patches-4.14/0007-irqchip-irq-ath79-intc-add-irq-cascade-driver-for-QC.patch

It seems it calls the ath9k interrupt handler once, and then after that get stuck in a loop. 
My modified irq-ath79-intc.c https://gist.github.com/silverchris/43f059cbe246763a5c1a6e4866f651aa
serial console output https://gist.github.com/silverchris/f10dd897e459fbb6962ea094be76b0d6

**Comment by 981213** [comment]
@blogic @juppin @silverchris 
I added enable and disable function for irqchip like this:
```

static void ath79_intc_irq_enable(struct irq_data *d)
{
	printk("ENABLE %d %lu\n", d->irq, d->hwirq);
	dump_stack();
}

static void ath79_intc_irq_disable(struct irq_data *d)
{
	printk("DISABLE %d %lu\n", d->irq, d->hwirq);
	dump_stack();
}

static void ath79_intc_irq_unmask(struct irq_data *d)
{
	printk("UNMASK %d %lu\n", d->irq, d->hwirq);
	dump_stack();
}

static void ath79_intc_irq_mask(struct irq_data *d)
{
	printk("MASK %d %lu\n", d->irq, d->hwirq);
	dump_stack();
}
```
```
	intc->chip = dummy_irq_chip;
	intc->chip.name = "INTC";
	intc->chip.irq_disable = ath79_intc_irq_disable;
	intc->chip.irq_enable = ath79_intc_irq_enable;
	intc->chip.irq_unmask = ath79_intc_irq_unmask;
	intc->chip.irq_mask = ath79_intc_irq_mask;
```
and I found that there is a call to the disable function:
```
[   27.126463] INTSTAT_REG 0x00000001
[   27.129909] PENDING_MASK 0x000001FF
[   27.133447] GOT_PENDING_IRQ 1
[   27.136457] HANDLE_ENTER HWIRQ 11
[   27.139820] MASK 11 1
[   27.142132] CPU: 0 PID: 1140 Comm: hostapd Not tainted 4.14.48 #0
[   27.148310] Stack : 00000000 00000000 80637502 00000035 87efde54 804e18e7 8048a6f8 00000474
[   27.156800]         80633660 804f0a70 87c03700 8049f72c 8049f718 00000001 87c09e60 c533cc05
[   27.165283]         00000000 00000000 80630000 000031d8 00000000 00000000 00000007 00000000
[   27.173767]         000000b3 9c6c00b2 000000b2 00000000 80000000 87c0499c 00000001 804eadac
[   27.182250]         87c04900 804f0a70 87c03700 8049f72c 00000000 8025cce4 00000000 80630000
[   27.190732]         ...
[   27.193215] Call Trace:
[   27.195726] [<8006a86c>] show_stack+0x58/0x100
[   27.200260] [<800b2d4c>] mask_irq.part.2+0x28/0x54
[   27.205122] [<800b2ee4>] handle_level_irq+0x60/0x154
[   27.210164] [<800af0a0>] generic_handle_irq+0x38/0x50
[   27.215310] [<8020d4e4>] ath79_intc_irq_handler+0x154/0x1ec
[   27.220961] [<800af0a0>] generic_handle_irq+0x38/0x50
[   27.226102] [<803f8f8c>] do_IRQ+0x1c/0x2c
[   27.230176] [<8020d330>] plat_irq_dispatch+0xc0/0x120
[   27.235303] [<800658b8>] handle_int+0x138/0x144
[   27.239938] [<8771ccec>] ath9k_hw_kill_interrupts+0x208/0x250 [ath9k_hw]
[   27.246766] [<87765398>] ath9k_calculate_summary_state+0x45c/0x644 [ath9k]
[   27.253751] CPU: 0 PID: 1140 Comm: hostapd Not tainted 4.14.48 #0
[   27.259927] Stack : 00000000 00000000 80637502 00000035 87efde54 804e18e7 8048a6f8 00000474
[   27.268419]         80633660 804eb2cc 8048e444 804f0000 00000001 00000000 87c09dc0 c533cc05
[   27.276902]         00000000 00000000 80630000 000036f0 00000000 00000000 00000007 00000000
[   27.285386]         000000c6 fcb75d9a 000000c5 00000000 80000000 876f5460 00000000 87c09eec
[   27.293868]         0000000b 804eb2cc 8048e444 804f0000 00000000 8025cce4 00000000 80630000
[   27.302352]         ...
[   27.304834] Call Trace:
[   27.307317] [<8006a86c>] show_stack+0x58/0x100
[   27.311834] [<877647e0>] ath_isr+0x28/0x2b4 [ath9k]
[   27.316793] [<800afa44>] __handle_irq_event_percpu+0x78/0x184
[   27.322620] [<800afb70>] handle_irq_event_percpu+0x20/0x64
[   27.328190] [<800afbf0>] handle_irq_event+0x3c/0x6c
[   27.333146] [<800b2f94>] handle_level_irq+0x110/0x154
[   27.338274] [<800af0a0>] generic_handle_irq+0x38/0x50
[   27.343407] [<8020d4e4>] ath79_intc_irq_handler+0x154/0x1ec
[   27.349062] [<800af0a0>] generic_handle_irq+0x38/0x50
[   27.354188] [<803f8f8c>] do_IRQ+0x1c/0x2c
[   27.358258] [<8020d330>] plat_irq_dispatch+0xc0/0x120
[   27.363380] [<800658b8>] handle_int+0x138/0x144
[   27.367987] [<8771ccec>] ath9k_hw_kill_interrupts+0x208/0x250 [ath9k_hw]
[   27.374800] [<87765398>] ath9k_calculate_summary_state+0x45c/0x644 [ath9k]
[   27.381787] UNMASK 11 1
[   27.384270] CPU: 0 PID: 1140 Comm: hostapd Not tainted 4.14.48 #0
[   27.390441] Stack : 00000000 00000000 80637502 00000035 87efde54 804e18e7 8048a6f8 00000474
[   27.398932]         80633660 804f0a70 87c03700 8049f72c 8049f718 00000000 87c09e60 c533cc05
[   27.407415]         00000000 00000000 80630000 00003cf0 00000000 00000000 00000007 00000000
[   27.415898]         000000dd c841947c 000000dc 00000000 80000000 00000000 00000001 804eadac
[   27.424381]         87c04900 804f0a70 87c03700 8049f72c 00000000 8025cce4 00000000 80630000
[   27.432865]         ...
[   27.435347] Call Trace:
[   27.437839] [<8006a86c>] show_stack+0x58/0x100
[   27.442357] [<800b2e54>] unmask_irq.part.4+0x28/0x58
[   27.447395] [<800b2fc4>] handle_level_irq+0x140/0x154
[   27.452524] [<800af0a0>] generic_handle_irq+0x38/0x50
[   27.457650] [<8020d4e4>] ath79_intc_irq_handler+0x154/0x1ec
[   27.463304] [<800af0a0>] generic_handle_irq+0x38/0x50
[   27.468430] [<803f8f8c>] do_IRQ+0x1c/0x2c
[   27.472501] [<8020d330>] plat_irq_dispatch+0xc0/0x120
[   27.477629] [<800658b8>] handle_int+0x138/0x144
[   27.482238] [<8771ccec>] ath9k_hw_kill_interrupts+0x208/0x250 [ath9k_hw]
[   27.489053] [<87765398>] ath9k_calculate_summary_state+0x45c/0x644 [ath9k]
[   27.496024] HANDLER_RET 0
[   27.498681] HANDLE_EXIT
[   27.501154] IRQ_EXIT
[   27.503948] DISABLE 11 1
[   27.506535] CPU: 0 PID: 1140 Comm: hostapd Not tainted 4.14.48 #0
[   27.512709] Stack : 00000000 00000000 80637502 00000035 87efde54 804e18e7 8048a6f8 00000474
[   27.521199]         80633660 874d2010 874d2268 877c6460 00000000 00000001 8709db68 c533cc05
[   27.529682]         00000000 00000000 80630000 00004288 00000000 00000000 00000007 00000000
[   27.538166]         000000f4 8dfa5438 000000f3 00000000 80000000 876f5df8 874d2268 876f4b80
[   27.546648]         00000000 874d2010 874d2268 877c6460 00000000 8025cce4 00000000 80630000
[   27.555131]         ...
[   27.557614] Call Trace:
[   27.560116] [<8006a86c>] show_stack+0x58/0x100
[   27.564642] [<800b2ddc>] __irq_disable+0x64/0xb4
[   27.569329] [<800afff4>] __disable_irq_nosync+0x3c/0x68
[   27.574634] [<800b003c>] disable_irq+0x14/0x38
[   27.579164] [<877653fc>] ath9k_calculate_summary_state+0x4c0/0x644 [ath9k]
[   27.594460] IRQ ENTR
[   27.596691] INTSTAT_REG 0x00000001
[   27.600137] PENDING_MASK 0x000001FF
[   27.603675] GOT_PENDING_IRQ 1
[   27.606685] HANDLE_ENTER HWIRQ 11
[   27.610046] HANDLER_RET 0
[   27.612702] HANDLE_EXIT
[   27.615175] IRQ_EXIT
```
the irq driver in QSDK kernel do have an enable and disable function defined:
```

static void ath79_ip2_disable(struct irq_data *data)
{
	disable_irq(ATH79_CPU_IRQ(2));
}

static void ath79_ip2_enable(struct irq_data *data)
{
	enable_irq(ATH79_CPU_IRQ(2));
}

static void ath79_ip3_disable(struct irq_data *data)
{
	disable_irq(ATH79_CPU_IRQ(3));
}

static void ath79_ip3_enable(struct irq_data *data)
{
	enable_irq(ATH79_CPU_IRQ(3));
}
```
```
void __init arch_init_irq(void)
{
	ip2_chip = dummy_irq_chip;
	ip2_chip.irq_disable = ath79_ip2_disable;
	ip2_chip.irq_enable = ath79_ip2_enable;

	ip3_chip = dummy_irq_chip;
	ip3_chip.irq_disable = ath79_ip3_disable;
	ip3_chip.irq_enable = ath79_ip3_enable;

```
So I think this may be the problem. I'll have a test now.

**Comment by 981213** [comment]
BTW other print in the dmesg I posted above is in the irqhandler function:
```
static void ath79_intc_irq_handler(struct irq_desc *desc)
{
	struct irq_domain *domain = irq_desc_get_handler_data(desc);
	struct irq_chip *chip = irq_desc_get_chip(desc);
	struct ath79_intc *intc = domain->host_data;
	u32 pending;

	printk("IRQ ENTR\n");
	chained_irq_enter(chip, desc);
	pending = ath79_reset_rr(intc->int_status);
	printk("INTSTAT_REG 0x%08X\n", pending);
	pending &= intc->pending_mask;
	printk("PENDING_MASK 0x%08X\n",intc->pending_mask);

	if (pending) {
		int i;

		for (i = 0; i < domain->hwirq_max; i++)
			if (pending & intc->irq_mask[i]) {
				printk("GOT_PENDING_IRQ %d\n",i);
				if (intc->if_ddr_wb_flush)
					ath79_ddr_wb_flush(intc->ddr_wb_flush[i]);
				printk("HANDLE_ENTER HWIRQ %d\n", irq_find_mapping(domain, i));
				printk("HANDLER_RET %d\n", generic_handle_irq(irq_find_mapping(domain, i)));
				printk("HANDLE_EXIT\n");
			}
	} else {
		printk("WRONG_IRQ\n");
		spurious_interrupt();
	}
	chained_irq_exit(chip, desc);
	printk("IRQ_EXIT\n");
}
```

**Comment by 981213** [comment]
Everything works fine after adding enable and disable function as follow:
```
static void ath79_intc_irq_enable(struct irq_data *d)
{
	struct ath79_intc *intc = d->domain->host_data;
	enable_irq(intc->irq);
}

static void ath79_intc_irq_disable(struct irq_data *d)
{
	struct ath79_intc *intc = d->domain->host_data;
	disable_irq(intc->irq);
}
```
I'll create a PR later.

**Comment by silverchris** [comment]
Yup, Seems to be working here for the wireless using the interrupt cascade

Tried putting a card in the MPCIE connector on my board, and with or without the IRQ cascade driver, it kernel panics with a data bus error [kernel output](https://gist.github.com/silverchris/14e61639ba60ab29274afe2079ee6f6c)

Relevent device tree
```
&apb {
        pcie: pcie-controller@180c0000 {
                compatible = "qcom,ar7240-pci";
                #address-cells = <3>;
                #size-cells = <2>;
                bus-range = <0x0 0x0>;
                reg = <0x180c0000 0x1000>, /* CRP */
                                <0x180f0000 0x100>, /* CTRL */
                                <0x14000000 0x1000>; /* CFG */
                reg-names = "crp_base", "ctrl_base", "cfg_base";
                ranges = <0x2000000 0 0x10000000 0x10000000 0 0x04000000 /* pci memory */
                                0x1000000 0 0x00000000 0x0000000 0 0x000001>; /* io space */
                interrupt-parent = <&intc2>;
                interrupts = <0>;

                interrupt-controller;
                #interrupt-cells = <1>;

                interrupt-map-mask = <0 0 0 1>;
                interrupt-map = <0 0 0 0 &pcie 0>;

                status = "okay";
        };
};
```

**Comment by juppin** [comment]
PCIE and SoC Wifi on WDR3600/4300 works great with the fixed intc driver in master.
Remove the intc commits, rebase on master and try again...

**Comment by silverchris** [comment]
Figured out the PCIE issue... Turns out that when the 74x164 gets initialized, it turns off all it's outputs, which turns off power to the PCIE port, and I guess that makes the PCIE bus a little unhappy! :)

Will cleanup and commit my patch for that tomorrow

**Comment by silverchris** [comment]
Everything appears to be working now. I just need to work on the flashing process with sysupgrade.

I am also not terribly sure on how to name these, but it looks like from the rest of the dts files, they are named for one specific model only?

This should support the RB911G-2HPnD, RB911G-5HPnD, and RB912UAG-5HPnD with little to no changes. 
As far as I know, the RB911G both just have less ram, and no PCIE slot, and the RB912UAG-5HPnD is just the 5ghz variant.

**Comment by mkresin** [comment]
I stumbled over this PR and found a lot of formal issues. For all your commits the following is missing:

- Signed-off-by
- the prefix in the commit title
- commit message

If your search the internet, you will find a lot of post on how a good commit message should look like. IMHO, the three most important points are:

A good commit message should answer three questions about a patch:

-    Why is it necessary? It may fix a bug, it may add a feature, it may improve performance, reliabilty, stability, or just be a change for the sake of correctness.
-   How does it address the issue? For short obvious patches this part can be omitted, but it should be a high level description of what the approach was.
-  What effects does the patch have? (In addition to the obvious ones, this may include benchmarks, side effects, etc.)

Or in other words, convince us that we want to have his commit.

**Comment by silverchris** [comment]
@mkresin I will hopefully have some free time later this week, and should be able to get it polished up. I don't get the chance to contribute to projects very often, so I appreciate the feedback!

**Comment by blogic** [comment]
@silverchris please reopen the PR once you managed to cleanup the patches

**Pull request closed without merging**
