### PR TITLE
armsr: armv8: Enable KASLR in kernel 6.1

### PR DESCRIPTION
**Pull request by jetm**
In userspace, ASLR is enabled, but it's missing to enable KASLR on the kernel side to improve security as part of SystemReady recommendations.

### CODE REVIEW

**Comment by jetm** [comment]
@hauke @mcbridematt Could you review this change?

**Comment by mcbridematt** [comment]
Typo in the commit message: `s/ASRL/ASLR/`

Looks good to me otherwise.

**Comment by linusw** [comment]
The Kconfig options that you activate are not available on ARMv7 (which does not support KASLR).
However on Aarch64/ARM64 it is a well supported and stable feature.
Please patch this into armv8/config-6.1 instead.

**Comment by jetm** [comment]
@hauke 
> Are you aware of any compatibility problem? A colleague of mine tried to activate this option on a MIPS SoC some time ago and it was a challenging task to make the SoC boot up again. I assume that ARM64 SR is not that constrained, but I would like to know if there are any known problems.

I am not aware of that compatibility problem on a MIPS SoC. Like @linusw mentioned, this feature is stable on the ARM64 side. Maybe the MIPS SoC needs more support from the kernel side.

@linusw Thank you for your comments and suggestions. I moved the changes to the `armv8/config-6.1` file and updated the commit message to show this change only affects ARM64.

**Comment by linusw** [comment]
Looks good to me now: approved.

**Review by linusw — APPROVED** [review]

**Pull request merged**
