### PR TITLE
ipq806x: reduce pci IO space to 64k

### PR DESCRIPTION
**Pull request by Ansuel**
With some talk with the ARM maintainer, it was notice that enlarging the limit to the current value is VERY wrong and clash with other memory. A better solution would be to reduce the IO space from 1MB to 64K as probably it's a long lasting typo and even x86 arch doesn't have a IO space that big.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

@ynezz can you check this when you can?

### CODE REVIEW

**Comment by adschm** [comment]
Commit message needs to be wrapped.

**Comment by pkgadd** [comment]
Tested for the last ~2 days on my nbg6817, seems to work (no negative side effects visible).

**Comment by rbpp** [comment]
Tested on C2600 and R7800. Both working fine.

**Comment by nicklowe** [comment]
Tested for a while too, appears to work fine.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master.

**Pull request closed without merging**
