### PR TITLE
cmake : Remove irrelevant QT Tests to let cmake compile properly

### PR DESCRIPTION
**Pull request by grosjo**
As mentioned in the title

### CODE REVIEW

**Comment by ynezz** [comment]
Missing commit description, include the important part of the error message.

**Comment by ynezz** [comment]
commit subject should be `cmake:`

**Comment by grosjo** [comment]
done

**Comment by grosjo** [comment]
fixed

**Comment by grosjo** [comment]
@ynezz : what else ?

**Comment by adrianschmutzler** [comment]
You should remove the space before the colon in your commit title and make the word after it lower case ("Remove"->"remove").

In your commit message, you should describe how you fix the linked bug and why that's a good solution.

**Comment by ynezz** [comment]
> what else ?

* add proper commit description, I don't consider `Fixes #bugnumber` as a proper commit description
* you can link to the bug url though, but adding FS#2693 is enough, no need to duplicate the same information twice.

```
cmake: remove irrelevant QT Tests to let cmake compile properly

   ... add proper commit description here...

Fixes: FS#2693
Signed-off-by: Joan Moreau <jom@grosjo.net>
```

BTW I still don't understand what is wrong, what are you trying to fix, so you probably should add following to your bug report:

1. Add version information of your Linux distribution
2. Attach your config (output of `./scripts/diffconfig`)
3. Include steps needed to reproduce the problem, so anyone interested can copy&paste those instructions into the Docker container with your Linux distribution version defined in 1. and reproduce the issue

**Comment by grosjo** [comment]
what is wrong is that OpenWrt just does not compile anymore without this 
patch (QT5 testing fails)

**Comment by ynezz** [comment]
As stated in the [FS#2693](https://bugs.openwrt.org/index.php?do=details&task_id=2693) I'm not able to reproduce the issue, so I'm closing this PR as well.

**Comment by grosjo** [comment]
The OPenWrt just does NOT compile without it ! How come you close this PR ???

**Comment by bobafetthotmail** [comment]
OpenWrt compiles fine on OpenSUSE and Debian and also in his Arch Linux container test.

Maybe there is an issue in your system.

**Comment by grosjo** [comment]
No, it does not compile in any Archlinux system I have (using 'testing'
repo) 

On 2020-01-07 11:56, Alberto Bursi wrote:

> OpenWrt compiles fine on OpenSUSE and Debian and also in his Arch Linux container test. 
> 
> Maybe there is an issue in your system. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/openwrt/openwrt/pull/2643?email_source=notifications&amp;email_token=AAROMB7ABZLYSZZ6EUH2NQLQ4RNVNA5CNFSM4J6ZVF7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIIPXDA#issuecomment-571538316
[2]

**Pull request closed without merging**
