### PR TITLE
mvebu: add support for Fortinet FortiGate/FortiWiFi 30E/5xE devices

### PR DESCRIPTION
**Pull request by musashino205**
This PR adds support for Fortinet FortiGate 52E.

50E + 2x mSATA SSD = 52E

### CODE REVIEW

**Comment by musashino205** [comment]
I'm working to add an additional dtsi for FortiGate 5xE series...

**Comment by musashino205** [comment]
UPDATE:

- add dtsi for FortiGate 5xE series devices

**Comment by RaylynnKnight** [comment]
Are you interested in adding support for additional Fortinet devices based on the same OEM device (Gemtek WRTM-320N) used in the devices you have already added?  If so I would be willing to provide data and testing for the devices I have.  I have the following devices:

- FG-30E (FortiGate 30E)
- FWF-30E (FortiWiFi 30E) adds MiniPCIe WiFi to FG-30E
- FG-50E (FortiGate 50E)
- FWF-51E (FortiWifi 51E) adds MiniPCIe WiFi and mSATA to FG-50E

I also have an FWF-50E-2R which uses a slightly different base board (GemTek WRTM-319N), but may otherwise be compatible.  
- FWF-50E-2R (FortiWiFi 50E-2R) adds 2x MiniPCIe WiFi to FG-50E

**Comment by musashino205** [comment]
Oh, interesting... I'll add commits for additional FortiGate/FortiWiFi devices :)

**Comment by RaylynnKnight** [comment]
> Oh, interesting... I'll add commits for additional FortiGate/FortiWiFi devices :)

I've added entries to [WikiDevi](https://wikidevi.wi-cat.ru) for the devices I have.   

- [FG-30E](https://wikidevi.wi-cat.ru/Fortinet_FortiGate-30E_(FG-30E))
- [FWF-30E](https://wikidevi.wi-cat.ru/Fortinet_FortiWifi-30E_(FWF-30E))
- [FG-50E](https://wikidevi.wi-cat.ru/Fortinet_FortiGate-50E_(FG-50E))
- [FWF-50E-2R](https://wikidevi.wi-cat.ru/Fortinet_FortiWifi_50E-2R_(FWF-50E-2R))
- [FWF-51E](https://wikidevi.wi-cat.ru/Fortinet_FortiWifi-51E_(FWF-51E))

**Comment by musashino205** [comment]
UPDATE:

- separate common parts to new dtsi for FortiGate/FortiWiFi 3xE
- add support of FortiWiFi devices for testing
  - FortiWiFi 30E
  - FortiWiFi 50E-2R
  - FortiWiFi 51E

### known issues:

- the GPIO pin of "WiFi" LED on FortiWiFi 30E/51E is unknown

### Please test:

- availability of "WIFI1" and "WIFI2" LEDs on FortiWiFi 50E-2R
- LED-WLAN binding of "WIFI1" and "WIFI2" on FortiWiFi 50E-2R
  - green:wifi1 <--> phy1tpt, green:wifi2 <--> phy0tpt   <=== are these correct?

**Comment by musashino205** [comment]
UPDATE:

- drop kmod-ath9k from FWF-50E-2R

**Comment by musashino205** [comment]
UPDATE:

- improve commit title of separating dtsi for FortiGate/FortiWiFi 5xE

**Comment by RaylynnKnight** [comment]
> ### Please test:
> 
>     * availability of "WIFI1" and "WIFI2" LEDs on FortiWiFi 50E-2R
> 
>     * LED-WLAN binding of "WIFI1" and "WIFI2" on FortiWiFi 50E-2R
>       
>       * green:wifi1 <--> phy1tpt, green:wifi2 <--> phy0tpt   <=== are these correct?

Initial testing shows both WiFi LEDs on.  However radio0 activates the LED labeled WiFi2 5GHz, and radio1 activates the LED labeled WiFi1 2.4GHz.  Is there anything else you'd like me to check on the 50E-2R?

**Comment by musashino205** [comment]
> Initial testing shows both WiFi LEDs on. However radio0 activates the LED labeled WiFi2 5GHz, and radio1 activates the LED labeled WiFi1 2.4GHz. Is there anything else you'd like me to check on the 50E-2R?

Thank you for the testing. If you set the brightness of "green:wifi1" and "green:wifi2" to 1, will the each LED light up?

**Comment by RaylynnKnight** [comment]
> 
> Thank you for the testing. If you set the brightness of "green:wifi1" and "green:wifi2" to 1, will the each LED light up?
> 
> And also, can you investigate the GPIO pin of "WiFi" LED on FWF-30E/51E by manipulating gpio?

Hope I didn't confuse you.  On initial install both wifi LEDs were unlit.  Enabling radio0 causes LED labeled WiFi2 5GHz to light, enabling radio1 causes LED labeled WiFi1 2.4GHz to light.   When WiFi is disabled and LEDs are unlit the following commands have no effect:

root@OpenWrt:/# echo 1 > /sys/devices/platform/gpio-leds/leds/green:wifi1/brightness 
root@OpenWrt:/# echo 1 > /sys/devices/platform/gpio-leds/leds/green:wifi2/brightness 

I'll try to find time this weekend to test the FWF-30E and FWF-51E.  FYI there is also an FWF-50E (no -2R) which has only a single WiFi similar to the FWF-30E.  I don't have it, so don't know which WiFi it uses.

**Comment by musashino205** [comment]
Thank you for your detailed explanation! I got it.

> I'll try to find time this weekend to test the FWF-30E and FWF-51E.

Thank you!

> FYI there is also an FWF-50E (no -2R) which has only a single WiFi similar to the FWF-30E. I don't have it, so don't know which WiFi it uses.

I'm also interested in that model. However, I don't have that too, so I'm going to postpone adding support this time :)

**Comment by RaylynnKnight** [comment]
Just acquired another device.  An FG-51E which is similar to the FG-50E with the addition of a 32GB mSATA card accessible from the bottom of the device.  I'll be adding a WikiDevi entry for it sometime this weekend.

**Comment by RaylynnKnight** [comment]
> UPDATE:
> 
>     * separate common parts to new dtsi for FortiGate/FortiWiFi 3xE
> 
>     * add support of FortiWiFi devices for testing
>       
>       * FortiWiFi 30E

After system boots with openwrt-mvebu-cortexa9-fortinet_fwf-30e-initramfs-kernel.bin there is no access to any network ports.  The ifconfig command only lists lo (the loopback interface).  Not sure what to check here, but if you have any suggestions I'm willing to test further.  Attached below is a log of the session which shows issues similar to `error -19 setting up PHY for tree 0, switch 0, port 0` for each port.

[FWF-30E.log](https://github.com/openwrt/openwrt/files/13848250/FWF-30E.log)

**Comment by RaylynnKnight** [comment]
> UPDATE:
> 
>     * separate common parts to new dtsi for FortiGate/FortiWiFi 3xE
> 
>     * add support of FortiWiFi devices for testing
>       
>       * FortiWiFi 51E
> 

For the 51E I was able to successfully install.  I then enabled the WiFi which caused the WiFi LED to then light.  After installing additional software I was able to mount the mSATA SSD which appears as sda1 and was also able to mount a USB3 disk at sdb1 using the front USB port.  Let me know if you want me to provide any other details or run any other tests.  Please feel free to add my Tested By for both the FortiWiFi 51E and FortiWiFi 50E-2R.

**Comment by musashino205** [comment]
> After system boots with openwrt-mvebu-cortexa9-fortinet_fwf-30e-initramfs-kernel.bin there is no access to any network ports.

Hmmm, I have no idea about it now... I'll check on my FG-30E...

> I then enabled the WiFi which caused the WiFi LED to then light.

Oh, really? I didn't defined "WiFi" LED, so it's not controlled by SoC GPIO... The same may be true for 50E-2R.
I'll drop definitions of "wifiN" LEDs from 50E-2R, then, can you test "WiFiN" LEDs on 50E-2R?

> Please feel free to add my Tested By for both the FortiWiFi 51E and FortiWiFi 50E-2R.

Of course! I'll add your Tested-by tag to FWF commits ;)

**Comment by musashino205** [comment]
UPDATE:

- drop "wifiN" LEDs from FWF-50E-2R

**Comment by musashino205** [comment]
UPDATE:

- rebase from current main branch
- add support for FortiGate 51E

I tested on my FortiGate 30E for checking switch, but it was detected and worked without any issue. Hmm...

**Comment by musashino205** [comment]
@RaylynnKnight Can you test on your FG-51E?

**Comment by RaylynnKnight** [comment]
> @RaylynnKnight Can you test on your FG-51E?

Testing on FG-51E is successful.  Still having issue with the FWF-30E.  I also have an FG-30E which functions correctly.

**Comment by musashino205** [comment]
Thank you for testing :)
Hmmmm, I have no idea about switch on FWF-30E... Can we go without FWF-30E on this PR?

And, can you check availability of "WIFI1" and "WIFI2" LED on your FWF-50E-2R with the current dts that has no "wifiN" LED definitions?

**Comment by musashino205** [comment]
I'll rebase this PR after merging #14667 and drop FWF-30E to temporarily postpone the support...

**Comment by RaylynnKnight** [comment]
> I'll rebase this PR after merging #14667 and drop FWF-30E to temporarily postpone the support...

Are you still planning on re-basing?   If you do I will build and test against my devices and then provide an appropriate review.

**Comment by musashino205** [comment]
> Are you still planning on re-basing? If you do I will build and test against my devices and then provide an appropriate review.

Yes, and I did. I was waiting for a reaction from the team members to #14667, but there hasn't been any yet, so I rebased this PR from #14667...

**Comment by fabm3n** [comment]
Love that you add support to FWF-30E. Is it also possible to add support for the FWF-30E-3G4G? AFAIK, there is only the Sierra Wireless EM7565 as modem added. (To complete the family, maybe the FG-30E-3G4G should be added as well)

**Comment by musashino205** [comment]
@fabm3n Hm, can you provide an output of `[I]: System information.` -> `[I]: Display system information.` on bootmenu of FWF-30E-3G4G? `Platform ID` in it is required to generate an initramfs image for that device.

example (FG-30E):

```
  Vendor ID       : Fortinet
  CPU family      : Cortex
  CPU model       : Cortex-A9
  CPU MHz         : 1332 MHz
  Cache size      : 64 KB
  Memory          : DDR SDRAM 1GB 
  Platform ID   : FGT30E
  Serial number : FGT30E3Uxxxxxxxx
  BIOS       Ver:05000014
  Restricted mode : Disable
  Menu timeout    : 60
```

**Comment by fabm3n** [comment]
@musashino205 yes i can provide the information for the FortiWifi Model next week when i'm in the office again. For the FortiGate model i need some weeks. I get one after it is replaced by a new 40E.

**Comment by musashino205** [comment]
UPDATE:

- rebase from current main branch
  - #14667 was merged

**Comment by fabm3n** [comment]
I had no acces to the hardware today, so here are the other informations:

FortiWiFi 30E-3G4G-INTL
Serial-Number: FW30EIXXXX
Due to the Serial-Number the plaform id could be FW30E but i will check it to be sure.

```
hostname # fnsysctl cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00200000 00010000 "uboot"
mtd1: 00600000 00010000 "kn1"
mtd2: 01800000 00010000 "rfs1"
mtd3: 00600000 00010000 "kn2"
mtd4: 01800000 00010000 "rfs2"
mtd5: 01200000 00010000 "part1"
mtd6: 01200000 00010000 "part2"
mtd7: 01e00000 00010000 "data2"
```


```
hostname # fnsysctl ifconfig
eth0	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:15656660 errors:0 dropped:0 overruns:0 frame:0
TX packets:18582724 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:532
RX bytes:2437281611 (2.3 GB)  TX bytes:2720170301 (2.5 GB)
Interrupt:193
 
wan	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:532
RX bytes:0 (0  Bytes)  TX bytes:0 (0  Bytes)
Interrupt:194
 
lan1	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:0 (0  Bytes)  TX bytes:188 (188  Bytes)
Interrupt:255
 
lan2	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:0 (0  Bytes)  TX bytes:188 (188  Bytes)
Interrupt:255
 
lan3	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:15656660 errors:0 dropped:0 overruns:0 frame:0
TX packets:18582718 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:2343341651 (2.2 GB)  TX bytes:2720169737 (2.5 GB)
Interrupt:255
 
lan4	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:0 (0  Bytes)  TX bytes:188 (188  Bytes)
Interrupt:255
 
wifi0	Link encap:Unknown  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:209903808 errors:0 dropped:0 overruns:0 frame:0
TX packets:49954527 errors:301654 dropped:48 overruns:0 carrier:0
collisions:0 txqueuelen:400
RX bytes:0 (0  Bytes)  TX bytes:0 (0  Bytes)
Interrupt:61 Memory:c20c0000-c20e0000
 
root	Link encap:Local Loopback
inet addr:127.0.0.1  Mask:255.0.0.0
UP LOOPBACK RUNNING  MTU:16436  Metric:1
RX packets:8377766 errors:0 dropped:0 overruns:0 frame:0
TX packets:8377766 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:719168570 (685.9 MB)  TX bytes:719168570 (685.9 MB)
 
ssl.root	Link encap:Unknown
UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:2 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:0 (0  Bytes)  TX bytes:0 (0  Bytes)
 
SoftwareSwitch1	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
inet addr:XXXX Bcast:XXXX Mask:255.255.255.128
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:46190 errors:0 dropped:0 overruns:0 frame:0
TX packets:7637457 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:3278408 (3.1 MB)  TX bytes:341902679 (326.1 MB)
 
SoftwareSwitch2	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
inet addr:XXXX Bcast:XXXX Mask:255.255.255.128
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:15656617 errors:0 dropped:0 overruns:0 frame:0
TX packets:18582712 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:2124133510 (1.10 GB)  TX bytes:2645838325 (2.5 GB)
 
WIFI SSID	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:7445 errors:0 dropped:0 overruns:0 frame:0
TX packets:7658808 errors:0 dropped:6 overruns:0 carrier:0
collisions:0 txqueuelen:400
RX bytes:794052 (775.4 KB)  TX bytes:343527762 (327.6 MB)
 
loopback.1	Link encap:Unknown
inet addr:127.0.0.1  Bcast:0.0.0.0  Mask:255.0.0.0
UP BROADCAST LOOPBACK RUNNING NOARP MULTICAST  MTU:1500  Metric:1
RX packets:9156197428552337408 errors:0 dropped:212 overruns:0 frame:0
TX packets:2131843340 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:0 (0  Bytes)  TX bytes:3 (3  Bytes)
 
VPN_Tunnel1	Link encap:Unknown
inet addr:XXXX Mask:255.255.255.255
UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1406  Metric:1
RX packets:136867 errors:0 dropped:0 overruns:0 frame:0
TX packets:134087 errors:1 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:30569756 (29.2 MB)  TX bytes:34502973 (32.9 MB)
 
VPN_Tunnel2	Link encap:Unknown
inet addr:XXXX  Mask:255.255.255.255
UP POINTOPOINT NOARP MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:2 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:0 (0  Bytes)  TX bytes:0 (0  Bytes)
 
vsys_ha	Link encap:Local Loopback
inet addr:127.0.0.1  Mask:255.0.0.0
UP LOOPBACK RUNNING  MTU:16436  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:0 (0  Bytes)  TX bytes:0 (0  Bytes)
 
port_ha	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST MULTICAST  MTU:1496  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:0 (0  Bytes)  TX bytes:94 (94  Bytes)
 
vsys_fgfm	Link encap:Local Loopback
inet addr:127.0.0.1  Mask:255.0.0.0
UP LOOPBACK RUNNING  MTU:16436  Metric:1
RX packets:270748 errors:0 dropped:0 overruns:0 frame:0
TX packets:270748 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:137877210 (131.5 MB)  TX bytes:137877210 (131.5 MB)
 
__xxwlan00	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
UP BROADCAST RUNNING MULTICAST  MTU:1600  Metric:1
RX packets:51426 errors:0 dropped:0 overruns:0 frame:0
TX packets:101857 errors:0 dropped:7569434 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:5687512 (5.4 MB)  TX bytes:21415135 (20.4 MB)
 
wwan	Link encap:Ethernet  HWaddr XX:XX:XX:XX:XX:XX
inet addr:XXXXX  Bcast:XXXXX Mask:255.255.255.255
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:30795996 errors:0 dropped:0 overruns:0 frame:0
TX packets:30020965 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:1920366213 (1.8 GB)  TX bytes:163112284 (155.6 MB)
 
tun_fgfm	Link encap:Unknown
inet addr:XXXX   Mask:XXXX
UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:155 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:4500
RX bytes:0 (0  Bytes)  TX bytes:29627 (28.9 KB)
 ```

**Comment by musashino205** [comment]
UPDATE:

- rebase from current main branch
- drop support for FWF-30E at the moment

**Comment by fabm3n** [comment]
Sorry for the delay. There are only the following information displayed in the System Information:
```
Vendor ID       : Fortinet
CPU family      : Cortex
CPU model       : Cortex-A9
CPU MHz         : 1332 MHz
Cache size      : 64 KB
Memory          : DDR SDRAM 1GB
```

Platform ID and the other stuff is missing. Is there another way to get the Platform ID?

**Comment by musashino205** [comment]
The first 6 characters in the serial number is also a Platform ID.
But sorry, I can't manage adding more 3xE/5xE devices since I'm busy for working to add support for the other several devices (ath79, ramips, mvebu, realtek, ...).

**Pull request merged**
