### PR TITLE
x86: switch to 5.15 as default kernel

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Set 5.15 as default kernel. Testing support was already added on 29.10.2022.

Testing support was added in
9b3bc5d11978 ("x86: enable 5.15 as testing kernel").

Tested-by: Thomas Huehn <thomas.huehn@hs-nordhausen.de>
Signed-off-by: Nick Hainke <vincent@systemli.org>

### CODE REVIEW

**Review by markmentovai — COMMENTED** [review]
In the commit message:

> ```
> Set 5.15 as default kernel. Testing support was already added on
> 29.10.2022.
> ```

Should be 03, not 10.

This also needs https://github.com/openwrt/openwrt/pull/10917 to not break cross builds from non-Linux build hosts.

Otherwise:

Tested-by: Mark Mentovai \<mark@mentovai.com>

**Comment by PolynomialDivision** [comment]
Thanks! :) Updated.

**Comment by ynezz** [comment]
Can you add following dummy change in order to have it build tested?

```patch
diff --git a/.github/workflows/kernel.yml b/.github/workflows/kernel.yml
index 0ba8c27e2e73..4c8d1db8f90f 100644
--- a/.github/workflows/kernel.yml
+++ b/.github/workflows/kernel.yml
@@ -6,7 +6,7 @@ on:
       - '.github/workflows/kernel.yml'
       - 'include/kernel-*'
       - 'package/kernel/**'
-      - 'target/linux/generic/**'
+      - 'target/linux/**'
 
 permissions:
   contents: read

```

**Comment by PolynomialDivision** [comment]
Done. :)

**Comment by pkgadd** [comment]
I've been successfully running v5.15 on my Atom j1900/ gateprotect GP-7543 for over 2 months now (in use as my main router).

```
Tested-by: Stefan Lippers-Hollmann <s.l-h@gmx.de>
```

**Comment by ynezz** [comment]
> Done. :)

Thanks, check https://github.com/openwrt/openwrt/actions/runs/3211150268/jobs/5249119217#step:21:36

```
Package kmod-mmc-spi is missing dependencies for the following libraries:
of_mmc_spi.ko
```

**Comment by PolynomialDivision** [comment]
@ynezz So we need to enable `CONFIG_MMC_SPI`? However, that is also not enabled for 5.10?

**Comment by john-tho** [comment]
> @ynezz So we need to enable `CONFIG_MMC_SPI`? However, that is also not enabled for 5.10?

Not really.
Find out why this is different between kernel versions: Check Linux git history of that mmc host Makefile: https://github.com/torvalds/linux/commit/edd602146507532c1714d8428f654b87205f492e: of_mmc_spi no longer requires `CONFIG_OF` after 5.13
Change the conditional for that packaged module file: https://github.com/openwrt/openwrt/blob/ec6293febc244d187e71a6e54f44920be679cde4/package/kernel/linux/modules/spi.mk#L18

Something like:
If kernel greater or equal to 5.13, include of_mmc_spi.ko
If kernel less that 5.13, include of_mmc_spi.ko only if `CONFIG_OF`

**Comment by john-tho** [comment]
> @ynezz So we need to enable `CONFIG_MMC_SPI`? However, that is also not enabled for 5.10?

Not really.
Find out why this is different between kernel versions: Check Linux git history of that mmc host Makefile: https://github.com/torvalds/linux/commit/edd602146507532c1714d8428f654b87205f492e: of_mmc_spi no longer requires `CONFIG_OF` after 5.13
Change the conditional for that packaged module file: https://github.com/openwrt/openwrt/blob/ec6293febc244d187e71a6e54f44920be679cde4/package/kernel/linux/modules/spi.mk#L18

Something like:
If kernel greater or equal to 5.13, include of_mmc_spi.ko
If kernel less that 5.13, include of_mmc_spi.ko only if `CONFIG_OF`

**Comment by PolynomialDivision** [comment]
@john-tho Thanks. I just removed the condition, because this commit just bumps the kernel version above 5.13, so we don't need to check that?

**Comment by PolynomialDivision** [comment]
@john-tho I added your changes. Thanks! :)

**Comment by PolynomialDivision** [comment]
@ynezz I think this is ready to be merged? :)

**Comment by john-tho** [comment]
> @john-tho I added your changes. Thanks! :)

We might want to add those same kver conditionals on the of_mmc_spi `AUTOLOAD` line as well:
https://github.com/openwrt/openwrt/blob/ec6293febc244d187e71a6e54f44920be679cde4/package/kernel/linux/modules/spi.mk#L20

Sorry I missed it the first time.

Maybe?
```
AUTOLOAD:=$(call AutoProbe,$(if $(CONFIG_OF),of_mmc_spi@lt5.13) of_mmc_spi@ge5.13 mmc_spi)
```

**Comment by ynezz** [comment]
Thanks! Merged in fdd605581c4a 0ecb971a6f37

**Pull request closed without merging**
