### PR TITLE
uboot-envtools: support more Xiaomi devices

### PR DESCRIPTION
**Pull request by akanouras**
- Xiaomi Mi Wi-Fi Router 3G v2
- Xiaomi Mi Router 4A Gigabit Edition

Signed-off-by: Antonis Kanouras <antonis@metadosis.eu>

### CODE REVIEW

**Comment by ynezz** [comment]
> Xiaomi Mi Router 4A Gigabit Edition

I don't see it in the diff.

**Comment by adschm** [comment]
@ynezz mir4a is currently handled as an alternative name for mir3g-v2 (DEVICE_ALT0_MODEL). So, technically this is correct, just the commit message is not as precise as it could be.

In https://github.com/openwrt/openwrt/pull/3562 there is an attempt to have that as a separate device (but it's not at the moment).

**Comment by adschm** [comment]
Strictly, this would also need a PKG_RELEASE bump.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by Neustradamus** [comment]
Merged commit is:
- https://github.com/openwrt/openwrt/commit/cb8c94f5162688dc476979ffc8f2fbf11c3db660

**Pull request closed without merging**
