### PR TITLE
kernel: move GPIO-add-named-gpio-exports.patch to generic

### PR DESCRIPTION
**Pull request by sch-m**
@blogic 
This brings 2 advantages
- no redundant code
- feature is available on every target

Signed-off-by: Martin Schiller <ms@dev.tdt.de>

### CODE REVIEW

**Comment by sch-m** [comment]
> ... give us an real world example not covered by the alternate/upstream solutions outlined above.

We have GPIOs with the following features here:

- input: DSL annex indication (A or B)
- input: SIM inserted indication (for wwan module)
- output: hard-reset for wwan module
- output: power-cycle for wwan module
- output: hard-reset for tpm chip
- output: power-cycle for tpm chip
- output: hard-reset for "daughter boards"
- etc.

And all/most of these GPIOs are accessed by userspace applications or simple shell scripts at runtime to react on some events.

The `package/base-files/files/etc/init.d/gpio_switch` would just set a specified value at bootup as well as the `gpio-hogs` feature do.

Additionally we need an uniform interface to this gpios on targets with devicetree support as well as on x86 targets.

**Comment by sch-m** [comment]
I also know that the gpio sysfs interface is deprecated and one should use the new character device abi, but the sysfs abi is very simple to use (espacially with shell scripts) and it just works.

**Comment by ynezz** [comment]
> input: DSL annex indication (A or B)
> input: SIM inserted indication (for wwan module)

I don't know if there's currently any other upstream solution, but I'm (ab)using `gpio-keys` for similar stuff.

> output: hard-reset for wwan module
> output: power-cycle for wwan module
> output: hard-reset for tpm chip
> output: power-cycle for tpm chip
> output: hard-reset for "daughter boards"

I don't know if there's currently any other upstream solution, but I'm (ab)using `gpio-leds` for this, since `gpio-export` is OpenWrt specific and upstream kernel DTS would need to be patched anyway.

> I also know that the gpio sysfs interface is deprecated and one should use the new character device abi

Maybe it's time for proper solution, for something like `ugpiod` daemon which would handle this in the `OpenWrt` way, using upstream compatible [libgpiod](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git) so one can then use `ubus` to set GPIOs and also receive `ubus` events once the GPIO has changed its state (SIM, DSL). Any volunteers? :-)

**Comment by ynezz** [comment]
I've played with `libgpiod` today little bit, prepared [`libgpiod` package](https://github.com/ynezz/openwrt/tree/wip/libgpiod), you need both commits if you want to play with it:

* [autotools.mk: autoreconf: Fix missing install-sh by forcing install in libtoolize](https://github.com/ynezz/openwrt/commit/391732dd672ba09f969a35ad44559edb2373559c)
* [packages/libs: Add libgpiod library for interacting with the GPIO char device](https://github.com/ynezz/openwrt/commit/0e6e823b5a819d9e4ec62c186a68a4fa6afb9945)

Don't forget to add `libgpiod-tools` package to the image. Then I've just added `gpio-line-names` property to my imx6 board's DTS:

```
&gpio1 {
        gpio-line-names =
                "USB Host VBUS", "", "", "", "Wake Up", "", "", "",
                "", "", "", "", "", "", "", "",
                "Reset Button", "LED 4 Green", "", "", "", "LED 4 Red", "", "",
                "", "PHY Reset", "", "", "PCIe Reset", "", "", "";
};

&gpio2 {
        gpio-line-names =
                "", "LED 5 Green", "LED 5 Red", "", "", "", "", "",
                "", "", "", "", "", "", "", "",
                "", "", "", "", "", "", "", "",
                "", "", "", "", "", "", "", "";
};

&gpio3 {
        gpio-line-names =
                "", "", "", "", "", "", "", "",
                "", "", "", "", "", "", "", "",
                "", "", "", "", "", "", "USB OTG VBUS", "",
                "", "", "", "", "USB Host VBUS Hub", "", "", "";
};

&gpio6 {
        gpio-line-names =
                "", "", "", "", "", "", "", "",
                "", "", "", "", "", "", "SD1 CD", "",
                "", "", "", "", "", "", "", "",
                "", "", "", "", "", "", "", "";
};
```

So when booted with modified DTS described above, I got following runtime GPIO setup:

```
root@OpenWrt:/# gpioinfo | grep -E '(gpiochip|" unused|\[used)'
gpiochip0 - 32 lines:
        line   0: "USB Host VBUS" "usb_host_vbus" output active-high [used]
        line   4:    "Wake Up"    "Wake-Up"   input  active-high [used]
        line  16: "Reset Button" unused input active-high 
        line  17: "LED 4 Green" "LED_4_GREEN" output active-high [used]
        line  21:  "LED 4 Red"  "LED_4_RED"  output  active-high [used]
        line  25:  "PHY Reset"  "phy-reset"  output  active-high [used]
        line  28: "PCIe Reset" "PCIe reset"  output  active-high [used]
gpiochip1 - 32 lines:
        line   1: "LED 5 Green" "LED_5_GREEN" output active-high [used]
gpiochip2 - 32 lines:
        line  22: "USB OTG VBUS" "usb_otg_vbus" output active-high [used]
        line  28: "USB Host VBUS Hub" "usb_host_vbus_hub" output active-high [used]
gpiochip3 - 32 lines:
gpiochip4 - 32 lines:
gpiochip5 - 32 lines:
        line  14:     "SD1 CD"         "cd"   input   active-low [used]
gpiochip6 - 32 lines:
```
and could switch on `LED 5 Red` for one second by issuing following command:

```
gpioset --mode=time --sec=1 $(gpiofind "LED 5 Red")=1; \
    gpioset (gpiofind "LED 5 Red")=0
```
and monitor reset button states as well:

```
root@OpenWrt:/# gpiomon $(gpiofind "Reset Button")
event: FALLING EDGE offset: 16 timestamp: [978313048.958988157]
event:  RISING EDGE offset: 16 timestamp: [978313049.177971490]
```

So it seems like we could probably replace deprecated usage of sysfs interface in OpenWrt with just upstream supported `libgpiod` and if we're missing something we can probably add our utils on top of this or find an upstreamable solution.

@sch-m I think, that all of your use cases could be implemented using `gpio-keys` and with `libgpiod` or did I missed something?

@chunkeey Do you think, that you could use `libgpiod` for your `Netgear WNDAP620's antennae mux` as well?

**Comment by chunkeey** [comment]
> Do you think, that you could use libgpiod for your Netgear WNDAP620's antennae mux as well?

Now that you mention it, I did stumble on gpiod too and I was thinking about packaging it or putting it into procd (or wait a little longer, maybe busybox picks it up :smile: )... But since you seem eager: please follow though! I don't know how any of the owners think about it. Because this is definitely a double-edged sword since the tools/binaries and uci integration add a few kilobytes to the images, while on the other hand: the currently employed sysfs gpio interface is [deprecated](https://github.com/torvalds/linux/blob/master/Documentation/gpio/sysfs.txt) and the gpio-export will never get accepted upstream. Soooo, anyone?

OT: I did also have a "backup plan" for the WNDAP620/660 mux: use [gpio_switches](https://github.com/openwrt/openwrt/blob/master/package/base-files/files/etc/init.d/gpio_switch). And this is what the integration change for the WNAP620/660 looked like:

```
diff --git a/target/linux/apm821xx/base-files/etc/board.d/03_gpio_switches b/target/linux/apm821xx/base-files/etc/board.d/03_gpio_switches
new file mode 100755
index 0000000000..3283016319
--- /dev/null
+++ b/target/linux/apm821xx/base-files/etc/board.d/03_gpio_switches
@@ -0,0 +1,19 @@
+#!/bin/sh
+
+. /lib/functions/uci-defaults.sh
+
+board_config_update
+
+board=$(board_name)
+
+case "$board" in
+netgear,wndap620 | \
+netgear,wndap660)
+       ucidef_add_gpio_switch "internal-antenna-switch" "Select internal antenna" "491" "1"
+       ucidef_add_gpio_switch "external-antenna-switch" "Select external antenna" "494" "0"
+       ;;
+esac
+
+board_config_flush
+
+exit 0
```

In my opinion, the most defensive option that would be immune from any space-related criticism is to package the tools with an adapted and extended "/etc/init.d/gpio_switch" script that uses gpioset and friends. This package(s) could make use the install-overlay feature ( b5222924059f5146007a02e33d317f2c04d7dd0b ) to add said /etc/init.d/gpio_switch file. This way it can be installed on top without opkg complaining. (But this is some work and it's almost bordering on harassment).

**Comment by ynezz** [comment]
>  I was thinking about packaging it

@chunkeey It's already available in [packages feed](https://github.com/openwrt/packages/blob/master/libs/libgpiod/Makefile).

**Comment by sch-m** [comment]
> @sch-m I think, that all of your use cases could be implemented using `gpio-keys` and with `libgpiod` or did I missed something?

Yes, you are right. libgpiod and the tools from there would meet my requirements.
I've tried it some time ago and got some problems (as far as I can remember) when reading inputs.
I'll take a look at that again soon.

**Comment by chunkeey** [comment]
> @chunkeey It's already available in packages feed.

I ran into the same problems that you described in your message (the initial one, it looks like you edited it and deleted the extra patches) https://github.com/openwrt/openwrt/pull/1366#issuecomment-444177376

>I've played with libgpiod today little bit, prepared libgpiod package, you need both commits if you want to play with it:
>
>    autotools.mk: autoreconf: Fix missing install-sh by forcing install in libtoolize
>    packages/libs: Add libgpiod library for interacting with the GPIO char device
> ...

So, in order to use the utilities in the default configuration it needs to be packaged with the generated wndap620/660 image. And this is where it can get complicated because based on the premise of "gpio-export" (i.e. make GPIOs more accessible) there is already another existing method: 
/etc/init.d/gpio-switch that can also do it and already has uci integration.

**Comment by ynezz** [comment]
Christian Lamparter <notifications@github.com> [2018-12-05 17:23:28]:

> I ran into the same problems that you described in your message

Good, it's good to know, that it's really some bug and not just something
happening on my development machine.

I've modified my comment so we rather all use already packaged libgpiod from
packages feed and not my 2nd attempt.

> >  packages/libs: Add libgpiod library for interacting with the GPIO char device
>
> So, in order to use the utilities in the default configuration it needs to
> be packaged with the generated wndap620/660 image. 

Sure, that's why I've started adding libgpiod directly in packages/libs under
OpenWrt in the first place.

> And this is where it can get complicated because based on the premise of
> "gpio-export" (i.e. make GPIOs more accessible) there is already another
> existing method: /etc/init.d/gpio-switch that can also do it and already has
> uci integration.

Indeed, but if we allow addition of the new code/platform/boards to legacy
sysfs indefinitely, then we would never switch to libgpiod. So ideally mark
gpio-export/sysfs as fixes-only, any new code should just use libgpiod.

I don't have enough experience with the codebase to come with the good
solution, but we probably need to find a way, how to handle transition from
gpio_switch using sysfs to gpiod_switch using libgpiod/gpio-set for new
platforms/boards.

Maybe something like `FEATURES += legacy-gpio-sysfs` would work.  We might
just as well package `gpio-set` and `gpio-find` only, maybe staticaly linked
to make the flash size overhead smallest as possible. But this would need to
be investigated yet.

If my grep kung-fu is correct, we would just probably need to handle following
packages/files using legacy sysfs:

```
package/base-files/files/etc/init.d/gpio_switch
package/base-files/files/etc/init.d/led
package/kernel/om-watchdog/files/om-watchdog
package/network/config/ltq-vdsl-app/files/dsl_control
```

and inspect/convert following DTSes which seems to be using gpio-export:

```
apm821xx/dts/netgear-wndap6x0.dtsi
ath79/dts/ar7161_buffalo_wzr-hp-ag300h.dts
ath79/dts/ar7241_tplink_tl-mr3x20.dtsi
ath79/dts/ar7242_buffalo_wzr-bhr.dtsi
ath79/dts/ar7242_buffalo_wzr-hp-g302h-a1a0.dts
ath79/dts/ar9341_tplink_tl-wr842n-v2.dts
ath79/dts/ar9344_tplink_tl-wdr4300.dtsi
ath79/dts/qca9558_openmesh_om5p-ac-v2.dts
ath79/dts/qca9558_tplink_archer-c7.dtsi
ath79/dts/qca9558_tplink_tl-wdr4900-v2.dts
ath79/dts/qca9558_tplink_tl-wr1043nd.dtsi
ath79/dts/qca9561_tplink_archer-c5x.dtsi
ath79/dts/qca9563_tplink_tl-wr1043n.dtsi
ramips/dts/C108.dts
ramips/dts/D240.dts
ramips/dts/DWR-512-B.dts
ramips/dts/FREESTATION5.dts
ramips/dts/HLKRM04.dts
ramips/dts/MZK-WDPR.dts
ramips/dts/NIXCORE.dtsi
ramips/dts/U7621-06.dtsi
ramips/dts/VOCORE.dtsi
```

I didn't found any signs of sysfs-gpio in luci and packages feeds.

**Comment by ynezz** [comment]
Christian Lamparter <notifications@github.com> [2018-12-05 17:23:28]:

> I ran into the same problems that you described in your message

Good, it's good to know, that it's really some bug and not just something
happening on my development machine.

I've modified my comment so we rather all use already packaged libgpiod from
packages feed and not my 2nd attempt.

> >  packages/libs: Add libgpiod library for interacting with the GPIO char device
>
> So, in order to use the utilities in the default configuration it needs to
> be packaged with the generated wndap620/660 image. 

Sure, that's why I've started adding libgpiod directly in packages/libs under
OpenWrt in the first place.

> And this is where it can get complicated because based on the premise of
> "gpio-export" (i.e. make GPIOs more accessible) there is already another
> existing method: /etc/init.d/gpio-switch that can also do it and already has
> uci integration.

Indeed, but if we allow addition of the new code/platform/boards to legacy
sysfs indefinitely, then we would never switch to libgpiod. So ideally mark
gpio-export/sysfs as fixes-only, any new code should just use libgpiod.

I don't have enough experience with the codebase to come with the good
solution, but we probably need to find a way, how to handle transition from
gpio_switch using sysfs to gpiod_switch using libgpiod/gpio-set for new
platforms/boards.

Maybe something like `FEATURES += legacy-gpio-sysfs` would work.  We might
just as well package `gpio-set` and `gpio-find` only, maybe staticaly linked
to make the flash size overhead smallest as possible. But this would need to
be investigated yet.

If my grep kung-fu is correct, we would just probably need to handle following
packages/files using legacy sysfs:

```
package/base-files/files/etc/init.d/gpio_switch
package/base-files/files/etc/init.d/led
package/kernel/om-watchdog/files/om-watchdog
package/network/config/ltq-vdsl-app/files/dsl_control
```

and inspect/convert following DTSes which seems to be using gpio-export:

```
apm821xx/dts/netgear-wndap6x0.dtsi
ath79/dts/ar7161_buffalo_wzr-hp-ag300h.dts
ath79/dts/ar7241_tplink_tl-mr3x20.dtsi
ath79/dts/ar7242_buffalo_wzr-bhr.dtsi
ath79/dts/ar7242_buffalo_wzr-hp-g302h-a1a0.dts
ath79/dts/ar9341_tplink_tl-wr842n-v2.dts
ath79/dts/ar9344_tplink_tl-wdr4300.dtsi
ath79/dts/qca9558_openmesh_om5p-ac-v2.dts
ath79/dts/qca9558_tplink_archer-c7.dtsi
ath79/dts/qca9558_tplink_tl-wdr4900-v2.dts
ath79/dts/qca9558_tplink_tl-wr1043nd.dtsi
ath79/dts/qca9561_tplink_archer-c5x.dtsi
ath79/dts/qca9563_tplink_tl-wr1043n.dtsi
ramips/dts/C108.dts
ramips/dts/D240.dts
ramips/dts/DWR-512-B.dts
ramips/dts/FREESTATION5.dts
ramips/dts/HLKRM04.dts
ramips/dts/MZK-WDPR.dts
ramips/dts/NIXCORE.dtsi
ramips/dts/U7621-06.dtsi
ramips/dts/VOCORE.dtsi
```

I didn't found any signs of sysfs-gpio in luci and packages feeds.

**Comment by chunkeey** [comment]
> I've started adding libgpiod directly in packages/libs under
> OpenWrt in the first place.

Great. Looks like you want to follow through. 

> > And this is where it can get complicated because based on the premise of
> > "gpio-export" (i.e. make GPIOs more accessible) there is already another
> > existing method: /etc/init.d/gpio-switch that can also do it and already has
> > uci integration.
> 
> Indeed, but if we allow addition of the new code/platform/boards to legacy
> sysfs indefinitely, then we would never switch to libgpiod. So ideally mark
> gpio-export/sysfs as fixes-only, any new code should just use libgpiod.

This sounds like as if you already have a good idea of how to mark both
"gpio-export" and the "sysfs" things as "fixes-only"? I mean you could do
that and add comments and notices everywhere, but I don't think it will
deter determined devs ;). Because devs literally only want one thing and
it's disgusting hacks. 

Instead, I would start small and begin by pinging @mhei right now to
prepare for the move of the libgpiod + gpio-tools packages from the
openwrt package feed to the base (for lack of a better word) openwrt.
The main idea here is to make them available (and sort out the
automake stuff).

To help with the move, one could argue that the sysfs-gpio is poised to
be removed as per: 

https://www.kernel.org/doc/Documentation/ABI/obsolete/sysfs-gpio
```
  This ABI is deprecated and will be removed after 2020. It is
  replaced with the GPIO character device.
```
But I also know that this might never be (fully) enforced... Still, libgpiod does
have more advantages. Simply because it allows the gpios to be addressed like in
device-tree and not just arbitrary numbers that can change over time.

And then plan the next step: converting/integrating it into gpio-switch and
dealing with gpio-export. 

> We probably need to find a way, how to handle transition from
> gpio_switch using sysfs to gpiod_switch using libgpiod/gpio-set
> for new platforms/boards.

I don't think that introducing a new, independent "gpiod_switch" that can't
deal with the existing infrastructure will gain much traction. I can see what
you are trying to do there. I know that "gpioset" is sadly not a direct drop-in
replacement for the sysfs-manipulation in /etc/init.d/gpio-switch. This is because
the sysfs uses absolute gpio numbers (like 491, 494, 0, 23) whereas gpioset
needs to know the gpiochip(either number or ID) and the relative gpio
address/number. So having something that does the translation would be
required there to keep it compatible.

However, before you invest your valuable time, it would be highly advisable to
consult the mailing-list too. Because this all is just my opinion and there might be
something hiding in plain sight that none of us knew about.

> Maybe something like `FEATURES += legacy-gpio-sysfs` would work. We might
> just as well package `gpio-set` and `gpio-find` only, maybe staticaly linked
> to make the flash size overhead smallest as possible. But this would need to
> be investigated yet.
Please, I don't think there is a need for yak shaving just yet. 
 
> If my grep kung-fu is correct, we would just probably need to handle following
> packages/files using legacy sysfs:
> 
> ```
> package/base-files/files/etc/init.d/gpio_switch
> package/base-files/files/etc/init.d/led
Do you mean the gpio ledtrigger? If so, don't worry about it since this will need
to be addressed in the kernel first.

> package/kernel/om-watchdog/files/om-watchdog
Hm. This looks like a simple gpio watchdog. I wonder why nobody migrated
to the in-kernel gpio-wdt there? Maybe this can be axed altogether, maybe
not. Chances are, this will stick around until it finally breaks.

> package/network/config/ltq-vdsl-app/files/dsl_control
From what I can tell, this is used in conjunction with gpio-export . So, this
will be definitely out of our league. 
> ```
> 
> and inspect/convert following DTSes which seems to be using gpio-export:
> 
> ```
> apm821xx/dts/netgear-wndap6x0.dtsi
> ath79/dts/ar7161_buffalo_wzr-hp-ag300h.dts
> ath79/dts/ar7241_tplink_tl-mr3x20.dtsi
> ath79/dts/ar7242_buffalo_wzr-bhr.dtsi
> ath79/dts/ar7242_buffalo_wzr-hp-g302h-a1a0.dts
> ath79/dts/ar9341_tplink_tl-wr842n-v2.dts
> ath79/dts/ar9344_tplink_tl-wdr4300.dtsi
> ath79/dts/qca9558_openmesh_om5p-ac-v2.dts
> ath79/dts/qca9558_tplink_archer-c7.dtsi
> ath79/dts/qca9558_tplink_tl-wdr4900-v2.dts
> ath79/dts/qca9558_tplink_tl-wr1043nd.dtsi
> ath79/dts/qca9561_tplink_archer-c5x.dtsi
> ath79/dts/qca9563_tplink_tl-wr1043n.dtsi
> ramips/dts/C108.dts
> ramips/dts/D240.dts
> ramips/dts/DWR-512-B.dts
> ramips/dts/FREESTATION5.dts
> ramips/dts/HLKRM04.dts
> ramips/dts/MZK-WDPR.dts
> ramips/dts/NIXCORE.dtsi
> ramips/dts/U7621-06.dtsi
> ramips/dts/VOCORE.dtsi
> ```
> 
> I didn't found any signs of sysfs-gpio in luci and packages feeds.

**Comment by sch-m** [comment]
OK, so I've also played with libgpiod a little bit and got the following questions:
1. How do I set the direction of an GPIO?
2. Is it possible to initialize to GPIOs via dts? (like settings active-low, direction, initial value)

**Comment by ynezz** [comment]
> How do I set the direction of an GPIO?

```c
/**
 * @brief Reserve a single line, set the direction to output.
 * @param line GPIO line object.
 * @param consumer Name of the consumer.
 * @param default_val Initial line value.
 * @return 0 if the line was properly reserved, -1 on failure.
 */
int gpiod_line_request_output(struct gpiod_line *line,
                              const char *consumer, int default_val);
```

> Is it possible to initialize to GPIOs via dts? (like settings active-low, direction, initial value)

It should be possible with gpio-hog or with pinctrl/iomux settings.

**Comment by chunkeey** [comment]
> I meant via gpio-tools, like it is possible via the sysfs api.

In my opinion, the biggest change that gpiod brings is the relative gpio-addressing (just like with DeviceTree and the gpio- phandle stuff).

For example, if you just want to set the 5th gpio line of gpiochip0 to "high" (if that gpio is available/unused)

     # gpioset gpiochip0 5=1
     # gpioset 0 5=1
     # gpioset 1000000.pinctrl 5=1

The "1000000.pinctrl" identifier is the device-tree node name for gpiochip0 on my IPQ4018 test device.

If your gpio5 is a input line and you want to know the state

     # gpioget gpiochip0 5
     1

     If you are unsure what gpiochip belongs to what hardware, run:

     # gpioinfo

etc.

> > > Is it possible to initialize to GPIOs via dts? (like settings active-low, direction, initial value)
> I've already tried gpio hog and the problem with it is, that the values can't be changed afterwards.

active-low can be set through the "-l" flag for gpioset and gpioget. 

the direction is automatically changed by the tools.  gpioset will set a gpio to "output" and gpioget to "input".

the initial-value for gpioset is let's call it implied. so if you run 
        # gpioset gpiochip0 5=1

the gpio will start out high.

**Comment by sch-m** [comment]
OK, so here is one example of our use cases:

We have a GPIO to control the power of a wwan module.
On one platform this GPIO is active-low, on another one it is active-high.

This output is now used by userspace applications (e.g. shell/lua scripts) to power-cycle the wwan module for some reasons.

With the "old" gpio export and sysfs interface it is possible to setup the output in dts and simply call echo "0" > /sys/class/gpio/wwan_pwr/value to turn the wwan module off.

Using gpioset from the gpio-tools the userspace script has to know if the io is active-low or active-high to properly call gpioset [-l] $(gpiofind wwan_pwr)=0.

It is also not possible to read the set value of an output, when gpioget implicitly switch to input mode.

**Comment by chunkeey** [comment]
> Using gpioset from the gpio-tools the userspace script has to know if the io is active-low or active-high to properly call gpioset [-l] $(gpiofind wwan_pwr)=0.
>
>It is also not possible to read the set value of an output, when gpioget implicitly switch to input mode.

gpioinfo does provide the direction, value and active-low setting you are after. Problem is that it does not filter for a specific gpiochip and line. But the software is actively developed. I would welcome if you
could post your bugreport to the linux-gpio@vger.kernel.org list with a [libgpiod] tag in the subject. I'm sure that this will be of importance for others as well. :+1:

**Comment by adrianschmutzler** [comment]
Last comment here is from 2018, and gpio_export is effectively deprecated. Do we still need this PR open as a reminder?

**Comment by sch-m** [comment]
I will close this PR. It's comprehensible that the deprecated gpio_export supported shouldn't go into the generic path, even if patch handling would be easier ( 1 instead of 3 identical patches).

We should switch to the new libgpiod framework as soon as all requirements can be covered.

**Pull request closed without merging**
