### PR TITLE
qualcommax: convert to nvmem-layout

### PR DESCRIPTION
**Pull request by neheb**
nvmem-cells is deprecated

ping @rmilecki @Ansuel

### CODE REVIEW

**Comment by testuser7** [comment]
After the change, the following message appears:
```
[    1.377598] 0x000000f80000-0x000001000000 : "0:art"
[    1.382596] OF: Bad cell count for /soc/nand-controller@79b0000/nand@0/partitions
```

**Comment by neheb** [comment]
Can you add

```
#address-cells = <1>;
#size-cells = <1>;
```

before nvmem-layout?

**Comment by testuser7** [comment]
Same issue with this:
```
			partition@f80000 {
				#address-cells = <1>;
				#size-cells = <1>;
				label = "0:art";
				reg = <0xf80000 0x80000>;
				read-only;

				nvmem-layout {
					compatible = "fixed-layout";
					#address-cells = <1>;
					#size-cells = <1>;

					caldata_qca9984: caldata@33000 {
						reg = <0x33000 0x2f20>;
					};
				};
			};
```

**Comment by neheb** [comment]
Yeah I tried to fix this with various permutations. Was unsuccessful.

**Comment by neheb** [comment]
https://github.com/openwrt/openwrt/commit/68883278ab2973f6df226e023cabd3ab8353289b

indicates it should be outside of partitions. weird.

**Comment by testuser7** [comment]
Yep, this configuration is OK:
```
	nand@0 {
		reg = <0>;
		compatible = "qcom,nandcs";
		nand-ecc-strength = <4>;
		nand-ecc-step-size = <512>;
		nand-bus-width = <8>;

		#address-cells = <1>;
		#size-cells = <1>;

		partitions {
			compatible = "fixed-partitions";
			#address-cells = <1>;
			#size-cells = <1>;

			.
			.
			.

			partition@f80000 {
				label = "0:art";
				reg = <0xf80000 0x80000>;
				read-only;

				nvmem-layout {
					compatible = "fixed-layout";
					#address-cells = <1>;
					#size-cells = <1>;

					caldata_qca9984: caldata@33000 {
						reg = <0x33000 0x2f20>;
					};
				};
			};
			
			.
			.
			.

		};
	};
```

**Comment by neheb** [comment]
more info on that harmless warning: https://github.com/openwrt/openwrt/pull/11302/commits/e74219c795a03e8b9adccbb5e6a20d4566872f8a

**Comment by aiamadeus** [comment]
From commit be7f9ad, do we need to add 0 at the end?

**Comment by neheb** [comment]
Only if Mac-base is used

**Pull request merged**
