### PR TITLE
ipq40xx: Add support ZTE MF18A

### PR DESCRIPTION
**Pull request by MiG-41**
Light and small router ( In Poland operators sells together with MC7010 outdoor modem to provide WIFI inside home).

### Device specification

SoC Type: Qualcomm IPQ4019
RAM: 256 MiB
Flash: 128 MiB SPI NAND (Winbond W25N01GV)
ROM: 2MiB SPI Flash (GD25Q16)
Wireless 2.4 GHz (IP4019): b/g/n, 2x2
Wireless 5 GHz (QCA9982): a/n/ac, 3x3
Ethernet: 2xGbE (WAN/LAN1, LAN2)
USB ports: No
Button: 2 (Reset/WPS)
LEDs: 3 external leds: Power (blue) , WiFI (blue and red), SMARTHOME (blue and red) and 1 internal (blue) -- NOTE: Power controls all external led (if down ,all others also not lights even signal is up)
Power: 5VDC, 2,1A via USB-C socket
Bootloader: U-Boot
On board ZWave and Zigbee modules ( not supported by orginal software )

### Installation

1.Open MF18A case by ungluing rubber pad under the router and unscrew screws, and connect to serial console port, with the following pinout, starting from pin 1, which is the topmost pin when the board is upright (reset button on the bottom) :

VCC (3.3V). Do not use unless you need to source power for the converer from it.
TX
RX
GND
Default port configuration in U-boot as well as in stock firmware is 115200-8-N-1.

Acc to picture:   https://i.ibb.co/GRJS05g/202212112.jpg

2.Place OpenWrt initramfs image for the device on a TFTP in the server's root. This example uses Server IP: 192.168.0.2

3. Connect TFTP server to RJ-45 port (WAN/LAN1).

4.Power on MF18A , stop in u-Boot (using ESC button) and run u-Boot commands:
    setenv serverip 192.168.0.2
    setenv ipaddr 192.168.0.1
    set fdt_high 0x85000000
    tftpboot 0x84000000 openwrt-ipq40xx-generic-zte_mf18a-initramfs-fit-zImage.itb
    bootm 0x84000000

5. Please make backup of original partitions, if you think about revert to stock, specially mtd16 (Web UI) and mtd17 (rootFS). Use /tmp as temporary storage and do:

WEB PARITION

cat /dev/mtd8 > /tmp/mtd8.bin
scp /tmp/mtd8.bin root@YOURSERVERIP:/
rm /tmp/mtd8.bin

ROOT PARITION

cat /dev/mtd9 > /tmp/mtd9.bin
scp /tmp/mtd9.bin root@YOURSERVERIP:/
rm /tmp/mtd9.bin

If you are sure ,that you want to flash openwrt , from uBoot , before bootm clean rootfs partition with command:
nand erase 0x1800000 0x1D00000

Login via ssh or serial and remove stock partitions (default IP 192.168.1.1):
ubiattach -m 9 # it could return error if ubi was attached before or rootfs part was erased before
ubirmvol /dev/ubi0 -N ubi_rootfs # it could return error if rootfs part was erased before
ubirmvol /dev/ubi0 -N ubi_rootfs_data # some devices doesn't have it

Install image via :
sysupgrade -n /tmp/openwrt-ipq40xx-generic-zte_mf18a-squashfs-sysupgrade.bin
previously wgeting bin. Sometimes it could print ubi attach error, but please ignore it if process goes forward.

### Back to Stock (!!! need original dump taken from initramfs !!!) -------------

Place mtd8.bin and mtd9.bin initramfs image for the device on a TFTP in the server's root. This example uses Server IP: 192.168.0.2
Connect serial console (115200,8n1) to serial console connector .
Connect TFTP server to RJ-45 port (WAN/LAN1).
rename mtd8.bin to web.img and mtd9.bin to root_uImage_s
Stop in u-Boot (using ESC button) and run u-Boot commands:
This will erase Web and RootFS:
nand erase 0x1000000 0x800000
nand erase 0x1800000 0x1D00000

This will restore RootFS:
tftpboot 0x84000000 root_uImage_s
nand erase 0x1800000 0x1D00000
nand write 0x84000000 0x1800000 0x1D00000

This will restore Web Interface:
tftpboot 0x84000000 web.img
nand erase 0x1000000 0x800000
nand write 0x84000000 0x1000000 0x800000

After first boot on stock firwmare, do a factory reset. Push reset button for 5 seconds so all parameters will be reverted to the one printed on label on bottom of the router

As reference was taken MF289F support by Giammarco Marzano [stich86@gmail.com](mailto:stich86@gmail.com) and MF286D by Pawel Dembicki [paweldembicki@gmail.com](mailto:paweldembicki@gmail.com)

Signed-off-by: Marcin Gajda [mgajda@o2.pl](mailto:mgajda@o2.pl)

### CODE REVIEW

**Comment by Leo-PL** [comment]
@MiG-41 is the 1st pin of the UART marked somehow, perhaps with a square pad? Did your unit come with the header soldered in?
This image link might go dead eventually - I'd remove it.

**Comment by MiG-41** [comment]
@Leo-PL ,no goldpins is my job. I don't recall any markings ( but i dont negate , that this square can be under plastic of goldpin's header). 'm sure that this socket is not marked ( there is no signs like X8 , or X2...) . For now only tip is ,that cont is from the top , and bottom is reset pin as reference.
Ok , removed link to picture from commit.

O

**Comment by kriswr741217** [comment]
I can not execute - not working: 4.Power on MF18A , stop in u-Boot (using ESC button) and run u-Boot commands:

**Comment by MiG-41** [comment]
What exacly not working ?
You can't stop uBoot  (but you see , that text is apearing) ? Or ? You sure connection is ok ?

**Comment by Leo-PL** [comment]
LZMA error possibly? I've started to observe this more often recently, due to growth of initramfs images. Primarily on ath79, but ipq40xx might be affected as well.

**Comment by kriswr741217** [comment]
the console connection is fine.

fota_main: enter into !
ZTE_InitFotaFlashPara: nand_curr_device=0
zte_getHandOffState: read data=0xff from 0x0
Press ESC to abort autoboot in 2 seconds

when starting the router I click ESC, but it does not respond.

**Comment by MiG-41** [comment]
Then it is a case of connection.  When orginal fw start you can press ENTER and have a console , is that also not working ?
If you shortcut on your converter TX with RX you recive "echo" ? ( something what you are typing in putty apear second time).

Simplest way would be to try another converter ( best with other chip ).

**Comment by kriswr741217** [comment]
of course you were right, I changed the converter and the connection works fine. thanks.
but I have another problem.
setenv serverip 192.168.1.50
setenv ipaddr 192.168.1.1
set fdt_high 0x85000000
tftpboot 0x84000000 openwrt-ipq40xx-generic-zte_mf18a-initramfs-fit-zImage.itb   # I did not find
tftpboot 0x84000000 openwrt-ipq40xx-generic-zte_mf18a-initramfs-uImage.itb       # I flash That file, is it corect or not ?
bootm 0x84000000  								                  # after that command I have information as below
										                                     and nothing happens
Using machid 0x8010001 from environment
Starting kernel ...

**Comment by kriswr741217** [comment]
Please help me I'm stuck here.
root@OpenWrt:~#
root@OpenWrt:~# ubiattach -m 9
[  806.467630] ubi: mtd9 is already attached to ubi0
ubiattach: error!: cannot attach mtd9
           error 17 (File exists)
root@OpenWrt:~# ubirmvol /dev/ubi0 -N ubi_rootfs
ubirmvol: error!: cannot find UBI volume "ubi_rootfs"
          error 2 (No such file or directory)
root@OpenWrt:~# ubirmvol /dev/ubi0 -N ubi_rootfs_data
ubirmvol: error!: cannot find UBI volume "ubi_rootfs_data"
          error 2 (No such file or directory)
root@OpenWrt:~# sysupgrade -n /tmp/openwrt-23.05.0-ipq40xx-generic-zte_mf18a-squ
ashfs-sysupgrade.bin
Mon Oct  9 21:59:26 UTC 2023 upgrade: Image metadata not present
Mon Oct  9 21:59:26 UTC 2023 upgrade: Use sysupgrade -F to override this check when downgrading or flashing to vendor firmware
[  838.425117] ubi: mtd9 is already attached to ubi0
ubiattach: error!: cannot attach mtd9
           error 17 (File exists)
Image check failed.
root@OpenWrt:~# [  851.517111] qca8k-ipq4019 c000000.switch lan: Link is Down
[  851.518229] br-lan: port 1(lan) entered disabled state

**Pull request merged**
