### PR TITLE
[WIP] mt7622: switch to 6.1 kernel

### PR DESCRIPTION
**Pull request by PolynomialDivision**
**HIGHLY WIP!**
If someone want to use kernel 6.1rc2 on a banana pi r64 you can try this branch:
```
CONFIG_TARGET_mediatek_mt7622_DEVICE_bananapi_bpi-r64=y
# CONFIG_DRIVER_11AC_SUPPORT is not set
# CONFIG_DRIVER_11N_SUPPORT is not set
# CONFIG_PACKAGE_iw is not set
# CONFIG_PACKAGE_kmod-cfg80211 is not set
# CONFIG_PACKAGE_kmod-crypto-ccm is not set
# CONFIG_PACKAGE_kmod-crypto-ctr is not set
# CONFIG_PACKAGE_kmod-crypto-gcm is not set
# CONFIG_PACKAGE_kmod-crypto-gf128 is not set
# CONFIG_PACKAGE_kmod-crypto-ghash is not set
# CONFIG_PACKAGE_kmod-crypto-hmac is not set
# CONFIG_PACKAGE_kmod-crypto-rng is not set
# CONFIG_PACKAGE_kmod-crypto-seqiv is not set
# CONFIG_PACKAGE_kmod-crypto-sha256 is not set
# CONFIG_PACKAGE_kmod-hwmon-core is not set
# CONFIG_PACKAGE_kmod-mac80211 is not set
# CONFIG_PACKAGE_kmod-mt7615-firmware is not set
# CONFIG_PACKAGE_kmod-mt7615e is not set
# CONFIG_PACKAGE_wireless-regdb is not set
```

### CODE REVIEW

**Comment by Ansuel** [comment]
Oh god what did I start...

**Comment by PolynomialDivision** [comment]
> Oh god what did I start...

Something great. :D

**Comment by mrkiko** [comment]
Definitely a nice adventure :)

**Comment by AntonyFl** [comment]
Hi @PolynomialDivision Can you add filogic, I want to try v6.1 on the banana pi bpi-r3, thanks!

**Comment by barrenechea** [comment]
> Hi @PolynomialDivision Can you add filogic, I want to try v6.1 on the banana pi bpi-r3, thanks!

Completely off-topic, how's the BPi R3 working for you with OpenWRT? Thinking about it, but expecting for the PoE version to come out 🤔

**Comment by AntonyFl** [comment]
> Completely off-topic, @AntonyFl how's the BPi R3 working for you with OpenWRT? Thinking about it, but expecting for the PoE version to come out thinking

BPi R3  is supported https://github.com/openwrt/openwrt/commit/a96382c1bb204698cd43e82193877c10e4b63027

**Pull request closed without merging**
