### PR TITLE
ath79/ramips: Change DTS license to GPL-2.0-or-later OR MIT 

### PR DESCRIPTION
**Pull request by ynezz**
Hi @rmilecki, here are the requested changes to the licenses. Thanks.

### CODE REVIEW

**Comment by rmilecki** [comment]
@mkresin: you've modified BDCOM-WAP2100-SK.dts in the commit e4d9217fe541 ("ramips: improve BDCOM WAP2100-SK support"). I need you to send Acked-by for the @ynezz's commit 69b2723e65f7 ("ath79: ubnt-bullet-m-xw: Change DTS license to GPL-2.0-or-later OR MIT").

How do we handle that with GitHub pull requests?

**Comment by mkresin** [comment]
@rmilecki I'll push the PR later. Should be enough acknowledgement.

**Comment by rmilecki** [comment]
I've asked on #openwrt-devel and apparently GitHub does not support adding any tags to the commits. So there is no way for @mkresin to ack that commit. Hooray, another reason to love GitHub for me.

@ynezz: thank you for changes, I've picked ath79 ones and pushed them to the OpenWrt repo!

@mkresin: can you pick the ramips commit, add your Acked-by and push to the OpenWrt tree, please?

**Comment by mkresin** [comment]
Merged, thanks!

**Pull request closed without merging**
