### PR TITLE
mpc85xx: p2020: kernel: enable CONFIG_BLK_DEV_NVME

### PR DESCRIPTION
**Pull request by autobakterie**
mpc85xx: p2020: kernel: enable CONFIG_BLK_DEV_NVME

Enables use of NVMe storage devices with appropriate adapter in miniPCIe slots (including for boot)
in Turris 1.x routers and possibly NXP P2020RDB boards
(these are the only currently supported p2020 devices according to docs[^1]).

Proper detection, mountability and readability was proved to be working
on Turris 1.1, OpenWrt 21.02 with similar configuration.

Increases gzip compressed kernel size by approximately 35 KiB (from 3 645 KiB to 3 680 KiB).

Should boot from those devices be possible the driver needs to be built in.
Inclusion as a module would prevent this functionality.

CONFIG_BLK_DEV_NVME=y
Includes NVMe driver in the kernel.[^2]

CONFIG_NVME_CORE=y
Selected by CONFIG_BLK_DEV_NVME.[^3] Not necessarily needed to be enabled explicitly,
but included to match the form of similar functionality implementations
for mvebu, x86_64 and rockchip_armv8 targets.

Some other NVMe related configuration items disabled explicitly
to prevent using more space than necessary.

[^1]: https://openwrt.org/docs/techref/targets/mpc85xx
[^2]: https://cateee.net/lkddb/web-lkddb/BLK_DEV_NVME.html
[^3]: https://cateee.net/lkddb/web-lkddb/NVME_CORE.html

Signed-off-by: Šimon Bořek <simon.borek@nic.cz>

### CODE REVIEW

**Review by BKPepe — APPROVED** [review]

**Comment by mans0n** [comment]
Please try `make kernel_oldconfig CONFIG_TARGET=subtarget` after the change.

**Comment by autobakterie** [comment]
I rebased onto current master and added automatically altered `mpc85xx/p2020/config-default` after `make kernel_oldconfig CONFIG_TARGET=subtarget` run as a fixup commit.

The current sizes of gzip compressed kernel are:
* 3 648.234 KiB with config-default from current master
* 3 684.340 KiB with config-default with my changes (rebased onto current master) before running kernel_oldconfig
* 3 684.320 KiB after runnning kernel_oldconfig on top of my change

**Comment by autobakterie** [comment]
`make kernel_oldconfig CONFIG_TARGET=subtarget` generally leads to following changes in `mpc85xx/p2020/config-default`.

## Most are done the same in master branch as well as after applying my changes:

### Additions:
```
CONFIG_DEFAULT_UIMAGE=y
CONFIG_FSL_ULI1575=y
CONFIG_GENERIC_MSI_IRQ=y
CONFIG_GENERIC_MSI_IRQ_DOMAIN=y
CONFIG_IRQ_DOMAIN_HIERARCHY=y
CONFIG_MDIO_DEVRES=y
CONFIG_NEED_DMA_MAP_STATE=y
CONFIG_PCI_MSI_ARCH_FALLBACKS=y
CONFIG_PCI_MSI_IRQ_DOMAIN=y
CONFIG_PPC_I8259=y
CONFIG_SWIOTLB=y
```
### Deletions:
```
CONFIG_ARCH_HAS_TICK_BROADCAST=y
CONFIG_HAVE_RCU_TABLE_FREE=y
CONFIG_MTD_NAND_BCH=y
CONFIG_MTD_NAND_ECC_BCH=y
```

## Changes specific to my changes:

### Deletions:
```
# CONFIG_NVME_HWMON is not set
# CONFIG_NVME_TCP is not set
```

**Comment by autobakterie** [comment]
Apart from the removal of two lines explicitly disabling two options (which I think were just classified as redundant) the changes made by kernel_oldconfig don't seem to be anyhow related to the proposed change.

Therefore I see no reason to incorporate the unrelated changes into the current pull request.

Would you prefer leaving out
```
# CONFIG_NVME_HWMON is not set
# CONFIG_NVME_TCP is not set
```
from my change as well?

**Comment by autobakterie** [comment]
I updated the kernel size values in the commit message to those from my yesterday's testing after rebase onto current master.

**Comment by autobakterie** [comment]
Shall I sort `config_default`'s lines in alphabetic order (disregarding hashes) - the way `kernel_oldconfig` seems to sort - prior to merge?

Is there anything else you consider needed to be done regarding this PR?

@mans0n

**Comment by hauke** [comment]
It looks like the `target/linux/mpc85xx/p2020/config-default` file is out of sync already without your changes. Could you please run `make kernel_oldconfig CONFIG_TARGET=subtarget` first without your change to refresh the configuration in current master and add this as a seperate commit. Please add your cahnges as a seperate commit and also run with your cahnges. `make kernel_oldconfig CONFIG_TARGET=subtarget`again.

**Comment by autobakterie** [comment]
I split my changes and  `make kernel_oldconfig CONFIG_TARGET=subtarget` ones into different commits as requested. Is further description of autochanged configuration items needed in the related commit message? @hauke

**Comment by BKPepe** [comment]
@chunkeey may I ask you to look at this PR? It might seem like there are too many changes at first glance, but these were caused that one config being already out of sync, and the important part is that it enables NVME support for p2020 subtarget. Currently, this subtarget supports only [P2020RDB](https://www.nxp.com/design/qoriq-developer-resources/p2020-reference-design-board:P2020RDB), which has miniPCIe slot, and it can be very handy to connect external storage to it.

**Comment by chunkeey** [comment]
@BKPepe . I don't want to cause another 6006f73383cc7626552175010de23530bdcc8718 situation. though, I get that without NVME support, you can't do much useful stuff with an NVME card in that slot.


If you both are just after "handy to connect external storage to it." I think there could be compromise option.. which would conveniently preemptively side-step any criticism: make a package for the NVME_CORE + BLK_NVME as a module. This should be possible without much/any kernel growth since linux has already both CONFIG_NVME_CORE (but sadly without a prompt) and CONFIG_BLK_DEV_NVME as tristate in KConfig. So it is possible to built them as modules.

(This would also start a foundation for NVME over TCP support. Though this is by no means a requirement since I'm not sure if that is within the current scope of OpenWrt... It might be in the future).

What do you think?

**Comment by BKPepe** [comment]
I think the first part deserves a reference to the pull request - https://github.com/openwrt/openwrt/pull/10005 , where the commit itself does not do anything wrong. The support for it was already enabled in the kernel config. Thus some packages were missing. What it currently does is that extends build time and storage capacity a bit since then. Still some users might benefit from it.

Having external storage for NVMe disk is good to have to prevent writes on flash memory, which can not be easily replaced (in some cases). P2020RDB (the only supported target in p2020 right now) has a large storage capacity, I would say. 

Kernel increase "by approximately 36 KiB (from 3 648 KiB to 3 684 KiB)." (stated in the commit message) seems alright once it is enabled directly in the kernel, which allows booting from it, and that's can not be done when it is done as modules.

However, to prevent any misunderstanding, let's cc @CHKDSK88

**Comment by BKPepe** [comment]
Kind reminder @CHKDSK88

**Comment by CHKDSK88** [comment]
> I think the first part deserves a reference to the pull request - #10005 , where the commit itself does not do anything wrong. The support for it was already enabled in the kernel config. Thus some packages were missing. What it currently does is that extends build time and storage capacity a bit since then. Still some users might benefit from it.
> 
> Having external storage for NVMe disk is good to have to prevent writes on flash memory, which can not be easily replaced (in some cases). P2020RDB (the only supported target in p2020 right now) has a large storage capacity, I would say.
> 
> Kernel increase "by approximately 36 KiB (from 3 648 KiB to 3 684 KiB)." (stated in the commit message) seems alright once it is enabled directly in the kernel, which allows booting from it, and that's can not be done when it is done as modules.
> 
> However, to prevent any misunderstanding, let's cc @CHKDSK88

I'm fine with that PR. LGTM.

**Comment by chunkeey** [comment]
Looks like https://github.com/openwrt/openwrt/pull/10337 is packing the nvme support in a kmod.

**Comment by autobakterie** [comment]
> Looks like #10337 is packing the nvme support in a kmod.

He is creating a kernel module accessible to all devices, but as described in [a comment inside the thread](https://github.com/openwrt/openwrt/pull/10337#issuecomment-1195520887) that is not mutually exclusive with enabling NVMe inside kernel itself for select devices (capable of actually utilizing NVMe for boot and having enough storage). NXP P2020RDB board seems to have enough internal storage for the 36KiB kernel size increase and as it also allows NVMe storage attchment, it might benefit from built-in NVMe boot support easily. The same goes for Turris 1.x routers.

**Comment by BKPepe** [comment]
Guys, guys. Can we have this merged? :raised_hands:  :raised_hands:

**Comment by BKPepe** [comment]
After almost a month, I am here again! :laughing: 

Guys, @hauke or @champtar, can you look at it and merge this so that we can get rid of it? It has been here since March. :(

**Comment by BKPepe** [comment]
Kind reminder. Cc: @Ansuel

**Comment by BKPepe** [comment]
Guys? Kind reminder. What's blocking this PR to have this merged? 

cc: @chunkeey , @hauke

**Comment by Ansuel** [comment]
@BKPepe does this target have space constrains ?

**Comment by BKPepe** [comment]
@Ansuel: Currently, the only supported target here is P2020RDB and I doubt that increase by 35KiB is blocking this PR from being merged. We would like to have this for Turris 1.x routers, which have up 256 MB NAND storage (recently upstreamed Linux kernel and U-boot, so hopefully, we will manage to have upstream OpenWrt support soon). But both these boards have miniPCIe slots and as well microSD card reader, which can boot from.

If you were asking about of the NVMe length for Turris 1.x boards that it is up to 58mm, so only disks, which can be used are 30mm and 42mm.

**Comment by Ansuel** [comment]
@autobakterie can you rebase this? the delta have more changes than what this pr describe.

**Comment by autobakterie** [comment]
`make kernel_oldconfig CONFIG_TARGET=subtarget` run pre- and post- changes application on current master. Builds successfully after both config refreshes. Size increase basically the same as before - 37 KiB (from 3 703 KiB to 3 740 KiB). 

First config refresh now additionally removes `# CONFIG_PPC_QUEUED_SPINLOCKS is not set` and adds:
```
CONFIG_REGMAP=y
CONFIG_REGMAP_I2C=y
CONFIG_TARGET_CPU="8540"
CONFIG_TARGET_CPU_BOOL=y
```

**Comment by Ansuel** [comment]
@autobakterie can you squash the last 2 commit? Aside from that, this seems ready

**Comment by autobakterie** [comment]
Rebased onto current master, the last to commits squashed.

**Comment by autobakterie** [comment]
The MR should be ready in its current state. Could it be merged?

**Pull request merged**
