### PR TITLE
kernel: modules: drop outdated kernel version switch

### PR DESCRIPTION
**Pull request by 1715173329**
We have only kernel 6.6 support now.

### CODE REVIEW

**Comment by namiltd** [comment]
Partial duplicate: https://github.com/openwrt/openwrt/pull/16432

**Comment by 1715173329** [comment]
Oh sorry I missed that. Feel free to include the remaining parts into your PR, I will close this one.

**Comment by namiltd** [comment]
Your PR is broader though, reopen it, I'll close mine.

**Comment by 1715173329** [comment]
Not really necessary tbh ;)

**Pull request closed without merging**
