### PR TITLE
ath25: split up DEVICE_TITLE

### PR DESCRIPTION
**Pull request by mwarning**
DEVICE_TITLE is split up into DEVICE_VENDOR, DEVICE_MODEL and DEVICE_VARIANT

### CODE REVIEW

**Comment by mwarning** [comment]
@adrianschmutzler another odd one. Do you have good idea?

**Comment by adrianschmutzler** [comment]
Same as with octeon: Since it's a Generic image, we might just keep it. Let's wait for response from @aparcar

**Comment by aparcar** [comment]
I commented [here](https://github.com/openwrt/openwrt/pull/2453#issuecomment-536220287) on a similar situation.

**Comment by mwarning** [comment]
@adrianschmutzler let's use this then?
```
  DEVICE_VENDOR := Generic
  DEVICE_MODEL := ath25
```

**Comment by adrianschmutzler** [comment]
Yes. As stated with octeon, I would put all those together into a new PR.
(Maybe grep for remaining DEVICE_TITLES in target/)

There we could sort out consistency issues, like "ath25"/"octeon" or "Ath25"/"Octeon" etc.

Since ath25 and octeon PRs are only about the generic entry, I would close those then.

**Review by adschm — APPROVED** [review]

**Review by aparcar — APPROVED** [review]

**Comment by mwarning** [comment]
@rsa9000 please review - thanks!

**Comment by dangowrt** [comment]
I still believe we shouldn't pollute this by adding a 'Generic' vendor. If you are really insisting to split-up even those titles which do not belong to one or more specific device(s), let's at least use something meaningful, such as
```
DEVICE_VENDOR := 'Atheros' 
DEVICE_MODEL := 'Generic AR2xxx board'
```

**Review by rsa9000 — APPROVED** [review]

**Comment by rsa9000** [comment]
@mwarning, I am Ok with the change.

The same image could be flashed to multiple devices because vendors reimplement an original Atheros reference design. So specifying 'Atheros' as the device vendor for the firmware image, as @dangowrt suggests, looks sane too.

It is up to you to keep the change as is or take a closer look to the @dangowrt suggestion. I am Ok with both of them.

**Comment by adrianschmutzler** [comment]
@dangowrt 

Your suggestion is similar to what I once tried for the Generic devices in brcm63xx:
https://github.com/openwrt/openwrt/pull/2390#discussion_r322741239

There, the "Generic" vendor was preferred. So, generally I'm more in favor of your approach, but for consistency I would now prefer to have the solution in the current state of this commit.

However, I can live with both options.

**Comment by dangowrt** [comment]
Imho the same even more applies for those brcm63xx reference designs,
vendor should be 'Broadcom' there -- I doubt that anyone would type
the word 'Generic' into the auto-completing-search input fields which
build upon that metadata...

**Comment by adrianschmutzler** [comment]
@dangowrt Then it might be best if you sort this out with @KanjiMonster , as I'm not a member and thus can only express my thoughts here, but not veto on a member's statement.

**Comment by adrianschmutzler** [comment]
(We obviously could also just have different schemes for different targets, as nobody will die from inconsistency ...)

**Comment by mwarning** [comment]
Fine with me. A generic vendor is a kludge.

**Comment by hauke** [comment]
Thank you for your patch, it was applied to master.

**Pull request closed without merging**
