### PR TITLE
octeon: move usb3 usb-dwc3 and usb-storage-uas kmods to DEFAULT_PACKAGES

### PR DESCRIPTION
**Pull request by damex**
as reported on forums and irc - automated initramfs builds
  does not include packages from DEVICE_PACKAGES list
  hence the fresh installs from usb flash drive are not possible.

DEVICE_PACKAGES are ignored on initramfs images when:
 - CONFIG_TARGET_MULTI_PROFILE
 - CONFIG_TARGET_PER_DEVICE_ROOTFS
 - CONFIG_TARGET_ALL_PROFILES
are set.

here we move DEVICE_PACKAGES that implement usb support to
  DEFAULT_PACKAGES so fresh installs from initramfs would be possible again.

Signed-off-by: Roman Kuzmitskii <damex.pp@icloud.com>

### CODE REVIEW

**Comment by ynezz** [comment]
I'm struggling with something similar and I think, that this proposed solution is not a proper fix, just workaround.

Either this needs to go into [DEFAULT_PACKAGES](https://git.openwrt.org/?p=openwrt/staging/ynezz.git;a=commitdiff;h=7a629ef6b502038c9ffd6da2c90d3e9a3a609d93;hp=efe5b9a0fe9df89a4dc07b3e0989d55e94166fe6) like in my current work in progress solution for similar issue in mvebu/cortexa9. The other approach might be fixing different behavior for packages in initramfs images. I mean, if the packages ends up in the other images like sysupgrade, why it's not consistent with initramfs images as well?

**Comment by damex** [comment]
@ynezz
please check it again.
i moved packages to DEFAULT_PACKAGES.

**Comment by mans0n** [comment]
Did #4757 solved this issue or not?

**Comment by ynezz** [comment]
Should be fixed via https://github.com/openwrt/openwrt/commit/e900779e6f15a3a00a2f9003dd68a43aa0ef88e8

**Pull request closed without merging**
