### PR TITLE
ipq806x: base-files: add default led config

### PR DESCRIPTION
**Pull request by Ansuel**
This adds default leds config fro r7800 as these leds are supported.
@blogic 
Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by juppin** [comment]
You could add this also in tje corresponding dts file.

Here is a example:
https://github.com/openwrt/openwrt/blob/master/target/linux/ath79/dts/ar9344_tl-wdr4300.dtsi

**Comment by mkresin** [comment]
2018-06-22 15:48 GMT+02:00 Johann Neuhauser <notifications@github.com>:
>
> You could add this also in tje corresponding dts file.
>
> Here is a example:
> https://github.com/openwrt/openwrt/blob/master/target/linux/ath79/dts/ar9344_tl-wdr4300.dtsi

Unfortunately not. The ath10k GPIO controller support was dropped
between v12 and v13 of the patch that adds the ath10k leds.
Nevertheless, adding the GPIO controller code would be the cleanest
solution.

**Comment by mkresin** [comment]
@Ansuel would you mind to test the "mac80211: ath10k: use tpt LED trigger by default" commit from [my staging tree](https://git.openwrt.org/?p=openwrt/staging/mkresin.git;a=summary) instead.

**Comment by Ansuel** [comment]
i will test

I hope this doesn't create some conflicts with a custom led definition.

**Comment by Ansuel** [comment]
@mkresin the patch compile correctly but how should i test it? 

i need to reset the router?

**Comment by juppin** [comment]
I think it should be sufficient to remove currently set triggers for that leds in /etc/config/system and on a boot the default trigger should be set for phyXtpt through the new code...
If you set a trigger in the mentioned config it will be overwritten when the led init script executes.

**Comment by Ansuel** [comment]
so at runtime remove it doesn't work right?

**Comment by juppin** [comment]
> so at runtime remove it doesn't work right?

No, the code that sets the trigger runs only while the ath10k leds are registered... This would definitely happen on boot, but probably it will also work if you unload the driver and load it again... 
Don´t know whats the name for it.You could check with lsmod for somthing with ath10k.

**Comment by Ansuel** [comment]
the driver is ath10k-pci

**Comment by mkresin** [comment]
Okay, a bit more background information.

LEDs are usually created with the `none` trigger set. It means, nothing triggers this LED. That is why we have `/etc/init.d/leds`, to set the triggers configured in `/etc/config/system`.

With my patch applied, the `ath10k-phy*` LEDs have the `phy*tpt` trigger set by default instead of `none`.

It is still possible to set a different led trigger via `/etc/config/system`. It will overwrite the default trigger, as it was done all the time (just that the default trigger is `phy*tpt` instead of `none`).

You can see the set triggers in `/sys/class/leds/*/trigger`.

To properly test my patch, you need to remove the settings for the `ath10k-phy0` and `ath10k-phy1` led from `/etc/config/system`. After a reboot the `phy0tpt` trigger should be set for `ath10k-phy0` and `phy1tpt` for `ath10k-phy1`, even if not configured in `/etc/config/system`.

The expectation is that the wireless LEDs just work without any kind of configuration.

**Comment by Ansuel** [comment]
ok this night i will test... 

I tested the patch in the wrong way then...

**Comment by Ansuel** [comment]
@mkresin i tested and the patch works well... anyway i notice a strange thing... 

A sysupgrade doesn't apply the new driver (tested with a driver without led support and without your patch)

The only way to apply the new driver is by using tftp... Any idea why ?

**Comment by hnyman** [comment]
@mkresin 
Made a build of r7313-4b50854a60 plus the two patches from your staging tree (stintel's and yours), and the wifi LEDs work ok in R7800. 

I removed the existing LED config from /etc/config/system, and the default triggers got assigned ok when I sysupgraded to the new build.

(Normal sysupgrade worked ok, so no idea about needing TFTP like ansuel claims.)

Both 2.4 and 5 GHz LEDs reacted ok to connecting devices.

**Comment by Ansuel** [comment]
@hnyman can you test to sysupgrade from a build without led support to a build with led support?

**Comment by hnyman** [comment]
@Ansuel 
do you mean that a build with the LED settings can not be flashed with sysupgrade (flashing/booting itself fails), or that the new driver does not get applied in a sysupgrade (which works ok otherwise)?

I tried "downgrading" to recent buildbot image and failed. TFTP was needed to recover. I doubt that it is related to the LED code, but there is no relevant change between buildbot r7312-5c5bf8b865 and my own r7313-4b50854a60.

**Comment by Ansuel** [comment]
ummm no in my case, the firmware gets flashed (i think...) but i notice that the chages to ath10k doesn't apply (firmware upgraded but no new leds in /sys/class) 
by flashing with tftp the leds finally comes up. 

I don't know if it's just sysupgrade that doesn't flash the image...

**Comment by mkresin** [comment]
Thanks to all for testing!

I'm quite sure the sysupgrade isssue you're seeing is unrelated to the LED trigger change. There was an issue [reported reading sysupgrade failures on the OpenWrt Development mailing list](http://lists.infradead.org/pipermail/openwrt-devel/2018-June/thread.html#12717).

But this issue should be already fixed. A serial console log might be helpful to see what is going on.

**Comment by mkresin** [comment]
I merged my default trigger patch instead of the PR. I still would like to see the ath10k patch ported, to add the wireless LEDs properly. But so far the wireless LEDs do their job.

**Pull request closed without merging**
