### PR TITLE
firewall3: update file hash

### PR DESCRIPTION
**Pull request by mcprat**
the hash and timestamp of the remote copy of the archive
has changed since last bump

Signed-off-by: Michael Pratt <mcpratt@pm.me>

### CODE REVIEW

**Comment by Ansuel** [comment]
@jow- pls don't tell me this is the old problem i sent an email at times.
http://lists.openwrt.org/pipermail/openwrt-devel/2022-May/038712.html

Can i merge this? From your last replay it seems nobody cared to update the hash.

**Comment by Ansuel** [comment]
@mpratt14 sorry to say... wanted to fix this myself but it would require too much changes... Can you reword this?

Something like firewall3: fix wrong package hash
and the commit description with
It seems the package was bumped with the wrong hash.
Fix this and update the package hash with the correct one.

**Comment by rsalvaterra** [comment]
> @rsalvaterra jow said you pushed the wrong hash... https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=435d7a052bf1b6a3a01cb3ad6cda6ba4b25b1879 can you confirm this in some way?

Ugh… Indeed, I'm measuring `ce9e8ac1bcf22afbb0a80c3da1a8e8e887851299681097e3dfbfc347f2c4c80f` now. How the heck have I managed to mess that up?! 😱

**Comment by Ansuel** [comment]
don't know it's strange... i don't whant to think something happen to firewall3 repo...

**Comment by mpratt14** [comment]
repo had no change at all, but it does seem like the archive has changed

I worded the commit message like I did because of the timestamp I saw on https://sources.cdn.openwrt.org/
and it differs a lot from the timestamp of the commit of the last bump

**Pull request closed without merging**
