### PR TITLE
Autorelease

### PR DESCRIPTION
**Pull request by aparcar**
Hi all, please test this, particularity if this slows down any building. I couldn't find any specific slowdown but I'm suspecting it could introduce some.

@nbd168 please have a look.

### CODE REVIEW

**Comment by adschm** [comment]
I wonder whether there is any case where we _want_ PKG_VERSION without PKG_RELEASE, because this would not be possible anymore?

**Comment by aparcar** [comment]
Worst case one could add an extra case that a PKG release of 0 isnt added to the filename. However I'm not aware of such case

**Comment by aparcar** [comment]
From IRC (thanks to @rsalvaterra )

> Got 8m38,150s vs 16m13,578s with your PR, so this makes it a pretty solid Yikes™. Double-checking…

Seems like it does slow things down, I'll investigate where this is happening.

**Comment by huaracheguarache** [comment]
I recently made a commit which updated the ath10k-ct package and set PKG_RELEASE=$(AUTORELEASE). You should update your PR to remove it from the Makefile: https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=package/kernel/ath10k-ct/Makefile;h=f06d7cf1320b125616069a52fcc3567cead3b5ea;hb=HEAD

**Comment by aparcar** [comment]
> EDIT: I see that I even made a typo in that commit by forgetting to add the colon before the equals sign...

I'm assuming that's bad, please create a PR to fix this.

**Comment by huaracheguarache** [comment]
> I'm assuming that's bad, please create a PR to fix this.

I've created a PR now: #4297

**Comment by jefferyto** [comment]
If packages in the base feed use AUTORELEASE, then SDKs would need to do a full checkout to compile base packages - is this correct? This would use a lot of network traffic and be a significant slowdown.

**Comment by Ansuel** [comment]
Closing this as AUTORELEASE is flagged as dropped.

**Pull request closed without merging**
