### PR TITLE
Treewide generic

### PR DESCRIPTION
**Pull request by aparcar**
treewide: add Generic subtarget if missing

As in 853e4dd OpenWrt should follow a unified structure, where every
device has a target/subtarget combination, if there is only one
subtarget, call it "Generic". This introduces predictable filenames.

 treewide: add generic subtarget to uboot

It fails to build if the uboot Makefile lacks the subtarget.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Isn't there a way to get around having those "generic/target.mk" files?

Can you tell where those are used/included?

**Comment by aparcar** [comment]
@adrianschmutzler I guess this line could be changed https://github.com/openwrt/openwrt/blob/d4190ad56cbad311663397f8b40ae0501ea46e23/target/linux/ath25/Makefile#L22

**Comment by adrianschmutzler** [comment]
This still looks like too much repetition to me. There must be a more elegant way to achieve this (or at least get rid of the target.mk file).

**Comment by adschm** [comment]
Nobody else seemed interested and I personally think (as already stated) there must a more elegant way to achieve this. So, I'm closing this now as last relevant comment is from last year anyway.

**Comment by aparcar** [comment]
It's not a nice solution, I'm happy this is closed.

**Pull request closed without merging**
