### PR TITLE
realtek: Migrate to upstream generic MIPS addresses

### PR DESCRIPTION
**Pull request by oliv3r**
Upstream generic MIPS uses 0x80100000 and 0x80100400 for the LOADADDR and ENTRY addresses. As we do not want to diverge from upstream and patch upstream when not needed, adjust our addresses as well to be future proof.

### CODE REVIEW

**Comment by oliv3r** [comment]
@svanheule this currently does not yet work, but I'm struggling to figure out why. Where else is the load address/entry address referenced/used/needed? U-Boot does properly print these addresses. But then I get zero output (as obviously something is wrong).

**Comment by oliv3r** [comment]
> Your commit is for 5.10, but you're booting 5.15? If that's not the issue, make sure your kernel was recompiled with the correct load address.

@svanheule 
I see what you are saying, and indeed, I am doing the wrong thing, however, that would mean that currently, 5.15 isn't functioning on master for rtl930x ... Let me adjust this for both targets and retest. gimme a sec.

**Comment by oliv3r** [comment]
@svanheule thanks! So obvious; cost me yet another hour or two  :S but it works correctly now on both 5.10 and 5.15.

Lets get this in, as the migration to MIPS will require this change, and having different addresses for different configs is just frustratingly annoying :) (Regardless of the saved megabyte, if that). Upstream is using this, and we don't want to mangle upstream.

```

root@OpenWrt:/# free
              total        used        free      shared  buff/cache   available
Mem:         121980       17056       90948       11616       13976       67552
Swap:             0           0           0
```

(I'll remove this comment and replace it with the output without the patch in a moment).

**Comment by janh** [comment]
Tested successfully on HPE 1920-8G and 1920-48G.

This change would also allow to remove the `relocate-kernel` step in the HPE 1920 build recipe, which was needed because the bootloader hard-codes the kernel load address to memory offset 0x100000.

**Comment by svanheule** [comment]
@janh Thanks for testing! Mind if I add that as a Tested-by?

**Comment by oliv3r** [comment]
> Tested successfully on HPE 1920-8G and 1920-48G.
> 
> This change would also allow to remove the `relocate-kernel` step in the HPE 1920 build recipe, which was needed because the bootloader hard-codes the kernel load address to memory offset 0x100000.

If you want, I can add this to this Mr as well, if you can re-test it. If you have a .patch file with your signoff, I can add it to this MR.

**Comment by svanheule** [comment]
@oliv3r I think it will be more efficient to let Jan handle that, as long as this change doesn't break HPE 1920 builds.

**Comment by oliv3r** [comment]
I think it's more efficient to actually merge a MR, rather then having 3 open ones :p but I was suggesting the same, have HIS patch part of this MR, so they are also related and grouped. Poteto, potato. I'll leave that up to you guys.

**Comment by janh** [comment]
This doesn't break on HPE 1920, it just makes relocating the kernel unnecessary, as it is already at the right address now. So, removing `relocate-kernel` reduces the boot time by a second or two.

Here is a commit that removes it: https://github.com/janh/openwrt/commit/4f99140cf4b92481ab081c9fb28b44de25ff9b73
I don't mind if you include it in this pull request, but of course I could also send a patch later.

**Comment by svanheule** [comment]
Merged with commit 44e07852856e realtek: Migrate to upstream generic MIPS addresses

@janh Feel free to send that patch out.

**Pull request closed without merging**
