### PR TITLE
tools/cmake: update to 3.24.1

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Update cmake to newest version.

### CODE REVIEW

**Comment by hnyman** [comment]
Looks like you have forgotten to update the fallback download directory...
```
PKG_SOURCE_URL:= ...
		https://cmake.org/files/v3.22/
```
Should likely be "v3.24"

**Comment by PolynomialDivision** [comment]
Thanks! Updated.

**Comment by mpratt14** [comment]
it would be nice if this gets merged first, so we dont have to worry about the *other* version number

https://github.com/openwrt/openwrt/pull/10250/commits/f74a32923c9595b0f405abfe77dab4175631a6bf

@PolynomialDivision you're welcome to pick it into this PR, if you want

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in 3b2f19271cc2cd92a4f3c184f6362c2ec2793041.

**Comment by hnyman** [comment]
@PolynomialDivision 
Next time, please remember to also refresh the patches along the version bump. 
The patches do not apply cleanly any more:

```
Applying ./patches/100-no-testing.patch using plaintext: 
patching file Modules/CTest.cmake
patching file Modules/Dart.cmake
patching file Tests/Contracts/VTK/Dashboard.cmake.in

Applying ./patches/120-curl-fix-libressl-linking.patch using plaintext: 
patching file Utilities/cmcurl/CMakeLists.txt
Hunk #1 succeeded at 594 (offset 29 lines).

Applying ./patches/130-bootstrap_parallel_make_flag.patch using plaintext: 
patching file bootstrap
Hunk #1 succeeded at 1441 (offset 18 lines).
```

`make tools/cmake/{clean,refresh}` would have taken care of that.

**Comment by PolynomialDivision** [comment]
@hnyman Thanks for spotting this. I know that you need to refresh the patches but forgot it here. :/
I made a new PR fixing it: https://github.com/openwrt/openwrt/pull/10492

**Pull request closed without merging**
