### PR TITLE
 ramips: Fix GB-PC1 cpuclock again

### PR DESCRIPTION
**Pull request by neheb**
Last change to this did not have enough 0s. Copy/Paste error I think.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Review by hauke — APPROVED** [review]

**Comment by blogic** [comment]
merged, Thanks !

**Comment by blogic** [comment]
@mkresin says the commit message needs to be improved

**Comment by mkresin** [comment]
Please mention the clock value you are intending to set. If the value is known, a mistake  can be seen.

**Comment by neheb** [comment]
Erm I mentioned 900Mhz in my previous commit. Guess I'll add it again.

**Comment by neheb** [comment]
Force pushed new version.

**Comment by mkresin** [comment]
> Erm I mentioned 900Mhz in my previous commit. Guess I'll add it again.

Yeah you did and I failed to check if the values is equal to the mentioned 900Mhz.

Anyway, this time I checked it and your patch is merged. Thanks!

**Pull request closed without merging**
