### PR TITLE
[21.02] kernel: ath10k: provide a build variant for small RAM devices

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Based on: 1ac627024de9 ("kernel: ath10k-ct: provide a build variant for
small RAM devices")

Like described in the ath10k-ct-smallbuffers version, oom-killer gets
triggered frequently by devices with small RAM.

That change is necessary for many community mesh networks which use
ath10k based devices with too little RAM. The -ct driver has been
proven unstable if used with 11s meshing and only wave2 chipsets are
supporting 11s. Freifunk Berlin is nowadays assembling its
firmware-based completely of vanilla OpenWRT with some package additions
which are made through the imagebuilder. Therefore we cannot take the
approach other freifunk communities have taken to maintain that patch
downstream [1]. Other communities consider these devices as broken and
that change would pretty much give those devices a second life [2].
[1] - https://git.freifunk-franken.de/mirror/openwrt/commit/450b306e540bc0f2c8a8841bbe4d9612f2b8cdea
[2] - https://github.com/freifunk-gluon/gluon/issues/1988#issuecomment-619532909

Signed-off-by: Simon Polack <spolack+git@mailbox.org>
Signed-off-by: Nick Hainke <vincent@systemli.org>
(cherry picked from commit 694757a08f620a9f24b70003542d9dcd0abeac46)

### CODE REVIEW

**Comment by aparcar** [comment]
Was this patch ever proposed upstream?

**Comment by PolynomialDivision** [comment]
> Was this patch ever proposed upstream?

You suggest to put that to linux-wireless?

**Comment by hauke** [comment]
Thank you for your patch, I applied it to the openwrt-21.02 branch in 27225e35382d018a59078a52fa802e5e56d6be4b.

It would be nice to get this into mainline Linux too, but probably it needs some redesign. You should probably get these sizes from device tree to allow to use the same binary driver with bigger and smaller memory.

**Comment by PolynomialDivision** [comment]
@hauke I will try to do this. :)

**Pull request closed without merging**
