### PR TITLE
ramips: mt7530: Implement set_port_link

### PR DESCRIPTION
**Pull request by FlyGoat**
set_port_link is required by swconfig to setup link mode.
Here we implemented set_port_link by touching MII PHY registers.
For autoneg enabled case, we set advertise registers to let
autoneg reach the target mode and then retrigger autoneg. For
non autoneg case, we set BMCR register to force PHY enter
desired mode.

This patch has been tested on both MT7620 and MT7621.

Signed-off-by: Jiaxun Yang <jiaxun.yang@flygoat.com>

### CODE REVIEW

**Comment by FlyGoat** [comment]
Any update?
Thanks.

**Comment by Shad0w1and** [comment]
Tested on my end and it worked like a charm. It fixes issues on 7530 not been able to get GBE wan speed on certain occasions.

**Comment by adrianschmutzler** [comment]
@981213 Maybe you can have a look here?

**Comment by lunzima** [comment]
It fixes hardware with broken PCB/U-boot such as newifi d1

**Comment by adschm** [comment]
This needs to be updated, as there is no kernel 4.14 anymore.

Apart from that, be aware that mt7621 isn't using that code anymore in master.

**Comment by FlyGoat** [comment]
I'm going to abandon this work.
The link quality have been enhanced in latest kernel.

**Comment by adschm** [comment]
Nevertheless, thanks for your effort!

**Pull request closed without merging**
