### PR TITLE
ipq40xx: switch to performance governor by default

### LINKED ISSUE #13649: IPQ4019  ethernet
### Describe the bug

Network cable directly connects router and computer.
Now the ping packet delay is greater than 2ms. This delay seems too large and abnormal.
And only openwrt firmware has this problem. Using qsdk firmware, the delay is less than 1ms.

root@OpenWrt:/# ping 192.168.1.10
PING 192.168.1.10 (192.168.1.10): 56 data bytes
64 bytes from 192.168.1.10: seq=0 ttl=64 time=0.612 ms
64 bytes from 192.168.1.10: seq=1 ttl=64 time=2.852 ms
64 bytes from 192.168.1.10: seq=2 ttl=64 time=2.719 ms
64 bytes from 192.168.1.10: seq=3 ttl=64 time=2.741 ms
64 bytes from 192.168.1.10: seq=4 ttl=64 time=2.808 ms
64 bytes from 192.168.1.10: seq=5 ttl=64 time=2.757 ms
64 bytes from 192.168.1.10: seq=6 ttl=64 time=2.626 ms

### OpenWrt version

openwrt21.02/22.03/23.05

### OpenWrt target/subtarget

ipq40xx/generic

### Device

e2600ac c1/c2

### Image kind

Official downloaded image

### Steps to reproduce

_No response_

### Actual behaviour

_No response_

### Expected behaviour

_No response_

### Additional info

_No response_

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by xback**
Doing a simple ping to my device shows this:

64 bytes from 10.0.253.101: icmp_seq=1 ttl=64 time=2.00 ms
64 bytes from 10.0.253.101: icmp_seq=2 ttl=64 time=2.02 ms
64 bytes from 10.0.253.101: icmp_seq=3 ttl=64 time=1.68 ms
64 bytes from 10.0.253.101: icmp_seq=4 ttl=64 time=1.91 ms
64 bytes from 10.0.253.101: icmp_seq=5 ttl=64 time=1.92 ms
64 bytes from 10.0.253.101: icmp_seq=6 ttl=64 time=2.04 ms

Some users even report higher values on older kernels:

64 bytes from 192.168.1.10: seq=0 ttl=64 time=0.612 ms
64 bytes from 192.168.1.10: seq=1 ttl=64 time=2.852 ms
64 bytes from 192.168.1.10: seq=2 ttl=64 time=2.719 ms
64 bytes from 192.168.1.10: seq=3 ttl=64 time=2.741 ms
64 bytes from 192.168.1.10: seq=4 ttl=64 time=2.808 ms

The problem is that the governor is set to Ondemand, which causes the CPU to clock all the way down to 48MHz in some cases.

Switching to performance governor:

64 bytes from 10.0.253.101: icmp_seq=1 ttl=64 time=0.528 ms
64 bytes from 10.0.253.101: icmp_seq=2 ttl=64 time=0.561 ms
64 bytes from 10.0.253.101: icmp_seq=3 ttl=64 time=0.633 ms
64 bytes from 10.0.253.101: icmp_seq=4 ttl=64 time=0.526 ms

In theory, using the Performance governor should increase power draw, but it looks like it really does not matter for this soc.

Using a calibrated precision DC power supply (cpu idle):

Ondemand
24.00V * 0.134A = 3.216 Watts
48.00V * 0.096A = 4.608 Watts

Performance
24.00V * 0.135A = 3.240 Watts
48.00V * 0.096A = 4.608 Watts

Let's simply switch to the Performance governor by default to fix the general jittery behaviour on devices using this soc.

Tested on: MikroTik wAP ac

Fixes: #13649

We could in theory just disable the low 48MHz operation mode, but looking at power draw using performance, there is no gain in doing so.
The device will still perform more jittery than running full-speed due to the "slow" responsiveness of the Ondemand governor.
This also avoids having to drag a patch forever altering the freq table.

@robimarko 
@f00b4r0

### CODE REVIEW

**Comment by robimarko** [comment]
LGTM, for this SoC there is no voltage scaling at all so the power draw should always be the same.
`Reviewed-by: Robert Marko <robimarko@gmail.com>`

**Comment by f00b4r0** [comment]
LGTM. Have to wonder why cpu freq scaling was implemented in the first place if it makes no power usage difference at all.
Might want to backport this to 23.05 and 22.03.

**Comment by xback** [comment]
Merged

**Comment by guidosarducci** [comment]
I'm posting after finding https://github.com/openwrt/openwrt/commit/b8e52852bd62236a2a84663b4592d221ebc64cb4 while working on another PR, and being very surprised this change was pushed through.

> Doing a simple ping to my device shows this:
> 
> 64 bytes from 10.0.253.101: icmp_seq=1 ttl=64 time=2.00 ms 64 bytes from 10.0.253.101: icmp_seq=2 ttl=64 time=2.02 ms 64 bytes from 10.0.253.101: icmp_seq=3 ttl=64 time=1.68 ms 64 bytes from 10.0.253.101: icmp_seq=4 ttl=64 time=1.91 ms 64 bytes from 10.0.253.101: icmp_seq=5 ttl=64 time=1.92 ms 64 bytes from 10.0.253.101: icmp_seq=6 ttl=64 time=2.04 ms

Yes, I remember first noticing this while developing `speedtest-netperf` ages ago, even seeing 2 - 3 ms on-box latencies. However, simply avoiding the 48 MHz CPU operating point was enough to achieve sub-millisecond times, which is fine for on-box latencies.

> In theory, using the Performance governor should increase power draw, but it looks like it really does not matter for this soc.
> 
> Using a calibrated precision DC power supply (cpu idle):

No, this needs to be tested under load. Microprocessor designers had approaches to reduce idle power-consumption decades ago. It would be surprising if testing only at idle **did** show a significant difference.

> Ondemand
> 24.00V * 0.134A = 3.216 Watts
> 48.00V * 0.096A = 4.608 Watts
> 
> Performance
> 24.00V * 0.135A = 3.240 Watts
> 48.00V * 0.096A = 4.608 Watts

This also looks like you used a PoE-supplied device, suggesting a switching regulator whose efficiency can vary with operating point. A better choice would be something that uses a fixed supply (e.g. a wall wart).

> Let's simply switch to the Performance governor by default to fix the general jittery behaviour on devices using this soc.
> 
> Tested on: MikroTik wAP ac

The device above is listed online as a single-core CPU, while I believe multi-core devices are more widely used and would better reflect power-consumption changes.

> We could in theory just disable the low 48MHz operation mode, but looking at power draw using performance, there is no gain in doing so. 

This just isn't plausible for the reasons I outlined above. I captured representative numbers using a EA6350v3 ( ipq40xx SoC, 4 core, 12 VDC), with a wall-plug power meter, and testing under load (`stress -c 4`) at each supported frequency with `mtr`.

ea6350v3_pwr_freq

The results are quite clear. We can gain most of the latency improvements with negligible change in power by only dropping the 48 MHz operating point. Setting the maximum frequency (i.e. "performance mode") is not appropriate to force on all users, since it comes with small incremental latency benefit but a large 20% power usage increase. I believe we need to revert this commit and simply disable 48 MHz as proposed in the past.

**Comment by xback** [comment]
> This also looks like you used a PoE-supplied device, suggesting a switching regulator whose efficiency can vary with operating point. A better choice would be something that uses a fixed supply (e.g. a wall wart).

No, this was measured using the DC input which in this case has a range of 8V up to 48
I measured 24V and 48V as those are most commonly input on a lot of devices (especially for PoE devices)
Agreed, 12V would have also been nice, but if the results on 24V are good, they can only be better on 12V.

> The device above is listed online as a single-core CPU, while I believe multi-core devices are more widely used and would better reflect power-consumption changes.

Mikrotik released 2 version of the Wap AC:
- [Wap AC based on ath79](https://mikrotik.com/product/RBwAPG-5HacT2HnD) (which is the single core one)
- [Wap AC based on ipq40xx](https://mikrotik.com/product/wap_ac) (which was the one used for this PR)


> The results are quite clear. We can gain most of the latency improvements with negligible change in power by only dropping the 48 MHz operating point. Setting the maximum frequency (i.e. "performance mode") is not appropriate to force on all users, since it comes with small incremental latency benefit but a large 20% power usage increase. I believe we need to revert this commit and simply disable 48 MHz as proposed in the past.

No, the results from that table are for **fixed** frequencies.
As we used OnDemand before, it quickly scales up when stressing all cores (similar to performance)
But this scaling-up takes some time,
so on very small burst loads (like a ping during idle), the soc is is still on low frequency and the ping already ended before it scaled up, leading to jittery behavior.

**Comment by robimarko** [comment]
Since this SoC doesn't have voltage scaling, there is no way it can draw more on the max OPP.

**Pull request closed without merging**
