### PR TITLE
ipq40xx: add support for kernel 5.15

### PR DESCRIPTION
**Pull request by Ansuel**
Add testing support for 5.15 for ipq40xx

Tested device:
- FritzBox 7530
- map-ac2200

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>
Reviewed-by: Robert Marko <robert.marko@sartura.hr>

### CODE REVIEW

**Comment by Ansuel** [comment]
@robimarko i wonder... want to test this?

**Comment by robimarko** [comment]
Yeah, I can do some testing tommorow.

**Comment by john-tho** [comment]
There have been a few extra devices, and target patch changes since this was branched off. From a quick look through the [target patch history](https://github.com/openwrt/openwrt/commits/master/target/linux/ipq40xx/patches-5.10), I get these:
- Extra device DTS in: https://github.com/openwrt/openwrt/blob/master/target/linux/ipq40xx/patches-5.10/901-arm-boot-add-dts-files.patch
- [ipq40xx: update 105-ipq40xx-fix-sleep-clock.patch](https://github.com/openwrt/openwrt/commit/db7a392adea0eaa2616522afb157406907d472b8)
- [kernel: move bootargs-append patch to generic](https://github.com/openwrt/openwrt/commit/81a561b4a64d3d0107e82f49e52d4d0ff1a29719)
- [ipq40xx: qcom_scm: Disable SDI at boot](https://github.com/openwrt/openwrt/commit/a93ec36630ef4ff5a2195ad613b616bffa50d00d)
- [ipq40xx: qcom_scm: Fix cold boot address command](https://github.com/openwrt/openwrt/commit/26af098e0e97124a741c5c96a824b17e7f1b6434)

Thank you very much for all your work on 5.15 & qca8k.
Will start testing soon.

**Comment by Ansuel** [comment]
@john-tho thx for the alert... give me some minutes so i refresh this.

**Comment by Ansuel** [comment]
Ok i have rebased this with the missing commit and reworked the wpj419 patch

**Comment by pkgadd** [comment]
You also might want to set `KERNEL_TESTING_PATCHVER:=5.15`, but I've successfully built this PR (at https://github.com/openwrt/openwrt/commit/17e40d0b8443334d35aaf056247bd98e5a22da9f) with kernel v5.10 and v5.15 and quickly runtime tested v5.15 on my map-ac2200/ ipq4019 (I still have to do something about it doing a continuous light show, probably involving DTS changes for the LP5523 LED controller, but that got introduced with kernel v5.10 and is **not** a regression of this PR).

**Comment by Ansuel** [comment]
@pkgadd can i add you router to the list?

**Comment by pkgadd** [comment]
Sure, of course.

**Comment by mans0n** [comment]
A typo in the last commit: `s/ipq804xx/ipq40xx/`

**Comment by Ansuel** [comment]
Fixed sorry

**Comment by Borromini** [comment]
I did a quick 'n' dirty sysupgrade on an EA6350 v3, and there's no life in it anymore now :sunglasses: Will have to see if I can get it on serial. Compilation itself went without a hiccup :stuck_out_tongue_closed_eyes:.

**Comment by Ansuel** [comment]
Fun stuff o.o
Wth went wrong ?

Il Mar 29 Mar 2022, 20:12 Borromini ***@***.***> ha scritto:

**Comment by pkgadd** [comment]
I'd bet on the kernel size just crossing 3 MB (3'184'788 bytes on my build), which is the limit set by u-boot for the ea6350v3.

**Comment by Borromini** [comment]
Yes, my money is on that too.

**Comment by pkgadd** [comment]
If you have bootloader access via serial, you could try bumping the size limit for the kernel (up to 6 MB, as the NAND partitioning reserves at most).

**Comment by pkgadd** [comment]
Btw. what's the exact kernel size of your build?

```
$ tar -xf openwrt-ipq40xx-generic-asus_map-ac2200-squashfs-sysupgrade.bin
$ ls -gG sysupgrade-asus_map-ac2200/
total 14768
-rw-r--r-- 1       22 Mar 28 00:51 CONTROL
-rw-r--r-- 1  3184788 Mar 28 00:51 kernel
-rw-r--r-- 1 11930624 Mar 28 00:51 root
```

**Comment by Borromini** [comment]
@pkgadd Looks like it's well below 3 MB:

```
$ ls -gG sysupgrade-linksys_ea6350v3/
totaal 10356
-rw-r--r-- 1      23 29 Mar 19:23 CONTROL
-rw-r--r-- 1 2870044 29 Mar 19:23 kernel
-rw-r--r-- 1 7729152 29 Mar 19:23 root
```

So kernel size shouldn't be an issue here, but I haven't tried to hook up serial yet. On my to-do.

**Comment by Gingernut1978** [comment]
Built and tested on a Netgear WAC510 used as a dumb AP.

Wired and wireless working fine.

Nice job.

**Comment by SirDMZ** [comment]
Patch failing to apply on fresh master. This is during the make stage.

Applying /home/openwrt/glnet/openwrt/target/linux/ipq40xx/patches-5.15/105-ipq40xx-fix-sleep-clock.patch using plaintext:
patching file arch/arm/boot/dts/qcom-ipq4019.dtsi
Hunk #1 FAILED at 142.
1 out of 1 hunk FAILED -- saving rejects to file arch/arm/boot/dts/qcom-ipq4019.dtsi.rej
Patch failed!  Please fix /home/openwrt/glnet/openwrt/target/linux/ipq40xx/patches-5.15/105-ipq40xx-fix-sleep-clock.patch!
make[2]: *** [Makefile:34: /home/openwrt/glnet/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.15.33/.prepared_e44e05925cb551068d191bb2d5e52718] Error 1
make[2]: Leaving directory '/home/openwrt/glnet/openwrt/target/linux/ipq40xx'
make[1]: *** [Makefile:11: menuconfig] Error 2
make[1]: Leaving directory '/home/openwrt/glnet/openwrt/target/linux'

**Comment by Gingernut1978** [comment]
Just remove the patch as It has been applied upstream.

**Comment by jmv2009** [comment]
Testing this kernel with a straight "gh pr checkout 9563" on a fritz repeater 1200 (no switch, single ethernet). My issue with the ipq40xx platform is that if I put two vlans on one bridge, there is no dhcp (or other broadcast traffic?) to the vlans. I'll check out other platforms as well. Usage example is to separate out igmp multicast traffic if the switch has no igmp snooping. Now I need to make a separate network for each client.

**Comment by robimarko** [comment]
@Ansuel Works for me on 8devices Habanero after rebase onto master as well as some minor changes in the tree:
https://github.com/sartura/openwrt/commits/ipq40xx-5.15

So, I would say that its ready after those are picked.

**Comment by Ansuel** [comment]
@robimarko nice! Will refresh this asap and add the tag to this pr

**Comment by robimarko** [comment]
Its just those two

**Comment by Ansuel** [comment]
@adschm i wonder if this can be merged

**Review by mans0n — APPROVED** [review]
Looks good to me. IMO `ipq40xx: 5:15: refresh patches` and `ipq40xx: 5.15: refresh kernel patches` could have been squashed into a single commit but no big deal.
With robimarko's Reviewed-by, I think this is ready for merge. I'll take care of this on this weekend if no one is faster than me.

**Comment by mans0n** [comment]
During a build with buildbot setting, I've encountered with this error:
```
$ make target/linux/compile
(snip)
*
* Restart config...
*
*
* Qualcomm thermal drivers
*
Qualcomm TSENS Temperature Alarm (QCOM_TSENS) [N/m/y/?] n
Qualcomm SPMI PMIC Thermal Monitor ADC5 (QCOM_SPMI_ADC_TM5) [N/m/?] (NEW)
Error in reading or end of file.

make[6]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[5]: *** [Makefile:616: syncconfig] Error 2
make[4]: *** [Makefile:729: include/config/auto.conf.cmd] Error 2
make[4]: *** [include/config/auto.conf.cmd] Deleting file 'include/generated/autoconf.h'
make[3]: *** [Makefile:25: /openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.15.35/.modules] Error 2
make[2]: *** [Makefile:11: compile] Error 2
time: target/linux/compile#1.69#0.37#2.01
```
But if I manually add `# CONFIG_QCOM_SPMI_ADC_TM5 is not set` in config-5.15 and run `make kernel_oldconfig`, it reverts back my change. Any idea?

There are also some minor changes with `make kernel_oldconfig CONFIG_TARGET=subtarget`.

And some devices now have bigger kernels. We are not going to disable them right now, though.
```
 make[3] -C target/linux install
    WARNING: Image file /openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linksys_ea6350v3-fit-zImage.itb is too big: 3147732 > 3145728
    WARNING: Image file /openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linksys_ea8300-fit-zImage.itb is too big: 3148444 > 3145728
    WARNING: Image file /openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linksys_mr8300-fit-zImage.itb is too big: 3148320 > 3145728
    ERROR: target/linux failed to build.
```

**Comment by robimarko** [comment]
Hm, was there a minor kernel update recently?
If there was one, that would explain config changes

I am building with `CONFIG_BUILDBOT` now minus the SDK, imagebuilder and SDK so will see whats going on.

And, yeah good catch on the sizes over the limit

**Comment by robimarko** [comment]
`CONFIG_QCOM_SPMI_ADC_TM5` is sorted with:
https://patchwork.ozlabs.org/project/openwrt/patch/20220430181724.1948406-1-robert.marko@sartura.hr/

But, builds are falling on antfs for me(Whatever that is)

**Comment by mans0n** [comment]
> `CONFIG_QCOM_SPMI_ADC_TM5` is sorted with:
> https://patchwork.ozlabs.org/project/openwrt/patch/20220430181724.1948406-1-robert.marko@sartura.hr/

Nice!

> As far as disabling devices goes, that should probably be postponed until 5.15 becomes the default for IPQ40xx as otherwise we are gonna stop building 5.10 images.
> Hopefully by then, users will update the device support to work with larger images

Right. I'll just add a small note in the commit message.

**Comment by mans0n** [comment]
Thanks! Applied your patchset to master.

**Comment by SirDMZ** [comment]
Hey there, it looks like this 5.15 patch was done after this commit so the patch is missing.

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=ab7e53e5cce703c7a62efbe1d41fb94c2228a178

**Comment by jmv2009** [comment]
Nope, that's a seperate PR: https://github.com/openwrt/openwrt/pull/9818

**Pull request closed without merging**
