### PR TITLE
ipq806x: fix patch and reenable Asrock g10

### PR DESCRIPTION
**Pull request by CHKDSK88**
This PR contains fix suggested by @hnyman . It also revert commit, which disables Asrock G10.

### CODE REVIEW

**Comment by adschm** [comment]
@hnyman Would you provide a Tested-by here based on your feedback in the mail thread?

**Comment by hnyman** [comment]
> Would you provide a Tested-by

Sure. The commits from this PR produces identical Kconfig and kernel .config as the version I actually run-tested earlier (with patches from Pawel's repo).

` Tested-by: Hannu Nyman <hannu.nyman@iki.fi>  (run-tested for R7800) `

**Comment by hnyman** [comment]
I just noticed that there is now a conflict in the patch 900 since the kernel bump to 5.4.86 has changed line numbering in Kconfig and in the current patch 900.  The old version of patch says now line 1838 instead of 1836.

https://github.com/openwrt/openwrt/commit/9b1b89229f0efef43a738f91875e0fd9fcc42277#diff-9ac4b9ec0ad0db5d0e2f3e3ad778e322cbe08a7ee66e834ee5aeb53f1a4bbbd4L3

Needed new line location:

```
--- a/target/linux/ipq806x/patches-5.4/900-arm-add-cmdline-override.patch
+++ b/target/linux/ipq806x/patches-5.4/900-arm-add-cmdline-override.patch
@@ -1,20 +1,20 @@
 --- a/arch/arm/Kconfig
 +++ b/arch/arm/Kconfig
-@@ -1838,6 +1838,14 @@ config ARM_ATAG_DTB_COMPAT_CMDLINE_MANGL
-         Only command line ATAG will be processed, the rest of the ATAGs
-         sent by bootloader will be ignored.
+@@ -1840,6 +1840,14 @@ config ARM_ATAG_DTB_COMPAT_CMDLINE_MANGL
...
```

**Comment by CHKDSK88** [comment]
Done.

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master

**Pull request closed without merging**
