### PR TITLE
tools/cmake: bump to 3.26.0

### PR DESCRIPTION
**Pull request by misaka36**
Release Notes:
https://cmake.org/cmake/help/v3.26/release/3.26.html

### CODE REVIEW

**Comment by BKPepe** [comment]
I would not say that the "cmake.org download URL" is useless" even though the Download page tries to point you to GitHub, where you would download the tarball, but on the same page, ``cmake.org/files`` are marked as older releases, but they include the latest files as you can see here: https://cmake.org/files/v3.26/

**Comment by lovehackintosh** [comment]
I agree with you. Change back.

**Comment by BKPepe** [comment]
Even, you removed it, there is a still one thing, which needs to be addressed as it is leftover in your commit description.

**Comment by lovehackintosh** [comment]
Updated commit message, thanks.

**Pull request merged**
