### PR TITLE
build: add comments to makefiles

### PR DESCRIPTION
**Pull request by matsievskiysv**
Add comments to build system makefile functions and variables to help developers in understanding build system internals and ease the development process.

This patch adds some documentation examples with proposed doxygen-like syntax. Hopefully, this would start the discussion and result in generation of the makefile documentation guidelines.

### CODE REVIEW

**Comment by matsievskiysv** [comment]
The relevant forum discussion may be found [at the link](https://forum.openwrt.org/t/build-system-inline-documentation/213921).

**Comment by Ansuel** [comment]
@matsievskiysv love it. Can I merge this or do you plan to add also other comments?

**Comment by matsievskiysv** [comment]
> Can I merge this or do you plan to add also other comments?

@Ansuel yes, I do plan to more, but I think it would be better to merge it now, so more people could participate in documenting.

**Comment by hnyman** [comment]
Some comments look useful, but others look made-up, just self-explanatory listing of the words in the next line (like in the device profile lines).  Some selectiveness in where to add comments would be needed

**Comment by matsievskiysv** [comment]
@hnyman I agree that some comments, particularly the `Device/Init` ones, are not all that helpful.

> Some selectiveness in where to add comments would be needed

I'll work on that in the next commits and if you don't mind, will add you as the reviewer.

**Pull request merged**
