### PR TITLE
ramips: fix tplink re200v4 led assignments for Power and Wifi (red)

### PR DESCRIPTION
**Pull request by misanthropos**
Led assignments on RE200 v3 and v4 are incorrect with DTSI definitions for the v1 version.

### CODE REVIEW

**Comment by mans0n** [comment]
Do v3 and v4 have only a single wifi red LED? (no 2g/5g in contrast to v2?) This contradicts what you described in 009e62c92c35...
IMO this should be handled by moving the led nodes to each dts, not creating another dtsi.
I think one single commit is enough to deal with it. And please fill out the commit message properly.

**Comment by misanthropos** [comment]
> Do v3 and v4 have only a single wifi red LED? (no 2g/5g in contrast to v2?) This contradicts what you described in [009e62c](https://github.com/openwrt/openwrt/commit/009e62c92c35142c5be3b375d6c393e63d2d27eb)... IMO this should be handled by moving the led nodes to each dts, not creating another dtsi. I think one single commit is enough to deal with it. And please fill out the commit message properly.

It does contradict the commit message of v2 - sadly I can not verify the information given there. At the time it looked good to me and I did knot have to knowledge how to trigger those GPIOs. One has to really look closely to spot the difference. V2-4 have a different SOC in comparison to V1 - that is reason enough for me to create a dtsi for that SOC.

**Comment by mans0n** [comment]
Err sorry, I don't understand what you mean...
Your v3 patch said there're 8x GPIO-controlled LEDs so it should have two wifi red leds...but actually you were wrong and there's only one wifi red led? (And you did not fully tested your patch at that time?)
This PR creates a new re200v3.dtsi file which is almost same as re200.dtsi except for power and wifi leds, which is not enough to justify another dtsi file IMO. Simply moving power and wifi led nodes to v2, v3, v4, and re220 dts respectively would make more sense. I don't understand why v1 matters here.

**Comment by misanthropos** [comment]
I took over the information from the v2 commit and as I said before I did not have the means to fully test it and it looked good to me. It might be v2 shows the same behaviour as v3 and v4 does.
Only later I noticed something was off and spent time to figure out how to check the GPIO settings.

Can you give me an example on how to address the GPIO settings in corresponding dts files?

**Comment by mans0n** [comment]
I mean like this:
https://git.openwrt.org/?p=openwrt/staging/mans0n.git;a=summary

It seems weird to me. Before this patch, any of LED did not blink during boot, but now the power LED is working with your patch, is it correct?
I feel we should deal with this with more caution this time, not to repeat the same mistake.

**Comment by misanthropos** [comment]
> I mean like this: https://git.openwrt.org/?p=openwrt/staging/mans0n.git;a=summary

No! I would not dare changing any of the V1 definitions because I am pretty sure the author was thorough in that attempt. It could well be the current settings are correct for V1! Unlikely but possibly even for V2.
So if you are going to change every single dts, then you need to add the entries you removed from dtsi to a new v1 dts file. 

But now I see why my first attempts to just modify dts files did not work. I thought it possible to simply redefine some values and maybe undo others - but adding same definitions led to compile errors which in turn led me to my solution to simply create a new dtsi file (and that fact of a different SOC for v2,v3,v4)

I still think my solution has more charme because it could well be that SOC has other differences as well, and one does not need to repeat the same code in every dts file and add on more dts file for v1. After all those are just definitions and wont affect binary sizes, right?

> 
> It seems weird to me. Before this patch, any of LED did not blink during boot, but now the power LED is working with your patch, is it correct? I feel we should deal with this with more caution this time, not to repeat the same mistake.

Green wifi leds worked as they should - so I never missed red. I have no clue on which conditions the device might turn on red wifi, except the user does on purpose.

By nature of this device it has to be plugged into a power outlet itself. Labels on its front are very small symbols in light grey on white. Normally power outlets are to be found just a short distance from floor. From a distance of a meter or more you barely see, if at all, that it is the ethernet led right next to power blinking and I think was not aware of a power led.

This time however I tested and confirmed correct led settings.

**Comment by mans0n** [comment]
> No! I would not dare changing any of the V1 definitions because I am pretty sure the author was thorough in that attempt. It could well be the current settings are correct for V1! Unlikely but possibly even for V2.
So if you are going to change every single dts, then you need to add the entries you removed from dtsi to a new v1 dts file.

Err, v1 uses mt7620a so it does not import `mt7628an_tplink_re200.dtsi`. (Instead it imports `mt7620a_tplink_re2x0-v1.dtsi`.) I've changed every dts files that import re200.dtsi so it should be okay. ;)

> I still think my solution has more charme because it could well be that SOC has other differences as well, and one does not need to repeat the same code in every dts file and add one more dts file for v1.

Instead you're duplicating the whole dtsi, which produces a larger diff.

> After all those are just definitions and wont affect binary sizes, right?

AFAIK yes.

> This time however I tested and confirmed correct led settings.

Okay, but I still would like to have more testers with this. It looks like there are some users with RE200 v{2,3,4} and RE220 v2 in the forum, maybe we can ask them for reviews.

**Comment by misanthropos** [comment]
> Err, v1 uses mt7620a so it does not import mt7628an_tplink_re200.dtsi. (Instead it imports mt7620a_tplink_re2x0-v1.dtsi.) I've changed every dts files that import re200.dtsi so it should be okay. ;)

In that case it should be fine indeed.

**Comment by misanthropos** [comment]
Can we assume correctness by now?

**Comment by mans0n** [comment]
Did you ask RE200 users in the forum for validation and test? I believe we need some confirmations to make this go forward.

**Comment by hauke** [comment]
A similar patch fixing the problem was applied in 02aa7a2bb9b6bdc8033d30c97f5b49534206a37c, see #11165.

**Pull request closed without merging**
