### PR TITLE
realtek: add support for APRESIA ApresiaLightGS120GT-SS

### PR DESCRIPTION
**Pull request by musashino205**
This patch series adds support for APRESIA ApresiaLightGS120GT-SS.
This depends on mtdsplit changes (https://github.com/openwrt/openwrt/pull/11553).

bootlog: https://gist.github.com/musashino205/fca2f5f5db9d3028470d93251e0bb813

### CODE REVIEW

**Comment by svanheule** [comment]
It's a bit of a hassle, but can you split this up in device support, and trailing patches to enable the dual-boot feature? That way only the second part of the series would be blocked by PR #11553 .

**Comment by musashino205** [comment]
OK, I'll update this PR ;)

**Comment by musashino205** [comment]
UPDATE:

- remove dependency of bootindex support on mtdsplit
  - update flash instruction in the commit message

**Comment by svanheule** [comment]
Thanks for the update! Merged the patches to master.

**Pull request closed without merging**
