### PR TITLE
tools/mkimage: workaround version.h build failure

### PR DESCRIPTION
**Pull request by ivan-dives**
cherry-pick upstream commit e1df3fa364a5f0d8b4c589c29c0f304d69a0121c

Signed-off-by: Ivan Diorditsa <ivan.diorditsa@gmail.com>

### CODE REVIEW

**Comment by ynezz** [comment]
Your commit message lacks the information why is this change needed, anyway, shouldn't it be just enough to bump the version to the latest 2019.1 release?

**Comment by ynezz** [comment]
Are you going to address the requested changes and move forward with this PR?

**Comment by hauke** [comment]
I created a U-Boot update here:
https://patchwork.ozlabs.org/patch/1098467/
Please check if this fixes your problem.

**Comment by ynezz** [comment]
@ivan-dives Ping.

**Comment by adrianschmutzler** [comment]
This is closed as the original author did not respond at all.

It can be reopened if there is some progress.

**Pull request closed without merging**
