### PR TITLE
toolchain: gcc: update to 13.3

### PR DESCRIPTION
**Pull request by NukeMania**
Release Notes:
https://gcc.gnu.org/pipermail/gcc/2024-May/243980.html

Remove upstreamed patches:
- patches-13.x/020-Include-safe-ctype.h-after-C-standard-headers-to-avo.patch
- patches-13.x/021-libcc1-fix-vector-include.patch
- patches-13.x/400-LoongArch-Fix-MUSL_DYNAMIC_LINKER.patch
- patches-13.x/401-LoongArch-Modify-MUSL_DYNAMIC_LINKER.patch

Refresh patches:
- patches-13.x/300-mips_Os_cpu_rtx_cost_model.patch
- patches-13.x/970-macos_arm64-building-fix.patch

Signed-off-by: Olcay Korkmaz <nuke_mania@hotmail.com>

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
I'm not sure if your author name applies with our contribution guidelines since we require real name or known identity.
https://openwrt.org/submitting-patches#submission_guidelines

**Review by hauke — APPROVED** [review]
LGTM, the removed patches are really integrated upstream.

**Comment by NukeMania** [comment]
> I'm not sure if your author name applies with our contribution guidelines since we require real name or known identity. https://openwrt.org/submitting-patches#submission_guidelines

indeed it's my name but it's was without last name 
pushed with full name as author title

**Comment by PolynomialDivision** [comment]
You also need to change the author name to match your signed off.
`git commit --amend --author="..."`

**Comment by PolynomialDivision** [comment]
Merged. Thanks a lot! :)

**Pull request merged**
