### PR TITLE
ramips: ASUS RT-AX53U use space in NAND

### PR DESCRIPTION
**Pull request by gabest11**
This is mostly the same patch for this router as this one https://github.com/openwrt/openwrt/pull/10502

I left the last 8MB unallocated and added Alisa900's suggestion about NMBM https://github.com/openwrt/openwrt/pull/10502#issuecomment-1236708434

The changes have been tested and do not brick the device, but to see the extra partition space, the settings must be reset during sysupdate.

kernel log: https://gist.github.com/gabest11/d545327c99041ae76fd5ab00dc9bd237

### CODE REVIEW

**Comment by mans0n** [comment]
It would be nice if you elaborate the commit message more...

BMT range should not include ubi partition area, for example:
https://github.com/openwrt/openwrt/blob/c27279dc26a26b8ad054882d4c5f86a85526fd16/target/linux/ramips/dts/mt7621_h3c_tx180x.dtsi#L71-L74

> The changes have been tested and do not brick the device, but to see the extra partition space, the settings must be reset during sysupdate.

So sysupgrade with keeping the settings does not brick the device? I thought mtd and ubi partition does not depend on the settings, could you explain why it should be reset?

**Comment by gabest11** [comment]
This router has 128MB nand flash. The ASUS firmware occupies 2x50MB (Kernel, Kernel2) and there is also a jffs2 partition in the left-over space, just before the bad block area. 

If someone converts it to OpenWRT now (writes the factory image into Kernel), there will be a 4MB partition for the linux kernel, a smaller rootfs, and a larger rootfs_data. All inside the first 50MB. This leaves second half of the NAND space completely unused.

I can't comment on BMT, I took the "mediatek,nmbm;" line from the comment in the previous pull request. It seems to produce a meaningful dmesg output.

When I first attempted a sysuprgade, left the keep settings checked and it came back with the same UBI partition size, despite already showing the extended range in the kernel log. Next I did a sysupgrade without the check and it filled the whole size.

**Comment by gabest11** [comment]
> BMT range should not include ubi partition area

0x0000007e0000-0x000007800000 : "ubi"

I think the area you a refering to is the last 8MB. It's between 7800000-8000000.

**Comment by mans0n** [comment]
> When I first attempted a sysupgrade, I left the "keep settings" checked and it came back with the same UBI partition size, despite already showing the extended range in the kernel log. Next I did a sysupgrade without the check and it filled the whole size.

Hmm, perhaps the mtd size was increased but the ubi partition was kept as is?
Then we might need to increase `DEVICE_COMPAT_VERSION` to force users not to keep settings during sysupgrade.
```
  DEVICE_COMPAT_VERSION := 1.2
  DEVICE_COMPAT_MESSAGE := ubi partition has been resized blah blah
```
It would be great if we can hear more test reports from other testers, to be safe.

> I think the area you a referring to is the last 8MB. It's between 7800000-8000000.

No, the ubi partition should also be excluded, as UBI has its own bad block management scheme, and it does not get along well with NMBM.

**Comment by gabest11** [comment]
> Hmm, perhaps the mtd size was increased but the ubi partition was kept as is? 

That's what I observed.

> Then we might need to increase `DEVICE_COMPAT_VERSION` to force users not to keep settings during sysupgrade.
> 
> ```
>   DEVICE_COMPAT_VERSION := 1.2
>   DEVICE_COMPAT_MESSAGE := ubi partition has been resized blah blah
> ```
> 
> It would be great if we can hear more test reports from other testers, to be safe.

Definitely. I hope more people will notice this router. It is probably the cheapest with wifi 6 around here (only does 80mhz though) and the easiest to convert to openwrt. It appeared under the more generic rt-ax1800u name a few months ago, with a huge price cut compared to rt-ax53u, but it's still the same device.

> No, the ubi partition should also be excluded, as UBI has its own bad block management scheme, and it does not get along well with NMBM.

The ASUS firmware was not using UBI and the reserved 8MB probably matches the other 120MB in size, with the number of entries and such. The bootloader also seem to depend on it, someone bricked the device by erasing it, there is a [link to his adventures](https://forum.openwrt.org/t/asus-rt-ax53u-bricked-but-talks-on-lan1/128692) in the previous pull request. 

Honestly, I don't know enough about this to be more helpful, other then continously testing it in this new configuration, this is my main wifi ap at home now.

**Comment by Alisa900** [comment]
Indeed, ubi manages the bad blocks in its partitions on its own and therefore it should be excluded from NMBM management.

I also had to reset when doing sysupdate to get extra space.

@gabest11, please apply the patch (not yet tested by me) to this commit:
```
--- a/target/linux/ramips/dts/mt7621_asus_rt-ax53u.dts
+++ b/target/linux/ramips/dts/mt7621_asus_rt-ax53u.dts
@@ -54,6 +54,9 @@
 	status = "okay";
 
 	mediatek,nmbm;
+	mediatek,bmt-max-ratio = <1>;
+	mediatek,bmt-max-reserved-blocks = <64>;
+	mediatek,bmt-remap-range = <0x000000 0x7e0000>;
 
 	partitions {
 	compatible = "fixed-partitions";
```

**Comment by gabest11** [comment]
Okay, but I can only test it tomorrow, not at home atm.

**Comment by gabest11** [comment]
> > There is still the issue with partition resizing. How does DEVICE_COMPAT_* work?
> 
> It will display an incompatibility warning when using sysupgrade, reminding the user not to keep the configuration. I guess not keeping the config doesn't fix the partition size, maybe you need to format the ubi partition before upgrading: `mtd erase ubi`. This command is dangerous if the device doesn't have tftp recovery mode.
> 
> The right way is back to stock firmware and then install OpenWrt again. This process can destroy and rebuild ubi. These info may help:
> 
> ```
>   DEVICE_COMPAT_VERSION := 1.2
>   DEVICE_COMPAT_MESSAGE := Please back to stock firmware and then install OpenWrt again xxx
> ```

I can see now where this goes now. In target/linux/ramips/image/mt7621.mk, there are sections for each device. Basically it goes under "define Device/asus_rt-ax53u", right?

**Comment by DragonBluep** [comment]
Yes. It's better to set IMAGE_SIZE to kernel size + ubi size. This variable seems to be used to limit the size of the binary image file and is not related to the partition size.

**Comment by gabest11** [comment]
I re-did the asuswrt => openwrt official 1.1 => my build 1.2 upgrade path.

First I choose to keep the settings and rebooted.

image

Version stayed at 1.1, but that's also what the [documentation says](https://openwrt.org/docs/guide-quick-start/admingui_sysupgrade_keepsettings#forcing_upgrade).
```
root@OpenWrt:~# uci show | grep version
system.@system[0].compat_version='1.1'
```

Next time I did an upgrade with full reset (checkboxes cleared) and got all the extra storage space. However, compat_version is still 1.1. I expected this to be 1.2.

> Consequently, as a forced update won't reset your config, it also won't bump your compat-version, and you will have to do that manually afterwards, e.g.

A forced update won't reset, but what if I reset? Still no version bump?

**Comment by DragonBluep** [comment]
@gabest11 try to add
```
	asus,rt-ax53u)
		ucidef_set_compat_version "1.2"
		;;
```
between line 10 and line 11:
https://github.com/openwrt/openwrt/blob/20581ee8b590afc56cda013272861e1e614a078e/target/linux/ramips/mt7621/base-files/etc/board.d/05_compat-version#L10-L11

**Comment by gabest11** [comment]
That was it! 

Looking at all the 05_compat-version files, not many devices needed a version bump so far.

**Comment by DragonBluep** [comment]
BTW, another improvement: you can create a firmware partition and include the kernel and ubi in it. In this way, it is very convenient for user to restore the stock firmware using the mtd command. https://github.com/openwrt/openwrt/commit/37753f34ac68fbd70730aa37a6b8b94ad3215d85

**Comment by gabest11** [comment]
Are the offsets relative to the parent? I can't find any info on nested paritions.

**Comment by Alisa900** [comment]
There is not much documentation on devicetree, but here:
https://www.kernel.org/doc/Documentation/devicetree/bindings/mtd/partition.txt
https://www.kernel.org/doc/Documentation/devicetree/bindings/mtd/partitions/partition.yaml
https://www.kernel.org/doc/Documentation/devicetree/bindings/mtd/partitions/fixed-partitions.yaml

I can’t say anything about the strange layout, but this is not a requirement for returning to stock firmware, since mtd partitions are just an abstraction (or rather, a structure in RAM) in the kernel are not written to the flash chip.
If we add a fireware partition, then only one command will be required to restore to stock firmware:
```
mtd -r write <imagefile> firmware
```

Here is an example with subpartitions from fixed-partitions.yaml:
```
    partitions {
        compatible = "fixed-partitions";
        #address-cells = <1>;
        #size-cells = <1>;

        partition@0 {
            label = "bootloader";
            reg = <0x000000 0x100000>;
            read-only;
        };

        firmware@100000 {
            compatible = "brcm,trx";
            label = "firmware";
            reg = <0x100000 0xe00000>;
        };

        calibration@f00000 {
            compatible = "fixed-partitions";
            label = "calibration";
            reg = <0xf00000 0x100000>;
            ranges = <0 0xf00000 0x100000>;
            #address-cells = <1>;
            #size-cells = <1>;

            partition@0 {
                label = "wifi0";
                reg = <0x000000 0x080000>;
            };

            partition@80000 {
                label = "wifi1";
                reg = <0x080000 0x080000>;
            };
        };
    };
```

And a small test:
```
root@OpenWrt:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 000e0000 00020000 "u-boot"
mtd1: 00100000 00020000 "u-boot-env"
mtd2: 00100000 00020000 "factory"
mtd3: 00100000 00020000 "factory2"
mtd4: 07420000 00020000 "firmware"
mtd5: 00400000 00020000 "kernel"
mtd6: 07020000 00020000 "ubi"
root@OpenWrt:~# nanddump -l 0x400000 /dev/mtd4 | md5sum
ECC failed: 0
ECC corrected: 0
Number of bad blocks: 0
Number of bbt blocks: 0
Block size 131072, page size 2048, OOB size 64
Dumping data starting at 0x00000000 and ending at 0x00400000...
a5ab52c5522deab979fe26707b93681e  -
root@OpenWrt:~# nanddump /dev/mtd5 | md5sum
ECC failed: 0
ECC corrected: 0
Number of bad blocks: 0
Number of bbt blocks: 0
Block size 131072, page size 2048, OOB size 64
Dumping data starting at 0x00000000 and ending at 0x00400000...
a5ab52c5522deab979fe26707b93681e  -
root@OpenWrt:~#
```
The conclusion is that the data from firmware partition with length 0x400000 and data from kernel partition are equivalent, which means that the kernel addresses these partitions correctly.

**Comment by gabest11** [comment]
I think clicking sync fork was a mistake. Now this automation thing has problems.

@Alisa900 If you write the asus image to firmware, will it work without the copy in Kernel2?

**Comment by Alisa900** [comment]
The original firmware image also contains the Kernel2 partition and will be written to the flash chip.

**Comment by Alisa900** [comment]
Hmm... for this model, Asus has assembled a bootloader without dual image support.

Partial content of config_rtax53u:
```
# CONFIG_MTK_DUAL_IMAGE_SUPPORT is not set
```

And here is what is said in "MTK MT7621 U-Boot User Manual.pdf":
```
2.2.3.11 Dual image support
Dual image support is a mechanism for image/firmware backup and recovery.
This feature requires two MTD partitions: the main firmware partition, which store the firmware to be booted.
And the backup firmware partition, which only stores the backup firmware.
When u-boot tries to boot firmware, it will first check the integrity of the firmware in both partitions.
If both firmware are correct, u-boot will boot the firmware in the main partition.
If one of the firmware is damaged, it will be replaced by the firmware from another partition.
If both firmware are damaged, u-boot will not be the firmware.
Just for notice: currently only the kernel part is capable of integrity checking. Rootfs part has only a simple
data checking.
```

**Comment by Alisa900** [comment]
Some suspicious silence... Is the second attempt to merge also a failure?

Offtop (interpersonal interaction):
gabest11, did I accidentally offend you?

**Comment by gabest11** [comment]
I don't know what's happening. I wish we could go back to subversion. The pull request is here, my repo is there, if anyone wants it, they can find it.

**Comment by matmo** [comment]
@gabest11, the tests seem to be failing because of the included merge commit (1a6634fd). A solution would be to rebase the three other commits onto openwrt master. I did this [in my branch](https://github.com/matmo/openwrt/tree/asus_rtax53u_use_nand), so you can pull them into your repo if you want. HTH

**Comment by gabest11** [comment]
How exactly do I do that?

**Comment by Alisa900** [comment]
@gabest11, here is the official git documentation:
https://git-scm.com/book/en/v2
https://git-scm.com/book/en/v2/Git-Branching-Rebasing
https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches

Run these commands in your git repository:
```
git remote add upstream https://github.com/openwrt/openwrt.git
git fetch upstream
git branch upstream upstream/master
git rebase upstream
git branch -d upstream # optional, it removes the "upstream" branch added earlier
git remote remove upstream # also not required. since the "upstream" branch has been deleted, the remote repository is no longer needed
git push
```

**Comment by matmo** [comment]
The advice above is not correct, the merge commit would be still in there. This however should do:

```
git checkout -b ca161d3f1b asus_use_nand
git push origin asus_use_nand
```

Then change the compare branch in this PR from `gabest11:master` to `gabest11:asus_use_nand`. 

Alternatively you can delete the merge commit using `git reset --hard ca161d3f1b` followed by a force push `git push -f`.

**Comment by gabest11** [comment]
I reset it already but got scared of the forced push and waited for suggestions.

**Comment by gabest11** [comment]
Has anyone seen ci_helpers.sh?

**Comment by Alisa900** [comment]
I wonder if this request will merge before the new year?

**Comment by Djfe** [comment]
me too

just a suggestion:
You could move the comment from line 108 in the dts file to line 55
and maybe adjust it since we now know, it's nmbm. (it's not just an assumption)
and explain that the remap range excludes the ubi partition

**Comment by DragonBluep** [comment]
> Has anyone seen ci_helpers.sh?

You can rebase onto upstream master branch to solve the CI error.

**Comment by Djfe** [comment]
I like making the amount of usable flash larger for the ubi partition, but if we don't care about flash wear on upgrades, then we could do it like this and actually make use of firmware2 as a fallback in-case an update fails, so the bootloader can load firmware2 instead of the device bootlooping.
https://github.com/openwrt/openwrt/blob/5c7e4a9d2e25d5ecc33c3c2650e4f954936c9c69/target/linux/ramips/mt7621/base-files/lib/upgrade/platform.sh#L44

**Comment by Alisa900** [comment]
@gabest11, after acceptance #11612 into upstream, a rebase will be needed to merge this request.

**Comment by Djfe** [comment]
If you've got the time, then you only need to do:
```
git fetch upstream
git rebase upstream/master
git push -f
```
the force is needed because you actually delete the old commits and then place them at the end of your master branch on github after pulling updates. It's like you apply your commits after the last commit on the official branch openwrt/master (which is the so called upstream)

**Comment by Djfe** [comment]
reply to https://github.com/openwrt/openwrt/pull/10685#issuecomment-1249597109
About making nested fixed-partitions @Alisa900 @DragonBluep 
We could technically make this a major compat version increase that would prevent people from using sysupgrade (even with -n), but is that really worth it?
Making one update harder so people can return to stock without Asus's Recovery tool if they did a backup before flashing openwrt.
I'm not so sure. Especially since you could use backups of the stock partitions "linux" and "rootfs" instead.

**Comment by gabest11** [comment]
I'm quickly losing interest in the maze of git command. Could someone else do a PR instead and delete this?

**Comment by Znevna** [comment]
I think the flag is set at compile time, the device behaves as described in "Dual image support".

**Comment by Djfe** [comment]
> I'm quickly losing interest in the maze of git commands. Could someone else do a PR instead and delete this?

ok, here is the new PR: #11806 
You are able to close this PR yourself (I can't, only maintainers would be able to close it).

**Pull request closed without merging**
