### PR TITLE
tfa-layerscape: fix build issue

### PR DESCRIPTION
**Pull request by biwenli**
build log:
        pkgbuild stdio:

        In file included from fiptool.h:16:0,
                         from fiptool.c:19:
        fiptool_platform.h:18:27: fatal error: openssl/sha.h: No such file or directory  #  include <openssl/sha.h>
                                   ^
        compilation terminated.
        Makefile:50: recipe for target fiptool.o failed
        make[4]: *** [fiptool.o] Error 1
        Makefile:749: recipe for target tools/fiptool/fiptool failed
        make[3]: *** [tools/fiptool/fiptool] Error 2
        make[3]: Leaving directory /builder/shared-workdir/build/build_dir/target-aarch64_generic_musl/tfa-layerscape-ls1012ardb/tfa-layerscape-lsdk-1903
        Makefile:135: recipe for target /builder/shared-workdir/build/build_dir/target-aarch64_generic_musl/tfa-layerscape-ls1012ardb/tfa-layerscape-lsdk-1903/.built failed

Signed-off-by: Biwen Li <biwen.li@nxp.com>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by ynezz** [comment]
@biwenli this looks overcomplicated, what about following https://github.com/ynezz/openwrt/commit/f6060397eeedc066f8b1f07070ed97f021fdfd29 ?

**Comment by biwenli** [comment]
@ynezz ok,i will update pull request following your suggestions.

**Comment by biwenli** [comment]
@ynezz Hi,ynezz,thank you so much,it's Okay.

**Comment by ynezz** [comment]
Ok, I've just pushed my version of fix to master, will wait for the buildbot feedback and if it's ok, then I'm going to cherry-pick this fix into 19.07 as well.

**Comment by biwenli** [comment]
> Ok, I've just pushed my version of fix to master, will wait for the buildbot feedback and if it's ok, then I'm going to cherry-pick this fix into 19.07 as well.

Thanks,wait you of good news.

**Comment by ynezz** [comment]
Seems like there are more host tools like `create_pbl` and `byte_swap`, which need to be fixed properly:

```
# -a option appends the image for Chassis 3 devices in case of non secure boot
aarch64-openwrt-linux-musl-gcc -Wall -Werror -pedantic -std=c99 -O2 -DVERSION='"v1.5(release):reboot-10604-ge9216b3336"' -D_GNU_SOURCE -D_XOPEN_SOURCE=700  -c -o create_pbl.o create_pbl.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
  LD      create_pbl
/usr/bin/ld: create_pbl.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: create_pbl.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: create_pbl.o: Relocations in generic ELF (EM: 183)
create_pbl.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:43: recipe for target 'create_pbl' failed
make[4]: *** [create_pbl] Error 1
plat/nxp/tools/pbl_ch2.mk:45: recipe for target 'pbl' failed
make[3]: *** [pbl] Error 2
```

**Comment by biwenli** [comment]
@ynezz Ok,got it,i will fix it.

**Comment by biwenli** [comment]
@ynezz hi, i have added a commit to fix the problem.commit as below:
https://github.com/openwrt/openwrt/pull/2267/commits/dfb1138eac565cd12970b167c938d3db7a2bd023

**Comment by biwenli** [comment]
> Seems like there are more host tools like `create_pbl` and `byte_swap`, which need to be fixed properly:
> 
> ```
> # -a option appends the image for Chassis 3 devices in case of non secure boot
> aarch64-openwrt-linux-musl-gcc -Wall -Werror -pedantic -std=c99 -O2 -DVERSION='"v1.5(release):reboot-10604-ge9216b3336"' -D_GNU_SOURCE -D_XOPEN_SOURCE=700  -c -o create_pbl.o create_pbl.c
> cc1: note: someone does not honour COPTS correctly, passed 0 times
>   LD      create_pbl
> /usr/bin/ld: create_pbl.o: Relocations in generic ELF (EM: 183)
> /usr/bin/ld: create_pbl.o: Relocations in generic ELF (EM: 183)
> /usr/bin/ld: create_pbl.o: Relocations in generic ELF (EM: 183)
> create_pbl.o: error adding symbols: File in wrong format
> collect2: error: ld returned 1 exit status
> Makefile:43: recipe for target 'create_pbl' failed
> make[4]: *** [create_pbl] Error 1
> plat/nxp/tools/pbl_ch2.mk:45: recipe for target 'pbl' failed
> make[3]: *** [pbl] Error 2
> ```

Hi,i have added a commit to fix the problem.commit as below:
https://github.com/openwrt/openwrt/commit/dfb1138eac565cd12970b167c938d3db7a2bd023

**Comment by ynezz** [comment]
Ok, pushed 83d5ca2186f7801d94f336e09f8db0a2c5c5d97f so let's see how this pans out.

**Comment by ynezz** [comment]
> Ok, pushed 83d5ca2 so let's see how this pans out

Seems to be fixed in master.

**Comment by ynezz** [comment]
> > Ok, pushed [83d5ca2](https://github.com/openwrt/openwrt/commit/83d5ca2186f7801d94f336e09f8db0a2c5c5d97f) so let's see how this pans out
> 
> Seems to be fixed in master.

And in 19.07 as well, thanks!

**Comment by biwenli** [comment]
> > > Ok, pushed [83d5ca2](https://github.com/openwrt/openwrt/commit/83d5ca2186f7801d94f336e09f8db0a2c5c5d97f) so let's see how this pans out
> > 
> > 
> > Seems to be fixed in master.
> 
> And in 19.07 as well, thanks!

Okay,you are welcome.

**Pull request closed without merging**
