### PR TITLE
igmpproxy: remove package and move it to packages repo

### PR DESCRIPTION
**Pull request by ja-pa**
This PR removes igmpproxy package from openwrt repo and moves it to packages repo (related packages MR https://github.com/openwrt/packages/pull/15061)

The proposal for this change was raised in openwrt/openwrt#3819

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Review by rsalvaterra — APPROVED** [review]

**Comment by hnyman** [comment]
This removal PR should be merged, as the PR adding igmpproxy to the packages feed has already been merged a few days ago.

Currently there is always a duplicate error at the feeds install step:
```
perus@ub2010:/Openwrt/r7800$ ./scripts/feeds install -a
Installing all packages from feed packages.
WARNING: Not overriding core package 'igmpproxy'; use -f to force
Installing all packages from feed luci.
Installing all packages from feed routing.
```

**Comment by adschm** [comment]
Has this been discussed with @nbd168 package maintainer.

Apart from that, please add a commit message telling _why_ this is moved to packages feed.

I would merge if both things are taken care of.

**Comment by ja-pa** [comment]
The commit message was updated. 

@nbd168  Is it ok for you to move igmpproxy to packages?

**Comment by adschm** [comment]
Thanks, will merge that later today.

**Pull request closed without merging**
