### PR TITLE
ramips: allow USB power control on TP-Link MR3020v3

### PR DESCRIPTION
**Pull request by iDm1**
By switching EPHY_LED4_N_JTRST_N from EPHY_LED4_N to GPIO#39 
we can control USB port power an all current revisions of MR3020v3. 
It was not a thing on some first revisions, pin was unused.
But for now on all current MR3020v3 boards EPHY_LED4_N_JTRST_N pin 
is connected to USB power key. 
Also it was not used as EPHY indicator on any revision of the board.

Signed-off-by: Dmitry Chigiryov <dmitry.chigiryov@ya.ru>

### CODE REVIEW

**Comment by adschm** [comment]
This has formal issue. Please visit https://openwrt.org/submitting-patches#submission_guidelines another time.

**Comment by adschm** [comment]
Ping.

**Comment by iDm1** [comment]
Is formal issue resolved?

**Comment by adschm** [comment]
How can you resolve the issue by not changing anything?

Note that there is a difference between the _PR_ and the _commit_ ...

**Comment by adschm** [comment]
Apart from the formal issues still not being resolved, I wonder what changing state_default will help without setting up the GPIO somewhere?

**Comment by iDm1** [comment]
MT7628N pins are multipurpose. EPHY_LED4_N_JTRST_N pin is configured as EPHY_LED4_N by default and GPIO#39 is not available. This patch changes EPHY_LED4_N_JTRST_N pin to work as GPIO#39.

You can find this in MT7628N documentation or in other patches for devices that are using MT7628N.
http://vonger.cn/upload/MT7628_Full.pdf
https://lists.openwrt.org/pipermail/openwrt-devel/2019-March/022161.html

**Comment by mans0n** [comment]
You should change your *commit message*, not just the PR description.
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes#know_the_difference_between_the_pr_pull_request_and_the_commit

For the USB power control, you'd also want a dedicated GPIO line which can be handy.
https://github.com/openwrt/openwrt/blob/b0d5939b80008aca8090832eb9918b998f08e8f3/target/linux/ramips/dts/mt7628an_zyxel_keenetic-extra-ii.dts#L74

**Comment by mans0n** [comment]
Please squash your changes into a single commit.
https://openwrt.org/docs/guide-developer/working-with-github-pr#squashing_commits

mt7628an.dtsi does not have &gpio1 node anymore, you'd better test your patch on your device before a push.

And the mail addresses in author and SoB line does not match, please arrange that as well.

**Comment by iDm1** [comment]
GitHub is friendly for such changes.

**Comment by iDm1** [comment]
Created a new pull request #9340

**Pull request closed without merging**
