### PR TITLE
Improve support for MikroTik devices in DTS targets

### PR DESCRIPTION
**Pull request by f00b4r0**
This PR mirrors the two patch series submissions here:

https://patchwork.ozlabs.org/project/openwrt/list/?series=171373
https://patchwork.ozlabs.org/project/openwrt/list/?series=171381

Please refer to the following covers which detail in great length the rationale for each of these submissions:
https://patchwork.ozlabs.org/project/openwrt/cover/20200420131336.18252-1-hacks@slashdirt.org/
https://patchwork.ozlabs.org/project/openwrt/cover/20200420133503.18700-1-hacks@slashdirt.org/

The purpose of this PR is to get maximum exposure for these proposals, as the goal is to set the foundation for MikroTik in ath79, as well as other targets (ramips and possibly ipq40xx, see #2417).

Additionally, selective backport in 19.07 will be possible to restore WLAN for some supported devices which have switched to a different encoding scheme for caldata (known cases: newer mAP Lite now compress in LZO - `MAGIC_ERD` - vs bare RLE-encoding previously, PR #2729 is another more complex example using `MAGIC_LZOR`). #2850 illustrates another problem that this PR addresses.

### CODE REVIEW

**Comment by xback** [comment]
@rogerpueyo 
Purely fyi

**Comment by adrianschmutzler** [comment]
When merging from this source, please take care to exclude the merge commits ...

**Comment by rogerpueyo** [comment]
Hi @xback @f00b4r0 ,

I just tested it on the mikrotik,routerboard-wap-g-5hact2hnd (wAP AC), everything seems to be running fine. Namely:
 - boot / board detection / MTD partitions
 - mac addresses, radios, calibration data
 - /sys/firmware/mikrotik

:+1:

**Comment by f00b4r0** [comment]
@TobleMiner if you can give it one last shot on ramips (to test 3d6531f in particular) :)

**Comment by f00b4r0** [comment]
FTR: above changes pushed are only formatting, no code change.

**Comment by TobleMiner** [comment]
3d6531f7d0bdc6b9de023f411e66e16767414306 LGTM

Patch works fine on my RBM33g

**Comment by f00b4r0** [comment]
> [3d6531f](https://github.com/openwrt/openwrt/commit/3d6531f7d0bdc6b9de023f411e66e16767414306) LGTM
> 
> Patch works fine on my RBM33g

Thanks! Quick question: on these devices, what is supposed to receive the "base" MAC? I'm surprised that both WAN and LAN get incremented: does it match the sticker on the device?

**Comment by TobleMiner** [comment]
Good question. The sticker lists two mac adresses:

```
E01: <base mac>
E03: <base mac + 2>
```

Looking at https://i.mt.lv/cdn/rb_files/RBM33-1565865697.png E01 and E03 are probably the two lan ports.

Thus assigning `<base mac + 1>` to the wan interface and using `<base mac>` for lan might be more faithful to the original setup in RouterOS.

**Comment by f00b4r0** [comment]
@TobleMiner Thanks, I'll update the patch to do that.

**Comment by f00b4r0** [comment]
ping

**Comment by adrianschmutzler** [comment]
This has been merged, and will be backported in a different shape, so let's close the PR now.

Thanks to all people involved!

**Pull request closed without merging**
