### PR TITLE
toolchain/gcc: switch to version 11 by default

### PR DESCRIPTION
**Pull request by aparcar**
gcc10 seem to increase build size and gcc11 seem to fix that.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Review by rsalvaterra — APPROVED** [review]
LGTM. Feel free do add my reviewed-by.

**Review by hauke — APPROVED** [review]
When you run some tests please add the results to the commit message.

**Comment by stintel** [comment]
Ideally this is runtime-tested on several different targets, and mentioned in the commit message as @hauke suggested.

**Review by stintel — CHANGES_REQUESTED** [review]
Ideally this is runtime-tested on several different targets, and mentioned in the commit message as @hauke suggested. And ideally also at least build-tested for several targets, with CONFIG_ALL=y.

**Comment by tapper82** [comment]
Hi I built and ran on my r7800 C7-V2 and a wdr3600. All with no issues. I did not build all packages.

**Comment by abajk** [comment]
Tested-by: Aleksander Jan Bajkowski <olek2@wp.pl> # tested on BT Home Hub 5A

**Review by abajk — APPROVED** [review]

**Comment by neheb** [comment]
mips with CONFIG_ALL compiles

**Comment by aparcar** [comment]
I've compiled all targets with buildbot settings, the outcome looks good except for bcm63xx, for which @neheb already provided a patch.

Testing of all targets available here: https://github.com/aparcar/openwrt/actions/runs/1250461209

Testing of likely fixed bcm63xx here: https://github.com/aparcar/openwrt/actions/runs/1251467913 - it should be done in about 90 minutes

In both cases artifacts are provided which can be downloaded and runtime tested.

**Comment by anomeome** [comment]
Been running with GCC11 on mvebu(mamba, rango) for ~2 months since the initial hurdles were overcome.

**Review by stintel — APPROVED** [review]

**Comment by stintel** [comment]
> I've compiled all targets with buildbot settings, the outcome looks good except for bcm63xx, for which @neheb already [provided a patch](https://github.com/openwrt/openwrt/pull/4575).

I've approved, but please mention what's been tested in the commit message.

**Comment by joaochainho** [comment]
Successful runtime tests with ath79 / Netgear WNDR3800, GCC11+5.10 kernel.

**Comment by aparcar** [comment]
This is blocked by https://github.com/openwrt/openwrt/pull/4575

**Comment by CHKDSK88** [comment]
@aparcar 
> 
> Testing of all targets available here: https://github.com/aparcar/openwrt/actions/runs/1250461209
> 

I ran Your image for P2020RDB board (mpx85xx/p2020). It works as expected:

```
[    0.000000] Memory CAM mapping: 256/256/256 Mb, residual: 256Mb
[    0.000000] Linux version 5.4.145 (builder@buildhost) (gcc version 11.2.0 (OpenWrt GCC 11.2.0 r17531-f413e4835e)) #0 SMP Sat Sep 18 18:59:31 2021
[    0.000000] Using P2020 RDB machine description
```
So:
`Tested-by: Pawel Dembicki <paweldembicki@gmail.com>`

**Pull request closed without merging**
