### PR TITLE
master. Enabled support for xr819 radio module and Allwinner H2+ soc-AUDIO 

### PR DESCRIPTION
**Pull request by melsem**
Branch master!!
[Enabled support for xr819 radio module and soc-AUDIO on device-sun8i-h2-plus-orangepi-zero](https://github.com/melsem/openwrt). This repository is a mirror of https://git.openwrt.org/openwrt/openwrt.git

And the patch itself. [dts-add-usb2-usb3-soc_codec-opi_zero-wifi_xradio_xr819_openwrt-master.patch](https://github.com/melsem/openwrt-lede_xradio-xr819_soc-audio/blob/master/openwrt-master-Snapshot-17.04.2019.20-30/dts-add-usb2-usb3-soc_codec-opi_zero-wifi_xradio_xr819_openwrt-master.patch)

[Patches for each file separately.](https://github.com/melsem/openwrt-lede_xradio-xr819_soc-audio/tree/master/openwrt-master-Snapshot-17.04.2019.20-30/all-files-patch)

### CODE REVIEW

**Comment by dedeckeh** [comment]
Each of the commits has multiple formal issues:

-  the git commit subject has no prefix for each commit

- none of the commits have a git commit description explaining what you're changing

- a SoB is missing for each commit

Please have a look at https://openwrt.org/submitting-patches#submitting_patches

**Comment by ysc3839** [comment]
https://github.com/ysc3839/openwrt/tree/opi0-xr819
Here's my commits of your files, not including sound codec.

**Comment by melsem** [comment]
> https://github.com/ysc3839/openwrt/tree/opi0-xr819
> Вот мои коммиты ваших файлов, не включая звуковой кодек. 
> Проверено, но не работает. Показывает «Беспроводной не связан».

The file package/kernel/mac80211/**Makefile** changed incorrectly.
Patch for [/package/kernel/mac80211/**Makefile**](https://github.com/melsem/openwrt-lede_xradio-xr819_soc-audio/blob/master/openwrt-master-Snapshot-17.04.2019.20-30/all-files-patch/Makefile.patch)

**Comment by ysc3839** [comment]
I moved xr819 firmware to separate package.
https://github.com/ysc3839/openwrt/tree/opi0-xr819/package/firmware/xr819-firmware

**Comment by melsem** [comment]
Update

**Pull request closed without merging**
