### PR TITLE
kirkwood: solidify SATA_PMP config

### PR DESCRIPTION
**Pull request by mans0n**
SATA_PMP option is no longer exposed when no SATA host driver is enabled
since upstream linux commit bd322af15ce9 ("ata: make SATA_PMP option
selectable only if any SATA host driver is enabled").

Commit 1bb3f593ee73 ("kirkwood: update config for kernel 5.10") manually
added CONFIG_SATA_PMP=y to config file, but the config will disappear for
every kernel_oldconfig refresh.

To prevent this, a small hack is added, which selects SATA_HOST
automatically when SATA_PMP is enabled. This patch can be dropped if
SATA_MV is ever re-added into kernel config file.

### CODE REVIEW

**Comment by CHKDSK88** [comment]
I build image for Netgear ReadyNAS v2. Config looks good:

```
cat ./build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.10.42/.config | grep SATA
CONFIG_SATA_HOST=y
CONFIG_SATA_PMP=y
CONFIG_SATA_AHCI=m
CONFIG_SATA_MOBILE_LPM_POLICY=0
# CONFIG_SATA_AHCI_PLATFORM is not set
# CONFIG_SATA_INIC162X is not set
# CONFIG_SATA_ACARD_AHCI is not set
CONFIG_SATA_SIL24=m
# CONFIG_SATA_QSTOR is not set
# CONFIG_SATA_SX4 is not set
# SATA SFF controllers with BMDMA
CONFIG_SATA_MV=m
CONFIG_SATA_NV=m
# CONFIG_SATA_PROMISE is not set
CONFIG_SATA_SIL=m
# CONFIG_SATA_SIS is not set
# CONFIG_SATA_SVW is not set
# CONFIG_SATA_ULI is not set
CONFIG_SATA_VIA=m
# CONFIG_SATA_VITESSE is not set
CONFIG_PHY_MVEBU_SATA=y
```

Image works as expected:
```
[    2.877992] sata_mv f1080000.sata: slots 32 ports 2
[    2.887020] scsi host0: sata_mv
[    2.891202] scsi host1: sata_mv
[    2.894488] ata1: SATA max UDMA/133 irq 33
[    2.898634] ata2: SATA max UDMA/133 irq 33
[    3.398237] ata1: SATA link up 3.0 Gbps (SStatus 123 SControl F300)
[    3.428315] ata1.00: ATA-8: ST500LT012-1DG142, 1003YAM1, max UDMA/133
[    3.434787] ata1.00: 976773168 sectors, multi 16: LBA48 NCQ (depth 31/32)
[    3.498309] ata1.00: configured for UDMA/133
[    3.502887] scsi 0:0:0:0: Direct-Access     ATA      ST500LT012-1DG14 YAM1 PQ: 0 ANSI: 5
[    3.511934] sd 0:0:0:0: [sda] 976773168 512-byte logical blocks: (500 GB/466 GiB)
[    3.519484] sd 0:0:0:0: [sda] 4096-byte physical blocks
[    3.525724] sd 0:0:0:0: [sda] Write Protect is off
[    3.530647] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    3.858935] sd 0:0:0:0: [sda] Attached SCSI disk
[    4.018241] ata2: SATA link up 3.0 Gbps (SStatus 123 SControl F300)
[    4.048313] ata2.00: ATA-8: ST500LT012-1DG142, 1003YAM1, max UDMA/133
[    4.054787] ata2.00: 976773168 sectors, multi 16: LBA48 NCQ (depth 31/32)
[    4.118308] ata2.00: configured for UDMA/133
[    4.122843] scsi 1:0:0:0: Direct-Access     ATA      ST500LT012-1DG14 YAM1 PQ: 0 ANSI: 5
[    4.131878] sd 1:0:0:0: [sdb] 976773168 512-byte logical blocks: (500 GB/466 GiB)
[    4.139422] sd 1:0:0:0: [sdb] 4096-byte physical blocks
[    4.145538] sd 1:0:0:0: [sdb] Write Protect is off
[    4.150450] sd 1:0:0:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    4.479449] sd 1:0:0:0: [sdb] Attached SCSI disk
```

Refresh config works as expected.

`Tested-by: Pawel Dembicki <paweldembicki@gmail.com>`

**Comment by mans0n** [comment]
@CHKDSK88 Thanks for your test!

Added a simple description to the patch file.

**Comment by CHKDSK88** [comment]
I think, if this PR  and #4299 will be merged, we could switch to 5.10.

**Comment by adschm** [comment]
@hauke Can you have a look whether we want to accept a hack like that?
The problem is real and described very well by the initial post (the option really disappears with every refresh).
I do hesitate to accept a hack that modifies "expected" kernel behavior, though.

**Comment by mans0n** [comment]
If this is accepted, we might apply it to sunxi as well...

**Comment by argonym** [comment]
Shouldn't `config SATA_PMP` rather go into generic?

**Comment by hauke** [comment]
Thank you for the patches, I applied them.
I move the patch to generic/hack-5.10 to also use it on sunxi. Then I added a patch to change the sunxi configuration too.

**Pull request closed without merging**
