### PR TITLE
kirkwood: add 5.15 kernel

### PR DESCRIPTION
**Pull request by CHKDSK88**
This patch series adds 5.15 testing kernel for kirkwood target.

Compile tested: all devices.
Run tested: Endian 4i.

### CODE REVIEW

**Comment by mans0n** [comment]
Could you consider moving `KERNEL_TESTING_PATCHVER:=5.15` to the last commit? And IMO copying and refreshing patches in a same commit compromises the purpose of patch splitting...

I would split the patches in this way:

1. (optional) Refresh config for kernel 5.10
2. Copy config and patches to kernel 5.15
3. Refresh patches for kernel 5.15
4. (optional) Add missing symbol in generic 5.15
5. Update config for kernel 5.15
6. Set testing kernel version to 5.15

**Comment by CHKDSK88** [comment]
@mans0n 

> Could you consider moving `KERNEL_TESTING_PATCHVER:=5.15` to the last commit? And IMO copying and refreshing patches in a same commit compromises the purpose of patch splitting...
> 

Done.

> I would split the patches in this way:
> 
>     1. (optional) Refresh config for kernel 5.10
> 

No needed.

>     2. Copy config and patches to kernel 5.15
> 

Done

>     3. Refresh patches for kernel 5.15
> 

No needed. 

>     4. (optional) Add missing symbol in generic 5.15
> 
>     5. Update config for kernel 5.15
> 
>     6. Set testing kernel version to 5.15

Done.

**Comment by mans0n** [comment]
Thanks, I'll do build test and merge this on this weekend.

**Comment by mans0n** [comment]
Thanks! Applied your patchset to master.

**Pull request closed without merging**
