### PR TITLE
toolchain: fix stampfile and cleanup dependencies

### PR DESCRIPTION
**Pull request by mcprat**
some minor Makefile cleanup for the toolchain

### CODE REVIEW

**Comment by Ansuel** [comment]
Wonder if we should introduce ci toolchain tests

**Comment by mpratt14** [comment]
@dhewg would you like to test this out btw?

**Comment by dhewg** [comment]
Works for me, that nicely aligns well with the comment blob above.

Is $libc/utils redundant? Coffee may not yet kicked in, but I can't even find it? Heh

**Comment by dhewg** [comment]
Seems to be a uclibc leftover, see c3caa1b768728fc9daf833c55f846d6bc2362efb and 63fb175203bbf3b336804587c2f5b3a2d8132ec1
Do you mind removing that step and comment while you're at it?

**Comment by hauke** [comment]
Please rebase, we have a toolchain CI now.

**Comment by mpratt14** [comment]
nice catch, I assumed that was for `glibc`

commit 5d19a38d8008411f06b8beb265d94890690f562b shows the change more clearly

the title suggests, however, that it can also used with `eglibc`
I don't know if its still possible to use that library here... never heard of it ¯ \ _ (ツ) _ / ¯

**Comment by mpratt14** [comment]
their website says for 2.19 (8 years, 4 months ago)

```
This is the final release branch of EGLIBC; users and developers should now move back
to GLIBC and develop it as needed in accordance with the goals of EGLIBC
```

whats the best way to make sure glibc doesn't need that line?

**Comment by dhewg** [comment]
The two above commits add/remove toolchain/uClibc/utils/Makefile and the in-tree musl and glibc don't have it.
The target doesn't exist and nothing is calling it, it's just a dead dependency AFAICT

**Comment by mpratt14** [comment]
I agree

googling things got me too confused, the utils directory would be in our source not their source...haha

**Comment by dhewg** [comment]
Just built a toolchain successfully with this hunk on top:
```
@@ -46,7 +46,6 @@ ifeq ($(CONFIG_EXTERNAL_TOOLCHAIN),)
 
   $(curdir)/$(LIBC)/compile:=$(curdir)/gcc/initial/compile $(curdir)/kernel-headers/compile
   $(curdir)/gcc/final/compile:=$(curdir)/$(LIBC)/compile
-  $(curdir)/$(LIBC)/utils/compile:=$(curdir)/gcc/final/compile
 endif
 
 ifndef DUMP_TARGET_DB
```

**Comment by mpratt14** [comment]
i was slow to update, how does it look now? :-)

**Review by dhewg — APPROVED** [review]

**Comment by mpratt14** [comment]
final thoughts:

maybe the stampfile names should be in rules.mk, so it is a common variable in both the toolchain's Makefile and gcc's common.mk?

**Comment by dhewg** [comment]
I wouldn't for just this, LGTM as is

**Pull request merged**
