### PR TITLE
nftables: bump to version 0.9.2

### PR DESCRIPTION
**Pull request by rockdrilla**
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by rockdrilla** [comment]
NB: merge #2179 first.

**Comment by rockdrilla** [comment]
Changes:
- disable building Python-related stuff;
- cherry-pick necessary patches from upstream.

**Comment by hauke** [comment]
This is a pretty huge size increase, is there something new activated?

**Comment by dengqf6** [comment]
[nftables 0.9.2 and libnftnl 1.1.4 released](https://netfilter.org/news.html#2019-08-19b)

**Comment by rockdrilla** [comment]
@dengqf6, thanks.

**Comment by n8v8R** [comment]
@hauke is there a reason why this PR is not getting merged into Master, and subsequently perhaps uplifted to the 19.x branch?

**Comment by hauke** [comment]
Thank you, your patch was applied to master.

**Pull request closed without merging**
