### PR TITLE
Add FXS support for TP-Link Archer VR200v

### PR DESCRIPTION
**Pull request by Aeronaut**
I done this patch in past LEDE from 04.11.2017.
Now I want to Update my router to latest openwrt. But now the TAE ports are silent and dmesg reports following 10 messages every time I restart asterisk:

> [   69.843176] Read Cmd MBX overslept.
> [   70.047189] Read Cmd MBX overslept.
> [   70.251204] Read Cmd MBX overslept.
> [   70.455176] Read Cmd MBX overslept.
> [   70.659174] Read Cmd MBX overslept.
> [   70.863206] Read Cmd MBX overslept.
> [   71.067186] Read Cmd MBX overslept.
> [   71.271189] Read Cmd MBX overslept.
> [   71.475214] Read Cmd MBX overslept.
> [   71.679187] Read Cmd MBX overslept.
I will try some older openwrt and report back if I find out something new...

### CODE REVIEW

**Comment by Aeronaut** [comment]
I found out, that this error comes from drv_vmmc-1.9.0/src/drv_vmmc_api.c Line 332 and there is a Comment: OS problem with blocking or waking up. This is not an immediate error but needs investigation.
If I understand right, this error does not mean that the firmware isn't loaded correctly, so overall not path leading...
Any hint how to dig deeper are welcome.

**Comment by Aeronaut** [comment]
[Full bootlog](https://pastebin.com/gmEiRJYi)

**Comment by Aeronaut** [comment]
Thanks to Plonk34, now the POTS are working!

**Comment by hauke** [comment]
Please squash this together into one commit and add a commit description with a Singed-off-by line.

How is this related to #1534 ?

**Comment by blogic** [comment]
will merge the other version of the patch

**Pull request closed without merging**
