### PR TITLE
omap: add support and switch to kernel 6.1

### PR DESCRIPTION
**Pull request by dhewg**
Simple and fast change, since this target has no patches on its own.
Lightly tested on boneblack.

### CODE REVIEW

**Comment by dhewg** [comment]
There's a bunch of enabled kernel configs that are likely not required, like ISDN or some of the PHYs.
I didn't bother combing through the supported boards to determine what's required.
Boot log: [log.txt](https://github.com/openwrt/openwrt/files/14208405/log.txt)

**Comment by PolynomialDivision** [comment]
I guess the last two commits are a bit fast. ^^ Normally adding 6.1 testing and after some time going to 6.1 by default.

**Comment by alexeys85** [comment]
We use kernel 6.1 since beginning on our BBB based board which is different in only just additional ethernet, its rock solid. But we dont use bridge functions.

**Review by alexeys85 — APPROVED** [review]

**Comment by PolynomialDivision** [comment]
For me it looks good. Do you still want feedback from the others?

**Comment by lynxis** [comment]
It seems I overlooked the notification. (Not related to this issue, but always fine to ping my via mail).

So the reason why omap went source only were the upstream in the ethernet driver.
Upstream didn't used DSA instead they went for hardcoded vlans in the device tree to differentiate the ports the packet came from and went through.

This also broke the default build on the BBB.

**Pull request merged**
