### PR TITLE
ipq40xx: delete files used for building 5.10 kernel

### PR DESCRIPTION
**Pull request by PolynomialDivision**
The kernel 5.15 now defaults. Remove unnecessary files.

### CODE REVIEW

**Comment by robimarko** [comment]
Can you rebase this?

It would be good to remove 5.10 from ipq40xx, no point in people having to add patches for it.

**Comment by PolynomialDivision** [comment]
> Can you rebase this?

Done. We could also have used your PR. Just wanted to point out that we did the same. ;)

**Comment by robimarko** [comment]
Nah, I forgot that you made one, no point in a second PR.

**Comment by ynezz** [comment]
Thanks, merged in 65f606fb82e00d

**Pull request closed without merging**
