### PR TITLE
ath79: remove gpio-export USB support

### PR DESCRIPTION
**Pull request by neheb**
Regulators are the upstream solution for this.

Not currently tested, but it should work.

### CODE REVIEW

**Comment by neheb** [comment]
hrm it doesn't work right on my archer c7v2 looks like. The USB ports work, indicating the GPIO is turned on. But I don't know if it can be turned off. poweroff/halt does not turn the GPIO off.

**Comment by john-tho** [comment]
> hrm it doesn't work right on my archer c7v2 looks like. The USB ports work, indicating the GPIO is turned on. But I don't know if it can be turned off. poweroff/halt does not turn the GPIO off.

(Some time ago) I looked at a problem with ath79 ar300m USB power control: https://github.com/john-tho/openwrt/commit/2bfd0a327a322ab71896a49189c96cf3515dd945. Then, and for that device I thought: fixed regulator was added to DTS, and referenced from the
"generic-ehci" USB controller node. ehci-platform.c is not a regulator
consumer, so no kernel devlinks were built between the supplier node
reg_usb_vbus, and the consumer usb0. This meant that the regulator was
never enabled. A workaround now would be to use a userspace consumer `regulator-output`, example: https://github.com/openwrt/openwrt/blob/52b6c9247997e51a97f13bb9e94749bc34e2d52e/target/linux/mvebu/files-6.6/arch/arm64/boot/dts/marvell/armada-7040-rb5009.dts#L51

On mt7621, the usb controller is a regulator consumer, so with the same setup, unbind of the USB driver powered down the GPIO.

**Comment by neheb** [comment]
right. my idea was to modify the phy driver to add regulator support. Doesn't look like it's a good idea.

**Comment by Leo-PL** [comment]
> hrm it doesn't work right on my archer c7v2 looks like. The USB ports work, indicating the GPIO is turned on. But I don't know if it can be turned off. poweroff/halt does not turn the GPIO off.

Userspace GPIO switches then, maybe?

**Comment by Leo-PL** [comment]
I took a glance at the patch, and to fully be able to control power, these regulators should interface with USB (root) hub driver, which is able to control port power - perhaps then `uhubctl` could handle controlling these.

**Comment by neheb** [comment]
Uhubctl… is that even packaged here?

That’s what I figured. I thought the phy driver would be an alternative. Looks like no.

**Comment by neheb** [comment]
Alright so, it seems I misunderstood that you have to explicitly disable the regulator in power_off.

It works now.

**Comment by john-tho** [comment]
> Alright so, it seems I misunderstood that you have to explicitly disable the regulator in power_off.
> 
> It works now.

Super.

Could you please consider adding more details to the commit message (that's why I missed the adding phy driving regulator part of the change earlier, sorry):
At least that regulator support is added to our ?downstream phy driver (how and why might also help).
possibly also an example of how to power off and power on a port (does unbind / bind work here)?

Thanks.

**Comment by neheb** [comment]
I tried to figure it out. I couldn't.

However, 

It seems there's a userspace utility that handles this: uhubctl

If I do

```
uhubctl -a 0 -l 2
```

My USB device's light turns off. Same thing happens with halt/poweroff. I also see dmesg output saying the device disconnects/reconnects with

```
uhubctl -a 1 -l 2
```

Interestingly enough, it only powers off on phy1 and not phy0. I'm guessing the GPIO is wrong for my Archer?

**Comment by neheb** [comment]
so I just found out that phy-core.c supports specifying a regulator called

```
phy-supply
```

Meaning we don't even need to patch the USB PHY driver.

@robimarko what do you think?

**Comment by DragonBluep** [comment]
`CONFIG_REGULATOR_FIXED_VOLTAGE=y` symbol should be moved to https://github.com/openwrt/openwrt/blob/main/target/linux/ath79/config-6.6 as some devices belong to the `ath79/nand` target.

**Comment by DragonBluep** [comment]
I've tested it on NETGEAR R6100. `uhubctl` tool can disconnect the usb connection, but it can not cut off the USB power supply. After executing `uhubctl -a 0`, the USB port can still charge my phone.

**Comment by neheb** [comment]
On my archer c7v2 when connecting a hub and a serial USB adapter, the LED for the hub turns off but not the serial adapter. Not sure what to make of it.

**Comment by Leo-PL** [comment]
`uhubctl` uses userspace USB accesses to control the hub, so hub driver itself likely isn't even aware about changes it does. So the data lines get disabled correctly, but the power does not. And kernel driver doesn't allow direct userspace power control, like it did in the past, only the autosuspend thing. So it looks like we're out of luck here.

**Comment by neheb** [comment]
hrm unfortunate.

**Comment by neheb** [comment]
@981213 it seems you added the only user of phy-supply in ath79: https://github.com/openwrt/openwrt/commit/0997342f24a00

do you have any insight here?

**Comment by neheb** [comment]
aha. I think I got it:

```
target/linux/ath79/dts/ar9330.dtsi:                     compatible = "chipidea,usb2";
```

**Pull request closed without merging**
