### PR TITLE
iptables: update to 1.6.2

### PR DESCRIPTION
**Pull request by Ansuel**
Update to new iptables release.
Tested on ip806x

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by dedeckeh** [comment]
Please add in the commit description the change log overview for 1.6.2 by adding the output of git log --oneline in the iptables git repo

**Comment by Ansuel** [comment]
@dedeckeh done ;)

**Comment by Ansuel** [comment]
No merge?

**Comment by dedeckeh** [comment]
@Ansuel I've been testing iptables 1.6.2 on my arm-virt target; but I hit the following issue
`iptables -L -vn
Fatal: can't open lock file /run/xtables.lock: No such file or directory
`
I did not yet find time to dig further into the issue

**Comment by Ansuel** [comment]
@dedeckeh found the problem... (my bad that i didn't notice that)
with this new version they introduced this lock file.... as in openwrt we don't have a run directory (we have it in the /tmp ) iptables try to create a file in a non existing directory (/run) 
(i notice a compile option to change it... this should fix the problem.. will test now)

**Comment by Ansuel** [comment]
@dedeckeh fixed

**Comment by dedeckeh** [comment]
Thanks; pulled into my staging tree (https://git.openwrt.org/?p=openwrt/staging/dedeckeh.git;a=commit;h=4ce4ada10b61fc82643ace053ece32c3ed7b450e)

**Pull request closed without merging**
