### PR TITLE
toolchaini/gcc: fix libstdc++ dual abi model

### PR DESCRIPTION
**Pull request by avengermsoft**
Hello to all.

Parameter "with-default-libstdcxx-abi=new" must be set for parameter "enable-libstdcxx-dual-abi" to work.

Info:
[dual abi](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html)

Signed-off-by: Ivan Maslov <avenger_msoft@mail.ru>

### CODE REVIEW

**Comment by avengermsoft** [comment]
From code gcc "gcc-11.2.0\libstdc++-v3\include\bits\c++config". Parameter "_GLIBCXX_USE_CXX11_ABI(with-default-libstdcxx-abi=new)" is disabled if parameter "_GLIBCXX_USE_DUAL_ABI(libstdcxx-dual-abi)" is not set. 

```
#define _GLIBCXX_USE_DUAL_ABI

#if ! _GLIBCXX_USE_DUAL_ABI
// Ignore any pre-defined value of _GLIBCXX_USE_CXX11_ABI
# undef _GLIBCXX_USE_CXX11_ABI
#endif

#ifndef _GLIBCXX_USE_CXX11_ABI
#define _GLIBCXX_USE_CXX11_ABI
#endif
```

When I run a third party application [Jackett](https://github.com/Jackett/Jackett) get errors:
```
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED2Ev: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm: symbol not found
Error relocating /tmp/publish/jackett: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEPKcmm: symbol not found
Error relocating /tmp/publish/jackett: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEcm: symbol not found
Error relocating /tmp/publish/jackett: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12find_last_ofEPKcmm: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8_M_eraseEmm: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE14_M_replace_auxEmmmc: symbol not found
Error relocating /tmp/publish/jackett: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEcm: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ERKNS_12basic_stringIcS2_S3_EESt13_Ios_Openmode: symbol not found
Error relocating /tmp/publish/jackett: _ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EES4_: symbol not found
Error relocating /tmp/publish/jackett: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE17find_first_not_ofEPKcmm: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm: symbol not found
Error relocating /tmp/publish/jackett: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ESt13_Ios_Openmode: symbol not found
Error relocating /tmp/publish/jackett: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm: symbol not found
Error relocating /tmp/publish/jackett: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEmmRKS4_: symbol not found
Error relocating /tmp/publish/jackett: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEmmPKc: symbol not found
Error relocating /tmp/publish/jackett: _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE: symbol not found
Error relocating /tmp/publish/jackett: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE: symbol not found
```

**Comment by neheb** [comment]
wow that is...surprising.

The original desire was to build only the C++11 ABI.

**Comment by avengermsoft** [comment]
For example, the file  "openwrt-toolchain-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64\toolchain-aarch64_generic_gcc-11.2.0_musl\aarch64-openwrt-linux-musl\include\c++\11.2.0\aarch64-openwrt-linux-musl\bits\c++config.h" contains the following compilation options 
```
# define _GLIBCXX_USE_DUAL_ABI 0

#if ! _GLIBCXX_USE_DUAL_ABI
// Ignore any pre-defined value of _GLIBCXX_USE_CXX11_ABI
# undef _GLIBCXX_USE_CXX11_ABI
#endif

#ifndef _GLIBCXX_USE_CXX11_ABI
# define _GLIBCXX_USE_CXX11_ABI 0
#endif
```

**Comment by avengermsoft** [comment]
@neheb  What do you think of these changes?

**Comment by neheb** [comment]
What's the ipk size increase?

**Comment by avengermsoft** [comment]
@neheb 

For NanoPi R4S
```
Before: 428260 bytes
After:  562837 bytes
Delta:  134577 bytes
```

**Comment by neheb** [comment]
gotta love how huge newer versions of libstdc++ get.

**Comment by neheb** [comment]
weird. I'm getting this error with sumo:

```
[133/679] Building CXX object src/libtraci/CMakeFiles/libtracistatic.dir/TrafficLight.cpp.o
FAILED: src/libtraci/CMakeFiles/libtracistatic.dir/TrafficLight.cpp.o
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/bin/powerpc64-openwrt-linux-musl-g++  -I/home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src -isystem /home/mangix/devstuff/openwrt/staging_dir/target-powerpc64_e5500_musl/usr/include/freetype2 -Og -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0=sumo-1.12.0 -Werror=format -Werror=format-security -DPIC -fpic -fstack-protector-strong -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -std=c++11 -pthread -Wall -pedantic -Wextra -DNDEBUG -fPIC -MD -MT src/libtraci/CMakeFiles/libtracistatic.dir/TrafficLight.cpp.o -MF src/libtraci/CMakeFiles/libtracistatic.dir/TrafficLight.cpp.o.d -o src/libtraci/CMakeFiles/libtracistatic.dir/TrafficLight.cpp.o -c /home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/libtraci/TrafficLight.cpp
/home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/libtraci/TrafficLight.cpp: In static member function 'static void libtraci::TrafficLight::setNemaCycleLength(const string&, double)':
/home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/libtraci/TrafficLight.cpp:364:59: error: call of overloaded 'to_string(double&)' is ambiguous
  364 |     setParameter(tlsID, "NEMA.cycleLength", std::to_string(cycleLength));
      |                                             ~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from /home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/string:55,
                 from /home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/foreign/tcpip/storage.h:30,
                 from /home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/libsumo/StorageHelper.h:22,
                 from /home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/libtraci/TrafficLight.cpp:26:
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6659:3: note: candidate: 'std::string std::to_string(int)'
 6659 |   to_string(int __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6670:3: note: candidate: 'std::string std::to_string(unsigned int)'
 6670 |   to_string(unsigned __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6678:3: note: candidate: 'std::string std::to_string(long int)'
 6678 |   to_string(long __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6689:3: note: candidate: 'std::string std::to_string(long unsigned int)'
 6689 |   to_string(unsigned long __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6697:3: note: candidate: 'std::string std::to_string(long long int)'
 6697 |   to_string(long long __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6709:3: note: candidate: 'std::string std::to_string(long long unsigned int)'
 6709 |   to_string(unsigned long long __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/libtraci/TrafficLight.cpp: In static member function 'static void libtraci::TrafficLight::setNemaOffset(const string&, double)':
/home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/libtraci/TrafficLight.cpp:369:54: error: call of overloaded 'to_string(double&)' is ambiguous
  369 |     setParameter(tlsID, "NEMA.offset", std::to_string(offset));
      |                                        ~~~~~~~~~~~~~~^~~~~~~~
In file included from /home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/string:55,
                 from /home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/foreign/tcpip/storage.h:30,
                 from /home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/libsumo/StorageHelper.h:22,
                 from /home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/src/libtraci/TrafficLight.cpp:26:
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6659:3: note: candidate: 'std::string std::to_string(int)'
 6659 |   to_string(int __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6670:3: note: candidate: 'std::string std::to_string(unsigned int)'
 6670 |   to_string(unsigned __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6678:3: note: candidate: 'std::string std::to_string(long int)'
 6678 |   to_string(long __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6689:3: note: candidate: 'std::string std::to_string(long unsigned int)'
 6689 |   to_string(unsigned long __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6697:3: note: candidate: 'std::string std::to_string(long long int)'
 6697 |   to_string(long long __val)
      |   ^~~~~~~~~
/home/mangix/devstuff/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-11.2.0_musl/powerpc64-openwrt-linux-musl/include/c++/11.2.0/bits/basic_string.h:6709:3: note: candidate: 'std::string std::to_string(long long unsigned int)'
 6709 |   to_string(unsigned long long __val)
      |   ^~~~~~~~~
ninja: build stopped: subcommand failed.
make[2]: *** [Makefile:58: /home/mangix/devstuff/openwrt/build_dir/target-powerpc64_e5500_musl/sumo-1.12.0/.built] Error 1
make[2]: Leaving directory '/home/mangix/devstuff/openwrt/feeds/packages/utils/sumo'
time: package/feeds/packages/sumo/compile#134.17#8.23#0.00
    ERROR: package/feeds/packages/sumo failed to build.
make[1]: *** [package/Makefile:116: package/feeds/packages/sumo/compile] Error 1
make[1]: Leaving directory '/home/mangix/devstuff/openwrt'
make: *** [/home/mangix/devstuff/openwrt/include/toplevel.mk:230: package/sumo/compile] Error **2**
```

this PR fixes it.

The real question is whether or not to continue using libstdc++ or use libc++ from LLVM. I'm thinking of the former although the latter is smaller.

**Comment by neheb** [comment]
nvm this PR does nothing. Still broken.

**Comment by avengermsoft** [comment]
@neheb Please start the workflow pending approval.

**Comment by neheb** [comment]
I'm not a core developer

**Comment by kskog** [comment]
Would be great if we could get this into the next release. This issue blocks .NET 6 development on OpenWrt.

**Comment by kskog** [comment]
Actually, to make .NET 6 apps work in all cases, musl must also be upgraded to 1.2 so that `__fstatat_time64` is defined and it can handle time correctly beyond 2038. [musl time64](https://musl.libc.org/time64.html)

See [this](https://github.com/dotnet/sdk/issues/24448#issuecomment-1073888341) github comment.

I also made a separate issue for musl 1.2 https://github.com/openwrt/openwrt/issues/9497

**Comment by am11** [comment]
On 64-bit OpenWrt, musl 1.1.24 is fine. `musl time64` only concerns 32-bit platforms.

However, this PR is needed to run .NET on all OpenWrt supported architectures.

**Comment by neheb** [comment]
@hauke can you merge and back port this?

**Comment by kskog** [comment]
@am11 I have now re-compiled OpenWrt with `--enable-libstdcxx-dual-abi` as the diff in this PR indicates, but I still get the same errors..

**Comment by am11** [comment]
You mean missing `__cxx` symbols? @avengermsoft [wrote above](https://github.com/openwrt/openwrt/pull/5014#issuecomment-1024983626):
> There are no errors with the patch.

for a .NET application (Jackett), so maybe he can provide some insights.

**Comment by avengermsoft** [comment]
> @am11 I have now re-compiled OpenWrt with `--enable-libstdcxx-dual-abi` as the diff in this PR indicates, but I still get the same errors..

[Look here](https://github.com/Jackett/Jackett/pull/12886#issuecomment-1046033860)

**Comment by kskog** [comment]
My build is based on v21.02.0 and in this version GCC default version is 8.4.0:

https://github.com/openwrt/openwrt/blob/v21.02.0/toolchain/gcc/Config.version

I guess it must be 11.2.0 for these symbols to work?

**Comment by predators46** [comment]
for now use snapshoot.

> My build is based on v21.02.0 and in this version GCC default version is 8.4.0:
> 
> https://github.com/openwrt/openwrt/blob/v21.02.0/toolchain/gcc/Config.version
> 
> I guess it must be 11.2.0 for these symbols to work?

if alpine can possibly openwrt can too. the same as using java in openwrt

**Comment by kskog** [comment]
Will this be merged soon and part of a 22.03-rc?

**Comment by predators46** [comment]
> Will this be merged soon and part of a 22.03-rc?

not sure if this will be merged in my opinion. now the master branch has updated the gcc 12 version. why don't you manage the patch yourself

**Comment by kskog** [comment]
> > Will this be merged soon and part of a 22.03-rc?
> 
> not sure if this will be merged in my opinion. now the master branch has updated the gcc 12 version. why don't you manage the patch yourself

Sure, we can do that.

**Comment by neheb** [comment]
@Ansuel tl;dr: this should be merged.

Basically my prior commit disabling this was mistaken. I thought --disable-libstdcxx-dual-abi would force the usage of the C++11 ABI for std::string. But it actually disables the C++11 ABI and enables the old C++98 ABI.

Unfortunately, this blows up libstdc++. I had LLVM's libc++ in the packages repo but abandoned it as it was still quite big.

**Comment by Ansuel** [comment]
@hauke oh ok so size increase and sumo problem were unrelated right?

**Comment by neheb** [comment]
I have no idea what that sumo problem was. Bad toolchain I think. I don't get it anymore.

**Comment by Ansuel** [comment]
Thanks, merged in master with 3c06a344e9c7c03c49c9153342e68a5390651323

**Comment by PRIMETSS** [comment]
> Would be great if we could get this into the next release. This issue blocks .NET 6 development on OpenWrt.

and dotnet 7 and .dotnet 8

[https://github.com/openwrt/openwrt/issues/9497#issuecomment-1500784472](https://github.com/openwrt/openwrt/issues/9497#issuecomment-1500784472)

**Comment by thangdo1998** [comment]
i just build dotnet project and get errors
--
root@OpenWrt:~/source/MyOpenWrt/MyOpenWrt# ~/net7/dotnet publish -c Release -o ../publish
MSBuild version 17.7.0-preview-23281-05+310891fbe for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/root/net7/sdk/7.0.400-preview.23302.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/source/MyOpenWrt/MyOpenWrt/MyOpenWrt.csproj]
  MyOpenWrt -> /root/source/MyOpenWrt/MyOpenWrt/bin/Release/net7.0/linux-musl-x64/MyOpenWrt.dll
  /usr/bin/ld: cannot find -ldl: No such file or directory
  /usr/bin/ld: cannot find -lrt: No such file or directory
collect2 : error : ld returned 1 exit status [/root/source/MyOpenWrt/MyOpenWrt/MyOpenWrt.csproj]
/root/net7/sdk/7.0.400-preview.23302.1/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(346,5): error MSB3073: The command ""gcc" "obj/Release/net7.0/linux-musl-x64/native/MyOpenWrt.o" -o "bin/Release/net7.0/linux-musl-x64/native/MyOpenWrt" /root/.nuget/packages/runtime.linux-musl-x64.microsoft.dotnet.ilcompiler/7.0.5/sdk/libbootstrapper.a /root/.nuget/packages/runtime.linux-musl-x64.microsoft.dotnet.ilcompiler/7.0.5/sdk/libRuntime.WorkstationGC.a /root/.nuget/packages/runtime.linux-musl-x64.microsoft.dotnet.ilcompiler/7.0.5/framework/libSystem.Native.a /root/.nuget/packages/runtime.linux-musl-x64.microsoft.dotnet.ilcompiler/7.0.5/framework/libSystem.Globalization.Native.a /root/.nuget/packages/runtime.linux-musl-x64.microsoft.dotnet.ilcompiler/7.0.5/framework/libSystem.IO.Compression.Native.a /root/.nuget/packages/runtime.linux-musl-x64.microsoft.dotnet.ilcompiler/7.0.5/framework/libSystem.Net.Security.Native.a /root/.nuget/packages/runtime.linux-musl-x64.microsoft.dotnet.ilcompiler/7.0.5/framework/libSystem.Security.Cryptography.Native.OpenSsl.a -Wl,--strip-debug -Wl,-rpath,'$ORIGIN' -Wl,--build-id=sha1 -Wl,--as-needed -pthread -lstdc++ -ldl -lm -lz -lrt -pie -Wl,-z,relro -Wl,-z,now -Wl,--discard-all -Wl,--gc-sections" exited with code 1. [/root/source/MyOpenWrt/MyOpenWrt/MyOpenWrt.csproj]
root@OpenWrt:~/source/MyOpenWrt/MyOpenWrt#

**Comment by PRIMETSS** [comment]
@thangdo1998 Need more info and difficult to read. Seems like your dotnet install might be bad. Did you install all the dependencies. Here is good article to follow for getting it running (runtime & SDK) on OpenWRT.
[https://davidjmclaughlin.com/projects/how-to/2020/03/15/running-.net-core-on-openwrt-and-raspberry-pi-4.html](https://davidjmclaughlin.com/projects/how-to/2020/03/15/running-.net-core-on-openwrt-and-raspberry-pi-4.html)

**Pull request closed without merging**
