### PR TITLE
Add mt7615 80211 driver support to dts for R3P

### PR DESCRIPTION
**Pull request by lolyinseo**
Little fix for support 80211 MT7615 driver for Xiaomi R3P

### CODE REVIEW

**Comment by chunkeey** [comment]
The PR has formal issues as it has no Signed-off-by, commit subject and commit message need some touches as well, please check [Submitting patches](https://openwrt.org/submitting-patches) for details.

**Comment by ynezz** [comment]
@lolyinseo Ping

**Comment by 981213** [comment]
Superseded by #2293

**Comment by Neustradamus** [comment]
Original merged commit is:
- https://github.com/openwrt/openwrt/commit/d0090339117031d1994d139240bb30cb39b73060

Updated by merged commit:
- https://github.com/openwrt/openwrt/commit/d7c082ba4f7de97b3708d1f4a064954ffc774778

Linked to:
- https://github.com/openwrt/openwrt/pull/1823
- https://github.com/openwrt/openwrt/pull/2006
- https://github.com/openwrt/openwrt/pull/2293

**Pull request closed without merging**
