### PR TITLE
sunxi: Globally support for SY8106A voltage regulator

### PR DESCRIPTION
**Pull request by diizzyy**
Globally add support for Silergy SY8106A voltage regulator
which is needed for cpufreq support on boards such as
Orange Pi PC and Orange Pi PC 2 instead of just adding it for
Cortex A7 subtarget.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@hauke

**Comment by hauke** [comment]
I activated it for the cortexa7 subtarget, I think this regulator is only used on these boards. You could at least remove it from the cortexa7 subtarget.
I think there are more boards which could use it, but it is not defined in more device  trees.

**Comment by hauke** [comment]
yes please remove it from subtarget

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master

**Pull request closed without merging**
