### PR TITLE
kernel: armsr: Renesas: RZ: serial Ethernet ttySC0

### PR DESCRIPTION
**Pull request by JohnXVincent**
The issue related to the changes https://github.com/openwrt/openwrt/issues/15284

Serial driver and etherent enable for Renesas RZ platform

inittab fix for ttySC0

### CODE REVIEW

**Comment by JohnXVincent** [comment]
Hi @mcbridematt I've tested the changes on RZ/G2L platform and added this pull request.
This is related to the changes you have referred in the issue https://github.com/openwrt/openwrt/issues/15284
Please use this for reference or merge this whichever is convenient .  Thanks.

**Comment by hauke** [comment]
Please fix the order of the kernel configuration options using `make kernel_oldconfig CONFIG_TARGET=subtarget`

**Comment by mcbridematt** [comment]
@JohnXVincent FYI, the serial options have been added for 6.6 under https://github.com/openwrt/openwrt/commit/683355d0a6d51cbeda258492bc16a9c6413b387e
We should just need the inittab change to make it work fully
I will submit a pull to change armsr to 6.6 soon.

On the armsr target, we try and keep the kernel built-ins to those necessary to boot the system from a storage device (PCIe, USB, SD/MMC etc.), this helps keep the kernel binary small, and allows those using OpenWrt for specific devices to disable drivers they don't need.

The network drivers are defined in `target/linux/armsr/modules.mk` like https://github.com/openwrt/openwrt/blob/0d74b2a1e5f35d534fb5433ffcd85aa6b967cd47/target/linux/armsr/modules.mk#L254-L268
Can you create a kmod for your network driver instead?

Some of the options like phylib, phylink and ptp are already modules, as you can see from the other drivers in the file.

**Comment by JohnXVincent** [comment]
Hi @mcbridematt 
>I will submit a pull to change armsr to 6.6 soon.
Thanks.
> Can you create a kmod for your network driver instead?
I'll update the kmod for our network. 

I see the image files to download for snapshots here https://downloads.openwrt.org/snapshots/targets/armsr/armv8/
but could not find the installation iso image?

Is there an installation iso image to download for armv8 hardware?

**Comment by mcbridematt** [comment]
> but could not find the installation iso image?

There isn't an iso installer for OpenWrt as the generated images (-generic-ext4-combined.img.gz) are intended to be written directly to the storage device. The same is true for x86.
If you need to install to a device that you aren't booting from (e.g eMMC), you can use dd or another tool to write a copy of the image to it.

**Comment by hauke** [comment]
Please rebase this PR. 
Better only add the changes to related to serial here and the Ethernet changes in #15539

**Pull request closed without merging**
