### PR TITLE
ramips: add support for D-Link DIR-878 R1

### PR DESCRIPTION
**Pull request by TiGRoNdev**
Signed-off-by: Igor Nazarov <tigron.dev@gmail.com>

### CODE REVIEW

**Comment by TiGRoNdev** [comment]
I've recently added PR with support for D-Link DIR-878 R1, all has compiled and works perfectly fine.
According to this thread https://forum.openwrt.org/t/add-support-for-dlink-dir-878-r1/118208/3
I've seen that guy didn't finished his work on it, and it was 2 months ago. But edits about this PR is about 1 min of coding, 5 min to compile and 5 min to make a PR.

Everything is going nice through Failsafe UI, according to this thread https://forum.openwrt.org/t/d-link-dir-882-r1-bootloader-fw-image-verification/74834

Compiled firmware works on D-Link DIR-878 R1 (Ru ver.) 
Thanks pyckle for his sign-dlink-ru script :D

**Comment by Borromini** [comment]
You can see GitHub ran your submission through a few formality checks and those failed. See here: https://openwrt.org/submitting-patches#submission_guidelines.

**Comment by TiGRoNdev** [comment]
@Borromini @mans0n I've updated PR, added sign-off, can I start GitHub checks on my own?

**Comment by TiGRoNdev** [comment]
I hope I've done all formalities for this commit :D

**Comment by TiGRoNdev** [comment]
@Borromini I've made a commit message based on formalities

**Review by mans0n — APPROVED** [review]

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in 42626aef676d2ca1ea1577b7a47ba8e4135f1a4c.

**Pull request closed without merging**
