### PR TITLE
ramips: add dwr-512 jboot firmware configuration

### PR DESCRIPTION
**Pull request by fid0did0**
The previous fw version require the replacement of the stock bootloader with u-boot.
This prevent an easy stock restore of the original fw.

Now a proper fw util has been developed to manage the stock bootloader (jboot).
Therefore make sense prepare an image for the stock bootloader.

The old fw configuration (u-boot) is anyway kept.

So at the end 3 image can be generated:

1) factory image with jboot bootloader
	openwrt-ramips-rt305x-dwr-512-b-jboot-squashfs-factory.bin
2) sysupgrade image with jboot bootloader
	openwrt-ramips-rt305x-dwr-512-b-jboot-squashfs-sysupgrade.bin
3) factory and sysupgrade image with u-boot bootloader
	openwrt-ramips-rt305x-dwr-512-b-uboot-squashfs-sysupgrade.bin

Signed-off-by: Giuseppe Lippolis <giu.lippolis@gmail.com>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://lede-project.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by mkresin** [comment]
Would it be acceptable for you to drop the u-boot support and convert the dwr-512-b support to jboot only?

I never was a big fan of the requirement of replacing the bootloader and rather suspect that it will be done - if at all - only by the minority of the users.

If it is fine for you, please add only the missing pieces for jboot. Please don't migrate the board to the generic board detection within the same commit. It is pretty hard to review if multiple, independent, changes are done within the same commit.

**Comment by fid0did0** [comment]
Hi @mkresin,

> I never was a big fan of the requirement of replacing the bootloader and rather suspect that it will be done - if at all - only by the minority of the users.

Agree, because now we can use the stock jboot bootloader I will declare deprecated the bootloader replacement.

In any case, considering that the old u-boot fw is not compatible with the new one due to a different mtd partition scheme, IMHO we might support for a while the old configuration.

Let me know, for me at the end is not a problem remove at all the u-boot fw configuration.

**Comment by mkresin** [comment]
> In any case, considering that the old u-boot fw is not compatible with the new one due to a different mtd partition scheme, IMHO we might support for a while the old configuration.

As long as we don't support the u-boot version with a release, I'm fine to drop it without considering any backwards compatibility.

**Comment by fid0did0** [comment]
Ok, I will drop it.

**Comment by fid0did0** [comment]
Updated and tested.

**Comment by mkresin** [comment]
Merged to my staging tree.

Something is wrong with your git client. You have a bogus signed-off-by and author. I fixed the line length within the commit message as well, to match our submitting patches guideline.

**Pull request closed without merging**
