### PR TITLE
kernel: add missing config symbol (fix 87359976)

### PR DESCRIPTION
**Pull request by hnyman**
Fix build breakage caused by commit 8735997686 by adding the missing kernel config symbol NET_DSA_TAG_RTL4_A

Commit 8735997686 added NET_DSA_TAG_RTL4_A without providing a default value. That broke my ipq806x/R7800 build, as the build stopped to wait for the missing config value.

Error message:
`  Tag driver for Realtek 4 byte protocol A tags (NET_DSA_TAG_RTL4_A) [N/m/y/?] (NEW) 
`
Build stops as as there is no default set for the NET_DSA_TAG_RTL4_A symbol in the kernel config.

Details:
```
scripts/kconfig/conf  --syncconfig Kconfig
net/sched/Kconfig:45: warning: menuconfig statement without prompt
.config:4210:warning: symbol value 'm' invalid for NF_NAT_REDIRECT
*
* Restart config...
*
*
* Distributed Switch Architecture
*
Distributed Switch Architecture (NET_DSA) [Y/n/m/?] y
  Tag driver for switches using custom 802.1Q VLAN headers (NET_DSA_TAG_8021Q) [N/m/y/?] n
  Tag driver for Broadcom switches using in-frame headers (NET_DSA_TAG_BRCM) [N/m/y/?] n
  Tag driver for Broadcom switches using prepended headers (NET_DSA_TAG_BRCM_PREPEND) [N/m/y/?] n
  Tag driver for Lantiq / Intel GSWIP switches (NET_DSA_TAG_GSWIP) [N/m/y/?] n
  Tag driver for Marvell switches using DSA headers (NET_DSA_TAG_DSA) [N/m/y/?] n
  Tag driver for Marvell switches using EtherType DSA headers (NET_DSA_TAG_EDSA) [N/m/y/?] n
  Tag driver for Mediatek switches (NET_DSA_TAG_MTK) [N/m/y/?] n
  Tag driver for Microchip 8795/9477/9893 families of switches (NET_DSA_TAG_KSZ) [N/m/y/?] n
  Tag driver for Realtek 4 byte protocol A tags (NET_DSA_TAG_RTL4_A) [N/m/y/?] (NEW) 
```

### CODE REVIEW

**Comment by hnyman** [comment]
ping @hauke @adschm

**Comment by adschm** [comment]
I wonder why I cannot reproduce that problem...?

**Comment by adschm** [comment]
Formal stuff:

Commit title:
More specific, e.g.
"kernel: add missing symbol NET_DSA_TAG_RTL4_A"

and then to the commit message:
`Fixes: 8735997686a3 ("kernel: backport RTL8366RB patches")`

**Comment by hnyman** [comment]
Fixed according to your instructions.

Note that specifying the missing symbol in the commit title has not been the usual style:
```
perus@ub2004:/Openwrt/r7800$ git log --oneline | grep missing.*symbol | head -n 15
5d8fded26a kernel: add missing config symbols
5c3e83fa88 kernel: fix missing TRANSPARENT_HUGEPAGE symbols
1bff9f5b78 kernel: add missing config symbol
646bfe0842 malta: add missing symbols for kernel 5.4
8383e63808 ath79/mikrotik: add missing kernel config symbol for 5.4
03fd38d612 kernel: add missing symbol to 5.4 config
0543eb1110 imx6: 5.4: add missing kernel perf monitor symbol
ddf1832207 linux: generic: 5.4: add missing config symbols
a2c0b02dfa generic: add missing symbol from 5.4 config
085b445b42 mpc85xx: add missing kernel symbols
53801ae1c7 kernel: generic: add missing config symbol to 4.19
683341d98f kernel: generic: add missing 4.19 config symbol
d00e66f26f kernel: generic: add missing 4.19 config symbol
9b8d0f14f3 kernel: generic: add missing DRM panel 4.19 config symbols
6ca9d37b53 kernel: generic: add missing 4.19 config symbol
```

**Comment by wulfy23** [comment]
confirmed Sun Aug 30 02:28:11 AEST 2020

**Comment by hauke** [comment]
Thank you for the pull request, it was applied to master.

**Pull request closed without merging**
