### PR TITLE
kernel: remove bridge offload hack

### LINKED ISSUE #11877: [mvebu] VLAN frames are not properly untagged
### Describe the bug

I've recently moved to master snapshot due to the WRT32X being removed from the 22.0.3.* builds.  As a result, I've run across a VLAN untagging issue.  My configuration is as below.  Note that this exact configuration functions properly under 22.0.2.2.

/etc/config/network
```
config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'

config device
        option name 'br-lan'
        option type 'bridge'
        list ports 'lan3'
        list ports 'lan4'

config interface 'lan'
        option proto 'static'
        option netmask '255.255.255.0'
        option delegate '0'
        option ipaddr '192.168.2.1'
        option device 'br-lan.4'

config device
        option name 'wan'
        option macaddr 'xx:xx:xx:xx:xx:xx'

config interface 'wan'
        option device 'wan'
        option proto 'static'
        option ipaddr 'x.x.x.x'
        option netmask '255.255.255.252'
        option gateway 'x.x.x.x'
        list dns '1.1.1.1'

config interface 'guest'
        option proto 'static'
        option ipaddr '192.168.3.254'
        option netmask '255.255.255.0'
        option type 'bridge'
        option device 'br-lan.3'
        option delegate '0'

config interface 'dmz'
        option proto 'static'
        option device 'lan1'
        option ipaddr '192.168.0.254'
        option netmask '255.255.255.0'

config bridge-vlan
        option device 'br-lan'
        option vlan '4'
        list ports 'lan4:u*'

config bridge-vlan
        option device 'br-lan'
        option vlan '3'
        list ports 'lan3:u*'
```

/etc/config/wireless
```
config wifi-device 'radio0'
        option type 'mac80211'
        option path 'soc/soc:pcie/pci0000:00/0000:00:01.0/0000:01:00.0'
        option band '5g'
        option htmode 'VHT80'
        option country 'US'
        option cell_density '0'
        option channel '36'

config wifi-iface 'default_radio0'
        option device 'radio0'
        option network 'lan'
        option mode 'ap'
        option ssid 'xxxxxxxx'
        option encryption 'psk2'
        option key 'xxxxxxxx'
        option skip_inactivity_poll '1'
        option disassoc_low_ack '0'
        option wpa_disable_eapol_key_retries '1'

config wifi-device 'radio1'
        option type 'mac80211'
        option path 'soc/soc:pcie/pci0000:00/0000:00:02.0/0000:02:00.0'
        option band '2g'
        option country 'US'
        option htmode 'HT40'
        option channel '11'
        option cell_density '0'

config wifi-iface 'default_radio1'
        option device 'radio1'
        option network 'lan'
        option mode 'ap'
        option ssid 'xxxxxxxx'
        option encryption 'psk2'
        option key 'xxxxxxxx'

config wifi-device 'radio2'
        option type 'mac80211'
        option path 'platform/soc/soc:internal-regs/f10d8000.sdhci/mmc_host/mmc0/mmc0:0001/mmc0:0001:1'
        option channel '34'
        option band '5g'
        option htmode 'VHT80'
        option disabled '1'

config wifi-iface 'default_radio2'
        option device 'radio2'
        option network 'lan'
        option mode 'ap'
        option ssid 'xxxxxxxx'
        option encryption 'none'

config wifi-iface 'wifinet3'
        option device 'radio1'
        option mode 'ap'
        option encryption 'psk2'
        option key 'xxxxxxxx'
        option network 'guest'
        option ssid 'xxxxxxxx'
```

Packets sent between wireless devices on VLAN 4 and wired devices on VLAN 4 are not untagged properly prior to leaving the router.  Wired to wired and anything originating from the router is untagged properly.  Interestingly, the first packet **IS** untagged properly, but the remaining packets are **NOT**.  I have not determined what resets this "initial packet working" state.

For instance, here is tcpdump running on a wired device (192.168.2.2) receiving pings from a wireless device (192.168.2.211).

```
13:34:58.132565 b8:27:eb:dc:ef:ea > 7a:50:df:d0:bc:cb, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 42690, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.2.211 > 192.168.2.2: ICMP echo request, id 31467, seq 1, length 64

13:34:58.132612 7a:50:df:d0:bc:cb > b8:27:eb:dc:ef:ea, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 24968, offset 0, flags [none], proto ICMP (1), length 84)
    192.168.2.2 > 192.168.2.211: ICMP echo reply, id 31467, seq 1, length 64

13:34:59.137439 b8:27:eb:dc:ef:ea > 7a:50:df:d0:bc:cb, ethertype 802.1Q (0x8100), length 102: vlan 4, p 0, ethertype IPv4 (0x0800), (tos 0x0, ttl 64, id 42772, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.2.211 > 192.168.2.2: ICMP echo request, id 31467, seq 2, length 64

13:35:00.146242 b8:27:eb:dc:ef:ea > 7a:50:df:d0:bc:cb, ethertype 802.1Q (0x8100), length 102: vlan 4, p 0, ethertype IPv4 (0x0800), (tos 0x0, ttl 64, id 42806, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.2.211 > 192.168.2.2: ICMP echo request, id 31467, seq 3, length 64
```
Here, the first packet is properly untagged and the wired device is able to reply.  All of the following packets are still tagged as VLAN 4 and the wired device ignores them.

### OpenWrt version

r21791-c03e458c86

### OpenWrt target/subtarget

mvebu/cortexa9

### Device

Linksys WRT32X

### Image kind

Official downloaded image

### Steps to reproduce

Configure as above and attempt to ping between wireless and wired devices.

### Actual behaviour

Packets from wireless devices are not untagged properly when sent to wired devices.

### Expected behaviour

Packets from all devices should be tagged/untagged as per the user's VLAN configuration.

### Additional info

This issue has been discussed by others [here](https://forum.openwrt.org/t/divested-wrt-no-nonsense-hardened-builds-for-linksys-wrt-series/80522/948).  Flow offloading has NOT been enabled.

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by champtar**
This patch initially introduced in 94b4da9b4aaded6ed8a5bd93bf38a7c92753fe68 breaks mvebu devices when using vlan filtering with kernel 5.15 or 6.1, it was working ok in 5.10.

With this patch, frame that should exit untagged from the switch exit tagged. Running 'tcpdump -Q out -evnnli eth1' (eth1 being the dsa interface)
- with the hack, frame is sent directly to the destination port 4 with VID 2, so the switch leave the tag as instructed: 11:22:33:44:55:66 > 77:88:99:aa:bb:cc, Marvell EDSA ethertype 0xdada (Unknown), rsvd 0 0, mode From CPU, target dev 0, port 4, tagged, VID 2, FPri 0, ethertype ARP (0x0806), length 50: Ethernet (len 6), IPv4 (len 4), Request who-has 5.6.7.8 tell 1.2.3.4, length 28

- without the hack, frame is sent to the switch that performs the forwarding decision and untagging:
11:22:33:44:55:66 > 77:88:99:aa:bb:cc, Marvell EDSA ethertype 0xdada (Unknown), rsvd 0 0, mode Forward, dev 1, port 0, tagged, VID 2, FPri 0, ethertype ARP (0x0806), length 50: Ethernet (len 6), IPv4 (len 4), Request who-has 5.6.7.8 tell 1.2.3.4, length 28

Removing this patch makes my Turris Omnia usable with vlan filtering, ie wifi device can talk to wired device again.
Using kernel 5.15 some broadcast/multicast traffic is still leaked (on a VLAN 2 access port I see tagged VLAN 3 frame), using kernel 6.1 fixes that.

Partially fix https://github.com/openwrt/openwrt/issues/11877

ping @nbd168 as you are the original author

### CODE REVIEW

**Review by BKPepe — APPROVED** [review]
Go for it!

**Comment by Ansuel** [comment]
We should really test perf regression by removing this. Also I wonder if the patch can be fixed or the feature can be made configurable

**Comment by BKPepe** [comment]
Let's get rid of it first.  If something like this is desired, it should be
implemented/reported to upstream developers such as Linux kernel to deal
with it.

Having patches downstream makes everything harder to troubleshoot, debug,
when it is working in vanilla kernel, but not in OpenWrt ones as they are
patches, which no one knows what they are doing and no one has time to look
into it.

- Very good example is referenced issue. It took the time, which could be
focused elsewhere and author of that patch is lets say very hard to reach
or he has other priorities to work with. My intention is not to blame him,
but the issue is here for very long time and partially because of that
mvebu target was broken and it was decided to not support it anymore in the
stable version.

Another thing is if you are going to look at Linux kernel mailing list,
devs were suprised how many patches are here... :/

Dne ne 11. 6. 2023 11:17 uživatel Christian Marangi <
***@***.***> napsal:

**Comment by Ansuel** [comment]
It's in hack as we know this won't ever accepted. But consider we still have some low spec target, the impact without this might be pretty big. (I expect regression in the order of 100mbps or more)

Main problem of dropping patches is that once dropped nobody will care to reintroduce them.

We know the cause, we know how to identify it. If we can actually check that removing this would cause big performance hit on low spec device, I would investigate how to fix it. At max we can totally make this configurable or even introduce a custom config to disable it for the single targets.

Again AFAIK many target without swconfig and these kind of offload hack would result in having pretty bad perf in the order of not even reaching 100mbps of traffic so we need to be carful on what we drop. And I'm not even talking about that low spec device (see ipq806x that migrating from swconfg to DSA lose at least 200mbps of handling traffic, can't immagine some mips or ath79 targets)

**Comment by BKPepe** [comment]
> It's in hack as we know this won't ever accepted.

Of course, the proper question is why it was accepted here in the first place, and hence it is already here. It is pointless to point finger who caused it...

> But consider we still have some low spec target, the impact without this might be pretty big. (I expect regression in the order of 100mbps or more)

Ehm... then why don't you introduce this hack patch only for targets, where do you need it? Right now, this patch si applied for all routers, and clearly, it is causing issues on mvebu target. Anyway, in any case, this hack patch should be removed to know the upstream behavior or check it vanilla kernel and if there it is working, then good. If not, then we need to check more patches, which we do have here and narrow it to the behavior which is wanted.

> Main problem of dropping patches is that once dropped nobody will care to reintroduce them.

Isn't this wanted behavior?; –) What would you like to do with hack patches which don't have any commit message and are causing more issues. Also, fewer patches, then better maintenance efforts and time.

>  If we can actually check that removing this would cause big performance hit on low spec device, I would investigate how to fix it.

Almost the same can ask you mvebu users. It was investigated by @champtar 3 months ago that untagging issue works, but it is removed only now. The entire issue is present for how long? 6 months. Someone can say that it is an incredible time to remove the downstream patch, when using the upstream kernel it works OOTB.

> Again AFAIK many target without swconfig and these kind of offload hack would result in having pretty bad perf in the order of not even reaching 100mbps of traffic so we need to be carful on what we drop. 

I'm thinking. Are these targets supported in the Linux kernel? 
- If not, they bad, though. It is what it is. 
- If yes, you can verify it there if it works, right?

**Comment by champtar** [comment]
Kernel 5.15 + vlan_filtering on + this hack is unusable, I'm happy to test any patch to fix this hack,
but I agree with @BKPepe that we can't keep piles of hack, this deprives us from upstream support.

Also this issue might be present with every switches using DSA + 'mode forward' (frame sent to the switch for forwarding / untaging) + vlan_filtering

Maybe this could be re-implemented leveraging flowtables, so lots of coner cases are handled, and it has a chance of being upstreamed ?

In any case it would be nice to fix mvebu for 23.05, and this is the best fix I have for now.

**Comment by LGA1150** [comment]
I also found a scheduling-while-atomic bug, and posted a fix to the [mailing list](https://patchwork.ozlabs.org/project/openwrt/patch/20230515102640.1321685-1-dqfext@gmail.com/), but nobody seemed to care.

**Comment by BKPepe** [comment]
Thats another reason. We do have hack patch, someone looked at it to
improve it and honestly, nobody took care to review it and merge it.

So really drop this once for all. :pray:

Dne po 12. 6. 2023 5:55 uživatel LGA1150 ***@***.***> napsal:

**Comment by diizzyy** [comment]
As much as performance is of importance I think regressions can be tolerable and I don't think anyone expect ARMv7 to break any speed records in 2023. OpenWrt still doesn't do O2 by default or enable NEON on most mvebu platforms so I think the performance argument can be more or less disregarded as we can pick up the regression else to some extent.

**Comment by neheb** [comment]
> I also found a scheduling-while-atomic bug, and posted a fix to the [mailing list](https://patchwork.ozlabs.org/project/openwrt/patch/20230515102640.1321685-1-dqfext@gmail.com/), but nobody seemed to care.

Sounds like this should be added to OpenWrt's pending.

**Comment by champtar** [comment]
I managed to build mvebu / turris with kernel 6.1, I confirm this patch is also problematic with 6.1, and good news 6.1 fixes the broadcast/multicast frames 'leak' I have with 5.15

**Comment by Ansuel** [comment]
> It's also in generic but any platform where this will actually matter peformance is very likely already considered legacy (and indirectly "slow") so I doubt users in general are going to notice any difference in performance in real life.

again we really need to have some stats for this... ipq806x notice a regression and lose 100mbps of traffic just removing the L2 scaling patch and people complained. And I expect for legacy device the perf to drop in the order of 40mbps of traffic handling max. I would love to apply the proposed patch and also work on making this configurable or guard everything behind a config but we really need some clear stats if it's really worth to keep it and fix or drop as suggested.

But in any case no hurry... We can delay 23.05 since we found this known issue and backport dropping a patch is nothing difficult to do. Maybe we can ask on the forum some help for testing some perf difference?

**Comment by champtar** [comment]
If anyone can reach @nbd168, it would be interesting to know how bridger fit in the whole picture (https://github.com/openwrt/openwrt/blob/main/package/network/services/bridger/Makefile), does it complement this hack ? is it the next version ?
Again happy to test any fix, I just want proper support for mvebu after having previous stable release broken for the default use case.

**Comment by rany2** [comment]
@champtar FYI I'm fairly certain after testing for 2 days that this fixed this issue I was experiencing on my mt7621 device: https://github.com/openwrt/openwrt/issues/9555. So this seems to break more than just your mvebu device, haven't had it happen since despite it being extremely common before.

**Comment by BKPepe** [comment]
How many issues do we need to remove this patch? :-) Of course, we do need more statistics as we had them when introducing this patch, which no one except the author reviewed and the 2nd version (the refactored one) is sitting on the shelf to have broader audience. I mean testers. Where are they now? Who tested this hack patch? The author? It was only him? 

More questions are popping out.

**Comment by ptpt52** [comment]
I would like to drop this hack, since upstream linux should never accept it.

**Comment by rany2** [comment]
@Ansuel Unfortunately I use OpenWRT as a dumb AP, so i cannot be of help

**Comment by nbd168** [comment]
ACK from me for removing the patch. People that need a faster bridge datapath can use bridger - it should provide similar performance without hardware acceleration.

**Comment by Ansuel** [comment]
@nbd168 this right? https://github.com/nbd168/bridger

**Comment by champtar** [comment]
> ACK from me for removing the patch. People that need a faster bridge datapath can use bridger - it should provide similar performance without hardware acceleration.

Thanks, updated the commit with your ACK and a reference to bridger

**Comment by champtar** [comment]
> @nbd168 this right? https://github.com/nbd168/bridger

Already packaged https://github.com/openwrt/openwrt/blob/main/package/network/services/bridger/Makefile

**Comment by glanham-jr** [comment]
> At max we can totally make this configurable or even introduce a custom config to disable it for the single targets.

At minimum I think this should be done with at least mvebu on the disabled target list. This way, I can comfortably upgrade to the latest version, even if there is a perf hit. It sounds like this sort of patch would benefit from an integration test given the unknowns, but honestly I'm not sure how easy or feasible that would be to do with mvebu on something like qemu let alone gathering the requirements of what needs tested.

I'd be happy to try some perf testing, but I'm amateur to network testing/programming (let alone kernel space), and would need some guidance on doing tests. I have a Linksys 3200ACM. I can use a backup router while testing.

**Comment by neheb** [comment]
The author acked removal. Nuke it.

**Comment by ynezz** [comment]
Thanks! Merged.

**Comment by ynezz** [comment]
@champtar feel free to create a backport to 23.05 as well, thanks

**Comment by larena1** [comment]
> @champtar FYI I'm fairly certain after testing for 2 days that this fixed this issue I was experiencing on my mt7621 device: #9555. So this seems to break more than just your mvebu device, haven't had it happen since despite it being extremely common before.
> 
> Edit: Should have noted I'm not using VLAN filtering or anything like that, but it is a DSA device if that matters.

Are you sure about that? I'm still seeing this issue on the Qualcomm AX platform with a snapshot from just a few days ago so I doubt it's really fixed. Maybe this is caused by another one of OpenWRT's hacks?

**Pull request closed without merging**
