### PR TITLE
tools: e2fsprogs: patch cleanup

### PR DESCRIPTION
**Pull request by robimarko**
After looking into what patches we carry for e2fsprogs I think its safe to drop the e4defrag and crond ones.

Considering that this patch to not build e4defrag was added 12 years ago
because:
Compilation fails on older systems due to missing syscalls

I think its safe to say that enough time is passed so that whatever those
older systems were are either updated or not used anymore so lets drop
the patch.

Currently, e2fsprogs is being patched to avoid detecting host crond, but
instead of doing that we can simply pass --with-crond-dir=no as an
argument and drop the patch.

### CODE REVIEW

**Comment by robimarko** [comment]
@mcprat

**Comment by zxlhhyccc** [comment]
@robimarko Are older versions of glibc supported?

**Comment by robimarko** [comment]
@zxlhhyccc glibc versions have nothing to do with these changes

**Comment by robimarko** [comment]
@zxlhhyccc That did not change, and its a completely different thing we are trying to sort.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
