### PR TITLE
kernel: bump 5.4 to 5.4.69

### PR DESCRIPTION
**Pull request by graysky2**
Seemingly unneeded based on new upstream code so manually deleted:
   `platform/820-usb-0007-usb-dwc3-gadget-increase-timeout-value-for-send-ep-c.patch`

Manually merged:
   `generic-hack/251-sound_kconfig.patch`

All other modifications made by `update_kernel.sh`

Build system: x86_64
Build-tested: ipq806x/R7800, ath79/generic, bcm27xx/bcm2711
Run-tested: ipq806x/R7800

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by graysky2** [comment]
@adschm - Corrected, thanks.

**Comment by zuzia-dev** [comment]
Build system: x86_64
Build-tested: lantiq/Easybox 904 xDSL
Run-tested:  lantiq/Easybox 904 xDSL

Everything works fine.

**Comment by adschm** [comment]
Thanks, merged.

**Comment by curtdept** [comment]
Build and run tested (x86/64) by: Curtis Deptuck <curtdept@me.com>

Wow big kernel patch set.

**Pull request closed without merging**
