### PR TITLE
Fix sysupgrade from vendor image on UniElec U7623

### PR DESCRIPTION
**Pull request by dwmw2**
Based on the work in #3230 for master, this is the minimal backport to make 19.07 work:

 • Add the required `console=` to the command line to fix serial input.
 • Add command line partitioning so that we don't depend on the MBR *(which sysupgrade doesn't update for us)* matching our partition layout.
 • Stop wasting so much space on the eMMC, so that we fix in the @36MiB limit for sysupgrade on the vendor image.

### CODE REVIEW

**Comment by dwmw2** [comment]
@kristrev

**Comment by adrianschmutzler** [comment]
Please wait until this is merged for master, and then backport with "git cherry-pick -x" so the commit id from master is annotated.

**Comment by dwmw2** [comment]
> Please wait until this is merged for master, and then backport with "git cherry-pick -x" so the commit id from master is annotated.

I have added the commit IDs from what I expect to be the final version of #3230. I shall continue to do the waiting part...

**Comment by adrianschmutzler** [comment]
> > Please wait until this is merged for master, and then backport with "git cherry-pick -x" so the commit id from master is annotated.
> 
> I have added the commit IDs from what I expect to be the final version of #3230. I shall continue to do the waiting part...

They will of course change with every rebase :-)

**Comment by dwmw2** [comment]
Commit IDs updated to match what's now in master.

**Comment by 981213** [comment]
Merged. Thanks!

**Pull request closed without merging**
