### PR TITLE
ramips: fix MT7621 dtsi

### PR DESCRIPTION
**Pull request by dengqf6**
Fix SysTick reg
Add uartlite2 and uartlite3 nodes

### CODE REVIEW

**Comment by 981213** [comment]
One suggestion here :)
uartlite means there is only tx/rx. However uart2/uart3 have the full uart pins so they should be named uart not uartlite.

**Comment by dengqf6** [comment]
@981213 Well the [MT7621 programming guide](http://ftp.mqmaker.com/WiTi/Docs/Software/MT7621_ProgrammingGuide_Preliminary_Platform.pdf) does call them "UARTLITE"
I'll correct it later

**Comment by 981213** [comment]
Sorry my suggestion is wrong. A full uart has 8 pins.

**Comment by dengqf6** [comment]
Uhhhh. Here we go again

**Comment by mkresin** [comment]
merged, thanks!

**Pull request closed without merging**
