### PR TITLE
kernel: move CONFIG_PAGE_POOL to generic

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Cleanup symbols by running make kernel_oldconfig.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision - I added this to the kernel bump [f50a66c](https://github.com/openwrt/openwrt/commit/f50a66c25032f831d249f29fb492d1abb8d10b76)
> 
> At the time, only mpc85xx/p2020 failed. Are you thinking there are more subtargets that also need a refresh?

Removing `# CONFIG_FSL_DPAA2_SWITCH is not set` does not work for me on p101. I know the kernel config scripts tries to remove it, however, locally I get errors when doing that.

As you can see I added `# CONFIG_PPC_QUEUED_SPINLOCKS is not set` to p202 to the config. After adding this, all subtargets build fine.

> I added this to the kernel bump [f50a66c](https://github.com/openwrt/openwrt/commit/f50a66c25032f831d249f29fb492d1abb8d10b76)

Can I leave this PR open?

**Comment by Ansuel** [comment]
(@PolynomialDivision testing a new feature of github to rebase branch on top of master)

**Comment by robimarko** [comment]
@hauke Has PR for the `CONFIG_PPC_QUEUED_SPINLOCKS` already, that should be merged first.

https://github.com/openwrt/openwrt/pull/12047

**Comment by graysky2** [comment]
@PolynomialDivision - I will revert my commit in https://github.com/openwrt/openwrt/pull/12071 since you have this here.

**Comment by hauke** [comment]
`# CONFIG_FSL_DPAA2_SWITCH is not set` should be moved to the generic kernel configuration and removed from all target configurations.

**Comment by hauke** [comment]
I think we should also move `# CONFIG_PAGE_POOL is not set` to the generic kernel configuration and remove it from all targets which also deactivate it. `KERNEL_PAGE_POOL` is also set in `config/Config-kernel.in` and activated by default by mt76 wifi driver, see d02d4556789f5.

**Pull request merged**
