### PR TITLE
kernel: bump 6.6 to 6.6.51

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.51

Removed upstreamed:
	generic/backport-6.6/200-regmap-maple-work-around-false-positive-warning.patch
	generic/backport-6.6/822-v6.11-0012-nvmem-Fix-return-type-of-devm_nvmem_device_get-in-ke.patch
	bcm27xx/patches-6.6/950-1018-drivers-mmc-apply-SD-quirks-earlier-during-probe.patch

Manually rebased:
	bcm27xx/patches-6.6/950-0993-drivers-mmc-cqhci-clear-CQHCI_CTL-if-halt-fails.patch
        ramips/patches-6.6/311-MIPS-use-set_mode-to-enable-disable-the-cevt-r4k-irq.patch[4]
All other patches automatically rebased.

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.6.51&id=e42ea96d6d36a16526cb82b8aa2e5422814c3250
2. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.6.51&id=3d1baf322a3a69b38b6b2d511cfe0d611d1b5462
3. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.6.51&id=115a755bb38db5a1175be44e6a9a93a0a8233885
4. Adapted the changes from Hauke Mehrtens' modification in PR#16366 to 5.15.167

Build system: x86/64
Build-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3
Run-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3

### CODE REVIEW

**Comment by zxlhhyccc** [comment]
@graysky2
````
make[2]: Leaving directory '/__w/openwrt/openwrt/openwrt/scripts/config'
 make[1] target/compile
 make[2] -C target/linux compile
    ERROR: target/linux failed to build.
make -r target/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/__w/openwrt/openwrt/openwrt/include/toplevel.mk:248: target/compile] Error 1
====== Make errors from logs/target/linux/compile.txt ======
  HDRINST usr/include/asm/unistd_n32.h
  HDRINST usr/include/asm/ipcbuf.h
  HDRINST usr/include/asm/kvm_para.h
  INSTALL /__w/openwrt/openwrt/openwrt/build_dir/target-mipsel-openwrt-linux-musl_musl/linux-ramips_mt7620/linux-6.6.51/user_headers/include
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-mipsel-openwrt-linux-musl_musl/linux-ramips_mt7620/linux-6.6.51'
arch/mips/kernel/cevt-r4k.c: In function 'r4k_clockevent_init':
arch/mips/kernel/cevt-r4k.c:325:22: error: unused variable 'irq' [-Werror=unused-variable]
  325 |         unsigned int irq, min_delta;
      |                      ^~~
cc1: all warnings being treated as errors
make[8]: *** [scripts/Makefile.build:243: arch/mips/kernel/cevt-r4k.o] Error 1
make[8]: *** Waiting for unfinished jobs....
make[7]: *** [scripts/Makefile.build:480: arch/mips/kernel] Error 2
make[7]: *** Waiting for unfinished jobs....
make[6]: *** [scripts/Makefile.build:480: arch/mips] Error 2
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [/__w/openwrt/openwrt/openwrt/build_dir/target-mipsel-openwrt-linux-musl_musl/linux-ramips_mt7620/linux-6.6.51/Makefile:[19](https://github.com/openwrt/openwrt/actions/runs/10830180839/job/30049484090?pr=16370#step:31:20)21: .] Error 2
make[4]: *** [Makefile:234: __sub-make] Error 2
make[3]: *** [Makefile:23: /__w/openwrt/openwrt/openwrt/build_dir/target-mipsel-openwrt-linux-musl_musl/linux-ramips_mt76[20](https://github.com/openwrt/openwrt/actions/runs/10830180839/job/30049484090?pr=16370#step:31:21)/linux-6.6.51/.modules] Error 2
make[2]: *** [Makefile:11: compile] Error 2
`````

**Comment by graysky2** [comment]
@zxlhhyccc - are you suggesting that commit needs a revert?

**Comment by zxlhhyccc** [comment]
@graysky2 Yes.

**Comment by DragonBluep** [comment]
> @zxlhhyccc - are you suggesting that commit needs a revert?

Please fix ramips 311 patch instead.
```
--- a/arch/mips/kernel/cevt-r4k.c
+++ b/arch/mips/kernel/cevt-r4k.c
@@ -318,11 +318,12 @@ core_initcall(r4k_register_cpufreq_notifier);
 int r4k_clockevent_init(void)
 {
 #ifndef CONFIG_CEVT_SYSTICK_QUIRK
+	unsigned int irq;
 	unsigned long flags = IRQF_PERCPU | IRQF_TIMER | IRQF_SHARED;
 #endif
 	unsigned int cpu = smp_processor_id();
 	struct clock_event_device *cd;
-	unsigned int irq, min_delta;
+	unsigned int min_delta;
 
 	if (!cpu_has_counter || !mips_hpt_frequency)
 		return -ENXIO;

```

**Comment by zxlhhyccc** [comment]
@graysky2   I think @DragonBluep the patch is correct, please base the 311 patch manually. deleting new added 900 Patches

**Comment by hauke** [comment]
> > @zxlhhyccc - are you suggesting that commit needs a revert?
> 
> Please fix ramips 311 patch instead.
> 
> ```
> --- a/arch/mips/kernel/cevt-r4k.c
> +++ b/arch/mips/kernel/cevt-r4k.c
> @@ -318,11 +318,12 @@ core_initcall(r4k_register_cpufreq_notifier);
>  int r4k_clockevent_init(void)
>  {
>  #ifndef CONFIG_CEVT_SYSTICK_QUIRK
> +	unsigned int irq;
>  	unsigned long flags = IRQF_PERCPU | IRQF_TIMER | IRQF_SHARED;
>  #endif
>  	unsigned int cpu = smp_processor_id();
>  	struct clock_event_device *cd;
> -	unsigned int irq, min_delta;
> +	unsigned int min_delta;
>  
>  	if (!cpu_has_counter || !mips_hpt_frequency)
>  		return -ENXIO;
> ```

This will introduce a problem. The functions `mips_state_oneshot()` and `mips_state_shutdown()` and  are using the irq.

**Comment by hauke** [comment]
I added a fix for the ramips problem to #16366.

**Comment by graysky2** [comment]
> I added a fix for the ramips problem to https://github.com/openwrt/openwrt/pull/16366.

Nice, I used that here.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
