### PR TITLE
netsupport.mk: add MultiPath TCP modules

### PR DESCRIPTION
**Pull request by sKyissKy**
Signed-off-by: sKyissKy <szhynet@gmail.com>

netsupport.mk: add MultiPath TCP modules

### CODE REVIEW

**Comment by john-tho** [comment]
Because the MPTCP (core) config options do not build modules, and we still want the ability to enable or disable them, it might be better to set them via config/Config-kernel.in, rather than using empty packages. You could have Config-kernel.in options for CONFIG_MPTCP, CONFIG_MPTCP_IPV6, and the KernelPackage for mptcp_diag.ko
This commit should give you an idea of linking a Config-kernel.in setting and a KernelPackage https://github.com/openwrt/openwrt/commit/45d541bb409355f090b971d96ebebd8610ef84a7

**Comment by hauke** [comment]
Please do not close your existing pull requests and open new ones. Please force push into your existing pull request. 
There are already these old ones: #11064, #11071, #11131

**Comment by hauke** [comment]
I agree with @john-tho, please use config/Config-kernel.in and do not abuse a kernel package to change a compiled in option. 

No need to make this depend on kernel 5.6 and later, OpenWrt master only supports kernel 5.10 and 5.15. 

Maybe you can integrate the net/mptcp/mptcp_diag.ko file into the existing kmod-inet-diag package.

**Comment by BKPepe** [comment]
Test Formalities check is failing for you.

This means:
 - We require to have real name in the ``Signed-off-by``
 - You should add commit description, which would explain why are you doing these changes and why they are necessary
 
 All these details can be found at this page https://openwrt.org/submitting-patches , where you can see all the details and steps, which will help you to fix the failing check from the CI.

**Pull request closed without merging**
