### PR TITLE
ath79: fix qca956x SoC boot

### PR DESCRIPTION
**Pull request by lucize**
based on old ar71xx irq.c driver

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by lucize** [comment]
maybe there is a better approach, but without it, the board will hang with

```
[    0.000000] Linux version 4.14.44 (build@droid) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r7054-64b53247c4)) #0 Fri Jun 1 19:01:03 2018
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019750 (MIPS 74Kc)
[    0.000000] MIPS: machine is Ubiquiti Uifi AC Lite
[    0.000000] SoC: Qualcomm Atheros QCA956X ver 1 rev 0
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 08000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] random: get_random_bytes called from 0x8048873c with crng_init=0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32512
[    0.000000] Kernel command line: console=ttyS0,115200n8 rootfstype=squashfs,jffs2
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 117164K/131072K available (3615K kernel code, 148K rwdata, 484K rodata, 7840K init, 207K bss, 13908K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] CPU clock: 775.000 MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 4932285024 ns
[    0.000007] sched_clock: 32 bits at 387MHz, resolution 2ns, wraps every 5541893118ns
```

**Comment by juppin** [comment]
Your added peace of code is already added with [this](https://github.com/openwrt/openwrt/blob/master/target/linux/ath79/patches-4.14/0017-MIPS-ath79-add-support-for-qca956x-soc.patch ) patch...

If you look at [line 286](https://github.com/openwrt/openwrt/blob/master/target/linux/ath79/patches-4.14/0017-MIPS-ath79-add-support-for-qca956x-soc.patch#L286), i think there is something wrong in the patch...
The address operator "&" is definetely wrong here... But there could be another mistake and i don´t have the time to take a look on the complete code...
@lucize Could you test this please?

**Comment by robimarko** [comment]
I also think that irq is not called at all.
Since when he added the reset code to the clocks it boots.

But it should be called as the code is identical to ar71xx and clearly, soc_is_qca956x function detects the SoC as clocks are initialized.
The same function should also call qca956x_irq_init

There has gotta be some weird bug when this was patched in

**Comment by lucize** [comment]
@juppin yes, I know, but as @robimarko stated, later is deleted. I wanted to raise this problem, why add some stuff and remove them later, maybe a complete patch rework would be cleaner

**Comment by robimarko** [comment]
Patch cleanup is needed since a lot of what is patched is later dropped.
This is most likely since old ar71xx patches were just reused

**Comment by blogic** [comment]
patch is correct, thanks ! and yes the patches need to be refactored before i send them upstream. I have already started doing so in a local tree that i have here.

**Pull request closed without merging**
