### PR TITLE
ramips: ethernet: ralink: add led_source dts-binding

### PR DESCRIPTION
**Pull request by therealsummoner**
this adds the new dts-binding "mediatek,led_source"
currently for MT7628AN and MT7688 built-in switches,
which is documented as a 3-bit field configuring the
switch LEDs for various control schemes from 0 to 3.

Normally this is not needed, but e.g. for Asus RT-AC1200-V2
it is a must to set it to the anyway undocumented value
of 4, to have the switch LEDs react correctly on link/act
events. This is an MT7628DAN device, but I doubt this is
a speciality of this particular SoC.

Also added the RT305X_ESW_LED_OFF value to LED states.
Did also rename the register RT5350_EWS_REG_LED_POLARITY
to RT5350_EWS_REG_LED_CONTROL, which is the correct name.
Also making use of defines for some hardcoded values.

Signed-off-by: Tamas Balogh <tamasbalogh@hotmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Does the switch support gpio?

I ask since this is a more upstream friendly way of implementing LED control for switches.

**Comment by neheb** [comment]
Specifically, I'm asking if the switch supports something like this: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=429a0edeefd88cbfca5c417dfb8561047bb50769

**Comment by therealsummoner** [comment]
The switch supports gpio, but the LEDs are not functioning correctly via the switch trigger, i.e. they reflect link, but no activity at all.

> Specifically, I'm asking if the switch supports something like this: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=429a0edeefd88cbfca5c417dfb8561047bb50769
> 
> ping @LGA1150

I'll look, thanx for the suggestion.

**Comment by mans0n** [comment]
> I'm working on the RT-AC1200-V2 and here when the switch LEDs are not included in the gpio state_default group, they will be controlled internally and constant crazy-fast blinking is on loose.

That's exactly what I experienced with mt7628! All the mt7628 devices I've met showed the same behavior. I've also tinkered with the LED control reg (a few years ago), but I could not solve the problem so I gave up. The LEDs were fine with the stock FW, or when the device was connected to other labtops, so I thought the culprit was my laptop, not the SoC.
I'll definitely test this if it really fixes the problem. :)

**Comment by therealsummoner** [comment]
Thing is, this could give others the possibility to drive them LEDs at least in a way. Driving them via GPIO swconfig is somehow malfunctioning (no tx/rx activity) and thus this remains the only way. My last info about DSA for MT7628 is that it is still WIP.

**Comment by therealsummoner** [comment]
@mans0n could you please pm me about the device on openwrt forum, username is 'tsb', thanx!

**Comment by AuthorReflex** [comment]
Tested on Asus RT-AC1200 with PR #5028

**Comment by therealsummoner** [comment]
This should be considered as another (undocumented) mode of the LED configuration. In the default mode, all the LEDs are constantly triggered by something e.g. some flow-control or such, thus they don't stop blinking.
Interestingly in this mode this is not happening anymore and the blink speed is indeed set to a ~2Hz interval, which seems to me anyway as a default interval, at least I have very similar behavior on other platforms, even with GPIO LEDs.

**Comment by mans0n** [comment]
I've been wondering, why this (significant) issue was not discovered and resolved till now?
I've checked the other mt7628 devices and it seems many devices are actually using software trigger, so those are not affected by this issue.
While I was seeking a reviewer for this PR, I finally found that someone already reported this issue a few years ago. #911
And I feel disabling EEE is a more proper solution to this problem. I've also tested the patch and it worked well, the LED now blinks with a real "normal speed" I expected.
The author chose to abandon the patch, so I picked it up myself and opened a new PR as #xxxx. I would be glad if you can test it on your devices and share your thoughts on it.

**Comment by therealsummoner** [comment]
At the level of LED-controlling, personally I'd stick to not alter any features and use the undocumented LED-control mode, but the main thing is to have a working solution, because as mentioned before, swconfig is not handling the GPIO LEDs correctly.

**Comment by therealsummoner** [comment]
accidental close

**Comment by therealsummoner** [comment]
Any chance to get it reviewed/merged? Its also tested already.
TiA

**Comment by w43322** [comment]
> Thing is, this could give others the possibility to drive them LEDs at least in a way. Driving them via GPIO swconfig is somehow malfunctioning (no tx/rx activity) and thus this remains the only way. My last info about DSA for MT7628 is that it is still WIP.

About that, I think it might be an expected behavior? Because currently I‘m using a router which is on a completely different platform (ipq40xx), which uses GPIO swconfig, and the LEDs also show no tx/rx activity…

**Comment by therealsummoner** [comment]
> > Thing is, this could give others the possibility to drive them LEDs at least in a way. Driving them via GPIO swconfig is somehow malfunctioning (no tx/rx activity) and thus this remains the only way. My last info about DSA for MT7628 is that it is still WIP.
> 
> About that, I think it might be an expected behavior? Because currently I‘m using a router which is on a completely different platform (ipq40xx), which uses GPIO swconfig, and the LEDs also show no tx/rx activity…

That's some interesting input. I don't know what is planned, but if swconfig stays for older HW to be supported, it certainly needs to be fixed.

**Comment by therealsummoner** [comment]
Would this be possible to get merged since tested was ok as well?
I'm not sure whether there is anything against it, or not; please let me know.

**Comment by mans0n** [comment]
I've got more and more inclined to SW trigger approach, as I feel this is a kind of hack, but the register is documented in the datasheet anyway, so adding a DT property for it won't be a big problem IMO.

**Comment by mans0n** [comment]
Thanks! Applied your patch in 65dc9e098025.

**Pull request closed without merging**
