### PR TITLE
lantiq/xrx200: move 8M flash devices to a small flash subtarget

### LINKED ISSUE #16761: lantiq/xrx200: main branch (prospective 24.xx) 8M flash devices not building sysupgrade images - image too large
### Describe the bug

As best I can tell, there are 6 xrx200 devices with 8MB flash:
- arcadyan_vgv7510kw22-brn  
- arcadyan_vgv7519-brn  
- lantiq_easy80920-nor  
- netgear_dm200  
- tplink_tdw8970  
- tplink_tdw8980  

Of these only the first 4 appear to have snapshot sysupgrade images at https://downloads.openwrt.org/snapshots/targets/lantiq/xrx200/ as of 0900 UTC on 23Oct2024.  Of these 4 only the Netgear DM200 seems likely to build a sysupgrade image and have some usable overlayfs space in a 24.xx context, given that the snapshot builds don't include LUCI; the Lantiq Easy80920-NOR might also build a sysupgrade image in a 24.xx context but seems unlikely to have usable overlayfs space.

At least the last 3 devices in the above list are still in use as ADSL or VDSL2 modems and I own both a DM200 and a TD-W8980 and would like to continue to be able to use them until such time as I can get a FTTP connection (some time away yet unfortunately).

### OpenWrt version

SNAPSHOT

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

lantiq/xrx200

### Device

arcadyan_vgv7510kw22-brn   arcadyan_vgv7519-brn   lantiq_easy80920-nor   netgear_dm200   tplink_tdw8970   tplink_tdw8980  

### Image kind

Official downloaded image

### Steps to reproduce

check for sysupgrade images for affected devices at https://downloads.openwrt.org/snapshots/targets/lantiq/

### Actual behaviour

sysupgrade images for affected devices not available or of size such that installation leaves device with little or no usable free overlayfs space

### Expected behaviour

sysupgrade images for affected devices available and of size such that when installed leaves device with sufficient free overlayfs space for basic configuration

### Additional info

I believe that sysupgrade images for these devices can still be built if migrated into a SMALL_FLASH variant of the xrx200 subtarget, as that is what I effectively do with custom builds to incorporate the alternative Lantiq xDSL firmware blobs required in my VDSL2 environment.  The SMALL_FLASH approach may not keep these devices buildable much beyond 24.xx though but the time bought would still be useful in my view.

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by aimacintyre**
Images for xrx200 8M flash are either not building due to image size (TD-W8970, TD-W8980) or building such that the available free space in the overlayfs is too little to be useful.

To keep images for these devices buildable, move them into a small flash variant of the xrx200 subtarget.  As these devices are NOR flash only, remove NAND and UBI references from the kernel config to gain some additional image size reduction.

The apparent 8M flash devices Arcadyan VGV7510KW22-brn, Arcadyan VGV7519-brn and Lantiq Easy80920-nor seem to exist in order to create special "factory" installation images for these devices (which actually have larger flash: 16MB for the Arcardyan devices; 64MB for the Lantiq device).  As a considerable amount of surgery would appear to be required to the uboot-lantiq package structure to separate the "factory" from the "sysupgrade" device recipes for these devices they remain in the xrx200 target - if factory images aren't now created, 23.05.x factory images should suffice for initial installation.

Tested on: Netgear DM200, TP-Link TD-W8980,
           AVM Fritz7490 (xrx200 subtarget: image build only)

Fixes: https://github.com/openwrt/openwrt/issues/16761
Signed-off-by: Andrew MacIntyre <andymac@pcug.org.au>

### CODE REVIEW

**Comment by aimacintyre** [comment]
If accepted, I would recommend that the PR be backported to the 24.10 branch which is showing the same issues for the same devices.  I'm aware that there is a policy of not back-porting new subtargets to release branches, but request consideration of an exception for this case as there has yet been no 24.10 release (as of creating this PR) and the new subtarget has only be created to make images buildable for existing supported devices (i.e. no new supported devices being added to 24.10 branch).

**Comment by vahithosan** [comment]
Hello.

```
https://janfla.slask.pl/2021/01/tp-link-td-w8970v1-16m-mod/
https://janfla.slask.pl/2022/01/openwrt-21-02-tp-link-td-w8970v1-16m-mod/
```

I replaced the 16M spi chip in my modem with the path at this address.

I also installed Openwrt version 21.02 from the same page.



When I compiled newest version openwrt for SPI chip 16M, I could not run it. 



Can you help me?

**Comment by aimacintyre** [comment]
> When I compiled newest version openwrt for SPI chip 16M, I could not run it.

I believe you need to take your query to the OpenWrt forums (I suggest the [Hardware Questions and Recommendations](https://forum.openwrt.org/c/hardware-questions-and-recommendations/13) category) - I can't see that it is relevant to this pull request.

**Comment by hauke** [comment]
I would prefer `xrx200_tiny` over `xrx200_legacy`. In the ath79 target we also name it tiny.

How big are thd new images and how big were the old images? I would lie to know how much smaller the new stuff it.

**Comment by aimacintyre** [comment]
I used the name `xrx200_legacy` because the Lantiq target already has an `xway_legacy` subtarget as a parallel to the `xway` subtarget with the same small flash support purpose.  I don't have a strong preference for the name though.

The DM200 sysupgrade image is the only one in the proposed small_flash list that currently builds in main or 24.10 due to not needing Wifi or USB support; the 24.10-rc2 DM200 sysupgrade image (which includes LUCI) is currently 6913kB, while the small_flash sysupgrade image (including LUCI) builds for me at 5889kB - a reduction of just over 1MB.

The TD-W8970 & TD-W8980 small_flash sysupgrade images (including LUCI) build for me at 6529kB with a recipe image size limit for both of 7680kB.  I calculate that these sysupgrade images would be around 7800kB without the small_flash setting if the size limit were not applied.

**Pull request merged**
