### PR TITLE
bmips: enable testing kernel version with 6.6 version

### PR DESCRIPTION
**Pull request by GoetzGoerisch**
* bmips: 6.6: copy patches, config from 6.1
* bmips: 6.6: refresh kernel patches
* bmips: add 6.6 kernel as testing

Signed-off-by: Goetz Goerisch <ggoerisch@gmail.com>

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
@Noltari I'm able to reproduce the failure locally, but I'm not able to fix it.
Feedback or guidance appreciated.

**Comment by Noltari** [comment]
> @Noltari I'm able to reproduce the failure locally, but I'm not able to fix it. Feedback or guidance appreciated.

@GoetzGoerisch I'm sorry, but I don't know which failure you're talking about...
If you could add more info about the failure maybe I can help you.

**Comment by Noltari** [comment]
Also, maybe we should wait until https://github.com/openwrt/openwrt/pull/15354 is merged.
That's one of the reasons I haven't started with v6.6 on bmips yet...

**Comment by GoetzGoerisch** [comment]
@Noltari 
I was seeing this also locally:
```
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-bmips_bcm6318/linux-6.6.33'
mips-openwrt-linux-musl-ld.bin: kernel/kexec_core.o: in function `__crash_kexec':
kernel/kexec_core.c:(.text.__crash_kexec+0xc0): undefined reference to `machine_crash_shutdown'
mips-openwrt-linux-musl-ld.bin: kernel/kexec_core.c:(.text.__crash_kexec+0xc8): undefined reference to `machine_kexec'
mips-openwrt-linux-musl-ld.bin: kernel/kexec_core.o: in function `kernel_kexec':
kernel/kexec_core.c:(.text.kernel_kexec+0xa4): undefined reference to `machine_shutdown'
mips-openwrt-linux-musl-ld.bin: kernel/kexec_core.c:(.text.kernel_kexec+0xb4): undefined reference to `machine_kexec'
```
But working with the kernel is new to me.
I see that now some patches need refresh and will wait for the mentioned PR to get committed upstream.

**Comment by kylehendrydev** [comment]
I think this patch fixes the build problem: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8cd2accb71f5eb8e92d775fc1978d3779875c2e5

The short term workaround is disable CONFIG_CRASH_DUMP

**Comment by Noltari** [comment]
> I think this patch fixes the build problem: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8cd2accb71f5eb8e92d775fc1978d3779875c2e5
> 
> The short term workaround is disable CONFIG_CRASH_DUMP

Thanks, but instead of disabling CONFIG_CRASH_DUMP we should backport it:
https://github.com/openwrt/openwrt/pull/15795

**Comment by GoetzGoerisch** [comment]
Thank you @Noltari!

**Pull request merged**
