### PR TITLE
kernel: bump 5.10 to 5.10.51

### PR DESCRIPTION
**Pull request by rsalvaterra**
Run-tested:
ath79/generic (TL-WDR3600)
mvebu/cortexa9 (Turris Omnia)
ramips/mt7621 (Redmi AC2100)

No deleted or manually refreshed patches.

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by usver1** [comment]
Can not compile Rockchip target (FriendlyARM NanoPi R4S 4GB LPDDR4) after this commit. Compilation with kernel 5.10.50 was OK.
`make[5]: Entering directory '/home/v/mr/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.10.51'
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
  CC      scripts/mod/devicetable-offsets.s
  DTC     arch/arm64/boot/dts/rockchip/rk3318-a95x-z2.dtb
  MKELF   scripts/mod/elfconfig.h
  DTC     arch/arm64/boot/dts/rockchip/rk3326-odroid-go2.dtb
  UPD     scripts/mod/devicetable-offsets.h
arch/arm64/boot/dts/rockchip/rk3328.dtsi:1006.24-1031.4: ERROR (duplicate_node_names): /usb@ff600000: Duplicate node name
ERROR: Input tree has errors, aborting (use -f to force output)
make[7]: *** [scripts/Makefile.lib:326: arch/arm64/boot/dts/rockchip/rk3318-a95x-z2.dtb] Error 2
make[7]: *** Waiting for unfinished jobs....
  HOSTCC  scripts/mod/modpost.o
  HOSTCC  scripts/mod/sumversion.o
make[6]: *** [scripts/Makefile.build:497: arch/arm64/boot/dts/rockchip] Error 2
make[5]: *** [Makefile:1358: dtbs] Error 2
make[5]: *** Waiting for unfinished jobs....
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/mod/modpost
  CC      kernel/bounds.s
  CALL    scripts/atomic/check-atomics.sh
  UPD     include/generated/timeconst.h
  UPD     include/generated/bounds.h
  CC      arch/arm64/kernel/asm-offsets.s
  UPD     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
make[5]: Leaving directory '/home/v/mr/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.10.51'
make[4]: *** [Makefile:24: /home/v/mr/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.10.51/.modules] Error 2
make[4]: Leaving directory '/home/v/mr/target/linux/rockchip'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/v/mr/target/linux'
time: target/linux/compile#2.02#0.36#1.89
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/v/mr'
make[1]: *** [target/Makefile:18: /home/v/mr/staging_dir/target-aarch64_generic_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/v/mr'
make: *** [/home/v/mr/include/toplevel.mk:230: world] Error 2
`

**Comment by rsalvaterra** [comment]
> Can not compile Rockchip target (FriendlyARM NanoPi R4S 4GB LPDDR4) after this commit. Compilation with kernel 5.10.50 was OK.

Thanks for the report, I see the issue, will fix.

**Comment by rsalvaterra** [comment]
@usver1, can you please confirm if [this patch](https://patchwork.ozlabs.org/project/openwrt/patch/20210720124043.52945-1-rsalvaterra@gmail.com/) works for you?

**Comment by usver1** [comment]
Unfortunately it does not. Though the error is different.
`Error: arch/arm64/boot/dts/rockchip/rk3328-nanopi-r2s.dts:403.1-13 Label or path usbdrd_dwc3 not found
FATAL ERROR: Syntax error parsing input tree
make[7]: *** [scripts/Makefile.lib:326: arch/arm64/boot/dts/rockchip/rk3328-nanopi-r2s.dtb] Error 1
make[7]: *** Waiting for unfinished jobs....
make[6]: *** [scripts/Makefile.build:497: arch/arm64/boot/dts/rockchip] Error 2
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [Makefile:1358: dtbs] Error 2
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/home/v/mr/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.10.51'
make[4]: *** [Makefile:24: /home/v/mr/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.10.51/.modules] Error 2
make[4]: Leaving directory '/home/v/mr/target/linux/rockchip'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/v/mr/target/linux'
time: target/linux/compile#20.78#63.91#78.30
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/v/mr'
make[1]: *** [target/Makefile:18: /home/v/mr/staging_dir/target-aarch64_generic_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/v/mr'
make: *** [/home/v/mr/include/toplevel.mk:230: world] Error 2
`

**Comment by rsalvaterra** [comment]
@usver1, try [this one](https://patchwork.ozlabs.org/project/openwrt/patch/20210720152450.493544-1-rsalvaterra@gmail.com/). It should be the proper fix.

**Comment by usver1** [comment]
It works. There are no errors anymore.
Thank You!

**Pull request closed without merging**
