### PR TITLE
toolchain: gcc: update to 12.3.0

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release notes:
https://gcc.gnu.org/gcc-12/changes.html

Refresh patches:
- 230-musl_libssp.patch
- 910-mbsd_multi.patch
- 920-specs_nonfatal_getenv.patch
- 970-macos_arm64-building-fix.patch

### CODE REVIEW

**Comment by Ansuel** [comment]
@PolynomialDivision any chance they fixed the elf bug or elf fixed the bug?

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision any chance they fixed the elf bug or elf fixed the bug?

You mean the path analysis bug? Looks like it:
https://github.com/gcc-mirror/gcc/commits/releases/gcc-12.3.0/gcc/tree-ssa-alias.cc

https://github.com/gcc-mirror/gcc/commit/ef6051b36241bf130bf76af0b775248635dc616e

**Comment by Ansuel** [comment]
@PolynomialDivision the one about elfutils failing to build with the realloc... we are currently disabling the warning waiting for a proper fix. If you notice that got fixed, please drop the workaround and include it in this pr

**Comment by PolynomialDivision** [comment]
@Ansuel Could you link me to more information, e.g. the error message? Or the setup to reproduce it?

**Comment by PolynomialDivision** [comment]
Runtested on TOTOLINK A7000R.

**Comment by Ansuel** [comment]
@PolynomialDivision can you by chance also update the gcc package?

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision can you by chance also update the gcc package?

You mean the toolchain package? Isn't that automatically bumped?

**Comment by hauke** [comment]
This package needs an update too: https://github.com/openwrt/packages/tree/master/devel/gcc

**Comment by Ansuel** [comment]
Yep was referring to the feeds package

**Pull request merged**
