### PR TITLE
libressl: fix ARM host build

### PR DESCRIPTION
**Pull request by mcprat**
result of conversation from:

#10299 
https://github.com/openwrt/packages/pull/18981

### CODE REVIEW

**Comment by dhewg** [comment]
Dunno about the pic one, but the asm patch looks good to me.

I guess the real issue is that a 64bit kernel/32bit userland gets detected as 64bit by the libressl build system, which then erroneously builds 64bit code? See also a395563f68fde6f52dbf10913f59f13b8c804cd5, which is about x32, and you have a 64bit arm64 host with an arm32 userland. Maybe mention that in the commit message.

**Review by neheb — APPROVED** [review]

**Comment by mpratt14** [comment]
I could try swapping to the 32-bit kernel, but I don't think its responsible for the behavior I see

I test on a branch that has many other commits that I'm working on, one of them introduces a way to manually handle a weird system identity like mine. LibreSSL uses `GNU_HOST_NAME` with the default configure recipe

https://github.com/openwrt/openwrt/pull/9975/commits/918b079db74f0caa16dc09ab0f8596c192b3fd02

**Comment by mpratt14** [comment]
> Dunno about the pic one

that configure option seems to just add the PIC flags so they appear twice, but there might be more, so better to have extra copys of the same flags than a small possibility that something is missing

**Comment by mpratt14** [comment]
cleaned up commit messages

**Comment by dhewg** [comment]
> > Dunno about the pic one
> 
> that configure option seems to just add the PIC flags so they appear twice, but there might be more, so better to have extra copys of the same flags than a small possibility that something is missing

Yeah, but there's more than one pic flag through: -fpic, -fPIC, -DPIC, and depending on the arch only one combination might be correct.
It might be better to avoid adding that switch and rely on OpenWrt's flags if that works, because that change might break another arch if LibreSSL chooses different flags?

**Comment by mpratt14** [comment]
openwrt requires GCC and has only one version of those flags for `HOST_FPIC`

I'm not sure what scenario the GNU autotools would decide on the lowercase version...

**Comment by dhewg** [comment]
No idea either, just saying: why fix something that isn't broken?

**Comment by mpratt14** [comment]
I'm in the middle of a build test build right now (some random package) and I see lines that have both the uppercase and lowercase. does GCC take the uppercase or the right-most version of the flag?

`
mips-openwrt-linux-musl-gcc  -I. -Iinclude -fPIC -pthread -mabi=32 -Wa,--noexecstack -Wall -O3 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -fmacro-prefix-map=/media/SDStorage/builds/github-openwrt/openwrt/build_dir/target-mips_24kc_musl/openssl-1.1.1p=openssl-1.1.1p -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -ffunction-sections -fdata-sections -znow -zrelro -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DOPENSSLDIR="\"/etc/ssl\"" -DENGINESDIR="\"/usr/lib/engines-1.1\"" -DNDEBUG -DOPENSSL_PREFER_CHACHA_OVER_GCM -DOPENSSL_SMALL_FOOTPRINT -I/media/SDStorage/builds/github-openwrt/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.3.0_musl/usr/include -I/media/SDStorage/builds/github-openwrt/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.3.0_musl/include/fortify -I/media/SDStorage/builds/github-openwrt/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.3.0_musl/include -MMD -MF crypto/err/err_prn.d.tmp -MT crypto/err/err_prn.o -c -o crypto/err/err_prn.o crypto/err/err_prn.c
`

**Comment by mpratt14** [comment]
the more important question, which to trust more, CFLAGS or the --with-pic configure option, or is it the same...

**Comment by mpratt14** [comment]
I suppose looking into the checks performed by autotools would answer the questions. In my opinion, any issue regarding the addition of this configure option would instead suggest something is wrong with GNU autotools, not the actual option.

```
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
```

as for why to fix something that's not broken, sometimes redundancy is a good safety net, but in this case I thought it does more than just add the PIC flag, and I'm still not 100% sure that's all there is to the option (at least it seems there are some checks before the flag is added, other than the checks that verify the flag works)

**Comment by hauke** [comment]
For me a build on an aarch64 ubuntu system (Oracle cloud) works without problems. It uses a 64 bit kernel and user space.

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in b2e2deeb8dfa3c1a620cb5d1d0d54eccff85d2c0 and 7012f2e18fb857d6c01211f8cc6217ac5b2933fe.

**Pull request closed without merging**
