### PR TITLE
ramips: fix typo in image Makefile

### PR DESCRIPTION
**Pull request by mans0n**
ramips: fix SUPPORTED_DEVICES for Mercury MAC1200R v2
ramips: remove duplicate hyphen in DEVICE_PACKAGES

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
The package statement in patch two is nonsense anyway.

Seems to have been introduced in the initial support patch already:
https://github.com/openwrt/openwrt/commit/30786d2dd0e0063b56ba5e616e868f4e6775eaad

I'd prefer to really fix this, either by adding the packages correctly (if they are necessary) or by just removing them for now (if they are not necessary or we cannot find out easily).

**Comment by mans0n** [comment]
@adrianschmutzler You are right. I thought the packages are subtarget default but they are not. It seems belkin f7c027 is a smart plug and it does not have any usb port, so I guess we can safely remove it.

**Comment by mans0n** [comment]
Removed DEVICE_PACKAGES entirely.

**Comment by adrianschmutzler** [comment]
Thanks, merged. I plan to backport the second patch, as this package removal (-package) seems plain nonsense to me.

**Pull request closed without merging**
