### PR TITLE
mbedtls: Update to 2.11.0

### PR DESCRIPTION
**Pull request by diizzyy**
Update mbed TLS to 2.11.0
Disable OFB block mode and XTS block cipher mode, added in 2.11.0.
Drop MBEDTLS_SHA256_SMALLER implementation, not enabled by default in
upstream and reduces performance by quite a bit.

Source: include/mbedtls/config.h

Enable an implementation of SHA-256 that has lower ROM footprint but also
lower performance.

The default implementation is meant to be a reasonnable compromise between
performance and size. This version optimizes more aggressively for size at
the expense of performance. Eg on Cortex-M4 it reduces the size of
mbedtls_sha256_process() from ~2KB to ~0.5KB for a performance hit of
about 30%.

Clean up patch, use "//" consistently.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile and runtime (curl) tested on: Octeon, EdgeRouter Lite, OpenWrt Master
I'll add a separate commit if there's a need to bump other packages.

**Comment by neheb** [comment]
Why comment out MBEDTLS_ECDSA_DETERMINISTIC?

**Comment by diizzyy** [comment]
No, idea size?
It got merged here...
https://github.com/openwrt/openwrt/commit/732c24a0cac4293b058c99ff7867fd13a2670eca#diff-c74c5a58576f0ddcdd7d119cd0b2abff

**Comment by neheb** [comment]
I'd love to see comparisons. Deterministic DSA is a necessity on embedded hardware.

**Comment by diizzyy** [comment]
Size?
Alternatively ask @nbd168 if he remembers why.

**Comment by hauke** [comment]
If you change some settings please divide this into multiple commits one dumping the version and an other changing some settings. Keep the changes default settiungs for the new option with the version dump.
This is now ABI incompatible only API compatible and the so version changed, please also dump the pgk_release of all packages depending on mbedtls.

I support activating deterministic ECDSA this increases the binary size by 2K, see: 
https://git.openwrt.org/?p=openwrt/staging/hauke.git;a=commitdiff;h=87a47466eb0172bb8f929a0a54df423884b9cf37

**Comment by diizzyy** [comment]
@hauke Looks ok?

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master with a little bit reordering of the commit .

**Pull request closed without merging**
