### PR TITLE
ksmbd: update to 3.4.7

### PR DESCRIPTION
**Pull request by neheb**
Remove upstreamed patches.

Switch to git tarballs. Codeload recently had a reproducibility issue.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by dhewg** [comment]
That URL would have the same issue, as it depends on the gz implementation of git, as we all learned this week.
"github releases" are the ones which won't change. At least by github, owners can still delete/recreate IIRC. Not every project uses releases though, some just rely on tag-tarballs.
But you're in luck ;) https://github.com/cifsd-team/ksmbd/releases
The first link is a release, the "Source code" ones are not.
Cheers!

**Comment by neheb** [comment]
how so? OpenWrt defaults to xz tarballs.

**Comment by dhewg** [comment]
Ok, I'm too tired I guess, read the diff incorrectly :\
Nevermind, but wouldn't a tgz release still be a smaller download?
Anyway, you're right, this works too - as long as OpenWrt's way of pack-a-tree as txz doesn't change ;)

**Comment by diizzyy** [comment]
Just use the release tarballs that @dhewg suggests, it's overall preferred over using codeload and using git should really be last resort.

**Comment by BKPepe** [comment]
@neheb ping

**Comment by neheb** [comment]
@BKPepe fixed

**Pull request merged**
