### PR TITLE
starfive: add kernel 6.6

### PR DESCRIPTION
**Pull request by namiltd**
Adding kernel 6.6 as test kernel for starfive.

Testing on real hardware required.

### CODE REVIEW

**Comment by namiltd** [comment]
Ping @wigyori

**Comment by zxlhhyccc** [comment]
@namiltd `# CONFIG_SND_SOC_STARFIVE is not set`

**Comment by wigyori** [comment]
This patchset doesn't work on the Visionfive 1, the MMC driver fails to bring up the card. The reason is that the ccache/DMA patches from upstream had to be backported, which are a bit different on 6.6 as they were on 6.1. With these updated, both the VF1 and VF2 boards now work again.
I'll send in a new PR to cover the 6.6 upgrade.

**Comment by namiltd** [comment]
I wrongly deleted the entire patches folder. Files require verification that are not yet in kernel 6.6.

**Comment by wigyori** [comment]
Tested / working patchset at https://github.com/openwrt/openwrt/pull/16307

**Comment by namiltd** [comment]
I'm closing it to avoid duplication.

**Pull request closed without merging**
