### PR TITLE
rockchip: add Orange Pi R1 Plus (LTS) support

### PR DESCRIPTION
**Pull request by 1715173329**
Orange Pi R1 Plus (LTS) is a Rockchip RK3328 based SBC by Xunlong.

This device is similar to the NanoPi R2S, and has a 16MB
SPI NOR (mx25l12805d). The reset button is changed to
directly reset the power supply, another detail is that
both network ports have independent MAC addresses.

Note: booting from SPI is currently unsupported, you have to install
the image on a SD card.

---

The patches for u-boot are not merged yet, see:
https://lore.kernel.org/u-boot/20230520112050.93745-1-cnsztl@gmail.com/

I'm not sure when @keveryang will pick them,
but all of these should be done in v2023.07 release cycle.

### CODE REVIEW

**Comment by 1715173329** [comment]
cc @blocktrron @hauke

**Comment by regae** [comment]
as i recall when playing with this device, i can't boot with u-boot below 2023-07-rc version,
and also with lpddr3-1600.dtsi, need to change to lpddr3-666.dtsi in order to be able to boot.
if i remember correctly.

can someone confirm my memory ?

**Comment by 1715173329** [comment]
> need to change to lpddr3-666.dtsi in order to be able to boot

Yep, and thanks for confirming it. I have updated it and sent v2 to upstream already.

> i can't boot with u-boot below 2023-07-rc version

in 2023.07-rc2 rk3328 was also converted to use "standard boot", that however, didn't seem to work well with openwrt, needs more investigation.

**Comment by Pugemon** [comment]
When I enter the command "saveenv," I get the error "Saving Environment to MMC... MMC Device 0 not found, No MMC card found, Failed (1)."

CONFIG_SYS_MMC_ENV_DEV is set to 1.

How can I fix this error?

**Pull request merged**
