### PR TITLE
ramips: pinctrl-aw9523: update to current upstream

### PR DESCRIPTION
**Pull request by neheb**
Various cleanups and bugfixes were applied.

This file goes away with LTS after 6.6.

### CODE REVIEW

**Comment by robimarko** [comment]
Why do we even keep this driver in a source format instead of just backporting upstream fixes since it is upstream?

**Comment by neheb** [comment]
@robimarko well, I assume it's a bit harder to do, especially since it goes through multiple kernel versions.

**Comment by robimarko** [comment]
@neheb Looking at the history, it seems that its because it was added before it got merged upstream.

So, I would rather see the source file get dropped and it backported as patches.

**Comment by neheb** [comment]
In generic backports or ramips?

**Comment by hauke** [comment]
If this is only used in ramips add it to the ramips target.

**Comment by neheb** [comment]
@hauke done

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by ptpt52** [comment]
possible cause crash with this PR update
```
Oops#1 Part1
<4>[  1002.850165]  ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ipmac ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink jool_siit(O) jool(O) nf_defrag_ipv4 jool_common(O) ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 nfsv4 nls_ucs2_utils cifs_arc4 asn1_decoder nfs msdos bonding tls ip6_gre ip_gre gre nat46(O) nf_defrag_ipv6 ip6_udp_tunnel udp_tunnel sit ip6_tunnel oid_registry tunnel6 tunnel4 ip_tunnel udp_diag tcp_diag raw_diag inet_diag tun lockd sunrpc grace autofs4 dns_resolver nls_utf8 nls_iso8859_1 nls_cp437 crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg sha512_generic sha256_generic libsha256 sha1_generic seqiv sha3_generic drbg md5 crypto_hw_eip93 hmac geniv rng ecb des_generic libdes cmac authencesn authenc arc4 uas usb_storage leds_gpio xhci_plat_hcd
<4>[  780.939574]  xhci_pci xhci_mtk_hcd xhci_hcd ohci_platform ohci_hcd softdog fsl_mph_dr_of ehci_platform ehci_fsl sd_mod scsi_mod scsi_common ehci_hcd gpio_button_hotplug(O) vfat fat ext4 mbcache jbd2 exfat usbcore nls_base usb_common mii crc32c_generic [last unloaded: ksmbd]
<4>[  1003.053906] CPU: 2 PID: 0 Comm: swapper/2 Tainted: G        W  O       6.6.56 #0
<4>[  1003.061342] Stack : 00000000 8007f510 00000222 00000004 00000000 00000000 81813cfc 80b10000
<4>[  1003.069734]         809d0000 8084ae34 00000000 00000000 00000000 00000001 81813ca8 81891140
<4>[  1003.078094]         00000000 00000000 8084ae34 81813be0 ffffefff 00000000 ffffffea 00000000
<4>[  1003.086453]         81813bec 00000223 80946e58 ffffffff 8084ae34 00000001 8101bc80 81847300
<4>[  1003.094812]         00000000 81813e18 00000000 80840000 00000018 80430664 00000008 80b10008
<4>[  1003.103168]         ...
<4>[  1003.105608] Call Trace:
<4>[  1003.108039] [<800078d4>] show_stack+0x28/0xf0
<4>[  1003.112412] [<80750fa4>] dump_stack_lvl+0x60/0x80
<4>[  1003.117118] [<80057bb4>] __schedule_bug+0x58/0x6c
<4>[  1003.121842] 
<1>[  1003.125355] CPU 2 Unable to handle kernel paging request at virtual address 000001f8, epc == 8005a264, ra == 8005a264
<4>[  1003.136133] Oops[#1]:
<4>[  1003.138436] CPU: 2 PID: 0 Comm: swapper/2 Tainted: G        W  O       6.6.56 #0
<4>[  1003.145810] $ 0   : 00000000 80b10008 00000000 81847300
<4>[  1003.151047] $ 4   : 00000001 81847300 1100fc00 ffff00fe
<4>[  1003.156270] $ 8   : 81875fe0 0000fc00 00000064 ffffffff
<4>[  1003.161494] $12   : 00000002 000000b5 00000000 81b4a2e0
<4>[  1003.166716] $16   : 8101bc80 00000000 81027c80 00000000
<4>[  1003.171941] $20   : 8101bc80 81b4a280 00000000 00000000
<4>[  1003.177162] $24   : 00000000 00000000                  
<4>[  1003.182386] $28   : 81874000 81813de0 00000001 8005a264
<4>[  1003.187608] Hi    : 0001989a
<4>[  1003.190474] Lo    : 9e16c0c5
<4>[  1003.193337] epc   : 8005a264 ttwu_do_activate.isra.0+0x94/0x250
<4>[  1003.199275] ra    : 8005a264 ttwu_do_activate.isra.0+0x94/0x250
<4>[  1003.205207] Status: 1100fc03	KERNEL EXL IE 
<4>[  1003.209389] Cause : 40800008 (ExcCode 02)
<4>[  1003.213376] BadVA : 000001f8
<4>[  1003.216240] PrId  : 0001992f (MIPS 1004Kc)
<4>[  1003.220317] Modules linked in: ksmbd qcserial pppoe ppp_async option cdc_mbim wireguard usb_wwan sierra_net sierra rndis_host qmi_wwan pptp pppox ppp_mppe ppp_generic pl2303 nft_fib_inet mt7915e(O) mt76_connac_lib(O) mt76(O) mac80211(O) libchacha20poly1305 ipt_REJECT huawei_cdc_ncm cp210x cfg80211(O) cdc_ncm cdc_ether xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_MASQUERADE xt_LOG xt_HL xt_DSCP xt_DNETMAP(O) xt_DHCPMAC(O) xt_CLASSIFY usbserial usbnet usblp ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda ts_fsm ts_bm tcp_scalable tcp_bbr slhc sch_cake poly1305_mips nft_tproxy nft_socket nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject_bridge nft_reject nft_redir nft_quota nft_queue nft_numgen nft_nat nft_meta_bridge nft_masq nft_log nft_limit nft_hash
<4>[  1003.220900]  nft_fwd_netdev nft_fib_ipv6 nft_fib_ipv4 nft_fib nft_dup_netdev nft_ct nft_compat nft_chain_nat nfnetlink_queue nf_tproxy_ipv6 nf_tproxy_ipv4 nf_tables nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_pptp nf_nat_irc nf_nat_h323 nf_nat_ftp nf_nat_amanda nf_log_syslog nf_dup_netdev nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_sane nf_conntrack_pptp nf_conntrack_netlink nf_conntrack_netbios_ns nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast nf_conntrack_bridge ts_kmp nf_conntrack_amanda nf_conncount macvlan libcurve25519_generic libcrc32c ipvlan iptable_nat iptable_mangle iptable_filter ipt_ECN ipheth ip_tables hwmon crc_ccitt compat_xtables(O) compat(O) chacha_mips cdc_wdm br_netfilter natflow(O) natcap(O) nf_nat nf_conntrack fuse ntfs3 sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred act_gact ledtrig_usbport cryptodev(O) xt_set
<4>[  1003.310029]  ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ipmac ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink jool_siit(O) jool(O) nf_defrag_ipv4 jool_common(O) ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 nfsv4 nls_ucs2_utils cifs_arc4 asn1_decoder nfs msdos bonding tls ip6_gre ip_gre gre nat46(O) nf_defrag_ipv6 ip6_udp_tunnel udp_tunnel sit ip6_tunnel oid_registry tunnel6 tunnel4 ip_tunnel udp_diag tcp_diag raw_diag inet_diag tun lockd sunrpc grace autofs4 dns_resolver nls_utf8 nls_iso8859_1 nls_cp437 crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg sha512_generic sha256_generic libsha256 sha1_generic seqiv sha3_generic drbg md5 crypto_hw_eip93 hmac geniv rng ecb des_generic libdes cmac authencesn authenc arc4 uas usb_storage leds_gpio xhci_plat_hcd
<4>[  1003.399045]  xhci_pci xhci_mtk_hcd xhci_hcd ohci_platform ohci_hcd softdog fsl_mph_dr_of ehci_platform ehci_fsl sd_mod scsi_mod scsi_common ehci_hcd gpio_button_hotplug(O) vfat fat ext4 mbcache jbd2 exfat usbcore nls_base usb_common mii crc32c_generic [last unloaded: ksmbd]
<4>[  1003.513034] Process swapper/2 (pid: 0, threadinfo=7221d658, task=2324bb57, tls=00000000)
<4>[  1003.521112] Stack : 8101bc80 800583b0 00000000 00000000 81b4a280 8101bc80 00000000 8005bcd0
<4>[  1003.529472]         000000b5 800c06f0 81019700 81019958 8101b360 000000b5 dc978c80 00000000
<4>[  1003.537830]         ffffffff 800beac0 00000000 00000000 00000000 81d47760 81d47094 00000013
<4>[  1003.546189]         00000002 80933ae0 8093ff20 80899254 00000004 805465ac 00000000 00000000
<4>[  1003.554552]         81d47080 00000000 81d47080 804e2574 810196c0 810196c0 000000b5 81d47080
<4>[  1003.562909]         ...
<4>[  1003.565348] Call Trace:
<4>[  1003.567780] [<8005a264>] ttwu_do_activate.isra.0+0x94/0x250
<4>[  1003.573356] [<8005bcd0>] try_to_wake_up+0x248/0x70c
<4>[  1003.51004.2] [<805465ac>] __napi_schedule+0x80/0x110
<4>[  1003.583100] [<804e2574>] mtk_handle_irq_tx+0xa0/0xbc
<4>[  1003.588072] [<804e3784>] mtk_handle_irq+0xfc/0x118
<4>[  1003.592854] [<80082410>] __handle_irq_event_percpu+0x58/0x16c
<4>[  1003.598604] 
<4>[  1003.600088] Code: 02202825  0c01684c  02002025 <8e2201f8> ae200000  8c420030  10400003  02202825  0040f809 
<4>[  1003.609839] 
<4>[  1003.611323] Unhandled kernel unaligned access[#2]:
<4>[  1003.616129] CPU: 0 PID: 9 Comm: kworker/0:1 Tainted: G      D W  O       6.6.56 #0
<4>[  1003.623732] Workqueue: events 0x82daacfc
<4>[  1003.628204] $ 0   : 00000000 00000001 00000001 81813e18
<4>[  1003.633477] $ 4   : 81855dc8 ffffffff 000000bb ffffffff
<4>[  1003.638722] $ 8   : 00000001 00000000 00000004 80808080
<4>[  1003.643957] $12   : fefefeff 000000b5 00000000 00000000
<4>[  1003.649185] $16   : 81980688 81855dc8 00000000 81980688
<4>[  1003.654408] $20   : 81981e00 00000000 81823250 800517f4
<4>[  1003.659640] $24   : 00000000 803c714c                  
<4>[  1003.664865] $28   : 81854000 81855d90 80940000 80059b28
<4>[  1003.670096] Hi    : 00000b72
<4>[  1003.672967] Lo    : b5d74000
<4>[  1003.675832] epc   : 800579f4 __wake_q_add+0x8/0x58
<4>[  1003.680634] ra    : 80059b28 wake_q_add+0x10/0x6c
<4>[  1003.685325] Status: 11000403	KERNEL EXL IE 
<4>[  1003.689508] Cause : 40800010 (ExcCode 04)
<4>[  1003.693495] BadVA : 00000477
<4>[  1003.696360] PrId  : 0001992f (MIPS 1004Kc)
<4>[  1003.700444] Modules linked in: ksmbd qcserial pppoe ppp_async option cdc_mbim wireguard usb_wwan sierra_net sierra rndis_host qmi_wwan pptp pppox ppp_mppe ppp_generic pl2303 nft_fib_inet mt7915e(O) mt76_connac_lib(O) mt76(O) mac80211(O) libchacha20poly1305 ipt_REJECT huawei_cdc_ncm cp210x cfg80211(O) cdc_ncm cdc_ether xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_MASQUERADE xt_LOG xt_HL xt_DSCP xt_DNETMAP(O) xt_DHCPMAC(O) xt_CLASSIFY usbserial usbnet usblp ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda ts_fsm ts_bm tcp_scalable tcp_bbr slhc sch_cake poly1305_mips nft_tproxy nft_socket nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject_bridge nft_reject nft_redir nft_quota nft_queue nft_numgen nft_nat nft_meta_bridge nft_masq nft_log nft_limit nft_hash
<4>[  1003.700975]  nft_fwd_netdev nft_fib_ipv6 nft_fib_ipv4 nft_fib nft_dup_netdev nft_ct nft_compat nft_chain_nat nfnetlink_queue nf_tproxy_ipv6 nf_tproxy_ipv4 nf_tables nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_pptp nf_nat_irc nf_nat_h323 nf_nat_ftp nf_nat_amanda nf_log_syslog nf_dup_netdev nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_sane nf_conntrack_pptp nf_conntrack_netlink nf_conntrack_netbios_ns nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast nf_conntrack_bridge ts_kmp nf_conntrack_amanda nf_conncount macvlan libcurve25519_generic libcrc32c ipvlan iptable_nat iptable_mangle iptable_filter ipt_ECN ipheth ip_tables hwmon crc_ccitt compat_xtables(O) compat(O) chacha_mips cdc_wdm br_netfilter natflow(O) natcap(O) nf_nat nf_conntrack fuse ntfs3 sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred act_gact ledtrig_usbport cryptodev(O) xt_set
<4>[  1003.790113]  ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ipmac ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink jool_siit(O) jool(O) nf_defrag_ipv4 jool_common(O) ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 nfsv4 nls_ucs2_utils cifs_arc4 asn1_decoder nfs msdos bonding tls ip6_gre ip_gre gre nat46(O) nf_defrag_ipv6 ip6_udp_tunnel udp_tunnel sit ip6_tunnel oid_registry tunnel6 tunnel4 ip_tunnel udp_diag tcp_diag raw_diag inet_diag tun lockd sunrpc grace autofs4 dns_resolver nls_utf8 nls_iso8859_1 nls_cp437 crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg sha512_generic sha256_generic libsha256 sha1_generic seqiv sha3_generic drbg md5 crypto_hw_eip93 hmac geniv rng ecb des_generic libdes cmac authencesn authenc arc4 uas usb_storage leds_gpio xhci_plat_hcd
<4>[  1003.879132]  xhci_pci xhci_mtk_hcd xhci_hcd ohci_platform ohci_hcd softdog fsl_mph_dr_of ehci_platform ehci_fsl sd_mod scsi_mod scsi_common ehci_hcd gpio_button_hotplug(O) vfat fat ext4 mbcache jbd2 exfat usbcore nls_base usb_common mii crc32c_generic [last unloaded: ksmbd]
<4>[  1003.993166] Process kworker/0:1 (pid: 9, threadinfo=e87aecd8, task=5f07be2a, tls=00000000)
<4>[  1004.001423] Stack : 81855df4 804550ac 81980688 80455110 00000001 00000000 00000000 8077f37c
<4>[  1004.009789]         00000000 81855df4 81980688 80455110 81842281 81980680 00000001 81855dc8
<4>[  1004.018151]         00000000 00000004 00000000 803c7894 00000000 00000000 00000000 80063420
<4>[  1004.026513]         fffffffd 000000bb 81c33050 00000001 00000001 8284ac80 8180a805 803cb8d8
<4>[  1004.034891]         81003c80 81842280 80942de0 00000000 8284ad0c 82daac88 818425e8 8182322c
<4>[  1004.043293]         ...
<4>[  1004.045733] Call Trace:
<4>[  1004.048166] [<800579f4>] __wake_q_add+0x8/0x58
<4>[  1004.052622] [<80059b28>] wake_q_add+0x10/0x6c
<4>[  1004.056974] [<8077f37c>] __mutex_unlock_slowpath.isra.0+0x94/0x14c
<4>[  1004.063160] [<803c7894>] aw9523_gpio_get+0x8c/0xec
<4>[  1004.067939] [<803cb8d8>] gpiod_get_value+0x60/0xc0
<4>[  1004.072950] [<82daac88>] 0x82daac88
<4>[  1004.076867] 
<4>[  1004.078356] Code: 00000000  27bdfff8  24020001 <c0a60478> 14c00005  00000000  00400825  e0a10478  1020fffa 
<4>[  1004.088110] 
<4>[  1004.090455] ---[ end trace 0000000000000000 ]---
```

**Comment by ptpt52** [comment]
> There are some newly merged cleanups. I doubt they''ll fix anything.

what cleanups?

I reverted this commit and ran it for more than ten hours. No crash has occurred so far.

**Comment by neheb** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/log/drivers/pinctrl/pinctrl-aw9523.c?h=next-20241022

Anyway, I recommend removing patches from 805 to see when the crashing stops: https://github.com/openwrt/openwrt/tree/main/target/linux/ramips/patches-6.6

**Pull request merged**
