### PR TITLE
dropbear: bump to 2024.85

### PR DESCRIPTION
**Pull request by rockdrilla**
dropbear: bump to 2024.85

- update dropbear to latest stable 2024.85;
  for the changes see https://matt.ucc.asn.au/dropbear/CHANGES
- drop cherry-picked patches (merged in release 2024.84)
- refresh remaining patches

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by rockdrilla** [comment]
Build-tested: mediatek/filogic (GL.iNet GL-MT6000)
Binary size changes: 263091 -> 263099 (+9)
IPK size changes: 110600 -> 111758 (+1158)

**Comment by rockdrilla** [comment]
Run-tested: mediatek/filogic (GL.iNet GL-MT6000)
Custom build config:
```sh
CONFIG_DROPBEAR_MODERN_ONLY=y
# CONFIG_DROPBEAR_AGENTFORWARD is not set
# CONFIG_DROPBEAR_DBCLIENT_AGENTFORWARD is not set
# CONFIG_DROPBEAR_U2F is not set
```

**Comment by rockdrilla** [comment]
Rebase after commit 1d4b8826.

**Comment by Borromini** [comment]
Compile-tested: mvebu/cortexa72, ramips/mt7621.
Run-tested: mvebu/cortexa72 (RB5009UG+S+IN), ramips/mt7621 (EAP615-Wall v1)

Tested-by: Stijn Segers <foss@volatilesystems.org>

**Pull request merged**
