### PR TITLE
tools/isl: update to 0.20

### PR DESCRIPTION
**Pull request by wongsyrone**
Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

### CODE REVIEW

**Comment by wongsyrone** [comment]
Any update?

**Comment by wongsyrone** [comment]
Compile and run tested on x86_64 with https://github.com/openwrt/openwrt/pull/1846

**Comment by neheb** [comment]
Tested on 7.4. Seems fine.

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
