### PR TITLE
pppd: Update Makefile to install header net/ppp_defs.h

### PR DESCRIPTION
**Pull request by hojuruku**
I gave up trying to patch the source to update the include/linux & include/net headers for now
My patch broke pppd plugins. net/ppp_defs.h is needed to build any project that includes pppd.h

https://dev.openwrt.org/ticket/21350

### CODE REVIEW

**Comment by lperkov** [comment]
This pull request contains two unrelated changes. Can you please fix that?

Also, can you please describe how to replicate the issue you are trying to fix?

**Comment by plntyk** [comment]
some (not yet submitted) packages (rp-pppoe) want to use pppd.h header

```
find staging_dir -name "pppd.h"                                     
staging_dir/target-mips_24kc_musl-1.1.14/usr/include/pppd/pppd.h
```
that header contains:

```#include <net/ppp_defs.h>```

this files is currently missing

PS: There is a linux/ppp_defs.h but its having some different content

**Comment by hojuruku** [comment]
thanks plntyk for reading the ticket ;) To find out what packages I guess we could run a recursive grep on all packages for net/ppp_defs.h downloaded and extracted in the buildroot but my 4MB roms don't have enough space for that. 

A poor Chinese fork of openwrt suggested including linux/ppp_defs.h instead when compiling apps but that's not the way to go. pppd would never compile that way. 

The unrelated change is me new to git. Just changes the default CPU_TYPE for ar71xx to the most common router CPU. It freaks people out when they see 34kc instead of 24kc as the path to their cross compiler even though the optimizations for 24kc.

**Comment by jow-** [comment]
So far I simply patched the few affected packages to ship their own copies, see https://github.com/openwrt/packages/commit/419637e17f09164c852dc9e93bfa8a6129f2ab13 and https://github.com/openwrt/packages/commit/ba31ff7d5e8c8f51b5c467bc1b046e77afd1673c

**Comment by hojuruku** [comment]
For the sake of a consistent build with all apps using the same pppd headers it's the job of pppd package to install the net/ppp_defs.h as it does on all other distros.

If you see the ticket Chinese forks of openwrt are already including the wrong file (linux/ppp_defs.h) that has __u32 kernel typedefs. 

Proposed is the elegant solution and it doesn't break anything. __uXX correct me if I am wrong is datatypes in the linux kernel used for interacting with userspace, not regular userspace coding that is multi-platform.

I had a hell of a time trying to make pppd use a linux header from the kernel. This patch works, but not for pppd's plugins. If I spent more time hacking around I might have made it work. Best leave it to the real C programmers, I don't do kernel - just dynamic languages.

Once this patch is applied other packages like @jow- 's can include the header from the staging dir & or the toolchain like I tried to do with some linux headers.

```Diff
patches/209-pppd_use_toolchain_includes.patch 
pppd: update pppd's includes to be linux 4.1

Ticket #22661
Some other apps outside pppd source tree want to use broken target installed pppd.h
pppd.h defines net/ppp_defs.h that is not installed.
Openwrt does not install outdated net/ppp_defs.h it references. 
We either have to delete $(PKG_BUILD_DIR)/include/linux/ppp_defs.h or patch it. gcc doesn't seem to honor
include precidence https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html

Update $(TOPDIR)/package/network/services/ppp/Makefile
MAKE_FLAGS += COPTS="$(TARGET_CFLAGS)" \
              PRECOMPILED_FILTER=1 \
	      STAGING_DIR="$(STAGING_DIR)" \
	      TOOLCHAIN_DIR="$(TOOLCHAIN_DIR)"

Signed-off-by: Luke McKee <hojuruku@gmail.com>


--- a/pppd/Makefile.linux	2016-06-24 23:17:04.603512081 +0700
+++ b/pppd/Makefile.linux	2016-06-24 23:16:32.707910831 +0700
@@ -78,7 +78,8 @@
 
 MAXOCTETS=y
 
-INCLUDE_DIRS= -I../include
+# Preference Openwrt Toolchain linux headers first if available over bundled outdated ones #22661
+INCLUDE_DIRS= -I$(TOOLCHAIN_DIR)/include -I../include
 
 COMPILE_FLAGS= -DHAVE_PATHS_H -DHAVE_MMAP

--- a/pppd/plugins/Makefile.linux	2016-06-25 03:26:21.963519349 +0700
+++ b/pppd/plugins/Makefile.linux	2016-06-25 03:27:36.654585582 +0700
@@ -1,6 +1,6 @@
 #CC	= gcc
 COPTS	= -O2 -g
-CFLAGS	= $(COPTS) -I.. -I../../include -fPIC
+CFLAGS	= $(COPTS) -I.. -I${TOOLCHAIN_DIR}/include -I../../include -fPIC
 LDFLAGS	= -shared
 INSTALL	= install
  
--- a/include/net/ppp_defs.h	2016-06-27 00:15:58.434940886 +0700
+++ b/include/net/ppp_defs.h	2016-06-27 00:41:50.321539634 +0700
@@ -1,38 +1,11 @@
-/*	$Id: ppp_defs.h,v 1.17 2002/12/06 09:49:15 paulus Exp $	*/
-
 /*
  * ppp_defs.h - PPP definitions.
  *
- * Copyright (c) 1984 Paul Mackerras. All rights reserved.
- *
- * Redistribution and use in source and binary forms, with or without
- * modification, are permitted provided that the following conditions
- * are met:
- *
- * 1. Redistributions of source code must retain the above copyright
- *    notice, this list of conditions and the following disclaimer.
- *
- * 2. Redistributions in binary form must reproduce the above copyright
- *    notice, this list of conditions and the following disclaimer in
- *    the documentation and/or other materials provided with the
- *    distribution.
- *
- * 3. The name(s) of the authors of this software must not be used to
- *    endorse or promote products derived from this software without
- *    prior written permission.
- *
- * 4. Redistributions of any form whatsoever must retain the following
- *    acknowledgment:
- *    "This product includes software developed by Paul Mackerras
- *     <paulus@samba.org>".
+ * Copyright 1994-2000 Paul Mackerras.
  *
- * THE AUTHORS OF THIS SOFTWARE DISCLAIM ALL WARRANTIES WITH REGARD TO
- * THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
- * AND FITNESS, IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY
- * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
- * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
- * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
- * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
+ *  This program is free software; you can redistribute it and/or
+ *  modify it under the terms of the GNU General Public License
+ *  version 2 as published by the Free Software Foundation.
  */
 
 #ifndef _PPP_DEFS_H_
@@ -80,14 +53,20 @@
 #define PPP_IPX		0x2b	/* IPX protocol */
 #define	PPP_VJC_COMP	0x2d	/* VJ compressed TCP */
 #define	PPP_VJC_UNCOMP	0x2f	/* VJ uncompressed TCP */
+#define PPP_MP		0x3d	/* Multilink protocol */
 #define PPP_IPV6	0x57	/* Internet Protocol Version 6 */
+#define PPP_COMPFRAG	0xfb	/* fragment compressed below bundle */
 #define PPP_COMP	0xfd	/* compressed packet */
+#define PPP_MPLS_UC	0x0281	/* Multi Protocol Label Switching - Unicast */
+#define PPP_MPLS_MC	0x0283	/* Multi Protocol Label Switching - Multicast */
 #define PPP_IPCP	0x8021	/* IP Control Protocol */
 #define PPP_ATCP	0x8029	/* AppleTalk Control Protocol */
 #define PPP_IPXCP	0x802b	/* IPX Control Protocol */
 #define PPP_IPV6CP	0x8057	/* IPv6 Control Protocol */
+#define PPP_CCPFRAG	0x80fb	/* CCP at link level (below MP bundle) */
 #define PPP_CCP		0x80fd	/* Compression Control Protocol */
 #define PPP_ECP		0x8053	/* Encryption Control Protocol */
+#define PPP_MPLSCP	0x80fd	/* MPLS Control Protocol */
 #define PPP_LCP		0xc021	/* Link Control Protocol */
 #define PPP_PAP		0xc023	/* Password Authentication Protocol */
 #define PPP_LQR		0xc025	/* Link Quality Report protocol */
--- a/include/linux/ppp_defs.h	2016-06-27 02:05:39.975660305 +0700
+++ b/include/linux/ppp_defs.h	2016-06-27 01:41:03.841114526 +0700
@@ -1,54 +1,16 @@
-/*	$Id: ppp_defs.h,v 1.11 2002/12/06 09:49:15 paulus Exp $	*/
-
 /*
  * ppp_defs.h - PPP definitions.
  *
- * Copyright (c) 1989-2002 Paul Mackerras. All rights reserved.
- *
- * Redistribution and use in source and binary forms, with or without
- * modification, are permitted provided that the following conditions
- * are met:
- *
- * 1. Redistributions of source code must retain the above copyright
- *    notice, this list of conditions and the following disclaimer.
- *
- * 2. Redistributions in binary form must reproduce the above copyright
- *    notice, this list of conditions and the following disclaimer in
- *    the documentation and/or other materials provided with the
- *    distribution.
- *
- * 3. The name(s) of the authors of this software must not be used to
- *    endorse or promote products derived from this software without
- *    prior written permission.
- *
- * 4. Redistributions of any form whatsoever must retain the following
- *    acknowledgment:
- *    "This product includes software developed by Paul Mackerras
- *     <paulus@samba.org>".
- *
- * THE AUTHORS OF THIS SOFTWARE DISCLAIM ALL WARRANTIES WITH REGARD TO
- * THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
- * AND FITNESS, IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY
- * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
- * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
- * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
- * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
+ * Copyright 1994-2002 Paul Mackerras.
+ *  This program is free software; you can redistribute it and/or
+ *  modify it under the terms of the GNU General Public License
+ *  version 2 as published by the Free Software Foundation.
  */
-
-/*
- *  ==FILEVERSION 20020521==
- *
- *  NOTE TO MAINTAINERS:
- *     If you modify this file at all, please set the above date.
- *     ppp_defs.h is shipped with a PPP distribution as well as with the kernel;
- *     if everyone increases the FILEVERSION number above, then scripts
- *     can do the right thing when deciding whether to install a new ppp_defs.h
- *     file.  Don't change the format of that line otherwise, so the
- *     installation script can recognize it.
- */
-
 #ifndef _PPP_DEFS_H_
 #define _PPP_DEFS_H_
+#endif
+#ifndef _UAPI_PPP_DEFS_H_
+#define _UAPI_PPP_DEFS_H_
 
 /*
  * The basic PPP frame.
@@ -82,6 +45,8 @@
 #define PPP_IPV6	0x57	/* Internet Protocol Version 6 */
 #define PPP_COMPFRAG	0xfb	/* fragment compressed below bundle */
 #define PPP_COMP	0xfd	/* compressed packet */
+#define PPP_MPLS_UC	0x0281	/* Multi Protocol Label Switching - Unicast */
+#define PPP_MPLS_MC	0x0283	/* Multi Protocol Label Switching - Multicast */
 #define PPP_IPCP	0x8021	/* IP Control Protocol */
 #define PPP_ATCP	0x8029	/* AppleTalk Control Protocol */
 #define PPP_IPXCP	0x802b	/* IPX Control Protocol */
@@ -90,6 +55,7 @@
 #define PPP_CCP		0x80fd	/* Compression Control Protocol */
 #define PPP_ECPFRAG	0x8055	/* ECP at link level (below MP bundle) */
 #define PPP_ECP		0x8053	/* Encryption Control Protocol */
+#define PPP_MPLSCP	0x80fd	/* MPLS Control Protocol */
 #define PPP_LCP		0xc021	/* Link Control Protocol */
 #define PPP_PAP		0xc023	/* Password Authentication Protocol */
 #define PPP_LQR		0xc025	/* Link Quality Report protocol */
@@ -192,4 +158,4 @@
 #endif
 #endif
 
-#endif /* _PPP_DEFS_H_ */
+#endif /* _UAPI_PPP_DEFS_H_ */
```

**Comment by hojuruku** [comment]
__u32 etc from #include linux/types.h will work on any linux platform even in user-space apps, but pppd was designed to be used on other platforms of course, hence why the need for linux/ppp_defs.h and net/ppp_defs.h, the latter is more portable and does the same thing.

Many upstream projects as part of good practice if they are to compile on other unixes using other pppd stacks will use net/ppp_defs.h.

I think that's what all this is about.

**Comment by hojuruku** [comment]
Will re-do with a feature-fork when i'm testing rp-ppoe later.

**Pull request closed without merging**
