### PR TITLE
ramips: mt7621: add support for Xiaomi Mi Router 4

### PR DESCRIPTION
**Pull request by inflabz**
ramips: mt7621: add support for Xiaomi Mi Router 4

Xiaomi Mi Router 4 is the same as Xiaomi Mi Router 3G, except for the RAM(256Mib→128Mib) LED and gpio(MiNet button).

Specification
=============
Power: 12 VDC, 1.5 A
Connector type: barrel
CPU1: MediaTek MT7621A (880 MHz, 4 cores)
FLA1: 128 MiB (ESMT F59L1G81MA)
RAM1: 128 MiB (ESMT M15T1G1664A)
WI1 chip1: MediaTek MT7603EN
WI1 802dot11 protocols: bgn
WI1 MIMO config: 2x2:2
WI1 antenna connector: U.FL
WI2 chip1: MediaTek MT7612EN
WI2 802dot11 protocols: an+ac
WI2 MIMO config: 2x2:2
WI2 antenna connector: U.FL
ETH chip1: MediaTek MT7621A
Switch: MediaTek MT7621A

UART Serial
[o] TX
[o] GND
[o] RX
[ ] VCC - Do not connect it

Flash instruction
=================
1.Create a simple http server (nginx etc)
2.set uart enable
To enable writing to the console, you must reset to factory settings
Then you see uboot boot, press the keyboard 4 button (enter uboot command line)
If it is not successful, repeat the above operation of restoring the factory settings.
After entering the uboot command line, type:

setenv uart_en 1
saveenv
boot

3.use shell in uart
cd /tmp
wget http://"your_computer_ip:80"/openwrt-ramips-mt7621-xiaomi_mir4-squashfs-kernel1.bin
wget http://"your_computer_ip:80"/openwrt-ramips-mt7621-xiaomi_mir4-squashfs-rootfs0.bin
mtd write openwrt-ramips-mt7621-xiaomi_mir4-squashfs-kernel1.bin kernel1
mtd write openwrt-ramips-mt7621-xiaomi_mir4-squashfs-rootfs0.bin rootfs0
nvram set flag_try_sys1_failed=1
nvram commit
reboot
4.login to the router http://192.168.1.1/

### CODE REVIEW

**Comment by sequentiality** [comment]
@inflabz thanks, do you plan to finish it?

**Comment by inflabz** [comment]
@sequentiality  
I was having problems with my repository. The latest version is here https://github.com/inflabz/openwrt/tree/mir4nand

At the moment, I cannot continue. Since I no longer have this router.
If you want to continue, then I'm glad of it

**Comment by sequentiality** [comment]
@inflabz 
Thanks for the update. For now, I have no idea what to do. Was just searching for possible on-going development.
@ioiotor @soikjk
Guys might be able to check this as already ported 19.07.2 for R4. https://github.com/ioiotor/mir4-ss/releases/tag/V0.1

**Comment by antonsteenvoorden** [comment]
There is a new Xiaomi Router 4 Pro, are there any differences between this one and the 4Q ?

**Comment by adschm** [comment]
@inflabz Is the state in your linked repository tested?

I'd try to create a shared DTSI with mir3g, any ideas how to call the shared DTSI to distinguish it from the other devices?

**Comment by adschm** [comment]
I've taken the referenced version, messed around with it, and pushed it here:
https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/mir4

**Comment by Rstment25** [comment]
> I've taken the referenced version, messed around with it, and pushed it here:
> https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/mir4

Hi there !

Sorry I'm new here but does this mean you compiled a working image for mi router 4 that we can use ?

Are there any bugs yet or do you not have the device and are waiting for feedback?

**Comment by adschm** [comment]
I just put together what's lying around so far, we still need somebody to properly wrap it up.

**Comment by antonsteenvoorden** [comment]
Excuse me for bumping this post, but is there any new status on this PR? 

- Will this support the 4 Pro as well? [here](https://www.gearbest.com/wireless-routers/pp_3001438204877590.html) 
- If not, how can I add support for the 4 Pro?

**Comment by adschm** [comment]
This is obviously discontinued, so I'm closing the PR. If somebody intends to continue the work on this device, please submit a new PR or patch.

**Comment by sequentiality** [comment]
@adschm should I create a new PR for merging ioiotor/openwrt@d02f1be ?

**Comment by adschm** [comment]
If that is an improved version of this PR (you might also have a look at the changes from my staging area), feel free to submit it as a PR (I haven't had a closer look at the content, so this is a general answer).

**Comment by Neustradamus** [comment]
Good PR is :
- https://github.com/openwrt/openwrt/pull/3649

Merged commit is:
- https://github.com/openwrt/openwrt/commit/c2a7bb520a0fb107984ad3757174d391796cd222

**Pull request closed without merging**
