### PR TITLE
kernel: bump 6.6 to 6.6.61

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.61

Manually rebased:
	bcm27xx/patches-6.6/950-0998-i2c-designware-Add-support-for-bus-clear-feature.patch

All other patches automatically rebased.

Build system: x86/64
Build-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3
Run-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3

### CODE REVIEW

**Comment by namiltd** [comment]
Build system: x86/64
Build-tested: ramips/tplink_archer-c5-v4
Run-tested: ramips/tplink_archer-c5-v4

**Review by namiltd — APPROVED** [review]

**Comment by namiltd** [comment]
Intel HDCP2.2 services of ME Interface (INTEL_MEI_HDCP) [N/m/?] (NEW) make[7]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[6]: *** [Makefile:697: syncconfig] Error 2

**Comment by graysky2** [comment]
@namiltd - I cannot reproduce building the buildbot config for `x86/x86_geode`

**Comment by namiltd** [comment]
Kernel 6.6.62 has just been released.

**Pull request merged**
