### PR TITLE
[23.05] ipq40xx: convert Engenius EAP1300 to DSA

### PR DESCRIPTION
**Pull request by ryancdotorg**
This is just the commits from #15358 cherry-picked against openwrt-23.05.

### CODE REVIEW

**Review by cminyard — APPROVED** [review]
This all looks correct to me.  I have tested these exact changes (though I did the porting by hand and not from here) and they work without issue.

**Comment by robimarko** [comment]
I will let CI take a pass at rebased tree and merge if it passes as it seems OK to me

**Comment by ryancdotorg** [comment]
Thank you, Rob, I appreciate this.

**Comment by robimarko** [comment]
Thanks! Rebased on top of openwrt-23.05 and merged!

**Pull request merged**
