### PR TITLE
Fix error: after USB modem repluged it does not connect until reboot device or restart network.

### PR DESCRIPTION
**Pull request by rozhuk-im**
Fix error: after USB modem repluged it does not connect until reboot device or restart network.

Hotplug manager send: "remove" -> "add" -> "bind" events,
script interpret bind as "not add" = "remove" and mark device
as unavailable.

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @rozhuk-im,

Please, read our [submitting patches rules](https://openwrt.org/submitting-patches), and make sure your pull request follows them - at the moment, your commit has some formal issues, like missing SoB line.

Cheers,
Piotr

**Comment by ynezz** [comment]
Similar to #2359 ?

**Comment by rozhuk-im** [comment]
> Similar to #2359 ?

Yes, but mine version fix thin in 2 files.

**Comment by rozhuk-im** [comment]
@pepe2k is now ok?

**Comment by adrianschmutzler** [comment]
You still have formal issues, e.g. not using the real name for Signed-off.
Please team up with @andres-h in #2359 , so we can save work and don't have to discuss twice.

**Comment by rozhuk-im** [comment]
@adrianschmutzler patch in #2359 do same, but only for 3g, mine also fix wwan.
So you can merge this and close #2359.

**Comment by adrianschmutzler** [comment]
But patch in #2359 has better description and formal compliance.

Anyway, we might as well use this one. Please split your commit into two, one for each package. Then try to merge your commit message and that from #2359 into a single, better one.

And I would be obliged if the submitter of #2359 would test this one, as this one has obviously been earlier.

@andres-h

**Comment by andres-h** [comment]
> And I would be obliged if the submitter of #2359 would test this one, as this one has obviously been earlier.

The first patch is identical to mine now, so it is obviously tested.

I cannot test the second one (wwan), because I don't have a use case for that. Is it used in the current OpenWrt version at all?

**Comment by rozhuk-im** [comment]
Is something else needed here?

**Comment by tapper82** [comment]
Ping rozhuk-im  seems to have dun what they were asked to fix. Can some one take a look at this. rozhuk-im  thanks for trying to fix a bug in OpenWrt and pleas don't let the time it has taken to review put you off openwrt. We don't have a lot of people working on openwrt and some times we take to long to look at stuff. All I can say is sorry.

**Comment by rozhuk-im** [comment]
Thanks @tapper82 !
I also have #2352

**Comment by Azq2** [comment]
This problem very important and terrible. I tested this PR - works fine. 
Why you wont merge this PR?

Without this fix any USB modem wont work in openwrt. 
Many users spend time trying to get their modems to work in openwrt. But all is useless. Only pain and frustration. :(

**Comment by dedeckeh** [comment]
@Azq2 Can I add your Tested-By in the commit description ?

**Comment by dedeckeh** [comment]
Patch pushed to master; thx

**Comment by willymilkytron** [comment]
Is there any chance this fix can be backported to the 19.07 branch? USB modems are basically useless with openwrt-19.07 due to this bug.

**Pull request closed without merging**
