### PR TITLE
ath79: add support for Buffalo WZR-HP-G302H A1A0

### PR DESCRIPTION
**Pull request by musashino205**
Buffalo WZR-HP-G302H is a 2T2R 2.4 GHz 11n router, based on Atheros
AR7242.

It is Japanese market model of WZR-HP-G300NH2, but there are some
diffrences. This commit is based on WZR-HP-G300NH2 in ar71xx.
And, G302H has several hardware versions and hardware is different
dependent on the versions. This commit adds support for "A1A0"
version.

Specification:

- Atheros AR7242
- 64 MB of RAM (DDR2)
- 32 MB of Flash
  - 2x 16 MB SPI-NOR flash
- 2.4 GHz 2T2R wifi
  - Atheros AR9283
- 5x 10/100/1000 Mbps Ethernet
  - Atheros AR8316
- 7x LEDs, 5x keys
  - LED: 1x gpio-leds, 6x ath9k-leds
  - key: 3x buttons, 2x slide switches
- UART header on PCB
  - Vcc, GND, TX, RX from ethernet port side
  - 115200n8

Flash instruction using factory image:

1. Boot WZR-HP-G302H normaly and connect the computer to its LAN port
2. Access to "http://192.168.11.1/" and move to firmware update page
("ファーム更新")
3. Select the OpenWrt factory image and click update ("更新実行")
button to perform firmware update
4. Wait ~200 seconds to complete flashing

Signed-off-by: INAGAKI Hiroshi <musashino.open@gmail.com>

### CODE REVIEW

**Comment by musashino205** [comment]
ath9k-leds seems to be broken after ccab68f2d399d2395a18d1fb3495fe7e048fe054 and cannot be used now.
(gpiochip of ath9k is registered, but LEDs are not.)

```
root@OpenWrt:/# ls -alh /sys/class/leds/
drwxr-xr-x    2 root     root           0 Jan  1  1970 .
drwxr-xr-x   22 root     root           0 Jan  1  1970 ..
lrwxrwxrwx    1 root     root           0 Jan  1  1970 buffalo:red:diag -> ../../devices/platform/leds/leds/buffalo:red:diag
```
```
root@OpenWrt:/# cat /sys/kernel/debug/gpio
gpiochip0: GPIOs 0-31, parent: platform/18040000.gpio, 18040000.gpio:
 gpio-1   (                    |reset               ) in  hi    
 gpio-7   (                    |usb                 ) in  hi    
 gpio-8   (                    |router_on           ) in  lo    
 gpio-11  (                    |movie_engine        ) in  lo    
 gpio-12  (                    |wps                 ) in  hi    
 gpio-13  (                    |buffalo:usb-power   ) out lo    
 gpio-16  (                    |buffalo:red:diag    ) out lo    

gpiochip1: GPIOs 502-511, ath9k-phy0:
root@OpenWrt:/#
```

**Comment by mkresin** [comment]
Please move the `buffalo-tag -w 3` vs. `buffalo-tag -w $(hwver)` change into an own commit, as it affects other boards than the G302H A1A0 as well.

Beside of the minor (nitpick), looks good to me.

**Comment by musashino205** [comment]
@mkresin Thanks for your review.
>as it affects other boards than the G302H A1A0 as well

I see, I updated this PR.

**Comment by mkresin** [comment]
merged, thanks!

**Pull request closed without merging**
