### PR TITLE
kernel: bump 5.4 to 5.4.52

### PR DESCRIPTION
**Pull request by graysky2**
`update_kernel.sh` refreshed all patches, no human interaction was needed

Build system: x86_64
Run-tested: Netgear R7800 (ipq806x)

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Wrong SOB.

**Comment by adrianschmutzler** [comment]
> Build tested: ipq806x (Netgear R7800)

Run-tested?

**Comment by graysky2** [comment]
* Fixed email.
* Yes, R7800 is running this with no dmesg regressions.  Uptime is low but all functions services work.

**Comment by adrianschmutzler** [comment]
> Yes, R7800 is running this with no dmesg regressions. Uptime is low but all functions services work.

Then you should replace "build-tested" by "run-tested" or "device-tested" :-)

**Comment by adrianschmutzler** [comment]
> Fixed email (what does SOB stand for in this context? Submitter OB)?

**S**igned-**o**ff-**b**y :-)

**Comment by graysky2** [comment]
> Then you should replace "build-tested" by "run-tested" or "device-tested" :-)

Done.

> Signed-off-by

Got it, thanks.

**Comment by adamhnat** [comment]
did you manage to compile image without tristate thermal config path for generic kernel?

```
--- a/drivers/thermal/Kconfig
+++ b/drivers/thermal/Kconfig
@@ -4,7 +4,7 @@
 #

 menuconfig THERMAL
-       bool "Generic Thermal sysfs driver"
+       tristate "Generic Thermal sysfs driver"
        help
          Generic Thermal Sysfs driver offers a generic mechanism for
          thermal management. Usually it's made up of one or more thermal
```

**Comment by graysky2** [comment]
@adamhnat - Compiled and tested as you see with the commit.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
