### PR TITLE
brcm47xx: add kernel 4.14 support

### PR DESCRIPTION
**Pull request by p-wassi**
@hauke @rmilecki 

This commit adds support for kernel 4.14 on target brcm47xx.

Things are compile- and run-tested for WRT54GL and WL500gPv2 devices only.
The patch 030 is already included in 4.14, therefore dropped here.
Also, at two places, `asm/uaccess.h` is renamed to `linux/uaccess.h` (include files)

What about config-4.14?
EDIT: updated config-4.14 with `make kernel_menuconfig` (was manually before)
Makefile is at this time not switched over to 4.14 since things may grow too big for some of
the older devices in the default configuration.

I've summarised my changes (and a bootlog from both devices) at [1]

[1]:
https://pwassi.privatedns.org/lede/brcm47xx_414/

### CODE REVIEW

**Comment by diizzyy** [comment]
Does this actually run reliably? I could easily make my WL500gPv2 boxes reboot very easily because they would run out of memory / overload and that was way before 4.x without doing anything special at all.

**Comment by kofec** [comment]
If I can share my opinion. Maybe it is worth to split the same way  as ar71xx - tiny. I have even ath25 on latest build.

**Comment by p-wassi** [comment]
> Maybe it is worth to split the same way as ar71xx - tiny.

There's already the 'legacy' subtarget, which has the `low_mem` and `small_flash` features set.

> Does this actually run reliably? I could easily make my WL500gPv2 boxes reboot very easily
> because they would run out of memory / overload

Ok, TBH, I cheated a bit: my WL500gPv2 are upgraded to 64MB RAM and the WRT54GLs to 32MB.
WRT54GL's default 16MB are by far not enough.
For my WL500gPv2, I don't have any problems at all (uptime 5 days now).
For the WRT54GL I encountered 'problems' with flash memory size: I can now decide between
a) WiFi with WPA2 or b) openvpn-mbedtls (before, I had both) ;-)
In terms of stability, I think we can compare my upgraded WRT54GL with its 32MB RAM to the
factory WL500gPv2 with also 32MB of RAM: I currently have it running as an openvpn-client
on IPv6 without the wifi packages. RAM is 
<pre>
             total       used       free     shared    buffers     cached
Mem:         28096      22388       5708       3216       1516       8944
-/+ buffers/cache:      11928      16168
Swap:            0          0          0
</pre>
which is more of free RAM compared to some of my ar71xx vpn-clients.
Uptime is counting, so no resets observed yet.

So the WL500gPv2 with its original specifications 8MB flash, 32MB RAM should actually
give usable results. Anyway, the flash constraints on WRT54GL are one reason, why this
commit just adds 4.14 and not switches over to 4.14

**Comment by p-wassi** [comment]
In the meantime: some statistics from the WRT54GL:
<pre>
root@OpenWrt:~# uptime
 14:55:58 up 13 days,  3:35,  load average: 0.00, 0.00, 0.00
root@OpenWrt:~# free
             total       used       free     shared    buffers     cached
Mem:         28096      19916       8180         76       1516       6140
-/+ buffers/cache:      12260      15836
Swap:            0          0          0
root@OpenWrt:~# ifconfig eth0.2
eth0.2    Link encap:Ethernet  HWaddr 68:7F:74:__:__:__  
          inet addr:192.__.__.__  Bcast:192.__.__.__  Mask:255.255.255.0
          inet6 addr: fd87:____:____::____/128 Scope:Global
          inet6 addr: 2a02:____:____:____::___/128 Scope:Global
          inet6 addr: fe80::____:____:____:____/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:14566606 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7552958 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:16092752017 (14.9 GiB)  TX bytes:6145410913 (5.7 GiB)

root@OpenWrt:~#
</pre>

It has moved ~20GB in 13 days, is running an OpenVPN client and still fine.
So far, I did not experience issues regarding stability.

**Comment by hauke** [comment]
I think we should wait with to bring the mips targets to kernel 4.14 till after the release.
@rmilecki What do you think?

**Comment by rmilecki** [comment]
On 3 April 2018 at 20:39, p-wassi <notifications@github.com> wrote:
> Just added the patch for the Luxul WiFi LEDs like recently commited to master by @rmilecki .
>
> Since this PR does not switch to 4.14: what about having this target in the same state as some others (like brcm63xx for example)? I.e. support for 4.14 is there, but 18.05 is still released with 4.9 (as discussed on the mailing list)

Thanks a lot, this looks OK of course! I'd like to discuss 4.14 switch
next days.

**Pull request closed without merging**
