### PR TITLE
Openwrt 21.02

### PR DESCRIPTION
**Pull request by sanzi-nas**
Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by aparcar** [comment]
Hi, thanks for your contribution!

Please read through [the patch submitting guidelines](https://openwrt.org/submitting-patches). Your patch patch has some formal issues.

Most commonly are the following:
* Prefix the commit subject with the affected *area*, find that area by looking at `git log <modified_file>`
* Add a commit message describing why this patch was required
* Add a Signed-of-by line containing your real name

**Comment by mans0n** [comment]
This can be closed now as it should be rebased on master branch first.
But it's actually their 4th try and they doesn't seem to be listening at all, let's see what they'll do if this is kept open.
https://github.com/openwrt/openwrt/pulls?q=author%3Asanzi-nas

**Comment by aparcar** [comment]
From a quick look at the PRs you linked, you're the one not implemented the feedback you receive:

* https://github.com/openwrt/openwrt/pull/4971#issuecomment-1016402101
* https://github.com/openwrt/openwrt/pull/4979#issuecomment-1018527423

Please open this PR again `master` branch and follow the guideline for submitting patches.

**Comment by mans0n** [comment]
So this is now superseded by 3343ca7e6837 in master branch.
Note that we don't usually backport device supports to older stable branches.
https://openwrt.org/docs/guide-developer/device-support-policies#backports

**Pull request closed without merging**
