### PR TITLE
ramips: enable external amplifier for D-Link DIR-810L

### PR DESCRIPTION
**Pull request by rogerpueyo**
The 2.4 GHz radio had very poor signal reception (-88 dBm for an AP sitting 5 m away). By enabling the external amplifier, received signal has improved to -50 dBm for the same AP.

Improvement can be seen in the number of networks detected, and the signal level. Before:
```
root@OpenWrt:~# iwinfo wlan1 scan | grep Signal
          Signal: -88 dBm  Quality: 22/70
          Signal: -92 dBm  Quality: 18/70
          Signal: -92 dBm  Quality: 18/70
          Signal: -92 dBm  Quality: 18/70
          Signal: -90 dBm  Quality: 20/70
          Signal: -90 dBm  Quality: 20/70
          Signal: -92 dBm  Quality: 18/70
          Signal: -70 dBm  Quality: 40/70
          Signal: -70 dBm  Quality: 40/70
          Signal: -72 dBm  Quality: 38/70
          Signal: -72 dBm  Quality: 38/70
          Signal: -72 dBm  Quality: 38/70
```

After:
```
root@OpenWrt:~# iwinfo wlan1 scan | grep Signal
          Signal: -48 dBm  Quality: 62/70
          Signal: -58 dBm  Quality: 52/70
          Signal: -62 dBm  Quality: 48/70
          Signal: -48 dBm  Quality: 62/70
          Signal: -48 dBm  Quality: 62/70
          Signal: -50 dBm  Quality: 60/70
          Signal: -58 dBm  Quality: 52/70
          Signal: -48 dBm  Quality: 62/70
          Signal: -48 dBm  Quality: 62/70
          Signal: -66 dBm  Quality: 44/70
          Signal: -20 dBm  Quality: 70/70
          Signal: -58 dBm  Quality: 52/70
          Signal: -24 dBm  Quality: 70/70
          Signal: -24 dBm  Quality: 70/70
          Signal: -66 dBm  Quality: 44/70
          Signal: -24 dBm  Quality: 70/70
          Signal: -24 dBm  Quality: 70/70
          Signal: -52 dBm  Quality: 58/70
          Signal: -66 dBm  Quality: 44/70
          Signal: -74 dBm  Quality: 36/70
          Signal: -58 dBm  Quality: 52/70
          Signal: -66 dBm  Quality: 44/70
          Signal: -62 dBm  Quality: 48/70
          Signal: -62 dBm  Quality: 48/70
          Signal: -68 dBm  Quality: 42/70
          Signal: -60 dBm  Quality: 50/70
          Signal: -84 dBm  Quality: 26/70
```

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
@blocktrron @981213 This might be a quick one.

**Comment by psyborg55** [comment]
which revision that is, and could you verify it doesn't affect the other one negatively? A1 has ext amps, B1 does not

**Comment by 981213** [comment]
Merged into my staging tree at: https://git.openwrt.org/?p=openwrt/staging/981213.git;a=summary Thanks!

@psyborg55 

> which revision that is, and could you verify it doesn't affect the other one negatively? A1 has ext amps, B1 does not

It doesn't. This is just a pinctrl option. The actual existence of PA is determined with calibration data.

**Comment by psyborg55** [comment]
ok, in case this is b1, the commit name is wrong. it should've dropped 'external'

**Comment by rogerpueyo** [comment]
For the record, this was tested on the A1 revision.

**Comment by adrianschmutzler** [comment]
@rogerpueyo Do you think this is eligible for backporting to 19.07.

**Comment by rogerpueyo** [comment]
@adrianschmutzler Yes, I've just tested it on 19.07. It can be easily backported (same patch applies, though the file name has changed) and the behaviour is the expected, same as with trunk. How to proceed?

**Comment by adrianschmutzler** [comment]
@rogerpueyo I will take care and also backport the MAC address fix (though it will not work on 5 GHz, as I do not know whether mt76 changes are typically backported, too).

**Comment by rogerpueyo** [comment]
@adrianschmutzler , that's excellent! The MAC fix also works, albeit just on the WiSoC radio, not on the pcie one. As expected. :)

**Comment by adrianschmutzler** [comment]
BTW: My backported versions can be found here:
https://github.com/adrianschmutzler/openwrt/commits/staging-19.07

**Pull request closed without merging**
