### PR TITLE
ramips: add support for D-Link DIR-2150 A1

### PR DESCRIPTION
**Pull request by frkca**
D-link DIR-2150 is a wireless SOHO WiFI 5 (802.11.ac Wave 2) router
with 4 antennas up to 300 Mbps (2.4GHz) + 1733 Mbps (5GHz) (sold as
2100), gigabit WAN and 4 LAN ports with 4 LEDs and reset and WPS buttons.

Specifications
--------------

  - SoC: Mediatek MT7621DAT (MIPS1004Kc 880 MHz, dual core)
  - RAM: 128 MB (Winbond and others)
  - Storage: 128 MB NAND flash (various manufacturers)
  - Ethernet: 5x 10/100/1000 Mbps builtin SoC
  - Wireless: 5 GHz: Mediatek MT7615N (802.11b/g/n MIMO 2x2)
              2.4 GHz: Mediatek MT7603EN (802.11n/ac MU-MIMO 4x4)
  - 4x LED:
      - 1x power (white, amber)
      - 1x Internet (white, amber)
      - 1x WiFi 2 GHz (white)
  - 2x button (restart, WPS)

MAC Table
---------

| Interface | MAC               |
| --------- | -----------------:|
| LAN       | ..:..:..:..:..:0a |
| WAN       | ..:..:..:..:..:0a |
| 2.4 GHz   | ..:..:..:..:..:0b |
| 5 GHz     | ..:..:..:..:..:0c |

Installation
------------

OpenWRT can be installed via [D-Link Recovery GUI] (need to use double reboot):

1) Connect your MS Windows client computer (or VM) to any LAN port of the device
2) Push and hold reset button (on the bottom of the device)
   until power led starts flashing (about 5-10 secs) while plugging in the power cable.
3) Set your client IP address manually to 192.168.0.2 / 255.255.255.0
   (or anything else in the /24).
4) Call the recovery page for the device at http://192.168.0.1/
5) Before clicking upload button repeate steps 2) and 3)
   and then upload factory bin file.

Using cURL or any Linux-native client was proven non-working. The router
may even accept the image and respond with upgrade in progress page but
in fact it doesn't start the upgrade.

Thanks to Lucky1 for creating the DTS file and modifying other, so it was
really easy for me to build images, test and submit this PR.

[D-Link Recovery GUI]: https://openwrt.org/docs/guide-user/installation/installation_methods/d-link_recovery_gui

### CODE REVIEW

**Review by csharper2005 — COMMENTED** [review]
Thanks for the PR!
1. Your commits can be squashed into the one
2. Please wrap long lines in the commit message
3. `Wireless: Mediatek MT7615N (802.11b/g/n/ac MU-MIMO 4x4)` this is 5 Ghz. What about 2.4?
4. MAC address table in the commit message would be nice.
5. Please add SoB with your real name and Email at the end of the commit
6. `ramips:` instead of `mt7621:` in the commit title would look more familiar

**Comment by Borromini** [comment]
This device probably has two MT7615 radios, one for 5 and another for 2,4 GHz.

**Comment by csharper2005** [comment]
> This device probably has two MT7615 radios, one for 5 and another for 2,4 GHz.

We should have at least twice more speed than 300 Mbit in 2.4 in this case.

My suggestion is 7603

**Comment by frkca** [comment]
> Thanks for the PR!
> 
>     1. Your commits can be squashed into the one
> 
>     2. Please wrap long lines in the commit message
> 
>     3. `Wireless: Mediatek MT7615N (802.11b/g/n/ac MU-MIMO 4x4)` this is 5 Ghz. What about 2.4?
> 
>     4. MAC address table in the commit message would be nice.
> 
>     5. Please add SoB with your real name and Email at the end of the commit
> 
>     6. `ramips:` instead of `mt7621:` in the commit title would look more familiar

The 1. wasn't intended, just pulled latest master. 2-6 should now be fixed, sorry if I missed something.

**Comment by frkca** [comment]
Some troubles with CI or do I have to refresh any sources in my repo?

`Run . .github/workflows/scripts/ci_helpers.sh
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>

Diff output format options
    -p, --patch           generate patch
Kernel patches for ramips/mt7620 require refresh. (run 'make target/linux/refresh' and force push this pr)
You can also check the provided artifacts with the refreshed patch from this CI run.`

**Comment by frkca** [comment]
> @frkca You probably want to switch MT7615 and MT7603 for 2,4 / 5 GHz.

My fault, thanks, corrected ;-)

**Comment by frkca** [comment]
Can you guys @csharper2005  @Borromini @florolf or @azuwis let me know if I need to add/update anything or is this PR ready for your approval?

**Comment by csharper2005** [comment]
> Can you guys @csharper2005 @Borromini @florolf or @azuwis let me know if I need to add/update anything or is this PR ready for your approval?

I suggest to squash your 6 commits into the one. Everything else looks good to me.

**Comment by csharper2005** [comment]
@frkca do you know how to squash the commits?

**Comment by frkca** [comment]
Renamed the master to main (as the main branch did in last few days and sounds like this closed this PR :-( Will most likely open a new PR unless there is a short way to reopen this one :-(

**Comment by s-2** [comment]
Being unable to flash via the D-Link Recovery on Linux was also observed on other (ath79) devices manufactured by SGE, i.e. the D-Link COVR P2500 and C1200.
Someone recently attempted a new PR for the P2500, including a script `dlink_recovery_upload.py` that uses tcp_info information to throttle the http upload: https://github.com/openwrt/openwrt/pull/12114
Though I cannot fully evaluate whether this type of implementation would be the most desirable solution to be included within OpenWrt, could you maybe try if that script works for flashing DIR-2150 on Linux as well?

**Comment by gyimesibalazs** [comment]
I can confirm that I was able to upload OpenWRT images with a Linux computer with `dlink_recovery_upload.py` from this PR https://github.com/openwrt/openwrt/pull/12114
Device is working properly with the build from latest master branch plus this PR

**Comment by s-2** [comment]
Since I'm currently working on [support for COVR-X1860](https://forum.openwrt.org/t/add-support-for-d-link-covr-x1860/161862), including a tool `dlink-sge-image` which is an open-source reimplementation of the `imgcrypt`  binary from the GPL code released by D-Link, I was recently going through the GPL releases for many devices from this family.
Just checked DIR-2150, and the key is indeed contained and working to verify the image signature. Since I need to rework the tool once more in the coming days, I will include support for DIR-2150, so we could additionally flash this device via the regular OEM webinterface  (even on Linux), when recovery of a bricked device is not necessary.

**Comment by NBZ-Vasil** [comment]
Just wanted to say I tested this and can confirm it works on my DIR-2150 A1. I compiled the target bins following the instructions. The only obstacle was the upload problem @s-2 mentioned, I did not have the chance to test the python script but an alternative I used was running a Windows 10 virtual box and binding it to my network interface. Worked like a charm. Anyhow, it works!

Is there anything else I need to provide?

**Comment by frkca** [comment]
> squas

Hello @csharper2005 ,

I just spent quite a lot of time studying how to properly squash the commits in my branch (which include now more than 1.2k commits) to not mess up things. Would you find yourself few moments to guide me through or do you think creating a new branch and applying patch and submitting a new PR will be cleaner? While I do want to contribute, I'm now a bit disappointed with this paperwork :-(

Thanks!

**Comment by s-2** [comment]
> do you think creating a new branch and applying patch and submitting a new PR will be cleaner?

Working with git can be annoying sometimes, especially since updates to a PR should not be actual merges like to an existing project, but overwrite the previous attempt so that the result is one clean, single commit on top of current master (so we typically rebase and force-push rather than merging). Additionally, you local branch seems to be `master`, which could make it more annoying when you try to rebase your commits on top of the changes in latest master from origin.

However, you don't need to create a new PR, since the PR is just tied to a branch (`frkca:master` in this case), so the PR would update automatically to whatever changes in that branch.

In the current situation, you probably want to create a new branch locally first.
/* edit: the following commands assume `origin` points to openwrt/openwrt, not your fork. Check with `git remote -v` first */

`git fetch origin` might be a good idea at first, though it's probably updated already.
`git checkout origin/master` will give you a detached HEAD warning (since your local master diverged), just ignore that for now.
`git checkout -b dir-2150` will create a new branch locally, in the same state of origin/master.

Now you can merge your DIR-2150-related commits from master to that branch, i.e. `git cherry-pick <commit-hash>`. The hashes can be found by calling `git log master`, or just looking them up in the github WebUI in the current state of this PR. Hopefully, they will apply nicely ;-)

You probably have 2 commits at this point, try if everything builds. Now we squash them to one:
`git rebase -i HEAD~2` will start an interactive rebase on top of the commit "HEAD minus two" (which should be the same as master). A text editor will open with two commits marked `pick`, change the later one to `squash` or `fixup` (fixup will ignore the second commit message, squash will merge the commit messages, but you can edit them in a text editor later). Saving that text file should start the rebase and give you a single commit in the DIR-2150 branch, on top of origin/master (check with `git log`).

Now go back to master `git checkout master` and force this to be the same as your DIR-2150 branch.
`git reset --hard DIR-2150` (be careful with this one, it does not care about any uncommited changes in the worktree)

Now you can force-push master to the remote pointing to your github account.
`git push --force <your-remote>` (run `git remote -v` to make sure origin points to openwrt/openwrt, not your fork)

Technically this should update the PR, let me know if anything breaks in between though 🙂

**Review by zkabelac — COMMENTED** [review]
Definitelly works on my Dir-2150 - would be nice to have this merged upstream - so users can easily user newer snapshot builds

**Comment by csharper2005** [comment]
> Definitelly works on my Dir-2150 - would be nice to have this merged upstream - so users can easily user newer snapshot builds

Need to fix formal issues (deprecated syntax and so on).

**Comment by Lucky1openwrt** [comment]
this PR could be updated to add recovery and factory images
as believe the key was leek for this model
please do test as don't have a device 

just need to add these Lines to /linux/ramips/image/mt7621.mk file under Device/dlink_dir-2150-a1
`  
  IMAGES += factory.bin
  IMAGE/factory.bin := $$(IMAGE/recovery.bin) | dlink-sge-image $$(DEVICE_MODEL)
`

like the dir-853-a3 below 

`
define Device/dlink_dir-853-a3
  $(Device/dlink_dir-xx60-a1)
  DEVICE_MODEL := DIR-853
  DEVICE_VARIANT := A3
  IMAGES += factory.bin
  IMAGE/factory.bin := $$(IMAGE/recovery.bin) | dlink-sge-image $$(DEVICE_MODEL)
endef
`

https://github.com/openwrt/firmware-utils/commit/ba5bc4e1ae9d3e7b41d3bed39ce505670dc95078

**Comment by rodneyrod** [comment]
Hey @Lucky1openwrt thanks for helping out with this CR and the others you've put up, not sure if @frkca is still around, would it be possible to add your changes to this CR or incorporate them in a new one?

**Comment by Lucky1openwrt** [comment]
ok @rodneyrod I can try 
as I don't have that model can you check thing s for me ?
do you still have factory firmware installed ?

**Comment by rodneyrod** [comment]
@Lucky1openwrt Not at the moment (I'm actually using one of your nightly builds from Feb :grin: ) but I can revert it easily enough. I should have time later tonight or on the weekend.
Let me know what upgrade path(s) and settings you want to test and I'll post the results by then.

**Comment by Lucky1openwrt** [comment]
I do want to confirm the original MAC address allocated by dlink in there firmware
if i remember the logs is the place to find the Mac address
then test the direct web update form oem to openwrt

**Comment by hauke** [comment]
Support for this device was added in 30e8fd73ec54865ea7db4e6e08560e6a16dd4272, see #15263.

**Pull request closed without merging**
