### PR TITLE
[22.03] bcm27xx: refresh 5.10 patches

### PR DESCRIPTION
**Pull request by dave14305**
bcm27xx builds have been broken on openwrt-22.03 since 5.10.121 was merged.

Patch conflicts with this commit:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/mailbox/mailbox.c?h=linux-5.10.y&id=bb2220e0672b7433a9a42618599cd261b2629240

Signed-off-by: dave14305 <44532942+dave14305@users.noreply.github.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
we need a correct Sob tag with real name and email.

Also can you put here the conflict?

**Comment by dave14305** [comment]
The patch is from [Raspberry Pi in 2020](https://github.com/raspberrypi/linux/commit/66b7c6aa6af587519ae263e234b6871df2d6a35c) to revert https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/mailbox/mailbox.c?h=linux-5.10.y&id=c7dacf5b0f32957b24ef29df1207dc2cd8307743.

Now in 2022, 5.10.121 has also reverted the same commit with an additional fix.
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/mailbox/mailbox.c?h=linux-5.10.y&id=bb2220e0672b7433a9a42618599cd261b2629240

I’m not a dev to know if these are equivalent solutions, but it seems possible that the patch is no longer needed.

It didn’t come up in master because bcm27xx is already moved to 5.15.x.

Maybe @graysky2 can review.

**Comment by Ansuel** [comment]
@dave14305 the patch looks good... Just can you fix the Sob (Signed-off by) tag and rework the description to something like

```
Drop 950-0005-Revert-mailbox-avoid-timer-start-from-callback patch now present
upstream.

Patch got superseded by commit [1] upstream with additional fixup.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/mailbox/mailbox.c?h=linux-5.10.y&id=bb2220e0672b7433a9a42618599cd261b2629240
```

And add your Sob tag... Pls do it. If you can do at least provide a correct Sob and I will push a fixed patch in 22.03

**Review by graysky2 — APPROVED** [review]

**Comment by graysky2** [comment]
@Ansuel - done

**Comment by dave14305** [comment]
> Pls do it. If you can do at least provide a correct Sob and I will push a fixed patch in 22.03

I realize I don’t see how to update the actual commit text on Github, but I’m fine to close this PR if you are ok to fix it directly in 22.03 branch.

**Comment by Ansuel** [comment]
@dave14305 pls don't close this... Ok just provide Sob tag and I will fix it.

@graysky2 Reviewed-by tag?

**Comment by dave14305** [comment]
Good to go. Fixed it with git.

**Comment by mj22226** [comment]
@Ansuel refresh 22.03 patches is a better option
```
raspi22-03$ git status
On branch openwrt-22.03
Your branch is up to date with 'origin/openwrt-22.03'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    target/linux/bcm27xx/patches-5.10/950-0005-Revert-mailbox-avoid-timer-start-from-callback.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0038-pinctrl-bcm2835-Set-base-to-0-give-expected-gpio-num.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0046-MMC-added-alternative-MMC-driver.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0060-Add-support-for-all-the-downstream-rpi-sound-card-dr.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0131-bcmgenet-Better-coalescing-parameter-defaults.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0138-usb-add-plumbing-for-updating-interrupt-endpoint-int.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0139-xhci-implement-xhci_fixup_endpoint-for-interval-adju.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0151-hid-usb-Add-device-quirks-for-Freeway-Airmouse-T3-an.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0185-pinctrl-bcm2835-Remove-gpiochip-on-error.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0187-pinctrl-bcm2835-Accept-fewer-than-expected-IRQs.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0190-of-overlay-Correct-symbol-path-fixups.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0252-SQUASH-pinctrl-bcm2835-Set-base-for-bcm2711-GPIO-to-.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0323-media-i2c-Add-driver-for-Sony-IMX477-sensor.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0334-net-bcmgenet-Reset-RBUF-on-first-open.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0347-drm-vc4-Add-debugfs-node-that-dumps-the-current-disp.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0355-xhci-quirks-add-link-TRB-quirk-for-VL805.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0408-drm-atomic-Pass-the-full-state-to-CRTC-atomic-enable.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0409-drm-atomic-Pass-the-full-state-to-CRTC-atomic_check.patch
        deleted:    target/linux/bcm27xx/patches-5.10/950-0410-drm-atomic-Pass-the-full-state-to-CRTC-atomic-begin-.patch
        deleted:    target/linux/bcm27xx/patches-5.10/950-0411-drm-vc4-hvs-Align-the-HVS-atomic-hooks-to-the-new-AP.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0412-drm-vc4-Pass-the-atomic-state-to-encoder-hooks.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0597-drm-vc4-crtc-Pass-the-drm_atomic_state-to-config_pv.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0598-drm-vc4-crtc-Fix-vc4_get_crtc_encoder-logic.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0643-drm-vc4-crtc-Add-encoder-to-vc4_crtc_config_pv-proto.patch
        deleted:    target/linux/bcm27xx/patches-5.10/950-0644-drm-vc4-crtc-Rework-the-encoder-retrieval-code-again.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0645-drm-vc4-crtc-Add-some-logging.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0647-drm-vc4-Fix-timings-for-interlaced-modes.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0650-Support-RPi-DPI-interface-in-mode6-for-18-bit-color.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0657-Documentation-devicetree-Add-documentation-for-imx37.patch
        deleted:    target/linux/bcm27xx/patches-5.10/950-0678-bcm2711_thermal-Don-t-clamp-temperature-at-zero.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0681-drm-Introduce-an-atomic_commit_setup-function.patch
        deleted:    target/linux/bcm27xx/patches-5.10/950-0685-drm-vc4-hvs-Align-the-HVS-atomic-hooks-to-the-new-AP.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0686-drm-Use-the-state-pointer-directly-in-atomic_check.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0689-drm-automatic-legacy-gamma-support.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0690-drm-Pass-the-full-state-to-connectors-atomic-functio.patch
        modified:   target/linux/bcm27xx/patches-5.10/950-0699-drm-vc4-Fix-timings-for-VEC-modes.patch
        deleted:    target/linux/bcm27xx/patches-5.10/950-0720-drm-vc4-Increase-the-core-clock-based-on-HVS-load.patch
        deleted:    target/linux/bcm27xx/patches-5.10/950-0721-drm-vc4-Increase-the-core-clock-to-a-minimum-of-500M.patch
        modified:   target/linux/generic/hack-5.10/402-mtd-blktrans-call-add-disks-after-mtd-device.patch
        modified:   target/linux/generic/hack-5.10/420-mtd-set-rootfs-to-be-root-dev.patch
        modified:   target/linux/generic/pending-5.10/470-mtd-spi-nor-support-limiting-4K-sectors-support-base.patch
        modified:   target/linux/generic/pending-5.10/495-mtd-core-add-get_mtd_device_by_node.patch
```

**Comment by Ansuel** [comment]
@mj22226 lots of delete patch is see all merged upstream?

**Comment by mj22226** [comment]
> lots of delete patch is see all merged upstream?

I didn't' check that but at least they need to be manually fixed

**Comment by dave14305** [comment]
So is it going to continue to be problematic when, for example, @hauke cherry-picks @graysky2's kernel bumps into 22.03, but bcm27xx patches-5.10 don't get refreshed because they don't exist in master?

**Comment by Ansuel** [comment]
@dave14305 nha it's just that a correct refresh is needed... in your testing the patch you fix here is the only one that had conflicts? after that openwrt-22.02 compiled correctly?

**Comment by dave14305** [comment]
I thought it was a one-off after reading the buildbot logs, but now I see it's more widespread and my single commit won't help.

950-0410-drm-atomic-Pass-the-full-state-to-CRTC-atomic-begin-.patch is the next one to fail.

Time to call in the professionals.

**Comment by Ansuel** [comment]
@dave14305 well this can be fixed easily just by building an image...

**Comment by mj22226** [comment]
> 950-0410-drm-atomic-Pass-the-full-state-to-CRTC-atomic-begin-.patch is the next one to fail.

@dave14305 that patch only need to be edited manually in
```
--- a/drivers/gpu/drm/ingenic/ingenic-drm-drv.c
+++ b/drivers/gpu/drm/ingenic/ingenic-drm-drv.c
@@ -292,7 +292,7 @@ ingenic_drm_crtc_mode_valid(struct drm_c
 }
 
 static void ingenic_drm_crtc_atomic_begin(struct drm_crtc *crtc,
-					  struct drm_crtc_state *oldstate)
+					  struct drm_atomic_state *state)
 {
 	struct ingenic_drm *priv = drm_crtc_get_priv(crtc);
 	u32 ctrl = 0;
@@ -312,14 +312,14 @@ static void ingenic_drm_crtc_atomic_begi
 }
 
 static void ingenic_drm_crtc_atomic_flush(struct drm_crtc *crtc,
-					  struct drm_crtc_state *oldstate)
+					  struct drm_atomic_state *state)
 {
 	struct ingenic_drm *priv = drm_crtc_get_priv(crtc);
-	struct drm_crtc_state *state = crtc->state;
-	struct drm_pending_vblank_event *event = state->event;
+	struct drm_crtc_state *crtc_state = crtc->state;
+	struct drm_pending_vblank_event *event = crtc_state->event;
 
-	if (drm_atomic_crtc_needs_modeset(state)) {
-		ingenic_drm_crtc_update_timings(priv, &state->mode);
+	if (drm_atomic_crtc_needs_modeset(crtc_state)) {
+		ingenic_drm_crtc_update_timings(priv, &crtc_state->mode);
 		priv->update_clk_rate = true;
 	}
 
@@ -331,7 +331,7 @@ static void ingenic_drm_crtc_atomic_flus
 	}
 
 	if (event) {
-		state->event = NULL;
+		crtc_state->event = NULL;
 
 		spin_lock_irq(&crtc->dev->event_lock);
 		if (drm_crtc_vblank_get(crtc) == 0)
```
the other upstreamed patch is
950-0678-bcm2711_thermal-Don-t-clamp-temperature-at-zero.patch
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/thermal/broadcom/bcm2711_thermal.c?h=v5.10.128&id=83603802954068ccd1b8a3f2ccbbaf5e0862acb0
after that  refresh the patches  `make target/linux/{clean,refresh} V=s`

**Comment by Ansuel** [comment]
(if he do the change i would suggest `Co-Developed-by` tag @mj22226 if it's ok for you)

**Comment by dave14305** [comment]
Working on it.

**Comment by dave14305** [comment]
Ping @rsalvaterra to also review since he might have concerns with commits like these (as he said in the broad sense on IRC).

**Comment by dave14305** [comment]
I realized I could not keep my SoB with integrity because I did not really test this end-to-end, since my build env is inadequate. I will leave this to the kernel gurus and figure out how to avoid this in the future kernel 5.10 updates for bcm27xx. Thanks guys for the education!

**Comment by hauke** [comment]
Thanks for reporting this problem and trying to fix it. I refreshed all patches in OpenWrt 22.03 in this commit ee67afeda9eb2f4b0b779e2969421ce96c27e720. It should compile now again.

**Pull request closed without merging**
