### PR TITLE
kernel: bump 6.6 to 6.6.43

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.43

All patches automatically rebased.

Build system: x86/64
Build-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3
Run-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3

### CODE REVIEW

**Comment by namiltd** [comment]
File target\linux\bcm27xx\patches-6.6\950-0490-input-ads7846-Add-missing-spi_device_id-strings.patch to remove. The patch is already included in the code.

**Comment by graysky2** [comment]
@namiltd - you are right, I wonder why the update script failed to detect it.

**Comment by rany2** [comment]
@graysky2 fairly minor but the changelog URL is invalid, there's an `a` at the end which causes a 404 to be returned.

**Comment by schuettecarsten** [comment]
I have some issues on my bcm27xx (rpi4) device, not sure if they're caused by kernel 6.6.41/6.6.42 or what's going on here, still investigating (https://github.com/openwrt/openwrt/issues/16011). Will try using 6.6.42.

**Comment by rany2** [comment]
Not sure if you care, but I've compile and run tested on `mediatek/mt7622` (Redmi AX6S).

**Comment by schuettecarsten** [comment]
Works in bcm27xx (Raspberry Pi 4)

**Comment by schuettecarsten** [comment]
6.6.43 also works on bcm27xx/bcm27xx

**Pull request merged**
