### PR TITLE
ath79: ZTE MF286[,A,R]: fix WLAN LED mapping 

### PR DESCRIPTION
**Pull request by Leo-PL**
This series fixes WLAN LED mapping for the ath79-based part of ZTE MF286 family, and completes the suport of the devices, fixing their last quirk.

First commit ensures the pinctrl mapping of GPIO19 is set as GPIO properly, which isn't the case after U-boot ends.
Second commit redefines the GPIO hog as LED again and maps it to throughput trigger of 2.4GHz radio, so the actual LED shows activity of both radios by default - using onboard logic - and can be configured from userspace.

Run tested on both MF286 (the older version) and MF286R, which shares mainboard with MF286A.
This series should be cherry-picked for 22.03 release, to ensure complete device support.

Signed-off-by: Lech Perczak <lech.perczak@gmail.com>

### CODE REVIEW

**Comment by Leo-PL** [comment]
cc @chunkeey

**Comment by obsy** [comment]
Tested-by: Cezary Jackiewicz <cezary@eko.one.pl>

**Comment by Leo-PL** [comment]
And in the meantime tested also on MF286A by a friend.

**Comment by Leo-PL** [comment]
Updated commit description to make it more clear, how the single WLAN LED is controlled by both radios. Logical AND is used, which plays very well with phy0tpt + phy1tpt trigger combination. No changes to the code.

**Comment by Leo-PL** [comment]
Also, @chunkeey - is `blue:wlan` or `blue:wlan2g` more appropriate label for the LED, given that the actual LED is shared, and the GPIO part is controlled by default by 2.4GHz radio? What do you think?

**Comment by chunkeey** [comment]
> Also, @chunkeey - is blue:wlan or blue:wlan2g more appropriate label for the LED, given that the actual LED is shared, and the GPIO part is controlled by default by 2.4GHz radio? What do you think? In theory, you can set arbitrary triggers both for ath10k-phy0 and blue:wlan to control its behavior fully.

With "label"-property being deprecated in favor of function and color property. this "wlan" vs "wlan2g" "label" is becoming pointless since the name will be generated by the color and function property. I have no idea what upstream has for ideas about wlan2g vs 5g. Currently, this is what the function enumerator for.

(it would be great if the led-source with the trigger could be described like usb-ports through the device-tree. The current phy$Xtpt phy$Xassoc is not great, because the phy$X can be swapped and change. This would require a bigger rewrite of cfg80211/mac80211 led-code.

(should I drop the label-property in the patch?)

**Comment by Leo-PL** [comment]
@chunkeey I'll make a quick test if it still works as previously. For 99% - you can, kernel will generate the exact same sysfs handle for that anyway.

Maybe I shouldn't write that here, but defines for `function` property are just strings, so I could write `function = "wlan2g"` - upstream would hate me for that, but it would work.

**Comment by chunkeey** [comment]
> Maybe I shouldn't write that here, but defines for `function` property are just strings, so I could write `function = "wlan2g"` - upstream would hate me for that, but it would work.

yes, the function property just holds a string. Technically, upstream has a bit more to say about approaching this issue.
https://www.kernel.org/doc/html/latest/leds/leds-class.html

> Examples of proper LED names:
> [...] 
> phy1:green:wlan
> phy3::wlan
> [...]

Though, I don't think this is a good idea there. The wireless stack assigns the phy$x in ascending order. It's a "first come first served" situation so things could end up swapped :shrug:. Also, "freed" phy$i slots do not get reassigned and if you hit INT_MAX, you are out of luck until you reload cfg80211.

**Comment by Leo-PL** [comment]
Yeah, we probably have to live with that for now.

**Comment by chunkeey** [comment]
I stumbled across: "this way the LED will show activity for both bands, as it is bound by logical AND with output of
ath10k-phy0 LED."

and wondered what this meant. But the PR's description helped:

> so the actual LED shows activity of both radios by default - using onboard logic - and can be configured from userspace.

plain as day: "using onboard logic" ?! How Wow, Ok. 

I wonder though about "AND". Because then the LED would "only" blink if there's simulations traffic on both bands which can be hard to pull off with only one client. Is it maybe "OR" - logic? Because then the LED would blink if there's traffic on either wifi band. (Yes, this is very academic/unnecessarily pedantic).

**Comment by Leo-PL** [comment]
It is "AND" because the activity indication for "tpt" trigger is "active low". And yes, the LED will light up only if both `ath10k-phy0` and `blue:wlan` are lit.

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
