### PR TITLE
ramips: correct Newifi-D2 LED display

### PR DESCRIPTION
**Pull request by ghost**
Update 01_leds

### CODE REVIEW

**Comment by ptpt52** [comment]
not just newifi-d2, most leds not work in current 01_leds
@nbd168

**Comment by musashino205** [comment]
> Signed-off-by: G <kvmcore@gmail.com>

Please use your real name for ```Signed-off-by: ``` and author field (```From: ```) of the [commit](https://github.com/openwrt/openwrt/pull/13510.patch)

**Comment by kvmcore** [comment]
> > Signed-off-by: G [kvmcore@gmail.com](mailto:kvmcore@gmail.com)
> 
> Please use your real name for `Signed-off-by: ` and author field (`From: `) of the [commit](https://github.com/openwrt/openwrt/pull/13510.patch)

I don't want to provide my real name, nor do I want to provide a false name for this matter. If you feel it's inappropriate, please delete this PR.

**Comment by musashino205** [comment]
ref: https://openwrt.org/submitting-patches#submission_guidelines

> all commits must contain Signed-off-by: My Name <my@email.address> where you write your real name and real email address, in accordance with [Section 11 of the Linux Kernel patches guide](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD#n416)

**Comment by kvmcore** [comment]
> ref: https://openwrt.org/submitting-patches#submission_guidelines
> 
> > all commits must contain Signed-off-by: My Name [my@email.address](mailto:my@email.address) where you write your real name and real email address, in accordance with [Section 11 of the Linux Kernel patches guide](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD#n416)

It's too troublesome, I don't want to do any further actions, please delete the PR.

**Pull request closed without merging**
