### PR TITLE
ramips: mt7621: enable lzma-loader for Asus RT-N56U-B1

### PR DESCRIPTION
**Pull request by l-lossen**
Fixes boot loader LZMA decompression issues

Signed-off-by: Alex Khodin <mxktz1@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@l-lossen do we have an issue open about this or some link to reference?

**Comment by l-lossen** [comment]
Issue is same as described here:
 #10645 

Also we have discussion on russian forum 4Pda about this issue. [link](https://4pda.to/forum/index.php?s=&showtopic=428005&view=findpost&p=117398284)

Locally builded image with enabled lzma-loader fix the problem.

**Comment by hauke** [comment]
The linked ticket is about Netgear EX6150v1. 
Do you have the same problem Asus RT-N56U-B and with your change it boots up fine?

**Comment by l-lossen** [comment]
[hauke](https://github.com/hauke),
exactly. Official builds 22.03.0, 22.03.1, 22.03.2 cause boot loop.
I made new builds with customized mt7621.mk - and now device boots up fine.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in f6099d797460b23e06fb0c391606346993b4593e.

**Pull request closed without merging**
