### PR TITLE
ramips : add SPDX license identifier into dts,dtsi for R6350 and WRC-1900GST

### PR DESCRIPTION
**Pull request by drvlabo**
add SPDX license identifier into dts,dtsi for R6350 and WRC-1900GST

Signed-off-by: NOGUCHI Hiroshi <drvlabo@gmail.com>

### CODE REVIEW

**Comment by ynezz** [comment]
@drvlabo Please can you consider `SPDX-License-Identifier: GPL-2.0-or-later OR MIT` as in [DTS Checklist](https://openwrt.org/submitting-patches#dts_checklist) ?

> Having MIT as alternative is sometimes preferred by upstream maintainers
and allows sharing that simple code with other projects. We don't really
want multiple DTS versions for the same device.

**Comment by drvlabo** [comment]
I would like to specify GPL-2.0 only. (same as Linux kernel license)
The checklist says "add proper license", I understand that it is not but to force adding "OR MIT".

If it may not be accepted, I'll discard this PR.

**Comment by ynezz** [comment]
> I would like to specify GPL-2.0 only. (same as Linux kernel license)

@drvlabo Sure, you can choose compatible license accroding to your preferences, it's your code after all, so it's your choice. I was just trying to suggest you to consider adding that MIT part as it would make sharing your work with other projects and operating systems easier.

From https://www.kernel.org/doc/html/latest/process/license-rules.html 

> OR should be used if the file is dual licensed and only one license is to be selected. For example, some dtsi files are available under dual licenses

And this are numbers of SPDX license identifiers extracted for you from DTS files from Linux kernel source v4.19.10:

```
   710 SPDX-License-Identifier: GPL-2.0
   260 SPDX-License-Identifier: (GPL-2.0+ OR MIT)
     70 SPDX-License-Identifier: GPL-2.0+
     51 SPDX-License-Identifier: (GPL-2.0 OR MIT)
     32 SPDX-License-Identifier: GPL-2.0+ OR MIT
     31 SPDX-License-Identifier: GPL-2.0-or-later OR MIT
     20 SPDX-License-Identifier: (GPL-2.0+ OR BSD-3-Clause)
     15 SPDX-License-Identifier: GPL-2.0 OR X11
      5 SPDX-License-Identifier: GPL-2.0 
      3 SPDX-License-Identifier: (GPL-2.0 or BSD-3-Clause)
      2 SPDX-License-Identifier: (GPL-2.0+ OR X11)
      2 SPDX-License-Identifier: (GPL-2.0+ or MIT)
      2 SPDX-License-Identifier: (GPL-2.0+)
      1 SPDX-License-Identifier: (GPL-2.0+ OR BSD-3-Clause) 
      1 SPDX-License-Identifier:  GPL-2.0+
      1 SPDX-License-Identifier: BSD-3-Clause
```

> If it may not be accepted, I'll discard this PR.

No, nobody has said or has written something like that, it's not mandatory.

**Comment by mkresin** [comment]
@musashino205 You have done changes to the elecom_wrc-gst.dtsi as well and therefore you must agree to the licence change. Do you agree to the licence change of the elecom_wrc-gst.dtsi?

**Comment by musashino205** [comment]
@mkresin Yes. I recieved the email from @drvlabo and agreed to this changes :)

**Comment by mkresin** [comment]
merged, thanks!

**Pull request closed without merging**
