### PR TITLE
Package kernel crash log ramoops/pstore facility as kmod and use it for R7800

### PR DESCRIPTION
**Pull request by hnyman**
Alternative approach to #5045 as suggested by @chunkeey and @ynezz 

* Package the ramoops facility as kmod.
* Define the exposed symbols in the default kernel config
 
* Second commit shows the implementation in R7800 and XR500

Note: I packaged ramoops, pstore and reed_solomon .ko files into the same package. Not sure if that is allowed.

Run-tested with R7800

----

```
 OpenWrt SNAPSHOT, r18779-64125ed1d0
 -----------------------------------------------------
root@router1:~# logread | grep -i -E "pstore|ramo"

root@router1:/# opkg install /etc/backup.stats/ramoops.ipk
Installing kmod-ramoops (5.10.96-1) to root...
Configuring kmod-ramoops.

root@router1:/# ls -l /overlay/upper/lib/modules/5.10.96/
-rw-r--r--    1 root     root         20836 Feb  4 22:13 pstore.ko
-rw-r--r--    1 root     root         23076 Feb  4 22:13 ramoops.ko
-rw-r--r--    1 root     root          9152 Feb  4 22:13 reed_solomon.ko

After reboot:

root@router1:~# logread | grep -i -E "pstore|ramo"
Wed Feb  9 23:49:14 2022 kern.info kernel: [   16.377464] pstore: Using crash dump compression: deflate
Wed Feb  9 23:49:14 2022 kern.info kernel: [   16.377494] pstore: Registered ramoops as persistent store backend
Wed Feb  9 23:49:14 2022 kern.info kernel: [   16.381920] ramoops: using 0x40000@0x42100000, ecc: 0


After crash:

 OpenWrt SNAPSHOT, r18779-64125ed1d0
 -----------------------------------------------------

root@router1:~# ls -l /sys/fs/pstore/
-r--r--r--    1 root     root         27251 Feb  9 23:50 dmesg-ramoops-0
root@router1:~# cat /sys/fs/pstore/dmesg-ramoops-0
Panic#1 Part1
<7>[    0.671541] pcieport 0001:00:00.0: assign IRQ: got 45
<6>[    0.672395] pcieport 0001:00:00.0: AER: enabled with IRQ 46
...
<6>[  334.923721] sysrq: Trigger a crash
<0>[  334.923762] Kernel panic - not syncing: sysrq triggered crash
<2>[  334.926040] CPU0: stopping
<4>[  334.931846] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 5.10.96 #0
<4>[  334.934445] Hardware name: Generic DT based system
<4>[  334.940633] [<c030e32c>] (unwind_backtrace) from [<c030a1ac>] (show_stack+0x14/0x20)
<4>[  334.945225] [<c030a1ac>] (show_stack) from [<c0629a48>] (dump_stack+0x94/0xa8)
```

### CODE REVIEW

**Comment by ynezz** [comment]
> Note: I packaged ramoops, pstore and reed_solomon .ko files into the same package. Not sure if that is allowed.

You should check the module interdependencies and if they exists, you should split them into separate packages, otherwise someone else would need to do this split in the future, because it make no sense to drag in ramoops module if you just need error correction module.

**Comment by hnyman** [comment]
Any idea, where in the modules Makefiles they should be placed?

* pstore to fs.mk ?
* ramoops and reed_solomon to other.mk ?

**Comment by hnyman** [comment]
I have now split the modules to three different kmods.

**Comment by chunkeey** [comment]
on-topic: @hnyman can you please add a link to the ramoops' admin guide to the commit?
<https://www.kernel.org/doc/html/v5.10/admin-guide/ramoops.html>.

I think it nicely explains how to get the dump and that this can also be setup through the kernel cmdline.

A bit off-topic:

The ipq806x target is currently not building because of the EA8500 and EA7500-v1 3MiB KERNEL_SIZE limit.
I "think" this happened because of the 5.10 kernel bump, but I'm not 100% sure.

Should I just disable the affected devices?

**Comment by hnyman** [comment]
> can you please add a link to the ramoops' admin guide to the commit?

I can do that in a few days. 
(If you want to merge this PR sooner, just add that by yourself)

**Comment by hnyman** [comment]
@chunkeey 
Regarding your offtopic:

> The ipq806x target is currently not building because of the EA8500 and EA7500-v1 3MiB KERNEL_SIZE limit.
>I "think" this happened because of the 5.10 kernel bump, but I'm not 100% sure.
>
> Should I just disable the affected devices?

Looking at the buildbot logs, the first failed build seems to just have a few commits, one is about adding fast path to bridge. A few kilobytes more to kernel size... See changes tab:

https://buildbot.openwrt.org/master/images/#/builders/33/builds/452

You better disable the affected devices, so that others build.

**Comment by hnyman** [comment]
@chunkeey 

> on-topic: @hnyman can you please add a link to the ramoops' admin guide to the commit?
> https://www.kernel.org/doc/html/v5.10/admin-guide/ramoops.html.

Done.

**Comment by hnyman** [comment]
Could this be merged before the 22.0x feature freeze...

**Comment by hnyman** [comment]
cc @chunkeey 
Note that I did not yet add kmod-ramoops to the R7800 device packages, but just added the needed definitions to DTS. The user still needs to install the kmod with opkg or include it into the build.

I wonder if it should be added to the R7800 device packages?

**Comment by chunkeey** [comment]
CONFIG_EFI_VARS_PSTORE was coming up in the x86 builds. I added it as disabled.
From what I know, people can use the firmware builder to add packages to their images: https://firmware-selector.openwrt.org/.
So this should work for your cases since they just need to add the kmod, no?

(I just merged it. It was queued but bcm27xx needs to come back)

**Comment by hnyman** [comment]
@chunkeey  @aparcar 
I noticed that bcm63xx with kernel 5.4 now fails in buildbot, as I only defined the kernel config symbols for 5.10.
I thought that the 5.10 bump there would be merged by now.

Should I issue a pr for 5.4 config, or can you just apply the config changes there?

**Comment by chunkeey** [comment]
oh, I found compile issue with mac80211 changes as well.

(I just noticed you managed to sneak this in :) )

# CONFIG_PSTORE_COMPRESS_DEFAULT="deflate"

congratulations!

**Pull request closed without merging**
