### PR TITLE
uboot-mvebu: add __u64 patch as present in others

### PR DESCRIPTION
**Pull request by neheb**
Needed for compilation under macOS.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Thanks for your contribution to OpenWrt!

@svlobanov I don't know of a good way to upstream this. Any ideas?

### CODE REVIEW

**Comment by neheb** [comment]
hmmm, maybe replace asm/types.h with linux/types.h . I don't have a macOS system to test.

**Comment by BKPepe** [comment]
Maybe @httpstorm could help with this since it was introduced in this PR: https://github.com/openwrt/openwrt/pull/3894

But still, in the patch itself, there are missing formal details like - author, commit subject, commit description, etc. 

**Before merging this here, this should be reported to upstream to fix it properly or send this pull request to U-boot developers to cooperate.**

But that's not your fault. That should be done first in #3894.

**Comment by aparcar** [comment]
I'd merge this for now as it fixes compilation on macOS systems, once there is patch upstream, upgrade all u-boots at once?

**Comment by neheb** [comment]
Proper solution might be to change this: https://github.com/u-boot/u-boot/blob/master/include/asm-generic/int-ll64.h#L27 to

```
__clang__
```

**Comment by BKPepe** [comment]
> I'd merge this for now as it fixes compilation on macOS systems, once there is patch upstream, upgrade all u-boots at once?

Please, just don't do it. That's not a good idea at all. When you merge this, no one bothers to look at it anymore because it works. You or someone else should take time to do it more properly and cooperate with U-boot developers to fix it to get rid of this patch in the future. At least create an issue in U-boot. That would at least be something.

Otherwise, we will rebase this patch every time there is a new U-boot version. It will increase the maintenance effort, and we will carry this patch forever as with other patches in the OpenWrt base repository.

**Comment by aparcar** [comment]
@neheb can you send your patches upstream?

**Comment by neheb** [comment]
@aparcar updated. Please retest.

**Comment by aparcar** [comment]
@neheb does not do the trick https://paste.sr.ht/~aparcar/5ef3e7faa65db581384c4a86e8b7aa395446219e

**Comment by neheb** [comment]
I don't have /Users/user/src/openwrt/openwrt/staging_dir/host/include/asm/types.h locally. can you post the contents of /Users/user/src/openwrt/openwrt/staging_dir/host/include ?

**Comment by neheb** [comment]
maybe https://github.com/openwrt/openwrt/blob/master/tools/mkimage/patches/050-Add-compatibility-with-non-Linux-hosts.patch has a big hint...

**Comment by neheb** [comment]
yeah. @aparcar please retest this PR.

**Comment by neheb** [comment]
@diizzyy since you use FreeBSD, can you comment on this patch and see if all of it is needed?

**Comment by diizzyy** [comment]
@neheb 
__u64 isn't defined but on the other hand I don't see any patches for this in FreeBSD's repo so I guess something gets confused in OpenWrt's buildroot? https://cgit.freebsd.org/ports/tree/sysutils/u-boot-tools/
The port is using a rather old version though....

**Comment by neheb** [comment]
Current assumption is that @hauke 's patch is for an older version of FreeBSD. I don't build OpenWrt on FreeBSD so I don't know if all of that patch is needed.

**Comment by diizzyy** [comment]
I doubt anyone does as there's much "Linux"-ism involved which breaks in various places. There's even a challenge to build even on non Debian hosts but that's another topic.

**Comment by neheb** [comment]
mkhash patch would be great.

**Comment by httpstorm** [comment]
> mkhash patch would be great.

mkhash patch: https://github.com/openwrt/openwrt/pull/9385

**Comment by neheb** [comment]
@httpstorm I just looked at your link. Where is asm/types.h in staging_dir coming from? The one in u-boot sources is different.

**Comment by neheb** [comment]
tools/include/asm/types.h ...

**Comment by neheb** [comment]
ping @hauke This is ready.

**Comment by BKPepe** [comment]
Did someone try to upstream @hauke's patch?

**Comment by neheb** [comment]
I just managed to get FreeBSD  somewhat working. mkimage does not even build. stdarg.h and stdbool.h cannot be found.

**Comment by neheb** [comment]
Reverted to the simpler patch used in other uboot packages.

A proper fix for this would be more complex. Unfortunately, I do not have a macOS machine.

**Comment by BKPepe** [comment]
So, in that case, what's left is to report this issue to U-boot developers and let them know about this. It would be nice if the patch itself has commit message, why this is necessary to have.

**Comment by httpstorm** [comment]
@neheb Hi Rosen! That simple patch works just fine on macOS, without any conflicts on Linux. In case you have better ideas, prepare a few test branches, and I can test them for you. I'm fine with the simple patch. Good luck.

**Comment by aparcar** [comment]
Can you please provide a link where you send this to upstream?

**Comment by neheb** [comment]
It has not been sent upstream. It's not applicable upstream. Upstream will never support non Linux compilation.

Note that https://github.com/openwrt/openwrt/blob/master/tools/Makefile#L146 adds various headers to get it to compile.

**Comment by BKPepe** [comment]
> It has not been sent upstream. It's not applicable upstream. Upstream will never support non Linux compilation.

Is there any reference from U-boot developers? For example, it could be an issue where they stated this? It would be nice if we could **at least** try to do it even though they refused it, so we can let users/devs know about it.

@pali Can you please take a look at it and say if @neheb is correct or if there is anything we can do to prevent carrying this patch forever for macOS?

**Comment by neheb** [comment]
@BKPepe editing https://github.com/openwrt/openwrt/blob/master/tools/include/asm/types.h is a solution.

**Comment by neheb** [comment]
@BKPepe editing https://github.com/openwrt/openwrt/blob/master/tools/include/asm/types.h is a solution.

**Comment by ynezz** [comment]
> Upstream will never support non Linux compilation.

FYI they CI QA building of host tools for [Windows](https://github.com/u-boot/u-boot/blob/master/.azure-pipelines.yml#L16) and [macOS](https://github.com/u-boot/u-boot/blob/master/.azure-pipelines.yml#L42)

**Comment by neheb** [comment]
I'll look into this. From a quick glance it doesn't seem to be applicable to uboot itself.

**Comment by neheb** [comment]
If someone wants to attempt this, by all means.

**Pull request closed without merging**
