### PR TITLE
procd: Add wrapper for uci_validate_section()

### PR DESCRIPTION
**Pull request by jefferyto**
This adds a wrapper (`uci_validate_load`) for `uci_validate_section()` that allows callers (through a callback function) to access the values set by `uci_validate_section()`, without having to manually declare a (potentially long) list of local variables.

The callback function receives two arguments when called, the config section name and the return value of `uci_validate_section()`.

If no callback function is given, then the wrapper exits with the value returned by `uci_validate_section()`.

This also updates several init scripts to use the new wrapper function.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
I have run-tested these changes in armvirt-32 (snapshot) and malta-be (master), though more thorough examination is certainly welcome.

The actually wrapper name can be changed; I just couldn't come up with a better name :joy:

I've been working on an init script for a package recently and I'd really like to use `uci_validation_section()`, but the prospect of repeating every option in a `local` declaration was not appealing. It's not a big deal when there are only a few options, but when there are a lot of options (e.g. [clamav](https://github.com/openwrt/packages/blob/cf327c3d89605601d8a137c88f45d55e958e2cd7/net/clamav/files/clamav.init#L50), [e2guardian](https://github.com/openwrt/packages/blob/cf327c3d89605601d8a137c88f45d55e958e2cd7/net/e2guardian/files/e2guardian.init#L88)), it's barely maintainable.

**Comment by jow-** [comment]
I like the change. Would probably change `uci_validate_load` (which sounds as if the success of the loading is validated) to `uci_load_validate`. APart from that LGTM

**Comment by jefferyto** [comment]
Done :joy: - thanks!

**Comment by stangri** [comment]
@jefferyto @jow- I'm trying to use a list as the default value with uci_load_validate and I'd appreciate feedback on it. I've started discussion at https://forum.openwrt.org/t/uci-load-validate-how-to-pass-a-list-as-default-value/168134.

**Pull request closed without merging**
