### PR TITLE
qoriq: add kernel 6.6

### PR DESCRIPTION
**Pull request by namiltd**
Adding kernel 6.6 as test kernel for qoriq.

Testing on real hardware required.

### CODE REVIEW

**Comment by namiltd** [comment]
Because there were problems with compilation I enabled:
```
CONFIG_CRYPTO_CURVE25519=y
CONFIG_CRYPTO_LIB_CURVE25519_GENERIC=y
```
Or maybe it would be better?:
```
# CONFIG_CRYPTO_MANAGER_DISABLE_TESTS is not set
# CONFIG_CRYPTO_MANAGER_EXTRA_TESTS is not set
```

**Comment by namiltd** [comment]
Maybe we should remove source-only from FEATURES in the Makefile?

**Comment by namiltd** [comment]
Ping @stintel

**Comment by stintel** [comment]
I won't be able to test this until I move my M300's from my apartment to my house and install them here.

Maybe @RussellSenior or @f00b4r0 could test this.

**Comment by RussellSenior** [comment]
Builds and runs fine (afaict) on my M300.

**Comment by stintel** [comment]
> Because there were problems with compilation I enabled:
> 
> ```
> CONFIG_CRYPTO_CURVE25519=y
> CONFIG_CRYPTO_LIB_CURVE25519_GENERIC=y
> ```

The same has been done for the layerscape target so I'm fine with the above.

**Comment by stintel** [comment]
Merged, thanks.

**Comment by namiltd** [comment]
@stinel Next stage: https://github.com/openwrt/openwrt/pull/16120

**Pull request merged**
