### PR TITLE
ath79: support Meraki MR18 and Z1

### PR DESCRIPTION
**Pull request by Leo-PL**
Bring back Cisco Meraki MR18 and Z1 from long limbo after ar71xx removal. Based largely on @chunkeey's work, fixing only a few typos, but with added fix for potentially affected Mikrotik devices using SW ECC for their NAND flash. Installation is the same as it was in ar71xx.

### CODE REVIEW

**Comment by chunkeey** [comment]
Thank you.

Yes, I don't have the mikrotik boards, but since Koen is fine with the
proposed mikrotik change, the mr18 image is definitely ready for inclusion.
I can do that on Sunday.

The Z1 is different, the last word was that it bricked the router. And
resetting an Z1 is from what was told me, not that straight forward as it
involves shorting out data pins on the nand chip during boot in order to
trigger recovery/fallback. So if there isn't a confirmation, I would rather
err on the side of caution than let people unknowingly brick their routers.

Lech Perczak ***@***.***> schrieb am Mo., 8. Mai 2023, 19:49:

**Comment by Leo-PL** [comment]
Okay, feel free to not include Z1 - I pulled it in because it was easier to cherry-pick changes for MR18 from your staging tree.

**Comment by chunkeey** [comment]
Merged without Z1 for now. Thanks!

**Comment by Leo-PL** [comment]
> 

Should work without a hitch, I was able to run this ath79 board on MR18 before 22.03 got branched off as well.

**Comment by chunkeey** [comment]
> Should work without a hitch, I was able to run this ath79 board on MR18 before 22.03 got branched off as well.

True, it's been running for a long time here as well. I'm worried about the NAND changes. Another NAND device could have sneaked by.

**Comment by Leo-PL** [comment]
I checked that while backporting for my own use - only those two Mikrotiks are affected. If no ECC mode is set, it defaults to hw. And IIRC no new Mikrotik NAND devices were added from 21.02 until migration to `yafut`.

**Comment by Leo-PL** [comment]
@chunkeey I just checked downloads.openwrt.org for an image for MR18 and strangely, I found no initramfs image. It might be worth to check buildbot logs to see why it happened

**Comment by xback** [comment]
Just tested on a large set of various rb922 boards.

Found one:

```
[    1.610391] UBI: auto-attach mtd2
[    1.613782] ubi0: attaching mtd2
[    1.618041] ubi0 error: validate_ec_hdr: bad VID header offset 2048, expected 512
[    1.625656] ubi0 error: validate_ec_hdr: bad EC header
[    1.630899] Erase counter header dump:
[    1.634702]  magic          0x55424923
[    1.638511]  version        1
[    1.641522]  ec             1
[    1.644530]  vid_hdr_offset 2048
[    1.647812]  data_offset    4096
[    1.651079]  image_seq      341407690
[    1.654792]  hdr_crc        0xa75ed772
[    1.658603] erase counter header hexdump:
[    1.662699] CPU: 0 PID: 1 Comm: swapper Not tainted 5.15.112 #0
[    1.668715] Stack : 00000000 00000000 80c19c8c 80990000 807e0000 8071e834 80c37520 807e1da3
[    1.677232]         809932d4 00000001 55424923 800ba08c 20303020 00000001 80c19c48 c4895742
[    1.685733]         00000000 00000000 8071e834 80c19ae0 ffffefff 00000000 00000000 ffffffea
[    1.694247]         0000007c 80c19aec 0000007c 807e6f58 818c9600 80e34000 00000000 80e34000
[    1.702762]         00000000 55424923 818cb014 818c9200 00000018 803e229c 00000000 80990000
[    1.711274]         ...
[    1.713762] Call Trace:
[    1.716241] [<80066b30>] show_stack+0x28/0xf0
[    1.720702] [<804587d8>] validate_ec_hdr+0xc0/0x118
[    1.725660] [<804594a8>] ubi_io_read_ec_hdr+0x20c/0x26c
[    1.730976] [<8045eba0>] ubi_attach+0x2f4/0x1538
[    1.735674] [<80452f58>] ubi_attach_mtd_dev+0x530/0xbf8
[    1.741008] [<8087bc1c>] ubi_init+0x320/0x3bc
[    1.745442] [<80060638>] do_one_initcall+0x50/0x1b8
[    1.750407] [<808670b4>] kernel_init_freeable+0x1d0/0x26c
[    1.755896] [<8067dd80>] kernel_init+0x20/0x108
[    1.760518] [<80061ed8>] ret_from_kernel_thread+0x14/0x1c
[    1.765999] 
[    1.767522] ubi0 error: ubi_io_read_ec_hdr: validation failed for PEB 0
[    1.774239] ubi0 error: ubi_attach_mtd_dev: failed to attach mtd2, error -22
[    1.781468] UBI error: cannot attach mtd2

```

**Comment by Leo-PL** [comment]
This begs the question, if ath79 NAND driver actually respects the `nand-ecc-step-size` property. I'll take a look into the kernel soon.

**Comment by xback** [comment]
I went through the code and think I noticed another issue also.

The check now for 2048 is within ecc_engine_host condition, not within ecc_engine_soft.

So on todays driver, it simply does not enter that branch afaict.

I hope to dig a little bit deeper on Friday when I'm back at the office.

**Pull request closed without merging**
