### PR TITLE
mediatek: dts: mt7988a.dtsi: Enable clock of MACSec HW offload engine

### PR DESCRIPTION
**Pull request by onlyfly34**
Enable clock of MACSec HW offload engine on MT7988

### CODE REVIEW

**Comment by hauke** [comment]
Does the driver support MacSec already?

**Comment by onlyfly34** [comment]
I’ll commit it later.

**Comment by onlyfly34** [comment]
I posted MACSec clock settings first, to facilitate better integration of the macsec driver within our internal SDK(MT7988). However, if this requires HW MACSec driver uploaded to get merged. I'll propose this someday.

**Comment by onlyfly34** [comment]
Found a build error. I'll fix and repost.

**Comment by Neustradamus** [comment]
@onlyfly34: Why do you close all times?
- https://github.com/openwrt/openwrt/pull/16919
- https://github.com/openwrt/openwrt/pull/16920
- https://github.com/openwrt/openwrt/pull/16921

**Pull request closed without merging**
