### PR TITLE
package: busybox: disable mips16 on hard-float

### PR DESCRIPTION
**Pull request by 981213**
The busybox built with mips16 enabled has broken seq command. Disassembling shows that the call to hard-float strtod in mips16 code is generated without the __call_stub_fp:
```
   0x00406d6f <+118>:   lw      v0,32(sp)
   0x00406d71 <+120>:   sll     s0,2
   0x00406d73 <+122>:   addu    s0,v0,s0
   0x00406d75 <+124>:   lw      a0,-4(s0)
   0x00406d79 <+128>:   jal     0x44ebc1 <strtod@mips16plt>
   0x00406d7d <+132>:   addiu   a1,sp,84
   0x00406d7f <+134>:   sw      v0,64(sp)
   0x00406d81 <+136>:   lw      v0,0(s1)
   0x00406d83 <+138>:   sw      v1,68(sp)
```

As a result, strtod returns the result in float point registers while the calling mips16 code expect the result in v0/v1.

I discovered this while adding support for Siflower SF19A2890, which has MIPS InterAptiv cores with FPU.
Fixing GCC is too hard for me, so I decided to disable mips16 to get a functional busybox for now.
This should also be broken on pistachio, but I don't have a board to test it.

### CODE REVIEW

**Comment by KanjiMonster** [comment]
Please also report this issue upstream, so they are at least aware of it.

**Comment by hauke** [comment]
nice finding. On the pistachio target (MIPS InterAptiv with FPU) awk is broken. That is probably the same problem.

**Comment by hauke** [comment]
If you are able to create a small program which shows this problem with an unmodified GCC the upstream GCC people will probably debug this further and provide a fix for the root cause.

**Comment by 981213** [comment]
I tried binutils 2.43 + gcc 14.2 + https://github.com/gcc-mirror/gcc/commit/9522fc8bb7812f2ad50eb038e0938bfd958e730f and these two patches dropped:
toolchain/gcc/patches-14.x/110-Fix-MIPS-PR-84790.patch (already fixed in gcc 14.2 according to the bug link)
toolchain/gcc/patches-14.x/900-bad-mips16-crt.patch (A really old patch which I don't know if it's still needed)

I don't have the board with me right now. I'll make a commit on the toolchain after tested tomorrow.

**Comment by 981213** [comment]
I'm unable to create a minimal reproducable code for gcc. The generated code is correct if I compile only the seq source code (with a bit modification to make it work without libbb.).
I'll report the bug as-is in a few days.

**Pull request closed without merging**
