### PR TITLE
malta: update MIPS64 ISA to R2

### PR DESCRIPTION
**Pull request by guidosarducci**
**Suggested reviewers**: @ynezz , @hauke , @yousong (based on commit history)
**Compile tested**:  master branch, malta target: mips32el, mips32eb, mips64el, mips64eb 
**Run tested**:  master branch, malta target: mips32el, mips32eb, mips64el, mips64eb

**Test note**: Both `/proc/cpuinfo` output and presence of a working eBPF JIT were used as confirmation during testing.

**Description**:
Usage of current R1 ISA is inconsistent with the MIPS32 R2 subtargets, little used and has limited utility for testing. Indeed, many distros target a minimum R2 ISA. Debian MIPS 32-bit/64-bit ports all use MIPS R2 ISA since Stretch, for example. Fedora's MIPS arch also targets the R2 ISA for 32-bit/64-bit.

Widely used MIPS64 platforms like Octeon are based on the MIPS R2 ISA or later, and benefit from having a compatible test platform in OpenWRT. While Linux does support MIPS64 R1 targets, its usefulness for development and testing is limited. As an example, the modern Linux eBPF JIT requires a MIPS R2 ISA or later, making R1 targets a poor choice for advanced networking development.

These commits separately update the MIPS64 ISA used during image building and QEMU emulation.

Thanks!

### CODE REVIEW

**Comment by neheb** [comment]
Interesting...

Isn't this also true of the devices supported by the octeon target?

**Comment by Grommish** [comment]
> Interesting...
> 
> Isn't this also true of the devices supported by the octeon target?

octeon uses the octeonplus CPU define, not the general mips64 define.

**Comment by neheb** [comment]
I was right: https://github.com/gcc-mirror/gcc/blob/master/gcc/config/mips/mips-cpus.def#L169

@Grommish I was talking about the kernel config. I don't see any reference to MIPS_R2. Maybe one of the other config entries defines it...

**Comment by Grommish** [comment]
Right.. I was talking about the MIPS Documentation, but I suppose it would depend on the kernel level.  I've only used 4.19 and 5.4, so far.

```
-march=arch

    Generate code that runs on arch, which can be the name of a generic MIPS ISA, or the name of a particular processor. The ISA names are: ‘mips1’, ‘mips2’, ‘mips3’, ‘mips4’, ‘mips32’, ‘mips32r2’, ‘mips32r3’, ‘mips32r5’, ‘mips32r6’, ‘mips64’, ‘mips64r2’, ‘mips64r3’, ‘mips64r5’ and ‘mips64r6’. The processor names are: ‘4kc’, ‘4km’, ‘4kp’, ‘4ksc’, ‘4kec’, ‘4kem’, ‘4kep’, ‘4ksd’, ‘5kc’, ‘5kf’, ‘20kc’, ‘24kc’, ‘24kf2_1’, ‘24kf1_1’, ‘24kec’, ‘24kef2_1’, ‘24kef1_1’, ‘34kc’, ‘34kf2_1’, ‘34kf1_1’, ‘34kn’, ‘74kc’, ‘74kf2_1’, ‘74kf1_1’, ‘74kf3_2’, ‘1004kc’, ‘1004kf2_1’, ‘1004kf1_1’, ‘i6400’, ‘i6500’, ‘interaptiv’, ‘loongson2e’, ‘loongson2f’, ‘loongson3a’, ‘gs464’, ‘gs464e’, ‘gs264e’, ‘m4k’, ‘m14k’, ‘m14kc’, ‘m14ke’, ‘m14kec’, ‘m5100’, ‘m5101’, ‘octeon’, ‘octeon+’, ‘octeon2’, ‘octeon3’, ‘orion’, ‘p5600’, ‘p6600’, ‘r2000’, ‘r3000’, ‘r3900’, ‘r4000’, ‘r4400’, ‘r4600’, ‘r4650’, ‘r4700’, ‘r5900’, ‘r6000’, ‘r8000’, ‘rm7000’, ‘rm9000’, ‘r10000’, ‘r12000’, ‘r14000’, ‘r16000’, ‘sb1’, ‘sr71000’, ‘vr4100’, ‘vr4111’, ‘vr4120’, ‘vr4130’, ‘vr4300’, ‘vr5000’, ‘vr5400’, ‘vr5500’, ‘xlr’ and ‘xlp’. The special value ‘from-abi’ selects the most compatible architecture for the selected ABI (that is, ‘mips1’ for 32-bit ABIs and ‘mips3’ for 64-bit ABIs).

    The native Linux/GNU toolchain also supports the value ‘native’, which selects the best architecture option for the host processor. -march=native has no effect if GCC does not recognize the processor.

    In processor names, a final ‘000’ can be abbreviated as ‘k’ (for example, -march=r2k). Prefixes are optional, and ‘vr’ may be written ‘r’.

    Names of the form ‘nf2_1’ refer to processors with FPUs clocked at half the rate of the core, names of the form ‘nf1_1’ refer to processors with FPUs clocked at the same rate as the core, and names of the form ‘nf3_2’ refer to processors with FPUs clocked a ratio of 3:2 with respect to the core. For compatibility reasons, ‘nf’ is accepted as a synonym for ‘nf2_1’ while ‘nx’ and ‘bfx’ are accepted as synonyms for ‘nf1_1’.

    GCC defines two macros based on the value of this option. The first is _MIPS_ARCH, which gives the name of target architecture, as a string. The second has the form _MIPS_ARCH_foo, where foo is the capitalized value of _MIPS_ARCH. For example, -march=r2000 sets _MIPS_ARCH to "r2000" and defines the macro _MIPS_ARCH_R2000.

    Note that the _MIPS_ARCH macro uses the processor names given above. In other words, it has the full prefix and does not abbreviate ‘000’ as ‘k’. In the case of ‘from-abi’, the macro names the resolved architecture (either "mips1" or "mips3"). It names the default architecture when no -march option is given.
```

**Comment by guidosarducci** [comment]
Just to be clear, user-space packages and kernels are handled slightly differently, since Linux's build scripts also define compiler options. For example, all octeon* platforms get similar kernel optimization since Linux will use "-march=octeon" cflags (which guarantees working on all platforms).

See [this example](https://github.com/openwrt/openwrt/blob/master/target/linux/generic/pending-5.4/308-mips32r2_tune.patch) of how we tweak this for OpenWRT mips32 when needed.

The octeon target userspace packages use "-march=octeon+" instead. Is this strictly necessary? Probably not -- the same malta packages compiled for mips64r2 should also work on octeon targets too (don't recall FPU or other special units). That approach would have another big advantage: addition of other newer octeon targets is less likely to draw complaints of bloating the size of package repos.

But this is really tangential to malta/mips64 and this PR.

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Comment by guidosarducci** [comment]
Thanks, Hauke. Could you also take a look at the malta PR https://github.com/openwrt/openwrt/pull/3291 when you have a chance? Nothing controversial, just cleanup.

On October 11, 2020, at 07:42, Hauke Mehrtens <notifications@github.com> wrote:

Thank you for the patch, it was applied to master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/openwrt/openwrt/pull/3457#issuecomment-706714860">https://github.com/openwrt/openwrt/pull/3457#issuecomment-706714860</a>", "url": "<a href="https://github.com/openwrt/openwrt/pull/3457#issuecomment-706714860">https://github.com/openwrt/openwrt/pull/3457#issuecomment-706714860</a>", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Pull request closed without merging**
