### PR TITLE
ramips: fix lzma-loader for buffalo_WSR_600DHP

### LINKED ISSUE #11919: WSR-600DHP boot looping after upgrading to 22.03
### Describe the bug

The device was working fine in 21.02.5, cannot boot after upgrading to 22.03. Tried 22.03.0 and 22.03.3 from official download page, same behavior.
Here is the log from serial

```
===================================================================
     		MT7621   stage1 code 13:14:00 (ASIC)
     		CPU=50000000 HZ BUS=12500000 HZ
==================================================================
Change MPLL source from XTAL to CR...
do MEMPLL setting..
MEMPLL Config : 0x31000000
3PLL mode + External loopback
=== XTAL-40Mhz === DDR-800Mhz ===
PLL3 FB_DL: 0x4, 1/0 = 628/396 11000000
PLL4 FB_DL: 0xa, 1/0 = 616/408 29000000
PLL2 FB_DL: 0x10, 1/0 = 663/361 41000000
do DDR setting..[00320000]
Apply DDR2 Setting...(use default AC)
          0    8   16   24   32   40   48   56   64   72   80   88   96  104  112  120
      --------------------------------------------------------------------------------
0000:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0001:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0002:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0003:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0004:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0005:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0006:|    0    0    0    0    0    0    0    0    0    0    0    0    0    1    1    1
0007:|    0    0    0    0    0    1    1    1    1    1    1    1    1    1    1    1
0008:|    1    1    1    1    1    1    1    1    1    1    1    1    0    0    0    0
0009:|    1    1    1    1    0    0    0    0    0    0    0    0    0    0    0    0
000A:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000B:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000C:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000D:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000E:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000F:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0010:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0011:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0012:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0013:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0014:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0015:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0016:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0017:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0018:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0019:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001A:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001B:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001C:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001D:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001E:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001F:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
rank 0 coarse = 8
rank 0 fine = 48
B:|    0    0    0    0    0    0    0    1    1    1    0    0    0    0    0    0
opt_dle value:8
DRAMC_R0DELDLY[018]=00002C2A
==================================================================
		RX	DQS perbit delay software calibration 
==================================================================
1.0-15 bit dq delay value
==================================================================
bit|     0  1  2  3  4  5  6  7  8  9
--------------------------------------
0 |    7 6 7 7 3 5 6 4 6 9 
10 |    9 11 7 10 9 7 
--------------------------------------

==================================================================
2.dqs window
x=pass dqs delay value (min~max)center 
y=0-7bit DQ of every group
input delay:DQS0 =42 DQS1 = 44
==================================================================
bit	DQS0	 bit      DQS1
0  (1~83)42  8  (1~85)43
1  (1~83)42  9  (1~85)43
2  (2~83)42  10  (1~86)43
3  (1~80)40  11  (1~86)43
4  (1~83)42  12  (1~86)43
5  (1~84)42  13  (1~84)42
6  (1~83)42  14  (1~88)44
7  (1~82)41  15  (1~84)42
==================================================================
3.dq delay value last
==================================================================
bit|    0  1  2  3  4  5  6  7  8   9
--------------------------------------
0 |    7 6 7 9 3 5 6 5 7 10 
10 |    10 12 8 12 9 9 
==================================================================
==================================================================
     TX  perbyte calibration 
==================================================================
DQS loop = 15, cmp_err_1 = ffff0000 
dqs_perbyte_dly.last_dqsdly_pass[0]=15,  finish count=1 
dqs_perbyte_dly.last_dqsdly_pass[1]=15,  finish count=2 
DQ loop=15, cmp_err_1 = ffff0000
dqs_perbyte_dly.last_dqdly_pass[0]=15,  finish count=1 
dqs_perbyte_dly.last_dqdly_pass[1]=15,  finish count=2 
byte:0, (DQS,DQ)=(8,8)
byte:1, (DQS,DQ)=(8,8)
20,data:88
[EMI] DRAMC calibration passed

===================================================================
     		MT7621   stage1 code done 
     		CPU=50000000 HZ BUS=12500000 HZ
===================================================================


U-Boot 1.1.3 (Aug 14 2014 - 22:05:54)

Board: Ralink APSoC DRAM:  64 MB
relocate_code Pointer at: 83fb8000

Config XHCI 40M PLL 
******************************
Software System Reset Occurred
******************************
flash manufacture id: ef, device id 40 18
find flash: W25Q128BV
============================================ 
Ralink UBoot Version: 4.2.1.0
Buffalo UBoot Version: 1.03
-------------------------------------------- 
ASIC 7621_MP (MAC to MT7530 Mode)
DRAM_CONF_FROM: Auto-Detection 
DRAM_TYPE: DDR2 
DRAM bus: 16 bit
Xtal Mode=3 OCP Ratio=1/4
Flash component: 16 MBytes NOR Flash
Date:Aug 14 2014  Time:22:05:54
============================================ 
icache: sets:256, ways:4, linesz:32 ,total:32768
dcache: sets:256, ways:4, linesz:32 ,total:32768 

 ##### The CPU freq = 880 MHZ #### 
 estimate memory size =64 Mbytes
#Reset_MT7530
set LAN/WAN LLLLW
aossgpio=[262144]

Please choose the operation: 
   1: Load system code to SDRAM via TFTP. 
   2: Load system code then write to Flash via TFTP. 
   3: Boot system code via Flash (default).
   4: Entr boot command line interface.
   7: Load Boot Loader code then write to Flash via Serial. 
   9: Load Boot Loader code then write to Flash via TFTP. 
 0 
   
3: System Boot system code via Flash.

=================================================
Check image validation:
Image1 Header Magic Number --> OK
Image2 Header Magic Number --> OK
Image1 Header Checksum --> OK
Image2 Header Checksum --> OK
Image1 Data Checksum --> OK
Image2 Data Checksum --> OK

Image1: OK Image2: OK
Check if Image1 and Image2's Checksum are the same:
Two Images are the same

=================================================
Erasing SPI Flash...
.
Writing to SPI Flash...
.
done
## Booting image at bfc50000 ...
   Image Name:   MIPS OpenWrt Linux-5.10.161
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    2713586 Bytes =  2.6 MB
   Load Address: 80001000
   Entry Point:  80001000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... LZMA ERROR 1 - must RESET board to recover
```

### OpenWrt version

22.03

### OpenWrt target/subtarget

ramips/mt7621

### Device

WSR-600DHP

### Image kind

Official downloaded image

### Steps to reproduce

flash 22.03

### Actual behaviour

not boot

### Expected behaviour

boot

### Additional info

_No response_

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by Lorilandly**
Fixes: #11919

Need to be back-ported to earlier versions of 22.03

### CODE REVIEW

**Comment by hauke** [comment]
Please follow the OpenWrt Submission Guidelines, see https://openwrt.org/submitting-patches#submission_guidelines

The Signed-off-by line is missing for example.

**Comment by Ansuel** [comment]
@Lorilandly thanks a lot for the patch...

please fix the commit title to something like ramips: fix bootloop for Buffalo WSR 600HP by using LZMA loader

and use the format `Fixes: #11919` for fixes tag

**Comment by Lorilandly** [comment]
> Also no new line between sob and fixes

I'm curious what does sob stand for

**Comment by Ansuel** [comment]
Signed off by

Il Mar 18 Apr 2023, 07:35 Haoan Li ***@***.***> ha scritto:

**Comment by Lorilandly** [comment]
Apologies for repeated pushes

I'm still learning git and the process

**Pull request merged**
