### PR TITLE
Update sysctl.conf

### PR DESCRIPTION
**Pull request by AlexLaroche**
Base on sysctl.conf tested on the follow system below and i use in my production stage :
- Ubuntu 14.04 LTS kernel version 3.13
- Debian 7 kernel version 3.2
- CentOS 7 kernel version 3.10

Try to improve security of OpenWrt.

### CODE REVIEW

**Comment by lperkov** [comment]
We should not hard code this in such way. Can we make this either configurable in make menuconfig or somehow be able to easily import a file from remote repo and/or local filesystem?

**Comment by AlexLaroche** [comment]
It's not hard code in the kernel.

It's a configuration file that can be editable at anytime when a image is install (vi /etc/sysctl.config on a running system) or before at compilation.

I just suggest that we harden the default configuration by default as the common Linux distribution (Ubuntu, Debian, Centos) have already be done.

**Comment by lperkov** [comment]
Right, but it would be good that this file is can be configured with prefered set of options before compilation. That way your image that you flash already has the correct options. Otherwise we just endup with "I use this settings lets just mainline those".

**Comment by lperkov** [comment]
Changes are needed. Closing this pull request.

**Pull request closed without merging**
