### PR TITLE
generic: better support RealTek 2.5G PHYs

### PR DESCRIPTION
**Pull request by dangowrt**
The RealTek RTL8221 and RTL8226 2.5G Ethernet PHYs have various issues with the current phy driver.
1. Instead of using rate-adaptation we should switch the MAC interface mode and follow the link speed of the twisted pair interface.
2. Vendor bootloaders tend to program the PHY to report weird interface modes, as observed on the Netgear WAX206. Reset the PHY using `genphy_soft_reset` to start of a clean sheet.
3. The PHY is expecting Cisco-style SGMII auto-negotiation by default while Linux MAC drivers use out-of-band status unless `managed = "in-band-status";` is specified in device tree. Use magic sequence to switch off in-band auto-negotiation of the PHY so SGMII link comes up and the MAC tracks the PHYs link speed as commonly done in Linux.

https://forum.openwrt.org/t/netgear-wax206-issue-wan-last-snapshot-r22459/156195

https://github.com/openwrt/openwrt/pull/12202#pullrequestreview-1347413996

@ptpt52  @aiamadeus

### CODE REVIEW

**Comment by ptpt52** [comment]
@dangowrt 
great thanks.
This pull request is functioning well for my board with the RTL8221 PHY connected to the SoC MDIO bus. However, there is still an issue when the PHY is connected to the GPIO-MDIO bus, where a poll timeout error occurs in rtl8221b_config_init or phy_poll_reset. It seems that the PHY is never ready, although it works with the MTK SDK source (based on kernel 5.4).

**Comment by ptpt52** [comment]
poll timeout log with the phy connected to gpio-mdio bus:
```
[    9.127305] mt7530 gpio-0:1f: no interrupt support
[    9.361916] mt7530 gpio-0:1f: configuring for fixed/2500base-x link mode
[    9.410911] mt7530 gpio-0:1f: Link is Up - 2.5Gbps/Full - flow control rx/tx
[    9.610857] mt7530 gpio-0:1f lan5 (uninitialized): PHY [mt7530-1:00] driver [MediaTek MT7531 PHY] (irq=POLL)
[    9.830922] mt7530 gpio-0:1f lan6 (uninitialized): PHY [mt7530-1:01] driver [MediaTek MT7531 PHY] (irq=POLL)
[   10.047138] mt7530 gpio-0:1f lan7 (uninitialized): PHY [mt7530-1:02] driver [MediaTek MT7531 PHY] (irq=POLL)
[   10.263330] mt7530 gpio-0:1f lan8 (uninitialized): PHY [mt7530-1:03] driver [MediaTek MT7531 PHY] (irq=POLL)
[   10.479541] mt7530 gpio-0:1f gsw2_p4 (uninitialized): PHY [mt7530-1:04] driver [MediaTek MT7531 PHY] (irq=POLL)
[   11.134420] RTL8221B-VB-CG 2.5Gbps PHY gpio-0:07: phy_poll_reset failed: -110
[   11.143540] mt7530 gpio-0:1f wan2 (uninitialized): failed to connect to PHY: -ETIMEDOUT
[   11.151542] mt7530 gpio-0:1f wan2 (uninitialized): error -110 setting up PHY for tree 1, switch 0, port 5
[   11.195374] DSA: tree 1 setup
[   11.264018] IPsec XFRM device driver
```

**Comment by ptpt52** [comment]
> > `irq=POLL`
> 
> I assume that all 4 built-in PHYs polling on a bit-banged MDIO bus maybe a bit too much for the `phy_read_mmd_poll_timeout` in `725-net-phy-realtek-disable-SGMII-in-band-AN-for-2-5G-PHYs.patch`... Try increasing the wait value from 500 to 10000 and see if that helps.


sure. I did that but no help:
```
[    9.289058] Backport generated by backports.git v5.15.81-1-41-g02e352527db5
[   10.277159] mt7530 gpio-0:1f: no interrupt support
[   10.511826] mt7530 gpio-0:1f: configuring for fixed/2500base-x link mode
[   10.560815] mt7530 gpio-0:1f: Link is Up - 2.5Gbps/Full - flow control rx/tx
[   10.760774] mt7530 gpio-0:1f lan5 (uninitialized): PHY [mt7530-1:00] driver [MediaTek MT7531 PHY] (irq=POLL)
[   10.980879] mt7530 gpio-0:1f lan6 (uninitialized): PHY [mt7530-1:01] driver [MediaTek MT7531 PHY] (irq=POLL)
[   11.197127] mt7530 gpio-0:1f lan7 (uninitialized): PHY [mt7530-1:02] driver [MediaTek MT7531 PHY] (irq=POLL)
[   11.413338] mt7530 gpio-0:1f lan8 (uninitialized): PHY [mt7530-1:03] driver [MediaTek MT7531 PHY] (irq=POLL)
[   11.629564] mt7530 gpio-0:1f gsw2_p4 (uninitialized): PHY [mt7530-1:04] driver [MediaTek MT7531 PHY] (irq=POLL)
[   17.786686] RTL8221B-VB-CG 2.5Gbps PHY gpio-0:07: phy_poll_reset failed: -110
[   17.795792] mt7530 gpio-0:1f wan2 (uninitialized): failed to connect to PHY: -ETIMEDOUT
[   17.803785] mt7530 gpio-0:1f wan2 (uninitialized): error -110 setting up PHY for tree 1, switch 0, port 5
[   17.845209] DSA: tree 1 setup
```

```diff
diff --git a/drivers/net/phy/phy_device.c b/drivers/net/phy/phy_device.c
index 7692cef..0822827 100644
--- a/drivers/net/phy/phy_device.c
+++ b/drivers/net/phy/phy_device.c
@@ -1176,7 +1176,7 @@ static int phy_poll_reset(struct phy_device *phydev)
        int ret, val;
 
        ret = phy_read_poll_timeout(phydev, MII_BMCR, val, !(val & BMCR_RESET),
-                                   50000, 600000, true);
+                                   500000, 6000000, true);
        if (ret)
                return ret;
        /* Some chips (smsc911x) may still need up to another 1ms after the
diff --git a/drivers/net/phy/realtek.c b/drivers/net/phy/realtek.c
index 308c2d3..0359e15 100644
--- a/drivers/net/phy/realtek.c
+++ b/drivers/net/phy/realtek.c
@@ -912,7 +912,7 @@ static int rtl8221b_config_init(struct phy_device *phydev)
        phy_write_mmd(phydev, RTL8221B_MMD_SERDES_CTRL, 0x7589, 0x71d0);
        phy_write_mmd(phydev, RTL8221B_MMD_SERDES_CTRL, 0x7587, 0x3);
        phy_read_mmd_poll_timeout(phydev, RTL8221B_MMD_SERDES_CTRL, 0x7587, val,
-                                 !(val & BIT(0)), 500, 100000, false);
+                                 !(val & BIT(0)), 500000, 6000000, false);
 
        return 0;
 }
```

**Comment by boretom** [comment]
Just wanted to report that this PR works well with my WAX206 on a QNAP QSW-M1204-4C and a MikroTek CSS610-8G-2S+IN switch
Since it's merged already I'll use OpenWrt master

**Comment by dangowrt** [comment]
> QNAP QSW-M1204-4C and a MikroTek CSS610-8G-2S+IN switch

So I understand correctly that you tested both with, 2500Base-T and 1000Base-T link partners and both work fine?

**Comment by boretom** [comment]
> So I understand correctly that you tested both with, 2500Base-T and 1000Base-T link partners and both work fine?

Yes, I apologise for not being more precise:

- On the QNAP QSW-M1204-4C I successfully set the following port configurations in the switch GUI:
   - Port 10 (10GbE RJ45) set Auto-Neg
   - Port 10 set to 2.5G
   - Port 10 set to 1G
 
- On the MikroTik CSS610-8G-2S+IN I successfully tested:
    - Connected to a regular 1G port set to Auto-Neg
    - Connected to a MikroTik S+RJ10 10GbE SFP+ module in one of the two SFP+ ports, again Auto-Neg

**Comment by ptpt52** [comment]
>Well, try removing genphy_soft_reset again for that PHY, ie. drop https://github.com/openwrt/openwrt/commit/7e3284eef7f6d2bf270941fc0a94c95307db1ca5. That won't be a good solution as we should reset the PHY when Linux comes up so we don't end up with weird settings the bootloader may have left behind... But trying this will show somewhat where about the problem is.

@dangowrt 

dropping that commit no help. it would poll timeout in rtl8221b_config_init. and even I drop the `phy_read_mmd_poll_timeout ` line in rtl8221b_config_init()
the 2.5G phy do not function

```
[    9.717328] mt7530 gpio-0:1f: no interrupt support
[    9.951926] mt7530 gpio-0:1f: configuring for fixed/2500base-x link mode
[   10.000936] mt7530 gpio-0:1f: Link is Up - 2.5Gbps/Full - flow control rx/tx
[   10.200933] mt7530 gpio-0:1f lan5 (uninitialized): PHY [mt7530-1:00] driver [MediaTek MT7531 PHY] (irq=POLL)
[   10.421046] mt7530 gpio-0:1f lan6 (uninitialized): PHY [mt7530-1:01] driver [MediaTek MT7531 PHY] (irq=POLL)
[   10.637310] mt7530 gpio-0:1f lan7 (uninitialized): PHY [mt7530-1:02] driver [MediaTek MT7531 PHY] (irq=POLL)
[   10.853509] mt7530 gpio-0:1f lan8 (uninitialized): PHY [mt7530-1:03] driver [MediaTek MT7531 PHY] (irq=POLL)
[   11.069781] mt7530 gpio-0:1f gsw2_p4 (uninitialized): PHY [mt7530-1:04] driver [MediaTek MT7531 PHY] (irq=POLL)
[   11.743535] RTL8221B-VB-CG 2.5Gbps PHY gpio-0:07: rtl8221b_config_init failed: -110
[   11.785269] mt7530 gpio-0:1f wan2 (uninitialized): PHY [gpio-0:07] driver [RTL8221B-VB-CG 2.5Gbps PHY] (irq=POLL)
[   11.796043] DSA: tree 1 setup
```

**Comment by dangowrt** [comment]
@aiamadeus If the problem you describe occurs, does the link come up at all? Ie. does the PHY establish a link in 1000M/100M/10M if interface mode is initially set to 2500Base-X? Or does the link not even come up (which would hint to a problem with auto-negotiation bits)?

I should have the TP-LINK XDR6068 hardware in a couple of days and then test myself.

**Comment by aiamadeus** [comment]
First negotiated to 1G:
```
root@OpenWrt:/# ethtool eth1
Settings for eth1:
        Supported ports: [ TP MII ]
        Supported link modes:   10baseT/Half 10baseT/Full 
                                100baseT/Half 100baseT/Full 
                                1000baseT/Full 
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  Not reported
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Link partner advertised link modes:  10baseT/Half 10baseT/Full 
                                             100baseT/Half 100baseT/Full 
                                             1000baseT/Full 
                                             2500baseT/Full 
        Link partner advertised pause frame use: Symmetric Receive-only
        Link partner advertised auto-negotiation: Yes
        Link partner advertised FEC modes: Not reported
        Speed: 1000Mb/s
        Duplex: Unknown! (255)
        Port: Twisted Pair
        PHYAD: 7
        Transceiver: external
        Auto-negotiation: on
        MDI-X: Unknown
        Current message level: 0x000000ff (255)
                               drv probe link timer ifdown ifup rx_err tx_err
        Link detected: yes
```
First negotiated to 2.5G:
```
root@OpenWrt:/# ethtool eth1
Settings for eth1:
        Supported ports: [ TP MII ]
        Supported link modes:   2500baseT/Full 
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  2500baseT/Full 
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Link partner advertised link modes:  10baseT/Half 10baseT/Full 
                                             100baseT/Half 100baseT/Full 
                                             1000baseT/Full 
                                             2500baseT/Full 
        Link partner advertised pause frame use: Symmetric Receive-only
        Link partner advertised auto-negotiation: Yes
        Link partner advertised FEC modes: Not reported
        Speed: 2500Mb/s
        Duplex: Full
        Port: Twisted Pair
        PHYAD: 7
        Transceiver: external
        Auto-negotiation: on
        MDI-X: Unknown
        Current message level: 0x000000ff (255)
                               drv probe link timer ifdown ifup rx_err tx_err
        Link detected: yes
```
Use `service network restart` can make it work, but the maximum speed is 1G.

**Comment by dangowrt** [comment]
@aiamadeus Thank you for testing.
Did I understand correctly that under some conditions all possible link modes (2500M/1000M/100M/10M) now work?
Apparently there are still some problems with the `read_status()` function which needs improving, or maybe autoneg announced rates are not being programmed to the PHY correctly which lead to missing 2500Base-T? To analyse this, it'd be interesting to see ethtool output of the link partner in both cases as well.
I'm suspecting that this is probably the underlying cause for `Duplex: Unknown! (255)` and also lack of SerDes interface mode switch (Cisco SGMII <-> 2500Base-X).
Monitoring `/sys/bus/mdio/mdio_bus/devices/mdio-bus:07/phy_interface` may give a hint if interface mode switching actually happens.

**Comment by aiamadeus** [comment]
> Did I understand correctly that under some conditions all possible link modes (2500M/1000M/100M/10M) now work?

No, either SGMII or 2500Base-X, depending on the rate of the first link after boot.
If first negotiated to 2.5G, use `service network restart` can make it work on 1G (sgmii only).

**Comment by dangowrt** [comment]
> No, either SGMII or 2500Base-X, depending on the rate of the first link after boot.

Can you check if from the perspective of the link-partner you still see 2500Base-T being announced in auto-negotiation by the TL-XDR6068 after you did `service network restart` and only 1G link works?
If so, will the link appear to come up if you force 2500M speed using ethtool on the other side?

**Comment by v4lkyr** [comment]
I have a router with the same 2.5G chip and it's not working in latest openwrt build.

**Pull request merged**
