### PR TITLE
kernel: Mark rtcache implementation as hack

### PR DESCRIPTION
**Pull request by ecsv**
This kernel module was never accepted as upstream. Instead it is currently only maintained as a hack in OpenWrt. This module causes various crashes and warnings. And since there is no one in Linux upstream dealing with it, the patch should not be handled like a backport.

----

Please check https://patchwork.ozlabs.org/project/netfilter-devel/list/?series=&submitter=&state=*&q=netfilter%3A+conntrack%3A+cache+route+for+forwarded+connections&archive=both&delegate= regarding the upstreaming status

Regarding the claim that this is just a hack which causes various problems:

There were various reports related to this. Today I got following from Datto:

    WARNING: CPU: 4 PID: 26517 at net/netfilter/nf_conntrack_rtcache.c:199 0xffffffffa05ec38d()
    Modules linked in: cdc_ether pppoe ppp_async option iptable_nat ath9k usb_wwan qmi_wwan pppox ppp_generic nft_chain_nat_ipv4 nf_tables_inet nf_nat_pptp nf_nat_ipv6 nf_nat_ipv4 nf_nat_amanda nf_conntrack_pptp nf_conntrack_ipv6 nf_conntrack_ipv4 nf_conntrack_amanda ipt_REJECT ipt_MASQUERADE cdc_ncm ath9k_common xt_time xt_tcpudp xt_tcpmss xt_string xt_statistic xt_state xt_recent xt_quota xt_policy xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xWed May 1 19:48:46 2019 kern.warn kernel: [133596.567091] CPU: 4 PID: 26517 Comm: snort Tainted: P W 4.4.92 #0
    Hardware name: To be filled by O.E.M. To be filled by O.E.M./To be filled by O.E.M., BIOS 5.6.5 04/06/2016
    0000000000000000 ffffffff81208612 0000000000000000 ffffffffa05ec540
    ffffffff81071bf3 ffff88006d337a00 0000000000000002 ffff880230ef0800
    ffffffff8171a758 0000000000000000 ffffffffa05ec38d ffff88006b733a70
    Call Trace:
    [<ffffffff81208612>] ? dump_stack+0x5c/0x7a
    [<ffffffff81071bf3>] ? warn_slowpath_common+0x73/0xa0
    [<ffffffffa05ec38d>] ? 0xffffffffa05ec38d
    [<ffffffff8142fb74>] ? nf_iterate+0x54/0x60
    [<ffffffff81430b9b>] ? nf_reinject+0xfb/0x140
    [<ffffffffa0661a2e>] ? 0xffffffffa0661a2e
    [<ffffffff81224fad>] ? nla_parse+0x8d/0xe0
    [<ffffffffa023a334>] ? nfnetlink_unicast+0x1b4/0x87d [nfnetlink]
    [<ffffffffa023a200>] ? nfnetlink_unicast+0x80/0x87d [nfnetlink]
    [<ffffffff8142d7a3>] ? netlink_rcv_skb+0x73/0x90
    [<ffffffffa023a7a0>] ? nfnetlink_unicast+0x620/0x87d [nfnetlink]
    [<ffffffff81114487>] ? __kmalloc_track_caller+0x17/0xd0
    [<ffffffff8142d142>] ? netlink_unicast+0x132/0x1e0
    [<ffffffff8142d55b>] ? netlink_sendmsg+0x2ab/0x350
    [<ffffffff813ecb6a>] ? ___sys_sendmsg+0x22a/0x240
    [<ffffffff8109dd7f>] ? __wake_up+0x2f/0x50
    [<ffffffff8142b7fe>] ? netlink_recvmsg+0x21e/0x350
    [<ffffffff813ed9a9>] ? __sys_sendmsg+0x39/0x70
    [<ffffffff814f02ae>] ? entry_SYSCALL_64_fastpath+0x12/0x71
    ---[ end trace f28b59438a48034c ]---

But I also saw actual crashes in `ip_rcv_finish` when `skb_dst->input` is `NULL` when a device switches the bridge. 

    CPU 0 Unable to handle kernel paging request at virtual address 00000000, epc == 00000000, ra == 800a1d80
    Oops[#1]:
    CPU: 0 PID: 908 Comm: srvd Tainted: P               3.18.8 #1
    task: 87829838 ti: 8576e000 task.ti: 8576e000
    $ 0   : 00000000 00000001 86b53830 fffffffe
    $ 4   : 8653e540 86b53831 00000001 00000000
    $ 8   : f67191ad 80064f28 00000015 0015002a
    $12   : 00000003 00000000 00000000 00000000
    $16   : 80348588 80347134 8653e540 86b53000
    $20   : 00000000 00000800 80347148 80347140
    $24   : 00000000 00000000                  
    $28   : 8576e000 8576fa88 00000000 800a1d80
    Hi    : 0000068d
    Lo    : b37de000
    epc   : 00000000   (null)
        Tainted: P              
    ra    : 800a1d80 __netif_receive_skb_core+0x630/0x6b0
    Status: 1100fc03 KERNEL EXL IE 
    Cause : 00800008
    BadVA : 00000000
    PrId  : 00019750 (MIPS 74Kc)
    Modules linked in: iptable_nat ath9k nf_nat_pptp nf_nat_ipv4 nf_nat_amanda nf_conntrack_pptp nf_conntrack_ipv6 nf_conntrack_ipv4 nf_conntrack_amanda ipt_REJECT ipt_MASQUERADE ath9k_common xt_time xt_tcpudp xt_tcpmss xt_string xt_statistic xt_state xt_recent xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_id xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_NETMAP xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY ts_kmp ts_fsm ts_bm nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_proto_gre nf_nat_masquerade_ipv4 nf_nat_irc nf_nat_h323 nf_nat_ftp nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_rtcache nf_conntrack_proto_gre nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt ath9k_hw sch_tbf sch_sfq sch_red sch_prio sch_netem sch_htb sch_gred sch_dsmark sch_codel em_text em_nbyte em_meta em_cmp cls_basic act_police act_ipt act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_hfsc sch_ingress tmp421 hwmon batman_adv libcrc32c crc16 ath10k_pci ath10k_core ath mac80211 cfg80211 compat i2c_dev tc_classid_mapper(P) filter_group classifier_dns(P) classifier_netblock(P) classifier_bittorrent(P) classifier_rtmp(P) classifier_ssl(P) classifier_content(P) classifier_quic(P) classifier_skype(P) kernel_classifier nf_conntrack xt_set ip_set_list_set ip_set_hash_netport ip_set_hash_netiface ip_set_hash_net ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6table_filter ip6_tables x_tables ifb tun ipv6 arc4 crypto_blkcipher input_polldev gpio_button_hotplug button_hotplug input_core ag71xx crc32c_generic crypto_hash
    Process srvd (pid: 908, threadinfo=8576e000, task=87829838, tls=775f0440)
    Stack : 80340000 80347140 800e4860 800e4ed0 80347148 80000000 803479a4 8653e540
              8653e540 86bf5042 86bf5042 8567ca00 8576fb50 8035abf0 80340000 80347140
              800e4860 800e4acc 8653e540 87a49800 00000000 86dc60cc 00000000 800e4b48
              80000000 87a49800 00000000 8653e540 00000000 87a49800 00000000 800a1c0c
              00000000 00000800 8576fb48 86a5d820 80347140 86bf5000 00000800 800f12f0
              ...
    Call Trace:
    [<800e4860>] br_handle_frame+0x0/0x2e8
    [<800e4ed0>] br_handle_frame_finish+0x388/0x418
    [<800e4860>] br_handle_frame+0x0/0x2e8
    [<800e4acc>] br_handle_frame+0x26c/0x2e8
    [<86dc60cc>] 0x86dc60cc
    [<800e4b48>] br_handle_frame_finish+0x0/0x418
    [<800a1c0c>] __netif_receive_skb_core+0x4bc/0x6b0
    [<800f12f0>] build_skb+0x44/0xd4
    [<87a10954>] 0x87a10954
    [<801d5ecc>] net_rx_action+0x10c/0x1dc
    [<80165628>] handle_irq_event_percpu+0x154/0x188
    [<8008fc44>] __do_softirq+0xf8/0x230
    [<801664d8>] handle_percpu_irq+0x54/0x84
    [<80190e20>] irq_exit+0x54/0x70
    [<80060830>] ret_from_irq+0x0/0x4
    [<801e4b30>] ovl_dentry_open+0xd8/0x124
    [<802ac77c>] unlink_anon_vmas+0xe8/0x1c0
    [<801ab05c>] kmem_cache_free+0x74/0x13c
    [<801540f8>] free_pgtables+0x84/0xf4
    [<8013fc34>] exit_mmap+0x84/0x16c
    [<801c21d8>] mmput+0x3c/0xd4
    [<8014e944>] flush_old_exec+0x420/0x548
    [<801b4018>] load_elf_binary+0x31c/0x1238
    [<800912c4>] __flush_anon_page+0x70/0xa0
    [<80093c40>] __get_user_pages.part.29+0x328/0x374
    [<8021f794>] r4k_flush_data_cache_page+0x0/0x48
    [<8023c40c>] search_binary_handler+0x88/0x1c8
    [<801233dc>] do_execve+0x32c/0x4c0
    [<80062b5c>] handle_sys+0x11c/0x140
    
    
    Code: (Bad address in epc)
    
    ---[ end trace e24d5bbbcdb5a6b5 ]---
    Kernel panic - not syncing: Fatal exception in interrupt
    Rebooting in 3 seconds..

This was solved by removing this file at all. A similar problem was also reported in the past to batman-adv + OpenWrt and it was solved the same way (dropping of this patch): https://dev.archive.openwrt.org/ticket/22283

    CPU 0 Unable to handle kernel paging request at virtual address 00000000, epc == 00000000, ra == 8018c50c
    Oops[#1]:
    CPU: 0 PID: 1072 Comm: sysctl Tainted: P               3.18.8 #1
    task: 879c3548 ti: 86bbc000 task.ti: 86bbc000
    $ 0   : 00000000 00000001 00000000 fffffffe
    $ 4   : 86a30480 86b3b831 00000001 00000000
    $ 8   : c7eb9975 80064f28 86a30540 00000000
    $12   : 00000000 00000000 00000000 00000000
    $16   : 86a30480 867fc050 80359178 86b3b000
    $20   : 00000000 00000800 8034d148 8034d140
    $24   : 00000000 76eb7d20
    $28   : 86bbc000 86bbdc10 00000000 8018c50c
    Hi    : 0000040b
    Lo    : a3656800
    epc   : 00000000   (null)
        Tainted: P
    ra    : 8018c50c ip_rcv_finish+0x348/0x3b8
    Status: 1100fc03 KERNEL EXL IE
    Cause : 00800008
    BadVA : 00000000
    PrId  : 00019750 (MIPS 74Kc)
    [...]
    Stack : 8034d864 80000000 86a30480 867fc050 80359178 86b3b000 86a30480 867fc050
            80359178 86b3b000 00000000 8018c118 8008896c 800e598c 86a30780 8008896c
            00000000 8018c1c4 80000000 86b3b000 00000000 8034e588 8034d134 86a30480
            86b3b000 800a26d0 86bbdce0 801e0b8c 87a5c000 800e595c 8034d148 86b3b000
            801dbb6c 80113038 86a30480 86a30480 86b3b420 867fc042 867e0200 80360bf0
            ...
    Call Trace:
    [<8018c118>] ip_rcv+0x3b4/0x460
    [<8008896c>] __br_forward+0x0/0xdc
    [<800e598c>] br_forward_finish+0x30/0x7c
    [<8008896c>] __br_forward+0x0/0xdc
    [<8018c1c4>] ip_rcv_finish+0x0/0x3b8
    [<800a26d0>] __netif_receive_skb_core+0x630/0x6b0
    [<801e0b8c>] nf_iterate+0x88/0xe0
    [<800e595c>] br_forward_finish+0x0/0x7c
    [<801dbb6c>] netif_receive_skb+0x0/0x1c
    [<80113038>] deliver_clone+0x50/0x6c
    [<800e5b90>] br_handle_frame+0x0/0x2e8
    [<800a2048>] __netif_receive_skb+0x28/0x80
    [<801247a4>] do_dentry_open.isra.15+0x54/0x334
    [<801dbbe8>] netif_receive_skb_internal+0x60/0x70
    [<801dbb6c>] netif_receive_skb+0x0/0x1c
    [<801dbb7c>] netif_receive_skb+0x10/0x1c
    [<800e5b90>] br_handle_frame+0x0/0x2e8
    [<800e61c0>] br_handle_frame_finish+0x348/0x404
    [<800e5e78>] br_handle_frame_finish+0x0/0x404
    [<801dbb6c>] netif_receive_skb+0x0/0x1c
    [<800e5dfc>] br_handle_frame+0x26c/0x2e8
    [<8684d0e0>] 0x8684d0e0
    [<800e5e78>] br_handle_frame_finish+0x0/0x404
    [<800a255c>] __netif_receive_skb_core+0x4bc/0x6b0
    [<801f0de0>] pagecache_get_page+0x5c/0x244
    [<800a2048>] __netif_receive_skb+0x28/0x80
    [<801adb28>] kmem_cache_alloc+0x3c/0xec
    [<801f5428>] path_openat+0x218/0x57c
    [<801dbbe8>] netif_receive_skb_internal+0x60/0x70
    [<800f25dc>] build_skb+0x44/0xd4
    [<801dbb7c>] netif_receive_skb+0x10/0x1c
    [<879d0954>] 0x879d0954
    [<801d9904>] net_rx_action+0x10c/0x1dc
    [<80090460>] __do_softirq+0xf8/0x230
    [<801939b8>] irq_exit+0x54/0x78
    [<80122174>] do_IRQ+0x24/0x34
    [<80074ad4>] SyS_ioctl+0x50/0x94
    [<8020c148>] plat_irq_dispatch+0x4c/0x9c
    [<80060830>] ret_from_irq+0x0/0x4

----

Btw. there is a similar crash problem in the past (not tested with 18.06 or newer) with target/linux/generic/pending-*/150-bridge_allow_receiption_on_disabled_port.patch which I found while searching for the stacktraces from rtcache:

* https://dev.archive.openwrt.org/ticket/22265
* https://www.spinics.net/lists/netfilter-devel/msg40962.html
* https://www.spinics.net/lists/netfilter-devel/msg40997.html

### CODE REVIEW

**Comment by ynezz** [comment]
From my POV it looks like it should be removed and not just moved around.

**Comment by ecsv** [comment]
@ynezz This is at least what I try to do in all projects which use OpenWrt. I just wanted to leave someone in OpenWrt to pick up the patch. At least @nbd168 stated in his commit that:

    commit 27f36718d31026fadbf2b627eed2d261e98493f6
    Author: Felix Fietkau <nbd@openwrt.org>
    Date:   Tue Dec 9 11:01:49 2014 +0000
    
        kernel: add a patch to make netfilter conntrack cache routing information
        
        Significantly improves routing / NAT performance
        
        Signed-off-by: Felix Fietkau <nbd@openwrt.org>
        
        SVN-Revision: 43587

And at least for the other change (150-bridge_allow_receiption_on_disabled_port.patch) it seems to be a requirement for the WDS support. So you have not only decide between crashes and performance - no, now you also have to decide between crashes and functionality.

When it is just about stability - yes, both should be dropped.

**Comment by ynezz** [comment]
By looking closely at your crash reports, it's coming from some old kernels, makes me wonder if it's still issue with 4.14/4.19 kernels as I can't find any similar bug report on bugs.openwrt.org, but maybe I'm just trying wrong search phrase.

**Comment by kristrev** [comment]
The rtcache-module works fine for me (on kernel 4.14+) and does, as @nbd168 wrote in his commit message, provide a nice speed-up. There are two issues though, I have fixed them up locally but never got around to submitting a patch:

* rmmod fails due to some missing clean-up code.
* restarting the firewall with certain routing configurations causes a DDOS.

I will try to find time to clean up my local patch and submit it.

**Comment by ynezz** [comment]
> I will try to find time to clean up my local patch and submit it.

Sound great, and I really hope (and all my fingers are crossed), that by `submit it` you actually mean to submit it upstream.

**Comment by kristrev** [comment]
> Sound great, and I really hope (and all my fingers are crossed), that by `submit it` you actually mean to submit it upstream.

I would have liked to make an attempt at upstream, but the rtcache-patch will most likely never be accepted. I see that the discussions around the original patch died out around 2014. Upstream seems to be very much against most attempts at caching (with good reason), since caching is an excellent DDOS-vector. See for example the removal of the ipv4 routing cache, ipsec xfrm cache, etc.

However, I still believe the patch is worth carrying in OpenWRT, as it does provide a nice performance gain on not so powerful devices.

**Comment by ynezz** [comment]
> However, I still believe the patch is worth carrying in OpenWRT, as it does provide a nice performance gain on not so powerful devices.
 
I agree with you, but to the point where it doesn't introduce any problems. If it's causing stability issues, then it should be either fixed, made clearly experimental/optional (opt-in via some config option?) or simply removed.

**Comment by kristrev** [comment]
> I agree with you, but to the point where it doesn't introduce any problems. If it's causing stability issues, then it should be either fixed, made clearly experimental/optional (opt-in via some config option?) or simply removed.

That we fully agree on :) With the exception of the two issues I mentioned above (and my routing configuration is a bit strange), I have had no issues with the patch and not seen anyone report issues recently.

**Comment by ecsv** [comment]
I currently cannot reproduce the crashes with OpenWrt master. But I am waiting for Datto to provide some feedback.

**Comment by AlbanBedel** [comment]
Crash or not this open the door for DoS attack on the router and should not be enabled per default on platforms where it is not absolutely necessary to get acceptable performances. Furthermore the option documentation should clearly state the security implication.

I understand that for home users such a performance before security trade off might be acceptable, but there is also many users that use OpenWrt in untrusted networks where such hacks have no place.

**Comment by ynezz** [comment]
> Crash or not this open the door for DoS attack on the router and should not be enabled per default on platforms where it is not absolutely necessary to get acceptable performances. Furthermore the option documentation should clearly state the security implication.

@AlbanBedel I agree, feel free to propose this in a patch.

**Comment by adrianschmutzler** [comment]
@ecsv @kristrev @AlbanBedel What's the status here? Discussion stopped five months ago...

**Comment by ecsv** [comment]
I didn't hear back from datto and I am also waiting for further actions

**Comment by adrianschmutzler** [comment]
@ecsv Since last state was "working" and there has been no feedback for a month, I consider closing this one?

**Comment by ecsv** [comment]
It is still not an upstream patch and should therefore not be part of the backports directory

**Comment by adrianschmutzler** [comment]
Hi, since this is a cosmetic patch after all, and none of the committer have been interested in merging it, I close this now.

I'm sorry, but better do this now than waiting another year where supposedly nothing different will happen.

Feel encouraged to propose other patches as suggested during the discussion.

**Comment by AlbanBedel** [comment]
The fact that rtcache is a security hole and can't be disabled is still not addressed. I'm also asking myself if the dog slow devices it was written for are still supported.

**Comment by adrianschmutzler** [comment]
> The fact that rtcache is a security hole and can't be disabled is still not addressed. I'm also asking myself if the dog slow devices it was written for are still supported.

However, this hasn't been the aim of this PR. If you want to fix or remove it, feel free to propose that in a new PR.

**Comment by atiensivu** [comment]
If you need more proof:

I was researching this module to see what it does, decided I didn't want it, and attempted to 'rmmod' it.
It is supposed to wait until the connections die, but instead, it dies. 
It may still be useful as optional but defaulted to no.

And I don't normally rmmod modules, but it should clean itself up properly. Maybe not SMP safe.

```
[14651.857170] ------------[ cut here ]------------
[14651.866681] WARNING: CPU: 0 PID: 13349 at net/netfilter/nf_conntrack_rtcache.c:414 cleanup_module+0x1cc/0x228 [nf_conntrack_rtcache]
[14651.891245] Waiting for all rtcache conntracks to go away
[14651.902131] Modules linked in: hwmon xt_connlimit pppoe ppp_async nf_conncount iptable_nat xt_state xt_nat xt_helper xt_conntrack xt_connmark xt_connbytes xt_REDIRECT xt_MASQUERADE xt_FLOWOFFLOAD xt_CT pppox ppp_generic nf_nat nf_flow_table_hw nf_flow_table nf_conntrack_rtcache(-) nf_conntrack_netlink nf_conntrack mt7615e mt7615_common mt7603e mt76 mac80211 ipt_REJECT ebtable_nat ebtable_filter ebtable_broute cfg80211 xt_time xt_tcpudp xt_tcpmss xt_statistic xt_recent xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_ecn xt_dscp xt_comment xt_TCPMSS xt_LOG xt_HL xt_DSCP xt_CLASSIFY wireguard slhc sch_cake nlmon nfnetlink_queue nfnetlink_log nf_reject_ipv4 nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables ebtables ebt_vlan ebt_stp ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_among ebt_802_3 crc_ccitt compat sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_tcindex cls_route cls_matchall cls_fw cls_flow cls_basic
[14651.902400]  act_skbedit act_mirred dwc3 ohci_platform ohci_hcd ledtrig_usbport ledtrig_heartbeat xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 ahci libahci libata fsl_mph_dr_of ehci_platform ehci_fsl sd_mod scsi_mod ehci_hcd ifb ip6_udp_tunnel udp_tunnel netlink_diag leds_gpio xhci_plat_hcd xhci_pci xhci_mtk xhci_hcd gpio_button_hotplug usbcore nls_base usb_common
[14652.204915] CPU: 0 PID: 13349 Comm: rmmod Not tainted 5.4.48 #0
[14652.216705] Stack : fffffff0 80077324 806c0000 806bc3bc 80720000 806bc384 806bb4d8 86709d9c
[14652.233359]         80860000 874e4188 80706d83 80651380 00000000 00000001 86709d40 3db551c6
[14652.249998]         00000000 00000000 808a0000 00000000 00000030 0000015a 342e3520 2038342e
[14652.266610]         00000000 000002d8 00000000 00032073 80000000 80720000 00000000 862f267c
[14652.283223]         00000009 862f0000 00000001 807042b0 00000002 8033d914 00000000 80860000
[14652.299835]         ...
[14652.304685] Call Trace:
[14652.309565] [<8000b72c>] show_stack+0x30/0x100
[14652.318425] [<805945b4>] dump_stack+0xa4/0xdc
[14652.327100] [<80028058>] __warn+0xc0/0x10c
[14652.335238] [<80028130>] warn_slowpath_fmt+0x8c/0xac
[14652.345122] [<862f267c>] cleanup_module+0x1cc/0x228 [nf_conntrack_rtcache]
[14652.358794] [<800ae098>] sys_delete_module+0x15c/0x238
[14652.369014] [<80014578>] syscall_common+0x34/0x58
[14652.380848] ---[ end trace 653a03c35a50edc0 ]---

```

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r13611-3f27a6e640'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r13611-3f27a6e640'

**Pull request closed without merging**
