### PR TITLE
toolchain/binutils: Add binutils 2.32

### PR DESCRIPTION
**Pull request by diizzyy**
Add binutils 2.32 to repo

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile/Runtime tested: octeon, UBNT EdgeRouter Lite, OpenWrt master

**Comment by diizzyy** [comment]
@EvgeniiDidin 
What's the status with arc support upstream (binutils, gcc, glibc) can we switch to upstream and if so what version(s) or do we still need to stick to your forks?

**Comment by abrodkin** [comment]
@diizzyy Binutils 2.32 should have all most recent fixes (as opposed to 2.30 & 2.31) so I'm all for switching ARC on upstream Binutils - it makes life easier for all. Do I need to do something about it?

**Comment by diizzyy** [comment]
@abrodkin 
I can do a PR once this is in, can you do a run-test (compiles fine for me)?
https://github.com/diizzyy/openwrt/commit/fa3f071242d4d102f45454e38623bb99a840c2d8
https://github.com/diizzyy/openwrt/commit/fa3f071242d4d102f45454e38623bb99a840c2d8.patch

Also, can we remove 2.29 once this is in or do you think we should keep it?

**Comment by EvgeniiDidin** [comment]
@diizzyy @abrodkin
I have tested on HSDK(ARC HS38) an image, which was built with Binutils 2.32, it works fine.

**Comment by diizzyy** [comment]
@EvgeniiDidin 
Thanks! 

Do we want to keep 2.29 or can we remove it once 2.32 is in the tree?

**Comment by abrodkin** [comment]
@diizzyy Feel free to get rid of Binutils 2.29 as there's nothing special about it for ARC and new upstream version has quite a few critical fixes for ARC.

And thanks for doing that work!

Just FYI once GCC 8.3.0 gets released we may get rid of ARC GCC version as well.

**Comment by diizzyy** [comment]
@nbd168 
Ping

**Comment by diizzyy** [comment]
@hauke 
Can you haev a look at this?

**Comment by wongsyrone** [comment]
Compile and run tested on x86_64

**Comment by hingbong** [comment]
run nomally on r7800

**Comment by diizzyy** [comment]
Thanks for testing everyone!

**Comment by diizzyy** [comment]
Rebase

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
