### PR TITLE
ath79: fix GL-AR300M nand support 

### PR DESCRIPTION
**Pull request by mennozon**
This fixes a few things that makes nand flash work on ath79 GL-AR300M.

- Update dts to be able to detect flash chip
- Add ath79 patch to include chip id's for AR300M flash chip
- Enable UBI related kernel config options in ath79 nand profile

This is based on the original ar71xx and ath79's pull requests by @hanetzer, all credits go to people providing the information in those pull requests.

### CODE REVIEW

**Comment by hauke** [comment]
Please send a patch with the changes in 999-drivers-gl-inet-ar300m-nand-device-ids.patch to the upstream Linux kernel.

**Comment by hanetzer** [comment]
@hauke @mennozon I have the actual name for the FW Device nand chip, just gotta find that datasheet again. Gimme a bit (late for me here, so prolly 12ish hours or so) and I'll get ya that so it can be accurate.

**Comment by chunkeey** [comment]
@hauke 
>Please send a patch with the changes in 999-drivers-gl-inet-ar300m-nand-device-ids.patch to the upstream Linux kernel.

Not a good idea. John tried that with the "W25N01GV" already:

https://patchwork.ozlabs.org/patch/948498/

So unless the patch can sneak past the gatekeepers it's not going to happen.
(I checked the spinand http://git.infradead.org/linux-mtd.git/blob/refs/heads/nand/next:/drivers/mtd/nand/spi/ a while ago and tried to backport it to 4.14 for the ipq40xx. It is possible, but the SoC's spi drivers need to be updated too.)

**Comment by mennozon** [comment]
> @hauke @mennozon I have the actual name for the FW Device nand chip, just gotta find that datasheet again. Gimme a bit (late for me here, so prolly 12ish hours or so) and I'll get ya that so it can be accurate.

Thanks, isn't the chip from Paragon (see last patch), if not I'll update the name accordingly.

**Comment by mennozon** [comment]
> @hauke
> 
> > Please send a patch with the changes in 999-drivers-gl-inet-ar300m-nand-device-ids.patch to the upstream Linux kernel.
> 
> Not a good idea. John tried that with the "W25N01GV" already:
> 
> https://patchwork.ozlabs.org/patch/948498/
> 
> So unless the patch can sneak past the gatekeepers it's not going to happen.
> (I checked the spinand http://git.infradead.org/linux-mtd.git/blob/refs/heads/nand/next:/drivers/mtd/nand/spi/ a while ago and tried to backport it to 4.14 for the ipq40xx. It is possible, but the SoC's spi drivers need to be updated too.)

@hauke @chunkeey I wouldn't mind trying to upstream this if it has a chance to get merged, I'm a bit unsure about the patch as it adds multiple chips and I only have access to my own AR300M which uses that Paragon chip.

Should I rework the patch to only include that specific chip?

**Comment by hanetzer** [comment]
@mennozon Paragon, but the chip is something they bought off another company or
another company they bought or something. XTX or something like that iirc.

**Comment by chunkeey** [comment]
> Should I rework the patch to only include that specific chip?

Depends, but it won't likely help.

See the linked patch and the comment from Boris Brezillon:

https://patchwork.ozlabs.org/patch/948498/#1960274

>Nice try! You're trying to add support for a SPI NAND in a subsystem
>that is supposed to only deal with parallel/raw NANDs :-). I guess
>you're using the MT29F driver that lies in staging (or a modified
>version of this driver).

All new IDs in that patch are for SPI-NAND chips. The ID-Length for all
these chips is "2" (which is a dead giveaway that the staging mt29f_spinand
driver is involved). So, if you want to add support for this chip upstream, you'll
have to port it over to the new spi-nand subsystem. (Or hope that nobody
notices that you are adding spi-nand IDs to a subsystem that only deals with
parallel/raw NANDs ).

**Comment by mennozon** [comment]
> @mennozon Paragon, but the chip is something they bought off another company or
> another company they bought or something. XTX or something like that iirc.

Oh right, you mentioned that [here](https://github.com/openwrt/openwrt/pull/615#issuecomment-372556068) that's why I assumed Paragon at first.

If it's XTX Technology I'll amend the commit.

**Comment by mennozon** [comment]
> @mennozon
> 
> > Should I rework the patch to only include that specific chip?
> 
> Depends, but it won't likely help.
> 
> See the linked patch and the comment from Boris Brezillon:
> 
> https://patchwork.ozlabs.org/patch/948498/#1960274
> 
> > Nice try! You're trying to add support for a SPI NAND in a subsystem
> > that is supposed to only deal with parallel/raw NANDs :-). I guess
> > you're using the MT29F driver that lies in staging (or a modified
> > version of this driver).
> 
> All new IDs in that patch are for SPI-NAND chips. The ID-Length for all
> these chips is "2" (which is a dead giveaway that the staging mt29f_spinand
> driver is involved). So, if you want to add support for this chip upstream, you'll
> have to port it over to the new spi-nand subsystem. (Or hope that nobody
> notices that you are adding spi-nand IDs to a subsystem that only deals with
> parallel/raw NANDs ).

I'm not sure if I'd be able to port it over to spi-nand. I'll look into it though, thanks for clarifying!

**Comment by chunkeey** [comment]
> I'm not sure if I'd be able to port it over to spi-nand. I'll look into it though, thanks for clarifying!

Not only that, but in order to port it to the spi-nand subsystem, you would need to backport all the spi-nand changes from the current upstream (aka 4.19-rcX) back to OpenWrt 4.14 first (which pulls in changes from the mtd, nand and spi subsystem as well).

I would say that the 999-drivers-gl-inet-ar300m-nand-device-ids.patch is ok for right now. But once OpenWrt moves to 4.19 (which could be "soon". see https://github.com/openwrt/openwrt/pull/1386 ) it would be great to do a follow-up and convert the device to the new spi-nand subsystem.

What do you think?

**Comment by mennozon** [comment]
> I would say that the 999-drivers-gl-inet-ar300m-nand-device-ids.patch is ok for right now. But once OpenWrt moves to 4.19 (which could be "soon". see #1386 ) it would be great to do a follow-up and convert the device to the new spi-nand subsystem.
> 
> What do you think?

Sounds like a good idea, I just noticed 999 is not the right prefix for the patch, I'll change it to 4xx as documented [here.](https://wiki.openwrt.org/doc/devel/patches)

**Comment by mennozon** [comment]
> I am waiting 4.19 support to move to the new SPI NAND driver for the widely used W25N01GV SPI NAND on ipq40xx target.
> Its simple to support it and gets rid of the staging m29tf_spinand driver and relevant ID hack in nand_ids.c

Thanks, I'll keep an eye out for this and attempt to convert this device over as well!

**Comment by robimarko** [comment]
@mennozon Just got 4.19-rc5 compiled for ipq40xx and tested the new SPI-NAND driver, works like a treat.
Already pushed a patch to add support for W25N01GV upstream.
Hopefully 4.19 will be ready soon,but there are some issues with mac80211 and swconfig LEDs.

**Comment by mennozon** [comment]
@robimarko I don't have a datasheet, I think @hanetzer might have this though.

**Comment by hanetzer** [comment]
@robimarko @mennozon http://www.xtxtech.com/upfile/2016082517274590.pdf << should be it.

**Comment by mennozon** [comment]
@hanetzer Thanks! I've updated the name.

I also fixed a few other issues that prevented sysupgrade from working, I've tested installing NAND and NOR as well as sysupgrade on them both, everything seem to be working fine.

@robimarko I hope to have some time this week to look into 4.19 and using the new SPI-NAND driver.

**Comment by robimarko** [comment]
The NEW SPI-NAND drivers are really simple, just some basic setup and the framework takes care of the rest.
This one does not look like a special one so something similar to currently supported SPI NANDs should work.
But it requires 4.19 to not have to backport pretty much the whole MTD and SPI subsystems

**Comment by mkresin** [comment]
>  But it requires 4.19 to not have to backport pretty much the whole MTD and SPI subsystems

Please re-spin the patch as soon as we have kernel 4.19 support. The approach was already [NAK'ed upstream](https://patchwork.ozlabs.org/patch/948498/#1960274) and I don't see much gain in adding the hack if the next major kernel in OpenWrt will provide a suitable solution.

**Comment by hex0cter** [comment]
I am looking forward to this. Thanks for your work guys!

**Pull request closed without merging**
