### PR TITLE
libselinux: update to 3.5

### PR DESCRIPTION
**Pull request by misaka36**
Release Notes:
https://github.com/SELinuxProject/selinux/releases/download/3.4/RELEASE-3.4.txt https://github.com/SELinuxProject/selinux/releases/download/3.5/RELEASE-3.5.txt

### CODE REVIEW

**Comment by hauke** [comment]
Did you test seLinux on OpenWrt recently?
There are some paches pending for a long time:
https://patchwork.ozlabs.org/project/openwrt/list/?submitter=81290

**Comment by PolynomialDivision** [comment]
CI fails:
```
 In file included from label_file.h:17,
                 from label_file.c:24:
regex.h:8:10: fatal error: pcre2.h: No such file or directory
    8 | #include <pcre2.h>
      |          ^~~~~~~~~
compilation terminated.
```

**Comment by lovehackintosh** [comment]
libselinux-3.4+ depends on pcre2 instead of pcre.
So, we need to move pcre2 from the packages feed to base. (see https://patchwork.ozlabs.org/project/openwrt/list/?series=301077)

**Comment by BKPepe** [comment]
Hmm, recently, many packages went from packages feed to base even though @ynezz in the first was against merging a lot of packages to main repository and he tried if I remember correctly, to move almost all non-relevant packages to the packages repository because the reasons were using too much HW resources and took more time to build everything in the base.

**Comment by lovehackintosh** [comment]
@BKPepe After moved pcre2, we can remove pcre from the base.
It shouldn’t use too much resources and take more time than before.

**Pull request closed without merging**
