### PR TITLE
ramips: introduce rt2880-clock driver

### PR DESCRIPTION
**Pull request by drvlabo**
This patch introduces gating clock driver for ramips.

In addititon, this patch allows MT7620 and MT76x8 to use common clock features.
(gating clock, fixed rate clock, etc)
We sometimes need common clock features to feed clocks to peripheral devices.
For example, there is a case when we need to bind a fixed rate clock to audio CODEC.

Signed-off-by: NOGUCHI Hiroshi <drvlabo@gmail.com>

### CODE REVIEW

**Comment by peterwillcn** [comment]
ping @nbd168

**Comment by Leo-PL** [comment]
You might consider submitting this driver upstream, so it could be pulled from there, to reduce number of kernel patches OpenWrt has.

**Comment by ynezz** [comment]
@peterwillcn Yeah, it would be nice to get this through upstream first, then backport it to OpenWrt, probably under one of the `target/linux/generic/backport-4.19` or `target/linux/generic/pending-4.19` dirs.

**Comment by drvlabo** [comment]
> You might consider submitting this driver upstream
Where I should post the patches to ? linux-mips ML ?

**Comment by drvlabo** [comment]
And now, many SoC peripheral drivers stays as patches in ramips directory. SPI, I2C, and so on.
Why they are not posted to upstream for a long time ? They have been tested on many devices.

**Comment by ynezz** [comment]
@drvlabo 

> Where I should post the patches to ? linux-mips ML ?

https://www.kernel.org/doc/html/latest/process/submitting-patches.html

> Why they are not posted to upstream for a long time ? They have been tested on many devices.

Simply because nobody is interested in doing this (it's very time consuming) or simply doesn't have spare time needed to do so. Feel free to help upstreaming those patches as well, very much appreciated! Thanks!

**Comment by ynezz** [comment]
@drvlabo 

> linux-mips ML ?

In short, it's something like this, but better read the nice [documentation](https://www.kernel.org/doc/html/latest/process/submitting-patches.html) about it
```
cd linux.git
git format-patch -s1
scripts/checkpatch.pl 000*
scripts/get_maintainer.pl 000*
git send-email --to ...
```

**Comment by peterwillcn** [comment]
Maybe fix [this](https://github.com/openwrt/mt76/issues/263) 
Maybe fix [this ](http://www.acwifi.net/wp-content/uploads/2018/10/SAM_2765.jpg)

**Comment by drvlabo** [comment]
Both mt7620pci and mt7621 do not call clk_* APIs.
Therefore I did not include PCIe clock gating (bit 26) in clock resource table.
(If including it, clk framework disables it as "not used")
This driver effects nothing for PCIe.

Is PCIe reset (PERST) certainly asserted in initializing sequence ?

**Comment by peterwillcn** [comment]
@drvlabo Ok, Thank you.

**Comment by neheb** [comment]
@drvlabo Some of these drivers went through kernel.org's staging process and have now made it upstream (GPIO, SPI, and ethernet).

**Comment by drvlabo** [comment]
I submitted to upstream. Thanks.

**Pull request closed without merging**
