### PR TITLE
[23.05] tools: bzip2: use static lib and tools

### PR DESCRIPTION
**Pull request by robimarko**
Currently, bzip2 is built with a dynamically linked library on which all of the bzip2 tools depend on.

However, when trying to use the staging dir bzip2 during building on Fedora 40 the following error appers:
`staging_dir/host/bin/bzip2: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory`

Looking into it, the binary is dynamically linked: 
```
$ ldd staging_dir/host/bin/bzip2
linux-vdso.so.1 (0x00007f5ebd9ff000)
libbz2.so.1.0 => not found
libc.so.6 => /lib64/libc.so.6 (0x00007f5ebd7f5000) /lib64/ld-linux-x86-64.so.2 (0x00007f5ebda01000)
```

libbz2.so.1.0 is installed into staging_dir/lib but that directory is not evaluated for the required libraries and Fedora only ships: 
```
/usr/lib64/libbz2.so.1
/usr/lib64/libbz2.so.1.0.8
```

Thus it cannot find the libbz2 that bzip2 is linked against and thus trying to use bzip2 will fail and stop compilation as it is used for bzip2 compressed tarballs.

So, to avoid OpenWrt compiled bzip2 to even attempt to load a required library from the host we can just static compile libbz2 and bzip2.

### CODE REVIEW

**Comment by robimarko** [comment]
@neheb This was quite annoying.

BTW, the main branch that uses CMake is also broken as it dynamically links as well but CMake will properly find the Fedora provided library so "it works".

**Comment by neheb** [comment]
bzip2 was supposed to have a meson build upstream. Guess that was abandoned.

**Comment by robimarko** [comment]
Well, that is the sad thing, official bzip releases only have plain Makefiles.

The bzip 1.1 repo which turns out is not the official thing has CMake and Meson.
For the whole saga:
https://sourceware.org/bugzilla/show_bug.cgi?id=31660

**Comment by neheb** [comment]
what do you think of something like this?

```
--- a/include/cmake.mk
+++ b/include/cmake.mk
@@ -127,6 +127,7 @@ define Build/Configure/Default
                        -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=TRUE \
                        -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=FALSE \
                        -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=TRUE \
+                       -DBUILD_SHARED_LIBS=ON \
                        $(CMAKE_OPTIONS) \
                $(CMAKE_SOURCE_DIR) \
        )
@@ -174,6 +175,7 @@ define Host/Configure/Default
                        -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=TRUE \
                        -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=FALSE \
                        -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=TRUE \
+                       -DBUILD_SHARED_LIBS=OFF \
                        $(CMAKE_HOST_OPTIONS) \
                $(HOST_CMAKE_SOURCE_DIR) \
        )
```

**Comment by robimarko** [comment]
I guess defaulting to not building shared libs for host tools makes sense

**Comment by robimarko** [comment]
@Ansuel You were part of the initial bzip2 merge, thought?

**Comment by robimarko** [comment]
Thanks! Rebased on top of openwrt-23.05 and merged!

**Pull request merged**
