### PR TITLE
ath10k-ct: update to version from 2021-09-22

### PR DESCRIPTION
**Pull request by theAeon**
Signed-off-by: Andrew Robbins <andrew@robbinsa.me>

Upstream patch on 9/22/21 fixes broken VHT160. Tested working on R7800.

### CODE REVIEW

**Comment by castiel652** [comment]
You need to refresh the patches and describe what's updated in the commit message

**Comment by theAeon** [comment]
> 
> 
> You need to refresh the patches and describe what's updated in the commit message

ack, my bad, hold on.

**Comment by hnyman** [comment]
You should first propose this to the master branch, not to the stable 21.02.

**Comment by theAeon** [comment]
> 
> 
> You should first propose this to the master branch, not to the stable 21.02.

I was unaware bugfix patches needed to filter down like from master?

**Comment by hnyman** [comment]
Well, it would be strange that 21.02 would have newer ath10k-ct driver than the bleeding edge master...
(If the fix works, it should naturally be implemented in both)

**Comment by theAeon** [comment]
> 
> 
> Well, it would be strange that 21.02 would have newer ath10k-ct driver than the bleeding edge master... (If the fix works, it should naturally be implemented in both)

Fair point. I'll rebase. Can that even be changed on this PR or do i need to close it?

**Comment by theAeon** [comment]
oh god. hold on.

**Comment by theAeon** [comment]
Alright. Rebased master, refreshed the patches and fixed the commit description (copy/pasted from upstream dev). Should be good.

**Comment by adschm** [comment]
Please use a commit title similar to the earlier ones, e.g. "ath10k-ct: update to latest version".

**Comment by adschm** [comment]
> ath10k-ct: update to commit 23c7461

If you don't like "to latest version", maybe use "to version from 2021-09-22". The mere commit hash is not really helpful for a _title_, as it's not saying anything by itself.

**Comment by hnyman** [comment]
I tested with my R7800, and at the first glance, it actually works. Nice ;-)

80 MHz wide DFS channel
```
Tue Oct  5 22:47:01 2021 kern.info kernel: [  187.651192] device wlan0 entered promiscuous mode
Tue Oct  5 22:47:01 2021 daemon.notice hostapd: wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
Tue Oct  5 22:47:01 2021 daemon.notice hostapd: wlan0: interface state COUNTRY_UPDATE->HT_SCAN
Tue Oct  5 22:47:01 2021 daemon.notice hostapd: wlan0: interface state HT_SCAN->DFS
Tue Oct  5 22:47:01 2021 daemon.notice hostapd: wlan0: DFS-CAC-START freq=5500 chan=100 sec_chan=1, width=1, seg0=106, seg1=0, cac_time=60s
Tue Oct  5 22:47:02 2021 daemon.notice netifd: Wireless device 'radio0' is now up
Tue Oct  5 22:48:02 2021 daemon.notice hostapd: wlan0: DFS-CAC-COMPLETED success=1 freq=5500 ht_enabled=0 chan_offset=0 chan_width=3 cf1=5530 cf2=0
Tue Oct  5 22:48:02 2021 kern.info kernel: [  248.812351] ath10k_pci 0000:01:00.0: mac flush null vif, drop 0 queues 0xffff
Tue Oct  5 22:48:02 2021 kern.info kernel: [  248.849150] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
Tue Oct  5 22:48:02 2021 kern.info kernel: [  248.849294] br-lan: port 2(wlan0) entered blocking state
Tue Oct  5 22:48:02 2021 kern.info kernel: [  248.854669] br-lan: port 2(wlan0) entered forwarding state
Tue Oct  5 22:48:02 2021 daemon.notice netifd: Network device 'wlan0' link is up
Tue Oct  5 22:48:02 2021 daemon.notice hostapd: wlan0: interface state DFS->ENABLED
Tue Oct  5 22:48:02 2021 daemon.notice hostapd: wlan0: AP-ENABLED
Tue Oct  5 22:48:10 2021 daemon.info hostapd: wlan0: STA cc:b1:... IEEE 802.11: authenticated
Tue Oct  5 22:48:10 2021 daemon.info hostapd: wlan0: STA cc:b1:... IEEE 802.11: associated (aid 1)
```

160 MHz wide DFS seems to also work:
```
Tue Oct  5 22:51:22 2021 kern.info kernel: [  448.291667] device wlan0 entered promiscuous mode
Tue Oct  5 22:51:22 2021 daemon.notice hostapd: wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
Tue Oct  5 22:51:22 2021 daemon.notice hostapd: wlan0: interface state COUNTRY_UPDATE->HT_SCAN
Tue Oct  5 22:51:22 2021 daemon.notice hostapd: wlan0: interface state HT_SCAN->DFS
Tue Oct  5 22:51:22 2021 daemon.notice hostapd: wlan0: DFS-CAC-START freq=5500 chan=100 sec_chan=1, width=2, seg0=114, seg1=0, cac_time=60s
Tue Oct  5 22:51:23 2021 daemon.notice netifd: Wireless device 'radio0' is now up
Tue Oct  5 22:52:23 2021 daemon.notice hostapd: wlan0: DFS-CAC-COMPLETED success=1 freq=5500 ht_enabled=0 chan_offset=0 chan_width=5 cf1=5570 cf2=0
Tue Oct  5 22:52:23 2021 kern.info kernel: [  509.934485] ath10k_pci 0000:01:00.0: mac flush null vif, drop 0 queues 0xffff
Tue Oct  5 22:52:23 2021 kern.info kernel: [  509.969128] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
Tue Oct  5 22:52:23 2021 kern.info kernel: [  509.969275] br-lan: port 2(wlan0) entered blocking state
Tue Oct  5 22:52:23 2021 kern.info kernel: [  509.974543] br-lan: port 2(wlan0) entered forwarding state
Tue Oct  5 22:52:23 2021 daemon.notice netifd: Network device 'wlan0' link is up
Tue Oct  5 22:52:23 2021 daemon.notice hostapd: wlan0: interface state DFS->ENABLED
Tue Oct  5 22:52:23 2021 daemon.notice hostapd: wlan0: AP-ENABLED
Tue Oct  5 22:52:31 2021 daemon.info hostapd: wlan0: STA cc:b1:... IEEE 802.11: authenticated
```

**Comment by lister-wrt** [comment]
Tested on unifi-ac-pro for ~12hrs. No issues

**Comment by ACwifidude** [comment]
Working well on three R7800 (uptime 24 hours each) running 21.02

**Comment by hnyman** [comment]
@hauke seems to have a similar ath10k-ct version bump on his staging tree at 
https://git.openwrt.org/?p=openwrt/staging/hauke.git;a=commitdiff;h=798ca12cc638eaf5c05bb74bd564e8eb947f3a5f
...but to have a different PKG_MIRROR_HASH there. Which one is right?

Btw, I tested this also on 21.02 in R7800. Seems enable VHT160 DFS also there. So, I hope that this ath10k-ct bump gets backported also to 21.02 (which theAeon originally targeted), as it is annoying that ath10k-ct is currently crippled also there.

**Comment by hauke** [comment]
Both mirror hashes are correct. You used the date 2021-09-22 and I used the date 2021-09-23. This will generate a different tar..xz file with a different hash.

**Pull request closed without merging**
