### PR TITLE
ipq40xx: easy install for ASUS RT-AC58U/RT-ACRH13

### PR DESCRIPTION
**Pull request by ptpt52**
This patch make it easy to flash via web upgrade from factory firmware.
 * build flash-factory.trx for web ui upgrade from stock system.
 * fixup macaddress for eth0
 * rewrite the initramfs building command: initramfs image ready to upgrade from stock

 - install from stock to openwrt:
   1. upgrade via stock web ui, using file: initramfs-factory.trx
   2. sysupgrade via openwrt web ui, use the sysupgrade.bin

 - revert back to stock:
   1. copy RT-ACXXX.trx to /tmp/ via ssh
   2. do sysupgrade -F /tmp/RT-ACXXX.trx

idea original from 981213

### CODE REVIEW

**Comment by ptpt52** [comment]
tested on RT-AC58U and RT-ACRH17 (of course this is not suppported in openwrt for now).

**Comment by chunkeey** [comment]
Check this out: 

https://git.openwrt.org/?p=openwrt/staging/chunkeey.git;a=commit;h=3109d573196ae0696a371bb2e28324cad2838793

it cuts out the "middle man" completely, no sysupgrade from the ramdisk required.

**Comment by ptpt52** [comment]
There are some differences
This way I make it easier to get back to stock, I only need sysupgrade -F RT-AC58U.trx

We have reserved enough space for 'linux' partition, and also kept a small 'jffs2' partition to meet the u-boot requirements, so if the openwrt system fails, we can restart the device, hold reset into recovery mode, and then tftp put xxx.trx to restore

**Comment by ptpt52** [comment]
the "middle man" is not that import I think.
The probability of someone attacking you when you are actually flashing is rarely.

**Comment by luaraneda** [comment]
@chunkeey Are you sure that replacing the stock bootloader is a good idea? I thought that replacing the bootloader was the last resort option when adding support for a new device.
You are replacing the bootloader and additionally requiring serial access, which means opening the device and connecting a serial adapter.

I don't completely agree with @ptpt52 's solution, but for sure less invasive as it doesn't replace the bootloader nor require serial access, and can be done by a user with the right guide/documentation.

I installed OpenWRT on my first RT-AC58U using a serial adapter, but for the second I put the device into rescue mode an flashed the initramfs with the ASUS Firmware Restoration utility because the webUI was rejecting the initramfs image.

Maybe we can implement another solution for this device. Maybe with an installation script that runs on the first boot.

**Comment by ptpt52** [comment]
@luaraneda hi, the @chunkeey 's solution should replacing the stock bootloader, as I can see.
maybe it just pre-attach a bootloader script to do the trick.

by the way can you help do more test on my solution? you can revert back to stock and do the test.

**Comment by chunkeey** [comment]
> @chunkeey Are you sure that replacing the stock bootloader is a good idea? I thought that replacing the bootloader was the last resort option when adding support for a new device.
You are replacing the bootloader and additionally requiring serial access, which means opening the device and connecting a serial adapter

Don't worry, that's not the case. The u-boot is installing the image as sysupgrade would and it's overwriting itself in the process. it goes from ASUS Stock Firmware straight to OpenWrt without needing any serial adapters or messing with ssh... and it keeps the linux2 partition around so it would fallback in case something went wrong during the flashing procedure. The idea really was that it's "just like a real factory image".

**Comment by luaraneda** [comment]
> Don't worry, that's not the case. (EDIT: The original u-boot will be untouched. The idea follows that of the AVM FritzBox 4040, that uses a custom u-boot image for its purposes). The u-boot that's written to the linux partition will look for the rest of the sysupgrade image in the linux voume and will install it. (In which case it will overwriting itself in the process, so it won't take up any space).

Ok, so you are chain-loading u-boot (Stock u-boot -> custom u-boot). Nice trick!
I think that chain-loading it's not even supported on mainline u-boot, but you somehow did it :)
Just a suggestion: You might want to rework the commit message, as it wasn't clear to me the first time I read it.

> Now, it's possible to from ASUS Stock Firmware straight to OpenWrt without needing any serial adapters or messing with ssh. This version also keeps the linux2 partition around so it would fallback in case something went wrong during the flashing procedure. The idea really was that it's "just like a real factory image".

Great. That got me thinking, could we do the same thing that your modified u-boot is doing from OpenWRT? If I remember correctly, OpenWRT always starts as an initramfs and later on the boot process it switches the rootfs to the flash. Maybe we can execute some init/installation script before the switch.

Additionally, I think the stock bootloader copies the content of **linux** to **linux2** when it founds a valid image (checksum?) on **linux**, so we hypothetically have another copy of the OpenWRT image (not confirmed).

**Comment by chunkeey** [comment]
>Just a suggestion: You might want to rework the commit message, as it wasn't clear to me the first time I read it.

Ok, any idea how that should look like? What would you have written instead?

>>  Now, it's possible to from ASUS Stock Firmware straight to OpenWrt without needing any serial adapters or messing with ssh. This version also keeps the linux2 partition around so it would fallback in case something went wrong during the flashing procedure. The idea really was that it's "just like a real factory image".
>
> Great. That got me thinking, could we do the same thing that your modified u-boot is doing from OpenWRT? If I remember correctly, OpenWRT always starts as an initramfs and later on the boot process it switches the rootfs to the flash. Maybe we can execute some init/installation script before the switch.

? Are you referring to a specific target, or "general" openwrt image here? Because initramfs
should be avoided for proper installations since the configuration will be gone after a reboot.

> Additionally, I think the stock bootloader copies the content of linux to linux2 when it founds a valid image (checksum?) on linux, so we hypothetically have another copy of the OpenWRT image (not confirmed).

Yes, something along the lines. I think I remember update_tftp() in common/update.c was involved in that process, but don't remember the details. So it could behave differently whenever it was updated
through the web-ui or through recovery or tftp.

**Comment by luaraneda** [comment]
> Ok, any idea how that should look like? What would you have written instead?

I would change a small detail, so it is more explicit that on the commit message you are describing two installations methods for the -factory.trx image. Something like:
```
The -factory.trx image can be installed using the web-console:
 [instructions here]
Alternatively, the -factory.trx can be installed using TFTP and a serial cable:
 [instructions here]
```

> ? Are you referring to a specific target, or "general" openwrt image here? Because initramfs
> should be avoided for proper installations since the configuration will be gone after a reboot.

Yeah, you are right. I thought that something could be done on the preinit stage, but I'm not so sure anymore. I'm gonna play with preinit when I have some free time.

**Comment by adrianschmutzler** [comment]
@ptpt52 Can you respond and/or make the necessary changes if you want to continue with this?
Despite, "X Wrt" is not a valid name for Signed-off ...

**Comment by ptpt52** [comment]
hi @adrianschmutzler 

it seems @chunkeey use new method for factory img? if that is the case I should close this PR

**Comment by adrianschmutzler** [comment]
@ptpt52 I'm just collecting loose ends, so I haven't dived into the topic in detail. So, you will have to make up your mind yourself. ;-)

**Comment by adrianschmutzler** [comment]
@ptpt52 So, can it be closed or do you want to update?

**Comment by ptpt52** [comment]
I close it.

**Pull request closed without merging**
