### PR TITLE
wolfssl: bump to v5.3.0-stable

### PR DESCRIPTION
**Pull request by cotequeiroz**
This is mostly a bug fix release, including two that were already patched here:
- 300-fix-SSL_get_verify_result-regression.patch
- 400-wolfcrypt-src-port-devcrypto-devcrypto_aes.c-remove-.patch

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

---

This was tested on mediatek/mt7622 (aarch64-cortexa53) using uclient_fetch, wpad & uhttpd.

While at it, can someone take a look at #9738.  Even though enabling CPU crypto support should be a no-brainer,  the need to make it `nonshared` may raise concerns.  Speaking of enabling CPU crypto instructions support, #9756 will add them to the kernel, where mac80211 can make good use of them.

### CODE REVIEW

**Comment by hauke** [comment]
Thank you for the patch, I applied it tot master in 73c1fe2890baa5c0bfa46f53c5387f5e47de1acb.

**Comment by neheb** [comment]
@cotequeiroz this broke https://downloads.openwrt.org/releases/faillogs-22.03/aarch64_cortex-a53/packages/libuwsc/wolfssl/compile.txt . Can you take a look?

**Comment by cotequeiroz** [comment]
I think it may be related to #9738, unless it started earlier than that.

**Comment by cotequeiroz** [comment]
Sorry, it took some time before I managed to look into it.  It is missing 
``` C
#include <wolfssl/options.h>
```
before the other wolfssl includes in `src/ssl.c`.

**Pull request closed without merging**
