### PR TITLE
[RFT] brcm63xx: use more systematic names for image/DTS plus board_name removal

### PR DESCRIPTION
**Pull request by adschm**
** Please test on device **

This changes brcm63xx target to achieve consistency between image
names, device nodes names, compatible, DTS name and device name
as much as possible. As with other targets, having consistent
names is supposed to make life easier for developers and reduces
the number of "variables" in the system. In particular, applying
the DTS scheme will make it easier to find the correct file and
architecture.

Despite, I took the chance to also remove the "old" board_name
variable and replace it by directly using the compatible. This
also resulted in fixing several wrong identifiers in base-files.

As with other similar projects, I cannot test this on device and
would be glad if someone could do that.

### CODE REVIEW

**Comment by KanjiMonster** [comment]
Please use `<soc>-<vendor>-<boardname>.dts`, as this is what upstream linux uses. Or just `<boardname>dts`. Both are in use.

Note that <soc> and Chip ID used in the image headers are not always identical - e.g. the SoCs BCM63168, BCM63268, BCM63169 and BCM63269 all use the 63268 Chip ID for the image header, but are four different SoCs with different capabilities, so the dts naming should reflect that, if you deem to include the SoC (xxxx9 means no DSL support, 6316x is a cheaper variant of 6326x with some disabled features, etc).

So far it hasn't been necessary to discriminate them in device tree since the differing capabilities aren't available yet in device tree, but to avoid a lot of renaming churn it would be better to have that properly reflected in the files names from the start.

**Comment by adrianschmutzler** [comment]
@KanjiMonster I've changed to <soc>-<vendor>-<boardname>.dts (currently build testing), will push here in an hour.

> Note that and Chip ID used in the image headers are not always identical - e.g. the SoCs BCM63168, BCM63268, BCM63169 and BCM63269 all use the 63268 Chip ID for the image header, but are four different SoCs with different capabilities, so the dts naming should reflect that, if you deem to include the SoC (xxxx9 means no DSL support, 6316x is a cheaper variant of 6326x with some disabled features, etc).

Since there is no indication anywhere (dtsi, compatible, Chip ID) what to use as the correct SOC, that's a little hard for me to do. Can you provide any kind of comprehensive overview which device should have which SOC prefix?

**Comment by adrianschmutzler** [comment]
Changed to hyphen for separation in DTS name.

**Comment by KanjiMonster** [comment]
Sorry for the unavailabilty, more busy than expected. I couldn't have pointed you to better source though.

**Comment by adrianschmutzler** [comment]
@KanjiMonster Any objections against me merging this this or next week?

**Pull request closed without merging**
