### PR TITLE
utils: mtd-utils: drop patches

### PR DESCRIPTION
**Pull request by robimarko**
We have been carrying the 100-fix_includes.patch and 130-lzma_jffs2.patch for a long time but the reason is lost to history.

We dont need to carry the JFFS2 LZMA support patch as mkfs.jffs2 is not even being packaged so its not even being used.

As for the 100-fix_includes.patch that also seems like a relic of history as mtd-utils compiles fine without it.

So, lets drop both patches.

### CODE REVIEW

**Comment by robimarko** [comment]
@Ansuel You can probably sanity check this

**Comment by Ansuel** [comment]
@robimarko mhhh i notice some bmips mvebu and ath79 target still use mkfs.jffs2 (from tools tho)

we should check if there are some runtime script that can make of it (but I doubt) afaik if some reason ubi fails to create an overlay... jffs2 is still used as a fallback... so that is also to consider. lets give some days for this to be notice and see how it goes.

**Comment by robimarko** [comment]
Yes, JFFS2 is required in the host tool.

Read the commit again, `mkfs,jffs2` tool is not even packaged for installation on the device, only ubi and and nand tools are.
So, we cannot have a device using it during runtime.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
