### PR TITLE
kernel: bump 5.10 to 5.10.131

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by hauke** [comment]
Please rebase these patch they are not applying any more on top of 1a9ee367343edce263f82cc91a49d796c9d45ea3.

**Comment by graysky2** [comment]
@hauke - done

**Comment by hardfalcon** [comment]
Compile tested: realtek/rtl838x (Netgear GS108T v3)
Run tested: realtek/rtl838x (Netgear GS108T v3)

**Comment by blocktrron** [comment]
Merged see https://github.com/openwrt/openwrt/commit/c50d462e34e373ef4190e6b0b1f49a22202b9fe0

**Pull request closed without merging**
