### PR TITLE
dante: Disabled "sched_getscheduler()" - not implemented in musl

### PR DESCRIPTION
**Pull request by yangfl**
Ref: http://lists.alpinelinux.org/alpine-devel/3936.html

Signed-off-by: David Yang <mmyangfl@gmail.com>

Maintainer: @jow-
Compiled tested: openwrt 18.06.0
Run tested: openwrt 18.06.0 wndr3800

### CODE REVIEW

**Comment by mkresin** [comment]
Please rewrite your commit message. Don't force us to follow any external links and to find/filter the relevant information on our own.

Good commit messages serve at least three important purposes:

 - To speed up the reviewing process.
 - To help us write a good release note.
 - To help the future maintainers, say five years into the future, to find out why a particular change was made to the code or why a specific feature was added.

A good commit message should answer three questions about a patch:

 - Why is it necessary? It may fix a bug, it may add a feature, it may improve performance, reliabilty, stability, or just be a change for the sake of correctness.
 - How does it address the issue? For short obvious patches this part can be omitted, but it should be a high level description of what the approach was.
 - What effects does the patch have? (In addition to the obvious ones, this may include benchmarks, side effects, etc.)

**Comment by yangfl** [comment]
@mkresin updated, please take a look.

**Comment by mkresin** [comment]
Sorry,  not my area of expertise!

**Review by super-kevin — COMMENTED** [review]
Thanks for the fix. I run into the same problem.

**Comment by jow-** [comment]
Merged, thank you!

**Pull request closed without merging**
