### PR TITLE
[WiP][RFC] ath79: add support for PISEN WMB001N

### PR DESCRIPTION
**Pull request by 981213**
This is a "music box" with ar9341+wm8918.

Factory u-boot is built without 'savenv' support so it's impossible to change kernel offset. A 2MB kernel partition won't be enough in the future.
My solution for this problem:
1. add OKLI image magic support into uImage parser.
2. build an OKLI loader, compress it with lzma and add a normal uImage header.
3. flash the loader to where the original kernel supposed to be.
4. create a uImage firmware using OKLI loader.
5. flash the created firmware to where rootfs supposed to be.

By doing so, u-boot will start OKLI loader, which will then load the actual kernel at 0x20000.
(This is similar to the solution I mentioned somewhere for implementing auto kernel/rootfs splitting of TP-LINK CPE routers.)

This introduced another problem: We are now wasting the entire 2MB kernel partition.
Solution:
1. create a 64K (1 erase block) partition for OKLI loader and create another partition with the left space.
2. concatenate rootfs and this partition into a virtual flash.
3. use the virtual flash for firmware partition.

Currently OKLI loader is flashed with factory image only. sysupgrade won't replace it. Since it only has one function and it works for several years, its unlikely to have some bugs that requires a replacement.

WiP: porting/rewriting QCA's PCM/I2S driver.
RFC:
1. Similar to PISEN WMM003N, this router also has a weird english name: "Music Cloud Box". Should I add this name to DEVICE_MODEL?
2. To create factory image, I need a fixed binary blob and append a tarball containing uImage and rootfs. That fixed binary blob contains model name and a checksum. I think it's overkill to write a mkxxximage that can only output fixed data so I just copied that binary blob into target/linux/ath79/image/bin. Is this appropriate?

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
> Similar to PISEN WMM003N, this router also has a weird english name: "Music Cloud Box". Should I add this name to DEVICE_MODEL?

You could use the DEVICE_ALT0_VENDOR/DEVICE_ALT0_MODEL syntax for that (which is currently still waiting for final review).

**Comment by 981213** [comment]
This isn't a "two boards using the same firmware" situation. This is just a "nickname" for this model.

**Comment by ptpt52** [comment]
I think we should set the nickname to `DEVICE_VARIANT`
```
DEVICE_VARIANT := (Music Cloud Box)
```

**Comment by adrianschmutzler** [comment]
DEVICE_ALTx_VENDOR/DEVICE_ALTx_MODEL were invented for a similar scenario as yours, i.e. when there is device that has different names (e.g. an "internal" name and a name chosen by a retailer):
https://github.com/openwrt/openwrt/pull/2229

Actually the way I used it for the WR94x discussion was derived from that original motivation.

**Comment by adrianschmutzler** [comment]
@ptpt52 
DEVICE_VARIANT is meant to _distinguish_ between variants, so it's not the right choice here.
One should use either the ALTx approach or just append it in brackets to the DEVICE_MODEL as initially suggested.

**Comment by ptpt52** [comment]
@adrianschmutzler append it to `DEVICE_MODEL` is ok

actually, it's just a name. It's better to do it simply, quote the names in parentheses, and use a slash to separate multiple name.

**Comment by ptpt52** [comment]
just like
`
DEVICE_MODEL := XXXXX (Name1/Name2/Name3)
`

**Comment by adrianschmutzler** [comment]
@ptpt52 
This concept quickly becomes a mess, as we have experienced when converting lantiq in #2299 .

However, if you want to contribute to that discussion, maybe it's better to respond on #2299 or #2250 ...

**Comment by 981213** [comment]
I'm unable to figure out how the sound subsystem work so far and I gave up on that WiP part...

**Pull request closed without merging**
