### PR TITLE
dropbear: bump to 2018.76

### PR DESCRIPTION
**Pull request by rockdrilla**
Configuration/compatibility changes:
  - "configure --enable-static" should now be used instead of "make STATIC=1".
    This will avoid 'hardened build' flags that conflict with static binaries.
  - Set 'hardened build' flags by default if supported by the compiler.
    These can be disabled with configure --disable-harden if needed.
  - Spectre patch from Loganaden Velvindron.
  - "dropbear -r" option for hostkeys no longer attempts to load the default
    hostkey paths as well. If desired these can be specified manually.
    Patch from CamVan Nguyen.
  - group1-sha1 key exchange is disabled in the server by default since the
    fixed 1024-bit group may be susceptible to attacks.
  - twofish ciphers are now disabled in the default configuration.
  - Default generated ECDSA key size is now 256 (rather than 521) for better
    interoperability.
  - Minimum RSA key length has been increased to 1024 bits.

  Other features and fixes:
  - Add runtime -T max_auth_tries option from Kevin Darbyshire-Bryant.
  - Add 'dbclient -J &fd' to allow dbclient to connect over an existing socket.
    See dbclient manpage for a socat example. Patch from Harald Becker.
  - Add "-c forced_command" option. Patch from Jeremy Kerr.
  - Restricted group -G option added with patch from stellarpower.
  - Support server-chosen TCP forwarding ports, patch from houseofkodai.
  - Allow choosing outgoing address for dbclient with
    -b [bind_address][:bind_port]. Patch from houseofkodai.
  - Makefile will now rebuild object files when header files are modified.
  - Add group14-256 and group16 key exchange options.
  - curve25519-sha256 also supported without @libssh.org suffix.
  - Update bundled libtomcrypt to 1.18.1, libtommath to 1.0.1.
    This fixes building with some recent versions of clang.
  - Set PAM_RHOST which is needed by modules such as pam_abl.
  - Improvements to DSS and RSA public key validation.
    Found by OSS-Fuzz.
  - Don't exit when an authorized_keys file has malformed entries.
    Found by OSS-Fuzz.
  - Fix null-pointer crash with malformed ECDSA or DSS keys.
    Found by OSS-Fuzz
  - Numerous code cleanups and small issues fixed by Francois Perrad.
  - Test for pkt_sched.h rather than SO_PRIORITY which was problematic with
    some musl platforms. Reported by Oliver Schneider and Andrew Bainbridge.
  - Fix some platform portability problems, from Ben Gardner.
  - Add EXEEXT filename suffix for building dropbearmulti, from William Foster.
  - Support --enable-<option> properly for configure, from Stefan Hauser.
  - configure have_openpty result can be cached, from Eric BУЉnard.
  - handle platforms that return close() < -1 on failure, from Marco Wenzel.
  - Build and configuration cleanups from Michael Witten.
  - Fix libtomcrypt/libtommath linking order, from Andre McCurdy.
  - Fix old Linux platforms that have SYS_clock_gettime but not CLOCK_MONOTONIC.
  - Update curve25519-donna implementation to current version.

  Cherry-pick upstream fixes, strip down supplemental code for fuzzing, refresh
  patches, move OpenWRT configuration from patch to Build/Configure recipe.

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by rockdrilla** [comment]
This PR requires some work with more skilled OpenWRT devs, because binary size has grown by 75% (168kb vs 295kb) in 'make defconfig' scenario and package (ipk) has grown by 52% (85kb vs 128kb).

**Comment by rockdrilla** [comment]
@xback, thanks for comment. Please report as soon as possible in which cases that problem is reproducible, I'll try to investigate by myself.

**Comment by rockdrilla** [comment]
I've rebased PR on top of master. There're commits in master (16cec7ae and 61eee1ad) which probably fix Illegal instruction errors. Need acknowledgement from @xback.

**Comment by xback** [comment]
@rockdrilla 

Apologies for late reply .. It's been really busy here.
Building at this very moment to test it using todays master containg those 2 commits.

**Comment by rockdrilla** [comment]
I was totally wrong when I've decided to squash upstream fixes into one patch. I'll done PR in right way (likewise PR 794) during several days, so I'm closing this one.

**Pull request closed without merging**
