### PR TITLE
hostapd: update to 2023-06-22

### LINKED ISSUE #12661: MT7921u drivers hangs when starts access point
### Describe the bug

```text
[   13.047646] mt7921u 2-1:1.3: Message 00020003 (seq 6) timeout
[   13.053416] phy0-ap0: failed to set key (1, ff:ff:ff:ff:ff:ff) to hardware (-110)
[   16.247579] mt7921u 2-1:1.3: vendor request req:63 off:d02c failed:-110
[   19.467546] mt7921u 2-1:1.3: vendor request req:63 off:d054 failed:-110
[   22.056415] passwall2: restart when wan ifup
[   22.676952] mt7921u 2-1:1.3: vendor request req:63 off:d058 failed:-110
[   25.887021] mt7921u 2-1:1.3: vendor request req:63 off:53b8 failed:-110
[   29.106829] mt7921u 2-1:1.3: vendor request req:63 off:53c4 failed:-110
[   31.704241] passwall2: restart when wanv6 ifup
[   32.306604] mt7921u 2-1:1.3: vendor request req:66 off:53c4 failed:-110
[   35.506410] mt7921u 2-1:1.3: vendor request req:63 off:d698 failed:-110
[   38.706237] mt7921u 2-1:1.3: vendor request req:63 off:d520 failed:-110
[   41.906062] mt7921u 2-1:1.3: vendor request req:63 off:d518 failed:-110
[   45.115859] mt7921u 2-1:1.3: vendor request req:63 off:d688 failed:-110
[   48.315695] mt7921u 2-1:1.3: vendor request req:63 off:d690 failed:-110
[   51.515532] mt7921u 2-1:1.3: vendor request req:63 off:d558 failed:-110
[   54.715376] mt7921u 2-1:1.3: vendor request req:63 off:d564 failed:-110
[   57.915228] mt7921u 2-1:1.3: vendor request req:63 off:d568 failed:-110
[   61.115072] mt7921u 2-1:1.3: vendor request req:63 off:d7a8 failed:-110
[   64.314940] mt7921u 2-1:1.3: vendor request req:63 off:a150 failed:-110
[   67.514794] mt7921u 2-1:1.3: vendor request req:63 off:a158 failed:-110
[   70.714651] mt7921u 2-1:1.3: vendor request req:63 off:d780 failed:-110
[   73.914523] mt7921u 2-1:1.3: vendor request req:63 off:d770 failed:-110
[   77.114400] mt7921u 2-1:1.3: vendor request req:63 off:d774 failed:-110
[   80.314290] mt7921u 2-1:1.3: vendor request req:63 off:d55c failed:-110
[   83.513857] mt7921u 2-1:1.3: vendor request req:63 off:10e0 failed:-110
[   86.714019] mt7921u 2-1:1.3: vendor request req:63 off:10e4 failed:-110
[   89.914461] mt7921u 2-1:1.3: vendor request req:63 off:10e8 failed:-110
[   93.114886] mt7921u 2-1:1.3: vendor request req:63 off:10ec failed:-110
[   96.315310] mt7921u 2-1:1.3: vendor request req:63 off:10f0 failed:-110
[   99.515701] mt7921u 2-1:1.3: vendor request req:63 off:10f4 failed:-110
[  102.716087] mt7921u 2-1:1.3: vendor request req:63 off:10f8 failed:-110
[  105.916444] mt7921u 2-1:1.3: vendor request req:63 off:10fc failed:-110
[  109.116786] mt7921u 2-1:1.3: vendor request req:63 off:d7dc failed:-110
[  112.317143] mt7921u 2-1:1.3: vendor request req:63 off:d7ec failed:-110
[  115.517432] mt7921u 2-1:1.3: vendor request req:63 off:d7e0 failed:-110
[  118.717454] mt7921u 2-1:1.3: vendor request req:63 off:d7f0 failed:-110
[  121.917669] mt7921u 2-1:1.3: vendor request req:63 off:d7e4 failed:-110
[  125.117298] mt7921u 2-1:1.3: vendor request req:63 off:d7f4 failed:-110
[  128.317497] mt7921u 2-1:1.3: vendor request req:63 off:d7e8 failed:-110
[  131.517434] mt7921u 2-1:1.3: vendor request req:63 off:d7f8 failed:-110
[  131.746515] mt7921u 2-1:1.3: HW/SW Version: 0x8a108a10, Build Time: 20230331110902a
[  131.746515] 
[  131.766324] mt7921u 2-1:1.3: WM Firmware Version: ____010000, Build Time: 20230331110939
[  134.502562] br-lan: port 1(phy0-ap0) entered disabled state
[  134.510904] device phy0-ap0 left promiscuous mode
[  134.515733] br-lan: port 1(phy0-ap0) entered disabled state
[  135.766014] br-lan: port 1(phy0-ap0) entered blocking state
[  135.771761] br-lan: port 1(phy0-ap0) entered disabled state
[  135.777662] device phy0-ap0 entered promiscuous mode
[  135.782869] br-lan: port 1(phy0-ap0) entered blocking state
[  135.788510] br-lan: port 1(phy0-ap0) entered forwarding state`
```

From system boot to ap ready, it takes nearly 150 seconds.

### OpenWrt version

r22910-a7747e8670

### OpenWrt target/subtarget

bcm27xx/bcm2711

### Device

Raspberry Pi 4 Model B Rev 1.4

### Image kind

Self-built image

### Steps to reproduce

After system boot, just execute 
`wifi up radio1`.

You will see the error messages with
`dmesg`

### Actual behaviour

It seems that there something wrong with the driver. Until the error timeout, the ap won't start.

### Expected behaviour

Start the ap with no error.

### Additional info

Here are the drivers installed.
```text
root@pi:~# lsmod | grep 7921
cfg80211              315392  8 brcmfmac,mt7921_common,mt76x2_common,mt76x02_lib,mt7603e,mt76_connac_lib,mt76,mac80211
mac80211              610304  6 mt7921_common,mt76x2e,mt76x02_lib,mt7603e,mt76_connac_lib,mt76
mt76                   61440  8 mt7921u,mt7921_common,mt76x2e,mt76x2_common,mt76x02_lib,mt7603e,mt76_usb,mt76_connac_lib
mt76_connac_lib        49152  2 mt7921u,mt7921_common
mt76_usb               24576  1 mt7921u
mt7921_common          65536  1 mt7921u
mt7921u                20480  0 
```

Here is the ap settings.
``` text
root@pi:~# uci show wireless.radio1
wireless.radio1=wifi-device
wireless.radio1.type='mac80211'
wireless.radio1.path='scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-1/2-1:1.3'
wireless.radio1.channel='149'
wireless.radio1.band='5g'
wireless.radio1.htmode='HE80'
wireless.radio1.cell_density='0'
wireless.radio1.txpower='20'
wireless.radio1.beacon_int='37'
wireless.radio1.distance='37'
wireless.radio1.country='CN'
```

### Diffconfig

```text
CONFIG_TARGET_bcm27xx=y
CONFIG_TARGET_bcm27xx_bcm2711=y
CONFIG_TARGET_bcm27xx_bcm2711_DEVICE_rpi-4=y
CONFIG_DRIVER_11AX_SUPPORT=y
# CONFIG_FEED_kenzo is not set
# CONFIG_FEED_small is not set
CONFIG_HTOP_LMSENSORS=y
CONFIG_IMAGEOPT=y
CONFIG_KERNEL_PAGE_POOL=y
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_MBEDTLS=y
CONFIG_LIBCURL_NGHTTP2=y
CONFIG_LIBCURL_NO_SMB="!"
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_UNIX_SOCKETS=y
CONFIG_LIBSODIUM_MINIMAL=y
CONFIG_LIBSSH2_OPENSSL=y
CONFIG_OPENSSH_LIBFIDO2=y
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_PACKAGE_MAC80211_DEBUGFS=y
CONFIG_PACKAGE_MAC80211_MESH=y
CONFIG_PACKAGE_acme=y
CONFIG_PACKAGE_acme-acmesh=y
CONFIG_PACKAGE_acme-acmesh-dnsapi=y
CONFIG_PACKAGE_acme-common=y
CONFIG_PACKAGE_bash=y
CONFIG_PACKAGE_bzip2=y
CONFIG_PACKAGE_ca-certificates=y
CONFIG_PACKAGE_cfdisk=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_coreutils=y
CONFIG_PACKAGE_coreutils-base64=y
CONFIG_PACKAGE_coreutils-nohup=y
CONFIG_PACKAGE_curl=y
# CONFIG_PACKAGE_dnsmasq is not set
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_dnsmasq_full_auth=y
CONFIG_PACKAGE_dnsmasq_full_conntrack=y
CONFIG_PACKAGE_dnsmasq_full_dhcp=y
CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
CONFIG_PACKAGE_dnsmasq_full_dnssec=y
CONFIG_PACKAGE_dnsmasq_full_ipset=y
CONFIG_PACKAGE_dnsmasq_full_nftset=y
CONFIG_PACKAGE_dnsmasq_full_noid=y
CONFIG_PACKAGE_dnsmasq_full_tftp=y
# CONFIG_PACKAGE_dropbear is not set
CONFIG_PACKAGE_git=y
CONFIG_PACKAGE_git-http=y
CONFIG_PACKAGE_gzip=y
CONFIG_PACKAGE_haproxy=y
CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_hysteria=y
CONFIG_PACKAGE_iftop=y
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_iperf3-ssl=y
CONFIG_PACKAGE_ipset=y
CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
CONFIG_PACKAGE_iptables-mod-iprange=y
CONFIG_PACKAGE_iptables-mod-socket=y
CONFIG_PACKAGE_iptables-mod-tproxy=y
CONFIG_PACKAGE_iptables-nft=y
CONFIG_PACKAGE_iptables-zz-legacy=y
CONFIG_PACKAGE_kmod-crypto-aead=y
CONFIG_PACKAGE_kmod-crypto-ccm=y
CONFIG_PACKAGE_kmod-crypto-cmac=y
CONFIG_PACKAGE_kmod-crypto-ctr=y
CONFIG_PACKAGE_kmod-crypto-gcm=y
CONFIG_PACKAGE_kmod-crypto-gf128=y
CONFIG_PACKAGE_kmod-crypto-ghash=y
CONFIG_PACKAGE_kmod-crypto-hmac=y
CONFIG_PACKAGE_kmod-crypto-kpp=y
CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y
CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y
CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y
CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y
CONFIG_PACKAGE_kmod-crypto-manager=y
CONFIG_PACKAGE_kmod-crypto-null=y
CONFIG_PACKAGE_kmod-crypto-rng=y
CONFIG_PACKAGE_kmod-crypto-seqiv=y
CONFIG_PACKAGE_kmod-crypto-sha256=y
CONFIG_PACKAGE_kmod-crypto-sha512=y
CONFIG_PACKAGE_kmod-ipt-conntrack=y
CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-iprange=y
CONFIG_PACKAGE_kmod-ipt-ipset=y
CONFIG_PACKAGE_kmod-ipt-nat=y
CONFIG_PACKAGE_kmod-ipt-socket=y
CONFIG_PACKAGE_kmod-ipt-tproxy=y
CONFIG_PACKAGE_kmod-mac80211=y
CONFIG_PACKAGE_kmod-mt76=y
CONFIG_PACKAGE_kmod-mt76-connac=y
CONFIG_PACKAGE_kmod-mt76-core=y
CONFIG_PACKAGE_kmod-mt76-usb=y
CONFIG_PACKAGE_kmod-mt7603=y
CONFIG_PACKAGE_kmod-mt76x02-common=y
CONFIG_PACKAGE_kmod-mt76x2=y
CONFIG_PACKAGE_kmod-mt76x2-common=y
CONFIG_PACKAGE_kmod-mt7921-common=y
CONFIG_PACKAGE_kmod-mt7921-firmware=y
CONFIG_PACKAGE_kmod-mt7921u=y
CONFIG_PACKAGE_kmod-nf-conncount=y
CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-socket=y
CONFIG_PACKAGE_kmod-nft-compat=y
CONFIG_PACKAGE_kmod-tcp-bbr=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_kmod-udptunnel4=y
CONFIG_PACKAGE_kmod-udptunnel6=y
CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=y
CONFIG_PACKAGE_kmod-usb-net-rndis=y
CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
CONFIG_PACKAGE_kmod-wireguard=y
CONFIG_PACKAGE_libatomic=y
CONFIG_PACKAGE_libbpf=y
CONFIG_PACKAGE_libbz2=y
CONFIG_PACKAGE_libcap=y
CONFIG_PACKAGE_libcares=y
CONFIG_PACKAGE_libcbor=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libelf=y
CONFIG_PACKAGE_libev=y
CONFIG_PACKAGE_libevdev=y
CONFIG_PACKAGE_libfdisk=y
CONFIG_PACKAGE_libffi=y
CONFIG_PACKAGE_libfido2=y
CONFIG_PACKAGE_libgdbm=y
CONFIG_PACKAGE_libgmp=y
CONFIG_PACKAGE_libip4tc=y
CONFIG_PACKAGE_libip6tc=y
CONFIG_PACKAGE_libipset=y
CONFIG_PACKAGE_libiptext=y
CONFIG_PACKAGE_libiptext-nft=y
CONFIG_PACKAGE_libiptext6=y
CONFIG_PACKAGE_libltdl=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblua5.3=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_liblz4=y
CONFIG_PACKAGE_liblzma=y
CONFIG_PACKAGE_libminiupnpc=y
CONFIG_PACKAGE_libmount=y
CONFIG_PACKAGE_libnatpmp=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnetfilter-conntrack=y
CONFIG_PACKAGE_libnettle=y
CONFIG_PACKAGE_libnfnetlink=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_libpcre=y
CONFIG_PACKAGE_libpython3=y
CONFIG_PACKAGE_libqrencode=y
CONFIG_PACKAGE_libreadline=y
CONFIG_PACKAGE_libsodium=y
CONFIG_PACKAGE_libsqlite3=y
CONFIG_PACKAGE_libssh2=y
CONFIG_PACKAGE_libstdcpp=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libuci-lua=y
CONFIG_PACKAGE_libudev-zero=y
CONFIG_PACKAGE_libusb-1.0=y
CONFIG_PACKAGE_libustream-mbedtls=m
CONFIG_PACKAGE_libustream-openssl=y
CONFIG_PACKAGE_libuv=y
CONFIG_PACKAGE_libwebsockets-full=y
CONFIG_PACKAGE_libxtables=y
CONFIG_PACKAGE_libzstd=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-acl=y
CONFIG_PACKAGE_luci-app-acme=y
# CONFIG_PACKAGE_luci-app-adguardhome_INCLUDE_binary is not set
# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_ShadowsocksR_Libev_Client is not set
# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_ShadowsocksR_Libev_Server is not set
# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Shadowsocks_Libev_Client is not set
# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Shadowsocks_Libev_Server is not set
# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Simple_Obfs is not set
# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Socks_Server is not set
# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Trojan is not set
# CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Xray is not set
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-app-passwall2=y
CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Hysteria=y
CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_NaiveProxy=y
# CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_ShadowsocksR_Libev_Client is not set
CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Libev_Server=y
CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Rust_Server=y
# CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Simple_Obfs is not set
CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_V2ray=y
# CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_V2ray_Plugin is not set
CONFIG_PACKAGE_luci-app-passwall2_Transparent_Proxy_Iptables-nft=y
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Haproxy is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray is not set
# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ChinaDNS_NG is not set
# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Client is not set
# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Simple_Obfs is not set
CONFIG_PACKAGE_luci-app-ttyd=y
CONFIG_PACKAGE_luci-app-uhttpd=y
# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Hysteria is not set
# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_ShadowsocksR_Libev_Server is not set
# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Trojan is not set
# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Xray is not set
# CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Xray_plugin is not set
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-light=y
CONFIG_PACKAGE_luci-lua-runtime=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-proto-wireguard=y
CONFIG_PACKAGE_luci-ssl-openssl=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_lz4=y
CONFIG_PACKAGE_naiveproxy=y
CONFIG_PACKAGE_ncat-full=y
CONFIG_PACKAGE_nmap-full=y
CONFIG_PACKAGE_ntpclient=y
CONFIG_PACKAGE_openssh-client=y
CONFIG_PACKAGE_openssh-client-utils=y
CONFIG_PACKAGE_openssh-keygen=y
CONFIG_PACKAGE_openssh-server=y
CONFIG_PACKAGE_openssh-sftp-client=y
CONFIG_PACKAGE_openssh-sftp-server=y
CONFIG_PACKAGE_openssl-util=y
CONFIG_PACKAGE_python3=y
CONFIG_PACKAGE_python3-asyncio=y
CONFIG_PACKAGE_python3-base=y
CONFIG_PACKAGE_python3-certifi=y
CONFIG_PACKAGE_python3-cgi=y
CONFIG_PACKAGE_python3-cgitb=y
CONFIG_PACKAGE_python3-chardet=y
CONFIG_PACKAGE_python3-codecs=y
CONFIG_PACKAGE_python3-ctypes=y
CONFIG_PACKAGE_python3-dbm=y
CONFIG_PACKAGE_python3-decimal=y
CONFIG_PACKAGE_python3-distutils=y
CONFIG_PACKAGE_python3-email=y
CONFIG_PACKAGE_python3-idna=y
CONFIG_PACKAGE_python3-light=y
CONFIG_PACKAGE_python3-logging=y
CONFIG_PACKAGE_python3-lzma=y
CONFIG_PACKAGE_python3-multiprocessing=y
CONFIG_PACKAGE_python3-ncurses=y
CONFIG_PACKAGE_python3-openssl=y
CONFIG_PACKAGE_python3-pydoc=y
CONFIG_PACKAGE_python3-readline=y
CONFIG_PACKAGE_python3-requests=y
CONFIG_PACKAGE_python3-sqlite3=y
CONFIG_PACKAGE_python3-unittest=y
CONFIG_PACKAGE_python3-urllib=y
CONFIG_PACKAGE_python3-urllib3=y
CONFIG_PACKAGE_python3-uuid=y
CONFIG_PACKAGE_python3-xml=y
CONFIG_PACKAGE_qrencode=y
CONFIG_PACKAGE_r8152-firmware=y
CONFIG_PACKAGE_resize2fs=y
CONFIG_PACKAGE_resolveip=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-rrdns=y
CONFIG_PACKAGE_rpcd-mod-ucode=y
CONFIG_PACKAGE_shadowsocks-libev-config=y
CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
CONFIG_PACKAGE_shadowsocks-libev-ss-server=y
CONFIG_PACKAGE_shadowsocks-rust-sslocal=y
CONFIG_PACKAGE_shadowsocks-rust-ssserver=y
CONFIG_PACKAGE_socat=y
CONFIG_PACKAGE_tcpdump=y
CONFIG_PACKAGE_tcping=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_ttyd=y
CONFIG_PACKAGE_ucode-mod-html=y
CONFIG_PACKAGE_ucode-mod-lua=y
CONFIG_PACKAGE_ucode-mod-math=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_PACKAGE_unzip=y
CONFIG_PACKAGE_usbutils=y
CONFIG_PACKAGE_v2ray-core=y
CONFIG_PACKAGE_v2ray-geoip=y
CONFIG_PACKAGE_v2ray-geosite=y
CONFIG_PACKAGE_v2ray-plugin=y
CONFIG_PACKAGE_vim-fuller=y
CONFIG_PACKAGE_wget-ssl=y
CONFIG_PACKAGE_wireguard-tools=y
CONFIG_PACKAGE_xray-core=y
CONFIG_PACKAGE_xtables-legacy=y
CONFIG_PACKAGE_xtables-nft=y
CONFIG_PACKAGE_xz-utils=y
CONFIG_PACKAGE_zerotier=y
CONFIG_PACKAGE_zlib=y
CONFIG_PACKAGE_zstd=y
CONFIG_PREINITOPT=y
CONFIG_SQLITE3_COLUMN_METADATA=y
CONFIG_SQLITE3_DYNAMIC_EXTENSIONS=y
CONFIG_SQLITE3_FTS3=y
CONFIG_SQLITE3_FTS4=y
CONFIG_SQLITE3_FTS5=y
CONFIG_SQLITE3_RTREE=y
CONFIG_TARGET_PREINIT_BROADCAST="192.168.0.255"
CONFIG_TARGET_PREINIT_IFNAME="br-lan"
CONFIG_TARGET_PREINIT_IP="192.168.0.2"
CONFIG_TARGET_ROOTFS_PARTSIZE=2048
# CONFIG_TARGET_ROOTFS_SQUASHFS is not set
CONFIG_WPA_MBO_SUPPORT=y
CONFIG_ZSTD_OPTIMIZE_O3=y
# CONFIG_OPENSSL_WITH_IDEA is not set
# CONFIG_OPENSSL_WITH_MDC2 is not set
# CONFIG_OPENSSL_WITH_SEED is not set
# CONFIG_OPENSSL_WITH_WHIRLPOOL is not set
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by dhewg**
This fixes the "vendor request failed" errors on at least mt7921u, which were introduced with 304423a4, see #12661.

Notes:
I didn't hunt down which exact hostapd patch fixes the issue, but whatever the problem is, without this enabling mt7921u deteriorates the whole box. It looks like mt76 tries something in a loop with interrupts disabed, because that long hang causes e.g. a ppp connection to disconnect. Maybe that can/should be improved in the mt76 error handling?

Removed, merged upstream:
- 170-wpa_supplicant-fix-compiling-without-IEEE8021X_EAPOL.patch

Manually refreshed:
- 040-mesh-allow-processing-authentication-frames-in-block.patch
- 600-ubus_support.patch
- 761-shared_das_port.patch

Fixes: #12661
Fixes: 304423a4 "hostapd: update to 2023-03-29"

cc @nbd168 @PolynomialDivision

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Just some nitpicking: You put the commit message of the fixes tag into `(" ... ")`?

Thanks a lot for looking into this. I see no reason not to update it. It would be good if we also get this to 23.05, or instead we find the commit that fixes it and than backport it. cc @hauke

**Comment by dhewg** [comment]
FWIW, if I make said mt76 error loop tighter, the ppp disconnect doesn't happen anymore:
```
+diff --git a/usb.c b/usb.c
+index 5e5c7bf5..c7b24ac3 100644
+--- a/usb.c
++++ b/usb.c
+@@ -8,8 +8,8 @@
+ #include "usb_trace.h"
+ #include "dma.h"
+ 
+-#define MT_VEND_REQ_MAX_RETRY	10
+-#define MT_VEND_REQ_TOUT_MS	300
++#define MT_VEND_REQ_MAX_RETRY	3
++#define MT_VEND_REQ_TOUT_MS	250
+ 
+ static bool disable_usb_sg;
+ module_param_named(disable_usb_sg, disable_usb_sg, bool, 0644);
```

**Comment by dhewg** [comment]
Guesswork, but the actual fix might be
https://w1.fi/cgit/hostap/commit/?id=f8931fcbafc8889ef96615593d26964cb60910c3
since we had `phy0-ap0: failed to set key (1, ff:ff:ff:ff:ff:ff) to hardware (-110)` in the logs

**Comment by PolynomialDivision** [comment]
@dhewg Can you test?

**Comment by dhewg** [comment]
I could, but do we care? I mean, is there a reason to not bump the package? The top hostapd commit is still from 06/22, so it seems to have settled a bit, which is always a nice indicator

**Comment by PolynomialDivision** [comment]
I am unsure if we can backport hostapd updates to 23.05. However, it is still in rc state so maybe it is possible. That's why I pinged @hauke ;) If that's not possible we can backport the commit as patch.

**Comment by PolynomialDivision** [comment]
Merged in https://github.com/openwrt/openwrt/commit/cd804c1ebb34c9740f8ad9fe393a81f3efb7b009

**Comment by dhewg** [comment]
That was quick, thanks!

**Pull request closed without merging**
