### PR TITLE
kernel: bump 5.4 to 5.4.79

### PR DESCRIPTION
**Pull request by graysky2**
Manually rebased patches:
```
  ath79/patches-5.4/910-unaligned_access_hacks.patch
  bcm27xx/patches-5.4/950-0135-spi-spi-bcm2835-Disable-forced-software-CS.patch
  bcm27xx/patches-5.4/950-0414-SQUASH-Fix-spi-driver-compiler-warnings.patch
  ipq806x/patches-5.4/093-4-v5.8-ipq806x-PCI-qcom-Use-bulk-clk-api-and-assert-on-error.patch
```
Removed since could be reverse-applied by quilt and found to be included upstream:
```
  ipq806x/patches-5.4/096-PCI-qcom-Make-sure-PCIe-is-reset-before-init-for-rev.patch
```
All modifications made by `update_kernel.sh`

Build system: x86_64
Build-tested: ipq806x/R7800, ath79/generic, bcm27xx/bcm2711
Run-tested: ipq806x/R7800

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by graysky2** [comment]
This should be considered WIP due to https://github.com/graysky2/openwrt/commit/6ae812749b2ba63aea3f58d08608cd7782a1c65f#commitcomment-44344144

**Comment by adschm** [comment]
> This should be considered WIP due to [graysky2@6ae8127#commitcomment-44344144](https://github.com/graysky2/openwrt/commit/6ae812749b2ba63aea3f58d08608cd7782a1c65f#commitcomment-44344144)

Or, with one link less to follow: ;-)

The kernel bump breaks xtables-addons, which is reported/discussed here:
https://github.com/openwrt/packages/issues/13947

**Comment by neheb** [comment]
Is xtables-addons that important?

**Comment by adschm** [comment]
> Is xtables-addons that important?

It's selected by default when using buildbot settings, so local builds fail (I'm not sure what actual SDK build at buildbots will do).

**Comment by neheb** [comment]
I ask as it's in the packages feed and not here.

**Comment by adschm** [comment]
The blocker should be gone, xtables-addons has been updated.

**Comment by graysky2** [comment]
> The blocker should be gone, xtables-addons has been updated.

I updated the package feed and tried building for ath79/generic but got errors:
```
...
 make[3] -C feeds/packages/lang/perl-text-csv_xs compile
 make[3] -C feeds/telephony/net/rtpengine compile
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/scratch/union/include/toplevel.mk:242: world] Error 1
```

[Here](https://gist.github.com/graysky2/025468e0ee55899c42725aeaa82a5b30) is a complete `make -j9 V=s` for review.

**Comment by adschm** [comment]
Same problem, different package:
```
/scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c: In function 'send_proxy_packet4':
/scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c:3355:42: error: passing argument 2 of 'ip_route_me_harder' from incompatible pointer type [-Werror=incompatible-pointer-types]
  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))
                                          ^~~
In file included from ./include/uapi/linux/netfilter_ipv4/ip_tables.h:22,
                 from ./include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c:25:
./include/linux/netfilter_ipv4.h:19:54: note: expected 'struct sock *' but argument is of type 'struct sk_buff *'
 int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
                                         ~~~~~~~~~~~~~^~
/scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c:3355:6: error: too few arguments to function 'ip_route_me_harder'
  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))
      ^~~~~~~~~~~~~~~~~~
In file included from ./include/uapi/linux/netfilter_ipv4/ip_tables.h:22,
                 from ./include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c:25:
./include/linux/netfilter_ipv4.h:19:5: note: declared here
 int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
     ^~~~~~~~~~~~~~~~~~
/scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c: In function 'send_proxy_packet6':
/scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c:3451:43: error: passing argument 2 of 'ip6_route_me_harder' from incompatible pointer type [-Werror=incompatible-pointer-types]
  if (ip6_route_me_harder(par->state->net, skb))
                                           ^~~
In file included from /scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c:27:
./include/linux/netfilter_ipv6.h:146:55: note: expected 'struct sock *' but argument is of type 'struct sk_buff *'
 int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);
                                          ~~~~~~~~~~~~~^~
/scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c:3451:6: error: too few arguments to function 'ip6_route_me_harder'
  if (ip6_route_me_harder(par->state->net, skb))
      ^~~~~~~~~~~~~~~~~~~
In file included from /scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.c:27:
./include/linux/netfilter_ipv6.h:146:5: note: declared here
 int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);
     ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:266: /scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module/xt_RTPENGINE.o] Error 1
make[5]: *** [Makefile:1729: /scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module] Error 2
make[5]: Leaving directory '/scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-5.4.79'
make[4]: *** [Makefile:34: modules] Error 2
make[4]: Leaving directory '/scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/kernel-module'
make[3]: *** [Makefile:267: /scratch/union/build_dir/target-mips_24kc_musl/linux-ath79_generic/rtpengine-no-transcode/rtpengine-mr8.5.2.1/.built] Error 2
make[3]: Leaving directory '/scratch/union/feeds/telephony/net/rtpengine'
time: package/feeds/telephony/rtpengine/no-transcode/compile#1.39#0.39#3.39
make[2]: *** [package/Makefile:114: package/feeds/telephony/rtpengine/compile] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by adschm** [comment]
Filed:

https://github.com/openwrt/telephony/issues/590

**Comment by micmac1** [comment]
rtpengine should be good now. So all blockers are gone now I hope.

**Comment by anomeome** [comment]
compile / test : mvebu / mamba, rango

**Comment by graysky2** [comment]
@adschm - I just updated the commit confirming that I built ath79/generic without error.  However, I was unable to build bcm27xx/bcm2711.

```
...
 make[3] -C feeds/packages/libs/expat host-compile
 make[2] buildinfo
 make[3] diffconfig buildversion feedsversion
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/scratch/union/include/toplevel.mk:242: world] Error 1
```

Currently running `make -j9 V=s` and will update this post when it finishes.

**Comment by graysky2** [comment]
@adschm - I just updated the commit confirming that both ath79/generic and bcm27xx/bcm2711 built without error.

**Comment by adschm** [comment]
Thanks, will merge it during the day.

**Pull request closed without merging**
