### PR TITLE
wolfssl: reorganized build options

### PR DESCRIPTION
**Pull request by cotequeiroz**
Package Maintainer: @commodo 
Compile & Run tested: brcm47xx/mipsel & ramips/mipsel

Removed options that can't be turned off because we're building with `--enable-stunnel`, some of which affected hostpad's `Config.in`.
Adjusted the title of OCSP option, as OCSP itself can't be turned off, only the stapling part is selectable.
Fixed poly1035 build.   By the way, any reason to split up chacha20 and poly1305?  If not, I would merge them into a single option.
Mark options turned on when wpad support is selected.
Add building with TLS v1.0 support as an option.

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

### CODE REVIEW

**Comment by commodo** [comment]
hey
atm, there is this PR https://github.com/openwrt/openwrt/pull/1008 which tries to add a bit more flexibility and enhance the option coverage of wolfssl options;

@dangowrt will also take a look on that change
but feel free to also take a look and see if and how that fits your needs

thanks
Alex

**Comment by commodo** [comment]
let's address 18.06 with your change
and go in master with my PR :)

**Comment by ldir-EDB0** [comment]
Since PR #1008 is closed, what is the resultant status on this PR?

**Comment by commodo** [comment]
It seems we forgot about this.

As I said initially: this looks fine for 18.06
I guess, this should have been picked up by someone with merge rights.

In the meantime I’ve withdrawn from maintaining wolfssl.

**Comment by ldir-EDB0** [comment]
Is there a reason why this shouldn't go in master?  It would be unusual to have a fix in 18.06 not in master...what happens when 19.x is branched ;-)

**Comment by commodo** [comment]
I guess we can move this to master now.

**Pull request closed without merging**
