### PR TITLE
ramips: fix switch config for ZyXEL Keenetic Viva

### PR DESCRIPTION
**Pull request by some-nickname**
Port 7 of the RTL8367B is not supported by the current driver.
However, the switch is also connected to the CPU via port 6.
Use extif1 to connect to port 5 of the CPU's Ethernet controller.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Your PR has formal issues:
- Please adjust the commit titles to be more specific (having the same title for both commits indicates that it is not specific enough :-) )
- Add Signed-off-by with real name at the end of the commit message for both commits.

**Comment by adrianschmutzler** [comment]
@981213 Maybe you can comment on the content here.

**Comment by 981213** [comment]
So we got a device support which is added in 2016, fixed once in 2018 and still broken in 2020...

@some-nickname Would you mind to test whether this patch added a proper extif2 support?
https://patchwork.ozlabs.org/patch/1147465/

If it fixes the problem I'll just fix the style problem in that patch and merge it instead.

**Comment by some-nickname** [comment]
@981213 

> Would you mind to test whether this patch added a proper extif2 support?
https://patchwork.ozlabs.org/patch/1147465/

I tested this patch and it works fine.
Both extif1 and extif2 can be used as CPU ports:
```
root@OpenWrt:~# swconfig dev mt7620 port 4 show; swconfig dev mt7620 port 5 show
Port 4:
        mib: Port 4 MIB counters
TxGPC      : 304
TxBOC      : 0
TxGOC      : 37349
TxEPC      : 0
RxGPC      : 155
RxBOC      : 0
RxGOC      : 15254
RxEPC1     : 0
RxEPC2     : 0

        pvid: 0
        link: port:4 link:up speed:1000baseT full-duplex 
Port 5:
        mib: Port 5 MIB counters
TxGPC      : 4848
TxBOC      : 0
TxGOC      : 542167
TxEPC      : 0
RxGPC      : 5378
RxBOC      : 0
RxGOC      : 568611
RxEPC1     : 0
RxEPC2     : 0

        pvid: 0
        link: port:5 link:up speed:1000baseT full-duplex 
```

**Comment by 981213** [comment]
@some-nickname 
Could you test the first two commit in rtl-extif2 branch of my staging tree?
https://git.openwrt.org/?p=openwrt/staging/981213.git;a=shortlog;h=refs/heads/rtl-extif2

Please test both extif1 and extif2 configuration.
Thanks in advance!

**Comment by some-nickname** [comment]
@981213

> Could you test the first two commit in rtl-extif2 branch of my staging tree?

Tested.
extif1 works, extif2 does not work.

Test config 2:
```
cpu_port = <7>;
realtek,extif2 = <1 0 1 1 1 1 1 1 2>;
```
Result 2:
```
# logread | grep 8367 ; swconfig dev switch1 port 7 show | grep link
Fri Feb 28 00:05:19 2020 kern.info kernel: [   15.110612] rtl8367b rtl8367rb: using MDIO bus 'mdio'
Fri Feb 28 00:05:19 2020 kern.info kernel: [   15.121702] rtl8367b rtl8367rb: RTL8367RB chip found
Fri Feb 28 00:05:19 2020 kern.info kernel: [   16.488428] libphy: rtl8367rb: probed
        link: port:7 link:down
```
It looks like the switch works, but the data link is down.

Original patch https://patchwork.ozlabs.org/patch/1147465/ :
```
-#define RTL8367B_DI_FORCE_REG(_x)		(0x1310 + (_x))
+#define RTL8367B_DI_FORCE_REG(_x)		((_x) == 2 ? 0x13c4 : 0x1310 + (_x))
```
Is it no longer required?
With this fix, the driver works properly.

**Comment by 981213** [comment]
> Original patch https://patchwork.ozlabs.org/patch/1147465/ :
> 
> ```
> -#define RTL8367B_DI_FORCE_REG(_x)		(0x1310 + (_x))
> +#define RTL8367B_DI_FORCE_REG(_x)		((_x) == 2 ? 0x13c4 : 0x1310 + (_x))
> ```
> 
> Is it no longer required?
> With this fix, the driver works properly.

The original patch doesn't apply cleanly and I have to manually modify rtl8367b.c. I must have overlooked this change.
I've added this change back and pushed final commit to my staging tree:
https://git.openwrt.org/?p=openwrt/staging/981213.git;a=summary

Thanks again for testing my commits!

**Pull request closed without merging**
