### PR TITLE
[RFT] ramips: add support for Netgear EX6120 (and adjust EX6130/EX3700)

### PR DESCRIPTION
**Pull request by adschm**
Since this device seems cursed and I have reached the point where I don't think explaining changes will help anymore, I've put together a proper patch for adding EX6120 myself.

This needs to be tested on device, as I don't have it.

Despite, I'm adjusting the boot LED color for EX6130/EX3700 as indicated by the manual. For that, a test is not mandatory, but would be nice.

@ASerbinski @Bzzz @playya

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
@Bzzz I've built images for you here:
https://www.adrianschmutzler.net/upload/ex6120.zip

These are just default configuration, so no LuCI, similar to the snapshots for master.

**Comment by ASerbinski** [comment]
Thanks.
If somebody is able to test it working, please add my sign-off to it.
If nobody is able to test it, I'll have time on the 29th to test it.

**Comment by Bzzz** [comment]
uci WiFi setup from scratch works, connects fine on 2.4GHz and 5GHz, amber boot LED works as expected.

Status LEDs are off except for the power LED - no activity visible on both radios.
`/sys/class/leds/` still has unusable entries and `/etc/config/system` is still devoid of default triggers. triggers can be added manually via uci, e.g. `echo "default-on" > /sys/class/leds/ex6120\:red\:device/trigger` activates the red device LED

**Comment by adrianschmutzler** [comment]
Merged, closed.

**Pull request closed without merging**
