### PR TITLE
ipq40xx: use upstreamed SDI disable support

### PR DESCRIPTION
**Pull request by robimarko**
Google WiFi board has what seems as debug version of TZ/QSEE and it is always enabling SDI (Secure Debug Image) and in order to do a regular reboot it must be disabled, as otherwise you are stuck in a debug state where you are supposed to extract debug logs via QCA tooling which is not helpfull at all for regular users.

So, instead of using our downstream version to disable SDI lets use the version that was merged upstream and relies on a boolean property in the SCM node instead of checking the compatible.

### CODE REVIEW

**Comment by robimarko** [comment]
@computersforpeace Can you give this a runtime test?

**Comment by computersforpeace** [comment]
> @computersforpeace Can you give this a runtime test?

Works for me, thanks.

Tested-by: Brian Norris <computersforpeace@gmail.com>

**Comment by Ansuel** [comment]
@robimarko can you add the tag and then i will merge?

**Comment by robimarko** [comment]
Done

**Pull request merged**
