### PR TITLE
[21.02] kernel: backport three SFP patches mostly for Ubiquiti

### PR DESCRIPTION
**Pull request by BKPepe**
- The first commit fixes EEPROM in Cotsworks SFP modules to be able detect
them. The second one improves SFP handling.

- Refresh other patches

### CODE REVIEW

**Comment by BKPepe** [comment]
Backported these two patches from Linux kernel. They are already part of kernel 5.10. Nice to have for kernel 5.4.

- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=624407d2cf14 ("net: sfp: cope with SFPs that set both LOS normal and LOS inverted")

- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b18432c5a49c ("net: phy: sfp: Cotsworks SFF module EEPROM fixup")

**Comment by BKPepe** [comment]
I will also add two more patches from kernel for GPON modules.

**Comment by BKPepe** [comment]
Something about these patches. These are already part of LTS kernel 5.10 and it would be nice to have them in OpenWrt 21.02 release.

Patches:
- target/linux/generic/backport-5.4/768-net-sfp-cope-with-SFPs-that-set-both-LOS-normal-and-.patch
Backport from: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/phy/sfp.c?h=v5.10.92&id=9d9facd32d89f737605c7135cee7f8189959d098

- target/linux/generic/pending-5.4/771-net-sfp-add-mode-quirk-Ubiquiti-UFiber-Instant.patch
Backport from: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/phy/sfp.c?h=v5.10.92&id=6c15e41dc4ac38ad0d4a5790ebdf582c98f88d74

- target/linux/generic/pending-5.4/772-net-sfp-relax-bitrate-devided-check.patch
Backport from: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/phy/sfp-bus.c?h=v5.10.92&id=2a60ab2dab3df84e6d6690ac7a23e1d921b25a36

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
