### PR TITLE
mpc85xx: remove 5.15, switch to 6.1 and add 6.6 kernel as testing

### PR DESCRIPTION
**Pull request by CHKDSK88**
This PR realize three steps:
  - switch to 6.1 kernel
  - remove 5.15 support
  - add 6.6 kernel as testing version

It's simple target without many target-specified patches.

### CODE REVIEW

**Comment by neheb** [comment]
git grep shows swconfig being used here. I can't tell if it's for b53 or REALTEK_PHY.

**Comment by CHKDSK88** [comment]
@neheb 
> git grep shows swconfig being used here. I can't tell if it's for b53 or REALTEK_PHY.

Ocedo Panda uses swconfig for b53: https://github.com/openwrt/openwrt/commit/b368373fab45f31963cd2bc1c6ab90e0a577e611

**Comment by neheb** [comment]
interesting.

There's a DSA driver for it. I guess @blocktrron needs to do the conversion since he has the hardware.

**Comment by CHKDSK88** [comment]
> interesting.
> 
> There's a DSA driver for it. I guess @blocktrron needs to do the conversion since he has the hardware.
> 
> edit: what about CONFIG_REALTEK_PHY?

It was introduced by 97e4311fca73d064d17065e7844699aa777cb157

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
