### PR TITLE
dropbear: bump to 2020.79

### PR DESCRIPTION
**Pull request by rockdrilla**
dropbear: bump to 2020.79
- drop patches (applied upstream):
  * 010-backport-change-address-logging.patch
  * 020-backport-ed25519-support.patch
  * 021-backport-chacha20-poly1305-support.patch
- backport patches:
  * 010-backport-disable-toom-and-karatsuba.patch:
    reduce dropbear binary size (about ~8Kb).
- refresh patches.
- don't bother anymore with following config options
  because they are disabled in upstream too:
  * DROPBEAR_3DES
  * DROPBEAR_ENABLE_CBC_MODE
  * DROPBEAR_SHA1_96_HMAC
- explicitly disable DO_MOTD as it was before commit a1099ed:
  upstream has (accidentally) switched it to 0 in release 2019.77,
  but reverted back in release 2020.79.

### CODE REVIEW

**Comment by rockdrilla** [comment]
Force-pushing branch due to missing disable for DO_MOTD: it was initially disabled in 120-openwrt_options.patch before a1099edf32 and then option was absent from configuration.
This was inspired by upstream changes defaulting DO_MOTD to 0 due to rework of option handling,
but then mkj/dropbear@002b79e2f9 reverted this accidental change, so we should mention it again.

**Comment by hauke** [comment]
Please mention in the commit message why you removed 
* DROPBEAR_3DES 
* DROPBEAR_ENABLE_CBC_MODE
* DROPBEAR_SHA1_96_HMAC
and added
* DO_MOTD
like you did in the pull request description.

Where did you test it?
How much bigger is the binary now? Please provide some size comparision numbers for MIPS or ARM.

**Comment by themiron** [comment]
@rockdrilla @hauke fyi, binary size increase is ~11Kb (mips-24kc-musl) due libtommath update.
please consider upstream commit https://github.com/mkj/dropbear/commit/10e119f638b3f5f1b9b7e3e3df8a011f2671c6d2
I think there's more space for further size-optimizations

**Comment by rockdrilla** [comment]
Compile- and run-tested with mips_24kc_musl @ TP-Link Archer C7 v2.

Binary size (/usr/sbin/dropbear):

190K dropbear_2019.78-5
206K dropbear_2020.79-1
198K dropbear_2020.79-1 (with upstream commit  mkj/dropbear@10e119f638)

Package size:

 99K dropbear_2019.78-5_mips_24kc.ipk
105K dropbear_2020.79-1_mips_24kc.ipk
103K dropbear_2020.79-1_mips_24kc.ipk (with upstream commit  mkj/dropbear@10e119f638)

**Comment by dedeckeh** [comment]
@rockdrilla Can you squash the two commits into one commit as the backported patch is directly related to the dropbear update.

**Comment by rockdrilla** [comment]
@dedeckeh done.

**Comment by dedeckeh** [comment]
Pulled into my staging tree; thx

**Pull request closed without merging**
