### PR TITLE
kernel: add iscsi-initator support

### PR DESCRIPTION
**Pull request by lucize**
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

Kernel drivers needed for open-iscsi package https://github.com/openwrt/packages/pull/11831

### CODE REVIEW

**Comment by ynezz** [comment]
Missing commit description.

**Comment by lucize** [comment]
@ynezz fixed, don't know how I missed it!

**Comment by lucize** [comment]
@ynezz ping !

**Comment by lucize** [comment]
@adrianschmutzler how about this PR is just a basic kernel module

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by ynezz** [comment]
I've fixed one issue bbdd99619c714d338c14982913d3879f0a088c2d caused by this PR. There is one remaining http://buildbot.openwrt.org/master/images/builders/at91%2Fsama5/builds/451/steps/kmods/logs/stdio

**Comment by lucize** [comment]
on it

**Comment by ynezz** [comment]
Next one http://buildbot.openwrt.org/master/images/builders/mvebu%2Fcortexa9/builds/435

```
WARNING: Image file /builder/shared-workdir/build/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linksys_wrt1900ac-v1-kernel.bin is too big
```

This is probably not fixable easily. I'm wondering whether this iscsi stuff is worth this kernel increase, but I doubt that.

**Comment by adrianschmutzler** [comment]
Well, so much for cortexa9_tiny ...

Can we move stuff to modules for this target like we did for kirkwood here: https://github.com/openwrt/openwrt/pull/2979 ?

**Comment by lucize** [comment]
And I was thinking to add LIO ISCSI kernel driver :), from forum chat it seems that the target is problematic

**Comment by lucize** [comment]
I force pushed over this

**Comment by lucize** [comment]
don't know it there are mvebu devices booting from sata or raid, that could be added as a module, mmc I think it needs to stay, and also usb could be added as a module and we should be good with this

**Comment by lucize** [comment]
I made a compare build and I find strage that zImage is much larger than uncompressed

```
-rwxr-xr-x  1 build build 11722944 iul  8 23:08 vmlinux
-rwxr-xr-x  1 build build 11727936 iul  8 23:13 vmlinux
4992
-rwxr-xr-x  1 build build  3033400 iul  8 23:08 zImage
-rwxr-xr-x  1 build build  3047704 iul  8 23:13 zImage
14304
```

**Comment by lucize** [comment]
on second look I think we don't need the SCSI_LOWLEVEL option, but how will this go with default config that have them as SCSI_LOWLEVEL=y ?

**Pull request closed without merging**
