### PR TITLE
tools/zstd: update to 1.5.4

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Review by PolynomialDivision — APPROVED** [review]

**Comment by diizzyy** [comment]
fwiw, https://git.alpinelinux.org/aports/tree/main/zstd/APKBUILD#n55

**Review by dhewg — APPROVED** [review]

**Comment by dhewg** [comment]
> fwiw, https://git.alpinelinux.org/aports/tree/main/zstd/APKBUILD#n55

This host package is already build with meson

**Comment by diizzyy** [comment]
I was referring to the PGO part

**Comment by dhewg** [comment]
The same commit switched from make to meson too, and the comment mentions Makefile, so I assume that refers to that part? Maybe not, maybe both ;)

**Comment by eli-schwartz** [comment]
It's referring to the PGO -- but switching to Meson also made it easy to use PGO. :)

**Comment by neheb** [comment]
Beyond the scope of this PR. I assume it also won't work with old GCC as in Ubuntu 18.04.

**Pull request merged**
