### PR TITLE
[24.10] odhcp6c: update to Git HEAD (2024-09-25) 

### PR DESCRIPTION
**Pull request by try496**

### CODE REVIEW

**Comment by systemcrash** [comment]
Also, context: https://github.com/openwrt/luci/issues/7397
and https://github.com/openwrt/openwrt/pull/17013

**Comment by try496** [comment]
> Also, context: [openwrt/luci#7397](https://github.com/openwrt/luci/issues/7397) and #17013


Should I replace the line "Link:" with this one?

**Comment by Neustradamus** [comment]
@try496: It can be done for 23.05.x too?

Replaces:
- https://github.com/openwrt/openwrt/pull/17016

Linked to:
- https://github.com/openwrt/openwrt/pull/17013
- https://github.com/openwrt/odhcp6c/issues/92

**Comment by ynezz** [comment]
> @try496: It can be done for 23.05.x too?

Nope.

**Comment by ynezz** [comment]
Thanks, but I've already cherry-picked it via 9a09c54449

**Pull request closed without merging**
