### PR TITLE
kernel: backport support for Sercomm mtd partitions

### PR DESCRIPTION
**Pull request by csharper2005**
This set of commits backport support for Sercomm partition map from mtd-next and enables it for mt7621 target.

This is necessary for a wide range of devices that have dynamic partition map. Currently they use static partitioning. Sometimes it leads eeprom displacement, bootloops and other bugs. Some examples:

- [Netgear R6850: very low transmit power on 5GHz](https://forum.openwrt.org/t/netgear-r6850-very-low-transmit-power-on-5ghz/90984)
- [R6260 - Very low Tx power](https://forum.openwrt.org/t/r6260-very-low-tx-power/91530)
- [NETGEAR R6220 random MAC problem](https://forum.openwrt.org/t/netgear-r6220-random-mac-problem/129093)
- https://github.com/openwrt/openwrt/issues/7298
- https://github.com/openwrt/openwrt/issues/7668
- https://github.com/openwrt/openwrt/issues/8885
- https://github.com/openwrt/openwrt/pull/1304

These commits were originally part of https://github.com/openwrt/openwrt/pull/4195.
@Borromini [suggested](https://forum.openwrt.org/t/netgear-r6220-random-mac-problem/129093/12) to open a separate PR for the backport due to a wide scope of affected devices.

Next steps:
- Apply partition map parser to the each affected device.  [An example](https://github.com/openwrt/openwrt/pull/4195/commits/9ee22abe6a3c55c34615b194ad9943ae75433843)

### CODE REVIEW

**Comment by Borromini** [comment]
Cc'ing @ynezz and @mkresin who commented I'm the earlier patch set on Patchwork.

**Comment by csharper2005** [comment]
Backported patches have been refreshed with fix from Yang Yingliang https://lore.kernel.org/linux-mtd/20220617014008.851583-1-yangyingliang@huawei.com/

**Comment by rmilecki** [comment]
I started with applying your patch 28a42c8f64fd10cd724d34df2a22aaa08c08f669 ("kernel: backport support for Sercomm mtd partitions") but had too many issues with it.

1. It's said to be cherry-picked from commit 00a5095 which isn't commited anywhere
2. Added patch differs from mainline (`of_node_put()`)
3. It misses config updates which was **later** handled by 3577f8355195 ("kernel: add missing (disabled) MTD_SERCOMM_PARTS symbol") - I can't take patch that breaks something just to have it fixed later
4. It didn't refresh `ipq806x`
5. It broke applying patches (and compilation):
```
Applying /home/rmilecki/openwrt/openwrt-master-mt7621/target/linux/generic/pending-5.10/435-mtd-add-routerbootpart-parser-config.patch using plaintext: 
patching file drivers/mtd/parsers/Kconfig
Hunk #1 FAILED at 195.
1 out of 1 hunk FAILED -- saving rejects to file drivers/mtd/parsers/Kconfig.rej
patching file drivers/mtd/parsers/Makefile
Hunk #1 succeeded at 14 with fuzz 1 (offset 1 line).
Patch failed!  Please fix /home/rmilecki/openwrt/openwrt-master-mt7621/target/linux/generic/pending-5.10/435-mtd-add-routerbootpart-parser-config.patch!
```

I basically wasted half an hour trying to sort that out :( I gave up using this work at that point, sorry.

Please rebase / update if there is anything left to be commited that I missed.

**Comment by csharper2005** [comment]
@rmilecki thank you for the merging of the patch and detailed feedback! I've taken it into the account. And I'm incredible sorry for your time.
I rebased my device commit https://github.com/openwrt/openwrt/pull/4195 and tested both 5.10 and 5.15. All is ok.

@Borromini looks like the guys interested in fix for Netgears can start the testing and preparation of the fix commits.

I'm closing this PR if no one minds.

**Comment by rmilecki** [comment]
Thanks for verifying this pull request vs. my patch. While maybe not everything went smooth, I'm still extremely happy to have that parser upstreamed, great work!

**Pull request closed without merging**
