### PR TITLE
ipip6: add new package for IPIP6(RFC2473) support

### PR DESCRIPTION
**Pull request by missing233**
Add Generic Packet Tunneling in IPv6 Specification (RFC 2473) support.
Japan NTT V6 Plus fixed IP
[luci:#6873](https://github.com/openwrt/luci/pull/6873)

### CODE REVIEW

**Comment by musashino205** [comment]
Please use your real email address for ```Signed-off-by``` line in the commit message and [author field (```From: ```)](https://github.com/openwrt/openwrt/pull/14498.patch) of the commit.

**Comment by missing233** [comment]
> Please use your real email address for `Signed-off-by` line in the commit message and [author field (`From: `)](https://github.com/openwrt/openwrt/pull/14498.patch) of the commit.
> 
> https://openwrt.org/submitting-patches#submission_guidelines

Thank you for reviewing my pull request. I have updated my real email address. Please let me know if there's anything else needed from my side.

**Comment by musashino205** [comment]
The author field still needs to be updated.

```
$ git commit --amend --author="missing233 <ms@missing233.com>"
$ git push -f
```

And, "```ipip6: add new package for IPIP6(RFC2473) support```" might be preferable for the title.

**Comment by missing233** [comment]
> The author field still needs to be updated.
> 
> ```
> $ git commit --amend --author="missing233 <ms@missing233.com>"
> $ git push -f
> ```
> 
> And, "`ipip6: add new package for IPIP6(RFC2473) support`" might be preferable for the title.

 Thanks, I've made the modification.

**Comment by 981213** [comment]
Hi! Is it possible to integrate the support for this into the existing ipip protocol support? These IP tunnels seem to share a lot of options.
Also, you should use a (preferably real) name in Sign-off, instead of a nickname.

**Comment by missing233** [comment]
> Hi! Is it possible to integrate the support for this into the existing ipip protocol support? These IP tunnels seem to share a lot of options. Also, you should use a (preferably real) name in Sign-off, instead of a nickname.

Thank you for your feedback on my PR.
This ip4ip6 tunnel is more similar to ds-lite. Maybe we could integrate it with ds-lite?
For privacy reasons, I prefer not to use my real name in public contributions. Is there an alternative approach that would be acceptable for this project, such as using a pseudonym or initials?

**Comment by 981213** [comment]
> Thank you for your feedback on my PR.
> This ip4ip6 tunnel is more similar to ds-lite. Maybe we could integrate it with ds-lite?

Sure.

> For privacy reasons, I prefer not to use my real name in public contributions. Is there an alternative approach that would be acceptable for this project, such as using a pseudonym or initials?

From my understanding, a pseudonym is fine as long as you use it consistently across your contributions.
There's an explanation for "real name" in DCO here: https://github.com/cncf/foundation/blob/main/dco-guidelines.md

**Comment by missing233** [comment]
> > Thank you for your feedback on my PR.
> > This ip4ip6 tunnel is more similar to ds-lite. Maybe we could integrate it with ds-lite?
> 
> Sure.
> 
> > For privacy reasons, I prefer not to use my real name in public contributions. Is there an alternative approach that would be acceptable for this project, such as using a pseudonym or initials?
> 
> From my understanding, a pseudonym is fine as long as you use it consistently across your contributions. There's an explanation for "real name" in DCO here: https://github.com/cncf/foundation/blob/main/dco-guidelines.md


Thank you. I will reopen a PR later to make these modifications.

**Pull request closed without merging**
