### PR TITLE
[main] Update mac80211.sh so min_tx_power isn't on the same line if it's defined in config/wireless

### LINKED ISSUE #13007: min_tx_power and/or acs_exclude_dfs don't work properly
### Describe the bug

when you have both min_tx_power and acs_exclude_dfs as set options in an AP config, they share the same line, meaning either ACS is read or it isn't, and min tx isn't respected, because either it's being interpreted as the value for ACS or it's being ignored because there's a space delimiter between the hostapd conf file that is generated. when you have both like I will show here, you can get UNI I channels despite specifying a higher min Tx than UNI I (24 vs the 29 I am using here, which is 1 higher than DFS). The solution would be to add a line break or delimiter. I have given guidance on how to do this further on; I wrote this part last, in post, so although I'm being a bit thin on detail here it's cause I already wrote it below so read on please.

### OpenWrt version

snapshot 2nd latest to newest 

### OpenWrt target/subtarget

r23453-5af7d47cd7

### Device

various (issue isn't device dependent, it's universal)

### Image kind

Official downloaded image

### Steps to reproduce

in /etc/config/wireless try with option min_tx_power 29 and option acs_exclude_dfs 1 in wifi_device section

### Actual behaviour

cat /tmp/run/*f|grep min_
acs_exclude_dfs=1 min_tx_power=29

The ACS and the min are on the same line so if anything only the ACS takes effect. So you will get channel 40, 36, etc.

### Expected behaviour

You don't get the two parameters on the same line. Which currently you do and it's been this way for at least 6 months possibly ever since you added these options they have been broken like this. In effect you shouldn't be put on channel 36, 40, etc with this specific setup but you can be. The ACS line should have a line break after but it doesn't. So either ACS is read or it's not, but min is ignored for sure because min 29 would exclude the min 24 36, 40 etc.

### Additional info

Relevant code is in https://github.com/openwrt/openwrt/blob/master/package/kernel/mac80211/files/lib/netifd/wireless/mac80211.sh lines 141-150. What I suspect is happening is it's appending the option workout a line break or the normal way options are delimited in the shell file. I haven't looked really into it but that's the best I can explain it. See below:

cat /tmp/run/*f|grep -e min_ -e acs
min_tx_power=29                                                 acs_exclude_dfs=1
channel=acs_survey                                              acs_exclude_dfs=1 min_tx_power=29

Above I only showed some of the output, plus my config has "list hostapd_options 'min_tx_power=29 acs_exclude_dfs=1'". So clearly the line with both isn't my hostapd options. I have both the individual options and the hostapd options configured cause i was seeing if I could remove the hapd options. As you see the two options per line isn't my hapd options because my hapd options are in reverse order. Hapd options afaik are not added in reverse order and are always added separately whether you have them space delimited or separate list entry with any number of space delimiters.

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by ascendbeing**
See my recent bug report for context. This is 2nd pull of 2
This fixes https://github.com/openwrt/openwrt/issues/13007

### CODE REVIEW

**Comment by castiel652** [comment]
Please fix your commit format

**Comment by john-tho** [comment]
Thank you for identifying and fixing this.

> Please fix your commit format

See the OpenWrt wiki for the guide: https://openwrt.org/submitting-patches
For the short version, make the commit title and description look something like a previous commit to the same file (example: https://github.com/openwrt/openwrt/commit/d2d5aabdbb947443b0d5f75c3847754c7c38a117).

At the very least, you need
- A properly formatted commit title, something like:
  `hostapd: fix min_tx_power option`

- A commit description: Answer why is this change being made?
  At the end of your description, you can identify the OpenWrt issue that this change fixes:
  `Fixes: #13007`
  You can also identify (`git blame`) the commit which made the mistake, so that it is easier to see where this needs to be backported to, with a Fixes tag, just before your Signed-off-by: tag
  `Fixes: d2d5aabdbb94 ("hostapd: introduce min_tx_power option")`

- A Signed-off-by: tag, with your name and email address. This specifies that you authored this work, and agree with the rules of the project.

Generally, we want to get the change applied in main/master branch, then cherry pick that back to the older branches where required, so focus on the PR against the main branch first.

Cheers

**Comment by ascendbeing** [comment]
This fixes https://github.com/openwrt/openwrt/issues/13007

**Comment by john-tho** [comment]
> This fixes #13007

yup, put that in the commit message…

**Comment by danpawlik** [comment]
@ascendbeing whats the status?

**Comment by ascendbeing** [comment]
this is actually relevant to acs_exclude_dfs not min_tx_power; the problems show up when you use the former via an option rather than via hostapd_options; I will have to consult y'all's helpful comments and probably resubmit accurately and succinctly for consideration. sorry for getting this so wrong. to be clear, when you do min_tx_power whether via option or hostapd_options it's fine; acs_exclude_dfs is what's actually the problem to be solved

**Pull request closed without merging**
