### PR TITLE
device: add initial support for Linksys EA8300

### PR DESCRIPTION
**Pull request by Bunkerschild**
See https://openwrt.org/inbox/linksys/linksys_ea8300 for details.

Specs:
- SoC: Qualcomm IPQ4019
- CPU-Cores: 4x ARM Cortex A7
- CPU-Freq: 717 MHz
- Flash-Size: 256 MB
- Flash-Type: Macronix MX30LF2G18AC-TI
- RAM-Size: 256 MB
- RAM-Type: Nanya NT5CC128M16IP-DI

Changes to be committed:
	modified:   target/linux/ipq40xx/Makefile
	modified:   target/linux/ipq40xx/base-files/etc/board.d/02_network
	modified:   target/linux/ipq40xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
	new file:   target/linux/ipq40xx/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac
	new file:   target/linux/ipq40xx/base-files/etc/init.d/linksys_recovery
	new file:   target/linux/ipq40xx/base-files/lib/upgrade/linksys.sh
	modified:   target/linux/ipq40xx/base-files/lib/upgrade/platform.sh
	modified:   target/linux/ipq40xx/config-4.14
	new file:   target/linux/ipq40xx/files-4.14/arch/arm/boot/dts/qcom-ipq4019-bus.dtsi
	new file:   target/linux/ipq40xx/files-4.14/arch/arm/boot/dts/qcom-ipq4019-ea8300.dts
	new file:   target/linux/ipq40xx/files-4.14/arch/arm/boot/dts/qcom-ipq4019-ea8300.dtsi
	modified:   target/linux/ipq40xx/image/Makefile
	new file:   target/linux/ipq40xx/patches-4.14/855-ipq40xx-add-ess-resets.patch
	new file:   target/linux/ipq40xx/patches-4.14/856-ipq40xx-fix-mdio-driver-to-detect-ipq4019.patch
	modified:   target/linux/ipq40xx/patches-4.14/901-arm-boot-add-dts-files.patch
	new file:   target/linux/ipq40xx/patches-4.14/902-add-include-dt-bindings-msm-msm-bus-ids-h.patch
	new file:   target/linux/ipq40xx/patches-4.14/903-add-include-dt-bindings-msm-msm-bus-rule-ops-h.patch

Flash instruction:
Applying factory image via web-gui is currently impossible, due to Linksys signed firmware image checks.
Image can be applied via TFTP, using the serial console at JP1, analogue to Linksys EA8500.

Serial (JP1):
- PIN2: RX
- PIN3: TX
- PIN5: GND
- Parameters: 115200, 8N1

Signed-off-by: Oliver Welter <contact@verbotene.zone>

### CODE REVIEW

**Comment by robimarko** [comment]
Why are you reintroducing the bus dtsi?
Also,why are you making a custom dtsi for E8300 instead of pulling ipq4019 dtsi and making the necessary changes only in the E8300 dts.

Why are you making so many kernel config changes?

**Comment by VerboteneZone** [comment]
> Why are you reintroducing the bus dtsi? Also why...

I have tried this first, but there are many compatibillity issues, when using the existing files and you can't set some neccessary values. Also, getting the ipq4019 to work seemed to be impossible this way. I know that this is more a workaround than an usefull and clean solution, but first and important to me was, to get the EA8300 running, rather than cleaning up things (which can be done later) and make the other dtsi's compatible and check, whether they are working this way or not.

> Why are you making so many kernel config changes?

While doing the first builds, I ran into problems, because the kernel image size exceeded the given maximum. So I tried to make it a little smaller, while removing some debugging options. The rest of made changes are neccessary hardware stuff. Maybe there are some remnants from internal testing, but I thought it is a good idea to get the stuff into this branch, so some other people can help with development for this device and clean things up. I am relative new to this Project, so help with some stuff would be great.

**Comment by robimarko** [comment]
Well, I doubt that this will get merged in this state.
You are introducing dtsi that includes stuff like SD voltage controller and SDHCI node too.
Voltage controller does not even have the driver for it merged.

How come other devices work fine with the current ipq4019.dtsi?
You need to use that one and then override stuff in dts for the device if needed.

**Comment by Bunkerschild** [comment]
Sorry for that, as I said before, there are some remnants that I didnt see before. I will clean this up and try to change the dtsi. Hope that this will work. Closing the request, until cleanup is done.

**Pull request closed without merging**
