### PR TITLE
ath79: mikrotik: improvements for RB9xxG series

### PR DESCRIPTION
**Pull request by Leo-PL**
This series cleans up the support for RB9xxG series. Primary purpose is to add explicit support for RB911G-2HPnD, RB911G-5HPnD and RB911G-5HPacD.
First patch adds alternative name for RB912UAG-5HPnD, keeping the existing mikrotik,rb912uag-2hpnd to avoid the hassle of renaming devices and changing compatible strings.
Second patch adds support for 802.11n versions of RB911G series, which are stripped-down of the above, with PCIe and USB removed from the boards.
Third patch adds `rssileds` configuration for those boards, to match default settings of factory firmware
Fourth patch add support for RB911G-5HPacD, which differs from the existing devices by dropping of `eth1`, which was used for SFP on RB92x series, which is absent on those boards.

Run tested on RB911G-5HPnD and RB911G-5HPacD using all affected images.

### CODE REVIEW

**Comment by Leo-PL** [comment]
cc @blocktrron

**Comment by Leo-PL** [comment]
@blocktrron the alternative way to handle RB911-[2,5]HPnD is to just add DEVICE_ALTn_MODEL, because RB912UAG image works for it without problem, and there is plenty of space on NAND for the extraneous USB support. And this would consume less buildbot resources.

**Comment by Leo-PL** [comment]
On the other hand, those leds are labeled as "user1...user5" on the board. In general I agree, but it makes more sense to rename them once the mentioned patch lands.

**Comment by raenye** [comment]
> user1...user5

In any case the DTS currently specifies `label = "green:led5";` instead of `label = "green:user5";`.

**Comment by Leo-PL** [comment]
> > user1...user5
> 
> In any case the DTS currently specifies `label = "green:led5";` instead of `label = "green:user5";`.

I don't want to change that now, because changing this will break user configurations, unless a migration script is created with it too.
As for button - makes more sense, because nothing depends on that name, really, so it can be changed safely.

**Comment by raenye** [comment]
So perhaps fix `01_leds`, which uses `green:user5`.

**Comment by Leo-PL** [comment]
Ah, now I see. My existing configuration must've slipped in.

**Comment by Leo-PL** [comment]
@raenye fixed and tested. Thanks for spotting that.

**Pull request merged**
