### PR TITLE
treewide: initial conversion to color/function LED format

### PR DESCRIPTION
**Pull request by Ansuel**
This is a bit effort in starting to convert all the DTS to colr/function LED format.

This was done by an automated script and is based on latest common.h LED kernel include.

With the following change, we should be able to compose a better list of what common.h still lack on function and colors and propose the missing piece upstream.

I will in the future compose a list of EVERY function and color currently used as from what I can se we have lots of case where we use wlan5g, 5g, wifi5g and think how we should handle them.

### CODE REVIEW

**Comment by csharper2005** [comment]
Awesome. 👍

[Such scripts](https://github.com/openwrt/openwrt/blob/main/target/linux/ramips/mt7620/base-files/etc/board.d/01_leds) also require adjustment. How do you plan to change them?

**Comment by Ansuel** [comment]
@csharper2005 that is something to think later but changing those is not a problem. For this pr we will have the same exact sysfs entry so it's not a problem.

**Comment by raenye** [comment]
Nice. Any idea how to deal with `function-enumerator` conversations?

Also, no upstream `function` for WWAN (3g, 4g, LTE, 5g, modem, ...), mesh and RSSI (signal). There's a patch for signal in patchworks though.

**Comment by Ansuel** [comment]
@raenye that needs some additional scripting but for now I would love to leave out just the simple case...

**Comment by raenye** [comment]
This can be traced to `target/linux/ramips/dts/mt7621_snr_snr-cpe-me2-lite.dts`:
```
        leds {
                compatible = "gpio-leds";

                led_sys: led-0 {
                        color = <LED_COLOR_ID_GREEN>;
                        function = LED_FUNCTION_STATUS;
                        gpios = <&gpio 15 GPIO_ACTIVE_HIGH>;
                };

                led_vpn: led-1 {
                        color = <LED_COLOR_ID_GREEN>;
                        function = LED_FUNCTION_STATUS;
                        gpios = <&gpio 14 GPIO_ACTIVE_LOW>;
                };
        };
```

We don't have `LED_FUNCTION_SYSTEM` in `ramips`' `include/dt-bindings/leds/common.h`, so  GPIO 15 should probably be kept unchanged, while GPIO 14 could be changed to `LED_FUNCTION_INDICATOR`.

@Ansuel should @wertwert4pda file an issue for this?

**Comment by wertwert4pda** [comment]
> maybe use `LED_FUNCTION_POWER` for GPIO 15?
This device have another HW power LED.  It's always on on powered.
I think LED_FUNCTION_INDICATOR is good idea for led_vpn
Maybe need to change 01_leds script for real name label?

**Comment by raenye** [comment]
> Also in this device doesn't work 5G led indicator

You mean there's an extra LED not supported by OpenWrt? By 5G you mean wifi 5ghz or mobile wwan?
You can try to enable various GPIO via the /sys/debug interface, to see which value is the missing one.
Alternatively this can be found in gpl sources, or in u-boot.

**Comment by wertwert4pda** [comment]
> wifi 5ghz

5GHz this one led doesn't light
Factory image is a fork OpenWrt. I decompile factory dts and sysfs and i see only 2 led "sys" and "vpn"

>  cat /sys/kernel/debug/gpio
GPIOs 0-31, platform/1e000600.gpio, 1e000600.gpio:
 gpio-14  (                    |?                   ) out hi
 gpio-15  (                    |?                   ) out lo
 gpio-18  (                    |reset               ) in  hi
 gpio-19  (                    |��               ) out hi
GPIOs 32-63, platform/1e000600.gpio, 1e000600.gpio:
GPIOs 64-95, platform/1e000600.gpio, 1e000600.gpio:

I think led controlled by driver end soldered to mt7513be chip 5GHz.

**Pull request merged**
