### PR TITLE
[22.03] Revert "mbedtls: import patch to fix illegal instruction on mpc85xx"

### PR DESCRIPTION
**Pull request by PolynomialDivision**
The commit was pushed into the branch to early. It does not help fixing illegal instruction bug on mpc85xx. That's why it should be reverted.

This reverts commit de6c3cca4d2b523937403ae2959597a1e48c7351.

### CODE REVIEW

**Comment by Ansuel** [comment]
@PolynomialDivision do we have a replacement patch or it's totally wrong and cause regression?

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision do we have a replacement patch or it's totally wrong and cause regression?

It does not cause a regression, but is also wrong. No I don't have a replacement except bumping gcc to next higher version. ;)

**Comment by BKPepe** [comment]
Just drop it...

**Comment by hauke** [comment]
Does anyone know which gcc commit fixed the problem? We could backport that toolchain change.

**Comment by pali** [comment]
The last gcc version which is working fine for mpc85xx without any issues is 8.5.0. You should stick on this gcc version to prevent such issues. Also later gcc versions completely removed vectorization support for mpc85xx together with HW floating point support. And there is not any plan in gcc to reintroduce and fix it back for this platform. @BKPepe has patches which compiles openwrt, toolchain, musl and packages with gcc 8 for mpc8548 with vector instructions and hw floating point support.

**Comment by PolynomialDivision** [comment]
> Does anyone know which gcc commit fixed the problem? We could backport that toolchain change.

Maybe it is this fix?
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=3cb53c10831be59d967d9dce8e7980fee4703500

**Pull request merged**
