### PR TITLE
kernel: drop support for mtd-mac-address

### PR DESCRIPTION
**Pull request by Ansuel**
Now that we have fully switched to nvmem interface we can drop
the use of mtd-mac-address patches as it's not used anymore and
the new nvmem implementation should be used for any new device.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
(we still need to actually drop the device using mtd-mac-address so this pr is to track the remaining device and finally drop the extra patch)

**Comment by adschm** [comment]
> (we still need to actually drop the device using mtd-mac-address so this pr is to track the remaining device and finally drop the extra patch)

Which are missing?

**Comment by adschm** [comment]
Commit title prefix would be "kernel:"

**Comment by Ansuel** [comment]
@adschm I think I missed the commits to handle the nvmem conversion for the dtsi devices.
Anyway
```
ansuel@Ansuel-xps:~/openwrt-clean/openwrt$ grep -rnw . -e "mtd-mac.*"
grep: ./.git/index: binary file matches
./target/linux/generic/pending-5.10/681-NET-add-mtd-mac-address-support-to-of_get_mac_addres.patch:4:Subject: [PATCH 1/2] NET: add mtd-mac-address support to of_get_mac_address()
./target/linux/generic/pending-5.10/681-NET-add-mtd-mac-address-support-to-of_get_mac_addres.patch:45:+ list = of_get_property(np, "mtd-mac-address", &size);
./target/linux/generic/pending-5.10/681-NET-add-mtd-mac-address-support-to-of_get_mac_addres.patch:86:+ * If a mtd-mac-address property exists, try to fetch the MAC address from the
./target/linux/generic/pending-5.10/682-of_net-add-mac-address-increment-support.patch:24:  * If a mtd-mac-address property exists, try to fetch the MAC address from the
./target/linux/generic/pending-5.4/681-NET-add-mtd-mac-address-support-to-of_get_mac_addres.patch:4:Subject: [PATCH 1/2] NET: add mtd-mac-address support to of_get_mac_address()
./target/linux/generic/pending-5.4/681-NET-add-mtd-mac-address-support-to-of_get_mac_addres.patch:45:+  list = of_get_property(np, "mtd-mac-address", &size);
./target/linux/generic/pending-5.4/681-NET-add-mtd-mac-address-support-to-of_get_mac_addres.patch:86:+ * If a mtd-mac-address property exists, try to fetch the MAC address from the
./target/linux/generic/pending-5.4/682-of_net-add-mac-address-increment-support.patch:24:  * If a mtd-mac-address property exists, try to fetch the MAC address from the
```
So i think we can drop it.

**Comment by Ansuel** [comment]
@adschm are we ready for this?

**Comment by adschm** [comment]
I would like some Acked-by from committers here. Maybe I will write to the list in a few days ...

**Comment by adschm** [comment]
BTW, has this actually been tested on a few devices, so we do not remove any hooks that are still necessary?

**Comment by adschm** [comment]
Thanks, I will do a final build test and merge then.

**Pull request closed without merging**
