### PR TITLE
[21.02] ramips: add support for TP-Link Archer C6 v3

### PR DESCRIPTION
**Pull request by amishv**
The patch adds support for the TP-Link Archer C6 v3 (FCC ID TE7A6V3)
The patch adds identification changes to the existing TP-Link Archer A6,
by Vinay Patil <post2vinay@gmail.com>, which has identical hardware.

Specification
-------------
MediaTek MT7621 SOC
RAM:         128MB DDR3
SPI Flash:   W25Q128 (16MB)
Ethernet:    MT7530 5x 1000Base-T
WiFi 5GHz:   Mediatek MT7613BE
WiFi 2.4GHz: Mediatek MT7603E
UART/Serial: 115200 8n1

Device Configuration & Serial Port Pins
---------------------------------------
ETH Ports:    LAN4 LAN3 LAN2 LAN1 WAN
             _______________________
             |                     |
Serial Pins: |   VCC GND TXD RXD   |
             |_____________________|

LEDs:         Power Wifi2G Wifi5G LAN WAN

Build Output
------------
The build will generate following set of files
[1] openwrt-ramips-mt7621-tplink_archer-c6-v3-initramfs-kernel.bin
[2] openwrt-ramips-mt7621-tplink_archer-c6-v3-squashfs-factory.bin
[3] openwrt-ramips-mt7621-tplink_archer-c6-v3-squashfs-sysupgrade.bin

How to Use - Flashing from TP-Link Web Interface
------------------------------------------------
* Go to "Advanced/System Tools/Firmware Update".
* Click "Browse" and upload the OpenWrt factory image: factory.bin[2]
* Click the "Upgrade" button, and select "Yes" when prompted.

TFTP Booting
------------
Setup a TFTP boot server with address 192.168.0.5.
While starting U-boot press '4' key to stop autoboot.
Copy the initramfs-kernel.bin[1] to TFTP server folder, rename as test.bin
From u-boot command prompt run tftpboot followed by bootm.

Recovery
--------
Archer A6 V3 has recovery page activated if SPI booting from flash fails.
Recovery page can be activated by powercycling the router four times
before the boot process is complete.
Note: TFTP boot can be activated only from u-boot serial console.
Device recovery address: 192.168.0.1

Signed-off-by: Amish Vishwakarma <vishwakarma.amish@gmail.com>
[fix indent]
Signed-off-by: David Bauer <mail@david-bauer.net>
Signed-off-by: Amish Vishwakarma <vishwakarma.amish@gmail.com>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by amishv** [comment]
TP-Link Archer C6 v3 appears to have the same hardware as Archer A6 v3, that is included in 21.03.
It will be prudent to add this PR along with A6 v3

**Comment by adschm** [comment]
The commit should be created with "git cherry-pick -x", so a reference to the original commit is included (automatically).

And please don't add an [21.02] prefix to the _commit_.

**Comment by amishv** [comment]
> The commit should be created with "git cherry-pick -x", so a reference to the original commit is included (automatically).
> 
> And please don't add an [21.02] prefix to the _commit_.

the commit was created using  

git cherry-pick -n d22fb7f4fd833c420bc2ab34384862da0a6688b5

Shall I redo the commit?

**Comment by amishv** [comment]
@adschm Kindly remove ath79 label, this is a ramips MT7621 device.

**Comment by aparcar** [comment]
> Shall I redo the commit?

Use `git cherry-pick -x d22fb7f` so it keeps a reference to the push in master branch.

**Comment by amishv** [comment]
Updated the branch with git cherry-pick -x

**Comment by aparcar** [comment]
@adschm looks good to me, mind I merge this?

**Review by aparcar — APPROVED** [review]

**Comment by adschm** [comment]
@aparcar We currently have 197 open PRs. I personally won't spend my time on reviewing device backports when PRs for new stuff have to wait in exchange (unless there is a special reason, of course). Sorry.

**Comment by aparcar** [comment]
I thought backports of devices are more of an easy thing than sone low level changes, but i might be wrong.

I'll do an extra shift later to review some things :)

**Comment by adschm** [comment]
From my experience/perspective, reviewing backports takes about the same time as reviewing new devices. The only advantage is that you mostly don't have the 1000 iterations with the formal/formatting/indent/whatever carelessness changes.

But even if it's easy, it's still work to be done. If I review this backport now, it will eventually lead to some other device not reviewed in time for the next branch, so there will be one additional backport popping up for review then and so on ...

**Comment by amishv** [comment]
@aparcar are there any updates?

It will be nice to get this included in the 21.02 release along with archer A6 v3 and archer C6u.

**Comment by galacticwarrior448** [comment]
Is there any chance of this coming to 21.02?

**Comment by amishv** [comment]
> Is there any chance of this coming to 21.02?

I have left hope and track after the attitude of the reviewer!

At least the snapshot is working for me :)

**Comment by galacticwarrior448** [comment]
> 
> 
> > Is there any chance of this coming to 21.02?
> 
> I have left hope and track after the attitude of the reviewer!
> 
> At least the snapshot is working for me :)

I am having a lot of issues regarding speed in 5ghz in my 300mbps connection. I saw somewhere that stable builds work better. If I cherry pick this into v21.02-rc3 and compile it, would it work the same way?

**Comment by adschm** [comment]
@aparcar After 1.5 months, this should either be reviewed or closed (=rejected) to reduce the number of dead PRs.

https://openwrt.org/docs/guide-developer/device-support-policies#backports

**Comment by aparcar** [comment]
Closing this since I don't have the device for testing and I'm not qualified to review the content itself. I'm very sorry @amishv for the slow response and the rejection, this will be in the next stable OpenWrt release!

**Comment by amishv** [comment]
> Closing this since I don't have the device for testing and I'm not qualified to review the content itself. I'm very sorry @amishv for the slow response and the rejection, this will be in the next stable OpenWrt release!

Thanks @appacar. Thanks for bringing this to closure.

I will not be tracking this anymore.

**Comment by aparcar** [comment]
@amishv please don't be discouraged from further contributions! It's late in the release process and adding new devices may postpone the final release even further!

**Comment by amishv** [comment]
@aparcar no reason to be discouraged.  
I bought a router and I needed to run openwrt on it. It was not supported and so I decided to do it myself! Mission accomplished.  :1st_place_medal:
I thought others may also get benefited (my bad), so decided to upload it back as mandated by GPL;  but the arrogance puts me off. If nobody needs it, so be it, my device is now working that is good enough for me!

**Comment by amishv** [comment]
@aparcar I see a lot of people struggling with this model, can we recheck -in the changes? I am not sure as the branch has moved on...

**Comment by aparcar** [comment]
I'm trying to push for a new release soon. I think this is the better approach :)

**Comment by amishv** [comment]
> I'm trying to push for a new release soon. I think this is the better approach :)

@aparcar, can you guide me to cherry-pick this into the main release?

**Comment by d-me3** [comment]
@amishv @aparcar I just did a new pull-request by cherry picking both the commit to add support to Archer C6 v3 to 21.02 as well as fixing a boot loop issue with Archer A6 v3 in the 21.02.2 stable release (which to me seems critical to fix). Please review the new pull request below. Also, since this is my first pull request, please let me know if any additional change needs to be done. I personally already tested it and it works OK. Thanks!

https://github.com/openwrt/openwrt/pull/9502

**Pull request closed without merging**
