### PR TITLE
ramips: Add support for Dlink DIR-853-R1

### PR DESCRIPTION
**Pull request by fiduchi**
Specifications:

    SoC: MT7621AT
    RAM: 128MB
    Flash: 16MB SPI
    WiFi: MT7615DN (2.4GHz+5Ghz) with DBDC (This mode allows
    this single chip act as an 2x2 11n radio and an 2x2 11ac radio at the
    same time)
    LAN: 5x1000M
    LEDs Power Blue+Orange,Wan Blue+Orange,WPS Blue,"2.4G"Blue, "5G" Blue,
    USB Blue
    Buttons Reset,WPS, Wifi

lan factory 0xe000 CD(label)
wan factory 0xe006 D0
2.4 GHz factory 0xe000+1 ECCE
5.0 GHz factory 0xe000+2 6ECE

Flashing instruction:

The Dlink "Emergency Room"

Connect your client computer to LAN1 of the device
Set your client IP address manually to 192.168.0.101 / 255.255.255.0.
Then, power down the router, press and hold the reset button, then
re-plug it. Keep the reset button pressed until the internet LED stops
flashing
Call the recovery page or tftp for the device at http://192.168.0.1
Use the provided emergency web GUI to upload and flash a new firmware to
the device.

Signed-off-by: Stas Fiduchi fiduchi@protonmail.com

### CODE REVIEW

**Comment by csharper2005** [comment]
I think you should correct your **commit** subject and description according to https://openwrt.org/submitting-patches#submission_guidelines

**Review by MaxS0niX — APPROVED** [review]
Please add a PR description to the commit message.
---
Пожалуйста, добавьте описание PR в сообщение коммита.

**Comment by fiduchi** [comment]
ramips: Add support for Dlink DIR-853-R1

**Comment by fiduchi** [comment]
Add support for Dlink DIR-853-R1

**Review by fiduchi — COMMENTED** [review]
DIR-853-R1

**Pull request closed without merging**
