### PR TITLE
build: support for PKG_SUBDIRS | tools/elfutils: simplify Makefile

### PR DESCRIPTION
**Pull request by mcprat**
ping @robimarko 

this is the last of the changes I intend to do for host elfutils, simplifying the Makefile
(part 1 #15368)
(part 2 #15690)

this also adds support for PKG_SUBDIRS for overriding the subdirectories for recursive Makefiles
and common recipes for using gnulib the way it is used with elfutils

this also makes host c++ compiling have optimization by default
(we can consider removing optimization for cmake if it takes a long time to build)

### CODE REVIEW

**Comment by mpratt14** [comment]
also ping @Ansuel 

for your thoughts on the common build system changes

**Comment by robimarko** [comment]
Well, I am no expert on anything here, so I can just confirm it seems to work on MacOS.

**Comment by mpratt14** [comment]
we have a few cases of setting PKG_SUBDIRS in individual Makefiles, so now this is just moving it to common build recipes and then removing useless lines from the elfutils makefile. 

and then there is the optimization flag so that c and c++ is processed the same way

**Comment by robimarko** [comment]
To me, the changes look sane (The CXX flags were on my TODO list as I hit a similar issue).

Are you going to push anything new or you are done?

**Comment by mpratt14** [comment]
@robimarko I updated the commit messages, I'm done now

**Comment by mpratt14** [comment]
also I realized that this does not affect cmake like I thought it would because cmake uses `-O3` for building as a release

I'm considering removing or changing optimization for cmake in a new PR that I will post if I find that the build time difference is significant enough

**Comment by mpratt14** [comment]
@Ansuel @robimarko ready for final review

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by robimarko** [comment]
Lets see what breaks :)

**Comment by mpratt14** [comment]
haha, well I'm pretty sure this is a very simple thing :)

**Pull request merged**
