### PR TITLE
kernel: bump 5.4 to 5.4.100

### PR DESCRIPTION
**Pull request by graysky2**
Ran `update_kernel.sh` in a fresh clone without any existing toolchains.
```
Build system: x86_64
Build-tested: ipq806x/R7800
Run-tested: ipq806x/R7800
```
No dmesg regressions, everything functional.

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by timocapa** [comment]
Build system: x86_64
Build-tested: ramips/MT7621/Xiaomi Mi R3G
Run-tested: ramips/MT7621/Xiaomi Mi R3G
GCC: 10.2
binutils: 2.35.1

No regressions, don't have the time to test the other router right now.

**Comment by Borromini** [comment]
```
Compile-tested: ath79/{generic,tiny}, ipq40xx, octeon, realtek, ramips/{mt7620,mt7621}, x86/64
Run-tested: ath79/generic: WNDR3700v2, octeon: EdgeRouter Lite, ramips/{mt7620,mt7621}: Archer C2 v1 / EAP235-Wall, R6800, RT-AC57U v1
```

Has been tested on the 21.02 branch but so far that's not really diverging from master kernel-wise.

Tested-by: Stijn Segers <foss@volatilesystems.org>

**Comment by timocapa** [comment]
I can also confirm my second router now.

Build system: x86_64
Build-tested: ramips/MT7621/Xiaomi Mi R3G, Lantiq/XWAY/Fritz!Box 7320/7330
Run-tested: ramips/MT7621/Xiaomi Mi R3G, Lantiq/XWAY/Fritz!Box 7320/7330

All good

**Comment by adschm** [comment]
Thanks, merged.

**Pull request closed without merging**
