### PR TITLE
libjson-c: update to 0.14

### PR DESCRIPTION
**Pull request by dengqf6**
Update libjson-c to 0.14
Changelog: https://github.com/json-c/json-c/wiki/Notes-for-v0.14-release

Compile & run tested on ramips and mvebu
ipk size increased by 2KB

### CODE REVIEW

**Comment by hauke** [comment]
Please mention in the commit message that you switched to cmake because the upstream build system was changed between 0.13 and 0.14

**Comment by diizzyy** [comment]
NACK, CVE is still present in release
https://github.com/json-c/json-c/tree/json-c-0.14

**Comment by dengqf6** [comment]
added CVE patch

**Comment by dedeckeh** [comment]
@dengqf6 Please keep the backported patches in their original format as was the case before the update

**Comment by neheb** [comment]
Is it possible to use cmake?

**Comment by dedeckeh** [comment]
@dengqf6 Ping
As requested please keep the backported patches in their orignal format as separate patches

**Comment by dengqf6** [comment]
> in their original format

The patch is **directly picked** from json-c/json-c@5d6fa331418d49f1bd488553fd1cfa9ab023fabb on branch _json-c-0.14_

**Comment by dedeckeh** [comment]
I missed the patch in the json-c-0.14 branch
Anyway patch merged to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=summary); thx

**Pull request closed without merging**
