### PR TITLE
kernel: add kmod-nvme package

### PR DESCRIPTION
**Pull request by dangowrt**
Add driver for NVM Express block devices.

Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Review by BKPepe — CHANGES_REQUESTED** [review]
Hi Daniel,

Thanks for creating a pull request, but I am unsure if this is a good way. May I first ask you which your's device is using NVMe disk(s)? Isn't it big enough to have it enabled directly in the kernel? The kernel increase is about 36 KiB. I am afraid that your proposal prevents users from booting from NVMe. 

Also, there are already several targets, which has enabled this in kernel config:
- ipq807x
- rockchip/armv8
- x86/84
- mvebu
There is also pending PR to enable this on mpc85xx. 

Right now, it seems like that you will introduce another option on how to enable NVMe support and it could be confusing for end-users.

**Comment by dangowrt** [comment]
Many boards nowadays have M.2/NGFF sockets which can be used (among other things) for NVMe storage. I've seen people manually enabling the kernel config options to have built-in support for NVMe on ramips/mt7621. I don't think NVMe support should be built-in by default on this target as there are space-constraint devices with only NOR flash and no option to even connect anything to the PCIe bus. Also on mediatek/mt7622 and the upcoming mediatek/filogic targets are good examples: Some boards may provide sockets for NVMe storage, others are NOR-flash based access points without any option to add NVMe disks via  NGFF/M.2 (or mPCIe) slots.

Having a kmod package for something which may be built-in on some targets is not a problem, we have many examples for that (`kmod-i2c-gpio`, `kmod-phylink`, `kmod-phy-*`, ...) and the result is just that on such platforms the kmod package is an empty dummy.

For users this makes things easier, as independently of whether support for a feature is built-in or provided by a kernel module, installing (or depending on) the relevant kmod package will always result in the feature being available (either because it was already available because it is built-into the kernel, or because the relevant kernel modules are added).

**Comment by BKPepe** [comment]
Thanks for the detailed explanation. Yes, I agree with you. It makes sense. I think it would be good if you could include this in the commit description, which is relatively short.

**Review by hauke — APPROVED** [review]

**Comment by dangowrt** [comment]
Improved commit message and pushed.

**Comment by BKPepe** [comment]
Reference: https://github.com/openwrt/openwrt/commit/dbe53352e38d20bb5245158b19d4ff810c209548

**Pull request closed without merging**
