### PR TITLE
ar71xx: Add TP-Link WR940N v6 support

### PR DESCRIPTION
**Pull request by robimarko**
Add support for TL-WR940N v6 board.
It is pretty much the same as v5 except they only left WAN LED and removed other ones.

Installation:
Flash factory image through WEB UI
or use TFTP to flash it.

Signed-off-by: Robert Marko <robimarko@gmail.com>

### CODE REVIEW

**Comment by JamesT42** [comment]
WAN Led seems to be dual color, are both of these available in your PR? (I know that switching the color is not easy etc... but I still could use it with some scripting).

**Comment by robimarko** [comment]
Are you sure?
I only found 1 GPIO assigned to LEDs

**Comment by heinzek** [comment]
From User Guide:

image

**Comment by robimarko** [comment]
Ok,will look into GPL again tommorow.

**Comment by robimarko** [comment]
Took another look at GPL and they defined GPIO14 to be used too, but only in the bootloader.
I did not find it earlier since I was searching by model name and not their product identifier code.
/*` turn on all wan blue*/
    li t0, GPIO_OUT
    lw t1, 0(t0)
    li t2, ~((1<<14) | (1<<15))
    /*li t2, 0xfffb3e07*/
    and t1, t1, t2
    sw t1, 0(t0)

    /* wait for a while */
    li t0, 0x0
    li t1, 0x9000000
1:
    addi t0, t0, 1
    bne t0, t1, 1b
    nop

    /* turn on wan orange*/
    li t0, GPIO_OUT
    lw t1, 0(t0)
    li t2, ((1<<14)|(1<<15))
    or t1, t1, t2
    sw t1, `0(t0)

Not really intuitive, but it looks like its GPIO14 for another color.
I could add it to GPIOs so it can be used as diagnosing LED.

@JamesT42 Would you be willing to test the new image?

**Comment by robimarko** [comment]
No interest so far in testing GPIO for other color.
Rebased on master due to makefile changes.
So,this is good to go

**Comment by JamesT42** [comment]
Really sorry, I did not see your comment before. I do not have such a device yet, so I can not test it.

**Comment by JamesT42** [comment]
@robimarko I have a WR940N V6 now, if you send me an image I will test it ASAP.

**Comment by robimarko** [comment]
@JamesT42 Here is a test image:
https://drive.google.com/drive/folders/1iUQUSMz-KlBGESlkbHBJxsDrMijG7gIe?usp=sharing

Orange LED should be used during first boot as I set it as diag one.
Please inform me which color is lit and when

**Comment by robimarko** [comment]
@jernejs Ok,thanks.
It should be fixed now
https://drive.google.com/drive/folders/1iUQUSMz-KlBGESlkbHBJxsDrMijG7gIe?usp=sharing

**Comment by robimarko** [comment]
It should be turned off after everything is booted.
Blue one should be on after WAN is connected

**Comment by jernejs** [comment]
Confirmed, this now works properly.

**Comment by robimarko** [comment]
Great,will push those changes to this PR.

**Comment by JamesT42** [comment]
Sorry, but I can not confirm that.
I tried your image, and also build my own using your patches.
After boot, blue switches on and of very shortly, then orange turns on, then blinks. After the boot is finished, it mostly lights blue/redish at the same time, but blinks orange on wan traffic.
When unplugging wan, it lights orange. (Which is kind of ok I guess)

**Comment by JamesT42** [comment]
Maybe we need something like
ucidef_set_led_netdev "wan-blue" "WAN (blue)" "tp-link:blue:wan" "eth0"
ucidef_set_led_default "wan-orange" "WAN (orange)" "tp-link:orange:wan" "0" 
(I'm not sure if that is correct, i just looked at the file an other devices) so the orange led has a defined state and is pre-configured in (l)uci?

**Comment by robimarko** [comment]
No,orange one is just for diag.sh
Most likely it is set to 1 as default by bootloader.
So I need to set it to 0 by default.
Will have a image to test soon

**Comment by JamesT42** [comment]
Why not make the orange led accessible in (l)uci as standard?

**Comment by robimarko** [comment]
Well,it is accessible.
You can make whatever rules you want with it

**Comment by rotanid** [comment]
> It is pretty much the same as v5

but there is no v5 support in OpenWrt, is there?

**Comment by heinzek** [comment]
WR940Nv5 use the same image as WR940Nv4

**Comment by movikbence** [comment]
Hi

If am in europe, and my firmware is the official factory, shall I upgrade it with that : ..factory-eu.bin , on that link you previously added to the conversation.
Thank you

**Comment by movikbence** [comment]
Sorry i forgot one thing: I have TP-Link TLWR940N-V6

**Comment by JamesT42** [comment]
@robimarko Have you found the missing "orange LED off" somewhere?

**Comment by robimarko** [comment]
Yes,it is registered.

**Comment by JamesT42** [comment]
Any news on this? Would be nice to have the new hardware in snapshots now.

**Comment by pepe2k** [comment]
@robimarko

Thank you for your contribution! I have merged your changes into [my staging tree](https://git.openwrt.org/openwrt/staging/pepe2k.git).

Cheers,
Piotr

**Pull request closed without merging**
