### PR TITLE
omap: switch default kernel to 5.15

### PR DESCRIPTION
**Pull request by alexeys85**
Tested on Beaglebone Black for +6month now without issues.

Signed-off-by: Alexey Smirnov <s.alexey@gmail.com>

### CODE REVIEW

**Comment by alexeys85** [comment]
Rebased.

**Comment by PolynomialDivision** [comment]
I think this is ready to be merged? @chunkeey merged already the 5.15 support.

**Comment by lynxis** [comment]
I tested omap today with upstream version 6bc675c0bed969303f94bb59310081d92bf2e74a
The ethernet can't be added to the bridge.

**Comment by alexeys85** [comment]
According to the commit torvalds/linux@1f12177b322dd7e7555537211778d308bdc31dab it is necessary to disable vlan filtering and probably fix `default_pvid` before working with bridge. 
@lynxis I dont have a device right now, it would be great if you could take it over and test.

**Comment by aparcar** [comment]
I updated this to run the added CI checks.

**Comment by aparcar** [comment]
@alexeys85 @lynxis friendly ping

**Comment by alexeys85** [comment]
Well, I don't know what's the best solution of this problem as I don't use default bridge. Otherwise it works rock solid since beginning.

**Comment by PolynomialDivision** [comment]
There seems to be a workaround:
https://github.com/openwrt/openwrt/issues/11953#issuecomment-1419078990

**Comment by alexeys85** [comment]
@PolynomialDivision, unfortunately I don't have spare device right now to check, but I believe it should work.

**Pull request closed without merging**
