### PR TITLE
kernel: update SSDK and NSS-DP to 12.4.5.r1

### PR DESCRIPTION
**Pull request by robimarko**
Qualcomm has finally started the preparatory work in order to support
kernel 6.1, so let's use that and update SSDK and NSS-DP to 12.4.5.r1
which allows us to drop a lot of patches.

Runtime tested on Qnap 301W, testing on other devices would be great.

### CODE REVIEW

**Comment by zxlhhyccc** [comment]
> I would really appreciate testing roaming, cause we had issues with that before and QCA implemented something similar to our fix but I dont think it will work as intended.

5.15 kernel compilation error, can be compatible with the 5.15 kernel?

**Comment by Ansuel** [comment]
@zxlhhyccc 5.15 support was dropped with all the required patches. Also no point in keep using 6.1 considering the target is new and would only benefits from using a new kernel

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc 5.15 support was dropped with all the required patches. Also no point in keep using 6.1 considering the target is new and would only benefits from using a new kernel

After adding these two patches, the 5.15 kernel will compile normally, but the 6.1 kernel may compile errors!
````
--- a/nss_dp_main.c
+++ b/nss_dp_main.c
@@ -634,14 +634,14 @@ static int32_t nss_dp_of_get_pdata(struct device_node *np,
 	hal_pdata->netdev = netdev;
 	hal_pdata->macid = dp_priv->macid;
 
-#if (LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 0))
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0))
 	dp_priv->phy_mii_type = of_get_phy_mode(np);
 #else
 	if (of_get_phy_mode(np, &dp_priv->phy_mii_type))
 		return -EFAULT;
 #endif
 
-#if (LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 0))
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0))
 	maddr = (uint8_t *)of_get_mac_address(np);
 #if (LINUX_VERSION_CODE > KERNEL_VERSION(5, 4, 0))
 	if (IS_ERR((void *)maddr)) {
@@ -649,10 +649,12 @@ static int32_t nss_dp_of_get_pdata(struct device_node *np,
 	}
 #endif
 #else
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 0))
 	maddr = mac_addr;
 	if (of_get_mac_address(np, maddr))
 		maddr = NULL;
 #endif /* LINUX_VERSION_CODE 6.1.0 */
+#endif
 
 	if (maddr && is_valid_ether_addr(maddr)) {
 #if (LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 0))
`````
````
--- a/nss_dp_switchdev.c
+++ b/nss_dp_switchdev.c
@@ -288,7 +288,7 @@ void nss_dp_switchdev_setup(struct net_device *dev)
  * nss_dp_port_attr_set()
  *	Sets attributes
  */
-#if (LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 0))
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0))
 static int nss_dp_port_attr_set(struct net_device *dev,
 				const struct switchdev_attr *attr
 				,struct switchdev_trans *trans)
@@ -299,7 +299,7 @@ static int nss_dp_port_attr_set(struct net_device *dev,
 {
 	struct nss_dp_dev *dp_priv = (struct nss_dp_dev *)netdev_priv(dev);
 
-#if (LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 0))
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0))
 	if (switchdev_trans_ph_prepare(trans))
 		return 0;
 #endif
@@ -335,7 +335,7 @@ static int nss_dp_switchdev_port_attr_set_event(struct net_device *netdev,
 		return NOTIFY_DONE;
 	}
 
-#if (LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 0))
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0))
 	err = nss_dp_port_attr_set(netdev, port_attr_info->attr
 				   ,port_attr_info->trans);
 #else
``````

**Comment by robimarko** [comment]
@zxlhhyccc I dont care about 5.15 at all, 6.1 compiles without any warnings.

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc I dont care about 5.15 at all, 6.1 compiles without any warnings.

@robimarko yes，Now the 23.05 branch is the 5.15 kernel, otherwise can only use the old version...

**Comment by zxlhhyccc** [comment]
@Ansuel @robimarko 
**`qca-ssdk` There is this warning:**
````
/home/lin/ax6/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-ssdk-2023-06-06-74caf88a/temp/src/init/ssdk_init.c:343:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  343 |                 priv->phy_mmd_write(priv->device_id, phy, 0x4007, 0x0);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/lin/ax6/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-ssdk-2023-06-06-74caf88a/temp/src/init/ssdk_init.c:349:9: note: here
  349 |         case 4:
      |         ^~~~
  CC [M]  /home/lin/ax6/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-ssdk-2023-06-06-74caf88a/temp/src/init/ssdk_plat.o
``````

**Comment by robimarko** [comment]
I dont plan to backport this to 23.05 anyway.
Those warnings are not present in this version

**Comment by zxlhhyccc** [comment]
> I dont plan to backport this to 23.05 anyway. Those warnings are not present in this version

Probably still a kernel issue

**Comment by robimarko** [comment]
@zxlhhyccc Again, those warnings do not exist when compiling against the current OpenWrt master and kernel 6.1.
5.15 is completely irrelevant.

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc同样，当针对当前 OpenWrt master 和内核 6.1 进行编译时，这些警告不存在。 5.15 完全无关。

@robimarko Older versions also have this warning。。。

**Comment by zxlhhyccc** [comment]
`qca-nss-ecm' Is there any plan to transplant?

**Comment by Ansuel** [comment]
@zxlhhyccc NEVER.

Also again WE DON'T CARE. 5.15 was dropped and we moved to 6.1 so we focus on having them working with the supported kernel. there is 23.05 with the old version and patches supported for 5.15.

Community can put some effort in adding 5.15 patch back on main and have this new ssdk version on 5.15... But to me it sounds like a tremendous amount of time wasted that could be better invested on downstream project on porting your precious qcom packages on 6.1 (cause we all know that is the intention of keeping 5.15 and asking for support of this new ssdk version on 5.15 and community members should be clear about this and not fake it)

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc NEVER.
> 
> Also again WE DON'T CARE. 5.15 was dropped and we moved to 6.1 so we focus on having them working with the supported kernel. there is 23.05 with the old version and patches supported for 5.15.
> 
> Community can put some effort in adding 5.15 patch back on main and have this new ssdk version on 5.15... But to me it sounds like a tremendous amount of time wasted that could be better invested on downstream project on porting your precious qcom packages on 6.1 (cause we all know that is the intention of keeping 5.15 and asking for support of this new ssdk version on 5.15 and community members should be clear about this and not fake it)

OK！

**Comment by kwiateusz** [comment]
On Xiaomi AX3600 (ipq807x) everything works like before. I can't check roaming because I don't have a spare extra device to experiment.

**Comment by Ansuel** [comment]
> > @zxlhhyccc NEVER.
> > Also again WE DON'T CARE. 5.15 was dropped and we moved to 6.1 so we focus on having them working with the supported kernel. there is 23.05 with the old version and patches supported for 5.15.
> > Community can put some effort in adding 5.15 patch back on main and have this new ssdk version on 5.15... But to me it sounds like a tremendous amount of time wasted that could be better invested on downstream project on porting your precious qcom packages on 6.1 (cause we all know that is the intention of keeping 5.15 and asking for support of this new ssdk version on 5.15 and community members should be clear about this and not fake it)
> 
> OK！But what I'm saying **`qca-nss-ecm`**，Because the latest version is compatible with the 6.1 kernel。

ecm require additional patch to the kernel and they are too much changes for it... Also no sense in having support for ecm and lacking support for drv.

**Comment by rmandrad** [comment]
Tested on the dynalink sucessfully and able to roam from one ssid to another ; Noted I used the latest 2.9 firmware - fw_version 0x290904a5 fw_build_timestamp 2023-06-18 03:33 fw_build_id WLAN.HK.2.9.0.1-01832-QCAHKSWPL_SILICONZ-1

**Comment by mrkiko** [comment]
Out of curiosity - does "roaming" mean passing from a SSID to another on the same device or shouldwe have different devices? Thanks!

**Comment by robimarko** [comment]
It's roaming from one device to another, as that was the previous issue we had.
Basically, if you had another AP hanging off the ipq807x one, then if your device moved back to ipq807x AP it would have a duplicate FDB entry until the original one timed out.

**Comment by rmandrad** [comment]
> It's roaming from one device to another, as that was the previous issue we had. Basically, if you had another AP hanging off the ipq807x one, then if your device moved back to ipq807x AP it would have a duplicate FDB entry until the original one timed out.
> 

don't seem to reproduce the issue ... so from my perspesctive it seems to work ...note though I am using the latest ipq8074 firmware  (01832) that was issued on 18/6 by upstream quic

**Comment by kwiateusz** [comment]
Too bad this new firmware doesn't work on xiaomi again

**Comment by robimarko** [comment]
> Too bad this new firmware doesn't work on xiaomi again

I am going to need more details

**Comment by rmandrad** [comment]
> Too bad this new firmware doesn't work on xiaomi again

this fix doesn't update any firmware  ... pls take this conversation to forum.openwrt.com if it relates to the firmware... I just noted that my testing is not using the openwrt ath11k firmware that is shipped ootb but instead the latest

**Comment by zxlhhyccc** [comment]
@robimarko @Ansuel One big problem is that the MAC address of the lan is automatically changed every time the firmware is upgraded！

**Comment by robimarko** [comment]
@zxlhhyccc More details please, what board, since when its happening etc cause I find it rather unlikely.

**Comment by kwiateusz** [comment]
> > Too bad this new firmware doesn't work on xiaomi again
> 
> this fix doesn't update any firmware ... pls take this conversation to forum.openwrt.com if it relates to the firmware... I just noted that my testing is not using the openwrt ath11k firmware that is shipped ootb but instead the latest

I know, sorry, but after your comment I uploaded a new version of fw and again it is impossible to connect over wifi and there is nothing interesting in the log. I was disappointed and couldn't help but comment especially since @robimarko  was releasing an update earlier.

The code itself from the pull request still works with no apparent errors.

**Comment by Ansuel** [comment]
Guys ignore this if I'm wrong but can we please not go off topic? This is
about updating ssdk and nss-dp nothing about WiFi... It was asked about
roaming problem with the current WiFi Fw and this pr... It's really to
understand if this bump is ok to merge it and move further

Il Dom 25 Giu 2023, 20:36 kwiateusz ***@***.***> ha scritto:

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc More details please, what board, since when its happening etc cause I find it rather unlikely.

Unable to provide more details, but after firmware upgrade, the MAC address of br-lan will automatically change, and the same firmware will also change when upgraded again...

**Comment by robimarko** [comment]
@zxlhhyccc I am going to stop taking you seriously, cause these kinds of "bug" reports are useless.
So you cant even tell the board you are seeing it on, nor when it started happening, is it even related to this PR?

**Comment by zxlhhyccc** [comment]
@robimarko @Ansuel 
mac address before the upgrade：
image
mac address after the upgrade:
image

After the tests, everything was normal after the rollback...

**Comment by robimarko** [comment]
@zxlhhyccc Again, until you provide basic info like what is the router/board you are seeing this I will just ignore you.

**Comment by XiaoliChan** [comment]
Wifi roaming not working after this commit, after the client got a connection from the first AP, if the client attempt to do roaming to the second AP, it will disconnect from the second AP instantly and the client still try to connect to the second AP. (client will do these step repeatedly)

How to reproduce?
- Two AP (I have two redmi ax6)
- The client connected to the first AP, then did manual disconnect from the first AP to make it force connect to the second AP.

Logs:
- Kernel logs have nothing special
- System logs:
[logs.txt](https://github.com/openwrt/openwrt/files/11872538/logs.txt)

**Comment by robimarko** [comment]
@XiaoliChan Thanks for testing, that confirms my suspicions about the QCA code.
I will patch that tomorrow to restore the old behavior that removes the old MAC entry when roaming.

**Comment by XiaoliChan** [comment]
> @XiaoliChan Thanks for testing, that confirms my suspicions about the QCA code.
> Can you include `ip-bridge` package and dump the FDB via `bridge fdb` to see if there is a duplicate MAC entry?

Sure, what command result did you need? Just  ` bridge fdb show `?

**Comment by robimarko** [comment]
Yes, `bridge fdb show` but when you are having the issue.

**Comment by XiaoliChan** [comment]
@robimarko Here is all APs fdb dump, catch it when client roaming happening.
[fdb-all-dump.tar.gz](https://github.com/openwrt/openwrt/files/11885386/fdb-all-dump.tar.gz)

**Comment by robimarko** [comment]
Thanks, I will implement the old roaming fix back and make a PR for testing.
I am getting reports that newer FW is working fine so its probably time for PR for that as well.

**Pull request merged**
