### PR TITLE
bcm47xx: cleanup patches before jumping to 5.15

### PR DESCRIPTION
**Pull request by PolynomialDivision**
While working on the bump to 5.15, add upstream tags and replace patches with upstream ones.

### CODE REVIEW

**Comment by satmandu** [comment]
Could we get https://github.com/openwrt/openwrt/issues/11608#issuecomment-1364676840 added to this to fix ethernet?

**Comment by Ansuel** [comment]
@PolynomialDivision am i wrong or we are losing the aruas rtn10u board data?

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision am i wrong or we are losing the asus rtn10u board data?

Yes. Thanks! I was missing `324-v5.17-MIPS-BCM47XX-Add-LEDs-and-buttons-for-Asus-RTN-10U.patch`

**Comment by Ansuel** [comment]
@PolynomialDivision bcm47xx_buttons_linksys_wrt310n_v2 seems also missing

**Comment by PolynomialDivision** [comment]
Yep, I was missing `325-v5.17-MIPS-BCM47XX-Define-Linksys-WRT310N-V2-buttons.patch`.

**Comment by Ansuel** [comment]
@PolynomialDivision think now everything should be good can you do an extra check?

**Comment by PolynomialDivision** [comment]
@Ansuel I tried to compare each line. Seems fine. :)

**Pull request merged**
