### PR TITLE
ar71xx: add support for Pisen Cloud Easy Power

### PR DESCRIPTION
**Pull request by Icenowy**
Pisen Cloud Easy Power is an AR9331-based router and power bank combo
device. The device uses a stock firmware modified from OpenWRT for
TP-Link TL-WR703N; however some GPIO definition is different on this
device with TL-WR703N. An AXP202 PMIC (connected to a 5000mAh battery)
and a SD slot are also added, and the stock Flash/RAM configuration
is 8MiB/64MiB.

http://my.piseneasy.com/product/details/2465

Signed-off-by: Icenowy Zheng <icenowy@aosc.io>

### CODE REVIEW

**Comment by pepe2k** [comment]
Hi @Icenowy,

Please:

- rebase on current master
- drop link from your commit message
- include `IMAGES := sysupgrade.bin` in your image definition if this device doesn't require factory image and can be flashed with just sysupgrade one
- include flashing instruction in your commit message

Cheers,
Piotr

**Comment by Icenowy** [comment]
Hi @pepe2k,

I have force pushed the changed commit to my branch.

Thanks!

**Comment by Icenowy** [comment]
Ping. @pepe2k could you re-check my patch?

**Comment by blogic** [comment]
sorry this got lost along the way. patch looks good but fails to apply, please rebase and reopen the PR if still relevant.

**Comment by Icenowy** [comment]
@blogic @pepe2k Rebased the commit and changed the model number to WMM003N, and not directly use the product name in the code.

BTW should I migrate this to ath79?

**Comment by bobafetthotmail** [comment]
> BTW should I migrate this to ath79?

Would be nice, as that's what will replace ar71xx eventually.

**Comment by Icenowy** [comment]
OK please ignore this pull request and go to #1276 instead.

**Pull request closed without merging**
