### PR TITLE
Busybox host compatibility

### PR DESCRIPTION
**Pull request by aboyett**
This PR removes a couple of GNU-isms from buildroot-ng:

Busybox time supports the GNU time '-f' syntax used by the build time
logging implemented in ff6e62b288c, however the prerequisite check added
only works with GNU time installed as `time` or `gtime`.
    
busybox gzip does not support "--force" unless busybox is explicitly
compiled with FEATURE_GZIP_LONG_OPTIONS=y. As a result most
installations of busybox gzip can't handle "--force" including those
provided by OpenWrt and Alpine Linux.
    
Refer to the commit messages for full details on each fix.

### CODE REVIEW

**Comment by joeholden** [comment]
Looks good here on Alpine 3.7

**Comment by mcbridematt** [comment]
The gzip issue was solved by #873 which was merged in a couple of days ago.

**Comment by aboyett** [comment]
I'm inclined to leave the PR as-is to reduce rebase noise. Since our fixes were identical there are no merge conflicts. Let me know if a rebase is preferred.

**Comment by blogic** [comment]
merged, Thanks ! ... 1/2 was already in the tree ....

**Comment by blogic** [comment]
1/2 was fixed by fba168f5745acac95db519a9984b62e3e508df6a

**Pull request closed without merging**
