### PR TITLE
libmbedtls: build option menu

### PR DESCRIPTION
**Pull request by gstrauss**
libmbedtls: build option menu

Follow-up from #10727

This replaces package/libs/mbedtls/patches/200-config.patch
It preserves most of the settings in 200-config.patch, with a few changes:

MBEDTLS_CMAC_C
MBEDTLS_DES_C 
MBEDTLS_NIST_KW_C
are enabled since hostapd pulls in a local implementation if the underlying algorithms are not present in the crypto library.

MBEDTLS_ECP_DP_SECP521R1_ENABLED
MBEDTLS_ECP_DP_CURVE448_ENABLED
are enabled because strong crypto algos should be made available from the *library*

### CODE REVIEW

**Comment by gstrauss** [comment]
@neheb would you please approve running the workflow on this PR for the first step of review?

**Comment by gstrauss** [comment]
Aside: not all the MBEDTLS_KEY_EXCHANGE_* options were part of patches/200-config.patch

Options to consider adding to menu and disabling by default to save binary size (not quantified):
MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED

Options to consider adding to menu (and leaving enabled) for completeness:
MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED

**Comment by neheb** [comment]
I’d add and disable those in a separate commit. JPAKE is indeed useless.

**Comment by gstrauss** [comment]
To reduce binary size some, I am going to push a change to this PR to have
MBEDTLS_ECP_DP_SECP521R1_ENABLED
MBEDTLS_ECP_DP_CURVE448_ENABLED
disabled by default, as is the current behavior in the openwrt mbedtls package.

Reasoning:

(Oct 2021)
https://community.letsencrypt.org/t/when-choosing-an-elliptic-curve-look-for-a-safe-curve/161837

(May 2022)
Guidance for Choosing an Elliptic Curve Signature Algorithm in 2022
https://soatok.blog/2022/05/19/guidance-for-choosing-an-elliptic-curve-signature-algorithm-in-2022/

---

While making the above modification, I added the following options, disabled by default, as discussed further above.
MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED

MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED is disabled by default in mbedtls, and not worth providing as an option.

I added the following options, enabled by default, as discussed further above.
MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
These might be disabled by default in the future, if not needed by openwrt dependants.  (I have not surveyed their use.)

**Comment by neheb** [comment]
Would be interesting to run Lufi HTTPS or something with these modifications and see if anything new fails to connect.

**Comment by neheb** [comment]
I just tested without this PR. I doubt this changes anything related to LuCI's HTTPS.

```
Cipher Suites
--
# TLS 1.3                                                 (suites in server-preferred order)
TLS_CHACHA20_POLY1305_SHA256 (0x1303)                                                                                    ECDH x25519 (eq. 3072 bits RSA)   FS | 256
TLS_AES_128_GCM_SHA256 (0x1301)                                                                                    ECDH x25519 (eq. 3072 bits RSA)   FS | 128
TLS_AES_256_GCM_SHA384 (0x1302)                                                                                    ECDH x25519 (eq. 3072 bits RSA)   FS | 256
# TLS 1.2                                                 (suites in server-preferred order)
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)                                                                                    ECDH x25519 (eq. 3072 bits RSA)   FS | 256
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)                                                                                    ECDH x25519 (eq. 3072 bits RSA)   FS | 128
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)                                                                                    ECDH x25519 (eq. 3072 bits RSA)   FS | 256
```

**Comment by hauke** [comment]
Please do the changes in 2 steps. One converting it to the menu config and an other step changing the defaults. Currently it is not easily visible what default settings you changed.
We still need some of the TLS RSA  key exchanges to support older https clients and server and probably also for some VPNs or later WPA EAP.

**Comment by gstrauss** [comment]
@hauke as requested, I have modified the PR to make the changes in separate commits.

I have also left MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED enabled per your feedback.

**Comment by gstrauss** [comment]
How does an external contributor (me) get **6** approving reviews?  There are only 3 accounts following this PR, and one is me.

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
No idea who came up with that. It'll probably be merged by the end of the week.

**Comment by neheb** [comment]
ping @hauke

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in 602a76ed65e51fa4f10f50dbeda821741f2bdbab, aeeb12eb83d669ea66dc5315cc490662bbbbd967 and 106425225953164ca45569c04d8147f16641a696.

**Comment by neheb** [comment]
@gstrauss http://lists.openwrt.org/pipermail/openwrt-devel/2022-November/039788.html

**Comment by gstrauss** [comment]
```
/data/src/LEDE/archer-C7-ath79-5.10.x-dsa-fw4/build_dir/target-mips_74kc_musl/mbedtls-2.28.1/include/mbedtls/check_config.h:76:2: error: #error "MBEDTLS_CTR_DRBG_C defined, but not all prerequisites"
    76 | #error "MBEDTLS_CTR_DRBG_C defined, but not all prerequisites"
       |  ^~~~~
```
That can only happen if `MBEDTLS_AES_C` is not defined, and that gets defined by default, so something is likely amiss in that user's environment.

@neheb my first guess for http://lists.openwrt.org/pipermail/openwrt-devel/2022-November/039788.html would be that the user did not `make menuconfig` to pick up the new defaults.

My second guess would be that the user did not run the feeds update script, which I do via
`make -j 8 package/symlinks`
`make -j 8 -k download`
`make menuconfig`

My third guess (and least likely) would be that user's environment does not have python3 installed to be able to run `/mydevenv/openwrt-repo/build_dir/target-mipsel_24kc_musl/mbedtls-2.28.1/scripts/config.py`  (which is where the script is run in my test env).

I just reconfirmed that the HEAD of the openwrt repo builds mbedtls in my target-mipsel_24kc_musl env.

**Comment by gstrauss** [comment]
The user should check if `/mydevenv/openwrt-repo/build_dir/target-mipsel_24kc_musl/mbedtls-2.28.1/include/mbedtls/config.h` exists and if it is empty.  It should not be empty, and should have the missing prerequisites defined, but according to the user's error report, it does not.  What's there in the user's environment, and have they tried a clean build?
`make V=1 -j 8 -k package/libs/mbedtls/clean`
`make V=1 -j 8 -k package/libs/mbedtls/compile`

**Comment by dhewg** [comment]
It happens when mbed isn't even selected:
`grep -i mbed .config` yields only commented stuff

It still gets built by the build system, I think because of mbedtls variants of other packages?

**Comment by gstrauss** [comment]
@dhewg thanks for the hint.
@neheb why is mbedtls being built when it has not been selected?  Wouldn't it be more efficient if it were not built, and if variants with the implicit dependency were not built?  Alternatively, if mbedtls is going to be built by variants, shouldn't mbedtls be selected and configured?

I'll submit a PR in a little while to skip the Makefile reconfiguration of mbedtls_config.h if nothing has been configured, since that produces a broken build when mbedtls is not configured in `make menuconfig` and then a build of mbedtls is manually triggered.

**Comment by neheb** [comment]
It's an unfortunate consequence of having packages support multiple backends and the build system building them, even when not selected. I don't remember the full details but I believe this is caused by ustream-ssl.

**Comment by gstrauss** [comment]
#11256 fixes the mbedtls build for builds without mbedlts selected and configured.

@neheb, sorry, I did not know earlier to test that use case.

**Pull request closed without merging**
