### PR TITLE
Fixed mwlwifi loading with backports v5.3

### PR DESCRIPTION
**Pull request by borkra**
Signed-off-by: Boris Krasnovskiy <borkra@gmail.com>

### CODE REVIEW

**Comment by dengqf6** [comment]
Please open a pull request at https://github.com/kaloz/mwlwifi

**Comment by lantis1008** [comment]
> Please open a pull request at https://github.com/kaloz/mwlwifi

While that is good advice, given the current situation with the driver and Marvell, the likelihood of any movement occurring is low, so patching here is the right move until/if upstream is ever fixed.

**Comment by borkra** [comment]
This not fixable in mwlwifi. The new parameter was added in kernel 5.3, which did not exist before.

So yes we #if on a kernel version. But that will not help here, as here we have backports, and kernel version did not change.

**Comment by borkra** [comment]
Current master builds break mvebu routers, so please do something ASAP or revert backports v5.3 commit or add this.

**Comment by borkra** [comment]
I submitted pull request on mwlwifi (https://github.com/kaloz/mwlwifi/pull/369), but again this will not eliminate need in some patch in openwrt as it is using backports and BACKPORTED_KERNEL_VERSION != KERNEL_VERSION

**Comment by dengqf6** [comment]
Is there a version macro in backports.git that we can use?

**Comment by hauke** [comment]
Please try it with this policy: mwl_vendor_attr_policy instead of VENDOR_CMD_RAW_DATA

**Comment by borkra** [comment]
Yes, and No.
Yes there is a macro if driver would be compiled inside backports Kconfig space. But that would require driver to be handled by backports package itself. And even then then there are patches that bundled inside backports package. 
That is not what have been decided to do, mwlwifi is compiled outside backports package space and Kconfig space, so all backports related patches would need to be done at the package level.

**Comment by borkra** [comment]
@hauke yes it works with mwl_vendor_attr_policy, I updated the patch.

**Comment by hauke** [comment]
Thank you your patch was applied to master with some modifications to the commit description.

**Pull request closed without merging**
