### PR TITLE
uci: add uci_revert function

### PR DESCRIPTION
**Pull request by feckert**
@aparcar Add missing `uci_revert` shell function wrapper.

### CODE REVIEW

**Comment by aparcar** [comment]
What's the advantage?

**Comment by feckert** [comment]
@aparcar I use this functions for upgrade scripts on my systems.
If I want to revert my previous steps, I have done during upgrade handling, this is not possible to use this with the uci wrapper functions.

The revert wrapper is only available for the state [`uci_revert_state`](https://github.com/openwrt/openwrt/blob/982578994a03a3be662e8074ec23a8346c849cca/package/system/uci/files/lib/config/uci.sh#L55).

The change unifies the API for the uci wrappers and the missing `uci_revert` function without state

**Comment by aparcar** [comment]
Consider using AUTORELEASE or bump PKG release

**Comment by feckert** [comment]
> Consider using AUTORELEASE or bump PKG release

@aparcar Already done https://github.com/openwrt/openwrt/pull/4295/files#diff-f83c2ac157e56d1ae1f1fc7db5bd903784d50c2bfacf7cac609476764028bd8eR12

**Comment by aparcar** [comment]
Merged, thanks!

Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (10/10), 765 bytes | 255.00 KiB/s, done.
Total 10 (delta 5), reused 0 (delta 0), pack-reused 0
remote: *** no recipients configured so no email will be sent
remote: *** for 'refs/heads/master' update f0f1d68d528402b4d51a1dd08d2e2c9034167f92->92ac2a20ebba9f8695b464041cc8aeb30bb85576
remote: To github.com:openwrt/openwrt.git
remote:    f0f1d68d52..92ac2a20eb  master -> master
remote: To github.com:lede-project/source.git
remote:    f0f1d68d52..92ac2a20eb  master -> master
To git.openwrt.org:openwrt/openwrt.git
   f0f1d68d52..92ac2a20eb  master -> master

**Pull request closed without merging**
