### PR TITLE
fix hanging uqmi, see #17939

### PR DESCRIPTION
**Pull request by dr-ni**
can you fix this issue?

### CODE REVIEW

**Comment by Leo-PL** [comment]
We should definitely use the timeout option instead. I prefer adding it to the first access.

This patch has formal issues - I can whip up a cleaner version sometime later this week, as I've been observing timeouts on ZTE QMI modems from time to time.

**Comment by dr-ni** [comment]
I have now changed to the timeout option...

**Comment by Leo-PL** [comment]
The patch has some formal issues - I can deal with them and submit my patch - could you help testing it? It seems that my devices exhibit those issues rarely.

**Comment by dr-ni** [comment]
yes of course I can help testing. Tell me what I can do...

**Comment by Leo-PL** [comment]
Okay, I'll try to whip it up sometime this week. It'll be enough to copy over uqmi.sh for testing over current `main`.

**Comment by dr-ni** [comment]
I'm on:
Model	Linksys WRT3200ACM
Architecture	ARMv7 Processor rev 1 (v7l)
Target Platform	mvebu/cortexa9
Firmware Version	OpenWrt 23.05.0-rc3 r23389-5deed175a5 / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8
Kernel Version	5.15.127

and it's starting now without any issues

Bildschirmfoto zu 2023-09-12 21-45-57

**Comment by Leo-PL** [comment]
What is the LTE modem you use? This is the part which matters most.

**Comment by xback** [comment]
To give some background on the issue.
I've adapted used the perl scripts so it generates a library form of this code. (Includingbthe eventd now)

The fun part is that is easily allows to step through in readable easy C without to much replacement and allows easy analysis, debugging and adjustment.

The main issue is that each time communication begins at the start, the "sync" command is provided to erase any clients connected to a specific service.

No the bug is that *all* modems using qmi do not reply on the 1st "sync" but they do on subsequent.
"No reply" as in : qmi does not send anything back on the bus the 1ste time.

There are 2 fixes needed in uqmi to fix this once and for all
- send "sync" twice
- use "poll" to wait for 2 FD's
- 1) a pipeline FD which can be set by a signal handler
- 2) the fd of the qmi device

Set the timeout to 20 seconds for:
- scan command
- connect command (WDS)

Set the timeout to 1 sec for all others


I'm using this way of working in my code using this generated lib and it has been working for years without any hang or hiccup on hundreds of devices from 3G up to 5G SA and on various modems (quectel, sierra, Telit, tdtech, fibocom, ..)

**Comment by dr-ni** [comment]
> What is the LTE modem you use? This is the part which matters most.

I'm using a SIMCOM SIM7600G-H R2 CAT4 4G/LTE USB 150Mbps WORLD minipci-express MDM9207

**Comment by hauke** [comment]
Pleas squash the commits together into one commit

**Comment by dr-ni** [comment]
I'm afraid - I have now squashed all upstream changes - how can I fix this?

**Comment by Leo-PL** [comment]
It wasn't about that - @hauke meant to squash only your changes (the later fixes) into your first commit.
Use `git reset --hard fadec48` on your branch, and then do `git rebase -i main` and replace all but first `pick` with `squash`.
While at that, the patch needs proper commit description to be accepted. See here for howto: https://openwrt.org/submitting-patches

**Comment by dr-ni** [comment]
I've managed the reset (then pushed) but `git rebase -i main` failes  with unknown main
with master I'm getting noop

**Comment by Leo-PL** [comment]
Then maybe just rebasing on master or main should rectify this.

**Comment by Leo-PL** [comment]
@xback could you take look at this? http://github.com/Leo-PL/openwrt/tree/uqmi-timeout-fixes
Still need to add retry to `start-network` part, but I'd like to know if general concept is OK.

**Comment by dr-ni** [comment]
`git rebase -i main` fatal: no Upstream 'main'

`git rebase -i main` 

```
noop

# Rebase von fadec484f4..fadec484f4 auf fadec484f4 (1 Kommando)
#
# Befehle:
# p, pick <Commit> = Commit verwenden
# r, reword <Commit> = Commit verwenden, aber Commit-Beschreibung bearbeiten
# e, edit <Commit> = Commit verwenden, aber zum Nachbessern anhalten
# s, squash <Commit> = Commit verwenden, aber mit vorherigem Commit vereinen
# f, fixup <Commit> = wie "squash", aber diese Commit-Beschreibung verwerfen
# x, exec <Commit> = Befehl (Rest der Zeile) mittels Shell ausführen
# b, break = hier anhalten (Rebase später mit 'git rebase --continue' fortsetze>
# d, drop <Commit> = Commit entfernen
# l, label <Label> = aktuellen HEAD mit Label versehen
# t, reset <Label> = HEAD zu einem Label umsetzen
# m, merge [-C <Commit> | -c <Commit>] <Label> [# <eineZeile>]
# .       Merge-Commit mit der originalen Merge-Commit-Beschreibung erstellen
# .       (oder die eine Zeile, wenn keine originale Merge-Commit-Beschreibung
# .       spezifiziert ist). Benutzen Sie -c <Commit> zum Bearbeiten der
# .       Commit-Beschreibung.

```

**Comment by dr-ni** [comment]
> @xback could you take look at this? [http://github.com/Leo-PL/openwrt/tree/uqmi-timeout-fixes](https://github.com/Leo-PL/openwrt/tree/uqmi-timeout-fixes) Still need to add retry to `start-network` part, but I'd like to know if general concept is OK.

I'll also check your version tomorrow

**Comment by Leo-PL** [comment]
This is definitely not yet ready to use.
Also, `main` and `master` point at the same commit, maybe you haven't checked out main - either is fine. You can `git reset --hard again` and try again, but frankly - I have no idea how to throw out the merge commits you made at this time.

**Comment by dr-ni** [comment]
> This is definitely not yet ready to use. Also, `main` and `master` point at the same commit, maybe you haven't checked out main - either is fine. You can `git reset --hard again` and try again, but frankly - I have no idea how to throw out the merge commits you made at this time.

now managed to throw out all upstream changes, however rebase -i master => still noop

**Comment by dr-ni** [comment]
sorry auto closed while removed dead commit

**Comment by dr-ni** [comment]
sorry again, now hopefully ok

**Comment by hauke** [comment]
Please describe in the commit description why you need the change and what problem it fixes.

**Comment by dr-ni** [comment]
OMG what is now the provlem?
I never ever had so much efford to update one line of code...

**Comment by dr-ni** [comment]
why is the automatic test always failing?

**Comment by dr-ni** [comment]
> @xback could you take look at this? [http://github.com/Leo-PL/openwrt/tree/uqmi-timeout-fixes](https://github.com/Leo-PL/openwrt/tree/uqmi-timeout-fixes) Still need to add retry to `start-network` part, but I'd like to know if general concept is OK.

I have tested and fixed your versiob, see:
https://github.com/openwrt/openwrt/pull/13781/commits/c8b0e92a708fa3d473dd48db679ae11d9b76fb77

**Comment by xback** [comment]
> > @xback could you take look at this? [http://github.com/Leo-PL/openwrt/tree/uqmi-timeout-fixes](https://github.com/Leo-PL/openwrt/tree/uqmi-timeout-fixes) Still need to add retry to `start-network` part, but I'd like to know if general concept is OK.
> 
> I have tested and fixed your version, see: #13781

I'll try to take a look on Monday.
(I'm a bit overloaded at work currently.)

**Pull request merged**
