### PR TITLE
apk: Make new config files suffix defineable and set it to -apk-new

### LINKED ISSUE #17033: apk: Re-installing a package with a config in /etc/config breaks uci
### Describe the bug

When re-installing a package that comes with a config file in `/etc/config`, in my case `stubby`, then a backup of the existing config file is created with the name `/etc/config/stubby.apk-new`.

After that happened, most of my `uci` commands failed with `invalid argument`, especially `uci commit` and `reload_config`. Thus, removing any ability to make changes to any services.

After removing the `stubby.apk-new` file, uci returned to normal behavior.

According to the IRC, this is normal behavior for `apk` to backup files and the error lies within `uci` as it doesn't know about this behavior and assumes the `opkg` way, which was just a `.opkg` extension.

### OpenWrt version

r28091-77cfe8fd15

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

Bananapi BPI-R4

### Image kind

Official downloaded image

### Steps to reproduce

- `apk add stubby`
- `apk del stubby`
- `apk add stubby`
- `uci commit`

### Actual behaviour

`uci commit` fails with `invalid argument`.

### Expected behaviour

`uci commit` succeeds without error.

### Additional info

_No response_

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by hnyman**
This PR fixes the uci incompatibility with the new config file's suffix ".apk-new" that is used when installing a package that already has a config file.

VERSION 2: 

**One upstreamable patch that just changes the 4 separate literals to one definition**
 
`apk: Add configuration for the suffix of a new config file`

Add configuration possibility to the suffix of a new config file that is installed along a package, when there already exists a config file that should not get overwritten, and the new config file need to get added with a suffix.

Define the option as a preprocessor define, so that it can be also set via compiler command line.

The default value stays ".apk-new".

**Makefile change**

Set "-apk-new" as the new default suffix in OpenWrt.
Apk's default is ".apk-new" that chokes uci.

The first commit could be upstreamed to apk-tools.

<del>In place of the second commit there could maybe be a compile-time configuratin options from Makefile that sets the suffix, and that would be used instead, as  the definition in .h might be inside `#if !defined`</del>

Now just a Makefile change is needed, no permanent patch  (if the the first gets upstreamed)

This should fix #17033

-----
Proof:
```
root@router5:~# ls /etc/config/us*
/etc/config/usteer    /etc/config/usteer-opkg

root@router5:~# apk del usteer
OK: 69 MiB in 312 packages
root@router5:~# apk add usteer
(1/1) Installing usteer (2022.08.18~7d2b17c9-r1)
usteer-2022.08.18~7d2b17c9-r1: installing file to etc/config/usteer-apk-new
Executing usteer-2022.08.18~7d2b17c9-r1.post-install
OK: 70 MiB in 313 packages

root@router5:~# ls /etc/config/us*
/etc/config/usteer     /etc/config/usteer-apk-new  /etc/config/usteer-opkg
```

### CODE REVIEW

**Comment by hnyman** [comment]
I made a second version if this.
Now there is just one (hopefully) upstreamable patch and a Makefile change.

**Comment by hnyman** [comment]
Any feedback on this?
Should this be proposed to upstream apk?

**Comment by robimarko** [comment]
I aint not expert, but I would send this upstream and see what they have to say, if its fine by them then great for us

**Comment by KanjiMonster** [comment]
It might make sense (not for us directly) to have the divider/suffix configurable per package. E.g. `sudo` will only ignore files in `/etc/sudoers.d` if they contain a `.`, so if you were shipping files there, you would want to have the package copy to have a `.` so it doesn't get applied as well (potentially undoing any user changes).

Might be thinkable that different programs have different constraints, and there is no one suffix that works side effect free for everything.

**Comment by KanjiMonster** [comment]
Another alternative would be to store all default config files in a separate directory instead of alongside the modified configuration files, but that will definitely increase the storage usage further.

**Comment by Ansuel** [comment]
Honestly this seems a fragility of uci itself... those kind of file should be ignored and not parsed at all...

the .apk-new is similar to other implementation like .dpkg-new 

I will check what are the effort for making uci ignore those files.

**Comment by hnyman** [comment]
I made an apk merge request: 
https://gitlab.alpinelinux.org/alpine/apk-tools/-/merge_requests/251
Let's see what upstream apk thinks.

**Comment by Ansuel** [comment]
Can someone test this 
https://gist.github.com/Ansuel/9e9273f38e1416b0a5dcf0887b4b6bd6

**Comment by Ansuel** [comment]
@hnyman did you find time to test this?

**Comment by hnyman** [comment]
Seems to work.
(I compiled uci with your patch, and then normal apk without my own fix.)

**Comment by Ansuel** [comment]
And you did those test with add remove?

**Comment by hnyman** [comment]
Yeah, pretty much the same thing again with stubby. Couldn't retrigger the uci commit failure ;-)

**Comment by Ansuel** [comment]
Nice. I will merge that change in uci and push update. I would love to print some warning but that is problematic for parsing...

**Comment by hnyman** [comment]
I will close this, as the uci fix from Ansuel should take care of the underlying problem in uci.

**Pull request closed without merging**
