### PR TITLE
tools/expat: update to 2.4.7

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
ping @stintel this should fix your issue with gdb.

**Comment by Grommish** [comment]
I can't speak to the version bump, but enabling `EXPAT_DTD` fixed the issue outlined https://forum.openwrt.org/t/scripts-remote-gdb-fails-with-gdb-error-xml-useforeigndtd-failed/122325

**Comment by hauke** [comment]
Could you please split this into two commits, one to fix the gdb bug and the other for the update.

**Comment by neheb** [comment]
Done.

**Comment by nbd168** [comment]
Applied, thanks

**Pull request closed without merging**
