### PR TITLE
kernel: modules: hwmon-core: set a poweroff delay greater than 0

### PR DESCRIPTION
**Pull request by danitool**
The thermal emergency poweroff needs a delay with a positive value or it won't work otherwise.

If we use the 0 default value, when the critical temperature is reached the device won't be able to poweroff and could cause physical damage.

Set a 10 ms delay. Tested succesfully in a Buffalo Linkstation (mvebu target).

### CODE REVIEW

**Comment by chunkeey** [comment]
this sounds broken? The kernel's description for [THERMAL_EMERGENCY_POWEROFF_DELAY_MS](https://cateee.net/lkddb/web-lkddb/THERMAL_EMERGENCY_POWEROFF_DELAY_MS.html)

>Thermal subsystem will issue a graceful shutdown when critical temperatures are reached using orderly_poweroff(). In >case of failure of an orderly_poweroff(), the thermal emergency poweroff kicks in after a delay has elapsed and shuts >down the system. This config is number of milliseconds to delay before emergency poweroff kicks in. Similarly to the >critical trip point, the delay should be carefully profiled so as to give adequate time for orderly_poweroff() to finish on >regular execution. If set to 0 emergency poweroff will not be supported.
>
>In doubt, leave as 0.

So, when the critical temperature tripping point is reached, it should issue a "orderly_poweroff()" already. The THERMAL_EMERGENCY_POWEROFF_DELAY_MS is there as a fallback, in case the orderly_poweroff() does nothing
within in that specified time. (I do unterstand that shutting down to prevent hardware damage is important, that
said 10 ms is extremely short.)

**Comment by danitool** [comment]
Hi @chunkeey, I can't say if the thermal emergency poweroff is broken. I would say it worked in the past without the delay (maybe in the 21.02 release). But in 22.03 and snapshots, when the critical temperature is reached, it throws kernel messages but no poweroff is performed.

The CONFIG_THERMAL_WRITABLE_TRIPS kernel option should also be set (in another patch) to allow configuring thermal trips from userspace. This allows easier testing this feature among other things.

Should I apply this patch only on the target I've tested it?

**Comment by chunkeey** [comment]
> I can't say if the thermal emergency poweroff is broken. I would say it worked in the past without the delay (maybe in the 21.02 release). But in 22.03 and snapshots, when the critical temperature is reached, it throws kernel messages but no poweroff is performed.

Ok, this sounds like something did indeed break. From the description the THERMAL_EMERGENCY_POWEROFF_DELAY_MS is a fallback... for a fallback. But then what are you going to do otherwise?! Just watching the magic smoke escape? 

Are the messages you are getting contain some of the following strings?

    ...critical temperature reached, shutting down...
    ...HARDWARE PROTECTION shutdown...

and can you normally shutdown the device via /sbin/poweroff (or this it hang, i.e. is it waiting for a (net)fs or something?)?

(From the codes POV, if the temperature has tripped the critical trip point, the kernel initiates usually lands in  [thermal_zone_device_critical()](https://elixir.bootlin.com/linux/v5.15.111/C/ident/thermal_zone_device_critical)
from there it goes through [hw_protection_shutdown()](https://elixir.bootlin.com/linux/v5.15.111/C/ident/hw_protection_shutdown). if THERMAL_EMERGENCY_POWEROFF_DELAY_MS has a delay is set, then it sets up a delayed workqueue item which will forcefully shutdown/reboot after the delay has elapsed (through the kernels own API). But regardless of that, it will always call orderly_shutdown(true). Which will call the userspace utility /sbin/poweroff to initiate the orderly poweroff so hopefully no data loss happens.

**Comment by danitool** [comment]
I made a snapshot clean build with default packages and the default config but with *CONFIG_THERMAL_WRITABLE_TRIPS* enabled to allow test this. I couldn't reproduce this issue anymore:

```
root@OpenWrt:~# echo 40000 > /sys/class/thermal/thermal_zone1/trip_point_1_temp 
root@OpenWrt:~# Connection to 192.168.1.1 closed by remote host.
Connection to 192.168.1.1 closed.
```
At the serial console, (the poweroff is ok):
```
 
[  203.741856] thermal thermal_zone1: ethphy-thermal: critical temperature reached, shutting down
[  203.750581] reboot: HARDWARE PROTECTION shutdown (Temperature too high)
[  204.165148] nfsd: last server has exited, flushing export cache
[  204.522152] br-lan: port 1(eth0) entered disabled state
[  204.535521] device eth0 left promiscuous mode
[  204.540005] br-lan: port 1(eth0) entered disabled state
[  204.560201] mvneta d0074000.ethernet eth0: Link is Down
[  208.834559] reboot: Power down
[  208.838395] reboot: Restarting system with command 'Power off'
```

Thanks for reviewing.

Closing.

**Pull request closed without merging**
