### PR TITLE
kernel: compress ubifs using zstd by default

### PR DESCRIPTION
**Pull request by rsalvaterra**
Add two kernel patches, in order to enable ubifs zstd compression by default (previously it defaulted to lzo). Also centralise the compression configuration in the generic kconfigs. This will make disabling lzo and zlib easier, in the future.

### CODE REVIEW

**Comment by rsalvaterra** [comment]
@hauke, I think this is ready for consumption, let me know if anything else is needed.

**Comment by dengqf6** [comment]
This will break sysupgrade.

**Comment by rsalvaterra** [comment]
No, it won't. The filesystem is reformatted on sysupgrade. I've tested on a
Redmi AC2100 with no issues whatsoever.

A segunda, 5/04/2021, 07:55, DENG Qingfang ***@***.***>
escreveu:

**Comment by rsalvaterra** [comment]
However, assuming I was just lucky, how do we introduce these kinds of structural changes? With a `compat_version` bump?

**Comment by dengqf6** [comment]
> No, it won't. The filesystem is reformatted on sysupgrade. I've tested on a
> Redmi AC2100 with no issues whatsoever (and, by the way, ramips/mt7621 is the only NAND target which doesn't have zstd enabled in ubifs).

Did you only test if it boots? On my end it fails to mount ubifs as overlay and falls back to tmpfs (RAM).
We are going from ubifs with lzo/zlib support, to _only_ zstd support. sysupgrade knows nothing about what is supported in the new image.

**Comment by rsalvaterra** [comment]
> Did you only test if it boots? On my end it fails to mount ubifs as overlay and falls back to tmpfs (RAM).

Like I said, in my case I didn't have any issues, it mounted the overlay just fine, but I could have been lucky.

> We are going from ubifs with lzo/zlib support, to _only_ zstd support. sysupgrade knows nothing about what is supported in the new image.

I see. But sysupgrade needs to mount the ubifs overlay for restoring the backed up configuration. Assuming zstd is supported in all NAND/ubifs targets, what's keeping sysupgrade from mounting the overlay with forced zstd compression (`compr=zstd`), in order to make sure the volume only uses zstd, even if other algorithms are supported?

**Comment by hauke** [comment]
When you have 21.02 installed the ubifs uses lzo/zlib. When you do a sysupgrade to master it will boot up the system with the new kernel which only supports zstd and can not mount the zlib partition.
When we switched from UBI FS format v4 to v5 we stayed at V4 for some time to allow downgrades with sysupgrade.

I would suggest to active CONFIG_UBIFS_FS_ZSTD only in addition for now and use it by default.

**Comment by adschm** [comment]
"treewide:" should be enough for the second patch (and maybe without the exclamation mark ...?)

**Comment by adschm** [comment]
"kernel/generic:" -> "kernel:"

**Comment by rsalvaterra** [comment]
> "treewide:" should be enough for the second patch (and maybe without the exclamation mark ...?)

Hold on, this is going to be something completely different… working on it.

**Comment by rsalvaterra** [comment]
@adschm, I sent [this patch](https://lore.kernel.org/linux-mtd/20210405152935.148129-1-rsalvaterra@gmail.com/) upstream and backported it to OpenWrt master (5.4 and 5.10) in my tree. It would be nice if we could get it in for 21.x, as we could then drop lzo and zlib from ubifs for the next release. Thoughts?

**Comment by rsalvaterra** [comment]
Rebased on top of current master.

**Comment by rsalvaterra** [comment]
Moved the patches from `pending-5.{4,10}` to `backport-5.{4,10}`, now that the kernel patch has been [accepted upstream](https://lore.kernel.org/linux-mtd/CAFLxGvwhtRY-6kT-sN=AgjvyssHb5qdTS6WQHkhKu3YrPuTkdw@mail.gmail.com/).

**Comment by adschm** [comment]
> ubifs: default to zstd compression

"kernel: ..."

**Comment by rsalvaterra** [comment]
> "kernel: ..."

Done.

**Comment by rsalvaterra** [comment]
Rebased on top of current master, also including lantiq/{xrx200,xway}/config-5.10.

**Comment by ldir-EDB0** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ldir.git

**Pull request closed without merging**
