### PR TITLE
kernel: bump 5.15 to 5.15.53

### PR DESCRIPTION
**Pull request by rsalvaterra**
Manually rebased:
bcm27xx/patches-5.15/950-0078-BCM2708-Add-core-Device-Tree-support.patch

Signed-off-by: John Audia \<therealgraysky@proton.me\>
Signed-off-by: Marty Jones \<mj8263788@gmail.com\>
Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by jospezial** [comment]
5.15.51 released

**Comment by rsalvaterra** [comment]
@graysky2, please take a look. I took your 5.15.51 bump and massaged it a bit so the patch rebasing is cleaner. Haven't build-tested yet, though.

**Comment by rsalvaterra** [comment]
Force-pushed to fix authorship.

**Comment by graysky2** [comment]
My bump never built.  This does not either, erroring out at the same place mine did (see github comments on my commit for reference).  Here is what I get with this PR:
```
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/kernel/head.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/kernel/smccc-call.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/clear_page.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/clear_user.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/copy_from_user.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/copy_page.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/copy_to_user.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memchr.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memcmp.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memcpy.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memset.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strchr.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strcmp.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strlen.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strncmp.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strnlen.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strrchr.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/tishift.o' being placed in section `__ksymtab_strings'
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/kernel/head.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/kernel/smccc-call.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/clear_page.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/clear_user.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/copy_from_user.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/copy_page.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/copy_to_user.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memchr.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memcmp.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memcpy.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memset.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strchr.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strcmp.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strlen.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strncmp.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strnlen.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strrchr.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/tishift.o' being placed in section `__ksymtab_strings'
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      vmlinux
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/kernel/head.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/kernel/smccc-call.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/clear_page.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/clear_user.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/copy_from_user.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/copy_page.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/copy_to_user.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memchr.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memcmp.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memcpy.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memset.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strchr.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strcmp.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strlen.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strncmp.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strnlen.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strrchr.o' being placed in section `__ksymtab_strings'
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/tishift.o' being placed in section `__ksymtab_strings'
  SORTTAB vmlinux
  SYSMAP  System.map
  OBJCOPY arch/arm64/boot/Image
scripts/Makefile.build:44: arch/arm64/boot/dts/overlays/Makefile: No such file or directory
make[7]: *** No rule to make target 'arch/arm64/boot/dts/overlays/Makefile'.  Stop.
make[6]: *** [scripts/Makefile.build:551: arch/arm64/boot/dts/overlays] Error 2
make[5]: *** [Makefile:1410: dtbs] Error 2
make[5]: Leaving directory '/scratch/union/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/linux-5.15.52'
make[4]: *** [Makefile:34: /scratch/union/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/linux-5.15.52/.modules] Error 2
make[4]: Leaving directory '/scratch/union/target/linux/bcm27xx'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/scratch/union/target/linux'
time: target/linux/compile#566.20#49.04#617.80
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/scratch/union'
make[1]: *** [target/Makefile:23: /scratch/union/staging_dir/target-aarch64_cortex-a72_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/scratch/union'
make: *** [/scratch/union/include/toplevel.mk:230: world] Error 2
```

**Comment by graysky2** [comment]
@Ansuel - Do you have any insights into the build error?

**Comment by hauke** [comment]
I applied the first patch in commit 90a63504230ed31303bf7978658ba5db74f54f84 to master.

**Comment by ldir-EDB0** [comment]
.52 appears to stop ksmbd from building as well

**Comment by mj22226** [comment]
@graysky2 `bcm27xx/patches-5.15/950-0078-BCM2708-Add-core-Device-Tree-support.patch `mismatch with mine
```
diff --git a/target/linux/bcm27xx/patches-5.15/950-0078-BCM2708-Add-core-Device-Tree-support.patch b/target/linux/bcm27xx/patches-5.15/950-0078-BCM2708-Add-core-Device-Tree-support.patch
index 55ff91028f..e6b8a4d6d4 100644
--- a/target/linux/bcm27xx/patches-5.15/950-0078-BCM2708-Add-core-Device-Tree-support.patch
+++ b/target/linux/bcm27xx/patches-5.15/950-0078-BCM2708-Add-core-Device-Tree-support.patch
@@ -4003,12 +4003,12 @@ index f4d2fc20397c..bed192b085df 100644
 -&expgpio {
 -	gpio-line-names = "BT_ON",
 -			  "WL_ON",
--			  "",
+-			  "PWR_LED_OFF",
 -			  "GLOBAL_RESET",
 -			  "VDD_SD_IO_SEL",
--			  "CAM_GPIO",
+-			  "GLOBAL_SHUTDOWN",
 -			  "SD_PWR_ON",
--			  "SD_OC_N";
+-			  "SHUTDOWN_REQUEST";
 +&pwm1 {
 +	status = "disabled";
 +};
```
`bcm27xx/patches-5.15/950-0577-ARM-dts-Update-rpi-400-and-cm4-dts-to-match-4-b.patch` is untouched

**Comment by mj22226** [comment]
> - Can you share the entire commit from your update?

@graysky2 I only edited manually the 950-0078 patch https://gist.github.com/mj22226/571d3bb6fa8b5f313ccbeac883ce92d6

**Comment by graysky2** [comment]
Thanks @mj22226, I applied your patch and updated the rest of them here:  https://github.com/graysky2/openwrt/commits/bump
Everything seems to be working as expected. :+1: 

@rsalvaterra - Do you want to pull from mine to update this PR or do you want to close this PR and I will send through a new one?

**Comment by rsalvaterra** [comment]
Alright, done.

**Comment by graysky2** [comment]
5.15.53
```
Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200
```

**Comment by rsalvaterra** [comment]
@ldir-EDB0, I see. I'll rebase on current master and update.

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 552d76f2bebe182ce9352aed357268f97d2c626f, 2fc6d9912a3ee4adfb86443d9dcbcc8ff23c2a23 and 3e9ad2cdce569e7272d2f34ea5feaef7cd531219.

**Pull request closed without merging**
