### PR TITLE
trace-cmd: update to 3.3

### PR DESCRIPTION
**Pull request by neheb**
Use local tarballs instead of upstream generated ones. Smaller.

Fix version to be compatible with apk.

ping @aparcar

### CODE REVIEW

**Comment by aparcar** [comment]
LGTM

**Comment by aparcar** [comment]
I'm seeing a different PKG_HASH

```diff
diff --git a/package/devel/trace-cmd/Makefile b/package/devel/trace-cmd/Makefile
index 22d37752e6..76fdcb6b31 100644
--- a/package/devel/trace-cmd/Makefile
+++ b/package/devel/trace-cmd/Makefile
@@ -7,7 +7,7 @@ PKG_RELEASE:=1
 PKG_SOURCE_PROTO:=git
 PKG_SOURCE_VERSION:=$(PKG_NAME)-v$(PKG_VERSION)
 PKG_SOURCE_URL:=https://git.kernel.org/pub/scm/utils/trace-cmd/trace-cmd
-PKG_MIRROR_HASH:=7a4f9c3a18a01012cd76ab9a0a2c4447aed8293d005679d5228ef2aef243445c
+PKG_MIRROR_HASH:=c5c2ea348bfd877697f451f9d66ade84d80bc7889549cd46acc0916d0f7afd10
 
 PKG_LICENSE:=GPL-2.0-only
 PKG_LICENSE_FILES:=COPYING
```

**Comment by neheb** [comment]
@feckert had a similar problem. OS zstd was leaking into the build.

**Comment by robimarko** [comment]
Make sure that OpenWrt ZSTD is built, otherwise you will be using the host one and get a different hash.

**Comment by aparcar** [comment]
Wait zstd is not reproducible by default?

**Comment by robimarko** [comment]
> Wait zstd is not reproducible by default?

This is the latest from:
https://github.com/facebook/zstd/issues/4099#issuecomment-2284686248

```
Exact same binary representation is only an objective with the following conditions :

same compression level
same library version
same parameters
```

Basically, they don't guarantee binary reproducibility between different versions.

**Comment by neheb** [comment]
Well, that makes sense given that they improve compression with each new version. bzip2, gzip, zlib are bugfix only I believe. I could be wrong but I think xz manipulates filters with different versions. zstd is always improving.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
