### PR TITLE
rockchip: switch to 5.15 kernel

### PR DESCRIPTION
**Pull request by TLarg**
Tested on NanoPI R4S

### CODE REVIEW

**Comment by shark873** [comment]
Tested on NanoPI R4S as well, boots properly with any config file, while the original PR -> https://github.com/openwrt/openwrt/pull/9626 <- would only boot with a minimal config file.

But since you are switching to kernel 5.15 instead of using it as testing kernel, don't you need to remove 5.10?

**Comment by TLarg** [comment]
> But since you are switching to kernel 5.15 instead of using it as testing kernel, don't you need to remove 5.10?

@shark873 clean up the old kernel does not affect for testing this PR it can be done later on.

**Comment by wurzerj** [comment]
Also tested on NaniPi R4S. I successfully built and tested both a minimal build and my standard build including all packages I typically use. Both boot without any problems and seem to be stable. Thanks for the config fix. As already mentioned by @shark873 you should remove the 5.10 patches.

**Comment by AntonyFl** [comment]
Tested on the NanoPi R2S, without this patch the testing kernel 5.15 brakes on of the R2S LAN ports

**Comment by shark873** [comment]
@blocktrron hi, can you take a look here?

This PR, is a supplementary one that fixes issues from the original one:

https://github.com/openwrt/openwrt/pull/9626

That you merged before.

**Review by ProKn1fe — APPROVED** [review]
LGTM

**Comment by wurzerj** [comment]
I tested it again, using latest master and kernel 5.15.60 on my R4S. Still works.

**Review by Fail-Safe — APPROVED** [review]

**Comment by lucize** [comment]
@PolynomialDivision, @hauke do we still need to keep this working PR open for such a long time ?

**Comment by blocktrron** [comment]
Merged, thanks!

**Pull request closed without merging**
