### PR TITLE
ramips: bdcom-wap2100: Fixes and improvements

### PR DESCRIPTION
**Pull request by ynezz**
Hi @mkresin,

thank you for your board support improvements, unfortunately it has rendered the board unbootable due to the missing `compatible` property in the `partitions` node. So this PR fixes that boot failure, and while touching that device again, I'm adding back SUPPORTED_DEVICES variable which you've (accidentally?) removed during your improvements session also. I've also added proper partition format to the `firmware` partition and enabled 5GHz radio.

Cheers, Petr

### CODE REVIEW

**Comment by mkresin** [comment]
Dammit, I should have noticed the missing `fixed-partitions` compatible. The `SUPPORT_DEVICES` isn't required. The very same value is set based on the device define in https://github.com/openwrt/openwrt/blob/master/target/linux/ramips/image/Makefile#L42.

**Comment by mkresin** [comment]
I've fixed the whitespace issues in "ramips: bdcom-wap2100: Enable mt7610e 5GHz radio", selected only the required mt76 drivers with regards to #1468 and pushed the result to [my staging tree](https://git.openwrt.org/?p=openwrt/staging/mkresin.git;a=summary).

Would you please compile an image from my staging tree and confirm that everything still works as expected.

**Comment by ynezz** [comment]
> The SUPPORT_DEVICES isn't required

Nice, so could I prepare patch which would remove all `SUPPORTED_DEVICES` from the image makefiles and enable `REQUIRE_IMAGE_METADATA=1` for sysupgrade by default for `ramips` platform?

> Would you please compile an image from my staging tree and confirm that everything still works as expected.

Yes, it's working.

```
root@OpenWrt:/# cat /etc/openwrt_version 
r8598-2493547
```

**Comment by mkresin** [comment]
> Nice, so could I prepare patch which would remove all SUPPORTED_DEVICES from the image makefiles

No please not. I migrated some board to generic board detection as I've done it with your board. But older images still using the former used userspace board name and expect the former used name present in the image metadata. Otherwise an upgrade from e.g OpenWrt 18.06 would be refused. Commit 509d02a3 is such an example. Please note the `SUPPORTED_DEVICES +=' which adds the former used board name ("u7621-06-256M-16M") in addition to the auto generated  the auto generated "unielec,u7621-06-256m-16m".

> and enable REQUIRE_IMAGE_METADATA=1 for sysupgrade by default for ramips platform?

We still have four ramips boards using [legacy image build code](https://github.com/openwrt/openwrt/blob/master/target/linux/ramips/image/rt305x-legacy.mk), which isn't aware of the image metadata. 

They either need to be converted to the new image build code or dropped. Since nobody took care of these during the last 1.5 years, I rather tend to drop them.

**Comment by mkresin** [comment]
merged, thanks!

**Comment by ynezz** [comment]
> We still have four ramips boards using legacy image build code, which isn't aware of the image metadata.

Ok, noted.

> I rather tend to drop them.

Or we could just exclude them and enable metadata checking for the rest.

```
diff --git a/target/linux/ramips/base-files/lib/upgrade/platform.sh b/target/linux/ramips/base-files/lib/upgrade/platform.sh
index e28f066..9f36c47 100755
--- a/target/linux/ramips/base-files/lib/upgrade/platform.sh
+++ b/target/linux/ramips/base-files/lib/upgrade/platform.sh
@@ -4,6 +4,23 @@
 
 PART_NAME=firmware
 
+enable_image_metadata_check() {
+       local board=$(board_name)
+
+       case "$board" in
+       all0239-3g|\
+       dcs-930|\
+       dcs-930l-b1|\
+       wl-341v3)
+               REQUIRE_IMAGE_METADATA=0
+               ;;
+       *)
+               REQUIRE_IMAGE_METADATA=1
+               ;;
+       esac
+}
+enable_image_metadata_check
```

**Pull request closed without merging**
