### PR TITLE
curl: move package to packages.git

### PR DESCRIPTION
**Pull request by aparcar**
curl is replaced by uclient-fetch within the OpenWrt build system and we
can therefore move curl to packages.git. This is based on the Hamburg
2019 decision that non essential packages should move outside base.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Review by dangowrt — APPROVED** [review]
Nothing seems to depend on `curl` any more (`opkg` used to use `curl` before we first switched to (busybox-)`wget` and later to `uclient-fetch`)

**Comment by dedeckeh** [comment]
Package nghttp2 (https://github.com/openwrt/openwrt/tree/master/package/libs/nghttp2) can be moved as well to packages git as curl is the only package depending on it

**Review by dedeckeh — APPROVED** [review]

**Comment by aparcar** [comment]
Faster than I though `curl` was moved over.... https://github.com/openwrt/packages/pull/13214

**Comment by aparcar** [comment]
Rebased...

**Comment by dedeckeh** [comment]
Patch pushed to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=a5d030a54f671e52e4dd20460b350482a568ddb3); thx

**Comment by curtdept** [comment]
For anyone who finds this, this change sucks for people with existing build dirs. make dirclean wont cleanout package/feeds or feeds directories in addtion the package update doesnt pleace the files correctly and so curl and libcurl are no longer found.

To complicate it, .config was also permanently modified to remove all related packages.

**Comment by aparcar** [comment]
@curtdept I removed the ./tmp folder, updated the feeds, install curl (this time the one from packages.git), make nconfig, select curl, compile

**Comment by curtdept** [comment]
I had an existing dir, did a feeds, menuconfig, both complained of missing libcurl and curl. Then I thought old temp files somewhere, so I did a make dirclean, feeds, same thing.

until I wiped out feeds, started over and restored my .config it was stuck, seems fine now.

**Pull request closed without merging**
