### PR TITLE
kernel: fix w25q256fv unbootable and u-boot erase

### PR DESCRIPTION
**Pull request by dimatto**
"481-mtd-spi-nor-rework-broken-flash-reset-support.patch" patched kernel
5.10 will not boot on winbond w25q256fv chip with image size >= 16M,
and it will erase u-boot when sysupgrade a image with size >=16M.
The author of this patch is unreachable through email and github,
so delete this patch for now to let w25q256fv bootable and protect
u-boot from totally bricked.
Without this patch, I test it with power unplug and reboot command,
it seems no problem.

Signed-off-by: Frank Di Matteo <dimatto@foxmail.com>

### CODE REVIEW

**Comment by ptpt52** [comment]
ping @981213

**Comment by mans0n** [comment]
Hi, next time please do not open another new PR to amend your commit. Please do force-push instead.
https://openwrt.org/docs/guide-developer/working-with-github-pr#squashing_commits

And you should use your full name in the Signed-off-by tag.
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes#add_a_signed-off-by_with_your_real_name

**Comment by dimatto** [comment]
I used full name but can't pass check, github prompt me to use dimatto, I use it and passed check.

**Comment by mans0n** [comment]
> I used full name but can't pass check, github prompt me to use dimatto, I use it and passed check.

Hmm, probably that's because the SoB line and the author line do not match. Try this:
```
git config user.name <full name>
git commit --amend --reset-author --signoff
```

**Comment by dimatto** [comment]
I'm sorry I didn't submit this PR through command line , instead I submit it through github web interface because I don't want to mess up openwrt repository with my limit git knowledge. How can I meet your requirements with github web interface ?

**Comment by mans0n** [comment]
I don't know, maybe you can add your name in the GitHub account setting page?
I strongly recommend you to use git CLI, as the web interface is likely to slow down the review process, which is unfortunate for both of us.

**Comment by mans0n** [comment]
And while you're fixing it, please wrap the commit message to 75 characters per line.

**Comment by 981213** [comment]
Dropped the patch in my staging tree with proper explanation: https://git.openwrt.org/?p=openwrt/staging/981213.git;a=summary

Thanks for reporting and sorry for a late response.

**Pull request closed without merging**
