### PR TITLE
uci: fix typos in Makefile

### PR DESCRIPTION
**Pull request by oskarirauta**
I think some : chars are missing from Makefile.
Doesn't change much, but does standardise Makefile.

### CODE REVIEW

**Comment by Ansuel** [comment]
@oskarirauta WOW i checked history and this was wrong from the start... i'm impressed... 

Aside from this funny check, can you reword the commit description in something more imperative? Something like "Fix wrong declaration for PKG_SROUCE_URL and PKG_VERSION variables and add missing colon"

If you can I can take care of reworking the commit description!

**Comment by oskarirauta** [comment]
@ansuel Sure thing - bumped into it by accident, I made few dev packages containing headers and stuff, where libuci-dev was one of them, I have a included makefile that parses some details from pointed Makefiles, to use existing built source to provide dev package and uci failed because of this- so that's how I ended up at this point..

I'll fix the commit description right away..

**Comment by oskarirauta** [comment]
@Ansuel

Better now?

**Comment by Ansuel** [comment]
@oskarirauta can you by chance run this also on every feeds packages? Would love to check if we have other kind of simple errors.

**Comment by KanjiMonster** [comment]
Just want to point out that `=` and `:=` are two different ways of assigning variables, with semantic differences. In this case it doesn't matter since they are set to static values, but when using variables in the right hand side can matter.

**Comment by KanjiMonster** [comment]
See https://www.gnu.org/software/make/manual/html_node/Setting.html for the various ways of setting variables.

**Comment by Ansuel** [comment]
@KanjiMonster yep you are totally correct and just for this reason, the makefile was wrong in assigning the variable that way instead of assigning it one time as a const one.

**Comment by oskarirauta** [comment]
I think everyone should mention/PR if they find something like this. There is no tool for checking this, atleast I don’t have One. My routine just failed why I found this. Me to searching for more would be manually reading Makefiles and surely I will act if these come up, but won’t systematicly read all makefiles, sorry.”Tool”/include file that I used is at my git HTTPS://github.com/oskarirauta/openwrt-devel but it is not anything special.. that is why this One failed on it.Lähetetty iPhonestaChristian Marangi ***@***.***> kirjoitti 2.10.2023 kello 0.10:﻿
@KanjiMonster yep you are totally correct and just for this reason, the makefile was wrong in assigning the variable that way instead of assigning it one time as a const one.

**Pull request merged**
