### PR TITLE
kmod-nft-reject: Fix for "nft_reject_ipv4.ko missing" warning

### PR DESCRIPTION
**Pull request by pprindeville**
Seeing the following:

    ERROR: module '/home/philipp/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.33/net/ipv4/netfilter/nft_reject_ipv4.ko' is missing.
    modules/netfilter.mk:1068: recipe for target '/home/philipp/lede/bin/targets/x86/64/packages/kmod-nft-core_5.4.33-1_x86_64.ipk' failed
    make[3]: *** [/home/philipp/lede/bin/targets/x86/64/packages/kmod-nft-core_5.4.33-1_x86_64.ipk] Error 1

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by pprindeville** [comment]
@jow- @nbd168 @NeoRaider @ynezz I have to admit I completely don't understand this patch.  It allows the compilation to continue, but then it doesn't end up generating `nft_reject_ipv4.ko` or `nft_reject_ipv6.ko` in the `linux-5.4.33` build directory, nor in the `kmod-nft-core/` directory.

**Comment by pprindeville** [comment]
Who can assign reviewers?

**Comment by bobafetthotmail** [comment]
> Who can assign reviewers?

I don't think OpenWrt works like that.

You post the PR and hope a reviewer appears eventually.

**Comment by hauke** [comment]
Could you please provide the configuration you used when seeing this problem.

**Comment by pprindeville** [comment]
This is in [FS #3038](https://bugs.openwrt.org/index.php?do=details&task_id=3038).

**Comment by adrianschmutzler** [comment]
Based on the referenced bug report, this is reported for a very specific configuration on x86/64.

**Comment by pprindeville** [comment]
> Based on the referenced bug report, this is reported for a very specific configuration on x86/64 only so far.

The config I had was one known to reproduce it.  That doesn't mean that it can't be reproduced with a much simpler one.  I just haven't spent the time trying to pare it down.

Absence of evidence isn't evidence of absence...

**Comment by adrianschmutzler** [comment]
> I just haven't spent the time trying to pare it down.

Exactly.

**Comment by NeoRaider** [comment]
I assume you hit this issue in a kernel configuration with `CONFIG_NFT_REJECT=m` and `CONFIG_NFT_REJECT_IPV4` unset, which can happen with `NF_TABLES_IPV4` disabled.

The fix looks correct to me.

**Comment by pprindeville** [comment]
> Exactly.

Someone more familiar with the `kmod` logic might have an easier time figuring out what the minimal logic required to reproduce the bug is.

**Comment by pprindeville** [comment]
Can I get a review, please?

**Comment by dangowrt** [comment]
Cherry-picked. Thanks!

**Comment by dangowrt** [comment]
Broke the build. Please fix it.
```
Package kmod-nft-core is missing dependencies for the following libraries:
nft_reject.ko
modules/netfilter.mk:1071: recipe for target '/builder/shared-workdir/build/bin/targets/octeontx/generic/packages/kmod-nft-core_5.4.72-1_aarch64_generic.ipk' failed
```

**Comment by pprindeville** [comment]
Can you point me at the build logs and the `.config` and `kernel-config` that was used to build this?

**Comment by adschm** [comment]
@pprindeville If it was the buildbots (as it looks to me), the config used is found together with the images at the download page:
https://downloads.openwrt.org/snapshots/targets/octeontx/generic/config.buildinfo

**Comment by adschm** [comment]
Ping.

**Comment by pprindeville** [comment]
> Ping.

How do I get the expanded `.config` after applying defaults?

**Comment by pprindeville** [comment]
Also, if it's broken, then why are there current builds?

**Comment by pprindeville** [comment]
> Ping.

Wasn't this addressed as [499924a](https://github.com/openwrt/openwrt/commit/499924adf077428e88010230ecf5c363fe018623)?

**Comment by pprindeville** [comment]
@dangowrt This is 100% reproducible on my build VM.  Can you log in and have a look with me when you have some free time?

**Comment by adschm** [comment]
Since this appears to be leading nowhere, and no attempts have been made to fix the build breakage in almost a year, I'm closing this now.

**Pull request closed without merging**
