### PR TITLE
libnftnl/nftables: update to latest version

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Update libnftnl and nftables to latest version.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Runtested Linksys E8450.

**Comment by regae** [comment]
can you do an insert rule ?
mine is error

BUG: unhandled op 4
Assertion failed: 0 (evaluate.c: interval_set_eval: 1537)
Aborted

**Comment by PolynomialDivision** [comment]
@regae Can you give more exaple what you are executing?

**Comment by regae** [comment]
nft insert rule inet fw4 srcnat oifname "pppoe-wan" counter snat ip6 prefix to ip6 saddr map { xxxx/64 : xxxx/64 }

**Comment by PolynomialDivision** [comment]
Did this occur also in 1.0.4?

**Comment by nasbdh9** [comment]
```
make[3]: Entering directory '/home/nasbdh9/x86/package/libs/libmnl'
mkdir -p /home/nasbdh9/x86/staging_dir/target-x86_64_musl/root-x86/stamp
echo '0' | cmp -s - /home/nasbdh9/x86/staging_dir/target-x86_64_musl/pkginfo/libmnl.version || { echo '0' > /home/nasbdh9/x86/staging_dir/target-x86_64_musl/pkginfo/libmnl.version;  } 
SHELL= flock /home/nasbdh9/x86/tmp/.root-copy.flock -c 'cp -fpR /home/nasbdh9/x86/build_dir/target-x86_64_musl/libmnl-1.0.5/.pkgdir/libmnl/. /home/nasbdh9/x86/staging_dir/target-x86_64_musl/root-x86/'
touch /home/nasbdh9/x86/staging_dir/target-x86_64_musl/root-x86/stamp/.libmnl_installed
echo "libmnl" >> /home/nasbdh9/x86/staging_dir/target-x86_64_musl/pkginfo/libmnl.default.install
make[3]: Leaving directory '/home/nasbdh9/x86/package/libs/libmnl'
time: package/libs/libmnl/compile#0.14#0.09#0.22
make[3]: Entering directory '/home/nasbdh9/x86/package/libs/libnftnl'
rm -f /home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3/.built
touch /home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3/.built_check
CFLAGS="-march=cascadelake -O2 -pipe -ftree-vectorize -ftree-slp-vectorize -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3=libnftnl-1.2.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -flto  -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include " CXXFLAGS="-march=cascadelake -O2 -pipe -ftree-vectorize -ftree-slp-vectorize -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3=libnftnl-1.2.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -flto  -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include " LDFLAGS="-L/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -flto " make  -C /home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3/. AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -march=cascadelake -O2 -pipe -ftree-vectorize -ftree-slp-vectorize -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3=libnftnl-1.2.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -flto" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CROSS="x86_64-openwrt-linux-musl-" ARCH="x86_64" ;
make[4]: Entering directory '/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3'
make  all-recursive
make[5]: Entering directory '/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3'
Making all in src
make[6]: Entering directory '/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3/src'
depbase=`echo expr/fullcone.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CC   --mode=compile x86_64-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I. -I..  -D_FILE_OFFSET_BITS=64 -D_REENTRANT -I../include -I/home/nasbdh9/x86/staging_dir/target-x86_64_musl/usr/include   -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include  -Wall -Waggregate-return -Wmissing-declarations 	-Wmissing-prototypes -Wshadow -Wstrict-prototypes 	-Wformat=2 -Wwrite-strings -pipe -fvisibility=hidden -march=cascadelake -O2 -pipe -ftree-vectorize -ftree-slp-vectorize -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3=libnftnl-1.2.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -flto  -MT expr/fullcone.lo -MD -MP -MF $depbase.Tpo -c -o expr/fullcone.lo expr/fullcone.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  x86_64-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I. -I.. -D_FILE_OFFSET_BITS=64 -D_REENTRANT -I../include -I/home/nasbdh9/x86/staging_dir/target-x86_64_musl/usr/include -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/nasbdh9/x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -Wall -Waggregate-return -Wmissing-declarations -Wmissing-prototypes -Wshadow -Wstrict-prototypes -Wformat=2 -Wwrite-strings -pipe -fvisibility=hidden -march=cascadelake -O2 -pipe -ftree-vectorize -ftree-slp-vectorize -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3=libnftnl-1.2.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -flto -MT expr/fullcone.lo -MD -MP -MF expr/.deps/fullcone.Tpo -c expr/fullcone.c  -fPIC -DPIC -o expr/.libs/fullcone.o
expr/fullcone.c:166:10: error: 'struct expr_ops' has no member named 'snprintf'
  166 |         .snprintf       = nftnl_expr_fullcone_snprintf,
      |          ^~~~~~~~
make[6]: *** [Makefile:711: expr/fullcone.lo] Error 1
make[6]: Leaving directory '/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3/src'
make[5]: *** [Makefile:495: all-recursive] Error 1
make[5]: Leaving directory '/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3'
make[4]: *** [Makefile:401: all] Error 2
make[4]: Leaving directory '/home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3'
make[3]: *** [Makefile:77: /home/nasbdh9/x86/build_dir/target-x86_64_musl/libnftnl-1.2.3/.built] Error 2
make[3]: Leaving directory '/home/nasbdh9/x86/package/libs/libnftnl'
time: package/libs/libnftnl/compile#0.23#0.11#0.31
    ERROR: package/libs/libnftnl failed to build.
make[2]: *** [package/Makefile:116: package/libs/libnftnl/compile] Error 1
make[2]: Leaving directory '/home/nasbdh9/x86'
make[1]: *** [package/Makefile:110: /home/nasbdh9/x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/nasbdh9/x86'
make: *** [/home/nasbdh9/x86/include/toplevel.mk:230：world] 错误 2
```

**Comment by hauke** [comment]
@nasbdh9 expr/fullcone.c is not part of upstream libnftnl library or any upstream OpenWrt patch.
You probably have to adapt your downstream patches to this change: https://git.netfilter.org/libnftnl/commit/?id=84d12cfacf8ddd857a09435f3d982ab6250d250c

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in ce28f303e802f7a7ba85ac7c5c423f7c3f667d69 and 36bec544d73dbed46f06875fdfa570e89a40e553.

**Pull request closed without merging**
