### PR TITLE
librpc: remove package

### PR DESCRIPTION
**Pull request by Andy2244**
Remove the replaced librpc from base and related options.

* replaced with packages/libtirpc
* remove busybox options rarely used/deprecated 
BUSYBOX_CONFIG_FEATURE_MOUNT_NFS
BUSYBOX_CONFIG_FEATURE_INETD_RPC

The mount option was for kernel < 2.6 and the second option for some "very rarely" used feature?
So instead of keeping those, it should be safe to remove those?

@jow- @tripolar opinions?

PS: #1274 should than be moved to packages as suggested

### CODE REVIEW

**Comment by tripolar** [comment]
i am fine with this.

And conntrack-tools has to be moved to the packages repo or libtirpc has to be moved to the openwrt repo

**Comment by jow-** [comment]
Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/jow.git

**Comment by kofec** [comment]
Hi, Is it related to this change - package "portmap" on architecture Kirkwood:
```
make[4]: Entering directory '/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/portmap_6.0'
arm-openwrt-linux-muslgnueabi-gcc -Os -pipe -mcpu=xscale -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft -iremap/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/portmap_6.0:portmap_6.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/mnt/openwrt/OpenwrtNSA310/staging_dir/target-arm_xscale_musl_eabi/usr/include -I/mnt/openwrt/OpenwrtNSA310/staging_dir/target-arm_xscale_musl_eabi/include -I/mnt/openwrt/OpenwrtNSA310/staging_dir/toolchain-arm_xscale_gcc-7.4.0_musl_eabi/usr/include -I/mnt/openwrt/OpenwrtNSA310/staging_dir/toolchain-arm_xscale_gcc-7.4.0_musl_eabi/include/fortify -I/mnt/openwrt/OpenwrtNSA310/staging_dir/toolchain-arm_xscale_gcc-7.4.0_musl_eabi/include -DHOSTS_ACCESS -DFACILITY=LOG_DAEMON -DIGNORE_SIGCHLD -DHOSTS_ACCESS -DCHECK_PORT -DRPCUSER=\"rpc\" -DIGNORE_SIGCHLD        -DFACILITY=LOG_DAEMON   -c -o portmap.o portmap.c
portmap.c:79:10: fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>
          ^~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'portmap.o' failed
make[4]: *** [portmap.o] Error 1
make[4]: Leaving directory '/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/portmap_6.0'
Makefile:53: recipe for target '/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/portmap_6.0/.built' failed
make[3]: *** [/mnt/openwrt/OpenwrtNSA310/build_dir/target-arm_xscale_musl_eabi/portmap_6.0/.built] Error 2
make[3]: Leaving directory '/mnt/openwrt/OpenwrtNSA310/feeds/packages/net/portmap'
time: package/feeds/packages/portmap/compile#0.17#0.09#0.28
package/Makefile:107: recipe for target 'package/feeds/packages/portmap/compile' failed

```

**Comment by Andy2244** [comment]
Yes, we did replace portmap with rpcbind a while ago and it uses libtirpc. So i'm a bit confused where is this portmap_6.0 package coming from? I cant find it in snapshots?

**Comment by nobk** [comment]
utils/mc compile will failing with option 'Enable virtual filesystem support' for ssh/scp/ftp/sftp/cpio/tar.
error message librpc.a not find.
.config file
CONFIG_MC_BACKGROUND=y
CONFIG_MC_CHARSET=y
CONFIG_MC_DIFFVIEWER=y
CONFIG_MC_EDITOR=y
CONFIG_MC_LARGEFILE=y
CONFIG_MC_SUBSHELL=y
CONFIG_MC_VFS=y

**Comment by kofec** [comment]
@Andy2244 
> Yes, we did replace portmap with rpcbind a while ago and it uses libtirpc. So i'm a bit confused where is this portmap_6.0 package coming from? I cant find it in snapshots?

Sorry that was my fault. I switch between master and latest branch and for some reason portmap left on master. I remove the repository and download from scratch. That resolved my issue

**Pull request closed without merging**
