### PR TITLE
uci,ubus,libubox,lua,libnl-tiny,libjson-c: mark nonshared

### PR DESCRIPTION
**Pull request by hnyman**
cc @aparcar 

Mark uci, ubus, libubox, lua, libnl-tiny and libjson-c as nonshared packages. This helps to keep coherent dependencies if these ABI versioned packages are later updated.

Before this commit it is possible to get missing dependencies in target-specific nonshared packages (like iwinfo) that depend on these shared ABI versioned packages. If these are later updated and rebuilt, only the new ABI version will be available for download, while the target-specific packages in releases continue to depend on the old ABI version.

After this commit the packages are built along the other nonshared packages by the phase1 images buildbot and will be available at the target/ download directories instead of packages/base dir. That will help to keep a coherent set available.

Reference to:
https://lists.openwrt.org/pipermail/openwrt-devel/2021-June/035436.html
https://lists.openwrt.org/pipermail/openwrt-devel/2021-June/035442.html

(This should probably be also backported to at least 21.02, but preferably just a before the rc3 or release, as applying this will soon remove the old shared packages, so the packages need to be in the available nonshared repos.)

**Background:**

Based on forum discussion, we have currently a broken 21.02.0-rc2 imagebuilder, as libiwinfo can't find the correct libubus version.
https://forum.openwrt.org/t/21-02-0-rc2-build-error-on-libubus20210215/98373

My analysis leading to the PR:

* ubus is a normal (shared) package in the packages/ downloads dir
* the nonshared libiwinfo depends on libubus with ABI specification.
* ubus has been updated since rc2, so new ubus and libubus versions are now 
offered for download
* The nonshared libiwinfo is located in the target/ download directory of 
rc2, and it still depends on the older libubus with the old ABI version. And 
that old libubus version has already been replaced by the newer libubus 
version in the normal packages download dir.

The libubus dependency difference is visible in the libiwinfo package metadata:

libiwinfo from 21.02-SNAPSHOT:
```
 Package: libiwinfo20210106
 Version: 2021-01-31-4a32b33e-1
 Depends: libc, libnl-tiny1, libuci20130104, libubus20210603
```

From rc2:
```
 Package: libiwinfo20210106
 Version: 2021-01-31-4a32b33e-1
 Depends: libc, libnl-tiny1, libuci20130104, libubus20210215
```

I went through the ~60 instances of "nonshared" packages in the main OpenWrt repo, and found that toggling six packages to nonshared would solve the common problems:

libubox, ubus, uci, lua, libjson-c, libnl-tiny

Additionally also elfutils (libelf, libdw) could be toggled to nonshared, but as that is only needed for the non-default "perf" package, I do not find it that important.

### CODE REVIEW

**Comment by adschm** [comment]
commit title prefix should be "treewide:" or maybe "packages:" ...

**Comment by hnyman** [comment]
> commit title prefix should be "treewide:" 

Changed.

**Comment by aparcar** [comment]
If any of those packages doesn't use AUTORELEASE please bum the PKG_RELEASE

**Comment by hnyman** [comment]
> please bum the PKG_RELEASE

done.

**Comment by predators46** [comment]
Hi all. maybe this is not the place to report bugs but i would like to report openwrt 21-20-rc2 having clock sync issues on ubuntu and on debian. i have set the time on my amazon vps and made the firmware using imagebuilder openwrt, when i flash it on my router and when it's done i see the clock on my router is different the time i use on my amazon vps and i've tried on openwrt 19.07.4 nothing time problem

**Review by hauke — APPROVED** [review]
This looks good to me, I would merge this into master in the next days and into 21.02 before rc3.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master and the 21.02 branch.

**Comment by ynezz** [comment]
@hnyman FYI I plan to [backport](https://lists.infradead.org/pipermail/openwrt-devel/2021-July/035718.html) this into 19.07 along with other ubus fixes.

**Comment by map-b** [comment]
2026 retry
- https://github.com/openwrt/openwrt/pull/22396

**Comment by map-b** [comment]
Void? Vacuum?? :( I prefer a good rant at least

**Comment by hnyman** [comment]
You probably noticed that this PR's solution attempt from me got first implemented, but then reverted with 8307da3. So the packages are normally "shared" again.

**Comment by map-b** [comment]
It is not a simple "retry", thanks to your attempt we have a clear view of the problem, but I unearthed the torch and tried another approach, by the way, for me, although not since the start, your attempt helped, it is like co-develop by you, should I tag you, suggested-by at least?

**Comment by hnyman** [comment]
Ne need to tag me.
I think that core developers know well the problematics related to the 2-stage buildbot approach and shared(rolling) packages vs. non-shared (that are locked to releases) packages.

It is non-optimal that we have a "non-shared/locked" package to depend on a rollingly built package. My attempt tried to remove that by locking the few key rolling packages, but that was not seen optimal in the end and was reverted.

Now apk has replaced opkg, and it may be more friendly towards having several version of the same package available, so it could be more easily possible to store also the crucial few shared packages along the non-shared packages in the release target/packages dir on the download server. Your draft PR #22396 looks like going to the right direction.

**Pull request closed without merging**
