### PR TITLE
kmod-sched-cake: update to 20180706

### PR DESCRIPTION
**Pull request by gamanakis**
Update kmod-sched-cake to 20180706.
Tested on TP-Link WR-941NDv3.

Signed-off-by: George Amanakis <gamanakis@gmail.com>

### CODE REVIEW

**Comment by gamanakis** [comment]
Tested on TP-Link WR-941NDv3.

**Comment by guidosarducci** [comment]
@gamanakis 
Hi George, the latest CAKE master now includes a backport of upstream classifier functionality and fixes to make this work on kernel 4.4, which I've compile and run tested on LEDE 17.01.4/ar71xx (also using your [iproute2 PR](https://github.com/openwrt/openwrt/pull/1179)). Could you try that version? It's a shame we missed the 17.01.5 release however.

Thanks,
Tony

**Comment by ldir-EDB0** [comment]
Hi Tony,

Can you clarify for me please, does the classifier stuff actually work on kernel 4.4 for cake or is it just not implemented courtesy the ifdef fun?

Sorry we missed .5, the horse fairly bolted out of the stable and was over the hill before I noticed the gate opened - will make sure gets in for .6

Kevin

**Comment by guidosarducci** [comment]
It _actually works_ on kernel 4.4. I reclassified some video from BE into BK and could follow the change live in the stats. Cool to see!

**Comment by ldir-EDB0** [comment]
Oh fantastic!  Am in the process of cherry-picking this from the master & 18.06 branches so we retain the spirit of the commit logs if not the absolute truth :-)

**Comment by ldir-EDB0** [comment]
Merged!  Cherry picked from master.  Thanks for the prodding to get this done.

**Pull request closed without merging**
