### PR TITLE
ci: use checkpatch.pl on every PR

### PR DESCRIPTION
**Pull request by aparcar**
Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by diizzyy** [comment]
At least try to add a commit message?

**Comment by KanjiMonster** [comment]
Please no empty commit logs. Provide a justification why you think this change is good/needed.

`checkpatch.pl` doesn't handle patches of patches, so will produce warnings/errors when trying to add/modify patches to kernel or packages. It enforces the kernel code style (and has a lot of checks for simple mistakes in kernel API usage), which might not be appropriate for non-kernel patches/code. See the clang-format discussion. It's also now quite outdated, last modifications from 2017.

Running it on the top 100 commits it warned on 15 of them, and produced over 1000 errors/warnings on them - AFAICT all of them false positives. This will only lead to actual errors/warnings being lost in noise, and nobody will notice them.

So I don't think this is a good idea without first reducing the amount of false positives it produces severely.

**Comment by aparcar** [comment]
@KanjiMonster very good point, I did not perform such test and misst the errors. Would it be an option for you to collect common errors here so I can create a more reliable test script? SoB, commit messages and no whitespace errors could be a start.

**Comment by aparcar** [comment]
Talking with @ynezz we came up with the idea to compile changed device-tree files via dtc.

**Comment by ynezz** [comment]
@aparcar I would simply start experimenting on the GitLab, iron out the rough edges there, probably start by mirroring PRs from GitHub to GitLab (interested reviewers could simply always look at the GitLab for PR check reports) and once the final decision/voting is made, we could either keep it on GitLab or migrate it back to GitHub. What do you think?

**Comment by ynezz** [comment]
> interested reviewers could simply always look at the GitLab for PR check reports

This could as well work with some kind of PR check bot/comment on GitHub from GitLab instance over some API call...

**Comment by diizzyy** [comment]
GitLab?

**Comment by ynezz** [comment]
> GitLab?

Yes https://github.com/openwrt/openwrt/pull/2218#issuecomment-511304385

**Comment by ynezz** [comment]
I think, that we don't need this open anymore, we could continue development on the testing GitLab instance. Anyway, if you think, that this should be left open, feel free to request re-open.

**Pull request closed without merging**
