### PR TITLE
mediatek: correct address of MT753x switch IC

### PR DESCRIPTION
**Pull request by dangowrt**
For all boards currently working with the mt7530 DSA driver we can be sure that the address of the switch on the MDIO bus is 31 -- simply because that address is hard-coded in the driver and the address from the Device Tree is being ignore.

An upcoming patch will add support for MT753x ICs which are programmed to addresses different from 0x1f using bootstrap pins. As a result the address from the Device Tree will then be taken into account, which will break currently working boards which got the address set to anything else than 31.

While at it also unify the syntax in Device Tree to always us a decimal value for the 'reg' property.

 * `mt7622-buffalo-wsr-3200ax4s.dts`
    Cosmetic change: `reg = <0x1f>` -> `reg = <31>`

 * `mt7622-dlink-eagle-pro-ai-ax3200-a1.dtsi`
   Wrong address: `0` -> `31`

 * `mt7622-elecom-wrc-x3200gst3.dts`
   Wrong address: `0` -> `31`

 * `mt7622-linksys-e8450.dtsi`
   Wrong address: `0` -> `31`

 * `mt7622-ruijie-rg-ew3200.dtsi`
   Wrong address: `0` -> `31`

 * `mt7622-xiaomi-redmi-router-ax6s.dts`
   Wrong address: `0` -> `31`

 * `mt7629-iptime-a6004mx.dts`
   Wrong address: `2` -> `31`

 * `mt7981b-zbtlink-zbt-z8102ax.dts`
   Cosmetic change: `reg = <0x1f>` -> `reg = <31>`

Other targets are not affected because MT7621 already got the correct values set in `mt7621.dtsi`, MT7620 doesn't use the DSA driver and there are no supported boards using the MT753x ICs on any other targets.

### CODE REVIEW

**Comment by dangowrt** [comment]
@arinc9 Please have a look as well

**Comment by dangowrt** [comment]
On Tue, Apr 23, 2024 at 05:57:29AM -0700, Mieczyslaw Nalewaj wrote:
> Or maybe move this setting for every chips to the parent file (similar to mt7621)?

In case of MT7622, MT7623, MT7629, MT7981 and MT7986 the switch chip is
a dedicated IC, not built-into the SoC package like on MT7621.

**Comment by arinc9** [comment]
@dangowrt looks good. Could you use a hexadecimal value for the reg property? To conform to the [Devicetree Sources (DTS) Coding Style](https://docs.kernel.org/devicetree/bindings/dts-coding-style.html): Hex values in properties, e.g. “reg”, shall use lowercase hex.

**Comment by dangowrt** [comment]
> Anyway, my preference is to use hex to be aligned with the unit address on the node name.

I did  a quick survey over all DTS files in the OpenWrt tree:
```
$ find -name \*.dts\* | while read line; do grep 'reg.*=.*<[0-9]*>' $line ; done | wc -l
4341
$ find -name \*.dts\* | while read line; do grep 'reg.*=.*<0x[0-9a-fA-F]*>' $line ; done | wc -l
591
```

In the Linux kernel the situation is not that extreme, but still similar:
```
$ find -name \*.dts\* | while read line; do grep 'reg.*=.*<[0-9]*>' $line ; done | wc -l
37284
$ find -name \*.dts\* | while read line; do grep 'reg.*=.*<0x[0-9a-fA-F]*>' $line ; done | wc -l
10339
```

So using decimals there for things which are *not* memory ranges (and hence usually aligned to some bit-length which makes them more readable as hex values) is by far more common, at least on our tree.

**Pull request merged**
