### PR TITLE
kernel: bump 5.10 to 5.10.61

### PR DESCRIPTION
**Pull request by graysky2**
Manually rebased:
  bcm27xx/patches-5.10/950-1031-net-lan78xx-Ack-pending-PHY-ints-when-resetting.patch

Removed upstreamed:
  mvebu/patches-5.10/101-cpufreq-armada-37xx-forbid-cpufreq-for-1.2-GHz-variant.patch

All other patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B
Run-tested: bcm2711/RPi4B

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by graysky2** [comment]
In the future, if I bump both 5.4 and 5.10, what is the best practice for PRs?  Separate or together (multiple commits)?

Obviously, when you merge this or https://github.com/openwrt/openwrt/pull/4481 I believe a manual rebase will be needed to correct `include/kernel-version.mk`, no?

**Comment by adschm** [comment]
Title is wrong (5.4 vs. 5.10)

**Comment by Beginner-Go** [comment]
Hi .
Are you maintaining kernel 5.10 now?

**Comment by rsalvaterra** [comment]
> Manually rebased:
> bcm27xx/patches-5.10/950-1031-net-lan78xx-Ack-pending-PHY-ints-when-resetting.patch
> 
> Removed upstreamed:
> mvebu/patches-5.10/101-cpufreq-armada-37xx-forbid-cpufreq-for-1.2-GHz-variant.patch
> 
> All other patches automatically rebased.

This looks good to me. I arrived at the same result as you, since I hadn't noticed this pull request. 😉

**Comment by pkgadd** [comment]
Runtime-tested:
- ipq806x

Build-tested:
- ath79
  - ath79-tiny
- lantiq
- realtek
- ipq806x
- ipq807x

`Tested-by: Stefan Lippers-Hollmann <s.l-h@gmx.de>`



> Obviously, when you merge this or #4481 I believe a manual rebase will be needed to correct `include/kernel-version.mk` on the other, no?

Personally I'd suggest to move the definitions for v5.4 and v5.10 slightly further away from each other, so that at least GNU `patch` and `quilt` won't fall over the differences (`git am` would still complain, but that would still make rebasing easier).

**Comment by graysky2** [comment]
@rsalvaterra - I had a little free time today to do this, but I know you have been very actively updating 5.10.y.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master.

With `git am -3` it is easy to fix the merge conflict.

I do not care if you put this into one pull request or into multiple, but please use separate commits for kernel 5.4 and 5.10.

**Pull request closed without merging**
