### PR TITLE
ath79: generic: disable SPI-NOR write protect unconditionally to fix UBNT XW and WA devices

### LINKED ISSUE #13750: Ubnt Nanostation AC loco fails to store config after upgrade to 23.05
### Describe the bug

I have many Ubiquiti Nanostation 5 AC loco devices, that have been running 22.03 fine for ages. I thought I'd try upgrading to 23.05 but it appears after upgrade configuration cannot be stored. Anything configured is fine at runtime, and operates well while the device is on, but if anything interrupts the power or if the device is manually rebooted, all configuration is lost.

I have spare devices, and have reverted one back to 22.03.5 which is again working fine (although I had to use Ubiquiti's TFTP factory image process as downgrading from OpenWRT didn't work.... because a reset just applies the current 23.05 image again)

I think it may be something to do with the mounts, but I am by no means an expert here.

I have performed an upgrade on two different Nanostation AC locos, one brand new, and the result is the same.

Thanks,

### OpenWrt version

r23389-5deed175a5

### OpenWrt target/subtarget

ath79/generic

### Device

Ubiquiti Nanostation AC loco (WA)

### Image kind

Official downloaded image

### Steps to reproduce

1. Flash 23.05 (tried both rc3 and release 23.05) to device
2. Configure anything i.e. system name, password, wireless, dhcp, etc.
3. Reboot
4. Configuration is lost.

### Actual behaviour

Device does not keep any information after reboot or power loss

### Expected behaviour

Device should persist configuration

### Additional info

Output of df -h on **23.05**
```
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 4.0M      4.0M         0 100% /rom
tmpfs                    27.9M     76.0K     27.8M   0% /tmp
/dev/mtdblock5            9.3M      9.3M         0 100% /overlay
tmpfs                    27.9M     84.0K     27.8M   0% /tmp/root
overlayfs:/tmp/root      27.9M     84.0K     27.8M   0% /
tmpfs                   512.0K         0    512.0K   0% /dev
```

Output of df -h on **22.03**
```
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 4.0M      4.0M         0 100% /rom
tmpfs                    28.0M    232.0K     27.8M   1% /tmp
/dev/mtdblock5            9.3M    436.0K      8.8M   5% /overlay
overlayfs:/overlay        9.3M    436.0K      8.8M   5% /
tmpfs                   512.0K         0    512.0K   0% /dev
```

Output of cat /proc/mtd on **23.05""
```
dev:    size   erasesize  name
mtd0: 00040000 00010000 "u-boot"
mtd1: 00010000 00010000 "u-boot-env"
mtd2: 00f60000 00010000 "firmware"
mtd3: 00240000 00010000 "kernel"
mtd4: 00d20000 00010000 "rootfs"
mtd5: 00950000 00010000 "rootfs_data"
mtd6: 00040000 00010000 "cfg"
mtd7: 00010000 00010000 "art"
```

Output of cat /proc/mtd on **22.03""
```
dev:    size   erasesize  name
mtd0: 00040000 00010000 "u-boot"
mtd1: 00010000 00010000 "u-boot-env"
mtd2: 00f60000 00010000 "firmware"
mtd3: 00230000 00010000 "kernel"
mtd4: 00d30000 00010000 "rootfs"
mtd5: 00940000 00010000 "rootfs_data"
mtd6: 00040000 00010000 "cfg"
mtd7: 00010000 00010000 "art"
```
Output of cat /proc/mounts on **23.05**
```
/dev/root /rom squashfs ro,relatime,errors=continue 0 0
proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,noatime 0 0
/dev/mtdblock5 /overlay jffs2 rw,noatime 0 0
tmpfs /tmp/root tmpfs rw,noatime,mode=755 0 0
overlayfs:/tmp/root / overlay rw,noatime,lowerdir=/,upperdir=/tmp/root/upper,workdir=/tmp/root/work 0 0
tmpfs /dev tmpfs rw,nosuid,noexec,noatime,size=512k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,noatime,mode=600,ptmxmode=000 0 0
debugfs /sys/kernel/debug debugfs rw,noatime 0 0
bpffs /sys/fs/bpf bpf rw,nosuid,nodev,noexec,noatime,mode=700 0 0
```

Output of cat /proc/mounts on **22.03**
```
/dev/root /rom squashfs ro,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,noatime 0 0
/dev/mtdblock5 /overlay jffs2 rw,noatime 0 0
overlayfs:/overlay / overlay rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work 0 0
tmpfs /dev tmpfs rw,nosuid,noexec,noatime,size=512k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,noatime,mode=600,ptmxmode=000 0 0
debugfs /sys/kernel/debug debugfs rw,noatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,noatime,mode=700 0 0
```

If any more outputs will be useful, let me know I will keep a device on 23.05 for troubleshooting for now. I can also test any adjustments if you like.

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by Leo-PL**
Kernel 5.15 introduced a significant change to spi-nor subsystem [1], which would the SPI-NOR core to no longer unprotect the Flash chips if their protection bits are non-volatile, which is the case for MX25L6405D and MX25L12805D, used in Ubiquiti XW and WA lines of devices [2].

However, their bootloader forcibly enables this protection before continuing to boot, making the kernel not unprotect the flash upon boot, causing JFFS2 to be unable write to the filesystem. Because sysupgrade seems to unlock the flash explicitly, the upgrade will work, but the system will be unable to save configrationm showing the following symptom in the kernel log:

[   86.168016] jffs2_scan_eraseblock(): End of filesystem marker found at 0x0
[   86.192344] jffs2_build_filesystem(): unlocking the mtd device...
[   86.192443] done.
[   86.200669] jffs2_build_filesystem(): erasing all blocks after the end marker...
[   86.220646] jffs2: Newly-erased block contained word 0x19852003 at offset 0x001e0000
[   86.292388] jffs2: Newly-erased block contained word 0x19852003 at offset 0x001d0000
[   86.324867] jffs2: Newly-erased block contained word 0x19852003 at offset 0x001c0000
[   86.355316] jffs2: Newly-erased block contained word 0x19852003 at offset 0x001b0000
[   86.402855] jffs2: Newly-erased block contained word 0x19852003 at offset 0x001a0000

Disable the write protection unconditionally for ath79/generic subtarget, so the XW and WA devices can function again. However, this is only a stopgap solution - it probably should be investigated if there is a way to selectively unlock the area used by rootfs_data - but given the lock granularity, this seems unlikely.

With this patch in place, rootfs_data partition on my Nanostation Loco M5 XW is writable again.

Fixes: 579703f38c14 ("ath79: switch to 5.15 as default kernel")
Link: http://www.infradead.org/pipermail/linux-mtd/2020-October/082805.html
Link: https://forum.openwrt.org/t/powerbeam-m5-xw-configuration-loss-after-reboot/141925

Closes #13750

### CODE REVIEW

**Comment by Leo-PL** [comment]
cc @chunkeey @hauke 
This patch should be cherry-picked for 23.05, too.

**Comment by jmranger** [comment]
Related to #13750.

**Comment by jmranger** [comment]
Related to #12882.

**Comment by jmranger** [comment]
Tested on Ubiquity Nanostation AC loco (WA). Context/results:

- on 22.03.6, flash is working as expected.
- on 23.05.2, flash is read-only - configurations can't be saved, and sysypgrade is unable to flash anything.
- on today's snapshot (r24705-782eb05008), both writing to flash and sysupgrade'ing back to 22.03.6 are working.
- my attempts to backport this to the 23.05 branch and build it are incomplete.

@chunkeey  @hauke I'd like to echo the request to backport this to 23.05. Given the pain to recover (some of these devices are designed to be installed outdoor, and recovery sometimes require flashing back the Ubiquiti firmware over TFTP), I believe this should be listed in the known issues in the release notes as well.

If there's anything missing for either of these two things to happen, please advise.
Thanks, and happy 2024 everyone.

**Comment by Leo-PL** [comment]
IIRC this was a simple cherry-pick (I'm building my images from source) so +1 for the above.

**Comment by LipkeGu** [comment]
Closes #14941

**Pull request merged**
