### PR TITLE
base-files: upgrade: add case to export_bootdevice

### PR DESCRIPTION
**Pull request by kkudielka**
The factory uboot of the Turris Omnia boots with "root=b301", and we
instruct new users to sysupgrade from there (e.g. method 1, step 7).
Currently, this will fail with "Unable to determine upgrade device".
Add a new case to export_bootdevice, which parses the hex argument.

Fixes commit 2e5a0b81 ("mvebu: sysupgrade: sdcard: keep user added ...")

Signed-off-by: Klaus Kudielka <klaus.kudielka@gmail.com>
--
I may be paranoid, but I believe the Turris Omnia [installation procedure](https://openwrt.org/toh/turris_cz.nic/turris_cz.nic_omnia) still does not work with (post-2e5a0b81) master and 19.07. These are the factory bootargs:
```
root@turris-omnia:~# fw_printenv bootargs
bootargs=earlyprintk console=ttyS0,115200 rootfstype=btrfs rootdelay=2 root=b301 rootflags=subvol=@,commit=5 rw
```
I have tested (with OpenWRT):
- that bootargs make it into /proc/cmdline when an initramfs image is booted
- that the updated export_bootdevice will do the right thing with root=b301 in /proc/cmdline.

I have _not_ tested the whole installation procedure again.

### CODE REVIEW

**Comment by ynezz** [comment]
@tmn505 this is proposed fix for your 2e5a0b81ec29a897fde5ca30b0dc95fd28b9d4fb can you please check it?

**Comment by ynezz** [comment]
> master and 19.07.

@kkudielka Do I understand it properly, that this fix should be backported to openwrt-19.07?

**Comment by tmn505** [comment]
If that's what the `/proc/cmdline` says, then Yes, this patch is necessary, since currently we don't have case for handling such naming of boot devices. Maybe alternative would be patching Omnia's chosen node in dts with `bootargs = earlyprintk console=ttyS0,115200 root=/dev/mmcblk0p2 rootfstype=auto rootwait`? This would overwrite `bootargs` from U-Boot.

**Comment by kkudielka** [comment]
> @kkudielka Do I understand it properly, that this fix should be backported to openwrt-19.07?

Correct.

For completeness: An alternative workaround would be to modify the installation instructions, and have the user modify the u-boot environment himself & reboot the ramdisk image again, before executing sysupgrade. Not very user friendly, which is why I proposed this one.

**Comment by kkudielka** [comment]
> Maybe alternative would be patching Omnia's chosen node in dts with `bootargs = earlyprintk console=ttyS0,115200 root=/dev/mmcblk0p2 rootfstype=auto rootwait`? This would overwrite `bootargs` from U-Boot.

It would be a more local solution to a local problem. But it would completely eliminate any flexibility in the bootargs, once and forever? In that case, I would probably prefer the workaround during installation.

**Comment by ynezz** [comment]
y

**Comment by kkudielka** [comment]
@ynezz As far as I can tell this has _not_ been back-ported to 19.07 - which may be a possible explanation for this report: https://forum.openwrt.org/t/turris-omnia-2019/49399

**Comment by ynezz** [comment]
@kkudielka thanks for the reminder, I've just cherry-picked it into 19.07

**Pull request closed without merging**
