### PR TITLE
kernel: bump 5.15 to 5.15.62

### PR DESCRIPTION
**Pull request by ynezz**
Deleted following upstreamed patches:
 * bcm27xx: 950-0006-drm-vc4-hdmi-Fix-HPD-GPIO-detection.patch
 * bcm27xx: 950-0420-drm-vc4-Adopt-the-dma-configuration-from-the-HVS-or-.patch
 * bcm27xx: 950-0425-drm-vc4-A-present-but-empty-dmas-disables-audio.patch
 * bcm27xx: 950-0432-vc4-drm-Avoid-full-hdmi-audio-fifo-writes.patch
 * bcm27xx: 950-0433-vc4-drm-vc4_plane-Remove-subpixel-positioning-check.patch
 * bcm27xx: 950-0435-drm-vc4-Correct-pixel-order-for-DSI0.patch
 * bcm27xx: 950-0436-drm-vc4-Register-dsi0-as-the-correct-vc4-encoder-typ.patch
 * bcm27xx: 950-0437-drm-vc4-Fix-dsi0-interrupt-support.patch
 * bcm27xx: 950-0438-drm-vc4-Add-correct-stop-condition-to-vc4_dsi_encode.patch
 * bcm27xx: 950-0443-drm-vc4-Fix-timings-for-interlaced-modes.patch
 * bcm27xx: 950-0445-drm-vc4-Fix-margin-calculations-for-the-right-bottom.patch
 * bcm27xx: 950-0475-drm-vc4-Reset-HDMI-MISC_CONTROL-register.patch
 * bcm27xx: 950-0476-drm-vc4-Release-workaround-buffer-and-DMA-in-error-p.patch
 * bcm27xx: 950-0477-drm-vc4-Correct-DSI-divider-calculations.patch
 * bcm27xx: 950-0664-drm-vc4-dsi-Correct-max-divider-to-255-not-7.patch
 * bcm53xx: 072-next-ARM_dts_BCM53015-add-mr26.patch
 * mediatek: 920-linux-next-dts-mt7622-bpi-r64-fix-wps-button.patch

Manually rebased following patches:

 * bcm27xx: 950-0004-drm-vc4-hdmi-Remove-the-DDC-probing-for-status-detec.patch
 * bcm27xx: 950-0700-net-phy-lan87xx-Decrease-phy-polling-rate.patch
 * bcm27xx: 950-0711-drm-vc4-Rename-bridge-to-out_bridge.patch
 * bcm27xx: 950-0713-drm-vc4-Remove-splitting-the-bridge-chain-from-the-d.patch
 * bcm27xx: 950-0715-drm-vc4-Convert-vc4_dsi-to-using-a-bridge-instead-of.patch
 * bcm27xx: 950-0787-vc4-drm-vc4_plane-Keep-fractional-source-coords-insi.patch
 * bcm27xx: 950-0914-mmc-block-Don-t-do-single-sector-reads-during-recove.patch

Runtime tested on turris-omnia and glinet-b1300.

### CODE REVIEW

**Comment by ynezz** [comment]
@Noltari would be nice if you could take a look and/or test this on some bcm27xx target as there was a lot of manual fiddling needed during this kernel version bump.

**Comment by Noltari** [comment]
> @Noltari would be nice if you could take a look and/or test this on some bcm27xx target as there was a lot of manual fiddling needed during this kernel version bump.

@ynezz unfortunately I'm currently on a trip on the US and I won't be able to test this until my return in almost 3 weeks.
However, I could look over the patches and it looks OK. Those are the usual patches that give me some trouble when rebasing linux versions...

**Comment by graysky2** [comment]
```
Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200
```

My RPi4 is headless so cannot comment on all the video stuff.

**Comment by ynezz** [comment]
Merged in 26d202f0b58.

**Comment by PolynomialDivision** [comment]
Why don't we close?

**Pull request closed without merging**
