### PR TITLE
toolchain: Update to GCC 8.3.0

### PR DESCRIPTION
**Pull request by diizzyy**
Update GCC to 8.3.0
Refresh patches
Allow GCC to be used for ARC
Source: https://github.com/openwrt/openwrt/pull/1803#issuecomment-462334890

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested on: Octeon, EdgeRouter Lite, OpenWrt master + archs38, Synopsys DesignWare ARC HS38, OpenWrt master

Run tested on: Octeon, EdgeRouter Lite, OpenWrt master

**Comment by diizzyy** [comment]
This + https://github.com/openwrt/openwrt/pull/1803 would enable us to change from forked versions to upstream for ARC.

**Comment by wongsyrone** [comment]
Compile and run tested on x86_64

**Comment by hingbong** [comment]
run normally on r7800

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Comment by CHKDSK88** [comment]
Compile and run tested on mpc85xx.

**Pull request closed without merging**
