### PR TITLE
nettle: add PKG_CPE_ID

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Add CPE ID for tracking CVEs.

### CODE REVIEW

**Comment by musashino205** [comment]
Please provide more details in the commit message,
- what it means
- why is it necessary

**Comment by PolynomialDivision** [comment]
It is a common OpenWrt Makefile definition for tracking CVEs. See: https://github.com/openwrt/packages/issues/8534#issuecomment-520038157

**Comment by neheb** [comment]
It's used by https://sdwalker.github.io/uscan/index.html

IIRC , if PKG_CPE_ID is missing, it searches for one. Otherwise it uses what is specified.

**Comment by musashino205** [comment]
Ah, thanks for explanations. I didn't know and it's not documented on OpenWrt wiki...

**Comment by svanheule** [comment]
Still, the commit message just copies what the patch does and doesn't explain why. IMHO it should at least state something along the lines of "Add CPE ID for tracking CVEs".

**Comment by PolynomialDivision** [comment]
> Still, the commit message just copies what the patch does and doesn't explain why. IMHO it should at least state something along the lines of "Add CPE ID for tracking CVEs".

Updated all CPE PRs with it. :)

**Pull request closed without merging**
