### PR TITLE
treewide: strip useless `default n` Kconfig lines

### PR DESCRIPTION
**Pull request by Spudz76**
> Kconfig docs say:
> > The default value deliberately defaults to 'n' in order to avoid
> > bloating the build.
> 
> Apply this rule everywhere, to avoid more cloning of bad examples

Discovered in #11453 

There are some others inside patches, which probably means the kernel itself breaks the Kconfig rules, and some of the injected blocks too.

### CODE REVIEW

**Comment by anomeome** [comment]
FYI: this is a [breaking patch](https://github.com/openwrt/openwrt/issues/11933)

**Comment by Spudz76** [comment]
FYI: wasn't my bright idea: https://github.com/openwrt/openwrt/pull/11453#issuecomment-1364742636

**Comment by anomeome** [comment]
I certainly meant no disrespect if that was your takeaway. IMO there was not really anyway this was going to get caught beforehand, just the nature of the beast.

After identifying commit, and pinging a principal as to issue in the above link, I was surprised that it had not been reverted when I checked ~12 hours later, so I assumed not available and thought the two monikers (at that time) in this PR should be made aware, just an attempt to resolve issue. Ain't no big to me, just trying to offer an assist.

**Comment by Ansuel** [comment]
@anomeome I should be more quick with revert but I tried to wait a bit since the problem was already getting bisected and a fix was ready 

Reverting that would  have end up in the following log:
- Revert ...
- Readd commit
- Fix commit 

So i preferred to wait a bit

**Pull request merged**
