### PR TITLE
mpc85xx: switch to Kernel 5.10

### PR DESCRIPTION
**Pull request by aparcar**
Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by adschm** [comment]
swich -> switch

**Comment by blocktrron** [comment]
You'll need to disable builds for the WDR4900, as the kernel won't fit with 5.10. Otherwise looks good.

**Comment by adschm** [comment]
I will take care.

**Comment by adschm** [comment]
Reopening.

Apparantly, the target needs config refresh. p2020 build failed for me due to missing symbols.

**Comment by aparcar** [comment]
@blocktrron can you help out here?

**Comment by CHKDSK88** [comment]
@adschm

I have p2020rdb. I will try fix it.

**Comment by adschm** [comment]
> @adschm
> 
> I have p2020rdb. I will try fix it.

Thanks. Note that `make kernel_oldconfig` did lots of changes for the other subtargets as well, but they at least did not stop the build process.

**Comment by aparcar** [comment]
> > @adschm
> 
> > 
> 
> > I have p2020rdb. I will try fix it.
> 
> 
> 
> Thanks. Note that `make kernel_oldconfig` did lots of changes for the other subtargets as well, but they at least did not stop the build process.

This sounds like something to be CI tested?

**Comment by CHKDSK88** [comment]
https://github.com/openwrt/openwrt/pull/4634/ fix compilation.

**Comment by adschm** [comment]
Thanks, will merge it during the week.

**Pull request closed without merging**
