### PR TITLE
[WIP,RFT,RFC] treewide: fix external toolchain use

### PR DESCRIPTION
**Pull request by Ansuel**
This is a continue of https://github.com/openwrt/openwrt/pull/3733 that looks the be stalled.

I manage to fix it and it looks to work now with a toolchain generated from an openwrt build.
(ideally the next step is to move this to a github action and check how it works)

What i notice we always make wrong is that we are not using the script to generate the config...
The wiki about using an external toolchain is ancient and with wrong info...

Anyway the correct way to setup an openwrt buildroot with an external toolchain is the following

- Assuming the toolchain tar has been extracted
- Run `/scripts/ext-toolchain.sh --toolchain [toolchain dir] --config [config]`

A command example is:
```
/scripts/ext-toolchain.sh --toolchain openwrt-toolchain-ipq806x-generic_gcc-12.1.0_musl_eabi.Linux-x86_64/toolchain-arm_cortex-a15+neon-vfpv4_gcc-12.1.0_musl_eabi --config ipq806x/generic
```

I obviously tested this only with a simple ipq806x configuration... The produced image was run tested on a r7800 and looks to work correctly.

Concern:
---
- This current change remove the wrapper bin created in the toolchain staging dir... I didn't understand why we need them if we can directly use the bin from the toolchain... I assume as a fallback if some package use it?

What to do next:
---
- [x] Test this
- [x] Fix the wiki
- [x] Implement this in github actions

### CODE REVIEW

**Comment by Ansuel** [comment]
I'm testing this under https://github.com/Ansuel/openwrt/runs/7186547625

**Comment by Ansuel** [comment]
News on this.
glibc was broken with the external toolchain script.
Also musl toolchain worked just because our toolchain.config assumed musl by default...

I fixed both error and now the external toolchain config generator correctly generate a config based on the different toolchain...

Also it does assume the toolchain is an openwrt generated one with rules.mk and print error if it can't correctly detect the libc type. (our buildroot supports glibc and musl anyway... but i wonder if uclibc is similar to gnulibc and we can use USE_GLIBC config flag?)

**Comment by Ansuel** [comment]
Merged in master with:
7be01fe13b scripts: ext-toolchain: add support for musl
75311977f5 scripts: ext-toolchain: add support for info.mk in probe_cc
ddeabc75eb scripts: ext-toolchain: actually probe libc type on config generation
f4dd18ca39 scripts: ext-toolchain: add option to overwrite config
53c293262f scripts: ext-toolchain: fix wrong prefix in print_config generation
a90eabf602 rules_mk: don't include wrapped bin with external toolchains
2555ffb453 rules_mk: use gcc versions for external toolchain

Wiki still needs to be updated with correct info on using the script.

**Comment by Ansuel** [comment]
Using make menuconfig is not viable as some config needs to be changed based on the toolchain.

I added the --overwrite-config option to use before the --config to just do what you need

**Comment by Ansuel** [comment]
That would require more discussion about packaging tools... Also that is
very system dependent.

Il Mar 26 Lug 2022, 06:09 antermin ***@***.***> ha scritto:

**Comment by Rondom** [comment]
Will this be cherry-picked to 22.03? It would be nice to profit from the CI improvments depending on this change also on 22.03.

**Comment by Ansuel** [comment]
@Rondom mhhh don't know if it's worth it. @aparcar what do you think ?

**Comment by aparcar** [comment]
Sorry I lost track, why didn't this move forward?

**Comment by Ansuel** [comment]
@aparcar it did but i leaved open since i still have to update the wiki with the new info. Should I also backport this openwrt-22.03?

**Comment by aparcar** [comment]
Looks like a good patch to me

**Comment by Ansuel** [comment]
I fixed the wiki. Too late for backporting this to 22.03. Finally closing.

**Pull request closed without merging**
