### PR TITLE
build: add noarch support

### PR DESCRIPTION
**Pull request by aparcar**
This allows to store all architecture independent packages in a single
folder instead of storing duplicates in each architecture folder.

As a result nearly 3000 less packages are build per architecture and
instead a single *noarch* job creates packages usable by all
architectures.

Built images will have an extended `distfeeds.conf` containing the feeds
separated in arch specific and *noarch*. As this will increase the time
needed for an `opkg update`, future commits could disable the option
`PER_FEED_REPO` as all default feeds are OpenWrt maintained and
build at the same time anyway.

A new *No-Arch* field in the package metadata allows the tools
`./scripts/feeds` to sort on arch dependent and independent packages via
later commits.

Signed-off-by: Paul Spooren <mail@aparcar.org>

> Thanks for your contribution to OpenWrt!

kthxbye

### CODE REVIEW

**Comment by aparcar** [comment]
`distfeeds.conf` would look like this:

```
files/ipkg-aarch64_cortex-a53/base-files/etc/opkg/distfeeds.conf
src/gz openwrt_core https://downloads.openwrt.org/snapshots/targets/mediatek/mt7622/packages
src/gz openwrt_base https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base
src/gz openwrt_libremesh_noarch https://downloads.openwrt.org/snapshots/packages/noarch/libremesh
src/gz openwrt_libremesh https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/libremesh
src/gz openwrt_luci_noarch https://downloads.openwrt.org/snapshots/packages/noarch/luci
src/gz openwrt_luci https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages_noarch https://downloads.openwrt.org/snapshots/packages/noarch/packages
src/gz openwrt_packages https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing_noarch https://downloads.openwrt.org/snapshots/packages/noarch/routing
src/gz openwrt_routing https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony_noarch https://downloads.openwrt.org/snapshots/packages/noarch/telephony
src/gz openwrt_telephony https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony
```

**Comment by hnyman** [comment]
What would be the approximate benefit for non-LuCI feeds?  I think that majortity of your "3000" comes from LuCI.

I think that there are only a few "script-only" packages (or firmware blob only packages) outside LuCI.   Something like adblock, ddns, banip, bcp38 etc., but there aren't that many such packages.

Just thinking if this adds more complication than solves things.

**Comment by aparcar** [comment]
I think it cover nearly all LuCI stuff plus translations, Python and Lua. I'll run a test later how much storage this is.

I don't see how the complexity is increased by this, what is your concern?

**Comment by jow-** [comment]
> I don't see how the complexity is increased by this, what is your concern?

 - You're introducing a new metadata field
 - You're duplicating the amount of sources
 - The repository layout gets changed, downstream users now need to take the "noarch" repo into consideration in addition to the target and pkg-arch specific ones
 - By merging this change, multiple concurrently running builders with different source versions each will upload into the same globally shared repository with unforeseeable consequences (think e.g. tightly coupled packages like libfoo1 + libfoo-data where the data package is PKGARCH:=all - now libfoo1 gets updated to libfoo2 while one builder compiles and older source stamp including libfoo1 while another arch builder compiles a slightly newer source stamp including libfoo2)
 - Conditional build time dependencies (e.g. DEPENDS:=+@x86_64:foo) will be improperly handled, an unrelated pkgarch might end up using shared packages which were built under a different arch, resulting in differently rendered binary dependencies

If the goal is to reduce disk space on the destination server, ensuring reproducible builds and implementing `rsync --link-dest` or another, offline hardlink-based deduplication seems like a more worthwhile goal.

**Pull request closed without merging**
