### PR TITLE
ipq40xx: Drop nand features from Chromium image

### PR DESCRIPTION
**Pull request by computersforpeace**
This target doesn't actually use NAND.

### CODE REVIEW

**Comment by DragonBluep** [comment]
It's worth to drop UBI fs support from kernel config file, too.

**Comment by KanjiMonster** [comment]
s/FEAUTRES/FEATURES/

**Comment by computersforpeace** [comment]
I dropped UBI and UBIFS stuff (moving it into generic and microtik subtargets), and fixed the spelling. Thanks.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
