### PR TITLE
[23.05]: filogic: add support for GL.iNet GL-MT6000

### PR DESCRIPTION
**Pull request by zhaojh329**

### CODE REVIEW

**Comment by 1715173329** [comment]
Please backport commit 85b0d7592c45 as well, thanks!

**Comment by zhaojh329** [comment]
> Please backport commit [85b0d75](https://github.com/openwrt/openwrt/commit/85b0d7592c454f2e4e02be043a1e433c67df4e41) as well, thanks!

OK.

**Comment by xabolcs** [comment]
> Please verify using the latest `openwrt-23.05` branch

Thanks for merging!
For the record this PR landed as
* b530d492a9 filogic: add support for GL.iNet GL-MT6000
* f3a8820959 mediatek: filogic: remove kmod-usb2 for GL-MT6000
* 6143b730fc uboot-mediatek: fix typo in bootmenu for GL-MT6000
* cc285dc2b6 generic: net: phy: realtek: add interrupt support for RTL8221B
* 5a0bdab24c mt76: drop default eeprom file for mt7986-firmware
* f8c149dcbd mediatek: fix eeprom loading (Mercusys MR90X v1)

**Comment by ewangsoft** [comment]
/etc/config/network:
config device
	option name 'eth1'
	option macaddr 'XX:XX:XX:XX:XX:XX'
	option ipv6 '1'
config device
	option type 'bridge'
	option name 'br-wan'
	list ports 'eth1'
	option igmp_snooping '1'
	option ipv6 '1'
	option multicast '1'
	option macaddr 'XX:XX:XX:XX:XX:XX'
	option promisc '1'
config interface 'wan'
	option device 'br-wan'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.0'
	option gateway '192.168.1.254'
	list dns '114.114.114.114'

/etc/config/dhcp:
config dhcp 'wan'
	option interface 'wan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv4 'server'
	list dhcp_option '1,255.255.0.0'
	list dhcp_option '3,192.168.1.2'
	list dhcp_option '6,114.114.114.114'
	option master '1'
	option ra 'relay'
	option dhcpv6 'relay'
	option ndp 'relay'

/etc/config/wireless:
config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'wan'
	option mode 'ap'
	option ssid 'OpenWrt'
	option encryption 'psk2+ccmp'
	option key 'xxxxxxxx'

A terminal connected to the openwrt SSID is unable to obtain an IPV4 address.
Who can give me some guidance?

**Pull request closed without merging**
