### PR TITLE
CC: openssl: bump to 1.0.2l

### PR DESCRIPTION
**Pull request by peterwillcn**
1. openssl upgrade 1.0.2l
2. ugps: fix filename to eliminate build problems due to ordering PKG_SOURCE_VERSION is not defined leading to a filename "ugps-.tar.bz2"

### CODE REVIEW

**Comment by wigyori** [comment]
Hi,

Can you please:
 - split the changes for the two packages into separate commits
 - the commit titles should be "CC: $package: bump to $xyz" - the separate commits also need to have proper titles.

Thanks,
-w-

**Comment by peterwillcn** [comment]
@wigyori OK.

**Comment by wigyori** [comment]
Hi @peterwillcn, I still see the commits with incorrect tags and without signed-off-by. Can you please add these and rework the patch queue?

> Subject: [PATCH 1/2] Fixed build problems for ugps
> 
> ---
> 
> Subject: [PATCH 2/2] Upgrade openssl to 1.0.2l
> 
> ---

Thanks,
-w-

**Comment by wigyori** [comment]
Merged in #559 , thanks for the heads-up.

**Pull request closed without merging**
