### PR TITLE
[23.05] mediatek: filogic:  Add support for Xiaomi AX3000T and clean up Xiaomi WR30U

### PR DESCRIPTION
**Pull request by nicefile**
Add support AX3000T in 23.05 
Also some clean up for it's twin brother WR30U included 
wr30u-112m-nmbm version was removed as not supported uboot-mod fork
One of backported commit  also fixes failsafe mode for Mediatek Filogic devices with no lan1.

Signed-off-by: Robert Senderek <robert.senderek@10g.pl>

### CODE REVIEW

**Comment by nicefile** [comment]
look fine by me ... clean build with wr30u and ax3000t on my [gdrive](https://drive.google.com/drive/folders/1X4EHa1bF2q94adMgJ6J_tbVpUYGeuUgy?usp=sharing)

**Comment by nicefile** [comment]
updated to most recent "at time" branch. Here is bootlog 
[bootlog-23.05-ubootmod.txt](https://github.com/openwrt/openwrt/files/15274556/bootlog-23.05-ubootmod.txt)

**Comment by nachum37** [comment]
Thanks to all involved!

Please explain me how it works, why is the buildbot waiting for the next version and not building version 23.05.3 right now?

**Comment by nicefile** [comment]
@nachum37 23.05.3 is 4th stable build of branch 23.05 .... It is final and won't be including AX3000T  .Next stable build named 23.05.4 will contain all recent changes and will add AX3000T support and few other models.

**Comment by nachum37** [comment]
> @nachum37 23.05.3 is 4th stable build of branch 23.05 .... It is final and won't include AX3000T .Next stable build named 23.05.4 will contain all recent changes and will add AX3000T support and few other models.

@nicefile Thanks your reply. Why in addition to the 23.05 branch tags such as 23.05.3 is necessarily? Why does the buildbot not build 23.05 with these changes as soon as we merge into the stable branch?

**Comment by nicefile** [comment]
@nachum37 in 23.05 there is no point to build it daily / weekly as branch changes are not so often. On the other hand master branch is updated few times a day and buildbot create images daily.  
Also from my local yard  there is user who among other things compile 23.05 branch every couple weeks. They're not official builds ofc but they do the trik. You can find more [here](https://[dl.eko.one.pl](https://dl.eko.one.pl/luci/openwrt-23.05/mediatek/filogic/)/luci/openwrt-23.05/mediatek/filogic/)

**Comment by nachum37** [comment]
@nicefile the link is broken

**Pull request merged**
