### PR TITLE
HC5861 update wan port to consistent with the original equipment

### PR DESCRIPTION
**Pull request by lzf213**
update wan port  to consistent with the original equipment

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Your commit has formal issues. Please have a look at the linked document in the initial post you forgot to remove.

**Comment by adrianschmutzler** [comment]
Please respond and update your commit, or we will close it.

**Comment by ptpt52** [comment]
hi, we set port 5 as wan because it is a Gigabit port

**Comment by adrianschmutzler** [comment]
Closing this because there has been no response by the original author. Feel free to ask for reopening if you want to continue working on this.

**Comment by adrianschmutzler** [comment]
@ptpt52 That's interesting. In principle, the WAN/LAN assignment in OpenWrt should be same as with vendor OS (if the OS has such a setting by default). In my view, adjustment like setting a particular port to WAN/LAN because of its speed should be left to the user, as we cannot anticipate all the actual use cases of the users ...

**Pull request closed without merging**
