### PR TITLE
rockchip: introduce 5.15 testing kernel

### PR DESCRIPTION
**Pull request by wurzerj**
Makefile:
Added testing kernel

rockchip/patches-5.10 -> rockchip/patches-5.15:
Removed 004-v5.13-rockchip-rk3399-Add-support-for-FriendlyARM-NanoPi-R.patch ... appears to be upstreamed
Removed 104-rockchip-use-USB-host-by-default-on-rk3399-rock-pi-4.patch ... appears to be upstreamed
Updated remaining patches using "make target/linux/refresh V=s"

armv8/config-5.15:
Refresh config for kernel 5.15 using make kernel_menuconfig

Compiled for NanoPi R4S, boots successfully, running stable so far.

Signed-off-by: Juergen Wurzer [wurzer.juergen@gmail.com](mailto:wurzer.juergen@gmail.com)

### CODE REVIEW

**Comment by mans0n** [comment]
Hi, not a strict requirement but could you consider splitting your patch into multiple pieces like #9628? (optional config-5.10 refresh -> copy -> refresh patch -> refresh config -> add testing version) That will also help explaining the config-5.{10,15} diff.

**Comment by wurzerj** [comment]
@mans0n: Got it, I'll try to get it done today.

**Comment by wurzerj** [comment]
@mans0n: Done.

**Comment by SirDMZ** [comment]
Ran for over 24 hours on R4S, appears to be fine.

**Comment by mj22226** [comment]
@wurzerj Patches 101 and 102 are in the uptream kernel and can be removed, otherwise it will break the nanopi r2s, patch 103 needs to be manually edited. 
```
--- a/arch/arm64/boot/dts/rockchip/rk3328-nanopi-r2s.dts
+++ b/arch/arm64/boot/dts/rockchip/rk3328-nanopi-r2s.dts
@@ -404,6 +404,7 @@
 	rtl8153: device@2 {
 		compatible = "usbbda,8153";
 		reg = <2>;
+		realtek,led-data = <0x87>;
 	};
 };
```

**Comment by wurzerj** [comment]
@mj22226: Thanks for the feedback.
- Regarding 101 and 102 I believe you are referring to https://github.com/torvalds/linux/commit/d49f120e27dc1689e11a14e9714e63a390dd4520, thanks for the hit. I'll remove them.
- Do you have a "clean" 103 patch I could use (https://github.com/mj22226/openwrt/blob/e904d1dfdc20d39625c706ae57e95d7b1f097b55/target/linux/rockchip/patches-5.15/103-arm64-rockchip-add-OF-node-for-USB-eth-on-NanoPi-R2S.patch) available, including proper description and listing you as signed-off-by? It could make sense to introduce a new patch file / re-name the file, since patching the LED is the only missing piece not being upstreamed yet. 

I'll try to re-submit an update asap ... likely tomorrow.

**Comment by mj22226** [comment]
@wurzerj I don't think a new patch is necessary, simply mention you manually edited.

**Comment by wurzerj** [comment]
@mj22226: I pushed the changes as discussed. Thanks for your help! Before pushing I tested a fresh build on my R4S ... everything seems to be stable since ~12 hours.

**Comment by mans0n** [comment]
Please do not add revert commits, do rebase instead.

**Comment by wurzerj** [comment]
@mans0n: Done, sorry for the extra effort.

**Comment by wurzerj** [comment]
Modified commit messages to fix some formality checks.

**Comment by lucize** [comment]
@wurzerj 
the trend is to switch to 5.15, so it's safe to remove 5.10
tested on rk3328 Rock64 board, for me it seems that these kernel symbols are missing from the config:

```
DRM Support for Rockchip (DRM_ROCKCHIP) [N/m/?] (NEW)
ASoC support for Rockchip (SND_SOC_ROCKCHIP) [N/m/?] (NEW)
Rockchip RK817 audio CODEC (SND_SOC_RK817) [N/m/?] (NEW)
```

otherwise
Tested-by: Lucian Cristian <lucian.cristian@gmail.com>

**Comment by SirDMZ** [comment]
Would probably need to be reworked to include this change.
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=b1346d35e470662c98912efc49108733ee7c101c

**Comment by wurzerj** [comment]
Thanks for the feedback. I’ll try to update the patch in the next couple of days.

**Comment by wurzerj** [comment]
As promised, I updated the patch:

- @SirDMZ: Done.
- @lucize: Thanks for your feedback. I double-checked, those kernel symbols do not seem to be required at the moment. I guess they are related to your patch adding support for Rock64 board (https://github.com/openwrt/openwrt/pull/9922). To keep the rockchip 5.15 patch clean and not mix other stuff with it I decided to not include those symbols for now. From my perspective it would be a lot cleaner if you then add those with your Rock64 board patch. I hope you understand.

Regarding testing:

- I previously ran kernel 5.15.31 on my main R4S router with 63 days uptime and not problems at all.
- Overnight I ran a build with the updated patch and kernel 5.15.45 on my second R4S router for about 6 hours ... also no problems.

I hope this will be merged soon and @lucize can add the Rock64 board support on top of it.

**Comment by TLarg** [comment]
Fails to build with `CONFIG_ALL_KMODS=y CONFIG_ALL_NONSHARED=y`
I accounted these missing kernel symbols:
```
Rockchip RK805 PMIC power key support (INPUT_RK805_PWRKEY) [N/m/y/?] (NEW)
Rockchip Image Signal Processing v1 Unit driver (VIDEO_ROCKCHIP_ISP1) [N/m/?] (NEW)
DRM Support for Rockchip (DRM_ROCKCHIP) [N/m/?] (NEW)
ASoC support for Rockchip (SND_SOC_ROCKCHIP) [N/m/?] (NEW)
Rockchip RK817 audio CODEC (SND_SOC_RK817) [N/m/?] (NEW)
Rockchip SARADC driver (ROCKCHIP_SARADC) [N/m/?] (NEW)
Rockchip's Cryptographic Engine driver (CRYPTO_DEV_ROCKCHIP) [N/m/y/?] (NEW)
```

**Comment by wurzerj** [comment]
@TLarg: Thanks for the feedback, will check + update asap ... likely tomorrow.

**Comment by wurzerj** [comment]
@TLarg: Could you please send me your ".config" file. I tried to reproduce the missing kernel symbols, but did not get those when trying to compile latest master. I'll then try again.

I'd also believe most people would not build OpenWrt setting those parameters to yes, so I do not think this should be a blocker for a merge.

**Comment by lucize** [comment]
I'll say it also in here, again. You can add whatever kernel symbols as not configured, they will do no harm, we will just delay the already late merge of this, better be on the safe side than having failures
Regards!

**Comment by wurzerj** [comment]
@lucize: Ok, will add those asap.

**Comment by wurzerj** [comment]
@lucize, @TLarg: Done.

**Comment by blocktrron** [comment]
Merged to my staging tree, thanks!

**Pull request closed without merging**
