### PR TITLE
ramips: improve support for MT7620 Phicomm K2x devices

### PR DESCRIPTION
**Pull request by DragonBluep**
Description:
 * Improve compatibility of the device tree include file. Now a new .dtsi
   file will support both PSG1218A, PSG1218B and K2G.

### CODE REVIEW

**Comment by adschm** [comment]
This needs to be broken down into several individual patches, one for each logic (separate) step.

Please remove the merge commits and make sure all patches follow the guidelines (as "ramips: improve support for mt7620a Phicomm K2x devices" seems to do, apart from that it needs to be split).

**Comment by DragonBluep** [comment]
> This needs to be broken down into several individual patches, one for each logic (separate) step.
> 
> Please remove the merge commits and make sure all patches follow the guidelines (as "ramips: improve support for mt7620a Phicomm K2x devices" seems to do, apart from that it needs to be split).

okay, I have merged all commit and submit again.

**Comment by adschm** [comment]
The task was to break down commits into logical steps.
One commit for changing network config of existing devices, one commit for changing pinmux of existing devices, one commit for adding the new device ... etc.

**Comment by DragonBluep** [comment]
Need reviews. Yours Sincerely. @adschm

**Comment by adschm** [comment]
So, for the last time, please separate this into the different subjects you are addressing.
I won't repeat this another time.

**Comment by adschm** [comment]
Thanks, I will merge this later today.

**Pull request closed without merging**
