### PR TITLE
squashfs: switch to squashfs-tools-ng

### PR DESCRIPTION
**Pull request by aparcar**
The `squashfs-tools-ng` is a reimplementation of `squashfs-tools` of
which a fork called `squashfskit` is currently used withn OpenWrt.

Tested with x86/64 and created image boots fine in qemu.

ImageBuilder also tested and works.

Tested and works on:
- x86/64 qemu
- mediatek/mt7622 Linksys 8540

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
@lynxis please join in the fun

**Comment by lynxis** [comment]
Plan to test on:

- [ ] wr841v8
- [ ] wr841v9
- [ ] wr841v13
- [ ] wdr1043v1
- [ ] wdr1043v3
- [ ] wdr1043v5
- [ ] wdr4300
- [ ] ubnt nanostation m xm
- [ ] ubnt nanostation m xw

**Comment by lynxis** [comment]
@aparcar can you install **rdsquashfs**?
The uid in the image seems to be wrong, it's still the uid of the user.

**Comment by lynxis** [comment]
the image seems to be closer now.

**Comment by aparcar** [comment]
I tried a quick benchmark for mksquashfs4, gensquashfs and tar2sqfs using [hyperfine](https://github.com/sharkdp/hyperfine).

```bash
[a@tb target-x86_64_musl (squashfs-tools-ng-testbuild)]$ hyperfine --warmup 3 "~/src/openwrt/openwrt/staging_dir/host/bin/mksquashfs4 root-x86/ mksquashfs4.bin -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2  -b 1024k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1" 'tar -c --sort=name --owner=0 --group=0 --numeric-owner -C root-x86/ . | tar2sqfs -d uid=0,gid=0,mtime=0 -f tar2squfs.bin' 'gensquashfs -f --pack-dir root-x86/ gensquashfs.bin'
Benchmark #1: ~/src/openwrt/openwrt/staging_dir/host/bin/mksquashfs4 root-x86/ mksquashfs4.bin -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2  -b 1024k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1
  Time (mean ± σ):     15.257 s ±  0.594 s    [User: 18.593 s, System: 0.084 s]
  Range (min … max):   14.531 s … 16.264 s    10 runs

Benchmark #2: tar -c --sort=name --owner=0 --group=0 --numeric-owner -C root-x86/ . | tar2sqfs -d uid=0,gid=0,mtime=0 -f tar2sqfs.bin
  Time (mean ± σ):      5.565 s ±  0.220 s    [User: 41.253 s, System: 0.665 s]
  Range (min … max):    5.362 s …  6.020 s    10 runs

Benchmark #3: gensquashfs -f --pack-dir root-x86/ gensquashfs.bin
  Time (mean ± σ):      5.496 s ±  0.200 s    [User: 40.911 s, System: 0.575 s]
  Range (min … max):    5.326 s …  5.976 s    10 runs

Summary
  'gensquashfs -f --pack-dir root-x86/ genquashfs.bin' ran
    1.01 ± 0.05 times faster than 'tar -c --sort=name --owner=0 --group=0 --numeric-owner -C root-x86/ . | tar2sqfs -d uid=0,gid=0,mtime=0 -f tar2sqfs.bin'
    2.78 ± 0.15 times faster than '~/src/openwrt/openwrt/staging_dir/host/bin/mksquashfs4 root-x86/ mksquashfs4.bin -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2  -b 1024k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1'
```

As `gensquashfs` does not support the user/group management yet (maybe ping upstream?) I'd suggest to use the `tar2sqfs` solution. Also both tools end up with different access rights.

The file size of `mksquashfs4` is however the best... With a difference of 2Mb this seems like a dead end if we don't find any optimizations for `squashfs-tools-ng`.

```bash
54421537 18284 -rw-------  1 a a 18722816 Apr 21 23:20 tar2squfs.bin
54421538 16232 -rw-r--r--  1 a a 16619620 Apr 21 23:19 mksquashfs4.bin
54421536 18280 -rw-------  1 a a 18718720 Apr 21 22:59 gensquashfs.bin
```

**Comment by aparcar** [comment]
@AgentD mind giving some advise on this?

**Comment by AgentD** [comment]
Oh, one more thing: could you run `sqfsdiff -SCOP` on the images? This way we can check if the difference in size is *actually* caused by the data packing and not the meta data.

**Comment by aparcar** [comment]
Hi, thank you very much for the informative answer and joining the discussion!

The `sqfsdiff` output seem to be broken when looking at `mksquashfs4` files, @lynxis do you know if we use any special methods which could break it?

```bash
[a@tb target-x86_64_musl (squashfs-tools-ng-testbuild)]$ sqfsdiff -SCOP -a tar2sqfs.bin -b mksquashfs4.bin
mksquashfs4.bin: reading compressor options: data corrupted.
[a@tb target-x86_64_musl (squashfs-tools-ng-testbuild)]$ sqfsdiff -SCOP -a tar2sqfs.bin -b gensquashfs.bin
======== super blocks are different ========
ID table entries: +1
total bytes used: -916
Location of root inode differs
Location of ID table differs
Location of directory table differs
Location of fragment table differs
```

**Comment by lynxis** [comment]
@aparcar I think we're missing the compression options, that might be also a good pointer, why the files are so big.

**Comment by aparcar** [comment]
So basically we need to extend `st-ng` with the two options plus `--all-root`? @AgentD would these options be of your interest, too? If not we would end up with another patched squashfs implementation 😑

**Comment by AgentD** [comment]
In the current master branch, gensquashfs now has 3 new options:
```
--set-uid, -u <number>
--set-gid, -g <number>
--all-root
```
Those can be used to force UID/GID for *all* inodes to a specific value before the meta data is packed.

The last one is a short hand for `-u 0 -g 0`.

As for compressor options, `gensquashfs` & `tar2sqfs` support the same compressor micromanagement that `mksquashfs` does, the options just have different names. Of course, if squashfs-tools-ng is built without XZ support, this might also explain the size difference. By default it chooses the xz compressor, *if available*.

If there are any quick questions I can help with, I'm in #openwrt-devel on Freenode, using the nick goliath.

**Comment by aparcar** [comment]
@AgentD great, the `--all-root` options looks like a perfect fit.

Regarding size I'm unsure what I should do. Looking at the `--help` output I see `gzip lzma lzo xz` supported (the Debian installation supports `	gzip lzma lzo xz lz4 zstd`), so I'm guessing `xz` is available? Using `-X help` only shows `dictsize` as an configuration option (same for Debian). Am I looking at the from place?

**Comment by aparcar** [comment]
Thanks to @AgentD I rerun the tests with a blocksize of 1 MegaByte (adding `-b 1M`) and now the created files are even smaller than `mksquashfs`!

```bash
39617055 13516 -rw------- 1 a a 13840384 Mai  2 13:02 gensquashfs.bin
39617053 13524 -rw-r--r-- 1 a a 13848486 Mai  2 12:59 mksquashfs4.bin
39617054 13516 -rw------- 1 a a 13840384 Mai  2 13:01 tar2squfs.bin
```

**Comment by aparcar** [comment]
The latest test results:

```bash
[a@tb target-x86_64_musl (squashfs-tools-ng)]$ hyperfine --warmup 3 "mksquashfs4 root-x86/ mksquashfs4.bin -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2  -b 1024k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1" 'gensquashfs -f --pack-dir root-x86/ --all-root -b 1M gensquashfs.bin'
Benchmark #1: mksquashfs4 root-x86/ mksquashfs4.bin -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2  -b 1024k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1
  Time (mean ± σ):     16.547 s ±  0.581 s    [User: 18.917 s, System: 0.073 s]
  Range (min … max):   15.806 s … 17.602 s    10 runs

Benchmark #2: gensquashfs -f --pack-dir root-x86/ --all-root -b 1M gensquashfs.bin
  Time (mean ± σ):      6.404 s ±  0.422 s    [User: 42.350 s, System: 0.186 s]
  Range (min … max):    5.889 s …  7.112 s    10 runs

Summary
  'gensquashfs -f --pack-dir root-x86/ --all-root -b 1M gensquashfs.bin' ran
    2.58 ± 0.19 times faster than 'mksquashfs4 root-x86/ mksquashfs4.bin -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2  -b 1024k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1'
[a@tb target-x86_64_musl (squashfs-tools-ng)]$ ls -lisa *.bin
39586222 13516 -rw-r--r-- 1 a a 13840384 Mai  3 09:02 gensquashfs.bin
39586221 13524 -rw-r--r-- 1 a a 13848486 Mai  3 09:01 mksquashfs4.bin
```

So it's better in time and space!

**Comment by aparcar** [comment]
It's now updated to version 0.9.1

**Comment by lynxis** [comment]
@aparcar it's still missing the same compression arguments as mksquashfs. I think this is also missing in squashfs-tools-ng, because sqfsdiff cannot parse the mksquashfs image.

**Comment by aparcar** [comment]
What special arguments are needed? Isn't it enough that it boots and creates smaller images?

**Comment by AgentD** [comment]
The size difference was due to the missing block size argument for `gensquashfs`. Using the same images and unpacking/repacking them with the correct block size, the result is similar to `mksquashfs4`.

If you mean the bcj filters for XZ, they are available in `gensquashfs` through the -X option. Adding bcj filters just shaves off some extra ~50k:

```shell
sqfs2tar ./tar2squfs.bin | tar2sqfs -b 1M test.sqfs
sqfs2tar ./tar2squfs.bin | tar2sqfs -b 1M -Xx86 test2.sqfs
```
> -rw-r--r--. 1 goliath goliath 13848486 May  3 00:44 mksquashfs4.bin
> -rw-r--r--. 1 goliath goliath 13840384 May  3 21:26 test.sqfs
> -rw-r--r--. 1 goliath goliath 13791232 May  3 21:26 test2.sqfs

**Comment by lynxis** [comment]
@AgentD I would like to parse more specific xz options.
tar2sqfs -c xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2 ./tar2squfs.bin
(or similiar)

**Comment by AgentD** [comment]
Those options are not in upstream mksquashfs, but I managed to find them in the squashfskit fork.

I tried patching squahfs-tools-ng to expose those and ran a few tests:

```shell
sqfs2tar ./mksquashfs4.bin | tar2sqfs -b 1M -f test.sqfs
sqfs2tar ./mksquashfs4.bin | tar2sqfs -b 1M -X x86 -f test2.sqfs
sqfs2tar ./mksquashfs4.bin | tar2sqfs -b 1M -X x86,lc=0,lp=2,pb=2 -f test3.sqfs
sqfs2tar ./mksquashfs4.bin | tar2sqfs -b 1M -X lc=0,lp=2,pb=2 -f test4.sqfs
sqfs2tar ./mksquashfs4.bin | tar2sqfs -b 1M -X lc=0,lp=2,pb=2,extreme -f test5.sqfs
sqfs2tar ./mksquashfs4.bin | tar2sqfs -b 1M -X x86,lc=0,lp=2,pb=2,extreme -f test6.sqfs
```

Setting lc, lp and pb doesn't make any difference, using the "extreme" flag *does* shave off a few kb:

> -rw-r--r--. 1 goliath goliath 13901824 May  4 12:05 test.sqfs
> -rw-r--r--. 1 goliath goliath 13852672 May  4 12:06 test2.sqfs
> -rw-r--r--. 1 goliath goliath 13852672 May  4 12:06 test3.sqfs
> -rw-r--r--. 1 goliath goliath 13901824 May  4 12:06 test4.sqfs
> -rw-r--r--. 1 goliath goliath 13873152 May  4 12:21 test5.sqfs
> -rw-r--r--. 1 goliath goliath 13824000 May  4 12:22 test6.sqfs

My pocket calculator tells me that the difference between the smallest and the largest are 77824 bytes, or ~0.56% of the size of the largest image.
 
I wonder how you actually arrived on those values for lc, lp and pb? Especially after reading the documentation on what they actually do (i.e. the comments in the xz-utils source code) I'm kind of puzzled.

**Comment by nbd168** [comment]
If I remember correctly, the compression options make a bigger difference on MIPS binaries (maybe ARM too).

**Comment by aparcar** [comment]
@AgentD please provide the patch so we can run some tests

**Comment by aparcar** [comment]
@lynxis please have a look again, it now uses latest squashfs-tools-ng version which supports the compression parameters. Also added and fixed the packfile from your staging tree

**Comment by aparcar** [comment]
If just tested two images and the OpenWrt patched squashfs version is non deterministic. It doesn't support the `--all-time` option which is already supported in the upstream squashfs-tools version. I'd really like to proceed with this PR or at least upgrade squashfs-tools to the upstream version.

**Comment by lynxis** [comment]
The OpenWrt version is different from the upstream version, but it is reproudcible. It doesn't need the `--all-time` because it's already using SOURCE_DATE_EPOCH for that. If it would not reproducible, the results at https://tests.reproducible-builds.org/openwrt/openwrt_ath97.html would show it.

**Comment by aparcar** [comment]
Rebased and updated to version v1.0.0

**Comment by aparcar** [comment]
Rebased and updated to 1.0.3. I'll do some testing now but don't want this be become part of 20.x

**Comment by aparcar** [comment]
QEMU stuck in a reboot loop using squashfs-ng

image

**Comment by AgentD** [comment]
Hi @aparcar ,

I just browser through the change set and it appears the problem is that there are no files in the resulting SquashFS because the listing file doesn't pack any. You only write the `/dev` directory and `/dev/console` file into the image. I think what the intention here is, is to get the rest of the entries from the pack directory?

The idea behind the pack directory in `gensquashfs` was to get files from there that are explicitly specified in the listing file, the same way that `gen_init_cpio` works.

The current master branch of squashfs-tools-ng has a `find`-like `glob` command that can be used to scan parts of the pack directory explicitly and apply a shell-glob pattern. With those changes, adding a `glob / * * *` line should recursively scan the entire input tree and add the entries with their respective permissions directly to the root directory.

I plan to release the current master as version 1.1.0 over the weekend and do some further regression testing on my end until then.

**Comment by adschm** [comment]
@aparcar This should be updated or closed.

**Comment by aparcar** [comment]
Will update this soon

**Comment by aparcar** [comment]
Rebased and tested, works as expected on x86/64. Will try to do some more device testing.

**Comment by Ansuel** [comment]
Considering the proposal of the other filesystem (and the fact that it's no ready) any chance we get some interest in this again ?

**Comment by Ansuel** [comment]
@robimarko @mpratt14 considering squashfs tools reborn and i read that squashfs-tools-ng totally changed and reimplemented stuff should we work on updating the normal tools and do not care to migrate to squashfs-tools-ng?

**Comment by aparcar** [comment]
Yes please do that, however there is a bunch of downstream patches we added

**Comment by robimarko** [comment]
Yeah, squahfs-tools-ng went their own way, but squashfs-tools are now regularly developed so we should move to those especially since squashfskit4 did not see any development since 2019.

It would be nice to see what was added to squashfskit4 that may be potentially needed

**Comment by Ansuel** [comment]
@aparcar closing this as we switched to squashfs maintained version.

**Pull request closed without merging**
