### PR TITLE
mediatek: mt7622: use schedutil governor as default

### PR DESCRIPTION
**Pull request by ghost**
Use schedutil governor as default by @selanf #4440

The cpu runs no longer all the time at 1,3Xghz
this causes for me about 5-10°C less cpu temperature
my device runs 95% of time at 300mhz

But running the device by git-default (USERSPACE) at full speed causes 5-10°C more what reduced the lifespan for sure, so something should be changed.

As mentioned @elan on the [OpenWRT forum](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1222) "ondemand" is obsolete and now it is replaced by "schedutil" and has no stucks issues after reboot command like ondemand.

### CODE REVIEW

**Comment by yusername** [comment]
I'm not sure about this, but @Jip-Hop [confirm that it works](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1227).

@stintel @dangowrt @BKPepe @aparcar @hauke @feckert @ffainelli

**Comment by stintel** [comment]
Can you stop spamming developers?

**Comment by yusername** [comment]
I'm not sure about this, but @Gix, @elan and @Jip-Hop confirm that it works.
[Belkin RT3200/Linksys E8450 WiFi AX discussion - #1177 by Gix](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1177)
[Belkin RT3200/Linksys E8450 WiFi AX discussion - #1227 by Jip-Hop](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1227)

**Comment by yusername** [comment]
I'm not sure about this because I'm an idiot, but @Gix, @elan and @Jip-Hop confirm that it works.
[Belkin RT3200/Linksys E8450 WiFi AX discussion - #1177 by Gix](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1177)
[Belkin RT3200/Linksys E8450 WiFi AX discussion - #1222 by elan](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1222)
[Belkin RT3200/Linksys E8450 WiFi AX discussion - #1227 by Jip-Hop](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1227)

**Comment by yusername** [comment]
@Gix, @elan and @Jip-Hop confirm that it works.
[Belkin RT3200/Linksys E8450 WiFi AX discussion - #1177 by Gix](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1177)
[Belkin RT3200/Linksys E8450 WiFi AX discussion - #1222 by elan](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1222)
[Belkin RT3200/Linksys E8450 WiFi AX discussion - #1227 by Jip-Hop](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1227)

**Comment by yusername** [comment]
@dangowrt can you accept the request, please.

**Comment by dangowrt** [comment]
It's nice that this works, please go ahead and document it on the device page on the wiki, so people find this indeed helpful information.
However, I don't think making this kinda arbitrary target-wide changes in code is a good idea, unless it is provided in form of a general purpose opt-in package integrating cpufreq settings into UCI. If a that stage, adding device-specific uci-defaults to change cpufreq settings can be discussed.

**Comment by yusername** [comment]
You have the last word, not me.

I sent this request because they say it works and I don't know how to check if what they say is true or false.

**Comment by yusername** [comment]
You have the last word, not me.

I sent this request because they say it works and I don't know how to check if what they say is true or false.

**Comment by Jip-Hop** [comment]
Do I understand correctly the reason `CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL=y` can't be set is because it would apply to [all mt7622 targets](https://openwrt.org/toh/views/toh_extended_all?dataflt%5BCPU*%7E%5D=mt7622), and they don't benefit from this change?

**Comment by dangowrt** [comment]
They may benefit (in terms of lower energy consumption and temperature), but it's untested (who knows if all devices even boot at all rates? past has shown this seems to be a sensitive spot). and it hurts latency.
And one may well ask: Why only for MT7622? cpufreq is supported on MT7623 as well, for example, but also on many other systems.

**Comment by Jip-Hop** [comment]
I get it. Though I think it would be better to have `ondemand` or `schedutil` as the default for the devices for which this does work (Belkin RT3200/Linksys E8450), instead of opt-in. Despite the latency, the lower energy consumption, lower temperature and the longer lifetime would benefit the devices and users generally :) But not everyone may know about it. And if they do they may not care/dare to change it if it's not the default, or may lose the change after a reset to default settings. The ones who want to increase performance at the risk of reduced lifetime could opt-out.

Instead of applying this change target-wide, would it be an option to apply `ondemand` or `schedutil` as the default for tested devices? For example in: [410-add-linksys-e8450.patch](https://github.com/openwrt/openwrt/blob/b6da10f2d1b82ca3c6d7cac55403d93b64828cdd/package/boot/uboot-mediatek/patches/410-add-linksys-e8450.patch).

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by dangowrt** [comment]
Please stop the spam.

**Comment by OpenWrtSuck** [comment]
OpenWrt 🤢🤮

@stintel @dangowrt @hauke

**Comment by dangowrt** [comment]
As previously stated, a meaningful abstraction which makes cpufreq configurable **on all devices supported** using LuCI would be an acceptable solution. Changing a **target-wide** default may seem convenient, but it's really the wrong place to do this.

See https://github.com/openwrt/openwrt/pull/4933#issuecomment-1008083154 and https://github.com/openwrt/openwrt/pull/4933#issuecomment-1009513661

Doing this per-board by letting U-Boot supply a kernel cmdline parameter switching the default governor also isn't exactly clean -- if we would change the per-board default, the right place would be to append the needed arguments kernel cmdline by adding `bootargs` attribute to an to-be-added `chosen` section of to the board's device tree source.

However, as there was an ongoing debate, I didn't immediately close the PR. Now that it is used for spam, that's the way to go (sorry @Jip-Hop, please open a new PR with a proper solution if you would like to work on this).

To our spamming friend: You honestly expect this to be dealt with by anyone volunteering here when commenting using a deleted account, previously called OpenWrtSuck before deleting it, or by giving fake-approvals? By showing such behavior your are sabotaging your own interests, it will make it **less likely for this or any related change to be dealt with by anyone because nobody like to be pressured, pushed or insulted**.

**Comment by OpenWrtGetOnMyLevel** [comment]
@dangowrt I forgive you, just don't do it again.

[I forgive you](https://www.youtube.com/watch?v=P3i2oJnCN_A&t=159s)

https://user-images.githubusercontent.com/97692550/149384836-39bc5ab0-65ac-4e00-b736-0d3526282082.mp4

**Comment by champtar** [comment]
FYI I just blocked the spammer

**Comment by DanielOpenWrtSorry** [comment]
Sorry @dangowrt, I just wanted to bother you for no reason and I'm really sorry, I was bored and I did it without thinking.

kitten-love

**Pull request closed without merging**
