### PR TITLE
gemini,layerscape,oxnas: fix disabled option CONFIG_BPF_SYSCALL

### PR DESCRIPTION
**Pull request by guidosarducci**
### Description:
Remove the target-level config setting and respect that from the generic kernel config, which is "enabled" tree-wide. The same was previously done for sunxi in 247ef4d98bab ("sunxi: enable CONFIG_BPF_SYSCALL and CONFIG_EMBEDDED"). Without this change BPF functionality would be crippled.

### Testing:
Build tested with the default `CONFIG_TARGET_oxnas_ox820_Default=y` config and verified changes in the kernel `.config` file before/after. Changes are straightforward and consistent across other platforms, but as I don't own these platforms I'm unable to run-test.

### Distribution:
@hauke previously fixed the issue for `sunxi`.
@linusw regularly updates `gemini`.
@dangowrt made prior commits for `oxnas`, and I recall @RussellSenior also owns one of those devices.
@CHKDSK88 and @adschm have both commited updates for `layerscape`.

Thanks for your review and feedback!

**_NOTE: These changes also apply to the 21.02 release and should be backported._**

### CODE REVIEW

**Comment by guidosarducci** [comment]
@adschm Could you please add tags for "kernel" and the targets "gemini", "layerscape", and "oxnas"? Thanks.

**Comment by guidosarducci** [comment]
Pinging a few more people with relevant target experience to broaden the pool for review: @yangbolu1991 @xback @kaloz @juhosg @blogic @nbd168 @ldir-EDB0 . Thanks all.

**Comment by ldir-EDB0** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ldir.git

**Comment by guidosarducci** [comment]
Thanks, Kevin!

**Comment by adschm** [comment]
@guidosarducci Please don't use multiple packages or targets for the commit title prefix.
Either create one patch per target/package, or use a more generic prefix if it's absolutely necessary (this would typically be "treewide:" or "kernel:").

**Pull request closed without merging**
