### PR TITLE
kernel: bump version 5.10 to 5.10.18

### PR DESCRIPTION
**Pull request by anomeome**
update kernel 5.10 to version 5.10.18, refresh current patchset

Signed-off-by: Kabuli Chana <newtownBuild@gmail.com>

### CODE REVIEW

**Comment by adschm** [comment]
Any manual adjustments? Tests?

**Comment by anomeome** [comment]
No to both. I have been building / running with the mvebu patchset (which you just pushed), so did not bother noting it here.

**Comment by 1Jeff1** [comment]
Compile-tested for: ath79, GL.iNet GL-AR750S
Run-tested on: ath79, GL.iNet GL-AR750S

**Comment by adschm** [comment]
Thanks, merged after another refresh.

**Pull request closed without merging**
