### PR TITLE
treewide: use APK compatible version schema

### PR DESCRIPTION
**Pull request by aparcar**
Different from OPKG, APK uses a deterministic version schema which chips the version into chunks and compares them individually. This enforces a certain schema which was previously entirely flexible.

 - Releases are added at the very and end prefixed with an `r` like `1.2.3-r3`.
- Hashes are prefixed with a `~` like `1.2.3~abc123`.
- Dates become semantic versions, like `2024.04.01`
- Extra tags are possible like `_git`, `_alpha` and more.

For full details see the APK test list:
https://gitlab.alpinelinux.org/alpine/apk-tools/-/blob/master/test/version.data

Further problematic versions:

- [ ] adb - android.5.0.2_r1-r3
- [ ] adb-enablemodem - 2017-03-05-r1
- [ ] apex - 1.6.10-openwrt-r1
- [ ] at91bootstrap-at91sam9x5eknf_uboot - v4.0.3-r2
- [ ] at91bootstrap-at91sam9x5eksd_uboot - v4.0.3-r2
- [ ] at91bootstrap-sam9x60eknf_uboot - v4.0.3-r2
- [ ] at91bootstrap-sam9x60eksd_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d27_som1_ekqspi_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d27_som1_eksd_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d27_wlsom1_ekdf_qspi_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d27_wlsom1_eksd_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d2_icpdf_qspi_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d2_icpsd_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d2_ptc_eknf_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d2_ptc_eksd_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d2_xplaineddf_qspi_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d2_xplaineddf_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d2_xplainedsd_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d3_xplainednf_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d3_xplainedsd_uboot - v4.0.3-r2
- [ ] at91bootstrap-sama5d4_xplaineddf_uboot_secure - v4.0.3-r2
- [ ] at91bootstrap-sama5d4_xplainednf_uboot_secure - v4.0.3-r2
- [ ] at91bootstrap-sama5d4_xplainedsd_uboot_secure - v4.0.3-r2
- [ ] at91bootstrap-sama7g5eksd_uboot - v4.0.3-r2
- [ ] bcm27xx-gpu-fw - 2024-01-11-r0968de28716a9b1f106b8492646d0ed0a2800152
- [ ] bcm27xx-utils - 2024-01-18-r1
- [ ] ct-bugcheck - 2016-07-21
- [ ] cypress-firmware-43012-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-43340-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-43362-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-4339-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-43430-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-43439-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-43455-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-4354-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-4356-pcie - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-4356-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-43570-pcie - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-4373-pcie - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-4373-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-4373-usb - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-54591-pcie - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-54591-sdio - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-55560-pcie - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-55572-pcie - 5.10.9-2022_0909-r1
- [ ] cypress-firmware-55572-sdio - 5.10.9-2022_0909-r1
- [ ] dsl-vrx200-firmware-xdsl-a - 05.08.01.08.01.06_05.08.00.0B.01.01_osc-r1
- [ ] dsl-vrx200-firmware-xdsl-a-patch - 05.08.01.08.01.06_05.08.00.0B.01.01_osc-r1
- [ ] dsl-vrx200-firmware-xdsl-b - 05.08.01.08.01.06_05.08.00.0B.01.01_osc-r1
- [ ] dsl-vrx200-firmware-xdsl-b-patch - 05.08.01.08.01.06_05.08.00.0B.01.01_osc-r1
- [ ] layerscape-fman - lf-6.1.1-1.0.0-r1
- [ ] layerscape-ppfe - lf-6.1.1-1.0.0-r1
- [ ] layerscape-rcw - lf-6.1.1-1.0.0-r1
- [ ] libdb47 - 4.7.25.4.NC-r7
- [ ] libdb47xx - 4.7.25.4.NC-r7
- [ ] libedit - 20230828-3.1-r1
- [ ] libwolfssl - 5.6.6-stable-r1
- [ ] libwolfssl-benchmark - 5.6.6-stable-r1
- [ ] libwolfsslcpu-crypto - 5.6.6-stable-r1
- [ ] mt7623n-preloader - 2020-03-11-rb27114e184449a33b5d875fda14198f5e6fee2bb
- [ ] opensbi_generic - 2022.12.24~6b5188ca14e59ce7bf71afe4e7d3d557c3d31bf8-r1.2
- [ ] trace-cmd - v3.2-r1
- [ ] trace-cmd-extra - v3.2-r1
- [ ] trusted-firmware-a-ls1012a-frdm - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1012a-frwy-sdboot - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1012a-rdb - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1028a-rdb - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1028a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1043a-rdb - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1043a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1046a-frwy - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1046a-frwy-sdboot - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1046a-rdb - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1046a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1088a-rdb - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls1088a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-ls2088a-rdb - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-lx2160a-rdb - lf-6.1.1-1.0.0-r1
- [ ] trusted-firmware-a-lx2160a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-at91sam9m10g45ek_nandflash - linux4sam-2022.04-r3
- [ ] u-boot-at91sam9x5ek_mmc - linux4sam-2022.04-r3
- [ ] u-boot-at91sam9x5ek_nandflash - linux4sam-2022.04-r3
- [ ] u-boot-fsl_ls1012a-frdm - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1012a-frwy-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1012a-rdb - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1021a-iot-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1021a-twr - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1021a-twr-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1028a-rdb - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1028a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1043a-rdb - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1043a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1046a-frwy - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1046a-frwy-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1046a-rdb - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1046a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1088a-rdb - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls1088a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_ls2088a-rdb - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_lx2160a-rdb - lf-6.1.1-1.0.0-r1
- [ ] u-boot-fsl_lx2160a-rdb-sdboot - lf-6.1.1-1.0.0-r1
- [ ] u-boot-sam9x60ek_mmc - linux4sam-2022.04-r3
- [ ] u-boot-sam9x60ek_nandflash - linux4sam-2022.04-r3
- [ ] u-boot-sama5d27_som1_ek_mmc - linux4sam-2022.04-r3
- [ ] u-boot-sama5d27_som1_ek_qspiflash - linux4sam-2022.04-r3
- [ ] u-boot-sama5d27_wlsom1_ek_mmc - linux4sam-2022.04-r3
- [ ] u-boot-sama5d27_wlsom1_ek_qspiflash - linux4sam-2022.04-r3
- [ ] u-boot-sama5d2_icp_mmc - linux4sam-2022.04-r3
- [ ] u-boot-sama5d2_ptc_ek_mmc - linux4sam-2022.04-r3
- [ ] u-boot-sama5d2_ptc_ek_nandflash - linux4sam-2022.04-r3
- [ ] u-boot-sama5d2_xplained_mmc - linux4sam-2022.04-r3
- [ ] u-boot-sama5d2_xplained_spiflash - linux4sam-2022.04-r3
- [ ] u-boot-sama5d3_xplained_mmc - linux4sam-2022.04-r3
- [ ] u-boot-sama5d3_xplained_nandflash - linux4sam-2022.04-r3
- [ ] u-boot-sama5d4_xplained_mmc - linux4sam-2022.04-r3
- [ ] u-boot-sama5d4_xplained_nandflash - linux4sam-2022.04-r3
- [ ] u-boot-sama5d4_xplained_spiflash - linux4sam-2022.04-r3
- [ ] u-boot-sama7g5ek_mmc1 - linux4sam-2022.04-r3

### CODE REVIEW

**Comment by systemcrash** [comment]
I like this versioning. The best part for me is the explode into subparts for individual comparison - it's not infrequent that one needs to do this in shell somewhere.

**Comment by aparcar** [comment]
Merged. I'll fix the remaining versions before proceeding with merging APK.

**Comment by CHKDSK88** [comment]
@aparcar 
Please look packages in #14997 They should be non-problematic after PR merge.

**Comment by hmh** [comment]
Apparently APK does not have a major version override escape hatch (such as DPKG "epochs").

This means that, if you do not want to have an extremely ugly openwrt-package version string should upstream decide to go from semantic to date-based or the opposite (I've seen it happen several times over the last two decades working on Debian packages,), it would be a good idea to prefix date-based versions with "0." when first introducing them.

In fact, prefixing date-based versions with a major numeric version (like "0." or "1.") is a recommended practice even in Debian/Ubuntu when dealing with date-based versioning, because we try to avoid using epochs as much as possible there, too.

So, you'd do 0.2024.03.03-r1, instead of 2024.03.03-r1.

**Comment by hmh** [comment]
Hash-based versioning in APK, from what I can see in their version.data testsuite, is just a string match (i.e. the same as in opkg, dpkg/apt, rpm...).   APK will have to sort the hashes somehow, and that sorting is just as likely to match the reality of which version is earlier than the other, as it is likely to get it wrong.

If you envision that you might need to publish two *different* hash-based releases that have the same semantic version, you will need to extend the semantic version with an extra "sub version" that can properly order the hashes.

**Pull request closed without merging**
