### PR TITLE
tools/genext2fs: update genext2fs

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Update to latest version.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@linusw Can you test on D-Link DNS-313?

**Comment by linusw** [comment]
I'm sorry I don't see these github notifications much :(
I have however re-imaged the DNS-313 after this merge so I'd say it works fine!

**Comment by PolynomialDivision** [comment]
Nice! Thanks for testing! :)

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in f21394c4d11bf5c773c4f7bd5a115977ddeb3e98 and b6d29af9475f162b7258695299c2e95ce55c0b7c.

**Pull request closed without merging**
