### PR TITLE
add Cisco ON100 (Marvell Kirkwood)

### PR DESCRIPTION
**Pull request by a-a**
The Cisco ON100 device is a Kirkwood based router:

- SoC: Marvell 88F6282 1600Mhz
- SDRAM memory: 512MB DDR3 1333Mhz
- Gigabit ethernet: 2x Marvell 88E1310 (over RGMII)
- Flash memory: 512MB
- 2 Status LED (green/red, only one LED seems to be exposed via GPIO though)
- 1 Reset button
- 1 USB 2.0 port (on back)

This commit adds a target profile of "Cisco Systems ON100" under the target system "Marvell Kirkwood".

The stock u-boot can read ubi and supports booting via tftp, once "dhcp" command issued and device has a valid lease with tftp options set, flashing is performed as follows:

tftpboot ${loadaddr} openwrt-kirkwood-ciscoon100-uImage ; nand erase 0x200000 0x600000 ; nand write ${loadaddr} 0x200000 0x600000
nand erase 0x700000 0x1f900000
tftpboot ${loadaddr} openwrt-kirkwood-ciscoon100-rootfs.ubi ; nand erase 0x700000 ${filesize} ; nand write ${loadaddr} 0x700000 ${filesize}

OpenWRT is now flashed, but some configuration of environment variables is required:

setenv owrt_bootargs_root ubi.mtd=2 root=/dev/mtdblock2 rootfstype=jffs2 rw
setenv owrt_mtdparts mtdparts=nand_mtd:0x200000@0x0(u-boot),0x400000@0x200000(uImage),-@0x700000(data)
setenv owrt_boot nand read.e \${loadaddr} 0x200000 0x200000 \; setenv bootargs \$(console) \$(owrt_mtdparts) \${owrt_bootargs_root} \; bootm \${loadaddr}
setenv bootcmd run owrt_boot
saveenv

If u-boot has been replaced (there may not seem to be a need to do this, the stock u-boot seemed to work fine on my target), you may wish to confirm mac addresses are still present with printenv. If they are not present or incorrect, write your MAC addresses back with the following (use your MACs as per the label on your device, instead of the example)

setenv ethaddr 64:00:F1:00:00:00
setenv eth1addr 64:00:F1:00:00:01
saveenv

### CODE REVIEW

**Comment by a-a** [comment]
CI failing because libzlo source looks to be down and this version not mirrored by OpenWRT.

--2017-05-22 15:04:14--  http://www.oberhumer.com/opensource/lzo/download/lzo-2.09.tar.gz
Resolving www.oberhumer.com (www.oberhumer.com)... failed: Name or service not known.

**Comment by j4nkr** [comment]
You have to change the download path in the lzo makefile at package/libs/lzo/ to somethinge like

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
**PKG_SOURCE_URL:=http://download.openpkg.org/components/cache/lzo/
PKG_MD5SUM:=c7ffc9a103afe2d1bba0b015e7aa887f**

**Comment by a-a** [comment]
ah, thanks - i'd done something before using some other url I'd found, but it involved downgrading to 2.08 as wherever i'd found a stash of packages, 2.09 wasn't cached. i didn't commit it as it felt too hacky, but this looks better, so it should hopefully work now. thanks again.

**Comment by nmaas87** [comment]
Just tested it with the trunk version and works perfectly. Please merge this PR :)

````
BusyBox v1.24.2 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 DESIGNATED DRIVER (Bleeding Edge, 12009)
 -----------------------------------------------------
  * 2 oz. Orange Juice         Combine all juices in a
  * 2 oz. Pineapple Juice      tall glass filled with
  * 2 oz. Grapefruit Juice     ice, stir well.
  * 2 oz. Cranberry Juice
 -----------------------------------------------------
root@OpenWrt:/#
````

**Pull request closed without merging**
