### PR TITLE
kernel: bump 5.10 to 5.10.149

### PR DESCRIPTION
**Pull request by graysky2**
No patches required modification.

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by hauke** [comment]
OpenWrt does not use the wifi subsystem from the kernel, but form backports. The listed CVEs were already fixed in 26f400210d6b3780fcc0deb89b9741837df9c8b8.

**Comment by graysky2** [comment]
@hauke - I included that info in the commit message based on @BKPepe's comment [here](https://github.com/openwrt/openwrt/pull/10945#issuecomment-1279711289)

**Comment by BKPepe** [comment]
Yup, I requested it despite that I know that it uses Wi-Fi subsystem from backports, but still, I think that those CVEs should be mention in the commit message as it is taken from release notes. We can add one or two sentences that it was already fixed in backports to make everyone happy. :)

**Comment by hauke** [comment]
The linked commit already mentions the CVEs, they will also show up in the release notes. We just tagged new releases because of this problem.

**Pull request closed without merging**
