### PR TITLE
bcm47xx: add kernel 6.6

### PR DESCRIPTION
**Pull request by namiltd**
Adding kernel 6.6 as test kernel for bcm47xx.

### CODE REVIEW

**Comment by namiltd** [comment]
@rmilecki Can you take a look at this PR?

**Comment by namiltd** [comment]
Is there a chance for approval before the kernel is updated to 6.6.24 (released today) and we have to adapt the patches again?

**Comment by robimarko** [comment]
It would help if there were some Tested-by tags, as I dont know anything about this arch

**Comment by Mile-Lile** [comment]
I have r6250 and r8000 and serial on both units... if it helps I can test it... I don't know anything about compiling so if someone can provide me .chk for these units I can test them... if that woks that way at all...

**Comment by namiltd** [comment]
@Mile-Lile What exactly routers do you have (manufacturer/type)?

**Comment by Mile-Lile** [comment]
@namiltd 
Netgear r6250 and R8000... platform is bcm53xx generic on wiki

**Comment by Mile-Lile** [comment]
@namiltd 
packages needed for r8000

`base-files brcmfmac-firmware-43602a1-pcie busybox ca-bundle dnsmasq dropbear firewall4 fstools iwinfo kmod-brcmfmac kmod-gpio-button-hotplug kmod-leds-gpio kmod-nft-offload kmod-phy-bcm-ns-usb2 kmod-phy-bcm-ns-usb3 kmod-usb-ledtrig-usbport kmod-usb-ohci kmod-usb2 kmod-usb3 libc libgcc libustream-mbedtls logd luci mtd netifd nftables nvram odhcp6c odhcpd-ipv6only opkg osafeloader oseama otrx ppp ppp-mod-pppoe procd procd-seccomp procd-ujail uci uclient-fetch urandom-seed urngd wpad-basic-mbedtls`


for r6250

`base-files busybox ca-bundle dnsmasq dropbear firewall4 fstools iwinfo kmod-b43 kmod-gpio-button-hotplug kmod-leds-gpio kmod-nft-offload kmod-phy-bcm-ns-usb2 kmod-phy-bcm-ns-usb3 kmod-usb-ledtrig-usbport kmod-usb-ohci kmod-usb2 kmod-usb3 libc libgcc libustream-mbedtls logd luci mtd netifd nftables nvram odhcp6c odhcpd-ipv6only opkg osafeloader oseama otrx ppp ppp-mod-pppoe procd procd-seccomp procd-ujail uci uclient-fetch urandom-seed urngd wpad-basic-mbedtls`

**Comment by rmilecki** [comment]
@namiltd did you actually test it on any device?

@Mile-Lile: that is completely different target and architecture!

I really don't like those hacky commits. First moving patches that breaks 6.1. Then restoring them. Then removing patches that were just moved. Seriously we bring mess to our git history to satisfy somone who refuses to use an extra switch in `git log`.

**Comment by Mile-Lile** [comment]
> @Mile-Lile: that is completely different target and architecture!

oops... I apologize... won't bump anymore I promisse :)

**Comment by namiltd** [comment]
I only dealt with the software part and I'm waiting for hardware testers.

**Comment by namiltd** [comment]
@Mile-Lile There is so much work to do with the project that any help will be useful. For example, you can help with https://github.com/openwrt/openwrt/pull/15042 tests.

**Comment by namiltd** [comment]
I have compiled a version with kernel 6.6 for Netgear r8000 
[openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk.zip](https://github.com/openwrt/openwrt/files/14889707/openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk.zip), test it if you can and post the results in the thread https://github.com/openwrt/openwrt/pull/15042

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
