### PR TITLE
mvebu: cortexa72: enable ARM_ARMADA_8K_CPUFREQ

### PR DESCRIPTION
**Pull request by clayface**
Enable the AP806's cpufreq driver. This driver is compatible with the
Armada 7K and 8K platforms.

Tested on Mikrotik RB5009.

Signed-off-by: Matthew Hagan <mnhagan88@gmail.com>

### CODE REVIEW

**Comment by Borromini** [comment]
@clayface Any way to test this? E.g. any files in /sys I should check for frequency values?

**Comment by clayface** [comment]
Yes, thanks for testing. `/sys/devices/system/cpu/cpu(0-3)/cpufreq/` should be populated, eg 
`cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq` should output all current freuqencies. collectd/rrdtool should be funtional with the cpu frequency plugin as well.

**Comment by Borromini** [comment]
Thanks. Without your patch, there's no `/sys/devices/system/cpu/cpu[0-3]/cpufreq/` nor is there anything in `/sys/devices/system/cpu/cpufreq/`. With your patch there is indeed:
```
# cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq
700000
700000
350000
350000
```

Tested on MikroTik RB5009UG+S+IN.

Tested-by: Stijn Segers <foss@volatilesystems.org>

**Comment by robimarko** [comment]
LGTM, most likely an oversight so far.

Reviewed-by: Robert Marko <robimarko@gmail.com>

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
