### PR TITLE
ramips: set REQUIRE_IMAGE_METADATA=1 on boards

### PR DESCRIPTION
**Pull request by ptpt52**
for these board we must set REQUIRE_IMAGE_METADATA=1 to make sure upgrade checking

### CODE REVIEW

**Comment by mkresin** [comment]
We can't enforce image metadata as long as we have boards still using the old image build code, which doesn't add the image metadata. The boards in https://github.com/openwrt/openwrt/blob/master/target/linux/ramips/image/rt305x-legacy.mk  need to be converted to new image build code first.

> for these board we must set REQUIRE_IMAGE_METADATA=1 to make sure upgrade checking

Even without `REQUIRE_IMAGE_METADATA=1` metadata are validated if present. It is just that images without the metadata are accepted as well.

**Comment by ptpt52** [comment]
@mkresin 
nop
I think you misunderstood

I think these boards are sure new image with metadata

if you don't do a metadata validation, it will cause the device  bricked if someone Upgrade with a wrong file via web luci

This can cause serious problems

My patch just  enable force REQUIRE_IMAGE_METADATA for those boards

**Comment by ptpt52** [comment]
for R6220 MIR3G
a wrong file upgrade via luci web will cause the device brick

I have already tested it
because without the metadata checking, it just perform the UPGRADE actions, which remove the rootfs, wipe data, and then upgrade failed with a wrong file.

This kind of thing is very easy to happen on the client side, with disastrous consequences

**Comment by mkresin** [comment]
Indeed, I got it wrong. But I'm quite sure it will not work anyway.

The `REQUIRE_IMAGE_METADATA` is evaluated before `platform_do_upgrade` is called. As far as I can see the order of commands run is the following (`package/base-files/files/sbin/sysupgrade`):

1. set up image checks commands: `sysupgrade_image_check="fwtool_check_image platform_check_image"`.
2. run `sysupgrade_image_check` (`fwtool_check_image()` will evaluate `REQUIRE_IMAGE_METADATA`)
3. run `do_upgrade_stage2` (`package/base-files/files/lib/upgrade/common.sh`) which will start `platform_do_upgrade()` 

Hence the REQUIRE_IMAGE_METADATA is run to late.

**Comment by mkresin** [comment]
>  a wrong file upgrade via luci web will cause the device brick

If a wrong file is an image without metadata you are right. If it is an image with not matching metadata, the image should be rejected:

```
root@LEDE:/# sysupgrade /tmp/openwrt-ramips-mt7620-kn_rc-squashfs-sysupgrade.bin
 
Device alfa-network,ac1200rm not supported by this image
Supported devices: kn_rc
Image check 'fwtool_check_image' failed.
```

**Comment by ptpt52** [comment]
@mkresin yep, it is file without metadata. something like xxx.tar

**Comment by mkresin** [comment]
The easiest way to add some kind of validation is to add a `nand_do_platform_check()` call to `platform_check_image()` for your board.

But now that I got what you are trying, I've to admit that I kind of like your idea. But it need to be done in a different way.

What about doing something like the following:

1. change the order of the `sysupgrade_image_check` commands to run `platform_check_image` first and `fwtool_check_image` as last command
2. change `platform_check_image()` to set `REQUIRE_IMAGE_METADATA=1` for all boards by default
3. add an exception for boards still using the old/legacy image build code

```
platform_check_image() {
	local board=$(board_name)
	local magic="$(get_magic_long "$1")"

	case "$board" in
	all0239-3g|\
	dcs-930|\
	dcs-930l-b1|\
	wl-341v3|\
	whr-g300n)
		[ "$magic" != "27051956" ] && {
			echo "Invalid image type."
			return 1
		}
		;;
	*)
		REQUIRE_IMAGE_METADATA=1
		;;
	esac

	return 0
}
```

**Comment by ptpt52** [comment]
LGTM

**Comment by mkresin** [comment]
Nope, will not work. The `$check "$IMAGE"` in 

```
for check in $sysupgrade_image_check; do                                                          
        echo "REQUIRE_IMAGE_METADATA: $REQUIRE_IMAGE_METADATA"                                    
                                                                                                  
        ( $check "$IMAGE" ) || {                                                                  
                if [ $FORCE -eq 1 ]; then                                                         
                        echo "Image check '$check' failed but --force given - will update anyway!"
                        break                                                    
                else                                                             
                        echo "Image check '$check' failed."                                  
                        exit 1                                                   
                fi                                                               
        }                                                        
done 
```

runs in a subshell. Means, it isn't possible to pass any change to REQUIRE_IMAGE_METADATA back. And I'm quite sure it runs in a subshell for a reason.

Your only options left are:

1. migrate the remaining boards to the "new" image build code and set REQUIRE_IMAGE_METADATA=1
2. use nand_do_platform_check with a fixed boardname

**Comment by ptpt52** [comment]
so
for now my patch still the best solution?
it fix for these boards:
hc5962
mir3g
r6220
ubnt-erx
ubnt-erx-sfp

and they are sure the 'new' image build code.

**Comment by mkresin** [comment]
I don't understand what you are trying to say.

But your patch will not work. As I already mentioned in https://github.com/openwrt/openwrt/pull/637#issuecomment-356829506, the image checks are already done before your added REQUIRE_IMAGE_METADATA is evaluated. It never worked.

Your only options left are still:

1. migrate the remaining boards to the "new" image build code and set REQUIRE_IMAGE_METADATA=1
2. use nand_do_platform_check with a fixed boardname

**Comment by ptpt52** [comment]
I got the solution,
what about this patch:

`
diff --git a/target/linux/ramips/base-files/lib/upgrade/platform.sh b/target/linux/ramips/base-files/lib/upgrade/platform.sh
index 8160f5d..a30eafc 100755
--- a/target/linux/ramips/base-files/lib/upgrade/platform.sh
+++ b/target/linux/ramips/base-files/lib/upgrade/platform.sh
@@ -261,12 +261,6 @@ platform_check_image() {
                }
                return 0
                ;;
-       hc5962|\
-       mir3g|\
-       r6220)
-               # these boards use metadata images
-               return 0
-               ;;
        re350-v1)
                [ "$magic" != "01000000" ] && {
                        echo "Invalid image type."
@@ -274,6 +268,9 @@ platform_check_image() {
                }
                return 0
                ;;
+       hc5962|\
+       mir3g|\
+       r6220|\
        ubnt-erx|\
        ubnt-erx-sfp)
                nand_do_platform_check "$board" "$1"


`

**Pull request closed without merging**
