### PR TITLE
[RFT] kernel: bump 5.4 to 5.4.59 and clean up patches

### PR DESCRIPTION
**Pull request by adschm**
kernel: bump 5.4 to 5.4.59

    Removed since added upstream:
      bcm27xx:
        950-0428-staging-vchiq_arm-Add-a-matching-unregister-call.patch

    Manually adjusted patches:
      layerscape:
        801-audio-0005-Revert-ASoC-fsl_sai-Add-support-for-SAI-new-version.patch

    Build-tested: none yet
    Run-tested: none yet

---

    layerscape: remove useless pairs of kernel patches

    The layerscape kernel patches appears to be just some uncleaned local
    development tree, where patches are sometimes directly followed by
    their revert. While this does not seem a problem in the first place,
    it becomes incredibly unpleasant when kernel patches appear in the
    relevant areas.

    This removes all these patch-revert pairs and refreshs the rest.

    It removes about 44000 lines of entirely useless code.

---

    bcm27xx: remove no-op patch pair

    Patch 1 introduces a change, and patch 2 reverts it again. Remove
    both patches and achieve the same outcome.

    Refreshed patches for the target as well.

### CODE REVIEW

**Comment by adschm** [comment]
@graysky2 FYI.

**Comment by CHKDSK88** [comment]
@yangbolu1991
FYI

**Comment by anomeome** [comment]
compile / test - mvebu / mamba, rango

**Comment by 1Jeff1** [comment]
```
Build-tested: rockchip
Run-tested: rockpro64
```

**Comment by graysky2** [comment]
@adschm - Nice thanks!  I got stuck in those layerscape patches (TONS of them)!

Build-tested: x86_64
Run-tested: ipq806x (R7800)/no dmesg regressions/seems fully functional

**Comment by CHKDSK88** [comment]
I tested on layerscape ane can't see any issues or dmesg regresions.

Build-tested: layerscape(∗)
Run-tested: LS1012A-FRDM(∗), LS1046A-RDB(∗)

Tested-by: Pawel Dembicki <paweldembicki@gmail.com>

(∗) Used workaround from  #3179 to compile.

**Comment by zuzia-dev** [comment]
Build-tested: lantiq (xrx200), ok.

**Comment by adschm** [comment]
Merged.

**Comment by yangbolu1991** [comment]
I'm sorry for the layerscape build issue. 
I just generate a fix-up instead of https://github.com/openwrt/openwrt/pull/3179.
https://github.com/openwrt/openwrt/pull/3322

Thanks.

**Pull request closed without merging**
