### PR TITLE
uboot: mvebu: Minor version update and GCC 10+ fix

### PR DESCRIPTION
**Pull request by DeathCamel58**
Updated U-Boot to 2019.01.
Fixed GCC version 10+ compiles.

Tested on Linksys WRT1900AC

Signed-off-by: Dylan Corrales <deathcamel58@gmail.com>

### CODE REVIEW

**Comment by aparcar** [comment]
Do you really need this version bump for 19.07?

**Comment by DeathCamel58** [comment]
The current version in 19.07 doesn't compile on GCC version 10+. This can be seen in Fedora 34.
This is as far as I can bump the version before there are DTS issues for that device.

**Comment by aparcar** [comment]
@hauke do you think it makes sense to backport this now that 21.02 comes out in a bit?

**Comment by hauke** [comment]
OpenWrt 21.02 uses U-Boot 2021.01 for mvebu, this contains already these fixes. This is only relevant for OpenWrt 19.07.
https://github.com/u-boot/u-boot/commit/018921ee79d3f30893614b3b2b63b588d8544f73

I am fine with backporting the fix, but I do not like the upgrade of U.Boot to version 2019.01, could you stay at version 2018.03 for openwrt 19.07.

**Comment by adschm** [comment]
@DeathCamel58 Ping. Also note that the commit title prefix should be "uboot-mvebu:"

**Comment by hauke** [comment]
The mvebu U-Boot in OpenWrt 19.07 should build fine with gcc 10 since f31bb35b633cd7f0e81306823511b8f64c1f5983.

**Comment by hauke** [comment]
We assume this is fixed with  f31bb35.

**Pull request closed without merging**
