### PR TITLE
zynq: add sdcard image generation support

### PR DESCRIPTION
**Pull request by qinfengling**
- uboot-zynq: bump to 2016.07
- tools: build dosfstools and tools for zynq
- zynq: add sdcard image generation support

I have test image generation for zc702,zed and zybo, and test the firmware on zed.

@blogic @wigyori Could you help me review and  merge these changes ? Thanks.

### CODE REVIEW

**Comment by wigyori** [comment]
The patches make sense on the first look - I'll do a test build and get back to you. Can you add some docs for zynq on the wiki please? :)

Thanks,
-w-

**Comment by qinfengling** [comment]
Why not. I will try to write and update the zynq wiki in the next stage during the development.
Thanks for your quick response.

Can you tell me how to run test build? buildbot or shell script ?

**Comment by wigyori** [comment]
make[4]: Entering directory `/store/ftp/openwrt/zynq/openwrt/build_dir/target-arm_cortex-a9+neon_musl-1.1.14_eabi/u-boot-zc702/u-boot-2016.07'
  CHK     include/config/uboot.release
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/timestamp_autogenerated.h
  CHK     include/generated/generic-asm-offsets.h
  CHK     include/generated/asm-offsets.h
./scripts/dtc-version.sh: line 17: dtc: command not found
./scripts/dtc-version.sh: line 18: dtc: command not found
*** Your dtc is too old, please upgrade to dtc 1.4 or newer

Can you please check:

 - package/boot/uboot-sunxi/patches/001-use-dtc-in-kernel.patch
 - package/boot/uboot-sunxi/Makefile:

define Build/Compile
        $(MAKE) -C $(PKG_BUILD_DIR) \
                CROSS_COMPILE=$(TARGET_CROSS) \
                DTCDIR=$(LINUX_DIR)/scripts/dtc/
-----

Thanks,
-w-

**Comment by qinfengling** [comment]
I install device-tree-compiler on my Debian server before.
I will fix with another commit like uboot-sunxi.

**Comment by wigyori** [comment]
Builds like a charm, thanks. :)

For build testing, usually selecting your target, and selecting "Global build settings / Select all kernel/userspace packages" will tell if any package is broken.

Thanks,
-w-

**Pull request merged**
