### PR TITLE
igmpproxy: drop SSDP packets

### PR DESCRIPTION
**Pull request by hanipouspilot**
It is insecure to let this type of packets inside
They can e.g. open ports on some other routers with UPnP, etc

Signed-off-by: Dmitry Tunin <hanipouspilot@gmail.com>

### CODE REVIEW

**Comment by hanipouspilot** [comment]
igmpproxy 0.2.1 ignores 239.255.255.250 anyway, so accepting them makes no sense and is insecure.
https://github.com/pali/igmpproxy/commit/b445adbcbfa4b716e673ed55bfe53afc2f26baa8

**Comment by diizzyy** [comment]
Bump PKG_RELEASE

**Comment by hanipouspilot** [comment]
@diizzyy Done. Rebased to a single commit.

**Comment by blogic** [comment]
merged, Thanks !

**Comment by hanipouspilot** [comment]
@blogic Why don't I see this commit in the tree?

**Comment by blogic** [comment]
try now ...

**Comment by hanipouspilot** [comment]
OK now, thanks.

**Pull request closed without merging**
