### PR TITLE
Add support for Mofi 5500

### PR DESCRIPTION
**Pull request by rickmacgillis**
Installation Instructions
-------------------------
1. Update Mofi 5500 to at least stock firmware version 4.8.6. (Available on the Mofi website.) Previous versions are untested in the upgrade process.
2. Log into the LuCI web interface, usually at 192.168.10.1 and visit the "System->Backup/Flash Firmware" page.
3. Upload and flash the firmware as usual.

### CODE REVIEW

**Comment by rickmacgillis** [comment]
I fixed the commit message for anyone who might have been waiting on that.

**Comment by musashino205** [comment]
Please read a guideline: https://openwrt.org/submitting-patches#submission_guidelines

And please don't close a previous PR to update the commits:
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes#do_not_multi-post_or_re-post_prs

**Comment by rickmacgillis** [comment]
@musashino205 please be more specific about what you're disputing.

**Comment by musashino205** [comment]
https://openwrt.org/submitting-patches#submission_guidelines

> - **commit subject**
>   - must have a prefix that depends from what you are doing in the commit
>     - device architecture: for devices (for example, **mvebu:** or **ramips: add support to example_eval board** )
>
> - **commit description**
>   - must have less than 75 characters per line
>   - If you add support for new hardware: Include in your commit message a short description of the hardware and how to install OpenWrt on it. Have a look at the [recent additions](https://git.openwrt.org/?p=openwrt/openwrt.git&a=search&h=HEAD&st=commit&s=add+support+for) for some examples.

When updating commits, please use ```git rebase -i``` (and set ```squash``` or ```s``` to squashed commits) and ```git push -f``` instead of creating a new branch or repository.

**Comment by rickmacgillis** [comment]
Updated.

**Comment by rickmacgillis** [comment]
Hi guys. Can we get this approved today?

**Pull request closed without merging**
