### PR TITLE
For fritzbox7490

### PR DESCRIPTION
**Pull request by hvegh**
Consolidated efforts to get support for the xx90 line of Fritz devices.

### CODE REVIEW

**Comment by adschm** [comment]
This has severe formal issues. Please visit https://openwrt.org/submitting-patches another time.

Additional hints:
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes
https://openwrt.org/docs/guide-developer/device-support-policies

**Comment by hvegh** [comment]
> This has severe formal issues. Please visit https://openwrt.org/submitting-patches another time.
> 
> Additional hints:
> https://openwrt.org/docs/guide-developer/frequent-pr-mistakes
> https://openwrt.org/docs/guide-developer/device-support-policies

Yes I know, this is to big a change set to get commited also there are patches that do not belong in mainline.

We should organize an OpenWRT summit, or OpenWRT hackathon with a few maintainers.   
Any sponsors are welcome. 

Beginning next month I am in Hamburg - Germany with sufficient space to host this...
If needed feel free to drop by for a beer...

**Comment by hvegh** [comment]
Tested this pull/patch set id for reference only...

**Comment by adschm** [comment]
Pull Request are supposed to be stuff that is ready for review and can be merged.

Please don't use them for "just see[ing] the diffs", at least not in the official repository.

If you look for support in development, please check out our forum.

**Pull request closed without merging**
