### PR TITLE
realtek: switch to Kernel 5.15 by default

### PR DESCRIPTION
**Pull request by aparcar**
This PR to have an overview of testing.

### CODE REVIEW

**Comment by castillofrancodamian** [comment]
Wrong title.

**Comment by aparcar** [comment]
Wrong file pushed, thanks for checking.

**Comment by Borromini** [comment]
To my layman's eyes, this target is ready for 5.15. @svanheule @musashino205 @oliv3r Your take?

Run-tested on: Netgear GS108T v3, ZyXEL GS1900-8HP v1 (both rtl838x).

**Comment by svanheule** [comment]
FWIW
```Tested-by: Sander Vanheule <sander@svanheule.net>```

I have the impression most people building their own images for this target already prefer 5.15 at the moment. I don't think there were any recent issues with this kernel version (but I was out for a month), so I'm fine with changing it to be the default

**Comment by oliv3r** [comment]
I wonder how many people are actually doing much with openwrt :)

But you have my blessing for sure.

`Tested-by: Olliver Schinagl <oliver@schinagl.nl>`

**Comment by musashino205** [comment]
Sorry for late response.
I tested booting and basic functions on my devices:

- APRESIA ApresiaLightGS120GT-SS (RTL8382M)
- Panasonic Switch-M48eG PN28480K (RTL8393M)

```Tested-by: INAGAKI Hiroshi <musashino.open@gmail.com```

**Pull request merged**
