### PR TITLE
ath79: add HS UART to QCA955x and enable on ELECOM WAB-I1750-PS

### PR DESCRIPTION
**Pull request by musashino205**
This patch series adds HighSpeed UART support to QCA955x SoCs and enables it on ELECOM WAB-I1750-PS.

### CODE REVIEW

**Comment by musashino205** [comment]
UPDATE:

- add missing commit to drop unnecessary ```&uart``` node from dtsi of WAB series.

**Comment by musashino205** [comment]
UPDATE:

- drop ```&uart``` from Meraki MR18 too

**Comment by Leo-PL** [comment]
This is a welcome change. As for MR18 and Routerboard 92x (and in general), looks good to me - however I can only assume the exact numbers for UART1 are OK ;-)

**Comment by musashino205** [comment]
UPDATE:

- register ttyATH1 as a secondary console on WAB-I1750-PS

**Comment by musashino205** [comment]
Oops, ttyS0 seems to be broken on failsafe mode by the latest patch... I'll drop the commit.

**Comment by musashino205** [comment]
Oops, ttyS0 seems to be broken on failsafe mode by the latest commit... I'll drop that.

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
