### PR TITLE
ipq806x: make low latency kernel a default

### PR DESCRIPTION
**Pull request by fantom-x**
The default non-preemptive (Server) kernel is not well sutable for
routers. The low-latency kernel helps address the high latency issue:
100ms pings over wired connection.

This kernel will not boot without PR #848 .

There is more discussion about this on the forum: 
https://forum.lede-project.org/t/possible-cause-of-r7800-latency-issues/12872

Compiled and tested on Netgear R7800
Signed-off-by: Marc Benoit <marcb62185@gmail.com>

### CODE REVIEW

**Comment by pepe2k** [comment]
`iqp806x` -> `ipq806x`

**Comment by fantom-x** [comment]
I corrected it in the PR title.

**Comment by pepe2k** [comment]
> I corrected it in the PR title.

You should fix it also in your commit title.

**Comment by fantom-x** [comment]
Done.

**Comment by neheb** [comment]
Something tells me this should be in generic instead.

There's been discussion before about making 1000Hz default but nobody seemed to come out with numbers showing a benefit.

**Comment by fantom-x** [comment]
Well, the impact might also be platform and use case specific. The Netgear R7800 seemed to be the most impacted and it makes sense to start with one and see how it impacts a broader user base. It is not just a timer change, but also a change from a non-preemptive kernel to a fully preeemptive one. According to the forum posts, some people have followed my suggestions and are already running both voluntary and fully preemptive kernels with very noticeable improvements to response time and latency. 

Also, Netgear R7800 did not even boot once I made this config change and required another fix.

**Comment by fantom-x** [comment]
About the numbers: my ping spikes decreased from 100+ms two or three times a minute down to 20..25ms and every several minutes once I started using a preemptive kernel.

**Comment by gnufsh** [comment]
I am testing this on the IPQ8065/R7800 and it seems to work fine.

**Comment by nbd168** [comment]
I think enabling preempt to get rid of the 100ms spikes is just papering over the real bug. It seems that the forum discussion was also pointing at the real bug, and I would like to see that fixed instead.
So NACK from me on this PR.

**Comment by huaracheguarache** [comment]
@nbd168 I agree with that it's not really fixing the issue, but rather working around it. The quick and dirty patch in the tread fixes the vast majority of the spikes. 

Also, is there a recommended pre-emption model for the kernel when using OpenWrt? I'm currently using voluntary pre-emption and things feel a lot more snappy and responsive when browsing the web.

**Comment by nbd168** [comment]
My reservation is the fact that these latency spikes are way too high. They should never happen happen under normal circumstances, even with preempt disabled. If we paper over them on ipq806x without properly fixing them, they might still be there on other platforms.
Also, with these issues fixed properly, preempt might reduce overall network throughput.

I've pushed a change to my staging tree which should help reduce ar8216 induced latency (even without disabling MIB counters), please test it with preempt disabled.
You can find it here: http://git.openwrt.org/02ce5e4e3d6a17b846c8254700ace7bb3fd985fa

**Comment by fantom-x** [comment]
The last two commits do eliminate the need for a preemptive kernel. Thank you.

**Pull request closed without merging**
