### PR TITLE
ramips: adjust LZMA_TEXT_START for 32MB RAM devices

### PR DESCRIPTION
**Pull request by mans0n**
Currently the lzma-loader is placed in RAM at 32MB offset, which does not
make sense for devices with only 32MB RAM. If we adjust LZMA_TEXT_START to
24MB offset, then the lzma-loader can be used on those devices and still
about 24MB memory will be available for uncompressed image, which should be
enough for most use cases.

And enable the loader on RT5350F-OLinuXino devices.

### CODE REVIEW

**Comment by mans0n** [comment]
I've check that the current snapshot image also does not boot on the devices.

**Comment by adrianschmutzler** [comment]
So, is this becoming relevant only now as we need to start using lzma-loader, or why hasn't this 32 MB RAM restriction been relevant earlier?

**Comment by mans0n** [comment]
Perhaps because there hasn't been any other 32MB device using lzma-loader? It seems currently only mt7621 devices are using the loader.

**Comment by xabolcs** [comment]
@mans0n please adjust PR title and description or remove commit 18b4217a092f52bf5e5a5ff4a838cd07a6a2e3ac from the branch!

**Comment by xabolcs** [comment]
`ath79` commit 071a6372762d289b2fa5a8d1a138eff944c93c9e of the same has other details too.
@mans0n could you comment about `TARGET_INITRAMFS_COMPRESSION_LZMA`? Because it's enabled in `ramips` target.

@adrianschmutzler is it overkill to keep the 32 MB as `LZMA_TEXT_START` default, and modify it only for 32 MB RAM devices?

[For example](https://github.com/arrmo/openwrt/commit/f4b44d45458ba38b0550060a9490d78ac51a1ea3#diff-078cf44df243ae35f6fa7395e9a95aba):
```diff
diff --git a/target/linux/ramips/image/Makefile b/target/linux/ramips/image/Makefile
index fcf20fd1c4a4..0ab748d3245b 100644
--- a/target/linux/ramips/image/Makefile
+++ b/target/linux/ramips/image/Makefile
@@ -7,7 +7,7 @@
 include $(TOPDIR)/rules.mk
 include $(INCLUDE_DIR)/image.mk
 
-DEVICE_VARS += LOADER_TYPE LOADER_FLASH_OFFS
+DEVICE_VARS += LOADER_TYPE LOADER_FLASH_OFFS LZMA_TEXT_START
 DEVICE_VARS += NETGEAR_BOARD_ID NETGEAR_HW_ID
 DEVICE_VARS += BUFFALO_TAG_PLATFORM BUFFALO_TAG_VERSION BUFFALO_TAG_MINOR
 DEVICE_VARS += SEAMA_SIGNATURE SEAMA_MTDBLOCK
@@ -23,6 +23,7 @@ ldrplatform-$(CONFIG_TARGET_ramips_mt7621) := mt7621
 
 KERNEL_LOADADDR := $(loadaddr-y)
 LOADER_PLATFORM := $(ldrplatform-y)
+LZMA_TEXT_START := 0x82000000
 
 KERNEL_DTB = kernel-bin | append-dtb | lzma
 
@@ -64,7 +65,7 @@ define Build/loader-common
 		PKG_BUILD_DIR="$@.src" \
 		TARGET_DIR="$(dir $@)" LOADER_NAME="$(notdir $@)" \
 		BOARD="$(BOARDNAME)" PLATFORM="$(LOADER_PLATFORM)" \
-		LZMA_TEXT_START=0x82000000 LOADADDR=$(KERNEL_LOADADDR) \
+		LZMA_TEXT_START=$(LZMA_TEXT_START) LOADADDR=$(KERNEL_LOADADDR) \
 		$(1) compile loader.$(LOADER_TYPE)
 	mv "$@.$(LOADER_TYPE)" "$@"
 	rm -rf $@.src
diff --git a/target/linux/ramips/image/mt7620.mk b/target/linux/ramips/image/mt7620.mk
index e35c46771242..cec891c02e41 100644
--- a/target/linux/ramips/image/mt7620.mk
+++ b/target/linux/ramips/image/mt7620.mk
@@ -908,14 +897,14 @@ define Device/ralink_mt7620a-v22sg-evb
 endef
 TARGET_DEVICES += ralink_mt7620a-v22sg-evb
 
-define Device/ravpower_wd03
+define Device/ravpower_rp-wd03
+  $(Device/sunvalley_filehub)
   SOC := mt7620n
-  IMAGE_SIZE := 7872k
-  DEVICE_VENDOR := Ravpower
-  DEVICE_MODEL := WD03
-  DEVICE_PACKAGES := kmod-usb2 kmod-usb-ohci
+  DEVICE_VENDOR := RAVPower
+  DEVICE_MODEL := RP-WD03
+  LZMA_TEXT_START := 0x81800000
 endef
-TARGET_DEVICES += ravpower_wd03
+TARGET_DEVICES += ravpower_rp-wd03
 
 define Device/sanlinking_d240
   SOC := mt7620a
```

**Comment by adrianschmutzler** [comment]
> @adrianschmutzler is it overkill to keep the 32 MB as `LZMA_TEXT_START` default, and modify it only for 32 MB RAM devices?

Well, the question is whether such a "more complicated" setup would be _necessary_.

**Comment by mans0n** [comment]
> could you comment about TARGET_INITRAMFS_COMPRESSION_LZMA?

I don't think the double compression would do much harm in this case. And I don't know how to disable initramfs compression only for some devices.

> is it overkill to keep the 32 MB as LZMA_TEXT_START default, and modify it only for 32 MB RAM devices?

I've also considered that, but I think 24MB is more than enough for all ramips devices. I'll have a test on a mt7621 device to be sure.

**Comment by adrianschmutzler** [comment]
> could you comment about TARGET_INITRAMFS_COMPRESSION_LZMA?

This one cannot be limited to devices, you can only get rid of the second "lzma" in device recipes. However, one could limit it to subtargets by using stuff like TARGET_ramips_mt76x8 as done for ath79/mikrotik

**Comment by xabolcs** [comment]
> Well, the question is whether such a "more complicated" setup would be _necessary_.

And which test should one run to answer that question?

I'm thinking about different sized kernels with different sized compressed uImages. Also with as `initramfs.bin` and `factory.bin`.

**Comment by mans0n** [comment]
My mt7621 device works well even with 16MB offset.
It seems we can't get rid of "the second lzma." lzma-loader needs it, and it does reduce the size of uncompressed image a lot.

**Comment by adrianschmutzler** [comment]
I'm fine with the 24 MB change, but I would remove the LZMA_TEXT_START from image/Makefile entirely and adjust the value directly in the lzma-loader files, just like I did it in
https://github.com/openwrt/openwrt/commit/071a6372762d289b2fa5a8d1a138eff944c93c9e

Of course, we have to keep KERNEL_LOADADDR here, and I'd be happy if you changed both values:
image/lzma-loader/Makefile
image/lzma-loader/src/Makefile

**Comment by mans0n** [comment]
I don't feel good about hard-coding an arbitrary value inside code I don't really know well... I'd prefer passing it as an argument.

At least I'd like to limit the scope of change, as I can't rule out the possibility that LZMA_TEXT_START will be changed again in the future. Just touching `image/lzma-loader/Makefile` would be enough, I think.

**Comment by adrianschmutzler** [comment]
> I don't feel good about hard-coding an arbitrary value inside code I don't really know well... I'd prefer passing it as an argument.
> 
> At least I'd like to limit the scope of change, as I can't rule out the possibility that LZMA_TEXT_START will be changed again in the future. Just touching `image/lzma-loader/Makefile` would be enough, I think.

My point is that actually the hardcoded value is something ancient copied over from somewhere else where is probably had been copy/pasted again beforehand ...

But okay, I will take your patch as-is, and then I still can think about moving it around myself or not ...

Apart from that: I assume you tested the second patch, so this is another datapoint where rt305x with kernel 5.4 is working?

**Comment by mans0n** [comment]
> Apart from that: I assume you tested the second patch, so this is another datapoint where rt305x with kernel 5.4 is working?

I found it first while testing v5.4, but the issue is also relevant to v4.14. A v5.4 kernel with ALL_KMODS disabled worked find without the second patch.

I'm not sure why there haven't been any other reports on rt305x, though.

**Comment by mans0n** [comment]
I've checked that the current 19.07.3 image works fine, and the current v5.4 snapshot image fails to boot.

**Comment by adrianschmutzler** [comment]
>  and the current v5.4 snapshot image fails to boot.

... but is fixed with the patch here?

**Comment by mans0n** [comment]
> > and the current v5.4 snapshot image fails to boot.
>
> ... but is fixed with the patch here?

Precisely.

**Comment by adrianschmutzler** [comment]
Okay, thanks, I will merge both patches tomorrow.

**Comment by adrianschmutzler** [comment]
@xabolcs If there appear problem at mt7621 or with other bigger images, we can revisit this and try your approach or a similar one.

**Comment by xabolcs** [comment]
> why hasn't this 32 MB RAM restriction been relevant earlier?

@adrianschmutzler: as @mans0n wrote: the LZMA Loader was used by devices with at least 64 MByte RAM only.

The RAVPower RP-WD03 `mt7620n` device in my previous diff is also affected by this `LZMA_TEXT_START` problem. But it (and all older RAVPower / HooToo travel routers) has other problems too: 1.5M kernel size limitation, wrong partition setup, ...

**Pull request closed without merging**
