### PR TITLE
dnsmasq: version 2.90 (CVE 2023-50387, CVE 2023-50868)

### PR DESCRIPTION
**Pull request by nwf**
@nbd168 Please review the changes to package/network/services/dnsmasq/patches/200-ubus_dns.patch .  I believe they are correct, but upstream's 12ddb2a4b9204846db7c38eefe4080d89dbed708 ("To implement this needed the DNS-doctor code to be untangled from find_soa()") imposed a little bit of work.

### CODE REVIEW

**Review by ynezz — COMMENTED** [review]
Thanks for taking care, BTW this update fixes CVE 2023-50868 as well, so it should be mentioned in the commit description as well.

**Comment by egc112** [comment]
I compiled with your patch for my DL-WRX36.
DNSMasq is running without a problem:
```
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: started, version 2.90 cachesize 1000
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: DNS service limited to local subnets
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset nftset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.91.100 -- 192.168.91.249, lease time 12h
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.9.128 -- 192.168.9.191, lease time 12h
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for test
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for local
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: reading /tmp/resolv.conf.d/resolv.conf.auto
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using nameserver 9.9.9.9#53
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using nameserver 1.0.0.1#53
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using nameserver 2620:fe::10#53
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using nameserver 2606:4700:4700::1001#53
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for test
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for local
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: read /etc/hosts - 12 names
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 6 names
Mon Feb 19 17:10:56 2024 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
```
Do you want me to test anything else

**Review by egc112 — APPROVED** [review]
Working for me, Thanks

**Comment by nwf** [comment]
Commit message updated as per @ynezz feedback.

**Comment by ascendbeing** [comment]
Huh. interesting. #14631 would be a pseudo duplicate. I am mildly perplexed this PR exists, and appears to be still a work in progress, yet my bug was still marked "completed".

**Review by systemcrash — APPROVED** [review]

**Comment by nwf** [comment]
Can this be merged?  Do I need to do anything?

**Comment by gUstrx** [comment]
Can anyone post ipk package 2.90 for manual replacement?

**Review by joed74 — APPROVED** [review]
Its working without problems!

**Comment by stangri** [comment]
Great work! Can anyone with permissions cherry-pick it for current release? @robimarko ?

**Comment by systemcrash** [comment]
@stangri this is a relatively busy repo, so see if we can help out and prep the CP (of this commit) as a PR.

**Comment by stangri** [comment]
@systemcrash https://github.com/openwrt/openwrt/pull/14853

**Pull request merged**
