### PR TITLE
Add base support for Perenio PEACG01 Smarthome Gateway

### PR DESCRIPTION
**Pull request by kerenskiy**
Perenio PEACG01 is a Smart Home gateway based on QCA4531-BL3A board with PCF8563 RTC and EFR32 zigbee chip.

Specifications:

- Qualcomm Atheros QCA4531 CPU (Up to 650Mhz)
- 64 MB RAM
- 128 MB ROM on NAND Flash (MX35LF1GE4AB) + 4Mb on SPI Flash (MX25L3236F)
- 1x 802.11b/g/n (2x2) radio
- 1x 10/100 Mbps Ethernet
- 1x USB hub GL850G
- 1x Realtime Clock PCF8563 with battery backup
- 1x USB TTL based on PL2303 chip
- 1x zigbee chip EFR32MG1P232GG
- 3x LED, 3x button
- UART (J6) header on PCB (115200 8n1)
- uboot bootloader with tftp support

Installation:
You need a tftp server with ip address 192.168.1.10 . Connect Perenio PEACG01 by ethernet patch cord to PC with tftp server started on. Build minimal openwrt ramfs with LuCi and turned on AP with DHCP in configs, attach usb-ttl to J6, break boot to enter uboot prompt. Boot ramfs from tftp server with command **tftpboot**, then run ramfs with command **bootm**.

When openwrt bootup and AP started, connect to Wireless Access Point, and flash sysupgrade from LuCi web interface.

Signed-off-by: Aleksandr Chuprin [admin@melamori.ru](url)

### CODE REVIEW

**Comment by NaviyBer** [comment]
Хорошее дело

**Comment by mans0n** [comment]
Hi, this has some formal issues, especially:
* Please add a prefix "ath79:" to the commit title.
* Please add device specification and flashing instruction in the commit message.
* Please add a Signed-off-by tag with your real name.

https://openwrt.org/docs/guide-developer/frequent-pr-mistakes
https://openwrt.org/docs/guide-developer/device-support-policies#commit_message

**Comment by kerenskiy** [comment]
Add specs and flashing instruction.

**Comment by mans0n** [comment]
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes#know_the_difference_between_the_pr_pull_request_and_the_commit

**Comment by NaviyBer** [comment]
а как-то добавить памяти туда можно? сложная операция?

**Comment by MaxS0niX** [comment]
Ping6 :) Must be rebased against current master.

**Comment by mrTURav** [comment]
Приветствую. 
Уто то восстанавливал обратно оригинальную прошивку после openwrt?, из .bin бэкапа.

**Pull request closed without merging**
