### PR TITLE
mtd-utils: update to 2.1.1

### PR DESCRIPTION
**Pull request by dengqf6**
Removed upstream patch
Compile and run tested on mvebu

### CODE REVIEW

**Comment by EXSERENS** [comment]
Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master
Run tested: mvebu, Linksys WRT3200ACM, OpenWrt master

**Comment by xback** [comment]
Pulled into my staging tree.
Thanks!

**Comment by dengqf6** [comment]
@xback I have pushed a commit to update hosts tools too

**Comment by xback** [comment]
@dengqf6 
Update pulled to staging

**Comment by hauke** [comment]
This was applied in 79f235abef5a9902a625995fd9366b21b8fcbb3d and 08e274da9d7b1e4864885921dfa73454bc23b3f9

**Pull request closed without merging**
