### PR TITLE
x86: add led driver for PC Engines APU1

### PR DESCRIPTION
**Pull request by FooDeas**
This driver adds the LED support for the PC Engines APU1.
The driver is based on the Linux kernel driver and modified to support newer firmware versions. Also the default LED configuration is updated to use the correct devices.

Signed-off-by: Andreas Eberlein <foodeas@aeberlein.de>

### CODE REVIEW

**Comment by FooDeas** [comment]
Fixed typos in commit message.

**Comment by ynezz** [comment]
This is diff against leds-apu.c from 5.5-rc3:

```diff
--- drivers/leds/leds-apu.c	2019-12-07 01:21:22.297171958 +0100
+++ drivers/leds/leds-apu1.c	2019-12-25 13:57:10.467014852 +0100
@@ -173,8 +173,8 @@
 	int err;
 
 	if (!(dmi_match(DMI_SYS_VENDOR, "PC Engines") &&
-	      dmi_match(DMI_PRODUCT_NAME, "APU"))) {
-		pr_err("No PC Engines APUv1 board detected. For APUv2,3 support, enable CONFIG_PCENGINES_APU2\n");
+	      (dmi_match(DMI_PRODUCT_NAME, "APU") || dmi_match(DMI_PRODUCT_NAME, "apu1")))) {
+		pr_err("No PC Engines APUv1 board detected. For APUv2,3 support, install kmod-leds-apu2 or enable CONFIG_LEDS_APU2\n");
 		return -ENODEV;
 	}
```

This are the changes in `leds-apu.c` since 4.19.91:

* 60439711b69b leds: apu: add pr_fmt prefix for better log output
* 93562049a62c leds: apu: fix error message on probing failure
* cc92e3cce5db leds: apu: drop profile field from priv data
* 08e83826a5eb leds: apu: drop iosize field from priv data
* da97735cbdb4 leds: apu: drop enum_apu_led_platform_types
* 0344e6166bbf leds: apu: drop superseeded apu2/3 led support

So to me it looks like this out of kernel tree source code is a wrong approach and you should just add the `leds-apu` kernel module to `package/kernel/linux/modules/leds.mk` and eventually backport the fixes/changes since 4.19 into `target/linux/generic/backport-4.19`

**Comment by FooDeas** [comment]
The driver was not present in kernel v4.14. So I didn't add it the "right" way.
I had a look at the v4.19 sources - now I will merge the APU1 and APU2 driver to one single module and add the mainline firmware changes for APU1.

Thanks for your hint!

**Comment by bned-aeberlein** [comment]
Everything revised and successfully tested!

**Comment by bned-aeberlein** [comment]
Everything revised and successfully tested!

**Comment by bned-aeberlein** [comment]
foodeas@aeberlein.de

**Comment by bned-aeberlein** [comment]
Everything revised and tested!

**Comment by bned-aeberlein** [comment]
The implementation was made with the kernel sources of >=v4.20.
Note that with kernel v5.x the LED/Button driver source files for **all** APUs were changed completely.
We have to implement the changes when switching to the v5.x base.

**Comment by bned-aeberlein** [comment]
The implementation was made with the kernel sources of >=v4.19.
Note that with kernel v5.x the LED/Button driver source files for **all** APUs were changed completely.
We have to implement the changes when switching to the v5.x base.

**Comment by bned-aeberlein** [comment]
The implementation was made with the kernel sources of >=v4.19. Here the driver includes support for all APUs.

Note that with kernel v5.x the LED/Button driver source files and their location/name for **all** APUs were changed completely.
We have to implement the changes when switching to the v5.x base.

**Comment by bned-aeberlein** [comment]
Everything revised and successfully tested!

Additional information:
The implementation was made with the kernel sources of >=v4.19. Here the driver includes support for all APUs.

Note that with kernel v5.x the LED/Button driver source files and their location/name for **all** APUs were changed completely.
We have to implement the changes when switching to the v5.x base.

**Comment by FooDeas** [comment]
Everything revised and successfully tested!

Additional information:
The implementation was made with the kernel sources of >=v4.19. Here the driver includes support for all APUs.

Note that with kernel v5.x the LED/Button driver source files and their location/name for **all** APUs were changed completely.
We have to implement the changes when switching to the v5.x base.

**Comment by FooDeas** [comment]
@ynezz  @adrianschmutzler
With release of the current OpenWrt, the used kernel is still v4.14 for the the x86 target.
I think I'll have to take the v4.19 sources as a backport patch into v4.14 and add "@LINUX_4_19" in the DEPENDS section of leds.mk. Is that correct? My goal is to get the driver in the next v19.07.x release.

**Comment by ynezz** [comment]
>  Is that correct?

Nope, don't waste time on that.

> My goal is to get the driver in the next v19.07.x release.

It doesn't look like a fix to me, so it's unlikely, that it would be considered for inclusion into _stable_ release.

**Comment by ynezz** [comment]
@FooDeas we're now at 5.4, care to update this?

**Comment by FooDeas** [comment]
I'll try to have a look and test it next week.

**Comment by adrianschmutzler** [comment]
@FooDeas Ping.

Note that the commit title for the second patch is too long and you should wrap the content of your commit message.

Reference: https://openwrt.org/submitting-patches

**Comment by FooDeas** [comment]
I still have no access to the hardware for testing at the moment. I'll reopen the PR when I have more to commit.

**Comment by FooDeas** [comment]
replaced by #3135

**Pull request closed without merging**
