### PR TITLE
kernel: bump 6.1 to 6.1.52

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.52

All patches automatically rebased.

Build system: x86/64
Build-tested: x86/64/AMD Cezanne
Run-tested: x86/64/AMD Cezanne

### CODE REVIEW

**Comment by graysky2** [comment]
I refreshed the patches against the latest commit from master.  I do not understand why we are getting multiple failures.

**Comment by DragonBluep** [comment]
> I refreshed the patches against the latest commit from master. I do not understand why we are getting multiple failures.

Some target doesn't have 6.1 testing kernel, so CI refreshes 5.15 patches instead. These failures can be ignored.

**Comment by zxlhhyccc** [comment]
> I refreshed the patches against the latest commit from master. I do not understand why we are getting multiple failures.

780 patch To refresh

**Comment by graysky2** [comment]
@zxlhhyccc - not sure what you're saying... is something wrong with that patch as-is?

**Comment by zxlhhyccc** [comment]
@graysky2 The patch should be: `@@ -1181,6 +1183,11 `，Instead of:：`@@ -1180,6 +1182,11 `。

**Comment by graysky2** [comment]
> The patch should be: @@ -1181,6 +1183,11 ，Instead of:：@@ -1180,6 +1182,11 。

Can someone independently verify this with ` update_kernel.sh` - my runs did not do this.

**Comment by KanjiMonster** [comment]
> > The patch should be: @@ -1181,6 +1183,11 ，Instead of:：@@ -1180,6 +1182,11 。
> 
> Can someone independently verify this with ` update_kernel.sh` - my runs did not do this.

https://github.com/openwrt/openwrt/actions/runs/6108676756/job/16578199941?pr=13424 says:

```
Run . .github/workflows/scripts/ci_helpers.sh
target/linux/generic/hack-5.15/930-Revert-Revert-Revert-driver-core-Set-fw_devlink-on-b.patch
Kernel patches for apm821xx/nand require refresh. (run 'make target/linux/refresh' and force push this pr)
You can also check the provided artifacts with the refreshed patch from this CI run.
Error: Process completed with exit code 1.
```

looks like there is a patch that needs refreshing in the current source for 5.15 which is causing these failures. Nothing to do with the changes in this kernel bump.

**Comment by hauke** [comment]
I merged the 5.15 kernel bump which refreshes the kernel 5.15 patches. This should fix the problem.

**Comment by zxlhhyccc** [comment]
> > The patch should be: @@ -1181,6 +1183,11 ，Instead of:：@@ -1180,6 +1182,11 。
> 
> Can someone independently verify this with ` update_kernel.sh` - my runs did not do this.

image

**Pull request merged**
