### PR TITLE
lantiq: grow kernel partition Zyxel P-2812HNU-F1

### PR DESCRIPTION
**Pull request by IdWV**
Change partition table in dts file.
Enable automatic build.

To take advantage of the bigger kernel partition,
the uboot environment has to be changed:
```
setenv nboot 'nand read 0x81000000 0x60000 0x500000; bootm 0x81000000' 
setenv bootcmd 'run nboot'
saveenv
```

Of course you need a u-boot capable of handling this. 
The u-boot discussed in this forum thread:
https://forum.openwrt.org/t/zyxel-p2812hnu-f1-u-boot/100281 
should be able to handle kernels up to an uncompressed size of 16MiB.

### CODE REVIEW

**Comment by csharper2005** [comment]
Please squash all the commits into the one. Probably you also need to change the DEVICE_COMPAT_VERSION.

**Comment by IdWV** [comment]
> Probably you also need to change the DEVICE_COMPAT_VERSION.
After some Googling I think that indeed has to be done. But I wonder what the new version should be. Grepping in the Openwrt sources shows that the consensus seems to be that changing the 'major' means that sysupgrade cannot be used to flash an upgrade, while changing the 'minor' means the config is no longer compatible.
At the moment DEVICE_COMPAT_VERSION is 1.1. Should I change that to 2.0 or 2.1?

**Comment by csharper2005** [comment]
> 'major' means that sysupgrade cannot be used to flash an upgrade

Is this your case?

**Comment by IdWV** [comment]
Most likely. Sysupgrade writes the new uImage to the current kernel partition, which is only 3MiB. When the new uImage is bigger, the box will be bricked. 
The current master yields a bigger uImage, but maybe some genius will come with a patch to generate a significant smaller uImage. (In which case this pull request is not needed).

**Comment by IdWV** [comment]
I'm trying to squash the commits following this guide: https://openwrt.org/docs/guide-developer/working-with-github-pr#squashing_commits, but for some reason it doesn't work. When I execute 
``` 
git branch -a
git checkout p2812hnu-f1
git reset HEAD~2
git add -i
```
I get 
```
<snip>
262:    unchanged       +0/-27 target/linux/x86/legacy/config-6.6
 263:    unchanged        +0/-3 target/linux/zynq/config-6.6
 264:    unchanged        +2/-2 tools/ccache/Makefile
 265:    unchanged        +1/-1 tools/ccache/patches/100-honour-copts.patch

*** Commands ***
  1: status	  2: update	  3: revert	  4: add untracked
  5: patch	  6: diff	  7: quit	  8: help
What now> 
```
And 'help' doesn't yield anything helpful. Am I really supposed to manually do something with 265 changes?

**Pull request closed without merging**
