### PR TITLE
Layerscape fmc support

### PR DESCRIPTION
**Pull request by yangbolu1991**
The old pull request was merged leaving out fmc packages patches since they depended on libxml2 which was in package feed.
https://github.com/openwrt/openwrt/pull/724

This pull request moved libxml2 to core openwrt and added layerscape fmc support.
(packages.git libxml2 pull request: https://github.com/openwrt/packages/pull/6052)
Please help to review.

### CODE REVIEW

**Comment by ruantu** [comment]
None of the configuration options are optional

**Comment by yangbolu1991** [comment]
@ruantu libxml2 and tclap added in this pull request are common packages. 
fmlib, fmc, and fmc-eth-config packages are layerscape specific. 
I'm not so sure your meaning by saying "None of the configuration options are optional". 
:)

**Comment by yangbolu1991** [comment]
Any comments?

**Comment by ynezz** [comment]
@yangbolu1991 Why do you need this directly in OpenWrt, why it shouldn't stay in packages repository? I think, that dragging `libxml2` to OpenWrt is going to be a red flag unless you've very good reason for it. You should explain `Why is this needed?` better in your commit message.

**Comment by yangbolu1991** [comment]
@ynezz Thanks a lot for your comments.
Actually it's ok for me to put these packages in openwrt or packages.
I once sent email to mailing list for suggestion. But got no response. Just sent pull request for suggestion.
Do you think it's proper to put these packages in packages repository?
Some are layerscape specific but they are important for customer to use.

Thanks.

**Comment by ynezz** [comment]
@yangbolu1991 From my point of view, in OpenWrt should be only packages which are needed to boot and configure the target to some reasonable extent, everything else should go to the packages feed (if it would be accepted by the feed maintainers). You can create your own feed, which you can provide to your customers as well.

> I once sent email to mailing list for suggestion. But got no response.

Yes, this happens all the time, it's a project run mostly by volunteers. Probably it has fallen to the grey area, where nobody has strong opinion for or against it. It's normal to just refresh the the discussion after some time with 'Ping' email. There's also IRC channel #openwrt-devel on Freenode, where you can find sometime some of the core developers.

It would be kind if you could close this PR once you decide, that you don't want to continue pushing this packages to the OpenWrt main repository. Thanks!

**Comment by diizzyy** [comment]
@yangbolu1991 
Can you refresh this PR

**Comment by ynezz** [comment]
Seems dead to me.

**Pull request closed without merging**
