### PR TITLE
tools/ninja: update to 1.11.1

### PR DESCRIPTION
**Pull request by neheb**
Also switch to Kitware's fork where the only change is the addition of this patchset that we carry here.

Replace codeload with normal git tarballs.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Replaces https://github.com/openwrt/openwrt/pull/11103

**Comment by hauke** [comment]
I would prefer if we stay at the official repository + patch,
The repo from Kitware says this:
> This branch may be rebased without notice for maintenance on top of the upstream master branch. It will be removed once upstream has integrated the features.

This sounds to me like a normal feature branch.

**Comment by neheb** [comment]
Sounds like https://github.com/openwrt/openwrt/pull/11103 should be merged then.

**Comment by Ansuel** [comment]
@neheb @PolynomialDivision any feedback on this? Think this should be closed in favor of #11103 and that should be updated with the requested changes

**Pull request closed without merging**
