### PR TITLE
kmod-sched: add sch_multiq to extra schedulers

### PR DESCRIPTION
**Pull request by pprindeville**
For hardware that supports multiple hardware output queues, add
a compatible scheduler (NET_SCH_MULTIQ).

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by easyteacher** [comment]
On which device can it benefit? On my MT7621 router the datasheet says it has 16 hardware queues, but it seems OpenWrt lacks proper drivers to enable all of them, for there is only one folder in /sys/class/net/eth*/queues/.

**Comment by pprindeville** [comment]
It works with the `e1000e`, `igb`, and `ixgbe` hardware I believe.

**Comment by blogic** [comment]
merged, Thanks !

**Comment by pprindeville** [comment]
Thanks!

**Pull request closed without merging**
