### PR TITLE
layerscape: use semantic versions for LSDK

### PR DESCRIPTION
**Pull request by aparcar**
PKG_VERSION should not contain the package name but the version only.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by neheb** [comment]
You should also use $(PKG_VERSION) for PKG_SOURCE_VERSION.

**Comment by ynezz** [comment]
>  layerscape: use semantic versions for LSDK

I've always thought, that semantic versioning has 3 components.

> PKG_VERSION should not contain the package name but the version only.

I'm wondering, since when is this a problem? `PKG_VERSION` seems to be funky across various repos/feeds, so why just LSDK?

**Comment by neheb** [comment]
@ynezz it has to do with apk.

**Comment by ynezz** [comment]
On 25. 02. 22 9:08, Rosen Penev wrote:
> @ynezz <https://github.com/ynezz> it has to do with apk.

Shouldn't then APK have some sort of OpenWrt compat layer for 
`PKG_VERSION` instead of such changes? And if such changes are needed, 
shouldn't this be done in one go everywhere once/if we switch to APK?

**Comment by aparcar** [comment]
APK currently enforces a specific version scheme which doesn't not allow arbitrary strings in there.

**Comment by hauke** [comment]
I am fine with this change

**Pull request closed without merging**
