### PR TITLE
ar71xx: improve SPI flash performance

### PR DESCRIPTION
**Pull request by mantas-p**
QCA953x, QCA955x SPI controller has a shift register that allows faster transfer compared to pure bitbang mode. This is mostly relevant to boards that can't use hardware mapping (due to flash using 4-byte opcodes, SPI-NAND or having non-standard chip select)

With this patch set I get 120% read performance gain on Lima dev board (1MB/s -> 2.2MB/s) on simple dd copy test.

For now I've enabled this only on Lima board, other boards should be tested before enabling this in platform data.

### CODE REVIEW

**Comment by pepe2k** [comment]
> QCA953x, QCA955x SPI controller has a shift register that allows faster transfer compared to pure bitbang mode. This is mostly relevant to boards that can't use hardware mapping (due to flash using 4-byte opcodes, SPI-NAND or having non-standard chip select)

This is true also for AR933x, AR934x and QCA956x series.

Cheers,
Piotr

**Comment by LynxChaus** [comment]
Tested on tplink-mr3020 with this patch on top. Boooted, nothing is changed. Maybe boot time decreased on 0.10 sec.

```
diff --git a/target/linux/ar71xx/files/arch/mips/ath79/mach-tl-mr3020.c b/target/linux/ar71xx/files/arch/mips/ath79/mach-tl-mr3020.c
index 0a9dfbc8a0..fd5872c25e 100644
--- a/target/linux/ar71xx/files/arch/mips/ath79/mach-tl-mr3020.c
+++ b/target/linux/ar71xx/files/arch/mips/ath79/mach-tl-mr3020.c
@@ -10,6 +10,7 @@
  */
 
 #include <linux/gpio.h>
+#include <linux/spi/flash.h>
 
 #include <asm/mach-ath79/ath79.h>
 #include <asm/mach-ath79/ar71xx_regs.h>
@@ -17,7 +18,7 @@
 #include "dev-eth.h"
 #include "dev-gpio-buttons.h"
 #include "dev-leds-gpio.h"
-#include "dev-m25p80.h"
+#include "dev-spi.h"
 #include "dev-usb.h"
 #include "dev-wmac.h"
 #include "machtypes.h"
@@ -95,6 +96,23 @@ static struct gpio_keys_button tl_mr3020_gpio_keys[] __initdata = {
        }
 };
 
+static struct spi_board_info tl_mr3020_spi_info[] = {
+       {
+               .bus_num        = 0,
+               .chip_select    = 0,
+               .max_speed_hz   = 25000000,
+               .modalias       = "m25p80",
+               .platform_data  = &tl_mr3020_flash_data,
+       }
+};
+
+static struct ath79_spi_platform_data tl_mr3020_spi_data =
+{
+       .bus_num                = 0,
+       .num_chipselect         = 1,
+       .use_hw_shiftreg        = true,
+};
+
 static void __init tl_mr3020_setup(void)
 {
        u8 *mac = (u8 *) KSEG1ADDR(0x1f01fc00);
@@ -102,8 +120,7 @@ static void __init tl_mr3020_setup(void)
 
        /* disable PHY_SWAP and PHY_ADDR_SWAP bits */
        ath79_setup_ar933x_phy4_switch(false, false);
-
-       ath79_register_m25p80(&tl_mr3020_flash_data);
+       ath79_register_spi(&tl_mr3020_spi_data, tl_mr3020_spi_info, ARRAY_SIZE(tl_mr3020_spi_info));
        ath79_register_leds_gpio(-1, ARRAY_SIZE(tl_mr3020_leds_gpio),
                                 tl_mr3020_leds_gpio);
        ath79_register_gpio_keys_polled(-1, TL_MR3020_KEYS_POLL_INTERVAL,
```

**Comment by mantas-p** [comment]
@LynxChaus thanks for testing!
There is no read performance gain to be expected on TL-MR3020 since it's already using hardware mapping. Writes may be slightly faster but they are mostly limited by memory itself not by the SPI bus.

**Comment by lucize** [comment]
@mantas-p I would like to test this on QCA953x, QCA955x and QCA956x but using dts, how could I enable `use_hw_shiftreg` there ?

**Comment by psyborg55** [comment]
no difference on QCA9531 board. find another way to properly support your lim board!

**Comment by mantas-p** [comment]
Which QCA9531 board you tried exactly? If it has <=16MB flash, then no improvement is expected.

**Comment by psyborg55** [comment]
can you explain why 16MB storage would matter? copying file from RAM to device @ 38KB/s from device to RAM 2.1 MB/s lowest 5.1 MB/s highest rate. with and without your modifications. file size 8.6MB free space approx. 10MB.

**Comment by mantas-p** [comment]
16MB and smaller flash devices use 3-byte addressing, larger ones need 4-bytes. AR71xx flash controller has support for memory mapped (=fast) read access if device use 3-byte addressing. So <=16MB flash will always be fast. 
With larger flash it not possible to use memory mapped access reliably, so this leaves us using SPI bit-bang mode. My patches change bit-bang mode to shift register mode which is almost as fast as memory mapped access.

5.1MB/s read rate is quite unrealistic (with standard QCA9531 SPI clock of ~22MHz, at least), this looks more like read from block cache.

**Comment by psyborg55** [comment]
i assumed that too, since first copy was 2.1 and every other increased for 0.5-1. you can speed up reads if you change spi clock, 37.5MHz reduced a bit boot time here but @40 MHz it already didn't want to boot

**Comment by ratkaj** [comment]
Hi @mantas-p,

I tested your patches on my Lima board. I'm using standard OpenWrt setup with squashfs/jffs2.

Write averages after 10 writes: 
188kB/s without patches
223kB/s with patches

This shows about 20% increase in speed. As for read speed, this was a bit more difficult to determine and while i can't see much of a speed difference i can see that it's much more consistent with the patches.

I found no problems, so this seems good.

**Comment by mantas-p** [comment]
Thanks, @ratkaj 

I did my read testing on raw mtdblock device, skipping JFFS2 gives more consistency.

**Comment by ynezz** [comment]
@mantas-p I would guess, that since nobody has merged it to ar71xx till now, it's not going to happen as all the new development seems to be moved into the ath79/DTS. On ath79 there's a lot of efforts being made to minimalize the patchset over the upstream kernel, so it would be nice if you guys could start pushing your changes upstream first and then backport it to OpenWrt (or it would be picked up).

**Comment by 981213** [comment]
Though I've done the porting a month ago, I'm now wondering whether it's a better idea to write a new driver for ar933x and later chips. They doesn't have to involve the bitbang framework.
What do you guys think?

**Comment by mantas-p** [comment]
I don't think there is need for splitting driver for shiftreg support. We can treat differences in HW it as different features of ath79 SPI IP.

What current shiftreg implementation lacks, compared to bitbang, is handling of clock rate (i.e. divider). If different CS could have different `spi-max-frequency`, driver would be more useful for general purpose SPI (not just for flash memory)

**Comment by psyborg55** [comment]
i should also note that changing .max_speed_hz to match u-boot values did not have any effect in userspace. only clocks set from u-boot would make device boot faster, it could work fine at 50MHz but only with AHB clocked to 400MHz. some AHB clocks just don't work with specific SPI clocks. e.g. AHB 200MHz SPI 33 or 37.5 does not work; AHB 300MHz 33 and 37.5 work but 40 or more do not.

**Comment by ynezz** [comment]
Closing, as it's probably more then clean now, that it's not going to be merged. Thanks, looking forward to your ath79 improvements.

**Pull request closed without merging**
