### PR TITLE
[RFC] mvebu: armada-38x: change order of ethernet DT nodes

### PR DESCRIPTION
**Pull request by seragh**
Not a perfect solution but in my book slightly better than the alternatives

### CODE REVIEW

**Comment by wigyori** [comment]
Ping @kaloz for this one.

**Comment by thagabe** [comment]
last i recall there is already this change upstream linux but there is a problem on wrt1900acv1

**Comment by seragh** [comment]
On Mon, 02 Jan 2017 15:18:37 -0800
Gabe Rodriguez <notifications@github.com> wrote:

> last i recall there is already this change upstream linux but there
> is a problem on wrt1900acv1 
> 

The commit message mentions the upstream commit, so this is just
cherry-picking the commit in 4.6 for 4.4 and 4.1 and a fixup of
base-files.

Mamba (wrt1900acv1) doesn't get touched at all by this PR, it's based
on an armada-xp. Maybe you mean how Lede broke Rango when trying to
unify the meaning of eth0/1 by requiring a working swconfig which Rango
still lacks. This PR doesn't add a dependency on swconfig.

**Comment by blogic** [comment]
already fixed in the LEDE tree which will replace the OWRT tree shortly

**Pull request closed without merging**
