### PR TITLE
qosify: preserve /etc/qosify/* on sysupgrade

### PR DESCRIPTION
**Pull request by rsalvaterra**
Make sure any custom user configuration in /etc/qosify/ is also kept, not just 00-defaults.conf.

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Review by schuettecarsten — APPROVED** [review]

**Comment by dangowrt** [comment]
Actually, maybe `00-defaults.conf` would be the one file in `/etc/qosify/` we should not keep but rather always update with the package...?

**Comment by Ansuel** [comment]
@rsalvaterra in uci-defaults for example? in usr/ and a link in etc/? What is the usage of that file?

We might confider an uci-default script and move the file in usr... If the hash of the file match the expected one we just rm and create the link... If it's not we keep it. What do you think? Should be a nice solution to switch to a more robust implementation.

**Comment by rsalvaterra** [comment]
Let's step back for a bit. The `00-defaults.conf` file resides originally in the read-only root filesystem. Any changes to it will be stored in the overlay. Thus, the way I see it, there are two possible scenarios:

1. The user doesn't edit `00-defaults.conf`. In this case, the file will be normally updated whenever changed in the `qosify` package, as expected.
2. The user edits `00-defaults.conf`. In this case, the file will be preserved on `sysupgrade`, as part of the user configuration (the status quo).

Is (2) _really_ a problem? I believe OpenWrt users expect this behaviour, being an overlayfs-based system. In other words, I don't see an issue at all.

**Comment by dangowrt** [comment]
The problem is that case (1) is not really what happens on sysupgrade, sadly... The file would be copied to backup and restored even if the user did *not* edit it.

**Comment by rsalvaterra** [comment]
> The problem is that case (1) is not really what happens on sysupgrade, sadly... The file would be copied to backup and restored even if the user did _not_ edit it.

Hm. I see. I probably never noticed because I always do `sysupgrade -u`. Come to think of it, `-u` should probably be the default behaviour, but that's another story…

**Comment by blogic** [comment]
reading the thread no conclusion was agreed on. feel free to re-open if this is still an issue that you are working on.

**Pull request closed without merging**
