### PR TITLE
uboot-kirkwood: update to 2018.03

### PR DESCRIPTION
**Pull request by p-wassi**
@lperkov  @bobafetthotmail 

Now, that GCC is 7.3 by default, here's the PR for U-Boot update on kirkwood.

Compile tested for all kirkwood/U-Boot targets
Run tested on Seagate Dockstar only.

As last time, some config options were moved from the included header files
to the respective defconfig files.
@bobafetthotmail I've done some more changes to your 010 patch for Pogoplug v4.
This patch has touched configuration options for the whole kirkwood target. If those
changes are needed, then this should probably go into a patch seperated from the
device support.
In detail:
- CONFIG_FEATURE_COMMAND_EDITING: moved from 'global' to Pogoplug only
is this option required at all? No other device in U-Boot has this option enabled.
- CONFIG_SYS_64BIT_LBA: moved from 'global' to Pogoplug only
- CONFIG_CMD_BOOTZ removed from global, as this gave a redefinition warning
Each device has the CMD_BOOTZ configuration in their defconfig
- CONFIG_CMD_GPIO and CONFIG_KIRKWOOD_GPIO moved from 'global' to Pogoplug only
is this option required for other targets?
- defines for SOC_88F6192_ID and SOC_88F6702_ID removed completely
they're not used anywhere

Things are run-tested on my Dockstars, see console output at [1]

[1]:
https://pwassi.privatedns.org/lede/dockstar/

### CODE REVIEW

**Comment by hauke** [comment]
Does this fix the build error found by build bot with gcc 7?
http://phase1.builds.lede-project.org/builders/kirkwood%2Fgeneric/builds/735

**Comment by p-wassi** [comment]
Hi @hauke 
Yes, these errors were fixed upstream in [1]

Also, the numerous warnings about the redefinition of CONFIG_CMD_BOOTZ are gone
with modification of local patch 010*

[1]:
http://git.denx.de/?p=u-boot.git;a=commit;h=c005f7edbbc41b33de2c5f8d31a8c12d86ffdb59

**Comment by hauke** [comment]
When compiling I am getting a lot of these warnings:
```
  CC      arch/arm/cpu/arm926ejs/cache.o
In file included from include/config.h:5:0,
                 from include/common.h:21,
                 from arch/arm/cpu/arm926ejs/cpu.c:16:
include/configs/pogoplugv4.h:54:0: warning: "CONFIG_SYS_LONGHELP" redefined
 #define CONFIG_SYS_LONGHELP
 
In file included from ././include/linux/kconfig.h:4:0,
                 from <command-line>:0:
include/generated/autoconf.h:90:0: note: this is the location of the previous definition
 #define CONFIG_SYS_LONGHELP 1
 
  CC      arch/arm/mach-mvebu/dram.o
```

**Comment by p-wassi** [comment]
Thanks @hauke , fixed now.
I've also checked the other warnings and found, that there's an issue
with the GPIOs on NSA310.
Some GPIO numbers are beyond 31, and the definition e.g. (1 << 42)
used as a parameter of unsigned int gives a warning.

The function signature `mvebu_config_gpio` together with the comment
in `nsa310.c` suggest, that the mentioned 64 bit are split in 2x 32 bit parameters.
Therefore, I've shifted `NSA310_OE_HIGH` by 32 bits and added "ULL" to the shifted bits.
As I don't own a NSA310, I can't run-test. @bobafetthotmail

**Comment by hauke** [comment]
The mvebu_config_gpio() function here: https://github.com/u-boot/u-boot/blob/master/arch/arm/mach-mvebu/gpio.c only supports 32 bit values, but there are two registers for GPIOs.

**Comment by p-wassi** [comment]
Yeah, that was the thing I was talking about. In the current commit, there's no
64-bit value any more, so it should be fine. (At least the warnings are gone)

**Comment by hauke** [comment]
You probably have to substract just 32 from these values, see the device tree definition for this device: 
https://github.com/torvalds/linux/blob/master/arch/arm/boot/dts/kirkwood-nsa310.dts#L90
the HDD LEDs are on GPIO1 and not on GPIO2

**Comment by p-wassi** [comment]
But there are two HDD LEDs ;-) ("hdd" and "esata")

<pre>
DTS-Name    | DTS-Pin               | U-Boot Name | U-Boot Pin
------------+-----------------------+-------------+-----------
green-hdd   | gpio1, pin 9 = nr.41  | SATA1_GREEN | 41
red-hdd     | gpio1, pin 10 = nr.42 | SATA1_RED   | 42
green-esata | gpio0, pin 12 = nr.12 | SATA2_GREEN | 12
red-esata   | gpio0, pin 13 = nr.13 | SATA2_RED   | 13
</pre>
So it's fine, isn't it? Am I missing something?

**Comment by hauke** [comment]
Ah I overlooked the (MASK >> 32UL), yes that should be fine.

**Comment by hauke** [comment]
Thank you for the patches, they are applied to master.

**Pull request closed without merging**
