### PR TITLE
Enabled support for xr819 radio module and Allwinner H2+ soc-AUDIO

### PR DESCRIPTION
**Pull request by melsem**
..

### CODE REVIEW

**Comment by ysc3839** [comment]
You can use git push --force to overwrite your github repository/branch. The PR will afterwards update automatically.
You don't need to open a new PR.

**Comment by ysc3839** [comment]
Wi-Fi AP still not working using your repository. But Wi-Fi scanning is working.
Did I miss any package? I will try 18.06.

**Comment by melsem** [comment]
> Wi-Fi AP по-прежнему не работает с вашим хранилищем. Но сканирование Wi-Fi работает. 
> Я пропустил какой-либо пакет? Я постараюсь 18.06.

**Comment by melsem** [comment]
Sorry, I pressed the wrong button instead of an answer.

**Comment by melsem** [comment]
> Wi-Fi AP still not working using your repository. But Wi-Fi scanning is working.
> Did I miss any package? I will try 18.06.

Where are your patches?
I will look into them, so as not to dig your source code.

**Comment by melsem** [comment]
Wi-Fi works, and the access point and client are fine.
But Wifi Repyter significantly understates the speed of reception.

**Comment by ysc3839** [comment]
I'm using your repository https://github.com/melsem/openwrt
`git clone https://github.com/melsem/openwrt` and then compile without changes.

**Comment by 981213** [comment]
First of all, all the formal issues mentioned in https://github.com/openwrt/openwrt/pull/2013#issuecomment-486549635 are still there.
Besides that:
1. The xradio driver shouldn't be patched into mac80211 package. You can create a separated package for it like package/kernel/mt76
2. You should break the single commit into separated ones and each commit should do just one thing (e.g. adding sound packages into target/linux/sunxi/modules.mk should be a separated commit).
3. The README of https://github.com/fifteenhex/xradio mentioned that “The structure of the driver isn't great and it can lock up the kernel if it gets confused.” I don't think trading overall system stability to get the low-performance wifi chip working is a good idea.

**Comment by melsem** [comment]
> First of all, all the formal issues mentioned in [#2013 (comment)](https://github.com/openwrt/openwrt/pull/2013#issuecomment-486549635) are still there.

Here is the problem, **formal** issues mentioned 

> Besides that:
> 
> 1. The xradio driver shouldn't be patched into mac80211 package. You can create a separated package for it like package/kernel/mt76

Ok Got it.
> 2. You should break the single commit into separated ones and each commit should do just one thing (e.g. adding sound packages into target/linux/sunxi/modules.mk should be a separated commit).

Ok Got it.
> 3. The README of https://github.com/fifteenhex/xradio mentioned that “The structure of the driver isn't great and it can lock up the kernel if it gets confused.” I don't think trading overall system stability to get the low-performance wifi chip working is a good idea.

Armbian uses the same driver. How to drive it into this mode of operation, for the test ??

**Pull request closed without merging**
