### PR TITLE
sunxi: add text to Makefiles referencing Allwinner H3 and H5 CPUs

### PR DESCRIPTION
**Pull request by RoganDawes**
This makes it a little easier to figure out which options to choose.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Hi, please add a Signed-off-by to your commit message.

**Comment by RoganDawes** [comment]
Done

**Comment by adrianschmutzler** [comment]
@ynezz A quick look here should be enough.

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master

**Pull request closed without merging**
