### PR TITLE
tools/mkimage: update to v2024.04

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Update to latest version.

Refresh patches:
- 030-allow-to-use-different-magic.patch
- 095-tools-disable-TOOLS_FIT_FULL_CHECK.patch

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Comment by namiltd** [comment]
After installing this PR, my router (ramips, mt7620a, TP-link Archer C5 v4)  does not boot.
It displays message like below and restarts over and over again:
```
## Booting image at bc020000 ...

   Uncompressing Kernel Image ... LZMA ERROR 1 - must RESET board to recover

**Comment by PolynomialDivision** [comment]
I reverted it again.

**Comment by DragonBluep** [comment]
> After installing this PR, my router (ramips, mt7620a, TP-link Archer C5 v4) does not boot. It displays message like below and restarts over and over again:
> 
> ```
> ## Booting image at bc020000 ...
> 
>    Uncompressing Kernel Image ... LZMA ERROR 1 - must RESET board to recover
> ```

This is a well known issue which caused by the large kernel size. Have you tried self-build image?

**Comment by PolynomialDivision** [comment]
I don't have a mt7620a currently to test. My ramips device (mt7621) had no issues. Before more devices get bricked, I reverted it. @namiltd Can you investigate that a bit more?

**Comment by DragonBluep** [comment]
BTW, I remember TP-Link devices don't use UImage at all. So I would suggest you also check the recent `zstd` commits.

**Comment by namiltd** [comment]
@DragonBluep I have attached Config in https://github.com/openwrt/openwrt/issues/15088

**Comment by namiltd** [comment]
@PolynomialDivision In my opinion this PR is fine though.
The reasons are kernel size and dictionary size. After uploading the new mkimage, the kernel size increased only by 2kB but unfortunately it exceeded the limit (dictionary size: 8388608 bytes, uncompressed size: 11866779 bytes).
All I had to do was turn off one of the unused kernel modules, the size dropped by 4kB and the router started working.
This is not an update problem, the problem is kernel growth.
If the problem reoccurs, I will try to set the lzma parameters to make the dictionary size smaller.
e.g.:
```
  KERNEL := kernel-bin | append-dtb | lzma -d22
  KERNEL_INITRAMFS := kernel-bin | append-dtb | lzma -d22 | tplink-v2-header -e

**Pull request merged**
