### PR TITLE
[WIP] kernel: add leds support for qca8k

### PR DESCRIPTION
**Pull request by Ansuel**
WARNING
--

This is still WIP. This need to be changed to a generic trigger+ offload function and such I just skipping the rework of this.
The patch currently work but you should remove the documentation patch. **I'm leaving it here just to reference it but it WON'T APPLY as we switched to yaml.**

Add leds support for qca8k. Refer to the documentation patch on
how to implement this in the dts.

Depends on: https://github.com/openwrt/openwrt/pull/4528

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@Leo-PL here is the leds patch... everything should work correctly. I would really appreciate some test.

**Comment by Ansuel** [comment]
I honestly need some help about the label deprecation... and some hint in how to improve documentation and code :(

**Comment by neheb** [comment]
I don't see them.

Screenshot from 2021-09-17 17-32-01

**Comment by Ansuel** [comment]
Did you add them in the dts?

Il Sab 18 Set 2021, 02:33 Rosen Penev ***@***.***> ha scritto:

**Comment by Ansuel** [comment]
@neheb output of ls /sys/class/leds ?

**Comment by neheb** [comment]
```
root@OpenWrt:/# ls /sys/class/leds
ath9k-phy0    green:system  green:usb2    green:wlan5g
green:qss     green:usb1    green:wlan2g
```

although i see you updated the patch now.

**Comment by Ansuel** [comment]
There must be something stupid that we are not noticing ahahaha

**Comment by neheb** [comment]
> There must be something stupid that we are not noticing ahahaha

Yeah what's stupid is that I thought I applied this patch to my tree. Guess not.

**Comment by Ansuel** [comment]
Can you turn them on and off correctly? Does the trigger works?

**Comment by neheb** [comment]
Yeah I can manually control them. Haven't tested triggers.

btw what do you mean deprecate label?

**Comment by Ansuel** [comment]
From https://elixir.bootlin.com/linux/latest/source/Documentation/devicetree/bindings/leds/common.yaml

```
  label:
    description:
      The label for this LED. If omitted, the label is taken from the node name
      (excluding the unit address). It has to uniquely identify a device, i.e.
      no other LED class device can be assigned the same label. This property is
      deprecated - use 'function' and 'color' properties instead.
      function-enumerator has no effect when this property is present.
```

**Comment by neheb** [comment]
I don't know how smart it is to get rid of label. This router's configuration is a bit weird.

ports are
WAN - LAN1 - LAN2 - LAN3 - LAN4

but LEDs are
WAN- LAN4 - LAN3 - LAN2 - LAN1

**Comment by Ansuel** [comment]
@neheb mhh leds refer to the physical port so we just need to swap the label in the dts 

One simple way to test this is check if led lan4 enables lan1 led or lan4... 
There are many device with the lan numbering swapped...

**Comment by neheb** [comment]
I just tried removing label. The name turns to the node name.

Wonder what the point of specifying color is.

**Comment by Ansuel** [comment]
I know strange... it's not that clear looking at the documentation... i should check the source code on how they actually handle the different binding...

**Comment by neheb** [comment]
Uhh something is wrong here: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/leds/led-core.c?h=v5.14.6#n445

I have color and function name specified. But the LED name is just the node name instead of %s:%s

**Comment by Ansuel** [comment]
let me check if this is also present in 5.10

**Comment by neheb** [comment]
Hrm why is it falling to this branch... https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/leds/led-core.c?h=v5.10.67#n477

**Comment by Ansuel** [comment]
yep present... https://elixir.bootlin.com/linux/v5.10.66/source/drivers/leds/led-core.c#L451

**Comment by Ansuel** [comment]
we need to check `props.function || props.color_present` why it doesn't go in this

**Comment by neheb** [comment]
Any way to get a kernel with dev_err throwing stuff?

**Comment by Ansuel** [comment]
just use pr_err or pr_info no dev required  it's like printf... use %x  or %d and the value as arg

**Comment by Ansuel** [comment]
do we actually have a fwnode ? in that function ?

**Comment by neheb** [comment]
Should. Otherwise label = would not work.

**Comment by Ansuel** [comment]
Well time to debug this... i'm curious now...

**Comment by neheb** [comment]
I think I found the issue... https://github.com/openwrt/openwrt/blob/master/target/linux/ath79/patches-5.10/0003-leds-add-reset-controller-based-driver.patch

Does that seem plausible?

**Comment by Ansuel** [comment]
We need to understand why function is not detected by that function... Did you check anything related to that?

**Comment by neheb** [comment]
Couldn't find anything.

**Comment by Ansuel** [comment]
@neheb stop searching... the leds require to register using different api to use the new implementation... will fix this night (if not impossible)

**Comment by Ansuel** [comment]
image
tada :D

**Comment by Human-OS** [comment]
> Add leds support for qca8k. Refer to the documentation patch on
> how to implement this in the dts.
> 
> Depends on: #4528
> 
> Signed-off-by: Ansuel Smith [ansuelsmth@gmail.com](mailto:ansuelsmth@gmail.com)

I am using tp link tl-wr841hp v2(soc ar9344).  Recently i have successfully built openwrt for this device. In the dts i include ethernet port as generic swphy. but i notice in tplink firmware log the ethernet ports are mapped using mdio port map. 

btw, for openwrt with your patch how i map port for dsa support? should i use mdio port map from tplink wdr4300(soc ar9344)?

```
(none) mips #30Now flash open!
 Tue Nov 24 16:01:22 CST 2015 (none)
(none) login: Now flash open!
ATHR_GMAC: Length per segment 1536
ATHR_GMAC: fifo cfg 3 01f00140
mac:1 Registering S27....
ATHR_GMAC: RX TASKLET - Pkts per Intr:32
ATHR_GMAC: Max segments per packet :   1
ATHR_GMAC: Max tx descriptor count :   128
ATHR_GMAC: Max rx descriptor count :   128
ATHR_GMAC: Mac capability flags    :   2D82
mac:0 Registering S27....
ATHR_GMAC: RX TASKLET - Pkts per Intr:32
ATHR_GMAC: Max segments per packet :   1
ATHR_GMAC: Max tx descriptor count :   128
ATHR_GMAC: Max rx descriptor count :   128
ATHR_GMAC: Mac capability flags    :   2582
athr_gmac_ring_alloc Allocated 2048 at 0x838ad000
athr_gmac_ring_alloc Allocated 2048 at 0x83b6d800
WASP ----> S27 PHY MDIO
ATHRS27: resetting s27
ATHRS27: s27 reset done
++++ athrs27_igmp_setup once
port0 vid is 0xb000b
port1 vid is 0x30003
port2 vid is 0x50005
port3 vid is 0x70007
port4 vid is 0x90009
++ PVID: 0x0000000b, bitmap: 0x0000001f
++ PVID: 0x00000003, bitmap: 0x0000001f
++ PVID: 0x00000005, bitmap: 0x0000001f
++ PVID: 0x00000007, bitmap: 0x0000001f
++ PVID: 0x00000009, bitmap: 0x0000001f
vtable vid: 0x00000002, bitmap 0x00000003
vtable vid: 0x00000004, bitmap 0x00000005
vtable vid: 0x00000006, bitmap 0x00000007
vtable vid: 0x00000008, bitmap 0x00000009
vtable vid: 0x0000000a, bitmap 0x0000000b
vtable vid: 0x0000000c, bitmap 0x0000000d
vtable vid: 0x0000000e, bitmap 0x0000000f
vtable vid: 0x00000010, bitmap 0x00000011
vtable vid: 0x00000012, bitmap 0x00000013
vtable vid: 0x00000014, bitmap 0x00000015
vtable vid: 0x00000016, bitmap 0x00000017
vtable vid: 0x00000018, bitmap 0x00000019
vtable vid: 0x0000001a, bitmap 0x0000001b
.
vtable vid: 0x0000001c, bitmap 0x0000001d
vtable vid: 0x0000001e, bitmap 0x0000001f
.
.
vtable vid: 0x00000020, bitmap 0x00000021
.
Setting Drop CRC Errors, Pause Frames and Length Error frames
Setting PHY...
.
athr_gmac_ring_alloc Allocated 2048 at 0x83af0800
athr_gmac_ring_alloc Allocated 2048 at 0x83af0000
WASP ----> S27 PHY MDIO
Setting Drop CRC Errors, Pause Frames and Length Error frames
Setting PHY...
enet1 port1 up 100Mbps Full duplex
ATHR_GMAC: Enet Unit:1 PHY:1 is UP RGMii 1000Mbps full duplex
ATHR_GMAC: done cfg2 0x7215 ifctl 0x0 miictrl
```

**Comment by neheb** [comment]
:)

**Comment by Leo-PL** [comment]
@Ansuel do you have example of color/function mapping in device tree on hand? Just implementing this on C7v2 and WDR4300...

**Comment by Ansuel** [comment]
I think the led doesn't turn on at all.

**Comment by Leo-PL** [comment]
> 
> 
> I think the led doesn't turn on at all.

Acked.

> 
> About color and all I need to change this patch so the standard naming of newer kernel works...

Acked as well, please ping me when you do, I'll pull your patch in then. Right now I've written device trees using new syntax, will fall back to old syntax if needed.

**Comment by Ansuel** [comment]
The changes are ready and as you notice the screen tested.. Just need to clear them and will push here.

**Comment by Ansuel** [comment]
@Leo-PL @neheb pushed the new version and updated the example on how to use it

**Comment by Leo-PL** [comment]
So, regarding the issue I got with WDR4300 - for some """strange""" reason - probably PEBKAC - I got LEDs working according to specified rules only on LAN1-3 ports, i.e PHY 1-3, not on WAN (phy0) and LAN4 (phy4). Other than that, they behave as I specified in DT. That's a bit strange, since all the rules are exactly the same.

**Comment by Ansuel** [comment]
can you post the dts?

**Comment by Leo-PL** [comment]
> 
> 
> can you post the dts? could be absolutely something i did wrong in the patch considering coincidentally... phy0 and phy4 are a different reg than 1-3

Here you are: https://github.com/Leo-PL/openwrt/blob/ath79-dsa/target/linux/ath79/dts/ar9344_tplink_tl-wdr4300.dtsi

**Comment by Ansuel** [comment]
give me a sec to test led4 anyway in theory phy4 should be wan and phy0 should be lan1 

also as i said in the documentation you should really set led rules to the first lan port phy0 and to the wan port as all the lan port refer to the same control rule

**Comment by Leo-PL** [comment]
Acked. Good news is, that manual control (and triggers too) work for me for all ports.

**Comment by Ansuel** [comment]
anyway by testing i can trigger all the port on/off... 

wait a sec!!!! 

i think i understand this not correctly... 

You mean that you can turn lan1 and wan led on/off or that they are off with the rule applied?

**Comment by Ansuel** [comment]
Yep i think i understand the bug... easy fix give me a sec

**Comment by Leo-PL** [comment]
Just for extra clarity I mean that the manual control works fine for all ports, but rule control works _only_ for LAN1-3. LAN4 and WAN remain dark.

**Comment by Ansuel** [comment]
@Leo-PL ok nice! pushing the fix ahahahha give me 2 minutes

**Comment by Ansuel** [comment]
@Leo-PL if you want test now... they should work correctly... also in your opinion the control rule sys should expose all the reg or only the rules? 

Cause in the reg that set the rules is also present the pattern for the wan and led (if it's on off)
What do you think?

**Comment by Ansuel** [comment]
Yes i think i will change the sysfs to expose only the rule part... it makes more sense... even me the dev got confused and notice the bug only because you reported that.

**Comment by Leo-PL** [comment]
I didn't quite get the question in the first place - but I agree - let's expose the mask only, not the address.
I just picked up the latest patch and build is ongoing. I also rebased against current master.

**Comment by Ansuel** [comment]
Just for curiosity i will explain...

In the old version control rule value included also the pattern applied to the port (lan1 or wan)
The led pattern for the other lan2-3-4 are set with another reg and are not controlled by led rules... 

Now i changed the output of the sysfs entry to only report the control_rule with the led port pattern omitted (since it's controlled by brightness/blink/hw_mode)

**Comment by Leo-PL** [comment]
@Ansuel good news: after updating LEDs patch, ports 0 and 4 work as well using rules.

**Comment by Leo-PL** [comment]
@Ansuel swconfig driver keeps LEDs lit as well on poweroff.

**Comment by Ansuel** [comment]
@Leo-PL are you sure the poweroff doesn't just halt the router? The other leds are turned off?

**Comment by Ansuel** [comment]
Anyway i added suspend support but i think poweroff just halt the router so not really a proper power down... no way to fix that i think...

**Comment by Leo-PL** [comment]
You're probably right. Anyway, Wi-Fi leds turn off because they're controlled by wireless phy trigger, and system LED is controlled explicitly by init. I don't think this one synthetic edge case is worth splitting hairs.

**Comment by Ansuel** [comment]
Anyway i think this is ready.... @Leo-PL Do you think we need to add anything else to this?

**Comment by Leo-PL** [comment]
LGTM, I think it's ready.

**Comment by Ansuel** [comment]
I sent an rfc upstream... let the fun begin... aka A BIG NO.

**Comment by Ansuel** [comment]
And rip... as i thought they are planning on standardize the way leds are defined so now i have to take part on the discussion and then eventually add support for leds :( sad

**Comment by Leo-PL** [comment]
Could you please link thread from LKML here for reference?

**Comment by Ansuel** [comment]
Here https://x-lore.kernel.org/lkml/YUjesc5nLItkUNxy@lunn.ch/T/#re7be3b8b742906f657c2dd5c2c1d5cf0d5ffae6d

**Comment by neheb** [comment]
Lame. I hope this can be kept here at least.

**Comment by Ansuel** [comment]
For sure this will be included as it's not that hacky and actually very standard...
But we need to wait and i think I will have to propose a generic implementation... 
And then this will be refreshed... but untile that we will for sure have this merged in openwrt

**Comment by neheb** [comment]
I just looked at some mt7530 LED work that made it upstream: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/net/dsa/mt7530.c?h=next-20210922&id=429a0edeefd88cbfca5c417dfb8561047bb50769

I assume something similar can't be done here.

**Comment by neheb** [comment]
Hehehe I feel like upstream got tricked: https://github.com/neheb/openwrt/commit/6966344f49da0e383c67ce18fcf196a19b937167

stock OEM firmware pokes registers instead of GPIOs.

**Comment by neheb** [comment]
Just had a thought. Would upstream accept a patch to just grab and write to the LED registers? That is, no devm_led_classdev_register_ext .

**Comment by Ansuel** [comment]
> Just had a thought. Would upstream accept a patch to just grab and write to the LED registers? That is, no devm_led_classdev_register_ext .

I proposed an RFC upstream and they were happy that I used cdev and all standard... The complain was that we need a standard and generic solution for this... The patch is surely correct but we need to wait for a generic solution to be proposed... I have an idea but I need some time to implement it and hope it's not bad like the other 20 implementation proposed

**Comment by Ansuel** [comment]
@neheb @adschm Considering the attempt of proposing this upstream failed miserably. (one marvell dev wants to accept his only idea of this feature and any attempt resulted in him rejecting every version and the led team just ignored every revision)

Can we consider adding to openwrt the last revision (with some fixes) in the hack or pending directory so we can start closing some qca8k pr?
If you want I can tag the patch proposed upstream. In short the current state was adding generic support for leds controlled by hardware, tweaking the netdev trigger to support this new mode and add a dedicated trigger to configure the leds. The patch was 90% accepted by the marvell dev (but always with some rejection and other random complains) and I think it was accepted entirely by Andrew from net-next.

Think currently we should just merge the current state while I find the will to start the fight again / hope to "god"(?) that he himself propose a new patch. (also i didn't follow if he already started doing his own version of this feature)

**Comment by Leo-PL** [comment]
Just noticed, that LEDs on my C7v2 are dimly lit even when set to off by the switch, when I had to open the case to unbrick it and measure DRAM voltage. I wonder if it should be the case. It is the same way both with swconfig and with DSA. Haven't had chance yet  to check with vendor firmware, but I plan to do so. Am I right that setting LEDs as open drain had some other serious implications?

**Comment by DittelHome** [comment]
Hi, is there a chance to get WAN LED again back to my Archer C7 V2 ? (under 22.03)

**Comment by Leo-PL** [comment]
@DittelHome see my patches here: https://github.com/Leo-PL/openwrt/tree/ar8327-leds-devicetree
You'll need to build your own build, I don't see much value with upstreaming those when DSA is coming. But maybe someone can convince me otherwise.

**Comment by DittelHome** [comment]
> @DittelHome see my patches here: https://github.com/Leo-PL/openwrt/tree/ar8327-leds-devicetree You'll need to build your own build, I don't see much value with upstreaming those when DSA is coming. But maybe someone can convince me otherwise.

I use the imagebuilder ([openwrt-imagebuilder-22.03.3-ath79-generic.Linux-x86_64.tar.xz](https://downloads.openwrt.org/releases/22.03.3/targets/ath79/generic/openwrt-imagebuilder-22.03.3-ath79-generic.Linux-x86_64.tar.xz) to create my own firmware. In the old ar71xx  builds (equal or older then 19.07.9) i have had the WAN LED, now i miss. Is it not possible to integrate the WAN LED in the actual stable 22.03.3 Release for the Archer C7 V2 ? 
I thought the actual Release is already based on DSA ...

**Comment by Leo-PL** [comment]
Imagebuilder is not enough, you'll have to recompile kernel. OTOH maybe it's worth to integrate this support, because getting DSA to work on ath79 is still going to take a lot of effort. I'll reconsider that.

**Comment by DittelHome** [comment]
> I'll reconsider that.

It would be nice if that works with the 22.03.4 release ...

**Comment by Leo-PL** [comment]
Even if the PR gets merged, this is very unlikely - this is not a bugfix, and I share the opinion of maintainers, which are reluctant to backporting such changes. Anyway, I'll open a PR. I'd be glad for a `Tested-by:`.

**Comment by oldium** [comment]
It looks like LED support is somehow in progress - https://lore.kernel.org/linux-leds/20230327184606.37933d41@kernel.org/T/#t

**Comment by Leo-PL** [comment]
Yes, but that's very much WIP and for new qca8k driver.

**Comment by Ansuel** [comment]
This has been handled differently. Refer to kernel updates or just ask for information to about this if needed.

**Pull request closed without merging**
