### PR TITLE
ipq60xx: qualcommax: add support for Yuncore AX840 AP

### PR DESCRIPTION
**Pull request by legale**
Add Initial Support for IPQ60xx Based YunCore AX840

This series of patches introduces initial support for the Qualcomm IPQ60xx chip, along with support for the YunCore AX840 device.

Key Specifications:
- Qualcomm IPQ6010 chipset
- 1GB DDR3 RAM
- 8MB SPI NOR serial flash
- 256MB NAND parallel flash
- Dual-band WiFi: 2x2 2.4 GHz & 2x2 5 GHz (IPQ6010)
- Dual IPEX/U.FL antenna connectors
- Four 3dBi dual-band antennas
- Two 1Gbps Ethernet ports (QCA8075) with PoE (802.3at) support
- Single RGB LED
- Reset push-button
- 12V DC power input jack
- UART header (4-pin, 2.54 mm pitch) on PCB

Flashing Instructions (under stock QSDK image):
Access the u-boot console and execute the following commands:
```
dhcp
sleep 5
tftpboot 0x44000000 192.168.2.40:ax840_factory.ubi
flash rootfs
flash rootfs_1
reset
```

### CODE REVIEW

**Comment by legale** [comment]
@Ansuel @robimarko please review

**Comment by robimarko** [comment]
Sorry, but please wait until there is an actual `ipq60xx` subtarget, no point in this before.

**Comment by aiamadeus** [comment]
Please stop submitting nss drivers here, these things will not appear in upstream. BTW, the ath11k driver of ipq60xx is very unstable (especially the lack of new ath11k-firmware), so I think it is meaningless to submit ipq60xx support at this time.

**Comment by legale** [comment]
On Wed, Jan 31, 2024, 19:09 aiamadeus ***@***.***> wrote:

> Please stop submitting nss drivers here, these things will not appear in
> upstream. BTW, the ath11k driver of ipq60xx is very unstable (especially
> the lack of new ath11k-firmware), so I think it is meaningless to submit
> ipq60xx support at this time.
>
Wifi works well. I got 3 ipq60xx devices. Edgecore eap101, yuncore ax840,
yuncore fap650

Testing them for about a month.

**Comment by legale** [comment]
Ok. thanks.

**Comment by robimarko** [comment]
Closing until this is rebased on top of master and NSS additions are removed.

**Comment by Neustradamus** [comment]
@legale: Can you look for Yuncore AX840?

**Pull request closed without merging**
