### PR TITLE
automake: Fix "make V=1" behaviour in automake packages.

### PR DESCRIPTION
**Pull request by frolswe**
This patch was originally posted [1] to automake project in 2015, and
has never been accepted. The response to the bug report contains a
workaround packages can use if the have issues with standard automake
behaviour.

This change removes the patch to make automake in OpenWrt behave more
similar as upstream automake.

[1] https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20077

### CODE REVIEW

**Comment by ynezz** [comment]
@frolswe if it's fixing some real world problem as one would guess from the commit subject, then please include example in the commit message (link to the issue, steps to reproduce, whatever helpful)

**Comment by frolswe** [comment]
IMHO, justifications for including this pull request:

1. Impossible to propagate OpenWrt "V=sc" verbosity into the actual package build. The package will always be built without command lines and compiler output.
2. "make -C build_dir/target-*/mypackage V=1" unexpectedly produces no verbose output. This was actually why I discovered this issue to begin with. The build process did not behave as expected, and I had to spend time to debug it to make sure it was not broken in some subtle way. After debugging, the non-standard behaviour turned out to only be related to the V flag, but changes like this could very well have affected other parts of the package build process as well.
3. I believe patches to upstream projects should be kept to a minimum. They always come with the risk of introducing errors (or waste peoples time). I don't think upstream automake think the behaviour this patch introduces is desired, or they would have merged it long ago. Especially when an easy workaround for the original issue exitsts.

Resons for rejecting it:
1. It has been present for ~5 years with nobody publicly complaining.

**Comment by ynezz** [comment]
>     1. Impossible to propagate OpenWrt "V=sc" verbosity into the actual package build. The package will always be built without command lines and compiler output.

```
make package/popt/{clean,compile} V=s 2>&1 | grep -c ^mipsel-openwrt-linux-musl-gcc
3
```

So it works for me.

> 2. "make -C build_dir/target-*/mypackage V=1" unexpectedly produces no verbose output.

```
make -C build_dir/target-mipsel_24kc_musl/popt-1.16 clean all V=1 2>&1 | grep -c ^mipsel-openwrt-linux-musl-gcc
3
```

So it works for me.

**Comment by frolswe** [comment]
Humm, obviously I might be completely wrong, and that would be the best since there would be no real issue..

However, I think you picked an unfortunate package to test on. When I test with popt, the autoremake step fails (without interrupting the build), and the configure file already present in the source archive is used. This configure file was generated by an older and / or not an OpenWrt automake, and thus does not contain my issue. (As far as I can tell this is a completely different bug that also needs fixing..)

Repeating your tests on an other package, e.g. mtd-utils, triggers my issue.
```
$ make package/mtd-utils/{clean,compile} V=sc
...
  CCLD     lsmtd
  CC       nand-utils/nanddump.o
  CCLD     nanddump
...
```
```
$ make -C build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/mtd-utils-2.1.1 clean
...
$ make -C build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/mtd-utils-2.1.1 V=1
...
  CC       lib/libmtd.o
  CC       lib/libfec.o
  CC       lib/common.o
  CC       lib/libcrc32.o
```
Neither make command produces the compile command lines I would expect.

BR
/Fredrik

**Comment by mirko** [comment]
If you're talking about automake silent-rules, I tried to address V=s behaviour for packages using automake back then (43365ca6625363fbe3006ce47300f48434e2d36c / bc67ebc5858956eca492d3a8353162e1b600f954).
If not, please still keep the silent-rules behaviour as it might interfere.

**Comment by ynezz** [comment]
> If you're talking about automake silent-rules, I tried to address V=s behaviour for packages using automake back then ([43365ca](https://github.com/openwrt/openwrt/commit/43365ca6625363fbe3006ce47300f48434e2d36c) / [bc67ebc](https://github.com/openwrt/openwrt/commit/bc67ebc5858956eca492d3a8353162e1b600f954)).

@mirko in your 43365ca you claim `Projects using silent-rules might otherwise fail to compile.` and it makes me wonder which projects/packages are you talking about? I would like to have some test case for this. I did some build tests with this PR applied and didn't encountered any issue.

> If not, please still keep the silent-rules behaviour as it might interfere.

So far it seems to me, that this PR makes sense, but I would prefer to somehow handle the failing packages you're talking about in your original 43365ca as well.

**Comment by mirko** [comment]
> > If you're talking about automake silent-rules, I tried to address V=s behaviour for packages using automake back then ([43365ca](https://github.com/openwrt/openwrt/commit/43365ca6625363fbe3006ce47300f48434e2d36c) / [bc67ebc](https://github.com/openwrt/openwrt/commit/bc67ebc5858956eca492d3a8353162e1b600f954)).
> 
> @mirko in your [43365ca](https://github.com/openwrt/openwrt/commit/43365ca6625363fbe3006ce47300f48434e2d36c) you claim `Projects using silent-rules might otherwise fail to compile.` and it makes me wonder which projects/packages are you talking about? I would like to have some test case for this. I did some build tests with this PR applied and didn't encountered any issue.
> 
> > If not, please still keep the silent-rules behaviour as it might interfere.
> 
> So far it seems to me, that this PR makes sense, but I would prefer to somehow handle the failing packages you're talking about in your original [43365ca](https://github.com/openwrt/openwrt/commit/43365ca6625363fbe3006ce47300f48434e2d36c) as well.

I'm not sure what's unclear. Maybe meanwhile automake got patched/updated to a version, where the generated Makefiles handle it differently, but at least back then the automake developers refused to change its behaviour and claimed $(V) for themselves exclusively.

**Comment by mirko** [comment]
I just did a `openwrt.git$ grep -rn 'AM_V_P = $(am__v_P_$(V))' build_dir/` and apparently that code is still generated by currently used automake.
So, if I recall correctly, those package would be built incorrectly (if at all), if V is set to sth. other than 1 or 0.

**Comment by frolswe** [comment]
When I test, mtr does not fail to build for any setting of V, neither with nor without this PR. Without this PR verbose build output is never displayed. With this PR, verbose build output is displayed for any setting of V other than 0 or unset.

But I can understand that a compile fails if the upstream source uses constructs like "if $(AM_V_P); then ...". I cannot find any packages like this in my current tree though.

I do not think the correct solution for this is to break the V feature of automake. A better way, similar to what Pavel Raiskup suggested in the original bug report is to add the correct V value when calling into the upstream build, and not inherit the OpenWrt V setting. I.e. in the package Makefile for problematic packages:
```
# Translate OpenWrt "V=sc" etc. to automake "V=1".
ifneq ($(strip $(V)),)
  MAKE_FLAGS += V=1
endif
```

If anyone can find a package that actually fails to build with this PR, I am happy to verify this workaround really works and add it to the PR.

**Comment by mirko** [comment]
> But I can understand that a compile fails if the upstream source uses constructs like "if $(AM_V_P); then ...". I cannot find any packages like this in my current tree though.

Maybe we misunderstand each other, but I can find quite a few packages in my current build_dir using that code in their Makefiles.

I'm happy for any better solution. I just couldn't find a better solution in time, so I just quick-fixed builds which broke that way.

To quote myself from my commit back then:

> A better approach would be to actually take $(V) into account,
however not just pass it through (AM_V='$(V)') but
set AM_V to 0 if $V=0 / unset and to 1 otherwise.
This plan however is foiled due to my frustration about
automake as well as my lack of m4 skills.

..or whatever other solution, as long as it doesn't break any package(s) with V set to whatever.
Unfortunately I really don't remember which package(s) I noticed breaking which lead to above stated commits :/

**Comment by mirko** [comment]
Re the actual commit: I wouldn't word it "the following fails", as it doesn't (to me), but that's just cosmetics.
Also, why not reverting my actual commit from back then, so we know what this refers to?

**Comment by ynezz** [comment]
> Maybe we misunderstand each other, but I can find quite a few packages in my current build_dir using that code in their Makefiles.

I just rebuild from scratch ath79, mt7620 and imx6 with this PR applied and with `make V=s`, no problems spotted and `grep -rn 'AM_V_P = $(am__v_P_$(V))' build_dir/` returns 413 occurrences.

>  Also, why not reverting my actual commit from back then, so we know what this refers to?

Good point, I really don't like reverts, but I think, that in this case it makes sense. Can we add your `Acked-by` or `Reviewed-by` tag to that revert commit as well?

@frolswe can you rework this as revert and add there your [failing use case](https://github.com/openwrt/openwrt/pull/2481#issuecomment-540595346) so it's more clear what is currently not working as expected?

**Comment by frolswe** [comment]
> `grep -rn 'AM_V_P = $(am__v_P_$(V))' build_dir/` returns 413 occurrences.
AM_V_P is no problem in itself, it is when it is used in an if statement it can fail. The example from automake documentation looks like: `if $(AM_V_P); then`, which is an error in POSIX-sh if AM_V_P is empty.

> @frolswe can you rework this as revert and add there your [failing use case](https://github.com/openwrt/openwrt/pull/2481#issuecomment-540595346) so it's more clear what is currently not working as expected?
Sure, I'll see what I can do.

**Comment by mirko** [comment]
> Good point, I really don't like reverts, but I think, that in this case it makes sense. Can we add your `Acked-by` or `Reviewed-by` tag to that revert commit as well?

Feel free, please also include a link to this ticket.

**Comment by frolswe** [comment]
Can I do anything more here? Shall I add an "Acked-by: Mirko Vogt <mirko-openwrt@nanl.de>" line to the commit?

**Comment by ynezz** [comment]
> Can I do anything more here? 

It's ok, I'm just allowing some more time for review.

> Shall I add an "Acked-by: Mirko Vogt <mirko-openwrt@nanl.de>" line to the commit?

You can add `Acked-by`, though I can't comment on the content/email.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
