### PR TITLE
Change LED color for Xiaomi Mi-R3G

### PR DESCRIPTION
**Pull request by danielg4**

### CODE REVIEW

**Comment by pepe2k** [comment]
Acked-by: Piotr Dymacz <pepe2k@gmail.com>

**Comment by obsy** [comment]
Acked-by: Cezary Jackiewicz <cezary@eko.one.pl>

**Comment by mkresin** [comment]
merged, thanks!

**Comment by Neustradamus** [comment]
Linked to this merged commit:
- https://github.com/openwrt/openwrt/commit/e4442ca2d87ffebd4e6703e1998cb047c29aec91

**Pull request closed without merging**
