### PR TITLE
[19.07] Backport kernel: fix dst reference leak in flow offload to openwrt-19…

### PR DESCRIPTION
**Pull request by jerome-benoit**
….07 branch.

Fixes a significant amount of leaked memory with lots of connections

c6c4701def07cd01a1b077cee93f64a9b2e3b5be in master

Signed-off-by: Jerome Benoit <jerome.benoit@sap.com>

### CODE REVIEW

**Comment by ynezz** [comment]
@jerome-benoit I would prefer to cherry-pick that c6c4701def07cd01a1b077cee93f64a9b2e3b5be into openwrt-19.07 directly, can I add your `Tested-by: Jerome Benoit <jerome.benoit@sap.com>` ? BTW which device you've tested this backport on?

**Comment by jerome-benoit** [comment]
You can do the relevant commit cherry-picking if you prefer and add the Tested-by but you will have to solve conflicts doing so. 

My testing device is a WRT1900AC v1.

**Comment by ynezz** [comment]
Thanks, handled via 8ab2b42fac4fcbb4a294f3405aa15daeb706a9bd

**Comment by dzz007** [comment]
Seems like some sort of memory leak still exists. But this time it's way better than last time, my router(R6220 Netgear) with 19.07 was crashing every 3 days or so, this time with 19.07.1 was crashing every 11 days or so. This is the latest crash log with 19.07.1: 

Time: 1582056587.249622
Modules:	xt_recent@872ca000+1bf0	xt_helper@8775f000+360	xt_connmark@866ef000+4e0	xt_connlimit@86628000+1510	xt_connbytes@862be000+640	iptable_raw@866ed000+260	pppoe@86dcc000+23e0	ppp_async@86dc8000+1b90	pppox@877b0000+4b0	ppp_generic@86d58000+5970	nf_conntrack_ipv6@86f3a000+1590mt76x2e@877b8000+26c0	mt76x2_common@86f78000+2a40	mt76x02_lib@86cb0000+9640	mt7603e@86f00000+90a0	mt76@86f20000+7920	mac80211@86c00000+6c840iptable_nat@877bc000+2c0	ipt_REJECT@87769000+3c0	ipt_MASQUERADE@876eb000+2a0	cfg80211@86f40000+36b80	xt_time@877d7000+6e0	xt_tcpudp@877d1000+700	xt_state@87796000+2c0	xt_socket@87797000+9b0	xt_nat@876dc000+600	xt_multiport@876ea000+500	xt_mark@877c2000+2a0	xt_mac@8779a000+260	xt_limit@876b7000+4a0	xt_conntrack@876e5000+900	xt_comment@877bf000+1e0	xt_TPROXY@877c6000+11c0	xt_TCPMSS@877b7000+ae0	xt_REDIRECT@877b4000+2c0	xt_LOG@877b2000+300	xt_FLOWOFFLOAD@8779c000+c10	xt_CT@8779e000+a60	slhc@877a0000+13c0	nf_socket_ipv6@8776d000+4c0	nf_socket_ipv4@8770d000+5c0	nf_reject_ipv4@87727000+840	nf_nat_redirect@87687000+580	nf_nat_masquerade_ipv4@87765000+650	nf_conntrack_ipv4@87760000+1420	nf_nat_ipv4@8776b000+f30	nf_nat@87778000+37d0	nf_log_ipv4@87768000+d60	nf_flow_table_hw@87770000+8d0	nf_flow_table@87750000+3350	nf_defrag_ipv6@876ac000+12e0	nf_defrag_ipv4@8776f000+440	nf_conntrack_rtcache@8776e000+aa0	nf_conntrack@87780000+10550	iptable_mangle@876d6000+380	iptable_filter@8770f000+280	ip_tables@87758000+2b30	crc_ccitt@8772f000+3e0	compat@86e0a000+1740	ledtrig_usbport@876e2000+ab0	xt_set@876ae000+1b20	ip_set_list_set@876fe000+1c80	ip_set_hash_netportnet@87748000+6c60	ip_set_hash_netport@87740000+61e0	ip_set_hash_netnet@87738000+6780	ip_set_hash_netiface@87730000+62c0	ip_set_hash_net@87728000+5c00	ip_set_hash_mac@86e00000+2920	ip_set_hash_ipportnet@87720000+6740	ip_set_hash_ipportip@87718000+54a0	ip_set_hash_ipport@87710000+5140	ip_set_hash_ipmark@87708000+4e60	ip_set_hash_ip@87700000+4d80	ip_set_bitmap_port@86e08000+17e0	ip_set_bitmap_ipmac@876f8000+1b80	ip_set_bitmap_ip@876ec000+1ae0	ip_set@876f0000+5690	nfnetlink@876de000+1110	nf_log_ipv6@876da000+1020	nf_log_common@876d2000+aa0	ip6table_mangle@876b6000+4a0	ip6table_filter@876be000+280	ip6_tables@86e0c000+2a2ip6t_REJECT@87685000+400	x_tables@86e04000+3290	nf_reject_ipv6@87684000+9e0	tun@876a0000+5de0	leds_gpio@875c7000+b60	xhci_plat_hcd@875be000+15c0	xhci_pci@875cd000+bc0	xhci_mtk@875c4000+1460	xhci_hcd@87600000+160f0	gpio_button_hotplug@875a4000+1ac0	usbcore@875e0000+1fd50	nls_base@875a0000+1430	usb_common@87595000+8c0
<6>[405343.954921] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[429066.149267] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[429069.222468] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[435500.758204] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[435503.907782] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[436632.868483] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[436640.568028] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[436644.427242] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[436647.157905] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[443342.963457] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
<6>[443343.614613] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[443344.813747] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
<6>[443344.997071] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
<6>[443349.139002] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
<6>[443352.434113] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[443357.994426] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[445485.291287] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[445487.177166] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[445489.894193] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[454410.710430] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[454414.027927] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[479286.194470] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[479289.466900] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[499879.036781] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[499882.119108] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[501204.029699] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[501207.131574] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[533400.719118] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[533403.797298] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[573188.036185] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[573191.126093] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[575326.595505] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[575329.689155] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[619462.286083] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
<6>[619463.132384] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[619466.432446] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
<6>[619470.842572] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[619475.141768] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[623000.163398] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[623001.964683] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[623004.690574] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[625066.437481] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[625070.105757] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[632580.436919] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[632583.521456] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[654325.333458] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[654328.414079] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[663145.293066] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[663148.699388] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[671969.252039] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[671972.655744] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[677093.189589] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[677096.292273] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[678515.182552] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[678518.365854] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[693273.111409] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[693276.292242] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[713343.785302] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[713346.919413] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[716392.990516] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[716396.064700] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[732879.657644] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[732882.721017] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[737001.886488] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[737004.971407] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[743402.751905] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[743405.832271] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[755911.557351] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[755914.643213] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[762027.888462] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[762030.974066] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[763856.687000] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[763859.770268] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[771335.645240] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[771338.739897] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[773845.037543] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[773848.519937] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[779811.378488] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[779814.460741] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[798884.553472] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[798887.632316] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[821066.437160] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[821069.509412] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[836165.359456] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[836168.431114] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[836727.726502] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[836730.791170] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[842838.480849] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[842847.240449] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[842851.587116] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[842854.321476] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[861685.680656] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[861688.765900] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[865335.003545] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[865338.063601] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[866098.142718] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
<6>[866098.884603] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[866102.473569] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
<6>[866106.624932] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[866111.513897] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[939550.652845] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[939552.526866] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[939555.240609] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[961009.167203] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[961012.242689] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[972813.984545] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[972817.174041] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[980837.422588] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[980840.509566] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[987454.742823] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[987458.016265] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[1015210.652591] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[1015213.732841] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[1021487.588311] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[1021490.668662] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<6>[1027876.114622] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
<6>[1027906.566068] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
<1>[1259038.239157] CPU 1 Unable to handle kernel paging request at virtual address 07403000, epc == 8011054c, ra == 80110430
<4>[1259038.260662] Oops[#1]:
<4>[1259038.265522] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 4.14.167 #0
<4>[1259038.277982] task: 87c2bfc0 task.stack: 87c54000
<4>[1259038.287329] $ 0   : 00000000 00000001 00000000 811276d0
<4>[1259038.298077] $ 4   : 8054a1e8 00000001 00000001 07403000
<4>[1259038.308822] $ 8   : 0e4ffdd9 0e4ffdd8 3241a63c 529d396b
<4>[1259038.319564] $12   : 833bb00f 4afeb094 dea62a4c 00000000
<4>[1259038.330308] $16   : 87c02a00 01090220 86240000 80348d5c
<4>[1259038.341050] $20   : 00000700 000005ea 00000000 000005ea
<4>[1259038.351791] $24   : 00000000 eb02a8c0                  
<4>[1259038.362535] $28   : 87c54000 87c0b948 871b9bac 80110430
<4>[1259038.373278] Hi    : 00006c30
<4>[1259038.379339] Lo    : e72f51a0
<4>[1259038.385401] epc   : 8011054c 0x8011054c
<4>[1259038.393366] ra    : 80110430 0x80110430
<4>[1259038.401328] Status: 11007c03	KERNEL EXL IE 
<4>[1259038.409994] Cause : 40800008 (ExcCode 02)
<4>[1259038.418304] BadVA : 07403000
<4>[1259038.424366] PrId  : 0001992f (MIPS 1004Kc)
<4>[1259038.432844] Modules linked in: xt_recent xt_helper xt_connmark xt_connlimit xt_connbytes iptable_raw pppoe ppp_async pppox ppp_generic nf_conntrack_ipv6 mt76x2e mt76x2_common mt76x02_lib mt7603e mt76 mac80211 iptable_nat ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_state xt_socket xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TPROXY xt_TCPMSS xt_REDIRECT xt_LOG xt_FLOWOFFLOAD xt_CT slhc nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc_ccitt compat ledtrig_usbport xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet
<4>[1259038.574429]  ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 tun leds_gpio xhci_plat_hcd xhci_pci xhci_mtk xhci_hcd gpio_button_hotplug usbcore nls_base usb_common
<4>[1259038.652152] Process swapper/1 (pid: 0, threadinfo=87c54000, task=87c2bfc0, tls=00000000)
<4>[1259038.668587] Stack : 00000000 53261646 8660b840 80550000 8660b0c0 87c0b9a7 01080020 80348c5c
<4>[1259038.685565]         877c8c68 86ef20a4 872b4e00 00000002 8660b0c0 0000064b 01080020 87c0c600
<4>[1259038.702540]         00000000 80348d5c 000005fe 8666db40 00020036 00000000 8660b240 000005a8
<4>[1259038.719517]         00000042 8660b240 000005a8 8660b240 000005a8 8666db40 000005ea 803509dc
<4>[1259038.736494]         00000000 00000000 00000000 00000000 00000000 8660b840 877c8bc0 00000042
<4>[1259038.753470]         ...
<4>[1259038.758673] Call Trace:
<4>[1259038.758731] [<80348c5c>] 0x80348c5c
<4>[1259038.771212] [<80348d5c>] 0x80348d5c
<4>[1259038.778510] [<803509dc>] 0x803509dc
<4>[1259038.785801] [<80348a88>] 0x80348a88
<4>[1259038.793075] [<80347210>] 0x80347210
<4>[1259038.800352] [<8034c0e4>] 0x8034c0e4
<4>[1259038.807629] [<80361ef4>] 0x80361ef4
<4>[1259038.814916] [<803d6000>] 0x803d6000
<4>[1259038.822198] [<803e87f4>] 0x803e87f4
<4>[1259038.829496] [<803614f0>] 0x803614f0
<4>[1259038.836779] [<8036169c>] 0x8036169c
<4>[1259038.844069] [<80361c4c>] 0x80361c4c
<4>[1259038.851347] [<80073ef0>] 0x80073ef0
<4>[1259038.858636] [<80362740>] 0x80362740
<4>[1259038.865910] [<8025a960>] 0x8025a960
<4>[1259038.873205] [<8046a5f8>] 0x8046a5f8
<4>[1259038.880484] [<86f20100>] 0x86f20100 [mt76@86f20000+0x7920]
<4>[1259038.891747] [<8046a6b8>] 0x8046a6b8
<4>[1259038.899033] [<8025a748>] 0x8025a748
<4>[1259038.906304] [<80078220>] 0x80078220
<4>[1259038.913578] [<80077fe0>] 0x80077fe0
<4>[1259038.920859] [<8046a804>] 0x8046a804
<4>[1259038.928137] [<80073350>] 0x80073350
<4>[1259038.935429] [<80467780>] 0x80467780
<4>[1259038.942706] [<8036191c>] 0x8036191c
<4>[1259038.949990] [<80361ef4>] 0x80361ef4
<4>[1259038.957272] [<80361ac4>] 0x80361ac4
<4>[1259038.964561] [<803627a8>] 0x803627a8
<4>[1259038.971848] [<80370c38>] 0x80370c38
<4>[1259038.979152] [<80372c6c>] 0x80372c6c
<4>[1259038.986428] [<80256808>] 0x80256808
<4>[1259038.993712] [<87750218>] 0x87750218 [nf_flow_table@87750000+0x3350]
<4>[1259039.006539] [<87752e80>] 0x87752e80 [nf_flow_table@87750000+0x3350]
<4>[1259039.019346] [<80007488>] 0x80007488
<4>[1259039.026637] [<8039edf8>] 0x8039edf8
<4>[1259039.033926] [<803605e8>] 0x803605e8
<4>[1259039.041204] [<86f213e4>] 0x86f213e4 [mt76@86f20000+0x7920]
<4>[1259039.052459] [<86f24e50>] 0x86f24e50 [mt76@86f20000+0x7920]
<4>[1259039.063724] [<80360d74>] 0x80360d74
<4>[1259039.071008] [<86cb5190>] 0x86cb5190 [mt76x02_lib@86cb0000+0x9640]
<4>[1259039.083476] [<80363674>] 0x80363674
<4>[1259039.090761] [<804a24d8>] 0x804a24d8
<4>[1259039.098039] [<80032f84>] 0x80032f84
<4>[1259039.105309] [<80259e70>] 0x80259e70
<4>[1259039.112587] [<80007488>] 0x80007488
<4>[1259039.119858] 
<4>[1259039.123152] Code: 00000000  8e020014  00e23821 <8ce20000> 10000009  cc400000  1040ffbd  00000000  8e060010 
<4>[1259039.142900] 
<4>[1259039.146690] ---[ end trace 3c12f2252428df95 ]---

**Pull request closed without merging**
