### PR TITLE
octeon: switch to Kernel 5.10

### PR DESCRIPTION
**Pull request by aparcar**
CI build with artifacts: https://github.com/aparcar/openwrt/actions/runs/1292196874

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by stintel** [comment]
NAK. This kills my ERL after ~8h of uptime.

**Comment by aparcar** [comment]
@stintel thanks for the status update, are you aware of related patches I could link here?

**Comment by stintel** [comment]
Not that I'm aware of.

**Comment by Grommish** [comment]
I've been running a 5.10 test kernel since you put up the original patch
Adrian, without issue.

I wasn't aware I had to report that somewhere :D   My apologies. If there
is anything else you need from me, let me know.

[image: image.png]

**Comment by Grommish** [comment]
> 
> 
> > I wasn't aware I had to report that somewhere
> 
> You surely never **have to** but it's very helpful since most developers don't have devices for all targets at hand

You're right.. I never considered just how scarce Octeon devices can be.  I never could do a kernel change with the massive bisection of the patches, but I am more than willing to test any changes you do for at least the Octeon platform.. Just ping me so I see it (I can't handle the mailing lists, so I don't see what comes through) and I can toss it on a device

**Comment by Grommish** [comment]
@stintel - I've also found a memleak, but I'm not sure where to go about finding out what it is..

https://forum.openwrt.org/t/oom-killer-dnsmasq-when-physical-free-ram-remains/109351/41

**Comment by aparcar** [comment]
@stintel are you okay to put on the octeon hat?

**Comment by aparcar** [comment]
@stintel please merge or close this based on your conclusion.

**Review by stintel — APPROVED** [review]
I am unable to reproduce the leak I encountered on ERL. Was unable to use the exact setup as I no longer own any ERLs, but I conclude it's very rare to hit it and let's just switch Octeon to 5.10. If we get reports of other people hitting it, we can still mark Octeon source-only.

**Comment by aparcar** [comment]
Done

**Pull request closed without merging**
