### PR TITLE
Dnsmasq

### PR DESCRIPTION
**Pull request by selanf**
f6bd38fc82 dnsmasq: add option ptr-record
4b72fc60b4 dnsmasq: add options mx-target and localmx
a210feb38d dnsmasq: add option log-async

### CODE REVIEW

**Comment by adschm** [comment]
All commits lack a commit message.

Apart from that, using a better PR title might help to attract reviewers/testers.

**Comment by selanf** [comment]
I really dont know what to add. If someone needs the options, he read the manpage before

**Comment by adschm** [comment]
"it should explain to a competent reader why you made this commit."

**Comment by selanf** [comment]
Competent readers know hat a PTR and MX entries in DNS are
For the other it is no problems if they ignore it

**Comment by adschm** [comment]
> Competent readers know hat a PTR and MX entries in DNS are
> For the other it is no problems if they ignore it

Perfect, so your commit message would be that you add these options because they have been missing yet.

**Comment by selanf** [comment]
"missing" is subjective in this case

**Comment by adschm** [comment]
> "missing" is subjective in this case

See? Another reason to add an explanation.

By the way, my time is too precious to waste it on discussing with you why you would need to do _a mandatory formal requirement_. Please just add the commit messages. If you can't find one, you probably haven't thought enough about your change.

**Comment by selanf** [comment]
If you can better write commit messages, do it

**Pull request closed without merging**
