### PR TITLE
kernel: qca-ssdk: update to 12.4

### PR DESCRIPTION
**Pull request by robimarko**
Update SSDK version to 12.4, this fixes weird SFP port link up/downs
while there is no SFP module plugged in.

### CODE REVIEW

**Comment by hnyman** [comment]
@Ansuel @robimarko 

I suspect this commit to cause error `hsl_phy_phydev_get[805]:ERROR:phy_addr 4 phydev is NULL` to repeat every second on DL-WRX36.

r24324-7a8424827f built on 20231107 was ok
r24348-3763a6a075 built on 20231109 is broken.


There aren't that many possible suspects in the commit range, as the error materialises early in the boot process. First deviation from previous is `ssdk_dt_parse_interrupt[909]:INFO:intr-gpio does not exist`.


main-r24348-3763a6a075 built on 20231109T2102 is broken
```
[    2.038831] init: Console is alive
[    2.038981] init: - watchdog -
[    2.414640] random: crng init done
[    2.781012] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    2.907628] ssdk_dt_parse_interrupt[909]:INFO:intr-gpio does not exist
[    2.968586] malibu_phy_api_ops_init[1934]:INFO:qca probe malibu phy driver succeeded!
[    3.006887] hsl_phy_phydev_get[805]:ERROR:phy_addr 4 phydev is NULL
[    3.016535] qca808x_phy_api_ops_init[1844]:INFO:qca probe qca808x phy driver succeeded!
[    3.297090] hsl_phy_phydev_get[805]:ERROR:phy_addr 4 phydev is NULL
[    3.299892] hsl_phy_phydev_get[805]:ERROR:phy_addr 4 phydev is NULL
[    3.307564] hsl_phy_phydev_get[805]:ERROR:phy_addr 4 phydev is NULL
[    4.344707] regi_init[3603]:INFO:Initializing HPPE Done!!
[    4.344809] regi_init[3662]:INFO:qca-ssdk module init succeeded!
[    4.351546] EDMA ver 1 hw init
[    4.355390] EDMA HW Reset completed succesfully
[    4.358049] Num rings - TxDesc:1 (23-23) TxCmpl:1 (7-7)
[    4.362443] RxDesc:1 (15-15) RxFill:1 (7-7)
[    4.380726] **********************************************************
[    4.380765] * NSS Data Plane driver
```


main-r24324-7a8424827f built on 20231107T2034 is ok

```
Thu Nov  9 21:23:44 2023 user.info kernel: [    2.012779] init: Console is alive
Thu Nov  9 21:23:44 2023 user.info kernel: [    2.012906] init: - watchdog -
Thu Nov  9 21:23:44 2023 kern.notice kernel: [    2.254732] random: crng init done
Thu Nov  9 21:23:44 2023 user.info kernel: [    2.728919] kmodloader: loading kernel modules from /etc/modules-boot.d/*
Thu Nov  9 21:23:44 2023 kern.warn kernel: [    2.908666] malibu_phy_api_ops_init[2854]:INFO:qca probe malibu phy driver succeeded!
Thu Nov  9 21:23:44 2023 kern.warn kernel: [    2.946053] hsl_phy_phydev_get[798]:ERROR:phy_addr 4 phydev is NULL
Thu Nov  9 21:23:44 2023 kern.warn kernel: [    2.955896] qca808x_phy_api_ops_init[2665]:INFO:qca probe qca808x phy driver succeeded!
Thu Nov  9 21:23:44 2023 kern.warn kernel: [    3.217907] hsl_phy_phydev_get[798]:ERROR:phy_addr 4 phydev is NULL
Thu Nov  9 21:23:44 2023 kern.warn kernel: [    3.221045] hsl_phy_phydev_get[798]:ERROR:phy_addr 4 phydev is NULL
Thu Nov  9 21:23:44 2023 kern.warn kernel: [    3.920836] regi_init[3989]:INFO:Initializing HPPE Done!!
Thu Nov  9 21:23:44 2023 kern.warn kernel: [    3.920947] regi_init[4049]:INFO:qca-ssdk module init succeeded!
Thu Nov  9 21:23:44 2023 kern.info kernel: [    3.927482] EDMA ver 1 hw init
Thu Nov  9 21:23:44 2023 kern.info kernel: [    3.931498] EDMA HW Reset completed succesfully
Thu Nov  9 21:23:44 2023 kern.info kernel: [    3.934175] Num rings - TxDesc:1 (23-23) TxCmpl:1 (7-7)
Thu Nov  9 21:23:44 2023 kern.info kernel: [    3.938588] RxDesc:1 (15-15) RxFill:1 (7-7)
Thu Nov  9 21:23:44 2023 kern.info kernel: [    4.156809] **********************************************************
Thu Nov  9 21:23:44 2023 kern.info kernel: [    4.156844] * NSS Data Plane driver

```

**Comment by robimarko** [comment]
@hnyman Last `qualcommax` build was yesterday:
https://buildbot.staging.openwrt.org/images/#/builders/168/builds/108
and last change it includes is:
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=91169898ceae20e6acc34060f0906cd3f5959c05

So, this cannot be the issue.

**Comment by hnyman** [comment]
I have self-built the firmware image.
No relation to buildbot.

**Comment by robimarko** [comment]
Ok, then I misunderstood you completely.

**Comment by robimarko** [comment]
I kind of suspect this SSDK commit:
https://git.codelinaro.org/clo/qsdk/oss/lklm/qca-ssdk/-/commit/c780bf47f7288b9c100380af2c3881054d720356

**Pull request merged**
