### PR TITLE
kmod-mdio: fix extra closing paren in AUTOLOAD definition

### PR DESCRIPTION
**Pull request by pprindeville**
Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by seragh** [comment]
Tested-by ...

**Comment by pprindeville** [comment]
I tested this by dioing a "make clean" and rebuilding, burning a fresh CFast card, and rebooting.

Then I looked for the module being loaded as well as the module which depended on it.  Both were loaded.

Then again, I had a successful build, load, and run when the extra paren was preset also, so it's not clear what's adequate test coverage.

**Comment by seragh** [comment]
Sorry if I confused you, just wanted to signal I tested it myself and it fixes the issue. Don't know of a more appropriate way with the github workflow.

For this to fail during build you need to add -e to shellopts

**Comment by pprindeville** [comment]
> For this to fail during build you need to add -e to shellopts

How would that work?  In the `$(topdir)/Makefile`, would we add:

```
export SHELLOPTS=$(SHELLOPTS):errexit
```

**Comment by pprindeville** [comment]
Can we proceed with merging the fix?

**Comment by wigyori** [comment]
Thanks for this fix.

**Comment by pprindeville** [comment]
Thanks!

**Pull request merged**
