### PR TITLE
Add some extra Kernel config parameter to package/kernel/linux/module…

### PR DESCRIPTION
**Pull request by Plonkbong**
…s/video.mk,

because if graphic support enabled and kmod-fb choiced, compiling stops for asking these kernel parameter.

Signed-off-by: Plonkbong <plonkbong100@protonmail.com>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by ynezz** [comment]
@Plonkbong 

Please read https://openwrt.org/submitting-patches specifically following parts:

* commit subject
> must be less than 50 characters long

Probably something like `kernel: Add missing kernel symbols to kmod-fb module`

* commit description
>    must have less than 75 characters per line
> it will be committed to the source changelog, so it should explain to a competent reader why you made this commit.
> Include symptoms of the failure you are fixing (log messages, error messages, etc.), it will be useful for people searching the commit logs looking for a fix for their issue.
> If a patch fixes a compile failure, include only the most relevant part of the failure log

* real name in your SoB
> all commits must contain Signed-off-by: My Name <my@email.address> where you write your real name and real email address, in accordance with Section 11 of the Linux Kernel patches guide.

Please don't close this PR and open a new one. Please use `git commit --amend` to add changes to your commit. Use `git push --force` to overwrite your github repository/branch. The PR will afterwards update automatically. See the [squashing commits instructions](https://openwrt.org/submitting-patches#squashing_commits) on how to modify this PR without closing it and open a new one.

**Comment by Plonkbong** [comment]
Is this now OK in terms of form ?

**Comment by adrianschmutzler** [comment]
It might be good to add the "kernel:" in front of you commit title as suggested by ynezz.

**Comment by Plonkbong** [comment]
This PR change add only some kernel config parameter for graphic support.
Your have not to use this PR your can add some own config parameter, but without these parameter and you build with graphic support packages the build process stops and ask fore these parameters.
This sucks !

And my naive idea behind this PRs was: before i start a bug report or change it only for me i fix it in upstream openwrt.

**Comment by CodeFetch** [comment]
@Plonkbong Indeed this is very frustrating. I recommend a more prosaic commit message:
```
kernel: set new config symbols for graphic support

Some kernel config parameters are missing for graphics
support. This leads to an interruption of the build
process due to prompts for user choices.
This commit adds the missing defaults to allow for an
unattended build.
```

**Comment by Plonkbong** [comment]
Looks like that the problem are fixed, for this reason the PR are closed

**Pull request closed without merging**
