### PR TITLE
linux/named-gpio-export: add support for OPEN_DRAIN and OPEN_SOURCE flag

### PR DESCRIPTION
**Pull request by sch-m**
This change makes it possible to use the GPIO_OPEN_DRAIN / GPIO_OPEN_SOURCE Flags when exporting GPIOs via dts.

We need to emulate the open-source or open-drain functionalities for the initial value, because the used functions (gpiod_direction_output_raw) do not take this into account.

### CODE REVIEW

**Comment by hauke** [comment]
Please refresh the patch

**Comment by sch-m** [comment]
> Please refresh the patch

@hauke: Done.

**Comment by hauke** [comment]
There are also some style problems in the patch, please fix them too:
```
--- a/target/linux/generic/hack-6.1/800-GPIO-add-named-gpio-exports.patch
+++ b/target/linux/generic/hack-6.1/800-GPIO-add-named-gpio-exports.patch
@@ -15,7 +15,7 @@ Signed-off-by: John Crispin <blogic@openwrt.org>
  
  #include "gpiolib.h"
  #include "gpiolib-of.h"
-@@ -1030,3 +1032,101 @@ void of_gpio_dev_init(struct gpio_chip *
+@@ -1030,3 +1032,100 @@ void of_gpio_dev_init(struct gpio_chip *
  	else
  		gc->of_node = gdev->dev.of_node;
  }
@@ -62,22 +62,21 @@ Signed-off-by: John Crispin <blogic@openwrt.org>
 +				if (of_flags & OF_GPIO_SINGLE_ENDED) {
 +					/*
 +					 * As devm_gpio_request_one() uses gpiod_direction_output_raw(),
-+					 * we need to to emulate open drain or open source here.
++					 * we need to emulate open drain or open source here.
 +					 */
 +					if (of_flags & OF_GPIO_OPEN_DRAIN) {
 +						flags |= GPIOF_OPEN_DRAIN;
 +						flags |= val ? GPIOF_IN : GPIOF_OUT_INIT_LOW;
-+					}
-+					else {
++					} else {
 +						flags |= GPIOF_OPEN_SOURCE;
 +						flags |= val ? GPIOF_OUT_INIT_HIGH : GPIOF_IN;
 +					}
-+				}
-+				else
++				} else {
 +					flags |= val ? GPIOF_OUT_INIT_HIGH : GPIOF_OUT_INIT_LOW;
-+			}
-+			else
++				}
++			} else {
 +				flags |= GPIOF_IN;
++			}
 +
 +			if (devm_gpio_request_one(&pdev->dev, gpio, flags, name ? name : of_node_full_name(np)))
 +				continue;
```

**Comment by hauke** [comment]
Thank you for the patch, I applied it to main in 0af88d2512b94bb0e3d81058beaa220448e46119.

**Pull request closed without merging**
