### PR TITLE
tools: add `gnulib`, `gperf`, `libxml`, use with `libtool`, `coreutils`, `gettext`

### PR DESCRIPTION
**Pull request by mcprat**
following conversation in #12233 

Having a copy of `gnulib` allows us to remove some statically stored macro files, have updated macro files in our aclocal directory, and sync GNU tools with the same `gnulib` source while having control over it, and possibly more.

Each GNU tool that uses `gnulib` does a full download of `gnulib` whenever it is prepared for release, 
Each of the tools have a different copy of gnulib checked out from different commits. Having the same copy increases control over the build at the cost of a little bit of build time.

`m4`, `patch`, and `sed` potentially would also be able to do this, but there is no real benefit, and it's not easy to do. For example `patch` is so old that it doesn't work with newer `gnulib` source. Running the bootstrap script usually requires autoreconf, so using it on tools built before `automake` is not ideal and tends to have issues, so it would require reordering all of the dependencies between those tools.

There are some random fixes in here for issues that got in my way during testing.

### CODE REVIEW

**Comment by mpratt14** [comment]
@httpstorm try this and let me know what you think :D

**Comment by httpstorm** [comment]
@mpratt14 
We have a successful build on macOS. Thank you for your hard work, Michael! 🥳

**Comment by mpratt14** [comment]
last 2 commits for bootstrap with gnulib changes time more than I thought, may not be worth it

```
10287.40user 1754.53system 1:13:29elapsed 273%CPU (0avgtext+0avgdata 419572maxresident)k
1493152inputs+4502520outputs (4680major+102035460minor)pagefaults 0swaps
```

```
11296.20user 2084.98system 1:30:13elapsed 247%CPU (0avgtext+0avgdata 414648maxresident)k
1994320inputs+4938264outputs (9341major+120954533minor)pagefaults 0swaps
```

**Comment by httpstorm** [comment]
@mpratt14 
I don't understand, what does that data mean, and what would you suggest?

**Comment by mpratt14** [comment]
build time for tools before and after this PR

just something that no one likes to see increase, not sure what to do about it

**Comment by httpstorm** [comment]
@mpratt14 
Indeed people won't be happy if we slow the build down. Can we perhaps use just the `m4` files from `gnulib`, and take some shortcuts? Can you add some testing code, to measure the time used for building each tool? That should point to why we are getting slow.
If you like, I can run the same comparison on my side. What commands should I use?
Does it really take you one and a half hours to build just the tools or is this CPU time when all cores are considered? Could there be something interfering with the time measurements?

**Comment by mpratt14** [comment]
I got rid of the coreutils commit for now, it's not very important anyway. The main goal is that the new macros are in the openwrt aclocal directory.

that commit is still in another branch `tools-gnulib-final-all` if you want to use it

**Comment by mpratt14** [comment]
for the CI the difference was greater

macos-latest was 93 minutes, now it is back to 64 minutes

using the linux tools container it was 25 minutes before, we'll see shortly what it is now...

**Comment by mpratt14** [comment]
@jow- I would like to know your thoughts about this, since you added missing-macros

**Comment by httpstorm** [comment]
@mpratt14 
Regarding the build time for `coreutils`, there are three steps when building from a freshly cloned git:
`./bootstrap`, `./confiigure`, `make -j 16`. The `make` phase is very fast, a few seconds at most. The first two however take a few minutes. For comparison when building from the official `.tar.xz` archive, the `configure` script is already created and that saves half of the build time so long as we skip the `bootstrap` phase. The `coreutils` team said we don't need the `bootstrap` phase, and it may produce a bad `configure` script to be generated when used with old or incompatible `m4` files. So I removed `PKG_FIXUP:=autoreconf` from `tools/coreutils/Makefile` and this made the build faster. If any of your changes triggers `autoreconf`, the build time for `coreutils` will increase significantly. Hint: they do. There might be two reasons for that:
- `autoreconf` triggered explicitly by the OpenWRT build system
- the `coreutils` build process finds changes that require the `configure` script to be regenerated, for example modified `m4` files.

Any difference in the `configure` script between archive and build directory should indicate it was regenerated. Here is before and after your commits compiled on 2023-04-02:
```
-- # Generated by GNU Autoconf 2.71 for GNU coreutils 9.2.
++ # Generated by GNU Autoconf 2.71 for GNU coreutils UNKNOWN.
```
So if you can avoid that, the time will be reduced to that it was before.

**Comment by mpratt14** [comment]
using the bootstrap script on fresh source directly causes autoreconf to be ran, and I think it's necessary because it would not yet have the macros it needs locally

**Comment by httpstorm** [comment]
@mpratt14 
`bootstrap` does autoreconf, which is not necessary:
> If you're building from that tarball, coreutils doesn't need m4. I just 
now double-checked that, in an environment that didn't have m4. 
"./configure && make check" succeeded. So the m4 version should be 
irrelevant.
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=61386#259

Run a build after we upgraded to `coreutils-9.2` and you will see that autoreconf is not used. The original `configure` script from the tarball is used, and results in a successful build that should be faster than before. It would be best if we avoid autoreconf. The only case when we need to autoreconf a package, is when we modify any of the `m4` files. Then it will trigger automatically and it would be best if we use `m4/*.m4` from whatever package we are building.

> Yes if that m4 file is patched then m4 will need to run to regen stuff.
Though the existing m4 tool should be fine for that.
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=61386#265

**Comment by mpratt14** [comment]
in summary:

bootstrap calling autoreconf is necessary with fresh git source, and takes a long time

build fails after bootstrap with a release tarball which is already bootstrapped by devs
(unlike libtool)

so we are stuck unless we copy gnulib stuff another way, without the bootstrap script, which is why I threw out the commit for now

**Comment by httpstorm** [comment]
@mpratt14 
Correct. One way of keeping optional bootstrap would be to wrap your changes inside a conditional statement:
```
# uncomment this line to enable autoreconf
# PKG_FIXUP:=autoreconf

ifeq ($(PKG_FIXUP),autoreconf)
define Host/Bootstrap
	( \
		cd $(HOST_BUILD_DIR); \
		$(filter-out %true,$(AM_TOOL_PATHS)) \
		./bootstrap \
			--bootstrap-sync \
			--no-git \
			--skip-po \
			--gnulib-srcdir=$(GNULIB_SRCDIR) \
	)
endef

define Host/Prepare
	$(call Host/Prepare/Default)
	$(if $(QUILT),,$(call Host/Bootstrap))
endef

define Host/Configure
	$(if $(QUILT),$(call Host/Bootstrap))
	$(call Host/Configure/Default)
endef
endif
```

We may also provide a way to override the `m4` path:
```
# if defined, use M4 path specified here instead of ./host/share/aclocal
PKG_M4_PATH:=$(HOST_BUILD_DIR)/m4

# or relative to the project build dir, to make it more clean
PKG_M4_PATH:=m4

# or a flag: if 1, use m4 from the project build dir
# PKG_HAS_M4:=1

# or make it automatic
# if the path exist $(HOST_BUILD_DIR)/m4
# use it, else use ./host/share/aclocal
```

**Comment by mpratt14** [comment]
it doesn't have much to do with the macros directory (aclocal), I don't think it's worth it

and remember bootstrap doesn't work with the release package, only with a clone of source

**Comment by httpstorm** [comment]
@mpratt14 
`bootstrap` does work with a release package if we use updated `m4` files. If will only break the build if we use the old ones.

**Comment by mpratt14** [comment]
ok well I don't know how you got it to work, specifying the gnulib directory is supposed to give it the macros from gnulib, and those macros got copied into the aclocal directory too

**Comment by httpstorm** [comment]
@mpratt14 
If I copy `coreutils/m4` over to `aclocal` and enable `PKG_FIXUP:=autoreconf`, it builds correctly. It also went smooth when you first asked me to compile your branch. Perhaps I should have mentioned that the `Makefile` changes I suggested are rather a hint. The conditional block should work. `PKG_M4_PATH`, etc. can be implemented.

**Comment by mpratt14** [comment]
in my commit for coreutils, the source changes

autoreconf might work by itself, but not as part of the bootstrap script

**Comment by httpstorm** [comment]
@mpratt14 
If any of the files inside `coreutils/m4` changes, the `configure` script is recreated automatically. I assumed this is done through `bootstrap`, but I might me wrong. I apologise if I mislead you. I do not have experience with `autoreconf` or `bootstrap`.

**Comment by httpstorm** [comment]
@mpratt14 
If you send me a list of changes and commands I can test them for you. I have access to macOS 12.6.4 and Ubuntu 22.04.
My brain is fried at the moment, I just fixed a rare issue with the context switch code in nano RTOS, my own OS for embedded. 😎

**Comment by mpratt14** [comment]
ok I figured out how to skip autoreconf for bootstrap script in coreutils

**Comment by mpratt14** [comment]
@httpstorm if you run the following command on macos does it work?

`/usr/bin/env true --version`

**Comment by mpratt14** [comment]
packages build failing from a known issue

https://forum.openwrt.org/t/recent-builds-failing-on-gettext-full/153927

**Comment by httpstorm** [comment]
@mpratt14 
> @httpstorm if you run the following command on macos does it work?
> 
> `/usr/bin/env true --version`

```
/usr/bin/env true --version
# no output
which -a true
/usr/bin/true
which -a gtrue
/usr/local/bin/gtrue
/usr/bin/env gtrue --version
true (GNU coreutils) 9.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering.
```

**Comment by mpratt14** [comment]
I'm not understanding why the command fails with the CI...

**Comment by mpratt14** [comment]
seems like the problem is the spaces, and the shell is doing word splitting because the positional variables are not quoted

ending up with

`/usr/bin/env --verbose true --version`

**Comment by mpratt14** [comment]
sigh.... everything works on my side

@httpstorm can you help me out with testing on macos, do you get the same result as the CI build?

gettext needs gperf, which i selected as dependent, still not found...

coreutils needs to have autotools set to "env true" (unless there's another simple way) and the space is causing issues

**Comment by mpratt14** [comment]
ok I see that gperf is not getting built in the CI

the action "build all core packages" is likely not fetching the packages repository, so it needs to either do that or we add gperf and libxml2 to core Openwrt 

@Ansuel @neheb do you have any ideas on the best way to handle that? I know this is getting messy but I think it's still worth it after figuring this part out. It's able to fix building of gettext which currently is broken in master.

**Comment by neheb** [comment]
lz4 has a meson build. Should switch to that IMO.

**Comment by mpratt14** [comment]
I've seen the problem with time.h in coreutils on my system before but it stopped happening so I removed a line for it

at least now theres a reasonable solution for skipping autotools during bootstrap script now

**Comment by mpratt14** [comment]
finally.... now to rebase

**Comment by mpratt14** [comment]
squashed, rebased, and added commit messages

**Comment by mpratt14** [comment]
reorganized a little bit and updated commit messages

**Comment by httpstorm** [comment]
@mpratt14 running test build on macOS 12.6.5…

**Comment by mpratt14** [comment]
thanks for catching the typo (now to fix it...)

I wouldn't call this a performance improvement, goal of this PR is to have more consistency and control over the source and fewer patches and static files, but there is a hit to the build time

**Comment by mpratt14** [comment]
following the conversation in #12402,  now added a patch that allows libtextstyle build to not force usage of the included libxml.

very simple patch, just deletes the file that was created here
https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=commit;h=87927a4e2e1c57ae52af5f52bdefd306a1181d22

ping @1715173329 if you want to test again

**Comment by 1715173329** [comment]
Not sure if `libtextstyle/configure` requires patch too

**Comment by mpratt14** [comment]
last commit has gettext use autogen.sh which regenerates all configure scripts

**Comment by 1715173329** [comment]
Oh I overlooked that, will check it later today

**Comment by mpratt14** [comment]
I forgot to put `tools/gnulib/patches/000-bootstrap.patch` back the way it was, it has print messages edited for debugging...

will do it later...

**Comment by 1715173329** [comment]
compiled with `CONFIG_BUILDBOT=y` and so far so good

**Comment by mpratt14** [comment]
oops I have a typo in the makefile

`HOST_BUILD_DIR` for target build

**Comment by mpratt14** [comment]
should be good now...

**Comment by httpstorm** [comment]
@mpratt14 I compiled it successfully yesterday.

**Comment by Ansuel** [comment]
I would merge this after branch

**Comment by neheb** [comment]
@Ansuel in that case you should merge https://github.com/openwrt/openwrt/pull/12402

**Comment by Ansuel** [comment]
ahh fk it lets merge and see how it goes hoping this won't explode in rc stage... 

@mpratt14 can you by chance create pr for dropping the package in feeds?

**Comment by neheb** [comment]
Long range build failures: https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc/

**Comment by mpratt14** [comment]
gnulib is not being put in the SDK?

**Comment by Ansuel** [comment]
@mpratt14 in theory you should be able to check that from snapshot output

**Comment by mpratt14** [comment]
it honestly seems like some weird thing happened where the sdk was built and started running in the builder with a checkout before this PR and then grabbed packages base feed from after this PR

the faillog is 2 days old now, how often does it rerun?

**Comment by mpratt14** [comment]
no wait, the docs directory is missing

**Comment by mpratt14** [comment]
in target/sdk/Makefile

EXCLUDE_DIRS has `*/doc`

we just have to remove it, and perhaps delete doc folders except the one for gnulib, unless there is a more fancy way

I think it's better to just not have those docs installed into staging_dir at all...

**Comment by mpratt14** [comment]
#12563 should help

**Comment by 1715173329** [comment]
https://downloads.openwrt.org/snapshots/faillogs/mipsel_mips32/base/gettext-full/compile.txt
```
Making all in src
make[8]: Entering directory '/builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1/gettext-runtime/src'
mipsel-openwrt-linux-musl-gcc -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I..  -I. -I. -I.. -I../intl -I./../intl -I../gnulib-lib -I./../gnulib-lib -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/usr/include -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/include/fortify -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/include  -DINSTALLDIR=\"/usr/bin\" -Os -pipe -mno-branch-likely -mips32 -mtune=mips32 -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1=gettext-0.21.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic  -c -o gettext-gettext.o `test -f 'gettext.c' || echo './'`gettext.c
/bin/bash ../libtool  --tag=CC   --mode=link mipsel-openwrt-linux-musl-gcc -DINSTALLDIR=\"/usr/bin\" -Os -pipe -mno-branch-likely -mips32 -mtune=mips32 -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1=gettext-0.21.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic   -L/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/usr/lib -L/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/lib -znow -zrelro  -o gettext gettext-gettext.o ../gnulib-lib/libgrt.a ../intl/libintl.la     
libtool: link: mipsel-openwrt-linux-musl-gcc -DINSTALLDIR=\"/usr/bin\" -Os -pipe -mno-branch-likely -mips32 -mtune=mips32 -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1=gettext-0.21.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z -Wl,now -Wl,-z -Wl,relro -DPIC -fpic -znow -zrelro -o .libs/gettext gettext-gettext.o  -L/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/usr/lib -L/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/lib ../gnulib-lib/libgrt.a ../intl/.libs/libintl.so
/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/12.2.0/../../../../mipsel-openwrt-linux-musl/bin/ld: ../gnulib-lib/libgrt.a(libgrt_a-iconv.o): in function `rpl_iconv':
iconv.c:(.text+0x520): undefined reference to `u8_mbtoucr'
/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/12.2.0/../../../../mipsel-openwrt-linux-musl/bin/ld: iconv.c:(.text+0x598): undefined reference to `u8_mbtoucr'
/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/12.2.0/../../../../mipsel-openwrt-linux-musl/bin/ld: iconv.c:(.text+0x734): undefined reference to `u8_uctomb_aux'
/builder/shared-workdir/build/sdk/staging_dir/toolchain-mipsel_mips32_gcc-12.2.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/12.2.0/../../../../mipsel-openwrt-linux-musl/bin/ld: iconv.c:(.text+0x75c): undefined reference to `u8_uctomb_aux'
collect2: error: ld returned 1 exit status
make[8]: *** [Makefile:1638: gettext] Error 1
make[8]: Leaving directory '/builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1/gettext-runtime/src'
make[7]: *** [Makefile:1636: all-recursive] Error 1
make[7]: Leaving directory '/builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1/gettext-runtime'
make[6]: *** [Makefile:1541: all] Error 2
make[6]: Leaving directory '/builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1/gettext-runtime'
make[5]: *** [Makefile:406: all-recursive] Error 1
make[5]: Leaving directory '/builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1'
make[4]: *** [Makefile:362: all] Error 2
make[4]: Leaving directory '/builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1'
make[3]: *** [Makefile:189: /builder/shared-workdir/build/sdk/build_dir/target-mipsel_mips32_musl/gettext-0.21.1/.built] Error 2
time: package/feeds/base/gettext-full/compile#1059.75#384.77#3849.89
```

looks like there're still some issues with iconv.

**Pull request merged**
