### PR TITLE
generic: improve EON EN25Q128 and add EON EN25QX128A

### LINKED ISSUE #9442: xiaomi-4a-gigabit-edition has a new flash which is EN25QX128@44Mhz cause a endless reboot
I tried [openwrt-21.02.1-squashfs-sysupgrade](https://downloads.openwrt.org/releases/21.02.1/targets/ramips/mt7621/openwrt-21.02.1-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin) and 
[openwrt-21.02.2-squashfs-sysupgrade](https://downloads.openwrt.org/releases/21.02.2/targets/ramips/mt7621/openwrt-21.02.2-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin), both cause a endless reboot,
Due to conditional restrictions, I cannot provide the system startup log.
this is my info in breed(I use this breed:[breed-mt7621-pbr-m1.bin](https://breed.hackpascal.net/breed-mt7621-pbr-m1.bin))
image

### PR DESCRIPTION
**Pull request by Ansuel**
Improve EON EN25Q128 with QUAD_READ from documentation and add EON EN25QX128A spi-nor flash definition.

Fixes: #9442

---

This is a continuation of #9635

### CODE REVIEW

**Comment by Ansuel** [comment]
@xabolcs can you test?

**Comment by xabolcs** [comment]
> Also do you have an issue open about the affected device that doesn't work?

#9442

**Comment by Ansuel** [comment]
@xabolcs are we aware of any device that use EN25Q128? Need to know if quad read works.

**Comment by xabolcs** [comment]
> and would be good to have a tested-by tag

Will provide one, but ...
```
Applying /openwrt/target/linux/generic/pending-5.10/476-mtd-spi-nor-add-eon-en25q128.patch using plaintext: 
patching file drivers/mtd/spi-nor/eon.c

Applying /openwrt/target/linux/generic/pending-5.10/477-mtd-spi-nor-add-eon-en25qx128a.patch using plaintext: 
patching file drivers/mtd/spi-nor/eon.c
patch: **** malformed patch at line 21:  

Patch failed!  Please fix /openwrt/target/linux/generic/pending-5.10/477-mtd-spi-nor-add-eon-en25qx128a.patch!
make[4]: *** [Makefile:31: /openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.10.147/.prepared_e60e16e730b9bba08c94c5b3f96af369] Error 1
make[4]: Leaving directory '/openwrt/target/linux/ramips'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/openwrt/target/linux'
time: target/linux/compile#9.50#7.84#12.94
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/openwrt'
make[1]: *** [target/Makefile:23: /openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/openwrt'
make: *** [/openwrt/include/toplevel.mk:231: world] Error 2
```
k5.10 patch doesn't apply after `make clean`. :confused: 


> are we aware of any device that use EN25Q128? Need to know if quad read works.

[Forum search](https://forum.openwrt.org/search?q=EN25Q128) found a few topic like:
* [Support for new Archer c5 v4](https://forum.openwrt.org/t/support-for-new-archer-c5-v4/15889/238)
* [TG582n change of flash chip](https://forum.openwrt.org/t/tg582n-change-of-flash-chip/109013)

**Comment by Ansuel** [comment]
@Deoptim Can you test this?

**Comment by xabolcs** [comment]
> can you retest?

Sure.
I'm testing this PR as merging into `master`:
```
$ git fetch origin refs/pull/10971/merge:pr-10971-merge-EN25QX128A --force
From https://github.com/openwrt/openwrt
 + b957eed283...dc2adb20c5 refs/pull/10971/merge -> pr-10971-merge-EN25QX128A  (forced update)
```
Is this ok? should I test the branch head instead?

**Comment by xabolcs** [comment]
Patch now applies but doesn't compile. :see_no_evil: 

```
make[5]: Entering directory '/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.10.147'
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  CC      drivers/mtd/spi-nor/eon.o
drivers/mtd/spi-nor/eon.c:20:57: error: macro "INFO" requires 5 arguments, but only 4 given
   20 |         { "en25qx128a", INFO(0x1c7118, 0, 64 * 1024, 256) },
      |                                                         ^
In file included from drivers/mtd/spi-nor/eon.c:9:
drivers/mtd/spi-nor/core.h:320: note: macro "INFO" defined here
  320 | #define INFO(_jedec_id, _ext_id, _sector_size, _n_sectors, _flags)      \
      | 
drivers/mtd/spi-nor/eon.c:20:25: error: 'INFO' undeclared here (not in a function)
   20 |         { "en25qx128a", INFO(0x1c7118, 0, 64 * 1024, 256) },
      |                         ^~~~
```

Should I delete my `build_dir`?

**Comment by Ansuel** [comment]
@xabolcs sorry my mistake pls test with 5.10... They made so much changes to the spi macro and i was following new implementation...

**Comment by xabolcs** [comment]
```
===================================================================
                MT7621   stage1 code done 
                CPU=500000000 HZ BUS=166666666 HZ
===================================================================


U-Boot 1.1.3 (Apr 12 2021 - 09:00:20)

Board: Ralink APSoC DRAM:  128 MB
Power on memory test. Memory size= 128 MB...OK!
relocate_code Pointer at: 87fb0000

Config XHCI 40M PLL 
RT2880_RSTSTAT_REG 0xc0030004
******************************
Software System Reset Occurred
******************************
flash manufacture id: 1c, device id 71 18
Warning: un-recognized chip ID, please update bootloader!
============================================ 
Ralink UBoot Version: 5.0.0.0
-------------------------------------------- 
ASIC MT7621A DualCore (MAC to MT7530 Mode)
DRAM_CONF_FROM: Auto-Detection 
DRAM_TYPE: DDR3 
DRAM bus: 16 bit
Xtal Mode=3 OCP Ratio=1/3
Flash component: SPI Flash
Date:Apr 12 2021  Time:09:00:20
============================================ 
icache: sets:256, ways:4, linesz:32 ,total:32768
dcache: sets:256, ways:4, linesz:32 ,total:32768 

 ##### The CPU freq = 880 MHZ #### 
 estimate memory size =128 Mbytes
#Reset_MT7530
set LAN/WAN LLLLW

restore_defaults:<NULL>

Please choose the operation: 
   1: Load system code to SDRAM via TFTP. 
   2: Load system code then write to Flash via TFTP. 
   3: Boot system code via Flash (default).
   4: Entr boot command line interface.
   7: Load Boot Loader code then write to Flash via Serial. 
   9: Load Boot Loader code then write to Flash via TFTP. 

   n3: System Boot system code via Flash.
Booting System 1
Erasing SPI Flash...
raspi_erase: offs:30000 len:10000
.
Writing to SPI Flash...
.
done
## Booting image at bc180000 ...
   Image Name:   MIPS OpenWrt Linux-5.10.147
   Image Type:   MIPS Linux Kernel Image (uncompressed)
   Data Size:    2731633 Bytes =  2.6 MB
   Load Address: 80001000
   Entry Point:  80001000
   Verifying Checksum ... OK
OK
Erasing SPI Flash...
raspi_erase: offs:30000 len:10000
.
Writing to SPI Flash...
.
done
commandline uart_en=0 factory_mode=0 mem=128m root=/dev/mtdblock9
No initrd
## Transferring control to Linux (at address 80001000) ...
## Giving linux memsize in MB, 128

Starting kernel ...



OpenWrt kernel loader for MIPS based SoC
Copyright (C) 2011 Gabor Juhos <juhosg@openwrt.org>
Decompressing kernel... done!
Starting kernel at 80001000...

[    0.000000] Linux version 5.10.147 (xabolcs@ut2004) (mipsel-openwrt-linux-musl-gcc (OpenWrt GCC 11.3.0 r20946+2-fcff86be06) 11.3.0, GNU ld (GNU Binutils) 2.37) #0 SMP Fri Oct 14 19:41:21 2022
[    0.000000] SoC Type: MediaTek MT7621 ver:1 eco:3
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 0001992f (MIPS 1004Kc)
[    0.000000] MIPS: machine is Xiaomi Mi Router 4A Gigabit Edition
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] VPE topology {2,2} total 4
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
...
[    0.636174] spi-mt7621 1e000b00.spi: sys_freq: 220000000
[    0.642958] spi-nor spi0.0: en25qx128a (16384 Kbytes)
[    0.648182] 8 fixed-partitions partitions found on MTD device spi0.0
[    0.654586] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions
[    0.661886] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions
[    0.670033] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions
[    0.677386] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions
[    0.684938] Creating 8 MTD partitions on "spi0.0":
[    0.689738] 0x000000000000-0x000000030000 : "u-boot"
[    0.695701] 0x000000030000-0x000000040000 : "u-boot-env"
[    0.701937] 0x000000040000-0x000000050000 : "Bdata"
[    0.707844] 0x000000050000-0x000000060000 : "factory"
[    0.713972] 0x000000060000-0x000000070000 : "crash"
[    0.719998] 0x000000070000-0x000000080000 : "cfg_bak"
[    0.726105] 0x000000080000-0x000000180000 : "overlay"
[    0.732111] 0x000000180000-0x000001000000 : "firmware"
[    0.738351] 2 uimage-fw partitions found on MTD device firmware
[    0.744298] Creating 2 MTD partitions on "firmware":
[    0.749249] 0x000000000000-0x00000029aeb1 : "kernel"
[    0.754202] mtd: partition "kernel" doesn't end on an erase/write block -- force read-only
[    0.763458] 0x00000029aeb1-0x000000e80000 : "rootfs"
[    0.768447] mtd: partition "rootfs" doesn't start on an erase/write block boundary -- force read-only
[    0.778447] mtd: device 9 (rootfs) set to be root filesystem
[    0.784295] 1 squashfs-split partitions found on MTD device rootfs
[    0.790461] 0x0000005d0000-0x000000e80000 : "rootfs_data"
...
[   58.798097] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready



BusyBox v1.35.0 (2022-10-14 19:41:21 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r20947+3-63e5ba8e69
 -----------------------------------------------------
 | Machine: Xiaomi Mi Router 4A Gigabit Edition      |
 | Uptime: 0d, 00:02:34                              |
 | Load: 0.35 0.26 0.10                              |
 | Flash: total: 8.7MB, free: 8.3MB, used: 4%        |
 | Memory: total: 117.7MB, free: 91.2MB, used: 22%   |
 | WAN:                                              |
 | LAN: 192.168.1.1, leases: 1                       |
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@OpenWrt:/# 
```
(note the chip id in the u-boot!)
(the motd is custom :wink: )


So here is it for k5.10:
`Tested-by: Szabolcs Hubai <szab.hu@gmail.com> [ramips/mt7621: xiaomi_mi-router-4a-gigabit]`

**Comment by Ansuel** [comment]
@xabolcs now we just need to fix an user to test the other patch....

**Comment by xabolcs** [comment]
> > Also do you have an issue open about the affected device that doesn't work?
> 
> #9442

#9652 is a dupe of the above. May be closed when this lands.

**Comment by xabolcs** [comment]
> > are we aware of any device that use EN25Q128? Need to know if quad read works.
> 
> [Forum search](https://forum.openwrt.org/search?q=EN25Q128) found a few topic like:

Reading them they have different chip ID than `0x1c3018`. :confused:

**Comment by xabolcs** [comment]
> now we just need to fix an user to test the other patch....

For `en25q128` / `0x1c3018` the original submission is still open: [[1/2] mtd: spi-nor: Add support for EON EN25Q128](https://patchwork.ozlabs.org/project/linux-mtd/patch/20181209170342.9554-2-hauke@hauke-m.de/) (and your PDF is newer revision than [that](https://tonyho.github.io/static/SPINorFlash/docs/EN25Q128.pdf): `J` vs `E`)

**Comment by hauke** [comment]
I haven't looked into this topic for a long time. It would be nice if you could get this into the mainline kernel. I do not have a device with this flash chip.

I do not understand how the SPI NOR flash handling in recent kernel versions works. In the past we had to add each SPI NOR flash manually to the list of supported flash chips. Is the kernel now able to detect some basic properties of an SPI NOR chip  automatically?

**Comment by Ansuel** [comment]
Yes if the chip supports it, the kernel try to detect it first and fallback
to static flags...

In new kernel they moved all to macro and they have a book to enable
autodetection... By the way quad is not supported by dual is supposed so I
think we can merge this with the dual read flag.

Il Sab 15 Ott 2022, 22:26 Hauke Mehrtens ***@***.***> ha
scritto:

**Review by hauke — APPROVED** [review]

**Comment by Ansuel** [comment]
> I haven't looked into this topic for a long time. It would be nice if you could get this into the mainline kernel. I do not have a device with this flash chip.
> 
> I do not understand how the SPI NOR flash handling in recent kernel versions works. In the past we had to add each SPI NOR flash manually to the list of supported flash chips. Is the kernel now able to detect some basic properties of an SPI NOR chip automatically and it is not needed to add each chip to the list of supported SPI NOR chips?

I can send the EON EN25QX128A but we really need test for the other one... is it that hard to find user for that device o.o?

**Comment by xabolcs** [comment]
> but we really need test for the other one... is it that hard to find user for that device o.o?

The [Wiki search](https://openwrt.org/start?q=en25q128&do=search) finds the LEDE 17.01 release and the Thomson TG582n.
For the latter I posted a forum topic earlier - which I necroposted! 😅

**Comment by mark4z** [comment]
nay update? there are many users waiting this.

**Comment by szero** [comment]
Leaving my 2 cents on this issue: the EN25Q128 part of the code should be moved to separate backburner PR that awaits  someone with appropriate device to test it while the EN25QX128A part gets merged, I suspect that all new Xaomi devices will be rolling out with EON flashchips. Lack of this change on master branch slows OpenWrt adoption for Xiaomi Mi Router 4A Gigabit Edition V2/ Mi Router AC1200 at the moment.

**Comment by hauke** [comment]
At least parts of this was merged in d7876daf6552a9f39bd5e0bf50b554e9406ec275

**Comment by Ansuel** [comment]
Correct I honestly think this won't ever be tested so it will stall here
forever

Il Ven 6 Gen 2023, 19:30 Hauke Mehrtens ***@***.***> ha
scritto:

**Comment by Ansuel** [comment]
Closing this as there is no way to test EON EN25Q128. Sad but has to be done.

**Pull request closed without merging**
