### PR TITLE
ncurses: add foot terminfo

### PR DESCRIPTION
**Pull request by 9ary**
Add terminfo file for the terminal emulator foot.

https://codeberg.org/dnkl/foot

Prior art: #12078

### CODE REVIEW

**Comment by robimarko** [comment]
Can this instead be shipped like kitty-terminfo as a separate optional package?

**Comment by Kistelini** [comment]
I think it should be the other way around: The terminfo file for kitty should be in this package instead of a separate one. It's been upstreamed a long time ago: https://github.com/mirror/ncurses/commit/22a4b929f47f85588dc07fddf98b09776cec658f

**Comment by 9ary** [comment]
Either way makes sense to me. Splitting is not a terrible idea because terminfo can take up quite a bit of space due to the sheer number of terminals supported by ncurses (I'm seeing 7 to 9MB on two desktop-class distros, which is quite significant considering the flash space available on some targets).
A terminfo-full package and/or kconfig option could work. Or some other arbitrary segmentation, like splitting it up alphabetically.

**Comment by robimarko** [comment]
Please fix the formal issues as reported by the bot

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by 9ary** [comment]
Thank you!

**Pull request merged**
