### PR TITLE
mvebu: multiPort DSA support on mv88e6xxx switch

### PR DESCRIPTION
**Pull request by anomeome**
- Allow multiPort DSA, default CPU port assign via ip link set (iproute2)
	or DTS with default-cpu using dangole 780-5-net-dsa-add-dts-property-default_cpu.patch
- DTS modification to XP and 385 only

Note: prereq patch series https://patchwork.ozlabs.org/project/openwrt/list/?series=282003
The Marek Behun patch is modded a bit from the original push on 5.4

compile / test : mamba / rango

Signed-off-by: Kabuli Chana <newtownBuild@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
> * or DTS with default-cpu using dangole

Consider that the current interest of openwrt is keeping things as more upstream acceptable as possible.
The additional binding for the default cpu port was rejected at times. The correct way suggested by the netdev team is to change the link at runtime. The solution I have on ipq806x is a simple init script that change the link before network is up.

**Comment by anomeome** [comment]
My understanding is that this is all considered a temporary  OpenWrt specific _hack_ and will not be finding its way upstream (again), while awaiting a solution found to be acceptable upstream. imo the solutions in order of preference would be:
- DTS setting the _default_cpu_
- the OOTB round-robin (but I surmised this may be problematic on some targets so went with the above)
- the addition of the script as you alluded to above (but in this case I would just opt for setting in rc.local)
I see that you have submitted a V2, but with some follow up conversation. I can certainly scrape out the DTS mods but will wait for a design decision.

**Comment by robimarko** [comment]
The issue with "temporary" hacks is that they pretty much almost always become permanent.
Just look at the number of various hacks in OpenWrt that date years ago and its hard to even tell what are they doing

**Comment by dangowrt** [comment]
I don't see a big problem with having an additional DTS binding for that, because I see it does make sense and even if rejected upstream, we carrying a patch just for this locally would not a tragic. I also wonder what the reason for the rejection has been (I can't find that patch ever being submitted to kernel ml).
Maybe we just have to improve the naming of the attribute? More correctly, it should probably be 'linux,default-cpuport` or something like that.
Because setting the port labeled as WAN to use another MAC as other ports do *is* a hardware-specific property, as you won't get full bandwidth otherwise and the used MAC could even differ in features. Sure, doing this in user-space also works, it's just much more ugly, if you ask me.

**Comment by Ansuel** [comment]
There were many multicpu attempt and one of them had the binding to set the default cpu port. It was rejected as in the dsa idea every port is the same and cpu port (aka master port) should be handled differently. So the idea of a cpu port set only for a dsa port is not accepted (for now).

From what i understand the main intention by netdev team about multicpu is add support for lag across master (cpu port) and set every dsa port to the lag interface,

**Comment by elkablo** [comment]
One of the problems I see with both the DTS solution and `ip link` solution (the current, simple one) is that they work only for the simple cases, where there is a switch connected to CPU via multiple ports. DSA means `Distributed Switching Architecture`. The `Distributed` keyword means that there can be several switches connected to each other and some of them to the CPU.

Example:

```
                               +-------+
                               |  CPU  |
                               | p0 p1 |
                               +-v---v-+
           RJ45  RJ45            |   |            RJ45  RJ45
             |    |              |   |              |    |
        +----^----^----+   +-----^---^-----+   +----^----^----+
  RJ45--<p5  p6  p7  p0>---<p7   p0 p1   p2>---<p0  p7  p6  p5>--RJ45
        |      SW2     |   |      SW1      |   |      SW3     |
  RJ45--<p4  p3  p2  p1>---<p6   p5 p4   p3>---<p1  p2  p3  p4>--RJ45
        +----v----v----+   +-----v---v-----+   +----v----v----+
             |    |              |   |              |    |
           RJ45  RJ45          RJ45 RJ45          RJ45  RJ45
```

Here both `SW2` and `SW3` are connected to `SW1` via 2 ports, and `SW1` is connected to the CPU via 2 ports. The idea now of a CPU port for `p5` of `SW3` is vague. We have to talk about `upstream ports`. One problem is that upstream ports are not currently visible from userspace at all. There is no `eth` device associated with them. Another problem is that one might want packets from `SW3p5` and `p6` go to `SW1` via `SW3p0`, but to CPU via `SW1p0` and `SW1p1`, respectively - so the path is same in `SW3` but different in `SW1`. Now we have to talk about routing tables between the switches, and so it gets even more complicated.

Thus the idea of a simple `ip link set dsa-cpu-port` is insufficient for upstream kernel.

Another thing is that for switches which have good port aggregation support the better solution is to use that and aggregate the multiple ports into one. But some switches, for example Marvell LinkStreet switches (those supported by the `mv88e6xxx` driver) have only simple hashing for port aggregation, and choose the port only from hash of `src+dst MAC address`, which on a simple network has non-trivial probability of ending up with only one of the upstream ports being used...

Thus my advice here for you now is to create a simple patch that allows setting CPU port for the simple scenarios via `sysfs`, and create an utility for accessing these sysfs settings.

**Comment by tiagogaspar8** [comment]
>From what i understand the main intention by netdev team about multicpu is add support for lag across master (cpu port) and set every dsa port to the lag interface,

Do you have any idea of the status of that work? That's what I've been thinking ever since I started to dabble with DSA

**Comment by Ansuel** [comment]
They have started working on it... Aka they are making all the prereq to
support it. There is still lots to do.

Il Mer 26 Gen 2022, 01:22 Tiago Gaspar ***@***.***> ha
scritto:

**Comment by dangowrt** [comment]
Afaik none of the simple switch ICs commonly found in consumer grade routers even supports LAG.

**Comment by robimarko** [comment]
I know that QCA8k series does, MV88E6xxx mostly as well but I am not sure whats the support for LAG-s on the CPU ports

**Comment by dangowrt** [comment]
Wow, even the RealTek ones can offload LAG apparently...
https://github.com/openwrt/openwrt/pull/4973/commits/316ccf5f0ada32f3bb1ec96bb83a3d9f2263adcf

**Comment by tiagogaspar8** [comment]
That's what I was going to say, what ethernet chips that are connected to the CPU by means of two eth's don't support lag?
I believe none, most of them are either Realtek, Qualcomm, Marvell or Realtek, with a few exceptions I guess.
Unfortunately I can't comment on how lag would be implemented at driver level, that's out of my depth, but I'm sure you smart guys already have come ideas 😆

**Comment by Ansuel** [comment]
Again the problem is dsa using a lag interface as master not strictly setting a switch to that mode...

Some netdev team upstream are working on that.

**Comment by tiagogaspar8** [comment]
Hell, I've searched all over and found nothing... sad...
But I'm glad somebody's working on it and I hope we can backport this soon!

**Comment by Ansuel** [comment]
@tiagogaspar8 it's all preparation... (not clearly said but the final goal is multicpu) soon is a big word tho...

**Comment by tiagogaspar8** [comment]
Yeah I know, by one can hope, I believe it's the best way this feature can be implemented and I'd like to follow it, and test it once I can

**Comment by httpstorm** [comment]
For my WRT3200, I maintain a patch in my fork that reverts back from DSA to switch mode, so I can use port mirroring and have separate Ethernet interfaces for LAN and WAN. I noticed there is a third Ethernet interface. I was enabled it through .dts, then configured a MAC address, but I am not getting any communication. Does anyone know if `eth1` is connected to the switch? Can I use it?

**Comment by anomeome** [comment]
withering

**Pull request closed without merging**
