### PR TITLE
bpf tools: update libbpf and bpftool

### PR DESCRIPTION
**Pull request by guidosarducci**
**Maintainer**: me

**Description**:
Update libbpf and bpftool to versions v1.3.0 and v7.3.0 respectively, to include recent upstream improvements and bugfixes, while also refreshing local patches. These changes remain ABI-compatible with the previous release.

Upstream changelogs:
- https://github.com/libbpf/libbpf/releases/tag/v1.3.0
- https://github.com/libbpf/bpftool/releases/tag/v7.3.0

**Testing**: Build tested on ipq40xx, run tested on mipseb32/malta.

CC: @hauke @PolynomialDivision based on previous reviews/merges.

### CODE REVIEW

**Comment by guidosarducci** [comment]
Rebased against master.

**Comment by guidosarducci** [comment]
This passed all checks prior to rebasing, so I'm guessing something else recently changed in the build, apparently related to `libubox` building/deps.
```
====== Make errors from logs/package/libs/libubox/host-compile.txt ======
[41/46] Building C object CMakeFiles/blobmsg_json-static.dir/blobmsg_json.c.o
[42/46] Linking C static library libblobmsg_json.a
[43/46] Building C object CMakeFiles/jshn.dir/jshn.c.o
[44/46] Linking C executable jshn
FAILED: jshn 
: && /__w/openwrt/openwrt/openwrt/staging_dir/host/bin/gcc -O2 -I/__w/openwrt/openwrt/openwrt/staging_dir/host/include -I/__w/openwrt/openwrt/openwrt/staging_dir/hostpkg/include -I/__w/openwrt/openwrt/openwrt/staging_dir/target-x86_64-openwrt-linux-musl_musl/host/include -DNDEBUG -L/__w/openwrt/openwrt/openwrt/staging_dir/host/lib -L/__w/openwrt/openwrt/openwrt/staging_dir/hostpkg/lib -L/__w/openwrt/openwrt/openwrt/staging_dir/target-x86_64-openwrt-linux-musl_musl/host/lib   -rdynamic CMakeFiles/jshn.dir/jshn.c.o -o jshn  -Wl,-rpath,/__w/openwrt/openwrt/openwrt/build_dir/hostpkg/libubox-2023-11-27-d4c3066e:  libblobmsg_json.so  -Wl,-Bstatic  -ljson-c  -Wl,-Bdynamic  libubox.so && :
/usr/bin/ld: libubox.so: undefined reference to `shm_unlink'
/usr/bin/ld: libubox.so: undefined reference to `shm_open'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:114: /__w/openwrt/openwrt/openwrt/build_dir/hostpkg/libubox-2023-11-27-d4c3066e/.built] Error 1
time: package/libs/libubox/host-compile#5.21#1.83#10.08
Error: Process completed with exit code 2.
```

@hauke @PolynomialDivision I think it should be fine to merge this, and it's also flagged in the latest uscan update at https://sdwalker.github.io/uscan/index.html. Do you see any issues?

**Comment by PolynomialDivision** [comment]
Can you rebase again on latest main?

**Comment by guidosarducci** [comment]
> Can you rebase again on latest main?

Of course, done now.

**Comment by guidosarducci** [comment]
Just rebased again. Could you please have a look? Thanks @PolynomialDivision @hauke

**Pull request merged**
