### PR TITLE
octeon: refresh 5.4 kernel and re-enable CAVIUM_CN63XXP1/EdgeRouter

### PR DESCRIPTION
**Pull request by adschm**
The symbol CONFIG_CAVIUM_CN63XXP1 was disabled during the bump to
    4.19 (see Fixes:) with the following reason:

      No supported hardware uses CN63XXP1 and it causes "slight decrease
      in performance"

    However, it later turned out that the edgerouter image needed it,
    which led to having the device disabled in [1].
    Still, dropping support of a device seems a harsh action for just
    removing a "slight" decrease in performance from the other devices.

    Thus, this enables CONFIG_CAVIUM_CN63XXP1 again, and essentially
    restores the situation present until (including) kernel 4.14 on
    this target.

    For OpenWrt as a platform, it seems more desirable to support all
    devices (and have them tested regularly via the snapshots) in this
    case.
    Users interested in maximum performance might still just remove
    the symbol again in their local build.

    [1] 3824fa26d256 ("octeon: disable edgerouter image")

    Fixes: 6c22545225cd ("target/octeon: Add Linux 4.19 support")

### CODE REVIEW

**Comment by adschm** [comment]
@lemmi @damex FYI.
Please test (best would be one device affected and one device not affected by the symbol).

I plan to backport this to 21.02 as well and would update the 5.10 patches accordingly.

**Comment by damex** [comment]
Why not add subtarget with that option enabled?

It is know for that option to hurt other boards that don't need it.

Even if we test it now and decide about performance being acceptable - it won't be the same for all devices and will eventually become a huge problem that we might not be able get rid of.

**Comment by adschm** [comment]
A subtarget would consume substantial additional resources for building and a least some additional efforts for maintenance. This has been declined on other cases with clearer indication and substantially more users.

**Comment by damex** [comment]
@adschm
`-mfix-cn63xxp1` is also needed for that soc.
https://sourceware.org/binutils/docs/as/MIPS-Options.html 

im sorry but i think it is a bad idea to introduce that option(s) globally and can't support your decision.

**Comment by adschm** [comment]
> im sorry but i think it is a bad idea to introduce that option(s) globally and can't support your decision.

We do not introduce this option, but fix a commit where it was removed under wrong assumptions, which then broke a device.
Also note that CONFIG_CAVIUM_CN63XXP1 was enabled in _all_ stable releases since LEDE 17.01 (didn't check older ones).

So, your argument would have to be what is gained by dropping support for edgerouter.
In that context, no data has been provided, so we don't actually know whether dropping support for edgerouter will have a benefit at all.

**Comment by adschm** [comment]
And, just to prevent tears at a later point:
Not that my point is even _if_ we find performance degradation (which we don't have evidence for), I would still set this option as it essentially provides support on more platforms.

**Comment by hauke** [comment]
This looks good to me.
Did someone measure how much slower this will be? I do not expect you to do this, but if someone wants to have an extra sub target this information would be helpful.

**Comment by Grommish** [comment]
@hauke I can't see there being ANY performance hits since the entire structure uses Octeonplus as the arch target.  I was told when I asked about an Octeon3 specific target it wasn't worth the build bot resources.

The question isn't how much this will degrade the existing targets, it's how much (if any) performance would be gained by breaking the octeonplus and octeon3 targets apart.

I make the distinction because no change in existing performance means there isn't a reason not to re-include it, where-as the second can be evaluated fairly easily if someone can help me derive a test suite to quantify performance like that.  My device has 3 slots, so I can do back to back testing if it comes to that *shrug*

**Comment by hauke** [comment]
I support this change and we should only consider performance problems if someone can provide numbers.

**Comment by lemmi** [comment]
Just did a quick on ER-4 and ERPro-8. Both are booting, network seems to work, didn't do any performance tests.

**Comment by adschm** [comment]
Thanks for testing, I merged this to master and the second patch only (without refresh) to 21.02.

**Comment by Grommish** [comment]
I know this is closed, but an update:

My device has THREE separate kernel slots and three data partitions, in addition to the VFAT partition that u-boot uses to load.

Because of this, I am able to do direct A/B comparisons with and without the patch.

This is based on the 5.10.20 Kernel, using the attached script (renamed to ,txt so I can attach), run from both RAM and from eMMC in order to test IO in both cases.  Results below.

The CN63xx Errata patches loses nearly 100Mb/sec of RAM throughput...

I'm not sure this trade-off is worth supporting an unmaintained device or not seeing what else could be done about this issue.  

Thoughts?

[vpsbench.txt](https://github.com/openwrt/openwrt/files/6096647/vpsbench.txt)

Without CN63xx Errata Patch - RAM

```
CPU model:  Cavium Octeon III V0.2
Number of cores: 2
BogoMIPS:  2000.00 BogoMIPS
Total amount of RAM: 965960 MB
Total amount of swap:  MB
System uptime:
I/O speed:  644 MB/s
Gzip 25MB: 13.09s
Download 100MB file: |****|
```

Without CN63xx Errata Patch - Disc

```
CPU model:  Cavium Octeon III V0.2
Number of cores: 2
BogoMIPS:  2000.00 BogoMIPS
Total amount of RAM: 965960 MB
Total amount of swap:  MB
System uptime:
I/O speed:  1.2 MB/s
Bzip 25MB: 14.23s
Download 100MB file: |****|
```

With CN63xx Errata Patch - RAM

```
CPU model:  Cavium Octeon III V0.2
Number of cores: 2
BogoMIPS:  2000.00 BogoMIPS
Total amount of RAM: 965976 MB
Total amount of swap:  MB
System uptime:
I/O speed:  561 MB/s
Gzip 25MB: 13.19s
Download 100MB file: |*****|
```

With CN63xx Errata Patch - Disc

```
CPU model:  Cavium Octeon III V0.2
Number of cores: 2
BogoMIPS:  2000.00 BogoMIPS
Total amount of RAM: 965976 MB
Total amount of swap:  MB
System uptime:
I/O speed:  1.5 MB/s
Gzip 25MB: 13.40s
Download 100MB file: |****|
```

**Comment by adschm** [comment]
Hmm, so
RAM I/O   decrease by 13 %
Disc I/O    increase by 25 %
iperf         decrease 5-7%

The disc i/o changes make me wonder how much entropy there is in that test?

**Comment by Grommish** [comment]
I'm in a position to A/B test whatever you need.  As I told others, this
was correcting an issue that shouldn't have been broken, but being broken
went unnoticed because there wasn't anyone at the time to know either way.
(IE, me, since ER/ERlite had no one actively maintaining them with the
devices when I started).

Damex has the knowledge of the octeon system; you were fixing an error
that, if it hadn't been broken, would have popped up sooner or later.

My concern is we correct the newly introduced issues for the devices that
are negatively impacted, or at least verify they are (which I'm trying to
do).

So, suggestions on how to do this?

**Comment by Grommish** [comment]
Also, keep in mind that my "disc" is emmc, which will be low speed, but I
wanted both IOps data points

**Pull request closed without merging**
