### PR TITLE
toolchain: add gcc 11 version

### PR DESCRIPTION
**Pull request by Ansuel**
Add gcc 11 version. Same patches of gcc 10.

Build tested on: ipq806x ipq807x
Run tested on: ipq806x ipq807x

I'm testing this from at least 2 month with no problem

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by aparcar** [comment]
Exciting, any advantage of using this?

**Comment by Ansuel** [comment]
Aside from some fix
New warning and improvement to their version of the static analyzer 
Anyway 
https://gcc.gnu.org/gcc-11/changes.html

**Comment by jospezial** [comment]
tested for MIPS lantiq, VGV7510KW22 (o2 Box 6431)

**Comment by Boos4721** [comment]
package/libs/elfutils build error, ipq40xx

**Comment by Ansuel** [comment]
@Boos4721 Error?

**Comment by Boos4721** [comment]
> @Boos4721 Error?

humm, wait sec

**Comment by neheb** [comment]
sounds like a version update is needed. 0.182 locally seems to compiles.

**Comment by anomeome** [comment]
Presumably the _sysupgrade_ image size increase is just alignment / packing. All the _mvebu_ targets I generate are 40960 bytes bigger than the same 10.x generated images.

**Comment by ptpt52** [comment]
build fails with package/libs/elfutils

`make V=s package/libs/elfutils/compile`

```
....
make --no-print-directory all-recursive
Making all in config
make[5]: Nothing to be done for 'all'.
Making all in m4
make[5]: Nothing to be done for 'all'.
Making all in lib
make[5]: Nothing to be done for 'all'.
Making all in libelf
make[5]: Nothing to be done for 'all'.
Making all in libcpu
make[5]: Nothing to be done for 'all'.
Making all in backends
make[5]: Nothing to be done for 'all'.
Making all in libebl
arm-openwrt-linux-muslgnueabi-gcc -D_GNU_SOURCE -DHAVE_CONFIG_H -DLOCALEDIR='"/usr/share/locale"' -I. -I..  -I. -I. -I../lib -I.. -I./../libelf -I./../libdw -I./../libasm -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.1.0_musl_eabi/usr/include -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.1.0_musl_eabi/include/fortify -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.1.0_musl_eabi/include -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libiconv-stub/include -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libintl-stub/include  -std=gnu99 -Wall -Wshadow -Wformat=2 -Wold-style-definition -Wstrict-prototypes -Wtrampolines -Wlogical-op -Wduplicated-cond -Wnull-dereference -Wimplicit-fallthrough=5 -Werror -Wunused -Wextra -Wstack-usage=262144    -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/elfutils-0.180=elfutils-0.180 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libiconv-stub/include -I/mnt/Data/Sources/openwrt/x-wrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libintl-stub/include -D_GNU_SOURCE -Wno-unused-result -Wno-format-nonliteral  -MT ebl_syscall_abi.o -MD -MP -MF .deps/ebl_syscall_abi.Tpo -c -o ebl_syscall_abi.o ebl_syscall_abi.c
ebl_syscall_abi.c:37:64: error: argument 5 of type 'int *' declared as a pointer [-Werror=array-parameter=]
   37 | ebl_syscall_abi (Ebl *ebl, int *sp, int *pc, int *callno, int *args)
      |                                                           ~~~~~^~~~
In file included from ./libeblP.h:34,
                 from ebl_syscall_abi.c:33:
./libebl.h:248:46: note: previously declared as an array 'int[6]'
  248 |                             int *callno, int args[6]);
      |                                          ~~~~^~~~~~~
cc1: all warnings being treated as errors
Makefile:529: recipe for target 'ebl_syscall_abi.o' failed
make[5]: *** [ebl_syscall_abi.o] Error 1
Makefile:499: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
Makefile:415: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/elfutils-0.180'
Makefile:98: recipe for target '/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/elfutils-0.180/.built' failed
make[2]: *** [/mnt/Data/Sources/openwrt/x-wrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/elfutils-0.180/.built] Error 2
make[2]: Leaving directory '/mnt/Data/Sources/openwrt/x-wrt/package/libs/elfutils'
time: package/libs/elfutils/compile#0.25#0.09#0.32
    ERROR: package/libs/elfutils failed to build.
package/Makefile:114: recipe for target 'package/libs/elfutils/compile' failed
make[1]: *** [package/libs/elfutils/compile] Error 1
make[1]: Leaving directory '/mnt/Data/Sources/openwrt/x-wrt'
/mnt/Data/Sources/openwrt/x-wrt/include/toplevel.mk:228: recipe for target 'package/libs/elfutils/compile' failed
make: *** [package/libs/elfutils/compile] Error 2
```

**Comment by neheb** [comment]
Works with https://github.com/neheb/openwrt/commit/35a46c0f3ca250194f3cc47620d5d1d1a25e154b

**Comment by Ansuel** [comment]
Nice! probably gcc added more check and warning and now it does fail

**Comment by neheb** [comment]
Some of the failures in the packages feed are being cleaned up: https://github.com/neheb/packages/commits/mangix

**Comment by Ansuel** [comment]
I also remember to have some compilation error but they were probably caused by using a dirty buildroot... 
Autofixed by clearing the affected package... but i need to check if i made some change to the makefile

**Comment by Gingernut1978** [comment]
A build for the Netgear WAC510 (ipq40xx) compiled without errors. Flashed and runs fine.

**Comment by Boos4721** [comment]
> A build for the Netgear WAC510 (ipq40xx) compiled without errors. Flashed and runs fine.

which source

**Comment by Gingernut1978** [comment]
> > A build for the Netgear WAC510 (ipq40xx) compiled without errors. Flashed and runs fine.
> 
> which source

Latest OpenWRT master with this PR merged.

**Comment by Boos4721** [comment]
> > > A build for the Netgear WAC510 (ipq40xx) compiled without errors. Flashed and runs fine.
> > 
> > 
> > which source
> 
> Latest OpenWRT master with this PR merged.

ok,thx

**Comment by anomeome** [comment]
The above error is occurring again with the kernel 5.10.49PR

**Comment by neheb** [comment]
For the elfutils issue: https://github.com/openwrt/openwrt/pull/4366

**Comment by anomeome** [comment]
Yep, working, thanks.

**Comment by hauke** [comment]
Thank you for the patch, I refreshed the patches and applied it to master.

**Pull request closed without merging**
