### PR TITLE
kernel: retrieve kernel tar hash from remote sha256sums

### PR DESCRIPTION
**Pull request by Ansuel**
Introduce a simple script to get the kernel tar hash from
the remote sha256sums file. This file contains the hash of each
tar and is updated with every new kernel version.
The kernel-version include will use this script by passing the
kernel version to get the hash if it's not defined.
Remove the hash with this new feature to make kernel update quicker.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by nbd168** [comment]
I don't think this is a good idea. In addition to simply checking integrity of the downloads, the hashes also protect against man-in-the-middle attacks. If you add a script that simply pulls the hashes from a plain text file without further verification, it considerably weakens the level of protection against such attacks.

**Comment by Ansuel** [comment]
@nbd168 The fact that we use https and curl that should verify the certificate shouldn't be enough to prevent this kind of attack?

**Comment by nbd168** [comment]
Unless curl also verifies certificate transparency info, I don't think it's enough. There are so many CAs out there that probably have questionable security, and it only takes the compromise of one of them to allow MITM attacks.

**Comment by dangowrt** [comment]
I usually verify the PGP signature, however, unlike many other cases kernel folks signs the *compressed* tarball, so you got to `xz -kd`, then `gpg -v` (and make sure local keyring with pubkey exists).

**Comment by Ansuel** [comment]
> I usually verify the PGP signature, however, unlike many other cases kernel folks signs the *compressed* tarball, so you got to `xz -kd`, then `gpg -v` (and make sure local keyring with pubkey exists).
> Just checked: There is `sha256sums.asc` as well.

So verify the sign would permit us to use the remote asc file instead of keeping the hash in the include makefile

**Comment by nbd168** [comment]
One other thing I noticed is that this leads to a $(shell) call that opens up a download connection on every include of that makefile. That will slow things down considerably. I really don't see the point in doing this at build time, why not just make a script that you can use to automatically fill in the correct hash in the makefile?

**Comment by aparcar** [comment]
Don't we already have something like FIXUP=1 for packages?

**Comment by Ansuel** [comment]
@aparcar but I assume it doesn't work for kernel... Also do we have the FIXUP documented in the wiki?

@nbd168 the script idea seems to be better...
What I don't like of the current kernel version-hash implementation is the fact that they are placed in the same include... (it's a very corner case but still annoying...) Let me explain.
I have the 5.15 pr open and I have to rebase it every time as the include kernel change with every kernel bump...

Can we change the implementation and have separate files/location to put the hash and the kernel version? (for example a directory or some files with a scheme that the include makefile will read and include as the kernel available versions?)
Something like kernel-5.10 kernel -5.4 kernel 5.15 similar to the config and the patch scheme. That would solve these rebase problem and make the kernel bump quicker with the addition of the get_hash script.

**Comment by aparcar** [comment]
> @aparcar but I assume it doesn't work for kernel... Also do we have the FIXUP documented in the wiki?

It doesn't but I thought it's a similar case.

> Let me explain.

I know the hassle, that why I implemented $(AUTORELEASE) :) Your suggestion sounds fine to me.

**Comment by Ansuel** [comment]
I'm currently testing my idea with the specific files for each kernel version. Lets see how it does work.
Wonder if that way we can just add support for the FIXUP in che kernel check build command

**Pull request closed without merging**
