### PR TITLE
ath10k-ct: switch to version 6.10

### PR DESCRIPTION
**Pull request by DragonBluep**
Unfortunately this version didn't fix the known kernel warning on ath10k wave2 devices:
```
[   30.925606] ------------[ cut here ]------------
[   30.936592] WARNING: CPU: 3 PID: 1211 at backports-6.11/net/mac80211/main.c:270 ieee80211_do_open+0x4f4/0x5ec [mac80211]
[   30.941365] Modules linked in: pppoe ppp_async nft_fib_inet nf_flow_table_inet ath10k_pci(O) ath10k_core(O) ath(O) pppox ppp_generic nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject nft_redir nft_quota nft_numgen nft_nat nft_masq nft_log nft_limit nft_hash nft_flow_offload nft_fib_ipv6 nft_fib_ipv4 nft_fib nft_ct nft_chain_nat nf_tables nf_nat nf_flow_table nf_conntrack mac80211(O) cfg80211(O) slhc nfnetlink nf_reject_ipv6 nf_reject_ipv4 nf_log_syslog nf_defrag_ipv6 nf_defrag_ipv4 mdio_netlink(O) libcrc32c hwmon crc_ccitt compat(O) sha512_arm ghash_arm_ce cmac leds_gpio xhci_plat_hcd xhci_pci xhci_hcd dwc3 dwc3_qcom gpio_button_hotplug(O) crc32c_generic
[   30.988392] CPU: 3 PID: 1211 Comm: hostapd Tainted: G           O       6.6.52 #0
[   31.010582] Hardware name: Generic DT based system
[   31.018224]  unwind_backtrace from show_stack+0x10/0x14
[   31.022907]  show_stack from dump_stack_lvl+0x40/0x4c
[   31.028028]  dump_stack_lvl from __warn+0x94/0xbc
[   31.033235]  __warn from warn_slowpath_fmt+0x158/0x15c
[   31.037922]  warn_slowpath_fmt from ieee80211_do_open+0x4f4/0x5ec [mac80211]
[   31.042969]  ieee80211_do_open [mac80211] from ieee80211_open+0x58/0x7c [mac80211]
[   31.050167]  ieee80211_open [mac80211] from __dev_open+0xc4/0x170
[   31.057545]  __dev_open from __dev_change_flags+0x168/0x1dc
[   31.063704]  __dev_change_flags from dev_change_flags+0x18/0x54
[   31.069085]  dev_change_flags from devinet_ioctl+0x5b4/0x7ec
[   31.074990]  devinet_ioctl from inet_ioctl+0x16c/0x268
[   31.080893]  inet_ioctl from sock_ioctl+0x240/0x60c
[   31.085840]  sock_ioctl from sys_ioctl+0x25c/0xc0c
[   31.090615]  sys_ioctl from ret_fast_syscall+0x0/0x54
[   31.095474] Exception stack(0xc112ffa8 to 0xc112fff0)
[   31.100601] ffa0:                   00000010 bef00858 00000010 00008914 bef00858 00000000
[   31.105641] ffc0: 00000010 bef00858 00000010 00000036 00000001 00000001 00000000 00000020
[   31.113796] ffe0: 005d3ea4 bef00718 00550cd8 b6f2466c
[   31.122001] ---[ end trace 0000000000000000 ]---
```

### CODE REVIEW

**Comment by danpawlik** [comment]
@DragonBluep try solution proposed here: https://github.com/openwrt/openwrt/issues/16396#issuecomment-2353790321

**Comment by DragonBluep** [comment]
Update: Solve patch conflicts.

**Comment by hauke** [comment]
Is ath10k-ct 6.10 working better or as good as the version 6.9? 

You kernel warning is concerning me a bit, do you also see this with version 6.9?

**Comment by DragonBluep** [comment]
> Is ath10k-ct 6.10 working better or as good as the version 6.9?

In the past week's testing, I don't see any different between 6.9 and 6.10.

> You kernel warning is concerning me a bit, do you also see this with version 6.9?

Yes. This warning was introduced by https://github.com/openwrt/openwrt/commit/1bfcc1ea8a78ae834055bf554aa45720c09ea919 several months ago. According to the analysis of @markmentovai in https://github.com/openwrt/openwrt/issues/15959#issuecomment-2259603978, this is a harmless warning.

**Pull request merged**
