### PR TITLE
build: add 'make kernel_xconfig' command

### PR DESCRIPTION
**Pull request by 532910**
This adds the kernel_xconfig make target.

Signed-off-by: Sergio E. Nemirowski <sergio@outerface.net>

### CODE REVIEW

**Comment by ynezz** [comment]
You're missing commit description.

**Comment by 532910** [comment]
Updated!

**Comment by 532910** [comment]
@ynezz ping

**Comment by ynezz** [comment]
You're missing commit description, see https://openwrt.org/submitting-patches for details

**Comment by 532910** [comment]
Oh, sorry. Should be fixed now.

**Comment by 532910** [comment]
I've fixed commit description, isn't it?

**Comment by adrianschmutzler** [comment]
Please squash your changes into a single, proper commit (and force-push them to your branch again to update this PR).

**Comment by 532910** [comment]
> Please squash your changes

Do you mean #3112, #3097 and #2878? So I should merge two another into this one and force-push, am I right?

**Comment by adrianschmutzler** [comment]
No, I mean the commits in this PR.
You currently have three commit here, two with the same name and one merge commit. Please squash them into one proper commit.

**Comment by 532910** [comment]
done

**Comment by 532910** [comment]
Who should approve this?

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by ynezz** [comment]
```
export MAKEFLAGS= ;make V=ssc -C target/linux xconfig
make[1]: Entering directory '/opt/devel/openwrt/openwrt.git/target/linux'
make[1]: *** No rule to make target 'xconfig'.  Stop.
make[1]: Leaving directory '/opt/devel/openwrt/openwrt.git/target/linux'
/opt/devel/openwrt/openwrt.git/include/toplevel.mk:181: recipe for target 'kernel_xconfig' failed
```

**Comment by 532910** [comment]
Hm, I thought I checked it.

Fixed, now it works.

**Pull request closed without merging**
