### PR TITLE
oxnas: clean and tidy up

### PR DESCRIPTION
**Pull request by mans0n**
All patches are just cosmetic.

- harmonize line breaks in ox820.mk
- use AddDepends in modules.mk
- remove duplicate config options
- sort kernel configs
- merge Pogoplug V3 DTS patches into one file
- use dt-bindings macros for GPIO
- rework 02_network

### CODE REVIEW

**Comment by dangowrt** [comment]
@jow- so now we got a problem because I pushed them into git.openwrt.org in the same minute...?

**Comment by mans0n** [comment]
@dangowrt
The wiki says snapshot hangs after reboot, and I found the same on Pogoplug Pro.
https://openwrt.org/toh/cloudengines/pogoplugpro
And then I found your patch, saying that you sent it because ox820 hangs on reboot.
https://patchwork.kernel.org/patch/10848419/
As the patch is also in OpenWrt repo, I'd expect it fixed some issues, but the reboot bug is still there. Do you know anything relevant to it?

**Comment by dangowrt** [comment]
There were/are two issues, one of them has been fixed:
- upstream kernel lacked support for SoC reboot, I added this driver
- now reboot works, SoC comes up into bootloader again after Linux performed reboot, but when loading/starting a Kernel >=4.4, the newly loaded system will not come up.
This issues still persists and could potentially be related to any of the built-in drivers or even CPU bringup code. People in the community have run a bunch of tests and found out that even when running OpenWrt 18.06 (which does reboot fine back into the same kernel), warm-rebooting and loading OpenWrt 19.07 over TFTP doesn't work. So it's some kind of re-initialization problem in recent kernels (probably since we switched to use the upstream oxnas platform code instead of the OpenWrt-improved version of Mahajun's codebase).

**Comment by mans0n** [comment]
Thanks for you explanation. So 18.06 does not have this bug? I'll look into that more.
I added "earlycon" to bootargs and the boot log shows some irq error. I'd like to post it on Flyspray, but I can't login there with error message `Error #23: User or group not enabled for login.`, so I'll do it here for now.
```
Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.4.24 (localhost) (gcc version 8.3.0 (OpenWrt GCC 8.3.0 r12563-5c2e409be7)) #0 SMP Fri Mar 13 14:51:30 2020
[    0.000000] CPU: ARMv6-compatible processor [410fb025] revision 5 (ARMv7), cr=00c5787d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Cloud Engines PogoPlug Pro
[    0.000000] earlycon: ns16550a0 at MMIO 0x44200000 (options '115200n8')
[    0.000000] printk: bootconsole [ns16550a0] enabled
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 64 MiB at 0x64000000
[    0.000000] percpu: Embedded 15 pages/cpu s29644 r8192 d23604 u61440
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32480
[    0.000000] Kernel command line: earlycon console=ttyS0,115200
[    0.000000] Bootloader command line (ignored): root=ubi0:rootfs ubi.mtd=2,512 rootfstype=ubifs console=ttyS0,115200 elevator=cfq mac_adr=0x00,0x30,0xe0,0x00,0x00,0x01 mem=128M poweroutage=yes
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 45164K/131072K available (5120K kernel code, 157K rwdata, 1228K rodata, 11264K init, 203K bss, 20372K reserved, 65536K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu:     RCU event tracing is enabled.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=16 to nr_cpu_ids=2.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] FPGA IRQ chip 0 "interrupt-controller" @ (ptrval), 32 irqs, parent IRQ: 16
[    0.000000] random: get_random_bytes called from start_kernel+0x2c0/0x4e8 with crng_init=0
[    0.000023] sched_clock: 24 bits at 390kHz, resolution 2560ns, wraps every 21474835200ns
[    0.016322] clocksource: oxnas_rps_clocksource_timer: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 19112603332 ns
[    0.026964] timer_oxnas_rps: Registered clocksource rate 390625Hz
[    0.033039] timer_oxnas_rps: Registered clock event rate 6250000Hz prescaler 0 period 62500
[    0.041510] GIC: PPI13 is secure or misconfigured
[    0.046236] GIC: PPI13 is secure or misconfigured
## the log deviates from that of normal boot from this point
[    0.050977] irq 16, desc: (ptrval), depth: 0, count: 0, unhandled: 0
[    0.057308] ->handle_irq():  (ptrval), fpga_irq_handle+0x0/0x84
[    0.063198] ->irq_data.chip(): (ptrval), 0xc13040f0
[    0.068044] ->action(): (ptrval)
[    0.071262] ->action->handler(): (ptrval), bad_chained_irq+0x0/0x58
[    0.077493]      IRQ_LEVEL set
[    0.080524]    IRQ_NOPROBE set
[    0.083558]  IRQ_NOREQUEST set
[    0.086589]   IRQ_NOTHREAD set
[    0.089625] unexpected IRQ trap at vector 10
## the kernel hangs
```

**Comment by dangowrt** [comment]
maybe @superna9999 or @kref got any idea what's going on?

**Comment by superna9999** [comment]
honestly no, seems a bad IRQ config from last boot stayed on reboot. The kref platform used it's own secondary irq driver, maybe the upstream one "fpga_irq" doesn't erase all the irq set at boot

**Comment by mans0n** [comment]
I could not find the root cause (yet), but at least I found the exact trigger: torvalds/linux@fbc87aa0f7c4
The reboot bug disappeared after I disabled the rps-timer node in dts.
This is not an ultimate solution, I guess the bug resides somewhere between irq, timer, and restart.

**Comment by jow-** [comment]
> @jow- so now we got a problem because I pushed them into git.openwrt.org in the same minute...?

I didn't actually merge anything, I believe this is just the Github ui being confused :) Maybe because the mirroring runs under my account.

**Comment by superna9999** [comment]
Interesting, maybe something is left enabled and the driver doesn’t disable it.

**Comment by adrianschmutzler** [comment]
> I didn't actually merge anything, I believe this is just the Github ui being confused :) Maybe because the mirroring runs under my account.

Ah, that might explain why only your merges look different.

**Comment by mans0n** [comment]
Still I cannot find where the irq error comes from, at least I crafted a nice patch which resolves the bug apparently.
```
--- a/drivers/irqchip/irq-versatile-fpga.c
+++ b/drivers/irqchip/irq-versatile-fpga.c
@@ -6,6 +6,7 @@
 #include <linux/irq.h>
 #include <linux/io.h>
 #include <linux/irqchip.h>
+#include <linux/irqchip/chained_irq.h>
 #include <linux/irqchip/versatile-fpga.h>
 #include <linux/irqdomain.h>
 #include <linux/module.h>
@@ -68,12 +69,15 @@ static void fpga_irq_unmask(struct irq_data *d)
 
 static void fpga_irq_handle(struct irq_desc *desc)
 {
+	struct irq_chip *chip = irq_desc_get_chip(desc);
 	struct fpga_irq_data *f = irq_desc_get_handler_data(desc);
 	u32 status = readl(f->base + IRQ_STATUS);
 
+	chained_irq_enter(chip, desc);
+
 	if (status == 0) {
 		do_bad_IRQ(desc);
-		return;
+		goto out;
 	}
 
 	do {
@@ -82,6 +86,9 @@ static void fpga_irq_handle(struct irq_desc *desc)
 		status &= ~(1 << irq);
 		generic_handle_irq(irq_find_mapping(f->domain, irq));
 	} while (status);
+
+ out:
+	chained_irq_exit(chip, desc);
 }
 
 /*
```
The error log did not disappear, but the kernel proceeded to boot anyway. Should I send the patch to the oxnas mailing list?

**Comment by superna9999** [comment]
Interesting, do you mean you still have :
[    0.057308] ->handle_irq():  (ptrval), fpga_irq_handle+0x0/0x84
[    0.063198] ->irq_data.chip(): (ptrval), 0xc13040f0
[    0.068044] ->action(): (ptrval)
[    0.071262] ->action->handler(): (ptrval), bad_chained_irq+0x0/0x58
[    0.077493]      IRQ_LEVEL set
[    0.080524]    IRQ_NOPROBE set
[    0.083558]  IRQ_NOREQUEST set
[    0.086589]   IRQ_NOTHREAD set
[    0.089625] unexpected IRQ trap at vector 10

?

**Comment by superna9999** [comment]
I think there is a issue with the timer irq, and I think the chained_irq_enter/chained_irq_exit are missing, all the other chained irq controllers uses these calls.

**Comment by mans0n** [comment]
> Interesting, do you mean you still have :
> [ 0.057308] ->handle_irq(): (ptrval), fpga_irq_handle+0x0/0x84
> [ 0.063198] ->irq_data.chip(): (ptrval), 0xc13040f0
> [ 0.068044] ->action(): (ptrval)
> [ 0.071262] ->action->handler(): (ptrval), bad_chained_irq+0x0/0x58
> [ 0.077493] IRQ_LEVEL set
> [ 0.080524] IRQ_NOPROBE set
> [ 0.083558] IRQ_NOREQUEST set
> [ 0.086589] IRQ_NOTHREAD set
> [ 0.089625] unexpected IRQ trap at vector 10
> 
> ?

Yes, precisely. So there might be another bug.

**Comment by mans0n** [comment]
> I think there is a issue with the timer irq, and I think the chained_irq_enter/chained_irq_exit are missing, all the other chained irq controllers uses these calls.

Yes, that is what my patch does.

**Comment by superna9999** [comment]
Please send it on the linux-oxnas mailig-list with the irqchip maintainers: linus.walleij@linaro.org tglx@linutronix.de jason@lakedaemon.net maz@kernel.org linux-arm-kernel@lists.infradead.org linux-kernel@vger.kernel.org linux-oxnas@groups.io

**Comment by mans0n** [comment]
@superna9999 Thank you so much for the help! It's my first time submitting a kernel patch, so I was worried if I'm doing right. I'll send the patch soon.

**Comment by dangowrt** [comment]
@mans0n are you planning to make a PR to OpenWrt adding the patch to target/linux/oxnas/patches-5.4/ for now as well?

**Comment by mans0n** [comment]
@dangowrt Okay, I'll do it in a few days in case of any feedback from there. Thanks for the patch tip!

**Comment by superna9999** [comment]
@mans0n you did perfectly well for a first time ! thanks, I didn't have the board in my hands to test anything...

**Comment by dangowrt** [comment]
I added the patch to openwrt master and 19.07
https://github.com/openwrt/openwrt/commit/67b04e767a0dcd01d39fe71eed9bdff7d5be72f0
https://github.com/openwrt/openwrt/commit/2bd9d2e08be4eb392b07fe42dbeea26a1e1cb7da
It already got included in current snapshots builds. I also don't have hardware for testing at hand right now...

**Comment by mans0n** [comment]
Thanks for taking care of it. I've run-tested the snapshot image and it looks good.
And now I think I found a root cause of the bug and how to resolve the irq error log.
Though it might not be important as it was, I'll try sending the patch when it's ready.

**Comment by superna9999** [comment]
Is it in the timer code ? The main difference with kref is that upstream we init both clkevent and clksource, while kref only enabled clocksource

**Comment by superna9999** [comment]
But since the kernel handle multiple clock events with different précisions it works fine, but maybe the timer reset is missing when soft rebooting

**Comment by dangowrt** [comment]
@superna9999 soft rebooting is handled by a downstream driver here:
https://github.com/openwrt/openwrt/blob/master/target/linux/oxnas/files/drivers/power/reset/oxnas-restart.c
(I tried to submit this upstream but never received any feedback afair)

**Comment by mans0n** [comment]
> Is it in the timer code ?

Maybe. I'm still not sure where the fix should go.
The root cause is that we do not disable the clkevent timer interrupt during restart.
There are several ways to handle it, it might be the restart driver, rps-timer or rps-irq.
My choice is to fix and use "clear-mask", but I'm not sure if it's really a *fix* or a feature change. Maybe we'd better fix the restart driver...

**Comment by superna9999** [comment]
@dangowrt my bad, I forgot it, maybe it’s my responsibility to push it, can you resubmit it ?

**Comment by superna9999** [comment]
@mans0n can you try ?
```
diff --git a/drivers/clocksource/timer-oxnas-rps.c b/drivers/clocksource/timer-oxnas-rps.c
index 56c0cc32d0ac..399196958330 100644
--- a/drivers/clocksource/timer-oxnas-rps.c
+++ b/drivers/clocksource/timer-oxnas-rps.c
@@ -90,6 +90,7 @@ static int oxnas_rps_timer_shutdown(struct clock_event_device *evt)
                container_of(evt, struct oxnas_rps_timer, clkevent);
 
        oxnas_rps_timer_config(rps, 0, 0);
+       writel_relaxed(0, rps->clkevt_base + TIMER_CLRINT_REG);
 
        return 0;
 }
```

**Comment by mans0n** [comment]
I tried, but it did not help. It seems oxnas_rps_timer_shutdown() is never called on soft reboot. (Actually, it is called only once during boot, and it's too late to prevent irq resend.)

**Comment by mans0n** [comment]
FYI this is my candidate patch.
```
diff --git a/drivers/irqchip/irq-versatile-fpga.c b/drivers/irqchip/irq-versatile-fpga.c
index 70e2cfff8175..f1386733d3bc 100644
--- a/drivers/irqchip/irq-versatile-fpga.c
+++ b/drivers/irqchip/irq-versatile-fpga.c
@@ -212,6 +212,9 @@ int __init fpga_irq_of_init(struct device_node *node,
 	if (of_property_read_u32(node, "valid-mask", &valid_mask))
 		valid_mask = 0;
 
+	writel(clear_mask, base + IRQ_ENABLE_CLEAR);
+	writel(clear_mask, base + FIQ_ENABLE_CLEAR);
+
 	/* Some chips are cascaded from a parent IRQ */
 	parent_irq = irq_of_parse_and_map(node, 0);
 	if (!parent_irq) {
@@ -221,9 +224,6 @@ int __init fpga_irq_of_init(struct device_node *node,
 
 	fpga_irq_init(base, node->name, 0, parent_irq, valid_mask, node);
 
-	writel(clear_mask, base + IRQ_ENABLE_CLEAR);
-	writel(clear_mask, base + FIQ_ENABLE_CLEAR);
-
 	/*
 	 * On Versatile AB/PB, some secondary interrupts have a direct
 	 * pass-thru to the primary controller for IRQs 20 and 22-31 which need
```

**Comment by superna9999** [comment]
Looks correct, it's ok to clear the state of the irq controller, it should have been done already

**Comment by mans0n** [comment]
Thanks for you review. I've just sent the patch to the mailing lists.

**Pull request merged**
