### PR TITLE
tools/libressl: update to 3.4.1

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by dhewg** [comment]
Nope, that's only suitable here! Tailored for OpenWrt as we're just building static libraries

**Comment by neheb** [comment]
I just tried it. tools/cmake failed. rpath is missing. My hunch was correct.

**Comment by neheb** [comment]
Those so called build issues are missing rpath.

```
--- a/tools/cmake/Makefile
+++ b/tools/cmake/Makefile
@@ -32,6 +32,8 @@ HOST_CONFIGURE_ARGS := \
        --prefix="$(STAGING_DIR_HOST)" \
        --generator=Ninja
 
+HOST_LDFLAGS += -Wl,-rpath,$(STAGING_DIR_HOST)/lib
+
 define Host/Compile/Default
        +$(NINJA) -C $(HOST_BUILD_DIR) $(1)
 endef

```

allows cmake to compile. Maybe these need to also be shared to avoid rpath hacks:

```
[I] mangix@ryzen ~/d/o/s/h/lib (mangix)> ls *.so
libcrypto.so  libexpat.so  libfakeroot-0.so  libfakeroot.so  libltdl.so  libssl.so  libtls.so  libzstd.so
```

**Comment by neheb** [comment]
> Ok, you're talking shared then ;) Yes, that'll be the nicest solution, there wouldn't be the need for either my libressl nor the u-boot patch. I smelled a can of worms, so admit to intentionally not going there ;)

OTOH that rpath line would need to be added to the uboot Makefile.

**Comment by neheb** [comment]
Removed shared libraries. Needing rpath hacks are too annoying.

**Comment by dhewg** [comment]
@aparcar since you assigned this to yourself:
The additional issue I raised was fixed with #4709, this bump works and fixes a recent u-boot, in fact #4676 is waiting for it :)
Anything else holding this up?

**Comment by aparcar** [comment]
Sorry I went hiking the last days and didn't do any progress on this. Feel free to take over

**Review by dhewg — APPROVED** [review]
np, and thanks, but what can I do about it ;)
Hitting "Approve" woot

**Comment by aparcar** [comment]
Tested and works for me, merged.

**Comment by Neustradamus** [comment]
@aparcar: Thanks for merging!

**Comment by dhewg** [comment]
Nice, thank you!

**Comment by Neustradamus** [comment]
@neheb: For your information, LibreSSL 3.4.2 has been released:
- https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.4.2-relnotes.txt
- https://www.libressl.org/

**Comment by eli-schwartz** [comment]
> 1. (The comments there say defaulting to --static isn't implemented, but meanwhile there's WantDefaultStatic, see the first link)

Implemented in https://github.com/pkgconf/pkgconf/commit/48dc665ae3efa3cd9907518dc449525eea8bb2c8 which I notice is the same day as the last comment in the buildroot thread.

**Pull request closed without merging**
