### PR TITLE
libevent2: make cmake use relative imported path

### PR DESCRIPTION
**Pull request by liudongmiao**
Upstream patch is from https://github.com/libevent/libevent/commit/81c6b8823c1b58d7837e827bb1098aa5f9e5956b

### CODE REVIEW

**Comment by robimarko** [comment]
Please add a PR description and a proper commit description as I have no idea why is this change required.

**Comment by liudongmiao** [comment]
@robimarko libevent 2.1.4 introduce cmake module, however, it use absolute path.

```cmake
find_package(Libevent 2.1.0 REQUIRED)
```

For example, it will find the libevent in the absolute path `CMAKE_INSTALL_PREFIX` (`/usr` in OpenWrt).
Then it would just fail:

```
-- Found libevent include directory: /builder/staging_dir/target-mips_24kc_musl/usr/include
-- Found libevent component: /builder/staging_dir/target-mips_24kc_musl/usr/lib/libevent_core.so
-- Found libevent component: /builder/staging_dir/target-mips_24kc_musl/usr/lib/libevent_extra.so
-- Found libevent component: /builder/staging_dir/target-mips_24kc_musl/usr/lib/libevent_openssl.so
-- Found libevent 2.1.12 in /builder/staging_dir/target-mips_24kc_musl/usr
CMake Error at /builder/staging_dir/target-mips_24kc_musl/usr/lib/cmake/libevent/LibeventTargets-shared.cmake:102 (message):
  The imported target "libevent::core" references the file

     "/usr/lib/libevent_core-2.1.so.7.0.1"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/builder/staging_dir/target-mips_24kc_musl/usr/lib/cmake/libevent/LibeventTargets-shared.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /builder/staging_dir/target-mips_24kc_musl/usr/lib/cmake/libevent/LibeventConfig.cmake:168 (include)
  CMakeLists.txt:34 (find_package)
```

This patch make `Libevent` in relative path, not the hardened `/usr`, then cmake can find it: (cmake source code) 
https://github.com/Kitware/CMake/blob/v3.28.3/Source/cmExportInstallFileGenerator.cxx#L221-L268

**Comment by robimarko** [comment]
I get it now, but please update the commit description so its clear to anybody that will look at the commit in future

**Comment by liudongmiao** [comment]
@robimarko Thanks, and update, and force push.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by liudongmiao** [comment]
Thanks!

**Pull request merged**
