### PR TITLE
kernel: bump 5.10 to 5.10.87

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

```
Build system: x86_64
Build-tested: bcm2711/RPi4B, ipq806x/R7800*
Run-tested: bcm2711/RPi4B, ipq806x/R7800*
```
*Had to revert 7f1edbd41295dff9f2127b169fbc086c0fb2c14e in order to build (binutils 2.37, https://bugs.openwrt.org/index.php?do=details&task_id=4149)

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Review by rsalvaterra — APPROVED** [review]
Looks good to me, thanks!

Run-tested:
ramips/mt7621 (Redmi AC2100)

**Comment by hauke** [comment]
Please use your real name in the Signed-off-by line.

**Comment by graysky2** [comment]
Dammit, sorry about that.  Fixed.

**Comment by hauke** [comment]
The author name is still wrong.

**Comment by graysky2** [comment]
> The author name is still wrong.

If I look at the [commit itself](https://github.com/openwrt/openwrt/commit/f94fdbf355ed4d28eea1b050c52caacce807ba88.patch), it's right there.  What am I missing :smile:

**Comment by graysky2** [comment]
I have been experiencing kernel oops with 5.10.84 that I did not experience under 5.10.83.  I just downgraded to 5.10.83 to verify.

This happened twice now since updating to 5.10.84:
```
[ 2688.031694] ------------[ cut here ]------------
[ 2688.036355] NETDEV WATCHDOG: eth0 (bcmgenet): transmit queue 0 timed out
[ 2688.043122] WARNING: CPU: 3 PID: 0 at net/sched/sch_generic.c:467 dev_watchdog+0x2c8/0x2d0
[ 2688.051388] Modules linked in: xt_connlimit pppoe ppp_async nf_conncount iptable_nat brcmfmac xt_state xt_nat xt_helper xt_conntrack xt_connmark xt_connbytes xt_REDIRECT xt_MASQUERADE xt_FLOWOFFLOAD xt_CT wireguard pppox ppp_generic nf_nat nf_flow_table nf_conntrack libchacha20poly1305 libblake2s ipt_REJECT chacha_neon cfg80211 ax88179_178a xt_time xt_tcpudp xt_tcpmss xt_statistic xt_recent xt_quota xt_pkttype xt_physdev xt_owner xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_ecn xt_dscp xt_comment xt_cgroup xt_addrtype xt_TCPMSS xt_LOG xt_HL xt_DSCP xt_CLASSIFY usbnet usbhid slhc sch_cake rtl8150 r8152 poly1305_neon nf_reject_ipv4 nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 macvlan libcurve25519_generic libchacha libblake2s_generic iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables hid_generic crc_ccitt compat brcmutil br_netfilter sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_tcindex cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred
[ 2688.051700]  act_gact snd_bcm2835(C) hid evdev nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 ifb ip6_udp_tunnel udp_tunnel veth snd_rawmidi snd_seq_device snd_pcm_oss snd_mixer_oss snd_hwdep snd_compress snd_pcm snd_timer snd soundcore nls_utf8 vfat fat nls_iso8859_1 nls_cp437
[ 2688.168412] CPU: 3 PID: 0 Comm: swapper/3 Tainted: G         C        5.10.84 #0
[ 2688.175807] Hardware name: Raspberry Pi 4 Model B Rev 1.1 (DT)
[ 2688.181642] pstate: 60400005 (nZCv daif +PAN -UAO -TCO BTYPE=--)
[ 2688.187651] pc : dev_watchdog+0x2c8/0x2d0
[ 2688.191659] lr : dev_watchdog+0x2c8/0x2d0
[ 2688.195664] sp : ffffffc010b43d70
[ 2688.198975] x29: ffffffc010b43d70 x28: 0000000000000140 
[ 2688.204291] x27: 00000000ffffffff x26: 0000000000000000 
[ 2688.209606] x25: 0000000000000003 x24: 0000000000000000 
[ 2688.214921] x23: ffffff8040c40480 x22: 0000000000000001 
[ 2688.220235] x21: ffffffc0109b6000 x20: ffffff8040c40000 
[ 2688.225549] x19: 0000000000000000 x18: 0000000000000116 
[ 2688.230863] x17: 0001de7b88ffd018 x16: 0000000000000009 
[ 2688.236177] x15: ffffffc0109c7790 x14: 0000000000000342 
[ 2688.241492] x13: 0000000000000116 x12: ffffffc010b43a48 
[ 2688.246806] x11: ffffffc010a1f790 x10: 00000000fffff000 
[ 2688.252120] x9 : ffffffc010a1f790 x8 : 0000000000000000 
[ 2688.257434] x7 : ffffffc0109c7790 x6 : 0000000000000008 
[ 2688.262748] x5 : 0000000000000003 x4 : 0000000000000000 
[ 2688.268061] x3 : ffffffc0109b8f8c x2 : 0000000000000004 
[ 2688.273375] x1 : 0000000000000005 x0 : 000000000000003c 
[ 2688.278690] Call trace:
[ 2688.281136]  dev_watchdog+0x2c8/0x2d0
[ 2688.284801]  call_timer_fn.constprop.0+0x24/0x80
[ 2688.289418]  __run_timers.part.0+0x240/0x280
[ 2688.293688]  run_timer_softirq+0x3c/0x74
[ 2688.297609]  _stext+0x124/0x290
[ 2688.300751]  irq_exit+0xa0/0xf0
[ 2688.303893]  __handle_domain_irq+0x80/0xe0
[ 2688.307992]  gic_handle_irq+0x78/0xa0
[ 2688.311652]  el1_irq+0xcc/0x180
[ 2688.314793]  arch_cpu_idle+0x18/0x30
[ 2688.318369]  default_idle_call+0x20/0x70
[ 2688.322292]  do_idle+0x21c/0x280
[ 2688.325518]  cpu_startup_entry+0x28/0x60
[ 2688.329440]  secondary_start_kernel+0x128/0x150
[ 2688.333968] ---[ end trace ddbc004725827c20 ]---
```

**Review by rsalvaterra — APPROVED** [review]
Also LGTM.

Run-tested:
ramips/mt7621 (Redmi AC2100)

**Comment by hauke** [comment]
I fixed the Author name and applied the first patch to master.
You can see the raw patch here for example: https://github.com/openwrt/openwrt/pull/4811.patch

**Comment by graysky2** [comment]
@hauke - Thanks, if I compare my original commit for the 5.10.83 PR to the one you just referenced, the `Signed-off-by:` lines are identical.

https://github.com/openwrt/openwrt/commit/a471f5ac6f0d035ce083e619793885ee0a5188fc.patch

**Comment by graysky2** [comment]
@hauke - I am trying 5.10.85 now to check for the kernel oops observed with 5.10.84.  Will report back after some days unless it is triggered more rapidly.

**Review by rsalvaterra — APPROVED** [review]
LGTM, thanks. I hope the RPi stabilises this time.

Run-tested:
ramips/mt7621 (Redmi AC2100)

**Comment by PerkelSimon** [comment]
everytimes I applied it I have that error:

`patch -p1 < 4811.patch
patching file include/kernel-version.mk
Hunk #1 FAILED at 7.
1 out of 1 hunk FAILED -- saving rejects to file include/kernel-version.mk.rej
patching file target/linux/bcm27xx/patches-5.10/950-0355-xhci-quirks-add-link-TRB-quirk-for-VL805.patch
patching file target/linux/bcm27xx/patches-5.10/950-0690-drm-Pass-the-full-state-to-connectors-atomic-functio.patch
patching file target/linux/bcm27xx/patches-5.10/950-0733-usb-xhci-workaround-for-bogus-SET_DEQ_PENDING-endpoi.patch
patching file target/linux/generic/backport-5.10/600-v5.12-net-extract-napi-poll-functionality-to-__napi_poll.patch
patching file target/linux/generic/backport-5.10/601-v5.12-net-implement-threaded-able-napi-poll-loop-support.patch
patching file target/linux/generic/backport-5.10/602-v5.12-net-add-sysfs-attribute-to-control-napi-threaded-mod.patch
patching file target/linux/generic/backport-5.10/603-v5.12-net-fix-race-between-napi-kthread-mode-and-busy-poll.patch
patching file target/linux/generic/backport-5.10/604-v5.12-net-fix-hangup-on-napi_disable-for-threaded-napi.patch
patching file target/linux/generic/pending-5.10/680-NET-skip-GRO-for-foreign-MAC-addresses.patch
patching file target/linux/mediatek/patches-5.10/331-mt7622-rfb1-enable-bmt.patch
patching file target/linux/mediatek/patches-5.10/410-bt-mtk-serial-fix.patch
patching file target/linux/mvebu/patches-5.10/702-net-next-ethernet-marvell-mvnetaMQPrioOffload.patch
patching file target/linux/mvebu/patches-5.10/703-net-next-ethernet-marvell-mvnetaMQPrioFlag.patch
patching file target/linux/mvebu/patches-5.10/704-net-next-ethernet-marvell-mvnetaMQPrioQueue.patch
patching file target/linux/mvebu/patches-5.10/705-net-next-ethernet-marvell-mvnetaMQPrioTCOffload.patch
patching file include/kernel-version.mk
Hunk #1 FAILED at 7.
1 out of 1 hunk FAILED -- saving rejects to file include/kernel-version.mk.rej
`

**Comment by graysky2** [comment]
And what does `include/kernel-version.mk.rej` look like?

**Comment by PerkelSimon** [comment]
> And what does `include/kernel-version.mk.rej` look like?

`
--- include/kernel-version.mk
+++ include/kernel-version.mk
@@ -7,10 +7,10 @@ ifdef CONFIG_TESTING_KERNEL
 endif
 
 LINUX_VERSION-5.4 = .162
-LINUX_VERSION-5.10 = .84
+LINUX_VERSION-5.10 = .85
 
 LINUX_KERNEL_HASH-5.4.162 = c12d72ddaac78189305a5e98825295ecb02282970033b052276035e83189e25b
-LINUX_KERNEL_HASH-5.10.84 = 6e96271d72dd106c4bd83931ca16fda622413b34c5649e2916116c38c12e233d
+LINUX_KERNEL_HASH-5.10.85 = ba89162605ac447db8953c29f649b64d16aff7de8145e2db30d759e5476b19ac
 
 remove_uri_prefix=$(subst git://,,$(subst http://,,$(subst https://,,$(1))))
 sanitize_uri=$(call qstrip,$(subst @,_,$(subst :,_,$(subst .,_,$(subst -,_,$(subst /,_,$(1)))))))`

**Comment by graysky2** [comment]
And you just downloaded https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/4811.patch and applied that master?  Should work without issue.

```
% patch -Np1 -i ok.patch 
patching file include/kernel-version.mk
patching file target/linux/bcm27xx/patches-5.10/950-0355-xhci-quirks-add-link-TRB-quirk-for-VL805.patch
patching file target/linux/bcm27xx/patches-5.10/950-0690-drm-Pass-the-full-state-to-connectors-atomic-functio.patch
patching file target/linux/bcm27xx/patches-5.10/950-0733-usb-xhci-workaround-for-bogus-SET_DEQ_PENDING-endpoi.patch
patching file target/linux/generic/backport-5.10/600-v5.12-net-extract-napi-poll-functionality-to-__napi_poll.patch
patching file target/linux/generic/backport-5.10/601-v5.12-net-implement-threaded-able-napi-poll-loop-support.patch
patching file target/linux/generic/backport-5.10/602-v5.12-net-add-sysfs-attribute-to-control-napi-threaded-mod.patch
patching file target/linux/generic/backport-5.10/603-v5.12-net-fix-race-between-napi-kthread-mode-and-busy-poll.patch
patching file target/linux/generic/backport-5.10/604-v5.12-net-fix-hangup-on-napi_disable-for-threaded-napi.patch
patching file target/linux/generic/pending-5.10/680-NET-skip-GRO-for-foreign-MAC-addresses.patch
patching file target/linux/mediatek/patches-5.10/331-mt7622-rfb1-enable-bmt.patch
patching file target/linux/mediatek/patches-5.10/410-bt-mtk-serial-fix.patch
patching file target/linux/mvebu/patches-5.10/702-net-next-ethernet-marvell-mvnetaMQPrioOffload.patch
patching file target/linux/mvebu/patches-5.10/703-net-next-ethernet-marvell-mvnetaMQPrioFlag.patch
patching file target/linux/mvebu/patches-5.10/704-net-next-ethernet-marvell-mvnetaMQPrioQueue.patch
patching file target/linux/mvebu/patches-5.10/705-net-next-ethernet-marvell-mvnetaMQPrioTCOffload.patch
patching file include/kernel-version.mk
patching file target/linux/bcm27xx/patches-5.10/950-0139-xhci-implement-xhci_fixup_endpoint-for-interval-adju.patch
patching file target/linux/bcm27xx/patches-5.10/950-0151-hid-usb-Add-device-quirks-for-Freeway-Airmouse-T3-an.patch
patching file target/linux/bcm27xx/patches-5.10/950-0249-kbuild-Disable-gcc-plugins.patch
patching file target/linux/bcm27xx/patches-5.10/950-0323-media-i2c-Add-driver-for-Sony-IMX477-sensor.patch
patching file target/linux/bcm27xx/patches-5.10/950-0657-Documentation-devicetree-Add-documentation-for-imx37.patch
patching file target/linux/bcm27xx/patches-5.10/950-0733-usb-xhci-workaround-for-bogus-SET_DEQ_PENDING-endpoi.patch
patching file target/linux/generic/backport-5.10/610-v5.13-57-netfilter-flowtable-Set-offload-timeouts-according-t.patch
patching file target/linux/generic/backport-5.10/732-net-next-1-of-net-pass-the-dst-buffer-to-of_get_mac_address.patch
patching file target/linux/generic/pending-5.10/834-ledtrig-libata.patch
patching file target/linux/oxnas/patches-5.10/999-libata-hacks.patch
patching file target/linux/realtek/patches-5.10/008-5.17-watchdog-add-realtek-otto-watchdog-timer.patch
```

**Comment by PerkelSimon** [comment]
> And you just downloaded https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/4811.patch and applied that master? Should work without issue.
> 
> ```
> % patch -Np1 -i ok.patch 
> patching file include/kernel-version.mk
> patching file target/linux/bcm27xx/patches-5.10/950-0355-xhci-quirks-add-link-TRB-quirk-for-VL805.patch
> patching file target/linux/bcm27xx/patches-5.10/950-0690-drm-Pass-the-full-state-to-connectors-atomic-functio.patch
> patching file target/linux/bcm27xx/patches-5.10/950-0733-usb-xhci-workaround-for-bogus-SET_DEQ_PENDING-endpoi.patch
> patching file target/linux/generic/backport-5.10/600-v5.12-net-extract-napi-poll-functionality-to-__napi_poll.patch
> patching file target/linux/generic/backport-5.10/601-v5.12-net-implement-threaded-able-napi-poll-loop-support.patch
> patching file target/linux/generic/backport-5.10/602-v5.12-net-add-sysfs-attribute-to-control-napi-threaded-mod.patch
> patching file target/linux/generic/backport-5.10/603-v5.12-net-fix-race-between-napi-kthread-mode-and-busy-poll.patch
> patching file target/linux/generic/backport-5.10/604-v5.12-net-fix-hangup-on-napi_disable-for-threaded-napi.patch
> patching file target/linux/generic/pending-5.10/680-NET-skip-GRO-for-foreign-MAC-addresses.patch
> patching file target/linux/mediatek/patches-5.10/331-mt7622-rfb1-enable-bmt.patch
> patching file target/linux/mediatek/patches-5.10/410-bt-mtk-serial-fix.patch
> patching file target/linux/mvebu/patches-5.10/702-net-next-ethernet-marvell-mvnetaMQPrioOffload.patch
> patching file target/linux/mvebu/patches-5.10/703-net-next-ethernet-marvell-mvnetaMQPrioFlag.patch
> patching file target/linux/mvebu/patches-5.10/704-net-next-ethernet-marvell-mvnetaMQPrioQueue.patch
> patching file target/linux/mvebu/patches-5.10/705-net-next-ethernet-marvell-mvnetaMQPrioTCOffload.patch
> patching file include/kernel-version.mk
> patching file target/linux/bcm27xx/patches-5.10/950-0139-xhci-implement-xhci_fixup_endpoint-for-interval-adju.patch
> patching file target/linux/bcm27xx/patches-5.10/950-0151-hid-usb-Add-device-quirks-for-Freeway-Airmouse-T3-an.patch
> patching file target/linux/bcm27xx/patches-5.10/950-0249-kbuild-Disable-gcc-plugins.patch
> patching file target/linux/bcm27xx/patches-5.10/950-0323-media-i2c-Add-driver-for-Sony-IMX477-sensor.patch
> patching file target/linux/bcm27xx/patches-5.10/950-0657-Documentation-devicetree-Add-documentation-for-imx37.patch
> patching file target/linux/bcm27xx/patches-5.10/950-0733-usb-xhci-workaround-for-bogus-SET_DEQ_PENDING-endpoi.patch
> patching file target/linux/generic/backport-5.10/610-v5.13-57-netfilter-flowtable-Set-offload-timeouts-according-t.patch
> patching file target/linux/generic/backport-5.10/732-net-next-1-of-net-pass-the-dst-buffer-to-of_get_mac_address.patch
> patching file target/linux/generic/pending-5.10/834-ledtrig-libata.patch
> patching file target/linux/oxnas/patches-5.10/999-libata-hacks.patch
> patching file target/linux/realtek/patches-5.10/008-5.17-watchdog-add-realtek-otto-watchdog-timer.patch
> % echo $?
> 0
> ```

not this one, that one is 5.10.84, not 5.10.85
and you applied that patch with which code?

**Comment by PerkelSimon** [comment]
even with your link, same error

```
patch -p1 < 4811.patch
patching file include/kernel-version.mk
Hunk #1 FAILED at 7.
1 out of 1 hunk FAILED -- saving rejects to file include/kernel-version.mk.rej
patching file target/linux/bcm27xx/patches-5.10/950-0355-xhci-quirks-add-link-TRB-quirk-for-VL805.patch
patching file target/linux/bcm27xx/patches-5.10/950-0690-drm-Pass-the-full-state-to-connectors-atomic-functio.patch
patching file target/linux/bcm27xx/patches-5.10/950-0733-usb-xhci-workaround-for-bogus-SET_DEQ_PENDING-endpoi.patch
patching file target/linux/generic/backport-5.10/600-v5.12-net-extract-napi-poll-functionality-to-__napi_poll.patch
patching file target/linux/generic/backport-5.10/601-v5.12-net-implement-threaded-able-napi-poll-loop-support.patch
patching file target/linux/generic/backport-5.10/602-v5.12-net-add-sysfs-attribute-to-control-napi-threaded-mod.patch
patching file target/linux/generic/backport-5.10/603-v5.12-net-fix-race-between-napi-kthread-mode-and-busy-poll.patch
patching file target/linux/generic/backport-5.10/604-v5.12-net-fix-hangup-on-napi_disable-for-threaded-napi.patch
patching file target/linux/generic/pending-5.10/680-NET-skip-GRO-for-foreign-MAC-addresses.patch
patching file target/linux/mediatek/patches-5.10/331-mt7622-rfb1-enable-bmt.patch
patching file target/linux/mediatek/patches-5.10/410-bt-mtk-serial-fix.patch
patching file target/linux/mvebu/patches-5.10/702-net-next-ethernet-marvell-mvnetaMQPrioOffload.patch
patching file target/linux/mvebu/patches-5.10/703-net-next-ethernet-marvell-mvnetaMQPrioFlag.patch
patching file target/linux/mvebu/patches-5.10/704-net-next-ethernet-marvell-mvnetaMQPrioQueue.patch
patching file target/linux/mvebu/patches-5.10/705-net-next-ethernet-marvell-mvnetaMQPrioTCOffload.patch
patching file include/kernel-version.mk
Hunk #1 FAILED at 7.
1 out of 1 hunk FAILED -- saving rejects to file include/kernel-version.mk.rej

```

**Comment by graysky2** [comment]
What does `git pull --rebase` do?  Guessing your copy is not in sync with master.

**Comment by PerkelSimon** [comment]
> What does `git pull --rebase` do? Guessing your copy is not in sync with master.

I have the 5.10 build from acwifidude, NSS on r7800, rebase is ok.

**Comment by graysky2** [comment]
As I test switch to master then make a branch and try it there.  Bet you it works.

**Comment by graysky2** [comment]
@hauke - I have been on 5.10.85 for 2+ days now without that kernel oops.  Probably OK to pull into master from that prespective.

**Comment by Ninjanoir78** [comment]
> As I test switch to master then make a branch and try it there. Bet you it works.

Yep thanks
I got it

**Comment by PerkelSimon** [comment]
for the 5.10.86 kernel patch, this is what I need to download? ; 

[https://github.com/openwrt/openwrt/commit/0a5e685892309dcdf9c2b644ef4eddc2313269da.patch](url)

cause still problem with Hunk failed at #7

**Comment by anomeome** [comment]
just add .patch to the PR URL, you need all three commits.

**Comment by hauke** [comment]
Thank you for the patch, I applied them to master in 187c8f9153bee5deb8a1163ba2abcbc7bc9e229c, 43c0a12665eb22e7fc0ebbde47173a990291a40e, 002424e5ae49867e434fd80db66e9eebcda67fc9 and eabb4a5c5da6931969d7c38a88884502e6fa2039

**Pull request closed without merging**
