### PR TITLE
sunxi: Add THS and DVFS for selected sunxi targets

### PR DESCRIPTION
**Pull request by Menion2k**
This patch add thermal zone and dynamic voltage-frequency shift support to a selected number of Allwinner H3/H5 boards. The code is taken from the official WIP branch in megous fork. It is the official code of the sunxi mainlining effort for THS and DVFS.
Patch content is:

THS and DVFS code is WIP merge of the patchset from megous/linux branch ths-4-14

Compile in kernel support for the voltage regulators SY8106A
Compile in  kernel support for SUN8I_THS

Signed-off-by: Antonio Silverio <menion@gmail.com>

This is a PR, same of second patch of #825 as required by @wigyori

### CODE REVIEW

**Comment by blogic** [comment]
@Menion2k hi, the patch has formal issues. please
*) add a proper subject prefix "sunxi:"
*) add a better subject "fix voltage regulator on board XYZ" or similar
*) write a proper description text

**Comment by Menion2k** [comment]
@wigyori is there anything stopping this #PR?

**Comment by Menion2k** [comment]
Hi again
Honestly I don't know what is going on with this PR. Have you considered it outdated because of the nex moving to 4.19?

**Comment by diizzyy** [comment]
@Menion2k 
You haven't addressed the issues mentioned which are showstoppers. At this point you're probably better off looking at 4.19 but I'd advice you to wait until it's in tree. As far as I can tell H5 doesn't have support in mainline 4.19. You can view further discussion about the sunxi target here:
https://lists.openwrt.org/pipermail/openwrt-devel/2018-December/015252.html (last mail in thread)

**Comment by Menion2k** [comment]
Actually I thought that I have implemented the comments while ago, since I received no different feedbacks... As you pointed out in the linked mail thread the thermal and voltage throttling is very important for sunxi targets and my PR is 5 months old, meaning that we could have had it 5 months ago...
4.19 mainline supports H5 and cpufreq has been added in 4.18.
So I think this PR is unusefull now, unless someone wants to backport it. 
As comments, I honestly don't follow the way the PR are prioritized and managed, especially here in girhub. I have also tried to get feedbacks in IRC, but with zero answer

**Comment by diizzyy** [comment]
Patches/PRs gets more or less gets prioritized based on core dev(s) interest otherwise progress have a tendency to move at glacial pace if at all. You also have to take into account that it's more or less volunteer work so it's all "best effort". It's nothing new and has been discussed before unfortunately without any progress to my knowledge. GitHub is also "less preferred/prioritized" by some devs compared to patchwork which is a bit of a pity if you ask me.

Anyway, back to topic...
Do you have any idea why Armbian have a lot of patches for H3 and H5 and if we should import any?

**Comment by Menion2k** [comment]
Normally Armbian has sunxi mainline effort projects wip patch they implement in order to help testing. Nowadays with kernel 4.19 when it comes to everything which is older than H6, I don't think there is anything really needed from armbian, where most of the patch concerns H6 and newer SoC and multimedia (Cedrus, codecs, ecc...)

**Comment by diizzyy** [comment]
@Menion2k 
I think we can close this and focus on 4.19 instead

**Comment by Menion2k** [comment]
Yes, too late for 4.14

**Comment by ynezz** [comment]
Sorry, this simply looks like, that it's not in ideal shape for a merge, that's maybe why nobody has touched it yet. To increase your chances for a merge (and mainly making the review easier), please try to:

* use only upstream Linux commits (and backports) ([example](https://github.com/openwrt/openwrt/commit/e24983e710dd7a22909e26af1ad8ee8d027b5c71)), always include kernel version in the patch filename. In other words, patches from other sources need very good reason to be in the tree(fixing serious issue for example) as it's pretty hard to do kernel version bumps otherwise, in other words, such WIP etc. patches are then a maintenance nightmare

* use `git format-patch -1 <git commit hash>` and put that complete file (including the commit message) to the repository

* don't try to make one big commit like you have it now, try to split it to smaller logical parts (kernel config, DTS etc.), with proper commit subject and commit message/description (usually provide answer to Why? do you need that change)

BTW #830 is trying to provide similar functionality, right? Just guessing from the content of the kernel patches.

**Comment by ynezz** [comment]
Please re-open the PR once you find a time (or interest) to work on this.

**Pull request closed without merging**
