### PR TITLE
ksmbd: add

### PR DESCRIPTION
**Pull request by neheb**
continuation of https://github.com/openwrt/openwrt/pull/4866

@hauke I seem to get this error despite selecting the kmod:

```
ERROR: modpost: "sprint_oid" [/home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/ksmbd-3.4.3/ksmbd.ko] undefined!
make[4]: *** [scripts/Makefile.modpost:124: /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/ksmbd-3.4.3/Module.symvers] Error 1
make[4]: *** Deleting file '/home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/ksmbd-3.4.3/Module.symvers'
make[3]: *** [Makefile:1726: modules] Error 2
make[3]: Leaving directory '/home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-5.10.96'
make[2]: *** [Makefile:76: /home/mangix/devstuff/test-openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/ksmbd-3.4.3/.built] Error 2
make[2]: Leaving directory '/home/mangix/devstuff/test-openwrt/package/kernel/ksmbd'
time: package/kernel/ksmbd/compile#13.44#1.36#0.00
    ERROR: package/kernel/ksmbd failed to build.
make[1]: *** [package/Makefile:116: package/kernel/ksmbd/compile] Error 1
make[1]: Leaving directory '/home/mangix/devstuff/test-openwrt'
make: *** [/home/mangix/devstuff/test-openwrt/include/toplevel.mk:230: package/ksmbd/compile] Error 2

```

edit: caused by a typo. Fixed now.

### CODE REVIEW

**Comment by mans0n** [comment]
I think you could somehow restore the previous branch. :(
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes#do_not_multi-post_or_re-post_prs

**Comment by neheb** [comment]
The previous branch is now used for a different purpose. I'd rather not complicate things.

**Review by chunkeey — APPROVED** [review]
> These options will be used for ksmbd. Once kernel 5.15 makes it in, this
patch can go away.

probably not. Though, I think this is the right way to do it for 5.15+ too.

In your case with 5.10. Both [CONFIG_OID](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/lib/Kconfig?h=v5.15#n607) and  [CONFIG_ASN1](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/init/Kconfig?h=v5.15#n2355) don't have a prompt message. So they can't be properly selected by the openwrt's kconfig scripts with out this patch.

But what are we going to do?! 

In 5.15 [CONFIG_FS_CIFS](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/cifs/Kconfig?h=v5.15#n19) will also depend on ASN1 and OID_REGISTRY.
So a patch like this is needed in the foreseeable future.

**Comment by neheb** [comment]
> > These options will be used for ksmbd. Once kernel 5.15 makes it in, this
> > patch can go away.
> 
> probably not. Though, I think this is the right way to do it for 5.15+ too.
> 
> In your case with 5.10. Both [CONFIG_OID](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/lib/Kconfig?h=v5.15#n607) and [CONFIG_ASN1](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/init/Kconfig?h=v5.15#n2355) don't have a prompt message. So they can't be properly selected by the openwrt's kconfig scripts with out this patch.
> 
> But what are we going to do?!
> 
> In 5.15 [CONFIG_FS_CIFS](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/cifs/Kconfig?h=v5.15#n19) will also depend on ASN1 and OID_REGISTRY. So a patch like this is needed in the foreseeable future.

@hauke implied otherwise in the other thread. I'll test with the kernel 5.15 bump when it becomes available.

**Comment by chunkeey** [comment]
And.... I c&p the v5.15 Kconfigs instead of the v5.10. Well, here are the v5.10 [CONFIG_OID](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/lib/Kconfig?h=v5.10#n587) and [CONFIG_ASN1](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/init/Kconfig?h=v5.10#n2335). From what I can tell just the line numbers changed. 

As for CIFS: CIFS in v5.10 didn't select CONFIG_ASN1 and CONFIG_OID_REGISTRY.
This was changed in v5.13-rc7 by this patch: https://github.com/torvalds/linux/commit/0475c3655e6eb

**Comment by chunkeey** [comment]
Ok, I've merged this. We'll need it soon. Could you update packages?

**Comment by neheb** [comment]
@chunkeey I don't know if version 3.44 is good. @pesa1234 was having issues with it. It's fixed in master but a new release needs to be cut.

**Comment by pesa1234** [comment]
Yes, 3.4.4 have an issue with thunar mount. 
https://github.com/cifsd-team/ksmbd/issues/554

And it is necessary to comment these lines
```
#smb2 max read = 64K
#smb2 max write = 64K
#smb2 max trans = 64K
```
 from standard smb.conf.template to solve this issue
https://github.com/cifsd-team/ksmbd/issues/555

**Pull request closed without merging**
