### PR TITLE
realtek: align kernel config with upstream

### PR DESCRIPTION
**Pull request by plappermaul**
Since the start of the Realtek target OpenWrt works with RTL83XX as the target architecture. Upstream is using MACH_REALTEK_RTL instead. To simplify further development align that.

### CODE REVIEW

**Comment by plappermaul** [comment]
@SimonFischer04 @GoetzGoerisch @evs93 : Once again you can help with testing & review.

**Comment by evs93** [comment]
Out of laziness because JG926A support isn't merged yet I hope JG922A (RTL8380) and JG927A (RTL8393) is sufficient? Please let me know if you also require confirmation on JG926A (RTL8382M) and/or any output you require.

**Comment by plappermaul** [comment]
Hi, I'm thankful for each test (regardeless of the device). The more positive reviews the faster we can merge.

**Comment by evs93** [comment]
JG922A built and booted fine. Link to it and ssh/luci worked fine too. Haven't done any bandwidth testing but I think given this is just renaming \#defines I think that should be sufficient testing?

I read the change set and this change also is deleting a couple patches? Are the patches upstream now, so they're not required? If you could please elaborate on the alignment, is it related to `MACH_REALTEK_RTL` etc?

Working on building for JG927A now.

**Comment by plappermaul** [comment]
Thanks. The deleted patches are those that only convert MACH_REALTEK_RTL upstream define to RTL83XX OpenWrt define. Thus they are obsolete.

**Comment by evs93** [comment]
Awesome thanks. Yeah probably should have clicked and loaded the diff on github haha.

Anyway JG927A built fine, and link to it / luci / ssh worked fine. Will do the approval thing through github now.

**Review by evs93 — APPROVED** [review]
Appear to be no issues on JG922A (RTL8380) and JG927A (RTL8393). I approve this change.

**Review by GoetzGoerisch — APPROVED** [review]
Run-tested: JG924A (HPE 1920-24G)

Thank you!

**Comment by hauke** [comment]
Looks good. The resulting kernel configuration before and after this PR only contains the expected changes:
```
--- build_dir/target-mips_4kec_musl/linux-realtek_rtl838x/linux-6.6.61/.config
+++ build_dir/target-mips_4kec_musl/linux-realtek_rtl838x/linux-6.6.61/.config
@@ -247,7 +247,7 @@
 # CONFIG_MACH_PIC32 is not set
 # CONFIG_MACH_NINTENDO64 is not set
 # CONFIG_RALINK is not set
-CONFIG_MACH_REALTEK_RTL=y
+# CONFIG_MACH_REALTEK_RTL is not set
 # CONFIG_SGI_IP22 is not set
 # CONFIG_SGI_IP27 is not set
 # CONFIG_SGI_IP28 is not set
@@ -263,6 +263,7 @@
 # CONFIG_MACH_TX49XX is not set
 # CONFIG_MIKROTIK_RB532 is not set
 # CONFIG_CAVIUM_OCTEON_SOC is not set
+CONFIG_RTL83XX=y
 CONFIG_RTL838X=y
 # CONFIG_RTL839X is not set
 # CONFIG_RTL930X is not set
```

**Comment by plappermaul** [comment]
Thank you

**Comment by SimonFischer04** [comment]
> @SimonFischer04 @GoetzGoerisch @evs93 : Once again you can help with testing & review.

Sorry, only got time to test now:

Works like before: (1250)

**Pull request merged**
