### PR TITLE
ath10k-firmware: Update QCA9984 firmware version

### PR DESCRIPTION
**Pull request by robhancock**
This appears to fix some fairly frequent 5GHz connection dropouts on a
Netgear R7800.

Signed-off-by: Robert Hancock <hancockrwd@gmail.com>

### CODE REVIEW

**Comment by pkgadd** [comment]
Confirmed to be working on the ZyXEL NBG6817 (QCA9984), although I don't notice much of a difference (in a good sense). 

Just be aware that there are quite major staged changes upcoming (https://git.openwrt.org/?p=openwrt/staging/blogic.git;a=shortlog;h=refs/heads/mac80211).

**Comment by diizzyy** [comment]
I guess you're referring to this?
https://git.openwrt.org/?p=openwrt/staging/blogic.git;a=commit;h=f9ccc8f64670e3e15b160cffb19f1ef1a8519e97
That commit needs to be a lot more verbose about the decision

**Comment by bobafetthotmail** [comment]
@blogic do you have a better explanation for that?

**Comment by pkgadd** [comment]
Hi @diizzyy I'm more referring to https://git.openwrt.org/?p=openwrt/staging/blogic.git;a=commitdiff;h=54d15e8221fabc1e1e3d4435ebfb5cbbe8492acd and https://git.openwrt.org/?p=openwrt/staging/blogic.git;a=commitdiff;h=07d3d65f18ed443e3c66cbdc20a45d397e2f2caa as I don't expect the switch to ath10k-ct to be as drastic as in your quoted commit (changing the default, perhaps - completely removing upstream ath10k support feels unlikely).

**Comment by jcadduono** [comment]
If anyone is testing this out on current master, you will need to make these changes as well:

```
diff --git a/package/firmware/ath10k-firmware/Makefile b/package/firmware/ath10k-firmware/Makefile
index 256f988d10..0a4ae24f8c 100644
--- a/package/firmware/ath10k-firmware/Makefile
+++ b/package/firmware/ath10k-firmware/Makefile
@@ -611,7 +611,7 @@ endef
 #$(eval $(call BuildPackage,ath10k-firmware-qca988x))
 #$(eval $(call BuildPackage,ath10k-firmware-qca99x0))
 #$(eval $(call BuildPackage,ath10k-firmware-qca6174))
-#$(eval $(call BuildPackage,ath10k-firmware-qca9984))
+$(eval $(call BuildPackage,ath10k-firmware-qca9984))
 #$(eval $(call BuildPackage,ath10k-firmware-qca4019))
 
 $(eval $(call BuildPackage,ath10k-firmware-qca9887-ct))
diff --git a/package/firmware/linux-firmware/qca_ath10k.mk b/package/firmware/linux-firmware/qca_ath10k.mk
index a7c5b13b84..5301836efd 100644
--- a/package/firmware/linux-firmware/qca_ath10k.mk
+++ b/package/firmware/linux-firmware/qca_ath10k.mk
@@ -101,5 +101,5 @@ define Package/ath10k-firmware-qca9984/install
                $(PKG_BUILD_DIR)/ath10k/QCA9984/hw1.0/firmware-5.bin \
                $(1)/lib/firmware/ath10k/QCA9984/hw1.0/firmware-5.bin
 endef
-$(eval $(call BuildPackage,ath10k-firmware-qca9984))
+#$(eval $(call BuildPackage,ath10k-firmware-qca9984))
```

This is because a recent commit changed it so ath10k firmware is pulled from linux-firmware instead of the qca firmware GitHub repository.

I too have had issues with the 5GHz radio on my R7800 sometimes forgetting clients, and then clients continue to think they are connected and don't re-initiate the connection and must be reset manually from their end. I'm testing this firmware now and hoping it fixes it for me!

**Comment by hauke** [comment]
To have less problems our plan was to use the ath10k firmware shipped in linux-firmware repository and not the ones shipped in the ath10k-firmware repository. Kalle promised to update at least the broad-2.bin files in linux-firmware in the next weeks.

**Comment by jcadduono** [comment]
Hopefully the new 3.6.0.1 firmware will be making its way there soon, I can confirm that this has indeed fixed WiFi disconnections in my home. Our Samsung phones no longer have issues freezing while loading websites in the browser, and after long periods of idle we no longer need to turn WiFi off and on to access the internet/router. This has also fixed Netflix being unable to open on our Samsung TVs after the TV has been idle for some time as well.

**Comment by dougmoscrop** [comment]
Is it OK to use the ct driver with this non-ct firmware?

**Comment by pkgadd** [comment]
No, the ath10k-ct kernel modules depend on ath10k-ct firmware.

**Comment by dougmoscrop** [comment]
How do I build the non-ct driver ? I select it via menuconfig, but build still shows CT being installed

**Comment by greearb** [comment]
The ath10k-ct driver should work fine with stock firmware, and for that matter, the ath10k-ct firmware (non-htt-mgt version) should work fine with stock driver.  I suggest using ath10k-ct driver when using ath10k-ct firmware though....

**Comment by robhancock** [comment]
As noted above, since the current tree uses ath10k firmware from linux-firmware instead of ath10k-firmware, the change in this PR is no longer effective. The linux-firmware repository has now been updated with the updated firmware and I've created a new PR to update to a version containing it: https://github.com/openwrt/openwrt/pull/1482

Closing this PR.

**Pull request closed without merging**
