### PR TITLE
openvpn-easy-rsa: update to 3.0.4

### PR DESCRIPTION
**Pull request by luizluca**
Since 3.0.2, vars default location is $PWD/pki/vars.
Also, openssl-1.0.cnf was renamed to openssl-easyrsa.cnf.
For keep changes, when upgrading from previous versions, run:

 mv /etc/easy-rsa/vars /etc/easy-rsa/pki/vars
 mv /etc/easy-rsa/openssl-1.0.cnf /etc/easy-rsa/pki/openssl-easyrsa.cnf

Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Can you add a symlink instead of renaming?

**Comment by allaudet** [comment]
What's the reason behind adding your name in the copyright?

**Comment by luizluca** [comment]
@neheb , symblink will do. However, I don't know if it is the best way to deal with the change upstream. If it was RPM, I would do mv in %post if any conf file was changed. Sometime in the future, it is interesting to have confs the same places where easyrsa have them in other installations (not openwrt). I just don't know which is the best way to do it painless.
 
@allaudet , I just did what I used to do with openwrt/packages. It was discussed some time ago. As devs does not have a contract to pass rights to OpenWrt org, we should not use (c) to them. If needed, we must add our own. If this changed, (or it is different for core), I will remove it right away.  I really think that copyright headers are not the most efficient way to track all those who own rights over the source. Any need to ask devs (like if OpenWrt wants to change license), will need to dig into git log anyway. Should I remove it?

**Comment by luizluca** [comment]
Just rebasing...

**Comment by diizzyy** [comment]
LGTM

**Comment by diizzyy** [comment]
Ahh, good idea!

**Pull request closed without merging**
