### PR TITLE
ramips: rt3883: fix some issues for Belkin F9K1109

### PR DESCRIPTION
**Pull request by DragonBluep**
This PR fixes parts of issues reported by @ascendbeing in https://github.com/openwrt/openwrt/issues/16054.

### CODE REVIEW

**Comment by neheb** [comment]
Unrelated, just curious:

Isn't ieee80211-freq-limit the replacement for ralink,2ghz?

**Comment by DragonBluep** [comment]
> Unrelated, just curious:
> 
> Isn't ieee80211-freq-limit the replacement for ralink,2ghz?

Sadly it doesn't works on my mt7620(rt2x00 drived) device.

**Comment by ascendbeing** [comment]
Dragon ill test what you called the "final build" likely tonight. I'll update this post when I have done so. Not sure if it's up to date but probably that'll at least give an indication.

**Comment by ascendbeing** [comment]
@DragonBluep I just flashed the `final build` to f9k1109. result is soft brick, same as the one I tried before I was away. The last build that worked was two builds prior. There were some seemingly unresolved issues on that one, but it didn't soft brick.

**Comment by robimarko** [comment]
rt2x00 driver doesnt support `ieee80211-freq-limit`, it should be added via `wiphy_read_of_freq_limits`

**Pull request merged**
