### PR TITLE
e2fsprogs: Update to 1.45.6

### PR DESCRIPTION
**Pull request by diizzyy**
Update e2fsprogs to 1.45.6

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Just "e2fsprogs:" as prefix in the commit title should be appropriate.

**Comment by diizzyy** [comment]
That's very misleading and confusing as we have both e2fsprogs in both tools and packages.
This format also also been accepted and used by other in the past:
https://github.com/openwrt/openwrt/commit/804c51e1e661819c5a7532e66fb8a12166eef9a9
https://github.com/openwrt/openwrt/commit/1b46bce8509180914d2f44ea2374e41b6bbc0752
https://github.com/openwrt/openwrt/commit/198172c0488262d620d87ab765ecc3ad8292fbec

**Comment by jow-** [comment]
Please only use `e2fsprogs: ` as subject prefix despite the other accepted instances in the past

**Comment by diizzyy** [comment]
Compile/Runtime tested: octeon, EdgeRouter Lite, master

**Comment by dedeckeh** [comment]
Pulled into my staging tree (https://git.openwrt.org/?p=openwrt/staging/dedeckeh.git;a=commit;h=d716685872c7b958971fcb653846833b96a8793c); thx

**Pull request closed without merging**
