### PR TITLE
[21.02] ath79: fixes for Senao devices

### PR DESCRIPTION
**Pull request by mcprat**
these changes were tested again on most of the affected devices with public snapshot images

commits were picked in order with `git cherry-pick -x` and there was no conflicts

so it's ready for release 👍🏼

### CODE REVIEW

**Comment by mpratt14** [comment]
@tmn505 you may now test public snapshot images for your allnet device if you like

**Comment by mpratt14** [comment]
there might be another commit to add CAP324, CR3000, and CR5000 to this factory.bin and sysupgrade platform...

**Comment by mpratt14** [comment]
@hauke this is ready for release

also the other PRs here for 21.02 are probably ready as well

**Comment by mpratt14** [comment]
@hauke can this be backported now that RC1 has been tagged already?

**Comment by mpratt14** [comment]
added the fix for the small regression which is now in master, and rebased

**Comment by adschm** [comment]
Do we really really need all of these in the stable branch?

E.g. "ath79: move pcie node to DTSI for qca955x Senao APs" looks purely cosmetic to me and looks to me like a text-book example of a patch that you would not backport ...

**Comment by mpratt14** [comment]
Without the new sysupgrade process in 21.02, sysupgrade would not be possible for these devices between 21.02 and the next stable branch.

yes, the DTSI commits are cosmetic in terms of backporting...but the rest of the commits are based on it...

I assume we don't want to make new commits for 21.02 if we can just cherry-pick them right? Otherwise, they would have a conflict and need to be rewritten

**Comment by mpratt14** [comment]
@adschm also at some point (probably after the first release) I would like to backport more of these devices, which would be based on the DTSI's that we made

**Comment by mpratt14** [comment]
@ynezz ping

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
