### PR TITLE
Added support for Sitecom wlr4100 v1 001

### PR DESCRIPTION
**Pull request by JoostvdB94**
This PR will add support for the Sitecom WLR4100 v1 001

See discussion in https://forum.openwrt.org/t/openwrt-support-for-sitecom-wlr-4100-v1-001/

(needs testing)

### CODE REVIEW

**Comment by mpratt14** [comment]
not long ago a sitecom device was added, lets stick to that naming convention

```
	compatible = "sitecom,wlr-4100-v1-001", "ralink,mt7620a-soc";
	model = "Sitecom WLR-4100 v1 001";
```

**Comment by walterav1984** [comment]
Building on 21.02.2 will fail because the name of .dts file is incorrect and therefor not found during build. You will notice this error if you rebuild/remake with only a single cpu core. Although you have changed the name of the .dts recently its still not correct and should read than it will finish compiling with all cpu cores:
`rt3352_sitecom_wlr-4100-1001.dts`

Another thing thats missing in this git commit @BAjansen his [switch config](https://forum.openwrt.org/t/openwrt-support-for-sitecom-wlr-4100-v1-001/73193/41) any reason?
```
+       sitecom,wlr-4100-1001)
+               ucidef_add_switch "switch0" \
+                       "0:lan:4" "1:lan:3" "2:lan:2" "3:lan:1" "4:wan" "6@eth0"
+               ;;
```

Via 3,3v serial port at  57600 8n1 you have to force tftp boot from the initramfs-kernel image by interrupting boot and pressing the `1` key repeatedly.

After booting OpenWrt 21.02.2 you'll notice that the preferred onboard switch RTL8367rb is still missing and not functioning. Therefor no wan or lan interface is working. My guess is that kernel 5.4 introduced some changes to the working of the multiple switches rt305x+RTL8367rb that are inside this device?

Still trying to build 19.07.9 and see if it works but it uses different labels for devicename/dts/etc...

**Comment by walterav1984** [comment]
Building on 21.02.2 will fail because the name of .dts file is incorrect and therefor not found during build. You will notice this error if you rebuild/remake with only a single cpu core. Although you have changed the name of the .dts recently its still not correct and should read than it will finish compiling with all cpu cores:
`rt3352_sitecom_wlr-4100-1001.dts`

Another thing thats missing in this git commit @BAjansen his [switch config](https://forum.openwrt.org/t/openwrt-support-for-sitecom-wlr-4100-v1-001/73193/41) any reason?
```
+       sitecom,wlr-4100-1001)
+               ucidef_add_switch "switch0" \
+                       "0:lan:4" "1:lan:3" "2:lan:2" "3:lan:1" "4:wan" "6@eth0"
+               ;;
```

Via 3,3v serial port at  57600 8n1 you have to force tftp boot from the initramfs-kernel image by interrupting boot and pressing the `1` key repeatedly.

After booting OpenWrt 21.02.2 you'll notice that the preferred onboard switch RTL8367rb is still missing and not functioning. Therefor no wan or lan interface is working. My guess is that kernel 5.4 introduced some changes to the working of the multiple switches rt305x+RTL8367rb that are inside this device?

Still trying to build 19.07.9 and see if it works but it uses different labels for devicename/dts/etc...

**Comment by walterav1984** [comment]
Also in 19.07.9 when building succeeds the switch is not listed not configured and dmesg shows same error as 21.02.2:
`[   12.674101] rtl8367b rtl8367rb: cannot find mdio bus from bus handle (yet)`

**Comment by walterav1984** [comment]
Also in 19.07.9 when building succeeds the switch is not listed not configured and dmesg shows same error as 21.02.2:
`[   12.674101] rtl8367b rtl8367rb: cannot find mdio bus from bus handle (yet)`

**Pull request closed without merging**
