### PR TITLE
lantiq: switch to Kernel 5.15 by default

### PR DESCRIPTION
**Pull request by aparcar**
This PR to have an overview of testing.

### CODE REVIEW

**Comment by jospezial** [comment]
No related problems any more on xRX200 VGV7510KW22.
I'm using kernel 5.15.x since #9733.
I'm hot for testing kernel 6.x on that device.

**Comment by jospezial** [comment]
> In #9733 there was still runtime warning.
> 
> > there's a new runtime warning from the lantiq_gswip driver (e.g.: gswip 1e108000.switch: port 4 failed to add  vid 1 to fdb: -22) - maybe @hauke has an idea?

>Together with @sch-m I am working on fixing this upstream (patches are not sent yet). Backporting these patches is not possible (at least not easy) as it depends on DSA frameworks updates from Linux 5.18 and 5.19. Would we "just" document this new warning (not sure where though) and then close all bug reports related to these (I'm sure there will be a new report from time to time)?



>    For the warning could we add a info "... harmless ... link to this PR (#9733)" one line obove the warnings?

>That would be possible. I noticed that an even easier approach would be to change return -EINVAL; to return 0; using an OpenWrt patch (the approach you suggested also couldn't be upstreamed).
It's a gross hack but should at least get rid of the warning.

@xdarklight @sch-m , any news about this?

**Comment by jospezial** [comment]
Has @abajk an opinion about that warning?

> In #9733 there was still runtime warning.
> 
> > there's a new runtime warning from the lantiq_gswip driver (e.g.: gswip 1e108000.switch: port 4 failed to add  vid 1 to fdb: -22)

**Comment by rmilecki** [comment]
Upstream patch and discussion: https://patchwork.kernel.org/project/netdevbpf/patch/20220630212703.3280485-1-martin.blumenstingl@googlemail.com/

**Comment by jospezial** [comment]
> Upstream patch and discussion: https://patchwork.kernel.org/project/netdevbpf/patch/20220630212703.3280485-1-martin.blumenstingl@googlemail.com/

Unfortunately no progress there since July last year.

**Comment by abajk** [comment]
I think it would have been better to just merger PR 12064. The primary problem is the additional logs appearing on the console coming from the DSA driver. This can be fixed later. Apart from that, everything works fine :)

**Review by abajk — APPROVED** [review]

**Comment by PolynomialDivision** [comment]
@Ansuel Because we reverted the lantiq source-only, we can merge this?

**Pull request merged**
