### PR TITLE
apm821xx: switch to Kernel 5.10

### PR DESCRIPTION
**Pull request by aparcar**
CI build with artifacts: https://github.com/aparcar/openwrt/actions/runs/1289777003

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by chunkeey** [comment]
The build fails, right? 

Though, it seems like MX60(W) doesn't boot with 5.4 (but it builds!) either. But this "could" be fixed by uboot bootcmd shenanigans.

**Comment by aparcar** [comment]
@chunkeey are you aware of related patches to fix that issue?

**Comment by chunkeey** [comment]
what patches? No, there's this back and forth:

https://forum.openwrt.org/t/failure-apm821xx-nand-sat-jan-23-2021-images/86377

I've recently wrote a PM to lleachii about how the WNDR4700 is/was in a similar bind (again).
But so far no reply. I don't have a MX60(W) so, I err on the side of caution due to similar
situations in the past.

**Comment by Hurricos** [comment]
If you can provide me a NAND build, I can test on my MX60W. [Looks like](https://github.com/aparcar/openwrt/runs/3752468197?check_suite_focus=true) the last NAND build failed?

**Comment by aparcar** [comment]
@Hurricos no idea why the build fails at this point...

**Comment by chunkeey** [comment]
It's because the MX60's kernel got too big with 5.10.

I've a "way out" patch:

https://git.openwrt.org/?p=openwrt/staging/chunkeey.git;a=commit;h=8691e8c0dff5560786c2ec1a9df86428dd58743e

Thing is, this needs u-boot env update. But on the plus side, it does away with many current and future problems.

**Comment by aparcar** [comment]
Thank you, I'll run this in my CI and give an update.

**Comment by aparcar** [comment]
Looks like other `netgear_wndap620` is still causing trouble: https://github.com/aparcar/openwrt/runs/3771880662?check_suite_focus=true

**Comment by chunkeey** [comment]
k, this one I can test myself. (the wndap620 and wndap660 are pretty much the same here)

https://git.openwrt.org/?p=openwrt/staging/chunkeey.git;a=commit;h=8898c3efff7e213c0dddc7e520e0d3360aa66ed0

Note: In theory sysupgrade would break again (in the near future) when both wndap620+wndap660 are switched over to DSA.

**Comment by chunkeey** [comment]
@aparcar well then, what do you think? Would you do the honors of disabling the MX60 since nobody replied? The "fix" for the WNDAP620/660 can be applied at any time. (The WNDR4700 could need work as well, but there's a chicken and egg problem)

**Comment by Hurricos** [comment]
> @aparcar well then, what do you think? Would you do the honors of disabling the MX60 since nobody replied? The "fix" for the WNDAP620/660 can be applied at any time. (The WNDR4700 could need work as well, but there's a chicken and egg problem)

Hey there -- I am VERY interested in the continued existence of the MX60. 

Is the plan to fix the build? I'm still waiting on a "sanctioned" copy of the MX60 build to test with.

I'm happy to run the build myself if someone has a working revision and `.config`

**Comment by chunkeey** [comment]
@Hurricos 

https://github.com/openwrt/openwrt/pull/4617#issuecomment-932534596 

This one?

Just select the APM821xx target, select the NAND subtarget, then Multiple Profiles with just the MX60(W), then CONFIG_ALL.
As state in the patch, you'll need to update u-boot env and boot from a newly generated initramfs and to do the sysupgrade installation from there.

**Comment by Hurricos** [comment]
> @Hurricos
> 
> [#4617 (comment)](https://github.com/openwrt/openwrt/pull/4617#issuecomment-932534596)
> 
> This one?
> 
> then CONFIG_ALL.

I will not be able to build with CONFIG_ALL. Trying to build at all without it now from atop [a704ca7915](https://git.openwrt.org/?p=openwrt/staging/chunkeey.git;a=commit;h=a704ca79157bee09d90dda9dce74a7928ac7a9a8).

For CONFIG_ALL issues: I have repeatedly had issues compiling LuaJIT for ppc32: first because of lack of 32-bit support for gcc (solved by applying [here](https://lists.openwrt.org/pipermail/openwrt-devel/2021-January/033245.html), I use a Docker configuration very similar to the buildbot); now, I am having it stop when the LuaJIT `ld` fails (`grep -ie luajit -C 10 screenlog` output is [here](https://paste.c-net.org/AcresFates)). I see some hints from searching for these error messages that musl libc is incompatible with LuaJIT on ppc32? I am curious about how you folks manage to build this, but nothing much more than just curious.

**Comment by chunkeey** [comment]
> I am curious about how you folks manage to build this, but nothing much more than just curious.

they are probably not. the package on the builder just skips broken compiles. 

As for CONFIG_ALL alternatives: ````CONFIG_ALL_NONSHARED```` (which includes ````CONFIG_ALL_KMODS````) is probably the most important one... as the various related and unrelated kernel modules pull in all the unnecessary subsystems. I hope these "should" fully compile.

**Comment by Hurricos** [comment]
Hey folks,

The MX60 is tested-confirmed-working on Kernel 5.10.72 with @chunkeey's instructions. It is not much work overall to have to go reset the u-boot env. variables, because the serial headers are very accessible.

One final patch is required -- should be squashed into @chunkeey's [back-up patch](https://git.openwrt.org/?p=openwrt/staging/chunkeey.git;a=commit;h=8691e8c0dff5560786c2ec1a9df86428dd58743e) and applied to master:

```patch
From 1d31016b9312de9b73b622c6da1cb1bded947116 Mon Sep 17 00:00:00 2001
From: Martin Kennedy <hurricos@gmail.com>
Date: Thu, 14 Oct 2021 23:14:33 -0400
Subject: [PATCH] apm821xx: MX60: Fix compat-version to 2.0 on boot

Now that compat_version=2.0 is required to sysupgrade, make
sure to properly set it once running the appropriate image.
---
 .../base-files/etc/uci-defaults/01_fix-compat-version  | 10 ++++++++++
 1 file changed, 10 insertions(+)
 create mode 100644 target/linux/apm821xx/base-files/etc/uci-defaults/01_fix-compat-version

diff --git a/target/linux/apm821xx/base-files/etc/uci-defaults/01_fix-compat-version b/target/linux/apm821xx/base-files/etc/uci-defaults/01_fix-compat-version
new file mode 100644
index 0000000000..0fd88fd957
--- /dev/null
+++ b/target/linux/apm821xx/base-files/etc/uci-defaults/01_fix-compat-version
@@ -0,0 +1,10 @@
+. /lib/functions.sh
+
+case "$(board_name)" in
+	meraki,mx60)
+		uci set system.@system[0].compat_version="2.0"
+		uci commit system
+		;;
+esac
+
+exit 0
-- 
2.25.1
``` 

Shall I open a separate PR for the back-out-patch plus this one?

**Pull request closed without merging**
