### PR TITLE
lantiq: remove support for kernel 4.19

### PR DESCRIPTION
**Pull request by abajk**
Kernel 5.4 works fine and we can remove support for 4.19.
Tested on BT Home Hub 5A for last month (work as main VDSL router).

Signed-off-by: Aleksander Jan Bajkowski <A.Bajkowski@stud.elka.pw.edu.pl>
Acked-by: Martin Blumenstingl <martin.blumenstingl@googlemail.com>

### CODE REVIEW

**Comment by xdarklight** [comment]
according to github this needs to be rebased.
this is probably due to https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=6062d858929df927e244280ec4864b35a217d6d1

since resolving the conflict is going to be easy (remove the whole file) and everything else looks good: please include my
Acked-by: Martin Blumenstingl <martin.blumenstingl@googlemail.com>

Thank you!

**Comment by olek2** [comment]
rebased

**Comment by zuzia-dev** [comment]
Router Easybox 904 xDSL not working on kernel 5.4! Please do not remove kernel 4.19.

**Comment by olek2** [comment]
@zuzia-dev 
Support for Easybox 904 xDSL was never merged in OpenWRT #2060

**Comment by zuzia-dev** [comment]
However, the Plonbong patches work great.

**Comment by olek2** [comment]
@zuzia-dev 
But this shouldn't block OpenWRT development. 4.19 is incompatible with DSA #3085

**Comment by adrianschmutzler** [comment]
The fact that 5.4 is working is not really a reason to remove 4.19 now. The only real reason I see at the moment would be the DSA introduction, which indeed would make 4.19 incompatible (though for that particular subtarget only).

**Comment by xdarklight** [comment]
for me the reason why 4.19 support should be removed is commit 27724c2f54466803bf6e7d3efb637971ebcd139e
With that the only way to compile the lantiq target with Linux 4.19 is by manually changing ``target/linux/lantiq/Makefile`` (before that 5.4 could be selected by enabling the testing kernel version config switch).
I'm curious: how are kernel patches for 4.19 in the lantiq target refreshed in this scenario?

I don't mind keeping support for 4.19 around.
On the other hand I'm not going to spend time debugging issues with Linux 4.19 - I'd rather spend the time fixing the issues in 5.4

As you noted, the DSA PR (#3085) will then be the nail in the coffin (for 4.19 support for that {sub-,}target).

**Comment by adrianschmutzler** [comment]
> for me the reason why 4.19 support should be removed is commit 27724c2

It's been frequent practice to keep around an older kernel in the recent past to be able to test easily when necessary; e.g. note that most targets had 4.14 when 4.19 was already there...

**Comment by ynezz** [comment]
Thanks, but we'll remove the old kernels ourselves at right time.

**Comment by xdarklight** [comment]
Hi @ynezz et al

> Thanks, but we'll remove the old kernels ourselves at right time.

can you please elaborate what that means?

Within the lantiq target the "old" kernel version has been removed on the same day as enabling the "new" version by default for at least these releases:
* 4.4 to 4.9: e0d6f541f731a49d49f59734d1b72b6e05e4ff9b and 6b06c2fb8ec15faed936cae79f3d6cec2705cac1
* 4.9 to 4.14: d7b7483343b5c7f157a2a97244ce9e60f4260e43
* 4.14 to 4.19: e6867a5283b4bb4628744599f8b5070af846a054 and cb689f2723b40c96426ac69f1478530ff1d48368

This is why I'm confused to see this PR rejected.
I'm not saying that it has to kept "the way it has always been". What's important for me is to understand the new approach so no time is wasted (I'm happy with a link to a wiki page or some email discussion on the mailing-list where I can read more about this).


Thank you!

**Comment by ynezz** [comment]
> Within the lantiq target

I didn't studied lantiq's history.

> This is why I'm confused to see this PR rejected.

@adrianschmutzler already tried to explain it. We try to keep the previous kernel for a quick regression testing, so it's current kernel version and previous kernel version. For some examples see 8e6a8a08d2a3f23ff8accb065818808209eeceaa, 7a6a85ce108c4883c0d99d5ecdd30512af11dff4 and similar commits.

**Comment by xdarklight** [comment]
> @adrianschmutzler already tried to explain it. We try to keep the previous kernel for a quick regression testing, so it's current kernel version and previous kernel version. For some examples see [8e6a8a0](https://github.com/openwrt/openwrt/commit/8e6a8a08d2a3f23ff8accb065818808209eeceaa), [7a6a85c](https://github.com/openwrt/openwrt/commit/7a6a85ce108c4883c0d99d5ecdd30512af11dff4) and similar commits.

understood, thank you for the examples!
That means it's time to bring this topic back up when #3085 is ready - as @adrianschmutzler already suggested

**Pull request closed without merging**
