### PR TITLE
Update dnsmasq.init

### PR DESCRIPTION
**Pull request by sanchosk**
I have a problem with 2 independent dnsmasq instances.
When I am running 2 instances and one of them have static host with dns set to 1 and instance set to 'main', it will generate the record in /tmp/hosts/dhcp.main.
Problem is, the same addn-file dir (/tmp/hosts) is used also by the second instance of dnsmasq, so when the client there tries to resolve something from the main dnsmasq, it will get the result even though it should not.
Changing the path like described in my change would make sure the instances have separate folder and they do not collide with each other.

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by adschm** [comment]
This has formal issues.

https://openwrt.org/submitting-patches
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes

**Comment by e9hack** [comment]
@sanchosk, to solve this behaviour, option ignore_hosts_dir can be set 1 for both instances. If it is set, addn-hosts is set to the file and not to the directory. You may get the same issue with conf-dir. If you need it separately, option confdir must be set at least for one instance.

**Comment by Ansuel** [comment]
User never answered, a workaround (actually the correct solution to the problem) was provided... Closing this. If still required pls resubmit...

**Comment by sanchosk** [comment]
Thanks, I missed your first answer, I'll test it, but it seems reasonable.

**Pull request closed without merging**
