### PR TITLE
e2fsprogs: Fix build failure for e2fsprogs by ensuring external UUID library is found.

### PR DESCRIPTION
**Pull request by zxlhhyccc**
*** Need to explicitly link the pthread library
````
checking for uuid_generate in -luuid... no
configure: error: external uuid library not found
Makefile:50: recipe for target '../build_dir/host/e2fsprogs-1.47.0/.configured' failed
make[3]: *** [../build_dir/host/e2fsprogs-1.47.0/.configured] Error 1
````

### CODE REVIEW

**Comment by zxlhhyccc** [comment]
Ping @robimarko

**Comment by robimarko** [comment]
No, check the e2fsprogs history, it was switched away from using its internal `libuuid` and uses the `util-linux` provided one.

So, you are going to need to share more details so we can find the real issue.

**Comment by zxlhhyccc** [comment]
@robimarko but, `e2fsprogs` was compiled before `util-linux` was compiled, resulting in the `libuuid` library not being found.

**Comment by robimarko** [comment]
Can you go into `staging_dir/host/lib/` and look for `libuuid.la` and `libuuid.a`

**Comment by zxlhhyccc** [comment]
@robimarko 
image

**Comment by zxlhhyccc** [comment]
@robimarko The following changes can compiled:
````
--- a/Makefile
+++ b/Makefile
@@ -24,7 +24,7 @@ ifneq ($(shell $(HOSTCC) --version | grep clang),)
 endif
 HOST_CFLAGS += $(HOST_FPIC)
 
-HOST_CONFIGURE_ARGS += \
+HOST_CONFIGURE_ARGS += LDFLAGS="-lpthread" \
 	--disable-elf-shlibs \
 	--disable-libuuid \
 	--disable-tls \
````

**Comment by zxlhhyccc** [comment]
Ping @robimarko , The patch has been update.

**Comment by zxlhhyccc** [comment]
@robimarko  **mtd-utils erro：**
````
kfs_ubifs-hashtable.o ubifs-utils/mkfs.ubifs/hashtable/mkfs_ubifs-hashtable_itr.o ubifs-utils/mkfs.ubifs/mkfs_ubifs-devtable.o  libmtd.a libubi.a -L/home/lin/ax6-6.x/staging_dir/host/lib -lz   -L/home/lin/ax6-6.x/staging_dir/host/lib -luuid   -lm 
/usr/local/bin/ld: /home/lin/ax6-6.x/staging_dir/host/lib/libuuid.a(la-gen_uuid.o): in function `uuid_generate_time_generic':
gen_uuid.c:(.text+0xbac): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
Makefile:2351: recipe for target 'mkfs.ubifs' failed
make[3]: *** [mkfs.ubifs] Error 1
make[3]: Leaving directory '/home/lin/ax6-6.x/build_dir/host/mtd-utils-2.2.0'
Makefile:56: recipe for target '/home/lin/ax6-6.x/build_dir/host/mtd-utils-2.2.0/.built' failed
make[2]: *** [/home/lin/ax6-6.x/build_dir/host/mtd-utils-2.2.0/.built] Error 2
make[2]: Leaving directory '/home/lin/ax6-6.x/tools/mtd-utils'
time: tools/mtd-utils/compile#13.50#2.73#16.97
    ERROR: tools/mtd-utils failed to build.
tools/Makefile:232: recipe for target 'tools/mtd-utils/compile' failed
make[1]: *** [tools/mtd-utils/compile] Error 1
make[1]: Leaving directory '/home/lin/ax6-6.x'
/home/lin/ax6-6.x/include/toplevel.mk:246: recipe for target 'tools/mtd-utils/compile' failed
make: *** [tools/mtd-utils/compile] Error 2
````

**Comment by zxlhhyccc** [comment]
@robimarko Uses the `util-linux` provided `libuuid`，`mtd-utils` build error,but Uses the `e2fsprogs` provided `libuuid`  build is normal.

**Comment by neheb** [comment]
```
pthread_atfork
```

needs a link to pthread. e2fsprogs check needs fixing.

**Comment by zxlhhyccc** [comment]
> needs a link to pthread. e2fsprogs check needs fixing.

YES.

**Comment by robimarko** [comment]
Can you describe your setup, so host distro etc as to how to reproduce this as its working fine for me

**Comment by neheb** [comment]
@robimarko he's using a sub glibc 2.32 (forgot the version) distro where libpthread is not in libc.

I think the proper solution is something like this: https://github.com/openwrt/openwrt/blob/main/toolchain/gcc/common.mk#L78

ping @mcprat

**Comment by neheb** [comment]
Ah I think uuid.pc is the problem here.

@zxlhhyccc please post the contents of

```
staging_dir/host/lib/pkgconfig/uuid.pc
```

**Comment by robimarko** [comment]
I can only guess this is an Ubuntu 18.04 issue since even 20.04 which uses Glibc 2.31 doesn't exhibit the issue

**Comment by neheb** [comment]
Maybe. util-linux with meson handles this properly but that needs to wait for the next major version AFAIK.

**Comment by mcprat** [comment]
> Ah I think uuid.pc is the problem here.
> 
> ```
> staging_dir/host/lib/pkgconfig/uuid.pc
> ```

if it shows

`Version: 1.47.0`

or

`Version: 1.46.x`

1. delete the file
2. `make tools/e2fsprogs/clean tools/util-linux/clean`
3. rebuild

**Comment by robimarko** [comment]
Yeah, I can reproduce this with Ubuntu 18.04 only, which is not supported and has not been for a while since all of its components are older than what we require and its EOL.

**Comment by mcprat** [comment]
> Yeah, I can reproduce this with Ubuntu 18.04 only

I'm wondering though, is this a brand new buildroot or after advancing to current HEAD where old files like uuid.pc are still hanging around?

**Comment by robimarko** [comment]
> > Yeah, I can reproduce this with Ubuntu 18.04 only
> 
> I'm wondering though, is this a brand new buildroot or after advancing to current HEAD where old files like uuid.pc are still hanging around?

Brand new 18.04 docker, there isn't anything old

**Comment by neheb** [comment]
to fix we need an equivalent to https://github.com/openwrt/openwrt/commit/f2fabf7aaaacec6fdc50226f57f4be2c19d8cace for autotools, probably.

**Comment by zxlhhyccc** [comment]
@neheb @robimarko @mcprat 
````
$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
Copyright (C) 2018 自由软件基金会。
这是一个自由软件；请见源代码的授权条款。本软件不含任何没有担保；甚至不保证适销性
或者适合某些特殊目的。
由 Roland McGrath 和 Ulrich Drepper 编写。
`````

**Comment by robimarko** [comment]
@neheb I manually added the required flags to pkg-config file:
```
prefix=@prefix@
exec_prefix=@exec_prefix@
libdir=@usrlib_execdir@
includedir=@includedir@

Name: uuid
Description: Universally unique id library
Version: @LIBUUID_VERSION@
Requires:
Cflags: -I${includedir}/uuid
Libs: -L${libdir} -luuid -lpthread
```

But the e2fsprogs test will still fail

**Comment by robimarko** [comment]
Well, even with the upstream fix:
https://github.com/util-linux/util-linux/commit/81ea117e0396274808a77d40bf11af44ea047285

The check will still fail

**Comment by neheb** [comment]
Oh right. Autotools uses two different macros for static and shared pkgconfig

**Comment by zxlhhyccc** [comment]
@robimarko @neheb @mcprat 
image

**Comment by zxlhhyccc** [comment]
@robimarko @neheb @mcprat Upgrade glibc to version 2.28.

**Comment by neheb** [comment]
@robimarko I checked git history and found https://github.com/openwrt/openwrt/commit/728581dc4bc7f32a29b1fbba6aa54ed6266feb33

Claiming 18.04 is the new minimum.

Which components were too old?

**Comment by neheb** [comment]
@zxlhhyccc turns out this is just as simple as doing

```
--- a/tools/e2fsprogs/Makefile
+++ b/tools/e2fsprogs/Makefile
@@ -32,6 +32,9 @@ HOST_CONFIGURE_ARGS += \
        --enable-threads=pth \
        --disable-fuse2fs
 
+HOST_CONFIGURE_VARS += \
+       ac_cv_lib_uuid_uuid_generate=yes
+
 define Host/Prepare
        $(call Host/Prepare/Default)
        rm -rf $(HOST_BUILD_DIR)/doc

```

no need to update glibc.

**Comment by robimarko** [comment]
> @robimarko I checked git history and found [728581d](https://github.com/openwrt/openwrt/commit/728581dc4bc7f32a29b1fbba6aa54ed6266feb33)
> 
> Claiming 18.04 is the new minimum.
> 
> Which components were too old?

18.04 is definitively not supported, first of all, it's out of support by Canonical since 31/05/2023 so if you are not paying for extended support(Even then) you should not be using it.

But even then, it will fail on build requirements since:

1. GCC 8 is required but 18.04 only ships GCC 7
2. Python 3.7 is required but 18.04 ships 3.6

Yes, you can get random PPA-s with updated components or build them yourself like I did to reproduce the issue at all but it doesn't make it supported.

**Comment by neheb** [comment]
GCC8 is available in normal repos: https://launchpad.net/ubuntu/bionic/+package/g++-8
Python 3.8 is available in normal repos: https://launchpad.net/ubuntu/bionic/+package/python3.8

Yes I am aware that the defaults are GCC6 and Python 3.6 but the purpose of that commit was to improve Ubuntu 18.04 support. Hence why GCC is now symlinked to STAGING_DIR.

Anyway, I just compiled a build with an 18.04 container (distrobox). Worked perfectly fine.

My question was more along the lines of, what else.

**Comment by robimarko** [comment]
Well, what else is random stuff like this issue that went unnoticed for over 3 months?

I honestly do not see a point in adding more quirks for EoL distros like 18.04

**Comment by neheb** [comment]
I think @jow- 's talked about OEMs using absolutely ancient OSes before.

Given that at least for now it's fairly easy to keep support, I think we should.

Support can be killed in the future when it becomes impractical to do so.

CentOS7 support for example was kept for quite a while.

**Comment by robimarko** [comment]
All OEMs use ancient OS-es, but the question is why should we care?

They won't be using up-to-date OpenWrt releases anyway so this won't affect them for a long time, by then hopefully they updated their builders.

Even CentOS 7 support was dropped after it was EOL.

Even now it requires patching stuff, and then that will be kept around for years cause trust me eventually nobody will know why we even override `ac_cv_lib_uuid_uuid_generate` etc.

While I am for supporting as many weird host distributions, there has to be a line to it, for me its if the distro is supported or its EoL.

**Comment by neheb** [comment]
@robimarko that override goes away after util-linux gets updated as they fixed their pkgconfig file. Actually meson works correct anyway.

mtd-utils change was sent upstream: https://patchwork.ozlabs.org/project/linux-mtd/patch/20240923204502.823673-1-rosenp@gmail.com/

**Comment by robimarko** [comment]
Upstream util-linux change:
https://github.com/util-linux/util-linux/commit/81ea117e0396274808a77d40bf11af44ea047285

Is not enough, with just it the e2fsprogs check will fail.

**Comment by neheb** [comment]
It shouldn't.

https://github.com/tytso/e2fsprogs/blob/master/configure.ac#L484

seems to pass --static on failure. Unless I'm reading it wrong.

**Comment by robimarko** [comment]
Well, I applied that commit and the pkg-config file is updated:
```
prefix=/openwrt/openwrt/staging_dir/host
exec_prefix=/openwrt/openwrt/staging_dir/host
libdir=/openwrt/openwrt/staging_dir/host/lib
includedir=/openwrt/openwrt/staging_dir/host/include

Name: uuid
Description: Universally unique id library
Version: 2.40.2
Cflags: -I${includedir}/uuid
Libs.private:  -lpthread
Libs: -L${libdir} -luuid
```

But the check still fails:
```
configure:6214: checking for uuid_generate in -luuid
configure:6237: /openwrt/openwrt/staging_dir/host/bin/gcc -o conftest -O2 -I/openwrt/openwrt/staging_dir/host/include  -DPIC -fPIC -I/openwrt/openwrt/staging_dir/host/include  -L/openwrt/openwrt/staging_dir/host/lib  conftest.c -luuid   >&5
/openwrt/openwrt/staging_dir/host/lib/libuuid.a(la-gen_uuid.o): In function `uuid_generate_time_generic':
gen_uuid.c:(.text+0xb9c): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
```

**Comment by neheb** [comment]
looks like I'm wrong.

I'll look into it and send a patch upstream.

**Comment by zxlhhyccc** [comment]
> no need to update glibc.

@neheb Apply both patches,`e2fsprogs` and `mtd-utils` no need to update glibc is build success?

**Comment by neheb** [comment]
Yes

**Comment by zxlhhyccc** [comment]
> Yes

@neheb Can mention PR？

**Comment by zxlhhyccc** [comment]
> Well, its so weird that `Libs.private` is not enough since when called with `--static` pkg-config returns `-lpthread` properly in the host, but when testing it seems that only dynamic lib is attempted since only `-luuid` is passed



> @zxlhhyccc turns out this is just as simple as doing
> 
> ```
> --- a/tools/e2fsprogs/Makefile
> +++ b/tools/e2fsprogs/Makefile
> @@ -32,6 +32,9 @@ HOST_CONFIGURE_ARGS += \
>         --enable-threads=pth \
>         --disable-fuse2fs
>  
> +HOST_CONFIGURE_VARS += \
> +       ac_cv_lib_uuid_uuid_generate=yes
> +
>  define Host/Prepare
>         $(call Host/Prepare/Default)
>         rm -rf $(HOST_BUILD_DIR)/doc
> ```
> 
> no need to update glibc.
> 
> edit:
> 
> ```
> --- a/tools/mtd-utils/Makefile
> +++ b/tools/mtd-utils/Makefile
> @@ -37,6 +37,9 @@ HOST_CONFIGURE_ARGS+= \
> ```

@robimarko Use @neheb The above patch for older versions of glibc will compile normally

**Comment by robimarko** [comment]
That just skips the check entirely, the thing is that check should work

**Comment by zxlhhyccc** [comment]
@robimarko   Are you using this patch：https://patchwork.ozlabs.org/project/linux-mtd/patch/20240923204502.823673-1-rosenp@gmail.com/

**Comment by neheb** [comment]
@robimarko it’s using check_lib. The pkg-config stuff there is misleading. It needs to be rewritten.

**Comment by neheb** [comment]
oh this is even worse. that mtd-utils patch does nothing.

autotools doesn't test if the found module is usable.

**Comment by neheb** [comment]
@robimarko after discussion with mr. meson, it turns out util-linux's pkgconfig file is wrong.

Apparently, whenever only a static library is built, Libs.private goes away and everything gets promoted to Libs. Meaning pkg-config --static doesn't need to be passed.

**Pull request closed without merging**
