### PR TITLE
rockchip: Add support for some rk33xx/rk35xx devices

### PR DESCRIPTION
**Pull request by AutoCONFIG**
The commit is reorganized

This open source code is from [lean's lede](https://github.com/coolsnowwolf/lede)，and the open source protocol is GPLv2.

It has been tested on the FastRhino R66S(rk3568 board) and runs stably.

kernel version switched to 5.15 and patch & config-5.15 have been refreshed. Therefore, config-5.10 needs to be refreshed to support kernel 5.10

Due to the large number of modifications, some devices may not work properly, and I have no equipment for testing, but this is not a kernel error, and rk3568 has been tested to work properly.

### CODE REVIEW

**Comment by 981213** [comment]
> Due to the large number of modifications, some devices may not work properly, and I have no equipment for testing

Which means this PR is unacceptible...Please don't pull code from those forks and create a PR without knowing what exactly they are doing.

If you are actually interested in making contribution to OpenWrt you should read our submission guidelines here first: https://openwrt.org/submitting-patches
The commits should be split properly, and each commit should describe what exactly it's doing and why it's needed.

BTW various other unacceptible stuff in the code:
1. Overclocking RK3399.
2. The realtek ethernet drivers. Because those devices are already supported by the in-kernel driver.
3. arm-trusted-firmware-rockchip-vendor. It contains a bunch of prebuilt ATF and also needs to execute closed-source tools from Rockchip. There are opensource bootchain available so you need to explain why the opensource ones can't be used.

**Comment by 981213** [comment]
Oops. I accidentally closed the PR.
BTW pull requests can be updated by force pushing to the branch. You don't need to open a new PR every time you made any changes.

> Please don't pull code from those forks and create a PR without knowing what exactly they are doing.

But if this matches what you are doing i.e. there are parts of this PR you don't understand, you should probably ask if the original author of the commits are interested to contribute here themselves.

**Comment by AutoCONFIG** [comment]
> > Due to the large number of modifications, some devices may not work properly, and I have no equipment for testing
> 
> Which means this PR is unacceptible...Please don't pull code from those forks and create a PR without knowing what exactly they are doing.
> 
> If you are actually interested in making contribution to OpenWrt you should read our submission guidelines here first: https://openwrt.org/submitting-patches The commits should be split properly, and each commit should describe what exactly it's doing and why it's needed.
> 
> BTW various other unacceptible stuff in the code:
> 
> 1. Overclocking RK3399.
> 2. The realtek ethernet drivers. Because those devices are already supported by the in-kernel driver.
> 3. arm-trusted-firmware-rockchip-vendor. It contains a bunch of prebuilt ATF and also needs to execute closed-source tools from Rockchip. There are opensource bootchain available so you need to explain why the opensource ones can't be used.

Thank you for your comments.

> Due to the large number of modifications, some devices may not work properly, and I have no equipment for testing
Because I can only test on rk3568 board, I cannot test on other devices. It does not mean that there is something wrong with the code, but it has not been tested on physical device, so I cannot guarantee that it will be available for other devices.

> 1. Overclocking RK3399.
The default frequency performance is low, which may not meet the requirements of high-load networks. In addition, most users want to unlock the CPU frequency to achieve higher performance. Therefore, frequency unlock codes are provided.

> 2. The realtek ethernet drivers. Because those devices are already supported by the in-kernel driver.
Sorry, I looked in netdevices.mk before adding this driver, but it doesn't exist, and I did not check the driver in the kernel, so I added the driver package separately.
In addition, the r8125 and r8152 are third-party drivers. After modification and improvement, the network adapter runs stably. However, there seems to be some bugs in-kernel driver, which may cause the network adapter to fail to work stably.

> 3. arm-trusted-firmware-rockchip-vendor. It contains a bunch of prebuilt ATF and also needs to execute closed-source tools from Rockchip. There are opensource bootchain available so you need to explain why the opensource ones can't be used.
rk3568_bl31_v1.28.elf from https://github.com/rockchip-linux/rkbin
rk35xx board requires this tool to boot, and using a pre-built file saves compilation time.
Compiling from the source code, first of all, the file size of the source code is large, second of all, compiling with the source code can take a lot of time, and finally, compiling with the source code can cause a lot of compilation errors, which can increase the compilation uncertainty. At least I tried to refer to the rockchip documentation, and it didn't compile successfully. Why bother building with source code when debugging and writing Openwrt-makefiles requires extra development time.
If openwrt need to build rk3568_bl31 from source code, at least not in this PR.

> 4.Which means this PR is unacceptible...Please don't pull code from those forks and create a PR without knowing what exactly they are doing.
I have reviewed this part of the commit code, and there is no problem with them. The patch part only fixes bugs that some hardware cannot work properly, adds some new device support to the kernel, and includes some performance improvements, etc., but they are derived from lean's lede. Therefore, patch will have offset and fuzz. I have fixed patch and config of 5.15, but I do not want to fix 5.10 at present, because openwrt has started to switch to the 5.15 kernel, so it may not be meaningful to fix 5.10.

**Comment by AutoCONFIG** [comment]
> Oops. I accidentally closed the PR. BTW pull requests can be updated by force pushing to the branch. You don't need to open a new PR every time you made any changes.
> 
> > Please don't pull code from those forks and create a PR without knowing what exactly they are doing.
> 
> But if this matches what you are doing i.e. there are parts of this PR you don't understand, you should probably ask if the original author of the commits are interested in contributing here themselves.

I wanted openwrt to support more rockchip devices, but I waited almost a year without seeing any changes to openwrt, so I had to submit new device support to openwrt myself.
I don't think the original authors would be interested in submitting their own submissions here. After all, lean's lede's device support is much better than the official openwrt. If the original authors were interested, the official openwrt would support many more devices and features than it currently does.

If this pr fails, I'll add to my openwrt repository to support more rockchip devices.

Thank you very much for your reply. I sincerely hope that openwrt can get better and better.

**Comment by 981213** [comment]
> Because I can only test on rk3568 board, I cannot test on other devices. It does not mean that there is something wrong with the code, but it has not been tested on physical device, so I cannot guarantee that it will be available for other devices.

Don't touch the stuff you can't test then.

> The default frequency performance is low, which may not meet the requirements of high-load networks. In addition, most users want to unlock the CPU frequency to achieve higher performance. Therefore, frequency unlock codes are provided.

Overclocking means running CPU out of spec. You can have it in your local fork if you want but we can't ship stuff that may break users devices by default.

> Sorry, I looked in netdevices.mk before adding this driver, but it doesn't exist, and I did not check the driver in the kernel, so I added the driver package separately.

They should be supported by kmod-r8169.

> In addition, the r8125 and r8152 are third-party drivers. After modification and improvement, the network adapter runs stably. However, there seems to be some bugs in-kernel driver, which may cause the network adapter to fail to work stably.

The code quality of those vendor drivers are really bad. It contains a ton of garbage code and it's hard to understand what's going on. Meanwhile the in-kernel driver is coded well, widely used by a ton of devices out there and reviewed by upstream linux maintainers. If there are actual network stability issues we should fix the upstream driver instead.

> rk35xx board requires this tool to boot

This is a good reason.

> and using a pre-built file saves compilation time.
> Compiling from the source code, first of all, the file size of the source code is large, second of all, compiling with the source code can take a lot of time, and finally, compiling with the source code can cause a lot of compilation errors, which can increase the compilation uncertainty. At least I tried to refer to the rockchip documentation, and it didn't compile successfully. Why bother building with source code when debugging and writing Openwrt-makefiles requires extra development time.

but all these are not. Many OpenWrt users prefer open-source stuff that they can review and rebuild instead of closed-source vendor blobs. Also vendor blobs without explicit license from the vendor for redistribution may bring legal troubles for OpenWrt as an organization.

> After all, lean's lede's device support is much better than the official openwrt.

Adding garbage vendor code may be fine for a fork targeting only one or two chip vendors but it really isn't a maintainable approach for a big project like OpenWrt.

I'm closing this PR now. You may create a new PR to add support for only the devices you can test instead.

**Pull request closed without merging**
