### PR TITLE
kernel: use skb_list_del_init() instead of list_del in NF_HOOK_LIST

### PR DESCRIPTION
**Pull request by ptpt52**
This backport:
 * 756-v5.5-netfilter-add-and-use-nf_hook_slow_list.patch

### CODE REVIEW

**Comment by ynezz** [comment]
From your commit description I fail to see why those patches should backported.

I've quickly read the commit descriptions in the backported patches, but to me it seems like it's a new functionality, not fixing any bug or such. I assume if that `list_del()` -> `skb_list_del_init()` change would result in fix for older kernel version < 5.5 , then it would be fixed already in stable, but this is not the case.

**Comment by ptpt52** [comment]
@ynezz 
as said, skb->next not NULL then run in nf_hook() is bug

**Comment by ptpt52** [comment]
if skb->next not NULL then dev_queue_xmit() kernel panic happens

**Comment by ynezz** [comment]
Good, then please send a fix upstream. If you're correct, there is a bug in all stable kernels. Rebasing all this patches might be PITA during kernel versions bumps.

**Comment by ptpt52** [comment]
but how to send patch to upstream stable kernel 5.4?

**Comment by ynezz** [comment]
https://www.kernel.org/doc/html/latest/process/stable-kernel-rules.html

**Comment by adschm** [comment]
What's the status here?

**Comment by ptpt52** [comment]
hello I just re-push the commit, I prefer just replace the usage of skb_list_del_init()
just a bug fix to kernel code.

**Comment by clan** [comment]
https://bugzilla.kernel.org/show_bug.cgi?id=209823

**Comment by ynezz** [comment]
@clan Thanks a lot for making upstream aware.
@clan @ptpt52 I'm closing this, please create a new PR once the fix lands in  the upstream kernel, or just ping me here and I'll do the backport myself.

**Comment by ptpt52** [comment]
I notice that it is in kernel 5.4.81

**Pull request closed without merging**
