### PR TITLE
lantiq: Update to kernel 6.1

### PR DESCRIPTION
**Pull request by hauke**
This adds support for kernel 6.1 for the lantiq target.

This is not ready yet there are multiple known problems:
 - [ ] Requesting IRQs for some drivers not getting their IRQ number from device tree is broken (e.g. DSL, PCIe)
 - [ ] Basic test on ase
 - [ ] Basic test on falcon
 - [x] Basic test on xrx200
 - [ ] Basic test on xway
 - [ ] Basic test on xway_legacy
 - [ ] Add description to new patches

This also has some of the ugly DSA error messages we also see in kernel 5.15.

### CODE REVIEW

**Comment by hauke** [comment]
I added a hack to make some of the IRQs work with kernel 6.1 again, see fdd6fca02602a3e008a03c9b08b695a6c677e8d6. If someone is working on a real fix for this problem please contact me. 

I am still seeing this warning at bootup:
````
[   97.797174] ------------[ cut here ]------------
[   97.800541] WARNING: CPU: 0 PID: 1782 at target-mips_24kc_musl/linux-lantiq_xrx200/drv_mei_cpe-1.5.17.6/src/drv_mei_cpe_msg_process.c:3527 MEI_IoctlCmdMsgWrite+0x308/0x32c [drv_mei_cpe]
[   97.817049] memcpy: detected field-spanning write (size 4) of single field "pDestPtr" at target-mips_24kc_musl/linux-lantiq_xrx200/drv_mei_cpe-1.5.17.6/src/drv_mei_cpe_msg_process.c:3527 (size 2)
[   97.834540] Modules linked in: ath9k ath9k_common nft_fib_inet nf_flow_table_inet ath9k_hw ath pppoe nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject nft_redir nft_quota nft_objref nft_numgen nft_nat nft_masq nft_log nft_limit nft_hash nft_flow_offload nft_fib_ipv6 nft_fib_ipv4 nft_fib nft_ct nft_chain_nat nf_tables nf_nat nf_flow_table nf_conntrack mac80211 cfg80211 pppox ppp_async nfnetlink nf_reject_ipv6 nf_reject_ipv4 nf_log_syslog nf_defrag_ipv6 nf_defrag_ipv4 ltq_deu_vr9 libcrc32c crc_ccitt compat drv_dsl_cpe_api ledtrig_usbport drv_mei_cpe ltq_vectoring pppoatm ppp_generic slhc br2684 atm drv_ifxos sha512_generic seqiv jitterentropy_rng drbg hmac des_generic libdes cmac dwc2 roles gpio_button_hotplug crc32c_generic
[   97.899457] CPU: 0 PID: 1782 Comm: evnthnd Not tainted 6.1.38 #0
[   97.905268] Stack : 83160000 8008784c 00000000 00000004 00000000 00000000 821c79e4 80e80000
[   97.913621]         80970000 80809534 81d709b0 8097432f 00000000 00000001 821c7990 81439780
[   97.921973]         00000000 00000000 80809534 821c78b8 ffffefff 00000000 00000000 ffffffea
[   97.930335]         000000da 821c78c4 000000da 808f26a0 80809534 00000001 00000000 00000dc7
[   97.938686]         00000009 831470cc 808ea258 8312dc74 00000018 00000030 00000000 80e80000
[   97.947042]         ...
[   97.949479] Call Trace:
[   97.951914] [<8000bf98>] show_stack+0x28/0xf0
[   97.956277] [<806e787c>] dump_stack_lvl+0x60/0x80
[   97.960977] [<80032c58>] __warn+0x9c/0xe8
[   97.964993] [<80032dbc>] warn_slowpath_fmt+0x118/0x17c
[   97.970143] [<831470cc>] MEI_IoctlCmdMsgWrite+0x308/0x32c [drv_mei_cpe]
[   97.976828] [<831474ec>] MEI_IoctlMsgSend+0x84/0x324 [drv_mei_cpe]
[   97.983004] [<831430c8>] MEI_InternalMsgSend+0x68/0x84 [drv_mei_cpe]
[   97.989363] [<8314314c>] MEI_InternalSendMessage+0x68/0xcc [drv_mei_cpe]
[   97.996054] [<831555e4>] MEI_VRX_DSM_StatsGet+0x44/0x6c [drv_mei_cpe]
[   98.002494] [<8315565c>] MEI_VRX_DSM_FwStatsCheck+0x50/0xbc [drv_mei_cpe]
[   98.009294] [<83154314>] MEI_DEV_IoctlFirmwareDownload+0x1550/0x1b2c [drv_mei_cpe]
[   98.016864] [<831434fc>] MEI_InternalFirmwareDownload+0x38/0x50 [drv_mei_cpe]
[   98.024008] [<8319827c>] DSL_DRV_DEV_FwDownload+0x1c0/0x454 [drv_dsl_cpe_api]
[   98.031264] [<83184dfc>] DSL_DRV_AutobootLoadFirmware+0x1f8/0x58c [drv_dsl_cpe_api]
[   98.038897] [<831813f4>] DSL_DRV_IoctlHandleHelperCall+0xc0/0x19c [drv_dsl_cpe_api]
[   98.046553] [<8318443c>] DSL_DRV_IoctlHandle+0x50c/0x844 [drv_dsl_cpe_api]
[   98.053426] [<83186ba0>] DSL_DRV_ErrorToOS+0x134/0x15c [drv_dsl_cpe_api]
[   98.060117] 
[   98.061592] ---[ end trace 0000000000000000 ]---
````

**Comment by Neustradamus** [comment]
For information: Kernel 6.6 is LTS:
6.6 | Greg Kroah-Hartman & Sasha Levin | 2023-10-29 | Dec, 2026
- https://www.kernel.org/category/releases.html

**Comment by ccpalex** [comment]
Hi @hauke !

Regarding lantiq_gswip DSA errors, did you try something like [this](https://github.com/ccpalex/linux/tree/gswip) ?
I unfortunately cannot test on xrx200 or with lantiq driver, but we are trying to bring up Maxlinear gsw145 driver and it had the same problem. I do not see
```
  port 4 failed to add <LAN MAC address> vid 1 to fdb: -22
  port 4 failed to delete <LAN MAC address> vid 1 from fdb: -22
```
with my patch, but I'm not sure if it's the right thing to do though, because on gsw145 I observe further problems.
I didn't pay much attention to the commit message, but if it helps, I will work on it further...

**Comment by Snowiiii** [comment]
Have an lantiq system myself i look up to this

**Comment by hauke** [comment]
I am currently not working on this, if someone wants to take this over to get it to 6.6 it would be nice. 

Someone should update the PCIe and GPTU driver to get rid of this patch: https://github.com/openwrt/openwrt/pull/13046/commits/54bae1ee2f32a92c69e627d820eac2555be56a37
Taking the IRQs from device tree instead of hard coding them in the source code should solve it.

**Comment by sch-m** [comment]
@hauke @blogic  There is a GPTU driver in the upstream linux kernel (https://github.com/torvalds/linux/commit/30404aec4d093942ba67ded8e1926cbf4472d4f7) which seems to be used only by amazon-se at the moment. Do you know why we can't use this driver for the other targets as well?

**Comment by sch-m** [comment]
@hauke Please have a short look at my branch here: https://github.com/TDT-AG/openwrt/tree/pr/20240411-lantiq-6.1

- I have extended the PCIe and GPTU drivers so that they fetch the IRQs from the DeviceTree and as a result eliminated the HACK patch.

- I have also refreshed your patches and removed the last 4 GSWIP patches for now due to the resulting functionality issues. The driver needs to be looked at again independently of the linux update.

- I was also able to fix/work around the problem with the warning regarding field-spanning write in the DSL MEI driver.

- I can only perform tests with xrx200 (VRX268; no voice).

I would like to ask if we can include the intermediate step with linux 6.1, or if I have to update everything to linux 6.6 right away.?

Should I open a new PR or would you like to merge this changes into this one here?

**Comment by sch-m** [comment]
Doing some further tests I've found out there is still more work to do. At least the ltq_atm and ltq-ptm driver also needs an IRQ fix.

**Comment by nouman8** [comment]
Great to see progress being made for this target, cheers to all contributors :)

**Comment by sch-m** [comment]
ltq-vmmc should also work now. I'll have a look at ltq-adsl-mei tomorrow.

**Comment by nouman8** [comment]
@sch-m @hauke i compiled from your 6.1 branch and tested on tplink-w8970 so far lan, wireless and vdsl2 are working.

**Comment by jospezial** [comment]
Can you make use of this?:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=94c437edce65ff8cf71bf8b22801c81f48eefdd6
```
net: dsa: lantiq_gswip: provide own phylink MAC operations
Convert lantiq_gswip to provide its own phylink MAC operations, thus
avoiding the shim layer in DSA's port.c. For lantiq_gswip, it means
we end up with a common instance of phylink MAC operations that are
shared between the different variants, rather than having duplicated
initialisers in dsa_switch_ops.
```

**Comment by jospezial** [comment]
There are a lot of lantiq related commits between 5.15 and 6.8 or  [kernel/git/torvalds/linux.git](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/) head.
But I think it is the best to get this PR here done. Then fast step to 6.6. inclusive useful backports.

**Comment by nouman8** [comment]
@sch-m compiled a minimal build to test on BT-HH5A lan wireless and vdsl working on it too.

**Comment by Snowiiii** [comment]
> @jospezial Repairing and improving the GSWIP driver is another task. I would like to simply update the Lantiq target to linux 6.1 and then to 6.6 in a first step.

Looks like everything works fine with 6.1 so far. I think we can slowly move to 6.6

**Comment by PolynomialDivision** [comment]
What about merging this but don't make it default and than work on 6.6 testing support.

**Comment by sch-m** [comment]
> What about merging this but don't make it default and than work on 6.6 testing support?

@PolynomialDivision Yes, I would prefer it that way too. Then I'll create a new PR, ok?

**Comment by hauke** [comment]
Superseded by #15233 which was just merged

**Pull request closed without merging**
