### PR TITLE
toolchain: gcc: improve patch handling by introducing major version

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Every minor version bump of a major version will result in a huge patch
diff because of the moving of all the patches from version e.g. 11.2.0 to
11.3.0. This commit only use the major version for the patch folders to
differentiate between the different gcc versions. This will significantly
improve the reviewing of the smaller version bump patches and help to see
what really changed in a minor version bump.

### CODE REVIEW

**Comment by jospezial** [comment]
Is somebody there who likes to bump the gcc version to 12.2?
Should it be done in this PR or at least after this is merged?

**Comment by PolynomialDivision** [comment]
> Is somebody there who likes to bump the gcc version to 12.2?

@jospezial I did this here:
https://github.com/openwrt/openwrt/pull/10495
That was why I started with the PR here.

**Comment by mpratt14** [comment]
instead of a subdirectory that is just '10' have the patches folder be named with a dash 'patches-10' 'patches-11' etc.

**Comment by Ansuel** [comment]
@PolynomialDivision good idea instead of subdirectory madness why not change approach and drop the generic patches directory in favor of `patches-10.x patches 11.x ....`

**Comment by PolynomialDivision** [comment]
@Ansuel Yeah of course we can do something like this. I can update the PR. However, I thought you would be more comfortable still having the minor version in the patch-folder name?

**Comment by Ansuel** [comment]
@PolynomialDivision mine was a corner case, the better directory scheme is something that should be done anyway.

I'm stil hesitant about this but if others approve this then OK FOR ME.

Was just a hint and give some credits of a good idea :D

**Review by hauke — APPROVED** [review]
I like this patch.
@Ansuel  Do you often have to use an older minor version of GCC?
I once tried to bisect a problem with GCC, but then I had to use gcc from git anyway.

I think often even all patches are applying on older versions.

**Comment by Ansuel** [comment]
@hauke thanks for the approval and for the info that we have alternative way to test regression.

@PolynomialDivision In this case I'm happy, pls apply the new directory scheme and I will merge this!

**Comment by PolynomialDivision** [comment]
Okay. :) Give me a second, because my laptop is just busy compiling another PR again: https://github.com/openwrt/openwrt/pull/10394 (I think this is also ready to be merged)
Afterwards I will update everything. :)

**Comment by Ansuel** [comment]
@PolynomialDivision draft?

**Comment by PolynomialDivision** [comment]
@Ansuel Sorry, I did this yesterday night. I did this typo you described. When testing the changes I also noticed that gcc was not compiling and so I converted it to a draft, so it does not accidentally picked up. Now everything seems to compile fine. :)

**Comment by Ansuel** [comment]
Tanks, merged in master with d7382cc0e4446d4db1978055b0ba59259ac66751

**Pull request closed without merging**
