### PR TITLE
bcm27xx/bcm2711: disable duplicate driver

### PR DESCRIPTION
**Pull request by graysky2**
Enabling both `CONFIG_MMC_BCM2835` and `CONFIG_MMC_BCM2835_MMC` causes this error in dmesg: `Error: Driver 'sdhost-bcm2835' is already registered, aborting...`

Disabling the `CONFIG_MMC_BCM2835` and leaving `CONFIG_MMC_BCM2835_MMC` enabled avoids this error.

I only tested this on RPi4/unsure if other bcm27xx configs could be adjusted in a like fashion.

Build-tested: bcm2711/RPi4B
Run-tested: bcm2711/RPi4B

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by hauke** [comment]
What are the differences between these two drivers?

**Comment by graysky2** [comment]
The one with the shorter name which I disabled is from upstream linux and the one with the longer name is from the RPi Foundation which is tweaked/faster to my understanding.  The following patches make it available, see:
* [950-0070-MMC-added-alternative-MMC-driver.patch](https://github.com/openwrt/openwrt/blob/master/target/linux/bcm27xx/patches-5.15/950-0070-MMC-added-alternative-[MMC-driver.patch)
* [950-0071-Adding-bcm2835-sdhost-driver-and-an-overlay-to-enabl.patch](https://github.com/openwrt/openwrt/blob/master/target/linux/bcm27xx/patches-5.15/950-0071-Adding-bcm2835-sdhost-driver-and-an-overlay-to-enabl.patch)

**Comment by Noltari** [comment]
@hauke @graysky2 it looks like both of them are enabled because `CONFIG_MMC_BCM2835` is the default for bcm2835, which the upstream config:
https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/configs/bcm2835_defconfig#L130

But `CONFIG_MMC_BCM2835_MMC` is the default for the downstream configs:
https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/configs/bcmrpi_defconfig#L1247
https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/configs/bcm2709_defconfig#L1255
https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/configs/bcm2711_defconfig#L1277

So I think that we should disable CONFIG_MMC_BCM2835 and enable CONFIG_MMC_BCM2835_MMC for all our subtargets.

**Comment by Noltari** [comment]
> @hauke @graysky2 it looks like both of them are enabled because `CONFIG_MMC_BCM2835` is the default for bcm2835, which is the [upstream config](https://github.com/torvalds/linux/blob/master/arch/arm/configs/bcm2835_defconfig#L129): https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/configs/bcm2835_defconfig#L130
> 
> But `CONFIG_MMC_BCM2835_MMC` is the default for the downstream configs: https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/configs/bcmrpi_defconfig#L1247 https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/configs/bcm2709_defconfig#L1255 https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/configs/bcm2711_defconfig#L1277
> 
> So I think that we should disable CONFIG_MMC_BCM2835 and enable CONFIG_MMC_BCM2835_MMC for all our subtargets.

After a closer look, the collision isn't between `CONFIG_MMC_BCM2835` and `CONFIG_MMC_BCM2835_MMC`, but between 'CONFIG_MMC_BCM2835' and `CONFIG_MMC_BCM2835_SDHOST`:
- CONFIG_MMC_BCM2835: https://github.com/raspberrypi/linux/blob/rpi-5.15.y/drivers/mmc/host/bcm2835.c#L1467
- CONFIG_MMC_BCM2835_SDHOST: https://github.com/raspberrypi/linux/blob/rpi-5.15.y/drivers/mmc/host/bcm2835-sdhost.c#L2189
- CONFIG_MMC_BCM2835_MMC: https://github.com/raspberrypi/linux/blob/rpi-5.15.y/drivers/mmc/host/bcm2835-mmc.c#L1553

**Comment by graysky2** [comment]
@Noltari - ah, giving me a headache.  How do you suggest we tweak to avoid the error?

**Comment by Noltari** [comment]
@graysky2 merged in 3f7cc9d0144dbc429d19c1801cc6be149f969db9 with some changes

**Pull request closed without merging**
