### PR TITLE
mt7981b: hide bogus local-mac-address to enable nvmem assignment

### LINKED ISSUE #15507: mac address assignment using nvmem-layout fails for eth0 on mt7981b devices
During the porting work for the [cudy,m3000](https://github.com/openwrt/openwrt/pull/14393), we noticed that the mac address assignment for mac@0 doesn't work through `nvmem-layout`.
I noticed this happened for the yuncore,ax835 during a [cleanup commit](cfee7fa36682be3476b5b27e8affad99c8753934).

Example:

```
&eth {
  pinctrl-names = "default";
  pinctrl-0 = <&mdio_pins>;
    
  status = "okay";
    
  gmac0: mac@0 {
    compatible = "mediatek,eth-mac";
    reg = <0>;
    phy-mode = "2500base-x";
    phy-handle = <&rtl8221b_phy>;

    nvmem-cell-names = "mac-address";
    nvmem-cells = <&macaddr_bdinfo_de00 1>; /* <- doesn't work (even with a 0) */
  };

  gmac1: mac@1 {
    compatible = "mediatek,eth-mac";
    reg = <1>;
    phy-mode = "gmii";
    phy-handle = <&int_gbe_phy>;

    nvmem-cell-names = "mac-address";
    nvmem-cells = <&macaddr_bdinfo_de00 0>;
  };
};

&bdinfo {
          nvmem-layout {
          compatible = "fixed-layout";
          #address-cells = <1>;
          #size-cells = <1>;

          macaddr_bdinfo_de00: macaddr@de00 {
            #nvmem-cell-cells = <1>;
            compatible = "mac-base";
            reg = <0xde00 0x6>;
          };
        };
}l
```

`of_get_mac_address` is called twice for `mac@0`.
the first time, it finds a `local-mac-address` (that doesn't come from bdinfo but is consistent through reboots)
EDIT: no, it's not consistent. i misremembered.
the second time, it finds that same address in `mac-address `.

```
[    1.066786] of_get_mac_address for mac@0
[    1.070710] of_get_mac_address mac-address -19
[    1.075140] of_get_mac_address local-mac-address 0
[    1.079942] of_add_mac_address ret 0: d6:37:bf:39:da:6a

[    1.084809] of_get_mac_address for mac@1
[    1.088725] of_get_mac_address mac-address -19
[    1.093155] of_get_mac_address local-mac-address -19
[    1.098109] of_get_mac_address address -19
[    1.102723] of_get_mac_address nvmem 0: 80:af:ca:15:84:04
[    1.108134] of_add_mac_address ret 0: 80:af:ca:15:84:04

[    1.113001] of_get_mac_address for mac@0
[    1.116920] of_get_mac_address mac-address 0
[    1.121186] of_add_mac_address ret 0: d6:37:bf:39:da:6a
```

The most confusing thing is, there is a `mac-address` in sysfs:
```
$ hexdump -C /sys/firmware/devicetree/base/soc/ethernet@15100000/ma
c@0/mac-address 
00000000  d6 37 bf 39 da 6a                                 |.7.9.j|
```
(EDIT: `of_add_mac_address` puts it there, alright)
`local-mac-address` is also chilling there... why?

How does that get there?!

### OpenWrt target/subtarget

mediatek/filogic

### PR DESCRIPTION
**Pull request by yogo1212**
This fixes https://github.com/openwrt/openwrt/issues/15507.
I wasn't confident enough to do a `Fixes:` because I don't know whether/how it works if two commits are required.

### CODE REVIEW

**Comment by dangowrt** [comment]
Please just remove the `ethernet0` alias to prevent U-Boot-assigned MAC addresses. No kernel patching should be required for that.

**Comment by yogo1212** [comment]
@dangowrt alright - much easier! :+1: 

i can't test on the yuncore right now but it works for the m3000.

**Comment by yogo1212** [comment]
I assumed the `ethernet0` alias was telling U-Boot which devices to initialise in general.
Looking at `fdtdec_set_ethernet_mac_address`, it appears to only set the `local-mac-address` (and only when it exists - unlike this peculiar variety of U-Boot).

Let me put a comment in the dts explaining why there's no `ethernet0`'.

**Comment by john-tho** [comment]
If u-boot leaves DTS alone with this, you may as well add the nvmem macaddress to gmac0 and remove the `02_network` wan_mac setting?

**Comment by yogo1212** [comment]
@john-tho :joy: 
Oh damn! Yes, sure!
Where is my mind..

Thanks

**Comment by yogo1212** [comment]
Thanks :saluting_face:

**Pull request merged**
