### PR TITLE
ath79: add TL-MR3020-V1 support

### PR DESCRIPTION
**Pull request by lucize**
notes: side switch are not used for any actions
everything is working
only ram boot tested ! 
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
@lucize requires a rebase

**Comment by lucize** [comment]
@blogic done

**Comment by blogic** [comment]
@lucize does not work for me, prolly collided with what i just merged, please try one more time on latest HEAD

**Comment by lucize** [comment]
@blogic strange, I'm on the latest github HEAD and github is showing no conflicts..

**Comment by lucize** [comment]
@blogic rebased again, hopefully is ok now !

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
