### PR TITLE
kernel: bump 5.15 to 5.15.107

### PR DESCRIPTION
**Pull request by graysky2**
All  patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B, ramips/tplink_archer-a6-v3, filogic/xiaomi_redmi-router-ax6000-ubootmod
Run-tested: bcm2711/RPi4B, ramips/tplink_archer-a6-v3, filogic/xiaomi_redmi-router-ax6000-ubootmod

### CODE REVIEW

**Comment by Borromini** [comment]
Runs fine here from what I can tell.

Compile-tested: x86/64, ath79/generic, mvebu/cortexa{9,72}, ramips/mt76{20,21,x8}, realtek/RTL{838,930}x.
Run-tested: ramips/mt7621 (EAP615-Wall), mvebu/cirtexa72 (RB5009UG+S+IN).

**Comment by pkgadd** [comment]
v5.15.107 will require packaging changes to qrtr, as this breaks the build for ipq807x:
```
SHELL= flock /tmp/pkg/openwrt/tmp/.root-copy.flock -c 'cp -fpR /tmp/pkg/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/packages/.pkgdir/kernel/. /tmp/pkg/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/'
touch /tmp/pkg/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp/.kernel_installed
ERROR: module '/tmp/pkg/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.15.107/net/qrtr/ns.ko' is missing.
make[3]: *** [modules/netsupport.mk:1458: /tmp/pkg/openwrt/bin/targets/ipq807x/generic/packages/kmod-qrtr_5.15.107-1_aarch64_cortex-a53.ipk] Error 1
```

This is caused by https://lkml.kernel.org/r/<20230412082824.315901983@linuxfoundation.org>, which merges qrtr/ns.ko into qrtr.ko.

**Comment by pkgadd** [comment]
I've successfully testing this change on top of this PR on a Xiaomi ax3600:
```
v5.15.107: fix up qrtr packaging

qrtr/ns.ko is now merged into qrtr/qrtr.ko, so drop the individual module packaging.

Signed-off-by: Stefan Lippers-Hollmann <s.l-h@gmx.de>

--- a/package/kernel/linux/modules/netsupport.mk
+++ b/package/kernel/linux/modules/netsupport.mk
@@ -1446,8 +1446,7 @@ define KernelPackage/qrtr
   DEPENDS:=@!LINUX_5_10
   KCONFIG:=CONFIG_QRTR
   FILES:= \
-  $(LINUX_DIR)/net/qrtr/qrtr.ko \
-  $(LINUX_DIR)/net/qrtr/ns.ko
+  $(LINUX_DIR)/net/qrtr/qrtr.ko
   AUTOLOAD:=$(call AutoProbe,qrtr)
 endef
 

```

With the patch above:

Compile-tested (v5.15.107):
- at79
- ipq40xx
- ipq806x
- ipq807x
- lantiq/xrx200
- ramips/mt7621
- realtek/rtl838x
- x86_64

Run-tested (v5.15.107):
- x86_64 (baytrail-d/ j1900)
- ipq807x (xiaomi ax3600)
- ramips/mt7621 (dap-x1860)

```
Tested-by: Stefan Lippers-Hollmann <s.l-h@gmx.de> #ipq807x/ax3600, x86_64/FW-7543B, mt7621/dap-x1860
```

**Comment by graysky2** [comment]
@pkgadd - I pulled your patch out of your comment and saved it to `p.patch` and am trying to add your patch via `git am` but am getting this error:
```
git am p.patch
Applying: 
fatal: empty ident name (for <>) not allowed
```

**Comment by pkgadd** [comment]
Thanks for integrating it (and sorry for the trouble).

**Pull request merged**
