### PR TITLE
mwlwifi: pcie timeout issue

### PR DESCRIPTION
**Pull request by anomeome**
compile/test target mvebu/mamba, rango

Signed-off-by: Kabuli Chana <newtownBuild@gmail.com>

### CODE REVIEW

**Comment by dengqf6** [comment]
4.15 support is already included.
Please, fix your commit title

**Comment by manjuprajna** [comment]
@anomeome 
it seems that sha256sum should be 3bb9ac27479da2c651ab5a0d11094b254acc27572c608db86da9858f11b6b416
and release date is March 3

**Comment by anomeome** [comment]
I took the commit message of the previous mwlwifi push at face value and just reconciled it against the upstream git log.

**Comment by dengqf6** [comment]
You have not corrected the commit title yet.
Please use `git commit --amend`, edit the commit title and then `git push -f` to override this PR.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
