### PR TITLE
lantiq: fritz 7360 v2: fixups

### PR DESCRIPTION
**Pull request by lynxis**
Implements @adrianschmutzler recommendations.

### CODE REVIEW

**Comment by lynxis** [comment]
@Rising-Sun

**Comment by adrianschmutzler** [comment]
Reviewed-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>

Thanks for taking care so quickly.

**Comment by lynxis** [comment]
@Rising-Sun if you have time to test

**Comment by Rising-Sun** [comment]
run a sysupgrade with the force option. Upgrade went well and device is running. I am using the testing kernel (5.4).

**Pull request closed without merging**
