### PR TITLE
x86: add 6.1 testing support

### PR DESCRIPTION
**Pull request by PolynomialDivision**
ping @thuehn

### CODE REVIEW

**Comment by pkgadd** [comment]
Thanks for looking into this :)

While testing, I'm falling over:
```
  Xen Dom0 support (XEN_DOM0) [Y/n/?] y
  Always use safe MSR accesses in PV guests (XEN_PV_MSR_SAFE) [Y/n/?] (NEW) make[7]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[6]: *** [Makefile:704: syncconfig] Error 2
```
in my previous attempt of upgrading x86_64 to v6.1, I chose to set `CONFIG_XEN_PV_MSR_SAFE=y` (`target/linux/x86/64/config-6.1`).

**Comment by pkgadd** [comment]
Just for reference, I've slightly cleaned up my WIP patches in
https://github.com/openwrt/openwrt/compare/main...pkgadd:openwrt:x86_64-v61-WIP-0

This is not complete/ fully tested (e.g. I know that `kmod-hwmon-nct6775` will need packaging changes, to adapt for the module split in 

https://github.com/torvalds/linux/commit/6bb77c55b05fccea588fdc069008fa81e7359679

I expect there to be more changes necessary, the above is just a snapshot of the work where I had to abandon it due to lack of time - it's (mostly-) untested and just a code drop.

**Comment by PolynomialDivision** [comment]
@pkgadd Can you take over? I will close. The next days I have to travel again without my laptop. So I can't continue with it. Thanks a lot for all your work and comments. :)

**Comment by pkgadd** [comment]
It will take some time, as I'm rather busy right now as well. 
I'll have a look, but no promises yet (I didn't enable `CONFIG_ALL_KMODS=y` or `CONFIG_ALL_NONSHARED=y` yet and so far didn't even look at 32 bit at all).

**Comment by graysky2** [comment]
Can one of you guys explain how one should generate `target/linux/x86/generic/config-6.1`?  I grabbed this PR and https://github.com/openwrt/openwrt/pull/12996 but found that there way tons of missing symbols.  Thanks.

**Comment by pkgadd** [comment]
As I didn't want to create unnecessary merge issues for @graysky2, I've pushed my pending working set into a new branch at

https://github.com/pkgadd/openwrt/tree/x86_64-v61-WIP-1

this now compiles (and works, Atom-j1900) for me (x86_64 only, didn't touch any 32 bit subtargets, yet) with CONFIG_ALL_KMODS=y and CONFIG_ALL_NONSHARED=y.

The remaining issues 'should' now just be updating the kernel-config snippets for the three 32 bit subtargets (my method is rather convoluted).

Open issues (not x86_64 specific):
- https://github.com/openwrt/openwrt/pull/12746
- https://github.com/openwrt/telephony/pull/786
- coova-chili has been fixed a few days ago

This works for me, it's not quite PR-worthy at this point, but just to provide my current (working) code.

**Comment by graysky2** [comment]
Great job wit the rework.  Does it make sense for you to make a draft PR with your changes to 64?  Are you eventually planning to do 32-bit or would someone else pick that up and add to it?

**Comment by pkgadd** [comment]
afaik subtargets can declare different `KERNEL_PATCHVER` versions, but that's kind of ugly…

While I'd love if someone else would take a look at the i386 targets, I guess it'll end up on my desk - if I want to get x86_64 in.

Orthogonally to this, do we really need *three* i386 subtargets?!
(if it were a single one, I'd probably have already done it; sadly recent qemu has dropped 32-bit-only CPU emulations (Debian/unstable), making it a tad harder to confirm (kconfig likes to sneak `64BIT` into the config, when run on an x86_64 host).

**Comment by graysky2** [comment]
I can't speak to the three i386 subtargets... why not use `KERNEL_PATCHVER` to get 64 out there?

**Comment by graysky2** [comment]
@pkgadd - can you explain how I can tweak some kernel settings and then eventually diff them against `target/linux/x86/64/config-6.1`?  Is it `make kernel_menuconfig CONFIG_TARGET_x86_64`?  Doing that does not honor the testing kernel and goes into the 5.15.y kernel.  Thanks.

**Comment by graysky2** [comment]
Also, you forgot at set `KERNEL_TESTING_PATCHVER:=6.1` in `target/linux/x86/Makefile`

**Comment by trippleflux** [comment]
For me by the different OpenWrt steps would be : 
```
git clone https://github.com/pkgadd/openwrt.git -b x86_64-v61-WIP-1
```

Kudos to @PolynomialDivision & @pkgadd , thanks for taking care and supporting x86_64!.

**Comment by trippleflux** [comment]
@pkgadd 
I haven't tested it out thoroughly, it seems that IPV6 support is broken  in this PR.

**Comment by pkgadd** [comment]
> I haven't tested it out thoroughly, it seems that IPV6 support is broken in this PR.

Please re-check and provide some further details, I'm using the version above on my main router and am using IPv6 very actively, internally, externally, with DHCPv6, with SLAAC, incoming wireguard connections (which, 'thanks' to cgNAT can only connect via IPv6), outgoing traffic.

nlbwmon

**Comment by graysky2** [comment]
@pkgadd @PolynomialDivision - do either of you have some time to finalize the PR?  I can help but don't want to duplicate efforts.

**Comment by JimMatthew** [comment]
@pkgadd I cloned your repo but when I built it I got the 5.15 kernel, how do I make it build the 6.1 kernel? It didn't seem to like it when I added the testing_kernel option in the config.

**Pull request closed without merging**
