### PR TITLE
Add support for DIR-853-R1

### PR DESCRIPTION
**Pull request by fiduchi**
Add support for DIR-853-R1

This PR adds suppotr for router Dlink DIR-853-R1

Specifications:

    SoC: MT7621AT
    RAM: 128MB
    Flash: 16MB SPI
    WiFi: MT7615DN (2.4GHz+5Ghz) with DBDC (This mode allows
    this single chip act as an 2x2 11n radio and an 2x2 11ac radio at the
    same time)
    LAN: 5x1000M
    LEDs Power Blue+Orange,Wan Blue+Orange,WPS Blue,"2.4G"Blue, "5G" Blue,
    USB Blue
    Buttons Reset,WPS, Wifi

lan factory 0xe000 CD(label)
wan factory 0xe006 D0
2.4 GHz factory 0xe000+1 ECCE
5.0 GHz factory 0xe000+2 6ECE

Flashing instruction:

The Dlink "Emergency Room"

Connect your client computer to LAN1 of the device
Set your client IP address manually to 192.168.0.101 / 255.255.255.0.
Then, power down the router, press and hold the reset button, then
re-plug it. Keep the reset button pressed until the internet LED stops
flashing
Call the recovery page or tftp for the device at http://192.168.0.1
Use the provided emergency web GUI to upload and flash a new firmware to
the device.

Signed-off-by: Stas Fiduchi fiduchi@protonmail.com

### CODE REVIEW

**Comment by fiduchi** [comment]
PR #4086 не могу переоткрить так как он был удален и востановить нельзя.

**Comment by adschm** [comment]
Really? Do you really think another reopen will be a good idea after I disliked the last one... Please use the initial PR.

**Comment by mpratt14** [comment]
@fiduchi ok try this

```
git checkout -b dir-853
git branch -D master
git checkout 19c41a6c50c7fe8a337685d19f4a3b6f2d6b82bb
git checkout -b master
git push --force origin master
```

then, reopen PR #4086 

after it is reopened

```
git checkout master
git reset --hard HEAD^
git cherry-pick 19c41a6c50c7fe8a337685d19f4a3b6f2d6b82bb
git push --force origin master
```

**Comment by mpratt14** [comment]
sorry post had mistake, see edit

```
git cherry-pick 1e72a7bc39da457b99fb9ff3371df91cafb1e5be
```

**Comment by fiduchi** [comment]
> git checkout 19c41a6c50c7fe8a337685d19f4a3b6f2d6b82bb

~/Github/openwrt(dir-853) » git checkout 19c41a6c50c7fe8a337685d19f4a3b6f2d6b82bb
fatal: в дереве нет такой ссылки: 19c41a6c50c7fe8a337685d19f4a3b6f2d6b82bb

**Comment by adschm** [comment]
Maybe it's easiest to first directly check out the branch from the PR ...

**Comment by mpratt14** [comment]
@fiduchi OK, I figured it out

```
git branch -D master
git fetch https://github.com/openwrt/openwrt.git pull/4086/head
git checkout 19c41a6c50c7fe8a337685d19f4a3b6f2d6b82bb
git checkout -b master
git push --force https://github.com/fiduchi/openwrt.git master
```

then reopen #4086 

@adschm if this works, add this method to the wiki for deleted forks

**Comment by fiduchi** [comment]
> @fiduchi ОК, я разобрался
> 
> ```
> git branch -D master
> git fetch https://github.com/openwrt/openwrt.git pull/4086/head
> git checkout 19c41a6c50c7fe8a337685d19f4a3b6f2d6b82bb
> git checkout -b master
> git push --force https://github.com/fiduchi/openwrt.git master
> ```
> 
> затем снова [откройте # 4086 ](https://github.com/openwrt/openwrt/pull/4086)
> 
> @adschm, сработает если это , добавьте этот метод в вики для удаленных вилок

I also can't open # 4086. The button is not active. Here is the message (The repository that sent this transfer request was deleted.)

**Comment by fiduchi** [comment]
Guys please help. Accidentally closed Pull Request 4086 and deleted the repo. You can not delete PR 4086 so I can create a new one.

**Comment by kar200** [comment]
@mpratt14 Can you please let me know if you have managed to get this working? I know @fiduchi did not and ended up reopening a new pull request but I want to reopen mine [mine](https://github.com/openwrt/openwrt/pull/3318) now that everything is working with the device. 

I have been trying for days now (obviously not full time lol) but for the life of me I cannot get it to work. I tried several different guides but the reopen button is greyed out.

I found a quick way to set the tree to a specific PR is by using github cli. 
````
gh pr checkout 3318
````

But! Apparently the repo has to be at the same state as when the pull request was "closed" and not "last commit created". Is that for my own repo or is that for openwrt repo?

My repo had just my commits when it was closed but openwrt with several commits a day was way ahead.

**Pull request closed without merging**
