### PR TITLE
Fix untested merge of TL-WR841N-v11 backport

### PR DESCRIPTION
**Pull request by karlp**
Fixes: f98117a065f05ddd1ab3d082fc7aea67f98cbd05

Signed-off-by: Karl Palsson <karlp@etactica.com>

### CODE REVIEW

**Comment by karlp** [comment]
checks have failed but the details link is empty?  if the tests are broken please just disable them

**Comment by wigyori** [comment]
@lperkov, can you please check the drone.io stuff?

@karlp - thanks for the fix, looks like we'll have to get back to more testing of the individual PRs.

-w-

**Comment by wigyori** [comment]
Just noticed - can you please fix the commit title to have the ar71xx prefix.

Thx,
-w-

**Comment by karlp** [comment]
Alternative version has landed.

**Pull request closed without merging**
