### PR TITLE
lantiq: switch to 6.6

### PR DESCRIPTION
**Pull request by sch-m**
@hauke 
Let's switch the lantiq target to kernel 6.6 and remove the 5.15 and 6.1 support.

Also update the gswip patches to the already upstream versions.

### CODE REVIEW

**Comment by sch-m** [comment]
I have just discovered that there are still problems with the ltq-tapi driver. I'll look into it and update the PR.

**Comment by dangowrt** [comment]
Getting `drv_tapi` to compile was not hard:
https://github.com/dangowrt/openwrt/commit/cccf08e8e2903a10815c114ac1d62272d2a56927

However, there are still some other problems:
```
[    0.569899] lantiq,vmmc 1f107000.vmmc: reserved 1MB at 0x(ptrval)
[   60.459491] rcu: INFO: rcu_sched detected stalls on CPUs/tasks:
[   60.465273] rcu:     (detected by 0, t=6002 jiffies, g=-1183, q=165 ncpus=2)
[   60.472126] rcu: All QSes seen, last rcu_sched kthread activity 5989 (-23959--29948), jiffies_till_next_fqs=1, root ->qsmask 0x0
[   60.483758] rcu: rcu_sched kthread timer wakeup didn't happen for 5988 jiffies! g-1183 f0x2 RCU_GP_WAIT_FQS(5) ->state=0x200
[   60.495042] rcu:     Possible timer handling issue on cpu=1 timer-softirq=9
[   60.501813] rcu: rcu_sched kthread starved for 5989 jiffies! g-1183 f0x2 RCU_GP_WAIT_FQS(5) ->state=0x200 ->cpu=1
[   60.512142] rcu:     Unless rcu_sched kthread gets sufficient CPU time, OOM is now expected behavior.
[   60.521169] rcu: RCU grace-period kthread stack dump:
[   60.526291] task:rcu_sched       state:R stack:0     pid:15    ppid:2      flags:0x00100000
[   60.534712] Stack : 00000004 ffff8b05 00000000 809f0000 809eac2c 808dc194 00000000 00000002
[   60.543130]         00000000 81836820 80980000 00000001 80980000 00000000 809f0000 809eac2c
[   60.551550]         809f0000 80782c80 80980000 00000000 809f0000 809eac2c ffff8b05 80787ae4
[   60.559970]         809eaac0 00000001 80980000 00000000 00000000 8100b670 ffff8b05 800b45b8
[   60.568390]         01800001 81836820 809eaac0 809eaac0 00000000 800a44f0 00000000 00000002
[   60.576809]         ...
[   60.579328] Call Trace:
[   60.581844] [<807828ec>] __schedule+0x42c/0x770
[   60.586450] [<80782c80>] schedule+0x50/0xb4
[   60.590700] [<80787ae4>] schedule_timeout+0x68/0xe4
[   60.595648] [<800a44f0>] rcu_gp_fqs_loop+0x418/0x540
[   60.600683] [<800a8864>] rcu_gp_kthread+0x16c/0x1ac
[   60.605631] [<800581d4>] kthread+0x104/0x12c
[   60.609970] [<80006cb8>] ret_from_kernel_thread+0x14/0x1c
[   60.615441] 
[   60.617000] rcu: Stack dump where RCU GP kthread last ran:
[   60.622556] Sending NMI from CPU 0 to CPUs 1:
```

**Comment by sch-m** [comment]
> Getting `drv_tapi` to compile was not hard: [dangowrt@cccf08e](https://github.com/dangowrt/openwrt/commit/cccf08e8e2903a10815c114ac1d62272d2a56927)
> 

Thanks. I've added your commit here.

> However, there are still some other problems...

Well, I have to say that I really hate all these lantiq components regarding "voice".

If we could just drop this functionality, we would get rid of a lot of ugly patches and packages.
I don't know if and how many really use these features nowadays.

**Comment by dangowrt** [comment]
> Well, I have to say that I really hate all these lantiq components regarding "voice".

I tried adding `return 1` as first line in the probe function of vmmc which now fails to probe and prevent all the other voice components depending on it from being loaded. Sadly the problem persists.

**Comment by sch-m** [comment]
Yes, I'm also looking at it right now and try to find the cause. 

When I add maxvpes=1 maxtcs=1 nosmp to the bootargs of my VRX268 based device, the boot also hangs.

If I try the same with linux 6.1, the bootup works.

If I insert a `goto out_reenable;` before the `/* deactivate all but vpe0 */` in the `vpe_module_init()` function, the bootup also works.

@dangowrt Which device do you use for testing?

**Comment by dangowrt** [comment]
I got arcadyan,vgv7510kw22-nor ("o2 Box 6431") sitting on my desk with serial console attached at the moment.

**Comment by dangowrt** [comment]
@kochstefan Any ideas maybe what could be wrong with non-Linux usage of that VPE causing boot to get stuck...?

**Comment by sch-m** [comment]
After comparing the kernel messages of linux 6.1 and 6.6 again, I noticed that with linux 6.6 a 2nd CPU is still initialized despite the `nosmp` option.

Linux 6.1:
```
...
[    0.100890] cblist_init_generic: Setting adjustable number of callback queues.
[    0.108033] cblist_init_generic: Setting shift to 1 and lim to 1.
[    0.114860] rcu: Hierarchical SRCU implementation.
[    0.119562] rcu:     Max phase no-delay instances is 1000.
[    0.125983] smp: Bringing up secondary CPUs ...
[    0.130426] smp: Brought up 1 node, 1 CPU
...
```

Linux 6.6:
```
...
[    0.125512] RCU Tasks Trace: Setting shift to 1 and lim to 1 rcu_task_cb_adjust=1.
[    0.133964] rcu: Hierarchical SRCU implementation.
[    0.138603] rcu:     Max phase no-delay instances is 1000.
[    0.145219] smp: Bringing up secondary CPUs ...
[    0.151321] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.151365] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.151485] CPU1 revision is: 00019556 (MIPS 34Kc)
[    0.204091] Synchronize counters for CPU 1: done.
[    0.228362] smp: Brought up 1 node, 2 CPUs
...
```

Using `maxcpus=1` instead of `nosmp` let the system boot up normally.

@dangowrt Could you please verify this with your hardware?

**Comment by sch-m** [comment]
Ah, and here is already the fix:
https://github.com/torvalds/linux/commit/6ef8eb5125722c241fd60d7b0c872d5c2e5dd4ca

**Comment by sch-m** [comment]
I would create a backport patch for linux 6.6 for this fix. But I'm not quite sure if we shouldn't backport this commit as well:

https://github.com/torvalds/linux/commit/4c8a49854130da0117a0fdb858551824919a2389

**Comment by dangowrt** [comment]
Confirming that now everything is fine, including telephony features (I've tested incoming and outgoing calls, both audio and signalling work as expected).

**Comment by abajk** [comment]
One module does not build on kernel 6.6 (kmod-ltq-adsl).

**Comment by dangowrt** [comment]
> One module does not build on kernel 6.6 (kmod-ltq-adsl).

On which subtarget? Because for xrx200 it does build for me (`ltq_atm_vr9.ko` exists), I just can't test it, nothing but fiber here where I live ;)

**Comment by sch-m** [comment]
> One module does not build on kernel 6.6 (kmod-ltq-adsl).

Haven't you already fixed it yourself with #15706?

**Comment by sch-m** [comment]
I've added another patch to fix the enum-conversion warnings in `kmod-ltq-adsl`.

**Comment by FlyGoat** [comment]
I'd suggest you to disable `CONFIG_MIPS_VPE_LOADER_MT` for Lantiq (and possibility all MIPS MT) targets.
This option will interfere kernel's smp-mt functionality.
As we are not offloading anything to TCs enabling it makes no sense to me.

**Comment by dangowrt** [comment]
Did you take into account that we *are* using the 2nd VPE to run Lantiq telephony RTOS on it and enjoy VoIP functionality on some devices.

**Comment by FlyGoat** [comment]
Ah sorry I was not aware of that, I was trying to massage MT stuff at kernel side.
I will take that into account.

**Comment by uyguremre** [comment]
> Did you take into account that we *are* using the 2nd VPE to run Lantiq telephony RTOS on it and enjoy VoIP functionality on some devices.

Is there a way to use the second core for other functions to increase performance if we are not interested in VoIP?

**Comment by dangowrt** [comment]
> Is there a way to use the second core for other functions to increase performance if we are not interested in VoIP?

Yes, but you will have to edit `/chosen/bootargs` in DT. On devices without any VoIP features (such as the TL-W8970B) we do use both cores for Linux.

**Comment by uyguremre** [comment]
> > Is there a way to use the second core for other functions to increase performance if we are not interested in VoIP?
> 
> Yes, but you will have to edit `/chosen/bootargs` in DT. On devices without any VoIP features (such as the TL-W8970B) we do use both cores for Linux.

Thanks for the info, so my device homhub5a i am assuming i edit the file vr9_bt_homehub-v5a.dts

currently code is as follows, what would i change it to for using all vpes without voip please?
`	chosen {
		bootargs = "console=ttyLTQ0,115200";
	};`

**Comment by dangowrt** [comment]
> Thanks for the info, so my device homhub5a i am assuming i edit the file vr9_bt_homehub-v5a.dts

On this board you are already using both CPU cores for Linux, VoIP features (if any) are apparently not supported in OpenWrt. So no need to edit anything. You can confirm that both cores are used with Linux if they both show up in `/proc/cpuinfo`.

**Comment by uyguremre** [comment]
Compiled and installed just now, everything works just fine (adsl, wireless, ethernet) on BT Home Hub 5A.
image

**Comment by sch-m** [comment]
I would like to get some lantiq kernel patches upstream.

@abajk What about this patch here?
[0302-mtd-cfi_cmdset_0001-Disable-write-buffer-functions-i.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0302-mtd-cfi_cmdset_0001-Disable-write-buffer-functions-i.patch)

First, I wonder why this patch is in target lantiq. It is actually target-independent.
Secondly, it should be easily accepted upstream.
Don't you want to send it upstream?


These two patches regarding USB also look to me like they should be relatively easy to get into the kernel:
[0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch)
[0051-MIPS-lantiq-improve-USB-initialization.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0051-MIPS-lantiq-improve-USB-initialization.patch)

@hauke What do you think?

**Comment by abajk** [comment]
> > One module does not build on kernel 6.6 (kmod-ltq-adsl).
> 
> Haven't you already fixed it yourself with #15706?

I think I had a patch locally that disables treating enum conversions as an error and forgot to fix it at the time. Now it looks okay.

**Comment by abajk** [comment]
> I would like to get some lantiq kernel patches upstream.
> 
> @abajk What about this patch here? [0302-mtd-cfi_cmdset_0001-Disable-write-buffer-functions-i.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0302-mtd-cfi_cmdset_0001-Disable-write-buffer-functions-i.patch)
> 

[Patchwork](https://patchwork.ozlabs.org/project/linux-mtd/patch/20230514093935.4679-1-olek2@wp.pl/)

> First, I wonder why this patch is in target lantiq. It is actually target-independent.

It seems to me that this applies only to lantiq. It is caused by this patch https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0300-MTD-cfi-cmdset-0001-disable-buffered-writes.patch

> Secondly, it should be easily accepted upstream. Don't you want to send it upstream?

I can refresh and resend the patch if there are conflicts.

**Comment by abajk** [comment]
> These two patches regarding USB also look to me like they should be relatively easy to get into the kernel: [0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch) [0051-MIPS-lantiq-improve-USB-initialization.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0051-MIPS-lantiq-improve-USB-initialization.patch)
> 
> @hauke What do you think?

I'm sure Hauke tried to send these patches upstream but got no feedback. I can't find them now. I think they were sent to the old MIPS maling list and it might be worth sending them again to the new one.

**Comment by hauke** [comment]
Thank you for the PR. Merged it in 289f0ef40388dafc66bb3e5f3a37706bfa98c17a, 8a40d49a563bac15fd61468d322c7aa875aefb3e, 4624711139dff1d9afdfad1bbc244517c51830c5, 48d0068bb14b982671910f369507c7fd9a5b2392, a0e254826c5ef91a086c79329274f2b8e7bbe908, 04fde449733741cb60ad9a308011a0368b964be5 and 75cd4ef48dffea8c659605786cf426962dd6bfc4

**Comment by hauke** [comment]
I do not know why I did not send the 2 patches upstream 7 years ago, will do so.

**Comment by hauke** [comment]
> These two patches regarding USB also look to me like they should be relatively easy to get into the kernel: [0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch) [0051-MIPS-lantiq-improve-USB-initialization.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0051-MIPS-lantiq-improve-USB-initialization.patch)
> 
> @hauke What do you think?

**Comment by sch-m** [comment]
> > These two patches regarding USB also look to me like they should be relatively easy to get into the kernel: [0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch) [0051-MIPS-lantiq-improve-USB-initialization.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0051-MIPS-lantiq-improve-USB-initialization.patch)
> > @hauke What do you think?
> 
> I do not know why I did not send the 2 patches upstream 7 years ago, will do so.

That would be great. Thank you.

**Comment by hauke** [comment]
> > > These two patches regarding USB also look to me like they should be relatively easy to get into the kernel: [0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0050-USB-DWC2-make-the-lantiq-settings-match-vendor-drive.patch) [0051-MIPS-lantiq-improve-USB-initialization.patch](https://github.com/openwrt/openwrt/blob/main/target/linux/lantiq/patches-6.6/0051-MIPS-lantiq-improve-USB-initialization.patch)
> > > @hauke What do you think?
> > 
> > 
> > I do not know why I did not send the 2 patches upstream 7 years ago, will do so.
> 
> That would be great. Thank you.

Both patches were accepted upstream. I hope they still got into 6.11.

**Comment by namiltd** [comment]
@sch-m Maybe instead of:
```
CONFIG_CRYPTO_CURVE25519=y
CONFIG_CRYPTO_LIB_CURVE25519_GENERIC=y
```
it would be better:
```
# CONFIG_CRYPTO_MANAGER_DISABLE_TESTS is not set
# CONFIG_CRYPTO_MANAGER_EXTRA_TESTS is not set
```

**Pull request closed without merging**
