### PR TITLE
kernel: bump 5.4 to 5.4.63

### PR DESCRIPTION
**Pull request by graysky2**
Manual merged:
```
 hack-5.4
  230-openwrt_lzma_options.patch (with Adrian Schmutzler's help)
 bcm27xx
  950-0283-hid-usb-Add-device-quirks-for-Freeway-Airmouse-T3-an.patch
 x86
  patches-5.4
	 011-tune_lzma_options.patch (with Adrian Schmutzler's help)
```
Remove upstreamed patches in collaboration with Ansuel Smith:
```
 ipq806x
  093-1-v5.8-ipq806x-PCI-qcom-Add-missing-ipq806x-clocks-in-PCIe-driver.patch
  093-2-v5.8-ipq806x-PCI-qcom-Change-duplicate-PCI-reset-to-phy-reset.patch
  093-3-v5.8-ipq806x-PCI-qcom-Add-missing-reset-for-ipq806x.patch
```
All other modifications made by update_kernel.sh

Build system: x86_64
Run-tested: ipq806x (R7800)

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by neheb** [comment]
Removed patches are always nice :).

**Comment by graysky2** [comment]
Yeah, I don't understand how my branch got out-of-sync.  I played around for a while bit but I don't have unlimited time to try to get to the bottom of it, so I just closed https://github.com/openwrt/openwrt/pull/3383 and redid the work against a more recent commit.

**Comment by curtdept** [comment]
Build and Run Tested by: Curtis Deptuck curtdept@me.com (x86/64)

**Comment by adschm** [comment]
Thanks, will merge this during the next hour.

**Pull request closed without merging**
