### PR TITLE
[23.05] ath11k-firmware: update to stable WLAN.HK.2.9.0.1-01862

### PR DESCRIPTION
**Pull request by kwiateusz**
cherry pick from https://github.com/openwrt/openwrt/commit/e6b72de70367044260a6077bba3a91da463feaab

### CODE REVIEW

**Comment by tiagogaspar8** [comment]
Hi,
I have no power of course, but I'd like to object to this because this fw breaks IPv6 connectivity on WiFi.

**Comment by kwiateusz** [comment]
Looks like nobody is using ipv6 because there's no others reports from main branch. I'll try to check this. Can you provide some steps to reproduce that problem?

**Comment by tiagogaspar8** [comment]
Maybe people just don't notice, I noticed it because I was obsessed with ipv6 and because I only connect to devices locally over ipv6, so when it doesn't work it's obvious.
To reproduce you just need advertisements enabled and a WiFi device, and after some time router advertisements stop reaching WiFi devices (about a day).
It almost seems a timer is reached in the firmware and the device stops forwarding the multicast packets.

**Comment by greem** [comment]
> Maybe people just don't notice, I noticed it because I was obsessed with ipv6 and because I only connect to devices locally over ipv6, so when it doesn't work it's obvious. To reproduce you just need advertisements enabled and a WiFi device, and after some time router advertisements stop reaching WiFi devices (about a day). It almost seems a timer is reached in the firmware and the device stops forwarding the multicast packets.

See https://github.com/openwrt/openwrt/pull/13203

**Comment by robimarko** [comment]
@tiagogaspar8 What is the last FW revision that works?

**Comment by kwiateusz** [comment]
`01385` is in march release

**Comment by robimarko** [comment]
Ok, that kind of matches the last release that was mostly stable for me as well.

**Comment by tiagogaspar8** [comment]
Hi @robimarko , I'm still testing and I'm on vacation so, testing is taking a bit longer than expected, but I think the last version known to work for me is really 2.5.0, which I know it's super buggy (although with the latest driver patches I haven't found any) so this is really bad news, let's hope they notice this and fix it in later revisions 😅😅😅

**Comment by PalebloodSky** [comment]
On the forum thread it was posted that under wi-fi settings checking 'multicast-to-unicast' resolved an ipv6 issue. Might be related to the issue mentioned here:

https://forum.openwrt.org/t/dynalink-dl-wrx36-askey-rt5010w-ipq8072a-technical-discussion/110454/2083

https://forum.openwrt.org/t/dynalink-dl-wrx36-askey-rt5010w-ipq8072a-technical-discussion/110454/2089

**Comment by richardkendi** [comment]
https://github.com/quic/upstream-wifi-fw/commit/534f635e2073fae6845b079c76cba3021ab7a271

New version

**Comment by tiagogaspar8** [comment]
> On the forum thread it was posted that under wi-fi settings checking 'multicast-to-unicast' is a work-around for the ipv6 issue.

That should not be the solution.

> New version

I'm trying it as we speak, I'll get back with feedback. 😄

**Comment by tiagogaspar8** [comment]
I can confirm the latest version has multicast broken too...

**Comment by robimarko** [comment]
QCA is really trying to outdo themselves with the broken FW-s marked as stable.

**Comment by hauke** [comment]
@robimarko  Should I merge this or should we go back to the testing version?
As I understood the FW currently in 23.05 is as bad as this one. 

Did someone report this problem to QCA?

**Comment by robimarko** [comment]
It won't hurt to merge it for now, but for 23.05 I would go back to `01837` or `01385` as multicast should work in those.

I dont think it is reported, they dont really have a place to report FW issues to, we could try reporting in the ath11k bugzilla though.

**Comment by kwiateusz** [comment]
As this will be reverted I think will be better to close this PR instead of merging. There will be less work to do.

**Comment by hauke** [comment]
@robimarko  Will you create a pull request for 23.05?
Should we update master to the most recent version in #13344?

**Comment by robimarko** [comment]
@hauke Sure, I can make a PR to revert to a more stable FW.

Yes, I would personally update the master to the latest FW for now.

**Comment by Soromeister** [comment]
How do you people test this? I have ipv6 connectivity but also use ipv4 in parallel. Is there a specific way to test other than websites like test-ipv6.com ? I have this fw and ipv6 works for me by testing via that website.

**Comment by tiagogaspar8** [comment]
What I do is run a wireshark capture and see when the RAs stop. You can increase the RA interval in the router settings for this to become more evident.

**Pull request closed without merging**
