### PR TITLE
kernel: bump 6.6 to 6.6.28

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.6.28
    
Removed upstream:
            pending-6.6/796-net-dsa-mt7530-trap-link-local-frames-regardless-of-.patch
    
All oither patches automatically rebased.
    
1.. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.6.28&id=8b6c4b62582606c62074a7e7c64156f56d2785f2
    
Build system: x86/64
Build-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3
Run-tested: x86/64/AMD Cezanne, flogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3

### CODE REVIEW

**Comment by graysky2** [comment]
I cannot build for x86/64 due to an error, see this [forum post](https://forum.openwrt.org/t/build-error-with-libbpf-path-forward/195131).

**Comment by robimarko** [comment]
@graysky2 Thanks for this, I rebased it to see if any patches need to be refreshed again so we dont have to deal with that later.

**Comment by robimarko** [comment]
> ...do we know why bcm53xx with the external toolchain has been failing over these past few weeks?

Yes, a fix has been pending:
https://github.com/openwrt/openwrt/pull/15042

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
