### PR TITLE
[RFC] bcm27xx: support booting from USB/NVMe

### PR DESCRIPTION
**Pull request by Noltari**
This is my attempt to add USB booting to Raspberry Pi. There have been other attempts in the past, such as https://github.com/openwrt/openwrt/pull/9843
Comments/ideas are welcome :)

### CODE REVIEW

**Comment by Noltari** [comment]
I've just pushed a new version which fixes restoring configs with sysupgrade.
LuCI seems to be broken because it doesn't call `sysupgrade -r` and calls tar directly instead...

**Comment by Noltari** [comment]
I think that all the issues are now fixed and even downgrading to and upgradin from 23.05.2 works...

**Comment by mj22226** [comment]
@Noltari Good job, tested on rpi 4/5, also on the RPi5 boot from NVMe SSD is working.
```
RPi: BOOTSYS release VERSION:30cc5f37 DATE: 2024/01/05 TIME: 15:57:40
BOOTMODE: 0x06 partition 0 build-ts BUILD_TIMESTAMP=1704470260 serial b2cbb548 boardrev c04170 stc 1605080
AON_RESET: 00000003 PM_RSTS 00000020
RP1_BOOT chip ID: 0x20001927
PM_RSTS: 0x00000020
part 00000000 reset_info 00000000
PMIC reset-event 00000000 rtc 65bacc21 alarm 00000000 enabled 0
uSD voltage 3.3V
Initialising SDRAM 'Samsung' 16Gb x2 total-size: 32 Gbit 4267
DDR 4267 1 0 32 152
RP1_BOOT chip ID: 0x20001927

RP1_BOOT chip ID: 0x20001928
RP1_BOOT: fw size 25968
PCI2 init
PCI2 reset
PCIe scan 00001de4:00000001
RP1_CHIP_INFO 20001928

RPi: BOOTLOADER release VERSION:30cc5f37 DATE: 2024/01/05 TIME: 15:57:40
BOOTMODE: 0x06 partition 0 build-ts BUILD_TIMESTAMP=1704470260 serial b8c7b500 boardrev c04170 stc 4460789
AON_RESET: 00000003 PM_RSTS 00000020
usb_pd_init status 3
USB_PD CONFIG 0 43
Boot mode: NVME (06) order f41
PCI1 init
PCI1 reset
PCIe scan 00001c5c:00001327
VID 0x1c5c MN HFM512GDHTNG-8710B
NVME on
MBR: 0x00002000,  131072 type: 0x0c
MBR: 0x00024000, 2129920 type: 0x83
MBR: 0x00000000,       0 type: 0x00
MBR: 0x00000000,       0 type: 0x00
USB-PD: src-cap PDO object1 0x0a0191f4
Current 5000 mA
Voltage 5000 mV
USB-PD: src-cap PDO object2 0x0002d12c
Current 3000 mA
Voltage 9000 mV
USB-PD: src-cap PDO object3 0x0003c0e1
Current 2250 mA
Voltage 12000 mV
USB-PD: src-cap PDO object4 0x0004b0b4
Current 1800 mA
Voltage 15000 mV
Trying partition: 0
type: 16 lba: 8192 'mkfs.fat' '  V       ^ ' clusters 32695 (4)
rsc 4 fat-sectors 128 root dir cluster 1 sectors 32 entries 512
FAT16 clusters 32695
[nvme] autoboot.txt not found
Select partition rsts 0 C(boot_partition) 0 EEPROM config 0 result 0
Trying partition: 0
type: 16 lba: 8192 'mkfs.fat' '  V       ^ ' clusters 32695 (4)
rsc 4 fat-sectors 128 root dir cluster 1 sectors 32 entries 512
FAT16 clusters 32695
Read config.txt bytes      693 hnd 0x5
Read distroconfig.txt bytes      678 hnd 0x6
[nvme] pieeprom.upd not found
usb_max_current_enable forced to 1
Read bcm2712-rpi-5-b.dtb bytes    76621 hnd 0x18ea
dt-match: compatible: raspberrypi,5-model-b match: brcm,bcm2712
dt-match: compatible: brcm,bcm2712 match: brcm,bcm2712

NOTICE:  BL31: v2.6(release):v2.6-239-g2a9ede0bd
NOTICE:  BL31: Built : 14:26:57, Jun 22 2023
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x414fd0b1]

root@OpenWrt:~# dmesg | grep -i nvme
[    1.601831] nvme nvme0: pci function 0000:01:00.0
[    1.606587] nvme 0000:01:00.0: enabling device (0000 -> 0002)
[    1.687747] nvme nvme0: 4/0/0 default/read/poll queues
[    1.694024]  nvme0n1: p1 p2
[    2.813420] EXT4-fs (nvme0n1p2): mounted filesystem without journal. Quota mode: disabled.
[    5.098320] EXT4-fs (nvme0n1p2): re-mounted. Quota mode: disabled.
root@OpenWrt:~# rpi-eeprom-config
[all]
BOOT_UART=1
BOOT_ORDER=0xf416
POWER_OFF_ON_HALT=0
PCIE_PROBE=1
```

**Comment by Noltari** [comment]
> @Noltari Good job, tested on rpi 4/5, also on the RPi5 boot from NVMe SSD is working.

Thanks for testing!
Did you try upgrading/downgrading to new images with different PARTUUID?
Since PARTUUID is now autogenerated, upgrading/downgrading to an image with a different PARTUUID or restoring a config backup with a different PARTUUID is the real issue here and what makes this whole change breakable.
I think I covered all the cases but I want to be sure because I don't want to cause any issues to users...

**Comment by Noltari** [comment]
I merged the first 3 commits of this PR which should be harmless and cause no issues and rebased the other 3 commits on latest main.

**Comment by mj22226** [comment]
> Did you try upgrading/downgrading to new images with different PARTUUID?

@Noltari yes, I tried on the rpi5 upgrading and restoring backups works.
I found an issue not directly related to the PR , with NVMe the kernel configuration _PCIEASPM_POWER_SUPERSAVE_ need te be corrected to _PCIEASPM_POWERSAVE_ as is causing that the system occasionally freeze.

```
[   73.023557] nvme nvme0: controller is down; will reset: CSTS=0xffffffff, PCI_STATUS=0x10
[   73.031691] nvme nvme0: Does your device have a faulty power saving mode enabled?
[   73.039210] nvme nvme0: Try "nvme_core.default_ps_max_latency_us=0 pcie_aspm=off" and report a bug
[   73.123654] nvme0n1: I/O Cmd(0x2) @ LBA 239048, 8 blocks, I/O Error (sct 0x3 / sc 0x71)
[   73.131781] I/O error, dev nvme0n1, sector 239048 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
[   73.141054] nvme0n1: I/O Cmd(0x2) @ LBA 221344, 8 blocks, I/O Error (sct 0x3 / sc 0x71)
[   73.149182] I/O error, dev nvme0n1, sector 221344 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
[   73.223561] nvme 0000:01:00.0: enabling device (0000 -> 0002)
[   73.232845] nvme nvme0: 4/0/0 default/read/poll queues
```

**Comment by Noltari** [comment]
> @Noltari yes, I tried on the rpi5 upgrading and restoring backups works.

Thanks for testing!

> I found an issue not directly related to the PR , with NVMe the kernel configuration _PCIEASPM_POWER_SUPERSAVE_ need te be corrected to _PCIEASPM_POWERSAVE_ as is causing that the system occasionally freeze.

@mj22226 oh... can you create a new PR fixing that?

**Comment by mj22226** [comment]
> can you create a new PR fixing that?

@Noltari PR https://github.com/openwrt/openwrt/pull/14557

**Pull request merged**
