### PR TITLE
qoriq: use nvmem for MAC addresses

### PR DESCRIPTION
**Pull request by neheb**
Userspace handling is deprecated.

ping @stintel @namiltd

### CODE REVIEW

**Comment by namiltd** [comment]
I don't have a router from this target, so I can't check if the patch works.

**Comment by stintel** [comment]
@RussellSenior @f00b4r0 would any of you be able to test?

**Comment by neheb** [comment]
Rebased after kernel 6.1 removal.

**Comment by neheb** [comment]
ping @evs93

**Comment by evs93** [comment]
> ping @evs93

Yeah maybe sometime today or tomorrow. Currently trying to build all of 23.05.5 for qoriq which is going to take a while.

**Comment by evs93** [comment]
sweth3 through sweth7 end up with the same mac address as eth4 which isn't per previous behaviour:
i.e. sweth3-sweth7 would be 00:90:7f:d7:e3:0a per the example below.

The factory bootlog for example on the m300 wiki page:
`setting device eth0 to 00:90:7f:d7:e3:07
[   25.273364] setting device eth1 to 00:90:7f:d7:e3:08
[   25.273533] setting device eth2 to 00:90:7f:d7:e3:09
[   25.273693] setting device eth3 to 00:90:7f:d7:e3:0a
[   25.273875] setting device eth4 to 00:90:7f:d7:e3:0b
[   25.274042] setting device eth5 to 00:90:7f:d7:e3:0c
[   25.274196] setting device eth6 to 00:90:7f:d7:e3:0d
[   25.274379] setting device eth7 to 00:90:7f:d7:e3:0e`

**Comment by evs93** [comment]
OK figured it out. Looks like it's an off by one?

I dumped wg_cfg0. 0x186c is the offset in the flash. i.e. this is what I get with this change:
```
diff --git a/target/linux/qoriq/files/arch/powerpc/boot/dts/fsl/watchguard-firebox-m300.dts b/target/linux/qoriq/files/arch/powerpc/boot/dts/fsl/watchguard-firebox-m300.dts
index 7c0ad38113..6628e0eb23 100644
--- a/target/linux/qoriq/files/arch/powerpc/boot/dts/fsl/watchguard-firebox-m300.dts
+++ b/target/linux/qoriq/files/arch/powerpc/boot/dts/fsl/watchguard-firebox-m300.dts
@@ -121,33 +121,33 @@
                                #address-cells = <1>;
                                #size-cells = <1>;
 
-                               macaddr_cfg_186d: macaddr@186d {
+                               macaddr_cfg_186c: macaddr@186c {
                                        compatible = "mac-base";
-                                       reg = <0x186d 0x11>;
+                                       reg = <0x186c 0x11>;
                                        #nvmem-cell-cells = <1>;
                                };
 
-                               macaddr_cfg_1881: macaddr@1881 {
+                               macaddr_cfg_1880: macaddr@1880 {
                                        compatible = "mac-base";
-                                       reg = <0x1881 0x11>;
+                                       reg = <0x1880 0x11>;
                                        #nvmem-cell-cells = <1>;
                                };
 
-                               macaddr_cfg_1895: macaddr@1895 {
+                               macaddr_cfg_1894: macaddr@1894 {
                                        compatible = "mac-base";
-                                       reg = <0x1895 0x11>;
+                                       reg = <0x1894 0x11>;
                                        #nvmem-cell-cells = <1>;
                                };
 
-                               macaddr_cfg_18a9: macaddr@18a9 {
+                               macaddr_cfg_18a8: macaddr@18a8 {
                                        compatible = "mac-base";
-                                       reg = <0x18a9 0x11>;
+                                       reg = <0x18a8 0x11>;
                                        #nvmem-cell-cells = <1>;
                                };
 
-                               macaddr_cfg_18bd: macaddr@18bd {
+                               macaddr_cfg_18bc: macaddr@18bc {
                                        compatible = "mac-base";
-                                       reg = <0x18bd 0x11>;
+                                       reg = <0x18bc 0x11>;
                                        #nvmem-cell-cells = <1>;
                                };
                        };
@@ -274,7 +274,7 @@
                                label = "sweth3";
                                phy-handle = <&switch0phy0>;
 
-                               nvmem-cells = <&macaddr_cfg_186d 0>;
+                               nvmem-cells = <&macaddr_cfg_186c 0>;
                                nvmem-cell-names = "mac-address";
                        };
 
@@ -283,7 +283,7 @@
                                label = "sweth4";
                                phy-handle = <&switch0phy1>;
 
-                               nvmem-cells = <&macaddr_cfg_1881 0>;
+                               nvmem-cells = <&macaddr_cfg_1880 0>;
                                nvmem-cell-names = "mac-address";
                        };
 
@@ -292,7 +292,7 @@
                                label = "sweth5";
                                phy-handle = <&switch0phy2>;
 
-                               nvmem-cells = <&macaddr_cfg_1895 0>;
+                               nvmem-cells = <&macaddr_cfg_1894 0>;
                                nvmem-cell-names = "mac-address";
                        };
 
@@ -301,7 +301,7 @@
                                label = "sweth6";
                                phy-handle = <&switch0phy3>;
 
-                               nvmem-cells = <&macaddr_cfg_18a9 0>;
+                               nvmem-cells = <&macaddr_cfg_18a8 0>;
                                nvmem-cell-names = "mac-address";
                        };
 
@@ -310,7 +310,7 @@
                                label = "sweth7";
                                phy-handle = <&switch0phy4>;
 
-                               nvmem-cells = <&macaddr_cfg_18bd 0>;
+                               nvmem-cells = <&macaddr_cfg_18bc 0>;
                                nvmem-cell-names = "mac-address";
                        };

``` 


```shell
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 96 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br-lan state UP mode DEFAULT group default qlen 1000
    link/ether 97 brd ff:ff:ff:ff:ff:ff
4: eth2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 98 brd ff:ff:ff:ff:ff:ff
5: eth3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 99 brd ff:ff:ff:ff:ff:ff
6: eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1508 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 9a brd ff:ff:ff:ff:ff:ff
7: sweth3@eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default qlen 1000
    link/ether 99 brd ff:ff:ff:ff:ff:ff
8: sweth4@eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default qlen 1000
    link/ether 9a brd ff:ff:ff:ff:ff:ff
9: sweth5@eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default qlen 1000
    link/ether 9b brd ff:ff:ff:ff:ff:ff
10: sweth6@eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default qlen 1000
    link/ether 9c brd ff:ff:ff:ff:ff:ff
11: sweth7@eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default qlen 1000
    link/ether 9d brd ff:ff:ff:ff:ff:ff

```

**Comment by evs93** [comment]
Also @neheb per your suggestion on the mailing list deleting enet2 and enet3 per this:
```
--- a/target/linux/qoriq/files/arch/powerpc/boot/dts/fsl/watchguard-firebox-m300.dts
+++ b/target/linux/qoriq/files/arch/powerpc/boot/dts/fsl/watchguard-firebox-m300.dts
@@ -32,8 +32,6 @@
                ethernet0 = &enet7;
                ethernet1 = &enet0;
                ethernet2 = &enet1;
-               ethernet3 = &enet2;
-               ethernet4 = &enet3;
 
                led-boot = &led_shield;

``` 

Does remove the addresses from conduit0 and conduit1 per below.
We know that we want the front panel ports to be the correct mac adresses.
To me i don't think we want the conduits to be also set to the same mac address?
I'm unsure of what the implications are for that, given the front panel ports seem to work fine with them being the same mac address as the dsa conduits.
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 96 brd ff:ff:ff:ff:ff:ff
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq master br-lan state DOWN mode DEFAULT group default qlen 1000
    link/ether 97 brd ff:ff:ff:ff:ff:ff
4: eth2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq master br-lan state DOWN mode DEFAULT group default qlen 1000
    link/ether 98 brd ff:ff:ff:ff:ff:ff
5: conduit1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 12:ef:63:14:7f:43 brd ff:ff:ff:ff:ff:ff
6: conduit0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1508 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether a6:c4:a9:d7:6a:76 brd ff:ff:ff:ff:ff:ff
7: eth3@conduit0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue master br-lan state LOWERLAYERDOWN mode DEFAULT group default q0
    link/ether 99 brd ff:ff:ff:ff:ff:ff
8: eth4@conduit0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue master br-lan state LOWERLAYERDOWN mode DEFAULT group default q0
    link/ether 9a brd ff:ff:ff:ff:ff:ff
9: eth5@conduit0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP mode DEFAULT group default qlen 1000
    link/ether 9b brd ff:ff:ff:ff:ff:ff
10: eth6@conduit0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue master br-lan state LOWERLAYERDOWN mode DEFAULT group default 0
    link/ether 9c brd ff:ff:ff:ff:ff:ff
11: eth7@conduit0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue master br-lan state LOWERLAYERDOWN mode DEFAULT group default 0
    link/ether 9d brd ff:ff:ff:ff:ff:ff
```

**Comment by neheb** [comment]
Added off by one fixes.

Ignore the aliases comment.

**Comment by neheb** [comment]
Funny. CI seems broken for this target. ping @hauke

**Comment by RussellSenior** [comment]
I have aesthetic problems with "conduit". I wasn't confused by the old naming.

**Comment by neheb** [comment]
So does this PR work?

**Comment by RussellSenior** [comment]
> So does this PR work?

I'll give it a whirl. ETA 30 minutes.

**Comment by f00b4r0** [comment]
> Funny. CI seems broken for this target. ping @hauke 

It's source only, that's probably why.

**Comment by RussellSenior** [comment]
> > So does this PR work?
> 
> I'll give it a whirl. ETA 30 minutes.

DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r27720+1-9b66c7dfa5'

@neheb It builds and boots. Is there anything in particular you want checked?

**Comment by neheb** [comment]
Well, the goal is that the MAC addresses are the same before and after.

**Comment by RussellSenior** [comment]
> Well, the goal is that the MAC addresses are the same before and after.

@neheb They do seem to be the same range as before. My build from early August (26997-ga67b20e3d5) had them a bit more jumbled a bit haphazardly according to my console logs, sweth's not in order, your commit seems more orderly.

**Comment by evs93** [comment]
Let me check and build again. For me the mac addresses ended up in the correct order per factory.

**Comment by evs93** [comment]
@RussellSenior 
> I have aesthetic problems with "conduit". I wasn't confused by the old naming. But, investigating I find my complaints are a year late. Oh well.

To me conduit is a synonym for trunking like in the physical wiring of building sense so it works OK as an analogy I guess.  I'm trying to adapt to new naming too.

>I don't particularly like the way each interface is assigned its own network by default.

Yeah I'd much rather we move to eth1 through eth7 all being on lan as that means I don't have to do LuCI development =P. I have it that way in my private branch. Also of note check the mailing list I sent through changes to preinit to get the interfaces named per factory.

Regarding the mac address ordering:
Only thing I can think of is dump wg_cfg0 and make sure the order is correct there?

**Comment by RussellSenior** [comment]
> [...] like RusselSenior is describing.

Two l's please. ;-)

**Comment by evs93** [comment]
> > [...] like RusselSenior is describing.
> 
> Two l's please. ;-)

I see. Apologies. Fixed now.

**Comment by evs93** [comment]
Pulled and built again and "Works for me".

```
BusyBox v1.36.1 (2024-10-10 07:24:50 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r27730+1-3d7040b7d6
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@OpenWrt:~# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 96 brd ff:ff:ff:ff:ff:ff
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq master br-lan state DOWN qlen 1000
    link/ether 97 brd ff:ff:ff:ff:ff:ff
4: eth2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN qlen 1000
    link/ether 98 brd ff:ff:ff:ff:ff:ff
5: eth3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 99 brd ff:ff:ff:ff:ff:ff
6: eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1508 qdisc mq state UP qlen 1000
    link/ether 9a brd ff:ff:ff:ff:ff:ff
7: sweth3@eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN qlen 1000
    link/ether 99 brd ff:ff:ff:ff:ff:ff
8: sweth4@eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN qlen 1000
    link/ether 9a brd ff:ff:ff:ff:ff:ff
9: sweth5@eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 9b brd ff:ff:ff:ff:ff:ff
10: sweth6@eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN qlen 1000
    link/ether 9c brd ff:ff:ff:ff:ff:ff
11: sweth7@eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN qlen 1000
    link/ether 9d brd ff:ff:ff:ff:ff:ff
12: br-lan: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN qlen 1000
    link/ether 97 brd ff:ff:ff:ff:ff:ff
root@OpenWrt:~# cat /etc/board.json 
{
        "model": {
                "id": "watchguard,firebox-m300",
                "name": "WatchGuard Firebox M300"
        },
        "network": {
                "lan": {
                        "device": "eth1",
                        "protocol": "static"
                },
                "wan": {
                        "device": "eth0",
                        "protocol": "dhcp"
                },
                "eth2": {
                        "device": "eth2",
                        "protocol": "static",
                        "ipaddr": "10.0.2.1",
                        "netmask": "255.255.255.0"
                },
                "sweth4": {
                        "device": "sweth4",
                        "protocol": "static",
                        "ipaddr": "10.0.4.1",
                        "netmask": "255.255.255.0"
                },
                "sweth7": {
                        "device": "sweth7",
                        "protocol": "static",
                        "ipaddr": "10.0.7.1",
                        "netmask": "255.255.255.0"
                },
                "sweth5": {
                        "device": "sweth5",
                        "protocol": "static",
                        "ipaddr": "10.0.5.1",
                        "netmask": "255.255.255.0"
                },
                "sweth3": {
                        "device": "sweth3",
                        "protocol": "static",
                        "ipaddr": "10.0.3.1",
                        "netmask": "255.255.255.0"
                },
                "sweth6": {
                        "device": "sweth6",
                        "protocol": "static",
                        "ipaddr": "10.0.6.1",
                        "netmask": "255.255.255.0"
                }
        },
        "system": {
                "compat_version": "1.1"
        }
}
root@OpenWrt:~# 
```

**Comment by neheb** [comment]
Cool. Same before and after.

@stintel please merge.

**Comment by stintel** [comment]
> I don't particularly like the way each interface is assigned its own network by default.

AFAIR this is what the stock firmware does.

**Comment by stintel** [comment]
Ugh. The maintainer-tools/github-merge-pr.sh script is being stupid.

**Comment by neheb** [comment]
https://github.com/openwrt/openwrt/commit/c990f6e156699a4a60967603fb19b96a251a0bba got merged.

@evs93 you feeling like adding LED support?

**Comment by evs93** [comment]
> [c990f6e](https://github.com/openwrt/openwrt/commit/c990f6e156699a4a60967603fb19b96a251a0bba) got merged.
> 
> @evs93 you feeling like adding LED support?

Hmm. Happy to help test any changes you're willing to send me regarding LED support.
That is until I actually deploy this thing. I only have one of them.

We have Disk, Shield and Power LED right? IDK what they're hooked up to.
I haven't even looked to see what the reset button does either.

My attention now that this is merged  is on cleaning up my changes to preinit, board.d and the device tree to get the network devices named per factory. Then LuCI stuff.

**Comment by neheb** [comment]
@evs93 I have no idea what the LED situation is on this device.

On my MX60, the switch LEDs are the ones on the ports themselves. Link up and traffic.

**Pull request closed without merging**
