### PR TITLE
oxnas: do not use pcie-controller

### PR DESCRIPTION
**Pull request by neheb**
This was deprecated in kernel 4.14

ping @Ansuel @dangowrt

### CODE REVIEW

**Review by dangowrt — APPROVED** [review]

**Comment by neheb** [comment]
@dangowrt any chance in getting this merged?

**Comment by dangowrt** [comment]
Feel free to merge, I just don't have any way to test this right now.

**Comment by neheb** [comment]
I don't either. Nor do I have merge access.

**Comment by dangowrt** [comment]
To me this looks fine and should not hurt anyone. Lacking an oxnas
device for testing I reckon there is only one way to find out for
sure...

**Comment by neheb** [comment]
Thanks.

**Pull request closed without merging**
