### PR TITLE
tools/cmake: update to 3.30.5

### PR DESCRIPTION
**Pull request by zheshifandian**
Release notes: https://cmake.org/cmake/help/latest/release/3.30.html

### CODE REVIEW

**Comment by hnyman** [comment]
None of the patches require refresh ?

**Comment by zheshifandian** [comment]
> None of the patches require refresh ?

looks no need

**Comment by zheshifandian** [comment]
ping @robimarko

**Comment by hnyman** [comment]
looks ok to me, 
so far I have compiled mt7622/E8450, qualcommax/DL-WRX36 and filogic/MT6000 with this.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
