### PR TITLE
bcm63xx: sync driver with net-next Linux kernel

### PR DESCRIPTION
**Pull request by spliew89**
Sync ethernet driver code with net-next Linux kernel:
-Reduce xmit_more code changes.
-Combine rx cleanup code into a function.
-Convert to build_skb.
-Improve rx loop by optimizing loop tracking.

https://lore.kernel.org/netdev/20210106144208.1935-1-liew.s.piaw@gmail.com/
Signed-off-by: Sieng Piaw Liew <liew.s.piaw@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
ping @rmilecki

**Comment by Noltari** [comment]
> Sync ethernet driver code with upstream Linux kernel:
> -Reduce xmit_more code changes.
> -Combine rx cleanup code into a function.
> -Convert to build_skb.
> -Improve rx loop by optimizing loop tracking.
> 
> https://lore.kernel.org/netdev/20210106144208.1935-1-liew.s.piaw@gmail.com/
> Signed-off-by: Sieng Piaw Liew [liew.s.piaw@gmail.com](mailto:liew.s.piaw@gmail.com)

@spliew89 can you update your PR renaming the upstreamed patches with the upstream kernel version and move them to the beginning? (example: https://github.com/openwrt/openwrt/blob/master/target/linux/bcm63xx/patches-5.4/010-v5.8-MIPS-BCM63xx-fix-6328-boot-selection-bit.patch)
This simplifies the process of adding support for newer kernel versions.

BTW, thanks for taking the time to upstream those patches :)

**Comment by spliew89** [comment]
@Noltari the patches are accepted in net-next tree but not in the main one yet, so I don't know the kernel version yet. I should probably edit this PR title and message.

**Comment by Noltari** [comment]
Merged in https://github.com/openwrt/openwrt/commit/1d6f422e346ba1f39165577ffbe2ad15b944171c
Thanks!

**Comment by Noltari** [comment]
@spliew89 it looks like this PR is causing sporadic kernel panics on some SoCs (AFAIK it affects mainly BCM6318 and BCM6328):
```
CFE version 1.0.38-112.118-15 for BCM96318 (32bit,SP,BE)
Build Date: � 4月 11 21:08:50 CST 2013 (joba@SW1-BCM-02)
Copyright (C) 2000-2011 Broadcom Corporation.

HS Serial flash device: name ID_W25X128, id 0xef18 size 16384KB
Total Flash size: 16384K with 4096 sectors
Flash not used for Auxillary File System
Chip ID: BCM6318B0, MIPS: 333MHz, DDR: 333MHz, Bus: 166MHz
Main Thread: TP0
Total Memory: 67108864 bytes (64MB)
Boot Address: 0xb8000000

##checkForResetToDefaultHold:791##
Board IP address                  : 192.168.1.4:ffffff00  
Host IP address                   : 192.168.1.8  
Gateway IP address                : 192.168.1.1  
Run from flash/host (f/h)         : h  
Default host run file name        : ar5315u.elf  
Default host flash file name      : bcm963xx_fs_kernel  
Boot delay (0-9 seconds)          : 1  
Boot image (0=latest, 1=previous) : 0  
Board Id (0-5)                    : 96318A-1441N1  
Number of MAC Addresses (1-32)    : 32  
Base MAC Address                  : d8:b6:b7:16:b3:1a  
PSI Size (1-64) KBytes            : 24  
Enable Backup PSI [0|1]           : 1  
System Log Size (0-256) KBytes    : 0  
Auxillary File System Size Percent: 0  
Main Thread Number [0|1]          : 0  
WLAN Password                     : 5K6Usgc5FqwpWVvVMYVy  
Serial Number                     : 1665315UXXF-BH012226  

*** Press any key to stop auto run (1 seconds) ***
Auto run second count down: 1
 Port 2 link UP 
10
0x80a00000/5426645 Entry at 0x80a00000
Closing network.
Disabling Switch ports.
Flushing Receive Buffers...
0 buffers found.
Closing DMA Channels.
Starting program at 0x80a00000


OpenWrt kernel loader for BCM63XX
Copyright (C) 2011 Gabor Juhos <juhosg@openwrt.org>
Copyright (C) 2014 Jonas Gorski <jogo@openwrt.org>
Copyright (C) 2020 Alvaro Fernandez Rojas <noltari@gmail.com>
Decompressing kernel... done!
blasting from 0x80010000 to 0x011b2c24 (0x80010000 - 0x811c2c30)
Starting kernel at 80010000...

[    0.000000] Linux version 5.4.91 (noltari@skynet) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r15540-20a7c9d5c9)) #0 SMP Sat Jan 23 22:42:47 2021
[    0.000000] strap_override_bus = fffdffff
[    0.000000] Detected Broadcom 0x6318 CPU revision b0
[    0.000000] CPU frequency is 333 MHz
[    0.000000] 64MB of RAM installed
[    0.000000] board_bcm963xx: Boot address 0xb8000000
[    0.000000] board_bcm963xx: CFE version: 1.0.38-112.118-15
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00029033 (Broadcom BMIPS3300)
[    0.000000] board: board name: 96318A-1441N1
[    0.000000] MIPS: machine is Comtrend AR-5315u
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 16 bytes.
[    0.000000] Primary data cache 32kB, 2-way, VIPT, cache aliases, linesize 16 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] percpu: Embedded 14 pages/cpu s26160 r8192 d22992 u57344
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 16240
[    0.000000] Kernel command line: rootfstype=squashfs,jffs2 noinitrd console=ttyS0,115200
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 45416K/65536K available (5916K kernel code, 217K rwdata, 1244K rodata, 11816K init, 206K bss, 20120K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=16, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=2 to nr_cpu_ids=1.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 256
[    0.000000] random: get_random_bytes called from start_kernel+0x338/0x56c with crng_init=0
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 11479041721 ns
[    0.000023] sched_clock: 32 bits at 166MHz, resolution 6ns, wraps every 12897800188ns
[    0.008226] Calibrating delay loop... 332.54 BogoMIPS (lpj=665088)
[    0.046564] pid_max: default: 32768 minimum: 301
[    0.051811] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.059366] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.075372] rcu: Hierarchical SRCU implementation.
[    0.081827] smp: Bringing up secondary CPUs ...
[    0.086616] smp: Brought up 1 node, 1 CPU
[    0.107487] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.117603] futex hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.124863] pinctrl core: initialized pinctrl subsystem
[    0.132106] NET: Registered protocol family 16
[    0.398124] registering PCI controller with io_map_base unset
[    0.508890] PCI host bridge to bus 0000:00
[    0.513301] pci_bus 0000:00: root bus resource [mem 0x10200000-0x102fffff]
[    0.520393] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    0.527371] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    0.534367] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    0.542610] pci 0000:00:00.0: [14e4:6318] type 01 class 0x060400
[    0.549008] pci 0000:00:00.0: PME# supported from D0 D3hot
[    0.556371] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    0.565159] pci 0000:01:00.0: [14e4:a8db] type 00 class 0x028000
[    0.571499] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x00007fff 64bit]
[    0.578564] pci 0000:01:00.0: enabling Extended Tags
[    0.583878] pci 0000:01:00.0: supports D1 D2
[    0.589916] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    0.596815] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 01
[    0.603670] pci 0000:00:00.0: BAR 8: assigned [mem 0x10200000-0x102fffff]
[    0.610684] pci 0000:01:00.0: BAR 0: assigned [mem 0x10200000-0x10207fff 64bit]
[    0.618234] pci 0000:00:00.0: PCI bridge to [bus 01]
[    0.623333] pci 0000:00:00.0:   bridge window [mem 0x10200000-0x102fffff]
[    0.630726] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    0.654569] clocksource: Switched to clocksource MIPS
[    0.664474] NET: Registered protocol family 2
[    0.671553] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.680528] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.688542] TCP bind hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.696004] TCP: Hash tables configured (established 1024 bind 1024)
[    0.702943] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.709996] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.718303] NET: Registered protocol family 1
[    0.723124] PCI: CLS 0 bytes, default 16
[    1.147968] random: fast init done
[    1.660880] workingset: timestamp_bits=14 max_order=14 bucket_order=0
[    1.690416] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    1.696557] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    1.765872] bcm6318-pinctrl 10000080.pin-controller: registered at mmio (ptrval)
[    1.775647] pcieport 0000:00:00.0: enabling device (0000 -> 0002)
[    1.783655] 10000100.serial: ttyS0 at MMIO 0x10000100 (irq = 36, base_baud = 1562500) is a bcm63xx_uart
[    1.793565] printk: console [ttyS0] enabled
[    1.793565] printk: console [ttyS0] enabled
[    1.802180] printk: bootconsole [early0] disabled
[    1.802180] printk: bootconsole [early0] disabled
[    1.852193] spi-nor spi1.0: w25q128 (16384 Kbytes)
[    1.914787] 3 fixed-partitions partitions found on MTD device spi1.0
[    1.921545] Creating 3 MTD partitions on "spi1.0":
[    1.926530] 0x000000000000-0x000000010000 : "cfe"
[    1.934642] 0x000000010000-0x000000ff0000 : "linux"
[    1.949924] parser_imagetag: rootfs: CFE image tag found at 0x0 with version 6, board type 96318A-1441N1
[    1.959966] parser_imagetag: Partition 0 is rootfs offset 100 and length 68e000
[    1.967505] parser_imagetag: Partition 1 is kernel offset 68e100 and length 13e67e
[    1.975276] parser_imagetag: Spare partition is offset 7e0000 and length 800000
[    1.983338] 2 bcm963xx-imagetag partitions found on MTD device linux
[    1.990072] Creating 2 MTD partitions on "linux":
[    1.994957] 0x000000000100-0x00000068e100 : "rootfs"
[    2.002968] mtd: device 2 (rootfs) set to be root filesystem
[    2.012771] mtdsplit: no squashfs found in "rootfs"
[    2.018095] 0x00000068e100-0x0000007cc77e : "kernel"
[    2.026327] 0x000000ff0000-0x000001000000 : "nvram"
[    2.037445] libphy: Fixed MDIO Bus: probed
[    2.085574] b53_common: found switch: BCM63xx, rev 0
[    2.092013] bcm63xx-wdt bcm63xx-wdt:  started, timer margin: 30 sec
[    2.102528] leds-gpio leds-gpio.0: Skipping unavailable LED gpio 0 ((null))
[    2.109855] leds-gpio leds-gpio.0: Skipping unavailable LED gpio 0 ((null))
[    2.117021] leds-gpio leds-gpio.0: Skipping unavailable LED gpio 0 ((null))
[    2.124189] leds-gpio leds-gpio.0: Skipping unavailable LED gpio 0 ((null))
[    2.131363] leds-gpio leds-gpio.0: Skipping unavailable LED gpio 0 ((null))
[    2.139079] bcma-pci-bridge 0000:01:00.0: enabling device (0000 -> 0002)
[    2.146138] bcma-pci-bridge 0000:01:00.0: bus0: Found chip with id 43217, rev 0x01 and package 0x09
[    2.155546] bcma-pci-bridge 0000:01:00.0: bus0: Core 0 found: ChipCommon (manuf 0x4BF, id 0x800, rev 0x27, class 0x0)
[    2.166546] bcma-pci-bridge 0000:01:00.0: bus0: Core 1 found: IEEE 802.11 (manuf 0x4BF, id 0x812, rev 0x1E, class 0x0)
[    2.177642] bcma-pci-bridge 0000:01:00.0: bus0: Core 2 found: PCIe (manuf 0x4BF, id 0x820, rev 0x14, class 0x0)
[    2.209816] bcma-pci-bridge 0000:01:00.0: bus0: Bus registered
[    2.219566] NET: Registered protocol family 10
[    2.235354] Segment Routing with IPv6
[    2.239644] NET: Registered protocol family 17
[    2.244452] 8021q: 802.1Q VLAN Support v1.8
[    2.527299] Freeing unused kernel memory: 11816K
[    2.532126] This architecture does not have kernel memory protection.
[    2.538721] Run /init as init process
[    4.355301] init: Console is alive
[    4.359986] init: - watchdog -
[    4.423641] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    4.482004] usbcore: registered new interface driver usbfs
[    4.488067] usbcore: registered new interface driver hub
[    4.493907] usbcore: registered new device driver usb
[    4.525175] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.537175] ehci-fsl: Freescale EHCI Host controller driver
[    4.549253] ehci-platform: EHCI generic platform driver
[    4.659968] ehci-platform ehci-platform: EHCI Host Controller
[    4.666023] ehci-platform ehci-platform: new USB bus registered, assigned bus number 1
[    4.674787] ehci-platform ehci-platform: irq 50, io mem 0xb0005000
[    4.695880] ehci-platform ehci-platform: USB 2.0 started, EHCI 1.00, overcurrent ignored
[    4.707039] hub 1-0:1.0: USB hub found
[    4.712596] hub 1-0:1.0: 1 port detected
[    4.738472] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    4.749674] ohci-platform: OHCI generic platform driver
[    4.755698] ohci-platform ohci-platform: Generic Platform OHCI controller
[    4.762906] ohci-platform ohci-platform: new USB bus registered, assigned bus number 2
[    4.771421] ohci-platform ohci-platform: irq 49, io mem 0xb0005100
[    4.842652] hub 2-0:1.0: USB hub found
[    4.848245] hub 2-0:1.0: 1 port detected
[    4.856896] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    4.875665] init: - preinit -
[    5.494163] random: jshn: uninitialized urandom read (4 bytes read)
[    5.596981] random: jshn: uninitialized urandom read (4 bytes read)
[    5.861447] random: jshn: uninitialized urandom read (4 bytes read)
[    6.404463] bcm63xx_enetsw bcm63xx_enetsw.0: link UP on LAN2, 100Mbps, full-duplex
[    6.413473] IPv6: ADDRCONF(NETDEV_CHANGE): eth0.1: link becomes ready
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[    7.399939] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   10.886282] Kernel bug detected[#1]:
[   10.889958] CPU: 0 PID: 496 Comm: ip Not tainted 5.4.91 #0
[   10.895579] $ 0   : 00000000 10008400 00000000 00000001
[   10.900956] $ 4   : 82fd6250 0000005e 00000000 83d700b0
[   10.906337] $ 8   : 00000000 805cf8bc 00000000 00000000
[   10.911719] $12   : 104233f4 8073c630 00000000 7f7d33fc
[   10.917101] $16   : 83d14000 82fd6200 83d702c0 0000005e
[   10.922483] $20   : 00000001 00000001 83d145e8 82fd6500
[   10.927863] $24   : 00000000 00000000                  
[   10.933245] $28   : 834b2000 834b3c78 00000000 8040c038
[   10.938628] Hi    : 00000000
[   10.941588] Lo    : 00000000
[   10.944600] epc   : 803304e4 dql_completed+0x10/0x1d0
[   10.949801] ra    : 8040c038 bcm_enet_tx_reclaim+0x144/0x230
[   10.955579] Status: 10008403	KERNEL EXL IE 
[   10.959886] Cause : 00800034 (ExcCode 0d)
[   10.964013] PrId  : 00029033 (Broadcom BMIPS3300)
[   10.968851] Modules linked in: ohci_platform ohci_hcd fsl_mph_dr_of ehci_platform ehci_fsl ehci_hcd gpio_button_hotplug usbcore nls_base usb_common
[   10.982500] Process ip (pid: 496, threadinfo=(ptrval), task=(ptrval), tls=77e2aec8)
[   10.990376] Stack : 0000000a 80452c2c 00000001 10008401 83d144a8 83d145b0 83d14000 80723af0
[   10.998986]         83d14480 00000001 00000000 80720000 83d14000 8040c2d4 834b3cd8 834b3d20
[   11.007596]         00000000 00000001 00000000 80720000 83d14000 834b3d20 fffffffe 804513c4
[   11.016207]         00400000 83d14188 83d14000 8045d55c 00000000 8045d9c4 83d14000 00000000
[   11.024816]         83d14000 00001042 00000000 8045daac 82a489a4 00000072 00003200 838cd130
[   11.033427]         ...
[   11.035942] Call Trace:
[   11.038464] [<803304e4>] dql_completed+0x10/0x1d0
[   11.043322] Code: 8c860014  01461023  0045182b <00030336> 8c890010  8c8c001c  00c54021  00493823  010c5823 
[   11.053357] 
[   11.055111] ---[ end trace eae5216945bbc239 ]---
[   11.059852] Kernel panic - not syncing: Fatal exception
[   11.065203] Rebooting in 1 seconds..
[   12.067632] triggering watchdog soft-reset...
```

**Comment by Noltari** [comment]
@spliew89 I've pushed 7d12f29ae1d7337e4289baf9e6b4bf79445b0d59, which reverts netdev_reset_queue() to _open (like it was done before 1d6f422e346ba1f39165577ffbe2ad15b944171c).
Can you check that?
It looks like there's a race condition or something, because kernel panics are sporadic if netdev_reset_queue() is called from _stop().

**Pull request closed without merging**
