### PR TITLE
treewide: Set 32-bit or 64-bit by target on 4.19

### PR DESCRIPTION
**Pull request by diizzyy**
Both CONFIG_32BIT=y and CONFIG_64BIT=y shouldn't co-exist in kernel
config. Remove from global kernel config and set by target instead

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@xback @hauke @linusw 
Can you have a look at this?

**Comment by neheb** [comment]
Tested-by: Rosen Penev <rosenp@gmail.com>

**Comment by diizzyy** [comment]
@ynezz 
Can you have a look at this?

**Comment by diizzyy** [comment]
@ldir-EDB0 
Can you have a look at this? This also applies to 5.4

**Comment by jow-** [comment]
Is this a cosmetic or a functional change? When grepping an older (4.14) kernel tree I only see four architectures declaring `config 32BIT`, on all others the symbol should be automatically eliminated when kconfig processes the kernel `.config`.

**Comment by diizzyy** [comment]
I don't see why we should derive from upstream which may lead to potential issues further down the road. This is what Kconfig emits
```.config:3:warning: override: 64BIT changes choice state```

**Comment by diizzyy** [comment]
As 4.19 is slowly getting deprecated in favour of 5.4 I don't see the point in continuing working on this.

**Pull request closed without merging**
