### PR TITLE
ramips: fix calculation of cpu frequency for mt7621

### PR DESCRIPTION
**Pull request by hackpascal**
For a long time the mt7621 uses a fixed cpu clock which causes a problem if the cpu frequency is not 880MHz. The problem is the system time will be inaccurate.

This patch fixes the cpu clock calculation, adds the cpu/bus clkdev and fixes clocks in mt7621.dtsi.

Signed-off-by: Weijie Gao <hackpascal@gmail.com>

### CODE REVIEW

**Comment by lintel** [comment]
Godd Job 👍

**Comment by paldier** [comment]
👍

**Comment by neheb** [comment]
@hackpascal this is excellent. This can also be submitted upstream I think.

**Comment by hauke** [comment]
@blogic could you please have a look at these patches, they look good to me, but I do not know ramips.
@hackpascal  please Also send them upstream to get them into the Linux mainline kernel.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
