### PR TITLE
.gitignore: cleanup and handle nohup output

### PR DESCRIPTION
**Pull request by mcprat**
### toplevel.mk: remove legacy packages feed from 'make distclean'

package/openwrt-packages is left over
from what is now a legacy repository
and has no other reference in the build tree.

### .gitignore: cleanup and organization

combine similar globs
remove deprecated /package/openwrt-packages glob
make build-key glob root only
ordered with GNU `sort -V`

### .gitignore: ignore '.out' logs

nohup is a common GNU tool used when running a process remotely
to prevent a remote task from hanging up if connection is lost,
for example, when building an image over SSH.

By default, all terminal output is saved in the file 'nohup.out'
so ignore it

### CODE REVIEW

**Comment by aparcar** [comment]
I wonder if vim's sort doesn't do the trick slightly better:
```
*#
*.o
*.orig
*.rej
*~
.#*
.*.swp
.*project
.DS_Store
.ccache
.emacs.desktop*
/*.out
/*.patch
/.config*
/bin
/build_dir
/dl
/env
/feeds*
/files
/key-build*
/logs
/overlay
/package/feeds
/staging_dir
/tmp
TAGS*~
git-src
```

**Comment by mpratt14** [comment]
I just did `sort -V` which looks good but diff is larger now

**Comment by adschm** [comment]
I wonder whether we really need this (i.e. whether it's an improvement), or whether is just a different way to have it displayed.

**Comment by aparcar** [comment]
I'd say at least ignoring ".out" and removing the legacy cleanup makes sense. I find it visually more appealing/understandable but that's maybe subjective.

**Comment by mpratt14** [comment]
for sure sorting is not a performance improvement

depending on how git functions, fewer lines in .gitignore might save time when the index is rebuilt
(but an extremely small amount of time that's negligible to the user)

Also, I wonder if there is a time difference between root only vs. recursive glob...

**Comment by mpratt14** [comment]
probably several more can be made root only globs, for example `git-src` which is probably not in subdirectories...

I am not familiar with the rest, would there be any more?

**Comment by mpratt14** [comment]
I can't find any information on `git-src`, is it also deprecated?

if we want to fully handle emacs would we follow this?
https://github.com/github/gitignore/blob/master/Global/Tags.gitignore

**Comment by aparcar** [comment]
git-src is in use via the config option `SRC_TREE_OVERRIDE`:
```
If enabled, you can force a package to use a git tree as source
code instead of the normal tarball. Create a symlink 'git-src'
in the package directory, pointing to the .git tree that you want
to pull the source code from.
```

**Comment by mpratt14** [comment]
a little bit more combining

feeds line ignores the directories but not the script `scripts/feeds`
config line ignores .diffconfig and renamed .config

**Comment by 1715173329** [comment]
> I see .ccache in `make distclean`...does this mean it is in the root directory only?

By default it is.

**Comment by adschm** [comment]
> package/openwrt-packages is left over
> from what is now a legacy repository
> and has no other reference in the build tree

But isn't the point of distclean to remove "old" stuff?

**Comment by adschm** [comment]
> nohup is a common GNU tool used when running a process remotely
> to prevent a remote task from hanging up if connection is lost,
> for example, when building an image over SSH.

I'm not sure whether we should start this. My fear is that at some point everybody will come and want a .gitignore exception for the particular tools he uses. I'd rather say this is easy to take care of locally (either by not caring about the untracked files in git or by maintaining a local .gitignore). I'm working with files in my OpenWrt root dir for years now (listed as untracked files) and it never happened to be a problem at all for me.

**Comment by mpratt14** [comment]
@adschm sounds like you would prefer a more aggressive cleanup of .gitignore to remove more things? so that the only things left are openwrt-specific or OS-specific (.DS_Store)?

**Comment by adschm** [comment]
Sorry, but actually I would not touch it at all at the moment, because I don't see a strong reason to change anything ...
Except for /package/openwrt-packages maybe, which for .gitignore really seems unnecessary.

One could start a discussion about OS-specific stuff, but I don't really remember what the best-practices I read once said about this.

**Comment by aparcar** [comment]
I merge the legacy packages cleanup commit. I have no strong opinion on the rest. @mpratt14 feel free to start a mail conversation regarding gitignore if you care enough.

**Comment by mpratt14** [comment]
I have since learned how to use a local .gitignore alongside the one in the build tree, so you can close this if you want

**Pull request closed without merging**
