### PR TITLE
layerscape: armv8_64b: update and enable QorIQ TMU

### PR DESCRIPTION
**Pull request by sch-m**
@yangbolu1991
@Anson-Huang
Update the QorIQ thermal patches to the latest upstream version from the
linux kernel sources and enable it for the layerscape/armv8_64b target.

Also remove the "thermal: Add generic device cooling support" patch,
because it interferce with the devfreq driver and I can't see any reason
why we should need this.

In addition, we turn on the appropriate options to expose thermal
sensors as hwmon device.

### CODE REVIEW

**Comment by GoliathLabs** [comment]
You may want to squash the commits into one (https://www.git-tower.com/learn/git/faq/git-squash/)

**Comment by adschm** [comment]
> You may want to squash the commits into one (https://www.git-tower.com/learn/git/faq/git-squash/)

Why would he want that?

**Comment by GoliathLabs** [comment]
You sometimes suggest that in your comments below the PRs. Thought that might apply here as well

**Comment by adschm** [comment]
> You sometimes suggest that in your comments below the PRs. Thought that might apply here as well

Then please don't suggest something if you don't know the reasons behind it.

Changes should be organized in logical units. If the commit are addressing different things, the should be separate.
If they are just history of fixes to the same thing, i.e. they are actually addressing only one thing, and should be squashed.

https://openwrt.org/submitting-patches

**Comment by sch-m** [comment]
@adschm Thanks for clarifying that.

**Pull request closed without merging**
