### PR TITLE
kirkwood: add kernel 4.19 support

### PR DESCRIPTION
**Pull request by p-wassi**
Add patches for kernel 4.19

Things are compile- and run-tested for kirkwood/dockstar only.
The bootlog of this device is available at [1]

 @bobafetthotmail maybe you can test your devices on 4.19

Switchover to 4.19 in the Makefile is not done until successful tests
of other devices are reported.

[1]: https://pwassi.privatedns.org/openwrt/kirkwood_419/

### CODE REVIEW

**Comment by p-wassi** [comment]
As a user notified me via e-mail:
Drop patch `200-disable-tso` as the underlying issue was fixed upstream
in kernel commit 3b89624ab54b9dc2d92fc08ce2670e5f19ad8ec8
[1]

1: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/ethernet/marvell/mv643xx_eth.c?h=v4.19.13&id=3b89624ab54b9dc2d92fc08ce2670e5f19ad8ec8

**Comment by ynezz** [comment]
I've just successfuly build tested it with following config:

```
CONFIG_TARGET_kirkwood=y
CONFIG_TARGET_MULTI_PROFILE=y
CONFIG_TARGET_ALL_PROFILES=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_cisco_on100=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_cloudengines_pogoe02=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_cloudengines_pogoplugv4=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_iom_iconnect-1.1=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_iom_ix2_200=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_linksys_viper=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_linksys_audi=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_raidsonic_ib-nas62x0=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_seagate_dockstar=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_seagate_goflexhome=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_seagate_goflexnet=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_zyxel_nsa310b=y
CONFIG_TARGET_DEVICE_kirkwood_DEVICE_zyxel_nsa325=y
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
```

**Comment by ynezz** [comment]
@p-wassi There's quite a lot warnings in almost all DTS files, I don't know how severe those warnings are, but it might be good idea to check them as well while bumping the kernel.

**Comment by p-wassi** [comment]
Thanks @ynezz for testing and your notice on the DTS.

In fact, I only got two compile-time warnings for the DTSs. Did you see more?
`kirkwood-linksys-audi` and `kirkwood-linksys-viper`.
They were due to `reg` / `size-cells` mismatch. The `mvsw61xx` now
has a new parent node, which has `size-cells=0`. `reg` size is now correct and
DTC does not complain anymore. However, I have neither of these devices to actually test.

Additionally, on dockstar I get these run-time warnings:
```
[    0.009501] [Firmware Info]: /ocp@f1000000/ethernet-controller@72000/ethernet0-port@0: local-mac-address is not set
[    0.808796] [Firmware Warn]: /ocp@f1000000/mdio-bus@72004/ethernet-phy@0: Whitelisted compatible string. Please remove
```

For the first line: the `kirkwood.dtsi` sets this property to zero:
`local-mac-address = [00 00 00 00 00 00];`
If U-Boot parsed the DTB, it would overwrite the MAC address.

For the second line: the mentioned compatible string comes from upstream (line 100 in `kirkwood-dockstar.dts`). I actually do not want to introduce a new patch on OpenWrt side for this.
Should an upstream kirkwood maintainer be notified?

**Comment by ynezz** [comment]
> Did you see more?

@p-wassi It seems so:

```
image-kirkwood-on100.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-on100.dtb: Warning (unit_address_vs_reg): Node /gpio_keys/button@1 has a unit name, but no reg property
image-kirkwood-on100.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-on100.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-on100.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-pogo_e02.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-pogo_e02.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-pogo_e02.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-pogo_e02.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-pogoplug-series-4.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-pogoplug-series-4.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-pogoplug-series-4.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-pogoplug-series-4.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-iconnect.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-iconnect.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-iconnect.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-iconnect.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-iomega_ix2_200.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-iomega_ix2_200.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-iomega_ix2_200.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-iomega_ix2_200.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-linksys-audi.dtb: Warning (reg_format): "reg" property in /mvsw61xx has invalid length (4 bytes) (#address-cells == 1, #size-cells == 1)
image-kirkwood-linksys-audi.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-linksys-audi.dtb: Warning (unit_address_vs_reg): Node /mvsw61xx has a reg or ranges property, but no unit name
image-kirkwood-linksys-audi.dtb: Warning (pci_device_reg): Failed prerequisite 'reg_format'
image-kirkwood-linksys-audi.dtb: Warning (pci_device_bus_num): Failed prerequisite 'reg_format'
image-kirkwood-linksys-audi.dtb: Warning (simple_bus_reg): Failed prerequisite 'reg_format'
image-kirkwood-linksys-viper.dtb: Warning (reg_format): "reg" property in /mvsw61xx has invalid length (4 bytes) (#address-cells == 1, #size-cells == 1)
image-kirkwood-linksys-viper.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-linksys-viper.dtb: Warning (unit_address_vs_reg): Node /mvsw61xx has a reg or ranges property, but no unit name
image-kirkwood-linksys-viper.dtb: Warning (pci_device_reg): Failed prerequisite 'reg_format'
image-kirkwood-linksys-viper.dtb: Warning (pci_device_bus_num): Failed prerequisite 'reg_format'
image-kirkwood-linksys-viper.dtb: Warning (simple_bus_reg): Failed prerequisite 'reg_format'
image-kirkwood-ib62x0.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-ib62x0.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-ib62x0.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-ib62x0.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-dockstar.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-dockstar.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-dockstar.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-dockstar.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-goflexnet.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-goflexnet.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-goflexnet.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-goflexnet.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-goflexhome.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-goflexhome.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-goflexhome.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-goflexhome.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-nsa310b.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-nsa310b.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-nsa310b.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-nsa310b.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
image-kirkwood-nsa325.dtb: Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
image-kirkwood-nsa325.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/nand@012f simple-bus unit address format error, expected "12f000000000000"
image-kirkwood-nsa325.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/sa-sram@0301 simple-bus unit address format error, expected "301000000000000"
image-kirkwood-nsa325.dtb: Warning (simple_bus_reg): Node /mbus@f1000000/pcie@82000000 simple-bus unit address format error, expected "f001000000040000"
```

**Comment by p-wassi** [comment]
@ynezz 
> It seems so: (...)

What the heck...
I compile with `make -j 4 V=s`
and saw this (before having fixed the two warnings mentioned above):
```
  DTC     arch/arm/boot/dts/kirkwood-b3.dtb
  DTC     arch/arm/boot/dts/kirkwood-blackarmor-nas220.dtb
  DTC     arch/arm/boot/dts/kirkwood-cloudbox.dtb
  DTC     arch/arm/boot/dts/kirkwood-d2net.dtb
  DTC     arch/arm/boot/dts/kirkwood-db-88f6281.dtb
  DTC     arch/arm/boot/dts/kirkwood-db-88f6282.dtb
  DTC     arch/arm/boot/dts/kirkwood-dir665.dtb
  DTC     arch/arm/boot/dts/kirkwood-dns325.dtb
  DTC     arch/arm/boot/dts/kirkwood-dns320.dtb
  DTC     arch/arm/boot/dts/kirkwood-dockstar.dtb
  DTC     arch/arm/boot/dts/kirkwood-dreamplug.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds109.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds110jv10.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds111.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds112.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds209.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds210.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds212.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds409.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds212j.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds409slim.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds411.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds411j.dtb
  DTC     arch/arm/boot/dts/kirkwood-ds411slim.dtb
  DTC     arch/arm/boot/dts/kirkwood-goflexhome.dtb
  DTC     arch/arm/boot/dts/kirkwood-goflexnet.dtb
  DTC     arch/arm/boot/dts/kirkwood-guruplug-server-plus.dtb
  DTC     arch/arm/boot/dts/kirkwood-ib62x0.dtb
  DTC     arch/arm/boot/dts/kirkwood-iconnect.dtb
  DTC     arch/arm/boot/dts/kirkwood-iomega_ix2_200.dtb
  DTC     arch/arm/boot/dts/kirkwood-is2.dtb
  DTC     arch/arm/boot/dts/kirkwood-km_kirkwood.dtb
  DTC     arch/arm/boot/dts/kirkwood-laplug.dtb
  DTC     arch/arm/boot/dts/kirkwood-linkstation-lsqvl.dtb
  DTC     arch/arm/boot/dts/kirkwood-linkstation-lsvl.dtb
  DTC     arch/arm/boot/dts/kirkwood-linkstation-lswsxl.dtb
  DTC     arch/arm/boot/dts/kirkwood-linkstation-lswvl.dtb
  DTC     arch/arm/boot/dts/kirkwood-linkstation-lswxl.dtb
  DTC     arch/arm/boot/dts/kirkwood-linksys-audi.dtb
  DTC     arch/arm/boot/dts/kirkwood-linksys-viper.dtb
arch/arm/boot/dts/kirkwood-linksys-audi.dtb: Warning (reg_format): "reg" property in /mvsw61xx has invalid length (4 bytes) (#address-cells == 1, #size-cells == 1)
  DTC     arch/arm/boot/dts/kirkwood-lschlv2.dtb
arch/arm/boot/dts/kirkwood-linksys-viper.dtb: Warning (reg_format): "reg" property in /mvsw61xx has invalid length (4 bytes) (#address-cells == 1, #size-cells == 1)
  DTC     arch/arm/boot/dts/kirkwood-lsxhl.dtb
  DTC     arch/arm/boot/dts/kirkwood-mplcec4.dtb
  DTC     arch/arm/boot/dts/kirkwood-mv88f6281gtw-ge.dtb
  DTC     arch/arm/boot/dts/kirkwood-nas2big.dtb
  DTC     arch/arm/boot/dts/kirkwood-net2big.dtb
  DTC     arch/arm/boot/dts/kirkwood-net5big.dtb
  DTC     arch/arm/boot/dts/kirkwood-netgear_readynas_duo_v2.dtb
  DTC     arch/arm/boot/dts/kirkwood-netgear_readynas_nv+_v2.dtb
  DTC     arch/arm/boot/dts/kirkwood-ns2.dtb
  DTC     arch/arm/boot/dts/kirkwood-ns2lite.dtb
  DTC     arch/arm/boot/dts/kirkwood-ns2max.dtb
  DTC     arch/arm/boot/dts/kirkwood-ns2mini.dtb
  DTC     arch/arm/boot/dts/kirkwood-nsa310.dtb
  DTC     arch/arm/boot/dts/kirkwood-nsa310a.dtb
  DTC     arch/arm/boot/dts/kirkwood-nsa310b.dtb
  DTC     arch/arm/boot/dts/kirkwood-nsa320.dtb
  DTC     arch/arm/boot/dts/kirkwood-nsa325.dtb
  DTC     arch/arm/boot/dts/kirkwood-on100.dtb
  DTC     arch/arm/boot/dts/kirkwood-openblocks_a6.dtb
  DTC     arch/arm/boot/dts/kirkwood-openblocks_a7.dtb
  DTC     arch/arm/boot/dts/kirkwood-openrd-base.dtb
  DTC     arch/arm/boot/dts/kirkwood-openrd-client.dtb
  DTC     arch/arm/boot/dts/kirkwood-openrd-ultimate.dtb
  DTC     arch/arm/boot/dts/kirkwood-pogo_e02.dtb
  DTC     arch/arm/boot/dts/kirkwood-pogoplug-series-4.dtb
  DTC     arch/arm/boot/dts/kirkwood-rd88f6192.dtb
  DTC     arch/arm/boot/dts/kirkwood-rd88f6281-z0.dtb
  DTC     arch/arm/boot/dts/kirkwood-rd88f6281-a.dtb
  DTC     arch/arm/boot/dts/kirkwood-rs212.dtb
  DTC     arch/arm/boot/dts/kirkwood-rs409.dtb
  DTC     arch/arm/boot/dts/kirkwood-rs411.dtb
  DTC     arch/arm/boot/dts/kirkwood-sheevaplug.dtb
  DTC     arch/arm/boot/dts/kirkwood-sheevaplug-esata.dtb
  DTC     arch/arm/boot/dts/kirkwood-t5325.dtb
  DTC     arch/arm/boot/dts/kirkwood-topkick.dtb
  DTC     arch/arm/boot/dts/kirkwood-ts219-6281.dtb
  DTC     arch/arm/boot/dts/kirkwood-ts219-6282.dtb
  DTC     arch/arm/boot/dts/kirkwood-ts419-6281.dtb
  DTC     arch/arm/boot/dts/kirkwood-ts419-6282.dtb
```

**Comment by p-wassi** [comment]
> You're just looking at different build output, my output is from OpenWrt's image generation step, yours is from Linux (in tree build).

Current status is that the local patches do not generate more warnings than upstream
currently does.
The remaining warnings all need to be fixed upstream. I started working on a patch, but did not
finish that yet (and probably will not). (I'd touch almost *every* file in `arch/arm/boot/dts`.)

The issues basically boil down to the node's names (more precisely the unit address).
[1] states, that a unit address must be given **iff** the node has a `reg` property. (Section 2.2.1.1)
However, the dtc also complains, if there is `ranges` but no `reg`.
Things to change:
- `memory` -> `memory@0`
- sometimes the node-address does not match the first `reg` address (macro `MBUS_ID`)
- remove `size-cells` and `address-cells`for nodes that to not have a child with `reg` property. (e.g. `gpio-keys`)
- some nodes on the same level have the same base address (unit-address)

I'm stuck on the last one - currently no idea how to solve this without deeper insight into the platform.

[1]:
https://elinux.org/images/c/cf/Power_ePAPR_APPROVED_v1.1.pdf

**Comment by ynezz** [comment]
@p-wassi Thanks for looking into that!

> some nodes on the same level have the same base address (unit-address)

I don't know how to fix those properly either, probably they should be fixed somehow in `dtc` or just ignored...

**Comment by p-wassi** [comment]
>  probably they should be fixed somehow in `dtc`

The kirkwood `dtsi`s specify different nodes starting on the same physical address.
This can not be the case for devices on the same 'bus', e.g. memory mapped periphery.
Fixing this requires far more knowledge of the platform/architecture.

Since you mentioned fixing this in dtc: there's this:
https://patchwork.kernel.org/patch/8714701/
:smile:

**Comment by ynezz** [comment]
@p-wassi I've looked into it deeper, and decided, that we probably should [follow upstream](https://github.com/ynezz/openwrt/commit/0da1550b86c35871df5cd50ff5dcb7e1388412a3). Could you please test it?

**Comment by p-wassi** [comment]
@ynezz 
Your patch for the DTC warnings works fine as expected :-)

Refreshed the kirkwood 4.19 patch, the
``# CONFIG_USB_ROLE_SWITCH is not set``
should probably go into generic/config-4.19 ?

**Comment by ynezz** [comment]
> @ynezz
> Your patch for the DTC warnings works fine as expected :-)

Thanks for testing.
 
> Refreshed the kirkwood 4.19 patch, the

I've just build tested it and all seems fine.

> `# CONFIG_USB_ROLE_SWITCH is not set`
> should probably go into generic/config-4.19 ?

It's used in `drivers/usb/Makefile`, so I would say, that it belongs to generic config as well.

**Comment by ynezz** [comment]
> It's used in `drivers/usb/Makefile`, so I would say, that it belongs to generic config as well.

Here you go https://git.openwrt.org/?p=openwrt/staging/chunkeey.git;a=commit;h=2c6b86f4bd36697ee472d1649db8510796640f17

**Comment by bobafetthotmail** [comment]
ok, tested on nsa310 and pogoplugv4, no issues.

**Comment by diizzyy** [comment]
@p-wassi 
https://github.com/openwrt/openwrt/pull/1828
Can you give it a try and preferably define it in your kernel config?

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Comment by frymezim** [comment]
@p-wassi @bobafetthotmail 
does UUID detection has something to do kernel configuration?
it's been months now that I haven't able to do fstab automounting

```
@OpenWrt-NSA325:~# block info
/dev/mtdblock2: UUID="725550722" VERSION="1" TYPE="ubi"
/dev/ubiblock0_1: UUID="4057647d-ef38fe35-da50a366-f6a89ef7" VERSION="4.0" MOUNT="/rom" TYPE="squashfs"
/dev/ubi0_2: UUID="8aaab2bf-35ab-4e05-9132-090475a7ebac" VERSION="w4r0" MOUNT="/overlay" TYPE="ubifs"

@OpenWrt-NSA325:~# block detect
config 'global'
        option  anon_swap       '0'
        option  anon_mount      '0'
        option  auto_swap       '1'
        option  auto_mount      '1'
        option  delay_root      '5'
        option  check_fs        '0'

@OpenWrt-NSA325:~# xfs_admin -u /dev/sda
UUID = 6a5d7c5c-c9d0-41cc-8f19-78d97f839c05
@OpenWrt-NSA325:~# xfs_admin -u /dev/sdb
UUID = 02880b1f-0c67-46b6-9b05-5535680ccc89
```

**Comment by diizzyy** [comment]
To my knowledge xfs isn't supported as far as I can tell by looking at the source code
https://git.openwrt.org/?p=project/fstools.git;a=blob;f=block.c;h=cfc87273ee9969a153a4beededc61a5c6ba40a16;hb=refs/heads/master

Also, I'd be very careful about using xfs as the tools are very old and therefore might be out of sync with the kernel module/filesystem. 
https://github.com/openwrt/openwrt/blob/master/package/utils/xfsprogs/Makefile

**Comment by bobafetthotmail** [comment]
> @p-wassi @bobafetthotmail
> does UUID detection has something to do kernel configuration?
> it's been months now that I haven't able to do fstab automounting
> 

No it does not.

Afaik if **block detect** does not see your partitions, then the automount does not work either, as it is the same tool used in the automount.

From the source posted by diizyy I can see that you can only use ext4, f2fs, vfat, ntfs or btrfs. No xfs.

**Comment by frymezim** [comment]
@diizzyy 
Thanks for the help!

@bobafetthotmail 
Ok that's weird I've been using xfs automouting for almost a 2 years now and since I've upgraded to 4.9 and 4.14 it didn't work. Anyway does enabling config BUSYBOX_DEFAULT_FEATURE_VOLUMEID_XFS in busybox would xfs automount works? or is there any workaround for this?

**Comment by bobafetthotmail** [comment]
>Ok that's weird I've been using xfs automouting for almost a 2 years now and since I've upgraded to 4.9 and 4.14 it didn't work.

Hm, that's weird as it should have never worked, maybe a bug was fixed. Can you show the output of **dmesg** after you plug in a drive that should be automounted (or after reboot with the drive still mounted)?

>Anyway does enabling config BUSYBOX_DEFAULT_FEATURE_VOLUMEID_XFS in busybox would xfs automount works?

I don't know, afaik it shouldn't do anything.

>is there any workaround for this?

Yes, you can write your own hotplug script in /etc/hotplug.d/block so that it is triggered every time a block device is connected and disconnected. 
see here https://openwrt.org/docs/guide-user/base-system/hotplug_lede
Since you are writing it yourself you can use lsblk or xfs_admin to read the UUID to check if the device is indeed your drive and then mount it where you want.

something like the following (untested but should work)

```
# if a new block device is connected
if [ "$ACTION" = "add" ] ; then
    #getting device UUID
    detected_uuid=$( xfs_admin -u /dev/"$DEVICENAME" | awk '{print $3}' )
    #deciding mountpoint for known UUID
    mountpoint=""
    case "$detected_uuid" in
    6a5d7c5c-c9d0-41cc-8f19-78d97f839c05)
            mountpoint="/path/to/first/mountpoint"
            ;;
    02880b1f-0c67-46b6-9b05-5535680ccc89)
            mountpoint="/path/to/second/mountpoint"
            ;;
   esac

   #if we have a known UUID we have a mountpoint so we can mount it
   if [ "$mountpoint" != "" ] ; then 
       mount /dev/"$DEVICENAME" "$mountpoint"
   fi
fi
#unmounting happens automatically at device disconnection anyway so no logic for that
```

**Comment by frymezim** [comment]
This is what I'm getting from dmesg
```
OpenWrt-NSA325:~# dmesg | grep sd
[    1.651930] sd 0:0:0:0: [sda] 7814037168 512-byte logical blocks: (4.00 TB/3.64 TiB)
[    1.659729] sd 0:0:0:0: [sda] 4096-byte physical blocks
[    1.665255] sd 0:0:0:0: [sda] Write Protect is off
[    1.670075] sd 0:0:0:0: [sda] Mode Sense: 00 3a 00 00
[    1.670152] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.717580] sd 0:0:0:0: [sda] Attached SCSI disk
[    2.206100] sd 1:0:0:0: [sdb] 3907029168 512-byte logical blocks: (2.00 TB/1.82 TiB)
[    2.214152] sd 1:0:0:0: [sdb] Write Protect is off
[    2.218962] sd 1:0:0:0: [sdb] Mode Sense: 00 3a 00 00
[    2.219036] sd 1:0:0:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    2.245641] sd 1:0:0:0: [sdb] Attached SCSI disk
[    9.217388] random: ubusd: uninitialized urandom read (4 bytes read)
[    9.224039] random: ubusd: uninitialized urandom read (4 bytes read)
[    9.230442] random: ubusd: uninitialized urandom read (4 bytes read)
[    9.539341] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    9.544790] sd 1:0:0:0: Attached scsi generic sg1 type 0
[    9.628989] usbcore: registered new interface driver ums-isd200
[    9.649368] usbcore: registered new interface driver ums-sddr09
[    9.656182] usbcore: registered new interface driver ums-sddr55

config global
        option anon_swap '1'
        option anon_mount '1'
        option auto_swap '1'
        option auto_mount '1'
        option delay_root '5'
        option check_fs '0'

config mount
        option enabled '1'
        option uuid '6a5d7c5c-c9d0-41cc-8f19-78d97f839c05'
        option target '/mnt/xfs2'
        option fstype 'xfs'
        option options 'nodiratime'

config mount
        option uuid '02880b1f-0c67-46b6-9b05-5535680ccc89'
        option target '/mnt/xfs'
        option fstype 'xfs'
        option options 'nodiratime'
        option enabled '1'

config swap
        option enabled '1'
        option device '/mnt/xfs2/swap'

```
image

**Pull request closed without merging**
