### PR TITLE
[19.07] ath79: add wmac migration for all ar93xx/qca95xx SoCs

### PR DESCRIPTION
**Pull request by Leo-PL**
Backport Wi-Fi migration script for ar71xx devices for ath79 to 19.07 branch. 
I noticed that 19.07 branch lacks this migration while upgrading my fleet of TL-WDR4300, while 19.07.1 is released already.

Compile/run-tested on: TP-Link TL-WDR4300 v1.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Can't this be cherry-picked somewhere?

**Comment by adrianschmutzler** [comment]
Ah, looks like you did cherry-pick it.
Please use "git cherry-pick -x" next time, this will add a line about the commit it was taken from (e.g. https://github.com/openwrt/openwrt/commit/53cd2299ee6ae1e8abe3a3823c7b47eea87952a5).

For this PR, either add it manually or just quickly recreate with "git cherry-pick -x".

**Comment by adrianschmutzler** [comment]
But thanks for bringing that at the table, I've always wondered why people have problems with wmac migration while the scripts are there. Just wasn't aware that those have never been moved to 19.07.

**Comment by Leo-PL** [comment]
> 
> 
> Ah, looks like you did cherry-pick it.
> Please use "git cherry-pick -x" next time, this will add a line about the commit it was taken from (e.g. [53cd229](https://github.com/openwrt/openwrt/commit/53cd2299ee6ae1e8abe3a3823c7b47eea87952a5)).
> 
> For this PR, either add it manually or just quickly recreate with "git cherry-pick -x".

Ok, will do in a short while.

**Comment by adrianschmutzler** [comment]
@981213 Any objection against backporting those migrations?

**Review by 981213 — APPROVED** [review]

**Comment by adrianschmutzler** [comment]
Thanks, I've merged this into 19.07 (and added a Tested-by from Leo-PL according to his initial comment here.)

**Pull request closed without merging**
