### PR TITLE
kirkwood: switch to 6.1 and drop 5.15

### PR DESCRIPTION
**Pull request by CHKDSK88**
This PR contains all required changes for switching kirkwood to 6.1.

There was some issues:
1.  Kernel size problem. There was three ways:
- introduce 'tiny' subtarget for devices with small kernel partition
- another fight with kernel size, which will must be done in all kernel switches.
- Disable it by default
- resize kernel partition

  ~~I chosen 'tiny' subtarget.~~ I chosen resize kernel partiton. This devices have enough RAM for another version. There no need to drop it at this moment.

2. I found some issues with DSA devices, which needs patches from newer kernels.
3. Package dependency. 6.1 kernel cause problem with kmod-gpio-fan.

All of them are fixed. Kirkwood can be switched to 6.1.

### CODE REVIEW

**Comment by CHKDSK88** [comment]
I asked for help on forum:
https://forum.openwrt.org/t/looking-for-someone-with-linksys-ea3500/191253

If someone paste me EA3500 envs, I will drop tiny target and change partition size for those routers.

**Comment by CHKDSK88** [comment]
@sanderpqr 

Please look and test if Iomega is ok.

**Comment by CHKDSK88** [comment]
> > @sanderpqr
> > Please look and test if Iomega is ok.
> 
> I'll make some time for it this weekend. Just to be sure before I brick my device: If I run the 'fw_setenv' commands mentioned in the makefile via the OpenWrt console over SSH, I still need boot the initramfs image via TFTP, correct?

Yes, exactly. In envs you change only size of loaded kernel size. Iomega have separate kernel and rootfs partition and old system don't know new partition system.
1. Adjust envs. Old image will work after that operation.
2. Load initramfs and apply sysupgrade.

P.S.
If you have u-boot and envs backup, kirkwood is unbricable. :)

**Comment by CHKDSK88** [comment]
> @CHKDSK88 I've been tinkering with it today. Are you sure the command
> 
> `setenv bootcmd 'setenv bootargs $$$${console} $$$${mtdparts} $$$${bootargs_root}; nand read.e 0x800000 0x100000 0x300000; bootm 0x00800000'`
> 
> is correct? It's exactly the same as the command in the first [installation instructions](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=4642d8abdc699685db5d4eb251c71055a2bc43fa):
> 
> `setenv bootcmd 'setenv bootargs ${console} ${mtdparts} ${bootargs_root}; nand read.e 0x800000 0x100000 0x300000; bootm 0x00800000'`
> 
> Shouldn't it reference the new kernel size?

Indeed. It was 'too much ctrl-z' edit error. I fixed description.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
