### PR TITLE
tools: use 'xz' versions of packages

### PR DESCRIPTION
**Pull request by qosmio**
There is a discrepancy between `packages` and `tools` where the same package is essentially downloaded twice due to different extensions. ('gz' vs 'xz').

```
dl/e2fsprogs-1.47.0.tar.gz          dl/e2fsprogs-1.47.0.tar.xz
dl/gmp-6.3.0.tar.gz                 dl/gmp-6.3.0.tar.xz
dl/libtool-2.4.7.tar.gz             dl/libtool-2.4.7.tar.xz
dl/sed-4.9.tar.gz                   dl/sed-4.9.tar.xz
dl/util-linux-2.39.3.tar.gz         dl/util-linux-2.39.3.tar.xz
dl/zlib-1.3.1.tar.gz                dl/zlib-1.3.1.tar.xz
dl/zstd-1.5.5.tar.gz                dl/zstd-1.5.6.tar.gz
```

Initially I thought this was due to the build needing to compile 'xz' before it could use it, but 'xz' is already an OS build requirement and is already in use by other tool packages.

```
tools/7z/Makefile:PKG_SOURCE:=$(PKG_NAME)$(PKG_SOURCE_VERSION)-src.tar.xz
tools/autoconf-archive/Makefile:PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
tools/findutils/Makefile:PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
tools/gengetopt/Makefile:PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
tools/llvm-bpf/Makefile:PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).src.tar.xz
tools/mklibs/Makefile:PKG_SOURCE:=$(PKG_NAME)_$(PKG_VERSION).tar.xz
tools/sed/Makefile:PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
```

`xz` is also one of the [build requirements](https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem) and is default on many distros + the github ubuntu images.

### CODE REVIEW

**Comment by rany2** [comment]
This was in fact a deliberate change, see: https://github.com/openwrt/openwrt/commit/bab3ae2ee7656600a185f4cef11cef94389023af

**Comment by robimarko** [comment]
Yes, as pointed out this was fully intentional to start moving away from XZ.
Recent events finally provided a good incentive to do so.

**Comment by qosmio** [comment]
Thanks for the feedback, wasn't aware.

**Comment by rany2** [comment]
> There is a discrepancy between `packages` and `tools` where the same package is essentially downloaded twice due to different extensions. ('gz' vs 'xz').

Though is definitely a valid point, but it should be fixed in the packages repo I guess.

**Pull request closed without merging**
