### PR TITLE
toolchain: binutils: switch to version 2.42 by default

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Change the default binutils version to 2.42.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Ping @hauke @aparcar 

What about updating default binutils version?

**Comment by hauke** [comment]
We should do some testing and then try to merge this. 
I would like to have this for the next major OpenWrt version. 

I am currently looking into update to GCC 13.

**Comment by hauke** [comment]
GCC and musl libc were upgraded. We can merge this probably in 1 week after the musl libc upgrade had some rounds in the CI.

**Comment by PolynomialDivision** [comment]
@hauke Should we merge this now?

**Comment by dhewg** [comment]
I've been running builds using 2.42 on ipq40xx_generic, ramips_mt7621 and mediatek_filogic for quite some time by now. No regression due to this bump afaict

**Comment by PolynomialDivision** [comment]
> I've been running builds using 2.42 on ipq40xx_generic, ramips_mt7621 and mediatek_filogic for quite some time by now. No regression due to this bump afaict

So I can add your tested by?

**Pull request merged**
