### PR TITLE
mwlwifi: Update the 88W8964's firmware to 9.3.2.12 and fix backports version detection

### PR DESCRIPTION
**Pull request by jeolives**
Updates the 88W8964 firmware used in the Linksys WRT3200ACM and WRT32X
from v9.3.2.6 to v9.3.2.12

Removes 0c43219 ("mwlwifi: Fix loading with backports v5.3")
as it has been merged upstream.

Unfortunately, there is a bug where in Kaloz's repo, the version
detection mechanism for fixing vendor commands doesn't work.

It pulls in the Linux kernel version, which as of this time is
"4.14.y" or "4.19.y"

However, the proper behaviour is that it should pull in the mac80211
backports version which as of now is "5.4.27"

The included patch works around this using a backports define found
only on versions >5.3, "VENDOR_CMD_RAW_DATA".

Signed-off-by: Jose Olivera <oliverajeo@gmail.com>

GitHub Notes:
Working off of #2756, this PR updates it by pulling in a fix for backports version detection by @dengqf6 from https://github.com/kaloz/mwlwifi/pull/381/ (unmerged PR) in the official mwlwifi repository.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Hi, please shorten your commit title so it's not wrapped into the message.

**Comment by hauke** [comment]
Thank you for your patch, it was applied to master.

**Comment by lucenera** [comment]
Thank you. You are awesome!

**Comment by giro83** [comment]
Why isn't the new firmware in 19.07.3? :(

root@OpenWrt:~# opkg list-installed | grep mwlwifi-firmware
mwlwifi-firmware-88w8964 - 2019-03-02-31d93860-1

root@OpenWrt:~# dmesg | grep firmware | grep phy
[ 11.599001] ieee80211 phy0: firmware version: 0x9030206
[ 11.905992] ieee80211 phy0: firmware region code: 30
[ 13.343088] ieee80211 phy1: firmware version: 0x9030206
[ 13.649980] ieee80211 phy1: firmware region code: 30

**Pull request closed without merging**
