### PR TITLE
riscv: Add basic support for RISC-V

### PR DESCRIPTION
**Pull request by saeziae**
## What is done
This pull request added basic support for RISC-V architecture. Packages in feed need other patches there.

## Why
Since there have been manufactures making RISC-V boards that have more powerful chips, multiple eth ports and pcie support. It is time to look again into OpenWRT on RISC-V.

## What is patches

- RISC-V architecture was add to related build scripts.
- added `riscv64` device (RISC-V mainline kernel).
- added newest kernel stable for better support for this new architecture.
- `openssl`
- `netfilter`
- `ppp`

## What is tested

It runs successfully on QEMU, and the web panel is available.

Signed-off-by: Estela ad Astra <i@estela.cn>

### CODE REVIEW

**Comment by Ansuel** [comment]
duplicate of #9980 ? also adding 6.1 is currently wip and i think the current direction is to wait for version branch and moving each target to 5.15 before adding 6.1 (and drop 5.10)

**Comment by saeziae** [comment]
It it not something urgent and we could wait for next LTS kernel instead of backport.

Thank you for referring the possible duplication, and I went through it. The code referred to added support to Unmatched which is [discontinued](https://www.google.com/amp/s/www.hackster.io/news/sifive-discontinues-its-hifive-unmatched-risc-v-pc-boards-following-supply-chain-issues-1a1a5d4b7385.amp). I have got a [Visionfive 2](https://www.starfivetech.com/en/site/boards) with dual ethernet ports. After this practice on QEMU, I am trying to port it to Visionfive 2.

**Comment by robimarko** [comment]
Sorry, but what is the purpose of this PR if the #9980 adds the same basic infra and should be merged soon?

**Comment by saeziae** [comment]
If that branch is on the way to merge, I am closing this one.

I think I should open another one when another SoC is added, rebased on that new codebase, after that basic patch on build system is merged.

This current branch exists only because some basic need to be done before adding a board of unsupported architecture.

**Pull request closed without merging**
