### PR TITLE
scripts/download.pl: add tsinghua and ustc mirrors

### PR DESCRIPTION
**Pull request by bradfordzhang**
Add https://mirrors.tuna.tsinghua.edu.cn/ and https://mirrors.ustc.edu.cn/ mirrors into download.pl to speed up download in China.

### CODE REVIEW

**Comment by Ansuel** [comment]
wow they mirror everything? o.o

**Comment by bradfordzhang** [comment]
> wow they mirror everything? o.o

https://mirrors.ustc.edu.cn/status/
https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status

yes they sync everything i added

**Comment by Ansuel** [comment]
@bradfordzhang sorry can you update the title with `scripts/download.pl`
I just notice we were using the wrong tag and for everything inside scripts we should use `scripts/script: ....`

**Comment by bradfordzhang** [comment]
> @bradfordzhang sorry can you update the title with `scripts/download.pl`
> I just notice we were using the wrong tag and for everything inside scripts we should use `scripts/script: ....`

that's okay. I updated

**Comment by bradfordzhang** [comment]
> @bradfordzhang sorry can you update the title with `scripts/download.pl`
> I just notice we were using the wrong tag and for everything inside scripts we should use `scripts/script: ....`

If i should update title 'mirror' to 'mirrors'?

**Comment by bradfordzhang** [comment]
> mirrors should be more correct.

I've edited them

**Comment by bradfordzhang** [comment]
@Ansuel hi! have you seen #10851? official openwrt cdn's jq had been hacked. that make hash from openwrt cdn and other mirrors mismatch. what should we do for that?

**Pull request merged**
