### PR TITLE
NEW DEVICE ARCHITECTURE SUPPORT: Rockchip RT3568 & LinkStar H68K

### PR DESCRIPTION
**Pull request by TahomaSoft**
Pull Request is to add support for rockchip RT3568 boards, particularly Seeed Studio LinkStar H68K.

Compiles to sysimg, uboot might be an issue. MT76/MT79 support not currently available (compile issues).

Signed off by Erik Beck, bacon@tahomasoft.com

### CODE REVIEW

**Comment by motolav** [comment]
Your PR is a mess and doesn't follow the rules in the [submission guide](https://openwrt.org/submitting-patches#submission_guidelines), none of the maintainers will be likely to review your PR until its fixed
Also you must submit to the main branch first not a stable branch
Please don't close the PR but fix your changes and force push to fix it as described [here](https://openwrt.org/docs/guide-developer/working-with-github-pr)

**Comment by motolav** [comment]
One major blocker for you the patch-1.1 folder isn't appropriate for OpenWrt, patches to device trees are generally frowned upon and the kernel config replacement is also unacceptable

**Comment by motolav** [comment]
There is already a PR for the chip you're adding support for too https://github.com/openwrt/openwrt/pull/12974

**Comment by motolav** [comment]
Rebasing your PR off the one linked above and changing your PR to just adding support for your device would be the easiest way forward

**Comment by TahomaSoft** [comment]
Thank you very much for the advice! Will address all the issues you raised as soon as feasible.ErikSent from my iPhoneOn Sep 10, 2023, at 00:55, motolav ***@***.***> wrote:﻿
Rebasing your PR off the one linked above and changing your PR to just adding support for your device would be the easiest way forward

**Comment by TahomaSoft** [comment]
I’m a total newby at doing a PR for something at this scale. Greatly appreciate the good and prompt advice!ErikSent from my iPhoneOn Sep 10, 2023, at 00:55, motolav ***@***.***> wrote:﻿
Rebasing your PR off the one linked above and changing your PR to just adding support for your device would be the easiest way forward

**Comment by TahomaSoft** [comment]
Closing because very stale.

**Pull request closed without merging**
