### PR TITLE
ustp: bump package

### PR DESCRIPTION
**Pull request by systemcrash**
Get @Ansuel's fix in there :)

### CODE REVIEW

**Comment by robimarko** [comment]
Please use this script to generate the package update:
https://git.openwrt.org/?p=maintainer-tools.git;a=blob_plain;f=update_git_source_package.sh;hb=HEAD

**Comment by systemcrash** [comment]
So that's the script. It's needlessly complicated. It needs flags to execute the core of its mission @jow- 

I run it and (on macOS) I get tons of find `-printf` errors:
`find: -printf: unknown primary or operator` so that's something lower down happening. Darwin and BSD find don't have `printf`. My last attempt to fix that specific problem went something like:
```sh
	if [ "$(uname)" = "Darwin" ] || [ "$(uname)" = "FreeBSD" ]; then
		# macOS-specific commands
		find "$1" -path '*/templates/*.pot' -print0 | xargs -0r stat -f '%N' 
...
	elif [ "$(uname)" = "Linux" ]; then
		# Linux-specific commands
		find "$1" -path '*/templates/*.pot' -printf '%h '
...

```

Linux:
```
./update_git_source_package.sh package/network/services/ustp/Makefile a85a5bc83bde5b485319ca12b6e32c4b7f0b120f
Cloning into bare repository '/tmp/tmp.fcCJsGP0ix'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 49 (delta 19), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (49/49), done.
make: Entering directory '/home/user/openwrt/package/network/services/ustp'
make: Nothing to be done for 'download'.
make: Leaving directory '/home/user/openwrt/package/network/services/ustp'
On branch ustpd_bump
Untracked files:
	...

nothing added to commit but untracked files present
```

**Comment by robimarko** [comment]
Script is simple enough for its purpose, either use it or at least generate the changelog via git log as current description is not sufficient

**Comment by robimarko** [comment]
Just put HEAD instead of the hash in the title

**Comment by systemcrash** [comment]
Just doing what the script produced. 🤷🏻‍♂️

**Comment by robimarko** [comment]
Yes, because you gave it a hash, you dont have to give it one and it will just bump to current HEAD.
Putting the hash in title just makes it long.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
