### PR TITLE
kernel: bump 5.10 to 5.10.25

### PR DESCRIPTION
**Pull request by rsalvaterra**
Removed (reverse-applicable):
bmips/patches-5.10/010-v5.11-net-dsa-implement-a-central-TX-reallocation-procedur.patch

Automatically refreshed:
apm821xx/patches-5.10/802-usb-xhci-force-msi-renesas-xhci.patch
ath79/patches-5.10/0036-GPIO-add-named-gpio-exports.patch
ath79/patches-5.10/471-mtd-cfi_cmdset_0002-AMD-chip-0x2201-write-words.patch
bcm63xx/patches-5.10/143-gpio-fix-device-tree-gpio-hogs-on-dual-role-gpio-pin.patch
bmips/patches-5.10/049-v5.13-net-dsa-tag_brcm-add-support-for-legacy-tags.patch
bmips/patches-5.10/050-v5.13-net-dsa-b53-support-legacy-tags.patch
bmips/patches-5.10/505-net-dsa-b53-add-support-for-BCM63xx-RGMIIs.patch
generic/backport-5.10/771-v5.12-net-dsa-be-louder-when-a-non-legacy-FDB-operation-fa.patch
generic/backport-5.10/772-v5.12-net-dsa-don-t-use-switchdev_notifier_fdb_info-in-dsa.patch
generic/backport-5.10/773-v5.12-net-dsa-move-switchdev-event-implementation-under-th.patch
generic/backport-5.10/774-v5.12-net-dsa-exit-early-in-dsa_slave_switchdev_event-if-w.patch
generic/backport-5.10/775-v5.12-net-dsa-listen-for-SWITCHDEV_-FDB-DEL-_ADD_TO_DEVICE.patch
generic/hack-5.10/902-debloat_proc.patch
generic/pending-5.10/120-Fix-alloc_node_mem_map-with-ARCH_PFN_OFFSET-calcu.patch
generic/pending-5.10/640-12-net-dsa-resolve-forwarding-path-for-dsa-slave-ports.patch
generic/pending-5.10/640-16-dsa-slave-add-support-for-TC_SETUP_FT.patch
generic/pending-5.10/703-phy-add-detach-callback-to-struct-phy_driver.patch
generic/pending-5.10/765-net-dsa-Include-local-addresses-in-assisted-CPU-port.patch
generic/pending-5.10/766-net-dsa-Include-bridge-addresses-in-assisted-CPU-por.patch
generic/pending-5.10/767-net-dsa-Sync-static-FDB-entries-on-foreign-interface.patch
ramips/patches-5.10/720-Revert-net-phy-simplify-phy_link_change-arguments.patch
ramips/patches-5.10/721-NET-no-auto-carrier-off-support.patch
ramips/patches-5.10/800-GPIO-add-named-gpio-exports.patch
x86/patches-5.10/200-pcengines-apu2-reboot.patch

Run-tested:
ramips/mt7621 (Redmi AC2100)

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by anomeome** [comment]
compile / test - mvebu / mamba, rango

**Comment by ldir-EDB0** [comment]
I've pushed my own bumps and dropped the pc engines patch 'cos it annoyed me.

**Comment by ynezz** [comment]
> and dropped the pc engines patch 'cos it annoyed me.

@ldir-EDB0 

1. 'annoyed me' is not good enough reason, it would be at least nice to provide more details
2. have you read commit description in 20f365d70f3d219fe808532fe5892ecb134dbc73 ?
3. it must be a nice surprise to find out device miles away in a reboot hang after sysupgrade
4. you're now forcing everybody to use the working BIOS version, but you need to take into account, that sometimes it might not be possible, even if folks badly wanted to do that
5. it would be nice and polite to submit such changes for review beforehand and Cc: author
6. it's certainly acceptable to demand upstreaming of new patches, but IMO certainly not acceptable to remove patches in the tree for 4 years and demand upstreaming them

**Comment by rsalvaterra** [comment]
> I've pushed my own bumps and dropped the pc engines patch 'cos it annoyed me.

Hm. Are you sure you don't need the reboot patch for _any_ BIOS version?

**Comment by rsalvaterra** [comment]
>     6. it's certainly acceptable to demand upstreaming of new patches

This. A thousand times this, please.

**Pull request closed without merging**
