### PR TITLE
config: adds governor and iosched kernel config option

### PR DESCRIPTION
**Pull request by Ansuel**
This adds option to enable support for various kernel governor and iosched directly from openwrt menuconfig

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by pkgadd** [comment]
s/governator/governor/g

Arnie isn't everywhere ;)

**Comment by diizzyy** [comment]
Uhm... The idea isn't bad but this will need more work I think?
Why are multiple governors and schedulers default?

The SCSI option will most likely break things as USB Storage depends on SCSI and as far as I know devices  the boots off USB won't if it's not included in the kernel.

**Comment by bobafetthotmail** [comment]
> The SCSI option will most likely break things as USB storage depends on SCSI and as far as I know devices that boots off USB won't if it's not included in the kernel.

Maybe, or maybe not. Afaik it should be already enabled in their target-specific config, and if it is not it should be enabled there instead than tree-wide. Also, it's not that common for OpenWrt devices to boot from USB anyway.

I've seen that for some targets that don't have significant kernel size limitations the USB, Sata, SCSI and whatnot support is included in the kernel in the target-specific config-x.x file already, although afaik they don't boot from USB, at most they boot from SDcard.

For example Kirkwood https://github.com/openwrt/openwrt/blob/master/target/linux/kirkwood/config-4.14
Mvebu https://github.com/openwrt/openwrt/blob/master/target/linux/mvebu/config-4.14
Sunxi https://github.com/openwrt/openwrt/blob/master/target/linux/sunxi/config-4.14

While I don't find anything about SCSI in ramips or ar71xx (mostly router-like devices where USB is an optional, not crucial for booting)

**Comment by Ansuel** [comment]
i added scsi option flag as some iosched needs a specific option to be used (SCSI_MQ_DEFAULT)

without this option they can't be used. Scsi afaik is build as module so i can't really find a way to enable that option... so we should drop scsi module if that kernel option is selected?

**Comment by Ansuel** [comment]
@diizzyy what you mean with multiple default?

**Comment by diizzyy** [comment]
@bobafetthotmail 
The platform specific targets are quite "kludgy" especially without any kind of documentation in that regard. Given that you're changing the kernel config and no the inclusion of modules it might/will cause breakage unless the default config overrides menuconfig but that would still be ugly and confusing.

@Ansuel 
https://github.com/openwrt/openwrt/pull/1456/files#diff-a9af7e4a79e28e1a7b2e85d7e8150bf8R841
https://github.com/openwrt/openwrt/pull/1456/files#diff-a9af7e4a79e28e1a7b2e85d7e8150bf8R847
etc, is that intended?

**Comment by Ansuel** [comment]
default kernel include both performance and ondemand gov 

the real gov to use is set by this KERNEL_CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND

**Comment by Ansuel** [comment]
any update on this?

**Comment by diizzyy** [comment]
You need to remove existing KERNEL_SCSI and KERNEL_SCSI_MQ_DEFAULT entries from target configs and generic at least to the menu option instead.

**Comment by adrianschmutzler** [comment]
Is there still interest in this? Otherwise we would close it.

**Comment by Ansuel** [comment]
I can rebase it i just need to remove the scsi entries and have only the standards ioched

**Comment by Ansuel** [comment]
@adrianschmutzler should be good now @diizzyy can you review this?

**Comment by adrianschmutzler** [comment]
The "openwrt:" prefix to the commit title obviously isn't much helpful here. Have look what's been done for previous commit in that area and choose a more appropriate one (e.g. kernel: or config:).

**Comment by diizzyy** [comment]
@Ansuel 
I haven't tried to compile or run-test but it looks fine to me

**Comment by Ansuel** [comment]
I have tried to compile without any governor and it does compile well...
Soo should work good


Il Mar 29 Ott 2019, 23:01 Daniel Engberg <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
news on this?

**Comment by wulfy23** [comment]
see notengobattery 's patches re: io-sched + block type assignment...

instability can result from global usage... and a related hotplug block parser would be necessary to avert disk problems.

**Comment by nasbdh9** [comment]
This commit has been working well for me...
 (arm / arm64 / ramips)

**Comment by Ansuel** [comment]
@ynezz this is a minor change can you check this? should not cause ANY problem at all

**Comment by adrianschmutzler** [comment]
Hi, since this is not a fix, but a feature, and none of the committer seems to be interested in reviewing it, I will close it now (i.e. "Won't implement").

I'm sorry, but better crush your remaining hopes now than waiting another year where supposedly nothing will be different.

**Pull request closed without merging**
