### PR TITLE
base-files: led: add stop all leds procedure

### PR DESCRIPTION
**Pull request by garlett**
"Fixed script for allowing all leds to be turned off with one command without losing configuration"

Signed-off-by: Thi Garlet 
<garlet@gmail.com>

### CODE REVIEW

**Comment by garlett** [comment]
I am unable to understand this DCO signed-off-by bot

**Comment by adschm** [comment]
> I am unable to understand this DCO signed-off-by bot

You are also unable to read the links I provided, otherwise you wouldn't have opened a new PR.

**Comment by garlett** [comment]
Can you help me? 
I am using the GitHub web interface, and I couldn't find how to edit the last commit. I forgot to insert the description:

"Fixed script for allowing all leds to be turned off with one command without losing configuration"

I don't know if the signed-off-by clause is correct. 

The first PT was not from a clone of my repository. 

I clonned around 5 times and retyped the patch, but this results in a new PR. 

Thanks

**Comment by adschm** [comment]
You have to clone, update, and then force-push to your GitHub repo again. That way the PR will be updated.

Please address the formal issues, so this does not just rot here for another two months.

**Comment by Ansuel** [comment]
@garlett can you fix this? Or you are not interested anymore?

**Comment by garlett** [comment]
@Ansuel sure, but I'm without access to my openwrt machine, and I don't know if:


"Fixed script for allowing all leds to be turned off with one command without losing configuration"

Signed-off-by: Thi Garlet
[garlet@gmail.com](mailto:garlet@gmail.com)



Is correct?

**Comment by Ansuel** [comment]
@garlett you can totally do this on any machine. 

About the message. Commit message are "imperative". You tell the machine what to change.

Something like 
```
Add stop() function to turn off all leds without losing configuration.
Use service leds stop to turn off all leds.

Signed-off-by: Thi Garlet <garlet@gmail.com>
```

**Comment by Ansuel** [comment]
@garlett still interested?

**Pull request closed without merging**
