### PR TITLE
tools/ccache: update to 4.4.2

### PR DESCRIPTION
**Pull request by neheb**
Refreshed patch.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by nxhack** [comment]
The mixed cache of 4.3 and 4.4 had an impact on linux kernel related issues.

https://github.com/ccache/ccache/issues/926

**Comment by neheb** [comment]
Wow.

What's interesting is this "bug" enabled me to find actual bugs in several packages.

**Comment by neheb** [comment]
Setting to Draft for now.

**Comment by aparcar** [comment]
v4.4.1 released.

**Comment by neheb** [comment]
Yeah. Note that this is set to draft because there is a huge bug that prevents proper compilation. Upstream is working on it.

**Comment by aparcar** [comment]
Bug solved?

**Comment by neheb** [comment]
yep. Upstream reproduced and fixed.

**Comment by nxhack** [comment]
v4.4.2 did not have the problems that v4.4 backed.  LGTM

**Comment by aparcar** [comment]
Thanks

**Pull request closed without merging**
