### PR TITLE
firmware: add Intel BE200 firmware

### PR DESCRIPTION
**Pull request by januszdziedzic**
Add Intel BE200 firmware config option

### CODE REVIEW

**Comment by robimarko** [comment]
Is this firmware usable with the current iwlwifi driver in OpenWrt?

**Comment by januszdziedzic** [comment]
> Is this firmware usable with the current iwlwifi driver in OpenWrt?

Yes, I am using bpi-r64 as a test clients in my setup - inside Intel BE200.

**Comment by robimarko** [comment]
Please change the commit title to have the `linux-firmware: intel:` prefix

**Comment by xabolcs** [comment]
@januszdziedzic 
Sorry for nitpicking, but use lower case for the prefix!

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
