### PR TITLE
Add {arp,eb}tables-nft, rename curent versions to {arp,eb}tables-legacy

### PR DESCRIPTION
**Pull request by champtar**
Need to send the patch upstream but it should be ready for testing

Some future work in netfilter.mk is to split out all the legacy tables (arptable_* / ebtable_* / iptable_* / ip6table_*)
in separate packages

### CODE REVIEW

**Comment by champtar** [comment]
https://bugzilla.netfilter.org/show_bug.cgi?id=1593

**Comment by champtar** [comment]
A modified version of my patch was accepted upstream, I'm keeping my patch as I need to cherry pick at least 2 patches but they do not apply cleanly. I can try to find all the needed patch if preferred.

**Comment by champtar** [comment]
After this PR ip6tables doesn't depend on iptables anymore, some packages DEPENDS might need fixing.

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 2f5088ef5f3abd581e82970d223206a87a3c1909, 905b49920fa85d80aa36c1df0db1bb8f13843648, afb6824a2c188e5f2610c989a2848bb70e594efb, c913be1da1b4688cbfebaa54895624ad5e01c476, 66bb6dde36c22d3fb305f2d75741efd715ffeccc and 30c15d06e872c3170367fbf3c33da3d2b7b639cd.

**Pull request closed without merging**
