### PR TITLE
malta: Add kernel 6.6 support

### PR DESCRIPTION
**Pull request by hauke**
This adds basic kernel 6.6 support to the MIPS malta target.

### CODE REVIEW

**Comment by guidosarducci** [comment]
Thanks for this, and also apparently doing some "all modules" builds to shake out problems -- certainly time-consuming. I was in the middle of testing my own malta 6.6 PR, but yours looks fully baked so looking forward to seeing it merged.

I can confirm no major changes were needed for 6.6, at least with `malta/mipseb32` and `malta/mipsel64` which I tested. The kernel bump did break building `kselftests-bpf`, a devel package not built by default, so I'm working on some package fixes and also related upstream Linux patches.

I'd also note that of the config changes in https://github.com/openwrt/openwrt/pull/14891/commits/25887c297e2b3632718e8deea504d9a31fab653e, many also appear in other arches and could likely be filtered out or pulled into the top-level generic config. But probably best to wait for more 6.6 arch updates before trying to clean up and factor out changes. Cheers!

**Review by guidosarducci — APPROVED** [review]
LGTM

**Review by ehem — CHANGES_REQUESTED** [review]
There is a script for this which serves to preserve history.  That should be used instead.

**Review by ehem — CHANGES_REQUESTED** [review]
There are history preserving scripts for this, those should be used instead.

**Comment by sbwml** [comment]
> I can confirm no major changes were needed for 6.6, at least with `malta/mipseb32` and `malta/mipsel64` which I tested. The kernel bump did break building `kselftests-bpf`, a devel package not built by default, so I'm working on some package fixes and also related upstream Linux patches.

Hi! Do you have any progress on linux-6.6 `kselftests-bpf`?

Initially, I encountered an error: `cc: error: unrecognized command-line option '-fhonour-copts'; did you mean '-fhonor-std'?`

---------

I attempted to remove `-fhonour-copts` from TARGET_CFLAGS：

package/devel/kselftests-bpf/Makefile

`TARGET_CFLAGS := $(subst -fhonour-copts,,$(TARGET_CFLAGS))`

Afterward, I encountered another error:

```
make[3]: Entering directory '/home/sbwml/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.6.22/tools/testing/selftests/bpf'
  MKDIR    libbpf
In file included from <command-line>:
/home/sbwml/openwrt/staging_dir/toolchain-x86_64_gcc-14.0.1_musl/include/stdc-predef.h:10: error: "__STDC_UTF_16__" redefined [-Werror]
   10 | #define __STDC_UTF_16__ 1
      | 
<built-in>: note: this is the location of the previous definition
In file included from <command-line>:
/home/sbwml/openwrt/staging_dir/toolchain-x86_64_gcc-14.0.1_musl/include/stdc-predef.h:11: error: "__STDC_UTF_32__" redefined [-Werror]
   11 | #define __STDC_UTF_32__ 1
      | 
<built-in>: note: this is the location of the previous definition
cc1: all warnings being treated as errors
```

😔 I have no way to handle this error.  I hope this error is not because I'm using GCC14. After all, for me, it is very difficult to switch toolchains for testing, and it requires a lot of time.

**Comment by guidosarducci** [comment]
> Hi! Do you have any progress on linux-6.6 `kselftests-bpf`?
> 
> Initially, I encountered an error: `cc: error: unrecognized command-line option '-fhonour-copts'; did you mean '-fhonor-std'?`

> 😔 I have no way to handle this error. I hope this error is not because I'm using GCC14. After all, for me, it is very difficult to switch toolchains for testing, and it requires a lot of time.

@sbwml Hello, I'm the author and maintainer of `kselftests-bpf` package. Yes, I fixed it while also adding kernel 6.6 support for malta on my own. Seeing the changes from @hauke I decided to let him merge this first before re-testing and submitting my `kselftests-bpf` updates. I'll let him comment on what the issue might be delaying this PR. Since `kselftests-bpf` isn't built by default it shouldn't be a problem; do you need it for something you're working on?

I've tested with both GCC 12 and 13 and confirm it works fine; GCC 14 hasn't been released AFAIK so I wouldn't consider it reliable to use or worthwhile to troubleshoot.

**Comment by sbwml** [comment]
> @sbwml Hello, I'm the author and maintainer of `kselftests-bpf` package. Yes, I fixed it while also adding kernel 6.6 support for malta on my own. Seeing the changes from @hauke I decided to let him merge this first before re-testing and submitting my `kselftests-bpf` updates. I'll let him comment on what the issue might be delaying this PR. Since `kselftests-bpf` isn't built by default it shouldn't be a problem; do you need it for something you're working on?


Thanks for your reply, I found the answer in your warehouse `guidosarducci/openwrt/commits/master-test-misc-6.6`, and now kselftests-bpf has been successfully built

**Comment by guidosarducci** [comment]
@hauke Can this be merged now or are there some issues remaining? Have this would simplify upstream kernel testing...

**Comment by hauke** [comment]
This was merged in the similar PR #15215.

**Pull request closed without merging**
