### PR TITLE
kernel: bump 5.10 to 5.10.63

### PR DESCRIPTION
**Pull request by rsalvaterra**
Patches automatically refreshed.

Run-tested:
ramips/mt7621 (Redmi AC2100)

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Review by xh0823 — APPROVED** [review]

**Comment by graysky2** [comment]
```  
    Build system: x86_64
    Build-tested: bcm2711/RPi4B
    Run-tested: bcm2711/RPi4B
```

**Comment by graysky2** [comment]
5.10.63
```  
Build system: x86_64
Build-tested: bcm2711/RPi4B
Run-tested: bcm2711/RPi4B
```

**Comment by ldir-EDB0** [comment]
X86_64 APU2 is good for me.

**Comment by graysky2** [comment]
```
Build system: x86_64
Build-tested: ipq806x/R7800
Run-tested: ipq806x/R7800
```

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master.

**Pull request closed without merging**
