### PR TITLE
mvebu: uDPU/eDPU: use F2FS ZSTD compression

### PR DESCRIPTION
**Pull request by robimarko**
uDPU/eDPU devices use F2FS on eMMC, so we can utilize ZSTD compression in F2FS to prolong the eMMC life.

It is currently only enabled in case partitions are reformated or in a case of a new device since F2FS formatting to migrate takes a really long time (We are talking around 30 minutes in case rootfs is quite filled).

### CODE REVIEW

**Comment by mrkiko** [comment]
Really nice and would also be great to see this applied to more eMMC devices.

**Comment by Ansuel** [comment]
Nice that special option finally used! Happy it works correctly

**Comment by Ansuel** [comment]
@robimarko can you rebase on top of main?

**Comment by robimarko** [comment]
@Ansuel done

**Pull request merged**
