### PR TITLE
kernel: bump 5.15 to 5.15.67

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased

Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by graysky2** [comment]
@neheb @ynezz - The addition of `ARM64_ERRATUM_2441009` applies to Cortez-A510[1] but I am not totally sure which subarchs support that chip.  I grepped for `CONFIG_ARM64_ERRATUM` and found the 6 which I applied it to in this PR.  I need feedback as to whether or not that was the right course of action.

Finally, as stated in the commit message, removing `bcm27xx/patches-5.15/950-0019-drm-vc4-select-PM.patch` seemed like the right move since `CONFIG_PM=y` is selected anyway.

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/arch/arm64/Kconfig?id=v5.15.65&id2=v5.15.64

**Comment by LGA1150** [comment]
None of the subtargets uses ARMv9, just take a look at https://downloads.openwrt.org/snapshots/packages/

**Comment by graysky2** [comment]
Thanks guys, done.

**Comment by anomeome** [comment]
Refresh required due to [commit](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=884e63fa68f717a3feb14c930cc0269f0450ef5a)

**Comment by dangowrt** [comment]
Tested for a couple of days on a couple of devices. Picked to master.

**Pull request closed without merging**
