### PR TITLE
mediatek: various efforts to improve SNFI reliability

### PR DESCRIPTION
**Pull request by dangowrt**
The Linksys E8450 aka. Belkin RT3200 suffers from a hard-to-catch issue with unreliable writes to the SPI-NAND flash which is attached via the SNFI interface (ie. using SoC BCH engine instead of on-die ECC of the flash chip).
Apply various changes which hopefully help to get rid of what has been dubbed the "OpenWrt Kiss of Death" (OKD) once we create an updated UBI installer for the device based on them.

### CODE REVIEW

**Comment by aiamadeus** [comment]
For the [kernel part changes](https://github.com/openwrt/openwrt/pull/15112/commits/142166318acdd4c3d17f8ad52be623dfad2edfe8), I can confirm this works on
MT7981 + DS35Q1GA (which uses on-die ECC).
Before this change:
```
[    0.713881] spi spi0.0: setup: ignoring unsupported mode bits a00
[    0.720304] spi-nand spi0.0: Fidelix SPI NAND was found.
[    0.725615] spi-nand spi0.0: 128 MiB, block size: 128 KiB, page size: 2048, OOB size: 64
[    2.057819] ubi0 warning: ubi_eba_init: cannot reserve enough PEBs for bad PEB handling, reserved 17, need 19
[    9.654826] ubi0 warning: ubi_io_read: error -74 (ECC error) while reading 11 bytes from PEB 244:7585, read only 11 bytes, retry
[    9.666820] UBIFS error (ubi0:2 pid 463): ubifs_lpt_init: invalid type (15) in LPT node type 2
[    9.743737] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" stops
[    9.750287] mount_root: failed to mount -t ubifs /dev/ubi0_2 /tmp/overlay: Invalid argument
```
After this change:
```
[    0.716792] spi spi0.0: setup: ignoring unsupported mode bits a00
[    0.723257] spi-nand spi0.0: Fidelix SPI NAND was found.
[    0.728569] spi-nand spi0.0: 128 MiB, block size: 128 KiB, page size: 2048, OOB size: 64
[    2.049643] ubi0 warning: ubi_eba_init: cannot reserve enough PEBs for bad PEB handling, reserved 17, need 19
[    9.770535] mount_root: overlay filesystem has not been fully initialized yet
[    9.777911] mount_root: switching to ubifs overlay
```

**Comment by mrkiko** [comment]
Is switching to the performance governor or leaving cpufreq alone alltogeter considered still something important?
May this be an occasion to do that?

**Comment by rsalvaterra** [comment]
> too low voltage (or frequency?)

It was the voltage. I reinstated the 300 MHz OPP in my tree at 1 V and it never failed on me (minus the hang I started having at reboot with Linux 6.6, but that's another issue, surely).

**Comment by mrkiko** [comment]
What's the merging perspective for this PR?

**Comment by dangowrt** [comment]
Currently @onlyfly34 is working with some people on the forum with bricked devices to figure out how to address the root cause. I'm waiting for the result, and then would go ahead and merge this PR if it is deemed suitable.

**Comment by romanovj** [comment]
I have same problem with F50L1G41LB (routerich mt7981)

same thing many times:
_We may need a similar fix for the U-Boot driver, though problems have not been observed there. **However, we sporadically see bl2 failing to load fip for no apparent reason (ie. after the device was powered-off and working fine before, or after a reboot). The error then persists.**_

nanddump and nandtest and flash_erase shows 0 errors 0 ECC

squashfs and ubi errors 
```
[30856.271736] SQUASHFS error: Failed to read block 0x5e7584: -5
[30856.277530] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30856.284276] SQUASHFS error: Unable to read inode 0x2c2a0be1
[30856.290976] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30856.297748] SQUASHFS error: Unable to read inode 0x2c2a0fa3
[30856.303576] SQUASHFS error: Failed to read block 0x5e8da6: -5
[30856.303925] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30856.309482] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[30856.316079] SQUASHFS error: Unable to read inode 0x2c2a1383
[30856.316855] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30856.322917] SQUASHFS error: Unable to read directory block [5e8da4:1690]
[30856.328349] SQUASHFS error: Unable to read inode 0x2c2a1323
[30856.335113] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[30856.354289] SQUASHFS error: Unable to read directory block [5e8da4:1690]
[30856.354368] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30856.367748] SQUASHFS error: Unable to read inode 0x2c2a0c41
[30946.558526] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30946.565253] SQUASHFS error: Unable to read inode 0x2c2a0be1
[30946.571779] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30946.578619] SQUASHFS error: Unable to read inode 0x2c2a0fa3
[30946.584902] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30946.591797] SQUASHFS error: Unable to read inode 0x2c2a1383
[30946.597987] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30946.599413] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[30946.604909] SQUASHFS error: Unable to read inode 0x2c2a1323
[30946.611463] SQUASHFS error: Unable to read directory block [5e8da4:1690]
[30946.624067] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[30946.630821] SQUASHFS error: Unable to read directory block [5e8da4:1690]
[30946.638005] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30946.644753] SQUASHFS error: Unable to read inode 0x2c2a0c41
[30951.610998] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[30951.617804] SQUASHFS error: Unable to read directory block [5e8da4:1690]
[30951.624529] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[30951.631275] SQUASHFS error: Unable to read directory block [5e8da4:1690]
[30951.680419] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30951.687170] SQUASHFS error: Unable to read inode 0x2c2a0be1
[30951.694198] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30951.700956] SQUASHFS error: Unable to read inode 0x2c2a0fa3
[30951.707095] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30951.713841] SQUASHFS error: Unable to read inode 0x2c2a1383
[30951.720061] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30951.725899] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[30951.726815] SQUASHFS error: Unable to read inode 0x2c2a1323
[30951.739338] SQUASHFS error: Unable to read directory block [5e8da4:1690]
[30951.746203] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[30951.752940] SQUASHFS error: Unable to read directory block [5e8da4:1690]
[30951.759953] SQUASHFS error: Unable to read metadata cache entry [5e7582]
[30951.766722] SQUASHFS error: Unable to read inode 0x2c2a0c41
[31008.981402] UBIFS error (ubi0:2 pid 22176): ubifs_read_node: bad node type (0 but expected 2)
[31008.989974] UBIFS error (ubi0:2 pid 22176): ubifs_read_node: bad node at LEB 14:22096, LEB mapping status 1
[31008.999716] Not a node, first 24 bytes:
[31008.999722] 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00                          ........................
[31009.016415] CPU: 0 PID: 22176 Comm: ash Tainted: G        W  O       6.6.36 #0
[31009.023625] Hardware name: Routerich AX3000 (DT)
[31009.028228] Call trace:
[31009.030662]  dump_backtrace+0x9c/0xd8
[31009.034319]  show_stack+0x14/0x1c
[31009.037625]  dump_stack_lvl+0x44/0x58
[31009.041278]  dump_stack+0x14/0x1c
[31009.044581]  ubifs_read_node+0x22c/0x250
[31009.048494]  ubifs_tnc_read_node+0xa8/0xb0
[31009.052580]  tnc_read_hashed_node+0x7c/0x1c4
[31009.056840]  ubifs_tnc_locate+0x1b4/0x1d8
[31009.060839]  ubifs_tnc_lookup_nm+0x30/0x12c
[31009.065011]  ubifs_lookup+0x138/0x294
[31009.068663]  __lookup_slow+0x74/0x120
[31009.072318]  lookup_one_unlocked+0x6c/0x80
[31009.076406]  ovl_lookup_single+0x48/0x32c
[31009.080406]  ovl_lookup_layer+0x128/0x168
[31009.084407]  ovl_lookup+0xd8/0xc08
[31009.087799]  __lookup_slow+0x74/0x120
[31009.091453]  walk_component+0xd0/0x184
[31009.095191]  path_lookupat+0x70/0x19c
[31009.098842]  filename_lookup+0x7c/0x12c
[31009.102666]  vfs_statx+0x74/0x148
[31009.105972]  vfs_fstatat+0x11c/0x148
[31009.109538]  __do_sys_newfstatat+0x18/0x38
[31009.113624]  __arm64_sys_newfstatat+0x1c/0x24
[31009.117970]  invoke_syscall.constprop.0+0x4c/0xe0
[31009.122663]  do_el0_svc+0x3c/0xb8
[31009.125967]  el0_svc+0x18/0x4c
[31009.129015]  el0t_64_sync_handler+0x118/0x124
[31009.133361]  el0t_64_sync+0x150/0x154
[31009.137195] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[31009.143919] SQUASHFS error: Unable to read directory block [5e8da4:129c]
[31009.150653] SQUASHFS error: Unable to read metadata cache entry [5e8da4]
[31009.157351] SQUASHFS error: Unable to read directory block [5e8da4:f40]
```

**Can't boot after reboot**

```
NOTICE:  EMI: Detected DRAM size: 256MB
NOTICE:  EMI: complex R/W mem test passed
NOTICE:  CPU: MT7981 (1300MHz)
NOTICE:  SPI_NAND parses attributes from parameter page.
NOTICE:  SPI_NAND Detected ID 0xc8
NOTICE:  Page size 2048, Block size 131072, size 134217728
NOTICE:  Initializing NMBM ...
NOTICE:  Signature found at block 1023 [0x07fe0000]
NOTICE:  First info table with writecount 1 found in block 960
NOTICE:  Second info table with writecount 1 found in block 963
NOTICE:  NMBM has been successfully attached in read-only mode
NOTICE:  BL2: Booting BL31
INFO:    Total CPU count: 2
INFO:    MCUSYS: L2C share 256K --> 0K
INFO:    Disable NETSYS SRAM remapping
INFO:    Secondary bootloader is AArch64
INFO:    GICv3 without legacy support detected.
INFO:    ARM GICv3 driver initialized in EL3
INFO:    Maximum SPI INTID supported: 671
INFO:    SPMC: Changed to SPMC mode
NOTICE:  BL31: v2.7(release):20230902-14-g19cfed05-dirty
NOTICE:  BL31: Built : 17:02:14, Jan 15 2024
NOTICE:  Hello BL31!!!
INFO:    BL31: Initializing runtime services
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x41e00000
INFO:    SPSR = 0x3c9
```

Repaired by reflashing BL2 with mtk_uartboot

**Comment by dangowrt** [comment]
This problem with F50L1G41LB looks very different from the phenomenon observed with the DS35Q1GA aka. FM35Q1GA on the Belkin device: There reading under Linux or U-Boot just always works, only reading BL31 gave us problems. Also note that on the Belkin device we are *not* using the normal SPI controller of the SoC but rather a dedicated SPI-NAND Flash Interface (SNFI) which uses a hardware ECC (BCH) engine instead of the on-die ECC. And we are not using NMBM at all. So all quite different, different chip, different drivers, ...

**Comment by romanovj** [comment]
> This problem with F50L1G41LB looks very different from the phenomenon observed with the DS35Q1GA aka. FM35Q1GA on the Belkin device: There reading under Linux or U-Boot just always works, only reading BL31 gave us problems. Also note that on the Belkin device we are _not_ using the normal SPI controller of the SoC but rather a dedicated SPI-NAND Flash Interface (SNFI) which uses a hardware ECC (BCH) engine instead of the on-die ECC. And we are not using NMBM at all. So all quite different, different chip, different drivers, ...

1. Some times device can't read BL2 after squashfs/ubi errors
2. I can't enter uboot console. (or that's how it is without fip?)
3. I booted into openwrt on spi-nand with mtk_uartboot (my own compiled BL2 with uart  + stock fip), checked BL2 partition - no errors. Rebooting leads to `INFO:    BL31: Preparing for EL3 exit to normal world`
4. I din't reflash fip partition, **only BL2** from uboot failsafe web page. After it I can reboot.

Rebooting by unplugging or after poweroff command could lead to such errors.
Rebooting after IO errors could lead to hanging on `INFO:    BL31: Preparing for EL3 exit to normal world` or later stage(didn't have uart connected, maybe UBI mounting?).

**Comment by dangowrt** [comment]
It's also a very old (and odd) version of ARM TrustedFirmware-A, apparently modified by the device vendor.
Things like
```
NOTICE:  Hello BL31!!!
```
are not part of the upstream TF-A nor of MediaTek's published version on Github. So it's very hard to tell what's going on there, and literally out of our control, because it's code outside of OpenWrt which we are not building from source.

**Comment by romanovj** [comment]
@dangowrt that's shouldn't be BL2 issue, there is no BL2 code inside ram after booting, right? So why I see squashfs/ubi errors? After such errors I see many ECC errors with `nanddump -f /dev/null /dev/mtd5`. Rebooting could fix everything or break everything)

**Comment by dangowrt** [comment]
> So why I encounter with squashfs/ubi errors?

It's what I'm saying: You are commenting on a commit which attempts to improve the situation on the Linksys/Belkin device. We **never** saw any squashfs or ubi errors on that device. We only observed problems with BL2 not being able to load BL31 due to CRC errors. When reading the same volume later at boot in U-Boot or under Linux **it was always all fine**. Even **rewriting** with the data just read from flash magically fixes the issue. Hence I assume it is either related to the flash chip itself and some instability (which I consider likely) or some problems with the use of the ECC/BCH engine in the SNFI driver in BL2.
Hence, the issue you are describing here is **a completely different issue** and **unrelated** to this commit.

**Comment by romanovj** [comment]
@dangowrt 
same for me
_When reading the same volume later at boot in U-Boot or under Linux it was always all fine. Even rewriting with the data just read from flash magically fixes the issue._

What about different chip? Or it's near the same as FM35Q1GA(DS35Q1GA)?
_We observed the same thing on Foresee's F35SQA001G._
https://github.com/mtk-openwrt/arm-trusted-firmware/pull/7#issuecomment-2041841382

**Comment by dangowrt** [comment]
> same for me

You mentioned:
> squashfs and ubi errors

And that doesn't sound like
> When reading the same volume later at boot in U-Boot or under Linux it was always all fine

Hence I'm confused. What is the purpose of your comments on this commit? Is there something wrong with it in your opinion or not? 
Are you suggesting to use the same work-around (in Linux) also for other chips? If so, please file a PR or at least open an issue clearly stating that.

**Comment by romanovj** [comment]
@dangowrt I just wrote that I'm seeing similar patterns with my device. That's all.
Maybe there is something similar in mtk spi driver 1 and mtk spi driver 2.

**Pull request merged**
