### PR TITLE
realtek: Do not set KERNEL_ENTRY just to avoid NO_EXCEPT_FILL

### PR DESCRIPTION
**Pull request by oliv3r**
It seems like we are offsetting the KERNEL_ENTRY to +0x400, which is also accomplished by the NO_EXCEPT_FILL configuration option.

Since this is the default for MIPS_GENERIC_KERNEL, lets push a little bit closer to that one by doing the same thing.

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>

### CODE REVIEW

**Comment by oliv3r** [comment]
Haven't tested this much yet (will do tomorrow) but really need some more testing on RTL83xx and on different hardware.

**Comment by svanheule** [comment]
Interesting to see you're trying to move toward `CONFIG_MIPS_GENERIC_KERNEL`. The changes look like they're split up in an odd way though; updating the symbol selection after updating the patch doesn't break (non-interactive) builds in between? Otherwise I would suggest to remove `KERNEL_ENTRY` in a second patch, and keep the symbol changes grouped together, if that makes sense.

**Comment by oliv3r** [comment]
> Interesting to see you're trying to move toward `CONFIG_MIPS_GENERIC_KERNEL`. The changes look like they're split up in an odd way though; updating the symbol selection after updating the patch doesn't break (non-interactive) builds in between? Otherwise I would suggest to remove `KERNEL_ENTRY` in a second patch, and keep the symbol changes grouped together, if that makes sense.

@svanheule I actually got genkernel working now :) so I'm trying to get those patches in in the upcoming days.

Not sure what you mean. `NO_EXCEPT_FILL` is tightly coupled with `KERNEL_ENTRY`. You need to do both in sync, or you cannot boot.

The Kconfig changes we can squash together, or just drop complexity and do a 'generic lets just update everything together' commit that we seem to do :) You won't get a pop-up or anything, but I wanted to avoid the 'big refresh config' patches.

**Comment by svanheule** [comment]
Have you seen these similar upstream patches?
https://lore.kernel.org/linux-mips/20200527063438.391949-4-jiaxun.yang@flygoat.com/
https://lore.kernel.org/linux-mips/1347806915-25132-2-git-send-email-hauke@hauke-m.de/

Since our kernel is now loaded at 0x80100000, I take the same arguments apply here. I've checked, and the (mainline) kernel actually sets the ebase address to a non-0x80000000 address, so it would probably even work with the old load address.

Maybe you just didn't word it properly in your commit message, but that means the +0x400 entry address is used to compensate for the absence of NO_EXCEPT_FILL. Not that you can substitute one for the other.

I plan to submit the following upstream:
```diff
From: Sander Vanheule <sander@svanheule.net>
Date: Sat, 14 Jan 2023 17:34:46 +0100
Subject: [PATCH] mips: select NO_EXCEPT_FILL for MACH_REALTEK_RTL

These CPUs support MIPS32 R2, and allow ebase relocation. Even if the
default exception base of 0x80000000 is used, the MIPS_GENERIC load
address of 0x80100000 leaves sufficient space to not need an extra 0x400
bytes of padding.

Suggested-by: Olliver Schinagl <oliver@schinagl.nl>
Signed-off-by: Sander Vanheule <sander@svanheule.net>
---
 arch/mips/Kconfig | 1 +
 1 file changed, 1 insertion(+)

diff --git a/arch/mips/Kconfig b/arch/mips/Kconfig
index 2db5c853992e..a8895aaa490e 100644
--- a/arch/mips/Kconfig
+++ b/arch/mips/Kconfig
@@ -627,6 +627,7 @@ config MACH_REALTEK_RTL
 	select IRQ_MIPS_CPU
 	select CEVT_R4K
 	select CSRC_R4K
+	select NO_EXCEPT_FILL
 	select SYS_HAS_CPU_MIPS32_R1
 	select SYS_HAS_CPU_MIPS32_R2
 	select SYS_SUPPORTS_32BIT_KERNEL
```

Can you already add removal of that second hunk from the 931x-hacks patch to this series? I consider cleaning up that sort of hack a very good argument for adding `NO_EXCEPT_FILL` sooner.

**Comment by oliv3r** [comment]
> Have you seen these similar upstream patches? https://lore.kernel.org/linux-mips/20200527063438.391949-4-jiaxun.yang@flygoat.com/ https://lore.kernel.org/linux-mips/1347806915-25132-2-git-send-email-hauke@hauke-m.de/

Yes I had, but didn't quite understand them :p
> 
> Since our kernel is now loaded at 0x80100000, I take the same arguments apply here. I've checked, and the (mainline) kernel actually sets the ebase address to a non-0x80000000 address, so it would probably even work with the old load address.

But that's the thing, it doesn't work at all, you get a no output at-all. This has cost me several days to figure out :)
> 
> Maybe you just didn't word it properly in your commit message, but that means the +0x400 entry address is used to compensate for the absence of NO_EXCEPT_FILL. Not that you can substitute one for the other.

I probably didn't, because I didn't fully understand it. I think the FILL is used to pad 0x400 to leave room for the exception vectors. Anyway, I tried all combinations, and the original, and the suggested combo is the only thing that works.
> 
> I plan to submit the following upstream:
lgtm!

> Can you already add removal of that second hunk from the 931x-hacks patch to this series? I consider cleaning up that sort of hack a very good argument for adding `NO_EXCEPT_FILL` sooner.

No (again, sorry :p) I'm not touching 931x, we have zero people to test things, so I'm not inclined to do anything here. YET!

Mind you, I was offered a 9311 (from conor, like you) and then we can actually test stuff. WIth that in hand, I intend to drop all of those things. So I'll bring in some 'fix rtl9311' commits at some point :) My (short term goal) is to push all patches upto https://gitlab.com/olliver/openwrt/openwrt/-/commit/c68457f4748e8613d2da267311ed2a433cb733ac which gets rid of all this fluff. But needs (testing) hardware!

**Comment by oliv3r** [comment]
@svanheule any technical thoughts on this one?

**Comment by svanheule** [comment]
Merged with commits:
4db8598e4296 realtek: Do not set KERNEL_ENTRY just to avoid NO_EXCEPT_FILL
1bf39d91d5d9 realtek: Refresh kernel config with no_except_fill

And for completeness:
d84dc5d4d7b2 realtek: rtl931x: drop CONFIG_NO_EXCEPT_FILL hack

**Pull request closed without merging**
