### PR TITLE
tools/libdeflate: update to v1.20

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
- https://github.com/ebiggers/libdeflate/blob/master/NEWS.md#version-120

### CODE REVIEW

**Comment by neheb** [comment]
lol no. git is used for a very specific reason. This is what actually unpacks gz archives.

**Comment by robimarko** [comment]
@PolynomialDivision Can you respin this now that we use tarballs for libdeflate as well

**Comment by robimarko** [comment]
@PolynomialDivision I can take over if you dont have time

**Comment by PolynomialDivision** [comment]
Please go for it. Thanks! :)

**Comment by robimarko** [comment]
Thanks, I will close this PR then and make a new one.

**Pull request closed without merging**
