### PR TITLE
kernel: add mv88e61xx switch port-mirroring support

### PR DESCRIPTION
**Pull request by dengqf6**
Compile & run tested on mvebu.

### CODE REVIEW

**Comment by dengqf6** [comment]
If anyone wants to test it out..
@davidc502 @kkudielka @anomeome @tapper82

**Comment by anomeome** [comment]
I had put this in my build a number of days back when I was trying to trouble shoot the _openssl_ PR, just never got around to playing with it until today.  Looks good in in my testing on a _mamba_. Given the title I assume this is not applicable to the _rango_ switch (88E6352)?

**Comment by dengqf6** [comment]
> Given the title I assume this is not applicable to the _rango_ switch (88E6352)?

I glanced through the Linksys GPL source and found this
```c
#define DEV_MIRROR_DEST    \
    ( DEV_88E6097_FAMILY | DEV_88E6165_FAMILY |     \
      DEV_88E6351_FAMILY | DEV_88E6352_FAMILY)
```
```c
/* device name - devName */
#define DEV_88E6051              0x0001    /* quarterdeck 6051      */
#define DEV_88E6052              0x0002    /* quarterdeck 6052      */
#define DEV_88E6021              0x0004    /* fullsail              */
#define DEV_88E6060              0x0008    /* Gondola               */
#define DEV_88E6063              0x0010    /* clippership 6063      */
#define DEV_FF_EG                0x0020    /* FireFox-EG            */
#define DEV_FF_HG                0x0040    /* FireFox-HG            */
#define DEV_FH_VPN               0x0080    /* FireHawk-VPN          */
#define DEV_88E6083              0x0100    /* Octane 6083           */
#define DEV_88E6181              0x0200    /* Sapphire 88E6181      */
#define DEV_88E6183              0x0400    /* Sapphire 88E6153,88E6183 */
#define DEV_88E6093                 0x0800   /* 88E6093                  */
#define DEV_88E6092                 0x1000   /* 88E6092                  */
#define DEV_88E6095              0x2000   /* 88E6095                  */
#define DEV_88E6182              0x4000   /* Jade 88E6152, 88E6182 */
#define DEV_88E6185              0x8000   /* Jade 88E6155, 88E6185 */
#define DEV_88E6108              0x10000   /* 88E6108 */
#define DEV_88E6061              0x20000   /* 88E6031, 88E6061 */
#define DEV_88E6065              0x40000   /* 88E6035, 88E6055, 88E6065 */
#define DEV_88E6096              0x80000   /* 88E6096, 88E6046 */
#define DEV_88E6097              0x100000   /* 88E6097, 88E6047 */
#define DEV_88E6161              0x200000   /* 88E6161 */
#define DEV_88E6165              0x400000   /* 88E6165 */
#define DEV_88E6351              0x800000   /* 88E6351 */
#define DEV_88E6175              0x1000000  /* 88E6175 */
#define DEV_88E6171              0x2000000  /* 88E6125 and 88E6171 */
#define DEV_88E6371              0x4000000  /* 88E6321, 88E6350 */
#define DEV_88E6172              0x8000000  /* 88E6172 */
#define DEV_88E6176              0x10000000 /* 88E6176 */
#define DEV_88E6240              0x20000000 /* 88E6240 */
#define DEV_88E6352              0x40000000 /* 88E6352 */

/* device name 1 - devName1. These name for extended device family */
#define DEV_88EC000                      0x000000001  /* Melody 88EC0XX  */
#define DEV_88E3020                      0x000000010  /* Spannaker 88E3020  */
#define DEV_88E6020                      0x000000020  /* Spannaker 88E6020  */
#define DEV_88E6070                      0x000000040  /* Spannaker 88E6070  */
#define DEV_88E6071                      0x000000080  /* Spannaker 88E6071  */
#define DEV_88E6220                      0x000000100  /* Spannaker 88E6220  */
#define DEV_88E6250                      0x000000200  /* Spannaker 88E6250  */

#define DEV_88E6125                      0x000000400  /* Pearl 88E6125  */
#define DEV_88E6320                      0x000000800  /* Pearl 88E6320  */
#define DEV_88E6115                      0x000001000  /* Pearl 88E6115  */
#define DEV_88E6310                      0x000002000  /* Pearl 88E6310  */

#define DEV_88E6097_FAMILY    ( DEV_88E6096 | DEV_88E6097 )
#define G1_DEV_88E6097_FAMILY     0
#define DEV_88E6165_FAMILY    ( DEV_88E6161 | DEV_88E6165 )
#define G1_DEV_88E6165_FAMILY     0

/* Amber */
#define DEV_88E6351_AVB_FAMILY    ( DEV_88E6351 | DEV_88E6371 )
#define G1_DEV_88E6351_AVB_FAMILY      0
#define DEV_88E6351_NO_AVB_FAMILY    (DEV_88E6171 | DEV_88E6175)
#define G1_DEV_88E6351_NO_AVB_FAMILY   0
#define DEV_88E6351_FAMILY    ( DEV_88E6351_AVB_FAMILY | DEV_88E6351_NO_AVB_FAMILY)
#define G1_DEV_88E6351_FAMILY      0

/* Agate */
#define DEV_88E6352_AVB_FAMILY    ( DEV_88E6352 | DEV_88E6240 )
#define G1_DEV_88E6352_AVB_FAMILY      0
#define DEV_88E6352_NO_AVB_FAMILY    (DEV_88E6172 | DEV_88E6176)
#define G1_DEV_88E6352_NO_AVB_FAMILY   0
#define DEV_88E6352_FAMILY    ( DEV_88E6352_AVB_FAMILY | DEV_88E6352_NO_AVB_FAMILY)
#define G1_DEV_88E6352_FAMILY      0
```

So 88E6352 is supported as well

**Comment by dengqf6** [comment]
@diizzyy

**Comment by diizzyy** [comment]
@dengqf6 
I don't have a way to test it right now, sorry :(

**Comment by dengqf6** [comment]
@kaloz Is it okay for you?

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
