### PR TITLE
kernel: bump 5.10 to 5.10.88

### PR DESCRIPTION
**Pull request by rsalvaterra**
Deleted (upstreamed):
mpc85xx/patches-5.10/002-powerpc-85xx-fix-oops-when-CONFIG_FSL_PMC-n.patch [1]

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.10.88&id=151ffac3ac277ad7c2a5f201b566b56d97ed3a99

Run-tested:
ramips/mt7621 (Redmi AC2100)

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by graysky2** [comment]
Patch matches the one I generated.
```
Build system: x86_64
Build-tested: bcm2711/RPi4B
Run-tested: bcm2711/RPi4B

```

**Comment by PerkelSimon** [comment]
working with ipq806x?

**Comment by graysky2** [comment]
@PerkelSimon - Have not tried, cannot flash the device now.

**Comment by rsalvaterra** [comment]
> Patch matches the one I generated.
> 
> ```
> Build system: x86_64
> Build-tested: bcm2711/RPi4B
> Run-tested: bcm2711/RPi4B
> ```

Great, thanks for testing, @graysky2. By the way, is your RPi stable now?

**Comment by graysky2** [comment]
@rsalvaterra - Nope, experienced the same thing under 5.10.87.  Hardware checks out stability/torture testing.  I have no explanation for it nor has anyone responded to my posts on the RPi forum nor OpenWRT forum nor that bug against the kernel itself.

**Comment by graysky2** [comment]
@PerkelSimon - works

**Comment by anomeome** [comment]
Build is not complaining but
patch package/kernel/mac80211/patches/subsys/305-mac80211-fix-regression-in-SSN-handling-of-addba-tx.patch
now
commit 15640e40e3bbb8714afadab4655e606944f69a9f ?

**Pull request closed without merging**
