### PR TITLE
siflower: gpio: use gpiochip_get_data

### PR DESCRIPTION
**Pull request by neheb**
No need to use container_of.

ping @robimarko @981213

### CODE REVIEW

**Comment by 981213** [comment]
Merged. Thanks!

**Comment by 981213** [comment]
Got a comment from the original author Qingfang, saying that he intentionally chose container_of because container_of is faster than gpiochip_get_data (one subtraction vs two pointer dereferencing).
Though I'm a bit lazy to revert this now. I'll submit the original version when upstreaming.

**Comment by neheb** [comment]
is it an appreciable difference?

**Comment by 981213** [comment]
> is it an appreciable difference?

I don't believe so. However, it's unnecessary to replace one approach with another, since both are used in various upstream GPIO drivers.

**Comment by neheb** [comment]
Then NULL should be passed to gpiochip_add_data

**Pull request merged**
