### PR TITLE
swiotlb: "fix info leak with DMA_FROM_DEVICE from 5.17 patch.

### PR DESCRIPTION
**Pull request by carrot93**
compared 5.15.77 and 5.19 to add this part of original patch.
And could fix(or improve) ath79 can't keep connection with lone time by WDS mode.
files:
./include/linux/dma-mapping.h
./kernel/dma/swiotlb.c

### CODE REVIEW

**Comment by carrot93** [comment]
> 

Because I compared the 5.15.77 source code and the 5.19 source code on same file, And just the first part of patch is missing, second part of patch had already done, and it(second) did an error for compiling firmware. So, just removed it. And test this patch on 5.15.76(current openwrt version.) with wndr4300v1 hardware, it works.

**Comment by hauke** [comment]
If this is a general problem in the Linux stable kernel please try to get this accepted in the normal Linux stable tree maintained by stable@vger.kernel.org .
See here for more details: https://www.kernel.org/doc/html/latest/core-api/kobject.html

@robimarko  pointed out that this was intentionally reverted: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.77&id=7007c894631cf43041dcfa0da7142bbaa7eb673c Why was this done?

**Comment by carrot93** [comment]
test it on 5.15.77-5.15.79 with or without this patch: Under this patch, the duration of keeping the connection is significantly extended, up to 10 hours without dropping WDS link.

**Comment by robimarko** [comment]
@carrot93 Has this even been reported upstream?

Cause, if WDS is broken it's weird that it wasn't fixed in over a year.
PR itself is formally broken as this should be just one patch reverting the partial reintroduction.
That said, I am not really for just reverting upstream patches as that is just covering it up.

**Comment by carrot93** [comment]
@robimarko, yep. the main branch of kernel considered that this bug fixed(DMA leak), but not in fact,. even in 5.19.  Under this patch. WDS attached new stable record: 
wds_mwan3
It maybe not perfect patch, but it works stably.

**Comment by robimarko** [comment]
It really should be reported upstream, just reverting it in OpenWrt is not the proper fix

**Comment by hauke** [comment]
Please send this to upstream Linux or at least involve them. We can not really judge what is the impact of this change.
If this patch or a different version of this gets accepted in upstream Linux please reopen this pull request with the recent code and a pointer to the discussion on the upstream Linux mailing lists.

**Pull request closed without merging**
