### PR TITLE
[22.03] Lantiq. Add support for sending vectoring error samples (cherry picked from master)

### PR DESCRIPTION
**Pull request by nicefile**
I'm not the author of this commits.
Based on [forum ](https://forum.openwrt.org/t/vectoring-on-lantiq-vrx200-vr9-missing-callback-for-sending-error-samples/104046/268) and user tests  this should be merged to next stable release .
lantiq xrx200 is one of two platform with  VDSL2 vectoring capable modem that runs OpenWrt  .This is last vital element that close gap in modem operation between using OEM firmware and using OpenWrt. We even have miniJumbo frames (MRU1508)  absent from OEM allowing real MTU1500 WAN
@xdarklight Please consider this pull

### CODE REVIEW

**Comment by moeller0** [comment]
I endorse this. On my vectoring/G.INP VDSL2 link this set of patches solved two very long running problems:
a) a slow SNR-marging degradation over time, probably caused by the existing driver in stable not sending error sample packets the vectoring unit needs to properly pre-distort signals for my line, so that after cross-talk the received signal looks as intended. Not sending error samples means that if cross-talk conditions change the signals start to degrade (from the decent starting point just after the handshake) and the vectoring unit can not adapt to changes for that link.
b) a more or less random looking but load dependent propensity to resync. which appears to be caused by a race in interrupt handling in the context of SMP.

Again, with these patches in place my  now has uptimes of multiple months while before getting low single digit days, and all that with a comparably sync to a proprietary broadcom modem (which are rumored to work better with broadcom linecards). Getting this into stable now seems like a great idea!

**Comment by d12r-dev** [comment]
Seconded, with emphasis. Ostensibly the primary, if not singular, reason to use a Lantiq device is to make use of its built-in modem. With Vectoring lines becoming the default, this patch will ensure Lantiq targets remain a viable target. It absolutely should go into 22.03 before release.

**Comment by xdarklight** [comment]
(just in case there's some confusion I'd like to make it clear: I am not an OpenWrt maintainer/developer, so whatever I write is my opinion)

At this point in time I would not merge this PR.
@janh sent three more patches to the mailing list, the first of which seems to be a fix for a build failure on the xway target after the vectoring changes:
1. [ltq-atm/ltq-ptm: avoid unnecessary build dependencies](https://patchwork.ozlabs.org/project/openwrt/patch/20220425194350.1221966-1-jan@3e8.eu/)
2. [ltq-vdsl/ltq-adsl: fix elapsed time calculation](https://patchwork.ozlabs.org/project/openwrt/patch/20220425195239.1228052-1-jan@3e8.eu/)
3. [ltq-vdsl-app: disconnect when service is stopped](https://patchwork.ozlabs.org/project/openwrt/patch/20220427174050.2607214-1-jan@3e8.eu/)

So before backporting the changes from this PR I encourage everyone to test Jan's patches and give your feedback to him.
Then consider which of these extra patches should be backported as well.

**Comment by janh** [comment]
> All of those are optional as doesn't affect core dsl functions like this crucial PR.

As already mentioned, the first of my proposed patches ("ltq-atm/ltq-ptm: avoid unnecessary build dependencies") fixes a build issue which happens only with commit "ltq-vdsl-mei: enable vectoring error sample callback" from the vectoring fixes.

This error also occurs on the build bots, see for example [this lantiq/xway package build log](https://buildbot.openwrt.org/master/images/#/builders/6/builds/563/steps/47/logs/stdio):

```
51930 ERROR: modpost: "mei_dsm_cb_func_hook" [/builder/shared-workdir/build/build_dir/target-mips_24kc_musl/linux-lantiq_xway/drv_mei_cpe-1.5.17.6/src/drv_mei_cpe.ko] undefined!
…
51947     ERROR: package/kernel/lantiq/ltq-vdsl-mei failed to build.
```

The build bots call `make` with `'IGNORE_ERRORS=n m'` though, which makes it ignore errors in any packages that don't end up in the final images. But on a local build using just `make` without any options, this error does cause the entire build to fail.

Thus, I think the vectoring fixes should not be considered for cherry-picking into 22.03 unless a fix for that build issue is also merged.

(The other two of my proposed patches are independent, though, and I would also consider them less important than the vectoring fixes, as they don't affect the core functionality of the modem.)

**Comment by Rupurudu** [comment]
Also a +1 from me. Lantiq is the only open source platform with VDSL2 support. This fixes the resync problem most of the users are having.  

@nicefile please also add [this patch](https://patchwork.ozlabs.org/project/openwrt/patch/20220425194350.1221966-1-jan@3e8.eu/) to the pull request, this fixes the older ADSL only xway branch.

**Comment by nicefile** [comment]
Added patch "ltq-atm/ltq-ptm: avoid unnecessary build dependencies"

**Comment by sebastian-de** [comment]
The commits are missing the _cherry picked from_ line - use `git cherry-pick -x <commit>`.
Otherwise +1 from me.

**Comment by nicefile** [comment]
ltq-ptm fix landed in master so I've replaced old commit with the one picked up from master.

**Comment by abajk** [comment]
@nicefile Could you remove the commit "Revert "ltq-atm/ltq-ptm: avoid unnecessary build dependencies"" from this PR?

**Comment by nicefile** [comment]
@abajk done

**Comment by karlpip** [comment]
I've cherry picked this pr into a 22.03 from about 5 days ago and it helped my Fritz Box 3370 tremendously.
I can confirm it fixed the slowly dropping SNR and fixed some disconnects we got around evening everyday which i assume were connected to workload.

Would be very cool to see this in the next release candidate for 22.03!

Also thanks for this work, gamechanger for my 3370 all in one setup :)

Additional info about my internet connection:
1&1 Germany 100k DSL with DS-Lite dual stack.

**Comment by dcoder42** [comment]
Been using this patch with a self compiled 22.03 for a FritzBox 7362 SL for more almost two weeks now and the line is still up and running. Awesome work. Would love to see that in the official 22.03 release as well.

**Comment by abajk** [comment]
@moeller0 @karlpip @dcoder42 and anyone interested in this PR
Can you provide a Tested-by line?
Maybe with this kind of feedback this PR will be accepted faster :)

**Comment by hauke** [comment]
Thank you for the patches, I applied them to openwrt-22.03 in e56836dfc1353c49d43323b75d68ebc3456c6cff, 642d6c0c6d69dba27d841f6e3e06f866969b0609, d0397abd9d7ef5295d34c02b5bdecfe317a1e1fd, 290c13b7d70b0b396509bf20787ab75ccb057cb7, ea0744fbc699e030b2917f5fa2493068cab2b60f, 8f4b5fdd5f1a2a85f3b16da69a03edf1c3470369 and 9c0f94e9551dd06455e93ac5e41b61b5cd1d2459.

**Pull request closed without merging**
