### PR TITLE
ath25: drop target

### PR DESCRIPTION
**Pull request by robimarko**
ath25 has been on life support for the last couple of releases, eventually leading to marking it as source-only in 2023.

It has been basically only touched to do a kernel bump so that we can make the new OpenWrt release which was a challenge due to small RAM amount.

However, with the attempt of kernel 6.1 update it turns out that kernel cannot even finish booting due to RAM constraints, so its time to let this target go.

### CODE REVIEW

**Review by Leo-PL — APPROVED** [review]

**Review by ynezz — APPROVED** [review]
I agree, thanks!

**Comment by oliv3r** [comment]
What's still on ath25 (I don't even see it mentioned here https://downloads.openwrt.org/releases/23.05.2/targets/) and why is there a shortage of memory, is it not an external chip?

For the insiders it's probably logical and clear, and I would agree that dropping it probably makes sense if it can't even boot newer kernels anyway ...

**Comment by oliv3r** [comment]
> It has been source-only in 23.05, hence it's not mentioned. Memory is external chip, but is soldered onto the boards. Devices upgraded by hand can be considered "one-off" and it makes no sense to support this target just for them. If the user is able to mod the device, they're probably capable of building modified image for it, too.

In short, 'all devices ever supported by openwrt/in the openwrt database lack the memory' :)

**Review by PolynomialDivision — APPROVED** [review]

**Comment by robimarko** [comment]
Pushed to openwrt/targets for archival:
https://github.com/openwrt/targets/commit/5d2306e28782b5da881b0fcdb9d906a7eed6e635

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
