### PR TITLE
imx6: Add support for Toradex Apalis family of computer on modules

### PR DESCRIPTION
**Pull request by ynezz**
This PR adds support for the following [computer on modules (CoM) from Toradex](https://www.toradex.com/computer-on-modules/apalis-arm-family/nxp-freescale-imx-6):

```
 Apalis iMX6 Quad 2GB IT - i.MX 6Quad 800MHz, 2GB DDR3, 4GB eMMC, -40° to +85° C
 Apalis iMX6 Quad 1GB    - i.MX 6Quad 1GHz,   1GB DDR3, 4GB eMMC,   0° to +70° C
 Apalis iMX6 Dual 1GB IT - i.MX 6Dual 800MHz, 1GB DDR3, 4GB eMMC, -40° to +85° C
 Apalis iMX6 Dual 512MB  - i.MX 6Dual 1GHz, 512MB DDR3, 4GB eMMC,   0° to +70° C
```

I've developed and tested it on Quad 2GB IT v1.1A and Dual 512MB v1.1A CoMs,
using [Ixora carrier](https://www.toradex.com/products/carrier-board/ixora-carrier-board) board v1.0A, but it should hopefuly work on [Eval
board](https://www.toradex.com/products/carrier-board/apalis-evaluation-board) as well just by issuing `setenv fdt_file imx6q-apalis-eval.dtb; saveenv; reset`
in U-Boot.

FYI @agners @nbd168 @Gateworks @xback @lperkov @v-vid

### CODE REVIEW

**Comment by v-vid** [comment]
Hi @ynezz,

I tested your commits on the current master branch but I'm getting one issue during the build:

```
echo '{  "supported_devices":["apalis,ixora","apalis,eval"], "version": { "dist": "OpenWrt", "version": "SNAPSHOT", "revision": "r8629+4-f98fde2db4", "board": "imx6" } }' | fwtool -I - /opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin
[ ! -s "/opt/devel/openwrt/key-build" -o ! -s "/opt/devel/openwrt/key-build.ucert" -o ! -s "/opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin" ] || { cp "/opt/devel/openwrt/key-build.ucert" "/opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin.ucert" ; usign -S -m "/opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin" -s "/opt/devel/openwrt/key-build" -x "/opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin.sig" ; ucert -A -c "/opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin.ucert" -x "/opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin.sig" ; fwtool -S "/opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin.ucert" "/opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin" ; }
cp /opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-squashfs.sysupgrade.bin /opt/devel/openwrt/bin/targets/imx6/generic/openwrt-imx6-apalis-squashfs.sysupgrade.bin
dd if=/opt/devel/openwrt/staging_dir/target-arm_cortex-a9+neon_musl_eabi/image/apalis_imx6-u-boot-with-spl.imx >> /opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-u-boot-with-spl.imx
dd: failed to open '/opt/devel/openwrt/staging_dir/target-arm_cortex-a9+neon_musl_eabi/image/apalis_imx6-u-boot-with-spl.imx': No such file or directory
make[5]: *** [Makefile:229: /opt/devel/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/tmp/openwrt-imx6-apalis-u-boot-with-spl.imx] Error 1
make[5]: Leaving directory '/opt/devel/openwrt/target/linux/imx6/image'
make[4]: *** [Makefile:25: install] Error 2
make[4]: Leaving directory '/opt/devel/openwrt/target/linux/imx6'
make[3]: *** [Makefile:13: install] Error 2
make[3]: Leaving directory '/opt/devel/openwrt/target/linux'
time: target/linux/install#23.74#6.19#27.83
make[2]: *** [target/Makefile:25: target/linux/install] Error 2
make[2]: Leaving directory '/opt/devel/openwrt'
make[1]: *** [target/Makefile:19: /opt/devel/openwrt/staging_dir/target-arm_cortex-a9+neon_musl_eabi/stamp/.target_install] Error 2
make[1]: Leaving directory '/opt/devel/openwrt'
make: *** [/opt/devel/openwrt/include/toplevel.mk:218: world] Error 
```

The problem seems to be that your searching for the wrong binary in the wrong location. I could only find one spl.imx binary which is called **openwrt-imx6-apalis-u-boot-with-spl.imx** and it's located in the kernel temp directory instead of the staging dir, so I would suggest the following change to the _imx6/image/Makefile_:

```
-  UBOOT_PATH := $$(STAGING_DIR_IMAGE)/$$(UBOOT)-u-boot-with-spl.imx
+  UBOOT_PATH := $$(KDIR_TMP)/$$(IMAGE_PREFIX)-u-boot-with-spl.imx
```
Everything else looks good.

Regards,
Vladimir

**Comment by ynezz** [comment]
@v-vid Hi, thanks a lot for testing! That error is quite strange, I just did

```
rm -fr build_dir/target-arm_cortex-a9+neon_musl_eabi/u-boot*
rm -fr staging_dir/target-arm_cortex-a9+neon_musl_eabi/image
```

and it still builds fine here, I've `staging_dir/target-arm_cortex-a9+neon_musl_eabi/image/apalis_imx6-u-boot-with-spl.imx` produced here.

If you look into `package/boot/uboot-imx6/Makefile` then you can find following:

```
define Build/InstallDev
        $(INSTALL_DIR) $(STAGING_DIR_IMAGE)
        $(foreach img,$(UBOOT_IMAGE), \
                $(CP) $(PKG_BUILD_DIR)/$(img) $(STAGING_DIR_IMAGE)/$(BUILD_VARIANT)-$(img); \
        )
endef
```

So `UBOOT_PATH := $$(STAGING_DIR_IMAGE)/$$(UBOOT)-u-boot-with-spl.imx` should be OK.

Could you please try to build directly from my branch?

```
git remote add github-ynezz https://github.com/ynezz/openwrt
git fetch github-ynezz
git checkout -b imx6-apalis-testing github-ynezz/upstream/imx6-apalis
echo -e 'CONFIG_TARGET_imx6=y\nCONFIG_TARGET_imx6_DEVICE_apalis=y\nCONFIG_PACKAGE_u-boot-apalis_imx6=y' > .config
make defconfig world -j$(nproc)
```

**Comment by v-vid** [comment]
Hi @ynezz, sorry, looks like I did overcomplicate this a bit.

You're right, I can build the firmware fine by following your instructions. However, with the "echo" line above you are selecting both target and u-boot separately, which is something I've overlooked last time. 
If the user only selects target, (clean) build will fail as described above.

I first thought that _Build/imx6-sdcard_ is causing this, but your not calling it from the Device section so the problem might be in _[append-uboot](https://github.com/openwrt/openwrt/blob/master/include/image-commands.mk#L212)_ which is called by the artifacts.

Adding _u-boot-apalis_imx6_ under the DEVICE_PACKAGES will solve the issue.

**Comment by ynezz** [comment]
I'm going to merge this myself, but I'll send updated patchset to the mailing list first for review.

**Pull request closed without merging**
