### PR TITLE
ipq8064: Add support Linksys e8350

### PR DESCRIPTION
**Pull request by SergeyFilippov**
- Add new "addfwhdr" tool to firmware tools. 
  Needed to add support of sysupgrade from vendor firmware.
- add device dts and respective led/network/paltform
- add new dtb to boot patch

### CODE REVIEW

**Comment by musashino205** [comment]
Please don't use the branches of releases for adding new devices.

https://openwrt.org/submitting-patches#patch_backports

> 1. Changes needs to be first applied into the main branch

**Comment by SergeyFilippov** [comment]
> Please don't use the release branches for adding new devices.
> 
> https://openwrt.org/submitting-patches#patch_backports
> 
> > 1. Changes needs to be first applied into the main branch
> 

Got it, thanks. 
I guess then until (or if) I will find a way to make it work in main, there is no way to get device support in older releases.

> And changes for firmware-utils need to be sent to its repository instead of adding a patch into the main repository of OpenWrt.
> 
> https://github.com/openwrt/firmware-utils
> 

Sure, it's just since 22.03 uses specific git hash of firmware-utils, there is no other way I was able to make it work. 

> In addition, there are several formal issues, please read the following guideline and fix them.
> 
> https://openwrt.org/submitting-patches#submission_guidelines

Oh yes, this is not the first PR attempt I'm trying to make for this changes, following those guidelines seems to be more complicated that adding device support itself 😅.

Then I'm going to update devices page in OpenWrt inbox ([e8350](https://openwrt.org/inbox/toh/linksys/linksys_ea8350_1)) with my locally compiled build for those who may need it before official support is there.

One question before closing this PR:
The issue is that I was not able to make it work with 23.05 or main (Kernel 5.15+). All Ethernet ports are dead and I'm getting 
```
kern.err kernel: [   22.591132] ipq806x-gmac-dwmac 37200000.ethernet: Failed to reset the dma
kern.err kernel: [   22.591175] ipq806x-gmac-dwmac 37200000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
kern.err kernel: [   22.596912] ipq806x-gmac-dwmac 37200000.ethernet eth0: __stmmac_open: Hw setup failed
```

Maybe somebody aware of this kind of issues with QCA8337?

**Comment by pkgadd** [comment]
In this particular case, ipq806x has migrated from swconfig to DSA between 23.05.x and main, which changes a lot for ipq806x based devices (the switch initialization in the DTS needs to be difference, likewise the setup code in will be different; this hard cut pretty much precludes backporting to 23.05.x anyways, so concentrate on main only).

**Comment by SergeyFilippov** [comment]
> In this particular case, ipq806x has migrated from swconfig to DSA between 23.05.x and main, which changes a lot for ipq806x based devices (the switch initialization in the DTS needs to be difference, likewise the setup code in will be different; this hard cut pretty much precludes backporting to 23.05.x anyways, so concentrate on main only).

Thank you, will look in this direction.

**Pull request closed without merging**
