### PR TITLE
make verbosity affect uClibc++ build

### PR DESCRIPTION
**Pull request by wt**
Signed-off-by: Wren Turkal <wt@penguintechs.org>

### CODE REVIEW

**Comment by wt** [comment]
Before this change, setting the verbosity to something like V=sc would cause uclibc++ build to print errors to the screen.

**Review by neheb — APPROVED** [review]

**Comment by adrianschmutzler** [comment]
Formal issues:
- The commit title should be prefixed by "uclibc++: "
- The/an explanation for the reasons of this change should be given in the commit message.

**Comment by wt** [comment]
@adrianschmutzler, I altered the commit message as you asked. How do you feel about it now?

**Comment by adrianschmutzler** [comment]
Thanks, please also make the "Make" lower case and remove the full stop "." at the end.

**Comment by wt** [comment]
Sure.

**Comment by wt** [comment]
Done.

**Comment by neheb** [comment]
Looks good.

**Comment by wt** [comment]
Hey there. Is this merge-able at this point?

**Comment by wt** [comment]
I guess that means it's just a waiting game at this point.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
