### PR TITLE
iptables: update to 1.8.8

### PR DESCRIPTION
**Pull request by PolynomialDivision**
see commit

### CODE REVIEW

**Comment by jow-** [comment]
> Somehow firewall3 is broken.

Without having looked deeper into it, my first hunch would be to revert https://git.netfilter.org/iptables/commit/?id=6c689b639cf8e2aeced8685eca2915892d76ad86 - the stubbed `init_extensions()` calls likely prevent our shared libiptext from working correctly.

**Comment by PolynomialDivision** [comment]
Fixed with revert package/network/utils/iptables/patches/104-reverts-implify-static-build-extension-loading.patch
```
root@OpenWrt:~# /etc/init.d/firewall restart
Warning: Unable to locate ipset utility, disabling ipset support
Warning: Section @defaults[0] requires unavailable target extension FLOWOFFLOAD, disabling
Warning: Section @defaults[0] requires unavailable target extension FLOWOFFLOAD, disabling
 * Flushing IPv4 filter table
 * Flushing IPv4 nat table
 * Flushing IPv4 mangle table
 * Flushing IPv4 raw table
 * Flushing IPv6 filter table
 * Flushing IPv6 mangle table
 * Flushing IPv6 raw table
 * Flushing conntrack table ...
 * Populating IPv4 filter table
   * Rule 'Allow-DHCP-Renew'
   * Rule 'Allow-Ping'
   * Rule 'Allow-IGMP'
   * Rule 'Allow-IPSec-ESP'
   * Rule 'Allow-ISAKMP'
   * Forward 'lan' -> 'wan'
   * Zone 'lan'
   * Zone 'wan'
 * Populating IPv4 nat table
   * Zone 'lan'
   * Zone 'wan'
 * Populating IPv4 mangle table
   * Zone 'lan'
   * Zone 'wan'
 * Populating IPv4 raw table
   * Zone 'lan'
     - Using automatic conntrack helper attachment
   * Zone 'wan'
 * Populating IPv6 filter table
   * Rule 'Allow-DHCPv6'
   * Rule 'Allow-MLD'
   * Rule 'Allow-ICMPv6-Input'
   * Rule 'Allow-ICMPv6-Forward'
   * Rule 'Allow-IPSec-ESP'
   * Rule 'Allow-ISAKMP'
   * Forward 'lan' -> 'wan'
   * Zone 'lan'
   * Zone 'wan'
 * Populating IPv6 mangle table
   * Zone 'lan'
   * Zone 'wan'
 * Populating IPv6 raw table
   * Zone 'lan'
     - Using automatic conntrack helper attachment
   * Zone 'wan'
 * Set tcp_ecn to off
 * Set tcp_syncookies to on
 * Set tcp_window_scaling to on
 * Running script '/etc/firewall.user'
```

**Comment by PolynomialDivision** [comment]
> Well, it looks like firewall3 does a static build and calls
> init_extensions*(). It includes xtables.h without defining ALL_INCLUSIVE
> or NO_SHARED_LIBS, so ends up with the empty function definitions.
> Given that these functions are for internal use only, it is only harmful
> to declare them in the "official" libxtables header.
> Unless someone objects, I'll prepare a patch moving the declarations
> into xshared.h.
> https://marc.info/?l=netfilter-devel&m=165410366123188&w=2

Waiting for the patch... :)

**Comment by PolynomialDivision** [comment]
Patch is now also in the git:
https://git.netfilter.org/iptables/commit/?id=ef108943f69a6e20533d58823740d3f0534ea8ec

**Comment by PolynomialDivision** [comment]
ping @jow-

**Comment by PolynomialDivision** [comment]
@hauke

**Comment by PolynomialDivision** [comment]
rebased on master

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in 436fad7a3edaf071b45d8201e839acd914be4d10.

**Comment by champtar** [comment]
Is it planned to backport this to 22.03 before release ?

**Comment by PolynomialDivision** [comment]
> Is it planned to backport this to 22.03 before release ?

Are you asking @hauke or me? I can also backport it at a later point.

**Pull request closed without merging**
