### PR TITLE
ar71xx: fix tl-wdr3320-v2 upgrade

### PR DESCRIPTION
**Pull request by nanpuyue**

### CODE REVIEW

**Comment by ynezz** [comment]
The PR has formal issues, please check [Submitting patches](https://openwrt.org/submitting-patches#submitting_patches) for details once more, thanks!

**Comment by ynezz** [comment]
Ping.

**Comment by nanpuyue** [comment]
Pong.

**Comment by ynezz** [comment]
@nanpuyue good, now please add the commit description:

```
 commit description

    must have less than 75 characters per line
    it will be committed to the source changelog, so it should explain to a competent reader why you made this commit.
    Include symptoms of the failure you are fixing (log messages, error messages, etc.), it will be useful for
    people searching the commit logs looking for a fix for their issue.
    If a patch fixes a compile failure, include only the most relevant part of the failure log
```

**Comment by nanpuyue** [comment]
Done.

**Comment by adrianschmutzler** [comment]
Thanks. Merged.

**Pull request closed without merging**
