### PR TITLE
mediatek: move PHY patches to generic

### PR DESCRIPTION
**Pull request by neheb**
ping @dangowrt 

Interestingly enough I just get

```
[  145.936825] leds mt7530-0:00:white:wan: Setting an LED's brightness failed (-524)
[  163.821819] leds mt7530-0:00:white:wan: Setting an LED's brightness failed (-524)
```

When trying to set the LED.

### CODE REVIEW

**Comment by neheb** [comment]
@arinc9 since you maintain mt7530, any insight here?

**Comment by arinc9** [comment]
I don't maintain this OpenWrt-specific, out-of-tree, LED support. I'm not interested in code that is not on mainline Linux.

**Comment by dangowrt** [comment]
@arinc9 If you prefer to deal with it upstream, please take a of look at
https://patchwork.kernel.org/project/netdevbpf/list/?series=867087&state=*

LED support infrastructure is part of vanilla Linux as well and by no means only part of OpenWrt.
Just the series of @onlyfly34 enabling it also for the `mediatek-ge` driver (among other things) was picked to OpenWrt to give it some testing and more audience -- and that resulted in problems being discovered, which was the intention of including the pending series.

**Comment by neheb** [comment]
Oh that's interesting. I didn't know PHY muxing interferes. Since this router has only one LED for the WAN and no LAN ports, I guess keeping GPIO makes more sense. I will test that though.

**Comment by neheb** [comment]
I will say I would have though LED support would have been implemented in the DSA driver. That's how it is wit2h qca8k and the pending patch for Marvell switches.

**Comment by dangowrt** [comment]
@neheb The series only adds support for LED handling for the built-in PHYs of MT7531. On MT7530 (and hence also MT7621) this is not supported in this way as LEDs are driven by the switch logic rather than by the PHYs.

**Comment by arinc9** [comment]
> @arinc9 If you prefer to deal with it upstream, please take a of look at
> https://patchwork.kernel.org/project/netdevbpf/list/?series=867087&state=*

I don't maintain the PHY driver and I don't mean to do it anytime soon, if at all. Huang seems to be working on a newer version to address the requested changes. I'll let them have at it as they're surely also getting paid to do it.

> 
> LED support infrastructure is part of vanilla Linux as well and by no means only part of OpenWrt.
> Just the series of @onlyfly34 enabling it also for the `mediatek-ge` driver (among other things) was picked to OpenWrt to give it some testing and more audience -- and that resulted in problems being discovered, which was the intention of including the pending series.

Good effort. I like this approach. This too helped me out in fixing a bug in my code back in the day.

**Comment by neheb** [comment]
@dangowrt unfortunate. Guess I'll close this PR.

btw, given this patchset, I assume 766-net-phy-mediatek-ge-add-LED-configuration-interface.patch should be removed and mediatek,led-config be ported over.

**Comment by dangowrt** [comment]
> 766-net-phy-mediatek-ge-add-LED-configuration-interface.patch should be removed

The patch is useful for MT7531 switch ICs which are used on newer SoCs with 2500Base-X SerDes, but both MT7530 and MT7531 use `mediatek-ge.c` PHY driver.

**Comment by dangowrt** [comment]
I think this PR can still be useful as also Rockchip based BananaPi R2 Pro uses MT7531. Just not for ramips which uses MT7530, either as dedicated IC or as multi-chip module inside the MT7621 package.

**Comment by neheb** [comment]
Rebased against master.

**Comment by neheb** [comment]
Oh I need to recreate the PR.

**Pull request closed without merging**
