### PR TITLE
kernel: bump 5.4 to 5.4.105

### PR DESCRIPTION
**Pull request by graysky2**
Ran update_kernel.sh in a fresh clone without any existing toolchains.

Removed upstreamed generic-backports:
```
  830-v5.12-0001-net-usb-qmi_wwan-support-ZTE-P685M-modem.patch
```

Build system: x86_64
Build-tested: ipq806x/R7800
Run-tested: ipq806x/R7800

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by timocapa** [comment]
Apologize for the late response

Build system: x86_64
Build-tested: ramips/mt7621/{Xiaomi R3G, Redmi 210}, Lantiq/XWAY/Fritz!Box 7320/7330
Run-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330

All ok.

**Comment by graysky2** [comment]
Just updated to 5.4.104 in the same PR.

@adschm - You advised this in the [past](https://github.com/openwrt/openwrt/pull/3767#issuecomment-761045984) ... how to do want me to handle it beyond just a 2nd commit?

**Comment by timocapa** [comment]
Same as yesterday, all seems ok.

Build system: x86_64
Build-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330
Run-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330

**Review by curtdept — APPROVED** [review]
Build and Run Tested on x86/64

```Signed-off-by: Curtis Deptuck curtdept@me.com```

Might be worth bumping the subject line of this PR to 104

**Comment by curtdept** [comment]
Rebuild and will re-review now

**Comment by timocapa** [comment]
And once again,

```
Build system: x86_64
Build-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330
Run-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330
```

Looks fine

**Review by curtdept — APPROVED** [review]
Build and Run Tested on x86/64

```Signed-off-by: Curtis Deptuck curtdept@me.com```

@adschm this is GTG I think :) Has some great AMD IOMMU fixes in it.

**Comment by KaneGreen** [comment]
tested on 0183ee2 looks fine
Build system: x86_64
Build-tested: rockchip/armv8/Nanopi R2S
Run-tested: rockchip/armv8/Nanopi R2S

**Comment by adschm** [comment]
Thanks, I will merge this later today (in a sqashed version).

I think the current procedure works well, you stacking these up, and me finally squashing them ...

**Pull request closed without merging**
