### PR TITLE
kirkwood: add 6.6 kernel as testing version

### PR DESCRIPTION
**Pull request by CHKDSK88**
~~This PR should be merged with or after  #14803.~~

Run tested on Linksys EA4500

Known issues:
  - None so far

### CODE REVIEW

**Comment by namiltd** [comment]
Patch file: 834-ledtrig-libata.patch, line 61, to:
```
+	led_trigger_blink_oneshot(ap->ledtrig, led_delay, led_delay, 0);

**Comment by CHKDSK88** [comment]
> Patch file: target\linux\generic\pending-6.6\834-ledtrig-libata.patch, line 61, to:
> 
> ```
> +	led_trigger_blink_oneshot(ap->ledtrig, led_delay, led_delay, 0);
> ```

Thanks. I created new PR with fix: #14919

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by sanderpqr** [comment]
@CHKDSK88 Perhaps it's a good time to switch 6.6 to default, and get a bit more exposure for testing?

**Comment by CHKDSK88** [comment]
@sanderpqr It could be.  I prepared PR with it.

**Pull request merged**
