### PR TITLE
kernel: bump 5.4 to 5.4.108

### PR DESCRIPTION
**Pull request by graysky2**
All modifications made by by update_kernel.sh.
```
Build system: x86_64
Build-tested: ipq806x/R7800
```

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by timocapa** [comment]
```
Build system: x86_64
Build-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330
Run-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330
``` 
Looks good

**Comment by rockdrilla** [comment]
Build system: x86_64
Build-tested: ath79/generic (TP-Link Archer C7 v2)
Run-tested: ath79/generic (TP-Link Archer C7 v2)

LGTM.

**Comment by adschm** [comment]
I picked the 5.4.106 patch and will merge it later tonight. Note that you or your editor again changed unrelated whitespaces in the manually adjusted files.

**Comment by timocapa** [comment]
5.4.107

```
Build system: x86_64
Build-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330
Run-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330
```
Looks good but you should probably rerun the script to update it. I did.

**Comment by graysky2** [comment]
Fixed conflicts introduced in master.

**Comment by graysky2** [comment]
Updated to 5.4.108 but only build tested by me.  Cannot test for several days.

**Comment by timocapa** [comment]
As always

```
Build system: x86_64
Build-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330
Run-tested: ramips/mt7621/{Xiaomi R3G, Redmi 2100}, Lantiq/XWAY/Fritz!Box 7320/7330
```

LGTM

**Comment by adschm** [comment]
Thanks, will be merged later today.

**Pull request closed without merging**
