### PR TITLE
lantiq: ase: disable adm6996 and swconfig 

### PR DESCRIPTION
**Pull request by abajk**
The ase subtarget supports two devices. ALLNET ALL0333CJ has one 
Ethernet port and uses only the built-in MAC and PHY. The second
device is the Netgear DGN1000, which uses an AR8216 switch.

The driver for the adm6996 switch was probably accidentally
enabled instead of the ar8216 in commit that restores ase support
9b321bc60de3 ("lantiq: add Amazon-SE subtarget").

Before removing the ase subtarget, only ar8216 was enabled
c82183639512 ("lantiq: remove unmaintained code").

Reduce uncompressed kernel size by 15.6 kB.

Signed-off-by: Aleksander Jan Bajkowski <olek2@wp.pl>

### CODE REVIEW

**Comment by hauke** [comment]
The AR8216 driver is not activated in the ase kernel or for the  dgn1000b  board.

Do you have one of these boards? Are they still working?

**Comment by abajk** [comment]
I only have ALL0333CJ, but I accidentally erased the NAND flash on it. I only remember that 18.06 worked, later versions I have not tested.

**Comment by abajk** [comment]
Maybe the dgn1000b only works if the switch is programmed by u-boot. Should I mark this device broken?

**Comment by hauke** [comment]
Both of them are not build by default any more.

I do not think the ase target has many users if any at all. This patch is probably fine, I think it doe snot make sense to invest much time into ase.

**Comment by abajk** [comment]
I have similar feelings about ase. On the other hand it would be good to get rid of swconfig drivers where they are not needed. Only 19 of the 90 subtargets still have swconfig enabled.

**Pull request merged**
