### PR TITLE
[RFC] kirkwood: add initial support for I-O DATA HDL-A/HDL2-A NAS

### PR DESCRIPTION
**Pull request by musashino205**
This patch series adds initial support for I-O DATA HDL-A/HDL2-A series NAS.
On these series, kernel and rootfs need to be installed to SATA storage, so there are some specific changes.

And also, this support depends on the additional patch of fstools

~http://lists.openwrt.org/pipermail/openwrt-devel/2022-March/038215.html~ (rejected)

~http://lists.openwrt.org/pipermail/openwrt-devel/2022-March/038219.html~ (replaced)

http://lists.openwrt.org/pipermail/openwrt-devel/2022-July/038982.html (1/2, 2/2)

### CODE REVIEW

**Comment by musashino205** [comment]
UPDATE:

- fix commit message in the last commit
  - HDL-A has no HDD LED

**Comment by musashino205** [comment]
UPDATE:

- drop unnecessary fstools option from bootargs-append

**Comment by musashino205** [comment]
I'll change the default network configuration. And, an additional change is needed for overridden ```root=``` parameter in bootargs for fstools...

**Comment by musashino205** [comment]
UPDATE:

- use DHCP client on eth0 by default

**Comment by Leo-PL** [comment]
Looks very promising! As discussed on forum, we can join our efforts and create new 'disk' subtarget for devices with limited flash like this one or Synology DS211j.

**Pull request closed without merging**
