### PR TITLE
ar71xx: add support for the TP-Link TL-WR941N/ND v7 router

### PR DESCRIPTION
**Pull request by imbrolla**
This commit adds support for TP-Link TL-WR941N/ND v7 router

CPU: Qualcomm Atheros QCA9558 720MHz
RAM: 64MB
FLASH: 4MB
PORTS: 4 Port 10/100 Switch, 1 Port 10/100 Wan
Switch: 5x 10/100 Mbps Ethernet (AR8236)
WiFi: SoC QCA9558 integrated 3T3R 2.4 GHz
LED: Power, LAN , WAN, WiFi, QSS
BTN: WPS, Reset

Thanks to the machine code written by hackpascal.

inked88_1467840_609232f259309a8_li

Similar configuration models：Netgear_WNR2500 — N450 Wireless Router
https://wikidevi.com/wiki/Netgear_WNR2500
20181021045856_li

### CODE REVIEW

**Comment by 981213** [comment]
BTW "commit message" isn't "GitHub PR description"

**Comment by imbrolla** [comment]
> 与[＃1444](https://github.com/openwrt/openwrt/pull/1444)完全相同的问题，在机器代码中重置开关有一个肮脏的黑客...

I think you're a really narrow-minded person. 
My purpose was to make it available to those in need.

**Comment by imbrolla** [comment]
> Exactly the same problems as #1444 , there is a dirty hack to reset switch in machine code...

I think you're a really narrow-minded person.
My purpose was to make it available to those in need.

**Comment by hackpascal** [comment]
Yeah, another person used my work again without mentioned me.
A dirty hack I wrote almost 3 years ago (https://github.com/hackpascal/openwrt-old/commit/b06de1007c3c5e5ece5516854df32dac5b33bfe3) that I never planned to submit to OpenWrt mainline.

**Comment by 981213** [comment]
For those who are interested in that dirty hack:
The factory U-boot of this device (In fact, on all QCA device with an FE switch) will set MDIO_MASTER_EN bit to 1, which enabled the on-switch mdio master but also disallow the direct access to switch PHYs, resulting in the inability to read PHY ID from GMAC MDIO on SoC.
ar8216 on OpenWrt is introduced long time ago when there is no mdio device framework in kernel. It's probed using the PHY framework and current probing method requires an available PHY ID, which in this case isn't possible before setting MDIO_MASTER_EN to 0.
A proper way of solving this problem is writing a new probing procedure using the mdio-device framework currently available in kernel, which register a device directly without needing the access to an PHY ID and we can do a switch reset after that in the switch driver.
As for the dirty way here, the machine initialization code alter a switch soft reset by directly accessing mdio registers of GMAC0 and send mdio instructions before the probing of mdio driver, doing what shouldn't be done by machine initialization code and introducing a piece of messy and duplicated code into the target.

As for the author: PLEASE don't copy code from others without acknowledging them and without even knowing what their code actually did.

**Comment by imbrolla** [comment]
> Yeah, another person used my work again without mentioned me.
> A dirty hack I wrote almost 3 years ago ([hackpascal/openwrt-old@b06de10](https://github.com/hackpascal/openwrt-old/commit/b06de1007c3c5e5ece5516854df32dac5b33bfe3)) that I never planned to submit to OpenWrt mainline.

First of all, there are some details that have been left untreated. I have to say I'm sorry about that. You are a good man. Thank you for your contribution. Yes, you did this machine code, but there was a compilation error in kernel 4.14, so I wanted to let you know and change it to make it work. I'm really sorry if I offended you about that.

**Comment by imbrolla** [comment]
First of all, there are some details that have been left untreated. I have to say I'm sorry about that. You are a good man. Thank you for your contribution. Sure, you did this machine code, but there was a compile error in kernel 4.14, so I wanted to tell someone who needed it and changed it to make it work. I'm really sorry if I offended you about that.


> Yeah, another person used my work again without mentioned me.
> A dirty hack I wrote almost 3 years ago ([hackpascal/openwrt-old@b06de10](https://github.com/hackpascal/openwrt-old/commit/b06de1007c3c5e5ece5516854df32dac5b33bfe3)) that I never planned to submit to OpenWrt mainline.

First of all, there are some details that have been left untreated. I have to say I'm sorry about that. You are a good man. Thank you for your contribution. Sure, you did this machine code, but there was a compile error in kernel 4.14, so I wanted to tell someone who needed it and changed it to make it work. I'm really sorry if I offended you about that.

**Comment by imbrolla** [comment]
> Yeah, another person used my work again without mentioned me.
> A dirty hack I wrote almost 3 years ago ([hackpascal/openwrt-old@b06de10](https://github.com/hackpascal/openwrt-old/commit/b06de1007c3c5e5ece5516854df32dac5b33bfe3)) that I never planned to submit to OpenWrt mainline.

First of all, there are some details that have been left untreated. I have to say I'm sorry about that. You are a good man. Thank you for your contribution. Sure, you did this machine code, but there was a compile error in kernel 4.14, so I wanted to tell someone who needed it and changed it to make it work. I'm really sorry if I offended you about that.

**Comment by imbrolla** [comment]
> For those who are interested in that dirty hack:
> The factory U-boot of this device (In fact, on all QCA device with an FE switch) will set MDIO_MASTER_EN bit to 1, which enabled the on-switch mdio master but also disallow the direct access to switch PHYs, resulting in the inability to read PHY ID from GMAC MDIO on SoC.
> ar8216 on OpenWrt is introduced long time ago when there is no mdio device framework in kernel. It's probed using the PHY framework and current probing method requires an available PHY ID, which in this case isn't possible before setting MDIO_MASTER_EN to 0.
> A proper way of solving this problem is writing a new probing procedure using the mdio-device framework currently available in kernel, which registers a device directly without needing the access to an PHY ID and we can do a switch reset after that in the switch driver.
> As for the dirty way here, the machine initialization code alter a switch soft reset by directly accessing mdio registers of GMAC0 and send mdio instructions before the probing of mdio driver, doing what shouldn't be done by machine initialization code and introducing a piece of messy and duplicated code into the target.
> 
> As for the author: PLEASE don't copy code from others without acknowledging them and without even knowing what their code actually did.

First of all, I have no objection to offering you a way to solve this problem. But I feel that your personal feelings and attitudes are very unfriendly, and the last time I spoke about this in good faith, you said directly,'garbage submission', this time more than ever:'dirty hacker'. What? I am just a beginner, I have just studied, and I am more interested in this machine.

This submission is a hope and appeal to the responsible and capable people of the Openwrt organization to help fix and improve it. It's not like you are standing on the heights of morality. After all, many people in the openwrt organization are tolerant. Thanks！

**Comment by imbrolla** [comment]
> For those who are interested in that dirty hack:
> The factory U-boot of this device (In fact, on all QCA device with an FE switch) will set MDIO_MASTER_EN bit to 1, which enabled the on-switch mdio master but also disallow the direct access to switch PHYs, resulting in the inability to read PHY ID from GMAC MDIO on SoC.
> ar8216 on OpenWrt is introduced long time ago when there is no mdio device framework in kernel. It's probed using the PHY framework and current probing method requires an available PHY ID, which in this case isn't possible before setting MDIO_MASTER_EN to 0.
> A proper way of solving this problem is writing a new probing procedure using the mdio-device framework currently available in kernel, which registers a device directly without needing the access to an PHY ID and we can do a switch reset after that in the switch driver.
> As for the dirty way here, the machine initialization code alter a switch soft reset by directly accessing mdio registers of GMAC0 and send mdio instructions before the probing of mdio driver, doing what shouldn't be done by machine initialization code and introducing a piece of messy and duplicated code into the target.
> 
> As for the author: PLEASE don't copy code from others without acknowledging them and without even knowing what their code actually did.

First of all, I have no objection to offering you a way to solve this problem. But I feel that your personal feelings and attitudes are very unfriendly, and the last time I spoke about this in good faith, you said directly,'garbage submission', this time more than ever:'dirty hacker'. What? I am just a beginner, I have just studied, and I am more interested in this machine.

This submission is a hope and appeal to the responsible and capable people of the Openwrt organization to help fix and improve it. Instead of standing at the height of morality like you, saying nothing. After all, many people in the openwrt organization are tolerant. Thank

**Comment by imbrolla** [comment]
> For those who are interested in that dirty hack:
> The factory U-boot of this device (In fact, on all QCA device with an FE switch) will set MDIO_MASTER_EN bit to 1, which enabled the on-switch mdio master but also disallow the direct access to switch PHYs, resulting in the inability to read PHY ID from GMAC MDIO on SoC.
> ar8216 on OpenWrt is introduced long time ago when there is no mdio device framework in kernel. It's probed using the PHY framework and current probing method requires an available PHY ID, which in this case isn't possible before setting MDIO_MASTER_EN to 0.
> A proper way of solving this problem is writing a new probing procedure using the mdio-device framework currently available in kernel, which registers a device directly without needing the access to an PHY ID and we can do a switch reset after that in the switch driver.
> As for the dirty way here, the machine initialization code alter a switch soft reset by directly accessing mdio registers of GMAC0 and send mdio instructions before the probing of mdio driver, doing what shouldn't be done by machine initialization code and introducing a piece of messy and duplicated code into the target.
> 
> As for the author: PLEASE don't copy code from others without acknowledging them and without even knowing what their code actually did.

First of all, I have no objection to offering you a way to solve this problem. But I feel that your personal feelings and attitudes are very unfriendly, and the last time I spoke about this in good faith, you said directly,'garbage submission', this time more than ever:'dirty hacker'. What? I am just a beginner, I have just studied, and I am more interested in this machine.

This submission is a hope and appeal to the responsible and capable people of the Openwrt organization to help fix and improve it. Instead of standing at the height of morality like you, you just talk and don't do anything. After all, many people in the openwrt organization are tolerant. Thank

**Comment by imbrolla** [comment]
> 是的，另一个人在没有提到我的情况下再次使用我的作品。
> 我差不多3年前写的一个肮脏的黑客（[hackpascal / openwrt-old @ b06de10](https://github.com/hackpascal/openwrt-old/commit/b06de1007c3c5e5ece5516854df32dac5b33bfe3)）我从未计划提交给OpenWrt主线。
https://github.com/openwrt/openwrt/pull/1481


> 对于那些对这个脏黑客感兴趣的人：
> 该设备的工厂U-boot（事实上，在所有带有FE开关的QCA设备上）将MDIO_MASTER_EN位设置为1，这启用了on-switch mdio master，但也禁止直接访问交换机PHY，导致无法从SoC上的GMAC MDIO读取PHY ID。
> 很久以前，当内核中没有mdio设备框架时，OpenWrt上的ar8216就被引入了。它使用PHY框架进行探测，并且当前探测方法需要可用的PHY ID，在这种情况下，在将MDIO_MASTER_EN设置为0之前是不可能的。
> 解决此问题的正确方法是使用内核中当前可用的mdio-device框架编写新的探测过程，该框架直接注册设备而无需访问PHY ID，之后我们可以在交换机驱动程序中进行切换重置。
> 至于这里的脏路，机器初始化代码通过直接访问GMAC0的mdio寄存器来改变开关软复位，并在探测mdio驱动程序之前发送mdio指令，执行机器初始化代码不应该做的事情并引入一块凌乱和重复的代码进入目标。
> 
> 至于作者：请不要在没有确认代码的情况下从别人那里复制代码，甚至不知道他们的代码实际上做了什么。

**Comment by 981213** [comment]
"Dirty hack" (NOT DIRTY HACKER) is a widely used term referring to problems that solved incorrectly. Here it refers to the code written by @hackpascal and it just has nothing to do with you. You should really improve your english skill...

**Comment by 981213** [comment]
And what's the problem of calling your PR a "garbage submission" after you ignore the patch submission rules twice? I said that you should "Squash all commits into one and follow https://openwrt.org/submitting-patches" in #1444 and you just created #1458 that you followed completely nothing written in that patch submission guide. Here is a THIRD PR that you followed COMPLETELY NOTHING written there. (Commit messages are not GitHub PR description. If you are having trouble understanding the rules you should improve your english skill before submitting anything...)
(BTW "Squash all commits into one" means that you should submit all files in "one commit". You have 13 commits here and every single commit doesn't have a commit message that make sense...)

**Comment by imbrolla** [comment]
> And what's the problem of calling your PR a "garbage submission" after you ignore the patch submission rules twice? I said that you should "Squash all commits into one and follow https://openwrt.org/submitting-patches" in #1444 and you just created #1458 that you followed completely nothing written in that patch submission guide. Here is a THIRD PR that you followed COMPLETELY NOTHING written there. (Commit messages are not GitHub PR description. If you are having trouble understanding the rules you should improve your english skill before submitting anything...)
> (BTW "Squash all commits into one" means that you should submit all files in "one commit". You have 13 commits here and every single commit doesn't have a commit message that make sense...)



> "Dirty hack" (NOT DIRTY HACKER) is a widely used term referring to problems that solved incorrectly. Here it refers to the code written by @hackpascal and it just has nothing to do with you. You should really improve your english skill...



> "Dirty hack" (NOT DIRTY HACKER) is a widely used term referring to problems that solved incorrectly. Here it refers to the code written by @hackpascal and it just has nothing to do with you. You should really improve your english skill...

I don't think you understand. I submitted it because some problems were not solved, but they could be compiled temporarily. I mean hoping to get help from some people.

**Comment by imbrolla** [comment]
> And what's the problem of calling your PR a "garbage submission" after you ignore the patch submission rules twice? I said that you should "Squash all commits into one and follow https://openwrt.org/submitting-patches" in #1444 and you just created #1458 that you followed completely nothing written in that patch submission guide. Here is a THIRD PR that you followed COMPLETELY NOTHING written there. (Commit messages are not GitHub PR description. If you are having trouble understanding the rules you should improve your english skill before submitting anything...)
> (BTW "Squash all commits into one" means that you should submit all files in "one commit". You have 13 commits here and every single commit doesn't have a commit message that make sense...)

This is the code that is modified through webpage.
I've explained this to you, and if you keep thinking like this, I won't say anything more.

**Comment by imbrolla** [comment]
> "Dirty hack" (NOT DIRTY HACKER) is a widely used term referring to problems that solved incorrectly. Here it refers to the code written by @hackpascal and it just has nothing to do with you. You should really improve your english skill...

I don't think you understand. I submitted it because some problems were not solved, but they could be compiled temporarily. I mean hoping to get help from some people.

**Comment by imbrolla** [comment]
> And what's the problem of calling your PR a "garbage submission" after you ignore the patch submission rules twice? I said that you should "Squash all commits into one and follow https://openwrt.org/submitting-patches" in #1444 and you just created #1458 that you followed completely nothing written in that patch submission guide. Here is a THIRD PR that you followed COMPLETELY NOTHING written there. (Commit messages are not GitHub PR description. If you are having trouble understanding the rules you should improve your english skill before submitting anything...)
> (BTW "Squash all commits into one" means that you should submit all files in "one commit". You have 13 commits here and every single commit doesn't have a commit message that make sense...)

This is the code that is modified through webpage.
I've explained this to you, and if you keep thinking like this, I won't say anything more.

**Comment by 981213** [comment]
> I submitted it because some problems were not solved

Normally we submit a pull request to contribute our code to the project and we should fix the problems if there are some (or close the PR). However what you've done is "submit problems and wait for someone to fix it". PR isn't somewhere you should be doing things like this. Mailing list and forum are the proper places to ask for help.

> they could be compiled temporarily.

"It works" doesn't mean that "it is done right" and if you are not so "narrow-minded" you should be aware that introducing a dirty hack makes the code messy and hard to maintain and that's not what should be done when there is a proper fix for it.

**Comment by imbrolla** [comment]
> For project owners: I think you can close this PR since the author insist that he won't fix the rule violation because "he is using github web editor"...

"since the author insist that he won't fix the rule"？Please, I really take you. I ask you not to take your meaning as my position.

**Comment by imbrolla** [comment]
> > I submitted it because some problems were not solved
> 
> Normally we submit a pull request to contribute our code to the project and we should fix the problems if there are some (or close the PR). However what you've done is "submit problems and wait for someone to fix it". PR isn't somewhere you should be doing things like this. Mailing list and forum are the proper places to ask for help.
> 
> > they could be compiled temporarily.
> 
> "It works" doesn't mean that "it is done right" and if you are not so "narrow-minded" you should be aware that introducing a dirty hack makes the code messy and hard to maintain and that's not what should be done when there is a proper fix for it.

As I said earlier, you're just talking. I mean, some of the machine code that has been changed can be compiled and temporarily available to those in need. I also say that I am a beginner, and that is beyond my ability to solve this problem. I also expressed the hope that someone can help, rather than do nothing, and has been neglecting it.

**Review by imbrolla — COMMENTED** [review]
Compared with the previous version, this version of the code has modified one place so that kernel 4.14 can compile.
qq 20181021120220
Thank wheretoteardown for his help.

**Comment by 981213** [comment]
> "since the author insist that he won't fix the rule"？

You are not asked to "fix the rule". You are asked to "fix the rule violations"

> Please, I really take you.

Please use auto translation service carefully or you'll miss some details (e.g. the word "hack" never means "hacker", "dirty hack" doesn't mean that "The author is disgusting" and "take you" make no sense in English.)

> I ask you not to take your meaning as my position.

That's what you've actually done. You simply never fix it since #1444  and you refused to talk about this problem anymore. (What I assumed from this broken sentence :"if you keep thinking like this, I won't say anything more.")

> As I said earlier, you're just talking. 

Also a sentence that makes no sense...

> I mean, some of the machine code that has been changed can be compiled and temporarily available to those in need.

Just share it on a forum instead. That's not a piece of code that should go into mainline OpenWrt because it's a dirty hack.

> I also expressed the hope that someone can help

Use forum or mailing list instead. That's the proper place for these kinds of things.

This debate goes nowhere. Follow the rules if you want to contribute to OpenWrt, share your work on a forum if you want to, ask for help on a forum or mailing list instead of creating useless PR. I'll stop talking here now...

**Review by imbrolla — COMMENTED** [review]
.

**Comment by imbrolla** [comment]
以上的英文回答是通过机器翻译（意思表达可能有出入），怕给那个数字先生造成二次误会，只好以中文再次表达一下。
（这个提交是为了在内核4.14编译通过弄的，有人表示有一些不完善的地方，我个人能力有限，不得而知。希望有心人可以尝试解决。）

**Comment by redchenjs** [comment]
@imbrolla 楼主想通过社区帮忙解决这个问题的思路是好的，大可以先在issue里面讨论讨论，找找有没有统一战线的极客们一起合作完善代码，这样直接提交不完善的代码的确是有些唐突，OpenWRT的提交有标准流程和规范，所有的提交者都应该自觉遵守，不规范的提交是不被社区所接受的，还会占用大家宝贵的公共时间和空间。原作者认为代码中存在着一些不规范的代码，这些代码只是临时调试使用，很多地方的代码还有问题，后期会变得难以维护，所以不应该被提交到主分支。原作者虽然不再维护这个项目，但对自己的代码是享有著作权的，即便是开源代码，关心代码的去向也是对自己代码负责任的表现，不希望一些不规范的代码被滥用，因为这样对原作者和整个社区都会带来不好的影响，不知道你对此有没有切身体会。原作者并非认为你不应该使用他的代码，只是希望你能够研究透，吃透后将那些未完成的临时代码替换成规范的代码，这样才是正确的解决方式，代码必须要思虑周全，不规范的代码你可以写在自己的项目中，但不能出现在公共的项目里，技术归技术，写代码是需要时间和精力的，你不可能用你自己的意志去要求别人来做，能做出改变的只有你自己，社区的准则就是任何人都不应该把自己是初学者当作借口，规范就是规范，做事一定到做好做到位，要么就不要做，对自己对他人对代码都要负责，只要代码一天不满足规范，这份代码就一天不可能合并到主分支。

**Comment by imbrolla** [comment]
> @imbrolla 楼主想通过社区帮忙解决这个问题的思路是好的，大可以先在issue里面讨论讨论，找找有没有统一战线的极客们一起合作完善代码，这样直接提交不完善的代码的确是有些唐突，OpenWRT的提交有标准流程和规范，所有的提交者都应该自觉遵守，不规范的提交是不被社区所接受的，还会占用大家宝贵的公共时间和空间。
感谢您善意的提醒，我是因为刚开始知道这个的，还并不清楚其他渠道，不过，这些渠道对我来说，实在太难，可能连发言都难，更别说需要这种蹩脚的机器翻译。。。。
>原作者认为代码中存在着一些不规范的代码，这些代码只是临时调试使用，很多地方的代码还有问题，后期会变得难以维护，所以不应该被提交到主分支。原作者虽然不再维护这个项目，但对自己的代码是享有著作权的，即便是开源代码，关心代码的去向也是对自己代码负责任的表现，不希望一些不规范的代码被滥用，因为这样对原作者和整个社区都会带来不好的影响，不知道你对此有没有切身体会。
现实的情况下，你可能会发现：临时的措施可能会变成永久的措施。也意味着这些“临时”的代码也会变成“永久”的代码。这个就是我担心的现状。
>原作者并非认为你不应该使用他的代码，只是希望你能够研究透，吃透后将那些未完成的临时代码替换成规范的代码，这样才是正确的解决方式，代码必须要思虑周全，不规范的代码你可以写在自己的项目中，但不能出现在公共的项目里，技术归技术，写代码是需要时间和精力的，你不可能用你自己的意志去要求别人来做，能做出改变的只有你自己，社区的准则就是任何人都不应该把自己是初学者当作借口，规范就是规范，做事一定到做好做到位，要么就不要做，对自己对他人对代码都要负责，只要代码一天不满足规范，这份代码就一天不可能合并到主分支。
你说的吃透对我来说，难如登天，事实确实如此，原因我也不解释了。但是我其实没有想过强求别人来做，正如我在反复重申和解释这个原因：这个提交是为有需要的人弄的，解决在内核4.14编译的错误。但那位数字先生一直在强调规范，我想他误会错了我的出发点。代码作者本人也说代码不完善，我也对“合并请求”并不抱太大的希望。但是，我也表示对此事造成的误会和冒犯的人感到抱歉。也希望大佬，大侠们对此事看看就好，一笑而过。

**Comment by ynezz** [comment]
@imbrolla Thank you for your contribution, but I think, that it's clear now, that it's not going to be merged as it is. Could you please close this PR? Thanks!

**Comment by hzjnet** [comment]
作者能做3.18.23的提交吗？  谢谢

**Pull request closed without merging**
