### PR TITLE
bcm4908: fix calculation of new cferam index

### PR DESCRIPTION
**Pull request by mans0n**
The arithmetic expansion fails when idx becomes a two digit number.
Fix this by relying on expr command.
```
root@OpenWrt:/# echo $(((028 + 0) % 1000))
/bin/ash: arithmetic syntax error
root@OpenWrt:/# echo $(($(busybox expr 028 + 0) % 1000))
28
```

### CODE REVIEW

**Comment by mans0n** [comment]
Cc: @rmilecki

**Comment by mans0n** [comment]
@rmilecki Could you take a look at this?

**Comment by adschm** [comment]
@rmilecki Ping.

**Comment by rmilecki** [comment]
Thanks @mans0n for debugigng this issue & sorry for late reply.

I don't think that hardcoding `busybox` there is the best idea as that makes code less portable. If this problem can be solved with another simple trick - that doesn't make is `busybox` specific - I'd prefere a more generic solution.

I found https://stackoverflow.com/questions/12821715/convert-string-into-integer-in-bash-script-leading-zero-number-error and there are two solutions suggested:
1. Forcing 10-base parsing of number
2. Removing leading zeroes

---

Forcing base 10 seems to work well in bash:
```
# idx=028; echo $(( 10#$idx + 0))
28
```
but seems to fail in busybox:
```
# idx=028; echo $(( 10#$idx + 0))
-ash: arithmetic syntax error
```

---

Replacing leading zeroes seem to work in both: bash and busybox however:
```
# idx=008; echo ${idx##*0}
8
```

So do you think you could use that solution?

**Comment by mans0n** [comment]
> I don't think that hardcoding busybox there is the best idea as that makes code less portable. If this problem can be solved with another simple trick - that doesn't make is busybox specific - I'd prefere a more generic solution.

It seems our sysupgrade already has a dependency on busybox according to `git grep "busybox " package/base-files/files`, but I agree that a simple shell expansion is better than an explicit expr call if we have a choice.

> 1. Forcing 10-base parsing of number
> 2. Removing leading zeroes

I remember the first approach did not work on busybox as you said, but I don't remember exactly why I didn't choose the second approach, I should have written down the decision history somewhere...

Anyway, it seems to work with some numbers:
```
# idx=028; inc=0; echo $(((${idx##*0} + inc) % 1000))
28
```

...but it fails with numbers ending with 0:
```
# idx=020; inc=0; echo $(((${idx##*0} + inc) % 1000))
0
```

And I've lost access to my bcm4908 board, so I can't do run-test myself at the moment...

**Comment by mans0n** [comment]
Added expr to RAMFS_COPY_BIN.

**Comment by rmilecki** [comment]
> ...but it fails with numbers ending with 0:

You're absolutely right, good catch.

**Comment by rmilecki** [comment]
f4323538501d58298f4df73a034a51375a477cfc ("bcm4908: fix calculation of new cferam index")

**Pull request closed without merging**
