### PR TITLE
ramips: add/fix support for Cudy WR1300 v3

### PR DESCRIPTION
**Pull request by zekica**
This creates a separate build for Cudy WR1300 v3, a device identical to v2.

It fixes TX Power issue on all Cudy WR1300 v3 on 5GHz MT7613BE by using proper eeprom-data (taken from a v2 device), as all v3 devices I tested with have a bdinfo partition that contains improper calibration data and using it limits the tx power to the base value od 3dBm.

### CODE REVIEW

**Comment by zekica** [comment]
Hello,

Sorry, it is the "factory" partition, my mistake.

I'm not sure my way is a correct way to do it. I only have a v3 here too. 
The v2 device I fetched the eeprom data from is in production and not mine - they only lent me one for a short time and I cannot test with it, and there is no way to purchase one right now - all merchants sell v3 here.

I can try swapping 0x8000 and 0x0000 from v2 dts and see if that fixes it. 

So do I set `mediatek,mtd-eeprom = <&factory 0x8000>;` for both &pcie0 (mt7603) and &pcie1 (mt7613) devices?
Or do I test setting 0x0000 for mt7603 and 0x8000 for mt7613?

5GHz led doesn't work on v3 with my change, but that is the only issue I encountered. I don't have a v2 to test.

**Comment by Djfe** [comment]
Do you know whether v2 runs fine or have you never tested v2?

I'm certain that both need different calibration data. but you could check whether 0x8000 is meant for mt7603 or mt7613
maybe compare the output of `iw list`
I'm not sure myself how to debug this correctly

I can check eeprom/factory of my v3, whether calibration data exists at 0x0000 and 0x8000
Maybe just your unit is affected by missing calibration data?

**Comment by zekica** [comment]
v2 works fine in production using the dts from 23.05 or main branches (except for the mt7613be bug that I patched using [https://github.com/ptpt52/mt76/commit/9cf5097696647db067f5dc99327d49a7dfe3c6a1]([PATCH] mt7615: hack to clear all pending packets) but that is not unique to wr1300v2

**Comment by Djfe** [comment]
I only now realised that the factory data starts with
7603
or
7663
respectively, so I'll be able to see, which eeprom belongs to which chip :)

**Comment by zekica** [comment]
@Djfe Are there any news regarding this, do you have a better idea for supporting v3 devices properly? Thank you for all your work.

**Comment by Djfe** [comment]
I wasn't at home in the last week and therefore couldn't check the device, yet 😅
I will do it soon

**Comment by Djfe** [comment]
I just checked mine.
So your complaint is: v3 has wrong calibration data and you assume the calibration data for v2 is correct.

I think the data on your device is correct but the addresses were swapped.
Pls swap pcie1 and pcie0 in order for pcie0 to come first.

pcie0 is likely 2.4ghz and needs factory 0x0
while pcie1 is likely 5ghz and needs factory 0x8000

**Comment by Djfe** [comment]
I just rebased/updated my branch
feel free to test, whether it fixes your issue (wrong calibration/tx power)
https://github.com/djfe/openwrt/tree/Cudy1300

**Comment by zekica** [comment]
I will test probably tomorrow morning, as I'm quite busy today.

**Comment by Djfe** [comment]
if it doesn't we will have to compare all eeprom versions (your 3 and my one's) to see if we can figure it out.

**Comment by zekica** [comment]
I have built a version with the following [.config](https://gist.github.com/zekica/20c1569ba68e51cf93be94f9c67418f7) using your commit 93beb73 and it appears that it works fine with a v3 device - the effective tx power limit is the max of 23dBm and whatever is in the regulatory database (as it probably should be), but I don't have a v2 to test.

Can you tell me what did you exactly do as you almost completely rewrote the dts?

**Comment by zekica** [comment]
Hi, just wondering if there are any updates on your end?

**Comment by zekica** [comment]
@Djfe Hi, did you have time to look further into this? What can I do to help?

**Comment by Djfe** [comment]
well my issue right now, is finding time to get stuff done. :/

I didn't exactly rewrite the full dts this commit
https://github.com/Djfe/openwrt/commit/b57a50485739e99bfe358072ab4f38ff3b3b9ea2 leaves everything as it is and moves stuff that both nodes share into a common file so we don't have to repeat it for both. the single .dts files only contain stuff that is different between the revisions from now on.
ok what the commit did change: it combined both wifi layouts which were different before for no reason.
and it creates a new image for v3 and adds a uname to the image so you don't need to sysupgrade with force from Cudy's signed Openwrt build.
https://github.com/Djfe/openwrt/commit/b57a50485739e99bfe358072ab4f38ff3b3b9ea2

I can recommend reading the commit descriptions

this commit moves stuff in the dts around
https://github.com/Djfe/openwrt/commit/2a3b16818512f924d8cbde3ec7084b6611368dcd

and this one implements a new dts scheme for defining mac addresses https://github.com/Djfe/openwrt/commit/93beb737afef2f8db71b302af3b31f4884a5045f

the fix is part of the first commit. the issue was fixed by giving v1 and v2 the same layout for pcie0 and pcie1.
v2 made changes where probably none were necessary.

**Comment by Djfe** [comment]
you could try building this and runtesting it on your WR1300 v2

to confirm that it doesn't break v2.

If you tell me the version your v2 is running in production, then I could create a branch for you with the necessary change but nothing else (same version essentially but with the fix in place)
It shouldn't break anything. only improve it

if anything is worse than before then I might have to change some stuff in the dts again. But I would be surprised if that were the case

**Comment by zekica** [comment]
Closing this as @Djfe has a better solution

**Pull request closed without merging**
