### PR TITLE
mvebu: add support for SFP cage of CZ.NIC Turris Omnia

### PR DESCRIPTION
**Pull request by kkudielka**
Subject says it all. Apart from backporting upstream device tree changes, only the boot script needs to be modified. I have tested this with 5.4 and 5.10 kernels. Hardware: TP-Link TL-SM321B, CZ11NIC13.

This PR would also be a candidate for cherry picking in 21.02, as has been requested in the [forum](https://forum.openwrt.org/t/turris-omnia-experimental-support-for-sfp-cage/24046/61). Without the 5.10 patches, of course.

### CODE REVIEW

**Comment by kkeijzer** [comment]
As the one who made the request on the forum, I would definitely like to see the SFP enablement backported to Linux 5.4, so it can work on OpenWrt 21.02. Currently it's the only functionality completely missing from the Omnia, with one of its main selling points being the SFP option.

**Comment by elkablo** [comment]
@kkudielka note that I am working on proper handling for Omnia's SFP cage in kernel. There are some SFP modules which will bring the `MOD_DEF0` pin down only after the firmware inside SFP is ready, which make take up to 30 seconds (maybe more) on some GPON SFP modules. Since U-Boot looks at the value of the `MOD_DEF0` pin within the first 10 seconds, it won't detect these modules and boot the kernel without SFP node enabled.

**Review by elkablo — APPROVED** [review]
Looks good to me.

**Review by BKPepe — APPROVED** [review]

**Comment by kkudielka** [comment]
> @kkudielka note that I am working on proper handling for Omnia's SFP cage in kernel. There are some SFP modules which will bring the `MOD_DEF0` pin down only after the firmware inside SFP is ready, which make take up to 30 seconds (maybe more) on some GPON SFP modules. Since U-Boot looks at the value of the `MOD_DEF0` pin within the first 10 seconds, it won't detect these modules and boot the kernel without SFP node enabled.

Thanks @elkablo for the continuing work upstream - and for the approval if this PR. For owners of those "lazy" SFP modules: Wouldn't an increase of the U-Boot variable `bootdelay` be a viable workaround with the present solution?

**Comment by elkablo** [comment]
> For owners of those "lazy" SFP modules: Wouldn't an increase of the U-Boot variable `bootdelay` be a viable workaround with the present solution?

@kkudielka I fear that some of them will start booting only after `TX_DISABLE` pin is brought low. So it depends on what is the default value of that GPIO. If the value of this GPIO in U-Boot is 0, the SFP module will start booting, and if `bootdelay` is large enough, the SFP will bring `MOD_DEF0` low before your code reads the value. So it would be a viable workaround. But waiting 30 seconds before booting is not something many users will want to do.

**Comment by kkeijzer** [comment]
On the other hand, wouldn't having most modules working in the default builds, with some exceptions requiring a boot delay, be better than having no modules working at all, as is the current situation?

**Comment by jschwartzenberg** [comment]
This seems great. Currently on Turris OS, but having full upstream OpenWRT support with the SFP would be spectacular!

**Comment by bobafetthotmail** [comment]
> @kkudielka note that I am working on proper handling for Omnia's SFP cage in kernel. There are some SFP modules which will bring the `MOD_DEF0` pin down only after the firmware inside SFP is ready, which make take up to 30 seconds (maybe more) on some GPON SFP modules. Since U-Boot looks at the value of the `MOD_DEF0` pin within the first 10 seconds, it won't detect these modules and boot the kernel without SFP node enabled.

is there a drawback to always boot with SFP node enabled and let Linux kernel deal with it? why does u-boot check this

**Comment by kkudielka** [comment]
> is there a drawback to always boot with SFP node enabled and let Linux kernel deal with it? why does u-boot check this

I think the comments in the new upstream DTS describe the situation very well:
```
Turris Omnia has an SFP cage that, together with WAN PHY, is connected
to eth2 SerDes via a SerDes multiplexor. When a SFP module is present,
the multiplexor switches the SerDes signal from PHY to SFP.

Describe the SFP cage, but leave it disabled. Until phylink has support
for such configuration, we are leaving it to U-Boot to enable SFP and
disable WAN PHY at boot time depending on whether a SFP module is
present.
```
So, the main drawback is: No hot plugging / unplugging of SFP module. The boot script probes for module presence (MOD_DEF0 should be grounded, according to the SFP Transceiver MSA), and modifies the device tree, before booting Linux.

Until we have the perfect solution @elkablo is working on, I believe this is acceptable for most users.

**Review by ghost — APPROVED** [review]

**Comment by lucenera** [comment]
SFP works perfectly on my Omnia.  I'd like to see the pull request accepted in master.

**Comment by kkeijzer** [comment]
`Tested-by: Kevin Keijzer <kevin@quietlife.nl>`

**Comment by kkudielka** [comment]
@elkablo @BKPepe Thank you for approving this PR. Unless you object, I'll add Reviewed-by tags using E-mail addresses from your latest OpenWrt commits.

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master.

**Pull request closed without merging**
