### PR TITLE
Kirkwood: add sata port multiplier support

### PR DESCRIPTION
**Pull request by bobafetthotmail**
the sata controllers in kirkwood SoCs support sata port multipliers, just like mvebu.
Enable this feature.
tested and working on nsa310b

Signed-off-by: Alberto Bursi <alberto.bursi@outlook.it>

### CODE REVIEW

**Comment by frymezim** [comment]
@bobafetthotmail how does sata port multiplier work? How can I add more HD on my NSA325?

**Comment by chunkeey** [comment]
> how does sata port multiplier work? How can I add more HD on my NSA325?

oh, you need an extra sata port multiplier card (that usually also needs some power).

The problem here might be that this is could be considered a "modification". And the stance on that was that openwrt usually does not accept such patches. But, other nas targets (gemini, apm821xx, sunxi and mvebu) have it enabled too. So yeah, not that uncommon (altought x86 does not have it, which would be the prime candidate)?! 

Maybe @bobafetthotmail: do you know how much kbs it adds to the kirkwood kernel?

**Comment by bobafetthotmail** [comment]
It works like a USB hub, but with Sata ports. It's plug-and-play, you don't need to configure it.
The maximum bandwith is limited to the single Sata port you attach it to, just like with a USB hub.

Since the NSA325 has a Sata+Power 22pin female slot for each drive it supports (as do the PogoPlugs and GoflexNet/GoflexHome), you will need to get a sata 22pin male to male adapter like this 
https://www.ebay.it/itm/SATA-22Pin-7-15-Male-to-SATA-22P-7-15-Male-extension-convertor-Straight-adapter/232160573079
And then on this connector you can attach a cable like this for esata or for sata
esata :https://www.ebay.it/itm/2-5-Adattatore-cavo-USB-SATA-da-22-pin-a-eSATA/372508010892
sata :  https://www.ebay.it/itm/Cavo-Combinato-Di-Alimentazione-Dati-Sata-7p-4-pin-Con-22-Pin-7-15-Da/173460256431

Yes you will be using it "in reverse" but Sata cables are not directional, it's all fine.

On your NSA325 you can set up both Sata ports like this, and you should be able to control up to 10 drives.

This the sata multiplier board I used for testing is a "bridge board". It's supposed to be used in an external enclosure (usually rack mounted). http://www.lycom.com.tw/st126rm.htm

Some types of low-end driverless hardware RAID cards have this ability, you can set them to "port multiplier mode" with their dip switches. https://www.sybausa.com/index.php?route=product/product&product_id=184

Decent RAID enclosures with eSata port also offer the same feature as they use the same chipset.
For example this one https://www.amazon.com/Mediasonic-ProBox-HF2-SU3S2-SATA-Enclosure/dp/B003X26VV4/ref=sr_1_3?keywords=esata+raid+enclosure&qid=1555786796&s=gateway&sr=8-3
see the "Important Note": 
_Motherboards eSATA port Must support Port Multiplier in order for your computer to recognize multiple hard drive if the unit is connected to eSATA port._

If you buy a port multiplier board please make sure it has a heatsink over the chipset (or a fan blowing air on it), or add it yourself. They do heat up quite a bit and if there is no heatsink or no fan it will be unstable or even burn out.


Afaik, Intel and AMD Sata controllers in modern PCs don't support Sata port multipliers so this card won't work in a normal PC.
For a PC you need a PCIe card with a Sata controller that does support port multipliers (Usually Silicon Images or Marvell chipsets).
But if you have PCIe slots available it's usually better to just buy a low-end 8-port SAS RAID card and cross-flash it to non-RAID firmware.

**Comment by bobafetthotmail** [comment]
> The problem here might be that this is could be considered a "modification". And the stance on that was that openwrt usually does not accept such patches. 

Seriously, wtf are you talking about.

It's a Sata equivalent of USB hubs. No hardware modification to the device is required.

> altought x86 does not have it, which would be the prime candidate

No x86 is the least important candidate.
On PC it's not a thing (talking of Linux and Windows in general too) because of three reasons mainly:
-Intel/AMD Sata controllers don't support the feature so you would need an additional PCie card
-the performance is obviously bottlenecked by the single Sata port
-it's usually cheaper and well-known practice in the "home server" communities to just buy a second-hand 8-port SAS PCIe RAID card for 80-ish euro and cross-flash it to non-RAID firmware. Then plop it in a PCIe slot and boom, 8 more native Sata/SAS ports that go at native speed, for 10 euro-per-port, which is the same price-per-port that you get from smaller cards too.

> 
> Maybe @bobafetthotmail: do you know how much kbs it adds to the kirkwood kernel?

I'll check.

**Comment by bobafetthotmail** [comment]
> Maybe @bobafetthotmail: do you know how much kbs it adds to the kirkwood kernel?

Is this it? or I am comparing sizes of the wrong files?

```
alby@openSUSE-xeon:~/kirkwood test> ls -l *
-rwxr-xr-x 1 alby users 8517952 20 apr 21.54 vmlinux
-rwxr-xr-x 1 alby users 6454808 20 apr 21.54 vmlinux.elf
-rwxr-xr-x 1 alby users 6454808 20 apr 22.09 vmlinux.elf_with_PMP
-rwxr-xr-x 1 alby users 8517952 20 apr 16.52 vmlinux_with_PMP
-rw-r--r-- 1 alby users 2143610 20 apr 21.55 zyxel_nsa310b-uImage
-rw-r--r-- 1 alby users 2146562 20 apr 16.53 zyxel_nsa310b-uImage_with_PMP
```

**Comment by chunkeey** [comment]
>no offence but.. wtf are you talking about.

[No Offence](https://idioms.thefreedictionary.com/no+offence). None taken, but please let's not go there, okay?

It's what you wrote in the response to @frymezim : https://github.com/openwrt/openwrt/pull/2007#issuecomment-485151624

> Since the NSA325 has a Sata+Power 22pin female slot for each drive it supports (as do the PogoPlugs and GoflexNet/GoflexHome), you will need to get a sata 22pin male to male adapter like this
https://www.ebay.it/itm/SATA-22Pin-7-15-Male-to-SATA-22P-7-15-Male-extension-convertor-Straight-adapter/232160573079
And then on this connector you can attach a cable like this for esata or for sata
esata :https://www.ebay.it/itm/2-5-Adattatore-cavo-USB-SATA-da-22-pin-a-eSATA/372508010892
sata : https://www.ebay.it/itm/Cavo-Combinato-Di-Alimentazione-Dati-Sata-7p-4-pin-Con-22-Pin-7-15-Da/173460256431
>
> Yes you will be using it "in reverse" but Sata cables are not directional, it's all fine.
>
> If you buy a port multiplier board please make sure it has a heatsink over the chipset (or a fan blowing air on it), or add it yourself. They do heat up quite a bit and if there is no heatsink or no fan it will be unstable or even burn out.

Don't you see it? How many hoops you've to jump through to get this custom solution to work just right? Granted you don't have to solder chips, but I don't see how these cables and the extra hdds will fit into the enclosure any longer.

That being said, I'm not really against enabling PMP. As I've mentioned "other nas targets [...] have it enabled too". And you've showed that currently it adds just a tad less than 3KiB to the kernel's image size, so the kirkwood device with probably the most restrictive kernel size limit (Linksys EA3500) of 2624KiB is probably not in danger since its kernel size is currently at 2154 KiB. (I'm careful now because of the TL-WDR4900v1).

> No x86 is the least important candidate.
On PC it's not a thing (talking of Linux and Windows in general too) because of three reasons mainly [...]

I don't think the x86 targets serves only PCs. SATA port multiplier backplanes (CFI-B53PM) can be found in gear like these backblaze storage pods:
starting way back from 2009:
https://www.backblaze.com/blog/petabytes-on-a-budget-how-to-build-cheap-cloud-storage/

to their current version from 2016:
https://www.backblaze.com/blog/open-source-data-storage-server/ 

So that's why I think x86's OpenWrt could have PMP support as well, don't you agree?

**Comment by bobafetthotmail** [comment]
> 
> Don't you see it? How many hoops you've to jump through to get this custom solution to work just right?
> 

You misunderstood I guess?

There is nothing "custom" nor "hoops" to jump through here. For devices that have a 22-pin Sata port you need a male-male 22-pin Sata adapter and a 22-pin Sata to sata/esata cable. This is all commercial hardware, cheap, easily available to everyone and requiring 0 skill to connect.

For a nsa310b it's just an esata cable to connect the native esata port on the back of the device to something else (esata enclosure probably).

You can then connect many different things to this sata/esata cable that comes from the NAS, either a "bridge board" (or the full rack it is supposed to fit into), a low end hardware RAID card or a esata HDD RAID enclosure that usually supports port multiplier too.

All these will work OOTB and are all commercial devices, this is how any sata port multiplier setup works.

>Granted you don't have to solder chips, but I don't see how these cables and the extra hdds will fit into the enclosure any longer.

Yeah it's ugly, but it isn't against the rules, is it?

> As I've mentioned "other nas targets [...] have it enabled too". And you've showed that currently it adds just a tad less than 3KiB to the kernel's image size, so the kirkwood device with probably the most restrictive kernel size limit (Linksys EA3500) of 2624KiB is probably not in danger since its kernel size is currently at 2154 KiB. (I'm careful now because of the TL-WDR4900v1).

I can understand this concern. Do you think it's better to make a kmod for PMP? 

Afaik PMP is only used to access storage drives since no bootloader is able to operate a Sata port multiplier, so I'd say no device relies on it to boot.

I have no idea if this can be put in a kmod, I never made kmods at all. Is it as easy as making something like this? https://github.com/openwrt/openwrt/commit/c472ed29b4de611803438402d688f3bb1a650573

Having it as a module would kill a flock of birds with one stone, it would become available on x86 and we can reduce the kernel size in all other NAS targets.

>I don't think the x86 targets serves only PCs.

I actually wanted to say both PC and server hardware, but I didn't. I did mention the "home server" community in the last point too.

> SATA port multiplier backplanes (CFI-B53PM) can be found in gear like these backblaze storage pods:

That's a very specific use-case that does not contradict the gist of what I said.
(people on x86 usually need performance or can install similar sized sata/SAS cards at the same price)

BackBlaze is doing cold storage. The arrays in their pods are not supposed to provide high performance, they are supposed to be be the cheapest possible data availability. Each specific server won't be accessed by more than a few users at a time.

Unless you need to put 60+ drives in a rack for the sake of maximizing the amount of drives you connect to each server motherboard (which is not really a common requirement outside of cold storage), buying Sata or SAS PCIe cards is actually cheaper than making a small Sata port multiplier setup.
You can also get SAS backplanes for relatively cheap and they will work 100% fine with Sata drives.

> So that's why I think x86's OpenWrt could have PMP support as well, don't you agree?

Oh sure it can have PMP too, every target that supports PMP in hardware should have PMP imho.

I was just explaining why none ever complained for a decade about the absence of PMP in OpenWrt x86. Simply none ever needed it.

**Comment by neheb** [comment]
@chunkeey mvebu target already has this

From the amazon example, Seems to me all that's needed is this: https://www.ebay.com/itm/12V-5V-Power-eSATA-USB-2-0-Combo-to-22-Pin-SATA-Adapter-Cable-for-2-5-3-5-inch/281315629679?epid=1339381194&hash=item417fb7da6f:g:js4AAOSwQG5Zw2BZ

And for mvebu a regular esata cable.

**Comment by bobafetthotmail** [comment]
> From the amazon example, Seems to me all that's needed is this: https://www.ebay.com/itm/12V-5V-Power-eSATA-USB-2-0-Combo-to-22-Pin-SATA-Adapter-Cable-for-2-5-3-5-inch/281315629679?epid=1339381194&hash=item417fb7da6f:g:js4AAOSwQG5Zw2BZ
> 

That's a female 22-pin Sata connector. All devices that have 22-pin connectors will be using females too as they are supposed to be connected to a Sata drive's male 22-pin sata connector.
See here a photo of the goflexnet for example https://www.mydigitallife.net/seagate-freeagent-goflex-net-media-sharing-nas-device-review/

You need that cable AND a male-male 22-pin sata connector if you want to connect that cable to another female connector. https://www.ebay.com/itm/2-5inch-SATA-22Pin-Male-to-SATA-22P-7-15-Male-extension-convertor-adapter-USA/123685869190?hash=item1ccc409686:g:h~AAAOSw96ZbzY6R

**Comment by neheb** [comment]
Ah you're right.

**Comment by diizzyy** [comment]
PM support isn't as straight forward as USB because of chipset (controller and PM controller) quirks and because of FBS/FIS) and CBS. I don't see the reason for a huge debate about it, just enabled it and "you're on your own".

To my knowledge you're in general recommended to stick with ASMedia controllers if you want to go for the PM route and they seems to be the most "compatible" controllers available today. 

You can also find a bit "hacky" solutions such as:
https://www.amazon.com/Ableconn-PEX10-SAT-Port-Express-Adapter/dp/B0177GBY0Y
https://www.amazon.com/GLOTRENDS-Adapter-Chipset-Mining-Devices/dp/B07N39H887

https://ata.wiki.kernel.org/index.php/SATA_hardware_features (if you want a somewhat "complete list").

To my knowledge it's in general discouraged because of performance issues and also reliability because it's apparently hard to recover from a failure reliably as PMs have a bit of "undefined" behaviour.

**Comment by Leo-PL** [comment]
And it's not recommended to put RAID setups on them either, as indeed if just one disk on PM hangs, they will hang too, and pull down all the drives on them, in contrast with SAS PMs.

**Comment by bobafetthotmail** [comment]
> And it's not recommended to put RAID setups on them either, as indeed if just one disk on PM hangs, they will hang too, and pull down all the drives on them, in contrast with SAS PMs.

Jmicron PMs maybe, as they are the lousier ones in general (also for "hardware raid" enclosures).

Silicon Image and Marvell PMs don't hang like that when a drive fails or is removed.

**Comment by Leo-PL** [comment]
Nice to know that. I plan on porting OpenWrt to Synology DS211j (as DSM 6 is such a bloat...), so this information might come in handy.
Anyway, I'd also appreciate your patch :)

**Comment by chunkeey** [comment]
Alright, I merge it. Thanks.

**Comment by bobafetthotmail** [comment]
thank you

**Pull request closed without merging**
