### PR TITLE
toolchain: enable zstd

### PR DESCRIPTION
**Pull request by neheb**
The binutils change is noop until 2.40 (2.39 is default)

The GCC change works only on lightweight systems. On some, there's some problem where it causes issues during LTO.

ping @dhewg @anomeome

### CODE REVIEW

**Comment by dhewg** [comment]
Thanks, but the zstd patch was updated (direct path to .a), which may be the only way to force it to use exactly that (adding -L in the mix breaks different stuff)

**Comment by neheb** [comment]
Done.

**Comment by neheb** [comment]
@anomeome so is this OK or does ccache need wiping?

**Comment by anomeome** [comment]
ccache needs to be wiped whether moving forward to including zstd PR, or backing PR out. My last build log in the _other_ thread was with my ccache having been built with this PR, then trying another build with PR backed out.

**Comment by neheb** [comment]
In that case, setting as ready

**Comment by mpratt14** [comment]
consider bumping that file toolchain/build_version and adding to the toolchain_clean script a way to clear ccache

**Comment by robimarko** [comment]
Now that Binutils 2.40 are default, it would really make sense to merge this

**Comment by neheb** [comment]
rebased.

@hauke can we get this merged?

**Comment by Ansuel** [comment]
@neheb ok to merge or we notice some problems?

**Comment by neheb** [comment]
OK to merge

**Comment by Ansuel** [comment]
@neheb @mpratt14 btw i wonder if the ccache problem might be solvable with some kind of stamp that register the current tools state? And wiped when they are changed? Would be easier than creating an entire infrastructure to wipe ccache when needed?

**Comment by mpratt14** [comment]
in my opinion we just need to add lines to the script 

https://github.com/openwrt/openwrt/blob/master/scripts/check-toolchain-clean.sh

and maybe have a similar script for tools

unless a makefile only solution can be done

**Comment by hauke** [comment]
I think this broke building valgrind, see here for details: https://github.com/openwrt/openwrt/actions/workflows/packages.yml?query=branch%3Amaster

We hit now an internal compiler error in the github CI:
````
ccache mips-openwrt-linux-musl-gcc -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-signedness -Wformat-security -Wignored-qualifiers -Wmissing-parameter-type -Wlogical-op -Wenum-conversion -Wimplicit-fallthrough=2 -Wold-style-declaration -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin   -flto -flto-partition=one -fuse-linker-plugin  -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -msoft-float  -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-signedness -Wformat-security -Wignored-qualifiers -Wmissing-parameter-type -Wlogical-op -Wenum-conversion -Wimplicit-fallthrough=2 -Wold-style-declaration -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin       -L/__w/openwrt/openwrt/openwrt/openwrt-toolchain-malta-be_gcc-12.2.0_musl.Linux-x86_64/toolchain-mips_24kc_gcc-12.2.0_musl/usr/lib -L/__w/openwrt/openwrt/openwrt/openwrt-toolchain-malta-be_gcc-12.2.0_musl.Linux-x86_64/toolchain-mips_24kc_gcc-12.2.0_musl/lib -znow -zrelro  -o valgrind valgrind-launcher-linux.o valgrind-m_debuglog.o  
lto1: internal compiler error: original not compressed with zstd
0x1347ee6 internal_error(char const*, ...)
	???:0
0x937588 lto_end_uncompression(lto_compression_stream*, lto_compression)
	???:0
0x935fa0 lto_get_section_data(lto_file_decl_data*, lto_section_type, char const*, int, unsigned long*, bool)
	???:0
0x671e97 cgraph_node::get_untransformed_body()
	???:0
0x67d770 cgraph_node::expand()
	???:0
0x5f0791 lto_main()
	???:0
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <http://bugs.openwrt.org/> for instructions.
lto-wrapper: fatal error: mips-openwrt-linux-musl-gcc.bin returned 1 exit status
compilation terminated.
/__w/openwrt/openwrt/openwrt/openwrt-toolchain-malta-be_gcc-12.2.0_musl.Linux-x86_64/toolchain-mips_24kc_gcc-12.2.0_musl/bin/../lib/gcc/mips-openwrt-linux-musl/12.2.0/../../../../mips-openwrt-linux-musl/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[7]: *** [Makefile:3460: valgrind] Error 1
make[7]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/valgrind-3.20.0/coregrind'
make[6]: *** [Makefile:2474: all] Error 2
make[6]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/valgrind-3.20.0/coregrind'
make[5]: *** [Makefile:899: all-recursive] Error 1
make[5]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/valgrind-3.20.0'
make[4]: *** [Makefile:762: all] Error 2
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/valgrind-3.20.0'
make[3]: *** [Makefile:200: /__w/openwrt/openwrt/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/valgrind-3.20.0/.built] Error 2
time: package/devel/valgrind/compile#20.87#4.04#26.82
````

**Comment by Ansuel** [comment]
We need to wait a bit for cache to be wiped.
It's a known problem with cache not detecting the different config

Il Sab 18 Mar 2023, 13:06 Hauke Mehrtens ***@***.***> ha
scritto:

**Comment by mpratt14** [comment]
have we fully explored the configuration of ccache? I looked at the manual really quick and there are several modes that affect the sensitivity of whether a specific compilation gets labeled a cache hit or a cache miss and gets recompiled

**Comment by neheb** [comment]
would https://github.com/openwrt/openwrt/pull/12196 help?

**Comment by hauke** [comment]
I manually deleted the github ccache and re triggered the failed builds. Not it is passing again.

**Pull request merged**
