### PR TITLE
iperf3: update to 3.4

### PR DESCRIPTION
**Pull request by pprindeville**
Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by pprindeville** [comment]
Most of the patches have been accepted upstream other than the endianness fix, and hence are going away.

**Comment by pprindeville** [comment]
@pepe2k Please add @nbd168 as the maintainer/reviewer.

**Comment by hauke** [comment]
Thank you for the patch it was applied to master

**Comment by pprindeville** [comment]
Thanks!

**Pull request closed without merging**
