### PR TITLE
omap: kernel update and switch to 4.14

### PR DESCRIPTION
**Pull request by lucize**
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>
Maintainer: @lynxis 

Tested on beaglebone black

### CODE REVIEW

**Comment by commodo** [comment]
[curios] does 4.14 include `001-omap4_pandaboard-wlan_fix.patch` ?
it seems to be part of the 4.4 and 4.9 `patches` folder

**Comment by lucize** [comment]
that file disappeared between versions and I don't own a board to see if this is needed anymore
searched for a commit regarding to that patch and couldn't find one

**Comment by lynxis** [comment]
Looks good so far. I'm starting a build test now, but can do the hardware testing on Sunday.

**Review by lynxis — APPROVED** [review]

**Comment by lynxis** [comment]
Sorry for the delay. I'm still working on this. I want to have a least a booting test for this.  Might take one or two days.

**Comment by lynxis** [comment]
merged.

**Pull request closed without merging**
