### PR TITLE
Kernel: add packages for common USB DVB adapters (v2)

### PR DESCRIPTION
**Pull request by ghost**
DVB drivers are intended to be used with tvheadend package and easily available Astrometa USB DVB/analog tuners. More adapters can be added in the future. This allows users to record and stream TV programs from DVB networks to tvheadend clients.

Major changes:
- Add new kernel module category: Multimedia
- Moved video cameras from Video to Multimedia. Video menu will contain only output devices.
- Add packages for these kernel modules:
  - Multimedia support
  - DVB USB (installs dvb-core and dvb-usb-v2)
  - Realtek RTL28xxU, RTL2830, RTL2832
  - Rafael Micro R820T
  - Panasonic MN88472 (no firmware)
  - Panasonic MN88473 (no firmware)
  - Sony CXD2841ER

Minor changes:
- USB audio needed a dependecy on kmod-multimedia, when kmod-multimedia is also selected.
- New required kernel config options were added for both kernel versions.
- v2 of this PR fixes a bug in module load order that prevented the detection of DVB adapters that were already present during boot.

### CODE REVIEW

**Comment by Lucky1openwrt** [comment]
compiled this for an EA4500 with USB RTL2832
failed to compile when only DBVBRTL28XXU driver selected
when selected all USB DVB drivers selected it compiles successfully

currently working added 2nd RTL2832 via usb hub
and sharing TV to a few of my Kodi devices & phone
only using and tested for viewing DVB tv
works well so for 1 day up :)

**Comment by M95D** [comment]
I can't reproduce this. Please post the build error from the log.

**Comment by Lucky1openwrt** [comment]
from make V=sc 
```
+ bash ./scripts/mksysmap .tmp_vmlinux.kallsyms2 .tmp_System.map
+ cmp -s System.map .tmp_System.map
+ on_exit
+ '[' 0 -ne 0 ']'
make -f ./scripts/Makefile.build obj=arch/arm/boot MACHINE= arch/arm/boot/Image
  arm-openwrt-linux-muslgnueabi-objcopy -O binary -R .comment -S  vmlinux arch/arm/boot/Image
make -f ./scripts/Makefile.build obj=arch/arm/boot MACHINE= arch/arm/boot/zImage
make -f ./scripts/Makefile.build obj=arch/arm/boot/compressed arch/arm/boot/compressed/vmlinux
  { cat arch/arm/boot/compressed/../Image | sh ./scripts/xz_wrap.sh; printf \100\300\250\000; } > arch/arm/boot/compressed/piggy_data
  arm-openwrt-linux-muslgnueabi-gcc -Wp,-MMD,arch/arm/boot/compressed/.piggy.o.d  -nostdinc -isystem /home/lucky/dvb/staging_dir/toolchain-arm_xscale_gcc-12.2.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/12.2.0/include -I./arch/arm/include -I./arch/arm/include/generated  -I./include -I./arch/arm/include/uapi -I./arch/arm/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -fmacro-prefix-map=./= -D__ASSEMBLY__ -fno-PIE -mabi=aapcs-linux -mfpu=vfp -funwind-tables -marm -Wa,-mno-warn-deprecated -D__LINUX_ARM_ARCH__=5 -march=armv5te -mtune=xscale -include asm/unified.h -msoft-float -Wa,-gdwarf-2 -DZIMAGE    -c -o arch/arm/boot/compressed/piggy.o arch/arm/boot/compressed/piggy.S
  arm-openwrt-linux-muslgnueabi-ld  -EL -z noexecstack --no-warn-rwx-segments   --defsym _kernel_bss_size=211968 --no-undefined -X --orphan-handling=warn -T arch/arm/boot/compressed/vmlinux.lds arch/arm/boot/compressed/head.o arch/arm/boot/compressed/piggy.o arch/arm/boot/compressed/misc.o arch/arm/boot/compressed/decompress.o arch/arm/boot/compressed/string.o arch/arm/boot/compressed/fdt_rw.o arch/arm/boot/compressed/fdt_ro.o arch/arm/boot/compressed/fdt_wip.o arch/arm/boot/compressed/fdt.o arch/arm/boot/compressed/atags_to_fdt.o arch/arm/boot/compressed/lib1funcs.o arch/arm/boot/compressed/ashldi3.o arch/arm/boot/compressed/bswapsdi2.o -o arch/arm/boot/compressed/vmlinux
  arm-openwrt-linux-muslgnueabi-objcopy -O binary -R .comment -S  arch/arm/boot/compressed/vmlinux arch/arm/boot/zImage
make -f ./scripts/Makefile.build obj=arch/arm/boot/dts
bash ./scripts/modules-check.sh modules.order
make -f ./scripts/Makefile.build obj=scripts scripts/module.lds
make -f ./scripts/Makefile.modpost
  sed 's/ko$/o/' modules.order | scripts/mod/modpost     -o modules-only.symvers -i vmlinux.symvers   -T -
ERROR: modpost: "__regmap_init_i2c" [drivers/media/dvb-frontends/rtl2832.ko] undefined!
make[6]: *** [scripts/Makefile.modpost:123: modules-only.symvers] Error 1
make[6]: *** Deleting file 'modules-only.symvers'
make[5]: *** [Makefile:1747: modules] Error 2
make[5]: Leaving directory '/home/lucky/dvb/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood_generic/linux-5.10.168'
make[4]: *** [Makefile:24: /home/lucky/dvb/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood_generic/linux-5.10.168/.modules] Error 2
make[4]: Leaving directory '/home/lucky/dvb/target/linux/kirkwood'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/lucky/dvb/target/linux'
time: target/linux/compile#10.04#2.62#12.45
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/home/lucky/dvb'
make[1]: *** [target/Makefile:23: /home/lucky/dvb/staging_dir/target-arm_xscale_musl_eabi/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/lucky/dvb'
make: *** [/home/lucky/dvb/include/toplevel.mk:231: world] Error 2
lucky@6700K:~/dvb$
```

**Comment by Lucky1openwrt** [comment]
image

**Comment by M95D** [comment]
But you must clean the kernel if you change the config!
```make target/linux/clean```

Your error is not with other dvb modules, it's because i2c-mux is missing, previously required by panasonic modules, which are not selected anymore, but you didn't clean it and rtl2832 is still configured as if panasonic are present.

I'll try to see if rtl2832 has some missing dependencies and can be loaded independently of panasonic modules.

**Comment by Lucky1openwrt** [comment]
just saying whether I clean or not results are the same
but yes seems to need at lest one of the 2 panasonic modules with it to compile
anyway these are just observations all still working fine via my kodi pc;'s :)

**Comment by Lucky1openwrt** [comment]
If I remove "kmod-regmap-i2c" from DEPENDS:=+
it compile with out error but in the log after running
`Sun Mar 12 21:56:21 2023 kern.info kernel: [   66.391613] usb 1-2: USB disconnect, device number 2
Sun Mar 12 21:56:23 2023 kern.info kernel: [   67.956354] usb 1-2: new high-speed USB device number 3 using xhci-mtk
Sun Mar 12 21:56:23 2023 kern.info kernel: [   68.168496] usb 1-2: dvb_usb_v2: found a 'Realtek RTL2832U reference design' in warm state
Sun Mar 12 21:56:23 2023 kern.info kernel: [   68.242204] usb 1-2: dvb_usb_v2: will pass the complete MPEG2 transport stream to the software demuxer
Sun Mar 12 21:56:23 2023 kern.info kernel: [   68.260968] dvbdev: DVB: registering new adapter (Realtek RTL2832U reference design)
Sun Mar 12 21:56:23 2023 kern.info kernel: [   68.296910] i2c i2c-0: Added multiplexed i2c bus 1
Sun Mar 12 21:56:23 2023 kern.info kernel: [   68.306572] rtl2832 0-0010: Realtek RTL2832 successfully attached
Sun Mar 12 21:56:23 2023 kern.info kernel: [   68.318949] usb 1-2: DVB: registering adapter 0 frontend 0 (Realtek RTL2832 (DVB-T))...
Sun Mar 12 21:56:23 2023 kern.err kernel: [   68.352963] DVB: Unable to find symbol r820t_attach()`

so it seems to need "kmod-dvb-tuner-r820t"
and if you add this as well it all works 
so it seems you have to remove kmod-regmap-i2c & add kmod-dvb-tuner-r820t
under define KernelPackage/dvb-usb-rtl28xx
`  DEPENDS:=+kmod-dvb-tuner-r820t kmod-dvb-usb-v2`

**Comment by M95D** [comment]
I tried it again, building each module separately and it builds just fine without any error, including that exact selection from the screenshot you posted. I simply can't reproduce your build error.
If you want me to test further, I'll need your config file and any modifications you might have made to the kernel config (target/linux/<arch>/<cpu>/config-5.xx).

Did anyone else tried/tested this PR? Does it work on your systems?

About loading the modules:
Indeed you are correct. On my system r820t module must be loaded for dvb to work properly. Without it, the frontends (cxd and rtl) won't show up in /dev/dvb/adapterX/. The r820t can be loaded after rtl28xx, but the dvb adapter must be disconnected and reconnected to start working.
So, in my opinion r820t is not a hard dependency of rtl28xx, because rtl28xx can be loaded independently without any error if the dvb adapter is not connected. The symbol error appears only when the dvb adapter is connected, which means r820t must be a requirement of that specific adapter that was connected.
I also tried to connect an older adapter that I have, with Panasonic MN88472 instead of the Sony CXD, without having the Panasonic module loaded. The rtl28xx module detected the device correctly, without any error related to the missing panasonic frontend (the frontend was simply not detected).

**Comment by Lucky1openwrt** [comment]
here is the info but happy to wait for others also

the error I post was reproduced by unplugging & plunging back in the rtl28xx
I'm not 100% sure but don't think it work after 

didn't make any changes to config-5xx files that are as they came from your github

[DVB.txt](https://github.com/openwrt/openwrt/files/10976123/DVB.txt)
[config.txt](https://github.com/openwrt/openwrt/files/10976135/config.txt)

**Comment by M95D** [comment]
It's true. With your config file, it doesn't compile, even though i2c_regmap is properly selected.
Searching the net I found this patch: https://www.spinics.net/lists/linux-media/msg182489.html
So, it's probably a kernel bug. I'll try to include that patch.

I'm going to clean out dependencies a bit too.

**Comment by M95D** [comment]
Try it now: https://github.com/openwrt/openwrt/pull/12210

**Comment by Lucky1openwrt** [comment]
on a Netgear 6220 compiles fine now
but won't work with the error "DVB: Unable to find symbol r820t_attach()"
until I include "kmod-dvb-tuner-r820t" 
on then the RTL2832  shows up in tvheadend

**Pull request closed without merging**
