### PR TITLE
toolchain/musl: update to 1.2.4

### PR DESCRIPTION
**Pull request by misaka36**
Release notes:

new features:
- large dns record lookups via tcp fallback
- new getaddrinfo EAI_NODATA result to distinguish NODATA/NxDomain
- support for new RELR compressed format for relative relocations
- sysconf keys for querying signal stack size requirements
- real vfork on riscv64

performance:
- mallocng no longer uses MADV_FREE (high performance cost, little gain)
- vdso clock_gettime is supported once again on 32-bit arm

compatibility:
- gethostbyname family now distinguishes NO_DATA from HOST_NOT_FOUND
- res_send now works with caller-provided edns0 queries
- arpa/nameser.h RR types list is now up-to-date
- previously-missing POSIX confstr keys have been added
- mntent interfaces now accept missing fields
- alt signal stack, if any, is now used for internal signals
- the LFS64 macros are no longer exposed without _LARGEFILE64_SOURCE
- memmem (POSIX-future) is now exposed in default feature profile
- pthread_atfork now admits calls from an application-provided malloc
- debugger tracking of shared libraries now works on MIPS PIE binaries
- sendmsg now supports up to SCM_MAX_FD fds in SCM_RIGHTS messages

bugs fixed:
- gethostbyname[2]_r wrongly returned nonzero (error) on negative result
- parallel v4/v6 address queries could fail on query id collisions
- spurious getaddrinfo/AI_ADDRCONFIG failures due to errno clobbering
- dns search domains ending in dot (including lone dot) broke lookups
- ipv6 servers in resolv.conf broke lookups on systems with v6 disabled
- systems with bindv6only failed to query both v4 and v6 nameservers
- res_mkquery mishandled consecutive final dots in name
- res_send could malfunction for very small answer buffer sizes
- resolver dns backend accepted answers with wrong (A vs AAAA) RR type
- getservbyport_r returned junk or ENOENT (vs ERANGE) on buffer size errors
- dns result parsing of malformed responses could process uninitialized data
- freopen didn't reset stream orientation (byte/wide) & encoding rule
- fwprintf didn't print most fields on open_wmemstream FILEs
- wide printf %lc ignored field width
- wide printf erroneously processed %n after encoding errors
- use of wide printf %9$ argument slot overflowed undersized buffer
- swprintf malfunctioned on nul character in output
- strverscmp ordered digit sequences vs nondigits incorrectly
- timer_create/SIGEV_THREAD failure leaked the thread
- semaphores were subject to missed-wake under certain usage patterns
- several possible rare deadlocks with lock handling at thread exit
- several possible rare deadlocks with aio and multithreaded fork
- dynamic linker relro processing was broken on archs w/variable pagesize
- async cancellation could run cancellation handlers in invalid context
- pthread_detach was wrongly a cancellation point in rare race code path
- use-after-close/double-close errors in mq_notify error paths
- mq_notify event thread wrongly ran with signals unmasked
- wcs{,n}cmp, wmemcmp returned wrong results when difference overflowed
- accept4, pipe2, and dup3 handled unknown flags wrong in fallback cases
- CPU_SETSIZE macro had wrong unit
- select fallback for pre-time64 kernels truncated timeout (vs clamping)

arch-specific bugs fixed:
- x32 new socketcalls took fallback path due to pointer sign extension
- x32 wait4 didn't fill rusage structure (time64 regression)
- x32 semtimedop mismatched timespec ABI with kernel (time64 regression)
- sigaction signal mask was bogus on or1k, microblaze, mips, and riscv
- powerpc-sf longjmp asm clobbered value argument
- or1k poll function passed timeout to syscall in wrong form

Removed upstreamed:
- 800-mips_pie_debug.patch

Manually rebased:
- 600-nftw-support-common-gnu-extension.patch

### CODE REVIEW

**Comment by xback** [comment]
Did you do a full compile test?
I also made this patch last week and noticed a linux tool that had a build issue with this bump.

**Comment by lovehackintosh** [comment]
Yes. https://github.com/lovehackintosh/openwrt/actions/runs/4906138517
libbsd had a build issue. That’s why I marked it as a draft.

**Comment by xback** [comment]
Thanks, but I recall it was another tool.
I'll provide detailed info tomorrow when I'm in the office.

**Comment by xback** [comment]
Here it is:

```
selinux_restorecon.c: In function 'filespec_add':
selinux_restorecon.c:425:23: error: storage size of 'sb' isn't known
  425 |         struct stat64 sb;
      |                       ^~
selinux_restorecon.c:438:31: warning: implicit declaration of function 'lstat64'; did you mean 'lstat'? [-Wimplicit-function-declaration]
  438 |                         ret = lstat64(fl->file, &sb);
      |                               ^~~~~~~
      |                               lstat
make[5]: *** [Makefile:167: selinux_restorecon.o] Error 1
make[5]: Leaving directory '/home/koen/firmware/builds/generic_rb922/build_dir/target-mips_24kc_musl/libselinux-3.3/src'
make[4]: *** [Makefile:48: all] Error 1
make[4]: Leaving directory '/home/koen/firmware/builds/generic_rb922/build_dir/target-mips_24kc_musl/libselinux-3.3'
make[3]: *** [Makefile:161: /home/koen/firmware/builds/generic_rb922/build_dir/target-mips_24kc_musl/libselinux-3.3/.built] Error 2
make[3]: Leaving directory '/home/koen/firmware/builds/generic_rb922/package/libs/libselinux'
time: package/libs/libselinux/compile#0.16#0.01#0.16
    ERROR: package/libs/libselinux failed to build.
make[2]: *** [package/Makefile:116: package/libs/libselinux/compile] Error 1
make[2]: Leaving directory '/home/koen/firmware/builds/generic_rb922'
make[1]: *** [package/Makefile:110: /home/koen/firmware/builds/generic_rb922/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/koen/firmware/builds/generic_rb922'
make: *** [/home/koen/firmware/builds/generic_rb922/include/toplevel.mk:231: world] Error 2
```

**Comment by robimarko** [comment]
@xback
`On the API level, the legacy "LFS64" ("large file support") interfaces, which were provided by macros remapping them to their standard names (#define stat64 stat and similar) have been deprecated and are no longer provided under the _GNU_SOURCE feature profile, only under explicit _LARGEFILE64_SOURCE. The latter will also be removed in a future version. Builds broken by this change can be fixed short-term by adding -D_LARGEFILE64_SOURCE to CFLAGS, but should be fixed to use the standard interfaces.`

So, `_LARGEFILE64_SOURCE` needs to be defined.

**Comment by PolynomialDivision** [comment]
It would also be nice if someone could bump selinux to the new versions.

**Comment by bittorf** [comment]
please change version number in title:  
it is NOT "update to 1.24" but "update to 1.2.4"  
Thanks for your work!

**Comment by lovehackintosh** [comment]
@robimarko Thank you for your patch. I applied it.
@bittorf Changed it, thank you.

**Comment by hauke** [comment]
Is this problem already fixed upstream in selinux? If not id you report it?

**Comment by robimarko** [comment]
@hauke `LFS64` is still used upstream and I dont see an bug report as with glibc it will compile just fine.

**Comment by Ansuel** [comment]
@lovehackintosh @robimarko still draft or the problem got fixed?

**Comment by robimarko** [comment]
Its fixed now, second commit in the PR fixes selinux

**Comment by 1715173329** [comment]
```
making all in lib/ext2fs
make[5]: Entering directory '/mnt/disk/master/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/e2fsprogs-1.47.0/lib/ext2fs'
	CC bb_compat.c
	CC inode_io.c
	CC write_bb_file.c
	CC dupfs.c
	CC imager.c
	CC ext2_err.c
	CC alloc.c
	CC alloc_sb.c
	CC alloc_stats.c
	CC alloc_tables.c
	CC atexit.c
	CC badblocks.c
	CC bb_inode.c
	CC bitmaps.c
	CC bitops.c
	CC blkmap64_ba.c
	CC blkmap64_rb.c
	CC blknum.c
	CC block.c
	CC bmap.c
	CC check_desc.c
	CC closefs.c
	CC crc16.c
	GEN32CTABLE crc32c_table.h
	CC crc32c.c
	CC llseek.c
llseek.c:70:22: error: expected declaration specifiers or '...' before '_llseek'
   70 | static _syscall5(int,_llseek,unsigned int,fd,unsigned long,offset_high,
      |                      ^~~~~~~
llseek.c:70:43: error: unknown type name 'fd'
   70 | static _syscall5(int,_llseek,unsigned int,fd,unsigned long,offset_high,
      |                                           ^~
llseek.c:70:60: error: unknown type name 'offset_high'
   70 | static _syscall5(int,_llseek,unsigned int,fd,unsigned long,offset_high,
      |                                                            ^~~~~~~~~~~
llseek.c:71:33: error: unknown type name 'offset_low'; did you mean 'offsetof'?
   71 |                  unsigned long, offset_low,ext2_loff_t *,result,
      |                                 ^~~~~~~~~~
      |                                 offsetof
llseek.c:71:58: error: unknown type name 'result'
   71 |                  unsigned long, offset_low,ext2_loff_t *,result,
      |                                                          ^~~~~~
llseek.c:72:32: error: unknown type name 'origin'
   72 |                  unsigned int, origin);
      |                                ^~~~~~
llseek.c:67:12: warning: '_llseek' used but never defined
   67 | static int _llseek (unsigned int, unsigned long,
      |            ^~~~~~~
make[5]: *** [Makefile:693: llseek.o] Error 1
make[5]: Leaving directory '/mnt/disk/master/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/e2fsprogs-1.47.0/lib/ext2fs'
make[4]: *** [Makefile:456: all-libs-recursive] Error 1
make[4]: Leaving directory '/mnt/disk/master/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/e2fsprogs-1.47.0'
make[3]: *** [Makefile:371: all] Error 2
make[3]: Leaving directory '/mnt/disk/master/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/e2fsprogs-1.47.0'
make[2]: *** [Makefile:319: /mnt/disk/master/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/e2fsprogs-1.47.0/.built] Error 2
make[2]: Leaving directory '/mnt/disk/master/package/utils/e2fsprogs'
time: package/utils/e2fsprogs/compile#2.01#0.37#2.24
    ERROR: package/utils/e2fsprogs failed to build.
make[1]: *** [package/Makefile:120: package/utils/e2fsprogs/compile] Error 1
make[1]: Leaving directory '/mnt/disk/master'
make: *** [/mnt/disk/master/include/toplevel.mk:231: package/compile] Error 2
```

looks like e2fsprogs exploded due to this update

**Comment by robimarko** [comment]
Did you rebuild the toolchain?

Cause, e2fsprogs is building just fine for me

**Comment by 1715173329** [comment]
> Did you rebuild the toolchain?

yep, i did clean up everything.
alpine also added the flag https://git.alpinelinux.org/aports/commit/main/e2fsprogs/APKBUILD?id=1316b68e9bb502e94953f61c7e16fa73771b0b93

**Comment by robimarko** [comment]
Hm, its rather weird that its compiling for me, `f2fs-tools` do require LFS64 to be reenabled though.

**Comment by 1715173329** [comment]
> Hm, its rather weird that its compiling for me

hmmmm looks like it only fails for arm32

**Comment by robimarko** [comment]
@hauke It needs `TARGET_CFLAGS += -D_LARGEFILE64_SOURCE` as well

**Comment by 1715173329** [comment]
> `f2fs-tools` have some kind of a clash with `fortify-headers` which makes no sense as `f2fs-tools` correctly use `#define _LARGEFILE64_SOURCE`

from configuare script output:
> checking for lseek64... no

https://git.kernel.org/pub/scm/linux/kernel/git/jaegeuk/f2fs-tools.git/tree/lib/libf2fs_io.c#n70
looks like it just failed to detect lseek64 function and redefined it

**Comment by 1715173329** [comment]
not sure how many packages are/will be exploded, this shouldn't be merged before branching off...

**Comment by 1715173329** [comment]
https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a53/packages/
looks awesome

**Pull request merged**
