### PR TITLE
qoriq: switch to Linux  6.6

### PR DESCRIPTION
**Pull request by namiltd**
Switch to Linux kernel version 6.6 and drop config for Linux 6.1.

### CODE REVIEW

**Comment by stintel** [comment]
Someone should run 6.6 for at least a month without any apparent issues before I'm willing to merge this.

**Comment by RussellSenior** [comment]
I've been running b01f4bed9c333b28e9dc1d066e0dc365ca088c56 on an M300 in a test bed since late August on 6.6.47. It's mostly idle, but no apparent problems.

**Comment by namiltd** [comment]
Ping @stinel

**Comment by stintel** [comment]
I've moved my M300s to my primary location and will be test driving this with 6.6 as of today. I'll give it two weeks. Feel free to ping me then, if I have not merged this PR or dropped the qoriq target by then.

**Comment by stintel** [comment]
My entire network just died after flashing an image with 6.6. I do not have the time to debug this right now, so unfortunately this PR is going to have to wait.

**Pull request merged**
