### PR TITLE
ath25: switch to 5.10 Kernel

### PR DESCRIPTION
**Pull request by aparcar**
This is just to have a place to share test results.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by hauke** [comment]
Could anyone please test the ath25 target with kernel and report back if it works.
At least it is building fine for me, it could be that some images are now getting too big.

**Comment by 981213** [comment]
I have to build with wpad-mini and without IPv6/SSL/Firewall to get a firmware under 4M. (sysupgrade from this build is 3473408 bytes :P)
Tested on D-Link DIR-300 with 32M memory mod. It boots. wifi and ethernet seem to be working just fine. I can't really do any further pratical tests as this build doesn't have a firewall. Consider the fact that it took about 1.5 min to boot I think it's impratical to use it nowadays anyway.

Tested-by: Chuanhong Guo <gch981213@gmail.com>

Serial log attached below:
```
U-Boot 1.1.4 (Apr  4 2016 - 10:24:14)

AP61 (AR2317) U-Boot
DRAM:  32 MB
Flash: Winbond W25X32 (4 MB)
Using default environment

Clocks: CPU:230MHz, SDR:230MHz, AMBA:115MHz, Ref:40MHz
In:    serial
Out:   serial
Err:   serial
Net:   ae531x_enet_initialize...
Fetching MAC Address from Flash 0x003f0066
IC Plus IP175C PHY attached.
eth0: 00:1e:58:c5:24:da
eth0 up
eth0
Hit any key to stop autoboot:  0 
## Booting image at bfc30000 ...
   Image Name:   AR231X/AR5312 Linux Kernel Image
   Created:      1970-01-01   0:00:00 UTC
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    3788800 Bytes =  3.6 MB
   Load Address: 80041000
   Entry Point:  80041000
   Uncompressing Kernel Image ... OK
[    0.000000] Linux version 5.10.96 (user@guoguo-omen) (mips-openwrt-linux-musl-gcc (OpenWrt GCC 11.2.0 r18647+130-17135ae091) 11.2.0, GNU ld (GNU Binutils) 2.37) #0 Tue Feb 8 22:46:21 2022
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019064 (MIPS 4KEc)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 16kB, VIPT, 4-way, linesize 16 bytes.
[    0.000000] Primary data cache 16kB, 4-way, VIPT, no aliases, linesize 16 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000001ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000001ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000001ffffff]
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 8128
[    0.000000] Kernel command line: console=ttyS0,9600 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.000000] Inode-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 27592K/32768K available (3442K kernel code, 568K rwdata, 488K rodata, 160K init, 182K bss, 5176K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 256
[    0.000000] random: get_random_bytes called from 0x804a8a88 with crng_init=0
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 16619656060 ns
[    0.000054] sched_clock: 32 bits at 115MHz, resolution 8ns, wraps every 18673770491ns
[    0.094150] Calibrating delay loop... 228.55 BogoMIPS (lpj=1142784)
[    0.238646] pid_max: default: 32768 minimum: 301
[    0.294641] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.381544] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.482529] dyndbg: Ignore empty _ddebug table in a CONFIG_DYNAMIC_DEBUG_CORE build
[    0.576508] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.693696] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.777144] NET: Registered protocol family 16
[    0.979350] clocksource: Switched to clocksource MIPS
[    1.045946] NET: Registered protocol family 2
[    1.098315] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    1.187071] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    1.286656] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    1.378368] TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    1.462661] TCP: Hash tables configured (established 1024 bind 1024)
[    1.539713] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    1.617389] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    1.701732] NET: Registered protocol family 1
[    1.753475] PCI: CLS 0 bytes, default 16
[    1.841295] Radio config found at offset 0xf8 (0x1f8)
[    1.938085] workingset: timestamp_bits=30 max_order=13 bucket_order=0
[    2.040965] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    2.110180] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    2.232771] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    2.309063] serial8250: ttyS0 at MMIO 0x11100000 (irq = 9, base_baud = 7187500) is a 16550A
[    2.408805] printk: console [ttyS0] enabled
[    2.408805] printk: console [ttyS0] enabled
[    2.508673] printk: bootconsole [early0] disabled
[    2.508673] printk: bootconsole [early0] disabled
[    2.626396] ar2315-spiflash ar2315-spiflash.0: 4096 Kbytes flash detected
[    2.726087] Searching for RedBoot partition table in spiflash at offset 0x3d0000
[    2.856086] 6 RedBoot partitions found on MTD device spiflash
[    2.925354] Creating 6 MTD partitions on "spiflash":
[    2.985233] 0x000000000000-0x000000030000 : "RedBoot"
[    3.054708] 0x000000030000-0x000000190000 : "vmlinux.bin.l7"
[    3.131808] 0x000000190000-0x0000003d0000 : "rootfs"
[    3.195272] mtd: device 2 (rootfs) set to be root filesystem
[    3.263645] 1 squashfs-split partitions found on MTD device rootfs
[    3.338167] 0x000000370000-0x0000003d0000 : "rootfs_data"
[    3.414569] 0x0000003d0000-0x0000003df000 : "FIS directory"
[    3.481802] mtd: partition "FIS directory" doesn't end on an erase/write block -- force read-only
[    3.597320] 0x0000003df000-0x0000003e0000 : "RedBoot config"
[    3.665607] mtd: partition "RedBoot config" doesn't start on an erase/write block boundary -- force read-only
[    3.793652] 0x0000003e0000-0x000000400000 : "boardconfig"
[    3.955024] eth0: Atheros AR231x: 00:1e:58:c5:24:da, irq 4
[    4.131192] IP17xx: Found IP175C at 0:00
[    4.403992] eth0: attached PHY driver [IC+ IP17xx] (mii_bus:phy_addr=0:00)
[    4.493345] NET: Registered protocol family 17
[    4.547331] 8021q: 802.1Q VLAN Support v1.8
[    4.642300] VFS: Mounted root (squashfs filesystem) readonly on device 31:2.
[    4.728554] Freeing unused kernel memory: 160K
[    4.782177] This architecture does not have kernel memory protection.
[    4.859807] Run /sbin/init as init process
[    5.989435] random: fast init done
[    6.374330] init: Console is alive
[    6.417844] init: - watchdog -
[    7.684675] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    7.847527] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    7.946846] init: - preinit -
[    9.790524] eth0: link up (100Mbps/full duplex)
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[   14.596695] jffs2: notice: (308) jffs2_build_xattr_subsystem: complete building xattr subsystem, 14 of xdatum (0 unchecked, 7 orphan) and 17 of xref (2 dead, 6 orphan) found.
[   14.790757] mount_root: switching to jffs2 overlay
[   14.859238] overlayfs: upper fs does not support tmpfile.
[   14.962123] urandom-seed: Seeding with /etc/urandom.seed
[   15.296465] procd: - early -
[   15.333890] procd: - watchdog -
[   16.387759] procd: - watchdog -
[   16.488684] procd: - ubus -
[   16.637933] random: ubusd: uninitialized urandom read (4 bytes read)
[   16.727484] random: ubusd: uninitialized urandom read (4 bytes read)
[   16.806998] random: ubusd: uninitialized urandom read (4 bytes read)
[   16.908205] procd: - init -
Please press Enter to activate this console.
[   20.394302] kmodloader: loading kernel modules from /etc/modules.d/*
[   23.120483] urngd: v1.0.2 started.
[   23.913071] Loading modules backported from Linux version v5.15.8-0-g43e577d7a2cb
[   24.003314] Backport generated by backports.git v5.15.8-1-0-g83f664bb
[   24.206697] random: crng init done
[   24.248024] random: 7 urandom warning(s) missed due to ratelimiting
[   25.319190] PPP generic driver version 2.4.2
[   25.463310] NET: Registered protocol family 24
[   25.664362] ath5k: phy0: Atheros AR2317 chip found (MAC: 0x90, PHY: 0x48)
[   26.030989] kmodloader: done loading kernel modules from /etc/modules.d/*
[   66.398109] eth0: link down
[   66.725871] eth0: link up (100Mbps/full duplex)
[   66.835286] br-lan: port 1(eth0.1) entered blocking state
[   66.900419] br-lan: port 1(eth0.1) entered disabled state
[   66.967135] device eth0.1 entered promiscuous mode
[   67.025010] device eth0 entered promiscuous mode
[   67.474856] br-lan: port 1(eth0.1) entered blocking state
[   67.539989] br-lan: port 1(eth0.1) entered forwarding state
[   80.258270] br-lan: port 2(wlan0) entered blocking state
[   80.323043] br-lan: port 2(wlan0) entered disabled state
[   80.389927] device wlan0 entered promiscuous mode
[   81.234674] br-lan: port 2(wlan0) entered blocking state
[   81.298795] br-lan: port 2(wlan0) entered forwarding state
```

**Comment by aparcar** [comment]
You closed this but didn't actually merge it, do you want to declare the target dead or should I merge it?

**Comment by 981213** [comment]
> You closed this but didn't actually merge it, do you want to declare the target dead or should I merge it?

You can go ahead and merge it.

I think we can keep this target alive until someone comes with a bug report, or nobody wants to do a kernel bump for it. :)

**Comment by aparcar** [comment]
Oh sorry my bad, in my app it looked like you closed it while you just commented! I merged it thank you for testing!

**Pull request closed without merging**
