### PR TITLE
kernel: bump 5.10 to 5.10.20

### PR DESCRIPTION
**Pull request by rsalvaterra**
Removed (upstreamed) patches:
  070-net-icmp-pass-zeroed-opts-from-icmp-v6-_ndo_send-bef.patch
  081-wireguard-device-do-not-generate-ICMP-for-non-IP-pac.patch
  082-wireguard-queueing-get-rid-of-per-peer-ring-buffers.patch
  083-wireguard-kconfig-use-arm-chacha-even-with-no-neon.patch
  830-v5.12-0002-usb-serial-option-update-interface-mapping-for-ZTE-P685M.patch

Manually rebased patches:
  313-helios4-dts-status-led-alias.patch
  104-powerpc-mpc85xx-change-P2020RDB-dts-file-for-OpenWRT.patch

Run tested:
  ath79 (TL-WDR3600)
  mvebu (Turris Omnia)

EDIT: Also added a new kconfig symbol (`KCMP`) to the generic config, disabling the `SYS_kcmp` syscall by default. It was split from `CHECKPOINT_RESTORE`, which is also disabled by default, so the previous behaviour is kept.

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by Leo-PL** [comment]
If you wait for next release (or rebase), next patch for ZTE P685M could probably be dropped, Greg has queued it up for next release on my request. Same goes for 5.4

**Comment by rsalvaterra** [comment]
It's already upstreamed, that's one of the dropped patches. 😉

**Comment by Leo-PL** [comment]
No, I mean the _second_ one of two.

**Comment by rsalvaterra** [comment]
> No, I mean the _second_ one of two, affecting qmi_wwan.

Yeah, I figured right after sending. Sure, I'm fine with waiting. 🙂

**Comment by rsalvaterra** [comment]
However, do note that the 5.4 bump has already been [merged](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=196f3d586f11d96ba4ab60068cfb12420bcd20fd).

**Comment by Leo-PL** [comment]
That was quick, and a bit confusing because I see a duplicate PR for that ;-)
Anyway, I'm not holding you in any way, after all it's just dropping a backport - nothing critical.

**Comment by rsalvaterra** [comment]
> That was quick, and a bit confusing because I see a duplicate PR for that ;-)

Indeed, I was just as surprised as you!

**Comment by anomeome** [comment]
compile / test - mvebu / mamba, rango

**Comment by cybrnook** [comment]
> compile / test - mvebu / mamba, rango

@anomeome, were you able to also test wireguard?

**Comment by rsalvaterra** [comment]
> @anomeome, were you able to also test wireguard?

I did. I have three WireGuard endpoints configured, everything's working perfectly. However, I'd feel more comfortable with a cursory look from @zx2c4.

**Comment by lipnitsk** [comment]
Tested boot with Ubiquity EdgeRouter X running #3952 code.

Tested-by: Ilya Lipnitskiy <ilya.lipnitskiy@gmail.com>

**Comment by zx2c4** [comment]
> > @anomeome, were you able to also test wireguard?
> 
> I did. I have three WireGuard endpoints configured, everything's working perfectly. However, I'd feel more comfortable with a cursory look from @zx2c4.

Removing those WireGuard patches that I added is correct. I put them in the backport directory only after they'd been accepted into net.git, which means it was just a matter of time before they found their way into 5.10.

**Comment by rsalvaterra** [comment]
Ship it! 😎

**Comment by blocktrron** [comment]
Merged, thanks

**Pull request closed without merging**
