### PR TITLE
[RFT] treewide: backport support for nvmem on non platform devices

### PR DESCRIPTION
**Pull request by Ansuel**
In the current state, nvmem cells are only detected on platform device.
To quickly fix the problem, we register the affected problematic driver
with the of_platform but that is more an hack than a real solution.
Backport from net-next the required patch so that nvmem can work also
with non-platform devices and rework our current patch.
Drop the mediatek and dsa workaround and rework the ath10k patches.
Rework every driver that use the of_get_mac_address api.

This should be the correct fix for the nvmem...
I still have to test this. It's only barely compiled tested... In theory we should have time to test this...
(expect some compilation error as i have very little time and i currently have a very messy buildroot)

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by john-tho** [comment]
There are also a number of places where targets use `of_get_mac_address` in target level `patches` or `files`:
`grep --files-with-matches --recursive 'of_get_mac_address('
 $(find target/linux/ \( -path '*/pending*' -or -path '*/hack*' -or -path '*/backport*' -or -path '*/patches*' -or -path '*/files*' \) -type f -print )` or [github openwrt/openwrt search of_get_mac_address(](https://github.com/openwrt/openwrt/search?q=%22of_get_mac_address%28%22+in%3Afile):

- target/linux/ath79/files/drivers/net/ethernet/atheros/ag71xx/ag71xx_main.c
- target/linux/bcm4908/patches-5.4/074-v5.13-0001-net-broadcom-bcm4908_enet-read-MAC-from-OF.patch
- target/linux/bmips/files/arch/mips/bmips/ath9k-fixup.c
- target/linux/bmips/files/arch/mips/bmips/b43-sprom.c
- target/linux/bmips/files/drivers/net/ethernet/broadcom/bcm6368-enetsw.c
- target/linux/generic/pending-5.10/681-NET-add-of_get_mac_address_mtd.patch
- target/linux/generic/pending-5.4/681-NET-add-of_get_mac_address_mtd.patch
- target/linux/ipq40xx/files/drivers/net/ethernet/qualcomm/essedma/edma_axi.c
- target/linux/lantiq/patches-5.10/0025-NET-MIPS-lantiq-adds-xrx200-legacy.patch
- target/linux/lantiq/patches-5.10/0028-NET-lantiq-various-etop-fixes.patch
- target/linux/lantiq/patches-5.4/0025-NET-MIPS-lantiq-adds-xrx200-legacy.patch
- target/linux/lantiq/patches-5.4/0028-NET-lantiq-various-etop-fixes.patch
- target/linux/layerscape/patches-5.4/701-net-0009-dpa-SDK-DPAA-1.x-Ethernet-driver.patch
- target/linux/layerscape/patches-5.4/701-net-0286-staging-fsl_ppfe-eth-introduce-pfe-driver.patch
- target/linux/layerscape/patches-5.4/701-net-0313-staging-fsl_ppfe-eth-reorganize-platform-phy-paramet.patch
- target/linux/layerscape/patches-5.4/701-net-0399-staging-fsl_ppfe-eth-Enhance-error-checking-in-platf.patch
- target/linux/octeon/patches-5.10/700-allocate_interface_by_label.patch
- target/linux/octeon/patches-5.4/700-allocate_interface_by_label.patch
- target/linux/ramips/files/drivers/net/ethernet/ralink/mtk_eth_soc.c
- target/linux/realtek/files-5.4/drivers/net/ethernet/rtl838x_eth.c

**Comment by Ansuel** [comment]
Thx for the list, will have to update also them

Il Ven 23 Lug 2021, 23:23 john-tho ***@***.***> ha scritto:

**Comment by LGA1150** [comment]
mt76 fails to build with this pr
```
  CC [M]  ~/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt76-2021-07-15-bbebea7d/eeprom.o
~/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt76-2021-07-15-bbebea7d/eeprom.c: In function 'mt76_eeprom_override':
~/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt76-2021-07-15-bbebea7d/eeprom.c:99:9: error: too few arguments to function 'of_get_mac_address'
   99 |   mac = of_get_mac_address(np);
      |         ^~~~~~~~~~~~~~~~~~
In file included from ~/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/mac80211-backport/linux/of_net.h:3,
                 from ~/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt76-2021-07-15-bbebea7d/eeprom.c:6:
./include/linux/of_net.h:16:12: note: declared here
   16 | extern int of_get_mac_address(struct device_node *np, u8 *mac);
      |            ^~~~~~~~~~~~~~~~~~
```

**Comment by Ansuel** [comment]
@john-tho can you check if i missed some?
@LGA1150 can you retest if this work?

Probably some custom driver we use are still broken... Testing this will be hard.... Very sad actually...

**Comment by Vladdrako** [comment]
782-net-next-1-of-net-pass-the-dst-buffer-to-of_get_mac_address.patch conflicts with 683-NET-add-mac-address-property.patch

**Comment by Ansuel** [comment]
> 782-net-next-1-of-net-pass-the-dst-buffer-to-of_get_mac_address.patch conflicts with 683-NET-add-mac-address-property.patch

where is this?

**Comment by Vladdrako** [comment]
@Ansuel https://github.com/openwrt/openwrt/commit/b30924873062be47250e6b872347461c8221688d

**Comment by Ansuel** [comment]
Correct 683 should be dropped.

**Comment by LGA1150** [comment]
Nope, you didn't patch the out-of-tree mt76 driver.

**Comment by Ansuel** [comment]
@LGA1150 mb i put the patch in the nat46 package.....

**Comment by LGA1150** [comment]
It worked, thanks.

**Comment by Ansuel** [comment]
@LGA1150 very good

@adschm sorry for the tag. With a quick look do you think this is acceptable? should i split this?

**Comment by Ansuel** [comment]
Tested this with r7800 with ath10k-ct and the mac gets correctly set with this pr

**Comment by john-tho** [comment]
I think there are too many diff context lines in the second hunk of 5.10 681 at the moment?
```
Applying /mnt/openwrt/openwrt/target/linux/generic/pending-5.10/681-NET-add-mtd-
mac-address-support-to-of_get_mac_addres.patch using plaintext:                 
patching file drivers/of/of_net.c                                               
patch: **** malformed patch at line 36:  {                                      
                                                                                
Patch failed!  Please fix /mnt/openwrt/openwrt/target/linux/generic/pending-5.10
/681-NET-add-mtd-mac-address-support-to-of_get_mac_addres.patch!
```

Otherwise, this has been working well for my limited testing prior to the latest two pushes.
Cheers!

**Comment by Ansuel** [comment]
@john-tho rebase magic.... hope it's good now.

**Comment by blocktrron** [comment]
Tested on UniFi 6 LR / Ocedo Raccoon. Looks good.

**Comment by hnyman** [comment]
I will post also here the comment that I posted to the commit itself:

I think that this commit has causes a lot of breakage in buildbot. Most targets seem to be broken.

Looks like at least drivers/net/usb/smsc95xx.c is still unpatched???


Looking back at the buildbot error logs, this gets shown up in every failing target:

x86/geode
```
drivers/net/usb/smsc95xx.c: In function 'smsc95xx_init_mac_address':
drivers/net/usb/smsc95xx.c:907:13: error: too few arguments to function 'of_get_mac_address'
  mac_addr = of_get_mac_address(dev->udev->dev.of_node);
             ^~~~~~~~~~~~~~~~~~
In file included from drivers/net/usb/smsc95xx.c:20:
./include/linux/of_net.h:22:19: note: declared here
 static inline int of_get_mac_address(struct device_node *np, u8 *mac)
                   ^~~~~~~~~~~~~~~~~~
  CC      drivers/usb/host/xhci-mem.o
  CC      drivers/scsi/scsi_transport_spi.o
  CC [M]  drivers/staging/rtl8712/rtl8712_led.o
  AR      net/netfilter/built-in.a
make[7]: *** [scripts/Makefile.build:262: drivers/net/usb/smsc95xx.o] Error 1
make[7]: *** Waiting for unfinished jobs....
```

armvirt32:
```
drivers/net/usb/smsc95xx.c: In function 'smsc95xx_init_mac_address':
drivers/net/usb/smsc95xx.c:907:13: error: too few arguments to function 'of_get_mac_address'
  mac_addr = of_get_mac_address(dev->udev->dev.of_node);
             ^~~~~~~~~~~~~~~~~~
In file included from drivers/net/usb/smsc95xx.c:20:
./include/linux/of_net.h:14:12: note: declared here
 extern int of_get_mac_address(struct device_node *np, u8 *mac);
            ^~~~~~~~~~~~~~~~~~
make[7]: *** [scripts/Makefile.build:262: drivers/net/usb/smsc95xx.o] Error 1
make[7]: *** Waiting for unfinished jobs....
```

**Comment by Ansuel** [comment]
5.4 or 5.10?

Il Gio 5 Ago 2021, 12:58 Hannu Nyman ***@***.***> ha scritto:

**Comment by hnyman** [comment]
> 5.4 or 5.10?

Pretty much all targets, so both 5.4 and 5.10.

Only gemini, mt7622 and mt7623 survivied this commit, all others failed.
https://buildbot.openwrt.org/master/images/#/grid

But hopefully blocktron has already fixed it with 774b386a9. 
At least some failing targets have already been built ok, again, so hopefully ok now.

**Comment by Ansuel** [comment]
The change modify the of_get_mac_addr function so every user not updated
will cause a compilation error.

Il Gio 5 Ago 2021, 14:11 Hannu Nyman ***@***.***> ha scritto:

**Comment by hnyman** [comment]
@blocktrron  @Ansuel 
Looks like there is at least one more error in the layerscape patch
`target/linux/layerscape/patches-5.4/701-net-0009-dpa-SDK-DPAA-1.x-Ethernet-driver.patch`

https://buildbot.openwrt.org/master/images/#/builders/31/builds/222

```
patching file drivers/net/ethernet/freescale/sdk_dpaa/mac.c
patch: **** malformed patch at line 11917: --- /dev/null
Patch failed!  Please fix /builder/shared-workdir/build/target/linux/layerscape/patches-5.4/701-net-0009-dpa-SDK-DPAA-1.x-Ethernet-driver.patch!
make[3]: *** [Makefile:32: /builder/shared-workdir/build/build_dir/target-aarch64_generic_musl/linux-layerscape_armv8_64b/linux-5.4.137/.prepared_968c1b3a3852d34557be87da2317c36b] Error 1
make[3]: Leaving directory '/builder/shared-workdir/build/target/linux/layerscape'
make[2]: *** [Makefile:11: compile] Error 2
```

Looking at the changes by this PR here, the diff line number correction of -2 has been made to the wrong place.

https://github.com/openwrt/openwrt/pull/4392/files#diff-f7b294e318cbb1dd0a931aeaa8610d12ad8bedf77ebe1e361e9e481b27afe143L10514-L10520

Instead of line 10517, the decrease of the patched lines' number should have been decreased at line 11429, (so that the actually changed lines 11585-11711 belong to the affected block... 

https://github.com/openwrt/openwrt/pull/4392/files#diff-f7b294e318cbb1dd0a931aeaa8610d12ad8bedf77ebe1e361e9e481b27afe143L11429

**Comment by hnyman** [comment]
@blocktrron @Ansuel 

layerscape is still broken due to the malformed patch caused by this PR.

```
patching file drivers/net/ethernet/freescale/sdk_dpaa/mac.c
patch: **** malformed patch at line 11917: --- /dev/null
Patch failed!  Please fix /builder/shared-workdir/build/target/linux/layerscape/patches-5.4/701-net-0009-dpa-SDK-DPAA-1.x-Ethernet-driver.patch!
make[3]: *** [Makefile:32: /builder/shared-workdir/build/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-layerscape_armv7/linux-5.4.137/.prepared_09f3973b7752403261fc8642243c1561] Error 1
make[3]: Leaving directory '/builder/shared-workdir/build/target/linux/layerscape'
make[2]: *** [Makefile:11: compile] Error 2
```

Like said in my previous message before the weekend, 
this PR made the patch length lines number correction of "-2" to the wrong place.

https://github.com/openwrt/openwrt/pull/4392/files#diff-f7b294e318cbb1dd0a931aeaa8610d12ad8bedf77ebe1e361e9e481b27afe143L10514-L10520

Instead of line 10517, the decrease of the patched lines' number should have been decreased at line 11429, (so that the actually changed lines 11585-11711 belong to the affected block...

https://github.com/openwrt/openwrt/pull/4392/files#diff-f7b294e318cbb1dd0a931aeaa8610d12ad8bedf77ebe1e361e9e481b27afe143L11429

**Pull request closed without merging**
