### PR TITLE
busybox: update to 1.29.2

### PR DESCRIPTION
**Pull request by hnyman**
EDIT: Updated for 1.29.2 stable release on 31 July 2018

-----

Busybox 1.29 has been released. It is still officially unstable, but likely the stable .1 gets released in a month or so.
https://busybox.net/
https://git.busybox.net/busybox/

* Update busybox to 1.29.2  (was 1.29.0)
* refresh default config
* remove upstreamed patches
   * 001-resource_h_include.patch
   * 400-udhcpc-remove-code-which-requires-server-ID-to-be-on.patch
   * 111-i386_no_arch_flags.patch should be redundant with the new BUSYBOX_CONFIG_STACK_OPTIMIZATION_386 option.  @NeoRaider 

There is also a new BUSYBOX_CONFIG_FEATURE_SORT_OPTIMIZE_MEMORY that should decrease memory used by "sort". Might be enabled?

Size addition from 1.28.4 is about 1 kB, based on the website.

Config has been refreshed with 
```
cd config/
../convert_menuconfig.pl ../../../../build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/busybox-1.29.2
cd ..
./convert_defaults.pl < ../../../build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/busybox-1.29.2/.config > Config-defaults.in 
```

### CODE REVIEW

**Comment by diizzyy** [comment]
..and 1.29.1 is out :-)

**Comment by hnyman** [comment]
Updated for busybox 1.29.1 stable release on 17 July 2018. 
Rebased for current master.

1.29.1 was a really small bump, just two minor fixes:

> 15 July 2018 -- BusyBox 1.29.1 (stable)
> Bug fix release. 1.29.1 has fixes for wget (http->https redirect) and sendmail (angle bracket parsing).

**Comment by wongsyrone** [comment]
Does anyone want to take care of this PR?

**Comment by diizzyy** [comment]
@wongsyrone 
Given the amount of PRs open I think there's a bit of a backlog

**Comment by hnyman** [comment]
@nbd168  @dedeckeh  

Updated for busybox 1.29.2 stable release on 31 July 2018.
Rebased for current master.

> 31 July 2018 -- BusyBox 1.29.2 (stable)
> Bug fix release. 1.29.2 has fixes for fdisk (compat fixes, allow 2TB+ sizes), gzip (FEATURE_GZIP_LEVELS was producing badly-compressed .gz), hexedit (segfault fix).

**Comment by dedeckeh** [comment]
Merged; thx

**Pull request closed without merging**
