### PR TITLE
mconf readme update

### PR DESCRIPTION
**Pull request by 532910**
This updates mconf.c readme message to maintain less changes with
upstream and consistency with nconf.c

Signed-off-by: Sergio E. Nemirowski <sergio@outerface.net>

### CODE REVIEW

**Comment by 532910** [comment]
complementary for #3097

**Comment by adrianschmutzler** [comment]
Please update your commit title to follow the formal requirements (particularly you lack a prefix).

**Comment by 532910** [comment]
My bad. Done.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by 532910** [comment]
Thank you, Petr!
Am I right that I can safely remove my branches?

**Comment by 532910** [comment]
@ynezz, can I remove my branches?

**Pull request closed without merging**
