### PR TITLE
tools/libelf: alpine linux os type: linux-musl fix

### PR DESCRIPTION
**Pull request by legale**
Prevent ./configure "checking build system" test fail on Alpine linux.

Signed-off-by: Ruslan Isaev legale.legale@gmail.com

### CODE REVIEW

**Comment by aparcar** [comment]
Thanks for the patch, did you send it to upstream as well?

**Comment by legale** [comment]
> Thanks for the patch, did you send it to upstream as well?

You mean libelf developer?

**Comment by legale** [comment]
Ok. I will.

ср, 2 февр. 2022 г., 00:31 Hauke Mehrtens ***@***.***>:

**Comment by ynezz** [comment]
> Ok. I will.

@legale so whats the status?

**Comment by Ansuel** [comment]
@legale NEWS?

**Comment by legale** [comment]
I've sent this patch to the author.

**Comment by Ansuel** [comment]
@legale can you post here the mailing list link so we can track the status?

**Comment by legale** [comment]
> @legale can you post here the mailing list link so we can track the status?

@Ansuel I have no idea what else i can do. :)

image

image

**Comment by Ansuel** [comment]
@ynezz any idea to wait mailing list send this? I also didn't find the correct one...

**Comment by paper42** [comment]
Newer systems use libelf from elftools, the old separate libelf version seems to be abandoned and most distributions switched from it years ago. I am having a similar issue on Void musl and removing libelf helped: bf4aa0c6a2f57951f995b2ac6f394c45ac852b9d. Could we instead backport that commit to OpenWrt 21.02?

**Comment by ynezz** [comment]
Merged, thanks!

> @ynezz any idea to wait mailing list send this? I also didn't find the correct one...

Nope, sorry. We've tried hard to upstream this fix, but failed. Sometimes that happens and IMO we can't do more about that.

**Pull request closed without merging**
