### PR TITLE
master: Add github actions for test ci

### PR DESCRIPTION
**Pull request by peterwillcn**
Signed-off-by: Xiaobo Tian <peterwillcn@gmail.com>

   x86_64 as a general overall test template, the code for the initial test, in a timely manner to find errors in the code.
Screen Shot 2020-03-28 at 22 52 40

### CODE REVIEW

**Comment by ynezz** [comment]
Thanks, but we're not going to use and maintain this GitHub feature. So far there is a plan to have self-hosted GitLab instance where we could setup CI tasks. BTW this testing seems same as we've now on buildbots https://openwrt.org/infrastructure#buildbot

**Comment by peterwillcn** [comment]
@ynezz Why not have one more option, be open to github's ci build tool, and make a few changes?

**Comment by ynezz** [comment]
> Why not have one more option

Maintenance, there is https://git.openwrt.org/?p=buildbot.git already

> be open to github's ci build tool, and make a few changes

Majority of core developers don't want to use and/or promote proprietary tools http://lists.infradead.org/pipermail/openwrt-adm/2020-January/001253.html, for more details see https://github.com/openwrt/openwrt/pull/2218 and https://forum.openwrt.org/t/communication-problem-with-the-openwrt-team

**Comment by Neustradamus** [comment]
Any news on Actions?

**Pull request closed without merging**
