### PR TITLE
kernel: bump 4.14 to 4.14.94

### PR DESCRIPTION
**Pull request by peterwillcn**
bump 4.14 to 4.14.94
Signed-off-by: xiaobo <peterwillcn@gmail.com>

### CODE REVIEW

**Comment by 981213** [comment]
Kernel bumping isn't just changing version in Makefile. You also need to refresh patches for *every* targets. I guess there are scripts doing this but I don't know exactly which command it is.

**Comment by dengqf6** [comment]
@981213 Interestingly, in this case the kernel version is the _only_ needed to be changed according to @xback 's staging tree

**Comment by xback** [comment]
Correct.
It not occuring that much, but in this bump not a single patch was altered during refreshing.

I'll push this on Monday

**Comment by 981213** [comment]
Wow. That's interesting :D

**Comment by peterwillcn** [comment]
Interesting too.😄

**Pull request closed without merging**
