### PR TITLE
firmware-utils: sort tools alphabetically

### PR DESCRIPTION
**Pull request by mans0n**
Also remove leading whitespace after comma.

### CODE REVIEW

**Comment by mans0n** [comment]
I also wanted to replace all local crc32 functions to cyg_crc32, but probably I can't managed that.

**Comment by adrianschmutzler** [comment]
The patch is correct in what it tries to achieve, however I wonder whether the sequence of commands has a relevance here?

**Comment by mans0n** [comment]
I guess not. It seems new tools were mostly appended to the end, according to the git log of the Makefile.

**Comment by adrianschmutzler** [comment]
Seems to work fine.

Thanks, merged to master.

**Pull request closed without merging**
