### PR TITLE
[RFC] sunxi: single ext4 partition for SUNXI, Micro SD card and eMMC

### PR DESCRIPTION
**Pull request by antonyantony**
I have been using this patch, initial version, for a year. If you like this idea let me know.

sunxi: single ext4 partition for Micro SD card and eMMC

    add single ext4 partition image for SUNXI Allwinner, devices;
    without a DOS partition.

    * single ext4 partition instead of current dual partition image(DOS + ext4)
    * This would make it easier to install to eMMC, see sunxi-emmc-ext4-install.sh
      https://github.com/antonyantony/openwrt/tree/emmc-install
    * sysupgrade support on Micro SD card, single ext4
    * tar.gz image contains uboot files, and dtb file to install to eMMC

    Next on my wish list:
    * support sysupgrade for eMMC on Sunxi, it works for SD card.
    * would love to see dual partition support, primary and backup partions (with root and kernel)
    * get fw_printenv and fw_settenv and /etc/fw_env.config working for sunxi.
     https://blog.night-shade.org.uk/2014/01/fw_printenv-config-for-allwinner-devices/
     once fw_setenv works properly it could be easier to support dual partition.
    * support different partition sizes?

hauke  comments?

### CODE REVIEW

**Comment by antonyantony** [comment]
V2:
no more hard coded device name. Now it should support all sunxi devices.

**Comment by antonyantony** [comment]
v2:
 no more hard coded device name. Now it should support all sunxi devices.
v3:
fixed sysupgrade support for Micro SD card

**Comment by antonyantony** [comment]
v2:
no more hard coded device name. Now it should support all sunxi devices.
v3:
fixed sysupgrade support for Micro SD card
v4:  82cee3e
cleanup u-boot script generation
test old method DOS + ext4

**Comment by adrianschmutzler** [comment]
Hi, since this is not a fix, but a feature, and none of the committer seems to be interested in reviewing it, I will close it now (i.e. "Won't implement").

I'm sorry, but better crush your remaining hopes now than waiting another year where supposedly nothing different will happen.

**Pull request closed without merging**
