### PR TITLE
[21.02] ramips: mt7620: fix ethernet with external switches

### PR DESCRIPTION
**Pull request by mcprat**
these 10 commits should be backported after getting enough people to test

the first 7 commits are needed in order to backport the rest without conflicts when doing `git cherry-pick -x`

### CODE REVIEW

**Comment by polex** [comment]
It works on Sitecom WLR-4100 V1 002

**Comment by JiiPee74** [comment]
I have been running these changes on my Telewell TW-4G (LTE) router what is clone of lava lr25g001 router which is supported by openwrt.

Switch has been working great, I haven't run any issues.

**Comment by polex** [comment]
Sitecom WL-4100 did not work in 21.02 without this patch (I tested few months ago).
Did somebody tested the last 21.02.00 on similar router:
- LAVA LR-25G001
- EnGenius ESR600
I expect they do not work as well.

**Comment by polex** [comment]
I just tested the WLR-4100 V1 002 which does not work without this PR.
The device become unaccessible (UART access for recovery).

**Review by polex — APPROVED** [review]

**Comment by polex** [comment]
I am waiting for the embedding of this PR, before submitting a new PR for adding WLR-4100 in to 21.02 branch (like i did for Master branch).
The outcome of my test is that Sitecom WLR-4100 v1 002 requires this PR like in the master branch. Without it the device will be bricked and the UART recovery will be needed because the MT7620 losses the connection with QCA83x7 therefore the device cannot be controlled any longer.
I expect the very same behavior from any other MT7620A + AR 83x7 device like:
- D-Link DWR-961 A1
- EnGenius ESR600
- LAVA LR-25G001
In other words **those device will be bricked by an update from 19.07 to 21.02**.
In my understanding the bricking of those devices is a very good reason for embedding this PR in 21.02.
> these 10 commits should be backported after getting enough people to test

I understand @mpratt14 is concerned because this PR may be harmful for others device i.e.:
- MT7620A alone (i.e.: Ai-BR100, AC1200RM...)
- MT7620N (i.e.: WMR-300, DWR-921 C1...)
- MT7620A + other switches (i.e. Edimax BR-6478AC v2, EW-7478APC, ZyXEL Keenetic Viva...)

But I do not expect people with devices above to test this PR, just because they do not need it.

**Comment by mpratt14** [comment]
I'm not "concerned" necessarily... however the changes have been in master for a while

also I don't know how appropriate it is to pull other unrelated commits so that it merges cleanly, or if they actually prefer edited backports

maybe just email the development mail list

**Comment by ynezz** [comment]
Merged, thanks.

**Pull request closed without merging**
