### PR TITLE
mvebu: switch to kernel 6.6

### PR DESCRIPTION
**Pull request by stklcode**
Update default kernel version to 6.6 and drop configs and patches for kernel 6.1. We can also omit the conditional to include DTS dir.

We have 6.6 as testing merged for little over 5 weeks (#14912) and some of us (including myself) are testing it for about 8 weeks. There's not much feedback, but also no known blockers. We should move forward to 6.6 and leave the intermediate 6.1 behind us.

There are some minor open issues like compiling _mwlwifi_ for _cortexa53_ (#15108), which is not necessarily a 6.6 regression, but a line of not so clean upstream code in combination with `CONFIG_KERNEL_WERROR`. _cortexa9_ where some devices contain _mwlwifi_ by default is not affected.

Build and run tested on:
* mvebu/cortexa9: Turris Omnia
* mvebu/cortexa9: WRT1900ACS

### CODE REVIEW

**Comment by neheb** [comment]
Hmm?

https://github.com/openwrt/openwrt/commit/63dd3f74ac3413b9fe069f136b376bd489164524

fixes that compile error AFAIK. The 64-bit error I would ignore. Those casts seem quite off.

**Comment by stklcode** [comment]
Right, compilation is fine on 32bit targets and the referenced issue is a compiler warning on 64bit targets that only affects non-default configuration. Anyway not a 6.6 regression if i get it right, just the only open issue I’m currently aware of. Should not block us here.

**Comment by Borromini** [comment]
You have my vote :grinning:

Run-tested on mvebu/cortexa9 (WRT1200AC) and mvebu/cortexa72 (RB5009UG+S+IN).

**Review by BKPepe — APPROVED** [review]
Go for it! 👍

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
