### PR TITLE
kernel: bump 6.1 to 6.1.103

### PR DESCRIPTION
**Pull request by zxlhhyccc**
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.103

Removed upstreamed:
generic/backport-6.1/412-v6.3-01-spidev-Add-Silicon-Labs-EM3581-device-compatible.patch

See: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.103&id=c6c419ed94788ca13334b4acd50167b7f6d00a06

All other patches automatically rebased.

Build system: bcm4908 bcm53xx.

### CODE REVIEW

**Review by rany2 — COMMENTED** [review]
https://github.com/openwrt/openwrt/pull/16061/commits/a1db9b786ca2dac61e1dc927e0e9d898818a40d9 included in #16061 should fix the issue of `mtd_test.ko` causing CI to fail. I think you could just include that commit for now and either one of you drop it later depending on which PR gets merged first.

**Comment by zxlhhyccc** [comment]
> [a1db9b7](https://github.com/openwrt/openwrt/commit/a1db9b786ca2dac61e1dc927e0e9d898818a40d9) included in #16061 should fix the issue of `mtd_test.ko` causing CI to fail. I think you could just include that commit for now and either one of you drop it later depending on which PR gets merged first.

OK.

**Comment by zxlhhyccc** [comment]
> [a1db9b7](https://github.com/openwrt/openwrt/commit/a1db9b786ca2dac61e1dc927e0e9d898818a40d9) included in #16061 should fix the issue of `mtd_test.ko` causing CI to fail. I think you could just include that commit for now and either one of you drop it later depending on which PR gets merged first.

**Comment by robimarko** [comment]
@zxlhhyccc What is going on?

**Comment by zxlhhyccc** [comment]
@robimarko I'm sorry. Something happened. I accidentally deleted the branch.

**Pull request closed without merging**
