### PR TITLE
ci: bump buildworker container and check integrity of toolchain tarball 

### PR DESCRIPTION
**Pull request by ynezz**
### ci: build: verify downloaded toolchain tarball
    
    CDNs are known to ship outdated or corrupted files, if it unpacks
    correctly, it necessarily doesn't mean, that we're using the desired
    content. So lets fix it by checking the tarball as well.
    
    I'm adding GPG checking explicitly, its not needed, but just double
    checking, that everything is working as expected on build
    infrastructure.

###    ci: bump buildworker container to version v6
    
    Its being used by buildbot workers, adds g++-multilib to fix node
    cross-compilation from a 64-bit build machine to 32-bit host.
    
References: https://github.com/openwrt/buildbot/pull/7

### CODE REVIEW

**Comment by aparcar** [comment]
Looks fine but isn't it possible that all CDN files are outdated at the same time?

**Comment by ynezz** [comment]
I assume, that syncing bigger files takes longer time, I've seen such verification failures in docker repository several times already.

May 26, 2023 23:02:18 Paul Spooren ***@***.***>:

**Comment by aparcar** [comment]
I wonder if we can somehow tune the fastly CDN. I'll reach out to their support.

**Comment by ynezz** [comment]
> I've seen such verification failures in docker repository several times already.

#### https://gitlab.com/openwrt/docker/-/jobs/4066677994

```shell
+ curl https://downloads.cdn.openwrt.org/snapshots/targets/layerscape/armv8_64b/sha256sums -fs -o sha256sums
+ curl https://downloads.cdn.openwrt.org/snapshots/targets/layerscape/armv8_64b/sha256sums.asc -fs -o sha256sums.asc
+ curl https://downloads.cdn.openwrt.org/snapshots/targets/layerscape/armv8_64b/sha256sums.sig -fs -o sha256sums.sig
...
+ gpg --with-fingerprint --verify sha256sums.asc sha256sums
...
gpg: BAD signature from "OpenWrt Build System (PGP key for unattended snapshot builds) <pgpsign-snapshots@openwrt.org>" [ultimate]
```

#### https://gitlab.com/openwrt/docker/-/jobs/4052661692

```shell
wget https://downloads.cdn.openwrt.org/releases/22.03-SNAPSHOT/targets/x86/64/openwrt-imagebuilder-22.03-SNAPSHOT-x86-64.Linux-x86_64.tar.xz
...
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
openwrt-imagebuilder-22.03-SNAPSHOT-x86-64.Linux-x86_64.tar.xz: FAILED
```

I'm simply aware about those issues as GitLab.com sends email (by default?) if pipeline in any watched (?) project fails. I'm not sure if thats possible with GitHub.com, need to look at that, I would like to be aware as well about such failures.

**Review by aparcar — APPROVED** [review]

**Comment by ynezz** [comment]
Merged in 567784127e92b

**Pull request closed without merging**
