### PR TITLE
tools: add libressl and don't rely on host's openssl-dev package

### LINKED ISSUE #4608: openvswitch: Python urllib3 ImportError: No module named urllib3
Maintainer: @commodo 
Environment: OpenWRT
Package: openvswitch
Description:
When I update the git repo and package repo with

```
git pull
git checkout master
./scripts/feeds update -a
./scripts/feeds install  -a
```
And I recompile OpenWRT again, the stderr is like this
```
Traceback (most recent call last):
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/ensurepip/__init__.py", line 205, in _main
    default_pip=args.default_pip,
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/ensurepip/__init__.py", line 108, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13/Lib/ensurepip/__init__.py", line 31, in _run_pip
    import pip
  File "/tmp/tmpRHoJos/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 21, in <module>
  File "/tmp/tmpRHoJos/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 62, in <module>
  File "/tmp/tmpRHoJos/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
ImportError: No module named urllib3
Makefile:927: recipe for target 'install' failed
make[4]: *** [install] Error 1
make[4]: Leaving directory '/home/kholisrag/openwrt/build_dir/target-mips_34kc_musl-1.1.16/host/Python-2.7.13'
Makefile:304: recipe for target '/home/kholisrag/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/host/stamp/.python_installed' failed
make[3]: *** [/home/kholisrag/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/host/stamp/.python_installed] Error 2
make[3]: Leaving directory '/home/kholisrag/openwrt/feeds/packages/lang/python/python'
package/Makefile:196: recipe for target 'package/feeds/packages/python/host/compile' failed
make[2]: *** [package/feeds/packages/python/host/compile] Error 2
make[2]: Leaving directory '/home/kholisrag/openwrt'
package/Makefile:193: recipe for target '/home/kholisrag/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/stamp/.package_compile' failed
make[1]: *** [/home/kholisrag/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kholisrag/openwrt'
/home/kholisrag/openwrt/include/toplevel.mk:192: recipe for target 'world' failed
make: *** [world] Error 
```
I tried with
`pip install urllib3 --upgrade`
it's still not working

i think it's because openvswitch packages updated to version 2.7.1 , it's because dependency?

### PR DESCRIPTION
**Pull request by commodo**
Fixes https://github.com/openwrt/packages/issues/4608
Admittedly, usually fixes for packages go into the packages repo, but this one is related to openssl-dev

------------------------------------------------

The intent is to fix the Python/Python3 host build
on OpenWrt.

The openssl-dev package has occasionally been problematic
on Linux distros [ at least for Python ], because
of all the different variants.
And on OS X, openssl dev libs are marked as deprecated
in homebrew [ not sure about macports ].

On LEDE, the solution has been to add libressl
to tools.
So, copying that over ; this should make Python
compile-able with OpenWrt trunk ; then after
the re-merge all should be good.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by nmaas87** [comment]
I can confirm that this PR resolves Python compile issues for me 👍

**Review by nmaas87 — APPROVED** [review]
This PR resolved the problem and worked without issues
 👍

**Comment by paulo-raca** [comment]
Worked for me too :)

Thank you

**Comment by danweller18** [comment]
Worked for me as well... thanks

**Review by PauliusB — APPROVED** [review]

**Comment by blogic** [comment]
this is already part of the LEDE tree which will replace the OWRT tree shortly.

**Comment by commodo** [comment]
ack

**Pull request closed without merging**
