### PR TITLE
ath79: add support for ASUS PL-AC56

### PR DESCRIPTION
**Pull request by therealsummoner**
Asus PL-AC56 Powerline Range Extender Rev.A1
(in kit with Asus PL-E56P Powerline-slave)

Hardware specifications:
Board: AP152
SoC: QCA9563 2.4G n 3x3
PLC: QCA7500
WiFi: QCA9882 5G ac 2x2
Switch: QCA8337 3x1000M
Flash: 16MB 25L12835F SPI-NOR
DRAM SoC: 64MB w9751g6kb-25
DRAM PLC: 128MB w631gg6kb-15

Clocks: CPU:775.000MHz, DDR:650.000MHz, AHB:258.333MHz, Ref:25.000MHz

MAC addresses as verified by OEM firmware:
use            address      source
Lan/Wan/PLC    *:10         art 0x1002 (label)
2G             *:10         art 0x1000
5G             *:14         art 0x5000

Important notes:
 - the PLC firmware has to be provided and copied manually onto the
    device in the /lib/plc directory and the plc_firmware.nvm symlink has
    to be modified, if needed! The PLC here has no dedicated flash,
    thus the firmware file has to be uploaded to the PLC controller at
    every system start
 - the PLC functionality is managed by the script /etc/init.d/plc_basic,
    a very basic script based on the the one from Netadair (netadair dot de)
 - the firmware (.nvm) file can be gathered from the PL-AC56 source code
    from Asus, from various forums, etc., as also mentioned in the plc_basic
    script
 - for desired flashing the plc devices, see the notes in plc_basic script!

Installation:

Asus windows recovery tool:
 - have to have the latest Asus firmware flashed before continuing!
 - install the Asus firmware restoration utility
 - unplug the router, hold the reset button while powering it on
 - release when the power LED flashes slowly
 - specify a static IP on your computer:
    IP address: 192.168.1.75
    Subnet mask 255.255.255.0
 - start the Asus firmware restoration utility, specify the factory image
    and press upload
 - do NOT power off the device after OpenWrt has booted until the LED flashing

TFTP Recovery method:
 - have to have the latest Asus firmware flashed before continuing!
 - set computer to a static ip, 192.168.1.75
 - connect computer to the LAN 1 port of the router
 - hold the reset button while powering on the router for a few seconds
 - send firmware image using a tftp client; i.e from linux:
    $ tftp
    tftp> binary
    tftp> connect 192.168.1.1
    tftp> put factory.bin
    tftp> quit
 - do NOT power off the device after OpenWrt has booted until the LED flashing

Additional notes:
 - the pairing buttons have to have pressed for at least half a second,
    it doesn't matter on which plc device (master or slave) first
 - it is possible to pair the devices without the button-pairing requirement
    simply by pressing reset on the slave device. This will default to the
    firmware settings, which is also how the plc_basic script is setting up
    the master device, i.e. configuring it to firmware defaults
 - SWAP functionality e.g. ZRAM-SWAP is recommended to be used
 - the PL-E56P slave PLC has its dedicated 4MByte SPI, thus it is capable
    to store all firmware currently available. Note that some other
    slave devices are not guarantied to have the capacity for the newer
    ~1MByte firmware blobs!
    To have a good overlook about the slave device, here are its specs:
    same QCA7500 PLC controller, same w631gg6kb-15 128MB RAM,
    25L3233F 4MB SPI-NOR and an AR8035-A 1000M-Transceiver

Signed-off-by: Tamas Balogh <tamasbalogh@hotmail.com>

### CODE REVIEW

**Comment by mans0n** [comment]
Probably we won't accept a patch with toplevel `files` directory. As it will be used only by PLC devices (only this device so far), creating a new package might be a solution (or not).

**Comment by therealsummoner** [comment]
Hmm so files would be then global i.e. for all devices? Asking because I got different info about this.

**Comment by mans0n** [comment]
AFAIK toplevel `files` is global, `base-files` in (sub)target dir is applied only to the (sub)target. But I feel even the (sub)target `base-files` is not appropriate in this case.

What have you heard about it? I haven't used toplevel `files` myself so I might be wrong.

**Comment by therealsummoner** [comment]
My last info was the top level files are "bound" to subtargets, not global, however I find this strange as well. I was planning to create a package before, so maybe that's the way.
Can anyone confirm this, or if so, a package would be the best way here?

**Comment by jwmullally** [comment]
> As it will be used only by PLC devices (only this device so far), creating a new package might be a solution (or not).

> I was planning to create a package before, so maybe that's the way.

[The DLink COVR P2500](https://forum.openwrt.org/t/support-for-d-link-covr-p2500/30009) also needs the PLC firmware to be loaded on boot using `plchost`, so there could potentially be some shared usage between a few devices.

**Comment by therealsummoner** [comment]
> > As it will be used only by PLC devices (only this device so far), creating a new package might be a solution (or not).
> 
> > I was planning to create a package before, so maybe that's the way.
> 
> [The DLink COVR P2500](https://forum.openwrt.org/t/support-for-d-link-covr-p2500/30009) also needs the PLC firmware to be loaded on boot using `plchost`, so there could potentially be some shared usage between a few devices.

Problem is, most of these devices are not handling the PLC at all, or maybe with some small helper script like in your example.
Here I was creating a basic environment for all the things it need to function without much interaction, the only exception is the firmware file itself.
But if top level files are not the correct way, I have to either create some sort of package, or have to go the same way as these devices i.e. mark it as "external image" in ToH and provide only the base functionality without PLC.
For these kind of devices the best would be, if I could go with the top level files, so I can then nicely put everything where it has to be, for the full functionality. But I'm still not sure, as @mans0n mentioned, maybe this is not allowed.
Maybe there is no other way to achieve this, only with packages?

**Comment by jwmullally** [comment]
A flexible short term workaround until a package 
(or other solution) is ready could be putting the script on the device wiki for the user to copy+paste into the terminal. 

Either the direct contents, or something like
```
cat > /usr/bin/myfile <<'EOF'
#!/bin/sh
 
echo "Running program"
exit 0

EOF
chmod +x /usr/bin/myfile
echo "/usr/bin/myfile" >> /etc/sysupgrade.conf
```

**Comment by therealsummoner** [comment]
> A flexible short term workaround until a package (or other solution) is ready could be putting the script on the device wiki for the user to copy+paste into the terminal.
> 
> Either the direct contents, or something like
> 
> ```
> cat > /usr/bin/myfile <<'EOF'
> #!/bin/sh
>  
> echo "Running program"
> exit 0
> 
> EOF
> chmod +x /usr/bin/myfile
> echo "/usr/bin/myfile" >> /etc/sysupgrade.conf
> ```

This was my original idea, however I got the warning for this approach too, that maybe a PR like that would be not accepted, due to being like "half ready".
But if this is confirmed to be a working solution, I'd gladly do it this way.

**Comment by jwmullally** [comment]
> This was my original idea, however I got the warning for this approach too, that maybe a PR like that would be not accepted, due to being like "half ready".

Yeah, if manual steps are needed to supply the firmware, either way the PLC isnt going to work out of the box and the user will need to follow some instructions.

If there is no nice existing package for this, it seems better to first add this device with all the regular router parts (WiFi, LAN etc) working with a nice tidy commit, and include a basic copy+paste PLC script on the Wiki.

Then seperately, iterate on these PLC scripts until they are generic enough to support multiple similar QCA7550 plchost devices (e.g. [Devolo DLAN Pro 1200 WiFi](https://openwrt.org/toh/devolo/dlan_pro_1200_wifi_ac#powerline_interface) and make a package for it. You could come back later and include that package in the default build. It would be nice to able package the firmware, (e.g. firmware-qca7550-eu), but that would need a PLC expert to asess (there may be regulatory or license issues).

These are just my 2c anyway!

**Comment by therealsummoner** [comment]
> If there is no nice existing package for this, it seems better to first add this device with all the regular router parts (WiFi, LAN etc) working with a nice tidy commit, and include a basic copy+paste PLC script on the Wiki.

This sounds like a plan to me, I'll go then this way first, thanx for your help!

**Pull request closed without merging**
