### PR TITLE
toolchain: glibc: Update to version 2.36

### PR DESCRIPTION
**Pull request by hauke**
This updates glibc to version 2.36.

I will apply the fstools patches directly to fstools.

This was build tested on arc, aarch64 and mips 32 BE with all core packages. I did not test the feed packages. 
I also runtime tested it a bit.

### CODE REVIEW

**Comment by trippleflux** [comment]
Still error on x86_64 snapshot : 
```
 -fno-plt -mtune=skylake -march=skylake -O3 -funsafe-math-optimizations -ftree-vectorize -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -MT sanitizer_printf.lo -MD -MP -MF .deps/sanitizer_printf.Tpo -c /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/sanitizer_common/sanitizer_printf.cpp  -fPIC -DPIC -o .libs/sanitizer_printf.o
In file included from /home/username/works/openwrt/staging_dir/toolchain-x86_64_gcc-12.1.0_glibc/include/linux/fs.h:19,
                 from /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp:76:
/home/username/works/openwrt/staging_dir/toolchain-x86_64_gcc-12.1.0_glibc/include/linux/mount.h:95:6: error: multiple definition of 'enum fsconfig_command'
   95 | enum fsconfig_command {
      |      ^~~~~~~~~~~~~~~~
In file included from /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp:63:
/home/username/works/openwrt/staging_dir/toolchain-x86_64_gcc-12.1.0_glibc/include/sys/mount.h:189:6: note: previous definition here
  189 | enum fsconfig_command
      |      ^~~~~~~~~~~~~~~~
/home/username/works/openwrt/staging_dir/toolchain-x86_64_gcc-12.1.0_glibc/include/linux/mount.h:129:8: error: redefinition of 'struct mount_attr'
  129 | struct mount_attr {
      |        ^~~~~~~~~~
/home/username/works/openwrt/staging_dir/toolchain-x86_64_gcc-12.1.0_glibc/include/sys/mount.h:161:8: note: previous definition of 'struct mount_attr'
  161 | struct mount_attr
      |        ^~~~~~~~~~
mv -f .deps/method-ml.Tpo .deps/method-ml.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0-final/./gcc/xgcc -shared-libgcc -B/home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0-final/./gcc -nostdinc++ -L/home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0-final/x86_64-openwrt-linux-gnu/libstdc++-v3/src -L/home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0-final/x86_64-openwrt-linux-gnu/libstdc++-v3/src/.libs -L/home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0-final/x86_64-openwrt-linux-gnu/libstdc++-v3/libsupc++/.libs -B/home/username/works/openwrt/staging_dir/toolchain-x86_64_gcc-12.1.0_glibc/x86_64-openwrt-linux-gnu/bin/ -B/home/username/works/openwrt/staging_dir/toolchain-x86_64_gcc-12.1.0_glibc/x86_64-openwrt-linux-gnu/lib/ -isystem /home/username/works/openwrt/staging_dir/toolchain-x86_64_gcc-12.1.0_glibc/x86_64-openwrt-linux-gnu/include -isystem /home/username/works/openwrt/staging_dir/toolchain-x86_64_gcc-12.1.0_glibc/x86_64-openwrt-linux-gnu/sys-include    -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -DHAVE_RPC_XDR_H=0 -DHAVE_TIRPC_RPC_XDR_H=0 -I. -I/home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/sanitizer_common -I..  -I /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/include -I /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer -isystem /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/include/system  -Wall -W -Wno-unused-parameter -Wwrite-strings -pedantic -Wno-long-long -fPIC -fno-builtin -fno-exceptions -fno-rtti -fomit-frame-pointer -funwind-tables -fvisibility=hidden -Wno-variadic-macros -I../../libstdc++-v3/include     -I../../libstdc++-v3/include/x86_64-openwrt-linux-gnu     -I/home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/../libstdc++-v3/libsupc++ -std=gnu++14 -fcf-protection -mshstk -DSANITIZER_LIBBACKTRACE -DSANITIZER_CP_DEMANGLE -I /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/../libbacktrace -I ../libbacktrace -I /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/../include -include /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/libbacktrace/backtrace-rename.h -mtune=skylake -march=skylake -O3 -funsafe-math-optimizations -ftree-vectorize -fno-caller-saves -fno-plt -mtune=skylake -march=skylake -O3 -funsafe-math-optimizations -ftree-vectorize -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -MT sanitizer_procmaps_bsd.lo -MD -MP -MF .deps/sanitizer_procmaps_bsd.Tpo -c -o sanitizer_procmaps_bsd.lo /home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/sanitizer_common/sanitizer_procmaps_bsd.cpp
/home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/sanitizer_common/sanitizer_posix.cpp: In function '__sanitizer::fd_t __sanitizer::OpenFile(const char*, FileAccessMode, error_t*)':
/home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/sanitizer_common/sanitizer_posix.cpp:162:27: warning: 'flags' may be used uninitialized [-Wmaybe-uninitialized]
  162 |   fd_t res = internal_open(filename, flags, 0660);
      |              ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/username/works/openwrt/build_dir/toolchain-x86_64_gcc-12.1.0_glibc/gcc-12.1.0/libsanitizer/sanitizer_common/sanitizer_posix.cpp:156:7: note: 'flags' was declared here
  156 |   int flags;
      |       ^~~~~
make[8]: *** [Makefile:616: sanitizer_platform_limits_posix.lo] Error 1
make[8]: *** Waiting for unfinished jobs....
```

**Comment by hauke** [comment]
For me the toolchain is compiling with the following configuration:
````
$ ./scripts/diffconfig.sh 
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y
CONFIG_DEVEL=y
CONFIG_TOOLCHAINOPTS=y
# CONFIG_GCC_USE_VERSION_11 is not set
CONFIG_GCC_USE_VERSION_12=y
CONFIG_GCC_VERSION="12.1.0"
CONFIG_GCC_VERSION_12=y
CONFIG_LIBC="glibc"
CONFIG_LIBC_USE_GLIBC=y
# CONFIG_LIBC_USE_MUSL is not set
CONFIG_STRIP_ARGS="--strip-all"
CONFIG_TARGET_SUFFIX="gnu"
CONFIG_USE_GLIBC=y
CONFIG_USE_STRIP=y
````

Maybe you have to delete the toolchain to make OpenWrt apply the gcc patches again.

**Comment by trippleflux** [comment]
My bad, replacing the wrong archive which I was downloaded from the github, it didn't containing the new GCC patches. Thanks for the glibc bump.

**Comment by Vladdrako** [comment]
Not sure related or not
<pre>
.././configure: line 17897: syntax error near unexpected token `)'
.././configure: line 17897: `    gnu)'
make[3]: *** [Makefile:96: /home/vladdrako/openwrt/build_dir/hostpkg/libffi-3.4.2/.configured] Error 2
make[3]: Leaving directory '/home/vladdrako/openwrt/feeds/packages/libs/libffi'
time: package/feeds/packages/libffi/host-compile#16.43#1.83#18.62
    ERROR: package/feeds/packages/libffi [host] failed to build.
</pre>

**Comment by hauke** [comment]
I merged some parts of this pull request. glibc was updated in master to version 2.35, there are still many compile problems in the feeds with glibc 2.36. Lets wait some months.

The following changes were merged:
c97f918d37324db66c0ac4d12483baa93754f890
8456d06aa678c649d178053a5734d0d4c40a058c
a66f843971d8b0b2f8bad1cb75f3bbc1a8e06bf0
e58b76effe6b167c49812372d5334f6f57546778

**Comment by hauke** [comment]
I already prepared these changes fro glibc 2.36: https://github.com/hauke/packages/pull/new/glibc

**Comment by trippleflux** [comment]
@hauke 
Wanted to share liburing mod for Samba4 compilation success on glibc 2.36
```
diff -Naur a/src/include/liburing/io_uring.h b/src/include/liburing/io_uring.h
--- a/src/include/liburing/io_uring.h	2022-06-23 22:45:45.000000000 +0700
+++ b/src/include/liburing/io_uring.h	2022-08-09 01:07:30.174412800 +0700
@@ -7,8 +7,27 @@
  */
 #ifndef LINUX_IO_URING_H
 #define LINUX_IO_URING_H
+#define HAVE_SYS_MOUNT_FSCONFIG
 
-#include <linux/fs.h>
+#ifdef HAVE_SYS_MOUNT_FSCONFIG
+/*
+ * glibc >= 2.36 linux/mount.h conflicts with sys/mount.h,
+ * which in turn prevents use of linux/fs.h. So we have to
+ * define the constants ourselves for now.
+ */
+#define FS_IOC_GETFLAGS                _IOR('f', 1, long)
+#define FS_IOC_SETFLAGS                _IOW('f', 2, long)
+#define FS_IOC_GETVERSION              _IOR('v', 1, long)
+#define FS_IOC_SETVERSION              _IOW('v', 2, long)
+#define FS_IOC_FIEMAP                  _IOWR('f', 11, struct fiemap)
+#define FS_IOC32_GETFLAGS              _IOR('f', 1, int)
+#define FS_IOC32_SETFLAGS              _IOW('f', 2, int)
+#define FS_IOC32_GETVERSION            _IOR('v', 1, int)
+#define FS_IOC32_SETVERSION            _IOW('v', 2, int)
+typedef int __bitwise __kernel_rwf_t;
+#else
+ #include <linux/fs.h>
+#endif
 #include <linux/types.h>
 
 #ifdef __cplusplus
```
Don't know if it's proper or not but I have found that define from archlinux package.

**Comment by hauke** [comment]
The LXC build will get fixed with https://github.com/openwrt/packages/pull/20098
All other packages should build like before.

**Pull request merged**
