### PR TITLE
ipq40xx: convert to DSA and enable mobipromo,cm520-79f

### PR DESCRIPTION
**Pull request by redchenjs**
Convert to DSA and enable the MobiPromo CM520-79F device again.

Signed-off-by: Jack Chen <redchenjs@live.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@robimarko ?

Also does the leds are handled by the switch also on some ipq40xx devices? If that's the case it can be wrong to assign the led to netdev as the kernel can't control them...

**Comment by redchenjs** [comment]
> @robimarko ?
> 
> Also does the leds are handled by the switch also on some ipq40xx devices? If that's the case it can be wrong to assign the led to netdev as the kernel can't control them...

https://github.com/openwrt/openwrt/blob/fcff86be06da37e1b0839d12efd4a5afc40e8973/target/linux/ipq40xx/files/arch/arm/boot/dts/qcom-ipq4019-cm520-79f.dts#L132-L145

The LEDs on the device are controlled by GPIO and have no default trigger properties in dts.

According to my tests, the LEDs won't work if we don't assign them to netdev triggers.

**Comment by robimarko** [comment]
Hm, its rather weird that they dont blink if you manually add netdev trigger, that should really work

**Comment by Ansuel** [comment]
> Hm, its rather weird that they dont blink if you manually add netdev trigger, that should really work

think you got this wrong... leds correctly blink if they are added to netdev.

**Comment by robimarko** [comment]
Oh, then just add them via `01_leds` like for others

**Comment by Ansuel** [comment]
@redchenjs can you rebase? @robimarko aside from led is this good?

**Comment by redchenjs** [comment]
> @redchenjs can you rebase? @robimarko aside from led is this good?

Done.

**Comment by robimarko** [comment]
@Ansuel LGTM, so:
`Reviewed-by: Robert Marko <robimarko@gmail.com>`

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in 57577bb8ccaa79adc30e0c4b1f85a88a84e3ebfe.

**Pull request closed without merging**
