### PR TITLE
ath10k-ct: update to latest release

### PR DESCRIPTION
**Pull request by rodsmar**
- Changelog:

1.  Remove upstreamed 164-ath10k-commit-rates-from-mac80211.patch

- Runtime-tested on TP-Link Archer C6 V2 (US) - ath79 

Signed-off-by: Rodrigo B. de Sousa Martins <rodrigo.sousa.577@gmail.com>

### CODE REVIEW

**Comment by nicklowe** [comment]
There will almost certainly be another revision soon of ath10k-ct to include fixes for the FragAttacks issues.

**Comment by huaracheguarache** [comment]
> There will almost certainly be another revision soon of ath10k-ct to include fixes for the FragAttacks issues.

I think that's been patched in mac80211: https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=025bd93f36c9923127674ce127e22933592cba6c

**Comment by nicklowe** [comment]
Please refer to https://www.mail-archive.com/openwrt-devel@lists.openwrt.org/msg58655.html and https://www.mail-archive.com/openwrt-devel@lists.openwrt.org/msg58842.html

**Comment by huaracheguarache** [comment]
And here I merrily sat thinking I had a router that had been patched... Thanks for the heads up!

On the topic of the PR: it would probably be a good idea to take the opportunity to change PKG_RELEASE=2 to PKG_RELEASE=$(AUTORELEASE)

**Comment by anomeome** [comment]
[patched](http://lists.openwrt.org/pipermail/openwrt-devel/2021-June/035423.html), a new one?

**Comment by huaracheguarache** [comment]
I've given the patches a spin and everything seems to be working fine. Should I make a new PR, or do you want to update yours, @rodsmar?

**Comment by nicklowe** [comment]
I suggest to open a new PR that does not have the formal issues that this one does.

**Comment by huaracheguarache** [comment]
Ok, I've created a new pull request here: #4228

**Comment by adschm** [comment]
This seems to be abandoned by the submitter. Closing it in favor of the newer PR.

**Pull request closed without merging**
