### PR TITLE
ipq40xx: add Linksys MR8300 WAN port

### PR DESCRIPTION
**Pull request by jcassette**
Fix [FS#4227](https://bugs.openwrt.org/index.php?do=details&task_id=4227)

Signed-off-by: Julien Cassette <jcassette@users.noreply.github.com>

### CODE REVIEW

**Comment by adschm** [comment]
Missing commit message (explanation/justification of the change.)

**Comment by jcassette** [comment]
Hi @adschm
I have edited the commit message
Let me know if you have any suggestion
Julien

**Comment by musashino205** [comment]
You need to use your real email address in the commit. The use of github's address is not allowed.

**Comment by jcassette** [comment]
Okay, I have edited the commit.

**Comment by jcassette** [comment]
Hi. Is there anything else needed to get this merged? Thanks, Julien

**Comment by mans0n** [comment]
Please wrap the commit message to 75 characters per line.

And as I heard, this will make both LAN and WAN belong to the same VLAN ID. Is it intended/okay?
https://github.com/openwrt/openwrt/pull/2883#discussion_r403429241

**Comment by jcassette** [comment]
> Please wrap the commit message to 75 characters per line.

Okay, I have edited the commit message.
 
> And as I heard, this will make both LAN and WAN belong to the same VLAN ID. Is it intended/okay? [#2883 (comment)](https://github.com/openwrt/openwrt/pull/2883#discussion_r403429241)

This seems to be the default configuration for similar hardware. One can always create a new VLAN and assign the WAN/LAN ports differently. Note that the CPU interfaces (eth0 and eth1) are on the same switch port (number 0) and so they will always belong to the same VLANs.

For reference, I am attaching the configuration that I have been running with this change. It is working fine :-)

Capture

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
