### PR TITLE
base-files: emmc: invalidate kernel image while rootfs is being written

### PR DESCRIPTION
**Pull request by Lanchon**
Some setups have alternate boot actions in case the main OS fails to boot. These can include a secondary copy of the OS, a recovery OS, a fallback to TFTP boot, etc.

This commit invalidates the kernel image while rootfs is being written which, if a sysupgrade is interrupted, will trigger an alternate boot action in devices that support it. This results in safer sysupgrades.

----

this change has been tested to work properly in spectrum sax1v1k.

### CODE REVIEW

**Comment by Lanchon** [comment]
@dangowrt, @robimarko 

may i interest you guys on this?

**Comment by dangowrt** [comment]
Nice work, thank you. @mrkiko might want to have a look at it as well.

**Comment by mrkiko** [comment]
LGTM - even tough I am not a fan of added sync calls, even tough I can understand their purpose.

**Comment by Lanchon** [comment]
> LGTM - even tough I am not a fan of added sync calls, even tough I can understand their purpose.

the sync calls are necessary to order the writes so that this works. without sync, these changes make no sense.

also, sync will happen soon enough after the upgrade finishes and before reboot. doing it earlier does not cause any writes that would not end up happening in a few seconds anyway. (except for the small 1K zero write needed to invalidate the kernel.) with this in mind, i don't know how these syncs could be viewed to be negative in any way.

**Comment by Lanchon** [comment]
@dangowrt thanks Dan!!

**Pull request merged**
