### PR TITLE
kernel: bump 6.1 to 6.1.103

### PR DESCRIPTION
**Pull request by zxlhhyccc**
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.103

Removed upstreamed:
generic/backport-6.1/412-v6.3-01-spidev-Add-Silicon-Labs-EM3581-device-compatible.patch

See: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.103&id=c6c419ed94788ca13334b4acd50167b7f6d00a06

All other patches automatically rebased.

1、kernel: mtdtests: update for 6.1 as well
6.1.103 and 6.6.44 introduced breakage complaining about missing mtd_test.ko
for some targets.

Build system: bcm4908 bcm53xx

### CODE REVIEW

**Comment by zxlhhyccc** [comment]
I'm sorry, accidentally delete https://github.com/openwrt/openwrt/pull/16063 this branch of PR, this is resubmitted PR.

**Comment by robimarko** [comment]
Please remove the fixes tag from the kmod commit, and shorten the title to something more like:
`kernel: mtdtests: update for 6.1 as well`

**Comment by zxlhhyccc** [comment]
@robimarko It has been modified.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
