### PR TITLE
mpc85xx: p1010: fix NAND devices

### PR DESCRIPTION
**Pull request by neheb**
Upstream commit 9ba0cae3cac07c21c583f9ff194f74043f90d29c made FSL_IFC visible and selectable, which means that in order for MTD_NAND_FSL_IFC to work, it needs these two extra CONFIG options.

ping @hauke 

This needs backporting to 23.05 as that commit was backported to 5.15 as well.

Also see:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=9ba0cae3cac07c21c583f9ff194f74043f90d29c
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=45547a0a93d85f704b49788cde2e1d9ab9cd363b

### CODE REVIEW

**Comment by neheb** [comment]
ping @Shine-

**Comment by Shine-** [comment]
Applied to 23.05-SNAPSHOT, working fine again!
<details><summary>boot log</summary>

```
[    0.549009] printk: console [ttyS0] enabled
[    0.559404] nand: device found, Manufacturer ID: 0xad, Chip ID: 0xdc
[    0.565830] nand: Hynix H27U4G8F2DTR-BC
[    0.569674] nand: 512 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    0.577792] Bad block table found at page 262080, version 0x01
[    0.584300] Bad block table found at page 262016, version 0x01
[    0.590408] nand_read_bbt: bad block at 0x000004760000
[    0.596261] 8 fixed-partitions partitions found on MTD device ff800000.flash
[    0.603372] Creating 8 MTD partitions on "ff800000.flash":
[    0.608874] 0x000000000000-0x000000020000 : "wg-dtb"
[    0.614816] 0x000000020000-0x000000520000 : "kernel"
[    0.621432] 0x000000520000-0x000007f00000 : "wg-sysa-rootfs"
[    0.628595] 0x000007f00000-0x000008400000 : "wg-sysb-kernel"
[    0.636010] 0x000008400000-0x000009c00000 : "wg-sysb-rootfs"
[    0.642573] 0x000009c00000-0x00000a100000 : "wg-sysa2-kernel"
[    0.650015] 0x00000a100000-0x000011ae0000 : "wg-sysa2-rootfs"
[    0.657305] 0x000011ae0000-0x000020000000 : "ubi"
[    0.667809] fsl,ifc-nand ff800000.nand: IFC NAND device at 0xff800000, bank 0
[    0.675406] fsl_espi ffe07000.spi: cs=0, init_csmode=0x100008
[    0.685941] spi-nor spi0.0: mx25l8005 (1024 Kbytes)
[    0.691317] 4 fixed-partitions partitions found on MTD device spi0.0
[    0.697737] Creating 4 MTD partitions on "spi0.0":
[    0.702542] 0x000000000000-0x000000090000 : "u-boot"
[    0.708405] 0x000000090000-0x0000000a0000 : "u-boot-env"
[    0.715437] 0x0000000a0000-0x0000000c0000 : "cfgxxx"
[    0.721258] 0x0000000c0000-0x000000100000 : "device_id"
[    0.728291] OF: Bad cell count for /soc@ffe00000/spi@7000/flash@0/partitions
[    0.737286] fsl_espi ffe07000.spi: irq = 59
```
</details>

Thanks a lot, you're showing some breathtaking performance here, without even owning a comparable device!

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by robimarko** [comment]
Backported to 23.05 as well.

**Comment by Shine-** [comment]
@robimarko
Please also have a look at #16310, this is verified working now as well. Thanks!

**Pull request merged**
