### PR TITLE
qualcommax: apm: remove platform_get_resource

### PR DESCRIPTION
**Pull request by neheb**
ping @robimarko

### CODE REVIEW

**Comment by neheb** [comment]
ping

**Comment by robimarko** [comment]
This is not working:
```
[    0.085793] qcom,msm-apm b111000.apm: can't request region for resource [mem 0x0b111000-0x0b111fff]
[    0.085813] qcom,msm-apm b111000.apm: Failed to map PM APCC Global registers
[    0.085819] qcom,msm-apm b111000.apm: Failed to initialize APM controller device: ret=-16
[    0.085827] qcom,msm-apm: probe of b111000.apm failed with error -16
```

**Comment by KanjiMonster** [comment]
> This is not working:
> 
> ```
> [    0.085793] qcom,msm-apm b111000.apm: can't request region for resource [mem 0x0b111000-0x0b111fff]
> [    0.085813] qcom,msm-apm b111000.apm: Failed to map PM APCC Global registers
> [    0.085819] qcom,msm-apm b111000.apm: Failed to initialize APM controller device: ret=-16
> [    0.085827] qcom,msm-apm: probe of b111000.apm failed with error -16
> ```

-16 is `-EBUSY`.

The conversion looks correct, but there seems to be a resource conflict in the dts(i):

ipq8074-cpr-regulator.dtsi:

```
	apc_apm: apm@b111000 {
		compatible = "qcom,ipq807x-apm";
		reg = <0xb111000 0x1000>;
```

vs.

ipq8074.dtsi:

```
		apcs_glb: mailbox@b111000 {
			compatible = "qcom,ipq8074-apcs-apps-global",
				     "qcom,ipq6018-apcs-apps-global";
			reg = <0x0b111000 0x1000>;
```

which is likely triggering the `-EBUSY`.

**Comment by robimarko** [comment]
Ugh yes, it's the good old issue with a lot of stuff being in the APCS address space.

The solution is the same as for the A53 PLL, the APCS mailbox driver needs to register the APM one which means more patching but then there is no need for resource assignment as APCS will pass its regmap of the whole space.

**Comment by neheb** [comment]
so this needs dts changes. Lovely :).

**Comment by robimarko** [comment]
You cannot fix this with just DTS changes as multiple drivers are using the same register space.

I will work on replacing this APM driver with a much simpler one that gets registered by APCS and uses its regmap.

**Comment by neheb** [comment]
@robimarko rebased. Should I close this?

**Comment by robimarko** [comment]
@neheb You can close it as it wont work like this, I am like halfway through writing a new driver that gets registered via APCS

**Pull request closed without merging**
