### PR TITLE
build: store artifacts in JSON

### PR DESCRIPTION
**Pull request by aparcar**
Multiple profiles create artifacts, these should be stored in the JSON
file as well, allowing downstream tooling to show those files, too.

Artifacts don't have specific filesystems so only the fields `name`,
`type` and `sha256` are available.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
@dangowrt as requested, please test.

**Review by dangowrt — APPROVED** [review]
Works great for me.

**Comment by aparcar** [comment]
I'm wondering if it's a better solution to keep everything in the "images" field, thoughts?

**Comment by aparcar** [comment]
@mwarning do you have an opinion on that?

**Comment by aparcar** [comment]
Example of current output:

<details>
<pre>
{
        "arch_packages": "aarch64_cortex-a53",
        "default_packages": ["base-files", "blockdev", "busybox", "ca-bundle", "dnsmasq", "dropbear", "firewall", "fstools", "ip6tables", "iptables", "kmod-gpio-button-hotplug", "kmod-ipt-offload", "kmod-leds-gpio", "kmod-mt7615-firmware", "kmod-mt7615e", "libc", "libgcc", "libustream-wolfssl", "logd", "mtd", "netifd", "odhcp6c", "odhcpd-ipv6only", "opkg", "ppp", "ppp-mod-pppoe", "procd", "uboot-envtools", "uci", "uclient-fetch", "urandom-seed", "urngd", "wpad-basic-wolfssl"],
        "metadata_version": 1,
        "profiles": {
                "bananapi_bpi-r64": {
                        "artifacts": [{
                                "name": "openwrt-mediatek-mt7622-bananapi_bpi-r64-sdcard.img.gz",
                                "sha256": "9b63c94f16e459595b7991e5cb8a4b8b37d5a2c7ace3408a325be7b57e82e6d9",
                                "type": "sdcard.img.gz"
                        }, {
                                "name": "openwrt-mediatek-mt7622-bananapi_bpi-r64-emmc-preloader.bin",
                                "sha256": "7edb7c5597beb15e7a4daf550dbec40f48ec26af8dbc485132cb3a3382c17972",
                                "type": "emmc-preloader.bin"
                        }, {
                                "name": "openwrt-mediatek-mt7622-bananapi_bpi-r64-emmc-bl31-uboot.fip",
                                "sha256": "b229c157b7701de39d372ac20a4bd4d17ecabbc2b1a6901197f1459134a53888",
                                "type": "emmc-bl31-uboot.fip"
                        }, {
                                "name": "openwrt-mediatek-mt7622-bananapi_bpi-r64-snand-preloader.bin",
                                "sha256": "84d5f5c72a60a2bd626172881676e75ed8985a747ac7296c68d21fb3692cee68",
                                "type": "snand-preloader.bin"
                        }, {
                                "name": "openwrt-mediatek-mt7622-bananapi_bpi-r64-snand-bl31-uboot.fip",
                                "sha256": "5f6bdd95cf30a34058c8615bed202784c1788e33086cc4452a15030cebf97a12",
                                "type": "snand-bl31-uboot.fip"
                        }],
                        "device_packages": ["kmod-ata-ahci-mtk", "kmod-btmtkuart", "kmod-usb3", "e2fsprogs", "mkf2fs", "f2fsck"],
                        "image_prefix": "openwrt-mediatek-mt7622-bananapi_bpi-r64",
                        "images": [{
                                "filesystem": "squashfs",
                                "name": "openwrt-mediatek-mt7622-bananapi_bpi-r64-squashfs-sysupgrade.itb",
                                "sha256": "d26cde93a4cdcf8f5f3f3482ee77cd07d766c9c322f85a7e4c7594c437d1aac7",
                                "type": "sysupgrade"
                        }, {
                                "filesystem": "initramfs",
                                "name": "openwrt-mediatek-mt7622-bananapi_bpi-r64-initramfs-recovery.itb",
                                "sha256": "2b444a3e111e1bf29af9065fa6cb7e232fb8f3873873118b77f6c66d848856c3",
                                "type": "kernel"
                        }],
                        "supported_devices": ["bananapi,bpi-r64"],
                        "titles": [{
                                "model": "BPi-R64",
                                "vendor": "Bananapi"
                        }]
                }
        },
        "source_date_epoch": "1631501031",
        "target": "mediatek/mt7622",
        "version_code": "r17502+25-0470159552",
        "version_number": "SNAPSHOT"
}
</pre>
</details>

**Comment by mwarning** [comment]
> @mwarning do you have an opinion on that?

Looks good to me.

**Comment by aparcar** [comment]
Reworked to be part of images. Please try again

**Comment by aparcar** [comment]
Merged.

**Pull request closed without merging**
