### PR TITLE
toolchain/gcc: bump gcc 11 to 11.2

### PR DESCRIPTION
**Pull request by rsalvaterra**
Patches automatically refreshed.

Run-tested (built images):
ath79/generic (TL-WDR3600)
mvebu/cortexa9 (Turris Omnia)

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by jospezial** [comment]
Run-tested (built images):
lantiq VGV7510KW22 (o2 Box 6431)

**Comment by jospezial** [comment]
@rsalvaterra Are there any changes between your force-pushes besides setting this on top of master? Can we get this PR merged?

**Comment by rsalvaterra** [comment]
No changes at all, just trivial rebasing. It can be merged at any time.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master.

**Pull request closed without merging**
