### PR TITLE
util-linux: Update to 2.34

### PR DESCRIPTION
**Pull request by diizzyy**
Update util-linux to 2.34
Refresh patch

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master
Run tested: mvebu, Linksys WRT3200ACM, OpenWrt master

**Comment by diizzyy** [comment]
@ynezz 
This should be labeled packages for consistency

**Comment by diizzyy** [comment]
Compile tested: ipq40xx, Linksys EA6350v3, OpenWrt master
Run tested: ipq40xx, Linksys EA6350v3, OpenWrt master

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
