### PR TITLE
package: add option to enable RSS support for r8125 and r8126

### PR DESCRIPTION
**Pull request by p-w-p**
Add option to enable RSS support for r8125 and r8126 for better RX performance.

### CODE REVIEW

**Comment by aiamadeus** [comment]
The title is a bit misleading because there is a target called realtek but they are not related.
However, rss should be an option rather than turned on by default.
Because some machines (especially on the x86 platforms), turning on rss will make the rtl8125 network card very unstable.

**Comment by p-w-p** [comment]
Apologies for the title, should I change it to package: enable rss support for r8125 and r8126?
The RSS support for r8125 has been verified [downstream](https://github.com/immortalwrt/immortalwrt/blob/master/package/kernel/r8125/Makefile) for a long time, but I haven't noticed any related issues. Can you provide a related report?

**Comment by Noltari** [comment]
> The title is a bit misleading because there is a target called realtek but they are not related. However, rss should be an option rather than turned on by default. Because some machines (especially on the x86 platforms), turning on rss will make the rtl8125 network card very unstable.

@p-w-p as @aiamadeus pointed out I'd rather keep RSS disabled or provide it as an option, but if Realtek provides the drivers with that option disabled by default that usually means that it can cause unexpected issues...

**Comment by p-w-p** [comment]
@Noltari @aiamadeus Thanks for the suggestion, the modification has been made as requested!

**Comment by Noltari** [comment]
@p-w-p see https://github.com/openwrt/openwrt/pull/16142
The problem with your approach is that the only way to have RSS support is by manually building the package with that option enabled.
In my opinion it's better to add build variants and have two packages: one with RSS support and another one without it.

**Comment by p-w-p** [comment]
https://github.com/openwrt/openwrt/pull/16142

**Pull request closed without merging**
