### PR TITLE
kernel: Fix multiple Ethernet drivers after ndo_do_ioctl removal

### PR DESCRIPTION
**Pull request by hauke**
* ltq-ptm: Fix netdev ioctls with kernel > 5.15
    
    .ndo_do_ioctl is not called for SIOCDEVPRIVATE any more, the kernel
    calls .ndo_siocdevprivate now.
    
    See upstream Linux kernel commit:
    https://git.kernel.org/linus/b9067f5dc4a07c8e24e01a1b277c6722d91be39e

 * ath79: Fix PHY access over ag71xx driver
    
    .ndo_do_ioctl is not called any more. For PHY MII ioctl handling, the
    kernel calls .ndo_eth_ioctl now.
    
    The SIOCSIFHWADDR and SIOCGIFHWADDR operation are handled in the generic
    code in the same way just with more input validation.
    
    See upstream Linux kernel commit:
    https://git.kernel.org/linus/a76053707dbf0dc020a73b4d90cd952409ef3691
    
    Reported-by: Cthulhu88 in https://forum.openwrt.org/t/ethernet-leds-control-for-tp-link-tl-wr1043nd-v2-v3/202378

 * ramips: eth: Fix PHY access over mtk_eth_soc driver
    
    .ndo_do_ioctl is not called any more. For PHY MII ioctl handling, the
    kernel calls .ndo_eth_ioctl now.
    
    See upstream Linux kernel commit:
    https://git.kernel.org/linus/a76053707dbf0dc020a73b4d90cd952409ef3691
    
    Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

 * ipq40xx: eth: Fix PHY access over ipqess driver
    
    .ndo_do_ioctl is not called any more. For PHY MII ioctl handling, the
    kernel calls .ndo_eth_ioctl now.
    
    See upstream Linux kernel commit:
    https://git.kernel.org/linus/a76053707dbf0dc020a73b4d90cd952409ef3691

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
Hmm upstream ag71xx doesn’t use a custom function: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/drivers/net/ethernet/atheros/ag71xx.c?id=a76053707dbf0dc020a73b4d90cd952409ef3691

**Comment by hauke** [comment]
> Hmm upstream ag71xx doesn’t use a custom function: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/drivers/net/ethernet/atheros/ag71xx.c?id=a76053707dbf0dc020a73b4d90cd952409ef3691

Upstream ag71xx stores the phy handle in `dev->phydev`, our driver stores it in `ag->phy_dev`.
https://elixir.bootlin.com/linux/v5.15.162/source/drivers/net/phy/phy.c#L396

**Comment by neheb** [comment]
> > Hmm upstream ag71xx doesn’t use a custom function: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/drivers/net/ethernet/atheros/ag71xx.c?id=a76053707dbf0dc020a73b4d90cd952409ef3691
> 
> Upstream ag71xx stores the phy handle in `dev->phydev`, our driver stores it in `ag->phy_dev`. https://elixir.bootlin.com/linux/v5.15.162/source/drivers/net/phy/phy.c#L396

There’s a further problem that upstream uses phylink. Guess this needs to be kept.

**Comment by neheb** [comment]
I just whipped up https://github.com/neheb/openwrt/commit/37da869947480169ac4e536bbb6761691bc8ee29 . Untested so far.

**Review by namiltd — APPROVED** [review]

**Comment by hauke** [comment]
> I just whipped up [neheb@37da869](https://github.com/neheb/openwrt/commit/37da869947480169ac4e536bbb6761691bc8ee29) . Untested so far.

Someone should test this commit before we merge it. I would go with the current changes which should not break anything which is currently working. You can do this as a follow up PR.

**Comment by robimarko** [comment]
`Reviewed-by: Robert Marko <robimarko@gmail.com>` for ipq40xx.

**Comment by lister-wrt** [comment]
Tested on a tdw8980 (lantiq/xrx200, vdsl line).
```
Sun Jul 28 14:49:08 2024 daemon.notice dsl-notify: Switching to TC-Layer EFM/PTM
Sun Jul 28 14:49:08 2024 kern.info kernel: [   61.819017] Lantiq PTM driver, version 1.0.27, (c) 2001-2013 Lantiq Deutschland GmbH
Sun Jul 28 14:49:08 2024 kern.info kernel: [   61.819017]     PTM (E1) firmware version 2.16.0
Sun Jul 28 14:49:08 2024 kern.warn kernel: [   61.830018] ifxmips_ptm: PTM init succeed
```

**Pull request merged**
