### PR TITLE
ipq40xx: update E2600AC c1/c2 board

### PR DESCRIPTION
**Pull request by zhangsd20**
Modified the radio frequency hardware part of e2600ac c1/c2,
need to cooperate with the modified board.bin file, the device
can work normally.

Signed-off-by: 张 鹏 <sd20@qxwlan.com>

### CODE REVIEW

**Comment by chunkeey** [comment]
I've seen you posted the boardfiles to the ML already. Merged.

**Comment by zhangsd20** [comment]
Thanks.


I see it is merged into master branch.


Will it be merged in 22.03?
















在2022年03月26 01时16分，"Christian ***@***.***>写道：


I've seen you posted the boardfiles to the ML already. Merged.

**Comment by chunkeey** [comment]
> Will it be merged in 22.03?

yes, it is queued. openwrt-22.03 will ship with the updated boardfiles.

**Comment by Neustradamus** [comment]
Replaces:
- https://github.com/openwrt/openwrt/pull/9546

Merged commit:
- https://github.com/openwrt/openwrt/commit/bdc786e82c13547b01bd8f699d00598a974c14f6

**Pull request closed without merging**
