### PR TITLE
libjson-c: update to 0.13.1

### PR DESCRIPTION
**Pull request by dengqf6**
Update libjson-c to 0.13.1
Run tested on mvebu

### CODE REVIEW

**Comment by dedeckeh** [comment]
What is the size increase ?

**Comment by dengqf6** [comment]
About 7kB

**Comment by neheb** [comment]
Could try to reduce size with -Wl,--gc-sections,--as-needed and whatnot.

**Comment by diizzyy** [comment]
This has been shot down multiple times due to size concerns

**Comment by tapper82** [comment]
change log i think.
https://github.com/json-c/json-c/blob/master/ChangeLog

**Comment by dengqf6** [comment]
Oh 0.14 is out, which has removed some deprecated APIs so it may be smaller..

**Comment by NeoRaider** [comment]
Some of us discussed this at the OpenWrt dev meeting in Hamburg, and we came to the conclusion that we can't put off updates of core components forever because of size concerns. In short: thanks, merged!

**Comment by dengqf6** [comment]
@lucize ?

**Comment by lucize** [comment]
@dengqf6 yes, after a clean build it worked, would be cool if init or the rest of dependent binary was also rebuilt with this so it will not crash for the others that are still doing dirty builds

**Comment by jow-** [comment]
> @dengqf6 yes, after a clean build it worked, would be cool if init or the rest of dependent binary was also rebuilt with this so it will not crash for the others that are still doing dirty builds

https://git.openwrt.org/?p=openwrt/staging/jow.git;a=commitdiff;h=56d908703eee9b0ea207b853646030e6922b1efc

**Pull request closed without merging**
