### PR TITLE
config: kernel: Add support for configuring BTRFS to be built-in

### PR DESCRIPTION
**Pull request by elkablo**
Add the KERNEL_BTRFS_FS config option so that targets can select whether BTRFS support must be built-in.

Select this option (alongside KERNEL_BTRFS_FS_POSIX_ACL) from the layerscape/armv8_64b subtarget instead of enabling it in target/linux/layerscape/armv8_64b/config-* files.

Move disabling of CONFIG_BTRFS_FS_CHECK_INTEGRITY into generic configs.

This makes it possible for OpenWRT to be built with built-in BTRFS support on specific boards, instead of whole targets.

### CODE REVIEW

**Comment by elkablo** [comment]
@robimarko @dangowrt @rmilecki @hauke if some of you could find some time to take a look at this. Basically I wan't to be able to select BTRFS to be built-in, in order to be able to boot OpenWRT off a BTRFS root partition.

**Comment by robimarko** [comment]
Hi, I am on vacation, will look after I come back.

**Comment by john-tho** [comment]
> makes it possible for OpenWRT to be built with built-in BTRFS support on specific boards, instead of whole targets.

OpenWrt buildbot is setup to build a single kernel for each (sub)target, so may need to reword this. Example buildbot config: https://downloads.openwrt.org/snapshots/targets/layerscape/armv8_64b/config.buildinfo

Relevant OpenWrt config symbols:
- `CONFIG_BUILDBOT` (but builds all kmods, not needed to demonstrate `DEPENDS`)
- `CONFIG_TARGET_MULTI_PROFILE`
- `CONFIG_TARGET_PER_DEVICE_ROOTFS`

I think the `target.mk` `DEPENDS` on this symbol would prevent buildbot building that image (if the new `BTRFS` symbol is not set), so you would need to `default y if TARGET_layerscape_armv8_64b` in `Config-kernel.in` to maintain current config and images.

**Comment by elkablo** [comment]
> I think the `target.mk` `DEPENDS` on this symbol would prevent buildbot building that image (if the new `BTRFS` symbol is not set), so you would need to `default y if TARGET_layerscape_armv8_64b` in `Config-kernel.in` to maintain current config and images.

The dependency says `+@KERNEL_BTRFS_FS`. The `+@SYMBOL` means that if the target is selected, it will cause `CONFIG_SYMBOL` to also be selected.

Indeed using the `config.buildinfo` you linked as `.config` and running `echo | make oldconfig` sets everything up correctly.

A agree that I may have to change the wording.

**Pull request merged**
