### PR TITLE
tools: refresh all patches

### PR DESCRIPTION
**Pull request by neheb**
CI mandates clean patches in the packages feed but not here. Hrm.

### CODE REVIEW

**Comment by Ansuel** [comment]
We actually do the same here but those packages depends on the target so they were never checked... for tools is should really check why the action doesn't work with checking to-refresh patches...

**Comment by neheb** [comment]
I just noticed these lz4 patches are completely pointless. meson is used for lz4, not make.

**Comment by neheb** [comment]
@Ansuel is this ready to go?

**Comment by Ansuel** [comment]
@neheb I would ask just some additional hours or maybe a day... I just fixed a bug with tools/refresh and I introduced support for it in CI

**Comment by Ansuel** [comment]
@neheb can I drop the packages commit and can we handle that in a different PR?

**Comment by neheb** [comment]
OK

**Comment by Ansuel** [comment]
@neheb maybe create a dedicated branch for the packages commit so you don't lose it?

**Comment by neheb** [comment]
Yeah I got that.

**Comment by neheb** [comment]
@Ansuel slight modification. Smaller refresh.

**Pull request merged**
