### PR TITLE
ramips: improve Samsung CY-SWR1100 support

### PR DESCRIPTION
**Pull request by mans0n**
This patch does the following:

- rename flash partitions
- switch from gpio-keys-polled to gpio-keys
- add power LED and use it as status LED
- set correct PCI ID to compatible string in wifi node
- remove ralink,5ghz property in wifi node
- fix LAN/WAN MAC addresses and provide label MAC address
- add kmod-usb-ledtrig-usbport to DEVICE_PACKAGES

Rename devdata partition to devconf as indicated in the stock firmware
partition table:
00030000-00040000: "devdata"
00040000-00050000: "devconf"

Power LED can be controlled by SoC GPIO. Use power LED for status
indication and free WPS LED for other uses.

RT3092L supports only bgn mode, so it is unnecessary to disable 5GHz band.

Ethernet MAC address setup has been broken since c3e420f28cf1. Restore
original setting.

### CODE REVIEW

**Comment by mans0n** [comment]
Note: WiFi 2.4GHz works, but it fails on some situation. [FS#2587](https://bugs.openwrt.org/index.php?do=details&task_id=2587)

**Comment by adrianschmutzler** [comment]
Please split this down a little into separate commits.
In particular:
1. Make the 02_network fix a separate commit and add a "Fixes: ..." to the commit message, referring to the initial commit breaking it. Good find!
2. Have you tested extensively with gpio-keys? You will be the first one using that on ralink subtarget.
3. Are the u-boot* partition labels also renamed based on vendor firmware?

You might end up with 5-8 commits here, but I think this would be more appropriate for this case, and would also give you the opportunity to provide details on each change :-)

**Comment by adrianschmutzler** [comment]
We will have to backport the 02_network fix down to 17.01 ...

**Comment by mans0n** [comment]
@adrianschmutzler Okay, but it will take some time.

2. I think I have, but I'll do more tests with it.

3. The whole partition table used by stock firmware is as follows:
00000000-00030000: "u-boot"
00030000-00038000: "boot env"
00030000-00040000: "devdata"
00040000-00050000: "devconf"
00050000-007f0000: "upgrade"
007f0000-00800000: "langpack"

**Comment by adrianschmutzler** [comment]
Maybe start with the 02_network fix, that one should be easy to build and review, and has no interdependencies.
You might either add label_mac already in that one, or do it separately, I'm agnostic about that.

**Comment by mans0n** [comment]
gpio-keys works well. keys are registered in /proc/interrupts, and pressed/timeout/released are all functional.
It seems many devices still use "uboot" and "uboot-env" partition names, so I removed that part from the PR.

Split into four commits.

**Comment by adrianschmutzler** [comment]
Merged everything but the usb-ledtrig-usbport patch. Will have a look on that later unless someone else does.

**Comment by mans0n** [comment]
@adrianschmutzler Thanks! I never thought it would be merged this soon.

**Pull request closed without merging**
