### PR TITLE
bmips: backport upstream RAC patches

### PR DESCRIPTION
**Pull request by Ansuel**
This is a testing commit that will be fixed later to text an alternative approach for RAC fixup on bmips.

---

@Noltari @danitool can you guys test this and check what do you think?

It may not work at all but i think (given my assumption are all correct) this is the good path to upstream this.

Probably better logic should be applied for `(read_c0_brcm_cmt_local() & (1 << 31))` but that is minor to the implementation proposal.

### CODE REVIEW

**Comment by danitool** [comment]
I tested the patch on BCM6358 (HG556a) and BCM6368 (VH4032N). It works ok, no errors or apparent issues.

BTW I had to delete the documentation patch because it didn't apply correctly.

**Comment by Ansuel** [comment]
@danitool thanks a lot. This patchset comes from linux-next so it's expected that the documentation patch doesn't apply.

@Noltari This is pretty much done, I would wait your check and then I would try to upstream if... Still maybe we should check if RAC is enabled to decide if dma sync should be disabled or not. What do you think?

**Comment by Ansuel** [comment]
@Noltari just to know are you aware if the cbr address change or is always the same in the system (aka calling the register from different cpu doesn't report a different addr?)

**Comment by Ansuel** [comment]
Seems upstreaming is going smooth

**Comment by Noltari** [comment]
Rebased on latest main with v6.6 kernel, updated patches to v8 and backported upstream patch.

Thanks @Ansuel!

**Comment by Ansuel** [comment]
They merged them? I didn't receive the confirm email

Il Mar 25 Giu 2024, 11:24 Álvaro Fernández Rojas ***@***.***>
ha scritto:

**Comment by Noltari** [comment]
> They merged them? I didn't receive the confirm email

Nope, but I was testing this on latest kernel after updating it to v6.6 and since upstreaming is progressing I thought I could just update this to make it easier once they merge them.

**Comment by Noltari** [comment]
> @Noltari pretty busy, patch got merged in bmips-next... can you by chance backport them, update this pr and merge it?

Yes, I will do that later today because I'm at work right now.
Thanks @Ansuel! :)

**Pull request merged**
