### PR TITLE
Support for Xiaomi MiWifi R3

### PR DESCRIPTION
**Pull request by gitnewcomer**
This pull request was a mistake, sorry.
I'm just testing the support for Xiaomi MiWifi R3.
If you can delete this pull request, please do it.
Thanks!

### CODE REVIEW

**Comment by cewbdex** [comment]
Hello, I wanted to try to port this router to OWRT and just found your PR, are you still working on it?

**Comment by Neustradamus** [comment]
@gitnewcomer, @cewbdex: It is really good to add this support!

Can you really look it?

**Comment by gitnewcomer** [comment]
@cewbdex @Neustradamus I stopped my tests because I found a repo where it was already ported: https://github.com/XFY9326/Xiaomi-R3-OpenWrt-Stable
You should be able to compile snapshot of OpenWRT using the modified files from the above repo... the files for the newest kernel can be found on X-WRT repo: https://github.com/x-wrt/x-wrt

**Comment by gitnewcomer** [comment]
> @gitnewcomer: Can you see with @XFY9326 to integrate it directly in OpenWrt upstream?

This isn't our work, but the work from X-WRT, we just added the corresponding changes to OpenWRT:
https://github.com/XFY9326/Xiaomi-R3-OpenWrt-Stable/blob/main/patches/0001-Support-MiWifi-R3.patch

For the OpenWRT Snapshot you need the patch for kernel 5.10 from X-WRT:
https://github.com/x-wrt/x-wrt/blob/master/target/linux/ramips/patches-5.10/0038-mtd-ralink-add-mt7620-nand-driver.patch

I don't know why it never has been integrated to OpenWRT, maybe source code doesn't comply with OpenWRT?

**Comment by cewbdex** [comment]
May we ask @ynezz and @dangowrt if there are any licencing problems?

**Comment by dangowrt** [comment]
There are no problems with the license, it's all GPL. However, the NAND driver is in very bad shape and unfit for submission upstream. And space limitations on other MT7620 boards (with only 4 or 8 megs of NOR flash and/or stupid partition layout/kernel size limitation) will force us to have an additional subtarget `ramips/mt7620-nand` with NAND driver and UBI enabled (as enabling that for all mt7620 boards will break many devices). All that seemed too much effort only to allow support of basically this one device. Imho it's a good candidate for a community build.

**Pull request closed without merging**
