### PR TITLE
kernel: x86_64: update kernel 5.4 config

### PR DESCRIPTION
**Pull request by nasbdh9**
Update the PCI configuration of the kernel, fix the problem that the PCIe device cannot run at full speed or the MaxPayload/MaxReadReq configuration is incorrect when certain devices, such as Mellanox VPI

Test platform: HP T730 / x86-64

Signed-off-by: Tan Zien <nabsdh9@gmail.com>

### CODE REVIEW

**Comment by mans0n** [comment]
While you are touching it, could you also run `make kernel_oldconfig` and `make kernel_oldconfig CONFIG_TARGET=subtarget`? (see 49795690e698)
Your diff is larger than needed (for example `CONFIG_PCI=y` is already in the target config), probably you can make it more compact.

**Comment by adschm** [comment]
On the formal side:
This lacks a commit message; prefix should be "x86:". If you want to include the subtarget, use "x86: 64:" or include the subtarget name in the text ...

**Comment by nasbdh9** [comment]
@mans0n @adschm update

**Comment by bobafetthotmail** [comment]
commit message is still missing

**Comment by adschm** [comment]
You obviously still haven't refreshed config as indicated by mans0n

**Pull request closed without merging**
