### PR TITLE
mwlwifi - Upgrade FW+debugfs+Driver

### PR DESCRIPTION
**Pull request by daloki83**
mwlwifi - Upgrade 88W8964 firmware to 9.3.2.4.
+Added debugfs file coredump.
Bump to latest commit

### CODE REVIEW

**Comment by anomeome** [comment]
_PKG_MIRROR_HASH_ appears incorrect.
I'm not sure about there being a disconnect between:
     cat /sys/kernel/debug/ieee80211/phy0/mwlwifi/info | grep -i driver
and this, seems _PKG_RELEASE_ might be better choice, but debateable.

**Comment by tapper82** [comment]
Hi can this Change driver version to 10.3.4.0-20180118?
https://github.com/kaloz/mwlwifi/commit/a149180fecec4fbaafb3f52ae46e33bd66501441

**Comment by anomeome** [comment]
Yes, @yuhhaurlin has now bumped the version number.

**Comment by daloki83** [comment]
Hopefully now everything is fine ?! Dont have many expirience with github...all i can say...with that makefiel everything work well on my build. So if something is wrong, please let me know how to make it better. My intention is just to bring such updated faster to the build (in the past it took (for my feeling) to long.

**Comment by anomeome** [comment]
My _hash_ on the latest push:

`0util@util0:~/br/dl$ sha256sum mwlwifi-10.3.4.0-20180118.tar.xz
2610d146d46fe58a7dd5b4b4a415c8ff4b6c0d1166654e4f6e00296d1c56648f  mwlwifi-10.3.4.0-20180118.tar.xz
`

You will also have to _squash_ the commits into one as per my previous link. See [here(Dec 21](https://github.com/lede-project/source/pull/526) for an explicit walk-through.

**Comment by daloki83** [comment]
Thanks @anomeome !!! I did now as written in your link. A new PR was created...https://github.com/openwrt/openwrt/pull/668
Is this correct ?
If yes, i have to close this PR ?

**Comment by anomeome** [comment]
There should only be the one PR(no need for the new one), with the amendments having been applied to this PR, and then all the commits _squashed_. So really just the second part of that walk-through, where you are making a change to an existing PR.

If you add _.patch_ to the URL in the address bar you will see the patch that would be generated as things are now, with 3 commits.

**Comment by daloki83** [comment]
OK, (maybe) i understand 👍  but this will only work, if you create the PR from shell...i made it directly through web gui...however i updatedet the file with the correct hash...if this PR should be still wrong, i will close them and give another one the chance to create a correct PR...btw. for LEDE it wasnt so complicated

**Comment by daloki83** [comment]
Outdated...new https://github.com/openwrt/openwrt/pull/692

**Pull request closed without merging**
