### PR TITLE
uboot-mvebu: update to v2020.10

### PR DESCRIPTION
**Pull request by dhewg**
Remove merged patches and update the emmc set.
Don't add CONFIG_NET_RANDOM_ETHADDR to defconfig.

### CODE REVIEW

**Comment by dhewg** [comment]
@hauke 
This is a continuation of #3360, can you please throw them on your pile? And these two are related #3405 #3442 and could go in too if you agree.

**Comment by Cornu** [comment]
@dhewg I'm looking at building this with [espressobin-nix](https://github.com/mirrexagon/espressobin-nix) and searched for the correct DDR_TOPOLOGY value and i noticed the value for [espressobin-v3-v5-1gb-1cs](https://github.com/dhewg/openwrt/blob/3686395eadc12457d9555b3f03e5672a56997120/package/boot/arm-trusted-firmware-mvebu/Makefile#L48) is wrong, shouldn't this be 4 (the same as the emmc build)?

**Review by tmn505 — APPROVED** [review]

**Comment by dhewg** [comment]
@Cornu indeed, thanks! Added a patch here #3442

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
