### PR TITLE
realtek: fix VLAN 1 special case

### PR DESCRIPTION
**Pull request by tomjnixon**
This removes the VLAN1 special case in the rtl83xx driver, so that VLAN1 is not enabled on all ports, and configurations without bridges work.

The failsafe hack which works around this is reverted.

So far I've only tested this on RTL8380M, so I'd be especially interested in feedback from people with other devices that this driver supports; that looks like mostly RTL8382: allnet_all-sg8208m, d-link_dgs-1210, d-link_dgs-1210.

I'm pretty sure that [this case](https://github.com/openwrt/openwrt/blob/dea4bae7c2b963af02e1e3e3bdb5cd656a5ea3d3/target/linux/realtek/files-5.4/drivers/net/dsa/rtl83xx/dsa.c#L903-L904) could be removed in the same style, but it's not clear what the original purpose was, and it shouldn't have any effect either way.

This fixes [this issue](https://lists.openwrt.org/pipermail/openwrt-devel/2021-June/035557.html), and there's some more background on the forum, [starting here](https://forum.openwrt.org/t/support-for-rtl838x-based-managed-switches/57875/595?u=tomn).

### CODE REVIEW

**Comment by RussellSenior** [comment]
Works for me without the bridge_vlan configuration on a Netgear GS108Tv3, e.g.:

> config interface 'wan'
>         option proto 'dhcp'
>         option device 'lan1'
> 
> config interface 'wan6'
>         option proto 'dhcpv6'
>         option device '@wan'
>         option reqprefix '60'

**Comment by tomjnixon** [comment]
Great, thanks for trying it out.

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master.

**Comment by tomjnixon** [comment]
thanks!

**Pull request closed without merging**
