### PR TITLE
prereq-build: increase python requirement

### PR DESCRIPTION
**Pull request by neheb**
The current minimum OS requirement for OpenWrt is Ubuntu 18.04, which includes 3.7 and 3.8. 3.7 is necessary to update tools/meson.

ping @eli-schwartz @dhewg @jow-

### CODE REVIEW

**Comment by eli-schwartz** [comment]
It might be worth explicitly describing in the error message for Ubuntu 18.04 that it will be necessary to `apt install python3.8` since the default python3 (probably preinstalled for system reasons) is 3.6 but 3.8 is available for people that explicitly want it.

It will be necessary to explicitly invoke python as `python3.8` rather than `python3` but that's probably fine.

(In the Meson CI container for Ubuntu 18.04, we scribble all over the system using update-alternatives to make this the default python. That's out of scope here.)

**Comment by neheb** [comment]
btw what's the upstream plan to migrate to 3.8, if any?

**Comment by eli-schwartz** [comment]
Nothing super exciting in 3.8 as far as Meson is concerned, as I recall -- so I think I'm actually fine with just waiting another year or two until something tempting comes along.

The most interesting 3.8 feature I use is `=` in f-strings and that's solely a debugging method. But 3.10 is desperately longed-for, KW_ONLY will help a lot... sad to say, we'll be waiting practically forever for that...

**Comment by neheb** [comment]
OK. Minimum can be updated to 3.8 later.

**Comment by dhewg** [comment]
LGTM, are buildbot and CI fulfilling the new req already?
Slightly related: #11747

**Comment by neheb** [comment]
buildbot is Debian 10 IIRC. Not an issue there.

CI is Ubuntu 22.04.

**Review by BKPepe — APPROVED** [review]

**Comment by hauke** [comment]
I would prefer if we wait with changing the minimum python version to after the next release was branched off. 
Ubuntu 18.04 uses python 3.6 by default.

**Comment by mpratt14** [comment]
this is me being picky and caught on small details again (words)

in my mind:

increase --> an additional check added to prereq-build for python
increment or bump --> version x.y to x.z

alternatively just title as "remove support for 3.6"

**Comment by robimarko** [comment]
Since we branched off, its probably time for this so meson can be updated.

**Comment by eli-schwartz** [comment]
Needs to be rebased on top of #10649 now that commit 7d0fb2cc34cb7aaa2b6eaca4f14f2c20778d3e40 has landed.

**Comment by neheb** [comment]
A variant was merged

**Comment by neheb** [comment]
For meson I'm sure @PolynomialDivision can handle it in https://github.com/openwrt/openwrt/pull/10543

**Pull request closed without merging**
