### PR TITLE
[22.03] tools/sed: update to 4.9

### PR DESCRIPTION
**Pull request by BKPepe**
Backported sed from the main branch. This version is also in OpenWrt 23.05.
The reason for backport:

- The latest MacOS update caused that I could not compile sed anymore while use OpenWrt 22.03.
- I hope I am right, but I tracked it down, the issue lies within gnulib, which is used as Git submodule for sed. Thus it is being a little bit hard to update submodule and hope that everything is alright and that there are no other commits necessary.
    - It is required to backport this commit: https://git.savannah.gnu.org/cgit/gnulib.git/commit/lib/obstack.c?id=0cc39712803ade7b2d4b89c36b143dad72404063

Changes between 4.9 and 4.8 can be found here:
https://git.savannah.gnu.org/gitweb/?p=sed.git;a=shortlog;h=refs/tags/v4.9

Fixes: https://github.com/openwrt/openwrt/issues/15270

### CODE REVIEW

**Comment by BKPepe** [comment]
Unfortunately, I need the same for coreutils as well, but that would be so complicated as there are so many changes between OpenWrt 22.03 and OpenWrt 23.05/main branch. 

@ynezz Do you have any idea how to add patch to submodule instead of bumping the submodule?

**Comment by BKPepe** [comment]
It seems that we need to update CI for OpenWrt 22.03 branch to apply same changes as in actions-shared-workflow or switch to use it as done in newer branches

**Comment by ynezz** [comment]
> The latest MacOS update caused that I could not compile sed anymore while use OpenWrt 22.03.

It would be nice to get the most important bit, the actual error message from that clang compiler.

> It is required to backport this commit: https://git.savannah.gnu.org/cgit/gnulib.git/commit/lib/obstack.c?id=0cc39712803ade7b2d4b89c36b143dad72404063

```diff
-static _Noreturn void
+static __attribute_noreturn__ void
```

IMO this could be worked around less intrusively, than by bumping sed to 4.9. Something clang/macOS specific should be good enough and acceptable, but very unlikely, that anyone is going to look into this and merge it due to EOL of the release, see bellow.

> It seems that we need to update CI for OpenWrt 22.03 branch to apply same changes as in actions-shared-workflow or switch to use it as done in newer branches

Version 22.03 is essentially at the end of its life. In my opinion, version 22.03.7 will likely be released very soon, marking the final update for 22.03. Therefore, I wouldn't expect that anyone will continue to invest time in this release.

**Comment by BKPepe** [comment]
> It would be nice to get the most important bit, the actual error message from that clang compiler.

That's in the referenced issue. IMHO, CI/CD will fail on this as well.

> this could be worked around less intrusively,

That's why I asked you if you do have any better way how to backport the patch for the Git submodule, but it does not seems so. Updating sed for host should not be issue at all and it was the fastest and easiest way how to fix it, but coreutils, I agree that it could introduce some unwanted features/bugfixes, which you simply dont want here.

> Therefore, I wouldn't expect that anyone will continue to invest time in this release.

Sad. Some downstream distributions needs to patch it or even locally before they will be able to switch to newer release. 🤷 
Then developers will be playing on their own ground to get working somehow at least. Someone is still using OpenWrt 22.03 release, though.

**Comment by robimarko** [comment]
@BKPepe We can just simply backport that gnulib fix and then it compiles on 22.03 for me:https://github.com/openwrt/openwrt/pull/15289

I got a Scaleway instance of M2 with 14.4.1 and it compiles with that.

I have to agree with @ynezz, 22.03 is basically EOL(We are already past the original EOL date) and 22.03.7 is the latest its going to get.
We cannot really influence downstream distributions.

**Comment by ynezz** [comment]
> @BKPepe We can just simply backport that gnulib fix and then it compiles on 22.03 for me:https://github.com/openwrt/openwrt/pull/15289

Great, thanks!

**Comment by BKPepe** [comment]
Hey @robimarko , it seems like I owe you a beer! :) Thank you for looking into it. Really appreciated. 👏 I haven't thought that the backport is so trivial. Otherwise, I would do that by myself. Thanks again.

**Pull request closed without merging**
