### PR TITLE
[22.03] uboot-mvebu: update to 2022.10

### PR DESCRIPTION
**Pull request by BKPepe**
It also allows dropping existing patches as they are all backports.

Backported from https://github.com/openwrt/openwrt/pull/10776

### CODE REVIEW

**Comment by BKPepe** [comment]
Guys @robimarko , @dhewg  and @paper42 could I get approve from you?

**Comment by robimarko** [comment]
I dont personally use nor test 22.03, but for the update itself:
`Reviewed-by: Robert Marko <robimarko@gmail.com>`

**Comment by paper42** [comment]
I also don't use 22.03 anywhere currently, but I can confirm that the 3 dropped patches are no longer necessary and that 2022.10 works on 21.02.

**Comment by dhewg** [comment]
Sorry, I too only use master. The backport looks good, but the other firmware components have different version there, so should be tested independently.

On the other side, does this need to be backported? One could just flash a firmware from master and run 22.03 with that?

**Comment by ynezz** [comment]
> It also allows dropping existing patches as they are all backports.

If 2022.10 contains some fixes you need, then selectively cherry-pick those only. We're not going to do such version bumps in stable releases.

**Comment by BKPepe** [comment]
> We're not going to do such version bumps in stable releases

Hmm, that's interesting. It seems you, as OpenWrt developers, are not unified and it seems like you are changing policy too often without reason.

In the past, my two pull requests were merged to the stable release:
- https://github.com/openwrt/openwrt/pull/9797 (this one by you)
- https://github.com/openwrt/openwrt/pull/10271 (by someone else from OpenWrt)

Anyway, having patched U-boot version can be somehow problematic for upstream to troubleshoot it. I would need approx. 20 patches, which are related to mvebu (especially those for A38X) to backport for uboot-mvebu 2022.07. They are not doing fixup releases. They are releasing a new version.

From your response, it is not understandable, why there could not be uboot-mvebu 2022.10, when it was properly tested and reviewed by others.

**Comment by ynezz** [comment]
> In the past, my two pull requests were merged to the stable release:

It was stable release branch, before 22.03.0 release. This is mostly OK, since no release was made yet, some regressions are more or less acceptable at this point of time.

> From your response, it is not understandable, why there could not be uboot-mvebu 2022.10

Every such update scream regressions, have [you forget already](https://github.com/openwrt/openwrt/pull/9409) ?

> when it was properly tested and reviewed by others.

I parse it differently.

**Pull request closed without merging**
