### PR TITLE
[23.05] ramips: add support for TP-Link Archer C5 v4

### PR DESCRIPTION
**Pull request by namiltd**
Patch https://github.com/openwrt/openwrt/pull/14599 successor. PR https://github.com/openwrt/openwrt/pull/14418 compatible with release 23.05.

TP-Link Archer C5 v4 is a dual band router with 5 GbE ports
Advertised as AC1200 for its 867Mbps (2x2) 5GHz band
and 300 Mbps (2x2) 2.4GHz band.

Specs:
- SoC: MediaTek MT7620A
- Ethernet: 5x GbE ports (Realtek RTL8367S)
- Wireless 2.4GHz: MediaTek MT7620A
- Wireless 5GHz: MediaTek MT7612E
- RAM: 64MiB
- ROM: 8MiB (GD25Q64CSIG)
- 1 USB 2.0 port
- 2 Buttons (WPS and reset)
- 8 LEDs

Currently, you can install OpenWrt via serial console or TFTP.

Flash instructions via serial console:
1. Rename the factory.bin to to test.bin
2. start a TFTP server from IP address 192.168.0.225 and serve the image named test.bin
3. connect your device to the LAN port
4. power up the router and press 4 on the console to stop the boot process.
5. enter the following commands on the router console
	tftp 0x80060000 test.bin
	erase tplink 0x20000 0x7a0000
	cp.b 0x80060000 0x20000 0x7a0000
	reset

Flash instructions via TFTP:
1. Update orginal firmware of the router to the latest one.
2. Rename openwrt-ramips-mt7620-tplink_archer-c5-v4-squashfs-tftp-recovery.bin to tp_recovery.bin
3. Change computer IP to 192.168.0.66
4. Run TFTP serwer
5. Start the router with the reset button pressed, the file will be automatically downloaded and after a while the router will restart.
6. After updating, set your computer's IP to DHCP

A little note: Since there are problems with the performance of 2.4GHz WiFi for Mediatek MT7620, disable 802.11w Management Frame Protection in Wireless Security.

### CODE REVIEW

**Comment by luizluca** [comment]
@namiltd, you should target main branch for new devices. I don't think a PR for a released version will ever be merged without the corresponding support for the next version.

**Comment by namiltd** [comment]
This PR without any changes will also work for "main".  For compatibility with the remaining dts files in the tree, you only need to move mac-address-increment to nvmem-cells.

**Comment by hauke** [comment]
Please target the main branch first. When it was merged into main you can create a new pull request with a backport to 23.05.

**Comment by namiltd** [comment]
Closed due to PR https://github.com/openwrt/openwrt/pull/14599 closing.

**Pull request closed without merging**
