### PR TITLE
mac80211: backport and update patch for ath10k

### PR DESCRIPTION
**Pull request by Ansuel**
This refresh and update patch version of the 2 patches that fix 160mhz on ath10k wireless driver. Also adds some patch from ath-next pushed upstream.

@hnyman 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
what patch should be backported?

**Comment by ecsv** [comment]
> After all, the issue @ecsv mentioned will also affect newer 9984 firmwares, right?

I am not sure why the QCA9984 firmware is mentioned here. Anway: I don't have the QCA changelogs but the 10.4-3.6.x with the same number should have similar features - include the DFS host confirmation mis-feature.

> what patch should be backported?

I think he means that the patches mentioned in https://github.com/openwrt/openwrt/pull/1138#issuecomment-403192221 have to be backported when a 10.4-3.6 firmware is used. And I am guessing that he assumes that there is a conflict between your change and the required changes for #1138

**Comment by Ansuel** [comment]
i can add that patch to this pr and then that pr can be merged after this

is it good? 

Applying that patch shoudn't brake wifi for older firmware right?

**Comment by chunkeey** [comment]
> Applying that patch shoudn't brake wifi for older firmware right?

No it shouldn't brake wifi for older firmware.

Unless there are older firmwares that have the WMI_SERVICE_HOST_DFS_CHECK_SUPPORT flag set, but have an incomplete or buggy implementation. (But this could be true for the current 10.4-3.6.x firmwares too).

**Comment by Ansuel** [comment]
ummm this applied well

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f40105e6747892e8edab94020567c158c9bec0df

i need to rework this... 

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=6f6eb1bcbeff48c875617b800f00f1c5d1b12290

**Comment by Ansuel** [comment]
just to not rebase the patch a lot...

adding this should be good...

https://patchwork.kernel.org/patch/10241601/

**Comment by Ansuel** [comment]
@chunkeey i backported the patch... ( i decided to add the needed patch instead of modify it, cleaner)

**Comment by Ansuel** [comment]
Currently testing the latest firmware... any idea how to test the reported problem?

**Comment by Ansuel** [comment]
@ecsv @hauke

**Comment by ecsv** [comment]
> Currently testing the latest firmware... any idea how to test the reported problem?

If you are talking about the DFS host confirmation: Enable a FCC country on the AP, switch to a DFS channel, start a DFS radar pattern generator (not sure whether you have the hardware for this) and check that the QCA firmware doesn't completely block TX & finishes the DFS host confirmation

**Comment by Ansuel** [comment]
I today tested with this

Mon Jul  9 11:50:35 2018 daemon.notice hostapd: wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
Mon Jul  9 11:50:35 2018 daemon.notice hostapd: ACS: Automatic channel selection started, this may take a bit
Mon Jul  9 11:50:35 2018 daemon.notice hostapd: wlan0: interface state COUNTRY_UPDATE->ACS
Mon Jul  9 11:50:35 2018 daemon.notice hostapd: wlan0: ACS-STARTED
Mon Jul  9 11:50:50 2018 daemon.notice hostapd: wlan0: ACS-COMPLETED freq=5260 channel=52
Mon Jul  9 11:50:50 2018 daemon.notice hostapd: wlan0: interface state ACS->HT_SCAN
Mon Jul  9 11:50:50 2018 daemon.notice hostapd: Switch own primary and secondary channel to get secondary channel with no Beacons from other BSSes
Mon Jul  9 11:50:50 2018 daemon.notice hostapd: wlan0: interface state HT_SCAN->DFS
Mon Jul  9 11:50:50 2018 daemon.notice hostapd: wlan0: DFS-CAC-START freq=5280 chan=56 sec_chan=-1, width=1, seg0=58, seg1=0, cac_time=60s
Mon Jul  9 11:51:54 2018 daemon.notice hostapd: wlan0: DFS-CAC-COMPLETED success=1 freq=5280 ht_enabled=0 chan_offset=0 chan_width=3 cf1=5290 cf2=0
Mon Jul  9 11:51:54 2018 daemon.err hostapd: Using interface wlan0 with hwaddr dc:ef:09:f2:5d:51 and ssid "No More Lag 5Ghz"
Mon Jul  9 11:51:54 2018 daemon.notice hostapd: WPS: Converting push_button to virtual_push_button for WPS 2.0 compliance
Mon Jul  9 11:51:54 2018 kern.info kernel: [  325.734534] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
Mon Jul  9 11:51:54 2018 kern.info kernel: [  325.734862] br-lan: port 3(wlan0) entered blocking state
Mon Jul  9 11:51:54 2018 kern.info kernel: [  325.740009] br-lan: port 3(wlan0) entered forwarding state
Mon Jul  9 11:51:54 2018 daemon.notice hostapd: wlan0: interface state DFS->ENABLED
Mon Jul  9 11:51:54 2018 daemon.notice hostapd: wlan0: AP-ENABLED
Mon Jul  9 11:51:54 2018 daemon.notice netifd: Network device 'wlan0' link is up

latest firmware with this patch, no problem

**Comment by Ansuel** [comment]
these are all upstream patch... if the devs wants they can be applied to 18.06 too...

**Comment by jow-** [comment]
I am looking into it. There are various issues in the PR which prevent it from getting merged as-is.

**Comment by jow-** [comment]
Reworked commit at https://git.openwrt.org/?p=openwrt/staging/jow.git;a=commitdiff;h=c75bb741e18009bc5c0e82b9ef13a95b9ff18f88 - would appreciate a hardware test run.

**Comment by Ansuel** [comment]
thx a lot for the rework... sorry for all that mess. Anyway asked to test on the forum topic. Let's wait...

**Pull request closed without merging**
