### PR TITLE
kernel: add fq_pie

### PR DESCRIPTION
**Pull request by rhjdvsgsgks**
Signed-off-by: rhjdvsgsgks <26178113+rhjdvsgsgks@users.noreply.github.com>

### CODE REVIEW

**Comment by pepe2k** [comment]
@rhjdvsgsgks your PR has a formal issues: missing proper commit description and a real e-mail address inside SoB line. Please, read the guide and fix your submission: https://openwrt.org/submitting-patches

**Comment by neheb** [comment]
this is interesting to me.

So compared to fq_codel (the default), this has less RAM usage. Wonder if it makes sense to replace fq_codel...

**Comment by Ansuel** [comment]
@neheb interesting what about load?

**Comment by Ansuel** [comment]
@rhjdvsgsgks closing this as someone helped you with the privacy problem. Would be good to leave a comment in the other pr :D

**Pull request closed without merging**
