### PR TITLE
ipq40xx: add kernel 6.6 as a testing kernel version

### PR DESCRIPTION
**Pull request by Ansuel**
Add and enable kernel 6.6 as a testing kernel version.

### CODE REVIEW

**Comment by mrkiko** [comment]
VDSL drivers (as used in FRITZ!BOX 7530) are failing build due to an enum conversion.

**Comment by mrkiko** [comment]
Reporting here the error more specifically:

  CC [M]  /mnt/wbook/NEWS/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dsl_cpe_mei-ugw_8.5.2.10/src/drv_mei_cpe_api_atm_ptm_intern.o
/mnt/wbook/NEWS/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dsl_cpe_mei-ugw_8.5.2.10/src/drv_mei_cpe_api_atm_ptm_intern.c: In function 'MEI_TcRequest':
/mnt/wbook/NEWS/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dsl_cpe_mei-ugw_8.5.2.10/src/drv_mei_cpe_api_atm_ptm_intern.c:226:34: error: implicit conversion from 'mei_tc_request_type' to 'MEI_TC_RequestType_t' [-Werror=enum-conversion]
  226 |       argsTcRequest.request_type = request_type;
      |                                  ^
/mnt/wbook/NEWS/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dsl_cpe_mei-ugw_8.5.2.10/src/drv_mei_cpe_api_atm_ptm_intern.c: In function 'MEI_InternalLineTCModeSwitch':
/mnt/wbook/NEWS/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dsl_cpe_mei-ugw_8.5.2.10/src/drv_mei_cpe_api_atm_ptm_intern.c:401:34: error: implicit conversion from 'enum <anonymous>' to 'MEI_TC_RequestType_t' [-Werror=enum-conversion]
  401 |       argsTcRequest.request_type = bPowerUp ? MEI_TC_REQUEST_PTM : MEI_TC_REQUEST_OFF;
      |                                  ^
cc1: all warnings being treated as errors

**Comment by mrkiko** [comment]
Unfortunately I don't know hot to handle the implicit enumconversions in here also due to the macro usage.
Any helps ideas, suggestions welcome.

**Comment by Ansuel** [comment]
@mrkiko eh i didn't compile test that driver... will fix.

**Comment by Ansuel** [comment]
@mrkiko I should have fixed the warning.

**Comment by namiltd** [comment]
Some files (e.g. 110-mtd-limit-OTP-nvmem-to-non-nand-devices.patch) require updating to kernel 6.6.23.
Please refresh patches.

**Pull request merged**
