### PR TITLE
kernel: kmod-fs-virtiofs: add Virtiofs filesystem support.

### PR DESCRIPTION
**Pull request by daiaji**
Add the Virtiofs filesystem.

Signed-off-by: daiaji MC <hentaiwushuang@gmail.com>

### CODE REVIEW

**Comment by mans0n** [comment]
Hi, please stick to the original PR next time. (This supersedes #9441)
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes#do_not_multi-post_or_re-post_prs

And this has some formal issues, especially:
* Please elaborate the commit message.
* Please add a Signed-off-by tag with your real name.

https://openwrt.org/docs/guide-developer/frequent-pr-mistakes

**Comment by daiaji** [comment]
Maybe depends on virtio, but I don't know if this kmod exists.

**Comment by noorall** [comment]
> 

Yes, I am compiling it for arm64 device.

**Comment by daiaji** [comment]
You may need to add your `virtio` kernel module using `make kernel_menuconfig`.

**Comment by helmiau** [comment]
i also have same issue with @noorall , i tried to build on various devices (you can see here https://github.com/helmiau/HelmiWrt-OS/actions ) with 5.4 kernel

and it says same error
```
Package kmod-fs-virtiofs is missing dependencies for the following libraries:
virtio.ko
virtio_ring.ko
```

**Comment by daiaji** [comment]
@helmiau Use `make kernel_menuconfig` to add virtio support to the kernel, and please do not compile this kmod for devices other than the virtual machine guest, because `virtiofs` only works in the virtual machine guest.

**Comment by mans0n** [comment]
> Use `make kernel_menuconfig` to add virtio support to the kernel, and please do not compile this kmod for devices other than the virtual machine guest, because `virtiofs` only works in the virtual machine guest.

I think you should also handle it somehow to get this merged, as the kmod package will be built for all targets by the buildbot.

And you still did not fix the formal issues I've mentioned. https://github.com/openwrt/openwrt/pull/9447#issuecomment-1065794114
While at it, please squash your changes into a single commit.

**Comment by daiaji** [comment]
@mans0n I've actually given up, as you can see it's not just adding a kmod to the problem, I'm going to close this pr.

**Pull request closed without merging**
