### PR TITLE
ar71xx: add support for COMFAST CF-E355AC v2

### PR DESCRIPTION
**Pull request by fall513**
COMFAST CF-E355AC v2 is a ceiling mount AP with PoE support, based on
    Qualcomm/Atheros QCA9531 + QCA9886.

    Short specification:

    - 2x 10/100 Mbps Ethernet, with PoE support
    - 128MB of RAM (DDR2)
    - 16 MB of FLASH
    - 2T2R 2.4 GHz, 802.11b/g/n
    - 2T2R 5 GHz, 802.11ac/n/a, WAVE 2
    - built-in 4x 3 dBi antennas
    - output power (max): 500 mW (27 dBm)
    - 1x RGB LED, 1x button
    - built-in watchdog chipset

    Flash instruction:

    Original firmware is based on OpenWrt.
    Use sysupgrade image directly in vendor GUI.

Signed-off-by: Ding Tengfei <dtf@comfast.cn>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://lede-project.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @fall513,

Thank you for your pull request. Based on a quick review, I see that the only difference between v1 and v2 is the AC radio and ath10k firmware included, am I right?

Cheers,
Piotr

**Comment by fall513** [comment]
Hi @pepe2k ，

You are right. Mainly changes are length of caldata and pre-caldata file.

Cheers,
Ding Tengfei

**Comment by pepe2k** [comment]
Hi @fall513,

> You are right. Mainly changes are length of caldata and pre-caldata file.

OK, could you then drop changes from (we don't need separate kernel config for the same board with just different AC radio installed):

target/linux/ar71xx/config-4.4
target/linux/ar71xx/config-4.9
target/linux/ar71xx/files/arch/mips/ath79/Kconfig.openwrt
target/linux/ar71xx/files/arch/mips/ath79/Makefile
target/linux/ar71xx/generic/config-default

And also include separate patch (in front of your change) which renames `CF-E355AC` to `CF-E355AC v1`?

Thanks!
Piotr

**Comment by fall513** [comment]
Hi @pepe2k ,

> OK, could you then drop changes from (we don't need separate kernel config for the same board with just different AC radio installed):
> target/linux/ar71xx/config-4.4
target/linux/ar71xx/config-4.9
target/linux/ar71xx/files/arch/mips/ath79/Kconfig.openwrt
target/linux/ar71xx/files/arch/mips/ath79/Makefile
target/linux/ar71xx/generic/config-default

I don't think it's a good idea, CF-E355AC and CF-E355AC-v2 are designed with different 5G chips, in other word, they are not same board, just similar. QCA9886 is a new chip of QCOM, and many developers do not know how to initialize it, that is why I update this patch.

> And also include separate patch (in front of your change) which renames CF-E355AC to CF-E355AC v1?

OK, I will update other separate patch to rename CF-E355AC to CF-E355AC v1.

Best Regards,
Ding Tengfei

**Comment by pepe2k** [comment]
@fall513

> I don't think it's a good idea, CF-E355AC and CF-E355AC-v2 are designed with different 5G chips, in other word, they are not same board, just similar. QCA9886 is a new chip of QCOM, and many developers do not know how to initialize it, that is why I update this patch.

Similar enough that you didn't make any change in mach-*.c file for this board and that's the reason why separate kernel config is redundant here.

Cheers,
Piotr

**Comment by fall513** [comment]
Hi @pepe2k ,

> Similar enough that you didn't make any change in mach-*.c file for this board and that's the reason why separate kernel config is redundant here.

OK, after remove those files, how to build CF-E355AC-v2? I think it should be remained ath79/Kconfig.openwrt and ath79/Makefile at least.

Best Regards,
Ding Tengfei

**Comment by pepe2k** [comment]
@fall513,

> OK, after remove those files, how to build CF-E355AC-v2? I think it should be remained ath79/Kconfig.openwrt and ath79/Makefile at least.

Exactly the same way you built it before. `CONFIG_ATH79_MACH_CF_E355AC` is already selected in generic subtarget kernel configuration and that's enough, `mach-cf-e316n-v2.c` will be compiled and included in kernel. Have a look for example at `ATH79_MACH_ARCHER_C7_V2` and `ATH79_MACH_TL_WDR4900_V2`.

Cheers,
Piotr

**Comment by fall513** [comment]
Hi @pepe2k ，

> Exactly the same way you built it before. CONFIG_ATH79_MACH_CF_E355AC is already selected in generic subtarget kernel configuration and that's enough, mach-cf-e316n-v2.c will be compiled and included in kernel. Have a look for example at ATH79_MACH_ARCHER_C7_V2 and ATH79_MACH_TL_WDR4900_V2.

You are right, those files are not necessary.

Best Regards,
Ding Tengfei

**Comment by pepe2k** [comment]
@fall513, please squash your commits.

Cheers,
Piotr

**Comment by pepe2k** [comment]
@fall513,

Thank you for your contribution! I have merged your changes into [my staging tree](https://git.openwrt.org/openwrt/staging/pepe2k.git).

Cheers,
Piotr

**Pull request closed without merging**
