### PR TITLE
kernel: bump 5.4 to 5.4.51

### PR DESCRIPTION
**Pull request by graysky2**
update via update_kernel.sh -v -u 5.4

Removed upstreamed patches:
 350-MIPS-Add-missing-EHB-in-mtc0-mfc0-sequence-for-DSPen.patch

Script refreshed patches:
 902-debloat_proc.patch
 904-debloat_dma_buf.patch

Attempted merge conflict in following patches:
 0024-MIPS-lantiq-revert-DSA-switch-driver-PMU-clock-chang.patch

Build system: x86_64
Build tested: ipq806x (Netgear R7800)

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by graysky2** [comment]
I would like someone more knowledgeable to review my merge conflict resolution to `target/linux/lantiq/patches-5.4/0024-MIPS-lantiq-revert-DSA-switch-driver-PMU-clock-chang.patch`

**Comment by guidosarducci** [comment]
> I would like someone more knowledgeable to review my merge conflict resolution to `target/linux/lantiq/patches-5.4/0024-MIPS-lantiq-revert-DSA-switch-driver-PMU-clock-chang.patch`

Then best to ping the patch author for review: @mkresin

**Comment by mans0n** [comment]
Your `From:` field is slightly different from `Signed-off-by:` field, is it intentional? It seems the maintainers had adjusted it manually. 3e992ea790f4

**Comment by graysky2** [comment]
@mans0n - That was unintentional.  Fixed now.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
