### PR TITLE
mediatek: add support for MT7988 SoC to filogic subtarget

### PR DESCRIPTION
**Pull request by dangowrt**
Add clock, cpufreq, dsa, ethernet and pinctrl drivers for the upcoming MT7988 [Filogic 880](https://www.mediatek.com/products/broadband-wifi/mediatek-filogic-880) SoC as well as provisional device tree and image for the reference board.

Features working on the reference board:
- [x] PMIC and CPU frequency scaling
- [x] 3x PCIe
- [x] USB 3.2
- [x] built-in DSA switch incl. 4x 1G Ethernet built-in PHY
- [x] built-in 2.5G Ethernet PHY (needs firmware, not yet officially published but available on https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/+/refs/heads/master/target/linux/mediatek/mt7988/base-files/lib/firmware/)
- [x] external 10GE Aquantia AQR113C PHY via USXGMII
- [ ] external Maxlinear GPY211C PHY (untested, my board doesn't have them connected)
- [ ] SFP+ cages (not connected on my board)
- [ ] wireless offloading (driver support and firmware missing)

### CODE REVIEW

**Comment by dangowrt** [comment]
merged.

**Comment by aiamadeus** [comment]
https://github.com/openwrt/openwrt/blob/e3a681bab4b2c193704e76b8a6091e57f0fab14e/target/linux/mediatek/filogic/target.mk#L4
The MT7988 SoC is cortex-a73, maybe we need to make a distinction here?

**Comment by dangowrt** [comment]
> The MT7988 SoC is cortex-a73, maybe we need to make a distinction here?

While it's true that MT7988 could benefit from code optimized for Cortex-A73 (main difference is in-order vs. out-of-order execution), I don't see this as a necessity. Code built for the A53 will run just fine on the A72.

**Comment by soxrok2212** [comment]
Is there a reason _not_ to? Might as well take advantage of what we can.

**Comment by DragonBluep** [comment]
I found that the [mtk official feed](https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/+/refs/heads/master/target/linux/mediatek/mt7988/target.mk#4) also defines it as a53.
```
ARCH:=aarch64
SUBTARGET:=mt7988
BOARDNAME:=MT7988
CPU_TYPE:=cortex-a53
FEATURES:=squashfs nand ramdisk
```

**Pull request closed without merging**
