### PR TITLE
ar71xx: initial board support for tl-hs110

### PR DESCRIPTION
**Pull request by aep**
this adds initial  board support for tl-hs110

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @aep,

Please, read our [submitting patches rules](https://lede-project.org/submitting-patches), and make sure your pull request follows them.

Cheers,
Piotr

**Comment by aep** [comment]
@pepe2k no idea what's wrong now. feel free to close.

**Comment by mkresin** [comment]
@aep Okay, I'm doing the reading for you:

> If you add support for new hardware: Include in your commit message a short description of the hardware and how to install LEDE on it. Have a look at the [recent additions](https://git.openwrt.org/?p=openwrt%2Fopenwrt.git&a=search&h=HEAD&st=commit&s=add+support+for) for some examples.

Am I right that "initial board support" suggests that not everything is work? What doesn't work? 

Drop the printks from the mach file as well. No debug code please.

**Comment by pepe2k** [comment]
> @pepe2k no idea what's wrong now. feel free to close.

`ATH79_MACH_TL_HS110` isn't enabled in kernel configuration...
Have you tested your code?

Cheers,
Piotr

**Comment by aep** [comment]
@mkresin thanks. i can do that if this is even acceptable otherwise. It's not possible to install lede on it without some pretty big changes we make, so i'm looking for feedback if i should continue anyway.

@pepe2k that is correct. should i submit the kernel config change too?

**Comment by pepe2k** [comment]
> @mkresin thanks. i can do that if this is even acceptable otherwise. **It's not possible to install lede on it without some pretty big changes we make**, so i'm looking for feedback if i should continue anyway.

Explain it, please.

> @pepe2k that is correct. should i submit the kernel config change too?

If you are not going to make this board ever working, I don't see any reason to include partial/broken support for it.

**Comment by aep** [comment]
@pepe2k this is not a user maintainable system. you need to open it and solder on  ethernet.  i'm upstreaming this because there's no user.mk or anything where we could add a board downstream without git breaking all the time.

i did the changes you requested

**Comment by pepe2k** [comment]
> @pepe2k this is not a user maintainable system. you need to open it and solder on ethernet.

Please, don't underestimate our/our community knowledge and hardware hacking possibilities :). I'm pretty sure there is no need to solder Ethernet - you should be able to install firmware using UART in U-Boot. Also, have you found and read this before https://www.softscheck.com/en/reverse-engineering-tp-link-hs110/?

> i did the changes you requested

Your commit message still doesn't include basic information about the hardware. Please have a look at some of the [recent additions](https://git.openwrt.org/?p=openwrt%2Fopenwrt.git&a=search&h=HEAD&st=commit&s=add+support+for) for better examples.

In most places where you did your changes, you broke alphabetical order. Also, `SOC_AS934X` isn't valid (if you copy something, make sure that it's not already broken). If this device doesn't have Ethernet and/or USB port/s, you shouldn't add support for that in mach-* code.

I saw that you made w page for this device in [OpenWrt Wiki](https://wiki.openwrt.org/toh/tp-link/tl-hs110), could you share more pictures of the PCBs?

> i'm upstreaming this because there's no user.mk or anything where we could add a board downstream without git breaking all the time.

This device has only 4 MB of flash and some additional mtd partitions (you probably shouldn't overwrite their content, users might want to revert to vendor firmware) which make available flash size even smaller than on a regular 4 MB TP-Link device... I'm worried that it just doesn't make sense to include official support for this device as it will never get image built. Have you tried `tiny` subtarget instead of `generic` one? How much space is left on device after installation?

Cheers,
Piotr

**Comment by pepe2k** [comment]
Ah, I forgot and didn't spot one thing... please, rebase your support on master branch. We don't accept PR/patches with devices support for release branch.

**Comment by aep** [comment]
>Please, don't underestimate our/our community knowledge and hardware hacking possibilities 

sure, do you want me to put the electrical layout into the commit message? I'm still unclear what you need me to put there. the examples you point at are user maintainable devices with factory images and stuff. There's no UI on this thing.

>Also, have you found and read this before https://www.softscheck.com/en/reverse-engineering-tp-link-hs110/?

yes

>  you should be able to install firmware using UART in U-Boot.

no. uboot is stripped of everything except tftp and cp. you must use ethernet or desolder the flash chip.


> In most places where you did your changes, you broke alphabetical order.

yes, bottom is easier for downstream patching. I'll fix it when we agree on a way forward.


> If this device doesn't have Ethernet and/or USB port/s, you shouldn't add support for that in mach-* code

We're using them. I don't see how it hurts anyone to leave them there. If we have to downstream patch that file, there's no point up-streaming it.

> I saw that you made w page for this device in OpenWrt Wiki, could you share more pictures of the PCBs?

of course!

> And some additional mtd partitions (you probably shouldn't overwrite their content, users might want to revert to vendor firmware)

The stock firmware should be able to deal with config and log being 0xff. It doesn't put a filesystem there anyway, but directly accesses it via the cpu mapping. ART is at the end and obviously needs to be not overwritten.

> I'm worried that it just doesn't make sense to include official support for this device as it will never get image built. 

Well I would agree, if every board in openwrt must be usable the same way (they're not). I'm not keen on upstreaming if there's resistance. It's just easier for us to maintain.

> How much space is left on device after installation?

the generic image boots fine on this branch, not on master

> please, rebase your support on master branch.

yeah, see above, not sure what to do there.

**Comment by aep** [comment]
/dev/mtdblock4          576.0K    204.0K    372.0K  35% /overlay

**Comment by pepe2k** [comment]
> sure, do you want me to put the electrical layout into the commit message? I'm still unclear what you need me to put there. the examples you point at are user maintainable devices with factory images and stuff. There's no UI on this thing.

Have a look at eb9e3651dd1a081e0d908e7e5162d6683098c1f3 and try to make your description similar.

> no. uboot is stripped of everything except tftp and cp. you must use ethernet or desolder the flash chip.

Really just cp and tftp?
Can you please show list of available U-Boot commands?

> We're using them. I don't see how it hurts anyone to leave them there. If we have to downstream patch that file, there's no point up-streaming it.

It's a dead code.

> The stock firmware should be able to deal with config and log being 0xff. It doesn't put a filesystem there anyway, but directly accesses it via the cpu mapping. ART is at the end and obviously needs to be not overwritten.

Have you actually confirmed that erasing all that additional data (excluding ART) isn't harmful for vendor firmware?

> yeah, see above, not sure what to do there.

Have a look: 0cd5e85e7ad621223b0787e66d8ad20fb2694135

Cheers,
Piotr

**Comment by aep** [comment]
> Have a look at eb9e365 and try to make your description similar.

i can copy that if you insist, but it will be useless without ethernet.


>  Can you please show list of available U-Boot commands?

```
ar7240> help
reset   - Perform RESET of the CPU
?       - alias for 'help'
boot    - boot default, i.e., run 'bootcmd'
bootd   - boot default, i.e., run 'bootcmd'
bootm   - boot application image from memory
cp      - memory copy
erase   - erase FLASH memory
help    - print online help
md      - memory display
mm      - memory modify (auto-incrementing)
mtest   - simple RAM test
mw      - memory write (fill)
nm      - memory modify (constant address)
ping    - send ICMP ECHO_REQUEST to network host
printenv- print environment variables
progmac - Set ethernet MAC addresses
run     - run commands in an environment variable
setenv  - set environment variables
tftpboot- boot image via network using TFTP protocol
version - print monitor version

```

> It's a dead code.

well not for us. anyway, it might still be easier to maintain that downstream, maybe.

> Have you actually confirmed that erasing all that additional data (excluding ART) isn't harmful for vendor firmware?

no, that would be pointless. you cannot flash back the firmware without a backup anyway

**Comment by pepe2k** [comment]
> i can copy that if you insist, but it will be useless without ethernet.

What does Ethernet have in common with a proper hardware description in commit message? We have great people working on [Wiki Table of Hardware](https://lede-project.org/toh/start) and that's why we always ask contributors to write something *useful* about the hardware.

```
ar7240> help
reset   - Perform RESET of the CPU
?       - alias for 'help'
boot    - boot default, i.e., run 'bootcmd'
bootd   - boot default, i.e., run 'bootcmd'
bootm   - boot application image from memory
cp      - memory copy
erase   - erase FLASH memory
help    - print online help
md      - memory display
mm      - memory modify (auto-incrementing)
mtest   - simple RAM test
mw      - memory write (fill)
nm      - memory modify (constant address)
ping    - send ICMP ECHO_REQUEST to network host
printenv- print environment variables
progmac - Set ethernet MAC addresses
run     - run commands in an environment variable
setenv  - set environment variables
tftpboot- boot image via network using TFTP protocol
version - print monitor version
```
So, it's not just "cp and tftp" as you wrote before.. You can use something like https://github.com/HorstBaerbel/ubootwrite. Will be slow but still easier (and faster) than soldering Ethernet.

> well not for us. anyway, it might still be easier to maintain that downstream, maybe.

I don't understand what kind of issues you might have with your own fork but it looks like you are doing something wrong there.

> no, that would be pointless. you cannot flash back the firmware without a backup anyway

UART access is required for flashing anyway so you can do also a flash backup that way.

PS. Found more pictures here: https://www.curesec.com/blog/article/blog/The-HS-110-Smart-Plug-aka-Projekt-Kasa-165.html

Cheers,
Piotr

**Comment by aep** [comment]
i tried my best to copy the descriptions format, since that seems to very important. I also changed to alphabetic order where sensible

> I don't understand what kind of issues you might have with your own fork but it looks like you are doing something wrong there.

it's a change affecting lots of files that change alot. if there was a user.mk for each that never changed, it would be much easier.

> You can use something like https://github.com/HorstBaerbel/ubootwrite

sure. we don't. Is this a requirement for getting this in? This is not useful for our case, since we do mass production.

**Comment by bobafetthotmail** [comment]
> sure. we don't. Is this a requirement for getting this in? This is not useful for our case, since we do mass production.

Well, you only need to make sure it works like that and write instructions.

Imho, for mass production is much faster to just desolder the SPI chip with a hot air smd rework station or use a SOIC clip for in-circuit programming and do all the job with a hardware flasher instead of soldering serial and ethernet. Also you have to do that anyway if you plan to increase the flash chip as you hinted.

**Comment by pepe2k** [comment]
@aep, could you please tell me what version of this device you have/are adding support for? In case of TP-Link it's important and kind of a mess with bazillion hardware versions.

I got confirmation that v1 and v2 (for EU market) are based on AR9331 but also found that v2 for US market is based on an embedded solution: QCA4010. Have a look: https://fccid.io/TE7HS110V2/Internal-Photos/Internal-Photos-3617078. And, there is also a v3 coming to EU market but for now nobody was able to tell ma what it will be based on.

Also:

* there is no TL-HS110. The model name is just **HS110**, according to the vendor website
* at least for v1, firmware is available on the vendor website, have you checked it?

Cheers,
Piotr

**Comment by pepe2k** [comment]
@aep please reopen this PR when you have the time to address the requested changes/questions.

Cheers,
Piotr

**Pull request closed without merging**
