### PR TITLE
Parse optreqs as a list of options as will be provided by Luci

### LINKED ISSUE #14056: DHCPv6 Client includes MAP-T and MAP-E OROs even though the map package isn't installed
### Describe the bug

The odhcpv6 client sends a DHCPv6 Solicit asking for MAP-T/E (and lw4over6 etc.) even though the packages required to support them (map) are not installed.  This can trigger some ISPs to **only** provide IPv4aaS instead of native DHCPv4, leaving users without IPv4 connectivity until they install the required map package.

### OpenWrt version

r23630-842932a63d

### OpenWrt release

23.05.2

### OpenWrt target/subtarget

x86/64

### Device

innotek GmbH VirtualBox

### Image kind

Official downloaded image

### Steps to reproduce

Fresh install, no non-default configuration required

### Actual behaviour

DHCPv6 Solicit contain the MAP-T, MAP-E and other Softwire options as defined by [RFC 7598](https://datatracker.ietf.org/doc/html/rfc7598), within the DHCPv6 Option Request Option.

### Expected behaviour

The DHCPv6 Solicit should only request options within the Option Request Option, for features and functionality the client and system can support.
i.e., if the map package isn't installed, it shouldn't ask for MAP-T/E options

### Additional info

An alternative fix, and one I would prefer, is for the default OpenWRT image to include the map and other IPv4aaS packages, so it can support these protocols out-of-the-box.  

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by detobate**
Partial fix to close: #14056 and to facilitate Luci#6739

### CODE REVIEW

**Comment by systemcrash** [comment]
Approved.

@dedeckeh can you review/merge please?

**Comment by jow-** [comment]
This will break backwards compatibility with existing configurations.

**Comment by systemcrash** [comment]
> This will break backwards compatibility with existing configurations.

The string to array change? Would a migrate script suffice?

**Comment by jow-** [comment]
Yes, the type change. Migrate scripts are only a partial solutions as they won't catch cases where backups are restored or provisioning scripts run after system boot.

**Comment by systemcrash** [comment]
Can luci help here? Every page load could transform them. Not ideal but
pretty good.

How does one ideally handle this scenario?

**Comment by jow-** [comment]
Not every user uses LuCI. The ui would need to emit strings instead of lists.-

**Comment by detobate** [comment]
> Not every user uses LuCI. The ui would need to emit strings instead of lists.-

to be honest I did go down that path first to avoid this PR, but struggled to make Luci do so nicely before deciding that a list was nicer anyway.
I could go back to Luci and continue trying to output a string, or could try parsing the var as a space-separated string initially before falling back to a list?

**Comment by detobate** [comment]
New PR odhcp6c#81

**Comment by systemcrash** [comment]
@jow- 
My understanding of the `list(.*)` syntax, is that it should be used to produce `list x value` in the uci config. 

And that `proto_config_add_string` usage is the exception to the rule. Should it in fact be `proto_config_add_array` and that if it isn't it's "incorrect"?

**Comment by jow-** [comment]
No, the list validator just means that the type may appear multiple times, separated by space. It does not tell whether the underlying uci value should be a list or a string.

**Comment by systemcrash** [comment]
OK thanks. So to handle a list like this, one might override the save function to output `x '1 2 3 ...'` instead of `list x value` multiple times?

**Comment by jow-** [comment]
Yes, that's how it is done for other options.

**Comment by systemcrash** [comment]
One question there: do those `.write` functions become callbacks when the user presses "save config"? I didn't see that written expressly in the luci html docs.

**Comment by jow-** [comment]
Yes, https://github.com/openwrt/luci/blob/master/modules/luci-base/htdocs/luci-static/resources/form.js#L2025

**Pull request closed without merging**
