### PR TITLE
ramips: add support for Xiaomi Mi Router 3G NOR

### PR DESCRIPTION
**Pull request by ulp1an**
This commit adds support for Xiaomi Mi WiFi Router 3G NOR.

Short specification:
 - MT7621AT + MT7603EN + 7612EN
CPU: MT7621A 880 MHz
ROM: 16 MB NOR SPI Flash
RAM: 256MB DDR3-1200
USB 3.0 (5V / 1A)
2.4 Ghz WiFi 2x2 (up to 300 Mbps)
5 Ghz WiFi 2x2 (up to 866 Mbps)
WAN up to 1 Gbps
LANх2 up to 1 Gbps
Power supply 12V / 1.5A Plug: 5.5x2.1 mm

Installation:
Serial U-Boot TFTP recovery
 - Open the router and connect a 3.3 V UART adapter to the pins.
 - Default serial parameters: 115200 / 8N1
 - Power on the router by pressing the reset button and interrupt boot process.
 - When it asks for the boot mode on the serial console choose  4: Entr boot command line interface.
 - Enter the commands below.

`setenv uart_en 1`
`setenv bootdelay 2 (2 seconds is enough in standard 5 usually)`
`setenv boot_wait on`
`setenv ssh_en 1`
`setenv telnet_en 1`
`setenv model R3G_SPI`
`setenv ipaddr 192.168.1.1`
`setenv serverip 192.168.1.2`
`setenv SN 15757/30044444`
#use your own SN which is on the label#
`setenv CountryCode EU`
`saveenv`
`reset `

 - After resetting your router put sysupgrade.bin file on a pre-formatted FAT32 USB flash memory and rename it to root_uImage
 - Press and hold the Reset button and supply power to the router. As soon as the red LED starts blinking, you can release the reset button.

The person who prepared these patches is **ptpt52**, known for the his x-wrt firmware, not me. All credit goes to him.

### CODE REVIEW

**Comment by jneuhauser** [comment]
Is this a hardware modification for the nand based R3G or is this a variant similar to R3Gv2?

Have you tested the R3Gv2 image on this device?

**Comment by mebeldek** [comment]
> Is this a hardware modification for the nand based R3G or is this a variant similar to R3Gv2?
Yes very same hardware but with SPI NOR instead of NAND flash. The SPI NOR flash is W25Q128FV exactly.
> Have you tested the R3Gv2 image on this device?
No, I haven't tested before. Because this device has 256 MB RAM but 3G v2 has only 128 MB RAM. I don't think it will work.

**Comment by jneuhauser** [comment]
The mt7621 target has memory size auto detection implemented and hasn't set any fixed memory size in the device tree. So i don't see why the image from R3Gv2 shouldn't work.

**Comment by mebeldek** [comment]
I just tried that device's firmware and the device got bricked and went into bootloop. Here is the bootlog.
flashed file: openwrt-21.02.1-ramips-mt7621-xiaomi_mi-router-3g-v2-squashfs-sysupgrade.bin
```
`
===================================================================
                MT7621   stage1 code Mar 12 2015 14:43:30 (ASIC)
                CPU=500000000 HZ BUS=125000000 HZ
==================================================================
Change MPLL source from XTAL to CR...
do MEMPLL setting..
MEMPLL Config : 0x11100000
3PLL mode + External loopback
=== XTAL-40Mhz === DDR-1200Mhz ===
PLL4 FB_DL: 0xf, 1/0 = 634/390 3D000000
PLL3 FB_DL: 0x13, 1/0 = 671/353 4D000000
PLL2 FB_DL: 0x17, 1/0 = 664/360 5D000000
do DDR setting..[01F40000]
Apply DDR3 Setting...(use customer AC)
          0    8   16   24   32   40   48   56   64   72   80   88   96  104  11                                                                                                                                                             2  120
      --------------------------------------------------------------------------                                                                                                                                                             ------
0000:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0001:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0002:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0003:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0004:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0005:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0006:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0007:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0008:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0009:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
000A:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
000B:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
000C:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
000D:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    1
000E:|    0    0    0    0    0    0    0    0    0    1    1    1    1    1                                                                                                                                                                 1    1
000F:|    0    0    0    0    1    1    1    1    1    1    1    1    1    1                                                                                                                                                                 0    0
0010:|    1    1    1    1    1    1    1    1    1    0    0    0    0    0                                                                                                                                                                 0    0
0011:|    1    1    1    1    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0012:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0013:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0014:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0015:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0016:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0017:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0018:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
0019:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
001A:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
001B:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
001C:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
001D:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
001E:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
001F:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0                                                                                                                                                                 0    0
DRAMC_DQSCTL1[0e0]=13000000
DRAMC_DQSGCTL[124]=80000033
rank 0 coarse = 15
rank 0 fine = 72
B:|    0    0    0    0    0    0    0    0    0    0    1    1    1    0    0                                                                                                                                                                 0
opt_dle value:11
DRAMC_DDR2CTL[07c]=C287223D
DRAMC_PADCTL4[0e4]=000022B3
DRAMC_DQIDLY1[210]=0B0B0A09
DRAMC_DQIDLY2[214]=06090807
DRAMC_DQIDLY3[218]=08070705
DRAMC_DQIDLY4[21c]=07070907
DRAMC_R0DELDLY[018]=00001E1F
==================================================================
                RX      DQS perbit delay software calibration
==================================================================
1.0-15 bit dq delay value
==================================================================
bit|     0  1  2  3  4  5  6  7  8  9
--------------------------------------
0 |    9 7 7 9 6 7 7 6 3 5
10 |    5 7 7 7 5 6
--------------------------------------

==================================================================
2.dqs window
x=pass dqs delay value (min~max)center
y=0-7bit DQ of every group
input delay:DQS0 =31 DQS1 = 30
==================================================================
bit     DQS0     bit      DQS1
0  (1~61)31  8  (2~55)28
1  (1~56)28  9  (1~55)28
2  (0~55)27  10  (1~55)28
3  (1~57)29  11  (2~56)29
4  (1~60)30  12  (2~59)30
5  (1~60)30  13  (1~55)28
6  (1~58)29  14  (1~56)28
7  (1~61)31  15  (1~57)29
==================================================================
3.dq delay value last
==================================================================
bit|    0  1  2  3  4  5  6  7  8   9
--------------------------------------
0 |    9 10 11 11 7 8 9 6 5 7
10 |    7 8 7 9 7 7
==================================================================
==================================================================
     TX  perbyte calibration
==================================================================
DQS loop = 15, cmp_err_1 = ffff0000
dqs_perbyte_dly.last_dqsdly_pass[0]=15,  finish count=1
dqs_perbyte_dly.last_dqsdly_pass[1]=15,  finish count=2
DQ loop=15, cmp_err_1 = ffff00a0
dqs_perbyte_dly.last_dqdly_pass[1]=15,  finish count=1
DQ loop=14, cmp_err_1 = ffff0000
dqs_perbyte_dly.last_dqdly_pass[0]=14,  finish count=2
byte:0, (DQS,DQ)=(8,8)
byte:1, (DQS,DQ)=(8,8)
DRAMC_DQODLY1[200]=88888888
DRAMC_DQODLY2[204]=88888888
20,data:88
[EMI] DRAMC calibration passed

===================================================================
                MT7621   stage1 code done
                CPU=500000000 HZ BUS=125000000 HZ
===================================================================


U-Boot 1.1.3 (Oct  6 2017 - 20:26:30)

Board: MediaTek APSoC DRAM: 256 MB

Config XHCI 40M PLL
MediaTek SPI flash driver, SPI clock: 44MHz
spi device id: ef 40 18 0
find flash: W25Q128FV
============================================
MediaTek U-Boot Version: 5.0.1.0-6
--------------------------------------------
ASIC MT7621A DualCore (MAC to MT7530 Mode)
DRAM_CONF_FROM: Auto-Detection
DRAM_TYPE: DDR3
DRAM bus: 16 bit
Xtal Mode=5 OCP Ratio=1/4
Flash component: SPI Flash
Date:Oct  6 2017  Time:20:26:30
============================================
icache: sets:256, ways:4, linesz:32, total:32768
dcache: sets:256, ways:4, linesz:32, total:32768

 #### The CPU freq = 880 MHZ ####
 estimate memory size = 256 Mbytes

 Reset MT7530
set LAN/WAN WLLLL

Please choose the operation:
   1: Load system code to SDRAM via TFTP.
   2: Load system code then write to Flash via TFTP.
   3: Boot system code via Flash (default).
   4: Enter boot command line interface.
   5: Load system code then write to Flash via USB Storage.
   9: Load U-Boot code then write to Flash via TFTP.                          0


3: System Boot system code via Flash.
## Checking image at bc050000 ...
   Image Name:   MIPS OpenWrt Linux-5.4.154
   Image Type:   MIPS Linux Kernel Image (uncompressed)
   Data Size:    2367218 Bytes =  2.3 MB
   Load Address: 80001000
   Entry Point:  80001000
   Verifying Checksum ... OK
OK
No initrd
## Transferring control to Linux (at address 80001000) ...
## Giving linux memsize in MB, 256

Starting kernel ...



OpenWrt kernel loader for MIPS based SoC
Copyright (C) 2011 Gabor Juhos <juhosg@openwrt.org>
Decompressing kernel... done!
Starting kernel at 80001000...

[    0.000000] Linux version 5.4.154 (builder@buildhost) (gcc version 8.4.0 (Ope                                                                                                                                                             nWrt GCC 8.4.0 r16325-88151b8303)) #0 SMP Sun Oct 24 09:01:35 2021
[    0.000000] SoC Type: MediaTek MT7621 ver:1 eco:3
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 0001992f (MIPS 1004Kc)
[    0.000000] MIPS: machine is Xiaomi Mi Router 3G v2
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] VPE topology {2,2} total 4
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 byt                                                                                                                                                             es
[    0.000000] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000000fffffff]
[    0.000000]   HighMem  empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000000fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000000fffffff]
[    0.000000] percpu: Embedded 14 pages/cpu s26768 r8192 d22384 u57344
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 64960
[    0.000000] Kernel command line: console=ttyS0,115200n8 rootfstype=squashfs,j                                                                                                                                                             ffs2
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes, l                                                                                                                                                             inear)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes, lin                                                                                                                                                             ear)
[    0.000000] Writing ErrCtl register=00009803
[    0.000000] Readback ErrCtl register=00009803
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 250792K/262144K available (6089K kernel code, 210K rwdata                                                                                                                                                             , 748K rodata, 1260K init, 238K bss, 11352K reserved, 0K cma-reserved, 0K highme                                                                                                                                                             m)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jif                                                                                                                                                             fies.
[    0.000000] NR_IRQS: 256
[    0.000000] random: get_random_bytes called from 0x806e5a3c with crng_init=0
[    0.000000] CPU Clock: 880MHz
[    0.000000] clocksource: GIC: mask: 0xffffffffffffffff max_cycles: 0xcaf478ab                                                                                                                                                             b4, max_idle_ns: 440795247997 ns
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_i                                                                                                                                                             dle_ns: 4343773742 ns
[    0.000009] sched_clock: 32 bits at 440MHz, resolution 2ns, wraps every 48806                                                                                                                                                             45118ns
[    0.007819] Calibrating delay loop... 583.68 BogoMIPS (lpj=1167360)
[    0.042019] pid_max: default: 32768 minimum: 301
[    0.046799] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linea                                                                                                                                                             r)
[    0.054026] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes,                                                                                                                                                              linear)
[    0.064541] rcu: Hierarchical SRCU implementation.
[    0.070001] smp: Bringing up secondary CPUs ...
[    3.508883] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    3.508894] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 byt                                                                                                                                                             es
[    3.508906] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    3.509012] CPU1 revision is: 0001992f (MIPS 1004Kc)
[    0.102770] Synchronize counters for CPU 1: done.
[    3.576507] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    3.576518] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 byt                                                                                                                                                             es
[    3.576526] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    3.576584] CPU2 revision is: 0001992f (MIPS 1004Kc)
[    0.167514] Synchronize counters for CPU 2: done.
[    3.631611] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    3.631621] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 byt                                                                                                                                                             es
[    3.631630] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    3.631694] CPU3 revision is: 0001992f (MIPS 1004Kc)
[    0.225380] Synchronize counters for CPU 3: done.
[    0.255264] smp: Brought up 1 node, 4 CPUs
[    0.263820] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, ma                                                                                                                                                             x_idle_ns: 7645041785100000 ns
[    0.273516] futex hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    0.280600] pinctrl core: initialized pinctrl subsystem
[    0.287499] NET: Registered protocol family 16
[    0.316851] workqueue: max_active 576 requested for napi_workq is out of rang                                                                                                                                                             e, clamping between 1 and 512
[    0.328318] clocksource: Switched to clocksource GIC
[    0.334773] thermal_sys: Registered thermal governor 'step_wise'
[    0.335293] NET: Registered protocol family 2
[    0.345745] IP idents hash table entries: 4096 (order: 3, 32768 bytes, linear                                                                                                                                                             )
[    0.353834] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144                                                                                                                                                              bytes, linear)
[    0.362172] TCP established hash table entries: 2048 (order: 1, 8192 bytes, l                                                                                                                                                             inear)
[    0.369767] TCP bind hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.376857] TCP: Hash tables configured (established 2048 bind 2048)
[    0.383285] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.389770] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.396992] NET: Registered protocol family 1
[    0.401309] PCI: CLS 0 bytes, default 32
[    0.496280] 4 CPUs re-calibrate udelay(lpj = 1163264)
[    0.503049] workingset: timestamp_bits=14 max_order=16 bucket_order=2
[    0.515992] random: fast init done
[    0.522644] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.528431] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORIT                                                                                                                                                             Y) (c) 2001-2006 Red Hat, Inc.
[    0.539741] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 2                                                                                                                                                             51)
[    0.549094] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.555088] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.560995] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.567438] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.577656] printk: console [ttyS0] disabled
[    0.581963] 1e000c00.uartlite: ttyS0 at MMIO 0x1e000c00 (irq = 19, base_baud                                                                                                                                                              = 3125000) is a 16550A
[    0.590952] printk: console [ttyS0] enabled
[    0.590952] printk: console [ttyS0] enabled
[    0.599212] printk: bootconsole [early0] disabled
[    0.599212] printk: bootconsole [early0] disabled
[    0.611584] spi-mt7621 1e000b00.spi: sys_freq: 220000000
[    0.628536] spi-nor spi0.0: w25q128 (16384 Kbytes)
[    0.633414] 8 fixed-partitions partitions found on MTD device spi0.0
[    0.639753] Creating 8 MTD partitions on "spi0.0":
[    0.644554] 0x000000000000-0x000000030000 : "u-boot"
[    0.650868] 0x000000030000-0x000000040000 : "u-boot-env"
[    0.657692] 0x000000040000-0x000000050000 : "Bdata"
[    0.663904] 0x000000050000-0x000000060000 : "factory"
[    0.670429] 0x000000060000-0x000000070000 : "crash"
[    0.676776] 0x000000070000-0x000000080000 : "cfg_bak"
[    0.683287] 0x000000080000-0x000000180000 : "overlay"
[    0.689683] 0x000000180000-0x000001000000 : "firmware"
[    0.706711] libphy: Fixed MDIO Bus: probed
[    0.738715] libphy: mdio: probed
[    0.742248] mt7530 mdio-bus:1f: MT7530 adapts as multi-chip module
[    0.750903] mtk_soc_eth 1e100000.ethernet: generated random MAC address 72:6d                                                                                                                                                             :3e:d6:20:bd
[    0.760035] mtk_soc_eth 1e100000.ethernet eth0: mediatek frame engine at 0xbe                                                                                                                                                             100000, irq 21
[    0.770597] mt7621-pci 1e140000.pcie: Parsing DT failed
[    0.778830] NET: Registered protocol family 10
[    0.784902] Segment Routing with IPv6
[    0.788696] NET: Registered protocol family 17
[    0.793225] bridge: filtering via arp/ip/ip6tables is no longer available by                                                                                                                                                              default. Update your scripts to load br_netfilter if you need this.
[    0.806405] 8021q: 802.1Q VLAN Support v1.8
[    0.812754] mt7530 mdio-bus:1f: MT7530 adapts as multi-chip module
[    0.830855] libphy: dsa slave smi: probed
[    0.835692] mt7530 mdio-bus:1f lan2 (uninitialized): PHY [dsa-0.0:02] driver                                                                                                                                                              [Generic PHY]
[    0.845566] mt7530 mdio-bus:1f lan1 (uninitialized): PHY [dsa-0.0:03] driver                                                                                                                                                              [Generic PHY]
[    0.855446] mt7530 mdio-bus:1f wan (uninitialized): PHY [dsa-0.0:04] driver [                                                                                                                                                             Generic PHY]
[    0.865261] mt7530 mdio-bus:1f: configuring for fixed/rgmii link mode
[    0.876503] DSA: tree 0 setup
[    0.879838] rt2880-pinmux pinctrl: pcie is already enabled
[    0.885484] mt7621-pci-phy 1e149000.pcie-phy: PHY for 0xbe149000 (dual port =                                                                                                                                                              1)
[    0.893088] mt7621-pci-phy 1e14a000.pcie-phy: PHY for 0xbe14a000 (dual port =                                                                                                                                                              0)
[    1.000196] mt7621-pci-phy 1e149000.pcie-phy: Xtal is 40MHz
[    1.005782] mt7621-pci-phy 1e14a000.pcie-phy: Xtal is 40MHz
[    1.111010] mt7621-pci 1e140000.pcie: pcie2 no card, disable it (RST & CLK)
[    1.117965] mt7621-pci 1e140000.pcie: PCIE0 enabled
[    1.122836] mt7621-pci 1e140000.pcie: PCIE1 enabled
[    1.127715] mt7621-pci 1e140000.pcie: PCI coherence region base: 0x60000000,                                                                                                                                                              mask/settings: 0xf0000002
[    1.137200] mt7621-pci 1e140000.pcie: PCI host bridge to bus 0000:00
[    1.143572] pci_bus 0000:00: root bus resource [io  0x1e160000-0x1e16ffff]
[    1.150441] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff]
[    1.157310] pci_bus 0000:00: root bus resource [bus 00-ff]
[    1.162831] pci 0000:00:00.0: [0e8d:0801] type 01 class 0x060400
[    1.168867] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    1.175130] pci 0000:00:00.0: reg 0x14: [mem 0x00000000-0x0000ffff]
[    1.181466] pci 0000:00:00.0: supports D1
[    1.185477] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    1.191637] pci 0000:00:01.0: [0e8d:0801] type 01 class 0x060400
[    1.197683] pci 0000:00:01.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    1.203946] pci 0000:00:01.0: reg 0x14: [mem 0x00000000-0x0000ffff]
[    1.210274] pci 0000:00:01.0: supports D1
[    1.214286] pci 0000:00:01.0: PME# supported from D0 D1 D3hot
[    1.221468] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), rec                                                                                                                                                             onfiguring
[    1.229475] pci 0000:00:01.0: bridge configuration invalid ([bus 00-00]), rec                                                                                                                                                             onfiguring
[    1.237692] pci 0000:01:00.0: [14c3:7603] type 00 class 0x028000
[    1.243751] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff]
[    1.250155] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    1.257691] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
[    1.262938] pci 0000:00:00.0:   bridge window [io  0x0000-0x0fff]
[    1.269028] pci 0000:00:00.0:   bridge window [mem 0x00000000-0x000fffff]
[    1.275806] pci 0000:00:00.0:   bridge window [mem 0x00000000-0x000fffff pref                                                                                                                                                             ]
[    1.283023] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    1.289871] pci 0000:02:00.0: [14c3:7662] type 00 class 0x028000
[    1.295938] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit]
[    1.302757] pci 0000:02:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    1.309557] pci 0000:02:00.0: PME# supported from D0 D3hot D3cold
[    1.317124] pci 0000:00:01.0: PCI bridge to [bus 02-ff]
[    1.322356] pci 0000:00:01.0:   bridge window [io  0x0000-0x0fff]
[    1.328446] pci 0000:00:01.0:   bridge window [mem 0x00000000-0x000fffff]
[    1.335229] pci 0000:00:01.0:   bridge window [mem 0x00000000-0x000fffff pref                                                                                                                                                             ]
[    1.342449] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02
[    1.349107] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    1.355710] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    1.362665] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000]
[    1.369271] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000]
[    1.376223] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff]
[    1.383006] pci 0000:00:00.0: BAR 9: assigned [mem 0x60100000-0x601fffff pref                                                                                                                                                             ]
[    1.390222] pci 0000:00:01.0: BAR 8: assigned [mem 0x60200000-0x602fffff]
[    1.397006] pci 0000:00:01.0: BAR 9: assigned [mem 0x60300000-0x603fffff pref                                                                                                                                                             ]
[    1.404218] pci 0000:00:00.0: BAR 1: assigned [mem 0x60400000-0x6040ffff]
[    1.411005] pci 0000:00:01.0: BAR 1: assigned [mem 0x60410000-0x6041ffff]
[    1.417792] pci 0000:00:00.0: BAR 7: assigned [io  0x1e160000-0x1e160fff]
[    1.424576] pci 0000:00:01.0: BAR 7: assigned [io  0x1e161000-0x1e161fff]
[    1.431362] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff]
[    1.438146] pci 0000:00:00.0: PCI bridge to [bus 01]
[    1.443110] pci 0000:00:00.0:   bridge window [io  0x1e160000-0x1e160fff]
[    1.449890] pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
[    1.456672] pci 0000:00:00.0:   bridge window [mem 0x60100000-0x601fffff pref                                                                                                                                                             ]
[    1.463890] pci 0000:02:00.0: BAR 0: assigned [mem 0x60200000-0x602fffff 64bi                                                                                                                                                             t]
[    1.471206] pci 0000:02:00.0: BAR 6: assigned [mem 0x60300000-0x6030ffff pref                                                                                                                                                             ]
[    1.478419] pci 0000:00:01.0: PCI bridge to [bus 02]
[    1.483381] pci 0000:00:01.0:   bridge window [io  0x1e161000-0x1e161fff]
[    1.490162] pci 0000:00:01.0:   bridge window [mem 0x60200000-0x602fffff]
[    1.496942] pci 0000:00:01.0:   bridge window [mem 0x60300000-0x603fffff pref                                                                                                                                                             ]
[    1.504737] mt7530 mdio-bus:1f: Link is Up - 1Gbps/Full - flow control off
[    1.512189] hctosys: unable to open rtc device (rtc0)
[    1.518113] /dev/root: Can't open blockdev
[    1.522228] VFS: Cannot open root device "(null)" or unknown-block(0,0): erro                                                                                                                                                             r -6
[    1.529687] Please append a correct "root=" boot option; here are the availab                                                                                                                                                             le partitions:
[    1.538026] 1f00             192 mtdblock0
[    1.538030]  (driver?)
[    1.544560] 1f01              64 mtdblock1
[    1.544563]  (driver?)
[    1.551080] 1f02              64 mtdblock2
[    1.551084]  (driver?)
[    1.557610] 1f03              64 mtdblock3
[    1.557613]  (driver?)
[    1.564130] 1f04              64 mtdblock4
[    1.564133]  (driver?)
[    1.570663] 1f05              64 mtdblock5
[    1.570666]  (driver?)
[    1.577193] 1f06            1024 mtdblock6
[    1.577196]  (driver?)
[    1.583714] 1f07           14848 mtdblock7
[    1.583717]  (driver?)
[    1.590244] Kernel panic - not syncing: VFS: Unable to mount root fs on unkno                                                                                                                                                             wn-block(0,0)
[    1.598510] Rebooting in 1 seconds..`
```

**Comment by mans0n** [comment]
Hi, first thanks for your effort to post a PR. I know first-time contribution is a hard work.

But I've got little dubious after reading the flow and tried searching if the 3G NOR variant does exist, and I found a forum post:
https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-mi-router-3g-nor/113825/4
So it's a user-modified device (and you did not mentioned it here), and you copied a patchset not your own without clarifying the authorship.
Well... Please don't surprise me in this way next time, okay?

Anyway, I agree that custom hardware support is hardly accepted. :(

**Comment by mebeldek** [comment]
Hello @mans0n
I appreciate your response.

As you might guess, I have no experience with this..  I'm sorry I don't want any drama but I did not try to hide anything. Why would I do that? I really don't know why you think that. I actually mentioned it clearly above (and my forum post) when he/she asked if it was a modded device. Please see above in case you missed it.

> -Is this a hardware modification for the nand based R3G or is this a variant similar to R3Gv2?
> +**Yes very same hardware but with SPI NOR instead of NAND flash. The SPI NOR flash is W25Q128FV exactly.**

And this is from forum post

> [Yes you're right, it is a NOR modified variant of the same device.](https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-mi-router-3g-nor/113825/4)

I did not know that I should be the original owner of the patch(es). I tried to do create a PR myself because I couldn't find any help on this. If there is something that is not in accordance with the PR procedure, I can accept it. But it's definitely not intentional. I'm telling this because I want you to know that it was NOT done on purpose.

Regards.

PS: I can't say that I like the language you use when talking to me.

**Comment by mans0n** [comment]
I apologize if my language offended you. I'll try to be more gentle.

First let me correct one thing. I didn't think you were hiding something on purpose. I still think this is a mistake that newcomer can make, especially they is not familiar yet with the common practice and implicit rule. I was just flustered from knowing that some important information a reviewer should be aware was missing in the PR description and I could find it in another forum post you made. It would be much easier for me to grasp if you provided the forum link...

> > -Is this a hardware modification for the nand based R3G or is this a variant similar to R3Gv2?
> > +**Yes very same hardware but with SPI NOR instead of NAND flash. The SPI NOR flash is W25Q128FV exactly.**

I took it that means 3G NOR device is another official variant from the vendor. Actually some GL.iNet vendor models have NOR and NAND versions and I thought this is also the case here. I think this misunderstanding came from our different experience.

> I did not know that I should be the original owner of the patch(es). I tried to do create a PR myself because I couldn't find any help on this.

You don't have to be the original author of the patch, but the authorship should be clarified somewhere. Usually the patch includes Signed-off-by tag from the origianl author and that is sufficient, but in this case the origianl author did not provide it so this is a little trickier... Another way is to ask the origianl author directly for permission to copy their patch. (Sorry for bothering but authorship is important here.)

I'm sorry your first PR here didn't go well. I hope to see your next contribution in the future (unless you're disappointed with my response).

Thanks!

**Comment by Neustradamus** [comment]
@8bx: Any news?

**Pull request closed without merging**
