### PR TITLE
kernel: add PCTV 461e DVB-S2 USB card support

### PR DESCRIPTION
**Pull request by psyborg55**
This changeset adds support for PCTV 461e DVB-S2 USB card by enabling related kernel modules and their dependencies.
The card has been tested on latest ath79 target source (Archer C7) with tvheadend as a streaming app. CPU load on router was in range 0.05-0.25 while streaming single h264 full HD channel.
Remote controller has not been tested.

Signed-off-by: Tomislav Požega <pozega.tomislav@gmail.com>

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
GitHub seems to not like me, so let's try this way:
You can omit kmod-i2c-core, as it should be pulled by the other packages. Same should apply to kmod-input-core where you have kmod-rc-core defined as dependency.

**Comment by psyborg55** [comment]
i've had it originally only in kmod-media package but after applying this to clean sources clone menuconfig complained about recursive dependencies error so i had to add it to kmod-dvb-pctv461e too. if you can be more specific i can try it again.

**Comment by adrianschmutzler** [comment]
I cannot annotate in the patches directly due to some browser/GitHub foo. I will try later with another machine ...

**Comment by SvenRoederer** [comment]
Just for reference: there is a closed PR https://github.com/openwrt/openwrt/pull/1451 also about DVB-support

**Comment by adrianschmutzler** [comment]
Since I still cannot comment inline, let's do it this way:

> define KernelPackage/media
> 	SUBMENU:=$(VIDEO_MENU)
> 	TITLE:=Multimedia video cards support
> 	DEPENDS:=+kmod-i2c-core +kmod-input-core +kmod-rc-core

Here, kmod-input-core should be selected by kmod-rc-core, so you can remove the further.

> define KernelPackage/dvb-pctv461e
> 	SUBMENU:=$(VIDEO_MENU)
> 	TITLE:=PCTV 461e DVB-S2 support
> 	DEPENDS:=+kmod-i2c-core +kmod-i2c-mux +kmod-media +kmod-rc-keymap-pinnacle-pctv-hd \
> 		 +kmod-regmap-i2c +kmod-usb2 +pctv461e-firmware

Here, kmod-i2c-core should be selected by kmod-i2c-mux, so you can remove the further.

**Comment by psyborg55** [comment]
removing kmod-input-core is fine, build tested - packages have the same size.
removing kmod-i2c-core makes kmod-dvb-pctv461e disappear from menuconfig and these messages printed in console upon exiting:

tmp/.config-package.in:10653:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:10653:	symbol PACKAGE_kmod-i2c-core is selected by PACKAGE_kmod-regmap-i2c
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:15002:	symbol PACKAGE_kmod-regmap-i2c is selected by PACKAGE_kmod-dvb-pctv461e
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:17673:	symbol PACKAGE_kmod-dvb-pctv461e depends on PACKAGE_kmod-i2c-core

**Comment by tmn505** [comment]
Small hint, when adding kernel modules (especially for media subsystem, which heavily relies on `select` in Kconfig) always test changes with `CONFIG_ALL_KMODS` enabled, which will help You spot the missing dependencies for kernel modules already packaged in OpenWrt. It's good practice to do compilation test for few architectures, especially x86, arm(brcm2708) and mips(ath79).

**Comment by psyborg55** [comment]
removed kmod-input-core and pushed

**Comment by adrianschmutzler** [comment]
Hi, as with #1451, it appears that none of the committers is interested in reviewing or merging this. Since there has been no response for quite some time, I'm going to close it now.

I'm sorry, but better crush your remaining hopes now than waiting another 6 months where supposedly nothing will be different.

**Pull request closed without merging**
