### PR TITLE
Enable wolfSSL library support for OpenVPN

### PR DESCRIPTION
**Pull request by AuthorReflex**
Support for wolfSSL has been upstreamed to the master OpenVPN branch in f6dca235ae560597a0763f0c98fcc9130b80ccf4 so we can use wolfSSL directly in OpenVPN. So no more needed differnt SSL engine for OpenVPN in systems based on wolfSSL lib
rary
Compiled && tested on ramips/mt7620, ramips/mt7621

### CODE REVIEW

**Comment by castiel652** [comment]
Two commits are the same?

**Comment by AuthorReflex** [comment]
> 
> 
> Two commits are the same?

Yes. First commit has incorrect comment structure, try to fixing it produces new commit.

**Comment by castiel652** [comment]
> > Two commits are the same?
> 
> Yes. First commit has incorrect comment structure, try to fixing it produces new commit.

How did you fix it?

You should just use `git commit --amend` to fix the commit message.

**Comment by AuthorReflex** [comment]
> 
> 
> > > Two commits are the same?
> > 
> > 
> > Yes. First commit has incorrect comment structure, try to fixing it produces new commit.
> 
> How did you fix it?
> 
> You should just use `git commit --amend` to fix the commit message.

I'm trying to squashing commit 
https://openwrt.org/docs/guide-developer/working-with-github-pr#squashing_commits

**Comment by AuthorReflex** [comment]
> 
> 
> > > > Two commits are the same?
> > > 
> > > 
> > > Yes. First commit has incorrect comment structure, try to fixing it produces new commit.
> > 
> > 
> > How did you fix it?
> > You should just use `git commit --amend` to fix the commit message.
> 
> I'm trying to squashing commit
> https://openwrt.org/docs/guide-developer/working-with-github-pr#squashing_commits

Commits are fixed.

**Comment by adschm** [comment]
Commit title needs to be prefixed by "wolfssl:" (this might allow to shorten the rest, ending up with something like "wolfssl: add support for OpenVPN".
Apart from that, please wrap your commit message to have max. 74 chars per line max.

**Comment by AuthorReflex** [comment]
> 
> 
> Commit title needs to be prefixed by "wolfssl:" (this might allow to shorten the rest, ending up with something like "wolfssl: add support for OpenVPN".
> Apart from that, please wrap your commit message to have max. 74 chars per line max.

Fixed

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master.

**Pull request closed without merging**
