### PR TITLE
ipq806x: support L2 cache and rpm clocks scaling

### PR DESCRIPTION
**Pull request by fantom-x**
This is an attempt to finish off PR#632 (https://github.com/openwrt/openwrt/pull/632)

I have made two changes:

1. Merged four commits into one
2. Cached L2 freq/volt: multiple cpu frequencies map to the same l2 freq/volt so it does not make sense to set them to the same value over and over

There was a comment in the original pull request (see below) and if it is still valid, I would appreciate some directions on how to address it. My understanding is that I would need to create a new file **cpufreq-dt-ipq806x** and compile it instead of the original one?

> I noticed that you're hacking a lot of ipq806x specific code into the generic cpufreq-dt driver. I think it would be a lot less messy if you just fork that driver and create an ipq806x specific one instead.

### CODE REVIEW

**Comment by fantom-x** [comment]
Messed up the first commit: l2-freq needs to be cached per cpu (both cores) while l2-volt needs to be cache per a core.

Also fixed the commit message

**Comment by fantom-x** [comment]
This and the original  patches are decreasing the router throughput by [~35%](https://forum.openwrt.org/t/netgear-r7800-exploration-ipq8065-qca9984/285/1693?u=fantom-x).

@dissent1 as the author of the original patch, do you have any insight into the possible causes?

**Comment by hingbong** [comment]
[https://github.com/hingbong/openwrt-r7800/tree/ipq806x-support-L2-cache-and-rpm-clocks-scaling](url)
port to linux-4.19 and running normally

**Comment by fantom-x** [comment]
@hingbong how about the throughput? It was running normally for me until I tested for performance.

**Comment by fantom-x** [comment]
I have a slightly modified version locally that caches all the remaining values that I was hoping would fix performance by eliminating contention, but it did not help. So I did not bother pushing it into this PR yet.

**Comment by hingbong** [comment]
sorry, I don't have the high bandwidth to test.

**Comment by fantom-x** [comment]
Neither did I, so I put the router between two computers and ran iperf3 on each. Another way to test is by using dslresport’s speed test with 32 streams and watch the CPU usage: my connection is 50M/10M and the cpu was at 100% during the test. Without his change, the CPU usage was around 60%.

**Comment by hingbong** [comment]
with 100M downlink, it takes 24% sirq

**Comment by fantom-x** [comment]
And what was it before the change?

**Comment by fantom-x** [comment]
Oh, and a way better test would be to use SQM with cake: both cores were at 100% with 50M download.

**Comment by hingbong** [comment]
I ended up working earlier today, so I was able to compile and test. I compile a build without this patch and have a test. On 100M downlink, it takes 10% sirq

**Comment by fantom-x** [comment]
That sounds about right :(

**Comment by fantom-x** [comment]
The implementation degrades the router's performance

**Comment by facboy** [comment]
What's the definitive test for this?  I tried this (tweaking the 600MHz -> 800MHz) with SQM/cake on my 80/20 connection (more like 68/20) and the cores were more like 20% utilization using the ondemand governor but with the up_threshold set to 60.  this was with 32 streams on DSL reports.

**Pull request closed without merging**
