### PR TITLE
layerscape: Update to LSDK-21.08 / kernel 5.10

### PR DESCRIPTION
**Pull request by sch-m**
@hauke @aparcar @yangbolu1991 @mcbridematt 

This patch set updates various layerscape components to the state of LSDK-21.08 and adds support for linux kernel v5.10.

As already discussed on the mailing list, the countless kernel patches from the LSDK were not included, but only a few patches were added so that all targets compile again.
It can thus be assumed that a few regressions are still included.

I currently have an LS1046ARDB and an FRWY-LS1046A available and at first glance everything seems to work basically here.

Any feedback is welcome.

### CODE REVIEW

**Comment by neheb** [comment]
Are those gcc11 patches still needed?

**Comment by sch-m** [comment]
> Are those gcc11 patches still needed?

Oh, thanks for the hint. The tfa-layerscape gcc11 patch is indeed not required any more.

I'll update this PR accordingly.

**Comment by neheb** [comment]
I mention it since the patch is probably not optimal. AFAIK, just adding volatile to the pointer is enough to fix compilation.

**Comment by hauke** [comment]
Looks good to me. I do not have any boards to test this, it would be nice if more people with boards could test this and report their results.

**Comment by CHKDSK88** [comment]
I have three layerscape Devices. Please give me couple days.

**Comment by sch-m** [comment]
I was advised on the u-boot mailing list that the LS1043ARDB board also requires a patch for PCI enumeration. I have now added this here as well.

**Comment by hauke** [comment]
Thank you for the patches, I pushed them to master.

**Pull request closed without merging**
