### PR TITLE
mtd-utils: update to 2.0.1

### PR DESCRIPTION
**Pull request by wongsyrone**
010-fix-rpmatch.patch is upstream, removed from our patchset
The file structure is changed, modify patch accordingly
use CONFIGURE_ARGS to disable tests, xattr and lzo

Compile and run tested on mvebu and x86_64

Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
I suggest renaming patch 130 to 100 and renaming patch 100 to 110 as it's a simple patch that can be upstreamed quite easily.

**Comment by wongsyrone** [comment]
There are only two patches now, it seems doesn't matter.

**Comment by neheb** [comment]
hrm make check seems to be giving me this:

WARNING: PKG_MIRROR_HASH does not match mtd-utils-2.0.1.tar.xz hash 1209ad14255e4c5e72a5886240f0a55e006b9105186d4efa45792f60896d5d88

**Comment by wongsyrone** [comment]
I'll check the hash issue in this evening(UTC+8).

**Comment by wongsyrone** [comment]
I deleted the tarball and re-download it, sha256sum gives me the same result. The hash should be fine.

**Comment by wongsyrone** [comment]
Forgot to mention the close reason is https://github.com/openwrt/openwrt/commit/56d0dd56e9c6efa79d03b6417dc0ae5449343001 is pushed before this patch, someone has to change lzma codes accordingly.

**Pull request closed without merging**
