### PR TITLE
openvpn: update to 2.5.0

### PR DESCRIPTION
**Pull request by swg0101**
New features:
* Per client tls-crypt keys
* ChaCha20-Poly1305 can be used to encrypt the data channel
* Routes are added/removed via Netlink instead of ifconfig/route
  (unless iproute2 support is enabled).
* VLAN support when using a TAP device

Significant changes:
* Server support can no longer be disabled.
* Crypto support can no longer be disabled, remove nossl variant.
* Blowfish (BF-CBC) is no longer implicitly the default cipher.
  OpenVPN peers prior to 2.4, or peers with data cipher negotiation
  disabled, will not be able to connect to a 2.5 peer unless
  option data_fallback_ciphers is set on the 2.5 peer and it contains a
  cipher supported by the client.

Signed-off-by: Magnus Kroken <mkroken at gmail.com>
---
Compile-tested openssl variant on mips_24kc, powerpc_8540 and
arm_cortex-a9. Runtime-tested openssl variant as server on arm_cortex-a9.

I have tested the earlier 2.5 beta and RC releases more extensively with
both openssl and mbedtls in various configurations.

I propose disabling LZO compression support by default, due to:
* Compression is not recommended, as it may weaken the security of the
  connection
* For users who need compression, we build with LZ4 support by default
* LZO in OpenVPN pulls in liblzo at approx. 32 kB. LZO support also
  adds about 1 kB to the OpenVPN package itself. LZ4 support (using
  OpenVPN bundled LZ4) adds about 6 kB to the OpenVPN package in total.

This means OpenWrt users will not be able to connect to OpenVPN
peers that require LZO compression, unless they build the package
themselves.

I left the PROVIDES line as "openvpn openvpn-crypto". As the nossl
variant will no longer exist and all OpenVPN packages will cover both
cases I am not entirely sure how this should be handled.

.../services/openvpn/Config-mbedtls.in        |  6 +-
 .../network/services/openvpn/Config-nossl.in  | 50 --------------
 .../services/openvpn/Config-openssl.in        |  6 +-
 package/network/services/openvpn/Makefile     | 20 +-----
 .../services/openvpn/files/openvpn.config     | 67 ++++++++++++-------
 .../services/openvpn/files/openvpn.options    | 14 +++-
 .../001-reproducible-remove_DATE.patch        |  6 +-
 ...bedtls-disable-runtime-version-check.patch |  2 +-
 ...l-dont-use-deprecated-ssleay-symbols.patch | 58 ----------------
 ...enssl-add-missing-include-statements.patch | 65 ------------------
 .../210-build_always_use_internal_lz4.patch   |  2 +-
 .../openvpn/patches/220-disable_des.patch     | 21 ++----
 12 files changed, 72 insertions(+), 245 deletions(-)
 delete mode 100644 package/network/services/openvpn/Config-nossl.in
 delete mode 100644 package/network/services/openvpn/patches/110-openssl-dont-use-deprecated-ssleay-symbols.patch
 delete mode 100644 package/network/services/openvpn/patches/111-openssl-add-missing-include-statements.patch

### CODE REVIEW

**Comment by BKPepe** [comment]
I want to mention that this was to the OpenWrt's mailing list one month ago:
http://lists.openwrt.org/pipermail/openwrt-devel/2020-October/031924.html

**Comment by swg0101** [comment]
Interesting, was there an issue with the patch such that it is not accepted yet?

**Review by borkra — APPROVED** [review]
It builds and works ok for me on mvebu.

**Comment by aparcar** [comment]
Also again, why isn't openvpn not moved to packages.git?

**Comment by swg0101** [comment]
@aparcar I was wondering about that myself... 📦
Anyways, I will replace this PR with @mkrkn 's patch since his covers a bit more depth. Probably need to rework some of the patches since some of those are already incorporated upstream...

**Comment by swg0101** [comment]
Tested @mkrkn 's patch on my r7800 and it builds fine, along with ChaPoly.

```~# openvpn --show-ciphers
AES-128-CBC  (128 bit key, 128 bit block)
AES-192-CBC  (192 bit key, 128 bit block)
AES-256-CBC  (256 bit key, 128 bit block)
AES-128-GCM  (128 bit key, 128 bit block, TLS client/server mode only)
AES-192-GCM  (192 bit key, 128 bit block, TLS client/server mode only)
AES-256-GCM  (256 bit key, 128 bit block, TLS client/server mode only)
CHACHA20-POLY1305  (256 bit key, stream cipher, TLS client/server mode only)

The following ciphers have a block size of less than 128 bits,
and are therefore deprecated.  Do not use unless you have to.

BF-CBC  (128 bit key by default, 64 bit block)
```

**Comment by adschm** [comment]
Please do not post the same stuff on mailing list _and_ GitHub. This just creates redundant work in dealing with it. I'm closing this in favor of the patch in patchwork:
https://patchwork.ozlabs.org/project/openwrt/patch/20201031140615.1687-1-mkroken@gmail.com/

@swg0101 Note that recently updated state would not have met the formal requirements in several ways. Does not matter anymore now, though.

**Pull request closed without merging**
