### PR TITLE
tools/expat: update to 2.6.0

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Changelog:
https://github.com/libexpat/libexpat/blob/R_2_6_0/expat/Changes

### CODE REVIEW

**Comment by schuettecarsten** [comment]
Expat 2.6.0 fails to build with GCC 13:

```
checking whether ccache /home/cschuette/openwrt/snapshot/openwrt/staging_dir/host/bin/g++ supports C++11 features with -std=c++11... no
checking whether ccache /home/cschuette/openwrt/snapshot/openwrt/staging_dir/host/bin/g++ supports C++11 features with +std=c++11... no
checking whether ccache /home/cschuette/openwrt/snapshot/openwrt/staging_dir/host/bin/g++ supports C++11 features with -h std=c++11... no
checking whether ccache /home/cschuette/openwrt/snapshot/openwrt/staging_dir/host/bin/g++ supports C++11 features with -std:c++11... no
checking whether ccache /home/cschuette/openwrt/snapshot/openwrt/staging_dir/host/bin/g++ supports C++11 features with -std=c++0x... no
checking whether ccache /home/cschuette/openwrt/snapshot/openwrt/staging_dir/host/bin/g++ supports C++11 features with +std=c++0x... no
checking whether ccache /home/cschuette/openwrt/snapshot/openwrt/staging_dir/host/bin/g++ supports C++11 features with -h std=c++0x... no
checking whether ccache /home/cschuette/openwrt/snapshot/openwrt/staging_dir/host/bin/g++ supports C++11 features with -std:c++0x... no
configure: error: *** A compiler with support for C++11 language features is required.
make[3]: *** [Makefile:34: /home/cschuette/openwrt/snapshot/openwrt/build_dir/host/expat-2.6.0/.configured] Error 1
```

**Comment by xback** [comment]
On a perfect clean directory it works as expected.
But as soon as I use it with oldconfig and custom patches in a local build, I have this build error.

It's on my investigation list too why this happens.

**Comment by PolynomialDivision** [comment]
Maybe it has something todo with ccache?

**Comment by PolynomialDivision** [comment]
https://github.com/libexpat/libexpat/blob/b7e1a1101133725c79e2170b0870cca8543e5323/expat/Changes#L50

**Comment by xback** [comment]
> Maybe it has something todo with ccache?

yeah .. spot-on ..
Tested on 2 fresh clones, 1 with ccache enabled and 1 disabled.

The ccache-enabled build fails at expat

**Comment by PolynomialDivision** [comment]
Should we revert it until we found a fix?

**Comment by xback** [comment]
Nah,

This fixes it:

```
From ff577689aa84ab39a04a93f317242273d6f6f41f Mon Sep 17 00:00:00 2001
From: Koen Vandeputte <koen.vandeputte@citymesh.com>
Date: Thu, 15 Feb 2024 11:52:29 +0100
Subject: [PATCH] tools/expat: fix build error with ccache

Disable compilation of separate tests as it causes
a build error when combined with ccache

Signed-off-by: Koen Vandeputte <koen.vandeputte@citymesh.com>
---
 tools/expat/Makefile | 1 +
 1 file changed, 1 insertion(+)

diff --git a/tools/expat/Makefile b/tools/expat/Makefile
index c1a8cb8d97..c0a6603b7d 100644
--- a/tools/expat/Makefile
+++ b/tools/expat/Makefile
@@ -24,6 +24,7 @@ HOSTCC := $(HOSTCC_NOCACHE)
 HOST_CONFIGURE_ARGS += \
        --disable-shared \
        --without-docbook \
+       --without-tests \
        --with-pic
 
 define Host/Uninstall
-- 
2.34.1

```

**Pull request merged**
