### PR TITLE
kernel: 2500bx quirk and tx fixup for GPON-ONU-34-20BI

### PR DESCRIPTION
**Pull request by tidalf**
The sfp device GPON-ONU-34-20BI can operate at 2500base-X but doesn't announce it like the huawei MA5671A. This patch also adds the ignore tx fault fixup (to prevent error messages and disabling of the device if the serial redirection is enabled)

### CODE REVIEW

**Comment by john-tho** [comment]
No need for this to be a hack. Please send it upstream to netdev, then it can be a pending patch. They usually want the ethtool module eeprom info in the commit message as well.
Plenty of examples in the list archive: https://lore.kernel.org/netdev/?q=s%3Asfp+s%3Aquirk

**Comment by hauke** [comment]
Please send this patch also to the upstream Linux kernel.
After you send it add that patch to OpenWrt pending directory and add the link to the mailing list post to the pull request description.

Please do not add merges to the pull request, but do rebases and then force push to your branch.

**Comment by Ansuel** [comment]
@tidalf net-next should open in some days now... If you have some problem with submitting the patch, if you want I can take care of doing it but you need to give me some info and help me with some reasoning :D (if you have problem with submitting yourself)

**Comment by Ansuel** [comment]
@tidalf net-next accept new patch now, any news with this?

**Comment by Ansuel** [comment]
Suppressed by https://github.com/openwrt/openwrt/pull/13563

**Pull request closed without merging**
