### PR TITLE
generic: trim outdated kernel config symbols

### PR DESCRIPTION
**Pull request by DragonBluep**
<details>
<summary>scripts</summary>

```
#!/bin/bash

# Author: Shiji Yang <yangshiji66@outlook.com>
# Copy this file to the kernel directory and then run it.
pattern="Kconfig*"
symbols="/tmp/ksymbols"
configs="/tmp/kconfig"
src="/workspaces/openwrt/target/linux/generic/config-6.1"

# fetch all Kconfig symbols
readarray kconfig_paths < <(find . -name "$pattern")

len=${#kconfig_paths[*]}
echo "found $len Kconfig files!"

[[ -f $symbols ]] && rm $symbols
for p in ${kconfig_paths[@]}; do
	cat $p | sed -n '/config\s*[A-Z0-9_]/p' >> $symbols
done

sed -i 's/menuconfig\s*/CONFIG_/' $symbols
sed -i 's/config\s*/CONFIG_/' $symbols
sed -i 's/^\s*//g' $symbols


# query line index and remove
cat $src > $configs
sed -i 's/\# //g' $configs
sed -i 's/ is not set//g' $configs
sed -i 's/=.*$//g' $configs

cnt1=0
cnt2=0
for line in `cat $configs`
do
	((cnt1++))
	if [ $(cat $symbols | grep "^$line$" | wc -l) -eq 0 ]; then
		mark[$cnt2]=$cnt1
		((cnt2++))
	fi
done
cat $src > $configs

echo "$cnt2 outdated symbols will be removed!"
while(( $cnt2>0 ))
do
	((cnt2--))
	sed -i "${mark[$cnt2]}d" $configs
done
cat $configs > $src

```

</details>

### CODE REVIEW

**Comment by hauke** [comment]
nice work

Currently it should be possible to run 'make kernel_oldconfig' on target kernel configurations and no needed symbols should get removed. If a config option gets removed and is needed we moved it into the generic configuration. The refresh is done without any extra kernel packages selected. Some configuration options are only visible when some extra kernel packages are selected. As an alternative we can also add such configuration options to the package.

**Comment by DragonBluep** [comment]
Update:
1. Rebase to solve the file conflicts and x86 target build issue.
2. Remove changes for kernel 5.15 and 6.1. They will be dropped soon.

> Currently it should be possible to run `make kernel_oldconfig` on target kernel configurations and no needed symbols should get removed.

`make kernel_oldconfig` seems unable to clean dead symbols from `generic` config. For example, the first trimmed symbol `CONFIG_64BIT_TIME` has already been removed since kernel 5.5 https://github.com/torvalds/linux/commit/3ca47e958a64b1116a2c35e65dcf467fc53d52de.

> If a config option gets removed and is needed we moved it into the generic configuration. The refresh is done without any extra kernel packages selected. Some configuration options are only visible when some extra kernel packages are selected. As an alternative we can also add such configuration options to the package.

Yes. And regarding this PR, GitHub will compile all packages and targets, so I think if the CI doesn't fail, it should be safe. All symbols are automatically trimmed. They are not **unused** symbols, but **non-existent** symbols.

**Comment by hauke** [comment]
The generic configuration was never trimmed and we do not have an automated process for that. Thanks for writing the script and running it.

**Comment by guidosarducci** [comment]
Thanks, this looks nice. Any plans to contribute the script itself via PR?

**Comment by hauke** [comment]
Please create a PR to add the script to the /scripts folder in the main repository or the https://git.openwrt.org/?p=maintainer-tools.git;a=summary repository.

**Comment by DragonBluep** [comment]
Thanks. I am not good at shell programming, but I will give it a try when I have time.

**Pull request merged**
