### PR TITLE
include: drop relevant default packages when ipv6 is not support

### PR DESCRIPTION
**Pull request by rosysong**
Signed-off-by: Rosy Song <rosysong@rosinson.com>

### CODE REVIEW

**Comment by jow-** [comment]
This should not be needed if the relevant packages depend on `@IPV6` themselves.

**Comment by rosysong** [comment]
Yes but in this case(ipv4 only)  It  just drop the ip6tables, odhcpd-ipv6only, and odhcp6c and seems has no affect for the packages build.

**Comment by jow-** [comment]
I am fine with letting IPv6 specific packages depend on @IPV6 but I do not want to sprinkle !IPV6 specific hacks everywhere.

**Comment by rosysong** [comment]
Yes, maybe you have a point, I should pay attention on "@IPV6", Thank you.

**Comment by dedeckeh** [comment]
I agree with @jow- this looks too hacky; same remark is valid for PRs https://github.com/openwrt/openwrt/pull/1394 and https://github.com/openwrt/openwrt/pull/1395

**Pull request closed without merging**
