### PR TITLE
iproute2: update to 5.1.0

### PR DESCRIPTION
**Pull request by dengqf6**
Update iproute2 to 5.1.0
Remove upstream patch 010-cake-fwmark.patch

### CODE REVIEW

**Comment by dedeckeh** [comment]
This fails to compile if devlink package is enabled

In file included from devlink.c:25:0:
/home/dedeckeh/arm-virt-staging/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.4.0_musl_eabi/include/sys/sysinfo.h:10:8: error: redefinition of 'struct sysinfo'
 struct sysinfo {
        ^~~~~~~
In file included from ../include/uapi/linux/kernel.h:5:0,
                 from ../include/uapi/linux/netlink.h:5,
                 from ../include/uapi/linux/genetlink.h:6,
                 from devlink.c:21:
../include/uapi/linux/sysinfo.h:8:8: note: originally defined here
 struct sysinfo {
        ^~~~~~~
devlink.c: In function 'pr_out_u64':
devlink.c:1729:11: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t {aka long long unsigned int}' [-Wformat=]
    pr_out("%s %lu", name, val);
           ^
devlink.c:59:21: note: in definition of macro 'pr_out'
   fprintf(stdout, ##args);   \
                     ^~~~
devlink.c:1731:11: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t {aka long long unsigned int}' [-Wformat=]
    pr_out(" %s %lu", name, val);
           ^
devlink.c:59:21: note: in definition of macro 'pr_out'
   fprintf(stdout, ##args);   \
                     ^~~~
devlink.c: In function 'pr_out_uint64_value':
devlink.c:1756:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint64_t {aka long long unsigned int}' [-Wformat=]
   pr_out(" %lu", value);
          ^
devlink.c:59:21: note: in definition of macro 'pr_out'
   fprintf(stdout, ##args);   \
                     ^~~~

**Comment by dengqf6** [comment]
Added a patch to fix the redefinition error on musl libc

**Comment by dedeckeh** [comment]
The patch should go upstream to the iproute2 git repo as well otherwise the risk exists we've to carry another patch forever

**Comment by dengqf6** [comment]
This is what I found https://lore.kernel.org/patchwork/patch/449607/
It seems related to `include/uapi/linux/kernel.h`, but the patch never got merged

**Comment by dengqf6** [comment]
Backported an upstream patch to fix the redefinition issue @dedeckeh

**Comment by dedeckeh** [comment]
Patch pulled into master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=917eeaf26bca5342817419d0c360301896932476); thx

**Pull request closed without merging**
