### PR TITLE
kernel: qca-ssdk: update 12.5 to 2024-06-13

### PR DESCRIPTION
**Pull request by skramstad**
There are some new commits, so refresh and update patches. Some build warnings have been fixed upstream too.

Add backport `target/linux/generic/backport-6.6/722-v6.10-dt-bindings-arm-qcom-ids-Add-SoC-ID-for-IPQ5321.patch`.

**Removed upstream:**
```
[-] qca-ssdk/patches/101-hsl_phy-add-support-for-detection-PSGMII-PHY-mode.patch
[-] qca-ssdk/patches/201-fix-compile-warnings.patch
```

**List of changes:**
```
2024-04-16  -c451136b-  qca-ssdk: strip MRPPE code
2024-06-05  -f455a820-  [qca-ssdk]: fix enum-int-mismatch warnings
2024-05-31  -bbfc0fa9-  Merge "[qca-ssdk]: update eee status of phydev"
2024-05-31  -adbe9dc5-  Merge "[qca-ssdk]: support psgmii and uqsxgmii mode of kernel"
2024-05-31  -d06ca777-  Merge "[qca-ssdk]: fix 5G issue with the AQR FW that use 5gbaser for 5G speed"
2024-05-31  -c6f539a5-  Merge "qca-ssdk: support mrppe pktedit padding functions"
2024-04-29  -c321e2a9-  qca-ssdk: support mrppe pktedit padding functions
2024-05-24  -ee6e201e-  qca-ssdk: Fix the big endian compile error
2024-05-15  -8c116bb9-  [qca-ssdk]: update eee status of phydev
2024-05-20  -f0341a2c-  Merge "qca-ssdk: Enable igmp for PPE MINI profile"
2024-05-16  -44a0ce93-  qca-ssdk: Enable igmp for PPE MINI profile
2024-05-15  -8b91bbf6-  [qca-ssdk]: support psgmii and uqsxgmii mode of kernel
2024-05-14  -7eec1658-  [qca-ssdk]: fix 5G issue with the AQR FW that use 5gbaser for 5G speed
2024-05-12  -b9f5ea0e-  [qca-ssdk]: ethtool support, do not change wake-up timer when the requested timer is 0
2024-05-09  -5e2c15ed-  Merge "[qca-ssdk]: remove check when mht clock enable"
2024-05-09  -a1563b90-  Merge "[qca-ssdk] support new sku IPQ5321"
2024-04-23  -f04b7680-  [qca-ssdk]: show unknown status when link down
2024-03-22  -33b91b30-  [qca-ssdk]: remove check when mht clock enable
2024-04-29  -b6362f2b-  Merge "qca-ssdk:fix bug in marina nptv6 iid cal"
2024-04-29  -097033ae-  Merge "[qca-ssdk] support cypress uniphy0 connecting MHT switch port0"
2024-04-24  -d45560fd-  qca-ssdk:fix bug in marina nptv6 iid cal
2024-04-24  -7d7a42af-  qca-ssdk: enable policer counter on low memory profile
2024-04-18  -e36cf6ea-  Merge "[qca-ssdk]: change portvlan egress mode initial value as untouched"
2024-04-18  -27817881-  Merge "[qca-ssdk]: update the aqr phy supported ability"
2024-04-18  -5a3a693c-  Merge "qca-ssdk:support marina nptv6"
2024-04-16  -129fe9b3-  Merge "qca-ssdk: support tunnel fields and innner fields inverse"
2024-01-09  -fc8f6abd-  qca-ssdk:support marina nptv6
```
Tested on WAX620.

Signed-off-by: Kristian Skramstad <kristian+github@83.no>

### CODE REVIEW

**Comment by skramstad** [comment]
Robi: Don't know if this breaks anything but they added in file https://git.codelinaro.org/clo/qsdk/oss/lklm/qca-ssdk/-/blob/NHSS.QSDK.12.5/src/hsl/phy/hsl_phy.c?ref_type=heads#L1349
```
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(6,6,0))
		case PHY_INTERFACE_MODE_PSGMII:
			*interface_mode_status = PHY_PSGMII_BASET;
			break;
#endif
```
and in our patch `101-hsl_phy-add-support-for-detection-PSGMII-PHY-mode.patch` we had
```
+		case PHY_INTERFACE_MODE_PSGMII:
+			*interface_mode_status = PHY_PSGMII_BASET;
+			break;
```
Also, I'm not sure about removing `case QCOM_ID_IPQ5321:` in file https://git.codelinaro.org/clo/qsdk/oss/lklm/qca-ssdk/-/blob/NHSS.QSDK.12.5/src/init/ssdk_plat.c?ref_type=heads#L1693 but it did complain about "first time use of `QCOM_ID_IPQ5321`, are you sure you didn't mean `QCOM_ID_IPQ5332`. And I could not figure out how to fix this, looking at i.e `QCOM_ID_IPQ5332`.

**Comment by robimarko** [comment]
`IPQ5321` ID is missing in socinfo so that is why its failing, its a recent addition upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/include/dt-bindings/arm/qcom,ids.h?h=next-20240621&id=27c42e925323b975a64429e313b0cf5c0c02a411

So, we can either backport it or revert that commit in SSDK.

**Comment by robimarko** [comment]
As for the `101-hsl_phy-add-support-for-detection-PSGMII-PHY-mode.patch`, we should be able to drop it as QCA added the same thing upstream.

**Comment by skramstad** [comment]
I added the backport patch and removed patch 201. Did I get the naming right for `target/linux/qualcommax/patches-6.6/0023-v6.7-dt-bindings-arm-qcom-ids-Add-SoC-ID-for-IPQ5321.patch`?

Unsure about v6.7,v6.8 etc...

**Comment by robimarko** [comment]
Its not in 6.9 as well, so make it `v6.10`

**Comment by skramstad** [comment]
Alright. You are referring to folder `target/linux/generic/backport-6.6/` right?

**Comment by robimarko** [comment]
> Alright. You are referring to folder `target/linux/generic/backport-6.6/` right?

Yes, you will find more QCA SOC ID backports, so just put it after them

**Comment by skramstad** [comment]
Moved patch to `target/linux/generic/backport-6.6/722-v6.10-dt-bindings-arm-qcom-ids-Add-SoC-ID-for-IPQ5321.patch` and ran `make -j1 target/linux/refresh V=sc`.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by skramstad** [comment]
Thanks 👍

**Pull request merged**
