### PR TITLE
build: add CMAKE_PREFIX_INSTALL and CMAKE_GENERATOR variables in cmake.mk

### PR DESCRIPTION
**Pull request by ja-pa**
This allows switching cmake to other types for generators
for example Ninja etc and set a prefix for installation.

Signed-off-by: Jan Pavlinec <jan.pavlinec@nic.cz>

### CODE REVIEW

**Comment by diizzyy** [comment]
Perhaps worth making cmake generators a toolchain menu option?

**Comment by ja-pa** [comment]
@diizzyy Hi,
I can add a menu option for that, but I have a concern that it can mislead some users since without Build/Compile/Default adaptation for Ninja (or other generators) build will fail since it will use make.


<idea_description>
My idea, for now, is that I will add Ninja to packages feed  (more info about that decision is https://github.com/openwrt/openwrt/pull/1871  and  https://github.com/openwrt/packages/issues/8315 . And it would be possible for new packages to include include ninja.mk which would set generator for cmake accordingly  
</idea_description>

**Comment by adrianschmutzler** [comment]
Your commit title seems to be wrapped as it is too long. Please fix that.

**Comment by adrianschmutzler** [comment]
Hi, since this is not a fix, but a feature, and none of the committer seems to be interested in reviewing it, I will close it now (i.e. "Won't implement").

I'm sorry, but better crush your remaining hopes now than waiting another year where supposedly nothing different will happen.

**Pull request closed without merging**
