### PR TITLE
odhcp6c: update to Git HEAD (2024-09-25)

### PR DESCRIPTION
**Pull request by try496**

### CODE REVIEW

**Comment by ynezz** [comment]
Can you do the version bump with https://git.openwrt.org/?p=maintainer-tools.git;a=blob_plain;f=update_git_source_package.sh;hb=HEAD ? It will do the bump automatically, with everything done as expected.

1. `PKG_MIRROR_HASH` seems wrong here
2. `PKG_RELEASE:=1` should be set
3. It will provide correct Git commit subject `odhcp6c: update to Git HEAD (2024-09-25)`

IMO the version bump is not enough:

1. there is config validator 'reqprefix:or("auto","no",range(0, 64))' so you wont be able to set IPv6 address in the prefix
2. the [documentation on the wiki](https://openwrt.org/docs/guide-user/network/ipv6/configuration#protocol_dhcpv6) should be adapted

**Comment by try496** [comment]
屏幕截图 2024-11-19 132510
I have changed the address several times and have obtained the specified prefix each time. I entered it here.

**Comment by ynezz** [comment]
> When I enter the IP address and prefix, I successfully obtain the designated IPv6 prefix from the ISP.

Ok, good, so my understanding is wrong, there is no validation happening.

**Comment by ynezz** [comment]
> 2. the [documentation on the wiki](https://openwrt.org/docs/guide-user/network/ipv6/configuration#protocol_dhcpv6) should be adapted

Updated https://openwrt.org/docs/guide-user/network/ipv6/configuration?do=diff&rev2%5B0%5D=1729690074&rev2%5B1%5D=1732007460&difftype=inline

**Comment by systemcrash** [comment]
Context https://github.com/openwrt/luci/issues/7397

**Comment by Neustradamus** [comment]
@try496: Thanks!

Backported for 24.10:
- https://github.com/openwrt/openwrt/pull/17016 (closed)
- https://github.com/openwrt/openwrt/pull/17017

Can be done for 23.05.x too?

Linked to:
- https://github.com/openwrt/odhcp6c/issues/92

**Pull request merged**
