### PR TITLE
tools/kernel2minor: Update to 0.26

### PR DESCRIPTION
**Pull request by SvenRoederer**
This adds some checks to avoid truncation of filenames, which will cause silent build-errors. Also fixes some compiler-warnings.

@nbd168

### CODE REVIEW

**Comment by SvenRoederer** [comment]
@nbd168 @mkresin  Ping...
So far I'm using this since some time in out Firmware without issues.

**Comment by adschm** [comment]
Does this affect you and can you comment/test: @robimarko @f00b4r0 @john-tho

**Comment by john-tho** [comment]
Worked fine for me on an ath79 squashfs test install & boot.
The source changes made in this bump: https://github.com/adron-s/kernel2minor/compare/1e5a52c7941945f6d64807ebca4a5923ba5466bd...062eed9f47e8f47a5aeb659558ad5548697dc8e2

**Comment by aparcar** [comment]
ping @robimarko @f00b4r0 please comment :)!

**Comment by f00b4r0** [comment]
Upstream code is unparsable and unreviewable. It has some intrinsic issues (the result is not fully YAFFS compliant), and it's also an ugly workaround for the fact that YAFFS is no longer supported in OpenWRT.

The main consequence of that workaround is that it turns all NAND-based devices into ticking timebombs, since no badblock management is performed, resulting in e.g. [this](https://forum.openwrt.org/t/rb433-bad-sector-cannot-start-openwrt/71519/11). See more details [here](https://github.com/openwrt/openwrt/pull/3026#issuecomment-673597461) and in the following comments.

With all that said, I'm not inclined to review a PR on this tool, which I think should be entirely replaced anyway. My suggestion is we shouldn't accept any change unless it _fixes_ something, and it's unclear to me that this particular PR does. In fact, a quick glimpse at the upstream diff suggests it may introduce new bugs.

My 2c :)

**Comment by aparcar** [comment]
@f00b4r0 thanks for your feedback. I only looked at the changes provided by @john-tho and it doesn't look terribly complicated. I think it's fine to merge.

Apart from that I can't talk about what `kernel2minor` does and how it's implemented. If there are better alternatives please share!

**Comment by robimarko** [comment]
@f00b4r0 I agree that the code is not rather pretty and it has bugs, but I am for merging this minor update.
Until a better solution appears this is the only one available.

**Comment by f00b4r0** [comment]
@robimarko the very first hunk in the upstream patch looks like it applies sizeof() to a pointer:

```
-  strncpy(oh->name, name, YAFFS_MAX_NAME_LENGTH);
 + strcpy_safe(oh->name, name);
```

Definition of `strcpy_safe()`:
```
//safe copy string s -> d
#define strcpy_safe(d, s){			\
	strncpy(d, s, sizeof(d) - 1);	\
	d[sizeof(d) - 1] = '\0';			\
}
```

Does this look "safe" to you? 😛 

I'm not interested in reviewing this code, but I'm of the opinion that someone who can't correctly use strncpy() should not be trusted to provide bug-free "updates".

Once again, what does this new "release" fix?

**Comment by robimarko** [comment]
@f00b4r0 Like I said, I agree that the code is full of bugs and questionable choices.

**Comment by f00b4r0** [comment]
> @f00b4r0 thanks for your feedback. I only looked at the changes provided by @john-tho and it doesn't look terribly complicated. I think it's fine to merge.

As illustrated above, I suspect it introduces more bugs and fixes none.

> Apart from that I can't talk about what `kernel2minor` does and how it's implemented. If there are better alternatives please share!

The problem is that for optimal support of Mikrotik devices, we would need YAFFS in OpenWRT. My understanding is that YAFFS support was dropped after 15.05, I'm not exactly sure why (overhead to other platforms who use ubifs might be the reason).

Either we reintroduce full YAFFS support (might be an option now that mikrotik devices live in their own subtarget, but it's going to be an extra maintenance burden for the build system), or I think we should at the very least stop advertising NAND-based devices as supported and drop support for them since kernel2minor or any clean rewrite of this tool will not provide bad block management.

My 2c.

**Comment by robimarko** [comment]
@f00b4r0 The issue with yaffs is that the upstream kernel has no support for it.
So it was dropped after kernel2minor got rid of the requirement for it as it would stall kernel bumps to the support for it needing constant updates.

**Comment by f00b4r0** [comment]
> @f00b4r0 The issue with yaffs is that the upstream kernel has no support for it.
> So it was dropped after kernel2minor got rid of the requirement for it as it would stall kernel bumps to the support for it needing constant updates.

I see, thanks. Then we're in a bad situation, unless mikrotik comes to their senses and finally add support for something less retarded in their bootloader. I'm not sure if anyone ever tried to flash a raw ELF kernel with recent boards, maybe it works? ;^)

**Comment by robimarko** [comment]
> I see, thanks. Then we're in a bad situation, unless mikrotik comes to their senses and finally add support for something less retarded in their bootloader. I'm not sure if anyone ever tried to flash a raw ELF kernel with recent boards, maybe it works? ;^)

Tried it with hAP ac2, no luck as it searches for the magic.

**Comment by SvenRoederer** [comment]
> My suggestion is we shouldn't accept any change unless it _fixes_ something, and it's unclear to me that this particular PR does. In fact, a quick glimpse at the upstream diff suggests it may introduce new bugs.
> 

My primary reason for this PR was to get the changes of this PR https://github.com/adron-s/kernel2minor/pull/2 into OpenWrt. Upstream code silently failed with long pathnames which caused hard to find buildfailures.

**Comment by f00b4r0** [comment]
> > My suggestion is we shouldn't accept any change unless it _fixes_ something, and it's unclear to me that this particular PR does. In fact, a quick glimpse at the upstream diff suggests it may introduce new bugs.
> 
> My primary reason for this PR was to get the changes of this PR [adron-s/kernel2minor#2](https://github.com/adron-s/kernel2minor/pull/2) into OpenWrt. Upstream code silently failed with long pathnames which caused hard to find buildfailures.

I see. So now it'll still fail, only not silently. Not sure if that's much of an improvement ;P
Seems to me the correct fix would be not to have hardcoded limits to both arguments (which should be trivial to implement, but I'm not going down that rabbit hole).

This change in itself is "ok". The problem is it's now packaged with other changes which don't look so ok...

**Comment by SvenRoederer** [comment]
Sure, still no perfect code, but much more easy to find, what makes the build fail.

If the code-quality is not acceptable, we can also use only the "file-length patch" locally in OpenWrt on top of current v0.25 code. But not sure, if keeping a local patch is that great alternative to upstream-code.

**Comment by PolynomialDivision** [comment]
Could it be that just the file-max length and maximum file**path** length was switched? I wrote a patch using the correct buffer sizes:

https://github.com/openwrt/openwrt/pull/4152

**Comment by f00b4r0** [comment]
The Freifunk fix mentioned above is clean and does not require pulling more questionable changes. I'd suggest using it instead of this.

**Comment by PolynomialDivision** [comment]
> The Freifunk fix mentioned above is clean and does not require pulling more questionable changes. I'd suggest using it instead of this.

As the kernel2minor programm writes, "r" and "k" give:
```
  -k   Path to kernel file                     
  -r   Path to result file 
```
So they give filepaths. And kernel2minor uses for whatever reason the hardcoded 255 file-name length limit. I think my change is correct, but I'm also afraid that something breaks at another point if I do the change.

However, in the Freifunk patch I do not understand the line
```
kernel2minor -k $(temp_file) -r /tmp/bar $(1)
mv $(temp_file) $@
```
Should that be 
```
mv /tmp/bar $@
```
?

**Comment by SvenRoederer** [comment]
The Freifunk patch is my initial work (PR adron-s/kernel2minor#2)?

Don't see the shell-code mentioned by @PolynomialDivision

**Comment by f00b4r0** [comment]
> The Freifunk patch is my initial work (PR [adron-s/kernel2minor#2](https://github.com/adron-s/kernel2minor/pull/2))?

No.

> Don't see the shell-code mentioned by @PolynomialDivision

See #4155

**Comment by SvenRoederer** [comment]
@f00b4r0 thanks

**Comment by adschm** [comment]
Since nobody picked this in a long time and we have an alternate patch for the underlying issue merged now [1], I'm closing this.

[1] https://github.com/openwrt/openwrt/commit/5a9608102b3c444d0c963255f9d016a1d5469d5d

**Pull request closed without merging**
