### PR TITLE
ath79: move device specific nodes to respective dts files

### PR DESCRIPTION
**Pull request by zpc0**
qca9558_devolo_dvl1xxx.dtsi contains device specific nodes.
To improve simplicity, move such nodes.

### CODE REVIEW

**Comment by adschm** [comment]
Thanks, will be merged later today.

**Comment by mpratt14** [comment]
Too bad I didn't see this sooner

It is very likely that, even though there was differences in the original commits (maybe because u-boot uses different register values) that eth0 and gmac_config nodes SHOULD be the same...

all 6 of these boards use the same switch PHY (AR8035)

from my research and experience with other boards with the AR8035, the following configuration should work perfectly for all of them (with master branch today)

@zpc0 see my comment if you like
https://github.com/openwrt/openwrt/pull/3505#issuecomment-716050292

```
&eth0 {
	status = "okay";

	mtd-mac-address = <&art 0x0>;

	phy-handle = <&phy4>;
	phy-mode = "rgmii-id";

	pll-data = <0x82000000 0x80000101 0x80001313>;

	gmac-config {
		device = <&gmac>;
		rgmii-enabled = <1>;
		rxdv-delay = <3>;
		rxd-delay = <3>;
	};
};
```

it might also work without `rxdv-delay` and `rxd-delay`

@blocktrron @djangoa you would be able to verify if you still have access to all of them...

**Comment by blocktrron** [comment]
@mpratt14 Does not work on the 1200e (90% packet loss on 100 Mbit/s)

**Comment by mpratt14** [comment]
pll-data is unchanged for speed 100 Mbit....

maybe you need all the delay bits in gmac_config

```
&gmac_config {
	rxdv-delay = <3>;
	rxd-delay = <3>;
	txen-delay = <3>;
	txd-delay = <3>;
};
```

**Comment by blocktrron** [comment]
Sorry, I've missed the last zero, packet loss occurred on 1000 Mbit/s.

The Ethernet configuration originated from the vendor GPL dumps which were explicitly defined for each model. So it is not an accident that these all differ.

**Comment by mpratt14** [comment]
Interesting...

all the Engenius boards I worked on also had different settings for this register, but I have had success with this pattern.

the kernel log is identifying the chip correctly? like this?

`[    0.794447] ag71xx 19000000.eth: connected to PHY at mdio.0:04 [uid=004dd072, driver=Atheros 8035 ethernet]`

**Comment by mpratt14** [comment]
@blocktrron so either way we can still make it common...forgetting about setting the delay with PHY driver only...

so using the original `pll-data`

```
&eth0 {
	status = "okay";

	mtd-mac-address = <&art 0x0>;

	phy-handle = <&phy4>;
	phy-mode = "rgmii-id";

	pll-data = <0xae000000 0x80000101 0x80001313>;

	gmac-config {
		device = <&gmac>;
		rgmii-enabled = <1>;
		rxdv-delay = <3>;
		rxd-delay = <3>;
		txen-delay = <3>;
		txd-delay = <3>;
	};
};
```

**Comment by blocktrron** [comment]
The delays necessary depend on how the traces on the PCB are designed. As these are different board to board here, i don't see how (and why at all) this should have a one-size-fits-all solution.

Also there is a cross-dependency on the clock generation depending on gmac1.

**Comment by mpratt14** [comment]
ok these are more complicated than I thought, I assumed same company and same switch would have same board design

**Pull request closed without merging**
