### PR TITLE
NLS cleanup

### PR DESCRIPTION
**Pull request by neheb**
Setting as draft until I make sure all packages compile.

### CODE REVIEW

**Comment by neheb** [comment]
hmmm maybe second and third commit should be merged. thoughts?

**Comment by neheb** [comment]
So it turns out CMake's find_package(Iconv REQUIRED) is completely broken and doesn't work with nls.mk at all. It needs to be overridden.

meson's dependency('iconv') works perfectly.

I think the best way forward is to remove nls.mk for those packages.

**Comment by neheb** [comment]
Going to mark this as ready. I've fixed most packages currently. Others will be dealt with when libiconv-stub is gone.

**Comment by Ansuel** [comment]
@neheb do you want me to run this under the github actions and check if we have additional package not compiled?

**Comment by neheb** [comment]
@Ansuel wouldn’t hurt.

**Comment by neheb** [comment]
@mhei useless how? musl has iconv

**Comment by mhei** [comment]
@neheb: "useless" is maybe wrong wording, but when looking at the help description of `CONFIG_BUILD_NLS`:

> bool "Compile with full language support"
> help
>       When this option is enabled, packages are built with the full versions of
>       iconv and GNU gettext instead of the default OpenWrt stubs. If uClibc is
>       used, it is also built with locale support.

I mean: previously we removed iconv/gettext functionality mostly completely when this option was not selected, right? The stubs however allowed to compile packages which did not offer selecting iconv/gettext usage during configure/compile time. Now that musl brings "strong for its size, but not comprehensive like glibc’s" iconv support, we don't have such a large impact of this switch anymore as previously.
At least, the description should be updated IMO.

**Comment by neheb** [comment]
Sure I can update the description.

**Comment by neheb** [comment]
@mhei updated.

**Comment by mhei** [comment]
Thnx. Just removing the wrong part is ok, but wouldn't it be even better to describe the behavior with musl gettext/iconv implementation?

For example:

> By default, musl libc provides gettext and iconv functionality - which is "is very strong for its size, but not comprehensive like glibc’s" [1]. With this option enabled, packages are built with the standalone, full versions of iconv and GNU gettext - and the package dependencies are adjusted accordingly, which in turn increases the overall footprint of the filesystem.
> 
> [1] https://wiki.musl-libc.org/functional-differences-from-glibc.html

What do you think?

**Comment by mhei** [comment]
Good point. But if I was an ordinary OpenWrt user, not deeply involved in programming stuff etc., what is the benefit/gain of enabling this option for glibc? Can you describe it?

**Comment by neheb** [comment]
According to https://lists.gnu.org/archive/html/bug-gnu-libiconv/2010-05/msg00010.html , seems to be a difference in locale dependence.

Ordinary OpenWrt users don't use the SDK or build their own packages.

Anyway, I made a small change.

**Comment by neheb** [comment]
This is ready for inclusion. ping @Ansuel

**Comment by chunkeey** [comment]
Merged. Thanks. I'm curious what will show up. I tried running some targets and SDK builds in my cases it all worked fine.

**Comment by dhewg** [comment]
This shows up here:
```
WARNING: Makefile 'package/feeds/packages/glib2/Makefile' has a build dependency on 'libiconv/host', which does not exist
WARNING: Makefile 'package/feeds/packages/glib2/Makefile' has a build dependency on 'libiconv/host', which does not exist
WARNING: Makefile 'package/feeds/packages/softethervpn/Makefile' has a build dependency on 'libiconv/host', which does not exist
```

**Comment by chunkeey** [comment]
@dhewg true, I think it is also interesting to see what the package builds looks like.

so far:

```
WARNING: Makefile 'package/feeds/packages/acsccid/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/acsccid/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/alpine/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/apache/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/apparmor/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/apr-util/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/aria2/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/asterisk/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/asterisk-chan-dongle/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/asterisk-chan-sccp/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/augeas/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/avrdude/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/baresip/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/bind/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/binutils/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/bitlbee/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/bluez/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/bluez-tools/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/bluld/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/bpftools/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/bridger/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/ccid/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/clamav/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/collectd/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/conmon/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/coturn/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/crelay/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/cryptsetup/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/dmapd/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/dosfstools/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/dovecot/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/dtndht/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/elektra/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/elfutils/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/exim/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/fakepop/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/flent-tools/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gammu/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gcc/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/gdb/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gerbera/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/geth/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gkrellmd/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/glib2/Makefile' has a build dependency on 'libiconv/host', which does not exist
WARNING: Makefile 'package/feeds/packages/glib2/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/glib2/Makefile' has a build dependency on 'libiconv/host', which does not exist
WARNING: Makefile 'package/feeds/packages/gnunet/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gnunet-fuse/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gnupg2/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gphoto2/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/grilo/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/grilo-plugins/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gst1-libav/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gst1-plugins-bad/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gst1-plugins-base/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gst1-plugins-good/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gst1-plugins-ugly/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/gstreamer1/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/hidapi/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/hs20/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/httping/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/ibrcommon/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/ibrdtn/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/icecast/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/ices/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/iproute2/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/irqbalance/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/irssi/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/json-glib/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/kamailio/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/klish/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/ksmbd-tools/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/lcd4linux/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/lcdgrilo/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/lcdringer/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libdaq/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libdmapsharing/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libextractor/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libgee/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libgphoto2/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libidn2/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libiio/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libmariadb/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libmbim/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/liboil/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libp11/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libpsl/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libqmi/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libqrtr-glib/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libslirp/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libsoup/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libstrophe/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libv4l/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libxerces-c/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libxml2/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/libxslt/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/linknx/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/loudmouth/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/lttng-tools/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/madplay/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/mariadb/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/mbtools/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/mc/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/minicom/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/minidlna/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/mocp/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/modemmanager/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/monit/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/motion/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/mpd/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/msmtp/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/nbd/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/newt/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/nginx/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/node-hid/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/oor/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/open-vm-tools/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/openconnect/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/openocd/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/opensc/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/owntone/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/perf/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/php8/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/php8-pecl-dio/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/php8-pecl-http/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/php8-pecl-imagick/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/php8-pecl-krb5/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/php8-pecl-mcrypt/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/php8-pecl-raphf/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/php8-pecl-redis/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/php8-pecl-sodium/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/pigeonhole/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/pkg-config/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/policycoreutils/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/powertop/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/pulseaudio/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/qemu/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/qosify/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/quassel-irssi/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/quasselc/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/rpcsvc-proto/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/rsync/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/rtpengine/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/ruby/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/schroot/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/secilc/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/shadow/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/shared-mime-info/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/slang2/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/slirp4netns/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/smstools3/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/sofia-sip/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/softethervpn/Makefile' has a build dependency on 'libiconv/host', which does not exist
WARNING: Makefile 'package/feeds/packages/softethervpn5/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/speedtestpp/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/spice/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/sshfs/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/stoken/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/strace/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/strongswan/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/subversion/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/syslog-ng/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/sysstat/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/tcsh/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/totem-pl-parser/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/tvheadend/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/usbip/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/uvcdynctrl/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/vips/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/wolfssl/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/base/xdp-tools/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/telephony/yate/Makefile' has a build dependency on 'libiconv', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a build dependency on 'libiconv', which does not exist
```

a few base packages (strace, binutils, gdb,wolfssl,iproute2,perf,xdp-tools,secilc,qosify,elfutils) show up as well. I've seen those disappear when nls.mk gets updated. hmm, this should have happend, or are the phase2 sticking to a particular sdk?

**Comment by neheb** [comment]
Those should go away when tmp gets wiped.

**Comment by dhewg** [comment]
I got those too at first, but it went away from a clean build tree.

**Comment by chunkeey** [comment]
@dhewg 

@neheb followed up with: https://github.com/openwrt/openwrt/pull/10286 . I think this patch would quench those warnings.

**Comment by neheb** [comment]
Not quite. Once that patch is merged, I'll merge https://github.com/neheb/packages/commit/c44751003b03074d4b16b184aa4d783b4723152d .

**Pull request closed without merging**
