### PR TITLE
ath79: use realtek switch as loadable modules

### PR DESCRIPTION
**Pull request by luizluca**
ath79 was including all realtek switches as builtin modules, even with just a couple of devices using it.

target/linux/ath79/dts/ar7161_dlink_dir-825-b1.dts:             compatible = "realtek,rtl8366s";
target/linux/ath79/dts/ar7242_tplink_tl-wr2543-v1.dts:          compatible = "realtek,rtl8367";
target/linux/ath79/dts/ar9132_buffalo_wzr-hp-g300nh-rb.dts:     compatible = "realtek,rtl8366rb";
target/linux/ath79/dts/ar9132_buffalo_wzr-hp-g300nh-s.dts:      compatible = "realtek,rtl8366s";
target/linux/ath79/dts/ar9132_tplink_tl-wr1043nd-v1.dts:        compatible = "realtek,rtl8366rb";
target/linux/ath79/dts/ar7161_netgear_wndr.dtsi:                compatible = "realtek,rtl8366s";

target/linux/ath79/dts/ar7161_netgear_wndr3700.dts:#include "ar7161_netgear_wndr.dtsi"
target/linux/ath79/dts/ar7161_netgear_wndr3700-v2.dts:#include "ar7161_netgear_wndr.dtsi"
target/linux/ath79/dts/ar7161_netgear_wndr3800ch.dts:#include "ar7161_netgear_wndr.dtsi"
target/linux/ath79/dts/ar7161_netgear_wndr3800.dts:#include "ar7161_netgear_wndr.dtsi"
target/linux/ath79/dts/ar7161_netgear_wndrmac-v1.dts:#include "ar7161_netgear_wndr.dtsi"
target/linux/ath79/dts/ar7161_netgear_wndrmac-v2.dts:#include "ar7161_netgear_wndr.dtsi"

Those modules does work as loadable modules, debloating a little bit ath79 kernel for other devices.

This PR was tested with tl-wr1043nd-v1(rtl8366rb) and tplink_tl-wr2543-v1(rtl8367), both in failsafe and normal operation.
No device with rtl8366s was tested, although it looks straightforward.

### CODE REVIEW

**Comment by Borromini** [comment]
Out of curiosity, how much is shaved off the kernel with this?

**Comment by luizluca** [comment]
> Out of curiosity, how much is shaved off the kernel with this?

Nothing that would revive 4MB targets ;-) It reduces about 45kb, or 0,5% of its size.

```patch
-8063252 build_dir/target-mips_24kc_musl/linux-ath79_generic/vmlinux
-37935492 build_dir/target-mips_24kc_musl/linux-ath79_generic/vmlinux.debug
+8018116 build_dir/target-mips_24kc_musl/linux-ath79_generic/vmlinux
+37772968 build_dir/target-mips_24kc_musl/linux-ath79_generic/vmlinux.debug
```

**Comment by Borromini** [comment]
Alas, was worth a try :stuck_out_tongue_closed_eyes:.

**Comment by pkgadd** [comment]
Only tangentially related, but out of curiosity - did you happen to take a look at realtek_smi and moving those devices to DSA?

**Comment by luizluca** [comment]
> Only tangentially related, but out of curiosity - did you happen to take a look at realtek_smi and moving those devices to DSA?

Yes, I did looked at that/those driver/s a lot for the last couple of months. I refactored that realtek driver and implemented the support for MDIO-connected switches (as well as adding support for rtl8367s).

The driver for rtl8366rb, driver rtl8366rb.ko, seems to be in a good shape while rtl8366s and rtl8367 does not have support yet (although it might be easy to add to rtl8366rb.ko). The only device I have that could use it is tl-wr1043nd, but it is quite old and not very useful with only 32MB of RAM. I don't think it is worthy for now.

The models compatible with rtl8367c driver does work for rtl8365mb, rtl8367s and rtl8367rb with driver rtl8365mb.ko, but all forwarding happens in CPU and it only support RMII. Until someone implements the forwarding logic, rtl8365mb.ko is still not ready for production. It is relative easy to implement support for other switch models but support for SGMII might require a little bit of effort.

Anyway, moving those drivers into loadable modules is a good first step to get rid of swconfig.

**Comment by Ansuel** [comment]
@luizluca think we can merge this? I would ask to squash some commits but it's ok as is. What do you think?

**Comment by Leo-PL** [comment]
Yes please, this will ease DSA migration for ath79 as well.

**Comment by Ansuel** [comment]
@Leo-PL just waiting him and I will merge this

**Comment by Leo-PL** [comment]
BTW @luizluca I have a Flash-and-RAM-modded WR1043NDv1 and I could do some testing on it, do you have your patches pushed somewhere?

**Comment by luizluca** [comment]
> @luizluca think we can merge this? I would ask to squash some commits but it's ok as is. What do you think?

The patch series is good. It might be a couple of years late (I really missed those 45kb in the past) but it still relevant for DSA migration.

**Comment by luizluca** [comment]
> BTW @luizluca I have a Flash-and-RAM-modded WR1043NDv1 and I could do some testing on it, do you have your patches pushed somewhere?

I believe you mean the Realtek DSA switch drivers from upstream, right? https://github.com/luizluca/openwrt/commits/tplink_c5v4_dsa . It requires kernel 5.15. I didn't submit it yet as I was afraid some of those backported patches would eventually break another device DSA support. I was just being lazy and waiting for the next OpenWRt 5.20 kernel. However, as DSA migration is happening everywhere, most of those patches will eventually get backported anyway.

**Comment by luizluca** [comment]
> @luizluca just to make sure... Can you rebase this on top of master? I would have fixed it but just to make sure, pls rebase and check all the changes required.

Rebased and retested on tl-wr1043nd-v1 (OpenWrt SNAPSHOT, r19947+6-1005dc0a64)

**Comment by Leo-PL** [comment]
> > BTW @luizluca I have a Flash-and-RAM-modded WR1043NDv1 and I could do some testing on it, do you have your patches pushed somewhere?
> 
> I believe you mean the Realtek DSA switch drivers from upstream, right? https://github.com/luizluca/openwrt/commits/tplink_c5v4_dsa . It requires kernel 5.15. I didn't submit it yet as I was afraid some of those backported patches would eventually break another device DSA support. I was just being lazy and waiting for the next OpenWRt 5.20 kernel. However, as DSA migration is happening everywhere, most of those patches will eventually get backported anyway.

Yeah, I do mean upstream DSA for Realtek. I'll give it a spin in free time.

**Comment by Ansuel** [comment]
Thanks, merged in master with
```
6e0f0eae5b ath79: use rtl8366s and rtl8366_smi as a module
b129923b57 kernel: netdevices: load rtl8366s on boot
b168a07799 ath79: use rtl8367 as a module
96d056f5f0 kernel: netdevices: add rtl8367 module
575ec7a4b1 ath79: use rtl8366rb as a module
1b14e25d2e kernel: netdevices: load rtl8366rb on boot
```

**Pull request closed without merging**
