### PR TITLE
hostapd: bump to 2024-03-09

### PR DESCRIPTION
**Pull request by cotequeiroz**
Fixed upstream:
 - 001-wolfssl-init-RNG-with-ECC-key.patch
 - 022-hostapd-fix-use-of-uninitialized-stack-variables.patch
 - 180-driver_nl80211-fix-setting-QoS-map-on-secondary-BSSs.patch
 - 993-2023-10-28-ACS-Fix-typo-in-bw_40-frequency-array.patch

Upstream commit c74739250a ("AP MLD: Use a helper function to check if a STA is a non-AP MLD") forced some header changes, including new patch 461-Move-definition-of-WLAN_SUPP_RATES_MAX-to-defs.h.patch, and the the change to package/network/services/hostapd/src/src/ap/ubus.h.

---

~There's another pull request updating hostapd, #13911.  Given that the changes in the patches that I'm proposing in this PR are not trivial, it may be a good idea to merge #13911 first, and then move on to this.~

There are over 600 commits between current version and 2024-02-03, plus 94 to get to 2024-03-09.  To make this update, I imported the patches into a clone of hostap's git repository https://github.com/cotequeiroz/hostap/tree/openwrt-2023-09-08, and created two branches:  
- [openwrt_rebase](https://github.com/cotequeiroz/hostap/tree/openwrt_rebase): I rebased the openwrt patches on top of current git head.
- [openwrt_forward](https://github.com/cotequeiroz/hostap/tree/openwrt_rebase):  I rebased the current git head on top of the current openwrt version.

The goal is to ensure they both converge to a common base.  In order to make this easier, I propose to use the git version of the patches, that can be easily imported with `git am`, and do not interfere with quilt refresh.  It basically adds some headers, and changes the order of the files in some of the patches.  For this PR, I manually removed the headers and kept the current order of the patches, to make reviews easier.

I have built all packages variants for mediatek/aarch64, ath79/mips, mvebu/arm, and ramips/mipsel, and only run-tested this with the full openssl version on Linksys E8450 (mediatek), Archer C6 v2 (ath79), and Linksys WRT3200ACM (mvebu).

There appears to be some recent improvements in FT interoperability, especially with iOS devices, but the problems only happen sporadically, so it may need more time to confirm this.  FILS got some attention as well, but I have not played much with it.

~I'm keeping this as a draft for now until I get some feedback, and a decision is made about merging #13911 first.~

Edit: I'm officially giving up on #13911.  This should be ready to merge.

### CODE REVIEW

**Comment by xback** [comment]
@cotequeiroz 
I also bumped it independently over [here](https://git.openwrt.org/?p=openwrt/staging/xback.git;a=summary)
Feel free to compare :-)

**Comment by cotequeiroz** [comment]
I missed a declaration of struct `wpa_info` inside src/ap/ubus.h to avoid a warning, so I'm updating the main commit.
I'm also adding a commit to remove 050-build_fix.patch.  It is a legit fix, but for a combination of options that we are not using in OpenWrt.  We might as well stop maintaining an unused patch.
The last commit adjusts the patches to be more easily used with git am/git format-patch, without interfering with quilt.

**Comment by dhewg** [comment]
Seems to work for me so far, tested on ipq40xx/ath10k, ramips/mt7621 and mediatek/filogic including mesh and wds

**Comment by Gingernut1978** [comment]
Testing without issues on mediatek/mt7986, mediatek/mt7622, ramips/mt7621 & ipq40xx/ath10k.

Thx

**Comment by danpawlik** [comment]
After one day, I don't see any issue on mt7988 (with mt7921) and mt7622.

**Comment by robimarko** [comment]
Think this is ready to get out of draft status?

**Comment by cotequeiroz** [comment]
Sure.

**Comment by cmonroe** [comment]
I've been testing this pretty heavily on MT7915 and MT7986 with a lot of 4mac backhaul and don't see any major issues. Two minor things to note:
1. Due to hostapd commit [ada9083a](https://w1.fi/cgit/hostap/commit/?id=ada9083ac4a13e87e0cb3847158f0c9c0a66d0e5), he_6ghz_reg_pwr_type defaults to VLP (Very Low Power) mode. I'm guessing most OpenWrt APs will instead be Indoor APs. Before I changed he_6ghz_reg_pwr_type to Indoor AP my 6GHz radio wouldn't start at all.. I don't quite understand why this is and can dig a bit deeper for a cause if helpful. This option can be set from the config so perhaps it's better to take care of this via config change.
2. I'm also testing with EHT support enabled in hostapd.. in this case I end up with the compile error below due to sta_info.sh being included via ubus.h. I can open a separate PR with a fix for this but figured I'd mention it here in case it might cause any other issues.

```
In file included from /sandbox/cmonroe/smartos/polecat/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-openssl/hostapd-2024-02-03-8270afcd/src/ap/ubus.h:11,
                 from /sandbox/cmonroe/smartos/polecat/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-openssl/hostapd-2024-02-03-8270afcd/src/ap/hostapd.h:21,
                 from main.c:26:
/sandbox/cmonroe/smartos/polecat/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-openssl/hostapd-2024-02-03-8270afcd/src/ap/sta_info.h: In function 'ap_sta_is_mld':
/sandbox/cmonroe/smartos/polecat/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-openssl/hostapd-2024-02-03-8270afcd/src/ap/sta_info.h:425:20: error: invalid use of undefined type 'struct hostapd_data'
  425 |         return hapd->conf->mld_ap && sta && sta->mld_info.mld_sta;
      |                    ^~
```

This can be solved by moving the sta_info.sh include from src/src/ap/ubus.h to src/src/ap/ucode.c where it is needed.

**Comment by schuettecarsten** [comment]
I get error `daemon.err hostapd: Multiple BSSes specified in BSS-config` with this hostapd version. I also have lots of trouble to bring up a wifi AP that has multiple SSIDs. Restarting wpad service solves this temporarily and shows ` daemon.err hostapd: eloop: could not process SIGINT or SIGTERM in two seconds. Looks like there is a bug that ends up in a busy loop that prevents clean shutdown. Killing program forcefully`. I never saw this before.

**Comment by cotequeiroz** [comment]
I hit the `Multiple BSSes...` error just now.  In my case I was fiddling with configuration, and had an `option network 'iot'` in `/etc/config/wireless` before I had `iot` set up.  After configuring the network and restarting the router, it worked.  I did not try to restart just the wpad service.

**Comment by schuettecarsten** [comment]
> I hit the `Multiple BSSes...` error just now. In my case I was fiddling with configuration, and had an `option network 'iot'` in `/etc/config/wireless` before I had `iot` set up. After configuring the network and restarting the router, it worked. I did not try to restart just the wpad service.

That did not help for me, I just recreated the whole wireless config and after a reboot, it ends up like this:

image

```
Wed Mar  6 22:14:18 2024 daemon.info procd: - init complete -
Wed Mar  6 22:14:18 2024 daemon.notice hostapd: Set new config for phy phy0:
Wed Mar  6 22:14:18 2024 daemon.notice wpa_supplicant[1393]: Set new config for phy phy0
Wed Mar  6 22:14:18 2024 daemon.notice hostapd: Set new config for phy phy1:
Wed Mar  6 22:14:18 2024 daemon.notice wpa_supplicant[1393]: Set new config for phy phy1
Wed Mar  6 22:14:19 2024 daemon.notice netifd: radio0 (2209): command failed: Not supported (-122)
Wed Mar  6 22:16:21 2024 user.notice firewall: Reloading firewall due to ifup of lan (br-lan)
Wed Mar  6 22:16:23 2024 daemon.notice wpa_supplicant[1393]: Set new config for phy phy0
Wed Mar  6 22:16:23 2024 daemon.notice hostapd: Set new config for phy phy0: /var/run/hostapd-phy0.conf
Wed Mar  6 22:16:23 2024 daemon.notice hostapd: Restart interface for phy phy0
Wed Mar  6 22:16:24 2024 daemon.notice hostapd: Configuration file: data: driver=nl80211 logger_syslog=127 logger_syslog_level=2 logger_stdout=127 logger_stdout_level=2 country_code=DE ieee80211d=1 ieee80211h=1 hw_mode=a supported_rates=60 90 120 180 240 360 480 540 basic_rates=60 120 240 beacon_int=100 chanlist=36 tx_queue_data2_burst=2.0 #num_global_macaddr=1 ieee80211n=1 ht_coex=0 ht_capab=[HT40+][LDPC][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][MAX-AMSDU-7935][DSSS_CCK-40] ieee80211ac=1 vht_oper_chwidth=1 vht_oper_centr_freq_seg0_idx=42 vht_capab=[RXLDPC][SHORT-GI-80][TX-STBC-2BY1][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN][RX-STBC-1][MAX-MPDU-11454][MAX-A-MPDU-LEN-EXP7] channel=36  interface=ph0-ap1 bssid=d8:47:32:ad:9a:78 ctrl_interface=/var/run/hostapd ap_isolate=1 bss_load_update_period=60 chan_util_avg_period=600 disassoc_low_ack=1 skip_inactivity_poll=0 preamble=1 wmm_enabled=1 ignore_broadcast_ssid=0 uapsd_advertisement_enabled=1 utf8_ssid=1 multi_ap=0 sae_require_mfp=1 sae_pwe=2 wpa_passphrase=*** wpa_psk_f
Wed Mar  6 22:16:24 2024 daemon.notice wpa_supplicant[1393]: Set new config for phy phy1
Wed Mar  6 22:16:25 2024 kern.warn kernel: [   57.469759] ath10k_pci 0000:00:00.0: pdev param 0 not supported by firmware
Wed Mar  6 22:16:25 2024 kern.info kernel: [   57.495326] br-lan: port 2(ph0-ap1) entered blocking state
Wed Mar  6 22:16:25 2024 kern.info kernel: [   57.501066] br-lan: port 2(ph0-ap1) entered disabled state
Wed Mar  6 22:16:25 2024 kern.info kernel: [   57.506995] device ph0-ap1 entered promiscuous mode
Wed Mar  6 22:16:25 2024 kern.info kernel: [   57.512220] br-lan: port 2(ph0-ap1) entered blocking state
Wed Mar  6 22:16:25 2024 kern.info kernel: [   57.517904] br-lan: port 2(ph0-ap1) entered forwarding state
Wed Mar  6 22:16:25 2024 kern.info kernel: [   57.537773] br-lan: port 2(ph0-ap1) entered disabled state
Wed Mar  6 22:16:25 2024 daemon.notice hostapd: ph0-ap1: interface state UNINITIALIZED->COUNTRY_UPDATE
Wed Mar  6 22:16:25 2024 daemon.notice hostapd: ph0-ap1: interface state COUNTRY_UPDATE->HT_SCAN
Wed Mar  6 22:16:25 2024 daemon.notice hostapd: Set new config for phy phy1: /var/run/hostapd-phy1.conf
Wed Mar  6 22:16:25 2024 daemon.notice hostapd: Restart interface for phy phy1
Wed Mar  6 22:16:25 2024 daemon.notice netifd: Wireless device 'radio0' is now up
Wed Mar  6 22:16:26 2024 kern.info kernel: [   58.799837] IPv6: ADDRCONF(NETDEV_CHANGE): ph0-ap1: link becomes ready
Wed Mar  6 22:16:26 2024 kern.info kernel: [   58.806746] br-lan: port 2(ph0-ap1) entered blocking state
Wed Mar  6 22:16:26 2024 kern.info kernel: [   58.812472] br-lan: port 2(ph0-ap1) entered forwarding state
Wed Mar  6 22:16:26 2024 daemon.notice netifd: Network device 'ph0-ap1' link is up
Wed Mar  6 22:16:26 2024 user.info usteer: Creating local node hostapd.ph0-ap1
Wed Mar  6 22:16:27 2024 daemon.notice hostapd: Configuration file: data: driver=nl80211 logger_syslog=127 logger_syslog_level=2 logger_stdout=127 logger_stdout_level=2 country_code=DE ieee80211d=1 hw_mode=g supported_rates=60 90 120 180 240 360 480 540 basic_rates=60 120 240 beacon_int=100 chanlist=1 #num_global_macaddr=1 ieee80211n=1 ht_coex=0 ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][DSSS_CCK-40] channel=1  interface=ph1-ap0 bssid=d8:47:32:ad:9a:79 ctrl_interface=/var/run/hostapd ap_isolate=1 bss_load_update_period=60 chan_util_avg_period=600 disassoc_low_ack=1 skip_inactivity_poll=0 preamble=1 wmm_enabled=1 ignore_broadcast_ssid=0 uapsd_advertisement_enabled=1 utf8_ssid=1 multi_ap=0 sae_require_mfp=1 sae_pwe=2 wpa_passphrase=*** wpa_psk_file=/var/run/hostapd-ph1-ap0.psk auth_algs=1 wpa=2 wpa_pairwise=CCMP ssid=Dummi bridge=br-lan wds_bridge= snoop_iface=br-lan time_advertisement=2 time_zone=CET-1CEST,M3.5.0,M10.5.0/3 wnm_sleep_mode=1 wnm_sleep_mode_no_keys=1 bss_transition=1 rrm_neighbor_report
Wed Mar  6 22:16:27 2024 kern.info kernel: [   58.913420] br-lan: port 3(ph1-ap0) entered blocking state
Wed Mar  6 22:16:27 2024 kern.info kernel: [   58.919115] br-lan: port 3(ph1-ap0) entered disabled state
Wed Mar  6 22:16:27 2024 kern.info kernel: [   58.925205] device ph1-ap0 entered promiscuous mode
Wed Mar  6 22:16:27 2024 kern.info kernel: [   58.930392] br-lan: port 3(ph1-ap0) entered blocking state
Wed Mar  6 22:16:27 2024 kern.info kernel: [   58.936076] br-lan: port 3(ph1-ap0) entered forwarding state
Wed Mar  6 22:16:27 2024 daemon.notice hostapd: ph1-ap0: interface state UNINITIALIZED->COUNTRY_UPDATE
Wed Mar  6 22:16:27 2024 daemon.notice hostapd: ph1-ap0: interface state COUNTRY_UPDATE->HT_SCAN
Wed Mar  6 22:16:27 2024 daemon.notice hostapd: Configuration file: data: driver=nl80211 logger_syslog=127 logger_syslog_level=2 logger_stdout=127 logger_stdout_level=2 country_code=DE ieee80211d=1 hw_mode=g supported_rates=60 90 120 180 240 360 480 540 basic_rates=60 120 240 beacon_int=100 chanlist=1 #num_global_macaddr=1 ieee80211n=1 ht_coex=0 ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][DSSS_CCK-40] channel=1  interface=ph1-ap0 bssid=d8:47:32:ad:9a:79 ctrl_interface=/var/run/hostapd ap_isolate=1 bss_load_update_period=60 chan_util_avg_period=600 disassoc_low_ack=1 skip_inactivity_poll=0 preamble=1 wmm_enabled=1 ignore_broadcast_ssid=0 uapsd_advertisement_enabled=1 utf8_ssid=1 multi_ap=0 sae_require_mfp=1 sae_pwe=2 wpa_passphrase=*** wpa_psk_file=/var/run/hostapd-ph1-ap0.psk auth_algs=1 wpa=2 wpa_pairwise=CCMP ssid=Dummi bridge=br-lan wds_bridge= snoop_iface=br-lan time_advertisement=2 time_zone=CET-1CEST,M3.5.0,M10.5.0/3 wnm_sleep_mode=1 wnm_sleep_mode_no_keys=1 bss_transition=1 rrm_neighbor_report
Wed Mar  6 22:16:27 2024 daemon.err hostapd: Multiple BSSes specified in BSS-config
Wed Mar  6 22:16:27 2024 daemon.notice hostapd: hostapd.add_iface failed for phy phy1 ifname=ph1-ap0
Wed Mar  6 22:16:27 2024 user.notice firewall: Reloading firewall due to ifup of mgmt (br-mgmt)
Wed Mar  6 22:16:28 2024 kern.info kernel: [   59.869813] br-lan: port 3(ph1-ap0) entered disabled state
Wed Mar  6 22:16:29 2024 user.notice firewall: Reloading firewall due to ifup of guest (br-guest)
Wed Mar  6 22:16:56 2024 daemon.notice netifd: Wireless device 'radio1' is now up
```

**Comment by robimarko** [comment]
I tried using this, but it somehow makes my Dynalink WLAN really slow and randomly loose connection

**Comment by cotequeiroz** [comment]
I started working on a current HEAD update.  There was a change in `hostapd_set_freq_params` to include EHT puncturing bitmap to the channel parameters.  This broke compilation because `hostapd_switch_chan` in ubus.c was calling that function.  I'm still not 100% sure what should be used in this case (I will try to pass `hostapd_get_punct_bitmap(hapd)` as done elsewhere in code); I don't think it would matter to our current usage, but it could affect 802.11be.  I don't have anything with EHT to test it.   While at it I noticed another possible problem with EHT in the same function, because the `link_id` parameter is not being set, unlike what's done in the rest of the code when switching channels.  Time has been short for this, so I may take a while.

**Comment by AgustinLorenzo** [comment]
Hi @cotequeiroz 

I picked your commit for my build of AX3600 with NSS offloading and at the moment is working well.

Thanks for your job :)

Regards, Agustin

**Comment by robimarko** [comment]
@cotequeiroz Deploying on my AP.

BTW, if this updates it to current hostapd head, then both commit and description need to be updated

**Comment by cotequeiroz** [comment]
I have amended the PR description to reflect the change.  I made a second commit to update it further than the original one, to make it easier to find out if something got broken or fixed between them.  I can squash them if this is close to being merged--or immediately if you think keeping 2 commits is unnecessary.

The second commit does point out it is the current HEAD, although I did not record any additional changes.

**Comment by schuettecarsten** [comment]
Patch needs to be rebased as it conflicts with latest changes in main branch:
Merge conflict in package/network/services/hostapd/Makefile

**Comment by cotequeiroz** [comment]
I've rebased it, and reworded the last commit.  I don't anticipate changes, but I must mention the fact that I haven't even compile tested it after the apk version adjustment.

**Comment by cotequeiroz** [comment]
I have rebased it again after bf4c04a4d08376bb611a748a102dbf974d089336, and compile-tested it.  Previous version did build locally, as my build dir is not as long as the Ci or the buildbots'.

**Comment by robimarko** [comment]
This works for me, would be ideal to get some tested-bys

**Comment by K900** [comment]
Been running it here on my AX6S for a while with no issues.

**Comment by cotequeiroz** [comment]
> This works for me, would be ideal to get some tested-bys

I think there's no point in keeping both update commits (going to 2024-02-03 and then to 2024-03-09), so I squashed them.  If you want to have them separate, then I'll undo this.



> Been running it here on my AX6S for a while with no issues.

Can I add a "Tested-by" line?  It needs your name and e-mail, such as:
```
Tested-by: Eneas U de Queiroz <cotequeiroz@gmail.com>
```

**Comment by K900** [comment]
`Tested-by: Ilya Katsnelson <me@0upti.me>`

**Comment by Gingernut1978** [comment]
Running this, on varios different targets, for weeks without issues.

```Tested by: Andrew Sim <andrewsimz@gmail.com>

Thank you

**Comment by nbd168** [comment]
Merged, thanks.

**Comment by Neustradamus** [comment]
@cotequeiroz, @PolynomialDivision, @blocktrron, @dhewg: There is now an official build: 2.11 (2024-06-20) that I have requested:
- https://lists.infradead.org/pipermail/hostap/2024-July/042847.html

It is possible to update?

History:
- https://github.com/openwrt/openwrt/pull/12178
- https://github.com/openwrt/openwrt/pull/13064
- https://github.com/openwrt/openwrt/pull/13911
- https://github.com/openwrt/openwrt/pull/14620

**Comment by AuthorReflex** [comment]
> @cotequeiroz, @PolynomialDivision, @blocktrron, @dhewg: There is now an official build: 2.11 (2024-06-20) that I have requested:
> 
> * https://lists.infradead.org/pipermail/hostap/2024-July/042847.html
> 
> It is possible to update?
> 
> History:
> 
> * [hostapd: update to 2023-03-29 #12178](https://github.com/openwrt/openwrt/pull/12178)
> * [hostapd: update to 2023-06-22 #13064](https://github.com/openwrt/openwrt/pull/13064)
> * [hostapd: update to latest HEAD #13911](https://github.com/openwrt/openwrt/pull/13911)
> * [hostapd: bump to 2024-03-09 #14620](https://github.com/openwrt/openwrt/pull/14620)

https://github.com/openwrt/openwrt/pull/16338

**Pull request closed without merging**
