### PR TITLE
kernel: replace GCC11_NO_ARRAY_BOUNDS with GCC10_NO_ARRAY_BOUNDS

### PR DESCRIPTION
**Pull request by namiltd**
According to https://lore.kernel.org/lkml/20240223170824.work.768-kees@kernel.org/raw 
GCC11_NO_ARRAY_BOUNDS has been replaced by GCC10_NO_ARRAY_BOUNDS 
so replace GCC11_NO_ARRAY_BOUNDS setting with GCC10_NO_ARRAY_BOUNDS.

### CODE REVIEW

**Comment by robimarko** [comment]
This should probably be filtered out from the config as its dynamically set

**Comment by namiltd** [comment]
The same result is obtained by "make kernel_oldconfig" for subsequent targets

**Comment by robimarko** [comment]
Hence why it should be removed from the configs and filtered out so it doesn't get added back since its dynamically added by the kernel based on GCC version so it makes no sense for us to carry it

**Comment by namiltd** [comment]
I think this also applies to CC_NO_ARRAY_BOUNDS

**Comment by robimarko** [comment]
Yes, that is right

**Comment by namiltd** [comment]
Can you create a PR that removes GCC11_NO_ARRAY_BOUNDS, GCC10_NO_ARRAY_BOUNDS and CC_NO_ARRAY_BOUNDS, with proper description?

**Comment by robimarko** [comment]
Sure, I will try to squeeze it over the weekend

**Comment by namiltd** [comment]
@robiemarko Please take a look at https://github.com/openwrt/openwrt/pull/16990 and possibly correct the description.

**Pull request closed without merging**
