### PR TITLE
iptables: bump to 1.8.2

### PR DESCRIPTION
**Pull request by Ansuel**
Drop 030-extensions-libxt_bpf-Fix-build-with-old-kernel-versi.patch Pushed Upstream
Added
010-extensions_format-security_fixes_in_libip.patch
010-include_fix_build_with_kernel_headers_before_4_2.patch
010-remove-register-check.patch

The first and the second patch are upsteam fix for some compilation error.
The third patch remove check if one target lib is already registred. This is caused by shared libs that are loaded before the iptables execution.

Compiled and tested r7800 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
This looks like a rather large bump. Whats the size increase of the resulting binaries?

**Comment by Ansuel** [comment]
@jow- 

1.8.2
70885 /usr/sbin/xtables-legacy-multi
20746 /usr/lib/libip4tc.so.0.1.0
24842 /usr/lib/libip6tc.so.0.1.0
29478 Nov 22 16:30 /usr/lib/libiptext4.so
25382 Nov 22 16:30 /usr/lib/libiptext6.so

1.6.2
70885 xtables-multi
20746 libip4tc.so.0.1.0
24842 libip6tc.so.0.1.0
25278 Nov 17 16:27 libiptext4.so
25278 Nov 17 16:27 libiptext4.so

**Comment by escalade** [comment]
Fails to build with glibc:

```
arm-openwrt-linux-gnueabi-gcc -D_LARGEFILE_SOURCE=1 -D_LARGE_FILES -D_FILE_OFFSET_BITS=64 -D_REENTRANT 	-DXTABLES_LIBDIR=\"/usr/lib/iptables\" -DXTABLES_INTERNAL -I../include -I.. -I../include -I.. -I/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/linux-4.14.82/user_headers/include/uapi -I/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/linux-4.14.82/user_headers/include -I/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/linux-4.14.82/user_headers/include/uapi -I/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/linux-4.14.82/user_headers/include -I/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/iptables-1.8.2/include -I/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/linux-4.14.82/user_headers/include -I/media/MyBook/openwrt/staging_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/usr/include -I/media/MyBook/openwrt/staging_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/include -I/media/MyBook/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.2.0_glibc_eabi/usr/include -I/media/MyBook/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.2.0_glibc_eabi/include    -Wp,-MMD,./.libxt_mac.o.d,-MT,libxt_mac.o -Wall -Waggregate-return -Wmissing-declarations 	-Wmissing-prototypes -Wredundant-decls -Wshadow -Wstrict-prototypes 	-Wlogical-op 	-Winline -pipe -DNO_SHARED_LIBS=1 -D_INIT=libxt_mac_init -DPIC -fPIC -O2 -pipe -march=armv7-a+neon-vfpv4 -mtune=cortex-a15 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/iptables-1.8.2=iptables-1.8.2 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/iptables-1.8.2/include -I/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/linux-4.14.82/user_headers/include -ffunction-sections -fdata-sections -DNO_LEGACY  -o libxt_mac.o -c libxt_mac.c;
In file included from ../include/xtables.h:15,
                 from libxt_mac.c:7:
/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/linux-4.14.82/user_headers/include/linux/in.h:29:3: error: redeclaration of enumerator 'IPPROTO_IP'
   IPPROTO_IP = 0,  /* Dummy protocol for TCP  */
   ^~~~~~~~~~
/media/MyBook/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.2.0_glibc_eabi/include/netinet/in.h:42:5: note: previous definition of 'IPPROTO_IP' was here
     IPPROTO_IP = 0,    /* Dummy protocol for TCP.  */
     ^~~~~~~~~~
/media/MyBook/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/linux-ipq806x/linux-4.14.82/user_headers/include/linux/in.h:31:3: error: redeclaration of enumerator 'IPPROTO_ICMP'
   IPPROTO_ICMP = 1,  /* Internet Control Message Protocol */
   ^~~~~~~~~~~~
/media/MyBook/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-8.2.0_glibc_eabi/include/netinet/in.h:44:5: note: previous definition of 'IPPROTO_ICMP' was here
     IPPROTO_ICMP = 1,    /* Internet Control Message Protocol.  */
     ^~~~~~~~~~~~
```

**Comment by escalade** [comment]
The answer is probably here somewhere: https://bugzilla.redhat.com/show_bug.cgi?id=1300256

**Comment by Ansuel** [comment]
@escalade strange you have a kernel before 4.2 ? 

anyway will include patch wait a sec and try the new commit

**Comment by escalade** [comment]
No, this is on master with kernel 4.14.82. I think the old fix is not relevant, just posted that as a referance to why this is happening. Rolling back this PR lets iptables build fine with glibc.

**Comment by Ansuel** [comment]
@escalade can you try this pr with the new patch?

**Comment by Ansuel** [comment]
sorry try this... pushed patch with .txt extension... (thx windows -.-)

**Comment by escalade** [comment]
It compiles fine if you put the #endif after including in6.h. No idea if it's a proper fix, but it compiles so I'll give it a spin :)

**Comment by Ansuel** [comment]
@escalade so with that patch you have the same error? or it does refer to if6?

**Comment by escalade** [comment]
I had a different error regarding ipv6. As mentioned, putting #endif after in6.h solves it and builds clean.

**Comment by Ansuel** [comment]
test if it does work...  can you post here the error so i can report to iptables team?

**Comment by escalade** [comment]
It's working fine :)

**Comment by diizzyy** [comment]
```
Current version:
18439 ./bin/targets/ar71xx/generic/packages/libip4tc_1.6.2-3_mips_24kc.ipk
18411 ./bin/targets/ar71xx/generic/packages/libip6tc_1.6.2-3_mips_24kc.ipk

Updated version:
19180 ./bin/targets/ar71xx/generic/packages/libip4tc_1.8.2-1_mips_24kc.ipk
19318 ./bin/targets/ar71xx/generic/packages/libip6tc_1.8.2-1_mips_24kc.ipk
```
Disabling MIPS16 makes the packages about 1kbyte larger, -flto fails to compile (didn't look too much at it).

**Comment by Ansuel** [comment]
it it too much? i mean openwrt now require a lager flash so this is not a problem right?
@diizzyy

**Comment by diizzyy** [comment]
Compile tested: ar71xx, ramips
Runtime tested: ramips, WiTi board, OpenWrt master

**Comment by Ansuel** [comment]
any update on this?

**Comment by dedeckeh** [comment]
@Ansuel Can you sure the newly added patches have distinct patch numbers? Backported commits can start with 001- as they can be removed with the next update

**Comment by Ansuel** [comment]
@dedeckeh should i follow the patch legend of the kernel? Can you provide me one so i can apply the right number to the patch?

**Comment by dedeckeh** [comment]
@Ansuel For the kernel we use 0xx for backported upstream commits; hence I would start with 001 for the backported commits

**Comment by Ansuel** [comment]
and for the custom patches?

**Comment by dedeckeh** [comment]
For,packages we don't have a clear policy but I would propose to keep the custom patches out of the 0xx range

**Comment by Ansuel** [comment]
@dedeckeh  now should be good

**Comment by dedeckeh** [comment]
Patch pushed to my staging tree (https://git.openwrt.org/?p=openwrt/staging/dedeckeh.git;a=commit;h=ea8fb9041d7a232ac6de04e5160e31f8a8bc3ad4); thx

**Comment by cshoredaniel** [comment]
Breaks ath79 (see [FS#1990](https://bugs.openwrt.org/index.php?do=details&task_id=1990)

```  CC       libebt_vlan.oo
In file included from /home/daniel/Build/openwrt-ath79/staging_dir/toolchain-mips_24kc_gcc-7.3.0_musl/include/net/ethernet.h:10:0,
                 from ../iptables/nft-bridge.h:8,
                 from libebt_vlan.c:18:
/home/daniel/Build/openwrt-ath79/staging_dir/toolchain-mips_24kc_gcc-7.3.0_musl/include/netinet/if_ether.h:111:8: error: redefinition of 'struct ethhdr'
 struct ethhdr {
        ^~~~~~
In file included from libebt_vlan.c:16:0:
/home/daniel/Build/openwrt-ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.14.82/user_headers/include/linux/if_ether.h:155:8: note: originally defined here
 struct ethhdr {
        ^~~~~~
make[6]: *** [GNUmakefile:127: libebt_vlan.oo] Error 1
make[6]: Leaving directory '/home/daniel/Build/openwrt-ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/iptables-1.8.2/extensions'
make[5]: *** [Makefile:506: all-recursive] Error 1
```

**Comment by Ansuel** [comment]
seems related to source problem and not ath79

**Comment by Ansuel** [comment]
@cshoredaniel will add a patch as this ssems to be the same problem... just wait the pr

http://git.netfilter.org/iptables/commit/?id=51d374ba41ae4f1bb851228c06b030b83dd2092f

**Comment by Ansuel** [comment]
here https://github.com/openwrt/openwrt/pull/1612

**Pull request closed without merging**
