### PR TITLE
kernel: add missing symbol

### PR DESCRIPTION
**Pull request by neheb**
Should fix qoriq compilation.

### CODE REVIEW

**Comment by innovara** [comment]
Is that not fixed already on https://github.com/openwrt/openwrt/commit/1bd6dda198eb44f6f34f3646c628dc248e5699fe?

**Comment by hauke** [comment]
Fix in 1bd6dda198eb44f6f34f3646c628dc248e5699fe.

**Comment by stintel** [comment]
@hauke @neheb suggested on IRC that this should go in generic/config-6.6 instead. Since there are other PPC targets, this might indeed be the better place. WDYT?

**Comment by neheb** [comment]
@stintel got this on mpc85xx p1020 as well

```
Open Firmware display driver (DRM_OFDRM) [N/m/?] (NEW) 
```

**Comment by hauke** [comment]
@stintel Yes I also think generic would be the better place. 
@neheb  you can reopen this PR and add it to generic and remove it from qoriq

**Pull request closed without merging**
