### PR TITLE
comfast: match brand name across supported devices

### PR DESCRIPTION
**Pull request by LuKePicci**
Match COMFAST brand name across all supported devices.

Signed-off-by: Luca Piccirillo <luca.piccirillo@gmail.com>

### CODE REVIEW

**Comment by LuKePicci** [comment]
@dangowrt could you help getting this reviewed?

**Review by GoetzGoerisch — APPROVED** [review]
LGTM
Please fix your author firstname lastname to match your SoB.

**Comment by LuKePicci** [comment]
Thanks @GoetzGoerisch, should be fixed now

**Comment by LuKePicci** [comment]
@GoetzGoerisch automatic checks green now. 👍

**Pull request merged**
