### PR TITLE
mediatek: filogic: typo fixes and reorder alphabetically 

### PR DESCRIPTION
**Pull request by aiamadeus**
Reorder scripts and image recipes to keep alphabetical order.

### CODE REVIEW

**Review by ptpt52 — APPROVED** [review]

**Review by raenye — APPROVED** [review]
LGTM

**Comment by Ansuel** [comment]
@aiamadeus should we backport commit 1 and 2 ?

**Comment by aiamadeus** [comment]
> should we backport commit 1 and 2 ?

These devices only exist on the main branch, so they are not needed.

**Comment by aiamadeus** [comment]
> should we backport commit 1 and 2 ?

Looks like we should backport commit 1 now.

**Pull request merged**
