### PR TITLE
mediatek ramips: add support for Asus RT-N600

### PR DESCRIPTION
**Pull request by russinnes**
The ASUS RT-N600 Wireless Router is based on the MT7628AN SoC.

- CPU: MediaTek MT7628AN @580MHz WiSoC (2T2R 802.11bgn)
- WLAN: MediaTek MT7612EN (2T2R 802.11an -> 802.11an/ac)
- RAM: 64MB (DDR2), Flash 16MB (SPI, 16-pin)
- USB 2.0
- LED (ETHx4, WLANx2, USB, Power)
- PORTS: 4x 100M RJ45 LAN, 1x 100M WAN

Initial Flashing:

- Download the "Asus Firmware Recovery Tool" from the Asus website
- Set a static IP of 192.168.1.10 on a wired connection (Netmask 255.255.255.0)
- Load the desired firmware file in the recovery tool (.bin, .trx, etc)
- Power on the device while holding the reset button (Power LED will begin flashing when ready)
- Update the firmware (recovery) in the software

* Known Issues *: All LED's work and are configurable with the exception of the 5g WLAN LED. 

Signed-off-by: Russ Innes russ.innes@gmail.com

### CODE REVIEW

**Comment by therealsummoner** [comment]
Does the device have a modem built-in?

**Comment by therealsummoner** [comment]
The 5G LED control is here then surely similarly different, like for the RT-AC1200-V2.
You can try and edit my PR for that here: https://github.com/openwrt/mt76/pull/651
Ofc you'll then need to compare the registers, what the OEM does there with, so this can be a good start.

**Comment by russinnes** [comment]
> Does the device have a modem built-in?

Good catch, got too focused on the LEDs. Updated.

**Comment by russinnes** [comment]
> The 5G LED control is here then surely similarly different, like for the RT-AC1200-V2. You can try and edit my PR for that here: [openwrt/mt76#651](https://github.com/openwrt/mt76/pull/651) Ofc you'll then need to compare the registers, what the OEM does there with, so this can be a good start.

> The 5G LED control is here then surely similarly different, like for the RT-AC1200-V2. You can try and edit my PR for that here: [openwrt/mt76#651](https://github.com/openwrt/mt76/pull/651) Ofc you'll then need to compare the registers, what the OEM does there with, so this can be a good start.

Yes, I spent many hours on that single LED. I wish I would have seen your pr ahead of all of that prior to excavating the Asus firmware. I'll come back to it with fresh eyes at a later date.

**Comment by therealsummoner** [comment]
Have to remove uqmi as well, that is also modem stuff and squash all the commits into a single one

**Comment by russinnes** [comment]
I tried to squash them when merging to :master at my end, perhaps Ill just close this for good and start a new PR from my master.

**Comment by russinnes** [comment]
> Have to remove uqmi as well, that is also modem stuff and squash all the commits into a single one

Created a new PR with all changes.

**Pull request closed without merging**
