### PR TITLE
mwlwifi: Update the 88W8964's firmware to 9.3.2.12

### PR DESCRIPTION
**Pull request by jeolives**
Updates the 88W8964 firmware used in the Linksys WRT3200ACM and WRT32X
[v9.3.2.6 -> v9.3.2.12]

Removes 0c43219 ("mwlwifi: Fix loading with backports v5.3")
as it has been merged upstream.

Unfortunately, there is a bug wherein Kaloz's repo, the version
detection mechanism for fixing vendor commands doesn't work.

It pulls in the Linux kernel version, which as of this time is
"4.14.y" or "4.19.y"

However, the proper behaviour is that it should pull in the mac80211
backports version which as of now is "5.4-rc8"

The included patch works around this by removing the version check.

Signed-off-by: Jose Olivera <oliverajeo@gmail.com>

### CODE REVIEW

**Comment by tapper82** [comment]
Run tested on WRT3200acm

**Comment by 1Jeff1** [comment]
On the WRT32X mwlwifi driver is not  loading .
https://gist.github.com/1Jeff1/7c73650098507230481f65f758bc7456

**Comment by tapper82** [comment]
Could it be the removal of the patch?

**Comment by tapper82** [comment]
Does this work for you @diizzyy

**Comment by 1Jeff1** [comment]
> Could it be the removal of the patch?

@tapper82  yes is the patch added in kaloz repo https://github.com/kaloz/mwlwifi/commit/bb27b319c94dce7f2ff177ec3cdbb2c63bafc060
removing lines 95,97,104 and 106 fix it.

**Comment by jeolives** [comment]
The commit linked by @1Jeff1 is the issue. It pulls the kernel version (which is either 4.14 or 4.19). However, it needs to pull the backports version in the called by `package/mac80211/Makefile` (currently at 5.4-rc8).

**Comment by jeolives** [comment]
I've fixed the error reported by removing the lines @1Jeff1 talked about. However, a much better fix would be finding out how one can pull the kernel version the "mac80211" backports package is based off of. For now this should do.

**Comment by diizzyy** [comment]
@tapper82 
No idea, haven't tested it.

**Comment by jeolives** [comment]
This PR will be updated when @dengqf6's [PR](https://github.com/kaloz/mwlwifi/pull/381) gets merged by @kaloz

**Comment by jeolives** [comment]
Will create a new PR as I need to rebase the branch.

**Comment by adrianschmutzler** [comment]
There is no reason to create a new PR just because you need to rebase. Just rebase and then force-push to GitHub again.

Creating new PRs just because of a rebase is merely annoying all other people, as all discussion and history is missing there.

**Comment by giro83** [comment]
Why isn't the new firmware in 19.07.3? :(

root@OpenWrt:~# opkg list-installed | grep mwlwifi-firmware
mwlwifi-firmware-88w8964 - 2019-03-02-31d93860-1

root@OpenWrt:~# dmesg | grep firmware | grep phy
[   11.599001] ieee80211 phy0: firmware version: 0x9030206
[   11.905992] ieee80211 phy0: firmware region code: 30
[   13.343088] ieee80211 phy1: firmware version: 0x9030206
[   13.649980] ieee80211 phy1: firmware region code: 30

**Comment by nicolaerosia** [comment]
same situation in 19.07.5
```
root@OpenWrt:~# dmesg | grep firmware | grep phy
[   10.652993] ieee80211 phy0: firmware version: 0x9030206
[   10.959903] ieee80211 phy0: firmware region code: 30
[   12.388927] ieee80211 phy1: firmware version: 0x9030206
[   12.695917] ieee80211 phy1: firmware region code: 30
```

**Comment by anomeome** [comment]
Simple enough to set it up with a [soft link](https://forum.openwrt.org/t/new-official-firmware-wrt3200-acm/54313/51?u=anomeome), but it's pretty much a nothingburger.

**Pull request closed without merging**
