### PR TITLE
[RFC] TPLink CPE210/510 re-balance flash split ratio between kernel & rootfs

### PR DESCRIPTION
**Pull request by thuehn**
Kernel & RootFS in sum can occupy ~8MByte on those devices. The split ratio is
fixed (would be cool to have it dynamically shared as firmare with okli driver somehow).
The former kernel_vs_rootfs split ratio (from good old ar71xx times) was:
 2MB kernel & 6 MB rootfs
That ratio had to be changed as the kernel size increased above 2MB at the point in time
when we switched to the ath79 target and kernel 5.4. The actual re-ratio_ing commit d7fb7ac27849b 
increased the kernel max size by 1MB hence decreased the rootfs size by 1MB.
With this patch, we argue that a reduced rootfs size from 6MB to 5MB makes it a hard task
to create e.g. a Freifunk mesh node with luci web interface & routing running. This patch increases the
kernel size by only 256kByte and hence reduces the rootfs by this 256kByte.

Signed-off-by: Thomas Huehn <thomas.huehn@hs-nordhausen.de>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by adschm** [comment]
> The split ratio is
fixed (would be cool to have it dynamically shared as firmare with okli driver somehow).

If I remember correctly, somebody has sent a patchset/open a PR for that? @svenheule was that you?

> The actual re-ratio_ing commit d7fb7ac
increased the kernel max size by 1MB hence decreased the rootfs size by 1MB.
> With this patch, we argue that a reduced rootfs size from 6MB to 5MB makes it a hard task
to create e.g. a Freifunk mesh node with luci web interface & routing running. This patch increases the
kernel size by only 256kByte and hence reduces the rootfs by this 256kByte.

I increased by 1 MiB intentionally, since I do not see a point in adjusting this every half year; this is meant to serve for 1 or 2 years. If 4.5 MiB rootfs really limits you that much, maybe you are on the wrong platform?

**Comment by svanheule** [comment]
I did indeed send [a patch](https://patchwork.ozlabs.org/project/openwrt/patch/20200927135933.419394-1-sander@svanheule.net/) to the mailing list a few weeks ago.

A rebased version of that patch can now be found at https://github.com/svanheule/openwrt/tree/tplink_cpe_elfloader, feel free to give it a try. Make sure you have a means of recovery, because I didn't (and can't) run-test that patch.

**Comment by thuehn** [comment]
hiho,

I just had the time to test your tplink_cpe_elfloader patch on a fresh compiled trunk for CPE510 v3.
Compiles without errors with my kernel > 2MB and the image boots up & works as intended.
So will test your patch on the CPE510v1 & CPE510v2 that we have running in our mesh as well and report back.

I am in favor of your approach and it looks promising.

Greetings Thomas

**Comment by thuehn** [comment]
back  from testing ... I've just compile an image for target CPE510v2 with the same settings ... image does compile, but does stuck in a boot loop:

`TP-LINK SafeLoader (Build time: Jun 12 2015 - 09:49:53)
CPU: 560MHz AHB: 225MHz DDR: 64MB
Performing LED check..  PASS
Press CTRL+B to enter SafeLoader: 1
Flash Manufacturer: Unknown(0xc8)
Flash Device ID: Unknown(0x4017)
Data flash init failed.
open user-config failed.
open user-config failed.
Allocated memory for elf segment ok: addr: 0x80060000, size 0x1eb701

Starting kernel
`

Any hint ?

Greetings Thomas

**Comment by thuehn** [comment]
Any try to get the CPE510v2 booting an image via tftp recovery does not work. The Openwrt trunk stock image does not boot eather:

```
TP-LINK SafeLoader (Build time: Jun 12 2015 - 09:49:53)
CPU: 560MHz AHB: 225MHz DDR: 64MB
Performing LED check..  PASS
Press CTRL+B to enter SafeLoader: 1
Flash Manufacturer: Unknown(0xc8)
Flash Device ID: Unknown(0x4017)
Data flash init failed.
open user-config failed.
open user-config failed.

enet0 port4 up

TFTP server address is 192.168.0.100; our address is 192.168.0.254
Get filename 'recovery.bin'.
#################################################################
##############################
Done.
Bytes transferred = 4846640, 403 Kbytes/sec
Incorrect File.
Writting error.
Allocated memory for elf segment ok: addr: 0x80060000, size 0x1eb701
```

Looks a bit like the bootloadergot broken and I would need a hw flasher ... hmmm

Greetings Thomas

**Comment by svanheule** [comment]
As discussed [on the mailing list](http://lists.openwrt.org/pipermail/openwrt-devel/2020-August/031146.html), the OpenWrt partition layout is slightly different from the stock layout. This means OpenWrt will erase the soft-version and support-list partitions to gain 64kB of storage space (not really worth it IMO). As I understand is, the problem could be that the safeloader images are verified against the metadata in these two partitions. Since this data was erased, any checks will now fail, causing the bootloader to fail flashing stock/factory images.

**Comment by mpratt14** [comment]
is there anything stopping us from implementing OKLI instead?

**Comment by svanheule** [comment]
mtdsplit doesn't support okli images (uimage with custom magic bytes) immediately after the loader, in the same partition.

OKLI was mainly designed to be put in a (small) kernel partition, with the actual kernel being relocated to the (larger) file system partition, so it's not really the best choice here. I originally used it for my EAP245 port, but that required a big patch for the uimage splitter. That's why I switched to kernel-loader there.

The best solution, in my opinion, would be to switch to zBoot, as was recently done for Mikrotik devices. But someone else will have to weigh in, because it might not be possible within the current ath79/generic target.

**Comment by adschm** [comment]
And, eventually, the question would be whether it's worth it, because everything works fine here so far and the problem is "just" not enough space on rootfs for a limited time.

**Comment by mpratt14** [comment]
@svanheule isn't the patch you're thinking of in master now? or am I mistaken?
https://github.com/openwrt/openwrt/commit/90c248c80ad1b763a645e941d3fb7dc6bb3a150f

Adrian put together this common makefile definition after my first PR for Engenius boards (all AR7 or AR9 based boards need it). The implementation here would be similar, but with a custom sysupgrade.bin as well, and other adjustments...Instead of handling the loader in another custom definition, it would be the first thing in factory.bin and sysupgrade.bin
https://github.com/openwrt/openwrt/blob/master/target/linux/ath79/image/generic.mk#L851

As far as I understand, partitioning doesn't matter, as long as everything starts on an eraseblock...so if everyone is ok with wasting only 1 block it's something to consider...

**Comment by svanheule** [comment]
The solution used for the Engenius board works because the uImage placed at the next erase block boundary. So it would also work here, and indeed only at the cost of 1 EB. It would also work around any size limitation that may (or may not) be present in the bootloader.

What I meant with "immediately after the loader", is having the loader and start of the uImage in the same erase block. That wouldn't work since the current mtd-splitter only checks the start of an erase block (which is where the loader would be).

A zBoot solution would be interesting in that it only uses upstream machinery to create a self-extracting kernel.

**Comment by thuehn** [comment]
Hi,

As I do have 3 testing devices: TPLink CPE510 v1, v2 and v3 around I do struggle with the recovery process in such a case I faced on the last flash attempt to a CPE510 v2 with the patch from svanheule that the bootloader does not work anymore. We do not have yet a proper hw flashed setup to have this last mile recovery working.

**Comment by apcameron** [comment]
I suggest you look at what @NeoRaider recommended on PR#1704 where he said "Well, the commit message of 0c0bb62 basically explains the situation. Old OpenWrt installations with a too small kernel partition ("os-image") in the TP-Link partition table exist in the field, so the bootloader would fail to load the whole compressed kernel into the RAM. The OKLI loader is a workaround for this: The TP-Link bootloader only loads the tiny OKLI loader, and the OKLI loader will then read the actual kernel from the flash.
While this is only an issue for old installations, and installing a new OpenWrt factory image from the stock firmware will result in a "fixed" partition layout (with bigger os-image), 1. we can't easily upgrade old devices (as explained in the referenced commit message, such an upgrade would need to happen before sysupgrade), and 2. the OKLI loader solution is more robust in case we ever need to increase kernel partition size again. Therefore, I would propose to keep the OKLI loader for ath79 as well"

I have tried the MD Splitter approach but it did not work on these devices.

**Comment by thuehn** [comment]
ok, the situation is suboptimal for updating our ~60 CPE510s mesh nodes, where some date back to an installation in 2016. There update lifecycle can not stop on ath79 ;) .. so my pragmatic approach for the time been is to revert (https://github.com/openwrt/openwrt/commit/d7fb7ac27849b8e1c1dcb17bac2472a2521fe946) and aim at a tight max 2MB kernel image. Ok I will try that.

**Comment by adschm** [comment]
> ok, the situation is suboptimal for updating our ~60 CPE510s mesh nodes, where some date back to an installation in 2016. There update lifecycle can not stop on ath79 ;) .. so my pragmatic approach for the time been is to revert ([d7fb7ac](https://github.com/openwrt/openwrt/commit/d7fb7ac27849b8e1c1dcb17bac2472a2521fe946)) and aim at a tight max 2MB kernel image. Ok I will try that.

IMO, you should rather try to reduce your excessive use of space on rootfs. The kernel will grow further, so everything you invest into getting it smaller will be in vain once we have seen one or two further kernel updates (or stable releases). If you manage to drop unneeded stuff from rootfs, though, your work will have a longer half-life period.

**Comment by thuehn** [comment]
Hi Adrian,
Is't there more to consider at the current stage when migrating from ar71xx to ath79 on CPE510 ?
AFAI read (https://github.com/openwrt/openwrt/commit/0c0bb629992d3cc2fe277a2348e8cf70fa429567) the partition table should be changed in order to update the bootloader on older OpenWrt installations and hence be able to boot kernels > 2MB. But I don not know how to do this over-the-air in a safe manner. So in the current state I would need to have a kernel < 2MB anyway or flash each node localy by tftp with a factory image and re-apply its configuration ... any alternative suggestions ?
So for our old CPE510 OpenWrt installations, the use of https://github.com/openwrt/openwrt/commit/d7fb7ac27849b8e1c1dcb17bac2472a2521fe946 would force a 1MB smaller rootfs and the running partition table would force a kernel < 2MB ... so not-the-best from two worlds ;)
But there is a bigger showstopper ... I've build a trunk image for CPE510 v1 yesterday, got the kernel in < 2MB bounds and ... Ethernet is broken, not packet reception ... tested an image from Downloads as well ... same problem... the dts setup for the switch seems to be wrong on the 2-port CPE510v1 .. I will open a ticket with my findings / troubleshooting.

**Comment by adschm** [comment]
I was under the impression that this situation is exactly what the okli loader was introduced for. If your rootfs is too big already, though, you might get problems. However, note that we would have a kernel increase in master in any case, the question is just how big it would be. My intention was actually to make sure we have such events less often, and not with every kernel bump if we increase in smaller steps.

I haven't checked whether ethernet setup changes from ar71xx to ath79, that might be the case ... Will check that later.

**Comment by svanheule** [comment]
As far as I can tell, using an OKLI setup as @mpratt14 suggested, would solve the issues here, no? You would have a small loader that will never exceed the original kernel size (solves the bootloader issue), and a firmware partition with a dynamic kernel/rootfs split.

**Comment by adschm** [comment]
Indeed, network setup changed:

ar71xx:
```
		ucidef_add_switch "switch0" \
			"0@eth0" "5:lan" "4:wan"
		;;
```

ath79:
```
		ucidef_set_interfaces_lan_wan "eth1" "eth0"
```

So, if you just keep your /etc/config/network when upgrading from ar71xx to ath79, you might have problems apart from the upgrade process itself (and thus, this is actually off-topic for this PR).

**Comment by mpratt14** [comment]
> For the Engenius, a 1 EB sized "loader" partition is present, which I'm guessing is located at the start of the original kernel partition? I don't quite understand all the things going on in the image building for that device, but is seems quite complicated and I'm not sure sysupgrades could be done without modifying other parts of the code.

Right, this is a detail I forgot...

Yes, your understanding of the Engenius build is correct...

sysupgrades are possible in any case, however if the uImage is not at the beginning of "firmware" partition then it might fail to boot by assuming it starts with rootfs like you said... I have not done a lot of testing without a dedicated "loader" partition, I probably gave up for this reason.

To make sysupgrade from version 19 work, another EB would have to be wasted, or a change to mtdsplit...

**Comment by svanheule** [comment]
@bmork recently proposed some [changes to mtdsplit](https://patchwork.ozlabs.org/project/openwrt/patch/20201125114511.26663-9-bjorn@mork.no/) which might accommodate an offset uImage, even without requiring an entire EB. Setting "ih-start" to 0x3000, and "extra-magic" left empty or set to the ELF magic (0x7f454c46), would probably do the trick.

**Comment by thuehn** [comment]
Hi all,
I am happy to test some new approaches on cpe510v1,v1 and v3. So can you think of something concrete that I should test out ?
Greetings Thomas

**Comment by adschm** [comment]
I just had another look at my patch https://github.com/openwrt/openwrt/commit/d7fb7ac27849b8e1c1dcb17bac2472a2521fe946

There, I stated that the actual buildbot kernel was already 2469 kiB, or 0x269400. Thus, decreasing to 0x240000 is not an option anyway.

I'm thus NAKing this PR and closing it. Discussion about alternate partitioning/mtdsplit approaches may continue, but IMO at the current state they would be more suited in the forum.

**Comment by thuehn** [comment]
Hi Adrian,
Let's keep the discussion and testing open... the forum seems the right place.
 I have just updated one of our OpenWrt CPE210v3 access nodes running OpenWrt with an 2MB kernel partition via tftp initramfs and it stucks in the boot precess with the following output: (https://pastebin.com/TJze7rLn) So I am eager to  get this to a dynamic flash space usage device 👍 Greetings THomas

**Comment by adschm** [comment]
CPE210v3 is qca9533 and uses a splitter already. This is totally different from what's discussed here.

BTW I have never used initramfs on these devices, I'm not sure whether it's even supposed to work at all.

**Comment by thuehn** [comment]
ahh .. I see ... it's not the ar9344 ... ok ... l should be more focused ... promise to do so.
Let me get on of our v2s.
Gretings THomas

**Comment by mpratt14** [comment]
@thuehn make a forum post and link here, I can help you make an image with okli and the new mtdsplit patches

**Comment by adschm** [comment]
But be aware that the general interest in such a change for a specific set of (old) devices won't be overwhelming.

**Comment by mpratt14** [comment]
@bmork in your patch I see this if statement

`		if (header_offset && part_magic && (be32_to_cpu(*(u32 *)buf) != part_magic))`

(I could be wrong, my experience in C is very limited)

It looks to me that both header_offset and part_magic must be defined at the same time, and defining only one of them does nothing. I imagine there would be situations (like for these boards, TP Link CPE-series if we use OKLI), where you want to use one of these features but not the other. So maybe split it into two different if statements?

**Comment by bmork** [comment]
mpratt14 <notifications@github.com> writes:

> @bmork in your patch I see this if statement
>
> `		if (header_offset && part_magic && (be32_to_cpu(*(u32 *)buf) != part_magic))`
>
> (I could be wrong, my experience in C is very limited)
>
> It looks to me that both header_offset and part_magic must be defined
> at the same time, and defining only one of them does nothing.

Defining header_offset alone will do something.  But part_magic is only
valid if there is extra data before the U-Boot Image.  It's an
additional magic value, different from the one in the header.

> I imagine there would be situations (like for these boards, TP Link
> CPE-series if we use OKLI), where you want to use one of these features
> but not the other. So maybe split it into two different if statements?

There's another magic property ("openwrt,ih-magic") which is used to
define the non-default U-Boot Imagic for this device and others.  The
part_magic ("openwrt,partition-magic") is only used for a few device
where we verify two magic values.  This was previously implemented as
the "edimax,uimage" mtdsplit parser.

Yes, the names are confusing.  Naming is the hardest part of any
programming task ;-)  Feel free to suggest a better scheme...

**Pull request closed without merging**
