### PR TITLE
bpf tools: update libbpf (v1.4.0) and bpftool (v7.4.0)

### PR DESCRIPTION
**Pull request by guidosarducci**
**Maintainer**: me

**Description**:
Update libbpf and bpftool to versions v1.4.0 and v7.4.0 respectively, to include recent upstream improvements and bugfixes. This also drops some unneeded local patches and makefile override of `MAKE_VARS`. The upstream changes remain ABI-compatible with the previous release.

Upstream changelogs:
- https://github.com/libbpf/libbpf/releases/tag/v1.4.0
- https://github.com/libbpf/bpftool/compare/v7.3.0...v7.4.0 (formal release notes missing)

**Testing**: Build and run tested on mips64el/malta.

CC: @hauke @PolynomialDivision based on previous reviews/merges.

### CODE REVIEW

**Comment by guidosarducci** [comment]
> Does this libbpf version compile when lto is enabled? I have modified the Makefile to include `no-lto` in `PKG_BUILD_FLAGS` and it would be interesting if it is still necessary with the new version.

Looking more closely after you asked... When I added the package in 2f0d672088c39914ab9cd59b9de3d6f705cd6d5d I specifically disabled LTO for `libbpf` because shared libs and LTO aren't compatible, but enabled it for `bpftool`. However, it looks the flag was dropped by mistake recently so I'll need to re-add it. Did you have some build problems? Do you use LTO globally perhaps?

**Comment by guidosarducci** [comment]
Yes, I updated LTO flags and build/run tested.
________________________________

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by guidosarducci** [comment]
Thanks for merging.

**Pull request merged**
