### PR TITLE
mt76: mt7603: add additional EEPROM chip ID

### PR DESCRIPTION
**Pull request by kousu**
Over on the forum [people are dealing with a miserable wifi bug](https://forum.openwrt.org/t/archer-c50-v4-mac80211-looses-internet-access-after-20-away-from-router-but-maintains-connection/53575/128) which was fixed by [this one line patch](https://github.com/openwrt/mt76/pull/442). But the fix isn't available to anyone except people who manually cherry-pick it into their tree or are brave enough to trust a stranger's build. I would like to see it in the future http://downloads.openwrt.org/releases/19.07.7/targets/ramips/mt76x8/openwrt-19.07.7-ramips-mt76x8-tplink_c50-v4-squashfs-sysupgrade.bin so we can all have the fix, so I cherry-picked https://github.com/openwrt/openwrt/commit/b837534f029da10abbd1069392867e0700134ace over to the stable branch.

I bet this probably can't go in directly, since it includes a bunch of patches and not just https://github.com/openwrt/mt76/commit/b0c7f88d900d2986cd2061113201825eda6a6482, but I'm at least hoping that in the discussion I can find out how to get it into "production" the right way.

Thanks for your consideration and your software. I appreciate putting the slogan into practice in my daily radiation doses.

### CODE REVIEW

**Comment by Borromini** [comment]
@nbd168 ping

**Comment by hauke** [comment]
I would prefer if you only backport this single patch to 19.07:
https://github.com/openwrt/mt76/commit/9a1a0a4dec71728c314938a205f87b320a71cb77

**Comment by adschm** [comment]
Note that there is an openwrt-19.07 branch in mt76 repo. Changes should first be put there, and then a proper commit from that branch should be taken.

Thus, having stuff backported to that branch should actually be discussed with @nbd168 in the mt76 repo.

**Comment by kousu** [comment]
Ah I see! Thanks for the guidance. I've put that up here: https://github.com/openwrt/mt76/pull/499

I guess I can't know what commit ID to use until if/when that gets merged. Can I leave this open as a draft for later?

**Comment by kousu** [comment]
Thank you for merging this @blocktronn!

https://github.com/openwrt/openwrt/commit/a7a207e18bf7fa04f265bb95cbe6fa91561fbfe8

**Pull request closed without merging**
