### PR TITLE
dnsmasq: change the default local domain to ".INTERNAL"

### PR DESCRIPTION
**Pull request by gentrydeng**
The Internet Assigned Numbers Authority has made a provisional determination that ".INTERNAL" should be reserved for private-use and internal network applications.

https://www.icann.org/en/announcements/details/icann-seeks-feedback-on-proposed-top-level-domain-string-for-private-use-24-01-2024-en

---

- Proceeding: https://www.icann.org/en/public-comment/proceeding/proposed-top-level-domain-string-for-private-use-24-01-2024
- Discussions in the forum: https://forum.openwrt.org/t/icann-proposes-internal-private-zone/186075
- Related PR: https://github.com/openwrt/openwrt/pull/9891

### CODE REVIEW

**Comment by simpz** [comment]
Seems a bit premature to change this, as this is just a proposal and most of the public comments say internal is too long and maybe lan would be better.

**Comment by cherinyy** [comment]
> Seems a bit premature to change this, as this is just a proposal and most of the public comments say internal is too long and maybe lan would be better.

I agree with this, `.LAN` is simpler than `.INTERNAL`. I'm going to go ahead and submit my comments as well.

This PR is mainly to "force" more people to know about the proposal.

**Comment by hauke** [comment]
Many users are used to the `.lan` domain. Changing the default will cause trouble for our users. `.lan` is currently not for sale and I do not think it will happen. I would prefer to stay at `.lan`.

**Comment by systemcrash** [comment]
NAK

**Comment by rokezu** [comment]
It is now ratified, just adding the reference, I'm fine either way with .lan or .internal: 

_Resolved (2024.07.29.06), the Board reserves .INTERNAL from delegation in the DNS root zone permanently to provide for its use in private-use applications. The Board recommends that efforts be undertaken to raise awareness of its reservation for this purpose through the organization's technical outreach._

Reference: https://www.icann.org/en/board-activities-and-meetings/materials/approved-resolutions-special-meeting-of-the-icann-board-29-07-2024-en#section2.a

**Pull request closed without merging**
