### PR TITLE
tools: tar: update to 1.35

### PR DESCRIPTION
**Pull request by robimarko**
Instead of backporting select 1.35 fixes to make tar work for us, lets update to 1.35 now that we have identified the upstream fix for macOS.

### CODE REVIEW

**Comment by mpratt14** [comment]
I thought we couldn't do this because it broke macOS build because either:

A. we were not patching Makefile.in directly

or

B. we were not able to enable autoreconf because of dependency conflicts between tools

**Comment by mpratt14** [comment]
oh wait, I see you did patch Makefile.in instead, nevermind

after a quick look I only noticed the message in the patch saying `src/Makefile.am`

**Comment by robimarko** [comment]
Yeah, Makefile.in is patched directly to avoid requiring m4, I tested this on macOS 14.5.

**Comment by mpratt14** [comment]
no longer builds on 32-bit OS because of requiring 64-bit timestamps
(would need to be reconfigured to bypass)

please see #15799

**Pull request merged**
