### PR TITLE
iproute2: fix GCC14 compilation

### PR DESCRIPTION
**Pull request by neheb**
Missing limits.h. Upstream backport.

ping @hauke @robimarko

### CODE REVIEW

**Comment by robimarko** [comment]
How are you reproducing this?
Because even with GCC14 it still compiles fine for me in OpenWrt.

That being said, probably a good idea to also backport:
- https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=c8b3ecc22ed0edaf0259eaf7d1a5c04f300ad6e4
- https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=f982f30e166a02e09097de05129449031ba51f76
- https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=458dce5d0431f0589aca1bc841904b5d1db3bbce

**Comment by neheb** [comment]
@robimarko mips64 malta with CONFIG_ALL.

**Comment by neheb** [comment]
Reworked. Replaced all local patches with upstream backports.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
