### PR TITLE
netfilter: fix HW NAT crash when KERNEL_NET_NS=y

### PR DESCRIPTION
**Pull request by HenryHsiu**
It is found that hardware offload encounters a kernel panic issue when
KERNEL_NET_NS=y.

Root cause: when the flow offloading framework intends to delete a flow
from the hardware table, it is necessary to retrieve the namespace from
nf_flowtable->ft_net. However, no one ever wrote the namespace into
nf_flowtable->ft_net in advance. So the framework will mistakenly use a NULL
namespace to execute dev_get_by_index_rcu(net, ifindex), making the kernel
panic issue happens.

Signed-off-by: HsiuWen Yen <y.hsiuwen@gmail.com>

### CODE REVIEW

**Comment by ynezz** [comment]
How to reproduce this problem, which platform/device are you experiencing it on? Can you please provide complete kernel crash log? 

Was the crash caused by fcb41decf6c622482b20af45a77e62db8d95046e ? If so please add `Fixes: fcb41decf6c6 ("config: enable some useful features on !SMALL_FLASH devices")`.

Please remove the other merge commits (you probably need to do rebase), there should be only one commit `Commits (1)` in the `Commits (3)` tab above.

**Comment by HenryHsiu** [comment]
I use mt7621 with hardware flow offloading enabled.

The issue can be reproduced as follows:

(Step 1) :
open KERNEL_NET_NS=y via "make menuconfig", then build image.

Symbol: KERNEL_NET_NS [=y]
Type  : boolean
Prompt: Network namespace
Location:                                                -> Global build
settings                          -> Kernel build options
      -> Enable kernel namespaces (KERNEL_NAMESPACES [=y])


(Step 2):
After boot up, open hardware flow offloading via command "iptables -I
FORWARD 1 -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw"

(Step 3) :
Initiate a LAN to WAN traffic, then we can immediately see the kernel panic
log as follows :

[   75.153531] CPU 1 Unable to handle kernel paging request at virtual
address 000000a4, epc == 8037b128, ra == 86a57024
[   75.164130] Oops[#1]:
[   75.166395] CPU: 1 PID: 66 Comm: kworker/1:1 Not tainted 4.14.127 #0
[   75.172748] Workqueue: events_power_efficient flow_offload_lookup
[nf_flow_table]
[   75.180198] task: 87c7db00 task.stack: 87dba000
[   75.184705] $ 0   : 00000000 00000001 00000200 00000003
[   75.189915] $ 4   : 00000000 00000003 87dbbd98 00000602
[   75.195125] $ 8   : dd92e70b ab1210d0 00000002 000e27f4
[   75.200335] $12   : 00000000 86a40780 86a40780 76760000
[   75.205544] $16   : 00000000 87dbbd98 87d61904 86ac2400
[   75.210755] $20   : 86abaa78 86abc70c 805c0000 cccccccd
[   75.215964] $24   : 00000000 8000cf34
[   75.221175] $28   : 87dba000 87dbbd68 00000000 86a57024
[   75.226385] Hi    : 00000099
[   75.229248] Lo    : 999999c0
[   75.232122] epc   : 8037b128 dev_get_by_index_rcu+0x4/0x5c
[   75.237585] ra    : 86a57024 0x86a57024
[   75.241398] Status: 11007c03 KERNEL EXL IE
[   75.245569] Cause : 40800008 (ExcCode 02)
[   75.249554] BadVA : 000000a4
[   75.252416] PrId  : 0001992f (MIPS 1004Kc)
[   75.256487] Modules linked in: pppoe ppp_async pppox ppp_generic
nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp
xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack
xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_FLOWOFFLOAD slhc nf_reject_ipv4
nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat
nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4
nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables
crc_ccitt nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter
ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 leds_gpio gpio_button_hotplug
[   75.313009] Process kworker/1:1 (pid: 66, threadinfo=87dba000,
task=87c7db00, tls=00000000)
[   75.321317] Stack : ff7f5fff 87c3a780 21518048 c0a80103 00000000
87d61900 87d6193c 86a57490
[   75.329653]         0a0a0a03 f2afcaca 00000000 00000000 00000000
00000000 00000000 00000000
[   75.337986]         00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000
[   75.346319]         00000000 00000000 81142cf0 00000003 87d61900
86a57620 87d9bc00 81142940
[   75.354653]         81145b00 86abaa78 00000003 86a90c2c 87c7de30
804b0000 805c0000 fffffffe
[   75.362986]         ...
[   75.365421] Call Trace:
[   75.367859] [<8037b128>] dev_get_by_index_rcu+0x4/0x5c
[   75.372987] [<86a57024>] 0x86a57024
[   75.376461] Code: 03e00008  00000000  30a300ff <8c8200a4> 00031880
 00431021  8c420000  1040000e  00000000
[   75.386188]
[   75.387794] ---[ end trace 1162d511c24dc728 ]---
[   75.393639] Kernel panic - not syncing: Fatal exception in interrupt
[   75.400957] Rebooting in 3 seconds..


Petr Štetiar <notifications@github.com> 於 2019年6月21日 週五 下午6:24寫道：

**Comment by HenryHsiu** [comment]
I use mt7621 with hardware flow offloading enabled.
The issue can be reproduced as follows:

(Step 1) :
Enter "make menuconfig" to open option KERNEL_NET_NS=y, then build image.

Symbol: KERNEL_NET_NS [=y]
Type  : boolean         
Prompt: Network namespace
Location:                                                
     -> Global build settings                          
         -> Kernel build options                         
             -> Enable kernel namespaces (KERNEL_NAMESPACES [=y]) 

(Step 2):
After boot-up, open hardware flow offloading via command "iptables -I FORWARD 1 -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD --hw"

(Step 3) : 
Initiate a LAN to WAN traffic, then we can immediately see the kernel panic log as follows :

[   75.153531] CPU 1 Unable to handle kernel paging request at virtual address 000000a4, epc == 8037b128, ra == 86a57024
[   75.164130] Oops[#1]:
[   75.166395] CPU: 1 PID: 66 Comm: kworker/1:1 Not tainted 4.14.127 #0
[   75.172748] Workqueue: events_power_efficient flow_offload_lookup [nf_flow_table]
[   75.180198] task: 87c7db00 task.stack: 87dba000
[   75.184705] $ 0   : 00000000 00000001 00000200 00000003
[   75.189915] $ 4   : 00000000 00000003 87dbbd98 00000602
[   75.195125] $ 8   : dd92e70b ab1210d0 00000002 000e27f4
[   75.200335] $12   : 00000000 86a40780 86a40780 76760000
[   75.205544] $16   : 00000000 87dbbd98 87d61904 86ac2400
[   75.210755] $20   : 86abaa78 86abc70c 805c0000 cccccccd
[   75.215964] $24   : 00000000 8000cf34
[   75.221175] $28   : 87dba000 87dbbd68 00000000 86a57024
[   75.226385] Hi    : 00000099
[   75.229248] Lo    : 999999c0
[   75.232122] epc   : 8037b128 dev_get_by_index_rcu+0x4/0x5c
[   75.237585] ra    : 86a57024 0x86a57024
[   75.241398] Status: 11007c03 KERNEL EXL IE
[   75.245569] Cause : 40800008 (ExcCode 02)
[   75.249554] BadVA : 000000a4
[   75.252416] PrId  : 0001992f (MIPS 1004Kc)
[   75.256487] Modules linked in: pppoe ppp_async pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_FLOWOFFLOAD slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc_ccitt nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 leds_gpio gpio_button_hotplug
[   75.313009] Process kworker/1:1 (pid: 66, threadinfo=87dba000, task=87c7db00, tls=00000000)
[   75.321317] Stack : ff7f5fff 87c3a780 21518048 c0a80103 00000000 87d61900 87d6193c 86a57490
[   75.329653]         0a0a0a03 f2afcaca 00000000 00000000 00000000 00000000 00000000 00000000
[   75.337986]         00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[   75.346319]         00000000 00000000 81142cf0 00000003 87d61900 86a57620 87d9bc00 81142940
[   75.354653]         81145b00 86abaa78 00000003 86a90c2c 87c7de30 804b0000 805c0000 fffffffe
[   75.362986]         ...
[   75.365421] Call Trace:
[   75.367859] [<8037b128>] dev_get_by_index_rcu+0x4/0x5c
[   75.372987] [<86a57024>] 0x86a57024
[   75.376461] Code: 03e00008  00000000  30a300ff <8c8200a4> 00031880  00431021  8c420000  1040000e  00000000
[   75.386188]
[   75.387794] ---[ end trace 1162d511c24dc728 ]---
[   75.393639] Kernel panic - not syncing: Fatal exception in interrupt
[   75.400957] Rebooting in 3 seconds..

By the way, thanks for your reminder.
I will reorganize the three commits later.

**Comment by ynezz** [comment]
> Enter "make menuconfig" to open option KERNEL_NET_NS=y, then build image.

This makes me confused, as I think, that this is not necessary, you should be able to trigger the problem even with snapshot images from http://downloads.openwrt.org/snapshots/targets/ramips/mt7621/ as `KERNEL_NET_NS=y` is now added automatically for mt6721 with following commit https://github.com/openwrt/openwrt/commit/fcb41decf6c622482b20af45a77e62db8d95046e

Reporter from https://bugs.openwrt.org/index.php?do=details&task_id=2321 is using snapshot images and is getting the same crash.

**Comment by simontretter** [comment]
Same issue here. Reproduced on the Ubiquity ER-X.

**Comment by HenryHsiu** [comment]
@ynezz
yes, this step is not necessary. I just want to emphasize that the crash is
highly related to the network namespace option.
The kernel panic problem can indeed be triggered with the snapshot images
from http://downloads.openwrt.org/snapshots/targets/ramips/mt7621/


Simon Tretter <notifications@github.com> 於 2019年6月23日 週日 下午5:56寫道：

**Comment by ynezz** [comment]
Thanks, I've reworked it little bit and merged it into my staging tree https://git.openwrt.org/05dabd75163f

**Comment by ynezz** [comment]
@simontretter Can you please kindly test https://git.openwrt.org/05dabd75163f and give me your `Tested-by: Real Name <your@email.com>` ? Thanks!

**Comment by simontretter** [comment]
[Refactored](https://git.openwrt.org/?p=openwrt/staging/ynezz.git;a=commit;h=05dabd75163fe7f2882dd549ef73a4f45ac7d7f9) patch tested on ER-X. No kernel crashes / reboots.

Tested-by: Simon Tretter simon@mediaarchitectu.re

**Pull request closed without merging**
