### PR TITLE
kernel: bump 5.4 to 5.4.102

### PR DESCRIPTION
**Pull request by graysky2**
Ran update_kernel.sh in a fresh clone without any existing toolchains.

Removed upstreamed generic-backports:
```
  080-wireguard-0072-net-icmp-pass-zeroed-opts-from-icmp-v6-_ndo_send-bef.patch
  080-wireguard-0073-net-icmp-pass-zeroed-opts-from-icmp-v6-_ndo_send-bef.patch
  830-v5.12-0002-usb-serial-option-update-interface-mapping-for-ZTE-P685M.patch
```
Manually rebased:
```
  mvebu/312-helios4-dts-status-led-alias.patch
```

Build system: x86_64
Build-tested: ipq806x/R7800
Run-tested: ipq806x/R7800

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by graysky2** [comment]
I get an error relating to iproute2 failing to build.  But building a 2nd time using `make -j1 V=s` completes without error.  I am reluctant to flash the image as a result.  Can others confirm?

```
 make[3] -C package/network/utils/iproute2 compile
    ERROR: package/network/utils/iproute2 failed to build (build variant: tc).
```

**Comment by Borromini** [comment]
I've been seeing that kind of breakage for like a week now. -j1 'fixes' it for me as well, so yeah, looks like a race condition.

If it builds, it builds. The build system has a check for every single package (unless you overrule it), so there's no reason not to flash an image that wasn't build in a single run.

**Comment by graysky2** [comment]
@Borromini - Thanks for the perspective.  I flashed it and it was fine.

**Comment by rsalvaterra** [comment]
@zx2c4's bump was [merged](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=196f3d586f11d96ba4ab60068cfb12420bcd20fd) already…

**Pull request closed without merging**
