### PR TITLE
uhttpd: fix 413 when content length is a multiple of 4096

### PR DESCRIPTION
**Pull request by jjm2473**
fix https://github.com/openwrt/luci/issues/2051

Signed-off-by: Liangbin Lian <jjm2473@gmail.com>

### CODE REVIEW

**Review by jannson — APPROVED** [review]
Should not response "Request Entity Too Large" when the state is CLIENT_STATE_DONE, after the http header parsing complete.

**Comment by ptpt52** [comment]
mark

**Comment by hnyman** [comment]
For some reason, this is authored for 21.02 instead of master...

And the fix should be done directly to the uhttpd repo, instead of creating a patch here.

cc @jow-

**Comment by Ansuel** [comment]
@hnyman think we should resend this to the mailing list.

**Comment by hnyman** [comment]
Why?

I think that the code has already been updated by @jow- in the uhttp repo, but the Makefile in the OpenWrt main repo has not been bumped to use the new version :-(

https://git.openwrt.org/?p=project/uhttpd.git;a=commitdiff;h=23977554d9694d025eada50a5547e99ee1be7838

https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=package/network/services/uhttpd/Makefile;h=d6a5a271819f7e79871164cf609cbea6d7ea5685;hb=HEAD

**Comment by Ansuel** [comment]
Oh ok then it's just a simple package bump

Il Sab 24 Dic 2022, 13:17 Hannu Nyman ***@***.***> ha scritto:

**Comment by hauke** [comment]
The patch was already merged into uhttpd. I updated uhttp to recent master in 73dca49f355fe10d1d5e629b0df584b03a1849b3. OpenWrt master includes this fix now.

**Pull request closed without merging**
