### PR TITLE
ipq807x: use Aquantia PHY as kmod

### PR DESCRIPTION
**Pull request by robimarko**
ipq807x does not compile-in hwmon core, and this is leading to the hwmon
code in AQR driver not being compiled due to `IS_REACHABLE(CONFIG_HWMON)`
evaluating to false as hwmon is being built as a module.

So, let's not compile-in Aquantia PHY driver but include it as a kmod instead to
have functioning AQR hwmon features.

`Signed-off-by: Robert Marko <robimarko@gmail.com>`

### CODE REVIEW

**Comment by robimarko** [comment]
@mrkiko This is required in order to be able to add thermal zones on top of AQR thermal sensors

**Comment by Ansuel** [comment]
Mhhh lets add also why we need hwmon feature? Just curious

**Comment by robimarko** [comment]
@Ansuel You mean in the commits or PR?

Its in order for AQR thermal sensors to be registered so they can be used a thermal zone for cooling

**Comment by Ansuel** [comment]
@robimarko both also i think a better idea is to squash the 2 last commit and use something like "move AQR driver from built-in to kmod" or something like that? Would produce better commit message and delta

**Comment by robimarko** [comment]
@Ansuel Ok, makes sense

**Comment by robimarko** [comment]
@Ansuel should be better now

**Pull request merged**
