### PR TITLE
bcm27xx-gpu-fw: update to version 2022-02-09

### PR DESCRIPTION
**Pull request by Yx-2**
bcm27xx-gpu-fw: update to version 2022-02-09

Signed-off-by: Rox Nones [wdfcy2@outlook.com](mailto:wdfcy2@outlook.com)

### CODE REVIEW

**Comment by mans0n** [comment]
Hi, this has some formal issues, especially:
* Please add a proper commit message.
* Please add a Signed-off-by tag with your real name and a reachable mail address.
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes

**Comment by Yx-2** [comment]
> 



> Hi, this has some formal issues, especially:
> 
> * Please add a proper commit message.
> * Please add a Signed-off-by tag with your real name and a reachable mail address.
> 
> https://openwrt.org/docs/guide-developer/frequent-pr-mistakes

Changed

**Comment by mans0n** [comment]
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes#know_the_difference_between_the_pr_pull_request_and_the_commit

**Comment by Noltari** [comment]
Sorry, I didn't see this PR when adding linux 5.15 support.
Anyway, it's now obsolete due to bca05bd072180dc38ef740b37ded9572a6db1981.

**Pull request closed without merging**
