### PR TITLE
ipq806x: switch to kernel 5.10

### PR DESCRIPTION
**Pull request by Ansuel**
Move kernel version to 5.10 as has been tested by many user
with positive feedback.
Patches for kernel 5.4 are kept for reference if for whatever
reason someone still needs them or require to build an image
with the old kernel version.
Patch for 5.4 will later be dropped when this target will
be migrated to DSA since too much effort are required to
backport qca8k patch for 5.4 and won't work anymore.

@hnyman @adschm Think it's time to move this target... If I have time i will also rework the dsa patch and move it to generic and hope to finally start to test that for other target. Did anyone notice the mail send to the mailing list? 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
would be great to get DSA on ath79.

**Comment by Ansuel** [comment]
@neheb don't have a target to test so i can only help and check what is needed to get it running

**Comment by neheb** [comment]
Sure. I've been busy with other stuff lately so I couldn't devote as much time on this.

Last I remember I couldn't get qca8k go load. It's possible this was because I was building with the wrong kernel (5.4 instead of 5.10 ...). I'll try to redo my setup sometime soon.

Since then, I removed the WiFi card from my device and placed it elsewhere. For those curious: 
PXL_20210823_221539545

**Comment by Ansuel** [comment]
the card is a little bigger ahahah (if you want to use the other port, try to find an extension cable)

anyway the not loading error is strange at least an error should be reported... the kernel should not be the cause...

**Comment by neheb** [comment]
> 
> 
> the card is a little bigger ahahah (if you want to use the other port, try to find an extension cable)
There are three slots. I don't mind if one is blocked. It is somewhat concerning that it's that close to the CPU.
> 
> anyway the not loading error is strange at least an error should be reported... the kernel should not be the cause...
Hmm good point. I remember looking through dmesg and not finding qca8k anywhere.

**Comment by Ansuel** [comment]
the driver check the switch id... in some old version it was silent and didn't produce any error... now it should report if it does detect an invalid id and fail to probe... could be that there is a special configuration needed for the mdio communication (and id 0 was reported) or the switch actually use a not supported id

**Comment by mrkiko** [comment]
Is the Netgear R7800 working correctly on 5.10? I guess yes, but I remember looking at this in the beginning and now lost track.

**Comment by wulfy23** [comment]
thanks for your hard work ansuel... especially the nice linear spacing of all the recent major changes... spot on

really appreciate having the 5.4 patches left in tree for a month-ish or so and the ability to build from those.

**Comment by pkgadd** [comment]
> Is the Netgear R7800 working correctly on 5.10?

The Netgear r7800 has been confirmed to work in v5.10, I guess the table at https://github.com/openwrt/openwrt/pull/4036#issuecomment-839053531 is still largely current (in the mean time I've successfully tested the ASRock G10 as well, albeit only within the DSA branch).

**Comment by adschm** [comment]
Commit message should be edited since this does _not_ "drop" kernel 5.4. This will only be the case when config and patches are removed.

It's still perfectly possible to build 5.4 if you just change this single variable.

However, regarding DSA I understand it that way that 5.4 won't work anymore after DSA patches are introduced. Thus, we should actually remove kernel 5.4 support - by dropping patches/config - before that point.

Due to the latter, I think we should move to default 5.10 soon; this will help to spot problems by a wider audience before we might introduce additional problems with DSA (so DSA will probably have to wait a few weeks after default 5.10 due to that reason).

So, are there any known problem with 5.10 left at the moment?

**Comment by rbpp** [comment]
I've been using 5.10 on my R7800 and C2600 for a few months and had no problems whatsoever.

**Comment by Ansuel** [comment]
@adschm aside the problem of instability with some very high load (present also on 5.4), no issue observed.

Will change the message and remove the drop part

**Comment by hnyman** [comment]
I compiled the current 5.10 version for R7800 and it works nicely ;-)

**Comment by graysky2** [comment]
> I compiled the current 5.10 version for R7800 and it works nicely ;-)

Stupid question but here goes: is there anything special needed to switch from 5.4.x to 5.10.x on the R7800?  Is it as simple as applying this PR, building, and flashing?

**Comment by Ansuel** [comment]
no you actually test 5.10 by enabling the testing kernel version flag...

**Comment by graysky2** [comment]
> no you actually test 5.10 by enabling the testing kernel version flag...

OK.  Just wanted to be sure nothing else was needed.  I am happy to apply this PR and test on my R7800.

I found this under a symbol search:
```
Symbol: TESTING_KERNEL [=n]
Type  : bool
Defined at config/Config-build.in:63 
   Prompt: Use the testing kernel version
   Depends on: HAS_TESTING_KERNEL [=n]
   Location:
     -> Global build settings
```

But I do not see a corresponding option under Global build settings in my nconfig.  What am I missing?

**Comment by Ansuel** [comment]
if you have applied this pr then 5.10 is now the default version and testing kernel version flag is not available anymore.

**Comment by graysky2** [comment]
Got it.  Apply, build, flash.  Thank you.

**Comment by pkgadd** [comment]
> So, are there any known problem with 5.10 left at the moment?

I'm not aware of any regressions relative to v4.19 or v5.4 (yes, digitalcircuit is hunting a crash under load, but that one also happens with v5.4 and happened with v4.19 already, so this is not a regression in this PR).

Stealing (and slightly updating) the table below from the [DSA PR#4036](https://github.com/openwrt/openwrt/pull/4036), which implies using kernel v5.10:

Tested, or very similar to a tested device:
- ASRock G10 ✅
- Linksys EA7500 V1 WiFi Router ✅
  - Linksys EA8500 WiFi Router  ☑️ (probably similar enough to expect it working)
- NEC WG2600HP ✅
- NEC WG2600HP3 ✅
- Netgear r7800 ✅
  - Netgear d7800 ☑️ (probably similar enough to expect it working)
  - Netgear r7500 ☑️ (probably similar enough to expect it working)
  - Netgear r7500v2 ☑️ (probably similar enough to expect it working)
- TP-Link Archer c2600 ✅
  - TP-Link Archer VR2600V ☑️ (probably similar enough to expect it working)
  - TP-Link Talon AD7200 ☑️ (probably similar enough to expect it working)
- Ubiquiti UniFi AC HD ✅
- ZyXEL NBG6817 ✅

Untested:
- Askey RT4230W REV6 ❓
- Buffalo WXR-2533DHP ❓
- Edgecore ECW5410 ❓

Unlikely to get feedback (expensive devboards, used by early adopters who have probably moved on meanwhile):
- Compex WPQ864
- Qualcomm IPQ8064/AP-148
- Qualcomm IPQ8064/AP161
- Qualcomm IPQ8064/DB149

This test matrix successfully covers ipq8064 and ipq8065, just as well as spi-nor, NAND and eMMC storage.

**Review by neheb — APPROVED** [review]

**Comment by adschm** [comment]
Thanks, I will merge this during the weekend.

**Comment by adschm** [comment]
I'm sorry, won't build for me:

```
true "AR_FLAGS=rc" "CC_FOR_BUILD=gcc" "CFLAGS=-O2 -I/data/openwrt/staging_dir/host/include " "CXXFLAGS=-g -O2" "CFLAGS_FOR_BUILD=" "CFLAGS_FOR_TARGET=-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" "INSTALL=/data/openwrt/staging_dir/host/bin/install -c" "INSTALL_DATA=/data/openwrt/staging_dir/host/bin/install -c -m 644" "INSTALL_PROGRAM=/data/openwrt/staging_dir/host/bin/install -c" "INSTALL_SCRIPT=/data/openwrt/staging_dir/host/bin/install -c" "LDFLAGS=-static-libstdc++ -static-libgcc " "LIBCFLAGS=-O2 -I/data/openwrt/staging_dir/host/include " "LIBCFLAGS_FOR_TARGET=-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" "MAKE=make" "MAKEINFO=/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0/missing makeinfo --split-size=5000000 --split-size=5000000 " "PICFLAG=" "PICFLAG_FOR_TARGET=" "SHELL=/bin/bash" "EXPECT=expect" "RUNTEST=runtest" "RUNTESTFLAGS=" "exec_prefix=/data/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi" "infodir=/data/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/share/info" "libdir=/data/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/lib" "prefix=/data/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi" "tooldir=/data/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/arm-openwrt-linux-muslgnueabi" "AR=ar" "AS=as" "CC=gcc" "CXX=g++" "LD=ld" "LIBCFLAGS=-O2 -I/data/openwrt/staging_dir/host/include " "NM=nm" "PICFLAG=" "RANLIB=ranlib" "DESTDIR=" DO=all multi-do # make
make[6]: Leaving directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/zlib'
make[6]: Entering directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/libbacktrace'
make  all-am
make[7]: Entering directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/libbacktrace'
true  DO=all multi-do # make
make[7]: Leaving directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/libbacktrace'
make[6]: Leaving directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/libbacktrace'
make[6]: Entering directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/libcpp'
test -f config.h || (rm -f stamp-h1 && make stamp-h1)
make[6]: Leaving directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/libcpp'
make[6]: Entering directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/libdecnumber'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/libdecnumber'
make[6]: Entering directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/gcc'
/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/./gcc/xgcc -B/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/./gcc/ -xc -nostdinc /dev/null -S -o /dev/null -fself-test=/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0/gcc/testsuite/selftests
xgcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
make[6]: *** [/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0/gcc/c/Make-lang.in:124: s-selftest-c] Error 1
make[6]: Leaving directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/gcc'
make[5]: *** [Makefile:4397: all-gcc] Error 2
make[5]: Leaving directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final'
make[4]: *** [Makefile:961: all] Error 2
make[4]: Leaving directory '/data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final'
make[3]: *** [Makefile:91: /data/openwrt/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/gcc-10.3.0-final/.built] Error 2
make[3]: Leaving directory '/data/openwrt/toolchain/gcc/final'
time: toolchain/gcc/final/compile#1.23#0.13#1.34
    ERROR: toolchain/gcc/final failed to build.
make[2]: *** [toolchain/Makefile:97: toolchain/gcc/final/compile] Error 1
make[2]: Leaving directory '/data/openwrt'
make[1]: *** [toolchain/Makefile:93: /data/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-10.3.0_musl_eabi/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/data/openwrt'
make: *** [/data/openwrt/include/toplevel.mk:230: world] Error 2
```

on Debian 10 and 11 with default settings

**Comment by Ansuel** [comment]
strange they are toolchain error not related to target compilation problem o.O

my build env is ubuntu devel with gcc 11

**Comment by adschm** [comment]
@Ansuel Yes, of course not related, but I'm not able to build and thus test. In contrast, ipq40xx builds without problems.

**Comment by Ansuel** [comment]
could be that some advanced toolchain flags are set that are not compatible with ipq806x ?
I had some strange error when i tried to compile ath79 with the ipq806x flags and they were caused by some custom flags set by me that were still present after changing target in menuconfig

**Comment by adschm** [comment]
Well, gcc 10 never really went smoothly on my systems. I'm still trying to get it build reliably here.
But maybe the problem is just somewhere on my side.

**Comment by adschm** [comment]
This builds fine with gcc 8, so I decided to merge it anyway.
My gcc 10 build issues are probably unrelated.

**Comment by hnyman** [comment]
@adschm @Ansuel 

Probably also the armvirt (32) target that provides the packages SDK for buildbot, should be toggled to 5.10 sooner or later.

It has been "testing 5.10" since #4005 in April, but I am not sure what that actually indicates as buildbot is not really building the testing kernelSDK, and I think pretty much nobody builds armvirt separately for private builds.

**Comment by Neustradamus** [comment]
Merged commit is:
- https://github.com/openwrt/openwrt/commit/0470159552641c2b11ccc1b0fcfcb4ea08f2c6ab

**Pull request closed without merging**
