### PR TITLE
realtek: Follow kernel comment style recommendation

### PR DESCRIPTION
**Pull request by oliv3r**
While Linus is fine with longer code lines, comments should still be within the 80 char limit.

### CODE REVIEW

**Comment by oliv3r** [comment]
@svanheule this one comes out of Marcus's pile and can be merged completly isolated from the rest. The rest, requires a lot more love!

**Comment by oliv3r** [comment]
@Ansuel can you add the 'trivial' tag for me? :)

**Comment by svanheule** [comment]
Applied. I hope you're not going to commit all your patches one by one. ;)

**Comment by oliv3r** [comment]
> Applied. I hope you're not going to commit all your patches one by one. ;)

lol; maybe; I could open a big MR though with the others in it :package: 
jokes aside, I'm grouping things as they fit. This one _should_ have been part of the whitespace/codestyle patch; but I hadn't looked at those timer patches at all. Otherwise, it would have gone with that set.

**Pull request closed without merging**
