### PR TITLE
hostapd: update to 2024-09-15

### PR DESCRIPTION
**Pull request by AuthorReflex**
On 2024-07-20 hostapd published 2.11 release

Key features:
* Wi-Fi Easy Connect
  - add support for DPP release 3
  - allow Configurator parameters to be provided during config exchange
* HE/IEEE 802.11ax/Wi-Fi 6
  - various fixes
* EHT/IEEE 802.11be/Wi-Fi 7
  - add preliminary support
* SAE: add support for fetching the password from a RADIUS server
* support OpenSSL 3.0 API changes
* support background radar detection and CAC with some additional
  drivers
* support RADIUS ACL/PSK check during 4-way handshake (wpa_psk_radius=3)
* EAP-SIM/AKA: support IMSI privacy
* improve 4-way handshake operations
  - use Secure=1 in message 3 during PTK rekeying

...and many more

First commit update version to 2.11 release tag, second commit updates to the most actual version.

Runtime tested on mt7622/Xiaomi redmi ax6s(openssl), mt7621/Xiaomi  mi router 3 pro (openssl) , mt76x8/TP-Link mr3020 (mbedtls), mt76x8/Asus AC1200 (mbedtls), ath79/TP-Link wa901nd (mbedtls, kernel 5.15) with 802.11r configuration.

Additional tests are welcome

### CODE REVIEW

**Comment by Neustradamus** [comment]
@AuthorReflex: Thanks for your PR!

**Comment by AgustinLorenzo** [comment]
Hi @AuthorReflex

I have added your 2 commits to the build I compile for AX3600+NSS, in a couple of hours I will tell you how it works in my setup :)

Regards, Agustin

**Comment by rany2** [comment]
I know for sure that these were supported prior. For example, #16342 and #16343 both depend on the below but don't need to update hostapd or backport any patches.

> * EHT/IEEE 802.11be/Wi-Fi 7
> * SAE: add support for fetching the password from a RADIUS server

IMO it would be better that you drop your 802.11be related changes in favor of the more complete PR #16342.

**Comment by AuthorReflex** [comment]
> I know for sure that these were supported prior. For example, #16342 and #16343 both depend on the below but don't need to update hostapd or backport any patches.
> 
> > * EHT/IEEE 802.11be/Wi-Fi 7
> > * SAE: add support for fetching the password from a RADIUS server
> 
> (somewhat related) IMO it would be better that you drop your 802.11be related changes in favor of the more complete PR #16342.
> 
> Edit: also I've been running this for 2 days now on ramips/mt7621 (asus rt-ax53u) and mediatek/mt7622 (redmi ax6s) both on the openssl full variant. I can't notice any changes which in this context is a good thing.

Sure. I made these changes to check compatibility and they accidentally got committed when updating existing patches. They have now been removed.

**Comment by AgustinLorenzo** [comment]
After 1 day and 6 hours of uptime I haven't detected anything strange (there may be a small performance improvement) and the users that use my build, none of them have reported anything strange.

Device: AX3600

**Comment by danpawlik** [comment]
After half day testing, I don't see any strange behavior or any error. LGTM.

**Comment by danpawlik** [comment]
Need to check once again, but I guess that change with  https://github.com/openwrt/openwrt/pull/16342 does not work properly for eht and 6GHz network

**Comment by danpawlik** [comment]
@AuthorReflex please update issue name. Thanks!

**Comment by Neustradamus** [comment]
@AuthorReflex: Thanks for the update time after time from hostapd upstream before the @openwrt team merging :)

**Comment by robimarko** [comment]
Lets see what breaks :)

**Pull request merged**
