### PR TITLE
image.mk: set subtarget to generic if unset

### PR DESCRIPTION
**Pull request by aparcar**
The target `ipq806x` has no subtarget and the resulting filesnames
threfore only contain `ipq806x`. For consistency created files are
stored in `ipq806x/generic`, this patch does the same to filenames.

Example output:

    openwrt-ipq806x-generic-netgear_r7800-initramfs-uImage
    openwrt-ipq806x-generic-netgear-r7800.manifest
    openwrt-ipq806x-generic-netgear_r7800-squashfs-factory.img
    openwrt-ipq806x-generic-netgear_r7800-squashfs-sysupgrade.bin

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Should be the same for ipq40xx ...

**Review by adschm — APPROVED** [review]
Well, whether this should be done is essentially a philosophical question, but

> For consistency created files are stored in `ipq806x/generic`, this patch does the same to filenames.

if folders are already set like this, then we indeed should also fix names accordingly.

As with your other PRs, one might ask the question whether one shouldn't fix this problem where it originates, and introduce a "generic" subtarget for the targets in the first place.

**Comment by aparcar** [comment]
> As with your other PRs, one might ask the question whether one shouldn't fix this problem where it originates, and introduce a "generic" subtarget for the targets in the first place.

I guess you're right. I've just checked the produced JSON and it's broken this way. https://aparcar.stephen304.com/download/json-demo/openwrt/snapshots/targets/ipq40xx/generic/openwrt-ipq40xx-zyxel_wre6606.json

**Comment by aparcar** [comment]
Superseded by https://patchwork.ozlabs.org/patch/1151231/

**Pull request closed without merging**
