### PR TITLE
bpf related changes

### PR DESCRIPTION
**Pull request by stintel**
See https://patchwork.ozlabs.org/project/openwrt/list/?series=288137

### CODE REVIEW

**Comment by aparcar** [comment]
Is this added for CI reasons?

**Comment by stintel** [comment]
Yes, to test reported breakage with dwarves. But it's not built by default, and has a dependency on !HOST_OS_MACOS so that probably wasn't very useful. I've reproduced the problem in an Ubuntu VM.

**Comment by aparcar** [comment]
CI runs on Ubuntu per default as well. Since we never merge PRs from GitHub directly, I usually add testing commits which add the needed config options.

**Comment by stintel** [comment]
Doesn't matter, dwarves depends on CONFIG_DWARVES=y, so CI doesn't try to build it.

**Comment by stintel** [comment]
@Ansuel would you mind testing this?

**Comment by Ansuel** [comment]
@stintel dwarves now correctly compile and doesn't require system package as dependency

**Comment by stintel** [comment]
@lucize heads-up: once this lands, frr should depend on CONFIG_USE_ELFUTILS rather than using `PKG_BUILD_DEPENDS:=frr/host`.

**Comment by stintel** [comment]
> @stintel it's just that I don't seem to understand how to use this

Same problem here, I was thinking DEPENDS+=@CONFIG_USE_ELFUTILS or something like that but it also didn't work.

**Comment by lucize** [comment]
something like
elf.h:10:10: fatal error: gelf.h: No such file or directory

**Comment by lucize** [comment]
also ncurses host throws this

```
make[5]: Entering directory '/home/build/proxy/build_dir/hostpkg/ncurses-6.3/progs'
/home/build/proxy/staging_dir/host/bin/install -c -s tic     /home/build/proxy/staging_dir/hostpkg/bin/`echo tic|       sed 's/$//'|sed 's,$,,;s,^,,'|sed 's/$//'`
strip: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory
/home/build/proxy/staging_dir/host/bin/install: strip process terminated abnormally
make[5]: *** [Makefile:219: install.progs] Error 1
make[5]: Leaving directory '/home/build/proxy/build_dir/hostpkg/ncurses-6.3/progs'

```

**Comment by stintel** [comment]
@lucize thanks for your feedback, I have changed tools/elfutils to build unconditionally.

**Comment by lucize** [comment]
@stintel 
don't know what is missing on my build system but I still get this

```
ln -fs i486-openwrt-linux-musl-gdb /home/build/ha_via/staging_dir/toolchain-i386_pentium4_gcc-11.2.0_musl/bin/i486-openwrt-linux-gdb
strip /home/build/ha_via/staging_dir/toolchain-i386_pentium4_gcc-11.2.0_musl/bin/i486-openwrt-linux-musl-gdb
strip: error while loading shared libraries: libdw.so.1: cannot open shared object file: No such file or directory
make[3]: *** [Makefile:76: /home/build/ha_via/staging_dir/toolchain-i386_pentium4_gcc-11.2.0_musl/stamp/.gdb_installed] Error 127
make[3]: Leaving directory '/home/build/ha_via/toolchain/gdb'
time: toolchain/gdb/compile#0.01#0.02#0.03
    ERROR: toolchain/gdb failed to build.
make[2]: *** [toolchain/Makefile:97: toolchain/gdb/compile] Error 1
make[2]: *** Waiting for unfinished jobs....

```

**Comment by stintel** [comment]
> of course installing elfutils from OS passes this, but I guess this is not how is indented to work

Indeed, that's not how it's intended to work. Someone else is reporting the same issue on IRC, but the buildbots seem fine so far... I've asked to try `make tools/elfutils/compile` and retry...

**Comment by lucize** [comment]
I have the a and so files the `staging_dir/host/lib` already

**Comment by stintel** [comment]
I have no issues on Ubuntu 20.04 after make dirclean.

**Comment by lucize** [comment]
I used dirclean from start also

**Comment by stintel** [comment]
What distro are you building on?

**Comment by lucize** [comment]
debian 10

**Comment by stintel** [comment]
Can reproduce it in a Debian 10 container:

```
build@be1c232eded0:/owrt/openwrt$ ldd ./staging_dir/host/bin/strip
        linux-vdso.so.1 (0x00007ffec8585000)
        libelf.so.1 => /usr/lib/x86_64-linux-gnu/libelf.so.1 (0x00007f2719e8b000)
        libdw.so.1 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2719ccb000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2719aad000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2719f04000)
```

The problem is that elfutils installs staging_dir/host/bin/strip without pointing LDFLAGS to staging_dir/host/lib, and when something tries to use that strip on a host system without libdw that doesn't work.

We could fix HOST_LDFLAGS but I'd rather just not have elfutils install strip, so that binutils strip will always be used. Unfortunately that doesn't seem possible without patching the elfutils source, or overriding the host install macro. I'm off to bed, if anyone comes up with a clean way to fix it, be my guest.

**Pull request closed without merging**
