### PR TITLE
openssl: move engine.mk to INCLUDE_DIR

### PR DESCRIPTION
**Pull request by cotequeiroz**
engine.mk is supposed to be included by engine packages, but it will not be present in the same place in the main repository (`$(TOPDIR)/package/libs/openssl`), and in the SDK (`$(TOPDIR)/feeds/base/libs/openssl`, with symlink at `$(TOPDIR)/package/feeds/base/openssl`).

Move it to include/openssl-engine.mk to avoid this.

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

Built & Tested on mediatek/mt7622/Linksys E8450/master, using afalg and gost engines with openwrt/packages#18132 applied.

OpenSSL & engine packages were additionally test-built with the resulting SDK.

_**This should be cherry-picked to 22.03.**_

### CODE REVIEW

**Comment by aparcar** [comment]
Bump the PKG_RELEASE or set it to $(AUTORELEASE)

**Comment by cotequeiroz** [comment]
OK.  I've set it to `$(AUTORELEASE)`.

**Comment by aparcar** [comment]
Thank you!

**Comment by aparcar** [comment]
Uhm, while at it could you please add a SPDX header to the file like all other files in include/ should have one?

**Comment by cotequeiroz** [comment]
Done.

**Comment by aparcar** [comment]
Thanks, merged!

**Comment by cotequeiroz** [comment]
@aparcar, do we need to do anything for the buildbots SDK to pick up the new `include/openssl-engine.mk` addition:
```
Makefile:400: WARNING: skipping libopenssl-afalg -- package has no install section
Makefile:401: WARNING: skipping libopenssl-devcrypto -- package has no install section
Makefile:67: /builder/shared-workdir/build/sdk/include/openssl-engine.mk: No such file or directory
make[3]: *** No rule to make target '/builder/shared-workdir/build/sdk/include/openssl-engine.mk'.  Stop.
time: package/feeds/base/openssl/compile#0.44#0.10#0.66
```
I've double-checked, and the file is installed to the SDK tarball:
```
src/openwrt $ tar tJvf bin/targets/mediatek/mt7622/openwrt-sdk-mediatek-mt7622_gcc-11.2.0_musl.Linux-x86_64.tar.xz openwrt-sdk-mediatek-mt7622_gcc-11.2.0_musl.Linux-x86_64/include/openssl-engine.mk
-rw-r--r-- cotequeiroz/devel  1223 2022-03-22 14:03 openwrt-sdk-mediatek-mt7622_gcc-11.2.0_musl.Linux-x86_64/include/openssl-engine.mk
```

**Comment by ynezz** [comment]
@cotequeiroz Indeed, seems like it broke something somewhere, I've noticed following `ustream-ssl` project issues in my mailbox today:

* [Job build with Freescale i.MX 6 SDK (out of tree)](https://gitlab.com/openwrt/project/ustream-ssl/-/jobs/2248323357)
* [Job build with Marvell Armada Cortex A-53 SDK (out of tree)](https://gitlab.com/openwrt/project/ustream-ssl/-/jobs/2248323357)

I've tried to reproduce it locally with following:

```
git clone https://git.openwrt.org/project/ustream-ssl.git
docker run --volume $(pwd)/ustream-ssl:/build --rm -it openwrt/sdk:mvebu-cortexa53-snapshot sh -c "export CI_TARGET_BUILD_DEPENDS='libubox openssl' && wget -q https://gitlab.com/ynezz/openwrt-ci/raw/master/Makefile -O Makefile.ci && make ci-prepare -f Makefile.ci && make ci-sdk-oot-build -f Makefile.ci"
```
and it works, I'm not able to reproduce it and I'm not seeing this error locally either:

```
ERROR: please fix feeds/base/package/libs/openssl/Makefile - see logs/feeds/base/package/libs/openssl/dump.txt for details
```

**Comment by ynezz** [comment]
Ok, so I'm able to reproduce it with following ` openwrt/sdk:imx6-generic-snapshot` container:

```shell
git clone https://git.openwrt.org/project/ustream-ssl.git
docker run \
  --rm \
  --volume $(pwd)/ustream-ssl:/home/build/source \
  --workdir /home/build/source \
  --env CI_TARGET_BUILD_DEPENDS="libubox openssl" -it openwrt/sdk:imx6-generic-snapshot \
  sh -c "wget -q https://gitlab.com/ynezz/openwrt-ci/raw/master/Makefile -O Makefile.ci && make ci-prepare -f Makefile.ci && make ci-sdk-oot-build -f Makefile.ci"
```

So it looks like this issue is transitory, until all SDKs and containers get rebuild:

```shell
docker run --rm -it openwrt/sdk:imx6-generic-snapshot sh -c "ls -al include/openssl*"
ls: cannot access 'include/openssl*': No such file or directory
```

**Comment by cotequeiroz** [comment]
I imagined something like this.  I did not know how the SDK was rebuilt--[manually, periodically/automatically] [from scratch/using the previous SDK].  If using the previous SDK, it would never fix itself!  I see it is working now.  Every target built from March 25 built the openssl packages just fine.

Even if I had saved the new include file there from the start, it would still cause the failure.  So, the next time I (or someone) needs to do something like this, it needs to be done in steps, like a key rollover:
1. Copy the old file to the new place
2. Wait for the rebuild of SDKs and containers (I don't have an estimate of how long; can/should it be forced?) so that the new file is present in all of them (can the presence be confirmed?).  Any changes to the other feeds should be done at this stage to avoid breakage.
3. Use the new location in base, and remove the old file

I think this could be documented somewhere--it may already be and I just missed it.

Cheers

**Pull request closed without merging**
