### PR TITLE
archs38: add kernel 6.6

### PR DESCRIPTION
**Pull request by namiltd**
Adding kernel 6.6 as test kernel for archs38.

Testing on real hardware required.

### CODE REVIEW

**Comment by namiltd** [comment]
@abrodkin Can you check if this patch works?

**Comment by abrodkin** [comment]
@namiltd works like a charm! Thank you so much for taking care of our platform!
```
nsimdrv -prop=nsim_isa_family=av2hs -prop=nsim_isa_core=3 -prop=chipid=0xffff -prop=nsim_isa_atomic_option=1 -prop=nsim_isa_ll64_option=1 -prop=nsim_mmu=4 -prop=mmu_pagesize=8192 -prop=mmu_super_pagesize=2097152 -prop=mmu_stlb_entries=16 -prop=mmu_ntlb_ways=4 -prop=mmu_ntlb_sets=128 -prop=icache=32768,64,4,0 -prop=dcache=16384,64,2,0 -prop=nsim_isa_shift_option=2 -prop=nsim_isa_swap_option=1 -prop=nsim_isa_bitscan_option=1 -prop=nsim_isa_sat=1 -prop=nsim_isa_div_rem_option=1 -prop=nsim_isa_mpy_option=9 -prop=nsim_isa_enable_timer_0=1 -prop=nsim_isa_enable_timer_1=1 -prop=nsim_isa_number_of_interrupts=32 -prop=nsim_isa_number_of_external_interrupts=32 -prop=isa_counters=1 -prop=nsim_isa_pct_counters=8 -prop=nsim_isa_pct_size=48 -prop=nsim_isa_pct_interrupt=1 -prop=nsim_mem-dev=uart0,kind=dwuart,base=0xf0000000,irq=24 -prop=nsim_isa_aps_feature=1 -prop=nsim_isa_num_actionpoints=4 -prop=nsim_isa_rtc_option=1 -prop=nsim_isa_fpud_option=1 bin/targets/archs38/generic-glibc/openwrt-archs38-generic-nsim_hs-initramfs.elf

[    0.000000] Linux version 6.6.41 (abrodkin@SNPS-Ecl1TeCeXg) (arc-openwrt-linux-gnu-gcc (OpenWrt GCC 13.3.0 r27001-ccc5fd6a4a) 13.3.0, GNU ld (GNU Binutils) 2.42) #0 SMP PREEMPT Fri Jul 26 00:31:30 2024
[    0.000000] Memory @ 80000000 [1024M]
[    0.000000] Memory @ 100000000 [1024M] Not used
[    0.000000] OF: fdt: Machine model: snps,zebu_hs
[    0.000000] earlycon: uart8250 at MMIO32 0xf0000000 (options '115200n8')
[    0.000000] printk: bootconsole [uart8250] enabled
[    0.000000] Failed to get possible-cpus from dtb, pretending all 4 cpus exist
[    0.000000]
[    0.000000] IDENTITY : ARCVER [0x53] ARCNUM [0x0] CHIPID [0xffff]
[    0.000000] processor [0]    : HS38 R3.0 (ARCv2 ISA)
[    0.000000] ISA Extn : atomic ll64 unalign mpy[opt 9] div_rem   FPU: sp dp
[    0.000000] BPU              : partial match, cache:2048, Predict Table:16384 Return stk: 8P
[    0.000000] MMU [v4] : 8k/2M, swalk 2 lvl, JTLB 128x4, uDTLB 8, uITLB 4, SASID
[    0.000000] I-Cache          : 32K, 4way/set, 64B Line, VIPT
[    0.000000] D-Cache          : 16K, 2way/set, 64B Line, PIPT
[    0.000000] Peripherals      : 0xc0000000
[    0.000000] Timers           : Timer0 Timer1 RTC [UP 64-bit]
[    0.000000] Vector Table     : 0x90006000
[    0.000000] DEBUG            : ActionPoint 4/full
[    0.000000] Extn [SMP]       : ARConnect (v0): 0 cores with
[    0.000000] archs-intc       : 15 priority levels (default 1)
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000080000000-0x00000000bfffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080000000-0x00000000bfffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080000000-0x00000000bfffffff]
[    0.000000] percpu: Embedded 6 pages/cpu s19072 r8192 d21888 u49152
[    0.000000] pcpu-alloc: s19072 r8192 d21888 u49152 alloc=6*8192
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Kernel command line: earlycon=uart8250,mmio32,0xf0000000,115200n8 console=ttyS0,115200n8 debug print-fatal-signals=1
[    0.000000] Dentry cache hash table entries: 131072 (order: 6, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 5, 262144 bytes, linear)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 130432
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 1025304K/1048576K available (5222K kernel code, 659K rwdata, 1704K rodata, 7736K init, 267K bss, 23272K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=128, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000]  Trampoline variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 512
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] Local-64-bit-Ctr not usable in SMP
[    0.000000] Failed to initialize '/rtc': -22
[    0.000000] Failed to initialize '/timer1': -22
[    0.000000] sched_clock: 32 bits at 100 Hz, resolution 10000000ns, wraps every 21474836475000000ns
[    0.000000] Calibrating delay loop... 99.22 BogoMIPS (lpj=496128)
[    0.090000] pid_max: default: 32768 minimum: 301
[    0.310000] Mount-cache hash table entries: 2048 (order: 0, 8192 bytes, linear)
[    0.310000] Mountpoint-cache hash table entries: 2048 (order: 0, 8192 bytes, linear)
[    0.490000] RCU Tasks: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1.
[    0.490000] RCU Tasks Trace: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1.
[    0.490000] rcu: Hierarchical SRCU implementation.
[    0.490000] rcu:     Max phase no-delay instances is 1000.
[    0.490000] smp: Bringing up secondary CPUs ...
[    0.490000] Idle Task [1] (ptrval)
[    0.490000] Trying to bring up CPU1 ...
[    1.500000] Timeout: CPU1 FAILED to come up !!!
[    1.500000] Idle Task [2] (ptrval)
[    1.500000] Trying to bring up CPU2 ...
[    2.500000] Timeout: CPU2 FAILED to come up !!!
[    2.500000] Idle Task [3] (ptrval)
[    2.500000] Trying to bring up CPU3 ...
[    3.500000] Timeout: CPU3 FAILED to come up !!!
[    3.500000] smp: Brought up 1 node, 1 CPU
[    3.530000] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    3.530000] futex hash table entries: 1024 (order: 4, 131072 bytes, linear)
[    3.690000] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    3.690000] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[    3.850000] SCSI subsystem initialized
[    3.850000] pps_core: LinuxPPS API ver. 1 registered
[    3.850000] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    3.850000] PTP clock support registered
[    4.110000] NET: Registered PF_INET protocol family
[    4.110000] IP idents hash table entries: 16384 (order: 4, 131072 bytes, linear)
[    4.140000] tcp_listen_portaddr_hash hash table entries: 1024 (order: 0, 8192 bytes, linear)
[    4.140000] Table-perturb hash table entries: 65536 (order: 5, 262144 bytes, linear)
[    4.140000] TCP established hash table entries: 8192 (order: 2, 32768 bytes, linear)
[    4.140000] TCP bind hash table entries: 8192 (order: 4, 131072 bytes, linear)
[    4.140000] TCP: Hash tables configured (established 8192 bind 8192)
[    4.140000] UDP hash table entries: 512 (order: 1, 16384 bytes, linear)
[    4.140000] UDP-Lite hash table entries: 512 (order: 1, 16384 bytes, linear)
[    4.160000] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    4.160000] RPC: Registered named UNIX socket transport module.
[    4.160000] RPC: Registered udp transport module.
[    4.160000] RPC: Registered tcp transport module.
[    4.160000] RPC: Registered tcp-with-tls transport module.
[    4.160000] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    4.230000] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    4.910000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    5.110000] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    5.170000] jitterentropy: Initialization failed with host not compliant with requirements: 2
[    5.190000] simple-pm-bus fpga: use noncoherent DMA ops
[    5.210000] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    5.240000] of_serial f0000000.serial: use noncoherent DMA ops
[    5.240000] printk: console [ttyS0] disabled
[    5.240000] f0000000.serial: ttyS0 at MMIO 0xf0000000 (irq = 24, base_baud = 3125000) is a 16550A
[    5.240000] printk: console [ttyS0] enabled
[    5.240000] printk: console [ttyS0] enabled
[    5.240000] printk: bootconsole [uart8250] disabled
[    5.240000] printk: bootconsole [uart8250] disabled
[    5.440000] brd: module loaded
[    5.490000] sdhci: Secure Digital Host Controller Interface driver
[    5.490000] sdhci: Copyright(c) Pierre Ossman
[    5.490000] Synopsys Designware Multimedia Card Interface Driver
[    5.490000] sdhci-pltfm: SDHCI platform and OF driver helper
[    5.530000] NET: Registered PF_INET6 protocol family
[    5.540000] Segment Routing with IPv6
[    5.540000] In-situ OAM (IOAM) with IPv6
[    5.540000] NET: Registered PF_PACKET protocol family
[    5.540000] 8021q: 802.1Q VLAN Support v1.8
[    5.840000] clk: Disabling unused clocks
[    5.870000] Freeing unused kernel image (initmem) memory: 7736K
[    5.870000] This architecture does not have kernel memory protection.
[    5.870000] Run /init as init process
[    5.870000]   with arguments:
[    5.870000]     /init
[    5.870000]   with environment:
[    5.870000]     HOME=/
[    5.870000]     TERM=linux
[    7.170000] init: Console is alive
[    7.200000] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    7.250000] usbcore: registered new interface driver usbfs
[    7.250000] usbcore: registered new interface driver hub
[    7.250000] usbcore: registered new device driver usb
[    7.280000] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    7.290000] init: - preinit -
[  255.050000] random: crng init done
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[  258.390000] procd: - early -
[  259.150000] procd: - ubus -
[  259.310000] procd: - init -
Please press Enter to activate this console.
[  263.590000] kmodloader: loading kernel modules from /etc/modules.d/*
[  263.650000] compat: loading out-of-tree module taints kernel.
[  263.650000] Loading modules backported from Linux version v6.9.9-0-g28fdf4518483
[  263.650000] Backport generated by backports.git v6.1.97-1-29-gf1d24a3683b2
[  264.340000] usbcore: registered new interface driver ath9k_htc
[  264.340000] kmodloader: done loading kernel modules from /etc/modules.d/*



BusyBox v1.36.1 (2024-07-26 00:31:30 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r27001-ccc5fd6a4a
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@(none):/# uname -a
Linux (none) 6.6.41 #0 SMP PREEMPT Fri Jul 26 00:31:30 2024 arc GNU/Linux
root@(none):/#
```

**Comment by namiltd** [comment]
Ping @robimarko

**Comment by robimarko** [comment]
@abrodkin Did secondary CPU bringup fail before as well?

```
[    0.490000] smp: Bringing up secondary CPUs ...
[    0.490000] Idle Task [1] (ptrval)
[    0.490000] Trying to bring up CPU1 ...
[    1.500000] Timeout: CPU1 FAILED to come up !!!
[    1.500000] Idle Task [2] (ptrval)
[    1.500000] Trying to bring up CPU2 ...
[    2.500000] Timeout: CPU2 FAILED to come up !!!
[    2.500000] Idle Task [3] (ptrval)
[    2.500000] Trying to bring up CPU3 ...
[    3.500000] Timeout: CPU3 FAILED to come up !!!
[    3.500000] smp: Brought up 1 node, 1 CPU
```

**Comment by namiltd** [comment]
@robimarko Yes: https://github.com/openwrt/openwrt/pull/14794#issuecomment-2002456035

**Comment by robimarko** [comment]
@namiltd Replace the local regmap patch (BTW, please do not post plain diffs, always post patches output by git format patch and with proper description) with the upstream backport:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/base/regmap/regcache-maple.c?h=next-20240726&id=542440fd7b30983cae23e32bd22f69a076ec7ef4

And put it in generic since it affects all targets.

**Comment by namiltd** [comment]
Of course I would if I found this code. I created the patch myself and the result was exactly the same because it is not complicated.

**Comment by abrodkin** [comment]
> @abrodkin Did secondary CPU bringup fail before as well?
> 
> ```
> [    0.490000] smp: Bringing up secondary CPUs ...
> [    0.490000] Idle Task [1] (ptrval)
> [    0.490000] Trying to bring up CPU1 ...
> [    1.500000] Timeout: CPU1 FAILED to come up !!!
> [    1.500000] Idle Task [2] (ptrval)
> [    1.500000] Trying to bring up CPU2 ...
> [    2.500000] Timeout: CPU2 FAILED to come up !!!
> [    2.500000] Idle Task [3] (ptrval)
> [    2.500000] Trying to bring up CPU3 ...
> [    3.500000] Timeout: CPU3 FAILED to come up !!!
> [    3.500000] smp: Brought up 1 node, 1 CPU
> ```

Right, I did instantiate only 1 core in simulation as it makes execution in our proprietary simulator much faster. And unfortunately our QEMU port for ARC doesn't support SMP emulaion at all. So that's fine.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
