### PR TITLE
realtek: Fix self assignment

### PR DESCRIPTION
**Pull request by qarmin**
Signed-off-by: Rafał Mikrut mikrutrafal@protonmail.com

### CODE REVIEW

**Comment by adschm** [comment]
Same comments as for you other PR apply.

**Review by mtdcr — APPROVED** [review]
RTL8390_FAMILY_ID uses RTL839X_LED_GLB_CTRL, so this change looks good to me.

**Comment by svanheule** [comment]
Looking at the [LED_GLB_CTRL documentation](https://biot.com/switches/led_control), the use of this register as a GPIO register really isn't right. Although this patch does expose the correct register at GPIOs 32-63, it should be really be put in a separate pin controller.

I am currently reworking the (internal and external) GPIO driver, which will delete the code affected here anyway. Currently I'm stil figuring out how implement the IRQs correctly, but I think it should be ready soon. A new pin control driver for the LEB_GLB_CONTROL register should also be feasible on short notice.

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/openwrt/openwrt/commit/848d668427c544d20f8aa3041fa11b4d4adc9bc8

**Pull request closed without merging**
