### PR TITLE
layerscape: switch to 5.10 Kernel

### PR DESCRIPTION
**Pull request by aparcar**
This is just a placeholder to share test results

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
Support added via 7e35d86ca2d272a9ae484f08e75625c24ea80a37

**Comment by hauke** [comment]
@sch-m @CHKDSK88 @yangbolu1991 @mcbridematt Could you please check if kernel 5.10 works fine on your boards and report back.

**Comment by CHKDSK88** [comment]
On LS1012A-FRDM ethernet won't work. 

```[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.10.89 (Y@X) (aarch64-openwrt-linux-musl-gcc (OpenWrt GCC 11.2.0 r18472-ef1a64caf40e) 11.2.0, GNU ld (GNU Binutils) 2.37) #0 SMP PREEMPT Wed Jan 5 00:57:43 2022
[    0.000000] Machine model: LS1012A Freedom Board
[    0.000000] earlycon: uart8250 at MMIO 0x00000000021c0500 (options '')
[    0.000000] printk: bootconsole [uart8250] enabled
[    0.000000] NUMA: No NUMA configuration found
[    0.000000] NUMA: Faking a node at [mem 0x0000000080000000-0x000000009bdfffff]
[    0.000000] NUMA: NODE_DATA [mem 0x9bd10100-0x9bd11fff]
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000080000000-0x000000009bdfffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080000000-0x000000009bdfffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080000000-0x000000009bdfffff]
[    0.000000] On node 0 totalpages: 114176
[    0.000000]   DMA zone: 1784 pages used for memmap
[    0.000000]   DMA zone: 0 pages reserved
[    0.000000]   DMA zone: 114176 pages, LIFO batch:31
[    0.000000] cma: Reserved 16 MiB at 0x0000000099000000
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.1
[    0.000000] percpu: Embedded 22 pages/cpu s51480 r8192 d30440 u90112
[    0.000000] pcpu-alloc: s51480 r8192 d30440 u90112 alloc=22*4096
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 112392
[    0.000000] Policy zone: DMA
[    0.000000] Kernel command line: rootfstype=squashfs,jffs2 noinitrd earlycon=uart8250,mmio,0x21c0500 console=ttyS0,115200 mtdparts=1550000.spi:1m(bl2),4m(fip),1m(u-boot-env),4m(reserved-1),3m(pfe),2m(reserved-2),1m(dtb),-(firmware)
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 385292K/456704K available (10750K kernel code, 1128K rwdata, 2816K rodata, 9344K init, 345K bss, 55028K reserved, 16384K cma-reserved)
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=64 to nr_cpu_ids=1.
[    0.000000]  Trampoline variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] random: get_random_bytes called from start_kernel+0x348/0x4d4 with crng_init=0
[    0.000000] arch_timer: cp15 timer(s) running at 25.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x5c40939b5, max_idle_ns: 440795202646 ns
[    0.000005] sched_clock: 56 bits at 25MHz, resolution 40ns, wraps every 4398046511100ns
[    0.008510] Console: colour dummy device 80x25
[    0.013085] Calibrating delay loop (skipped), value calculated using timer frequency.. 50.00 BogoMIPS (lpj=250000)
[    0.023583] pid_max: default: 32768 minimum: 301
[    0.028445] Mount-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.035861] Mountpoint-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.045387] rcu: Hierarchical SRCU implementation.
[    0.050462] dyndbg: Ignore empty _ddebug table in a CONFIG_DYNAMIC_DEBUG_CORE build
[    0.058433] smp: Bringing up secondary CPUs ...
[    0.063059] smp: Brought up 1 node, 1 CPU
[    0.067115] SMP: Total of 1 processors activated.
[    0.071881] CPU features: detected: 32-bit EL0 Support
[    0.077101] CPU features: detected: CRC32 instructions
[    0.082351] CPU features: emulated: Privileged Access Never (PAN) using TTBR0_EL1 switching
[    0.092257] CPU: All CPU(s) started at EL2
[    0.096406] alternatives: patching kernel code
[    0.104828] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.115190] futex hash table entries: 256 (order: 2, 16384 bytes, linear)
[    0.124102] NET: Registered protocol family 16
[    0.130890] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[    0.138142] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.146205] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.156772] thermal_sys: Registered thermal governor 'step_wise'
[    0.157133] cpuidle: using governor menu
[    0.170240] ASID allocator initialised with 65536 entries
[    0.176129] Serial: AMBA PL011 UART driver
[    0.193866] Machine: LS1012A Freedom Board
[    0.198018] SoC family: QorIQ LS1012A
[    0.202686] SoC ID: svr:0x87040010, Revision: 1.0
[    0.256611] HugeTLB registered 1.00 GiB page size, pre-allocated 0 pages
[    0.264136] HugeTLB registered 32.0 MiB page size, pre-allocated 0 pages
[    0.270926] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    0.278242] HugeTLB registered 64.0 KiB page size, pre-allocated 0 pages
[    0.289762] raid6: skip pq benchmark and using algorithm neonx8
[    0.295759] raid6: using neon recovery algorithm
[    0.309778] iommu: Default domain type: Passthrough
[    0.315744] vgaarb: loaded
[    0.319183] SCSI subsystem initialized
[    0.323634] libata version 3.00 loaded.
[    0.324728] imx-i2c 2180000.i2c: can't get pinctrl, bus recovery not supported
[    0.334451] i2c i2c-0: IMX I2C adapter registered
[    0.340287] pps_core: LinuxPPS API ver. 1 registered
[    0.345966] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.355330] PTP clock support registered
[    0.363178] clocksource: Switched to clocksource arch_sys_counter
[    0.370080] VFS: Disk quotas dquot_6.6.0
[    0.374311] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.397999] NET: Registered protocol family 2
[    0.402564] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.414397] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.422884] TCP established hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.431309] TCP bind hash table entries: 4096 (order: 4, 65536 bytes, linear)
[    0.438691] TCP: Hash tables configured (established 4096 bind 4096)
[    0.445289] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.451918] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.459239] NET: Registered protocol family 1
[    0.463686] PCI: CLS 0 bytes, default 64
[    0.529755] workingset: timestamp_bits=44 max_order=17 bucket_order=0
[    0.537545] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.543647] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.554000] fuse: init (API version 7.32)
[    0.558561] SGI XFS with security attributes, realtime, no debug enabled
[    0.566320] xor: measuring software checksum speed
[    0.577532]    8regs           :  1577 MB/sec
[    0.587267]    32regs          :  1868 MB/sec
[    0.597903]    arm64_neon      :  1584 MB/sec
[    0.602313] xor: using function: 32regs (1868 MB/sec)
[    0.607609] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    0.619527] rcpm 1ee2140.power-controller: can't request region for resource [mem 0x01ee2140-0x01ee2143]
[    0.632494] rcpm: probe of 1ee2140.power-controller failed with error -16
[    0.640434] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.649930] printk: console [ttyS0] disabled
[    0.656286] 21c0500.serial: ttyS0 at MMIO 0x21c0500 (irq = 21, base_baud = 7812500) is a 16550A
[    0.665392] printk: console [ttyS0] enabled
[    0.674032] printk: bootconsole [uart8250] disabled
[    0.685674] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.707716] brd: module loaded
[    0.718885] loop: module loaded
[    0.728214] spi-nor spi0.0: Failed to parse optional parameter table: ff81
[    0.735486] spi-nor spi0.0: s25fs512s (65536 Kbytes)
[    0.740502] 8 cmdlinepart partitions found on MTD device 1550000.spi
[    0.747164] Creating 8 MTD partitions on "1550000.spi":
[    0.752403] 0x000000000000-0x000000100000 : "bl2"
[    0.757864] 0x000000100000-0x000000500000 : "fip"
[    0.764009] 0x000000500000-0x000000600000 : "u-boot-env"
[    0.770381] 0x000000600000-0x000000a00000 : "reserved-1"
[    0.776792] 0x000000a00000-0x000000d00000 : "pfe"
[    0.782669] 0x000000d00000-0x000000f00000 : "reserved-2"
[    0.789102] 0x000000f00000-0x000001000000 : "dtb"
[    0.795081] 0x000001000000-0x000004000000 : "firmware"
[    0.801701] 2 fit-fw partitions found on MTD device firmware
[    0.807799] 0x000001000000-0x000001672000 : "kernel"
[    0.813691] 0x000001680000-0x000004000000 : "rootfs"
[    0.819842] mtd: device 9 (rootfs) set to be root filesystem
[    0.825970] 1 squashfs-split partitions found on MTD device rootfs
[    0.832172] 0x0000019f9000-0x000004000000 : "rootfs_data"
[    0.848306] libphy: Fixed MDIO Bus: probed
[    0.869599] VFIO - User Level meta-driver version: 0.3
[    0.878353] mousedev: PS/2 mouse device common for all mice
[    0.887095] ftm-alarm 29d0000.timer: registered as rtc1
[    0.894774] i2c /dev entries driver
[    0.911323] qoriq-cpufreq qoriq-cpufreq: Freescale QorIQ CPU frequency scaling driver
[    0.921399] sdhci: Secure Digital Host Controller Interface driver
[    0.928793] sdhci: Copyright(c) Pierre Ossman
[    0.933326] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.939717] caam 1700000.crypto: RNG4 SH0 was previously instantiated without prediction resistance. Tearing it down
[    0.950747] caam 1700000.crypto: Deinstantiated RNG4 SH0
[    0.956126] caam 1700000.crypto: Instantiated RNG4 SH0
[    0.988211] caam 1700000.crypto: Instantiated RNG4 SH1
[    0.993386] caam 1700000.crypto: device ID = 0x0a14040000000000 (Era 8)
[    1.000013] caam 1700000.crypto: job rings = 3, qi = 0
[    1.015082] caam algorithms registered in /proc/crypto
[    1.021784] caam 1700000.crypto: caam pkc algorithms registered in /proc/crypto
[    1.029249] caam 1700000.crypto: registering rng-caam
[    1.037572] cbus_baseaddr: ffff800014000000, ddr_baseaddr: ffff000003400000, ddr_phys_baseaddr: 83400000, ddr_size: c00000
[    1.051444] pfe_hw_init
[    1.054119] CLASS version: 20
[    1.057092] TMU version: 1011231
[    1.060322] BMU1 version: 21
[    1.063391] BMU2 version: 21
[    1.066273] EGPI1 version: 50
[    1.069274] EGPI2 version: 50
[    1.072242] HGPI version: 50
[    1.075154] HIF version: 10
[    1.077948] HIF NOPCY version: 10
[    1.081268] bmu_init(1) done
[    1.084196] bmu_init(2) done
[    1.089322] class_init() done
[    1.102326] tmu_init() done
[    1.105133] gpi_init(1) done
[    1.108016] gpi_init(2) done
[    1.110899] gpi_init(hif) done
[    1.113962] bmu_enable(1) done
[    1.117017] bmu_enable(2) done
[    1.120072] pfe_hif_lib_init
[    1.123235] pfe_hif_init
[    1.125770] pfe_hif_alloc_descr
[    1.129125] pfe_hif_init_buffers
[    1.133153] pfe_firmware_init
[    1.136210] Failed to find the node
[    1.139701] pfe_firmware_init:PFE firmware not found in FDT.
[    1.145378] pfe_firmware_init:Trying to load firmware from filesystem...!
[    1.152472] pfe_load_elf
[    1.155058] pe_load_ddr_section: load address(3fb0000) and elf file address(ffff80001322f000) rcvd
[    1.187393] PFE binary version: pfe_ls1012a_slowpath_10
[    1.192627] pfe_load_elf
[    1.195305] random: fast init done
[    1.199644] pfe_ctrl_init
[    1.202265] pfe_ctrl_init finished
[    1.205679] pfe_eth_init
[    1.208227] pfe 4000000.pfe: pfe_eth_mdio_init: mdc_div: 64, phy_mask: fffffff9
[    1.228155] libphy: ls1012a MDIO Bus: probed
[    1.232456] pfe 4000000.pfe: pfe_eth_mdio_init: mdc_div: 64, phy_mask: fffffff9
[    1.251918] libphy: ls1012a MDIO Bus: probed
[    1.259558] random: crng init done
[    1.264164] pfe_phy_init interface 4
[    1.303239] pfe 4000000.pfe eth0: pfe_eth_init_one: created interface, baseaddr: 000000001b4e9505
[    1.315958] pfe_phy_init interface 4
[    1.353258] pfe 4000000.pfe eth1: pfe_eth_init_one: created interface, baseaddr: 00000000b8c16019
[    1.362222] pfe_debugfs_init
[    1.366247] NET: Registered protocol family 10
[    1.372374] Segment Routing with IPv6
[    1.376211] NET: Registered protocol family 17
[    1.380705] 8021q: 802.1Q VLAN Support v1.8
[    1.387942] Btrfs loaded, crc32c=crc32c-generic
[    1.405711] Freeing unused kernel memory: 9344K
[    1.433318] Run /init as init process
[    1.436992]   with arguments:
[    1.436996]     /init
[    1.437000]   with environment:
[    1.437003]     HOME=/
[    1.437007]     TERM=linux
[    1.633710] init: Console is alive
[    1.637334] init: - watchdog -
[    1.646340] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    1.662692] usbcore: registered new interface driver usbfs
[    1.668654] usbcore: registered new interface driver hub
[    1.674412] usbcore: registered new device driver usb
[    1.690426] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller
[    1.696483] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus number 1
[    1.704620] xhci-hcd xhci-hcd.1.auto: hcc params 0x0220f66d hci version 0x100 quirks 0x0000000002010010
[    1.714227] xhci-hcd xhci-hcd.1.auto: irq 27, io mem 0x02f00000
[    1.721050] hub 1-0:1.0: USB hub found
[    1.725217] hub 1-0:1.0: 1 port detected
[    1.729671] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller
[    1.735603] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus number 2
[    1.743372] xhci-hcd xhci-hcd.1.auto: Host supports USB 3.0 SuperSpeed
[    1.750041] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[    1.759108] hub 2-0:1.0: USB hub found
[    1.763515] hub 2-0:1.0: 1 port detected
[    1.771477] usbcore: registered new interface driver usb-storage
[    1.778118] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    1.788128] init: - preinit -
[    1.913331] usb usb1-port1: over-current condition
[    2.114342] usb usb2-port1: over-current condition
[    2.243058] pfe 4000000.pfe eth0: pfe_eth_open
[    2.258194] hif_process_client_req: register client_id 0
[    2.263534] pfe_hif_client_register
[    2.281612] pfe 4000000.pfe eth0: pfe_gemac_init
[    2.334355] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    6.530147] pfe 4000000.pfe eth0: pfe_eth_shutdown
[    6.588805] hif_lib_client_unregister : client: 00000000933bbe8d, client_id: 0, txQ_depth: 2048, rxQ_depth: 256
[    6.629323] hif_process_client_req: unregister client_id 0
[    6.634830] pfe_hif_client_unregister
[    6.670361] procd: - early -
[    6.682713] procd: - watchdog -
[    7.440209] procd: - watchdog -
[    7.444266] procd: - ubus -
[    7.498970] procd: - init -
[    8.049583] kmodloader: loading kernel modules from /etc/modules.d/*
[    8.130872] urngd: v1.0.2 started.
[    8.225358] xt_time: kernel timezone is -0000
[    8.307865] PPP generic driver version 2.4.2
[    8.340038] NET: Registered protocol family 24
[    8.404460] kmodloader: done loading kernel modules from /etc/modules.d/*
[   17.529551] pfe 4000000.pfe eth0: pfe_eth_open
[   17.568839] hif_process_client_req: register client_id 0
[   17.574231] pfe_hif_client_register
[   17.634625] pfe 4000000.pfe eth0: pfe_gemac_init
[   17.703697] br-lan: port 1(eth0) entered blocking state
[   17.708947] br-lan: port 1(eth0) entered disabled state
[   17.761258] device eth0 entered promiscuous mode
[   17.871718] pfe 4000000.pfe eth1: pfe_eth_open
[   17.894789] hif_process_client_req: register client_id 1
[   17.900141] pfe_hif_client_register
[   17.943556] pfe 4000000.pfe eth1: pfe_gemac_init
[   22.153824] pfe 4000000.pfe eth1: Link is Up - 1Gbps/Full - flow control off
```


I have LS1046A-RDB and LS1012A-RDB. But I will test it in the future.

**Comment by sch-m** [comment]
I'll do some tests tomorrow with a LS1046A-RDB and a FRWY-LS1046A.

@CHKDSK88 Can you please try if adding this 2 patches to the 5.10 tree fixes your problem:
https://github.com/openwrt/openwrt/blob/master/target/linux/layerscape/patches-5.4/302-dts-0038-arm64-dts-ls1012a-use-phy-handle-to-handle-phy-param.patch
https://github.com/openwrt/openwrt/blob/master/target/linux/layerscape/patches-5.4/302-dts-0039-arm64-dts-ls1012a-remove-unused-gemac-bus-id.patch

**Comment by sch-m** [comment]
In my (admittedly cursory) tests with the FRWY-LS1046A, I have not encountered any problems so far.
With the LS1046A-RDB, on the other hand, I found a problem with one of the six network interfaces:
```
[    1.122645] fsl_dpaa_mac 1ae4000.ethernet eth0: Probed interface eth0
[    1.130235] fsl_dpaa_mac 1ae6000.ethernet: qman_init_fq(926) = -5
[    1.137668] fsl_dpa dpaa-ethernet.1: qman_retire_fq(926) = -22
[    1.143510] fsl_dpa dpaa-ethernet.1: qman_oos_fq(926) = -22
[    1.545797] fsl_dpa: probe of dpaa-ethernet.1 failed with error -5
[    1.558369] fsl_dpaa_mac 1ae8000.ethernet eth1: Probed interface eth1
[    1.571661] fsl_dpaa_mac 1aea000.ethernet eth2: Probed interface eth2
[    1.587378] fsl_dpaa_mac 1af0000.ethernet eth3: Probed interface eth3
[    1.601870] fsl_dpaa_mac 1af2000.ethernet eth4: Probed interface eth4
```
Sometimes, the interface seems to be initialized fine, but when I try to use it i'll get following error messages:
```
[   39.509218] fsl_dpaa_mac 1ae6000.ethernet eth1: Err FD status = 0x00040000
[   39.562724] fsl_dpaa_mac 1ae6000.ethernet eth1: Err FD status = 0x00080000
```

I'm trying to figure out what's wrong here.

**Comment by CHKDSK88** [comment]
@sch-m 
Patches aren't required. I had issues with my u-boot. Ethernet in LS1012A works in 5.10 kernel.

**Comment by aparcar** [comment]
Merged, thanks for testing!

**Pull request closed without merging**
