### PR TITLE
[23.05}: Fix filogic build 23.05

### PR DESCRIPTION
**Pull request by hauke**
Backport patches to fix filogic build.
See: https://buildbot.openwrt.org/images/#/builders/224

### CODE REVIEW

**Comment by hauke** [comment]
I do not own this device.
Could someone please test this.
 @dangowrt

**Comment by dangowrt** [comment]
Unfortunately the buildbot doesn't show me any logs -- just 0 bytes files, so hard to tell what's wrong there.

**Comment by hauke** [comment]
It fails like this:
````
dd if=/builder/shared-workdir/build/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/tmp/openwrt-23.05-snapshot-r23787-1bbb94df96-mediatek-filogic-mediatek_mt7981-rfb-sdcard.img.gz of=/builder/shared-workdir/build/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/tmp/openwrt-23.05-snapshot-r23787-1bbb94df96-mediatek-filogic-mediatek_mt7981-rfb-sdcard.img.gz.new bs=64M conv=sync
cat: /builder/shared-workdir/build/staging_dir/target-aarch64_cortex-a53_musl/image/mt7986_zyxel_ex5601-t0-u-boot.fip: No such file or directory
dd if=/builder/shared-workdir/build/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/tmp/openwrt-23.05-snapshot-r23787-1bbb94df96-mediatek-filogic-mediatek_mt7988a-rfb-sdcard.img.gz of=/builder/shared-workdir/build/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/tmp/openwrt-23.05-snapshot-r23787-1bbb94df96-mediatek-filogic-mediatek_mt7988a-rfb-sdcard.img.gz.new bs=55M conv=sync
make[4]: *** [Makefile:43: /builder/shared-workdir/build/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/tmp/openwrt-23.05-snapshot-r23787-1bbb94df96-mediatek-filogic-zyxel_ex5601-t0-ubootmod-bl31-uboot.fip] Error 1
cat: /builder/shared-workdir/build/staging_dir/target-aarch64_cortex-a53_musl/image/mt7986-spim-nand-4k-ddr4-bl2.imgmake[4]: *** Waiting for unfinished jobs....
: No such file or directory
make[4]: *** [Makefile:43: /builder/shared-workdir/build/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/tmp/openwrt-23.05-snapshot-r23787-1bbb94df96-mediatek-filogic-zyxel_ex5601-t0-ubootmod-preloader.bin] Error 1
sh /builder/shared-workdir/build/scripts/ubinize-image.sh --kernel /builder/shared-workdir/build/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/tmp/openwrt-23.05-snapshot-r23787-1bbb94df96-mediatek-filogic-xiaomi_redmi-router-ax6000-ubootmod-initramfs-factory.ubi.tmp /builder/shared-workdir/build/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/tmp/openwrt-23.05-snapshot-r23787-1bbb94df96-mediatek-filogic-xiaomi_redmi-router-ax6000-ubootmod-initramfs-factory.ubi -p 128KiB -m 2048   -E 5
````

I also saw this in a local build. The board references `spim-nand-4k-ddr4`, but this is not build.

**Comment by dangowrt** [comment]
Ah I see. I only backported that board because otherwise backporting other boards would not apply cleanly... Lets merge this to fix the build then. Sorry for the mess and thank you for sorting it.

PS: How did you retrieve the log from buildbot? And why do I see only 0-byte files there?

**Pull request merged**
