### PR TITLE
libnftnl: bump to version 1.1.4

### PR DESCRIPTION
**Pull request by rockdrilla**
ABI version is same.

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by n8v8R** [comment]
Could this be uplifted to the 19.x branch please?

**Comment by hauke** [comment]
@n8v8R Is there anything special you need from libnftnl in OpenWrt 19.07?

**Comment by n8v8R** [comment]
@hauke Unless it get cherry picked the update will live only in Master, if this PR even/ever gets merged to Master, whilst 19.x being expected to be soon(er or later) transitioning into the current branch.

I would rather not start a discussion about the pro/cons of keeping packages in the repo current/on par with source stable releases.

**Comment by hauke** [comment]
Thank you, your patch was applied to master.

**Pull request closed without merging**
