### PR TITLE
mwlwifi: update to version 10.3.9.0-20230311

### PR DESCRIPTION
**Pull request by anomeome**
upstream PR 408 improvements, see: [PR408 comments](https://github.com/kaloz/mwlwifi/pull/408)

compile for mvebu target devices, but untested by me, I'll leave that to people who still use the radios on these devices.

### CODE REVIEW

**Comment by neheb** [comment]
why not just update the git revision?

that is very interesting. I wonder if these patches fix that stuck queue issue.

**Comment by anomeome** [comment]
Unfortunately the change is not just a grab and compile against the current OpenWrt source, had to modify a couple of the files. The original author appears to have a home brewed Debian source running on target device mamba. I guess I could have gone around the tree the other way and modified the current OpenWrt mwlwifi patches, but nyet.

**Comment by neheb** [comment]
Needs a PKG_RELEASE bump at least.

**Comment by wongsyrone** [comment]
I tested WRT3200ACM in dumb AP mode, and cannot find noticeable problems.

My commit https://github.com/wongsyrone/lede-1/commit/0c61864edc97f73efeb5e65d8a99e7e2ce218002, you can just `git am` to test.

**Comment by BKPepe** [comment]
As noted by others, you should bump the source to the latest version instead of taking one patch.

**Comment by hauke** [comment]
If you have to do some modifications specific to OpenWrt please do it in a separate patch so we later know which change came from you and which from the upstream repository. I also prefer if you just upgrade to the latest version of mwlwifi.

**Comment by hnyman** [comment]
Now the PR looks sensible (pulling the git head from @kaloz repo, the correct local patched dropped etc.)

Regarding the two local patches left, I wonder if 005-mac80211_update.patch by @nbd168 in Dec 2022 (created as part of 8d90b9fef1ef) should also be upstreamed to kaloz repo?

**Comment by BKPepe** [comment]
Commit subject should be changed to be more appropriate.

Dne čt 13. 4. 2023 6:50 uživatel Hannu Nyman ***@***.***>
napsal:

**Review by neheb — APPROVED** [review]

**Comment by neveripe** [comment]
Not sure if this is related, but after upgrade to r22599 networking was only partially working.

**Comment by anomeome** [comment]
Given the number of monikers seeing the same issue this should probably be reverted.

**Comment by neheb** [comment]
Unfortunate

**Comment by neveripe** [comment]
> Given the number of monikers seeing the same issue this should probably be reverted.

I figured out that my networking problem were unrelated to the mwlwifi update. After update to further snapshot - r22602 everything seem to be working and wifi seems to be stable

Could you please provide me some deterministic way to test if anything is wrong with WiFi?

(have WRT32X)

**Comment by pesa1234** [comment]
I don't know what I do but I think I found a solution... I'm testing...

**Comment by neveripe** [comment]
Should this be reported upstream? I'm not quite get what is the problem aforementioned commit was/is trying to solve.

**Comment by neheb** [comment]
The better question is why only some people are having issues.

**Comment by anomeome** [comment]
@neveripe It has been, there is an open issue and a PR, [see post](https://forum.openwrt.org/t/linksys-wrt1900acs-v2-openwrt-snapshot/157825/8?u=anomeome)

**Comment by neveripe** [comment]
> @neveripe It has been, there is an open issue and a PR, [see post](https://forum.openwrt.org/t/linksys-wrt1900acs-v2-openwrt-snapshot/157825/8?u=anomeome)

Do you happen to know what is the average time to merge PR there or we should stop waiting and have this patch in openwrt until it gets merged upstream?

**Comment by hauke** [comment]
Is this pull request fixing the problem?
https://github.com/kaloz/mwlwifi/pull/412/files
If it fixes the problem and you have tested it please create a pull request to OpenWrt which adds the commit with the fix. When it gets merged upstream we can update mwlwifi again and remove the patch in OpenWrt.

**Comment by pesa1234** [comment]
Yes it works

**Comment by neveripe** [comment]
Okay, it has been merged upstream

**Comment by anomeome** [comment]
[PR12500](https://github.com/openwrt/openwrt/pull/12500) if someone wants to add a WFM post

**Pull request merged**
