### PR TITLE
busybox: update to version 1.34.0

### PR DESCRIPTION
**Pull request by hnyman**
Update busybox to version 1.34.0

* Remove upstreamed patches (205, 530, 540)

* Remove one old patch that does not apply any more. (203)
  That was originally introduced by in 2008 with 563d23459,
  but does not apply after busybox restructuring with
  https://git.busybox.net/busybox/commit/networking/udhcp/dhcpc.c?h=1_34_stable&id=e6007c4911c3ea26925f9473b9f156a692585f30
  and
  https://git.busybox.net/busybox/commit/networking/udhcp/dhcpc.c?h=1_34_stable&id=1c7253726fcbab09917f143f0b703efbd2df55c3

* Refresh config and patches.

Config refresh:

Refresh commands, run after busybox is first built once:

```
cd utils/busybox/
cd config/
../convert_menuconfig.pl ../../../../build_dir/target-aarch64_cortex-a53_musl/busybox-default/busybox-1.34.0
cd ..
./convert_defaults.pl < ../../../build_dir/target-aarch64_cortex-a53_musl/busybox-default/busybox-1.34.0/.config > Config-defaults.in

```
Manual edits needed after config refresh:

* Config-defaults.in:  OpenWrt config symbol IPV6 logic applied to
  BUSYBOX_DEFAULT_FEATURE_IPV6
* Config-defaults.in:  OpenWrt configTARGET_bcm53xx logic applied to
  BUSYBOX_DEFAULT_TRUNCATE (commit 547f1ec)
* Config-defaults.in:  OpenWrt logic applied to
  BUSYBOX_DEFAULT_LOGIN_SESSION_AS_CHILD (commit dc92917)
* config/editors/Config.in: Add USE_GLIBC dependency to
  BUSYBOX_CONFIG_FEATURE_VI_REGEX_SEARCH (commit f141090)
* config/shell/Config.in : change at "Options common to all shells"  the symbol
  SHELL_ASH  -->  BUSYBOX_CONFIG_SHELL_ASH
   (discussion in http://lists.openwrt.org/pipermail/openwrt-devel/2021-January/033140.html
     Apparently our script does not see the hidden option while
     prepending config options with "BUSYBOX_CONFIG_" which leads to a
     missed dependency when the options are later evaluated.)
* Edit Config.in files by adding quotes to sourced items in
  config/Config.in, config/networking/Config.in and config/util-linux/Config.in (commit 1da014f)

Other config changes reflect the upstream changes (or our earlier feature removals).

Run tested with ipq806x/R7800, mt7622/RT3200 and ath79/WNDR3700v2

### CODE REVIEW

**Comment by hnyman** [comment]
Regarding the removed DHCP patch "203-udhcpc_renew_no_deconfig.patch":
https://github.com/openwrt/openwrt/blob/90e167abaae80a59c8780d3305f8e1260d9f1339/package/utils/busybox/patches/203-udhcpc_renew_no_deconfig.patch

That was originally introduced by @nbd168  in 2008 with 563d23459
without any other explanation than the title
"don't call deconfig in udhcpc when entering the renew phase"

That patch does not apply after heavy busybox restructuring with  
https://git.busybox.net/busybox/commit/networking/udhcp/dhcpc.c?h=1_34_stable&id=e6007c4911c3ea26925f9473b9f156a692585f30  and   
https://git.busybox.net/busybox/commit/networking/udhcp/dhcpc.c?h=1_34_stable&id=1c7253726fcbab09917f143f0b703efbd2df55c3

The udhcp in busybox has evolved a lot since 2008, so I am not sure if we still need that (or what has been the actual usage. Preventing "deconfig" before renewal?). 

If that would still be needed, the place would likely be at line 1595
https://git.busybox.net/busybox/tree/networking/udhcp/dhcpc.c?h=1_34_stable#n1592

**Comment by hnyman** [comment]
Curiously, both R7800 and RT3200 seem to choke at validating firmware when trying to sysupgrade away from a router with a build of  r17444-1c8214d6f2 with busybox 1.34.0. 
The `/usr/libexec/validate_firmware_image` process takes lots of CPU (100% for one core) for a while and then the router reboots.

Not yet sure if it is related to some change in busybox 1.34.0, or some other recent change.

**Comment by rsalvaterra** [comment]
@hnyman, I can confirm it's a process substitution regression. [This patch](http://lists.busybox.net/pipermail/busybox/2021-August/089133.html) fixes it. 😉

**Comment by hnyman** [comment]
Well, thanks for confirming my findings, and also for finding the brand-new upstream patch for it ;-)

I looked yesterday at the upstream changes between 1.33.1 and 1.34.0 and noticed that there weren't that many ash shell changes, so the amount of likely culprits was small. Nice to know that this has been reported at upstream.

I will add the patch to the PR (and I will later replace it with the one accepted for upstream, when that happens.)

**Comment by hnyman** [comment]
Thanks. The patch seems to have fixed things ;-)
I have updated the PR.

**Comment by rsalvaterra** [comment]
BUSYBOX_DEFAULT_UDHCPC_DEFAULT_INTERFACE still defaults to "n". It's a string, not a boolean, and in our case it's supposed to be empty.

**Comment by hnyman** [comment]
Thanks for spotting that. The "n" looked too natural answer to me :-(

I will change it. Interestingly our automatic busybox config collection script places that "n" there although it seems have "eth0" as the original upstream value.   

(I don't think the value actually affects us much, as we always call it with an interface parameter, I believe)

**Comment by rsalvaterra** [comment]
> (I don't think the value actually affects us much, as we always call it with an interface parameter, I believe)

Right, that's why I believe it should be empty by default (better empty than wrong 😉). Someone compiling from source and seeing a device name there might get confused. With that change, you have my ack.

**Review by rsalvaterra — APPROVED** [review]

**Comment by dedeckeh** [comment]
Patch pushed to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=b6cbbbb6ef4deaba00f5c128ea66696fc64c5bf0); thx

**Pull request closed without merging**
