### PR TITLE
ramips: convert Xiaomi MIR3G to the new DTS based board name detection

### PR DESCRIPTION
**Pull request by iscilyas**
Fix Xiaomi Mi Router 3G based on feedback received when adding support for the Xiaomi Mi Router 3 Pro.

Signed-off-by: Ozgur Can Leonard <ozgurcan@gmail.com>

### CODE REVIEW

**Comment by iscilyas** [comment]
@ynezz and @chunkeey here are the changes for MIR3G as we discussed earlier (when talking about the MIR3P)

**Comment by chunkeey** [comment]
Since the label of the mir3g changed the entries would move to another location in the 01_leds, 02_network. But there are so many other entries in there that are out of order. so... 

As for the compatible, it's derived from the product name: "Xiaomi Mi Router 3G", the question is whenever we want to stick with xiaomi,mir3g or go for "xiaomi,mi-router-3g" (From what I have seen, it's possible to have spaces in the compatible id so "xiaomi,mi router 3g"  is possible, but let's not tempt fate and ruin some script). The definite plus of having "xiaomi,mir3g" is that we don't need to have a LED migration script. 

Please tell me what you think, even if we agree here and follow through with xiaomi,mir3g :laughing: .

**Review by chunkeey — COMMENTED** [review]
Please keep the subject line around 50 characters and the text in the commit around 75.
This will make the commit look much nicer on [git.openwrt.org](https://git.openwrt.org/?p=openwrt/openwrt.git;a=summary) since the subject won't be cut off (check it out!).

Furthermore, it would be great if you could add a short list of what changes you did to the commit message. This is because other people will look/skim through the message as well. And they don't know the context of what "feedback" you received by just looking at the message.

And finally, please also add to the commit message that you have modified the LED-behavior to
better make use of the LEDs and match stock firmware behavior. 

Otherwise, it looks like the patch fulfills of what's required by: https://openwrt.org/submitting-patches#submitting_patches

**Comment by iscilyas** [comment]
> Since the label of the mir3g changed the entries would move to another location in the 01_leds, 02_network. But there are so many other entries in there that are out of order. so...

crap... i guess i screwed up the order with the mir3p too... fixed (both)

> As for the compatible, it's derived from the product name: "Xiaomi Mi Router 3G", the question is whenever we want to stick with xiaomi,mir3g or go for "xiaomi,mi-router-3g" (From what I have seen, it's possible to have spaces in the compatible id so "xiaomi,mi router 3g" is possible, but let's not tempt fate and ruin some script). The definite plus of having "xiaomi,mir3g" is that we don't need to have a LED migration script.

honestly i don't have strong feelings either way... seems like "mir3g" has been in use and working well, though ;) and i don't want to write a LED migration script (even if i knew what that was ;))

i guess (the longer answer) is that the word "router" in the router's name seems redundant ;) then i guess "xiaomi,mi-router-3g" could become "xiaomi,mi-3g"... which i guess is also redundant (since "mi" is "xiaomi" afaik)... and "mir3g" was the christening name when "xiaomi" wasn't part of the name. so i suppose the real question is whether to keep it as "xiaomi,mir3g" or reduce it to "xiaomi,3g" (and yes, "3G" is an extremely confusing name for a router)... 

similarly, "xiaomi,mir3p" could become "xiaomi,3pro". openwrt also has "xiaomi,miwifi-mini" and "xiaomi,miwifi-nano" (at least, that's their names in the DTS... in the wild they're known as "miwifi-mini" and "miwifi-nano" (see 02_network).... for consistency, these would be "xiaomi,mini" and "xiaomi,nano" (i'm just bringing all of these to your attention to make sure whatever answer we come up with makes sense)... FWIW, the product line on xiaomi's webpage is "miwifi" (e.g. https://www.mi.com/miwifi3g/)

> Please tell me what you think, even if we agree here and follow through with xiaomi,mir3g  .

i can't say i have a very strong opinion either way... i suppose for the sake of consistency i'd advocate "xiaomi,3g", "xiaomi,3pro", "xiaomi,mini", "xiaomi,nano"... but not strongly enough to make enemies ;)

> Please keep the subject line around 50 characters and the text in the commit around 75.
> This will make the commit look much nicer on [git.openwrt.org](https://git.openwrt.org/?p=openwrt/openwrt.git;a=summary) since the subject won't be cut off (check it out!).

it's a real PITA to keep the subject ~50 chars. i tried. the subject now seems terse to me, but let me know what you think.
 
> Furthermore, it would be great if you could add a short list of what changes you did to the commit message. This is because other people will look/skim through the message as well. And they don't know the context of what "feedback" you received by just looking at the message.
 
yeah i know... i was just being lazy... fixed.

> And finally, please also add to the commit message that you have modified the LED-behavior to
> better make use of the LEDs and match stock firmware behavior.

OK. done.

> Otherwise, it looks like the patch fulfills of what's required by: https://openwrt.org/submitting-patches#submitting_patches

yeay!

**Comment by chunkeey** [comment]
Please take a look:
https://git.openwrt.org/?p=openwrt/staging/chunkeey.git;a=commit;h=7ed66fb8aaacbaa5e4a000834c6a52658065b704

I just added the PDF for the (old) MiWiFi Router 3 (because I couldn't find the "G" PDF) as well since it's a slightly better match (it looks almost 1:1 the same, though older hardware of course).

OT: Interestingly enough, Xiaomi is calling the 3 Pro: "Xiaomi R3D PRO Router" in the PDF you provided. Soo in hindsight, I should have just left this can of worms alone.

**Comment by iscilyas** [comment]
OK. so it sounds like "accepted". whew. one down.

**Comment by chunkeey** [comment]
Merged. Thanks.

**Comment by Neustradamus** [comment]
Merged commit is:
- https://github.com/openwrt/openwrt/commit/201d3d1a82e62bd139950571fc30f6b49d395378

**Pull request closed without merging**
