### PR TITLE
tools/ccache: update to 4.6.3

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release notes:
https://ccache.dev/releasenotes.html#_ccache_4_6_1

### CODE REVIEW

**Comment by BKPepe** [comment]
Wouldn't it be better just to point to release notes - https://ccache.dev/releasenotes.html#_ccache_4_6_1 instead of copy&þasting it to commit message?

**Comment by jospezial** [comment]
Ccache 4.6.2
Release date: 2022-08-22

**Comment by PolynomialDivision** [comment]
@jospezial Thanks. Pushed a new commit updating to latest version.

**Comment by jospezial** [comment]
new version again:
Ccache 4.6.3
Release date: 2022-08-27

**Comment by PolynomialDivision** [comment]
Thanks. I pushed a new update.

**Pull request merged**
