### PR TITLE
rtl838x: bundle phy firmware with Linux kernel

### PR DESCRIPTION
**Pull request by mtdcr**
Fixes long delay on boot when booting from flash. The driver waits
for one minute for userspace to load firmware, before it becomes
available.

Signed-off-by: Andreas Oberritter <obi@saftware.de>

### CODE REVIEW

**Comment by robimarko** [comment]
This does not look ok, why not make a new firmware package that will install the firmware to /lib/firmware?

Is this maybe in linux-firmware?

**Comment by mtdcr** [comment]
The rootfs is unavailable at the time the firmware files get loaded.

**Comment by mtdcr** [comment]
By the way, these files were installed to /lib/firmware before this patch.

**Comment by robimarko** [comment]
Cant, you have the driver defer probe for a couple of times before giving up, you can use the nowait version of request_firmware?
I don't know if that would work with a PHY driver but it should
That way you would for sure have rootfs available and avoid having to bake the fw into kernel

**Comment by mtdcr** [comment]
It wouldn't work for nfsroots at least. Disclaimer: I'm not working on the driver.

I tried to put the firmware files into an initramfs before, but rtl838x targets have old versions of U-Boot, which can't load FIP images. So the only remaining way if found would be to append an initramfs to the kernel, but OpenWrt seems to actively prohibit this unless you're putting the whole rootfs into it.

By the way, there's precedent for bundling firmware with the kernel in OpenWrt: imx6 and lantiq.

**Comment by robimarko** [comment]
I don't think that nfsroot matters in that respect at all, all that is required for it to load it from internal flash.

I am just saying that everything should be done to avoid baking in the FW.

**Comment by bkobl** [comment]
The RTL838x based devices with up to 52 ports are switches for SOHOs and even larger installations. In these settings it is normal to be able to load a configuration during boot via the network to make sure all switches can be centrally administered.  Also the main purpose of these switches is to switch traffic and the user expects that to happen as quickly as possible during the boot process. Therefore bundling the firmware with the kernel appears to be the most suitable choice to make sure user expectations are fulfilled.

**Comment by robimarko** [comment]
I understand your point, but in OpenWrt generally baking anything in is a no-no except in cases where there is no way around it.
That is why any FW blobs that are not make or break when it comes to booting the kernel are loaded from rootfs.

That is my view, but since I don't have commit rights all I can do is offer my opinion.

**Comment by pepe2k** [comment]
@bkobl @mtdcr how does it look with (re)distribute of that binary firmware, I don't see any license? Can we do that at all (sorry, I didn't follow initial work on this platform, so I might be missing something here)?

**Comment by mtdcr** [comment]
@pepe2k maybe we should first stop calling it firmware. When I submitted this PR, I wasn't taking care about what this wording would imply. They are configuration files loaded through the firmware loader API.

I'm not aware of the actual source of the data contained in *these* files, but the files were created for OpenWrt and I can show you one example I found, which very closely resembles the beginning of `rtl838x_8214fc.fw`:

```c
confcode_prv_t rtl8214fc_6276A_rtl8390_perchip_serdes[] = {
    /* Serdes */
    { 0, 0x1e, 8},
    { 0, 0x1f, 0x405}, { 0, 0x14, 0x8EC},     //# S0 default 0x8E4, bit 3 = 1 => S0 40 bit, 0 --- S0 20 bits.

    { 0, 0x1f, 0x404}, { 0, 0x17, 0x5359},//# S0 RXCLKWR change to neg edge

    { 0, 0x1f, 0x424}, { 0, 0x17, 0x5359},    //# S1 RXCLKWR change to neg edge

    //## Analog AFE patch
    { 0, 0x1f, 0x42C},     //# 0x2161 0x4000
    { 0, 0x11, 0x4000},
    { 0, 0x12, 0x2020},  //# S1 KI=0, KP = 3

    { 0, 0x1f, 0x42D},     //# 0x2169 0xC014
    { 0, 0x11, 0xC014},

    { 0, 0x1f, 0x464},     //# 0x2325 0x202a
    { 0, 0x15, 0x202a},     //Rsel = 10G/FF, kp1_1 = 2
    { 0, 0x12, 0x1fe0},    //#configure VGA=0x3

    { 0, 0x1f, 0x404},    // # 0x232a 0x40ff
    { 0, 0x10, 0x9703},

    { 0, 0x1f, 0x42E}, //    # 0x2171 0x218F
    { 0, 0x11, 0x218F},

    { 0, 0x1f, 0x044C}, //# 0x2261 = 0x4000, Turn off RING PLL
    { 0, 0x11, 0x4000},

    {0, 31, 0x0460}, {0, 0x10, 0x4800},
    {0, 31, 0x0462}, {0, 0x12, 0x96b3},
    {0, 0x15, 0x6e58},  //#enable cmu lbw for Icp
    {0, 31, 0x0464}, {0, 0x13, 0x3def}, {0, 0x16, 0xf072},
    {0, 31, 0x0465}, {0, 0x10, 0x4208}, {0, 0x11, 0x3a08}, {0, 0x12, 0x4007},

    {0, 31, 0x0464}, {0, 0x17, 0x84f5}, {0, 0x17, 0x04f5},
};
```

This is from `u-boot-2011.12/board/Realtek/switch/rtk/phy/conf/conf_rtl8214fc.c`, part of a GPL dump for an ALLNET switch (ALL-SG8316M in this case).

As @bkobl already explained, `rtl838x_8214fc.fw` and the other two files were derived from C arrays. These arrays just contain register values and were part of a GPLv2-licensed work, hence part of a GPL dump, but not necessarily from ALLNET and I don't know whether these arrays were taken from U-Boot or Linux.

Please see the [driver](https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=target/linux/rtl838x/files-5.4/drivers/net/dsa/rtl838x_phy.c;h=209ea50f040e9393a71718c021e7057506a29dfe;hb=HEAD#l806) for details on how the files get used.

**Comment by bkobl** [comment]
Indeed. We should stop calling it firmware. These are register values for the PHYs. From the below you can see that they are triples of (page, register, value) that need to be put into the PHY for
example to setup the right PLL frequency. One of these tuples basically stands for a line in the driver such as

write_phy_register(page=0, register = 1, value = x).

Because there are so many settings and it would clutter the code, they were moved into "firmware" files, but what happens is merely that these values are read in and then the above line is actually
called in a loop for each tuple. There are also 2-tuples when the PHY is internal to the SoC, in that case the tuples are merely (u32 register, u16 value) because the SoC can be directly addressed
without going through an MDIO bus/protocol. This is equivalent to set-up e.g. the UART of the SoC, you could put the register values e.g. for the PLL frequency also into a separate file but would not
call it "firmware". Have a look at e.g. the code for the other Realtek PHYs in the kernel:

https://github.com/torvalds/linux/blob/master/drivers/net/dsa/rtl8366rb.c

You can find similar deserts of configuration values from u-boot gpl dumps in there. Putting these values in the "firmware" files was a request by mainline kernel developers to make it more friendly.

So these values are really needed to get anything going.

**Comment by blogic** [comment]
merged, Thanks !

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/openwrt/openwrt/commit/0c26c9395bafb905a7eab240bdfc52cef686cd62

**Pull request closed without merging**
