### PR TITLE
[23.05] ipq40xx: add support for Linksys WHW03 V1

### PR DESCRIPTION
**Pull request by Lanchon**
this is a backport of https://github.com/openwrt/openwrt/pull/15345

fully tested, including MAC address correctness.

@robimarko, this was backported without the V1/V2 DTS merging.

thanks!

### CODE REVIEW

**Comment by Lanchon** [comment]
@robimarko i had taken this PR to draft until i understood the situation with [this LED bug](https://github.com/openwrt/openwrt/pull/15438) on 23.05. the bug is fixed in this branch too, so this PR is ready to be merged as is (no workaround needed).

thanks!

**Comment by robimarko** [comment]
I am going to be honest, I am not a fan of adding new devices to existing releases.
More so that BDF needs to be added as well, meaning ipq-wifi needs to be updated.

**Comment by Lanchon** [comment]
@robimarko 

i don't know what to say. there will probably not be a 2024 openwrt release, and having a release would help me for sure.

i suppose if there is an incorrect BDF in a released device, the correct BDF would be backported to 23.x. so i suspect a newer ipq-wifi in 23.x can only affect yet unreleased devices.

that said, the device works fine without the BDFs (with reduced range some have said, but i didn't notice that), so even a backport without the BDFs would be welcome.

again, i don't know what to say. this is more politics than technicalities, and this is not my project so it's not my place to say.

in any case, thanks for the help with the BDFs in master.

**Comment by robimarko** [comment]
I am not a fan of backporting device support, cause if we are going to backport everything then what is the point of a stable release?

@Ansuel Your thoughts?

**Comment by Lanchon** [comment]
@robimarko so i don't want to be a pain, in fact do i have a preference but i don't really care much about it, more so now with the recent stable release already behind us.

buy my question is... 23.05.4 just released with [support for 18 new devices](https://github.com/openwrt/openwrt/releases/tag/v23.05.4). before that, on 23.05.3 there were [24 new devices](https://github.com/openwrt/openwrt/releases/tag/v23.05.3). and etc, same story with the previous releases. so i guess... how do us collaborators are supposed to make sense of policies?

**Comment by robimarko** [comment]
Others merged those, I am perfectly fine with backporting devices if they are DTS+image recipe but not when they require more changes to be backported.

And again, you need a BDF for this device so that means that we would have to update the ipq-wifi package and that is a straight NACK from me since it will break existing devices.

**Comment by Lanchon** [comment]
note for self-builders: this backport works but requires BDFs for optimum performance. (see: https://github.com/openwrt/openwrt/pull/15844.)

**Pull request closed without merging**
