### PR TITLE
at91: add kernel 6.6

### PR DESCRIPTION
**Pull request by namiltd**
Adding kernel 6.6 as test kernel for at91.

Testing on real hardware required.

### CODE REVIEW

**Comment by namiltd** [comment]
Ping @PolynomialDivision

**Comment by PolynomialDivision** [comment]
For reference: https://github.com/torvalds/linux/commit/724ba6751532055db75992fc6ae21c3e322e94a7

**Comment by PolynomialDivision** [comment]
The [upstream dts](https://github.com/torvalds/linux/blob/89f5e14d05b4852db5ecdf222dc6a13edc633658/arch/arm/boot/dts/microchip/at91-q5xr5.dts) is different to our [downstream dts](https://github.com/openwrt/openwrt/blob/1fa28dd899593c874da3397efc069e17a66cbfed/target/linux/at91/files/arch/arm/boot/dts/at91-q5xr5.dts)?

**Comment by namiltd** [comment]
It is different, but I assumed it was newer and better compatible with kernel 6.6. I can't check that without real hardware though.

**Comment by PolynomialDivision** [comment]
Someone added it [here](https://github.com/torvalds/linux/commit/8c8b997c34ef1dca3b37a36b47808a649fb43a06) with the comment:
> Add Exegin Q5xR5. The base device tree is from OpenWrt tree and with
the addition of this patch there will be no need to maintain it
separatelly in OpenWrt.

The OpenWrt commit was made in [2015](https://github.com/openwrt/openwrt/commit/0227827f7bdfd029f40a4bf4b12a325e11dd4859). I guess it is fine to assume that the upstream dts file is fine and more complete.

**Comment by PolynomialDivision** [comment]
Same for the [lmu5000](https://github.com/torvalds/linux/commit/6dcb573a0afd989933c120240a270a8cfbdd0dfb).

**Comment by PolynomialDivision** [comment]
> It is different, but I assumed it was newer and better compatible with kernel 6.6. I can't check that without real hardware though.

You could probably contact `Claudiu Beznea <claudiu.beznea@tuxon.dev>`and ask for testing.

**Comment by PolynomialDivision** [comment]
Claudiu will test this PR until the end of the week. :) Let's wait for it. I accidentially added to much links. I will fix this when merging the PR.

**Comment by claudiubeznea** [comment]
Run basic boot test on SAMA7G5-EK, SAMA5D27 WLSOM1 EK, SAM9X60-EK. Results here:

https://p.fr33tux.org/9d1bd3
https://p.fr33tux.org/67153f
https://p.fr33tux.org/b6216c

Note that tuning failure issue is something that is reproducible also with some mainline versions.

**Comment by namiltd** [comment]
According to these tests there is no traffic on the Ethernet. Is the network working properly?

**Comment by claudiubeznea** [comment]
Haven't tried it. Will try to re-check it later today (not sure I'll manage to do it). Is there anything that should be checked?

**Comment by namiltd** [comment]
Overall, does it work well enough to become a test version.

**Comment by PolynomialDivision** [comment]
I can not view the logs. :/ However, I would merge it like this and if people going testing, we can add following up patches.

**Comment by claudiubeznea** [comment]
I cannot view it myself either at this time. Seem the site is down. I haven't managed to check the Ethernet, yet. I think it's OK to merge it as is.

**Comment by PolynomialDivision** [comment]
Thanks! Rebased on top of main and merged!

**Comment by namiltd** [comment]
Next stage: https://github.com/openwrt/openwrt/pull/16121

**Pull request merged**
