### PR TITLE
apm821xx: MR24: Change default config of WLAN LED

### PR DESCRIPTION
**Pull request by nasbdh9**
The previous config will only show 2.4G radio activity status

This change mr24:green:wifi4 and mr24:green:wifi2 to
show 2.4G and 5G radio on and off status

change mr24:green:wifi3 and mr24:green:wifi1 to
show 2.4G and 5G radio activity status

Signed-off-by: Tan Zien <nabsdh9@gmail.com>

### CODE REVIEW

**Comment by adschm** [comment]
Please explain _why_ this change is necessary in your commit description.

**Comment by nasbdh9** [comment]
> Please explain _why_ this change is necessary in your commit description.

Please check

**Comment by nasbdh9** [comment]
@adschm Please check

**Review by riptidewave93 — APPROVED** [review]

**Comment by mans0n** [comment]
The original function of the LEDs in the stock firmware is RSSI indicator, but rssileds does not take multiple ifaces for a single LED, so I guess this is a better choice.

BTW what happens to the older led config after sysupgrade to the newer image? Is it preserved or overwritten?

**Comment by nasbdh9** [comment]
> The original function of the LEDs in the stock firmware is RSSI indicator, but rssileds does not take multiple ifaces for a single LED, so I guess this is a better choice.
> 
> BTW what happens to the older led config after sysupgrade to the newer image? Is it preserved or overwritten?

Even if select `Keep settings and retain the current configuration` in luci, sysupgrade to the updated image will still use the LED config in the new image to overwrite old LED config

**Comment by nasbdh9** [comment]
Are there other problems?
Can this change be merged

**Review by mans0n — APPROVED** [review]

**Comment by adschm** [comment]
I will merge this with a slight change in names.
@mans0n board.d is only evaluated once, so existing config should be kept.

**Comment by hauke** [comment]
I already merged this in 7efc0d4d062e2b890b7daa6b30aa3a5e1754aaf5

**Comment by adschm** [comment]
Hmm, okay. So the question is whether I should add the improved names separately now, so people don't have to deduce that "0" is link and "1" is act ...

**Pull request closed without merging**
