### PR TITLE
target/octeon: Add Linux 4.19 support

### PR DESCRIPTION
**Pull request by diizzyy**
```
This commit adds support for Linux 4.19 kernel, various cleanups
listed below.

Drop 170-cisco-hack.patch as these devices never seems to have been
supported.

Unset kernel symbols:

* CONFIG_CAVIUM_CN63XXP1=y
  No supported hardware uses CN63XXP1 and it causes "slight decrease in
  performance"
  Source: https://cateee.net/lkddb/web-lkddb/CAVIUM_CN63XXP1.html

* CONFIG_USB_OCTEON_EHCI=y
  CONFIG_USB_OCTEON_OHCI=y
  Deprecated
  Source: https://cateee.net/lkddb/web-lkddb/USB_OCTEON_EHCI.html
  https://cateee.net/lkddb/web-lkddb/USB_OCTEON_OHCI.html

Removed kernel symbols:

* # CONFIG_ARCH_HIBERNATION_POSSIBLE=y
* CONFIG_ARCH_SUSPEND_POSSIBLE=y
  These are not in if you do a vanilla config of a MIPS Octeon kernel
  and I can't find any references about support on this platform.

* # CONFIG_BOOTPARAM_HUNG_TASK_PANIC is not set
* CONFIG_BOOTPARAM_HUNG_TASK_PANIC_VALUE=0
  No need to have this in by default, not defined in most other targets

* CONFIG_CRASH_CORE=y
  Can't find any documentation why this should be enabled by default

* CONFIG_DEBUG_INFO=y
  Set by https://github.com/openwrt/openwrt/blob/master/config/Config-kernel.in#L134

* CONFIG_DEBUG_SPINLOCK=y
  No need to have this in by default

* CONFIG_DEFAULT_HUNG_TASK_TIMEOUT=120
  Already set by default
  Source: https://cateee.net/lkddb/web-lkddb/DEFAULT_HUNG_TASK_TIMEOUT.html

* CONFIG_DETECT_HUNG_TASK=y
  No need to have this in by default, not defined in most other targets

* CONFIG_HAVE_DEBUG_KMEMLEAK=y
  No need to have this in by default, not defined in most other targets

* CONFIG_HAVE_DEBUG_STACKOVERFLOW=y
  No need to have this in by default

* CONFIG_HAVE_IDE=y
  None of the supported devices have IDE

* CONFIG_HZ=250
* # CONFIG_HZ_100 is not set
* CONFIG_HZ_250=y
  This is broken with generic config

* CONFIG_KALLSYMS=y
  No need to have this in by default, not defined in most other targets

* CONFIG_KEXEC=y
* CONFIG_KEXEC_CORE=y
  No need to have this in by default, not defined in most other targets

* CONFIG_HAVE_KVM=y
  No need to have this in by default

* CONFIG_SCHED_DEBUG=y
  No need to have this in by default, not defined in most other targets

* CONFIG_SYSFS_DEPRECATED=y
  Deprecated symbol
  Source: https://cateee.net/lkddb/web-lkddb/SYSFS_DEPRECATED.html

* CONFIG_SYSFS_DEPRECATED_V2=y
  Discouraged usage in general
  Source: https://cateee.net/lkddb/web-lkddb/SYSFS_DEPRECATED_V2.html

* CONFIG_UNINLINE_SPIN_UNLOCK=y
  No need to have this in by default, not defined in most other targets
  Source: https://github.com/openSUSE/kernel/blob/master/lib/Kconfig.debug#L1137

* CONFIG_ZLIB_INFLATE=y
  No need to have this in by default, not defined in most other targets

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>
```

### CODE REVIEW

**Comment by diizzyy** [comment]
@blogic @nbd168 @hauke 

@xback @ynezz 
You can have a look at this if possible?

**Comment by diizzyy** [comment]
Compile/Runtime tested on: EdgeRouter Lite

**Comment by ynezz** [comment]
> Depends on: #1799

Circular dependency detected :-)

**Comment by diizzyy** [comment]
Thanks, https://github.com/openwrt/openwrt/pull/1798 (link corrected above) ;-)

**Comment by ynezz** [comment]
I've just succesfully build tested `make -j9 V=s` following configuration

```
CONFIG_TARGET_octeon=y
CONFIG_TARGET_MULTI_PROFILE=y
CONFIG_TARGET_ALL_PROFILES=y
CONFIG_TARGET_DEVICE_octeon_DEVICE_generic=y
CONFIG_TARGET_DEVICE_octeon_DEVICE_er=y
CONFIG_TARGET_DEVICE_octeon_DEVICE_erlite=y
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
```

**Comment by diizzyy** [comment]
@ynezz 
Many thanks!

**Comment by diizzyy** [comment]
Bootlog ( including https://github.com/openwrt/openwrt/pull/1813 ):
```
[    0.000000] Linux version 4.19.18 (diizzyy@buildbox-v4) (gcc version 7.4.0 (OpenWrt GCC 7.4.0 r9248+1-efa6b8b6b6)) #0 SMP Sun Feb 10 20:07:41 2019
[    0.000000] CVMSEG size: 2 cache lines (256 bytes)
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 000d0601 (Cavium Octeon+)
[    0.000000] Checking for the multiply/shift bug... no.
[    0.000000] Checking for the daddiu bug... no.
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 0000000005400000 @ 0000000002a00000 (usable)
[    0.000000]  memory: 0000000007c00000 @ 0000000008200000 (usable)
[    0.000000]  memory: 000000000fc00000 @ 0000000410000000 (usable)
[    0.000000]  memory: 00000000018595c0 @ 0000000001100000 (usable)
[    0.000000] Wasting 243712 bytes for tracking 4352 unused pages
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Using internal Device Tree.
[    0.000000] software IO TLB: mapped [mem 0x0350d000-0x0750d000] (64MB)
[    0.000000] Primary instruction cache 32kB, virtually tagged, 4 way, 64 sets, linesize 128 bytes.
[    0.000000] Primary data cache 16kB, 64-way, 2 sets, linesize 128 bytes.
[    0.000000] Zone ranges:
[    0.000000]   DMA32    [mem 0x0000000000000000-0x00000000efffffff]
[    0.000000]   Normal   [mem 0x00000000f0000000-0x000000041fbfffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000002958fff]
[    0.000000]   node   0: [mem 0x0000000002a00000-0x0000000007dfffff]
[    0.000000]   node   0: [mem 0x0000000008200000-0x000000000fdfffff]
[    0.000000]   node   0: [mem 0x0000000410000000-0x000000041fbfffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000041fbfffff]
[    0.000000] On node 0 totalpages: 128345
[    0.000000]   DMA32 zone: 873 pages used for memmap
[    0.000000]   DMA32 zone: 0 pages reserved
[    0.000000]   DMA32 zone: 63833 pages, LIFO batch:15
[    0.000000]   Normal zone: 882 pages used for memmap
[    0.000000]   Normal zone: 64512 pages, LIFO batch:15
[    0.000000] random: get_random_bytes called from start_kernel+0x90/0x500 with crng_init=0
[    0.000000] percpu: Embedded 19 pages/cpu @(____ptrval____) s39200 r8192 d30432 u77824
[    0.000000] pcpu-alloc: s39200 r8192 d30432 u77824 alloc=19*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 126590
[    0.000000] Kernel command line: mtdparts=phys_mapped_flash:512k(boot0)ro,512k(boot1)ro,64k(eeprom)ro root=/dev/sda2 rootfstype=squashfs,ext4 rootwait console=ttyS0,115200
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 6, 262144 bytes)
[    0.000000] Memory: 395464K/513380K available (5335K kernel code, 310K rwdata, 1292K rodata, 1300K init, 16677K bss, 117916K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=128, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu:     CONFIG_RCU_FANOUT set to non-default value of 32.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=16 to nr_cpu_ids=2.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
[    0.000000] NR_IRQS: 127
[   31.682654] clocksource: OCTEON_CVMCOUNT: mask: 0xffffffffffffffff max_cycles: 0xe6a171a037, max_idle_ns: 881590485102 ns
[   31.693521] Calibrating delay loop (skipped) preset value.. 1000.00 BogoMIPS (lpj=5000000)
[   31.701673] pid_max: default: 32768 minimum: 301
[   31.706501] Mount-cache hash table entries: 1024 (order: 1, 8192 bytes)
[   31.712949] Mountpoint-cache hash table entries: 1024 (order: 1, 8192 bytes)
[   31.720688] Checking for the daddi bug... no.
[   31.726220] rcu: Hierarchical SRCU implementation.
[   31.731724] smp: Bringing up secondary CPUs ...
[   31.736805] SMP: Booting CPU01 (CoreId  1)...
[   31.741184] CPU1 revision is: 000d0601 (Cavium Octeon+)
[   31.741396] smp: Brought up 1 node, 2 CPUs
[   31.754242] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[   31.763973] futex hash table entries: 512 (order: 4, 65536 bytes)
[   31.770638] NET: Registered protocol family 16
[   31.783916] Not in host mode, PCI Controller not initialized
[   31.807635] SCSI subsystem initialized
[   31.811822] usbcore: registered new interface driver usbfs
[   31.817294] usbcore: registered new interface driver hub
[   31.822684] usbcore: registered new device driver usb
[   31.829778] clocksource: Switched to clocksource OCTEON_CVMCOUNT
[   31.837105] NET: Registered protocol family 2
[   31.842404] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes)
[   31.849978] TCP established hash table entries: 4096 (order: 3, 32768 bytes)
[   31.856998] TCP bind hash table entries: 4096 (order: 4, 65536 bytes)
[   31.863498] TCP: Hash tables configured (established 4096 bind 4096)
[   31.869889] UDP hash table entries: 256 (order: 1, 8192 bytes)
[   31.875582] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[   31.882145] NET: Registered protocol family 1
[   31.886371] PCI: CLS 0 bytes, default 128
[   31.888442] Crashlog allocated RAM at address 0x3f00000
[   31.893844] workingset: timestamp_bits=62 max_order=17 bucket_order=0
[   31.916436] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[   31.922608] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[   31.938873] io scheduler noop registered
[   31.942722] io scheduler deadline registered (default)
[   31.949280] octeon_gpio 1070000000800.gpio-controller: OCTEON GPIO driver probed.
[   31.957161] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[   31.964608] console [ttyS0] disabled
[   31.968081] 1180000000800.serial: ttyS0 at MMIO 0x1180000000800 (irq = 41, base_baud = 31250000) is a OCTEON
[   31.977899] console [ttyS0] enabled
[   31.984802] bootconsole [early0] disabled
[   31.993525] 1180000000c00.serial: ttyS1 at MMIO 0x1180000000c00 (irq = 42, base_baud = 31250000) is a OCTEON
[   32.004026] octeon_rng octeon_rng: Octeon Random Number Generator
[   32.010615] cacheinfo: Failed to find cpu0 device node
[   32.015766] cacheinfo: Unable to detect cache hierarchy for CPU 0
[   32.028827] loop: module loaded
[   32.032974] of-flash 1f400000.nor: Can't get bank width from device tree
[   32.040257] libphy: mdio_octeon: probed
[   32.044146] [Firmware Warn]: /soc@0/mdio@1180000001800/ethernet-phy@7: Whitelisted compatible string. Please remove
[   32.055311] [Firmware Warn]: /soc@0/mdio@1180000001800/ethernet-phy@6: Whitelisted compatible string. Please remove
[   32.066506] [Firmware Warn]: /soc@0/mdio@1180000001800/ethernet-phy@5: Whitelisted compatible string. Please remove
[   32.077686] mdio_octeon 1180000001800.mdio: Probed
[   32.083102] libphy: Fixed MDIO Bus: probed
[   32.087413] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[   32.094009] ehci-platform: EHCI generic platform driver
[   32.099489] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[   32.105772] ohci-platform: OHCI generic platform driver
[   32.111412] usbcore: registered new interface driver usb-storage
[   32.111431] random: fast init done
[   32.117483] octeon_wdt: Initial granularity 5 Sec
[   32.129493] Interface 0 has 3 ports (RGMII)
[   32.138214] octeon-hcd 16f0010000000.usbc: Octeon Host Controller
[   32.144445] octeon-hcd 16f0010000000.usbc: new USB bus registered, assigned bus number 1
[   32.152665] octeon-hcd 16f0010000000.usbc: irq 56, io mem 0x00000000
[   32.160084] hub 1-0:1.0: USB hub found
[   32.163943] hub 1-0:1.0: 1 port detected
[   32.168489] octeon-hcd 16f0010000000.usbc: Registered HCD for port 0 on irq 56
[   32.177447] NET: Registered protocol family 10
[   32.184143] Segment Routing with IPv6
[   32.187947] NET: Registered protocol family 17
[   32.192592] 8021q: 802.1Q VLAN Support v1.8
[   32.197057] Bootbus flash: Setting flash for 4MB flash at 0x1f800000
[   32.203578] phys_mapped_flash: Found 1 x16 devices at 0x0 in 8-bit bank. Manufacturer ID 0x0000c2 Chip ID 0x0000a7
[   32.213968] Amd/Fujitsu Extended Query Table at 0x0040
[   32.219132]   Amd/Fujitsu Extended Query version 1.1.
[   32.224231] phys_mapped_flash: Swapping erase regions for top-boot CFI table.
[   32.231396] number of CFI chips: 1
[   32.234841] 3 cmdlinepart partitions found on MTD device phys_mapped_flash
[   32.241756] Creating 3 MTD partitions on "phys_mapped_flash":
[   32.247513] 0x000000000000-0x000000080000 : "boot0"
[   32.253632] 0x000000080000-0x000000100000 : "boot1"
[   32.259797] 0x000000100000-0x000000110000 : "eeprom"
[   32.267707] OF: fdt: not creating '/sys/firmware/fdt': CRC check failed
[   32.274958] Waiting for root device /dev/sda2...
[   32.579734] usb 1-1: new high-speed USB device number 2 using octeon-hcd
[   33.142138] usb-storage 1-1:1.0: USB Mass Storage device detected
[   33.148803] scsi host0: usb-storage 1-1:1.0
[   34.490454] scsi 0:0:0:0: Direct-Access     ADATA    USB Flash Drive  1100 PQ: 0 ANSI: 4
[   34.501575] sd 0:0:0:0: [sda] 15155200 512-byte logical blocks: (7.76 GB/7.23 GiB)
[   34.510485] sd 0:0:0:0: [sda] Write Protect is off
[   34.515298] sd 0:0:0:0: [sda] Mode Sense: 43 00 00 00
[   34.516585] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   34.534842]  sda: sda1 sda2
[   34.543211] sd 0:0:0:0: [sda] Attached SCSI removable disk
[   34.566106] EXT4-fs (sda2): mounted filesystem without journal. Opts: (null)
[   34.573341] VFS: Mounted root (ext4 filesystem) readonly on device 8:2.
[   34.581159] Freeing unused kernel memory: 1300K
[   34.585701] This architecture does not have kernel memory protection.
[   34.592192] Run /sbin/init as init process
[   34.677269] init: Console is alive
[   34.681048] init: - watchdog -
[   34.792019] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[   34.799502] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[   34.816741] init: - preinit -
[   35.096439] random: jshn: uninitialized urandom read (4 bytes read)
[   35.147800] random: jshn: uninitialized urandom read (4 bytes read)
[   35.186827] random: jshn: uninitialized urandom read (4 bytes read)
[   35.222176] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   38.353338] mount_root: mounting /dev/root
[   38.897705] random: crng init done
[   38.901126] random: 1 urandom warning(s) missed due to ratelimiting
[   40.098477] EXT4-fs (sda2): re-mounted. Opts: (null)
[   40.207901] urandom-seed: Seed file not found (/etc/urandom.seed)
[   40.257025] procd: - early -
[   40.260203] procd: - watchdog -
[   40.908177] procd: - watchdog -
[   40.911874] procd: - ubus -
[   40.969614] procd: - init -
[   41.173697] kmodloader: loading kernel modules from /etc/modules.d/*
[   41.229927] xt_time: kernel timezone is -0000
[   41.251528] PPP generic driver version 2.4.2
[   41.257268] NET: Registered protocol family 24
[   41.272005] kmodloader: done loading kernel modules from /etc/modules.d/*
[   47.955408] br-lan: port 1(eth0) entered blocking state
[   47.960774] br-lan: port 1(eth0) entered disabled state
[   47.966471] device eth0 entered promiscuous mode
[   48.019722] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   48.072879] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
```

**Comment by diizzyy** [comment]
```CONFIG_CAVIUM_OCTEON_CVMSEG_SIZE```
Any reason why this is ```2``` instead of the default ```1```?
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/mips/cavium-octeon/Kconfig?h=v4.19.21#n14

Any reason why ```CONFIG_JUMP_LABEL``` isn't enabled (not enabled vanilla kernel)?

@ynezz 
Can you have a look at this?

**Comment by diizzyy** [comment]
Hmm...
```make target/linux/compile``` works fine while ```make target/linux/compile V=s``` doesn't

**Comment by diizzyy** [comment]
Unbreak, apparently ```# XXX is not set``` makes ```V=s``` happy.
Revisit cleanup attempt once this is in

**Comment by diizzyy** [comment]
Kernel HZ is "fixed" by https://github.com/openwrt/openwrt/pull/1831

**Comment by diizzyy** [comment]
Depends on https://github.com/openwrt/openwrt/pull/1828

**Comment by diizzyy** [comment]
To be clear, this is ready to be merged. (To the best of my knowledge)
https://github.com/openwrt/openwrt/pull/1831 isn't needed (100Hz is hardset) but I guess it would be nice? :-)

@hauke 
Can you have a look? I pinged John via email a few days ago but I never recieved a reply

**Comment by diizzyy** [comment]
If someone else can have a look at this please do

**Comment by ynezz** [comment]
@hauke I've just made it easier for you to review kernel config changes between 4.14 and 4.19, 

Additions:

```diff
--- target/linux/octeon/config-4.14     2019-03-01 11:42:54.120796448 +0000                                                                                                                                          
+++ target/linux/octeon/config-4.19     2019-03-23 11:45:10.678631616 +0000
+CONFIG_ARCH_HAS_PHYS_TO_DMA=y
+CONFIG_COMPAT_32BIT_TIME=y
+CONFIG_DMA_DIRECT_OPS=y
+CONFIG_FS_IOMAP=y
+CONFIG_GENERIC_LIB_ASHLDI3=y
+CONFIG_GENERIC_LIB_ASHRDI3=y
+CONFIG_GENERIC_LIB_CMPDI2=y
+CONFIG_GENERIC_LIB_LSHRDI3=y
+CONFIG_GENERIC_LIB_UCMPDI2=y
+CONFIG_HAS_RAPIDIO=y
+CONFIG_HAVE_ARCH_COMPILER_H=y
+CONFIG_HAVE_LD_DEAD_CODE_DATA_ELIMINATION=y
+CONFIG_HAVE_RSEQ=y
+CONFIG_LOCK_DEBUGGING_SUPPORT=y
+CONFIG_MEMFD_CREATE=y
+CONFIG_MIGRATION=y
+CONFIG_MIPS_NR_CPU_NR_MAP=1024
+CONFIG_MIPS_NR_CPU_NR_MAP_1024=y
+CONFIG_NEED_DMA_MAP_STATE=y
+CONFIG_NR_CPUS_DEFAULT_64=y
+CONFIG_NVMEM=y
+CONFIG_OF_KOBJ=y
```

Removals:

```diff
--- target/linux/octeon/config-4.14     2019-03-01 11:42:54.120796448 +0000                                                                                                                                          
+++ target/linux/octeon/config-4.19     2019-03-23 11:45:10.678631616 +0000
-CONFIG_ARCH_HIBERNATION_POSSIBLE=y
-CONFIG_ARCH_MIGHT_HAVE_PC_PARPORT=y
-CONFIG_ARCH_MIGHT_HAVE_PC_SERIO=y
-CONFIG_ARCH_PHYS_ADDR_T_64BIT=y
-CONFIG_ARCH_SUSPEND_POSSIBLE=y
-CONFIG_BOOTPARAM_HUNG_TASK_PANIC_VALUE=0
-CONFIG_CAVIUM_CN63XXP1=y
-CONFIG_CRASH_CORE=y
-CONFIG_DEBUG_INFO=y
-CONFIG_DEBUG_SPINLOCK=y
-CONFIG_DEFAULT_HUNG_TASK_TIMEOUT=120
-CONFIG_DETECT_HUNG_TASK=y
-CONFIG_DMA_COHERENT=y
-CONFIG_GENERIC_IO=y
-CONFIG_HAVE_CC_STACKPROTECTOR=y
-CONFIG_HAVE_DEBUG_KMEMLEAK=y
-CONFIG_HAVE_DEBUG_STACKOVERFLOW=y
-CONFIG_HAVE_DMA_API_DEBUG=y
-CONFIG_HAVE_IDE=y
-CONFIG_HAVE_KVM=y
-CONFIG_HZ=250
-CONFIG_HZ_250=y
-CONFIG_IOMMU_HELPER=y
-CONFIG_KALLSYMS=y
-CONFIG_KEXEC=y
-CONFIG_KEXEC_CORE=y
-CONFIG_MMC_OCTEON=y
-CONFIG_NEED_SG_DMA_LENGTH=y
-CONFIG_NR_CPUS_DEFAULT_16=y
-CONFIG_OF_ADDRESS_PCI=y
-CONFIG_OF_PCI=y
-CONFIG_OF_PCI_IRQ=y
-CONFIG_PCI_BUS_ADDR_T_64BIT=y
-CONFIG_PRINTK_SAFE_LOG_BUF_SHIFT=13
-CONFIG_SCHED_DEBUG=y
-CONFIG_SYSFS_DEPRECATED=y
-CONFIG_SYSFS_DEPRECATED_V2=y
-CONFIG_UNINLINE_SPIN_UNLOCK=y
-CONFIG_USB_OCTEON_EHCI=y
-CONFIG_USB_OCTEON_OHCI=y
-CONFIG_ZLIB_INFLATE=y
```

@diizzyy I would probably leave those enabled, although I don't use kexec personally, I think, that it might be handy for someone and if this platform could accomodate it in terms of disk/flash space, then I see no point for removal during the kernel version bump.

```
-CONFIG_CRASH_CORE=y
-CONFIG_KEXEC=y
-CONFIG_KEXEC_CORE=y
```

**Comment by ynezz** [comment]
Build test finished fine as well.

**Comment by diizzyy** [comment]
I'm trying to be as consistent as possible

```CONFIG_KEXEC``` is handled here: https://github.com/openwrt/openwrt/blob/master/config/Config-kernel.in#L257

```CONFIG_CRASH_CORE``` is only defined by a handful on targets for no obvious reason
```
target/linux/gemini/config-4.14
target/linux/gemini/config-4.19
target/linux/brcm63xx/config-4.14
target/linux/octeontx/config-4.14
target/linux/octeon/config-4.14
target/linux/oxnas/config-4.14
target/linux/layerscape/armv8_32b/config-4.14
target/linux/layerscape/armv7/config-4.14
target/linux/layerscape/armv8_64b/config-4.14
target/linux/x86/config-4.14
target/linux/x86/config-4.19
```

```CONFIG_KEXEC_CORE``` same as above but this seems a bit "broken" in the tree. This should match the above on 4.14 and higher but works anyway since the kernel config logic enforces it.
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/Kconfig?h=v4.14.107#n9
```
target/linux/gemini/config-4.14
target/linux/gemini/config-4.19
target/linux/brcm63xx/config-4.14
target/linux/brcm63xx/config-4.9
target/linux/octeontx/config-4.14
target/linux/at91/config-4.9
target/linux/octeon/config-4.14
target/linux/oxnas/config-4.14
target/linux/layerscape/armv8_32b/config-4.14
target/linux/layerscape/armv7/config-4.14
target/linux/layerscape/armv8_64b/config-4.14
target/linux/rb532/config-4.14
target/linux/x86/config-4.14
target/linux/x86/config-4.19
```

Many thanks for reviewing

**Comment by diizzyy** [comment]
@ynezz 
Possible to merge this or are any adjustments needed?

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
