### PR TITLE
[23.05]: kernel: bump 5.15 to 5.15.171

### PR DESCRIPTION
**Pull request by hauke**
* kernel: bump 5.15 to 5.15.168
    
    Manually adapted:
       bcm27xx/patches-5.15/950-0166-xhci-Use-more-event-ring-segment-table-entries.patch
         I replaced it with the version from main branch which applies more easily
       bcm27xx/patches-5.15/950-0600-xhci-quirks-add-link-TRB-quirk-for-VL805.patch
       bcm27xx/patches-5.15/950-0605-xhci-refactor-out-TRBS_PER_SEGMENT-define-in-runtime.patch
       bcm27xx/patches-5.15/950-0606-usb-xhci-add-VLI_TRB_CACHE_BUG-quirk.patch
       bcm27xx/patches-5.15/950-0717-usb-xhci-add-a-quirk-for-Superspeed-bulk-OUT-transfe.patch
       bcm53xx/patches-5.15/180-usb-xhci-add-support-for-performing-fake-doorbell.patch
       generic/hack-5.15/645-netfilter-connmark-introduce-set-dscpmark.patch
    
    Added patch:
       generic/backport-5.15/777-netfilter-xtables-fix-typo-causing-some-targets-to-not-load-on-IPv6.patch
          This fixes a bug intoduced in this version.
    
    Adapt kernel configuration for newly added option
    CONFIG_PROC_MEM_ALWAYS_FORCE.
    
 * kernel: bump 5.15 to 5.15.169
    
    Added patch:
       generic/backport-5.15/430-v6.3-udf-Allocate-name-buffer-in-directory-iterator-on-he.patch
       This patch fixes the following compile warning:
    ```
      CC [M]  fs/udf/namei.o
    fs/udf/namei.c: In function 'udf_rename':
    fs/udf/namei.c:878:1: error: the frame size of 1144 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
      878 | }
          | ^
    cc1: all warnings being treated as errors
    make[7]: *** [scripts/Makefile.build:289: fs/udf/namei.o] Error 1
    ```

 * kernel: bump 5.15 to 5.15.170
    
    Removed because they are upstream:
       generic/backport-5.15/777-netfilter-xtables-fix-typo-causing-some-targets-to-not-load-on-IPv6.patch
       https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.15.y&id=90baa455aa7e099152898cfa5eb3928d6152da12
    
 * mac80211: compatibility with kernel 6.6.59
    
    Fix genlmsg_multicast_allns() build error on kernel 6.6.59.
    Based on kernel patch https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit?h=v6.6.59&id=e0f83d268974dab0361d11904dfc9acec53f96a6
    
* kernel: bump 5.15 to 5.15.171
    
    No manual changes needed.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@hauke: You have done a little mistake in title :/

**Comment by hauke** [comment]
The update still has this compile problem:
```
  CC [M]  fs/udf/namei.o
fs/udf/namei.c: In function 'udf_rename':
fs/udf/namei.c:878:1: error: the frame size of 1144 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
  878 | }
      | ^
cc1: all warnings being treated as errors
make[7]: *** [scripts/Makefile.build:289: fs/udf/namei.o] Error 1
```
It was introduced in kernel 5.15.170.

**Comment by namiltd** [comment]
I created a patch to reduce the frame size of the udf_rename function by dynamically allocating oiter, niter and diriter structures. Copy the patch to target/linux/generic/hack-5.15
[931-reduce_udf_rename_frame_size.patch](https://github.com/user-attachments/files/17689498/931-reduce_udf_rename_frame_size.patch)

**Comment by hauke** [comment]
Thank you @rx78gp01, I added the patch and will inform Linux stable.

**Comment by namiltd** [comment]
Patch 430-v6.3-udf-Allocate-name-buffer-in-directory-iterator-on-he.patch works as expected. @hauke Add information about this patch to PR description,

**Comment by hauke** [comment]
> Patch 430-v6.3-udf-Allocate-name-buffer-in-directory-iterator-on-he.patch works as expected. @hauke Add information about this patch to PR description,

I already added it to the commit description.

**Review by namiltd — APPROVED** [review]

**Pull request merged**
