### PR TITLE
libnftnl: bump to version 1.1.3

### PR DESCRIPTION
**Pull request by rockdrilla**
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

### CODE REVIEW

**Comment by rockdrilla** [comment]
I don't sure about ABI_VERSION bump: is it internal OpenWrt versioning or library symbols specific or even soname part?

**Comment by rockdrilla** [comment]
I've split PR into two commits. If ABI bump is appreciated - merge them all, if not - pick up only first one.

**Review by jow- — COMMENTED** [review]
The ABI version should correspond to the soname (https://abi-laboratory.pro/index.php?view=timeline&l=libnftnl)

**Comment by rockdrilla** [comment]
@jow-, fixed, and squashed two commits into one.

**Comment by chunkeey** [comment]
Note:

This likely fixes commit 299f6cb2da0 ("iptables: update to 1.8.3") since iptables current complains about
the following if CONFIG_IPTABLES_NFTABLES = y
    
     checking for libnftnl >= 1.1.3... no
     *** Error: no suitable libnftnl found. ***
         Please install the 'libnftnl' package
         Or consider --disable-nftables to skip
         iptables-compat over nftables support.

**Comment by chunkeey** [comment]
Merged. Thanks.

**Pull request closed without merging**
