### PR TITLE
ncurses: enable pc files in the host build

### PR DESCRIPTION
**Pull request by neheb**
Needed for things such as readline that depend on ncurses.

Found as a result of https://github.com/openwrt/packages/pull/24486

### CODE REVIEW

**Comment by neheb** [comment]
I hate ncurses.

So hostpkg has ncurses.pc . Target has ncursesw. readline only lists the former.

**Comment by neheb** [comment]
I also hate autotools.

**Comment by neheb** [comment]
Submitted upstream: https://lists.gnu.org/archive/html/bug-readline/2024-07/msg00000.html

ping @robimarko

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
