### PR TITLE
toolchain: binutils: add support for 2.43.1

### PR DESCRIPTION
**Pull request by NukeMania**
Release notes:
https://lists.gnu.org/archive/html/info-gnu/2024-08/msg00003.html

No need to refresh patches
Test device: Xiaomi ax3600

Signed-off-by: Olcay Korkmaz <nuke_mania@hotmail.com>

### CODE REVIEW

**Comment by robimarko** [comment]
Have you checked if patches need to be refreshed?

**Comment by NukeMania** [comment]
> Have you checked if patches need to be refreshed?

My bad i didn't quote that patches don't need to be refresh

**Comment by robimarko** [comment]
It fails to compile for me on Fedora 40:
```
make[7]: Circular doc/bfd.stamp <- doc/bfd.texi dependency dropped.
/usr/bin/env bash ./libtool  --tag=CC   --mode=compile /home/robimarko/Building/AX3600/qualcommax/staging_dir/host/bin/gcc -DHAVE_CONFIG_H -I.  -DBINDIR='"/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/bin"' -DLIBDIR='"/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/lib"' -I. -I. -I./../include  -DHAVE_aarch64_elf64_le_vec -DHAVE_aarch64_elf64_be_vec -DHAVE_aarch64_elf32_le_vec -DHAVE_aarch64_elf32_be_vec -DHAVE_arm_elf32_le_vec -DHAVE_arm_elf32_be_vec -DHAVE_aarch64_pei_le_vec -DHAVE_aarch64_pe_le_vec -DHAVE_elf64_le_vec -DHAVE_elf64_be_vec -DHAVE_elf32_le_vec -DHAVE_elf32_be_vec   -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144  -I/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/include -pthread -O2 -I/home/robimarko/Building/AX3600/qualcommax/staging_dir/host/include      -MT bfdio.lo -MD -MP -MF .deps/bfdio.Tpo -c -o bfdio.lo bfdio.c
libtool: compile:  /home/robimarko/Building/AX3600/qualcommax/staging_dir/host/bin/gcc -DHAVE_CONFIG_H -I. -DBINDIR=\"/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/bin\" -DLIBDIR=\"/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/lib\" -I. -I. -I./../include -DHAVE_aarch64_elf64_le_vec -DHAVE_aarch64_elf64_be_vec -DHAVE_aarch64_elf32_le_vec -DHAVE_aarch64_elf32_be_vec -DHAVE_arm_elf32_le_vec -DHAVE_arm_elf32_be_vec -DHAVE_aarch64_pei_le_vec -DHAVE_aarch64_pe_le_vec -DHAVE_elf64_le_vec -DHAVE_elf64_be_vec -DHAVE_elf32_le_vec -DHAVE_elf32_be_vec -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -I/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/include -pthread -O2 -I/home/robimarko/Building/AX3600/qualcommax/staging_dir/host/include -MT bfdio.lo -MD -MP -MF .deps/bfdio.Tpo -c bfdio.c -o bfdio.o
In file included from /home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/include/sys/types.h:70,
                 from sysdep.h:33,
                 from bfdio.c:24:
/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/include/endian.h: In function '__bswap32':
/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/include/endian.h:26:32: warning: suggest parentheses around arithmetic in operand of '|' [-Wparentheses]
   26 |         return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
      |                          ~~~~~~^~~~~~~
/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/include/endian.h:26:48: warning: suggest parentheses around arithmetic in operand of '|' [-Wparentheses]
   26 |         return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
      |                                          ~~~~~~^~~~~~~~~
/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/include/endian.h: In function '__bswap64':
/home/robimarko/Building/AX3600/qualcommax/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/include/endian.h:31:30: warning: suggest parentheses around '+' inside '<<' [-Wparentheses]
   31 |         return __bswap32(__x)+0ULL<<32 | __bswap32(__x>>32);
      |                ~~~~~~~~~~~~~~^~~~~
bfdio.c: In function '_bfd_real_ftell':
bfdio.c:52:10: error: implicit declaration of function 'ftello64'; did you mean 'ftello'? [-Wimplicit-function-declaration]
   52 |   return ftello64 (file);
      |          ^~~~~~~~
      |          ftello
bfdio.c: In function '_bfd_real_fseek':
bfdio.c:64:10: error: implicit declaration of function 'fseeko64'; did you mean 'fseeko'? [-Wimplicit-function-declaration]
   64 |   return fseeko64 (file, offset, whence);
      |          ^~~~~~~~
      |          fseeko
bfdio.c: In function '_bfd_real_fopen':
bfdio.c:256:25: error: implicit declaration of function 'fopen64'; did you mean 'fopen'? [-Wimplicit-function-declaration]
  256 |   return close_on_exec (fopen64 (filename, modes));
      |                         ^~~~~~~
      |                         fopen
bfdio.c:256:25: error: passing argument 1 of 'close_on_exec' makes pointer from integer without a cast [-Wint-conversion]
  256 |   return close_on_exec (fopen64 (filename, modes));
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                         |
      |                         int
bfdio.c:75:22: note: expected 'FILE *' {aka 'struct _IO_FILE *'} but argument is of type 'int'
   75 | close_on_exec (FILE *file)
      |                ~~~~~~^~~~
make[7]: *** [Makefile:1768: bfdio.lo] Error 1
```

**Comment by robimarko** [comment]
Ok, wiping everything along with patches being applied fixes building on Fedora 40.

**Comment by NukeMania** [comment]
> Ok, wiping everything along with patches being applied fixes building on Fedora 40.

i didn't notice patch folder thanks for that 
also my testing was done unintentionally  without patches
i sorry for headache

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
