### PR TITLE
Add support for Comfast CF-WR650AC v1 and v2

### PR DESCRIPTION
**Pull request by gareth41**
This is a dual band 11a/11n router with 1x wan and 4x gig lan ports.  There are two versions of this router which can be identified through the factory web interface, v1 has 128mb ram and a uboot size of 128k, v2 has 256mb ram and a uboot size of 256k, the remaining hardware and PCB markings are the same.  Factory firmware uses customized openwrt so use sysupgrade file directly.
Signed-off-by: Gareth Parker <gareth41@orcon.net.nz>

### CODE REVIEW

**Comment by ynezz** [comment]
@gareth41 You should probably consider adding this device under new ath79(based on DTS) platform. We're now on 4.14 kernel, so this PR is obsolete by now and I'm not sure if it would get merged even if updated to the latest master as ath79 support seems to be preferred.

**Comment by Neustradamus** [comment]
@gareth41 @ynezz, any news?

**Comment by grosjo** [comment]
I made a port to ath79 : 

https://github.com/openwrt/openwrt/pull/1893

Please kindly review it

**Comment by ynezz** [comment]
Thanks, let's continue with ath79.

**Pull request closed without merging**
