### PR TITLE
[23.05] armvirt: add EFI support + rename to armsr

### PR DESCRIPTION
**Pull request by mcbridematt**
This is the 23.05 / 5.15 kernel version of https://github.com/openwrt/openwrt/pull/4996 which was merged into the main branch a few days ago.

Differences of note:
* A different patch is used to resolve the SFP lock issue on NXP DPAA2 platforms (see https://github.com/openwrt/openwrt/commit/61ec9a8154a58420e3c913c5e62a9e00b10f1936 for the 6.x fix). It is difficult to port the 6.2 fix back to 5.15 due to significant changes (in the phylink code) between the versions.

### CODE REVIEW

**Comment by ynezz** [comment]
Sorry, but I didn't anticipated this move, so I've thought, that we've a lot more time to tackle that already confusing `armvirt` target name with something more appropriate.

IIUC then we've currently short window before `23.05.0-rc1` hits the ground and if we're going to merge this into 23.05 (I'm pretty much in favor of this), then we should probably strongly consider renaming/moving the target from `armvirt/64` to something less confusing, since its not only `virt` target anymore.

We should probably go with the well established `generic` subtarget naming scheme (24 hits currently), thus I would suggest to simply use `arm64/generic`. That being said, I would move/rename only the 64-bit part under `arm64/generic`, I would leave `armvirt/32` as it is today.

I've proposed this on IRC already this weekend to gather first level of feedback and @Ansuel was fine with that, what about @dangowrt @hauke ?

FWIW @pkgadd suggested on IRC following: SBSA (server base system architecture) or multi-platform (e.g. arm64mp) might come to mind as well, but I don't really see a compelling reason for the hurdles of renaming, yet - until there are actually a number of (physical) devices from different vendors which just work that way

**Comment by mcbridematt** [comment]
> We should do that as 23.05 is going to stay with us for quite some time and it would be just another source of confusion if we rename armvirt in main branch later and leave it as armvirt in 23.05 (renaming target is not an option for example between 23.05.2 and 23.05.3).

I'm happy to change the target name. Everyone was telling me to put it into armvirt instead of a new target (e.g `arm64` or `armserver` in previous versions), so that is where it ended up.
I guess also 'taking over' an existing target means there isn't an extra buildbot cycle and other infra issues.

> multi-platform (e.g. arm64mp)

I like that name.

> armv8/generic

Armv9 devices aren't far away. Hypothetically, `arm64/armv8` and `armv8/armv9` could happen if the CPU features justify it.

**Comment by anta5010** [comment]
As this new target is not for any multi-platforms, but requires that a platform is SBSA and BBR compatible maybe we can name it to arm64sr (SystemReady)? https://developer.arm.com/documentation/102858/0100/Introduction

**Comment by ynezz** [comment]
> As this new target is not for any multi-platforms, but requires that a platform is SBSA and BBR compatible maybe we can name it to arm64sr (SystemReady)?

I like this proposal.

> Armv9 devices aren't far away. Hypothetically, arm64/armv8 and armv8/armv9 could happen if the CPU features justify it.

Yep, so probably  we should consider `armvirt/64` -> `arm64sr/armv8` ?

**Comment by mcbridematt** [comment]
Ok, I had a look at how this could be done today.
The easiest would be to rename the entire `armvirt` target including the 32-bit support.
Maybe `armsr` (Arm SystemReady) as the new target name.

So
```
git mv target/linux/armvirt target/linux/armsr
```
and possibly:
```
git mv target/linux/armsr/32 target/linux/armsr/armv7 # other options: arm32, aarch32
git mv target/linux/armsr/64 target/linux/armsr/armv8 # other options: generic, arm64, aarch64
```

If a future CPU specification justifies it's own profile, it could be named `armv9` or similar.

There are other references to armvirt, like `config/Config-images.in` where we would do a search and replace.

Option 2, rename 64 bit only:

Move `target/linux/armvirt/64` to `target/linux/arm64sr/armv8`
Leave armvirt/32 as is, though I would remove EFI support and return it to how it previously was. Otherwise it will get messy managing GRUB and the image configs.

**Comment by anta5010** [comment]
> The easiest would be to rename the entire `armvirt` target including the 32-bit support.
> Maybe `armsr` (Arm SystemReady) as the new target name.

I agree that renaming `armvirt` to `armsr` and leaving 32 and 64 targets make sense.  In future, if required, separate `armv8` and `armv9` sub-targets can be created under  `armsr/64`

**Comment by mcbridematt** [comment]
I've just appended the 23.05 version of the [armsr name change](https://github.com/openwrt/openwrt/pull/12832) to this pull request.

**Comment by mcbridematt** [comment]
New changes after the main branch version was merged:

- Added 'cherry picked from commit X' or '23.05/5.15 version of X' to all commits
- Cherry picked #12858 to fix mdio-bus-mux description not set properly

This should be ready to go now.

**Comment by ynezz** [comment]
> This should be ready to go now.

**Pull request closed without merging**
