### PR TITLE
ar71xx: add support for Archer C60v2

### PR DESCRIPTION
**Pull request by heinzek**
TP-Link Archer C60v2 is a dual-band AC1350 router, based on Qualcomm/Atheros
QCA9561+QCA9886.

Specification:

775/650/258 MHz (CPU/DDR/AHB)
64 MB of RAM (DDR2)
8 MB of FLASH (SPI NOR)
3T3R 2.4 GHz
2T2R 5 GHz
5x 10/100 Mbps Ethernet
7x LED, 2x button
UART header on PCB

Flash instruction:
Web:
Download lede-ar71xx-generic-archer-c60-v2-squashfs-factory.bin
and use OEM System Tools - Firmware Upgrade site.

Recovery:
Set PC to fixed ip address 192.168.0.66
Download lede-ar71xx-generic-archer-c60-v2-squashfs-factory.bin
and rename it to tp_recovery.bin
Start a tftp server with the file tp_recovery.bin in its root directory
Turn off the router
Press and hold Reset button
Turn on router with the reset button pressed and wait ~15 seconds
Release the reset button and after a short time
the firmware should be transferred from the tftp server
Wait ~30 second to complete recovery.

Flash instruction under U-Boot, using UART:
tftp 0x81000000 lede-ar71xx-...-sysupgrade.bin
erase 0x9f030000 +$filesize
cp.b $fileaddr 0x9f030000 $filesize
reset

### CODE REVIEW

**Comment by hmh** [comment]
I am trying to use these changes in a Brazilian Archer C60v2, but the stock firmware complains of "illegal file type" when I attempt to flash the images from the stock firmware "firmware upgrade" button.

Firmware version: 2.0.0 build 20161206 rel.69298
Hardware Archer C60 v2.0 (BR)  -  likely same as the version for Mexico/MX

The hardware and firmware are most likely based on the US version of the router.

I will try to use the other methods and report if they don't work (or do work), but it would be nice to be able to flash from stock firmware. Any ideas on how to proceed with this?

**Comment by heinzek** [comment]
@hmh You can easy add Your "region" to support_list. Just replace one entry to:
`"{product_name:Archer C60,product_ver:2.0.0,special_id:42520000}\r\n"`

Partition "support_list" on this router have max size 256 byte and It can only contain three entries.

**Comment by hmh** [comment]
@heinzek that worked, thank you very much!

This Archer C60 v2 (BR) box seems to be operating normally, both on 5GHz and 2.4GHz, throughput is also reasonable (80Mbit/s without NAT).

Is it possible to add a submodel with the BR and MX signatures?  That would make the whole thing a lot more user friendly...

FWIW, BR and MX have radios with the eeprom code for US.

**Comment by heinzek** [comment]
I try replace UN region to BR because i cant see any C60v2 with UN region.

**Comment by hmh** [comment]
Isn't it US? It would be bad to remove that, besides it is an stopgap measure at best. Next, someone from MX will ask the same, and then we find out there are other localized firmwares that need more entries, etc.

I will look at how the TL-WR4300 (IL) was done, it makes sense to have submodels on routers that have the same problem of too many localized firmwares *and* a small variant partition like the Archer C60...

I will ask the TP-Link Brazil engineers if they could find out all the firmware variants and what countries they're for, and we could add all of those as a later patchset.  Hopefully, they are allowed to give me that information...

FWIW: this merge request/pull request has my vote and Tested-by to get merged ASAP, it works as-is for  subset of the countries where the Archer C60v2 is sold.   Support for further countries/variants can always be added later as separate merge requests/PRs/patches.

**Comment by mtippmann** [comment]
Any reason this isn't merged yet? Patch works works fine and Archer C60v2 runs without problems.

**Comment by hmh** [comment]
There are a few minor conflicts with OpenWRT master right now due to the commits that ordered model names in several ar71xx files.  They're all trivial to fix, but you might want to respin this PR on top of today's master just in case?

However, one thing that is *not* working fine here, is ath10k-firmware.  The one in OpenWRT master disagrees rather severely with my TP-Link C60v2 BR.

The QCA9888 in the C60v2 will crash the firmware 10.4-3.4-00082 and 10.4-3.4-00104 (currently in OpenWRT master).

Version 10.4-3.2-00072 is stable and works well, so reverting commit 2d3a73afc4379031ee063df368e1290690f64d6f from OpenWRT master works as a temporary fix.   I have also tested (upstream) version  10.4-3.5.3-00053, and it seems to be working correctly.

**Comment by hmh** [comment]
Archer C60v2 QCA9888 is operating very, very stable with FW 10.4-3.5.3-00053.  And that firmware has just been merged by linux-firmware upstream, as well.

I suggest that the OpenWRT ath10k-firmware package be updated to match the new upstream set of stable firmware (sent to linux-firmware).  That would make the Archer C60v2 (US,EU) ready for an upcoming OpenWRT 2018.x stable release.

**Comment by hmh** [comment]
This PR depends on #744.

**Comment by rakeshku-test** [comment]
@hmh I cloned latest OpenWRT repo, applied this patch and built image for C60v2(EU). 
TP link UI accepted the image, however post upgrade, router didn't provide IP to dhcp clients. 
It appears to be bricked. 
I did recover it back to stock FW using tftp recovery. 
But I do want to use OpenWRT on it. 
It's the most economical dual-band router out there, with decent HW specs. 
Any pointers will be greatly appreciated.

**Comment by hmh** [comment]
@rakeshku-test: looks like you're hitting a generic OpenWRT issue, not related to this merge request.

Note that adding a new router model to OpenWRT [via patches] requires touching some makefiles to ensure a rebuild, regenerating the .config, etc.  If you fail to do it correctly, it can indeed generate a broken image that won't work right.

You could do a "make dirclean" and then setup the feeds and remake the config, to cleanup any mess left over.  It should also work without any annoyances when you apply all patches *right after* cloning openwrt.  And by that I mean you do not run "make clean" or *anything else* in the freshly cloned openwrt work tree, before you apply the patches.  Only after they have been applied, can you do anything on the work tree.

But these are all generic OpenWRT instructions/details, unrelated to this particular merge request.

**Comment by pepe2k** [comment]
@heinzek,

Thank you for your contribution! I have merged your changes into [my staging tree](https://git.openwrt.org/openwrt/staging/pepe2k.git).

Cheers,
Piotr

**Comment by rakeshku-test** [comment]
Thanks. I see that it's finally merged into snapshot.

**Comment by oneunits** [comment]
1. I see only 22 dbm for 2.4 wifi. Is it limit for chip?
2. Please describe me procedure for install original firmware.
My model C60V2-RU. special_id=52550000.

**Pull request closed without merging**
