### PR TITLE
kernel: 5.10: backport additional qca8k fixes

### PR DESCRIPTION
**Pull request by Ansuel**
Backport 3 additional fixes for qca8k.
- Fix MTU calculation
- Fix a bug with config set to the wrong PAD when secondary cpu port is defined.
- Fix redundant check in parse_port_config

Backport qca8k new feature:
- Ageing configuration support
- Add 2 missing counter on qca8337
- Convert to regmap
- Standardize define and code with GENMASK AND BITFILED macro
- Add mdb add/del support

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@adschm can you merge this?

**Comment by Leo-PL** [comment]
I'm probably missing something, or another patch adding `.reg_update_bits` to `struct regmap_config` is needed. In vanilla 5.10.87 I don't see this member either.
I got the following error trying to rebuild:
```
drivers/net/dsa/qca8k.c:282:10: error: 'struct regmap_config' has no member named 'reg_update_bits'
  282 |         .reg_update_bits = qca8k_regmap_update_bits,
      |          ^~~~~~~~~~~~~~~
drivers/net/dsa/qca8k.c:282:9: warning: the address of 'qca8k_regmap_update_bits' will always evaluate as 'true' [-Waddress]
  282 |         .reg_update_bits = qca8k_regmap_update_bits,
      |         ^
cc1: some warnings being treated as errors
make[8]: *** [scripts/Makefile.build:280: drivers/net/dsa/qca8k.o] Error 1
make[7]: *** [scripts/Makefile.build:497: drivers/net/dsa] Error 2
make[6]: *** [scripts/Makefile.build:497: drivers/net] Error 2
make[5]: *** [Makefile:1822: drivers] Error 2
make[5]: Leaving directory '/work/builds/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-5.10.87'
make[4]: *** [Makefile:21: /work/builds/openwrt/ath79/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-5.10.87/.modules] Error 2
make[4]: Leaving directory '/work/builds/openwrt/ath79/target/linux/ath79'
make[3]: *** [Makefile:11: compile] Error 2
```

**Comment by Leo-PL** [comment]
I think I found the missing patch by accident: https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=02d6fdecb9c3

**Comment by Leo-PL** [comment]
I cherry-picked that missing patch manually a few hours before, built and flashed the image. Now testing this together with Multi-CPU on my C7v2 "on production". Haven't yet looked into advanced features so far, but a typical configuration with software bridges assisted by DSA and software VLANs work.

Traffic through SGMII port on my C7v2 is still less stable and slower than through RGMII port - I have to look into that in spare time, it's likely that no-one cared yet to tune that.

**Comment by Ansuel** [comment]
@Leo-PL did you enable assisted learning on cpu port?

**Comment by Leo-PL** [comment]
@Ansuel not yet, any TL;DR howto? I guess I need to cherry-pick something more for that.

On RGMII I get very consistent 400Mbps towards router CPU and 200Mbps from router's CPU on iperf3. Without packet loss. On SGMII it's far less consistent, and I get around 200Mbps both ways, with some retransmissions, and the speed jitters up to around 40Mbps typically throughout the test.
With flow offload enabled, I can get only around 220Mbps UL/DL NAT performance to the internet.

I'll use this build for a while, though, to properly test #4849 which could unblock myself from hitting 21.02 now.

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 5cf198f7643975a12d7c4f95674349988d76b711 and 1e4469b090a7e3234345c1b7f17c956ec7dc0b81.

**Pull request closed without merging**
