### PR TITLE
[21.02] rampis: feed zbt-we1026 external watchdog (backported and adapted)

### PR DESCRIPTION
**Pull request by nemesifier**
This patch backports and adapts two fixes for zbt-we1026 to the OpenWrt 21.02 branch:

- fb2801b82c06878ae2ad20b8f95546c34ed3cdf4
- 1a97c03d864ee5ab917aff2988c62fce223c041e

Tested both compilation and usage, the boot loop on OpenWrt 21.02 affecting this device is fixed with this patch.

### CODE REVIEW

**Comment by Ansuel** [comment]
@nemesisdesign pls split this in 2 backport commits... also instead of using "backported from" just use `cherry-pick -x COMMIT`
If you did some changes to the backport commit you have to sign it with -s and add a tag with the changes done. Example`[ adapted to old dts ]`

**Comment by nemesisdesign** [comment]
@Ansuel the problem is that both commits on master work on a file which has been removed on master

**Comment by Ansuel** [comment]
@nemesisdesign yes the idea is that, if you need help just ask :D i'm here to help

**Comment by nemesisdesign** [comment]
@Ansuel: done, is it good?

**Comment by nemesisdesign** [comment]
Rebased. Ping @Ansuel @hauke

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
