### PR TITLE
tools/tar: update to 1.35

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
https://lists.gnu.org/archive/html/info-gnu/2023-07/msg00005.html

Refresh patches:
- 100-symlink-force-root-name.patch
- 110-symlink-force-permissions.patch

### CODE REVIEW

**Comment by neheb** [comment]
From IRC

```
so, are github packages.git builders somehow using the host distro tools (like tar)? it took me a while, but I figured out they're not using this patch:
https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=tools/tar/patches/100-symlink-force-root-name.patch;h=8a8ebc0c4cfdb4c4af1cbc90f33201274ca736fd;hb=HEAD
that frankly hasn't been necessary for 6 years, with https://git.savannah.gnu.org/cgit/tar.git/commit/?id=da8d0659a6fe8faf76b3a3275cf1f403e78edb1f
but anyway, I'm seeing that I can only match the builders' PKG_MIRROR_HASH when I use my distro's tar
I guess maybe that's not an "openwrt core" question; but it'd also be nice to drop that patch IMO
```

**Comment by Ansuel** [comment]
@neheb think there is a bit of confusion here... on IRC it is pointed out that --numeric-owner got fixed and tar can correctly produce deterministic archive BUT our patch actually force root/root as owner instead of using the system name for user 0. (problematic with macos where root group is wheel)

Switching to --numeric-owner would result in the same thing with the difference that owner is 0/0.

Problem of doing such change is that AFAIK the tool is used to create tar of cloned repo and changing the owner i think change the hash of the tar resulting in us having to wipe any kind of mirror as the hash would mismatch.

**Comment by neheb** [comment]
It wouldn’t be the first time tarball hashes broke. SVN tarballs are notoriously nondeterministic

**Comment by Ansuel** [comment]
Well if we want to drop the patch we have to set --numeric-owner and wipe our entire dl mirror, it's really not that trivial

**Comment by neheb** [comment]
Thinking about it, switching to —numeric-owner should be possible. Just have all packages with old hashes and old tarballs on mirrors. On version update, they’ll use the updated ones.

**Comment by Ansuel** [comment]
@neheb can you do a quick test. You may be right with the big statement that regenerating the tar will result in a different correct hash

**Comment by neheb** [comment]
Not sure I get what you mean. Removing the patch will break git clones, which is not an issue since they’re all mirrored. On version update of the package, the proper hash gets generated and mirrored.

The only problematic part of this proposal is PKG_RELEASE bumps with the version remaining the same. That’s an edge case IMO.

btw for context, @nbd

**Comment by neheb** [comment]
wait... --numeric-owner is already used. this patch should be no-op.

**Comment by Ansuel** [comment]
@neheb the patch overwrite what numeric-owner does. But let me do some testing...

**Comment by neheb** [comment]
autoreconf makes this fail for me:

https://gist.github.com/neheb/079425cfa6b64806cba39d78c5166af7

**Comment by neheb** [comment]
ping @mpratt14 gnulib issue i think.

**Comment by mpratt14** [comment]
it's trying to run aclocal

tar depends on automake right now for some reason but is not set that way currently 

either set the dependency or use AM_TOOL_PATHS_FAKE to skip using autotools

I don't know why though, I only looked at the log

**Comment by mpratt14** [comment]
oh, i see you added autoreconf to the makefile which makes it depend on the autotools

**Comment by neheb** [comment]
didn't work. I did

```
--- a/tools/tar/Makefile
+++ b/tools/tar/Makefile
@@ -22,6 +22,9 @@ include $(INCLUDE_DIR)/host-build.mk
 HOSTCC := $(HOSTCC_NOCACHE)
 HOSTCXX := $(HOSTCXX_NOCACHE)
 
+HOST_MAKE_FLAGS += \
+       $(AM_TOOL_PATHS_FAKE)
+
 HOST_CONFIGURE_ARGS += \
        --without-posix-acls \
        --without-selinux 
```

**Comment by Ansuel** [comment]
@neheb i just tested and i can confirm different tar are produced... the patch force the use of root user  even with numerical-owner used

**Comment by neheb** [comment]
so this patch makes numetical-owner no-op. Now I'm sure it should be removed.

**Comment by Ansuel** [comment]
@neheb think the history of this is...

the patch was done before --numeric-owner to handle macos having wheel as group
then --numeric-owner was introduced but we had this patch and to now invalidate all the current hash we forced root root to keep this

And here we are with the same exact problem.

**Comment by neheb** [comment]
I don't see an issue. Old root/root tarballs can be kept and newer 0/0 ones can be generated on package version update.

**Comment by Ansuel** [comment]
@neheb well we can see what happen.

Anyway the breaking case will be when
1. for some reason the github mirror fails to download
2. the repo is cloned
3. the archive is generated
4. the hash is compared and doesn't match the one saved in makefile

outside this strange corner case everything should be O.K.

**Comment by mpratt14** [comment]
> didn't work. I did
> 
> ```
> --- a/tools/tar/Makefile
> +++ b/tools/tar/Makefile
> @@ -22,6 +22,9 @@ include $(INCLUDE_DIR)/host-build.mk
>  HOSTCC := $(HOSTCC_NOCACHE)
>  HOSTCXX := $(HOSTCXX_NOCACHE)
>  
> +HOST_MAKE_FLAGS += \
> +       $(AM_TOOL_PATHS_FAKE)
> +
>  HOST_CONFIGURE_ARGS += \
>         --without-posix-acls \
>         --without-selinux 
> ```

also remove autoreconf?

**Comment by neheb** [comment]
autoreconf is needed to fix macOS.

**Comment by mpratt14** [comment]
isn't there an Makefile.in already generated that can be patched as well? otherwise tar will have to depend on automake being built first to actually do autoreconf in a first-time build

or did you mean the CI error...?

**Comment by neheb** [comment]
No idea how to modify Makefile.in

**Comment by Ansuel** [comment]
Any news with this?

**Comment by mpratt14** [comment]
we have to make a decision:

A. reorder tools dependencies so that tar build depends on automake build

or

B. remove autoreconf from tar build and patch the shipped version of the automake generated files directly (patch Makefile.in instead of Makefile.am)

**Comment by Ansuel** [comment]
> by the way, we can, instead of patching, override the value of tar_LDADD by adding it to HOST_MAKE_FLAGS

mhhh what do you mean? how ugly it would be?

Also a little ot but do you think it's doable to introduce mandatory dependency on zstd tool for everything? (example dependency of zstd for make package/x/download ?)

**Comment by mpratt14** [comment]
Yeah it would be a little bit ugly to have this in our own Makefile, but it would (hopefully) be temporary pending the next release of gnu tar, so this would be option C

```
diff --git a/tools/tar/Makefile b/tools/tar/Makefile
index 2d15fe6e69..d7ac01ca85 100644
--- a/tools/tar/Makefile
+++ b/tools/tar/Makefile
@@ -28,6 +28,22 @@ HOST_CONFIGURE_ARGS += \
        --disable-acl \
        --disable-nls

+HOST_MAKE_FLAGS += \
+       tar_LDADD=' \
+               $$$$(LIBS) ../lib/libtar.a ../gnu/libgnu.a \
+               $$$$(LIB_ACL) \
+               $$$$(LIB_CLOCK_GETTIME) \
+               $$$$(LIB_EACCESS) \
+               $$$$(LIB_GETRANDOM) \
+               $$$$(LIB_HARD_LOCALE) \
+               $$$$(FILE_HAS_ACL_LIB) \
+               $$$$(LIB_MBRTOWC)\
+               $$$$(LIB_SELINUX) \
+               $$$$(LIB_SETLOCALE_NULL) \
+               $$$$(LIBINTL) \
+               $$$$(LIBICONV) \
+       '
+
 define Host/Uninstall
        -$(call Host/Compile/Default,uninstall)
 endef
```


> Also a little ot but do you think it's doable to introduce mandatory dependency on zstd tool for everything? (example dependency of zstd for make package/x/download ?)

It should be easy to make foo/bar/download targets depend on the tools stampfile, but to make it specific to the packages targets there would have to be some kind of conditional, or else downloading zstd (and the rest) would fail by requiring it to be already built... overall it's probably not difficult to do

**Comment by Ansuel** [comment]
> Yeah it would be a little bit ugly to have this in our own Makefile, but it would (hopefully) be temporary pending the next release of gnu tar, so this would be option C

think it's better to wait for next tar release



> It should be easy to make foo/bar/download targets depend on the tools stampfile, but to make it specific to the packages targets there would have to be some kind of conditional, or else downloading zstd (and the rest) would fail by requiring it to be already built... overall it's probably not difficult to do

maybe we reference the list of mandatory tools and depends on that and ignore this dependency?

**Comment by Ansuel** [comment]
Superseded by: #15743

**Pull request closed without merging**
