### PR TITLE
generic: various fixes and improvements for routerboot sysfs driver

### PR DESCRIPTION
**Pull request by f00b4r0**
This PR combines several minor updates to the routerboot sysfs driver

@xback if you want to give it a spin

### CODE REVIEW

**Comment by ch6574** [comment]
Just an FYI, I tested this on an rb493g, and can confirm the cpufreq is now showing up.

old: 
==> /sys/firmware/mikrotik/soft_config/cpufreq_index <==
tail: read error: Socket type not supported

new (at 680 MHz)
==> /sys/firmware/mikrotik/soft_config/cpufreq_index <==
0x00000360

new (at 800 MHz)
==> /sys/firmware/mikrotik/soft_config/cpufreq_index <==
0x000003f0

**Comment by rogerpueyo** [comment]
Tested on an AR7241-based OmniTIK UPA-5hnD (omni-5fe), where I was also getting `tail: read error: Socket type not supported` and now:

400 MHz:
```
0x000001b0
```

350 MHz:
```
0x00000120
```

300 MHz:
```
0x00000090
```

250 MHz:
```
0x00000000
```

Actually, here's the whole soft_config partition, just in case it can help somehow:
```
400 MHz
0000000 7466 6f53 53c1 27b8 0004 000c 0000 01b0
0000010 0004 000a 0000 0002 0004 0001 0000 0000
0000020 0004 0002 0000 0002 0004 0003 0000 0001
0000030 0004 0004 0000 0000 0004 0005 0000 0000
0000040 0004 0007 0000 0000 0004 0009 0000 0000
0000050 0004 000f 0000 0001 0004 0015 0000 0000
0000060 0004 0017 0000 0000 0004 000d 0000 0000
0000070 0004 0006 362e 3437 0008 000b 0000 0000
0000080 0001 a76f 0004 001b 0000 0000 0004 001f
0000090 0014 0258 0000 0000 0000 0000 0000 0000
00000a0 0000 0000 0000 0000 0000 0000 0000 0000
*
0001000

350 MHz
0000000 7466 6f53 732b e12a 0004 000c 0000 0120
0000010 0004 000a 0000 0002 0004 0001 0000 0000
0000020 0004 0002 0000 0002 0004 0003 0000 0001
0000030 0004 0004 0000 0000 0004 0005 0000 0000
0000040 0004 0007 0000 0000 0004 0009 0000 0000
0000050 0004 000f 0000 0001 0004 0015 0000 0000
0000060 0004 0017 0000 0000 0004 000d 0000 0000
0000070 0004 0006 362e 3437 0008 000b 0000 0000
0000080 0001 a969 0004 001b 0000 0000 0004 001f
0000090 0014 0258 0000 0000 0000 0000 0000 0000
00000a0 0000 0000 0000 0000 0000 0000 0000 0000
*
0001000

300 MHz
0000000 7466 6f53 90e5 01b9 0004 000c 0000 0090
0000010 0004 000a 0000 0002 0004 0001 0000 0000
0000020 0004 0002 0000 0002 0004 0003 0000 0001
0000030 0004 0004 0000 0000 0004 0005 0000 0000
0000040 0004 0007 0000 0000 0004 0009 0000 0000
0000050 0004 000f 0000 0001 0004 0015 0000 0000
0000060 0004 0017 0000 0000 0004 000d 0000 0000
0000070 0004 0006 362e 3437 0008 000b 0000 0000
0000080 0001 ac96 0004 001b 0000 0000 0004 001f
0000090 0014 0258 0000 0000 0000 0000 0000 0000
00000a0 0000 0000 0000 0000 0000 0000 0000 0000
*
0001000

250 MHz
0000000 7466 6f53 1899 ba9b 0004 000c 0000 0000
0000010 0004 000a 0000 0002 0004 0001 0000 0000
0000020 0004 0002 0000 0002 0004 0003 0000 0001
0000030 0004 0004 0000 0000 0004 0005 0000 0000
0000040 0004 0007 0000 0000 0004 0009 0000 0000
0000050 0004 000f 0000 0001 0004 0015 0000 0000
0000060 0004 0017 0000 0000 0004 000d 0000 0000
0000070 0004 0006 362e 3437 0008 000b 0000 0000
0000080 0001 b1fa 0004 001b 0000 0000 0004 001f
0000090 0014 0258 0000 0000 0000 0000 0000 0000
00000a0 0000 0000 0000 0000 0000 0000 0000 0000
*
0001000
```

**Comment by f00b4r0** [comment]
@ch6574 Just curious: only two frequency steps on your device?
@rogerpueyo thanks!

**Comment by ch6574** [comment]
It goes slower - do you want me to test and check those values too?

**Comment by f00b4r0** [comment]
> It goes slower - do you want me to test and check those values too?

If I want to cook an implementation, I'd need the values for _each available step_, yes please :)

**Comment by ch6574** [comment]
Not a problem, here we go:

```
 100MHz		0x00000000
 150MHz		0x00000090
 200MHz		0x00000120
 300MHz		0x000001b0
 400MHz		0x00000240
 600MHz		0x000002d0
```

**Comment by f00b4r0** [comment]
Excellent! This shows it goes in 0x90 increments, just like @rogerpueyo AR7241. It just goes further. Now I have an idea of how to implement this ;) Thanks!

**Comment by rogerpueyo** [comment]
I've got an IPQ4018-based device which does not show the cpufreq_index parameter:
```
root@OpenWrt:~# ls /sys/firmware/mikrotik/soft_config/
bios_version  boot_device   boot_proto    cpu_mode      uart_speed
boot_delay    boot_key      commit        silent_boot
```

Available values are::
image

Is it useful for you if I paste the soft_config content here, or do you prefer me to send you the whole file?

**Comment by f00b4r0** [comment]
@rogerpueyo If this setting is available in `hard_config` (which is unknown at this stage), ideally and to be thorough I'd need the hard_config dump of all values, to find out which tag(s) is(are) concerned and how the values are computed.
Meanwhile I'll try to add a commit to this PR to add support for AR7xxx cpufreq :)

**Comment by f00b4r0** [comment]
@ch6574 @rogerpueyo if you guys want to give a shot at the last patch, feel free to report ;)

**Comment by ch6574** [comment]
Just took it for a spin, and now I get (at 680 MHz), which corresponds correctly to the 8 settings this board has.

```
==> /sys/firmware/mikrotik/soft_config/cpufreq_index <==
a b c d e f [g] h 
```

**Comment by f00b4r0** [comment]
Ping?

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
