### PR TITLE
treewide: refresh all patches with quilt

### PR DESCRIPTION
**Pull request by neheb**
Cleans up patch fuzz and whatnot.

Ran with
find ./package -type d -name patches | rev | cut -d '/' -f 2 | rev > p
while read PKG;make package/$PKG/refresh;end < p

Signed-off-by: Rosen Penev <rosenp@gmail.com>

First patch is to fix refreshing lua host patches as they live in a different directory.
The non treewide patches are to fix quilt not being able to deal with file renames properly.

### CODE REVIEW

**Comment by jow-** [comment]
NAK on the hard coded file rename handling in Makefiles

**Comment by aparcar** [comment]
This is an improved followup of https://github.com/openwrt/openwrt/pull/3899

**Comment by neheb** [comment]
OK. No more Makefile hackery.

**Comment by adschm** [comment]
I agree with @jow- , but particularly I do not see the benefit of all this. The refreshs don't seem to fix any actual offset issues issues, mostly they just remove some optional lines. But I do not see why this is _needed_?

**Comment by cotequeiroz** [comment]
I'm also against this, at least for the OpenSSL patches.  I don't particularly like the function names cutoff.  I wish there was a flag to remove the index lines in git, though.  I'll **think** about running a sed script to get rid of them the next time around.  I don't think we need to add a commit just for aesthetic reasons.  OpenSSL seems to be releasing a new security update every month, anyway.  As for the manual adjustments or having to remove the index lines when patch management is done with git, they create extra maintenance burden.

The value of this is if we were to add a `make refresh` check, as it is done in the packages feed, but even then, I would rather check for patch fuzziness when applying them, not just to see if `make refresh` comes up with a difference.

**Comment by neheb** [comment]
@adschm I mean... kernel refreshes are not needed either. But it is done anyway. The main value is keeping the tree clean.

And yes, I understand you took care of a lot of the fuzz posed in the initial PR separately.

@cotequeiroz AFAIK , quilt uses diff from GNU diffutils by default. It has the line length hardcoded. I believe quilt allows to override the diff command.

**Comment by adschm** [comment]
> @adschm I mean... kernel refreshes are not needed either. But it is done anyway. The main value is keeping the tree clean.

Well, kernel refreshs actually change some positions (i.e. fix at least offsets). With packages, it seems more appealing to leave the means of refreshing to the package maintainers/patch authors. Those can then use quilt or git-based refresh based on their preferences. This is not really possibly with kernel where more people tend to work with the same patches, and it's more patches per target/unit.

**Comment by cotequeiroz** [comment]
> @cotequeiroz AFAIK , quilt uses diff from GNU diffutils by default. It has the line length hardcoded. I believe quilt allows to override the diff command.

I went through that path, as I would really like to just `make refresh` and have the patches all tidy and shiny.  However, that setting is just for `quilt diff`.  `quild refresh` has `diff` hardcoded in [quilt/scripts/patchfns.in:744](http://git.savannah.nongnu.org/cgit/quilt.git/tree/quilt/scripts/patchfns.in#n744) 😢.

Speaking of handling refresh manually, it seems I missed `410-eng_devcrypto-add-configuration-options.patch` 🤦‍♂️, so you have my approval (whatever it is worth) for the openssl patch.  My apologies for not realizing sooner that your commit actually fixes it.

As a result, I've finally written a script to prepare and ship the patches from my openssl fork to openwrt, and it shouldn't happen again, at least for the patches I regularly maintain.  I added the `--zero-commit` option, and took the opportunity get rid of the `index` lines as well with `sed -e '/^index [0-9a-f]\{10\}\.\.[0-9a-f]\{10\}\( [0-9]\{6\}\)\?$/d'`.  If this PR does not get pushed, then I'll wait for the next bump to implement it.

**Comment by neheb** [comment]
On Sun, Mar 28, 2021 at 12:17 PM Eneas U de Queiroz <
***@***.***> wrote:

> @cotequeiroz <https://github.com/cotequeiroz> AFAIK , quilt uses diff
> from GNU diffutils by default. It has the line length hardcoded. I believe
> quilt allows to override the diff command.
>
> I went through that path, as I would really like to just make refresh and
> have the patches all tidy and shiny. However, that setting is just for quilt
> diff. quild refresh has diff hardcoded in quilt/scripts/patchfns.in:744
> <http://git.savannah.nongnu.org/cgit/quilt.git/tree/quilt/scripts/patchfns.in#n744>
> 😢.
>
Sounds like a patch should be submitted upstream.

> Speaking of handling refresh manually, it seems I missed
> 410-eng_devcrypto-add-configuration-options.patch 🤦‍♂️, so you have my
> approval (whatever it is worth) for the openssl patch. My apologies for not
> realizing sooner that your commit actually fixes it.
>
Seems nobody likes this PR.

> As a result, I've finally written a script to prepare and ship the patches
> from my openssl fork to openwrt, and it shouldn't happen again, at least
> for the patches I regularly maintain. I added the --zero-commit option,
> and took the opportunity get rid of the index lines as well with sed -e
> '/^index [0-9a-f]\{10\}\.\.[0-9a-f]\{10\}\( [0-9]\{6\}\)\?$/d'. If this
> PR does not get pushed, then I'll wait for the next bump to implement it.
>
I still think make package/x/refresh is adequate. The context shortening
doesn't seem to make a difference.

**Comment by cotequeiroz** [comment]
> Sounds like a patch should be submitted upstream.

It's not so trivial.  You can always add a wrapper script as `diff`, and use a different program.  The problem is that there are GNU diff options being passed that are not supported by `git diff`.  QUILT copies the original files to a temporary directory, and then diffs them there, passing the `--label` to override their names. I could ignore the option, but then:
```diff
diff -p -u --label a/Configure --label b/Configure .pc/100-Configure-afalg-support.patch/Configure Configure
--- a/Configure
+++ b/Configure
@@ -1545,7 +1545,9 @@ unless ($disabled{"crypto-mdebug-backtra

 unless ($disabled{afalgeng}) {
     $config{afalgeng}="";
-    if (grep { $_ eq 'afalgeng' } @{$target{enable}}) {
+    if ($target =~ m/openwrt$/) {
+        push @{$config{engdirs}}, "afalg";
+    } elsif (grep { $_ eq 'afalgeng' } @{$target{enable}}) {
         my $minver = 4*10000 + 1*100 + 0;
         if ($config{CROSS_COMPILE} eq "") {
             my $verstr = `uname -r`;
```

``` diff
git diff --no-index -p -u .pc/100-Configure-afalg-support.patch/Configure Configure
diff --git a/.pc/100-Configure-afalg-support.patch/Configure b/Configure
index b286dd0678..eb4ae68c02 100755
--- a/.pc/100-Configure-afalg-support.patch/Configure
+++ b/Configure
@@ -1545,7 +1545,9 @@ unless ($disabled{"crypto-mdebug-backtrace"})

 unless ($disabled{afalgeng}) {
     $config{afalgeng}="";
-    if (grep { $_ eq 'afalgeng' } @{$target{enable}}) {
+    if ($target =~ m/openwrt$/) {
+        push @{$config{engdirs}}, "afalg";
+    } elsif (grep { $_ eq 'afalgeng' } @{$target{enable}}) {
         my $minver = 4*10000 + 1*100 + 0;
         if ($config{CROSS_COMPILE} eq "") {
             my $verstr = `uname -r`;
```

**Comment by neheb** [comment]
@adschm can at least the first patch be merged? That's an actual bugfix.

**Comment by adschm** [comment]
> @adschm can at least the first patch be merged? That's an actual bugfix.

I cannot really judge; consider making it a separate PR or supply via the mailing list, so it's not hidden behind a "refresh patches" label ...

**Comment by neheb** [comment]
This was effectively rejected.

**Pull request closed without merging**
