### PR TITLE
version.mk: don't use comma in version sed scripts

### PR DESCRIPTION
**Pull request by pprindeville**
Especially not if comma is a potential delimiter for the
value being replaced, like "Redfish Solutions, LLC" for the
manufacturer (or URLs, where commas are common).

Fixes FS#1151.

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by pprindeville** [comment]
@KanjiMonster Thanks for the suggestion.  Ended up going with something pretty much as you suggested.

**Comment by pprindeville** [comment]
Tested it with:

```
CONFIG_DEVEL=y
CONFIG_IMAGEOPT=y
CONFIG_VERSIONOPT=y
CONFIG_VERSION_MANUFACTURER="Tom's house of routers, LLC"
CONFIG_VERSION_SUPPORT_URL="http://www.redfish-solutions.com/support?product=router&model=xeon"
```

and I get:

```
NAME="OpenWrt"
VERSION="SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt SNAPSHOT"
VERSION_ID="snapshot"
HOME_URL="http://www.redfish-solutions.com/"
BUG_URL="http://bugs.lede-project.org/"
SUPPORT_URL="http://www.redfish-solutions.com/support?product=router&model=xeon"
BUILD_ID="r5937+8-e003f33"
LEDE_BOARD="x86/64"
LEDE_ARCH="x86_64"
LEDE_TAINTS="no-all busybox"
LEDE_DEVICE_MANUFACTURER="Tom's House of Routers, LLC"
LEDE_DEVICE_MANUFACTURER_URL="http://www.redfish-solutions.com/"
LEDE_DEVICE_PRODUCT="Generic"
LEDE_DEVICE_REVISION="v0"
LEDE_RELEASE="OpenWrt SNAPSHOT r5937+8-e003f33"
```

and as you can see, comma, ampersand, and squote are all intact.

**Comment by pprindeville** [comment]
@NeoRaider Any issues or are we good for a merge?  Thanks

**Comment by pprindeville** [comment]
Was previously in LEDE as https://github.com/lede-project/source/pull/1586

**Comment by jow-** [comment]
Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/jow.git

**Comment by pprindeville** [comment]
Thanks

**Pull request closed without merging**
