### PR TITLE
ipq806x: fix USB bug in 5.10 dtsi additions 

### PR DESCRIPTION
**Pull request by Lanchon**
@mans0n 
the global fixes, as per [your request](https://github.com/openwrt/openwrt/pull/9657#issuecomment-1093840071).

i strongly advice to backport this to 22.03 for reasons explained in the commit.

tested on my ipq8065 device.

fixes: https://github.com/openwrt/openwrt/pull/9657

thanks!

### CODE REVIEW

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 3a4d972d43987e1ab0f697817c0f68d1a4a706dc and 284f2c2ae0e569660effa61c9f8d0f6459a2ae19.

**Comment by Lanchon** [comment]
@hauke thank you!

FYI...

as you know, this PR renames the two USB XHCI as seen from userland. (the rename would have happened anyway when switching to kernel 5.15.)

but as things stand, 22.03 is going out with the old names. IMHO it makes sense to switch ASAP, before more users code their userland stuff that depends on the old names, as we are going to break that later and cause some grief.

i reviewed all ipq806x ports (and so did @mans0n to some degree) and found:
- no devices enabled just one USB port (obviously, as that wouldn't have worked before this fix), so the name swap will not disable any port on any device.
- only a couple of devices attempted a half-baked fix (which i removed in the first commit of this PR).

so my conclusion is: it is safe to cherrypick to 22.03; the only visible change will be the name swap.

please note that the current, unpatched 22.03 USB code might have issues we don't know of. the drivers have the clocks and resets of the blocks swapped, and if/when they use them, stuff will break. for example: ports seem to work; but maybe if i remove a device from one port while another is under active use in the other port, the second device might malfunction because the driver decides to cycle reset to the wrong XHCI. this is a hypothesis out of the blue of course. but since the lines are there in the hardware, it is not unthinkable the driver might use them under some unknown condition.

thanks again.

**Comment by hauke** [comment]
I cherry picked them to 22.03 in aa9ae01ee38005dfb93a2e49254ee7c4f9c53331 and b142587f6e8a401da19dfc2f5db3474687fbf194

**Comment by Lanchon** [comment]
good call! thanks :)

**Comment by Lanchon** [comment]
hi @hauke

with this PR backported to 22.03, the way is paved for having this device backported too: https://github.com/openwrt/openwrt/pull/9835

i see no possible harm, and the backport is fully tested. should i ask anybody in particular about this before 22.03 is out?

thank you!

**Pull request closed without merging**
