### PR TITLE
kernel: bump 5.4 to 5.4.139

### PR DESCRIPTION
**Pull request by graysky2**
Manually rebased:
 layerscape
  pending-5.4/701-net-0009-dpa-SDK-DPAA-1.x-Ethernet-driver.patch*
  patches-5.4/701-net-0317-staging-fsl_ppfe-eth-separate-mdio-init-from-mac-ini.patch
  patches-5.4/701-net-0399-staging-fsl_ppfe-eth-Enhance-error-checking-in-platf.patch*

All other patches automatically rebased.

Build system: x86_64
Build-tested: ipq806x/R7800
Run-tested: not tested

*Fixed with rediff due to malformation or unexpected EOF

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master.

**Comment by graysky2** [comment]
@hauke - Probably want to have someone run test 5.4.139 and review my work with Layerscape...

**Comment by graysky2** [comment]
@hauke - I now have 5.4.139 run tested.  Do you have that commit pulled into a staging repo somewhere?

Run-tested: ipq806x/R7800

**Comment by hauke** [comment]
Sorry I did not notice that you pushed an update after I took the patch. Could you just reopen this for the 5.4.139  update please. 
The layerscape patches are applying now again.

**Comment by graysky2** [comment]
I will create a new PR as the one I made no longer cleanly applies against HEAD.

**Pull request closed without merging**
