### PR TITLE
tegra: add kernel 6.1 support

### PR DESCRIPTION
**Pull request by xback**
Adds support for kernel 6.1 to the Tegra target.

This series has been compile-tested only using kernel 5.15 and 6.1
It has been tested tough on nvidia jetson nano with additional patcheso n top of these.

### CODE REVIEW

**Comment by xback** [comment]
@tmn505 
Is enabling VDE still needed here for proper functioning on trimSlice?

**Comment by namiltd** [comment]
change:
CONFIG_USB_XHCI_TEGRA=y

**Comment by xback** [comment]
@namiltd 
Can you also elaborate why?
It is also disabled in 5.15

The plan here is to first switch to 6.1 with minimal changes.

**Comment by namiltd** [comment]
There were compilation errors before, but now everything is fine.

**Comment by tmn505** [comment]
> Is enabling VDE still needed here for proper functioning on trimSlice?

Nothing changed in that regard, so yes, it's still needed.

**Comment by xback** [comment]
@tmn505 
Thanks, I found the details regarding this in your repo

The plan is to first do the conversion to 6.1, and only then add jetson stuff.
i'm reworking it locally as we speak.

**Comment by tmn505** [comment]
ping

**Comment by xback** [comment]
@tmn505 
I'm finally out of the hospital again and will finish this next week

**Comment by hauke** [comment]
I merged the changes from @tmn505 adding support for kernel 6.6 some time ago. 

If kernel 6.6 is working for one of you could you please create a PR or send a patch to use kernel 6.6 by default.

**Pull request closed without merging**
