### PR TITLE
[19.07] uboot-kirkwood: fix ethernet and usb

### PR DESCRIPTION
**Pull request by CHKDSK88**
Before 2019.01 version was introduced patch, which changes cache
routines: 93b283d4 ("ARM: CPU: arm926ejs: Consolidate cache
routines to common file"). Unfortunately that patch make ethernet
and usb in kirkwood broken.

This patch backport commit 599f7aa5 ("ARM: kirkwood: disable dcache
for Kirkwood boards"), which are fix for that problem.

Fixes: dc08514e6d ("uboot-kirkwood: update to 2019.01")

Run tested: pogoplugv4

Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>

### CODE REVIEW

**Comment by ynezz** [comment]
@obsy can I have your tested-by on this one as well? Thanks!

**Comment by obsy** [comment]
Yes, usb now working on NSA-310.

Tested-by: Cezary Jackiewicz <cezary@eko.one.pl>

**Comment by CHKDSK88** [comment]
Added @obsy to commit message.

**Comment by CHKDSK88** [comment]
Thank You. Done.

**Comment by bobafetthotmail** [comment]
@kofec this sounds like a fix for the problem you had

**Comment by ynezz** [comment]
Thanks! Merged into my tree.

**Pull request closed without merging**
