### PR TITLE
kernel: bump 5.10 to 5.10.139

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by graysky2** [comment]
Can someone refresh the build checks; at least one is due to a dl error.

**Comment by graysky2** [comment]
@ynezz @hauke - is there a way to grant my user permission to refresh a test build?  For reference, see conversation in: https://github.com/openwrt/openwrt/pull/10436

**Comment by ynezz** [comment]
>  is there a way to grant my user permission to refresh

I assume it's only available to team members. Anyway, as a reviewer, you usually want to see those prior build failures and decide by yourself if that failure is transitory (like for example those download issues) or should be handled, like for example parallel build issues. So IMO the CI failed job re-run should be only available to reviewers and they should decide how to handle that.

**Comment by graysky2** [comment]
Is there a way to code in a more robust download routine to avoid false positives?

**Comment by ynezz** [comment]
> Is there a way to code in a more robust download routine to avoid false positives?

Sure, there is always a way to retry the failed attempt.

**Comment by graysky2** [comment]
I never looked at the CI stuff before, can you point me to the relevant repo?

**Comment by hauke** [comment]
The CI code is in this repo. I think this action failed: https://github.com/openwrt/openwrt/blob/master/.github/workflows/kernel.yml

**Comment by hauke** [comment]
Maybe this action would help: https://github.com/marketplace/actions/retry-step

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in e0753c5d5cef5b03c60601364188afb262ccd02e.

**Pull request closed without merging**
