### PR TITLE
tools/mold: update to 2.4.0

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
- https://github.com/rui314/mold/releases/tag/v2.3.3
- https://github.com/rui314/mold/releases/tag/v2.4.0

### CODE REVIEW

**Comment by hardfalcon** [comment]
It might make sense to update this to [mold 2.30.0](https://github.com/rui314/mold/releases/tag/v2.30.0).

**Comment by schm0** [comment]
perl fails to link/build with latest mold 2.30.0 and lto enabled.
mold: lto-wrapper failed or something like that...

**Comment by robimarko** [comment]
@PolynomialDivision Do you mind if I take over updating to 2.30.0?

**Comment by PolynomialDivision** [comment]
No. Please go for it :)

**Pull request closed without merging**
