### PR TITLE
at91: update for kernel v5.15

### PR DESCRIPTION
**Pull request by claudiubeznea**
Update at91 targets for kernel v5.15. Most of the patches from v5.10
are not needed now as they are integrated in mainline v5.15.

### CODE REVIEW

**Comment by hauke** [comment]
Please split this into two commits. One commit which just copies the patches and the kernel configuration from kernel 5.10 to the new files for kernel 5.15 without adapting them for kernel 5.15 like this one 3064e76c948570a6f0930e893d25a551449df8ff and then an additional patch adapting it for kernel 5.15. This makes reviewing the code much easier because I can directly see what you changed for kernel 5.15.

**Comment by PolynomialDivision** [comment]
@ claudiubeznea Are you going to update the PR? Otherwise I can also do that for you.

**Comment by claudiubeznea** [comment]
@PolynomialDivision : I have it prepared for some time but hadn't had the chance to post it, yet. I'll try to post it today.

**Comment by claudiubeznea** [comment]
@hauke : you suggested me [1] to directly force push to my branch for automatic update of the pull requests. I must confess I am not very familiar with pull requests. By taking this approach I see the formalities test failed but I don't see in my commits where could be the issue. I run locally the code of formalities test but saw no issue.

Thank you!

[1] https://github.com/openwrt/openwrt/pull/10575

**Comment by claudiubeznea** [comment]
I'll close this one as I don't know how to handle the test formalities failures.

**Comment by hauke** [comment]
This PR was replaced by #11035.

**Pull request closed without merging**
