### PR TITLE
ramips: Convert gpio-export to platform driver.

### PR DESCRIPTION
**Pull request by vDorst**
Needed to export i2c expander gpio.

Signed-off-by: René van Dorst <opensource@vdorst.com>

### CODE REVIEW

**Comment by vDorst** [comment]
Needed for PR #1196.

**Comment by mkresin** [comment]
Please patch the patch adding our custom gpio export code directly (target/linux/ramips/patches-4.14/0024-GPIO-add-named-gpio-exports.patch).

Please use the commit message from your 0030-GPIOLIB-Convert-gpio-export-to-a-platform-driver.patch for the patch in this PR. It way better describes what you are changing and why you are changing it.

**Comment by vDorst** [comment]
Ok, I shall change it.

**Comment by mkresin** [comment]
merged, thanks!

**Pull request closed without merging**
