### PR TITLE
tools/llvm-bpf: make sure llvm-bpf.tar.gz is created

### PR DESCRIPTION
**Pull request by zhanhb**
The llvm-bpf-$version.tar.xz might be absent. For example `make clean` executed, `CONFIG_TARGET` changed or even `CONFIG_SDK_LLVM_BPF` changed from `unset` to `y`. It's not needed to recompile llvm-bpt at this time.

### CODE REVIEW

**Comment by zhanhb** [comment]
I'm not sure if there's a better way to make the stamp file work as expected.

**Comment by nbd168** [comment]
I merged your change to tools/llvm-bpf/Makefile and added a better fix for the tools stampfile.
Thanks!

**Comment by zhanhb** [comment]
`tools_config` works for  `$(tools/stamp-compile)` when `CONFIG_TARGET_*=y` changed for the `tools-y` changed.
But it doestn't work when `make clean` is executed. My original patch to the tools/Makefile does not work either.

Maybe a patch like the one shown in the following is needed to clean the stamp file `$(tools/stamp-compile)` when `make clean` is executed.

```patch
--- a/tools/Makefile
+++ b/tools/Makefile
@@ -156,8 +156,14 @@ $(curdir)/ := .config prereq
 
 $(curdir)/install: $(curdir)/compile
 
-tools_config = CONFIG_SDK_LLVM_BPF
-tools_enabled = $(foreach tool,$(sort $(tools-y) $(tools-)),$(if $(filter $(tool),$(tools-y)),y,n))$(foreach c,$(tools_config),$(if $($(c)),y,n))
-$(eval $(call stampfile,$(curdir),tools,compile,,_$(subst $(space),,$(tools_enabled)),$(STAGING_DIR_HOST)))
+ifneq ($(and $(CONFIG_USE_LLVM_BUILD),$(CONFIG_SDK_LLVM_BPF)),)
+STAMP_COMPILE_LOCATION:=
+else
+STAMP_COMPILE_LOCATION:=$(STAGING_DIR_HOST)
+endif
+
+tools_enabled = $(foreach tool,$(sort $(tools-y) $(tools-)),$(if $(filter $(tool),$(tools-y)),y,n))
+
+$(eval $(call stampfile,$(curdir),tools,compile,,_$(subst $(space),,$(tools_enabled)),$(STAMP_COMPILE_LOCATION)))
 $(eval $(call stampfile,$(curdir),tools,check,$(TMP_DIR)/.build,,$(STAGING_DIR_HOST)))
 $(eval $(call subdir,$(curdir)))
```

**Comment by nbd168** [comment]
Thanks, I didn't consider that. Now that I think about this some more, I believe that addressing this in the tools stampfile is the wrong approach, since there are even more corner cases to deal with (e.g. switching target, removing bin/).
I think the best course of action is to move the code that builds the tarball out of tools/llvm-bpf and create a new makefile in target/llvm-bpf instead (similar to SDK/imagebuilder).

**Comment by zhanhb** [comment]
Agree, it looks perfect if do like that.

**Comment by nbd168** [comment]
Done

**Comment by zhanhb** [comment]
Excellent!! It looks clean and tidy now.

**Comment by zhanhb** [comment]
The variable `HOST_STAMP_INSTALLED` is empty now. Maybe its prerequisite shoud be `$(STAGING_DIR_HOST)/llvm-bpf/.llvm-version` to make sure the tarball rebuilt if tools/llvm-bpf rebuilt.

```patch
--- a/target/llvm-bpf/Makefile
+++ b/target/llvm-bpf/Makefile
@@ -14,7 +14,7 @@ LLVM_VERSION := $(shell cat $(STAGING_DIR_HOST)/llvm-bpf/.llvm-version)
 LLVM_BPF_PREFIX := llvm-bpf-$(LLVM_VERSION).$(HOST_OS)-$(HOST_ARCH)
 LLVM_TAR := $(BIN_DIR)/$(LLVM_BPF_PREFIX).tar.xz
 
-$(LLVM_TAR): $(HOST_STAMP_INSTALLED)
+$(LLVM_TAR): $(STAGING_DIR_HOST)/llvm-bpf/.llvm-version
 	tar -C $(STAGING_DIR_HOST) \
 		-I '$(STAGING_DIR_HOST)/bin/xz -7e -T$(if $(filter 1,$(NPROC)),2,0)' \
 		-cf $@.tmp llvm-bpf $(LLVM_BPF_PREFIX)
```

**Comment by nbd168** [comment]
Done

**Pull request closed without merging**
