### PR TITLE
kernel: bump 5.15 to 5.15.82

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B, filogic/xiaomi_redmi-router-ax6000-stock
Run-tested: bcm2711/RPi4B, filogic/xiaomi_redmi-router-ax6000-stock
    
Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by graysky2** [comment]
Someone tell me if my edit to the generic config was wrong... I do not know how to tell which targets aside from bcm2711 needs that new symbol

**Comment by graysky2** [comment]
So I got quite a few build failures [here](https://github.com/graysky2/openwrt/actions/runs/3622664985/jobs/6108478280) but the web UI says "All checks have passed (147 successful checks).

**Comment by DragonBluep** [comment]
```
net/ethernet/eth.c: In function 'nvmem_cell_get_mac_address_ascii':
net/ethernet/eth.c:571:24: warning: returning 'long int' from a function with return type 'void *' makes pointer from integer without a cast [-Wint-conversion]
  571 |                 return PTR_ERR(mac_ascii);
      |                        ^~~~~~~~~~~~~~~~~~
```
https://github.com/openwrt/openwrt/pull/11228 should be helpful to this warning.

**Comment by graysky2** [comment]
Can someone reset the bcm27xx/bcm2708 build?  Looks like a d/l error.

**Comment by Borromini** [comment]
Compile-tested: mvebu/cortexa9 & mvebu/cortexa72
Run-tested: mvebu/cortexa9 (Linksys WRT1200AC & mvebu/cortexa72 (MikroTik RB5009UG+S+IN)

**Comment by HZFrodo** [comment]
Build-tested: mediatek/filogic/xiaomi_redmi-router-ax6000
Run-tested: mediatek/filogic/xiaomi_redmi-router-ax6000
All good

**Comment by Spudz76** [comment]
Build-tested: ramips/mt7621/linksys_ea7300-v1
Run-tested: ramips/mt7621/linksys_ea7300-v1
Seems normal

**Pull request merged**
