### PR TITLE
kernel: x86: enable NVME support for 64 bit target

### PR DESCRIPTION
**Pull request by lucize**
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
Please fix commit message

**Comment by lucize** [comment]
updated, do I need to be more specific ?

**Comment by ynezz** [comment]
> updated, do I need to be more specific ?

Commit message is missing, you need to explain why do you need this changes.

**Comment by lucize** [comment]
@ynezz hopefully is ok now

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
