### PR TITLE
uboot-mvebu: update to version 2023.07.02

### PR DESCRIPTION
**Pull request by damnms**
this is now really my last attempt to get it into openwrt :> see https://github.com/openwrt/openwrt/pull/12551

Since 2021.07 multiple bugs where introduced that made it impossible to create a bootable target for mvebu [1]. This is now fixed since 2023.07-rc1.

[1] #11661

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Comment by robimarko** [comment]
It's probably time to merge this.
`Reviewed-by: Robert Marko <robimarko@gmail.com>`

**Comment by dhewg** [comment]
``Tested-by: Andre Heider <a.heider@gmail.com> # espressobin-v3-v5-1gb-2cs``

**Comment by ynezz** [comment]
Merged in ba7d6dddc7d20222c1703b173ef50befefb3fb52, thanks!

**Comment by ynezz** [comment]
@damnms congrats to your first contribution! :-) It would be nice to backport this into `openwrt-23.05` and `openwrt-22.03` branches (separate pull request for each branch) using `git cherry-pick -x ba7d6dddc7d20222c1703b173ef50befefb3fb52` command, to actually fix the https://github.com/openwrt/openwrt/issues/11661, thanks!

**Pull request closed without merging**
