### PR TITLE
libunwind: update version and mips64 support

### PR DESCRIPTION
**Pull request by Grommish**
Bump the version to 1.5.0 and add mips64 support.  Moving to 1.5.0 required +zlib to be included from what I could tell.  

Sending them in as two commits because the bump and the support change should be separated.

### CODE REVIEW

**Comment by Grommish** [comment]
ping @adschm :)

**Comment by ynezz** [comment]
You should provide commit descriptions.

**Comment by Grommish** [comment]
> You should provide commit descriptions.

There are two commits, each with a one line description on what it is for. One is to bump the level, one is to add mips64 support. What else needs to be there?

**Comment by ynezz** [comment]
> What else needs to be there?

If unsure just skim through following guide https://openwrt.org/submitting-patches

**Comment by Grommish** [comment]
> 
> 
> > What else needs to be there?
> 
> If unsure just skim through the following guide https://openwrt.org/submitting-patches

Again, I ask where it falls shorts..

This really is too much of an issue for a version bump and an arch addition that should have been either made a while ago or never left of in the first place.   I'm not adding a package.  I bumped the version and THEN added the mips64 support, because that's how it was tested and how it should be committed.  

If it's an issue for you to accept this, then it's ok, just disregard it.  This is a community and standards are fantastic, but this seems excessive for what is, again, a version bump and an arch change.. 

Take it, don't.. For what it is, I'll just maintain it locally until someone else bothers to bump it.. since it was already two versions behind, it'll be whenever.  I do this as a favor to anyone else who might be using libunwind.

If you don't want it, close it out.

**Comment by adschm** [comment]
It would have been much easier to write one sentence of comment to each of the commits than writing a whole lot of argument why not to do it BTW.

**Comment by Grommish** [comment]
Because using git and nano gives me a line to do what is grabs as the title
and then, the commit msg starts.

I'm not doubling the word count of the commit msg for the sake of this,
there is no point other than because it Can be done.  Policy for no legit
reason is garbage.  I'm not going out of my way to hand edit commit
messages on GitHub to add a pointless commit message.

You know more then anyone, Adrian, I'm willing to deal with nit picking,
but this is silly and simply not worth the response I got versus the energy
to do it in the first place.

Someone might find it useful when they need to update the package

**Comment by adschm** [comment]
You just don't seem to understand the point of a commit message. If you just repeat the title, you are obviously not making it right. In contrast, there always is a lot of things that you can provide as helpful information:

libunwind: Bump to 1.5.0

- What are the changes (typically copy of git shortlog)
- Why are you adding +zlib, is this triggered by the bump or was it missing beforehand

libunwind: Add mips64 support

- Why is mips64 support added now? Is this possible due to the update? Or just forgotten beforehand?
(- Which devices might be affected?)

That's about the minimum. You may provide additional information if you think it would be helpful.

**Pull request closed without merging**
