### PR TITLE
mediatek: convert eeprom/macaddr to nvmem format for jdcloud re-cp-03

### PR DESCRIPTION
**Pull request by 1715173329**
Switch to new nvmem binding.

Also fixes a issue that the MAC address assigned to lan/wan was reversed.

### CODE REVIEW

**Comment by cyyself** [comment]
I have tested this commit here: https://github.com/1715173329/openwrt-official/commit/fd5ba853a19a0c724b7916c2ff18662b6a3d069c#commitcomment-142934727

**Comment by upsangel** [comment]
Saw the latest 23.05.4 release add support for jdcloud re-cp-03, may I ask if the flash procedure is the same as in the https://github.com/openwrt/openwrt/pull/14144 ? Couldn't find wiki page steps, just to confirm. Thank you very much!

**Comment by 1715173329** [comment]
same

**Comment by upsangel** [comment]
> same

Thank you for your quick reply!

**Pull request merged**
