### PR TITLE
malta: switch to Kernel 5.10

### PR DESCRIPTION
**Pull request by aparcar**
CI build with artifacts: https://github.com/aparcar/openwrt/actions/runs/1290279218

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by neheb** [comment]
This...should have been done long ago.

**Comment by aparcar** [comment]
> This...should have been done long ago.

Please elaborate

**Comment by neheb** [comment]
malta and armvirt are testing platforms.

**Comment by adschm** [comment]
I'd say we just need a commit message expressing that fact and then malta and armvirt can be merged?

**Comment by yousong** [comment]
LGTM

It's also my understanding that armvirt and malta targets are indeed mainly for testing and debugging purposes.  It's possible that these days people may have used armvirt in virtuliazation context.

**Comment by aparcar** [comment]
Merged, thanks!

**Pull request closed without merging**
