### PR TITLE
Rb5009 with poe

### PR DESCRIPTION
**Pull request by prudy**
Add a PoE handling to the RB5009 model if the board is equipped with the necessary hardware.

### CODE REVIEW

**Comment by Borromini** [comment]
It would be cleaner to provide a common DTSI and then build on top off that for both RB5009UPr+S+IN and RB5009UG+S+IN. They're different devices, still.

**Comment by prudy** [comment]
Hi, so you say to go with my first approach (separate menu target)? I agree it's very polite. However,

**Comment by prudy** [comment]
Sorry, let me continue..
Hi, so you say to go with my first approach (separate menu target)? I agree it's very polite. However, that would require a full separate build and assets. Does it make sense?
If so, I can refresh my other branch and go with that one instead, no problem.

**Comment by robimarko** [comment]
Hm, this PR is a bit misleading as it alone doesnt really enable PoE and depends on the mtpoe_ctrl which is not in OpenWrt root nor packages repos.

**Comment by prudy** [comment]
> Hm, this PR is a bit misleading as it alone doesnt really enable PoE and depends on the mtpoe_ctrl which is not in OpenWrt root nor packages repos.

It enables the 'PoE device' to be available in the system. Sure, the user-space tool is needed to do all the settings. And the pr for adding it to packages is also raised.
That is why (small and rather not essential change from the UG model point of view) I see it slightly questionable going with this to a separate menu target. Even the original FW, if you take away the PoE controller, will simply ignore it and the router works as UG model. Thus effectively the only difference in having a separate menu target is to see the different model string on the status page.
But as I said I'm not against a separate target. Thus, if we can agree some reasonable approach then we could have this model in.
The brilliant solution would be to write a dedicated module for the mtpoe, but since the user-space tool is working it makes sense to use it.

**Comment by prudy** [comment]
I've sent an alternative approach in #15989, that creates a separate device for this router.

**Comment by robimarko** [comment]
I dont think there is a need to add a separate model at all, maybe only alt_model so its displayed in menuconfig.

But, again, I do not see a point as long as the required userspace component is not available in OpenWrt at all, especially the fact that we are supposed to carry the spidev patch essentially indefinitively.

**Comment by prudy** [comment]
@Borromini - currently this gives RB5009 and RB5009UPr+S+IN menu targets. Shall we possibly keep the RB5009 (as a base) and give an alt name as RB5009UG+S+IN?

@robimarko You made a very good point with using alt configs, I refreshed the pr with it.
Referring to your doubts, I can only outline my points here.

Pros:
- This pr makes the onboard PoE controller accessible in the system, thus having it in the main tree gives a baseline for any user space tools
- As for the tools themselves:
  - they can further be a part of packages or as a custom package, or none, which do not not impact on this pr
  - if they get a form of the driver, then this pr is not needed - but currently the quick available solution is the user-space

Cons:
- The PoE enable pin is set to output even on the base model without the PoE hardware – this does not seem to be any problem
- As you said, the spidev name stays in the tree. But it does not break anything either. Basing the DT on a particular device name (not on the spi in general) is the right thing. Although, personally I feel that adding a bunch of names to the spidev source is kind of opposite to the no-modification idea of the DT, but as of this moment it is the recommended approach.

**Comment by olemmela** [comment]
Instead of using user-space POE control software, kernel space POE pse-pd driver should be written for mikrotik. There is nowadays pse-pd framework which can be controlled by ethtool for example. https://github.com/torvalds/linux/blob/master/drivers/net/pse-pd/Kconfig

**Comment by prudy** [comment]
@olemmela agree 100%, however it's not done. If you willing to handle this, I can share findings for additional statuses and proper spi response handling (the mtpoe-ctrl tool uses repeated request for this purpose, but I assume the origin of the tool was to have a quick working sufficient solution).

**Comment by robimarko** [comment]
I gave this some thought, and I have changed my opinion and agree with @Borromini that DTSI should be used for everything common and PoE model should be separate.

However, I am still not convinced that we should have the PoE model supported separately until all of the required tooling for PoE to actually work is available in OpenWrt.

**Comment by olemmela** [comment]
> @olemmela agree 100%, however it's not done. If you willing to handle this, I can share findings for additional statuses and proper spi response handling (the mtpoe-ctrl tool uses repeated request for this purpose, but I assume the origin of the tool was to have a quick working sufficient solution). Anyway this pr does not prevent from adding the dedicated ko in the future.

I don't currently have the extra hardware to test the poe controller. I also don't have enough free time to rewrite the driver to use the pse-pd framework.

My previous kernel driver is available in github if anyone else have time to rewrite it https://github.com/olemmela/openwrt/commit/d2d99bf5444e2d10dd3f0d04753471a75bf8c4a0

**Comment by prudy** [comment]
@robimarko if considering the PCB I bet both models are alike, with rb5009ug not populated with pie elements. Is it common then from the DT point of view? Formally not there means not in DT. But some common sense decision ia needed here taking into consideration separate build.

@olemmela I perfectly understand the time factor, that is why I went for mtpoe and not the dedicated ko.

**Comment by prudy** [comment]
Just to inform I keep an eye on this and soon could handle it.

**Comment by robimarko** [comment]
Just have them as separate models, no DEVICE_ALT0_MODEL please

**Comment by prudy** [comment]
This way we go to the initial patch refered at the initial post. Not a problem, but please see the other one so we can stick to one version. Of course, I'll add a common dtsi there.
Sent from Proton Mail Android
-------- Original Message --------On 11/26/24 18:02, Robert Marko  wrote:
Just have them as separate models, no DEVICE_ALT0_MODEL please

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/openwrt/openwrt/pull/15980#issuecomment-2501448496",
"url": "https://github.com/openwrt/openwrt/pull/15980#issuecomment-2501448496",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by prudy** [comment]
Closing as moved to [#15989](https://github.com/openwrt/openwrt/pull/15989)

**Pull request closed without merging**
