### PR TITLE
tools/meson: update to 1.1.0

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
- 0.62.0 https://mesonbuild.com/Release-notes-for-0-62-0.html
- 0.63.0 https://mesonbuild.com/Release-notes-for-0-63-0.html
- (other notes are not available)

### CODE REVIEW

**Comment by dhewg** [comment]
This wasn't bumped yet because of:
https://mesonbuild.com/Release-notes-for-0-62-0.html#minimum-required-python-version-updated-to-37

So ensure that meson keeps working everywhere we need to bump the required python version first, see also 7379f8bd3e7ee0722faa6ec8b2969081fbdc1e07

I'm not sure if all buildbot slaves fulfill that though

**Comment by neheb** [comment]
NACK.

Upstream still updates 0.61 because of the python issue (I believe red hat is handling the backports).

**Comment by aparcar** [comment]
Is this stell relevant?

**Comment by dhewg** [comment]
Assuming #12186 gets merged, can we go straight to v1.1.0?

**Comment by eli-schwartz** [comment]
@PolynomialDivision the minimum required python is now 3.7 so this patch can now proceed (perhaps even updated to meson 1.1.0).

Can it be taken out of draft mode?

**Comment by eli-schwartz** [comment]
The oneline summary of the commit message is now inaccurate. :)

**Comment by mpratt14** [comment]
#12700 should fix the CI error

the actual cause is a mystery though

**Pull request closed without merging**
