### PR TITLE
x86: enable console keyboard

### LINKED ISSUE #16157: x86_64: console is unusable with USB keyboard
### Describe the bug

With recent Releases my installation does not boot into console and refuses any input after the bootloader.
The same behavior occurs when booting into failsafe mode.

I did already try the latest stable release.

Any help is greatly appreciated.

photo_2024-08-13_00-56-26_2

### OpenWrt version

r27123-8cf9a932fa

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

x86/64

### Device

HUNSN Micro Firewall Appliance

### Image kind

Official downloaded image

### Steps to reproduce

wget https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-ext4-combined-efi.img.gz

gunzip openwrt-x86-64-generic-ext4-combined-efi.img.gz
 
lsblk
 
dd if=openwrt-x86-64-generic-ext4-combined-efi.img bs=1M of=/dev/#some_nvme

shutdown -h now

##

Then just starting the machine.

### Actual behaviour

Does not show console and does not accept input like instructed in the picture.

### Expected behaviour

Openwrt console screen and input from keyboard.

### Additional info

Don't know if it has to do with it but the log tells me to press Enter to activate console but this doesn't help either.
Maybe related to #15615?

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by markmentovai**
The kernel support necessary to use a console keyboard was not built on x86, affecting real and virtual machines alike. The console keyboard would function properly in GRUB, but would not work at all once Linux booted. It appeared that the console was intended to work because console video appeared on the display, including prompts to enter failsafe or select the debug log level from the keyboard, and the prompt to ”Press Enter to activate this console”, but there was no way to provide input to it. All keystrokes were ignored.

This enables several kernel configuration options to enable HID and USB HID support (`CONFIG_HID`, `CONFIG_HID_SUPPORT`, `CONFIG_HID_GENERIC`, and `CONFIG_USB_HID`), making the keyboard functional. [For alignment with armsr, `CONFIG_USB_HIDDEV`](https://github.com/openwrt/openwrt/blob/ea7383e7215c36e47a769f34c57aa458300b8bc2/target/linux/armsr/config-6.6#L319) is also added, although not strictly necessary for keyboard support. Note that this change also causes `CONFIG_HID_HYPERV_MOUSE` to be enabled: it was already set in target/linux/x86/{[64](https://github.com/openwrt/openwrt/blob/f34620f14676eddea9eeb5c811d82adef9ba665a/target/linux/x86/64/config-6.6#L258),[generic](https://github.com/openwrt/openwrt/blob/f34620f14676eddea9eeb5c811d82adef9ba665a/target/linux/x86/generic/config-6.6#L185)}/config-6.6, but was ineffective due to `CONFIG_HID` being absent.

The omission of keyboard support on x86 may not have been widely noticed because USB HID is not used on production OpenWrt x86 machines such as pc-engines,apu2 which only have a serial console, or with the default x86 configuration used by [scripts/qemustart](https://github.com/openwrt/openwrt/blob/497012ab4eb1f37cbbbff9a766d2fecdb43dd0db/scripts/qemustart), which uses [`-nographic`](https://github.com/openwrt/openwrt/blob/497012ab4eb1f37cbbbff9a766d2fecdb43dd0db/scripts/qemustart#L316) and does not configure a virtual physical console but instead uses a serial console.

This configuration change results in, for x86_64, +40kB in kernel.bin and just over +40kB in gzip-compressed “combined” images. This should not be a problem for the non-storage-constrained x86 target.

Fixes: https://github.com/openwrt/openwrt/issues/16157

### CODE REVIEW

**Review by ynezz — APPROVED** [review]
LGTM, thanks!

**Comment by tmn505** [comment]
Please do it per sub-target, leaving out the 'geode' one.

**Comment by markmentovai** [comment]
https://github.com/openwrt/openwrt/pull/16208#issuecomment-2299568144:
> Please do it per sub-target, leaving out the 'geode' one.

OK, updated.

**Comment by tmn505** [comment]
Thank You. You left out also 'legacy' sub-tagret, accidental omission?

**Comment by markmentovai** [comment]
https://github.com/openwrt/openwrt/pull/16208#issuecomment-2299644420:
> Thank You. You left out also 'legacy' sub-tagret, accidental omission?

Yeah, I meant to investigate whether I wanted just HID or HID and USB_HID, and wound up doing neither.

I dug a bit more and decided to do both. Updated, again. Thanks.

**Review by tmn505 — APPROVED** [review]

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
