### PR TITLE
x86: use device vendor/model variable

### PR DESCRIPTION
**Pull request by mwarning**
Remove use of DEVICE_TITLE in favor of the
DEVICE_VENDOR and DEVICE_MODEL as used by
all other targets.

Signed-off-by: Moritz Warning <moritzwarning@web.de>

### CODE REVIEW

**Comment by mwarning** [comment]
This change does not change the image name or the displayed target/subtarget/model in `make menuconfig`.
It is debatable if Generic is a vendor and x86 can pose a model, but this is a step to retire the DEVICE_TITLE variable.
We can also go for `Unbranded` as a vendor and `Generic` as model, and maybe `x86` as variant, but this might need more discussion.

@adschm you might want to have a look here.

**Comment by aparcar** [comment]
Looks good to me.

I wouldn't change the vendor to "Unbranded"

**Comment by aparcar** [comment]
@adschm I'll merge this if there's no objections from your side.

**Comment by adschm** [comment]
@mwarning I think when you/we introduced the DEVICE_* variables in the first place, someone of the committers was against using "Generic" as vendor. I'm against Unbranded, too, as this would just make the assembled name quite unreadable.

Personally, I must say that IMO the concept of DEVICE_VENDOR/DEVICE_MODEL simply doesn't fit generic images. I would leave them alone and stick to DEVICE_TITLE there, unless you are hit very badly by this variable in some place.

**Comment by mwarning** [comment]
@adschm I agree that it does not really fit generic images. Generic is no vendor. The reasons of replacing DEVICE_TITLE are IMO:
* we already use Generic as vendor (for targets bcm63xx and octeon)
* we would be able to remove a bit of complexity of the build system
* it is set in about 5 files, thus DEVICE_TITLE can be seen as a legacy
* for these images DEVICE_TITLE/VENDOR/MODEL have no influence on the images name
  * it only affects the menu entry and generate profiles.json

**Comment by aparcar** [comment]
I can't find the discussion on why a "Generic" vendor is something bad. Seems like *Traverse Technologies* is actually a company, so it totally makes sense to add this.

Removing `TITLE` support long term and going with the more specific variables would be my preferred way to go.

**Comment by adschm** [comment]
Well, as surfaced in other discussions, the problem is essentially that in x86 we do things completely different compared to all other targets. And I stick to my earlier comment that obviously the DEVICE_VENDOR/DEVICE_MODEL does not work for generic images.

That does not mean that we cannot force the generic names into this model, but it will never be natural by any means, and always depend on some forceful convention/definition. Thus, in my personal opinion, the gain of removing DEVICE_TITLE is not really big enough (is there relevant gain at all?) to do this forceful mending of names into the vendor/model concept. But if you feel different, I won't stop you either.

I actually don't care about x86 at all due to the problem described above, at least as long as it doesn't bite me somewhere else ...

**Comment by aparcar** [comment]
It eventually allows better interface due to a higher consistency in data. I don't see it as an issue and rather an advantage to get rid of corner cases.

**Comment by adschm** [comment]
Forcing something into a model that does not fit in nothing I would call "consistent". Consistent means to me that stuff is treated the same way in different places. What you try here is making it look consistent although it isn't - which is actually _inconsistent_.

**Comment by aparcar** [comment]
It's consistent that we have the same variables available for all profiles rather than maintaining two corner cases.

That x86 is still special in more ways, but that's something I'm somewhat working on via different commits.

**Comment by adschm** [comment]
Well, would you keep the property "horse power" on a bicycle just to have the same consistent set of variables for all means of transportation?

**Comment by bobafetthotmail** [comment]
> That does not mean that we cannot force the generic names into this model, but it will never be natural by any means, and always depend on some forceful convention/definition.

To me the current system isn't natural nor particularly better either, both are more or less arbitrary.
What does "DEVICE_TITLE" even mean? It's just the legacy way, most other targets were migrated to DEVICE_VENDOR/DEVICE_MODEL somehwere in 2019 https://github.com/openwrt/openwrt/search?q=split+up+DEVICE_TITLE&type=commits
And even back then there was a lot of DEVICE_VENDOR=Generic added around the place

Unless there is something actually better, I think just removing corner cases is good enough reason to do this.

**Comment by aparcar** [comment]
Merged, allows to get rid of the DEVICE_TITLE legacy variable.

**Pull request closed without merging**
