### PR TITLE
igmpproxy: add logopts option that sets it to "-d"

### PR DESCRIPTION
**Pull request by hanipouspilot**
This redirects log to STDERR

Signed-off-by: Dmitry Tunin <hanipouspilot@gmail.com>

### CODE REVIEW

**Comment by ldir-EDB0** [comment]
Please can you explain in the commit message why this changed is needed.
What does/doesn't work without it?  What is the advantage?  Is the change incompatible with the '-v -v' option?

**Comment by hanipouspilot** [comment]
@ldir-EDB0  See https://github.com/pali/igmpproxy/blob/master/doc/igmpproxy.8.in

.IP -h
Display help.
.IP -v
Verbose logging. Set logging level to INFO instead of WARNING used by default. 
.IP -vv
More verbose logging. Set logging level to DEBUG.
.IP -n
Do not run as a daemon.
.IP -d
Output log messages to STDERR instead of to syslog.

In Openwrt it actually disables igmpproxy log. In some cases it spams too much to syslog.
I will update the message.

**Comment by ldir-EDB0** [comment]
OK, I get it now.  You've effectively implemented a 'silent' logging level but at verbose '3' which isn't that intuitive.  With a small sacrifice to backward compatibility may I ask you to:

1) Change the levels such that 0 = -d, 2 = -v, 3 = -v -v
2) Set the default to 1
3) update igmpproxy.conf to say something like "#      option verbose [0-3] (none, minimal[default], more, maximum)"
4) bump the package release

Something like that would be merged.

**Comment by hanipouspilot** [comment]
@ldir-EDB0  Done.

**Pull request closed without merging**
