### PR TITLE
ubus: update to version 2022-06-15

### PR DESCRIPTION
**Pull request by ynezz**
Update which contains just a following fix:

 * ubusd: add lookup command queuing support ([9913aa61de739e](https://git.openwrt.org/9913aa61de739e))

   Defers and continues a client's lookup command to avoid unnecessary
   buffering under load.

### CODE REVIEW

**Comment by ynezz** [comment]
@Ansuel @robimarko any [idea what might cause this ipq807xx target build](https://github.com/openwrt/openwrt/actions/runs/4023524985/jobs/6914502511#step:29:91) test failure in `qca-ssdk-2022-09-12-628b22bc` ?
```
aarch64-openwrt-linux-musl-gcc.bin: warning: ./bin/../lib/gcc/aarch64-openwrt-linux-musl/120200/include/: linker input file unused because linking not done
aarch64-openwrt-linux-musl-gcc.bin: error: ./bin/../lib/gcc/aarch64-openwrt-linux-musl/120200/include/: linker input file not found: No such file or directory
```

**Comment by robimarko** [comment]
Not really as its building locally with the ubus update just fine

**Comment by ynezz** [comment]
> Not really as its building locally with the ubus update just fine

I don't think, that this ubus update is related, it's probably some build concurrency/race issue in `qca-ssdk`.

**Comment by robimarko** [comment]
Hmm, there shouldn't be any as the parallel build is disabled for it, since it's completely broken if you try to build it parallel.

**Comment by ynezz** [comment]
> I've [just triggered rebuild, 2nd attempt](https://github.com/openwrt/openwrt/actions/runs/4023524985).

FYI it has failed as well.

**Comment by robimarko** [comment]
Ok, now its extremely weird as it was building fine in CI before.

**Pull request merged**
