### PR TITLE
toolchain: gdb: update to 13.1

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
https://www.sourceware.org/gdb/download/ANNOUNCEMENT

### CODE REVIEW

**Comment by john-tho** [comment]
Trivial, but I noticed that the release notes link is not versioned.
Might it be better to point to the mailing list archive mail for this release?
https://sourceware.org/pipermail/gdb-announce/2023/000134.html

**Comment by BKPepe** [comment]
That's good point about the release notes link and I see it was updated to the commit description. Good.

However, I am not sure, why this is marked as draft?

**Comment by PolynomialDivision** [comment]
> However, I am not sure, why this is marked as draft?

It does not compile on my buildsystem. Not sure why.

**Comment by hauke** [comment]
What compile error do you get?

**Comment by lovehackintosh** [comment]
GDB 13.2 released.

**Pull request closed without merging**
