### PR TITLE
ipq806x: fix min<>target opp volt mixup on ipq8065

### PR DESCRIPTION
**Pull request by digitalcircuit**
## In brief
* Rearrange voltage triplets for `opp_table0` to match specs
   * See [Linux kernel documentation on Operating Performance Points](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/devicetree/bindings/opp/opp.txt?h=v5.4.142#n91)
   * `opp-microvolt` and `opp-microvolt-<name>` triplets are `<target min max>`, **NOT** `<min target max>`
   * Avoids CPU *always* at "minimum" voltage, ignoring actual intended target
   * Fixes regression from [`1e25423` ipq806x: refresh dtsi patches](https://github.com/openwrt/openwrt/commit/1e25423be8acb38e979cd5a38abb1ca4cac2837e) from [pull request #4192](https://github.com/openwrt/openwrt/pull/4192 )
   * *Does **not** fix SFTP USB HDD crash, but this should probably be addressed anyways*

### Review request
@Ansuel Whenever you have the time, would you look over this?  I tried to verify my changes, but it's possible I misunderstood or missed something.

### Steps
1.  Compile and flash to an IPQ8065 device that does not override `opp_table0` from `qcom-ipq8065.dtsi`
     * Tested with [ZyXEL NBG6817](https://openwrt.org/toh/zyxel/nbg6817 )
2.  Check the CPU voltages for a known frequency
```
/usr/bin/tail -n +1 /sys/kernel/debug/opp/cpu0/opp\:1725000000/supply-0/u_volt_*
```
3.  Compare with the expected results in `qcom-ipq8065.dtsi`
     * With a PVS bin 2, `&opp_table0` → `opp-1725000000` → `opp-microvolt-speed0-pvs2-v0` shows expected values

### Before
*On an NBG6817 with a Qualcomm CPU of PVS bin 2*

```
/usr/bin/tail -n +1 /sys/kernel/debug/opp/cpu0/opp\:1725000000/supply-0/u_volt_*
==> /sys/kernel/debug/opp/cpu0/opp:1725000000/supply-0/u_volt_max <==
1260000

==> /sys/kernel/debug/opp/cpu0/opp:1725000000/supply-0/u_volt_min <==
1200000

==> /sys/kernel/debug/opp/cpu0/opp:1725000000/supply-0/u_volt_target <==
1140000
```
*Notice how `u_volt_target` is below `u_volt_min`, which doesn't make sense.  Separately, checking the regulator summary shows that the voltage actually gets set to below the minimum.*

### After
```
/usr/bin/tail -n +1 /sys/kernel/debug/opp/cpu0/opp\:1725000000/supply-0/u_volt_*
==> /sys/kernel/debug/opp/cpu0/opp:1725000000/supply-0/u_volt_max <==
1260000

==> /sys/kernel/debug/opp/cpu0/opp:1725000000/supply-0/u_volt_min <==
1140000

==> /sys/kernel/debug/opp/cpu0/opp:1725000000/supply-0/u_volt_target <==
1200000
```
*Notice how `u_volt_target` is above `u_volt_min` and still below `u_volt_max`, which makes more sense.  Also notice how the target voltage matches before [`1e25423` ipq806x: refresh dtsi patches](https://github.com/openwrt/openwrt/commit/1e25423be8acb38e979cd5a38abb1ca4cac2837e).*

### Additional notes
To check voltages and frequencies at run time, use…

```
/bin/cat /sys/kernel/debug/regulator/regulator_summary && /bin/cat /sys/kernel/debug/clk/clk_summary | grep "hfpll"
```

Also see the [Linux kernel documentation on Operating Performance Points](
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/devicetree/bindings/opp/opp.txt?h=v5.4.142#n91)

---

*As to my ongoing diagnosing of the [Deja Dup SFTP upload to USB 3.0 HDD crash](https://lists.openwrt.org/pipermail/openwrt-devel/2021-August/036026.html ), this does **not** fix that issue, but [I am using this change as part of my backport tests](https://github.com/openwrt/openwrt/compare/openwrt-21.02...digitalcircuit:openwrt-21.02-cpufreq-dtsivolt-cache-fix-opp-order ).*

### CODE REVIEW

**Comment by digitalcircuit** [comment]
I've set this as a draft because I'm still trying to get the build working.  It worked fine on `21.02`, and nothing in my change appeared to cause a build failure, but it's failed.  I've been running a verbose, non-parallel build for the past hour+, and I'll mark this as ready for review once I get a successful build.

**Comment by Ansuel** [comment]
Can we consider fixing this also for ipq8064?

**Comment by adschm** [comment]
@Ansuel If you verify this and provide a Reviewed-by, I would merge it (preferably with ipq8064 included).

**Comment by digitalcircuit** [comment]
I had entirely overlooked `ipq8064`, thank you for the heads up!

Though I don't have any `ipq8064` devices to test on, I can make the change there as well.  I should get this done tonight (EST timezone), and if sooner would be preferred,  feel free to modify this PR directly.

**Comment by Ansuel** [comment]
We really don't need to test this for plain ipq8064. The current
implementation is plain wrong and I never notice that. This could be the
cause of the reported instability. Can you swap the values by tweaking the
patch ?

Il Ven 20 Ago 2021, 23:26 Shane Synan ***@***.***> ha scritto:

**Comment by digitalcircuit** [comment]
I've pushed updated commits that address existing patches (`ipq8065` as before, but also `ipq8062`, and `ipq8064`), then I've partially backported the kernel 5.10 version of `083-ipq8064-dtsi-additions.patch` to kernel 5.4, namely the `opp-microvolt-X` ranges and the `opp-level` (I haven't touched the other sections).

With any luck, this will improve stability for those on `master`!

This appears to build and run on my NBG6817, as before.  I am still testing this more thoroughly ([the bursty Deja Dup SFTP upload to USB HDD connected to router test](https://lists.openwrt.org/pipermail/openwrt-devel/2021-August/036026.html )), but that **should not block merging this PR** as this is more correct and may help solve others' issues.

I'll either post a comment here once I have more findings, or follow up on the mailing list.

**Comment by Ansuel** [comment]
`Reviewed-by: Ansuel Smith <ansuelsmth@gmail.com>`

**Comment by digitalcircuit** [comment]
As mentioned earlier, this is commentary on [my ongoing debugging of a related-but-separate issue](https://lists.openwrt.org/pipermail/openwrt-devel/2021-August/036026.html ), and **should not block merging this PR.**

---

While this is more correct, it doesn't solve my particular instability with the NBG6817.  I've actually [tried raising the CPU voltage by `20000` µV](https://github.com/openwrt/openwrt/compare/openwrt-21.02...digitalcircuit:openwrt-21.02-cpufreq-dtsivolt-cache-fix-opp-order ) on top of this change and that hasn't resolved it, either.

However, after [enabling dynamic kernel debugging](https://www.kernel.org/doc/html/v5.4/admin-guide/dynamic-debug-howto.html ) with…
```
echo "file drivers/regulator/* =p" > /sys/kernel/debug/dynamic_debug/control
echo "file drivers/cpufreq/* =p" > /sys/kernel/debug/dynamic_debug/control
```
…I noticed that in one case (`master` + `digitalcircuit:fix-ipq8065-dts-opp-order`), the crash happened with one CPU core at 1.75 GHz when the other CPU core shifted up from 800 MHz to 1.75 GHz.

```
[…]
[17666.280778] cpufreq: __target_index: cpu: 0, oldfreq: 800000, new freq: 1725000
[17666.288601] cpufreq: notification 0 of frequency transition to 1725000 kHz
[17666.297746] s1a: ramp_delay not set
[17666.302576] s2a: ramp_delay not set
[serial console log ends here, hard reboot]
```

<details><summary>Longer excerpt of above serial console log crash on commit 11e938030d498222388ef716329c48d22fc41770</summary>

```
[…]
[17665.817901] s1a: ramp_delay not set
[17665.822988] s2a: ramp_delay not set
[17665.826270] cpufreq: notification 1 of frequency transition to 1725000 kHz
[17665.829685] cpufreq: FREQ: 1725000 - CPUs: 0
[17665.836755] cpufreq: target for CPU 1: 600000 kHz, relation 2, requested 504690 kHz
[17665.841060] cpufreq: __target_index: cpu: 1, oldfreq: 1725000, new freq: 600000
[17665.848501] cpufreq: notification 0 of frequency transition to 600000 kHz
[17665.857475] s1a: ramp_delay not set
[17665.862817] s2b: ramp_delay not set
[17665.865977] cpufreq: notification 1 of frequency transition to 600000 kHz
[17665.869448] cpufreq: FREQ: 600000 - CPUs: 1
[17665.877366] cpufreq: target for CPU 1: 1725000 kHz, relation 1, requested 1725000 kHz
[17665.880389] cpufreq: __target_index: cpu: 1, oldfreq: 600000, new freq: 1725000
[17665.888472] cpufreq: notification 0 of frequency transition to 1725000 kHz
[17665.897223] s1a: ramp_delay not set
[17665.902627] s2b: ramp_delay not set
[17665.905865] cpufreq: notification 1 of frequency transition to 1725000 kHz
[17665.909286] cpufreq: FREQ: 1725000 - CPUs: 1
[17666.001752] cpufreq: target for CPU 0: 719250 kHz, relation 2, requested 719250 kHz
[17666.001774] cpufreq: __target_index: cpu: 0, oldfreq: 1725000, new freq: 800000
[17666.008274] cpufreq: notification 0 of frequency transition to 800000 kHz
[17666.018286] s1a: ramp_delay not set
[17666.022601] s2a: ramp_delay not set
[17666.025793] cpufreq: notification 1 of frequency transition to 800000 kHz
[17666.029213] cpufreq: FREQ: 800000 - CPUs: 0
[17666.037286] cpufreq: target for CPU 0: 1725000 kHz, relation 1, requested 1725000 kHz
[17666.040391] cpufreq: __target_index: cpu: 0, oldfreq: 800000, new freq: 1725000
[17666.048629] cpufreq: notification 0 of frequency transition to 1725000 kHz
[17666.057009] s1a: ramp_delay not set
[17666.062749] s2a: ramp_delay not set
[17666.066107] cpufreq: notification 1 of frequency transition to 1725000 kHz
[17666.069193] cpufreq: FREQ: 1725000 - CPUs: 0
[17666.081636] cpufreq: target for CPU 1: 638790 kHz, relation 2, requested 638790 kHz
[17666.081657] cpufreq: __target_index: cpu: 1, oldfreq: 1725000, new freq: 600000
[17666.088142] cpufreq: notification 0 of frequency transition to 600000 kHz
[17666.097125] s1a: ramp_delay not set
[17666.102456] s2b: ramp_delay not set
[17666.105625] cpufreq: notification 1 of frequency transition to 600000 kHz
[17666.109113] cpufreq: FREQ: 600000 - CPUs: 1
[17666.116202] cpufreq: target for CPU 1: 1725000 kHz, relation 1, requested 1725000 kHz
[17666.120040] cpufreq: __target_index: cpu: 1, oldfreq: 600000, new freq: 1725000
[17666.128108] cpufreq: notification 0 of frequency transition to 1725000 kHz
[17666.136865] s1a: ramp_delay not set
[17666.142273] s2b: ramp_delay not set
[17666.145515] cpufreq: notification 1 of frequency transition to 1725000 kHz
[17666.148936] cpufreq: FREQ: 1725000 - CPUs: 1
[17666.241730] cpufreq: target for CPU 0: 759480 kHz, relation 2, requested 759480 kHz
[17666.241754] cpufreq: __target_index: cpu: 0, oldfreq: 1725000, new freq: 800000
[17666.248504] cpufreq: notification 0 of frequency transition to 800000 kHz
[17666.257306] s1a: ramp_delay not set
[17666.262584] s2a: ramp_delay not set
[17666.265720] cpufreq: notification 1 of frequency transition to 800000 kHz
[17666.269193] cpufreq: FREQ: 800000 - CPUs: 0
[17666.277414] cpufreq: target for CPU 0: 1725000 kHz, relation 1, requested 1725000 kHz
[17666.280778] cpufreq: __target_index: cpu: 0, oldfreq: 800000, new freq: 1725000
[17666.288601] cpufreq: notification 0 of frequency transition to 1725000 kHz
[17666.297746] s1a: ramp_delay not set
[17666.302576] s2a: ramp_delay not set

U-Boot 2012.07 [Standard IPQ806X.LN,unknown] (Oct 03 2018 - 18:59:17)
```

</details>

…I noticed that in another case ([21.02 backport branch before further raising DTS voltages](https://github.com/openwrt/openwrt/compare/openwrt-21.02...digitalcircuit:openwrt-21.02-cpufreq-dtsivolt-cache-fix-opp-order )), the crash happened with one CPU core at 1.75 GHz when the other CPU core shifted down from 1.75 GHz to 800 MHz.

```
[…]
[ 1400.584045] cpufreq: __target_index: cpu: 1, oldfreq: 1725000, new freq: 800000
[ 1400.590562] cpufreq: notification 0 of frequency transition to 800000 kHz
[serial console log ends here, hard reboot]
```

Disabling the highest CPU clock frequency (limiting CPU to 1.4 GHz instead of 1.75 GHz, which also disables the L2 cache 1.4 GHz frequency) tentatively seems to stop the crashes (not thoroughly tested).
```
echo "1400000" > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
echo "1400000" > /sys/devices/system/cpu/cpufreq/policy1/scaling_max_freq
```

This is only a workaround, not a solution, but I'm at least getting a better grasp of what's happening - perhaps it's frequency transitions with one core remaining at max frequency, the other core dipping down from max, or some other sort of switching.

Separate from this PR, I'll keep diagnosing this.  My next idea will be to make a script to automatically force the CPU clocks up and down randomly within the discrete range of allowed values (600 MHz to 1.75 GHz).

Future updates I'll move back to the mailing list.

---

Again, **this doesn't take away from the fixes in this PR.**

**Comment by Ansuel** [comment]
Very interesting discovery
We currently have a script to disable low freq as in the original qsdk
there was a comment alerting about instability with low freq and the second
core couldn't run with lowest cache (and other CPU freq at something more
that idle freq)...

If you are correct we can think about a transition freq when scaling to
high freq



Il Sab 21 Ago 2021, 23:24 Shane Synan ***@***.***> ha scritto:

**Comment by adschm** [comment]
I'll merge the 5.10 patch tonight.
I'm not so sure that we should change 5.4 behavior, though.

**Comment by Ansuel** [comment]
Regulator are not enabled by OPP anyway so voltage scaling doesn't really
work on 5.4

Il Sab 21 Ago 2021, 23:52 Adrian Schmutzler ***@***.***> ha
scritto:

**Comment by Ansuel** [comment]
@digitalcircuit another test would be to check if forcing both core to run at the same freq improve stability...  (that can be easily done with the dts)

**Comment by digitalcircuit** [comment]
@Ansuel Thank you for the suggestions!  Those all seem promising to explore.

Meanwhile, I think I've successfully created an automated test case to trigger the CPU reset issue that only needs the router itself, skipping the Déjà Dup backup over SFTP, USB HDD, etc:
https://github.com/digitalcircuit/openwrt-ipq806x-qa-cpu-reset

I haven't yet had time to do more with this, but in the near future, I plan to email the mailing list to update others and I'll explore your suggestions for resolving the issue.

And belatedly `[@]adschm`, thanks for [merging the main patch](https://github.com/openwrt/openwrt/commit/9baca410644b3f0fe94e2d5b6558c9c4bf61e712 ), including cleaning it up!

**Comment by Ansuel** [comment]
@digitalcircuit feel free to ask for help about tweaking the cpufreq driver

**Comment by adschm** [comment]
5.4 has been dropped and the 5.10 patch is already merged. So, this can be closed.

**Comment by Ansuel** [comment]
@adschm considering we dropped 5.4 should we drop also the smem workaround for the caldata?

**Comment by adschm** [comment]
Already did that here or are you referring to something else: https://github.com/openwrt/openwrt/commit/6a27e8036e63f2477333c324ae41f038e9ac6297

**Comment by Ansuel** [comment]
Was referring to this 6a27e80 so already done

**Pull request closed without merging**
