### PR TITLE
build: improve security via procd-ujail and procd-seccomp

### PR DESCRIPTION
**Pull request by aparcar**
This was proposed a long time ago on the mailing list but never made it in. I'd like to merge this within the next week.

### CODE REVIEW

**Comment by SkewedZeppelin** [comment]
I've had this enabled in my moderately popular Divested-WRT [builds](https://forum.openwrt.org/t/divested-wrt-no-nonsense-linksys-wrt-builds/80522) for nearly a year now with no issues seen by myself or reported by others.

**Review by dangowrt — APPROVED** [review]

**Comment by egorenar** [comment]
I traced back issues with transmission daemon to procd-ujail. Removing procd-ujail from my config helps to fix the issues.

Error message:
```
jail: exec-ing /usr/bin/transmission-daemon
[2021-11-20 10:19:45.257] Transmission 3.00 (bb6b5a062e) started (session.c:769)
[2021-11-20 10:19:45.257] Cache Maximum cache size set to 2.00 MiB (128 blocks) (cache.c:260)
[2021-11-20 10:19:45.257] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:956)
[2021-11-20 10:19:45.257] RPC Server Adding address to whitelist: ::1 (rpc-server.c:956)
[2021-11-20 10:19:45.258] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (rpc-server.c:1243)
[2021-11-20 10:19:45.258] RPC Server Started listening on 0.0.0.0:9091 (rpc-server.c:834)
[2021-11-20 10:19:45.258] Bound socket 15 to port 51413 on 0.0.0.0 (net.c:462)
[2021-11-20 10:19:45.258] Bound socket 16 to port 51413 on :: (net.c:462)
[2021-11-20 10:19:45.258] DHT Initializing DHT (tr-dht.c:338)
[2021-11-20 10:19:45.258] Couldn't read "/mnt/sda1/openwrt/transmission/config/dht.dat": No such file or directory (utils.c:263)
[2021-11-20 10:19:45.258] DHT Generating new id (tr-dht.c:389)
[2021-11-20 10:19:45.258] DHT DHT initialized (tr-dht.c:413)
[2021-11-20 10:19:45.258] Using settings from "/mnt/sda1/openwrt/transmission/config" (daemon.c:646)
[2021-11-20 10:19:45.258] Couldn't save temporary file "/mnt/sda1/openwrt/transmission/config/settings.json.tmp.XXXXXX": Permission denied (variant.c:1235)
```

But the weird things is all permissions are set correctly:
```
bash-5.1# ls -l /mnt/sda1/openwrt/transmission/
drwxr-xr-x    1 transmis transmis        94 Nov 20 10:40 config
drwxr-xr-x    1 transmis transmis      1334 Nov 14 09:14 download
drwxr-xr-x    1 transmis transmis         0 Oct 22 20:00 incomplete
drwxrwxrwx    1 transmis transmis         0 Nov 20 10:19 watch
```

**Comment by dangowrt** [comment]
@egorenar Probably another missing syscall in the seccomp filter...
Which hardware are you running on (CPU architecture is relevant for seccomp)?
Please try `/etc/init.d/transmission trace` let it run for a bit and then `/etc/init.d/transmission stop`, then look for file `/tmp/transmission-daemon*.json` and compare it with `/etc/seccomp/transmission-daemon.json`. If anything is missing, add it there and try running normally (ie. without trace) again.

**Comment by egorenar** [comment]
Thanks for the hint.
My arch is `ARMv7 Processor rev 4 (v7l)`.
I gave `trace` a try, but so far no new syscalls discovered, they are all in `/etc/seccomp/transmission-daemon.json` already.
But it works indeed with `/etc/init.d/transmission trace`.

**Comment by dangowrt** [comment]
Odd. I have tested transmission on ARMv7 recently and it worked fine, but maybe depends on configuration. Can you share you `/etc/config/transmission` file?

**Comment by egorenar** [comment]
```
bash-5.1# cat /etc/config/transmission

config transmission
        option config_overwrite '1'
        option user 'transmission'
        option group 'transmission'
        option mem_percentage '50'
        option nice '10'
        option alt_speed_enabled 'false'
        option alt_speed_time_enabled 'false'
        option bind_address_ipv4 '0.0.0.0'
        option bind_address_ipv6 '::'
        option blocklist_enabled 'false'
        option cache_size_mb '2'
        option dht_enabled 'true'
        option download_queue_enabled 'true'
        option download_queue_size '4'
        option encryption '1'
        option idle_seeding_limit_enabled 'false'
        option lazy_bitfield_enabled 'true'
        option lpd_enabled 'false'
        option message_level '1'
        option peer_limit_global '240'
        option peer_limit_per_torrent '60'
        option peer_port '51413'
        option peer_port_random_on_start 'false'
        option peer_socket_tos 'default'
        option pex_enabled 'true'
        option port_forwarding_enabled 'true'
        option preallocation '1'
        option queue_stalled_enabled 'true'
        option queue_stalled_minutes '30'
        option ratio_limit_enabled 'false'
        option rename_partial_files 'true'
        option rpc_authentication_required 'false'
        option rpc_bind_address '0.0.0.0'
        option rpc_enabled 'true'
        option rpc_host_whitelist_enabled 'false'
        option rpc_port '9091'
        option rpc_url '/transmission/'
        option rpc_whitelist_enabled 'false'
        option scrape_paused_torrents_enabled 'true'
        option script_torrent_done_enabled 'false'
        option seed_queue_enabled 'false'
        option speed_limit_down_enabled 'false'
        option speed_limit_up_enabled 'false'
        option start_added_torrents 'true'
        option trash_original_torrent_files 'false'
        option umask '18'
        option upload_slots_per_torrent '14'
        option utp_enabled 'true'
        option scrape_paused_torrents 'true'
        option config_dir '/mnt/sda1/openwrt/transmission/config'
        option download_dir '/mnt/sda1/openwrt/transmission/download'
        option incomplete_dir_enabled 'false'
        option watch_dir_enabled 'false'
        option enabled '1'
```

**Comment by egorenar** [comment]
It's weird, i started ujail + transmission with the JSON seccmp file created with trace and it didn't work.

```
/sbin/ujail -n transmission -S /mnt/sda1/openwrt/transmission/transmission-daemon.16304.json \
                 -U transmission -G transmission -l -w /mnt/sda1/openwrt/transmission/config/blocklists \
                 -w /mnt/sda1/openwrt/transmission/config/resume -r /mnt/sda1/openwrt/transmission/config/settings.json \
                 -w /mnt/sda1/openwrt/transmission/config/stats.json -w /mnt/sda1/openwrt/transmission/config/torrents \
                 -w /mnt/sda1/openwrt/transmission/download -- /usr/bin/transmission-daemon -g \
                -g /mnt/sda1/openwrt/transmission/config --log-debug
```

Still getting the same error:
```
[2021-11-20 15:37:03.935] Using settings from "/mnt/sda1/openwrt/transmission/config" (daemon.c:646)
[2021-11-20 15:37:03.935] Couldn't save temporary file "/mnt/sda1/openwrt/transmission/config/settings.json.tmp.XXXXXX": Permission denied (variant.c:1235)
```

**Comment by dangowrt** [comment]
The error relating to not being able to save temporary file is unrelated, transmission works fine even with that error, it just means that configuration changes done via transmission-client will not survive restart.

**Comment by egorenar** [comment]
This is the error i'm getting when i try to open transmission Web UI

```
404: Not Found

Couldn't find Transmission's web interface files!

Users: to tell Transmission where to look, set the TRANSMISSION_WEB_HOME environment variable to the folder where the web interface's index.html is located.

Package Builders: to set a custom default at compile time, #define PACKAGE_DATA_DIR in libtransmission/platform.c or tweak tr_getClutchDir() by hand.
```

Maybe the web files are inaccessible.

**Comment by dangowrt** [comment]
Are you running a build after https://github.com/openwrt/openwrt/commit/9224ddf72d0fb1b1fb6a47055efb57dd36b0155d ?
Because web UI depends on having environment variable `TRANSMISSION_WEB_HOME` passed to ujail.

**Comment by egorenar** [comment]
Yes, i'm running latest master, updated today.

**Comment by dangowrt** [comment]
try
```
uci set transmission.@transmission[0].web_home='/usr/share/transmission/web'
uci commit transmission
```

**Comment by egorenar** [comment]
Thanks you. That works finally :+1:

**Pull request merged**
