### PR TITLE
ath79: get rid of BOARD_NAME for RouterBOARD 922UAGS-5HPacD

### PR DESCRIPTION
**Pull request by adschm**
So far, specifying "BOARD_NAME := routerboard" is required by the
upgrade code of Mikrotik NAND devices, as "sysupgrade-routerboard"
is hardcoded in platform_do_upgrade_mikrotik_nand().

This patch replaces the latter with a grep for the name like it
is already done in nand_upgrade_tar() in /lib/upgrade/nand.sh.

By that, BOARD_NAME is obsolete now for this device.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
@rogerpueyo

**Comment by rogerpueyo** [comment]
To me that's good, I didn't like the "BOARD_NAME := routerboard" thing neither; its whole point was to allow upgrading from ar71xx to ath79 via sysupgrade, since ar71xx images do use it.

I'm now going to test it. Do you think we could have it in next 19.07? Since it's probably the last ar71xx release, it'd be a nice feature.

**Comment by adrianschmutzler** [comment]
I'm obviously going backport the ar71xx patch, as it would not make any sense to have it just in master.
The bigger question is whether it should go into 18.06.

@xback Opinion?

**Comment by xback** [comment]
> I'm obviously going backport the ar71xx patch, as it would not make any sense to have it just in master.
> The bigger question is whether it should go into 18.06.
> 
> @xback Opinion?

If the change is straightforward and easy to port, I would port it.
A lot of users are still on 18.06 and being able to upgrade will aid in the transition from ar71xx to ath79

**Comment by rogerpueyo** [comment]
The RB922 accidentally got the soft_config partition in read-only mode (sorry, my bad), which right now is the safe option until we solve https://github.com/openwrt/openwrt/pull/2791.

**Comment by adrianschmutzler** [comment]
Will be merged.

**Comment by adrianschmutzler** [comment]
Bah, there are non-backported changes in ar71xx master, so backporting this change needs some review/testing.

@rogerpueyo Can you test my backport here: https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/staging-19.07

**Comment by adrianschmutzler** [comment]
@rogerpueyo @xback 
Can please one of you test my backport of the routerboard upgrade, so I can merge this into 19.07 and 18.06:
https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/staging-19.07

**Comment by adrianschmutzler** [comment]
19.07 has been finally merged now.

Since 19.07 does not have any ath79 Mikrotik devices, we decided to not cherry-pick the upgrade patch to 18.06, as it's not worth the extra testing (it applies cleanly there, though).

**Pull request closed without merging**
