### PR TITLE
bcm53xx/ipq40xx: fix vendor spelling

### PR DESCRIPTION
**Pull request by mwarning**
Adjust spelling of vendor names to what is used in other places.

### CODE REVIEW

**Comment by adschm** [comment]
Thanks, I've improve the commit title/message and will merge this later today.

Please be more careful next time to include a proper commit message and make the commit title sufficiently specific.

**Comment by mwarning** [comment]
Feel free to change the commit title. Maybe "ipq40xx: fix spelling or DEVICE_VENDOR" might be better, but lower/upper case does not really apply to lower/upper case...

**Comment by adschm** [comment]
It's already merged. The point is that you do not fix the spelling of DEVICE_VENDOR for all devices, but just the a small subset.

**Comment by mwarning** [comment]
ok, understood. Thanks for merging.

**Pull request closed without merging**
