### PR TITLE
Revert "opkg: bump to git HEAD"

### PR DESCRIPTION
**Pull request by jwmullally**
This reverts commit 1445d333aa0f12bef1c9ea469bf0d84fe2667c5f.

opkg install fails to include dependencies. This has been observed
by some people on their devices and using imagebuilder.

### CODE REVIEW

**Comment by jwmullally** [comment]
@aparcar or @dangowrt 

User report here: https://github.com/openwrt/openwrt/commit/1445d333aa0f12bef1c9ea469bf0d84fe2667c5f#commitcomment-43784779

This looks to have affected imagebuilder too. The images produced only include the directly requested packages, and don't include any of their dependencies.

E.g. https://downloads.openwrt.org/snapshots/targets/ath79/generic/openwrt-imagebuilder-ath79-generic.Linux-x86_64.tar.xz

2020-10-29 - 13:00 GMT - works OK
```bash
$ make image PROFILE="tplink_tl-wpa8630p-v2.0-eu" PACKAGES="procd iw luci -ppp -ppp-mod-pppoe"

Packages: procd iw luci ath10k-firmware-qca9888-ct base-files busybox ca-bundle dnsmasq dropbear firewall fstools ip6tables iptables kernel kmod-ath10k-ct kmod-ath9k kmod-gpio-button-hotplug kmod-ipt-offload libc libgcc libustream-wolfssl logd mtd netifd odhcp6c odhcpd-ipv6only opkg procd swconfig uboot-envtools uci uclient-fetch urandom-seed urngd wpad-basic-wolfssl

Configuring liblucihttp0.
Configuring libubox20191228.
Configuring libubus20191227.
Configuring cgi-io.
Configuring liblua5.1.5.
Configuring lua.
Configuring luci-lib-nixio.
Configuring libnl-tiny.
Configuring luci-lib-ip.
Configuring libjson-c5.
Configuring luci-lib-jsonc.
Configuring liblucihttp-lua.
Configuring luci-lib-base.
Configuring libuclient20160123.
Configuring uclient-fetch.
Configuring libpthread.
Configuring opkg.
Configuring luci-app-opkg.
Configuring libwolfssl24.
Configuring libustream-wolfssl20200215.
Configuring libblobmsg-json.
Configuring ubusd.
Configuring ubus.
Configuring iw.
Configuring libuci20130104.
Configuring rpcd.
Configuring busybox.
Configuring libubus-lua.
Configuring kmod-nf-reject6.
Configuring libiwinfo20200105.
Configuring libiwinfo-lua.
Configuring swconfig.
Configuring rpcd-mod-file.
Configuring rpcd-mod-luci.
Configuring luci-base.
Configuring kmod-ledtrig-default-on.
Configuring kmod-ledtrig-heartbeat.
Configuring kmod-ledtrig-netdev.
Configuring kmod-ledtrig-timer.
Configuring luci-mod-system.
Configuring kmod-nf-conntrack.
Configuring kmod-nf-flow.
Configuring getrandom.
Configuring luci-theme-bootstrap.
Configuring hostapd-common.
Configuring wpad-basic-wolfssl.
Configuring kmod-nf-reject.
Configuring kmod-nf-ipt.
Configuring kmod-ipt-core.
Configuring kmod-ipt-conntrack.
Configuring jshn.
Configuring netifd.
Configuring jsonfilter.
Configuring usign.
Configuring openwrt-keyring.
Configuring ubox.
Configuring fstools.
Configuring fwtool.
Configuring base-files.
Configuring kmod-nf-nat.
Configuring uboot-envtools.
Configuring dnsmasq.
Configuring libjson-script.
Configuring procd.
Configuring luci-mod-status.
Configuring libxtables12.
Configuring libip4tc2.
Configuring libip6tc2.
Configuring kmod-nf-conntrack6.
Configuring kmod-ipt-nat.
Configuring firewall.
Configuring luci-app-firewall.
Configuring kmod-nf-ipt6.
Configuring kmod-ip6tables.
Configuring odhcp6c.
Configuring wireless-regdb.
Configuring kmod-cfg80211.
Configuring kmod-mac80211.
Configuring kmod-ath.
Configuring kmod-ath9k-common.
Configuring kmod-ath9k.
Configuring ath10k-firmware-qca9888-ct.
Configuring uci.
Configuring dropbear.
Configuring kmod-hwmon-core.
Configuring mtd.
Configuring odhcpd-ipv6only.
Configuring urandom-seed.
Configuring luci-proto-ppp.
Configuring rpcd-mod-iwinfo.
Configuring luci-mod-network.
Configuring luci-mod-admin-full.
Configuring kmod-gpio-button-hotplug.
Configuring logd.
Configuring luci-proto-ipv6.
Configuring iptables.
Configuring uhttpd.
Configuring ip6tables.
Configuring kmod-ath10k-ct.
Configuring ca-bundle.
Configuring uhttpd-mod-ubus.
Configuring rpcd-mod-rrdns.
Configuring luci.
Configuring kmod-ipt-offload.
Configuring urngd.

Filesystem size 3457.66 Kbytes (3.38 Mbytes)
```

2020-10-30 - 13:00 GMT - produces bad image, no dependencies included
```
make image PROFILE="tplink_tl-wpa8630p-v2.0-eu" PACKAGES="procd iw luci -ppp -ppp-mod-pppoe"

Configuring libgcc1.
Configuring uclient-fetch.
Configuring opkg.
Configuring libustream-wolfssl20200215.
Configuring iw.
Configuring busybox.
Configuring swconfig.
Configuring wpad-basic-wolfssl.
Configuring netifd.
Configuring fstools.
Configuring base-files.
Configuring uboot-envtools.
Configuring dnsmasq.
Configuring procd.
Configuring firewall.
Configuring odhcp6c.
Configuring kmod-ath9k.
Configuring ath10k-firmware-qca9888-ct.
Configuring uci.
Configuring dropbear.
Configuring mtd.
Configuring odhcpd-ipv6only.
Configuring urandom-seed.
Configuring kmod-gpio-button-hotplug.
Configuring logd.
Configuring iptables.
Configuring ip6tables.
Configuring kmod-ath10k-ct.
Configuring ca-bundle.
Configuring luci.
Configuring kmod-ipt-offload.
Configuring urngd.

Filesystem size 2064.25 Kbytes (2.02 Mbytes)
```

**Comment by 1Jeff1** [comment]
Customized builds on x86 , bcm27xx targets are also affected for the missing dependencies,  generating useless images.

**Comment by aparcar** [comment]
Fixed via https://git.openwrt.org/?p=project/opkg-lede.git;a=commit;h=b4fa2a8f6c2a0149d602db5d1e2dba6145113aaa

**Comment by aparcar** [comment]
Also sorry for the inconveniences and thank you for testing!

**Comment by jwmullally** [comment]
Thanks! Closing this PR in favor of fix.

**Pull request closed without merging**
