### PR TITLE
firewall: make uci scripting friendlier

### PR DESCRIPTION
**Pull request by vgaetera**
Make UCI scripting for firewall configuration friendlier.
It's much easier to analyze configuration as well as set up firewall via CLI using named sections.
The default configuration should provide simple and easy to distinguish names for UCI sections.
In addition, unify the indentation for the example sections.

### CODE REVIEW

**Comment by aparcar** [comment]
@adschm if you add the `needs changes` label please also elaborate what missing :)

**Comment by adschm** [comment]
The Signed-off-by is missing. But since hauke and jow- already fought about who is assignee, I thought they would take care anyway ;-)

**Comment by vgaetera** [comment]
> The Signed-off-by is missing.

I'm not sure why it is missing.
My real name and the primary email are configured in the GitHub profile.
Perhaps the wiki guide for submitting patches requires clarification/update how to set up that correctly using the web interface.

Anyway, thank you.

**Comment by adschm** [comment]
> > The Signed-off-by is missing.
> 
> I'm not sure why it is missing.
> My real name and the primary email are configured in the GitHub profile.
> Perhaps the wiki guide for submitting patches requires clarification/update how to set up that correctly using the web interface.
> 
> Anyway, thank you.

Well, for me the guide says very boldly that you should use `git commit --signoff`. You probably just used `git commit`. You can heal that by using `git commit --am --si`.

**Comment by bobafetthotmail** [comment]
> > The Signed-off-by is missing.
> 
> I'm not sure why it is missing.
> My real name and the primary email are configured in the GitHub profile.
> Perhaps the wiki guide for submitting patches requires clarification/update how to set up that correctly using the web interface.
> 

it was missing in the commit message, I have added a line in the wiki guide to make it more clear that from Github or a git GUI you need to add that line manually at the end of the commit description.

**Comment by jow-** [comment]
I don‘t like the change and tend to not merge it.

Reasoning:
- such a default config will make it non-obvious that sections may be anonymous 
- the config will be prone to duplicate section errors due to copy paste
- LuCI will generate anonymous sections anyway

**Comment by vgaetera** [comment]
Okay, never mind.

**Pull request closed without merging**
