### PR TITLE
kernel: bump 5.4 to 5.4.140

### PR DESCRIPTION
**Pull request by graysky2**
Removed upstreamed bcm27xx/patches-5.4:
```
    950-0977-USB-gadget-f_hid-avoid-crashes-and-log-spam.patch
    950-0980-SQUASH-USB-gadget-f_hid-remove-more-spam.patch
```
All other patches automatically rebased.

Build system: x86_64
Build-tested: ipq806x/R7800
Run-tested: ipq806x/R7800

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by t-8ch** [comment]
Tested with EA6350v3 (IPQ40XX)

**Comment by graysky2** [comment]
@pelwell - Following up on our email exchange, can you please confirm removing the two patches here?

**Review by pelwell — APPROVED** [review]
Yes - that's the correct course of action.

**Comment by blocktrron** [comment]
Merged to my staging tree - thanks!

**Pull request closed without merging**
