### PR TITLE
ipq806x: fix error with cache handling

### PR DESCRIPTION
**Pull request by Ansuel**
These 2 patch improve cache handling for this target.
In the 5.10 merge, ipq8065 never reimplemented the 1.4ghz for the cache and currently is working with 1.2ghz.
Fix a wrong implementation in the logic used in the dedicated cpufreq driver.

### CODE REVIEW

**Comment by hauke** [comment]
This does not compile with kernel 5.4 any more:
```
  DTC     arch/arm/boot/dts/qcom-ipq8065-r7800.dtb
Error: arch/arm/boot/dts/qcom-ipq8065.dtsi:80.1-14 Label or path opp_table_l2 not found
FATAL ERROR: Syntax error parsing input tree
  DTC     arch/arm/boot/dts/qcom-ipq8068-ecw5410.dtb
make[6]: *** [scripts/Makefile.lib:285: arch/arm/boot/dts/qcom-ipq8065-nbg6817.dtb] Error 1
make[6]: *** Waiting for unfinished jobs....
Error: arch/arm/boot/dts/qcom-ipq8065.dtsi:80.1-14 Label or path opp_table_l2 not found
FATAL ERROR: Syntax error parsing input tree
make[6]: *** [scripts/Makefile.lib:285: arch/arm/boot/dts/qcom-ipq8065-r7800.dtb] Error 1
make[5]: *** [Makefile:1274: dtbs] Error 2
make[5]: *** Waiting for unfinished jobs....
```

**Comment by Ansuel** [comment]
@hauke can you give this another spin?

**Comment by nicklowe** [comment]
@hauke This would be a good one to progress for R7800 users.

**Comment by pkgadd** [comment]
`Tested-by: Stefan Lippers-Hollmann <s.l-h@gmx.de> #ipq8065/ nbg6817`

I've been (successfully) using this patch with kernel v5.10 and the [DSA PR](https://github.com/openwrt/openwrt/pull/4036) since March 27th.

**Comment by Ansuel** [comment]
Can we merging this?

**Comment by digitalcircuit** [comment]
To get this to compile with kernel v5.4 atop `master`, I had to run the following…

```
cd target/linux/ipq806x/patches-5.4/
rediff 083-ipq8064-dtsi-additions.patch > 083-ipq8064-dtsi-additions.patch
```

…to fix up the patch line numbers [as shown in my test branch](https://github.com/openwrt/openwrt/compare/master...digitalcircuit:test-pr-4192-cache ), but after that, it compiled successfully and booted.

I'm currently giving this a test with the ZyXEL NBG6817 + kernel v5.4 atop `master` in preparation for a future backport to the `21.02` branch.  I've started the first seven hour SFTP test and will edit this comment as I get results.  However, you don't need to wait for me!

*Context on why I'm here: I ran into an unexpected reboot within 1 hour of the SFTP test using [my rough faux-backport to the `21.02` branch](https://github.com/openwrt/openwrt/compare/openwrt-21.02...digitalcircuit:openwrt-21.02-cpufreq-dtsivolt-cache ) as first shared [on the mailing list](https://lists.openwrt.org/pipermail/openwrt-devel/2021-June/035667.html), so I figured I should check `master` + this PR first to see if and where I've messed up.*

**Comment by Ansuel** [comment]
@digitalcircuit can i """abuse""" of your testing? Do you want to test 5.10 ? :D

**Comment by digitalcircuit** [comment]
> @digitalcircuit can i """abuse""" of your testing? Do you want to test 5.10 ? :D

@Ansuel Sure!

I've gotten one seven-hour success on 5.4 so far, and before switching to 5.10 I'd like to achieve 3 more successful tests first.  (Previously, I once had two successful runs in a row during 30/35 failures on 21.02rcX.)

Then I'll do 4 tests for 5.10 of `master` + this PR.  If that all goes well and no further testing is needed, I'll revisit the `21.02` faux-backport and troubleshoot why my efforts there broke.

**Comment by hauke** [comment]
Thank you for the patch. I fixed the patches for 5.4 and applied them to master.

**Pull request closed without merging**
