### PR TITLE
Add support for Easybox-904xDSL (lantiq/xrx200)

### PR DESCRIPTION
**Pull request by Plonkbong**
This commits adds support for the Arcadyan/Astoria VGV952CJW33-E-IR Router aka Vodafon Easybox-904xDSL
It base on Quallenauge git from here https://github.com/Quallenauge/Easybox-904-XDSL
Information: 
https://forum.openwrt.org/t/support-for-easybox-904-lte/14478
https://openwrt.org/toh/astoria/arcadyan_astoria_easybox_904xdsl_r01
https://www.randomprojects.org/wiki/Vodafone_EasyBox_904_xDSL

Hardware:
---------
CPU:	       Lantiq PSB 80920 EL V1.2		      VRX200 2x500MHz with a mips32 architekture called mips_34Kc
RAM:	       EtronTech EM68C16CWQD-25H	      128MB DDRII SDRAM 400MHz
Flash: 	       Samsung K9F4G08U0x		      512MiB NAND-flash
Ethernet:      Realtek RTL8367RB		      4x 10/100/1000 Mbit/s vlan support
Wlan:	       Realtek RT3883F + RT5392L	      5GHz/2.4GHz 802.11abgn
USB: 	       unknown				      2 x USB-2.0
Serial:	       (from CPU)			      yes with connectors
xDSL-Modem:    Lantiq PSB 80190 V V1.1 XWAY VRX208    up to VDSL2 profile 30a and Vectoring support
POTS:	       Lantiq PEF 42068 V V1.2 XWAY SLIC120   2 x FXS Analog Telefon ports
ISDN: 	       Lantiq PEF 82902 F V1.1 T TSMINTI 4B3T 1 x S0-Bus
LCD-Screen:    ILITEK ILI9341			      TFT LCD 320x240 RGB 262K colors
Touchpad:      unknown			              yes
Simcardreader: unknown				      one exist but no function

It exist some restrictions:
- The VRX200 have some speedlimitations under Openwrt
- Driver for WLAN and touchpad
found here: https://github.com/Quallenauge/lede-feeds-easybox904
and here optimised for SDK build: https://github.com/Plonkbong/eb904x-feedfix
- WLAN non standart Driver because WiSoc, only AP mode are possible
- xDSL-Modem it is not know whish ADSL-annexes are supported / Vectoring are possible, 
but only with an self extracted modemfirmware from foeign VR9 device.
- ISDN not supported yet and probably in future
- Simcardreader not supported

Building:
---------
for an working WLAN it is required to enable devmem in kernel and bussybox:
CONFIG_BUSYBOX_CUSTOM=y
CONFIG_BUSYBOX_CONFIG_DEVMEM=y
CONFIG_KERNEL_DEVMEM=y

Installation:
-------------
short:
1.) use the UBoot-tftp method to install the initramfs image at your router and start it again
2.) This is optional but usefull: 
override the password locked uboot with an free uboot from here:
linked in https://github.com/Quallenauge/Easybox-904-XDSL commit fa8e9a88891841f6b4a35296315db68526cde2f1 from 27.06.2018
SHA256: 4d035b3777f1a93090e7f0bd8faf2fa83f4b1bc0570de076f5f5cdbc8680ea9a
3.) install the sysupgrade-image via sysupgrade
long:
see https://github.com/Quallenauge/Easybox-904-XDSL

Serial:
-------
parameter: 115200, 8N1

------------------------------------
upper edge from Router             |
------------------------           |
                                   |
<quartz> 4 3 2 1 <capacitor>       |
                                   |
                                   |
connectors                         |
------------------------------------

Pin 1 	Vcc 3.3V (DO NOT CONNECT, since it could irreparably damage the device.)
Pin 2 	TX
Pin 3 	RX
Pin 4 	GND

### CODE REVIEW

**Comment by mrkiko** [comment]
Congratulagint with you - great work!!
Can you detail a little bit about what you refer to when you talk about "speed limitations under OpenWRt"?
thank you very very much for your work, and all,

Enrico

**Comment by pkgadd** [comment]
> The VRX200 have some speedlimitations under Openwrt
> > Can you detail a little bit about what you refer to when you talk about "speed limitations under OpenWRt"?

Disclaimer: I'm only answering to this specific aspect, not the PR as a whole.

This remark isn't specific to the Easybox 904 xDSL, but common to all VRX2xx based lantiq chipsets, which are made up of two 500 MHz mips 24Kc cores.

- using a single of these cores (nosmp, which is implicit for all lantiq devices sporting (enabled-) FXS (analogue phone-) ports, the lantiq SOC achieves roughly ~55 MBit/s throughput (LAN to WAN throughput, using the integrated VDSL2 modem, via a PPPoE session/ NAT/ routing/ default firewalling); this figure doesn't change significantly by enabling flow-offloading.
- if both cores are available (smp, FXS ports disabled), you can expect up to around 85 MBit/s LAN-to-WAN throughput under the same circumstances, flow-offloading can -in the SMP case- bump these figure beyond 100 MBit/s (probably up to around 115 MBit/s).

The way FXS support is implemented on the VRX2xx SOC, is by uploading a voice firmware (vmmc) to the second CPU core (and by assigning 2 MB RAM dedicated to this 'voice-' core, running the vmmc firmware), this means only a single 500 MHz mips 24Kc remains available to the system. Given the that bootloader cmdline settings are ignored and overriden by the device's DTS files, the decision between enabling the FXS ports (and thereby sacrificing the second core) or configuring the router for SMP mode needs to be taken at build time, in general in favour of supporting the given hardware (so vmmc && nosmp for devices equipped with FXS ports, like the Easybox 904 xDSL - or no-fxs && smp for devices without FXS ports, e.g. BT Home Hub 5 Type A/ AVM Fritz!Box 3070).

But again, that's not specific to the Easybox 904 xDSL, but the same for all lantiq VRX2xx devices - simplified:
- devices with FXS ports are only good up to 50 MBit/s VDSL WAN throughput
- devices without (enabled-) FXS ports can achieve up to 100 MBit/s VDSL2 WAN throughput, if you enable flow-offloading (it's tight, but works in general).

Proprietary firmware tend to squeeze a little more out of the hardware, using further acceleration methods (e.g. AVM seems to have found a way to do the dsp operations needed for FXS support without having to globally sacrifice the second core).

**Comment by mrkiko** [comment]
Cool! Thank you for the kind kind reply!! :)

**Comment by Plonkbong** [comment]
as @pkgadd sad, it is a general xrx200 problem under openwrt.
It means that the most Routers with stockfirmware simple reach 100Mbit/s at WAN(VDSL)<->LAN speed. (Speedports, Fritzbox, TP-Link)
Routers with openwrt reaches only 50-90Mbit/s.

The other VPE for the vmmc is only one problem. The others are:
- missed driver for PPE (Protokoll Processor Engine) are kind of hardwaren-NAT of VRX200 SOC
- bad IRQ balancing between VPEs (see: https://forum.openwrt.org/t/xrx200-irq-balancing-between-vpes/29732)
- xrx200 ethernet code are not much speed optimized
- openwrt using the mips_24kc arch, not the mips_34kc arch
see this thread:
https://forum.openwrt.org/t/how-can-we-make-the-lantiq-xrx200-devices-faster/9724

**Comment by mrkiko** [comment]
thank you very very much @Plonkbong and all, for this detailed and nice response!
Really.

**Comment by zuzia-dev** [comment]
Plonkbong, thank you for everything you've done.

**Comment by Plonkbong** [comment]
@zuzia-dev
Sorry but i only make a PR from the work of other people
like Quallenauge Arnysch and Kovs see 
https://github.com/Quallenauge/Easybox-904-XDSL
And not forget like all the other people they make it generally possible.
For example Stefan Koch where writing the asterisk-channel-lantiq, 
without it the FXS ports are not usable.

**Comment by Plonkbong** [comment]
I have migrate to Kernel 4.19 (it was simple)
I do some small tests:
The good news it works generall.
The bad news is that the WLAN driver for the rt3883 wifichip not working now on kernel 4.19
But the wifi driver is not a part of these pullrequest.

**Comment by zuzia-dev** [comment]
> Sorry but i only make a PR from the work of other people
> like Quallenauge Arnysch and Kovs see
> https://github.com/Quallenauge/Easybox-904-XDSL
> And not forget like all the other people they make it generally possible.
> For example Stefan Koch where writing the asterisk-channel-lantiq,
> without it the FXS ports are not usable.


Yes, I know. I'm so grateful to everyone who has supported this project. The Asterisk 16 is working perfectly fine.

**Comment by adrianschmutzler** [comment]
Hi, please have look at https://openwrt.org/submitting-patches

Some important issues in your patches (Signed-off-by with real name, length of commit title and lines in message, ...).

First of all, you should reorganize your commits into a smaller number of logically aggregated commits.

Despite, is there a need for https://github.com/openwrt/openwrt/pull/2061 to be separate or can it be included here. You need to get away from your development process for that and think about what logical units are in terms of adding patches to OpenWrt master.

**Comment by Plonkbong** [comment]
The reason for the large quantity of commits are here that there come from different people and over development process it was the best practise to have one commit for changing one file.
The other reason was is the important information who and why/what should be inside the commits and is growing over a long time
see: https://forum.openwrt.org/t/support-for-easybox-904-lte/14478
It is difficult for me and i have no freetime at the moment (when i start this PR and some months later i have a lot freetime), but i will look what i can do.

If i should add the uboot part: I thing this know the openwrt team better like me, 
i separate it because the main-part works without uboot and i want a lean PR because i thing it increase the change that the PR will accepted.

**Comment by adrianschmutzler** [comment]
@Plonkbong I won't be able to review your patches, I just wanted to give some pointers how you might enhance the experience for others who might want to do so.
So, you do not have to hurry, just wanted to point out the direction you might have to go ...

**Comment by adrianschmutzler** [comment]
@Plonkbong You still have not addressed any of the formal issues of your patches. In the current state, your patches cannot be accepted (or even be reviewed reasonably).
I will close this PR for now (as well as #2061). We can reopen this any time you find the time to reshape your patches and address the formal issues.

**Comment by Plonkbong** [comment]
So I have changed the linked: https://github.com/Plonkbong/openwrt/tree/pr001-eb904x
I have squashfs all together.
But i can not see any changes here what are the reason ?

**Comment by adrianschmutzler** [comment]
Looks like GitHub won't allow reopening if the PR has been closed and the branch has been force-pushed after. So, unfortunately, it looks like there must be a new PR opened for this.

**Comment by Plonkbong** [comment]
OK i have done
@adrianschmutzler
What did you self thing about this PR is it usefull to spent time in it for wait 3 months again to the next: mi mi mi the PR have not the correct form ?

**Comment by Plonkbong** [comment]
https://github.com/openwrt/openwrt/pull/2531

**Comment by adrianschmutzler** [comment]
> What did you self thing about this PR is it usefull to spent time in it for wait 3 months again to the next: mi mi mi the PR have not the correct form ?

Well, fulfulling the proper formal guidelines is a service to the reviewers and to the people having to look at the merged code later, making their lives easier a lot. It is a little like applying proper spelling and reading a text a second time before you send it...

**Pull request closed without merging**
