### PR TITLE
ar71xx: fix wpj531 sig1 LED gpio

### PR DESCRIPTION
**Pull request by yogo1212**
In 6c937df7, i commited a faulty GPIO num for a fix.

Signed-off-by: Leon M. George <leon@georgemail.eu>

### CODE REVIEW

**Comment by ynezz** [comment]
Would be nice if you could little bit improve the commit message, make it more verbose, like adding background about why do you think, that GPIO 12 is the proper one. It's going to be backported to 19.07 so more details would be nice.

**Comment by yogo1212** [comment]
@ynezz will do :-)
in the end, i'm submitting the patch because without it, the LED can only be driven by exporting GPIO 12 in /sys/class/gpio.
the corresponding file in /sys/class/leds doesn't have any effect on the LED.

**Comment by yogo1212** [comment]
forgot to say i'm done with the description - ready from my end

**Comment by ynezz** [comment]
Thanks, pushed to master, 19.07 and 18.06.

**Pull request closed without merging**
