### PR TITLE
ath79: add Kernel 5.10 as testing kernel

### PR DESCRIPTION
**Pull request by blocktrron**
This adds Kernel 5.10 support for the generic, nand and tiny subtargets.

The following patch is not contained, as it needs to be reworked:
platform/920-mikrotik-rb4xx.patch

Tested-on:
 - Siemens WS-AP3610
 - Enterasys WS-AP3710
 - Aerohive HiveAP 121
 - TP-Link TL-WA901 v2
 - TP-Link TL-WR741 v1

Signed-off-by: David Bauer <mail@david-bauer.net>

### CODE REVIEW

**Comment by dengqf6** [comment]
How about using the upstream ag71xx driver? It has issues on 5.4 but may be fixed already on 5.10.
The upstream one also has phylink support.
@olerem

**Comment by olerem** [comment]
ag71xx is standalone driver compared to non upstream variant. It is not including PHY or switch support, no integrated PHY resets or other kinds quirks related to other components. 
Most probably you wont be able to use it as drop in replacement with chips without proper PHY driver, devicetree or  dsa switch driver. On other hand, all this work should be done some day by some one. Currently i'm work on proper bridge acceleration support for the ar9331 dsa driver. Without it, you can't use ar9331 as simple switch, so you won't be able to get same functionality as the OpenWRT version. But I can promise, my current WIP code already can do spanning tree, loop detection, system integration of packet counters (no need to decode vendor specific MIBs from ethtools -S, just use ip -s l).
In any case, in long term, I would recommend to use available resources to make upstream kernel work for you, instead of maintaining old drivers downstream.

**Comment by blocktrron** [comment]
> On other hand, all this work should be done some day by some one.

This is more or less the problem why we reverted to the downstream driver the last time, as it was no drop in replacement.

If somebody fixes the outstanding problems (for me, at lest the PLL configuring and the SGMII lockup would be of necessity), we can switch to the upstream driver.

But in the end it has to be done. As nobody took the hat for that, i don't see why we should stall adding the 5.10 patches.

**Comment by blocktrron** [comment]
@PolynomialDivision Can you check the block protection clearing is working on your Ubiquiti boards? I'll have access to the earliest next week, so i was unable to do proper testing on these patches.

**Comment by olerem** [comment]
@blocktrron , which chip is affected? i'Il would need to know what exactly should be configured.

**Comment by PolynomialDivision** [comment]
Tested on Ubiquiti AC Gen2:

```
[   54.302208] jffs2_scan_eraseblock(): End of filesystem marker found at 0x0
[   54.324504] jffs2_build_filesystem(): unlocking the mtd device... 
[   54.324576] done.
[   54.332875] jffs2_build_filesystem(): erasing all blocks after the end marker... 
...
[   98.380661] jffs2: notice: (1766) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
[   98.579032] overlayfs: upper fs does not support tmpfile.
```

Maybe a dump question, but how can I directly build 5.10 kernel without changing the kernel version in the makefile? So using `KERNEL_TESTING_PATCHVER`?

**Comment by PolynomialDivision** [comment]
> @blocktrron , which chip is affected? i'Il would need to know what exactly should be configured.

macronix flash chip

**Comment by olerem** [comment]
No, i refer to "If somebody fixes the outstanding problems (for me, at lest the PLL configuring and the SGMII lockup would be of necessity), we can switch to the upstream driver." :)

**Comment by PolynomialDivision** [comment]
> No, i refer to "If somebody fixes the outstanding problems (for me, at lest the PLL configuring and the SGMII lockup would be of necessity), we can switch to the upstream driver." :)

But could this be merged, since it is only testing? I would like to test 5.10er kernel for other stuff (xdp and so on).

**Comment by olerem** [comment]
I see now, on the QCA9563 is missing complete SGMII functionality, "8.8 GMAC Interface Registers".. looks like a huge stone, can't be done just within one weekend,

**Comment by olerem** [comment]
> But could this be merged, since it is only testing? I would like to test 5.10er kernel for other stuff (xdp and so on).

No problem from my side

**Comment by blocktrron** [comment]
@olerem The PLL settings refer to the clock generated for RGMII TX/RK for external PHYs (sould affect all chips with external PHYs)

The QCA955x needs a workaround, as the SGMII link get's stuck when changing the interface speed and needs to be reset multiple times to recover. See my ugly hack here: https://patchwork.ozlabs.org/project/openwrt/patch/20190411155945.28600-2-mail@david-bauer.net/

**Comment by olerem** [comment]
Ok, after bridge and vlan patches for ar9331 will go mainline, i'll start to work on ar9344  tl-wdr4300. This board seems to use external switch connected over RGMII interface.

**Comment by blocktrron** [comment]
@olerem Can you share the VLAN patches? I still have WIP patches for the QCA953x+ switch series against your DSA driver, but I was a bit unsure how to cope with the shortcomings of the switch hardware in terms of VLAN tagging.

Maybe i can take some inspirations from your work there :rocket:

**Comment by olerem** [comment]
Here is my current WIP code https://github.com/olerem/linux-2.6/commits/v5.11/topic/atheros-2021.02.18

VLAN tagging is currently not done, i need first investigate how per port vlan database is working and if it is possible to combine it with the main forwarding database.

**Comment by adschm** [comment]
> Maybe a dump question, but how can I directly build 5.10 kernel without changing the kernel version in the makefile? So using `KERNEL_TESTING_PATCHVER`?

make menuconfig -> Global build settings -> Use the testing kernel version

**Comment by PolynomialDivision** [comment]
> make menuconfig -> Global build settings -> Use the testing kernel version

Nice thanks.

**Comment by dengqf6** [comment]
Tested on WNDR3800

**Comment by 1Jeff1** [comment]
Tested on GL.iNet GL-AR750S [boot.log](https://gist.github.com/1Jeff1/51d894d6d2cc16bab229070b65898d32)

**Comment by msandber** [comment]
> The following patch is not contained, as it needs to be reworked:
> platform/920-mikrotik-rb4xx.patch

@blocktrron I did it mechanically here: https://github.com/msandber/openwrt/blob/ath79_kernel_5_10_support/target/linux/ath79/patches-5.10/920-mikrotik-rb4xx.patch

Looks pretty much like the one in 5.4, but i don't know if there are is issues beyond that.

**Comment by mrkiko** [comment]
Building now for the TP-Link TL-MR6400 V1 - I'll let you know of what happens. :)

**Comment by olerem** [comment]
> @olerem Can you share the VLAN patches? I still have WIP patches for the QCA953x+ switch series against your DSA driver, but I was a bit unsure how to cope with the shortcomings of the switch hardware in terms of VLAN tagging.
> 
> Maybe i can take some inspirations from your work there rocket

If you still need inspiration for the VLAN part https://github.com/olerem/linux-2.6/commits/v5.11/topic/atheros-2021.04.03-mainline

**Pull request closed without merging**
