### PR TITLE
bcm27xx: remove overlay FS on upgrade

### PR DESCRIPTION
**Pull request by wryun**
This addresses #9113 by adding extra space to the image if it doesn't fill the partition. Otherwise if the rootfs image is exactly the same size, the overlay is in the same place and is not reinitialised on upgrade (regardless of whether settings are kept or not).

Credit to @lespinasse and @plan44

### CODE REVIEW

**Comment by wryun** [comment]
@plan44 pointed out on the associated issue that this doesn't zero out space between the end of the FS and the next 512byte boundary as it should. In practice, I believe the overlay is aligned on 64kb blocks, so it's unlikely to cause issues, but...

**Comment by wryun** [comment]
(I would update this PR except I don't want to bother testing it again; if someone wants to open a corrected PR under their name I'll happily close this one)

**Comment by wryun** [comment]
Upstream has changed (notably dropping some vars that are relied on here). Going to close this for now, since interest seems low.

**Comment by plan44** [comment]
> since interest seems low.

OpenWrt seems to be a very tightly knitted community - so far I never succeeded to get any feedback to any attempt to contribute. Admittedly, fringe things like this one (who runs OpenWrt on Rpi?), but still, I couldn't figure out yet what I'm doing wrong, communication wise.

Just for the record, regarding the problem itself - I can't afford to brick my hundreds of Rpi's in the field. At the moment these are 22.03 and use the patch below which addresses this and another related f2fs problem occurring when the boot partition expands. Once I update to 23.07 or later I will need to re-test and adapt that patch. So if you happen to be in a similar situation sometime in the future, just let me know and I might have an update…

The patch as I am using it now on 22.03.5:

```diff
--- a/target/linux/bcm27xx/image/gen_rpi_sdcard_img.sh
+++ b/target/linux/bcm27xx/image/gen_rpi_sdcard_img.sh
@@ -22,8 +22,32 @@ BOOTSIZE="$(($2 / 512))"
 ROOTFSOFFSET="$(($3 / 512))"
 ROOTFSSIZE="$(($4 / 512))"
 
-dd bs=512 if="$BOOTFS" of="$OUTPUT" seek="$BOOTOFFSET" conv=notrunc
-dd bs=512 if="$ROOTFS" of="$OUTPUT" seek="$ROOTFSOFFSET" conv=notrunc
-
+# for sqashfs + f2fs layout, the rootfs image is only the sqashfs part, which
+# is (usually much) smaller than the rootfs partition.
+# The f2fs part (for the overlay) will be created only at first boot
+# into the new image, when mount_root does not detect a valid filesystem already
+# present. To make sure random data from previous installations are not falsely
+# detected (which could and did happen in earlier versions), we add 1 MB zero padding
+# or up to the end of the rootfs partition, whichever is less.
+# While the padding is required for the squashfs+f2fs layout only, it does not
+# interfere with other rootfs partition types such as ext4.
 
+# the image itself is usually less than the partition size (ROOTFSSIZE)
+ROOTFSBYTES="$(wc -c < $ROOTFS)"
+ROOTFSIMGSIZE="$(( ($ROOTFSBYTES+511) / 512))"
+# we start padding one block BEFORE image ends
+PADOFFSET="$(($ROOTFSOFFSET + $ROOTFSIMGSIZE - 1))"
+PADSIZE="$(($ROOTFSSIZE - ROOTFSIMGSIZE + 1))"
+# limit the padding to 1M, it needs to be just enough to prevent false fs detection by mount_root
+if (( $PADSIZE > 2048 )); then
+  PADSIZE=2048
+fi
 
+# write the boot partition
+dd bs=512 if="$BOOTFS" of="$OUTPUT" seek="$BOOTOFFSET" conv=notrunc
+# pad out some space after rootfs image, overlapping last block
+if (( $PADSIZE > 0 )); then
+  dd bs=512 if=/dev/zero of="$OUTPUT" seek="$PADOFFSET" count="$PADSIZE" conv=notrunc
+fi
+# write the rootfs image which does usually not fill the entire partition
+dd bs=512 if="$ROOTFS" of="$OUTPUT" seek="$ROOTFSOFFSET" conv=notrunc
--- a/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
+++ b/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
@@ -64,7 +64,17 @@ platform_do_upgrade() {
 
 		# Separate removal and addtion is necessary; otherwise, partition 1
 		# will be missing if it overlaps with the old partition 2
-		partx -d - "/dev/$diskdev"
+
+		# Note: this will still fail when partition2 is a f2fs. For some reason
+		#		the partition remains blocked and can't be removed, presumably by
+		#		f2fs having something open on the partdev despite being unmounted
+		#		and loopdev removed. So, partx -d will fail, and in consequence,
+		#		partx -a will then fail, too.
+		if ! partx -d - "/dev/$diskdev"; then
+			# removing partition failed, set marker to enable workaround
+			# below in platform_copy_config()
+			touch /tmp/partitions_blocked
+		fi
 		partx -a - "/dev/$diskdev"
 
 		return 0
@@ -86,14 +96,31 @@ platform_do_upgrade() {
 }
 
 platform_copy_config() {
-	local partdev
+	local partdev diskdev
 
-	if export_partdevice partdev 1; then
-		mkdir -p /boot
-		[ -f /boot/kernel.img ] || mount -t vfat -o rw,noatime "/dev/$partdev" /boot
-		cp -af "$UPGRADE_BACKUP" "/boot/$BACKUP_FILE"
-		tar -C / -zxvf "$UPGRADE_BACKUP" boot/cmdline.txt boot/config.txt
-		sync
-		umount /boot
+	if [ -f /tmp/partitions_blocked ]; then
+		# need to work around blocked partition: access possibly grown boot via loop
+		if export_bootdevice && export_partdevice diskdev 0; then
+			get_partitions "/dev/$diskdev" newbootdisk
+			read BOOTNO BOOTOFFS BOOTSZ < /tmp/partmap.newbootdisk
+			BYTEOFFS=$((BOOTOFFS * 512))
+			BYTESZ=$((BOOTSZ * 512))
+			LOOPDEV=$(losetup -f "/dev/$diskdev" -o $BYTEOFFS --sizelimit $BYTESZ --show)
+			mkdir -p /boot
+			[ -f /boot/kernel.img ] || mount -t vfat -o rw,noatime "$LOOPDEV" /boot
+			cp -af "$UPGRADE_BACKUP" "/boot/$BACKUP_FILE"
+			tar -C / -zxvf "$UPGRADE_BACKUP" boot/cmdline.txt boot/config.txt
+			sync
+			umount /boot
+		fi
+	else
+		if export_partdevice partdev 1; then
+			mkdir -p /boot
+			[ -f /boot/kernel.img ] || mount -t vfat -o rw,noatime "/dev/$partdev" /boot
+			cp -af "$UPGRADE_BACKUP" "/boot/$BACKUP_FILE"
+			tar -C / -zxvf "$UPGRADE_BACKUP" boot/cmdline.txt boot/config.txt
+			sync
+			umount /boot
+		fi
 	fi
 }
```

**Pull request closed without merging**
