### PR TITLE
ar71xx: Fix support of CPE510 v2

### PR DESCRIPTION
**Pull request by adschm**
Device support for the CPE510v2 so far has been a hack to enable
    flashing with CPE510v1 images. Those even have different hardware
    (e.g. additional ethernet port).

    With this simple patch, we provide proper support for this device
    in ar71xx.

~~This includes the first patch from #2252, so partitions remain consistent between tplink-safeloader.c and generic-tp-link.mk.~~ (Has been pushed already.)

This is supposed to be backported to 19.07, too. For this, the tplink-safeloader definition for CPE510v2 (introduced with ath79 support patch) has to be backported to ar71xx, too.

Based on PR #1631

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
@apcameron Can you test this on CPE510v2?

**Comment by apcameron** [comment]
Unfortunately as it is it bricked my device.
Please change mach-cpe510.c so it matches the one in the attached zip
[mach-cpe510.zip](https://github.com/openwrt/openwrt/files/3474733/mach-cpe510.zip)
Once I changed that file it booted.
See attached dmesg output
[dmesg.txt](https://github.com/openwrt/openwrt/files/3474734/dmesg.txt)

**Comment by adrianschmutzler** [comment]
@apcameron That's essentially the file from your PR, isn't it?
I only touched it because I thought the CPE510v2 is single-port, while the file initializes two eth?

**Comment by adrianschmutzler** [comment]
The differences in mach-cpe510.c are only affecting the network setup:
Your version:
```
	/* disable PHY_SWAP and PHY_ADDR_SWAP bits */
	ath79_setup_ar933x_phy4_switch(false, false);

	ath79_register_mdio(1, 0x0);
	/* WAN */
	ath79_switch_data.phy4_mii_en = 1;
	ath79_switch_data.phy_poll_mask = BIT(4);
	ath79_eth0_data.phy_if_mode = PHY_INTERFACE_MODE_MII;
	ath79_eth0_data.phy_mask = BIT(4);
	ath79_eth0_data.mii_bus_dev = &ath79_mdio1_device.dev;
	ath79_init_mac(ath79_eth0_data.mac_addr, mac, 1);
	ath79_register_eth(0);
	/* LAN */
	ath79_eth1_data.phy_if_mode = PHY_INTERFACE_MODE_GMII;
	ath79_eth1_data.duplex = DUPLEX_FULL;
	ath79_eth1_data.speed = SPEED_1000;
	ath79_init_mac(ath79_eth1_data.mac_addr, mac, 0);
	ath79_register_eth(1);
```

My version:
```
	ath79_register_mdio(0, 0x0);
	ath79_init_mac(ath79_eth0_data.mac_addr, mac, 0);
	ath79_eth0_data.duplex = DUPLEX_FULL;
	ath79_eth0_data.phy_if_mode = PHY_INTERFACE_MODE_MII;
	ath79_eth0_data.speed = SPEED_100;
	ath79_eth0_data.phy_mask = BIT(4);
	ath79_register_eth(0);
```

Everything else should be effectively the same.
Essentially, I just tried to reproduce the network setup from your ath79 DTS.

Despite, I'm not sure whether these changes are big enough to brick the device.

Is it possible that you did not include the safeloader-patch from my other PR, which changes partitioning in ar71xx? I will include it here, too.

**Comment by apcameron** [comment]
The CPE510 v2 is not the same as the CPE210 v2. The mdio is 1 not 0.
The reason I fire up both network ports is the device will not work if you just enable eth0. The workaround for that on the ath79 branch was to define eth1 as
compatible = "syscon" , "simple-mfd";
Note after today I will not be able to test again until near the end of the month

**Comment by adrianschmutzler** [comment]
@apcameron 

Okay, I understand.
Unfortunately this eliminates any options to condense code in the mach file, which I was looking for to enhance chances for this patch to be merged (by making it smaller).

I've updated the code now using your version (with tiny adjustments).
On top, I added a patch that removes only the eth1 initialization.

If you still have time, I would be happy if you could test two versions, one with the "Test" patch and one without (which should be almost identical to your initial patch). If both boot, I would be interested in the dmesg output of both.

**Comment by apcameron** [comment]
@adrianschmutzler Unfortunately this has patch conflicts that need to be resolved before I can test

**Comment by apcameron** [comment]
If I try to apply these changes as a patch I get the following
~/openwrt$ git apply --check patch.txt 
error: patch failed: target/linux/ar71xx/image/generic-tp-link.mk:172
error: target/linux/ar71xx/image/generic-tp-link.mk: patch does not apply
error: patch failed: tools/firmware-utils/src/tplink-safeloader.c:140
error: tools/firmware-utils/src/tplink-safeloader.c: patch does not apply
~/openwrt$

**Comment by adrianschmutzler** [comment]
@apcameron Resolved.
Just today the other CPE patches were pushed, and I didn't expect you to take the most recent version as base.
Now it's resolved, removing the safeloader patch from this PR.

**Comment by adrianschmutzler** [comment]
I won't be available for the next 9 hours or so, so good luck :-)

**Comment by apcameron** [comment]
I have tested it without the commit for **"Test: Remove unused eth1"** and it works as expected.
[info.txt](https://github.com/openwrt/openwrt/files/3479765/info.txt)
I ran out of time to test the last commit but will test tomorrow once it has compiled however from earlier tests I do not expect it to work with that one.

**Comment by apcameron** [comment]
@adrianschmutzler I was able to test again with eth1 removed (All commits in this PR) and the device worked. See file below for dmesg etc.
[info1.txt](https://github.com/openwrt/openwrt/files/3483794/info1.txt)
Based on that this PR has been successfully tested and ready to be merged from my side.

**Comment by adrianschmutzler** [comment]
okay, thank you for testing.
I will then squash the test patch into the one before and hope that this is still accepted.

**Comment by adrianschmutzler** [comment]
Pushed the squashed (=final) version.

**Comment by adrianschmutzler** [comment]
@blocktrron If you want to take care of this follow-up of the CPE support PR, it would be ready now.

**Comment by ynezz** [comment]
@adrianschmutzler I'm not big fan of the reverts, would this https://github.com/ynezz/openwrt/commit/d76f07f7466082e6c1097ca5dc91e460b1b5de68 work for you?

**Comment by adrianschmutzler** [comment]
> I'm not big fan of reverts, would this ynezz@d76f07f work for you?

@ynezz Yes, looks good.

I only did the revert because I thought it would be clearer this way; now we are closer to apcameron's initial PR again (https://github.com/openwrt/openwrt/pull/1631).

If you prefer the squashed version I won't complain, my main goal was to get rid of the hijacked safeloader entry in ath79 master somehow ...

**Comment by adrianschmutzler** [comment]
@apcameron I've backported this to 19.07, which was more complicated than expected.
Can you test my 19.07 tree (https://github.com/adrianschmutzler/openwrt/commits/staging-19.07) on CPE510 v1 _and_ v2, please?

**Comment by apcameron** [comment]
@adrianschmutzler I have tested it on my TP-LINK CPE510 v2 and it works normally including the sysupgrade and Wifi
@AE6XE Would you be able to test it on your TP-LINK CPE510 V1.1?

**Comment by ae6xe** [comment]
@apcameron, yes, but traveling back home to device and can test Nov 3, end of this week.

**Comment by adrianschmutzler** [comment]
@ynezz I suspect I can do the backport myself, or do you _want_ to do it?

**Comment by ynezz** [comment]
> @ynezz I suspect I can do the backport myself, or do you _want_ to do it?

Thanks for taking care of that!

**Comment by adrianschmutzler** [comment]
@ae6xe Any news?

**Comment by ae6xe** [comment]
Am I doing the right test you are looking for?   ar71xx arch image on your staging-19.07 branch, correct?   All is well.   WAN port to my home internet,  connected laptop to try both LAN port and wifi functional and posting this comment. 
[info.txt](https://github.com/openwrt/openwrt/files/3812484/info.txt)

**Comment by adrianschmutzler** [comment]
@ae6xe Yes, thanks to you and @apcameron for testing again.
So, i will merge this now and this is finally resolved.

**Pull request closed without merging**
