### PR TITLE
kernel: move rtl8152 patches to generic

### PR DESCRIPTION
**Pull request by abajk**
This commit moves the patches for the r8152.c driver to the generic directory. Previously they were only available on the bcm27xx target. With these patches the Realtek RTL8153C, RTL8153D, RTL8156A and RTL8156B chips are supported on all targets by the kmod-usb-net-rtl8152 module. The RTL8156A and RTL8156B are the 2.5Gb/s Ethernet adapters.

The patches have been tested on TP-Link UE300 (RTL8153A) and UNITEK 1313B (RTL8156B).

Signed-off-by: Aleksander Jan Bajkowski <olek2@wp.pl>

### CODE REVIEW

**Comment by ynezz** [comment]
> This patch adds support 

You should probably add that patch :)

**Comment by abajk** [comment]
> > This patch adds support
> 
> You should probably add that patch :) And while at it, keep those unrelated changes like patch filename renames in separate commits.

Instead of the word patch there should be the word commit. No additional patches are needed. The previously mentioned adapters probably worked correctly on the bcm27xx target. This PR moves these patches to generic.

**Comment by ynezz** [comment]
```
 16 files changed, 0 insertions(+), 0 deletions(-)
```
so your statement `kernel: kmod-usb-net-rtl8152: add support for newer chips` is quite misleading, you're just doing cleanup, renaming patches, making it clear, from which kernel version they were backported.

**Comment by chunkeey** [comment]
Merged. Thank you!

**Pull request closed without merging**
