### PR TITLE
[21.02] mvebu: add support for SFP cage of CZ.NIC Turris Omnia to 21.02 branch

### PR DESCRIPTION
**Pull request by ghost**
Cherry-picked from pull request https://github.com/openwrt/openwrt/pull/4372

Enables the SFP module for the CZ.NIC Turris Omnia in OpenWrt 21.02.

- The boot script is modified to detect the SFP's presence and switch `eth2` to it in case it is available. Otherwise the RJ45 WAN port is used.
- Minimally required DTS changes have been applied for Linux 5.4 only. (The original pull request also featured a more comprehensive set of changes for Linux 5.10.)

Tested with TP-Link TL-SM321B SFP module.

### CODE REVIEW

**Comment by kkudielka** [comment]
`Tested-by: Klaus Kudielka <klaus.kudielka@gmail.com>`

I believe the common practice is `git cherry-pick -x`, resulting in the automatic creation of the "cherry picked from commit" line in the commit message.

**Comment by kkudielka** [comment]
Well, I guess nobody would pull this series of 6 commits... You should have started from scratch (`git reset --hard`).

**Comment by kkeijzer** [comment]
@kkudielka Like this, then?

**Comment by kkeijzer** [comment]
@elkablo @BKPepe Could you review this PR, like you did for the original one for the `master` branch, as well?

**Comment by BKPepe** [comment]
Well, this was already reviewed for the **master** branch, and it was approved and merged. Because it was ``cherry-picked``, it does not require approval once again, right? Because this is not how OpenWrt developers with commit access are doing it.

Even though you haven't said which SFP modules you have and which have been tested, that's my doubt. Please, tell us first which SFP did you try. There are many differences``*`` when you will be using kernel 5.4 and kernel 5.10 (that's in the master branch as a testing kernel). You can enable it, but I think that most SFP modules will not work as they have support in kernel 5.10, and thus I am not sure if we want to merge it when the 4th RC version of OpenWrt 21.02 was released.

``*`` https://gitlab.nic.cz/turris/os/build/-/issues/286

**Comment by kkeijzer** [comment]
The only SFP modules I have are TP-Link TL-SM321B's, both version 2 and version 3. So those are the only modules I have tested.

**Comment by jschwartzenberg** [comment]
If there are many differences between 5.4 and 5.10, having this support backported might also be helpful to identify regressions that could have occurred. Although I'm on Turris OS, providing SFP support in the upcoming mainline 21.02 release would definitely make the Omnia stand out among the supported OpenWRT routers!

**Comment by nicorikken** [comment]
`Reviewed-by: Nico Rikken <nico@nicorikken.eu>`

I'm looking into an option for an OpenWRT-compatible router with SFP support, it looks like the Omnia will be the best option currently. Having this feature backported to the upcoming release would make a world of difference. There might be an edge case where somebody has an SFP module installed that does not work in Linux 5.4 which will be selected as the new default but won't function. This seems a real edge-case, which can be easy to debug (SFP will not work) and could be handled from OpenWRT by backporting kernel changes from 5.10 if there is user demand. Perhaps there should be a warning in the release notes about limited SFP module support. Some support would be better than no support.

**Comment by justinvansteijn** [comment]
`Reviewed-by: Justin van Steijn <justin@fsfe.org>`

**Comment by jschwartzenberg** [comment]
> `Tested-by: Klaus Kudielka <klaus.kudielka@gmail.com>`

Tested by the original author of the patches.


> Well, this was already reviewed for the **master** branch, and it was approved and merged. Because it was `cherry-picked`, it does not require approval once again, right? Because this is not how OpenWrt developers with commit access are doing it.

Already reviewed by Turris people for master.


> IMHO it is time to finally be able to use the SFP options in the Omnia-Turris on Open-WRT. Waiting for the perfect fit where all-SFP's would be able run on it probably means it will never materialize.
> Please release this in regular fashion, and create a list of supported SFP's along with it and add the list to the release notes.

Possibly there are many Dutch people responding as we simply have no other alternative to hook up to our ISPs other than through an SFP with OpenWRT. ISPs here are delivering fiber to the home connections through AON, also GPON and we can't find any OpenWRT compatible devices. As an alternative option I also contributed to testing a Fritzbox 5490 with OpenWRT, but WAN connectivity is simply not working yet and support for these models is way further from being mainlined (https://github.com/kestrel1974/openwrt/). Also this concerns a model for which the manufacturer already has released a successor (OpenWRT support is unlikely for it any time soon).

What else could be done to merge this and/or generally to enable OpenWRT for Dutch FTTH connections?
`Reviewed-by: Julius Schwartzenberg <julius.schwartzenberg@gmail.com>`

**Comment by kkeijzer** [comment]
Well, it looks like this PR did not make it in the silently released 21.02.0 stable images.

Is there any hope for getting this into 21.02.1, or will we all have to wait another two years before SFP support will finally arrive in OpenWrt stable images?

**Comment by kkeijzer** [comment]
Tonight, OpenWrt 21.02.1 was released. I built an image containing the SFP patches.

[openwrt-21.02.1-mvebu-cortexa9-cznic_turris-omnia-sysupgrade.img.gz](https://github.com/openwrt/openwrt/files/7446048/openwrt-21.02.1-mvebu-cortexa9-cznic_turris-omnia-sysupgrade.img.gz)
sha256sum: `69d20f47718306af82bc58e4b90fdc5633f57821b24268cd86cbf3f0dde14274`

This was a checkout of `v21.02.1` with only these two cherry picks: `82620cd610807da73935832e3751771866faa7c9` and `f2c57a294f567c4cd9fa163091a1026fb0bd351b`. I'm using this in production now with a TL-SM321B and it's working without any issues. If anyone is interested to test this, please do.

**Comment by justinvansteijn** [comment]
I upgraded my Turris Omnia from OpenWrt 21.02.0 to your patched version of 21.02.1 and notice no issues whatsoever in my router configuration without SFP.

**Comment by chunkeey** [comment]
hm, please note: the PR owner should add his signed-off-by to the commits too. But I don't think there's anything wrong going on here, so I merged this into 21.02 too.

**Pull request closed without merging**
