### PR TITLE
mt76: driver update to latest version

### PR DESCRIPTION
**Pull request by graysky2**
64c74dc9 mt76: fix dfs state issue with 160 MHz channels
c007ba3e mt76: mt7915: simplify conditional
de06d828 mt76: mt7921: fix injected MPDU transmission to not use HW A-MSDU
4f430954 mt76: mt7915: only use u32_get_bits with constant value
378b638c mt76: mt7915: fix unused variable with testmode disabled

Signed-off-by: John Audia <graysky@archlinux.us>

Maintainer: @nbd168

### CODE REVIEW

**Comment by mans0n** [comment]
Usually we follow this form for the commit message: 5a0975f7ef25

**Comment by graysky2** [comment]
@mans0n - Can you share the format string that generated that, ie `git log --pretty=format:"..."`

**Comment by mans0n** [comment]
Umm, I used `git log <last>..@ --oneline --no-decorate --reverse` in 19a90262df89. I guess adding `--abbrev=12` will result in 5a0975f7ef25.

**Comment by mans0n** [comment]
Superseded by da2b97210cdc...right?

**Pull request closed without merging**
