### PR TITLE
ath79: add support for TP-Link Archer D50 V1

### PR DESCRIPTION
**Pull request by DavideFioravanti**
This is a fixed version of this PR https://github.com/openwrt/openwrt/pull/1504.
I added the 8Mqca entry to mktplinkfw2 to make it working from flash.
I tested the flashing and restore procedure in the commit message.

### CODE REVIEW

**Comment by chunkeey** [comment]
Merged. Thanks.

**Comment by adrianschmutzler** [comment]
Although this PR has been has been closed already, I would be interested in some additional data about the device(s) in case you still have access to it:

I'm currently working on a PR to store the label-mac-address in the DTS (https://github.com/openwrt/openwrt/pull/2159).

I would appreciate if you could provide information about your device:
Please run
`find /proc/device-tree/ -name "*mac-address*"`
on your device (just with the current firmware, no need to update anything; just has to be ath79, no ar71xx).
For each of the returned paths (if there are any), retrieve the mac-address with `cat`, e.g.
`cat /proc/device-tree/ahb/eth@19000000/mac-address`

Now check which of those returned MAC addresses matches the one on the label/sticker/case of your device and tell me the device-tree path leading to it. Note that you do not have to post your MAC addresses here, but just a statement about which match, e.g. like
```
/proc/device-tree/ahb/eth@1a000000/mac-address
/proc/device-tree/ahb/eth@1a000000/mtd-mac-address-increment
/proc/device-tree/ahb/eth@1a000000/mtd-mac-address
/proc/device-tree/ahb/eth@19000000/mac-address <== this one
/proc/device-tree/ahb/eth@19000000/mtd-mac-address
/proc/device-tree/ahb/apb/wmac@18100000/mac-address
/proc/device-tree/ahb/apb/wmac@18100000/mtd-mac-address
```

There may be one, two or no paths giving the correct address. It may also happen that the `find` command returns nothing. Thanks.

**Comment by adrianschmutzler** [comment]
Unfortunately, my description is slightly incorrect. The MAC addresses are stored binary, so you can't read with `cat`, but have to use the following code to read from the paths retrieved by `find`:
```
. /lib/functions/system.sh
get_mac_binary "$yourpath" 0
```
The include is obviously only required once. Sorry.

**Comment by DavideFioravanti** [comment]
@adrianschmutzler 
Thanks to @suppenkasper0815 we have the values: https://forum.openwrt.org/t/archer-d50-support/38613/10?u=numero53

```
/proc/device-tree/ahb/eth@1a000000/mac-address ==> XX:XX:XX:XX:XX:db (mac on the sticker)
/proc/device-tree/ahb/apb/wmac@18100000/mac-address ==> XX:XX:XX:XX:XX:db (mac on the sticker)
/proc/device-tree/ahb/eth@19000000/mac-address ==> XX:XX:XX:XX:XX:dc
```

**Comment by adrianschmutzler** [comment]
Thanks, added the information to my PR #2159

**Comment by suppenkasper0815** [comment]
Hey, do you think there is a chance to get SFE-Support soon for our D50? With my D7 the performance from Wifi to WAN increased from 180Mbit/s to 400Mbit/s and LAN to WAN from 400Mbit/s to 600Mbit/s. I guess it's pretty similar here if I finally get it to work AP+STA on 5G or to use somehow 2G for WAN and 5G for LAN/Wifi as Repeater.

**Pull request closed without merging**
