### PR TITLE
ramips: improve and fix for Buffalo WCR-1166DS

### PR DESCRIPTION
**Pull request by musashino205**
The current factory image of WCR-1166DS causes kernel panic and bootloop, so fix the issue by using parser_trx in upstream with specifying the custom trx magic number.
And also, this patch series contains some improvements for WCR-1166DS.

### CODE REVIEW

**Comment by mans0n** [comment]
> But the current mtdsplit_trx doesn't support the custom magic number and
fail to parse and split to kernel and rootfs when the factory image is
flashed. Then, the kernel fails to mount rootfs automatically and panics.

Do you know exactly when it started to break? The original support patch (6b0b526a4fc1) used trx without custom magic for sysuprade image, then was it broken from the very beginning?

**Comment by musashino205** [comment]
Great, thank you for the investigation. I'll add a note about it to the last commit.

**Comment by musashino205** [comment]
UPDATE:

- added a note about the custom magic number support which existed on the old kernel version

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in 621d88d7416a61ee3bae0211ab518ab39ea77324, 770cfe9bffbe53fc9c3802041e0c1b1fda8fc015, cc49abc06bca59911caf5b904c3181814636e4da, d339de2e215f718529e8001ecb102241131f395d, 5403defbec81ef2daaddc191d34f653cb1ab3050 and f7f9e6bd20bbdca6f136d469d1712e6b124635b4

**Pull request closed without merging**
