### PR TITLE
kernel: bump 5.4 to 5.4.172

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.
```
Build system: x86_64
Build-tested: ramips/mt7621
```
Signed-off-by: John Audia <graysky@archlinux.us>

### CODE REVIEW

**Comment by abajk** [comment]
You forgot to modify the include / kernel-version.mk file.

**Comment by graysky2** [comment]
Spooky... used the update script as always, but you are correct.

**Comment by Beginner-Go** [comment]
@graysky2 should be written as `LINUX_KERNEL_HASH-5.4.171`

**Comment by graysky2** [comment]
@Beginner-Go - Thanks fixed in 38bac38948044cb1e7da423fdca6553cb5d756e6

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 53252c4ce937c32e2f7367448bb49d1fbf3d1e82 and a28afb92143b5a1dfa6327a265967dd0b800ea46

**Pull request closed without merging**
