### PR TITLE
ath25: fix ELF and initramfs image generation

### PR DESCRIPTION
**Pull request by Leo-PL**
This PR contains two fixes which restore the correct contents of ELF images, which were not restored correctly in 21f460a5dbef.
First patch selects correct source artifact for generic kernel.elf.
Second patch restores initramfs build recipe to use just vmlinux-initramfs.elf as the source, and adjusts artifact suffix to match the non-initramfs.

Run tested on D-Link DWR-3200AP A1.

### CODE REVIEW

**Comment by Leo-PL** [comment]
CC @jow- and @rsa9000

**Comment by rsa9000** [comment]
Hello Leo,

I do not build- or run-test them, but at first glance the patches look good. And if you successfully run test an output image, then I think that this should be merged.

Let me know if you need more build- or run-tests. And thanks to @jow- and you for noticing and taking care of this issue, I have not even seen it in 6 years :)

**Comment by Leo-PL** [comment]
@rsa9000 I think that's enough - sort of, I have yet to RAM-mod my device to make it fully boot, but also by checking contents with binwalk, I think the contents are OK.

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in 611291383a826827f240eddebca1949c2e1e7115 and 9f5cbb6e8b9537942db405719bf7662d0e08b8c5.

**Pull request closed without merging**
