### PR TITLE
iputils: update to 20151218

### PR DESCRIPTION
**Pull request by dengqf6**
This is based on commit 77d3ac8e3ecd7989a7cffb575c4a42bc68190b6c
@jow- @blogic

### CODE REVIEW

**Comment by diizzyy** [comment]
@dengqf6 
Can you switch to this repo instead?
https://github.com/iputils/iputils

**Comment by dengqf6** [comment]
This repo has merged `ping`, `ping6` into single `ping` exec, making it difficult to build without IPv6 support.
Same applies to `tracepath`

**Comment by diizzyy** [comment]
Is that an issue 2019? :-) Just make it depend on IPv6

**Comment by hauke** [comment]
I think the output format of ifconfig changes, do we have any scripts parsing this?

**Comment by dengqf6** [comment]
@hauke
ifconfig doesn't belong to iputils

**Comment by peterwillcn** [comment]
@xback merge it?

**Comment by pevik** [comment]
> This repo has merged ping, ping6 into single ping exec, making it difficult to build without IPv6 support.

@dengqf6 Any particular suggestion, how to fix this in https://github.com/iputils/iputils? Can you please describe the problem more here or (better) in https://github.com/iputils/iputils/issues?
IMHO fixing this and using live project is better that use C based project with no maintenance. I guess, we're open to ideas and patches.

**Comment by adrianschmutzler** [comment]
This has not seen any progress in 6 months. What's the status?

**Comment by dengqf6** [comment]
@adrianschmutzler Thanks for the head up. I may consider switching to https://github.com/iputils/iputils

**Comment by pevik** [comment]
yes, meson is required. Is it a problem for openwrt?

**Comment by neheb** [comment]
Yes and no. There's no meson or ninja under tools. There's a PR under packages that I plan to merge that adds both, which would either mean iputils must be moved to packages, or meson/ninja must be moved here. ping @ynezz 

As for the IPv6 dependency, I see no problem. This is a heavier weight package than busybox, which has both ping and ping6.

**Comment by dhewg** [comment]
@dengqf6 meson landed in packages, so this could be moved there as well and built with meson

**Comment by nmeyerhans** [comment]
Unfortunately I think we'll find the that iputils code at https://github.com/iputils/iputils has incorporated some GNU libc extensions in its code, and is unlikely to build with MUSL at the moment. For example, it makes use of the nonstandard `error()` library function in numerous places.

**Comment by pevik** [comment]
@nmeyerhans https://github.com/iputils/iputils strives to be musl compatible. Please report any bug of broken incompatibility.

But IMHO atm it *is* musl compatible. Buildroot (https://buildroot.org/) uses also uclibc-ng and musl and builds for both of them (tested manually current master, also their CI http://autobuild.buildroot.net/, which tests latest release does not report anything). Iputils requires only MMU (https://git.busybox.net/buildroot/tree/package/iputils/Config.in https://git.busybox.net/buildroot/tree/package/iputils/iputils.mk).

Ad `error()`: it has fallback implementation if `errno.h` not available https://github.com/iputils/iputils/blob/master/iputils_common.c#L14

**Comment by nmeyerhans** [comment]
> Ad `error()`: it has fallback implementation if `errno.h` not available https://github.com/iputils/iputils/blob/master/iputils_common.c#L14

Ack, thanks for clarifying! I somehow missed that. Glad to hear that compatibility with non-GNU libc implementations remains a goal.

**Comment by pevik** [comment]
@nmeyerhans FYI make sure musl compiles :) https://github.com/iputils/iputils/pull/227 https://travis-ci.org/pevik/iputils/builds/606796987

**Comment by pevik** [comment]
BTW, there was newer release s20190709 (title asks for 20151218).

**Comment by ynezz** [comment]
> iputils must be moved to packages

right, it aligns with my view on that topic http://lists.infradead.org/pipermail/openwrt-devel/2019-August/018399.html

**Comment by adrianschmutzler** [comment]
So, someone will have to open a PR for the newer version in packages, and, after this is merged, we can remove the old version here?

**Comment by nmeyerhans** [comment]
I'd be happy to package the newer iputils for the packages repo, unless
somebody else feels particularly possessive of it.  I'm already
maintaining it in Debian and am reasonably involved in tracking
development, etc.

**Comment by adrianschmutzler** [comment]
Thanks, go ahead :-)

**Comment by nmeyerhans** [comment]
Opened a PR with packages as openwrt/packages#10633. This PR can be closed (I don't have permission to do that.). I will open another one here to remove iputils once it's merged into packages.

**Comment by dengqf6** [comment]
@nmeyerhans ping

**Comment by nmeyerhans** [comment]
@dengqf6 What's the ping for? AFAIK there is no more to do here. #10633 has been merged, and the removal from the main tree is [here](https://git.openwrt.org/?p=openwrt/staging/ynezz.git;a=commitdiff;h=cf9f7cd1118491129b7b1bd3f98c7138f2947395).

**Comment by BKPepe** [comment]
Can we do the same for OpenWrt 19.07? mwan3 is broken because of old version of iputils according to [author
](https://github.com/openwrt/packages/issues/12836#issuecomment-668479431). It will fix also https://bugs.openwrt.org/index.php?do=details&task_id=1486 and https://bugs.openwrt.org/index.php?do=details&task_id=2724

Meson is present in packages feed for OpenWrt 19.07 and as meson does not get into the main repo (https://github.com/openwrt/openwrt/pull/2312#issuecomment-519927434), there needs to be something done for OpenWrt 19.07 as it is current stable release where should be security and bug (this case) fixes introduced.

**Comment by feckert** [comment]
> Can we do the same for OpenWrt 19.07? mwan3 is broken because of old version of iputils according to [author ](https://github.com/openwrt/packages/issues/12836#issuecomment-668479431). It will fix also https://bugs.openwrt.org/index.php?do=details&task_id=1486 and https://bugs.openwrt.org/index.php?do=details&task_id=2724

I have backport the mwan3 master version to openwrt-19.07 stable branch.
So the mwan3 version is pinned to use the busybox [ping](https://github.com/openwrt/packages/blob/openwrt-19.07/net/mwan3/files/usr/sbin/mwan3track#L9) binary.

**Comment by BKPepe** [comment]
But it is just not about mwan3 as you referenced in this commit message:
https://github.com/openwrt/packages/commit/19bebd3d89b50837fe0bc23c51a729bd2a0c2476

**Comment by feckert** [comment]
@BKPepe that was only a hint.

**Comment by nmeyerhans** [comment]
> Can we do the same for OpenWrt 19.07? mwan3 is broken because of old version of iputils according to [author ](https://github.com/openwrt/packages/issues/12836#issuecomment-668479431). It will fix also https://bugs.openwrt.org/index.php?do=details&task_id=1486 and https://bugs.openwrt.org/index.php?do=details&task_id=2724
> 
> Meson is present in packages feed for OpenWrt 19.07 and as meson does not get into the main repo ([#2312 (comment)](https://github.com/openwrt/openwrt/pull/2312#issuecomment-519927434)), there needs to be something done for OpenWrt 19.07 as it is current stable release where should be security and bug (this case) fixes introduced.

What specifically are you asking for? I'm guessing it is:

1. Removal of iputils from base in the openwrt-19.07 branch (essentially cherry-picking 98b3526bf23e8d1b48939c937c9b12e4f2160415)
2. Adding the `net/iputils` subdirectory to the openwrt-19.07 branch in packages (essentially cherry-picking https://github.com/openwrt/packages/commit/556698cedf9e86a0ffe9f148d4e8e733676c26f6)

Anything else?

Is this a reasonable change to make in what is intended as a stable branch?

**Comment by BKPepe** [comment]
Exactly as you described, yes. I think there are a several good reasons why to include it in OpenWrt 19.07. For example, those two bug reports which was mention and there are bugs in iputils referenced in the mwan3 commit.

**Pull request closed without merging**
