### PR TITLE
bpftools: add utility and library packages supporting eBPF usage

### PR DESCRIPTION
**Pull request by guidosarducci**
**Review/Distribution List**:  @tchebb 
**Compile tested**:  mips{32,64}-{be,le}-malta & armvirt-{32,64}, master branch
**Run tested**:  mips{32,64}-{be,le}-malta & armvirt-{32,64}, master branch (using QEMU)

**Description**:
Add support for building `bpftool` and `libbpf` from the latest 5.8.3 kernel sources, ensuring up-to-date functionality and fixes. Both are written to be backwards compatible, which simplfies build and usage across different OpenWRT image kernels.

`bpftool` is the primary userspace tool widely used for introspection and manipulation of eBPF programs and maps. Two variants are built: a 'full' version which supports object disassembly and depends on libbfd/libopcodes (total ~500KB); and a 'minimal' version without disassembly functions and dependencies. The default 'minimal' variant is otherwise fully functional, and both are compiled using LTO for further (~30KB) size reductions.

`libbpf` provides shared/static libraries and dev files needed for building userspace programs that perform eBPF interaction.

Several cross-compilation and build-failure problems are addressed by new patches and ones backported from farther upstream:
  * 001-libbpf-ensure-no-local-symbols-counted-in-ABI-check.patch
  * 002-libbpf-fix-build-failure-from-uninitialized-variable.patch
  * 003-bpftool-allow-passing-BPFTOOL_VERSION-to-make.patch
  * 004-v5.9-bpftool-use-only-ftw-for-file-tree-parsing.patch

Building also requires an common extension to the `nftw` library code which is missing in musl:
  * 600-nftw-support-common-gnu-extension.patch

NOTE: `bpftool` supports a skeleton generation feature which requires build-time usage of `clang`. Since this isn't guaranteed to be available in OpenWRT build environments (e.g. buildbots) the feature is disabled for now.

Appreciate your review and feedback!

### CODE REVIEW

**Comment by zorun** [comment]
Nice!

Where do libbfd and libopcodes come from?

Patching musl should be done with care. Did you send the patch upstream? Could it be that defining `_GNU_SOURCE` has adverse effects? Can you provide a size comparison? Also, please bump `PKG_RELEASE` in common.mk.

**Comment by adschm** [comment]
Do we need bpftools in main repo, or could it go to packages?

**Comment by guidosarducci** [comment]
@zorun :
> Nice!
> 
Thanks, I think the availability of `bpftool` has been the last big obstacle to people experimenting more with BPF on OpenWRT, following prior BPF improvements made to `iproute2`, `tc` classifier/actions, test modules, etc. It can also be challenging since embedded systems and cross-compilation aren't always front-of-mind for the leading-edge of development; I've run into several such issues while expanding BPF support and also looking at BTF.
> Where do libbfd and libopcodes come from?
> 
These are already provided by OpenWRT `binutils` package.
> Patching musl should be done with care. Did you send the patch upstream? Could it be that defining `_GNU_SOURCE` has adverse effects? Can you provide a size comparison? Also, please bump `PKG_RELEASE` in common.mk.
>
I'm trying to upstream all patches, if only for the sake of maintainability. There are a few kernel BPF and BTF patches, one of which was accepted so far, a couple which are ready to upstream, and others which are part of an in-progress series trying fix some BTF probelms.

The musl changes are well isolated, and based on an earlier patch submitted to the musl mailing list which sparked interest, but lacked follow-up by the submitter. I expect up-streaming should be OK, and this is the next patch in my up-streaming queue. The `_GNU_SOURCE` define is the standard documented way for program source to enable the `FTW_ACTIONRETVAL` extension, and is already used by musl for similar feature management. I don't recall a noticeable size difference in the library, not surprising given this adds only ~50 SLOC to an existing function. Did you notice a problem? Oh, thanks for the `PKG_RELEASE` reminder, will take of that...

@adschm : 
> Do we need bpftools in main repo, or could it go to packages?
>
It should really be in the main repo I think. It's a core subsystem for networking and performance measurement, and also intended to be built from kernel sources. Some of these same considerations are also shared by `perf`, `iptables`, `nftables`, `iproute2` and `ipset`, which are also in the main repo.

**Comment by robimarko** [comment]
@guidosarducci Hi, I am also interested in BPF userspace tooling support in OpenWrt.
Where you may be able to send the necessary patches upstream?
That would surely speed up the review process.

**Comment by guidosarducci** [comment]
Some necessary patches are already upstreamed and hence removed from this PR which is using the latest stable kernel. @tchebb  also had some needed patches accepted recently.

Patches with names containing a kernel version (`004-v5.9-bpftool-use-only-ftw-for-file-tree-parsing.patch`) have been accepted and can be removed in future, much like the kernel patches in our `target/linux/generic/backport-*` tree.

I'll deal with the remaining patches hopefully over the next few days. BTW, there will be another related PR enabling BTF support that also requires kernel patches...

**Review by dangowrt — APPROVED** [review]

**Comment by dangowrt** [comment]
Merged. Thanks!

**Comment by guidosarducci** [comment]
Thanks, I'll push the nls support stuff in a separate PR. ( I suppose I should have switched to "draft" as soon as I realized...)

@tchebb Hi Thomas, did you have a chance to try building against `libbpf` for your particular use case? That would be a useful data point to have. Otherwise, I think I took on all your earlier feedback -- thanks again for that.

**Comment by guidosarducci** [comment]
Update: two more patches have been accepted upstream:
* 001-libbpf-ensure-no-local-symbols-counted-in-ABI-check.patch
* 002-libbpf-fix-build-failure-from-uninitialized-variable.patch

**Pull request closed without merging**
