### PR TITLE
ramips: fix TP-Link RE200 v3/v4 LEDs

### PR DESCRIPTION
**Pull request by AiyionPrime**
> Reported-by: Richard Fröhning <misanthropos@gmx.de>
> Signed-off-by: Sungbo Eo <mans0n@gorani.run>

If it works, it supersedes #9258 and #4954.

@misanthropos offered to test it on his re200 v3 and v4.

### CODE REVIEW

**Comment by hauke** [comment]
Could someone please test this and report back if the LEDs are working correctly on one of the affected devices. Please also name the device you tested this on.

**Comment by AiyionPrime** [comment]
@misanthropos wrote earlier this afternoon he successfully tested it on an RE200v3.

He did test it on a v4 as well, but though the LEDs do work just fine, v4 is currently affected by some mac error, which results in 5Ghz wifi not working properly.
But that's unrelated to this PR and apparently a problem in current nightlies as well.

**Comment by misanthropos** [comment]
I have tested this commit with latest master on v3 and v4 - LED settings are correct.

**Comment by hauke** [comment]
Please add some description to the commit.

**Comment by AiyionPrime** [comment]
> Please add some description to the commit.

done.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in 02aa7a2bb9b6bdc8033d30c97f5b49534206a37c.

**Pull request closed without merging**
