### PR TITLE
ramips: add support for ELECOM WRC-733GHBK

### PR DESCRIPTION
**Pull request by musashino205**
ELECOM WRC-733GHBK is a 11ac router, based on MediaTek MT7620A.

Specification:

- MediaTek MT7620A
- 64 MB of RAM (DDR2)
- 8 MB of RAM (SPI-NOR)
- 2.4/5 GHz wifi
  - 2.4 GHz: 2T2R (SoC internal)
  - 5 GHz: 1T1R (MT7610E)
- 5x 10/100/1000 Mbps Ethernet
  - Realtek RTL8367RB switch
- 4x LEDs, 3x keys (2x buttons, 1x slide switch)
- UART through-hole on PCB
  - TX, GND, RX, Vcc from ethernet port side
  - 57600n8

Flash instruction using factory image:

1. Boot the WRC-733GHBK normaly and connect the computer to its LAN
port
2. Access to "http://192.168.2.1/" and open firmware update page
("ファームウェア更新 手動更新（アップデート）")
3. Select the OpenWrt factory image and click apply ("適用") button
to perform firmware update
4. On the (initramfs) factory image, execute sysupgrade with
squashfs-sysupgrade image for WRC-733GHBK
5. Wait ~150 seconds to complete flashing

Signed-off-by: INAGAKI Hiroshi <musashino.open@gmail.com>

### CODE REVIEW

**Comment by musashino205** [comment]
I am working on activating MT7610E in relation to 202ac58ca224032866f16c844cfc63396e2af928, but since WRC-733GHBK does not have a correct MAC address in "Factory" and it needs to be patched.

How should I do it?

**Comment by mkresin** [comment]
First of all, you need to point the driver to the eeprom on flash. Something like the following might work but to be really sure, please provide the output of `ls -F /sys/devices/pci*`

```
&pcie {
	wifi@0,0 {
		reg = <0x0000 0 0 0 0>;
		mediatek,mtd-eeprom = <&factory 0x8000>;
		ieee80211-freq-limit = <5000000 6000000>;
	};
};
```

If the above work, you can try the same with `ralink,eeprom = "my.eeprom";` instead of mediatek,mtd-eeprom. You should be able to handle the eeprom request for "my.eeprom" in `/etc/hotplug.d/firmware/10-rt2x00-eeprom`. And there you can patch the mac address if necessary.

I'm not yet sure if the driver requests an eeprom file if ralink,eeprom is not set and which name would be used. Might be you don't need the dts stuff.

**Comment by musashino205** [comment]
Thanks for your informations, I'll try it later.

**Comment by musashino205** [comment]
output of ```ls -F /sys/devices/pci*```:
```
root@OpenWrt:/# ls -F /sys/devices/pci*
0000:00:00.0/ pci_bus/      uevent
```

I dropped ```mediatek,mtd-eeprom```:
```
[   12.849333] mt76x0e 0000:01:00.0: card - bus=0x1, slot = 0x0 irq=4
[   12.861904] mt76x0e 0000:01:00.0: ASIC revision: 76100002
[   13.128346] mt76x0e 0000:01:00.0: Firmware Version: 0.1.00
[   13.234954] mt76x0e 0000:01:00.0: driver does not support default EEPROM
[   13.248446] mt76x0e: probe of 0000:01:00.0 failed with error -22
```

And, I got same error with following changes:
```
diff --git a/target/linux/ramips/base-files/etc/hotplug.d/firmware/10-rt2x00-eeprom b/target/linux/ramips/base-files/etc/hotplug.d/firmware/10-rt2x00-eeprom
index 815b1018e6..94143c0370 100644
--- a/target/linux/ramips/base-files/etc/hotplug.d/firmware/10-rt2x00-eeprom
+++ b/target/linux/ramips/base-files/etc/hotplug.d/firmware/10-rt2x00-eeprom
@@ -52,6 +52,18 @@ FW="/lib/firmware/$FIRMWARE"
 board=$(board_name)

 case "$FIRMWARE" in
+"mt7610e.eeprom")
+       case $board in
+       elecom,wrc-733ghbk)
+               wifi_mac=$(mtd_get_mac_ascii hwconfig HW.LAN.5G.0.MAC.Address)
+               rt2x00_eeprom_extract "Factory" 32768 512
+               rt2x00_eeprom_set_macaddr $wifi_mac
+               ;;
+       *)
+               rt2x00_eeprom_die "Please define mtd-eeprom in $board DTS file!"
+               ;;
+       esac
+       ;;
 "soc_wmac.eeprom")
        case $board in
        dlink,dwr-116-a1|\
diff --git a/target/linux/ramips/dts/WRC-733GHBK.dts b/target/linux/ramips/dts/WRC-733GHBK.dts
index ab72d770b5..d55b36f565 100644
--- a/target/linux/ramips/dts/WRC-733GHBK.dts
+++ b/target/linux/ramips/dts/WRC-733GHBK.dts
@@ -166,7 +166,7 @@
 &pcie0 {
        wifi@0,0 {
                reg = <0x0000 0 0 0 0>;
-               mediatek,mtd-eeprom = <&Factory 0x8000>;
+               ralink,mtd-eeprom = "mt7610e.eeprom";
                ieee80211-freq-limit = <5000000 6000000>;
        };
 };
```

**Comment by mkresin** [comment]
Please try `reg = <0x10000 0 0 0 0>;` instead. Your pci card is at 0000:01:00.0 and not 0000:00:00.0 as I assumed first.

Here my quick notes on how to calculate the correct reg:

```
0000:00:0e.0
     -------

00000000 00000000 01110000 00000000
npt000ss bbbbbbbb dddddfff rrrrrrrr

n == NOT relocatable (0 if relocatable, 1 if fixed).
p == prefetchable (cacheable).
t == aliased (Non-Relocatable I/O), below 1 MB (Memory), or below 64 KB (relocatable I/O).
s == 2-bit address space (Configuration [00], I/O [01], 32-bit Memory [10], 64-bit Memory [11]).

b == (8-bit bus number ) == 11111111 == FF
d == (5-bit device nb)   == 11111    == 1F
f == (3-bit function nb) == 111      == 3

r == 8-bit register number.

address cell 0: npt000ss bbbbbbbb dddddfff rrrrrrrr
address cell 1: hhhhhhhh hhhhhhhh hhhhhhhh hhhhhhhh
address cell 2: llllllll llllllll llllllll llllllll
```

**Comment by musashino205** [comment]
I changed to ```reg = <0x10000 0 0 0 0>;```, but same error occurred.
```
[   12.610313] mt76x0e 0000:01:00.0: card - bus=0x1, slot = 0x0 irq=4
[   12.622885] mt76x0e 0000:01:00.0: ASIC revision: 76100002
[   12.889471] mt76x0e 0000:01:00.0: Firmware Version: 0.1.00
[   12.999241] mt76x0e 0000:01:00.0: driver does not support default EEPROM
[   13.012728] mt76x0e: probe of 0000:01:00.0 failed with error -22
```

**Comment by mkresin** [comment]
Dangit! We are talking about the mt76 driver family, while I was the opinion it's the rt2x00 driver. The "ralink,eeprom" is only supported by the rt2x00 driver, which doesn't support the MT7610E wireless chip.

To my reading of the driver, the only way to get the eeprom is via `mediatek,mtd-eeprom`. There is no support for delegating the eeprom extraction to the userspace (yet).

1. https://github.com/openwrt/mt76/blob/5195257f22ce82e4108c4d5db8809867bfe46399/mt76x0/eeprom.c#L310
2. https://github.com/openwrt/mt76/blob/1d4ca10a562b6d9eaec3aaa5f3905804070ae743/eeprom.c#L103
3. https://github.com/openwrt/mt76/blob/1d4ca10a562b6d9eaec3aaa5f3905804070ae743/eeprom.c#L24

**Comment by musashino205** [comment]
Oh, I see.
Then, eeprom file must be supported first in openwrt/mt76, but to be honest I do not have the skills to do that...

**Comment by ynezz** [comment]
@mkresin @musashino205 If I read the dmesg correctly, maybe [this patch](https://github.com/openwrt/mt76/pull/209/commits/e9e5a6f37ae43bb0588072161c566de45eec5980) from @CHKDSK88 could be worth looking at?

**Comment by musashino205** [comment]
It seems to support only setting with the following dts properties:
- mac-address
- local-mac-address
- mtd-mac-address

In WRC-733GHBK, it has no hex mac address and stored as texts.
```
root@OpenWrt:/# hexdump -C /dev/mtd8
00000000  45 44 4d 58 00 00 00 4c  00 00 01 0d 48 57 2e 35  |EDMX...L....HW.5|
00000010  47 2e 43 61 6c 69 62 72  61 74 69 6f 6e 2e 50 72  |G.Calibration.Pr|
00000020  6f 64 75 63 74 69 6f 6e  3d 4f 4e 00 48 57 2e 43  |oduction=ON.HW.C|
00000030  6f 75 6e 74 72 79 49 44  3d 34 30 31 33 00 48 57  |ountryID=4013.HW|
00000040  2e 41 55 54 4f 46 57 2e  53 65 72 76 65 72 2e 55  |.AUTOFW.Server.U|
00000050  52 4c 3d 68 74 74 70 73  3a 2f 2f 75 70 64 61 74  |RL=https://updat|
00000060  65 2e 65 6c 65 63 6f 6d  2e 63 6f 2e 6a 70 2f 61  |e.elecom.co.jp/a|
00000070  75 74 6f 2f 75 70 64 61  74 65 2f 00 48 57 2e 52  |uto/update/.HW.R|
00000080  65 67 69 6f 6e 44 6f 6d  61 69 6e 3d 4a 50 00 48  |egionDomain=JP.H|
00000090  57 2e 4c 41 4e 2e 4d 41  43 2e 41 64 64 72 65 73  |W.LAN.MAC.Addres|
000000a0  73 3d 30 30 39 30 46 45  43 39 43 42 45 35 00 48  |s=0090FEC9CBE5.H|
000000b0  57 2e 4c 41 4e 2e 32 47  2e 30 2e 4d 41 43 2e 41  |W.LAN.2G.0.MAC.A|
000000c0  64 64 72 65 73 73 3d 30  30 39 30 46 45 43 39 43  |ddress=0090FEC9C|
000000d0  42 45 36 00 48 57 2e 4c  41 4e 2e 35 47 2e 30 2e  |BE6.HW.LAN.5G.0.|
000000e0  4d 41 43 2e 41 64 64 72  65 73 73 3d 30 30 39 30  |MAC.Address=0090|
000000f0  46 45 43 39 43 42 45 37  00 48 57 2e 57 41 4e 2e  |FEC9CBE7.HW.WAN.|
00000100  4d 41 43 2e 41 64 64 72  65 73 73 3d 30 30 39 30  |MAC.Address=0090|
00000110  46 45 43 39 43 42 45 34  00 00 00 00 00 00 00 00  |FEC9CBE4........|
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

**Comment by ynezz** [comment]
@musashino205 Ahh, I see now, bummer.

**Comment by musashino205** [comment]
Since there is no prospect of solving eeprom, I'll close this PR once...

**Pull request closed without merging**
