### PR TITLE
u-boot,at91bootstrap: fix incorrect HOSTCPPFLAGS variable

### PR DESCRIPTION
**Pull request by commodo**
This would should up as `$$(HOSTCPPFLAGS)` in the host CFLAGS.
```
make --jobserver-fds=3,4 -j -C <openwrt>/build_dir/target-arm_cortex-a8+vfpv3_musl_eabi/u-boot-A10-OLinuXino-Lime/u-boot-2017.07 CROSS_COMPILE=arm-openwrt-linux-muslgnueabi- DTC="<openwrt>/build_dir/target-arm_cortex-a8+vfpv3_musl_eabi/linux-sunxi_cortexa8/linux-4.9.76/scripts/dtc/dtc" HOSTCC="gcc" HOSTCFLAGS='-O2 -I<openwrt>/staging_dir/host/include -I<openwrt>/staging_dir/host/usr/include -I<openwrt>/staging_dir/hostpkg/include -I<openwrt>/staging_dir/target-arm_cortex-a8+vfpv3_musl_eabi/host/include $$(HOSTCPPFLAGS)' HOSTLDFLAGS="" BL31=<openwrt>/staging_dir/target-arm_cortex-a8+vfpv3_musl_eabi/image/bl31.bin
```

And then it would complain with:
```
 /bin/sh: 1: HOSTCPPFLAGS: not found
```

Also, HOSTCPPFLAGS does not exist.
The correct var is HOST_CPPFLAGS.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by NeoRaider** [comment]
HOSTCPPFLAGS is a variable in the uboot Makefile. The idea of `$$$$(HOSTCPPFLAGS)` is to defer the resolution of this variable to the actual use site. Unfortunately, this fails, as HOSTCFLAGS is not always evaluated the same number of times by uboot's different Makefiles, and thus may reach the shell as `$(HOSTCPPFLAGS)`.

It should be researched if changing this to `$$(HOSTCPPFLAGS)` is correct, or if a patch to the u-boot Makefiles would be a more appropriate fix.

**Comment by commodo** [comment]
Hmm, I'm a little vague on what the correct form would be here, but I'll check.

**Comment by hauke** [comment]
I have seen build warnings in uboot for multiple targets, I support this patch, you can probably also remove the definition of UBOOT_MAKE_FLAGS from multiple packages in package/boot/.
This was added in commit 68139cc0e819b5f654c4f78468049eef035d28f7 
@nbd168  can you comment on this?

**Comment by commodo** [comment]
@hauke 
i'm a little vague on `you can probably also remove the definition of UBOOT_MAKE_FLAGS from multiple packages in package/boot`

1. there seem to be a few makefiles that just clear out the `UBOOT_MAKE_FLAGS` var (mvebu, ar71xx, lantiq)
2. and there are fritz4040 and mxs, which add some extra stuff to this var;

which do you mean to remove ? 1. or 2. ? :)

from my side, any solution is fine, as long as we fix the build warning/err

**Comment by commodo** [comment]
it turns out that `uboot-mvebu` does not build if there is no `openssl-dev` available on the host system;

though the uboot tarball it downloads, is sufficiently new to be able to build against the `tools/libressl` which is in the tree 

added 2 more commits for this

**Comment by hauke** [comment]
I was talking about 1) (mvebu, ar71xx, lantiq)
I think this is done because of this warning.
Nice for finding this problem in the mvebu uboot, I think this is causing the random failure in build bot.

**Comment by commodo** [comment]
ok
i'll try out this changeset with for ar71xx and lantiq

**Comment by commodo** [comment]
clearing he UBOOT_MAKE_FLAGS var seems to be needed  for lantiq and ar71xx
they also have old uboot versions ;
lantiq: 2013.10
ar71xx: 2010.03

in the case of `uboot-lantiq` ; when removing `UBOOT_MAKE_FLAGS :=`, err is:
```
gcc -O2 -I/home/sandu/work/openwrt/staging_dir/host/include -I/home/sandu/work/openwrt/staging_dir/hostpkg/include -I/home/sandu/work/openwrt/staging_dir/target-mips_24kc_musl/host/include -I/home/sandu/work/openwrt/staging_dir/host/include -I/home/sandu/work/openwrt/staging_dir/hostpkg/include -I/home/sandu/work/openwrt/staging_dir/target-mips_24kc_musl/host/include   -o ltq-boot-image.o ltq-boot-image.c -c
ltq-boot-image.c:12:10: fatal error: compiler.h: No such file or directory
 #include <compiler.h>
          ^~~~~~~~~~~~
compilation terminated.
```

in the case of `uboot-ar71xx`, when removing `UBOOT_MAKE_FLAGS :=`, err is:
```
make[5]: Entering directory '/home/sandu/work/openwrt/build_dir/target-mips_24kc_musl/u-boot-nbg460n_550n_550nh/u-boot-2010.03/tools'
gcc -g -O2 -I/home/sandu/work/openwrt/staging_dir/host/include -I/home/sandu/work/openwrt/staging_dir/hostpkg/include -I/home/sandu/work/openwrt/staging_dir/target-mips_24kc_musl/host/include -I/home/sandu/work/openwrt/staging_dir/host/include -I/home/sandu/work/openwrt/staging_dir/hostpkg/include -I/home/sandu/work/openwrt/staging_dir/target-mips_24kc_musl/host/include -c -o crc32.o /home/sandu/work/openwrt/build_dir/target-mips_24kc_musl/u-boot-nbg460n_550n_550nh/u-boot-2010.03/lib_generic/crc32.c
/home/sandu/work/openwrt/build_dir/target-mips_24kc_musl/u-boot-nbg460n_550n_550nh/u-boot-2010.03/lib_generic/crc32.c:12:10: fatal error: common.h: No such file or directory
 #include <common.h>
          ^~~~~~~~~~
compilation terminated.
```

in both cases, re-adding `UBOOT_MAKE_FLAGS :=` fixes the errors

**Comment by hauke** [comment]
Ok then it is ok, this pull request looks good to me.
@nbd168 can you please comment on this.

**Comment by commodo** [comment]
ping @nbd168

**Pull request closed without merging**
