### PR TITLE
kernel: Initial DVB support

### PR DESCRIPTION
**Pull request by miska**
Add support for building some DVB modules. Not everything at the moment, plenty
is unsupported, but the list can grow over the time.

Signed-off-by: Michal Hrusecky <michal.hrusecky@nic.cz>

### CODE REVIEW

**Comment by kofec** [comment]
I like this idea. I always have to add it in kernel menu

**Comment by kofec** [comment]
Hi, I'm testing your solution. And below wireless driver the are two additional artifacts. Is it expected ?
```
  │ ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐ │  
  │ │                                       Block Devices  --->                                                                                   │ │  
  │ │                                       CAN Support  --->                                                                                     │ │  
  │ │                                       Cryptographic API modules  --->                                                                       │ │  
  │ │                                       DVB Support  --->                                                                                     │ │  
  │ │                                       Filesystems  --->                                                                                     │ │  
  │ │                                       FireWire support  --->                                                                                │ │  
  │ │                                       Hardware Monitoring Support  --->                                                                     │ │  
  │ │                                       I2C support  --->                                                                                     │ │  
  │ │                                       Industrial I/O Modules  --->                                                                          │ │  
  │ │                                       Input modules  --->                                                                                   │ │  
  │ │                                       LED modules  --->                                                                                     │ │  
  │ │                                       Libraries  --->                                                                                       │ │  
  │ │                                       Media tuners  --->                                                                                    │ │  
  │ │                                       Native Language Support  --->                                                                         │ │  
  │ │                                       Netfilter Extensions  --->                                                                            │ │  
  │ │                                       Network Devices  --->                                                                                 │ │  
  │ │                                       Network Support  --->                                                                                 │ │  
  │ │                                       Other modules  --->                                                                                   │ │  
  │ │                                       PCMCIA support  ----                                                                                  │ │  
  │ │                                       SPI Support  --->                                                                                     │ │  
  │ │                                       Sound Support  --->                                                                                   │ │  
  │ │                                       USB Support  --->                                                                                     │ │  
  │ │                                       Video Support  --->                                                                                   │ │  
  │ │                                       Virtualization  ----                                                                                  │ │  
  │ │                                       Voice over IP  --->                                                                                   │ │  
  │ │                                       W1 support  --->                                                                                      │ │  
  │ │                                       WPAN 802.15.4 Support  --->                                                                           │ │  
  │ │                                       Wireless Drivers  --->                                                                                │ │  
  │ │                                   < > kmod-tveeprom............................................. VIDEO_TVEEPROM                             │ │  
  │ │                                   < > kmod-v4l2........................................................... v4l2  
```

**Comment by miska** [comment]
Thanks for pointing it out. Fixed and rebased patch.

**Comment by kofec** [comment]
@miska It will be great if we have on Openwrt

**Comment by adrianschmutzler** [comment]
@miska Any interest in moving on with this? Otherwise, we will close it.

**Comment by SvenRoederer** [comment]
I did some work on this branch some time ago to make a BeagoBoneBlack working as dvb-t receiver.

**Comment by adrianschmutzler** [comment]
This is orphaned, so I close it now. Feel free to ask for reopening when there is any progress.

@SvenRoederer Feel free to submit a patch of your own. However, take into account that feedback on/interest in this one was small.

**Pull request closed without merging**
