### PR TITLE
ath79: Fix WAN LED for TP-Link Archer A6/C6 V2 (US)

### PR DESCRIPTION
**Pull request by rodsmar**
This PR fixes bug [FS#2854](https://bugs.openwrt.org/index.php?do=details&task_id=2854).

The amber and green wan led color was inverted in dts file, which ends up leaving the wan led amber when the connection is established, so, switch gpio led number (7 and 8) in qca9563_tplink_archer-c6-v2-us.dts.

_Tip: the /etc/config/system file needs to be regenerated._

### CODE REVIEW

**Comment by adschm** [comment]
Since this recipe is for two devices, please evaluate whether this change is also correct for the A6 v2 (US).

Do you have any data about the C6 V2 (non-US), which has the same setup ...

And please remove one of your two Signed-off-by.

**Comment by rodsmar** [comment]
@adschm i've made changes in PR description and title (added A6 mention).

Since C6 non-us is different in flash size (and i'm not manage any C6 non-us) i left this device out.

But if necessary, I can add it to the commit

**Comment by adschm** [comment]
This still has two Signed-off-by and needs to be squashed into a single proper commit.

However, since the change is small, I'd do it myself if you tell me which of the two Signed-off-by you'd like to keep.

**Comment by rodsmar** [comment]
I can't edit my sign-off for unknown question... can you edit for me?

**Comment by rodsmar** [comment]
na iminência do ramo mestre migrar os dispositivos ath79 para o DSA, irei criar um novo solicitação de mesclagem especificamente para a versão 21.02, que utiliza o swconfig para o ramo ath79.

**Pull request closed without merging**
