### PR TITLE
realtek: Disable boston clock

### PR DESCRIPTION
**Pull request by oliv3r**
We are not on the 'boston' platform so no point in having that clock driver enabled.

The actual fix is probably somewhere in Kconfig land, but lets only fix what directly impacts us here.

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>

### CODE REVIEW

**Comment by oliv3r** [comment]
@svanheule just a little trival patch, should work on 5.10 too, but I'll leave that to you.

**Comment by hauke** [comment]
This option is deactivated in the generic configuration please just remove the setting from the realtek configuration:
````
$ git grep CONFIG_COMMON_CLK_BOSTON
target/linux/ath79/config-5.10:# CONFIG_COMMON_CLK_BOSTON is not set
target/linux/generic/config-5.15:# CONFIG_COMMON_CLK_BOSTON is not set
target/linux/malta/config-5.10:# CONFIG_COMMON_CLK_BOSTON is not set
target/linux/pistachio/config-5.10:# CONFIG_COMMON_CLK_BOSTON is not set
target/linux/ramips/mt7621/config-5.10:# CONFIG_COMMON_CLK_BOSTON is not set
target/linux/realtek/rtl838x/config-5.10:CONFIG_COMMON_CLK_BOSTON=y
target/linux/realtek/rtl838x/config-5.15:CONFIG_COMMON_CLK_BOSTON=y
target/linux/realtek/rtl839x/config-5.10:CONFIG_COMMON_CLK_BOSTON=y
target/linux/realtek/rtl839x/config-5.15:CONFIG_COMMON_CLK_BOSTON=y
target/linux/realtek/rtl930x/config-5.10:CONFIG_COMMON_CLK_BOSTON=y
target/linux/realtek/rtl930x/config-5.15:CONFIG_COMMON_CLK_BOSTON=y
target/linux/realtek/rtl931x/config-5.10:CONFIG_COMMON_CLK_BOSTON=y
target/linux/realtek/rtl931x/config-5.15:CONFIG_COMMON_CLK_BOSTON=y
````

**Comment by oliv3r** [comment]
@hauke thanks, however, for some reason, I often see this one re-appearing in the configs, hence the forced disablement.

**Comment by oliv3r** [comment]
Right, i'll disable it on 5.10, remove it on 5.15 and lets see what happens. BTW, your git-grep solution potentially only shows who actively took care of of it. Could still be that it gets enabled by default, just not committed :)

**Comment by svanheule** [comment]
Remove on 5.15 (since it's in the generic config) and disable on 5.10 is what happens here too when I do `make kernel_oldconfig` after removing the `COMMON_CLK_BOSTON` line.

I don't quite agree with the second paragraph of the commit message though. Since there is nothing like `CONFIG_BOSTON`, this symbol will always be exposed when `CONFIG_MIPS=y` and just needs to be selected as required.

**Comment by oliv3r** [comment]
Removed that second paragraph. I think what happened was that for some reason I got sucked back into the 5.10 kernel, and it started to show up in my diffs, without me noticing 5.10.

So lets hope it stays away this time :)

**Comment by svanheule** [comment]
Thanks!

Merged with commit c9a7c00f809f ("realtek: Disable boston clock")

**Pull request closed without merging**
