### PR TITLE
ramips: specify "firmware" partition format

### PR DESCRIPTION
**Pull request by musashino205**
Specify firmware partition format for ramips devices.

formats in ramips:

- denx,uimage
- tplink,firmware
- seama

### CODE REVIEW

**Comment by mkresin** [comment]
Wouldn't it make sense to apply the change for all ramips boards? From the image build code it should be straight forward to see if the uimage, tp-link and so on splitter is required.

Since it means a lot of work, I'm perfect fine if you only would like to focus on boards you have. Just let me know, I don't want to delay the PR longer than necessary.

**Comment by musashino205** [comment]
> Wouldn't it make sense to apply the change for all ramips boards? 

OK, I'll try it :)

**Comment by musashino205** [comment]
Done.

**Comment by musashino205** [comment]
I could not find any compatible string that can be used in mtdsplit_trx.c ...

And as for MT7621.dts, I am confused because there is no "firmware" partition in the dts and device definition does not exist in image/*.mk.

**Comment by mkresin** [comment]
I had a closer look at the image build code and found the boards using the LZMA and WRGG splitter. I dropped the uImage compatible from the dts files.

I found some boards which have some special header before the uImage header. But I'm quite sure the uImage splitter still work as it worked before. Nevertheless, I added a note to the commit message.

Finally, I mentioned the boards which are using a splitter still without a compatible string in the commit message. Maybe someone else gets motivated to add the compatible to the splitter and dts files.

You can find the result in [my staging tree](https://git.openwrt.org/?p=openwrt/staging/mkresin.git;a=summary). Are you fine with my changes to your patch?

**Comment by mkresin** [comment]
merged, thanks!

**Comment by RussellSenior** [comment]
Fwiw, this seems to have broken the Dlink DIR-860L-B1. As of about November 15, it was showing a seama-fw in dmesg. Changing to compatible = "seama"; fixes it.

**Comment by musashino205** [comment]
@RussellSenior Sorry, it seems that I mistook it as another model.

**Pull request closed without merging**
