### PR TITLE
kernel: bump 5.10 to 5.10.58

### PR DESCRIPTION
**Pull request by rsalvaterra**
No deleted or manually refreshed patches.

Run-tested:
mvebu/cortexa9 (Turris Omnia)
ath79/generic (TL-WDR3600)

Signed-off-by: Rui Salvaterra <rsalvaterra@gmail.com>

### CODE REVIEW

**Comment by ldir-EDB0** [comment]
Nothing exploded on x86_64 on my APU2

**Comment by rmandrad** [comment]
> 
> 
> Nothing exploded on x86_64 on my APU2

nothing either on mvebu/wrt3200acm

**Comment by ldir-EDB0** [comment]
My APU2 is still in one piece ;-)

Just commit it already!

**Comment by rsalvaterra** [comment]
> Just commit it already!

I can't yet, but thanks for the x86-64 testing, as usual! :wink:

**Comment by dangowrt** [comment]
Tested on mediatek/mt7622, pushed to master. Thanks!

**Pull request closed without merging**
