### PR TITLE
kernel: backport generic phylink validate

### PR DESCRIPTION
**Pull request by dangowrt**
Backport generic phylink validate series and make use of it for mtk_eth_soc Ethernet driver as well as mt7530 DSA driver.

**Please help and test-run builds with this commit on *non-MediaTek* platforms**
As this change may potentially affect Ethernet functionality, make sure Ethernet works with all link speeds, flow-control and duplex options, ...

### CODE REVIEW

**Comment by neheb** [comment]
I'll probably test this on my RT1800, which I added support for here: https://github.com/openwrt/openwrt/pull/4470

On an unrelated note, I call the LEDs on the RT1800 white instead of blue. I notice the RT3200 calls them blue. Oversight?

**Comment by dangowrt** [comment]
@neheb The RT3200 actually doesn't have the LEDs populated (except for the white power LED which is always on and white GPIO-controlled Internet LED). On the (otherwise identical) Linksys E8450 port LEDs are populated, and all of them plus the power and Internet LED are blue.

**Comment by neheb** [comment]
right. my point was it's inaccurate to call these blue:

```
config led 'led_wan'
	option name 'WAN'
	option sysfs 'inet:blue'
	option trigger 'none'
	option default '0'

config led
	option name 'Power'
	option sysfs 'power:blue'
	option trigger 'none'
	option default '0'

```

**Comment by neheb** [comment]
you still need testing on mt7621? How are link speeds supposed to be changed?

**Comment by dangowrt** [comment]
@neheb Yes, testing on ramips platforms would still be desirable before pushing this to master. Link speeds should effectively remain the same, however, things like forcing port speeds or auto negotiation, or setting up flow-control may be different as much of it is now handled by the generic phylink validate code instead of (redundantly) being part of the Ethernet drivers.

**Comment by xabolcs** [comment]
Landed as commit aab466f422500842adb62ddb7b1357e2e123ebb2.

**Comment by anomeome** [comment]
Borked on target mvebu(mamba). Device setup does not complete during boot, no lanX - lanY extent.

**Comment by dangowrt** [comment]
Please submit complete kernel boot log for further insights of what the
cause may be.

**Comment by anomeome** [comment]
[bootlog](https://termbin.com/9n61)

**Comment by dangowrt** [comment]
@anomeome Please try if https://github.com/openwrt/openwrt/pull/10584 fixes it.

**Comment by anomeome** [comment]
Yep, resolves issue.

**Comment by dangowrt** [comment]
Thank you for reporting and testing. I've pushed the fix https://github.com/openwrt/openwrt/commit/6c302b900979c3bad2a7764f72f23ccc2d2a33a4

**Pull request closed without merging**
