### PR TITLE
zstd: follow-up minor cleanup

### PR DESCRIPTION
**Pull request by robimarko**
Instead of relying on env variables for setting the ZSTD compression
configuration we can simply do what we do for IB, SDK and the rest and
use tar -I to pass "zstd -T0 --ultra -20" directly.

This makes it rather clear what is being done and allows to drop the
zstd CLI max level override as its usually capped at level 19.

### CODE REVIEW

**Comment by robimarko** [comment]
@Ansuel I would love your opinion

**Comment by Ansuel** [comment]
I would really love to know the difference between using --zstd and -I

Needs to investigate a bit

**Comment by robimarko** [comment]
> I would really love to know the difference between using --zstd and -I
> 
> Needs to investigate a bit

Using `tar -I zstd -T0 --ultra -20` is the same as calling `zstd -T0 --ultra -20`, just `--zstd` is nothing more than a shortcut that just calls zstd without any arguments and then you have to rely on env variables.

We are calling tar -I in this PR as well, this is normal as tar -I is designed so you can pass arguments to the compressor
https://github.com/openwrt/openwrt/pull/14619

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
From the man page:

```
       ○   --ultra: unlocks high compression levels 20+ (maximum 22), using a lot more memory. Note that decompression will also require more memory  when
           using these levels.

```

Anyone do comparisons between 20 and 22?

**Review by f00b4r0 — APPROVED** [review]

**Comment by f00b4r0** [comment]
tested working on top of d997477

**Comment by robimarko** [comment]
> Anyone do comparisons between 20 and 22?

You can find a lot of Arch test results:
https://lists.archlinux.org/pipermail/arch-dev-public/2019-March/029542.html

Level over 20 dont seem worth it

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
