### PR TITLE
rockchip: add support for Radxa ROCK Pi E

### PR DESCRIPTION
**Pull request by jayanta525**
ROCK Pi E is an RK3328 Single Board Computer by [Radxa](https://wiki.radxa.com/RockpiE). It features dual Ethernet connectivity (100M and 1000M) and USB3.0 HOST.

Specification:
- CPU: Rockchip RK3328 64-bit Quad-core
- RAM: DDR3 256MB ~ 2GB
- Network:
    1 x 10/100/1000M Ethernet
    1 x 10/100M Ethernet
- Storage:
    1 x MicroSD Slot
    1 x eMMC Module Slot
- USB Host/OTG:
    1 x USB3.0 Type A HOST
    1 x USB2.0 OTG (40-pin pin-header)
- Wireless:
    RTL8723DU/RTL8821CU
- Debug Serial:
    1500000 baud at UART2 (40-pin pin-header)
- Power Supply:
    Type-C 5V
    Optionally PoE

Installation:
- Write image to SD Card or EMMC with dd
- Boot ROCK Pi E from the SD Card

### CODE REVIEW

**Comment by jayanta525** [comment]
cc @hauke

**Comment by hauke** [comment]
Some documents says this device also supports wifi. Did you try wifi? Is there a Wifi chip on your board and how is it connected?

If the board normally supports wifi and it does not work in OpenWrt please mention this in the commit message. If you need some extra OpenWrt package to make the wifi work, please add it to the default packages.

**Comment by jayanta525** [comment]
@hauke , yes, some variants (SKUs) have the module onboard (wifi + bt). There are two variants of wireless module - rtl8723du and rtl8821cu. The modules are connected via USB. 
USB is enabled in the Linux DTS.
```
&usb_host0_ehci {
	status = "okay";
};
```

My model didn't have the wifi module, so I couldn't look into the wifi part. However, rtl8723du and rtl8821cu drivers seems to be available with the newer Linux kernel v6.2 and above.

rtl8723du - https://github.com/torvalds/linux/commit/87caeef032fc3921bc866ad7becb6ed51aa8b27b
rtl8721cu - https://github.com/torvalds/linux/commit/aff5ffd718de23cb8603f2e229204670e2644334

@hauke  How do you suggest I proceed with this pull request?

**Comment by hauke** [comment]
Thanks for the clarification. This looks fine now. If only some of the SKUs contain the wifi chip and the driver is not yet in OpenWrt it is not needed in the default packages. Thanks for adding the comment to the commit description.

**Comment by jayanta525** [comment]
@hauke thanks for the merge.

**Pull request merged**
