### PR TITLE
package/libs/libevent: Update to 2.1.9-beta

### PR DESCRIPTION
**Pull request by diizzyy**
Update libevent to 2.1.9-beta
Use CMake instead GNU Autotools
Add patch for OpenSSL linking to avoid dependency for libevent2 pkg

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile and runtime tested on: octeon, EdgeRouter Lite, OpenWrt master

**Comment by diizzyy** [comment]
I know that we usually don't import beta software but this library includes many bugfixes and enhancements.  This is pretty much expected to be the final release (https://github.com/libevent/libevent/releases/tag/release-2.1.9-beta) so it would be nice to be able to iron out potential issues before branching 19.XX.

**Comment by neheb** [comment]
A few comments:

The normal way to add fPIC for CMake projects is
```
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
```

LTO is useless here. A short test:
On:
```
-rw-r--r-- 1 mangix mangix 92142 Feb 23 14:49 libevent2-7_2.1.9-beta-1_mipsel_24kc.ipk
-rw-r--r-- 1 mangix mangix 54430 Feb 23 14:49 libevent2-core7_2.1.9-beta-1_mipsel_24kc.ipk
-rw-r--r-- 1 mangix mangix 43663 Feb 23 14:49 libevent2-extra7_2.1.9-beta-1_mipsel_24kc.ipk
-rw-r--r-- 1 mangix mangix  8987 Feb 23 14:49 libevent2-openssl7_2.1.9-beta-1_mipsel_24kc.ipk
-rw-r--r-- 1 mangix mangix  3458 Feb 23 14:49 libevent2-pthreads7_2.1.9-beta-1_mipsel_24kc.ipk
```
Off:
```
-rw-r--r-- 1 mangix mangix 92092 Feb 23 14:45 libevent2-7_2.1.9-beta-1_mipsel_24kc.ipk
-rw-r--r-- 1 mangix mangix 54300 Feb 23 14:45 libevent2-core7_2.1.9-beta-1_mipsel_24kc.ipk
-rw-r--r-- 1 mangix mangix 43364 Feb 23 14:45 libevent2-extra7_2.1.9-beta-1_mipsel_24kc.ipk
-rw-r--r-- 1 mangix mangix  8962 Feb 23 14:45 libevent2-openssl7_2.1.9-beta-1_mipsel_24kc.ipk
-rw-r--r-- 1 mangix mangix  3459 Feb 23 14:45 libevent2-pthreads7_2.1.9-beta-1_mipsel_24kc.ipk
```

I recommend adding
```
TARGET_LDFLAGS += -Wl,--gc-sections -Wl,--as-needed
```
instead. Those options seem to make a positive difference.

**Comment by diizzyy** [comment]
Regarding the CMake option, it's not the same 
https://github.com/openwrt/openwrt/blob/master/rules.mk#L79
LTO makes a difference on octeon and I'm not sure if those switches will cause issues. Have you run tested?

**Comment by neheb** [comment]
I submitted this on the mailing list: http://lists.infradead.org/pipermail/openwrt-devel/2019-February/015904.html

I've tested it on ramips and ath79. Both work fine. -Wl,--as-needed I've tested on different projects. Also works fine. I avoided it in the patch as it seems to make a difference in the other libevent2 libraries (not the main one).

**Comment by diizzyy** [comment]
@neheb 
This works fine on octeon, can you give it a try?

**Comment by neheb** [comment]
Seems to work fine with transmission.

-flto still seems to give bigger sizes. 86850 vs. 86736. I also tried fPIC vs. fpic. No difference.

**Comment by neheb** [comment]
Just ran it with CMAKE_VERBOSE_MAKE. -fPIC is included.

```
-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/mangix/devstuff/openwrt/build_dir/target-mipsel_24kc_musl/libevent-2.1.9-beta:libevent-2.1.9-beta -Wformat -Werror=format-security -Wl,-z,now -Wl,-z,relro -ffunction-sections -fdata-sections -Wall -Wextra -Wno-unused-parameter -Wstrict-aliasing -fno-strict-aliasing -Winit-self -Wmissing-field-initializers -Wdeclaration-after-statement -Waddress -Wno-unused-function -Wnormalized=id -Woverride-init -Wlogical-op -DNDEBUG -fPIC   -fvisibility=hidden -o CMakeFiles/event_shared.dir/signal.c.o   -c /home/mangix/devstuff/openwrt/build_dir/target-mipsel_24kc_musl/libevent-2.1.9-beta/signal.c
```

**Comment by neheb** [comment]
This gave me the lowest size:

```
diff --git a/package/libs/libevent2/Makefile b/package/libs/libevent2/Makefile
index 0e68d094f4..4d81312a73 100644
--- a/package/libs/libevent2/Makefile
+++ b/package/libs/libevent2/Makefile
@@ -106,8 +106,8 @@ define Package/libevent2-pthreads/description
 	threading & locking.
 endef
 
-TARGET_CFLAGS += $(FPIC) -ffunction-sections -fdata-sections -flto
-TARGET_LDFLAGS += -Wl,--gc-sections,--as-needed -flto
+TARGET_CFLAGS +=-fdata-sections
+TARGET_LDFLAGS += -Wl,--gc-sections,--as-needed
 
 CMAKE_OPTIONS += \
 	-DEVENT__DISABLE_BENCHMARK:BOOL=ON \
@@ -116,7 +116,8 @@ CMAKE_OPTIONS += \
 	-DEVENT__DISABLE_SAMPLES:BOOL=ON \
 	$(if $(CONFIG_PACKAGE_libevent2-openssl),-DEVENT__DISABLE_OPENSSL:BOOL=OFF,-DEVENT__DISABLE_OPENSSL:BOOL=ON) \
 	$(if $(CONFIG_PACKAGE_libevent2-pthreads),-DEVENT__DISABLE_THREAD_SUPPORT:BOOL=OFF,-DEVENT__DISABLE_THREAD_SUPPORT:BOOL=ON) \
-	-DEVENT__DISABLE_TESTS:BOOL=ON
+	-DEVENT__DISABLE_TESTS:BOOL=ON \
+	-DEVENT__ENABLE_GCC_FUNCTION_SECTIONS=ON
 
 define Build/InstallDev
 	$(INSTALL_DIR) $(1)/usr/include
```

**Comment by diizzyy** [comment]
Size will differ slightly per arch so the current commit is fine as it is. I also prefer to use toolchain logic as much as possible. Thanks for testing :-)

**Comment by ynezz** [comment]
> Update libevent to 2.1.9-beta

Maybe you should add to the commit information, why we want to switch to beta release.

**Comment by diizzyy** [comment]
Closing this for now

**Comment by dengqf6** [comment]
2.1.10-stable is available @diizzyy

**Comment by diizzyy** [comment]
@dengqf6 
https://github.com/openwrt/openwrt/pull/2135

**Pull request closed without merging**
