### PR TITLE
yafut: update PKG_MIRROR_HASH

### PR DESCRIPTION
**Pull request by msandber**
github job: Build Kernel / Build all affected Kernels / Build Kernel with external toolchain (ramips, mt7621) / Check packages for ramips/mt7621 (push) Failing after 3m. Culprit package/utils/yafut/Makefile

Local log:
Hash of the local file yafut-2023.03.31~16435e89.tar.xz does not match (file: 281da69ba77c1b7556b76f8ee907e012dc9c6b15916bf5e2027980014b25d401, requested: 6eece622d1df99ffee1a18d162d36292f32bf2d5e514663a6b61fd82c2ecbcba)
 - deleting download.

Executed "make package/utils/yafut/check V=s FIXUP=1"

### CODE REVIEW

**Comment by msandber** [comment]
Friendly ping @Ansuel for updating the hash last.

**Comment by Ansuel** [comment]
The hash randomly changing is nothing to take lightly and must be investigated first.

**Comment by robimarko** [comment]
@Ansuel Its all because of:
https://github.com/openwrt/openwrt/commit/e8725a932e16eaf6ec51add8c084d959cbe32ff2

Also related:
https://github.com/openwrt/openwrt/pull/14960

**Comment by Ansuel** [comment]
@robimarko ugh... but why the hash change? Do we change something in the tar file related to version?

**Comment by robimarko** [comment]
@Ansuel No idea, look at the linked PR as it seems internals have changed and so the hash changed and now its a royal pain in the ass

**Pull request closed without merging**
