### PR TITLE
23.05 - Improve fan behaviour for GL.iNet MT3000 router

### PR DESCRIPTION
**Pull request by lukasz1992**
- double the number of cooling-levels one can use
- improve the fan behaviour:
  - turn on fan on lower temperatures, but make it quiet
  - increase RPMs faster on higher temperatures
  - reduce probability of constant start-stop actions

This is an improvement for all MT7981 devices with pwm fan.
This is cloned version of https://github.com/openwrt/openwrt/pull/13264 for 23.05 branch.

### CODE REVIEW

**Comment by herbetom** [comment]
To get something in a release branch like `openwrt-23.05` it's first necessary to be merged into `main`. After that a backport is possible. A backport is created with the `git cherry-pick -x COMMIT_ID_IN_MAIN` command.

I would suggest closing this for now and reopening it once you've got it merged into `main`.

**Comment by lukasz1992** [comment]
okay

**Comment by csharper2005** [comment]
@lukasz1992 

I'm testing a similar hardware (mt7981 + usb) and noticed high CPU Load average:
`Load average: 1.00 1.00 1.00`

After rmmod `xhci_mtk_hcd`:
`Load average: 0.00 0.00 0.00`

Have you noticed something like this on your GL.iNet MT3000 router?

**Comment by lukasz1992** [comment]
> @lukasz1992
> 
> I'm testing a similar hardware (mt7981 + usb) and noticed high CPU Load average: `Load average: 1.00 1.00 1.00`
> 
> After rmmod `xhci_mtk_hcd`: `Load average: 0.00 0.00 0.00`
> 
> Have you noticed something like this on your GL.iNet MT3000 router?

No. Just checked:
```
root@router:~# uptime
 18:13:50 up 1 day, 22 min,  load average: 0.00, 0.00, 0.00
root@router:~# lsmod | grep xhci
usb_common             12288  4 xhci_plat_hcd,xhci_mtk_hcd,xhci_hcd,usbcore
usbcore               180224  5 usb_storage,xhci_plat_hcd,xhci_pci,xhci_mtk_hcd,xhci_hcd
xhci_hcd              131072  3 xhci_plat_hcd,xhci_pci,xhci_mtk_hcd
xhci_mtk_hcd           20480  0
xhci_pci               16384  0
xhci_plat_hcd          12288  0
```
OS: OpenWRT 23.05.0

**Pull request closed without merging**
