### PR TITLE
xdp-tools: import patches fixing cross platform compiling

### PR DESCRIPTION
**Pull request by PolynomialDivision**
xdp-tools has issues with 64bit data types. The patches are fixing those
issues.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
ping @dangowrt

**Comment by neheb** [comment]
Those time_t changes are wrong. It’ll warn on platforms that run 32-bit time_t. Typical way to fix this is with a cast.

**Comment by PolynomialDivision** [comment]
> Those time_t changes are wrong. It’ll warn on platforms that run 32-bit time_t. Typical way to fix this is with a cast.

Are u sure? For me it fixes everything? Can you give me a platform that should not work?

**Comment by neheb** [comment]
x86 or ARM 32-bit with glibc.

**Comment by PolynomialDivision** [comment]
> x86 or ARM 32-bit with glibc.

How would you cast? Everything to long unsigned?

**Comment by neheb** [comment]
time_t is signed. I'd cast to long long.

**Comment by PolynomialDivision** [comment]
@tohojo What do you think?

**Comment by tohojo** [comment]
See my comment on the xdp-tools PR; I'm fine with just casting :)

**Pull request closed without merging**
