### PR TITLE
x86: kernel: Compile-in MPT-SAS drivers

### PR DESCRIPTION
**Pull request by mcarroll76**
This single line kernel config option compiles in the MPT-SAS drivers which are required under some set-ups to mount the rootfs. It's only a small addition to the kernel size, and without it OpenWrt fails to boot on the VMware VPSs offered by providers such as IONOS, so I think it belongs in the default config. Restricted to the x86/64 target, as it's unlikely to be applicable elsewhere.

As this issue prevents booting on certain platforms and the fix is a minor change, it would be nice if we could get this merged and cherry-picked back to the 21.02 branch before final release.

### CODE REVIEW

**Review by CodeFetch — CHANGES_REQUESTED** [review]
Please clean up/squash your commits and change the commit title and description to something like:
```
x86: kernel: enable Fusion-MPT SAS driver

Compile in MPT SAS driver required to mount rootfs on some VMWare
systems (e.g. required for 1&1 IONOS).
```

As the image is not bootable otherwise, I tend to agree, but
there are also a lot of network drivers missing for generic
x86 systems which we need to include in our firmware.
I think we should rethink policies here...

Like:
```
sky2
r8169
forcedeth
8139too
```

**Comment by mcarroll76** [comment]
Commits squashed and amended as requested.

I tend to agree that perhaps more network drivers should be included, but they can at least be built as kmod- packages that may be incorporated into custom images using the image builder. With a driver like this that is required to mount the rootfs, you can't even do that, as the system doesn't reach the point where it has a mounted filesystem to load modules from. The only way is to build the full OpenWrt toolchain from scratch to compile a custom kernel with the required drivers. This then creates the lingering problem of kernel signature mismatch if you later wish to install any kmod- packages.

**Comment by CodeFetch** [comment]
@mcarroll76 Yes, you are right. It's not needed for booting and the image builder is an option here... Still OpenWrt is not really use-able as a generic x86 system which I think should be discussed policy-wise in general.

**Review by CodeFetch — APPROVED** [review]

**Comment by adschm** [comment]
This is lacking a Signed-off-by.

**Comment by CodeFetch** [comment]
Indeed. It would be nice if we could add a Github CI check for that. It's really annoying... While I wonder why we still need this Signed-off-by-thing as OpenWrt uses git now...

**Comment by mcarroll76** [comment]
Sign-off added.

**Comment by blocktrron** [comment]
Looks good, but SoB has to match author

```
From 561ba57505cc2be8c157104a668d081cffc11a1e Mon Sep 17 00:00:00 2001
From: Mark Carroll <github@markcarroll.co.uk>
Date: Sat, 8 May 2021 11:42:50 +0000
Subject: [PATCH] x86: kernel: enable Fusion-MPT SAS driver

Compile in MPT SAS driver required to mount rootfs on some VMWare
systems (e.g. required for 1&1 IONOS).

Signed-off-by: Mark Carroll <git@markcarroll.net>
```

**Comment by mcarroll76** [comment]
That's because I foolishly started this PR using the github web interface. Fixed now.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master.

**Comment by bobafetthotmail** [comment]
> Please clean up/squash your commits and change the commit title and description to something like:
> 
> ```
> x86: kernel: enable Fusion-MPT SAS driver
> 
> Compile in MPT SAS driver required to mount rootfs on some VMWare
> systems (e.g. required for 1&1 IONOS).
> ```
> 
> As the image is not bootable otherwise, I tend to agree, but
> there are also a lot of network drivers missing for generic
> x86 systems which we need to include in our firmware.
> I think we should rethink policies here...
> 
> Like:
> 
> ```
> sky2
> r8169
> forcedeth
> 8139too
> ```

Network drivers are not built in but shipped as packages in default image, since they are not critical for booting. This way someone that wants to make a slimmed down image can remove them from his config or when assembling an image with ImageBuilder.

A few of those you mention are included already as the "informal policy" is that generic x86 images should have drivers for most common ethernet controllers so people can do first configuration through that. See the files in this folder, default packages for the four subtargets of x86 are defined here https://github.com/openwrt/openwrt/tree/master/target/linux/x86/image

If you think some should be added to the list, feel free to open a PR.

**Pull request closed without merging**
