### PR TITLE
ipq806x: define kernel crash log ramoops/pstore facility and use it for R7800 and XR500

### PR DESCRIPTION
**Pull request by hnyman**
Modify the ipq806x kernel config to support logging kernel crashes to pstore files 'ramoops' into RAM in /sys/fs/pstore
The crash log files survive a warm reboot, but not a cold reboot.
Enabling the feature requires adding a reserved-memory "ramoops" definition to the device DTS.
If no definition has been made in DTS, no crash log is stored for the device.

Define the kernel crash log storage ramoops/pstore feature for R7800 and its sister XR500.
Run-tested with R7800.

I have provided this for a few weeks on my R7800 community build, so there already has been somewhat wider user testing.

Similar ramoops feature has so far been enabled in OpenWrt for mt7622/E8450.

------

Even when there are the kernel config change, if there is no DTS definitions, no items are shown in the logs and no crash log files are stored. So, the kernel config change should be harmless for devices without a DTS definition.

```
Test without DTS definition:

 OpenWrt SNAPSHOT, r18776-09f383465e
 -----------------------------------------------------
root@router1:~# logread | grep -i -E "pstore|ramo"
root@router1:~#

ramoops defined in DTS:

 OpenWrt SNAPSHOT, r18770-46e0eeb760
 -----------------------------------------------------
root@router1:~# logread | grep -i -E "pstore|ramo"
Mon Feb  7 19:41:20 2022 kern.info kernel: [    0.023058] pstore: Registered ramoops as persistent store backend
Mon Feb  7 19:41:20 2022 kern.info kernel: [    0.023084] ramoops: using 0x40000@0x42100000, ecc: 0
Mon Feb  7 19:41:20 2022 kern.info kernel: [    2.865438] pstore: Using crash dump compression: deflate
```

Example of manually triggered crash in the pstore files after a reboot:
```
root@router1:~# cat /sys/fs/pstore/dmesg-ramoops-0
Panic#1 Part1
...
<6>[88071.709198] sysrq: Trigger a crash
<0>[88071.709238] Kernel panic - not syncing: sysrq triggered crash
<2>[88071.711513] CPU0: stopping
<4>[88071.717323] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 5.10.96 #0
<4>[88071.719920] Hardware name: Generic DT based system
<4>[88071.726108] [<c030e32c>] (unwind_backtrace) from [<c030a1ac>] (show_stack+0x14/0x20)
<4>[88071.730701] [<c030a1ac>] (show_stack) from [<c062ee08>] (dump_stack+0x94/0xa8)
<4>[88071.738597] [<c062ee08>] (dump_stack) from [<c030d050>] (do_handle_IPI+0x140/0x184)
<4>[88071.745627] [<c030d050>] (do_handle_IPI) from [<c030d0b0>] (ipi_handler+0x1c/0x2c)
<4>[88071.753180] [<c030d0b0>] (ipi_handler) from [<c037115c>] (__handle_domain_irq+0x90/0xf4)
<4>[88071.760820] [<c037115c>] (__handle_domain_irq) from [<c0649160>] (gic_handle_irq+0x90/0xb8)
<4>[88071.769068] [<c0649160>] (gic_handle_irq) from [<c0300b0c>] (__irq_svc+0x6c/0x90)
<4>[88071.777130] Exception stack(0xc0d01ee0 to 0xc0d01f28)
<4>[88071.784785] 1ee0: 00000000 00005019 1cd4b000 dd991cc0 00000000 c6b8fc60 c1c7a840 00000000
<4>[88071.789824] 1f00: dd990fb0 00005019 00000000 00005019 f01ffe60 c0d01f30 c07b613c c07b615c
<4>[88071.797967] 1f20: 60000013 ffffffff
<4>[88071.806136] [<c0300b0c>] (__irq_svc) from [<c07b615c>] (cpuidle_enter_state+0x180/0x380)
<4>[88071.809433] [<c07b615c>] (cpuidle_enter_state) from [<c07b63ac>] (cpuidle_enter+0x3c/0x5c)
<4>[88071.817765] [<c07b63ac>] (cpuidle_enter) from [<c034dfb0>] (do_idle+0x208/0x2a4)
<4>[88071.825833] [<c034dfb0>] (do_idle) from [<c034e308>] (cpu_startup_entry+0x1c/0x20)
<4>[88071.833396] [<c034e308>] (cpu_startup_entry) from [<c0c00eac>] (start_kernel+0x538/0x548)
```

Real-life example:
https://forum.openwrt.org/t/netgear-r7800-exploration-ipq8065-qca9984/285/2915

### CODE REVIEW

**Comment by chunkeey** [comment]
I've been using mtdoops as it is available as a packaged kmod by openwrt.
https://github.com/openwrt/openwrt/blob/master/package/kernel/linux/modules/other.mk#L743-L754

Looking at the doc:
https://www.kernel.org/doc/html/latest/admin-guide/ramoops.html

It also lists the possibility of setting up ramoops through the kernel parameters through the bootargs (i.e. from uboot,
so this can be done in a pinch without editing the DTS before testing).

> Similar ramoops feature has so far been enabled in OpenWrt for mt7622/E8450.

Found it, it's from @dangowrt 

e1adb1fa39dd5ef97280ad1b2bb9e8ff4c43674f 
 



Note of warning: 

I recently broke the ipq806x target with the nvmem-calibration patches. The TP-Link VR2600v went
over the alloted 3072K Kernel size... and it's still not fixed completely.

In the process, I looked around and I noticed that the Linksys EA7500 and EA8500 are dangerously
close to their 3072K kernel size limit as well. On the current (as in the snapshot image I downloaded just now), the
kernel size is 3144756 bytes. This is 972 bytes short of the limit. I don't know if the addition of the PS_STORE to
the config-5.10 image would cause issues for these devices. A safer bet would be to package PSTORE and CONFIG_PSTORE_RAM (ramoops itself) as a modules?

The downside of this is that the "oops" needs to happen after the module is loaded. So to catch early panics,
people will have to enable the feature through kernel_oldconfig / kernel_menuconfig which is going to be a pain.

**Comment by ynezz** [comment]
> A safer bet would be to package PSTORE and CONFIG_PSTORE_RAM (ramoops itself) as a modules?

+1 as it's more generic, less bloat in the kernel

> The downside of this is that the "oops" needs to happen after the module is loaded. So to catch early panics,
people will have to enable the feature through kernel_oldconfig / kernel_menuconfig which is going to be a pain.

This usually means device in boot loop, so you can only recover that information over serial console and you don't need this feature anyway.

**Comment by hnyman** [comment]
> Have you tried ramoops when using the kernel option CONFIG_KERNEL_KALLSYMS=n?

Works also that way, but does not solve the function names, naturally. 
So, this would really work in the development snapshots, but not be that beneficial in a release, stripped from kernel symbols.

```
 OpenWrt SNAPSHOT, r18779-64125ed1d0
 -----------------------------------------------------
root@router1:~# logread | grep -i -E "pstore|ramo"
Wed Feb  9 21:09:58 2022 kern.info kernel: [    0.022901] pstore: Registered ramoops as persistent store backend
Wed Feb  9 21:09:58 2022 kern.info kernel: [    0.022924] ramoops: using 0x40000@0x42100000, ecc: 0
Wed Feb  9 21:09:58 2022 kern.info kernel: [    2.847042] pstore: Using crash dump compression: deflate
root@router1:~# cat /sys/fs/pstore/dmesg-ramoops-0
Panic#1 Part1
<6>[    0.671559] pci 0001:00:00.0:   bridge window [mem 0x2e000000-0x2e1fffff]
<7>[    0.671756] pcieport 0001:00:00.0: assign IRQ: got 45
...
<6>[  131.099967] br-lan: port 3(wlan0) entered forwarding state
<6>[  170.997452] sysrq: Trigger a crash
<0>[  170.997488] Kernel panic - not syncing: sysrq triggered crash
<2>[  170.999769] CPU0: stopping
<4>[  171.005576] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 5.10.96 #0
<4>[  171.008172] Hardware name: Generic DT based system
<4>[  171.014344] Function entered at [<c030e24c>] from [<c030a0b8>]
<4>[  171.018938] Function entered at [<c030a0b8>] from [<c062c648>]
<4>[  171.024756] Function entered at [<c062c648>] from [<c030cf70>]
<4>[  171.030572] Function entered at [<c030cf70>] from [<c030cfd0>]
<4>[  171.036386] Function entered at [<c030cfd0>] from [<c037107c>]
<4>[  171.042203] Function entered at [<c037107c>] from [<c064696c>]
<4>[  171.048018] Function entered at [<c064696c>] from [<c0300b0c>]
<4>[  171.053836] Exception stack(0xc0c01ee0 to 0xc0c01f28)
<4>[  171.059671] 1ee0: 00000000 00000027 1ce4b000 dd991cc0 00000000 d041a080 c187a840 00000000
<4>[  171.064796] 1f00: dd990fb0 00000027 00000000 00000027 00041780 c0c01f30 c07b394c c07b396c
<4>[  171.072938] 1f20: 60000013 ffffffff
...
```

**Comment by hnyman** [comment]
#5057 shows the suggested kmod approach

**Comment by remittor** [comment]
> Works also that way, but does not solve the function names, naturally.

So you need to create a kernel module that would contain full debug information.
And also patch the kernel, so that in case of a panic, the necessary information would be taken from this kernel module.
It's just an idea.....

**Comment by ynezz** [comment]
>  So, this would really work in the development snapshots, but not be that beneficial in a release, stripped from kernel symbols.

It's possible to [download the debug symbols](https://downloads.openwrt.org/releases/21.02.1/targets/x86/64/kernel-debug.tar.zst), it's separate file and then it's possible to resolve it manually.

**Comment by hnyman** [comment]
This has been superseded by #5057 that got merged today.

Note that with the #5057 approach you need to select kmod-ramoops for the build, or install it later with opkg.  Just having the DTS definition is not enough,

**Pull request closed without merging**
