### PR TITLE
ramips: set default-trigger of wlan led in dts for rt* devices

### PR DESCRIPTION
**Pull request by yangfl**
Signed-off-by: David Yang <mmyangfl@gmail.com>

### CODE REVIEW

**Comment by aparcar** [comment]
Hi, thanks for your contribution!

Please read through [the patch submitting guidelines](https://openwrt.org/submitting-patches). Your patch patch has some formal issues.

Most commonly are the following:
* Prefix the commit subject with the affected *area*, find that area by looking at `git log <modified_file>`
* Add a commit message describing why this patch was required
* Add a Signed-of-by line containing your real name

**Comment by yangfl** [comment]
so my question is: is this change feasible for other rt305x devices?

**Comment by adschm** [comment]
> so my question is: is this change feasible for other rt305x devices?

Yes, if you can test it on these devices?

Have you checked that the label-mac-device you specify actually produces the correct address as printed on the label?

**Comment by adschm** [comment]
And please split this into two _commits_, one for the WiFi changes and one for the label MAC address ...

**Comment by yangfl** [comment]
> Yes, if you can test it on these devices?

Clearly I don't have 'these' devices, only that device.

**Comment by adschm** [comment]
> > Yes, if you can test it on these devices?
> 
> Clearly I don't have 'these' devices, only that device.

Then you won't be able to verify the label MAC address, so you can't set it on them.

**Comment by yangfl** [comment]
but led default-trigger?

**Comment by adschm** [comment]
Still not split ...

**Comment by adschm** [comment]
> Have you checked that the label-mac-device you specify actually produces the correct address as printed on the label?

And still no answer on this question either ...

**Comment by adschm** [comment]
Missing commit message.

What happened to the label-mac-device?

**Comment by yangfl** [comment]
Dropped label-mac-device changes.

**Comment by adschm** [comment]
> Dropped label-mac-device changes.

Why?

**Comment by adschm** [comment]
If you keep me/us speculating why you do thing, you will never get your stuff merged.

**Comment by yangfl** [comment]
> Why?

I think it's better to leave that change to another pr, and, why you always focus on those trivial thing?

> If you keep me/us speculating why you do thing, you will never get your stuff merged.

Please don't say 'do that or that', but 'do that, since that, like that'. My idea is everyone who read the commit title is clearly informed what this patch does. If you want me to put the background motivation into the commit message, I could say

> Set default-trigger of wlan led in dts for rt* devices, since it make them neater.

That's really my motivation just like fixing typo somewhere. Is that ok?

**Comment by adschm** [comment]
> I think it's better to leave that change to another pr, and, why you always focus on those trivial thing?

What's trivial here? Is there another PR setting this address now I'm not aware of?

> Please don't say 'do that or that', but 'do that, since that, like that'. My idea is everyone who read the commit title is clearly informed what this patch does. If you want me to put the background motivation into the commit message, I could say
>
> > Set default-trigger of wlan led in dts for rt* devices, since it make them neater.
>
> That's really my motivation just like fixing typo somewhere. Is that ok?

But this isn't like a typo, this is a functional change.

**Comment by yangfl** [comment]
open another PR later since I've got a bunch of PRs to work on.
If I got misinformed and they are functional differences, then just close this pr since there will be nothing changed but code quality even if it gets merged, in my opinion.

**Pull request closed without merging**
