### PR TITLE
ath79: register ttyATH1 as Linux/OpenWrt console on ELECOM WAB-I1750-PS

### PR DESCRIPTION
**Pull request by musashino205**
This patch series registers ttyATH1 ("SERIAL" port) on ELECOM WAB-I1750-PS as Linux/OpenWrt console for debugging/recoverying/configuration by users.

cdb4515b4b7d4ac0cb9730c43e8af4d38a632427 depends on https://github.com/openwrt/procd/pull/7.

The same changes should also be applicable to devolo WiFi Pro 1750e that has the similar PCB.

### CODE REVIEW

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by musashino205** [comment]
@robimarko Thanks, but
> cdb4515b4b7d4ac0cb9730c43e8af4d38a632427 depends on https://github.com/openwrt/procd/pull/7.

...

**Comment by robimarko** [comment]
> @robimarko Thanks, but
> 
> > [cdb4515](https://github.com/openwrt/openwrt/commit/cdb4515b4b7d4ac0cb9730c43e8af4d38a632427) depends on [openwrt/procd#7](https://github.com/openwrt/procd/pull/7).
> 
> ...

Sorry, missed that completely, merged the procd changes as they look OK to me

**Comment by musashino205** [comment]
Thank you for your work ;)

**Pull request merged**
