### PR TITLE
ramips: fix the bootup panic on Gehua-ghl-r-001

### PR DESCRIPTION
**Pull request by securecrt**
the 4b-opcodes feature caused bootup panic on some of the
Gehua-ghl-r-001 (HW.VER Q12-V0.4-2018/03/23)

999-fix-m25p-shutdown.patch is the new fix for the soft reboot issue

Signed-off-by: securecrt2008 <securecrt2008@gmail.com>
[bootlog.txt](https://github.com/openwrt/openwrt/files/3708193/bootlog.txt)

### CODE REVIEW

**Comment by securecrt** [comment]
below message dumped from UART with the latest snapshot

[    3.260440] libphy: mdio: probed
[    4.666528] mtk_soc_eth 1e100000.ethernet: loaded mt7530 driver
[    4.679163] mtk_soc_eth 1e100000.ethernet eth0: mediatek frame engine at 0xbe100000, irq 21
[    4.698406] NET: Registered protocol family 10
[    4.708674] Segment Routing with IPv6
[    4.716077] NET: Registered protocol family 17
[    4.724982] 8021q: 802.1Q VLAN Support v1.8
[    4.736088] hctosys: unable to open rtc device (rtc0)
[    4.746981] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    4.761885] Please append a correct "root=" boot option; here are the available partitions:
[    4.778521] 1f00             192 mtdblock0
[    4.778527]  (driver?)
[    4.791527] 1f01              64 mtdblock1
[    4.791532]  (driver?)
[    4.804545] 1f02              64 mtdblock2
[    4.804550]  (driver?)
[    4.817549] 1f03           32448 mtdblock3
[    4.817554]  (driver?)
[    4.830552] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    4.848681] Rebooting in 1 seconds..

**Comment by securecrt** [comment]
tested on my another gehua-ghl-r-001 router 
no bootup issue with my changes.

**Comment by bobafetthotmail** [comment]
you need to use a real name in he Signed Off By line. "securecrt2008" is a nickname, not a real name.

**Comment by securecrt** [comment]
@bobafetthotmail I have corrected the Signed Off name.

**Comment by ptpt52** [comment]
dropping `303-spi-nor-enable-4B-opcodes-for-mx66l51235l.patch` may not be correct.
I prefer change spi define in dts
see my patches:
https://github.com/x-wrt/x-wrt/commit/2cda5b61c40c40b37d3deb01f01c15882f997f9b

and

https://github.com/x-wrt/x-wrt/commit/2900b629cc0fb8fb85391c9d02aa1edc8bc6b633

**Comment by securecrt** [comment]
@ptpt52 
did you test your patch on the gehua-ghl-r-001 device?

**Comment by securecrt** [comment]
compiled the latest trunk + the latest patch , everything looks good. 

@ptpt52  I have changed the dts file as your recommendation do you have other suggestions ? 

[    0.000000] Linux version 4.14.148 (securecrt@ubuntulnx) (gcc version 8.3.0 (OpenWrt GCC 8.3.0 r11218-2c60de0e3f)) #0 SMP Mon Oct 14 10:36:02 2019
[    0.000000] SoC Type: MediaTek MT7621 ver:1 eco:3
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 0001992f (MIPS 1004Kc)
[    0.000000] MIPS: machine is GeHua GHL-R-001
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 1c000000 @ 00000000 (usable)
[    0.000000]  memory: 04000000 @ 20000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] VPE topology {2,2} total 4
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000000fffffff]
[    0.000000]   HighMem  [mem 0x0000000010000000-0x0000000023ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000001bffffff]
[    0.000000]   node   0: [mem 0x0000000020000000-0x0000000023ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000023ffffff]
[    0.000000] On node 0 totalpages: 131072
[    0.000000] free_area_init_node: node 0, pgdat 805ee2a0, node_mem_map 81003000
[    0.000000]   Normal zone: 576 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 65536 pages, LIFO batch:15
[    0.000000]   HighMem zone: 65536 pages, LIFO batch:15
[    0.000000] random: get_random_bytes called from start_kernel+0x9c/0x4d8 with crng_init=0
[    0.000000] percpu: Embedded 14 pages/cpu s26064 r8192 d23088 u57344
[    0.000000] pcpu-alloc: s26064 r8192 d23088 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 130496
[    0.000000] Kernel command line: console=ttyS0,57600 rootfstype=squashfs,jffs2
[    0.000000] PID hash table entries: 1024 (order: 0, 4096 bytes)
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Writing ErrCtl register=00008400
[    0.000000] Readback ErrCtl register=00008400
[    0.000000] Memory: 510960K/524288K available (4784K kernel code, 247K rwdata, 1040K rodata, 1276K init, 253K bss, 13328K reserved, 0K cma-reserved, 262144K highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 256
[    0.000000] CPU Clock: 880MHz
[    0.000000] clocksource: GIC: mask: 0xffffffffffffffff max_cycles: 0xcaf478abb4, max_idle_ns: 440795247997 ns
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 4343773742 ns
[    0.000010] sched_clock: 32 bits at 440MHz, resolution 2ns, wraps every 4880645118ns
[    0.015520] Calibrating delay loop... 586.13 BogoMIPS (lpj=2930688)
[    0.087847] pid_max: default: 32768 minimum: 301
[    0.097226] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.110251] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.126611] Hierarchical SRCU implementation.
[    0.136218] smp: Bringing up secondary CPUs ...
[    0.644087] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.644098] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.644111] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.644260] CPU1 revision is: 0001992f (MIPS 1004Kc)
[    0.205523] Synchronize counters for CPU 1: done.
[    0.399070] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.399079] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.399087] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.399164] CPU2 revision is: 0001992f (MIPS 1004Kc)
[    0.326649] Synchronize counters for CPU 2: done.
[    0.518005] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.518014] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.518022] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.518106] CPU3 revision is: 0001992f (MIPS 1004Kc)
[    0.446212] Synchronize counters for CPU 3: done.
[    0.505828] smp: Brought up 1 node, 4 CPUs
[    0.518259] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.537711] futex hash table entries: 1024 (order: 3, 32768 bytes)
[    0.550328] pinctrl core: initialized pinctrl subsystem
[    0.562239] NET: Registered protocol family 16
[    0.581427] FPU Affinity set after 11720 emulations
[    0.582182] pull PCIe RST: RALINK_RSTCTRL = 0
[    0.891260] release PCIe RST: RALINK_RSTCTRL = 7000000
[    0.901331] ***** Xtal 40MHz *****
[    0.908054] release PCIe RST: RALINK_RSTCTRL = 7000000
[    0.918271] Port 0 N_FTS = 1b105000
[    0.925162] Port 1 N_FTS = 1b105000
[    0.932090] Port 2 N_FTS = 1b102800
[    2.091260] PCIE2 no card, disable it(RST&CLK)
[    2.099962]  -> 21007f2
[    2.104770] PCIE0 enabled
[    2.109973] PCIE1 enabled
[    2.115153] PCI host bridge /pcie@1e140000 ranges:
[    2.124681]  MEM 0x0000000060000000..0x000000006fffffff
[    2.135034]   IO 0x000000001e160000..0x000000001e16ffff
[    2.145409] PCI coherence region base: 0xbfbf8000, mask/settings: 0x60000000
[    2.169842] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    2.181187] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    2.192418] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    2.205153] PCI host bridge to bus 0000:00
[    2.213177] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff]
[    2.226840] pci_bus 0000:00: root bus resource [io  0xffffffff]
[    2.238577] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    2.252058] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    2.267825] pci 0000:00:00.0: [0e8d:0801] type 01 class 0x060400
[    2.267869] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    2.267881] pci 0000:00:00.0: reg 0x14: [mem 0x60300000-0x6030ffff]
[    2.267948] pci 0000:00:00.0: supports D1
[    2.267957] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    2.268251] pci 0000:00:01.0: [0e8d:0801] type 01 class 0x060400
[    2.268295] pci 0000:00:01.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    2.268315] pci 0000:00:01.0: reg 0x14: [mem 0x60310000-0x6031ffff]
[    2.268383] pci 0000:00:01.0: supports D1
[    2.268393] pci 0000:00:01.0: PME# supported from D0 D1 D3hot
[    2.268890] pci 0000:01:00.0: [14c3:7603] type 00 class 0x028000
[    2.268951] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff]
[    2.269084] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    2.269299] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    2.269556] pci 0000:02:00.0: [14c3:7662] type 00 class 0x028000
[    2.269624] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit]
[    2.269672] pci 0000:02:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    2.269766] pci 0000:02:00.0: PME# supported from D0 D3hot D3cold
[    2.269978] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02
[    2.270005] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 02
[    2.270103] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    2.283132] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    2.296952] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000]
[    2.310073] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000]
[    2.323905] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff]
[    2.337385] pci 0000:00:01.0: BAR 8: assigned [mem 0x60100000-0x601fffff]
[    2.350859] pci 0000:00:01.0: BAR 9: assigned [mem 0x60200000-0x602fffff pref]
[    2.365209] pci 0000:00:00.0: BAR 1: assigned [mem 0x60300000-0x6030ffff]
[    2.378691] pci 0000:00:01.0: BAR 1: assigned [mem 0x60310000-0x6031ffff]
[    2.392169] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff]
[    2.405640] pci 0000:00:00.0: PCI bridge to [bus 01]
[    2.415477] pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
[    2.428977] pci 0000:02:00.0: BAR 0: assigned [mem 0x60100000-0x601fffff 64bit]
[    2.443495] pci 0000:02:00.0: BAR 6: assigned [mem 0x60200000-0x6020ffff pref]
[    2.457823] pci 0000:00:01.0: PCI bridge to [bus 02]
[    2.467658] pci 0000:00:01.0:   bridge window [mem 0x60100000-0x601fffff]
[    2.481152] pci 0000:00:01.0:   bridge window [mem 0x60200000-0x602fffff pref]
[    2.497043] clocksource: Switched to clocksource GIC
[    2.508779] NET: Registered protocol family 2
[    2.518080] TCP established hash table entries: 2048 (order: 1, 8192 bytes)
[    2.531828] TCP bind hash table entries: 2048 (order: 2, 16384 bytes)
[    2.544613] TCP: Hash tables configured (established 2048 bind 2048)
[    2.557355] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    2.568861] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    2.581549] NET: Registered protocol family 1
[    2.590157] PCI: CLS 0 bytes, default 32
[    2.826980] 4 CPUs re-calibrate udelay(lpj = 2924544)
[    2.838685] Crashlog allocated RAM at address 0x3f00000
[    2.849270] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    2.862305] random: fast init done
[    2.877580] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    2.889079] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    2.912428] bounce: pool size: 64 pages
[    2.919997] io scheduler noop registered
[    2.927710] io scheduler deadline registered (default)
[    2.939019] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
[    2.953049] console [ttyS0] disabled
[    2.960137] 1e000c00.uartlite: ttyS0 at MMIO 0x1e000c00 (irq = 19, base_baud = 3125000) is a 16550A
[    2.978046] console [ttyS0] enabled
[    2.991824] bootconsole [early0] disabled
[    3.008570] 1e000e00.uartlite3: ttyS1 at MMIO 0x1e000e00 (irq = 20, base_baud = 3125000) is a 16550A
[    3.028810] MediaTek Nand driver init, version v2.1 Fix AHB virt2phys error
[    3.043216] spi-mt7621 1e000b00.spi: sys_freq: 220000000
[    3.054845] m25p80 spi0.0: mx25l25635e (32768 Kbytes)
[    3.064991] 4 fixed-partitions partitions found on MTD device spi0.0
[    3.077653] Creating 4 MTD partitions on "spi0.0":
[    3.087208] 0x000000000000-0x000000030000 : "u-boot"
[    3.098419] 0x000000030000-0x000000040000 : "u-boot-env"
[    3.110253] 0x000000040000-0x000000050000 : "factory"
[    3.121512] 0x000000050000-0x000002000000 : "firmware"
[    3.133172] 2 uimage-fw partitions found on MTD device firmware
[    3.145032] Creating 2 MTD partitions on "firmware":
[    3.154926] 0x000000000000-0x0000001eabdf : "kernel"
[    3.166058] 0x0000001eabdf-0x000001fb0000 : "rootfs"
[    3.177189] mtd: device 5 (rootfs) set to be root filesystem
[    3.188602] 1 squashfs-split partitions found on MTD device rootfs
[    3.200932] 0x000000730000-0x000001fb0000 : "rootfs_data"
[    3.213624] libphy: Fixed MDIO Bus: probed
[    3.289075] libphy: mdio: probed
[    4.696571] mtk_soc_eth 1e100000.ethernet: loaded mt7530 driver
[    4.709225] mtk_soc_eth 1e100000.ethernet eth0: mediatek frame engine at 0xbe100000, irq 22
[    4.728704] NET: Registered protocol family 10
[    4.739385] Segment Routing with IPv6
[    4.746774] NET: Registered protocol family 17
[    4.755770] 8021q: 802.1Q VLAN Support v1.8
[    4.766759] hctosys: unable to open rtc device (rtc0)
[    4.781798] VFS: Mounted root (squashfs filesystem) readonly on device 31:5.
[    4.800863] Freeing unused kernel memory: 1276K
[    4.809946] This architecture does not have kernel memory protection.
[    5.422771] init: Console is alive
[    5.429855] init: - watchdog -
[    6.333386] mtk_soc_eth 1e100000.ethernet eth0: port 4 link up
[    6.453198] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    6.559499] usbcore: registered new interface driver usbfs
[    6.570577] usbcore: registered new interface driver hub
[    6.581359] usbcore: registered new device driver usb
[    6.599811] mtk_soc_eth 1e100000.ethernet eth0: port 1 link up
[    6.623841] xhci-mtk 1e1c0000.xhci: 1e1c0000.xhci supply vbus not found, using dummy regulator
[    6.641148] xhci-mtk 1e1c0000.xhci: 1e1c0000.xhci supply vusb33 not found, using dummy regulator
[    6.658870] xhci-mtk 1e1c0000.xhci: xHCI Host Controller
[    6.669487] xhci-mtk 1e1c0000.xhci: new USB bus registered, assigned bus number 1
[    6.687201] xhci-mtk 1e1c0000.xhci: hcc params 0x01401198 hci version 0x96 quirks 0x0000000000210010
[    6.705490] xhci-mtk 1e1c0000.xhci: irq 21, io mem 0x1e1c0000
[    6.717988] hub 1-0:1.0: USB hub found
[    6.725540] hub 1-0:1.0: 2 ports detected
[    6.734150] xhci-mtk 1e1c0000.xhci: xHCI Host Controller
[    6.744772] xhci-mtk 1e1c0000.xhci: new USB bus registered, assigned bus number 2
[    6.759699] xhci-mtk 1e1c0000.xhci: Host supports USB 3.0  SuperSpeed
[    6.772767] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[    6.789802] hub 2-0:1.0: USB hub found
[    6.797390] hub 2-0:1.0: 1 port detected
[    6.810559] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    6.827417] init: - preinit -
[    7.844555] mtk_soc_eth 1e100000.ethernet: PPE started
[   11.160287] jffs2: notice: (471) jffs2_build_xattr_subsystem: complete building xattr subsystem, 3 of xdatum (0 unchecked, 3 orphan) and 3 of xref (3 dead, 0 orphan) found.
[   11.193042] mount_root: switching to jffs2 overlay
[   11.225363] overlayfs: upper fs does not support tmpfile.
[   11.242310] urandom-seed: Seeding with /etc/urandom.seed
[   11.374730] mtk_soc_eth 1e100000.ethernet: 0x100 = 0x6060000c, 0x10c = 0x80818
[   11.397790] procd: - early -
[   11.403632] procd: - watchdog -
[   12.077284] procd: - watchdog -
[   12.083903] procd: - ubus -
[   12.228311] random: ubusd: uninitialized urandom read (4 bytes read)
[   12.258938] random: ubusd: uninitialized urandom read (4 bytes read)
[   12.272078] random: ubusd: uninitialized urandom read (4 bytes read)
[   12.285722] procd: - init -
[   12.854689] random: crng init done
[   12.861480] random: 7 urandom warning(s) missed due to ratelimiting
[   12.892261] urngd: v1.0.0 started.
[   12.900525] kmodloader: loading kernel modules from /etc/modules.d/*
[   12.974560] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   12.995470] Loading modules backported from Linux version v5.3-rc4-0-gd45331b00ddb
[   13.010692] Backport generated by backports.git v5.3-rc4-1-0-g4ec72687
[   13.025954] ip_tables: (C) 2000-2006 Netfilter Core Team
[   13.043966] nf_conntrack version 0.5.0 (8192 buckets, 32768 max)
[   13.098753] xt_time: kernel timezone is -0000
[   13.179915] bus=0x1, slot = 0x0, irq=0xff
[   13.188215] mt7603e 0000:01:00.0: ASIC revision: 76030010
[   14.228486] mt7603e 0000:01:00.0: Firmware Version: ap_pcie
[   14.239698] mt7603e 0000:01:00.0: Build Time: 20160107100755
[   14.287044] mt7603e 0000:01:00.0: firmware init done
[   14.459659] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   14.472369] bus=0x2, slot = 0x1, irq=0xff
[   14.480701] mt76x2e 0000:02:00.0: ASIC revision: 76120044
[   15.197246] mt76x2e 0000:02:00.0: ROM patch build: 20141115060606a
[   15.213177] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[   15.224208] mt76x2e 0000:02:00.0: Build: 1
[   15.232385] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[   15.267040] mt76x2e 0000:02:00.0: Firmware running!
[   15.279931] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
[   15.288257] PPP generic driver version 2.4.2
[   15.298879] NET: Registered protocol family 24
[   15.311037] kmodloader: done loading kernel modules from /etc/modules.d/*
[   21.543781] mtk_soc_eth 1e100000.ethernet: PPE started
[   21.562295] br-lan: port 1(eth0.1) entered blocking state
[   21.573299] br-lan: port 1(eth0.1) entered disabled state
[   21.584918] device eth0.1 entered promiscuous mode
[   21.594538] device eth0 entered promiscuous mode
[   21.607424] br-lan: port 1(eth0.1) entered blocking state
[   21.618281] br-lan: port 1(eth0.1) entered forwarding state
[   21.630097] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   22.881975] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   24.965176] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready
[   24.985745] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   25.011310] br-lan: port 2(wlan0) entered blocking state
[   25.022119] br-lan: port 2(wlan0) entered disabled state
[   25.033907] device wlan0 entered promiscuous mode
[   25.045938] br-lan: port 3(wlan1) entered blocking state
[   25.056734] br-lan: port 3(wlan1) entered disabled state
[   25.068386] device wlan1 entered promiscuous mode
[   25.643947] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   25.657593] br-lan: port 2(wlan0) entered blocking state
[   25.668265] br-lan: port 2(wlan0) entered forwarding state
[   26.352827] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[   26.366176] br-lan: port 3(wlan1) entered blocking state
[   26.376861] br-lan: port 3(wlan1) entered forwarding state

**Comment by ptpt52** [comment]
@securecrt 
you should not remove `target/linux/ramips/patches-4.14/303-spi-nor-enable-4B-opcodes-for-mx66l51235l.patch`

many other devices need this patch

**Comment by securecrt** [comment]
@ptpt52  
remove the 303-spi-nor-enable-4B-opcodes-for-mx66l51235l.patch will keep the maxim compatibility on other devices . turn on the 4B-OPCODE feature will cause the bootup issue on some type of gehua-r-001 , I think it could be possible cause the same issue on other devices.

**Comment by securecrt** [comment]
@ptpt52  I made a mistake , yes we should keep 303-spi-nor-enable-4B-opcodes-for-mx66l51235l.patch

in fact I was intended to delete this one:
304-spi-nor-enable-4B-opcodes-for-mx25l25635f.patch

I have changed my patch.

**Comment by ptpt52** [comment]
@securecrt 
may be @dengqf6 know about `304-spi-nor-enable-4B-opcodes-for-mx25l25635f.patch`

**Comment by securecrt** [comment]
@ptpt52 
In fact I have asked @dengqf6  to revert this patch at about half year ago. But he said this patch is running ok on his own router.

**Comment by ptpt52** [comment]
as I can see,
why ghl crash: 
`flash mx25l25635e + 304 patch + ghl-dts force flash mx25l25635f`

I mean:
on some of ghl devices, the flash is mx25l25635f and some is mx25l25635e
That is why it crash.

on youku-yk1 and newifi-d1 it's flash is mx25l25635f so 304 patch works
but for some of these devices, if its flash is mx25l25635e it would crash

**Comment by securecrt** [comment]
I dont know if the 304 patch has been deleted, youku-yk1 and newifi-d1 will work or not? 
I was thinking that this patch was trying to fix the soft reboot issue.
999-fix-m25p-shutdown.patch should be more safe to fix the soft reboot issue on such devices.

**Comment by securecrt** [comment]
who can test this patch on youku-yk1 and newifi-d1 , if there is no side effect I suggest to merge this patch ASAP, since currently the gehua-r-001 can't boot with the snapshot build.

**Comment by securecrt** [comment]
@ptpt52  can you please review this patch and help to merge it to the trunk?

**Comment by ptpt52** [comment]
I think `304-spi-nor-enable-4B-opcodes-for-mx25l25635f.patch` should not be dropped, it seems work on youku-yk1 and newifi-d1.

The reason why GHL crash with `304-spi-nor-enable-4B-opcodes-for-mx25l25635f.patch` is:
GHL use `mx25l25635e flash` while the code treat it as `mx25l25635e flash`

**Comment by ptpt52** [comment]
It’s also reasonable to delete the `4B patch` as you did.
if `m25p-shutdown.patch` work on all case (No side effects for other devices) then your commit is good.

but first we need more feedback and testing to determine if there is a problem.

**Comment by securecrt** [comment]
I dont have the youku-yk1 and newifi-d1 routers. What I can confirm is my patch works well on the ghl-r-001. can you find someone who have the youku-yk1 and newifi-d1?

**Comment by adrianschmutzler** [comment]
@securecrt It would be good if you provide more information on the what you change and why in the commit message. If you affect other devices by your changes, it normally a good idea to look who has added support/patches to those devices so far. You can then mention those people here and ask them for help/test.
Despite, I do not think it's a good idea to use number 999 on a patch. I haven't checked for this case, but for certain cases the first digit of the patch number is based on which purpose the patch should follow.

**Comment by jeffsf** [comment]
https://openwrt.org/docs/guide-developer/build-system/use-patches-with-buildsystem#naming_patches

**Comment by mkresin** [comment]
Your patch `target/linux/ramips/patches-4.14/999-fix-m25p-shutdown.patch` will not be accepted. 

Read http://lists.infradead.org/pipermail/openwrt-devel/2019-October/019648.html and the included links for more details.

**Comment by adrianschmutzler** [comment]
@securecrt Ping.

**Comment by securecrt** [comment]
> @securecrt Ping.

I will drop this pull request.

**Pull request closed without merging**
