### PR TITLE
build: introduce a dependency check for swig

### PR DESCRIPTION
**Pull request by vulpes2**
`swig` is required by `pylibfdt`, which is needed to build modern versions of u-boot. There is no reliable way to check for Python support, and running grep on the help text feels pretty fragile, so only the existence of `swig` is being checked.

Should we make this per-target or put it in `u-boot.mk` somehow, so this is only checked if u-boot is being built? Suggestions are welcome.

### CODE REVIEW

**Comment by hauke** [comment]
The default build container does not have swig installed and the github CI fails like this:
````
Checking 'which'... ok.
Checking 'swig'... failed.
Checking 'ldconfig-stub'... ok.

Build dependency: Please install 'swig'

Prerequisite check failed. Use FORCE=1 to override.
make: *** [/__w/openwrt/openwrt/openwrt/include/toplevel.mk:181: staging_dir/host/.prereq-build] Error 1
Error: Process completed with exit code 1.
````

**Comment by vulpes2** [comment]
@aparcar Could you please look into this? The failing workflow is pulling `ghcr.io/openwrt/tools:latest` and it this image needs to be updated. The swig dependency issue has been fixed a long time ago here: https://gitlab.com/openwrt/buildbot/-/commit/3776a9157532e69478ef03236d22254267a4f12e but it has not been made available to this workflow yet.

**Comment by ynezz** [comment]
What about something like this (untested)? 

```diff
diff --git a/include/u-boot.mk b/include/u-boot.mk
index 8945e8e2b8f5..75d20a632555 100644
--- a/include/u-boot.mk
+++ b/include/u-boot.mk
@@ -8,6 +8,10 @@ PKG_SOURCE_URL = \
        ftp://ftp.denx.de/pub/u-boot
 endif
 
+ifdef UBOOT_FORCE_INTREE_DTC
+$(eval $(call SetupHostCommand,swig,Please install 'swig', swig))
+endif
+
 PKG_BUILD_DIR = $(BUILD_DIR)/$(PKG_NAME)-$(BUILD_VARIANT)/$(PKG_NAME)-$(PKG_VERSION)
 
 PKG_TARGETS := bin
@@ -85,7 +89,9 @@ define Build/Configure/U-Boot
        +$(MAKE) $(PKG_JOBS) -C $(PKG_BUILD_DIR) $(UBOOT_CONFIGURE_VARS) $(UBOOT_CONFIG)_config
 endef
 
+ifndef UBOOT_FORCE_INTREE_DTC
 DTC=$(wildcard $(LINUX_DIR)/scripts/dtc/dtc)
+endif
 
 define Build/Compile/U-Boot
        +$(MAKE) $(PKG_JOBS) -C $(PKG_BUILD_DIR) \
```

which could then be used like this:

```diff
diff --git a/package/boot/uboot-rockchip/Makefile b/package/boot/uboot-rockchip/Makefile
index 441028fe7f1e..896214e8572b 100644
--- a/package/boot/uboot-rockchip/Makefile
+++ b/package/boot/uboot-rockchip/Makefile
@@ -12,6 +12,7 @@ PKG_HASH:=312b7eeae44581d1362c3a3f02c28d806647756c82ba8c72241c7cdbe68ba77e
 
 PKG_MAINTAINER:=Tobias Maedel <openwrt@tbspace.de>
 
+UBOOT_FORCE_INTREE_DTC:=1
 include $(INCLUDE_DIR)/u-boot.mk
 include $(INCLUDE_DIR)/package.mk
```

**Comment by Ansuel** [comment]
@vulpes2 that container use the buildworker container 3.4.1

https://github.com/openwrt/openwrt/blob/master/.github/workflows/Dockerfile.tools

**Comment by vulpes2** [comment]
> Anyway, what about something like this (untested)?

I'll test this later today and report back, thanks!



@Ansuel `swig` has been added even before buildworker v3.0.1 and I'm not entirely sure why it's still not available then: https://gitlab.com/openwrt/buildbot/-/commit/3776a9157532e69478ef03236d22254267a4f12e

**Comment by vulpes2** [comment]
My apologies for neglecting this for so long, life has been really hectic lately. I think the issue was that `swig` sets the return code to 1 if you call it without any arguments. The easiest way to get it to return 0 is to use help option, so that's what I did.

**Comment by Ansuel** [comment]
@ynezz are we sure it's ok to fragment SetupHostCommand in other include? Also I missed why this could not be just a host tool to compile?

**Comment by leandrolnh** [comment]
I think this can be closed due to commit [a3ec85507370efd7802837aabebe691c1f6b34db](https://github.com/openwrt/openwrt/commit/a3ec85507370efd7802837aabebe691c1f6b34db)

**Pull request closed without merging**
