### PR TITLE
kernel: bump 5.10 to 5.10.120

### PR DESCRIPTION
**Pull request by graysky2**
Patches automatically rebased.

Build system: x86_64
Build-tested: ipq806x/R7800, x86/64

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by Borromini** [comment]
I've first tried testing this on 22.03, but for me it's breaking on at least x86/64. I have these symbols in `target/linux/generic/config-5.10`. Your PR is missing the x86 symbol.

```
$ grep -in blake2s target/linux/generic/config-5.10 
1053:# CONFIG_CRYPTO_BLAKE2S is not set
1054:# CONFIG_CRYPTO_BLAKE2S_X86 is not set
1147:# CONFIG_CRYPTO_LIB_BLAKE2S is not set
```

To be sure this isn't a 22.03 issue, I checked master, same there:

```
~/code/lede/master$ grep -in blake2s target/linux/generic/config-5.10
1053:# CONFIG_CRYPTO_BLAKE2S is not set
1054:# CONFIG_CRYPTO_BLAKE2S_X86 is not set
1147:# CONFIG_CRYPTO_LIB_BLAKE2S is not set
```

Is your master branch clean? I ran git blame on the master config-5.10 file and line 1053 and 1054 haven't been touched in a while:

```
b10d6044599 (Felix Fietkau            2020-10-24 21:14:16 +0200 1053) # CONFIG_CRYPTO_BLAKE2S is not set
fc61a87c299 (Ilya Lipnitskiy          2021-03-03 08:58:22 -0800 1054) # CONFIG_CRYPTO_BLAKE2S_X86 is not set
```
Commit [fc61a87c299](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=fc61a87c2990fa90ed7e468bf0b85a8bb1fcd2f7) is part of OpenWrt master so this is no local change on my end.

Removing the two BLAKE2S symbols makes kconfig prompt me to set both when trying to compile 5.10.119:

```
  BLAKE2b digest algorithm (CRYPTO_BLAKE2B) [N/m/y/?] n
  BLAKE2s digest algorithm (CRYPTO_BLAKE2S) [N/m/y/?] (NEW) 
  BLAKE2s digest algorithm (x86 accelerated version) (CRYPTO_BLAKE2S_X86) [M/y/?] (NEW)

```
I checked the [upstream commit](https://github.com/torvalds/linux/commit/6048fdcc5f269c7f31d774c295ce59081b36e6f9) that makes BLAKE2s a built-in, but I don't see or understand why I'm getting prompted about those kernel symbols if they have been removed?

Might it be its not the crypto kernel symbols being removed in that commit, but the **lib/crypto** symbol - CRYPTO_LIB_BLAKE2S? That is what is happening [here](https://github.com/torvalds/linux/commit/6048fdcc5f269c7f31d774c295ce59081b36e6f9#diff-67a96d0074fdf01651314044986a01f2cc223d8fc4f9dc9e836dcabc1f88176aL84=) on line 84. Everything you are (correctly, I think) removing from the crypto and netsupport Makefiles are `crypto-lib-*` definitions.

**Comment by graysky2** [comment]
@Borromini - I build the buildbot config for x86/64 without errors.  Are you building with this PR against master or another branch?

**Comment by Borromini** [comment]
Whelp that was some serious PEBKAC. Sorry for the noise.

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in c9929fabcbd367cc82a9080ced08d7f21dead45a, 01a6a5c73120ccddd2a83381252ede91aac070f4, b789a588b1c55fe1df7e2d6ae1c4f84b96a03a95, cd634afe6cb6565eb6865931c8d73d97cab3600a and f800f8d6fc4f21ed87454aa657ebbf376dc3b6cf

**Pull request closed without merging**
