### PR TITLE
x86: add kernel 5.10 support to testing

### PR DESCRIPTION
**Pull request by curtdept**
NOTE: This PR is dependent on elfutils changes, pending by others.

Remove patch:
800-hwmon-w83627ehf-dont-claim-nct677x.patch (condition no longer present upstream)

Refresh patch:
011-tune_lzma_options.patch
012-pcengines-apu2-detect-apuv4-board.patch
100-fix_cs5535_clockevt.patch
200-pcengines-apu2-reboot.patch
300-pcengines_apu1_led.patch

### CODE REVIEW

**Comment by curtdept** [comment]
Looks like we have a few people working on this now, hopefully we can unify under testing.

This currently does NOT build under x86_64 due to libelf being to old. (see https://github.com/openwrt/openwrt/pull/3855)

**Comment by adschm** [comment]
Please agree on one PR and close the other, so we don't have split discussion.

**Comment by mj22226** [comment]
> This currently does NOT build under x86_64 due to libelf being to old and missing now used gelf_getsymshndx.

@curtdept Other work-around for x86_64 on 5.10 is revert https://github.com/torvalds/linux/commit/28fe1d7bf89f8ed5be70b98a33932dbaf99345dd I can build in 5.11 with no issues.

**Comment by curtdept** [comment]
> > This currently does NOT build under x86_64 due to libelf being to old and missing now used gelf_getsymshndx.
> 
> @curtdept Other work-around for x86_64 on 5.10 is revert [torvalds/linux@28fe1d7](https://github.com/torvalds/linux/commit/28fe1d7bf89f8ed5be70b98a33932dbaf99345dd) I can build in 5.11 with no issues.

True but I am guessing we will hot some wide device on this eventually. Plus everything else uses this now, binutils, etc

**Comment by curtdept** [comment]
I have raised https://github.com/openwrt/openwrt/pull/3942 as a precursor which corrects this issue.

**Comment by curtdept** [comment]
Closing, adding request for changes to existing PR

**Pull request closed without merging**
