### PR TITLE
ramips: fix tplink re200v3 led assignments for Power and Wifi (red)

### PR DESCRIPTION
**Pull request by misanthropos**
Power Led was not assigned correctly with mt7628an_tplink_re200.dtsi for V3 and V4. Same for Wifi (red)

Signed-off-by: Richard Fröhning <misanthropos@gmx.de>

### CODE REVIEW

**Comment by adschm** [comment]
I don't understand this change. What's it supposed to achieve? (Commit message might help, so we can discuss how to bring this in proper shape).

**Comment by misanthropos** [comment]
Trying to add those devices to gluon it came to my attention the Power LEDs ist not assigned correctly. Trying to figure out which GPIO would control it I found out there is no red for 2g and 5g, but for Wifi in general.
So I removed 2g_red and 5g_red and correctly assigned GPIOs to Power and Wifi (red).

https://github.com/freifunk-gluon/gluon/pull/2347

**Comment by misanthropos** [comment]
@adschm, I am not sure if you are waiting for a different commit message or my description regarding this PR is not sufficient to you.

**Comment by AiyionPrime** [comment]
@misanthropos dts files follow a hierarchy and files that include `.dtsi`-files include their definitions as such.

While technically possible, OpenWrt strives to avoid redundancies in widely same models.

If you want to change the led definition of only a few revisions, you should move the led definitions to the revisions dts files and to the changes there.

Let me know if you need further help with that.

**Comment by hauke** [comment]
Instead of adding a new dtsi file I would preefr if you just change the wrong settings in the `target/linux/ramips/dts/mt7628an_tplink_re200-v3.dts` file. 

Currently you have the following diff:
````
--- target/linux/ramips/dts/mt7628an_tplink_re200.dtsi	2022-10-22 00:58:21.521872353 +0200
+++ target/linux/ramips/dts/mt7628an_tplink_re200v3.dtsi	2022-10-22 16:05:16.133075301 +0200
@@ -47,6 +47,11 @@
 			gpios = <&gpio 4 GPIO_ACTIVE_LOW>;
 		};
 
+		wifi_red {
+			label = "red:wifi";
+			gpios = <&gpio 40 GPIO_ACTIVE_LOW>;
+		};
+
 		lan {
 			label = "green:lan";
 			gpios = <&gpio 39 GPIO_ACTIVE_LOW>;
@@ -54,7 +59,7 @@
 
 		led_power: power {
 			label = "green:power";
-			gpios = <&gpio 44 GPIO_ACTIVE_LOW>;
+			gpios = <&gpio 43 GPIO_ACTIVE_LOW>;
 		};
 
 		wifi2g_green {
@@ -69,15 +74,6 @@
 			linux,default-trigger = "phy1tpt";
 		};
 
-		wifi2g_red {
-			label = "red:wifi2g";
-			gpios = <&gpio 43 GPIO_ACTIVE_LOW>;
-		};
-
-		wifi5g_red {
-			label = "red:wifi5g";
-			gpios = <&gpio 40 GPIO_ACTIVE_LOW>;
-		};
 	};
 };
 
````
You can change the dts settings in the mt7628an_tplink_re200-v3.dts file for example:
````
&led_power {
	gpios = <&gpio 43 GPIO_ACTIVE_LOW>;
};
````

**Comment by AiyionPrime** [comment]
@misanthropos Let me know if you'd like help on this; Or if you just need a few more days.

**Comment by AiyionPrime** [comment]
It appears Sungbo already did the work for both the v3, as well as the v4 (#9258).

https://git.openwrt.org/?p=openwrt/staging/mans0n.git;a=commitdiff;h=c247bf48a478eed9beed38be88b5adf6fd0e83cb;hp=c11aad792afbbca582977002854148966ddccfb3

@mans0n if I built the v3 and v4 images of your patch onto the current master and  @misanthropos were to test them both, could we get your patch merged?

**Comment by hauke** [comment]
A similar patch fixing the problem was applied in 02aa7a2bb9b6bdc8033d30c97f5b49534206a37c, see #11165.

**Pull request closed without merging**
