### PR TITLE
kernel: Rtl8761 USB bluetooth support

### PR DESCRIPTION
**Pull request by QuintinHill**
Add support for RTL8761B USB bluetooth devices.  These are cheap and easy to find. Tested on a WNDR3700v4 with rtl8761bu firmware. Would love to have this backported to 22.03 if possible after it hits master.

Note without the correct firmware `hciconfig hci0 up` gives `Can't init device hci0: Out of memory (12)`.

### CODE REVIEW

**Comment by xabolcs** [comment]
Am I understand correctly that this PR adds support for e.g. TP-Link UB5A (tedboudros/tplink-ub500-linux-patch-guide#1)?

**Comment by xabolcs** [comment]
I successfully tested on TP-Link 1043NDv4 with TP-Link UB5A as [Bluetooth sink](https://openwrt.org/docs/guide-user/hardware/bluetooth/bluetooth.audio).

```
[    0.000000] Linux version 5.15.74 (xabolcs@ut2004) (mips-openwrt-linux-musl-gcc (OpenWrt GCC 11.3.0 r21115+4-ae57770c95) 11.3.0, GNU ld (GNU Binutils) 2.37) #0 Thu Oct 27 22:24:05 2022
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019750 (MIPS 74Kc)
[    0.000000] MIPS: machine is TP-Link TL-WR1043ND v4
[    0.000000] SoC: Qualcomm Atheros QCA956X ver 1 rev 0
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
...
[   24.246757] Bluetooth: Core ver 2.22
[   24.250570] NET: Registered PF_BLUETOOTH protocol family
[   24.256097] Bluetooth: HCI device and connection manager initialized
[   24.262674] Bluetooth: HCI socket layer initialized
[   24.267738] Bluetooth: L2CAP socket layer initialized
[   24.272974] Bluetooth: SCO socket layer initialized
[   24.280671] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   24.286223] Bluetooth: BNEP filters: protocol multicast
[   24.291628] Bluetooth: BNEP socket layer initialized
[   24.306389] usbcore: registered new interface driver btusb
[   24.315573] Loading modules backported from Linux version v5.15.74-0-ga3f2f5ac9d61
[   24.323496] Backport generated by backports.git v5.15.74-1-0-ge2d78967
[   24.330831] Bluetooth: hci0: RTL: examining hci_ver=0a hci_rev=0b00 lmp_ver=0a lmp_subver=6187
[   24.341129] Bluetooth: hci0: RTL: rom_version status=0 version=1
[   24.347420] Bluetooth: hci0: RTL: loading rtl_bt/rtl8761bu_fw.bin
[   24.472846] Bluetooth: hci0: RTL: loading rtl_bt/rtl8761bu_config.bin
[   24.480406] Bluetooth: hci0: RTL: cfg_sz 6, total sz 27814
[   24.488447] Bluetooth: HCI UART driver ver 2.3
[   24.493150] Bluetooth: HCI UART protocol H4 registered
[   24.498497] Bluetooth: HCI UART protocol BCSP registered
[   24.507307] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[   24.513557] Bluetooth: HIDP socket layer initialized
[   24.545167] Bluetooth: RFCOMM TTY layer initialized
[   24.550348] Bluetooth: RFCOMM socket layer initialized
[   24.555714] Bluetooth: RFCOMM ver 1.11
[   24.849156] PPP generic driver version 2.4.2
[   24.855850] Bluetooth: hci0: RTL: fw version 0x09a98a6b
```

```
root@OpenWrt ~ # lsusb 
Bus 001 Device 002: ID 2357:0604   TP-Link UB5A Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux 5.15.74 ehci_hcd EHCI Host Controller
```


So, here is my `Tested-by`:
```
Tested-by: Szabolcs Hubai <szab.hu@gmail.com> [2357:0604   TP-Link UB5A Adapter]
```

**Comment by QuintinHill** [comment]
@xabolcs thank you very much for testing this.  I will add your tested by if/when I reroll the first patch in the series.  I note that support for the TP-Link UB500 (UB5A) was backported to the 5.15 stable kernel (from 5.16) in https://github.com/gregkh/linux/commit/73f1e74f9c87cf36be5429c9a18358742806d7ed. Unfortunately this was not applied to the 5.10 stable series.  Similarly support for my device is only in the 5.15 stable series (https://github.com/gregkh/linux/commit/5b2ca3b8213a49940cb88d29034cbdaa3fbaccb7).

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in bc67c27283e1d0fa468c7fac5de9e864238305c7, 0bf512aa86678365aa2c7cd1dd1d6ae506ed7f62, 5e6e45b7ff0fee964d52fd57eb89e1a63ef5d8be and 4c3f664c2f4466b5a720f31fb74896d29db5d926.

**Pull request closed without merging**
