### PR TITLE
mt7621: set affiinity for mt79xx too

### PR DESCRIPTION
**Pull request by neheb**
Now that mt7915 devices are used with mt7621, this small change sets the IRQ affinity for those too.

Originally suggested on the forum:
https://forum.openwrt.org/t/linksys-e7350-serial-port-problem-or-downgrade-method/151557/48

ping @dengqf6 @Ansuel

### CODE REVIEW

**Comment by neheb** [comment]
Further simplified command:

```
grep "mt7[69]..e" /proc/interrupts | while read -r irq _;do echo "${irq/:/}";done
```

What do you guys think?

**Comment by nbd168** [comment]
I'd prefer to just drop this script instead. I don't see any reason for setting IRQ affinity for ethernet/WLAN anymore.

**Comment by nbd168** [comment]
Just to clarify that comment a bit: On Ethernet and WLAN, NAPI is threaded for all queues. This means that the processing work is not stuck on the CPU that fired the IRQ. Under heavy load, IRQs get disabled anyway, so it should not matter at all which CPUs the IRQs fire on.

**Comment by neheb** [comment]
basic testing indicates this to be true. I'll remove.

**Comment by neheb** [comment]
```
> git grep smp_affinity
target/linux/oxnas/base-files/etc/init.d/set-irq-affinity:      echo "$val" > "/proc/irq/$irq/smp_affinity"
target/linux/rockchip/armv8/base-files/etc/hotplug.d/net/40-net-smp-affinity:   echo "${core_mask}" > /proc/irq/${irq}/smp_affinity
```

maybe hotplug was a better place for this anyway.

**Pull request merged**
