### PR TITLE
rockchip: add linux v5.15 support and Rock64 board

### PR DESCRIPTION
**Pull request by lucize**
Tested on Pine Rock64

### CODE REVIEW

**Comment by mans0n** [comment]
The 5.15 bump part is duplicate of #9626. I'd be glad if you can provide Tested-by there.

**Comment by lucize** [comment]
somehow I missed that, will test and see

**Comment by Ansuel** [comment]
@lucize closing this as it was handled by another pr. If you notice something missing feel free to open another pr

**Comment by lucize** [comment]
I'll make a new PR, hopefully rather sooner than later :)

**Comment by Ansuel** [comment]
@CanadianBaconBoi it was also to add support for linux 5.15 so better create a separate PR just for the new device :D

**Comment by shark873** [comment]
There is also this PR going on right now:

https://github.com/openwrt/openwrt/pull/10123

FYI

**Comment by lucize** [comment]
I'm aware, hoping it will get merged soon and drop 5.10

**Pull request closed without merging**
