### PR TITLE
firmware-utils: mkdlinkfw: new tool for D-Link devices with JBOOT

### PR DESCRIPTION
**Pull request by CHKDSK88**
Tested on D-Link DWR-116.
Based on mktplinkfw.

Signed-off-by: Pawel Dembicki paweldembicki@gmail.com

### CODE REVIEW

**Comment by blogic** [comment]
merged the JBOOT patch, please create an extra PR for the board support patches

**Comment by CHKDSK88** [comment]
@blogic 
I can't find commit about this PR in main tree.

**Comment by blogic** [comment]
@CHKDSK88 https://github.com/openwrt/openwrt/commit/680e867d7f48bc326007e0b2bd8abba1ae702da6

**Comment by CHKDSK88** [comment]
@blogic 

Please check this PR again. #712  and #717 are diffrent patches. This patch add firmware builder, #717 added kernel splitter.

**Comment by blogic** [comment]
@CHKDSK88 please open a single PR containing *all* the patches that you want merged.

**Comment by CHKDSK88** [comment]
@blogic 
I am terribly sorry that I make mess.

Now everything is in one single #675

**Pull request closed without merging**
