### PR TITLE
ath79: add support for TP-Link WR841v11

### PR DESCRIPTION
**Pull request by juppin**
This device is apart from two additional led´s the same as TP-Link WR841v9.

Also remove SUPPORTED_DEVICES from wr841-v9 because it´s not needed and
for consistency rename everything to tl-wr841-v9.

Signed-off-by: Johann Neuhauser <johann@it-neuhauser.de>

### CODE REVIEW

**Comment by mkresin** [comment]
Please move the tl-wr841-v9 related changes into an own commit. They shouldn't be hidden in a commit adding support.

IMHO there should be three commits in the end:

- fix tl-wr841-v9 compatible string + remove SUPPORTED_DEVICES
- move status led alias node from dtsi to dts and rename label
- add support for v11 + adding gpio_leds label

**Comment by adrianschmutzler** [comment]
How about the EU/US versions in ath79? Will this be dealt with somehow internally or is this missing in the patch?

**Comment by juppin** [comment]
@mkresin I agree with you. Sorry for my laziness and thanks for your feedback.
@adrianschmutzler It´s missing here, i will add eu and us factory build definition as on ar71xx.

**Comment by mkresin** [comment]
merged, thanks!

**Pull request closed without merging**
