### PR TITLE
kernel: enable SRv6 support by enabling lwtunnel

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Enable the ability to use segment routing based on IPv6. It allows the packet to specify a path that the packet should take through the network.

Lwtunnel allow an easy encapsulation of a package. You can just install ip-full package and use it:

    ip -6 route add  2003::/64 dev eth0 encap seg6 mode encap segs 2001::1,2002::2

An IPv6 package looks like this:

    [IPv6 HDR][IPv6 RH][IPv6 HDR][Data...]

Netifd support:
  https://git.openwrt.org/?p=project/netifd.git;a=commit;h=458b1a7e9473c150a40cae5d8be174f4bb03bd39

Increases imagesize by 24.125 KiB. Therefore, only enable for devices with enough flash.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
netifd support merge: https://github.com/openwrt/openwrt/pull/3684

**Comment by PolynomialDivision** [comment]
Enable only for devices with sufficient flash. Further, deleted ` # CONFIG_IPV6_SEG6_LWTUNNEL is not set `target/linux/generic/config-5.4`.

**Comment by PolynomialDivision** [comment]
Anything new with this PR? I would love to see that merged. ;)

**Review by neheb — APPROVED** [review]

**Comment by PolynomialDivision** [comment]
@aparcar could u maybe ack that as second person? ;)
I want to utilize that in our mesh network for different purposes.

**Comment by aparcar** [comment]
Thanks!

**Comment by PolynomialDivision** [comment]
Nice thanks a lot!

**Pull request closed without merging**
