### PR TITLE
kernel: add and enable MGLRU for Linux 5.15

### PR DESCRIPTION
**Pull request by rsalvaterra**
After the [Phoronix](https://www.phoronix.com/news/MGLRU-Performance-OpenWRT) article I thought "well, why not?", so here it is in all its glory. Yu Zhao's MGLRU for 5.15 as an OpenWrt patch set. Go crazy, folks. 😎

Please note that I've been running this on several devices (APU2C4, Turris Omnia, Redmi AC2100, Belkin RT3200) for about three months without any issues, but I haven't tested all architectures. Further testing is most welcome, although it does seem rock-solid.

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by aparcar** [comment]
Mind sharing some benchmarks?

**Comment by rsalvaterra** [comment]
> Mind sharing some benchmarks?

I haven't done any, but there are some results [here](https://lore.kernel.org/linux-mm/20220831041731.3836322-1-yuzhao@google.com/).

**Comment by Vladdrako** [comment]
ramips/mt7621/mir3p. Crashes on USB-HDD activity.
<details>
<pre>
<1>[  226.043272] CPU 1 Unable to handle kernel paging request at virtual address 0032f1f0, epc == 80159b24, ra == 80159c78
<4>[  226.054334] Oops[#1]:
<4>[  226.056689] CPU: 1 PID: 114 Comm: kswapd0 Tainted: G           O      5.15.64 #0
<4>[  226.064141] $ 0   : 00000000 00000001 0032f1e8 1f0436dd
<4>[  226.069429] $ 4   : 8110396c fffffffc 00000005 80b20ce0
<4>[  226.074705] $ 8   : 00000005 00000028 89af8058 0000003c
<4>[  226.079976] $12   : 80c60000 80a80000 80c90000 00000001
<4>[  226.085317] $16   : 77816000 80b20c78 89af7f68 80b20c64
<4>[  226.090590] $20   : 80b20120 7781a000 8160fac0 81440800
<4>[  226.095840] $24   : 00000003 0000007b                  
<4>[  226.101084] $28   : 8160e000 8160fa58 81441000 80159c78
<4>[  226.106335] Hi    : 00000000
<4>[  226.109208] Lo    : b6db6db9
<4>[  226.112084] epc   : 80159b24 lru_gen_look_around+0x264/0x4e4
<4>[  226.117760] ra    : 80159c78 lru_gen_look_around+0x3b8/0x4e4
<4>[  226.123415] Status: 1100fc03	KERNEL EXL IE 
<4>[  226.127615] Cause : c0800008 (ExcCode 02)
<4>[  226.131613] BadVA : 0032f1f0
<4>[  226.134489] PrId  : 0001992f (MIPS 1004Kc)
<4>[  226.138573] Modules linked in: nf_nat_amanda nf_conntrack_amanda pppoe ppp_async cdc_mbim wireguard snd_usb_audio rndis_host qmi_wwan pptp pppox ppp_mppe ppp_generic nft_fib_inet nf_flow_table_ipv6 nf_flow_table_ipv4 nf_flow_table_inet mt7615e(O) mt7615_common(O) mt76_connac_lib(O) mt76(O) mac80211(O) libchacha20poly1305 ipt_REJECT huawei_cdc_ncm ebtable_nat ebtable_filter ebtable_broute cfg80211(O) cdc_subset cdc_ncm cdc_ether cdc_eem xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_geoip(O) xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY vhci_hcd usbnet usblp usbip_host usbip_core usbhid ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda ts_kmp ts_fsm ts_bm tcp_hybla snd_usbmidi_lib slhc poly1305_mips nft_tproxy nft_socket nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet
<4>[  226.139307]  nft_reject_bridge nft_reject nft_redir nft_quota nft_queue nft_objref nft_numgen nft_nat nft_meta_bridge nft_masq nft_log nft_limit nft_hash nft_fwd_netdev nft_fullcone(O) nft_flow_offload nft_fib_ipv6 nft_fib_ipv4 nft_fib nft_dup_netdev nft_ct nft_counter nft_compat nft_chain_nat nfnetlink_queue nfnetlink_log nf_tproxy_ipv6 nf_tproxy_ipv4 nf_tables nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_pptp nf_nat_irc nf_nat_h323 nf_nat_ftp nf_nat nf_log_syslog nf_flow_table nf_dup_netdev nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_pptp nf_conntrack_netlink nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast nf_conntrack_bridge nf_conncount mdio_netlink(O) lzo_rle lzo libcurve25519_generic lib80211_crypt_wep(O) lib80211_crypt_tkip(O) lib80211_crypt_ccmp(O) lib80211(O) iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables hwmon hid_generic ebtables ebt_vlan ebt_stp ebt_redirect
<4>[  226.226725]  ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_among ebt_802_3 crc_itu_t crc_ccitt compat(O) cls_flower arptable_filter arpt_mangle arp_tables act_vlan fuse ntfs3 cls_bpf act_bpf sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_tcindex cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred act_gact sg hid evdev ledtrig_usbport ledtrig_gpio cryptodev(O) xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ipmac ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink jool_siit(O) jool(O) jool_common(O) ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 nfsv4 nfsv3 nfsd nfs msdos bonding ip6_gre ip_gre gre ifb nat46(O) sit ip6_tunnel netlink_diag tunnel6 tunnel4 rpcsec_gss_krb5 auth_rpcgss veth tun snd_rawmidi
<4>[  226.313644]  snd_seq_device snd_pcm_oss snd_mixer_oss snd_hwdep snd_compress snd_pcm snd_timer snd soundcore ovpn_dco(O) nbd loop vfat fat lockd sunrpc grace minix isofs hfsplus hfs cdrom cifs cifs_md4 cifs_arc4 autofs4 dns_resolver nls_koi8_r nls_iso8859_6 nls_iso8859_2 nls_iso8859_15 nls_iso8859_13 nls_iso8859_1 nls_cp936 nls_cp866 nls_cp864 nls_cp862 nls_cp852 nls_cp850 nls_cp775 nls_cp437 nls_cp1251 nls_cp1250 algif_skcipher algif_rng algif_hash algif_aead af_alg sha1_generic des_generic arc4 uas leds_gpio xhci_plat_hcd xhci_pci xhci_mtk_hcd xhci_hcd ahci libahci libata gpio_button_hotplug(O) xfs jfs f2fs ext4 mbcache jbd2 exfat btrfs raid6_pq lzo_decompress lzo_compress dm_mirror dm_region_hash dm_log dm_crypt dm_mod dax mii mq_deadline kyber_iosched bfq crc32_generic
<4>[  226.468468] Process kswapd0 (pid: 114, threadinfo=1005c3cc, task=d31b28f0, tls=00000000)
<4>[  226.476558] Stack : 00000001 a1279c47 8160fb18 81f69e00 8160fbf0 80067a58 8160fbf0 80067a58
<4>[  226.484950]         00000005 00000005 00000005 81890000 8160fb64 8a7aba20 00000000 80b20000
<4>[  226.493342]         000777fa 00010000 8922a090 8a7aba20 fffffff2 801885c8 8160fb18 8006b284
<4>[  226.501737]         00300005 841cfc6c 80fe07c8 8a7aba20 777fa000 89986774 89af7fe8 80e03ad0
<4>[  226.510133]         00000000 80a85418 777fa000 80824260 80a26268 777fa000 899da8e0 8160fb50
<4>[  226.518530]         ...
<4>[  226.520984] Call Trace:
<4>[  226.523420] [<80159b24>] lru_gen_look_around+0x264/0x4e4
<4>[  226.528749] [<801885c8>] page_referenced_one+0xb8/0x178
<4>[  226.534002] [<801881fc>] rmap_walk_anon+0x184/0x258
<4>[  226.538883] [<80188a40>] page_referenced+0x16c/0x1b8
<4>[  226.543856] [<801531f8>] shrink_page_list+0x5ac/0x131c
<4>[  226.548994] [<801568e0>] shrink_lruvec+0x10f0/0x1fb0
<4>[  226.553961] [<80157c50>] shrink_node+0x4b0/0x7ec
<4>[  226.558580] [<80158e84>] kswapd+0x9f4/0xd10
<4>[  226.562769] [<80053ba4>] kthread+0x148/0x15c
<4>[  226.567043] [<800034f8>] ret_from_kernel_thread+0x14/0x1c
<4>[  226.572447] 
<4>[  226.573938] Code: 10a00004  2405fffc  00451024 <10000002> 8c420008  00451024  16e2ffe9  2402ff7b  00621024 
<4>[  226.583731] 
<4>[  226.585364] ---[ end trace bc90de31d7cdc6d2 ]---
<0>[  226.609505] Kernel panic - not syncing: Fatal exception
</pre>
</details>
But maybe this is a common memory issue because even without MGLRU I have crashes like this:
<details>
<pre>
[25718.338425] CPU: 1 PID: 35 Comm: kcompactd0 Tainted: G           O      5.15.60 #0
[25718.346010] $ 0   : 00000000 00000001 d47a5783 00000000
[25718.351319] $ 4   : d47a5782 00000001 00000008 00000280
[25718.356591] $ 8   : 8120cfdc 00000001 00010000 000003aa
[25718.361887] $12   : 04219800 04219800 00001764 00001764
[25718.367182] $16   : 81204000 00000000 0001d400 00010000
[25718.372481] $20   : 0001dc00 0001d800 00010000 81527e20
[25718.377782] $24   : 00000000 8096cdbc
[25718.383066] $28   : 81526000 81527d70 00000000 801a21e8
[25718.388342] Hi    : 00000b0d
[25718.391250] Lo    : 00000001
[25718.394153] epc   : 801a2224 compact_zone+0x6e8/0xd60
[25718.399259] ra    : 801a21e8 compact_zone+0x6ac/0xd60
[25718.404355] Status: 1100fc03 KERNEL EXL IE
[25718.408604] Cause : 40800010 (ExcCode 04)
[25718.412653] BadVA : d47a5782
[25718.415560] PrId  : 0001992f (MIPS 1004Kc)
[25718.419673] Modules linked in: nf_nat_amanda nf_conntrack_amanda pppoe ppp_async cdc_mbim wireguard snd_usb_audio rndis_host qmi_wwan pptp pppox ppp_mppe ppp_generic nft_fib_inet nf_flow_table_ipv6 nf_flow_table_ipv4 nf_flow_table_inet mt7615e(O) mt7615_common(O) mt76_connac_lib(O) mt76(O) mac80211(O) libchacha20poly1305 ipt_REJECT huawei_cdc_ncm ebtable_nat ebtable_filter ebtable_broute cfg80211(O) cdc_subset cdc_ncm cdc_ether cdc_eem xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_geoip(O) xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY vhci_hcd usbnet usblp usbip_host usbip_core usbhid ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda ts_kmp ts_fsm ts_bm tcp_hybla snd_usbmidi_lib slhc poly1305_mips nft_tproxy nft_socket nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet
[25718.420240]  nft_reject_bridge nft_reject nft_redir nft_quota nft_queue nft_objref nft_numgen nft_nat nft_meta_bridge nft_masq nft_log nft_limit nft_hash nft_fwd_netdev nft_flow_offload nft_fib_ipv6 nft_fib_ipv4 nft_fib nft_dup_netdev nft_ct nft_counter nft_compat nft_chain_nat nfnetlink_queue nfnetlink_log nf_tproxy_ipv6 nf_tproxy_ipv4 nf_tables nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_pptp nf_nat_irc nf_nat_h323 nf_nat_ftp nf_nat nf_log_syslog nf_flow_table nf_dup_netdev nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_pptp nf_conntrack_netlink nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast nf_conntrack_bridge nf_conncount mdio_netlink(O) lzo_rle lzo libcurve25519_generic lib80211_crypt_wep(O) lib80211_crypt_tkip(O) lib80211_crypt_ccmp(O) lib80211(O) iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables hwmon hid_generic ebtables ebt_vlan ebt_stp ebt_redirect ebt_pkttype ebt_mark_m
[25718.507415]  ebt_mark ebt_limit ebt_among ebt_802_3 crc_itu_t crc_ccitt compat(O) cls_flower arptable_filter arpt_mangle arp_tables act_vlan fuse ntfs3 cls_bpf act_bpf sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_tcindex cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred act_gact sg hid evdev ledtrig_usbport ledtrig_gpio cryptodev(O) xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ipmac ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink jool_siit(O) jool(O) jool_common(O) ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 nfsv4 nfsv3 nfsd nfs msdos bonding ip6_gre ip_gre gre ifb nat46(O) sit ip6_tunnel netlink_diag tunnel6 tunnel4 rpcsec_gss_krb5 auth_rpcgss tun snd_rawmidi snd_seq_device snd_pcm_oss
[25718.594786]  snd_mixer_oss snd_hwdep snd_compress snd_pcm snd_timer snd soundcore ovpn_dco(O) nbd loop vfat fat lockd sunrpc grace minix isofs hfsplus hfs cdrom cifs cifs_md4 cifs_arc4 autofs4 dns_resolver nls_koi8_r nls_iso8859_6 nls_iso8859_2 nls_iso8859_15 nls_iso8859_13 nls_iso8859_1 nls_cp936 nls_cp866 nls_cp864 nls_cp862 nls_cp852 nls_cp850 nls_cp775 nls_cp437 nls_cp1251 nls_cp1250 algif_skcipher algif_rng algif_hash algif_aead af_alg sha1_generic des_generic arc4 uas leds_gpio xhci_plat_hcd xhci_pci xhci_mtk_hcd xhci_hcd ahci libahci libata gpio_button_hotplug(O) xfs jfs f2fs ext4 mbcache jbd2 exfat btrfs raid6_pq lzo_decompress lzo_compress dm_mirror dm_region_hash dm_log dm_crypt dm_mod dax mii mq_deadline kyber_iosched bfq crc32_generic
[25718.746934] Process kcompactd0 (pid: 35, threadinfo=07ba3632, task=46851a90, tls=00000000)
[25718.755230] Stack : 7e538737 801a0948 80b61da8 81315b80 81527d90 81315b40 81527de8 81315b40
[25718.763657]         80c5d288 00000000 80dd0000 0000000c 00000000 81527e28 00000001 80bc0000
[25718.772107]         00000000 00000003 00010000 8019f0f0 801a0948 00000022 00000000 0000000c
[25718.780512]         00010000 00000000 80bc0000 80bc1414 80c5cd20 00000001 0000000a 80c5caa0
[25718.788914]         80bc1414 80c911f0 80c911f4 000015fd 00000000 801a2b64 ffffffff 00000000
[25718.797307]         ...
[25718.799784] Call Trace:
[25718.802224] [<801a2224>] compact_zone+0x6e8/0xd60
[25718.806952] [<801a2b64>] kcompactd_do_work+0x220/0x394
[25718.812130] [<801a2e20>] kcompactd+0x148/0x288
[25718.816604] [<8005aa5c>] kthread+0x1c4/0x1d8
[25718.820892] [<80003558>] ret_from_kernel_thread+0x14/0x1c

[25718.827863] Code: 10a00002  02002025  2444ffff <8c820000> 00531024  1040000a  00000000  9082002d  2c42000a

[25718.839841] ---[ end trace bc90de31d7cdc6d2 ]---
</pre>
</details>

**Comment by PolynomialDivision** [comment]
Runtested on:
- ipq40xx: Mikrotik SXTsq 5 AC
- TBD

**Comment by PolynomialDivision** [comment]
@icecream42 What did you use as benchmark tool?

**Comment by yuzhaogoogle** [comment]
> ramips/mt7621/mir3p. Crashes on USB-HDD activity.
> 
> <1>[  226.043272] CPU 1 Unable to handle kernel paging request at virtual address 0032f1f0, epc == 80159b24, ra == 80159c78
> <4>[  226.054334] Oops[#1]:
> <4>[  226.056689] CPU: 1 PID: 114 Comm: kswapd0 Tainted: G           O      5.15.64 #0
> <4>[  226.064141] $ 0   : 00000000 00000001 0032f1e8 1f0436dd
> <4>[  226.069429] $ 4   : 8110396c fffffffc 00000005 80b20ce0
> <4>[  226.074705] $ 8   : 00000005 00000028 89af8058 0000003c
> <4>[  226.079976] $12   : 80c60000 80a80000 80c90000 00000001
> <4>[  226.085317] $16   : 77816000 80b20c78 89af7f68 80b20c64
> <4>[  226.090590] $20   : 80b20120 7781a000 8160fac0 81440800
> <4>[  226.095840] $24   : 00000003 0000007b                  
> <4>[  226.101084] $28   : 8160e000 8160fa58 81441000 80159c78
> <4>[  226.106335] Hi    : 00000000
> <4>[  226.109208] Lo    : b6db6db9
> <4>[  226.112084] epc   : 80159b24 lru_gen_look_around+0x264/0x4e4
> <4>[  226.117760] ra    : 80159c78 lru_gen_look_around+0x3b8/0x4e4
> <4>[  226.123415] Status: 1100fc03	KERNEL EXL IE 
> <4>[  226.127615] Cause : c0800008 (ExcCode 02)
> <4>[  226.131613] BadVA : 0032f1f0
> <4>[  226.134489] PrId  : 0001992f (MIPS 1004Kc)

This is an MGLRU bug, and it was first reported by an Armbian user [here](https://forum.armbian.com/topic/20018-mglru-patches-to-bring-down-kswapd-cpu-usage/) and fixed in v12 [here](https://lore.kernel.org/r/20220614071650.206064-1-yuzhao@google.com/) (the latest MGLRU is v14 [here](https://lore.kernel.org/linux-mm/20220815071332.627393-1-yuzhao@google.com/)).

The following change to `lru_gen_look_around()` should fix it:
```
 	start = max(pvmw->address & PMD_MASK, pvmw->vma->vm_start);
-	end = pmd_addr_end(pvmw->address, pvmw->vma->vm_end);
+	end = min(pvmw->address | ~PMD_MASK, pvmw->vma->vm_end - 1) + 1;

 	if (end - start > MIN_BATCH_SIZE * PAGE_SIZE) {
```

Thanks for the pull request. @rsalvaterra 

I'll backport latest MGLRU to the current stable kernel 5.15 after it lands in 6.1 so that all distros use 5.15 can have the latest MGLRU without having to wait for 6.1 (the next stable kernel).

**Comment by rsalvaterra** [comment]
> > ramips/mt7621/mir3p. Crashes on USB-HDD activity.
> > <1>[  226.043272] CPU 1 Unable to handle kernel paging request at virtual address 0032f1f0, epc == 80159b24, ra == 80159c78
> > <4>[  226.054334] Oops[#1]:
> > <4>[  226.056689] CPU: 1 PID: 114 Comm: kswapd0 Tainted: G           O      5.15.64 #0
> > <4>[  226.064141] $ 0   : 00000000 00000001 0032f1e8 1f0436dd
> > <4>[  226.069429] $ 4   : 8110396c fffffffc 00000005 80b20ce0
> > <4>[  226.074705] $ 8   : 00000005 00000028 89af8058 0000003c
> > <4>[  226.079976] $12   : 80c60000 80a80000 80c90000 00000001
> > <4>[  226.085317] $16   : 77816000 80b20c78 89af7f68 80b20c64
> > <4>[  226.090590] $20   : 80b20120 7781a000 8160fac0 81440800
> > <4>[  226.095840] $24   : 00000003 0000007b
> > <4>[  226.101084] $28   : 8160e000 8160fa58 81441000 80159c78
> > <4>[  226.106335] Hi    : 00000000
> > <4>[  226.109208] Lo    : b6db6db9
> > <4>[  226.112084] epc   : 80159b24 lru_gen_look_around+0x264/0x4e4
> > <4>[  226.117760] ra    : 80159c78 lru_gen_look_around+0x3b8/0x4e4
> > <4>[  226.123415] Status: 1100fc03	KERNEL EXL IE
> > <4>[  226.127615] Cause : c0800008 (ExcCode 02)
> > <4>[  226.131613] BadVA : 0032f1f0
> > <4>[  226.134489] PrId  : 0001992f (MIPS 1004Kc)
> 
> This is an MGLRU bug, and it was first reported by an Armbian user [here](https://forum.armbian.com/topic/20018-mglru-patches-to-bring-down-kswapd-cpu-usage/) and fixed in v12 [here](https://lore.kernel.org/r/20220614071650.206064-1-yuzhao@google.com/) (the latest MGLRU is v14 [here](https://lore.kernel.org/linux-mm/20220815071332.627393-1-yuzhao@google.com/)).
> 
> The following change to `lru_gen_look_around()` should fix it:
> 
> ```
>  	start = max(pvmw->address & PMD_MASK, pvmw->vma->vm_start);
> -	end = pmd_addr_end(pvmw->address, pvmw->vma->vm_end);
> +	end = min(pvmw->address | ~PMD_MASK, pvmw->vma->vm_end - 1) + 1;
> 
>  	if (end - start > MIN_BATCH_SIZE * PAGE_SIZE) {
> ```
> 
> Thanks for the pull request. @rsalvaterra
> 
> I'll backport latest MGLRU to the current stable kernel 5.15 after it lands in 6.1 so that all distros use 5.15 can have the latest MGLRU without having to wait for 6.1 (the next stable kernel).

Wonderful, @yuzhaogoogle, thank you so much for stopping by! By the way (and going off topic for a bit, sorry about that), are you also backporting for 6.0? v14 doesn't apply cleanly, since it's based on mm-unstable (on top of the folio work, I think), and the rebasing conflicts looked quite scary to me (I'm not an mm expert at all). :wink:

**Comment by yuzhaogoogle** [comment]
> are you also backporting for 6.0? v14 doesn't apply cleanly, since it's based on mm-unstable (on top of the folio work, I think), and the rebasing conflicts looked quite scary to me (I'm not an mm expert at all). 😉

Thanks.

I just pushed the latest patchset for 6.0-rc4 here: https://github.com/yuzhaogoogle/linux/tree/for-6.0

**Comment by rsalvaterra** [comment]
> > are you also backporting for 6.0? v14 doesn't apply cleanly, since it's based on mm-unstable (on top of the folio work, I think), and the rebasing conflicts looked quite scary to me (I'm not an mm expert at all). wink
> 
> Thanks.
> 
> I just pushed the latest patchset for 6.0-rc4 here: https://github.com/yuzhaogoogle/linux/tree/for-6.0

That was fast, thank you once again! Will give it a spin quite soon.

**Comment by rsalvaterra** [comment]
> > > are you also backporting for 6.0? v14 doesn't apply cleanly, since it's based on mm-unstable (on top of the folio work, I think), and the rebasing conflicts looked quite scary to me (I'm not an mm expert at all). wink
> > 
> > 
> > Thanks.
> > I just pushed the latest patchset for 6.0-rc4 here: https://github.com/yuzhaogoogle/linux/tree/for-6.0
> 
> That was fast, thank you once again! Will give it a spin quite soon.

Working perfectly, thanks once again!

**Comment by rsalvaterra** [comment]
> The following change to `lru_gen_look_around()` should fix it:
> 
> ```
>  	start = max(pvmw->address & PMD_MASK, pvmw->vma->vm_start);
> -	end = pmd_addr_end(pvmw->address, pvmw->vma->vm_end);
> +	end = min(pvmw->address | ~PMD_MASK, pvmw->vma->vm_end - 1) + 1;
> 
>  	if (end - start > MIN_BATCH_SIZE * PAGE_SIZE) {
> ```

I updated the 6th patch with this fix (and consequently the pull request). However, it's probably a good idea to wait for the definitive backport, as it will surely contain fixes for other corner cases.

**Comment by Ansuel** [comment]
Wow was talking about this some time ago on IRC and here we have a patch... Was on my todo list to implement this on openwrt but never had time to actually implement. We should spam this PR with benchmark out of curiosity... Wonder if we should create a topic on the forum so community can help with the benchmark and stability?

**Comment by PolynomialDivision** [comment]
Nice, it is merged. :D
https://github.com/openwrt/openwrt/commit/05158082f669aeb16a85604620abf7973a5ea807

So we can close? Maybe open a support thread in https://forum.openwrt.org/?

**Comment by Ansuel** [comment]
mhhh wasn't a bit too soon to merge? but i guess this way we can catch all the problems and fix bugs quicker :D

**Comment by PolynomialDivision** [comment]
> @PolynomialDivision i would leave this open to track this?

Of course you can leave it open. :)

**Comment by thuehn** [comment]
Hiho,

Today we have compiled a new trunk image for our CPE510 Freifunk routers with the 5.15 testing kernel and upgraded 67 mesh CPE510 routers ... all working fine ... no real memory benchmark yet, but iperf3 and ssh feels a bit faster/snappier ;)

Greetings Thomas

**Comment by yuzhaogoogle** [comment]
Thanks. @thuehn 

> but iperf3 and ssh feels a bit faster/snappier ;)

It's possible you imagined this :)

But it's also possible this is real -- I saw two relevent reports:

1. _... 1gb of ram ... The conditions were absolutely heavy ... The system was always responsive to SSH shells, which is a great achievement by itself!_ from an Armbian maintainer [here](https://forum.armbian.com/topic/20018-mglru-patches-to-bring-down-kswapd-cpu-usage/?do=findComment&comment=140827)
2. On Android **without** swap files, app launch time reduced by half. From our Android team [here](https://lpc.events/event/16/contributions/1336/) (page 11).

**Comment by rsalvaterra** [comment]
Ok, guys, I'm closing this now, since @dangowrt already merged this version. However, I'll open up a new pull request with the updated backport from upstream, when @yuzhaogoogle gets to it. Thanks to everyone involved!

**Comment by tapper82** [comment]
How do you toggle this on?

**Comment by Ansuel** [comment]
It's on by default

Il Lun 12 Set 2022, 07:25 tapper82 ***@***.***> ha scritto:

**Comment by PolynomialDivision** [comment]
I flashed two mikrotik sxtsq 5 ac, doing a 802.11s connection and found today this in the logs:
```
[   72.629093] ------------[ cut here ]------------
[   72.629199] WARNING: CPU: 1 PID: 8 at backports-5.15.58-1/net/mac80211/mesh_hwmp.c:348 airtime_link_metric_get+0xe0/0x528 [mac80211]
[   72.632869] Modules linked in: nf_flow_table_ipv6 nf_flow_table_ipv4 nf_flow_table_inet ath10k_pci ath10k_core ath nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject_bridge nft_reject nft_redir nft_quota nft_objref nft_numgen nft_nat nft_meta_bridge nft_masq nft_log nft_limit nft_hash nft_flow_offload nft_ct nft_counter nft_chain_nat nf_tables nf_nat nf_flow_table nf_conntrack_bridge nf_conntrack mac80211 cfg80211 nfnetlink nf_reject_ipv6 nf_reject_ipv4 nf_log_syslog nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c compat ghash_arm_ce cmac leds_gpio xhci_plat_hcd xhci_pci xhci_hcd dwc3 dwc3_qcom gpio_button_hotplug crc32c_generic
[   72.678291] CPU: 1 PID: 8 Comm: kworker/u8:0 Not tainted 5.15.67 #0
[   72.700388] Hardware name: Generic DT based system
[   72.706381] Workqueue: phy0 ieee80211_iface_work [mac80211]
[   72.711253] [<c030ce38>] (unwind_backtrace) from [<c0309838>] (show_stack+0x10/0x14)
[   72.716714] [<c0309838>] (show_stack) from [<c0623088>] (dump_stack_lvl+0x40/0x4c)
[   72.724698] [<c0623088>] (dump_stack_lvl) from [<c0321d5c>] (__warn+0xb8/0x114)
[   72.732077] [<c0321d5c>] (__warn) from [<c0321e20>] (warn_slowpath_fmt+0x68/0x78)
[   72.739281] [<c0321e20>] (warn_slowpath_fmt) from [<bf157164>] (airtime_link_metric_get+0xe0/0x528 [mac80211])
[   72.746952] [<bf157164>] (airtime_link_metric_get [mac80211]) from [<bf1571a4>] (airtime_link_metric_get+0x120/0x528 [mac80211])
[   72.756840] [<bf1571a4>] (airtime_link_metric_get [mac80211]) from [<bf1578bc>] (mesh_rx_path_sel_frame+0x310/0x9e4 [mac80211])
[   72.768559] [<bf1578bc>] (mesh_rx_path_sel_frame [mac80211]) from [<bf153294>] (ieee80211_mesh_rx_queued_mgmt+0xe0/0x100 [mac80211])
[   72.779759] [<bf153294>] (ieee80211_mesh_rx_queued_mgmt [mac80211]) from [<bf110d10>] (ieee80211_iface_work+0x324/0x454 [mac80211])
[   72.791915] [<bf110d10>] (ieee80211_iface_work [mac80211]) from [<c033a5f4>] (process_one_work+0x20c/0x484)
[   72.803440] [<c033a5f4>] (process_one_work) from [<c033a8d0>] (worker_thread+0x64/0x5b0)
[   72.813154] [<c033a8d0>] (worker_thread) from [<c0341b3c>] (kthread+0x148/0x164)
[   72.821508] [<c0341b3c>] (kthread) from [<c0300110>] (ret_from_fork+0x14/0x24)
[   72.828862] Exception stack(0xc143dfb0 to 0xc143dff8)
[   72.835905] dfa0:                                     00000000 00000000 00000000 00000000
[   72.841036] dfc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[   72.849195] dfe0: 00000000 00000000 00000000 00000000 00000013 00000000
[   72.857569] ---[ end trace 31d8f9225ff327d1 ]---
```
Not sure if it is because of 5.15 kernel or MGLRU. ;)

**Comment by yuzhaogoogle** [comment]
Thanks.  The warning from `net/mac80211/mesh_hwmp.c:348` seems unrelated.

**Comment by FireBurn** [comment]
Is this likely to be included in the next point release of 22.03?

**Comment by sebastian-de** [comment]
22.03 uses kernel 5.10, so no.
Even if someone backported the patches, I highly doubt that a change like this gets added to a point release. These patches should get their testing in master for a while and are material for the next major release IMHO.

**Pull request closed without merging**
