### PR TITLE
kexec-tools: add kdump scripts util

### PR DESCRIPTION
**Pull request by ptpt52**
This add back kdump scripts to save crashlog or vmcore to disk

### CODE REVIEW

**Comment by dangowrt** [comment]
lgtm
@pprindeville Does this make sense to you as well? I don't remember why the script was removed in first place.

**Comment by pprindeville** [comment]
> lgtm
> @pprindeville Does this make sense to you as well? I don't remember why the script was removed in first place.

That's a question for @neheb.  I didn't really understand the choice myself.  You might want to download the dump and sift through it offline, and not tie up your router with a GDB session while you try to make sense of the crash...

**Review by pprindeville — APPROVED** [review]
LGTM

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
