### PR TITLE
bcm27xx:  add support for linux 5.15

### PR DESCRIPTION
**Pull request by mj22226**
Build tested on raspberry pi 4, using the buildbot config.

### CODE REVIEW

**Comment by graysky2** [comment]
I build with this PR and found I could boot my RPi4B without dmesg regressions.  Good job.

**Comment by graysky2** [comment]
Running this on RPi4B with 5.15.38.  LXC, wireguard, VLANs, various other services all seem nominal.  No errors in dmesg.

**Comment by SquallATF** [comment]
The poe fan driver in linux 5.15 has changed
https://github.com/raspberrypi/linux/commit/5ff73ab47547de0e972b74f2882c339210760e53
[rpi-poe-fan.c](https://github.com/raspberrypi/linux/blob/rpi-5.10.y/drivers/hwmon/rpi-poe-fan.c) driver does not exist in 5.15

**Comment by mj22226** [comment]
@SquallATF I have all the rabased patches here https://github.com/mj22226/linux-stable/tree/bcm27xx on branch bcm27xx
pwm-raspberrypi-poe.c 
https://github.com/mj22226/linux-stable/blob/bcm27xx/drivers/pwm/pwm-raspberrypi-poe.c
i2c fan driver
https://github.com/mj22226/linux-stable/commit/6dda9d99bb90dd35aab35fe56f42c635f6784ce0

**Comment by SquallATF** [comment]
pwm-raspberrypi-poe module name is different, should create a new kmod.
https://github.com/openwrt/openwrt/commit/dcbfbb3771086e40d81f1d806bf0439c8ec9ed38 will not load pwm-raspberrypi-poe module.

**Comment by Noltari** [comment]
Hi @mj22226,

First of all, thanks for the PR.
I'm currently working on v5.15 support and I've relied on some of your changes.

However, I rebased the latest patches myself and tested it on RPi B+ and RPi 3B since you've already tested it on RPI 4B.
I discovered that bcm2708 and bcm2710 targets need a new symbol (CONFIG_NOP_USB_XCEIV) in order to get USBs working. Without that there's no USB/Ethernet on those two targets.

I will push it to latest OpenWrt's master as soon as possible :)

**Comment by Noltari** [comment]
Support for linux v5.15 has been pushed to master (20ea6adbf199097c4f5f591ffee088340630dae4) :)
Thanks!

**Pull request closed without merging**
