### PR TITLE
ramips: Adds preliminary support for RAVPower WD009

### PR DESCRIPTION
**Pull request by jwischka**
Signed-off-by: Jeff Wischkaemper <jeff@wisch.org>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Review by jwischka — COMMENTED** [review]
Forgot to change a couple of values when copying over from the MT7628EVB

**Comment by adrianschmutzler** [comment]
There has been a reorganization in ramips target today. Please:
- update your board.d subfiles since they have been re-sorted
- update your Makefile (mt****/rt****.mk) changes so sorting of devices is correct
- rename your DTS/DTSI files following the scheme soc_vendor_device.dts(i), e.g. mt7620a_tplink_archer-c50-v1.dts (and update includes there if necessary)
- remove `DTS := ...` from Makefile
- add `MTK_SOC` to Makefile (needs to match "soc" in DTS file name), e.g. `MTK_SOC := mt7620a`

Thank you!

Also note that you need to split DEVICE_TITLE into DEVICE_VENDOR etc. due to another recent commit.

**Comment by adrianschmutzler** [comment]
Hi, do you want to proceed with this PR?

If yes, please have another look at https://openwrt.org/submitting-patches and address the changes I posted above.

Despite, I don't think it's a good idea to add "partial" support in OpenWrt master (at least for ramips target). Maybe label this PR [WIP] or similar if you are still working to complete support.

**Comment by adrianschmutzler** [comment]
Closed, since there has been no response by the original author.

Feel free to ask for reopening if the patches have been updated.

**Pull request closed without merging**
