### PR TITLE
ipq40xx: map-ac2200 11-ath10k-caldata symlink fix

### PR DESCRIPTION
**Pull request by protectivedad**
Fix to issue #13603. Creates a symlink to the pre-cal-data just created.

### CODE REVIEW

**Comment by Ansuel** [comment]
are we sure this is correct? first time I see a same BDF for precal and board...

**Comment by protectivedad** [comment]
I am not sure. The pci `ath10k-calibration-variant` (ASUS-MAP-AC2200) mentioned in the DTS doesn't show up in the board-2.bin for the QCA9888. Is it supposed to?

The device works with a dangling symlink, no symlink or a symlink to the pci pre cal data. The messages are always the same:
```
[   11.964540] ath10k_pci 0000:01:00.0: enabling device (0140 -> 0142)
[   11.965281] ath10k_pci 0000:01:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
[   12.745107] ath10k_pci 0000:01:00.0: qca9888 hw2.0 target 0x01000000 chip_id 0x00000000 sub 0000:0000
[   12.745176] ath10k_pci 0000:01:00.0: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 0
[   12.757962] ath10k_pci 0000:01:00.0: firmware ver 10.4-3.9.0.2-00157 api 5 features no-p2p,mfp,peer-flow-ctrl,allows-mesh-bcast,no-ps,iram-recovery crc32 812c4602
[   13.079701] ath10k_pci 0000:01:00.0: board_file api 2 bmi_id 0:17 crc32 ae4cbea5
[   14.987608] ath10k_pci 0000:01:00.0: htt-ver 2.2 wmi-op 6 htt-op 4 cal pre-cal-file max-sta 512 raw 0 hwcrypto 1
[   34.259916] ath10k_pci 0000:01:00.0: Unknown eventid: 36933
```

Maybe the symlink is no longer necessary.

**Comment by protectivedad** [comment]
Oh I just remembered because of the mesh I don't use the CT firmware and drivers. Not sure how that changes things.

**Comment by robimarko** [comment]
Yes, that symlink should disappear unless somebody can explain why it exists as `pre-cal` data is not BDF.

The proper solution would be to first check if there is a need for a custom BDF by comparing the hash from the stock FW BDF against all of the ones in upstream `board-2.bin`.
Then if there is no match package the BDF from stock FW with the current variant and ship that.

**Comment by protectivedad** [comment]
> Yes, that symlink should disappear unless somebody can explain why it exists as `pre-cal` data is not BDF.
> 
> The proper solution would be to first check if there is a need for a custom BDF by comparing the hash from the stock FW BDF against all of the ones in upstream `board-2.bin`. Then if there is no match package the BDF from stock FW with the current variant and ship that.

So I have the stock BDF that the original firmware uses. What can I do to help this process along?

**Comment by robimarko** [comment]
BMI ID 17 is the common 5GHz IPQ4019 ID, I have not seen it used outside of IPQ4019 BDF-s.
To me it looks like you will need to package that stock BDF with the variant so it can be included and this symlink needs to get dropped.

@Ansuel Any insights?

**Comment by Ansuel** [comment]
@robimarko what it's not clear is where is the precal... that should always be there right? for board a generic one can be used (but it would be better to use a more specific one) but precal...

**Comment by protectivedad** [comment]
> @robimarko what it's not clear is where is the precal... that should always be there right? for board a generic one can be used (but it would be better to use a more specific one) but precal...

The precal is there created by the script. It is just the script. It is

**Comment by protectivedad** [comment]
I was trying to change the pr to remove the symlink and bring it back up to the current main. Which messed this up nicely. Is there a way to point the pr to the new branch? Or do I have to open a new pr?

**Comment by Ansuel** [comment]
> The precal is there created by the script pulled from the mtd.

ok then the board file should be extracted from the original firmware and packaged...

**Pull request closed without merging**
