### PR TITLE
gdb: Fix for apk by removing backtick from description 

### PR DESCRIPTION
**Pull request by hnyman**
@Ansuel @aparcar 

One more core repo package fix case for apk:

Remove backtick from gdb description text, as that seems to be recognized as a shell action by compilation with apk, causing error.

Example from test buildbot:
https://downloads.staging.openwrt.org/snapshots/faillogs/mips_24kc/base/gdb/compile.txt
```
 rstrip.sh: /builder/shared-workdir/build/sdk/build_dir/target-aarch64_generic_musl/gdb-15.2/ipkg-aarch64_generic/gdb/usr/bin/gdb: executable
 bash: -c: line 1: unexpected EOF while looking for matching ``'
 bash: -c: line 2: syntax error: unexpected end of file
 make[3]: *** [Makefile:123: /builder/shared-workdir/build/sdk/bin/packages/aarch64_generic/base/gdb-15.2-r1.apk] Error 2
```

Local compilation:
```
 rstrip.sh: /OpenWrt/aarch64/build_dir/target-aarch64_cortex-a53_musl/gdb-15.2/ipkg-aarch64_cortex-a53/gdb/usr/bin/gdb: executable
 bash: -c: line 1: unexpected EOF while looking for matching ``'
 make[2]: *** [Makefile:123: /OpenWrt/aarch64/bin/packages/aarch64_cortex-a53/base/gdb-15.2-r1.apk] Error 2
```
Fix is compile-tested for mediatek/filogic MT6000. 

Looks like apk is really picky about package description text contents, and the possible shell-action-like contents are more eagerly thought to be for parsing as commands.  E.g. quotes/parenthesis mix, backtick, etc.

### CODE REVIEW

**Comment by Ansuel** [comment]
@hnyman it's not a problem of apk... but of makefile... we should escape these char in package-pack.mk than having to fix each package.

**Comment by hnyman** [comment]
Curiously these have gone through in the opkg world, but seem to fail with apk. Something is different.

**Comment by Ansuel** [comment]
@hnyman with opkg we copy the string in a txt file... here we pass the description as args to a command...

**Comment by hnyman** [comment]
Yeah, I though it is something like that. (based on the ddns-scripts yesterday and gdb today)

Looking at the remaining failures at the testing buildbot, gdb is the last error of this kind, currently.

**Comment by geldot** [comment]
> @hnyman it's not a problem of apk... but of makefile... we should escape these char in package-pack.mk than having to fix each package.

@Ansuel  (Untested) Perhaps in `package-pack.mk` do escaping to avoid churn in the broader set of package repos?

```make
sanitize_field = --info "$(1):$(subst \`,'$(subst ‘,'$(subst ’,'$(subst “,'$(subst ”,'$(strip $(2))))))"
```

```make
$(FAKEROOT) $(STAGING_DIR_HOST)/bin/apk mkpkg \
  $(call sanitize_field,description,$(Package/$(1)/description)) \
  $(call sanitize_field,license,$(LICENSE)) \
  ...
```

**Comment by hauke** [comment]
I applied the patch, it looks fine. We can try to fix the general problem in a separate PR.

**Pull request merged**
