### PR TITLE
ramips: add support for TP-Link EC220-G5 v2

### PR DESCRIPTION
**Pull request by namiltd**
TP-Link EC220-G5 v2 is a dual band router with 4 GbE ports Advertised as AC1200 for its 867Mbps (2x2) 5GHz band and 300 Mbps (2x2) 2.4GHz band.

Specs:
- SoC: MediaTek MT7620A
- Ethernet: 4x GbE ports (Realtek RTL8367S)
- Wireless 2.4GHz: MediaTek MT7620A
- Wireless 5GHz: MediaTek MT7612E
- RAM: 64MiB
- ROM: 8MiB (W25Q64BV)
- 2 Buttons (WPS and reset)
- 7 LEDs

Flash instructions via serial console:
1. Rename the factory.bin to to test.bin
2. start a TFTP server from IP address 192.168.0.225 and serve the image named test.bin
3. connect your device to the LAN port
4. power up the router and press 4 on the console to stop the boot process.
5. enter the following commands on the router console tftp 0x80060000 test.bin erase tplink 0x20000 0x7a0000 cp.b 0x80060000 0x20000 0x7a0000 reset

Flash instructions via TFTP:
1. Update orginal firmware of the router to the latest one.
2. Rename openwrt-ramips-mt7620-tplink_ec220-g5-v2-squashfs-tftp-recovery.bin to tp_recovery.bin
3. Change computer IP to 192.168.0.66
4. Run TFTP serwer
5. Start the router with the reset button pressed, the file will be automatically downloaded and after a while the router will restart.
6. After updating, set your computer's IP to DHCP

Since there are problems with the performance of 2.4GHz WiFi for Mediatek MT7620, disable 802.11w Management Frame Protection in Wireless Security.

Discussion: https://forum.openwrt.org/t/support-for-tp-link-ec220-g5

Successor of PR https://github.com/openwrt/openwrt/pull/15140

### CODE REVIEW

**Comment by namiltd** [comment]
The router is very similar to TP-link Archer C5 v4 except for number of ethernet ports, LED and keys settings and WAN port number.

**Comment by namiltd** [comment]
@[svanheule](https://github.com/openwrt/openwrt/commits?author=svanheule) Please take a look at this PR.

**Comment by mdbetancourt** [comment]
does this works for ec220-G5 v3?

**Comment by namiltd** [comment]
The ec220-G5 v3 router has only 4MB flash. This is not enough to run the current version of OpenWRT on it.

**Pull request merged**
