### PR TITLE
ipq40xx: fix pcie wifi on rt-acrh17

### PR DESCRIPTION
**Pull request by ptpt52**
I create this PR for discuss only.

It autually fix the pcie wifi QCA9984 bug on my RT-ACRH17 router

without this patch the 5G wifi hang after a while of running

anyway it also fix some indent on the DTS

### CODE REVIEW

**Comment by ptpt52** [comment]
without this patch, the 5G wifi on RT-ACRH17(pcie QCA9984) hang
dmesg:

> ath10k_pci 0000:01:00.0: failed to send pdev bss chan info request
ath10k_pci 0000:01:00.0: failed to recalculate rts/cts prot for vdev 0: -11

**Comment by ptpt52** [comment]
I don't know the cause of the problem, so I can't say anything, just think it's a bug report. I compared the historical changes of dts. Revert these changes to the old version, the problem is solved
it is something related to this commit https://github.com/openwrt/openwrt/commit/95672e04335ea0d7d8f468cec8f63d593cc6ede6

**Comment by robimarko** [comment]
This will never get merged.
And also, RT-ACRH17 isnt even supported.

**Comment by ptpt52** [comment]
I create this PR for discuss only. as says in first comment

**Comment by mkresin** [comment]
Please use the [mailing list](https://openwrt.org/contact) for discussions.

**Pull request closed without merging**
