### PR TITLE
toolchain: gcc: add support for GCC 13

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Run-Tested on Banana Pi R64.

**Comment by Ansuel** [comment]
wow you are fast AHAHAHHA

btw we should really consider start enabling those static analyzer feature... with gcc12 they were good now with gcc13 they are on part with clang i think

**Comment by PolynomialDivision** [comment]
@Ansuel haha, I just knew that this week the release should happen and was a bit excited. But I just checked yesterday and it was there. ^^

If you want, you can take over the PR. :)

I made a config option to use fanalyzer. Not sure if that's what you requested?
I also saw that @dhewg wants to use `-gz=zstd` like described here:
https://github.com/openwrt/openwrt/commit/acc8c2d829fb5e0e0b2495d720e058f91ea164b0

**Comment by Ansuel** [comment]
Add that in s different commit... GCC 13 won't be default so I guess we can enable all this feature by default
Zstd can be enabled without a flag but I think we should check how to implement it with the host tool dependency

**Comment by PolynomialDivision** [comment]
> Add that in s different commit... GCC 13 won't be default so I guess we can enable all this feature by default

I already added this in a separate commit? Sorry, I don't understand what you request.

**Comment by Ansuel** [comment]
Was referring to the zstd. The static analyzer is good

Il Ven 28 Apr 2023, 09:50 Nick Hainke ***@***.***> ha scritto:

**Comment by PolynomialDivision** [comment]
```
/home/nick/openwrt/build_dir/toolchain-aarch64_cortex-a53_gcc-13.1.0_musl/gcc-13.1.0/libitm/beginend.cc: In member function 'bool GTM::gtm_thread::trycommit()':
/home/nick/openwrt/build_dir/toolchain-aarch64_cortex-a53_gcc-13.1.0_musl/gcc-13.1.0/libitm/beginend.cc:589:17: error: use of NULL 'cp' where non-null expected [CWE-476] [-Werror=analyzer-null-argument]
  589 |       cp->commit(this);
      |       ~~~~~~~~~~^~~~~~
  'bool GTM::gtm_thread::trycommit()': events 1-8
    |
    |  574 | GTM::gtm_thread::trycommit ()
    |      | ^~~
    |      | |
    |      | (1) entry to 'GTM::gtm_thread::trycommit'
    |......
    |  579 |   if (nesting > 0 && (parent_txns.size() == 0 ||
    |      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |                   |                           |
    |      |                   |                           (4) following 'false' branch...
    |      |                   (2) following 'false' branch...
    |  580 |       nesting > parent_txns[parent_txns.size() - 1].nesting))
    |      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |                                                   |
    |      |                                                   (3) ...to here
    |......
    |  583 |   if (nesting > 0)
    |      |   ~~
    |      |   |
    |      |   (5) ...to here
    |      |   (6) following 'true' branch...
    |......
    |  587 |       gtm_transaction_cp *cp = parent_txns.pop();
    |      |       ~~~~~~~~~~~~~~~~~~       ~~~~~~~~~~~~~~~~~
    |      |       |                                       |
    |      |       (7) ...to here                          (8) calling 'GTM::vector<GTM::gtm_transaction_cp>::pop' from 'GTM::gtm_thread::trycommit'
    |
    +--> 'T* GTM::vector<T, alloc_separate_cl>::pop() [with T = GTM::gtm_transaction_cp; bool alloc_separate_cl = true]': events 9-10
           |
           |/home/nick/openwrt/build_dir/toolchain-aarch64_cortex-a53_gcc-13.1.0_musl/gcc-13.1.0/libitm/containers.h:113:12:
           |  113 |   iterator pop() {
           |      |            ^~~
           |      |            |
           |      |            (9) entry to 'GTM::vector<GTM::gtm_transaction_cp>::pop'
           |  114 |     if (likely(m_size > 0))
           |      |     ~~      
           |      |     |
           |      |     (10) following 'false' branch...
           |
         'T* GTM::vector<T, alloc_separate_cl>::pop() [with T = GTM::gtm_transaction_cp; bool alloc_separate_cl = true]': event 11
           |
           |cc1plus:
           | (11): ...to here
           |
    <------+
    |
  'bool GTM::gtm_thread::trycommit()': events 12-13
    |
    |/home/nick/openwrt/build_dir/toolchain-aarch64_cortex-a53_gcc-13.1.0_musl/gcc-13.1.0/libitm/beginend.cc:587:47:
    |  587 |       gtm_transaction_cp *cp = parent_txns.pop();
    |      |                                ~~~~~~~~~~~~~~~^~
    |      |                                               |
    |      |                                               (12) returning to 'GTM::gtm_thread::trycommit' from 'GTM::vector<GTM::gtm_transaction_cp>::pop'
    |  588 |       commit_allocations(false, &cp->alloc_actions);
    |  589 |       cp->commit(this);
    |      |       ~~~~~~~~~~~~~~~~                         
    |      |                 |
    |      |                 (13) argument 'this' ('cp') NULL where non-null expected
    |
/home/nick/openwrt/build_dir/toolchain-aarch64_cortex-a53_gcc-13.1.0_musl/gcc-13.1.0/libitm/beginend.cc:450:1: note: argument 'this' of 'void GTM::gtm_transaction_cp::commit(GTM::gtm_thread*)' must be non-null
  450 | GTM::gtm_transaction_cp::commit(gtm_thread* tx)
      | ^~~
cc1plus: all warnings being treated as errors
make[7]: *** [Makefile:678: beginend.lo] Error 1
```

**Comment by PolynomialDivision** [comment]
I think enabling zstd causes some issues:
```
[    1.271343] Alternate GPT is invalid, using primary GPT.
[    1.277577] FIT: Selected configuration: "config-mt7622-bananapi-bpi-r64-pcie1" (OpenWrt bananapi_bpi-r64 with mt7622-bananapi-bpi-r64-pcie1)
[    1.290302] FIT:           kernel sub-image 0x00001000..0x0050553f "kernel-1" (ARM64 OpenWrt Linux-5.15.108) 
[    1.300229] FIT:          flat_dt sub-image 0x00506000..0x0050e0d8 "fdt-1" (ARM64 OpenWrt bananapi_bpi-r64 device tree blob) 
[    1.311546] FIT:          flat_dt sub-image 0x0050f000..0x0050f11a "fdt-mt7622-bananapi-bpi-r64-pcie1" (ARM64 OpenWrt bananapi_bpi-r64 device tree overlay mt7622-bananapi-bpi-r64-pcie1) 
[    1.328159] FIT:          flat_dt sub-image 0x00510000..0x0051020f "fdt-mt7622-bananapi-bpi-r64-sata" (ARM64 OpenWrt bananapi_bpi-r64 device tree overlay mt7622-bananapi-bpi-r64-sata) 
[    1.341633] mtk-pcie 1a143000.pcie: PCI host bridge to bus 0000:00
[    1.344591] FIT:       filesystem sub-image 0x00511000..0x00966fff "rootfs-1" (ARM64 OpenWrt bananapi_bpi-r64 rootfs) 
[    1.350758] pci_bus 0000:00: root bus resource [bus 00-ff]
[    1.361449] FIT: selecting configured loadable "rootfs-1" to be root filesystem
[    1.366921] pci_bus 0000:00: root bus resource [mem 0x20000000-0x27ffffff]
[    1.374237]  mmcblk0: p1 p2 p3 p4 p65(rootfs-1) p66(rootfs_data) p128

...

[    1.578490] pcieport 0000:00:00.0: PME: Signaling with IRQ 148
[    1.584435] pcieport 0000:00:00.0: saving config space at offset 0x0 (reading 0x325814c3)
[    1.592612] pcieport 0000:00:00.0: saving config space at offset 0x4 (reading 0x100006)
[    1.600623] pcieport 0000:00:00.0: saving config space at offset 0x8 (reading 0x6040000)
[    1.608713] pcieport 0000:00:00.0: saving config space at offset 0xc (reading 0x10000)
[    1.616628] pcieport 0000:00:00.0: saving config space at offset 0x10 (reading 0xc)
[    1.624282] pcieport 0000:00:00.0: saving config space at offset 0x14 (reading 0x0)
[    1.631932] pcieport 0000:00:00.0: saving config space at offset 0x18 (reading 0x40010100)
[    1.640194] pcieport 0000:00:00.0: saving config space at offset 0x1c (reading 0x4200000)
[    1.648368] pcieport 0000:00:00.0: saving config space at offset 0x20 (reading 0x20002000)
[    1.656630] pcieport 0000:00:00.0: saving config space at offset 0x24 (reading 0x0)
[    1.664283] pcieport 0000:00:00.0: saving config space at offset 0x28 (reading 0x0)
[    1.671932] pcieport 0000:00:00.0: saving config space at offset 0x2c (reading 0x0)
[    1.679585] pcieport 0000:00:00.0: saving config space at offset 0x30 (reading 0x0)
[    1.687240] pcieport 0000:00:00.0: saving config space at offset 0x34 (reading 0x50)
[    1.694980] pcieport 0000:00:00.0: saving config space at offset 0x38 (reading 0x0)
[    1.702629] pcieport 0000:00:00.0: saving config space at offset 0x3c (reading 0x20194)
[    1.711148] mtk-pcie 1a145000.pcie: host bridge /pcie@1a145000 ranges:
[    1.717719] mtk-pcie 1a145000.pcie: Parsing ranges property...
[    1.723560] mtk-pcie 1a145000.pcie:      MEM 0x0028000000..0x002fffffff -> 0x0028000000
[    1.942976] mtk-pcie 1a145000.pcie: Port1 link down
[    1.948063] mtk-pcie 1a145000.pcie: PCI host bridge to bus 0001:00
```

**Comment by dhewg** [comment]
I'd have added a config knob to enable zlib/zstd for packages only. I'm not sure if enabling it unconditionally everywhere is a good idea.
Bit that's a different topic to me anyway, let's keep this PR just about the new mayor version?

**Comment by timocapa** [comment]
https://github.com/openwrt/openwrt/pull/12489/commits/fcd5ff5c5b4c0f0012ad4246731a96d928c01647 seems to mess with menuconfig/nconfig, showing entries of other pages on the main screen

image

**Comment by timocapa** [comment]
Compile and run tested on:

ramips/mt7621, lantiq/xrx200 and ath79/generic

However without fcd5ff5c5b4c0f0012ad4246731a96d928c01647 and e2fdac3f0d70070326dad1f5ef8a569ea011153f

**Comment by PolynomialDivision** [comment]
I deleted now the other commits, so we can already merge the gcc 13 support, @Ansuel ? ;)

I saved the other commits here:
https://github.com/PolynomialDivision/openwrt/commits/gcc-13-save-new

**Comment by rsalvaterra** [comment]
Please, don't. Wait for 13.2. There's a [nasty code generation bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109585) which was recently found, affecting versions 10.2+.

**Comment by PolynomialDivision** [comment]
> Please, don't. Wait for 13.2. There's a [nasty code generation bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109585) which was recently found, affecting versions 10.2+. It's fixed in master (and already backported), but didn't make it before the 13.1 cut.

What about just back-porting the patch?
https://github.com/gcc-mirror/gcc/commit/bb406a6aea336966681927a27f54ee89c4fd4ea1

**Comment by rsalvaterra** [comment]
> What about just back-porting the patch? [gcc-mirror/gcc@bb406a6](https://github.com/gcc-mirror/gcc/commit/bb406a6aea336966681927a27f54ee89c4fd4ea1)

Sure, that would be fine.

**Comment by PolynomialDivision** [comment]
Updated the branch already. I still need to test this.

**Comment by anomeome** [comment]
[Build error](https://termbin.com/ndhc) target mvebu

**Comment by PolynomialDivision** [comment]
> [Build error](https://termbin.com/ndhc) target mvebu

Maybe this can fix it:
https://github.com/torvalds/linux/commit/7c00621dcaeea206d7489b3e8b50b1864841ae69

**Comment by robimarko** [comment]
> > [Build error](https://termbin.com/ndhc) target mvebu
> 
> Maybe this can fix it: [torvalds/linux@7c00621](https://github.com/torvalds/linux/commit/7c00621dcaeea206d7489b3e8b50b1864841ae69)
> 
> Edit: No, same error. :/

mvebu A9 compiles fine for me with your last push

**Comment by PolynomialDivision** [comment]
> > > [Build error](https://termbin.com/ndhc) target mvebu
> > 
> > 
> > Maybe this can fix it: [torvalds/linux@7c00621](https://github.com/torvalds/linux/commit/7c00621dcaeea206d7489b3e8b50b1864841ae69)
> > Edit: No, same error. :/
> 
> mvebu A9 compiles fine for me with your last push

Can you double check that you really compiled with gcc-13? I tested again today but still fails.

**Comment by robimarko** [comment]
Well, guess who forgot to select GCC13.
I am hitting the same error, and it seems to be hitting 32 bit ARM as ipq806x has the same issue if AHCI kmod is included

**Comment by PolynomialDivision** [comment]
Any idea on which mailing list we can look for a patch?

**Comment by rtlhq** [comment]
> Any idea on which mailing list we can look for a patch?

https://lkml.iu.edu/hypermail/linux/kernel/2212.0/01028.html

**Comment by PolynomialDivision** [comment]
Works for me. :) I think this is ready to be merged @Ansuel ;)

**Comment by robimarko** [comment]
Makes the kernel compile on ipq806x, I did find an regression in regards to SHA512 kmod but that is unrelated to GCC.

**Comment by anomeome** [comment]
[new error](https://termbin.com/j1y7) for me.

**Comment by anomeome** [comment]
From a clean build. Does not matter where it gets shaken out, probably get more eyeballs once pushed to master

**Pull request merged**
