### PR TITLE
u-boot.mk: add LOCALVERSION (explicitly specify OpenWrt build)

### PR DESCRIPTION
**Pull request by BKPepe**
For debugging purposes, we need to know if users are using modified
U-boot versions or not. Currently, the U-boot version is somehow
stripped. This is a little bit problematic when there are
backported/wip/to-upstream patches.

To make it more confusing, there was (before this commit) two U-boot
versioning. U-boot compiled by OpenWrt build bots are missing ``Build:``
This is also the case when the U-boot is compiled locally.

Example:
```
U-Boot SPL 2022.01 (Jan 27 2022 - 00:24:34 +0000)
U-Boot 2022.01 (Jan 27 2022 - 00:24:34 +0000)
```

On the other hand, if you run full build, you can at least see, where it
was compiled. Notice added ``Build:``.

Example:
```
U-Boot 2022.01 (Jan 27 2022 - 00:24:34 +0000), Build: jenkins-turris-os-packages-burstlab-omnia-216
```

In both cases, it is not clear to U-boot developers if it is an unmodified
build. This is also caused that there is a missing ``.git`` file from
U-boot folder, and so there is no history. It leads to that it can not
contain suffix ``-dirty`` (uncommitted modifications) or even something
else like number of commits, etc. [1]

When U-boot is compiled as it should be, the version should look like
this: ``U-Boot 2022.04-rc1-01173-g278195ea1f (Feb 11 2022 - 14:46:50 +0100)``
The date is not changed daily when there are new OpenWrt builds.

This commit adds OpenWrt specific version, which could be verified by
using strings.

```
$ strings bin/targets/mvebu/cortexa9/u-boot-omnia/u-boot-spl.kwb | grep -E "OpenWrt*"
U-Boot SPL 2022.01-OpenWrt-r18942+54-cbfce92367 (Feb 21 2022 - 13:17:34 +0000)
arm-openwrt-linux-muslgnueabi-gcc (OpenWrt GCC 11.2.0 r18942+54-cbfce92367) 11.2.0
2022.01-OpenWrt-r18942+54-cbfce92367
U-Boot 2022.01-OpenWrt-r18942+54-cbfce92367 (Feb 21 2022 - 13:17:34 +0000)
```

[1] https://u-boot.readthedocs.io/en/latest/develop/version.html

cc: @pali, @Cynerd

### CODE REVIEW

**Comment by BKPepe** [comment]
Shall I do something about failing CI? It fails because of: 
```Commit subject line MUST start with '<area>: ' (u-boot.mk: add LOCALVERSION (explicitly specify OpenWrt build))```, however, looking through [Git history](https://github.com/openwrt/openwrt/commits/master/include/u-boot.mk), I can see that no one used ``include/u-boot.mk``.

**Comment by aparcar** [comment]
Patch looks good to me.

Regarding CI, I need to improve the handling of dots in the "area"

**Comment by aparcar** [comment]
@neheb this doesn't compile on macOS (unrelated to this patch), ideas how to fix it?

<details>
make[3]: Entering directory '/Users/user/src/openwrt/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/u-boot-omnia/u-boot-2022.01'
  HOSTCC  tools/env/embedded.o
  HOSTCC  tools/lib/sha1.o
  HOSTLD  tools/envcrc
ld: warning: directory not found for option '-L/Users/user/src/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/host/lib'
  HOSTCC  tools/lib/crc8.o
  HOSTLD  tools/gen_ethaddr_crc
ld: warning: directory not found for option '-L/Users/user/src/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/host/lib'
  HOSTLD  tools/mkenvimage
ld: warning: directory not found for option '-L/Users/user/src/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/host/lib'
  HOSTCC  tools/aisimage.o
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:13:
include/linux/types.h:146:9: error: unknown type name '__u64'; did you mean '__s64'?
typedef __u64 __bitwise __le64;
        ^
/Users/user/src/openwrt/openwrt/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:13:
include/linux/types.h:147:9: error: unknown type name '__u64'; did you mean '__s64'?
typedef __u64 __bitwise __be64;
        ^
/Users/user/src/openwrt/openwrt/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:125:42: error: unknown type name '__u64'; did you mean '__s64'?
static __inline__ __attribute__((const)) __u64 __fswab64(__u64 x)
                                         ^
/Users/user/src/openwrt/openwrt/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:125:58: error: unknown type name '__u64'; did you mean '__s64'?
static __inline__ __attribute__((const)) __u64 __fswab64(__u64 x)
                                                         ^
/Users/user/src/openwrt/openwrt/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:130:12: error: use of undeclared identifier '__u64'
        return (((__u64)__swab32(l)) << 32) | ((__u64)(__swab32(h)));
                  ^
include/linux/byteorder/swab.h:130:42: error: use of undeclared identifier '__u64'
        return (((__u64)__swab32(l)) << 32) | ((__u64)(__swab32(h)));
                                                ^
include/linux/byteorder/swab.h:135:19: error: unknown type name '__u64'; did you mean '__s64'?
static __inline__ __u64 __swab64p(const __u64 *x)
                  ^
/Users/user/src/openwrt/openwrt/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:135:41: error: unknown type name '__u64'; did you mean '__s64'?
static __inline__ __u64 __swab64p(const __u64 *x)
                                        ^
/Users/user/src/openwrt/openwrt/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
        return __arch__swab64p(x);
               ^
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:89:24: note: expanded from macro '__swab64'
(__builtin_constant_p((__u64)(x)) ? \
                       ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:32:4: note: expanded from macro '___swab64'
        ((__u64)( \
          ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:33:4: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x00000000000000ffULL) << 56) | \
                 ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:33:13: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x00000000000000ffULL) << 56) | \
                          ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:33:26: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x00000000000000ffULL) << 56) | \
                                       ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:34:4: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x000000000000ff00ULL) << 40) | \
                 ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:34:13: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x000000000000ff00ULL) << 40) | \
                          ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:34:26: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x000000000000ff00ULL) << 40) | \
                                       ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:35:4: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x0000000000ff0000ULL) << 24) | \
                 ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:35:13: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x0000000000ff0000ULL) << 24) | \
                          ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:35:26: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x0000000000ff0000ULL) << 24) | \
                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[4]: *** [scripts/Makefile.host:112: tools/aisimage.o] Error 1
make[3]: *** [Makefile:1810: tools] Error 2
make[3]: Leaving directory '/Users/user/src/openwrt/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/u-boot-omnia/u-boot-2022.01'
make[2]: *** [Makefile:84: /Users/user/src/openwrt/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/u-boot-omnia/u-boot-2022.01/.built] Error 2
make[2]: Leaving directory '/Users/user/src/openwrt/openwrt/package/boot/uboot-mvebu'
time: package/boot/uboot-mvebu/omnia/compile#0.67#0.47#1.30
    ERROR: package/boot/uboot-mvebu failed to build (build variant: omnia).
make[1]: *** [package/Makefile:110: package/boot/uboot-mvebu/compile] Error 1
make[1]: Leaving directory '/Users/user/src/openwrt/openwrt'
make: *** [/Users/user/src/openwrt/openwrt/include/toplevel.mk:230: package/uboot-mvebu/compile] Error 2
</details>

**Comment by neheb** [comment]
That sounds unrelated. It looks like host headers are leaking for some reason. Btw you should use gist when copy/pasting that.

**Comment by BKPepe** [comment]
v1 → v2:

rebased on the latest changes in the master branch
   - should fix the failing CI

**Comment by neheb** [comment]
@aparcar both uboot-mediatek and uboot-sunxi have a 260-add-missing-type-u64.patch file. Maybe also needed here.

**Comment by BKPepe** [comment]
Guys, it would help if you moved your discussion elsewhere since it is not related to my changes, which I propose. For example, you can use GitHub issues.

Regarding adding new patches, please, always send them upstream first. Otherwise, we will end up with patches that we don't know what they are doing and why we need to care for them forever. That leads to no one wanting to deal with them anymore. That is what happened with ```service/ppp``` here.

On the other hand, all the patches I added for ``uboot-mvebu`` are already merged upstream. It is always better for upstream developers to troubleshoot and debug issues if there are no patches instead of looking to the code they don't know. It is also possible that the patch is wrong and causing multiple issues.

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
@BKPepe it's tangentially related. @aparcar tests on macOS. I'll open a different PR for his issue. As far as upstream is concerned, the patch is a hack. I don't know of a proper way to upstream it.

**Comment by BKPepe** [comment]
As we both know, compiling on macOS could be problematic.

- https://github.com/openwrt/packages/issues/17669
- https://github.com/openwrt/packages/issues/17423

While looking at [OpenWrt documentation](https://openwrt.org/docs/guide-developer/toolchain/buildroot.exigence.macosx) that says that any native GNU/Linux distribution is recommended, and my point is that my change is unrelated to the build failure on macOS.

If the patch is hack, it should be reported to upstream developers to look. They can be very helpful if they know about it, which is the important thing, I'd say. Here is their GitLab repository: https://source.denx.de/u-boot/u-boot/-/issues

**Comment by aparcar** [comment]
Thanks for this patch!

**Comment by BKPepe** [comment]
For reference merged as commit https://github.com/openwrt/openwrt/commit/d6aa9d9e071d9f23ed26f5142991bc66aefe20f5

Shall I send pull request to OpenWrt 21.02 to cherry-pick this or do we prefer to wait a little bit?

**Pull request closed without merging**
