### PR TITLE
ath25: add 6.1 kernel

### PR DESCRIPTION
**Pull request by robimarko**
Add 6.1 kernel as the testing kernel for ath25.

Note that I don't have any boards that are supported so this is compile only.

### CODE REVIEW

**Comment by Leo-PL** [comment]
I'll try building in coming days.

**Comment by robimarko** [comment]
@Leo-PL Any chance you gave it a go?

**Comment by Leo-PL** [comment]
I ran the builds - they work but image is too big for Ubiquiti devices. I have to try running it on one device yet, but I doubt I can do more than booting initramfs as of now. I'll try to do that - if the time permits - today, if not, sometime during next week.

**Comment by robimarko** [comment]
Well, I mean 5.15 was also a stretch due to size but if it cannot even be booted, what is the point of even keeping the target

**Comment by Leo-PL** [comment]
I tried on a stock DWL-3200AP - with just 16 megs of RAM the kernel barely boots:
```
ar531x rev 0x00005850 firmware startup...
SDRAM TEST...PASSED



  WAP-G02A  Boot Procedure                       V1.0
---------------------------------------------------------
  Start ..Boot.B14..

Atheros AR5001AP default version 3.0.0.43A


 1
[Boot]: $ae(1,0)hai:openwrt-ath25-generic-generic-kernel.elf h=10.0.0.24 e=10.0.0.254:0xffffff00 f=0x80
Attached TCP/IP interface to ae1.
Attaching network interface lo0... done.
Loading... 55027960x80fbb650 (tNetTask): arp info overwritten for 0a000018 by e4:aa:ea:59:06:fd
0x80fbb650 (tNetTask): arp info overwritten for 0a000018 by d4:be:d9:ff:19:b7

Starting at 0x8040f6e0...

[    0.000000] Linux version 5.15.148 (lechu@gigabyte-b550m) (mips-openwrt-linux-musl-gcc (OpenWrt GCC 12.3.0 r0-3739e38706ad) 12.3.0, GNU ld (GNU Binutils) 2.40.0) #0 Sun Feb 25 11:33:42 2024
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 0001800a (MIPS 4Kc)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 16kB, VIPT, 4-way, linesize 16 bytes.
[    0.000000] Primary data cache 16kB, 4-way, VIPT, no aliases, linesize 16 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000000ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000000ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000000ffffff]
[    0.000000] Built 1 zonelists, mobility grouping off.  Total pages: 4064
[    0.000000] Kernel command line: console=ttyS0,9600 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.000000] Inode-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 10824K/16384K available (3923K kernel code, 562K rwdata, 536K rodata, 152K init, 193K bss, 5560K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 256
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 20774570075 ns
[    0.000015] sched_clock: 32 bits at 92MHz, resolution 10ns, wraps every 23342213114ns
[    0.094487] Calibrating delay loop... 183.70 BogoMIPS (lpj=918528)
[    0.247699] pid_max: default: 32768 minimum: 301
[    0.310937] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.397832] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.522745] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.639863] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.733216] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.873834] clocksource: Switched to clocksource MIPS
[    0.948229] NET: Registered PF_INET protocol family
[    1.007739] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    1.099424] tcp_listen_portaddr_hash hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    1.200056] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    1.292604] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    1.384208] TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    1.468318] TCP: Hash tables configured (established 1024 bind 1024)
[    1.545270] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    1.623083] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    1.709135] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    1.776754] PCI: CLS 0 bytes, default 16
[    1.823479] Radio config found at offset 0x10000 (0x100)
[    1.959318] workingset: timestamp_bits=30 max_order=12 bucket_order=0
[    2.085192] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    2.154596] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    2.284159] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    2.381381] serial8250: ttyS0 at MMIO 0x1c000000 (irq = 9, base_baud = 2875000) is a 16550A
[    2.481025] printk: console [ttyS0] enabled
[    2.481025] printk: console [ttyS0] enabled
[    2.580752] printk: bootconsole [early0] disabled
[    2.580752] printk: bootconsole [early0] disabled
[    2.701707] physmap-flash physmap-flash.0: physmap platform flash device: [mem 0x1e000000-0x1e7fffff]
[    2.812939] physmap-flash.0: Found 1 x16 devices at 0x0 in 8-bit bank. Manufacturer ID 0x0000c2 Chip ID 0x0000cb
[    2.935363] Amd/Fujitsu Extended Query Table at 0x0040
[    2.997376]   Amd/Fujitsu Extended Query version 1.1.
[    3.058326] number of CFI chips: 1
[    3.125446] Searching for RedBoot partition table in physmap-flash.0 at offset 0x7d0000
[    3.241216] CPU 0 Unable to handle kernel paging request at virtual address 055bfc10, epc == 8028f754, ra == 8028f738
[    3.368747] Oops[#1]:
[    3.396084] CPU: 0 PID: 1 Comm: swapper Not tainted 5.15.148 #0
[    3.467002] $ 0   : 00000000 1000c000 055bfc00 80831c54
[    3.529705] $ 4   : 00010000 00000003 00000001 00000000
[    3.592419] $ 8   : 00000001 ffffffff ffffffff ffffffff
[    3.655130] $12   : ffffffff 000008c4 00000000 ffffffff
[    3.717840] $16   : 80895400 8045578c 007d0000 00000000
[    3.780552] $20   : c0047000 00010000 00000000 804547cc
[    3.843266] $24   : 00000000 00000000                  
[    3.905979] $28   : 80830000 80831c18 80450000 8028f738
[    3.968691] Hi    : 00000000
[    4.003114] Lo    : 00000000
[    4.037539] epc   : 8028f754 0x8028f754
[    4.083507] ra    : 8028f738 0x8028f738
[    4.129476] Status: 1000c003 KERNEL EXL IE 
[    4.179706] Cause : 10800008 (ExcCode 02)
[    4.227648] BadVA : 055bfc10
[    4.262075] PrId  : 0001800a (MIPS 4Kc)
[    4.307941] Modules linked in:
[    4.344547] Process swapper (pid: 1, threadinfo=(ptrval), task=(ptrval), tls=00000000)
[    4.439400] Stack : 636d646c 808a9a80 007d0000 00000000 00010000 80831c54 c0047000 809bed80
[    4.539754]         809be500 80520000 00000006 80011420 80802700 00000000 00000000 00010000
[    4.640115]         80521218 8045578c 00000000 00000000 80895400 804732d8 00000000 804547cc
[    4.740474]         80450000 8028d318 00001000 80831c94 00000000 80824000 80455788 00000000
[    4.840836]         00000000 00000000 80895400 00000000 00000000 80455788 00000000 00000000
[    4.941196]         ...
[    4.970524] Call Trace:
[    4.970626] [<8028d318>] 0x8028d318
[    5.041695] [<8028a0ac>] 0x8028a0ac
[    5.083481] [<80291b20>] 0x80291b20
[    5.125294] [<80297ce4>] 0x80297ce4
[    5.167099] [<8019d9a8>] 0x8019d9a8
[    5.208912] [<8052a094>] 0x8052a094
[    5.250710] [<8027e930>] 0x8027e930
[    5.292525] [<8027c6c0>] 0x8027c6c0
[    5.334337] [<8027ca7c>] 0x8027ca7c
[    5.376135] [<8027ce74>] 0x8027ce74
[    5.417935] [<8027cd4c>] 0x8027cd4c
[    5.459756] [<8027cf74>] 0x8027cf74
[    5.501555] [<8027a6f8>] 0x8027a6f8
[    5.543368] [<8027ce74>] 0x8027ce74
[    5.585170] [<8027a770>] 0x8027a770
[    5.626980] [<80224cf4>] 0x80224cf4
[    5.668799] [<8027b944>] 0x8027b944
[    5.710594] [<8052a094>] 0x8052a094
[    5.752421] [<8027d6a4>] 0x8027d6a4
[    5.794215] [<8053ca98>] 0x8053ca98
[    5.836020] [<8053cca4>] 0x8053cca4
[    5.877824] [<8053ccc8>] 0x8053ccc8
[    5.919636] [<800415d0>] 0x800415d0
[    5.961445] [<80275b9c>] 0x80275b9c
[    6.003262] [<8007c794>] 0x8007c794
[    6.045089] [<8052b02c>] 0x8052b02c
[    6.086878] [<8052a094>] 0x8052a094
[    6.128693] [<8040f854>] 0x8040f854
[    6.170489] [<8040f834>] 0x8040f834
[    6.212289] [<80042fc8>] 0x80042fc8
[    6.254185] 
[    6.271980] Code: 16a20177  00111200  02821021 <8c420010> 26b1ffff  02228824  00118a02  0015b202  02d11021 
[    6.389083] 
[    6.407573] ---[ end trace af5ec09d01203d2a ]---
[    6.463226] Kernel panic - not syncing: Fatal exception
[    6.525884] Rebooting in 1 seconds..

```
With the requirement to flash- and RAM-mod device to run that, I'm in favor of letting it go - most of ath25 devices are 2/16M anyway, and can be bumped to 8/32 at best.

**Comment by robimarko** [comment]
If that is the case, think I will just close this PR and make one to drop the target because there is no point in it if its not bootable

**Comment by Leo-PL** [comment]
I just noticed that I forgot to enable the testing kernel build in config and built 5.15. But there is no point to keep this on life support either way.

**Comment by robimarko** [comment]
That makes it even worse :(, I made a PR to drop it and then it will be moved to https://github.com/openwrt/targets so its archived in case anybody ever needs it.

https://github.com/openwrt/openwrt/pull/14793

**Pull request closed without merging**
