### PR TITLE
owipcalc: separate in client and lib

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Separate owipcalc in client and lib part. Owipcalc brings a lot of nice functionality with it, e.g. parsing and calculating prefixes.

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
I use that here:
https://github.com/PolynomialDivision/babeld-ids/tree/use-owipcalc-lib

**Comment by adschm** [comment]
This package looks to me like a candidate for the packages feed ...

@jow- Opinion?

**Comment by PolynomialDivision** [comment]
Maybe compiling owipcalc with a shared lib causes performance degradation, or? Not sure if that could be problematic.

**Comment by PolynomialDivision** [comment]
> This package looks to me like a candidate for the packages feed ...
> 
> @jow- Opinion?

If we move owipcalc, I directly would move `maccalc`, too.

**Comment by adschm** [comment]
Hi, I've moved owipcalc and maccalc to packages, so you will need to open a PR there.

Sorry, but while this might look inconvenient at first, you probably will receive more feedback and get merged quicker there for stuff like this.

Thanks for working at this tool, I found out about it only due to your patches :-)

**Pull request closed without merging**
