### PR TITLE
kernel: generic: fix problem with w1-gpio-custom

### PR DESCRIPTION
**Pull request by CHKDSK88**
In boards with fdt is impossible to use kmod-w1-gpio-custom.
w1-gpio-custom create platform structure for w1-gpio module,
but if board use fdt, data is ignored in w1-gpio probe.

This workaround fix the problem.

Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
@CHKDSK88 why is this in hacks folder ? it should go into pending and you should really send the fix upstream

**Comment by CHKDSK88** [comment]
@blogic 

Patch is proper only for kernels <v4.15-rc2.

I can't send this patch to upstream, because driver was changed:
https://github.com/torvalds/linux/commit/e0fc62a6552f3d9c21e73cc65844f9aad1892cf7#diff-bb6f7f44e3a84c675e41af41b2b37376

The problem is still unsolved, but it needs different patch for kernels >=4.15.

Could you give me some advice, how do it properly?

**Comment by CHKDSK88** [comment]
@blogic 

Now is in pending and in proper format. I send it to maintainers from script and to stable ML.

**Comment by CHKDSK88** [comment]
I think, that this fix:

https://dev.openwrt.org/ticket/21889
https://dev.openwrt.org/ticket/21965

**Comment by CHKDSK88** [comment]
@blogic 

Is possible to add this patch before 18.03/04 release?

**Pull request closed without merging**
