### PR TITLE
imx: pico-pi-imx7d: support CPU frequency scaling

### PR DESCRIPTION
**Pull request by Leo-PL**
This series enables symbols needed to make CPU frequency scaling and thermal zone support on pico-pi-imx7d devkit. When adding initial support, CONFIG_REGULATOR_PFUZE100 was missing from cortexa7 subtarget, together with CONFIG_CPU_FREQ_THERMAL which are required for frequency scaling and thermal throttling support. The other required dependency is the `cpu-supply` nodes added to both cores, which were present in downstream kernels in "Android Things" devkit. They are added here - the patches doing that were submitted to LKML.

### CODE REVIEW

**Comment by Leo-PL** [comment]
cc @pepe2k

**Comment by Leo-PL** [comment]
Kernel patch applied upstream: https://lore.kernel.org/linux-arm-kernel/CAOMZO5BH6v5YbMHF-oqdfehqXjEtk2sSBcqvJpXKEhEAKV4MTw@mail.gmail.com/T/#m598e80f1f1c6317898e817674d7e14d1d7360422/
I'll move the patches to backports soon.

**Comment by chunkeey** [comment]
Merged. Thanks! (yes, upstream patches will get automatically removed once the kernel hits :) )

**Comment by Leo-PL** [comment]
It seems that Kernel folks have different opinion on that, about backporting to stable:
https://lore.kernel.org/all/CAOMZO5Bd+mVV0BQPgUD+45M6SKQ-txN7uJTgMrh5wtZXFXZtWw@mail.gmail.com/T/#m3f11736ed4ee573967ca2ed1838bb2d1747a7295

I think that a change that causes cpufreq support to work by fixing an omission might be considered one.

**Comment by chunkeey** [comment]
you could try to quote them their own "stable-rules" rules:

> "Serious issues as reported by a user of a distribution kernel may also be considered if they fix a notable performance or interactivity issue. "

That said, I don't think you could convince them and you would get the opposite (i.e. he could double down...).

I would probably go with [Option 2 ](https://github.com/torvalds/linux/blob/master/Documentation/process/stable-kernel-rules.rst#option-2) after the patch has hit mainline (though, I know that this would take a while until maybe the ~6.9/6.8 timeline starts). Because stable@vger.kernel.org is handled by different folks that have a different views.

**Comment by Leo-PL** [comment]
Makes sense. A friend told me that enabling cpufreq might be quite a significant change, that can make someone's day worse, though. So I'd let it sink until it hits mainline indeed. I think we can live with this backport for a while.

**Pull request closed without merging**
