### PR TITLE
sunxi: Add support for Banana Pi M2 Ultra

### PR DESCRIPTION
**Pull request by halmartin**
Add support for Banana Pi M2 Ultra (Cortex-A7, sun8i)

Signed-off-by: Hal Martin <hal.martin@gmail.com>

### CODE REVIEW

**Comment by psyborg55** [comment]
This can not be accepted. Read general guidelines on adding new device support

**Comment by bobafetthotmail** [comment]
what's wrong with it?

**Comment by halmartin** [comment]
@psyborg55 I have read the new device support guidelines, can you be more specific on what part of this pull request goes against the guidelines?

As this hardware is already supported in mainline u-boot and Linux. I have the hardware and this commit enables me to build and boot OpenWrt.

If there are specific improvements required for this PR to be acceptable quality, I'm happy to do that.

**Comment by psyborg55** [comment]
No any kind of device info or flashing procedure

**Comment by halmartin** [comment]
Sure, I've created a TOH entry for the device:
https://openwrt.org/toh/hwdata/sinovoip/sinovoip_banana_pi_m2_ultra

It's a single board computer similar to a Raspberry Pi, so there are no flashing instructions.

Simply write the resulting sdcard ext4/squashfs img file to a microSD card, insert it, and the board will boot OpenWrt.

**Comment by psyborg55** [comment]
Put the basic info in commit message and in PR first message!

**Comment by adrianschmutzler** [comment]
@halmartin 
psyborg seems to be a little aggressive towards non-perfect device support PRs. Please do not feel repelled by that.

Still, you are indeed supposed to add device specifications to your commit message. This was the last device added, maybe it can serve as an example:
https://github.com/openwrt/openwrt/commit/445ca981d163d54c8dcf16cf206bc44904160b99#diff-60c346ec597d3bd7404aff34cd1e7da9

Note that it might take some time until you receive feedback actually concerned with your code. (I'm not familiar with sunxi, I'm just writing to ensure a constructive tone ...)

**Comment by hauke** [comment]
Thank you for your patch, it was applied to master.

**Pull request closed without merging**
