### PR TITLE
generic: fix realtek PHY detection

### PR DESCRIPTION
**Pull request by namiltd**
Fixes the issue of RTL8221B-VB-CG not being detected correctly after commit ca44690

### CODE REVIEW

**Comment by dangowrt** [comment]
Converted DOS linebreaks to UNIX in patch description.
Why didn't you restore the patch description of my original patch which was removed by ca44690?

```
From 0de82310d2b32e78ff79d42c08b1122a6ede3778 Mon Sep 17 00:00:00 2001
From: Daniel Golle <daniel@makrotopia.org>
Date: Sun, 30 Apr 2023 00:15:41 +0100
Subject: [PATCH] net: phy: realtek: detect early version of RTL8221B

Early versions (?) of the RTL8221B PHY cannot be identified in a regular
Clause-45 bus scan as the PHY doesn't report the implemented MMDs
correctly but returns 0 instead.
Implement custom identify function using the PKGID instead of iterating
over the implemented MMDs.

Signed-off-by: Daniel Golle <daniel@makrotopia.org>
```

**Comment by namiltd** [comment]
I didn't think of that, sorry. Please change the description to what you think is most appropriate.

**Comment by Noltari** [comment]
@namiltd https://github.com/openwrt/openwrt/pull/16203

**Comment by namiltd** [comment]
@Noltari However, this is not the original Daniel Golle patch, but a patch created by me but based on the Daniel Golle patch code. There is no mention of this in the description.

**Comment by Noltari** [comment]
> @Noltari However, this is not the original Daniel Golle patch, but a patch created by me but based on the Daniel Golle patch code. There is no mention of this in the description.

Yes, and I also made some minor changes to it.
The patch had to be reworked anyway because of the upstream changes, so...

**Comment by namiltd** [comment]
Merged: https://github.com/openwrt/openwrt/commit/052732bddb4bbe2f7c3c47700f825d8f1e7b9858

**Pull request closed without merging**
