### PR TITLE
mwlwifi - Update to latest commit 20180208

### PR DESCRIPTION
**Pull request by daloki83**
Changes since last merge into OpenWrt since 2017-12-14:
- Added debugfs file tx_hist.
- Added debugfs file fixed_rate.
- Added debugfs file ba_hist.
- Modified the way to establish BA stream.
- Added code to control BF type.
- Added functions to check/dump dhcp packet.
- Upgrade 88W8964 firmware to 9.3.2.4.
- Added debugfs file coredump.
- Corrected the way to transmit multicast packets.
- Change driver version to 10.3.4.0-20180118.
- Corrected the way to get qos control.
- Assigned broadcast dhcpoffer to another queue.
- Separated broadcast and multicast packets.
Bump to latest commit 20180208

### CODE REVIEW

**Comment by tapper82** [comment]
Can this be Merged?

**Comment by thagabe** [comment]
Maybe this should hold off until the code is finalized.

**Comment by daloki83** [comment]
I'll also agree to merge this, because there we're a lot of bugs fixed since the last merge from about ~6 weeks ago. Also it runs very smooth now.

**Comment by anomeome** [comment]
Likelihood of push increases with correctness of PR OOTB, check _HASH_

`make package/kernel/mwlwifi/check FIXUP=1`

**Comment by daloki83** [comment]
Could someone (maybe @anomeome) explain me the hash thing and how to get the correct one ? -It lools like i'm doing something wrong there...
my steps...(always from scratch)
1. git clone https://github.com/openwrt/openwrt.git
2. cd openwrt
3. nano/vi (whatever) package/kernel/mwlwifi/Makefile
-->Change PKG_VERSION to latest (from) commit
-->Change PKG_SOURCE_VERSION to latest commit
-->Change PKG_MIRROR_HASH to none (empty)
4. make package/mwlwifi/download V=s
5. sha256sum dl/mwlwifi-10.3.4.0-20180118.tar.xz
--> Result = ab8c1dd3fa1c7752303b45bdefbba624a892bc5df6c8f5c65a958a709b6140cf
4. nano/vi (whatever) package/kernel/mwlwifi/Makefile
-->Change PKG_MIRROR_HASH to Result
...etc

**Comment by anomeome** [comment]
Don't know where the flaw is in your process, the only thing that can be wrong is the content of your _mwlwifi_ file, delete it and make(git) again, for me:

```
0util@util0:~/br/wrtpac/source/dl$ sha256sum mwlwifi-10.3.4.0-20180123.tar.xz
a0dbb72854bec932a6190e349aec4518217506728875d1d72e7234e5d91d7a7d  mwlwifi-10.3.4.0-20180123.tar.xz
```

**Comment by daloki83** [comment]
Should be ok now...but from where did you get this file_naming "mwlwifi-10.3.4.0-20180123.tar.xz" ? There was no commit on that date

**Comment by tapper82** [comment]
Bump!

**Comment by daloki83** [comment]
Hmm...it looks like no one is interested on this PR ?! Is there anything wrong or whats the reason ? Just asking if it would make sense to update this longer

**Comment by tapper82** [comment]
Hi mate just hang on some one will look. When they have time. I am waiting on this to. 😊

**Comment by rs-se** [comment]
This pull request needs to be canceled, this version of the driver has been very unstable due to untested code. Best known stable revision 4464371.

**Comment by anomeome** [comment]
So cancel is the only option? How about waiting for @yuhhaurlin to push a fix and/or modifying this PR as appropriate.

**Comment by rs-se** [comment]
Before I saw this PR, I was already posting a PR for the latest stable version. r064e888 is not for production, a fix will come but is not a priority due to the commit before works.

**Comment by hauke** [comment]
I did the update to version 20180118 now, that should be sufficient for now.

**Pull request closed without merging**
