### PR TITLE
ath79: Add support for TP-Link TL-WR841N/ND v10 and v12

### PR DESCRIPTION
**Pull request by adschm**
Both devices can be supported with a trivial copy/paste job.

I tested successfully on v10 and v12.

~~Still need a tester for v12!~~

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
@VittGam In case you still have the v12 from your ar71xx commit, I still need someone to test on ath79 ...

**Comment by CodeFetch** [comment]
@oszilloskop can you please tell me what these :eyes: mean?

**Comment by oszilloskop** [comment]
@CodeFetch 
For me it means that I find this topic very interesting and I will observe it.

**Comment by adrianschmutzler** [comment]
Acquired a v12 myself and tested successfully on it, too.

**Comment by adrianschmutzler** [comment]
Added a DTSI for v11/v12 (and trivial rebase).

**Comment by blocktrron** [comment]
Thanks, merged to my staging tree: https://git.openwrt.org/?p=openwrt/staging/blocktrron.git;a=summary

**Pull request closed without merging**
