### PR TITLE
treewide: update PKG_MIRROR_HASH

### PR DESCRIPTION
**Pull request by aparcar**
With the change in version schema the downloaded files changed, too.

### CODE REVIEW

**Comment by BKPepe** [comment]
Just my opinion on this one. It would be good if the commit description is more explainable. Why did the sources change, what was the reason, and **what do we need to do in other feeds as well (packages, routing, etc)** to have correct hashes for ``PKG_MIRROR_HASH``.

**Comment by aparcar** [comment]
@BKPepe good point! Will improve it.

I'm a bit worried about this error here, wonder if it comes from the version changes?

```
====== Make errors from logs/package/network/services/hostapd/supplicant-p2p-internal/compile.txt ======

Applying /__w/openwrt/openwrt/openwrt/package/network/services/hostapd/patches/992-nl80211-add-extra-ies-only-if-allowed-by-driver.patch using plaintext: 
patching file src/drivers/driver.h
patching file src/drivers/driver_nl80211_capa.c
patching file src/drivers/driver_nl80211_scan.c

Applying /__w/openwrt/openwrt/openwrt/package/network/services/hostapd/patches/993-2023-10-28-ACS-Fix-typo-in-bw_40-frequency-array.patch using plaintext: 
patching file src/ap/acs.c
make[4]: Entering directory '/__w/openwrt/openwrt/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/hostapd-supplicant-p2p-internal/hostapd-2023.09.08~e5ccbfc6/wpa_supplicant'
make[4]: /bin/sh: Argument list too long
make[4]: *** [../src/build.rules:83: _make_dirs] Error 127
make[4]: Leaving directory '/__w/openwrt/openwrt/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/hostapd-supplicant-p2p-internal/hostapd-2023.09.08~e5ccbfc6/wpa_supplicant'
make[3]: *** [Makefile:814: /__w/openwrt/openwrt/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/hostapd-supplicant-p2p-internal/hostapd-2023.09.08~e5ccbfc6/.built] Error 2
time: package/network/services/hostapd/supplicant-p2p-internal/compile#0.86#0.70#1.59
```

**Comment by neheb** [comment]
after all of these are updated, the openwrt sources need to be refreshed.

**Comment by ptpt52** [comment]
Also hash change needed in `package/boot/arm-trusted-firmware-mediatek/Makefile`

**Comment by chunkeey** [comment]
> after all of these are updated, the openwrt sources need to be refreshed.

hmm, wouldn't this break packages in the every release (openwrt-22.03, openwrt-23.05, ...)  that uses the same "sources"?
Maybe have a PKG_MIRROR_HASH_OLD for the time being with the current hashes? Gee, don't know?!

**Comment by aparcar** [comment]
I don't see why they couldn't live in parallel? Takes more storage, sure, but we store ancient version anyway

**Comment by neheb** [comment]
The only way I see old tarballs and new living side by side is to switch away from xz and switching to zstd. OTOH that creates larger ones.

**Comment by aparcar** [comment]
the structure of the downloaded file is different, too, so I don't understand the issue?

**Comment by Ansuel** [comment]
@aparcar might be useful to add some logic in CI to suggest the fixed Makefiles? (but I wonder if that's already a thing?)

Also any idea why the hash actually change? Do we store the version in the mirror tar? Maybe we repack the tar with the version in it?

Also about it, I remember there was an idea of moving from xz to zstd due to better perf and size. Maybe it's a good time to make the change since we have to regenerate hash of every package?

**Comment by aparcar** [comment]
> Also any idea why the hash actually change? Do we store the version in the mirror tar? Maybe we repack the tar with the version in it?

we sure do.

> Also about it, I remember there was an idea of moving from xz to zstd due to better perf and size. Maybe it's a good time to make the change since we have to regenerate hash of every package?

IIRC we added zstd to the buildbot containers some time ago, so I'm fine with the change.

**Comment by Ansuel** [comment]
> we sure do.

ok now it makes sense. 

> IIRC we added zstd to the buildbot containers some time ago, so I'm fine with the change.

maybe we should ask this to ynezz and other member but changing the format should also make it more clear that we are changing formats/migrating to something else. (Would also make a clear separation of before opkg and after apk introduction with all new packages using zstd compression)

@BKPepe Any problem with this?

**Comment by BKPepe** [comment]
Thanks for asking, no, no. Its great. :)

Dne ne 24. 3. 2024 21:59 uživatel Christian Marangi <
***@***.***> napsal:

**Comment by aparcar** [comment]
```diff
diff --git a/include/download.mk b/include/download.mk
index d9edcb1c3a..00b8fbef09 100644
--- a/include/download.mk
+++ b/include/download.mk
@@ -13,7 +13,7 @@ ifdef PKG_SOURCE_VERSION
     PKG_VERSION := $(if $(PKG_SOURCE_DATE),$(subst -,.,$(PKG_SOURCE_DATE)),0)~$(call version_abbrev,$(PKG_SOURCE_VERSION))
   endif
   PKG_SOURCE_SUBDIR ?= $(PKG_NAME)-$(PKG_VERSION)
-  PKG_SOURCE ?= $(PKG_SOURCE_SUBDIR).tar.xz
+  PKG_SOURCE ?= $(PKG_SOURCE_SUBDIR).tar.zst
 endif
 
 DOWNLOAD_RDEP=$(STAMP_PREPARED) $(HOST_STAMP_PREPARED)
```

🍿

**Comment by aparcar** [comment]
So ever since https://github.com/openwrt/buildbot/commit/1eb8aec7a64e57e370791cacea2025a343df746d we got zstd in place and the patch above does the magic. Fine with me, we'd need to add zstd as a build requirement, too, right?

**Comment by Ansuel** [comment]
@aparcar you mean in the prereq checks?

**Comment by aparcar** [comment]
@Ansuel correct

**Comment by neheb** [comment]
Just checked. Settings seem maxed out for zstd compression. I remember Arch Linux defaults being quite different. I forgot the details.

**Comment by aparcar** [comment]
Merged. The remaining CI issue is the hostapd thing of #14970

**Comment by aparcar** [comment]
@Ansuel if you care for zst please have a look here https://github.com/openwrt/openwrt/pull/14971

**Pull request closed without merging**
