### PR TITLE
dropbear: allow build without dbclient

### PR DESCRIPTION
**Pull request by rosysong**
This can save ~16KBytes size for the ipk

Signed-off-by: Rosy Song <rosysong@rosinson.com>

### CODE REVIEW

**Comment by dedeckeh** [comment]
Now you're actually breaking the config settings in Config.in as the Configuration submenu does not show up anymore in menuconfig. Next to that for consistency this extra config option must be added in Config.in

**Comment by rosysong** [comment]
@dedeckeh  It's done, thanks!

**Comment by dedeckeh** [comment]
CONFIG_DROPBEAR_DBCLIENT must be added to PKG_CONFIG_DEPENDS to force a recompile if the config option changes

**Comment by rosysong** [comment]
@dedeckeh  Forget to add it, thanks!

**Comment by dedeckeh** [comment]
Patch pushed to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=524810ce6ddff85a79af9ed979452bb8a8ed1b6d); thx

**Pull request closed without merging**
