### PR TITLE
kernel: bump 5.4 to 5.4.77

### PR DESCRIPTION
**Pull request by graysky2**
Manually rebased patches:
```
 bcm27xx/patches-5.4/950-0135-spi-spi-bcm2835-Disable-forced-software-CS.patch
 generic-backport/744-v5.5-net-sfp-soft-status-and-control-support.patch
 layerscape/patches-5.4/819-uart-0005-tty-serial-fsl_lpuart-enable-dma-mode-for-imx8qxp.patch
 mvebu/patches-5.4/521-arm64-dts-marvell-espressobin-Add-ethernet-switch-al.patch
```

Removed:
```
 layerscape/patches-5.4/819-uart-0012-tty-serial-lpuart-add-LS1028A-support.patch
```

All modifications made by `update_kernel.sh`

Build system: x86_64
Build-tested: ipq806x/R7800, ath79/generic, bcm27xx/bcm2711, lantiq/Easybox 904 xDSL, x86_64
Run-tested: ipq806x/R7800, lantiq/Easybox 904 xDSL, x86_64

No dmesg regressions, everything functional

Signed-off-by: John Audia <graysky@archlinux.us>
Co-developed-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>
Co-developed-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>
Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>

### CODE REVIEW

**Comment by graysky2** [comment]
PR prepared in collaboration with @adschm and @ldir-EDB0

**Comment by adschm** [comment]
Note that you technically must not use my Signed-off-by without permission. Since I'm not in the From: field anyway, I shouldn't be the first entry anyway. The proper way would be to use

```
Signed-off-by: John Audia <graysky@archlinux.us>
Co-developed-by: Adrian Schmutzler <mail@adrianschmutzler.de>
Signed-off-by: Adrian Schmutzler <mail@adrianschmutzler.de>
```

but personally, I'd just prefer it dropped since my contribution is minor and the eventual patch is yours.

But please keep in mind that a Signed-off-by can only be added if provided explicitly.

**Comment by graysky2** [comment]
@adschm - Got it.  Fixed.

**Comment by dengqf6** [comment]
Wireguard failed to build on 5.4.76+
@zx2c4

**Comment by zx2c4** [comment]
Fixed in wireguard already. I'll have a new release out and a patch for openwrt today.

**Comment by zx2c4** [comment]
http://lists.openwrt.org/pipermail/openwrt-devel/2020-November/032073.html

**Comment by adschm** [comment]
@graysky2 Technically, a Co-developed-by can only exist in combination with a Signed-off-by from the same person:

https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html#when-to-use-acked-by-cc-and-co-developed-by

I'm probably the only person pedantic enough to care about stuff like that, though. I'd personally still just remove my name from that ...

**Comment by graysky2** [comment]
@adschm - My intent is to capture the true contributions and in this case both you and @ldir-EDB0 are in the category as I could not rebase correctly with you help.

It seems to me that the `Co-developed-by` is the right way to do it, and after skimming through the link, it does also require a `Signed-by-by` as well.  The `Acked-by` doesn't seem right since you both contributed to it.

So if you want to follow the letter of the law here, I feel that both lines are needed by both of you.  Thoughts?

**Comment by adschm** [comment]
The Co-developed-by essentially expresses that the whole contribution is a cooperative effort, it can be seen as an additional "From:", since that can only take one entry. If somebody just added a smaller thing, one would usually just use Signed-off-by of this person with a reference to his/her contribution, e.g.
`Signed-off-by: XY <address> [fix patch A]`

Note that the Signed-off-by is not so much a statement of authorship, but a statement of taking responsibility for the submission (and/or changes to it). If I e.g. pick a patch from somebody and merge it with changes, I do not add my Signed-off-by because I'm so eager to show what I've done, but to make clear I introduced these changes so the original author is not _blamed_ for them.

Even more strictly, if you have actually taken my patch and just tidied up as discussed as an option via e-mail, actually I would be the initial author (From: field = me) and my signed-off-by would be first, as your contribution would be minor then (an alteration of the initial patch):

```
Signed-off-by: Adrian Schmutzler <...>
[add commit message/title, tidy up]
Signed-off-by: John Audia <...>
```

So, this is a matter of _interpretation_ then: Did you take my patch and alter it, or did you incorporate my changes into your patchset.

Coming back to the question, interpreted strictly this means if we are listed as Co-developed-by, we are co-authors of the entire patchset and acknoledge it as such. I'm personally fine with either way (i.e. you can use my signed-off), but I'm not sure what's ldir's point on this or whether he cares at all.

**Comment by graysky2** [comment]
@adschm - This is a horribly vague question, but here goes: could any of the changes in the PR (and in the 5.4.77 code) have implications to wireless devices and VPN connectivity _beyond_ wireguard?

I have observed some disconnections from my work laptop (W10) which uses a proprietary VPN.  Note that there is very poor debug abilities in that client and users cannot see even basic logs.  Further, I cannot rule out the laptop as the cause, or any down stream links in connections it is making.

I can downgrade my OW router to my build of 5.6.75 which did not show these issues.  I am not seeing anything diagnostic in OW devices to indicate a problem (`dmesg` or `logread`).

**Comment by graysky2** [comment]
> I'm personally fine with either way (i.e. you can use my signed-off), but I'm not sure what's ldir's point on this or whether he cares at all.

OK.  I re added your signed-off.

**Comment by zuzia-dev** [comment]
Build system: x86_64
Build-tested: lantiq/Easybox 904 xDSL
Run-tested: lantiq/Easybox 904 xDSL

Everything functional.

**Comment by graysky2** [comment]
Thanks, @zuzia-dev - Added your result to the commit

**Comment by adschm** [comment]
Would somebody please confirm that wireguard works now with the update merged to master 4 days ago?
Any further evidence on the other VPN issues reported here?

**Comment by graysky2** [comment]
@adschm - I do not run wireguard on OW.  I can tell you that I have not experienced any non-wireguard connectivity issues with the proprietary firewall on my work laptop.  Since I am still running this the same OW build now as I did last week, I will conclude they were unrelated.

**Comment by graysky2** [comment]
@adschm - I do not run wireguard on OW.  Perhaps someone else can comment.

WRT the other VPN issues, I have not experienced the connectivity issues with the proprietary firewall on my work laptop since Friday of last week.  Since I am still running this the same OW build now as I did last week, I will conclude they were unrelated.

**Comment by curtdept** [comment]
Not sure it's helpful but build and run tested ok on x86_64.

I do not run wireguard though.

**Comment by graysky2** [comment]
@adschm - I believe 5.4.78 will get released shortly.  I already have 5.4.78-rc1 setup and running.  Since this PR has been runtested on several platforms, it might be better to merge it rather than rebasing to 5.4.78.  Thoughts?

**Comment by adschm** [comment]
If it's not merged to master in time, you can still have separate subsequent 5.4.77 and 5.4.78 patches, so 5.4.78 changes won't affect the test results of 5.4.77 ...

**Comment by adschm** [comment]
Anyway, I will pick this now.
Before I close this, please re-push and replace my e-mail address with the usual freifunk@ address I use in this place.
That's another problem of using Signed-off-by and similar without permission; I now have no option to remove that other e-mail address from this place anymore now (but you can at least replace the topmost patch version).

**Comment by graysky2** [comment]
@adschm - Done.

**Pull request closed without merging**
