### PR TITLE
rockchip: add NanoPi R2C support

### PR DESCRIPTION
**Pull request by 1715173329**
- uboot-rockchip: cleanup redudant variables
- rockchip: merge bootscript
- rockchip: move UBOOT_DEVICE_NAME to default
- kernel: backport Motorcomm YT8521/YT8531 support
- rockchip: add NanoPi R2C support

The NanoPi R2C is a minor variant of NanoPi R2S with the on-board NIC
chip changed from rtl8211e to yt8521s, and otherwise identical to R2S.

### CODE REVIEW

**Comment by ptpt52** [comment]
mark.

**Comment by 1715173329** [comment]
rebased upon the latest git HEAD, hope this will not take another month to get merged...

**Comment by 1715173329** [comment]
ping @aparcar @hauke

**Comment by 1715173329** [comment]
Cc @Ansuel

**Comment by aparcar** [comment]
CC @PolynomialDivision

**Review by hauke — APPROVED** [review]

**Comment by hauke** [comment]
I rebased it to run the github CI with the change from a7747e8670cb9bc92a28f3a20d07708c171a1b09 again.

**Comment by 1715173329** [comment]
Thank you!

**Pull request merged**
