### PR TITLE
add protocol qmi/mbim support for ucidef_set_interface()

### LINKED ISSUE #10569: is it possible to use ucidef_set_interface() for proto qmi?
I use following uci configuration for my QMI modem, is it possible to set it with [ucidef_set_interface()](https://github.com/openwrt/openwrt/blob/master/package/base-files/files/lib/functions/uci-defaults.sh#L28) or similar function at build-time?
```
set network.wwan='interface'
set network.wwan.proto='qmi'
set network.wwan.device='/dev/cdc-wdm0'
set network.wwan.pdptype='ipv4'
```

### PR DESCRIPTION
**Pull request by bam80**
useful for default wan configuration of devices with modem

Fixes #10569

Device using it: #10972 

@Linaro1985 @hauke

### CODE REVIEW

**Comment by Leo-PL** [comment]
@bam80 The first commit looks mostly fine (and I'm looking forward to merging it!), but second is missing commit message - and I think it might be handled separately, on per-device basis. I wanted to add that to some ZTE LTE devices myself, but this wasn't possible without change like yours.

**Comment by bam80** [comment]
@Leo-PL I've moved the device-specific commit to a separate #10972 and added the commit message there

**Comment by Leo-PL** [comment]
LGTM

**Comment by Leo-PL** [comment]
@bam80 You also add MBIM support in source, but don't mention it in commit title nor message. It might be worthy to add it, and elaborate a bit more in the commit message, like:
`Make it possible to setup default WAN interface for devices with built-in LTE modems, using QMI or MBIM.`

I'm not sure, though if MBIM protocol handler can work without APN set - but maybe it can be modified to do so. OTOH I have yet to see a device which uses MBIM with stock firmware. For QMI I'm sure it works, remebering the last used profile on stock FW.

**Comment by bam80** [comment]
@Leo-PL done

**Review by Leo-PL — APPROVED** [review]

**Comment by Leo-PL** [comment]
LGTM, so
`Reviewed-by: Lech Perczak <lech.perczak@gmail.com>`

**Comment by bam80** [comment]
> `Reviewed-by: Lech Perczak <lech.perczak@gmail.com>`

added

**Comment by bam80** [comment]
> At least 6 approving reviews are required to merge this pull request. 

Is it an error or it so indeed?

**Comment by Leo-PL** [comment]
Just Github thing, OpenWrt staff prefers to merge patches manually via Git itself rather than Github.

**Comment by bam80** [comment]
So nothing to do from my side any more?

**Comment by Leo-PL** [comment]
Okay, I'll think about it.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in bf9dc176516bdf030486483e3b766b9f49f3db15.

**Pull request closed without merging**
