### PR TITLE
rockchip: fix issue in sysupgrade

### PR DESCRIPTION
**Pull request by bl4kraven**
In rockchip sysupgrade, the upgrade backup sysupgrade.tgz need copy to boot partition(fat32). The default kernel config not enable fat32 support, and cause error in sysupgrade:

> [   86.052163] F2FS-fs (mmcblk0p1): Magic Mismatch, valid(0xf2f52010) - read(0x0)
> [   86.060401] F2FS-fs (mmcblk0p1): Can't find valid F2FS filesystem in 1th superblock
> [   86.069707] F2FS-fs (mmcblk0p1): Magic Mismatch, valid(0xf2f52010) - read(0x6020601)
> [   86.078420] F2FS-fs (mmcblk0p1): Can't find valid F2FS filesystem in 2th superblock
> mount: mounting /dev/mmcblk0p1 on /mnt failed: Invalid argument
> umount: can't unmount /mnt: Invalid argument

So the kernel config need enable fat32 support.

Signed-off-by: Leo Chung <gewalalb@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
`The default kernel config does not enable fat32 support, and cause error in sysupgrade:` <-- can you add does? 

Also i think it would be a good idea to insert the log in the commit description.

**Comment by bl4kraven** [comment]
OK,  in rockchip rk3328 board with openwrt master branch execute sysupgrade on serialport console log is 

```
Thu Oct 20 16:59:30 CST 2022 upgrade: Reading partition table from bootdisk...
zcat: write error: Broken pipe
zcat: write: Broken pipe
Thu Oct 20 16:59:30 CST 2022 upgrade: Reading partition table from image...
Thu Oct 20 16:59:30 CST 2022 upgrade: Saving config files...
Thu Oct 20 16:59:30 CST 2022 upgrade: Commencing upgrade. Closing all shell sessions.
Thu Oct 20 16:59:31 CST 2022 upgrade: Sending TERM to remaining processes ...
Thu Oct 20 16:59:35 CST 2022 upgrade: Sending KILL to remaining processes ...
[   41.206682] stage2 (1825): drop_caches: 3
Thu Oct 20 16:59:42 CST 2022 upgrade: Switching to ramdisk...
Thu Oct 20 08:59:44 UTC 2022 upgrade: Performing system upgrade...
Thu Oct 20 08:59:44 UTC 2022 upgrade: Reading partition table from bootdisk...
0+1 records in
0+1 records out
zcat: write error: Broken pipe
zcat: write: Broken pipe
Thu Oct 20 08:59:44 UTC 2022 upgrade: Reading partition table from image...
Writing image to /dev/mmcblk0p1...
zcat: write error: Broken pipe
zcat: write: Broken pipe
32768+0 records in
16+0 records out
Writing image to /dev/mmcblk0p2...
5478+1 records in
2+1 records out
Writing new UUID to /dev/mmcblk0...
zcat: write error: Broken pipe
4+0 records in
4+0 records out
zcat: write: Broken pipe
[   47.375693] F2FS-fs (mmcblk0p1): Magic Mismatch, valid(0xf2f52010) - read(0x0)
[   47.384025] F2FS-fs (mmcblk0p1): Can't find valid F2FS filesystem in 1th superblock
[   47.393539] F2FS-fs (mmcblk0p1): Magic Mismatch, valid(0xf2f52010) - read(0x6020601)
[   47.402225] F2FS-fs (mmcblk0p1): Can't find valid F2FS filesystem in 2th superblock
mount: mounting /dev/mmcblk0p1 on /mnt failed: Invalid argument
umount: can't unmount /mnt: Invalid argument
Thu Oct 20 08:59:48 UTC 2022 upgrade: Upgrade completed
Thu Oct 20 08:59:49 UTC 2022 upgrade: Rebooting system...
umount: can't unmount /dev: Resource busy
umount: can't unmount /tmp: Resource busy
[   48.516617] reboot: Restarting system
```
you can see the error:
```
[   47.375693] F2FS-fs (mmcblk0p1): Magic Mismatch, valid(0xf2f52010) - read(0x0)
[   47.384025] F2FS-fs (mmcblk0p1): Can't find valid F2FS filesystem in 1th superblock
[   47.393539] F2FS-fs (mmcblk0p1): Magic Mismatch, valid(0xf2f52010) - read(0x6020601)
[   47.402225] F2FS-fs (mmcblk0p1): Can't find valid F2FS filesystem in 2th superblock
mount: mounting /dev/mmcblk0p1 on /mnt failed: Invalid argument
umount: can't unmount /mnt: Invalid argument

```
which is cause by  [ /lib/upgrade/platform.sh ](https://github.com/openwrt/openwrt/blob/master/target/linux/rockchip/armv8/base-files/lib/upgrade/platform.sh) platform_copy_config

```
platform_copy_config() {
	local partdev

	if export_partdevice partdev 1; then
		mount -o rw,noatime "/dev/$partdev" /mnt
		cp -af "$UPGRADE_BACKUP" "/mnt/$BACKUP_FILE"
		umount /mnt
	fi
}
```
platform_copy_config need mount /dev/mmcblk0p1 boot partition(fat32) and copy config backup file to it, so next reboot openwrt will restore config backup to system. And kernel config not enable fat32 support.

**Comment by Ansuel** [comment]
@bl4kraven okok just some additional info is fat32 the default fs or something the user decide?

**Comment by AntonyFl** [comment]
This will not fix the issue with system upgrade not saving setting. problem is the kernel size has increased and need more room
https://github.com/coolsnowwolf/lede/commit/91dd328375d1a6c4b91aadd7934ef4e53d9fbc41

**Comment by bl4kraven** [comment]
@Ansuel  Sorry for my mistake, i just check the rockchip firmware partition again, and found that default boot partition /dev/mmcblk0p1 is ext4 (I change it to fat32 for some reason long ago), and kernel default support ext4, so this pull request is not necessary, just ignore this.

**Comment by bl4kraven** [comment]
@AntonyFl Thank you for mention this, i'm use rk3328 board with openwrt master branch and default kernel 5.15 kconfig, boot partition is this:
```
root@OpenWrt:/tmp# mkdir boot
root@OpenWrt:/tmp# mount /dev/mmcblk0p1 boot
[ 1100.584300] EXT4-fs (mmcblk0p1): mounted filesystem without journal. Opts: (null). Quota mode: none.
root@OpenWrt:/tmp# ls -l /tmp/boot/
-rw-r--r--    1 root     root           381 Oct 24 09:35 boot.scr
-rw-r--r--    1 root     root      15529992 Oct 24 09:35 kernel.img
drwx------    2 root     root          4096 Jan  1  1970 lost+found
-rw-r--r--    1 root     root         35766 Oct 24 09:35 rockchip.dtb
root@OpenWrt:/tmp# df /dev/mmcblk0p1 
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/mmcblk0p1           16084     15220       540  97% /tmp/boot
```
The ext4 boot partition has 540KB room for config backup, and config backup file sysupgrade.gz just 5KB size. So for now this is enough for sysupgrade store config backup file , and  i just try sysupgrade and found no error.

But you are right  kernel size is too big (kernel.img 15529992), and can be increase in future. The 16M boot partition may be not enough.

**Comment by ScottESanDiego** [comment]
> This will not fix the issue with system upgrade not saving setting. problem is the kernel size has increased and need more room [coolsnowwolf/lede@91dd328](https://github.com/coolsnowwolf/lede/commit/91dd328375d1a6c4b91aadd7934ef4e53d9fbc41)

Is there a PR for this against OpenWRT?

**Comment by bl4kraven** [comment]
OK, guys i'm just close this pull request, thanks.

**Pull request closed without merging**
