### PR TITLE
scripts: add size_compare.sh

### PR DESCRIPTION
**Pull request by aparcar**
As package size changes are a continuous topic on the mailing list this
scripts helps developers to compare their local package modifications
against latest upstream.

The script downloads the latest package indexes based on env variables
or the `.config` file. The script compares the actual installed size
(data.tar.gz) or the IPK package size.

An example output is found below:

```
user@dawn:~/src/openwrt/openwrt$ ./scripts/size_compare.sh
Compare packages of ath79/tiny/mips_24kc:
dropbear busybox iw ubus

Checking configuration difference
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   554  100   554    0     0    336      0  0:00:01  0:00:01 --:--:--   336

 --- start config diff ---
--- /tmp/config.DDjwVh-LOCAL	2020-11-23 09:08:28.913203068 -1000
+++ /tmp/config.DDjwVh-UPSTREAM	2020-11-23 09:08:36.369240887 -1000
@@ -1,5 +1,9 @@
+CONFIG_ALL_KMODS=y
+CONFIG_ALL_NONSHARED=y
 CONFIG_AUTOREBUILD=y
+CONFIG_AUTOREMOVE=y
 CONFIG_BINARY_FOLDER
 CONFIG_USE_UCLIBCXX=y
 --- end config diff ---

Checking installed size

Fetching latest package indexes...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80634  100 80634    0     0  33499      0  0:00:02  0:00:02 --:--:-- 33485
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 54082  100 54082    0     0  24252      0  0:00:02  0:00:02 --:--:-- 24252

Comparing package sizes...
Change 	Local	Remote 	Package
+271	51386	51115	base-files
+123	705241	705118	bnx2-firmware
+86	17209	17123	fstools
+22	47989	47967	procd
+21	208311	208290	busybox
+19	67181	67162	netifd

```

I plan to integrate this script into the CI so we have a summary how
sizes change over different architectures.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by wulfy23** [comment]
probably prudent to parse: CONFIG_BINARY_FOLDER and check existence...

nice script!

**Comment by bobafetthotmail** [comment]
Nice. If there is a dedicated tool we can add to the contribution guide and rules to "always post a result of size_compare in the commit message"

**Comment by aparcar** [comment]
Updated to work with `curl` or `wget` and saved a `grep` by telling `tar` to look for `./data.tar.gz` directly.

**Comment by aparcar** [comment]
I want to add this to the `packages.git` CI, please merge this.

**Comment by aparcar** [comment]
Based on feedback from @dangowrt the script now also prints a config diff so it's easier to spot config options that may influenced size changed:


Checking configuration difference
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   554  100   554    0     0    336      0  0:00:01  0:00:01 --:--:--   336

```
 --- start config diff ---
37,39d36
< CONFIG_KERNEL_SECURITY_SELINUX_BOOTPARAM=y
< CONFIG_KERNEL_SECURITY_SELINUX_DEVELOP=y
< CONFIG_KERNEL_SECURITY_SELINUX=y
44,45d40
< CONFIG_SELINUXTYPE_dssp=y
< CONFIG_SELINUX=y
49d43
< CONFIG_SSTRIP_ARGS=""
52d45
< CONFIG_TARGET_ROOTFS_SECURITY_LABELS=y
 --- end config diff ---
```

**Comment by ynezz** [comment]
> I want to add this to the `packages.git` CI, please merge this.

Why don't you merge it yourself?

**Comment by ynezz** [comment]
> Based on feedback from @dangowrt the script now also prints a config diff so it's easier to spot config options that may influenced size changed:
> 
> ```
> Checking configuration difference
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   554  100   554    0     0    336      0  0:00:01  0:00:01 --:--:--   336
> 
>  --- start config diff ---
> 37,39d36
> < CONFIG_KERNEL_SECURITY_SELINUX_BOOTPARAM=y
> < CONFIG_KERNEL_SECURITY_SELINUX_DEVELOP=y
> < CONFIG_KERNEL_SECURITY_SELINUX=y
> 44,45d40
> < CONFIG_SELINUXTYPE_dssp=y
> < CONFIG_SELINUX=y
> 49d43
> < CONFIG_SSTRIP_ARGS=""
> 52d45
> < CONFIG_TARGET_ROOTFS_SECURITY_LABELS=y
>  --- end config diff ---
> ```

I find unified diffs (`diff -u`) more readable.

**Comment by adschm** [comment]
> I find unified diffs (`diff -u`) more readable.

Yes, please.

**Comment by aparcar** [comment]
Using now `diff -u` and curl/wget for all calls.

>  Why don't you merge it yourself?

No access yet, I'll write a request

**Comment by aparcar** [comment]
Merged.

**Pull request closed without merging**
