### PR TITLE
ramips: fix dts file name for SNR-CPE-ME1

### PR DESCRIPTION
**Pull request by MaxS0niX**
Rename file mt7621_snr-spe-me-1.dts -> mt7621_snr_snr-spe-me-1.dts
Fix for #11160 
@hauke Most likely, the check did not detect a mismatch in the name dts.

### CODE REVIEW

**Comment by AcidSlide** [comment]
Confirming this fixed build issue for `ramips/mt7621`

**Comment by AcidSlide** [comment]
@MaxS0niX removed my previous comment.. Re-confirming actual PR fixed the build issue.. confirming correct filename change.

**Comment by MaxS0niX** [comment]
Ok, waiting for the corrections to be accepted :)

**Comment by rmilecki** [comment]
```
Tested-by: Rafał Miłecki <rafal@milecki.pl>
```

**Comment by hauke** [comment]
@rmilecki  You could have also merged it yourself.

**Pull request merged**
