### PR TITLE
[21.02]exfat: update to 5.12.3

### PR DESCRIPTION
**Pull request by neheb**
Major changes are:
    Avoid page allocation failure from upcase table allocation.
    Add support for FITRIM.
    Improve write perofmrance on dirsync mount.
    Improve lookup perofmrance.
    Fix a bug on discard mount.

Switch to AUTORELEASE to avoid having to bump it.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Updated to 5.12.3

**Comment by aparcar** [comment]
Was this updated in master?

**Comment by neheb** [comment]
this is not present in master as this went in the kernel at version 5.7. since master is 5.10, there's no point in having it out of tree.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to the 21.02 branch.

**Pull request closed without merging**
