### PR TITLE
kernel: fix mac80211 ubus call hostapd config_add

### PR DESCRIPTION
**Pull request by yezige**
Fix ubus call hostapd config_add error
This error is often reported when logread, and an extra space is found.
```
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019): Command failed: ubus call hostapd config_add {"iface":"phy0-ap0", "config":"/var/run/hostapd-phy0.conf"} (Invalid argument)
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019): Usage: ubus [<options>] <command> [arguments...]
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019): Options:
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  -s <socket>:		Set the unix domain socket to connect to
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  -t <timeout>:		Set the timeout (in seconds) for a command to complete
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  -S:			Use simplified output (for scripts)
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  -v:			More verbose output
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  -m <type>:		(for monitor): include a specific message type
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019): 			(can be used more than once)
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  -M <r|t>		(for monitor): only capture received or transmitted traffic
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019): Commands:
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  - list [<path>]			List objects
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  - call <path> <method> [<message>]	Call an object method
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  - subscribe <path> [<path>...]	Subscribe to object(s) notifications
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  - listen [<path>...]			Listen for events
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  - send <type> [<message>]		Send an event
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  - wait_for <object> [<object>...]	Wait for multiple objects to appear on ubus
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):  - monitor				Monitor ubus traffic
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019):
Sat Nov 12 10:30:41 2022 daemon.notice netifd: radio0 (10019): Device setup failed: HOSTAPD_START_FAILED
```

### CODE REVIEW

**Comment by ptpt52** [comment]
mark

**Comment by zxlhhyccc** [comment]
Mark

**Comment by yezige** [comment]
I'm very sorry, I understand the error, although the error `Usage: ubus [<options>] <command> [arguments...]` is reported in the log, but the `ubus call` is actually executed correctly, the reason for the error is `/var/ run/hostapd-phy0.conf` has some issues, so this pull request is temporarily closed.

**Comment by yezige** [comment]
You can continue to comment here, I'll reply here when the issue is fixed, possibly opening the pull request again.

**Comment by yezige** [comment]
One of the cases that will report this error is that your wireless network card ax mode only supports HE40/2.4GHz, HE40/HE80/5GHz, HE160/5GHz, but you use HE20/5GHz.

**Comment by crass** [comment]
> This error is often reported when logread, and an extra space is found.

I don't think this space has anything to do with the problem, assuming this is the same issue I've reported in #11246. This is not a failure to parse the json because of an extra space.

There's actually a couple issues here:
1. `ubus` is showing usage when it should not (#11246).
2. hostapd is choking on the `/var/run/hostapd-phy0.conf` for some reason.

> One of the cases that will report this error is that your wireless network card ax mode only supports HE40/2.4GHz, HE40/HE80/5GHz, HE160/5GHz, but you use HE20/5GHz.

In my case, I don't believe this is the problem is with the frequency width as you suggest because its set to a supported channel width. I now suspect that there's a variety of reasons why hostapd doesn't like the config file. Your's are probably different than mine. Currently mine are #11248 and #11247.

**Comment by yezige** [comment]
You are right, I read the source code, json is wrapped in double quotes
`"`, so it is not a problem of spaces

crass ***@***.***> 于2022年11月15日周二 13:49写道：

**Pull request closed without merging**
