### PR TITLE
[RFT] lantiq: use soc_vendor_device scheme on DTS file

### PR DESCRIPTION
**Pull request by adschm**
This is a copy of a similar patchset sent to the list:

** Please run-test **

This renames lantiq DTS(I) files to follow soc_vendor_device scheme.

The same patchset is available t:
https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/lantiq

It is based on the DTS changes proposed in
https://github.com/openwrt/openwrt/pull/2216
(this patchset is based on them, but they are not included in the set;
they are added in the referenced staging tree and in GitHub, though)

The state in my tree is build-tested on all subtargets, but should be
run-tested at least on 1-3 selected devices.

If Acked, I will change the ATH_SOC, MTK_SOC and SUNXI_SOC variables to
SOC as well when applying this patchset.

### CODE REVIEW

**Comment by hauke** [comment]
this looks good to me

**Comment by adrianschmutzler** [comment]
Thanks for the feedback. I'd be happy if someone could just test this at least on one single device, so we can merge both patchsets.

**Comment by adrianschmutzler** [comment]
@xdarklight Can you please test this PR on your device? Since my changes are only affecting build, I'd merge the entire patchset (including your patches) after it has been flashed successfully onto one device.

**Comment by adrianschmutzler** [comment]
Merged.

**Comment by xdarklight** [comment]
I runtime tested this on two boards:
- XRX200 BT Home Hub 5A
- XWAY AVM Fritz!Box 7312

both are booting fine, all wifi radios come up and there are no (obvious) errors in dmesg

**Comment by adrianschmutzler** [comment]
Perfect, thanks!

**Pull request closed without merging**
