### PR TITLE
ramips: mt7621: add NETGEAR R7200 as DEVICE_ALT1

### PR DESCRIPTION
**Pull request by CHKDSK88**
Netgear R7200 is another clone of Netgear R6700v2, introduced in:
6e80df5 ("ramips: add support for NETGEAR R6700v2/AC2400")

Reported-by: Joel Pinsker, github user @joelp64
(https://github.com/joelp64)

Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Since R6700 is a v2 and R7200 is a "v1", I consider this more confusing then just adding another "full" device. I'd go for the latter.

**Comment by CHKDSK88** [comment]
The same situation is with Nighthawk added as DEVICE_ALT0.

**Comment by adrianschmutzler** [comment]
Yes, but the Nighthawks follow a different naming scheme, and we never have a nighthawk as "primary" name reflected in the image name. I'm not forcing you, though, just wanted to share my personal preference/tendency in this case.

**Comment by CHKDSK88** [comment]
I want to find the greatest solution.

Maybe there is a time for DEVICE_ALTx_VARIANT?

**Comment by adrianschmutzler** [comment]
Well, there is no really good solution to this problem. That's why it's limited to a matter of personal taste.

**Comment by dangowrt** [comment]
You can define DEVICE_ALT{0,1}_VARIANT...?

**Comment by CHKDSK88** [comment]
Now it should be clear-cut.

**Comment by CHKDSK88** [comment]
It's merged, so I close.

**Pull request closed without merging**
