### PR TITLE
ath79: add more image options and fix factory

### PR DESCRIPTION
**Pull request by lucize**
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by NeoRaider** [comment]
I just pushed aea146736cfd5792fbce06f33371adc13516e318, fixing the 1043v1 build. For the other image sizes, let's add them as soon as they are needed.

**Comment by lucize** [comment]
they are needed for 841 and 1043nd-v2

**Comment by lucize** [comment]
the v1 is also wip so if I only update with image sizes is not enough ?

**Comment by mkresin** [comment]
While we are at it, I'm quite sure at least some of the padding steps can be removed. To my knowledge we only create a 64k squashfs. Furthermore, I rather would have expected that we take the flash erase blocksize into account using the BLOCKSIZE variable or similar (for flash chips with 4K erase block size).

I'm not that familiar with the specific needs of the ar71xx/ath79 images, but I'm quite surprised to see that the rootfs need to be aligned to a erase block boundary. The lantiq tp-link images are fine if the rootfs is directly appended to the kernel. The splitter is still able to find the rootfs offset.

However, the mktplink code seems to enforces a padding. But might be that the lowest value (0x4) is fine here.

**Comment by lucize** [comment]
@NeoRaider I worked on my 1043nd-v1 and openwrt boot loader is not starting in most of the times, did you encounter that problem ?
for now I'm testing it using the initrd image and at the momment
usb is working properly, I started the switch but wasn't able to start the eth0 interface and pcie is hanging or giving me panic when I add ath9k 
@mkresin in 1043ndv2/v3 and 841nd-v9 0x4 was selected

**Pull request closed without merging**
