### PR TITLE
ath79: migrate archer c7 v2 5ghz radio device path

### PR DESCRIPTION
**Pull request by howl**
Upgrading an Archer C7 v2 from ar71xx to ath79 5ghz radio stops
working because the device path changes.

Some people subtitute the 5GHz radio found in v1 with the v2. The stock radio
doesn't work, so it's safe to apply the change also for v1.

Also rename the migration file and variables from wmac to wifi.

Signed-off-by: David Santamaría Rogado <howl.nsp@gmail.com>

### CODE REVIEW

**Comment by howl** [comment]
Is not a wmac path but the change is similar, Archer C7 v2 needs to change radio1 2.4GHz from 'platform/qca955x_wmac' to 'platform/ahb/ahb:apb/18100000.wmac' but also radio0 5 GHz from 'pci0000:01/0000:01:00.0' to 'pci0000:00/0000:00:00.0'. Archer C7 v4 is not affected because it uses the all zeroes path in both ar71xx and ath79.

I'm not sure if this change as is in the pull request is safe because it could interfere with other devices that should have 'pci0000:01/0000:01:00.0' path for one of their radios. A solution could be to check also the board name to only apply to archer c7 v2.

**Comment by adrianschmutzler** [comment]
This should solve the problem blocking https://patchwork.ozlabs.org/patch/1086982/ .

**Comment by howl** [comment]
@adrianschmutzler So v1 also have the same 2.4 GHz device path change. V1 doesn't have support for the native 5 GHz radio so I suppose you get no wifi with the update. If the board check is necessary the check should be to let both archer c7 v1 and v2 do the change.

**Comment by adrianschmutzler** [comment]
@howl 
No, I didn't change anything. I just wanted to provide SUPPORTED_DEVICE variables to enable upgrade from ar71xx to ath79 without -F.
To do this, I was pointed towards WiFi migration that seems to need care. However, I use a custom script for updating network-/wireless-config during upgrade, so I do not use OpenWrt-migration or understand how it works.

Thus, my mentioned patch was waiting for someone to take care of this. However, there was a little of discussion going on there which might be helpful for fixing.

**Comment by chunkeey** [comment]
> I don't know if the change is safe but if it's necessary the board check should be only for the v2.

Can you please add that and add a check so only the Archer C7 are converted?

(Nitpick: now might be a good time to rename the file to 00-wifi-migration and rename all the *WMAC*/*wmac* to *WIFI*/*wifi* in that file.)

**Comment by howl** [comment]
@chunkeey I like your idea, will do it asap. I will check only for v2, v1 should have not working 5GHz card.

**Comment by howl** [comment]
Arg, I forget to add the board_name check and force pushing it caused the file to be deleted and recreated instead of being moved.

**Comment by howl** [comment]
Have tried to have the rename done force reverting and force pushing again but I couldn't do it.

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
