### PR TITLE
package/utils/f2fs-tools: Update to 1.13.0

### PR DESCRIPTION
**Pull request by diizzyy**
Update f2fs-tools to 1.13.0
Remove upstreamed patches
Disable build of static library

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested: ramips, mvebu
Runtime tested: mvebu Linksys WRT3200ACM

**Comment by neheb** [comment]
I am curious if 100-use_urandom.patch is needed since urngd was added. ping @ynezz

**Comment by adrianschmutzler** [comment]
> Disable build of static library

Why?

**Comment by hauke** [comment]
Thank you for your pull request, it was applied to master.

**Pull request closed without merging**
