### PR TITLE
ath79: ap5030dn: use nvmem

### PR DESCRIPTION
**Pull request by neheb**
Userspace handling is deprecated.

ping @robimarko

### CODE REVIEW

**Comment by neheb** [comment]
ping @CodingMarco

**Comment by musashino205** [comment]
This is not a conversion to NVMEM binding but changes for `label-mac-device`, so IMO, `ath79: ap5030dn: use label-mac-device property` or something is better.

**Comment by neheb** [comment]
Done.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
