### PR TITLE
Don't install USB WiFi chip firmware on PCIE routers (53xx family)

### PR DESCRIPTION
**Pull request by jen1-sys**
Don't install USB WiFi chip firmware on PCIE routers (53xx family)

For more details https://github.com/openwrt/openwrt/issues/16423

Basically the name of the package is wrong, it will install 2 firmware for USB WiFi Chips  and will add 2 files to /lib/firmware/brcm: brcmfmac43143.bin and brcmfmac43236b.bin.

These USB WiFi chips are used for USB WiFi adapters and will not be needed for the 53xx family.  again for more details https://github.com/openwrt/openwrt/issues/16423

### CODE REVIEW

**Comment by brada4** [comment]
brcm USB wifi plugs can be plugged into target devices, no more?

**Comment by hauke** [comment]
We should keep BRCMFMAC_USB activate also on bcm53xx. It would be nice if the USB part would be a separate .ko file, currently the kernel only supports adding USB support to the main module. You could remove the dependency to `brcmfmac-firmware-usb` to not add the extra firmware files. Maybe remove this only on bcm53xx.

**Comment by jen1-sys** [comment]
Will reopen with my full name signature so the formality will be pass the test.

@hauke The ackage name is misleading, it is a driver/firmware for the 2 mentioned chips. I am literally running my router with out t, and it can be add later if needed (it wont be needed for sure) 
Screenshot 2024-10-02 221322

**Comment by jen1-sys** [comment]
@hauke  The usb support is added by the linux kernel and BRCMFMAC_USB  will not add usb support, it is just a driver.

Please look at the pic 
Screenshot 2024-10-02 223110

I will close this PR and reopen a new one, as my full name was not added and it will fail the test.

**Pull request closed without merging**
