### PR TITLE
Layerscape: update kernel and all components to LSDK-20.04 (linux-5.4)

### PR DESCRIPTION
**Pull request by yangbolu1991**
The pull request is to update Layerscape kernel and all components to Layerscape SDK 20.04. The kernel version is upgraded to 5.4.

The LSDK-20.04 has not been announced by NXP now. But all the source and tag LSDK-20.04 is ready.
https://lsdk.github.io/
https://www.nxp.com/design/software/embedded-software/linux-software-and-development-tools/layerscape-software-development-kit:LAYERSCAPE-SDK

NXP will also have Layerscape OpenWrt release on June 2020. I will make sure any bug-fix patches in release sent to community too.

Please help to review and merge!
Thanks!

### CODE REVIEW

**Comment by ynezz** [comment]
`layerscape: support linux-5.4` is a gem of itself `30 files changed, 257284 insertions(+), 1 deletion(-)`, and I'm not going to review this one, I'll pass it to someone else.

That `701-lsdk-net-support.patch` itself is `435 files changed, 192599 insertions(+), 3322 deletions(-)`, uh?

**Comment by yangbolu1991** [comment]
@ynezz 
I'm sorry. I understand it is very difficult to review such large code changes. I was very painful too to port/rebase a large number of layerscape patches.

Currently NXP uses an unify linux to support i.MX/QorIQ/S32 series platforms. There should be almost 4000 patches on tag LSDK-20.04-V5.4.
https://source.codeaurora.org/external/qoriq/qoriq-components/linux/log/?h=LSDK-20.04-V5.4 

I identified and cherry-picked only QorIQ Layerscape specific patches (943 patches) for OpenWrt. Then made the all-in-one patches as you see in patches-5.4 for each IP/feature.

There are too many IPs on Layerscape platforms, especially in net controllers. It's right we have a 7.2MB 701-lsdk-net-support.patch for layerscape net controllers, like eTSEC on LS1021A, DPAA1 on LS1043A/LS1046A, DPAA2 on LS1088A/LS2088A, PFE on LS1012A, and ENETC and OCELOT/FELIX on LS1028A (which we will support in OpenWrt). And DPAA1/DPAA2 are much complicated including several hardware components. We are continuously to upstreaming kernel patches to Linux community, but it would take a very long time to accept all. To support full features of net controllers, we have to maintain and use SDK version driver except for the upstream version.

If you would like I set up a github for my linux tree for layerscape, I can do that. My linux tree cherry-picked layerscape specific patches on different IP/feature branches. I think it may help for reviewing. Or I think community reviewing may focus on files changed by patches, and the quality of patches. Any function issues, I will address. We will also have system test on OpenWrt Layerscape for June release. I have had basic tests on these patches.

Thanks.

**Comment by ynezz** [comment]
> I identified and cherry-picked only QorIQ Layerscape specific patches (943 patches) for OpenWrt. Then made the all-in-one patches as you see in patches-5.4 for each IP/feature.

Well, take a look at bcm27xx for example at `target/linux/bcm27xx/patches-5.4`, this changeset is `863 files changed, 310692 insertions(+), 3027 deletions(-)`, there is like ~500 patches in that directory.

I think, that having separate patches with proper commit description is better then having those amalgamated patch bombs.

Then in order to make the kernel .config changes visible, split those in two separate commits like for example 2cad8341daf399d1cd821132699313d8194e8d8f and badedbf007033b33d73327ae1758bc246a7ae635 so changes in kernel config symbols are easily visible in separate commit like in badedbf007033b33d73327ae1758bc246a7ae635.

**Comment by yangbolu1991** [comment]
@ynezz 
Thanks for your suggestions.
Actually the reason we used those amalgamated patch bombs for 5.4, and for previous 4.14, 4.9 etc. was because initially the reviewer did not like so many kernel patches. If the number of patches is not problem, I am happy to use separate patches. Let me work on a V2 patch-set.

Regarding to the suggestion on kernel .config, I will rework as your suggested.
Thank you very much!

**Comment by yangbolu1991** [comment]
@ynezz ,
I updated the pull request. Below are the changes of v2.
- Split kernel 5.4 support patch into several patches.
- Used separate kernel patches.
- Re-added config-5.4 from config-4.14.
- Moved u-boot env changes into uboot-layerscape patch.
- Rebased.

Thanks!

**Comment by yangbolu1991** [comment]
Any comments:)
Thanks!

**Comment by mcbridematt** [comment]
@yangbolu1991 There are a few patches no longer needed after the 5.4.33 is used in 23916bca61435ee80236f6aef70a3f0acacd4a93

target/linux/layerscape/patches-5.4/701-net-0405-soc-fsl-dpio-register-dpio-irq-handlers-after-dpio-c.patch
target/linux/layerscape/patches-5.4/804-crypto-0037-LF-717-crypto-dcp-fix-scatterlist-linearization-for-.patch
target/linux/layerscape/patches-5.4/804-crypto-0039-LF-983-crypto-caam-qi2-fix-chacha20-data-size-error.patch

So far it is working ok on our LS1088 board, I'll check LS1043 as well.

**Comment by yangbolu1991** [comment]
@mcbridematt 
Thanks a lot for verification and information.
I just rebased on latest code base, dropping the three kernel patches you mentioned.

Since there are too many kernel patches, I will have to rebase once mainline kernel version changes until this pull request is accepted.
Thanks.

**Comment by yangbolu1991** [comment]
@ynezz 
Rebased on latest code base, and did build test. No code changes.
Thanks.

**Comment by yangbolu1991** [comment]
@ynezz 
May I know if there is any update on reviewing? Do I need to improve anything of the patch-set?
Thank you very much:)

**Comment by yangbolu1991** [comment]
@ynezz 
Rebased on latest code base again, and did build test. No code changes.
Thanks.

**Comment by ynezz** [comment]
Merged, thanks!

**Pull request closed without merging**
