### PR TITLE
kernel: bump 5.15 to 5.15.72

### PR DESCRIPTION
**Pull request by graysky2**
Removed upstreamed:
  generic/pending-5.15/722-net-mt7531-only-do-PLL-once-after-the-reset.patch[1]
  bcm53xx/patches-5.15/082-v6.0-clk-iproc-Do-not-rely-on-node-name-for-correct-PLL-s.patch[2]

All other patches automatically rebased

Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.72&id=5de02ab84aeca765da0e4d8e999af35325ac67c2
2. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.72&id=ab5c5787ab5ecdc4a7ea20b4ef542579e1beb49d

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by Borromini** [comment]
Compile-tested: mvebu/cortexa72
Run-tested: mvebu/cortexa72 (RB5009UG+S+IN)

**Comment by anomeome** [comment]
Refresh required. Shouldn't CI be catching this?

**Comment by anomeome** [comment]
Right, but for some reason these kernel bumps do not seem to indicate an issue when one develops. @ynezz might know if this is expected.

**Comment by ynezz** [comment]
> Refresh required.

Can you be more specific, which part needs refresh?

> to indicate an issue when one develops

What kind of issues?

> Shouldn't CI be catching this?

It would catch that in case patches doesn't apply anymore for some reason, but there is no such patch dirty CI check as in packages repository.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in 911012662047ec133bdf4f5e490e0891cb782f3c.

**Pull request closed without merging**
