### PR TITLE
bzip2: add bzcat, bzcmp, bzdiff, bzgrep, bunzip2

### PR DESCRIPTION
**Pull request by zhanhb**

### CODE REVIEW

**Comment by zhanhb** [comment]
bzdiff requires package bindutils.

**Comment by adrianschmutzler** [comment]
Please add a commit description. Why are these changes needed?

**Comment by zhanhb** [comment]
Support full version shell utility `bunzip2`. Support more bzip2 utilies. These changes are not required for any other packages yet.

**Comment by hauke** [comment]
How big are these extra binaries? 
If they are bigger you could add them as extra packages.

**Comment by zhanhb** [comment]
These are shell scripts.
bzdiff 2140 bytes
bzgrep 2054 bytes

**Comment by zhanhb** [comment]
Maybe an extra packages `bzdiff` with only the script `bzdiff`, symlink and depends `diffutils` is needed.

**Comment by ynezz** [comment]
Commit description is still empty https://github.com/openwrt/openwrt/pull/3155/commits/718001a2161ce5db19d59d7b0726044d7d7a322b

**Comment by aparcar** [comment]
Looks okay to me, I'd merge this?

**Comment by adschm** [comment]
I still wonder _why_ we would need this change ...

**Comment by adschm** [comment]
Ping. Why is this marked as draft?

**Comment by zhanhb** [comment]
I' like to add all bzip utilities. But I've no idea how to process dependencies.

bzdiff => diffutils
bzless => less
bzmore => more
bzip2recover

**Comment by adschm** [comment]
This has not seen any change since the original post, and nobody seems to be particularly interested either.
So, I'm closing it now after about 3/4 of a year ...

**Pull request closed without merging**
