### PR TITLE
octeon: add USB3 support

### PR DESCRIPTION
**Pull request by ldebomy**
Fixes: FS#4086

USB3 is required for mounting usb stick on Ubiquiti EdgeRouter 6P, otherwise there is no /dev/sda1 

Signed-off-by: Laurent DEBOMY <laurent.debomy@canal-belletrud.fr>

### CODE REVIEW

**Comment by mans0n** [comment]
Hi, could you elaborate in the commit message?
There you can use a tag `Fixes: FS#4086`.

And this adds USB3 support to all octeon devices, please adapt the commit title. (it should start with "octeon:" like the PR title)

**Comment by francais01** [comment]
I've tried to build with these changes, but have been unable to get an initramfs kernel with XHCI. I've also used `make kernel_menuconfig` various times to adjust and tried removing USB 1.1 and 2 support, leaving just 3, but no matter what I do, when I load the kernel on the 6P there are no boot messages about XHCI and the flash drive is ignored. This may be a local issue to me, but I haven't found a cause yet. I'm running the build in a clean Ubuntu 20.04 VM. If you have any thoughts, please let me know.
(I'm using these instructions: https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem.)

**Comment by francais01** [comment]
> I've tried to build with these changes, but have been unable to get an initramfs kernel with XHCI. I've also used `make kernel_menuconfig` various times to adjust and tried removing USB 1.1 and 2 support, leaving just 3, but no matter what I do, when I load the kernel on the 6P there are no boot messages about XHCI and the flash drive is ignored. This may be a local issue to me, but I haven't found a cause yet. I'm running the build in a clean Ubuntu 20.04 VM. If you have any thoughts, please let me know. (I'm using these instructions: https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem.)

Never mind, I did a `git reset --hard` and deleted everything shown by `git status --ignored`, then I ran through the build steps again, but just did `make menuconfig` not `make kernel_menuconfig` and I got an initramfs that worked and can now read the flash drive.

**Review by francais01 — APPROVED** [review]
Worked for me on an EdgeRouter 6P.

**Comment by hauke** [comment]
I am surprised that this works.
The Ubiquiti EdgeRouter 6P uses the `synopsys,dwc3` USB3 controller which needs `CONFIG_USB_DWC3`
I would prefer this pull request: #3854

**Comment by francais01** [comment]
FYI, this is from dmesg on my 6P, now running a snapshot build applied with `sysupgrade`:
```
[   16.182252] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[   16.208299] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[   16.213810] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
[   16.221582] xhci-hcd xhci-hcd.0.auto: hcc params 0x0220f06d hci version 0x100 quirks 0x0000000002010010
[   16.231033] xhci-hcd xhci-hcd.0.auto: irq 44, io mem 0x1680000000000
[   16.238061] hub 1-0:1.0: USB hub found
[   16.241899] hub 1-0:1.0: 1 port detected
[   16.246034] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[   16.251564] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
[   16.259233] xhci-hcd xhci-hcd.0.auto: Host supports USB 3.0 SuperSpeed
[   16.265849] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[   16.274484] hub 2-0:1.0: USB hub found
[   16.278283] hub 2-0:1.0: 1 port detected
[   16.284549] usbcore: registered new interface driver uas
[   16.290124] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
```

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in e900779e6f15a3a00a2f9003dd68a43aa0ef88e8.

**Pull request closed without merging**
