### PR TITLE
tools/zstd: enable position independent code compilation

### LINKED ISSUE #15247: tools/llvm-bpf: compilation fails due to zstd
### Describe the bug

llvm-bpf fails to compile in snapshot and 23.05 HEAD due to zstd

```
[2225/3517] Linking CXX shared library lib/libLLVM-15.so
FAILED: lib/libLLVM-15.so 
: && /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/bin/g++ -fPIC -O2 -I/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -DNDEBUG  -L/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/lib -Wl,-z,defs -Wl,-z,nodelete   -Wl,-rpath-link,/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/build_dir/host/llvm-project-15.0.7.src/build/./lib  -Wl,--gc-sections  -Wl,-Bsymbolic-functions -shared -Wl,-soname,libLLVM-15.so -o lib/libLLVM-15.so tools/llvm-shlib/CMakeFiles/LLVM.dir/libllvm.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib"  -Wl,--version-script,/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/build_dir/host/llvm-project-15.0.7.src/build/./lib/tools/llvm-shlib/simple_version_script.map  -Wl,--whole-archive  lib/libLLVMDemangle.a  lib/libLLVMSupport.a  lib/libLLVMCore.a  lib/libLLVMFuzzerCLI.a  lib/libLLVMFuzzMutate.a  lib/libLLVMFileCheck.a  lib/libLLVMInterfaceStub.a  lib/libLLVMIRReader.a  lib/libLLVMCodeGen.a  lib/libLLVMSelectionDAG.a  lib/libLLVMAsmPrinter.a  lib/libLLVMMIRParser.a  lib/libLLVMGlobalISel.a  lib/libLLVMBinaryFormat.a  lib/libLLVMBitReader.a  lib/libLLVMBitWriter.a  lib/libLLVMBitstreamReader.a  lib/libLLVMDWARFLinker.a  lib/libLLVMExtensions.a  lib/libLLVMFrontendOpenACC.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMTransformUtils.a  lib/libLLVMInstrumentation.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMScalarOpts.a  lib/libLLVMipo.a  lib/libLLVMVectorize.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMCoroutines.a  lib/libLLVMCFGuard.a  lib/libLLVMLinker.a  lib/libLLVMAnalysis.a  lib/libLLVMLTO.a  lib/libLLVMMC.a  lib/libLLVMMCParser.a  lib/libLLVMMCDisassembler.a  lib/libLLVMMCA.a  lib/libLLVMObjCopy.a  lib/libLLVMObject.a  lib/libLLVMObjectYAML.a  lib/libLLVMOption.a  lib/libLLVMRemarks.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMDebugInfoGSYM.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMSymbolize.a  lib/libLLVMDWP.a  lib/libLLVMExecutionEngine.a  lib/libLLVMInterpreter.a  lib/libLLVMJITLink.a  lib/libLLVMMCJIT.a  lib/libLLVMOrcJIT.a  lib/libLLVMOrcShared.a  lib/libLLVMOrcTargetProcess.a  lib/libLLVMRuntimeDyld.a  lib/libLLVMTarget.a  lib/libLLVMBPFCodeGen.a  lib/libLLVMBPFAsmParser.a  lib/libLLVMBPFDisassembler.a  lib/libLLVMBPFDesc.a  lib/libLLVMBPFInfo.a  lib/libLLVMAsmParser.a  lib/libLLVMLineEditor.a  lib/libLLVMProfileData.a  lib/libLLVMCoverage.a  lib/libLLVMPasses.a  lib/libLLVMTextAPI.a  lib/libLLVMDlltoolDriver.a  lib/libLLVMLibDriver.a  lib/libLLVMXRay.a  lib/libLLVMWindowsDriver.a  lib/libLLVMWindowsManifest.a  -Wl,--no-whole-archive  lib/libLLVMExtensions.a  lib/libLLVMExecutionEngine.a  lib/libLLVMJITLink.a  lib/libLLVMOrcTargetProcess.a  lib/libLLVMOrcShared.a  lib/libLLVMRuntimeDyld.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMCoroutines.a  lib/libLLVMSelectionDAG.a  lib/libLLVMAsmPrinter.a  lib/libLLVMCodeGen.a  lib/libLLVMipo.a  lib/libLLVMIRReader.a  lib/libLLVMAsmParser.a  lib/libLLVMBitWriter.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMInstrumentation.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMVectorize.a  lib/libLLVMLinker.a  lib/libLLVMTransformUtils.a  lib/libLLVMTarget.a  lib/libLLVMAnalysis.a  lib/libLLVMMCDisassembler.a  lib/libLLVMProfileData.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMObject.a  lib/libLLVMBitReader.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMTextAPI.a  lib/libLLVMBinaryFormat.a  lib/libLLVMOption.a  lib/libLLVMSupport.a  lib/libLLVMDemangle.a  -lrt  -ldl  -lm  /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/lib/libz.a  /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/lib/libzstd.a && :
/usr/bin/ld: /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/lib/libzstd.a(zstd_common.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:56: /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/build_dir/host/llvm-project-15.0.7.src/.built] Error 1
make[3]: Leaving directory '/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/tools/llvm-bpf'
time: tools/llvm-bpf/compile#40.46#25.68#63.74
    ERROR: tools/llvm-bpf failed to build.
make[2]: *** [tools/Makefile:230: tools/llvm-bpf/compile] Error 1
make[2]: Leaving directory '/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src'
make[1]: *** [tools/Makefile:226: /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/stamp/.tools_compile_nyyyyyynnnyyynynyyyyyyynyyynnynyyynynnyyyyyynyyyyyyyyyyynynnyyyyyyyy] Error 2
make[1]: Leaving directory '/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src'
make: *** [/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/include/toplevel.mk:233: world] Error 2
```

### OpenWrt version

r26007-d89e898edf

### OpenWrt release

snapshot

### OpenWrt target/subtarget

rockchip/armv8

### Device

friendlyarm_nanopi-r4s

### Image kind

Self-built image

### Steps to reproduce

```
./scripts/feeds update -i -f &&
./scripts/feeds update -a -f &&
./scripts/feeds install -a -f
(I modify .config manually here)
make -j1 V=s defconfig download clean world
```

### Actual behaviour

```
[2225/3517] Linking CXX shared library lib/libLLVM-15.so
FAILED: lib/libLLVM-15.so 
: && /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/bin/g++ -fPIC -O2 -I/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -DNDEBUG  -L/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/lib -Wl,-z,defs -Wl,-z,nodelete   -Wl,-rpath-link,/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/build_dir/host/llvm-project-15.0.7.src/build/./lib  -Wl,--gc-sections  -Wl,-Bsymbolic-functions -shared -Wl,-soname,libLLVM-15.so -o lib/libLLVM-15.so tools/llvm-shlib/CMakeFiles/LLVM.dir/libllvm.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib"  -Wl,--version-script,/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/build_dir/host/llvm-project-15.0.7.src/build/./lib/tools/llvm-shlib/simple_version_script.map  -Wl,--whole-archive  lib/libLLVMDemangle.a  lib/libLLVMSupport.a  lib/libLLVMCore.a  lib/libLLVMFuzzerCLI.a  lib/libLLVMFuzzMutate.a  lib/libLLVMFileCheck.a  lib/libLLVMInterfaceStub.a  lib/libLLVMIRReader.a  lib/libLLVMCodeGen.a  lib/libLLVMSelectionDAG.a  lib/libLLVMAsmPrinter.a  lib/libLLVMMIRParser.a  lib/libLLVMGlobalISel.a  lib/libLLVMBinaryFormat.a  lib/libLLVMBitReader.a  lib/libLLVMBitWriter.a  lib/libLLVMBitstreamReader.a  lib/libLLVMDWARFLinker.a  lib/libLLVMExtensions.a  lib/libLLVMFrontendOpenACC.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMTransformUtils.a  lib/libLLVMInstrumentation.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMScalarOpts.a  lib/libLLVMipo.a  lib/libLLVMVectorize.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMCoroutines.a  lib/libLLVMCFGuard.a  lib/libLLVMLinker.a  lib/libLLVMAnalysis.a  lib/libLLVMLTO.a  lib/libLLVMMC.a  lib/libLLVMMCParser.a  lib/libLLVMMCDisassembler.a  lib/libLLVMMCA.a  lib/libLLVMObjCopy.a  lib/libLLVMObject.a  lib/libLLVMObjectYAML.a  lib/libLLVMOption.a  lib/libLLVMRemarks.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMDebugInfoGSYM.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMSymbolize.a  lib/libLLVMDWP.a  lib/libLLVMExecutionEngine.a  lib/libLLVMInterpreter.a  lib/libLLVMJITLink.a  lib/libLLVMMCJIT.a  lib/libLLVMOrcJIT.a  lib/libLLVMOrcShared.a  lib/libLLVMOrcTargetProcess.a  lib/libLLVMRuntimeDyld.a  lib/libLLVMTarget.a  lib/libLLVMBPFCodeGen.a  lib/libLLVMBPFAsmParser.a  lib/libLLVMBPFDisassembler.a  lib/libLLVMBPFDesc.a  lib/libLLVMBPFInfo.a  lib/libLLVMAsmParser.a  lib/libLLVMLineEditor.a  lib/libLLVMProfileData.a  lib/libLLVMCoverage.a  lib/libLLVMPasses.a  lib/libLLVMTextAPI.a  lib/libLLVMDlltoolDriver.a  lib/libLLVMLibDriver.a  lib/libLLVMXRay.a  lib/libLLVMWindowsDriver.a  lib/libLLVMWindowsManifest.a  -Wl,--no-whole-archive  lib/libLLVMExtensions.a  lib/libLLVMExecutionEngine.a  lib/libLLVMJITLink.a  lib/libLLVMOrcTargetProcess.a  lib/libLLVMOrcShared.a  lib/libLLVMRuntimeDyld.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMCoroutines.a  lib/libLLVMSelectionDAG.a  lib/libLLVMAsmPrinter.a  lib/libLLVMCodeGen.a  lib/libLLVMipo.a  lib/libLLVMIRReader.a  lib/libLLVMAsmParser.a  lib/libLLVMBitWriter.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMInstrumentation.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMVectorize.a  lib/libLLVMLinker.a  lib/libLLVMTransformUtils.a  lib/libLLVMTarget.a  lib/libLLVMAnalysis.a  lib/libLLVMMCDisassembler.a  lib/libLLVMProfileData.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMObject.a  lib/libLLVMBitReader.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMTextAPI.a  lib/libLLVMBinaryFormat.a  lib/libLLVMOption.a  lib/libLLVMSupport.a  lib/libLLVMDemangle.a  -lrt  -ldl  -lm  /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/lib/libz.a  /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/lib/libzstd.a && :
/usr/bin/ld: /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/lib/libzstd.a(zstd_common.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:56: /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/build_dir/host/llvm-project-15.0.7.src/.built] Error 1
make[3]: Leaving directory '/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/tools/llvm-bpf'
time: tools/llvm-bpf/compile#40.46#25.68#63.74
    ERROR: tools/llvm-bpf failed to build.
make[2]: *** [tools/Makefile:230: tools/llvm-bpf/compile] Error 1
make[2]: Leaving directory '/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src'
make[1]: *** [tools/Makefile:226: /home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/staging_dir/host/stamp/.tools_compile_nyyyyyynnnyyynynyyyyyyynyyynnynyyynynnyyyyyynyyyyyyyyyyynynnyyyyyyyy] Error 2
make[1]: Leaving directory '/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src'
make: *** [/home/bryan/.local/bin/openwrtbuilder/src/r4s/snapshot-src/include/toplevel.mk:233: world] Error 2
```

### Expected behaviour

llvm-bpf compiles without errors

### Additional info

Tested on fedora 39 and fedora 40, it is not gcc dependent

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by cryobry**
Fixes tools/llvm-bpf compilation errors

Fixes https://github.com/openwrt/openwrt/issues/15247.

### CODE REVIEW

**Comment by neheb** [comment]
another consequence of moving away from meson looks like.

**Comment by robimarko** [comment]
@neheb Not really if 23.05 has the same issue since it still uses meson for ZSTD

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by neheb** [comment]
> @neheb Not really if 23.05 has the same issue since it still uses meson for ZSTD
meson has PIC enabled by default.

**Comment by robimarko** [comment]
@neheb The linked issue claimed that 23.05 failed in the same way but after testing that is not the case and LLVM compiles fine with it.

**Comment by neheb** [comment]
right. PIC is enabled by default in meson for both static and shared libraries for performance reasons. autotools has it enabled by default only for shared libraries IIRC. PIE is not enabled by default.

**Pull request merged**
