### PR TITLE
kernel: bump 5.15 to 5.15.133

### PR DESCRIPTION
**Pull request by graysky2**
Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.133

Removed upstreamed:
	bcm47xx/patches-5.15/101-v5.18-mtd-rawnand-brcmnand-Allow-SoC-to-provide-I-O-operations.patch[1]

Cherry picked build fix.[2] All other patches automatically rebased. All other patches automatically rebased.

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.133&id=56cf9f446b331414a15ef0e8dedf23583ec2c427
2. https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/queue-5.15/fix-up-backport-of-136191703038-interconnect-teach-l.patch

Build system: x86_64
Build-tested: ramips/tplink_archer-a6-v3
Run-tested: ramips/tplink_archer-a6-v3

### CODE REVIEW

**Comment by graysky2** [comment]
Any thoughts on why tegra/generic failed?

**Comment by DragonBluep** [comment]
> Any thoughts on why tegra/generic failed?

It's an upstream issue, will be fixed on next release.
https://lore.kernel.org/all/e56ced8d-d09d-469b-80df-0cc2bdd943f4@roeck-us.net/

**Comment by hauke** [comment]
You could just chery pick this patch frm the next stable version: https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/queue-5.15/fix-up-backport-of-136191703038-interconnect-teach-l.patch

**Comment by graysky2** [comment]
@hauke - good call on the CP.  This is probably good to merge.

**Pull request merged**
