### PR TITLE
tools/meson: update to 0.61.1

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by aparcar** [comment]
CI says no

**Comment by aparcar** [comment]
In other words, please add a commit message what changed on meson.

**Comment by neheb** [comment]
Added based on: https://mesonbuild.com/Release-notes-for-0-61-0.html

**Comment by neheb** [comment]
with version 0.62, python 3.6 cannot be used. This includes Ubuntu 18.04 LTS, which I believe has python 3.7 or up available.

**Comment by hauke** [comment]
Thank you for your patch, I applied it to master in fb6cf22866b3bb6dfcbee0659f785982d071c863.

**Pull request closed without merging**
