### PR TITLE
18.06: ar71xx/ipq40xx: Fix sysupgrade for Allnet and OpenMesh devices

### PR DESCRIPTION
**Pull request by ecsv**
There are still upgrade scripts which use the hook sysupgrade_pre_upgrade to prepare the ramdisk for the use of fw_setenv and fw_printenv:

* target/linux/ar71xx/base-files/lib/upgrade/allnet.sh
* target/linux/ar71xx/base-files/lib/upgrade/openmesh.sh
* target/linux/ipq40xx/base-files/lib/upgrade/openmesh.sh

But this hook was removed without any replacement in 6a27c2f4b1a4 ("base-files: drop fwtool_pre_upgrade"). Not running the hooks can either prevent a successful upgrade or brick the device.

And the behavior of install_bin was also changed in 438dcbfe74a6 ("base-files: automatically handle paths and symlinks for RAMFS_COPY_BIN") to ignore the second parameter. This then resulted in a not created fw_setenv (which is called by these scripts.

----

@NeoRaider This is the OpenWrt 18.06 PR mentioned in #1421.

### CODE REVIEW

**Comment by mkresin** [comment]
For the stable branch I would prefer to limit changes to a minimum and bring back the `run_hooks "" $sysupgrade_pre_upgrade` instead. It was around for ages and was obviously dropped accidentally with the mentioned commit.

Any opinion on my proposal?

**Comment by ecsv** [comment]
@mkresin: I have now added the requested changes but it is not tested yet. I will do that after lunch.

**Comment by ecsv** [comment]
@mkresin Tested successfully on OM2P-HS

**Comment by mkresin** [comment]
merged, thanks!

**Pull request closed without merging**
