### PR TITLE
lantiq: update ltq-ifxos and use default dsl_cpe_api device name

### PR DESCRIPTION
**Pull request by dhewg**
These are two changes preparing the upcoming ipq40xx/VR11 support.
Both are affecting packages for the current lantiq/VR9 target.

At this point, this has only been compile time tested on lantiq.
Can someone please verify that this doesn't break DSL on that platform?

### CODE REVIEW

**Comment by janh** [comment]
In a quick test on a Fritzbox 7412 connected to an ALL126AM2 everything works. I didn't test on my actual DSL line, though.

**Comment by dhewg** [comment]
So far so good, thanks!
Let's see/hope if someone can still test the DSL part

**Comment by janh** [comment]
> Let's see/hope if someone can still test the DSL part

I *did* test the DSL part, just connected to my own VTU-C modem instead of the line from by internet provider.

**Comment by dhewg** [comment]
Oh, sorry, didn't look up what that product is.
Perfect then ;)

**Comment by jospezial** [comment]
Tested on lantiq/VR9 VGV7510KW22 (o2 Box 6431)
No regressions on VDSL and telephony with asterisk 19.1.

**Comment by dhewg** [comment]
Awesome, thanks! Removing RFT tag then

**Review by hauke — APPROVED** [review]

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in 5ee1e045174bad1b7f2754bb022346acc60220f5 and 9d878d84227ffac92b5616fb9a4253cae28fc580.

**Pull request closed without merging**
