### PR TITLE
at91: add support for SAMA7G5 SoC on kernel v5.10

### PR DESCRIPTION
**Pull request by claudiubeznea**
Hi,

The following patches add support for Microchip SAMA7G5 SoC by
backporting the remaining patches from mainline kernel. Along with SoC
support board support has been added (board is called SAMA7G5-EK).

Patches 1/4, 2/4 are preparatory patches to update AT91Bootstrap and
U-Boot AT91.

Thank you,
Claudiu Beznea

### CODE REVIEW

**Comment by ynezz** [comment]
Thank, merged.

**Comment by ynezz** [comment]
Seems like something changed meanwhile as buildbot build fails https://buildbot.openwrt.org/master/images/#/builders/68/builds/469 althought my build test went fine https://gitlab.com/ynezz/openwrt/-/jobs/2133825737

**Comment by claudiubeznea** [comment]
I'm checking on my side with latest master

**Comment by claudiubeznea** [comment]
On my side build seems fixed if reverting 97158fe10e60 ("kernel: package ramoops pstore-ram crash log storage")

**Comment by ynezz** [comment]
> On my side build seems fixed if reverting 97158fe 
> <https://github.com/openwrt/openwrt/commit/97158fe10e6090a8b21629df130734bac53f87ee> ("kernel: package ramoops pstore-ram crash log storage")

Thank you for looking into it, but reverting is not an option. Seems 
like kernel configuration needs to be updated.

**Comment by claudiubeznea** [comment]
Yes, I'm looking to it. sama5 has PM_DEBUG enabled without DPM_WATCHDOG which triggers the failure. I'm checking to see how it behaves if disabling PM_DEBUG on sama5 as there is no need for it an official image.

**Comment by claudiubeznea** [comment]
I've created a new PR: https://github.com/openwrt/openwrt/pull/9341

**Pull request closed without merging**
