### PR TITLE
README: replace logo.svg with include/logo.png

### PR DESCRIPTION
**Pull request by aparcar**
Some Git hoster (e.g. sr.ht) disable hosting of svg images (xml) to
avoid XSS attacks. To show the logo correctly on all code hosters use a
"safe" PNG image.

Also move image to include/ folder to lower autocomplete churn with the
`logs/` folder. While at it, replace absolute logo path and make it
relative, as this may break other code hosters as well.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
https://git.sr.ht/~aparcar/openwrt

**Comment by hnyman** [comment]
Do we need to delete logo.svg?
Both .svg and .png might be available in the source repo, but just .png would be linked in README page.

**Comment by bobafetthotmail** [comment]
yeah, please leave the svg logo too, it's useful for those that want to add it to a page or make icons or other stuff.

**Comment by aparcar** [comment]
Thanks for the feedback, merged.

**Pull request closed without merging**
