### PR TITLE
iproute2: fix configure script, feature detection, plugins and enable BPF object loading

### PR DESCRIPTION
**Pull request by guidosarducci**
**Maintainers/Distribution List**: @RussellSenior  @ldir-EDB0 
**Compile tested**: mips32-be-malta, openwrt-18.06 & master branch
**Run tested**: mips32-be-malta, openwrt-18.06 & master branch
**Related PRs**: https://github.com/openwrt/openwrt/pull/1615 (merged), https://github.com/openwrt/openwrt/pull/1626, #1648 (merged)

**Description**:
This PR captures a set of related changes for the `iproute2` suite of utilities, primarily `tc`. The end goal is to enable tc classifiers and actions using IPSET/other ematch and BPF, and support ip loading of XDP/BPF programs.

1. Fix out-of-date configure script patches and broken feature detection for IPSET and xtables support.
2. Simplify libelf1 linkage for supporting loading of eBPF object files for tc classifiers and actions, and BPF/XDP object files with ip.
3. Fix support for .so plugins (e.g. tc's act_ipt) and reduce executable sizes.

**Sizing Considerations**:
There are small changes to core package sizes, mainly due to common linking of `iproute2` `libutil.a` which depends on `libelf` if detected together with package `tc` being selected.

1. Slight size increase to common `iproute2` packages:
   - `tc_4.19.0-9_mips_24kc.ipk`: 141647 (+14 KB change with shared lib and BPF support)
   - `ip-full_4.19.0-9_mips_24kc.ipk`: 168233 (+9 KB change with XDP/BPF support)
   - `ip-tiny_4.19.0-9_mips_24kc.ipk`: 120793 (~same size as old version)

Appreciate any feedback!

EDIT: add missing `ematch_map` file moved to `base-files` and merged.
EDIT: fix for linker error (first reported by @wongsyrone ) upstreamed and backported.
EDIT: updated sizing to show improvements after introducing variants, enabling shared libs and BPF.
EDIT: updated to reflect latest build/commits.

### CODE REVIEW

**Comment by wongsyrone** [comment]
The `iproute2: tc: fix linker errors related to xtables ` patch looks good to me.

I skimmed through the patch, it seems you add libelf as PKG_BUILD_DEPENDS and runtime dependency. If I understand it correctly, PKG_BUILD_DEPENDS doesn't involve runtime dependency, e.g.: headers from other library or static .a file

**Comment by guidosarducci** [comment]
@wongsyrone Thanks for looking over this. BTW, were you trying to get the linker patch pushed upstream after you found the problem with LDFLAGS vs. LDLIBS? 

I'm using PKG_BUILD_DEPENDS strictly for a build-time dependency, to pre-install elfutils's `pkg-config` library files, which are used by the iproute2 `configure` script for `libelf` detection. (And note this PR depends on my elfutils PR https://github.com/openwrt/openwrt/pull/1615)

Is that what you were referring to?

**Comment by jow-** [comment]
Can't we just disable `libelf` support? I wonder why iproute2 needs it at all, surely not to just dlopen its match plugins...

**Comment by guidosarducci** [comment]
@wongsyrone 
>I didn't try to submit it upstream, if you want to do so, go ahead.
If you already add it to DEPENDS := +libelf1, the build system deals libelf first.

I'd never worked with upstream before, so hoped you'd already started. :-)
As far as PKG_BUILD_DEPENDS goes, I seem to remember a build problem without it, but trying again now after your prompting confirms it's not needed. Thanks, I'll update that commit.

@jow- 
>Can't we just disable libelf support? I wonder why iproute2 needs it at all, surely not to just dlopen its match plugins...

No, it's not related to match plugins. The `tc` utility needs `libelf` to load user-supplied eBPF object files for use as classifiers or actions (for kernel modules cls_bpf and act_bpf).

I think the dlopening of plugins (as .so files) you refer to has been disabled for a long time, ever since the iproute2 Makefile flag `SHARED_LIBS` was set blank.

**Comment by wongsyrone** [comment]
Submitted upstream as https://patchwork.ozlabs.org/patch/1011853/

**Comment by guidosarducci** [comment]
@wongsyrone Thanks, that's very helpful.

Also @jow and @ldir-EDB0 :
> @guidosarducci commented 18 hours ago
I think the dlopening of plugins (as .so files) you refer to has been disabled for a long time, ever since the iproute2 Makefile flag `SHARED_LIBS` was set blank.

Further to this, going back a few versions I've never been able to use the `ipt` / `xt` tc action for iptables targets: e.g.
```
tc filter add dev lo parent 1: protocol ip u32 match u32 0 0 action xt -j DSCP --set-dscp-class EF
Bad action type xt
```
Seems like there are multiple pieces to the problem. The current package Makefile defines `SHARED_LIBS=""`, which stubs `dlopen()` and disables loading of both iptables `.so` files and tc's own `m_xt.so` (which is missing from the package anyway). After building with `SHARED_LIBS="y"`, `tc` doesn't even recognize compiled-in modules such as `fq_codel`, meaning there's a problem with dynamic symbols. It could be the build process, or `gcc` or even the `dlsym()` in `musl`.

I'll continue looking into this but wanted to push the commits I had first. Does anyone know if `SHARED_LIBS="y"` or "action xt/ipt" worked in the far past, or other relevant OpenWrt history for `tc`/`iproute2`? Thanks...

**Comment by wongsyrone** [comment]
Fix accepted https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=6ddb36c3a9686df1cca2f4d06518395f1eb9d5cc

**Comment by guidosarducci** [comment]
Another quick update... I've figured out the various issues related to supporting `SHARED_LIBS="y"` and "action xt/ipt", and will push the commits.

I've also made further use of package variants to keep the `ip-tiny` package the same size as before (see https://github.com/openwrt/openwrt/pull/1627#issue-237931875), important because of the ~47 KB defference between `ip-tiny` and `ip-full`.

I also experimented with `tc` variants `tc-tiny` (same as old size 128 KB) and `tc-full` (142 KB).

Question for @ldir-EDB0 or @jow- : are these `tc` variants worth it in light of the only 14 KB size difference?

**Comment by ldir-EDB0** [comment]
For 14K I'm not inclined to keep the tiny variant, but then I'm not up against hard flash space limits...yet.  @jow may have a different and more sensible opinion.

**Comment by guidosarducci** [comment]
That was my first thought too, but backwards compatibility and paranoia around flash space make me want to keep a `tc-tiny` variant.

To put into perspective, here are the size changes vs. the per-OpenWrt-releases (for ar71xx/mips_24kc):

| Package| LEDE-17.01.5|OpenWrt-18.06.1|master@2018-12-16|
| --- | --- | --- | --- |
| **tc** | 95.8 KB | 124 KB | 128 KB |
| **ip-tiny** | 79.5 KB | 118 KB | 121 KB |
| **ip-full** | 114 KB | 156 KB | 159 KB |

Now pushing commit updates using tc variants and supporting `SHARED_LIBS="y"` with "action xt/ipt, and BPF support. Much tidier now after rebase/squashing...

**Comment by guidosarducci** [comment]
Unlike `ip-full` and `ip-tiny` variants which don't share common files and can be installed together, my`tc-tiny` and `tc-full` variants each include the file `/etc/hotplug.d/iface/15-teql`. This means they conflict when trying to install both together.

Question for @ldir-EDB0  or @jow-  : How best to deal with this? The `ip` variants both use `/etc/iproute2/rt_protos` and `/etc/iproute2/rt_tables`, and place them into `base-files` to avoid conflict it seems. Is the same thing reasonable for a hotplug script?

BTW, I noticed `/etc/hotplug.d/iface/15-teql` references kernel module `sch_teql`, which is part of package `kmod-sched`. But `tc` (where the hotplug script resides) depends on `kmod-sched-core` **not** `kmod-sched`. Could the hotplug script could go into `kmod-sched`?

**Comment by ldir-EDB0** [comment]
Good questions 'cos I don't know the answer and your exploring areas of the build/package system I struggle with.  There's a PROVIDES directive which may help here, e.g. tc-tiny & tc-full both provide tc and may be the way out.  dnsmasq uses that technique to handle its many variants but I honestly don't know if this is the correct/best solution in this case. @ldir-EDB0 seeks a higher power... @jow- :-)

**Comment by jow-** [comment]
Yes, moving the hotplug script into the kmod seems reasonable.

**Comment by guidosarducci** [comment]
Alright, I'll move the hotplug script into the same package `kmod-sched` which contains the related module `sch_teql`. I guess I'll fold that into my "kernel module" PR, #1626 . (Also please look at my questions there for you guys. Thanks!)

@jow- Could you share an opinion on https://github.com/openwrt/openwrt/pull/1627#issuecomment-447619962? I've now created package variants `tc-tiny` and `tc-full`, which can save 14 KB when space-constrained. Compared to the 38 KB difference between `ip-tiny` and `ip-full`, is that 14 KB justified IYO?

**Comment by guidosarducci** [comment]
After further consideration and feedback, I've reworked to keep the single `tc`utility with support for shared object plugins and BPF object loading. Will rebase this version against master since there have been several related commits.

Once again, Github display of changes will likely be broken, so please review the [master-update-iproute](https://github.com/guidosarducci/openwrt/commits/master-update-iproute) branch directly. If reviewers wish, I could try creating a new PR with working display of changes.

**Comment by tohojo** [comment]
LGTM; nice work, thanks for doing this! :)

**Comment by guidosarducci** [comment]
Updated/rebased for the latest `master` branch changes and retested.
As with #1626 , I'd like to get this merged given the various fixes/cleanup this brings, alongside up-to-date BPF support. Pinging @ldir-EDB0 @hauke @tohojo @jow- for feedback/decision. Thanks all!

**Comment by ldir-EDB0** [comment]
@guidosarducci  I'll poke this tomorrow and commit it unless someone says no - it's hung around for too long - I suspect it's not been committed 'cos people don't want to break the build

**Comment by ldir-EDB0** [comment]
Merged into master!

**Comment by ldir-EDB0** [comment]
@guidosarducci   Hi Tony - https://github.com/openwrt/openwrt/pull/1627/commits/1beadacb5cdc0608b16a0c0451f20741336bb6b8 is breaking install of some iproute utilities e.g. nstat, ipbridge.  currently they're only installed if the ip-tiny variant is selected while this is not the case for the full-variant.  From IRC:

<dedeckeh>	Yes; I wonder why he makes the installation of ip-bridge,ss, nstat,devlink, rdma dependant on the ip-tiny variant - ip-full should install them as well, similar for the InstallDev step.

I think that's an oversight but your input would be appreciated!

**Comment by dedeckeh** [comment]
@guidosarducci I've reverted commits https://github.com/openwrt/openwrt/commit/e6d84fa8864e7bbbcec139dd09a2922a06f5b2a0, https://github.com/openwrt/openwrt/commit/26681fa6a6fcbec0024906eb8367e9a3160521fb, https://github.com/openwrt/openwrt/commit/fc80ef3613465e60257a5ddf0674debe45b09180, https://github.com/openwrt/openwrt/commit/248797834bf21916ddf663edc96d86ee5377850e for now as it breaks the installation of the iproute2 utilities ip-bridge, ss, nstat, devlink, rdma for the ip-full variant

**Comment by guidosarducci** [comment]
@ldir-EDB0 @dedeckeh 
> Hi Tony - [1beadac](https://github.com/openwrt/openwrt/commit/1beadacb5cdc0608b16a0c0451f20741336bb6b8) is breaking install of some iproute utilities e.g. nstat, ipbridge. currently they're only installed if the ip-tiny variant is selected while this is not the case for the full-variant.

Grrrr. Most of my coverage testing involved enabling and installing **all** the iproute2 packages towards the end of my work, so I can understand the oversight. Official repos that build all packages would be fine, but a custom image without ip-tiny is a problem...

>From IRC:
> 
> Yes; I wonder why he makes the installation of ip-bridge,ss, nstat,devlink, rdma dependant on the ip-tiny variant - ip-full should install them as well, similar for the InstallDev step.

I think the commit description is fairly clear. Not sure if folks are aware of this, but the non-variant packages (rdma, ss, etc.) are rebuilt/overwritten every time a variant package (tc, ip-full, ip-tiny) is built. This has consequences for size and reproducibility because the final non-variant packages may/may not include some dependencies (e.g. libelf), depending on the build order of the variant packages (which seems random during parallel builds). So, for example, ss might have a useless dependency on libelf1, or might not.

My changes to InstallDev and the non-variant package builds was to try consistently eliminating useless dependencies and size overheads.
> 
> @guidosarducci I've reverted commits [e6d84fa](https://github.com/openwrt/openwrt/commit/e6d84fa8864e7bbbcec139dd09a2922a06f5b2a0), [26681fa](https://github.com/openwrt/openwrt/commit/26681fa6a6fcbec0024906eb8367e9a3160521fb), [fc80ef3](https://github.com/openwrt/openwrt/commit/fc80ef3613465e60257a5ddf0674debe45b09180), [2487978](https://github.com/openwrt/openwrt/commit/248797834bf21916ddf663edc96d86ee5377850e) for now as it breaks the installation of the iproute2 utilities ip-bridge, ss, nstat, devlink, rdma for the ip-full variant

Since the issue is with the tiny-variant conditional installation, why not simply remove that rather than reverting most of the commits and the bulk of the work? Or have the relevant discussion first?

I have a tested update that drops the conditional installation: cfed7610de2e27107c85da5f55efbec76ac45af6.

How to apply this? Revert the reversions in master and then apply the above? A new PR reapplying the the same reverted commits followed by the above? In any case, the current PR has important historical value for it's changes, so we should avoid editing it.

**Comment by dedeckeh** [comment]
> @ldir-EDB0 @dedeckeh
> 
> > Hi Tony - [1beadac](https://github.com/openwrt/openwrt/commit/1beadacb5cdc0608b16a0c0451f20741336bb6b8) is breaking install of some iproute utilities e.g. nstat, ipbridge. currently they're only installed if the ip-tiny variant is selected while this is not the case for the full-variant.
> 
> Grrrr. Most of my coverage testing involved enabling and installing **all** the iproute2 packages towards the end of my work, so I can understand the oversight. Official repos that build all packages would be fine, but a custom image without ip-tiny is a problem...
> 
> > From IRC:
> > Yes; I wonder why he makes the installation of ip-bridge,ss, nstat,devlink, rdma dependant on the ip-tiny variant - ip-full should install them as well, similar for the InstallDev step.
> 
> I think the commit description is fairly clear. Not sure if folks are aware of this, but the non-variant packages (rdma, ss, etc.) are rebuilt/overwritten every time a variant package (tc, ip-full, ip-tiny) is built. This has consequences for size and reproducibility because the final non-variant packages may/may not include some dependencies (e.g. libelf), depending on the build order of the variant packages (which seems random during parallel builds). So, for example, ss might have a useless dependency on libelf1, or might not.
> 
> My changes to InstallDev and the non-variant package builds was to try consistently eliminating useless dependencies and size overheads.
> 
> > @guidosarducci I've reverted commits [e6d84fa](https://github.com/openwrt/openwrt/commit/e6d84fa8864e7bbbcec139dd09a2922a06f5b2a0), [26681fa](https://github.com/openwrt/openwrt/commit/26681fa6a6fcbec0024906eb8367e9a3160521fb), [fc80ef3](https://github.com/openwrt/openwrt/commit/fc80ef3613465e60257a5ddf0674debe45b09180), [2487978](https://github.com/openwrt/openwrt/commit/248797834bf21916ddf663edc96d86ee5377850e) for now as it breaks the installation of the iproute2 utilities ip-bridge, ss, nstat, devlink, rdma for the ip-full variant
> 
> Since the issue is with the tiny-variant conditional installation, why not simply remove that rather than reverting most of the commits and the bulk of the work? Or have the relevant discussion first?
As the commits caused regression it's not an option to keep them in; besides iproute2 utilities not being installed user applications linking to libnetlink.a will also fail in case ip-full is selected
> 
> I have a tested update that drops the conditional installation: [cfed761](https://github.com/openwrt/openwrt/commit/cfed7610de2e27107c85da5f55efbec76ac45af6).
> 
> How to apply this? Revert the reversions in master and then apply the above? A new PR reapplying the the same reverted commits followed by the above? In any case, the current PR has important historical value for it's changes, so we should avoid editing it.
I'm fine opening a separate PR which re-applies the reverted commits together with the fixes

**Comment by ldir-EDB0** [comment]
@guidosarducci   Hi Tony.  If you want someone to blame for the revert then blame me.  We can't have builds not working/not installing binaries and after trying a simplistic 'remove the conditionals' which fell into the libelf dependency trap (as you predicted) I in essence panicked/agreed with Hans that reverting was a reasonable step.  If nothing else it further exposes my ignorance of the build process.

I agree that a separate PR with the 4 reverted commits and the fix commit would be a fair way forward.

**Comment by ldir-EDB0** [comment]
@guidosarducci  I don't get why iproute-full now depends on libelf?  And this (& related) PRs have gone on so long I've lost the plot (both of the PR and mentally :-)

I thought the aim was to get 'tc' as the only consumer of libelf

**Comment by guidosarducci** [comment]
@ldir-EDB0 @dedeckeh It's not really a question of blame so much as wanting to avoid unnecessary churn in the git history. But any fault is my own, for trying to fix a variant/build problem it seems few have noticed, and overlooking a "last mile" check that's much simpler than all the prior, hairy test/debug with ip/tc, kernel modules, gcc, dynamic loading, symbols, bpf, etc. So don't go blaming yourselves... and thanks for catching this! :slightly_smiling_face: 
>I'm fine opening a separate PR which re-applies the reverted commits together with the fixes

OK, I opened a new PR, #1844.

> I don't get why iproute-full now depends on libelf? And this (& related) PRs have gone on so long I've lost the plot (both of the PR and mentally :-)
>
>I thought the aim was to get 'tc' as the only consumer of libelf

Because ip-full needs eBPF support for loading XDP/BPF objects, as @tohojo also remarked in one of the threads I think. The ip-tiny package still omits this as expected. A loading test case, for example:
```
root@OpenWrt:~# ip link set dev lo xdp object bpf_test_eb.o section classifier verbose

Prog section 'classifier' loaded (5)!
 - Type:         6
 - Instructions: 3 (0 over limit)
 - License:      GPL

Verifier analysis:

0: (18) r0 = 0xffffffff
2: (95) exit
processed 2 insns, stack depth 0

root@OpenWrt:~# ip link show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 xdpgeneric qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    prog/xdp id 3 tag 59904229c5a1f55d

```

**Pull request closed without merging**
