### PR TITLE
mwlwifi: update to version 10.3.9.1-20230429

### PR DESCRIPTION
**Pull request by anomeome**
resolve disconnect issue, upstream PR412

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Review by gnaux — APPROVED** [review]

**Review by pesa1234 — APPROVED** [review]

**Comment by tamer-hassan** [comment]
Tested on WRT3200ACM

Compared to the old mwlwifi (without @jbsky patches), the performance is noticeably worse, regardless of whether AMSDU on or off.

i.e. now getting at best 390-400Mbps with iperf3, despite being connected at 1300Mbps (Macbook pro 2019)

Previously, was getting consistent 570-600Mbps (also while connected at 1300Mbps from Macbook pro 2019).

sad :frowning:

**Comment by neveripe** [comment]
@tamer-hassan, This update is just fix of wifi instability, right now after update to 10.3.9.0 there are random client disconnects. This 10.3.9.1 contains just 1-liner fix to address this issue.

**Comment by tamer-hassan** [comment]
@neveripe Understandable. Just wanted to highlight that the wifi disconnects was not the only side-effect of 10.3.9.0. I am referring to the whole lot of @jbsky's patches up till this one.

**Comment by tamer-hassan** [comment]
Sorry, it seems after I upgraded I forgot to include in my `config globals`:
`option packet_steering '1'`

hence why my throughput results were skewed.

**Review by xophr — APPROVED** [review]

**Comment by zaventh** [comment]
This fixes a significant issue currently in master with `mwlwifi`. I had to revert ab3f151aa874837ae1ac56d5b1cc31bb6cd68681 entirely, however, in order to resolve further regressions that are harder to reproduce.

**Comment by tamer-hassan** [comment]
I conducted my tests again

```
root@WRT3200ACM:~# cat /sys/kernel/debug/ieee80211/phy0/mwlwifi/tx_amsdu
tx amsdu: enable
```

```
root@WRT3200ACM:~# grep -A2 globals /etc/config/network
config globals 'globals'
	option ula_prefix 'fdff:c666:414c::/48'
	option packet_steering '1'
```

The best throughput I now get:
```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-30.00  sec  2.54 GBytes   728 Mbits/sec                  sender
[  5]   0.00-30.01  sec  2.54 GBytes   728 Mbits/sec                  receiver
```
The worst throughput:
```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-30.00  sec  2.33 GBytes   667 Mbits/sec                  sender
[  5]   0.00-30.02  sec  2.33 GBytes   666 Mbits/sec                  receiver
```

With old mlwifi (20200206-3)
--- 192.168.100.1 ping statistics ---
38 packets transmitted, 38 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 2.564/7.462/11.055/2.903 ms

With mlwifi 10.3.9.1-20230429
--- 192.168.100.1 ping statistics ---
38 packets transmitted, 38 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 2.310/4.677/10.057/3.014 ms


As you can see, with comparable configuration (both packet_steering enabled), and AMSDU enabled with latest mlwifi (vs AMSDU disabled in old mlwifi), I get **a bit less throughput** (666Mbps-728Mbps) vs old mlwifi (consistently 741Mbps), but I do get **better latency**.

**Comment by panchomira** [comment]
Hello guys. 

I'm very limited in knowledge but I'm more than willing to help. This updates to the drivers are particularly of my interest due to owning a wrt1900ac. 

Thanks for the work that you are putting into it!

**Comment by neveripe** [comment]
After testing 10.3.9.1 for few days - I can confirm that it apparently fixes the disconnect issue introduced in 10.3.9.0.
Haven't had any disconnects for at least 48+ hours now, while previously disconnects happened within anything from 1 to 8 hours.

WRT32X, SNAPSHOT r22847

**Comment by mmortal03** [comment]
@dgilman , the guy from the other thread, @brada4 might have some idea, but isn't subscribed to this pull request.

**Comment by brada4** [comment]
Im no wiser, if you add `2>/dev/null` to the script it masks other more genuine failures.
ENOENT returned from file access does not seem to be returned from driver in sysfs?

**Comment by tamer-hassan** [comment]
> @tamer-hassan , are you sure packet steering was enabled? I am currently seeing #12095 on 23.05.0-rc1 on a WRT3200ACM which prevents me from enabling packet steering. The other thread suggests it is a driver bug that prevents packet steering from being actually enabled. If it's broken you'll see
> 
> ```
> Wed Jun 14 12:48:00 2023 daemon.notice procd: /etc/rc.d/S25packet_steering: sh: write error: No such file or directory
> Wed Jun 14 12:48:00 2023 daemon.notice procd: /etc/rc.d/S25packet_steering: sh: write error: No such file or directory
> ```
> 
> in the syslog. But your comment was also left on May 2nd, so maybe this packet steering issue was a regression between then and now?

Yes, I'm sure.. Till today I'm still running the same snapshot, which was from Divested-WRT, before he removed the patches of this PR for his personal reasons of not being happy with it on WRT1900AC.

Here's proof:

```
root@WRT3200ACM:~# cat /etc/openwrt_release
DISTRIB_ID='Divested-WRT'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r22702+10-cf8d861978'
DISTRIB_TARGET='mvebu/cortexa9'
DISTRIB_ARCH='arm_cortex-a9_vfpv3-d16'
DISTRIB_DESCRIPTION='Divested-WRT SNAPSHOT r22702+10-cf8d861978'
DISTRIB_TAINTS='no-all'
root@WRT3200ACM:~# cat /etc/openwrt_version
r22702+10-cf8d861978
root@WRT3200ACM:~# find /sys/class/net/*/queues/[rt]x-[01234567]/[rx]ps_cpus -exec sh -c 'echo {} && cat {}' \;
/sys/class/net/br-lan/queues/rx-0/rps_cpus
0
/sys/class/net/br-lan/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/eth0/queues/rx-0/rps_cpus
3
/sys/class/net/eth0/queues/rx-1/rps_cpus
3
/sys/class/net/eth0/queues/rx-2/rps_cpus
3
/sys/class/net/eth0/queues/rx-3/rps_cpus
3
/sys/class/net/eth0/queues/rx-4/rps_cpus
3
/sys/class/net/eth0/queues/rx-5/rps_cpus
3
/sys/class/net/eth0/queues/rx-6/rps_cpus
3
/sys/class/net/eth0/queues/rx-7/rps_cpus
3
/sys/class/net/eth0/queues/tx-0/xps_cpus
3
/sys/class/net/eth0/queues/tx-1/xps_cpus
3
/sys/class/net/eth0/queues/tx-2/xps_cpus
3
/sys/class/net/eth0/queues/tx-3/xps_cpus
3
/sys/class/net/eth0/queues/tx-4/xps_cpus
3
/sys/class/net/eth0/queues/tx-5/xps_cpus
3
/sys/class/net/eth0/queues/tx-6/xps_cpus
3
/sys/class/net/eth0/queues/tx-7/xps_cpus
3
/sys/class/net/lan1/queues/rx-0/rps_cpus
0
/sys/class/net/lan1/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/lan2/queues/rx-0/rps_cpus
0
/sys/class/net/lan2/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/lan3/queues/rx-0/rps_cpus
0
/sys/class/net/lan3/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/lan4/queues/rx-0/rps_cpus
0
/sys/class/net/lan4/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/lo/queues/rx-0/rps_cpus
0
/sys/class/net/lo/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/phy0-ap0/queues/rx-0/rps_cpus
3
/sys/class/net/phy0-ap0/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/phy1-ap0/queues/rx-0/rps_cpus
3
/sys/class/net/phy1-ap0/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/pppoe-wan/queues/rx-0/rps_cpus
0
/sys/class/net/pppoe-wan/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/wan.30/queues/rx-0/rps_cpus
0
/sys/class/net/wan.30/queues/tx-0/xps_cpus
cat: read error: No such file or directory
/sys/class/net/wan/queues/rx-0/rps_cpus
0
/sys/class/net/wan/queues/tx-0/xps_cpus
cat: read error: No such file or directory
root@WRT3200ACM:~#
```

**Comment by tamer-hassan** [comment]
@dgilman I rebooted the router just to check system log from the beginning, and to see if I get the same two lines of errors in the log, and I did actually see them:

```
Sun May 14 10:14:47 2023 daemon.notice procd: /etc/rc.d/S25packet_steering: sh: write error: No such file or directory
Sun May 14 10:14:47 2023 daemon.notice procd: /etc/rc.d/S25packet_steering: sh: write error: No such file or directory
```

but does that actually mean that packet steering is not enabled for any interfaces? see my 1 line script/command and output in my previous comment above that proves otherwise, I believe.

**Comment by brada4** [comment]
@tamer-hassan what happens if you `touch /sys/class/net/*/queues/?x-*/?ps_cpus`
If it errors it may serve as guard against unpredictable operation.

**Comment by danpawlik** [comment]
Also got such error in the system logs, but it seems that the packet_sterring is enabled via uci:
```
root@Mi4A-Giga:~# uci show| grep steering
network.globals.packet_steering='1'
```

So I tried to disable that:
```
root@Mi4A-Giga:~# uci set network.globals.packet_steering=0
root@Mi4A-Giga:~# uci commit
root@Mi4A-Giga:~# uci show| grep steering
network.globals.packet_steering='0'
root@Mi4A-Giga:~# reboot
```

And it seems, that there is nothing related to `S25packet_steering` in the logs.

**Comment by brada4** [comment]
Log entries represent bug in script yielding noise when only one queue of type for device rejects CPU mask. It is no damage done, all other traffic directions and devices are set up correctly (and the noisy one not changed at all)

**Pull request merged**
