### PR TITLE
[RFC] bcm63xx: drop target

### PR DESCRIPTION
**Pull request by Noltari**
bcm63xx maintainance is a PITA since there's no full Device Tree support and therefore every board needs it's own definition in board_bcm963xx.c.
There's no DSA support for this target and there have been very few contributions in the last years.
Moreover, BCM63xx SoCs >= BCM6358 are already supported in bmips target, so any efforts to keep this target alive aren't worth the time.
Let's focus the community efforts on improving bmips instead.

CC @ffainelli @KanjiMonster @danitool

### CODE REVIEW

**Review by ynezz — APPROVED** [review]
>  Let's focus the community efforts on improving bmips instead.

Sounds like a good plan, thus this proposal makes sense to me, thanks!

**Comment by ynezz** [comment]
BTW feel free to move it over to https://github.com/openwrt/targets

**Review by robimarko — APPROVED** [review]
LGTM, especially since there is a target that replaces it

**Comment by rikka0w0** [comment]
> Let's focus the community efforts on improving bmips instead.

I'm adding support for a BCM63168 OEM router and i found that the "gpio-leds" does not work BMIPS target. It worked on the old BCM63xx target. I removed the "gpio-leds" in the DTS and compiled it against the latest BMIPS codes, then tried to control the LEDs via `/sys/class/gpio`, it doesn't work, except for GPIO8. (I tried to toggle all 52 GPIOs)

In [my DTS](https://github.com/rikka0w0/openwrt-fast3864op/blob/8fccbd7eef91501fb20620544fa3d01ee306df51/target/linux/bmips/dts/bcm63168-sagem-fast-3864-op.dts), LEDs driven by the 74HC161 shift-register and GPIO LEDs (<24) are controlled by the hardware LED controller and working as expected. However, my router has LEDs that are attached to GPIOs >32, and "gpio-leds" is the only option, as the LED controller hardware only supports up to 24 LEDs. 

In my BMIPS image, command `ls /sys/class/gpio` gives: `export       gpiochip460  unexport` and `cat /sys/class/gpio/gpiochip460/ngpio` gives `52`. But I remembered back in the BCM63xx target, there were two gpiochip instances.

[This wiki page](https://openwrt.org/docs/techref/hardware/soc/soc.broadcom.bcm63xx#gpios) said that:
```
When having more than 32 GPIOs they are splitted between 2 gpiochips. The labels in the Linux kernel are:

bcm63xx-gpio.0
bcm63xx-gpio.1
```

So I think there might be some problem with the GPIO controller driver on the BMIPS target?

#14664

**Comment by Noltari** [comment]
> > Let's focus the community efforts on improving bmips instead.
> 
> I'm adding support for a BCM63168 OEM router and i found that the "gpio-leds" does not work BMIPS target. It worked on the old BCM63xx target. I removed the "gpio-leds" in the DTS and compiled it against the latest BMIPS codes, then tried to control the LEDs via `/sys/class/gpio`, it doesn't work, except for GPIO8. (I tried to toggle all 52 GPIOs)
> 
> In [my DTS](https://github.com/rikka0w0/openwrt-fast3864op/blob/8fccbd7eef91501fb20620544fa3d01ee306df51/target/linux/bmips/dts/bcm63168-sagem-fast-3864-op.dts), LEDs driven by the 74HC161 shift-register and GPIO LEDs (<24) are controlled by the hardware LED controller and working as expected. However, my router has LEDs that are attached to GPIOs >32, and "gpio-leds" is the only option, as the LED controller hardware only supports up to 24 LEDs.
> 
> In my BMIPS image, command `ls /sys/class/gpio` gives: `export gpiochip460 unexport` and `cat /sys/class/gpio/gpiochip460/ngpio` gives `52`. But I remembered back in the BCM63xx target, there were two gpiochip instances.
> 
> [This wiki page](https://openwrt.org/docs/techref/hardware/soc/soc.broadcom.bcm63xx#gpios) said that:
> 
> ```
> When having more than 32 GPIOs they are splitted between 2 gpiochips. The labels in the Linux kernel are:
> 
> bcm63xx-gpio.0
> bcm63xx-gpio.1
> ```
> 
> So I think there might be some problem with the GPIO controller driver on the BMIPS target?
> 
> #14664

@rikka0w0 as @ynezz [already stated](https://github.com/openwrt/openwrt/issues/14664#issuecomment-1950968251), please open a new PR as draft and I/others will try to help you there.
Posting this here is offtopic.

**Comment by Noltari** [comment]
> BTW feel free to move it over to https://github.com/openwrt/targets

Done, https://github.com/openwrt/targets/commit/a1497c456220a26c4103d98f6701f7507b187f40

**Comment by Foufa25** [comment]
bcm63xx target was removed from snapshot and bmips target is used for that platform now, but HG556a A was not migrated to bmips target. (HG556a B was migrated to bmips)
Can you restore it please

**Pull request merged**
