### PR TITLE
Libtool bump to 2.4.6 (plus fix for SDK issue)

### PR DESCRIPTION
**Pull request by micmac1**
Hi all,

This cherry-picks @cotequeiroz  libtool bump and then updates one patch to fix the issue seen when the build bots tried to build the packages (the reason why @hauke reverted the commit).

I don't know why "$STAGING_DIR/../host" is used within the patch instead of "$STAGING_DIR_HOST", but I kept with this theme and did it likewise, because there may of course be a good reason.

Kind regards,
Seb

### CODE REVIEW

**Comment by neheb** [comment]
From IRC:

```
12:11:08mangixOne way to work around these failures is to remove autoreconf.
12:28:59jowor to stop needlessly updating that autotools
12:30:57jowthe bump commit cites no reason why libtool was updated
12:31:07jowother than that the one we use is from 2015
12:34:33jowand wouldn't disabling autoreconf effectively revert packages to wahtever ancient upstream libtool they ship with? rendering the libtool update mostly moot in the first place?
```

**Comment by neheb** [comment]
2.4.7 is out.

**Comment by micmac1** [comment]
Honestly, I completely forgot about this :-)

**Comment by neheb** [comment]
https://github.com/neheb/openwrt/commit/30d5311f8364ba01ac85c4b5dbf5f8a73d91be47

**Comment by hauke** [comment]
@jow-  Can you please take care of this.

**Comment by neheb** [comment]
@micmac1 please include https://github.com/neheb/openwrt/commit/30d5311f8364ba01ac85c4b5dbf5f8a73d91be47

**Comment by micmac1** [comment]
> @micmac1 please include [neheb@30d5311](https://github.com/neheb/openwrt/commit/30d5311f8364ba01ac85c4b5dbf5f8a73d91be47)

Hi Rosen,

I tried, but I can't. I added your openwrt fork to my remotes and fetched it. But I can't find the commit https://github.com/neheb/openwrt/commit/30d5311f8364ba01ac85c4b5dbf5f8a73d91be47. Currently no idea why.

Kind regards,
Seb

**Comment by neheb** [comment]
Just do

```
curl https://github.com/neheb/openwrt/commit/30d5311f8364ba01ac85c4b5dbf5f8a73d91be47.patch | git am
```

**Comment by neheb** [comment]
ping @Ansuel this is ready

**Comment by micmac1** [comment]
Rebased and added the requested commit. Thanks for the command line help Rosen!

**Comment by mpratt14** [comment]
2.42 to 2.46 are bugfix releases, and 2.47 has new features (version numbering not helping haha....)

Looking at the changelog, I think some housekeeping should be done

 - look in openwrt for presense of `AR_FLAGS` and change to `ARFLAGS` if possible
 - add to `rules.mk` `export FILECMD:=$(STAGING_DIR_HOST)/bin/file`

**Comment by neheb** [comment]
This may have issues.

Compiling tools/libressl I get this: https://github.com/openwrt/openwrt/commit/5451b03b7ceb2315445c683fe174e28bbdd49c2f#commitcomment-79014662

Looking at my branch, this is the only thing that could cause it. origin/master builds fine.

**Comment by neheb** [comment]
2.4.7 is out.

**Comment by mpratt14** [comment]
and this should keep track of #11214

if that gets accepted then this would have to be adjusted similarly

**Comment by neheb** [comment]
That was merged. ping @micmac1

**Comment by micmac1** [comment]
> That was merged. ping @micmac1

Eneas' original commit "libtool: bump to 2.4.6" now does not apply
cleanly anymore. I don't have the time to look into this.

Kind regards,
Seb

**Comment by mpratt14** [comment]
@micmac1 it is not a lot you have to change, just the first patch for libtool called "relocatable"

every
`STAGING_DIR/../host`
to
`STAGING_DIR_HOST`

and every
`STAGING_DIR`
to
`STAGING_DIR_HOST`

**Comment by lovehackintosh** [comment]
@micmac1 I rebased and resolved the conflicts, you just need to cherry-pick these commits https://github.com/lovehackintosh/openwrt/tree/libtool-bump

**Comment by mpratt14** [comment]
I'm planning to squash this together and add into my other PR for the rest of the autotools

**Comment by hauke** [comment]
Similar patches were applied in #10394. See commit c7828a7184d704dafcdfd89b1f59ac2a70090637, efe56a51bcd0b2c2db39c682e88fb166a2431727, a22c54e39f8cb668ea5d717a51359fe2409fa336, 0d0cfe9f2d086404093b547b89afec822c32bd76 and bf261073dc4d788170d51fdc718d63ce0976fd77.

**Pull request closed without merging**
