### PR TITLE
ar71xx: add support for Zsun WiFi SD Card Reader

### PR DESCRIPTION
**Pull request by gdm85**
Re-submitting #312 .

Support for ZSUN WiFi SD Card Reader; there was previously a problem with the image size, see #312 for all the previous comments.

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @gdm85,

Please, read our [submitting patches rules](https://lede-project.org/submitting-patches), and make sure your patch or pull request follows them.

Cheers,
Piotr

**Comment by gdm85** [comment]
@pepe2k what rules are you referring to?

The builder is not providing useful logs for the failure either:
```
make -r world: build failed. Please re-run make with -j1 V=s to see what's going on
```

**Comment by pepe2k** [comment]
@gdm85,

> @pepe2k what broken rules are you specifically referring to?

Please, read them all, carefully.
Your commits are missing, among others, SoB lines, proper prefixes and descriptions.

Also, we no longer accept support for devices with legacy build code, please use generic.

> The builder is not providing useful logs for the failure either:

Did you build your changes locally?

Cheers,
Piotr

**Comment by danielg4** [comment]
It looks like the commits were intended only as local changes, because they seem to hard-code building specifically for this device. This support needs to be redone in a way that can be merged, which will need serial access to test, but should be trivial otherwise.

**Comment by radiolee** [comment]
Hard to accept, openwrt  do not support the ZSun WiFi card reader officially till now...

**Comment by gdm85** [comment]
@danielg4 it is an improvement over the original patches I found, which were actually embedding `.patch` files to be patched just before building...

I do not intend to continue with this PR, hence I am closing this.

**Comment by josteink** [comment]
@gdm85: while I can understand that you won’t spend more time on this, I hope you will keep your repo around for others to use.

**Comment by pidiet** [comment]
sad to see this one closed

**Comment by pbriesch** [comment]
I was hoping  for a long time to see openwrt support and eventually for gluon so that I could use my tiny routers for Freifunk.

Please don‘t give up @gdm85 and many thanks for your efforts!

**Comment by gdm85** [comment]
Guys, this is not how open source works. @pbriesch you can continue the work on it from where I left, and @josteink you can click the "Fork" button to keep a copy of the repo around.

**Comment by ShapeShifter499** [comment]
> It looks like the commits were intended only as local changes, because they seem to hard-code building specifically for this device. This support needs to be redone in a way that can be merged, which will need serial access to test, but should be trivial otherwise.

@danielg4 I'm tempted to pickup an attempt at this. But I have never ever tried to port OpenWrt or any such similar router software to a device before.  I own two Zsun Wifi SD Card readers.   What do you mean exactly when you say serial access is needed?   Do I need to grab the boot logs as they happen to show it working?

**Comment by ShapeShifter499** [comment]
I just noticed this https://forum.openwrt.org/t/supporting-zsun-wifi-card-reader-16mb-flash-64mb-ram-ar9331/2142/372

and this https://github.com/brunompena/zsun-resources/releases/tag/19.07.3

I don't know if this message will make it to you but @brunompena are you ever planning to try to submit a PR so support can be made official somehow?

**Comment by brunompena** [comment]
> I just noticed this https://forum.openwrt.org/t/supporting-zsun-wifi-card-reader-16mb-flash-64mb-ram-ar9331/2142/372
> 
> and this https://github.com/brunompena/zsun-resources/releases/tag/19.07.3
> 
> I don't know if this message will make it to you but @brunompena are you ever planning to try to submit a PR so support can be made official somehow?

This was attempted in several PR:

- OpenWrt support for Zsun-SD100 device : Main Firmware
1. [OpenWrt: add support for Zsun-SD100 on ar71xx](https://github.com/openwrt/openwrt/pull/2568)
2. [OpenWrt: add support for Zsun-SD100 on ath79](https://github.com/openwrt/openwrt/pull/2569)
3. [OpenWrt: base-files: add support for WiFi only devices](https://github.com/openwrt/openwrt/pull/2571)

- OpenWrt support for read-only partitions : Recovery Firmware
1. [Kernel: make mtd sub-partitions inherit parent's access mode](https://github.com/openwrt/openwrt/pull/2535)
 re-submitted as: [kernel: mtd: enforce sub-partitions access mode](https://github.com/openwrt/openwrt/pull/2709)
2. [fstools: add support to read-only MTD partitions (eg. for recovery images)](http://lists.infradead.org/pipermail/openwrt-devel/2019-November/025579.html)
 re-submitted as: [fstools: add support to read-only MTD partitions (eg. for recovery images)](http://lists.infradead.org/pipermail/openwrt-devel/2020-January/026772.html)

- u-boot_mod support for Zsun-SD100 : U-Boot
1. [u-boot_mod: add support for Zsun-SD100](https://github.com/pepe2k/u-boot_mod/pull/236)

However the idea of support this device with the proposed changes was not well received as you can read through the comments of the PR - I have since closed the PR since they were not going anywhere.

**Pull request closed without merging**
