### PR TITLE
mediatek: filogic: disable swconfig

### PR DESCRIPTION
**Pull request by abajk**
This subtarget supports 3 devices:
 * Bananapi BPi-R3 (added in a96382c1bb204698cd43e82193877c10e4b63027),
 * MediaTek MTK7986 rfba AP (added in cffc77ae55ed0e5b9e70417d6a1e1d280cea92cf),
 * MediaTek MTK7986 rfbb AP (added in cffc77ae55ed0e5b9e70417d6a1e1d280cea92cf).

This subtarget supports DSA from the beginning. It looks like CONFIG_SWCONFIG was copied from another config when the subtarget was created.

Signed-off-by: Aleksander Jan Bajkowski <olek2@wp.pl>

### CODE REVIEW

**Comment by DragonBluep** [comment]
Just some information:
Some filogic devices use RTL8367S switch, which do not seem to support DSA? I am not sure.
Although these devices may never be supported by openwrt.
https://www.acwifi.net/18464.html

**Comment by Gingernut1978** [comment]
@DragonBluep It's not based on the Filogic platform but the Totolink A8000RU (mt7622) also has a Realtek RTL8367S switch and is supported by OpenWRT.

**Comment by abajk** [comment]
> Some filogic devices use RTL8367S switch, which do not seem to support DSA? I am not sure.

There is a DSA driver for RTL8367S (https://github.com/torvalds/linux/commit/d40f607c181f5f6282fe6c10eb2c0544f551cf7d).

**Review by dangowrt — APPROVED** [review]

**Comment by dangowrt** [comment]
Picked. 985d59cdf0fe69530dea8ed5bb1ba2119b4586ac

**Pull request closed without merging**
