### PR TITLE
grub2: update to 2.06~rc1

### PR DESCRIPTION
**Pull request by plntyk**
- release of 2.06 soon (April 2021)
- over 100 security patches
(Multiple GRUB2 vulnerabilities - 2021/03/02 round)
see https://lists.gnu.org/archive/html/grub-devel/2021-03/msg00007.html

- fix build issue on some hosts: error: Decompressor is too big

Compiled on: x86 VM, x86_64 VM
Tested on: x86 VM, x86_64 VM

Signed-off-by: Dirk Neukirchen <plntyk.lede@plntyk.name>

### CODE REVIEW

**Comment by plntyk** [comment]
current distros have over 100 grub2 patches for their 2.04 based releases and 2.06 might be released soon since rc is already released

Fedora ~190: https://src.fedoraproject.org/rpms/grub2/tree/rawhide
buildroot ~150: https://git.buildroot.net/buildroot/tree/boot/grub2

**Comment by adschm** [comment]
Why is this marked as 21.02 when it's based against master? Note that we only accept changes through master.

**Comment by plntyk** [comment]
sorry - i was tagging it that way because a backport should be done if its accepted - as there are a ton of security fixes with CVE numbers

**Comment by stintel** [comment]
I've came to the same solution today to fix https://bugs.openwrt.org/index.php?do=details&task_id=3790
Is it OK for you that I use my work and attribute you with Suggested-by as in https://git.openwrt.org/?p=openwrt/staging/stintel.git;a=commit;h=3bc522aab6734451ec8ccd6b63533e038acdd8f1 ?

**Comment by stintel** [comment]
e74d81ece2e2932a4f370d8e6d180061a6a2c229

**Pull request closed without merging**
