### PR TITLE
zynq: add testing support for 6.1

### PR DESCRIPTION
**Pull request by PolynomialDivision**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
@luaraneda Can you runtest?

**Comment by luaraneda** [comment]
> @luaraneda Can you runtest?

Sure, I think over the weekend I can test it.

Do you plan to also do kernel 6.6?
I was planning to do it of these weekends.

**Comment by PolynomialDivision** [comment]
> > @luaraneda Can you runtest?
> 
> Sure, I think over the weekend I can test it.
> 
> Do you plan to also do kernel 6.6? I was planning to do it of these weekends.

I would also do 6.6. But if you want to do it, I am also happy with it. :)

**Comment by PolynomialDivision** [comment]
If you test it, can you directly give me your "Tested-by: ..."?

**Comment by PolynomialDivision** [comment]
ping @luaraneda

**Comment by luaraneda** [comment]
Sorry for the delay on testing.
Run tested on Zybo Z7-20.

Feel free to add:
`Tested-by: Luis Araneda <luaraneda@gmail.com> # Zybo Z7-20`

**Pull request merged**
