### PR TITLE
gdb: Update to version 15.2 

### PR DESCRIPTION
**Pull request by hauke**
* toolchain: gdb: Update to version 15.2
    
    See news file for changes:
    https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gdb/NEWS;hb=gdb-15.1-release
    
    This requires a C++17 compiler compatible compiler like GCC 9 and
    later.
    
 * gdb: Remove MIPS NSIG patch
    
    This bug was fixed in the libc:
    https://sourceware.org/bugzilla/show_bug.cgi?id=14523
    https://git.busybox.net/uClibc/commit/?id=2da958760f798224065508431787e3a83b7fe2ae
    https://git.musl-libc.org/cgit/musl/commit/?id=7c440977db9444d7e6b1c3dcb1fdf4ee49ca4158
    
 * gdb: Remove upstreamed SIGINT patch
    
    The problem was fixed upstream, see:
    https://sourceware.org/bugzilla/show_bug.cgi?id=18945
    https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=4c35c4c6a779c79e456b7a5311f74aafc9026bd5
  
 * gdb: Update to version 15.2
    
    See news file for changes:
    https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gdb/NEWS;hb=gdb-15.1-release
 
I tested this on mips 32 be malta doing remote debugging.

### CODE REVIEW

**Comment by neheb** [comment]
@robimarko will this finally kill Ubuntu 18.04 support ;)

**Comment by robimarko** [comment]
If it requires G++-9 then yeah, though 18.04 should have been dead over a year ago.

That would mean that we need to raise the prereq check for GCC-8 to GCC-9 as well

**Comment by hauke** [comment]
The gdb NEWS file says this:
> * Building GDB and GDBserver now requires a C++17 compiler.
>   For example, GCC 9 or later.

If it still compiles under Ubuntu 18.04, we should keep the minimum gcc version at GCC 8, but I would not invest efforts to keep it working.

**Comment by robimarko** [comment]
Trust me, I dont want to invest anything to keep 18.04 running, its time has passed but I just tried compiling with GCC-8(The officially provided one) in 18.04 and GDB compiled.

GCC-8 has C++17 support though only partial, but seems enough.

**Comment by neheb** [comment]
I tested this PR on 18.04. gdb still compiles. Not quite yet ;)

**Pull request merged**
