### PR TITLE
wolfssl: update to 4.8.1-stable

### PR DESCRIPTION
**Pull request by AuthorReflex**
Changes from 4.7.0:
  Fix one high (OCSP verification issue) and two low vulnerabilities
  Improve compatibility layer
  Other improvements and fixes

For detailed changes refer to https://github.com/wolfSSL/wolfssl/releases

For compilation, libtool 2.4.2+ requred (see https://github.com/openwrt/openwrt/pull/4521)

Compile && runtime tested ath79/generic, ramips/mt7620, ramips/mt7621

Signed-off-by: Ivan Pavlov <AuthorReflex@gmail.com>

### CODE REVIEW

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master.

**Comment by rmandrad** [comment]
Hi,

the wolfssl 4.8.1 compile is failing with "libwolfssl.so: undefined reference to `wc_Sha256Transform'" ... 

FAILED: ustream-example-client
: && /home/rmandrad/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc -O2 -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/rmandrad/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/ustream-ssl-wolfssl/ustream-ssl-2020-12-10-68d09243=ustream-ssl-2020-12-10-68d09243 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/rmandrad/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr/include/wolfssl -DNDEBUG -L/home/rmandrad/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/usr/lib -L/home/rmandrad/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/lib -znow -zrelro CMakeFiles/ustream-example-client.dir/ustream-example-client.c.o -o ustream-example-client  libustream-ssl.so  -lubox  -lwolfssl  -lm && :
/home/rmandrad/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/11.2.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: /home/rmandrad/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr/lib/libwolfssl.so: undefined reference to `wc_Sha256Transform'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:73: /home/rmandrad/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/ustream-ssl-wolfssl/ustream-ssl-2020-12-10-68d09243/.built] Error 1

**Comment by AuthorReflex** [comment]
> Hi,
> 
> the wolfssl 4.8.1 compile is failing with "libwolfssl.so: undefined reference to `wc_Sha256Transform'" ...
> 
> FAILED: ustream-example-client
> : && /home/rmandrad/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc -O2 -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/rmandrad/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/ustream-ssl-wolfssl/ustream-ssl-2020-12-10-68d09243=ustream-ssl-2020-12-10-68d09243 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/rmandrad/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr/include/wolfssl -DNDEBUG -L/home/rmandrad/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/usr/lib -L/home/rmandrad/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/lib -znow -zrelro CMakeFiles/ustream-example-client.dir/ustream-example-client.c.o -o ustream-example-client libustream-ssl.so -lubox -lwolfssl -lm && :
> /home/rmandrad/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-11.2.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/11.2.0/../../../../arm-openwrt-linux-muslgnueabi/bin/ld: /home/rmandrad/openwrt/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr/lib/libwolfssl.so: undefined reference to `wc_Sha256Transform'
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.
> make[3]: *** [Makefile:73: /home/rmandrad/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/ustream-ssl-wolfssl/ustream-ssl-2020-12-10-68d09243/.built] Error 1

can you provide config file for build?

**Comment by csrutil** [comment]
```
./scripts/diffconfig.sh
CONFIG_TARGET_rockchip=y
CONFIG_TARGET_rockchip_armv8=y
CONFIG_TARGET_MULTI_PROFILE=y
CONFIG_TARGET_DEVICE_rockchip_armv8_DEVICE_friendlyarm_nanopi-r2s=y
CONFIG_TARGET_DEVICE_PACKAGES_rockchip_armv8_DEVICE_friendlyarm_nanopi-r2s=""
CONFIG_TARGET_DEVICE_rockchip_armv8_DEVICE_friendlyarm_nanopi-r4s=y
CONFIG_TARGET_DEVICE_PACKAGES_rockchip_armv8_DEVICE_friendlyarm_nanopi-r4s=""
CONFIG_TARGET_DEVICE_rockchip_armv8_DEVICE_pine64_rockpro64=y
CONFIG_TARGET_DEVICE_PACKAGES_rockchip_armv8_DEVICE_pine64_rockpro64=""
CONFIG_TARGET_DEVICE_rockchip_armv8_DEVICE_radxa_rock-pi-4a=y
CONFIG_TARGET_DEVICE_PACKAGES_rockchip_armv8_DEVICE_radxa_rock-pi-4a=""
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
CONFIG_DEVEL=y
CONFIG_TARGET_PER_DEVICE_ROOTFS=y
CONFIG_AUTOREMOVE=y
CONFIG_BUILDBOT=y
CONFIG_COLLECT_KERNEL_DEBUG=y
# CONFIG_FEED_luci is not set
# CONFIG_FEED_packages is not set
# CONFIG_FEED_routing is not set
# CONFIG_FEED_telephony is not set
CONFIG_IB=y
CONFIG_IMAGEOPT=y
CONFIG_KERNEL_BUILD_DOMAIN="buildhost"
CONFIG_KERNEL_BUILD_USER="builder"
# CONFIG_KERNEL_KALLSYMS is not set
CONFIG_MAKE_TOOLCHAIN=y
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_ENGINE_BUILTIN=y
CONFIG_OPENSSL_ENGINE_BUILTIN_DEVCRYPTO=y
CONFIG_OPENSSL_NO_DEPRECATED=y
CONFIG_OPENSSL_OPTIMIZE_SPEED=y
CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_PACKAGE_kmod-crypto-aead=y
CONFIG_PACKAGE_kmod-crypto-authenc=y
CONFIG_PACKAGE_kmod-crypto-hash=y
CONFIG_PACKAGE_kmod-crypto-manager=y
CONFIG_PACKAGE_kmod-crypto-null=y
CONFIG_PACKAGE_kmod-cryptodev=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_openssl-util=y
CONFIG_REPRODUCIBLE_DEBUG_INFO=y
CONFIG_SDK=y
CONFIG_TARGET_ALL_PROFILES=y
CONFIG_VERSIONOPT=y
CONFIG_VERSION_BUG_URL=""
CONFIG_VERSION_CODE=""
CONFIG_VERSION_CODE_FILENAMES=y
CONFIG_VERSION_DIST="OpenWrt"
CONFIG_VERSION_FILENAMES=y
CONFIG_VERSION_HOME_URL=""
CONFIG_VERSION_HWREV=""
CONFIG_VERSION_MANUFACTURER=""
CONFIG_VERSION_MANUFACTURER_URL=""
CONFIG_VERSION_NUMBER=""
CONFIG_VERSION_PRODUCT=""
CONFIG_VERSION_REPO="https://downloads.openwrt.org/snapshots"
CONFIG_VERSION_SUPPORT_URL=""
CONFIG_WOLFSSL_HAS_DEVCRYPTO=y
CONFIG_WOLFSSL_HAS_DEVCRYPTO_FULL=y
CONFIG_WOLFSSL_HAS_ECC25519=y
# CONFIG_WOLFSSL_HAS_NO_HW is not set
# CONFIG_OPENSSL_ENGINE_BUILTIN_AFALG is not set
CONFIG_OPENSSL_NO_DEPRECATED=y
# CONFIG_OPENSSL_WITH_DEPRECATED is not set
# CONFIG_OPENSSL_WITH_ERROR_MESSAGES is not set
CONFIG_PACKAGE_kmod-crypto-user=m
# CONFIG_PACKAGE_libopenssl-afalg_sync is not set
```

**Comment by AuthorReflex** [comment]
https://github.com/openwrt/openwrt/pull/4688

**Pull request closed without merging**
