### PR TITLE
rockchip: switch to Kernel 5.10

### PR DESCRIPTION
**Pull request by aparcar**
CI build with artifacts: https://github.com/aparcar/openwrt/actions/runs/1292210847

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by blocktrron** [comment]
I would drop 5.4 in the process and get rid of this hack here: https://github.com/openwrt/openwrt/blob/ea1767c5fb2dfd5e781447624da900a04146b0fa/target/linux/rockchip/files-5.10/arch/arm64/boot/dts/rockchip/rk3399-rock-pi-4.dts#L10

**Comment by blocktrron** [comment]
You've deleted the DTS, however  this means you need to add the new name to the images & add the old name to the supported-devices list.

**Comment by mj22226** [comment]
This patch has to be deleted to https://github.com/openwrt/openwrt/blob/master/target/linux/rockchip/patches-5.10/105-rockchip-rock-pi-4.patch   
For the image I had done this
```
target/linux/rockchip/image/armv8.mk
@@ -35,8 +35,9 @@
 define Device/radxa_rock-pi-4
   DEVICE_VENDOR := Radxa
   DEVICE_MODEL := ROCK Pi 4
+  DEVICE_DTS := rockchip/rk3399-rock-pi-4a
   SOC := rk3399
-  SUPPORTED_DEVICES := radxa,rockpi4
+  SUPPORTED_DEVICES := radxa,rockpi4a
   UBOOT_DEVICE_NAME := rock-pi-4-rk3399
   IMAGE/sysupgrade.img.gz := boot-common | boot-script | pine64-img | gzip | append-metadata
 endef
```

**Comment by aparcar** [comment]
> You've deleted the DTS, however this means you need to add the new name to the images & add the old name to the supported-devices list.

Let's keep the cleanup specifics out of this, me or someone should add that once the kernel switch happened.

**Comment by adschm** [comment]
I also think we should just switch first. I will prepare the name change in a separate PR.

**Comment by adschm** [comment]
#4629

**Comment by aparcar** [comment]
@adschm are you okay taking over this PR and your rename PR?

**Comment by adschm** [comment]
I'd take care of the merge if @blocktrron gives me a go.

**Comment by adschm** [comment]
Hmm, since testing support is already there for seven months, I think I will just switch this and see what happens.

**Comment by aparcar** [comment]
Thanks @adschm

**Pull request closed without merging**
