### PR TITLE
uboot-mvebu: update to version 2023.07-rc1

### PR DESCRIPTION
**Pull request by damnms**
Since 2021.07 multiple bugs where introduced that made it impossible to create a bootable target for mvebu [1]. This is now fixed in 2023.07-rc1.

[1] https://github.com/openwrt/openwrt/issues/11661

### CODE REVIEW

**Comment by john-tho** [comment]
Close this, and reopen https://github.com/openwrt/openwrt/pull/12547
When you push to your PR branch, the PR will update.
If you need help, ask.

**Comment by damnms** [comment]
i am no git dev, i already killed my branch multiple times. why do i have to kill this now and do it all again.
i can also provide the patch if that helps and someone who is familiar with all those rules here can apply it then

**Comment by john-tho** [comment]
When someone opens, then closes, then opens a new PR for the same topic, all the history is lost from the old PR.
Yes, git can be tricky to work out.
The point of it is not needing to do-it-all-again.
Work out how to use `git rebase -i` and `git commit --amend`, and things get much easier.
If you are making mistakes, create a backup branch first, then rebase there.
I was only trying to help you get your commits to a point where they would be acceptable for OpenWrt.

**Comment by damnms** [comment]
with killed i mean stashing my changes, rebasing to openwrt master, modify and trying to be somehow compliant for openwrt. 
i dont know what you mean, how the structure of the PR should look like
this is the only commit that is really required to get it working, but if its so complicated to have a PR accepted, guess i wait until july

**Pull request closed without merging**
