### PR TITLE
[22.03] ipq40xx: support ZTE MF289F

### PR DESCRIPTION
**Pull request by Leo-PL**
Backport support for ZTE MF289F from master before DSA conversion, including the GPIO fix.
Introduce a swconfig-specific fix for port mapping, which isn't typical for ipq40xx devices, having port 5 as LAN2 and port 2 as LAN1/WAN, keeping the previous WAN personality of this port.

### CODE REVIEW

**Comment by Ansuel** [comment]
cherry pick needs to be done with cherry-pick -x 

also we need a tested by tag for the last commit about port mapping

**Comment by Leo-PL** [comment]
@Ansuel Okay, will add the commit hashes later. I notified folks at eko.one.pl forum to put their tags, I already have some positive reports on the last one.

**Comment by Ansuel** [comment]
(sing the command is better than manually adding stuff as it's more standard)
(for the first commit use [ ] for changes to the patch than ( ) )

**Review by MiG-41 — APPROVED** [review]
Tested-by: Marcin Gajda <mgajda@o2.pl>

**Comment by Ansuel** [comment]
@MiG-41 you need to provide real name and email for tested by

**Comment by MiG-41** [comment]
@Ansuel , i edited my profile , name is Marcin , mail mgajda@o2.pl

**Comment by tango38317** [comment]
Tested by tango38317, OK

**Comment by Ansuel** [comment]
@MiG-41 @tango38317 guys you have to provide a tag like

Tested-by: Robert Marko <robimarko@gmail.com>

**Comment by tango38317** [comment]
Tested-by: Christian Heuff <christian@heuff.at>

**Comment by Leo-PL** [comment]
@Ansuel updated commit messages as requested, also added the Tested-by: tags.

**Comment by SuperKali** [comment]
Tested-by: SuperKali hello@superkali.me

**Review by ynezz — APPROVED** [review]
Thanks, LGTM.

**Comment by Ansuel** [comment]
@SuperKali we can't use nickname for tag... We need real name and surname :(

**Comment by hauke** [comment]
Thank you for the patches, I applied them to openwrt-22.03 branch in 3e15a54bb0ef470e19a36dfbbd97c1bc9b363b99, 71178a85068c9986aece584d58e4c14cd78939c6 and 26b58991b0bfe3b19b39ae8bfb190b569a072e9c.

**Pull request closed without merging**
