### PR TITLE
tools/llvm: update to 18.1.7

### PR DESCRIPTION
**Pull request by rockdrilla**
- release notes:
  - https://discourse.llvm.org/t/llvm-16-0-0-release/69326
  - https://discourse.llvm.org/t/llvm-17-0-1-released/73549
  - https://discourse.llvm.org/t/llvm-18-1-0-released/77448
  - https://discourse.llvm.org/t/llvm-18-1-1-released/77540
  - https://discourse.llvm.org/t/18-1-2-released/77821
  - https://discourse.llvm.org/t/18-1-3-released/78136
  - https://discourse.llvm.org/t/18-1-4-released/78430
  - https://discourse.llvm.org/t/18-1-5-released/78740
  - https://discourse.llvm.org/t/18-1-6-released/79068
  - https://discourse.llvm.org/t/18-1-7-released/79433
- remove PKG_RELEASE (irrelevant to tools)
- set default target/triplet to "bpf"
- rearrange configuration options
- better control feature support and improve build reproducibility:
  disable auxiliary features that are enabled implicitly - their support is detected at build-time

### CODE REVIEW

**Comment by rockdrilla** [comment]
Compile-tested: mediatek/filogic (GL.iNet GL-MT6000).

**Comment by neheb** [comment]
I have this patch for tools/sparse that fixes compilation. Is it related?

```
--- a/sparse-llvm.c
+++ b/sparse-llvm.c
@@ -302,7 +302,7 @@ static LLVMValueRef get_sym_value(LLVMMo
 			LLVMSetGlobalConstant(data, 1);
 			LLVMSetInitializer(data, LLVMConstString(strdup(s), strlen(s) + 1, true));
 
-			result = LLVMConstGEP(data, indices, ARRAY_SIZE(indices));
+			result = LLVMConstGEP2(type, data, indices, ARRAY_SIZE(indices));
 			return result;
 		}
 		default:
@@ -485,7 +485,7 @@ static LLVMValueRef calc_gep(LLVMBuilder
 	/* convert base to char* type */
 	base = LLVMBuildPointerCast(builder, base, bytep, name);
 	/* addr = base + off */
-	addr = LLVMBuildInBoundsGEP(builder, base, &off, 1, name);
+	addr = LLVMBuildInBoundsGEP2(builder, type, base, &off, 1, name);
 	/* convert back to the actual pointer type */
 	addr = LLVMBuildPointerCast(builder, addr, type, name);
 	return addr;
@@ -705,13 +705,15 @@ static LLVMValueRef calc_memop_addr(stru
 static void output_op_load(struct function *fn, struct instruction *insn)
 {
 	LLVMValueRef addr, target;
+	LLVMTypeRef type;
 	char name[MAX_PSEUDO_NAME];
 
 	addr = calc_memop_addr(fn, insn);
+	type = LLVMTypeOf(addr);
 
 	/* perform load */
 	pseudo_name(insn->target, name);
-	target = LLVMBuildLoad(fn->builder, addr, name);
+	target = LLVMBuildLoad2(fn->builder, type, addr, name);
 
 	insn->target->priv = target;
 }
@@ -801,6 +803,7 @@ static void output_op_call(struct functi
 	int n_arg = 0, i;
 	struct pseudo *arg;
 	LLVMValueRef *args;
+	LLVMTypeRef type;
 	char name[64];
 
 	n_arg = pseudo_list_size(insn->arguments);
@@ -819,7 +822,8 @@ static void output_op_call(struct functi
 	FINISH_PTR_LIST(ctype);
 
 	pseudo_name(insn->target, name);
-	target = LLVMBuildCall(fn->builder, func, args, n_arg, name);
+	type = LLVMTypeOf(func);
+	target = LLVMBuildCall2(fn->builder, type, func, args, n_arg, name);
 
 	insn->target->priv = target;
 }

```

**Comment by rockdrilla** [comment]
@neheb IDK why `tools/sparse` was built without errors on my machine, but your patch looks similar to [this commit](https://git.kernel.org/pub/scm/devel/sparse/sparse.git/commit/?id=0544c547682b878758eea731ef4b8e64e5ec91fb).

**Comment by neheb** [comment]
I use GCC14 on my machine. Anyway, I'll backport that.

**Comment by rockdrilla** [comment]
Important notice: this MR **no longer** requires #15702 and #15703 to be merged first (due to build-time configuration `-DLLVM_DEFAULT_TARGET_TRIPLE=bpf`).

**Comment by rockdrilla** [comment]
NB: LLVM 18.1.8 doesn't have any major changes (`std::string` fixes).

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
