### PR TITLE
kernel: 6.1: Backport Turris Omnia LED patches

### PR DESCRIPTION
**Pull request by lixkel**
This backports patches
  leds: turris-omnia: Use sysfs_emit() instead of sprintf()
  leds: turris-omnia: Drop unnecessary mutex locking
  leds: turris-omnia: Do not use SMBUS calls
  leds: turris-omnia: Make set_brightness() more efficient
  leds: turris-omnia: Support HW controlled mode via private trigger
  leds: turris-omnia: Add support for enabling/disabling HW gamma correction
into backport-6.1 and patch
  leds: turris-omnia: Fix brightness setting and trigger activating
into pending-6.1.

The above patches replace:
  leds: turris-omnia: support HW controlled mode via private trigger
  leds: turris-omnia: initialize multi-intensity to full
  leds: turris-omnia: change max brightness from 255 to 1
from mvebu/patches-6.1.

### CODE REVIEW

**Comment by Ansuel** [comment]
@lixkel the pending one is pending or merged but still needs to be merged in linux-next? (want to know why in pending and not in backport)

**Comment by lixkel** [comment]
@Ansuel Lee has applied the patch locally, but has yet to merge it into his -next branch.
https://lore.kernel.org/linux-leds/169771730067.2462718.13976120509366125466.b4-ty@kernel.org/

**Comment by Ansuel** [comment]
@lixkel then please move them to backport directly since they are accepted.

Pending usage is for patch that are still in review or are in submission progress.

**Comment by lixkel** [comment]
@Ansuel done.

**Comment by BKPepe** [comment]
Is there any chance to get this backported even to kernel 5.15? I see that @elkablo prepared [same series](https://gitlab.nic.cz/turris/os/build/-/merge_requests/674) for your Turris OS, which has 5.15 kernel. It would be really nice to have it in sync with upstream. 🙌

**Comment by elkablo** [comment]
@BKPepe yes, we have some more changes for 6.1 and once they are merged we will also push for 5.15

**Pull request merged**
