### PR TITLE
Add W25Q256JV support for ar71xx

### PR DESCRIPTION
**Pull request by mantas-p**
Winbond W25Q256JV and W25Q256FV chips have same JEDEC ID even they are functionally different.

 * W25Q256FV has incomplete 4-byte address instruction set (only read) and HOLD/RESET pin.
 * W25Q256JV leaves out RESET pin functionality in WSON package, but has a complete 4-byte instruction set.
    
Only way to reliably use W25Q256JV chip on ar71xx platform is to always use native 4-byte commands and never enter 4-byte address mode. Otherwise external or watchdog reset may leave flash in 4-byte mode and system unable to boot.

This patch partialy backports SFDP parser from [1] to help differentiate between chips. Parts of code that parsed for properties not used in v4.9 kernel were removed. For W25Q256JV it then enables native 4-byte opcode set instead of entering 4-byte mode. Also there's a fix to avoid using mmaped fast read when fetching SFDP data.

[1] mtd: spi-nor: parse Serial Flash Discoverable Parameters (SFDP) tables
    by: Cyrille Pitchen <cyrille.pitchen@microchip.com>
    f384b352cbf0310fd20c379c4710408c70e769b6

### CODE REVIEW

**Comment by ratkaj** [comment]
My Lima board is up and running for almost a week now with these patches included into build. So far i can really say there were no issues. Looking good.

**Comment by ynezz** [comment]
@mantas-p Can you please check if this PR is still actual with ar71xx now being on 4.14?

**Comment by mantas-p** [comment]
Yes this is outdated as of now. For 4.14 patch still would be needed, though much smaller. I still haven't got around checking if latest upstream fixes (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/mtd/spi-nor/spi-nor.c?h=v4.20-rc5&id=b038e8e3be724dd293a0849f5fe267fdddcca9dd) solves current issue.

**Comment by ynezz** [comment]
@mantas-p Feel free to close this outdated PR request and open the new one once it's ready. Thanks.

**Comment by T-X** [comment]
@mantas-p do you (or anyone else) know if this is still needed for a Lima board or if it was substituted/obsoleted by something else in OpenWrt 19.07?

**Comment by mantas-p** [comment]
@T-X, fix was eventually merged into master (4745969ad7c0cb65f55c8de1f05eba786ca27f71)
For 19.07 you can try this: https://gist.github.com/mantas-p/b269feb098775cc896b4f415c106d353

**Pull request closed without merging**
