### PR TITLE
layerscape: armv8_64b: enable CONFIG_ARM_PSCI_CPUIDLE

### PR DESCRIPTION
**Pull request by sch-m**
@yangbolu1991 
Enable PSCI firmware based CPUidle driver.
PSCI firmware is the standard power management control for all ARM64
based platforms.

Signed-off-by: Martin Schiller <ms@dev.tdt.de>

### CODE REVIEW

**Comment by adschm** [comment]
"layerscape: armv8_64b: ..."

**Comment by sch-m** [comment]
> "layerscape: armv8_64b: ..."

OK, I've updated the commit subject.

**Comment by sch-m** [comment]
Synced patch with latest master.

**Comment by hauke** [comment]
Thank you for the patch. I applied it to master.

**Pull request closed without merging**
