### PR TITLE
kernel: support for Intel(R) x710 10/40GbE adapters PF/VF devices

### PR DESCRIPTION
**Pull request by peterwillcn**
Add Support for Intel(R) 10/40GbE PCI Express x710 adapters: 
- kmod-i40e	4.14.101-1	Kernel modules for Intel(R) Ethernet Controller XL710 Family 10/40 Gigabit Ethernet adapters.	
- kmod-i40evf	4.14.101-1	Kernel modules for Intel(R) Ethernet Controller XL710 Family Virtual Function Ethernet adapters.

```
[    0.000000] Linux version 4.19.24 (openwrt@robot) (gcc version 7.4.0 (OpenWrt GCC 7.4.0 r9420-c17a68c)) #0 SMP Sat Feb 23 01:58:20 2019
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz root=PARTUUID=82ee4abc-02 rootfstype=ext4 rootwait console=tty0 console=ttyS0,115200n8 noinitrd
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[  3.359563] i40e: Intel(R) Ethernet Connection XL710 Network Driver - version 2.1.14-k
[  3.374535] i40e: Copyright (c) 2013 - 2014 Intel Corporation.
[  3.376581] i40evf: Intel(R) 10 Gigabit PCI Express Virtual Function Network Driver - version 2.1.14-k
[  3.377524] i40evf: Copyright (c) 2009 - 2015 Intel Corporation.
[  3.378532] i40evf 0000:00:05.0: 00:11:22:33:93:01
[  3.379527] i40evf 0000:00:05.0: MAC: 4
[  3.380096] i40evf 0000:00:05.0: Intel(R) X710 Virtual Function
[  3.384642] i40evf 0000:00:06.0: 00:11:22:33:93:02
[  3.389573] i40evf 0000:00:06.0: MAC: 4
[  3.392017] i40evf 0000:00:06.0: Intel(R) X710 Virtual Function
```

Compile-tested on: x86_64
Runtime-tested on: x86_64

Signed-off-by: Xiaobo Tian <peterwillcn@gmail.com>

### CODE REVIEW

**Comment by peterwillcn** [comment]
Closed, turn on Intel x710 support when the 19.03 kernel is upgraded to 4.19!

**Comment by peterwillcn** [comment]
Closed, turn on Intel x710 support when the 19.03 kernel is upgraded to 4.19!

**Comment by supersebbo** [comment]
What was the reason for pausing this until the Kernel is at 4.19?  It works just fine on 4.14 in the 19.07 branch.

**Comment by peterwillcn** [comment]
@supersebbo https://github.com/openwrt/openwrt/commit/5d81b28a829ac20fb60991e71ee7a7c53d14fd58

**Pull request closed without merging**
