### PR TITLE
exfatprogs: update to 1.0.3

### PR DESCRIPTION
**Pull request by neheb**
exfatprogs: update to 1.0.3

This release removes iconv dependency which needed nls.mk before.

It also removes the library component.

Switch from old name to new name in Makefile.

Fixed license information.

Several other cleanups for consistency between packages.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

From: https://patchwork.ozlabs.org/project/openwrt/list/?series=172822

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
I saw your patch to mailing list to migrate xfsprogs to packages.
Maybe this can be moved to packages feed too? It's not needed by anything in the main repo.

**Comment by neheb** [comment]
Beats me. @dangowrt added it here.

**Comment by bobafetthotmail** [comment]
in this commit, where there is no commit description or anything else that ties this package to any current or future use by other packages in core OpenWrt repo https://github.com/openwrt/openwrt/commit/de634663643ae7e09522dd22165bb8793631b26f

**Comment by neheb** [comment]
I should also mention that it fails on https://downloads.openwrt.org/snapshots/faillogs/arc_archs/base/exfat-utils/compile.txt

This PR fixes it.

**Comment by ynezz** [comment]
As always, this package would have better care and maintenance at packages feed repo, so I'm all in to move it there. I would express my negative view in the review on this, but didn't get a chance :-)

**Comment by neheb** [comment]
OK. Placed in packages: https://github.com/openwrt/packages/pull/12378

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
