### PR TITLE
dnsmasq: dnssec+ntp initscript fixes

### PR DESCRIPTION
**Pull request by hmh**
Fix FS#2574 (dnssec + ntp chicken-and-egg workaround not working), and also remove the use of "test -a" and "test -o" (as in "[ ... -a ... ]" and "[ ... -o ... ]").

The individual commits have more details in their commit logs.

Signed-off-by: Henrique de Moraes Holschuh <henrique@nic.br>

### CODE REVIEW

**Comment by hmh** [comment]
(if this PR is accepted, at least the second commit "fix dnssec+ntp ..." should be backported to the still active branches).

**Comment by dedeckeh** [comment]
Patches pushed to master; thx

**Comment by jonathanunderwood** [comment]
Any chance of this fix being pulled in to the next 19.07 release to fix the DNSSEC/NTP chicken-and-egg breakage? This is a regression relative to 18.06.

**Comment by hmh** [comment]
For the record, ensure "uci set system.ntp.enabled=1" and it will work around the bug.

The fact that there isn't an uci-defaults script that forces that setting when that uci node is missing seems to be a bug in itself.

**Comment by jonathanunderwood** [comment]
> For the record, ensure "uci set system.ntp.enabled=1" and it will work around the bug.
> 
> The fact that there isn't an uci-defaults script that forces that setting when that uci node is missing seems to be a bug in itself.

I have reported this here: https://bugs.openwrt.org/index.php?do=details&task_id=3022

**Pull request closed without merging**
