### PR TITLE
mediatek: filogic: prevent faulty mac address assignment

### LINKED ISSUE #15507: mac address assignment using nvmem-layout fails for eth0 on mt7981b devices
During the porting work for the [cudy,m3000](https://github.com/openwrt/openwrt/pull/14393), we noticed that the mac address assignment for mac@0 doesn't work through `nvmem-layout`.
I noticed this happened for the yuncore,ax835 during a [cleanup commit](cfee7fa36682be3476b5b27e8affad99c8753934).

Example:

```
&eth {
  pinctrl-names = "default";
  pinctrl-0 = <&mdio_pins>;
    
  status = "okay";
    
  gmac0: mac@0 {
    compatible = "mediatek,eth-mac";
    reg = <0>;
    phy-mode = "2500base-x";
    phy-handle = <&rtl8221b_phy>;

    nvmem-cell-names = "mac-address";
    nvmem-cells = <&macaddr_bdinfo_de00 1>; /* <- doesn't work (even with a 0) */
  };

  gmac1: mac@1 {
    compatible = "mediatek,eth-mac";
    reg = <1>;
    phy-mode = "gmii";
    phy-handle = <&int_gbe_phy>;

    nvmem-cell-names = "mac-address";
    nvmem-cells = <&macaddr_bdinfo_de00 0>;
  };
};

&bdinfo {
          nvmem-layout {
          compatible = "fixed-layout";
          #address-cells = <1>;
          #size-cells = <1>;

          macaddr_bdinfo_de00: macaddr@de00 {
            #nvmem-cell-cells = <1>;
            compatible = "mac-base";
            reg = <0xde00 0x6>;
          };
        };
}l
```

`of_get_mac_address` is called twice for `mac@0`.
the first time, it finds a `local-mac-address` (that doesn't come from bdinfo but is consistent through reboots)
EDIT: no, it's not consistent. i misremembered.
the second time, it finds that same address in `mac-address `.

```
[    1.066786] of_get_mac_address for mac@0
[    1.070710] of_get_mac_address mac-address -19
[    1.075140] of_get_mac_address local-mac-address 0
[    1.079942] of_add_mac_address ret 0: d6:37:bf:39:da:6a

[    1.084809] of_get_mac_address for mac@1
[    1.088725] of_get_mac_address mac-address -19
[    1.093155] of_get_mac_address local-mac-address -19
[    1.098109] of_get_mac_address address -19
[    1.102723] of_get_mac_address nvmem 0: 80:af:ca:15:84:04
[    1.108134] of_add_mac_address ret 0: 80:af:ca:15:84:04

[    1.113001] of_get_mac_address for mac@0
[    1.116920] of_get_mac_address mac-address 0
[    1.121186] of_add_mac_address ret 0: d6:37:bf:39:da:6a
```

The most confusing thing is, there is a `mac-address` in sysfs:
```
$ hexdump -C /sys/firmware/devicetree/base/soc/ethernet@15100000/ma
c@0/mac-address 
00000000  d6 37 bf 39 da 6a                                 |.7.9.j|
```
(EDIT: `of_add_mac_address` puts it there, alright)
`local-mac-address` is also chilling there... why?

How does that get there?!

### OpenWrt target/subtarget

mediatek/filogic

### PR DESCRIPTION
**Pull request by ondrani**
This extends this fix #15507 also for Cudy WR3000

see also:
#15587
#15515

### CODE REVIEW

**Comment by hauke** [comment]
The change looks fine. I am wondering why you add the signed off by line from @yogo1212. Was he involved or did you just apply the changes from a55ab9e1343e85021253e9c55f67adf33ad68f09 to the WR300?

**Comment by ondrani** [comment]
> The change looks fine. I am wondering why you add the signed off by line from @yogo1212. Was he involved or did you just apply the changes from [a55ab9e](https://github.com/openwrt/openwrt/commit/a55ab9e1343e85021253e9c55f67adf33ad68f09) to the WR300?

Yeah, I just applied the changes from https://github.com/openwrt/openwrt/commit/a55ab9e1343e85021253e9c55f67adf33ad68f09. I don't have the knowledge about the .dts file but it works also for the WR3000. I just wanted to somehow mention him that he is the true author of that idea.

**Comment by hauke** [comment]
You should use your name as author. You can change it with: `git commit --amend --author="Ondřej Niesner <ondra.niesner@seznam.cz>"`

You can reference the commit a55ab9e1343e85021253e9c55f67adf33ad68f09.

**Comment by yogo1212** [comment]
@ondrani @hauke i don't mind either way :-)

**Pull request merged**
