### PR TITLE
rtl83xx: make debugfs use constants from mach-rtl83xx

### PR DESCRIPTION
**Pull request by MaZderMind**
This PR cleans up come code around `net/dsa/rtl83xx/debugfs.c` by referencing the register-values from `asm/mach-rtl838x/mach-rtl83xx.h`, fixing a register definition there and fixing a broken indentation.

The `RTL8390` constants in `net/dsa/rtl83xx/debugfs.c` are not reflected in `asm/mach-rtl838x/mach-rtl83xx.h` and I would like to know if I should rework them too.

### CODE REVIEW

**Comment by MaZderMind** [comment]
(sorry for opening the PR before fixing the summary/descripton)

**Comment by MaZderMind** [comment]
Commit-Name changed to Real Name, Sign-Off added and rebased to current main.

**Comment by Ansuel** [comment]
@MaZderMind  can you wrap the commit description to 80 columns?

**Comment by MaZderMind** [comment]
Will do this evening 👌

**Comment by MaZderMind** [comment]
@Ansuel I fixed the commit message wrap. Sorry for all the formality issues, These are my first PRs to openwrt or a project with this kind of requirements. I think I have the git-config/editor-settings nailed down for now, so future commits should be conformant.

I'm not sure I understand your other comment correctly. The `rtl83xx` family of SOCs are Switch-SOCs with embedded MIPS CPU. I'm not sure about the terminology here, if `mach` only refers to the architecture or a specific part of the SOC. I stumbled upon the duplicated defines while working on #13524 where I used these registers and wanted to try to clean this up. The whole `rtl83xx` platoform code seems to be mixed with the (very similar) `rtl93xx` family code by putting `if/else` branches everywhere and resuing code named `83xx` for `93xx` things, instead of splitting the specific it up into different modules, but fixing this is a major undertaking that I don't think I am ready to do quite yet.

**Comment by Ansuel** [comment]
> I fixed the commit message wrap. Sorry for all the formality issues, These are my first PRs to openwrt or a project with this kind of requirements. I think I have the git-config/editor-settings nailed down for now, so future commits should be conformant.

can you share what setting you use? do you use nano as editor? We apply the same rules used to submit patches to the linux kernel.



> I'm not sure I understand your other comment correctly. The `rtl83xx` family of SOCs are Switch-SOCs with embedded MIPS CPU. I'm not sure about the terminology here, if `mach` only refers to the architecture or a specific part of the SOC. I stumbled upon the duplicated defines while working on #13524 where I used these registers and wanted to try to clean this up. The whole `rtl83xx` platoform code seems to be mixed with the (very similar) `rtl93xx` family code by putting `if/else` branches everywhere and resuing code named `83xx` for `93xx` things, instead of splitting the specific it up into different modules, but fixing this is a major undertaking that I don't think I am ready to do quite yet.

the question was just that... does these switch are ONLY embedded or they can also be present outside as IS?
We had similar situation where the qca8k driver was an external switch and then the same regmap used as an internal switch in the ipq40xx soc... I was just confused noticing that we are putting these define in the mach include directory that is limited to stuff for the arch and can't be used externally... (example an external switch on an arm cpu)

Again was just a question/curiosity. I'm just checking the change and I need some info on how things works for realtek switch.

**Comment by MaZderMind** [comment]
> can you share what setting you use? do you use nano as editor? We apply the same rules used to submit patches to the linux kernel.
I use sublime as editor also for my commit messages. I just configured a per-filetype config with https://github.com/randy3k/AutoWrap configured. I'm fairly new to kernel work.

> the question was just that... does these switch are ONLY embedded or they can also be present outside as IS? 
Ah, I see. I don't think that they are intended or suited as a peripheral. They have built in DDR1/2/3 support and the only external interface would be two UARTs.

As a peripheral the RTL8367N or simil would be more suited, which is already supported by OpenWrt (as a peripheral).

> Again was just a question/curiosity. I'm just checking the change and I need some info on how things works for realtek switch.
I'm by no means an expert in Realtek Switches. My goal is to make the out-of-the-box experience for OpenWrt these devices better (and fixing stuff along the way, if needed). I just stumbled into this because the Netgear GS308T is nice an cheap OpenWrt supported L2-Switch.

**Comment by MaZderMind** [comment]
can we merge this? @Ansuel

**Pull request merged**
