### PR TITLE
ramips: mt7621: Fix DNA EX400 mac address retrieval

### PR DESCRIPTION
**Pull request by msandber**
The initial commit where DNA Valokuitu Plus EX400 was introduced left the device with no network connectivity. To fix this create kernel modules kmod-ubi-nvmem and kmod-nvmem-uboot-env and use them for the devices. Also, repair the DTS file.

### CODE REVIEW

**Comment by neheb** [comment]
That UBI needs compatible = "linux,ubi";

ping @dangowrt

**Comment by msandber** [comment]
> That UBI needs compatible = "linux,ubi";

@neheb already tried it. Please see [here](https://github.com/openwrt/openwrt/pull/13798#issuecomment-2354695215)

**Comment by neheb** [comment]
I believe you need CONFIG_NVMEM_SYSFS=y for that.

**Comment by neheb** [comment]
oh wait a minute, you need CONFIG_NVMEM_U_BOOT_ENV=y

**Comment by neheb** [comment]
as for your redundant bool question, you need to use hexdump -C. If you have 4 bytes before text, it's single. If 5, it's redundant.

See https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/drivers/nvmem/layouts/u-boot-env.c?h=next-20240918#n17

**Comment by msandber** [comment]
@neheb Thanks for your reply.

> oh wait a minute, you need CONFIG_NVMEM_U_BOOT_ENV=y

```
--- a/target/linux/ramips/mt7621/config-6.6
+++ b/target/linux/ramips/mt7621/config-6.6
@@ -201,6 +201,8 @@ CONFIG_NR_CPUS=4
 CONFIG_NVMEM=y
 CONFIG_NVMEM_LAYOUTS=y
 # CONFIG_NVMEM_LAYOUT_MIKROTIK is not set
+CONFIG_NVMEM_LAYOUT_U_BOOT_ENV=y
+CONFIG_NVMEM_U_BOOT_ENV=y

```
> as for your redundant bool question, you need to use hexdump -C. If you have 4 bytes before text, it's single. If 5, it's redundant.
It's 5, and I tried both `u-boot,env-redundant-bool` and `u-boot,env-redundant-count`

**Comment by neheb** [comment]
If adding CONFIG_NVMEM_SYSFS=y , do you get anything in sysfs?

**Comment by msandber** [comment]
> If adding CONFIG_NVMEM_SYSFS=y , do you get anything in sysfs?

Nothing.

**Comment by msandber** [comment]
@rmilecki Friendly ping, any suggestions on how to go forward?

**Comment by neheb** [comment]
this is a longshot. With those configs as well,

```
--- a/target/linux/ramips/dts/mt7621_dna_valokuitu-plus-ex400.dts
+++ b/target/linux/ramips/dts/mt7621_dna_valokuitu-plus-ex400.dts
@@ -80,14 +80,11 @@
 
                        volumes {
                                ubi-volume-env1 {
+                                       compatible = "u-boot,env-redundant-count";
                                        volname = "env1";
 
-                                       nvmem-layout {
-                                               compatible = "u-boot,env";
-
-                                               ethaddr: ethaddr {
-                                                       #nvmem-cell-cells = <1>;
-                                               };
+                                       ethaddr: ethaddr {
+                                               #nvmem-cell-cells = <1>;
                                        };
                                };
                        };

```

**Comment by msandber** [comment]
It needs still CONFIG_MTD_UBI_NVMEM=y and then it works

**Comment by msandber** [comment]
I tried to package MTD_UBI_NVMEM, NVMEM_LAYOUT_U_BOOT_ENV and CONFIG_NVMEM_U_BOOT_ENV in kernel modules. They are shipped on to the device alright, but they are not being loaded properly. Can you please have a look the nvmem.mk file? I tried different combinatios of AutoProbe and AutoLoad with several priorities and flagging them as boot.

**Comment by msandber** [comment]
It's working now. Ping @myllyja if you want to test it out.

**Comment by msandber** [comment]
Dropped CONFIG_NVMEM_U_BOOT_ENV  as unnecessary, only the nvmem layout is needed.

**Comment by robimarko** [comment]
Why not just build these into the kernel?

**Comment by msandber** [comment]
> Why not just build these into the kernel?

Simply because not all devices need it I thought loading modules would make sense. But of course they can be built-in. Let me know.

**Comment by msandber** [comment]
Creted an alternative PR for the same goal that adds nvmem-on-ubi and u-boot env nvmem layout as built-in components. Please see [here](https://github.com/openwrt/openwrt/pull/16573). If either find its way to the main, the other one can just be dropped.

**Comment by hauke** [comment]
These two drivers are pretty small and they do not have any new dependencies. I think adding it into the kernel binary is fine.

**Comment by hauke** [comment]
I merged the changes from #16573

**Pull request closed without merging**
