### PR TITLE
kernel: bump 5.10 to 5.10.92

### PR DESCRIPTION
**Pull request by rsalvaterra**
Patches automatically rebased.

Run-tested:
ramips/mt7621 (Redmi AC2100)

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by graysky2** [comment]
```
Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200
```

**Comment by PerkelSimon** [comment]
tested on ipq806x/tplink c2600, working good

**Comment by graysky2** [comment]
@rsalvaterra - Why the bump?  The two commits seems identical content-wise.

**Comment by rsalvaterra** [comment]
> @rsalvaterra - Why the bump? The two commits seems identical content-wise.

Trivial rebase on top of current master.

**Comment by graysky2** [comment]
```
Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200
```

Matches the one I did.  One thing I am finding peculiar.  What is the output of this command for you, @rsalvaterra

```
grep -m 1 Version tmp/info/.targetinfo-mediatek | uniq | awk '{ print $2 }'
```

Adjust it to the target you built.  For me, even though I build 5.10.92, it returns `5.10.90`

**Comment by rsalvaterra** [comment]
> ```
> Build system: x86_64
> Build-tested: bcm2711/RPi4B, mt7622/RT3200
> Run-tested: bcm2711/RPi4B, mt7622/RT3200
> ```
> 
> Matches the one I did. One thing I am finding peculiar. What is the output of this command for you, @rsalvaterra
> 
> ```
> grep -m 1 Version tmp/info/.targetinfo-mediatek | uniq | awk '{ print $2 }'
> ```
> 
> Adjust it to the target you built. For me, even though I build 5.10.92, it returns `5.10.90`

Strange, are you sure you're not just seeing stale information? I usually `rm -r tmp/` after doing a kernel bump, before building a new image for my target. Surely enough, after verifying, all 5.10 targets in `tmp/info/.targetinfo-*` are at 5.10.92 here.

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in 7229981994d3459e9bd5911b3e36fd09ab4ec428 and 61e58f7cecb9f6044375dd7839f56a6e07807903

**Comment by graysky2** [comment]
That must have been it... added a `rm -rf tmp` to my build script.

**Pull request closed without merging**
