### PR TITLE
layerscape: harmonize device strings in device definition

### PR DESCRIPTION
**Pull request by adschm**
OpenWrt lately has harmonized device (definition) names to the
pattern vendor_model to improve overall consistency, also with
other values like the DTS compatible.

This patch applies that scheme to the layerscape target.

Since this (intentionally) creates a bigger overlap between DTS names,
compatible, and device definition name, it also moves DEVICE_DTS and
SUPPORTED_DEVICES definitions to the Device/Default blocks.

Where deviating, variables can still be set individually to overwrite.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
@yangbolu1991 @mcbridematt

**Comment by mcbridematt** [comment]
Ok with me (Traverse boards)

**Comment by yangbolu1991** [comment]
It looks good to me.
Thanks.

**Comment by yangbolu1991** [comment]
Sorry, wait, did you have a build test?
The IMAGE/firmware.bin and sysupgrade.bin definition are mostly using $(1) in image name to append images.
There may be build problem.

**Comment by adrianschmutzler** [comment]
> Sorry, wait, did you have a build test?
> The IMAGE/firmware.bin and sysupgrade.bin definition are mostly using $(1) in image name to append images.
> There may be build problem.

No, so far this was code work only. I will have a specific look into the IMAGE definitions and of course also build test at some point.

**Comment by yangbolu1991** [comment]
@adrianschmutzler Thank you.
BTW, on current mainline there is now a kernel build issue for layerscape.
I had sent out a temporary fix-up, waiting for our IP owner's proper fix. But it was rejected.
Here is my pull request in case you want to try building.
https://github.com/openwrt/openwrt/pull/3179

**Comment by adrianschmutzler** [comment]
I at least forgot to update BUILD_DEVICES in uboot-layerscape. Will take care.

**Comment by adrianschmutzler** [comment]
@yangbolu1991 I've worked through all the packages and was able to build-test all devices successfully (I also checked default settings, though, nothing from packages repo etc.).

I've added your temporary fix here as I used it for building, but I won't merge it as it got rejected already.

I'd be happy if you could have another look and possible test at one of the devices, as I don't have any.

**Comment by yangbolu1991** [comment]
@adrianschmutzler The changes look perfect to me.
I had verified on ls1043ardb with sdboot. The basic network and sysupgrade worked fine. Attached the log.
Thanks!
[ls1043ardb-sdboot.txt](https://github.com/openwrt/openwrt/files/4979955/ls1043ardb-sdboot.txt)

**Comment by adrianschmutzler** [comment]
Thanks, I will merge it later today then.

**Pull request closed without merging**
