### PR TITLE
Fedora 34/35 use alias and proc for 'which' and it breaks 'which' detection of 'which'

### PR DESCRIPTION
**Pull request by JiiPee74**
```
[jiipee@fedoradev openwrt]$ which which
which ()
{ 
    ( alias;
    eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"
}

```

That will cause openwrt build prereq to fail at least on Fedora 34 and 35.
Simply adding 'env' solve this issue.

```
[jiipee@fedoradev openwrt]$ env which which
/usr/bin/which
```

Another option would be adding some opts for which

```
[jiipee@fedoradev openwrt]$ which --skip-functions --skip-alias which
/usr/bin/which
```

But I think env route is better, simpler.

### CODE REVIEW

**Comment by neheb** [comment]
Funny. I use Fedora 34 and don't run into this. However CentOS 8(based on recent fedora) does. Maybe I need to reinstall...

**Comment by aparcar** [comment]
Please rebase your changes.

**Comment by JiiPee74** [comment]
That is strange, I just made build enviroment less than week ago for centos 8 and didn't have this issue there, but today I made new with Fedora 35 on another machine and hit this issue.

**Comment by neheb** [comment]
Oh maybe it was CentOS Stream.

**Comment by JiiPee74** [comment]
@aparcar Sorry, I have no idea how to do that. I have been trying to do this pr now like 3 hours. I am 1st time working with git like this.
For this simple 3 letter fix, way too much time spend. Maybe I learn to use this some day but it's clearly is not today.

**Comment by aparcar** [comment]
Merged via https://github.com/openwrt/openwrt/commit/fca5ad55d292f8e481406123d0e95b3c85d39733

**Comment by httpstorm** [comment]
This breaks macOS, please revert and revise the patch!

```
g@gMac:/Volumes/wrt3200/openwrt$ ./scripts/feeds update -a
Updating feed 'packages' from 'https://git.openwrt.org/feed/packages.git' ...
Cloning into './feeds/packages'...
remote: Enumerating objects: 6361, done.
remote: Counting objects: 100% (6361/6361), done.
remote: Compressing objects: 100% (5293/5293), done.
remote: Total 6361 (delta 226), reused 4726 (delta 146)
Receiving objects: 100% (6361/6361), 4.26 MiB | 3.12 MiB/s, done.
Resolving deltas: 100% (226/226), done.
Updating feed 'luci' from 'https://git.openwrt.org/project/luci.git' ...
Cloning into './feeds/luci'...
remote: Enumerating objects: 8914, done.
remote: Counting objects: 100% (8914/8914), done.
remote: Compressing objects: 100% (4128/4128), done.
remote: Total 8914 (delta 2881), reused 6264 (delta 940)
Receiving objects: 100% (8914/8914), 7.67 MiB | 3.59 MiB/s, done.
Resolving deltas: 100% (2881/2881), done.
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git' ...
Cloning into './feeds/routing'...
remote: Enumerating objects: 384, done.
remote: Counting objects: 100% (384/384), done.
remote: Compressing objects: 100% (312/312), done.
remote: Total 384 (delta 26), reused 311 (delta 18)
Receiving objects: 100% (384/384), 256.04 KiB | 1.31 MiB/s, done.
Resolving deltas: 100% (26/26), done.
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git' ...
Cloning into './feeds/telephony'...
remote: Enumerating objects: 265, done.
remote: Counting objects: 100% (265/265), done.
remote: Compressing objects: 100% (252/252), done.
remote: Total 265 (delta 9), reused 67 (delta 1)
Receiving objects: 100% (265/265), 169.46 KiB | 1.69 MiB/s, done.
Resolving deltas: 100% (9/9), done.
Create index file './feeds/packages.index' 
Checking 'working-make'... ok.
Checking 'case-sensitive-fs'... ok.
Checking 'proper-umask'... ok.
Checking 'gcc'... ok.
Checking 'working-gcc'... ok.
Checking 'g++'... ok.
Checking 'working-g++'... ok.
Checking 'ncurses'... ok.
Checking 'perl-data-dumper'... ok.
Checking 'perl-findbin'... ok.
Checking 'perl-file-copy'... ok.
Checking 'perl-file-compare'... ok.
Checking 'perl-thread-queue'... ok.
Checking 'tar'... ok.
Checking 'find'... ok.
Checking 'bash'... ok.
Checking 'xargs'... ok.
Checking 'patch'... ok.
Checking 'diff'... ok.
Checking 'cp'... ok.
Checking 'seq'... ok.
Checking 'awk'... ok.
Checking 'grep'... ok.
Checking 'egrep'... ok.
Checking 'getopt'... ok.
Checking 'stat'... ok.
Checking 'unzip'... ok.
Checking 'bzip2'... ok.
Checking 'wget'... ok.
Checking 'install'... ok.
Checking 'perl'... ok.
Checking 'python2-cleanup'... ok.
Checking 'python'... ok.
Checking 'python3'... ok.
Checking 'python3-distutils'... ok.
Checking 'git'... ok.
Checking 'file'... ok.
Checking 'rsync'... ok.
Checking 'which'... ok.
Checking 'ldconfig-stub'... ok.
which: illegal option -- a
usage: env [-iv] [-P utilpath] [-S string] [-u name]
           [name=value ...] [utility [argument ...]]
Collecting package info: feeds/packages/mail/pigeonhole
```

**Comment by neheb** [comment]
I have no commit access.

Anyway, looks unfortunate.

**Comment by httpstorm** [comment]
Thanks Rosen, let's hope @aparcar is going to notice this sooner.
From what I see on macOS 11.6, the installed `/usr/bin/which` does support `-a`, so I assume the make system relays on the internal command for one of the shells, but I can't figure out which one. `bash` and `sh` work correctly, while `csh` does not support `which -a`, but it returns a different error. And we also have an error related to `env`.

```
env which which
/usr/bin/which

which which
/usr/bin/which

which -a bash
/usr/local/bin/bash
/bin/bash

/usr/local/bin/bash -c 'which -a env'
/usr/bin/env

/bin/bash -c 'which -a env'
/usr/bin/env

/bin/csh -c 'which -a env'
-a: Command not found.
/usr/bin/env
```

**Comment by aparcar** [comment]
@httpstorm do you have an idea which would work for both Mac and later Fedora versions?

Looking at the code we only need `which -a` at two redundant places:

```shell
Makefile
17:DISTRO_PKG_CONFIG:=$(shell which -a pkg-config | grep -E '\/usr' | head -n 1)

target/sdk/files/Makefile
17:DISTRO_PKG_CONFIG:=$(shell which -a pkg-config | grep -E '\/usr' | head -n 1)
```

Reverting this now break things for Fedora and the other way around, I'd prefer to come up with a real solution.

**Comment by httpstorm** [comment]
@aparcar 
I have access to an Ubuntu VM. I can also install Fedora and give you root access if you like to play with it, but I do not have much internal experience with how the make system works. We can also try TeamViewer on my MacBook? So far I noticed that in addition to reverting the patch, I have to start from an empty directory. Luckily `./scripts/feeds update -a` is the first command and fails within seconds.

**Comment by neheb** [comment]
The commit seems wrong anyway. env is not used for anything else in prereq-build.mk.

**Comment by httpstorm** [comment]
@neheb `which -a which` works on macOS.

```
$(eval $(call SetupHostCommand,which,Please install 'which', \
	which -a which | grep which))
```

Only these options are available:
```
which
     -a      List all instances of executables found (instead of just the
             first one of each).

     -s      No output, just return 0 if all of the executables are found, or
             1 if some were not found.
```

**Comment by httpstorm** [comment]
@neheb @aparcar 
```
[root@fedora ~]# which -a which
which ()
{
    ( alias;
    eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"
}
/usr/bin/which
/bin/which
```

**Comment by aparcar** [comment]
Reverted via https://github.com/openwrt/openwrt/commit/16e83a7491bb038187e918273671894992ae003c

We need to come up with a different solution

**Comment by httpstorm** [comment]
@aparcar Thanks! I noticed that after we run `./scripts/feeds update -a`, the configuration for `which` is cached, and reverting the patch has no effect. It would make sense to check what configuration is saved for macOS and Fedora. I e-mailed you my Skype and phone in case you wish to work together. I can provide you with access to both macOS and a Fedora VM.

**Comment by champtar** [comment]
(On my phone) Can we do something like
```
/usr/bin/which -a which,
/bin/which -a which,
which -a which
```

**Comment by fda77** [comment]
From https://github.com/openwrt/openwrt/commit/fca5ad55d292f8e481406123d0e95b3c85d39733#commitcomment-57359780

Works `command which which` ?

@httpstorm answered
```
...
However on macOS ./scripts/feeds update -a reports errors:
/Volumes/wrt3200/b/openwrt/staging_dir/host/bin/which: line 4: builtin: which: not a shell builtin
...
```

I have no Apples to test, on Fedora:
```
 ls -al  staging_dir/host/bin/which
lrwxrwxrwx. 1 open wrt 14  1. Okt 17:03 staging_dir/host/bin/which -> /usr/bin/which

 staging_dir/host/bin/which --version
GNU which v2.21, Copyright (C) 1999 - 2015 Carlo Wood.
GNU which comes with ABSOLUTELY NO WARRANTY;
This program is free software; your freedom to use, change
and distribute this program is protected by the GPL.

```

**Comment by httpstorm** [comment]
@fda77 Another thing that might work on Fedora would be
`which -a which | tail -1`, though that's a bad idea because it will use the non preferred version on any host.
We could also use some grep filter that ignores lines with brackets `{}()`. We could also print a warning if brackets are found in the which path and tell the user to `unset witch`.

**Comment by fda77** [comment]
I think using "tail" here is not a good idea, its not sure in which order the results are. Maybe the best hit is in the 1st line.
`which -a which --skip-functions --skip-alias` works too, but im not sure if which has these arguments on all systems. Why does "command" not work for you?

**Comment by httpstorm** [comment]
@fda77 As I stated earlier https://github.com/openwrt/openwrt/pull/4621#issuecomment-931835194 only `-a -s` is supported on macOS, and as I recall, on Ubuntu too.

**Comment by fda77** [comment]
Okay.. so why does "command" not work on macos? Is staging_dir/host/bin/which a link? And what is in line 4 (`head staging_dir/host/bin/which`)

**Comment by httpstorm** [comment]
@fda77 
```
/Volumes/wrt3200/b/openwrt/staging_dir/host/bin$ ll which
lrwxr-xr-x  1 g  staff  16 Oct  1 17:02 which@ -> /usr/bin/command

/Volumes/wrt3200/b/openwrt/staging_dir/host/bin$ cat /usr/bin/command 
#!/bin/sh
# $FreeBSD: src/usr.bin/alias/generic.sh,v 1.2 2005/10/24 22:32:19 cperciva Exp $
# This file is in the public domain.
builtin `echo ${0##*/} | tr \[:upper:] \[:lower:]` ${1+"$@"}

/bin/sh -c 'builtin which which'
/bin/sh: line 0: builtin: which: not a shell builtin

command which which
/usr/bin/which
```

**Comment by JiiPee74** [comment]
Does this work for MacOS?

```
root@OpenWrt:~# command -v which
/usr/bin/which
root@OpenWrt:~# command -v i_dont_have_this_command_installed
root@OpenWrt:~#

```

I cannot test, no mac here.

**Comment by neheb** [comment]
so if which -a which works on macOS and it works on Fedora, why not use that? The point of having which as a dependency is the -a option anyway.

**Comment by JiiPee74** [comment]
nevermind, if goal is to get /bin/which as an result, command -v doesn't work in fedora.

**Comment by JiiPee74** [comment]
> so if which -a which works on macOS and it works on Fedora, why not use that? The point of having which as a dependency is the -a option anyway.

Because grepping that result spit this on fedora

```
[jiipee@nas ~]$ which -a which | grep which
which ()
    eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"
/usr/bin/which
[jiipee@nas ~]$

```

so would need to do
```
[jiipee@nas ~]$ which -a which | grep which | tail -n 1
/usr/bin/which
[jiipee@nas ~]$
```

Or something else

**Comment by champtar** [comment]
If I remember correctly SetupHostCommand doesn't care about the output, if `a | b` return 0, then it does a symlink to a, if it doesn't return 0 it tries the next one. Can someone try the solution I posted previously ?

**Comment by fda77** [comment]
You could `| grep which$` but `head -n1` should be better if the best result as 1st.
To get the path should still `command which which` be the best, but the link was created wrong

**Comment by JiiPee74** [comment]
> You could `| grep which$` but `head -n1` should be better if the best result as 1st. To get the path should still `command which which` be the best, but the link was created wrong

```
[jiipee@nas ~]$ command which which
/usr/bin/which
[jiipee@nas ~]$ echo $?
0
[jiipee@nas ~]$ command no_command no_command
bash: no_command: command not found...
[jiipee@nas ~]$ echo $?
127
[jiipee@nas ~]$
```

that should work for fedora, also tested on CentOS 8, how about mac?

**Comment by aparcar** [comment]
I'm loosing track here, please somebody ping me one a solution came up.

**Comment by champtar** [comment]
@aparcar see my messages

**Comment by aparcar** [comment]
@champtar so you're thinking of the following?

```diff
diff --git a/include/prereq-build.mk b/include/prereq-build.mk
index 9242407b18..0072c17cd3 100644
--- a/include/prereq-build.mk
+++ b/include/prereq-build.mk
@@ -186,7 +186,9 @@ $(eval $(call SetupHostCommand,rsync,Please install 'rsync', \
        rsync --version </dev/null))
 
 $(eval $(call SetupHostCommand,which,Please install 'which', \
-       which which | grep which))
+       /usr/bin/which -s which | grep which, \
+       /bin/which -s which | grep which, \
+       which -s which))
 
 $(STAGING_DIR_HOST)/bin/mkhash: $(SCRIPT_DIR)/mkhash.c
        mkdir -p $(dir $@)
```

**Comment by champtar** [comment]
If we put `-s` then no `| grep which`

**Comment by httpstorm** [comment]
> I'm loosing track here, please somebody ping me one a solution came up.

@aparcar 
This might be a good solution: exclude lines containing `-`, and include lines containing `/which`. Works correctly when I run `./scripts/feeds update -a` on macOS. I also tried running the command in a Fedora terminal.
```
$(eval $(call SetupHostCommand,which,Please install 'which', \
	which -a which | grep -v '-' | grep /which))
```

**Comment by champtar** [comment]
(Still on my phone)
```
/usr/bin/which -s which, \
/bin/which -s which, \
which -s which))
```
Or
```
/usr/bin/which which, \
/bin/which which, \
which which))
```
Or
```
/usr/bin/which which | grep which, \
/bin/which which | grep which, \
which which | grep which))
```

**Comment by httpstorm** [comment]
I figured why `env which which` and `command which which` fail on macOS:
They result in `staging_dir/host/bin/which` being a link to `/usr/bin/env` or `/usr/bin/command` while `which -a which | grep -v '-' | grep /which` or the original `which which | grep which` link to `/usr/bin/which` and work correctly. So whatever command we start with, the make system locates and links to it. This might be a bug or intentional decision elsewhere.

**Comment by champtar** [comment]
@httpstorm that's what I said some messages ago :)
Can you try my solutions ?

**Comment by httpstorm** [comment]
@champtar All three variants work on macOS 11.6. https://github.com/openwrt/openwrt/pull/4621#issuecomment-932609314

**Comment by fda77** [comment]
In include/prereq.mk "SetupHostCommand" is defined. It runs some shell commands including "which"... to detect which itself and create the (wrong) link. Maybe replacing this which by command too avoids the wrong link.
Pipe multiple time grep (slow) or using hardcoded paths (whats about /usr/local/ ?) is bad style

**Comment by httpstorm** [comment]
@fda77 Running grep twice takes a few milliseconds and will not slow the build, because this step is performed only once to generate the symbolic link. It might be possible to use two patterns with one grep, though the pipe is more simple and less switches means better compatibility.

**Comment by champtar** [comment]
@aparcar I would pick solution number 2 but @httpstorm confirmed all are working on MacOS so you can pick your favorite ;)

**Comment by JiiPee74** [comment]
How about?

'which which | grep -o "/.*which"'

How many systems that will break because stripped down grep?

works on fedora 34, centos 7, centos 8, openwrt snapshot

**Comment by aparcar** [comment]
https://github.com/openwrt/openwrt/pull/4628

**Comment by champtar** [comment]
@JiiPee74 SetupHostCommand doesn't care about the output, just the return code and what executable is run, see other comments

**Comment by aparcar** [comment]
Fixed via https://github.com/openwrt/openwrt/commit/0d1ebf0d6d20f0439ab45b293f9daa7662c44ba6

**Pull request closed without merging**
