### PR TITLE
omap: update u-boot and switch to kernel 5.10

### PR DESCRIPTION
**Pull request by dhewg**
Runtime tested on beagleblack, bootlog with this PR from eMMC:
```
U-Boot SPL 2021.07 (Sep 11 2021 - 10:30:59 +0000)
Trying to boot from MMC2


U-Boot 2021.07 (Sep 11 2021 - 10:30:59 +0000)

CPU  : AM335X-GP rev 2.1
Model: TI AM335x BeagleBone Black
DRAM:  512 MiB
WDT:   Started with servicing (60s timeout)
NAND:  0 MiB
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from FAT... <ethaddr> not set. Validating first E-fuse MAC
Net:   eth2: ethernet@4a100000, eth3: usb_ether
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mmc 1:1...
Found U-Boot script /boot.scr
326 bytes read in 2 ms (159.2 KiB/s)
## Executing script at 80000000
4200440 bytes read in 270 ms (14.8 MiB/s)
62852 bytes read in 7 ms (8.6 MiB/s)
Kernel image @ 0x82000000 [ 0x000000 - 0x4017f8 ]
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Device Tree to 8ffed000, end 8ffff583 ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.10.63 (dhewg@goaway) (arm-openwrt-linux-muslgnueabi-gcc (OpenWrt GCC 10.3.0 r17495+15-66db87fc78) 10.3.0, GNU ld (GNU Binutils) 2.36.1) #0 SMP Sat Sep 11 10:30:59 2021
[    0.000000] CPU: ARMv7 Processor [413fc082] revision 2 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: TI AM335x BeagleBone Black
[    0.000000] Memory policy: Data cache writeback
[    0.000000] cma: Reserved 16 MiB at 0x9ec00000
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000080000000-0x000000009fdfffff]
[    0.000000]   HighMem  empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080000000-0x000000009fdfffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080000000-0x000000009fdfffff]
[    0.000000] CPU: All CPU(s) started in SVC mode.
[    0.000000] AM335X ES2.1 (sgx neon)
[    0.000000] percpu: Embedded 15 pages/cpu s31884 r8192 d21364 u61440
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129412
[    0.000000] Kernel command line: console=ttyO0,115200n8 root=/dev/mmcblk1p2 rootwait
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 486168K/522240K available (9090K kernel code, 697K rwdata, 2456K rodata, 1024K init, 330K bss, 19688K reserved, 16384K cma-reserved, 0K highmem)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=1.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] IRQ: Found an INTC at 0x(ptrval) (revision 5.0) with 128 interrupts
[    0.000000] random: get_random_bytes called from start_kernel+0x370/0x540 with crng_init=0
[    0.000000] TI gptimer clocksource: always-on /ocp/interconnect@44c00000/segment@200000/target-module@31000
[    0.000011] sched_clock: 32 bits at 24MHz, resolution 41ns, wraps every 89478484971ns
[    0.000029] clocksource: dmtimer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.000361] TI gptimer clockevent: 24000000 Hz at /ocp/interconnect@48000000/segment@0/target-module@40000
[    0.001169] Calibrating delay loop... 996.14 BogoMIPS (lpj=4980736)
[    0.090446] pid_max: default: 32768 minimum: 301
[    0.090622] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.090639] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.091630] CPU: Testing write buffer coherency: ok
[    0.091710] CPU0: Spectre v2: using BPIALL workaround
[    0.092020] CPU0: thread -1, cpu 0, socket -1, mpidr 0
[    0.092772] Setting up static identity map for 0x80100000 - 0x80100060
[    0.092938] rcu: Hierarchical SRCU implementation.
[    0.093143] dyndbg: Ignore empty _ddebug table in a CONFIG_DYNAMIC_DEBUG_CORE build
[    0.093279] smp: Bringing up secondary CPUs ...
[    0.093293] smp: Brought up 1 node, 1 CPU
[    0.093304] SMP: Total of 1 processors activated (996.14 BogoMIPS).
[    0.093313] CPU: All CPU(s) started in SVC mode.
[    0.104582] VFP support v0.3: implementor 41 architecture 3 part 30 variant c rev 3
[    0.104820] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.104852] futex hash table entries: 256 (order: 2, 16384 bytes, linear)
[    0.105972] pinctrl core: initialized pinctrl subsystem
[    0.107609] NET: Registered protocol family 16
[    0.109656] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.128128] l3-aon-clkctrl:0000:0: failed to disable
[    0.129280] thermal_sys: Registered thermal governor 'fair_share'
[    0.129294] thermal_sys: Registered thermal governor 'step_wise'
[    0.129310] thermal_sys: Registered thermal governor 'user_space'
[    0.129547] cpuidle: using governor ladder
[    0.129566] cpuidle: using governor menu
[    1.149029] SCSI subsystem initialized
[    1.156043] usbcore: registered new interface driver usbfs
[    1.156111] usbcore: registered new interface driver hub
[    1.156194] usbcore: registered new device driver usb
[    1.156878] pps_core: LinuxPPS API ver. 1 registered
[    1.156896] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    1.156934] PTP clock support registered
[    1.157194] Advanced Linux Sound Architecture Driver Initialized.
[    1.164808] clocksource: Switched to clocksource dmtimer
[    1.165167] VFS: Disk quotas dquot_6.6.0
[    1.165250] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    1.166078] NET: Registered protocol family 2
[    1.166271] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    1.166956] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    1.166990] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    1.167036] TCP bind hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    1.167097] TCP: Hash tables configured (established 4096 bind 4096)
[    1.167207] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    1.167234] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    1.167413] NET: Registered protocol family 1
[    1.170338] RPC: Registered named UNIX socket transport module.
[    1.170366] RPC: Registered udp transport module.
[    1.170374] RPC: Registered tcp transport module.
[    1.170383] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    1.173594] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    1.178712] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    1.180537] NFS: Registering the id_resolver key type
[    1.180595] Key type id_resolver registered
[    1.180607] Key type id_legacy registered
[    1.180660] jffs2: version 2.2 (NAND) (SUMMARY) (LZO) (LZMA) (RTIME) (RUBIN) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    1.393175] gpiochip_add_data_with_key: GPIOs 0..31 (gpio-0-31) failed to register, -517
[    1.393215] omap_gpio 44e07000.gpio: Could not register gpio chip -517
[    1.591583] gpiochip_add_data_with_key: GPIOs 0..31 (gpio-0-31) failed to register, -517
[    1.591624] omap_gpio 4804c000.gpio: Could not register gpio chip -517
[    1.641181] gpiochip_add_data_with_key: GPIOs 0..31 (gpio-0-31) failed to register, -517
[    1.641222] omap_gpio 481ac000.gpio: Could not register gpio chip -517
[    1.651037] gpiochip_add_data_with_key: GPIOs 0..31 (gpio-0-31) failed to register, -517
[    1.651072] omap_gpio 481ae000.gpio: Could not register gpio chip -517
[    1.704110] debugfs: Directory '49000000.dma' with parent 'dmaengine' already present!
[    1.704160] edma 49000000.dma: TI EDMA DMA engine driver
[    1.723803] pinctrl-single 44e10800.pinmux: 142 pins, size 568
[    1.776409] Serial: 8250/16550 driver, 2 ports, IRQ sharing enabled
[    1.778255] omap_uart 44e09000.serial: no wakeirq for uart0
[    1.778376] 44e09000.serial: ttyO0 at MMIO 0x44e09000 (irq = 20, base_baud = 3000000) is a OMAP UART0
[    2.494927] printk: console [ttyO0] enabled
[    2.504687] random: fast init done
[    2.528371] brd: module loaded
[    2.538400] loop: module loaded
[    2.543739] mtdoops: mtd device (mtddev=name/number) must be supplied
[    2.553011] libphy: Fixed MDIO Bus: probed
[    2.614717] davinci_mdio 4a101000.mdio: davinci mdio revision 1.6, bus freq 1000000
[    2.622743] libphy: 4a101000.mdio: probed
[    2.629207] davinci_mdio 4a101000.mdio: phy[0]: device 4a101000.mdio:00, driver SMSC LAN8710/LAN8720
[    2.639195] cpsw 4a100000.ethernet: initialized cpsw ale version 1.4
[    2.645882] cpsw 4a100000.ethernet: ALE Table size 1024
[    2.652705] cpsw 4a100000.ethernet: cpts: overflow check period 500 (jiffies)
[    2.660312] cpsw 4a100000.ethernet: Detected MACID = d0:39:72:3b:d5:fc
[    2.670476] am335x-phy-driver 47401300.usb-phy: supply vcc not found, using dummy regulator
[    2.680291] am335x-phy-driver 47401b00.usb-phy: supply vcc not found, using dummy regulator
[    2.690122] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    2.697004] ehci-omap: OMAP-EHCI Host Controller driver
[    2.714382] musb-hdrc musb-hdrc.1: MUSB HDRC host driver
[    2.720168] musb-hdrc musb-hdrc.1: new USB bus registered, assigned bus number 1
[    2.729801] hub 1-0:1.0: USB hub found
[    2.734317] hub 1-0:1.0: 1 port detected
[    2.741247] omap_rtc 44e3e000.rtc: registered as rtc0
[    2.746719] omap_rtc 44e3e000.rtc: setting system clock to 2000-01-01T00:00:00 UTC (946684800)
[    2.756486] i2c /dev entries driver
[    2.761756] omap_wdt: OMAP Watchdog Timer Rev 0x01: initial timeout 60 sec
[    2.771184] sdhci: Secure Digital Host Controller Interface driver
[    2.777714] sdhci: Copyright(c) Pierre Ossman
[    2.782737] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.792693] sdhci-omap 481d8000.mmc: supply vqmmc not found, using dummy regulator
[    2.836909] ledtrig-cpu: registered to indicate activity on CPUs
[    2.844010] omap-aes 53500000.aes: OMAP AES hw accel rev: 3.2
[    2.850527] omap-aes 53500000.aes: will run requests pump with realtime priority
[    2.860552] omap-sham 53100000.sham: hw accel on OMAP rev 4.3
[    2.866726] mmc1: SDHCI controller on 481d8000.mmc [481d8000.mmc] using External DMA
[    2.877634] omap-sham 53100000.sham: will run requests pump with realtime priority
[    2.891915] davinci-mcasp 48038000.mcasp: IRQ common not found
[    2.908293] NET: Registered protocol family 10
[    2.917193] Segment Routing with IPv6
[    2.921135] NET: Registered protocol family 17
[    2.925952] NET: Registered protocol family 15
[    2.930692] 8021q: 802.1Q VLAN Support v1.8
[    2.935142] Key type dns_resolver registered
[    2.939692] ThumbEE CPU extension supported.
[    2.944151] Registering SWP/SWPB emulation handler
[    2.949174] omap_voltage_late_init: Voltage driver support not added
[    2.955823] sr_dev_init: No voltage domain specified for smartreflex0. Cannot initialize
[    2.964258] sr_dev_init: No voltage domain specified for smartreflex1. Cannot initialize
[    2.973080] SmartReflex Class3 initialized
[    2.997057] OMAP GPIO hardware version 0.1
[    3.035340] tps65217-pmic: Failed to locate of_node [id: -1]
[    3.048338] mmc1: new high speed MMC card at address 0001
[    3.056492] mmcblk1: mmc1:0001 MMC04G 3.60 GiB 
[    3.061946] mmcblk1boot0: mmc1:0001 MMC04G partition 1 2.00 MiB
[    3.069654] tps65217-bl: Failed to locate of_node [id: -1]
[    3.077031] mmcblk1boot1: mmc1:0001 MMC04G partition 2 2.00 MiB
[    3.083396] mmcblk1rpmb: mmc1:0001 MMC04G partition 3 128 KiB, chardev (247:0)
[    3.094811] tps65217 0-0024: TPS65217 ID 0xe version 1.2
[    3.101248] omap_i2c 44e0b000.i2c: bus 0 rev0.11 at 400 kHz
[    3.113123] omap_i2c 4819c000.i2c: bus 2 rev0.11 at 100 kHz
[    3.123882]  mmcblk1: p1 p2
[    3.145111] omap_gpio 44e07000.gpio: Could not set line 6 debounce to 200000 microseconds (-22)
[    3.154212] sdhci-omap 48060000.mmc: Got CD GPIO
[    3.159268] sdhci-omap 48060000.mmc: supply vqmmc not found, using dummy regulator
[    3.170773] ALSA device list:
[    3.173898]   No soundcards found.
[    3.233870] mmc0: SDHCI controller on 48060000.mmc [48060000.mmc] using External DMA
[    3.255484] VFS: Mounted root (squashfs filesystem) readonly on device 179:2.
[    3.265862] Freeing unused kernel memory: 1024K
[    3.275303] Run /sbin/init as init process
[    3.529970] init: Console is alive
[    3.535244] init: - watchdog -
[    3.658922] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    3.723907] ehci-fsl: Freescale EHCI Host controller driver
[    3.741973] ehci-platform: EHCI generic platform driver
[    3.761925] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    3.780984] ohci-platform: OHCI generic platform driver
[    3.796956] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    3.807270] init: - preinit -
[    4.522677] random: jshn: uninitialized urandom read (4 bytes read)
[    4.542926] random: jshn: uninitialized urandom read (4 bytes read)
[    4.642327] cpsw 4a100000.ethernet: initializing cpsw version 1.12 (0)
[    4.698980] random: procd: uninitialized urandom read (4 bytes read)
[    4.786516] SMSC LAN8710/LAN8720 4a101000.mdio:00: attached PHY driver [SMSC LAN8710/LAN8720] (mii_bus:phy_addr=4a101000.mdio:00, irq=POLL)
[    4.810742] 8021q: adding VLAN 0 to HW filter on device eth0
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[    6.885717] cpsw 4a100000.ethernet eth0: Link is Up - 100Mbps/Full - flow control off
[    6.894187] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    9.082613] mount_root: loading kmods from internal overlay
[    9.098716] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[    9.106717] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[    9.341505] block: attempting to load /etc/config/fstab
[    9.351130] block: unable to load configuration (fstab: Entry not found)
[    9.358880] block: no usable configuration
[    9.597565] F2FS-fs (loop0): Mounted with checkpoint version = 46ebfd38
[    9.676554] block: attempting to load /etc/config/fstab
[    9.682591] block: unable to load configuration (fstab: Entry not found)
[    9.689986] block: no usable configuration
[    9.696222] mount_root: switching to f2fs overlay
[    9.779808] urandom-seed: Seeding with /etc/urandom.seed
[    9.866487] cpsw 4a100000.ethernet eth0: Link is Down
[    9.879740] procd: - early -
[    9.882887] procd: - watchdog -
[   10.503222] procd: - watchdog -
[   10.516191] procd: - ubus -
[   10.599362] random: ubusd: uninitialized urandom read (4 bytes read)
[   10.608412] random: ubusd: uninitialized urandom read (4 bytes read)
[   10.617137] random: ubusd: uninitialized urandom read (4 bytes read)
[   10.628118] procd: - init -
Please press Enter to activate this console.
[   11.582384] kmodloader: loading kernel modules from /etc/modules.d/*
[   11.620021] tun: Universal TUN/TAP device driver, 1.6
[   11.772276] usbcore: registered new interface driver usbserial_generic
[   11.779332] usbserial: USB Serial support registered for generic
[   11.826891] urngd: v1.0.2 started.
[   11.896082] xt_time: kernel timezone is -0000
[   11.906605] usbcore: registered new interface driver ftdi_sio
[   11.912692] usbserial: USB Serial support registered for FTDI USB Serial Device
[   12.008960] usbcore: registered new interface driver pl2303
[   12.015037] usbserial: USB Serial support registered for pl2303
[   12.077097] kmodloader: done loading kernel modules from /etc/modules.d/*
[   12.111837] random: crng init done
[   12.115518] random: 4 urandom warning(s) missed due to ratelimiting
[   16.875292] cpsw 4a100000.ethernet: initializing cpsw version 1.12 (0)
[   16.976734] SMSC LAN8710/LAN8720 4a101000.mdio:00: attached PHY driver [SMSC LAN8710/LAN8720] (mii_bus:phy_addr=4a101000.mdio:00, irq=POLL)
[   17.013459] 8021q: adding VLAN 0 to HW filter on device eth0
[   19.126468] cpsw 4a100000.ethernet eth0: Link is Up - 100Mbps/Full - flow control off
[   19.134875] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
```

I guess beaglebone is still the only tested/used board for this platform, see also
https://github.com/openwrt/openwrt/pull/2852#issuecomment-620281604

### CODE REVIEW

**Comment by adschm** [comment]
I would not remove 5.4 config in the latest patch, but keep it around until we decide to remove 5.4 support widely.

**Comment by alexeys85** [comment]
Does GPIO work? I noticed some errors in your bootlog regarding it. On our custom board based on beaglebone it works fine with 5.4 without errors on boot.

**Comment by dhewg** [comment]
> I would not remove 5.4 config in the latest patch, but keep it around until we decide to remove 5.4 support widely.

Ok, done

> Does GPIO work? I noticed some errors in your bootlog regarding it.

I don't have anything attached and hence can't really test it, but -517 is EDEFERRED, which is normal

**Comment by dhewg** [comment]
rebased due to conflicts

**Comment by aparcar** [comment]
Any progress here? Do you need more testing or are things broken?

**Comment by dhewg** [comment]
Is there anything that need to be done?
AFAICT I resolved all suggested edits by Adrian.
There was a concern about errors in the log, but those are the just EDEFERRED errors, so harmless and somewhat normal.

**Comment by dhewg** [comment]
Actually, the last patch still deleted the 5.4 config. I thought I already fixed that, but apparently not... Fixed just now ;)

**Review by alexeys85 — APPROVED** [review]

**Comment by hauke** [comment]
Thank you for your patches, I applied them to master in ffb807ec90d3dc7f037f198ef828bb1c8d2ff7a6, 7f5c823da2b4906771bf3ea849aa27f8b12d02f5, d58eec88b5c6192c14187f2576dab6dda51f4f8f and 0aa1316218c4204b73f9df413478ee49dd2159bd.

**Pull request closed without merging**
