### PR TITLE
mvebu: use generic diag.sh

### PR DESCRIPTION
**Pull request by mans0n**
This commit removes the target-specific diag.sh script. This way, the
generic one is used for the target, which uses DT-aliases to specify the
LEDs used.

### CODE REVIEW

**Comment by mans0n** [comment]
Added 4.14 patch.

**Comment by mans0n** [comment]
I confirm that DT binding works well on mvebu, but I don't have the affected linksys devices. Any run-tests are welcome.

**Comment by dengqf6** [comment]
mvebu 4.14 support has been removed, please remove the 4.14 patch

**Comment by mans0n** [comment]
Thanks for letting me know. :)

**Comment by adrianschmutzler** [comment]
I'd be happy to merge this if you can organize a device-test. Maybe ask in the 5.4-support PR?

**Comment by Ansuel** [comment]
@adrianschmutzler I tested this on wrt3200acm on kernel 5.4 
All works as expected... (tested normal power up and upgrade)

**Comment by adrianschmutzler** [comment]
@Ansuel Would you provide a Tested-by ?

**Comment by Ansuel** [comment]
Tested-by: Ansuel Smith <ansuelsmth@gmail.com>

**Comment by adrianschmutzler** [comment]
Thanks, will be merged during the next hour.

**Pull request closed without merging**
