### PR TITLE
wolfssl: update to 5.1.1-stable

### PR DESCRIPTION
**Pull request by svlobanov**
Bump from 4.8.1-stable to 5.1.1-stable

Detailed release notes: https://github.com/wolfSSL/wolfssl/releases

Upstreamed patches:
001-Maths-x86-asm-change-asm-snippets-to-get-compiling.patch -
 https://github.com/wolfSSL/wolfssl/commit/fa8f23284d4689c2a737204b337b58d966dcbd8c
002-Update-macro-guard-on-SHA256-transform-call.patch -
 https://github.com/wolfSSL/wolfssl/commit/f447e4c1fa4c932c0286fa0331966756e243db81

Refreshed patches:
100-disable-hardening-check.patch
200-ecc-rng.patch

Signed-off-by: Sergey V. Lobanov <sergey@lobanov.in>

### CODE REVIEW

**Comment by svlobanov** [comment]
I will add one more commit to this PR related to ustream-ssl (bump ustream-ssl) after ustream-ssl patch is applied: http://lists.openwrt.org/pipermail/openwrt-devel/2022-January/037485.html

**Comment by dhewg** [comment]
Please switch from `-DWOLFSSL_ALT_CERT_CHAINS` to `--enable-altcertchains`, which was added for 5.0.0.

**Comment by svlobanov** [comment]
> Please switch from `-DWOLFSSL_ALT_CERT_CHAINS` to `--enable-altcertchains`, which was added for 5.0.0.

thank you, done

**Comment by zdz2019** [comment]
I think ustream-ssl may need to be upgraded. This is related to wolfssl.

**Comment by svlobanov** [comment]
> I think ustream-ssl may need to be upgraded. This is related to wolfssl.

Please check the first comment in this PR. I have already sent libustream-ssl patch to upstream. There is no reason to fix it as an openwrt patch because ustream-ssl is a part of openwrt project and maintained by @nbd168.

**Comment by svlobanov** [comment]
Related PR (libuhttpd): https://github.com/openwrt/packages/pull/17484

**Comment by svlobanov** [comment]
Related PR(rtty): https://github.com/openwrt/packages/pull/17486

**Comment by AuthorReflex** [comment]
> Please switch from `-DWOLFSSL_ALT_CERT_CHAINS` to `--enable-altcertchains`, which was added for 5.0.0.

`-DWOLFSSL_ALT_NAMES` can also be switched to  `--enable-ip-alt-name`

**Comment by svlobanov** [comment]
> > Please switch from `-DWOLFSSL_ALT_CERT_CHAINS` to `--enable-altcertchains`, which was added for 5.0.0.
> 
> `-DWOLFSSL_ALT_NAMES` can also be switched to `--enable-ip-alt-name`

It is not the same
configure flag --enable-ip-alt-name defines WOLFSSL_IP_ALT_NAME, not WOLFSSL_ALT_NAMES . it is different features

Currently (including wolfssl trunk) there is no configure flag to define WOLFSSL_ALT_NAMES

**Comment by svlobanov** [comment]
Fixes: https://bugs.openwrt.org/index.php?do=details&task_id=4188

**Comment by Alozxy** [comment]
> Fixes: https://bugs.openwrt.org/index.php?do=details&task_id=4188

Tested-by: Alozxy

**Review by cotequeiroz — APPROVED** [review]
I could not make 5.0.0 validate most certificates, but this works like a charm.  I've tested this on Linksys E8450/mediatek.

Acked-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

**Comment by svlobanov** [comment]
@cotequeiroz Unfortunately we can't merge this PR now because we have to update ustream-ssl (patch is here http://lists.openwrt.org/pipermail/openwrt-devel/2022-January/037485.html) (all other packages already updated)

I can add second commit to update ustream-ssl, but it is a part of OpenWrt repo so it will be strange to use patches for OpenWrt part. Looks like @nbd168 is busy so we have to decide what to do next - wait for accepting ustream-ssl patch or update ustream-ssl using OpenWrt patch

**Comment by cotequeiroz** [comment]
I don't expect this to be merged before the ustream-ssl change.

The ustream patch is rather trivial: the changed function is `static`, and its only caller is passing the return value of `SSL_get_error()`, from libwolfssl; there can't be anyone calling `handle_wolfssl_asn_error` with a value of `r=-159`, which would be required to trigger a different result.

I'll drop a note to the list about the security vulnerability.  It may help to expedite things.

**Comment by svlobanov** [comment]
Can someone ping nbd168 to merge ustream-ssl patch?

**Comment by svlobanov** [comment]
ustream-ssl patch has been applied, updated in OpenWrt package. Now we are able to merge this PR.

https://github.com/svlobanov/openwrt/commit/e74529552cf8fa16bd40b3db9d5cc82a913a49b4
https://git.openwrt.org/?p=project/ustream-ssl.git;a=commit;h=868fd8812f477c110f9c6c5252c0bd172167b94c

**Comment by svlobanov** [comment]
Added Tested-by and Acked-by to commit message

**Comment by svlobanov** [comment]
@mans0n  could you please remove 'work in progress' label? it is ready to be merged

**Comment by zokl** [comment]
libwolfssl 5.X solves the problem with wpa_supplicant and connection to WPA Enterprise networks. Please merge support as soon as possible. 

Thank you very much.


```
Tue Jan 25 14:47:20 2022 daemon.notice wpa_supplicant[9543]: wlan0: SME: Trying to authenticate with cc:16:7e:d2:cc:6c (SSID='eduroam' freq=5220 MHz)
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.463456] wlan0: authenticate with cc:16:7e:d2:cc:6c
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.477169] wlan0: send auth to cc:16:7e:d2:cc:6c (try 1/3)
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.483346] wlan0: authenticated
Tue Jan 25 14:47:20 2022 daemon.notice wpa_supplicant[9543]: wlan0: Trying to associate with cc:16:7e:d2:cc:6c (SSID='eduroam' freq=5220 MHz)
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.489897] wlan0: associate with cc:16:7e:d2:cc:6c (try 1/3)
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.497566] wlan0: RX AssocResp from cc:16:7e:d2:cc:6c (capab=0x1111 status=0 aid=2)
Tue Jan 25 14:47:20 2022 kern.warn kernel: [ 4748.506115] ath10k_pci 0000:04:00.0: pdev param 0 not supported by firmware
Tue Jan 25 14:47:20 2022 kern.warn kernel: [ 4748.513115] ath10k_pci 0000:04:00.0: failed to enable peer stats info: -95
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.520062] wlan0: associated
Tue Jan 25 14:47:20 2022 daemon.notice netifd: Network device 'wlan0' link is up
Tue Jan 25 14:47:20 2022 daemon.notice netifd: Interface 'WiFi' has link connectivity
Tue Jan 25 14:47:20 2022 daemon.notice wpa_supplicant[9543]: wlan0: Associated with cc:16:7e:d2:cc:6c
Tue Jan 25 14:47:20 2022 daemon.notice wpa_supplicant[9543]: wlan0: CTRL-EVENT-EAP-STARTED EAP authentication started
Tue Jan 25 14:47:20 2022 daemon.notice wpa_supplicant[9543]: wlan0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
Tue Jan 25 14:47:20 2022 kern.debug kernel: [ 4748.523164] wlan0: Limiting TX power to 17 dBm as advertised by cc:16:7e:d2:cc:6c
Tue Jan 25 14:47:20 2022 daemon.notice wpa_supplicant[9543]: wlan0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=25
Tue Jan 25 14:47:20 2022 daemon.notice wpa_supplicant[9543]: wlan0: CTRL-EVENT-EAP-METHOD EAP vendor 0 method 25 (PEAP) selected
Tue Jan 25 14:47:20 2022 daemon.notice wpa_supplicant[9543]: wlan0: CTRL-EVENT-EAP-PEER-CERT depth=1 subject='/C=NL/O=GEANT Vereniging/CN=GEANT OV RSA CA 4'
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.547775] traps: wpa_supplicant[9543] general protection fault ip:7f5043abb3b9 sp:7ffdc203a4a0 error:0 in libwolfssl.so.4.8.1.0748976a[7f5043a8b000+8d000]
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.598292] wlan0: deauthenticating from cc:16:7e:d2:cc:6c by local choice (Reason: 3=DEAUTH_LEAVING)
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.629918] ath10k_pci 0000:04:00.0: mac flush vdev 0 drop 1 queues 0x1 ar->paused: 0x0  arvif->paused: 0x0
Tue Jan 25 14:47:20 2022 kern.info kernel: [ 4748.639840] ath10k_pci 0000:04:00.0: mac flush vdev 0 drop 0 queues 0x1 ar->paused: 0x0  arvif->paused: 0x0
Tue Jan 25 14:47:20 2022 daemon.notice netifd: Network device 'wlan0' link is down
Tue Jan 25 14:47:20 2022 daemon.notice netifd: Interface 'WiFi' has link connectivity loss
```

**Comment by svlobanov** [comment]
Looks like @cotequeiroz has RW access to OpenWrt git. @cotequeiroz could you please merge this PR?

**Comment by zokl** [comment]
> Fixes: https://bugs.openwrt.org/index.php?do=details&task_id=4188

Tested-by: @zokl

**Comment by cotequeiroz** [comment]
I have no write access here.

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master in 93d91197b98463277b601ec2653351666a4ca4bd

**Comment by zokl** [comment]
> Thank you for the patch, I applied it to master in [93d9119](https://github.com/openwrt/openwrt/commit/93d91197b98463277b601ec2653351666a4ca4bd)

Hello, thank you for pushing it. Is it possible to push it into 21.02 too?

**Comment by svlobanov** [comment]
> Hello, thank you for pushing it. Is it possible to push it into 21.02 too?

It will be also required to backport to 21.02:
1. ustream-ssl https://github.com/openwrt/openwrt/commit/e74529552cf8fa16bd40b3db9d5cc82a913a49b4
2. libuhttpd (feeds/packages): openwrt/packages#17484
3. rtty (feeds/packages): openwrt/packages#17486

**Comment by hauke** [comment]
I backported the wolfssl update to openwrt 21.01 in 4108d02a29037cd733acfbd9a68f5dc4d58c3a56, 5ea2e1d5baa9cca7c300132dccc85ae0e2882eb7, 7d376e6e528f2d34e2f71f99f2f2f545a4dd63f2, 5b13b0b02c703a3c0c60828abfde01f283a2d821

**Comment by zokl** [comment]
Thank you!

**Pull request closed without merging**
