### PR TITLE
ath79: fix usb led on wr-1043nd-v1

### PR DESCRIPTION
**Pull request by lucize**
failed to test it before last commit
also remove leftover triggers

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by mkresin** [comment]
Please add a proper commit message. It is completely empty.

**Comment by lucize** [comment]
@mkresin better ?

**Comment by mkresin** [comment]
@lucize of course!

**Comment by mkresin** [comment]
merged thanks!

**Pull request closed without merging**
