### PR TITLE
mpc85xx: switch to kernel 4.19

### PR DESCRIPTION
**Pull request by CHKDSK88**
Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>

### CODE REVIEW

**Comment by ynezz** [comment]
Thanks for testing, but there's [currently plan](https://git.openwrt.org/?p=openwrt/staging/ynezz.git;a=commit;h=56a57f11c37843d672f185c21d95cc350db1c918) to switch all 4.19 ready targets to 4.19 once it passes basic build testing.

**Comment by ynezz** [comment]
Well, it seems like I need to adjust my plan slightly, because there are some concerns, that build testing is not good enough and we should actually run test this change.

So I'm not going bump all targets which passed the build test, but only those I've got either `Tested-by` or `Acked-by` (from other commiters) for, so I currently see two ways to move forward.

1. You could give me your `Tested-by` and device you've tested the 4.19 on and I'll bump mpc85xx with other targets in the common commit I've prepared in my staging tree
2. I'll reopen this PR and anyone who has access to the `mpc85xx` could then merge it.

**Comment by ynezz** [comment]
This is current state of that common 4.19 bump commit https://github.com/ynezz/openwrt/commit/c0e8e2eb97323cb000638667fe77c3445cc2ad6c

**Comment by CHKDSK88** [comment]
@ynezz 

You can add:
````Tested-by: Pawel Dembicki paweldembicki@gmail.com [mpc85xx/generic mpc85xx/p2020]````

I run tested with TL-WDR4900 and P2020RDB.

**Comment by adrianschmutzler** [comment]
@CHKDSK88 So this means, the TL-WDR4900 already runs with 4.19 without any further adjustment?

Because I thought that the solution from https://github.com/openwrt/openwrt/pull/1773 was expected to break on 4.19?

**Comment by CHKDSK88** [comment]
@adrianschmutzler

This commit fix kernel size problem in both kernels:
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=1e41de2f48e284c9d6658f9403365651178f6826

**Comment by adrianschmutzler** [comment]
Yes, but I recall that during early stage of the PR, two different approaches were discussed:
1. Temporary fix for 4.14/openwrt-19.07
2. A two-step bootloader which permanently fixes the kernel size limitation

So is the commit refered by @CHKDSK88 already a "permanent" fix (i.e. option 2)?

**Comment by CHKDSK88** [comment]
Yes. We use special powerpc boot wrapper and change compresion metod. That method shrink the kernel. It is permanent fix.

**Pull request closed without merging**
