### PR TITLE
meson: add target for Amlogic Meson s805 xSoC-s

### PR DESCRIPTION
**Pull request by shiyu1314**
Add a new target named "meson" that provides support for
Amlogic Meson s805x SoC-s

SoC: Cortex-A53 1.5 GHz
RAM: 1 GB RAM
Flash: 8 GB eMMC
LAN: 1x RTL8211F Gigabit Ethernet/at support
LEDs: 1x blue
USB：Two USB 2.0
Buttons: 1x reset button

Due to the lack of this device on the branch line, the u-boot can only be modified by myself

u-boot:
https://github.com/shiyu1314/u-boot-onecloud/releases

### CODE REVIEW

**Comment by Ansuel** [comment]
image
Still not following why... Commit can also be squashed but again JUST ASK if you have some problem in how to do one or 2 thing, don't close and reopen the same pr...

**Comment by shiyu1314** [comment]
> image
> Still not following why... Commit can also be squashed but again JUST ASK if you have some problem in how to do one or 2 thing, don't close and reopen the same pr...

Sorry, it’s my first time submitting on github as a newbie

**Comment by shiyu1314** [comment]
I'm sorry for causing you some annoyance.  I will pay attention

**Comment by Ansuel** [comment]
@shiyu1314 no problem... just don't open any new pr... if in doubt ask here

**Comment by shiyu1314** [comment]
> @shiyu1314 no problem... just don't open any new pr... if in doubt ask here

ok

**Comment by shiyu1314** [comment]
Can be merged

**Comment by DragonBluep** [comment]
> Can be merged

Adding a new target requires more time to be accepted. And I'm wondering if it can be merged into the `armsr` target. By the way, there is already a PR trying to add `meson` target. https://github.com/openwrt/openwrt/pull/10331

**Comment by shiyu1314** [comment]
> > Can be merged
> 
> Adding a new target requires more time to be accepted. And I'm wondering if it can be merged into the `armsr` target. By the way, there is already a PR trying to add `meson` target. https://github.com/openwrt/openwrt/pull/10331

That uboot is too old and I don’t think it’s suitable.

**Comment by shiyu1314** [comment]
> > Can be merged
> 
> Adding a new target requires more time to be accepted. And I'm wondering if it can be merged into the `armsr` target. By the way, there is already a PR trying to add `meson` target. https://github.com/openwrt/openwrt/pull/10331

And does not recognize emmc

**Comment by shiyu1314** [comment]
QQ20230925-080245
https://github.com/shiyu1314/openwrt-onecloud

**Comment by shiyu1314** [comment]
Although I use immortalwrt, it's all the same

**Comment by predators46** [comment]
@shiyu1314 

can you add s905x i want to try it

**Comment by shiyu1314** [comment]
> @shiyu1314
> 
> can you add s905x i want to try it

I don't have this device, I find it difficult to try

**Comment by shiyu1314** [comment]
> > Can be merged
> 
> Adding a new target requires more time to be accepted. And I'm wondering if it can be merged into the `armsr` target. By the way, there is already a PR trying to add `meson` target. #10331

This can be merged and has been tested several times

**Comment by predators46** [comment]
> > @shiyu1314
> > can you add s905x i want to try it
> 
> I don't have this device, I find it difficult to try

I'm confused about adding the amlogic s905x meson-gxl-s905x-p212 target. I'm currently using Armbian on my TV box

**Comment by motolav** [comment]
@shiyu1314 I told you before that it should be titled as a new target not as support for a new device

**Comment by shiyu1314** [comment]
> @shiyu1314 I told you before that it should be titled as a new target not as support for a new device
> 
> > You're adding a new target so your title should be something like
> > `meson: add target for Amlogic Meson SOCs`
> > and maybe use a separate commit for adding support for the device Thunder OneCloud
> > `meson: add support for Thunder OneCloud`

oh!  I forgot you said

> @shiyu1314 I told you before that it should be titled as a new target not as support for a new device
> 
> > You're adding a new target so your title should be something like
> > `meson: add target for Amlogic Meson SOCs`
> > and maybe use a separate commit for adding support for the device Thunder OneCloud
> > `meson: add support for Thunder OneCloud`

oh!  I forgot you said

**Comment by shiyu1314** [comment]
> @shiyu1314 I told you before that it should be titled as a new target not as support for a new device
> 
> > You're adding a new target so your title should be something like
> > `meson: add target for Amlogic Meson SOCs`
> > and maybe use a separate commit for adding support for the device Thunder OneCloud
> > `meson: add support for Thunder OneCloud`

oh! I forgot you said

**Comment by shiyu1314** [comment]
would anyone help to merge the request please?

**Comment by motolav** [comment]
You didn't fix your commit to what I suggested, you just changed the title of the PR

**Pull request closed without merging**
