### PR TITLE
ramips: add support for Comfast cf-wr752ac-v2

### PR DESCRIPTION
**Pull request by rhamp**
important: this is for v2, not for v1 that is ath79 based.

- Mediatek (Ramips) MT7628 + MT7612
- CPU Clock: 580MHz
- dual band, antenna 2*3dBi
- Output power 50mW (17dBm)
- 1x 10/100 Mbps LAN RJ45
- 64 MB DDR2 / 8 MB NAND FLASH (en25qh64)
- 3 LEDs (red/green/blue)
  incorporated in
  "color wheel reset switch"
- UART 57600 8N1 (because of u-boot preset)

Flashing instructions:

 The U-boot bootloader contains a recovery HTTP server
 to upload the  firmware. Push the reset button while powering the
 device on and keep it pressed for ~10 seconds. The device's LEDs will
 blink several times and the recovery page will be at
 http://192.168.1.1; use it to upload the sysupgrade image.

 Alternatively, the original firmware is based on OpenWrt so a
 sysupgrade image can be installed via the stock web GUI. Settings from
 the original firmware will be saved and restored on the new one, so a
 factory reset will be needed. To do so, once the new firmware is flashed,
 enter into failsafe mode by pressing the reset button several times during
 the boot process, until it starts flashing. Once in failsafe mode, perform
 a factory reset as usual.

Info:
All LEDs are working, blue is set to LAN, green to wlan2g and red to wlan5g,
the vendor MACs are extracted from firmware/eeprom partition.
sample mac ending (as in 2020 Comfast firmware):
eth0 x:8a
wlan2g: x:8c
wlan5g: x:8d

Signed-off-by: Roman Hampel <rhamp@arcor.de>

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Hi, please clean up this mess first.

**Comment by adrianschmutzler** [comment]
> important: this is for v2, not for v1 that is ath79 based.

Remove this from commit message (same for v1).

If you properly name you devices, this comment won't be required.

**Comment by adrianschmutzler** [comment]
To make this clear: I do not have a problem with you submitting the ramips PR already, it's reviewed independently anyway. But please provide it in a proper shape, as a single commit and without fragments from ath79 v1 support.

**Comment by rhamp** [comment]
Yes, thank you. As you can see, I am new to github comitting, and I do not have internalized the github logic so far.

**Comment by liangleslie** [comment]
Saw that this is marked closed -- are there still plans to merge this into main?

I own the device and have just tried compiling the sysupgrade image. Need to make some minor tweaks to gpio naming in the dts to be consistent with the current convention for 76x8, but other than that this seems to work when flashed via uboot method described by @rhamp

**Comment by rhamp** [comment]
Currently not.  Indeed the gpio setup changed as you found out by yourself. There are a few things to be changed to merge (mac address  extraction/calculation,  LED assignment etc. ) to comply with openwrt rules, but since it works well as it is, I refrained from it.

**Pull request closed without merging**
