### PR TITLE
sunxi: A20 olimex fixes

### PR DESCRIPTION
**Pull request by lucize**
greatly improve network speed and fix an existing bug with soft reset
reboot command will hang in u-boot with

```
U-Boot SPL 2018.05 (Oct 07 2018 - 20:16:10 +0000)
DR
```
this also needs to be applied on 18.06.x

### CODE REVIEW

**Comment by hauke** [comment]
is this already included in upstream U-Boot or was it posted on the upstream U-Boot mailing list?

**Comment by lucize** [comment]
I tried the latest uboot, and it wasn't there. The patches are on armbian repo, and when the board boots fine, I get 900+mb/s vs 230 mb/s

**Comment by lucize** [comment]
@hauke any news ?

**Comment by wigyori** [comment]
Is the soft-reset issue related to this one?
http://git.denx.de/?p=u-boot.git;a=commit;h=8311e84b18627d836b4f90df268bb6890c2576eb

As for the Micrel patch, that seems to be a must for the rev. K Lime2 boards (above rev. G, see below), so it's not just about network speed.

https://github.com/OLIMEX/OLINUXINO/blob/master/HARDWARE/A20-OLinuXino-LIME2/hardware_revision_changes_log.txt

#### Hardware revision H (internal, not released)
=============================
[...]
2. Changed the PHY for the Micrel one;
[...]

(I don't have either of the Lime2 boards, so I'll have to relent to people who have.)

Regards,
-w-

**Comment by wigyori** [comment]
Also, in the "improve network speed" patch, You enable the Micrel PHY for the Lime2_EMMC, but only enable the GMAC_TX_DELAY for the Lime2 - aren't they the same boards, one with MMC, the other without, and keeping the same revision numbering?

Regards,
-w-

**Comment by lucize** [comment]
> Is the soft-reset issue related to this one?

@wigyori yes, that one seems to solve the problem

for eMMC I just overlooked it, I'll adjust with the new one and add for eMMC also

**Comment by lucize** [comment]
I think that tx_delay is not needed anymore because of this code ?

```
+	} else if(phydev->drv->uid == 0x1cc915) {
+		/* RTL8211E has different GMAC_TX_DELAY requirements */
+		setbits_le32(&ccm->gmac_clk_cfg, CCM_GMAC_CTRL_TX_CLK_DELAY(2));
+	}
```

**Pull request closed without merging**
