### PR TITLE
ramips: add support to Beeline SmartBox GIGA

### PR DESCRIPTION
**Pull request by csharper2005**
This PR was mistakenly closed while trying to squash the commits.
New - https://github.com/openwrt/openwrt/pull/4195

### CODE REVIEW

**Comment by csharper2005** [comment]
Bump! Also this commit is compatible with 21.02.

**Review by legale — APPROVED** [review]
It works good.

**Review by MaxS0niX — CHANGES_REQUESTED** [review]
It works. Tested on my Beeline SmartBox GIGA.

**Review by csharper2005 — COMMENTED** [review]
Nothing to change here. Check it, please.

**Review by MaxS0niX — APPROVED** [review]

**Review by europe1453 — APPROVED** [review]

**Pull request closed without merging**
