### PR TITLE
busybox: update to 1.36.1

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Release Notes:
http://lists.busybox.net/pipermail/busybox-cvs/2023-May/041510.html

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
ping @hnyman

**Comment by hnyman** [comment]
Looks like none of the commits in the 1.36 branch wince 1.36.0 change busybox config options, so at the first glance your simple PR looks ok.

I will compile test it and check the logs a bit.

**Comment by hnyman** [comment]
Compiled ok, and seems to run ok, too.

LGTM ;-)

**Comment by hnyman** [comment]
sure.

Tested-by: Hannu Nyman <hannu.nyman@iki.fi>

**Comment by PolynomialDivision** [comment]
Thanks!

**Pull request merged**
