### PR TITLE
kernel: bump 5.15 to 5.15.74

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by Borromini** [comment]
Compile-tested: mvebu/cortexa72
Run-tested: mvebu/cortexa72 (RB5009UG+S+IN)

**Review by BKPepe — APPROVED** [review]
Compile tested: mvebu/cortex-a9 (Turris Omnia), mvebu/cortex-a53 (Turris MOX), mpc85xx/p2020 (Turris 1.1)
Run tested: same as above

Thanks!

**Comment by BKPepe** [comment]
While looking at changelog for [5.15.74](https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.74) version, you should mention that this is security update or include those CVEs fixes in the commit description.

**Comment by graysky2** [comment]
@BKPepe - how about my edit?

**Comment by BKPepe** [comment]
Much better, thank you so much!

**Comment by Borromini** [comment]
For 5.15.74:

Compile-tested: mvebu/cortexa72
Run-tested: mvebu/cortexa72 (RB5009UG+S+IN)

**Pull request closed without merging**
