### PR TITLE
ipq806x: usb30 block malfunction investigation

### PR DESCRIPTION
**Pull request by Lanchon**
** THIS PULL IS NOT MEANT TO BE MERGED **

@mans0n @dangowrt 

this is a space to study the issues around the ipq8065 usb30 blocks.

the current state as i open this PR is:
- USB works, with with workarounds:
  1. both blocks must be enabled, even though only one is used in the board.
  2. an additional swapped, clock is added to each block (as seen elsewhere; but this might not be necessary).

i will commit changes from here and document the result of testing each change in the commit message.

EDIT: relevant changes start on the 3rd commit; the first 2 are porting OpenWrt to a new device.

the current state of affairs:
```
[USB30_MASTER_SRC] = &usb30_master_clk_src.clkr : 0x3b28 (8)
.ns_reg = 0x3b2c,
.md_reg = 0x3b28,

[USB30_0_MASTER_CLK] = &usb30_0_branch_clk.clkr : 0x3b24 (4)
.halt_reg = 0x2fc4,
.halt_bit = 22,
.clkr.enable_reg = 0x3b24,

[USB30_1_MASTER_CLK] = &usb30_1_branch_clk.clkr : 0x3b34 (4)
.halt_reg = 0x2fc4,
.halt_bit = 17,
.clkr.enable_reg = 0x3b34,


[USB30_UTMI_SRC] = &usb30_utmi_clk.clkr : 0x3b40 (8)
.ns_reg = 0x3b44,
.md_reg = 0x3b40,

[USB30_0_UTMI_CLK] = &usb30_0_utmi_clk_ctl.clkr : 0x3b48 (4)
.halt_reg = 0x2fc4,
.halt_bit = 21,
.clkr.enable_reg = 0x3b48,

[USB30_1_UTMI_CLK] = &usb30_1_utmi_clk_ctl.clkr : 0x3b4c (4)
.halt_reg = 0x2fc4,
.halt_bit = 15,
.clkr.enable_reg = 0x3b4c,


[SFAB_USB30_*_RESET] = { 0x3b54, * },

[USB30_0_*_RESET] = { 0x3b50, * },

[USB30_1_*_RESET] = { 0x3b58, * },
```

### CODE REVIEW

**Comment by Lanchon** [comment]
@mans0n @dangowrt

so the clocks are swapped, no doubt. the status of other regs/bits (resets, halt bits, etc) is unknown.
without knowing about these other details, i can't recommend a fix at this time.

i think the TR 4400 v2 PR should be merged as is.
if/when this usb issue is fixed, i guess several devices will need updating.

thanks!

**Comment by Lanchon** [comment]
so i rolled back everything to initial state to propose a better workaround; see last commit.

**Comment by Lanchon** [comment]
5.10 dtsi patch comes from 5.4:
https://github.com/openwrt/openwrt/blame/master/target/linux/ipq806x/patches-5.10/083-ipq8064-dtsi-additions.patch

5.4 comes from upstream:
https://github.com/openwrt/openwrt/commit/b7b7c2a6adf96ff8186509fc1bef550c82d5fc26#diff-03a6c4bfcce73100fd9af4b3e8de0bf6e21f8802dd0dcce92da3044b1ccfb759R720-R802

interestingly, the 5.15 dtsi patch no longer adds the USB entries:
https://github.com/openwrt/openwrt/blob/master/target/linux/ipq806x/patches-5.15/083-ipq8064-dtsi-additions.patch

the removal:
https://github.com/openwrt/openwrt/commit/8cc2caed58e79ac24f9f5a075c6a12b07453c923#diff-5ede7b7d6dd7d75f601ee0ee6f32e65b03e9c91e7ba2780e7504b4dbe37ba451L682-L763

so maybe switching to 5.15 will fix this... breaking workarounds all over the place !

**Comment by robimarko** [comment]
Adding @Ansuel, he is the resident IPQ806x expert.

**Comment by Lanchon** [comment]
hi @Ansuel
if you want me to, i can test whether this issue is still present on 5.15. you just need to give me a pointer on how to switch kernels.

**Comment by Lanchon** [comment]
@Ansuel
> can't we just flag them as ignore unused?

i was happy to leave both blocks enabled, but it was flagged as an issue when i wanted to merge a port.

> If the problem is that both clk requires to be enabled...

no, it is not: i can disable one USB block with its set of clocks and the other USB block works just fine. the problem is that dtsi files want to disable the wrong set of clocks! (for my hardware)

please take a look at each commit (starting with 3rd) and its commit message.

btw, i'm sure you can repro in your r7800.

@mans0n 
> I guess switching to 5.15 won't really help...

probably, but worth a try anyway. i'll report

**Comment by Lanchon** [comment]
FYI 5.15 can't boot from squashfs:
https://gist.githubusercontent.com/Lanchon/a48e1e0cb1ed0b7111cb3c164a08dca2/raw/b18a27bfe37d7fdf413c8ed3e2f4cd931c669601/arris-tr4400-v2%2520k5.15%2520squashfs%2520bootlog

**Comment by Lanchon** [comment]
@mans0n @Ansuel 

K5.15 fixes the issue!!

it was not the clocks that were swapped, it was the usb blocks themselves.
see the address for both usb3_0 and dwc3_0 change from 0x110... to 0x100...:

- new: https://github.com/torvalds/linux/blob/3e732ebf7316ac83e8562db7e64cc68aec390a18/arch/arm/boot/dts/qcom-ipq8064.dtsi#L1082-L1097
- old: https://github.com/openwrt/openwrt/blob/f6d566301ee3dc12fd41e131f89dfc4777b002f3/target/linux/ipq806x/patches-5.10/083-ipq8064-dtsi-additions.patch#L698-L713

which means that the only workarounds that will survive a switch to kernel 5.15 without change are:
- enable both USB blocks
- enable only usb3_0/dwc3_0 but changing their address

**Comment by Lanchon** [comment]
so here is the final workaround, fully tested:
https://github.com/openwrt/openwrt/blob/76e7213547751907e91dbf78456fb45a81f69901/target/linux/ipq806x/files/arch/arm/boot/dts/qcom-ipq8065-tr4400-v2.dts#L347-L358
it backports the dtsi changes from the 5.15 mainline.

**Comment by mans0n** [comment]
Hmm, why don't we just backport the USB node changes as a patch in `target/linux/ipq806x/patches-5.10`?

**Comment by Lanchon** [comment]
> Hmm, why don't we just backport the dtsi change as a patch in `target/linux/ipq806x/patches-5.10`?

because it will rename usb3_0 into usb3_1 and viceversa, and i don't know the ramifications that would have in other ports.

if other ports don't do workarounds, then both blocks must be enabled and that change will not break them. however, the change is still visible from userland.

granted, changing to mainline 5.15 will do the same thing (but we could do things differently there... we could avoid that with more patching). but i just want to merge this port; getting in that rabbit hole could be neverending.

instead, here i propose a solution that will keep working after upgrading to 5.15 or backporting to 5.10, with no visible changes from userland.

**Comment by mans0n** [comment]
`git grep "usb3_" target/linux/ipq806x` shows that all ipq806x devices with usb port enable both `&usb3_0` and `&usb3_1` nodes, so I think it's safe to swap the usb nodes in dtsi. Anyway, it is what will happen after the switch to 5.15...

It would be the best if you submit the patch yourself, but if you don't like to touch it then I am willing to do the job. But I don't have a device for test at the moment so you might end up testing it...

**Comment by Lanchon** [comment]
@mans0n

> It would be the best if you submit the patch yourself

sure i can do that, and test with my device (nothing else). (it will have to wait for a few hours.)

> all ipq806x devices with usb port enable both &usb3_0 and &usb3_1 nodes, so I think it's safe to swap the usb nodes in dtsi.

(we also need to check for non-existence of clocks/regs workarounds, as one can imagine workarounds that break with the dtsi change. i'll assume you had done that already (or will do it) unless you tell me.)

i worried about breaking existing setups: people with their software running talking to some usb device of theirs on a specific port. but you are right, 5.15 is going to break their setup later anyway.

ok. ill do the change, thanks!

**Comment by Lanchon** [comment]
fixed by https://github.com/openwrt/openwrt/pull/9692

**Pull request closed without merging**
