### PR TITLE
tools/cmake: Update to 3.15.1

### PR DESCRIPTION
**Pull request by diizzyy**
Update CMake to 3.15.1
Refresh patches
Remove inofficial fossies.org and replace with GitHub (link on official site)
Remove 150-C-feature-checks-Match-warnings-more-strictly.patch as it's
a no longer needed backport from upstream.
Disable ccache if GCC is 4.8, 4.9 or 5.X to avoid build failures.
Reference: https://github.com/openwrt/openwrt/pull/1929

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master
Run tested: mvebu, Linksys WRT3200ACM, OpenWrt master

**Comment by diizzyy** [comment]
Compile tested: ipq40xx, Linksys EA6350v3, OpenWrt master
Run tested: ipq40xx, Linksys EA6350v3, OpenWrt master

**Comment by diizzyy** [comment]
Update to 3.15.1

Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master + ipq40xx, Linksys EA6350v3, OpenWrt master
Run tested: mvebu, Linksys WRT3200ACM, OpenWrt master + ipq40xx, Linksys EA6350v3, OpenWrt master

**Comment by EXSERENS** [comment]
Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master
Run tested: mvebu, Linksys WRT3200ACM, OpenWrt master

**Comment by hauke** [comment]
Thank you, your patch was applied to master.

**Pull request closed without merging**
