### PR TITLE
config: drop obsolete/redundant settings and fix build warnings

### PR DESCRIPTION
**Pull request by guidosarducci**
**Review/Distribution List**:  @dangowrt, @yousong  (based on similar fixes and commits in the repo)
**Compile tested**:  mips32-be-malta and mips64-le-malta, master branch
**Run tested**:  mips32-be-malta and mips64-le-malta, master branch

**Description**:
This makes for more consistent treatment of 32-bit/64-bit target configs and makefiles.

Comment out some conflicting target configs that are already set from
subtarget configs, which can lead to kernel compile warnings:

```
scripts/kconfig/conf  --syncconfig Kconfig
net/sched/Kconfig:45: warning: menuconfig statement without prompt
.config:1038:warning: override: CPU_MIPS32_R2 changes choice state
```

Similarly, migrate the 32-bit make definition from the target-level makefile to relevant subtarget makefiles, as is already done with the 64-bit definitions.

Thanks for your review and feedback!

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
This overlaps with https://patchwork.ozlabs.org/project/openwrt/patch/20200809161214.8271-1-hauke@hauke-m.de/

**Comment by adrianschmutzler** [comment]
And this one as well: https://patchwork.ozlabs.org/project/openwrt/patch/20200809161329.8392-1-hauke@hauke-m.de/

**Comment by guidosarducci** [comment]
> This overlaps with https://patchwork.ozlabs.org/project/openwrt/patch/20200809161214.8271-1-hauke@hauke-m.de/
> 
@hauke Aside from 1 line in common, my patch has some additional config options that should be commented/removed. If you could incorporate them into your patch then I shall close this one.

**Comment by hauke** [comment]
I refreshed the configuration with:
```
make kernel_oldconfig CONFIG_TARGET=subtarget
```
and
```
make kernel_oldconfig CONFIG_TARGET=target
```
This refresh the kernel configuration of the currently selected target or subtarget configuration. 

The target/linux/generic/config is done manually, you can just sort it automtaically with:
```
./scripts/kconfig.pl '+' target/linux/generic/config-4.19 /dev/null > target/linux/generic/config-4.19-new
mv target/linux/generic/config-4.19-new target/linux/generic/config-4.19
```

**Comment by guidosarducci** [comment]
That's what I suspected you were doing. The problem I've seen with `make kernel_*config` is that it sets *everything*, necessary or not, which makes managing our out-of-tree kernel config fragments more difficult. Ideally, we would have the kernel equivalent of OpenWRT's `./scripts/diffconfig.sh` that keeps only the relevant, non-default, non-automatic bits.

I wonder if `kconfig.pl` does/could do that, but I've never found any help or documentation for it. Do you have any references? Also, will you update your patch regarding the unnecessary additions?

**Comment by guidosarducci** [comment]
> Also add missing CONFIG_IONIC option to avoid prompt during kernel 5.4 build.
>
Dropped the above fix as being recently applied upstream, however all other changes are still applicable. Also added a similar commit to correctly position the "CPU_TYPE:=24kc" setting at the sub-target level.

**Comment by adschm** [comment]
Picked the second patch.

**Comment by ynezz** [comment]
Please rebase.

**Comment by guidosarducci** [comment]
@ynezz Hi Petr, thanks for the ping earlier -- I'm still slowly catching up on things... I rebased the one remaining commit as requested, and also added two more config-related commits I've been carrying for a few months; the latter are straightforward cleanups. Please have a look.

I'll update the PR title too...

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Pull request closed without merging**
