### PR TITLE
kernel: bump 4.4 to 4.4.39

### PR DESCRIPTION
**Pull request by wigyori**
Compile-tested on nearly all 4.4 targets.
Runtime-tested on ar71xx, mvebu.

Patches and target configs were refreshed or extended where
required.

Signed-off-by: Zoltan HERPAI <wigyori@uid0.hu>

### CODE REVIEW

**Review by seragh — COMMENTED** [review]
Just skimming,

as far as I can tell generic/051 are the remnants of back porting a fix that caused a regression, was fixed differently and back ported to 4.4 upstream. They better be dropped.

You drop ledtrig-morse, I also don't like it to be patched in but it could be packaged standalone like any other out of tree module. Eitherway should be a separate commit as it's not related to the bump.

ledtrig-usbdev is used in many boards base configuration and the ledtrig-usbport from Linux 4.9 lacks activity indication, so some might even prefer usbdev over usbport. Anyway needs change in other places as well and can't be considered related to the bump either.

**Comment by seragh** [comment]
@wigyori 

I can prepare similar patches for usbdev and netdev in case you intend to merge #307

**Comment by wigyori** [comment]
@seragh , I should have added an [RFC] as a prefix to the pullreq, as this is mainly a carbon-copy of what LEDE has, and I did not go through the full dependency tree yet. If You could add the required packages for the ledtrig kmods, and maybe add them into the target profiles, that'd be much appreciated. Thanks for checking.

**Comment by seragh** [comment]
@wigyori 

I opened #310 for what I have in mind wrt triggers. It's orthogonal to a kernel bump except for merge conflicts. So the question is if you agree overall how much you intend to review an merge before a bump and how much after? I'd prefer not to redo everything if it can be avoided.

Btw, 4.4.40 is out.

**Comment by wigyori** [comment]
@seragh 
 - OK for splitting out ledtrig-morse. TBH I don't know if anything uses it still, but we can keep the package around.
 - OK for ledtrig-usbdev and letrig-netdev split-out, too. Device profiles may choose between ledtrig-usbdev and ledtrig-usbport, whichever maintainers want.
(One thing to consider here is, the code merge with the LEDE codebase. As the "next step" is to merge the  OpenWrt patches into LEDE (the ones that are not there), whatever we do here, either for kmod rework or target/device updates, needs to be accepted over there.)
 - For the kernel version, sure, I've built a 4.4.40 already and will bump the PR to that version.

Thanks,
-w-

**Comment by wigyori** [comment]
... and now 4.4.41

**Comment by Pietia10** [comment]
4.4.70 ?;-O

**Comment by wigyori** [comment]
I guess this is obsolete for quite some time. :P

**Pull request closed without merging**
