### PR TITLE
kernel: bump 5.10 to 5.10.46

### PR DESCRIPTION
**Pull request by rsalvaterra**
Add the new symbol to the generic kconfig.

No deleted or manually refreshed patches.

Run-tested:
mvebu/cortexa9 (Turris Omnia)
ath79/generic (TL-WDR3600)

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by anomeome** [comment]
compile / test : mvebu / mamba, rango

A note on the .45 push. I built that on top of this PR and experienced breakage, both devices failed to pick up a dynamic IP from my ISP, the mamba was random on getting an IP on reboot, the rango never got an IP. dmesg on the rango showed no change from a working .44 image (except today's PCI commit). Just in case you move forward and experience same on targets you are testing. I will try again should you update PR.

**Comment by rsalvaterra** [comment]
Hi, Kabuli,

compile / test : mvebu / mamba, rango
>
> A note on the .45 push. I built that on top of this PR and experienced
> breakage, both devices failed to pick up a dynamic IP from my ISP, the
> mamba was random on getting an IP on reboot, the rango never got an IP.
> dmesg on the rango showed no change from a working .44 image (except
> today's PCI commit). Just in case you move forward and experience same on
> targets you are testing. I will try again should you update PR.
>

Very odd. I'll give it a spin on my Omnia ASAP (probably tomorrow),  maybe
it's an MVEBU specific issue.
Thanks for the heads-up!

Rui

>

**Comment by rockdrilla** [comment]
Compile/run-tested 5.10.45 on ath79/generic (Archer C7 v2).

**Comment by anomeome** [comment]
Did a hard reset on my tree, reapplied patches that I carry, did a `rm -rf bin tmp build_dir`, rebuilt. With this image I have not yet had the mamba fail, but the rango never succeeds. I assume if this was an issue upstream there would already be another push, so either something in the OpenWrt tree, me, or quarks. Omnia result will be of interest.

**Comment by rsalvaterra** [comment]
I have no issues whatsoever on my Omnia. Just tested.

**Comment by anomeome** [comment]
compile / test : mvebu / mamba, rango

So something about this .45 kernel push has changed regarding behaviour around /etc/config/network DSA config.I had a relatively simple bridge-vlan which I have removed in favour of the basic OOTB default which WFM. I will try to find what part of my previous config was stopping IP setup.

**Comment by anomeome** [comment]
A simple setup as per:

```
config device
	option name 'switch0'
	option type 'bridge'
	list ports 'lan1'
	list ports 'lan2'
	list ports 'lan3'
	list ports 'lan4'

config bridge-vlan
	option device 'switch0'
	option vlan '1'
	list ports 'lan4'
	list ports 'lan3'
	list ports 'lan2'
	list ports 'lan1'
	option alias 'lan'

config interface 'lan'
	option device 'switch0.lan'
	option proto 'static'
	option ipaddr '192.168.120.1'
	option netmask '255.255.255.0'
	option ip6assign '60'
```

unless I have things horribly wrong, breaks things as stated above. So .45 seems to break netifd setup. ping @nbd168

**Comment by rsalvaterra** [comment]
@anomeome, I assume that's your rango setup? I can't really comment, on the VLAN configuration, since I'm not using VLANs. This is what I have on the Omnia (yes, only one enslaved port on the bridge, at the moment):

```
config device
	option ipv6 '0'
	option name 'lan'
	option type 'bridge'
	list ports 'lan4'

config interface 'lan'
	option device 'lan'
	option ipv6 '0'
	option proto 'static'
	list ipaddr '192.168.16.1/24'

config interface 'wan'
	option device 'eth2'
	option ipv6 '0'
	option peerdns '0'
	option proto 'dhcp'
```

**Comment by anomeome** [comment]
I built a .44 and .45 image of _r16997-6561ca1fa5_ pull from today. Used the above simplified VLAN setup on both a mamba and rango, both worked on .44, both failed on .45. Of note this more [elaborate](https://termbin.com/kfec) VLAN config works fine with the .45 image on the mamba, so I do not think this is device related.

I do not see any commits in the kernel changelog comments that would indicate something significant on this front.

**Comment by rmandrad** [comment]
just to let you know that on my WRT3200ACM - I build the .45 kernel (with the same patches as .43) and it is working.
There were some changes not long time ago on netifd - are you using the latest version @anomeome ?

**Comment by anomeome** [comment]
I have tried the commits in the netifd repo ahead of what is currently pushed to master, I suspected cpu port so tried [upstream patch](https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=9d5ef190e561), and other things as time permitted. Could just be me, currently running .44 until .46 makes an appearance.

**Comment by hauke** [comment]
Thank you for the pull request, I applied the first update in 79481c71dcb9426878b9738755027c994d4d2273.

**Comment by rsalvaterra** [comment]
Thanks, @hauke. Pull request updated accordingly.

**Comment by jospezial** [comment]
5.10.46 please, contains important lantiq fixes.

**Comment by anomeome** [comment]
.46 fixes up the above bridge-vlan issue.

**Comment by rsalvaterra** [comment]
@jospezial, @anomeome, done.

**Comment by rsalvaterra** [comment]
Don't merge this yet, it needs to be fixed (missing kernel symbol that slipped due to my configuration).

**Comment by rsalvaterra** [comment]
Fixed.

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master.

**Pull request closed without merging**
