### PR TITLE
tools/ninja: update to 1.12.1 with same patches

### LINKED ISSUE #16675: Ninja fails to build with Python 3.13
### Describe the bug

Ninja (part of the toolchain) fails to build on Fedora 41 with the following error message:

```bash
make[3]: Entering directory '/var/home/michael/src/router_stuff/openwrt/tools/ninja'
cd /var/home/michael/src/router_stuff/openwrt/build_dir/host/ninja-1.11.1 && CXX="/var/home/michael/src/router_stuff/openwrt/staging_dir/host/bin/g++" CXXFLAGS="-O2 -I/var/home/michael/src/router_stuff/openwrt/staging_dir/host/include  -I/var/home/michael/src/router_stuff/openwrt/staging_dir/host/include " LDFLAGS="-L/var/home/michael/src/router_stuff/openwrt/staging_dir/host/lib " /var/home/michael/src/router_stuff/openwrt/staging_dir/host/bin/python3 configure.py --bootstrap --verbose
Traceback (most recent call last):
  File "/var/home/michael/src/router_stuff/openwrt/build_dir/host/ninja-1.11.1/configure.py", line 26, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
make[3]: *** [Makefile:40: /var/home/michael/src/router_stuff/openwrt/build_dir/host/ninja-1.11.1/.built] Error 1
make[3]: Leaving directory '/var/home/michael/src/router_stuff/openwrt/tools/ninja'
time: tools/ninja/compile#0.20#0.20#0.38
    ERROR: tools/ninja failed to build.
make[2]: *** [tools/Makefile:231: tools/ninja/compile] Error 1
make[2]: Leaving directory '/var/home/michael/src/router_stuff/openwrt'
make[1]: *** [tools/Makefile:227: /var/home/michael/src/router_stuff/openwrt/staging_dir/host/stamp/.tools_compile_nyyynyynnnyyynynyyyyyyynyyynynyynnynnyyyyyynyyyyyyyyyyynynnyyyyynyyy] Error 2
make[1]: Leaving directory '/var/home/michael/src/router_stuff/openwrt'
make: *** [/var/home/michael/src/router_stuff/openwrt/include/toplevel.mk:248: world] Error 2
```

This happens because Fedora uses Python 3.13 which has [removed](https://docs.python.org/3/whatsnew/3.13.html) `pipes` as a standard library. The issue has been fixed in version 1.12.0 and above of Ninja: https://github.com/ninja-build/ninja/pull/2340

### OpenWrt version

r27146-2ce206f27d

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

ipq806x/generic

### Device

Netgear Nighthawk X4S R7800

### Image kind

Self-built image

### Steps to reproduce

_No response_

### Actual behaviour

_No response_

### Expected behaviour

_No response_

### Additional info

_No response_

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by mcprat**
ping @hauke @robimarko 

Closes #16675 

In the interest of solving issue #16675 as simply and as fast as possible,
update ninja without changing which jobserver implementation is used.

That way, we have a cleaner history, and Rosen's PR #16424 can focus
on the jobserver patch only, giving us more time to make the right decision.

Also included are very simple and helpful Makefile edits and a patch that allows
Make to control the parallel building of Ninja itself.

### CODE REVIEW

**Comment by mcprat** [comment]
I know what's wrong... one moment...

**Comment by mcprat** [comment]
ok, I reviewed the diff very carefully this time... the jobserver patch is reduced even more in order to adapt to how the main builder loop has changed which ironically favors this old method even more, so the patch is a little smaller.

I should also mention, that I have had the first 3 commits here with the other fixes for a while and already tested for months on a branch while I was working on my Ninja PR. The commits are still dated as early August and earlier.

**Comment by mcprat** [comment]
changed the name of the option to `--no-rebuild` to avoid confusion

**Comment by mcprat** [comment]
actually I think the third commit makes the second one unnecessary...

**Comment by neheb** [comment]
I’m fine with this.

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by Neustradamus** [comment]
@mcprat: Good job!

And @neheb too for:
- https://github.com/openwrt/openwrt/pull/16424

**Comment by mcprat** [comment]
now that the google guy took over working on jobserver support, it seems no one here really wants to work on it anymore...

I will send them comments at some point though

**Pull request merged**
