### PR TITLE
netifd: update to Git  768027c (2024-11-25)

### PR DESCRIPTION
**Pull request by systemcrash**
#### TODO

- [x] investigate [86da5cbcdb9d](https://github.com/openwrt/netifd/commit/86da5cbcdb9d) `system-linux: do not pull ifindex/flags from netlink messages on rtnl events` as it seems to cause regressions with `ppp` based connections, [see](https://github.com/openwrt/openwrt/pull/17074#issuecomment-2499015781) 

-----
includes new ipproto property in rules

### CODE REVIEW

**Comment by ynezz** [comment]
Can you retry this update with https://git.openwrt.org/?p=maintainer-tools.git;a=blob_plain;f=update_git_source_package.sh;h=d7f823755d6ed7573aa15f703859f01a9017b016;hb=HEAD ?

Its as easy as `../maintainer-tools.git/update_git_source_package.sh netifd`

Thanks!

**Comment by systemcrash** [comment]
Sure thing. I did the CHECK=1 way. Does that turn out wrong?

**Comment by systemcrash** [comment]
Just my luck. git.openwrt.org seems to be down or otherwise not responding....

**Comment by ynezz** [comment]
Its going to provide proper Git commit subject (`latest` is relative etc.) and description of the changes (its currently missing).

**Comment by systemcrash** [comment]
I suppose if one provides a commit hash, it fixes that for you... :D

**Comment by systemcrash** [comment]
Fixed.

**Comment by systemcrash** [comment]
Could you also cherry-pick to 24?

**Comment by ynezz** [comment]
Is the `ipproto` documentaiton fine with you? https://openwrt.org/docs/guide-user/network/routing/ip_rules#options_for_ipv4_and_ipv6_rules

**Comment by systemcrash** [comment]
Yeah, good. During my testing, I think I tried 'UDP' and it worked fine. That can be amended in the docu later.

**Comment by ynezz** [comment]
> Fixed.

I would say, that this is the correct list of the changes:

```
34eb11eb6f5c device/interface: add "tags" attribute from config to status dump
86da5cbcdb9d system-linux: do not pull ifindex/flags from netlink messages on rtnl events
cd96f61ba63e proto-shell: fix spurious interface teardowns with host deps
a39fe3a8b150 wireless: add support for adding a list of devices for a wifi-iface
d29cf707478c iprule: add ipproto property
```

> Could you also cherry-pick to 24?

You can propose that change via pull request, but I'm certainly not going to cherry-pick so many changes into 24.10 :)

**Comment by systemcrash** [comment]
> > Fixed.
> 
> I would say, that this is the correct list of the changes:
> 
> ```
> 34eb11eb6f5c device/interface: add "tags" attribute from config to status dump
> 86da5cbcdb9d system-linux: do not pull ifindex/flags from netlink messages on rtnl events
> cd96f61ba63e proto-shell: fix spurious interface teardowns with host deps
> a39fe3a8b150 wireless: add support for adding a list of devices for a wifi-iface
> d29cf707478c iprule: add ipproto property
> ```
> 
> > Could you also cherry-pick to 24?
> 
> You can propose that change via pull request, but I'm certainly not going to cherry-pick so many changes into 24.10 :)

I would too but that's what the script produced. Shall I update it?
 
> > I think I tried 'UDP' and it worked fine.
> 
> ```c
> [RULE_IPPROTO]  = { .name = "ipproto", .type = BLOBMSG_TYPE_INT32 }
> ```
> 
> I'm not sure `UDP` would work, but there might be some translation layer I'm missing.

Yeah, I considered that, and thought it worth testing strings there to see how error handling worked. It was a while ago tho.

**Comment by e9hack** [comment]
`86da5cbcdb9d system-linux: do not pull ifindex/flags from netlink messages on rtnl events`
prevents the pppd daemon from starting. Therefore, there is no WAN connectivity.

**Comment by systemcrash** [comment]
So if you build netifd  @e9hack without that commit, pppd starts fine?

**Comment by e9hack** [comment]
I did build with the latest commit first. Since there was no WAN connectivity and no log entries related to the ppd demon in the logs, I did go back commit by commit. From that commit back to the previous one (latest in the main repo) pppd daemon did start again.

**Comment by systemcrash** [comment]
Hmm. So that commit prevents pppd from automatically starting, or from starting *at all*?

**Comment by systemcrash** [comment]
In any case, it seems like a trivial fix is to revert that commit. But I have no permission to do that...

**Comment by systemcrash** [comment]
ping @nbd168 see https://github.com/openwrt/openwrt/pull/17074#issuecomment-2499015781

**Comment by e9hack** [comment]
If I revert commit `86da5cbcdb9d system-linux: do not pull ifindex/flags from netlink messages on rtnl events`, then the head revision from netifd repo does work. 

I don't now if pppd does start or not. I'm connected via wifi and have to wait some time till I get access again.

**Comment by systemcrash** [comment]
> I don't now if pppd does start or not. I'm connected via wifi and have to wait some time till I get access again.

OK - for completeness sake, understanding what happens here will be beneficial.

**Comment by e9hack** [comment]
I replaced pppd by a script which starts the original pppd. The script generates an additional log entry. With the special commit, pppd is not started. I don't see the log entry from the start script. Without the special commit, pppd will be started. I see the log entries from the script and from pppd itself.

**Comment by nbd168** [comment]
Please show me a `/etc/config/network` that's affected by the bug.

**Comment by nbd168** [comment]
Thanks. I tracked down the issue and pushed a fix to netifd git

**Comment by systemcrash** [comment]
> Thanks. I tracked down the issue and pushed a fix to netifd git

Thanks for the fast fix. Updated.

**Comment by e9hack** [comment]
> Thanks. I tracked down the issue and pushed a fix to netifd git

Yes this fixes the issue.

**Pull request merged**
