### PR TITLE
kernel: Remove platform specific symbol for 4.19

### PR DESCRIPTION
**Pull request by diizzyy**
(CONFIG_)FRAME_WARN is platform specific and gets populated automatically
Source: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/lib/Kconfig.debug?h=v4.19.21#n222

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@chunkeey 
Can you have a look at this?

**Comment by diizzyy** [comment]
..and while we're on the topic
http://lists.infradead.org/pipermail/openwrt-devel/2019-February/015738.html

**Comment by diizzyy** [comment]
Forgot to add:
Tested with:  https://github.com/openwrt/openwrt/pull/1799 (with and without ``V=s```)

**Comment by chunkeey** [comment]
> @chunkeey
> Can you have a look at this?

sure, you know that 4.19 is currently on the backburner until 19.x gets tagged.
I'll add fixes for sure, but I wonder why you didn't make them for the existing 4.14 branches?

**Comment by diizzyy** [comment]
Because for all I know it should have been branched a long time ago ( https://lists.openwrt.org/pipermail/openwrt-adm/2018-September/000901.html ) or is there a the lack of communication? Adding last minute fixes is usually a bad idea even though they shouldn't cause any regressions.

**Comment by neheb** [comment]
Tested-by: Rosen Penev <rosenp@gmail.com>

**Comment by diizzyy** [comment]
Ping

**Comment by diizzyy** [comment]
Any progress on these 4.19 related PRs?

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by ynezz** [comment]
What could go wrong with such simple change, I've thought and considered it for merging:

```
make[4]: Entering directory '/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/linux-imx6/linux-4.19.34'
Makefile:600: include/config/auto.conf: No such file or directory
  HOSTCC  scripts/kconfig/conf.o
  LEX     scripts/kconfig/zconf.lex.c
  YACC    scripts/kconfig/zconf.tab.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --syncconfig Kconfig
net/sched/Kconfig:44: warning: menuconfig statement without prompt
.config:4073:warning: symbol value 'm' invalid for NF_NAT_REDIRECT
*
* Restart config...
*
*
* Compile-time checks and compiler options
*
Allow gcc to uninline functions marked 'inline' (OPTIMIZE_INLINING) [N/y/?] n
Compile the kernel with debug info (DEBUG_INFO) [Y/n/?] y
  Reduce debugging information (DEBUG_INFO_REDUCED) [Y/n/?] y
  Produce split debuginfo in .dwo files (DEBUG_INFO_SPLIT) [N/y/?] n
  Generate dwarf4 debuginfo (DEBUG_INFO_DWARF4) [N/y/?] n
  Provide GDB scripts for kernel debugging (GDB_SCRIPTS) [N/y/?] n
Enable __must_check logic (ENABLE_MUST_CHECK) [N/y/?] n
Warn for stack frames larger than (needs gcc 4.4) (FRAME_WARN) [1024] (NEW)
```

**Comment by diizzyy** [comment]
This is due to the inconsistent behaviour of using ```V=s``` / ```V=sc```, if you omit those switches buildroot properly populates it. I don't have the interest in looking into it further so I'll just close it instead.

**Pull request closed without merging**
