### PR TITLE
ipq40xx: drop upstreamed board-2.bin's

### PR DESCRIPTION
**Pull request by ecsv**
The BDFs for Meraki MR33, 8devices Jalapeno, AVM FRITZ!Box 4040, GL.iNet GL-B1300 and Netgear EX6100v2/EX6150v2 were upstreamed to the ath10k-firmware repository and are now part of ath10k-firmware 2018-04-19. The ipq-wifi-* packages for these devices can now be dropped because OpenWrt's ath10k-firmware package was updated to this version.

@riptidewave93, @robimarko, @chunkeey, @mkresin, @handongming, @blocktrron , you might be interested in checking these changes.

### CODE REVIEW

**Comment by robimarko** [comment]
Its weird that only Jalapeno which was sent over a month ago was not upstreamed.

**Comment by ecsv** [comment]
> Its weird that only Jalapeno which was sent over a month ago was not upstreamed.

Ehrm, please check the list again at http://lists.infradead.org/pipermail/ath10k/2018-April/011190.html - And Kalle just started to add more of them. Most likely, your BDFs will also be included soon.

**Comment by robimarko** [comment]
I checked the mailing list.
They were sent by you in March and like B1300 ones caught no traction.
Hopefully Kalle Valo is now doing it all at once

**Comment by ecsv** [comment]
Looks like Kalle Valo is now processing the rest of the submissions. Only remaining files are Asus RT-AC58U and 8devices Jalapeno.

I will be offline for the rest of the day - but I will most likely adjust the pull request tomorrow to include all the other BDFs.

**Comment by robimarko** [comment]
Yes,he added everything

**Comment by ecsv** [comment]
The additional upstreamed BDFs were now added. There might be an additional change for ASUS RT-AC58U in the near future.

**Comment by chunkeey** [comment]
@ecsv thank you. While not on the list, I've tested the current RT-AC58U boarddata with my RT-AC58U as well and it's now working much better with the ath10k-firmware.git's board-2.bin. 

Note: the ath10-firmware.git's board-2.bin boarddata for the RT-AC58U is the same as in the ipq-wifi-asus_rt-ac58u package. So, if you want to go for it, you could replace it as well... And if Kalle decides
to go through with the update I'll post the patch later.

The question is, what will happen to the ipq-wifi package?

**Comment by mkresin** [comment]
Dang it! Every time I finished my compile test something changes.

What is the deal with RT-AC58U boarddata file? @tchebb mentioned in his commit that a wrong file/version was upstreamed, Sven keep the OpenWrt boarddata file and the only one with access to the hardware says that everything is fine using the ath10-firmware.git's board-2.bin.

> The question is, what will happen to the ipq-wifi package?

If no one has a better idea, I' in favour of keeping the package. Given the time it took to get this batch of board data files/entries upstream, it might be required for future ipq40xx board additions.

**Comment by chunkeey** [comment]
Ok, let me try to explain. (from my POV)

First, the change Kvalo merged into his tree: https://github.com/kvalo/ath10k-firmware/commit/a47bcf1e58c4d8914af0951a80fd8861368b700d
is pretty much the same "data" that we ship in ipq-wifi-asus_rt-ac58u.
So, it would be OK to just use it for now. (The only difference is, the
ipq-wifi-asus_rt-ac58u board-2.bin file does not have the variant=RT-AC58U
string, whereas Kvalo's version does. So the wifi0 & wifi1 node in the 
qcom-ipq4018-rt-ac58u.dts need to be updated.)

What happend was, that I posted a updated v2 Patch for the RT-AC58U 
back in January 2018 (after the merge of the A42 Boardfile went through). 
http://lists.infradead.org/pipermail/ath10k/2018-January/010770.html

But it went unnoticed and @ecsv didn't include it in his "reminder/ping mail to kvalo"
so Kalle picked the older version. And I guess @ecsv / @tchebb were waiting for him to
delete the upload the right file.

**Comment by mkresin** [comment]
20.04.2018 21:42, Christian Lamparter:
> Ok, let me try to explain. (from my POV)
> 
> First, the change Kvalo merged into his tree: 
> kvalo/ath10k-firmware@a47bcf1 
> <https://github.com/kvalo/ath10k-firmware/commit/a47bcf1e58c4d8914af0951a80fd8861368b700d>
> is pretty much the same "data" that we ship in ipq-wifi-asus_rt-ac58u.
> So, it would be OK to just use it for now. (The only difference is, the
> ipq-wifi-asus_rt-ac58u board-2.bin file does not have the variant=RT-AC58U
> string, whereas Kvalo's version does. So the wifi0 & wifi1 node in the
> qcom-ipq4018-rt-ac58u.dts need to be updated.)

qcom-ipq4018-rt-ac58u.dts has already a qcom,ath10k-calibration-variant 
but not matching the string that was upstreamed with v1.

> What happend was, that I posted a updated v2 Patch for the RT-AC58U
> back in January 2018 (after the merge of the A42 Boardfile went through).
> http://lists.infradead.org/pipermail/ath10k/2018-January/010770.html

Out of curiosity, what what is the difference of v1 and v2 beside the 
different variant string.

> But it went unnoticed and @ecsv <https://github.com/ecsv> didn't include 
> it in his "reminder/ping mail to kvalo"
> so Kalle picked the older version. And I guess @ecsv 
> <https://github.com/ecsv> / @tchebb <https://github.com/tchebb> were 
> waiting for him to
> delete the upload the right file.

If I got it right, what I've in my staging tree should do the job. Am I 
right?

**Comment by chunkeey** [comment]
On Freitag, 20. April 2018 22:33:58 CEST Mathias Kresin wrote:
> 20.04.2018 21:42, Christian Lamparter:
> > Ok, let me try to explain. (from my POV)
> > 
> > First, the change Kvalo merged into his tree: 
> > kvalo/ath10k-firmware@a47bcf1 
> > <https://github.com/kvalo/ath10k-firmware/commit/a47bcf1e58c4d8914af0951a80fd8861368b700d>
> > is pretty much the same "data" that we ship in ipq-wifi-asus_rt-ac58u.
> > So, it would be OK to just use it for now. (The only difference is, the
> > ipq-wifi-asus_rt-ac58u board-2.bin file does not have the variant=RT-AC58U
> > string, whereas Kvalo's version does. So the wifi0 & wifi1 node in the
> > qcom-ipq4018-rt-ac58u.dts need to be updated.)
> 
> qcom-ipq4018-rt-ac58u.dts has already a qcom,ath10k-calibration-variant 
> but not matching the string that was upstreamed with v1.
Oh ok. Then I must have done this during the ipq806x/ipq40xx split already.
 
> > What happend was, that I posted a updated v2 Patch for the RT-AC58U
> > back in January 2018 (after the merge of the A42 Boardfile went through).
> > http://lists.infradead.org/pipermail/ath10k/2018-January/010770.html
> 
> Out of curiosity, what what is the difference of v1 and v2 beside the 
> different variant string.
I wish I knew. Maybe Sven could tell you more... But I guess he would want
an RT-AC58U for it ;).

The firmware release notes on ASUS Firmware site:
<https://www.asus.com/Networking/RT-AC58U/HelpDesk_BIOS/>

Only mention it in Version 3.0.0.4.380.7485 as:
|Optimization
|- Wireless 5GHz band performance

> > But it went unnoticed and @ecsv <https://github.com/ecsv> didn't include 
> > it in his "reminder/ping mail to kvalo"
> > so Kalle picked the older version. And I guess @ecsv 
> > <https://github.com/ecsv> / @tchebb <https://github.com/tchebb> were 
> > waiting for him to
> > delete the upload the right file.
> 
> If I got it right, what I've in my staging tree should do the job. Am I 
> right?

Yes you are right.

[0] <https://git.openwrt.org/?p=openwrt/staging/mkresin.git;a=blob;f=target/linux/ipq40xx/files-4.14/arch/arm/boot/dts/qcom-ipq4018-rt-ac58u.dts;h=d988275564380998e3d113353c87af47cac7a972;hb=6e67a2492b1ea1eafc3a548f5f0a92262362b7f9#l92>

**Comment by mkresin** [comment]
@chunkeey Got it! The board.bin merged by Kalle was from an older ASUS firmware. Your v2 includes the board.bin from the latest ASUS firmware but nobody knows what really has been changed.

@ecsv are you fine with the changes I applied to your patches as they can be seen in my staging tree?

**Comment by ecsv** [comment]
I can sent you some of the extracted data via mail. But my availability is not really that high this weekend - so I might reply in a timely fashion (and I don't have access to my HW - so A62 is postponed till Monday).

The change in your staging tree looks almost correct. I think you also wanted to remove the ipq-wifi-asus_rt-ac58u in target/linux/ipq40xx/image/Makefile and remove the board-asus_rt-ac58u.bin

**Comment by ecsv** [comment]
Now the squashed patches in your branch have:

* extra change in target/linux/ipq40xx/config-4.14 (ipq-wifi: drop custom board-2.bins)

**Comment by mkresin** [comment]
I took the easy way and merged your PR as it is. Thanks!

**Pull request closed without merging**
