### PR TITLE
package/utils/f2fs-tools: Update to 1.12.0

### PR DESCRIPTION
**Pull request by diizzyy**
Update f2fs-tools to 1.12.0

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested: ramips
Runtime tested: ramips, WiTi board, OpenWrt master

**Comment by diizzyy** [comment]
@tofurky

**Comment by tofurky** [comment]
i'll build & test this later today.

**Comment by tofurky** [comment]
same/similar issue. rather than install it system-wide i just extracted libf2fs/mkf2fs/f2fsck to a directory and used LD_LIBRARY_PATH. i'm sure it's using the new library because otherwise ldd failed with missing symbols.

this version just hangs with 0% cpu/io instead of exiting.

```
root@cosmos:~/f2fs# LD_LIBRARY_PATH=`pwd`/usr/lib usr/sbin/mkfs.f2fs /dev/sdb1 

	F2FS-tools: mkfs.f2fs Ver: 1.12.0 (2018-11-12)

Info: Disable heap-based policy
Info: Debug level = 0
Info: Trim is enabled
Info: [/dev/sdb1] Disk Model: Geek Squad      
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 7862849 (3839 MB)
Info: zone aligned segment0 blkaddr: 512
Info: format version with
  "Linux version 4.14.72 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Fri Sep 28 00:07:38 2018"
Info: [/dev/sdb1] Discarding device
Info: This device doesn't support BLKSECDISCARD
Info: This device doesn't support BLKDISCARD
Info: Overprovision ratio = 3.250%
Info: Overprovision segments = 128 (GC reserved = 69)
Info: format successful
```
```
root@cosmos:~/f2fs# LD_LIBRARY_PATH=`pwd`/usr/lib usr/sbin/fsck.f2fs /dev/sdb1 
Info: [/dev/sdb1] Disk Model: Geek Squad      
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 7862849 (3839 MB)
Info: MKFS version
  "Linux version 4.14.72 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Fri Sep 28 00:07:38 2018"
Info: FSCK version
  from "Linux version 4.14.72 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Fri Sep 28 00:07:38 2018"
    to "Linux version 4.14.72 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Fri Sep 28 00:07:38 2018"
Info: superblock features = 0 : 
Info: superblock encrypt level = 0, salt = 00000000000000000000000000000000
Info: total FS sectors = 7862848 (3839 MB)
Info: CKPT version = 2c871f4b
Info: Checked valid nat_bits in checkpoint
Info: checkpoint state = 185 :  trimmed nat_bits compacted_summary unmount
[ASSERT] (__check_inode_mode: 351)  --> inode [0x3] unknown file type i_mode [0x41ed0000]

NID[0x3] is unreachable, blkaddr:0x2600
[FSCK] Unreachable nat entries                        [Fail] [0x1]
[FSCK] SIT valid block bitmap checking                [Fail]
[FSCK] Hard link checking for regular file            [Ok..] [0x0]
[FSCK] valid_block_count matching with CP             [Fail] [0x0]
[FSCK] valid_node_count matcing with CP (de lookup)   [Fail] [0x0]
[FSCK] valid_node_count matcing with CP (nat lookup)  [Ok..] [0x1]
[FSCK] valid_inode_count matched with CP              [Fail] [0x0]
[FSCK] free segment_count matched with CP             [Ok..] [0x766]
[FSCK] next block offset is free                      [Ok..]
[FSCK] fixing SIT types
[FSCK] other corrupted bugs                           [Fail]

```

if anything i'd suggest downgrading to 1.10.0 rather than bumping again.

**Comment by diizzyy** [comment]
Is that using ath79 or ar71xx?

**Comment by tofurky** [comment]
ath79. more or less the same system/toolchain i first encountered the issue with on a few months back.

**Comment by diizzyy** [comment]
Can you try ar71xx? While I don't have my TP-Link around I'm pretty sure it's something odd going on with USB on ath79.

**Comment by tofurky** [comment]
i have another ar7161 router i can test with. which version did you want? can you provide .ipk for at least libf2fs and fsck.f2fs?

**Comment by diizzyy** [comment]
@tofurky 
I want to you give the ar71xx "profile/toolchain" a go instead of ath79 using the latest version.
I'd do it myself but all of my ar71xx/ath79 devices are no longer in my possesion.

**Comment by tofurky** [comment]
i meant latest night, build from master, 18.06.x, etc. i'll just do snapshot.

**Comment by diizzyy** [comment]
Oh, sorry... snapshot is as 18.X is only getting security updates.

**Comment by tofurky** [comment]
same issue with `openwrt-ar71xx-generic-wndr3700v2-squashfs-sysupgrade.bin` and `openwrt-sdk-ar71xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz`
```
root@OpenWrt:~# uname -a
Linux OpenWrt 4.14.82 #0 Wed Nov 28 00:11:38 2018 mips GNU/Linux
root@OpenWrt:~# mkfs.f2fs /dev/sda1

	F2FS-tools: mkfs.f2fs Ver: 1.12.0 (2018-11-12)

Info: Disable heap-based policy
Info: Debug level = 0
Info: Trim is enabled
Info: [/dev/sda1] Disk Model: Geek Squad      
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 7862849 (3839 MB)
Info: zone aligned segment0 blkaddr: 512
Info: format version with
  "Linux version 4.14.82 (buildbot@e18fde3b3fb2) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r8590-824b580)) #0 Wed Nov 28 00:11:38 2018"
Info: [/dev/sda1] Discarding device
Info: This device doesn't support BLKSECDISCARD
Info: This device doesn't support BLKDISCARD
Info: Overprovision ratio = 3.250%
Info: Overprovision segments = 128 (GC reserved = 69)
Info: format successful
root@OpenWrt:~# fsck.f2fs /dev/sda1
Info: [/dev/sda1] Disk Model: Geek Squad      
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 7862849 (3839 MB)
Info: MKFS version
  "Linux version 4.14.82 (buildbot@e18fde3b3fb2) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r8590-824b580)) #0 Wed Nov 28 00:11:38 2018"
Info: FSCK version
  from "Linux version 4.14.82 (buildbot@e18fde3b3fb2) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r8590-824b580)) #0 Wed Nov 28 00:11:38 2018"
    to "Linux version 4.14.82 (buildbot@e18fde3b3fb2) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r8590-824b580)) #0 Wed Nov 28 00:11:38 2018"
Info: superblock features = 0 : 
Info: superblock encrypt level = 0, salt = 00000000000000000000000000000000
Info: total FS sectors = 7862848 (3839 MB)
Info: CKPT version = 313595cd
Info: Checked valid nat_bits in checkpoint
Info: checkpoint state = 185 :  trimmed nat_bits compacted_summary unmount
[ASSERT] (__check_inode_mode: 351)  --> inode [0x3] unknown file type i_mode [0x41ed0000]

NID[0x3] is unreachable, blkaddr:0x2600
[FSCK] Unreachable nat entries                        [Fail] [0x1]
[FSCK] SIT valid block bitmap checking                [Fail]
[FSCK] Hard link checking for regular file            [Ok..] [0x0]
[FSCK] valid_block_count matching with CP             [Fail] [0x0]
[FSCK] valid_node_count matcing with CP (de lookup)   [Fail] [0x0]
[FSCK] valid_node_count matcing with CP (nat lookup)  [Ok..] [0x1]
[FSCK] valid_inode_count matched with CP              [Fail] [0x0]
[FSCK] free segment_count matched with CP             [Ok..] [0x766]
[FSCK] next block offset is free                      [Ok..]
[FSCK] fixing SIT types
[FSCK] other corrupted bugs                           [Fail]
```

**Comment by diizzyy** [comment]
Thanks, that's really strange and odd since it seems to only affect Atheros MIPS devices :/

**Comment by diizzyy** [comment]
Compile tested: sunxi
Runtime tested: sunxi, Orange Pi PC, OpenWrt master (Hauke's 4.19 branch with some minor patches)

**Comment by diizzyy** [comment]
No, as I mentioned above I no longer have ar71xx devices.

**Comment by neheb** [comment]
@tofurky Try this patch: https://drive.google.com/file/d/18dRSchNVqkBOfxayzeIh4cInVovPSlET/view?usp=sharing

I see a missing cpu_to_le16 in that commit.

**Comment by tofurky** [comment]
@neheb hey nice catch, that seemed to fix it:
```
root@OpenWrt:~# mkfs.f2fs /dev/sda1 

	F2FS-tools: mkfs.f2fs Ver: 1.12.0 (2018-11-12)

Info: Disable heap-based policy
Info: Debug level = 0
Info: Trim is enabled
Info: [/dev/sda1] Disk Model: Geek Squad      
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 7862849 (3839 MB)
Info: zone aligned segment0 blkaddr: 512
Info: format version with
  "Linux version 4.14.82 (buildbot@e18fde3b3fb2) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r8590-824b580)) #0 Wed Nov 28 00:11:38 2018"
Info: [/dev/sda1] Discarding device
Info: This device doesn't support BLKSECDISCARD
Info: This device doesn't support BLKDISCARD
Info: Overprovision ratio = 3.250%
Info: Overprovision segments = 128 (GC reserved = 69)
Info: format successful
root@OpenWrt:~# fsck.f2fs /dev/sda1
Info: [/dev/sda1] Disk Model: Geek Squad      
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 7862849 (3839 MB)
Info: MKFS version
  "Linux version 4.14.82 (buildbot@e18fde3b3fb2) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r8590-824b580)) #0 Wed Nov 28 00:11:38 2018"
Info: FSCK version
  from "Linux version 4.14.82 (buildbot@e18fde3b3fb2) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r8590-824b580)) #0 Wed Nov 28 00:11:38 2018"
    to "Linux version 4.14.82 (buildbot@e18fde3b3fb2) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r8590-824b580)) #0 Wed Nov 28 00:11:38 2018"
Info: superblock features = 0 : 
Info: superblock encrypt level = 0, salt = 00000000000000000000000000000000
Info: total FS sectors = 7862848 (3839 MB)
Info: CKPT version = 6cc39dc9
Info: Checked valid nat_bits in checkpoint
Info: checkpoint state = 185 :  trimmed nat_bits compacted_summary unmount

[FSCK] Unreachable nat entries                        [Ok..] [0x0]
[FSCK] SIT valid block bitmap checking                [Ok..]
[FSCK] Hard link checking for regular file            [Ok..] [0x0]
[FSCK] valid_block_count matching with CP             [Ok..] [0x2]
[FSCK] valid_node_count matcing with CP (de lookup)   [Ok..] [0x1]
[FSCK] valid_node_count matcing with CP (nat lookup)  [Ok..] [0x1]
[FSCK] valid_inode_count matched with CP              [Ok..] [0x1]
[FSCK] free segment_count matched with CP             [Ok..] [0x766]
[FSCK] next block offset is free                      [Ok..]
[FSCK] fixing SIT types
[FSCK] other corrupted bugs                           [Ok..]

Done.

```

**Comment by neheb** [comment]
@diizzyy want to integrate that or should I? Mailing list patch will get merged faster.

**Comment by tofurky** [comment]
maybe this patch is better than reverting the entire commit?
```
diff -uNr f2fs-tools-1.12.0/fsck/fsck.c f2fs-tools-1.12.0.new/fsck/fsck.c
--- f2fs-tools-1.12.0/fsck/fsck.c	2018-11-21 14:39:05.000000000 -0500
+++ f2fs-tools-1.12.0.new/fsck/fsck.c	2018-12-06 20:08:19.480648517 -0500
@@ -339,7 +339,7 @@
 	return ret;
 }
 
-static int __check_inode_mode(u32 nid, enum FILE_TYPE ftype, u32 mode)
+static int __check_inode_mode(u32 nid, enum FILE_TYPE ftype, u16 mode)
 {
 	if (ftype >= F2FS_FT_MAX)
 		return 0;
@@ -457,7 +457,7 @@
 		return 0;
 
 	if (ntype == TYPE_INODE &&
-		__check_inode_mode(nid, ftype, le32_to_cpu(node_blk->i.i_mode)))
+		__check_inode_mode(nid, ftype, le16_to_cpu(node_blk->i.i_mode)))
 		return -EINVAL;
 
 	/* workaround to fix later */

```

from include/f2fs_fs.h:
```
struct f2fs_inode {
        __le16 i_mode;                  /* file mode */
        __u8 i_advise;                  /* file hints */
        __u8 i_inline;                  /* file inline flags */
        __le32 i_uid;                   /* user ID */
```

**Comment by neheb** [comment]
Oh that seems better. I assume you've tested this?

**Comment by tofurky** [comment]
yeah i edited the comment to say i had tested it shortly after i posted it, sorry.

**Comment by neheb** [comment]
Ok. I will submit upstream once I get approved by the mailing list.

**Comment by tofurky** [comment]
okay, i can get the patch in a form suitable for submission upstream if you give me a bit

**Comment by diizzyy** [comment]
.....

**Comment by neheb** [comment]
@tofurky Does f2fs still work for you? I'm getting [ASSERT] (build_curseg:1517) array on my drive. A freshly created filesystem works fine.

I also get OOM when mounting it.

**Comment by cshoredaniel** [comment]
On 2/5/19 4:05 PM, Rosen Penev wrote:
>
> @tofurky <https://github.com/tofurky> Does f2fs still work for you?
> I'm getting [ASSERT] (build_curseg:1517) array on my drive. A freshly
> created filesystem works fine.
>
> I also get OOM when mounting it.
>
Been working for me on ath79 with f2fs created after the update and
working fine since then.  Used it with and with POSIX_ACL enabled too BTW.

Regards,

Daniel

**Comment by neheb** [comment]
It's erroring for me on "ASSERT(array);" in the code.

malloc(144) is what array gets set to. No idea how that can fail...

**Comment by tofurky** [comment]
i updated to master tonight and wound up switching back to 1.10.0 (again...). i didn't have time to look into it much but the first fsck after fs creation went okay, second or third boot it started doing this:
```
[    6.684058] sd 0:0:0:0: [sda] Attached SCSI removable disk
Info: Force to fix corruption
Info: [/dev/sda1] Disk Model: STORAGE DEVICE  
Info: Segments per section = 1
Info: Sections per zone = 1
Info: sector size = 512
Info: total sectors = 3334144 (1628 MB)
Info: MKFS version
  "Linux version 4.14.101 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Wed Feb 20 00:21:07 2019"
Info: FSCK version
  from "Linux version 4.14.101 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Wed Feb 20 00:21:07 2019"
    to "Linux version 4.14.101 (matt@aquos) (gcc version 8.2.0 (OpenWrt GCC 8.2.0 r7953+1-a4f4ddba61)) #0 Wed Feb 20 00:21:07 2019"
Info: superblock features = 0 : 
Info: superblock encrypt level = 0, salt = 00000000000000000000000000000000
Info: total FS sectors = 3334144 (1628 MB)
Info: CKPT version = 43ff23ad
Info: Corrupted valid nat_bits in checkpoint
Info: Write valid nat_bits in checkpoint
Info: checkpoint state = c4 :  nat_bits crc compacted_summary sudden-power-off
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x5 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x3a reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x38 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x39 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x35 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x15 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x37 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x19 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x11 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x24 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x26 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x21 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x28 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x25 reset i_g[   13.011020] block: check_filesystem: /usr/sbin/fsck.f2fs returned 255
c_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x3e reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x27 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x3c reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x41 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x43 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x2b reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x2c reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x2d reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x2e reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x2f reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x30 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x31 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x32 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x33 reset i_gc_failures from 0x1 to 0x00
[FIX] (fsck_chk_inode_blk: 954)  --> Regular: 0x42 reset i_gc_failures from 0x1 to 0x00

[FSCK] Unreachable nat entries                        [Ok..] [0x0]
[FSCK] SIT valid block bitmap checking                [Ok..]
[FSCK] Hard link checking for regular file            [Ok..] [0x0]
[FSCK] valid_block_count matching with CP             [Ok..] [0x40]
[FSCK] valid_node_count matcing with CP (de lookup)   [Ok..] [0x2f]
[FSCK] valid_node_count matcing with CP (nat lookup)  [Ok..] [0x2f]
[FSCK] valid_inode_count matched with CP              [Ok..] [0x2f]
[FSCK] free segment_count matched with CP             [Ok..] [0x31d]
[FSCK] next block offset is free                      [Ok..]
[FSCK] fixing SIT types
[FSCK] other corrupted bugs                           [Fail]
[ASSERT] (check_seg_range:1546) segno <= end_segno
[   13.648499] F2FS-fs (sda1): Found nat_bits in checkpoint
[   14.011574] F2FS-fs (sda1): Mounted with checkpoint version = 43ff23ad
```

**Comment by neheb** [comment]
Someone broke something. Mine started failing earlier.

In any case, I formatted my drive back to ext4 as I got tired of breakage and OOM from the kernel f2fs driver.

**Comment by diizzyy** [comment]
f2fs is also throwing errors on octeon and arm when using 4.19 + overlayfs so there's some kind of kernel bug too.

**Comment by neheb** [comment]
I get this on 4.14 as well. Must be some messed up backport.

**Comment by diizzyy** [comment]
https://github.com/openwrt/openwrt/pull/1800#issuecomment-461799659 for reference

**Comment by tofurky** [comment]
i haven't seen any kernel issues with f2fs since bumping to 4.14.101. i've only done a few hundred MiB of writes, though.

**Pull request closed without merging**
