### PR TITLE
kernel: bump 5.15 to 5.15.58

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B, mt7622/RT3200
Run-tested: bcm2711/RPi4B, mt7622/RT3200

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by rsalvaterra** [comment]
LGTM, thanks!

**Comment by rockdrilla** [comment]
@graysky2 5.15.55 is out and please look here: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.15.y&id=c80b15105a08dceffcbb0381f85696b46bce0d1b

**Comment by hardfalcon** [comment]
Compile tested: x86/64
Run tested: x86/64

**Comment by rockdrilla** [comment]
Build system: x86_64
Build-tested: ath79/generic
Run-tested: ath79/generic

**Comment by ldir-EDB0** [comment]
x86_64 has some new and hence missing config symbols to do with speculative execution mitigations, see https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/arch/x86/Kconfig?id=v5.15.57&id2=v5.15.56

**Comment by graysky2** [comment]
@ldir-EDB0 - I created the following `.config` and ran `make kernel_menuconfig` but that did not pull in any of the new defaults.  What is the right way to regenerate?

```
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y
```

For reference, that resulted in:
```
diff --git a/target/linux/x86/config-5.10 b/target/linux/x86/config-5.10
index ec27bb7945..71d39efc51 100644
--- a/target/linux/x86/config-5.10
+++ b/target/linux/x86/config-5.10
@@ -67,6 +67,7 @@ CONFIG_CRC16=y
 CONFIG_CRYPTO_CRC32=y
 CONFIG_CRYPTO_CRC32C=y
 # CONFIG_CRYPTO_CRC32_PCLMUL is not set
+CONFIG_CRYPTO_LIB_BLAKE2S_GENERIC=y
 CONFIG_CRYPTO_LIB_POLY1305_RSIZE=1
 CONFIG_CRYPTO_RNG2=y
 # CONFIG_CRYPTO_SERPENT_SSE2_586 is not set
@@ -157,7 +158,6 @@ CONFIG_HW_RANDOM_VIA=y
 # CONFIG_HYPERVISOR_GUEST is not set
 CONFIG_HZ_PERIODIC=y
 CONFIG_I8253_LOCK=y
-# CONFIG_I8K is not set
 CONFIG_IA32_FEAT_CTL=y
 # CONFIG_IB700_WDT is not set
 # CONFIG_IBMASR is not set
@@ -168,7 +168,6 @@ CONFIG_INITRAMFS_SOURCE=""
 CONFIG_INPUT=y
 CONFIG_INPUT_KEYBOARD=y
 CONFIG_INSTRUCTION_DECODER=y
-# CONFIG_INTEL_INT0002_VGPIO is not set
 # CONFIG_INTEL_PCH_THERMAL is not set
 # CONFIG_INTEL_POWERCLAMP is not set
 # CONFIG_INTEL_SCU_PCI is not set
```

**Comment by graysky2** [comment]
I manually edited `target/linux/x86/config-5.15` adding the defaulted symbols.  Someone please comment on the latest commit.

**Comment by ldir-EDB0** [comment]
x86_64 - builds & runs ok for me

**Comment by trippleflux** [comment]
Build system: x86_64
Build-tested: x86_64/generic
Run-tested: x86_64/generic

**Comment by hauke** [comment]
Thank you for the patches, I applied them to master in e4af991220638d4bb32e4668435d140afe232b25, ce014b1e3903887d47bede8128f2c698418ac5f1, 4921ab0be462aa0336e3a100e0bf77ffbcc6c09a, 317f59a0ee33b0deb0be4cedb7da20b302c7f6b9, 9d2ffe8cb895b8fd3f8f30389a50201babd213d9 and 364575e3a31e2e4e775a802fc8453b2d5a520e04.

**Pull request closed without merging**
