### PR TITLE
tools: switch LibreSSL to OpenSSL 1.1.1

### PR DESCRIPTION
**Pull request by commodo**
There may be a growing trend to start migrating back to OpenSSL, since it
has recovered quite a bit from the HeartBleed incident.
In the meantime, LibreSSL has been lagging behind in some features.
And a number of applications are trying to make use of these new features
and algorithms of OpenSSL.

Some links:
  https://lwn.net/Articles/841664/
  https://www.python.org/dev/peps/pep-0644/#compatibility
  https://www.python.org/dev/peps/pep-0644/#libressl-support

In my case, Python (starting with version 3.10) has started to enforce
OpenSSL 1.1.1 as a minimum. This makes it difficult for the python3 package
(the host version) to support HTTP SSL requests.
The SSL module of the host Python3 is required to download packages from
pypi.org for some Python3 packages in the packages feed.

An alternative would be to just patch CPython to work with libressl,
however this may be an early sign that other tools (CMake comes to mind)
would also start preferring OpenSSL.

LibreSSL has been forked from 1.0.1g in 2014.

While both SSL implementations have significant contributions, there seems
to be more push (newer features and contributors) on OpenSSL than LibreSSL.

There's even an OpenSSL 3.0.0 version. That version may be too new for
what's needed right now, but 1.1.1 seems like a good version to use right
now in the tools/ folder.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
ping  @neheb 
you seemed a bit interested in this OpenSSL 1.1.1 thing;
maybe ping other interested parties?

**Comment by neheb** [comment]
I prefer keeping LibreSSL. The build system is a lot more sane.

**Comment by commodo** [comment]
> I prefer keeping LibreSSL. The build system is a lot more sane.

yeah, OpenSSL's build system is a bit specific/quirky;
well, i will try to think of a way that works for Python;
keeping LibreSSL and adding a host-build for OpenSSL would be a bit nuts as well;
the headers and libs would overlap each other;
or, we could add a separate prefix for OpenSSL in staging_dir, but ¯\_(ツ)_/¯  ;
that's also just polluting the staging dir

i'll keep this PR here for a few days to sort of raise attention to it;
then i'll just keep the branch in my tree;

in the meantime I think I can try to patch Python to work with LibreSSL;
hopefully that will not evolve into something really annoying to keep patching;

i do feel that the idea to switch `tools/libressl -> tools/openssl` may come back later (not necessarily from my side);

**Comment by ptpt52** [comment]
I prefer the openssl

**Comment by dhewg** [comment]
Is that an actual problem you ran into, as in you updated the python3 package to 3.10?
I didn't dig into this at all, but it seems somewhat unlikely, as that would prevent *BSD to update their python, no?

**Comment by commodo** [comment]
> Is that an actual problem you ran into, as in you updated the python3 package to 3.10? I didn't dig into this at all, but it seems somewhat unlikely, as that would prevent *BSD to update their python, no?

yes; it actually fails to build the _ssl module in the host Python build;
some functions are missing in OpenBSD's LibreSSL;
and we need it for the Python build to download stuff from pypi.org

i did not check whether they updated their Python version;
but I did see that they did update some things in their libssl folder, to add some of the the missing functions that would help Python work with _ssl;
but that also means waiting for them to release a newer (standalone) LibreSSL [i'd be fine with that];

right now, I'm also working on a patch to support _ssl on host-Python with LibreSSL;
it's compiling, but not yet working;
patch looks like this (it gives an idea of what's missing in LibreSSL 3.4.1); 

```
--- a/Modules/_ssl.c
+++ b/Modules/_ssl.c
@@ -67,7 +67,47 @@
 #  error "OPENSSL_THREADS is not defined, Python requires thread-safe OpenSSL"
 #endif
 
+#ifdef OPENWRT_HOST_BUILD
+static int SSL_write_ex(SSL *s, const void *buf, size_t num, size_t *written)
+{
+    int ret = SSL_write(s, buf, num);
+    if (ret > 0)
+        *written = ret;
+    if (ret < 0)
+        ret = 0;
+    return (ret > 0);
+}
 
+static int SSL_read_ex(SSL *s, void *buf, size_t num, size_t *readbytes)
+{
+    int ret = SSL_read(s, buf, num);
+    if (ret > 0)
+        *readbytes = ret;
+    if (ret < 0)
+        ret = 0;
+    return (ret > 0);
+}
+
+static STACK_OF(X509) *SSL_get0_verified_chain(const SSL *s)
+{
+    return NULL;
+}
+
+static int SSL_CTX_set_num_tickets(SSL_CTX *ctx, size_t num_tickets)
+{
+    return 0;
+}
+
+size_t SSL_CTX_get_num_tickets(const SSL_CTX *ctx)
+{
+    return 0;
+}
+
+static int SSL_CTX_get_security_level(const SSL_CTX *ctx)
+{
+    return 0;
+}
+#endif
 
 struct py_ssl_error_code {
     const char *mnemonic;
--- a/Modules/_ssl/debughelpers.c
+++ b/Modules/_ssl/debughelpers.c
@@ -7,6 +7,13 @@
 #define SSL3_MT_CHANGE_CIPHER_SPEC              0x0101
 #endif
 
+#ifdef OPENWRT_HOST_BUILD
+typedef void (*SSL_CTX_keylog_cb_func)(const SSL *ssl, const char *line);
+static void SSL_CTX_set_keylog_callback(SSL_CTX *ctx, SSL_CTX_keylog_cb_func cb)
+{
+}
+#endif
+
 static void
 _PySSL_msg_callback(int write_p, int version, int content_type,
                     const void *buf, size_t len, SSL *ssl, void *arg)
```

**Comment by dhewg** [comment]
Huh, okay, that indeed looks problematic, thanks!

I don't know how urgent it is to bump the python3 package to >=3.10, but maybe wait a little 'till the dust settles.
It doesn't sound like support for libressl is gone for good: https://github.com/python/cpython/pull/28728#pullrequestreview-771114099
Maybe it all just works out with either of the parties releasing point releases to improve the situation.

**Comment by commodo** [comment]
> Huh, okay, that indeed looks problematic, thanks!
> 
> I don't know how urgent it is to bump the python3 package to >=3.10, but maybe wait a little 'till the dust settles. It doesn't sound like support for libressl is gone for good: [python/cpython#28728 (review)](https://github.com/python/cpython/pull/28728#pullrequestreview-771114099) Maybe it all just works out with either of the parties releasing point releases to improve the situation.

Well, it's not hurry from my side to update.
Though, this update is a little rockier than others (due to this OpenSSL story).
I've been working on this update on-n-off for 1-2 weeks now, trying to balance things.
Maybe this will settle in the next 2-4 weeks (which is fine).
I'll try to do a patch for CPython with LibreSSL, mostly to remove this from my work-queue for now.

In recent years, I also started trying to address some things at CPython level.
[Like these here](https://github.com/python/cpython/pulls?q=is%3Apr+author%3Acommodo+).
I got a bit of push-back from CPython on this OpenSSL think (see https://github.com/python/cpython/pull/29237 & https://bugs.python.org/issue45627 )
There's also hashlib that doesn't build without OpenSSL 1.1.1, but that lib isn't important for the host-side Python.

Yeah, navigating people's preferences is what this seems to boil down to :)

**Comment by dhewg** [comment]
Comparing OpenBSD's commit history with the diff you provided:
https://github.com/openbsd/src/commit/b5b7f1d2e021c1f41a554ad9366a06918f76f0b8
https://github.com/openbsd/src/commit/4a18b5ba2a01b084bc9ce0b8de88c9b0e394aa3b
https://github.com/openbsd/src/commit/8095b13035d3c80c255344b9166e7f4ff88e61e3
https://github.com/openbsd/src/commit/d1ec7c35ff68639d2ffc9074aada99d8e3dda889

If your diff is complete (in the sense of python >= 3.10 requirements) it appears only `SSL_CTX_get_security_level` is missing atm. So yes, waiting for a release including those symbols is most likely way easier that pushing for s/libressl/openssl/ :)

**Comment by commodo** [comment]
> If your diff is complete (in the sense of python >= 3.10 requirements) it appears only `SSL_CTX_get_security_level` is missing atm. So yes, waiting for a release including those symbols is most likely way easier that pushing for s/libressl/openssl/ :)

yeah, i found the same things last week;
but i only started looking into their tree after doing this PR;
the push-back I got from CPython is why I initially went for this PR/change

**Comment by dhewg** [comment]
OpenBSD's ports has python 3.10, and with its system libressl it seems they only need this one patch for `SSL_CTX_get_security_level`: https://github.com/openbsd/ports/blob/master/lang/python/3.10/patches/patch-Modules__ssl_c

**Comment by commodo** [comment]
> OpenBSD's ports has python 3.10, and with its system libressl it seems they only need this one patch for `SSL_CTX_get_security_level`: https://github.com/openbsd/ports/blob/master/lang/python/3.10/patches/patch-Modules__ssl_c

Thanks :)
I was thinking about looking for it later.
So, this means, we wait for their LibreSSL release and use this patch.

I'll close this PR in the next few days.

**Comment by dhewg** [comment]
Looks like that's indeed going to be easier now, but maybe there're other arguments for OpenSSL?
Dunno, I just got a little bit confused as it almost sounded like *BSD are stuck with <3.10 heh :)

**Comment by commodo** [comment]
> Looks like that's indeed going to be easier now, but maybe there're other arguments for OpenSSL? Dunno, I just got a little bit confused as it almost sounded like *BSD are stuck with <3.10 heh :)

Well, this also influenced me a bit:  https://lwn.net/Articles/841664/
It's a not very strong against LibreSSL, but it looks like some frustration venting.
There's also some contribution numbers comparisons there (per LibreSSL and per OpenSSL).

The Python core dev (who handles SSL) also pitched in there with a comment :
```
Posted Jan 4, 2021 23:21 UTC (Mon) by tiran (guest, #94212) [Link]
As the maintainer of CPython's ssl module I agree with the article.\
A short while ago I have created a Python enhancement 
proposal to drop compatibility with old OpenSSL versions and require 
OpenSSL >= 1.1.1 in Python 3.10. The same PEP 
also proposes to remove LibreSSL support from upstream CPython. 
Python core development doesn't have resources to support LibreSSL.
It's taking considerable time to work around API incompatibilities. 
Missing APIs are also blocking new features.

https://www.python.org/dev/peps/pep-0644/#libressl-support
```

And it does indeed feel that LibreSSL has been playing catch-up with OpenSSL.
For me, it's just Python 3.10 I care about.
Let's see how this evolves later :)

**Comment by dhewg** [comment]
I can't really comment on all the details, but the frustrations seem to go both ways:
https://gitlab.alpinelinux.org/alpine/tsc/-/issues/28

**Comment by commodo** [comment]
> I can't really comment on all the details, but the frustrations seem to go both ways: https://gitlab.alpinelinux.org/alpine/tsc/-/issues/28

figures i guess :)
well, we'll see ¯\_(ツ)_/¯

**Comment by dhewg** [comment]
@commodo see ^
That may influence how you wanna proceed.
Maybe reopen this or backport the libressl patches for the next half year?

**Comment by commodo** [comment]
> @commodo see ^ That may influence how you wanna proceed. Maybe reopen this or backport the libressl patches for the next half year?

oh; thanks for pitching in that discussion :)
so, backporting patches is the path of least resistance for now;

TBH, I don't care which {Libre,Open}SSL we use, as long as I don't need to manually spin-up patches which are also hard to sell to other people in the community.
If it's about Python, it's fine; I co-maintain it, so it's easier.

For now, switching LibreSSL to OpenSSL is a hard-sell; and I suspected it wouldn't fly.
But at least we got here, which mostly raises awareness on this.

**Comment by dhewg** [comment]
Sounds like a plan, I guess I would do the same (for the record: I don't care that much either, I just believe that changing the host SSL lib is more painful).

Just so I get the full picture (I don't use any python packages on-target):
If a python target package is build with/using pypi, that drags in the host python package, which then depends on the host SSL lib to download stuff over https? Without pypi there wouldn't be any need for the host python package?

**Comment by commodo** [comment]
> Sounds like a plan, I guess I would do the same (for the record: I don't care that much either, I just believe that changing the host SSL lib is more painful).
> 

I wouldn't change the tools/ssl lib either.
But, I don't know how painful it is to switch either.

> Just so I get the full picture (I don't use any python packages on-target): If a python target package is build with/using pypi, that drags in the host python package, which then depends on the host SSL lib to download stuff over https? Without pypi there wouldn't be any need for the host python package?

Python-target always requires Python-host.
It's one of the [since-forever] quirks of cross-building Python for a specific platform.
At some stage in the build, the same host-Python interpreter is required to do some stuff (which I forget) for the target-Python.
When building natively, the build re-uses the interpreter from the same build.
If the versions wouldn't need to match so closely, we wouldn't need to build the host-Python.

For other Python packages for target-build, the host-Python should have the _ssl module available, so that `pip` can download from `https://` URLs (from pypi.org usually).
So, Python (itself) will build fine without this SSL stuff, but other Python packages (for target and host builds) won't download; which will fill-up the buildbot faillogs.

**Comment by commodo** [comment]
urgs....
even with LibreSSL's patches, I still get:
```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError('No cipher can be selected.'))': /simple/ply/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError('No cipher can be selected.'))': /simple/ply/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError('No cipher can be selected.'))': /simple/ply/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError('No cipher can be selected.'))': /simple/ply/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError('No cipher can be selected.'))': /simple/ply/
Could not fetch URL https://pypi.org/simple/ply/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ply/ (Caused by SSLError(SSLError('No cipher can be selected.'))) - skipping
```

oh well, back to the drawing board;
i guess i may not patch LibreSSL at all;
it looks like I will just need to patch Python myself in a special way;
but i still felt like venting about this a bit;
and it's likely that OpenBSD's Python suffers from a similar issue, but they don't know it [maybe]

**Comment by dhewg** [comment]
Ugh, maybe some defines within python need to be adapted?
But don't worry, we've all been had these annoying bang-head-on-keyboad problems :)

**Comment by commodo** [comment]
for posterity;
i've cracked it: https://github.com/openwrt/packages/pull/17121

**Comment by dhewg** [comment]
Alright, so I assume patching libressl wasn't successful?

**Comment by commodo** [comment]
> Alright, so I assume patching libressl wasn't successful?

It may work to patch libressl, but I'd avoid it.
I have more control over what goes into Python than LibreSSL and OpenWrt core :)

**Pull request closed without merging**
