### PR TITLE
[RFC/RFT] build: switch to firewall4 by default

### PR DESCRIPTION
**Pull request by aparcar**
The next OpenWrt release might use `firewall4`, let's test it?

This commit replaces firewall aka firewall3 with its nftables based
successor firewall4.

Heads up for packages.git: https://github.com/openwrt/packages/issues/16818
Heads up for routing.git: https://github.com/openwrt/routing/issues/731
Heads up for luci.git: https://github.com/openwrt/luci/issues/5409

**Issues**:

- [x] option zone in /etc/config/network is ignored by firewall4
- [x] flow offloading doesn't work if no interfaces are configured
- [x] rules with option _name are skipped
- [x] defaults section is ignored if it contains any unsupported option
- [x] ipsets of type ipv{4,6}_addr claim CIDR is invalid
- [x] ipsets don't support timeout

Working on those [here](https://git.openwrt.org/?p=project/firewall4.git;a=log;h=refs/heads/staging/stintel/dev)

### CODE REVIEW

**Comment by champtar** [comment]
LGTM
If we want to switch we need to do it early so we have time to fix packages

**Comment by neheb** [comment]
doesn't nftables come with an iptables compat utility?

**Comment by K900** [comment]
Is fw4 at feature parity with fw3 yet? Last time I checked, it didn't support offloading, which is kind of a big deal for me and others running OpenWRT on potato home routers.

**Comment by aparcar** [comment]
> Is fw4 at feature parity with fw3 yet?

It should be as compatible as possible before we actually set it as default. 

> Last time I checked, it didn't support offloading, which is kind of a big deal for me and others running OpenWRT on potato home routers.

I haven't done any tests yet but the package `kmod-nft-offload` suggests something like that should be possible.

**Comment by K900** [comment]
I know it should be possible, yeah, it's just not implemented as of right now (I've just checked the source).

**Comment by stintel** [comment]
I will be pushing this to firewall4.git and bumping it in OpenWrt soon. One thing you're missing is that LuCI depends on luci-app-firewall, and luci-app-firewall depends on firewall, and firewall4 conflicts with firewall, so currently there is no way to have both LuCI and firewall4. I've asked Jo how we best solve that, suggesting to use PROVIDES.

**Comment by stintel** [comment]
I have zero experience with nftables to be honest, just gave firewall4 a try recently and notices flow offload was missing. In the examples I've found, they always seem to define devices. Docs mention

> The *devices* are specified as iifname(s) of the input interface(s) of the traffic that should be offloaded. Devices are required for both traffic directions. 

Can anyone with more experience tell me if this is actually required? With the changes I made to firewall4, the nft_flow_offload module shows as being in use in lsmod, so it does at least something.

> Out of curiosity, I've checked out the diff, and it seems like only IPv4 will get offloaded with this configuration? (`ip protocol { tcp , udp } flow offload @ft;`)

As I mentioned already, I've never touched nftables before. Just looked at some examples and the one I looked at while adding support for flow_offloading to firewall4 did not have IPv6 flow offloading enabled. I have updated my changes to firewall4 locally, but I cannot force push or delete the flow_offload branch. I can use another branch name but that would only pollute things. So while I wait for someone to give me more rights on firewall4.git, the changes can be grabbed from [my firewall4 branch of OpenWrt](https://git.openwrt.org/?p=openwrt/staging/stintel.git;a=shortlog;h=refs/heads/firewall4).

I would appreciate testing and feedback.

**Comment by K900** [comment]
Got it! Will definitely give this a try, probably somewhere next week.

**Comment by aparcar** [comment]
@stintel while you update `firewall4` please add PROVIDES to it. I had the same thought but currently no commit access to it.

I'm guessing that LuCI should work if `iftables-nft` is installed and Jo mentioned to add a JSON parser at some point.

**Comment by stintel** [comment]
> Not yet, I've been waiting for the LuCI changes to land first.

https://github.com/openwrt/luci/tree/firewall4

**Comment by stintel** [comment]
> https://github.com/openwrt/luci/tree/firewall4

Unfortunately there seems to be a circular dependency caused by the CONFLICTS definition in firewall4. You can manually remove that to be able to select firewall4. Don't forget to deselect firewall(3) afterwards.

Aside from that it seems ipset rules are also not supported. I make extensive use of that, so that's a blocker for me.

**Comment by stintel** [comment]
Issues:

[ ] option zone in /etc/config/network is ignored by firewall4
[ ] flow offloading doesn't work if no interfaces are configured

**Comment by dave14305** [comment]
There's a lot of activity from @stintel on firewall4. What's needed for a mortal user to be able to start testing?

**Comment by stintel** [comment]
> There's a lot of activity from @stintel on firewall4. What's needed for a mortal user to be able to start testing?

Build an image from [the firewall4 branch in my staging tree](https://git.openwrt.org/?p=openwrt/staging/stintel.git;a=shortlog;h=refs/heads/firewall4). If you need LuCI, you need [its firewall4 branch](https://github.com/openwrt/luci/tree/firewall4) too. You can point feeds.conf to it like this:

```
src-git luci https://github.com/openwrt/luci.git;firewall4
```

**Comment by K900** [comment]
Seems to work fine for me on Archer C6 v2. I was somewhat hopeful this would also fix https://bugs.openwrt.org/index.php?do=details&task_id=3373, but unfortunately it does not.

**Comment by K900** [comment]
On a related note, firewall4 should probably depend on kmod-nft-offload, otherwise enabling offload on a clean build breaks the whole thing.

**Comment by stintel** [comment]
> On a related note, firewall4 should probably depend on kmod-nft-offload, otherwise enabling offload on a clean build breaks the whole thing.

Thanks, added the dependency.

**Comment by rmandrad** [comment]
Hi just to report that I am running fw4 with 5.15 - I used your luci firewall4 + stintel repository fixes.  All good - had to delete a few things out of the /etc/config/firewall. Question - I lost the luci-app-firewall gui, is this intended ?

**Comment by dave14305** [comment]
> Hi just to report that I am running fw4 with 5.15 - I used your luci firewall4 + stintel repository fixes. All good - had to delete a few things out of the /etc/config/firewall. Question - I lost the luci-app-firewall gui, is this intended ?

I believe the Luci menu item is not shown because it depends on fw3 binary still.

https://github.com/openwrt/luci/blob/28221b5d9f920ef8eea17943bbeea7ee4e9b9d97/applications/luci-app-firewall/root/usr/share/luci/menu.d/luci-app-firewall.json#L11

**Comment by stintel** [comment]
> I lost the luci-app-firewall gui, is this intended ?

See https://github.com/openwrt/openwrt/pull/4642#issuecomment-980477493

**Comment by rmandrad** [comment]
> > I lost the luci-app-firewall gui, is this intended ?
> 
> See [#4642 (comment)](https://github.com/openwrt/openwrt/pull/4642#issuecomment-980477493)

thank you ... yes I applied your commit

**Comment by dave14305** [comment]
> > I lost the luci-app-firewall gui, is this intended ?
> 
> See [#4642 (comment)](https://github.com/openwrt/openwrt/pull/4642#issuecomment-980477493)

If firewall3 isn’t built, there is no /sbin/fw3 executable to satisfy the menu.d depends. Looks like firewall4 installs /usr/sbin/fw3 link instead.

**Comment by rmandrad** [comment]
there is a link indeed but to fw4 
lrwxrwxrwx    1 root     root             3 Dec 25 10:15 /usr/sbin/fw3 -> fw4

**Comment by dave14305** [comment]
> there is a link indeed but to fw4 lrwxrwxrwx 1 root root 3 Dec 25 10:15 /usr/sbin/fw3 -> fw4
> 
> removing the link and copying /usr/sbin/fw4 to fw3 doesn't change anything ... the firewall menu doesn't show

Try changing the `/usr/share/luci/menu.d/luci-app-firewall.json` from `/sbin/fw3` to `/usr/sbin/fw3` to see if it makes the Firewall menu appear.

**Comment by rmandrad** [comment]
> > there is a link indeed but to fw4 lrwxrwxrwx 1 root root 3 Dec 25 10:15 /usr/sbin/fw3 -> fw4
> > removing the link and copying /usr/sbin/fw4 to fw3 doesn't change anything ... the firewall menu doesn't show
> 
> Try changing the `/usr/share/luci/menu.d/luci-app-firewall.json` from `/sbin/fw3` to `/usr/sbin/fw3` to see if it makes the Firewall menu appear.

@dave14305 thank you that did the trick I now have the firewall menu- I used fw4 instead of fw3

**Comment by stintel** [comment]
> If firewall3 isn’t built, there is no /sbin/fw3 executable to satisfy the menu.d depends. Looks like firewall4 installs /usr/sbin/fw3 link instead.

Fixed in [my firewall4 staging branch](https://git.openwrt.org/?p=project/firewall4.git;a=shortlog;h=refs/heads/staging/stintel/dev).

**Comment by stintel** [comment]
FYI: just pushed my changes to firewall4.git, openwrt.git and luci.git.

**Comment by K900** [comment]
Trying it now, flow offloading seems to be broken on Archer C6 v2:

```
root@openwrt:~# uci show 'firewall.@defaults[0].flow_offloading'
firewall.cfg01e63d.flow_offloading='1'
root@openwrt:~# nft list ruleset | grep flowtable
root@openwrt:~#
```

**Comment by stintel** [comment]
> Trying it now, flow offloading seems to be broken on Archer C6 v2:
> 
> ```
> root@openwrt:~# uci show 'firewall.@defaults[0].flow_offloading'
> firewall.cfg01e63d.flow_offloading='1'
> root@openwrt:~# nft list ruleset | grep flowtable
> root@openwrt:~#
> ```

Looks like that got borked due to changes requested from review :-( I'll look into it.

**Comment by stintel** [comment]
https://git.openwrt.org/?p=project/firewall4.git;a=commitdiff;h=b68cf67019452527d6a5a967b823a39dd1ba1edd;hp=be5f4e33c6388935651e6a87c4e5348ade0bd714

It's an easy fix so you could do that manually until I push the fix and bump firewall4 in openwrt.git.

**Comment by aparcar** [comment]
Excellent work, thank you @stintel !

**Comment by K900** [comment]
Another issue I just found, I can't open the zone editor in LuCI, at least with theme-openwrt-2020.

**Comment by jow-** [comment]
> Another issue I just found, I can't open the zone editor in LuCI, at least with theme-openwrt-2020.

Any error reported in the browser console?

**Comment by K900** [comment]
I'll have to retest it later tonight, rolled back to fw3 for now.

**Comment by K900** [comment]
> > Another issue I just found, I can't open the zone editor in LuCI, at least with theme-openwrt-2020.
> 
> Any error reported in the browser console?

All I'm getting is `TypeError: can't convert null to object`, looks like [this line](https://github.com/openwrt/luci/blob/master/modules/luci-base/htdocs/luci-static/resources/ui.js#L777).

**Comment by K900** [comment]
> https://git.openwrt.org/?p=project/firewall4.git;a=commitdiff;h=b68cf67019452527d6a5a967b823a39dd1ba1edd;hp=be5f4e33c6388935651e6a87c4e5348ade0bd714
> 
> It's an easy fix so you could do that manually until I push the fix and bump firewall4 in openwrt.git.

The change worked as in a flowtable entry gets created, but it doesn't look like it's actually being used... I'm still getting massive CPU spikes under heavy load, and the bandwidth is severely limited.

**Comment by stintel** [comment]
> > https://git.openwrt.org/?p=project/firewall4.git;a=commitdiff;h=b68cf67019452527d6a5a967b823a39dd1ba1edd;hp=be5f4e33c6388935651e6a87c4e5348ade0bd714
> > It's an easy fix so you could do that manually until I push the fix and bump firewall4 in openwrt.git.
> 
> The change worked as in a flowtable entry gets created, but it doesn't look like it's actually being used... I'm still getting massive CPU spikes under heavy load, and the bandwidth is severely limited.

Running `perf top` shows nf_flow_table calls being made when I do a speedtest, so I conclude it is working...

**Comment by K900** [comment]
I am getting about 150mbps on Speedtest.net with fw4, and 600+ with fw3...

**Comment by stintel** [comment]
> I am getting about 150mbps on Speedtest.net with fw4, and 600+ with fw3...

It is most definitely working for me, as evidenced by these iperf3 runs:

Flow offloading disabled:
```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   449 MBytes   377 Mbits/sec   32             sender
[  5]   0.00-10.00  sec   446 MBytes   374 Mbits/sec                  receiver
```

Flow offloading enabled:
```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.08 GBytes   929 Mbits/sec   44             sender
[  5]   0.00-10.01  sec  1.08 GBytes   927 Mbits/sec                  receiver
```

Does your nft ruleset contain the correct devices in the flowtable?

**Comment by K900** [comment]
I've got br-lan and eth0.2 (which is my WAN interface). I'll have to retest later again.

**Comment by stintel** [comment]
@aparcar I've got 2 more changes pending in https://git.openwrt.org/?p=project/firewall4.git;a=shortlog;h=refs/heads/staging/stintel/fixes waiting for review by jow. Once these are in I'm OK with switching to firewall4 by default.

**Comment by aparcar** [comment]
This commit does not automatically add the transparent wrapper for _legacy_ iptables. Should it be added by default or would you make it a user choice?

For the next release it could make sense to add the wrapper to break less user setups. We should check the size impact, right?

**Comment by stintel** [comment]
I've hit some very nasty issue on a CentOS 8 box from mixing the transparent wrapper with nft for which I could not find a solution other than to reboot the machine, so I would prefer not to use the transparent wrapper at all.

**Comment by champtar** [comment]
I would say do not ship the wrapper by default, have package maintainer test if it actually make their package work and add the dependency as needed.

**Comment by aparcar** [comment]
Exciting, please ping me once the last commits are pushed, I'll then merge this.

I'll also write another heads up to the sub issues in each repo.

**Comment by Ansuel** [comment]
Oh wow we are switching to fw4 by default? Ot question but related.
Should we care that fw3 doesn't work with 5.15 now that fw4 will be default?
Or fw4 still has some limitations?

Il Gio 6 Gen 2022, 20:12 Paul Spooren ***@***.***> ha scritto:

**Comment by Ansuel** [comment]
> > I am getting about 150mbps on Speedtest.net with fw4, and 600+ with fw3...
> 
> It is most definitely working for me, as evidenced by these iperf3 runs:
> 
> Flow offloading disabled:
> 
> ```
> [ ID] Interval           Transfer     Bitrate         Retr
> [  5]   0.00-10.00  sec   449 MBytes   377 Mbits/sec   32             sender
> [  5]   0.00-10.00  sec   446 MBytes   374 Mbits/sec                  receiver
> ```
> 
> Flow offloading enabled:
> 
> ```
> [ ID] Interval           Transfer     Bitrate         Retr
> [  5]   0.00-10.00  sec  1.08 GBytes   929 Mbits/sec   44             sender
> [  5]   0.00-10.01  sec  1.08 GBytes   927 Mbits/sec                  receiver
> ```
> 
> Does your nft ruleset contain the correct devices in the flowtable? Also, to rule out other issues, test using 2 local endpoints.

This is strange... I'm currently testing this and I have 50mbps with a 150mbps connection... no flow offload... Can we investigate this perf regression?

**Comment by K900** [comment]
Just out of curiosity, what hardware are you testing on? Is hardware offload on? I'm on ath79, so no hardware offload for me. Is there a chance Stijn got those results with hardware offloading?

**Comment by Ansuel** [comment]
No hardware offload ipq806x

**Comment by stintel** [comment]
I'm on qoriq, also no HW offloading.

**Comment by rsalvaterra** [comment]
> Should we care that fw3 doesn't work with 5.15 now that fw4 will be default?

There are still components which don't work with fw4. A very, **very** important one (in my humble opinion, since I use it professionally) is mwan3. For now, we're using Linux 5.10, and people who need mwan3 can choose fw3 instead of fw4, so we should be fine for the next release. That said (and I know we're still in very early stages), when we upgrade to 5.15, I envision three possibilities:

1. Fw4 ships by default and fw3 is fixed to work with 5.15, allowing people to choose fw3 if they want to use mwan3;
2. Fw4 ships by default, fw3 stays broken in 5.15, people won't be able to use mwan3 (trainwreck scenario);
3. Somewhere, along the way, a wild mwan4 appears (the ideal, though I wager it's going to take a lot of work and time);

The obvious interim solution is, of course, to fix fw3. Thoughts?

**Comment by Ansuel** [comment]
@rsalvaterra IMHO the only correct way is fw3 but don't know if it's worth... currently fw3 doesn't work in 5.15 and with the revert patch pppoe doesn't work. Using fw4 fix all these problem at once.

**Comment by champtar** [comment]
@rsalvaterra mwan3 is also a blocker for me, but I still think we should go ahead with the fw4 switch so that if there are too many issues we can switch back before rc0. mwan4 will need some work for sure but there is a chance the logic is pretty similar. Until we switch nobody will look into it ;)

**Comment by stintel** [comment]
> Until we switch nobody will look into it ;)

That's the general feeling I'm getting, yes. All the more reason to switch early.

**Comment by rmandrad** [comment]
> > > I am getting about 150mbps on Speedtest.net with fw4, and 600+ with fw3...
> > 
> > 
> > It is most definitely working for me, as evidenced by these iperf3 runs:
> > Flow offloading disabled:
> > ```
> > [ ID] Interval           Transfer     Bitrate         Retr
> > [  5]   0.00-10.00  sec   449 MBytes   377 Mbits/sec   32             sender
> > [  5]   0.00-10.00  sec   446 MBytes   374 Mbits/sec                  receiver
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Flow offloading enabled:
> > ```
> > [ ID] Interval           Transfer     Bitrate         Retr
> > [  5]   0.00-10.00  sec  1.08 GBytes   929 Mbits/sec   44             sender
> > [  5]   0.00-10.01  sec  1.08 GBytes   927 Mbits/sec                  receiver
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does your nft ruleset contain the correct devices in the flowtable? Also, to rule out other issues, test using 2 local endpoints.
> 
> This is strange... I'm currently testing this and I have 50mbps with a 150mbps connection... no flow offload... Can we investigate this perf regression?

I haven't noticed any impact with wrt3200acm with fw4 either with flow offload or not ... unsure if there is any impact but I changed 660-fq_codel_defaults.patch (generic hack) to have the same definition as CONFIG_X86_64

**Comment by dave14305** [comment]
What happens to Luci’s Status -> Firewall page under firewall4?

**Comment by aparcar** [comment]
As discussed at yesterdays meeting I merged the changes. The next release will use `firewall4` as default and all packages incompatible (e.g. using `ipset`) should add a negative dependency. Our considerations are that the default (WiFI home router) setup works fine wir `firewall4` and special cases can always replace `firewall4` with `firewall3`, which should work at least until the upcoming 5.15 Kernels.

**Comment by K900** [comment]
Turns out my perf regression wasn't rooted in fw4, but in SQM/qosify. I'm guessing it now works more correctly (?) with offloaded flows, which completely kills the CPU...

**Comment by josacar** [comment]
I'm having some issues with `fw4` generating config with offloading:

```
# nft -f fw4.conf
fw4.conf:9:12-13: Error: Could not process rule: Not supported
flowtable ft {
^^
fw4.conf:54:29-44: Error: Could not process rule: No such file or directory
meta l4proto { tcp, udp } flow offload @ft;
```

this is a fragment of the file:
```
flush table inet fw4

table inet fw4 {
#
# Flowtable
#

flowtable ft {
hook ingress priority 0;
devices = { "br-lan", "pppoe-wan" };
flags offload;
}

#
# Set definitions
#


#
# Defines
#

define lan_devices = { "br-lan" }
define lan_subnets = { 192.168.1.0/24, 2a0c:5a84:b101:1000::/64, fd13:4280:a26d::/64 }
define wan_devices = { "pppoe-wan" }
define wan_subnets = { 86.127.238.4, fe80::567f:ee04, 2a0c:5a84:b1ff:ffff::567f:ee04 }

#
# User includes
#

include "/etc/nftables.d/*.nft"


#
# Filter rules
#

chain input {
type filter hook input priority filter; policy accept;

iifname "lo" accept comment "!fw4: Accept traffic from loopback"

ct state established,related accept comment "!fw4: Allow inbound established and related flows"
tcp flags & (fin | syn | rst | ack) == syn jump syn_flood comment "!fw4: Rate limit TCP syn packets"
iifname "br-lan" jump input_lan comment "!fw4: Handle lan IPv4/IPv6 input traffic"
iifname "pppoe-wan" jump input_wan comment "!fw4: Handle wan IPv4/IPv6 input traffic"
}

chain forward {
type filter hook forward priority filter; policy drop;

meta l4proto { tcp, udp } flow offload @ft;
ct state established,related accept comment "!fw4: Allow forwarded established and related flows"
iifname "br-lan" jump forward_lan comment "!fw4: Handle lan IPv4/IPv6 forward traffic"
iifname "pppoe-wan" jump forward_wan comment "!fw4: Handle wan IPv4/IPv6 forward traffic"
jump handle_reject
}

Thanks in advance.
```

**Pull request closed without merging**
