### PR TITLE
[21.02] iproute2: backport 5.11 update and improvements, related NLS fixes

### PR DESCRIPTION
**Pull request by guidosarducci**
### Description:
This backport series starts with recent updates to `iproute2` (#3904 and #3961) which are relevant to OpenWrt 21.02. They bring key improvements including:
1. Update to `iproute2` 5.11
This is the first version to use the modern `libbpf`, allowing more consistent and featureful BPF program handling e.g. support for global variables first available for the 5.4 kernel in OpenWrt 21.02.
2. Reduced installation footprint
Previously, most utilities had an unnecessary dependency on `libelf`, which is now removed.
3. Provide "tiny" and "full" variants of `tc`
The `tc-tiny` variant uses a smaller executable, and excludes the eBPF loader to avoid `libelf` and `libbpf` package dependencies.

The series continues with NLS fixes for `iproute2` and related dependencies (#4038), which also impact 21.02. They include:

4. Avoid overlinking `libbpf` with `libintl.so` when NLS is enabled.
Only secondary linking through `libelf` is needed and already present.
5. Fix NLS dependencies of `libbfd` in `binutils`.
Drop unneeded package dependency on `libiconv-full` and add missing link against `libintl.so`.
6. Fix `libbpf` detection when building `iproute` with NLS enabled.
Work around `rpath-link` not being passed to a feature-test compilation.

### Testing:
Compile and run tested on QEMU with malta/mips32be and armvirt/64, for the NLS-disabled case.

Compile and run tested on QEMU with malta/mips32be, with `glibc` and `musl`  as standard C libraries, for the NLS-enabled case.

All `iproute2`, `bpftools`, and `binutils` packages were built and installed to a test image. Some regression testing using `ip`, `tc`, and `bpftool` was successfully performed to exercise several kmods, tc modules, and simple BPF programs. Changes to packages and dependencies were also verified.

### Distribution:
@RussellSenior is the `iproute2` package maintainer and @nbd168 maintains the `binutils` package. Both reviewed changes in the original PRs, as did @rsalvaterra and @neheb . 

@hauke reviewed and merged all the original PRs.

### CODE REVIEW

**Comment by guidosarducci** [comment]
FYI, I put this on pause to address an NLS problem [reported on the ML](https://lists.openwrt.org/pipermail/openwrt-devel/2021-March/034487.html), which also highlighted some other NLS-related issues while investigating. I'll make a PR for these shortly.

**Comment by guidosarducci** [comment]
The NLS fix for iproute2 in #4038 doesn't directly affect this PR, and can be back-ported separately after review/merging.

Therefore unpausing this PR.

**Comment by guidosarducci** [comment]
> Therefore unpausing this PR. @adschm Could you drop the "WIP" tag please?

@adschm ping?

**Comment by guidosarducci** [comment]
The fixes merged in #4038 affect `iproute2` and also impact 21.02, so appending those 3 commits to this PR for backporting. Retested on 21.02 with NLS enabled, using both glibc and musl libs under QEMU/malta/be32.

**Comment by hauke** [comment]
Thank you for the pull request, I merged it into openwrt 21.02 branch.

**Comment by guidosarducci** [comment]
@hauke Thanks, Hauke.  I had asked about another potential backport a couple weeks ago in https://github.com/openwrt/openwrt/commit/6b2bcd2597688484007349243ac4cd835b2a5cd2#commitcomment-48872558. The relevant commit 24737d85e8cadb6062cff556b7fae29265f326e8 is also applicable to 21.02.

Can we backport that? Alternatively, the same fix is also present in an update to `bpftools 5.11.13` which I'm about to PR, but I don't know if we have time before a 21.02-rc1 release comes out. What do you think is best?

**Pull request closed without merging**
