### PR TITLE
kernel: enable (ARM|ARM64)_MODULE_PLTS in generic config

### PR DESCRIPTION
**Pull request by guidosarducci**
This allows loading modules with large memory requirements, recently needed while testing on armvirt/32. Past forum discussions \[1\] and bug reports \[2\] also raised this and the ipq806x target already set it in response [3]. Given this increases kernel image size by only ~1KB, is generally useful on multi-platform kernels, and enabled by default on upstream arm32 Linux, add it to the generic config.

The setting has similar utility on arm64, is a requirement for KASLR, and already enabled on most OpenWrt aarch64 targets, so pull this into the top-level generic config.

\[1\]: https://forum.openwrt.org/t/vmap-allocation-for-size-442368-failed-use-vmalloc-size-to-increase-size/34545/7
\[2\]: https://github.com/openwrt/openwrt/issues/8282
[3]: f81e148eb6 ("ipq806x: update 4.19 kernel config").

Pinging @Ansuel  and @ynezz who made the related previous fix for ipq806x, as well as @hauke and @graysky2 with previous maintenance work on ARM config settings. Thanks all !

### CODE REVIEW

**Comment by Ansuel** [comment]
@guidosarducci can you by chance refresh this also accounting 6.1?

**Comment by guidosarducci** [comment]
@Ansuel OK, I've rebased this and included the 6.1 changes too.

**Comment by guidosarducci** [comment]
@Ansuel OK, rebased now.

**Comment by Ansuel** [comment]
@guidosarducci sad a new commit got pushed :( can you rebase again... sorry....

**Comment by guidosarducci** [comment]
@Ansuel Done... I'm getting dizzy soon.

**Comment by guidosarducci** [comment]
@Ansuel Thanks! Could we backport this as well? Was meant to be in 23.05 too.

**Pull request merged**
