### PR TITLE
kernel: bump 5.15 to 5.15.89

### PR DESCRIPTION
**Pull request by graysky2**
Removed upstreamed:
  ipq806x/patches-5.15/007-v6.3-ASoC-qcom-lpass-cpu-Fix-fallback-SD-line-index-handl.patch[1]

1. https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.89&id=d4fa65960a9d0cb87a1102d47145675ceed7a4e6

All other patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B, filogic/xiaomi_redmi-router-ax6000-ubootmod
Run-tested: bcm2711/RPi4B, filogic/xiaomi_redmi-router-ax6000-ubootmod

Signed-off-by: John Audia <therealgraysky@proton.me>

### CODE REVIEW

**Comment by Ansuel** [comment]
@graysky2 it was reported that a patch got merged. Can you rebase this on top of master so we can retest this with latest changes?

**Comment by graysky2** [comment]
@Ansuel - done

**Comment by hauke** [comment]
That patch was added in c20915e8414c02cff24b9938944c63862176d2c2.

**Comment by Ansuel** [comment]
@graysky2 yes it was pointed out that a patch got backported and should be dropped on this kernel bump

**Comment by graysky2** [comment]
I realized that I routinely violate the 75 character limit mentioned [here](https://openwrt.org/submitting-patches)... what is recommended for showing a URL like in my current commit message?  Break the URL up?

**Comment by Ansuel** [comment]
@graysky2 everything used in the form 

```
I used something here [1]

[1] https://link.lol/something
```

bypass the char limit... That only apply for title and commit description. Tag and other have the limit relaxed.

**Comment by graysky2** [comment]
Is what I currently have covered under the "relaxed" bit?

**Comment by Ansuel** [comment]
Yep it's ok

**Pull request merged**
