### PR TITLE
WIP: kernel: Backport mvneta crash fix to 5.15

### PR DESCRIPTION
**Pull request by elkablo**
Backport Russell King's series [1]
  net: mvneta: reduce size of TSO header allocation
to pending-5.15 to fix random crashes on Turris Omnia.

This also backports two patches that are dependencies to this series:
  net: mvneta: Delete unused variable
  net: mvneta: fix potential double-frees in mvneta_txq_sw_deinit()

[1] https://lore.kernel.org/netdev/ZCsbJ4nG+So%2Fn9qY@shell.armlinux.org.uk/

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by BKPepe** [comment]
It would be nice to have confirmation from the user (@AreYouLoco), who reported this issue on [Turris forum](https://forum.turris.cz/t/random-kernel-exceptions-on-hbl-tos-7-0/18865/8) that the patch series fix it.

**Comment by BKPepe** [comment]
That's possible, but in the PR it was not said anywhere why it is WIP and what needs to be addressed.

**Comment by zaventh** [comment]
I would be able to test this on an `mvebu` target when ready. In snapshot builds I am seeing e.g.

> [36298.173752] mvneta f1070000.ethernet eth0: bad rx status 0cc30000 (overrun error), size=680

I assume that message is related to this issue.

**Comment by AreYouLoco** [comment]
> It would be nice to have confirmation from the user (@AreYouLoco), who reported this issue on [Turris forum](https://forum.turris.cz/t/random-kernel-exceptions-on-hbl-tos-7-0/18865/8) that the patch series fix it.

I am testing now. So far (3 days uptime) i encountered no problem. But it was more like random there was no sequence. Sometimes it was 2 days sometimes i got 2 weeks uptime without problems. I will ran test version for 2-3 weeks and if I cannot reproduce it we consider it fixed.

**Comment by elkablo** [comment]
@AreYouLoco thank you for this testing :)

**Comment by AreYouLoco** [comment]
> @AreYouLoco thank you for this testing :)

So I have uptime 9 days and I didn't look at the logs until now because I have network connectivity but I observed this:

```
466980.081747] mvneta f1034000.ethernet eth2: Link is Down
[466980.087095] sfp sfp: module transmit fault indicated
[466981.408065] sfp sfp: module transmit fault recovered
[466981.413171] mvneta f1034000.ethernet eth2: Link is Up - 1Gbps/Full - flow control rx/tx
[466983.338237] mvneta f1034000.ethernet eth2: Link is Down
[466983.352288] mvneta f1034000.ethernet eth2: configuring for inband/1000base-x link mode
[466983.397962] mvneta f1034000.ethernet eth2: Link is Up - 1Gbps/Full - flow control rx/tx
[466983.407495] IPv6: ADDRCONF(NETDEV_CHANGE): eth2: link becomes ready
[466983.414197] IPv6: ADDRCONF(NETDEV_CHANGE): eth2.101: link becomes ready
[466984.432772] mvneta f1034000.ethernet eth2: Link is Down
[466984.450931] mvneta f1034000.ethernet eth2: configuring for inband/1000base-x link mode
[466984.494929] mvneta f1034000.ethernet eth2: Link is Up - 1Gbps/Full - flow control rx/tx
[466984.507300] IPv6: ADDRCONF(NETDEV_CHANGE): eth2: link becomes ready
[466984.514025] IPv6: ADDRCONF(NETDEV_CHANGE): eth2.101: link becomes ready
[466985.552627] mvneta f1034000.ethernet eth2: Link is Down
[466985.565521] mvneta f1034000.ethernet eth2: configuring for inband/1000base-x link mode
[466985.608925] mvneta f1034000.ethernet eth2: Link is Up - 1Gbps/Full - flow control rx/tx
[466985.617082] IPv6: ADDRCONF(NETDEV_CHANGE): eth2: link becomes ready
[466985.623797] IPv6: ADDRCONF(NETDEV_CHANGE): eth2.101: link becomes ready
[466986.662362] mvneta f1034000.ethernet eth2: Link is Down
```

So it seems like its not crashing anymore because I have connectivity bu something is still causing interface to go flapping between up/down.

**Comment by zaventh** [comment]
I have also been testing this for several now and have not had the issue reappear since. I rebased the branch onto cf8d861978dbfdb572a25db460db464b50d9e809 however so my kernel is `5.15.109`. I don't see any issues related to the switch in `dmesg` but I also using a fairly straightforward configuration without VLANs or IP6.

**Comment by rmk92** [comment]
If the SFP cage uses GPIOs for the signals with interrupts, check /proc/interrupts to see whether the LOS signal is flapping. What SFP module are you using?

**Comment by AreYouLoco** [comment]
> If the SFP cage uses GPIOs for the signals with interrupts, check /proc/interrupts to see whether the LOS signal is flapping. What SFP module are you using?

I am using HALNy HL-GSFP GPON Stick: 
```
root@router:~# cat /proc/interrupts  | grep sfp
 93:          0          0    8-0071   4 Edge      sfp-mod-def0
 94:          0          0    8-0071   3 Edge      sfp-los
 95:          0          0    8-0071   0 Edge      sfp-tx-fault
```

**Comment by AreYouLoco** [comment]
So I still experience disconnects but at least its not crashing anymore. Last up/down was more or less 2 days ago (uptime 10days)

**Comment by rmk92** [comment]
> ```
> root@router:~# cat /proc/interrupts | grep sfp
>  93:          0          0    8-0071   4 Edge      sfp-mod-def0
>  94:          0          0    8-0071   3 Edge      sfp-los
>  95:          0          0    8-0071   0 Edge      sfp-tx-fault
> ```
> 
> I was thinking that it's on providers side but if there is no interrupts on LOS that doesn't seem like, right?

That's correct. From what I remember of the original report, the kernel warning was produced because a userspace program (check what was in the Comm: field) was repeatedly bringing the interface down and then back up - which was causing mvneta to release its large memory allocation, and then re-request it. Over time, the system memory became fragmented and then the re-request would fail, causing the warning. I believe I did point that out on the Turris forum and raised the question about why this was happening.

So these link losses seem to be a consequence of the userspace program doing that. I can't comment on why it would do that, that's a matter for others to research.

**Comment by AreYouLoco** [comment]
Thanks @rmk92 for patches I have now uptime of 12 days and didn't have to reboot to restore connectivity so it seems like your patches fix the after-symptoms. Consider it my positive review. Now I will continue with Turris guys to diagnose why netifd is going bananaz time to time.

**Comment by chunkeey** [comment]
feedback is overwhelmingly positive. Even it doesn't fix it 100%. Merged Thanks!

**Pull request closed without merging**
