### PR TITLE
wolfssl: fix validating new Let's Encrypt certificates

### PR DESCRIPTION
**Pull request by dhewg**
Build with WOLFSSL_ALT_CERT_CHAINS:
```
Alternate certification chains, as oppossed to requiring full chain validataion.
Certificate validation behavior is relaxed, similar to openssl and
browsers. Only the peer certificate must validate to a trusted
certificate. Without this, all certificates sent by a peer must be
used in the trust chain or the connection will be rejected.
```
This fixes e.g. uclient-fetch and curl connecting to servers using a Let's Encrypt certificate which are cross-signed by the now expired DST Root CA X3, see [0].

This is the recommended solution from upstream [1].

The overall binary size increases by ~4.3kb.

Draft as:
* ~~it's not yet clear what exactly the implications of WOLFSSL_ALT_CERT_CHAINS are~~
* ~~does the change now require ca-bundle for the library itself (curl already has a dependency on it)~~

[0] https://github.com/openwrt/packages/issues/16674
[1] https://github.com/wolfSSL/wolfssl/issues/4443#issuecomment-934926793

### CODE REVIEW

**Comment by dhewg** [comment]
@kabuobeid
As you're the expert, could you clarify the 2 open questions please? Just to make sure we're getting it right as this is security critical

**Comment by orangepizza** [comment]
not really related but why would reproducible-build option shrink binary by 8kb?

**Review by cotequeiroz — APPROVED** [review]
The reproducible build size decrease was a great catch!
I had overlooked that configure change.

**Comment by cotequeiroz** [comment]
> does the change now require ca-bundle for the library itself (curl already has a dependency on it)

I don't think it is appropriate for the library itself.  There are use cases that do not require certificate validation at all.  User packages should have the dependency, just like curl does.

**Comment by dhewg** [comment]
> I don't think it is appropriate for the library itself. There are use cases that do not require certificate validation at all. User packages should have the dependency, just like curl does.

Agreed, I just wasn't sure if that new option adds that dependency by itself

About the flag itself, sounds like this is the way to go:
https://github.com/wolfSSL/wolfssl/issues/4443#issuecomment-936406022

**Comment by aparcar** [comment]
Can we backport that?

**Comment by dhewg** [comment]
Additionally, not directly related to the issue at hand, but I think it's a good idea to enable ecc25519 by default, see
https://github.com/openwrt/packages/issues/16674#issuecomment-934983898
https://github.com/openwrt/packages/files/7271181/0001-wolfssl-enable-ecc-curve-25519-support-by-default.patch.txt

**Comment by aparcar** [comment]
> Is it really required for the latter?

I don't think 19.07 uses wolfssl per default so less impact, but it's still trouble. The size impact however looks a bit troubling for a backport.

**Comment by orangepizza** [comment]
default tls lib for that was mbedtls so.. no?

**Comment by MoetaYuko** [comment]
Hello, may I know the shipping blocker of this PR? If the increased binary size is the major concern for 19.07 backport,  can we land this PR for 21.04 and snapshot first to unlock "half of the Internet" and postpone the decision for 19.07 later?

**Review by orangepizza — APPROVED** [review]
suprised it need 6 approving reviews. - maybe make it a patch and post it on mailing list?

**Comment by blocktrron** [comment]
I've backported the alternative-chain patch already. I'd refrain from backporting the other changes, as i do not see them as necessary for operation.

**Pull request closed without merging**
