### PR TITLE
apk: update to Git HEAD (2024-11-30)

### PR DESCRIPTION
**Pull request by robimarko**
```
3da6c104f0f5 database: use APK_DB_LAYER_ROOT in more places 5437e3abada1 audit: add usr/lib/apk to the list of protected paths under --full de9baf912245 change default db location to /usr, but detect and use /lib if exists 218fdaa1a1a2 context: close root_fd on free
d33294236cb4 database: add support for only-when-modified trigger paths 36935db0ef3b package: fix memfd_create warnings on Linux kernels < 6.7 1c3fc36051a3 blob: add and use apk_blob_trim_{start,end} af5f9e3f93b0 pkg: fix v3 package size setting to installeddb 9428e34694c8 version: allow --check and --test to work without database 4b4add5326a8 test: fix unit test registration function to be unique eac18cb200d4 test: add testlib.sh for user tests
20dae205b006 mkpkg: fix creation of package with hardlinks 7bdecdca6a95 pkg: only allow tags in world and some commands 76de228bcc0b commit: show tags of world constrains 9a1b1cf68420 test: use testlib for solver.sh
99fc2a2a5efc test: remove dependency on GNU tar
6927746b9a10 Revert usrmerge/LFS related changes to apk used paths 5d287a9b06e9 apk-tools-3.0.0_pre5
8d93a79fb895 mkpkg: fix hardlink on big-endian system
```

Mainly for fixing the `memfd_create` warning

### CODE REVIEW

**Comment by neheb** [comment]
https://github.com/openwrt/packages/issues/25456

**Comment by neheb** [comment]
https://gitlab.alpinelinux.org/alpine/apk-tools/-/merge_requests/258

it'll probably get rejected.

**Comment by robimarko** [comment]
@neheb That is nice catch, I will merge this in the mean-time

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Pull request merged**
