### PR TITLE
Update e2fsprogs to 1.44.1

### PR DESCRIPTION
**Pull request by p-wassi**
@jow- 

These commits update e2fsprogs to 1.43.9 (bugfix release) and/or 1.44.0 (feature and bugfix release)
Should I squash them to skip 1.43.9?

Both are compile and run-tested on kirkwood (all programs/utilities)

Release notes can be found at [1]

[1]:
http://e2fsprogs.sourceforge.net/e2fsprogs-release.html#1.44.0

### CODE REVIEW

**Comment by p-wassi** [comment]
Squashed.
I'm planning to also update util-linux soon. Again, should I directly go to the
newest version in one commit? (As long as it's a reasonable amount to review)

**Comment by neheb** [comment]
@p-wassi https://github.com/neheb/source/commit/e8a45c9af75f7d676b89277b5abd975fca67b7fd

**Comment by p-wassi** [comment]
Hi @neheb 
thanks for the input. To be honest, I do not understand what I see there.
That's a commit which seems to be done through a PR. But I don't see it
updated in any branch, nor is there a PR.
Anyway, there's 2.32 and I think, there's a new dependency to add for wipefs
(as well as a bit of patch refreshing)
Can you have a look at #818 and see, whether the described 'bug' also occurs on
your platforms/targets?

**Comment by neheb** [comment]
It was one I cherry picked from a different branch. Never made it in OpenWrt as I didn't submit the patch.

Anyway, since there's a newer version, might as well update to that.

**Comment by p-wassi** [comment]
This is completely OT for e2fsprogs, but to prevent redundant work in the future, let me understand:
Ok, so @diizzyy originally updated to 2.31.1 in his snapshot-20180312 branch.
You @neheb then cherry picked that commit into your lede-source tree (from which you can (not)
do PRs against openwrt/openwrt?)
Did any of you (plan to) submit a patch or PR for this, or how would I find such situations?
I checked the open PR on openwrt/openwrt before and thought "Ok, there's no PR already
pending, so let's open one"

**Comment by diizzyy** [comment]
@p-wassi 
Yeah, there's a typo in that commit and I didn't bother as I don't plan to upstream myself but if you want to submit any of my commits feel free to do so. @tapper82 and @neheb have asked about about it and I gave them the same response.

**Comment by neheb** [comment]
.1 release is out.

**Comment by p-wassi** [comment]
Thanks - updated and tested on kirkwood.

**Comment by diizzyy** [comment]
@p-wassi 
Please bump the version in ./tools while at it

**Comment by p-wassi** [comment]
Thanks @diizzyy for the hint. Also bumped the tools' e2fsprogs and compile-tested.
(In the same commit - should they be seperated?)

**Comment by diizzyy** [comment]
In the past I did separate pull reqs but they were always committed at the same time as far as I remember so just do a separate commit.

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master.

**Pull request closed without merging**
