### PR TITLE
x86: kernel: set NR_CPU to 512

### PR DESCRIPTION
**Pull request by Edgaru089**
The NR_CPU kernel config limits the maximum number of CPUs supported, previously to 8. This makes total sense on hardware-restricted platforms, but not on x86_64, where CPUs with more than 8 cores can be easily acquired and with there are less physical limitations for kernel size.

This commit sets NR_CPU to 64 on x86_64.

See also: https://forum.openwrt.org/t/x86-64-8-cpu-limitation-on-vanilla-release/100946

### CODE REVIEW

**Comment by dangowrt** [comment]
Other than size limitation I can imagine this amy also have some performance hit. Did you run benchmarks (`openssl speed` with parallel execution)? I can also imagine that this value will influence the size of bitfields. Setting `NR_CPUS=64` assumes that no other values need to be represented in order to fit into a 64-bit register. So it'd be interesting to see if there are measurable differences between selecting `NR_CPUS=48` and `NR_CPUS=64` (if so, retry with `56`...).

**Comment by Edgaru089** [comment]
Just completed some `openssl speed` benchmarking.

[Original 21.02-rc3](https://gist.github.com/Edgaru089/ef62a46c43ffd55d5da25e0445ae640f)
[21.02-rc3 with NR_CPU=64](https://gist.github.com/Edgaru089/710039372d77c52bd4d3a971fc931c29)

The result shows an about <1% slowdown, well within the margin of error on most benchmarks.

Maybe `openssl speed` is not very system-call intensive, and changes on bitsets does not affect cryptographic performance a lot.

**Comment by dhewg** [comment]
Just for the record, on debian:
```
$ fgrep NR_CPUS /boot/config-5.10.0-8-amd64 
CONFIG_NR_CPUS_RANGE_BEGIN=8192
CONFIG_NR_CPUS_RANGE_END=8192
CONFIG_NR_CPUS_DEFAULT=8192
CONFIG_NR_CPUS=8192
```

So maybe bump it even more while at it?

**Comment by Edgaru089** [comment]
> Just for the record, on debian:
> 
> ```
> $ fgrep NR_CPUS /boot/config-5.10.0-8-amd64 
> CONFIG_NR_CPUS_RANGE_BEGIN=8192
> CONFIG_NR_CPUS_RANGE_END=8192
> CONFIG_NR_CPUS_DEFAULT=8192
> CONFIG_NR_CPUS=8192
> ```
> 
> So maybe bump it even more while at it?

The kernel config already has NR_CPUS_DEFAULT=64, for some unknown reason. Reckon that's why I went with the number 64 in the first place.

**Comment by Edgaru089** [comment]
A quote from kernel config help:

> This is purely to save memory: each supported CPU adds about 8KB to the kernel image.

So setting NR_CPUS to 8192 bloats the kernel by about 64MB, which is absolutely an overkill for relatively constrained platforms even for x86_64 OpenWrt.

The number 512 should suffice: even with the CPUs with the most cores, the AMD EPYC 7763 with 64 cores, 128 threads, 2 7763s have 256 threads.

**Comment by Edgaru089** [comment]
`NR_CPUS` is now set to 512.

**Comment by bobafetthotmail** [comment]
> Other than size limitation I can imagine this may also have some performance hit. Did you run benchmarks (`openssl speed` with parallel execution)? I can also imagine that this value will influence the size of bitfields. Setting `NR_CPUS=64` assumes that no other values need to be represented in order to fit into a 64-bit register. So it'd be interesting to see if there are measurable differences between selecting `NR_CPUS=48` and `NR_CPUS=64` (if so, retry with `56`...).

why cpu cores number should influence size of bitfields? aren't all cores supposed to be able to process the same size of data? Just curious.

**Comment by dangowrt** [comment]
> why cpu cores number should influence size of bitfields? aren't all cores supposed to be able to process the same size of data? Just curious.

Imagine interrupt handling or scheduling where the maximum number of
CPUs needs to be taken into account. Whenever you have a per-CPU flag,
the field holding the flags may or may nor fit into a register at once
depending on NR_CPUS. I haven't looked into it in detail, I can just
imagine that it would make a difference for things like interrupt
handling.

**Comment by nicklowe** [comment]
Why not set this to 64 for x86-64?

**Comment by aparcar** [comment]
> Why not set this to 64 for x86-64?

64Bit architecture is something else than the number of CPU cores

**Comment by nicklowe** [comment]
Yes, of course, same question, why not set this to 64 for x86-64 instead?

Do we expect to support x86-64 devices with more than 64 CPU cores in OpenWRT? 64 seems currently the right balance to me, alternatively perhaps use 128.

**Comment by bobafetthotmail** [comment]
>Do we expect to support x86-64 devices with more than 64 CPU cores in OpenWRT?

Do we expect not to? Why not?

The OP is running OpenWrt on server hardware (see the linked forum post), and has estimated 512 based on that a few posts above.

I personally don't see why x86-64 should have any CPU core limit at all. If the only drawback (as implied by the kernel help file) is wasting some MBs of kernel it's a non-issue on this target.

Btw, as another reference point, OpenSUSE Tumbleweed and Leap (the free versions of SLES) set it at 512
CONFIG_NR_CPUS_RANGE_BEGIN=2
CONFIG_NR_CPUS_RANGE_END=512
CONFIG_NR_CPUS_DEFAULT=64
CONFIG_NR_CPUS=512

Ubuntu seems to leave the Debian default of 8192 as above

CentOS/RHEL 6 should have 4096 afaik.

**Comment by bobafetthotmail** [comment]
hmm, it seems default kernel partition (the boot partition) size on x86 is 16Mb and an average kernel and grub2 occupy 5MB. With 512 CPU cores that is bumped up to 9 MB, which still fits.
If we want to go higher it's probably a good idea to bump up the kernel partition size for x86_64 target

https://github.com/openwrt/openwrt/blob/master/config/Config-images.in#L284

```
config TARGET_KERNEL_PARTSIZE
		int "Kernel partition size (in MiB)"
		depends on USES_BOOT_PART
		default 8 if TARGET_apm821xx_sata
		default 64 if TARGET_bcm27xx
		default 16
```

so add a line like this
`default XX if TARGET_x86_64`
above the "default 16"

**Comment by Edgaru089** [comment]
> so add a line like this
> `default XX if TARGET_x86_64`
> above the "default 16"

IMHO that should be done in a separate pull request.

**Comment by aparcar** [comment]
By the way this PR should be for master branch and then backported

**Comment by bobafetthotmail** [comment]
> > so add a line like this
> > `default XX if TARGET_x86_64`
> > above the "default 16"
> 
> IMHO that should be done in a separate pull request.

As I said for the current number 512 this is not needed, I was just documenting this for future expansion and discussion.

If you go higher than 512 you have to enlarge the partition as well or the kernel does not fit anymore.

No matter what you do, you cannot submit a change that breaks the build. So if you want to increase CPU past 512 you need to open another PR where you increase boot partition size, or refactor this PR to have two commits, first commit is increasing boot partition size and second commit increase CPU number.

**Comment by dhewg** [comment]
> With 512 CPU cores that is bumped up to 9 MB, which still fits.

Are you sure? That konfig knob should increase the runtime memory usage, but not the actual size of the binary kernel image. At least by that amount

**Comment by Edgaru089** [comment]
> By the way this PR should be for master branch and then backported

Oh I'm very sorry. Gotta work on it

> > With 512 CPU cores that is bumped up to 9 MB, which still fits.
> 
> Are you sure? That konfig knob should increase the runtime memory usage, but not the actual size of the binary kernel image. At least by that amount

Friendly reminder: remember what people call kernel files before the time of virtual memory? Just `linux`. Then `vmlinux` for supporting virtual memory. And then `vmlinuz` for zipping the kernel because fancy new bootloaders now support loading them.

**Comment by Edgaru089** [comment]
> By the way this PR should be for master branch and then backported

OK. This PR is now for the master branch.

**Comment by bobafetthotmail** [comment]
> > With 512 CPU cores that is bumped up to 9 MB, which still fits.
> 
> Are you sure? That konfig knob should increase the runtime memory usage, but not the actual size of the binary kernel image. At least by that amount

I did not compile this PR, I was reading the kernel help text
```

config NR_CPUS
	int "Maximum number of CPUs" if SMP && !MAXSMP
	range NR_CPUS_RANGE_BEGIN NR_CPUS_RANGE_END
	default NR_CPUS_DEFAULT
	help
	  This allows you to specify the maximum number of CPUs which this
	  kernel will support.  If CPUMASK_OFFSTACK is enabled, the maximum
	  supported value is 8192, otherwise the maximum value is 512.  The
	  minimum value which makes sense is 2.

	  This is purely to save memory: each supported CPU adds about 8KB
	  to the kernel image.
```

It says "kernel image" and that means the actual binary is bigger. And of course it is loaded in RAM so it will use more RAM space.
I do not know how compressible this change is though. Since the kernel is compressed on disk in vmlinuz file, maybe space usage on disk does not increase a lot and increasing boot partition may not be necessary even if you go "all in" with max cores supported, 8192.

@Edgaru089 can you tell us the size of the kernel image (compressed and uncompressed) before and after this change?

**Comment by Edgaru089** [comment]
> @Edgaru089 can you tell us the size of the kernel image (compressed and uncompressed) before and after this change?

```
$ ll vmlinuz*
-rwxrwxrwx 1 edgar edgar  4952736 7   9 15:15 vmlinuz_21.02.0-rc3
-rwxrwxrwx 1 edgar edgar  4956832 7  12 23:48 vmlinuz_master_NR_CPUS-512
```


```
$ extract-vmlinux vmlinuz_21.02.0-rc3        >vmlinux_21.02.0-rc3
$ extract-vmlinux vmlinuz_master_NR_CPUS-512 >vmlinux_master_NR_CPUS-512
$ ll vmlinux*
-rwxrwxrwx 1 edgar edgar 24914128 7  12 23:52 vmlinux_21.02.0-rc3
-rwxrwxrwx 1 edgar edgar 24950992 7  12 23:52 vmlinux_master_NR_CPUS-512
```
So that's about 4KB larger compressed, and **exactly 36KB** uncompressed (should only be a coincidence).

**Comment by aparcar** [comment]
This is fine for me and I'd go ahead to merge it.

**Comment by Edgaru089** [comment]
So, in my understanding, we're now waiting for a OpenWrt member to merge this via his own staging tree at https://git.openwrt.org/openwrt/staging/someone.git?

**Comment by aparcar** [comment]
I'll merge it once I'm at my computer

**Pull request closed without merging**
