### PR TITLE
mvebu: kernel: enable CONFIG_BLK_DEV_NVME

### PR DESCRIPTION
**Pull request by BKPepe**
This is a kernel driver for SSD connected to PCI or PCIe bus [1].
By default, it is enabled for targets "ipq807x", "rockchip/armv8"
and "x86/64".

With miniPCIe adapter, there is a possibility to connect NVMe disk
to Turris Omnia (cortex-a9), Turris MOX (cortex-a53).

- Into Turris Omnia, there fits 60mm NVMe disk

It allows to boot system from NVMe disk, because of that it can not
be kmod package as you can not access the disk to be able to boot from
it.

If you don't like it, I can prepare a variant as a kmod package.

Reference:
[1] https://cateee.net/lkddb/web-lkddb/BLK_DEV_NVME.html

### CODE REVIEW

**Comment by rsalvaterra** [comment]
Unfortunately, not all MVEBU devices have mini-PCIe slots, and there are those which have kernel [size](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=15309f5133d55e92bec3ed91dfb3ac9d124f6a96) [restrictions](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=10415d5e7016b69dc71c5f1b03e8e17b586f8edd). I don't oppose the change _per se_, but this is something we have to keep in mind when proposing changes which effectively increase the size of the kernel image.

**Comment by BKPepe** [comment]
I am aware, but I don't think there is a good solution for every mvebu devices. Many mvebu devices have a large internal storage, so it should not a big deal. There should not be a  large storage difference between enabled/disabled kernel option, but it could be crucial for some devices like you said, though.

**Comment by hauke** [comment]
You could add this to the cortex53 and cortex72 sub target. I think these two have enough space.
How much bytes does this option add?

**Comment by anomeome** [comment]
~28k on a _mamba_ kernel. Build stopped to query about unset kernel configs 2 | 3 times.

**Comment by BKPepe** [comment]
> You could add this to the cortex53 and cortex72 sub target. I think these two have enough space.

I looked at devices supported in sub-target cortex-a72, I need to agree with you, but I don't have any such devices, yet. In the future, I think I will have one. I'm interested to have enabled NVMe support in sub targets: ``cortex-a9 (Turris Omnia)`` and then ``cortex-a53 (Turris MOX)``. For the latter one, there is a follow-up PR, which fixes PCIe support in the aardvark driver for NVMe. 

There are some cases when you want to boot from NVMe disk or mSATA SSD. Especially when in that case, users try to see how many write the flash memory can survive beyond the specification. If you prefer, I can prepare the kernel module package, but for booting it will not be sufficient.

> Build stopped to query about unset kernel configs 2 | 3 times.

Can you try this now? It should work now.

**Comment by BKPepe** [comment]
1. Commit message:
 - kernel size increase thanks @anomeome
 - improve commit message (e.g. add related details about CONFIG_NVME_CORE and its reference)
2. Unset a few kernel options, but ``CONFIG_NVME_HWMON`` will be nice to enable it later, but there are no targets in OpenWrt, who is using it, so let's keep it now without providing temperatures.

**Review by elkablo — APPROVED** [review]

**Comment by chunkeey** [comment]
Merged. Thanks!

**Pull request closed without merging**
