### PR TITLE
kernel: bump 5.15 to 5.15.96

### PR DESCRIPTION
**Pull request by graysky2**
All patches automatically rebased.

Build system: x86_64
Build-tested: bcm2711/RPi4B, filogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3
Run-tested: bcm2711/RPi4B, filogic/xiaomi_redmi-router-ax6000-ubootmod, ramips/tplink_archer-a6-v3

### CODE REVIEW

**Comment by DragonBluep** [comment]
Kernel panic on ramips/mt7620 when Windows client connected. However, there is no problem with my two Android phones and iPad.

AP: Phicomm K2 with pppoe
Client Info:
System: Windows 11 build 22621.1343
NIC: MT7921 with driver 3.3.0.723

```
[  257.978586] ------------[ cut here ]------------
[  257.987882] WARNING: CPU: 0 PID: 4377 at net/core/stream.c:212 inet_csk_destroy_sock+0x6c/0x17c
[  258.005287] Modules linked in: rt2800soc rt2800mmio rt2800lib pppoe ppp_async nft_fib_inet nf_flow_table_ipv6 nf_flow_table_ipv4 nf_flow_table_inet rt2x00soc rt2x00mmio rt2x00lib pppox ppp_generic nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject nft_redir nft_quota nft_objref nft_numgen nft_nat nft_masq nft_log nft_limit nft_hash nft_flow_offload nft_fib_ipv6 nft_fib_ipv4 nft_fib nft_ct nft_counter nft_chain_nat nf_tables nf_nat nf_flow_table nf_conntrack mt76x2e mt76x2_common mt76x02_lib mt76 mac80211 lzo cfg80211 slhc nfnetlink nf_reject_ipv6 nf_reject_ipv4 nf_log_syslog nf_defrag_ipv6 nf_defrag_ipv4 lzo_rle lzo_decompress lzo_compress libcrc32c crc_ccitt compat sha256_generic libsha256 seqiv jitterentropy_rng drbg hmac cmac crypto_acompress leds_gpio gpio_button_hotplug crc32c_generic
[  258.146540] CPU: 0 PID: 4377 Comm: dnsmasq Tainted: G        W         5.15.95 #0
[  258.161475] Stack : 00000000 00000000 80c099dc 80860000 806b0000 80608730 80f19830 806abe23
[  258.178178]         808633b4 00001119 00000003 80061c60 80601eac 00000001 80c09998 84245f1d
[  258.194872]         00000000 00000000 80608730 80c09830 fffff171 00000000 00000000 ffffffea
[  258.211568]         00000000 80c0983c 00000171 806b2278 80860000 00000009 00000000 804651e0
[  258.228273]         00000009 00000003 00000002 00000006 00000018 803347a4 00000000 80860000
[  258.244993]         ...
[  258.249877] Call Trace:
[  258.254737] [<8000700c>] show_stack+0x28/0xf0
[  258.263459] [<8002622c>] __warn+0x9c/0x124
[  258.271649] [<80026310>] warn_slowpath_fmt+0x5c/0xac
[  258.281564] [<804651e0>] inet_csk_destroy_sock+0x6c/0x17c
[  258.292356] [<80479328>] tcp_reset+0x50/0xb0
[  258.300896] [<8047973c>] tcp_validate_incoming+0x3b4/0x624
[  258.311853] [<8047bc48>] tcp_rcv_state_process+0x32c/0xf80
[  258.322810] [<80521fa0>] tcp_v6_do_rcv+0x290/0x4e4
[  258.332400] [<80522da0>] tcp_v6_rcv+0xbac/0xc3c
[  258.341454] [<804e6798>] ip6_protocol_deliver_rcu+0x118/0x640
[  258.352945] [<804e6d6c>] ip6_input+0x84/0x9c
[  258.361477] [<803e224c>] __netif_receive_skb_one_core+0x44/0x54
[  258.373306] [<803e22ac>] netif_receive_skb+0x34/0xc8
[  258.383221] [<8054ba34>] br_handle_frame_finish+0x330/0x5b0
[  258.394362] [<8054c140>] br_handle_frame+0x48c/0x4fc
[  258.404279] [<803dfa30>] __netif_receive_skb_core.constprop.0+0x268/0xc30
[  258.417839] [<803e04e4>] __netif_receive_skb_list_core+0xec/0x224
[  258.430008] [<803e07c0>] netif_receive_skb_list_internal+0x1a4/0x254
[  258.442718] [<81c35b08>] ieee80211_rx_napi+0x84/0x8c [mac80211]
[  258.454881] [<819e07c0>] rt2x00lib_rxdone+0x318/0x940 [rt2x00lib]
[  258.467100] [<819bf08c>] rt2x00mmio_rxdone+0x8c/0xd8 [rt2x00mmio]
[  258.479279] [<819f6df0>] rt2800mmio_rxdone_tasklet+0x18/0xac [rt2800mmio]
[  258.492844] [<800294ec>] tasklet_action_common.constprop.0+0xc0/0xf8
[  258.505545] [<8057742c>] __do_softirq+0x10c/0x2c4
[  258.514934] [<80002950>] except_vec_vi_end+0xb8/0xc4
[  258.524847] [<8013b058>] __do_munmap+0xac/0x54c
[  258.533917] [<8013b55c>] __vm_munmap+0x64/0xd4
[  258.542800] [<8000ea44>] syscall_common+0x34/0x58
[  258.552197] 
[  258.555161] ---[ end trace 5910e4a6b837d518 ]---
[  259.281306] ------------[ cut here ]------------
[  259.290596] WARNING: CPU: 0 PID: 502 at net/core/stream.c:212 inet_csk_destroy_sock+0x6c/0x17c
[  259.307833] Modules linked in: rt2800soc rt2800mmio rt2800lib pppoe ppp_async nft_fib_inet nf_flow_table_ipv6 nf_flow_table_ipv4 nf_flow_table_inet rt2x00soc rt2x00mmio rt2x00lib pppox ppp_generic nft_reject_ipv6 nft_reject_ipv4 nft_reject_inet nft_reject nft_redir nft_quota nft_objref nft_numgen nft_nat nft_masq nft_log nft_limit nft_hash nft_flow_offload nft_fib_ipv6 nft_fib_ipv4 nft_fib nft_ct nft_counter nft_chain_nat nf_tables nf_nat nf_flow_table nf_conntrack mt76x2e mt76x2_common mt76x02_lib mt76 mac80211 lzo cfg80211 slhc nfnetlink nf_reject_ipv6 nf_reject_ipv4 nf_log_syslog nf_defrag_ipv6 nf_defrag_ipv4 lzo_rle lzo_decompress lzo_compress libcrc32c crc_ccitt compat sha256_generic libsha256 seqiv jitterentropy_rng drbg hmac cmac crypto_acompress leds_gpio gpio_button_hotplug crc32c_generic
[  259.449095] CPU: 0 PID: 502 Comm: napi/phy0-3 Tainted: G        W         5.15.95 #0
[  259.464551] Stack : 00000000 00000000 81a21934 80860000 806b0000 80608730 80e38870 806abe23
[  259.481251]         808633b4 000001f6 00000003 80061c60 80601eac 00000001 81a218f0 22ee1ee2
[  259.497945]         00000000 00000000 80608730 81a21788 fffff19a 00000000 00000000 ffffffea
[  259.514639]         00000000 81a21794 0000019a 806b2278 80860000 00000009 00000000 804651e0
[  259.531332]         00000009 00000003 00000002 00000006 00000018 803347a4 00000000 80860000
[  259.548030]         ...
[  259.552907] Call Trace:
[  259.557767] [<8000700c>] show_stack+0x28/0xf0
[  259.566489] [<8002622c>] __warn+0x9c/0x124
[  259.574672] [<80026310>] warn_slowpath_fmt+0x5c/0xac
[  259.584584] [<804651e0>] inet_csk_destroy_sock+0x6c/0x17c
[  259.595374] [<80479328>] tcp_reset+0x50/0xb0
[  259.603909] [<8047973c>] tcp_validate_incoming+0x3b4/0x624
[  259.614861] [<8047bc48>] tcp_rcv_state_process+0x32c/0xf80
[  259.625817] [<80521fa0>] tcp_v6_do_rcv+0x290/0x4e4
[  259.635399] [<80522da0>] tcp_v6_rcv+0xbac/0xc3c
[  259.644451] [<804e6798>] ip6_protocol_deliver_rcu+0x118/0x640
[  259.655939] [<804e6d6c>] ip6_input+0x84/0x9c
[  259.664461] [<803e224c>] __netif_receive_skb_one_core+0x44/0x54
[  259.676289] [<803e22ac>] netif_receive_skb+0x34/0xc8
[  259.686201] [<8054ba34>] br_handle_frame_finish+0x330/0x5b0
[  259.697339] [<8054c140>] br_handle_frame+0x48c/0x4fc
[  259.707255] [<803dfa30>] __netif_receive_skb_core.constprop.0+0x268/0xc30
[  259.720807] [<803e04e4>] __netif_receive_skb_list_core+0xec/0x224
[  259.732979] [<803e07c0>] netif_receive_skb_list_internal+0x1a4/0x254
[  259.745670] [<803e0bf8>] napi_complete_done+0x74/0x214
[  259.755957] [<818f2484>] mt76_dma_rx_poll+0x4b0/0x50c [mt76]
[  259.767307] [<803e0e08>] __napi_poll+0x70/0x1f8
[  259.776358] [<803e1034>] napi_threaded_poll+0xa4/0x110
[  259.786618] [<80045ef0>] kthread+0x140/0x164
[  259.795161] [<80002458>] ret_from_kernel_thread+0x14/0x1c
[  259.805942] 
[  259.808899] ---[ end trace 5910e4a6b837d519 ]---
```
The only custom change related to the kernel is to refresh kernel configs to enable page_pool API. But everything is normal in the 5.15.94 kernel.
```
+ CONFIG_PAGE_POOL=y
```

**Comment by graysky2** [comment]
@DragonBluep - are you certain you want that enabled?  It seems that for the failing build ([mpc85xx/p2020](https://github.com/openwrt/openwrt/actions/runs/4247709823/jobs/7386098262)) the default is disabled.

**Comment by DragonBluep** [comment]
> @DragonBluep - are you certain you want that enabled? It seems that for the failing build ([mpc85xx/p2020](https://github.com/openwrt/openwrt/actions/runs/4247709823/jobs/7386098262)) the default is disabled.

If I'm not wrong, the `mt76` driver needs `PAGE_POOL` API. But I'm not sure whether we need to explicitly enable it in the kernel config file.
My original changes: https://github.com/DragonBluep/openwrt/commit/acaf51391020ac74ce1e0aa404029903a51ba102
https://github.com/openwrt/openwrt/blob/b4ae914037e0ce900be53525c7058543e1ff9d64/package/kernel/mt76/Makefile#L39-L45


About kernel panic, I believe that that some upstream changes broken it. This kernel bump can be merged since it only affects a small part of the hardware. If it is still broken in 5.15.96 or 5.15.97, I will try to track it.

**Comment by schm0** [comment]
I have this kernel panic on x86 too.

**Comment by DragonBluep** [comment]
I guess the kernel panic is related to ipv6 (dhcpv6), because Windows and Android have different ipv6 modes. Disabling IPv6 may avoid it (I haven't tested it yet).

**Comment by hauke** [comment]
I do not want to merge it as long as we see these kernel OOPS on multiple platforms. Did someone report this upstream? Did someone try to remove most of our patches and checked if this also happens without all the OpenWrt patches and backports?

**Comment by DragonBluep** [comment]
Revert this commit can solve the ipv6 issue:
[dccp/tcp: Avoid negative sk_forward_alloc by ipv6_pinfo.pktoptions.](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.96&id=59e30d2bd3094bec9398372a83067c8a778365aa)

**Comment by graysky2** [comment]
Is this reported upstream?  Do we want to ship a revert patch (in this PR)?

**Comment by DragonBluep** [comment]
> Is this reported upstream?

Not yet. I'm not familiar working with the mailing list. Can you help to report it? Many thanks.

> Do we want to ship a revert patch (in this PR)?

If it can be fixed quickly, I think we can just wait for the next release 5.15.97.

**Comment by DragonBluep** [comment]
Friendly ping @schm0. This revert patch should work for us.
[999-revert-Avoid-negative-sk_forward_alloc-by-ipv6_pinfo-pktoptions.patch](https://github.com/openwrt/openwrt/files/10833563/999-revert-Avoid-negative-sk_forward_alloc-by-ipv6_pinfo-pktoptions.patch)

**Comment by schm0** [comment]
> Friendly ping @schm0. This revert patch should work for us. [999-revert-Avoid-negative-sk_forward_alloc-by-ipv6_pinfo-pktoptions.patch](https://github.com/openwrt/openwrt/files/10833563/999-revert-Avoid-negative-sk_forward_alloc-by-ipv6_pinfo-pktoptions.patch)

Thanks, seems to work fine.

**Comment by hauke** [comment]
I send a mail to the author of this patch and added @DragonBluep  into CC. I hope they have an idea what is wrong.

**Comment by hauke** [comment]
I got a very fast answer for the author of the patch, see: https://lore.kernel.org/netdev/CANn89iLYARLgLrwAMFEHr7g9M1GE7JUfi8OR0yowfwGBqZXtKg@mail.gmail.com/T/#m4abc921805c5053fd88d92f30a45408cc10f993d

The following patch is needed in addition: https://lore.kernel.org/netdev/20230210002202.81442-3-kuniyu@amazon.com/
Could you please add it to the kernel 5.15 update as a backport.

**Comment by hauke** [comment]
Here is the version which should get backported: https://lore.kernel.org/stable/20230227211548.13923-1-kuniyu@amazon.com/T/#u Please add it to the kernel 5.15.95 update.

**Comment by graysky2** [comment]
What is the right way to extract the patches from those link?  I just copy/pasted into a file.

**Comment by hauke** [comment]
I did it in this was in my Linux clone:
````
hauke@hauke-t480:~/linux/linux-next-clean$ git checkout v5.15.95 
Previous HEAD position was d383d0f28eca Linux 5.15.96
HEAD is now at 60b502b3ffea Linux 5.15.95
hauke@hauke-t480:~/linux/linux-next-clean$ wget https://lore.kernel.org/stable/20230227211548.13923-1-kuniyu@amazon.com/raw
--2023-02-27 23:12:21--  https://lore.kernel.org/stable/20230227211548.13923-1-kuniyu@amazon.com/raw
Resolving lore.kernel.org (lore.kernel.org)... 2604:1380:4601:e00::1, 145.40.68.75
Connecting to lore.kernel.org (lore.kernel.org)|2604:1380:4601:e00::1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7979 (7.8K) [text/plain]
Saving to: ‘raw’

raw                                                                    100%[==========================================================================================================================================================================>]   7.79K  --.-KB/s    in 0s      

2023-02-27 23:12:21 (45.6 MB/s) - ‘raw’ saved [7979/7979]

hauke@hauke-t480:~/linux/linux-next-clean$ git am raw
Applying: net: Remove WARN_ON_ONCE(sk->sk_forward_alloc) from sk_stream_kill_queues().
hauke@hauke-t480:~/linux/linux-next-clean$ git format-patch HEAD -1 
0001-net-Remove-WARN_ON_ONCE-sk-sk_forward_alloc-from-sk_.patch
hauke@hauke-t480:~/linux/linux-next-clean$ less 0001-net-Remove-WARN_ON_ONCE-sk-sk_forward_alloc-from-sk_.patch 
````

**Comment by graysky2** [comment]
Thanks for the walk-though, @hauke, very helpful.

You mentioned two patches, does that mean I need to repeat that process for this target as well `https://lore.kernel.org/netdev/20230210002202.81442-3-kuniyu@amazon.com/raw`

**Comment by hauke** [comment]
> Thanks for the walk-though, @hauke, very helpful.
> 
> You mentioned two patches, does that mean I need to repeat that process for this target as well `https://lore.kernel.org/netdev/20230210002202.81442-3-kuniyu@amazon.com/raw`

No it is the same patch. The version which Kuniyuki send to stable is a little bit different from the version which got into mainline Linux because something else was already changed. Your change looks good.

**Comment by DragonBluep** [comment]
My router has been running normally for several hours. Confirm that this patch fixes the problem. Thanks.

**Comment by rmandrad** [comment]
> I got a very fast answer for the author of the patch, see: https://lore.kernel.org/netdev/CANn89iLYARLgLrwAMFEHr7g9M1GE7JUfi8OR0yowfwGBqZXtKg@mail.gmail.com/T/#m4abc921805c5053fd88d92f30a45408cc10f993d
> 
> The following patch is needed in addition: https://lore.kernel.org/netdev/20230210002202.81442-3-kuniyu@amazon.com/ Could you please add it to the kernel 5.15 update as a backport.

don't tell @torvalds ...whoever merged this one messed big sh#t! who hasn't done it though !

**Comment by hauke** [comment]
Sorry I pushed the wrong branch into yours.

I merged these changes into master in de8d5b50e2a300136c6d3c87d68955ce69cdee35 and 736257141f7e2b4cc13c3fe297ecca0b21bcea4b manually.

@rmandrad Linus tree is fine. The problem was that only one of these patches was backported into Greg's stable tree. 
Maybe you can blame this on the Microsoft AI ;-) https://lwn.net/Articles/764647/

**Pull request closed without merging**
