### PR TITLE
lantiq: update to kernel 4.19 [request for testing]

### PR DESCRIPTION
**Pull request by xdarklight**
This updates the lantiq target to kernel 4.19

It is based on the work from @hauke 
- I "stole" his generic patch update
- then I added "0002-lantiq_etop-pass-struct-device-to-DMA-API-functions.patch" because I believe it's required on danube / ase / arx100 boards (but I can't test this myself due to lack of hardware)
- then I found out that USB is not working so I added "0003-usb-dwc2-use-a-longer-AHB-idle-timeout-in-dwc2_core_.patch" which is a pending upstream patch
- neither PCI nor PCIe was working so I had to add a hack to "0001-MIPS-lantiq-add-pcie-driver.patch"

This pull request is being created while I am connected (via 5GHz wifi) to my BT Home Hub 5A. my internet connection (VDSL2 with vectoring) is managed by the same device and also seems to work fine (he says after <10 minutes uptime).

I am fine with the last patch ("lantiq: switch to kernel 4.19") not being merged yet.

-----

REQUEST FOR TESTING (**only for devices with serial connection)**:
- DON'T try this if you don't have a serial console hooked up to your device
- DON'T expect this to work
- please try this on whichever board you have (preferably with Amazon SE, Danube or ARX100 SoC) and comment with the result
- in case of errors: include the full serial console output in the comment

### CODE REVIEW

**Comment by xdarklight** [comment]
TODOs:
* some special chars in copright holder names in `target/linux/lantiq/patches-4.19/0035-owrt-lantiq-wifi-and-ethernet-eeprom-handling.patch` are looking broken - reported by @hauke 
* store DTS files in "files" instead of "files-4.x" (because 4.14 and 4.19 .dts files are identical) - reported by @rmilecki 
* use the better fix for the PCIe problem from @mkresin  [https://git.openwrt.org/?p=openwrt/staging/mkresin.git;a=commitdiff;h=8bbe77a09d4204cf606a79d79f76e6f192843daf]

**Comment by mkresin** [comment]
I made a diff between your 4.19 bump and the one I worked on. Your 4.19 dts files are missing some changes which the 4.14 ones have:

- e7bd254ed9
- bd3a18bbe433cc53b6f86dd708477f97ac406abc (which is a no op, but that's another topic)
- f3da2ebf90f74aee9b7840e34bff16292be8d712
- f2f7802148f3d070b27f65b169efebfc6bf8286d

On the other had, I still had 0400-Revert-MIPS-smp-mt-Use-CPU-interrupt-controller-IPI-.patch in my tree, while it's fixed upstream.

> then I added "0002-lantiq_etop-pass-struct-device-to-DMA-API-functions.patch" because I believe it's required on danube / ase / arx100 boards (but I can't test this myself due to lack of hardware)

I've danube boards as well as one arx100 board here. What is the patch supposed to fix? What should I look at?

**Comment by xdarklight** [comment]
> I made a diff between your 4.19 bump and the one I worked on. Your 4.19 dts files are missing some changes which the 4.14 ones have:
good catch, thank you!
I will fix that up when I don't copy but rename the files-4.14 directory

> > then I added "0002-lantiq_etop-pass-struct-device-to-DMA-API-functions.patch" because I believe it's required on danube / ase / arx100 boards (but I can't test this myself due to lack of hardware)
> 
> I've danube boards as well as one arx100 board here. What is the patch supposed to fix? What should I look at?
the problem on the xRX200 platform was easy to see because the kernel crashed while probing the Ethernet driver.
this was due to the fact that the DMA API functions now require a non-NULL struct device pointer, but NULL was hardcoded before

please note that I won't be able to work on this until at least Monday.

**Comment by xdarklight** [comment]
I just updated this PR to version 2.
this addresses all issues form my comment from last week.

@mkresin is still testing his improved PCIe fix with boards with only a PCIe wifi card (PCI being disabled)

**Comment by mkresin** [comment]
Tested everything on ar9, different xrx200 and danube boards. Everything works fine.

I'v merge the version from my staging tree.

**Pull request closed without merging**
