### PR TITLE
octeon: add support for Ubiquiti EdgeRouter 6P

### PR DESCRIPTION
**Pull request by dbro**
Ubiquiti EdgeRouter 6P is 6 port router with similar
specifications as the EdgeRouter 4, support for which was added
in commit dd651e54cc5eadba480a56a7d2c18471e560f491

There are five 10/100/1000 Mbps RJ/Copper ports and
one 1000 Mbps SFP port.

SoC: Octeon Cavium 7130 (Cavium 3) at 1000MHz
Memory: 1GiB DDR3
Flash: 2x2M chips with uboots (chainloaded) + 512K eeprom
LEDs: 1x for power status (white/blue, controllable)
  and 6x for ethernet and SFP ports (no control over them)
Buttons: 1x Reset
Serial: 1x RJ45 port on front panel. 115200 baud, 8N1
USB: 1x USB3.0 on front panel
MII: 1x QSGMII from SoC
PHY: 1x Vitesse VSC8504 of which 4 ports are used (phys 4-7)
     1x Vitesse VSC8514 of which 2 ports are used (phys 8-9)

Network port mapping
 - eth0 on device maps to lan0 and phy5
 - eth1 on device maps to lan1 and phy6
 - eth2 on device maps to lan2 and phy7
 - eth3 on device maps to lan3 and phy8
 - eth4 on device maps to lan4 and phy9
 - eth5 (SFP) on device maps to lan5 and phy4

What is not working:
 - There is no port status available before it goes up
 - SFP have no additional status and presented as no different from eth
 - Power-over-ethernet (passive) support has not been tested

How to flash the firmware:
  - copy openwrt-octeon-ubnt_edgerouter-6p-initramfs-kernel.bin and
    openwrt-octeon-ubnt_edgerouter-6p-squashfs-sysupgrade.tar to
    USB flash drive that is formatted to vfat/fat32
  - connect USB flash drive to EdgeRouter 6P front USB port
  - connect serial cable using front RJ45 port (115200 baud, 8N1)
  - connect power to cable to EdgeRouter 6P
  - connect terminal to the console to see uboot boot process
  - interrupt boot by pressing button(s) on your keyboard to log in to the uboot
  - detect usb connected flash drives by typing to the console:
    usb start
  - after drive is detected load initramfs+kernel to the memory by typing:
    fatload usb 0:1 0x20000000 openwrt-octeon-ubnt_edgerouter-6p-initramfs-kernel.bin
  - after initramfs+kernel is loaded to the memory load it by typing:
    bootoctlinux 0 numcores=4 endbootargs mem=0
  - boot process should finish and you will be greeted with console after pressing enter
  - create directory to mount usb flash drive to by typing:
    mkdir /tmp/sda
  - mount flash drive to that directory by typing:
    mount /dev/sda1 /tmp/sda
  - flash firmware to router internal storage by typing:
    sysupgrade /tmp/sda/openwrt-octeon-ubnt_edgerouter-6p-squashfs-sysupgrade.tar
  - device will reboot and after it gets up you will have edgerouter 6p running openwrt

Signed-off-by: Dan Brown <danbrown@gmail.com>

### CODE REVIEW

**Comment by adschm** [comment]
Signed-off-by is missing.

**Comment by adschm** [comment]
> octeon: add new target and support for Ubiquiti EdgeRouter 6P

What's the new target? I'd simply have expected "octeon: add support for Ubiquiti EdgeRouter 6P"

Apart from that, if the DTS file is that similar to the edgerouter-4, one should consider a shared DTSI for both devices.

@damex Has the ER-4 image been submitted to upstream? If yes, upstream should be considered for the DTSI as well ...

**Comment by dbro** [comment]
Thanks for the feedback. This is my first pull request with OpenWRT, so I am trying to following examples when I haven't been able to find the docs. As suggested by the previous comment, I changed the title of the PR and added a "signed-off-by" to its description.

I think there are 4 similar devices made by Ubiquiti: EdgeRouter 4, EdgeRouter 6P, EdgeRouter 12, and EdgeRouter 12P (see [here](https://www.ui.com/edgemax/comparison/) for a high level view comparing them). I have only the 6P in my possession, so I can't test the others myself. If you can point me to an example or docs for how to create a DTSI, I will give it a go.

**Comment by dbro** [comment]
OK, there is a new commit with a DTSI file that collects the information common to the ER-4 and ER-6P. The DTSI contains information for the ER-4, which will be overridden or augmented by the DTS file for the ER-6P.

Adding support for the two other similar devices (ER-12 and ER-12P) might be a small additional amount of work, again thanks to previous commits written by @damex (his DTS file for the ER-12 is [here](https://github.com/damex/openwrt/tree/edgerouter4/target/linux/octeon3/dts)). I did not include that in this commit because I have no way to test the hardware myself.

**Comment by RaylynnKnight** [comment]
Perhaps remove the 4-6p from the DTSI file as the 12 and 12P will also likely share the same DTSI.

**Comment by damex** [comment]
> @damex Has the ER-4 image been submitted to upstream? If yes, upstream should be considered for the DTSI as well ...

no.

> Perhaps remove the 4-6p from the DTSI file as the 12 and 12P will also likely share the same DTSI.

not likely but they do share same dts.

base variant is e300. or edgerouter 4 (most basic one, other reuse same platoform to build something new).

**Comment by dbro** [comment]
Following the suggestion from @damex the DTSI file has been renamed to "e300"

For the ER-12 and ER-12P I attempted to create a DTS file for that in [another branch](https://github.com/dbro/openwrt/tree/er12), but I cannot test it myself. If you are able to test it, please do so and report back if the ports are working properly.

**Comment by adschm** [comment]
@dbro @damex 

Hi, I've reordered and slightly altered the patches and pushed them here:
https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/er64

Please test on both devices.

@dbro Please tell me whether I can use the Signed-off-by from your top post for these patches (instead of the placeholder I put).

**Comment by dbro** [comment]
Thanks @adschm . That reorganization makes sense. Sure, you can use my name as signed-off-by.

I just tested on the ER-6P device. I tested builds for both the ER-6P and ER-4 and they work as expected. Ports labelled "eth0-3" work in both builds, ports "eth4-5" work only in the build for ER-6P.

I am not able to test on an ER-4 device because I don't have one. Perhaps @damex could help test it?

**Comment by adschm** [comment]
Okay, that should be enough to merge this later.

**Comment by dbro** [comment]
Thanks @adschm.

Should I follow up to create a new wiki page for the EdgeRouter 6P [here](https://openwrt.org/toh/ubiquiti/start), or should I add information to the existing EdgeRouter 4 page there, like what was done with the EdgeRouter X and similar devices?

**Comment by adschm** [comment]
That's a little arbitrary, and depends on what data you want to add there.

Just decide for yourself, your judgement is probably better than mine anyway.

**Comment by RaylynnKnight** [comment]
@dbro The wiki has been moving to separate pages for each device.  So it would be preferred for you to create a new page.

**Comment by cgi2099** [comment]
I know this is old but can someone help with the ER12 DTS file? I have OpenWRT on the device now but only some of the ports work.

**Pull request closed without merging**
