### PR TITLE
[23.05] ipq40xx: whw03v2: enable additional 5 GHz channels

### PR DESCRIPTION
**Pull request by Lanchon**
@robimarko, @Ansuel,

backport of https://github.com/openwrt/openwrt/pull/15056
cherry picked from 1c32cee348f54e9f64b5928ee1a1efe491eec137

thank you!

### CODE REVIEW

**Comment by Ansuel** [comment]
@Lanchon can you drop the extra sob (after the cherry-pick)

**Comment by Lanchon** [comment]
> @Lanchon can you drop the extra sob (after the cherry-pick)

sure, thanks!

**Comment by Ansuel** [comment]
@Lanchon what happen with the 2 extra commit ?

**Comment by Lanchon** [comment]
> @Lanchon what happen with the 2 extra commit ?

it says "[CheWei-Chien](https://github.com/CheWei-Chien) added 2 commits 40 minutes ago".

they are not in my history.

**Comment by Ansuel** [comment]
And it does say that @ynezz committed them...  I'm confused.

**Comment by Ansuel** [comment]
Noooooooo :( why you force pushed.

**Comment by Lanchon** [comment]
> And it does say that @ynezz committed them... I'm confused.

i force pushed my history again. but those commit could maybe expected somewhere else

**Comment by ynezz** [comment]
> And it does say that @ynezz committed them... I'm confused.

Yes, I've committed them, but it seems like the sync between git.openwrt.org -> github.com didn't went through?

**Comment by Ansuel** [comment]
@ynezz for some reason github sync skipped your 2 commits... whatever on the next push the thing is restored anyway

**Pull request merged**
