### PR TITLE
tools/util-linux: build libuuid as PIC

### PR DESCRIPTION
**Pull request by neheb**
Needed to fix users of libuuid.a as autoconf applies PIC to only shared libraries by default.

Found when trying to build python3/host.

Ref: https://github.com/openwrt/packages/pull/24486

### CODE REVIEW

**Comment by neheb** [comment]
I'll note meson builds both as PIC for speed reasons.

**Comment by robimarko** [comment]
@neheb You interested in converting util-linux to meson?

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!

**Comment by neheb** [comment]
meson util-linux ends up building more stuff. Although that might not matter.

**Comment by robimarko** [comment]
Well, that is not really great

**Comment by neheb** [comment]
With -Dauto_features=disabled:

```
mangix/usr
mangix/usr/local
mangix/usr/local/bin
mangix/usr/local/bin/col
mangix/usr/local/bin/colcrt
mangix/usr/local/bin/colrm
mangix/usr/local/bin/rev
mangix/usr/local/bin/choom
mangix/usr/local/bin/flock
mangix/usr/local/bin/isosize
mangix/usr/local/bin/scriptreplay
mangix/usr/local/bin/look
mangix/usr/local/bin/mcookie
mangix/usr/local/bin/namei
mangix/usr/local/bin/whereis
mangix/usr/local/bin/kill
mangix/usr/local/bin/getopt
mangix/usr/local/bin/hardlink
mangix/usr/local/bin/waitpid
mangix/usr/local/bin/exch
mangix/usr/local/sbin
mangix/usr/local/sbin/ctrlaltdel
mangix/usr/local/sbin/mkfs
mangix/usr/local/share
mangix/usr/local/share/doc
mangix/usr/local/share/doc/util-linux
mangix/usr/local/share/doc/util-linux/getopt-example.bash
mangix/usr/local/share/doc/util-linux/getopt-example.tcsh
```

**Comment by robimarko** [comment]
That is still building stuff that we dont need and which will get used instead of the host distro ones so I want to avoid that.

**Comment by neheb** [comment]
Looks like we'll need meson for macOS.

I sent an incomplete draft upstream to figure out how to handle it: https://github.com/util-linux/util-linux/pull/3115

**Comment by robimarko** [comment]
We keep playing whack-a-mole with MacOS pulling tricks with different things breaking selectively on x86 and ARM.

**Pull request merged**
