### PR TITLE
hostapd: update to latest HEAD

### PR DESCRIPTION
**Pull request by blocktrron**
Compile-tested: mediatek-filogic
Run-tested: mediatek-filogic

Patch 180-driver_nl80211-fix-setting-QoS-map-on-secondary-BSSs was replaced by upstream commit

f7f8ea0aa nl80211: Change QoS Map configuration to be per bss, not radio

Git Log
=======
```
ddf026b1c tests: HE AP MBSSID with mixed security (WPA2-Personal + WPA3-Personal)
ab3e679ae MBSSID: Check xrates_supported for all BSSs explicitly
4bfc007b6 MBSSID: Fix Non-Inheritance element encoding
42add3c27 Scan 6 GHz channels after change to 6 GHz-allowed regdom
0b8a67225 Parse 6 GHz capability from driver capabilities
41baf0159 nl80211: Fix uses_6ghz flag
17bdf34c4 Use default IEs in wpa_supplicant_trigger_scan()
ccefa6419 tests: rrm_beacon_req_active_scan_fail to allow implementation change
909361e28 tests: Redesign bgscan_*_scan_failure to work with implementation change
77785da66 tests: WPA3/GCMP-256 connection at Suite B 192-bit level and OKC
aac288914 OKC with Suite B AKMPs in hostapd
0c9df339f OKC with Suite B AKMPs in wpa_supplicant
2bd8887e9 P2P: Pass the known BSSID to the driver to optimize scan time
bffd2b399 nl80211: Skip interface down/up when setting MAC address
9e426e068 Enable IPv6 in wpa_supplicant and eapol_test builds
3d8de6191 dbus: Use proper dbus_bool_t value TRUE instead of 1
03a9a57ac dbus: Add NonColoc6GHz and 6GHzOnly flags in wpa_supplicant scan
e5ea30fee SME: MLD: Handle reconfiguration Multi-Link element
e933c4e5a tests: AP MLD with two links and non-AP MLD sending ML Probe Request
7ea2798c2 Test command for sending ML probe request
de5e01010 wpa_supplicant: Support ML probe request
a12f39ad4 nl80211: Add support for minimal probe request content
c84709c59 hostapd: Output BSS Color (he_bss_color) when using STATUS
11a6ae242 More consistent use of mesh peer connected/disconnected notification
bd37f8615 Fix MESH-PEER-DISCONNECTED message logic on control iface
d986e8702 Respect disable_ht40/disable_vht/disable_he in AP/mesh mode
f7f8ea0aa nl80211: Change QoS Map configuration to be per bss, not radio
67bf89f55 WNM: Choose the best available BSS, not just the first one
fc7e74496 Sync with wireless-next.git include/uapi/linux/nl80211.h
5a96a516a dbus: Report guard interval and dual carrier modulation
3cb51378f Abort ongoing scan on DISCONNECT
5b21f4861 l2_packet_freebsd: Enable receiving priority tagged (VID=0) frames
0aa44ccf8 WNM: Lower rankings of current AP if disassociation imminent bit set
3242793cb P2P: Remove pending p2p-listen radio work on stopping listen
18330d1f6 hostapd: Update op_class after AP channel switching
2563edb8c Use 6 GHz default noise when estimating 6 GHz SNR
7a7339932 ACS: Fix typo in bw_40 frequency array
d01f677c2 tests: hwsim: Add more tracing
d76dbe6c7 tests: ap_mixed_security: Give AP time to set up stations
ee7437658 tests: GAS: Wait for STA before ANQP_GET
3918c4123 tests: ap_open_poll_sta_no_ack: Fix mgmt-rx race
95325f096 tests: ap_pmf: Wait for STA appropriately
b3e3e3b0d tests: pmksa_cache: Wait for STA on AP side before query
b99bb32f5 Don't disconnect on scan_freq update from control interface
dbcaf927c tests: ap_tdls: Wait before connectivity checks
f562fd014 tests: Blocked rekey: Give slightly more time
01afbeaf9 tests: ap_hs20: Add more wait_sta()
0f896ded9 tests: ap_hs20_connect_no_full_match: Add appropriate waits
83c5db6c0 tests: autogo_legacy: Wait for 4-way handshake
7e558095c tests: RRM: Wait for AP STA before requests to AP
4f4923bb0 tests: PASN: Try get_ptksa() from AP a few times
376bead96 tests: persistent_go_client_list: Ignore client order
434d557bc tests: FT/RRM: Wait for STA before check_beacon_req()
257ba3afa tests: Wait for radio work to start after DPP_LISTEN command
1d7ce8e2d tests: Multi-AP backhaul to backhaul+fronthaul BSS
cc5a00800 Ensure WDS is available on combined backhaul and fronthaul APs
1aeeebaa6 defconfig: Remove remaining reference to IEEE80211W symbol
aaeeb631e tests: More thorough testing of PMF and need for association comeback
8477fa7eb Check the need for SA Query earlier in association processing
3d8215aff tests: wpa_supplicant AP with all possible 20 MHz PRI for 80 MHz channel
a6440b57c Update correct VHT/HE/EHT mode in channel switch event
c86064716 Add NULL check for pmksa cache free_cb() callback
97b6cc6e5 tests: VHT80 and channel 161
7df76a4dd tests: EHT+MLO AP with SAE and transition mode
6affbf1fb tests: Remove exception for SAE MLD testing
2f911fb15 SAE: Remove current PMKSA from driver after reauth threshold is passed
2d4be0019 Double the first group rekey timeout if over 100 associated stations
a89cf6ba4 Reserve QCA vendor sub command id 234
1dfcafff3 FILS: EHT additions
26f29ef46 FILS: Fix NSS calculation for HE mode
fcbb643ff FILS: Rename local variable to indicate HE mode
dcf66d2f4 FILS: Move maximum NSS determination to a new function
24e0938b3 FILS: Move phy index determination to new function
015af1bee DPP: Use CONFIG_SAE consistently to avoid a compiler warning
55ea12bb7 AP MLD: Add missing CONFIG_SAE checks
ef8d48c4c Update Wide Bandwidth Channel Switch element
c4c5c991d SAE: Do not reject reauth threshold passed PMKSA in association event
7a9587cee PASN: Copy PMK to PASN context on responder
e59d2a31c hostapd: Fix premature beacon set during association handling
ae928e67a Add channel 144 (5720 MHz) into operating class conversion tables
c80ded25c Refine roam stats frame subtypes in a QCA vendor attribute
ed89ab429 Update roam stats of AP BSSID to user space in a QCA vendor attribute
881cb4198 EAP-SIM/AKA peer: Simplify identity selection for MK derivation
71b26a767 tests: Adding EAP-SIM/AKA coverage for ID selection
ec6acdbb6 EAP-SIM/AKA server: Configurable limit to fast re-authentication
c6268e103 EAP-SIM/AKA server: Allow method specific identity exchange to be skipped
40af6560b EAP-SIM/AKA peer: Fix identity selection for MK derivation with AT_IDENTITY
bc9256980 Define a QCA vendor attribute to set traffic shaping policy
dec5ab645 Add _IS_ML flag attribute to the ADD_STA_NODE QCA vendor command
0d65e27fb Extend maximum allowed bandwidth update type QCA vendor interface
e510a3bad Add QCA vendor attributes to indicate MLO capabilities

```

### CODE REVIEW

**Comment by xback** [comment]
Any chance of bumping it even further?
There are upstream wolfssl patches colliding then with a patch of yours :)

**Comment by danpawlik** [comment]
Works on few devices (just simply roaming)

**Comment by blocktrron** [comment]
@xback I'd like to do this in a follow-up patch. Which patch are you referring to.

**Comment by xback** [comment]
@blocktrron 
I was referring to [this one](https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=package/network/services/hostapd/patches/001-wolfssl-init-RNG-with-ECC-key.patch;h=269dcaac75ce3edb971e4a4cd93ed1c5cd1096a9;hb=HEAD)

I've got a bump to todays state in my staging tree but dropped this patch for now

**Comment by blocktrron** [comment]
@xback I'll check if this patch is still required

**Comment by cotequeiroz** [comment]
The rng issue was handled by hostapd back in April, 2022, with
https://w1.fi/cgit/hostap/commit/?id=d7b8c6eef21ade540e4f34e22cac3bbd15c26483

According to both commit messages, they are fixing the same problem.  So, 001-wolfssl-init-RNG-with-ECC-key.patch could have been dropped a while ago.

BTW, I have an upgrade to current HEAD (https://w1.fi/cgit/hostap/tree/?id=8270afcdeeccd7a5ce904bacf45801a5b3cf4f0e).
It is not a straightforward patch refresh.  I think this one should be merged first, and then we can move forward.  I'll run some tests and then open a draft PR.

**Comment by hauke** [comment]
This was superseded by 24d0e74627bb12305a8b0058af6261f3fd4012bf from  #14620.

**Pull request closed without merging**
