### PR TITLE
ipq40xx: Remove unused reserved-memory nodes

### PR DESCRIPTION
**Pull request by ecsv**
The reserved-memory regions are mostly undocumented by QCA and are named very unspecific in the QSDK device trees. It was tried to clean them up by commit 71ed9f10a33e ("ipq40xx: Use detailed reserved memory for A42") and similar changes.

The features which require these regions were mostly unknown but Senthilkumar N L <snlakshm@qti.qualcomm.com> and Sricharan Ramabadhran <srichara@qti.qualcomm.com> provided some more insight in some of them:

* crash dump feature
  - a couple of regions used when 'qca,scm_restart_reason' dt node has the
    value 'dload_status' not set to 1
    + apps_bl <0x87000000 0x400000>
    + sbl <0x87400000 0x100000>
    + cnss_debug <0x87400000 0x100000>
    + cpu_context_dump <0x87b00000 0x080000>
  - required driver not available in Linux
  - safe to remove
* QSEE app execution
  - region tz_apps <0x87b80000 0x280000>
  - required driver not available in Linux
  - safe to remove
* communication with TZ/QSEE
  - region smem <0x87b80000 0x280000>
  - driver changes not yet upstreamed
  - must not be removed because any access can crash kernel/program
* trustzone (QSEE) private memory
  - region tz <0x87e80000 0x180000>
  - must not be removed because any access can crash kernel/program

Removing the unnecessary regions saves some kilobyte of reserved-memory and
cleans up the device tree:

* 2560 KiB
  - 8devices Jalapeno
  - AVM FRITZ!Box 4040
  - Compex WPJ428
  - Meraki MR33 Access Point
  - OpenMesh A42
* 14336 KiB
  - GL.iNet GL-B1300
  - Qualcomm Technologies, Inc. IPQ40xx/AP-DK01.1-C1

----

This is a result of a longer journey to get some documentation from QCA. We didn't receive any actual document but at least some info from the mentioned developers. I also gave @mkresin @chunkeey  access to parts of the discussion. I hope this is enough to them to understand why I think that tz and smem regions must be protected.

It also looks like Sricharan Ramabadhran will also add some reserved memory regions to the Linux AP-DK devices after I pointed out that some devices don't even boot or also have weird crashes when smem/tz are not marked as reserved memory.

I personally tested it on A42 and WPJ428. Devices which should be tested:

* 8devices Jalapeno: @robimarko 
* AVM FRITZ!Box 4040: @chunkeey 
* Meraki MR33 Access Point: @riptidewave93
* GL.iNet GL-B1300: @handongming
* Qualcomm Technologies, Inc. IPQ40xx/AP-DK01.1-C1: @yeryomin

### CODE REVIEW

**Comment by chunkeey** [comment]
Note: A reserved-memory node can also be declared as "reusable". See [reserved-memory binding](https://www.kernel.org/doc/Documentation/devicetree/bindings/reserved-memory/reserved-memory.txt)

"reusable (optional) - empty property
    - The operating system can use the memory in this region with the
      limitation that the device driver(s) owning the region need to be
      able to reclaim it back. Typically that means that the operating
      system can use that region to store volatile or cached data that
      can be otherwise regenerated or migrated elsewhere."

This could be the best of both worlds.

**Comment by ecsv** [comment]
Hm, this is parameter is new to me. But the description doesn't really sounds like this is what we have here. We don't have any driver for these regions and thus they are currently useless to us. My understanding is now that we would need to have the qcom,scm functionality (+ drivers) to enable the crash feature and to communicate with the TZ.

**Comment by yeryomin** [comment]
@ecsv something is not correct here -- either you have conflicting info in description or the changes are erroneous.
Also I would vote strongly against removing any reserved map from dev boards like ap.dk01.1-c1. It can serve as guideline/example in the world of mysterious crashes.

**Comment by yeryomin** [comment]
@ecsv, how did you test access to the regions?

**Comment by ecsv** [comment]
The reserved-memory changes were now submitted to upstream (<https://patchwork.kernel.org/patch/10347459/>). I've noticed that Linux places the tz and the smem reserved-memory range in the soc dtsi and not in the board specific files. I have therefore imported my Linux patch and removed the duplicated stuff from the board specific files.

**Comment by mkresin** [comment]
merged. thanks!

**Pull request closed without merging**
