### PR TITLE
kernel: kmod-net-rtl8192su module name has changed

### LINKED ISSUE #10164: kmod-net-rtl8192su is empty
Download this file:
https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa9/kmods/5.10.127-1-9016c742c67c216f0c1ec2e815af16d1/kmod-net-rtl8192su_5.10.127-1_arm_cortex-a9_vfpv3-d16.ipk
Try to extract the kernel module. You can't. It's not there. The package is empty.
Other targets have empty kmod-net-rtl8192su too, and it seems that there are other empty packages too. See prism54.

I tried to build that module on my own build system. Same result. The module is not built. The resulting package is empty.

Second bug:
Building should fail, but it does not. It simply constructs an empty package.

Thanks.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #10164.

Signed-off-by: Marius Dinu <m95d+git@psihoexpert.ro>

### CODE REVIEW

**Comment by Ansuel** [comment]
@M95D can you add a commit description about this?
Also does this affect a specific kernel version or is broken on 5.10 too ?

**Comment by M95D** [comment]
This patch is wrong. There is some confusion about the name. RTL8192U is an entirely different driver that cannot be used with RTL8192**S**U devices.

**Comment by Ansuel** [comment]
Don't want to be picky but how did you come up with the change in the first place?

**Comment by M95D** [comment]
I searched the kernel generated .config file for "8712", couldn't find any, not even "is not selected", and I assumed that it doesn't exist anymore. This being a "staging" driver and "CONFIG_R**8712**U" totally unrelated to chip name and package name "kmod-net-rtl**8192**su", I thought that a name change was really likely. So I searched for "r8192", then "rtl8192", and I found CONFIG_RTL8192U.

**Comment by M95D** [comment]
This was a draft pull request. I can't test anything on the router during work days (work from home), but I had the extra time to make a commit and the pull request, so I did. The plan was to submit the pull request for approval after I tested the driver during the weekend. I was not expecting so much feedback so quickly.

**Pull request closed without merging**
