### PR TITLE
ath79/generic: ar8216: add support for mdio-device probing and ath79 builtin switch

### PR DESCRIPTION
**Pull request by 981213**
The builtin switch in ath79 chips are almost the same as the standalone ones supported by ar8216.

This PR adds around 550 lines of code into ar8216 for mdio-device probing and the support for builtin switch and we can drop the 1300 line switch driver in ag71xx while getting more functions like mib counter and arl table.

the original phy probing can't be used because:
1. It has some limitations at cpu port speed. It doesn't support a switch with a 1G CPU port when other ports are 100M.
2. It simply assumes phy0 is never used and report fixed link on it. On AR934x phy0 can be directly connected to CPU GMAC.
3. AR724x builtin switch uses the same chip id as standalone ar8216 while their registers are a little bit different. We need a way to distinguish them.

Tested on:
ath79:
TP-Link TL-WR841N v8 (AR9341)
TP-Link TL-WR841N v9 (QCA9533)
PISEN TS-D084 (AR9331 with 1 port. Tested with and without PHY swap.)
TP-Link TL-WR941N v7 (Chinese version. QCA9558+AR8236)
TP-Link TL-WR941N v4 (AR7240)
TP-Link TL-WDR4900 v2 (QCA9558+AR8327N. Tested with both phy and mdio-device probing.)

ar71xx: (To confirm that it doesn't break on non-OF targets.)
TP-Link TL-WDR4900 v2 (QCA9558+AR8327N)

BTW I have considered the upstream DSA framework but:
1. The datasheet of ar7240/ar933x doesn't say they supports atheros header and I can't find an ar8216 datasheet so I can't confirm whether that header mode is actually supported.
2. The performance of DSA will be a little bit lower since we need to mangle every frame to add/remove the atheros header.
3. DSA have to be registered with a ethernet connected to the CPU port but we only wants the mdio bus in switch on one-port routers and eth1 isn't needed at all.
4. For the same reason above we have to register eth1 before eth0 or probing of eth0 will fail due to phy not accessible.

### CODE REVIEW

**Comment by lucize** [comment]
while at it, can't you split the gigabit switch driver from the other one so tiny target gets only the 100M and save some space, in mind for when qca8k will be available for ath79 ?

**Comment by 981213** [comment]
> while at it, can't you split the gigabit switch driver from the other one so tiny target gets only the 100M and save some space, in mind for when qca8k will be available for ath79 ?

I don't know how to write a registering mechanism for ar8216 to split individual switch supports into separated modules so my attempt will be the same as your previous one, which has been rejected.

**Comment by neheb** [comment]
Tested on an Archer C7v2. Works fine. Ethernet performance seems a little lower. But that could be due to some other change (I'm using several other pull requests in my tree).

My understanding of ath79 is that it is meant to be an upstreamable solution. In that sense, it doesn't make much sense to continue to use swconfig. That being said, I do remember that qca8k needs some work.

**Comment by dangowrt** [comment]
nice work. merge?

**Comment by ynezz** [comment]
I've just tested this PR on `ubnt,bullet-m-xw (ar9342 rev2)` and `tplink,archer-c7-v5 (qca956X ver 1 rev 0)`.

**Comment by ynezz** [comment]
I've just merged this to my https://git.openwrt.org/?p=openwrt/staging/ynezz.git;a=shortlog;h=refs/heads/staging tree, will try to build and run test it again, then push to master once complete. Thanks!

**Pull request closed without merging**
