### PR TITLE
ath79: add support for tl-wdr4900-v2

### PR DESCRIPTION
**Pull request by 981213**

### CODE REVIEW

**Comment by mkresin** [comment]
I don't really like the idea of overwriting single properties defined in a "parent" dtsi. It is of course the best way to prevent duplication and I've done it the same way on my own in the past. But it makes dts files really hard to read and is error prone.

It doesn't look like the archer c7 dtsi is a good match for the tl wdr4900 v2 dts. I would propose to not include the dtsi here and add the missing nodes directly to the tl-wdr4900 dts.

**Comment by 981213** [comment]
Updated.

**Comment by mkresin** [comment]
Merged to [my staging tree](https://git.openwrt.org/?p=openwrt/staging/mkresin.git;a=summary). Will push it to master later the day.

**Comment by adrianschmutzler** [comment]
@981213 I just stumbled over an old bug report concerned with Archer C5/C7 v1/v2 MAC addresses.

Those were fixed based on stock firmware in ath79, but not in ar71xx. I just updated ar71xx in master:
https://github.com/openwrt/openwrt/commit/a021268032fb64afdce7bafa91c7c7bf44fa6ff2

However, in ar71xx WDR4900v2 is also using the same setup as c5/c7, while in ath79 it uses a separate DTS file. In WDR4900v2 DTS however, MAC addresses seems to be based on the "old" setup for C5/C7:

wlan0 (5GHz) : -2
wlan1 (2.4GHz) : -1
eth1 (LAN) : 0
eth0 (WAN) : 1

So, two questions:
1. Can you check the vendor MAC address setup for WDR4900 v2, I'd suspect it to be as follows (matching C5/C7):
wlan0 (5GHz) : -1
wlan1 (2.4GHz) : 0
eth1 (LAN) : 0
eth0 (WAN) : 1
(eth1/eth0 might be swapped in ath79 OpenWrt).

2. I'm inclined to base wdr4900-v2.dts on archer-c7.dtsi, as most of it looks similar. Do you think this would be right from a hardware perspective, and if yes, how would you name the common dtsi (for c5v1/c7v1/c7v2/wdr4900v2...)

**Comment by adrianschmutzler** [comment]
Hi again, I also realized that green and blue are mixed for LED colors, which I do not think will be really the case for the device?

I have created two patches under the assumption that
1. My proposed MAC assignment from previous comment is correct
2. All LEDs are actually green
in my staging tree:

https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/staging

Please confirm those changes or tell me that I'm doing nonsense.

Despite, no matter whether LEDs are green, blue, or mixed, 01_leds does not match the mach file in ar71xx, so USB leds won't work there. I will address that later, too.

**Comment by 981213** [comment]
I remembered that I specifically checked the mac addresses in factory firmware and the mac address used in this PR should be the correct one. Can't double-check it now because I don't have my wdr4900 with me.
International Archer C7 got green LEDs but WDR4900v2 and WDR7500 on Chinese market use blue leds on the front panel (USB leds are on the back and they are green.)
Archer C7 and WDR4900 are almost the same board (except 5G PCIE chip and number of antennas). A shared dtsi was proposed in this PR previously, but it needs to override buttons/led colors/partition tables and unless we override several single properties (which isn't very clear for reading), there aren't too much left in the shared dtsi. I think it should be left as-is.

**Comment by adrianschmutzler** [comment]
Thanks for your fast feedback.

> I remembered that I specifically checked the mac addresses in factory firmware and the mac address used in this PR should be the correct one. Can't double-check it now because I don't have my wdr4900 with me.

Okay, if you checked it back then I'm fine, I just wanted to exclude the case that it was just taken from ar71xx or C7. It's just a little uncommon for TP-Link to use four distinct addresses, so I wanted to reassure. I will then also align ar71xx to that setup, as wdr4900-v2 MAC addresses were never set up correctly there.

> International Archer C7 got green LEDs but WDR4900v2 and WDR7500 on Chinese market use blue leds on the front panel (USB leds are on the back and they are green.)

I see, so ath79 is correct in this aspect, and ar71xx seems wrong again, as there mach-files set up LEDs as green, while 01_leds thinks they are blue. I haven't yet finally made up my mind whether it would be better to fix that in 01_leds or to provide a separate LED definition in the mach file.

> A shared dtsi was proposed in this PR previously, but it needs to override buttons/led colors/partition tables and unless we override several single properties (which isn't very clear for reading), there aren't too much left in the shared dtsi. I think it should be left as-is.

Since LEDs and MAC addresses are different indeed, I think you are right.

One other thing:
In C7 DTS and also in mach files, two buttons (RFKILL and reset) are set up. This device only defines one button in ath79 (reset). Does it only have one?

**Comment by zorun** [comment]
> One other thing:
> In C7 DTS and also in mach files, two buttons (RFKILL and reset) are set up. This device only defines one button in ath79 (reset). Does it only have one?

The Archer C7 v5 has two buttons: "reset", and "WPS / Wi-Fi On/Off".

Using the 19.07.0-rc1 ath79 image, the WPS button seems to work:

    Thu Nov 14 12:35:04 2019 user.notice root: the button was wps and the action was pressed
    Thu Nov 14 12:35:04 2019 user.notice root: the button was wps and the action was released

(using https://openwrt.org/docs/guide-user/hardware/hardware.button#preliminary_steps )

**Comment by blocktrron** [comment]
@adrianschmutzler The LED color will never be right, as TP-Link produced (at least in EU) Archer C7 with blue (very early fabrications) as well as green LEDs. The same also applies for the WDR3600 / WDR4300 / WDR4900.

**Comment by 981213** [comment]
@adrianschmutzler 
It has a single WPS/Reset button. And since reset is more important than WPS I defined it as a reset button.

**Comment by adrianschmutzler** [comment]
@blocktrron Okay, I actually know that from WDR4900v1. Still, in ar71xx there is a mismatch between mach-files and base-files, which I think should be corrected.

@981213 Thanks again for your feedback. So, as it turns out your support is perfectly well :-)
I've updated my staging to address the problems in ar71xx based on that:
https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=shortlog;h=refs/heads/staging
1. Fix MAC address
2. Fix LED color to match the definitions in base-files, remove wlan5g controlled by ath9k
3. Remove setup of RFKILL button

@zorun Thanks for your feedback, but this is only about C7 v1/v2, C7 v4/v5 have a different SoC.

> And since reset is more important than WPS I defined it as a reset button.

That seems to be a general problem:
https://bugs.openwrt.org/index.php?do=details&task_id=839&only_watched=1&type[0]=&sev[0]=&due[0]=&cat[0]=&status[0]=open&percent[0]=&reported[0]=

**Pull request closed without merging**
