### PR TITLE
ar71xx: add support for COMFAST CF-E385AC

### PR DESCRIPTION
**Pull request by fall513**
COMFAST CF-E385AC is a ceiling mount AP with PoE
support, based on Qualcomm/Atheros QCA9558+QCA9984+QCA8337.

Short specification:

- 720/600/200 MHz (CPU/DDR/AHB)
- 1x 10/100/1000 Mbps Ethernet, with PoE support
- 256 MB of RAM (DDR2)
- 16 MB of FLASH
- 3T3R 2.4 GHz,
- 4T4R 5 GHz, wave 2
- 7x internal antennas
- 1x RGB LED, 1x button
- UART (T11), LEDs/GPIO (J7) and USB (T12) headers on PCB
- external watchdog (Pericon Technology PT7A7514)

Flash instruction:

Original firmware is based on OpenWrt.
Use sysupgrade image directly in vendor GUI.

Signed-off-by: Ding Tengfei <dtf@comfast.cn>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://lede-project.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by pepe2k** [comment]
Hi @fall513,

I have ready support for this board in my [staging tree](https://git.openwrt.org/?p=openwrt/staging/pepe2k.git;a=summary), tested on prototype version.

Could you please give it a try and confirm that everything works as expected? Especially, MAC addresses assignment for Ethernet and Wi-Fi interfaces and LAN port (eth0/RGMII) work (your RGMII RX delay values are different).

PS. For next time (I'm really surprised that you made such mistakes in support code for board manufactured by the vendor you seem to work for...):

> 1x 10/100/1000 Mbps Ethernet, with PoE support

Your board has 2 Ethernet ports.

```
+	cf-e385ac|\
	rb-750gl|\
	rb-751g|\
 	rb-951g-2hnd|\
 	rb-962uigs-5hact2hnt|\
 	wlr8100|\
 	wzr-hp-g450h)
 		ucidef_add_switch "switch0" \
 		"0@eth0" "2:lan" "3:lan" "4:lan" "5:lan" "1:wan"
```

This is wrong VLAN configuration for your board.

```
-	archer-c60-v1)
+	archer-c60-v1|\
+	cf-e385ac)
 		ath10kcal_extract "art" 20480 12064
 		ln -sf /lib/firmware/ath10k/pre-cal-pci-0000\:00\:00.0.bin \
 			/lib/firmware/ath10k/QCA9888/hw2.0/board.bin
```

Your board has QCA9984, not QCA9888.

`+	u8 wlan0_mac[ETH_ALEN];`

What do you need this variable for? It's not used in the code.

Cheers,
Piotr

**Comment by fall513** [comment]
Hi @pepe2k ,

> I have ready support for this board in my staging tree, tested on prototype version.

If you have alrealdy added in your staging tree, just ignore this patch and close it.

>  + u8 wlan0_mac[ETH_ALEN];
> What do you need this variable for? It's not used in the code.

This is use for "ath79_register_wmac(art + WMAC_CALDATA_OFFSET, wlan0_mac);".

Best regards

**Comment by pepe2k** [comment]
Hi @fall513,

> If you have alrealdy added in your staging tree, just ignore this patch and close it.

Could you test it and confirm that it's working on production version of your board? Your patch differs in several places.

> This is use for "ath79_register_wmac(art + WMAC_CALDATA_OFFSET, wlan0_mac);".

This line doesn't exist in your code.

Cheers,
Piotr

**Comment by fall513** [comment]
Hi @pepe2k ,

> Could you test it and confirm that it's working on production version of your board? Your patch differs in several places.

I have tested that both mine and yours work fine with my board.

> This line doesn't exist in your code.

Most devices do not initialize wifi with mac address, so I removed it.

Best regards

**Comment by pepe2k** [comment]
Hi @fall513,

> I have tested that both mine and yours work fine with my board.

OK, thank you for the confirmation!

Cheers,
Piotr

**Pull request closed without merging**
