### PR TITLE
RFT: realtek: Fix duplex on rtl83xx

### PR DESCRIPTION
**Pull request by oliv3r**
@svanheule a quick fix on duplexity. Also here, I can't test this. According to the code however, this can't work in its current form, so I'm curious how this is working right now, especially since 1000M doesn't even do half duplex afaik, and we're always executing half-duplex configuration. Could be that the content of that if is reversed however, so forcing half-duplex, works full, and vice versa  ... the register `RTL838X_DUPLEX_MODE` should be 1 in case of full duplex mode however.

### CODE REVIEW

**Comment by oliv3r** [comment]
Don't merge this just yet, there's 1 commit I want to add that I'm getting into upstream first.

**Comment by svanheule** [comment]
> Don't merge this just yet, there's 1 commit I want to add that I'm getting into upstream first.

Do you have a link?

**Comment by oliv3r** [comment]
Sure, but not _that_ useful as a link just yet :) https://gitlab.com/olliver/linux/-/commit/53631aca0aa95f92e72c75e878e995028c3b8764

**Comment by svanheule** [comment]
I've added the "blocked" label. Can you let me know when everything is in place to give this another look?

**Pull request closed without merging**
