### PR TITLE
ramips: mir3g dts define usb volt regulator

### PR DESCRIPTION
**Pull request by ldir-EDB0**
Define USB port power GPIO is voltage regulator type instead of exposing
as a normal GPIO.

Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by dissent1** [comment]
Are you sure that this gpio is a power supply and not just a simple on/off switch?
I’ve experienced such misinterpretation on ipq806x device when defined on/off usb power gpio switch (~1.2v) as a regulator with 5v supply. I’ve understood the mistake by a specific smell coming out of it :)

**Comment by ldir-EDB0** [comment]
I was the person who discovered the power on/off functionality of GPIO 12 and added it to the DTS tree originally.  There was discussion/confusion as to whether it should have been exposed a) at all b) as a gpio on/off c) some sort of USB associated voltage regulator (be it fixed or otherwise)

At the time I argued for (and got) b on the basis that no one understood/could advise how to do c.  Ath79 offered an example of how to do c, so I have followed it.

No smoke, magic or otherwise, has escape my unit as a result of this change and the USB port still works.  The disadvantage of this change is that it is no longer possible to switch USB power off/on... certainly not in an obvious way.  But I believe it to be a more technically correct way to do the DTS definition.

I am assuming that to be even more technically correct, the USB ports themselves would be defined and it is those that would then make reference to the (fixed) voltage regulator.  I have NO idea how to go about that, or indeed understand how the existing USB port is even discovered.

**Comment by dissent1** [comment]
I believe that removing the ability to switch off/on the USB port is not a good proposal - it allows the user to manually restart the usb attached device when needed.

**Comment by mkresin** [comment]
> I believe that removing the ability to switch off/on the USB port is not a good proposal

Most likely the GPIO doesn't power down the USB. It is should only disable the 5V VCC on Pin 1. Means, active powered USB devices should still work.

> it allows the user to manually restart the usb attached device when needed.

It depends on who you ask. In my opinion @ldir-EDB0 proposal is the right way to do it. @pepe2k on the other hand prefers to have full control over the GPIO. The GPIO discussion between me and Piotr is already kind of a running gag.

If implemented by the usb driver you can [pass the regulator as phandle](https://github.com/openwrt/openwrt/commit/d8b475212bbf9e5f80c1c923a9701dca5ceb23e2). This way the GPIO is pulled during driver load to enable usb vcc and pulled again during driver unload to disable usb vcc.

Looks like upstream prefers to give the driver full control over the vbus vcc as well (and it is even required when using an usb port in device instead of host mode). In the end, it isn't that different from GPIOs which are pulling reset pins.

It might even allow to reduce the boards power consumption by not loading the usb driver. Attached - not active powered devices - can be restarted via driver unload/load as well.

**Comment by pepe2k** [comment]
> It depends on who you ask. In my opinion @ldir-EDB0 proposal is the right way to do it. @pepe2k on the other hand prefers to have full control over the GPIO. The GPIO discussion between me and Piotr is already kind of a running gag.

That's why we should probably have a common agreement about that across whole project, not per target or even per device. Nevertheless, I haven't changed my opinion in this subject but would follow majority if we had it.

**Comment by ldir-EDB0** [comment]
I believe now that my change is incomplete anyway, working on filling the missing piece of the puzzle.  Wish I understood DTS better ;-)

**Comment by ldir-EDB0** [comment]
Pieces now filled in.  It now works.

Re: the discussion of whether these things should be exposed as open 'non specific' GPIO or be associate with the device, my opinion is for the latter.  IMO, the DTS should describe how the hardware is used/connected from a functionality perspective.  In this instance for example the GPIO pin is physically connected in some manner to the USB vcc output.  You cannot change that.  So it should be under control of the USB driver.  Similarly for LEDs, certain GPIOs are connected to certain colour LEDs, that is how the hardware is designed in the factory, and the DTS should reflect that design for this device.  Otherwise we should just label everything GPIO1-n and not tell anyone whether it's connected to an input/output/red/green/blue led etc.

The OS should have as complete a functional view of the hardware as possible via the DTS description IMO.

**Comment by dissent1** [comment]
So when you u load the driver does it also disable the USB-port?

If not, maybe it's possible to implement through regulator-gpio?
https://www.kernel.org/doc/Documentation/devicetree/bindings/regulator/gpio-regulator.txt

And 1 more question: have you checked what happens when you supply say 1.3V instead of 5V if USB still functions after that then it's not a 5V regulator. In MT7621 datasheet there are no Pons that supply 5V. The closest ones are analog USB supply with 3.3V as per datasheet (page 12).

**Comment by ldir-EDB0** [comment]
As per the commit message driver unload/load now controls the gpio pin used to turn the 'regulator' on /off.   There is no on board regulator on the soc, that's why it's a gpio output to control an external device.  The 'regulator' is fixed voltage (5V) so all the gpio does is turn it off/on.  It needs to be a 'regulator construct' in DTS so the USB driver can pick it up to control it (ie. turn on/off on driver load/unload)

**Comment by dissent1** [comment]
Not really, it doesn't only turn it on/off but with your change it also sets the Voltage to supply over the gpio i.e. 5V.

So what I'm saying is maybe this specific gpio is not meant to supply 5v. The highest I've seen in datasheet is 3.3v.

**Comment by dissent1** [comment]
So my reasonable concerns scared you?
Without knowing that this pin is really a supply but not a simple on/off switch it's better to leave as it is.
I've proposed a way to check it - to set min/max regulator voltage to a much smaller value - if ithe attached device still functions then it is a simple switch and the supply us elsewhere, if not then it is a supply.

**Comment by mkresin** [comment]
@dissent1 you completely miss the point of a fixed regulator and only add noise to the PR. Please read the kernel documentation!

ramips doesn't support to set different voltage levels. All pins have a fixed voltage, hence a fixed regulator. It doesn't really matter which voltage is set, as the pins always use there only supported voltage. Nevertheless, the pin is related to the 5V USB VCC, therefore the set voltage levels are logical correct.

And yes, it is a simple on/off switch. But the driver has the vcc-supply devicetree property for a reason. I already outlined why the driver should be aware of this GPIO/pin.

@ldir-EDB0 would you please reopen/recreate the PR. Using an upstream provided way to enable USB VCC is the way to go. The gpio-export patch/hack was rejected upstream a long time ago and the regulator framework can be seen as the upstream way of doing the same.

**Comment by ldir-EDB0** [comment]
I really don't get what is so hard here.  We have a GPIO output that is connected to a switch that turns on or off the 5V supply to a USB port.  The control of that GPIO output can appear as a conventional GPIO device, in which case it turns on/off the USB Vcc.  Or we can get the USB driver to do it for us.  That is done by defining a regulator property... in this instance a fixed regulator over which we have no control in terms of output voltage other than turning it on or off.  The regulator property controls whether to turn on/off the regulator's output by the very same GPIO output.  We then hand over the regulator to the USB driver, and the driver controls the GPIO output.

We are not trying to control the voltage level of the GPIO output (we cannot) nor are we trying to control the output of the USB Vcc 'regulator' because again we actually have no means of controlling that voltage either beyond turning it on or off.

I do understand that there are GPIO controlled *variable* voltage output regulators, and yes, we would need to be careful that the correct GPIO outputs were toggled to select a suitable output voltage from the regulator.  But that is not what is going on nor required in this case.

It's a GPIO output that controls a switch that turns USB Vcc on or off.  We assume that the *fixed* regulator output is 5V because that is what the USB spec says it should be.  We can neither measure or adjust the voltage.

**Comment by pepe2k** [comment]
@dissent1

> You are misusing this regulator framework, you are trying to describe a simple switch as a regulator and even define the voltage that it should supply [...]

Wasn't the [fixed-regulator](https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/regulator/fixed-regulator.txt) made exactly for that (for me it also looks like using a sledgehammer to crack a nut... but I don't know any better way which follows upstream approach)? This part is essential here: "However a fixed voltage regulator is expected to have the regulator-min-microvolt and regulator-max-microvolt to be the same.". What's also important, "voltage regulator" doesn't always mean that you can control voltage in wide range - in this case, it's just about two values: on (0 V) and off (5 V) but still, it's a "voltage regulator".

As I also prefer to keep control over USB power supply for user in easy way (exported GPIO), at some point we would want to upstream all dtses and keeping them aligned with upstream is the right way to make it easier in future.

Anyway, if you know a better idea which would be accepted upstream, I would like to know it.

> IF in future this SoC starts supporting Voltage adjustments beyond default values this regulator node will be the 1st candidate to burn smth in the unit, because this specific gpio is not meant to pass 5V.

I'm sure that would never happen on this platform. It's just impossible from h/w point of view.

> So it DOES adjust the voltage flowing through the gpio.

Yes, but only on platforms which support this feature.

Cheers,
Piotr

**Comment by neheb** [comment]
Speaking of upstream, mt7621 is currently in staging. It may be worthwhile to move the MIR3G DTS and see what they think.

**Comment by ldir-EDB0** [comment]
Speak with upstream?  I'd rather stick my head in a tiger and tickle its testicles with a hammer than get involved with the totally caustic and unfriendly environment of the 'open source shining light' that is Linux.

**Comment by neheb** [comment]
By upstream I mean Linux staging, not Mediatek or XiaoMi

**Comment by ldir-EDB0** [comment]
You can do what you want - I'm not going anywhere near it.

**Comment by neheb** [comment]
I mention staging since there are a bunch of gpio changes that may be relevant such as this one: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/staging/mt7621-dts?h=next-20180607&id=c7092ed7946217a9ffad8aa1bcacece727843674

**Comment by bobafetthotmail** [comment]
> Speak with upstream? I'd rather stick my head in a tiger and tickle its testicles with a hammer than get involved with the totally caustic and unfriendly environment of the 'open source shining light' that is Linux.

What's the worst that can happen, getting called names by some random dude on the internet?

**Comment by kofec** [comment]
Hi,
Previously I can manage USB power by executing
`echo "0" > /sys/class/gpio/usbpower/value`
 How can I manage USB power after this change ?

**Comment by ldir-EDB0** [comment]
You cannot directly.  It is under control of the USB driver, thus unloading/reloading the driver is the only way AFAIK.

**Comment by kofec** [comment]
I found something lie this but still don't know hot to manage power on USB:
```
root@LEDEXiaomi3G:~# cat /sys/kernel/debug/gpio
gpiochip0: GPIOs 0-31, parent: platform/1e000600.gpio, 1e000600.gpio:
 gpio-6   (                    |mir3g:red:status    ) out hi
 gpio-8   (                    |mir3g:blue:status   ) out lo
 gpio-10  (                    |mir3g:yellow:status ) out hi
 gpio-12  (                    |usb_vbus            ) out hi
 gpio-13  (                    |mir3g:amber:wan     ) out hi
 gpio-14  (                    |mir3g:amber:lan1    ) out hi
 gpio-16  (                    |mir3g:amber:lan2    ) out hi
 gpio-18  (                    |reset               ) in  hi

gpiochip1: GPIOs 32-63, parent: platform/1e000600.gpio, 1e000600.gpio:

gpiochip2: GPIOs 64-95, parent: platform/1e000600.gpio, 1e000600.gpio:

```

**Pull request closed without merging**
