### PR TITLE
 tplink-safeloader: Add missing serial-number partitions for CPE/WBS

### PR DESCRIPTION
**Pull request by jwmullally**
If a partition is not defined the TP-Link firmware file, the data
in that undeclared memory range is zero'd out during OEM upgrade.

When support for the the TP-Link CPE/WBS was originally added,
these serial-number partitions were not present, but were added
in later revisions.

This patch adds these partitions to all affected devices to ensure
they don't get erased when OpenWRT is flashed. The list of affected
units was determined by analyzing the partition tables of the CPE/WBS
firmware files.

Signed-off-by: Joe Mullally <jwmullally@gmail.com>

### CODE REVIEW

**Comment by jwmullally** [comment]
Previous discussion [here](https://github.com/openwrt/openwrt/pull/4078#discussion_r637586014).
Firmware report generated [here](https://github.com/jwmullally/openwrt_stuff/tree/master/cpe_wbs/report).

Relevant table:

|vendor                                |partition_hash                  |default_mac_base|default_mac_size|serial_number_base|serial_number_size|product_info_base|product_info_size|
|--------------------------------------|--------------------------------|----------------|----------------|------------------|------------------|-----------------|-----------------|
|CPE210(TP-LINK&#124;UN&#124;N300-2&#124;00000000):2.0|86d2f3dbdbd64373584c702ee77b9991|0x30000         |0x00020         |0x30100           |0x00020           |0x31100          |0x00100          |
|CPE210(TP-LINK&#124;UN&#124;N300-2&#124;00000000):2.0|def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE210(TP-LINK&#124;UN&#124;N300-2&#124;00000000):3.0|86d2f3dbdbd64373584c702ee77b9991|0x30000         |0x00020         |0x30100           |0x00020           |0x31100          |0x00100          |
|CPE210(TP-LINK&#124;UN&#124;N300-2&#124;00000000):3.0|def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE210(TP-LINK&#124;UN&#124;N300-2):1.1         |def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE220(TP-LINK&#124;UN&#124;N300-2&#124;00000000):2.0|def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE220(TP-LINK&#124;UN&#124;N300-2&#124;00000000):3.0|86d2f3dbdbd64373584c702ee77b9991|0x30000         |0x00020         |0x30100           |0x00020           |0x31100          |0x00100          |
|CPE220(TP-LINK&#124;UN&#124;N300-2&#124;00000000):3.0|def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE510(TP-LINK&#124;UN&#124;N300-5&#124;00000000):2.0|def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE510(TP-LINK&#124;UN&#124;N300-5&#124;00000000):3.0|86d2f3dbdbd64373584c702ee77b9991|0x30000         |0x00020         |0x30100           |0x00020           |0x31100          |0x00100          |
|CPE510(TP-LINK&#124;UN&#124;N300-5&#124;00000000):3.0|def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE510(TP-LINK&#124;UN&#124;N300-5):1.0         |7324ca34622656cf3264c688245bc56f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE510(TP-LINK&#124;UN&#124;N300-5):1.1         |7324ca34622656cf3264c688245bc56f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE610(TP-LINK&#124;UN&#124;N300-5&#124;00000000):1.0|86d2f3dbdbd64373584c702ee77b9991|0x30000         |0x00020         |0x30100           |0x00020           |0x31100          |0x00100          |
|CPE610(TP-LINK&#124;UN&#124;N300-5&#124;00000000):1.0|def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|CPE610(TP-LINK&#124;UN&#124;N300-5&#124;00000000):2.0|86d2f3dbdbd64373584c702ee77b9991|0x30000         |0x00020         |0x30100           |0x00020           |0x31100          |0x00100          |
|WBS210(TP-LINK&#124;UN&#124;N300-2&#124;00000000):2.0|86d2f3dbdbd64373584c702ee77b9991|0x30000         |0x00020         |0x30100           |0x00020           |0x31100          |0x00100          |
|WBS210(TP-LINK&#124;UN&#124;N300-2&#124;00000000):2.0|def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|WBS510(TP-LINK&#124;UN&#124;N300-5&#124;00000000):2.0|86d2f3dbdbd64373584c702ee77b9991|0x30000         |0x00020         |0x30100           |0x00020           |0x31100          |0x00100          |
|WBS510(TP-LINK&#124;UN&#124;N300-5&#124;00000000):2.0|def4cce79e014387ac0bef96855e0e2f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |
|WBS510(TP-LINK&#124;UN&#124;N300-5):1.20        |7324ca34622656cf3264c688245bc56f|0x30000         |0x00020         |                  |                  |0x31100          |0x00100          |

**Comment by adschm** [comment]
ptns -> partitions

Took me a while to understand the abbrev.

**Comment by jwmullally** [comment]
Updated (was staying under the recommended title limit).

**Comment by apcameron** [comment]
@jwmullally Thank you for addressing this.

**Comment by jwmullally** [comment]
This can be applied to both /master and /openwrt-21.02. Does this need any more changes/testing?

**Comment by adschm** [comment]
> When support for the the TP-Link CPE/WBS was originally added,
> these serial-number partitions were not present, but were added
> in later revisions.

So, what happens if you try to flash one of the older versions with the serial-number partition present in tplink-safeloader?

Anyway, note that firmware-utils has been moved to its own repository, so you will have to resubmit to the mailing list...

**Pull request closed without merging**
