### PR TITLE
octeontx: switch to 5.10 Kernel

### PR DESCRIPTION
**Pull request by aparcar**
CI build with artifacts: https://github.com/aparcar/openwrt/actions/runs/1292199329

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by dddaniel** [comment]
We have several Gateworks Newport GW6400 boards running openwrt octeontx builds with kernel 5.10 for a couple of month now without any issues. @aparcar

**Comment by aparcar** [comment]
I tried to add the missing symbols myself. @adschm can you approve that this solves your compilation issue?

**Comment by hauke** [comment]
I fixed the problem in this commit c120f7943eee9613b0332f20a5ac95085a299991 and also refreshed the target kernel configuration in d2ae4821c225f17e6484a8a7eeed20965901c9df.
@aparcar  Could you please rebase your pull request. 
@dddaniel or someone else with this hardware, could you please check if current OpenWrt master with kernel 5.10 s working fine on your octeontx devices and report back in this pull request or on the mailing list. If it is ok for you we can merge this pull request.

**Comment by dddaniel** [comment]
@hauke @aparcar. Confirmed. Build is running fine. Tested on multiple Gateworks Newport devices.

**Comment by aparcar** [comment]
Merged, thanks for testing.

**Pull request closed without merging**
