### PR TITLE
Openwrt 22.03 ramips: add support for Hanyang Digitech HYC-G920

### PR DESCRIPTION
**Pull request by momothefox**
I have this Device which is nearly Identical to ASUS RT-AC57U

SoC: MediaTek MT7621AT
RAM: 256M (SK hynix H5TQ2G63FFR)
FLASH: 16MB (Winbond 25Q128FVSG)
WiFi: MediaTek MT7602EN bgn 2SS
WiFi: MediaTek MT7612EN nac 2SS
BTN: Reset
LED: - Power RED
- WAN Green
- LAN {1-4}
- WiFi 2.4 GHz Blue
- WiFi 5 GHz Blue
- USB Green
UART:
GND - 3V3 - TX - RX - GND / 57600-8N1

RESET BTN @ gpio 3 Active low
Power LED @ gpio 0 Active low
USB LED @ gpio 18 Active low
wifi5g LED @ gpio 19 Active low
wifi2g LED @ gpio 20 Active low

editing mt7621_asus_rt-ac57u.dts

```
// SPDX-License-Identifier: GPL-2.0-or-later OR MIT

#include "mt7621.dtsi"

#include <dt-bindings/gpio/gpio.h>
#include <dt-bindings/input/input.h>

/ {
	compatible = "asus,rt-ac57u", "mediatek,mt7621-soc";
	model = "ASUS RT-AC57U";

	aliases {
		led-boot = &led_power;
		led-failsafe = &led_power;
		led-running = &led_power;
		led-upgrade = &led_power;
	};

	leds {
		compatible = "gpio-leds";

		led_power: power {
			label = "red:power";
			**gpios = <&gpio 0 GPIO_ACTIVE_LOW>;**
		};

		usb {
			label = "green:usb";
			**gpios = <&gpio 18 GPIO_ACTIVE_LOW>;**
			trigger-sources = <&ehci_port2>;
			linux,default-trigger = "usbport";
		};
	};

	keys {
		compatible = "gpio-keys";

		reset {
			label = "reset";
			**gpios = <&gpio 3 GPIO_ACTIVE_LOW>;**
			linux,code = <KEY_RESTART>;
			debounce-interval = <60>;
		};
	};

	led-regulator {
		compatible = "regulator-fixed";
		regulator-name = "LED-Power";
		gpio = <&gpio 46 GPIO_ACTIVE_LOW>;
		regulator-min-microvolt = <3300000>;
		regulator-max-microvolt = <3300000>;
		regulator-always-on;
	};
};

&spi0 {
	status = "okay";

	flash@0 {
		compatible = "jedec,spi-nor";
		reg = <0>;
		spi-max-frequency = <10000000>;

		partitions {
			compatible = "fixed-partitions";
			#address-cells = <1>;
			#size-cells = <1>;

			partition@0 {
				label = "u-boot";
				reg = <0x0 0x30000>;
				read-only;
			};

			partition@30000 {
				label = "config";
				reg = <0x30000 0x10000>;
				read-only;
			};

			factory: partition@40000 {
				label = "factory";
				reg = <0x40000 0x10000>;
				read-only;
			};

			partition@50000 {
				compatible = "denx,uimage";
				label = "firmware";
				reg = <0x50000 0xfb0000>;
			};
		};
	};
};

&pcie {
	status = "okay";
};

&pcie0 {
	wifi@0,0 {
		compatible = "mediatek,mt76";
		reg = <0x0000 0 0 0 0>;
		mediatek,mtd-eeprom = <&factory 0x8000>;

		led {
			led-sources = <2>;
			led-active-low;
		};
	};
};

&pcie1 {
	wifi@0,0 {
		compatible = "mediatek,mt76";
		reg = <0x0000 0 0 0 0>;
		mediatek,mtd-eeprom = <&factory 0x0000>;

		led {
			**led-sources = <2>;**
			led-active-low;
		};
	};
};

&gmac0 {
	nvmem-cells = <&macaddr_factory_e000>;
	nvmem-cell-names = "mac-address";
};

&switch0 {
	ports {
		port@0 {
			status = "okay";
			label = "wan";
			nvmem-cells = <&macaddr_factory_e006>;
			nvmem-cell-names = "mac-address";
		};

		port@1 {
			status = "okay";
			label = "lan1";
		};

		port@2 {
			status = "okay";
			label = "lan2";
		};

		port@3 {
			status = "okay";
			label = "lan3";
		};

		port@4 {
			status = "okay";
			label = "lan4";
		};
	};
};

&state_default {
	gpio {
		groups = "sdhci";
		function = "gpio";
	};
};

&factory {
	compatible = "nvmem-cells";
	#address-cells = <1>;
	#size-cells = <1>;

	macaddr_factory_e000: macaddr@e000 {
		reg = <0xe000 0x6>;
	};

	macaddr_factory_e006: macaddr@e006 {
		reg = <0xe006 0x6>;
	};
};
```

removed wps button code 
and changed code between ** and ** 
firmware works fine

### CODE REVIEW

**Comment by momothefox** [comment]
Changing U-boot to breed web via UART 
choose option 9 to write new bootloader to SPI 
then Flash new Firmware via breedweb

**Comment by mans0n** [comment]
This is not ready for a code review. (I can't find your own patch, did I miss it?) Please read:
https://openwrt.org/submitting-patches
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes
You might also find some help from the [forum](https://forum.openwrt.org/).

I'm closing this, please request me to reopen this before you push a patch ready for review.

**Comment by momothefox** [comment]
> This is not ready for a code review. (I can't find your own patch, did I miss it?) Please read: https://openwrt.org/submitting-patches https://openwrt.org/docs/guide-developer/frequent-pr-mistakes You might also find some help from the [forum](https://forum.openwrt.org/).
> 
> I'm closing this, please request me to reopen this before you push a patch ready for review.
Hi  
can you check this out 
https://github.com/momothefox/openwrt
i made a fork
added new file [mt7621_hanyang_hyc-g920.dts](https://github.com/momothefox/openwrt/blob/master/target/linux/ramips/dts/mt7621_hanyang_hyc-g920.dts)
and [Updated mt7621.mk](https://github.com/momothefox/openwrt/commit/07558278952a4aeb9663a797c743c2c116f3e17e)

and i am building now firmware using my repository to test it. 

am i on the right track?

**Comment by mans0n** [comment]
Yeah, that's in much better shape. Please open a new PR for it.
And please follow the guideline from the links I gave you. Your patch has some formal issues and you'll need to address it after you submit it.

**Pull request closed without merging**
