### PR TITLE
add delegate option support

### PR DESCRIPTION
**Pull request by ptpt52**
Ipv6 delegate option is not respected by these proto, this add support for them.

### CODE REVIEW

**Comment by 981213** [comment]
If you need to add every dhcpv6 options in all protocols, it's better to put the duplicated ipv6 interface setup into some functions, create a shared script, and include it in various protocol setup.

**Comment by ptpt52** [comment]
delegate option is available on luci page already, but it is not working without this PR

**Comment by ptpt52** [comment]
> If you need to add every dhcpv6 options in all protocols, it's better to put the duplicated ipv6 interface setup into some functions, create a shared script, and include it in various protocol setup.

This is already the most appropriate modification; there isn't a universal change that can apply to all protocols unless all protocol scripts are refactored.

**Comment by Neustradamus** [comment]
Any progress on it?

**Comment by hauke** [comment]
Applied to main branch in 01d257e95fed205edfea33eb57ef3ff14d9c8007, 72d9e4fc31a1e6cc8f00c1b8d7366bf2efc13f9e, 0371a4c8146d4f8239e03813e42f78d553178f8d, a97b7af33e7fc6c8a4e6920f32d402c5683a36ff, 8a5db2ff3c370f1ba3809e87767fbc478765abe6 and 105a5790b7131015c083cc3f08c81c3aca2b228a.

**Pull request closed without merging**
