### PR TITLE
Update dnsmasq to 2.86 in openwrt-21.02 branch

### PR DESCRIPTION
**Pull request by Curly060**
Hi!

OpenWRT stable is using dnsmasq 2.85 which has a bug when forwarding specific domains to alternate DNS servers, i.e. with the following config line in /etc/config/dhcp (not possible to enter this via LuCi, must be done manually or via uci CLI):
```
config dnsmasq
	list server '/*.home.mydomain.com/192.168.112.254'
```
dnsmasq 2.85 forwards this to the default upstream name server instead of 192.168.112.254.  This is a bug in dnsmasq and not OpenWRT. I have verified the bug with an x86 build of dnsmasq where this happens, too. dnsmasq 2.86 works correctly.

I have simply cherry-picked d2d0044e from the master branch. I have successfully compiled dnsmasq, uploaded the ipk to the router and successfully installed it via opkg.

It's now working as expected. I'd be very happy to see the updated dnsmasq in the next stable maintenance release which I hope is soon :)

Cheers, Ingo =;->

### CODE REVIEW

**Comment by dave14305** [comment]
There have been a lot of issues with 2.86 reported on the dnsmasq-discuss mailing list. It wasn’t a stellar release by Simon Kelley’s own admission, and he’s still fixing issues introduced in 2.86, including a hang issue.

**Comment by Curly060** [comment]
Well, in that case it does not make sense to accept this PR. But what to do then? Forwarding specific domains to other DNS servers is critical for me, but broken in dnsmasq 2.85. I assume Simon Kelley won't fix a bug in 2.85 and create a 2.85.1, but rather make 2.87 stable which means we have to wait until that happens...

**Comment by dave14305** [comment]
Isn’t the asterisk invalid in 2.85 (wildcards only added in 2.86)? Will it work if you just use
```
config dnsmasq
	list server '/home.mydomain.com/192.168.112.254' ```

**Comment by Curly060** [comment]
Oh dear! You are absolutely right! I was reading the online man page and it never occurred to me that this could be a brand new feature. So I assumed *.bla.com is the correct syntax. It is for 2.86, but not for 2.85 and below. So it's definitely not a bug. Good catch and sorry for the confusion!

Your suggestion will work, except that a DNS request to home.mydomain.com will also be forwarded like that. I explicitly only want to forward *.home.mydomain.com and have home.mydomain.com resolved through OpenWRT. So unfortunately it won't work in my specific use case.

Well, 2.85 can't do what I need, 2.86 is too buggy still to be pulled in. I will keep my custom built 2.86 and hope to not run into the hang issue you mentioned.

Thanks a lot for your help. I am closing this PR!

**Pull request closed without merging**
