### PR TITLE
ath79: ag71xx: Add gmac config for ar934x/qca9558 and split eth/mdio/switch apart

### PR DESCRIPTION
**Pull request by 981213**
Current ag71xx is a mixed driver of mac/mdio/switch, which should be independent parts:
Although QCA mixed mdio registers with gmac ones, mdio and gmac work independently. And we need them to work independently because we always need to use mdio1 for gmac0 on SoCs with builtin switch. (Edit: This is only true for ar7241 and later SoCs.)
The builtin switch is a separated IP (AR8216 on ar933x and earlier and AR8229 on ar934x and later) and has nothing to do with gmac. We don't need to reset and reconfigure the switch everytime we bring gmac1 up.
Current mdio driver for mdio1 isn't the one in gmac1 at all. ar7240sw_phy_read/write functions are used to operate mdio in builtin switch using mdio in gmac1. I think we shouldn't make a gmac driver which is supposed to operate gmac mdio operating the mdio in the switch because it's misleading.

This PR did the following things:
1. Make mdio a separated platform device registered before ag71xx-eth so that we can get both mdio ready before initializing gmac0/gmac1.
2. Register the builtin switch as a standard mdio device.
3. Register a separated mdio bus in switch driver.

### CODE REVIEW

**Comment by 981213** [comment]
Removed all the previous preparations for adding apb support and added mdio/phy/eth0 nodes for ar9341. Tested on TL-WR841N-V8.

**Comment by blocktrron** [comment]
Great work! Just a small pointer regarding the qca955x gmac setup: Some devices need additional values to be configured and an ar71xx this is done via custom c code in the machine file. Have a look at the mach-koala.c or mach-om5pacv2.c for example.

I've just now discovered your PR, while working on support for the OCEDO Koala i've faced the need to set those values, solved it fairly similar maybe you want to take a look and update your PR accordingly: https://github.com/blocktrron/openwrt/commit/be3f2bca680c65086c0c8f19e719ab9458f06a74

**Comment by 981213** [comment]
PHYs in builtin ar8216 isn't controllable through gmac1 mdio so I added those switch mdio operations back and registered a separated mdiobus in switch driver.
Support for AR9331 is added.
AR724X: I'm waiting for my ordering.
QCA953X: Waiting for #1094

**Comment by lucize** [comment]
@981213 sorry, I'm on holidays and can't test, only after 19/20 july

**Comment by 981213** [comment]
I have routers with QCA9533/QCA9558 now and this PR won't affect QCA9563 (Support for QCA9561 with builtin switch hasn't been added in ath79.)

**Comment by blocktrron** [comment]
@981213 Thanks for that!

**Comment by 981213** [comment]
Cherry-picked #1094 here with some modification to complete qca953x support.

**Comment by 981213** [comment]
I did the test on WDR4900 v2 for qca9558 (Similar to Archer C7 boards but replaced QCA9880 with AR9380. They shared the same machine code in ar71xx.) and found  several mistakes in current Archer C7 v2 support. Fix them in this PR because the added gmac-config depends on commits here. I will open another PR for wdr4900 support after the work for this PR is done and merged.

**Comment by 981213** [comment]
RFT: Support for ar7240/ar7241/ar7242 isn't tested because I don't have these routers.

**Comment by 981213** [comment]
Current ar7100/ar913x devices in ath79 isn't using mdio so I won't update dts for them in this PR.
I'll submit another PR to add tl-wr941nd-v2 support (This one need mdio bus for mv88e6060.) after I find my ancient router.

**Comment by juppin** [comment]
@981213 I did a test on TP-Link MR3420v1 (AR7421, built-in switch with 4xLAN + 1xWAN 100M) with your latest PR state. I´ve only compiled from your branch, no modifications are done.

Here is the kernel bootlog: https://pastebin.com/L3cLpPXT

At first everything looks great. I´ve connected my pc to one lan port and everything works...
Output of swconfig and ifconfig: https://pastebin.com/tqCEE2Rf

But as soon i connect anything to the wan port, no switch port is working anymore and shows down in swconfig. Wan port does work as expected.
Output of swconfig and ifconfig after wan port is up: https://pastebin.com/UPgw2JZH
I do not have disconnected the network cable in lan port 2 and can not ping anymore through any switch connected port until a reboot without connected wan port...
`ifdown -a && sleep 1 && ifup -a ` does not help either.

Let me know if i should do another test.

Greets and thanks for your effort.

**Comment by 981213** [comment]
@juppin The reset definition for ar724x gmac0/gmac1 is wrong like ar934x.( Connecting wan port will trigger a switch reset.) I've pushed a fix for that.

**Comment by juppin** [comment]
@981213 Now everything works as expected on TP-Link MR3420v1 (AR7421)

**Comment by juppin** [comment]
@981213 I´ve done a quick and dirty test on Buffalo WHR-G300N V2 (AR7240+builtin-switch(AR8216))

Last time i used this device with breed bootloader and ar71xx TP-Link WR740v2 image (very similar apart from partition layout), because this gives me 192k more flash and i can´t got a image without tp-link header working. Thats why i have here also used a tp-link image/header.

Switch and wan port does not work...
```
[    0.406496] mdio-bus.0:1f: unsupported chip, ctrl=00000000
[    0.412051] ag71xx-switch: probe of mdio-bus.0:1f failed with error -22
```

Here is my quick and very dirty created port: https://github.com/juppin/openwrt/tree/ath79_ag71xx_buffalo

And here the bootlog: https://pastebin.com/34xXPXCv

Any suggestions what is missing?

Probably at weekend i will try to get the stock bootloader and partition layout working, but i don´t think this is here the problem.

**Comment by 981213** [comment]
I guess the problem comes from the incorrectly defined mdio clock divider.
```c
	if (of_device_is_compatible(np, "qca,ar7240-mdio"))
		t = MII_CFG_CLK_DIV_6;
	else if (of_device_is_compatible(np, "qca,ar9340-mdio"))
		t = MII_CFG_CLK_DIV_58;
	else if (builtin_switch)
		t = MII_CFG_CLK_DIV_10;
	else
		t = MII_CFG_CLK_DIV_28;
```
The value of MII_CFG_CLK_DIV_6 is 2 and according to datasheet 2 is 'Source clock divided by 4'
Since the reference clock is 40MHz, the mdio clock is 10MHz and it may be too high.
But this mistake exists on ar71xx for a long time. If this cauesd the problem I don't know why it works previously.

Anyway I've bought a TP-Link TL-WR941N v4 (AR7240+AR9283) and I'll test this myself when it arrives. (Probably the day after tomorrow.)

**Comment by 981213** [comment]
The seller sent me the wrong version of router. They gave me a WR941N v6 (AR9344+AR9380) :(
@juppin Could you test on AR7240 again when you are free? I've fixed the mdio clock problem.

**Comment by juppin** [comment]
@981213 Same as before...
```
[    0.397843] libphy: Fixed MDIO Bus: probed
[    0.402468] MDIO_CLK 40000000/8=5000000 for 5000000
[    0.407543] libphy: ag71xx_mdio: probed
[    0.411691] mdio-bus.0:1f: unsupported chip, ctrl=00000000
[    0.417191] ag71xx-switch: probe of mdio-bus.0:1f failed with error -22
```
Complete bootlog: https://pastebin.com/G14PXSX6

**Comment by 981213** [comment]
I'm waiting another package delivery for an AR7240 router now. This PR may be hang here for another 3 days :(

**Comment by 981213** [comment]
The old initialization order is correct on ar7240 because the mdio bus is separated since ar7241. I ended up with a small workaround for ar7240.
This PR is ready to be checked and merged now.

**Comment by cshoredaniel** [comment]
@981213 I have a peculiar ar9341 device that in the ar71xx version (and stock firmware) has the switch on eth0 and wan (phy4 with phy4-mii-enable) on eth1, BUT this is only because the firmware performs the probes in reverse order (i.e. the ath79_register_eth(1) occurs before ath79_register_eth(0) in the ar71xx board def).  In search mach-ath79 dir in ar71xx I found at least one other board does the same thing.

I there a sane way to support this in DT, or does it make more sense to rename the devices early in preinit (i.e. before they are brought up) using 'ip link set ...' and avoid trying to mangle DT?  (I thought about a hotplug solution but the core ethernet stuff is assumed to be present before hotplug's coldplug is done, which means that won't work).

**Comment by cshoredaniel** [comment]
Also in [](https://bugs.openwrt.org/index.php?do=details&task_id=1702) I had started hacking on getting link detection working on the switch ports; since you've separated the phy, this could actually work across ath79/ag71xx devices by making something like the patch part of the phy driver (and getting rid of the fixed link in the DT).  This is more musing about a future feature request, to bring things more to parity with ar71xx (which can do link detection on the switch if you so choose; the phy_poll_mask bit was inspired (but not the same as) the ar71xx work function, which is what allows this.

**Comment by 981213** [comment]
Device tree is only designed to describe a device and there is no design for specifying an initialization order. Although the devices are probed in the order they are written in dts but the devices in dts should be ordered by their registers.
What I changed here has nothing to do with interface names. And since ath79 is a brand new target, there is no need to make the interface name the same as ar71xx did. (We don't need to make ethernet configuration compatible. Since wireless configuration is incompatible anyway, a sysupgrade is impossible.)

**Comment by 981213** [comment]
As for the switch part, I don't like to add more features to the builtin switch driver because current builtin switch driver has a lot of code duplicated with the ar8216 switch driver. I would prefer adding the builtin switch support to ar8216 and remove the builtin switch driver first. (That's a reason why I didn't move that driver into drivers/net/phy directory.)

**Comment by cshoredaniel** [comment]
@981213 Re: device names; I mentioned it only because you were working on the driver (and I'm not as familiar with DT as I'm guessing you are).

Re: switch: Understand, that makes a lot of sense.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
