### PR TITLE
iproute2: avoid unneeded compiles to speed building

### PR DESCRIPTION
**Pull request by guidosarducci**
### Description:
Skip building Makefile targets that aren't packaged: `tipc`, `dcb`, `ifstat`, `rtacct`, `lnstat`, and `man`. Also, only compile targets needed for the current build variant i.e. don't compile `tc` when building an `ip` variant and vice versa.

These changes reduce typical build times by over 30%:
  $ make package/iproute2/clean && time make -j8 package/iproute2/compile
  (old)
  ...
  real    2m24.985s
  user    3m12.537s
  sys     0m26.677s

  (new)
  ...
  real    1m36.945s
  user    2m8.734s
  sys     0m20.046s

### Testing:
Build and run-tested on master with QEMU/malta/mips32be.

### Distribution:
Package maintainer is @RussellSenior, and frequent contributors to `iproute2` include @ldir-EDB0 , @dedeckeh , and @nbd168 . @hauke also reviewed and merged several related PRs.

### CODE REVIEW

**Review by ldir-EDB0 — APPROVED** [review]
Builds & runs for me on x86_64 - was going to merge it, then realised ought to wait for Russ

**Comment by RussellSenior** [comment]
The thing I worry about is whether some other package relies on some built component as a build dependency, and what testing would be needed to discover that. The alternative tried-and-true approach is the traditional method of "cut the wire and wait for the phone to ring".  That is, in this case: apply the patch and wait for reports of breakage from the world.

**Comment by guidosarducci** [comment]
> The thing I worry about is whether some other package relies on some built component as a build dependency, and what testing would be needed to discover that.

I think this worry is already ruled out by design. The only possible dependencies I see are:
1. Host build/package: `iproute2` has none.
2. Development files: `iproute2` headers and libs from the `InstallDev` section are unchanged by this PR.
3. Target package: `iproute2` builds the same packages, and this PR only disables binaries which aren't being packaged.

What others dependencies do you think might exist? 

> The alternative tried-and-true approach is the traditional method of "cut the wire and wait for the phone to ring". That is, in this case: apply the patch and wait for reports of breakage from the world.

That strategy works especially well if the wire you cut is for the phone line. :^)

Kidding aside, I'm fine with making the change and then monitoring buildbots, etc. for signs of problems. Thanks, Kevin.

**Comment by RussellSenior** [comment]
Build dependencies aren't perfectly specified. See: https://github.com/openwrt/packages/issues/14897 for an example. Some obscure combination of .config selections *might* result in a build failure of some far flung package, and it's impractical to test them all. Absence of proof != proof of absence, etc. Other than that, I have no objection.

**Comment by ldir-EDB0** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ldir.git

**Comment by guidosarducci** [comment]
@ldir-EDB0 Thanks, Kevin. If you're still in the mood, could you have a look at https://github.com/openwrt/openwrt/pull/3855? That one's been waiting for some time without reported issues. I'd also like to resolve https://github.com/openwrt/openwrt/pull/4095 if possible. Cheers!

**Pull request closed without merging**
