### PR TITLE
openssl: fix bad sysupgrade with devcrypto engine

### LINKED ISSUE #12084: ipq807x Unable to upgrade firmware on page！！！
### Describe the bug

self-compiled AX6 firmware cannot be refreshed on the page

### OpenWrt version

r22136-c98a202446

### OpenWrt target/subtarget

ipq807x/generic

### Device

Redmi AX6

### Image kind

Self-built image

### Steps to reproduce

_No response_

### Actual behaviour

_No response_

### Expected behaviour

_No response_

### Additional info

_No response_

### Diffconfig

_No response_

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by cotequeiroz**
The bump to 3.0.8 inadvertently removed patches that are needed here, but were not adopted upstream.  The most important one changes the default value of the `DIGESTS` setting from `ALL` to `NONE`.  The absence of this patch causes a sysupgrade failure while the engine is in use with digests enabled.  When this happens, the system fails to boot with a kernel panic.

Also, explicitly set DIGESTS to NONE in the provided config file, and change the default ciphers setting to disable ECB, which has been recommended for a long time and may cause trouble with some apps.

The config file change by itself is not enough because the config file may be preserved during sysupgrade.

I included a commit with a trivial Makefile fix.

Fixes: #12084 

---

For people affected by this bug:

You can either:
1. remove, the `libopenssl-devcrypto` package
2. disable the engine in `/etc/config/openssl`;
3. change `/etc/ssl/engines.cnf.d/devcrypto.cnf` to set `DIGESTS=NONE`;
4. update `libopenssl-devcrypto` to >=3.0.8-3.
 
However, after doing any of the above, **you must reboot the device before running sysupgrade** to ensure no running application is using the engine.  Running `/etc/init.d/openssl restart` is not enough.

Ping @Ansuel 

This fixes a bad bug and should probably be merged asap.

### CODE REVIEW

**Comment by Ansuel** [comment]
@cotequeiroz that is the scale of this? Guess only user of devcrypt also i think we don't install such package by default right?

**Comment by cotequeiroz** [comment]
Affected users are people with HW crypto devices (not CPU instructions) that enable digests (I imagine most hw do) and that installed the engine package.  The package is not installed by default. 

As for the second commit, I have bumped it for reproducible builds. It won't affect build infrastructure if they are merged together.

**Comment by Ansuel** [comment]
@cotequeiroz merging this but really is upstream aware of this problem?

**Comment by cotequeiroz** [comment]
Yes: OpenSSL/openssl#8430.  However, I don’t expect much happening upstream since they have deprecated the whole engine API.

**Pull request merged**
