### PR TITLE
toolchain: glibc: Update to glibc 2.38

### PR DESCRIPTION
**Pull request by Kaz205**

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Please add some description in the commit message why you add those new configuration arguments. And please don't capitalize update in the commit header. :)

**Comment by Kaz205** [comment]
Done.

**Comment by Kaz205** [comment]
Cc: @hauke

**Comment by PolynomialDivision** [comment]
@hauke Why not bumping version to 2.38 like this PR suggests?

https://github.com/openwrt/openwrt/commit/2ef5714277ce32d0dc7d59e59f20591004f070c4

**Comment by Kaz205** [comment]
@Ansuel Thanks!

**Pull request merged**
