### PR TITLE
[RFC] [RFT] kirkwood: add support for kernel 5.4

### PR DESCRIPTION
**Pull request by CHKDSK88**
Refreshed all patches.
Changed:
105-ea4500.patch-> Upstream DSA driver was updated. Patch was fixed
202-linksys-find-active-root.patch -> Upstream driver was moved. Patch
was fixed
Refreshed kernel config with updated NAND config.

Known issues:
~~Modpost problem. See: https://github.com/openwrt/openwrt/pull/2799#issuecomment-593103597~~
~~Linksys Audi (EA3500): kernel is too big.~~

### CODE REVIEW

**Comment by CHKDSK88** [comment]
At this moment I can't compile sources. The result is:

````
make target/linux/install V=s
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libgnutls', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libopenldap', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libidn2', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libssh2', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/network/utils/nftables/Makefile' has a dependency on 'jansson', which does not exist
make[1]: Entering directory '/home/krolik/openwrt-1'
make[2]: Entering directory '/home/krolik/openwrt-1/target/linux'
make[3]: Entering directory '/home/krolik/openwrt-1/target/linux/kirkwood'
rm -f /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/localversion
/home/krolik/openwrt-1/scripts/kconfig.pl  + /home/krolik/openwrt-1/target/linux/generic/config-5.4 /home/krolik/openwrt-1/target/linux/kirkwood/config-5.4 > /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /home/krolik/openwrt-1/.config >> /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.target
/home/krolik/openwrt-1/scripts/package-metadata.pl kconfig /home/krolik/openwrt-1/tmp/.packageinfo /home/krolik/openwrt-1/.config 5.4 > /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.override
/home/krolik/openwrt-1/scripts/kconfig.pl 'm+' '+' /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.target /dev/null /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.override > /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.set
mv /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.set /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.old
grep -v INITRAMFS /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.old > /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.set
rm -rf /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/modules
cmp -s /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.set /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.prev || { cp /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.set /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config; cp /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.set /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.prev; }
export MAKEFLAGS= ; [ -d /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/user_headers ] || make -C /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22 KCFLAGS="-ffile-prefix-map=/home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi=target-arm_xscale_musl_eabi" HOSTCFLAGS="-O2 -I/home/krolik/openwrt-1/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Mar  1 14:19:32 2020" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/krolik/openwrt-1/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/krolik/openwrt-1/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KERNELRELEASE=5.4.22 CC="arm-openwrt-linux-muslgnueabi-gcc" INSTALL_HDR_PATH=/home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/user_headers headers_install
grep '=[ym]' /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.config.set | LC_ALL=C sort | mkhash md5 > /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.vermagic
touch /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.configured
rm -f /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/root-kirkwood/init
make -C /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22 KCFLAGS="-ffile-prefix-map=/home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi=target-arm_xscale_musl_eabi" HOSTCFLAGS="-O2 -I/home/krolik/openwrt-1/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Mar  1 14:19:32 2020" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/krolik/openwrt-1/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/krolik/openwrt-1/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KERNELRELEASE=5.4.22 CC="arm-openwrt-linux-muslgnueabi-gcc" zImage dtbs modules
make[4]: Entering directory '/home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22'
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  MODPOST vmlinux.o
Segmentation fault (core dumped)
make[5]: *** [scripts/Makefile.modpost:66: __modpost] Error 139
make[4]: *** [Makefile:1078: vmlinux] Error 2
make[4]: Leaving directory '/home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22'
make[3]: *** [Makefile:26: /home/krolik/openwrt-1/build_dir/target-arm_xscale_musl_eabi/linux-kirkwood/linux-5.4.22/.image] Error 2
make[3]: Leaving directory '/home/krolik/openwrt-1/target/linux/kirkwood'
make[2]: *** [Makefile:13: install] Error 2
make[2]: Leaving directory '/home/krolik/openwrt-1/target/linux'
time: target/linux/install#6.71#2.20#8.68
make[1]: *** [target/Makefile:25: target/linux/install] Error 2
make[1]: Leaving directory '/home/krolik/openwrt-1'
make: *** [/home/krolik/openwrt-1/include/toplevel.mk:227: target/linux/install] Error 2
````

@xback 
Can I ask for help? I have no clue how to fix it.
I successfully built images when Your 5.4 work was WIP.

**Comment by frymezim** [comment]
@bobafetthotmail or @p-wassi might help you.

**Comment by mans0n** [comment]
@CHKDSK88 Thanks for your work! I was also trying to port 5.4 to kirkwood, and I suffered from the same error. Maybe 6f9bc70dd584 and 854114800ce7 fix it?

**Comment by CHKDSK88** [comment]
> 
> 
> @CHKDSK88 Thanks for your work! I was also trying to port 5.4 to kirkwood, and I suffered from the same error. Maybe [6f9bc70](https://github.com/openwrt/openwrt/commit/6f9bc70dd584ed41dc1da31bf0342b3cf95ba5d9) and [8541148](https://github.com/openwrt/openwrt/commit/854114800ce7636f4d7628774023e399154b04bc) now fix it?

@mans0n 
Thank for Your answer. I rebased my PR to current master and it help. It is ready for testing now.

**Comment by mans0n** [comment]
I did a run-test on a device and it worked well.
I also tried some build-tests for all devices and kernel modules except for the feeds kernel packages. (I skipped them due to the long build time.) And I got some errors:
- kmod-ipt-nat6 (its build error was reported in the mailing list)
- kmod-iio-st_sensors-* (the build fails but I haven't yet figured out exactly why)
- linksys,audi and linksys,viper (image build fails due to the bigger kernel size)
The rest seem good (apparently).

I also suggest running `make kernel_oldconfig` after the build, it will tidy up the kernel config.
And do we need `CONFIG_PHY_MVEBU_A3700_UTMI=y` here? I guess it is for Armada 3700 and not for kirkwood.

**Comment by mans0n** [comment]
Just curious, how did you manage to get the kernel config? I copied config-4.19 and ran kernel_oldconfig to make config-5.4, but my file still has less configs then yours.

**Comment by CHKDSK88** [comment]
@mans0n 

Than You for tests.

>kmod-iio-st_sensors-* (the build fails but I haven't yet figured out exactly why)

It should be fixed in https://github.com/openwrt/openwrt/commit/4642c4864ef4c8df1749073f6fb6d2de5f51beef
>linksys,audi and linksys,viper (image build fails due to the bigger kernel size)

I added commit, which disable EA3500 by default. But I successfully compile image for EA4500 with all kmods (without feeds).

>And do we need CONFIG_PHY_MVEBU_A3700_UTMI=y here? I guess it is for Armada 3700 and not for kirkwood.

It is added when I run ```make kernel_menuconfig```.

>Just curious, how did you manage to get the kernel config? I copied config-4.19 and ran kernel_oldconfig to make config-5.4, but my file still has less configs then yours. I'd like to know how you did it so that I can do better next time.

It was generated from WIP version of 5.4 commit. I didn't send latest version, so it was my bad.

**Comment by bobafetthotmail** [comment]
not sure why kmods increase kernel size, they are usually modules and stay in root partition.

For EA3500 I don't think it is acceptable to disable the image build, the device is not that old.
If you don't find useless kernel options to disable for all kirkwoods you can make a subtarget with a lighter kernel config (no sata, no usb3 no other stuff they don't have) for audi, viper and other devices that have kernel size limitations.

**Comment by ynezz** [comment]
> not sure why kmods increase kernel size, they are usually modules and stay in root partition.

Kernel itself is getting bigger with each version.

> For EA3500 I don't think it is acceptable to disable the image build, the device is not that old.

It is acceptable for me and it's usually the only option if you don't own the affected device. It would be kind to Cc: the author of the device support in the tree (or some last commit authors related to this devices) so they're aware about this problem and can solve it.

Old or brand new, that doesn't matter if the hardware/bootloader/whatever doesn't allow usage of the recent kernel.

> you can make a subtarget with a lighter kernel config (no sata, no usb3 no other stuff they don't have) for audi, viper and other devices that have kernel size limitations.

I think, that this work has to be done by the interested developers willing to keep support for those devices. Target has to be switched ideally to the new kernel as soon as possible, so the testing by the wider user base can happen. It make no sense to impose such tedious work related to the tiny targets on the developers willing to keeping the target alive.

**Comment by ynezz** [comment]
> I did a run-test on a device and it worked well.

@mans0n which device and can I've your `Tested-by: Your RealName <foo@bar.com>` ?

**Comment by ynezz** [comment]
> kirkwood: add support for kernel 5.4

@CHKDSK88 Could you pls split that huge commit into smaller pieces, this single huge commit is hard for review, for example take a look at https://github.com/openwrt/openwrt/pull/2793/commits

**Comment by bobafetthotmail** [comment]
I'll start building for a few kirkwood devices I have and test on hardware.

> > not sure why kmods increase kernel size, they are usually modules and stay in root partition.
> 
> Kernel itself is getting bigger with each version.

Yeah I know, but this does not explain why on one device it fails for mas0n and builds for CHKDSK88. Unless I read it wrong he said that it failed for both audi and viper.

> 
> > For EA3500 I don't think it is acceptable to disable the image build, the device is not that old.
> 
> It is acceptable for me and it's usually the only option if you don't own the affected device.

If one of you guys can commit this I'm fine with it, I don't own that device either (I have the EA4500) so I won't miss it. It's just that I know other members had different opinions.

**Comment by mans0n** [comment]
@CHKDSK88

>> kmod-iio-st_sensors-* (the build fails but I haven't yet figured out exactly why)
>
> It should be fixed in 4642c48

Okay, that's good. :)

>> linksys,audi and linksys,viper (image build fails due to the bigger kernel size)
>
> I added commit, which disable EA3500 by default. But I successfully compile image for EA4500 with all kmods (without feeds).

kmods does not go into kernel image so I think that's because you turned off `CONFIG_NET_DSA_MV88E6XXX` in your last push.

>> And do we need CONFIG_PHY_MVEBU_A3700_UTMI=y here? I guess it is for Armada 3700 and not for kirkwood.
>
> It is added when I run make kernel_menuconfig.

I don't think it is used by any device so it's safe to disable it.
`# CONFIG_PHY_MVEBU_A3700_UTMI is not set`

> It was generated from WIP version of 5.4 commit.

You mean you copied the config from other targets?
I was wondering how `CONFIG_IO_URING` got into the config... I thought it might be useful but you dropped it anyway. ;)

**Comment by mans0n** [comment]
@ynezz

>> I did a run-test on a device and it worked well.
>
> @mans0n which device and can I've your Tested-by: Your RealName <foo@bar.com> ?

My device has not been ported yet.
`Tested-by: Sungbo Eo <mans0n@gorani.run>`

**Comment by CHKDSK88** [comment]
@ynezz

I reworked big commit. Now is splitted into small pieces. 

I change default config and now EA3500 fit. But still wait my PR with device, which need new features of kernel.

**Comment by bobafetthotmail** [comment]
tested on pogoplug v4 and nsa310b

On the nsa 310b (it's using a realtek chipset for the ethernet) the lights in the ethernet port don't light up, but the ethernet port works and I can access luci web interface.

Tested-by: Alberto Bursi <alberto.bursi@outlook.it>

**Comment by ynezz** [comment]
> I reworked big commit. Now is splitted into small pieces.

Thanks, seems ready to me, anything else is blocking merge of this?

**Comment by adrianschmutzler** [comment]
Maybe just switch KERNEL_PATCHVER to 4.19 as well in the latest commit, and bury the 4.19 PR?

**Comment by CHKDSK88** [comment]
If we don't want work on 4.19 and it will be buried soon, my proposal is switch directly KERNEL_PATCHVER to 5.4 like mpc85xx. This target is almost pure mainline. It was tested on my Checkpoint L-50, @mans0n device and @bobafetthotmail 310b and pogoplug v4. Let give people chance to test it. In other case, 5.4 will be untested widely like 4.19 at this moment.

**Comment by ynezz** [comment]
> my proposal is switch directly KERNEL_PATCHVER to 5.4 like mpc85xx

Ok, fine with me, go ahead.

**Comment by ynezz** [comment]
Could you add the testing information (devices) and Tested-by tags as well? So I don't need to touch the commits myself, thanks.

**Comment by CHKDSK88** [comment]
Ready for merge?

**Comment by ynezz** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

**Comment by CHKDSK88** [comment]
@ynezz 

Something goes wrong. My patch goes without changed Makefile. If we want jump directly to 5.4, please use this patch:
https://github.com/CHKDSK88/openwrt-1/commit/db5a5153c1bcd3c5fb0fab1c2e5888339b6b2527

**Comment by CHKDSK88** [comment]
@mans0n @bobafetthotmail 

Are LEDs working?
Could You make ```ls /sys/class/leds/``` of Your devices? Are all LEDs missing?

**Pull request closed without merging**
