### PR TITLE
binutils: Use 2.31.1 by default

### PR DESCRIPTION
**Pull request by diizzyy**
Set binutils 2.31.1 as default

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile/Runtime tested on:
octeonplus, EdgeRouter Lite, OpenWrt master
kirkwood, iOmega iConnect, OpenWrt master
mvebu, Linksys WRT3200ACM, OpenWrt master
ramips, MQMaker WiTi board, OpenWrt master

Mailing list: https://lists.openwrt.org/pipermail/openwrt-devel/2018-August/013899.html

Old PR: https://github.com/openwrt/openwrt/pull/1297

**Review by pprindeville — APPROVED** [review]
LGTM

**Comment by diizzyy** [comment]
Compile/Runtime tested on: sunxi, OrangePi PC, OpenWrt master

@hauke  @dedeckeh 
Can you have a look at this?

**Comment by hauke** [comment]
Thank you for the pull request, it was applied to master.

**Pull request closed without merging**
