### PR TITLE
rockchip: backport upstream updates for nanopc t6

### PR DESCRIPTION
**Pull request by 1715173329**
Backport ir-receiver/minipcie/poweroff/spi/usb-c support and other minor fixes for the NanoPC T6 board.

### CODE REVIEW

**Comment by 1715173329** [comment]
cc @peterwillcn

**Comment by peterwillcn** [comment]
OF: graph: no port node found in /i2c@fec80000/typec-portc@22

**Review by peterwillcn — COMMENTED** [review]
[    2.551020] OF: graph: no port node found in /i2c@fec80000/typec-portc@22

**Comment by 1715173329** [comment]
> [ 2.551020] OF: graph: no port node found in /i2c@fec80000/typec-portc@22

It's expected currently.

**Review by peterwillcn — APPROVED** [review]

**Pull request merged**
