### PR TITLE
kernel: bump 5.10 to 5.10.77

### PR DESCRIPTION
**Pull request by rsalvaterra**
Deleted (upstreamed):
bcm53xx/patches-5.10/081-v5.15-Revert-pinctrl-bcm-ns-support-updated-DT-binding-as-.patch

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.10.y&id=01c2881bb0e0a71b87ca425e1b763ac13855aa7e

Run-tested:
ramips/mt7621 (Redmi AC2100)

Signed-off-by: Rui Salvaterra \<rsalvaterra@gmail.com\>

### CODE REVIEW

**Comment by graysky2** [comment]
Build system: x86_64
Build-tested: bcm2711/RPi4B
Run-tested: bcm2711/RPi4B

**Comment by rsalvaterra** [comment]
We really should be in touch in order not to duplicate work, @graysky2… 😉 It does match your result, I hope?

**Comment by jospezial** [comment]
https://www.kernel.org/category/releases.html
5.15 is the latest LTS Kernel. Does somebody want to add it to our targets?

**Comment by graysky2** [comment]
@rsalvaterra - Yes, matches.  https://github.com/graysky2/openwrt/commit/2f18325c0cd4fa916bf9b47ef437828af2a5e937

**Comment by rsalvaterra** [comment]
> https://www.kernel.org/category/releases.html 5.15 is the latest LTS Kernel. Does somebody want to add it to our targets?

Let's not get ahead of ourselves. I personally won't touch anything 5.15-related until all supported targets are at 5.10 (stable, not testing).

**Comment by hauke** [comment]
Thank you for the patch, I applied it to master.

**Pull request closed without merging**
