### PR TITLE
uClibc: bumb to 1.0.31

### PR DESCRIPTION
**Pull request by ghost**
I have updated uClibc-ng to 1.0.31 because there is outdated uClibc-ng (1.0.30). (Sorry about signing commit, I forgot about ```git commit --signoff```)

### CODE REVIEW

**Comment by dedeckeh** [comment]
The PR has formal issues, no SoB and no clear git commit description.
Please have a look at https://openwrt.org/submitting-patches

**Comment by protonesso** [comment]
so, this commit is good now?

**Comment by dedeckeh** [comment]
No; it has no SoB and no clear git commit description why you want this patch to be accepted

**Comment by protonesso** [comment]
please explain me what is "SoB"

**Comment by protonesso** [comment]
I will re-create pull request

**Comment by dedeckeh** [comment]
SoB means Signed-off-by; more info can be found on https://openwrt.org/submitting-patches

**Comment by protonesso** [comment]
Okay, thanks for info!

**Pull request closed without merging**
