### PR TITLE
Reapply "prereq-build: add Python 3.12 support"

### PR DESCRIPTION
**Pull request by aparcar**
This reverts commit 09b7e1955c92e0b05197174b7bd4aef2c4073a35.

### CODE REVIEW

**Comment by neheb** [comment]
Seems the distutils check needs fixing. Something like:

```
$(eval $(call TestHostCommand,python3-distutils, \
	Please install the Python3 distutils module, \
	$(STAGING_DIR_HOST)/bin/python3 -c "import sys; sys.version_info < (3, 12) and __import__('distutils.util')"
```

**Comment by aparcar** [comment]
@neheb do you have the time to figure it out?

**Comment by dhewg** [comment]
You could just reuse this patch from my closed PR if you want:
https://github.com/openwrt/openwrt/pull/11747/commits/8e3a1e21d35229cee6f2519db5e9a3eccb275e37

**Review by neheb — APPROVED** [review]

**Comment by stintel** [comment]
Can confirm, the following change on top of this PR fixes both the issue in my previous comment as the one where the build system picks up Python 3.11 even when 3.12 is the default version on my Gentoo system.

```diff
stijn@taz openwrt on  master +1 -1 ➜ git diff
diff --git a/include/prereq-build.mk b/include/prereq-build.mk
index e4ec409d08..8b138cfc44 100644
--- a/include/prereq-build.mk
+++ b/include/prereq-build.mk
@@ -201,7 +201,7 @@ $(eval $(call SetupHostCommand,python3,Please install Python >= 3.7, \

 $(eval $(call TestHostCommand,python3-distutils, \
        Please install the Python3 distutils module, \
-       echo 'from sys import version_info\nif version_info < (3, 12):\n\tfrom distutils import util' | \
+       printf 'from sys import version_info\nif version_info < (3, 12):\n\tfrom distutils import util' | \
                $(STAGING_DIR_HOST)/bin/python3 -))

 $(eval $(call TestHostCommand,python3-stdlib, \
```

**Comment by neheb** [comment]
@aparcar can we get @stintel 's change in?

**Comment by robimarko** [comment]
Yeah, that would be great so we can get this thing merged and actually check for Python 3.12

**Comment by aparcar** [comment]
Added, please merge at your own convenience.

**Comment by KanjiMonster** [comment]
I'm not very knowledgeable in regards to python, but do we need distutils or do we not? Because if everything works with python 3.12 without it, I would expect it to work fine with earlier python versions well, and then we can drop the prereq check for it completely.

If it is still needed for some packages, then preferring python 3.11 over 3.12 sounds like a good idea, even if 3.12 is a default.

Just disabling the prereq check for 3.12 feels wrong, especially with no explanation why we are fine without it. This just hides the (potential?) issue, and just defers failures to later.

**Comment by aparcar** [comment]
Afaik some tool needed it but I don't have the time to debug this right now

**Comment by KanjiMonster** [comment]
> Afaik some tool needed it but I don't have the time to debug this right now

If there are still things depending on it, then this should be part of the commit message, ideally pointing out what still needs it. No need to fix it, just mention what's broken (and maybe open an issue about it, if there isn't).

**Comment by KanjiMonster** [comment]
Also the first revert commit is missing at least a short "why" (it is okay now).

**Comment by hauke** [comment]
This was done in bf059f7108e75fdec618a272ab8c52d4780aafed and 8191c8980f04087eaf2921dc327fff219999bd55.

**Pull request closed without merging**
