### PR TITLE
omap: fix squashfs and add sysupgrade

### PR DESCRIPTION
**Pull request by lucize**
@lynxis please review this

fixes FS#1034
tested on beaglebone black
added sysupgrade support
disable unsupported ubifs

### CODE REVIEW

**Comment by lucize** [comment]
sysupgrade is pending
the dts name doesn't match the image name, trying to fix it without a patch to dts file

```
Device ti,am335x-bone-black not supported by this image
Supported devices: am335x-boneblack
Image check 'fwtool_check_image' failed.

```

**Comment by lucize** [comment]
@nbd168 can we have this ready for the next stable ?

**Comment by mkresin** [comment]
Please don't add `target/linux/omap/base-files/lib/omap.sh`. It is legacy stuff and not required for targets using the devicetree.

The version you had before was already correct, just the SUPPORTED_DEVICES was missing within the image build code.

**Comment by mkresin** [comment]
The following _untested_ patch instead of "omap: fix board detect for sysupgrade" should do the trick:

```patch
diff --git a/package/boot/uboot-omap/Makefile b/package/boot/uboot-omap/Makefile
index 0d5260d..83329ec 100644
--- a/package/boot/uboot-omap/Makefile
+++ b/package/boot/uboot-omap/Makefile
@@ -24,17 +24,17 @@ endef
 
 define U-Boot/omap4_panda
   NAME:=Pandaboard
-  BUILD_DEVICES:=omap4-panda
+  BUILD_DEVICES:=ti_omap4-panda
 endef
 
 define U-Boot/am335x_boneblack
   NAME:=TI AM335x BeagleBone Black
-  BUILD_DEVICES:=am335x-boneblack
+  BUILD_DEVICES:=ti_am335x-bone-black
 endef
 
 define U-Boot/am335x_evm
   NAME:=AM335x EVM
-  BUILD_DEVICES:=am335x-evm
+  BUILD_DEVICES:=ti_am335x-evm
 endef
 
 define U-Boot/omap3_overo
@@ -43,7 +43,7 @@ endef
 
 define U-Boot/omap3_beagle
   NAME:=BeagleBoard
-  BUILD_DEVICES:=omap3-beagle
+  BUILD_DEVICES:=ti_omap3-beagle
 endef
 
 UBOOT_TARGETS:=omap4_panda am335x_evm omap3_overo omap3_beagle am335x_boneblack
diff --git a/target/linux/omap/image/Makefile b/target/linux/omap/image/Makefile
index 2f1e5b5..c7271ab 100644
--- a/target/linux/omap/image/Makefile
+++ b/target/linux/omap/image/Makefile
@@ -38,34 +38,34 @@ define Device/Default
   KERNEL := kernel-bin
   IMAGES := sdcard.img.gz
   IMAGE/sdcard.img.gz := omap-sdcard | append-metadata | gzip
-  SUPPORTED_DEVICES = $$(DEVICE_DTS)
+  SUPPORTED_DEVICES = $(subst _,$(comma),$(1))
 endef
 
 #uboot-omap-am335x_evm uboot-omap-omap3_beagle uboot-omap-omap3_overo uboot-omap-omap4_panda
 
-define Device/am335x-evm
+define Device/ti_am335x-evm
   DEVICE_TITLE := TI AM335x EVM
   DEVICE_DTS := am335x-evm
 endef
 
-TARGET_DEVICES += am335x-evm
+TARGET_DEVICES += ti_am335x-evm
 
-define Device/am335x-boneblack
+define Device/ti_am335x-bone-black
   DEVICE_TITLE := TI AM335x BeagleBone Black
   DEVICE_DTS := am335x-boneblack
 endef
 
-TARGET_DEVICES += am335x-boneblack
+TARGET_DEVICES += ti_am335x-bone-black
 
-define Device/omap4-panda
+define Device/ti_omap4-panda
   DEVICE_TITLE := OMAP4 TI pandaboard
   DEVICE_DTS := omap4-panda
   DEVICE_PACKAGES := kmod-usb-net-smsc95xx
 endef
 
-TARGET_DEVICES += omap4-panda
+TARGET_DEVICES += ti_omap4-panda
 
-define Device/omap3-beagle
+define Device/ti_omap3-beagle
   DEVICE_TITLE := OMAP3 TI beagleboard
   DEVICE_DTS := omap3-beagle
   # beagleboard doesn't have a network interface, support most common usb net
@@ -75,6 +75,6 @@ define Device/omap3-beagle
 	kmod-usb-net-smsc95xx kmod-usb-net-dm9601-ether
 endef
 
-TARGET_DEVICES += omap3-beagle
+TARGET_DEVICES += ti_omap3-beagle
 
 $(eval $(call BuildImage))
```

**Comment by lucize** [comment]
@mkresin thanks, it's working because my first approach was like yours but I was looking at some of the targets like arc and at91 so I thought that this is the less intrusive way

Regards

**Comment by lucize** [comment]
@lynxis ping

**Comment by lucize** [comment]
@mkresin can we have this for stable ?

**Comment by mkresin** [comment]
You should really split the changes into multi commits. Maybe something like that:

- sync metadata and user space boardname (and change the uboot BUILD_DEVICES variable to reflect the changed device names)
- switch from ubifs to squashfs (why?)
- add support for sysupgrade (are the new default packages related to sysupgrade support)

I've no idea what the reason for the kernel config changes is. I've no idea what kind of storage device for the omap boards is used. The nand feature would suggests something like nand flash, but the images are named sdcard.img.gz. I remember that squashfs support was recently added for the different Raspberry Pi. Maybe you should cross check how it was done there.

I'll not commit the PR, as I 've no knowledge about the hardware. But following my suggestions might attract a dev who knows about omap.

I'm quite sure one of the reason why nobody takes care of the PR is the lack of a propper commit message. For most of the changes I've no idea why they are required.

Good commit messages serve at least three important purposes:

 - To speed up the reviewing process.
 - To help us write a good release note.
 - To help the future maintainers, say five years into the future, to find out why a particular change was made to the code or why a specific feature was added.

A good commit message should answer three questions about a patch:

 - Why is it necessary? It may fix a bug, it may add a feature, it may improve performance, reliabilty, stability, or just be a change for the sake of correctness.
 - How does it address the issue? For short obvious patches this part can be omitted, but it should be a high level description of what the approach was.
 - What effects does the patch have? (In addition to the obvious ones, this may include benchmarks, side effects, etc.)

**Comment by lucize** [comment]
@mkresin is this ok now ?

**Comment by lynxis** [comment]
@lucize let's bring this first into trunk/master, but I agree with you, this should go to 18.06 if squashfs/ubifs is broken.

Can you split **omap: add sysupgrade support** into two patches. The first one is doing the renaming of ti, the second one is adding the move config platform.

PS: Sorry, your PR fall under table somehow, because I'm was quite busy lately.

@mkresin omap support emmc, sdcard and AFAIR nand, spi as well. But my targets all are emmc or sdcard.

**Comment by lucize** [comment]
@lynxis @mkresin made the changes

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
