### PR TITLE
mvebu/uDPU: run through shellcheck

### PR DESCRIPTION
**Pull request by neheb**
Should make the script overall faster. I doubt by much.

As I don't have any hardware to test with, ping @BKPepe @dhewg @v-vid

### CODE REVIEW

**Comment by BKPepe** [comment]
I don't have uDPU to test it on, I am so sorry. :(

**Comment by neheb** [comment]
hmm? Is it not related to the Turris MOX?

**Comment by BKPepe** [comment]
uDPU is using the same SoC as Turris MOX and Marvell ESPRESSObin, which is Marvell Armada 3720, but Turris MOX is not using any of these functions you changed.

**Comment by neheb** [comment]
@robimarko any thoughts?

**Comment by robimarko** [comment]
Finally got around to trying it, as far as I can tell it works fine, sysupgraded without an issue.

**Comment by neheb** [comment]
ping @Ansuel

**Comment by neheb** [comment]
ping @hauke

**Pull request merged**
