### PR TITLE
[22.03] ethtool: backport the latest version from master

### PR DESCRIPTION
**Pull request by BKPepe**
Turris OS is trying to migrate from EoL OpenWrt 21.02 (Turris OS 5.x) to OpenWrt 22.03 (Turris OS 6.x), and it was reported by @oskar456 that ethtool is different, and I think I can even say that it is semi-functional right now in OpenWrt 22.03 because they changed backend from ioctl to netlink [1], thus it is missing a lot of important details [2]. 

[1] https://forum.turris.cz/t/turris-os-7-0-is-in-rc/19755/59?u=pepe (details and compile and test verification that the version from OpenWrt master branch works)
[2] https://forum.turris.cz/t/turris-os-7-0-is-in-rc/19755/45?u=pepe (bugreport)

Ping: @PolynomialDivision 

Similar PR for OpenWrt 23.05 will be created shortly. My intention is to have the same ethtool version across all OpenWrt supported branches.

### CODE REVIEW

**Comment by ynezz** [comment]
> Turris OS is trying to migrate from EoL OpenWrt 21.02 (Turris OS 5.x) to OpenWrt 22.03 (Turris OS 6.x)

BTW  22.03 have projected EOL to 4/2024.

> My intention is to have the same ethtool version across all OpenWrt supported branches.

Isn't the intention of the stable branches, to have them somehow stable?

This problem doesn't really exist in OpenWrt, since nobody cared to report it yet (or its so minor/subjective, not even worth the effort?). There might be a less invasive fix for the existing ethtool version in 22.03, so I would recommend to first get down to the root of the problem instead of this brute force approach, which screams regressions.

```
$ git diff --stat v5.16..v6.6 | grep changed
 67 files changed, 6031 insertions(+), 269 deletions(-)
```

**Comment by BKPepe** [comment]
> BTW 22.03 have projected EOL to 4/2024.

That's their choice, though. I can not do anything with that. Users are telling Turris OS developers that it will be EoL and that they should rather move to OpenWrt 23.05.

> Isn't the intention of the stable branches, to have them somehow stable?

I can ask the same question. Isn't there an intention to have a working ethtool in all OpenWrt versions? 🤔 What if anything happens in some old version, etc? I know and understand that you would like to avoid introducing new regressions, but this was quick and fast what I could do. We can discuss if your proposed invasive fix is better, but that is up to Turris OS developers or, rather, Turris OS maintainers to look at it further and backport whatever works for ethtool. Updating ethtool was the easiest thing to do because the latest version is tested, and confirmed to be working, and having it in all branches without introducing new surprises for users might be one thing to consider it. 

Most likely, Turris OS will do the same like me with backport, but do we want to have OpenWrt and Turris OS diverged so much and keep it rather downstream instead of cooperating by each other? Of course, there might not be many routers with SFP cage supported in OpenWrt, but there is one and that's Turris Omnia. I could raise the issue here, but with currently more than 2000 opened issues, I doubt that anyone would look into it.

**Comment by hauke** [comment]
NACK from my side. 

I agree with @ynezz . We should not update package to more recent major versions in the stable branch without real reasons.

The legacy ethtool interface supports the features we are using in this old version.

**Comment by BKPepe** [comment]
> We should not update package to more recent major versions in the stable branch without real reasons.

I think that in the OP, I tried to describe the reason for updating it. To sum it up:

- OpenWrt 21.02 have working perfectly fine version for ethtool.
Then it was upgraded in OpenWrt 22.03, no one noticed it or no one is using SFP and upstream changed something. Oops! So, the version in OpenWrt 22.03 does not provide the same features and functions, which was in OpenWrt 21.02. That's called regression after all. Should I create an issue here for OpenWrt 22.03 version that ethtool is not working? Sure, I could do that. Will you look at it? I doubt it, since as it was pointed out. EoL will be really soon.

- Another reason is that if we do have the latest version, then we will get support from upstream developers, and we do not need to provide a modified version of ethtool that no one will look into it as upstream developers will just say - upgrade it to the latest version and let's see if it is improved over there. Also, Turris guys could fix them for themselves, leave it broken in upstream (OpenWrt in this case) and play on their own playground. I thought that downstream should cooperate with upstream.

References are in the OP, so I am not going to point them out ehre here in my response.

**Comment by ynezz** [comment]
Different projects come with their own set of objectives, preferences, and guidelines. Below, I have provided the rules and preferences specific to the OpenWrt project for your reference. These are what reviewers and maintainers are expected to adhere to. This implies that a method of addressing a bug that might be appropriate for one project may not necessarily be considered suitable for another. 

## [Release branches](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#release-branches)

* Please ONLY cherry-pick or commit security and bug-fixes to these branches.
* Do NOT add new packages and do NOT do major upgrades of packages here.

## [Patch backports](https://openwrt.org/submitting-patches#patch_backports)

Backporting refers to applying changes to a stable (release) branch like for example `openwrt-23.05` from the main branch. Since new features are not added to stable branches, backported changes are generally bug fixes and security fixes only.

**Comment by ynezz** [comment]
Lets try to find a less invasive and reviewable fix, thanks.

**Pull request closed without merging**
