### PR TITLE
bcm63xx: alloc RX SKB with NET_IP_ALIGN

### PR DESCRIPTION
**Pull request by spliew89**
Use netdev_alloc_skb_ip_align on newer SoC when refilling RX. Increases packet
processing performance by 30%.

Tested on BCM6328 320 MHz and iperf3 -M 512 to measure packet/sec performance.

Before:
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-30.00  sec   120 MBytes  33.7 Mbits/sec  277             sender
[  4]   0.00-30.00  sec   120 MBytes  33.5 Mbits/sec                  receiver

After:
[  4]   0.00-30.00  sec   155 MBytes  43.3 Mbits/sec  354             sender
[  4]   0.00-30.00  sec   154 MBytes  43.1 Mbits/sec                  receiver

### CODE REVIEW

**Comment by spliew89** [comment]
I've just found a possible bug.
On BCM6333 with modified bcm_enet_probe function to enable MDIO-GPIO connected b53 switch, networking cease to function.
I'm not sure if it's just me. I don't have other devices to test with. Maybe someone with older BCM63xx devices can test this commit.

**Comment by spliew89** [comment]
I've fixed the bug by checking enet_is_sw flag and then dispatching to the correct alloc function.

**Comment by spliew89** [comment]
With the latest commit, bulk alloc is replaced by netdev alloc with NET_IP_ALIGN.
The performance increase still stands but with a clearer view on what causes it.
This changes the original context considerably, so please let me know if a new PR is required.

**Comment by Noltari** [comment]
Merged, thanks!
https://github.com/openwrt/openwrt/commit/ba74da5b99a1e8239af896378fbbc68f8761cd15

**Pull request closed without merging**
