### PR TITLE
lantiq: add linux 6.6 support

### PR DESCRIPTION
**Pull request by sch-m**
@hauke
@PolynomialDivision 

This adds support for kernel 6.6 for the lantiq target.

I've only done a few tests with an xrx200 (VRX268; no voice) target so far.

@kestrel1974 Can you please take a look at the fix for the ltq-deu driver. I'm currently not quite sure about the be128.

### CODE REVIEW

**Comment by mrkiko** [comment]
Mark to follow.

**Comment by nouman8** [comment]
@sch-m tested on bt-hh5a wifi and vdsl are working.
Thank you for the hard work.

**Comment by PolynomialDivision** [comment]
Why still WIP? I would also already pull the first commit into the main if that is fine.

**Comment by sch-m** [comment]
> Why still WIP? I would also already pull the first commit into the main if that is fine.

OK, I've removed the WIP. I would still appreciate a little feedback from @kestrel1974 about the DEU patch.

In my opinion, the step from 5.15 to 6.1 (1st commit) can already be made.

**Comment by kestrel1974** [comment]
@sch-m I would need to run the cipher tests again with a kernel 6.6 environment. I guess the change is good, since there is no other change. Looking into the patch that removed u128_xor, le128_xor and be128_xor seem to be identical.

**Comment by sch-m** [comment]
@kestrel1974 OK, thanks for your feedback.

@PolynomialDivision Also thank you. I'm not at my workplace this week. I'll do that next week.

**Comment by khanjui** [comment]
WARNING: Image file /builder/shared-workdir/build/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/zyxel_p-2812hnu-f3-kernel.bin is too big: 3162850 > 2097152

Happens after 6.1

**Comment by sch-m** [comment]
> WARNING: Image file /builder/shared-workdir/build/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/zyxel_p-2812hnu-f3-kernel.bin is too big: 3162850 > [2097152](https://github.com/openwrt/openwrt/commit/20971520aab4e680610b116c74925b4891cffc76)
> 
> Happens after 6.1

Well, the kernel image for this device has been too large for some time now. See commit 6f5c27edd4f5

**Comment by khanjui** [comment]
> > WARNING: Image file /builder/shared-workdir/build/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/zyxel_p-2812hnu-f3-kernel.bin is too big: 3162850 > [2097152](https://github.com/openwrt/openwrt/commit/20971520aab4e680610b116c74925b4891cffc76)
> > Happens after 6.1
> 
> Well, the kernel image for this device has been too large for some time now. See commit [6f5c27e](https://github.com/openwrt/openwrt/commit/6f5c27edd4f5b51c5b2287f2b3e0cb67ec73e693)

[Buildbot fails on xrx200](https://buildbot.openwrt.org/images/#/builders/13/builds/235) and I'm currently not able to compile it by myself so I couldn't test the new kernel.

**Comment by sch-m** [comment]
> [Buildbot fails on xrx200](https://buildbot.openwrt.org/images/#/builders/13/builds/235) and I'm currently not able to compile it by myself so I couldn't test the new kernel.

I think the real problem is this one:

WARNING: Image file /builder/shared-workdir/build/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/zyxel_p-2812hnu-f1-kernel.bin is too big: 3162864 > 3145728

Maybe we should set the Zyxel P-2812HNU-F1 DEFAULT:=n as well?

**Comment by uyguremre** [comment]
I checkted out the main branch an hour ago, compiled for homehub 5a and installed sysupgrade over v22.03.6. Wireless ssid advertised as in my previous configuration but could not connect to wireless and wired network was showing cable unplugged. I reset with the router reset button, then connected with ssh and had to redo all adsl and wireless configuration and install luci but everything is working fine now. 
Firmware Version OpenWrt SNAPSHOT r26438-32e4c50d24 / LuCI Master 24.135.65178~2bb1e06
Kernel Version	6.1.89

**Comment by sch-m** [comment]
@PolynomialDivision I've rebased the commits once again.

**Comment by hauke** [comment]
Thank you, I applied the patches to main branch in e85c80edcbb990e00537dc67694942390bff7108, 5b522e49690f4e16e035517bc5a826b62122a36c, c80fa584e5852b6973fe465cb2dc1827ec3e3aec, 6ec7711d00b123e1c2c0dd731ac0763d7c4b50b7, c7648273d08daba9a51c3130004fba8d106af538, , 10f8a14eca521801add807bd4491323ce53cf59a, 45eeedbbfc805a26df2c0a0b9c6edca51a4a0895 and abf1c4e67dae8d7f73fd3a964192d7ede87fa4f8.

**Pull request closed without merging**
