### PR TITLE
mpc85xx: p2020: fix cfi-nor detection and add testing 5.10 kernel

### PR DESCRIPTION
**Pull request by CHKDSK88**
At this moment p2020rdb has broken images, because NOR memory connected to eLBC bus isn't detected.

In 642b1e8dbed7 linux tree commit, config dependencies of MTD_PHYSMAP_OF was changed and now MTD_PHYSMAP is required.

This patch adds MTD_PHYSMAP option to kernel config in p2020 subtarget and fix booting of p2020rdb.
    
Fixes: 13b1db795f05 ("mpc85xx: add support for kernel 5.4")
    
    Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>

### CODE REVIEW

**Comment by adschm** [comment]
I picked the config refresh for now until somebody will review the actual thing.

**Comment by CHKDSK88** [comment]
Rebased to current master

**Comment by CHKDSK88** [comment]
@blocktrron 

Please look at this.

**Comment by hauke** [comment]
Thank you for the pull request, it was added to master.
Should 76649fd06d454f1b93f2ee74951ef91225155a8c also be backported to 21.02?

**Comment by CHKDSK88** [comment]
@hauke

Yes this patch should be backported.

**Pull request closed without merging**
