### PR TITLE
[19.07] ramips: use tpt DTS trigger for TP-Link TL-MR3020 v3 and TL-WA801ND v5

### PR DESCRIPTION
**Pull request by nalxnet**
cherry picked commit 20eb45da4fc19c12ea2073471992eeaf9d602fa5 from master to 19.07

I'm integrating the TL-MR3020 v3 into gluon, which is based on 19.07.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
I'm not sure whether tpt trigger on mt7628 is supported in 19.07.

**Comment by nalxnet** [comment]
tpt trigger is already used for the WLAN LED of the TP-Link TL-WA801ND v5 in 19.07, I'm just moving the definition to the DTS here. This device also uses the mt7628 and I can confirm that the WLAN LED works there (did the gluon integration for these 2 weeks ago).

**Comment by adrianschmutzler** [comment]
@nalxnet You are right, and I was talking nonsense. I will backport this to 19.07 tomorrow or on Saturday. (It's always good to have stuff in master first for a few days to allow people to complain).

Can I add a comment that you tested on TL-WA801ND v5/19.07?

**Comment by nalxnet** [comment]
> @nalxnet You are right, and I was talking nonsense. I will backport this to 19.07 tomorrow or on Saturday. (It's always good to have stuff in master first for a few days to allow people to complain).

Sure, no need to rush.

> Can I add a comment that you tested on TL-WA801ND v5/19.07?

I can only confirm that the phy0tpt trigger works for the TL-WA801ND v5 on 19.07 at this point. If that is enough then please go ahead.
Regarding these precise changes, I will do another build, test it for both devices later today and post the results here.

**Comment by nalxnet** [comment]
@adrianschmutzler all tests successful, both TL-WA801ND v5 and TL-MR3020 v3 here have happily blinking WLAN LEDs.

**Comment by blocktrron** [comment]
Merged, thanks!

**Pull request closed without merging**
